ECCE @ EIC Software: G4SimpleIntegration Class Reference
G4SimpleIntegration Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4SimpleIntegration.hh>
Public Member Functions
G4SimpleIntegration (function pFunction)
G4SimpleIntegration (function pFunction, G4double pTolerance)
~G4SimpleIntegration ()
G4double Trapezoidal (G4double xInitial, G4double xFinal, G4int iterationNumber)
G4double MidPoint (G4double xInitial, G4double xFinal, G4int iterationNumber)
G4double Gauss (G4double xInitial, G4double xFinal, G4int iterationNumber)
G4double Simpson (G4double xInitial, G4double xFinal, G4int iterationNumber)
G4double AdaptGaussIntegration (G4double xInitial, G4double xFinal)
Protected Member Functions
G4double Gauss (G4double xInitial, G4double xFinal)
void AdaptGauss (G4double xInitial, G4double xFinal, G4double &sum, G4int &depth)
Private Member Functions
G4SimpleIntegration (const G4SimpleIntegration &)
G4SimpleIntegration & operator= (const G4SimpleIntegration &)
Private Attributes
function fFunction
G4double fTolerance
const G4int fMaxDepth
Detailed Description
Definition at line 63 of file G4SimpleIntegration.hh.
View newest version in sPHENIX GitHub at line 63 of file G4SimpleIntegration.hh
Constructor & Destructor Documentation
G4SimpleIntegration::G4SimpleIntegration (function pFunction) explicit
Definition at line 35 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 35 of file G4SimpleIntegration.cc
G4SimpleIntegration::G4SimpleIntegration (function pFunction, G4double pTolerance)
Definition at line 42 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 42 of file G4SimpleIntegration.cc
G4SimpleIntegration::~G4SimpleIntegration ()
Definition at line 51 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 51 of file G4SimpleIntegration.cc
G4SimpleIntegration::G4SimpleIntegration (const G4SimpleIntegration &) private
Member Function Documentation
void G4SimpleIntegration::AdaptGauss (G4double xInitial, G4double xFinal, G4double & sum, G4int & depth) protected
Definition at line 159 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 159 of file G4SimpleIntegration.cc
References FatalException, fMaxDepth, fTolerance, G4Exception(), and Gauss().
Referenced by AdaptGaussIntegration().
G4double G4SimpleIntegration::AdaptGaussIntegration (G4double xInitial, G4double xFinal)
Definition at line 133 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 133 of file G4SimpleIntegration.cc
References AdaptGauss(), and sum.
G4double G4SimpleIntegration::Gauss (G4double xInitial, G4double xFinal, G4int iterationNumber)
Definition at line 90 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 90 of file G4SimpleIntegration.cc
References Acts::Test::delta, fFunction, and x.
Referenced by AdaptGauss().
G4double G4SimpleIntegration::Gauss (G4double xInitial, G4double xFinal) protected
Definition at line 144 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 144 of file G4SimpleIntegration.cc
References Acts::Test::delta, fFunction, and sum.
G4double G4SimpleIntegration::MidPoint (G4double xInitial, G4double xFinal, G4int iterationNumber)
Definition at line 74 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 74 of file G4SimpleIntegration.cc
References fFunction, and x.
G4SimpleIntegration& G4SimpleIntegration::operator= (const G4SimpleIntegration &) private
G4double G4SimpleIntegration::Simpson (G4double xInitial, G4double xFinal, G4int iterationNumber)
Definition at line 108 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 108 of file G4SimpleIntegration.cc
References fFunction, sum, and x.
G4double G4SimpleIntegration::Trapezoidal (G4double xInitial, G4double xFinal, G4int iterationNumber)
Definition at line 58 of file G4SimpleIntegration.cc.
View newest version in sPHENIX GitHub at line 58 of file G4SimpleIntegration.cc
References fFunction, and x.
Member Data Documentation
function G4SimpleIntegration::fFunction private
Definition at line 114 of file G4SimpleIntegration.hh.
View newest version in sPHENIX GitHub at line 114 of file G4SimpleIntegration.hh
Referenced by Gauss(), MidPoint(), Simpson(), and Trapezoidal().
const G4int G4SimpleIntegration::fMaxDepth private
Definition at line 116 of file G4SimpleIntegration.hh.
View newest version in sPHENIX GitHub at line 116 of file G4SimpleIntegration.hh
Referenced by AdaptGauss().
G4double G4SimpleIntegration::fTolerance private
Definition at line 115 of file G4SimpleIntegration.hh.
View newest version in sPHENIX GitHub at line 115 of file G4SimpleIntegration.hh
Referenced by AdaptGauss().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4SimpleIntegration.hh
geant4/tree/geant4-10.6-release/source/global/HEPNumerics/src/G4SimpleIntegration.cc