ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/berger/berger.C File Reference
berger.C File Reference
Functions
in open ("./EGSnrc/100keV-DPK.ascii")
for (int i=0;i< nbdata;i++)
in close ()
h1d SetTitle ("Dose point kernel : energy deposition profile, e- 100 keV")
h1d GetXaxis () -> SetTitle("d(E/E0)/d(r/r0) along r/r0 r/r0")
h1d GetYaxis () -> SetTitle("DPK")
h1d SetStats (kFALSE)
h1d SetLineColor (kRed)
h1d Draw ("L")
TFile f1 ("./100keV_local.root")
h1 SetLineColor (kBlack)
h1 Draw ("SAME HIST")
legend AddEntry (h1,"local ","l")
legend AddEntry (h1d,"EGSnrc","l")
legend Draw ()
Variables
ifstream in
double x_min = 0
double x_max = 1.2
int nbdata = 0
TH1D * h1d = new TH1D("h1d","",nbdata,x_min,x_max)
Double_t x
Double_t y
TH1D * h1 = (TH1D*) f1.Get("8")
TLegend * legend = new TLegend(0.7,0.6,0.86,0.78)
Function Documentation
legend AddEntry (h1 , "local " , "l")
legend AddEntry (h1d , "EGSnrc" , "l")
legend->AddEntry(h2,"liver ","l"); legend->AddEntry(h3,"penel","l");
in close ()
h1d Draw ("L")
h3 Draw ("SAME HIST")
legend Draw ()
TFile f1 ("./100keV_local.root")
for ()
Definition at line 24 of file berger.C.
View newest version in sPHENIX GitHub at line 24 of file berger.C
References y.
h1d GetXaxis () -> SetTitle("d(E/E0)/d(r/r0) along r/r0 r/r0")
h1d GetYaxis () -> SetTitle("DPK")
in open ("./EGSnrc/100keV-DPK.ascii")
h14 SetLineColor (kRed)
h1 SetLineColor (kBlack)
h1d SetStats (kFALSE)
h1d SetTitle ("Dose point kernel : energy deposition profile, e-100 keV")
Variable Documentation
TH1D* h1 = (TH1D*) f1.Get("8")
Definition at line 42 of file berger.C.
View newest version in sPHENIX GitHub at line 42 of file berger.C
TH1D* h1d = new TH1D("h1d","",nbdata,x_min,x_max)
Definition at line 21 of file berger.C.
View newest version in sPHENIX GitHub at line 21 of file berger.C
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4ToolsAnalysisManager::PlotImpl(), G4XmlAnalysisReader::ReadH1Impl(), G4CsvAnalysisReader::ReadH1Impl(), and Fun4AllHistoManager::registerHisto().
ifstream in
Initial value:
{
   gROOT->Reset()
Definition at line 1 of file berger.C.
View newest version in sPHENIX GitHub at line 1 of file berger.C
TLegend* legend = new TLegend(0.7,0.6,0.86,0.78)
Definition at line 57 of file berger.C.
View newest version in sPHENIX GitHub at line 57 of file berger.C
in nbdata = 0
Definition at line 18 of file berger.C.
View newest version in sPHENIX GitHub at line 18 of file berger.C
Double_t x
Definition at line 23 of file berger.C.
View newest version in sPHENIX GitHub at line 23 of file berger.C
double x_max = 1.2
Definition at line 16 of file berger.C.
View newest version in sPHENIX GitHub at line 16 of file berger.C
Referenced by TpcSpaceChargeReconstructionHelper::copy_histogram().
double x_min = 0
Definition at line 15 of file berger.C.
View newest version in sPHENIX GitHub at line 15 of file berger.C
Referenced by TpcSpaceChargeReconstructionHelper::copy_histogram().
Double_t y
Definition at line 23 of file berger.C.
View newest version in sPHENIX GitHub at line 23 of file berger.C