ECCE @ EIC Software: G4P1Messenger Class Reference
G4P1Messenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4P1Messenger.hh>
Public Member Functions
G4P1Messenger (G4VAnalysisManager *manager)
virtual ~G4P1Messenger ()
virtual void SetNewValue (G4UIcommand *command, G4String value) final
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void CreateP1Cmd ()
void SetP1Cmd ()
Private Attributes
G4VAnalysisManager * fManager
Associated class.
std::unique_ptr
< G4AnalysisMessengerHelper > fHelper
std::unique_ptr< G4UIdirectory > fDirectory
std::unique_ptr< G4UIcommand > fCreateP1Cmd
std::unique_ptr< G4UIcommand > fSetP1Cmd
std::unique_ptr< G4UIcommand > fSetP1XCmd
std::unique_ptr< G4UIcommand > fSetP1YCmd
std::unique_ptr< G4UIcommand > fSetP1TitleCmd
std::unique_ptr< G4UIcommand > fSetP1XAxisCmd
std::unique_ptr< G4UIcommand > fSetP1YAxisCmd
std::unique_ptr< G4UIcommand > fSetP1XAxisLogCmd
std::unique_ptr< G4UIcommand > fSetP1YAxisLogCmd
G4int fXId
G4AnalysisMessengerHelper::BinData fXData
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 45 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 45 of file G4P1Messenger.hh
Constructor & Destructor Documentation
G4P1Messenger::G4P1Messenger (G4VAnalysisManager * manager) explicit
Definition at line 42 of file G4P1Messenger.cc.
View newest version in sPHENIX GitHub at line 42 of file G4P1Messenger.cc
References CreateP1Cmd(), fDirectory, fHelper, fSetP1TitleCmd, fSetP1XAxisCmd, fSetP1XAxisLogCmd, fSetP1XCmd, fSetP1YAxisCmd, fSetP1YAxisLogCmd, fSetP1YCmd, and SetP1Cmd().
G4P1Messenger::~G4P1Messenger () virtual
Definition at line 72 of file G4P1Messenger.cc.
View newest version in sPHENIX GitHub at line 72 of file G4P1Messenger.cc
Member Function Documentation
void G4P1Messenger::CreateP1Cmd () private
Definition at line 80 of file G4P1Messenger.cc.
View newest version in sPHENIX GitHub at line 80 of file G4P1Messenger.cc
References fCreateP1Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4P1Messenger().
void G4P1Messenger::SetNewValue (G4UIcommand * command, G4String value) final virtual
Reimplemented from G4UImessenger.
Definition at line 242 of file G4P1Messenger.cc.
View newest version in sPHENIX GitHub at line 242 of file G4P1Messenger.cc
References G4UIcommand::ConvertToBool(), G4UIcommand::ConvertToInt(), G4VAnalysisManager::CreateP1(), fCreateP1Cmd, fHelper, fManager, G4AnalysisMessengerHelper::BinData::fNbins, G4AnalysisMessengerHelper::BinData::fSbinScheme, fSetP1Cmd, fSetP1TitleCmd, fSetP1XAxisCmd, fSetP1XAxisLogCmd, fSetP1XCmd, fSetP1YAxisCmd, fSetP1YAxisLogCmd, fSetP1YCmd, G4AnalysisMessengerHelper::BinData::fSfcn, G4AnalysisMessengerHelper::ValueData::fSfcn, G4AnalysisMessengerHelper::BinData::fSunit, G4AnalysisMessengerHelper::ValueData::fSunit, G4AnalysisMessengerHelper::BinData::fVmax, G4AnalysisMessengerHelper::ValueData::fVmax, G4AnalysisMessengerHelper::BinData::fVmin, G4AnalysisMessengerHelper::ValueData::fVmin, fXData, fXId, G4UIcommand::GetParameterEntries(), G4Analysis::GetUnitValue(), Dataset::parameters, G4VAnalysisManager::SetP1(), G4VAnalysisManager::SetP1Title(), G4VAnalysisManager::SetP1XAxisIsLog(), G4VAnalysisManager::SetP1XAxisTitle(), G4VAnalysisManager::SetP1YAxisIsLog(), G4VAnalysisManager::SetP1YAxisTitle(), title(), G4Analysis::Tokenize(), and xaxis.
void G4P1Messenger::SetP1Cmd () private
Definition at line 165 of file G4P1Messenger.cc.
View newest version in sPHENIX GitHub at line 165 of file G4P1Messenger.cc
References fSetP1Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4P1Messenger().
Member Data Documentation
std::unique_ptr<G4UIcommand> G4P1Messenger::fCreateP1Cmd private
Definition at line 62 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4P1Messenger.hh
Referenced by CreateP1Cmd(), and SetNewValue().
std::unique_ptr<G4UIdirectory> G4P1Messenger::fDirectory private
Definition at line 60 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 60 of file G4P1Messenger.hh
Referenced by G4P1Messenger().
std::unique_ptr<G4AnalysisMessengerHelper> G4P1Messenger::fHelper private
Definition at line 59 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 59 of file G4P1Messenger.hh
Referenced by G4P1Messenger(), and SetNewValue().
G4VAnalysisManager* G4P1Messenger::fManager private
Associated class.
Definition at line 58 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 58 of file G4P1Messenger.hh
Referenced by SetNewValue().
std::unique_ptr<G4UIcommand> G4P1Messenger::fSetP1Cmd private
Definition at line 63 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4P1Messenger.hh
Referenced by SetNewValue(), and SetP1Cmd().
std::unique_ptr<G4UIcommand> G4P1Messenger::fSetP1TitleCmd private
Definition at line 66 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4P1Messenger.hh
Referenced by G4P1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P1Messenger::fSetP1XAxisCmd private
Definition at line 67 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4P1Messenger.hh
Referenced by G4P1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P1Messenger::fSetP1XAxisLogCmd private
Definition at line 69 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4P1Messenger.hh
Referenced by G4P1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P1Messenger::fSetP1XCmd private
Definition at line 64 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4P1Messenger.hh
Referenced by G4P1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P1Messenger::fSetP1YAxisCmd private
Definition at line 68 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4P1Messenger.hh
Referenced by G4P1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P1Messenger::fSetP1YAxisLogCmd private
Definition at line 70 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4P1Messenger.hh
Referenced by G4P1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4P1Messenger::fSetP1YCmd private
Definition at line 65 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4P1Messenger.hh
Referenced by G4P1Messenger(), and SetNewValue().
G4AnalysisMessengerHelper::BinData G4P1Messenger::fXData private
Definition at line 73 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4P1Messenger.hh
Referenced by SetNewValue().
G4int G4P1Messenger::fXId private
Definition at line 72 of file G4P1Messenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4P1Messenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4P1Messenger.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4P1Messenger.cc