ECCE @ EIC Software: OpNoviceRunAction Class Reference
OpNoviceRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/include/OpNoviceRunAction.hh>
Public Member Functions
OpNoviceRunAction ()
virtual ~OpNoviceRunAction ()
virtual void BeginOfRunAction (const G4Run *aRun)
virtual void EndOfRunAction (const G4Run *aRun)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4Timer * fTimer
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 45 of file OpNoviceRunAction.hh.
View newest version in sPHENIX GitHub at line 45 of file OpNoviceRunAction.hh
Constructor & Destructor Documentation
OpNoviceRunAction::OpNoviceRunAction ()
Definition at line 43 of file OpNoviceRunAction.cc.
View newest version in sPHENIX GitHub at line 43 of file OpNoviceRunAction.cc
References fTimer.
OpNoviceRunAction::~OpNoviceRunAction () virtual
Definition at line 52 of file OpNoviceRunAction.cc.
View newest version in sPHENIX GitHub at line 52 of file OpNoviceRunAction.cc
References fTimer.
Member Function Documentation
void OpNoviceRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 59 of file OpNoviceRunAction.cc.
View newest version in sPHENIX GitHub at line 59 of file OpNoviceRunAction.cc
References fTimer, G4cout, G4endl, G4Run::GetRunID(), and G4Timer::Start().
void OpNoviceRunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 67 of file OpNoviceRunAction.cc.
View newest version in sPHENIX GitHub at line 67 of file OpNoviceRunAction.cc
References fTimer, G4cout, G4endl, G4Run::GetNumberOfEvent(), and G4Timer::Stop().
Member Data Documentation
G4Timer* OpNoviceRunAction::fTimer private
Definition at line 56 of file OpNoviceRunAction.hh.
View newest version in sPHENIX GitHub at line 56 of file OpNoviceRunAction.hh
Referenced by BeginOfRunAction(), EndOfRunAction(), OpNoviceRunAction(), and ~OpNoviceRunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/include/OpNoviceRunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/src/OpNoviceRunAction.cc