ECCE @ EIC Software: G4VisExtent Class Reference
G4VisExtent Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4VisExtent.hh>
Public Member Functions
G4VisExtent (G4double xmin=0., G4double xmax=0., G4double ymin=0., G4double ymax=0., G4double zmin=0., G4double zmax=0.)
G4VisExtent (const G4Point3D &centre, G4double radius)
~G4VisExtent ()
G4bool operator!= (const G4VisExtent &e) const
G4bool operator== (const G4VisExtent &e) const
G4VisExtent & Transform (const G4Transform3D &)
G4double GetXmin () const
G4double GetXmax () const
G4double GetYmin () const
G4double GetYmax () const
G4double GetZmin () const
G4double GetZmax () const
const G4Point3D & GetExtentCentre () const
const G4Point3D & GetExtentCenter () const
G4double GetExtentRadius () const
void SetXmin (G4double xmin)
void SetXmax (G4double xmax)
void SetYmin (G4double ymin)
void SetYmax (G4double ymax)
void SetZmin (G4double zmin)
void SetZmax (G4double zmax)
Static Public Member Functions
static const G4VisExtent & GetNullExtent ()
Private Attributes
G4double fXmin
G4double fXmax
G4double fYmin
G4double fYmax
G4double fZmin
G4double fZmax
G4bool fRadiusCached
G4bool fCentreCached
G4double fRadius
G4Point3D fCentre
Friends
std::ostream & operator<< (std::ostream &os, const G4VisExtent &e)
Detailed Description
Definition at line 54 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VisExtent.hh
Constructor & Destructor Documentation
G4VisExtent::G4VisExtent (G4double xmin = 0., G4double xmax = 0., G4double ymin = 0., G4double ymax = 0., G4double zmin = 0., G4double zmax = 0.)
Definition at line 37 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VisExtent.cc
Referenced by GetNullExtent().
G4VisExtent::G4VisExtent (const G4Point3D & centre, G4double radius)
Definition at line 44 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VisExtent.cc
References fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
G4VisExtent::~G4VisExtent ()
Definition at line 58 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VisExtent.cc
Member Function Documentation
const G4Point3D & G4VisExtent::GetExtentCenter () const inline
Definition at line 106 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 106 of file G4VisExtent.hh
References GetExtentCentre().
Referenced by G4VVisCommand::DrawExtent().
const G4Point3D & G4VisExtent::GetExtentCentre () const
Definition at line 65 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VisExtent.cc
References fCentre, fCentreCached, fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
Referenced by G4Scene::CalculateExtent(), G4VSceneHandler::CreateSectionSolid(), GetExtentCenter(), G4BoundingSphereScene::ProcessVolume(), G4VisCommandsTouchable::SetNewValue(), and G4VisCommandViewerCentreOn::SetNewValue().
G4double G4VisExtent::GetExtentRadius () const
Definition at line 75 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 75 of file G4VisExtent.cc
References fRadius, fRadiusCached, fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
Referenced by G4VisCommandSceneAddUserAction::AddVisAction(), G4Scene::CalculateExtent(), G4PhysicalVolumeModel::CalculateExtent(), G4VSceneHandler::CreateSectionSolid(), G4BoundingSphereScene::ProcessVolume(), G4VisManager::RegisterEndOfEventUserVisAction(), G4VisManager::RegisterEndOfRunUserVisAction(), G4VisManager::RegisterRunDurationUserVisAction(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), and G4RayTracerViewer::SetView().
const G4VisExtent & G4VisExtent::GetNullExtent () static
Definition at line 60 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 60 of file G4VisExtent.cc
References G4VisExtent().
Referenced by G4VFieldModel::DescribeYourselfTo(), G4VFieldModel::G4VFieldModel(), and G4VSceneHandler::ProcessScene().
G4double G4VisExtent::GetXmax () const inline
Definition at line 100 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 100 of file G4VisExtent.hh
References fXmax.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4VFieldModel::DescribeYourselfTo(), G4VVisCommand::DrawExtent(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
G4double G4VisExtent::GetXmin () const inline
Definition at line 99 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 99 of file G4VisExtent.hh
References fXmin.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4VFieldModel::DescribeYourselfTo(), G4VVisCommand::DrawExtent(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
G4double G4VisExtent::GetYmax () const inline
Definition at line 102 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VisExtent.hh
References fYmax.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4VFieldModel::DescribeYourselfTo(), G4VVisCommand::DrawExtent(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
G4double G4VisExtent::GetYmin () const inline
Definition at line 101 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 101 of file G4VisExtent.hh
References fYmin.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4VFieldModel::DescribeYourselfTo(), G4VVisCommand::DrawExtent(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
G4double G4VisExtent::GetZmax () const inline
Definition at line 104 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 104 of file G4VisExtent.hh
References fZmax.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4VFieldModel::DescribeYourselfTo(), G4VVisCommand::DrawExtent(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
G4double G4VisExtent::GetZmin () const inline
Definition at line 103 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 103 of file G4VisExtent.hh
References fZmin.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), G4VSceneHandler::AddPrimitive(), G4tgbVolume::BuildSolidForDivision(), G4VFieldModel::DescribeYourselfTo(), G4VVisCommand::DrawExtent(), G4VisCommandSceneAddLogo::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
G4bool G4VisExtent::operator!= (const G4VisExtent & e) const
Definition at line 93 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 93 of file G4VisExtent.cc
References fXmax, fXmin, fYmax, fYmin, fZmax, and fZmin.
Referenced by operator==().
G4bool G4VisExtent::operator== (const G4VisExtent & e) const inline
Definition at line 65 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VisExtent.hh
References operator!=().
void G4VisExtent::SetXmax (G4double xmax) inline
Definition at line 112 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VisExtent.hh
References fCentreCached, fRadiusCached, fXmax, and xmax.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), and G4VSolid::GetExtent().
void G4VisExtent::SetXmin (G4double xmin) inline
Definition at line 110 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 110 of file G4VisExtent.hh
References fCentreCached, fRadiusCached, fXmin, and xmin.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), and G4VSolid::GetExtent().
void G4VisExtent::SetYmax (G4double ymax) inline
Definition at line 116 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VisExtent.hh
References fCentreCached, fRadiusCached, fYmax, and ymax.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), and G4VSolid::GetExtent().
void G4VisExtent::SetYmin (G4double ymin) inline
Definition at line 114 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VisExtent.hh
References fCentreCached, fRadiusCached, fYmin, and ymin.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), and G4VSolid::GetExtent().
void G4VisExtent::SetZmax (G4double zmax) inline
Definition at line 120 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VisExtent.hh
References fCentreCached, fRadiusCached, and fZmax.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), and G4VSolid::GetExtent().
void G4VisExtent::SetZmin (G4double zmin) inline
Definition at line 118 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VisExtent.hh
References fCentreCached, fRadiusCached, and fZmin.
Referenced by G4BoundingExtentScene::AccrueBoundingExtent(), and G4VSolid::GetExtent().
G4VisExtent & G4VisExtent::Transform (const G4Transform3D & transform)
Definition at line 102 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 102 of file G4VisExtent.cc
References DBL_MAX, fXmax, fXmin, fYmax, fYmin, fZmax, fZmin, HepGeom::Transform3D::getRotation(), HepGeom::Transform3D::getTranslation(), and CLHEP::Hep3Vector::transform().
Referenced by G4VModel::GetTransformedExtent(), G4BoundingExtentScene::ProcessVolume(), G4VisCommandsTouchable::SetNewValue(), and G4VisCommandSetVolumeForField::SetNewValue().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4VisExtent & e) friend
Definition at line 85 of file G4VisExtent.cc.
View newest version in sPHENIX GitHub at line 85 of file G4VisExtent.cc
Member Data Documentation
G4Point3D G4VisExtent::fCentre mutable private
Definition at line 96 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 96 of file G4VisExtent.hh
Referenced by GetExtentCentre().
G4bool G4VisExtent::fCentreCached mutable private
Definition at line 94 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 94 of file G4VisExtent.hh
Referenced by GetExtentCentre(), SetXmax(), SetXmin(), SetYmax(), SetYmin(), SetZmax(), and SetZmin().
G4double G4VisExtent::fRadius mutable private
Definition at line 95 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 95 of file G4VisExtent.hh
Referenced by GetExtentRadius().
G4bool G4VisExtent::fRadiusCached mutable private
Definition at line 94 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 94 of file G4VisExtent.hh
Referenced by GetExtentRadius(), SetXmax(), SetXmin(), SetYmax(), SetYmin(), SetZmax(), and SetZmin().
G4double G4VisExtent::fXmax private
Definition at line 93 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VisExtent.hh
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetXmax(), operator!=(), operator<<(), SetXmax(), and Transform().
G4double G4VisExtent::fXmin private
Definition at line 93 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VisExtent.hh
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetXmin(), operator!=(), operator<<(), SetXmin(), and Transform().
G4double G4VisExtent::fYmax private
Definition at line 93 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VisExtent.hh
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetYmax(), operator!=(), operator<<(), SetYmax(), and Transform().
G4double G4VisExtent::fYmin private
Definition at line 93 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VisExtent.hh
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetYmin(), operator!=(), operator<<(), SetYmin(), and Transform().
G4double G4VisExtent::fZmax private
Definition at line 93 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VisExtent.hh
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetZmax(), operator!=(), operator<<(), SetZmax(), and Transform().
G4double G4VisExtent::fZmin private
Definition at line 93 of file G4VisExtent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VisExtent.hh
Referenced by G4VisExtent(), GetExtentCentre(), GetExtentRadius(), GetZmin(), operator!=(), operator<<(), SetZmin(), and Transform().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4VisExtent.hh
geant4/tree/geant4-10.6-release/source/graphics_reps/src/G4VisExtent.cc