ECCE @ EIC Software: GB05BOptrSplitAndKillByCrossSection Class Reference
GB05BOptrSplitAndKillByCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/include/GB05BOptrSplitAndKillByCrossSection.hh>
Public Member Functions
GB05BOptrSplitAndKillByCrossSection (G4String particleToBias, G4String name="SplitAndKillByXS")
virtual ~GB05BOptrSplitAndKillByCrossSection ()
virtual void StartRun ()
void AddProcessToEquipoise (G4String processName)
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartTracking (const G4Track *)
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *, const G4BiasingProcessInterface *) final
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *, const G4BiasingProcessInterface *) final
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *) final
Private Attributes
GB05BOptnSplitAndKillByCrossSection * fSplitAndKillByCrossSection
const G4ParticleDefinition * fParticleToBias
std::vector< G4String > fProcessesToEquipoise
G4bool fSetup
std::vector< const G4VProcess * > fProcesses
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions inherited from G4VBiasingOperator
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Detailed Description
Definition at line 57 of file GB05BOptrSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 57 of file GB05BOptrSplitAndKillByCrossSection.hh
Constructor & Destructor Documentation
GB05BOptrSplitAndKillByCrossSection::GB05BOptrSplitAndKillByCrossSection (G4String particleToBias, G4String name = "SplitAndKillByXS")
Definition at line 41 of file GB05BOptrSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 41 of file GB05BOptrSplitAndKillByCrossSection.cc
References G4ParticleTable::FindParticle(), fParticleToBias, fSplitAndKillByCrossSection, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), and JustWarning.
GB05BOptrSplitAndKillByCrossSection::~GB05BOptrSplitAndKillByCrossSection () virtual
Definition at line 65 of file GB05BOptrSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 65 of file GB05BOptrSplitAndKillByCrossSection.cc
References fSplitAndKillByCrossSection.
Member Function Documentation
void GB05BOptrSplitAndKillByCrossSection::AddProcessToEquipoise (G4String processName)
Definition at line 182 of file GB05BOptrSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 182 of file GB05BOptrSplitAndKillByCrossSection.cc
References fProcessesToEquipoise.
Referenced by GB05DetectorConstruction::ConstructSDandField().
virtual G4VBiasingOperation* GB05BOptrSplitAndKillByCrossSection::ProposeFinalStateBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline final private virtual
Implements G4VBiasingOperator.
Definition at line 81 of file GB05BOptrSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 81 of file GB05BOptrSplitAndKillByCrossSection.hh
G4VBiasingOperation * GB05BOptrSplitAndKillByCrossSection::ProposeNonPhysicsBiasingOperation (const G4Track * track, const G4BiasingProcessInterface *) final private virtual
Implements G4VBiasingOperator.
Definition at line 144 of file GB05BOptrSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 144 of file GB05BOptrSplitAndKillByCrossSection.cc
References DBL_MAX, DBL_MIN, fParticleToBias, fProcesses, fSplitAndKillByCrossSection, G4Track::GetDefinition(), and GB05BOptnSplitAndKillByCrossSection::SetInteractionLength().
virtual G4VBiasingOperation* GB05BOptrSplitAndKillByCrossSection::ProposeOccurenceBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline final private virtual
Implements G4VBiasingOperator.
Definition at line 75 of file GB05BOptrSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 75 of file GB05BOptrSplitAndKillByCrossSection.hh
void GB05BOptrSplitAndKillByCrossSection::StartRun () virtual
Reimplemented from G4VBiasingOperator.
Definition at line 72 of file GB05BOptrSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 72 of file GB05BOptrSplitAndKillByCrossSection.cc
References fParticleToBias, fProcesses, fProcessesToEquipoise, fSetup, G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), G4BiasingProcessSharedData::GetPhysicsBiasingProcessInterfaces(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4BiasingProcessInterface::GetSharedData(), G4BiasingProcessInterface::GetWrappedProcess(), and JustWarning.
Member Data Documentation
const G4ParticleDefinition* GB05BOptrSplitAndKillByCrossSection::fParticleToBias private
Definition at line 103 of file GB05BOptrSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 103 of file GB05BOptrSplitAndKillByCrossSection.hh
Referenced by GB05BOptrSplitAndKillByCrossSection(), ProposeNonPhysicsBiasingOperation(), and StartRun().
std::vector< const G4VProcess* > GB05BOptrSplitAndKillByCrossSection::fProcesses private
Definition at line 106 of file GB05BOptrSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 106 of file GB05BOptrSplitAndKillByCrossSection.hh
Referenced by ProposeNonPhysicsBiasingOperation(), and StartRun().
std::vector< G4String > GB05BOptrSplitAndKillByCrossSection::fProcessesToEquipoise private
Definition at line 104 of file GB05BOptrSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 104 of file GB05BOptrSplitAndKillByCrossSection.hh
Referenced by AddProcessToEquipoise(), and StartRun().
G4bool GB05BOptrSplitAndKillByCrossSection::fSetup private
Definition at line 105 of file GB05BOptrSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 105 of file GB05BOptrSplitAndKillByCrossSection.hh
Referenced by StartRun().
GB05BOptnSplitAndKillByCrossSection* GB05BOptrSplitAndKillByCrossSection::fSplitAndKillByCrossSection private
Definition at line 102 of file GB05BOptrSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 102 of file GB05BOptrSplitAndKillByCrossSection.hh
Referenced by GB05BOptrSplitAndKillByCrossSection(), ProposeNonPhysicsBiasingOperation(), and ~GB05BOptrSplitAndKillByCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/include/GB05BOptrSplitAndKillByCrossSection.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/src/GB05BOptrSplitAndKillByCrossSection.cc