ECCE @ EIC Software: field_utils Namespace Reference
field_utils Namespace Reference
Typedefs
using State = G4double[G4FieldTrack::ncompSVEC]
Enumerations
enum Value3D
enum Value1D
Functions
template<typename ArrayType >
G4double getValue (const ArrayType &array, Value1D value)
template<typename ArrayType >
G4double getValue2 (const ArrayType &array, Value1D value)
template<typename ArrayType >
G4double getValue (const ArrayType &array, Value3D value)
template<typename ArrayType >
G4double getValue2 (const ArrayType &array, Value3D value)
template<typename ArrayType >
G4ThreeVector makeVector (const ArrayType &array, Value3D value)
G4double absoluteError (const G4double y[], const G4double yerr[], G4double hstep)
G4double relativeError2 (const G4double y[], const G4double yerr[], G4double hstep, G4double errorTolerance)
G4double relativeError (const G4double y[], const G4double yerr[], G4double hstep, G4double errorTolerance)
template<typename SourceArray , typename TargetArray >
void setValue (const SourceArray &src, Value1D value, TargetArray &trg)
template<typename SourceArray , typename TargetArray , typename... TargetArrays>
void setValue (const SourceArray &src, Value1D value, TargetArray &trg, TargetArrays &...trgs)
void copy (G4double dst[], const G4double src[], size_t size=G4FieldTrack::ncompSVEC)
G4double inverseCurvatureRadius (G4double particleCharge, G4double momentum, G4double BField)
template<typename T >
T clamp (T value, T lo, T hi)
Typedef Documentation
using field_utils::State = typedef G4double[G4FieldTrack::ncompSVEC]
Definition at line 45 of file G4FieldUtils.hh.
View newest version in sPHENIX GitHub at line 45 of file G4FieldUtils.hh
Enumeration Type Documentation
enum field_utils::Value1D
Definition at line 54 of file G4FieldUtils.hh.
View newest version in sPHENIX GitHub at line 54 of file G4FieldUtils.hh
enum field_utils::Value3D
Definition at line 47 of file G4FieldUtils.hh.
View newest version in sPHENIX GitHub at line 47 of file G4FieldUtils.hh
Function Documentation
G4double field_utils::absoluteError (const G4double y[], const G4double yerr[], G4double hstep)
Definition at line 38 of file G4FieldUtils.cc.
View newest version in sPHENIX GitHub at line 38 of file G4FieldUtils.cc
References getValue2(), and max.
template<typename T > T field_utils::clamp (T value, T lo, T hi)
Referenced by Acts::BoundaryCheck::computeClosestPointOnPolygon().
void field_utils::copy (G4double dst[], const G4double src[], size_t size = G4FieldTrack::ncompSVEC)
Definition at line 98 of file G4FieldUtils.cc.
View newest version in sPHENIX GitHub at line 98 of file G4FieldUtils.cc
Referenced by MakeActsGeometry::addActsTpcSurfaces(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), G4mpi::buildCommunicationMap(), G3VolTableEntry::ClearG3PosCopy(), nlohmann::detail::external_constructor< value_t::array >::construct(), SvtxTrack_v1::CopyFrom(), SvtxTrack_v2::CopyFrom(), G4TriangularFacet::CopyFrom(), ActsFatras::Simulator< charged_selector_t, charged_simulator_t, neutral_selector_t, neutral_simulator_t >::copyOutputs(), kdfinder::Data< T >::Data(), Packet_idcdevdescr::decode(), deflate(), FW::HelloWhiteBoardAlgorithm::execute(), G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::fill(), nlohmann::detail::from_json(), G4VPhysicsConstructor::GetBuilders(), gz_write(), inflate(), inflateBack(), inflateCopy(), SvtxTrack_v1::insert_state(), SvtxTrack_v2::insert_state(), HadrontherapyRBE::LoadLEMTable(), md5_append(), kdfinder::TrackCandidate< T >::mergeCandidate(), PHSimpleKFProp::MoveToFirstTPCCluster(), G4INCL::NuclearDensity::NuclearDensity(), boost::array< T, N >::operator=(), nanoflann::CArray< T, N >::operator=(), G4MPIscorerMerger::Pack(), Acts::ParameterSet< params...>::ParameterSet(), nlohmann::basic_json::patch(), PHField2D::PHField2D(), PHField3DCylindrical::PHField3DCylindrical(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::populateNeighborCache(), PHG4EtaParameterization::Print(), PHG4EtaPhiParameterization::Print(), G4VHadDecayAlgorithm::PrintVector(), PHG4TpcCentralMembrane::process_event(), PHGenFitTrkFitter::process_event(), PHSimpleKFProp::PropagateTrack(), G4CascadeCoalescence::reportArgs(), Acts::SingleFreeParameters< ChargePolicy >::SingleFreeParameters(), G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::SortedNucleonConfiguration(), G4RK547FEq2::Stepper(), G4RK547FEq1::Stepper(), G4RK547FEq3::Stepper(), G4BogackiShampine23::Stepper(), G4DormandPrince745::Stepper(), kdfinder::TrackCandidate< T >::TrackCandidate(), updatewindow(), and nlohmann::detail::output_vector_adapter< CharType >::write_characters().
template<typename ArrayType > G4double field_utils::getValue (const ArrayType & array, Value1D value)
Referenced by Acts::ParameterSet< params...>::setParameter(), and G4NystromRK4::Stepper().
template<typename ArrayType > G4double field_utils::getValue (const ArrayType & array, Value3D value)
template<typename ArrayType > G4double field_utils::getValue2 (const ArrayType & array, Value1D value)
Referenced by absoluteError(), relativeError2(), and G4NystromRK4::Stepper().
template<typename ArrayType > G4double field_utils::getValue2 (const ArrayType & array, Value3D value)
G4double field_utils::inverseCurvatureRadius (G4double particleCharge, G4double momentum, G4double BField)
Definition at line 104 of file G4FieldUtils.cc.
View newest version in sPHENIX GitHub at line 104 of file G4FieldUtils.cc
References source.hepunit::c_light, and momentum.
template<typename ArrayType > G4ThreeVector field_utils::makeVector (const ArrayType & array, Value3D value)
Referenced by G4RK547FEq1::DistChord(), G4RK547FEq3::DistChord(), G4RK547FEq2::DistChord(), G4BogackiShampine23::DistChord(), and G4DormandPrince745::DistChord().
G4double field_utils::relativeError (const G4double y[], const G4double yerr[], G4double hstep, G4double errorTolerance)
Definition at line 90 of file G4FieldUtils.cc.
View newest version in sPHENIX GitHub at line 90 of file G4FieldUtils.cc
References relativeError2().
Referenced by G4BulirschStoer::try_step().
G4double field_utils::relativeError2 (const G4double y[], const G4double yerr[], G4double hstep, G4double errorTolerance)
Definition at line 52 of file G4FieldUtils.cc.
View newest version in sPHENIX GitHub at line 52 of file G4FieldUtils.cc
References G4Exception(), getValue2(), Acts::UnitConstants::h, JustWarning, and max.
Referenced by relativeError().
template<typename SourceArray , typename TargetArray > void field_utils::setValue (const SourceArray & src, Value1D value, TargetArray & trg)
Referenced by G4ModifiedMidpoint::DoStep().
template<typename SourceArray , typename TargetArray , typename... TargetArrays> void field_utils::setValue (const SourceArray & src, Value1D value, TargetArray & trg, TargetArrays &... trgs)