ECCE @ EIC Software: G4DopplerProfile Class Reference
G4DopplerProfile Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4DopplerProfile.hh>
Public Member Functions
G4DopplerProfile (G4int minZ=1, G4int maxZ=100)
~G4DopplerProfile ()
size_t NumberOfProfiles (G4int Z) const
const G4VEMDataSet * Profiles (G4int Z) const
const G4VEMDataSet * Profile (G4int Z, G4int ShellIndex) const
void PrintData () const
G4double RandomSelectMomentum (G4int Z, G4int shellIndex) const
Private Member Functions
G4DopplerProfile & operator= (const G4DopplerProfile &right)
G4DopplerProfile (const G4DopplerProfile &)
void LoadBiggsP (const G4String &fileName)
void LoadProfile (const G4String &fileName, G4int Z)
Private Attributes
std::map< G4int, G4VEMDataSet
*, std::less< G4int > > profileMap
std::vector< G4int > nShells
G4int zMin
G4int zMax
size_t nBiggs
std::vector< G4double > biggsP
Detailed Description
Definition at line 51 of file G4DopplerProfile.hh.
View newest version in sPHENIX GitHub at line 51 of file G4DopplerProfile.hh
Constructor & Destructor Documentation
G4DopplerProfile::G4DopplerProfile (G4int minZ = 1, G4int maxZ = 100)
Definition at line 54 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 54 of file G4DopplerProfile.cc
References LoadBiggsP(), LoadProfile(), nBiggs, Z, zMax, and zMin.
G4DopplerProfile::~G4DopplerProfile ()
Definition at line 68 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 68 of file G4DopplerProfile.cc
References pos(), and profileMap.
G4DopplerProfile::G4DopplerProfile (const G4DopplerProfile &) private
Member Function Documentation
void G4DopplerProfile::LoadBiggsP (const G4String & fileName) private
Definition at line 118 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 118 of file G4DopplerProfile.cc
References biggsP, FatalException, file, G4Exception(), nBiggs, and s1.
Referenced by G4DopplerProfile().
void G4DopplerProfile::LoadProfile (const G4String & fileName, G4int Z) private
Definition at line 160 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 160 of file G4DopplerProfile.cc
References G4VEMDataSet::AddComponent(), biggsP, G4VDataSetAlgorithm::Clone(), FatalException, file, G4Exception(), nBiggs, nShells, profileMap, s1, and Z.
Referenced by G4DopplerProfile().
size_t G4DopplerProfile::NumberOfProfiles (G4int Z) const
Definition at line 80 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 80 of file G4DopplerProfile.cc
References n, nShells, zMax, and zMin.
G4DopplerProfile& G4DopplerProfile::operator= (const G4DopplerProfile & right) private
void G4DopplerProfile::PrintData (void) const
Definition at line 108 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 108 of file G4DopplerProfile.cc
References G4VEMDataSet::PrintData(), Profiles(), Z, zMax, and zMin.
const G4VEMDataSet * G4DopplerProfile::Profile (G4int Z, G4int ShellIndex) const
Definition at line 100 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 100 of file G4DopplerProfile.cc
References G4VEMDataSet::GetComponent(), and Profiles().
const G4VEMDataSet * G4DopplerProfile::Profiles (G4int Z) const
Definition at line 88 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 88 of file G4DopplerProfile.cc
References FatalException, G4Exception(), pos(), profileMap, and zMax.
Referenced by PrintData(), Profile(), and RandomSelectMomentum().
G4double G4DopplerProfile::RandomSelectMomentum (G4int Z, G4int shellIndex) const
Definition at line 226 of file G4DopplerProfile.cc.
View newest version in sPHENIX GitHub at line 226 of file G4DopplerProfile.cc
References Profiles(), and G4VEMDataSet::RandomSelect().
Referenced by G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
Member Data Documentation
std::vector<G4double> G4DopplerProfile::biggsP private
Definition at line 83 of file G4DopplerProfile.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DopplerProfile.hh
Referenced by LoadBiggsP(), and LoadProfile().
size_t G4DopplerProfile::nBiggs private
Definition at line 81 of file G4DopplerProfile.hh.
View newest version in sPHENIX GitHub at line 81 of file G4DopplerProfile.hh
Referenced by G4DopplerProfile(), LoadBiggsP(), and LoadProfile().
std::vector<G4int> G4DopplerProfile::nShells private
Definition at line 76 of file G4DopplerProfile.hh.
View newest version in sPHENIX GitHub at line 76 of file G4DopplerProfile.hh
Referenced by LoadProfile(), and NumberOfProfiles().
std::map<G4int,G4VEMDataSet*,std::less<G4int> > G4DopplerProfile::profileMap private
Definition at line 75 of file G4DopplerProfile.hh.
View newest version in sPHENIX GitHub at line 75 of file G4DopplerProfile.hh
Referenced by LoadProfile(), Profiles(), and ~G4DopplerProfile().
G4int G4DopplerProfile::zMax private
Definition at line 79 of file G4DopplerProfile.hh.
View newest version in sPHENIX GitHub at line 79 of file G4DopplerProfile.hh
Referenced by G4DopplerProfile(), NumberOfProfiles(), PrintData(), and Profiles().
G4int G4DopplerProfile::zMin private
Definition at line 78 of file G4DopplerProfile.hh.
View newest version in sPHENIX GitHub at line 78 of file G4DopplerProfile.hh
Referenced by G4DopplerProfile(), NumberOfProfiles(), and PrintData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4DopplerProfile.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4DopplerProfile.cc