ECCE @ EIC Software: StepLimiter Class Reference
StepLimiter Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/StepLimiter.hh>
Public Member Functions
StepLimiter (const G4String &processName="UserMaxStep")
virtual ~StepLimiter ()
G4bool IsApplicable (const G4ParticleDefinition &)
G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *)
void SetMaxStep (G4double)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
StepLimiter & operator= (const StepLimiter &right)
StepLimiter (const StepLimiter &)
Private Attributes
G4double fMaxChargedStep
StepLimiterMessenger * fMessenger
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 46 of file StepLimiter.hh.
View newest version in sPHENIX GitHub at line 46 of file StepLimiter.hh
Constructor & Destructor Documentation
StepLimiter::StepLimiter (const G4String & processName = "UserMaxStep")
Definition at line 38 of file StepLimiter.cc.
View newest version in sPHENIX GitHub at line 38 of file StepLimiter.cc
References fMessenger.
StepLimiter::~StepLimiter () virtual
Definition at line 47 of file StepLimiter.cc.
View newest version in sPHENIX GitHub at line 47 of file StepLimiter.cc
References fMessenger.
StepLimiter::StepLimiter (const StepLimiter &) private
Member Function Documentation
G4double StepLimiter::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition *) virtual
Implements G4VDiscreteProcess.
Definition at line 82 of file StepLimiter.cc.
View newest version in sPHENIX GitHub at line 82 of file StepLimiter.cc
References DBL_MAX.
G4bool StepLimiter::IsApplicable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 54 of file StepLimiter.cc.
View newest version in sPHENIX GitHub at line 54 of file StepLimiter.cc
References G4ParticleDefinition::GetPDGCharge(), and G4ParticleDefinition::IsShortLived().
Referenced by StepLimiterBuilder::ConstructProcess().
StepLimiter& StepLimiter::operator= (const StepLimiter & right) private
G4VParticleChange * StepLimiter::PostStepDoIt (const G4Track & aTrack, const G4Step &) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 73 of file StepLimiter.cc.
View newest version in sPHENIX GitHub at line 73 of file StepLimiter.cc
References G4VProcess::aParticleChange, and G4ParticleChange::Initialize().
G4double StepLimiter::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 61 of file StepLimiter.cc.
View newest version in sPHENIX GitHub at line 61 of file StepLimiter.cc
References fMaxChargedStep, and NotForced.
void StepLimiter::SetMaxStep (G4double value) inline
Definition at line 77 of file StepLimiter.hh.
View newest version in sPHENIX GitHub at line 77 of file StepLimiter.hh
References fMaxChargedStep.
Referenced by StepLimiterMessenger::SetNewValue().
Member Data Documentation
G4double StepLimiter::fMaxChargedStep private
Definition at line 72 of file StepLimiter.hh.
View newest version in sPHENIX GitHub at line 72 of file StepLimiter.hh
Referenced by PostStepGetPhysicalInteractionLength(), and SetMaxStep().
StepLimiterMessenger* StepLimiter::fMessenger private
Definition at line 74 of file StepLimiter.hh.
View newest version in sPHENIX GitHub at line 74 of file StepLimiter.hh
Referenced by StepLimiter(), and ~StepLimiter().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/StepLimiter.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/StepLimiter.cc