ECCE @ EIC Software: G4PhononPolarization Namespace Reference
G4PhononPolarization Namespace Reference
Enumerations
enum { Long =0, TransSlow =1, TransFast =2, UNKNOWN =-1 }
Functions
G4int Get (const G4ParticleDefinition *aPD)
G4ParticleDefinition * Get (G4int pol)
Enumeration Type Documentation
anonymous enum
Enumerator:
Long
TransSlow
TransFast
UNKNOWN
Definition at line 39 of file G4PhononPolarization.hh.
View newest version in sPHENIX GitHub at line 39 of file G4PhononPolarization.hh
Function Documentation
G4int G4PhononPolarization::Get (const G4ParticleDefinition * aPD)
Definition at line 38 of file G4PhononPolarization.cc.
View newest version in sPHENIX GitHub at line 38 of file G4PhononPolarization.cc
References G4PhononLong::Definition(), G4PhononTransSlow::Definition(), G4PhononTransFast::Definition(), TransFast, TransSlow, and UNKNOWN.
Referenced by XPhononStackingAction::ClassifyNewTrack(), G4VPhononProcess::CreateSecondary(), and G4VPhononProcess::GetPolarization().
G4ParticleDefinition * G4PhononPolarization::Get (G4int pol)
Definition at line 45 of file G4PhononPolarization.cc.
View newest version in sPHENIX GitHub at line 45 of file G4PhononPolarization.cc
References G4PhononLong::Definition(), G4PhononTransSlow::Definition(), G4PhononTransFast::Definition(), TransFast, and TransSlow.