ECCE @ EIC Software: G4Threading Namespace Reference
G4Threading Namespace Reference
Enumerations
enum { SEQUENTIAL_ID = -2, MASTER_ID = -1, WORKER_ID = 0, GENERICTHREAD_ID = -1000 }
Functions
G4Pid_t G4GetPidId ()
G4int G4GetNumberOfCores ()
G4int G4GetThreadId ()
G4bool IsWorkerThread ()
G4bool IsMasterThread ()
void G4SetThreadId (G4int aNewValue)
G4bool G4SetPinAffinity (G4int idx, G4NativeThread &at)
void SetMultithreadedApplication (G4bool value)
G4bool IsMultithreadedApplication ()
int WorkerThreadLeavesPool ()
int WorkerThreadJoinsPool ()
G4int GetNumberOfRunningWorkerThreads ()
Enumeration Type Documentation
anonymous enum
Enumerator:
SEQUENTIAL_ID
MASTER_ID
WORKER_ID
GENERICTHREAD_ID
Definition at line 268 of file G4Threading.hh.
View newest version in sPHENIX GitHub at line 268 of file G4Threading.hh
Function Documentation
G4int G4Threading::G4GetNumberOfCores ()
Definition at line 126 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 126 of file G4Threading.cc
Referenced by G4MTRunManager::G4MTRunManager(), main(), message(), G4RunMessenger::SetNewValue(), and G4WorkerThread::SetPinAffinity().
G4Pid_t G4Threading::G4GetPidId ()
Definition at line 116 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 116 of file G4Threading.cc
G4int G4Threading::G4GetThreadId ()
Definition at line 127 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 127 of file G4Threading.cc
References SEQUENTIAL_ID.
Referenced by G4UImanager::AddNewCommand(), F04RunAction::BeginOfRunAction(), F04EventAction::EndOfEventAction(), WLSEventAction::EndOfEventAction(), F04RunAction::EndOfRunAction(), G4BaseFileManager::GetFullFileName(), G4BaseFileManager::GetNtupleFileName(), G4RootAnalysisManager::GetNtupleFileNumber(), GammaRayTelRunAction::OpenFile(), G4UImanager::RemoveCommand(), G4WorkerRunManager::RunInitialization(), G4ParticleDefinition::SetProcessManager(), XrayTelSteppingAction::UserSteppingAction(), DMXEventAction::writePmtHitsToFile(), and DMXEventAction::writeScintHitsToFile().
G4bool G4Threading::G4SetPinAffinity (G4int idx, G4NativeThread & at)
Definition at line 132 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 132 of file G4Threading.cc
Referenced by G4WorkerThread::SetPinAffinity().
void G4Threading::G4SetThreadId (G4int aNewValue)
Definition at line 130 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 130 of file G4Threading.cc
Referenced by tbbTask::execute(), G4UImanager::SetUpForSpecialThread(), and G4MTRunManagerKernel::StartThread().
G4int G4Threading::GetNumberOfRunningWorkerThreads ()
Definition at line 138 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 138 of file G4Threading.cc
Referenced by G4RootAnalysisManager::GetNtupleFileNumber().
G4bool G4Threading::IsMasterThread ()
Definition at line 129 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 129 of file G4Threading.cc
Referenced by G4EmModelActivator::ActivateEmOptions(), B03PhysicsList::AddBiasingProcess(), G4NuclideTable::AddState(), G4Colour::AddToMap(), G4LogicalVolume::AssignFieldManager(), G4ParticleHPCapture::BuildPhysicsTable(), G4ParticleHPFission::BuildPhysicsTable(), G4ParticleHPElastic::BuildPhysicsTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPInelastic::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4RadioactiveDecayBase::BuildPhysicsTable(), G4RadioactiveDecay::BuildPhysicsTable(), G4UnitDefinition::ClearUnitsTable(), G4HadronPhysicsQGS_BIC::ConstructProcess(), G4HadronPhysicsShieldingLEND::ConstructProcess(), G4NeutronTrackingCut::ConstructProcess(), G4HadronPhysicsFTF_BIC::ConstructProcess(), G4HadronPhysicsQGSP_BIC::ConstructProcess(), G4HadronPhysicsQGSP_BERT::ConstructProcess(), G4HadronPhysicsShielding::ConstructProcess(), G4HadronPhysicsFTFP_BERT::ConstructProcess(), G4RunManagerKernel::DefineWorldVolume(), G4UIcommand::DoIt(), G4DeexPrecoParameters::Dump(), G4CascadeInterface::G4CascadeInterface(), G4MonopoleTransportation::G4MonopoleTransportation(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4ParticleHPInelasticData::G4ParticleHPInelasticData(), G4RunManagerKernel::G4RunManagerKernel(), G4UnitDefinition::G4UnitDefinition(), G4UnitDefinition::GetUnitsTable(), G4EmCorrections::Initialise(), G4RunManager::InitializeGeometry(), G4RunManagerKernel::InitializePhysics(), G4DNAChemistryManager::InitializeThreadSharedData(), G4ITTrackHolder::Instance(), G4DNAElectronHoleRecombination::IsApplicable(), G4DeexPrecoParameters::IsLocked(), G4EmParameters::IsLocked(), G4EmDNAPhysicsActivator::IsVerbose(), G4RunManager::ReinitializeGeometry(), G4RunManagerKernel::RunInitialization(), G4ExcitationHandler::SetDeexChannelsType(), G4LogicalVolume::SetSensitiveDetector(), G4NuclideTable::SetThresholdOfHalfLife(), G4RunManagerKernel::WorkerDefineWorldVolume(), G4FermiBreakUpVI::~G4FermiBreakUpVI(), and G4ParticleHPFission::~G4ParticleHPFission().
G4bool G4Threading::IsMultithreadedApplication ()
Definition at line 135 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 135 of file G4Threading.cc
Referenced by G4VisManager::BeginOfRun(), G4RootAnalysisManager::CloseFileImpl(), G4TrajectoriesModel::DescribeYourselfTo(), G4VisManager::Draw(), G4VisManager::EndOfEvent(), Run::EndOfRun(), G4VisManager::EndOfRun(), G4MonopoleTransportation::G4MonopoleTransportation(), G4DNAChemistryManager::Initialize(), G4ITTrackHolder::Instance(), G4VisCommandSceneAddEventID::EventID::operator()(), G4IonTable::PreloadNuclide(), G4VSceneHandler::ProcessScene(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4RootAnalysisManager::SetNtupleMergingMode(), and G4GenericMessenger::Command::SetUnit().
G4bool G4Threading::IsWorkerThread ()
Definition at line 128 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 128 of file G4Threading.cc
Referenced by G4VisManager::BeginDraw(), G4VisManager::BeginDraw2D(), G4VisManager::BeginOfRun(), G4ParticleHPFissionData::BuildPhysicsTable(), G4ParticleHPCaptureData::BuildPhysicsTable(), G4ParticleHPElasticData::BuildPhysicsTable(), G4ParticleHPInelasticData::BuildPhysicsTable(), TSRun::ConstructMFD(), G4IonTable::CreateIon(), G4VisManager::Draw(), G4VisManager::DrawT(), G4VisManager::DrawT2D(), G4RunManagerKernel::DumpRegion(), G4VisManager::EndDraw(), G4VisManager::EndDraw2D(), G4VisManager::EndOfRun(), G4ParticleTable::FindParticle(), G4LossTableManager::G4LossTableManager(), G4ParticleHPCaptureData::G4ParticleHPCaptureData(), G4ParticleHPElasticData::G4ParticleHPElasticData(), G4ParticleHPFissionData::G4ParticleHPFissionData(), G4Pow::G4Pow(), G4UIcommand::G4UIcommandCommonConstructorCode(), G4VScoreNtupleWriter::G4VScoreNtupleWriter(), G4IonTable::GetIon(), G4IonTable::GetMuonicAtom(), G4ParticleHPVector::GetXsec(), G4DNAChemistryManager::Initialize(), G4ParticleTable::Insert(), G4VScoreNtupleWriter::Instance(), G4AccumulableManager::Instance(), G4Hdf5AnalysisManager::Instance(), G4CsvAnalysisManager::Instance(), G4XmlAnalysisManager::Instance(), G4XmlAnalysisReader::Instance(), G4Hdf5AnalysisReader::Instance(), G4RootAnalysisReader::Instance(), G4CsvAnalysisReader::Instance(), G4RootAnalysisManager::Instance(), G4AccumulableManager::Merge(), ScoreSpecies::OutputAndClear(), G4ToolsAnalysisManager::PlotImpl(), G4PhysicsModelCatalog::Register(), G4ParticleTable::Remove(), G4IonTable::Remove(), G4RootAnalysisManager::SetNtupleMergingMode(), G4XmlAnalysisManager::WriteH1(), G4CsvAnalysisManager::WriteH1(), G4Hdf5AnalysisManager::WriteH1(), G4RootAnalysisManager::WriteH1(), G4XmlAnalysisManager::WriteH2(), G4CsvAnalysisManager::WriteH2(), G4Hdf5AnalysisManager::WriteH2(), G4RootAnalysisManager::WriteH2(), G4XmlAnalysisManager::WriteH3(), G4CsvAnalysisManager::WriteH3(), G4Hdf5AnalysisManager::WriteH3(), G4RootAnalysisManager::WriteH3(), G4XmlAnalysisManager::WriteP1(), G4CsvAnalysisManager::WriteP1(), G4Hdf5AnalysisManager::WriteP1(), G4RootAnalysisManager::WriteP1(), G4XmlAnalysisManager::WriteP2(), G4CsvAnalysisManager::WriteP2(), G4Hdf5AnalysisManager::WriteP2(), G4RootAnalysisManager::WriteP2(), G4ParticleHPCapture::~G4ParticleHPCapture(), G4ParticleHPElastic::~G4ParticleHPElastic(), G4ParticleHPInelastic::~G4ParticleHPInelastic(), and TSRun::~TSRun().
void G4Threading::SetMultithreadedApplication (G4bool value)
Definition at line 134 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 134 of file G4Threading.cc
Referenced by G4MTRunManagerKernel::G4MTRunManagerKernel().
int G4Threading::WorkerThreadJoinsPool ()
Definition at line 137 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 137 of file G4Threading.cc
Referenced by G4MTRunManagerKernel::StartThread().
int G4Threading::WorkerThreadLeavesPool ()
Definition at line 136 of file G4Threading.cc.
View newest version in sPHENIX GitHub at line 136 of file G4Threading.cc
Referenced by G4MTRunManagerKernel::StartThread().