ECCE @ EIC Software: G4LowEGammaNuclearModel Class Reference
G4LowEGammaNuclearModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4LowEGammaNuclearModel.hh>
Public Member Functions
G4LowEGammaNuclearModel ()
~G4LowEGammaNuclearModel () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) final
void InitialiseModel () final
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4LowEGammaNuclearModel & operator= (const G4LowEGammaNuclearModel &right)
G4LowEGammaNuclearModel (const G4LowEGammaNuclearModel &)
Private Attributes
G4PreCompoundModel * fPreco
G4LorentzVector lab4mom
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 46 of file G4LowEGammaNuclearModel.hh.
View newest version in sPHENIX GitHub at line 46 of file G4LowEGammaNuclearModel.hh
Constructor & Destructor Documentation
G4LowEGammaNuclearModel::G4LowEGammaNuclearModel () explicit
Definition at line 46 of file G4LowEGammaNuclearModel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4LowEGammaNuclearModel.cc
References G4HadronicInteractionRegistry::FindModel(), fPreco, G4HadronicInteraction::GetMaxEnergy(), CLHEP::GeV, G4HadronicInteractionRegistry::Instance(), G4HadronicParameters::Instance(), G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
G4LowEGammaNuclearModel::~G4LowEGammaNuclearModel () override
Definition at line 59 of file G4LowEGammaNuclearModel.cc.
View newest version in sPHENIX GitHub at line 59 of file G4LowEGammaNuclearModel.cc
G4LowEGammaNuclearModel::G4LowEGammaNuclearModel (const G4LowEGammaNuclearModel &) private
Member Function Documentation
G4HadFinalState * G4LowEGammaNuclearModel::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) final virtual
Implements G4HadronicInteraction.
Definition at line 65 of file G4LowEGammaNuclearModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4LowEGammaNuclearModel.cc
References A(), G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), G4PreCompoundModel::DeExcite(), dir, fPreco, G4cout, G4endl, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4NucleiProperties::GetNuclearMass(), G4Nucleus::GetZ_asInt(), lab4mom, MeV, CLHEP::HepLorentzVector::set(), G4HadSecondary::SetCreatorModelType(), G4HadFinalState::SetStatusChange(), G4HadSecondary::SetTime(), stopAndKill, G4HadronicInteraction::theParticleChange, CLHEP::Hep3Vector::unit(), G4HadronicInteraction::verboseLevel, and Z.
void G4LowEGammaNuclearModel::InitialiseModel () final virtual
Reimplemented from G4HadronicInteraction.
Definition at line 62 of file G4LowEGammaNuclearModel.cc.
View newest version in sPHENIX GitHub at line 62 of file G4LowEGammaNuclearModel.cc
G4LowEGammaNuclearModel& G4LowEGammaNuclearModel::operator= (const G4LowEGammaNuclearModel & right) private
Member Data Documentation
G4PreCompoundModel* G4LowEGammaNuclearModel::fPreco private
Definition at line 65 of file G4LowEGammaNuclearModel.hh.
View newest version in sPHENIX GitHub at line 65 of file G4LowEGammaNuclearModel.hh
Referenced by ApplyYourself(), and G4LowEGammaNuclearModel().
G4LorentzVector G4LowEGammaNuclearModel::lab4mom private
Definition at line 66 of file G4LowEGammaNuclearModel.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LowEGammaNuclearModel.hh
Referenced by ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4LowEGammaNuclearModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4LowEGammaNuclearModel.cc