ECCE @ EIC Software: G4BlineTracerMessenger Class Reference
G4BlineTracerMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/include/G4BlineTracerMessenger.hh>
Public Member Functions
G4BlineTracerMessenger (G4BlineTracer *aBlineTool)
virtual ~G4BlineTracerMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4BlineTracer * fTheBlineTool
G4UIdirectory * fBlineToolDir
G4UIcmdWithAnInteger * fBlineCmd
G4UIcmdWithADoubleAndUnit * fSetMaxTrackingStepCmd
G4UIcmdWith3Vector * fSetDrawColourCmd
G4UIcmdWithABool * fSetDrawBlineCmd
G4UIcmdWithABool * fSetDrawPointsCmd
G4UIcmdWithADouble * fSetPointSizeCmd
G4UIcmdWithoutParameter * fDrawCmd
G4UIcmdWithoutParameter * fResetCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 61 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BlineTracerMessenger.hh
Constructor & Destructor Documentation
G4BlineTracerMessenger::G4BlineTracerMessenger (G4BlineTracer * aBlineTool)
Definition at line 56 of file G4BlineTracerMessenger.cc.
View newest version in sPHENIX GitHub at line 56 of file G4BlineTracerMessenger.cc
References G4UIcommand::AvailableForStates(), fBlineCmd, fBlineToolDir, fDrawCmd, fResetCmd, fSetDrawBlineCmd, fSetDrawColourCmd, fSetDrawPointsCmd, fSetMaxTrackingStepCmd, fSetPointSizeCmd, fTheBlineTool, G4State_Idle, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), and G4UIcmdWithABool::SetParameterName().
G4BlineTracerMessenger::~G4BlineTracerMessenger () virtual
Definition at line 111 of file G4BlineTracerMessenger.cc.
View newest version in sPHENIX GitHub at line 111 of file G4BlineTracerMessenger.cc
References fBlineCmd, fBlineToolDir, fDrawCmd, fResetCmd, fSetDrawBlineCmd, fSetDrawColourCmd, fSetDrawPointsCmd, fSetMaxTrackingStepCmd, and fSetPointSizeCmd.
Member Function Documentation
void G4BlineTracerMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 126 of file G4BlineTracerMessenger.cc.
View newest version in sPHENIX GitHub at line 126 of file G4BlineTracerMessenger.cc
References G4BlineTracer::ComputeBlines(), G4BlineEventAction::DrawFieldLines(), fBlineCmd, fDrawCmd, fResetCmd, fSetDrawBlineCmd, fSetDrawColourCmd, fSetDrawPointsCmd, fSetMaxTrackingStepCmd, fSetPointSizeCmd, fTheBlineTool, G4BlineTracer::GetEventAction(), G4UIcmdWith3Vector::GetNew3VectorValue(), G4BlineEventAction::ResetVectorObjectToBeDrawn(), G4BlineEventAction::SetDrawBline(), G4BlineEventAction::SetDrawPoints(), G4BlineTracer::SetMaxTrackingStep(), G4BlineEventAction::SetPointSize(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4UIcmdWithAnInteger* G4BlineTracerMessenger::fBlineCmd private
Definition at line 77 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), SetNewValue(), and ~G4BlineTracerMessenger().
G4UIdirectory* G4BlineTracerMessenger::fBlineToolDir private
Definition at line 73 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), and ~G4BlineTracerMessenger().
G4UIcmdWithoutParameter* G4BlineTracerMessenger::fDrawCmd private
Definition at line 83 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), SetNewValue(), and ~G4BlineTracerMessenger().
G4UIcmdWithoutParameter* G4BlineTracerMessenger::fResetCmd private
Definition at line 84 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), SetNewValue(), and ~G4BlineTracerMessenger().
G4UIcmdWithABool* G4BlineTracerMessenger::fSetDrawBlineCmd private
Definition at line 80 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), SetNewValue(), and ~G4BlineTracerMessenger().
G4UIcmdWith3Vector* G4BlineTracerMessenger::fSetDrawColourCmd private
Definition at line 79 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), SetNewValue(), and ~G4BlineTracerMessenger().
G4UIcmdWithABool* G4BlineTracerMessenger::fSetDrawPointsCmd private
Definition at line 81 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), SetNewValue(), and ~G4BlineTracerMessenger().
G4UIcmdWithADoubleAndUnit* G4BlineTracerMessenger::fSetMaxTrackingStepCmd private
Definition at line 78 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), SetNewValue(), and ~G4BlineTracerMessenger().
G4UIcmdWithADouble* G4BlineTracerMessenger::fSetPointSizeCmd private
Definition at line 82 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), SetNewValue(), and ~G4BlineTracerMessenger().
G4BlineTracer* G4BlineTracerMessenger::fTheBlineTool private
Definition at line 72 of file G4BlineTracerMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BlineTracerMessenger.hh
Referenced by G4BlineTracerMessenger(), and SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/include/G4BlineTracerMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/field/BlineTracer/src/G4BlineTracerMessenger.cc