ECCE @ EIC Software: G4BGGPionElasticXS Class Reference
G4BGGPionElasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4BGGPionElasticXS.hh>
Public Member Functions
G4BGGPionElasticXS (const G4ParticleDefinition *)
~G4BGGPionElasticXS () final
G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *) final
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm, const G4Material *mat) final
G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat) final
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr) final
void BuildPhysicsTable (const G4ParticleDefinition &) final
void CrossSectionDescription (std::ostream &) const final
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Member Functions
G4double CoulombFactorPiPlus (G4double kinEnergy, G4int Z)
G4double FactorPiMinus (G4double kinEnergy)
G4BGGPionElasticXS & operator= (const G4BGGPionElasticXS &right)
G4BGGPionElasticXS (const G4BGGPionElasticXS &)
Private Attributes
G4double fGlauberEnergy
G4double fLowEnergy
G4double fLowestEnergy
const G4ParticleDefinition * theProton
const G4ParticleDefinition * thePiPlus
G4Pow * fG4pow
G4ComponentGGHadronNucleusXsc * fGlauber
G4UPiNuclearCrossSection * fPion
G4HadronNucleonXsc * fHadron
G4bool isPiplus
G4bool isMaster
Static Private Attributes
static G4double theGlauberFacPiPlus [93] = {0.0}
static G4double theCoulombFacPiPlus [93] = {0.0}
static G4double theGlauberFacPiMinus [93] = {0.0}
static G4double theCoulombFacPiMinus [93] = {0.0}
static G4int theA [93] = {0}
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 64 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BGGPionElasticXS.hh
Constructor & Destructor Documentation
G4BGGPionElasticXS::G4BGGPionElasticXS (const G4ParticleDefinition * p) explicit
Definition at line 68 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 68 of file G4BGGPionElasticXS.cc
References fG4pow, fGlauber, fGlauberEnergy, fHadron, fLowEnergy, fLowestEnergy, fPion, G4Pow::GetInstance(), GeV, G4HadronicParameters::Instance(), isMaster, isPiplus, MeV, G4PionPlus::PionPlus(), G4Proton::Proton(), G4VCrossSectionDataSet::SetForAllAtomsAndEnergies(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), thePiPlus, theProton, and G4VCrossSectionDataSet::verboseLevel.
G4BGGPionElasticXS::~G4BGGPionElasticXS () final
Definition at line 93 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 93 of file G4BGGPionElasticXS.cc
References fHadron.
G4BGGPionElasticXS::G4BGGPionElasticXS (const G4BGGPionElasticXS &) private
Member Function Documentation
void G4BGGPionElasticXS::BuildPhysicsTable (const G4ParticleDefinition & p) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 175 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 175 of file G4BGGPionElasticXS.cc
References A(), G4UPiNuclearCrossSection::BuildPhysicsTable(), CoulombFactorPiPlus(), FactorPiMinus(), FatalException, fGlauber, fGlauberEnergy, fHadron, fLowEnergy, fPion, G4cout, G4endl, G4Exception(), G4lrint(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4NistManager::GetAtomicMassAmu(), G4UPiNuclearCrossSection::GetElasticCrossSection(), G4ComponentGGHadronNucleusXsc::GetElasticGlauberGribov(), G4ParticleDefinition::GetParticleName(), G4NistManager::Instance(), isMaster, isPiplus, mom, G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetKineticEnergy(), theA, theCoulombFacPiMinus, theCoulombFacPiPlus, theGlauberFacPiMinus, theGlauberFacPiPlus, thePiPlus, and G4VCrossSectionDataSet::verboseLevel.
G4double G4BGGPionElasticXS::CoulombFactorPiPlus (G4double kinEnergy, G4int Z) private
Definition at line 270 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 270 of file G4BGGPionElasticXS.cc
References G4NuclearRadii::CoulombFactor(), theA, and thePiPlus.
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
void G4BGGPionElasticXS::CrossSectionDescription (std::ostream & outFile) const final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 286 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 286 of file G4BGGPionElasticXS.cc
G4double G4BGGPionElasticXS::FactorPiMinus (G4double kinEnergy) private
Definition at line 278 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 278 of file G4BGGPionElasticXS.cc
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGPionElasticXS::GetElementCrossSection (const G4DynamicParticle * dp, G4int Z, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 119 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 119 of file G4BGGPionElasticXS.cc
References barn, CoulombFactorPiPlus(), Acts::VectorHelpers::cross(), FactorPiMinus(), fGlauber, fGlauberEnergy, fLowEnergy, fLowestEnergy, fPion, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4UPiNuclearCrossSection::GetElasticCrossSection(), G4ComponentGGHadronNucleusXsc::GetElasticGlauberGribov(), GetIsoCrossSection(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), isPiplus, max, min, theA, theCoulombFacPiMinus, theCoulombFacPiPlus, theGlauberFacPiMinus, theGlauberFacPiPlus, G4VCrossSectionDataSet::verboseLevel, and Z.
G4double G4BGGPionElasticXS::GetIsoCrossSection (const G4DynamicParticle * dp, G4int Z, G4int A, const G4Isotope * iso = nullptr, const G4Element * elm = nullptr, const G4Material * mat = nullptr) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 151 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 151 of file G4BGGPionElasticXS.cc
References barn, Acts::VectorHelpers::cross(), fHadron, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4HadronNucleonXsc::GetElasticHadronNucleonXsc(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4HadronNucleonXsc::HadronNucleonXscNS(), theProton, and G4VCrossSectionDataSet::verboseLevel.
Referenced by GetElementCrossSection().
G4bool G4BGGPionElasticXS::IsElementApplicable (const G4DynamicParticle * , G4int Z, const G4Material *) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 101 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 101 of file G4BGGPionElasticXS.cc
G4bool G4BGGPionElasticXS::IsIsoApplicable (const G4DynamicParticle * , G4int Z, G4int A, const G4Element * elm, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 109 of file G4BGGPionElasticXS.cc.
View newest version in sPHENIX GitHub at line 109 of file G4BGGPionElasticXS.cc
G4BGGPionElasticXS& G4BGGPionElasticXS::operator= (const G4BGGPionElasticXS & right) private
Member Data Documentation
G4Pow* G4BGGPionElasticXS::fG4pow private
Definition at line 113 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 113 of file G4BGGPionElasticXS.hh
Referenced by G4BGGPionElasticXS().
G4ComponentGGHadronNucleusXsc* G4BGGPionElasticXS::fGlauber private
Definition at line 115 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 115 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionElasticXS(), and GetElementCrossSection().
G4double G4BGGPionElasticXS::fGlauberEnergy private
Definition at line 100 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 100 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionElasticXS(), and GetElementCrossSection().
G4HadronNucleonXsc* G4BGGPionElasticXS::fHadron private
Definition at line 117 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 117 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionElasticXS(), GetIsoCrossSection(), and ~G4BGGPionElasticXS().
G4double G4BGGPionElasticXS::fLowEnergy private
Definition at line 101 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 101 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionElasticXS(), and GetElementCrossSection().
G4double G4BGGPionElasticXS::fLowestEnergy private
Definition at line 102 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 102 of file G4BGGPionElasticXS.hh
Referenced by G4BGGPionElasticXS(), and GetElementCrossSection().
G4UPiNuclearCrossSection* G4BGGPionElasticXS::fPion private
Definition at line 116 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 116 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionElasticXS(), and GetElementCrossSection().
G4bool G4BGGPionElasticXS::isMaster private
Definition at line 119 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 119 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), and G4BGGPionElasticXS().
G4bool G4BGGPionElasticXS::isPiplus private
Definition at line 118 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 118 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), G4BGGPionElasticXS(), and GetElementCrossSection().
G4int G4BGGPionElasticXS::theA = {0} static private
Definition at line 108 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 108 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactorPiPlus(), and GetElementCrossSection().
G4double G4BGGPionElasticXS::theCoulombFacPiMinus = {0.0} static private
Definition at line 107 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 107 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGPionElasticXS::theCoulombFacPiPlus = {0.0} static private
Definition at line 105 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 105 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGPionElasticXS::theGlauberFacPiMinus = {0.0} static private
Definition at line 106 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 106 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4double G4BGGPionElasticXS::theGlauberFacPiPlus = {0.0} static private
Definition at line 104 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 104 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
const G4ParticleDefinition* G4BGGPionElasticXS::thePiPlus private
Definition at line 111 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 111 of file G4BGGPionElasticXS.hh
Referenced by BuildPhysicsTable(), CoulombFactorPiPlus(), and G4BGGPionElasticXS().
const G4ParticleDefinition* G4BGGPionElasticXS::theProton private
Definition at line 110 of file G4BGGPionElasticXS.hh.
View newest version in sPHENIX GitHub at line 110 of file G4BGGPionElasticXS.hh
Referenced by G4BGGPionElasticXS(), and GetIsoCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4BGGPionElasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4BGGPionElasticXS.cc