ECCE @ EIC Software: G4RegularNavigation Class Reference
G4RegularNavigation Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4RegularNavigation.hh>
Public Member Functions
G4RegularNavigation ()
~G4RegularNavigation ()
G4bool LevelLocate (G4NavigationHistory &history, const G4VPhysicalVolume *blockedVol, const G4int blockedNum, const G4ThreeVector &globalPoint, const G4ThreeVector *globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector &localPoint)
G4double ComputeStep (const G4ThreeVector &globalPoint, const G4ThreeVector &globalDirection, const G4double currentProposedStepLength, G4double &newSafety, G4NavigationHistory &history, G4bool &validExitNormal, G4ThreeVector &exitNormal, G4bool &exiting, G4bool &entering, G4VPhysicalVolume *(*pBlockedPhysical), G4int &blockedReplicaNo)
G4double ComputeStepSkippingEqualMaterials (G4ThreeVector &localPoint, const G4ThreeVector &globalDirection, const G4double currentProposedStepLength, G4double &newSafety, G4NavigationHistory &history, G4bool &validExitNormal, G4ThreeVector &exitNormal, G4bool &exiting, G4bool &entering, G4VPhysicalVolume *(*pBlockedPhysical), G4int &blockedReplicaNo, G4VPhysicalVolume *pCurrentPhysical)
G4double ComputeSafety (const G4ThreeVector &localPoint, const G4NavigationHistory &history, const G4double pProposedMaxLength=DBL_MAX)
void SetVerboseLevel (G4int level)
void CheckMode (G4bool mode)
void SetNormalNavigation (G4NormalNavigation *fnormnav)
Private Attributes
G4int fverbose = false
G4bool fcheck = false
G4NormalNavigation * fnormalNav = nullptr
G4double kCarTolerance
G4double fMinStep
G4bool fLastStepWasZero
G4int fNumberZeroSteps
G4int fActionThreshold_NoZeroSteps
G4int fAbandonThreshold_NoZeroSteps
G4int fNoStepsAllowed
G4bool fWarnPush
Detailed Description
Definition at line 50 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RegularNavigation.hh
Constructor & Destructor Documentation
G4RegularNavigation::G4RegularNavigation ()
Definition at line 42 of file G4RegularNavigation.cc.
View newest version in sPHENIX GitHub at line 42 of file G4RegularNavigation.cc
References fAbandonThreshold_NoZeroSteps, fActionThreshold_NoZeroSteps, fMinStep, fNoStepsAllowed, fWarnPush, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), and kCarTolerance.
G4RegularNavigation::~G4RegularNavigation ()
Definition at line 55 of file G4RegularNavigation.cc.
View newest version in sPHENIX GitHub at line 55 of file G4RegularNavigation.cc
Member Function Documentation
void G4RegularNavigation::CheckMode (G4bool mode) inline
Definition at line 114 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 114 of file G4RegularNavigation.hh
References fcheck.
G4double G4RegularNavigation::ComputeSafety (const G4ThreeVector & localPoint, const G4NavigationHistory & history, const G4double pProposedMaxLength = DBL_MAX)
Definition at line 354 of file G4RegularNavigation.cc.
View newest version in sPHENIX GitHub at line 354 of file G4RegularNavigation.cc
References G4NormalNavigation::ComputeSafety(), and fnormalNav.
Referenced by G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), and G4ITNavigator2::ComputeSafety().
G4double G4RegularNavigation::ComputeStep (const G4ThreeVector & globalPoint, const G4ThreeVector & globalDirection, const G4double currentProposedStepLength, G4double & newSafety, G4NavigationHistory & history, G4bool & validExitNormal, G4ThreeVector & exitNormal, G4bool & exiting, G4bool & entering, G4VPhysicalVolume ** pBlockedPhysical, G4int & blockedReplicaNo)
Definition at line 62 of file G4RegularNavigation.cc.
View newest version in sPHENIX GitHub at line 62 of file G4RegularNavigation.cc
References G4NormalNavigation::ComputeStep(), fnormalNav, G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetParameterisation(), G4PhantomParameterisation::GetReplicaNo(), G4NavigationHistory::GetTopTransform(), G4NavigationHistory::GetTopVolume(), G4PhantomParameterisation::GetTranslation(), G4AffineTransform::InverseTransformAxis(), G4AffineTransform::InverseTransformPoint(), and LevelLocate().
Referenced by G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), and G4ITNavigator2::ComputeStep().
G4double G4RegularNavigation::ComputeStepSkippingEqualMaterials (G4ThreeVector & localPoint, const G4ThreeVector & globalDirection, const G4double currentProposedStepLength, G4double & newSafety, G4NavigationHistory & history, G4bool & validExitNormal, G4ThreeVector & exitNormal, G4bool & exiting, G4bool & entering, G4VPhysicalVolume ** pBlockedPhysical, G4int & blockedReplicaNo, G4VPhysicalVolume * pCurrentPhysical)
Definition at line 124 of file G4RegularNavigation.cc.
View newest version in sPHENIX GitHub at line 124 of file G4RegularNavigation.cc
References G4RegularNavigationHelper::AddStepLength(), G4RegularNavigationHelper::ClearStepLengths(), G4PhantomParameterisation::ComputeMaterial(), G4NormalNavigation::ComputeStep(), G4VSolid::DistanceToOut(), EventMustBeAborted, fAbandonThreshold_NoZeroSteps, fActionThreshold_NoZeroSteps, fLastStepWasZero, fMinStep, fnormalNav, fNoStepsAllowed, fNumberZeroSteps, fWarnPush, G4cout, G4endl, G4Exception(), G4PhantomParameterisation::GetContainerSolid(), G4NavigationHistory::GetDepth(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetParameterisation(), G4PhantomParameterisation::GetReplicaNo(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTransform(), G4PhantomParameterisation::GetTranslation(), G4VSolid::Inside(), G4RegularNavigationHelper::Instance(), G4AffineTransform::InverseTransformPoint(), JustWarning, kCarTolerance, kInside, message(), min, G4PhantomParameterisation::SkipEqualMaterials(), and G4AffineTransform::TransformPoint().
G4bool G4RegularNavigation::LevelLocate (G4NavigationHistory & history, const G4VPhysicalVolume * blockedVol, const G4int blockedNum, const G4ThreeVector & globalPoint, const G4ThreeVector * globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector & localPoint)
Definition at line 374 of file G4RegularNavigation.cc.
View newest version in sPHENIX GitHub at line 374 of file G4RegularNavigation.cc
References G4PhantomParameterisation::ComputeMaterial(), G4PhantomParameterisation::ComputeTransformation(), G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4PhantomParameterisation::GetNoVoxel(), G4VPhysicalVolume::GetParameterisation(), G4PhantomParameterisation::GetReplicaNo(), G4NavigationHistory::GetTopTransform(), G4NavigationHistory::GetTopVolume(), kParameterised, G4NavigationHistory::NewLevel(), G4VPhysicalVolume::SetCopyNo(), G4AffineTransform::TransformAxis(), G4AffineTransform::TransformPoint(), and G4LogicalVolume::UpdateMaterial().
Referenced by ComputeStep(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), and G4ITNavigator2::LocateGlobalPointAndSetup().
void G4RegularNavigation::SetNormalNavigation (G4NormalNavigation * fnormnav) inline
Definition at line 115 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 115 of file G4RegularNavigation.hh
References fnormalNav.
Referenced by G4ITNavigator1::G4ITNavigator1(), G4ITNavigator2::G4ITNavigator2(), and G4Navigator::G4Navigator().
void G4RegularNavigation::SetVerboseLevel (G4int level) inline
Definition at line 113 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 113 of file G4RegularNavigation.hh
References fverbose.
Member Data Documentation
G4int G4RegularNavigation::fAbandonThreshold_NoZeroSteps private
Definition at line 133 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 133 of file G4RegularNavigation.hh
Referenced by ComputeStepSkippingEqualMaterials(), and G4RegularNavigation().
G4int G4RegularNavigation::fActionThreshold_NoZeroSteps private
Definition at line 131 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 131 of file G4RegularNavigation.hh
Referenced by ComputeStepSkippingEqualMaterials(), and G4RegularNavigation().
G4bool G4RegularNavigation::fcheck = false private
Definition at line 121 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 121 of file G4RegularNavigation.hh
Referenced by CheckMode().
G4bool G4RegularNavigation::fLastStepWasZero private
Definition at line 127 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 127 of file G4RegularNavigation.hh
Referenced by ComputeStepSkippingEqualMaterials().
G4double G4RegularNavigation::fMinStep private
Definition at line 125 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 125 of file G4RegularNavigation.hh
Referenced by ComputeStepSkippingEqualMaterials(), and G4RegularNavigation().
G4NormalNavigation* G4RegularNavigation::fnormalNav = nullptr private
Definition at line 123 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 123 of file G4RegularNavigation.hh
Referenced by ComputeSafety(), ComputeStep(), ComputeStepSkippingEqualMaterials(), and SetNormalNavigation().
G4int G4RegularNavigation::fNoStepsAllowed private
Definition at line 135 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 135 of file G4RegularNavigation.hh
Referenced by ComputeStepSkippingEqualMaterials(), and G4RegularNavigation().
G4int G4RegularNavigation::fNumberZeroSteps private
Definition at line 129 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 129 of file G4RegularNavigation.hh
Referenced by ComputeStepSkippingEqualMaterials().
G4int G4RegularNavigation::fverbose = false private
Definition at line 120 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 120 of file G4RegularNavigation.hh
Referenced by SetVerboseLevel().
G4bool G4RegularNavigation::fWarnPush private
Definition at line 138 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 138 of file G4RegularNavigation.hh
Referenced by ComputeStepSkippingEqualMaterials(), and G4RegularNavigation().
G4double G4RegularNavigation::kCarTolerance private
Definition at line 124 of file G4RegularNavigation.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RegularNavigation.hh
Referenced by ComputeStepSkippingEqualMaterials(), and G4RegularNavigation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4RegularNavigation.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4RegularNavigation.cc