ECCE @ EIC Software: DMXPmtHit Class Reference
DMXPmtHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXPmtHit.hh>
Public Member Functions
DMXPmtHit ()
~DMXPmtHit ()
DMXPmtHit (const DMXPmtHit &)
const DMXPmtHit & operator= (const DMXPmtHit &)
G4bool operator== (const DMXPmtHit &) const
void * operator new (size_t)
void operator delete (void *)
void Draw ()
void Print ()
void SetPos (G4ThreeVector xyz)
G4ThreeVector GetPos () const
void SetTime (G4double t)
G4double GetTime () const
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Private Attributes
G4ThreeVector pos
G4double time
Detailed Description
Definition at line 51 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 51 of file DMXPmtHit.hh
Constructor & Destructor Documentation
DMXPmtHit::DMXPmtHit ()
Definition at line 56 of file DMXPmtHit.cc.
View newest version in sPHENIX GitHub at line 56 of file DMXPmtHit.cc
References pos, and time.
DMXPmtHit::~DMXPmtHit ()
Definition at line 66 of file DMXPmtHit.cc.
View newest version in sPHENIX GitHub at line 66 of file DMXPmtHit.cc
DMXPmtHit::DMXPmtHit (const DMXPmtHit & right)
Definition at line 70 of file DMXPmtHit.cc.
View newest version in sPHENIX GitHub at line 70 of file DMXPmtHit.cc
References pos, and time.
Member Function Documentation
void DMXPmtHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 98 of file DMXPmtHit.cc.
View newest version in sPHENIX GitHub at line 98 of file DMXPmtHit.cc
References G4VVisManager::Draw(), G4VMarker::filled, G4VVisManager::GetConcreteInstance(), pos, G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
G4ThreeVector DMXPmtHit::GetPos () const inline
Definition at line 75 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 75 of file DMXPmtHit.hh
References pos.
G4double DMXPmtHit::GetTime () const inline
Definition at line 78 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 78 of file DMXPmtHit.hh
References time.
void DMXPmtHit::operator delete (void * aHit) inline
Definition at line 98 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 98 of file DMXPmtHit.hh
References DMXPmtHitsAllocator.
void * DMXPmtHit::operator new (size_t) inline
Definition at line 91 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 91 of file DMXPmtHit.hh
References DMXPmtHitsAllocator.
const DMXPmtHit & DMXPmtHit::operator= (const DMXPmtHit & right)
Definition at line 79 of file DMXPmtHit.cc.
View newest version in sPHENIX GitHub at line 79 of file DMXPmtHit.cc
References pos, and time.
G4bool DMXPmtHit::operator== (const DMXPmtHit & right) const
Definition at line 90 of file DMXPmtHit.cc.
View newest version in sPHENIX GitHub at line 90 of file DMXPmtHit.cc
void DMXPmtHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 117 of file DMXPmtHit.cc.
View newest version in sPHENIX GitHub at line 117 of file DMXPmtHit.cc
References G4BestUnit, G4cout, G4endl, pos, and time.
void DMXPmtHit::SetPos (G4ThreeVector xyz) inline
Definition at line 74 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 74 of file DMXPmtHit.hh
References pos.
Referenced by DMXPmtSD::ProcessHits().
void DMXPmtHit::SetTime (G4double t) inline
Definition at line 77 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 77 of file DMXPmtHit.hh
References t, and time.
Referenced by DMXPmtSD::ProcessHits().
Member Data Documentation
G4ThreeVector DMXPmtHit::pos private
Definition at line 69 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 69 of file DMXPmtHit.hh
Referenced by DMXPmtHit(), Draw(), GetPos(), operator=(), Print(), and SetPos().
G4double DMXPmtHit::time private
Definition at line 70 of file DMXPmtHit.hh.
View newest version in sPHENIX GitHub at line 70 of file DMXPmtHit.hh
Referenced by DMXPmtHit(), GetTime(), operator=(), Print(), and SetTime().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/include/DMXPmtHit.hh
geant4/tree/geant4-10.6-release/examples/advanced/underground_physics/src/DMXPmtHit.cc