ECCE @ EIC Software: G4LeptonConstructor Class Reference
G4LeptonConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/leptons/include/G4LeptonConstructor.hh>
Public Member Functions
G4LeptonConstructor ()
~G4LeptonConstructor ()
Static Public Member Functions
static void ConstructParticle ()
Static Protected Member Functions
static void ConstructELeptons ()
static void ConstructMuLeptons ()
static void ConstructTauLeptons ()
Detailed Description
Definition at line 38 of file G4LeptonConstructor.hh.
View newest version in sPHENIX GitHub at line 38 of file G4LeptonConstructor.hh
Constructor & Destructor Documentation
G4LeptonConstructor::G4LeptonConstructor ()
Definition at line 50 of file G4LeptonConstructor.cc.
View newest version in sPHENIX GitHub at line 50 of file G4LeptonConstructor.cc
G4LeptonConstructor::~G4LeptonConstructor ()
Definition at line 54 of file G4LeptonConstructor.cc.
View newest version in sPHENIX GitHub at line 54 of file G4LeptonConstructor.cc
Member Function Documentation
void G4LeptonConstructor::ConstructELeptons () static protected
Definition at line 66 of file G4LeptonConstructor.cc.
View newest version in sPHENIX GitHub at line 66 of file G4LeptonConstructor.cc
References G4AntiNeutrinoE::AntiNeutrinoEDefinition(), G4Electron::ElectronDefinition(), G4NeutrinoE::NeutrinoEDefinition(), and G4Positron::PositronDefinition().
Referenced by ConstructParticle().
void G4LeptonConstructor::ConstructMuLeptons () static protected
Definition at line 74 of file G4LeptonConstructor.cc.
View newest version in sPHENIX GitHub at line 74 of file G4LeptonConstructor.cc
References G4AntiNeutrinoMu::AntiNeutrinoMuDefinition(), G4MuonMinus::MuonMinusDefinition(), G4MuonPlus::MuonPlusDefinition(), and G4NeutrinoMu::NeutrinoMuDefinition().
Referenced by ConstructParticle().
void G4LeptonConstructor::ConstructParticle (void) static
Definition at line 59 of file G4LeptonConstructor.cc.
View newest version in sPHENIX GitHub at line 59 of file G4LeptonConstructor.cc
References ConstructELeptons(), ConstructMuLeptons(), and ConstructTauLeptons().
Referenced by B03PhysicsList::ConstructAllLeptons(), Par02PhysicsList::ConstructLeptons(), EICPhysicsList::ConstructParticle(), GammaKnifeParticles::ConstructParticle(), HadrontherapyParticles::ConstructParticle(), G4ChannelingPhysics::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), Particles::ConstructParticle(), G4DecayPhysics::ConstructParticle(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructParticle(), and G4StoppingPhysics::ConstructParticle().
void G4LeptonConstructor::ConstructTauLeptons () static protected
Definition at line 82 of file G4LeptonConstructor.cc.
View newest version in sPHENIX GitHub at line 82 of file G4LeptonConstructor.cc
References G4AntiNeutrinoTau::AntiNeutrinoTauDefinition(), G4NeutrinoTau::NeutrinoTauDefinition(), G4TauMinus::TauMinusDefinition(), and G4TauPlus::TauPlusDefinition().
Referenced by ConstructParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/leptons/include/G4LeptonConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/leptons/src/G4LeptonConstructor.cc