ECCE @ EIC Software: CexmcIncidentParticleTrackInfo Class Reference
CexmcIncidentParticleTrackInfo Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcIncidentParticleTrackInfo.hh>
Public Member Functions
CexmcIncidentParticleTrackInfo (CexmcTrackType trackType=CexmcInsipidTrack)
G4int GetTypeInfo (void) const
G4double GetCurrentTrackLengthInTarget (void) const
void AddTrackLengthInTarget (G4double value)
void SetNeedsTrackLengthResampling (G4bool on=true)
G4double GetFinalTrackLengthInTarget (void) const
void SetFinalTrackLengthInTarget (G4double value)
void ResetCurrentTrackLengthInTarget (void)
G4bool NeedsTrackLengthResampling (void) const
G4bool IsStudiedProcessActivated (void) const
void ActivateStudiedProcess (G4bool on=true)
Public Member Functions inherited from CexmcTrackInfo
CexmcTrackInfo (CexmcTrackType trackType=CexmcInsipidTrack, G4int copyNumber=0)
void Print (void) const
CexmcTrackType GetTrackType (void) const
void SetTrackType (CexmcTrackType value)
G4int GetCopyNumber (void) const
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
const G4String & GetType () const
Private Attributes
G4double currentTrackLengthInTarget
G4double finalTrackLengthInTarget
G4bool isStudiedProcessActivated
G4bool needsTrackLengthResampling
Additional Inherited Members
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Detailed Description
Definition at line 50 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 50 of file CexmcIncidentParticleTrackInfo.hh
Constructor & Destructor Documentation
CexmcIncidentParticleTrackInfo::CexmcIncidentParticleTrackInfo (CexmcTrackType trackType = CexmcInsipidTrack) explicit
Definition at line 47 of file CexmcIncidentParticleTrackInfo.cc.
View newest version in sPHENIX GitHub at line 47 of file CexmcIncidentParticleTrackInfo.cc
Member Function Documentation
void CexmcIncidentParticleTrackInfo::ActivateStudiedProcess (G4bool on = true) inline
Definition at line 145 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 145 of file CexmcIncidentParticleTrackInfo.hh
References isStudiedProcessActivated.
Referenced by CexmcTrackingAction::SetupIncidentParticleTrackInfo(), and CexmcSteppingAction::UserSteppingAction().
void CexmcIncidentParticleTrackInfo::AddTrackLengthInTarget (G4double value) inline
Definition at line 96 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 96 of file CexmcIncidentParticleTrackInfo.hh
References currentTrackLengthInTarget.
Referenced by CexmcSteppingAction::UserSteppingAction().
G4double CexmcIncidentParticleTrackInfo::GetCurrentTrackLengthInTarget (void) const inline
Definition at line 89 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 89 of file CexmcIncidentParticleTrackInfo.hh
References currentTrackLengthInTarget.
Referenced by CexmcStudiedProcess::PostStepGetPhysicalInteractionLength().
G4double CexmcIncidentParticleTrackInfo::GetFinalTrackLengthInTarget (void) const inline
Definition at line 110 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 110 of file CexmcIncidentParticleTrackInfo.hh
References finalTrackLengthInTarget.
Referenced by CexmcStudiedProcess::PostStepGetPhysicalInteractionLength().
G4int CexmcIncidentParticleTrackInfo::GetTypeInfo (void) const virtual
Reimplemented from CexmcTrackInfo.
Definition at line 56 of file CexmcIncidentParticleTrackInfo.cc.
View newest version in sPHENIX GitHub at line 56 of file CexmcIncidentParticleTrackInfo.cc
References CexmcIncidentParticleTrackType.
G4bool CexmcIncidentParticleTrackInfo::IsStudiedProcessActivated (void) const inline
Definition at line 138 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 138 of file CexmcIncidentParticleTrackInfo.hh
References isStudiedProcessActivated.
Referenced by CexmcStudiedProcess::PostStepGetPhysicalInteractionLength(), and CexmcSteppingAction::UserSteppingAction().
G4bool CexmcIncidentParticleTrackInfo::NeedsTrackLengthResampling (void) const inline
Definition at line 131 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 131 of file CexmcIncidentParticleTrackInfo.hh
References needsTrackLengthResampling.
Referenced by CexmcSteppingAction::UserSteppingAction().
void CexmcIncidentParticleTrackInfo::ResetCurrentTrackLengthInTarget (void) inline
Definition at line 124 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 124 of file CexmcIncidentParticleTrackInfo.hh
References currentTrackLengthInTarget.
Referenced by CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget().
void CexmcIncidentParticleTrackInfo::SetFinalTrackLengthInTarget (G4double value) inline
Definition at line 117 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 117 of file CexmcIncidentParticleTrackInfo.hh
References finalTrackLengthInTarget.
Referenced by CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget().
void CexmcIncidentParticleTrackInfo::SetNeedsTrackLengthResampling (G4bool on = true) inline
Definition at line 103 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 103 of file CexmcIncidentParticleTrackInfo.hh
References needsTrackLengthResampling.
Referenced by CexmcHadronicProcess::PostStepDoIt(), and CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget().
Member Data Documentation
G4double CexmcIncidentParticleTrackInfo::currentTrackLengthInTarget private
Definition at line 79 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 79 of file CexmcIncidentParticleTrackInfo.hh
Referenced by AddTrackLengthInTarget(), GetCurrentTrackLengthInTarget(), and ResetCurrentTrackLengthInTarget().
G4double CexmcIncidentParticleTrackInfo::finalTrackLengthInTarget private
Definition at line 81 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 81 of file CexmcIncidentParticleTrackInfo.hh
Referenced by GetFinalTrackLengthInTarget(), and SetFinalTrackLengthInTarget().
G4bool CexmcIncidentParticleTrackInfo::isStudiedProcessActivated private
Definition at line 83 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 83 of file CexmcIncidentParticleTrackInfo.hh
Referenced by ActivateStudiedProcess(), and IsStudiedProcessActivated().
G4bool CexmcIncidentParticleTrackInfo::needsTrackLengthResampling private
Definition at line 85 of file CexmcIncidentParticleTrackInfo.hh.
View newest version in sPHENIX GitHub at line 85 of file CexmcIncidentParticleTrackInfo.hh
Referenced by NeedsTrackLengthResampling(), and SetNeedsTrackLengthResampling().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcIncidentParticleTrackInfo.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcIncidentParticleTrackInfo.cc