ECCE @ EIC Software: CLHEP::RandPoissonQ Class Reference
CLHEP::RandPoissonQ Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandPoissonQ.h>
Public Member Functions
RandPoissonQ (HepRandomEngine &anEngine, double b1=1.0)
RandPoissonQ (HepRandomEngine *anEngine, double b1=1.0)
virtual ~RandPoissonQ ()
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
long fire ()
long fire (double m)
void fireArray (const int size, long *vect)
void fireArray (const int size, long *vect, double m)
double operator() ()
double operator() (double m)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::RandPoisson
RandPoisson (HepRandomEngine &anEngine, double a1=1.0)
RandPoisson (HepRandomEngine *anEngine, double a1=1.0)
virtual ~RandPoisson ()
long fire ()
long fire (double m)
void fireArray (const int size, long *vect)
void fireArray (const int size, long *vect, double m)
double operator() (double m)
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static long shoot (double m=1.0)
static void shootArray (const int size, long *vect, double m=1.0)
static long shoot (HepRandomEngine *anEngine, double m=1.0)
static void shootArray (HepRandomEngine *anEngine, const int size, long *vect, double m=1.0)
static std::string distributionName ()
static int tableBoundary ()
Static Public Member Functions inherited from CLHEP::RandPoisson
static long shoot (double m=1.0)
static void shootArray (const int size, long *vect, double m=1.0)
static long shoot (HepRandomEngine *anEngine, double m=1.0)
static void shootArray (HepRandomEngine *anEngine, const int size, long *vect, double m=1.0)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Public Attributes
static const double MAXIMUM_POISSON_DEVIATE = 2.0E9
Private Member Functions
void setupForDefaultMu ()
Static Private Member Functions
static long poissonDeviateSmall (HepRandomEngine *e, double mean)
static long poissonDeviateQuick (HepRandomEngine *e, double mean)
static long poissonDeviateQuick (HepRandomEngine *e, double A0, double A1, double A2, double sig)
Private Attributes
double a0
double a1
double a2
double sigma
Static Private Attributes
static const double FIRST_MU = 10
static const double LAST_MU = 95
static const double S = 5
static const int BELOW = 30
static const int ENTRIES = 51
Additional Inherited Members
Protected Member Functions inherited from CLHEP::RandPoisson
HepRandomEngine * getLocalEngine ()
Static Protected Member Functions inherited from CLHEP::RandPoisson
static double getOldMean ()
static double getMaxMean ()
static void setOldMean (double val)
static double * getPStatus ()
static void setPStatus (double sq, double alxm, double g1)
Protected Attributes inherited from CLHEP::RandPoisson
double meanMax
double defaultMean
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 31 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 31 of file RandPoissonQ.h
Constructor & Destructor Documentation
CLHEP::RandPoissonQ::RandPoissonQ (HepRandomEngine & anEngine, double b1 = 1.0) inline
CLHEP::RandPoissonQ::RandPoissonQ (HepRandomEngine * anEngine, double b1 = 1.0) inline
CLHEP::RandPoissonQ::~RandPoissonQ () virtual
Definition at line 79 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 79 of file RandPoissonQ.cc
Member Function Documentation
static std::string CLHEP::RandPoissonQ::distributionName () inline static
Definition at line 101 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 101 of file RandPoissonQ.h
HepRandomEngine & CLHEP::RandPoissonQ::engine () virtual
Reimplemented from CLHEP::RandPoisson.
Definition at line 49 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 49 of file RandPoissonQ.cc
References CLHEP::RandPoisson::engine().
long CLHEP::RandPoissonQ::fire ()
Definition at line 132 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 132 of file RandPoissonQ.cc
References a0, a1, a2, CLHEP::RandPoisson::defaultMean, CLHEP::RandPoisson::getLocalEngine(), LAST_MU, poissonDeviateQuick(), poissonDeviateSmall(), S, and sigma.
Referenced by fireArray(), and operator()().
long CLHEP::RandPoissonQ::fire (double m)
Definition at line 128 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 128 of file RandPoissonQ.cc
References CLHEP::RandPoisson::getLocalEngine(), and shoot().
void CLHEP::RandPoissonQ::fireArray (const int size, long * vect)
Definition at line 184 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 184 of file RandPoissonQ.cc
References CLHEP::RandPoisson::defaultMean, fire(), and v.
void CLHEP::RandPoissonQ::fireArray (const int size, long * vect, double m)
Definition at line 179 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 179 of file RandPoissonQ.cc
References fire(), and v.
std::istream & CLHEP::RandPoissonQ::get (std::istream & is) virtual
Reimplemented from CLHEP::RandPoisson.
Definition at line 571 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 571 of file RandPoissonQ.cc
References a0, a1, a2, CLHEP::RandPoisson::get(), CLHEP::DoubConv::longs2double(), name(), CLHEP::possibleKeywordInput(), sigma, and t.
std::string CLHEP::RandPoissonQ::name () const virtual
Reimplemented from CLHEP::RandPoisson.
Definition at line 48 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 48 of file RandPoissonQ.cc
Referenced by get(), and put().
double CLHEP::RandPoissonQ::operator() () virtual
Reimplemented from CLHEP::RandPoisson.
Definition at line 120 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 120 of file RandPoissonQ.cc
References fire().
double CLHEP::RandPoissonQ::operator() (double m)
Definition at line 124 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 124 of file RandPoissonQ.cc
References fire().
long CLHEP::RandPoissonQ::poissonDeviateQuick (HepRandomEngine * e, double mean) static private
Definition at line 192 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 192 of file RandPoissonQ.cc
References t.
Referenced by fire(), and shoot().
long CLHEP::RandPoissonQ::poissonDeviateQuick (HepRandomEngine * e, double A0, double A1, double A2, double sig) static private
Definition at line 216 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 216 of file RandPoissonQ.cc
References CLHEP::g, MAXIMUM_POISSON_DEVIATE, and CLHEP::RandGaussQ::shoot().
long CLHEP::RandPoissonQ::poissonDeviateSmall (HepRandomEngine * e, double mean) static private
Definition at line 254 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 254 of file RandPoissonQ.cc
References a, b, BELOW, c, E, ENTRIES, FIRST_MU, CLHEP::HepRandomEngine::flat(), int(), LAST_MU, N, CLHEP::poissonTables, r, S, CLHEP::s, and CLHEP::RandPoisson::shoot().
Referenced by fire(), and shoot().
std::ostream & CLHEP::RandPoissonQ::put (std::ostream & os) const virtual
Reimplemented from CLHEP::RandPoisson.
Definition at line 544 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 544 of file RandPoissonQ.cc
References a0, a1, a2, CLHEP::DoubConv::dto2longs(), name(), gammaraytel::pr, CLHEP::RandPoisson::put(), sigma, and t.
void CLHEP::RandPoissonQ::setupForDefaultMu () private
Definition at line 82 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 82 of file RandPoissonQ.cc
References a0, a1, a2, CLHEP::RandPoisson::defaultMean, sigma, and t.
long CLHEP::RandPoissonQ::shoot (double m = 1.0) static
Definition at line 116 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 116 of file RandPoissonQ.cc
References CLHEP::HepRandom::getTheEngine().
Referenced by fire(), and shootArray().
long CLHEP::RandPoissonQ::shoot (HepRandomEngine * anEngine, double m = 1.0) static
Definition at line 140 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 140 of file RandPoissonQ.cc
References CLHEP_THREAD_LOCAL, LAST_MU, poissonDeviateQuick(), poissonDeviateSmall(), S, and t.
void CLHEP::RandPoissonQ::shootArray (const int size, long * vect, double m = 1.0) static
Definition at line 171 of file RandPoissonQ.cc.
View newest version in sPHENIX GitHub at line 171 of file RandPoissonQ.cc
References shoot(), and v.
static void CLHEP::RandPoissonQ::shootArray (HepRandomEngine * anEngine, const int size, long * vect, double m = 1.0) static
static int CLHEP::RandPoissonQ::tableBoundary () inline static
Member Data Documentation
double CLHEP::RandPoissonQ::a0 private
Definition at line 127 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 127 of file RandPoissonQ.h
Referenced by fire(), get(), put(), and setupForDefaultMu().
double CLHEP::RandPoissonQ::a1 private
Definition at line 128 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 128 of file RandPoissonQ.h
Referenced by fire(), get(), put(), and setupForDefaultMu().
double CLHEP::RandPoissonQ::a2 private
Definition at line 129 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 129 of file RandPoissonQ.h
Referenced by fire(), get(), put(), and setupForDefaultMu().
const int CLHEP::RandPoissonQ::BELOW = 30 static private
Definition at line 145 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 145 of file RandPoissonQ.h
Referenced by poissonDeviateSmall().
const int CLHEP::RandPoissonQ::ENTRIES = 51 static private
Definition at line 146 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 146 of file RandPoissonQ.h
Referenced by poissonDeviateSmall().
const double CLHEP::RandPoissonQ::FIRST_MU = 10 static private
Definition at line 142 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 142 of file RandPoissonQ.h
Referenced by poissonDeviateSmall().
const double CLHEP::RandPoissonQ::LAST_MU = 95 static private
Definition at line 143 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 143 of file RandPoissonQ.h
Referenced by fire(), poissonDeviateSmall(), and shoot().
const double CLHEP::RandPoissonQ::MAXIMUM_POISSON_DEVIATE = 2.0E9 static
Definition at line 108 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 108 of file RandPoissonQ.h
Referenced by poissonDeviateQuick().
const double CLHEP::RandPoissonQ::S = 5 static private
Definition at line 144 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 144 of file RandPoissonQ.h
Referenced by fire(), poissonDeviateSmall(), and shoot().
double CLHEP::RandPoissonQ::sigma private
Definition at line 130 of file RandPoissonQ.h.
View newest version in sPHENIX GitHub at line 130 of file RandPoissonQ.h
Referenced by fire(), get(), put(), and setupForDefaultMu().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandPoissonQ.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandPoissonQ.cc