ECCE @ EIC Software: G4StatMFMacroTetraNucleon Class Reference
G4StatMFMacroTetraNucleon Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroTetraNucleon.hh>
Public Member Functions
G4StatMFMacroTetraNucleon ()
~G4StatMFMacroTetraNucleon ()
G4double CalcMeanMultiplicity (const G4double FreeVol, const G4double mu, const G4double nu, const G4double T)
G4double CalcZARatio (const G4double)
G4double CalcEnergy (const G4double T)
G4double CalcEntropy (const G4double T, const G4double FreeVol)
Public Member Functions inherited from G4VStatMFMacroCluster
G4VStatMFMacroCluster (const G4int Size)
virtual ~G4VStatMFMacroCluster ()
G4bool operator== (const G4VStatMFMacroCluster &right) const
G4bool operator!= (const G4VStatMFMacroCluster &right) const
G4double GetMeanMultiplicity (void) const
G4double GetInvLevelDensity (void) const
void SetZARatio (const G4double value)
G4double GetZARatio (void) const
void SetSize (const G4double value)
G4double GetSize (void) const
Private Member Functions
G4StatMFMacroTetraNucleon (const G4StatMFMacroTetraNucleon &right)
G4StatMFMacroTetraNucleon & operator= (const G4StatMFMacroTetraNucleon &right)
G4bool operator== (const G4StatMFMacroTetraNucleon &right) const
G4bool operator!= (const G4StatMFMacroTetraNucleon &right) const
Additional Inherited Members
Protected Attributes inherited from G4VStatMFMacroCluster
G4int theA
G4double _InvLevelDensity
G4double _Entropy
G4double theZARatio
G4double _MeanMultiplicity
G4double _Energy
Detailed Description
Definition at line 37 of file G4StatMFMacroTetraNucleon.hh.
View newest version in sPHENIX GitHub at line 37 of file G4StatMFMacroTetraNucleon.hh
Constructor & Destructor Documentation
G4StatMFMacroTetraNucleon::G4StatMFMacroTetraNucleon ()
Definition at line 38 of file G4StatMFMacroTetraNucleon.cc.
View newest version in sPHENIX GitHub at line 38 of file G4StatMFMacroTetraNucleon.cc
G4StatMFMacroTetraNucleon::~G4StatMFMacroTetraNucleon ()
Definition at line 42 of file G4StatMFMacroTetraNucleon.cc.
View newest version in sPHENIX GitHub at line 42 of file G4StatMFMacroTetraNucleon.cc
G4StatMFMacroTetraNucleon::G4StatMFMacroTetraNucleon (const G4StatMFMacroTetraNucleon & right) private
Member Function Documentation
G4double G4StatMFMacroTetraNucleon::CalcEnergy (const G4double T) virtual
Implements G4VStatMFMacroCluster.
Definition at line 69 of file G4StatMFMacroTetraNucleon.cc.
View newest version in sPHENIX GitHub at line 69 of file G4StatMFMacroTetraNucleon.cc
References G4VStatMFMacroCluster::_Energy, G4VStatMFMacroCluster::_InvLevelDensity, G4NucleiProperties::GetBindingEnergy(), G4StatMFParameters::GetCoulomb(), G4Pow::GetInstance(), G4VStatMFMacroCluster::theA, G4VStatMFMacroCluster::theZARatio, and G4Pow::Z23().
G4double G4StatMFMacroTetraNucleon::CalcEntropy (const G4double T, const G4double FreeVol) virtual
Implements G4VStatMFMacroCluster.
Definition at line 78 of file G4StatMFMacroTetraNucleon.cc.
View newest version in sPHENIX GitHub at line 78 of file G4StatMFMacroTetraNucleon.cc
References G4VStatMFMacroCluster::_InvLevelDensity, G4VStatMFMacroCluster::_MeanMultiplicity, fermi, and G4Log().
G4double G4StatMFMacroTetraNucleon::CalcMeanMultiplicity (const G4double FreeVol, const G4double mu, const G4double nu, const G4double T) virtual
Implements G4VStatMFMacroCluster.
Definition at line 46 of file G4StatMFMacroTetraNucleon.cc.
View newest version in sPHENIX GitHub at line 46 of file G4StatMFMacroTetraNucleon.cc
References G4VStatMFMacroCluster::_InvLevelDensity, G4VStatMFMacroCluster::_MeanMultiplicity, degeneracy, fermi, G4Exp(), G4NucleiProperties::GetBindingEnergy(), G4StatMFParameters::GetCoulomb(), G4Pow::GetInstance(), G4VStatMFMacroCluster::theA, G4VStatMFMacroCluster::theZARatio, and G4Pow::Z23().
G4double G4StatMFMacroTetraNucleon::CalcZARatio (const G4double) inline virtual
Implements G4VStatMFMacroCluster.
Definition at line 48 of file G4StatMFMacroTetraNucleon.hh.
View newest version in sPHENIX GitHub at line 48 of file G4StatMFMacroTetraNucleon.hh
References G4VStatMFMacroCluster::theZARatio.
G4bool G4StatMFMacroTetraNucleon::operator!= (const G4StatMFMacroTetraNucleon & right) const private
G4StatMFMacroTetraNucleon& G4StatMFMacroTetraNucleon::operator= (const G4StatMFMacroTetraNucleon & right) private
G4bool G4StatMFMacroTetraNucleon::operator== (const G4StatMFMacroTetraNucleon & right) const private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroTetraNucleon.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMacroTetraNucleon.cc