ECCE @ EIC Software: G4GEMChannel Class Reference
G4GEMChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/include/G4GEMChannel.hh>
Inherits G4VEvaporationChannel.
Inherited by G4AlphaGEMChannel, G4B10GEMChannel, G4B11GEMChannel, G4B12GEMChannel, G4B13GEMChannel, G4B8GEMChannel, G4Be10GEMChannel, G4Be11GEMChannel, G4Be12GEMChannel, G4Be7GEMChannel, G4Be9GEMChannel, G4C10GEMChannel, G4C11GEMChannel, G4C12GEMChannel, G4C13GEMChannel, G4C14GEMChannel, G4C15GEMChannel, G4C16GEMChannel, G4DeuteronGEMChannel, G4F17GEMChannel, G4F18GEMChannel, G4F19GEMChannel, G4F20GEMChannel, G4F21GEMChannel, G4He3GEMChannel, G4He6GEMChannel, G4He8GEMChannel, G4Li6GEMChannel, G4Li7GEMChannel, G4Li8GEMChannel, G4Li9GEMChannel, G4Mg22GEMChannel, G4Mg23GEMChannel, G4Mg24GEMChannel, G4Mg25GEMChannel, G4Mg26GEMChannel, G4Mg27GEMChannel, G4Mg28GEMChannel, G4N12GEMChannel, G4N13GEMChannel, G4N14GEMChannel, G4N15GEMChannel, G4N16GEMChannel, G4N17GEMChannel, G4Na21GEMChannel, G4Na22GEMChannel, G4Na23GEMChannel, G4Na24GEMChannel, G4Na25GEMChannel, G4Ne18GEMChannel, G4Ne19GEMChannel, G4Ne20GEMChannel, G4Ne21GEMChannel, G4Ne22GEMChannel, G4Ne23GEMChannel, G4Ne24GEMChannel, G4NeutronGEMChannel, G4O14GEMChannel, G4O15GEMChannel, G4O16GEMChannel, G4O17GEMChannel, G4O18GEMChannel, G4O19GEMChannel, G4O20GEMChannel, G4ProtonGEMChannel, and G4TritonGEMChannel.
Public Member Functions
G4GEMChannel (G4int theA, G4int theZ, const G4String &aName, G4GEMProbability *aEmissionStrategy)
virtual ~G4GEMChannel ()
virtual G4double GetEmissionProbability (G4Fragment *theNucleus)
virtual G4Fragment * EmittedFragment (G4Fragment *theNucleus)
virtual void Dump () const
void SetLevelDensityParameter (G4VLevelDensityParameter *aLevelDensity)
Public Member Functions inherited from G4VEvaporationChannel
G4VEvaporationChannel (const G4String &aName="")
virtual ~G4VEvaporationChannel ()
virtual void Initialise ()
virtual G4double GetLifeTime (G4Fragment *theNucleus)
virtual G4bool BreakUpChain (G4FragmentVector *theResult, G4Fragment *theNucleus)
G4FragmentVector * BreakUpFragment (G4Fragment *theNucleus)
virtual void SetICM (G4bool)
virtual void RDMForced (G4bool)
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
Private Member Functions
G4double SampleKineticEnergy (const G4Fragment &fragment)
G4GEMChannel (const G4GEMChannel &right)=delete
const G4GEMChannel & operator= (const G4GEMChannel &right)=delete
G4bool operator== (const G4GEMChannel &right) const =delete
G4bool operator!= (const G4GEMChannel &right) const =delete
Private Attributes
G4int A
G4int Z
G4int ResidualA
G4int ResidualZ
G4double EvaporatedMass
G4double ResidualMass
G4double CoulombBarrier
G4double EmissionProbability
G4double MaximalKineticEnergy
G4Pow * fG4pow
G4GEMProbability * theEvaporationProbabilityPtr
G4bool MyOwnLevelDensity
G4VLevelDensityParameter * theLevelDensityPtr
G4VCoulombBarrier * theCoulombBarrierPtr
G4NuclearLevelData * fNucData
Additional Inherited Members
Protected Attributes inherited from G4VEvaporationChannel
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 47 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4GEMChannel.hh
Constructor & Destructor Documentation
G4GEMChannel::G4GEMChannel (G4int theA, G4int theZ, const G4String & aName, G4GEMProbability * aEmissionStrategy) explicit
Definition at line 48 of file G4GEMChannel.cc.
View newest version in sPHENIX GitHub at line 48 of file G4GEMChannel.cc
References A, CoulombBarrier, EvaporatedMass, fG4pow, fNucData, G4Pow::GetInstance(), G4NuclearLevelData::GetInstance(), G4NucleiProperties::GetNuclearMass(), MyOwnLevelDensity, ResidualA, ResidualMass, ResidualZ, G4GEMProbability::SetCoulomBarrier(), theCoulombBarrierPtr, theEvaporationProbabilityPtr, theLevelDensityPtr, and Z.
G4GEMChannel::~G4GEMChannel () virtual
Definition at line 68 of file G4GEMChannel.cc.
View newest version in sPHENIX GitHub at line 68 of file G4GEMChannel.cc
References MyOwnLevelDensity, theCoulombBarrierPtr, and theLevelDensityPtr.
G4GEMChannel::G4GEMChannel (const G4GEMChannel & right) private delete
Member Function Documentation
void G4GEMChannel::Dump () const virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 249 of file G4GEMChannel.cc.
View newest version in sPHENIX GitHub at line 249 of file G4GEMChannel.cc
References G4GEMProbability::Dump(), and theEvaporationProbabilityPtr.
G4Fragment * G4GEMChannel::EmittedFragment (G4Fragment * theNucleus) virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 127 of file G4GEMChannel.cc.
View newest version in sPHENIX GitHub at line 127 of file G4GEMChannel.cc
References A, CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), EvaporatedMass, G4RandomDirection(), G4Fragment::GetMomentum(), momentum, ResidualA, ResidualZ, SampleKineticEnergy(), G4Fragment::SetMomentum(), G4Fragment::SetZandA_asInt(), and Z.
G4double G4GEMChannel::GetEmissionProbability (G4Fragment * theNucleus) virtual
Implements G4VEvaporationChannel.
Definition at line 74 of file G4GEMChannel.cc.
View newest version in sPHENIX GitHub at line 74 of file G4GEMChannel.cc
References A, CoulombBarrier, EmissionProbability, EvaporatedMass, fNucData, G4Fragment::GetA_asInt(), G4VCoulombBarrier::GetCoulombBarrier(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetGroundStateMass(), G4NucleiProperties::GetNuclearMass(), G4NuclearLevelData::GetPairingCorrection(), G4Fragment::GetZ_asInt(), MaximalKineticEnergy, ResidualA, ResidualMass, ResidualZ, theCoulombBarrierPtr, theEvaporationProbabilityPtr, and Z.
G4bool G4GEMChannel::operator!= (const G4GEMChannel & right) const private delete
const G4GEMChannel& G4GEMChannel::operator= (const G4GEMChannel & right) private delete
G4bool G4GEMChannel::operator== (const G4GEMChannel & right) const private delete
G4double G4GEMChannel::SampleKineticEnergy (const G4Fragment & fragment) private
Definition at line 147 of file G4GEMChannel.cc.
View newest version in sPHENIX GitHub at line 147 of file G4GEMChannel.cc
References a, A, Alpha, G4GEMProbability::CalcAlphaParam(), G4GEMProbability::CalcBetaParam(), CoulombBarrier, e2, EmissionProbability, EvaporatedMass, fermi, fG4pow, fNucData, G4Exp(), G4Log(), G4UniformRand, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetPairingCorrection(), G4GEMProbability::GetSpin(), G4Fragment::GetZ_asInt(), source.hepunit::hbarc, G4VLevelDensityParameter::LevelDensityParameter(), MaximalKineticEnergy, MeV, pi, pi2, ResidualA, ResidualZ, T, theEvaporationProbabilityPtr, theLevelDensityPtr, x, x1, and G4Pow::Z13().
Referenced by EmittedFragment().
void G4GEMChannel::SetLevelDensityParameter (G4VLevelDensityParameter * aLevelDensity) inline
Definition at line 63 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GEMChannel.hh
References MyOwnLevelDensity, and theLevelDensityPtr.
Member Data Documentation
G4int G4GEMChannel::A private
Definition at line 85 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4GEMChannel.hh
Referenced by EmittedFragment(), G4GEMChannel(), GetEmissionProbability(), and SampleKineticEnergy().
G4double G4GEMChannel::CoulombBarrier private
Definition at line 98 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4GEMChannel.hh
Referenced by G4GEMChannel(), GetEmissionProbability(), and SampleKineticEnergy().
G4double G4GEMChannel::EmissionProbability private
Definition at line 99 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 99 of file G4GEMChannel.hh
Referenced by GetEmissionProbability(), and SampleKineticEnergy().
G4double G4GEMChannel::EvaporatedMass private
Definition at line 96 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 96 of file G4GEMChannel.hh
Referenced by EmittedFragment(), G4GEMChannel(), GetEmissionProbability(), and SampleKineticEnergy().
G4Pow* G4GEMChannel::fG4pow private
Definition at line 104 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4GEMChannel.hh
Referenced by G4GEMChannel(), and SampleKineticEnergy().
G4NuclearLevelData* G4GEMChannel::fNucData private
Definition at line 116 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4GEMChannel.hh
Referenced by G4GEMChannel(), GetEmissionProbability(), and SampleKineticEnergy().
G4double G4GEMChannel::MaximalKineticEnergy private
Definition at line 102 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4GEMChannel.hh
Referenced by GetEmissionProbability(), and SampleKineticEnergy().
G4bool G4GEMChannel::MyOwnLevelDensity private
Definition at line 110 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4GEMChannel.hh
Referenced by G4GEMChannel(), SetLevelDensityParameter(), and ~G4GEMChannel().
G4int G4GEMChannel::ResidualA private
Definition at line 91 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 91 of file G4GEMChannel.hh
Referenced by EmittedFragment(), G4GEMChannel(), GetEmissionProbability(), and SampleKineticEnergy().
G4double G4GEMChannel::ResidualMass private
Definition at line 97 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4GEMChannel.hh
Referenced by G4GEMChannel(), and GetEmissionProbability().
G4int G4GEMChannel::ResidualZ private
Definition at line 94 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4GEMChannel.hh
Referenced by EmittedFragment(), G4GEMChannel(), GetEmissionProbability(), and SampleKineticEnergy().
G4VCoulombBarrier* G4GEMChannel::theCoulombBarrierPtr private
Definition at line 114 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4GEMChannel.hh
Referenced by G4GEMChannel(), GetEmissionProbability(), and ~G4GEMChannel().
G4GEMProbability* G4GEMChannel::theEvaporationProbabilityPtr private
Definition at line 107 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4GEMChannel.hh
Referenced by Dump(), G4GEMChannel(), GetEmissionProbability(), and SampleKineticEnergy().
G4VLevelDensityParameter* G4GEMChannel::theLevelDensityPtr private
Definition at line 111 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4GEMChannel.hh
Referenced by G4GEMChannel(), SampleKineticEnergy(), SetLevelDensityParameter(), and ~G4GEMChannel().
G4int G4GEMChannel::Z private
Definition at line 88 of file G4GEMChannel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4GEMChannel.hh
Referenced by EmittedFragment(), G4GEMChannel(), and GetEmissionProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/include/G4GEMChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/src/G4GEMChannel.cc