ECCE @ EIC Software: G4Run Class Reference
G4Run Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4Run.hh>
Inherited by B01Run, B02Run, B03Run, B1Run, B1Run, B3bRun, B4bRunData, CexmcRun, DicomRun, doiPETRun, ElectronRun, G4RTRun, LXeRun, ML2Run, RE02Run, RE06Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, STCyclotronRun, and TSRun.
Public Member Functions
G4Run ()
virtual ~G4Run ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Protected Attributes
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Private Member Functions
G4Run (const G4Run &)
G4Run & operator= (const G4Run &)
Detailed Description
Definition at line 45 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 45 of file G4Run.hh
Constructor & Destructor Documentation
G4Run::G4Run ()
Definition at line 34 of file G4Run.cc.
View newest version in sPHENIX GitHub at line 34 of file G4Run.cc
References eventVector, and G4StatAnalysis::ResetCpuClock().
G4Run::~G4Run () virtual
Definition at line 42 of file G4Run.cc.
View newest version in sPHENIX GitHub at line 42 of file G4Run.cc
References eventVector, G4RunManager::GetRunManager(), G4RunManager::GetRunManagerType(), and G4RunManager::masterRM.
G4Run::G4Run (const G4Run &) inline private
Definition at line 53 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 53 of file G4Run.hh
Member Function Documentation
const G4DCtable* G4Run::GetDCtable () const inline
Definition at line 87 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 87 of file G4Run.hh
References DCtable.
const std::vector<const G4Event*>* G4Run::GetEventVector () const inline
Definition at line 114 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 114 of file G4Run.hh
References eventVector.
Referenced by G4VisManager::Enable(), G4VisManager::EndOfEvent(), G4VisManager::EndOfRun(), G4VisCommandSceneAddEventID::EventID::operator()(), G4VSceneHandler::ProcessScene(), G4VisCommandSceneEndOfEventAction::SetNewValue(), and G4VisCommandReviewKeptEvents::SetNewValue().
const G4HCtable* G4Run::GetHCtable () const inline
Definition at line 84 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 84 of file G4Run.hh
References HCtable.
G4int G4Run::GetNumberOfEvent () const inline
Definition at line 78 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 78 of file G4Run.hh
References numberOfEvent.
Referenced by STCyclotronRun::EndOfRun(), Run::EndOfRun(), RMC01AnalysisManager::EndOfRun(), ExGflashRunAction::EndOfRunAction(), B3aRunAction::EndOfRunAction(), G4HumanPhantomRunAction::EndOfRunAction(), ElectronRunAction::EndOfRunAction(), B3bRunAction::EndOfRunAction(), RE06RunAction::EndOfRunAction(), FW::Geant4::MMRunAction::EndOfRunAction(), DicomRunAction::EndOfRunAction(), B1RunAction::EndOfRunAction(), OpNoviceRunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), Dicom2RunAction::EndOfRunAction(), BrachyRunAction::EndOfRunAction(), PurgMagRunAction::EndOfRunAction(), B02RunAction::EndOfRunAction(), B03RunAction::EndOfRunAction(), B01RunAction::EndOfRunAction(), doiPETRunAction::EndOfRunAction(), TSRunAction::EndOfRunAction(), RE02RunAction::EndOfRunAction(), RunAction::EndWorker(), export_G4Run(), RunAction::PrintRunInfo(), G4VUserMPIrunMerger::Receive(), and G4VUserMPIrunMerger::Send().
G4int G4Run::GetNumberOfEventToBeProcessed () const inline
Definition at line 82 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 82 of file G4Run.hh
References numberOfEventToBeProcessed.
Referenced by RMC01AnalysisManager::BeginOfRun(), DicomRunAction::BeginOfRunAction(), TSRunAction::BeginOfRunAction(), export_G4Run(), G4VisCommandSceneAddEventID::EventID::operator()(), and RunAction::PrintRunInfo().
const G4String& G4Run::GetRandomNumberStatus () const inline
Definition at line 90 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 90 of file G4Run.hh
References randomNumberStatus.
G4int G4Run::GetRunID () const inline
Definition at line 75 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 75 of file G4Run.hh
References runID.
Referenced by CCalRunAction::BeginOfRunAction(), ExGflashRunAction::BeginOfRunAction(), F01RunAction::BeginOfRunAction(), B3aRunAction::BeginOfRunAction(), G4HumanPhantomRunAction::BeginOfRunAction(), FW::Geant4::MMRunAction::BeginOfRunAction(), eRositaRunAction::BeginOfRunAction(), B3bRunAction::BeginOfRunAction(), RE01RunAction::BeginOfRunAction(), RE05RunAction::BeginOfRunAction(), FCALRunAction::BeginOfRunAction(), F04RunAction::BeginOfRunAction(), ExN02RunAction::BeginOfRunAction(), OpNoviceRunAction::BeginOfRunAction(), DicomRunAction::BeginOfRunAction(), ExP01RunAction::BeginOfRunAction(), B1ConRunAction::BeginOfRunAction(), WLSRunAction::BeginOfRunAction(), PurgMagRunAction::BeginOfRunAction(), G03RunAction::BeginOfRunAction(), GammaRayTelRunAction::BeginOfRunAction(), UltraRunAction::BeginOfRunAction(), Par02RunAction::BeginOfRunAction(), G02RunAction::BeginOfRunAction(), B01RunAction::BeginOfRunAction(), B02RunAction::BeginOfRunAction(), B03RunAction::BeginOfRunAction(), CML2RunAction::BeginOfRunAction(), DMXRunAction::BeginOfRunAction(), doiPETRunAction::BeginOfRunAction(), B4bRunAction::BeginOfRunAction(), XrayFluoRunAction::BeginOfRunAction(), RMC01RunAction::BeginOfRunAction(), XrayTelRunAction::BeginOfRunAction(), RE02RunAction::BeginOfRunAction(), G4TrajectoriesModel::DescribeYourselfTo(), G4VisManager::Draw(), CCalRunAction::EndOfRunAction(), eRositaRunAction::EndOfRunAction(), DicomRunAction::EndOfRunAction(), Dicom2RunAction::EndOfRunAction(), GammaRayTelRunAction::EndOfRunAction(), UltraRunAction::EndOfRunAction(), export_G4Run(), G4WorkerRunManager::GenerateEvent(), G4RunManager::GenerateEvent(), G4VisCommandSceneAddEventID::EventID::operator()(), RunAction::PrintRunInfo(), G4WorkerRunManager::rndmSaveThisEvent(), G4RunManager::rndmSaveThisEvent(), G4WorkerRunManager::rndmSaveThisRun(), G4MTRunManager::rndmSaveThisRun(), G4RunManager::rndmSaveThisRun(), G4WorkerRunManager::RunInitialization(), G4RunManager::RunInitialization(), and WLSSteppingAction::SaveRandomStatus().
void G4Run::Merge (const G4Run * right) virtual
Reimplemented in Run, TSRun, Run, RE02Run, Dicom2Run, DicomRun, B01Run, B02Run, B03Run, Run, Run, LXeRun, doiPETRun, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, Run, G4RTRun, Run, Run, Run, Run, Run, ML2Run, Run, Run, Run, STCyclotronRun, B3bRun, ElectronRun, B1ConRun, B1Run, RE06Run, B1Run, Run, and Run.
Definition at line 58 of file G4Run.cc.
View newest version in sPHENIX GitHub at line 58 of file G4Run.cc
References eventVector, and numberOfEvent.
Referenced by B1Run::Merge(), RE06Run::Merge(), B3bRun::Merge(), ElectronRun::Merge(), STCyclotronRun::Merge(), ML2Run::Merge(), G4RTRun::Merge(), Run::Merge(), doiPETRun::Merge(), LXeRun::Merge(), B03Run::Merge(), B02Run::Merge(), B01Run::Merge(), DicomRun::Merge(), RE02Run::Merge(), TSRun::Merge(), G4MTRunManager::MergeRun(), and G4VUserMPIrunMerger::Receive().
G4Run& G4Run::operator= (const G4Run &) inline private
Definition at line 54 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 54 of file G4Run.hh
void G4Run::RecordEvent (const G4Event *) virtual
Reimplemented in TSRun, RE02Run, Dicom2Run, DicomRun, B01Run, B02Run, B03Run, Run, Run, G4RTRun, ML2Run, B3bRun, ElectronRun, and RE06Run.
Definition at line 55 of file G4Run.cc.
View newest version in sPHENIX GitHub at line 55 of file G4Run.cc
References numberOfEvent.
Referenced by G4RunManager::AnalyzeEvent(), G4VUserMPIrunMerger::Receive(), B3bRun::RecordEvent(), ElectronRun::RecordEvent(), Run::RecordEvent(), DicomRun::RecordEvent(), and TSRun::RecordEvent().
void G4Run::SetDCtable (G4DCtable * DCtbl) inline
Definition at line 100 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 100 of file G4Run.hh
References DCtable.
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
void G4Run::SetHCtable (G4HCtable * HCtbl) inline
Definition at line 98 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 98 of file G4Run.hh
References HCtable.
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
void G4Run::SetNumberOfEventToBeProcessed (G4int n_ev) inline
Definition at line 96 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Run.hh
References numberOfEventToBeProcessed.
Referenced by export_G4Run(), G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
void G4Run::SetRandomNumberStatus (G4String & st) inline
Definition at line 102 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 102 of file G4Run.hh
References randomNumberStatus.
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
void G4Run::SetRunID (G4int id) inline
Definition at line 94 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 94 of file G4Run.hh
References runID.
Referenced by export_G4Run(), G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
void G4Run::StoreEvent (G4Event * evt)
Definition at line 66 of file G4Run.cc.
View newest version in sPHENIX GitHub at line 66 of file G4Run.cc
References eventVector.
Referenced by G4RunManager::StackPreviousEvent().
Member Data Documentation
G4DCtable* G4Run::DCtable protected
Definition at line 61 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 61 of file G4Run.hh
Referenced by GetDCtable(), and SetDCtable().
std::vector<const G4Event*>* G4Run::eventVector protected
Definition at line 63 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 63 of file G4Run.hh
Referenced by G4Run(), GetEventVector(), Merge(), StoreEvent(), and ~G4Run().
G4HCtable* G4Run::HCtable protected
Definition at line 60 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 60 of file G4Run.hh
Referenced by GetHCtable(), and SetHCtable().
G4int G4Run::numberOfEvent protected
Definition at line 58 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 58 of file G4Run.hh
Referenced by Run::EndOfRun(), LXeRun::EndOfRun(), GetNumberOfEvent(), Merge(), RE06Run::RecordEvent(), ML2Run::RecordEvent(), B01Run::RecordEvent(), B02Run::RecordEvent(), B03Run::RecordEvent(), RecordEvent(), RE02Run::RecordEvent(), and Run::Run().
G4int G4Run::numberOfEventToBeProcessed protected
Definition at line 59 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 59 of file G4Run.hh
Referenced by GetNumberOfEventToBeProcessed(), and SetNumberOfEventToBeProcessed().
G4String G4Run::randomNumberStatus protected
Definition at line 62 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 62 of file G4Run.hh
Referenced by GetRandomNumberStatus(), and SetRandomNumberStatus().
G4int G4Run::runID protected
Definition at line 57 of file G4Run.hh.
View newest version in sPHENIX GitHub at line 57 of file G4Run.hh
Referenced by GetRunID(), and SetRunID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4Run.hh
geant4/tree/geant4-10.6-release/source/run/src/G4Run.cc