ECCE @ EIC Software: G4NeutronPHPBuilder Class Reference
G4NeutronPHPBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4NeutronPHPBuilder.hh>
Public Member Functions
G4NeutronPHPBuilder ()
virtual ~G4NeutronPHPBuilder ()
virtual void Build (G4HadronElasticProcess *aP) finaloverride
virtual void Build (G4HadronFissionProcess *aP) finaloverride
virtual void Build (G4HadronCaptureProcess *aP) finaloverride
virtual void Build (G4NeutronInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
void SetMinInelasticEnergy (G4double aM)
virtual void SetMaxEnergy (G4double aM) finaloverride
void SetMaxInelasticEnergy (G4double aM)
Public Member Functions inherited from G4VNeutronBuilder
G4VNeutronBuilder ()=default
virtual ~G4VNeutronBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4double theMin
G4double theIMin
G4double theMax
G4double theIMax
G4ParticleHPElastic * theHPElastic
G4ParticleHPElasticData * theHPElasticData
G4ParticleHPInelastic * theHPInelastic
G4ParticleHPInelasticData * theHPInelasticData
G4ParticleHPFission * theHPFission
G4ParticleHPFissionData * theHPFissionData
G4ParticleHPCapture * theHPCapture
G4ParticleHPCaptureData * theHPCaptureData
Detailed Description
Definition at line 46 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 46 of file G4NeutronPHPBuilder.hh
Constructor & Destructor Documentation
G4NeutronPHPBuilder::G4NeutronPHPBuilder ()
Definition at line 33 of file G4NeutronPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 33 of file G4NeutronPHPBuilder.cc
References MeV, theHPCapture, theHPCaptureData, theHPElastic, theHPElasticData, theHPFission, theHPFissionData, theHPInelastic, theHPInelasticData, theIMax, theIMin, theMax, and theMin.
virtual G4NeutronPHPBuilder::~G4NeutronPHPBuilder () inline virtual
Definition at line 50 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 50 of file G4NeutronPHPBuilder.hh
Member Function Documentation
void G4NeutronPHPBuilder::Build (G4HadronElasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 55 of file G4NeutronPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 55 of file G4NeutronPHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theHPElastic, theHPElasticData, theMax, and theMin.
void G4NeutronPHPBuilder::Build (G4HadronFissionProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 66 of file G4NeutronPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 66 of file G4NeutronPHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theHPFission, theHPFissionData, theMax, and theMin.
void G4NeutronPHPBuilder::Build (G4HadronCaptureProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 77 of file G4NeutronPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 77 of file G4NeutronPHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theHPCapture, theHPCaptureData, theMax, and theMin.
void G4NeutronPHPBuilder::Build (G4NeutronInelasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 88 of file G4NeutronPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronPHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theHPInelastic, theHPInelasticData, theIMax, and theIMin.
virtual void G4NeutronPHPBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 67 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4NeutronPHPBuilder.hh
References theIMax, and theMax.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels().
void G4NeutronPHPBuilder::SetMaxInelasticEnergy (G4double aM) inline
Definition at line 72 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4NeutronPHPBuilder.hh
References theIMax.
virtual void G4NeutronPHPBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 58 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4NeutronPHPBuilder.hh
References theIMin, and theMin.
void G4NeutronPHPBuilder::SetMinInelasticEnergy (G4double aM) inline
Definition at line 63 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4NeutronPHPBuilder.hh
References theIMin.
Member Data Documentation
G4ParticleHPCapture* G4NeutronPHPBuilder::theHPCapture private
Definition at line 92 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 92 of file G4NeutronPHPBuilder.hh
Referenced by Build(), and G4NeutronPHPBuilder().
G4ParticleHPCaptureData* G4NeutronPHPBuilder::theHPCaptureData private
Definition at line 93 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 93 of file G4NeutronPHPBuilder.hh
Referenced by Build(), and G4NeutronPHPBuilder().
G4ParticleHPElastic* G4NeutronPHPBuilder::theHPElastic private
Definition at line 86 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 86 of file G4NeutronPHPBuilder.hh
Referenced by Build(), and G4NeutronPHPBuilder().
G4ParticleHPElasticData* G4NeutronPHPBuilder::theHPElasticData private
Definition at line 87 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 87 of file G4NeutronPHPBuilder.hh
Referenced by Build(), and G4NeutronPHPBuilder().
G4ParticleHPFission* G4NeutronPHPBuilder::theHPFission private
Definition at line 90 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 90 of file G4NeutronPHPBuilder.hh
Referenced by Build(), and G4NeutronPHPBuilder().
G4ParticleHPFissionData* G4NeutronPHPBuilder::theHPFissionData private
Definition at line 91 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 91 of file G4NeutronPHPBuilder.hh
Referenced by Build(), and G4NeutronPHPBuilder().
G4ParticleHPInelastic* G4NeutronPHPBuilder::theHPInelastic private
Definition at line 88 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronPHPBuilder.hh
Referenced by Build(), and G4NeutronPHPBuilder().
G4ParticleHPInelasticData* G4NeutronPHPBuilder::theHPInelasticData private
Definition at line 89 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 89 of file G4NeutronPHPBuilder.hh
Referenced by Build(), and G4NeutronPHPBuilder().
G4double G4NeutronPHPBuilder::theIMax private
Definition at line 84 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 84 of file G4NeutronPHPBuilder.hh
Referenced by Build(), G4NeutronPHPBuilder(), SetMaxEnergy(), and SetMaxInelasticEnergy().
G4double G4NeutronPHPBuilder::theIMin private
Definition at line 82 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4NeutronPHPBuilder.hh
Referenced by Build(), G4NeutronPHPBuilder(), SetMinEnergy(), and SetMinInelasticEnergy().
G4double G4NeutronPHPBuilder::theMax private
Definition at line 83 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4NeutronPHPBuilder.hh
Referenced by Build(), G4NeutronPHPBuilder(), and SetMaxEnergy().
G4double G4NeutronPHPBuilder::theMin private
Definition at line 81 of file G4NeutronPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4NeutronPHPBuilder.hh
Referenced by Build(), G4NeutronPHPBuilder(), and SetMinEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4NeutronPHPBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4NeutronPHPBuilder.cc