ECCE @ EIC Software: G4BiasingOperationManager Class Reference
G4BiasingOperationManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4BiasingOperationManager.hh>
Public Member Functions
const std::vector
< G4VBiasingOperation * > GetBiasingOperations ()
G4VBiasingOperation * GetBiasingOperation (std::size_t optionID)
~G4BiasingOperationManager ()
std::size_t Register (G4VBiasingOperation *)
Static Public Member Functions
static G4BiasingOperationManager * GetInstance ()
Private Member Functions
G4BiasingOperationManager ()
Static Private Attributes
static G4VectorCache
< G4VBiasingOperation * > fBiasingOperationVector
static G4MapCache
< G4VBiasingOperation
*, std::size_t > fBiasingOperationIDtoPointerMap
Friends
class G4ThreadLocalSingleton< G4BiasingOperationManager >
Detailed Description
Definition at line 50 of file G4BiasingOperationManager.hh.
View newest version in sPHENIX GitHub at line 50 of file G4BiasingOperationManager.hh
Constructor & Destructor Documentation
G4BiasingOperationManager::~G4BiasingOperationManager ()
Definition at line 35 of file G4BiasingOperationManager.cc.
View newest version in sPHENIX GitHub at line 35 of file G4BiasingOperationManager.cc
G4BiasingOperationManager::G4BiasingOperationManager () private
Definition at line 32 of file G4BiasingOperationManager.cc.
View newest version in sPHENIX GitHub at line 32 of file G4BiasingOperationManager.cc
Member Function Documentation
G4VBiasingOperation * G4BiasingOperationManager::GetBiasingOperation (std::size_t optionID)
Definition at line 57 of file G4BiasingOperationManager.cc.
View newest version in sPHENIX GitHub at line 57 of file G4BiasingOperationManager.cc
References fBiasingOperationVector, and G4VectorCache< VALTYPE >::Size().
const std::vector< G4VBiasingOperation* > G4BiasingOperationManager::GetBiasingOperations () inline
Definition at line 54 of file G4BiasingOperationManager.hh.
View newest version in sPHENIX GitHub at line 54 of file G4BiasingOperationManager.hh
References fBiasingOperationVector, and G4Cache< VALTYPE >::Get().
G4BiasingOperationManager * G4BiasingOperationManager::GetInstance (void) static
Definition at line 38 of file G4BiasingOperationManager.cc.
View newest version in sPHENIX GitHub at line 38 of file G4BiasingOperationManager.cc
References instance, and G4ThreadLocalSingleton< T >::Instance().
Referenced by G4VBiasingOperation::G4VBiasingOperation().
std::size_t G4BiasingOperationManager::Register (G4VBiasingOperation * option)
Definition at line 47 of file G4BiasingOperationManager.cc.
View newest version in sPHENIX GitHub at line 47 of file G4BiasingOperationManager.cc
References fBiasingOperationIDtoPointerMap, fBiasingOperationVector, G4VectorCache< VALTYPE >::Push_back(), and G4VectorCache< VALTYPE >::Size().
Referenced by G4VBiasingOperation::G4VBiasingOperation().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4BiasingOperationManager > friend
Definition at line 51 of file G4BiasingOperationManager.hh.
View newest version in sPHENIX GitHub at line 51 of file G4BiasingOperationManager.hh
Member Data Documentation
G4MapCache< G4VBiasingOperation *, std::size_t > G4BiasingOperationManager::fBiasingOperationIDtoPointerMap static private
Definition at line 65 of file G4BiasingOperationManager.hh.
View newest version in sPHENIX GitHub at line 65 of file G4BiasingOperationManager.hh
Referenced by Register().
G4VectorCache< G4VBiasingOperation * > G4BiasingOperationManager::fBiasingOperationVector static private
Definition at line 64 of file G4BiasingOperationManager.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BiasingOperationManager.hh
Referenced by GetBiasingOperation(), GetBiasingOperations(), and Register().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4BiasingOperationManager.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/management/src/G4BiasingOperationManager.cc