ECCE @ EIC Software: B4dDetectorConstruction Class Reference
B4dDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B4/B4d/include/B4dDetectorConstruction.hh>
Public Member Functions
B4dDetectorConstruction ()
virtual ~B4dDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
G4VPhysicalVolume * DefineVolumes ()
Private Attributes
G4bool fCheckOverlaps
Static Private Attributes
static G4ThreadLocal
G4GlobalMagFieldMessenger * fMagFieldMessenger = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Detector construction class to define materials and geometry. The calorimeter is a box made of a given number of layers. A layer consists of an absorber plate and of a detection gap. The layer is replicated.
Four parameters define the geometry of the calorimeter :
the thickness of an absorber plate,
the thickness of a gap,
the number of layers,
the transverse size of the calorimeter (the input face is a square).
In ConstructSDandField() sensitive detectors of G4MultiFunctionalDetector type with primitive scorers are created and associated with the Absorber and Gap volumes. In addition a transverse uniform magnetic field is defined via G4GlobalMagFieldMessenger class.
Definition at line 55 of file B4dDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file B4dDetectorConstruction.hh
Constructor & Destructor Documentation
B4dDetectorConstruction::B4dDetectorConstruction ()
Definition at line 62 of file B4dDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 62 of file B4dDetectorConstruction.cc
B4dDetectorConstruction::~B4dDetectorConstruction () virtual
Definition at line 70 of file B4dDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 70 of file B4dDetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * B4dDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 76 of file B4dDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 76 of file B4dDetectorConstruction.cc
References DefineMaterials(), and DefineVolumes().
void B4dDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 278 of file B4dDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 278 of file B4dDetectorConstruction.cc
References G4SDManager::AddNewDetector(), fMagFieldMessenger, G4SDManager::GetSDMpointer(), G4AutoDelete::Register(), G4VPrimitiveScorer::SetFilter(), G4VUserDetectorConstruction::SetSensitiveDetector(), G4GlobalMagFieldMessenger::SetVerboseLevel(), and G4SDManager::SetVerboseLevel().
void B4dDetectorConstruction::DefineMaterials () private
Definition at line 87 of file B4dDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 87 of file B4dDetectorConstruction.cc
References a, cm3, e, Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetMaterialTable(), G4NistManager::Instance(), kelvin, kStateGas, mole, pascal, source.hepunit::universe_mean_density, and z.
Referenced by Construct().
G4VPhysicalVolume * B4dDetectorConstruction::DefineVolumes () private
Definition at line 110 of file B4dDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 110 of file B4dDetectorConstruction.cc
References cm, FatalException, fCheckOverlaps, G4cout, G4endl, G4Exception(), G4VisAttributes::GetInvisible(), G4Material::GetMaterial(), kZAxis, and mm.
Referenced by Construct().
Member Data Documentation
G4bool B4dDetectorConstruction::fCheckOverlaps private
Definition at line 76 of file B4dDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file B4dDetectorConstruction.hh
Referenced by DefineVolumes().
G4ThreadLocal G4GlobalMagFieldMessenger * B4dDetectorConstruction::fMagFieldMessenger = 0 static private
Definition at line 73 of file B4dDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file B4dDetectorConstruction.hh
Referenced by ConstructSDandField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B4/B4d/include/B4dDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/basic/B4/B4d/src/B4dDetectorConstruction.cc