ECCE @ EIC Software: G4TrajectoriesModel Class Reference
G4TrajectoriesModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoriesModel.hh>
Public Member Functions
G4TrajectoriesModel ()
virtual ~G4TrajectoriesModel ()
virtual void DescribeYourselfTo (G4VGraphicsScene &)
const G4VTrajectory * GetCurrentTrajectory () const
void SetCurrentTrajectory (const G4VTrajectory *pTraj)
void SetRunID (G4int runID)
void SetEventID (G4int eventID)
const std::map< G4String,
G4AttDef > * GetAttDefs () const
std::vector< G4AttValue > * CreateCurrentAttValues () const
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
virtual G4String GetCurrentDescription () const
virtual G4String GetCurrentTag () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
virtual G4bool Validate (G4bool warn=true)
Private Attributes
const G4VTrajectory * fpCurrentTrajectory
G4int fRunID
G4int fEventID
Additional Inherited Members
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Detailed Description
Definition at line 51 of file G4TrajectoriesModel.hh.
View newest version in sPHENIX GitHub at line 51 of file G4TrajectoriesModel.hh
Constructor & Destructor Documentation
G4TrajectoriesModel::G4TrajectoriesModel ()
Definition at line 49 of file G4TrajectoriesModel.cc.
View newest version in sPHENIX GitHub at line 49 of file G4TrajectoriesModel.cc
References G4VModel::fGlobalDescription, G4VModel::fGlobalTag, and G4VModel::fType.
G4TrajectoriesModel::~G4TrajectoriesModel () virtual
Definition at line 59 of file G4TrajectoriesModel.cc.
View newest version in sPHENIX GitHub at line 59 of file G4TrajectoriesModel.cc
Member Function Documentation
std::vector< G4AttValue > * G4TrajectoriesModel::CreateCurrentAttValues () const
Definition at line 123 of file G4TrajectoriesModel.cc.
View newest version in sPHENIX GitHub at line 123 of file G4TrajectoriesModel.cc
References G4UIcommand::ConvertToString(), fEventID, fRunID, and Acts::Test::values.
Referenced by G4VSceneHandler::LoadAtts().
void G4TrajectoriesModel::DescribeYourselfTo (G4VGraphicsScene & sceneHandler) virtual
Implements G4VModel.
Definition at line 63 of file G4TrajectoriesModel.cc.
View newest version in sPHENIX GitHub at line 63 of file G4TrajectoriesModel.cc
References G4VGraphicsScene::AddCompound(), G4VVisManager::BeginDraw(), G4VVisManager::EndDraw(), G4TrajectoryContainer::entries(), fEventID, fpCurrentTrajectory, G4VModel::fpMP, fRunID, G4VVisManager::GetConcreteInstance(), G4RunManager::GetCurrentRun(), G4ModelingParameters::GetEvent(), G4MTRunManager::GetMasterRunManager(), G4Run::GetRunID(), G4RunManager::GetRunManager(), and G4Threading::IsMultithreadedApplication().
const std::map< G4String, G4AttDef > * G4TrajectoriesModel::GetAttDefs () const
Definition at line 109 of file G4TrajectoriesModel.cc.
View newest version in sPHENIX GitHub at line 109 of file G4TrajectoriesModel.cc
References G4AttDefStore::GetInstance().
Referenced by G4VSceneHandler::LoadAtts(), G4VisCommandList::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
const G4VTrajectory* G4TrajectoriesModel::GetCurrentTrajectory () const inline
Definition at line 62 of file G4TrajectoriesModel.hh.
View newest version in sPHENIX GitHub at line 62 of file G4TrajectoriesModel.hh
References fpCurrentTrajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound(), and G4VSceneHandler::LoadAtts().
void G4TrajectoriesModel::SetCurrentTrajectory (const G4VTrajectory * pTraj) inline
Definition at line 65 of file G4TrajectoriesModel.hh.
View newest version in sPHENIX GitHub at line 65 of file G4TrajectoriesModel.hh
References fpCurrentTrajectory.
Referenced by G4VisManager::Draw().
void G4TrajectoriesModel::SetEventID (G4int eventID) inline
Definition at line 71 of file G4TrajectoriesModel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4TrajectoriesModel.hh
References fEventID.
Referenced by G4VisManager::Draw().
void G4TrajectoriesModel::SetRunID (G4int runID) inline
Definition at line 68 of file G4TrajectoriesModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4TrajectoriesModel.hh
References fRunID.
Referenced by G4VisManager::Draw().
Member Data Documentation
G4int G4TrajectoriesModel::fEventID private
Definition at line 81 of file G4TrajectoriesModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4TrajectoriesModel.hh
Referenced by CreateCurrentAttValues(), DescribeYourselfTo(), and SetEventID().
const G4VTrajectory* G4TrajectoriesModel::fpCurrentTrajectory private
Definition at line 79 of file G4TrajectoriesModel.hh.
View newest version in sPHENIX GitHub at line 79 of file G4TrajectoriesModel.hh
Referenced by DescribeYourselfTo(), GetCurrentTrajectory(), and SetCurrentTrajectory().
G4int G4TrajectoriesModel::fRunID private
Definition at line 80 of file G4TrajectoriesModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4TrajectoriesModel.hh
Referenced by CreateCurrentAttValues(), DescribeYourselfTo(), and SetRunID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoriesModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoriesModel.cc