ECCE @ EIC Software: G4tgbMaterialMgr Class Reference
G4tgbMaterialMgr Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMgr.hh>
Public Member Functions
~G4tgbMaterialMgr ()
void CopyIsotopes ()
void CopyElements ()
void CopyMaterials ()
G4Isotope * FindOrBuildG4Isotope (const G4String &name)
G4Isotope * FindBuiltG4Isotope (const G4String &name) const
G4tgbIsotope * FindG4tgbIsotope (const G4String &name, G4bool bMustExist=0) const
G4Element * FindOrBuildG4Element (const G4String &name, G4bool bMustExist=1)
G4Element * FindBuiltG4Element (const G4String &name) const
G4tgbElement * FindG4tgbElement (const G4String &name, G4bool bMustExist=0) const
G4Material * FindOrBuildG4Material (const G4String &name, G4bool bMustExist=1)
G4Material * FindBuiltG4Material (const G4String &name) const
G4tgbMaterial * FindG4tgbMaterial (const G4String &name, G4bool bMustExist=0) const
const G4msg4isot GetG4IsotopeList () const
const G4msg4elem GetG4ElementList () const
const G4msg4mate GetG4MaterialList () const
Static Public Member Functions
static G4tgbMaterialMgr * GetInstance ()
Private Member Functions
G4tgbMaterialMgr ()
Private Attributes
G4mstgbisot theG4tgbIsotopes
G4mstgbelem theG4tgbElements
G4mstgbmate theG4tgbMaterials
G4msg4isot theG4Isotopes
G4msg4elem theG4Elements
G4msg4mate theG4Materials
Static Private Attributes
static G4ThreadLocal
G4tgbMaterialMgr * theInstance = 0
Detailed Description
Definition at line 65 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 65 of file G4tgbMaterialMgr.hh
Constructor & Destructor Documentation
G4tgbMaterialMgr::~G4tgbMaterialMgr ()
Definition at line 73 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 73 of file G4tgbMaterialMgr.cc
References theG4tgbElements, theG4tgbIsotopes, theG4tgbMaterials, and theInstance.
G4tgbMaterialMgr::G4tgbMaterialMgr () private
Definition at line 53 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 53 of file G4tgbMaterialMgr.cc
Referenced by GetInstance().
Member Function Documentation
void G4tgbMaterialMgr::CopyElements ()
Definition at line 119 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 119 of file G4tgbMaterialMgr.cc
References G4tgrMaterialFactory::GetElementList(), G4tgrMaterialFactory::GetInstance(), G4tgbElement::GetName(), and theG4tgbElements.
Referenced by GetInstance().
void G4tgbMaterialMgr::CopyIsotopes ()
Definition at line 104 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 104 of file G4tgbMaterialMgr.cc
References G4tgrMaterialFactory::GetInstance(), G4tgrMaterialFactory::GetIsotopeList(), G4tgbIsotope::GetName(), and theG4tgbIsotopes.
Referenced by GetInstance().
void G4tgbMaterialMgr::CopyMaterials ()
Definition at line 134 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 134 of file G4tgbMaterialMgr.cc
References G4tgrMaterialFactory::GetInstance(), G4tgrMaterialFactory::GetMaterialList(), G4tgbMaterial::GetName(), G4tgrMaterial::GetType(), and theG4tgbMaterials.
Referenced by GetInstance().
G4Element * G4tgbMaterialMgr::FindBuiltG4Element (const G4String & name) const
Definition at line 324 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 324 of file G4tgbMaterialMgr.cc
References G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theG4Elements.
Referenced by FindOrBuildG4Element().
G4Isotope * G4tgbMaterialMgr::FindBuiltG4Isotope (const G4String & name) const
Definition at line 195 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 195 of file G4tgbMaterialMgr.cc
References G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theG4Isotopes.
Referenced by FindOrBuildG4Isotope().
G4Material * G4tgbMaterialMgr::FindBuiltG4Material (const G4String & name) const
Definition at line 445 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 445 of file G4tgbMaterialMgr.cc
References G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theG4Materials.
Referenced by EICG4dRICHOptics::EICG4dRICHOptics(), and FindOrBuildG4Material().
G4tgbElement * G4tgbMaterialMgr::FindG4tgbElement (const G4String & name, G4bool bMustExist = 0) const
Definition at line 346 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 346 of file G4tgbMaterialMgr.cc
References FatalException, G4cout, G4endl, G4Exception(), G4tgrMessenger::GetVerboseLevel(), and theG4tgbElements.
Referenced by FindOrBuildG4Element().
G4tgbIsotope * G4tgbMaterialMgr::FindG4tgbIsotope (const G4String & name, G4bool bMustExist = 0) const
Definition at line 218 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 218 of file G4tgbMaterialMgr.cc
References FatalException, G4cout, G4endl, G4Exception(), G4tgrMessenger::GetVerboseLevel(), and theG4tgbIsotopes.
Referenced by FindOrBuildG4Isotope().
G4tgbMaterial * G4tgbMaterialMgr::FindG4tgbMaterial (const G4String & name, G4bool bMustExist = 0) const
Definition at line 467 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 467 of file G4tgbMaterialMgr.cc
References FatalException, G4cout, G4endl, G4Exception(), G4tgrMessenger::GetVerboseLevel(), and theG4tgbMaterials.
Referenced by FindOrBuildG4Material().
G4Element * G4tgbMaterialMgr::FindOrBuildG4Element (const G4String & name, G4bool bMustExist = 1)
Definition at line 248 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 248 of file G4tgbMaterialMgr.cc
References G4tgbElement::BuildG4ElementFromIsotopes(), G4tgbElement::BuildG4ElementSimple(), FatalException, FindBuiltG4Element(), FindG4tgbElement(), G4NistManager::FindOrBuildElement(), G4cout, G4endl, G4Exception(), G4Element::GetName(), G4tgbElement::GetType(), G4tgrMessenger::GetVerboseLevel(), G4NistManager::Instance(), and theG4Elements.
Referenced by G4tgbMaterialMixtureByWeight::BuildG4Material(), and G4tgbMaterialMixtureByNoAtoms::BuildG4Material().
G4Isotope * G4tgbMaterialMgr::FindOrBuildG4Isotope (const G4String & name)
Definition at line 160 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 160 of file G4tgbMaterialMgr.cc
References G4tgbIsotope::BuildG4Isotope(), FindBuiltG4Isotope(), FindG4tgbIsotope(), G4cout, G4endl, G4Isotope::GetName(), G4tgrMessenger::GetVerboseLevel(), and theG4Isotopes.
Referenced by G4tgbElement::BuildG4ElementFromIsotopes().
G4Material * G4tgbMaterialMgr::FindOrBuildG4Material (const G4String & name, G4bool bMustExist = 1)
Definition at line 376 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 376 of file G4tgbMaterialMgr.cc
References G4tgbMaterial::BuildG4Material(), FatalException, FindBuiltG4Material(), FindG4tgbMaterial(), G4NistManager::FindOrBuildMaterial(), G4cout, G4endl, G4Exception(), G4Material::GetIonisation(), G4tgrMaterial::GetIonisationMeanExcitationEnergy(), G4Material::GetName(), G4tgbMaterial::GetTgrMate(), G4tgrMessenger::GetVerboseLevel(), G4NistManager::Instance(), G4IonisParamMat::SetMeanExcitationEnergy(), and theG4Materials.
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
const G4msg4elem G4tgbMaterialMgr::GetG4ElementList () const inline
Definition at line 111 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 111 of file G4tgbMaterialMgr.hh
References theG4Elements.
Referenced by G4tgbVolumeMgr::DumpSummary().
const G4msg4isot G4tgbMaterialMgr::GetG4IsotopeList () const inline
Definition at line 110 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 110 of file G4tgbMaterialMgr.hh
References theG4Isotopes.
Referenced by G4tgbVolumeMgr::DumpSummary().
const G4msg4mate G4tgbMaterialMgr::GetG4MaterialList () const inline
Definition at line 112 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 112 of file G4tgbMaterialMgr.hh
References theG4Materials.
Referenced by G4tgbVolumeMgr::DumpSummary().
G4tgbMaterialMgr * G4tgbMaterialMgr::GetInstance (void) static
Definition at line 59 of file G4tgbMaterialMgr.cc.
View newest version in sPHENIX GitHub at line 59 of file G4tgbMaterialMgr.cc
References CopyElements(), CopyIsotopes(), CopyMaterials(), G4tgbMaterialMgr(), and theInstance.
Referenced by G4tgbElement::BuildG4ElementFromIsotopes(), G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), G4tgbVolumeMgr::DumpSummary(), EICG4dRICHOptics::EICG4dRICHOptics(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
Member Data Documentation
G4msg4elem G4tgbMaterialMgr::theG4Elements private
Definition at line 131 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 131 of file G4tgbMaterialMgr.hh
Referenced by FindBuiltG4Element(), FindOrBuildG4Element(), and GetG4ElementList().
G4msg4isot G4tgbMaterialMgr::theG4Isotopes private
Definition at line 129 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 129 of file G4tgbMaterialMgr.hh
Referenced by FindBuiltG4Isotope(), FindOrBuildG4Isotope(), and GetG4IsotopeList().
G4msg4mate G4tgbMaterialMgr::theG4Materials private
Definition at line 133 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 133 of file G4tgbMaterialMgr.hh
Referenced by FindBuiltG4Material(), FindOrBuildG4Material(), and GetG4MaterialList().
G4mstgbelem G4tgbMaterialMgr::theG4tgbElements private
Definition at line 125 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 125 of file G4tgbMaterialMgr.hh
Referenced by CopyElements(), FindG4tgbElement(), and ~G4tgbMaterialMgr().
G4mstgbisot G4tgbMaterialMgr::theG4tgbIsotopes private
Definition at line 123 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 123 of file G4tgbMaterialMgr.hh
Referenced by CopyIsotopes(), FindG4tgbIsotope(), and ~G4tgbMaterialMgr().
G4mstgbmate G4tgbMaterialMgr::theG4tgbMaterials private
Definition at line 127 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 127 of file G4tgbMaterialMgr.hh
Referenced by CopyMaterials(), FindG4tgbMaterial(), and ~G4tgbMaterialMgr().
G4ThreadLocal G4tgbMaterialMgr * G4tgbMaterialMgr::theInstance = 0 static private
Definition at line 121 of file G4tgbMaterialMgr.hh.
View newest version in sPHENIX GitHub at line 121 of file G4tgbMaterialMgr.hh
Referenced by GetInstance(), and ~G4tgbMaterialMgr().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMgr.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbMaterialMgr.cc