ECCE @ EIC Software: G4SurfaceProperty Class Reference
G4SurfaceProperty Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4SurfaceProperty.hh>
Public Member Functions
G4SurfaceProperty (const G4String &name, G4SurfaceType type=x_ray)
G4SurfaceProperty ()
virtual ~G4SurfaceProperty ()
const G4String & GetName () const
void SetName (const G4String &name)
const G4SurfaceType & GetType () const
void SetType (const G4SurfaceType &type)
Static Public Member Functions
static void CleanSurfacePropertyTable ()
static const
G4SurfacePropertyTable * GetSurfacePropertyTable ()
static size_t GetNumberOfSurfaceProperties ()
static void DumpTableInfo ()
Protected Attributes
G4String theName
G4SurfaceType theType
Static Protected Attributes
static G4SurfacePropertyTable theSurfacePropertyTable
Detailed Description
Definition at line 79 of file G4SurfaceProperty.hh.
View newest version in sPHENIX GitHub at line 79 of file G4SurfaceProperty.hh
Constructor & Destructor Documentation
G4SurfaceProperty::G4SurfaceProperty (const G4String & name, G4SurfaceType type = x_ray)
Definition at line 54 of file G4SurfaceProperty.cc.
View newest version in sPHENIX GitHub at line 54 of file G4SurfaceProperty.cc
References theSurfacePropertyTable.
G4SurfaceProperty::G4SurfaceProperty ()
Definition at line 64 of file G4SurfaceProperty.cc.
View newest version in sPHENIX GitHub at line 64 of file G4SurfaceProperty.cc
References theSurfacePropertyTable.
G4SurfaceProperty::~G4SurfaceProperty () virtual
Definition at line 70 of file G4SurfaceProperty.cc.
View newest version in sPHENIX GitHub at line 70 of file G4SurfaceProperty.cc
Member Function Documentation
void G4SurfaceProperty::CleanSurfacePropertyTable () static
Definition at line 106 of file G4SurfaceProperty.cc.
View newest version in sPHENIX GitHub at line 106 of file G4SurfaceProperty.cc
References DumpTableInfo(), pos(), and theSurfacePropertyTable.
void G4SurfaceProperty::DumpTableInfo () static
Definition at line 90 of file G4SurfaceProperty.cc.
View newest version in sPHENIX GitHub at line 90 of file G4SurfaceProperty.cc
References G4cout, G4endl, GetName(), GetNumberOfSurfaceProperties(), GetType(), and theSurfacePropertyTable.
Referenced by CleanSurfacePropertyTable().
const G4String& G4SurfaceProperty::GetName (void) const inline
Definition at line 113 of file G4SurfaceProperty.hh.
View newest version in sPHENIX GitHub at line 113 of file G4SurfaceProperty.hh
References theName.
Referenced by PHG4GDMLWriteStructure::BorderSurfaceCache(), G4GDMLWriteStructure::BorderSurfaceCache(), DumpTableInfo(), PHG4GDMLWriteSolids::OpticalSurfaceWrite(), G4GDMLWriteSolids::OpticalSurfaceWrite(), G4GDMLWriteSolids::PropertyWrite(), PHG4GDMLWriteStructure::SkinSurfaceCache(), and G4GDMLWriteStructure::SkinSurfaceCache().
size_t G4SurfaceProperty::GetNumberOfSurfaceProperties () static
Definition at line 83 of file G4SurfaceProperty.cc.
View newest version in sPHENIX GitHub at line 83 of file G4SurfaceProperty.cc
References theSurfacePropertyTable.
Referenced by DumpTableInfo().
const G4SurfacePropertyTable * G4SurfaceProperty::GetSurfacePropertyTable () static
Definition at line 78 of file G4SurfaceProperty.cc.
View newest version in sPHENIX GitHub at line 78 of file G4SurfaceProperty.cc
References theSurfacePropertyTable.
Referenced by G4GDMLReadSolids::GetSurfaceProperty().
const G4SurfaceType& G4SurfaceProperty::GetType () const inline
Definition at line 118 of file G4SurfaceProperty.hh.
View newest version in sPHENIX GitHub at line 118 of file G4SurfaceProperty.hh
References theType.
Referenced by DumpTableInfo(), PHG4GDMLWriteSolids::OpticalSurfaceWrite(), G4GDMLWriteSolids::OpticalSurfaceWrite(), and G4OpBoundaryProcess::PostStepDoIt().
void G4SurfaceProperty::SetName (const G4String & name) inline
Definition at line 115 of file G4SurfaceProperty.hh.
View newest version in sPHENIX GitHub at line 115 of file G4SurfaceProperty.hh
References theName.
void G4SurfaceProperty::SetType (const G4SurfaceType & type) inline
Definition at line 120 of file G4SurfaceProperty.hh.
View newest version in sPHENIX GitHub at line 120 of file G4SurfaceProperty.hh
References theType.
Member Data Documentation
G4String G4SurfaceProperty::theName protected
Definition at line 135 of file G4SurfaceProperty.hh.
View newest version in sPHENIX GitHub at line 135 of file G4SurfaceProperty.hh
Referenced by G4OpticalSurface::G4OpticalSurface(), GetName(), G4OpticalSurface::operator=(), and SetName().
G4SurfacePropertyTable G4SurfaceProperty::theSurfacePropertyTable static protected
Definition at line 139 of file G4SurfaceProperty.hh.
View newest version in sPHENIX GitHub at line 139 of file G4SurfaceProperty.hh
Referenced by CleanSurfacePropertyTable(), DumpTableInfo(), G4SurfaceProperty(), GetNumberOfSurfaceProperties(), and GetSurfacePropertyTable().
G4SurfaceType G4SurfaceProperty::theType protected
Definition at line 137 of file G4SurfaceProperty.hh.
View newest version in sPHENIX GitHub at line 137 of file G4SurfaceProperty.hh
Referenced by G4OpticalSurface::DumpInfo(), G4OpticalSurface::G4OpticalSurface(), GetType(), G4OpticalSurface::operator=(), G4OpticalSurface::SetFinish(), SetType(), and G4OpticalSurface::SetType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4SurfaceProperty.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4SurfaceProperty.cc