ECCE @ EIC Software: G4OpBoundaryProcess Class Reference
G4OpBoundaryProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/optical/include/G4OpBoundaryProcess.hh>
Public Member Functions
G4OpBoundaryProcess (const G4String &processName="OpBoundary", G4ProcessType type=fOptical)
virtual ~G4OpBoundaryProcess ()
virtual G4bool IsApplicable (const G4ParticleDefinition &aParticleType) override
virtual G4double GetMeanFreePath (const G4Track &, G4double, G4ForceCondition *condition) override
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4OpBoundaryProcessStatus GetStatus () const
virtual void SetInvokeSD (G4bool)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4OpBoundaryProcess (const G4OpBoundaryProcess &right)=delete
G4OpBoundaryProcess & operator= (const G4OpBoundaryProcess &right)=delete
G4bool G4BooleanRand (const G4double prob) const
G4ThreeVector GetFacetNormal (const G4ThreeVector &Momentum, const G4ThreeVector &Normal) const
void DielectricMetal ()
void DielectricDielectric ()
void DielectricLUT ()
void DielectricLUTDAVIS ()
void DielectricDichroic ()
void ChooseReflection ()
void DoAbsorption ()
void DoReflection ()
G4double GetIncidentAngle ()
G4double GetReflectivity (G4double E1_perp, G4double E1_parl, G4double incidentangle, G4double RealRindex, G4double ImaginaryRindex)
void CalculateReflectivity (void)
void BoundaryProcessVerbose (void) const
G4bool InvokeSD (const G4Step *step)
Private Attributes
G4double thePhotonMomentum
G4ThreeVector OldMomentum
G4ThreeVector OldPolarization
G4ThreeVector NewMomentum
G4ThreeVector NewPolarization
G4ThreeVector theGlobalNormal
G4ThreeVector theFacetNormal
G4Material * Material1
G4Material * Material2
G4OpticalSurface * OpticalSurface
G4MaterialPropertyVector * fRealRIndexMPV
G4MaterialPropertyVector * fImagRIndexMPV
G4double Rindex1
G4double Rindex2
G4double cost1
G4double cost2
G4double sint1
G4double sint2
G4OpBoundaryProcessStatus theStatus
G4OpticalSurfaceModel theModel
G4OpticalSurfaceFinish theFinish
G4double theReflectivity
G4double theEfficiency
G4double theTransmittance
G4double theSurfaceRoughness
G4double prob_sl
G4double prob_ss
G4double prob_bs
G4int iTE
G4int iTM
G4double kCarTolerance
size_t idx
size_t idy
G4Physics2DVector * DichroicVector
G4bool fInvokeSD
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 124 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 124 of file G4OpBoundaryProcess.hh
Constructor & Destructor Documentation
G4OpBoundaryProcess::G4OpBoundaryProcess (const G4String & processName = "OpBoundary", G4ProcessType type = fOptical) explicit
Definition at line 91 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 91 of file G4OpBoundaryProcess.cc
References cost1, cost2, DichroicVector, fImagRIndexMPV, fInvokeSD, fOpBoundary, fRealRIndexMPV, G4cout, G4endl, G4GeometryTolerance::GetInstance(), G4VProcess::GetProcessName(), G4GeometryTolerance::GetSurfaceTolerance(), glisur, idx, idy, iTE, iTM, kCarTolerance, Material1, Material2, OpticalSurface, polished, prob_bs, prob_sl, prob_ss, Rindex1, Rindex2, G4VProcess::SetProcessSubType(), sint1, sint2, theEfficiency, theFinish, theModel, thePhotonMomentum, theReflectivity, theStatus, theSurfaceRoughness, theTransmittance, Acts::Undefined, and G4VProcess::verboseLevel.
G4OpBoundaryProcess::~G4OpBoundaryProcess () virtual
Definition at line 141 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 141 of file G4OpBoundaryProcess.cc
G4OpBoundaryProcess::G4OpBoundaryProcess (const G4OpBoundaryProcess & right) private delete
Member Function Documentation
void G4OpBoundaryProcess::BoundaryProcessVerbose (void) const private
Definition at line 487 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 487 of file G4OpBoundaryProcess.cc
References Absorption, BackScattering, Detection, Dichroic, EtchedAirReflection, EtchedLumirrorAirReflection, EtchedLumirrorGlueReflection, EtchedTeflonAirReflection, EtchedTiOAirReflection, EtchedTyvekAirReflection, EtchedVM2000AirReflection, EtchedVM2000GlueReflection, FresnelReflection, FresnelRefraction, G4cout, G4endl, GroundAirReflection, GroundLumirrorAirReflection, GroundLumirrorGlueReflection, GroundTeflonAirReflection, GroundTiOAirReflection, GroundTyvekAirReflection, GroundVM2000AirReflection, GroundVM2000GlueReflection, LambertianReflection, LobeReflection, NoRINDEX, NotAtBoundary, PolishedAirReflection, PolishedLumirrorAirReflection, PolishedLumirrorGlueReflection, PolishedTeflonAirReflection, PolishedTiOAirReflection, PolishedTyvekAirReflection, PolishedVM2000AirReflection, PolishedVM2000GlueReflection, SameMaterial, SpikeReflection, StepTooSmall, theStatus, TotalInternalReflection, Transmission, and Acts::Undefined.
Referenced by PostStepDoIt().
void G4OpBoundaryProcess::CalculateReflectivity (void) private
Definition at line 1293 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 1293 of file G4OpBoundaryProcess.cc
References kdfinder::abs(), cost1, CLHEP::Hep3Vector::cross(), fImagRIndexMPV, fRealRIndexMPV, GetFacetNormal(), GetIncidentAngle(), GetReflectivity(), ground, kCarTolerance, CLHEP::Hep3Vector::mag(), OldMomentum, OldPolarization, sint1, theFacetNormal, theFinish, theGlobalNormal, thePhotonMomentum, theReflectivity, CLHEP::Hep3Vector::unit(), and G4PhysicsVector::Value().
Referenced by DielectricMetal(), and PostStepDoIt().
void G4OpBoundaryProcess::ChooseReflection () inline private
Definition at line 270 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 270 of file G4OpBoundaryProcess.hh
References BackScattering, G4UniformRand, LambertianReflection, LobeReflection, prob_bs, prob_sl, prob_ss, SpikeReflection, theFacetNormal, theGlobalNormal, and theStatus.
Referenced by DielectricDichroic(), DielectricDielectric(), and DielectricMetal().
void G4OpBoundaryProcess::DielectricDichroic () private
Definition at line 894 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 894 of file G4OpBoundaryProcess.cc
References CLHEP::Hep3Vector::angle(), BackScattering, source.hepunit::c_light, ChooseReflection(), Dichroic, DichroicVector, DoReflection(), FatalException, G4BooleanRand(), G4endl, G4Exception(), G4OpticalSurface::GetDichroicVector(), GetFacetNormal(), glisur, source.hepunit::h_Planck, idx, idy, LambertianReflection, LobeReflection, NewMomentum, NewPolarization, nm, OldMomentum, OldPolarization, OpticalSurface, perCent, pi, polished, theFacetNormal, theFinish, theGlobalNormal, theModel, thePhotonMomentum, theStatus, theTransmittance, and G4Physics2DVector::Value().
Referenced by PostStepDoIt().
void G4OpBoundaryProcess::DielectricDielectric () private
Definition at line 958 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 958 of file G4OpBoundaryProcess.cc
References kdfinder::abs(), alpha, BackScattering, source.hepunit::c_light, ChooseReflection(), cost1, cost2, CLHEP::Hep3Vector::cross(), DoAbsorption(), DoReflection(), FresnelReflection, FresnelRefraction, G4BooleanRand(), G4SwapObj(), G4SwapPtr(), G4UniformRand, GetFacetNormal(), groundbackpainted, source.hepunit::h_Planck, kCarTolerance, LambertianReflection, CLHEP::Hep3Vector::mag(), Material1, Material2, NewMomentum, NewPolarization, OldMomentum, OldPolarization, pi, polished, polishedbackpainted, Rindex1, Rindex2, s1, sint1, sint2, theFacetNormal, theFinish, theGlobalNormal, theModel, thePhotonMomentum, theReflectivity, theStatus, theSurfaceRoughness, theTransmittance, TotalInternalReflection, Transmission, unified, and CLHEP::Hep3Vector::unit().
Referenced by PostStepDoIt().
void G4OpBoundaryProcess::DielectricLUT () private
Definition at line 738 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 738 of file G4OpBoundaryProcess.cc
References CLHEP::Hep3Vector::angle(), CLHEP::Hep3Vector::cross(), DoAbsorption(), G4BooleanRand(), G4UniformRand, G4OpticalSurface::GetPhiIndexMax(), G4OpticalSurface::GetThetaIndexMax(), groundbackpainted, kCarTolerance, CLHEP::Hep3Vector::mag(), NewMomentum, NewPolarization, NoRINDEX, OldMomentum, OldPolarization, OpticalSurface, CLHEP::Hep3Vector::orthogonal(), pi, CLHEP::Hep3Vector::rotate(), theFacetNormal, theFinish, theGlobalNormal, theReflectivity, theStatus, theTransmittance, and Transmission.
Referenced by PostStepDoIt().
void G4OpBoundaryProcess::DielectricLUTDAVIS () private
Definition at line 805 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 805 of file G4OpBoundaryProcess.cc
References CLHEP::Hep3Vector::angle(), CLHEP::Hep3Vector::cross(), DoAbsorption(), G4UniformRand, G4OpticalSurface::GetAngularDistributionValueLUT(), G4OpticalSurface::GetLUTbins(), G4OpticalSurface::GetReflectivityLUTValue(), LobeReflection, CLHEP::Hep3Vector::mag(), NewMomentum, NewPolarization, OldMomentum, OldPolarization, OpticalSurface, pi, theEfficiency, theFacetNormal, theGlobalNormal, theStatus, Transmission, Acts::UnitConstants::u, v, and w.
Referenced by PostStepDoIt().
void G4OpBoundaryProcess::DielectricMetal () private
Definition at line 654 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 654 of file G4OpBoundaryProcess.cc
References BackScattering, CalculateReflectivity(), ChooseReflection(), CLHEP::Hep3Vector::cross(), DoAbsorption(), DoReflection(), fImagRIndexMPV, fRealRIndexMPV, G4BooleanRand(), G4UniformRand, GetFacetNormal(), glisur, iTE, iTM, LambertianReflection, LobeReflection, n, NewMomentum, NewPolarization, OldMomentum, OldPolarization, polished, sint1, theFacetNormal, theFinish, theGlobalNormal, theModel, theReflectivity, theStatus, theTransmittance, Transmission, and CLHEP::Hep3Vector::unit().
Referenced by PostStepDoIt().
void G4OpBoundaryProcess::DoAbsorption () inline private
Definition at line 289 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 289 of file G4OpBoundaryProcess.hh
References Absorption, G4VProcess::aParticleChange, Detection, fStopAndKill, G4BooleanRand(), NewMomentum, NewPolarization, OldMomentum, OldPolarization, G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), theEfficiency, thePhotonMomentum, and theStatus.
Referenced by DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), and PostStepDoIt().
void G4OpBoundaryProcess::DoReflection () inline private
Definition at line 309 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 309 of file G4OpBoundaryProcess.hh
References fImagRIndexMPV, fRealRIndexMPV, G4LambertianRand(), GetFacetNormal(), ground, LambertianReflection, LobeReflection, NewMomentum, NewPolarization, OldMomentum, OldPolarization, SpikeReflection, theFacetNormal, theFinish, theGlobalNormal, and theStatus.
Referenced by DielectricDichroic(), DielectricDielectric(), DielectricMetal(), and PostStepDoIt().
G4bool G4OpBoundaryProcess::G4BooleanRand (const G4double prob) const inline private
Definition at line 244 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 244 of file G4OpBoundaryProcess.hh
References G4UniformRand.
Referenced by DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricMetal(), and DoAbsorption().
G4ThreeVector G4OpBoundaryProcess::GetFacetNormal (const G4ThreeVector & Momentum, const G4ThreeVector & Normal) const private
Definition at line 574 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 574 of file G4OpBoundaryProcess.cc
References alpha, DAVIS, G4UniformRand, G4OpticalSurface::GetPolish(), G4OpticalSurface::GetSigmaAlpha(), halfpi, LUT, CLHEP::Hep3Vector::mag(), min, OpticalSurface, phi, CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4INCL::DeJongSpin::shoot(), theModel, twopi, unified, and CLHEP::Hep3Vector::unit().
Referenced by CalculateReflectivity(), DielectricDichroic(), DielectricDielectric(), DielectricMetal(), and DoReflection().
G4double G4OpBoundaryProcess::GetIncidentAngle () private
Definition at line 1209 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 1209 of file G4OpBoundaryProcess.cc
References CLHEP::Hep3Vector::mag(), OldMomentum, pi, and theFacetNormal.
Referenced by CalculateReflectivity().
G4double G4OpBoundaryProcess::GetMeanFreePath (const G4Track & , G4double , G4ForceCondition * condition) override virtual
Implements G4VDiscreteProcess.
Definition at line 1199 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 1199 of file G4OpBoundaryProcess.cc
References DBL_MAX, and Forced.
G4double G4OpBoundaryProcess::GetReflectivity (G4double E1_perp, G4double E1_parl, G4double incidentangle, G4double RealRindex, G4double ImaginaryRindex) private
Definition at line 1221 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 1221 of file G4OpBoundaryProcess.cc
References G4UniformRand, G4Material::GetMaterialPropertiesTable(), G4MaterialPropertiesTable::GetProperty(), iTE, iTM, kIMAGINARYRINDEX, kREALRINDEX, Material1, Rindex1, thePhotonMomentum, Acts::UnitConstants::u, and G4PhysicsVector::Value().
Referenced by CalculateReflectivity().
G4OpBoundaryProcessStatus G4OpBoundaryProcess::GetStatus () const inline virtual
Definition at line 258 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 258 of file G4OpBoundaryProcess.hh
References theStatus.
Referenced by PrtOpBoundaryProcess::PostStepDoIt(), G4EicDircOpBoundaryProcess::PostStepDoIt(), PHG4RICHSteppingAction::UserSteppingAction(), and WLSSteppingAction::UserSteppingAction().
G4bool G4OpBoundaryProcess::InvokeSD (const G4Step * step) private
Definition at line 1345 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 1345 of file G4OpBoundaryProcess.cc
References G4Step::AddTotalEnergyDeposit(), G4Step::GetPostStepPoint(), G4StepPoint::GetSensitiveDetector(), G4VSensitiveDetector::Hit(), and thePhotonMomentum.
Referenced by PostStepDoIt().
G4bool G4OpBoundaryProcess::IsApplicable (const G4ParticleDefinition & aParticleType) inline override virtual
Reimplemented from G4VProcess.
Reimplemented in G4EicDircOpBoundaryProcess.
Definition at line 251 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 251 of file G4OpBoundaryProcess.hh
References G4OpticalPhoton::OpticalPhoton().
Referenced by G4OpticalPhysics::ConstructProcess().
G4OpBoundaryProcess& G4OpBoundaryProcess::operator= (const G4OpBoundaryProcess & right) private delete
G4VParticleChange * G4OpBoundaryProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 147 of file G4OpBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 147 of file G4OpBoundaryProcess.cc
References G4VProcess::aParticleChange, BoundaryProcessVerbose(), CalculateReflectivity(), G4MaterialPropertiesTable::ConstPropertyExists(), Detection, dielectric_dichroic, dielectric_dielectric, dielectric_LUT, dielectric_LUTDAVIS, dielectric_metal, DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), DoAbsorption(), DoReflection(), EventMustBeAborted, fGeomBoundary, fImagRIndexMPV, fInvokeSD, fRealRIndexMPV, FresnelRefraction, fStopAndKill, G4cerr, G4cout, G4endl, G4Exception(), G4UniformRand, G4TransportationManager::GetActiveNavigatorsIterator(), G4Track::GetDynamicParticle(), G4OpticalSurface::GetFinish(), G4ParallelWorldProcess::GetHyperStep(), G4ParallelWorldProcess::GetHypNavigatorID(), G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetMaterial(), G4OpticalSurface::GetMaterialPropertiesTable(), G4Material::GetMaterialPropertiesTable(), G4OpticalSurface::GetModel(), G4DynamicParticle::GetMomentumDirection(), G4VPhysicalVolume::GetMotherLogical(), G4VPhysicalVolume::GetName(), G4StepPoint::GetPhysicalVolume(), G4DynamicParticle::GetPolarization(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4MaterialPropertiesTable::GetProperty(), G4Track::GetStepLength(), G4StepPoint::GetStepStatus(), G4LogicalSkinSurface::GetSurface(), G4LogicalBorderSurface::GetSurface(), G4LogicalSurface::GetSurfaceProperty(), G4DynamicParticle::GetTotalMomentum(), G4TransportationManager::GetTransportationManager(), G4SurfaceProperty::GetType(), G4Track::GetVelocity(), glisur, ground, groundbackpainted, groundfrontpainted, G4ParticleChange::Initialize(), InvokeSD(), iTE, iTM, kBACKSCATTERCONSTANT, kCarTolerance, kEFFICIENCY, kGROUPVEL, kIMAGINARYRINDEX, kREALRINDEX, kREFLECTIVITY, kRINDEX, kSPECULARLOBECONSTANT, kSPECULARSPIKECONSTANT, kSURFACEROUGHNESS, kTRANSMITTANCE, LambertianReflection, Material1, Material2, NewMomentum, NewPolarization, NoRINDEX, NotAtBoundary, OldMomentum, OldPolarization, OpticalSurface, polished, polishedbackpainted, polishedfrontpainted, G4VDiscreteProcess::PostStepDoIt(), prob_bs, prob_sl, prob_ss, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4ParticleChange::ProposePolarization(), G4VParticleChange::ProposeTrackStatus(), G4ParticleChange::ProposeVelocity(), Rindex1, Rindex2, SameMaterial, StepTooSmall, theEfficiency, theFinish, theGlobalNormal, theModel, thePhotonMomentum, theReflectivity, theStatus, theSurfaceRoughness, theTransmittance, Transmission, Acts::Undefined, unified, CLHEP::Hep3Vector::unit(), Acts::IntegrationTest::valid(), G4PhysicsVector::Value(), and G4VProcess::verboseLevel.
Referenced by PrtOpBoundaryProcess::PostStepDoIt(), and G4EicDircOpBoundaryProcess::PostStepDoIt().
void G4OpBoundaryProcess::SetInvokeSD (G4bool flag) inline virtual
Definition at line 264 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 264 of file G4OpBoundaryProcess.hh
References fInvokeSD.
Referenced by G4OpticalPhysics::ConstructProcess(), and G4OpticalPhysics::SetInvokeSD().
Member Data Documentation
G4double G4OpBoundaryProcess::cost1 private
Definition at line 213 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 213 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricDielectric(), and G4OpBoundaryProcess().
G4double G4OpBoundaryProcess::cost2 private
Definition at line 213 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 213 of file G4OpBoundaryProcess.hh
Referenced by DielectricDielectric(), and G4OpBoundaryProcess().
G4Physics2DVector* G4OpBoundaryProcess::DichroicVector private
Definition at line 234 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 234 of file G4OpBoundaryProcess.hh
Referenced by DielectricDichroic(), and G4OpBoundaryProcess().
G4MaterialPropertyVector* G4OpBoundaryProcess::fImagRIndexMPV private
Definition at line 208 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 208 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricMetal(), DoReflection(), G4OpBoundaryProcess(), and PostStepDoIt().
G4bool G4OpBoundaryProcess::fInvokeSD private
Definition at line 236 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 236 of file G4OpBoundaryProcess.hh
Referenced by G4OpBoundaryProcess(), PostStepDoIt(), and SetInvokeSD().
G4MaterialPropertyVector* G4OpBoundaryProcess::fRealRIndexMPV private
Definition at line 207 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 207 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricMetal(), DoReflection(), G4OpBoundaryProcess(), and PostStepDoIt().
size_t G4OpBoundaryProcess::idx private
Definition at line 233 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 233 of file G4OpBoundaryProcess.hh
Referenced by DielectricDichroic(), and G4OpBoundaryProcess().
size_t G4OpBoundaryProcess::idy private
Definition at line 233 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 233 of file G4OpBoundaryProcess.hh
Referenced by DielectricDichroic(), and G4OpBoundaryProcess().
G4int G4OpBoundaryProcess::iTE private
Definition at line 229 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 229 of file G4OpBoundaryProcess.hh
Referenced by DielectricMetal(), G4OpBoundaryProcess(), GetReflectivity(), and PostStepDoIt().
G4int G4OpBoundaryProcess::iTM private
Definition at line 229 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 229 of file G4OpBoundaryProcess.hh
Referenced by DielectricMetal(), G4OpBoundaryProcess(), GetReflectivity(), and PostStepDoIt().
G4double G4OpBoundaryProcess::kCarTolerance private
Definition at line 231 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 231 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricDielectric(), DielectricLUT(), G4OpBoundaryProcess(), and PostStepDoIt().
G4Material* G4OpBoundaryProcess::Material1 private
Definition at line 202 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 202 of file G4OpBoundaryProcess.hh
Referenced by DielectricDielectric(), G4OpBoundaryProcess(), GetReflectivity(), and PostStepDoIt().
G4Material* G4OpBoundaryProcess::Material2 private
Definition at line 203 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 203 of file G4OpBoundaryProcess.hh
Referenced by DielectricDielectric(), G4OpBoundaryProcess(), and PostStepDoIt().
G4ThreeVector G4OpBoundaryProcess::NewMomentum private
Definition at line 196 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 196 of file G4OpBoundaryProcess.hh
Referenced by DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), DoAbsorption(), DoReflection(), and PostStepDoIt().
G4ThreeVector G4OpBoundaryProcess::NewPolarization private
Definition at line 197 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 197 of file G4OpBoundaryProcess.hh
Referenced by DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), DoAbsorption(), DoReflection(), and PostStepDoIt().
G4ThreeVector G4OpBoundaryProcess::OldMomentum private
Definition at line 193 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 193 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), DoAbsorption(), DoReflection(), GetIncidentAngle(), and PostStepDoIt().
G4ThreeVector G4OpBoundaryProcess::OldPolarization private
Definition at line 194 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 194 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), DoAbsorption(), DoReflection(), and PostStepDoIt().
G4OpticalSurface* G4OpBoundaryProcess::OpticalSurface private
Definition at line 205 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 205 of file G4OpBoundaryProcess.hh
Referenced by DielectricDichroic(), DielectricLUT(), DielectricLUTDAVIS(), G4OpBoundaryProcess(), GetFacetNormal(), and PostStepDoIt().
G4double G4OpBoundaryProcess::prob_bs private
Definition at line 227 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 227 of file G4OpBoundaryProcess.hh
Referenced by ChooseReflection(), G4OpBoundaryProcess(), and PostStepDoIt().
G4double G4OpBoundaryProcess::prob_sl private
Definition at line 227 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 227 of file G4OpBoundaryProcess.hh
Referenced by ChooseReflection(), G4OpBoundaryProcess(), and PostStepDoIt().
G4double G4OpBoundaryProcess::prob_ss private
Definition at line 227 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 227 of file G4OpBoundaryProcess.hh
Referenced by ChooseReflection(), G4OpBoundaryProcess(), and PostStepDoIt().
G4double G4OpBoundaryProcess::Rindex1 private
Definition at line 210 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 210 of file G4OpBoundaryProcess.hh
Referenced by DielectricDielectric(), G4OpBoundaryProcess(), GetReflectivity(), and PostStepDoIt().
G4double G4OpBoundaryProcess::Rindex2 private
Definition at line 211 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 211 of file G4OpBoundaryProcess.hh
Referenced by DielectricDielectric(), G4OpBoundaryProcess(), and PostStepDoIt().
G4double G4OpBoundaryProcess::sint1 private
Definition at line 213 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 213 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricDielectric(), DielectricMetal(), and G4OpBoundaryProcess().
G4double G4OpBoundaryProcess::sint2 private
Definition at line 213 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 213 of file G4OpBoundaryProcess.hh
Referenced by DielectricDielectric(), and G4OpBoundaryProcess().
G4double G4OpBoundaryProcess::theEfficiency private
Definition at line 222 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 222 of file G4OpBoundaryProcess.hh
Referenced by DielectricLUTDAVIS(), DoAbsorption(), G4OpBoundaryProcess(), and PostStepDoIt().
G4ThreeVector G4OpBoundaryProcess::theFacetNormal private
Definition at line 200 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 200 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), ChooseReflection(), DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), DoReflection(), and GetIncidentAngle().
G4OpticalSurfaceFinish G4OpBoundaryProcess::theFinish private
Definition at line 219 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 219 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricMetal(), DoReflection(), G4OpBoundaryProcess(), and PostStepDoIt().
G4ThreeVector G4OpBoundaryProcess::theGlobalNormal private
Definition at line 199 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 199 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), ChooseReflection(), DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), DoReflection(), and PostStepDoIt().
G4OpticalSurfaceModel G4OpBoundaryProcess::theModel private
Definition at line 217 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 217 of file G4OpBoundaryProcess.hh
Referenced by DielectricDichroic(), DielectricDielectric(), DielectricMetal(), G4OpBoundaryProcess(), GetFacetNormal(), and PostStepDoIt().
G4double G4OpBoundaryProcess::thePhotonMomentum private
Definition at line 191 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 191 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricDichroic(), DielectricDielectric(), DoAbsorption(), G4OpBoundaryProcess(), GetReflectivity(), InvokeSD(), and PostStepDoIt().
G4double G4OpBoundaryProcess::theReflectivity private
Definition at line 221 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 221 of file G4OpBoundaryProcess.hh
Referenced by CalculateReflectivity(), DielectricDielectric(), DielectricLUT(), DielectricMetal(), G4OpBoundaryProcess(), and PostStepDoIt().
G4OpBoundaryProcessStatus G4OpBoundaryProcess::theStatus private
Definition at line 215 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 215 of file G4OpBoundaryProcess.hh
Referenced by BoundaryProcessVerbose(), ChooseReflection(), DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricLUTDAVIS(), DielectricMetal(), DoAbsorption(), DoReflection(), G4OpBoundaryProcess(), GetStatus(), and PostStepDoIt().
G4double G4OpBoundaryProcess::theSurfaceRoughness private
Definition at line 225 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 225 of file G4OpBoundaryProcess.hh
Referenced by DielectricDielectric(), G4OpBoundaryProcess(), and PostStepDoIt().
G4double G4OpBoundaryProcess::theTransmittance private
Definition at line 223 of file G4OpBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 223 of file G4OpBoundaryProcess.hh
Referenced by DielectricDichroic(), DielectricDielectric(), DielectricLUT(), DielectricMetal(), G4OpBoundaryProcess(), and PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/optical/include/G4OpBoundaryProcess.hh
geant4/tree/geant4-10.6-release/source/processes/optical/src/G4OpBoundaryProcess.cc