ECCE @ EIC Software: G4tgrPlaceDivRep Class Reference
G4tgrPlaceDivRep Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrPlaceDivRep.hh>
Public Member Functions
G4tgrPlaceDivRep ()
~G4tgrPlaceDivRep ()
G4tgrPlaceDivRep (const std::vector< G4String > &wl)
EAxis BuildAxis (const G4String &axisName)
EAxis GetAxis () const
G4int GetNDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4DivType GetDivType () const
void SetParentName (const G4String &parentName)
void SetNDiv (G4int ndiv)
void SetWidth (G4double width)
void SetAxis (EAxis axis)
void SetOffset (G4double offset)
void SetDivType (G4DivType typ)
Public Member Functions inherited from G4tgrPlace
G4tgrPlace ()
virtual ~G4tgrPlace ()
const G4String & GetParentName () const
G4tgrVolume * GetVolume () const
unsigned int GetCopyNo () const
const G4String & GetType () const
void SetVolume (G4tgrVolume *vol)
void SetType (const G4String &typ)
virtual G4ThreeVector GetPlacement () const
Private Attributes
G4int theNDiv
G4double theWidth
EAxis theAxis
G4double theOffset
G4DivType theDivType
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrPlaceDivRep &obj)
Additional Inherited Members
Protected Attributes inherited from G4tgrPlace
G4tgrVolume * theVolume
G4String theParentName
unsigned int theCopyNo
G4String theType
Detailed Description
Definition at line 52 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 52 of file G4tgrPlaceDivRep.hh
Constructor & Destructor Documentation
G4tgrPlaceDivRep::G4tgrPlaceDivRep ()
Definition at line 43 of file G4tgrPlaceDivRep.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgrPlaceDivRep.cc
G4tgrPlaceDivRep::~G4tgrPlaceDivRep ()
Definition at line 51 of file G4tgrPlaceDivRep.cc.
View newest version in sPHENIX GitHub at line 51 of file G4tgrPlaceDivRep.cc
G4tgrPlaceDivRep::G4tgrPlaceDivRep (const std::vector< G4String > & wl)
Definition at line 56 of file G4tgrPlaceDivRep.cc.
View newest version in sPHENIX GitHub at line 56 of file G4tgrPlaceDivRep.cc
References BuildAxis(), G4tgrUtils::CheckWLsize(), DivByNdivAndWidth, G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), mm, theAxis, theDivType, theNDiv, theOffset, G4tgrPlace::theParentName, theWidth, WLSIZE_GE, and WLSIZE_LE.
Member Function Documentation
EAxis G4tgrPlaceDivRep::BuildAxis (const G4String & axisName)
Definition at line 90 of file G4tgrPlaceDivRep.cc.
View newest version in sPHENIX GitHub at line 90 of file G4tgrPlaceDivRep.cc
References FatalException, G4Exception(), kPhi, kRho, kXAxis, kYAxis, and kZAxis.
Referenced by G4tgrPlaceDivRep(), and G4tgrVolumeDivision::G4tgrVolumeDivision().
EAxis G4tgrPlaceDivRep::GetAxis () const inline
Definition at line 68 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 68 of file G4tgrPlaceDivRep.hh
References theAxis.
Referenced by G4tgbVolume::ConstructG4PhysVol().
G4DivType G4tgrPlaceDivRep::GetDivType () const inline
Definition at line 72 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 72 of file G4tgrPlaceDivRep.hh
References theDivType.
Referenced by G4tgbVolume::ConstructG4PhysVol().
G4int G4tgrPlaceDivRep::GetNDiv () const inline
Definition at line 69 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 69 of file G4tgrPlaceDivRep.hh
References theNDiv.
Referenced by G4tgbVolume::ConstructG4PhysVol().
G4double G4tgrPlaceDivRep::GetOffset () const inline
Definition at line 71 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgrPlaceDivRep.hh
References theOffset.
Referenced by G4tgbVolume::ConstructG4PhysVol().
G4double G4tgrPlaceDivRep::GetWidth () const inline
Definition at line 70 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 70 of file G4tgrPlaceDivRep.hh
References theWidth.
Referenced by G4tgbVolume::ConstructG4PhysVol().
void G4tgrPlaceDivRep::SetAxis (EAxis axis) inline
Definition at line 77 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 77 of file G4tgrPlaceDivRep.hh
References theAxis.
Referenced by G4tgrVolumeDivision::G4tgrVolumeDivision().
void G4tgrPlaceDivRep::SetDivType (G4DivType typ) inline
Definition at line 79 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 79 of file G4tgrPlaceDivRep.hh
References theDivType, and pyG4ProcessManager::typ.
Referenced by G4tgrVolumeDivision::G4tgrVolumeDivision().
void G4tgrPlaceDivRep::SetNDiv (G4int ndiv) inline
Definition at line 75 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 75 of file G4tgrPlaceDivRep.hh
References theNDiv.
Referenced by G4tgrVolumeDivision::G4tgrVolumeDivision().
void G4tgrPlaceDivRep::SetOffset (G4double offset) inline
Definition at line 78 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 78 of file G4tgrPlaceDivRep.hh
References offset, and theOffset.
Referenced by G4tgrVolumeDivision::G4tgrVolumeDivision().
void G4tgrPlaceDivRep::SetParentName (const G4String & parentName) inline
Definition at line 74 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 74 of file G4tgrPlaceDivRep.hh
References G4tgrPlace::theParentName.
Referenced by G4tgrVolumeDivision::G4tgrVolumeDivision().
void G4tgrPlaceDivRep::SetWidth (G4double width) inline
Definition at line 76 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 76 of file G4tgrPlaceDivRep.hh
References theWidth.
Referenced by G4tgrVolumeDivision::G4tgrVolumeDivision().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrPlaceDivRep & obj) friend
Definition at line 115 of file G4tgrPlaceDivRep.cc.
View newest version in sPHENIX GitHub at line 115 of file G4tgrPlaceDivRep.cc
Member Data Documentation
EAxis G4tgrPlaceDivRep::theAxis private
Definition at line 87 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 87 of file G4tgrPlaceDivRep.hh
Referenced by G4tgrPlaceDivRep(), GetAxis(), operator<<(), and SetAxis().
G4DivType G4tgrPlaceDivRep::theDivType private
Definition at line 89 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 89 of file G4tgrPlaceDivRep.hh
Referenced by G4tgrPlaceDivRep(), GetDivType(), operator<<(), and SetDivType().
G4int G4tgrPlaceDivRep::theNDiv private
Definition at line 85 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 85 of file G4tgrPlaceDivRep.hh
Referenced by G4tgrPlaceDivRep(), GetNDiv(), operator<<(), and SetNDiv().
G4double G4tgrPlaceDivRep::theOffset private
Definition at line 88 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 88 of file G4tgrPlaceDivRep.hh
Referenced by G4tgrPlaceDivRep(), GetOffset(), operator<<(), and SetOffset().
G4double G4tgrPlaceDivRep::theWidth private
Definition at line 86 of file G4tgrPlaceDivRep.hh.
View newest version in sPHENIX GitHub at line 86 of file G4tgrPlaceDivRep.hh
Referenced by G4tgrPlaceDivRep(), GetWidth(), operator<<(), and SetWidth().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrPlaceDivRep.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrPlaceDivRep.cc