ECCE @ EIC Software: G4KM_NucleonEqRhs Class Reference
G4KM_NucleonEqRhs Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4KM_NucleonEqRhs.hh>
Public Member Functions
G4KM_NucleonEqRhs (G4KM_DummyField *field, G4V3DNucleus *nucleus)
~G4KM_NucleonEqRhs ()
virtual void EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const
virtual void SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double MassXc2)
void SetMass (G4double aMass)
Public Member Functions inherited from G4Mag_EqRhs
G4Mag_EqRhs (G4MagneticField *magField)
virtual ~G4Mag_EqRhs ()
G4double FCof () const
Public Member Functions inherited from G4EquationOfMotion
G4EquationOfMotion (G4Field *Field)
virtual ~G4EquationOfMotion ()
void RightHandSide (const G4double y[], G4double dydx[]) const
void EvaluateRhsReturnB (const G4double y[], G4double dydx[], G4double Field[]) const
void GetFieldValue (const G4double Point[4], G4double Field[]) const
const G4Field * GetFieldObj () const
G4Field * GetFieldObj ()
void SetFieldObj (G4Field *pField)
Private Attributes
G4V3DNucleus * theNucleus
G4double factor
G4int A
G4double theMass
Detailed Description
Definition at line 49 of file G4KM_NucleonEqRhs.hh.
View newest version in sPHENIX GitHub at line 49 of file G4KM_NucleonEqRhs.hh
Constructor & Destructor Documentation
G4KM_NucleonEqRhs::G4KM_NucleonEqRhs (G4KM_DummyField * field, G4V3DNucleus * nucleus)
Definition at line 45 of file G4KM_NucleonEqRhs.cc.
View newest version in sPHENIX GitHub at line 45 of file G4KM_NucleonEqRhs.cc
References A, G4Pow::A23(), factor, G4Pow::GetInstance(), G4V3DNucleus::GetMassNumber(), source.hepunit::hbarc, pi2, theMass, and theNucleus.
G4KM_NucleonEqRhs::~G4KM_NucleonEqRhs () inline
Definition at line 81 of file G4KM_NucleonEqRhs.hh.
View newest version in sPHENIX GitHub at line 81 of file G4KM_NucleonEqRhs.hh
Member Function Documentation
void G4KM_NucleonEqRhs::EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const virtual
Implements G4Mag_EqRhs.
Definition at line 55 of file G4KM_NucleonEqRhs.cc.
View newest version in sPHENIX GitHub at line 55 of file G4KM_NucleonEqRhs.cc
References G4Pow::A13(), source.hepunit::c_light, deriv(), e, factor, G4VNuclearDensity::GetDensity(), G4VNuclearDensity::GetDeriv(), G4Pow::GetInstance(), G4V3DNucleus::GetNuclearDensity(), pos(), theMass, and theNucleus.
void G4KM_NucleonEqRhs::SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double MassXc2) virtual
Reimplemented from G4Mag_EqRhs.
Definition at line 112 of file G4KM_NucleonEqRhs.cc.
View newest version in sPHENIX GitHub at line 112 of file G4KM_NucleonEqRhs.cc
void G4KM_NucleonEqRhs::SetMass (G4double aMass) inline
Definition at line 74 of file G4KM_NucleonEqRhs.hh.
View newest version in sPHENIX GitHub at line 74 of file G4KM_NucleonEqRhs.hh
References theMass.
Referenced by G4RKPropagation::Init().
Member Data Documentation
G4int G4KM_NucleonEqRhs::A private
Definition at line 68 of file G4KM_NucleonEqRhs.hh.
View newest version in sPHENIX GitHub at line 68 of file G4KM_NucleonEqRhs.hh
Referenced by G4KM_NucleonEqRhs().
G4double G4KM_NucleonEqRhs::factor private
Definition at line 67 of file G4KM_NucleonEqRhs.hh.
View newest version in sPHENIX GitHub at line 67 of file G4KM_NucleonEqRhs.hh
Referenced by EvaluateRhsGivenB(), and G4KM_NucleonEqRhs().
G4double G4KM_NucleonEqRhs::theMass private
Definition at line 69 of file G4KM_NucleonEqRhs.hh.
View newest version in sPHENIX GitHub at line 69 of file G4KM_NucleonEqRhs.hh
Referenced by EvaluateRhsGivenB(), G4KM_NucleonEqRhs(), and SetMass().
G4V3DNucleus* G4KM_NucleonEqRhs::theNucleus private
Definition at line 66 of file G4KM_NucleonEqRhs.hh.
View newest version in sPHENIX GitHub at line 66 of file G4KM_NucleonEqRhs.hh
Referenced by EvaluateRhsGivenB(), and G4KM_NucleonEqRhs().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4KM_NucleonEqRhs.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4KM_NucleonEqRhs.cc