ECCE @ EIC Software: G4FTFParameters Class Reference
G4FTFParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4FTFParameters.hh>
Public Member Functions
G4FTFParameters ()
~G4FTFParameters ()
void InitForInteraction (const G4ParticleDefinition *, G4int theA, G4int theZ, G4double s)
void SethNcmsEnergy (const G4double s)
void SetTotalCrossSection (const G4double Xtotal)
void SetElastisCrossSection (const G4double Xelastic)
void SetInelasticCrossSection (const G4double Xinelastic)
void SetProbabilityOfElasticScatt (const G4double Xtotal, const G4double Xelastic)
void SetProbabilityOfElasticScatt (const G4double aValue)
void SetProbabilityOfAnnihilation (const G4double aValue)
void SetRadiusOfHNinteractions2 (const G4double Radius2)
void SetSlope (const G4double Slope)
void SetGamma0 (const G4double Gamma0)
G4double GammaElastic (const G4double impactsquare)
void SetAvaragePt2ofElasticScattering (const G4double aPt2)
void SetParams (const G4int ProcN, const G4double A1, const G4double B1, const G4double A2, const G4double B2, const G4double A3, const G4double Atop, const G4double Ymin)
void SetDeltaProbAtQuarkExchange (const G4double aValue)
void SetProbOfSameQuarkExchange (const G4double aValue)
void SetProjMinDiffMass (const G4double aValue)
void SetProjMinNonDiffMass (const G4double aValue)
void SetProbLogDistrPrD (const G4double aValue)
void SetTarMinDiffMass (const G4double aValue)
void SetTarMinNonDiffMass (const G4double aValue)
void SetAveragePt2 (const G4double aValue)
void SetProbLogDistr (const G4double aValue)
void SetPt2Kink (const G4double aValue)
void SetQuarkProbabilitiesAtGluonSplitUp (const G4double Puubar, const G4double Pddbar, const G4double Pssbar)
void SetMaxNumberOfCollisions (const G4double aValue, const G4double bValue)
void SetProbOfInteraction (const G4double aValue)
void SetCofNuclearDestructionPr (const G4double aValue)
void SetCofNuclearDestruction (const G4double aValue)
void SetR2ofNuclearDestruction (const G4double aValue)
void SetExcitationEnergyPerWoundedNucleon (const G4double aValue)
void SetDofNuclearDestruction (const G4double aValue)
void SetPt2ofNuclearDestruction (const G4double aValue)
void SetMaxPt2ofNuclearDestruction (const G4double aValue)
G4double GetTotalCrossSection ()
G4double GetElasticCrossSection ()
G4double GetInelasticCrossSection ()
G4double GetProbabilityOfInteraction (const G4double impactsquare)
G4double GetInelasticProbability (const G4double impactsquare)
G4double GetProbabilityOfElasticScatt ()
G4double GetSlope ()
G4double GetProbabilityOfAnnihilation ()
G4double GetAvaragePt2ofElasticScattering ()
G4double GetProcProb (const G4int ProcN, const G4double y)
G4double GetDeltaProbAtQuarkExchange ()
G4double GetProbOfSameQuarkExchange ()
G4double GetProjMinDiffMass ()
G4double GetProjMinNonDiffMass ()
G4double GetProbLogDistrPrD ()
G4double GetTarMinDiffMass ()
G4double GetTarMinNonDiffMass ()
G4double GetAveragePt2 ()
G4double GetProbLogDistr ()
G4double GetPt2Kink ()
std::vector< G4double > GetQuarkProbabilitiesAtGluonSplitUp ()
G4double GetMaxNumberOfCollisions ()
G4double GetProbOfInteraction ()
G4double GetCofNuclearDestructionPr ()
G4double GetCofNuclearDestruction ()
G4double GetR2ofNuclearDestruction ()
G4double GetExcitationEnergyPerWoundedNucleon ()
G4double GetDofNuclearDestruction ()
G4double GetPt2ofNuclearDestruction ()
G4double GetMaxPt2ofNuclearDestruction ()
Public Attributes
G4double FTFhNcmsEnergy
G4double FTFXtotal
G4double FTFXelastic
G4double FTFXinelastic
G4double FTFXannihilation
G4double ProbabilityOfAnnihilation
G4double ProbabilityOfElasticScatt
G4double RadiusOfHNinteractions2
G4double FTFSlope
G4double AvaragePt2ofElasticScattering
G4double FTFGamma0
G4double ProcParams [5][7]
G4double DeltaProbAtQuarkExchange
G4double ProbOfSameQuarkExchange
G4double ProjMinDiffMass
G4double ProjMinNonDiffMass
G4double ProbLogDistrPrD
G4double TarMinDiffMass
G4double TarMinNonDiffMass
G4double AveragePt2
G4double ProbLogDistr
G4double Pt2kink
std::vector< G4double > QuarkProbabilitiesAtGluonSplitUp
G4double MaxNumberOfCollisions
G4double ProbOfInelInteraction
G4double CofNuclearDestructionPr
G4double CofNuclearDestruction
G4double R2ofNuclearDestruction
G4double ExcitationEnergyPerWoundedNucleon
G4double DofNuclearDestruction
G4double Pt2ofNuclearDestruction
G4double MaxPt2ofNuclearDestruction
Private Member Functions
G4double GetMinMass (const G4ParticleDefinition *aParticle)
void Reset ()
Private Attributes
G4LundStringFragmentation * StringMass
G4FTFParamCollBaryonProj fParCollBaryonProj
G4FTFParamCollMesonProj fParCollMesonProj
G4FTFParamCollPionProj fParCollPionProj
G4VComponentCrossSection * csGGinstance
Detailed Description
Definition at line 305 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 305 of file G4FTFParameters.hh
Constructor & Destructor Documentation
G4FTFParameters::G4FTFParameters ()
Definition at line 62 of file G4FTFParameters.cc.
View newest version in sPHENIX GitHub at line 62 of file G4FTFParameters.cc
References csGGinstance, G4CrossSectionDataSetRegistry::GetComponentCrossSection(), GeV, G4CrossSectionDataSetRegistry::Instance(), Reset(), SetPt2Kink(), SetQuarkProbabilitiesAtGluonSplitUp(), and StringMass.
G4FTFParameters::~G4FTFParameters ()
Definition at line 1483 of file G4FTFParameters.cc.
View newest version in sPHENIX GitHub at line 1483 of file G4FTFParameters.cc
References StringMass.
Member Function Documentation
G4double G4FTFParameters::GammaElastic (const G4double impactsquare) inline
Definition at line 488 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 488 of file G4FTFParameters.hh
References FTFGamma0, FTFSlope, and G4Exp().
Referenced by GetInelasticProbability().
G4double G4FTFParameters::GetAvaragePt2ofElasticScattering () inline
Definition at line 691 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 691 of file G4FTFParameters.hh
References AvaragePt2ofElasticScattering.
Referenced by G4ElasticHNScattering::ElasticScattering(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), and InitForInteraction().
G4double G4FTFParameters::GetAveragePt2 () inline
Definition at line 721 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 721 of file G4FTFParameters.hh
References AveragePt2.
Referenced by G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), and InitForInteraction().
G4double G4FTFParameters::GetCofNuclearDestruction () inline
Definition at line 757 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 757 of file G4FTFParameters.hh
References CofNuclearDestruction.
Referenced by InitForInteraction(), and G4FTFModel::ReggeonCascade().
G4double G4FTFParameters::GetCofNuclearDestructionPr () inline
Definition at line 753 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 753 of file G4FTFParameters.hh
References CofNuclearDestructionPr.
Referenced by InitForInteraction(), and G4FTFModel::ReggeonCascade().
G4double G4FTFParameters::GetDeltaProbAtQuarkExchange () inline
Definition at line 697 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 697 of file G4FTFParameters.hh
References DeltaProbAtQuarkExchange.
Referenced by G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), and InitForInteraction().
G4double G4FTFParameters::GetDofNuclearDestruction () inline
Definition at line 769 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 769 of file G4FTFParameters.hh
References DofNuclearDestruction.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), InitForInteraction(), and G4FTFModel::PutOnMassShell().
G4double G4FTFParameters::GetElasticCrossSection () inline
Definition at line 657 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 657 of file G4FTFParameters.hh
References FTFXelastic.
G4double G4FTFParameters::GetExcitationEnergyPerWoundedNucleon () inline
Definition at line 765 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 765 of file G4FTFParameters.hh
References ExcitationEnergyPerWoundedNucleon.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel::ComputeNucleusProperties(), InitForInteraction(), and G4FTFModel::ReggeonCascade().
G4double G4FTFParameters::GetInelasticCrossSection () inline
Definition at line 661 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 661 of file G4FTFParameters.hh
References FTFXinelastic.
G4double G4FTFParameters::GetInelasticProbability (const G4double impactsquare) inline
Definition at line 681 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 681 of file G4FTFParameters.hh
References GammaElastic().
G4double G4FTFParameters::GetMaxNumberOfCollisions () inline
Definition at line 745 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 745 of file G4FTFParameters.hh
References MaxNumberOfCollisions.
Referenced by G4FTFModel::ExciteParticipants().
G4double G4FTFParameters::GetMaxPt2ofNuclearDestruction () inline
Definition at line 777 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 777 of file G4FTFParameters.hh
References MaxPt2ofNuclearDestruction.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), and G4FTFModel::PutOnMassShell().
G4double G4FTFParameters::GetMinMass (const G4ParticleDefinition * aParticle) private
Definition at line 824 of file G4FTFParameters.cc.
View newest version in sPHENIX GitHub at line 824 of file G4FTFParameters.cc
References kdfinder::abs(), G4ParticleDefinition::GetPDGEncoding(), max, min, G4VLongitudinalStringDecay::minMassQDiQStr, G4VLongitudinalStringDecay::minMassQQbarStr, and StringMass.
Referenced by InitForInteraction().
G4double G4FTFParameters::GetProbabilityOfAnnihilation () inline
Definition at line 686 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 686 of file G4FTFParameters.hh
References ProbabilityOfAnnihilation.
Referenced by G4FTFModel::ExciteParticipants().
G4double G4FTFParameters::GetProbabilityOfElasticScatt () inline
Definition at line 677 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 677 of file G4FTFParameters.hh
References ProbabilityOfElasticScatt.
Referenced by G4FTFModel::ExciteParticipants().
G4double G4FTFParameters::GetProbabilityOfInteraction (const G4double impactsquare) inline
Definition at line 669 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 669 of file G4FTFParameters.hh
References RadiusOfHNinteractions2.
Referenced by G4FTFParticipants::GetList().
G4double G4FTFParameters::GetProbLogDistr () inline
Definition at line 729 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 729 of file G4FTFParameters.hh
References ProbLogDistr.
Referenced by G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), and InitForInteraction().
G4double G4FTFParameters::GetProbLogDistrPrD () inline
Definition at line 725 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 725 of file G4FTFParameters.hh
References ProbLogDistrPrD.
Referenced by G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), and InitForInteraction().
G4double G4FTFParameters::GetProbOfInteraction () inline
Definition at line 749 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 749 of file G4FTFParameters.hh
References ProbOfInelInteraction.
G4double G4FTFParameters::GetProbOfSameQuarkExchange () inline
Definition at line 701 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 701 of file G4FTFParameters.hh
References ProbOfSameQuarkExchange.
Referenced by G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), and InitForInteraction().
G4double G4FTFParameters::GetProcProb (const G4int ProcN, const G4double y)
Definition at line 848 of file G4FTFParameters.cc.
View newest version in sPHENIX GitHub at line 848 of file G4FTFParameters.cc
References G4Exp(), and ProcParams.
Referenced by G4DiffractiveExcitation::ExciteParticipants().
G4double G4FTFParameters::GetProjMinDiffMass () inline
Definition at line 705 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 705 of file G4FTFParameters.hh
References ProjMinDiffMass.
Referenced by G4DiffractiveExcitation::CreateStrings(), G4DiffractiveExcitation::ExciteParticipants(), and InitForInteraction().
G4double G4FTFParameters::GetProjMinNonDiffMass () inline
Definition at line 709 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 709 of file G4FTFParameters.hh
References ProjMinNonDiffMass.
Referenced by G4DiffractiveExcitation::ExciteParticipants(), and InitForInteraction().
G4double G4FTFParameters::GetPt2Kink () inline
Definition at line 735 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 735 of file G4FTFParameters.hh
References Pt2kink.
Referenced by G4DiffractiveExcitation::CreateStrings().
G4double G4FTFParameters::GetPt2ofNuclearDestruction () inline
Definition at line 773 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 773 of file G4FTFParameters.hh
References Pt2ofNuclearDestruction.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), InitForInteraction(), and G4FTFModel::PutOnMassShell().
std::vector< G4double > G4FTFParameters::GetQuarkProbabilitiesAtGluonSplitUp () inline
Definition at line 739 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 739 of file G4FTFParameters.hh
References QuarkProbabilitiesAtGluonSplitUp.
Referenced by G4DiffractiveExcitation::CreateStrings().
G4double G4FTFParameters::GetR2ofNuclearDestruction () inline
Definition at line 761 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 761 of file G4FTFParameters.hh
References R2ofNuclearDestruction.
Referenced by InitForInteraction(), and G4FTFModel::ReggeonCascade().
G4double G4FTFParameters::GetSlope () inline
Definition at line 665 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 665 of file G4FTFParameters.hh
References FTFSlope.
Referenced by InitForInteraction().
G4double G4FTFParameters::GetTarMinDiffMass () inline
Definition at line 713 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 713 of file G4FTFParameters.hh
References TarMinDiffMass.
Referenced by G4DiffractiveExcitation::CreateStrings(), G4DiffractiveExcitation::ExciteParticipants(), and InitForInteraction().
G4double G4FTFParameters::GetTarMinNonDiffMass () inline
Definition at line 717 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 717 of file G4FTFParameters.hh
References TarMinNonDiffMass.
Referenced by G4DiffractiveExcitation::ExciteParticipants(), and InitForInteraction().
G4double G4FTFParameters::GetTotalCrossSection () inline
Definition at line 653 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 653 of file G4FTFParameters.hh
References FTFXtotal.
void G4FTFParameters::InitForInteraction (const G4ParticleDefinition * particle, G4int theA, G4int theZ, G4double s)
Definition at line 81 of file G4FTFParameters.cc.
View newest version in sPHENIX GitHub at line 81 of file G4FTFParameters.cc
References kdfinder::abs(), csGGinstance, fermi, fParCollBaryonProj, fParCollMesonProj, fParCollPionProj, G4cout, G4endl, G4Exp(), G4Log(), GetAvaragePt2ofElasticScattering(), G4FTFParamCollection::GetAveragePt2(), GetAveragePt2(), G4ParticleDefinition::GetBaryonNumber(), GetCofNuclearDestruction(), GetCofNuclearDestructionPr(), G4FTFParamCollection::GetDeltaProbAtQuarkExchange(), GetDeltaProbAtQuarkExchange(), G4FTFParamCollection::GetDofNuclearDestruct(), GetDofNuclearDestruction(), G4VComponentCrossSection::GetElasticIsotopeCrossSection(), G4FTFParamCollection::GetExciEnergyPerWoundedNucleon(), GetExcitationEnergyPerWoundedNucleon(), G4Pow::GetInstance(), G4FTFParamCollection::GetMaxPt2ofNuclearDestruct(), GetMinMass(), G4FTFParamCollection::GetNuclearProjDestructP1(), G4FTFParamCollection::GetNuclearProjDestructP2(), G4FTFParamCollection::GetNuclearProjDestructP3(), G4FTFParamCollection::GetNuclearTgtDestructP1(), G4FTFParamCollection::GetNuclearTgtDestructP2(), G4FTFParamCollection::GetNuclearTgtDestructP3(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4FTFParamCollection::GetProbLogDistr(), GetProbLogDistr(), G4FTFParamCollection::GetProbLogDistrPrD(), GetProbLogDistrPrD(), G4FTFParamCollection::GetProbOfSameQuarkExchange(), GetProbOfSameQuarkExchange(), G4FTFParamCollection::GetProc0A1(), G4FTFParamCollection::GetProc0A2(), G4FTFParamCollection::GetProc0A3(), G4FTFParamCollection::GetProc0Atop(), G4FTFParamCollection::GetProc0B1(), G4FTFParamCollection::GetProc0B2(), G4FTFParamCollection::GetProc0Ymin(), G4FTFParamCollection::GetProc1A1(), G4FTFParamCollection::GetProc1A2(), G4FTFParamCollection::GetProc1A3(), G4FTFParamCollection::GetProc1Atop(), G4FTFParamCollection::GetProc1B1(), G4FTFParamCollection::GetProc1B2(), G4FTFParamCollection::GetProc1Ymin(), G4FTFParamCollection::GetProc2A1(), G4FTFParamCollection::GetProc2A2(), G4FTFParamCollection::GetProc2A3(), G4FTFParamCollection::GetProc2Atop(), G4FTFParamCollection::GetProc2B1(), G4FTFParamCollection::GetProc2B2(), G4FTFParamCollection::GetProc2Ymin(), G4FTFParamCollection::GetProc3A1(), G4FTFParamCollection::GetProc3A2(), G4FTFParamCollection::GetProc3A3(), G4FTFParamCollection::GetProc3Atop(), G4FTFParamCollection::GetProc3B1(), G4FTFParamCollection::GetProc3B2(), G4FTFParamCollection::GetProc3Ymin(), G4FTFParamCollection::GetProc4A1(), G4FTFParamCollection::GetProc4A2(), G4FTFParamCollection::GetProc4A3(), G4FTFParamCollection::GetProc4Atop(), G4FTFParamCollection::GetProc4B1(), G4FTFParamCollection::GetProc4B2(), G4FTFParamCollection::GetProc4Ymin(), G4FTFParamCollection::GetProjMinDiffMass(), GetProjMinDiffMass(), G4FTFParamCollection::GetProjMinNonDiffMass(), GetProjMinNonDiffMass(), G4FTFParamCollection::GetPt2NuclearDestructP1(), G4FTFParamCollection::GetPt2NuclearDestructP2(), G4FTFParamCollection::GetPt2NuclearDestructP3(), G4FTFParamCollection::GetPt2NuclearDestructP4(), GetPt2ofNuclearDestruction(), G4FTFParamCollection::GetR2ofNuclearDestruct(), GetR2ofNuclearDestruction(), GetSlope(), GetTarMinDiffMass(), GetTarMinNonDiffMass(), G4FTFParamCollection::GetTgtMinDiffMass(), G4FTFParamCollection::GetTgtMinNonDiffMass(), G4VComponentCrossSection::GetTotalIsotopeCrossSection(), CLHEP::GeV, GeV, G4FTFParamCollection::IsNuclearProjDestructP1_NBRNDEP(), G4FTFParamCollection::IsNuclearTgtDestructP1_ADEP(), G4FTFParamCollection::IsProjDiffDissociation(), G4FTFParamCollection::IsTgtDiffDissociation(), MeV, millibarn, G4Neutron::Neutron(), Neutron, pi, G4Pow::powA(), G4Proton::Proton(), Proton, Reset(), S(), SetAvaragePt2ofElasticScattering(), SetAveragePt2(), SetCofNuclearDestruction(), SetCofNuclearDestructionPr(), SetDeltaProbAtQuarkExchange(), SetDofNuclearDestruction(), SetElastisCrossSection(), SetExcitationEnergyPerWoundedNucleon(), SetGamma0(), SetInelasticCrossSection(), SetMaxNumberOfCollisions(), SetMaxPt2ofNuclearDestruction(), SetParams(), SetProbabilityOfAnnihilation(), SetProbabilityOfElasticScatt(), SetProbLogDistr(), SetProbLogDistrPrD(), SetProbOfSameQuarkExchange(), SetProjMinDiffMass(), SetProjMinNonDiffMass(), SetPt2ofNuclearDestruction(), SetR2ofNuclearDestruction(), SetRadiusOfHNinteractions2(), SetSlope(), SetTarMinDiffMass(), SetTarMinNonDiffMass(), SetTotalCrossSection(), and sqr().
Referenced by G4FTFModel::Init().
void G4FTFParameters::Reset () private
Definition at line 1489 of file G4FTFParameters.cc.
View newest version in sPHENIX GitHub at line 1489 of file G4FTFParameters.cc
References AvaragePt2ofElasticScattering, AveragePt2, CofNuclearDestruction, CofNuclearDestructionPr, DeltaProbAtQuarkExchange, DofNuclearDestruction, ExcitationEnergyPerWoundedNucleon, FTFGamma0, FTFhNcmsEnergy, FTFSlope, FTFXannihilation, FTFXelastic, FTFXinelastic, FTFXtotal, MaxNumberOfCollisions, MaxPt2ofNuclearDestruction, ProbabilityOfAnnihilation, ProbabilityOfElasticScatt, ProbLogDistr, ProbLogDistrPrD, ProbOfInelInteraction, ProbOfSameQuarkExchange, ProcParams, ProjMinDiffMass, ProjMinNonDiffMass, Pt2kink, Pt2ofNuclearDestruction, R2ofNuclearDestruction, RadiusOfHNinteractions2, TarMinDiffMass, and TarMinNonDiffMass.
Referenced by G4FTFParameters(), and InitForInteraction().
void G4FTFParameters::SetAvaragePt2ofElasticScattering (const G4double aPt2) inline
Definition at line 540 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 540 of file G4FTFParameters.hh
References AvaragePt2ofElasticScattering.
Referenced by InitForInteraction().
void G4FTFParameters::SetAveragePt2 (const G4double aValue) inline
Definition at line 580 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 580 of file G4FTFParameters.hh
References AveragePt2, and CLHEP::GeV.
Referenced by InitForInteraction().
void G4FTFParameters::SetCofNuclearDestruction (const G4double aValue) inline
Definition at line 628 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 628 of file G4FTFParameters.hh
References CofNuclearDestruction.
Referenced by InitForInteraction().
void G4FTFParameters::SetCofNuclearDestructionPr (const G4double aValue) inline
Definition at line 624 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 624 of file G4FTFParameters.hh
References CofNuclearDestructionPr.
Referenced by InitForInteraction().
void G4FTFParameters::SetDeltaProbAtQuarkExchange (const G4double aValue) inline
Definition at line 556 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 556 of file G4FTFParameters.hh
References DeltaProbAtQuarkExchange.
Referenced by InitForInteraction().
void G4FTFParameters::SetDofNuclearDestruction (const G4double aValue) inline
Definition at line 640 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 640 of file G4FTFParameters.hh
References DofNuclearDestruction.
Referenced by InitForInteraction().
void G4FTFParameters::SetElastisCrossSection (const G4double Xelastic) inline
Definition at line 502 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 502 of file G4FTFParameters.hh
References FTFXelastic.
Referenced by InitForInteraction().
void G4FTFParameters::SetExcitationEnergyPerWoundedNucleon (const G4double aValue) inline
Definition at line 636 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 636 of file G4FTFParameters.hh
References ExcitationEnergyPerWoundedNucleon.
Referenced by InitForInteraction().
void G4FTFParameters::SetGamma0 (const G4double Gamma0) inline
Definition at line 535 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 535 of file G4FTFParameters.hh
References FTFGamma0.
Referenced by InitForInteraction().
void G4FTFParameters::SethNcmsEnergy (const G4double s) inline
Definition at line 492 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 492 of file G4FTFParameters.hh
References FTFhNcmsEnergy, and S().
void G4FTFParameters::SetInelasticCrossSection (const G4double Xinelastic) inline
Definition at line 506 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 506 of file G4FTFParameters.hh
References FTFXinelastic.
Referenced by InitForInteraction().
void G4FTFParameters::SetMaxNumberOfCollisions (const G4double aValue, const G4double bValue) inline
Definition at line 607 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 607 of file G4FTFParameters.hh
References MaxNumberOfCollisions, and SetProbOfInteraction().
Referenced by InitForInteraction().
void G4FTFParameters::SetMaxPt2ofNuclearDestruction (const G4double aValue) inline
Definition at line 648 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 648 of file G4FTFParameters.hh
References MaxPt2ofNuclearDestruction.
Referenced by InitForInteraction().
void G4FTFParameters::SetParams (const G4int ProcN, const G4double A1, const G4double B1, const G4double A2, const G4double B2, const G4double A3, const G4double Atop, const G4double Ymin) inline
Definition at line 546 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 546 of file G4FTFParameters.hh
References ProcParams, and Ymin.
Referenced by InitForInteraction().
void G4FTFParameters::SetProbabilityOfAnnihilation (const G4double aValue) inline
Definition at line 523 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 523 of file G4FTFParameters.hh
References ProbabilityOfAnnihilation.
Referenced by InitForInteraction().
void G4FTFParameters::SetProbabilityOfElasticScatt (const G4double Xtotal, const G4double Xelastic) inline
Definition at line 510 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 510 of file G4FTFParameters.hh
References ProbabilityOfElasticScatt.
Referenced by G4FTFModel::Init(), and InitForInteraction().
void G4FTFParameters::SetProbabilityOfElasticScatt (const G4double aValue) inline
Definition at line 519 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 519 of file G4FTFParameters.hh
References ProbabilityOfElasticScatt.
void G4FTFParameters::SetProbLogDistr (const G4double aValue) inline
Definition at line 588 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 588 of file G4FTFParameters.hh
References ProbLogDistr.
Referenced by InitForInteraction().
void G4FTFParameters::SetProbLogDistrPrD (const G4double aValue) inline
Definition at line 584 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 584 of file G4FTFParameters.hh
References ProbLogDistrPrD.
Referenced by InitForInteraction().
void G4FTFParameters::SetProbOfInteraction (const G4double aValue) inline
Definition at line 620 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 620 of file G4FTFParameters.hh
References ProbOfInelInteraction.
Referenced by SetMaxNumberOfCollisions().
void G4FTFParameters::SetProbOfSameQuarkExchange (const G4double aValue) inline
Definition at line 560 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 560 of file G4FTFParameters.hh
References ProbOfSameQuarkExchange.
Referenced by InitForInteraction().
void G4FTFParameters::SetProjMinDiffMass (const G4double aValue) inline
Definition at line 564 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 564 of file G4FTFParameters.hh
References CLHEP::GeV, and ProjMinDiffMass.
Referenced by G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), and InitForInteraction().
void G4FTFParameters::SetProjMinNonDiffMass (const G4double aValue) inline
Definition at line 568 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 568 of file G4FTFParameters.hh
References CLHEP::GeV, and ProjMinNonDiffMass.
Referenced by G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), and InitForInteraction().
void G4FTFParameters::SetPt2Kink (const G4double aValue) inline
Definition at line 594 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 594 of file G4FTFParameters.hh
References Pt2kink.
Referenced by G4FTFParameters().
void G4FTFParameters::SetPt2ofNuclearDestruction (const G4double aValue) inline
Definition at line 644 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 644 of file G4FTFParameters.hh
References Pt2ofNuclearDestruction.
Referenced by InitForInteraction().
void G4FTFParameters::SetQuarkProbabilitiesAtGluonSplitUp (const G4double Puubar, const G4double Pddbar, const G4double Pssbar) inline
Definition at line 598 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 598 of file G4FTFParameters.hh
References QuarkProbabilitiesAtGluonSplitUp.
Referenced by G4FTFParameters().
void G4FTFParameters::SetR2ofNuclearDestruction (const G4double aValue) inline
Definition at line 632 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 632 of file G4FTFParameters.hh
References R2ofNuclearDestruction.
Referenced by InitForInteraction().
void G4FTFParameters::SetRadiusOfHNinteractions2 (const G4double Radius2) inline
Definition at line 527 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 527 of file G4FTFParameters.hh
References RadiusOfHNinteractions2.
Referenced by InitForInteraction().
void G4FTFParameters::SetSlope (const G4double Slope) inline
Definition at line 531 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 531 of file G4FTFParameters.hh
References FTFSlope.
Referenced by InitForInteraction().
void G4FTFParameters::SetTarMinDiffMass (const G4double aValue) inline
Definition at line 572 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 572 of file G4FTFParameters.hh
References CLHEP::GeV, and TarMinDiffMass.
Referenced by G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), and InitForInteraction().
void G4FTFParameters::SetTarMinNonDiffMass (const G4double aValue) inline
Definition at line 576 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 576 of file G4FTFParameters.hh
References CLHEP::GeV, and TarMinNonDiffMass.
Referenced by G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), and InitForInteraction().
void G4FTFParameters::SetTotalCrossSection (const G4double Xtotal) inline
Definition at line 498 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 498 of file G4FTFParameters.hh
References FTFXtotal.
Referenced by InitForInteraction().
Member Data Documentation
G4double G4FTFParameters::AvaragePt2ofElasticScattering
Definition at line 433 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 433 of file G4FTFParameters.hh
Referenced by GetAvaragePt2ofElasticScattering(), Reset(), and SetAvaragePt2ofElasticScattering().
G4double G4FTFParameters::AveragePt2
Definition at line 448 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 448 of file G4FTFParameters.hh
Referenced by GetAveragePt2(), Reset(), and SetAveragePt2().
G4double G4FTFParameters::CofNuclearDestruction
Definition at line 460 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 460 of file G4FTFParameters.hh
Referenced by GetCofNuclearDestruction(), Reset(), and SetCofNuclearDestruction().
G4double G4FTFParameters::CofNuclearDestructionPr
Definition at line 459 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 459 of file G4FTFParameters.hh
Referenced by GetCofNuclearDestructionPr(), Reset(), and SetCofNuclearDestructionPr().
G4VComponentCrossSection* G4FTFParameters::csGGinstance private
Definition at line 484 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 484 of file G4FTFParameters.hh
Referenced by G4FTFParameters(), and InitForInteraction().
G4double G4FTFParameters::DeltaProbAtQuarkExchange
Definition at line 439 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 439 of file G4FTFParameters.hh
Referenced by GetDeltaProbAtQuarkExchange(), Reset(), and SetDeltaProbAtQuarkExchange().
G4double G4FTFParameters::DofNuclearDestruction
Definition at line 465 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 465 of file G4FTFParameters.hh
Referenced by GetDofNuclearDestruction(), Reset(), and SetDofNuclearDestruction().
G4double G4FTFParameters::ExcitationEnergyPerWoundedNucleon
Definition at line 463 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 463 of file G4FTFParameters.hh
Referenced by GetExcitationEnergyPerWoundedNucleon(), Reset(), and SetExcitationEnergyPerWoundedNucleon().
G4FTFParamCollBaryonProj G4FTFParameters::fParCollBaryonProj private
Definition at line 477 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 477 of file G4FTFParameters.hh
Referenced by InitForInteraction().
G4FTFParamCollMesonProj G4FTFParameters::fParCollMesonProj private
Definition at line 480 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 480 of file G4FTFParameters.hh
Referenced by InitForInteraction().
G4FTFParamCollPionProj G4FTFParameters::fParCollPionProj private
Definition at line 481 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 481 of file G4FTFParameters.hh
Referenced by InitForInteraction().
G4double G4FTFParameters::FTFGamma0
Definition at line 434 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 434 of file G4FTFParameters.hh
Referenced by GammaElastic(), Reset(), and SetGamma0().
G4double G4FTFParameters::FTFhNcmsEnergy
Definition at line 422 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 422 of file G4FTFParameters.hh
Referenced by Reset(), and SethNcmsEnergy().
G4double G4FTFParameters::FTFSlope
Definition at line 432 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 432 of file G4FTFParameters.hh
Referenced by GammaElastic(), GetSlope(), Reset(), and SetSlope().
G4double G4FTFParameters::FTFXannihilation
Definition at line 428 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 428 of file G4FTFParameters.hh
Referenced by Reset().
G4double G4FTFParameters::FTFXelastic
Definition at line 426 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 426 of file G4FTFParameters.hh
Referenced by GetElasticCrossSection(), Reset(), and SetElastisCrossSection().
G4double G4FTFParameters::FTFXinelastic
Definition at line 427 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 427 of file G4FTFParameters.hh
Referenced by GetInelasticCrossSection(), Reset(), and SetInelasticCrossSection().
G4double G4FTFParameters::FTFXtotal
Definition at line 425 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 425 of file G4FTFParameters.hh
Referenced by GetTotalCrossSection(), Reset(), and SetTotalCrossSection().
G4double G4FTFParameters::MaxNumberOfCollisions
Definition at line 456 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 456 of file G4FTFParameters.hh
Referenced by GetMaxNumberOfCollisions(), Reset(), and SetMaxNumberOfCollisions().
G4double G4FTFParameters::MaxPt2ofNuclearDestruction
Definition at line 467 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 467 of file G4FTFParameters.hh
Referenced by GetMaxPt2ofNuclearDestruction(), Reset(), and SetMaxPt2ofNuclearDestruction().
G4double G4FTFParameters::ProbabilityOfAnnihilation
Definition at line 429 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 429 of file G4FTFParameters.hh
Referenced by GetProbabilityOfAnnihilation(), Reset(), and SetProbabilityOfAnnihilation().
G4double G4FTFParameters::ProbabilityOfElasticScatt
Definition at line 430 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 430 of file G4FTFParameters.hh
Referenced by GetProbabilityOfElasticScatt(), Reset(), and SetProbabilityOfElasticScatt().
G4double G4FTFParameters::ProbLogDistr
Definition at line 449 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 449 of file G4FTFParameters.hh
Referenced by GetProbLogDistr(), Reset(), and SetProbLogDistr().
G4double G4FTFParameters::ProbLogDistrPrD
Definition at line 444 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 444 of file G4FTFParameters.hh
Referenced by GetProbLogDistrPrD(), Reset(), and SetProbLogDistrPrD().
G4double G4FTFParameters::ProbOfInelInteraction
Definition at line 457 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 457 of file G4FTFParameters.hh
Referenced by GetProbOfInteraction(), Reset(), and SetProbOfInteraction().
G4double G4FTFParameters::ProbOfSameQuarkExchange
Definition at line 440 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 440 of file G4FTFParameters.hh
Referenced by GetProbOfSameQuarkExchange(), Reset(), and SetProbOfSameQuarkExchange().
G4double G4FTFParameters::ProcParams[5][7]
Definition at line 437 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 437 of file G4FTFParameters.hh
Referenced by GetProcProb(), Reset(), and SetParams().
G4double G4FTFParameters::ProjMinDiffMass
Definition at line 442 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 442 of file G4FTFParameters.hh
Referenced by GetProjMinDiffMass(), Reset(), and SetProjMinDiffMass().
G4double G4FTFParameters::ProjMinNonDiffMass
Definition at line 443 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 443 of file G4FTFParameters.hh
Referenced by GetProjMinNonDiffMass(), Reset(), and SetProjMinNonDiffMass().
G4double G4FTFParameters::Pt2kink
Definition at line 452 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 452 of file G4FTFParameters.hh
Referenced by GetPt2Kink(), Reset(), and SetPt2Kink().
G4double G4FTFParameters::Pt2ofNuclearDestruction
Definition at line 466 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 466 of file G4FTFParameters.hh
Referenced by GetPt2ofNuclearDestruction(), Reset(), and SetPt2ofNuclearDestruction().
std::vector< G4double > G4FTFParameters::QuarkProbabilitiesAtGluonSplitUp
Definition at line 453 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 453 of file G4FTFParameters.hh
Referenced by GetQuarkProbabilitiesAtGluonSplitUp(), and SetQuarkProbabilitiesAtGluonSplitUp().
G4double G4FTFParameters::R2ofNuclearDestruction
Definition at line 461 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 461 of file G4FTFParameters.hh
Referenced by GetR2ofNuclearDestruction(), Reset(), and SetR2ofNuclearDestruction().
G4double G4FTFParameters::RadiusOfHNinteractions2
Definition at line 431 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 431 of file G4FTFParameters.hh
Referenced by GetProbabilityOfInteraction(), Reset(), and SetRadiusOfHNinteractions2().
G4LundStringFragmentation* G4FTFParameters::StringMass private
Definition at line 470 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 470 of file G4FTFParameters.hh
Referenced by G4FTFParameters(), GetMinMass(), and ~G4FTFParameters().
G4double G4FTFParameters::TarMinDiffMass
Definition at line 445 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 445 of file G4FTFParameters.hh
Referenced by GetTarMinDiffMass(), Reset(), and SetTarMinDiffMass().
G4double G4FTFParameters::TarMinNonDiffMass
Definition at line 446 of file G4FTFParameters.hh.
View newest version in sPHENIX GitHub at line 446 of file G4FTFParameters.hh
Referenced by GetTarMinNonDiffMass(), Reset(), and SetTarMinNonDiffMass().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4FTFParameters.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/src/G4FTFParameters.cc