ECCE @ EIC Software: HEPREP::HepRepAttribute Class Reference
HEPREP::HepRepAttribute Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepAttribute.h>
Public Member Functions
virtual ~HepRepAttribute ()
Destructor.
virtual void addAttValue (HepRepAttValue *attValue)=0
virtual void addAttValue (std::string key, char *value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, std::string value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, int64 value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, int value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, double value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, bool value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, std::vector< double > value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, double red, double green, double blue, double alpha=1.0, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual HepRepAttValue * removeAttValue (std::string key)=0
virtual HepRepAttValue * getAttValue (std::string name)=0
virtual std::set
< HepRepAttValue * > getAttValuesFromNode ()=0
virtual HepRepAttValue * getAttValueFromNode (std::string lowerCaseName)=0
Detailed Description
HepRepAttribute interface.
Author
Mark Donszelmann
Definition at line 29 of file HepRepAttribute.h.
View newest version in sPHENIX GitHub at line 29 of file HepRepAttribute.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepAttribute::~HepRepAttribute () inline virtual
Destructor.
Definition at line 33 of file HepRepAttribute.h.
View newest version in sPHENIX GitHub at line 33 of file HepRepAttribute.h
Member Function Documentation
virtual void HEPREP::HepRepAttribute::addAttValue (HepRepAttValue * attValue) pure virtual
Adds an attValue.
Parameters
attValue to be added.
Implemented in cheprep::DefaultHepRepAttribute.
Referenced by G4HepRepSceneHandler::addAttributes(), G4HepRepSceneHandler::AddSolid(), G4HepRepSceneHandler::addTopLevelAttributes(), G4HepRepSceneHandler::getCalHitFaceType(), G4HepRepSceneHandler::getCalHitType(), G4HepRepSceneHandler::getEventType(), G4HepRepSceneHandler::getGeometryRootType(), G4HepRepSceneHandler::getHitType(), G4HepRepSceneHandler::getTrajectoryType(), and G4HepRepSceneHandler::setAttribute().
virtual void HEPREP::HepRepAttribute::addAttValue (std::string key, char * value, int showLabel = HepRepConstants::SHOW_NONE) pure virtual
Adds a char* attValue as a String. This call should be mapped to addAttValue(std::string, std::string, int); and necessary because C++ converts char* into bool and would thus call addAttValue(std::string, bool, int) for a call such as addAttValue("drawAs", "Cylinder", 0);
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implemented in cheprep::DefaultHepRepAttribute.
virtual void HEPREP::HepRepAttribute::addAttValue (std::string key, std::string value, int showLabel = HepRepConstants::SHOW_NONE) pure virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implemented in cheprep::DefaultHepRepAttribute.
virtual void HEPREP::HepRepAttribute::addAttValue (std::string key, int64 value, int showLabel = HepRepConstants::SHOW_NONE) pure virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implemented in cheprep::DefaultHepRepAttribute.
virtual void HEPREP::HepRepAttribute::addAttValue (std::string key, int value, int showLabel = HepRepConstants::SHOW_NONE) pure virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implemented in cheprep::DefaultHepRepAttribute.
virtual void HEPREP::HepRepAttribute::addAttValue (std::string key, double value, int showLabel = HepRepConstants::SHOW_NONE) pure virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implemented in cheprep::DefaultHepRepAttribute.
virtual void HEPREP::HepRepAttribute::addAttValue (std::string key, bool value, int showLabel = HepRepConstants::SHOW_NONE) pure virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implemented in cheprep::DefaultHepRepAttribute.
virtual void HEPREP::HepRepAttribute::addAttValue (std::string key, std::vector< double > value, int showLabel = HepRepConstants::SHOW_NONE) pure virtual
Adds a Color attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implemented in cheprep::DefaultHepRepAttribute.
virtual void HEPREP::HepRepAttribute::addAttValue (std::string key, double red, double green, double blue, double alpha = 1.0, int showLabel = HepRepConstants::SHOW_NONE) pure virtual
Adds a Color attValue.
Parameters
key name of attValue
red color
green color
blue color
alpha value
showLabel show this as label
Implemented in cheprep::DefaultHepRepAttribute.
virtual HepRepAttValue* HEPREP::HepRepAttribute::getAttValue (std::string name) pure virtual
Returns the attValue specified by name. This attValue is normally searched on the node itself and then on its type, moving up the typetree.
Parameters
name of attribute value.
Returns
attribute value.
Implemented in cheprep::DefaultHepRepInstance, cheprep::DefaultHepRepAttribute, cheprep::DefaultHepRepType, cheprep::DefaultHepRepDefinition, and cheprep::DefaultHepRepPoint.
Referenced by cheprep::DefaultHepRepPoint::getAttValue(), cheprep::DefaultHepRepInstance::getAttValue(), and G4HepRepSceneHandler::setAttribute().
virtual HepRepAttValue* HEPREP::HepRepAttribute::getAttValueFromNode (std::string lowerCaseName) pure virtual
Returns a named attribute value from this node.
Parameters
lowerCaseName name in all lowercase.
Returns
corresponding HepRepAttValue.
Implemented in cheprep::DefaultHepRepAttribute.
Referenced by cheprep::DefaultHepRepType::getAttValue(), G4HepRepSceneHandler::setAttribute(), and cheprep::XMLHepRepWriter::write().
virtual std::set<HepRepAttValue *> HEPREP::HepRepAttribute::getAttValuesFromNode () pure virtual
Returns a collection of all attribute values from this node.
Returns
collection of HepRepAttValues.
Implemented in cheprep::DefaultHepRepAttribute.
Referenced by cheprep::XMLHepRepWriter::write().
virtual HepRepAttValue* HEPREP::HepRepAttribute::removeAttValue (std::string key) pure virtual
Remove the attvalue named by key.
Parameters
key name of the attValue to be removed.
Returns
removed HepRepAttValue, or null if not removed.
Implemented in cheprep::DefaultHepRepAttribute.
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepAttribute.h