ECCE @ EIC Software: LXeRunAction Class Reference
LXeRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeRunAction.hh>
Public Member Functions
LXeRunAction ()
virtual ~LXeRunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
LXeRun * fRun
LXeHistoManager * fHistoManager
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 40 of file LXeRunAction.hh.
View newest version in sPHENIX GitHub at line 40 of file LXeRunAction.hh
Constructor & Destructor Documentation
LXeRunAction::LXeRunAction ()
Definition at line 37 of file LXeRunAction.cc.
View newest version in sPHENIX GitHub at line 37 of file LXeRunAction.cc
References fHistoManager.
LXeRunAction::~LXeRunAction () virtual
Definition at line 45 of file LXeRunAction.cc.
View newest version in sPHENIX GitHub at line 45 of file LXeRunAction.cc
References fHistoManager.
Member Function Documentation
void LXeRunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 59 of file LXeRunAction.cc.
View newest version in sPHENIX GitHub at line 59 of file LXeRunAction.cc
References G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::IsActive(), and G4VAnalysisManager::OpenFile().
void LXeRunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 69 of file LXeRunAction.cc.
View newest version in sPHENIX GitHub at line 69 of file LXeRunAction.cc
References G4VAnalysisManager::CloseFile(), LXeRun::EndOfRun(), fRun, G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::IsActive(), G4UserRunAction::isMaster, and G4VAnalysisManager::Write().
G4Run * LXeRunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 51 of file LXeRunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file LXeRunAction.cc
References fRun.
Member Data Documentation
LXeHistoManager* LXeRunAction::fHistoManager private
Definition at line 54 of file LXeRunAction.hh.
View newest version in sPHENIX GitHub at line 54 of file LXeRunAction.hh
Referenced by LXeRunAction(), and ~LXeRunAction().
LXeRun* LXeRunAction::fRun private
Definition at line 53 of file LXeRunAction.hh.
View newest version in sPHENIX GitHub at line 53 of file LXeRunAction.hh
Referenced by EndOfRunAction(), and GenerateRun().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeRunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeRunAction.cc