ECCE @ EIC Software: G4MonopoleFieldSetup Class Reference
G4MonopoleFieldSetup Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/include/G4MonopoleFieldSetup.hh>
Public Member Functions
G4MonopoleFieldSetup ()
~G4MonopoleFieldSetup ()
void InitialiseAll ()
void SetStepperAndChordFinder (G4int val)
void SetZMagFieldValue (G4double val)
void ConstructMagField ()
double GetZmagFieldValue () const
Private Member Functions
G4FieldManager * GetGlobalFieldManager ()
Private Attributes
G4FieldManager * fFieldManager
G4ChordFinder * fChordFinder
G4ChordFinder * fUsualChordFinder
G4ChordFinder * fMonopoleChordFinder
G4Mag_UsualEqRhs * fEquation
G4MonopoleEquation * fMonopoleEquation
G4MagneticField * fMagneticField
G4MagIntegratorStepper * fStepper
G4MagIntegratorStepper * fMonopoleStepper
G4double fMinStep
G4double fZmagFieldValue
G4MonopoleFieldMessenger * fMonopoleFieldMessenger
Detailed Description
Definition at line 62 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 62 of file G4MonopoleFieldSetup.hh
Constructor & Destructor Documentation
G4MonopoleFieldSetup::G4MonopoleFieldSetup ()
Definition at line 73 of file G4MonopoleFieldSetup.cc.
View newest version in sPHENIX GitHub at line 73 of file G4MonopoleFieldSetup.cc
References fFieldManager, fMonopoleFieldMessenger, and GetGlobalFieldManager().
G4MonopoleFieldSetup::~G4MonopoleFieldSetup ()
Definition at line 107 of file G4MonopoleFieldSetup.cc.
View newest version in sPHENIX GitHub at line 107 of file G4MonopoleFieldSetup.cc
References fMagneticField, fMonopoleChordFinder, fMonopoleFieldMessenger, fMonopoleStepper, fStepper, and fUsualChordFinder.
Member Function Documentation
void G4MonopoleFieldSetup::ConstructMagField ()
Definition at line 130 of file G4MonopoleFieldSetup.cc.
View newest version in sPHENIX GitHub at line 130 of file G4MonopoleFieldSetup.cc
References fFieldManager, fMagneticField, fZmagFieldValue, InitialiseAll(), and G4FieldManager::SetDetectorField().
Referenced by SetZMagFieldValue().
G4FieldManager * G4MonopoleFieldSetup::GetGlobalFieldManager () private
Definition at line 205 of file G4MonopoleFieldSetup.cc.
View newest version in sPHENIX GitHub at line 205 of file G4MonopoleFieldSetup.cc
References G4TransportationManager::GetFieldManager(), and G4TransportationManager::GetTransportationManager().
Referenced by G4MonopoleFieldSetup().
double G4MonopoleFieldSetup::GetZmagFieldValue () const inline
Definition at line 76 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 76 of file G4MonopoleFieldSetup.hh
References fZmagFieldValue.
void G4MonopoleFieldSetup::InitialiseAll ()
Definition at line 154 of file G4MonopoleFieldSetup.cc.
View newest version in sPHENIX GitHub at line 154 of file G4MonopoleFieldSetup.cc
References fEquation, fMagneticField, fMinStep, fMonopoleChordFinder, fMonopoleEquation, fMonopoleStepper, fStepper, fUsualChordFinder, mm, and SetStepperAndChordFinder().
Referenced by ConstructMagField().
void G4MonopoleFieldSetup::SetStepperAndChordFinder (G4int val)
Definition at line 173 of file G4MonopoleFieldSetup.cc.
View newest version in sPHENIX GitHub at line 173 of file G4MonopoleFieldSetup.cc
References fChordFinder, fFieldManager, fMagneticField, fMonopoleChordFinder, fUsualChordFinder, G4FieldManager::SetChordFinder(), and G4FieldManager::SetDetectorField().
Referenced by G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), and InitialiseAll().
void G4MonopoleFieldSetup::SetZMagFieldValue (G4double val)
Definition at line 120 of file G4MonopoleFieldSetup.cc.
View newest version in sPHENIX GitHub at line 120 of file G4MonopoleFieldSetup.cc
References ConstructMagField(), and fZmagFieldValue.
Referenced by G4MonopoleFieldMessenger::SetNewValue().
Member Data Documentation
G4ChordFinder* G4MonopoleFieldSetup::fChordFinder private
Definition at line 84 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 84 of file G4MonopoleFieldSetup.hh
Referenced by SetStepperAndChordFinder().
G4Mag_UsualEqRhs* G4MonopoleFieldSetup::fEquation private
Definition at line 87 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 87 of file G4MonopoleFieldSetup.hh
Referenced by InitialiseAll().
G4FieldManager* G4MonopoleFieldSetup::fFieldManager private
Definition at line 83 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 83 of file G4MonopoleFieldSetup.hh
Referenced by ConstructMagField(), G4MonopoleFieldSetup(), and SetStepperAndChordFinder().
G4MagneticField* G4MonopoleFieldSetup::fMagneticField private
Definition at line 90 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 90 of file G4MonopoleFieldSetup.hh
Referenced by ConstructMagField(), InitialiseAll(), SetStepperAndChordFinder(), and ~G4MonopoleFieldSetup().
G4double G4MonopoleFieldSetup::fMinStep private
Definition at line 95 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 95 of file G4MonopoleFieldSetup.hh
Referenced by InitialiseAll().
G4ChordFinder* G4MonopoleFieldSetup::fMonopoleChordFinder private
Definition at line 86 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MonopoleFieldSetup.hh
Referenced by InitialiseAll(), SetStepperAndChordFinder(), and ~G4MonopoleFieldSetup().
G4MonopoleEquation* G4MonopoleFieldSetup::fMonopoleEquation private
Definition at line 88 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 88 of file G4MonopoleFieldSetup.hh
Referenced by InitialiseAll().
G4MonopoleFieldMessenger* G4MonopoleFieldSetup::fMonopoleFieldMessenger private
Definition at line 101 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 101 of file G4MonopoleFieldSetup.hh
Referenced by G4MonopoleFieldSetup(), and ~G4MonopoleFieldSetup().
G4MagIntegratorStepper* G4MonopoleFieldSetup::fMonopoleStepper private
Definition at line 93 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 93 of file G4MonopoleFieldSetup.hh
Referenced by InitialiseAll(), and ~G4MonopoleFieldSetup().
G4MagIntegratorStepper* G4MonopoleFieldSetup::fStepper private
Definition at line 92 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 92 of file G4MonopoleFieldSetup.hh
Referenced by InitialiseAll(), and ~G4MonopoleFieldSetup().
G4ChordFinder* G4MonopoleFieldSetup::fUsualChordFinder private
Definition at line 85 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 85 of file G4MonopoleFieldSetup.hh
Referenced by InitialiseAll(), SetStepperAndChordFinder(), and ~G4MonopoleFieldSetup().
G4double G4MonopoleFieldSetup::fZmagFieldValue private
Definition at line 96 of file G4MonopoleFieldSetup.hh.
View newest version in sPHENIX GitHub at line 96 of file G4MonopoleFieldSetup.hh
Referenced by ConstructMagField(), GetZmagFieldValue(), and SetZMagFieldValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/include/G4MonopoleFieldSetup.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/src/G4MonopoleFieldSetup.cc