ECCE @ EIC Software: G4VLowEnergyModel Class Reference
G4VLowEnergyModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VLowEnergyModel.hh>
Public Member Functions
G4VLowEnergyModel (const G4String &name)
virtual ~G4VLowEnergyModel ()
virtual G4double TheValue (const G4DynamicParticle *particle, const G4Material *material)=0
virtual G4double TheValue (const G4ParticleDefinition *aParticle, const G4Material *material, G4double kineticEnergy)=0
virtual G4double HighEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const =0
virtual G4double LowEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const =0
virtual G4double HighEnergyLimit (const G4ParticleDefinition *aParticle) const =0
virtual G4double LowEnergyLimit (const G4ParticleDefinition *aParticle) const =0
virtual G4bool IsInCharge (const G4DynamicParticle *particle, const G4Material *material) const =0
virtual G4bool IsInCharge (const G4ParticleDefinition *aParticle, const G4Material *material) const =0
Private Member Functions
G4VLowEnergyModel & operator= (const G4VLowEnergyModel &right)
G4VLowEnergyModel (const G4VLowEnergyModel &)
Detailed Description
Definition at line 60 of file G4VLowEnergyModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VLowEnergyModel.hh
Constructor & Destructor Documentation
G4VLowEnergyModel::G4VLowEnergyModel (const G4String & name)
Definition at line 56 of file G4VLowEnergyModel.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VLowEnergyModel.cc
G4VLowEnergyModel::~G4VLowEnergyModel () virtual
Definition at line 61 of file G4VLowEnergyModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VLowEnergyModel.cc
G4VLowEnergyModel::G4VLowEnergyModel (const G4VLowEnergyModel &) private
Member Function Documentation
virtual G4double G4VLowEnergyModel::HighEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const pure virtual
Implemented in G4hIonEffChargeSquare, G4hNuclearStoppingModel, G4hParametrisedLossModel, G4hBetheBlochModel, G4IonChuFluctuationModel, G4IonYangFluctuationModel, and G4QAOLowEnergyLoss.
Referenced by G4hImpactIonisation::InitializeParametrisation().
virtual G4double G4VLowEnergyModel::HighEnergyLimit (const G4ParticleDefinition * aParticle) const pure virtual
Implemented in G4hNuclearStoppingModel, G4hIonEffChargeSquare, G4hParametrisedLossModel, G4hBetheBlochModel, G4IonChuFluctuationModel, G4IonYangFluctuationModel, and G4QAOLowEnergyLoss.
virtual G4bool G4VLowEnergyModel::IsInCharge (const G4DynamicParticle * particle, const G4Material * material) const pure virtual
Implemented in G4hNuclearStoppingModel, G4hIonEffChargeSquare, G4hParametrisedLossModel, G4hBetheBlochModel, G4IonChuFluctuationModel, G4IonYangFluctuationModel, and G4QAOLowEnergyLoss.
Referenced by G4hImpactIonisation::AntiProtonParametrisedDEDX().
virtual G4bool G4VLowEnergyModel::IsInCharge (const G4ParticleDefinition * aParticle, const G4Material * material) const pure virtual
Implemented in G4hNuclearStoppingModel, G4hIonEffChargeSquare, G4hParametrisedLossModel, G4hBetheBlochModel, G4IonChuFluctuationModel, G4IonYangFluctuationModel, and G4QAOLowEnergyLoss.
virtual G4double G4VLowEnergyModel::LowEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const pure virtual
Implemented in G4hNuclearStoppingModel, G4hIonEffChargeSquare, G4hParametrisedLossModel, G4hBetheBlochModel, G4IonChuFluctuationModel, G4IonYangFluctuationModel, and G4QAOLowEnergyLoss.
virtual G4double G4VLowEnergyModel::LowEnergyLimit (const G4ParticleDefinition * aParticle) const pure virtual
Implemented in G4hNuclearStoppingModel, G4hIonEffChargeSquare, G4hParametrisedLossModel, G4hBetheBlochModel, G4IonChuFluctuationModel, G4IonYangFluctuationModel, and G4QAOLowEnergyLoss.
G4VLowEnergyModel& G4VLowEnergyModel::operator= (const G4VLowEnergyModel & right) private
virtual G4double G4VLowEnergyModel::TheValue (const G4DynamicParticle * particle, const G4Material * material) pure virtual
Implemented in G4QAOLowEnergyLoss, G4hIonEffChargeSquare, G4hNuclearStoppingModel, G4hParametrisedLossModel, G4hBetheBlochModel, G4IonChuFluctuationModel, and G4IonYangFluctuationModel.
Referenced by G4hImpactIonisation::AlongStepDoIt(), G4hImpactIonisation::AntiProtonParametrisedDEDX(), G4hImpactIonisation::BuildLossTable(), G4hImpactIonisation::ComputeDEDX(), G4hImpactIonisation::GetMeanFreePath(), and G4hImpactIonisation::ProtonParametrisedDEDX().
virtual G4double G4VLowEnergyModel::TheValue (const G4ParticleDefinition * aParticle, const G4Material * material, G4double kineticEnergy) pure virtual
Implemented in G4QAOLowEnergyLoss, G4hIonEffChargeSquare, G4hNuclearStoppingModel, G4hParametrisedLossModel, G4hBetheBlochModel, G4IonChuFluctuationModel, and G4IonYangFluctuationModel.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VLowEnergyModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4VLowEnergyModel.cc