ECCE @ EIC Software: G4EnergySplitter Class Reference
G4EnergySplitter Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/scoring/include/G4EnergySplitter.hh>
Public Member Functions
G4EnergySplitter ()
virtual ~G4EnergySplitter ()
G4int SplitEnergyInVolumes (const G4Step *aStep)
void GetLastVoxelID (G4int &voxelID)
void GetFirstVoxelID (G4int &voxelID)
void GetVoxelID (G4int stepNo, G4int &voxelID)
void GetVoxelIDAndLength (G4int stepNo, G4int &voxelID, G4double &stepLength)
void GetLengthAndEnergyDeposited (G4int stepNo, G4int &voxelID, G4double &stepLength, G4double &energyLoss)
void GetLengthAndInitialEnergy (G4double &preStepEnergy, G4int stepNo, G4int &voxelID, G4double &stepLength, G4double &initialEnergy)
void SetNIterations (G4int niter)
G4Material * GetVoxelMaterial (G4int stepNo)
Private Member Functions
void GetStepLength (G4int stepNo, G4double &stepLength)
void GetPhantomParam (G4bool mustExist)
G4bool IsPhantomVolume (G4VPhysicalVolume *pv)
Private Attributes
G4EnergyLossForExtrapolator * theElossExt
G4int theNIterations
std::vector< G4double > theEnergies
G4PhantomParameterisation * thePhantomParam
Detailed Description
Definition at line 46 of file G4EnergySplitter.hh.
View newest version in sPHENIX GitHub at line 46 of file G4EnergySplitter.hh
Constructor & Destructor Documentation
G4EnergySplitter::G4EnergySplitter ()
Definition at line 43 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 43 of file G4EnergySplitter.cc
References theElossExt, theNIterations, and thePhantomParam.
G4EnergySplitter::~G4EnergySplitter () virtual
Definition at line 50 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 50 of file G4EnergySplitter.cc
References theElossExt.
Member Function Documentation
void G4EnergySplitter::GetFirstVoxelID (G4int & voxelID)
Definition at line 308 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 308 of file G4EnergySplitter.cc
References G4RegularNavigationHelper::GetStepLengths(), and G4RegularNavigationHelper::Instance().
void G4EnergySplitter::GetLastVoxelID (G4int & voxelID)
Definition at line 302 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 302 of file G4EnergySplitter.cc
References G4RegularNavigationHelper::GetStepLengths(), and G4RegularNavigationHelper::Instance().
void G4EnergySplitter::GetLengthAndEnergyDeposited (G4int stepNo, G4int & voxelID, G4double & stepLength, G4double & energyLoss) inline
Referenced by G4ScoreSplittingProcess::PostStepDoIt().
void G4EnergySplitter::GetLengthAndInitialEnergy (G4double & preStepEnergy, G4int stepNo, G4int & voxelID, G4double & stepLength, G4double & initialEnergy) inline
void G4EnergySplitter::GetPhantomParam (G4bool mustExist) private
Definition at line 261 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 261 of file G4EnergySplitter.cc
References FatalException, G4Exception(), G4PhysicalVolumeStore::GetInstance(), G4PVParameterised::GetParameterisation(), IsPhantomVolume(), and thePhantomParam.
Referenced by SplitEnergyInVolumes().
void G4EnergySplitter::GetStepLength (G4int stepNo, G4double & stepLength) private
Definition at line 330 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 330 of file G4EnergySplitter.cc
References G4RegularNavigationHelper::GetStepLengths(), and G4RegularNavigationHelper::Instance().
void G4EnergySplitter::GetVoxelID (G4int stepNo, G4int & voxelID)
Definition at line 314 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 314 of file G4EnergySplitter.cc
References G4UIcommand::ConvertToString(), FatalErrorInArgument, G4Exception(), G4RegularNavigationHelper::GetStepLengths(), and G4RegularNavigationHelper::Instance().
Referenced by G4ScoreSplittingProcess::PostStepDoIt().
void G4EnergySplitter::GetVoxelIDAndLength (G4int stepNo, G4int & voxelID, G4double & stepLength) inline
G4Material* G4EnergySplitter::GetVoxelMaterial (G4int stepNo) inline
Referenced by G4ScoreSplittingProcess::PostStepDoIt().
G4bool G4EnergySplitter::IsPhantomVolume (G4VPhysicalVolume * pv) private
Definition at line 285 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 285 of file G4EnergySplitter.cc
References FALSE, G4VPhysicalVolume::GetRegularStructureId(), G4VPhysicalVolume::GetReplicationData(), kParameterised, kReplica, offset, TRUE, and width.
Referenced by GetPhantomParam().
void G4EnergySplitter::SetNIterations (G4int niter) inline
G4int G4EnergySplitter::SplitEnergyInVolumes (const G4Step * aStep)
Definition at line 55 of file G4EnergySplitter.cc.
View newest version in sPHENIX GitHub at line 55 of file G4EnergySplitter.cc
References edep, FALSE, G4cout, G4endl, G4EmCalculator::GetDEDX(), G4Track::GetDefinition(), G4StepPoint::GetKineticEnergy(), G4StepPoint::GetMaterial(), G4PhantomParameterisation::GetMaterial(), G4Material::GetName(), G4ParticleDefinition::GetPDGCharge(), GetPhantomParam(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4RegularNavigationHelper::GetStepLengths(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), G4RegularNavigationHelper::Instance(), part, second, theElossExt, theEnergies, theNIterations, thePhantomParam, TRUE, and G4EnergyLossForExtrapolator::TrueStepLength().
Referenced by G4ScoreSplittingProcess::PostStepDoIt().
Member Data Documentation
G4EnergyLossForExtrapolator* G4EnergySplitter::theElossExt private
Definition at line 71 of file G4EnergySplitter.hh.
View newest version in sPHENIX GitHub at line 71 of file G4EnergySplitter.hh
Referenced by G4EnergySplitter(), SplitEnergyInVolumes(), and ~G4EnergySplitter().
std::vector<G4double> G4EnergySplitter::theEnergies private
Definition at line 75 of file G4EnergySplitter.hh.
View newest version in sPHENIX GitHub at line 75 of file G4EnergySplitter.hh
Referenced by SplitEnergyInVolumes().
G4int G4EnergySplitter::theNIterations private
Definition at line 73 of file G4EnergySplitter.hh.
View newest version in sPHENIX GitHub at line 73 of file G4EnergySplitter.hh
Referenced by G4EnergySplitter(), and SplitEnergyInVolumes().
G4PhantomParameterisation* G4EnergySplitter::thePhantomParam private
Definition at line 77 of file G4EnergySplitter.hh.
View newest version in sPHENIX GitHub at line 77 of file G4EnergySplitter.hh
Referenced by G4EnergySplitter(), GetPhantomParam(), and SplitEnergyInVolumes().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/scoring/include/G4EnergySplitter.hh
geant4/tree/geant4-10.6-release/source/processes/scoring/src/G4EnergySplitter.cc