ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/global/pymodG4global.cc File Reference
pymodG4global.cc File Reference
#include <boost/python.hpp>
Functions
void export_globals ()
void export_geomdefs ()
void export_G4StateManager ()
void export_G4ApplicationState ()
void export_G4String ()
void export_G4ThreeVector ()
void export_G4RotationMatrix ()
void export_G4Transform3D ()
void export_G4UnitsTable ()
void export_Randomize ()
void export_RandomEngines ()
void export_G4RandomDirection ()
void export_G4UserLimits ()
void export_G4Timer ()
void export_G4Version ()
void export_G4Exception ()
void export_G4ExceptionHandler ()
void export_G4ExceptionSeverity ()
void export_G4TwoVector ()
BOOST_PYTHON_MODULE (G4global)
Function Documentation
BOOST_PYTHON_MODULE (G4global)
Definition at line 59 of file pymodG4global.cc.
View newest version in sPHENIX GitHub at line 59 of file pymodG4global.cc
References export_G4ApplicationState(), export_G4Exception(), export_G4ExceptionHandler(), export_G4ExceptionSeverity(), export_G4RandomDirection(), export_G4RotationMatrix(), export_G4StateManager(), export_G4String(), export_G4ThreeVector(), export_G4Timer(), export_G4Transform3D(), export_G4TwoVector(), export_G4UnitsTable(), export_G4UserLimits(), export_G4Version(), export_geomdefs(), export_globals(), export_RandomEngines(), and export_Randomize().
void export_G4ApplicationState ()
Definition at line 41 of file pyG4ApplicationState.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4ApplicationState.cc
References G4State_Abort, G4State_EventProc, G4State_GeomClosed, G4State_Idle, G4State_Init, G4State_PreInit, and G4State_Quit.
Referenced by BOOST_PYTHON_MODULE().
void export_G4Exception ()
Definition at line 110 of file pyG4Exception.cc.
View newest version in sPHENIX GitHub at line 110 of file pyG4Exception.cc
References pyG4Exception::f2_G4Exception().
Referenced by BOOST_PYTHON_MODULE().
void export_G4ExceptionHandler ()
Definition at line 104 of file pyG4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 104 of file pyG4ExceptionHandler.cc
Referenced by BOOST_PYTHON_MODULE().
void export_G4ExceptionSeverity ()
Definition at line 41 of file pyG4ExceptionSeverity.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4ExceptionSeverity.cc
References EventMustBeAborted, FatalErrorInArgument, FatalException, JustWarning, and RunMustBeAborted.
Referenced by BOOST_PYTHON_MODULE().
void export_G4RandomDirection ()
Definition at line 51 of file pyG4RandomDirection.cc.
View newest version in sPHENIX GitHub at line 51 of file pyG4RandomDirection.cc
References pyG4RandomDirection::G4RandomDirection_1, and pyG4RandomDirection::G4RandomDirection_2.
Referenced by BOOST_PYTHON_MODULE().
void export_G4RotationMatrix ()
Definition at line 53 of file pyG4RotationMatrix.cc.
View newest version in sPHENIX GitHub at line 53 of file pyG4RotationMatrix.cc
References CLHEP::HepRotation::axis(), CLHEP::HepRotation::colX(), CLHEP::HepRotation::colY(), CLHEP::HepRotation::colZ(), CLHEP::HepRotation::delta(), pyG4RotationMatrix::f1_rotate, pyG4RotationMatrix::f2_rotate, CLHEP::HepRotation::getAxis(), CLHEP::HepRotation::getDelta(), CLHEP::HepRotation::getPhi(), CLHEP::HepRotation::getPsi(), CLHEP::HepRotation::getTheta(), CLHEP::HepRotation::IDENTITY, CLHEP::HepRotation::inverse(), CLHEP::HepRotation::invert(), CLHEP::HepRotation::isIdentity(), CLHEP::HepRotation::phi(), CLHEP::HepRotation::phiX(), CLHEP::HepRotation::phiY(), CLHEP::HepRotation::phiZ(), CLHEP::HepRotation::psi(), CLHEP::HepRotation::rotateAxes(), CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::HepRotation::rotateZ(), CLHEP::HepRotation::rowX(), CLHEP::HepRotation::rowY(), CLHEP::HepRotation::rowZ(), CLHEP::HepRotation::setAxis(), CLHEP::HepRotation::setDelta(), CLHEP::HepRotation::setPhi(), CLHEP::HepRotation::setPsi(), CLHEP::HepRotation::setTheta(), CLHEP::HepRotation::theta(), CLHEP::HepRotation::thetaX(), CLHEP::HepRotation::thetaY(), CLHEP::HepRotation::thetaZ(), CLHEP::HepRotation::xx(), CLHEP::HepRotation::xy(), CLHEP::HepRotation::xz(), CLHEP::HepRotation::yx(), CLHEP::HepRotation::yy(), CLHEP::HepRotation::yz(), CLHEP::HepRotation::zx(), CLHEP::HepRotation::zy(), and CLHEP::HepRotation::zz().
Referenced by BOOST_PYTHON_MODULE().
void export_G4StateManager ()
Definition at line 39 of file pyG4StateManager.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4StateManager.cc
References G4StateManager::GetCurrentState(), G4StateManager::GetPreviousState(), G4StateManager::GetStateManager(), and G4StateManager::GetStateString().
Referenced by BOOST_PYTHON_MODULE().
void export_G4String ()
Definition at line 47 of file pyG4String.cc.
View newest version in sPHENIX GitHub at line 47 of file pyG4String.cc
Referenced by BOOST_PYTHON_MODULE().
void export_G4ThreeVector ()
Definition at line 98 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 98 of file pyG4ThreeVector.cc
References CLHEP::HepRotation::compare(), Acts::VectorHelpers::cross(), deltaR(), pyG4ThreeVector::f1_angle, pyG4ThreeVector::f1_azimAngle, pyG4ThreeVector::f1_cos2Theta, pyG4ThreeVector::f1_cosTheta, pyG4ThreeVector::f1_eta, pyG4ThreeVector::f1_perp2, pyG4ThreeVector::f1_perpPart, pyG4ThreeVector::f1_polarAngle, pyG4ThreeVector::f1_project, pyG4ThreeVector::f1_rapidity, pyG4RotationMatrix::f1_rotate, pyG4ThreeVector::f1_theta, pyG4ThreeVector::f2_angle, pyG4ThreeVector::f2_azimAngle, pyG4ThreeVector::f2_cos2Theta, pyG4ThreeVector::f2_cosTheta, pyG4ThreeVector::f2_eta, pyG4ThreeVector::f2_perp2, pyG4ThreeVector::f2_perpPart, pyG4ThreeVector::f2_polarAngle, pyG4ThreeVector::f2_project, pyG4ThreeVector::f2_rapidity, pyG4RotationMatrix::f2_rotate, pyG4ThreeVector::f2_theta, pyG4ThreeVector::f5_rotate, CLHEP::HepRotation::getPhi(), CLHEP::HepRotation::getTheta(), CLHEP::HepRotation::getTolerance(), CLHEP::HepRotation::howNear(), CLHEP::HepRotation::isNear(), CLHEP::HepRotation::phi(), r, CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::HepRotation::rotateZ(), CLHEP::HepRotation::set(), CLHEP::HepRotation::setPhi(), CLHEP::HepRotation::setTheta(), CLHEP::HepRotation::setTolerance(), CLHEP::HepRotation::transform(), x, y, and z.
Referenced by BOOST_PYTHON_MODULE().
void export_G4Timer ()
Definition at line 39 of file pyG4Timer.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4Timer.cc
References G4Timer::GetRealElapsed(), G4Timer::GetSystemElapsed(), G4Timer::GetUserElapsed(), G4Timer::IsValid(), G4Timer::Start(), and G4Timer::Stop().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Transform3D ()
Definition at line 43 of file pyG4Transform3D.cc.
View newest version in sPHENIX GitHub at line 43 of file pyG4Transform3D.cc
References dx, dy, dz, CLHEP::HepRotation::inverse(), CLHEP::HepRotation::xx(), CLHEP::HepRotation::xy(), CLHEP::HepRotation::xz(), CLHEP::HepRotation::yx(), CLHEP::HepRotation::yy(), CLHEP::HepRotation::yz(), CLHEP::HepRotation::zx(), CLHEP::HepRotation::zy(), and CLHEP::HepRotation::zz().
Referenced by BOOST_PYTHON_MODULE().
void export_G4TwoVector ()
Definition at line 56 of file pyG4TwoVector.cc.
View newest version in sPHENIX GitHub at line 56 of file pyG4TwoVector.cc
References angle, CLHEP::HepRotation::howNear(), CLHEP::HepRotation::isNear(), CLHEP::HepRotation::phi(), r, CLHEP::HepRotation::rotate(), CLHEP::HepRotation::set(), CLHEP::HepRotation::setPhi(), x, and y.
Referenced by BOOST_PYTHON_MODULE().
void export_G4UnitsTable ()
Definition at line 40 of file pyG4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4UnitsTable.cc
References G4UnitDefinition::BuildUnitsTable(), G4UnitDefinition::GetCategory(), G4BestUnit::GetCategory(), G4BestUnit::GetIndexOfCategory(), G4UnitDefinition::GetName(), G4UnitsCategory::GetName(), G4UnitsCategory::GetNameMxLen(), G4UnitsCategory::GetSymbMxLen(), G4UnitDefinition::GetSymbol(), G4UnitsCategory::GetUnitsList(), G4UnitDefinition::GetUnitsTable(), G4UnitDefinition::GetValue(), G4UnitDefinition::GetValueOf(), G4UnitsCategory::PrintCategory(), G4UnitDefinition::PrintDefinition(), G4UnitDefinition::PrintUnitsTable(), G4UnitsCategory::UpdateNameMxLen(), and G4UnitsCategory::UpdateSymbMxLen().
Referenced by BOOST_PYTHON_MODULE().
void export_G4UserLimits ()
Definition at line 42 of file pyG4UserLimits.cc.
View newest version in sPHENIX GitHub at line 42 of file pyG4UserLimits.cc
References G4UserLimits::GetType(), G4UserLimits::GetUserMaxTime(), G4UserLimits::GetUserMaxTrackLength(), G4UserLimits::GetUserMinEkine(), G4UserLimits::GetUserMinRange(), init(), G4UserLimits::SetMaxAllowedStep(), G4UserLimits::SetType(), G4UserLimits::SetUserMaxTime(), G4UserLimits::SetUserMaxTrackLength(), G4UserLimits::SetUserMinEkine(), and G4UserLimits::SetUserMinRange().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Version ()
Definition at line 39 of file pyG4Version.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4Version.cc
References G4Date, G4Version, and G4VERSION_NUMBER.
Referenced by BOOST_PYTHON_MODULE().
void export_geomdefs ()
Definition at line 39 of file pygeomdefs.cc.
View newest version in sPHENIX GitHub at line 39 of file pygeomdefs.cc
References kInside, kNormal, kOutside, kParameterised, kPhi, kRadial3D, kReplica, kRho, kSurface, kUndefined, kXAxis, kYAxis, and kZAxis.
Referenced by BOOST_PYTHON_MODULE().
void export_globals ()
Definition at line 76 of file pyglobals.cc.
View newest version in sPHENIX GitHub at line 76 of file pyglobals.cc
References pyglobals::ResetG4PyCoutDestination(), and pyglobals::SetG4PyCoutDestination().
Referenced by BOOST_PYTHON_MODULE().
void export_RandomEngines ()
Definition at line 44 of file pyRandomEngines.cc.
View newest version in sPHENIX GitHub at line 44 of file pyRandomEngines.cc
Referenced by BOOST_PYTHON_MODULE().
void export_Randomize ()
Definition at line 176 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 176 of file pyRandomize.cc
References pyRandomize::f1_RandBit_shootBit(), pyRandomize::f1_RandGaussQ_shoot(), pyRandomize::f1_restoreEngineStatus(), pyRandomize::f1_saveEngineStatus(), pyRandomize::f1_setTheSeed(), pyRandomize::f1_setTheSeeds(), pyRandomize::f2_RandGaussQ_shoot(), pyRandomize::f2_restoreEngineStatus(), pyRandomize::f2_saveEngineStatus(), pyRandomize::f2_setTheSeed(), pyRandomize::f2_setTheSeeds(), pyRandomize::f_G4UniformRand(), pyRandomize::f_getTheSeeds(), and pyRandomize::f_getTheTableSeeds().
Referenced by BOOST_PYTHON_MODULE().