ECCE @ EIC Software: G4ITReactionPerTrack Class Reference
G4ITReactionPerTrack Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITReaction.hh>
Public Member Functions
virtual ~G4ITReactionPerTrack ()
void AddReaction (G4ITReactionPtr reaction)
void AddIterator (G4ITReactionPerTrackMap::iterator it)
bool RemoveThisReaction (G4ITReactionList::iterator it)
void RemoveMe ()
G4ITReactionList & GetReactionList ()
std::list
< G4ITReactionPerTrackMap::iterator > & GetListOfIterators ()
Static Public Member Functions
static G4ITReactionPerTrackPtr New ()
Protected Attributes
G4ITReactionList fReactions
std::list
< G4ITReactionPerTrackMap::iterator > fReactionSetIt
Private Member Functions
G4ITReactionPerTrack ()
Detailed Description
Definition at line 120 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ITReaction.hh
Constructor & Destructor Documentation
G4ITReactionPerTrack::G4ITReactionPerTrack () inline private
Definition at line 122 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ITReaction.hh
Referenced by New().
virtual G4ITReactionPerTrack::~G4ITReactionPerTrack () inline virtual
Definition at line 129 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ITReaction.hh
References fReactions.
Member Function Documentation
void G4ITReactionPerTrack::AddIterator (G4ITReactionPerTrackMap::iterator it) inline
Definition at line 141 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ITReaction.hh
References fReactionSetIt.
void G4ITReactionPerTrack::AddReaction (G4ITReactionPtr reaction) inline
Definition at line 134 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ITReaction.hh
References fReactions, and it.
std::list<G4ITReactionPerTrackMap::iterator>& G4ITReactionPerTrack::GetListOfIterators () inline
Definition at line 168 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ITReaction.hh
References fReactionSetIt.
G4ITReactionList& G4ITReactionPerTrack::GetReactionList () inline
Definition at line 163 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 163 of file G4ITReaction.hh
References fReactions.
static G4ITReactionPerTrackPtr G4ITReactionPerTrack::New () inline static
Definition at line 124 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ITReaction.hh
References G4ITReactionPerTrack().
Referenced by G4ITReactionSet::AddReaction().
void G4ITReactionPerTrack::RemoveMe () inline
Definition at line 147 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ITReaction.hh
References fReactions, fReactionSetIt, and it.
bool G4ITReactionPerTrack::RemoveThisReaction (G4ITReactionList::iterator it)
Definition at line 106 of file G4ITReaction.cc.
View newest version in sPHENIX GitHub at line 106 of file G4ITReaction.cc
References fReactions, G4ITReactionSet::Instance(), and G4ITReactionSet::RemoveReactionPerTrack().
Member Data Documentation
G4ITReactionList G4ITReactionPerTrack::fReactions protected
Definition at line 174 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ITReaction.hh
Referenced by AddReaction(), GetReactionList(), RemoveMe(), RemoveThisReaction(), and ~G4ITReactionPerTrack().
std::list<G4ITReactionPerTrackMap::iterator> G4ITReactionPerTrack::fReactionSetIt protected
Definition at line 175 of file G4ITReaction.hh.
View newest version in sPHENIX GitHub at line 175 of file G4ITReaction.hh
Referenced by AddIterator(), GetListOfIterators(), and RemoveMe().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITReaction.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITReaction.cc