ECCE @ EIC Software: G4RegionStore Class Reference
G4RegionStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4RegionStore.hh>
Public Member Functions
G4bool IsModified () const
void ResetRegionModified ()
void UpdateMaterialList (G4VPhysicalVolume *currentWorld=0)
G4Region * GetRegion (const G4String &name, G4bool verbose=true) const
G4Region * FindOrCreateRegion (const G4String &name)
void SetWorldVolume ()
Static Public Member Functions
static void Register (G4Region *pRegion)
static void DeRegister (G4Region *pRegion)
static G4RegionStore * GetInstance ()
static void SetNotifier (G4VStoreNotifier *pNotifier)
static void Clean ()
Protected Member Functions
G4RegionStore ()
virtual ~G4RegionStore ()
Static Private Attributes
static G4RegionStore * fgInstance = nullptr
static G4ThreadLocal
G4VStoreNotifier * fgNotifier = nullptr
static G4ThreadLocal G4bool locked = false
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 59 of file G4RegionStore.hh.
View newest version in sPHENIX GitHub at line 59 of file G4RegionStore.hh
Constructor & Destructor Documentation
G4RegionStore::G4RegionStore () protected
Definition at line 52 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 52 of file G4RegionStore.cc
G4RegionStore::~G4RegionStore () protected virtual
Definition at line 62 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 62 of file G4RegionStore.cc
References Clean(), and G4Region::Clean().
Member Function Documentation
void G4RegionStore::Clean () static
Definition at line 72 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 72 of file G4RegionStore.cc
References fgNotifier, G4cout, G4endl, GetInstance(), G4GeometryManager::IsGeometryClosed(), locked, G4VNotifier::NotifyDeRegistration(), and pos().
Referenced by ~G4RegionStore().
void G4RegionStore::DeRegister (G4Region * pRegion) static
Definition at line 136 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 136 of file G4RegionStore.cc
References fgNotifier, GetInstance(), locked, and G4VNotifier::NotifyDeRegistration().
Referenced by G4Region::~G4Region().
G4Region * G4RegionStore::FindOrCreateRegion (const G4String & name)
Definition at line 235 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 235 of file G4RegionStore.cc
References GetRegion().
Referenced by SplitProcess::SplitProcess().
G4RegionStore * G4RegionStore::GetInstance (void) static
Definition at line 156 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 156 of file G4RegionStore.cc
References fgInstance.
Referenced by G4EmBiasingManager::ActivateForcedInteraction(), G4EmModelActivator::ActivatePAI(), G4EmBiasingManager::ActivateSecondaryBiasing(), G4VEnergyLossProcess::ActivateSubCutoff(), G4ElectronCapture::BuildPhysicsTable(), G4LowECapture::BuildPhysicsTable(), ExTGRCRegionCutsMgr::BuildProductionCuts(), G4RunManagerKernel::CheckRegions(), Clean(), PHG4PhenixDetector::Construct(), RE01DetectorConstruction::Construct(), PHG4RICHDetector::ConstructMe(), Par01ParallelWorldForPion::ConstructSD(), Par01DetectorConstruction::ConstructSDandField(), PHG4TpcDetector::ConstructTpcGasVolume(), G4TheRayTracer::CreateBitMap(), G4EmExtraParameters::DefineRegParamForLoss(), DeRegister(), G4RunManagerKernel::DumpRegion(), RE06RunAction::EndOfRunAction(), G4GDMLParser::ExportRegions(), G4EmCalculator::FindCouple(), RE06SteppingVerbose::FindRegion(), G4EmConfigurator::FindRegion(), G4EmCalculator::FindRegion(), G4ProductionCutsTable::G4ProductionCutsTable(), G4Region::G4Region(), G4RunManagerKernel::G4RunManagerKernel(), G4VUserPhysicsList::GetCutValue(), GetRegion(), G4PAIPhotModel::Initialise(), G4PAIModel::Initialise(), G4EmModelManager::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), TrackingAction::Initialize(), RE06SteppingVerbose::InitializeTimers(), IsModified(), Register(), G4RunManager::ReinitializeGeometry(), RE06SteppingVerbose::Report(), ResetRegionModified(), STCyclotronPhysicsList::SetCutFoil(), STCyclotronPhysicsList::SetCutTarget(), G4VUserPhysicsList::SetCutValue(), G4VAtomDeexcitation::SetDeexcitationActiveRegion(), IORTPhysicsList::SetDetectorCut(), SetNotifier(), G4VUserPhysicsList::SetParticleCuts(), G4MaterialScanner::SetRegionName(), CexmcSetup::SetupSpecialVolumes(), SetWorldVolume(), G4GlobalFastSimulationManager::ShowSetup(), SplitProcess::SplitProcess(), GammaRayTelDetectorConstruction::UpdateGeometry(), G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster(), UpdateMaterialList(), G4RunManagerKernel::UpdateRegion(), and G4Region::~G4Region().
G4Region * G4RegionStore::GetRegion (const G4String & name, G4bool verbose = true) const
Definition at line 211 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 211 of file G4RegionStore.cc
References G4endl, G4Exception(), GetInstance(), JustWarning, and message().
Referenced by G4EmBiasingManager::ActivateForcedInteraction(), G4EmModelActivator::ActivatePAI(), G4EmBiasingManager::ActivateSecondaryBiasing(), G4VEnergyLossProcess::ActivateSubCutoff(), G4LowECapture::BuildPhysicsTable(), ExTGRCRegionCutsMgr::BuildProductionCuts(), G4ProductionCutsTable::CheckMaterialCutsCoupleInfo(), PHG4RICHDetector::ConstructMe(), Par01ParallelWorldForPion::ConstructSD(), Par01DetectorConstruction::ConstructSDandField(), PHG4TpcDetector::ConstructTpcGasVolume(), G4EmExtraParameters::DefineRegParamForLoss(), G4RunManagerKernel::DumpRegion(), RE06RunAction::EndOfRunAction(), FindOrCreateRegion(), G4EmConfigurator::FindRegion(), G4EmCalculator::FindRegion(), G4Region::G4Region(), G4RunManagerKernel::G4RunManagerKernel(), G4VUserPhysicsList::GetCutValue(), G4EmModelManager::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), TrackingAction::Initialize(), STCyclotronPhysicsList::SetCutFoil(), STCyclotronPhysicsList::SetCutTarget(), G4VUserPhysicsList::SetCutValue(), IORTPhysicsList::SetDetectorCut(), G4VUserPhysicsList::SetParticleCuts(), and G4MaterialScanner::SetRegionName().
G4bool G4RegionStore::IsModified () const
Definition at line 171 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 171 of file G4RegionStore.cc
References GetInstance().
void G4RegionStore::Register (G4Region * pRegion) static
Definition at line 126 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 126 of file G4RegionStore.cc
References fgNotifier, GetInstance(), and G4VNotifier::NotifyRegistration().
Referenced by G4Region::G4Region().
void G4RegionStore::ResetRegionModified ()
Definition at line 185 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 185 of file G4RegionStore.cc
References GetInstance().
void G4RegionStore::SetNotifier (G4VStoreNotifier * pNotifier) static
Definition at line 116 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 116 of file G4RegionStore.cc
References fgNotifier, and GetInstance().
void G4RegionStore::SetWorldVolume ()
Definition at line 250 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 250 of file G4RegionStore.cc
References G4PhysicalVolumeStore::GetInstance(), GetInstance(), and G4VPhysicalVolume::GetMotherLogical().
void G4RegionStore::UpdateMaterialList (G4VPhysicalVolume * currentWorld = 0)
Definition at line 197 of file G4RegionStore.cc.
View newest version in sPHENIX GitHub at line 197 of file G4RegionStore.cc
References GetInstance().
Referenced by G4TheRayTracer::CreateBitMap(), GammaRayTelDetectorConstruction::UpdateGeometry(), and G4RunManagerKernel::UpdateRegion().
Member Data Documentation
G4RegionStore * G4RegionStore::fgInstance = nullptr static private
Definition at line 110 of file G4RegionStore.hh.
View newest version in sPHENIX GitHub at line 110 of file G4RegionStore.hh
Referenced by GetInstance().
G4ThreadLocal G4VStoreNotifier * G4RegionStore::fgNotifier = nullptr static private
Definition at line 111 of file G4RegionStore.hh.
View newest version in sPHENIX GitHub at line 111 of file G4RegionStore.hh
Referenced by Clean(), DeRegister(), Register(), and SetNotifier().
G4ThreadLocal G4bool G4RegionStore::locked = false static private
Definition at line 112 of file G4RegionStore.hh.
View newest version in sPHENIX GitHub at line 112 of file G4RegionStore.hh
Referenced by Clean(), and DeRegister().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4RegionStore.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4RegionStore.cc