ECCE @ EIC Software: G4BetheBlochIonGasModel Class Reference
G4BetheBlochIonGasModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4BetheBlochIonGasModel.hh>
Public Member Functions
G4BetheBlochIonGasModel (const G4ParticleDefinition *p=0, const G4String &nam="BetheBlochGasIon")
virtual ~G4BetheBlochIonGasModel ()
virtual G4double ChargeSquareRatio (const G4Track &track) final
virtual G4double GetParticleCharge (const G4ParticleDefinition *p, const G4Material *mat, G4double kineticEnergy) final
Public Member Functions inherited from G4BetheBlochModel
G4BetheBlochModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="BetheBloch")
virtual ~G4BetheBlochModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *couple) override
virtual G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy) override
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *p, const G4Material *mat, G4double kineticEnergy) override
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *couple, const G4DynamicParticle *dp, G4double &eloss, G4double &, G4double length) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual void StartTracking (G4Track *)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
G4BetheBlochIonGasModel & operator= (const G4BetheBlochIonGasModel &right)=delete
G4BetheBlochIonGasModel (const G4BetheBlochIonGasModel &)=delete
Private Attributes
G4double currentCharge
Additional Inherited Members
Protected Member Functions inherited from G4BetheBlochModel
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kinEnergy) override
G4double GetChargeSquareRatio () const
void SetChargeSquareRatio (G4double val)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 54 of file G4BetheBlochIonGasModel.hh.
View newest version in sPHENIX GitHub at line 54 of file G4BetheBlochIonGasModel.hh
Constructor & Destructor Documentation
G4BetheBlochIonGasModel::G4BetheBlochIonGasModel (const G4ParticleDefinition * p = 0, const G4String & nam = "BetheBlochGasIon") explicit
Definition at line 55 of file G4BetheBlochIonGasModel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4BetheBlochIonGasModel.cc
G4BetheBlochIonGasModel::~G4BetheBlochIonGasModel () virtual
Definition at line 61 of file G4BetheBlochIonGasModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4BetheBlochIonGasModel.cc
G4BetheBlochIonGasModel::G4BetheBlochIonGasModel (const G4BetheBlochIonGasModel &) private delete
Member Function Documentation
G4double G4BetheBlochIonGasModel::ChargeSquareRatio (const G4Track & track) final virtual
Reimplemented from G4VEmModel.
Definition at line 66 of file G4BetheBlochIonGasModel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4BetheBlochIonGasModel.cc
References currentCharge, eplus, G4DynamicParticle::GetCharge(), G4Track::GetDynamicParticle(), and G4BetheBlochModel::SetChargeSquareRatio().
G4double G4BetheBlochIonGasModel::GetParticleCharge (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) final virtual
Reimplemented from G4BetheBlochModel.
Definition at line 76 of file G4BetheBlochIonGasModel.cc.
View newest version in sPHENIX GitHub at line 76 of file G4BetheBlochIonGasModel.cc
References currentCharge, and eplus.
G4BetheBlochIonGasModel& G4BetheBlochIonGasModel::operator= (const G4BetheBlochIonGasModel & right) private delete
Member Data Documentation
G4double G4BetheBlochIonGasModel::currentCharge private
Definition at line 77 of file G4BetheBlochIonGasModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4BetheBlochIonGasModel.hh
Referenced by ChargeSquareRatio(), and GetParticleCharge().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4BetheBlochIonGasModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4BetheBlochIonGasModel.cc