ECCE @ EIC Software: G4AdjointCSManager Class Reference
G4AdjointCSManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointCSManager.hh>
Public Member Functions
~G4AdjointCSManager ()
G4int GetNbProcesses ()
size_t RegisterEmAdjointModel (G4VEmAdjointModel *)
void RegisterEmProcess (G4VEmProcess *aProcess, G4ParticleDefinition *aPartDef)
void RegisterEnergyLossProcess (G4VEnergyLossProcess *aProcess, G4ParticleDefinition *aPartDef)
void RegisterAdjointParticle (G4ParticleDefinition *aPartDef)
void BuildCrossSectionMatrices ()
void BuildTotalSigmaTables ()
G4double GetTotalAdjointCS (G4ParticleDefinition *aPartDef, G4double Ekin, const G4MaterialCutsCouple *aCouple)
G4double GetTotalForwardCS (G4ParticleDefinition *aPartDef, G4double Ekin, const G4MaterialCutsCouple *aCouple)
G4double GetAdjointSigma (G4double Ekin_nuc, size_t index_model, G4bool is_scat_proj_to_proj, const G4MaterialCutsCouple *aCouple)
void GetEminForTotalCS (G4ParticleDefinition *aPartDef, const G4MaterialCutsCouple *aCouple, G4double &emin_adj, G4double &emin_fwd)
void GetMaxFwdTotalCS (G4ParticleDefinition *aPartDef, const G4MaterialCutsCouple *aCouple, G4double &e_sigma_max, G4double &sigma_max)
void GetMaxAdjTotalCS (G4ParticleDefinition *aPartDef, const G4MaterialCutsCouple *aCouple, G4double &e_sigma_max, G4double &sigma_max)
G4double GetCrossSectionCorrection (G4ParticleDefinition *aPartDef, G4double PreStepEkin, const G4MaterialCutsCouple *aCouple, G4bool &fwd_is_used, G4double &fwd_TotCS)
void SetFwdCrossSectionMode (G4bool aBool)
G4double GetContinuousWeightCorrection (G4ParticleDefinition *aPartDef, G4double PreStepEkin, G4double AfterStepEkin, const G4MaterialCutsCouple *aCouple, G4double step_length)
G4double GetPostStepWeightCorrection ()
G4double ComputeAdjointCS (G4Material *aMaterial, G4VEmAdjointModel *aModel, G4double PrimEnergy, G4double Tcut, G4bool IsScatProjToProjCase, std::vector< G4double > &AdjointCS_for_each_element)
G4Element * SampleElementFromCSMatrices (G4Material *aMaterial, G4VEmAdjointModel *aModel, G4double PrimEnergy, G4double Tcut, G4bool IsScatProjToProjCase)
G4double ComputeTotalAdjointCS (const G4MaterialCutsCouple *aMatCutCouple, G4ParticleDefinition *aPart, G4double PrimEnergy)
G4ParticleDefinition * GetAdjointParticleEquivalent (G4ParticleDefinition *theFwdPartDef)
G4ParticleDefinition * GetForwardParticleEquivalent (G4ParticleDefinition *theAdjPartDef)
void SetTmin (G4double aVal)
void SetTmax (G4double aVal)
void SetNbins (G4int aInt)
void SetIon (G4ParticleDefinition *adjIon, G4ParticleDefinition *fwdIon)
Static Public Member Functions
static G4AdjointCSManager * GetAdjointCSManager ()
Private Member Functions
std::vector< G4AdjointCSMatrix * > BuildCrossSectionsMatricesForAGivenModelAndElement (G4VEmAdjointModel *aModel, G4int Z, G4int A, G4int nbin_pro_decade)
std::vector< G4AdjointCSMatrix * > BuildCrossSectionsMatricesForAGivenModelAndMaterial (G4VEmAdjointModel *aModel, G4Material *aMaterial, G4int nbin_pro_decade)
G4AdjointCSManager ()
void DefineCurrentMaterial (const G4MaterialCutsCouple *couple)
void DefineCurrentParticle (const G4ParticleDefinition *aPartDef)
G4double ComputeAdjointCS (G4double aPrimEnergy, G4AdjointCSMatrix *anAdjointCSMatrix, G4double Tcut)
Private Attributes
std::vector< std::vector
< G4AdjointCSMatrix * > > theAdjointCSMatricesForScatProjToProj
std::vector< std::vector
< G4AdjointCSMatrix * > > theAdjointCSMatricesForProdToProj
std::vector< G4VEmAdjointModel * > listOfAdjointEMModel
G4Material * lastMaterial
G4double lastPrimaryEnergy
G4double lastTcut
std::vector< size_t > listOfIndexOfAdjointEMModelInAction
std::vector< G4bool > listOfIsScatProjToProjCase
std::vector< std::vector
< G4double > > lastAdjointCSVsModelsAndElements
G4bool CrossSectionMatrixesAreBuilt
size_t currentParticleIndex
G4ParticleDefinition * currentParticleDef
std::vector< G4PhysicsTable * > theTotalForwardSigmaTableVector
std::vector< G4PhysicsTable * > theTotalAdjointSigmaTableVector
std::vector< std::vector
< G4double > > EminForFwdSigmaTables
std::vector< std::vector
< G4double > > EminForAdjSigmaTables
std::vector< std::vector
< G4double > > EkinofFwdSigmaMax
std::vector< std::vector
< G4double > > EkinofAdjSigmaMax
G4bool TotalSigmaTableAreBuilt
std::vector< G4PhysicsTable * > listSigmaTableForAdjointModelScatProjToProj
std::vector< G4PhysicsTable * > listSigmaTableForAdjointModelProdToProj
std::vector< std::vector
< G4VEmProcess * > * > listOfForwardEmProcess
std::vector< std::vector
< G4VEnergyLossProcess * > * > listOfForwardEnergyLossProcess
std::vector
< G4ParticleDefinition * > theListOfAdjointParticlesInAction
G4double Tmin
G4double Tmax
G4int nbins
G4MaterialCutsCouple * currentCouple
G4Material * currentMaterial
size_t currentMatIndex
G4int verbose
G4bool forward_CS_is_used
G4bool forward_CS_mode
G4double PreadjCS
G4double PostadjCS
G4double PrefwdCS
G4double PostfwdCS
G4double LastEkinForCS
G4double LastCSCorrectionFactor
G4ParticleDefinition * lastPartDefForCS
G4ParticleDefinition * theAdjIon
G4ParticleDefinition * theFwdIon
G4double massRatio
size_t eindex
Static Private Attributes
static G4ThreadLocal
G4AdjointCSManager * theInstance = nullptr
Friends
class G4ThreadLocalSingleton< G4AdjointCSManager >
Detailed Description
Definition at line 68 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 68 of file G4AdjointCSManager.hh
Constructor & Destructor Documentation
G4AdjointCSManager::~G4AdjointCSManager ()
Definition at line 117 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 117 of file G4AdjointCSManager.cc
G4AdjointCSManager::G4AdjointCSManager () private
Definition at line 71 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 71 of file G4AdjointCSManager.cc
References G4AdjointElectron::AdjointElectron(), G4AdjointGamma::AdjointGamma(), G4AdjointProton::AdjointProton(), CrossSectionMatrixesAreBuilt, currentCouple, currentMaterial, currentMatIndex, currentParticleDef, currentParticleIndex, eindex, EkinofAdjSigmaMax, EkinofFwdSigmaMax, EminForAdjSigmaTables, EminForFwdSigmaTables, forward_CS_is_used, forward_CS_mode, keV, LastCSCorrectionFactor, LastEkinForCS, lastMaterial, lastPartDefForCS, lastPrimaryEnergy, lastTcut, listOfForwardEmProcess, listOfForwardEnergyLossProcess, listSigmaTableForAdjointModelProdToProj, listSigmaTableForAdjointModelScatProjToProj, massRatio, nbins, PostadjCS, PostfwdCS, PreadjCS, PrefwdCS, RegisterAdjointParticle(), TeV, theAdjIon, theFwdIon, theListOfAdjointParticlesInAction, theTotalAdjointSigmaTableVector, theTotalForwardSigmaTableVector, Tmax, Tmin, TotalSigmaTableAreBuilt, and verbose.
Member Function Documentation
void G4AdjointCSManager::BuildCrossSectionMatrices ()
Definition at line 181 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 181 of file G4AdjointCSManager.cc
References A(), BuildCrossSectionsMatricesForAGivenModelAndElement(), BuildCrossSectionsMatricesForAGivenModelAndMaterial(), CrossSectionMatrixesAreBuilt, G4cout, G4endl, G4lrint(), G4Element::GetElementTable(), G4Material::GetMaterialTable(), G4Element::GetN(), G4VEmAdjointModel::GetName(), G4VEmAdjointModel::GetUseMatrix(), G4VEmAdjointModel::GetUseMatrixPerElement(), G4VEmAdjointModel::GetUseOnlyOneMatrixForAllElements(), G4Element::GetZ(), listOfAdjointEMModel, G4VEmAdjointModel::SetCSMatrices(), theAdjointCSMatricesForProdToProj, theAdjointCSMatricesForScatProjToProj, and Z.
Referenced by G4AdjointForcedInteractionForGamma::BuildPhysicsTable(), and G4VAdjointReverseReaction::BuildPhysicsTable().
std::vector< G4AdjointCSMatrix * > G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndElement (G4VEmAdjointModel * aModel, G4int Z, G4int A, G4int nbin_pro_decade) private
Definition at line 747 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 747 of file G4AdjointCSManager.cc
References G4AdjointCSMatrix::AddData(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForScatProj(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForSecond(), e, G4VEmAdjointModel::GetHighEnergyLimit(), G4VEmAdjointModel::GetLowEnergyLimit(), G4VEmAdjointModel::GetSecondPartOfSameType(), max, and min.
Referenced by BuildCrossSectionMatrices().
std::vector< G4AdjointCSMatrix * > G4AdjointCSManager::BuildCrossSectionsMatricesForAGivenModelAndMaterial (G4VEmAdjointModel * aModel, G4Material * aMaterial, G4int nbin_pro_decade) private
Definition at line 840 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 840 of file G4AdjointCSManager.cc
References G4AdjointCSMatrix::AddData(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForSecond(), G4VEmAdjointModel::GetHighEnergyLimit(), G4VEmAdjointModel::GetLowEnergyLimit(), G4VEmAdjointModel::GetSecondPartOfSameType(), max, and min.
Referenced by BuildCrossSectionMatrices().
void G4AdjointCSManager::BuildTotalSigmaTables ()
Definition at line 268 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 268 of file G4AdjointCSManager.cc
References ComputeTotalAdjointCS(), DefineCurrentParticle(), e, e1, eindex, EkinofAdjSigmaMax, EkinofFwdSigmaMax, EminForAdjSigmaTables, EminForFwdSigmaTables, G4VEmModel::GetChargeSquareRatio(), G4MaterialCutsCouple::GetIndex(), G4PhysicsVector::GetLowEdgeEnergy(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4PhysicsVector::GetVectorLength(), k, listOfAdjointEMModel, listOfForwardEmProcess, listOfForwardEnergyLossProcess, listSigmaTableForAdjointModelProdToProj, listSigmaTableForAdjointModelScatProjToProj, massRatio, nbins, G4PhysicsVector::PutValue(), theAdjIon, theFwdIon, theListOfAdjointParticlesInAction, theTotalAdjointSigmaTableVector, theTotalForwardSigmaTableVector, Tmax, Tmin, and TotalSigmaTableAreBuilt.
Referenced by G4AdjointForcedInteractionForGamma::BuildPhysicsTable(), and G4VAdjointReverseReaction::BuildPhysicsTable().
G4double G4AdjointCSManager::ComputeAdjointCS (G4Material * aMaterial, G4VEmAdjointModel * aModel, G4double PrimEnergy, G4double Tcut, G4bool IsScatProjToProjCase, std::vector< G4double > & AdjointCS_for_each_element)
Definition at line 533 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 533 of file G4AdjointCSManager.cc
References G4VEmAdjointModel::AdjointCrossSection(), currentCouple, G4VEmAdjointModel::GetApplyCutInRange(), G4Material::GetElement(), G4Element::GetIndex(), G4Material::GetIndex(), G4Material::GetNumberOfElements(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForScatProjToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForScatProjToProjCase(), G4VEmAdjointModel::GetUseMatrix(), G4VEmAdjointModel::GetUseMatrixPerElement(), G4VEmAdjointModel::GetUseOnlyOneMatrixForAllElements(), G4Material::GetVecNbOfAtomsPerVolume(), G4Element::GetZ(), lastAdjointCSVsModelsAndElements, lastMaterial, lastPrimaryEnergy, lastTcut, listOfAdjointEMModel, listOfIndexOfAdjointEMModelInAction, listOfIsScatProjToProjCase, theAdjointCSMatricesForProdToProj, and theAdjointCSMatricesForScatProjToProj.
Referenced by G4VEmAdjointModel::AdjointCrossSection(), ComputeTotalAdjointCS(), and SampleElementFromCSMatrices().
G4double G4AdjointCSManager::ComputeAdjointCS (G4double aPrimEnergy, G4AdjointCSMatrix * anAdjointCSMatrix, G4double Tcut) private
Definition at line 1002 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 1002 of file G4AdjointCSManager.cc
References G4AdjointInterpolator::FindPositionForLogVector(), G4cout, G4endl, G4AdjointCSMatrix::GetData(), G4AdjointInterpolator::GetInstance(), G4AdjointCSMatrix::GetLogPrimEnergyVector(), G4AdjointInterpolator::InterpolateForLogVector(), G4AdjointCSMatrix::IsScatProjToProjCase(), and G4AdjointInterpolator::LinearInterpolation().
G4double G4AdjointCSManager::ComputeTotalAdjointCS (const G4MaterialCutsCouple * aMatCutCouple, G4ParticleDefinition * aPart, G4double PrimEnergy)
Definition at line 688 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 688 of file G4AdjointCSManager.cc
References ComputeAdjointCS(), currentMaterial, currentMatIndex, DefineCurrentMaterial(), eindex, G4ProductionCutsTable::GetEnergyCutsVector(), GetForwardParticleEquivalent(), G4MaterialCutsCouple::GetIndex(), G4ParticleDefinition::GetParticleName(), G4ProductionCutsTable::GetProductionCutsTable(), incremental_prev_tag::idx, listOfAdjointEMModel, listSigmaTableForAdjointModelProdToProj, and listSigmaTableForAdjointModelScatProjToProj.
Referenced by BuildTotalSigmaTables().
void G4AdjointCSManager::DefineCurrentMaterial (const G4MaterialCutsCouple * couple) private
Definition at line 969 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 969 of file G4AdjointCSManager.cc
References currentCouple, currentMaterial, currentMatIndex, G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), LastCSCorrectionFactor, LastEkinForCS, and lastPartDefForCS.
Referenced by ComputeTotalAdjointCS(), GetAdjointSigma(), GetCrossSectionCorrection(), GetEminForTotalCS(), GetMaxAdjTotalCS(), GetMaxFwdTotalCS(), GetTotalAdjointCS(), and GetTotalForwardCS().
void G4AdjointCSManager::DefineCurrentParticle (const G4ParticleDefinition * aPartDef) private
Definition at line 983 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 983 of file G4AdjointCSManager.cc
References currentParticleDef, currentParticleIndex, G4ParticleDefinition::GetPDGMass(), massRatio, source.hepunit::proton_mass_c2, theAdjIon, and theListOfAdjointParticlesInAction.
Referenced by BuildTotalSigmaTables(), GetEminForTotalCS(), GetMaxAdjTotalCS(), GetMaxFwdTotalCS(), GetTotalAdjointCS(), and GetTotalForwardCS().
G4AdjointCSManager * G4AdjointCSManager::GetAdjointCSManager () static
Definition at line 60 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 60 of file G4AdjointCSManager.cc
References G4ThreadLocalSingleton< T >::Instance(), and theInstance.
Referenced by G4VEmAdjointModel::AdjointCrossSection(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4AdjointPhysicsList::ConstructEM(), G4AdjointPhotoElectricModel::CorrectPostStepWeight(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4VEmAdjointModel::CorrectPostStepWeight(), G4AdjointForcedInteractionForGamma::G4AdjointForcedInteractionForGamma(), G4VAdjointReverseReaction::G4VAdjointReverseReaction(), G4VEmAdjointModel::G4VEmAdjointModel(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), and G4AdjointhIonisationModel::RapidSampleSecondaries().
G4ParticleDefinition * G4AdjointCSManager::GetAdjointParticleEquivalent (G4ParticleDefinition * theFwdPartDef)
Definition at line 948 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 948 of file G4AdjointCSManager.cc
References G4AdjointElectron::AdjointElectron(), G4AdjointGamma::AdjointGamma(), G4AdjointProton::AdjointProton(), G4ParticleDefinition::GetParticleName(), theAdjIon, and theFwdIon.
Referenced by RegisterEmProcess(), and RegisterEnergyLossProcess().
G4double G4AdjointCSManager::GetAdjointSigma (G4double Ekin_nuc, size_t index_model, G4bool is_scat_proj_to_proj, const G4MaterialCutsCouple * aCouple)
Definition at line 419 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 419 of file G4AdjointCSManager.cc
References b, currentMatIndex, DefineCurrentMaterial(), listSigmaTableForAdjointModelProdToProj, and listSigmaTableForAdjointModelScatProjToProj.
G4double G4AdjointCSManager::GetContinuousWeightCorrection (G4ParticleDefinition * aPartDef, G4double PreStepEkin, G4double AfterStepEkin, const G4MaterialCutsCouple * aCouple, G4double step_length)
Definition at line 503 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 503 of file G4AdjointCSManager.cc
References forward_CS_is_used, GetTotalAdjointCS(), GetTotalForwardCS(), and LastCSCorrectionFactor.
Referenced by G4AdjointAlongStepWeightCorrection::AlongStepDoIt().
G4double G4AdjointCSManager::GetCrossSectionCorrection (G4ParticleDefinition * aPartDef, G4double PreStepEkin, const G4MaterialCutsCouple * aCouple, G4bool & fwd_is_used, G4double & fwd_TotCS)
Definition at line 466 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 466 of file G4AdjointCSManager.cc
References currentCouple, DefineCurrentMaterial(), forward_CS_is_used, forward_CS_mode, GetTotalAdjointCS(), GetTotalForwardCS(), LastCSCorrectionFactor, LastEkinForCS, lastPartDefForCS, PreadjCS, and PrefwdCS.
Referenced by G4VAdjointReverseReaction::GetMeanFreePath().
void G4AdjointCSManager::GetEminForTotalCS (G4ParticleDefinition * aPartDef, const G4MaterialCutsCouple * aCouple, G4double & emin_adj, G4double & emin_fwd)
Definition at line 428 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 428 of file G4AdjointCSManager.cc
References currentMatIndex, currentParticleIndex, DefineCurrentMaterial(), DefineCurrentParticle(), EminForAdjSigmaTables, EminForFwdSigmaTables, and massRatio.
G4ParticleDefinition * G4AdjointCSManager::GetForwardParticleEquivalent (G4ParticleDefinition * theAdjPartDef)
Definition at line 959 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 959 of file G4AdjointCSManager.cc
References G4Electron::Electron(), G4Gamma::Gamma(), G4ParticleDefinition::GetParticleName(), G4Proton::Proton(), theAdjIon, and theFwdIon.
Referenced by ComputeTotalAdjointCS().
void G4AdjointCSManager::GetMaxAdjTotalCS (G4ParticleDefinition * aPartDef, const G4MaterialCutsCouple * aCouple, G4double & e_sigma_max, G4double & sigma_max)
Definition at line 453 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 453 of file G4AdjointCSManager.cc
References b, currentMatIndex, currentParticleIndex, DefineCurrentMaterial(), DefineCurrentParticle(), EkinofAdjSigmaMax, massRatio, and theTotalAdjointSigmaTableVector.
void G4AdjointCSManager::GetMaxFwdTotalCS (G4ParticleDefinition * aPartDef, const G4MaterialCutsCouple * aCouple, G4double & e_sigma_max, G4double & sigma_max)
Definition at line 440 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 440 of file G4AdjointCSManager.cc
References b, currentMatIndex, currentParticleIndex, DefineCurrentMaterial(), DefineCurrentParticle(), EkinofFwdSigmaMax, massRatio, and theTotalForwardSigmaTableVector.
G4int G4AdjointCSManager::GetNbProcesses ()
G4double G4AdjointCSManager::GetPostStepWeightCorrection ()
Definition at line 526 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 526 of file G4AdjointCSManager.cc
References LastCSCorrectionFactor.
Referenced by G4AdjointPhotoElectricModel::CorrectPostStepWeight(), G4AdjointIonIonisationModel::CorrectPostStepWeight(), G4VEmAdjointModel::CorrectPostStepWeight(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), and G4AdjointhIonisationModel::RapidSampleSecondaries().
G4double G4AdjointCSManager::GetTotalAdjointCS (G4ParticleDefinition * aPartDef, G4double Ekin, const G4MaterialCutsCouple * aCouple)
Definition at line 396 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 396 of file G4AdjointCSManager.cc
References b, currentMatIndex, currentParticleIndex, DefineCurrentMaterial(), DefineCurrentParticle(), massRatio, and theTotalAdjointSigmaTableVector.
Referenced by G4AdjointForcedInteractionForGamma::AlongStepDoIt(), GetContinuousWeightCorrection(), GetCrossSectionCorrection(), and G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength().
G4double G4AdjointCSManager::GetTotalForwardCS (G4ParticleDefinition * aPartDef, G4double Ekin, const G4MaterialCutsCouple * aCouple)
Definition at line 408 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 408 of file G4AdjointCSManager.cc
References b, currentMatIndex, currentParticleIndex, DefineCurrentMaterial(), DefineCurrentParticle(), massRatio, and theTotalForwardSigmaTableVector.
Referenced by G4AdjointForcedInteractionForGamma::AlongStepDoIt(), GetContinuousWeightCorrection(), and GetCrossSectionCorrection().
void G4AdjointCSManager::RegisterAdjointParticle (G4ParticleDefinition * aPartDef)
Definition at line 160 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 160 of file G4AdjointCSManager.cc
References EkinofAdjSigmaMax, EkinofFwdSigmaMax, EminForAdjSigmaTables, EminForFwdSigmaTables, G4ParticleDefinition::GetParticleName(), listOfForwardEmProcess, listOfForwardEnergyLossProcess, theListOfAdjointParticlesInAction, theTotalAdjointSigmaTableVector, and theTotalForwardSigmaTableVector.
Referenced by G4AdjointPhysicsList::ConstructEM(), G4AdjointCSManager(), RegisterEmProcess(), and RegisterEnergyLossProcess().
size_t G4AdjointCSManager::RegisterEmAdjointModel (G4VEmAdjointModel * aModel)
Definition at line 122 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 122 of file G4AdjointCSManager.cc
References listOfAdjointEMModel, listSigmaTableForAdjointModelProdToProj, and listSigmaTableForAdjointModelScatProjToProj.
Referenced by G4VEmAdjointModel::G4VEmAdjointModel().
void G4AdjointCSManager::RegisterEmProcess (G4VEmProcess * aProcess, G4ParticleDefinition * aPartDef)
Definition at line 131 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 131 of file G4AdjointCSManager.cc
References GetAdjointParticleEquivalent(), G4ParticleDefinition::GetParticleName(), listOfForwardEmProcess, RegisterAdjointParticle(), and theListOfAdjointParticlesInAction.
void G4AdjointCSManager::RegisterEnergyLossProcess (G4VEnergyLossProcess * aProcess, G4ParticleDefinition * aPartDef)
Definition at line 146 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 146 of file G4AdjointCSManager.cc
References GetAdjointParticleEquivalent(), G4ParticleDefinition::GetParticleName(), listOfForwardEnergyLossProcess, RegisterAdjointParticle(), and theListOfAdjointParticlesInAction.
G4Element * G4AdjointCSManager::SampleElementFromCSMatrices (G4Material * aMaterial, G4VEmAdjointModel * aModel, G4double PrimEnergy, G4double Tcut, G4bool IsScatProjToProjCase)
Definition at line 663 of file G4AdjointCSManager.cc.
View newest version in sPHENIX GitHub at line 663 of file G4AdjointCSManager.cc
References ComputeAdjointCS(), G4UniformRand, and G4Material::GetElement().
void G4AdjointCSManager::SetFwdCrossSectionMode (G4bool aBool) inline
Definition at line 123 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 123 of file G4AdjointCSManager.hh
References forward_CS_mode.
void G4AdjointCSManager::SetIon (G4ParticleDefinition * adjIon, G4ParticleDefinition * fwdIon) inline
Definition at line 170 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 170 of file G4AdjointCSManager.hh
References theAdjIon, and theFwdIon.
void G4AdjointCSManager::SetNbins (G4int aInt) inline
Definition at line 169 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 169 of file G4AdjointCSManager.hh
References nbins.
void G4AdjointCSManager::SetTmax (G4double aVal) inline
Definition at line 168 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 168 of file G4AdjointCSManager.hh
References Tmax.
void G4AdjointCSManager::SetTmin (G4double aVal) inline
Definition at line 167 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 167 of file G4AdjointCSManager.hh
References Tmin.
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4AdjointCSManager > friend
Definition at line 71 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 71 of file G4AdjointCSManager.hh
Member Data Documentation
G4bool G4AdjointCSManager::CrossSectionMatrixesAreBuilt private
Definition at line 198 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 198 of file G4AdjointCSManager.hh
Referenced by BuildCrossSectionMatrices(), and G4AdjointCSManager().
G4MaterialCutsCouple* G4AdjointCSManager::currentCouple private
Definition at line 230 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 230 of file G4AdjointCSManager.hh
Referenced by ComputeAdjointCS(), DefineCurrentMaterial(), G4AdjointCSManager(), and GetCrossSectionCorrection().
G4Material* G4AdjointCSManager::currentMaterial private
Definition at line 231 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 231 of file G4AdjointCSManager.hh
Referenced by ComputeTotalAdjointCS(), DefineCurrentMaterial(), and G4AdjointCSManager().
size_t G4AdjointCSManager::currentMatIndex private
Definition at line 232 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 232 of file G4AdjointCSManager.hh
Referenced by ComputeTotalAdjointCS(), DefineCurrentMaterial(), G4AdjointCSManager(), GetAdjointSigma(), GetEminForTotalCS(), GetMaxAdjTotalCS(), GetMaxFwdTotalCS(), GetTotalAdjointCS(), and GetTotalForwardCS().
G4ParticleDefinition* G4AdjointCSManager::currentParticleDef private
Definition at line 200 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 200 of file G4AdjointCSManager.hh
Referenced by DefineCurrentParticle(), and G4AdjointCSManager().
size_t G4AdjointCSManager::currentParticleIndex private
Definition at line 199 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 199 of file G4AdjointCSManager.hh
Referenced by DefineCurrentParticle(), G4AdjointCSManager(), GetEminForTotalCS(), GetMaxAdjTotalCS(), GetMaxFwdTotalCS(), GetTotalAdjointCS(), and GetTotalForwardCS().
size_t G4AdjointCSManager::eindex private
Definition at line 264 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 264 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), ComputeTotalAdjointCS(), and G4AdjointCSManager().
std::vector< std::vector<G4double> > G4AdjointCSManager::EkinofAdjSigmaMax private
Definition at line 209 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 209 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), GetMaxAdjTotalCS(), and RegisterAdjointParticle().
std::vector< std::vector<G4double> > G4AdjointCSManager::EkinofFwdSigmaMax private
Definition at line 208 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 208 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), GetMaxFwdTotalCS(), and RegisterAdjointParticle().
std::vector< std::vector<G4double> > G4AdjointCSManager::EminForAdjSigmaTables private
Definition at line 207 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 207 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), GetEminForTotalCS(), and RegisterAdjointParticle().
std::vector< std::vector<G4double> > G4AdjointCSManager::EminForFwdSigmaTables private
Definition at line 206 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 206 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), GetEminForTotalCS(), and RegisterAdjointParticle().
G4bool G4AdjointCSManager::forward_CS_is_used private
Definition at line 241 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 241 of file G4AdjointCSManager.hh
Referenced by G4AdjointCSManager(), GetContinuousWeightCorrection(), and GetCrossSectionCorrection().
G4bool G4AdjointCSManager::forward_CS_mode private
Definition at line 242 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 242 of file G4AdjointCSManager.hh
Referenced by G4AdjointCSManager(), GetCrossSectionCorrection(), and SetFwdCrossSectionMode().
std::vector< std::vector<G4double> > G4AdjointCSManager::lastAdjointCSVsModelsAndElements private
Definition at line 197 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 197 of file G4AdjointCSManager.hh
Referenced by ComputeAdjointCS().
G4double G4AdjointCSManager::LastCSCorrectionFactor private
Definition at line 250 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 250 of file G4AdjointCSManager.hh
Referenced by DefineCurrentMaterial(), G4AdjointCSManager(), GetContinuousWeightCorrection(), GetCrossSectionCorrection(), and GetPostStepWeightCorrection().
G4double G4AdjointCSManager::LastEkinForCS private
Definition at line 249 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 249 of file G4AdjointCSManager.hh
Referenced by DefineCurrentMaterial(), G4AdjointCSManager(), and GetCrossSectionCorrection().
G4Material* G4AdjointCSManager::lastMaterial private
Definition at line 192 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 192 of file G4AdjointCSManager.hh
Referenced by ComputeAdjointCS(), and G4AdjointCSManager().
G4ParticleDefinition* G4AdjointCSManager::lastPartDefForCS private
Definition at line 251 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 251 of file G4AdjointCSManager.hh
Referenced by DefineCurrentMaterial(), G4AdjointCSManager(), and GetCrossSectionCorrection().
G4double G4AdjointCSManager::lastPrimaryEnergy private
Definition at line 193 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 193 of file G4AdjointCSManager.hh
Referenced by ComputeAdjointCS(), and G4AdjointCSManager().
G4double G4AdjointCSManager::lastTcut private
Definition at line 194 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 194 of file G4AdjointCSManager.hh
Referenced by ComputeAdjointCS(), and G4AdjointCSManager().
std::vector< G4VEmAdjointModel*> G4AdjointCSManager::listOfAdjointEMModel private
Definition at line 178 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 178 of file G4AdjointCSManager.hh
Referenced by BuildCrossSectionMatrices(), BuildTotalSigmaTables(), ComputeAdjointCS(), ComputeTotalAdjointCS(), and RegisterEmAdjointModel().
std::vector< std::vector<G4VEmProcess*>* > G4AdjointCSManager::listOfForwardEmProcess private
Definition at line 218 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 218 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), RegisterAdjointParticle(), and RegisterEmProcess().
std::vector< std::vector<G4VEnergyLossProcess*>* > G4AdjointCSManager::listOfForwardEnergyLossProcess private
Definition at line 219 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 219 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), RegisterAdjointParticle(), and RegisterEnergyLossProcess().
std::vector< size_t> G4AdjointCSManager::listOfIndexOfAdjointEMModelInAction private
Definition at line 195 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 195 of file G4AdjointCSManager.hh
Referenced by ComputeAdjointCS().
std::vector< G4bool> G4AdjointCSManager::listOfIsScatProjToProjCase private
Definition at line 196 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 196 of file G4AdjointCSManager.hh
Referenced by ComputeAdjointCS().
std::vector<G4PhysicsTable*> G4AdjointCSManager::listSigmaTableForAdjointModelProdToProj private
Definition at line 214 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 214 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), ComputeTotalAdjointCS(), G4AdjointCSManager(), GetAdjointSigma(), and RegisterEmAdjointModel().
std::vector<G4PhysicsTable*> G4AdjointCSManager::listSigmaTableForAdjointModelScatProjToProj private
Definition at line 213 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 213 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), ComputeTotalAdjointCS(), G4AdjointCSManager(), GetAdjointSigma(), and RegisterEmAdjointModel().
G4double G4AdjointCSManager::massRatio private
Definition at line 257 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 257 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), DefineCurrentParticle(), G4AdjointCSManager(), GetEminForTotalCS(), GetMaxAdjTotalCS(), GetMaxFwdTotalCS(), GetTotalAdjointCS(), and GetTotalForwardCS().
G4int G4AdjointCSManager::nbins private
Definition at line 226 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 226 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), and SetNbins().
G4double G4AdjointCSManager::PostadjCS private
Definition at line 247 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 247 of file G4AdjointCSManager.hh
Referenced by G4AdjointCSManager().
G4double G4AdjointCSManager::PostfwdCS private
Definition at line 248 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 248 of file G4AdjointCSManager.hh
Referenced by G4AdjointCSManager().
G4double G4AdjointCSManager::PreadjCS private
Definition at line 247 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 247 of file G4AdjointCSManager.hh
Referenced by G4AdjointCSManager(), and GetCrossSectionCorrection().
G4double G4AdjointCSManager::PrefwdCS private
Definition at line 248 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 248 of file G4AdjointCSManager.hh
Referenced by G4AdjointCSManager(), and GetCrossSectionCorrection().
G4ParticleDefinition* G4AdjointCSManager::theAdjIon private
Definition at line 255 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 255 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), DefineCurrentParticle(), G4AdjointCSManager(), GetAdjointParticleEquivalent(), GetForwardParticleEquivalent(), and SetIon().
std::vector< std::vector<G4AdjointCSMatrix*> > G4AdjointCSManager::theAdjointCSMatricesForProdToProj private
Definition at line 177 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 177 of file G4AdjointCSManager.hh
Referenced by BuildCrossSectionMatrices(), and ComputeAdjointCS().
std::vector< std::vector<G4AdjointCSMatrix*> > G4AdjointCSManager::theAdjointCSMatricesForScatProjToProj private
Definition at line 176 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 176 of file G4AdjointCSManager.hh
Referenced by BuildCrossSectionMatrices(), and ComputeAdjointCS().
G4ParticleDefinition* G4AdjointCSManager::theFwdIon private
Definition at line 256 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 256 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), GetAdjointParticleEquivalent(), GetForwardParticleEquivalent(), and SetIon().
G4ThreadLocal G4AdjointCSManager * G4AdjointCSManager::theInstance = nullptr static private
Definition at line 175 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 175 of file G4AdjointCSManager.hh
Referenced by GetAdjointCSManager().
std::vector< G4ParticleDefinition*> G4AdjointCSManager::theListOfAdjointParticlesInAction private
Definition at line 223 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 223 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), DefineCurrentParticle(), G4AdjointCSManager(), RegisterAdjointParticle(), RegisterEmProcess(), and RegisterEnergyLossProcess().
std::vector<G4PhysicsTable*> G4AdjointCSManager::theTotalAdjointSigmaTableVector private
Definition at line 205 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 205 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), GetMaxAdjTotalCS(), GetTotalAdjointCS(), and RegisterAdjointParticle().
std::vector<G4PhysicsTable*> G4AdjointCSManager::theTotalForwardSigmaTableVector private
Definition at line 204 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 204 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), GetMaxFwdTotalCS(), GetTotalForwardCS(), and RegisterAdjointParticle().
G4double G4AdjointCSManager::Tmax private
Definition at line 225 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 225 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), and SetTmax().
G4double G4AdjointCSManager::Tmin private
Definition at line 225 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 225 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), G4AdjointCSManager(), and SetTmin().
G4bool G4AdjointCSManager::TotalSigmaTableAreBuilt private
Definition at line 210 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 210 of file G4AdjointCSManager.hh
Referenced by BuildTotalSigmaTables(), and G4AdjointCSManager().
G4int G4AdjointCSManager::verbose private
Definition at line 234 of file G4AdjointCSManager.hh.
View newest version in sPHENIX GitHub at line 234 of file G4AdjointCSManager.hh
Referenced by G4AdjointCSManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointCSManager.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/src/G4AdjointCSManager.cc