ECCE @ EIC Software: G4ConversionUtils Namespace Reference
G4ConversionUtils Namespace Reference
Functions
template<typename Value >
G4bool Convert (const G4String &myInput, Value &output)
template<>
G4bool Convert (const G4String &myInput, G4DimensionedDouble &output)
template<>
G4bool Convert (const G4String &myInput, G4ThreeVector &output)
template<typename Value >
G4bool Convert (const G4String &myInput, Value &value1, Value &value2)
template<>
G4bool Convert (const G4String &myInput, G4DimensionedDouble &min, G4DimensionedDouble &max)
template<>
G4bool Convert (const G4String &myInput, G4ThreeVector &min, G4ThreeVector &max)
Function Documentation
template<typename Value > G4bool G4ConversionUtils::Convert (const G4String & myInput, Value & output)
Definition at line 45 of file G4ConversionUtils.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ConversionUtils.hh
References G4String::strip().
Referenced by G4AttValueFilterT< T, ConversionErrorPolicy >::Accept(), G4AttValueFilterT< T, ConversionErrorPolicy >::GetValidElement(), G4AttValueFilterT< T, ConversionErrorPolicy >::LoadIntervalElement(), and G4AttValueFilterT< T, ConversionErrorPolicy >::LoadSingleValueElement().
template<> G4bool G4ConversionUtils::Convert (const G4String & myInput, G4DimensionedDouble & output) inline
Definition at line 58 of file G4ConversionUtils.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ConversionUtils.hh
References G4String::strip().
template<> G4bool G4ConversionUtils::Convert (const G4String & myInput, G4ThreeVector & output) inline
Definition at line 95 of file G4ConversionUtils.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ConversionUtils.hh
References G4String::strip().
template<typename Value > G4bool G4ConversionUtils::Convert (const G4String & myInput, Value & value1, Value & value2)
Definition at line 114 of file G4ConversionUtils.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ConversionUtils.hh
References G4String::strip().
template<> G4bool G4ConversionUtils::Convert (const G4String & myInput, G4DimensionedDouble & min, G4DimensionedDouble & max) inline
Definition at line 127 of file G4ConversionUtils.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ConversionUtils.hh
References G4String::strip(), and Acts::Test::valueMin.
template<> G4bool G4ConversionUtils::Convert (const G4String & myInput, G4ThreeVector & min, G4ThreeVector & max) inline
Definition at line 169 of file G4ConversionUtils.hh.
View newest version in sPHENIX GitHub at line 169 of file G4ConversionUtils.hh
References G4String::strip().