ECCE @ EIC Software: G4PSDoseDepositForCylinder3D Class Reference
G4PSDoseDepositForCylinder3D Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSDoseDepositForCylinder3D.hh>
Public Member Functions
G4PSDoseDepositForCylinder3D (G4String name, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
G4PSDoseDepositForCylinder3D (G4String name, const G4String &unit, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
virtual ~G4PSDoseDepositForCylinder3D ()
void SetCylinderSize (G4double dr, G4double dz)
void SetNumberOfSegments (G4int nSeg[3])
Public Member Functions inherited from G4PSDoseDeposit3D
G4PSDoseDeposit3D (G4String name, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
G4PSDoseDeposit3D (G4String name, const G4String &unit, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
virtual ~G4PSDoseDeposit3D ()
Public Member Functions inherited from G4PSDoseDeposit
G4PSDoseDeposit (G4String name, G4int depth=0)
G4PSDoseDeposit (G4String name, const G4String &unit, G4int depth=0)
virtual ~G4PSDoseDeposit ()
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4double ComputeVolume (G4Step *, G4int idx)
Protected Member Functions inherited from G4PSDoseDeposit3D
virtual G4int GetIndex (G4Step *)
Protected Member Functions inherited from G4PSDoseDeposit
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VPrimitiveScorer
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4ThreeVector cylinderSize
G4int nSegment [3]
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 44 of file G4PSDoseDepositForCylinder3D.hh.
View newest version in sPHENIX GitHub at line 44 of file G4PSDoseDepositForCylinder3D.hh
Constructor & Destructor Documentation
G4PSDoseDepositForCylinder3D::G4PSDoseDepositForCylinder3D (G4String name, G4int ni = 1, G4int nj = 1, G4int nk = 1, G4int depi = 2, G4int depj = 1, G4int depk = 0)
Definition at line 42 of file G4PSDoseDepositForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 42 of file G4PSDoseDepositForCylinder3D.cc
References nSegment.
G4PSDoseDepositForCylinder3D::G4PSDoseDepositForCylinder3D (G4String name, const G4String & unit, G4int ni = 1, G4int nj = 1, G4int nk = 1, G4int depi = 2, G4int depj = 1, G4int depk = 0)
Definition at line 50 of file G4PSDoseDepositForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PSDoseDepositForCylinder3D.cc
References nSegment.
G4PSDoseDepositForCylinder3D::~G4PSDoseDepositForCylinder3D () virtual
Definition at line 59 of file G4PSDoseDepositForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 59 of file G4PSDoseDepositForCylinder3D.cc
Member Function Documentation
G4double G4PSDoseDepositForCylinder3D::ComputeVolume (G4Step * , G4int idx) protected virtual
Reimplemented from G4PSDoseDeposit.
Definition at line 72 of file G4PSDoseDepositForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 72 of file G4PSDoseDepositForCylinder3D.cc
References cylinderSize, nSegment, pi, r1, and v.
void G4PSDoseDepositForCylinder3D::SetCylinderSize (G4double dr, G4double dz)
Definition at line 62 of file G4PSDoseDepositForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PSDoseDepositForCylinder3D.cc
References cylinderSize, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and twopi.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4PSDoseDepositForCylinder3D::SetNumberOfSegments (G4int nSeg[3])
Definition at line 67 of file G4PSDoseDepositForCylinder3D.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PSDoseDepositForCylinder3D.cc
References nSegment.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
Member Data Documentation
G4ThreeVector G4PSDoseDepositForCylinder3D::cylinderSize private
Definition at line 64 of file G4PSDoseDepositForCylinder3D.hh.
View newest version in sPHENIX GitHub at line 64 of file G4PSDoseDepositForCylinder3D.hh
Referenced by ComputeVolume(), and SetCylinderSize().
G4int G4PSDoseDepositForCylinder3D::nSegment[3] private
Definition at line 65 of file G4PSDoseDepositForCylinder3D.hh.
View newest version in sPHENIX GitHub at line 65 of file G4PSDoseDepositForCylinder3D.hh
Referenced by ComputeVolume(), G4PSDoseDepositForCylinder3D(), and SetNumberOfSegments().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSDoseDepositForCylinder3D.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSDoseDepositForCylinder3D.cc