ECCE @ EIC Software: Par01PiModel Class Reference
Par01PiModel Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01PiModel.hh>
Public Member Functions
Par01PiModel (G4Region *anEnvelope)
~Par01PiModel ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4bool ModelTrigger (const G4FastTrack &)
virtual void DoIt (const G4FastTrack &, G4FastStep &)
Public Member Functions inherited from G4VFastSimulationModel
G4VFastSimulationModel (const G4String &aName)
G4VFastSimulationModel (const G4String &aName, G4Envelope *, G4bool IsUnique=FALSE)
virtual ~G4VFastSimulationModel ()
virtual G4bool AtRestModelTrigger (const G4FastTrack &)
virtual void AtRestDoIt (const G4FastTrack &, G4FastStep &)
const G4String GetName () const
G4bool operator== (const G4VFastSimulationModel &) const
Detailed Description
Definition at line 40 of file Par01PiModel.hh.
View newest version in sPHENIX GitHub at line 40 of file Par01PiModel.hh
Constructor & Destructor Documentation
Par01PiModel::Par01PiModel (G4Region * anEnvelope)
Definition at line 39 of file Par01PiModel.cc.
View newest version in sPHENIX GitHub at line 39 of file Par01PiModel.cc
Par01PiModel::~Par01PiModel ()
Definition at line 45 of file Par01PiModel.cc.
View newest version in sPHENIX GitHub at line 45 of file Par01PiModel.cc
Member Function Documentation
void Par01PiModel::DoIt (const G4FastTrack & fastTrack, G4FastStep & fastStep) virtual
Implements G4VFastSimulationModel.
Definition at line 94 of file Par01PiModel.cc.
View newest version in sPHENIX GitHub at line 94 of file Par01PiModel.cc
References G4FastStep::CreateSecondaryTrack(), G4cout, G4endl, G4Gamma::GammaDefinition(), G4FastTrack::GetEnvelopeSolid(), G4Track::GetGlobalTime(), G4FastTrack::GetPrimaryTrack(), G4FastTrack::GetPrimaryTrackLocalDirection(), G4FastTrack::GetPrimaryTrackLocalPosition(), position, G4FastStep::ProposePrimaryTrackFinalPosition(), G4FastStep::SetNumberOfSecondaryTracks(), and CLHEP::Hep3Vector::setZ().
G4bool Par01PiModel::IsApplicable (const G4ParticleDefinition & particleType) virtual
Implements G4VFastSimulationModel.
Definition at line 50 of file Par01PiModel.cc.
View newest version in sPHENIX GitHub at line 50 of file Par01PiModel.cc
References G4PionMinus::PionMinusDefinition(), and G4PionPlus::PionPlusDefinition().
G4bool Par01PiModel::ModelTrigger (const G4FastTrack & fastTrack) virtual
Implements G4VFastSimulationModel.
Definition at line 59 of file Par01PiModel.cc.
View newest version in sPHENIX GitHub at line 59 of file Par01PiModel.cc
References G4cout, G4endl, G4Track::GetMomentum(), G4Track::GetPosition(), G4FastTrack::GetPrimaryTrack(), G4FastTrack::GetPrimaryTrackLocalDirection(), G4FastTrack::GetPrimaryTrackLocalPosition(), and CLHEP::Hep3Vector::unit().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01PiModel.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/src/Par01PiModel.cc