ECCE @ EIC Software: G4HadElementSelector Class Reference
G4HadElementSelector Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4HadronXSDataTable.hh>
Public Member Functions
G4HadElementSelector (G4DynamicParticle *, G4CrossSectionDataStore *, const G4Material *, G4int bins, G4double emin, G4double emax, G4bool spline)
~G4HadElementSelector ()
void Dump ()
const G4Element * SelectRandomAtom (G4double e) const
Private Member Functions
G4HadElementSelector (G4HadElementSelector &)=delete
G4HadElementSelector & operator= (const G4HadElementSelector &right)=delete
Private Attributes
G4int nElmMinusOne
const G4ElementVector * theElementVector
std::vector< G4PhysicsVector * > xSections
Detailed Description
Definition at line 58 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 58 of file G4HadronXSDataTable.hh
Constructor & Destructor Documentation
G4HadElementSelector::G4HadElementSelector (G4DynamicParticle * dp, G4CrossSectionDataStore * xs, const G4Material * mat, G4int bins, G4double emin, G4double emax, G4bool spline)
Definition at line 51 of file G4HadronXSDataTable.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HadronXSDataTable.cc
References Acts::VectorHelpers::cross(), e, G4PhysicsVector::Energy(), G4CrossSectionDataStore::GetCrossSection(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), n, nElmMinusOne, G4DynamicParticle::SetKineticEnergy(), G4PhysicsVector::SetSpline(), theElementVector, xSections, and y.
G4HadElementSelector::~G4HadElementSelector ()
Definition at line 90 of file G4HadronXSDataTable.cc.
View newest version in sPHENIX GitHub at line 90 of file G4HadronXSDataTable.cc
References nElmMinusOne, and xSections.
G4HadElementSelector::G4HadElementSelector (G4HadElementSelector &) private delete
Member Function Documentation
void G4HadElementSelector::Dump ()
Definition at line 99 of file G4HadronXSDataTable.cc.
View newest version in sPHENIX GitHub at line 99 of file G4HadronXSDataTable.cc
G4HadElementSelector& G4HadElementSelector::operator= (const G4HadElementSelector & right) private delete
const G4Element* G4HadElementSelector::SelectRandomAtom (G4double e) const inline
Definition at line 70 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 70 of file G4HadronXSDataTable.hh
References G4UniformRand, nElmMinusOne, x, and xSections.
Member Data Documentation
G4int G4HadElementSelector::nElmMinusOne private
Definition at line 90 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 90 of file G4HadronXSDataTable.hh
Referenced by G4HadElementSelector(), SelectRandomAtom(), and ~G4HadElementSelector().
const G4ElementVector* G4HadElementSelector::theElementVector private
Definition at line 91 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HadronXSDataTable.hh
Referenced by G4HadElementSelector().
std::vector<G4PhysicsVector*> G4HadElementSelector::xSections private
Definition at line 92 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 92 of file G4HadronXSDataTable.hh
Referenced by G4HadElementSelector(), SelectRandomAtom(), and ~G4HadElementSelector().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4HadronXSDataTable.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4HadronXSDataTable.cc