ECCE @ EIC Software: G4EnergyRangeManager Class Reference
G4EnergyRangeManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4EnergyRangeManager.hh>
Public Member Functions
G4EnergyRangeManager ()
~G4EnergyRangeManager ()
void RegisterMe (G4HadronicInteraction *a)
G4HadronicInteraction * GetHadronicInteraction (const G4HadProjectile &aHadProjectile, G4Nucleus &aTargetNucleus, const G4Material *aMaterial, const G4Element *anElement) const
std::vector
< G4HadronicInteraction * > & GetHadronicInteractionList ()
void Dump (G4int verbose=0)
void BuildPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4EnergyRangeManager (const G4EnergyRangeManager &right)
G4EnergyRangeManager & operator= (const G4EnergyRangeManager &right)
G4bool operator== (const G4EnergyRangeManager &right) const
G4bool operator!= (const G4EnergyRangeManager &right) const
Private Attributes
G4int theHadronicInteractionCounter
std::vector
< G4HadronicInteraction * > theHadronicInteraction
Detailed Description
Definition at line 39 of file G4EnergyRangeManager.hh.
View newest version in sPHENIX GitHub at line 39 of file G4EnergyRangeManager.hh
Constructor & Destructor Documentation
G4EnergyRangeManager::G4EnergyRangeManager () explicit
Definition at line 39 of file G4EnergyRangeManager.cc.
View newest version in sPHENIX GitHub at line 39 of file G4EnergyRangeManager.cc
G4EnergyRangeManager::~G4EnergyRangeManager ()
Definition at line 43 of file G4EnergyRangeManager.cc.
View newest version in sPHENIX GitHub at line 43 of file G4EnergyRangeManager.cc
G4EnergyRangeManager::G4EnergyRangeManager (const G4EnergyRangeManager & right) private
Member Function Documentation
void G4EnergyRangeManager::BuildPhysicsTable (const G4ParticleDefinition & aParticleType)
Definition at line 178 of file G4EnergyRangeManager.cc.
View newest version in sPHENIX GitHub at line 178 of file G4EnergyRangeManager.cc
References theHadronicInteraction.
Referenced by G4HadronicProcess::BuildPhysicsTable().
void G4EnergyRangeManager::Dump (G4int verbose = 0)
Definition at line 161 of file G4EnergyRangeManager.cc.
View newest version in sPHENIX GitHub at line 161 of file G4EnergyRangeManager.cc
References G4cout, G4endl, GeV, theHadronicInteraction, and theHadronicInteractionCounter.
G4HadronicInteraction * G4EnergyRangeManager::GetHadronicInteraction (const G4HadProjectile & aHadProjectile, G4Nucleus & aTargetNucleus, const G4Material * aMaterial, const G4Element * anElement) const
Definition at line 59 of file G4EnergyRangeManager.cc.
View newest version in sPHENIX GitHub at line 59 of file G4EnergyRangeManager.cc
References kdfinder::abs(), G4cout, G4endl, G4UniformRand, G4ParticleDefinition::GetBaryonNumber(), G4HadProjectile::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4HadronicInteraction::GetMaxEnergy(), G4HadronicInteraction::GetMinEnergy(), G4HadronicInteraction::GetModelName(), theHadronicInteraction, and theHadronicInteractionCounter.
Referenced by G4HadronicProcess::ChooseHadronicInteraction().
std::vector< G4HadronicInteraction * > & G4EnergyRangeManager::GetHadronicInteractionList ()
Definition at line 156 of file G4EnergyRangeManager.cc.
View newest version in sPHENIX GitHub at line 156 of file G4EnergyRangeManager.cc
References theHadronicInteraction.
Referenced by G4HadronicProcess::GetHadronicInteractionList(), and G4HadronicProcess::GetHadronicModel().
G4bool G4EnergyRangeManager::operator!= (const G4EnergyRangeManager & right) const private
G4EnergyRangeManager& G4EnergyRangeManager::operator= (const G4EnergyRangeManager & right) private
G4bool G4EnergyRangeManager::operator== (const G4EnergyRangeManager & right) const private
void G4EnergyRangeManager::RegisterMe (G4HadronicInteraction * a)
Definition at line 46 of file G4EnergyRangeManager.cc.
View newest version in sPHENIX GitHub at line 46 of file G4EnergyRangeManager.cc
References theHadronicInteraction, and theHadronicInteractionCounter.
Referenced by G4HadronicProcess::RegisterMe().
Member Data Documentation
std::vector<G4HadronicInteraction*> G4EnergyRangeManager::theHadronicInteraction private
Definition at line 68 of file G4EnergyRangeManager.hh.
View newest version in sPHENIX GitHub at line 68 of file G4EnergyRangeManager.hh
Referenced by BuildPhysicsTable(), Dump(), GetHadronicInteraction(), GetHadronicInteractionList(), and RegisterMe().
G4int G4EnergyRangeManager::theHadronicInteractionCounter private
Definition at line 67 of file G4EnergyRangeManager.hh.
View newest version in sPHENIX GitHub at line 67 of file G4EnergyRangeManager.hh
Referenced by Dump(), GetHadronicInteraction(), and RegisterMe().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4EnergyRangeManager.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/src/G4EnergyRangeManager.cc