ECCE @ EIC Software: G4hICRU49p Class Reference
G4hICRU49p Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hICRU49p.hh>
Public Member Functions
G4hICRU49p ()
~G4hICRU49p ()
G4bool HasMaterial (const G4Material *material)
G4double StoppingPower (const G4Material *material, G4double kineticEnergy)
G4double ElectronicStoppingPower (G4double z, G4double kineticEnergy) const
Public Member Functions inherited from G4VhElectronicStoppingPower
G4VhElectronicStoppingPower ()
virtual ~G4VhElectronicStoppingPower ()
Private Member Functions
void SetMoleculaNumber (G4int number)
Private Attributes
G4int iMolecula
const G4double protonMassAMU
Additional Inherited Members
Protected Member Functions inherited from G4VhElectronicStoppingPower
G4double HeEffChargeSquare (const G4double z, const G4double kineticEnergyHe) const
G4double GetHeMassAMU () const
Detailed Description
Definition at line 59 of file G4hICRU49p.hh.
View newest version in sPHENIX GitHub at line 59 of file G4hICRU49p.hh
Constructor & Destructor Documentation
G4hICRU49p::G4hICRU49p ()
Definition at line 64 of file G4hICRU49p.cc.
View newest version in sPHENIX GitHub at line 64 of file G4hICRU49p.cc
G4hICRU49p::~G4hICRU49p ()
Definition at line 71 of file G4hICRU49p.cc.
View newest version in sPHENIX GitHub at line 71 of file G4hICRU49p.cc
Member Function Documentation
G4double G4hICRU49p::ElectronicStoppingPower (G4double z, G4double kineticEnergy) const virtual
Implements G4VhElectronicStoppingPower.
Definition at line 183 of file G4hICRU49p.cc.
View newest version in sPHENIX GitHub at line 183 of file G4hICRU49p.cc
References a, fac, keV, protonMassAMU, and T.
Referenced by StoppingPower().
G4bool G4hICRU49p::HasMaterial (const G4Material * material) virtual
Implements G4VhElectronicStoppingPower.
Definition at line 76 of file G4hICRU49p.cc.
View newest version in sPHENIX GitHub at line 76 of file G4hICRU49p.cc
References false, G4Material::GetChemicalFormula(), G4Material::GetNumberOfElements(), G4Material::GetState(), kStateGas, numberOfMolecula, SetMoleculaNumber(), theState, and true.
void G4hICRU49p::SetMoleculaNumber (G4int number) inline private
Definition at line 80 of file G4hICRU49p.hh.
View newest version in sPHENIX GitHub at line 80 of file G4hICRU49p.hh
References iMolecula.
Referenced by HasMaterial().
G4double G4hICRU49p::StoppingPower (const G4Material * material, G4double kineticEnergy) virtual
Implements G4VhElectronicStoppingPower.
Definition at line 114 of file G4hICRU49p.cc.
View newest version in sPHENIX GitHub at line 114 of file G4hICRU49p.cc
References a, ElectronicStoppingPower(), G4Material::GetNumberOfElements(), G4Material::GetZ(), iMolecula, keV, protonMassAMU, T, and z.
Member Data Documentation
G4int G4hICRU49p::iMolecula private
Definition at line 80 of file G4hICRU49p.hh.
View newest version in sPHENIX GitHub at line 80 of file G4hICRU49p.hh
Referenced by SetMoleculaNumber(), and StoppingPower().
const G4double G4hICRU49p::protonMassAMU private
Definition at line 83 of file G4hICRU49p.hh.
View newest version in sPHENIX GitHub at line 83 of file G4hICRU49p.hh
Referenced by ElectronicStoppingPower(), and StoppingPower().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hICRU49p.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4hICRU49p.cc