ECCE @ EIC Software: CexmcStudiedProcess Class Reference
CexmcStudiedProcess Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcStudiedProcess.hh>
Public Member Functions
CexmcStudiedProcess (CexmcPhysicsManager *physicsManager, G4ProcessType processType=fUserDefined)
G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step)
Public Member Functions inherited from G4WrapperProcess
G4WrapperProcess (const G4String &aName="Wrapped", G4ProcessType aType=fNotDefined)
G4WrapperProcess (const G4WrapperProcess &right)
virtual ~G4WrapperProcess ()
G4bool operator== (const G4WrapperProcess &right) const
G4bool operator!= (const G4WrapperProcess &right) const
virtual void RegisterProcess (G4VProcess *)
virtual const G4VProcess * GetRegisteredProcess () const
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &stepData)
virtual G4VParticleChange * AtRestDoIt (const G4Track &track, const G4Step &stepData)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
virtual void SetMasterProcess (G4VProcess *masterP)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Attributes
CexmcPhysicsManager * physicsManager
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4WrapperProcess
G4VProcess * pRegProcess
Detailed Description
Definition at line 54 of file CexmcStudiedProcess.hh.
View newest version in sPHENIX GitHub at line 54 of file CexmcStudiedProcess.hh
Constructor & Destructor Documentation
CexmcStudiedProcess::CexmcStudiedProcess (CexmcPhysicsManager * physicsManager, G4ProcessType processType = fUserDefined) explicit
Definition at line 51 of file CexmcStudiedProcess.cc.
View newest version in sPHENIX GitHub at line 51 of file CexmcStudiedProcess.cc
Member Function Documentation
G4VParticleChange * CexmcStudiedProcess::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Reimplemented from G4WrapperProcess.
Definition at line 85 of file CexmcStudiedProcess.cc.
View newest version in sPHENIX GitHub at line 85 of file CexmcStudiedProcess.cc
References fStopAndKill, CexmcPhysicsManager::IncrementNumberOfTriggeredStudiedInteractions(), physicsManager, G4VProcess::PostStepDoIt(), and G4WrapperProcess::pRegProcess.
G4double CexmcStudiedProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4WrapperProcess.
Definition at line 59 of file CexmcStudiedProcess.cc.
View newest version in sPHENIX GitHub at line 59 of file CexmcStudiedProcess.cc
References CexmcDblMax(), CexmcIncidentParticleTrackType, CexmcIncidentParticleTrackInfo::GetCurrentTrackLengthInTarget(), CexmcIncidentParticleTrackInfo::GetFinalTrackLengthInTarget(), CexmcTrackInfo::GetTypeInfo(), G4Track::GetUserInformation(), CexmcIncidentParticleTrackInfo::IsStudiedProcessActivated(), CexmcPhysicsManager::IsStudiedProcessAllowed(), NotForced, and physicsManager.
Member Data Documentation
CexmcPhysicsManager* CexmcStudiedProcess::physicsManager private
Definition at line 68 of file CexmcStudiedProcess.hh.
View newest version in sPHENIX GitHub at line 68 of file CexmcStudiedProcess.hh
Referenced by PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcStudiedProcess.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcStudiedProcess.cc