ECCE @ EIC Software: G4GMocrenFileSceneHandler Class Reference
G4GMocrenFileSceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/gMocren/include/G4GMocrenFileSceneHandler.hh>
Classes
class Detector
class Index3D
Public Member Functions
G4GMocrenFileSceneHandler (G4GMocrenFile &system, G4GMocrenMessenger &messenger, const G4String &name="")
virtual ~G4GMocrenFileSceneHandler ()
void AddPrimitive (const G4Polyline &line)
void AddPrimitive (const G4Polyhedron &p)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polymarker &polymarker)
void AddPrimitive (const G4Scale &scale)
virtual void BeginModeling ()
virtual void EndModeling ()
virtual void BeginPrimitives (const G4Transform3D &objectTransformation)
virtual void EndPrimitives ()
void AddSolid (const G4Box &box)
void AddSolid (const G4Cons &cons)
void AddSolid (const G4Tubs &tubs)
void AddSolid (const G4Trd &trd)
void AddSolid (const G4Trap &trap)
void AddSolid (const G4Sphere &sphere)
void AddSolid (const G4Para &para)
void AddSolid (const G4Torus &torus)
void AddSolid (const G4Polycone &polycone)
void AddSolid (const G4Polyhedra &polyhedra)
void AddSolid (const G4Orb &orb)
void AddSolid (const G4Ellipsoid &ellipsoid)
void AddSolid (const G4TessellatedSolid &tess)
void AddSolid (const G4VSolid &solid)
void AddCompound (const G4VTrajectory &traj)
void AddCompound (const G4VHit &hit)
void AddCompound (const G4VDigi &hit)
void AddCompound (const G4THitsMap< G4double > &hits)
void AddCompound (const G4THitsMap< G4StatDouble > &hits)
void ClearTransientStore ()
void GFBeginModeling ()
void GFEndModeling ()
G4bool GFIsInModeling ()
G4bool IsSavingGdd (void)
void BeginSavingGdd (void)
void EndSavingGdd (void)
void SetGddFileName ()
G4GMocrenFile & GetSystem ()
const char * GetGddFileName ()
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
virtual void PostAddSolid ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Private Member Functions
void InitializeParameters ()
G4bool IsVisible ()
void AddDetector (const G4VSolid &solid)
void ExtractDetector ()
void GetNestedVolumeIndex (G4int, G4int[3])
Private Attributes
G4GMocrenFile & kSystem
G4GMocrenMessenger & kMessenger
G4GMocrenIO * kgMocrenIO
std::map< G4int, float > kModality
G4int kModalitySize [3]
G4bool kbSetModalityVoxelSize
G4bool kbModelingTrajectory
G4Transform3D kVolumeTrans3D
std::vector< Detector > kDetectors
G4ThreeVector kVolumeSize
G4ThreeVector kVoxelDimension
std::vector< G4String > kNestedVolumeNames
G4int kNestedVolumeDimension [3]
G4int kNestedVolumeDirAxis [3]
std::map< Index3D, float > kNestedModality
std::map< G4String, std::map
< Index3D, G4double > > kNestedHitsList
std::ofstream kGddDest
G4bool kFlagInModeling
G4bool kFlagSaving_g4_gdd
G4int kFlagParameterization
G4bool kFlagProcessedInteractiveScorer
char kGddDestDir [256]
char kGddFileName [256]
G4int kMaxFileNum
Static Private Attributes
static G4int kSceneIdCount = 0
Friends
class G4GMocrenFileViewer
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Detailed Description
Definition at line 53 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 53 of file G4GMocrenFileSceneHandler.hh
Constructor & Destructor Documentation
G4GMocrenFileSceneHandler::G4GMocrenFileSceneHandler (G4GMocrenFile & system, G4GMocrenMessenger & messenger, const G4String & name = "")
Definition at line 121 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 121 of file G4GMocrenFileSceneHandler.cc
References DEFAULT_GDD_FILE_NAME, FatalException, FR_MAX_FILE_NUM, G4Exception(), InitializeParameters(), kGddDestDir, kGddFileName, and kMaxFileNum.
G4GMocrenFileSceneHandler::~G4GMocrenFileSceneHandler () virtual
Definition at line 176 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 176 of file G4GMocrenFileSceneHandler.cc
References G4VisManager::confirmations, G4cout, G4endl, G4VisManager::GetVerbosity(), GFDEBUG, GFEndModeling(), kGddDest, and kgMocrenIO.
Member Function Documentation
void G4GMocrenFileSceneHandler::AddCompound (const G4VTrajectory & traj) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1597 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1597 of file G4GMocrenFileSceneHandler.cc
References G4VSceneHandler::AddCompound(), G4VTrajectory::DrawTrajectory(), FatalException, G4VSceneHandler::fpModel, G4cout, G4endl, G4Exception(), G4VTrajectory::GetCharge(), G4TrajectoriesModel::GetCurrentTrajectory(), G4VTrajectory::GetInitialMomentum(), G4VTrajectory::GetParticleName(), G4VTrajectory::GetPoint(), G4VTrajectory::GetPointEntries(), G4VTrajectoryPoint::GetPosition(), G4VTrajectory::GetTrackID(), GFDEBUG_TRK, and kbModelingTrajectory.
void G4GMocrenFileSceneHandler::AddCompound (const G4VHit & hit) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1637 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1637 of file G4GMocrenFileSceneHandler.cc
References G4VSceneHandler::AddCompound(), G4VHit::CreateAttValues(), FatalException, G4cout, G4endl, G4Exception(), G4GMocrenMessenger::getHitNames(), GFDEBUG_HIT, hits(), kMessenger, and kNestedHitsList.
void G4GMocrenFileSceneHandler::AddCompound (const G4VDigi & hit) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1737 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1737 of file G4GMocrenFileSceneHandler.cc
References G4VSceneHandler::AddCompound(), G4cout, G4endl, and GFDEBUG_DIGI.
void G4GMocrenFileSceneHandler::AddCompound (const G4THitsMap< G4double > & hits) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1742 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1742 of file G4GMocrenFileSceneHandler.cc
References G4cout, G4endl, G4GMocrenMessenger::getHitScorerNames(), G4VTHitsMap< T, Map_t >::GetMap(), G4VSceneHandler::GetName(), GetNestedVolumeIndex(), GFDEBUG_HIT, hits(), incremental_prev_tag::idx, kMessenger, kNestedHitsList, and kNestedVolumeDimension.
void G4GMocrenFileSceneHandler::AddCompound (const G4THitsMap< G4StatDouble > & hits) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1814 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1814 of file G4GMocrenFileSceneHandler.cc
References G4cout, G4endl, G4GMocrenMessenger::getHitScorerNames(), G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >::GetMap(), G4VSceneHandler::GetName(), GetNestedVolumeIndex(), GFDEBUG_HIT, hits(), incremental_prev_tag::idx, kMessenger, kNestedHitsList, and kNestedVolumeDimension.
void G4GMocrenFileSceneHandler::AddDetector (const G4VSolid & solid) private
Definition at line 1918 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1918 of file G4GMocrenFileSceneHandler.cc
References G4GMocrenFileSceneHandler::Detector::color, color(), G4VSolid::CreatePolyhedron(), G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpModel, G4cout, G4endl, G4Colour::GetBlue(), G4VisAttributes::GetColor(), G4PhysicalVolumeModel::GetCurrentLV(), G4Colour::GetGreen(), G4VSceneHandler::GetModel(), G4VSolid::GetName(), G4Colour::GetRed(), G4LogicalVolume::GetVisAttributes(), GFDEBUG_DET, kDetectors, G4GMocrenFileSceneHandler::Detector::name, G4GMocrenFileSceneHandler::Detector::polyhedron, return(), and G4GMocrenFileSceneHandler::Detector::transform3D.
Referenced by AddSolid().
void G4GMocrenFileSceneHandler::AddPrimitive (const G4Polyline & line) virtual
Implements G4VSceneHandler.
Definition at line 543 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 543 of file G4GMocrenFileSceneHandler.cc
References G4GMocrenIO::addTrack(), color(), G4VisManager::confirmations, FatalException, G4VSceneHandler::fpModel, G4VSceneHandler::fProcessing2D, G4cout, G4endl, G4Exception(), G4Colour::GetBlue(), G4VisAttributes::GetColor(), G4Colour::GetGreen(), G4Colour::GetRed(), HepGeom::Transform3D::getRotation(), HepGeom::Transform3D::getTranslation(), G4VisManager::GetVerbosity(), G4Visible::GetVisAttributes(), GFBeginModeling(), GFDEBUG, GFDEBUG_TRK, CLHEP::HepRotation::inverse(), JustWarning, kbModelingTrajectory, kgMocrenIO, kVolumeTrans3D, MAX_NUM_TRAJECTORIES, CLHEP::Hep3Vector::transform(), and CLHEP::Hep3Vector::x().
void G4GMocrenFileSceneHandler::AddPrimitive (const G4Polyhedron & p) virtual
Implements G4VSceneHandler.
Definition at line 720 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 720 of file G4GMocrenFileSceneHandler.cc
References G4VisManager::confirmations, f, G4VSceneHandler::fpModel, G4VSceneHandler::fProcessing2D, G4cout, G4endl, G4Exception(), G4PhysicalVolumeModel::GetCurrentLV(), G4PhysicalVolumeModel::GetCurrentPV(), G4VSolid::GetEntityType(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), HepPolyhedron::GetNextVertexIndex(), HepPolyhedron::GetNoFacets(), G4LogicalVolume::GetSolid(), G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, and JustWarning.
void G4GMocrenFileSceneHandler::AddPrimitive (const G4Text & text) virtual
Implements G4VSceneHandler.
Definition at line 635 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 635 of file G4GMocrenFileSceneHandler.cc
References G4VisManager::confirmations, G4VSceneHandler::fProcessing2D, G4cout, G4endl, G4Exception(), G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, and JustWarning.
void G4GMocrenFileSceneHandler::AddPrimitive (const G4Circle & mark_circle) virtual
Implements G4VSceneHandler.
Definition at line 663 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 663 of file G4GMocrenFileSceneHandler.cc
References G4VisManager::confirmations, G4VSceneHandler::fProcessing2D, G4cout, G4endl, G4Exception(), G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, and JustWarning.
void G4GMocrenFileSceneHandler::AddPrimitive (const G4Square & mark_square) virtual
Implements G4VSceneHandler.
Definition at line 692 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 692 of file G4GMocrenFileSceneHandler.cc
References G4VisManager::confirmations, G4VSceneHandler::fProcessing2D, G4cout, G4endl, G4Exception(), G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, and JustWarning.
void G4GMocrenFileSceneHandler::AddPrimitive (const G4Polymarker & polymarker) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 74 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 74 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4GMocrenFileSceneHandler::AddPrimitive (const G4Scale & scale) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 76 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4GMocrenFileSceneHandler::AddSolid (const G4Box & box) virtual
Reimplemented from G4VSceneHandler.
Definition at line 839 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 839 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), cm, cm3, G4VNestedParameterisation::ComputeDimensions(), G4PhantomParameterisation::ComputeMaterial(), G4VNestedParameterisation::ComputeMaterial(), G4VNestedParameterisation::ComputeTransformation(), G4VisManager::confirmations, G4Box::CreatePolyhedron(), FatalException, G4ScoringManager::FindMesh(), G4VSceneHandler::fObjectTransformation, G4VSceneHandler::fpModel, Acts::UnitConstants::g, G4cout, G4endl, G4Exception(), G4VPhysicalVolume::GetCopyNo(), G4PhysicalVolumeModel::GetCurrentDepth(), G4PhysicalVolumeModel::GetCurrentMaterial(), G4PhysicalVolumeModel::GetCurrentPV(), G4LogicalVolume::GetDaughter(), G4Material::GetDensity(), G4PhysicalVolumeModel::GetDrawnPVPath(), G4GMocrenMessenger::getDrawVolumeGrid(), G4VPhysicalVolume::GetLogicalVolume(), G4VSceneHandler::GetModel(), G4VPhysicalVolume::GetMultiplicity(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4VSceneHandler::GetName(), HepPolyhedron::GetNextEdge(), G4LogicalVolume::GetNoDaughters(), G4PhantomParameterisation::GetNoVoxelX(), G4PhantomParameterisation::GetNoVoxelY(), G4PhantomParameterisation::GetNoVoxelZ(), G4VScoringMesh::GetNumberOfSegments(), G4VPhysicalVolume::GetObjectTranslation(), G4VPhysicalVolume::GetParameterisation(), G4VPhysicalVolume::GetReplicationData(), HepGeom::Transform3D::getRotation(), G4VScoringMesh::GetRotationMatrix(), G4ScoringManager::GetScoringManager(), G4VScoringMesh::GetSize(), G4LogicalVolume::GetSolid(), G4PhysicalVolumeModel::GetTopPhysicalVolume(), G4VScoringMesh::GetTranslation(), HepGeom::Transform3D::getTranslation(), G4VisManager::GetVerbosity(), G4GMocrenMessenger::getVolumeName(), G4PhantomParameterisation::GetVoxelHalfX(), G4PhantomParameterisation::GetVoxelHalfY(), G4PhantomParameterisation::GetVoxelHalfZ(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), GFBeginModeling(), GFDEBUG, GFDEBUG_DET, incremental_prev_tag::idx, CLHEP::HepRotation::inverse(), CLHEP::HepRotation::isIdentity(), G4VPVParameterisation::IsNested(), G4VPhysicalVolume::IsParameterised(), G4VPhysicalVolume::IsReplicated(), IsVisible(), kbSetModalityVoxelSize, kFlagParameterization, kFlagProcessedInteractiveScorer, kgMocrenIO, kMessenger, kNestedModality, kNestedVolumeDimension, kNestedVolumeDirAxis, kNestedVolumeNames, kVolumeSize, kVolumeTrans3D, kVoxelDimension, kXAxis, kYAxis, kZAxis, mat, mm, n1, offset, pi, rad, return(), CLHEP::Hep3Vector::set(), G4GMocrenIO::setVoxelSpacing(), HepPolyhedron::Transform(), v1, v2, width, CLHEP::Hep3Vector::x(), HepGeom::BasicVector3D< T >::x(), CLHEP::Hep3Vector::y(), HepGeom::BasicVector3D< T >::y(), CLHEP::Hep3Vector::z(), and HepGeom::BasicVector3D< T >::z().
void G4GMocrenFileSceneHandler::AddSolid (const G4Cons & cons) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1465 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1465 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), G4VisManager::confirmations, G4cout, G4endl, G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, IsVisible(), and return().
void G4GMocrenFileSceneHandler::AddSolid (const G4Tubs & tubs) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1422 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1422 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), G4VisManager::confirmations, G4Tubs::CreatePolyhedron(), G4VSceneHandler::fpModel, G4cout, G4endl, G4PhysicalVolumeModel::GetCurrentMaterial(), G4VSceneHandler::GetModel(), G4VSolid::GetName(), G4Material::GetName(), HepPolyhedron::GetNoVertices(), G4VisManager::GetVerbosity(), HepPolyhedron::GetVertex(), GFBeginModeling(), GFDEBUG, GFDEBUG_DET, IsVisible(), mat, return(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4GMocrenFileSceneHandler::AddSolid (const G4Trd & trd) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1483 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1483 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), G4VisManager::confirmations, G4cout, G4endl, G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, IsVisible(), and return().
void G4GMocrenFileSceneHandler::AddSolid (const G4Trap & trap) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1538 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1538 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), G4VisManager::confirmations, G4cout, G4endl, G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, IsVisible(), and return().
void G4GMocrenFileSceneHandler::AddSolid (const G4Sphere & sphere) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1502 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1502 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), G4VisManager::confirmations, G4cout, G4endl, G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, IsVisible(), and return().
void G4GMocrenFileSceneHandler::AddSolid (const G4Para & para) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1520 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1520 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), G4VisManager::confirmations, G4cout, G4endl, G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, IsVisible(), and return().
void G4GMocrenFileSceneHandler::AddSolid (const G4Torus & torus) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1557 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1557 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), G4VisManager::confirmations, G4cout, G4endl, G4VisManager::GetVerbosity(), GFBeginModeling(), GFDEBUG, IsVisible(), and return().
void G4GMocrenFileSceneHandler::AddSolid (const G4Polycone & polycone) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 93 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 93 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4GMocrenFileSceneHandler::AddSolid (const G4Polyhedra & polyhedra) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 96 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 96 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4GMocrenFileSceneHandler::AddSolid (const G4Orb & orb) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 99 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 99 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4GMocrenFileSceneHandler::AddSolid (const G4Ellipsoid & ellipsoid) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 102 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 102 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4GMocrenFileSceneHandler::AddSolid (const G4TessellatedSolid & tess) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 105 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 105 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4GMocrenFileSceneHandler::AddSolid (const G4VSolid & solid) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1576 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1576 of file G4GMocrenFileSceneHandler.cc
References AddDetector(), G4VSceneHandler::AddSolid(), GFBeginModeling(), IsVisible(), and return().
virtual void G4GMocrenFileSceneHandler::BeginModeling () inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 79 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 79 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::BeginModeling().
void G4GMocrenFileSceneHandler::BeginPrimitives (const G4Transform3D & objectTransformation) virtual
Reimplemented from G4VSceneHandler.
Definition at line 814 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 814 of file G4GMocrenFileSceneHandler.cc
References G4VSceneHandler::BeginPrimitives(), G4VisManager::confirmations, G4cout, G4endl, G4VisManager::GetVerbosity(), GFBeginModeling(), and GFDEBUG.
void G4GMocrenFileSceneHandler::BeginSavingGdd (void)
Definition at line 281 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 281 of file G4GMocrenFileSceneHandler.cc
References G4GMocrenIO::clearDetector(), G4GMocrenIO::clearDoseDistAll(), G4GMocrenIO::clearROIAll(), G4GMocrenIO::clearTracks(), G4VisManager::confirmations, G4cout, G4endl, G4GMocrenFileCTtoDensityMap::GetDensity(), G4GMocrenFileCTtoDensityMap::GetMaxCT(), G4GMocrenFileCTtoDensityMap::GetMinCT(), G4VisManager::GetVerbosity(), GFDEBUG, IsSavingGdd(), kDetectors, kFlagSaving_g4_gdd, kgMocrenIO, kNestedHitsList, kNestedVolumeNames, SetGddFileName(), G4GMocrenIO::setModalityImageDensityMap(), and G4GMocrenIO::setModalityImageMinMax().
Referenced by GFBeginModeling().
void G4GMocrenFileSceneHandler::ClearTransientStore () virtual
Reimplemented from G4VSceneHandler.
Definition at line 1905 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1905 of file G4GMocrenFileSceneHandler.cc
References G4VSceneHandler::fpViewer.
virtual void G4GMocrenFileSceneHandler::EndModeling () inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 80 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 80 of file G4GMocrenFileSceneHandler.hh
References G4VSceneHandler::EndModeling().
void G4GMocrenFileSceneHandler::EndPrimitives () virtual
Reimplemented from G4VSceneHandler.
Definition at line 827 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 827 of file G4GMocrenFileSceneHandler.cc
References G4VisManager::confirmations, G4VSceneHandler::EndPrimitives(), G4cout, G4endl, G4VisManager::GetVerbosity(), and GFDEBUG.
void G4GMocrenFileSceneHandler::EndSavingGdd (void)
Definition at line 352 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 352 of file G4GMocrenFileSceneHandler.cc
References G4GMocrenIO::addTrack(), G4VisManager::confirmations, G4GMocrenIO::convertDensityToHU(), DBL_MAX, ExtractDetector(), G4cout, G4endl, HepGeom::Transform3D::getRotation(), HepGeom::Transform3D::getTranslation(), G4VisManager::GetVerbosity(), GFDEBUG, GFDEBUG_DET, incremental_prev_tag::idx, CLHEP::HepRotation::inverse(), IsSavingGdd(), kFlagSaving_g4_gdd, kGddDest, kGddFileName, kgMocrenIO, kModalitySize, kNestedHitsList, kNestedModality, kVolumeSize, kVolumeTrans3D, kVoxelDimension, n, G4GMocrenIO::newDoseDist(), scale, G4GMocrenIO::setDoseDist(), G4GMocrenIO::setDoseDistMinMax(), G4GMocrenIO::setDoseDistName(), G4GMocrenIO::setDoseDistScale(), G4GMocrenIO::setDoseDistSize(), G4GMocrenIO::setDoseDistUnit(), G4GMocrenIO::setModalityImage(), G4GMocrenIO::setModalityImageSize(), G4GMocrenIO::storeData(), CLHEP::Hep3Vector::transform(), G4GMocrenIO::translateDetector(), G4GMocrenIO::translateTracks(), Acts::Test::values, x, xmax, y, ymax, and z.
Referenced by GFEndModeling().
void G4GMocrenFileSceneHandler::ExtractDetector () private
Definition at line 1962 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1962 of file G4GMocrenFileSceneHandler.cc
References G4GMocrenIO::addDetector(), G4cout, G4endl, HepPolyhedron::GetNextEdge(), GFDEBUG_DET, HepGeom::Transform3D::inverse(), kDetectors, kgMocrenIO, kVolumeTrans3D, mm, HepPolyhedron::Transform(), v1, v2, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
Referenced by EndSavingGdd().
const char* G4GMocrenFileSceneHandler::GetGddFileName () inline
Definition at line 129 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 129 of file G4GMocrenFileSceneHandler.hh
References kGddFileName.
Referenced by G4GMocrenFileViewer::G4GMocrenFileViewer(), and G4GMocrenFileViewer::ShowView().
void G4GMocrenFileSceneHandler::GetNestedVolumeIndex (G4int _idx, G4int _idx3d[3]) private
Definition at line 2017 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 2017 of file G4GMocrenFileSceneHandler.cc
References kFlagParameterization, kNestedVolumeDimension, kNestedVolumeDirAxis, and Acts::PrimitivesVisualization::plane.
Referenced by AddCompound().
G4GMocrenFile& G4GMocrenFileSceneHandler::GetSystem () inline
Definition at line 128 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 128 of file G4GMocrenFileSceneHandler.hh
References kSystem.
void G4GMocrenFileSceneHandler::GFBeginModeling (void)
Definition at line 510 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 510 of file G4GMocrenFileSceneHandler.cc
References G4VSceneHandler::BeginModeling(), BeginSavingGdd(), G4VisManager::confirmations, G4cout, G4endl, G4Scene::GetEndOfEventModelList(), G4VSceneHandler::GetScene(), G4VisManager::GetVerbosity(), GFDEBUG, GFDEBUG_HIT, GFIsInModeling(), kFlagInModeling, and true.
Referenced by AddPrimitive(), AddSolid(), BeginPrimitives(), G4GMocrenFileViewer::ClearView(), and G4GMocrenFileViewer::DrawView().
void G4GMocrenFileSceneHandler::GFEndModeling ()
Definition at line 787 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 787 of file G4GMocrenFileSceneHandler.cc
References G4VisManager::confirmations, G4VSceneHandler::EndModeling(), EndSavingGdd(), false, G4cout, G4endl, G4VisManager::GetVerbosity(), GFDEBUG, GFIsInModeling(), and kFlagInModeling.
Referenced by G4GMocrenFileViewer::ShowView(), and ~G4GMocrenFileSceneHandler().
G4bool G4GMocrenFileSceneHandler::GFIsInModeling () inline
Definition at line 121 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 121 of file G4GMocrenFileSceneHandler.hh
References kFlagInModeling.
Referenced by GFBeginModeling(), GFEndModeling(), and G4GMocrenFileViewer::ShowView().
void G4GMocrenFileSceneHandler::InitializeParameters () private
Definition at line 191 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 191 of file G4GMocrenFileSceneHandler.cc
References kbSetModalityVoxelSize, kModalitySize, kNestedVolumeDimension, and kNestedVolumeDirAxis.
Referenced by G4GMocrenFileSceneHandler().
G4bool G4GMocrenFileSceneHandler::IsSavingGdd (void) inline
Definition at line 123 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 123 of file G4GMocrenFileSceneHandler.hh
References kFlagSaving_g4_gdd.
Referenced by BeginSavingGdd(), and EndSavingGdd().
G4bool G4GMocrenFileSceneHandler::IsVisible (void) private
Definition at line 1887 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1887 of file G4GMocrenFileSceneHandler.cc
References G4VSceneHandler::fpViewer, G4VSceneHandler::fpVisAttribs, G4VViewer::GetApplicableVisAttributes(), G4VisAttributes::IsVisible(), true, and visibility().
Referenced by AddSolid().
void G4GMocrenFileSceneHandler::SetGddFileName ()
Definition at line 206 of file G4GMocrenFileSceneHandler.cc.
View newest version in sPHENIX GitHub at line 206 of file G4GMocrenFileSceneHandler.cc
References DEFAULT_GDD_FILE_NAME, INPUTHEPMC::filename, fin, G4cout, G4endl, GDD_FILE_HEADER, G4VisManager::GetVerbosity(), GFDEBUG, kGddDestDir, kGddFileName, kMaxFileNum, MAX_NUM_TRAJECTORIES, and G4VisManager::warnings.
Referenced by BeginSavingGdd().
Friends And Related Function Documentation
friend class G4GMocrenFileViewer friend
Definition at line 55 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 55 of file G4GMocrenFileSceneHandler.hh
Member Data Documentation
G4bool G4GMocrenFileSceneHandler::kbModelingTrajectory private
Definition at line 155 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 155 of file G4GMocrenFileSceneHandler.hh
Referenced by AddCompound(), and AddPrimitive().
G4bool G4GMocrenFileSceneHandler::kbSetModalityVoxelSize private
Definition at line 154 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GMocrenFileSceneHandler.hh
Referenced by AddSolid(), and InitializeParameters().
std::vector<Detector> G4GMocrenFileSceneHandler::kDetectors private
Definition at line 172 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 172 of file G4GMocrenFileSceneHandler.hh
Referenced by AddDetector(), BeginSavingGdd(), and ExtractDetector().
G4bool G4GMocrenFileSceneHandler::kFlagInModeling private
Definition at line 201 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 201 of file G4GMocrenFileSceneHandler.hh
Referenced by G4GMocrenFileViewer::ClearView(), GFBeginModeling(), GFEndModeling(), and GFIsInModeling().
G4int G4GMocrenFileSceneHandler::kFlagParameterization private
Definition at line 212 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 212 of file G4GMocrenFileSceneHandler.hh
Referenced by AddSolid(), and GetNestedVolumeIndex().
G4bool G4GMocrenFileSceneHandler::kFlagProcessedInteractiveScorer private
Definition at line 215 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 215 of file G4GMocrenFileSceneHandler.hh
Referenced by AddSolid().
G4bool G4GMocrenFileSceneHandler::kFlagSaving_g4_gdd private
Definition at line 210 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 210 of file G4GMocrenFileSceneHandler.hh
Referenced by BeginSavingGdd(), EndSavingGdd(), and IsSavingGdd().
std::ofstream G4GMocrenFileSceneHandler::kGddDest private
Definition at line 200 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 200 of file G4GMocrenFileSceneHandler.hh
Referenced by EndSavingGdd(), and ~G4GMocrenFileSceneHandler().
char G4GMocrenFileSceneHandler::kGddDestDir[256] private
Definition at line 217 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 217 of file G4GMocrenFileSceneHandler.hh
Referenced by G4GMocrenFileSceneHandler(), and SetGddFileName().
char G4GMocrenFileSceneHandler::kGddFileName[256] private
Definition at line 218 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 218 of file G4GMocrenFileSceneHandler.hh
Referenced by EndSavingGdd(), G4GMocrenFileSceneHandler(), GetGddFileName(), and SetGddFileName().
G4GMocrenIO* G4GMocrenFileSceneHandler::kgMocrenIO private
Definition at line 149 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 149 of file G4GMocrenFileSceneHandler.hh
Referenced by AddPrimitive(), AddSolid(), BeginSavingGdd(), EndSavingGdd(), ExtractDetector(), and ~G4GMocrenFileSceneHandler().
G4int G4GMocrenFileSceneHandler::kMaxFileNum private
Definition at line 219 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 219 of file G4GMocrenFileSceneHandler.hh
Referenced by G4GMocrenFileSceneHandler(), and SetGddFileName().
G4GMocrenMessenger& G4GMocrenFileSceneHandler::kMessenger private
Definition at line 148 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 148 of file G4GMocrenFileSceneHandler.hh
Referenced by AddCompound(), and AddSolid().
std::map<G4int, float> G4GMocrenFileSceneHandler::kModality private
Definition at line 151 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 151 of file G4GMocrenFileSceneHandler.hh
G4int G4GMocrenFileSceneHandler::kModalitySize[3] private
Definition at line 152 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 152 of file G4GMocrenFileSceneHandler.hh
Referenced by EndSavingGdd(), and InitializeParameters().
std::map<G4String, std::map<Index3D, G4double> > G4GMocrenFileSceneHandler::kNestedHitsList private
Definition at line 197 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 197 of file G4GMocrenFileSceneHandler.hh
Referenced by AddCompound(), BeginSavingGdd(), and EndSavingGdd().
std::map<Index3D, float> G4GMocrenFileSceneHandler::kNestedModality private
Definition at line 195 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 195 of file G4GMocrenFileSceneHandler.hh
Referenced by AddSolid(), and EndSavingGdd().
G4int G4GMocrenFileSceneHandler::kNestedVolumeDimension[3] private
Definition at line 176 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 176 of file G4GMocrenFileSceneHandler.hh
Referenced by AddCompound(), AddSolid(), GetNestedVolumeIndex(), and InitializeParameters().
G4int G4GMocrenFileSceneHandler::kNestedVolumeDirAxis[3] private
Definition at line 177 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 177 of file G4GMocrenFileSceneHandler.hh
Referenced by AddSolid(), GetNestedVolumeIndex(), and InitializeParameters().
std::vector<G4String> G4GMocrenFileSceneHandler::kNestedVolumeNames private
Definition at line 175 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 175 of file G4GMocrenFileSceneHandler.hh
Referenced by AddSolid(), and BeginSavingGdd().
G4int G4GMocrenFileSceneHandler::kSceneIdCount = 0 static private
Definition at line 157 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 157 of file G4GMocrenFileSceneHandler.hh
G4GMocrenFile& G4GMocrenFileSceneHandler::kSystem private
Definition at line 147 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 147 of file G4GMocrenFileSceneHandler.hh
Referenced by GetSystem().
G4ThreeVector G4GMocrenFileSceneHandler::kVolumeSize private
Definition at line 173 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 173 of file G4GMocrenFileSceneHandler.hh
Referenced by AddSolid(), and EndSavingGdd().
G4Transform3D G4GMocrenFileSceneHandler::kVolumeTrans3D private
Definition at line 160 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 160 of file G4GMocrenFileSceneHandler.hh
Referenced by AddPrimitive(), AddSolid(), EndSavingGdd(), and ExtractDetector().
G4ThreeVector G4GMocrenFileSceneHandler::kVoxelDimension private
Definition at line 174 of file G4GMocrenFileSceneHandler.hh.
View newest version in sPHENIX GitHub at line 174 of file G4GMocrenFileSceneHandler.hh
Referenced by AddSolid(), and EndSavingGdd().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/gMocren/include/G4GMocrenFileSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/gMocren/src/G4GMocrenFileSceneHandler.cc