ECCE @ EIC Software: G4Trajectory Class Reference
G4Trajectory Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4Trajectory.hh>
Public Member Functions
G4Trajectory ()
G4Trajectory (const G4Track *aTrack)
G4Trajectory (G4Trajectory &)
virtual ~G4Trajectory ()
void * operator new (size_t)
void operator delete (void *)
G4int operator== (const G4Trajectory &r) const
G4int GetTrackID () const
G4int GetParentID () const
G4String GetParticleName () const
G4double GetCharge () const
G4int GetPDGEncoding () const
G4double GetInitialKineticEnergy () const
G4ThreeVector GetInitialMomentum () const
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void DrawTrajectory () const
virtual void AppendStep (const G4Step *aStep)
virtual G4int GetPointEntries () const
virtual G4VTrajectoryPoint * GetPoint (G4int i) const
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4ParticleDefinition * GetParticleDefinition ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
Private Types
using TrajectoryPointContainer = std::vector< G4VTrajectoryPoint * >
Private Attributes
TrajectoryPointContainer * positionRecord
G4int fTrackID
G4int fParentID
G4int PDGEncoding
G4double PDGCharge
G4String ParticleName
G4double initialKineticEnergy
G4ThreeVector initialMomentum
Detailed Description
Definition at line 62 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 62 of file G4Trajectory.hh
Member Typedef Documentation
using G4Trajectory::TrajectoryPointContainer = std::vector<G4VTrajectoryPoint*> private
Definition at line 66 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 66 of file G4Trajectory.hh
Constructor & Destructor Documentation
G4Trajectory::G4Trajectory ()
Definition at line 60 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 60 of file G4Trajectory.cc
G4Trajectory::G4Trajectory (const G4Track * aTrack)
Definition at line 66 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 66 of file G4Trajectory.cc
References fParentID, fTrackID, G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4Track::GetMomentum(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4Track::GetPosition(), G4Track::GetTrackID(), initialKineticEnergy, initialMomentum, ParticleName, PDGCharge, PDGEncoding, and positionRecord.
G4Trajectory::G4Trajectory (G4Trajectory & right)
Definition at line 81 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 81 of file G4Trajectory.cc
References fParentID, fTrackID, initialKineticEnergy, initialMomentum, ParticleName, PDGCharge, PDGEncoding, and positionRecord.
G4Trajectory::~G4Trajectory () virtual
Definition at line 99 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 99 of file G4Trajectory.cc
References positionRecord.
Member Function Documentation
void G4Trajectory::AppendStep (const G4Step * aStep) virtual
Implements G4VTrajectory.
Reimplemented in G4RichTrajectory.
Definition at line 205 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 205 of file G4Trajectory.cc
References G4Step::GetPostStepPoint(), and positionRecord.
std::vector< G4AttValue > * G4Trajectory::CreateAttValues () const virtual
Reimplemented from G4VTrajectory.
Reimplemented in G4RichTrajectory.
Definition at line 168 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 168 of file G4Trajectory.cc
References G4UIcommand::ConvertToString(), fParentID, fTrackID, G4BestUnit, G4cout, GetAttDefs(), GetPointEntries(), initialKineticEnergy, initialMomentum, CLHEP::Hep3Vector::mag(), ParticleName, PDGCharge, PDGEncoding, and Acts::Test::values.
Referenced by G4RichTrajectory::CreateAttValues().
void G4Trajectory::DrawTrajectory () const virtual
Reimplemented from G4VTrajectory.
Reimplemented in G4RichTrajectory, and LXeTrajectory.
Definition at line 118 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 118 of file G4Trajectory.cc
References G4VTrajectory::DrawTrajectory().
Referenced by DMXEventAction::drawTracks().
const std::map< G4String, G4AttDef > * G4Trajectory::GetAttDefs () const virtual
Reimplemented from G4VTrajectory.
Reimplemented in G4RichTrajectory.
Definition at line 125 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 125 of file G4Trajectory.cc
References G4AttDefStore::GetInstance().
Referenced by CreateAttValues(), G4RichTrajectory::GetAttDefs(), G4VisCommandList::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
G4double G4Trajectory::GetCharge () const inline virtual
Implements G4VTrajectory.
Definition at line 93 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 93 of file G4Trajectory.hh
References PDGCharge.
Referenced by DMXEventAction::drawTracks().
G4double G4Trajectory::GetInitialKineticEnergy () const inline
Definition at line 97 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 97 of file G4Trajectory.hh
References initialKineticEnergy.
G4ThreeVector G4Trajectory::GetInitialMomentum () const inline virtual
Implements G4VTrajectory.
Definition at line 99 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 99 of file G4Trajectory.hh
References initialMomentum.
G4int G4Trajectory::GetParentID () const inline virtual
Implements G4VTrajectory.
Definition at line 89 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 89 of file G4Trajectory.hh
References fParentID.
G4ParticleDefinition * G4Trajectory::GetParticleDefinition (void)
Definition at line 211 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 211 of file G4Trajectory.cc
References G4ParticleTable::GetParticleTable(), and ParticleName.
G4String G4Trajectory::GetParticleName () const inline virtual
Implements G4VTrajectory.
Definition at line 91 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 91 of file G4Trajectory.hh
References ParticleName.
Referenced by DMXEventAction::drawTracks(), and LXeEventAction::EndOfEventAction().
G4int G4Trajectory::GetPDGEncoding () const inline virtual
Implements G4VTrajectory.
Definition at line 95 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 95 of file G4Trajectory.hh
References PDGEncoding.
virtual G4VTrajectoryPoint* G4Trajectory::GetPoint (G4int i) const inline virtual
Implements G4VTrajectory.
Reimplemented in G4RichTrajectory.
Definition at line 108 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 108 of file G4Trajectory.hh
References positionRecord.
Referenced by LXeTrajectory::DrawTrajectory().
virtual G4int G4Trajectory::GetPointEntries () const inline virtual
Implements G4VTrajectory.
Reimplemented in G4RichTrajectory.
Definition at line 107 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 107 of file G4Trajectory.hh
References positionRecord.
Referenced by CreateAttValues(), LXeTrajectory::DrawTrajectory(), and MergeTrajectory().
G4int G4Trajectory::GetTrackID () const inline virtual
Implements G4VTrajectory.
Definition at line 87 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 87 of file G4Trajectory.hh
References fTrackID.
void G4Trajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) virtual
Implements G4VTrajectory.
Reimplemented in G4RichTrajectory.
Definition at line 216 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 216 of file G4Trajectory.cc
References GetPointEntries(), and positionRecord.
void G4Trajectory::operator delete (void * aTrajectory) inline
Definition at line 140 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 140 of file G4Trajectory.hh
References aTrajectoryAllocator().
void * G4Trajectory::operator new (size_t) inline
Definition at line 133 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 133 of file G4Trajectory.hh
References aTrajectoryAllocator().
G4int G4Trajectory::operator== (const G4Trajectory & r) const inline
Definition at line 83 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 83 of file G4Trajectory.hh
void G4Trajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented from G4VTrajectory.
Reimplemented in G4RichTrajectory.
Definition at line 111 of file G4Trajectory.cc.
View newest version in sPHENIX GitHub at line 111 of file G4Trajectory.cc
References G4VTrajectory::ShowTrajectory().
Member Data Documentation
G4int G4Trajectory::fParentID private
Definition at line 122 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 122 of file G4Trajectory.hh
Referenced by CreateAttValues(), G4Trajectory(), and GetParentID().
G4int G4Trajectory::fTrackID private
Definition at line 121 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 121 of file G4Trajectory.hh
Referenced by CreateAttValues(), G4Trajectory(), and GetTrackID().
G4double G4Trajectory::initialKineticEnergy private
Definition at line 126 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 126 of file G4Trajectory.hh
Referenced by CreateAttValues(), G4Trajectory(), and GetInitialKineticEnergy().
G4ThreeVector G4Trajectory::initialMomentum private
Definition at line 127 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 127 of file G4Trajectory.hh
Referenced by CreateAttValues(), G4Trajectory(), and GetInitialMomentum().
G4String G4Trajectory::ParticleName private
Definition at line 125 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 125 of file G4Trajectory.hh
Referenced by CreateAttValues(), G4Trajectory(), GetParticleDefinition(), and GetParticleName().
G4double G4Trajectory::PDGCharge private
Definition at line 124 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 124 of file G4Trajectory.hh
Referenced by CreateAttValues(), G4Trajectory(), and GetCharge().
G4int G4Trajectory::PDGEncoding private
Definition at line 123 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 123 of file G4Trajectory.hh
Referenced by CreateAttValues(), G4Trajectory(), and GetPDGEncoding().
TrajectoryPointContainer* G4Trajectory::positionRecord private
Definition at line 120 of file G4Trajectory.hh.
View newest version in sPHENIX GitHub at line 120 of file G4Trajectory.hh
Referenced by AppendStep(), G4Trajectory(), GetPoint(), GetPointEntries(), MergeTrajectory(), and ~G4Trajectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4Trajectory.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4Trajectory.cc