ECCE @ EIC Software: G4GDMLParser Class Reference
G4GDMLParser Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLParser.hh>
Public Member Functions
G4GDMLParser ()
G4GDMLParser (G4GDMLReadStructure *)
G4GDMLParser (G4GDMLReadStructure *, G4GDMLWriteStructure *)
~G4GDMLParser ()
void Read (const G4String &filename, G4bool Validate=true)
void ReadModule (const G4String &filename, G4bool Validate=true)
void Write (const G4String &filename, const G4VPhysicalVolume *pvol=0, G4bool storeReferences=true, const G4String &SchemaLocation=G4GDML_DEFAULT_SCHEMALOCATION)
void Write (const G4String &filename, const G4LogicalVolume *lvol, G4bool storeReferences=true, const G4String &SchemaLocation=G4GDML_DEFAULT_SCHEMALOCATION)
G4LogicalVolume * ParseST (const G4String &name, G4Material *medium, G4Material *solid)
G4bool IsValid (const G4String &name) const
G4double GetConstant (const G4String &name) const
G4double GetVariable (const G4String &name) const
G4double GetQuantity (const G4String &name) const
G4ThreeVector GetPosition (const G4String &name) const
G4ThreeVector GetRotation (const G4String &name) const
G4ThreeVector GetScale (const G4String &name) const
G4GDMLMatrix GetMatrix (const G4String &name) const
G4LogicalVolume * GetVolume (const G4String &name) const
G4VPhysicalVolume * GetWorldVolume (const G4String &setupName="Default") const
G4GDMLAuxListType GetVolumeAuxiliaryInformation (G4LogicalVolume *lvol) const
const G4GDMLAuxMapType * GetAuxMap () const
const G4GDMLAuxListType * GetAuxList () const
void AddAuxiliary (G4GDMLAuxStructType myaux)
void StripNamePointers () const
void SetStripFlag (G4bool)
void SetOverlapCheck (G4bool)
void SetRegionExport (G4bool)
void SetEnergyCutsExport (G4bool)
void SetSDExport (G4bool)
G4int GetMaxExportLevel () const
void SetMaxExportLevel (G4int)
void Clear ()
void AddModule (const G4VPhysicalVolume *const physvol)
void AddModule (const G4int depth)
void SetAddPointerToName (G4bool set)
void AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume *const lvol)
Private Member Functions
void ImportRegions ()
void ExportRegions (G4bool storeReferences=true)
Private Attributes
G4GDMLEvaluator eval
G4GDMLReadStructure * reader
G4GDMLWriteStructure * writer
G4GDMLAuxListType * rlist
G4GDMLAuxListType * ullist
G4GDMLMessenger * messenger
G4bool urcode
G4bool uwcode
G4bool strip
G4bool rexp
Detailed Description
Definition at line 54 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 54 of file G4GDMLParser.hh
Constructor & Destructor Documentation
G4GDMLParser::G4GDMLParser ()
Definition at line 43 of file G4GDMLParser.cc.
View newest version in sPHENIX GitHub at line 43 of file G4GDMLParser.cc
References Initialize(), messenger, reader, and writer.
G4GDMLParser::G4GDMLParser (G4GDMLReadStructure * extr)
Definition at line 53 of file G4GDMLParser.cc.
View newest version in sPHENIX GitHub at line 53 of file G4GDMLParser.cc
References Initialize(), messenger, reader, and writer.
G4GDMLParser::G4GDMLParser (G4GDMLReadStructure * extr, G4GDMLWriteStructure * extw)
Definition at line 63 of file G4GDMLParser.cc.
View newest version in sPHENIX GitHub at line 63 of file G4GDMLParser.cc
References Initialize(), messenger, reader, and writer.
G4GDMLParser::~G4GDMLParser ()
Definition at line 74 of file G4GDMLParser.cc.
View newest version in sPHENIX GitHub at line 74 of file G4GDMLParser.cc
References messenger, reader, rlist, ullist, urcode, uwcode, and writer.
Member Function Documentation
void G4GDMLParser::AddAuxiliary (G4GDMLAuxStructType myaux) inline
Referenced by ExportRegions().
void G4GDMLParser::AddModule (const G4VPhysicalVolume *const physvol) inline
void G4GDMLParser::AddModule (const G4int depth) inline
void G4GDMLParser::AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume *const lvol) inline
void G4GDMLParser::Clear () inline
Referenced by G4GDMLMessenger::SetNewValue().
void G4GDMLParser::ExportRegions (G4bool storeReferences = true) private
Definition at line 193 of file G4GDMLParser.cc.
View newest version in sPHENIX GitHub at line 193 of file G4GDMLParser.cc
References AddAuxiliary(), G4String::contains(), G4GDMLEvaluator::ConvertToString(), eval, G4GDMLWrite::GenerateName(), G4RegionStore::GetInstance(), G4LogicalVolume::GetName(), G4ReflectionFactory::Instance(), G4ReflectionFactory::IsReflected(), reader, rlist, G4GDMLRead::StripName(), ullist, and writer.
const G4GDMLAuxListType* G4GDMLParser::GetAuxList () const inline
Referenced by ImportRegions(), and main().
const G4GDMLAuxMapType* G4GDMLParser::GetAuxMap () const inline
Referenced by Par02DetectorConstruction::Construct(), and G04DetectorConstruction::ConstructSDandField().
G4double G4GDMLParser::GetConstant (const G4String & name) const inline
G4GDMLMatrix G4GDMLParser::GetMatrix (const G4String & name) const inline
G4int G4GDMLParser::GetMaxExportLevel () const inline
G4ThreeVector G4GDMLParser::GetPosition (const G4String & name) const inline
Referenced by CexmcSetup::ReadTransforms().
G4double G4GDMLParser::GetQuantity (const G4String & name) const inline
G4ThreeVector G4GDMLParser::GetRotation (const G4String & name) const inline
Referenced by CexmcSetup::ReadTransforms().
G4ThreeVector G4GDMLParser::GetScale (const G4String & name) const inline
G4double G4GDMLParser::GetVariable (const G4String & name) const inline
G4LogicalVolume* G4GDMLParser::GetVolume (const G4String & name) const inline
G4GDMLAuxListType G4GDMLParser::GetVolumeAuxiliaryInformation (G4LogicalVolume * lvol) const inline
Referenced by main(), and CexmcSetup::SetupSpecialVolumes().
G4VPhysicalVolume* G4GDMLParser::GetWorldVolume (const G4String & setupName = "Default") const inline
Referenced by FW::Geant4::MMDetectorConstruction::Construct(), G04DetectorConstruction::Construct(), Par02DetectorConstruction::Construct(), G03DetectorConstruction::Construct(), G02DetectorConstruction::Construct(), CexmcSetup::Construct(), export_G4GDMLParser(), main(), and G4GDMLMessenger::SetNewValue().
void G4GDMLParser::ImportRegions () private
Definition at line 83 of file G4GDMLParser.cc.
View newest version in sPHENIX GitHub at line 83 of file G4GDMLParser.cc
References G4Region::AddRootLogicalVolume(), G4String::contains(), DBL_MAX, eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), GetAuxList(), G4UnitDefinition::GetCategory(), G4LogicalVolumeStore::GetInstance(), G4ReflectionFactory::GetReflectedLV(), G4UnitDefinition::GetValueOf(), G4LogicalVolumeStore::GetVolume(), G4ReflectionFactory::Instance(), G4ReflectionFactory::IsConstituent(), reader, G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4Region::SetUserLimits(), strip, and G4GDMLRead::StripName().
G4bool G4GDMLParser::IsValid (const G4String & name) const inline
G4LogicalVolume* G4GDMLParser::ParseST (const G4String & name, G4Material * medium, G4Material * solid) inline
Referenced by G02DetectorConstruction::Construct(), and export_G4GDMLParser().
void G4GDMLParser::Read (const G4String & filename, G4bool Validate = true) inline
Referenced by FW::Geant4::MMDetectorConstruction::Construct(), G03DetectorConstruction::Construct(), Par02DetectorConstruction::Construct(), G02DetectorConstruction::Construct(), CexmcSetup::Construct(), PHG4EICMvtxDetector::ConstructMvtx(), PHG4MvtxDetector::ConstructMvtx(), export_G4GDMLParser(), main(), and G4GDMLMessenger::SetNewValue().
void G4GDMLParser::ReadModule (const G4String & filename, G4bool Validate = true) inline
Referenced by export_G4GDMLParser().
void G4GDMLParser::SetAddPointerToName (G4bool set) inline
Referenced by G4GDMLMessenger::SetNewValue().
void G4GDMLParser::SetEnergyCutsExport (G4bool) inline
Referenced by G4GDMLMessenger::SetNewValue().
void G4GDMLParser::SetMaxExportLevel (G4int) inline
void G4GDMLParser::SetOverlapCheck (G4bool) inline
Referenced by BeastMagnetDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), and main().
void G4GDMLParser::SetRegionExport (G4bool) inline
Referenced by main(), and G4GDMLMessenger::SetNewValue().
void G4GDMLParser::SetSDExport (G4bool) inline
Referenced by G4GDMLMessenger::SetNewValue().
void G4GDMLParser::SetStripFlag (G4bool) inline
Referenced by G4GDMLMessenger::SetNewValue().
void G4GDMLParser::StripNamePointers () const inline
void G4GDMLParser::Write (const G4String & filename, const G4VPhysicalVolume * pvol = 0, G4bool storeReferences = true, const G4String & SchemaLocation = G4GDML_DEFAULT_SCHEMALOCATION) inline
Referenced by G03DetectorConstruction::Construct(), G02DetectorConstruction::Construct(), main(), and G4GDMLMessenger::SetNewValue().
void G4GDMLParser::Write (const G4String & filename, const G4LogicalVolume * lvol, G4bool storeReferences = true, const G4String & SchemaLocation = G4GDML_DEFAULT_SCHEMALOCATION) inline
Member Data Documentation
G4GDMLEvaluator G4GDMLParser::eval private
Definition at line 149 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 149 of file G4GDMLParser.hh
Referenced by ExportRegions(), and ImportRegions().
G4GDMLMessenger* G4GDMLParser::messenger private
Definition at line 153 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 153 of file G4GDMLParser.hh
Referenced by G4GDMLParser(), and ~G4GDMLParser().
G4GDMLReadStructure* G4GDMLParser::reader private
Definition at line 150 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 150 of file G4GDMLParser.hh
Referenced by ExportRegions(), G4GDMLParser(), ImportRegions(), and ~G4GDMLParser().
G4bool G4GDMLParser::rexp private
Definition at line 154 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GDMLParser.hh
G4GDMLAuxListType* G4GDMLParser::rlist private
Definition at line 152 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 152 of file G4GDMLParser.hh
Referenced by ExportRegions(), and ~G4GDMLParser().
G4bool G4GDMLParser::strip private
Definition at line 154 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GDMLParser.hh
Referenced by ImportRegions().
G4GDMLAuxListType * G4GDMLParser::ullist private
Definition at line 152 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 152 of file G4GDMLParser.hh
Referenced by ExportRegions(), and ~G4GDMLParser().
G4bool G4GDMLParser::urcode private
Definition at line 154 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GDMLParser.hh
Referenced by ~G4GDMLParser().
G4bool G4GDMLParser::uwcode private
Definition at line 154 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 154 of file G4GDMLParser.hh
Referenced by ~G4GDMLParser().
G4GDMLWriteStructure* G4GDMLParser::writer private
Definition at line 151 of file G4GDMLParser.hh.
View newest version in sPHENIX GitHub at line 151 of file G4GDMLParser.hh
Referenced by ExportRegions(), G4GDMLParser(), and ~G4GDMLParser().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLParser.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLParser.cc