ECCE @ EIC Software: G4RDCompositeEMDataSet Class Reference
G4RDCompositeEMDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDCompositeEMDataSet.hh>
Public Member Functions
G4RDCompositeEMDataSet (G4RDVDataSetAlgorithm *argAlgorithm, G4double eUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn, G4int zMin=1, G4int zMax=99)
virtual ~G4RDCompositeEMDataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4RDVEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4RDVEMDataSet *dataSet)
virtual size_t NumberOfComponents () const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *data, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int componentId) const
Public Member Functions inherited from G4RDVEMDataSet
G4RDVEMDataSet ()
virtual ~G4RDVEMDataSet ()
Private Member Functions
void CleanUpComponents (void)
G4RDCompositeEMDataSet ()
G4RDCompositeEMDataSet (const G4RDCompositeEMDataSet &copy)
G4RDCompositeEMDataSet & operator= (const G4RDCompositeEMDataSet &right)
Private Attributes
std::vector< G4RDVEMDataSet * > components
G4RDVDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
G4int minZ
G4int maxZ
Detailed Description
Definition at line 55 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 55 of file G4RDCompositeEMDataSet.hh
Constructor & Destructor Documentation
G4RDCompositeEMDataSet::G4RDCompositeEMDataSet (G4RDVDataSetAlgorithm * argAlgorithm, G4double eUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn, G4int zMin = 1, G4int zMax = 99)
Definition at line 42 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 42 of file G4RDCompositeEMDataSet.cc
References algorithm, FatalException, and G4Exception().
G4RDCompositeEMDataSet::~G4RDCompositeEMDataSet () virtual
Definition at line 61 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 61 of file G4RDCompositeEMDataSet.cc
References algorithm, and CleanUpComponents().
G4RDCompositeEMDataSet::G4RDCompositeEMDataSet () private
G4RDCompositeEMDataSet::G4RDCompositeEMDataSet (const G4RDCompositeEMDataSet & copy) private
Member Function Documentation
virtual void G4RDCompositeEMDataSet::AddComponent (G4RDVEMDataSet * dataSet) inline virtual
Implements G4RDVEMDataSet.
Definition at line 71 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RDCompositeEMDataSet.hh
References components.
Referenced by LoadData().
void G4RDCompositeEMDataSet::CleanUpComponents (void) private
Definition at line 157 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 157 of file G4RDCompositeEMDataSet.cc
References components.
Referenced by LoadData(), and ~G4RDCompositeEMDataSet().
G4double G4RDCompositeEMDataSet::FindValue (G4double x, G4int componentId = 0) const virtual
Implements G4RDVEMDataSet.
Definition at line 68 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 68 of file G4RDCompositeEMDataSet.cc
References FatalException, G4RDVEMDataSet::FindValue(), G4Exception(), GetComponent(), and message().
virtual const G4RDVEMDataSet* G4RDCompositeEMDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 70 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RDCompositeEMDataSet.hh
References components.
Referenced by FindValue(), GetData(), GetEnergies(), PrintData(), RandomSelect(), and SaveData().
virtual const G4DataVector& G4RDCompositeEMDataSet::GetData (G4int componentId) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 75 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 75 of file G4RDCompositeEMDataSet.hh
References GetComponent(), and G4RDVEMDataSet::GetData().
virtual const G4DataVector& G4RDCompositeEMDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 74 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 74 of file G4RDCompositeEMDataSet.hh
References GetComponent(), and G4RDVEMDataSet::GetEnergies().
G4bool G4RDCompositeEMDataSet::LoadData (const G4String & fileName) virtual
Implements G4RDVEMDataSet.
Definition at line 117 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 117 of file G4RDCompositeEMDataSet.cc
References AddComponent(), algorithm, CleanUpComponents(), G4RDVDataSetAlgorithm::Clone(), G4RDVEMDataSet::LoadData(), maxZ, minZ, unitData, unitEnergies, and z.
virtual size_t G4RDCompositeEMDataSet::NumberOfComponents (void) const inline virtual
Implements G4RDVEMDataSet.
Definition at line 72 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 72 of file G4RDCompositeEMDataSet.hh
References components.
Referenced by PrintData().
G4RDCompositeEMDataSet& G4RDCompositeEMDataSet::operator= (const G4RDCompositeEMDataSet & right) private
void G4RDCompositeEMDataSet::PrintData (void) const virtual
Implements G4RDVEMDataSet.
Definition at line 83 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 83 of file G4RDCompositeEMDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4RDVEMDataSet::PrintData().
G4double G4RDCompositeEMDataSet::RandomSelect (G4int componentId) const virtual
Implements G4RDVEMDataSet.
Definition at line 168 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 168 of file G4RDCompositeEMDataSet.cc
References components, GetComponent(), and G4RDVEMDataSet::RandomSelect().
G4bool G4RDCompositeEMDataSet::SaveData (const G4String & fileName) const virtual
Implements G4RDVEMDataSet.
Definition at line 136 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 136 of file G4RDCompositeEMDataSet.cc
References FatalException, G4Exception(), GetComponent(), maxZ, message(), minZ, G4RDVEMDataSet::SaveData(), and z.
void G4RDCompositeEMDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * data, G4int componentId) virtual
Implements G4RDVEMDataSet.
Definition at line 100 of file G4RDCompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 100 of file G4RDCompositeEMDataSet.cc
References components, FatalException, G4Exception(), message(), and G4RDVEMDataSet::SetEnergiesData().
Member Data Documentation
G4RDVDataSetAlgorithm* G4RDCompositeEMDataSet::algorithm private
Definition at line 95 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RDCompositeEMDataSet.hh
Referenced by G4RDCompositeEMDataSet(), LoadData(), and ~G4RDCompositeEMDataSet().
std::vector<G4RDVEMDataSet*> G4RDCompositeEMDataSet::components private
Definition at line 93 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 93 of file G4RDCompositeEMDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), GetComponent(), NumberOfComponents(), RandomSelect(), and SetEnergiesData().
G4int G4RDCompositeEMDataSet::maxZ private
Definition at line 101 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 101 of file G4RDCompositeEMDataSet.hh
Referenced by LoadData(), and SaveData().
G4int G4RDCompositeEMDataSet::minZ private
Definition at line 100 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 100 of file G4RDCompositeEMDataSet.hh
Referenced by LoadData(), and SaveData().
G4double G4RDCompositeEMDataSet::unitData private
Definition at line 98 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 98 of file G4RDCompositeEMDataSet.hh
Referenced by LoadData().
G4double G4RDCompositeEMDataSet::unitEnergies private
Definition at line 97 of file G4RDCompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 97 of file G4RDCompositeEMDataSet.hh
Referenced by LoadData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDCompositeEMDataSet.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDCompositeEMDataSet.cc