ECCE @ EIC Software: WLSPrimaryGeneratorAction Class Reference
WLSPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSPrimaryGeneratorAction.hh>
Public Member Functions
WLSPrimaryGeneratorAction (WLSDetectorConstruction *)
virtual ~WLSPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
void BuildEmissionSpectrum ()
void SetOptPhotonPolar (G4double)
void SetDecayTimeConstant (G4double)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Protected Attributes
G4PhysicsTable * fIntegralTable
Private Member Functions
void SetOptPhotonPolar ()
void SetOptPhotonTime ()
Private Attributes
WLSDetectorConstruction * fDetector
G4GeneralParticleSource * fParticleGun
WLSPrimaryGeneratorMessenger * fGunMessenger
G4double fTimeConstant
Static Private Attributes
static G4bool fFirst = false
Detailed Description
Definition at line 50 of file WLSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 50 of file WLSPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
WLSPrimaryGeneratorAction::WLSPrimaryGeneratorAction (WLSDetectorConstruction * dc)
Definition at line 64 of file WLSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 64 of file WLSPrimaryGeneratorAction.cc
References fDetector, fGunMessenger, fIntegralTable, fParticleGun, and fTimeConstant.
WLSPrimaryGeneratorAction::~WLSPrimaryGeneratorAction () virtual
Definition at line 84 of file WLSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 84 of file WLSPrimaryGeneratorAction.cc
References G4PhysicsTable::clearAndDestroy(), fGunMessenger, fIntegralTable, and fParticleGun.
Member Function Documentation
void WLSPrimaryGeneratorAction::BuildEmissionSpectrum ()
Definition at line 103 of file WLSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 103 of file WLSPrimaryGeneratorAction.cc
References G4PhysicsVector::Energy(), fIntegralTable, G4Material::GetMaterialPropertiesTable(), G4Material::GetMaterialTable(), G4Material::GetNumberOfMaterials(), G4MaterialPropertiesTable::GetProperty(), G4PhysicsVector::GetVectorLength(), and G4PhysicsTable::insertAt().
Referenced by GeneratePrimaries().
void WLSPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 161 of file WLSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 161 of file WLSPrimaryGeneratorAction.cc
References BuildEmissionSpectrum(), eV, fFirst, fIntegralTable, fParticleGun, G4UniformRand, G4GeneralParticleSource::GeneratePrimaryVertex(), G4PhysicsOrderedFreeVector::GetEnergy(), G4Material::GetIndex(), G4Material::GetMaterialPropertiesTable(), G4Material::GetMaterialTable(), G4PhysicsOrderedFreeVector::GetMaxValue(), G4Material::GetName(), G4GeneralParticleSource::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4MaterialPropertiesTable::GetProperty(), SetOptPhotonPolar(), and SetOptPhotonTime().
void WLSPrimaryGeneratorAction::SetDecayTimeConstant (G4double time)
Definition at line 96 of file WLSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 96 of file WLSPrimaryGeneratorAction.cc
References fTimeConstant, and Acts::VectorHelpers::time().
void WLSPrimaryGeneratorAction::SetOptPhotonPolar (G4double angle)
Definition at line 218 of file WLSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 218 of file WLSPrimaryGeneratorAction.cc
References CLHEP::Hep3Vector::cross(), fParticleGun, G4cout, G4endl, G4GeneralParticleSource::GetParticleDefinition(), G4GeneralParticleSource::GetParticleMomentumDirection(), G4ParticleDefinition::GetParticleName(), CLHEP::normal(), and G4GeneralParticleSource::SetParticlePolarization().
void WLSPrimaryGeneratorAction::SetOptPhotonPolar () private
Definition at line 210 of file WLSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 210 of file WLSPrimaryGeneratorAction.cc
References angle, deg, and G4UniformRand.
Referenced by GeneratePrimaries().
void WLSPrimaryGeneratorAction::SetOptPhotonTime () private
Definition at line 243 of file WLSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 243 of file WLSPrimaryGeneratorAction.cc
References fParticleGun, fTimeConstant, G4UniformRand, G4GeneralParticleSource::SetParticleTime(), and Acts::VectorHelpers::time().
Referenced by GeneratePrimaries().
Member Data Documentation
WLSDetectorConstruction* WLSPrimaryGeneratorAction::fDetector private
Definition at line 76 of file WLSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 76 of file WLSPrimaryGeneratorAction.hh
Referenced by WLSPrimaryGeneratorAction().
G4bool WLSPrimaryGeneratorAction::fFirst = false static private
Definition at line 80 of file WLSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 80 of file WLSPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
WLSPrimaryGeneratorMessenger* WLSPrimaryGeneratorAction::fGunMessenger private
Definition at line 78 of file WLSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 78 of file WLSPrimaryGeneratorAction.hh
Referenced by WLSPrimaryGeneratorAction(), and ~WLSPrimaryGeneratorAction().
G4PhysicsTable* WLSPrimaryGeneratorAction::fIntegralTable protected
Definition at line 69 of file WLSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file WLSPrimaryGeneratorAction.hh
Referenced by BuildEmissionSpectrum(), GeneratePrimaries(), WLSPrimaryGeneratorAction(), and ~WLSPrimaryGeneratorAction().
G4GeneralParticleSource* WLSPrimaryGeneratorAction::fParticleGun private
Definition at line 77 of file WLSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 77 of file WLSPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), SetOptPhotonPolar(), SetOptPhotonTime(), WLSPrimaryGeneratorAction(), and ~WLSPrimaryGeneratorAction().
G4double WLSPrimaryGeneratorAction::fTimeConstant private
Definition at line 82 of file WLSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 82 of file WLSPrimaryGeneratorAction.hh
Referenced by SetDecayTimeConstant(), SetOptPhotonTime(), and WLSPrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSPrimaryGeneratorAction.cc