ECCE @ EIC Software: B01DetectorConstruction Class Reference
B01DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/B01/include/B01DetectorConstruction.hh>
Public Member Functions
B01DetectorConstruction ()
~B01DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
G4VIStore * CreateImportanceStore ()
G4VWeightWindowStore * CreateWeightWindowStore ()
G4String GetCellName (G4int i)
G4VPhysicalVolume * GetWorldVolume ()
void SetSensitive ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
std::vector< G4LogicalVolume * > fLogicalVolumeVector
std::vector< G4VPhysicalVolume * > fPhysicalVolumeVector
G4VPhysicalVolume * fWorldVolume
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 43 of file B01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 43 of file B01DetectorConstruction.hh
Constructor & Destructor Documentation
B01DetectorConstruction::B01DetectorConstruction ()
Definition at line 67 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 67 of file B01DetectorConstruction.cc
B01DetectorConstruction::~B01DetectorConstruction ()
Definition at line 74 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 74 of file B01DetectorConstruction.cc
References fLogicalVolumeVector, and fPhysicalVolumeVector.
Member Function Documentation
G4VPhysicalVolume * B01DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 82 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 82 of file B01DetectorConstruction.cc
References A(), G4Material::AddElement(), cm, cm3, deg, fLogicalVolumeVector, fPhysicalVolumeVector, fWorldVolume, Acts::UnitConstants::g, GetCellName(), kelvin, kStateGas, mole, pascal, G4VisAttributes::SetForceSolid(), SetSensitive(), G4LogicalVolume::SetVisAttributes(), source.hepunit::universe_mean_density, Z, and z.
void B01DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 407 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 407 of file B01DetectorConstruction.cc
References G4SDManager::AddNewDetector(), G4PSTrackLength::DivideByVelocity(), fCurrent_In, fLogicalVolumeVector, G4SDManager::GetSDMpointer(), it, G4PSTrackLength::MultiplyKineticEnergy(), G4MultiFunctionalDetector::RegisterPrimitive(), G4VSensitiveDetector::SetFilter(), G4VUserDetectorConstruction::SetSensitiveDetector(), G4PSTrackLength::Weighted(), and G4PSNofCollision::Weighted().
G4VIStore * B01DetectorConstruction::CreateImportanceStore ()
Definition at line 266 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 266 of file B01DetectorConstruction.cc
References G4IStore::AddImportanceGeometryCell(), fPhysicalVolumeVector, fWorldVolume, G4cout, G4endl, G4Exception(), G4IStore::GetInstance(), it, n, and RunMustBeAborted.
Referenced by main().
G4VWeightWindowStore * B01DetectorConstruction::CreateWeightWindowStore ()
Definition at line 309 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 309 of file B01DetectorConstruction.cc
References G4WeightWindowStore::AddLowerWeights(), fPhysicalVolumeVector, fWorldVolume, G4cout, G4endl, G4Exception(), G4WeightWindowStore::GetInstance(), GeV, it, n, RunMustBeAborted, and G4WeightWindowStore::SetGeneralUpperEnergyBounds().
Referenced by main().
G4String B01DetectorConstruction::GetCellName (G4int i)
Definition at line 367 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 367 of file B01DetectorConstruction.cc
Referenced by Construct(), and B01RunAction::EndOfRunAction().
G4VPhysicalVolume * B01DetectorConstruction::GetWorldVolume ()
Definition at line 380 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 380 of file B01DetectorConstruction.cc
References fWorldVolume.
Referenced by main().
void B01DetectorConstruction::SetSensitive ()
Definition at line 386 of file B01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 386 of file B01DetectorConstruction.cc
Referenced by Construct().
Member Data Documentation
std::vector< G4LogicalVolume * > B01DetectorConstruction::fLogicalVolumeVector private
Definition at line 67 of file B01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file B01DetectorConstruction.hh
Referenced by Construct(), ConstructSDandField(), and ~B01DetectorConstruction().
std::vector< G4VPhysicalVolume * > B01DetectorConstruction::fPhysicalVolumeVector private
Definition at line 68 of file B01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 68 of file B01DetectorConstruction.hh
Referenced by Construct(), CreateImportanceStore(), CreateWeightWindowStore(), and ~B01DetectorConstruction().
G4VPhysicalVolume* B01DetectorConstruction::fWorldVolume private
Definition at line 70 of file B01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 70 of file B01DetectorConstruction.hh
Referenced by Construct(), CreateImportanceStore(), CreateWeightWindowStore(), and GetWorldVolume().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/B01/include/B01DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/B01/src/B01DetectorConstruction.cc