ECCE @ EIC Software: G4ComponentSAIDTotalXS Class Reference
G4ComponentSAIDTotalXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ComponentSAIDTotalXS.hh>
Public Member Functions
G4ComponentSAIDTotalXS ()
virtual ~G4ComponentSAIDTotalXS ()
virtual G4double GetTotalElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4double)
virtual G4double GetTotalIsotopeCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)
virtual G4double GetInelasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4double)
virtual G4double GetInelasticIsotopeCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)
virtual G4double GetElasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4double)
virtual G4double GetElasticIsotopeCrossSection (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)
G4double GetChargeExchangeCrossSection (const G4ParticleDefinition *prim, const G4ParticleDefinition *sec, G4double kinEnergy, G4int, G4int)
virtual void Description (std::ostream &) const final
Public Member Functions inherited from G4VComponentCrossSection
G4VComponentCrossSection (const G4String &nam="")
virtual ~G4VComponentCrossSection ()
G4double GetTotalElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
G4double GetInelasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
G4double GetElasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
virtual G4double ComputeQuasiElasticRatio (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
const G4String & GetName () const
Private Member Functions
G4SAIDCrossSectionType GetType (const G4ParticleDefinition *prim, const G4ParticleDefinition *sec, G4int Z, G4int N)
void Initialise (G4SAIDCrossSectionType tp)
void ReadData (G4int index, G4PhysicsVector *, const G4String &, const G4String &)
void PrintWarning (const G4ParticleDefinition *prim, const G4ParticleDefinition *sec, G4int, G4int, const G4String &, const G4String &)
G4ComponentSAIDTotalXS & operator= (const G4ComponentSAIDTotalXS &right)
G4ComponentSAIDTotalXS (const G4ComponentSAIDTotalXS &)
Private Attributes
G4PhysicsVector * elastdata [numberOfSaidXS]
G4PhysicsVector * inelastdata [numberOfSaidXS]
Static Private Attributes
static const G4String fnames [numberOfSaidXS]
Detailed Description
Definition at line 74 of file G4ComponentSAIDTotalXS.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ComponentSAIDTotalXS.hh
Constructor & Destructor Documentation
G4ComponentSAIDTotalXS::G4ComponentSAIDTotalXS ()
Definition at line 53 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ComponentSAIDTotalXS.cc
References elastdata, inelastdata, and numberOfSaidXS.
G4ComponentSAIDTotalXS::~G4ComponentSAIDTotalXS () virtual
Definition at line 62 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ComponentSAIDTotalXS.cc
References elastdata, inelastdata, and numberOfSaidXS.
G4ComponentSAIDTotalXS::G4ComponentSAIDTotalXS (const G4ComponentSAIDTotalXS &) private
Member Function Documentation
void G4ComponentSAIDTotalXS::Description (std::ostream &) const final virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 170 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 170 of file G4ComponentSAIDTotalXS.cc
G4double G4ComponentSAIDTotalXS::GetChargeExchangeCrossSection (const G4ParticleDefinition * prim, const G4ParticleDefinition * sec, G4double kinEnergy, G4int Z, G4int N)
Definition at line 153 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 153 of file G4ComponentSAIDTotalXS.cc
References Acts::VectorHelpers::cross(), GetType(), incremental_prev_tag::idx, inelastdata, Initialise(), saidUnknown, and G4InuclParticleNames::tp.
G4double G4ComponentSAIDTotalXS::GetElasticElementCrossSection (const G4ParticleDefinition * part, G4double kinEnergy, G4int Z, G4double N) virtual
Implements G4VComponentCrossSection.
Definition at line 125 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 125 of file G4ComponentSAIDTotalXS.cc
References G4lrint(), and PrintWarning().
G4double G4ComponentSAIDTotalXS::GetElasticIsotopeCrossSection (const G4ParticleDefinition * part, G4double kinEnergy, G4int Z, G4int N) virtual
Implements G4VComponentCrossSection.
Definition at line 136 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 136 of file G4ComponentSAIDTotalXS.cc
References Acts::VectorHelpers::cross(), elastdata, GetType(), incremental_prev_tag::idx, Initialise(), saidUnknown, and G4InuclParticleNames::tp.
Referenced by GetTotalIsotopeCrossSection().
G4double G4ComponentSAIDTotalXS::GetInelasticElementCrossSection (const G4ParticleDefinition * part, G4double kinEnergy, G4int Z, G4double N) virtual
Implements G4VComponentCrossSection.
Definition at line 97 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ComponentSAIDTotalXS.cc
References G4lrint(), and PrintWarning().
G4double G4ComponentSAIDTotalXS::GetInelasticIsotopeCrossSection (const G4ParticleDefinition * part, G4double kinEnergy, G4int Z, G4int N) virtual
Implements G4VComponentCrossSection.
Definition at line 108 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 108 of file G4ComponentSAIDTotalXS.cc
References Acts::VectorHelpers::cross(), GetType(), incremental_prev_tag::idx, inelastdata, Initialise(), saidUnknown, and G4InuclParticleNames::tp.
Referenced by GetTotalIsotopeCrossSection().
G4double G4ComponentSAIDTotalXS::GetTotalElementCrossSection (const G4ParticleDefinition * part, G4double kinEnergy, G4int Z, G4double N) virtual
Implements G4VComponentCrossSection.
Definition at line 77 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ComponentSAIDTotalXS.cc
References G4lrint(), and PrintWarning().
G4double G4ComponentSAIDTotalXS::GetTotalIsotopeCrossSection (const G4ParticleDefinition * part, G4double kinEnergy, G4int Z, G4int N) virtual
Implements G4VComponentCrossSection.
Definition at line 88 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 88 of file G4ComponentSAIDTotalXS.cc
References GetElasticIsotopeCrossSection(), and GetInelasticIsotopeCrossSection().
G4SAIDCrossSectionType G4ComponentSAIDTotalXS::GetType (const G4ParticleDefinition * prim, const G4ParticleDefinition * sec, G4int Z, G4int N) private
Definition at line 175 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 175 of file G4ComponentSAIDTotalXS.cc
References G4ParticleDefinition::GetPDGEncoding(), saidGN_PI0N, saidGN_PINP, saidGP_ETAP, saidGP_ETAPP, saidGP_PI0P, saidGP_PIPN, saidNP, saidPINP, saidPINP_ETAN, saidPINP_PI0N, saidPIPP, saidPP, and saidUnknown.
Referenced by GetChargeExchangeCrossSection(), GetElasticIsotopeCrossSection(), and GetInelasticIsotopeCrossSection().
void G4ComponentSAIDTotalXS::Initialise (G4SAIDCrossSectionType tp) private
Definition at line 215 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 215 of file G4ComponentSAIDTotalXS.cc
References elastdata, FatalException, G4Exception(), G4MUTEXLOCK, G4MUTEXUNLOCK, incremental_prev_tag::idx, inelastdata, and ReadData().
Referenced by GetChargeExchangeCrossSection(), GetElasticIsotopeCrossSection(), and GetInelasticIsotopeCrossSection().
G4ComponentSAIDTotalXS& G4ComponentSAIDTotalXS::operator= (const G4ComponentSAIDTotalXS & right) private
void G4ComponentSAIDTotalXS::PrintWarning (const G4ParticleDefinition * prim, const G4ParticleDefinition * sec, G4int Z, G4int N, const G4String & ss1, const G4String & ss2) private
Definition at line 273 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 273 of file G4ComponentSAIDTotalXS.cc
References G4cout, G4endl, and G4ParticleDefinition::GetParticleName().
Referenced by GetElasticElementCrossSection(), GetInelasticElementCrossSection(), and GetTotalElementCrossSection().
void G4ComponentSAIDTotalXS::ReadData (G4int index, G4PhysicsVector * v, const G4String & ss1, const G4String & ss2) private
Definition at line 246 of file G4ComponentSAIDTotalXS.cc.
View newest version in sPHENIX GitHub at line 246 of file G4ComponentSAIDTotalXS.cc
References FatalException, fnames, G4cout, G4endl, G4Exception(), G4VComponentCrossSection::GetVerboseLevel(), CLHEP::MeV, CLHEP::millibarn, G4PhysicsVector::Retrieve(), G4PhysicsVector::ScaleVector(), and G4PhysicsVector::SetSpline().
Referenced by Initialise().
Member Data Documentation
G4PhysicsVector* G4ComponentSAIDTotalXS::elastdata[numberOfSaidXS] private
Definition at line 139 of file G4ComponentSAIDTotalXS.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ComponentSAIDTotalXS.hh
Referenced by G4ComponentSAIDTotalXS(), GetElasticIsotopeCrossSection(), Initialise(), and ~G4ComponentSAIDTotalXS().
const G4String G4ComponentSAIDTotalXS::fnames static private
Initial value:
= {
  "","pp","np","pip","pim",
  "pin","pie",
  "gp_pi0p","gp_pi+n","gn_pi-p","gn_pi0n","gp_etap","gp_etapp"
}
Definition at line 138 of file G4ComponentSAIDTotalXS.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ComponentSAIDTotalXS.hh
Referenced by ReadData().
G4PhysicsVector* G4ComponentSAIDTotalXS::inelastdata[numberOfSaidXS] private
Definition at line 140 of file G4ComponentSAIDTotalXS.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ComponentSAIDTotalXS.hh
Referenced by G4ComponentSAIDTotalXS(), GetChargeExchangeCrossSection(), GetInelasticIsotopeCrossSection(), Initialise(), and ~G4ComponentSAIDTotalXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ComponentSAIDTotalXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ComponentSAIDTotalXS.cc