ECCE @ EIC Software: G4FermiPair Class Reference
G4FermiPair Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiPair.hh>
Public Member Functions
G4FermiPair (const G4FermiFragment *f1, const G4FermiFragment *f2)
G4int GetA () const
G4int GetZ () const
G4double GetMass () const
G4double GetExcitationEnergy () const
G4double GetTotalEnergy () const
G4double GetDynamicMinMass (G4double Eex) const
const G4FermiFragment * GetFragment1 () const
const G4FermiFragment * GetFragment2 () const
Private Member Functions
G4FermiPair (const G4FermiPair &)=delete
const G4FermiPair & operator= (const G4FermiPair &)=delete
G4bool operator== (const G4FermiPair &) const =delete
G4bool operator!= (const G4FermiPair &) const =delete
Private Attributes
G4int totalZ
G4int totalA
G4double mass
G4double excitEnergy
const G4FermiFragment * fragment1
const G4FermiFragment * fragment2
Detailed Description
Definition at line 38 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 38 of file G4FermiPair.hh
Constructor & Destructor Documentation
G4FermiPair::G4FermiPair (const G4FermiFragment * f1, const G4FermiFragment * f2) explicit
Definition at line 34 of file G4FermiPair.cc.
View newest version in sPHENIX GitHub at line 34 of file G4FermiPair.cc
References excitEnergy, G4FermiFragment::GetA(), G4NucleiProperties::GetNuclearMass(), G4FermiFragment::GetTotalEnergy(), G4FermiFragment::GetZ(), mass, totalA, and totalZ.
G4FermiPair::G4FermiPair (const G4FermiPair &) inline private delete
Member Function Documentation
G4int G4FermiPair::GetA (void) const inline
Definition at line 71 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 71 of file G4FermiPair.hh
References totalA.
G4double G4FermiPair::GetDynamicMinMass (G4double Eex) const inline
Definition at line 106 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 106 of file G4FermiPair.hh
References fragment1, fragment2, G4FermiFragment::GetA(), G4FermiFragment::GetCoulombBarrier(), G4FermiFragment::GetTotalEnergy(), and G4FermiFragment::GetZ().
G4double G4FermiPair::GetExcitationEnergy (void) const inline
Definition at line 86 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 86 of file G4FermiPair.hh
References excitEnergy.
const G4FermiFragment * G4FermiPair::GetFragment1 () const inline
Definition at line 96 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 96 of file G4FermiPair.hh
References fragment1.
Referenced by G4FermiFragmentsPoolVI::Dump(), and G4FermiBreakUpVI::SampleDecay().
const G4FermiFragment * G4FermiPair::GetFragment2 () const inline
Definition at line 101 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 101 of file G4FermiPair.hh
References fragment2.
Referenced by G4FermiFragmentsPoolVI::Dump(), and G4FermiBreakUpVI::SampleDecay().
G4double G4FermiPair::GetMass () const inline
Definition at line 81 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 81 of file G4FermiPair.hh
References mass.
G4double G4FermiPair::GetTotalEnergy (void) const inline
Definition at line 91 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 91 of file G4FermiPair.hh
References excitEnergy, and mass.
G4int G4FermiPair::GetZ (void) const inline
Definition at line 76 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FermiPair.hh
References totalZ.
G4bool G4FermiPair::operator!= (const G4FermiPair &) const inline private delete
const G4FermiPair& G4FermiPair::operator= (const G4FermiPair &) inline private delete
G4bool G4FermiPair::operator== (const G4FermiPair &) const inline private delete
Member Data Documentation
G4double G4FermiPair::excitEnergy private
Definition at line 64 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 64 of file G4FermiPair.hh
Referenced by G4FermiPair(), GetExcitationEnergy(), and GetTotalEnergy().
const G4FermiFragment* G4FermiPair::fragment1 private
Definition at line 66 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 66 of file G4FermiPair.hh
Referenced by GetDynamicMinMass(), and GetFragment1().
const G4FermiFragment* G4FermiPair::fragment2 private
Definition at line 67 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 67 of file G4FermiPair.hh
Referenced by GetDynamicMinMass(), and GetFragment2().
G4double G4FermiPair::mass private
Definition at line 63 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 63 of file G4FermiPair.hh
Referenced by G4FermiPair(), GetMass(), and GetTotalEnergy().
G4int G4FermiPair::totalA private
Definition at line 61 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 61 of file G4FermiPair.hh
Referenced by G4FermiPair(), and GetA().
G4int G4FermiPair::totalZ private
Definition at line 60 of file G4FermiPair.hh.
View newest version in sPHENIX GitHub at line 60 of file G4FermiPair.hh
Referenced by G4FermiPair(), and GetZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiPair.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/src/G4FermiPair.cc