ECCE @ EIC Software: G4tgrLineProcessor Class Reference
G4tgrLineProcessor Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrLineProcessor.hh>
Public Member Functions
G4tgrLineProcessor ()
virtual ~G4tgrLineProcessor ()
virtual G4bool ProcessLine (const std::vector< G4String > &wl)
Protected Member Functions
G4tgrVolume * FindVolume (const G4String &volname)
Private Attributes
G4tgrVolumeMgr * volmgr
Detailed Description
Definition at line 49 of file G4tgrLineProcessor.hh.
View newest version in sPHENIX GitHub at line 49 of file G4tgrLineProcessor.hh
Constructor & Destructor Documentation
G4tgrLineProcessor::G4tgrLineProcessor ()
Definition at line 54 of file G4tgrLineProcessor.cc.
View newest version in sPHENIX GitHub at line 54 of file G4tgrLineProcessor.cc
References G4tgrVolumeMgr::GetInstance(), and volmgr.
G4tgrLineProcessor::~G4tgrLineProcessor () virtual
Definition at line 61 of file G4tgrLineProcessor.cc.
View newest version in sPHENIX GitHub at line 61 of file G4tgrLineProcessor.cc
Member Function Documentation
G4tgrVolume * G4tgrLineProcessor::FindVolume (const G4String & volname) protected
Definition at line 320 of file G4tgrLineProcessor.cc.
View newest version in sPHENIX GitHub at line 320 of file G4tgrLineProcessor.cc
References FatalException, G4tgrVolumeMgr::FindVolume(), G4Exception(), G4tgrVolume::GetType(), and volmgr.
Referenced by ProcessLine().
G4bool G4tgrLineProcessor::ProcessLine (const std::vector< G4String > & wl) virtual
Reimplemented in ExTGRCLineProcessor.
Definition at line 67 of file G4tgrLineProcessor.cc.
View newest version in sPHENIX GitHub at line 67 of file G4tgrLineProcessor.cc
References G4tgrMaterialFactory::AddElementFromIsotopes(), G4tgrMaterialFactory::AddElementSimple(), G4tgrMaterialFactory::AddIsotope(), G4tgrMaterialFactory::AddMaterialMixture(), G4tgrMaterialFactory::AddMaterialSimple(), G4tgrParameterMgr::AddParameterNumber(), G4tgrParameterMgr::AddParameterString(), G4tgrVolume::AddPlace(), G4tgrVolume::AddPlaceParam(), G4tgrVolume::AddPlaceReplica(), G4tgrRotationMatrixFactory::AddRotMatrix(), atmosphere, G4tgrVolumeMgr::CreateSolid(), G4tgrUtils::DumpVS(), FatalException, G4tgrMaterialFactory::FindMaterial(), FindVolume(), G4tgrVolumeMgr::FindVolumes(), G4Exception(), G4tgrUtils::GetDouble(), G4tgrParameterMgr::GetInstance(), G4tgrRotationMatrixFactory::GetInstance(), G4tgrMaterialFactory::GetInstance(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), kelvin, G4tgrVolumeMgr::RegisterMe(), G4tgrMaterial::SetIonisationMeanExcitationEnergy(), G4tgrMaterial::SetPressure(), G4tgrMaterial::SetState(), G4tgrMaterial::SetTemperature(), and volmgr.
Referenced by ExTGRCLineProcessor::ProcessLine(), and G4tgrFileReader::ReadFiles().
Member Data Documentation
G4tgrVolumeMgr* G4tgrLineProcessor::volmgr private
Definition at line 64 of file G4tgrLineProcessor.hh.
View newest version in sPHENIX GitHub at line 64 of file G4tgrLineProcessor.hh
Referenced by FindVolume(), G4tgrLineProcessor(), and ProcessLine().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrLineProcessor.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrLineProcessor.cc