ECCE @ EIC Software: XrayFluoEventAction Class Reference
XrayFluoEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoEventAction.hh>
Public Member Functions
XrayFluoEventAction (const XrayFluoDetectorConstruction *)
XrayFluoEventAction (const XrayFluoPlaneDetectorConstruction *)
XrayFluoEventAction (const XrayFluoMercuryDetectorConstruction *)
virtual ~XrayFluoEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
void SetDrawFlag (G4String val)
void SetPrintModulo (G4int val)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Member Functions
G4double RandomCut (G4double)
Private Attributes
G4String drawFlag
G4int HPGeCollID
XrayFluoEventActionMessenger * eventMessenger
G4int printModulo
XrayFluoVDetectorType * detectorType
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 52 of file XrayFluoEventAction.hh.
View newest version in sPHENIX GitHub at line 52 of file XrayFluoEventAction.hh
Constructor & Destructor Documentation
XrayFluoEventAction::XrayFluoEventAction (const XrayFluoDetectorConstruction * det)
Definition at line 58 of file XrayFluoEventAction.cc.
View newest version in sPHENIX GitHub at line 58 of file XrayFluoEventAction.cc
References detectorType, eventMessenger, XrayFluoDetectorConstruction::GetDetectorType(), XrayFluoDetectorConstruction::GetPhaseSpaceFlag(), and HPGeCollID.
XrayFluoEventAction::XrayFluoEventAction (const XrayFluoPlaneDetectorConstruction * det)
Definition at line 75 of file XrayFluoEventAction.cc.
View newest version in sPHENIX GitHub at line 75 of file XrayFluoEventAction.cc
References detectorType, eventMessenger, and XrayFluoPlaneDetectorConstruction::GetDetectorType().
XrayFluoEventAction::XrayFluoEventAction (const XrayFluoMercuryDetectorConstruction * det)
Definition at line 88 of file XrayFluoEventAction.cc.
View newest version in sPHENIX GitHub at line 88 of file XrayFluoEventAction.cc
References detectorType, eventMessenger, and XrayFluoMercuryDetectorConstruction::GetDetectorType().
XrayFluoEventAction::~XrayFluoEventAction () virtual
Definition at line 101 of file XrayFluoEventAction.cc.
View newest version in sPHENIX GitHub at line 101 of file XrayFluoEventAction.cc
References eventMessenger.
Member Function Documentation
void XrayFluoEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 109 of file XrayFluoEventAction.cc.
View newest version in sPHENIX GitHub at line 109 of file XrayFluoEventAction.cc
References e6, G4cout, G4endl, G4SDManager::GetCollectionID(), G4Event::GetEventID(), G4SDManager::GetSDMpointer(), and HPGeCollID.
void XrayFluoEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 135 of file XrayFluoEventAction.cc.
View newest version in sPHENIX GitHub at line 135 of file XrayFluoEventAction.cc
References XrayFluoAnalysisManager::analyseEnergyDep(), static_analysis_results::analysis(), detectorType, G4THitsCollection< T >::entries(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), XrayFluoAnalysisManager::getInstance(), HPGeCollID, and XrayFluoVDetectorType::ResponseFunction().
G4double XrayFluoEventAction::RandomCut (G4double energy) private
Definition at line 170 of file XrayFluoEventAction.cc.
View newest version in sPHENIX GitHub at line 170 of file XrayFluoEventAction.cc
References epsilon(), eV, F, G4UniformRand, and G4INCL::DeJongSpin::shoot().
void XrayFluoEventAction::SetDrawFlag (G4String val) inline
Definition at line 67 of file XrayFluoEventAction.hh.
View newest version in sPHENIX GitHub at line 67 of file XrayFluoEventAction.hh
References drawFlag.
Referenced by XrayFluoEventActionMessenger::SetNewValue().
void XrayFluoEventAction::SetPrintModulo (G4int val) inline
Definition at line 68 of file XrayFluoEventAction.hh.
View newest version in sPHENIX GitHub at line 68 of file XrayFluoEventAction.hh
References printModulo.
Referenced by XrayFluoEventActionMessenger::SetNewValue().
Member Data Documentation
XrayFluoVDetectorType* XrayFluoEventAction::detectorType private
Definition at line 84 of file XrayFluoEventAction.hh.
View newest version in sPHENIX GitHub at line 84 of file XrayFluoEventAction.hh
Referenced by EndOfEventAction(), and XrayFluoEventAction().
G4String XrayFluoEventAction::drawFlag private
Definition at line 68 of file XrayFluoEventAction.hh.
View newest version in sPHENIX GitHub at line 68 of file XrayFluoEventAction.hh
Referenced by SetDrawFlag().
XrayFluoEventActionMessenger* XrayFluoEventAction::eventMessenger private
Definition at line 76 of file XrayFluoEventAction.hh.
View newest version in sPHENIX GitHub at line 76 of file XrayFluoEventAction.hh
Referenced by XrayFluoEventAction(), and ~XrayFluoEventAction().
G4int XrayFluoEventAction::HPGeCollID private
Definition at line 73 of file XrayFluoEventAction.hh.
View newest version in sPHENIX GitHub at line 73 of file XrayFluoEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), and XrayFluoEventAction().
G4int XrayFluoEventAction::printModulo private
Definition at line 77 of file XrayFluoEventAction.hh.
View newest version in sPHENIX GitHub at line 77 of file XrayFluoEventAction.hh
Referenced by SetPrintModulo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoEventAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoEventAction.cc