ECCE @ EIC Software: G4ExcitedMesonConstructor Class Reference
G4ExcitedMesonConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedMesonConstructor.hh>
Public Types
enum { NMultiplets = 10 }
enum { NMesonTypes = 5 }
enum { NumberOfDecayModes = 19 }
Public Member Functions
G4ExcitedMesonConstructor (G4int nStates=0, G4int isoSpin=0)
virtual ~G4ExcitedMesonConstructor ()
virtual void Construct (G4int indexOfState=-1)
Protected Types
enum {
N11P1 = 0, N13P0 = 1, N13P1 = 2, N13P2 = 3,
N11D2 = 4, N13D1 = 5, N13D3 = 6, N21S0 = 7,
N23S1 = 8, N23P2 = 9
}
enum {
TPi =0, TEta =1, TEtaPrime =2, TK =3,
TAntiK =4
}
enum {
MPiGamma = 0, MRhoGamma =1, M2Pi =2, MPiRho =3,
M3Pi = 4, MPiEta =5, M4Pi =6, MKKStar =7,
M2PiEta =8, MRhoEta =9, M2PiRho =10, M2PiOmega =11,
M2Eta =12, M2K =13, M2KPi =14, MPiOmega =15,
MPiF2 =16, MPiF0 =17, MPiA2 =18
}
enum {
MKPi = 0, MKStarPi =1, MKRho =2, MKOmega =3,
MKStar2Pi =4, MKTwoPi =5, MKEta =6
}
Protected Member Functions
void ConstructMesons (G4int indexOfState, G4int indexOfType)
G4String GetName (G4int iIso3, G4int iState, G4int idxType)
G4double GetCharge (G4int iIsoSpin3)
G4int GetEncoding (G4int iIsoSpin3, G4int idxState, G4int idxType)
G4int GetQuarkContents (G4int iQ, G4int iIso3, G4int iType)
G4bool Exist (G4int idxState, G4int idxType)
G4double GetCharge (G4int iIsoSpin3, G4int idxType)
G4DecayTable * CreateDecayTable (const G4String &, G4int, G4int, G4int)
G4DecayTable * AddKPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iType)
G4DecayTable * AddKStarPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iType)
G4DecayTable * AddKStar2PiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iType)
G4DecayTable * AddKRhoMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iType)
G4DecayTable * AddKTwoPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iType)
G4DecayTable * AddKOmegaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iType)
G4DecayTable * AddKEtaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iType)
G4DecayTable * AddPiGammaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddRhoGammaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add2PiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddPiRhoMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddPiEtaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddPiF2Mode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddPiF0Mode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddPiA2Mode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add3PiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add4PiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddKKStarMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add2PiEtaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddRhoEtaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add2PiRhoMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add2PiOmegaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * AddPiOmegaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add2EtaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add2KMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
G4DecayTable * Add2KPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4int iIso)
Protected Attributes
const G4String type
const G4int leptonNumber
const G4int baryonNumber
Static Protected Attributes
static const char * name [NMultiplets][NMesonTypes]
static const G4double mass [NMultiplets][NMesonTypes]
static const G4double massKdiff [NMultiplets]
static const G4double width [NMultiplets][NMesonTypes]
static const G4double widthKdiff [NMultiplets]
static const G4int iIsoSpin [NMesonTypes]
static const G4int iSpin [NMultiplets]
static const G4int iParity [NMultiplets]
static const G4int iGParity [NMultiplets][NMesonTypes]
static const G4int iChargeConjugation [NMultiplets]
static const G4int encodingOffset [NMultiplets]
static const G4double bRatio [NMultiplets][NMesonTypes][NumberOfDecayModes]
Detailed Description
Definition at line 48 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ExcitedMesonConstructor.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
NMultiplets
Definition at line 69 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ExcitedMesonConstructor.hh
anonymous enum protected
Enumerator:
N11P1
N13P0
N13P1
N13P2
N11D2
N13D1
N13D3
N21S0
N23S1
N23P2
Definition at line 71 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ExcitedMesonConstructor.hh
anonymous enum
Enumerator:
NMesonTypes
Definition at line 78 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ExcitedMesonConstructor.hh
anonymous enum protected
Enumerator:
TPi
TEta
TEtaPrime
TK
TAntiK
Definition at line 80 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ExcitedMesonConstructor.hh
anonymous enum
Enumerator:
NumberOfDecayModes
Definition at line 102 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ExcitedMesonConstructor.hh
anonymous enum protected
Enumerator:
MPiGamma
MRhoGamma
M2Pi
MPiRho
M3Pi
MPiEta
M4Pi
MKKStar
M2PiEta
MRhoEta
M2PiRho
M2PiOmega
M2Eta
M2K
M2KPi
MPiOmega
MPiF2
MPiF0
MPiA2
Definition at line 104 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ExcitedMesonConstructor.hh
anonymous enum protected
Enumerator:
MKPi
MKStarPi
MKRho
MKOmega
MKStar2Pi
MKTwoPi
MKEta
Definition at line 109 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ExcitedMesonConstructor.hh
Constructor & Destructor Documentation
G4ExcitedMesonConstructor::G4ExcitedMesonConstructor (G4int nStates = 0, G4int isoSpin = 0)
Definition at line 46 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ExcitedMesonConstructor.cc
G4ExcitedMesonConstructor::~G4ExcitedMesonConstructor () virtual
Definition at line 52 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ExcitedMesonConstructor.cc
Member Function Documentation
G4DecayTable * G4ExcitedMesonConstructor::Add2EtaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1160 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1160 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::Add2KMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1343 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1343 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::Add2KPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1374 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1374 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::Add2PiEtaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1138 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1138 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::Add2PiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 818 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 818 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::Add2PiOmegaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1175 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1175 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::Add2PiRhoMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1218 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1218 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::Add3PiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1060 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1060 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::Add4PiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1101 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1101 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddKEtaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iType) protected
Definition at line 465 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 465 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), TAntiK, and TK.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddKKStarMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 1288 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 1288 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddKOmegaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iType) protected
Definition at line 434 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 434 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), TAntiK, and TK.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddKPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iType) protected
Definition at line 347 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 347 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), TAntiK, and TK.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddKRhoMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iType) protected
Definition at line 496 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 496 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), TAntiK, and TK.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddKStar2PiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iType) protected
Definition at line 584 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 584 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), TAntiK, and TK.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddKStarPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iType) protected
Definition at line 540 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 540 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), TAntiK, and TK.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddKTwoPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iType) protected
Definition at line 390 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 390 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), TAntiK, and TK.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddPiA2Mode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 969 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 969 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddPiEtaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 710 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 710 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddPiF0Mode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 791 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 791 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddPiF2Mode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 764 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 764 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddPiGammaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 629 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 629 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddPiOmegaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 656 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 656 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddPiRhoMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 878 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 878 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddRhoEtaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 737 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 737 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedMesonConstructor::AddRhoGammaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4int iIso) protected
Definition at line 683 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 683 of file G4ExcitedMesonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
void G4ExcitedMesonConstructor::Construct (G4int indexOfState = -1) virtual
Definition at line 56 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ExcitedMesonConstructor.cc
References ConstructMesons(), G4cerr, G4endl, G4ParticleTable::GetParticleTable(), NMesonTypes, and NMultiplets.
Referenced by G4ShortLivedConstructor::ConstructResonances().
void G4ExcitedMesonConstructor::ConstructMesons (G4int indexOfState, G4int indexOfType) protected
Definition at line 91 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 91 of file G4ExcitedMesonConstructor.cc
References baryonNumber, CreateDecayTable(), Exist(), GetCharge(), GetEncoding(), GetName(), iChargeConjugation, iGParity, iIsoSpin, iParity, iSpin, leptonNumber, mass, massKdiff, particle, G4ParticleDefinition::SetAntiPDGEncoding(), G4ParticleDefinition::SetDecayTable(), G4ExcitedMesons::SetMultipletName(), TAntiK, TEta, TEtaPrime, TK, TPi, type, width, and widthKdiff.
Referenced by Construct().
G4DecayTable * G4ExcitedMesonConstructor::CreateDecayTable (const G4String & parentName, G4int iIso3, G4int iState, G4int iType) protected
Definition at line 250 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 250 of file G4ExcitedMesonConstructor.cc
References Add2EtaMode(), Add2KMode(), Add2KPiMode(), Add2PiEtaMode(), Add2PiMode(), Add2PiOmegaMode(), Add2PiRhoMode(), Add3PiMode(), Add4PiMode(), AddKEtaMode(), AddKKStarMode(), AddKOmegaMode(), AddKPiMode(), AddKRhoMode(), AddKStar2PiMode(), AddKStarPiMode(), AddKTwoPiMode(), AddPiA2Mode(), AddPiEtaMode(), AddPiF0Mode(), AddPiF2Mode(), AddPiGammaMode(), AddPiOmegaMode(), AddPiRhoMode(), AddRhoEtaMode(), AddRhoGammaMode(), bRatio, iIsoSpin, M2Eta, M2K, M2KPi, M2Pi, M2PiEta, M2PiOmega, M2PiRho, M3Pi, M4Pi, MKEta, MKKStar, MKOmega, MKPi, MKRho, MKStar2Pi, MKStarPi, MKTwoPi, MPiA2, MPiEta, MPiF0, MPiF2, MPiGamma, MPiOmega, MPiRho, MRhoEta, MRhoGamma, TAntiK, and TK.
Referenced by ConstructMesons().
G4bool G4ExcitedMesonConstructor::Exist (G4int idxState, G4int idxType) protected
Definition at line 77 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ExcitedMesonConstructor.cc
References N13D1, N13P0, N23P2, TEtaPrime, and TPi.
Referenced by ConstructMesons().
G4double G4ExcitedMesonConstructor::GetCharge (G4int iIsoSpin3) protected
Referenced by ConstructMesons().
G4double G4ExcitedMesonConstructor::GetCharge (G4int iIsoSpin3, G4int idxType) protected
Definition at line 186 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 186 of file G4ExcitedMesonConstructor.cc
References charge, eplus, and GetQuarkContents().
G4int G4ExcitedMesonConstructor::GetEncoding (G4int iIsoSpin3, G4int idxState, G4int idxType) protected
Definition at line 198 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 198 of file G4ExcitedMesonConstructor.cc
References encodingOffset, GetQuarkContents(), iSpin, TAntiK, TEta, TEtaPrime, TK, and TPi.
Referenced by ConstructMesons().
G4String G4ExcitedMesonConstructor::GetName (G4int iIso3, G4int iState, G4int idxType) inline protected
Definition at line 177 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 177 of file G4ExcitedMesonConstructor.hh
References particle, TAntiK, TK, and TPi.
Referenced by ConstructMesons().
G4int G4ExcitedMesonConstructor::GetQuarkContents (G4int iQ, G4int iIso3, G4int iType) protected
Definition at line 141 of file G4ExcitedMesonConstructor.cc.
View newest version in sPHENIX GitHub at line 141 of file G4ExcitedMesonConstructor.cc
References TAntiK, TEta, TEtaPrime, TK, and TPi.
Referenced by GetCharge(), and GetEncoding().
Member Data Documentation
const G4int G4ExcitedMesonConstructor::baryonNumber protected
Definition at line 85 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const G4double G4ExcitedMesonConstructor::bRatio static protected
Definition at line 113 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ExcitedMesonConstructor.hh
Referenced by CreateDecayTable().
const G4int G4ExcitedMesonConstructor::encodingOffset static protected
Initial value:
=
{ 10000, 10000, 20000,      0, 10000, 30000,     0, 100000,100000,100000}
Definition at line 99 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ExcitedMesonConstructor.hh
Referenced by GetEncoding().
const G4int G4ExcitedMesonConstructor::iChargeConjugation static protected
Initial value:
=
{
     -1,   +1,   +1,   +1,   +1,   -1,   -1,   +1,   -1,   +1
}
Definition at line 98 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const G4int G4ExcitedMesonConstructor::iGParity static protected
Initial value:
=
{
  {  +1,  -1,  -1,  0,  0},
  {  -1,  +1,   0,  0,  0},
  {  -1,  +1,  +1,  0,  0},
  {  -1,  +1,  +1,  0,  0},
  {  -1,  +1,  +1,  0,  0},
  {  +1,  -1,   0,  0,  0},
  {  +1,  -1,  -1,  0,  0},
  {  -1,  +1, +1,  0,  0},
  {  +1,  -1,  -1,  0,  0},
  {   0,  +1,  +1,  0,  0}
}
Definition at line 97 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const G4int G4ExcitedMesonConstructor::iIsoSpin static protected
Initial value:
=
{
     2,     0,         0,   1,     1
}
Definition at line 94 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons(), and CreateDecayTable().
const G4int G4ExcitedMesonConstructor::iParity static protected
Initial value:
=
{
     +1,   +1,   +1,   +1,   -1,   -1,   -1,   -1,   -1,   +1
}
Definition at line 96 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const G4int G4ExcitedMesonConstructor::iSpin static protected
Initial value:
=
{
      2,    0,    2,    4,    4,    2,    6,    0,    2,    4
}
Definition at line 95 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons(), and GetEncoding().
const G4int G4ExcitedMesonConstructor::leptonNumber protected
Definition at line 84 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const G4double G4ExcitedMesonConstructor::mass static protected
Initial value:
=
{
  {  1.2295*GeV, 1.170*GeV, 1.386*GeV, 1.272*GeV,  1.272*GeV },
  {   1.474*GeV, 1.350*GeV,       0.0, 1.430*GeV,  1.430*GeV },
  {   1.230*GeV,1.2819*GeV,1.4264*GeV, 1.403*GeV,  1.403*GeV },
  {  1.3183*GeV,1.2755*GeV, 1.525*GeV,1.4256*GeV, 1.4256*GeV },
  {  1.6722*GeV, 1.617*GeV, 1.842*GeV, 1.773*GeV,  1.773*GeV },
  {   1.720*GeV, 1.670*GeV,       0.0, 1.718*GeV,  1.718*GeV },
  {  1.6888*GeV, 1.667*GeV, 1.854*GeV, 1.776*GeV,  1.776*GeV },
  {   1.300*GeV, 1.294*GeV, 1.476*GeV, 1.460*GeV,  1.460*GeV },
  {   1.465*GeV, 1.425*GeV, 1.680*GeV, 1.421*GeV,  1.421*GeV },
  {         0.0, 1.815*GeV, 2.010*GeV, 1.973*GeV,  1.973*GeV }
}
Definition at line 90 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const G4double G4ExcitedMesonConstructor::massKdiff static protected
Initial value:
= {
  0.0*MeV,  0.0*MeV, 0.0*MeV, 6.8*MeV, 0.0*MeV,
    0.0*MeV,  0.0*MeV, 0.0*MeV, 0.0*MeV, 0.0*MeV
}
Definition at line 91 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const char * G4ExcitedMesonConstructor::name static protected
Initial value:
=
{
  { "b1(1235)",   "h1(1170)",   "h1(1380)",      "k1(1270)",      "k1(1270)" },
  { "a0(1450)",   "f0(1370)",           "", "k0_star(1430)", "k0_star(1430)" },
  { "a1(1260)",   "f1(1285)",   "f1(1420)",      "k1(1400)",      "k1(1400)" },
  { "a2(1320)",   "f2(1270)","f2_prime(1525)","k2_star(1430)","k2_star(1430)"},
  {"pi2(1670)", "eta2(1645)", "eta2(1870)",      "k2(1770)",      "k2(1770)" },
  {"rho(1700)", "omega(1650)",          "",  "k_star(1680)",  "k_star(1680)" },
  {"rho3(1690)","omega3(1670)","phi3(1850)", "k3_star(1780)", "k3_star(1780)" },
  { "pi(1300)",  "eta(1295)",  "eta(1475)",       "k(1460)",       "k(1460)" },
  {"rho(1450)","omega(1420)",  "phi(1680)",  "k_star(1410)",  "k_star(1410)" },
  {         "",   "f2(1810)",   "f2(2010)", "k2_star(1980)", "k2_star(1980)" }
}
Definition at line 89 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ExcitedMesonConstructor.hh
const G4String G4ExcitedMesonConstructor::type protected
Definition at line 83 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const G4double G4ExcitedMesonConstructor::width static protected
Initial value:
=
{
  {  142.0*MeV, 360.0*MeV,  91.0*MeV,  90.0*MeV,  90.0*MeV },
  {  265.0*MeV, 350.0*MeV,       0.0, 270.0*MeV, 270.0*MeV },
  {  420.0*MeV,  22.7*MeV,  54.9*MeV, 174.0*MeV, 174.0*MeV },
  {  107.0*MeV, 186.7*MeV,  73.0*MeV,  98.5*MeV,  98.5*MeV },
  {  260.0*MeV, 181.0*MeV, 225.0*MeV, 186.0*MeV, 186.0*MeV },
  {  250.0*MeV, 315.0*MeV,       0.0, 320.0*MeV, 320.0*MeV },
  {  161.0*MeV, 168.0*MeV,  87.0*MeV, 159.0*MeV, 159.0*MeV },
  {  400.0*MeV,  55.0*MeV,  85.0*MeV, 260.0*MeV, 260.0*MeV },
  {  400.0*MeV, 215.0*MeV, 150.0*MeV, 236.0*MeV, 236.0*MeV },
  {        0.0, 197.0*MeV, 200.0*MeV, 373.0*MeV, 373.0*MeV }
}
Definition at line 92 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
const G4double G4ExcitedMesonConstructor::widthKdiff static protected
Initial value:
= {
  0.0*MeV,  0.0*MeV, 0.0*MeV, 10.5*MeV, 0.0*MeV,
    0.0*MeV,  0.0*MeV, 0.0*MeV, 0.0*MeV, 0.0*MeV
}
Definition at line 93 of file G4ExcitedMesonConstructor.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ExcitedMesonConstructor.hh
Referenced by ConstructMesons().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedMesonConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/shortlived/src/G4ExcitedMesonConstructor.cc