ECCE @ EIC Software: LBE Class Reference
LBE Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/lists/include/LBE.hh>
Public Member Functions
LBE (G4int ver=1)
virtual ~LBE ()
LBE (const LBE &)=delete
LBE & operator= (const LBE &right)=delete
virtual void SetCuts ()
Public Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList ()
virtual ~G4VModularPhysicsList ()
void RegisterPhysics (G4VPhysicsConstructor *)
const G4VPhysicsConstructor * GetPhysics (G4int index) const
const G4VPhysicsConstructor * GetPhysics (const G4String &name) const
const G4VPhysicsConstructor * GetPhysicsWithType (G4int physics_type) const
void ReplacePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4int type)
void RemovePhysics (const G4String &name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker () override
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
Protected Member Functions
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void ConstructGeneral ()
virtual void ConstructEM ()
virtual void ConstructHad ()
virtual void ConstructOp ()
virtual void AddTransportation ()
Protected Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList (const G4VModularPhysicsList &)
G4VModularPhysicsList & operator= (const G4VModularPhysicsList &)
Protected Member Functions inherited from G4VUserPhysicsList
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Private Member Functions
void ConstructMyBosons ()
void ConstructMyLeptons ()
void ConstructMyMesons ()
void ConstructMyBaryons ()
void ConstructMyIons ()
void ConstructMyShortLiveds ()
Private Attributes
G4int VerboseLevel
G4int OpVerbLevel
G4double cutForGamma
G4double cutForElectron
G4double cutForPositron
G4StoppingPhysics * stoppingPhysics
Additional Inherited Members
Static Public Member Functions inherited from G4VModularPhysicsList
static const G4VMPLManager & GetSubInstanceManager ()
Protected Types inherited from G4VModularPhysicsList
typedef
G4VMPLData::G4PhysConstVectorData G4PhysConstVector
Protected Attributes inherited from G4VModularPhysicsList
G4int verboseLevel
G4int g4vmplInstanceID
Static Protected Attributes inherited from G4VModularPhysicsList
static G4RUN_DLL G4VMPLManager G4VMPLsubInstanceManager
Detailed Description
Definition at line 58 of file LBE.hh.
View newest version in sPHENIX GitHub at line 58 of file LBE.hh
Constructor & Destructor Documentation
LBE::LBE (G4int ver = 1)
Definition at line 77 of file LBE.cc.
View newest version in sPHENIX GitHub at line 77 of file LBE.cc
References cutForElectron, cutForGamma, cutForPositron, G4VUserPhysicsList::defaultCutValue, G4cout, G4endl, CLHEP::micrometer, OpVerbLevel, G4VModularPhysicsList::SetVerboseLevel(), stoppingPhysics, and VerboseLevel.
LBE::~LBE () virtual
Definition at line 102 of file LBE.cc.
View newest version in sPHENIX GitHub at line 102 of file LBE.cc
References stoppingPhysics.
LBE::LBE (const LBE &) delete
Member Function Documentation
void LBE::AddTransportation () protected virtual
Definition at line 216 of file LBE.cc.
View newest version in sPHENIX GitHub at line 216 of file LBE.cc
References G4ProcessManager::AddDiscreteProcess(), G4VUserPhysicsList::AddTransportation(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), particle, and G4ParticleTableIterator< K, V >::reset().
Referenced by ConstructProcess().
void LBE::ConstructEM () protected virtual
Definition at line 286 of file LBE.cc.
View newest version in sPHENIX GitHub at line 286 of file LBE.cc
References G4ProcessManager::AddDiscreteProcess(), G4VEmProcess::AddEmModel(), G4VEnergyLossProcess::AddEmModel(), G4ProcessManager::AddProcess(), charge, fUseDistanceToBoundary, G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::IsShortLived(), CLHEP::MeV, particle, G4ParticleTableIterator< K, V >::reset(), G4VEnergyLossProcess::SetEmModel(), G4VEmModel::SetHighEnergyLimit(), G4VEnergyLossProcess::SetStepFunction(), G4VMultipleScattering::SetStepLimitType(), and CLHEP::um.
Referenced by ConstructProcess().
void LBE::ConstructGeneral () protected virtual
Definition at line 901 of file LBE.cc.
View newest version in sPHENIX GitHub at line 901 of file LBE.cc
References G4EmParameters::AddPhysics(), G4ProcessManager::AddProcess(), G4LossTableManager::AtomDeexcitation(), G4IonTable::Entries(), G4NuclearLevelData::GetInstance(), G4NuclideTable::GetInstance(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetIterator(), G4NuclearLevelData::GetParameters(), G4IonTable::GetParticle(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetProcessManager(), idxAtRest, idxPostStep, G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4EmParameters::Instance(), G4LossTableManager::Instance(), G4Decay::IsApplicable(), G4ParticleDefinition::IsShortLived(), particle, G4ParticleTableIterator< K, V >::reset(), G4LossTableManager::SetAtomDeexcitation(), G4EmParameters::SetAugerCascade(), G4DeexPrecoParameters::SetMaxLifeTime(), G4ProcessManager::SetProcessOrdering(), G4DeexPrecoParameters::SetStoreAllLevels(), G4ProcessManager::SetVerboseLevel(), and VerboseLevel.
Referenced by ConstructProcess().
void LBE::ConstructHad () protected virtual
Definition at line 596 of file LBE.cc.
View newest version in sPHENIX GitHub at line 596 of file LBE.cc
References G4HadronicProcess::AddDataSet(), G4ProcessManager::AddDiscreteProcess(), G4StoppingPhysics::ConstructProcess(), G4ChipsProtonElasticXS::Default_Name(), G4ChipsKaonPlusElasticXS::Default_Name(), G4ChipsKaonMinusInelasticXS::Default_Name(), G4ChipsKaonMinusElasticXS::Default_Name(), G4ChipsNeutronElasticXS::Default_Name(), G4ChipsKaonPlusInelasticXS::Default_Name(), G4ChipsKaonZeroElasticXS::Default_Name(), G4ChipsKaonZeroInelasticXS::Default_Name(), G4NeutronCaptureXS::Default_Name(), G4PionMinus::Definition(), G4PionPlus::Definition(), G4AntiNuclElastic::GetComponentCrossSection(), G4ParticleTable::GetIterator(), G4HadronicParameters::GetMaxEnergy(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), CLHEP::GeV, G4HadronicParameters::Instance(), G4CrossSectionDataSetRegistry::Instance(), CLHEP::MeV, G4Neutron::Neutron(), particle, G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4ParticleTableIterator< K, V >::reset(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetTransport(), and stoppingPhysics.
Referenced by ConstructProcess().
void LBE::ConstructMyBaryons () private
Definition at line 173 of file LBE.cc.
View newest version in sPHENIX GitHub at line 173 of file LBE.cc
References G4BaryonConstructor::ConstructParticle().
Referenced by ConstructParticle().
void LBE::ConstructMyBosons () private
Definition at line 128 of file LBE.cc.
View newest version in sPHENIX GitHub at line 128 of file LBE.cc
References G4ChargedGeantino::ChargedGeantinoDefinition(), G4Gamma::GammaDefinition(), G4Geantino::GeantinoDefinition(), and G4OpticalPhoton::OpticalPhotonDefinition().
Referenced by ConstructParticle().
void LBE::ConstructMyIons () private
Definition at line 183 of file LBE.cc.
View newest version in sPHENIX GitHub at line 183 of file LBE.cc
References G4IonConstructor::ConstructParticle().
Referenced by ConstructParticle().
void LBE::ConstructMyLeptons () private
Definition at line 143 of file LBE.cc.
View newest version in sPHENIX GitHub at line 143 of file LBE.cc
References G4AntiNeutrinoE::AntiNeutrinoEDefinition(), G4AntiNeutrinoMu::AntiNeutrinoMuDefinition(), G4Electron::ElectronDefinition(), G4MuonMinus::MuonMinusDefinition(), G4MuonPlus::MuonPlusDefinition(), G4NeutrinoE::NeutrinoEDefinition(), G4NeutrinoMu::NeutrinoMuDefinition(), and G4Positron::PositronDefinition().
Referenced by ConstructParticle().
void LBE::ConstructMyMesons () private
Definition at line 163 of file LBE.cc.
View newest version in sPHENIX GitHub at line 163 of file LBE.cc
References G4MesonConstructor::ConstructParticle().
Referenced by ConstructParticle().
void LBE::ConstructMyShortLiveds () private
Definition at line 192 of file LBE.cc.
View newest version in sPHENIX GitHub at line 192 of file LBE.cc
Referenced by ConstructParticle().
void LBE::ConstructOp () protected virtual
Definition at line 437 of file LBE.cc.
View newest version in sPHENIX GitHub at line 437 of file LBE.cc
References G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), idxAtRest, idxPostStep, G4Scintillation::IsApplicable(), OpVerbLevel, particle, G4ParticleTableIterator< K, V >::reset(), G4ProcessManager::SetProcessOrderingToLast(), G4Scintillation::SetScintillationExcitationRatio(), G4Scintillation::SetScintillationYieldFactor(), G4Scintillation::SetTrackSecondariesFirst(), and G4VProcess::SetVerboseLevel().
Referenced by ConstructProcess().
void LBE::ConstructParticle (void) protected virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 109 of file LBE.cc.
View newest version in sPHENIX GitHub at line 109 of file LBE.cc
References ConstructMyBaryons(), ConstructMyBosons(), ConstructMyIons(), ConstructMyLeptons(), ConstructMyMesons(), ConstructMyShortLiveds(), G4StoppingPhysics::ConstructParticle(), and stoppingPhysics.
void LBE::ConstructProcess (void) protected virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 202 of file LBE.cc.
View newest version in sPHENIX GitHub at line 202 of file LBE.cc
References AddTransportation(), ConstructEM(), ConstructGeneral(), ConstructHad(), and ConstructOp().
LBE& LBE::operator= (const LBE & right) delete
void LBE::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 967 of file LBE.cc.
View newest version in sPHENIX GitHub at line 967 of file LBE.cc
References cutForElectron, cutForGamma, cutForPositron, G4VUserPhysicsList::defaultCutValue, G4VUserPhysicsList::DumpCutValuesTable(), CLHEP::eV, G4BestUnit, G4cout, G4endl, G4ProductionCutsTable::GetProductionCutsTable(), CLHEP::GeV, G4VUserPhysicsList::SetCutValue(), G4ProductionCutsTable::SetEnergyRange(), and G4VModularPhysicsList::verboseLevel.
Member Data Documentation
G4double LBE::cutForElectron private
Definition at line 101 of file LBE.hh.
View newest version in sPHENIX GitHub at line 101 of file LBE.hh
Referenced by LBE(), and SetCuts().
G4double LBE::cutForGamma private
Definition at line 100 of file LBE.hh.
View newest version in sPHENIX GitHub at line 100 of file LBE.hh
Referenced by LBE(), and SetCuts().
G4double LBE::cutForPositron private
Definition at line 102 of file LBE.hh.
View newest version in sPHENIX GitHub at line 102 of file LBE.hh
Referenced by LBE(), and SetCuts().
G4int LBE::OpVerbLevel private
Definition at line 98 of file LBE.hh.
View newest version in sPHENIX GitHub at line 98 of file LBE.hh
Referenced by ConstructOp(), and LBE().
G4StoppingPhysics* LBE::stoppingPhysics private
Definition at line 108 of file LBE.hh.
View newest version in sPHENIX GitHub at line 108 of file LBE.hh
Referenced by ConstructHad(), ConstructParticle(), LBE(), and ~LBE().
G4int LBE::VerboseLevel private
Definition at line 97 of file LBE.hh.
View newest version in sPHENIX GitHub at line 97 of file LBE.hh
Referenced by ConstructGeneral(), and LBE().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/lists/include/LBE.hh
geant4/tree/geant4-10.6-release/source/physics_lists/lists/src/LBE.cc