ECCE @ EIC Software: F04Materials Class Reference
F04Materials Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04Materials.hh>
Public Member Functions
virtual ~F04Materials ()
G4Material * GetMaterial (G4String)
Static Public Member Functions
static F04Materials * GetInstance ()
Private Member Functions
F04Materials ()
void CreateMaterials ()
Private Attributes
G4NistManager * fNistMan
G4Material * fVacuum
G4Material * fAir
G4Material * fSci
G4Material * fBeO
Static Private Attributes
static F04Materials * fInstance = 0
Detailed Description
Definition at line 38 of file F04Materials.hh.
View newest version in sPHENIX GitHub at line 38 of file F04Materials.hh
Constructor & Destructor Documentation
F04Materials::~F04Materials () virtual
Definition at line 47 of file F04Materials.cc.
View newest version in sPHENIX GitHub at line 47 of file F04Materials.cc
References fAir, fBeO, fSci, and fVacuum.
F04Materials::F04Materials () private
Definition at line 36 of file F04Materials.cc.
View newest version in sPHENIX GitHub at line 36 of file F04Materials.cc
References CreateMaterials(), fNistMan, G4NistManager::Instance(), and G4NistManager::SetVerbose().
Referenced by GetInstance().
Member Function Documentation
void F04Materials::CreateMaterials () private
Definition at line 82 of file F04Materials.cc.
View newest version in sPHENIX GitHub at line 82 of file F04Materials.cc
References cm3, elements, fAir, fBeO, G4NistManager::FindOrBuildMaterial(), fNistMan, fSci, fVacuum, Acts::UnitConstants::g, G4cout, G4endl, and G4Material::GetMaterialTable().
Referenced by F04Materials().
F04Materials * F04Materials::GetInstance (void) static
Definition at line 59 of file F04Materials.cc.
View newest version in sPHENIX GitHub at line 59 of file F04Materials.cc
References F04Materials(), and fInstance.
Referenced by F04DetectorConstruction::Construct().
G4Material * F04Materials::GetMaterial (G4String material)
Definition at line 70 of file F04Materials.cc.
View newest version in sPHENIX GitHub at line 70 of file F04Materials.cc
References G4NistManager::FindOrBuildMaterial(), fNistMan, G4cout, G4endl, G4Material::GetMaterial(), and mat.
Referenced by F04DetectorConstruction::DefineMaterials().
Member Data Documentation
G4Material* F04Materials::fAir private
Definition at line 61 of file F04Materials.hh.
View newest version in sPHENIX GitHub at line 61 of file F04Materials.hh
Referenced by CreateMaterials(), and ~F04Materials().
G4Material* F04Materials::fBeO private
Definition at line 63 of file F04Materials.hh.
View newest version in sPHENIX GitHub at line 63 of file F04Materials.hh
Referenced by CreateMaterials(), and ~F04Materials().
F04Materials * F04Materials::fInstance = 0 static private
Definition at line 56 of file F04Materials.hh.
View newest version in sPHENIX GitHub at line 56 of file F04Materials.hh
Referenced by GetInstance().
G4NistManager* F04Materials::fNistMan private
Definition at line 58 of file F04Materials.hh.
View newest version in sPHENIX GitHub at line 58 of file F04Materials.hh
Referenced by CreateMaterials(), F04Materials(), and GetMaterial().
G4Material* F04Materials::fSci private
Definition at line 62 of file F04Materials.hh.
View newest version in sPHENIX GitHub at line 62 of file F04Materials.hh
Referenced by CreateMaterials(), and ~F04Materials().
G4Material* F04Materials::fVacuum private
Definition at line 60 of file F04Materials.hh.
View newest version in sPHENIX GitHub at line 60 of file F04Materials.hh
Referenced by CreateMaterials(), and ~F04Materials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04Materials.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04Materials.cc