ECCE @ EIC Software: G4tgrElementFromIsotopes Class Reference
G4tgrElementFromIsotopes Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrElementFromIsotopes.hh>
Public Member Functions
G4tgrElementFromIsotopes ()
~G4tgrElementFromIsotopes ()
G4tgrElementFromIsotopes (const std::vector< G4String > &wl)
G4int GetNumberOfIsotopes () const
const G4String & GetComponent (G4int n) const
G4double GetAbundance (G4int n) const
Public Member Functions inherited from G4tgrElement
G4tgrElement ()
virtual ~G4tgrElement ()
const G4String & GetName () const
const G4String & GetSymbol () const
const G4String & GetType () const
Private Attributes
G4int theNoIsotopes
std::vector< G4String > theComponents
std::vector< G4double > theAbundances
Friends
std::ostream & operator<< (std::ostream &, const G4tgrElementFromIsotopes &)
Additional Inherited Members
Protected Attributes inherited from G4tgrElement
G4String theName
G4String theSymbol
G4String theType
Detailed Description
Definition at line 48 of file G4tgrElementFromIsotopes.hh.
View newest version in sPHENIX GitHub at line 48 of file G4tgrElementFromIsotopes.hh
Constructor & Destructor Documentation
G4tgrElementFromIsotopes::G4tgrElementFromIsotopes ()
Definition at line 41 of file G4tgrElementFromIsotopes.cc.
View newest version in sPHENIX GitHub at line 41 of file G4tgrElementFromIsotopes.cc
G4tgrElementFromIsotopes::~G4tgrElementFromIsotopes ()
Definition at line 47 of file G4tgrElementFromIsotopes.cc.
View newest version in sPHENIX GitHub at line 47 of file G4tgrElementFromIsotopes.cc
G4tgrElementFromIsotopes::G4tgrElementFromIsotopes (const std::vector< G4String > & wl)
Definition at line 53 of file G4tgrElementFromIsotopes.cc.
View newest version in sPHENIX GitHub at line 53 of file G4tgrElementFromIsotopes.cc
References G4tgrUtils::CheckWLsize(), G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), theAbundances, theComponents, G4tgrElement::theName, theNoIsotopes, G4tgrElement::theSymbol, G4tgrElement::theType, and WLSIZE_GE.
Member Function Documentation
G4double G4tgrElementFromIsotopes::GetAbundance (G4int n) const inline
Definition at line 61 of file G4tgrElementFromIsotopes.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgrElementFromIsotopes.hh
References n, and theAbundances.
Referenced by G4tgbElement::BuildG4ElementFromIsotopes().
const G4String& G4tgrElementFromIsotopes::GetComponent (G4int n) const inline
Definition at line 60 of file G4tgrElementFromIsotopes.hh.
View newest version in sPHENIX GitHub at line 60 of file G4tgrElementFromIsotopes.hh
References n, and theComponents.
Referenced by G4tgbElement::BuildG4ElementFromIsotopes().
G4int G4tgrElementFromIsotopes::GetNumberOfIsotopes () const inline
Definition at line 59 of file G4tgrElementFromIsotopes.hh.
View newest version in sPHENIX GitHub at line 59 of file G4tgrElementFromIsotopes.hh
References theNoIsotopes.
Referenced by G4tgbElement::BuildG4ElementFromIsotopes().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrElementFromIsotopes & obj) friend
Definition at line 81 of file G4tgrElementFromIsotopes.cc.
View newest version in sPHENIX GitHub at line 81 of file G4tgrElementFromIsotopes.cc
Member Data Documentation
std::vector<G4double> G4tgrElementFromIsotopes::theAbundances private
Definition at line 69 of file G4tgrElementFromIsotopes.hh.
View newest version in sPHENIX GitHub at line 69 of file G4tgrElementFromIsotopes.hh
Referenced by G4tgrElementFromIsotopes(), GetAbundance(), and operator<<().
std::vector<G4String> G4tgrElementFromIsotopes::theComponents private
Definition at line 68 of file G4tgrElementFromIsotopes.hh.
View newest version in sPHENIX GitHub at line 68 of file G4tgrElementFromIsotopes.hh
Referenced by G4tgrElementFromIsotopes(), GetComponent(), and operator<<().
G4int G4tgrElementFromIsotopes::theNoIsotopes private
Definition at line 67 of file G4tgrElementFromIsotopes.hh.
View newest version in sPHENIX GitHub at line 67 of file G4tgrElementFromIsotopes.hh
Referenced by G4tgrElementFromIsotopes(), GetNumberOfIsotopes(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrElementFromIsotopes.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrElementFromIsotopes.cc