ECCE @ EIC Software: G4ParticleHPNBodyPhaseSpace Class Reference
G4ParticleHPNBodyPhaseSpace Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPNBodyPhaseSpace.hh>
Public Member Functions
G4ParticleHPNBodyPhaseSpace ()
~G4ParticleHPNBodyPhaseSpace ()
void Init (G4double aMass, G4int aCount)
void Init (std::istream &aDataFile)
G4ReactionProduct * Sample (G4double anEnergy, G4double massCode, G4double mass)
Public Member Functions inherited from G4VParticleHPEnergyAngular
G4VParticleHPEnergyAngular ()
virtual ~G4VParticleHPEnergyAngular ()
void SetProjectileRP (G4ReactionProduct *aIncidentParticleRP)
void SetTarget (G4ReactionProduct *aTarget)
G4ReactionProduct * GetTarget ()
G4ReactionProduct * GetProjectileRP ()
G4ReactionProduct * GetCMS ()
void SetQValue (G4double aValue)
virtual void ClearHistories ()
Private Member Functions
G4double Prob (G4double anEnergy, G4double eMax, G4int n)
G4double C (G4double anEnergy, G4double mass)
G4double GetEmax (G4double anEnergy, G4double mass)
G4double MeanEnergyOfThisInteraction ()
Private Attributes
G4double theTotalMass
G4int theTotalCount
Additional Inherited Members
Protected Member Functions inherited from G4VParticleHPEnergyAngular
G4double GetQValue ()
Detailed Description
Definition at line 42 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPNBodyPhaseSpace.hh
Constructor & Destructor Documentation
G4ParticleHPNBodyPhaseSpace::G4ParticleHPNBodyPhaseSpace () inline
Definition at line 46 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPNBodyPhaseSpace.hh
References theTotalCount, and theTotalMass.
G4ParticleHPNBodyPhaseSpace::~G4ParticleHPNBodyPhaseSpace () inline
Definition at line 50 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPNBodyPhaseSpace.hh
Member Function Documentation
G4double G4ParticleHPNBodyPhaseSpace::C (G4double anEnergy, G4double mass) inline private
Definition at line 77 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPNBodyPhaseSpace.hh
References GetEmax(), G4Pow::GetInstance(), CLHEP::pi, G4Pow::powA(), G4Pow::powN(), and theTotalCount.
G4double G4ParticleHPNBodyPhaseSpace::GetEmax (G4double anEnergy, G4double mass) inline private
Definition at line 87 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPNBodyPhaseSpace.hh
References G4ReactionProduct::GetMass(), G4VParticleHPEnergyAngular::GetProjectileRP(), G4VParticleHPEnergyAngular::GetQValue(), G4VParticleHPEnergyAngular::GetTarget(), mass, and theTotalMass.
Referenced by C(), and Sample().
void G4ParticleHPNBodyPhaseSpace::Init (G4double aMass, G4int aCount) inline
Definition at line 54 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPNBodyPhaseSpace.hh
References theTotalCount, and theTotalMass.
Referenced by G4ParticleHPInelasticBaseFS::BaseApply().
void G4ParticleHPNBodyPhaseSpace::Init (std::istream & aDataFile) inline virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 60 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPNBodyPhaseSpace.hh
References G4ParticleDefinition::GetPDGMass(), G4Neutron::Neutron(), theTotalCount, and theTotalMass.
G4double G4ParticleHPNBodyPhaseSpace::MeanEnergyOfThisInteraction () inline private virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 97 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPNBodyPhaseSpace.hh
G4double G4ParticleHPNBodyPhaseSpace::Prob (G4double anEnergy, G4double eMax, G4int n) inline private
Definition at line 70 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPNBodyPhaseSpace.hh
References G4Pow::GetInstance(), and G4Pow::powA().
Referenced by Sample().
G4ReactionProduct * G4ParticleHPNBodyPhaseSpace::Sample (G4double anEnergy, G4double massCode, G4double mass) virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 44 of file G4ParticleHPNBodyPhaseSpace.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPNBodyPhaseSpace.cc
References A(), G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4Electron::Electron(), energy, CLHEP::eV, G4cout, G4endl, G4UniformRand, G4Gamma::Gamma(), GetEmax(), G4ReactionProduct::GetMass(), G4VParticleHPEnergyAngular::GetProjectileRP(), G4VParticleHPEnergyAngular::GetTarget(), G4ReactionProduct::GetTotalMomentum(), G4He3::He3(), G4ReactionProduct::Lorentz(), max, maxE, G4Neutron::Neutron(), phi, G4Positron::Positron(), Prob(), G4Proton::Proton(), G4ReactionProduct::SetDefinition(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), theta(), theTotalCount, G4Triton::Triton(), twopi, and Z.
Referenced by G4ParticleHPInelasticBaseFS::BaseApply().
Member Data Documentation
G4int G4ParticleHPNBodyPhaseSpace::theTotalCount private
Definition at line 102 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ParticleHPNBodyPhaseSpace.hh
Referenced by C(), G4ParticleHPNBodyPhaseSpace(), Init(), and Sample().
G4double G4ParticleHPNBodyPhaseSpace::theTotalMass private
Definition at line 101 of file G4ParticleHPNBodyPhaseSpace.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPNBodyPhaseSpace.hh
Referenced by G4ParticleHPNBodyPhaseSpace(), GetEmax(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPNBodyPhaseSpace.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPNBodyPhaseSpace.cc