ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/xDataTOM_interpolation.cc File Reference
xDataTOM_interpolation.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Macros
#define dependentAxis 1
#define allowByRegion 2
Functions
static enum
xDataTOM_interpolationFlag xDataTOM_interpolation_getFromString (statusMessageReporting *smr, char const *s, char const **e, char const *str, int flag)
int xDataTOM_interpolation_set (statusMessageReporting *smr, xDataTOM_interpolation *interpolation, enum xDataTOM_interpolationFlag independent, enum xDataTOM_interpolationFlag dependent, enum xDataTOM_interpolationQualifier qualifier)
int xDataTOM_interpolation_setFromString (statusMessageReporting *smr, xDataTOM_interpolation *interpolation, char const *str)
int xDataTOM_interpolation_copy (statusMessageReporting *smr, xDataTOM_interpolation *desc, xDataTOM_interpolation *src)
Macro Definition Documentation
#define allowByRegion 2
Definition at line 15 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 15 of file xDataTOM_interpolation.cc
Referenced by xDataTOM_interpolation_getFromString().
#define dependentAxis 1
Definition at line 14 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 14 of file xDataTOM_interpolation.cc
Referenced by xDataTOM_interpolation_getFromString(), and xDataTOM_interpolation_setFromString().
Function Documentation
int xDataTOM_interpolation_copy (statusMessageReporting * smr, xDataTOM_interpolation * desc, xDataTOM_interpolation * src)
Definition at line 102 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 102 of file xDataTOM_interpolation.cc
References xDataTOM_interpolation_s::dependent, xDataTOM_interpolation_s::qualifier, and xDataTOM_interpolation_set().
Referenced by xDataTOM_axis_initialize(), and xDataTOM_subAxes_initialize().
static enum xDataTOM_interpolationFlag xDataTOM_interpolation_getFromString (statusMessageReporting * smr, char const * s, char const ** e, char const * str, int flag) static
Definition at line 80 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 80 of file xDataTOM_interpolation.cc
References allowByRegion, dependentAxis, smr_setReportError2, xDataTOM_interpolationFlag_byRegion, xDataTOM_interpolationFlag_flat, xDataTOM_interpolationFlag_invalid, xDataTOM_interpolationFlag_linear, xDataTOM_interpolationFlag_log, and xDataTOM_smrLibraryID.
Referenced by xDataTOM_interpolation_setFromString().
int xDataTOM_interpolation_set (statusMessageReporting * smr, xDataTOM_interpolation * interpolation, enum xDataTOM_interpolationFlag independent, enum xDataTOM_interpolationFlag dependent, enum xDataTOM_interpolationQualifier qualifier)
Definition at line 22 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_interpolation.cc
References xDataTOM_interpolation_s::dependent, xDataTOM_interpolation_s::qualifier, smr_setReportError2, xDataTOM_interpolationFlag_byRegion, xDataTOM_interpolationFlag_flat, xDataTOM_interpolationFlag_linear, xDataTOM_interpolationQualifier_correspondingPoints, xDataTOM_interpolationQualifier_invalid, and xDataTOM_smrLibraryID.
Referenced by xDataTOM_interpolation_copy(), xDataTOM_interpolation_setFromString(), xDataTOM_subAxes_initialize(), and xDataXML_axesToTOM().
int xDataTOM_interpolation_setFromString (statusMessageReporting * smr, xDataTOM_interpolation * interpolation, char const * str)
Definition at line 46 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 46 of file xDataTOM_interpolation.cc
References c, dependentAxis, e, smr_setReportError2, xDataTOM_interpolation_getFromString(), xDataTOM_interpolation_set(), xDataTOM_interpolationFlag_invalid, xDataTOM_interpolationQualifier_correspondingPoints, xDataTOM_interpolationQualifier_none, xDataTOM_interpolationQualifier_unitBase, and xDataTOM_smrLibraryID.
Referenced by xDataXML_axesToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), and xDataXML_regionsXYs_regionToTOM().