ECCE @ EIC Software: G4VisCommandSetColour Class Reference
G4VisCommandSetColour Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSet.hh>
Public Member Functions
G4VisCommandSetColour ()
virtual ~G4VisCommandSetColour ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VVisCommand
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4VisCommandSetColour (const G4VisCommandSetColour &)
G4VisCommandSetColour & operator= (const G4VisCommandSetColour &)
Private Attributes
G4UIcommand * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Member Functions inherited from G4VVisCommand
void SetViewParameters (G4VViewer *viewer, const G4ViewParameters &viewParams)
void RefreshIfRequired (G4VViewer *viewer)
void InterpolateViews (G4VViewer *currentViewer, std::vector< G4ViewParameters > viewVector, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
void InterpolateToNewView (G4VViewer *currentViewer, const G4ViewParameters &oldVP, const G4ViewParameters &newVP, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
const G4String & ConvertToColourGuidance ()
void ConvertToColour (G4Colour &colour, const G4String &redOrString, G4double green, G4double blue, G4double opacity)
G4bool ProvideValueOfUnit (const G4String &where, const G4String &unit, const G4String &category, G4double &value)
void CheckSceneAndNotifyHandlers (G4Scene *=nullptr)
void G4VisCommandsSceneAddUnsuccessful (G4VisManager::Verbosity verbosity)
void CopyGuidanceFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd, G4int startLine=0)
void CopyParametersFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd)
void DrawExtent (const G4VisExtent &)
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommand
static G4VisManager * fpVisManager = 0
static G4int fErrorCode = 0
static G4int fCurrentArrow3DLineSegmentsPerCircle = 6
static G4Colour fCurrentColour = G4Colour::White()
static G4double fCurrentLineWidth = 1.
static G4Colour fCurrentTextColour = G4Colour::Blue()
static G4Text::Layout fCurrentTextLayout = G4Text::left
static G4double fCurrentTextSize = 12.
static
G4PhysicalVolumeModel::TouchableProperties fCurrentTouchableProperties
static G4VisExtent fCurrentExtentForField
static std::vector
< G4PhysicalVolumesSearchScene::Findings > fCurrrentPVFindingsForField
Detailed Description
Definition at line 53 of file G4VisCommandsSet.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VisCommandsSet.hh
Constructor & Destructor Documentation
G4VisCommandSetColour::G4VisCommandSetColour ()
Definition at line 84 of file G4VisCommandsSet.cc.
View newest version in sPHENIX GitHub at line 84 of file G4VisCommandsSet.cc
References G4VVisCommand::ConvertToColourGuidance(), fpCommand, G4UIparameter::SetDefaultValue(), G4UIparameter::SetGuidance(), G4UIcommand::SetGuidance(), and G4UIcommand::SetParameter().
G4VisCommandSetColour::~G4VisCommandSetColour () virtual
Definition at line 112 of file G4VisCommandsSet.cc.
View newest version in sPHENIX GitHub at line 112 of file G4VisCommandsSet.cc
References fpCommand.
G4VisCommandSetColour::G4VisCommandSetColour (const G4VisCommandSetColour &) private
Member Function Documentation
G4String G4VisCommandSetColour::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 117 of file G4VisCommandsSet.cc.
View newest version in sPHENIX GitHub at line 117 of file G4VisCommandsSet.cc
G4VisCommandSetColour& G4VisCommandSetColour::operator= (const G4VisCommandSetColour &) private
void G4VisCommandSetColour::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 122 of file G4VisCommandsSet.cc.
View newest version in sPHENIX GitHub at line 122 of file G4VisCommandsSet.cc
References G4VisManager::confirmations, G4VVisCommand::ConvertToColour(), G4VVisCommand::fCurrentColour, G4VVisCommand::fpVisManager, G4cout, G4endl, and G4VisManager::GetVerbosity().
Member Data Documentation
G4UIcommand* G4VisCommandSetColour::fpCommand private
Definition at line 62 of file G4VisCommandsSet.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VisCommandsSet.hh
Referenced by G4VisCommandSetColour(), and ~G4VisCommandSetColour().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSet.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsSet.cc