ECCE @ EIC Software: G4Isotope Class Reference
G4Isotope Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4Isotope.hh>
Public Member Functions
G4Isotope (const G4String &name, G4int z, G4int n, G4double a=0., G4int m=0)
virtual ~G4Isotope ()
const G4String & GetName () const
G4int GetZ () const
G4int GetN () const
G4double GetA () const
G4int Getm () const
size_t GetIndex () const
G4bool operator== (const G4Isotope &) const
G4bool operator!= (const G4Isotope &) const
G4Isotope (__void__ &)
void SetName (const G4String &name)
Static Public Member Functions
static G4Isotope * GetIsotope (const G4String &name, G4bool warning=false)
static const G4IsotopeTable * GetIsotopeTable ()
static size_t GetNumberOfIsotopes ()
Private Member Functions
G4Isotope (G4Isotope &)
G4Isotope & operator= (const G4Isotope &)
Private Attributes
G4String fName
G4int fZ
G4int fN
G4double fA
G4int fm
size_t fIndexInTable
Static Private Attributes
static G4IsotopeTable theIsotopeTable
Friends
std::ostream & operator<< (std::ostream &, const G4Isotope *)
std::ostream & operator<< (std::ostream &, const G4Isotope &)
std::ostream & operator<< (std::ostream &, G4IsotopeTable)
Detailed Description
Definition at line 71 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Isotope.hh
Constructor & Destructor Documentation
G4Isotope::G4Isotope (const G4String & name, G4int z, G4int n, G4double a = 0., G4int m = 0)
Definition at line 58 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 58 of file G4Isotope.cc
References CLHEP::amu_c2, fA, FatalException, fIndexInTable, CLHEP::g, G4endl, G4Exception(), G4NistManager::GetAtomicMass(), G4NistManager::Instance(), CLHEP::mole, and theIsotopeTable.
G4Isotope::~G4Isotope () virtual
Definition at line 91 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 91 of file G4Isotope.cc
References fIndexInTable, and theIsotopeTable.
G4Isotope::G4Isotope (__void__ &)
Definition at line 84 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 84 of file G4Isotope.cc
G4Isotope::G4Isotope (G4Isotope & right) private
Definition at line 98 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 98 of file G4Isotope.cc
References fIndexInTable, right, and theIsotopeTable.
Member Function Documentation
G4double G4Isotope::GetA () const inline
Definition at line 96 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Isotope.hh
References fA.
Referenced by G4tgbGeometryDumper::DumpIsotope(), export_G4Isotope(), G4GDMLWriteMaterials::IsotopeWrite(), PHG4GDMLWriteMaterials::IsotopeWrite(), and G4tgbGeometryDumper::Same2G4Isotopes().
size_t G4Isotope::GetIndex () const inline
Definition at line 110 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 110 of file G4Isotope.hh
References fIndexInTable.
Referenced by export_G4Isotope().
G4Isotope * G4Isotope::GetIsotope (const G4String & name, G4bool warning = false) static
Definition at line 195 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 195 of file G4Isotope.cc
References G4cout, G4endl, GetName(), and theIsotopeTable.
Referenced by export_G4Isotope(), and G4GDMLReadMaterials::GetIsotope().
const G4IsotopeTable * G4Isotope::GetIsotopeTable () static
Definition at line 181 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 181 of file G4Isotope.cc
References theIsotopeTable.
Referenced by export_G4Isotope(), and G4NistManager::~G4NistManager().
G4int G4Isotope::Getm () const inline
Definition at line 99 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 99 of file G4Isotope.hh
References fm.
Referenced by G4LENDorBERTModel::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4LENDCrossSection::GetIsoCrossSection(), G4ParticleHPElementData::Init(), and G4ParticleHPChannel::Register().
G4int G4Isotope::GetN () const inline
Definition at line 93 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 93 of file G4Isotope.hh
References fN.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4ParticleHPJENDLHEData::BuildPhysicsTable(), G4Nucleus::ChooseParameters(), G4VCrossSectionDataSet::ComputeCrossSection(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4tgbGeometryDumper::DumpIsotope(), export_G4Isotope(), G4ParticleHPJENDLHEData::GetCrossSection(), G4CrossSectionDataStore::GetCrossSection(), G4MuNeutrinoNucleusTotXsc::GetElementCrossSection(), G4ParticleHPElementData::Init(), G4LENDCrossSection::IsIsoApplicable(), G4GDMLWriteMaterials::IsotopeWrite(), PHG4GDMLWriteMaterials::IsotopeWrite(), G4ParticleHPChannel::Register(), G4tgbGeometryDumper::Same2G4Isotopes(), G4CrossSectionDataStore::SampleZandA(), G4ParticleInelasticXS::SelectIsotope(), G4NeutronInelasticXS::SelectIsotope(), G4NeutronElasticXS::SelectIsotope(), G4NeutronCaptureXS::SelectIsotope(), G4VEmModel::SelectIsotopeNumber(), G4ElementSelector::SelectZandA(), G4Nucleus::SetIsotope(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
const G4String& G4Isotope::GetName (void) const inline
Definition at line 87 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 87 of file G4Isotope.hh
References fName.
Referenced by G4GDMLWriteMaterials::ElementWrite(), PHG4GDMLWriteMaterials::ElementWrite(), export_G4Isotope(), G4tgbMaterialMgr::FindOrBuildG4Isotope(), GetIsotope(), G4tgbGeometryDumper::GetIsotopeName(), G4GDMLWriteMaterials::IsotopeWrite(), PHG4GDMLWriteMaterials::IsotopeWrite(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
size_t G4Isotope::GetNumberOfIsotopes () static
Definition at line 188 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 188 of file G4Isotope.cc
References theIsotopeTable.
Referenced by export_G4Isotope().
G4int G4Isotope::GetZ () const inline
Definition at line 90 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 90 of file G4Isotope.hh
References fZ.
Referenced by G4Element::AddIsotope(), G4Nucleus::ChooseParameters(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4tgbGeometryDumper::DumpIsotope(), export_G4Isotope(), G4GDMLWriteMaterials::IsotopeWrite(), PHG4GDMLWriteMaterials::IsotopeWrite(), G4tgbGeometryDumper::Same2G4Isotopes(), G4Nucleus::SetIsotope(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
G4bool G4Isotope::operator!= (const G4Isotope & right) const
Definition at line 131 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 131 of file G4Isotope.cc
G4Isotope & G4Isotope::operator= (const G4Isotope & right) private
Definition at line 109 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 109 of file G4Isotope.cc
References fA, fm, fN, fName, and fZ.
G4bool G4Isotope::operator== (const G4Isotope & right) const
Definition at line 124 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 124 of file G4Isotope.cc
void G4Isotope::SetName (const G4String & name) inline
Definition at line 131 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 131 of file G4Isotope.hh
References fName.
Referenced by export_G4Isotope().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & flux, const G4Isotope * isotope) friend
Definition at line 138 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 138 of file G4Isotope.cc
std::ostream& operator<< (std::ostream & flux, const G4Isotope & isotope) friend
Definition at line 158 of file G4Isotope.cc.
View newest version in sPHENIX GitHub at line 158 of file G4Isotope.cc
std::ostream& operator<< (std::ostream & flux, G4IsotopeTable ElementTable) friend
Definition at line 466 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 466 of file G4Element.cc
Member Data Documentation
G4double G4Isotope::fA private
Definition at line 143 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 143 of file G4Isotope.hh
Referenced by G4Isotope(), GetA(), operator<<(), and operator=().
size_t G4Isotope::fIndexInTable private
Definition at line 149 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 149 of file G4Isotope.hh
Referenced by G4Isotope(), GetIndex(), and ~G4Isotope().
G4int G4Isotope::fm private
Definition at line 144 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 144 of file G4Isotope.hh
Referenced by Getm(), and operator=().
G4int G4Isotope::fN private
Definition at line 142 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 142 of file G4Isotope.hh
Referenced by GetN(), operator<<(), and operator=().
G4String G4Isotope::fName private
Definition at line 140 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 140 of file G4Isotope.hh
Referenced by GetName(), operator<<(), operator=(), and SetName().
G4int G4Isotope::fZ private
Definition at line 141 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 141 of file G4Isotope.hh
Referenced by GetZ(), operator<<(), and operator=().
G4IsotopeTable G4Isotope::theIsotopeTable static private
Definition at line 147 of file G4Isotope.hh.
View newest version in sPHENIX GitHub at line 147 of file G4Isotope.hh
Referenced by G4Isotope(), GetIsotope(), GetIsotopeTable(), GetNumberOfIsotopes(), and ~G4Isotope().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4Isotope.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4Isotope.cc