ECCE @ EIC Software: G4PreCompoundEmission Class Reference
G4PreCompoundEmission Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundEmission.hh>
Public Member Functions
G4PreCompoundEmission ()
~G4PreCompoundEmission ()
void SetDefaultModel ()
void SetHETCModel ()
G4ReactionProduct * PerformEmission (G4Fragment &aFragment)
G4double GetTotalProbability (const G4Fragment &aFragment)
void SetOPTxs (G4int)
void UseSICB (G4bool)
Private Member Functions
void AngularDistribution (G4VPreCompoundFragment *theFragment, const G4Fragment &aFragment, G4double KineticEnergy)
G4double rho (G4int p, G4int h, G4double gg, G4double E, G4double Ef) const
G4PreCompoundEmission (const G4PreCompoundEmission &right)
const G4PreCompoundEmission & operator= (const G4PreCompoundEmission &right)
G4bool operator== (const G4PreCompoundEmission &right) const
G4bool operator!= (const G4PreCompoundEmission &right) const
Private Attributes
G4Pow * g4calc
G4NuclearLevelData * fNuclData
G4double fFermiEnergy
G4PreCompoundFragmentVector * theFragmentsVector
G4VPreCompoundEmissionFactory * theFragmentsFactory
G4ThreeVector theFinalMomentum
G4bool fUseAngularGenerator
Detailed Description
Definition at line 50 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 50 of file G4PreCompoundEmission.hh
Constructor & Destructor Documentation
G4PreCompoundEmission::G4PreCompoundEmission ()
Definition at line 58 of file G4PreCompoundEmission.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PreCompoundEmission.cc
References fFermiEnergy, fNuclData, fUseAngularGenerator, g4calc, G4DeexPrecoParameters::GetFermiEnergy(), G4VPreCompoundEmissionFactory::GetFragmentVector(), G4Pow::GetInstance(), G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetParameters(), theFragmentsFactory, theFragmentsVector, and G4DeexPrecoParameters::UseAngularGen().
G4PreCompoundEmission::~G4PreCompoundEmission ()
Definition at line 70 of file G4PreCompoundEmission.cc.
View newest version in sPHENIX GitHub at line 70 of file G4PreCompoundEmission.cc
References theFragmentsFactory, and theFragmentsVector.
G4PreCompoundEmission::G4PreCompoundEmission (const G4PreCompoundEmission & right) private
Member Function Documentation
void G4PreCompoundEmission::AngularDistribution (G4VPreCompoundFragment * theFragment, const G4Fragment & aFragment, G4double KineticEnergy) private
Definition at line 173 of file G4PreCompoundEmission.cc.
View newest version in sPHENIX GitHub at line 173 of file G4PreCompoundEmission.cc
References G4InuclParticleNames::an, DBL_MIN, fFermiEnergy, fNuclData, G4Exp(), G4Log(), G4UniformRand, G4Fragment::GetA_asInt(), G4VPreCompoundFragment::GetBindingEnergy(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetMomentum(), G4VPreCompoundFragment::GetNuclearMass(), G4Fragment::GetNumberOfExcitons(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), G4Fragment::GetZ_asInt(), Acts::UnitConstants::h, max, MeV, phi, pi2, rho(), CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), theFinalMomentum, CLHEP::twopi, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Referenced by PerformEmission().
G4double G4PreCompoundEmission::GetTotalProbability (const G4Fragment & aFragment) inline
Definition at line 103 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 103 of file G4PreCompoundEmission.hh
References G4PreCompoundFragmentVector::CalculateProbabilities(), and theFragmentsVector.
Referenced by G4PreCompoundModel::DeExcite().
G4bool G4PreCompoundEmission::operator!= (const G4PreCompoundEmission & right) const private
const G4PreCompoundEmission& G4PreCompoundEmission::operator= (const G4PreCompoundEmission & right) private
G4bool G4PreCompoundEmission::operator== (const G4PreCompoundEmission & right) const private
G4ReactionProduct * G4PreCompoundEmission::PerformEmission (G4Fragment & aFragment)
Definition at line 101 of file G4PreCompoundEmission.cc.
View newest version in sPHENIX GitHub at line 101 of file G4PreCompoundEmission.cc
References AngularDistribution(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4PreCompoundFragmentVector::ChooseFragment(), fUseAngularGenerator, G4cout, G4endl, G4RandomDirection(), G4VPreCompoundFragment::GetA(), G4Fragment::GetMomentum(), G4VPreCompoundFragment::GetNuclearMass(), G4Fragment::GetNumberOfCharged(), G4Fragment::GetNumberOfParticles(), G4VPreCompoundFragment::GetReactionProduct(), G4VPreCompoundFragment::GetRestA(), G4VPreCompoundFragment::GetRestZ(), G4VPreCompoundFragment::GetZ(), max, G4VPreCompoundFragment::SampleKineticEnergy(), G4VPreCompoundFragment::SetMomentum(), G4Fragment::SetMomentum(), G4Fragment::SetNumberOfCharged(), G4Fragment::SetNumberOfParticles(), G4Fragment::SetZandA_asInt(), theFinalMomentum, and theFragmentsVector.
Referenced by G4PreCompoundModel::DeExcite().
G4double G4PreCompoundEmission::rho (G4int p, G4int h, G4double gg, G4double E, G4double Ef) const private
Definition at line 258 of file G4PreCompoundEmission.cc.
View newest version in sPHENIX GitHub at line 258 of file G4PreCompoundEmission.cc
References g4calc, G4Exp(), G4Log(), Acts::UnitConstants::h, G4Pow::logfactorial(), t1, and t2.
Referenced by AngularDistribution().
void G4PreCompoundEmission::SetDefaultModel ()
Definition at line 76 of file G4PreCompoundEmission.cc.
View newest version in sPHENIX GitHub at line 76 of file G4PreCompoundEmission.cc
References G4VPreCompoundEmissionFactory::GetFragmentVector(), G4PreCompoundFragmentVector::SetVector(), theFragmentsFactory, and theFragmentsVector.
void G4PreCompoundEmission::SetHETCModel ()
Definition at line 88 of file G4PreCompoundEmission.cc.
View newest version in sPHENIX GitHub at line 88 of file G4PreCompoundEmission.cc
References G4VPreCompoundEmissionFactory::GetFragmentVector(), G4PreCompoundFragmentVector::SetVector(), theFragmentsFactory, and theFragmentsVector.
Referenced by G4PreCompoundModel::InitialiseModel().
void G4PreCompoundEmission::SetOPTxs (G4int opt) inline
Definition at line 108 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PreCompoundEmission.hh
References G4PreCompoundFragmentVector::SetOPTxs(), and theFragmentsVector.
Referenced by G4PreCompoundModel::InitialiseModel().
void G4PreCompoundEmission::UseSICB (G4bool use) inline
Definition at line 113 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PreCompoundEmission.hh
References theFragmentsVector, and G4PreCompoundFragmentVector::UseSICB().
Member Data Documentation
G4double G4PreCompoundEmission::fFermiEnergy private
Definition at line 91 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PreCompoundEmission.hh
Referenced by AngularDistribution(), and G4PreCompoundEmission().
G4NuclearLevelData* G4PreCompoundEmission::fNuclData private
Definition at line 89 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 89 of file G4PreCompoundEmission.hh
Referenced by AngularDistribution(), and G4PreCompoundEmission().
G4bool G4PreCompoundEmission::fUseAngularGenerator private
Definition at line 99 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 99 of file G4PreCompoundEmission.hh
Referenced by G4PreCompoundEmission(), and PerformEmission().
G4Pow* G4PreCompoundEmission::g4calc private
Definition at line 88 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PreCompoundEmission.hh
Referenced by G4PreCompoundEmission(), and rho().
G4ThreeVector G4PreCompoundEmission::theFinalMomentum private
Definition at line 98 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 98 of file G4PreCompoundEmission.hh
Referenced by AngularDistribution(), and PerformEmission().
G4VPreCompoundEmissionFactory* G4PreCompoundEmission::theFragmentsFactory private
Definition at line 95 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PreCompoundEmission.hh
Referenced by G4PreCompoundEmission(), SetDefaultModel(), SetHETCModel(), and ~G4PreCompoundEmission().
G4PreCompoundFragmentVector* G4PreCompoundEmission::theFragmentsVector private
Definition at line 94 of file G4PreCompoundEmission.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PreCompoundEmission.hh
Referenced by G4PreCompoundEmission(), GetTotalProbability(), PerformEmission(), SetDefaultModel(), SetHETCModel(), SetOPTxs(), UseSICB(), and ~G4PreCompoundEmission().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundEmission.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4PreCompoundEmission.cc