ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4Fragment.cc File Reference
G4Fragment.cc File Reference
#include "G4Fragment.hh"
#include "G4HadronicException.hh"
#include "G4ios.hh"
#include <iomanip>
Functions
G4Allocator< G4Fragment > *& pFragmentAllocator ()
std::ostream & operator<< (std::ostream &out, const G4Fragment &theFragment)
Function Documentation
std::ostream& operator<< (std::ostream & out, const G4Fragment & theFragment)
Definition at line 181 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 181 of file G4Fragment.cc
References G4endl, G4Fragment::GetCreationTime(), G4Fragment::GetCreatorModelType(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetFloatingLevelNumber(), G4Fragment::GetMomentum(), G4Fragment::GetNuclearPolarization(), G4Fragment::GetNumberOfCharged(), G4Fragment::GetNumberOfChargedHoles(), G4Fragment::GetNumberOfExcitons(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), G4Fragment::GetSpin(), CLHEP::MeV, CLHEP::ns, CLHEP::HepLorentzVector::t(), G4Fragment::theA, G4Fragment::theZ, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
G4Allocator<G4Fragment>*& pFragmentAllocator ()
Definition at line 45 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 45 of file G4Fragment.cc
References G4ThreadLocalStatic.
Referenced by G4Fragment::operator delete(), and G4Fragment::operator new().