ECCE @ EIC Software: G4GammaTransition Class Reference
G4GammaTransition Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/include/G4GammaTransition.hh>
Public Member Functions
G4GammaTransition ()
virtual ~G4GammaTransition ()
virtual G4Fragment * SampleTransition (G4Fragment *nucleus, G4double newExcEnergy, G4double mpRatio, G4int JP1, G4int JP2, G4int MP, G4int shell, G4bool isDiscrete, G4bool isGamma)
virtual void SampleDirection (G4Fragment *nuc, G4double ratio, G4int twoJ1, G4int twoJ2, G4int mp)
void SetPolarizationFlag (G4bool val)
void SetTwoJMAX (G4int val)
void SetVerbose (G4int val)
Protected Attributes
G4ThreeVector fDirection
G4PolarizationTransition fPolTrans
G4int fTwoJMAX
G4int fVerbose
Private Member Functions
G4GammaTransition (const G4GammaTransition &right)=delete
const G4GammaTransition & operator= (const G4GammaTransition &right)=delete
G4bool operator== (const G4GammaTransition &right) const =delete
G4bool operator!= (const G4GammaTransition &right) const =delete
Private Attributes
G4bool polarFlag
Detailed Description
Definition at line 52 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 52 of file G4GammaTransition.hh
Constructor & Destructor Documentation
G4GammaTransition::G4GammaTransition () explicit
Definition at line 48 of file G4GammaTransition.cc.
View newest version in sPHENIX GitHub at line 48 of file G4GammaTransition.cc
G4GammaTransition::~G4GammaTransition () virtual
Definition at line 52 of file G4GammaTransition.cc.
View newest version in sPHENIX GitHub at line 52 of file G4GammaTransition.cc
G4GammaTransition::G4GammaTransition (const G4GammaTransition & right) private delete
Member Function Documentation
G4bool G4GammaTransition::operator!= (const G4GammaTransition & right) const private delete
const G4GammaTransition& G4GammaTransition::operator= (const G4GammaTransition & right) private delete
G4bool G4GammaTransition::operator== (const G4GammaTransition & right) const private delete
void G4GammaTransition::SampleDirection (G4Fragment * nuc, G4double ratio, G4int twoJ1, G4int twoJ2, G4int mp) virtual
Definition at line 152 of file G4GammaTransition.cc.
View newest version in sPHENIX GitHub at line 152 of file G4GammaTransition.cc
References fDirection, fPolTrans, fVerbose, G4cout, G4endl, G4UniformRand, G4Fragment::GetNuclearPolarization(), phi, ratio, G4PolarizationTransition::SampleGammaTransition(), CLHEP::Hep3Vector::set(), and CLHEP::twopi.
Referenced by SampleTransition().
G4Fragment * G4GammaTransition::SampleTransition (G4Fragment * nucleus, G4double newExcEnergy, G4double mpRatio, G4int JP1, G4int JP2, G4int MP, G4int shell, G4bool isDiscrete, G4bool isGamma) virtual
Definition at line 56 of file G4GammaTransition.cc.
View newest version in sPHENIX GitHub at line 56 of file G4GammaTransition.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4Electron::Electron(), CLHEP::electron_mass_c2, energy, fDirection, fTwoJMAX, fVerbose, G4cout, G4endl, G4RandomDirection(), G4Gamma::Gamma(), G4AtomicShells::GetBindingEnergy(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetGroundStateMass(), G4Fragment::GetMomentum(), G4Fragment::GetNumberOfElectrons(), G4AtomicShells::GetNumberOfShells(), G4ParticleDefinition::GetPDGMass(), G4Fragment::GetZ_asInt(), incremental_prev_tag::idx, CLHEP::HepLorentzVector::mag(), mass, max, min, mom, part, polarFlag, SampleDirection(), CLHEP::HepLorentzVector::set(), G4Fragment::SetExcEnergyAndMomentum(), G4Fragment::SetNumberOfElectrons(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
Referenced by G4PhotonEvaporation::GenerateGamma().
void G4GammaTransition::SetPolarizationFlag (G4bool val) inline
Definition at line 73 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 73 of file G4GammaTransition.hh
References polarFlag.
Referenced by G4PhotonEvaporation::Initialise().
void G4GammaTransition::SetTwoJMAX (G4int val) inline
Definition at line 75 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 75 of file G4GammaTransition.hh
References fTwoJMAX.
Referenced by G4PhotonEvaporation::Initialise().
void G4GammaTransition::SetVerbose (G4int val) inline
Definition at line 77 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 77 of file G4GammaTransition.hh
References fPolTrans, fVerbose, and G4PolarizationTransition::SetVerbose().
Referenced by G4PhotonEvaporation::Initialise().
Member Data Documentation
G4ThreeVector G4GammaTransition::fDirection protected
Definition at line 90 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 90 of file G4GammaTransition.hh
Referenced by SampleDirection(), and SampleTransition().
G4PolarizationTransition G4GammaTransition::fPolTrans protected
Definition at line 91 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 91 of file G4GammaTransition.hh
Referenced by SampleDirection(), and SetVerbose().
G4int G4GammaTransition::fTwoJMAX protected
Definition at line 92 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 92 of file G4GammaTransition.hh
Referenced by SampleTransition(), and SetTwoJMAX().
G4int G4GammaTransition::fVerbose protected
Definition at line 93 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 93 of file G4GammaTransition.hh
Referenced by SampleDirection(), SampleTransition(), and SetVerbose().
G4bool G4GammaTransition::polarFlag private
Definition at line 86 of file G4GammaTransition.hh.
View newest version in sPHENIX GitHub at line 86 of file G4GammaTransition.hh
Referenced by SampleTransition(), and SetPolarizationFlag().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/include/G4GammaTransition.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/src/G4GammaTransition.cc