ECCE @ EIC Software: PrimaryGeneratorMessenger Class Reference
PrimaryGeneratorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/PrimaryGeneratorMessenger.hh>
Public Member Functions
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *gen)
virtual ~PrimaryGeneratorMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValue)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
virtual ~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
~PrimaryGeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
PrimaryGeneratorMessenger & operator= (const PrimaryGeneratorMessenger &right)
PrimaryGeneratorMessenger (const PrimaryGeneratorMessenger &)
Private Attributes
PrimaryGeneratorAction * Action
G4UIdirectory * gunDir
G4UIcmdWithoutParameter * DefaultCmd
G4UIcmdWithADoubleAndUnit * RndmCmd
PrimaryGeneratorAction * fAction
G4UIdirectory * fGunDir
G4UIcmdWithAnInteger * fEmissionCmd
G4UIcmdWithAnInteger * fDefaultCmd
G4UIcmdWithADouble * fRndmCmd
G4UIcmdWithoutParameter * fDefaultCmd
G4UIcmdWithADoubleAndUnit * fRndmCmd
G4UIcmdWithABool * fRndmCmd
G4UIdirectory * fDir
G4UIcmdWithAnInteger * fSelectActionCmd
G4UIcmdWithADouble * fBeam
PrimaryGeneratorAction * fGen
G4bool fVerbose
G4UIcmdWithADoubleAndUnit * fBeamXCmd
G4UIcmdWithADoubleAndUnit * fBeamYCmd
G4UIcmdWithADoubleAndUnit * fBeamZCmd
G4UIcmdWithADoubleAndUnit * fBeamECmd
G4UIcmdWithADoubleAndUnit * fSigmaXCmd
G4UIcmdWithADoubleAndUnit * fSigmaYCmd
G4UIcmdWithADoubleAndUnit * fSigmaZCmd
G4UIcmdWithADoubleAndUnit * fSigmaECmd
G4UIcmdWithAString * fRandCmd
G4UIcmdWithADoubleAndUnit * fMaxThetaCmd
G4UIcmdWithADoubleAndUnit * fThetaCmd
PrimaryGeneratorAction * fPrimaryAction
G4UIcmdWithADoubleAndUnit * fPolarCmd
G4UIcmdWithADoubleAndUnit * fTimeCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 43 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 43 of file PrimaryGeneratorMessenger.hh
Constructor & Destructor Documentation
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction * Gun)
Definition at line 39 of file PrimaryGeneratorMessenger.cc.
View newest version in sPHENIX GitHub at line 39 of file PrimaryGeneratorMessenger.cc
References G4UIcommand::AvailableForStates(), DefaultCmd, G4State_Idle, G4State_PreInit, gunDir, RndmCmd, G4UIcommand::SetGuidance(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
Definition at line 61 of file PrimaryGeneratorMessenger.cc.
View newest version in sPHENIX GitHub at line 61 of file PrimaryGeneratorMessenger.cc
References DefaultCmd, gunDir, and RndmCmd.
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction * gen)
virtual PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger () virtual
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (const PrimaryGeneratorMessenger &) private
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
virtual PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger () virtual
PrimaryGeneratorMessenger::PrimaryGeneratorMessenger (PrimaryGeneratorAction *)
PrimaryGeneratorMessenger::~PrimaryGeneratorMessenger ()
Member Function Documentation
PrimaryGeneratorMessenger& PrimaryGeneratorMessenger::operator= (const PrimaryGeneratorMessenger & right) private
void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 70 of file PrimaryGeneratorMessenger.cc.
View newest version in sPHENIX GitHub at line 70 of file PrimaryGeneratorMessenger.cc
References Action, DefaultCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), RndmCmd, PrimaryGeneratorAction::SetDefaultKinematic(), and PrimaryGeneratorAction::SetRndmBeam().
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
virtual void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
void PrimaryGeneratorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Member Data Documentation
PrimaryGeneratorAction* PrimaryGeneratorMessenger::Action private
Definition at line 52 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithoutParameter* PrimaryGeneratorMessenger::DefaultCmd private
Definition at line 55 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorMessenger.hh
Referenced by PrimaryGeneratorMessenger(), SetNewValue(), and ~PrimaryGeneratorMessenger().
PrimaryGeneratorAction * PrimaryGeneratorMessenger::fAction private
Definition at line 50 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 50 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADouble* PrimaryGeneratorMessenger::fBeam private
Definition at line 56 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fBeamECmd private
Definition at line 78 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fBeamXCmd private
Definition at line 75 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fBeamYCmd private
Definition at line 76 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fBeamZCmd private
Definition at line 77 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithoutParameter* PrimaryGeneratorMessenger::fDefaultCmd private
Definition at line 57 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithoutParameter * PrimaryGeneratorMessenger::fDefaultCmd private
Definition at line 58 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file PrimaryGeneratorMessenger.hh
G4UIdirectory* PrimaryGeneratorMessenger::fDir private
Definition at line 56 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithAnInteger* PrimaryGeneratorMessenger::fEmissionCmd private
Definition at line 52 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorMessenger.hh
PrimaryGeneratorAction* PrimaryGeneratorMessenger::fGen private
Definition at line 72 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file PrimaryGeneratorMessenger.hh
G4UIdirectory * PrimaryGeneratorMessenger::fGunDir private
Definition at line 51 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 51 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fMaxThetaCmd private
Definition at line 85 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fPolarCmd private
Definition at line 59 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryGeneratorMessenger.hh
PrimaryGeneratorAction* PrimaryGeneratorMessenger::fPrimaryAction private
Definition at line 57 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithAString* PrimaryGeneratorMessenger::fRandCmd private
Definition at line 84 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithABool* PrimaryGeneratorMessenger::fRndmCmd private
Definition at line 56 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fRndmCmd private
Definition at line 58 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit * PrimaryGeneratorMessenger::fRndmCmd private
Definition at line 59 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithAnInteger* PrimaryGeneratorMessenger::fSelectActionCmd private
Definition at line 57 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fSigmaECmd private
Definition at line 82 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fSigmaXCmd private
Definition at line 79 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fSigmaYCmd private
Definition at line 80 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fSigmaZCmd private
Definition at line 81 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fThetaCmd private
Definition at line 86 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file PrimaryGeneratorMessenger.hh
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::fTimeCmd private
Definition at line 59 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryGeneratorMessenger.hh
G4bool PrimaryGeneratorMessenger::fVerbose private
Definition at line 73 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file PrimaryGeneratorMessenger.hh
G4UIdirectory* PrimaryGeneratorMessenger::gunDir private
Definition at line 54 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorMessenger.hh
Referenced by PrimaryGeneratorMessenger(), and ~PrimaryGeneratorMessenger().
G4UIcmdWithADoubleAndUnit* PrimaryGeneratorMessenger::RndmCmd private
Definition at line 56 of file PrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorMessenger.hh
Referenced by PrimaryGeneratorMessenger(), SetNewValue(), and ~PrimaryGeneratorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/include/PrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/src/PrimaryGeneratorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/src/PrimaryGeneratorMessenger.cc