ECCE @ EIC Software: G4GenericMessenger::Command Struct Reference
G4GenericMessenger::Command Struct Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4GenericMessenger.hh>
Public Types
enum UnitSpec { UnitCategory, UnitDefault }
Public Member Functions
Command (G4UIcommand *cmd, const std::type_info &ti)
Command ()
Command & SetStates (G4ApplicationState s0)
Command & SetStates (G4ApplicationState s0, G4ApplicationState s1)
Command & SetStates (G4ApplicationState s0, G4ApplicationState s1, G4ApplicationState s2)
Command & SetStates (G4ApplicationState s0, G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
Command & SetStates (G4ApplicationState s0, G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
Command & SetRange (const G4String &range)
Command & SetGuidance (const G4String &s0)
Command & SetUnit (const G4String &, UnitSpec=UnitDefault)
Command & SetUnitCategory (const G4String &u)
Command & SetDefaultUnit (const G4String &u)
Command & SetParameterName (const G4String &, G4bool, G4bool=false)
Command & SetDefaultValue (const G4String &)
Command & SetCandidates (const G4String &)
Command & SetToBeBroadcasted (G4bool s0)
Command & SetToBeFlushed (G4bool s0)
Command & SetWorkerThreadOnly (G4bool s0)
Public Attributes
G4UIcommand * command
const std::type_info * type
Detailed Description
Definition at line 58 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file G4GenericMessenger.hh
Member Enumeration Documentation
enum G4GenericMessenger::Command::UnitSpec
Enumerator:
UnitCategory
UnitDefault
Definition at line 59 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file G4GenericMessenger.hh
Constructor & Destructor Documentation
G4GenericMessenger::Command::Command (G4UIcommand * cmd, const std::type_info & ti) inline
Definition at line 60 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file G4GenericMessenger.hh
G4GenericMessenger::Command::Command () inline
Definition at line 61 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file G4GenericMessenger.hh
Member Function Documentation
G4GenericMessenger::Command & G4GenericMessenger::Command::SetCandidates (const G4String & candList)
Definition at line 246 of file G4GenericMessenger.cc.
View newest version in sPHENIX GitHub at line 246 of file G4GenericMessenger.cc
References G4UIparameter::SetParameterCandidates().
Command& G4GenericMessenger::Command::SetDefaultUnit (const G4String & u) inline
Definition at line 72 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4GenericMessenger.hh
References SetUnit(), and UnitDefault.
G4GenericMessenger::Command & G4GenericMessenger::Command::SetDefaultValue (const G4String & defVal)
Definition at line 252 of file G4GenericMessenger.cc.
View newest version in sPHENIX GitHub at line 252 of file G4GenericMessenger.cc
References G4UIparameter::SetDefaultValue().
Referenced by B5MagneticField::DefineCommands(), DetectorConstruction0::DefineCommands(), B5DetectorConstruction::DefineCommands(), DetectorConstruction::DefineCommands(), B5PrimaryGeneratorAction::DefineCommands(), and EICG4dRICHConfig::EICG4dRICHConfig().
Command& G4GenericMessenger::Command::SetGuidance (const G4String & s0) inline
Definition at line 69 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4GenericMessenger.hh
References G4UIcommand::SetGuidance().
Referenced by HadrontherapyRBE::CreateMessenger().
G4GenericMessenger::Command & G4GenericMessenger::Command::SetParameterName (const G4String & name, G4bool omittable, G4bool currentAsDefault = false)
Definition at line 238 of file G4GenericMessenger.cc.
View newest version in sPHENIX GitHub at line 238 of file G4GenericMessenger.cc
References G4UIparameter::SetCurrentAsDefault(), G4UIparameter::SetOmittable(), and G4UIparameter::SetParameterName().
Referenced by B5MagneticField::DefineCommands(), DetectorConstruction0::DefineCommands(), B5DetectorConstruction::DefineCommands(), DetectorConstruction::DefineCommands(), B5PrimaryGeneratorAction::DefineCommands(), and EICG4dRICHConfig::EICG4dRICHConfig().
Command& G4GenericMessenger::Command::SetRange (const G4String & range) inline
Definition at line 68 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4GenericMessenger.hh
References G4UIcommand::SetRange().
Referenced by B5DetectorConstruction::DefineCommands(), DetectorConstruction::DefineCommands(), B5PrimaryGeneratorAction::DefineCommands(), and EICG4dRICHConfig::EICG4dRICHConfig().
Command& G4GenericMessenger::Command::SetStates (G4ApplicationState s0) inline
Definition at line 63 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4GenericMessenger.hh
References G4UIcommand::AvailableForStates().
Referenced by HadrontherapyRBE::CreateMessenger(), DetectorConstruction0::DefineCommands(), DetectorConstruction::DefineCommands(), GB03BOptrGeometryBasedBiasing::GB03BOptrGeometryBasedBiasing(), and GB04BOptrBremSplitting::GB04BOptrBremSplitting().
Command& G4GenericMessenger::Command::SetStates (G4ApplicationState s0, G4ApplicationState s1) inline
Definition at line 64 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4GenericMessenger.hh
References G4UIcommand::AvailableForStates().
Command& G4GenericMessenger::Command::SetStates (G4ApplicationState s0, G4ApplicationState s1, G4ApplicationState s2) inline
Definition at line 65 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4GenericMessenger.hh
References G4UIcommand::AvailableForStates().
Command& G4GenericMessenger::Command::SetStates (G4ApplicationState s0, G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3) inline
Definition at line 66 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4GenericMessenger.hh
References G4UIcommand::AvailableForStates().
Command& G4GenericMessenger::Command::SetStates (G4ApplicationState s0, G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4) inline
Definition at line 67 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4GenericMessenger.hh
References G4UIcommand::AvailableForStates().
Command& G4GenericMessenger::Command::SetToBeBroadcasted (G4bool s0) inline
Definition at line 76 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GenericMessenger.hh
References G4UIcommand::SetToBeBroadcasted().
Referenced by HadrontherapyRBE::CreateMessenger().
Command& G4GenericMessenger::Command::SetToBeFlushed (G4bool s0) inline
Definition at line 77 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4GenericMessenger.hh
References G4UIcommand::SetToBeFlushed().
G4GenericMessenger::Command & G4GenericMessenger::Command::SetUnit (const G4String & unit, UnitSpec spec = UnitDefault)
Definition at line 185 of file G4GenericMessenger.cc.
View newest version in sPHENIX GitHub at line 185 of file G4GenericMessenger.cc
References command, FatalException, G4cerr, G4endl, G4Exception(), G4UIcommand::GetCommandPath(), G4UIcommand::GetGuidanceEntries(), G4UIcommand::GetGuidanceLine(), G4UIcommand::GetMessenger(), G4UIcommand::GetParameter(), G4UIparameter::GetParameterName(), G4UIcommand::GetRange(), G4Threading::IsMultithreadedApplication(), G4UIparameter::IsOmittable(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcommand::SetGuidance(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), G4UIcmdWithADoubleAndUnit::SetUnitCategory(), G4UIcmdWith3VectorAndUnit::SetUnitCategory(), tmp, type, UnitCategory, and UnitDefault.
Referenced by SetDefaultUnit(), and SetUnitCategory().
Command& G4GenericMessenger::Command::SetUnitCategory (const G4String & u) inline
Definition at line 71 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4GenericMessenger.hh
References SetUnit(), and UnitCategory.
Command& G4GenericMessenger::Command::SetWorkerThreadOnly (G4bool s0) inline
Definition at line 78 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4GenericMessenger.hh
References G4UIcommand::SetWorkerThreadOnly().
Member Data Documentation
G4UIcommand* G4GenericMessenger::Command::command
Definition at line 80 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4GenericMessenger.hh
Referenced by SetUnit().
const std::type_info* G4GenericMessenger::Command::type
Definition at line 81 of file G4GenericMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GenericMessenger.hh
Referenced by SetUnit().
The documentation for this struct was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4GenericMessenger.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4GenericMessenger.cc