ECCE @ EIC Software: XrayFluoHPGeDetectorType Class Reference
XrayFluoHPGeDetectorType Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoHPGeDetectorType.hh>
Public Member Functions
~XrayFluoHPGeDetectorType ()
G4String GetDetectorMaterial ()
G4double ResponseFunction (G4double)
G4double GetInfData (G4double, G4double, G4int)
G4double GetSupData (G4double, G4double, G4int)
void LoadResponseData (G4String)
void LoadEfficiencyData (G4String)
Public Member Functions inherited from XrayFluoVDetectorType
virtual ~XrayFluoVDetectorType ()
Static Public Member Functions
static XrayFluoHPGeDetectorType * GetInstance ()
Private Member Functions
XrayFluoHPGeDetectorType ()
Private Attributes
G4String detectorMaterial
const XrayFluoDataSet * efficiencySet
G4VDataSetAlgorithm * interpolation4
std::map< G4int, G4DataVector
*, std::less< G4int > > energyMap
std::map< G4int, G4DataVector
*, std::less< G4int > > dataMap
Static Private Attributes
static XrayFluoHPGeDetectorType * instance = 0
Additional Inherited Members
Protected Member Functions inherited from XrayFluoVDetectorType
XrayFluoVDetectorType ()
Detailed Description
Definition at line 48 of file XrayFluoHPGeDetectorType.hh.
View newest version in sPHENIX GitHub at line 48 of file XrayFluoHPGeDetectorType.hh
Constructor & Destructor Documentation
XrayFluoHPGeDetectorType::~XrayFluoHPGeDetectorType ()
Definition at line 58 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 58 of file XrayFluoHPGeDetectorType.cc
References dataMap, energyMap, interpolation4, and pos().
XrayFluoHPGeDetectorType::XrayFluoHPGeDetectorType () private
Definition at line 49 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 49 of file XrayFluoHPGeDetectorType.cc
References LoadEfficiencyData(), and LoadResponseData().
Referenced by GetInstance().
Member Function Documentation
G4String XrayFluoHPGeDetectorType::GetDetectorMaterial () virtual
Implements XrayFluoVDetectorType.
Definition at line 78 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 78 of file XrayFluoHPGeDetectorType.cc
References detectorMaterial.
G4double XrayFluoHPGeDetectorType::GetInfData (G4double energy, G4double random, G4int) virtual
Implements XrayFluoVDetectorType.
Definition at line 163 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 163 of file XrayFluoHPGeDetectorType.cc
References dataMap, energyMap, keV, pos(), and Z.
Referenced by ResponseFunction().
XrayFluoHPGeDetectorType * XrayFluoHPGeDetectorType::GetInstance (void) static
Definition at line 85 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 85 of file XrayFluoHPGeDetectorType.cc
References instance, and XrayFluoHPGeDetectorType().
Referenced by XrayFluoPlaneDetectorConstruction::SetDetectorType(), XrayFluoMercuryDetectorConstruction::SetDetectorType(), and XrayFluoDetectorConstruction::SetDetectorType().
G4double XrayFluoHPGeDetectorType::GetSupData (G4double energy, G4double random, G4int) virtual
Implements XrayFluoVDetectorType.
Definition at line 207 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 207 of file XrayFluoHPGeDetectorType.cc
References dataMap, energyMap, keV, pos(), and Z.
Referenced by ResponseFunction().
void XrayFluoHPGeDetectorType::LoadEfficiencyData (G4String fileName) virtual
Implements XrayFluoVDetectorType.
Definition at line 327 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 327 of file XrayFluoHPGeDetectorType.cc
References efficiencySet, interpolation4, and keV.
Referenced by XrayFluoHPGeDetectorType().
void XrayFluoHPGeDetectorType::LoadResponseData (G4String fileName) virtual
Implements XrayFluoVDetectorType.
Definition at line 246 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 246 of file XrayFluoHPGeDetectorType.cc
References a, dataMap, e, energyMap, FatalException, file, G4Exception(), k, keV, and Z.
Referenced by XrayFluoHPGeDetectorType().
G4double XrayFluoHPGeDetectorType::ResponseFunction (G4double energy) virtual
Implements XrayFluoVDetectorType.
Definition at line 96 of file XrayFluoHPGeDetectorType.cc.
View newest version in sPHENIX GitHub at line 96 of file XrayFluoHPGeDetectorType.cc
References efficiencySet, energy, XrayFluoDataSet::FindValue(), G4UniformRand, GetInfData(), GetSupData(), and keV.
Member Data Documentation
std::map<G4int,G4DataVector*,std::less<G4int> > XrayFluoHPGeDetectorType::dataMap private
Definition at line 96 of file XrayFluoHPGeDetectorType.hh.
View newest version in sPHENIX GitHub at line 96 of file XrayFluoHPGeDetectorType.hh
Referenced by GetInfData(), GetSupData(), LoadResponseData(), and ~XrayFluoHPGeDetectorType().
G4String XrayFluoHPGeDetectorType::detectorMaterial private
Definition at line 83 of file XrayFluoHPGeDetectorType.hh.
View newest version in sPHENIX GitHub at line 83 of file XrayFluoHPGeDetectorType.hh
Referenced by GetDetectorMaterial().
const XrayFluoDataSet* XrayFluoHPGeDetectorType::efficiencySet private
Definition at line 86 of file XrayFluoHPGeDetectorType.hh.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoHPGeDetectorType.hh
Referenced by LoadEfficiencyData(), and ResponseFunction().
std::map<G4int,G4DataVector*,std::less<G4int> > XrayFluoHPGeDetectorType::energyMap private
Definition at line 92 of file XrayFluoHPGeDetectorType.hh.
View newest version in sPHENIX GitHub at line 92 of file XrayFluoHPGeDetectorType.hh
Referenced by GetInfData(), GetSupData(), LoadResponseData(), and ~XrayFluoHPGeDetectorType().
XrayFluoHPGeDetectorType * XrayFluoHPGeDetectorType::instance = 0 static private
Definition at line 81 of file XrayFluoHPGeDetectorType.hh.
View newest version in sPHENIX GitHub at line 81 of file XrayFluoHPGeDetectorType.hh
Referenced by GetInstance().
G4VDataSetAlgorithm* XrayFluoHPGeDetectorType::interpolation4 private
Definition at line 88 of file XrayFluoHPGeDetectorType.hh.
View newest version in sPHENIX GitHub at line 88 of file XrayFluoHPGeDetectorType.hh
Referenced by LoadEfficiencyData(), and ~XrayFluoHPGeDetectorType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoHPGeDetectorType.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoHPGeDetectorType.cc