ECCE @ EIC Software: G4SingleDiffractiveExcitation Class Reference
G4SingleDiffractiveExcitation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4SingleDiffractiveExcitation.hh>
Public Member Functions
G4SingleDiffractiveExcitation ()
~G4SingleDiffractiveExcitation ()
G4bool ExciteParticipants (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4bool ProjectileDiffraction) const
Public Member Functions inherited from G4QGSDiffractiveExcitation
G4QGSDiffractiveExcitation ()
virtual ~G4QGSDiffractiveExcitation ()
virtual G4ExcitedString * String (G4VSplitableHadron *aHadron, G4bool isProjectile) const
Private Member Functions
G4SingleDiffractiveExcitation (const G4SingleDiffractiveExcitation &right)
G4double ChooseX (G4double Xmin, G4double Xmax) const
G4ThreeVector GaussianPt (G4double widthSquare, G4double maxPtSquare) const
const
G4SingleDiffractiveExcitation & operator= (const G4SingleDiffractiveExcitation &right)
G4bool operator== (const G4SingleDiffractiveExcitation &right) const
G4bool operator!= (const G4SingleDiffractiveExcitation &right) const
Detailed Description
Definition at line 48 of file G4SingleDiffractiveExcitation.hh.
View newest version in sPHENIX GitHub at line 48 of file G4SingleDiffractiveExcitation.hh
Constructor & Destructor Documentation
G4SingleDiffractiveExcitation::G4SingleDiffractiveExcitation ()
Definition at line 53 of file G4SingleDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 53 of file G4SingleDiffractiveExcitation.cc
G4SingleDiffractiveExcitation::~G4SingleDiffractiveExcitation ()
Definition at line 55 of file G4SingleDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SingleDiffractiveExcitation.cc
G4SingleDiffractiveExcitation::G4SingleDiffractiveExcitation (const G4SingleDiffractiveExcitation & right) private
Member Function Documentation
G4double G4SingleDiffractiveExcitation::ChooseX (G4double Xmin, G4double Xmax) const private
Definition at line 266 of file G4SingleDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 266 of file G4SingleDiffractiveExcitation.cc
References G4cout, G4endl, G4UniformRand, G4Pow::GetInstance(), G4Pow::powA(), x, and Xmin.
Referenced by ExciteParticipants().
G4bool G4SingleDiffractiveExcitation::ExciteParticipants (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4bool ProjectileDiffraction) const virtual
Reimplemented from G4QGSDiffractiveExcitation.
Definition at line 58 of file G4SingleDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 58 of file G4SingleDiffractiveExcitation.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boostVector(), ChooseX(), G4cerr, G4cout, G4endl, GaussianPt(), G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), GeV, CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), MeV, CLHEP::HepLorentzVector::rotateY(), CLHEP::HepLorentzVector::rotateZ(), S(), G4VSplitableHadron::Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), sqr(), CLHEP::HepLorentzRotation::transform(), CLHEP::HepLorentzVector::transform(), and CLHEP::HepLorentzVector::vect().
Referenced by G4QGSParticipants::PerformDiffractiveCollisions().
G4ThreeVector G4SingleDiffractiveExcitation::GaussianPt (G4double widthSquare, G4double maxPtSquare) const private
Definition at line 283 of file G4SingleDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 283 of file G4SingleDiffractiveExcitation.cc
References G4Log(), G4UniformRand, phi, pt2, and twopi.
Referenced by ExciteParticipants().
G4bool G4SingleDiffractiveExcitation::operator!= (const G4SingleDiffractiveExcitation & right) const private
const G4SingleDiffractiveExcitation& G4SingleDiffractiveExcitation::operator= (const G4SingleDiffractiveExcitation & right) private
G4bool G4SingleDiffractiveExcitation::operator== (const G4SingleDiffractiveExcitation & right) const private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4SingleDiffractiveExcitation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4SingleDiffractiveExcitation.cc