ECCE @ EIC Software: G4AdjointForcedInteractionForGamma Class Reference
G4AdjointForcedInteractionForGamma Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointForcedInteractionForGamma.hh>
Public Member Functions
G4AdjointForcedInteractionForGamma (G4String process_name)
virtual ~G4AdjointForcedInteractionForGamma ()
void PreparePhysicsTable (const G4ParticleDefinition &)
void BuildPhysicsTable (const G4ParticleDefinition &)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &step)
void RegisterAdjointComptonModel (G4VEmAdjointModel *aAdjointComptonModel)
void RegisterAdjointBremModel (G4VEmAdjointModel *aAdjointBremModel)
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double GetContinuousStepLimit (const G4Track &aTrack, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Attributes
G4VEmAdjointModel * theAdjointComptonModel
G4VEmAdjointModel * theAdjointBremModel
G4ParticleChange * fParticleChange
G4AdjointCSManager * theAdjointCSManager
G4double lastAdjCS
G4double lastFwdCS
G4int trackid
G4int nstep
G4bool is_free_flight_gamma
G4bool copy_gamma_for_forced_interaction
G4int last_free_flight_trackid
G4double acc_track_length
G4double total_acc_nb_adj_interaction_length
G4double total_acc_nb_fwd_interaction_length
G4double acc_nb_adj_interaction_length
G4double acc_nb_fwd_interaction_length
G4bool continue_gamma_as_new_free_flight
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 72 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 72 of file G4AdjointForcedInteractionForGamma.hh
Constructor & Destructor Documentation
G4AdjointForcedInteractionForGamma::G4AdjointForcedInteractionForGamma (G4String process_name)
Definition at line 38 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 38 of file G4AdjointForcedInteractionForGamma.cc
References acc_nb_adj_interaction_length, acc_nb_fwd_interaction_length, acc_track_length, continue_gamma_as_new_free_flight, copy_gamma_for_forced_interaction, fParticleChange, G4AdjointCSManager::GetAdjointCSManager(), is_free_flight_gamma, last_free_flight_trackid, lastAdjCS, nstep, theAdjointBremModel, theAdjointComptonModel, theAdjointCSManager, total_acc_nb_adj_interaction_length, total_acc_nb_fwd_interaction_length, and trackid.
G4AdjointForcedInteractionForGamma::~G4AdjointForcedInteractionForGamma () virtual
Definition at line 64 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 64 of file G4AdjointForcedInteractionForGamma.cc
References fParticleChange.
Member Function Documentation
G4VParticleChange * G4AdjointForcedInteractionForGamma::AlongStepDoIt (const G4Track & track, const G4Step & step) virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 156 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 156 of file G4AdjointForcedInteractionForGamma.cc
References kdfinder::abs(), acc_nb_adj_interaction_length, acc_nb_fwd_interaction_length, acc_track_length, G4AdjointGamma::AdjointGamma(), e, fParticleChange, G4AdjointCSManager::GetAdjointCSManager(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4Track::GetStep(), G4Step::GetStepLength(), G4AdjointCSManager::GetTotalAdjointCS(), G4AdjointCSManager::GetTotalForwardCS(), G4StepPoint::GetWeight(), G4ParticleChange::Initialize(), is_free_flight_gamma, lastAdjCS, lastFwdCS, G4VParticleChange::ProposeParentWeight(), G4VParticleChange::SetParentWeightByProcess(), G4VParticleChange::SetSecondaryWeightByProcess(), G4VProcess::theNumberOfInteractionLengthLeft, total_acc_nb_adj_interaction_length, and total_acc_nb_fwd_interaction_length.
void G4AdjointForcedInteractionForGamma::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VProcess.
Definition at line 74 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 74 of file G4AdjointForcedInteractionForGamma.cc
References G4AdjointCSManager::BuildCrossSectionMatrices(), G4AdjointCSManager::BuildTotalSigmaTables(), and theAdjointCSManager.
G4double G4AdjointForcedInteractionForGamma::GetContinuousStepLimit (const G4Track & aTrack, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety) protected virtual
Implements G4VContinuousDiscreteProcess.
Definition at line 272 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 272 of file G4AdjointForcedInteractionForGamma.cc
References DBL_MAX.
G4double G4AdjointForcedInteractionForGamma::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) protected virtual
Implements G4VContinuousDiscreteProcess.
Definition at line 280 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 280 of file G4AdjointForcedInteractionForGamma.cc
G4VParticleChange * G4AdjointForcedInteractionForGamma::PostStepDoIt (const G4Track & track, const G4Step &) virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 97 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 97 of file G4AdjointForcedInteractionForGamma.cc
References acc_nb_adj_interaction_length, G4ParticleChange::AddSecondary(), G4VEmAdjointModel::AdjointCrossSection(), G4AdjointGamma::AdjointGamma(), continue_gamma_as_new_free_flight, copy_gamma_for_forced_interaction, fParticleChange, G4UniformRand, G4Track::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4Track::GetMomentum(), G4ParticleChange::Initialize(), lastAdjCS, G4VEmAdjointModel::SampleSecondaries(), G4VEmAdjointModel::SetAdditionalWeightCorrectionFactorForPostStepOutsideModel(), G4VEmAdjointModel::SetCorrectWeightForPostStepInModel(), G4VParticleChange::SetParentWeightByProcess(), G4VParticleChange::SetSecondaryWeightByProcess(), theAdjointBremModel, theAdjointComptonModel, and total_acc_nb_adj_interaction_length.
G4double G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 225 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 225 of file G4AdjointForcedInteractionForGamma.cc
References acc_nb_adj_interaction_length, acc_nb_fwd_interaction_length, acc_track_length, G4AdjointGamma::AdjointGamma(), continue_gamma_as_new_free_flight, copy_gamma_for_forced_interaction, DBL_MAX, Forced, G4UniformRand, G4AdjointCSManager::GetAdjointCSManager(), G4Track::GetCurrentStepNumber(), G4Track::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterialCutsCouple(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), G4Track::GetStep(), G4AdjointCSManager::GetTotalAdjointCS(), G4Track::GetTrackID(), is_free_flight_gamma, last_free_flight_trackid, NotForced, G4VProcess::theInitialNumberOfInteractionLength, G4VProcess::theNumberOfInteractionLengthLeft, total_acc_nb_adj_interaction_length, and total_acc_nb_fwd_interaction_length.
void G4AdjointForcedInteractionForGamma::PreparePhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VProcess.
Definition at line 69 of file G4AdjointForcedInteractionForGamma.cc.
View newest version in sPHENIX GitHub at line 69 of file G4AdjointForcedInteractionForGamma.cc
void G4AdjointForcedInteractionForGamma::RegisterAdjointBremModel (G4VEmAdjointModel * aAdjointBremModel) inline
Definition at line 91 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 91 of file G4AdjointForcedInteractionForGamma.hh
References theAdjointBremModel.
Referenced by G4AdjointPhysicsList::ConstructEM().
void G4AdjointForcedInteractionForGamma::RegisterAdjointComptonModel (G4VEmAdjointModel * aAdjointComptonModel) inline
Definition at line 90 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 90 of file G4AdjointForcedInteractionForGamma.hh
References theAdjointComptonModel.
Member Data Documentation
G4double G4AdjointForcedInteractionForGamma::acc_nb_adj_interaction_length private
Definition at line 125 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 125 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt(), G4AdjointForcedInteractionForGamma(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
G4double G4AdjointForcedInteractionForGamma::acc_nb_fwd_interaction_length private
Definition at line 126 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 126 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt(), G4AdjointForcedInteractionForGamma(), and PostStepGetPhysicalInteractionLength().
G4double G4AdjointForcedInteractionForGamma::acc_track_length private
Definition at line 120 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 120 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt(), G4AdjointForcedInteractionForGamma(), and PostStepGetPhysicalInteractionLength().
G4bool G4AdjointForcedInteractionForGamma::continue_gamma_as_new_free_flight private
Definition at line 127 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 127 of file G4AdjointForcedInteractionForGamma.hh
Referenced by G4AdjointForcedInteractionForGamma(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
G4bool G4AdjointForcedInteractionForGamma::copy_gamma_for_forced_interaction private
Definition at line 117 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 117 of file G4AdjointForcedInteractionForGamma.hh
Referenced by G4AdjointForcedInteractionForGamma(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
G4ParticleChange* G4AdjointForcedInteractionForGamma::fParticleChange private
Definition at line 108 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 108 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt(), G4AdjointForcedInteractionForGamma(), PostStepDoIt(), and ~G4AdjointForcedInteractionForGamma().
G4bool G4AdjointForcedInteractionForGamma::is_free_flight_gamma private
Definition at line 116 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt(), G4AdjointForcedInteractionForGamma(), and PostStepGetPhysicalInteractionLength().
G4int G4AdjointForcedInteractionForGamma::last_free_flight_trackid private
Definition at line 118 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 118 of file G4AdjointForcedInteractionForGamma.hh
Referenced by G4AdjointForcedInteractionForGamma(), and PostStepGetPhysicalInteractionLength().
G4double G4AdjointForcedInteractionForGamma::lastAdjCS private
Definition at line 112 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 112 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt(), G4AdjointForcedInteractionForGamma(), and PostStepDoIt().
G4double G4AdjointForcedInteractionForGamma::lastFwdCS private
Definition at line 112 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 112 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt().
G4int G4AdjointForcedInteractionForGamma::nstep private
Definition at line 115 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 115 of file G4AdjointForcedInteractionForGamma.hh
Referenced by G4AdjointForcedInteractionForGamma().
G4VEmAdjointModel* G4AdjointForcedInteractionForGamma::theAdjointBremModel private
Definition at line 106 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AdjointForcedInteractionForGamma.hh
Referenced by G4AdjointForcedInteractionForGamma(), PostStepDoIt(), and RegisterAdjointBremModel().
G4VEmAdjointModel* G4AdjointForcedInteractionForGamma::theAdjointComptonModel private
Definition at line 105 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 105 of file G4AdjointForcedInteractionForGamma.hh
Referenced by G4AdjointForcedInteractionForGamma(), PostStepDoIt(), and RegisterAdjointComptonModel().
G4AdjointCSManager* G4AdjointForcedInteractionForGamma::theAdjointCSManager private
Definition at line 109 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AdjointForcedInteractionForGamma.hh
Referenced by BuildPhysicsTable(), and G4AdjointForcedInteractionForGamma().
G4double G4AdjointForcedInteractionForGamma::total_acc_nb_adj_interaction_length private
Definition at line 121 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 121 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt(), G4AdjointForcedInteractionForGamma(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
G4double G4AdjointForcedInteractionForGamma::total_acc_nb_fwd_interaction_length private
Definition at line 122 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 122 of file G4AdjointForcedInteractionForGamma.hh
Referenced by AlongStepDoIt(), G4AdjointForcedInteractionForGamma(), and PostStepGetPhysicalInteractionLength().
G4int G4AdjointForcedInteractionForGamma::trackid private
Definition at line 114 of file G4AdjointForcedInteractionForGamma.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AdjointForcedInteractionForGamma.hh
Referenced by G4AdjointForcedInteractionForGamma().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointForcedInteractionForGamma.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/src/G4AdjointForcedInteractionForGamma.cc