ECCE @ EIC Software: G4ModelingParameters Class Reference
G4ModelingParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ModelingParameters.hh>
Classes
class PVNameCopyNo
class PVPointerCopyNo
class VisAttributesModifier
Public Types
enum DrawingStyle {
wf, hlr, hsr, hlhsr,
cloud
}
enum VisAttributesSignifier {
VASVisibility, VASDaughtersInvisible, VASColour, VASLineStyle,
VASLineWidth, VASForceWireframe, VASForceSolid, VASForceCloud,
VASForceNumberOfCloudPoints, VASForceAuxEdgeVisible, VASForceLineSegmentsPerCircle
}
typedef std::vector< PVNameCopyNo > PVNameCopyNoPath
typedef
PVNameCopyNoPath::const_iterator PVNameCopyNoPathConstIterator
typedef std::vector
< PVPointerCopyNo > PVPointerCopyNoPath
typedef
PVPointerCopyNoPath::const_iterator PVPointerCopyNoPathConstIterator
Public Member Functions
G4ModelingParameters ()
G4ModelingParameters (const G4VisAttributes *pDefaultVisAttributes, DrawingStyle drawingStyle, G4bool isCulling, G4bool isCullingInvisible, G4bool isDensityCulling, G4double visibleDensity, G4bool isCullingCovered, G4int noOfSides)
~G4ModelingParameters ()
G4bool operator!= (const G4ModelingParameters &) const
G4bool IsWarning () const
const G4VisAttributes * GetDefaultVisAttributes () const
DrawingStyle GetDrawingStyle () const
G4int GetNumberOfCloudPoints () const
G4bool IsCulling () const
G4bool IsCullingInvisible () const
G4bool IsDensityCulling () const
G4double GetVisibleDensity () const
G4bool IsCullingCovered () const
G4int GetCBDAlgorithmNumber () const
const std::vector< G4double > & GetCBDParameters () const
G4bool IsExplode () const
G4double GetExplodeFactor () const
const G4Point3D & GetExplodeCentre () const
G4int GetNoOfSides () const
G4DisplacedSolid * GetSectionSolid () const
G4DisplacedSolid * GetCutawaySolid () const
const G4Event * GetEvent () const
const std::vector
< VisAttributesModifier > & GetVisAttributesModifiers () const
void SetWarning (G4bool)
void SetDefaultVisAttributes (const G4VisAttributes *pDefaultVisAttributes)
void SetDrawingStyle (DrawingStyle)
void SetNumberOfCloudPoints (G4int)
void SetCulling (G4bool)
void SetCullingInvisible (G4bool)
void SetDensityCulling (G4bool)
void SetVisibleDensity (G4double)
void SetCullingCovered (G4bool)
void SetCBDAlgorithmNumber (G4int)
void SetCBDParameters (const std::vector< G4double > &)
void SetExplodeFactor (G4double explodeFactor)
void SetExplodeCentre (const G4Point3D &explodeCentre)
G4int SetNoOfSides (G4int)
void SetSectionSolid (G4DisplacedSolid *pSectionSolid)
void SetCutawaySolid (G4DisplacedSolid *pCutawaySolid)
void SetEvent (const G4Event *pEvent)
void SetVisAttributesModifiers (const std::vector< VisAttributesModifier > &)
Private Attributes
G4bool fWarning
const G4VisAttributes * fpDefaultVisAttributes
DrawingStyle fDrawingStyle
G4int fNumberOfCloudPoints
G4bool fCulling
G4bool fCullInvisible
G4bool fDensityCulling
G4double fVisibleDensity
G4bool fCullCovered
G4int fCBDAlgorithmNumber
std::vector< G4double > fCBDParameters
G4double fExplodeFactor
G4Point3D fExplodeCentre
G4int fNoOfSides
G4DisplacedSolid * fpSectionSolid
G4DisplacedSolid * fpCutawaySolid
const G4Event * fpEvent
std::vector
< VisAttributesModifier > fVisAttributesModifiers
Friends
std::ostream & operator<< (std::ostream &os, const G4ModelingParameters &)
std::ostream & operator<< (std::ostream &os, const PVNameCopyNoPath &)
std::ostream & operator<< (std::ostream &os, const PVPointerCopyNoPath &)
std::ostream & operator<< (std::ostream &os, const std::vector< VisAttributesModifier > &)
Detailed Description
Definition at line 52 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ModelingParameters.hh
Member Typedef Documentation
typedef std::vector<PVNameCopyNo> G4ModelingParameters::PVNameCopyNoPath
Definition at line 94 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ModelingParameters.hh
typedef PVNameCopyNoPath::const_iterator G4ModelingParameters::PVNameCopyNoPathConstIterator
Definition at line 95 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ModelingParameters.hh
typedef std::vector<PVPointerCopyNo> G4ModelingParameters::PVPointerCopyNoPath
Definition at line 111 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ModelingParameters.hh
typedef PVPointerCopyNoPath::const_iterator G4ModelingParameters::PVPointerCopyNoPathConstIterator
Definition at line 112 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ModelingParameters.hh
Member Enumeration Documentation
enum G4ModelingParameters::DrawingStyle
Enumerator:
wf
hlr
hsr
hlhsr
cloud
Definition at line 57 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ModelingParameters.hh
enum G4ModelingParameters::VisAttributesSignifier
Enumerator:
VASVisibility
VASDaughtersInvisible
VASColour
VASLineStyle
VASLineWidth
VASForceWireframe
VASForceSolid
VASForceCloud
VASForceNumberOfCloudPoints
VASForceAuxEdgeVisible
VASForceLineSegmentsPerCircle
Definition at line 67 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ModelingParameters.hh
Constructor & Destructor Documentation
G4ModelingParameters::G4ModelingParameters ()
Definition at line 44 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ModelingParameters.cc
G4ModelingParameters::G4ModelingParameters (const G4VisAttributes * pDefaultVisAttributes, G4ModelingParameters::DrawingStyle drawingStyle, G4bool isCulling, G4bool isCullingInvisible, G4bool isDensityCulling, G4double visibleDensity, G4bool isCullingCovered, G4int noOfSides)
Definition at line 63 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 63 of file G4ModelingParameters.cc
G4ModelingParameters::~G4ModelingParameters ()
Definition at line 89 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 89 of file G4ModelingParameters.cc
References fpCutawaySolid, and fpSectionSolid.
Member Function Documentation
G4int G4ModelingParameters::GetCBDAlgorithmNumber () const
const std::vector<G4double>& G4ModelingParameters::GetCBDParameters () const
G4DisplacedSolid* G4ModelingParameters::GetCutawaySolid () const
const G4VisAttributes* G4ModelingParameters::GetDefaultVisAttributes () const
Referenced by G4PhysicalVolumeModel::Validate().
DrawingStyle G4ModelingParameters::GetDrawingStyle () const
const G4Event* G4ModelingParameters::GetEvent () const
Referenced by G4DigiModel::DescribeYourselfTo(), G4HitsModel::DescribeYourselfTo(), and G4TrajectoriesModel::DescribeYourselfTo().
const G4Point3D& G4ModelingParameters::GetExplodeCentre () const
G4double G4ModelingParameters::GetExplodeFactor () const
G4int G4ModelingParameters::GetNoOfSides () const
G4int G4ModelingParameters::GetNumberOfCloudPoints () const
G4DisplacedSolid* G4ModelingParameters::GetSectionSolid () const
const std::vector<VisAttributesModifier>& G4ModelingParameters::GetVisAttributesModifiers () const
G4double G4ModelingParameters::GetVisibleDensity () const
G4bool G4ModelingParameters::IsCulling () const
G4bool G4ModelingParameters::IsCullingCovered () const
G4bool G4ModelingParameters::IsCullingInvisible () const
G4bool G4ModelingParameters::IsDensityCulling () const
G4bool G4ModelingParameters::IsExplode () const
G4bool G4ModelingParameters::IsWarning () const
G4bool G4ModelingParameters::operator!= (const G4ModelingParameters & mp) const
Definition at line 244 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 244 of file G4ModelingParameters.cc
void G4ModelingParameters::SetCBDAlgorithmNumber (G4int)
Referenced by G4VSceneHandler::CreateModelingParameters().
void G4ModelingParameters::SetCBDParameters (const std::vector< G4double > &)
Referenced by G4VSceneHandler::CreateModelingParameters().
void G4ModelingParameters::SetCulling (G4bool)
Referenced by G4LogicalVolumeModel::DescribeYourselfTo().
void G4ModelingParameters::SetCullingCovered (G4bool)
void G4ModelingParameters::SetCullingInvisible (G4bool)
void G4ModelingParameters::SetCutawaySolid (G4DisplacedSolid * pCutawaySolid)
Definition at line 152 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 152 of file G4ModelingParameters.cc
Referenced by G4VSceneHandler::CreateModelingParameters().
void G4ModelingParameters::SetDefaultVisAttributes (const G4VisAttributes * pDefaultVisAttributes)
Referenced by G4PhysicalVolumeModel::Validate().
void G4ModelingParameters::SetDensityCulling (G4bool)
void G4ModelingParameters::SetDrawingStyle (DrawingStyle)
void G4ModelingParameters::SetEvent (const G4Event * pEvent)
Referenced by G4VSceneHandler::DrawEndOfRunModels(), and G4VSceneHandler::DrawEvent().
void G4ModelingParameters::SetExplodeCentre (const G4Point3D & explodeCentre)
Referenced by G4VSceneHandler::CreateModelingParameters().
void G4ModelingParameters::SetExplodeFactor (G4double explodeFactor)
Referenced by G4VSceneHandler::CreateModelingParameters().
G4int G4ModelingParameters::SetNoOfSides (G4int nSides)
Definition at line 132 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 132 of file G4ModelingParameters.cc
References fNoOfSides, fpDefaultVisAttributes, fWarning, G4cout, G4endl, and G4VisAttributes::GetMinLineSegmentsPerCircle().
void G4ModelingParameters::SetNumberOfCloudPoints (G4int)
Referenced by G4VSceneHandler::CreateModelingParameters().
void G4ModelingParameters::SetSectionSolid (G4DisplacedSolid * pSectionSolid)
Definition at line 146 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 146 of file G4ModelingParameters.cc
Referenced by G4VSceneHandler::CreateModelingParameters().
void G4ModelingParameters::SetVisAttributesModifiers (const std::vector< VisAttributesModifier > &)
Referenced by G4VSceneHandler::CreateModelingParameters().
void G4ModelingParameters::SetVisibleDensity (G4double visibleDensity)
Definition at line 115 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 115 of file G4ModelingParameters.cc
References cm3, fVisibleDensity, fWarning, Acts::UnitConstants::g, G4cout, and G4endl.
void G4ModelingParameters::SetWarning (G4bool)
Referenced by G4VSceneHandler::CreateModelingParameters().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4ModelingParameters & mp) friend
Definition at line 157 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 157 of file G4ModelingParameters.cc
std::ostream& operator<< (std::ostream & os, const PVNameCopyNoPath & vec) friend
Definition at line 135 of file CexmcAngularRange.cc.
View newest version in sPHENIX GitHub at line 135 of file CexmcAngularRange.cc
std::ostream& operator<< (std::ostream & os, const PVPointerCopyNoPath & vec) friend
Definition at line 135 of file CexmcAngularRange.cc.
View newest version in sPHENIX GitHub at line 135 of file CexmcAngularRange.cc
std::ostream& operator<< (std::ostream & os, const std::vector< VisAttributesModifier > & vams) friend
Definition at line 389 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 389 of file G4ModelingParameters.cc
Member Data Documentation
G4int G4ModelingParameters::fCBDAlgorithmNumber private
Definition at line 227 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 227 of file G4ModelingParameters.hh
Referenced by operator<<().
std::vector<G4double> G4ModelingParameters::fCBDParameters private
Definition at line 228 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 228 of file G4ModelingParameters.hh
Referenced by operator<<().
G4bool G4ModelingParameters::fCullCovered private
Definition at line 226 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 226 of file G4ModelingParameters.hh
Referenced by operator<<().
G4bool G4ModelingParameters::fCulling private
Definition at line 222 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 222 of file G4ModelingParameters.hh
Referenced by operator<<().
G4bool G4ModelingParameters::fCullInvisible private
Definition at line 223 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 223 of file G4ModelingParameters.hh
Referenced by operator<<().
G4bool G4ModelingParameters::fDensityCulling private
Definition at line 224 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 224 of file G4ModelingParameters.hh
Referenced by operator<<().
DrawingStyle G4ModelingParameters::fDrawingStyle private
Definition at line 219 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 219 of file G4ModelingParameters.hh
Referenced by operator<<().
G4Point3D G4ModelingParameters::fExplodeCentre private
Definition at line 230 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 230 of file G4ModelingParameters.hh
Referenced by operator<<().
G4double G4ModelingParameters::fExplodeFactor private
Definition at line 229 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 229 of file G4ModelingParameters.hh
Referenced by operator<<().
G4int G4ModelingParameters::fNoOfSides private
Definition at line 231 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 231 of file G4ModelingParameters.hh
Referenced by operator<<(), and SetNoOfSides().
G4int G4ModelingParameters::fNumberOfCloudPoints private
Definition at line 220 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 220 of file G4ModelingParameters.hh
Referenced by operator<<().
G4DisplacedSolid* G4ModelingParameters::fpCutawaySolid private
Definition at line 233 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 233 of file G4ModelingParameters.hh
Referenced by operator<<(), and ~G4ModelingParameters().
const G4VisAttributes* G4ModelingParameters::fpDefaultVisAttributes private
Definition at line 218 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 218 of file G4ModelingParameters.hh
Referenced by operator<<(), and SetNoOfSides().
const G4Event* G4ModelingParameters::fpEvent private
Definition at line 234 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 234 of file G4ModelingParameters.hh
Referenced by operator<<().
G4DisplacedSolid* G4ModelingParameters::fpSectionSolid private
Definition at line 232 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 232 of file G4ModelingParameters.hh
Referenced by operator<<(), and ~G4ModelingParameters().
std::vector<VisAttributesModifier> G4ModelingParameters::fVisAttributesModifiers private
Definition at line 235 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 235 of file G4ModelingParameters.hh
Referenced by operator<<().
G4double G4ModelingParameters::fVisibleDensity private
Definition at line 225 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 225 of file G4ModelingParameters.hh
Referenced by operator<<(), and SetVisibleDensity().
G4bool G4ModelingParameters::fWarning private
Definition at line 217 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 217 of file G4ModelingParameters.hh
Referenced by operator<<(), SetNoOfSides(), and SetVisibleDensity().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ModelingParameters.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4ModelingParameters.cc