ECCE @ EIC Software: G4PenelopeBremsstrahlungModel Class Reference
G4PenelopeBremsstrahlungModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeBremsstrahlungModel.hh>
Public Member Functions
G4PenelopeBremsstrahlungModel (const G4ParticleDefinition *p=0, const G4String &processName="PenBrem")
virtual ~G4PenelopeBremsstrahlungModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *theParticle, G4double kinEnergy, G4double Z, G4double A=0, G4double cut=0, G4double emax=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *theParticle, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy=DBL_MAX)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
void SetVerbosityLevel (G4int lev)
G4int GetVerbosityLevel ()
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForLoss * fParticleChange
const G4ParticleDefinition * fParticle
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
void ClearTables ()
G4PenelopeBremsstrahlungModel & operator= (const G4PenelopeBremsstrahlungModel &right)
G4PenelopeBremsstrahlungModel (const G4PenelopeBremsstrahlungModel &)
G4PenelopeCrossSection * GetCrossSectionTableForCouple (const G4ParticleDefinition *, const G4Material *, G4double cut)
void SetParticle (const G4ParticleDefinition *)
void BuildXSTable (const G4Material *material, G4double cut)
G4double GetPositronXSCorrection (const G4Material *, G4double energy)
Private Attributes
G4double fIntrinsicLowEnergyLimit
G4double fIntrinsicHighEnergyLimit
G4int verboseLevel
G4bool isInitialised
G4PenelopeOscillatorManager * oscManager
G4PhysicsLogVector * energyGrid
size_t nBins
std::map< std::pair< const
G4Material *, G4double >
, G4PenelopeCrossSection * > * XSTableElectron
std::map< std::pair< const
G4Material *, G4double >
, G4PenelopeCrossSection * > * XSTablePositron
G4PenelopeBremsstrahlungFS * fPenelopeFSHelper
G4PenelopeBremsstrahlungAngular * fPenelopeAngular
G4bool fLocalTable
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 62 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 62 of file G4PenelopeBremsstrahlungModel.hh
Constructor & Destructor Documentation
G4PenelopeBremsstrahlungModel::G4PenelopeBremsstrahlungModel (const G4ParticleDefinition * p = 0, const G4String & processName = "PenBrem")
Definition at line 63 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 63 of file G4PenelopeBremsstrahlungModel.cc
References eV, fIntrinsicHighEnergyLimit, fIntrinsicLowEnergyLimit, G4PenelopeOscillatorManager::GetOscillatorManager(), GeV, nBins, oscManager, G4VEmModel::SetDeexcitationFlag(), G4VEmModel::SetHighEnergyLimit(), SetParticle(), and verboseLevel.
G4PenelopeBremsstrahlungModel::~G4PenelopeBremsstrahlungModel () virtual
Definition at line 98 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 98 of file G4PenelopeBremsstrahlungModel.cc
References ClearTables(), fLocalTable, fPenelopeAngular, fPenelopeFSHelper, and G4VEmModel::IsMaster().
G4PenelopeBremsstrahlungModel::G4PenelopeBremsstrahlungModel (const G4PenelopeBremsstrahlungModel &) private
Member Function Documentation
void G4PenelopeBremsstrahlungModel::BuildXSTable (const G4Material * material, G4double cut) private
Definition at line 480 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 480 of file G4PenelopeBremsstrahlungModel.cc
References G4PenelopeCrossSection::AddCrossSectionPoint(), bin, source.hepunit::electron_mass_c2, energy, energyGrid, FatalException, fLocalTable, fPenelopeFSHelper, G4cout, G4endl, G4Exception(), G4Exp(), G4PenelopeBremsstrahlungFS::GetEffectiveZSquared(), G4PhysicsVector::GetLowEdgeEnergy(), G4PenelopeBremsstrahlungFS::GetMomentumIntegral(), G4Material::GetName(), G4PenelopeBremsstrahlungFS::GetNBinsX(), GetPositronXSCorrection(), G4PenelopeBremsstrahlungFS::GetScaledXSTable(), G4PhysicsVector::GetVectorLength(), G4VEmModel::IsMaster(), keV, nBins, verboseLevel, XSTableElectron, and XSTablePositron.
Referenced by GetCrossSectionTableForCouple(), and Initialise().
void G4PenelopeBremsstrahlungModel::ClearTables () private
Definition at line 436 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 436 of file G4PenelopeBremsstrahlungModel.cc
References G4PenelopeBremsstrahlungFS::ClearTables(), FatalException, fLocalTable, fPenelopeFSHelper, G4cout, G4endl, G4Exception(), G4VEmModel::IsMaster(), verboseLevel, XSTableElectron, and XSTablePositron.
Referenced by Initialise(), and ~G4PenelopeBremsstrahlungModel().
G4double G4PenelopeBremsstrahlungModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * theParticle, G4double kinEnergy, G4double Z, G4double A = 0, G4double cut = 0, G4double emax = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 281 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 281 of file G4PenelopeBremsstrahlungModel.cc
References G4cout, and G4endl.
G4double G4PenelopeBremsstrahlungModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * theParticle, G4double kineticEnergy, G4double cutEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 297 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 297 of file G4PenelopeBremsstrahlungModel.cc
References G4cout, G4endl, G4PenelopeOscillatorManager::GetAtomsPerMolecule(), GetCrossSectionTableForCouple(), G4PenelopeCrossSection::GetSoftStoppingPower(), G4Material::GetTotNbOfAtomsPerVolume(), keV, mm, oscManager, and verboseLevel.
G4double G4PenelopeBremsstrahlungModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * theParticle, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 233 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 233 of file G4PenelopeBremsstrahlungModel.cc
References G4cout, G4endl, G4PenelopeOscillatorManager::GetAtomsPerMolecule(), GetCrossSectionTableForCouple(), G4PenelopeCrossSection::GetHardCrossSection(), G4Material::GetName(), G4Material::GetTotNbOfAtomsPerVolume(), keV, mm, oscManager, G4VEmModel::SetupForMaterial(), and verboseLevel.
G4PenelopeCrossSection * G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple (const G4ParticleDefinition * part, const G4Material * mat, G4double cut) private
Definition at line 595 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 595 of file G4PenelopeBremsstrahlungModel.cc
References G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), BuildXSTable(), G4Electron::Electron(), energyGrid, FatalException, fLocalTable, fPenelopeFSHelper, G4endl, G4Exception(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), JustWarning, keV, G4VEmModel::LowEnergyLimit(), nBins, G4Positron::Positron(), G4TemplateAutoLock< _Mutex_t >::unlock(), verboseLevel, XSTableElectron, and XSTablePositron.
Referenced by ComputeDEDXPerVolume(), and CrossSectionPerVolume().
G4double G4PenelopeBremsstrahlungModel::GetPositronXSCorrection (const G4Material * mat, G4double energy) private
Definition at line 708 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 708 of file G4PenelopeBremsstrahlungModel.cc
References e, e6, source.hepunit::electron_mass_c2, fPenelopeFSHelper, G4Exp(), G4PenelopeBremsstrahlungFS::GetEffectiveZSquared(), and t.
Referenced by BuildXSTable().
G4int G4PenelopeBremsstrahlungModel::GetVerbosityLevel () inline
Definition at line 108 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PenelopeBremsstrahlungModel.hh
References verboseLevel.
void G4PenelopeBremsstrahlungModel::Initialise (const G4ParticleDefinition * part, const G4DataVector & theCuts) virtual
Implements G4VEmModel.
Definition at line 113 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 113 of file G4PenelopeBremsstrahlungModel.cc
References G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), BuildXSTable(), ClearTables(), energyGrid, fParticle, fParticleChange, fPenelopeAngular, fPenelopeFSHelper, G4cout, G4endl, G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4VEmModel::GetParticleChangeForLoss(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), GeV, G4VEmModel::HighEnergyLimit(), G4PenelopeBremsstrahlungAngular::Initialize(), isInitialised, G4VEmModel::IsMaster(), keV, G4VEmModel::LowEnergyLimit(), max, nBins, G4PenelopeBremsstrahlungAngular::PrepareTables(), SetParticle(), verboseLevel, XSTableElectron, and XSTablePositron.
void G4PenelopeBremsstrahlungModel::InitialiseLocal (const G4ParticleDefinition * part, G4VEmModel * masterModel) virtual
Reimplemented from G4VEmModel.
Definition at line 179 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 179 of file G4PenelopeBremsstrahlungModel.cc
References energyGrid, fParticle, fPenelopeAngular, fPenelopeFSHelper, G4cout, G4endl, G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4PenelopeBremsstrahlungAngular::Initialize(), G4VEmModel::IsMaster(), nBins, G4PenelopeBremsstrahlungAngular::PrepareTables(), verboseLevel, XSTableElectron, and XSTablePositron.
G4double G4PenelopeBremsstrahlungModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple *) virtual
Reimplemented from G4VEmModel.
Definition at line 472 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 472 of file G4PenelopeBremsstrahlungModel.cc
References fIntrinsicLowEnergyLimit.
G4PenelopeBremsstrahlungModel& G4PenelopeBremsstrahlungModel::operator= (const G4PenelopeBremsstrahlungModel & right) private
void G4PenelopeBremsstrahlungModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicParticle, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 333 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 333 of file G4PenelopeBremsstrahlungModel.cc
References CLHEP::Hep3Vector::cosTheta(), fIntrinsicLowEnergyLimit, fParticleChange, fPenelopeAngular, fPenelopeFSHelper, G4cout, G4endl, G4Gamma::Gamma(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4Material::GetName(), keV, material(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForLoss::ProposeMomentumDirection(), return(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), CLHEP::Hep3Vector::unit(), and verboseLevel.
void G4PenelopeBremsstrahlungModel::SetParticle (const G4ParticleDefinition * p) private
Definition at line 727 of file G4PenelopeBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 727 of file G4PenelopeBremsstrahlungModel.cc
References fParticle.
Referenced by G4PenelopeBremsstrahlungModel(), and Initialise().
void G4PenelopeBremsstrahlungModel::SetVerbosityLevel (G4int lev) inline
Definition at line 107 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4PenelopeBremsstrahlungModel.hh
References verboseLevel.
Member Data Documentation
G4PhysicsLogVector* G4PenelopeBremsstrahlungModel::energyGrid private
Definition at line 139 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 139 of file G4PenelopeBremsstrahlungModel.hh
Referenced by BuildXSTable(), GetCrossSectionTableForCouple(), Initialise(), and InitialiseLocal().
G4double G4PenelopeBremsstrahlungModel::fIntrinsicHighEnergyLimit private
Definition at line 126 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 126 of file G4PenelopeBremsstrahlungModel.hh
Referenced by G4PenelopeBremsstrahlungModel().
G4double G4PenelopeBremsstrahlungModel::fIntrinsicLowEnergyLimit private
Definition at line 125 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PenelopeBremsstrahlungModel.hh
Referenced by G4PenelopeBremsstrahlungModel(), MinEnergyCut(), and SampleSecondaries().
G4bool G4PenelopeBremsstrahlungModel::fLocalTable private
Definition at line 151 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 151 of file G4PenelopeBremsstrahlungModel.hh
Referenced by BuildXSTable(), ClearTables(), GetCrossSectionTableForCouple(), and ~G4PenelopeBremsstrahlungModel().
const G4ParticleDefinition* G4PenelopeBremsstrahlungModel::fParticle protected
Definition at line 112 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PenelopeBremsstrahlungModel.hh
Referenced by Initialise(), InitialiseLocal(), and SetParticle().
G4ParticleChangeForLoss* G4PenelopeBremsstrahlungModel::fParticleChange protected
Definition at line 108 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PenelopeBremsstrahlungModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4PenelopeBremsstrahlungAngular* G4PenelopeBremsstrahlungModel::fPenelopeAngular private
Definition at line 148 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4PenelopeBremsstrahlungModel.hh
Referenced by Initialise(), InitialiseLocal(), SampleSecondaries(), and ~G4PenelopeBremsstrahlungModel().
G4PenelopeBremsstrahlungFS* G4PenelopeBremsstrahlungModel::fPenelopeFSHelper private
Definition at line 147 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4PenelopeBremsstrahlungModel.hh
Referenced by BuildXSTable(), ClearTables(), GetCrossSectionTableForCouple(), GetPositronXSCorrection(), Initialise(), InitialiseLocal(), SampleSecondaries(), and ~G4PenelopeBremsstrahlungModel().
G4bool G4PenelopeBremsstrahlungModel::isInitialised private
Definition at line 130 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PenelopeBremsstrahlungModel.hh
Referenced by Initialise().
size_t G4PenelopeBremsstrahlungModel::nBins private
Definition at line 140 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 140 of file G4PenelopeBremsstrahlungModel.hh
Referenced by BuildXSTable(), G4PenelopeBremsstrahlungModel(), GetCrossSectionTableForCouple(), Initialise(), and InitialiseLocal().
G4PenelopeOscillatorManager* G4PenelopeBremsstrahlungModel::oscManager private
Definition at line 132 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 132 of file G4PenelopeBremsstrahlungModel.hh
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), and G4PenelopeBremsstrahlungModel().
G4int G4PenelopeBremsstrahlungModel::verboseLevel private
Definition at line 128 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4PenelopeBremsstrahlungModel.hh
Referenced by BuildXSTable(), ClearTables(), ComputeDEDXPerVolume(), CrossSectionPerVolume(), G4PenelopeBremsstrahlungModel(), GetCrossSectionTableForCouple(), GetVerbosityLevel(), Initialise(), InitialiseLocal(), SampleSecondaries(), and SetVerbosityLevel().
std::map< std::pair<const G4Material*,G4double>, G4PenelopeCrossSection*>* G4PenelopeBremsstrahlungModel::XSTableElectron private
Definition at line 142 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 142 of file G4PenelopeBremsstrahlungModel.hh
Referenced by BuildXSTable(), ClearTables(), GetCrossSectionTableForCouple(), Initialise(), and InitialiseLocal().
std::map< std::pair<const G4Material*,G4double>, G4PenelopeCrossSection*>* G4PenelopeBremsstrahlungModel::XSTablePositron private
Definition at line 143 of file G4PenelopeBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 143 of file G4PenelopeBremsstrahlungModel.hh
Referenced by BuildXSTable(), ClearTables(), GetCrossSectionTableForCouple(), Initialise(), and InitialiseLocal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4PenelopeBremsstrahlungModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4PenelopeBremsstrahlungModel.cc