ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/chem5.cc File Reference
chem5.cc File Reference
Chem5 example.
#include "DetectorConstruction.hh"
#include "PhysicsList.hh"
#include "ActionInitialization.hh"
#include "G4RunManager.hh"
#include "G4DNAChemistryManager.hh"
#include "G4UImanager.hh"
#include "G4UIExecutive.hh"
#include "G4VisExecutive.hh"
#include "CommandLineParser.hh"
Functions
CommandLineParser * parser (0)
unsigned int noise ()
void SetSeed ()
void Parse (int &argc, char **argv)
int main (int argc, char **argv)
bool IsBracket (char c)
Variables
long seed = 0
Detailed Description
Chem5 example.
Definition in file chem5.cc.
Function Documentation
bool IsBracket (char c)
Definition at line 198 of file chem5.cc.
View newest version in sPHENIX GitHub at line 198 of file chem5.cc
int main (int argc, char ** argv)
Definition at line 77 of file chem5.cc.
View newest version in sPHENIX GitHub at line 77 of file chem5.cc
References G4UImanager::ApplyCommand(), G4UIcommand::ConvertToInt(), G4DNAPARSER::CommandLineParser::DeleteInstance(), G4cout, G4endl, G4Threading::G4GetNumberOfCores(), G4DNAPARSER::CommandLineParser::GetCommandIfActive(), G4MTRunManager::GetNumberOfThreads(), G4DNAPARSER::Command::GetOption(), G4UImanager::GetUIpointer(), G4RunManager::Initialize(), G4VisManager::Initialize(), G4UIExecutive::IsGUI(), Parse(), parser(), G4WORLD::PhysicsList, G4UIExecutive::SessionStart(), G4MTRunManager::SetNumberOfThreads(), SetSeed(), and G4RunManager::SetUserInitialization().
unsigned int noise ()
void Parse (int & argc, char ** argv)
CommandLineParser* parser (0)
void SetSeed ()
Variable Documentation
long seed = 0
Definition at line 68 of file chem5.cc.
View newest version in sPHENIX GitHub at line 68 of file chem5.cc