ECCE @ EIC Software: G4H2ToolsManager Class Reference
G4H2ToolsManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4H2ToolsManager.hh>
Public Member Functions
G4H2ToolsManager (const G4AnalysisManagerState &state)
virtual ~G4H2ToolsManager ()
G4int AddH2 (const G4String &name, tools::histo::h2d *h2d)
void AddH2Vector (const std::vector< tools::histo::h2d * > &h2Vector)
tools::histo::h2d * GetH2 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
std::vector< tools::histo::h2d * >
::iterator BeginH2 ()
std::vector< tools::histo::h2d * >
::iterator EndH2 ()
std::vector< tools::histo::h2d * >
::const_iterator BeginConstH2 () const
std::vector< tools::histo::h2d * >
::const_iterator EndConstH2 () const
const std::vector
< tools::histo::h2d * > & GetH2Vector () const
const std::vector
< G4HnInformation * > & GetHnVector () const
Public Member Functions inherited from G4VH2Manager
G4VH2Manager ()
virtual ~G4VH2Manager ()
G4VH2Manager (const G4VH2Manager &rhs)=delete
G4VH2Manager & operator= (const G4VH2Manager &rhs)=delete
Public Member Functions inherited from G4THnManager< tools::histo::h2d >
G4THnManager (const G4AnalysisManagerState &state, const G4String &hnType)
virtual ~G4THnManager ()
G4bool Reset ()
G4bool IsEmpty () const
Protected Member Functions
virtual G4int CreateH2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinScheme="linear", const G4String &ybinScheme="linear") final
virtual G4int CreateH2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none") final
virtual G4bool SetH2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinScheme="linear", const G4String &ybinScheme="linear") final
virtual G4bool SetH2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none") final
virtual G4bool ScaleH2 (G4int id, G4double factor) final
virtual G4bool FillH2 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0) final
virtual G4int GetH2Id (const G4String &name, G4bool warn=true) const final
virtual G4int GetH2Nxbins (G4int id) const final
virtual G4double GetH2Xmin (G4int id) const final
virtual G4double GetH2Xmax (G4int id) const final
virtual G4double GetH2XWidth (G4int id) const final
virtual G4int GetH2Nybins (G4int id) const final
virtual G4double GetH2Ymin (G4int id) const final
virtual G4double GetH2Ymax (G4int id) const final
virtual G4double GetH2YWidth (G4int id) const final
virtual G4bool SetH2Title (G4int id, const G4String &title) final
virtual G4bool SetH2XAxisTitle (G4int id, const G4String &title) final
virtual G4bool SetH2YAxisTitle (G4int id, const G4String &title) final
virtual G4bool SetH2ZAxisTitle (G4int id, const G4String &title) final
virtual G4String GetH2Title (G4int id) const final
virtual G4String GetH2XAxisTitle (G4int id) const final
virtual G4String GetH2YAxisTitle (G4int id) const final
virtual G4String GetH2ZAxisTitle (G4int id) const final
virtual G4bool WriteOnAscii (std::ofstream &output) final
virtual std::shared_ptr
< G4HnManager > GetHnManager () final
Protected Member Functions inherited from G4THnManager< tools::histo::h2d >
void AddTVector (const std::vector< tools::histo::h2d * > &tVector)
std::vector< tools::histo::h2d * >
::iterator BeginT ()
std::vector< tools::histo::h2d * >
::iterator EndT ()
std::vector< tools::histo::h2d * >
::const_iterator BeginConstT () const
std::vector< tools::histo::h2d * >
::const_iterator EndConstT () const
tools::histo::h2d * GetTInFunction (G4int id, G4String functionName, G4bool warn=true, G4bool onlyIfActive=true) const
G4int RegisterT (tools::histo::h2d *t, const G4String &name)
G4int GetTId (const G4String &name, G4bool warn=true) const
Private Member Functions
void AddH2Information (const G4String &name, const G4String &xunitName, const G4String &yunitName, const G4String &xfcnName, const G4String &yfcnName, G4BinScheme xbinScheme, G4BinScheme ybinScheme) const
Static Private Attributes
static const G4int kDimension = 2
Additional Inherited Members
Protected Attributes inherited from G4THnManager< tools::histo::h2d >
const G4AnalysisManagerState & fState
std::vector< tools::histo::h2d * > fTVector
std::map< G4String, G4int > fNameIdMap
std::shared_ptr< G4HnManager > fHnManager
Detailed Description
Definition at line 51 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 51 of file G4H2ToolsManager.hh
Constructor & Destructor Documentation
G4H2ToolsManager::G4H2ToolsManager (const G4AnalysisManagerState & state) explicit
Definition at line 44 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 44 of file G4H2ToolsManager.cc
G4H2ToolsManager::~G4H2ToolsManager () virtual
Definition at line 50 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 50 of file G4H2ToolsManager.cc
Member Function Documentation
G4int G4H2ToolsManager::AddH2 (const G4String & name, tools::histo::h2d * h2d)
Definition at line 604 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 604 of file G4H2ToolsManager.cc
References AddH2Information(), G4THnManager< tools::histo::h2d >::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h2d >::RegisterT().
Referenced by G4CsvAnalysisReader::ReadH2Impl(), G4XmlAnalysisReader::ReadH2Impl(), G4RootAnalysisReader::ReadH2Impl(), and G4Hdf5AnalysisReader::ReadH2Impl().
void G4H2ToolsManager::AddH2Information (const G4String & name, const G4String & xunitName, const G4String & yunitName, const G4String & xfcnName, const G4String & yfcnName, G4BinScheme xbinScheme, G4BinScheme ybinScheme) const private
Definition at line 231 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 231 of file G4H2ToolsManager.cc
References G4HnInformation::AddDimension(), and G4THnManager< tools::histo::h2d >::fHnManager.
Referenced by AddH2(), and CreateH2().
void G4H2ToolsManager::AddH2Vector (const std::vector< tools::histo::h2d * > & h2Vector)
Definition at line 628 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 628 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::AddTVector().
Referenced by G4XmlAnalysisManager::WriteH2(), G4CsvAnalysisManager::WriteH2(), G4Hdf5AnalysisManager::WriteH2(), and G4RootAnalysisManager::WriteH2().
std::vector< tools::histo::h2d * >::const_iterator G4H2ToolsManager::BeginConstH2 () const inline
Definition at line 184 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 184 of file G4H2ToolsManager.hh
References G4THnManager< tools::histo::h2d >::BeginConstT().
std::vector< tools::histo::h2d * >::iterator G4H2ToolsManager::BeginH2 () inline
Definition at line 177 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 177 of file G4H2ToolsManager.hh
References G4THnManager< tools::histo::h2d >::BeginT().
G4int G4H2ToolsManager::CreateH2 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinScheme = "linear", const G4String & ybinScheme = "linear") final protected virtual
Implements G4VH2Manager.
Definition at line 249 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 249 of file G4H2ToolsManager.cc
References AddH2Information(), G4THnManager< tools::histo::h2d >::fState, G4Analysis::GetBinScheme(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h2d >::RegisterT().
G4int G4H2ToolsManager::CreateH2 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none") final protected virtual
Implements G4VH2Manager.
Definition at line 288 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 288 of file G4H2ToolsManager.cc
References AddH2Information(), G4THnManager< tools::histo::h2d >::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h2d >::RegisterT().
std::vector< tools::histo::h2d * >::const_iterator G4H2ToolsManager::EndConstH2 () const inline
Definition at line 188 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 188 of file G4H2ToolsManager.hh
References G4THnManager< tools::histo::h2d >::EndConstT().
std::vector< tools::histo::h2d * >::iterator G4H2ToolsManager::EndH2 () inline
Definition at line 180 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 180 of file G4H2ToolsManager.hh
References G4THnManager< tools::histo::h2d >::EndT().
G4bool G4H2ToolsManager::FillH2 (G4int id, G4double xvalue, G4double yvalue, G4double weight = 1.0) final protected virtual
Implements G4VH2Manager.
Definition at line 401 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 401 of file G4H2ToolsManager.cc
References G4HnDimensionInformation::fFcn, G4THnManager< tools::histo::h2d >::fHnManager, G4THnManager< tools::histo::h2d >::fState, G4HnDimensionInformation::fUnit, G4AnalysisManagerState::GetIsActivation(), G4THnManager< tools::histo::h2d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), G4Analysis::kX, G4Analysis::kY, G4AnalysisVerbose::Message(), and weight.
tools::histo::h2d * G4H2ToolsManager::GetH2 (G4int id, G4bool warn = true, G4bool onlyIfActive = true) const
Definition at line 634 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 634 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::GetTInFunction().
G4int G4H2ToolsManager::GetH2Id (const G4String & name, G4bool warn = true) const final protected virtual
Implements G4VH2Manager.
Definition at line 435 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 435 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::GetTId().
G4int G4H2ToolsManager::GetH2Nxbins (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 441 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 441 of file G4H2ToolsManager.cc
References G4Analysis::GetNbins(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kX.
G4int G4H2ToolsManager::GetH2Nybins (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 479 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 479 of file G4H2ToolsManager.cc
References G4Analysis::GetNbins(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kY.
G4String G4H2ToolsManager::GetH2Title (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 553 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 553 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::GetTitle().
const std::vector< tools::histo::h2d * > & G4H2ToolsManager::GetH2Vector () const inline
Definition at line 191 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 191 of file G4H2ToolsManager.hh
References G4THnManager< tools::histo::h2d >::fTVector.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4ToolsAnalysisManager::PlotImpl(), G4XmlAnalysisManager::WriteH2(), G4CsvAnalysisManager::WriteH2(), G4Hdf5AnalysisManager::WriteH2(), and G4RootAnalysisManager::WriteH2().
G4String G4H2ToolsManager::GetH2XAxisTitle (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 562 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 562 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kX.
G4double G4H2ToolsManager::GetH2Xmax (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 461 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 461 of file G4H2ToolsManager.cc
References G4Analysis::GetMax(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kX.
G4double G4H2ToolsManager::GetH2Xmin (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 450 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 450 of file G4H2ToolsManager.cc
References G4Analysis::GetMin(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kX.
G4double G4H2ToolsManager::GetH2XWidth (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 470 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 470 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::fHnManager, G4THnManager< tools::histo::h2d >::GetTInFunction(), G4Analysis::GetWidth(), and G4Analysis::kX.
G4String G4H2ToolsManager::GetH2YAxisTitle (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 571 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 571 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kY.
G4double G4H2ToolsManager::GetH2Ymax (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 499 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 499 of file G4H2ToolsManager.cc
References G4Analysis::GetMax(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kY.
G4double G4H2ToolsManager::GetH2Ymin (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 488 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 488 of file G4H2ToolsManager.cc
References G4Analysis::GetMin(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kY.
G4double G4H2ToolsManager::GetH2YWidth (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 508 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 508 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::fHnManager, G4THnManager< tools::histo::h2d >::GetTInFunction(), G4Analysis::GetWidth(), and G4Analysis::kY.
G4String G4H2ToolsManager::GetH2ZAxisTitle (G4int id) const final protected virtual
Implements G4VH2Manager.
Definition at line 580 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 580 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::h2d >::GetTInFunction(), and G4Analysis::kZ.
std::shared_ptr< G4HnManager > G4H2ToolsManager::GetHnManager () inline final protected virtual
Implements G4VH2Manager.
Definition at line 197 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 197 of file G4H2ToolsManager.hh
References G4THnManager< tools::histo::h2d >::fHnManager.
const std::vector< G4HnInformation * > & G4H2ToolsManager::GetHnVector () const inline
Definition at line 194 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 194 of file G4H2ToolsManager.hh
References G4THnManager< tools::histo::h2d >::fHnManager.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4ToolsAnalysisManager::PlotImpl(), G4XmlAnalysisManager::WriteH2(), G4CsvAnalysisManager::WriteH2(), G4Hdf5AnalysisManager::WriteH2(), and G4RootAnalysisManager::WriteH2().
G4bool G4H2ToolsManager::ScaleH2 (G4int id, G4double factor) final protected virtual
Implements G4VH2Manager.
Definition at line 392 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 392 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::GetTInFunction().
G4bool G4H2ToolsManager::SetH2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinScheme = "linear", const G4String & ybinScheme = "linear") final protected virtual
Implements G4VH2Manager.
Definition at line 322 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 322 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::fHnManager, G4THnManager< tools::histo::h2d >::fState, G4Analysis::GetBinScheme(), G4THnManager< tools::histo::h2d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4H2ToolsManager::SetH2 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none") final protected virtual
Implements G4VH2Manager.
Definition at line 360 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 360 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::fHnManager, G4THnManager< tools::histo::h2d >::fState, G4THnManager< tools::histo::h2d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4H2ToolsManager::SetH2Title (G4int id, const G4String & title) final protected virtual
Implements G4VH2Manager.
Definition at line 517 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 517 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::GetTInFunction(), and SetTitle().
G4bool G4H2ToolsManager::SetH2XAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VH2Manager.
Definition at line 526 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 526 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::GetTInFunction(), G4Analysis::kX, and G4Analysis::SetAxisTitle().
G4bool G4H2ToolsManager::SetH2YAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VH2Manager.
Definition at line 535 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 535 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::GetTInFunction(), G4Analysis::kY, and G4Analysis::SetAxisTitle().
G4bool G4H2ToolsManager::SetH2ZAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VH2Manager.
Definition at line 544 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 544 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::GetTInFunction(), G4Analysis::kZ, and G4Analysis::SetAxisTitle().
G4bool G4H2ToolsManager::WriteOnAscii (std::ofstream & output) final protected virtual
Implements G4VH2Manager.
Definition at line 589 of file G4H2ToolsManager.cc.
View newest version in sPHENIX GitHub at line 589 of file G4H2ToolsManager.cc
References G4THnManager< tools::histo::h2d >::fHnManager.
Member Data Documentation
const G4int G4H2ToolsManager::kDimension = 2 static private
Definition at line 173 of file G4H2ToolsManager.hh.
View newest version in sPHENIX GitHub at line 173 of file G4H2ToolsManager.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4H2ToolsManager.hh
geant4/tree/geant4-10.6-release/source/analysis/hntools/src/G4H2ToolsManager.cc