ECCE @ EIC Software: B5MagneticField Class Reference
B5MagneticField Class Reference
Magnetic field.
#include <geant4/tree/geant4-10.6-release/examples/basic/B5/include/B5MagneticField.hh>
Public Member Functions
B5MagneticField ()
virtual ~B5MagneticField ()
virtual void GetFieldValue (const G4double point[4], double *bField) const
void SetField (G4double val)
G4double GetField () const
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
virtual G4Field * Clone () const
Private Member Functions
void DefineCommands ()
Private Attributes
G4GenericMessenger * fMessenger
G4double fBy
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Magnetic field.
Definition at line 40 of file B5MagneticField.hh.
View newest version in sPHENIX GitHub at line 40 of file B5MagneticField.hh
Constructor & Destructor Documentation
B5MagneticField::B5MagneticField ()
Definition at line 38 of file B5MagneticField.cc.
View newest version in sPHENIX GitHub at line 38 of file B5MagneticField.cc
References DefineCommands().
B5MagneticField::~B5MagneticField () virtual
Definition at line 48 of file B5MagneticField.cc.
View newest version in sPHENIX GitHub at line 48 of file B5MagneticField.cc
References fMessenger.
Member Function Documentation
void B5MagneticField::DefineCommands () private
Definition at line 62 of file B5MagneticField.cc.
View newest version in sPHENIX GitHub at line 62 of file B5MagneticField.cc
References G4GenericMessenger::DeclareMethodWithUnit(), fMessenger, G4GenericMessenger::Command::SetDefaultValue(), SetField(), and G4GenericMessenger::Command::SetParameterName().
Referenced by B5MagneticField().
G4double B5MagneticField::GetField () const inline
Definition at line 49 of file B5MagneticField.hh.
View newest version in sPHENIX GitHub at line 49 of file B5MagneticField.hh
References fBy.
void B5MagneticField::GetFieldValue (const G4double point[4], double * bField) const virtual
Implements G4MagneticField.
Definition at line 53 of file B5MagneticField.cc.
View newest version in sPHENIX GitHub at line 53 of file B5MagneticField.cc
References fBy.
void B5MagneticField::SetField (G4double val) inline
Definition at line 48 of file B5MagneticField.hh.
View newest version in sPHENIX GitHub at line 48 of file B5MagneticField.hh
References fBy.
Referenced by DefineCommands().
Member Data Documentation
G4double B5MagneticField::fBy private
Definition at line 55 of file B5MagneticField.hh.
View newest version in sPHENIX GitHub at line 55 of file B5MagneticField.hh
Referenced by GetField(), GetFieldValue(), and SetField().
G4GenericMessenger* B5MagneticField::fMessenger private
Definition at line 54 of file B5MagneticField.hh.
View newest version in sPHENIX GitHub at line 54 of file B5MagneticField.hh
Referenced by DefineCommands(), and ~B5MagneticField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B5/include/B5MagneticField.hh
geant4/tree/geant4-10.6-release/examples/basic/B5/src/B5MagneticField.cc