ECCE @ EIC Software: G4SPSRandomGenerator Class Reference
G4SPSRandomGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4SPSRandomGenerator.hh>
Classes
struct a_check
struct bweights_t
Public Member Functions
G4SPSRandomGenerator ()
~G4SPSRandomGenerator ()
void SetXBias (G4ThreeVector)
void SetYBias (G4ThreeVector)
void SetZBias (G4ThreeVector)
void SetThetaBias (G4ThreeVector)
void SetPhiBias (G4ThreeVector)
void SetEnergyBias (G4ThreeVector)
void SetPosThetaBias (G4ThreeVector)
void SetPosPhiBias (G4ThreeVector)
G4double GenRandX ()
G4double GenRandY ()
G4double GenRandZ ()
G4double GenRandTheta ()
G4double GenRandPhi ()
G4double GenRandEnergy ()
G4double GenRandPosTheta ()
G4double GenRandPosPhi ()
void SetIntensityWeight (G4double weight)
G4double GetBiasWeight ()
void ReSetHist (G4String)
void SetVerbosity (G4int a)
Private Attributes
G4Cache< a_check > local_IPDFXBias
G4bool XBias
G4bool IPDFXBias
G4PhysicsOrderedFreeVector XBiasH
G4PhysicsOrderedFreeVector IPDFXBiasH
G4Cache< a_check > local_IPDFYBias
G4bool YBias
G4bool IPDFYBias
G4PhysicsOrderedFreeVector YBiasH
G4PhysicsOrderedFreeVector IPDFYBiasH
G4Cache< a_check > local_IPDFZBias
G4bool ZBias
G4bool IPDFZBias
G4PhysicsOrderedFreeVector ZBiasH
G4PhysicsOrderedFreeVector IPDFZBiasH
G4Cache< a_check > local_IPDFThetaBias
G4bool ThetaBias
G4bool IPDFThetaBias
G4PhysicsOrderedFreeVector ThetaBiasH
G4PhysicsOrderedFreeVector IPDFThetaBiasH
G4Cache< a_check > local_IPDFPhiBias
G4bool PhiBias
G4bool IPDFPhiBias
G4PhysicsOrderedFreeVector PhiBiasH
G4PhysicsOrderedFreeVector IPDFPhiBiasH
G4Cache< a_check > local_IPDFEnergyBias
G4bool EnergyBias
G4bool IPDFEnergyBias
G4PhysicsOrderedFreeVector EnergyBiasH
G4PhysicsOrderedFreeVector IPDFEnergyBiasH
G4Cache< a_check > local_IPDFPosThetaBias
G4bool PosThetaBias
G4bool IPDFPosThetaBias
G4PhysicsOrderedFreeVector PosThetaBiasH
G4PhysicsOrderedFreeVector IPDFPosThetaBiasH
G4Cache< a_check > local_IPDFPosPhiBias
G4bool PosPhiBias
G4bool IPDFPosPhiBias
G4PhysicsOrderedFreeVector PosPhiBiasH
G4PhysicsOrderedFreeVector IPDFPosPhiBiasH
G4Cache< bweights_t > bweights
G4int verbosityLevel
G4Mutex mutex
Detailed Description
Andrea Dotti Feb 2015 Important: This is a shared class between threads. Only one thread should use the set-methods here. Note that this is exactly what is achieved using UI commands. If you use the set methods to set defaults in your application take care that only one thread is executing them. In addition take care of calling these methods before the run is started Do not use these setters during the event loop
Definition at line 157 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 157 of file G4SPSRandomGenerator.hh
Constructor & Destructor Documentation
G4SPSRandomGenerator::G4SPSRandomGenerator ()
Definition at line 73 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 73 of file G4SPSRandomGenerator.cc
References EnergyBias, G4MUTEXINIT, IPDFEnergyBias, IPDFPhiBias, IPDFPosPhiBias, IPDFPosThetaBias, IPDFThetaBias, IPDFXBias, IPDFYBias, IPDFZBias, PhiBias, PosPhiBias, PosThetaBias, ThetaBias, verbosityLevel, XBias, YBias, and ZBias.
G4SPSRandomGenerator::~G4SPSRandomGenerator ()
Definition at line 98 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 98 of file G4SPSRandomGenerator.cc
References G4MUTEXDESTROY.
Member Function Documentation
G4double G4SPSRandomGenerator::GenRandEnergy ()
Definition at line 568 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 568 of file G4SPSRandomGenerator.cc
References bweights, EnergyBias, EnergyBiasH, false, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFEnergyBias, IPDFEnergyBiasH, local_IPDFEnergyBias, sum, verbosityLevel, and w.
Referenced by G4SPSEneDistribution::GenArbPointEnergies(), G4SPSEneDistribution::GenEpnHistEnergies(), G4SPSEneDistribution::GenerateBbodyEnergies(), G4SPSEneDistribution::GenerateBiasPowEnergies(), G4SPSEneDistribution::GenerateBremEnergies(), G4SPSEneDistribution::GenerateCdgEnergies(), G4SPSEneDistribution::GenerateCPowEnergies(), G4SPSEneDistribution::GenerateExpEnergies(), G4SPSEneDistribution::GenerateLinearEnergies(), G4SPSEneDistribution::GeneratePowEnergies(), and G4SPSEneDistribution::GenUserHistEnergies().
G4double G4SPSRandomGenerator::GenRandPhi ()
Definition at line 508 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 508 of file G4SPSRandomGenerator.cc
References bweights, false, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFPhiBias, IPDFPhiBiasH, local_IPDFPhiBias, PhiBias, PhiBiasH, sum, verbosityLevel, and w.
Referenced by G4SPSAngDistribution::GenerateCosineLawFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), and G4SPSAngDistribution::GenerateUserDefFlux().
G4double G4SPSRandomGenerator::GenRandPosPhi ()
Definition at line 693 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 693 of file G4SPSRandomGenerator.cc
References bweights, false, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFPosPhiBias, IPDFPosPhiBiasH, local_IPDFPosPhiBias, PosPhiBias, PosPhiBiasH, sum, verbosityLevel, and w.
Referenced by G4SPSPosDistribution::GeneratePointsOnSurface().
G4double G4SPSRandomGenerator::GenRandPosTheta ()
Definition at line 629 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 629 of file G4SPSRandomGenerator.cc
References bweights, false, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFPosThetaBias, IPDFPosThetaBiasH, local_IPDFPosThetaBias, PosThetaBias, PosThetaBiasH, sum, verbosityLevel, and w.
Referenced by G4SPSPosDistribution::GeneratePointsOnSurface().
G4double G4SPSRandomGenerator::GenRandTheta ()
Definition at line 445 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 445 of file G4SPSRandomGenerator.cc
References bweights, false, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFThetaBias, IPDFThetaBiasH, local_IPDFThetaBias, sum, ThetaBias, ThetaBiasH, verbosityLevel, and w.
Referenced by G4SPSAngDistribution::GenerateCosineLawFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), and G4SPSAngDistribution::GenerateUserDefFlux().
G4double G4SPSRandomGenerator::GenRandX ()
Definition at line 250 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 250 of file G4SPSRandomGenerator.cc
References bweights, false, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFXBias, IPDFXBiasH, local_IPDFXBias, sum, verbosityLevel, w, XBias, and XBiasH.
Referenced by G4SPSPosDistribution::GeneratePointsInBeam(), G4SPSPosDistribution::GeneratePointsInPlane(), G4SPSPosDistribution::GeneratePointsInVolume(), and G4SPSPosDistribution::GeneratePointsOnSurface().
G4double G4SPSRandomGenerator::GenRandY ()
Definition at line 327 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 327 of file G4SPSRandomGenerator.cc
References bweights, false, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFYBias, IPDFYBiasH, local_IPDFYBias, sum, verbosityLevel, w, YBias, and YBiasH.
Referenced by G4SPSPosDistribution::GeneratePointsInBeam(), G4SPSPosDistribution::GeneratePointsInPlane(), G4SPSPosDistribution::GeneratePointsInVolume(), and G4SPSPosDistribution::GeneratePointsOnSurface().
G4double G4SPSRandomGenerator::GenRandZ ()
Definition at line 385 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 385 of file G4SPSRandomGenerator.cc
References bweights, false, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetVectorLength(), G4PhysicsOrderedFreeVector::InsertValues(), IPDFZBias, IPDFZBiasH, local_IPDFZBias, sum, verbosityLevel, w, ZBias, and ZBiasH.
Referenced by G4SPSPosDistribution::GeneratePointsInVolume(), and G4SPSPosDistribution::GeneratePointsOnSurface().
G4double G4SPSRandomGenerator::GetBiasWeight ()
Definition at line 186 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 186 of file G4SPSRandomGenerator.cc
References bweights, G4Cache< VALTYPE >::Get(), and w.
Referenced by G4SingleParticleSource::GeneratePrimaryVertex().
void G4SPSRandomGenerator::ReSetHist (G4String atype)
Definition at line 203 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 203 of file G4SPSRandomGenerator.cc
References EnergyBias, EnergyBiasH, G4cout, G4endl, G4Cache< VALTYPE >::Get(), IPDFEnergyBias, IPDFEnergyBiasH, IPDFPhiBias, IPDFPhiBiasH, IPDFPosPhiBias, IPDFPosPhiBiasH, IPDFPosThetaBias, IPDFPosThetaBiasH, IPDFThetaBias, IPDFThetaBiasH, IPDFXBias, IPDFXBiasH, IPDFYBias, IPDFYBiasH, IPDFZBias, IPDFZBiasH, local_IPDFEnergyBias, local_IPDFPhiBias, local_IPDFPosPhiBias, local_IPDFPosThetaBias, local_IPDFThetaBias, local_IPDFXBias, local_IPDFYBias, local_IPDFZBias, PhiBias, PhiBiasH, PosPhiBias, PosPhiBiasH, PosThetaBias, PosThetaBiasH, ThetaBias, ThetaBiasH, XBias, XBiasH, YBias, YBiasH, ZBias, and ZBiasH.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSRandomGenerator::SetEnergyBias (G4ThreeVector input)
Definition at line 155 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 155 of file G4SPSRandomGenerator.cc
References EnergyBias, EnergyBiasH, G4PhysicsOrderedFreeVector::InsertValues(), CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSRandomGenerator::SetIntensityWeight (G4double weight)
Definition at line 182 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 182 of file G4SPSRandomGenerator.cc
References bweights, G4Cache< VALTYPE >::Get(), and weight.
Referenced by G4GeneralParticleSourceData::IntensityNormalise().
void G4SPSRandomGenerator::SetPhiBias (G4ThreeVector input)
Definition at line 146 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 146 of file G4SPSRandomGenerator.cc
References G4PhysicsOrderedFreeVector::InsertValues(), PhiBias, PhiBiasH, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSRandomGenerator::SetPosPhiBias (G4ThreeVector input)
Definition at line 173 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 173 of file G4SPSRandomGenerator.cc
References G4PhysicsOrderedFreeVector::InsertValues(), PosPhiBias, PosPhiBiasH, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSRandomGenerator::SetPosThetaBias (G4ThreeVector input)
Definition at line 164 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 164 of file G4SPSRandomGenerator.cc
References G4PhysicsOrderedFreeVector::InsertValues(), PosThetaBias, PosThetaBiasH, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSRandomGenerator::SetThetaBias (G4ThreeVector input)
Definition at line 137 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 137 of file G4SPSRandomGenerator.cc
References G4PhysicsOrderedFreeVector::InsertValues(), ThetaBias, ThetaBiasH, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSRandomGenerator::SetVerbosity (G4int a)
Definition at line 193 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 193 of file G4SPSRandomGenerator.cc
References a, and verbosityLevel.
void G4SPSRandomGenerator::SetXBias (G4ThreeVector input)
Definition at line 110 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 110 of file G4SPSRandomGenerator.cc
References G4PhysicsOrderedFreeVector::InsertValues(), CLHEP::Hep3Vector::x(), XBias, XBiasH, and CLHEP::Hep3Vector::y().
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSRandomGenerator::SetYBias (G4ThreeVector input)
Definition at line 119 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 119 of file G4SPSRandomGenerator.cc
References G4PhysicsOrderedFreeVector::InsertValues(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), YBias, and YBiasH.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSRandomGenerator::SetZBias (G4ThreeVector input)
Definition at line 128 of file G4SPSRandomGenerator.cc.
View newest version in sPHENIX GitHub at line 128 of file G4SPSRandomGenerator.cc
References G4PhysicsOrderedFreeVector::InsertValues(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), ZBias, and ZBiasH.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
Member Data Documentation
G4Cache<bweights_t> G4SPSRandomGenerator::bweights private
Definition at line 241 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 241 of file G4SPSRandomGenerator.hh
Referenced by GenRandEnergy(), GenRandPhi(), GenRandPosPhi(), GenRandPosTheta(), GenRandTheta(), GenRandX(), GenRandY(), GenRandZ(), GetBiasWeight(), and SetIntensityWeight().
G4bool G4SPSRandomGenerator::EnergyBias private
Definition at line 223 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 223 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandEnergy(), ReSetHist(), and SetEnergyBias().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::EnergyBiasH private
Definition at line 224 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 224 of file G4SPSRandomGenerator.hh
Referenced by GenRandEnergy(), ReSetHist(), and SetEnergyBias().
G4bool G4SPSRandomGenerator::IPDFEnergyBias private
Definition at line 223 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 223 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandEnergy(), and ReSetHist().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::IPDFEnergyBiasH private
Definition at line 225 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 225 of file G4SPSRandomGenerator.hh
Referenced by GenRandEnergy(), and ReSetHist().
G4bool G4SPSRandomGenerator::IPDFPhiBias private
Definition at line 219 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 219 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandPhi(), and ReSetHist().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::IPDFPhiBiasH private
Definition at line 221 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 221 of file G4SPSRandomGenerator.hh
Referenced by GenRandPhi(), and ReSetHist().
G4bool G4SPSRandomGenerator::IPDFPosPhiBias private
Definition at line 231 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 231 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandPosPhi(), and ReSetHist().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::IPDFPosPhiBiasH private
Definition at line 233 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 233 of file G4SPSRandomGenerator.hh
Referenced by GenRandPosPhi(), and ReSetHist().
G4bool G4SPSRandomGenerator::IPDFPosThetaBias private
Definition at line 227 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 227 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandPosTheta(), and ReSetHist().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::IPDFPosThetaBiasH private
Definition at line 229 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 229 of file G4SPSRandomGenerator.hh
Referenced by GenRandPosTheta(), and ReSetHist().
G4bool G4SPSRandomGenerator::IPDFThetaBias private
Definition at line 215 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 215 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandTheta(), and ReSetHist().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::IPDFThetaBiasH private
Definition at line 217 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 217 of file G4SPSRandomGenerator.hh
Referenced by GenRandTheta(), and ReSetHist().
G4bool G4SPSRandomGenerator::IPDFXBias private
Definition at line 203 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 203 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandX(), and ReSetHist().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::IPDFXBiasH private
Definition at line 205 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 205 of file G4SPSRandomGenerator.hh
Referenced by GenRandX(), and ReSetHist().
G4bool G4SPSRandomGenerator::IPDFYBias private
Definition at line 207 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 207 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandY(), and ReSetHist().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::IPDFYBiasH private
Definition at line 209 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 209 of file G4SPSRandomGenerator.hh
Referenced by GenRandY(), and ReSetHist().
G4bool G4SPSRandomGenerator::IPDFZBias private
Definition at line 211 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 211 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandZ(), and ReSetHist().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::IPDFZBiasH private
Definition at line 213 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 213 of file G4SPSRandomGenerator.hh
Referenced by GenRandZ(), and ReSetHist().
G4Cache<a_check> G4SPSRandomGenerator::local_IPDFEnergyBias private
Definition at line 222 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 222 of file G4SPSRandomGenerator.hh
Referenced by GenRandEnergy(), and ReSetHist().
G4Cache<a_check> G4SPSRandomGenerator::local_IPDFPhiBias private
Definition at line 218 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 218 of file G4SPSRandomGenerator.hh
Referenced by GenRandPhi(), and ReSetHist().
G4Cache<a_check> G4SPSRandomGenerator::local_IPDFPosPhiBias private
Definition at line 230 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 230 of file G4SPSRandomGenerator.hh
Referenced by GenRandPosPhi(), and ReSetHist().
G4Cache<a_check> G4SPSRandomGenerator::local_IPDFPosThetaBias private
Definition at line 226 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 226 of file G4SPSRandomGenerator.hh
Referenced by GenRandPosTheta(), and ReSetHist().
G4Cache<a_check> G4SPSRandomGenerator::local_IPDFThetaBias private
Definition at line 214 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 214 of file G4SPSRandomGenerator.hh
Referenced by GenRandTheta(), and ReSetHist().
G4Cache<a_check> G4SPSRandomGenerator::local_IPDFXBias private
Definition at line 202 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 202 of file G4SPSRandomGenerator.hh
Referenced by GenRandX(), and ReSetHist().
G4Cache<a_check> G4SPSRandomGenerator::local_IPDFYBias private
Definition at line 206 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 206 of file G4SPSRandomGenerator.hh
Referenced by GenRandY(), and ReSetHist().
G4Cache<a_check> G4SPSRandomGenerator::local_IPDFZBias private
Definition at line 210 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 210 of file G4SPSRandomGenerator.hh
Referenced by GenRandZ(), and ReSetHist().
G4Mutex G4SPSRandomGenerator::mutex private
Definition at line 247 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 247 of file G4SPSRandomGenerator.hh
G4bool G4SPSRandomGenerator::PhiBias private
Definition at line 219 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 219 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandPhi(), ReSetHist(), and SetPhiBias().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::PhiBiasH private
Definition at line 220 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 220 of file G4SPSRandomGenerator.hh
Referenced by GenRandPhi(), ReSetHist(), and SetPhiBias().
G4bool G4SPSRandomGenerator::PosPhiBias private
Definition at line 231 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 231 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandPosPhi(), ReSetHist(), and SetPosPhiBias().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::PosPhiBiasH private
Definition at line 232 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 232 of file G4SPSRandomGenerator.hh
Referenced by GenRandPosPhi(), ReSetHist(), and SetPosPhiBias().
G4bool G4SPSRandomGenerator::PosThetaBias private
Definition at line 227 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 227 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandPosTheta(), ReSetHist(), and SetPosThetaBias().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::PosThetaBiasH private
Definition at line 228 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 228 of file G4SPSRandomGenerator.hh
Referenced by GenRandPosTheta(), ReSetHist(), and SetPosThetaBias().
G4bool G4SPSRandomGenerator::ThetaBias private
Definition at line 215 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 215 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandTheta(), ReSetHist(), and SetThetaBias().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::ThetaBiasH private
Definition at line 216 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 216 of file G4SPSRandomGenerator.hh
Referenced by GenRandTheta(), ReSetHist(), and SetThetaBias().
G4int G4SPSRandomGenerator::verbosityLevel private
Definition at line 245 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 245 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandEnergy(), GenRandPhi(), GenRandPosPhi(), GenRandPosTheta(), GenRandTheta(), GenRandX(), GenRandY(), GenRandZ(), and SetVerbosity().
G4bool G4SPSRandomGenerator::XBias private
Definition at line 203 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 203 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandX(), ReSetHist(), and SetXBias().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::XBiasH private
Definition at line 204 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 204 of file G4SPSRandomGenerator.hh
Referenced by GenRandX(), ReSetHist(), and SetXBias().
G4bool G4SPSRandomGenerator::YBias private
Definition at line 207 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 207 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandY(), ReSetHist(), and SetYBias().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::YBiasH private
Definition at line 208 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 208 of file G4SPSRandomGenerator.hh
Referenced by GenRandY(), ReSetHist(), and SetYBias().
G4bool G4SPSRandomGenerator::ZBias private
Definition at line 211 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 211 of file G4SPSRandomGenerator.hh
Referenced by G4SPSRandomGenerator(), GenRandZ(), ReSetHist(), and SetZBias().
G4PhysicsOrderedFreeVector G4SPSRandomGenerator::ZBiasH private
Definition at line 212 of file G4SPSRandomGenerator.hh.
View newest version in sPHENIX GitHub at line 212 of file G4SPSRandomGenerator.hh
Referenced by GenRandZ(), ReSetHist(), and SetZBias().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4SPSRandomGenerator.hh
geant4/tree/geant4-10.6-release/source/event/src/G4SPSRandomGenerator.cc