ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/ChargeExchangeMC.cc File Reference
ChargeExchangeMC.cc File Reference
#include <set>
#include <G4UImanager.hh>
#include <G4String.hh>
#include <G4UIsession.hh>
#include <G4UIterminal.hh>
#include <G4VisExecutive.hh>
#include "CexmcRunManager.hh"
#include "CexmcHistoManager.hh"
#include "CexmcSetup.hh"
#include "CexmcPhysicsList.hh"
#include "CexmcPhysicsManager.hh"
#include "CexmcPrimaryGeneratorAction.hh"
#include "CexmcTrackingAction.hh"
#include "CexmcSteppingAction.hh"
#include "CexmcEventAction.hh"
#include "CexmcRunAction.hh"
#include "CexmcMessenger.hh"
#include "CexmcException.hh"
#include "CexmcBasicPhysicsSettings.hh"
#include "CexmcCommon.hh"
Classes
struct CexmcCmdLineData
Functions
void printUsage (void)
G4bool parseArgs (int argc, char **argv, CexmcCmdLineData &cmdLineData)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 292 of file ChargeExchangeMC.cc.
View newest version in sPHENIX GitHub at line 292 of file ChargeExchangeMC.cc
References G4UImanager::ApplyCommand(), CEXMC_LINE_START, CexmcCmdLineParseException, CexmcOutputEvents, CexmcPionZeroProduction, CexmcPreinitException, CexmcUnknownProductionModel, CexmcWeirdException, CexmcCmdLineData::customFilter, CexmcMessenger::Destroy(), e, G4cout, G4endl, CexmcRunManager::GetGdmlFileName(), CexmcRunManager::GetGuiMacroName(), CexmcPhysicsManager::GetProductionModel(), CexmcRunManager::GetProductionModelType(), G4UImanager::GetUIpointer(), G4RunManager::Initialize(), G4VisManager::Initialize(), CexmcCmdLineData::initMacro, CexmcMessenger::Instance(), CexmcCmdLineData::isInteractive, CexmcCmdLineData::outputData, CexmcCmdLineData::overrideExistingProject, parseArgs(), CexmcCmdLineData::preinitMacro, printUsage(), CexmcRunManager::ProjectIsRead(), CexmcRunManager::ProjectIsSaved(), CexmcCmdLineData::rProject, session, G4UIsession::SessionStart(), CexmcRunManager::SetPhysicsManager(), G4RunManager::SetUserAction(), G4RunManager::SetUserInitialization(), CexmcRunManager::ShouldGdmlFileBeValidated(), CexmcCmdLineData::startQtSession, CexmcException::what(), and CexmcCmdLineData::wProject.
G4bool parseArgs (int argc, char ** argv, CexmcCmdLineData & cmdLineData)
Definition at line 151 of file ChargeExchangeMC.cc.
View newest version in sPHENIX GitHub at line 151 of file ChargeExchangeMC.cc
References CexmcCmdLineParseException, CexmcOutputEvents, CexmcOutputGeometry, CexmcOutputRun, CexmcCmdLineData::customFilter, CexmcCmdLineData::initMacro, CexmcCmdLineData::isInteractive, k, CexmcCmdLineData::outputData, CexmcCmdLineData::overrideExistingProject, CexmcCmdLineData::preinitMacro, CexmcCmdLineData::rProject, split(), CexmcCmdLineData::startQtSession, and CexmcCmdLineData::wProject.
Referenced by main().
void printUsage (void)
Definition at line 105 of file ChargeExchangeMC.cc.
View newest version in sPHENIX GitHub at line 105 of file ChargeExchangeMC.cc
References G4cout, and G4endl.
Referenced by main().