ECCE @ EIC Software: G4BinaryPionBuilder Class Reference
G4BinaryPionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BinaryPionBuilder.hh>
Public Member Functions
G4BinaryPionBuilder ()
virtual ~G4BinaryPionBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
void SetMinEnergy (G4double aM) finaloverride
void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPionBuilder
G4VPionBuilder ()=default
virtual ~G4VPionBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4BinaryCascade * theModel
G4double theMin
G4double theMax
Detailed Description
Definition at line 52 of file G4BinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BinaryPionBuilder.hh
Constructor & Destructor Documentation
G4BinaryPionBuilder::G4BinaryPionBuilder ()
Definition at line 48 of file G4BinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4BinaryPionBuilder.cc
References GeV, G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual G4BinaryPionBuilder::~G4BinaryPionBuilder () inline virtual
Definition at line 56 of file G4BinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4BinaryPionBuilder.hh
Member Function Documentation
virtual void G4BinaryPionBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPionBuilder.
Definition at line 58 of file G4BinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BinaryPionBuilder.hh
void G4BinaryPionBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 58 of file G4BinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 58 of file G4BinaryPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4BinaryPionBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 67 of file G4BinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 67 of file G4BinaryPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4BinaryPionBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 63 of file G4BinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4BinaryPionBuilder.hh
References theMax.
void G4BinaryPionBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 62 of file G4BinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BinaryPionBuilder.hh
References theMin.
Member Data Documentation
G4double G4BinaryPionBuilder::theMax private
Definition at line 69 of file G4BinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BinaryPionBuilder.hh
Referenced by Build(), G4BinaryPionBuilder(), and SetMaxEnergy().
G4double G4BinaryPionBuilder::theMin private
Definition at line 68 of file G4BinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4BinaryPionBuilder.hh
Referenced by Build(), G4BinaryPionBuilder(), and SetMinEnergy().
G4BinaryCascade* G4BinaryPionBuilder::theModel private
Definition at line 67 of file G4BinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4BinaryPionBuilder.hh
Referenced by Build(), and G4BinaryPionBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BinaryPionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4BinaryPionBuilder.cc