ECCE @ EIC Software: RE06ParallelWorld Class Reference
RE06ParallelWorld Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/include/RE06ParallelWorld.hh>
Public Member Functions
RE06ParallelWorld (G4String worldName)
virtual ~RE06ParallelWorld ()
virtual void Construct ()
virtual void ConstructSD ()
void SetSerialGeometry (G4bool ser)
G4bool IsSerial () const
Public Member Functions inherited from G4VUserParallelWorld
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
G4String GetName ()
Private Member Functions
void SetupGeometry ()
void SetupDetectors ()
Private Attributes
G4LogicalVolume * fCalorLogical [3]
G4LogicalVolume * fLayerLogical [3]
G4VPhysicalVolume * fCalorPhysical [3]
G4VPhysicalVolume * fLayerPhysical [3]
G4String fCalName [3]
G4bool fConstructed
G4bool fSerial
G4double fTotalThickness
G4int fNumberOfLayers
Static Private Attributes
static G4ThreadLocal G4bool fSDConstructed = false
Additional Inherited Members
Protected Member Functions inherited from G4VUserParallelWorld
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes inherited from G4VUserParallelWorld
G4String fWorldName
Detailed Description
Definition at line 40 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 40 of file RE06ParallelWorld.hh
Constructor & Destructor Documentation
RE06ParallelWorld::RE06ParallelWorld (G4String worldName)
Definition at line 55 of file RE06ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 55 of file RE06ParallelWorld.cc
References fCalName, fCalorLogical, fCalorPhysical, fLayerLogical, and fLayerPhysical.
RE06ParallelWorld::~RE06ParallelWorld () virtual
Definition at line 76 of file RE06ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 76 of file RE06ParallelWorld.cc
Member Function Documentation
void RE06ParallelWorld::Construct (void) virtual
Implements G4VUserParallelWorld.
Definition at line 81 of file RE06ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 81 of file RE06ParallelWorld.cc
References fConstructed, and SetupGeometry().
void RE06ParallelWorld::ConstructSD () virtual
Reimplemented from G4VUserParallelWorld.
Definition at line 92 of file RE06ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 92 of file RE06ParallelWorld.cc
References fSDConstructed, and SetupDetectors().
G4bool RE06ParallelWorld::IsSerial () const inline
Definition at line 50 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 50 of file RE06ParallelWorld.hh
References fSerial.
void RE06ParallelWorld::SetSerialGeometry (G4bool ser)
Definition at line 200 of file RE06ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 200 of file RE06ParallelWorld.cc
References fCalorPhysical, fConstructed, fSerial, m, and G4VPhysicalVolume::SetTranslation().
void RE06ParallelWorld::SetupDetectors () private
Definition at line 151 of file RE06ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 151 of file RE06ParallelWorld.cc
References G4SDParticleFilter::add(), G4SDManager::AddNewDetector(), fCalName, fLayerLogical, G4SDManager::GetSDMpointer(), G4MultiFunctionalDetector::RegisterPrimitive(), G4VPrimitiveScorer::SetFilter(), G4VUserParallelWorld::SetSensitiveDetector(), and G4SDManager::SetVerboseLevel().
Referenced by ConstructSD().
void RE06ParallelWorld::SetupGeometry () private
Definition at line 102 of file RE06ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 102 of file RE06ParallelWorld.cc
References deg, fCalName, fCalorLogical, fCalorPhysical, fLayerLogical, fLayerPhysical, fNumberOfLayers, fSerial, fTotalThickness, G4VPhysicalVolume::GetLogicalVolume(), G4VUserParallelWorld::GetWorld(), kRho, and m.
Referenced by Construct().
Member Data Documentation
G4String RE06ParallelWorld::fCalName[3] private
Definition at line 60 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 60 of file RE06ParallelWorld.hh
Referenced by RE06ParallelWorld(), SetupDetectors(), and SetupGeometry().
G4LogicalVolume* RE06ParallelWorld::fCalorLogical[3] private
Definition at line 56 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 56 of file RE06ParallelWorld.hh
Referenced by RE06ParallelWorld(), and SetupGeometry().
G4VPhysicalVolume* RE06ParallelWorld::fCalorPhysical[3] private
Definition at line 58 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 58 of file RE06ParallelWorld.hh
Referenced by RE06ParallelWorld(), SetSerialGeometry(), and SetupGeometry().
G4bool RE06ParallelWorld::fConstructed private
Definition at line 61 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 61 of file RE06ParallelWorld.hh
Referenced by Construct(), and SetSerialGeometry().
G4LogicalVolume* RE06ParallelWorld::fLayerLogical[3] private
Definition at line 57 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 57 of file RE06ParallelWorld.hh
Referenced by RE06ParallelWorld(), SetupDetectors(), and SetupGeometry().
G4VPhysicalVolume* RE06ParallelWorld::fLayerPhysical[3] private
Definition at line 59 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 59 of file RE06ParallelWorld.hh
Referenced by RE06ParallelWorld(), and SetupGeometry().
G4int RE06ParallelWorld::fNumberOfLayers private
Definition at line 65 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 65 of file RE06ParallelWorld.hh
Referenced by SetupGeometry().
G4ThreadLocal G4bool RE06ParallelWorld::fSDConstructed = false static private
Definition at line 62 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 62 of file RE06ParallelWorld.hh
Referenced by ConstructSD().
G4bool RE06ParallelWorld::fSerial private
Definition at line 63 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 63 of file RE06ParallelWorld.hh
Referenced by IsSerial(), SetSerialGeometry(), and SetupGeometry().
G4double RE06ParallelWorld::fTotalThickness private
Definition at line 64 of file RE06ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 64 of file RE06ParallelWorld.hh
Referenced by SetupGeometry().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/include/RE06ParallelWorld.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/src/RE06ParallelWorld.cc