ECCE @ EIC Software: G4VPrimaryGenerator Class Reference
G4VPrimaryGenerator Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/event/include/G4VPrimaryGenerator.hh>
Public Member Functions
G4VPrimaryGenerator ()
virtual ~G4VPrimaryGenerator ()
virtual void GeneratePrimaryVertex (G4Event *evt)=0
G4ThreeVector GetParticlePosition ()
G4double GetParticleTime ()
void SetParticlePosition (G4ThreeVector aPosition)
void SetParticleTime (G4double aTime)
Static Public Member Functions
static G4bool CheckVertexInsideWorld (const G4ThreeVector &pos)
Protected Attributes
G4ThreeVector particle_position
G4double particle_time
Detailed Description
Definition at line 44 of file G4VPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VPrimaryGenerator.hh
Constructor & Destructor Documentation
G4VPrimaryGenerator::G4VPrimaryGenerator ()
Definition at line 32 of file G4VPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 32 of file G4VPrimaryGenerator.cc
G4VPrimaryGenerator::~G4VPrimaryGenerator () virtual
Definition at line 35 of file G4VPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 35 of file G4VPrimaryGenerator.cc
Member Function Documentation
G4bool G4VPrimaryGenerator::CheckVertexInsideWorld (const G4ThreeVector & pos) static
Definition at line 44 of file G4VPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VPrimaryGenerator.cc
References G4TransportationManager::GetTransportationManager(), kInside, Acts::Test::navigator, and Acts::Test::world.
virtual void G4VPrimaryGenerator::GeneratePrimaryVertex (G4Event * evt) pure virtual
Implemented in G4GeneralParticleSource, G4SingleParticleSource, G4HEPEvtInterface, G4ParticleGun, HepMCG4Interface, HepMCG4Interface, DMXParticleSource, and PrimaryGenerator.
Referenced by RE01PrimaryGeneratorAction::GeneratePrimaries(), and RE05PrimaryGeneratorAction::GeneratePrimaries().
G4ThreeVector G4VPrimaryGenerator::GetParticlePosition () inline
Definition at line 64 of file G4VPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VPrimaryGenerator.hh
References particle_position.
Referenced by export_G4ParticleGun(), RE02PrimaryGeneratorAction::GeneratePrimaries(), G4ParticleGunMessenger::GetCurrentValue(), CCalPrimaryGeneratorAction::GetParticlePosition(), CCalPrimaryGeneratorAction::print(), and EventAction::WriteFibers().
G4double G4VPrimaryGenerator::GetParticleTime () inline
Definition at line 66 of file G4VPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VPrimaryGenerator.hh
References particle_time.
Referenced by export_G4ParticleGun(), and G4ParticleGunMessenger::GetCurrentValue().
void G4VPrimaryGenerator::SetParticlePosition (G4ThreeVector aPosition) inline
Definition at line 68 of file G4VPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPrimaryGenerator.hh
References particle_position.
Referenced by B01PrimaryGeneratorAction::B01PrimaryGeneratorAction(), B02PrimaryGeneratorAction::B02PrimaryGeneratorAction(), B03PrimaryGeneratorAction::B03PrimaryGeneratorAction(), B3PrimaryGeneratorAction::B3PrimaryGeneratorAction(), B5PrimaryGeneratorAction::B5PrimaryGeneratorAction(), CCalPrimaryGeneratorAction::CCalPrimaryGeneratorAction(), ExP02PrimaryGeneratorAction::ExP02PrimaryGeneratorAction(), export_G4ParticleGun(), F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), F02PrimaryGeneratorAction::F02PrimaryGeneratorAction(), F03PrimaryGeneratorAction::F03PrimaryGeneratorAction(), F04PrimaryGeneratorAction::F04PrimaryGeneratorAction(), G01PrimaryGeneratorAction::G01PrimaryGeneratorAction(), G02PrimaryGeneratorAction::G02PrimaryGeneratorAction(), G03PrimaryGeneratorAction::G03PrimaryGeneratorAction(), G04PrimaryGeneratorAction::G04PrimaryGeneratorAction(), G4ParticleGunMessenger::G4ParticleGunMessenger(), GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction(), GB01PrimaryGeneratorAction::GB01PrimaryGeneratorAction(), GB02PrimaryGeneratorAction::GB02PrimaryGeneratorAction(), GB03PrimaryGeneratorAction::GB03PrimaryGeneratorAction(), GB04PrimaryGeneratorAction::GB04PrimaryGeneratorAction(), GB05PrimaryGeneratorAction::GB05PrimaryGeneratorAction(), GB06PrimaryGeneratorAction::GB06PrimaryGeneratorAction(), GB07PrimaryGeneratorAction::GB07PrimaryGeneratorAction(), RE06PrimaryGeneratorAction::GeneratePrimaries(), ExTGPrimaryGeneratorAction::GeneratePrimaries(), eRositaPrimaryGeneratorAction::GeneratePrimaries(), FCALPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction0::GeneratePrimaries(), ExUCNPrimaryGeneratorAction::GeneratePrimaries(), B2PrimaryGeneratorAction::GeneratePrimaries(), B3PrimaryGeneratorAction::GeneratePrimaries(), B4PrimaryGeneratorAction::GeneratePrimaries(), F05PrimaryGeneratorAction::GeneratePrimaries(), F06PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction1::GeneratePrimaries(), ExN02PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction4::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), ExP01PrimaryGeneratorAction::GeneratePrimaries(), RE04PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), F04PrimaryGeneratorAction::GeneratePrimaries(), F01PrimaryGeneratorAction::GeneratePrimaries(), F02PrimaryGeneratorAction::GeneratePrimaries(), F03PrimaryGeneratorAction::GeneratePrimaries(), RE02PrimaryGeneratorAction::GeneratePrimaries(), MyPrimaryGeneratorActionFromFile::GeneratePrimaries(), PurgMagPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), CexmcPrimaryGeneratorAction::GeneratePrimaries(), CML2PrimaryGenerationAction::GeneratePrimaries(), GunPrimaryGeneratorAction::GunPrimaryGeneratorAction(), LXePrimaryGeneratorAction::LXePrimaryGeneratorAction(), PrimaryGeneratorAction::Notify(), MyPrimaryGeneratorActionFromFile::Notify(), OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction(), Par01PrimaryGeneratorAction::Par01PrimaryGeneratorAction(), Par02PrimaryGeneratorAction::Par02PrimaryGeneratorAction(), RE01PrimaryGeneratorAction::RE01PrimaryGeneratorAction(), RE02PrimaryGeneratorAction::RE02PrimaryGeneratorAction(), RE03PrimaryGeneratorAction::RE03PrimaryGeneratorAction(), RE04PrimaryGeneratorAction::RE04PrimaryGeneratorAction(), RE05PrimaryGeneratorAction::RE05PrimaryGeneratorAction(), PrimaryGeneratorAction::SetDefaultKinematic(), CCalPrimaryGeneratorAction::SetGunPosition(), G4ParticleGunMessenger::SetNewValue(), XrayFluoMercuryPrimaryGeneratorAction::XrayFluoMercuryPrimaryGeneratorAction(), XrayFluoPlanePrimaryGeneratorAction::XrayFluoPlanePrimaryGeneratorAction(), and XrayFluoPrimaryGeneratorAction::XrayFluoPrimaryGeneratorAction().
void G4VPrimaryGenerator::SetParticleTime (G4double aTime) inline
Definition at line 70 of file G4VPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 70 of file G4VPrimaryGenerator.hh
References particle_time.
Referenced by export_G4ParticleGun(), G4ParticleGunMessenger::G4ParticleGunMessenger(), OpNovicePrimaryGeneratorAction::OpNovicePrimaryGeneratorAction(), and G4ParticleGunMessenger::SetNewValue().
Member Data Documentation
G4ThreeVector G4VPrimaryGenerator::particle_position protected
Definition at line 60 of file G4VPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VPrimaryGenerator.hh
Referenced by G4HEPEvtInterface::G4HEPEvtInterface(), G4ParticleGun::GeneratePrimaryVertex(), G4HEPEvtInterface::GeneratePrimaryVertex(), GetParticlePosition(), G4ParticleGun::SetInitialValues(), and SetParticlePosition().
G4double G4VPrimaryGenerator::particle_time protected
Definition at line 61 of file G4VPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VPrimaryGenerator.hh
Referenced by G4HEPEvtInterface::G4HEPEvtInterface(), G4ParticleGun::GeneratePrimaryVertex(), G4HEPEvtInterface::GeneratePrimaryVertex(), GetParticleTime(), G4ParticleGun::SetInitialValues(), and SetParticleTime().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4VPrimaryGenerator.hh
geant4/tree/geant4-10.6-release/source/event/src/G4VPrimaryGenerator.cc