ECCE @ EIC Software: F05DetectorConstruction Class Reference
F05DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field05/include/F05DetectorConstruction.hh>
Public Member Functions
F05DetectorConstruction ()
virtual ~F05DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
Private Attributes
G4Material * fVacuum
G4double fWorldSizeXY
G4double fWorldSizeZ
G4Box * fSolidWorld
G4LogicalVolume * fLogicWorld
G4VPhysicalVolume * fPhysiWorld
Static Private Attributes
static G4ThreadLocal F05Field * fField = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 50 of file F05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 50 of file F05DetectorConstruction.hh
Constructor & Destructor Documentation
F05DetectorConstruction::F05DetectorConstruction ()
Definition at line 69 of file F05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 69 of file F05DetectorConstruction.cc
References DefineMaterials().
F05DetectorConstruction::~F05DetectorConstruction () virtual
Definition at line 79 of file F05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 79 of file F05DetectorConstruction.cc
References fField.
Member Function Documentation
G4VPhysicalVolume * F05DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 97 of file F05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 97 of file F05DetectorConstruction.cc
References fLogicWorld, fPhysiWorld, fSolidWorld, fVacuum, fWorldSizeXY, fWorldSizeZ, m, mm, and G4LogicalVolume::SetUserLimits().
void F05DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 141 of file F05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 141 of file F05DetectorConstruction.cc
References fField, G4TransportationManager::GetFieldManager(), G4TransportationManager::GetPropagatorInField(), G4TransportationManager::GetTransportationManager(), mm, G4FieldManager::SetAccuraciesWithDeltaOneStep(), G4FieldManager::SetChordFinder(), G4ChordFinder::SetDeltaChord(), G4FieldManager::SetDeltaIntersection(), G4FieldManager::SetDetectorField(), G4PropagatorInField::SetMaximumEpsilonStep(), G4PropagatorInField::SetMinimumEpsilonStep(), and propagation_timing::stepper.
void F05DetectorConstruction::DefineMaterials () private
Definition at line 86 of file F05DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 86 of file F05DetectorConstruction.cc
References G4NistManager::FindOrBuildMaterial(), fVacuum, G4cout, G4endl, G4Material::GetMaterialTable(), and G4NistManager::Instance().
Referenced by F05DetectorConstruction().
Member Data Documentation
G4ThreadLocal F05Field * F05DetectorConstruction::fField = 0 static private
Definition at line 73 of file F05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file F05DetectorConstruction.hh
Referenced by ConstructSDandField(), and ~F05DetectorConstruction().
G4LogicalVolume* F05DetectorConstruction::fLogicWorld private
Definition at line 70 of file F05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 70 of file F05DetectorConstruction.hh
Referenced by Construct().
G4VPhysicalVolume* F05DetectorConstruction::fPhysiWorld private
Definition at line 71 of file F05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 71 of file F05DetectorConstruction.hh
Referenced by Construct().
G4Box* F05DetectorConstruction::fSolidWorld private
Definition at line 69 of file F05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 69 of file F05DetectorConstruction.hh
Referenced by Construct().
G4Material* F05DetectorConstruction::fVacuum private
Definition at line 64 of file F05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 64 of file F05DetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4double F05DetectorConstruction::fWorldSizeXY private
Definition at line 66 of file F05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file F05DetectorConstruction.hh
Referenced by Construct().
G4double F05DetectorConstruction::fWorldSizeZ private
Definition at line 67 of file F05DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file F05DetectorConstruction.hh
Referenced by Construct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field05/include/F05DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field05/src/F05DetectorConstruction.cc