ECCE @ EIC Software: G4ParticleHPInelasticCompFS Class Reference
G4ParticleHPInelasticCompFS Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPInelasticCompFS.hh>
Public Member Functions
G4ParticleHPInelasticCompFS ()
virtual ~G4ParticleHPInelasticCompFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &aSFType, G4ParticleDefinition *)
void InitGammas (G4double AR, G4double ZR)
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &theTrack)=0
virtual G4ParticleHPFinalState * New ()=0
virtual G4double GetXsec (G4double anEnergy)
virtual G4ParticleHPVector * GetXsec ()
G4int SelectExitChannel (G4double eKinetic)
void CompositeApply (const G4HadProjectile &theTrack, G4ParticleDefinition *aHadron)
void InitDistributionInitialState (G4ReactionProduct &anIncidentPart, G4ReactionProduct &aTarget, G4int it)
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Protected Attributes
G4ParticleHPVector * theXsection [51]
G4ParticleHPEnergyDistribution * theEnergyDistribution [51]
G4ParticleHPAngular * theAngularDistribution [51]
G4ParticleHPEnAngCorrelation * theEnergyAngData [51]
G4ParticleHPPhotonDist * theFinalStatePhotons [51]
G4ParticleHPDeExGammas theGammas
G4String gammaPath
std::vector< G4double > QI
std::vector< G4int > LR
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Private Member Functions
void two_body_reaction (G4ReactionProduct *proj, G4ReactionProduct *targ, G4ReactionProduct *product, G4double resExcitationEnergy)
G4bool use_nresp71_model (const G4ParticleDefinition *aDefinition, const G4int it, const G4ReactionProduct &theTarget, G4ReactionProduct &boosted)
Private Attributes
G4NRESP71M03 nresp71_model
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Detailed Description
Definition at line 50 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPInelasticCompFS.hh
Constructor & Destructor Documentation
G4ParticleHPInelasticCompFS::G4ParticleHPInelasticCompFS () inline
Definition at line 54 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPInelasticCompFS.hh
References G4ParticleHPFinalState::hasXsec, LR, QI, theAngularDistribution, theEnergyAngData, theEnergyDistribution, theFinalStatePhotons, and theXsection.
virtual G4ParticleHPInelasticCompFS::~G4ParticleHPInelasticCompFS () inline virtual
Definition at line 70 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPInelasticCompFS.hh
References theAngularDistribution, theEnergyAngData, theEnergyDistribution, theFinalStatePhotons, and theXsection.
Member Function Documentation
virtual G4HadFinalState* G4ParticleHPInelasticCompFS::ApplyYourself (const G4HadProjectile & theTrack) pure virtual
Reimplemented from G4ParticleHPFinalState.
Implemented in G4ParticleHPAInelasticFS, G4ParticleHPDInelasticFS, G4ParticleHPHe3InelasticFS, G4ParticleHPNInelasticFS, G4ParticleHPPInelasticFS, and G4ParticleHPTInelasticFS.
void G4ParticleHPInelasticCompFS::CompositeApply (const G4HadProjectile & theTrack, G4ParticleDefinition * aHadron)
Definition at line 235 of file G4ParticleHPInelasticCompFS.cc.
View newest version in sPHENIX GitHub at line 235 of file G4ParticleHPInelasticCompFS.cc
References kdfinder::abs(), G4HadFinalState::AddSecondary(), G4ParticleHPFinalState::adjust_final_state(), G4HadFinalState::Clear(), G4Neutron::Definition(), eps, G4cout, G4endl, G4UniformRand, G4Gamma::Gamma(), G4Cache< VALTYPE >::Get(), G4HadProjectile::Get4Momentum(), G4ParticleDefinition::GetBaryonNumber(), G4Nucleus::GetBiasedThermalNucleus(), G4ParticleHPDeExGammas::GetDecayGammas(), G4HadProjectile::GetDefinition(), G4ReactionProduct::GetDefinition(), G4ParticleHPManager::GetInstance(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4ReactionProduct::GetKineticEnergy(), G4DynamicParticle::GetKineticEnergy(), G4ParticleHPDeExGammas::GetLevel(), G4ParticleHPLevel::GetLevelEnergy(), G4ParticleHPDeExGammas::GetLevelEnergy(), G4ParticleHPPhotonDist::GetLevelEnergy(), G4ReactionProduct::GetMass(), G4HadProjectile::GetMaterial(), G4ReactionProduct::GetMomentum(), G4NucleiProperties::GetNuclearMass(), G4ParticleHPDeExGammas::GetNumberOfLevels(), G4HadFinalState::GetNumberOfSecondaries(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ParticleHPPhotonDist::GetPhotons(), G4Material::GetTemperature(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), InitDistributionInitialState(), it, CLHEP::keV, keV, G4ReactionProduct::Lorentz(), CLHEP::Hep3Vector::mag2(), maxA, MeV, G4Neutron::Neutron(), phi, G4Cache< VALTYPE >::Put(), QI, G4ParticleHPEnergyDistribution::Sample(), G4ParticleHPEnAngCorrelation::Sample(), G4ParticleHPAngular::SampleAndUpdate(), SelectExitChannel(), G4ReactionProduct::SetDefinition(), G4DynamicParticle::SetDefinition(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), G4DynamicParticle::SetMomentum(), G4HadFinalState::SetStatusChange(), stopAndKill, theAngularDistribution, G4ParticleHPFinalState::theBaseA, G4ParticleHPFinalState::theBaseZ, theEnergyAngData, theEnergyDistribution, theFinalStatePhotons, theGammas, G4ParticleHPFinalState::theProjectile, G4ParticleHPFinalState::theResult, theTarget, theXsection, two_body_reaction(), CLHEP::twopi, use_nresp71_model(), and CLHEP::HepLorentzVector::vect().
Referenced by G4ParticleHPDInelasticFS::ApplyYourself(), G4ParticleHPTInelasticFS::ApplyYourself(), G4ParticleHPPInelasticFS::ApplyYourself(), G4ParticleHPNInelasticFS::ApplyYourself(), G4ParticleHPHe3InelasticFS::ApplyYourself(), and G4ParticleHPAInelasticFS::ApplyYourself().
virtual G4double G4ParticleHPInelasticCompFS::GetXsec (G4double anEnergy) inline virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 90 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ParticleHPInelasticCompFS.hh
References max, and theXsection.
virtual G4ParticleHPVector* G4ParticleHPInelasticCompFS::GetXsec () inline virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 95 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPInelasticCompFS.hh
References theXsection.
Referenced by SelectExitChannel().
void G4ParticleHPInelasticCompFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & aSFType, G4ParticleDefinition *) virtual
Implements G4ParticleHPFinalState.
Reimplemented in G4ParticleHPNInelasticFS, G4ParticleHPPInelasticFS, and G4ParticleHPTInelasticFS.
Definition at line 86 of file G4ParticleHPInelasticCompFS.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPInelasticCompFS.cc
References kdfinder::abs(), CLHEP::eV, INPUTHEPMC::filename, G4cout, G4endl, gammaPath, G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPFinalState::hasAnyData, G4ParticleHPFinalState::hasFSData, G4ParticleHPFinalState::hasXsec, in, G4ParticleHPEnergyDistribution::Init(), G4ParticleHPAngular::Init(), G4ParticleHPEnAngCorrelation::Init(), G4ParticleHPVector::Init(), G4ParticleHPPhotonDist::InitAngular(), G4ParticleHPPhotonDist::InitEnergies(), G4ParticleHPPhotonDist::InitMean(), G4ParticleHPPhotonDist::InitPartials(), it, LR, QI, G4ParticleHPFinalState::SetAZMs(), theAngularDistribution, theEnergyAngData, theEnergyDistribution, theFinalStatePhotons, G4ParticleHPFinalState::theNames, G4ParticleHPFinalState::theNDLDataA, G4ParticleHPFinalState::theNDLDataZ, G4ParticleHPFinalState::theProjectile, theXsection, and G4INCL::CrossSections::total().
Referenced by G4ParticleHPDInelasticFS::Init(), G4ParticleHPTInelasticFS::Init(), G4ParticleHPPInelasticFS::Init(), G4ParticleHPNInelasticFS::Init(), G4ParticleHPHe3InelasticFS::Init(), and G4ParticleHPAInelasticFS::Init().
void G4ParticleHPInelasticCompFS::InitDistributionInitialState (G4ReactionProduct & anIncidentPart, G4ReactionProduct & aTarget, G4int it) inline
Definition at line 102 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ParticleHPInelasticCompFS.hh
References it, G4ParticleHPAngular::SetProjectileRP(), G4ParticleHPEnAngCorrelation::SetProjectileRP(), G4ParticleHPAngular::SetTarget(), G4ParticleHPEnAngCorrelation::SetTarget(), theAngularDistribution, and theEnergyAngData.
Referenced by CompositeApply().
void G4ParticleHPInelasticCompFS::InitGammas (G4double AR, G4double ZR)
Definition at line 64 of file G4ParticleHPInelasticCompFS.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleHPInelasticCompFS.cc
References gammaPath, in, G4ParticleHPDeExGammas::Init(), and theGammas.
Referenced by G4ParticleHPDInelasticFS::Init(), G4ParticleHPTInelasticFS::Init(), G4ParticleHPPInelasticFS::Init(), G4ParticleHPNInelasticFS::Init(), G4ParticleHPHe3InelasticFS::Init(), and G4ParticleHPAInelasticFS::Init().
virtual G4ParticleHPFinalState* G4ParticleHPInelasticCompFS::New () pure virtual
Implements G4ParticleHPFinalState.
Implemented in G4ParticleHPAInelasticFS, G4ParticleHPDInelasticFS, G4ParticleHPHe3InelasticFS, G4ParticleHPNInelasticFS, G4ParticleHPPInelasticFS, and G4ParticleHPTInelasticFS.
G4int G4ParticleHPInelasticCompFS::SelectExitChannel (G4double eKinetic)
Definition at line 200 of file G4ParticleHPInelasticCompFS.cc.
View newest version in sPHENIX GitHub at line 200 of file G4ParticleHPInelasticCompFS.cc
References G4UniformRand, GetXsec(), it, max, sum, and theXsection.
Referenced by CompositeApply().
void G4ParticleHPInelasticCompFS::two_body_reaction (G4ReactionProduct * proj, G4ReactionProduct * targ, G4ReactionProduct * product, G4double resExcitationEnergy) private
Definition at line 811 of file G4ParticleHPInelasticCompFS.cc.
View newest version in sPHENIX GitHub at line 811 of file G4ParticleHPInelasticCompFS.cc
References G4UniformRand, G4ParticleDefinition::GetBaryonNumber(), G4ReactionProduct::GetDefinition(), G4IonTable::GetIonTable(), G4ReactionProduct::GetMass(), G4ParticleDefinition::GetPDGCharge(), G4ReactionProduct::GetTotalMomentum(), G4ReactionProduct::Lorentz(), phi, G4ReactionProduct::SetDefinition(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), targ, theta(), and CLHEP::twopi.
Referenced by CompositeApply().
G4bool G4ParticleHPInelasticCompFS::use_nresp71_model (const G4ParticleDefinition * aDefinition, const G4int it, const G4ReactionProduct & theTarget, G4ReactionProduct & boosted) private
Definition at line 853 of file G4ParticleHPInelasticCompFS.cc.
View newest version in sPHENIX GitHub at line 853 of file G4ParticleHPInelasticCompFS.cc
References G4HadFinalState::AddSecondary(), G4NRESP71M03::ApplyMechanismABE(), G4NRESP71M03::ApplyMechanismI_NBeA2A(), G4NRESP71M03::ApplyMechanismII_ACN2A(), G4Neutron::Definition(), G4Alpha::Definition(), FatalException, G4Exception(), G4Cache< VALTYPE >::Get(), G4ReactionProduct::Lorentz(), LR, nresp71_model, QI, G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), G4HadFinalState::SetStatusChange(), stopAndKill, and G4ParticleHPFinalState::theResult.
Referenced by CompositeApply().
Member Data Documentation
G4String G4ParticleHPInelasticCompFS::gammaPath protected
Definition at line 127 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ParticleHPInelasticCompFS.hh
Referenced by Init(), and InitGammas().
std::vector<G4int> G4ParticleHPInelasticCompFS::LR protected
Definition at line 131 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ParticleHPInelasticCompFS.hh
Referenced by G4ParticleHPInelasticCompFS(), Init(), and use_nresp71_model().
G4NRESP71M03 G4ParticleHPInelasticCompFS::nresp71_model private
Definition at line 138 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ParticleHPInelasticCompFS.hh
Referenced by use_nresp71_model().
std::vector<G4double> G4ParticleHPInelasticCompFS::QI protected
Definition at line 130 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ParticleHPInelasticCompFS.hh
Referenced by CompositeApply(), G4ParticleHPInelasticCompFS(), Init(), and use_nresp71_model().
G4ParticleHPAngular* G4ParticleHPInelasticCompFS::theAngularDistribution[51] protected
Definition at line 121 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ParticleHPInelasticCompFS.hh
Referenced by CompositeApply(), G4ParticleHPInelasticCompFS(), Init(), InitDistributionInitialState(), and ~G4ParticleHPInelasticCompFS().
G4ParticleHPEnAngCorrelation* G4ParticleHPInelasticCompFS::theEnergyAngData[51] protected
Definition at line 122 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ParticleHPInelasticCompFS.hh
Referenced by CompositeApply(), G4ParticleHPInelasticCompFS(), Init(), InitDistributionInitialState(), and ~G4ParticleHPInelasticCompFS().
G4ParticleHPEnergyDistribution* G4ParticleHPInelasticCompFS::theEnergyDistribution[51] protected
Definition at line 120 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ParticleHPInelasticCompFS.hh
Referenced by CompositeApply(), G4ParticleHPInelasticCompFS(), Init(), and ~G4ParticleHPInelasticCompFS().
G4ParticleHPPhotonDist* G4ParticleHPInelasticCompFS::theFinalStatePhotons[51] protected
Definition at line 124 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ParticleHPInelasticCompFS.hh
Referenced by CompositeApply(), G4ParticleHPInelasticCompFS(), Init(), and ~G4ParticleHPInelasticCompFS().
G4ParticleHPDeExGammas G4ParticleHPInelasticCompFS::theGammas protected
Definition at line 126 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleHPInelasticCompFS.hh
Referenced by CompositeApply(), and InitGammas().
G4ParticleHPVector* G4ParticleHPInelasticCompFS::theXsection[51] protected
Definition at line 119 of file G4ParticleHPInelasticCompFS.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ParticleHPInelasticCompFS.hh
Referenced by CompositeApply(), G4ParticleHPInelasticCompFS(), GetXsec(), Init(), SelectExitChannel(), and ~G4ParticleHPInelasticCompFS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPInelasticCompFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPInelasticCompFS.cc