ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/materials/pymodG4materials.cc File Reference
pymodG4materials.cc File Reference
#include <boost/python.hpp>
Functions
void export_G4Material ()
void export_G4MaterialTable ()
void export_G4Element ()
void export_G4ElementTable ()
void export_G4Isotope ()
void export_G4NistManager ()
void export_G4AtomicShells ()
BOOST_PYTHON_MODULE (G4materials)
Function Documentation
BOOST_PYTHON_MODULE (G4materials)
Definition at line 47 of file pymodG4materials.cc.
View newest version in sPHENIX GitHub at line 47 of file pymodG4materials.cc
References export_G4AtomicShells(), export_G4Element(), export_G4ElementTable(), export_G4Isotope(), export_G4Material(), export_G4MaterialTable(), and export_G4NistManager().
void export_G4AtomicShells ()
Definition at line 39 of file pyG4AtomicShells.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4AtomicShells.cc
References G4AtomicShells::GetBindingEnergy(), G4AtomicShells::GetNumberOfElectrons(), G4AtomicShells::GetNumberOfShells(), and G4AtomicShells::GetTotalBindingEnergy().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Element ()
Definition at line 67 of file pyG4Element.cc.
View newest version in sPHENIX GitHub at line 67 of file pyG4Element.cc
References G4Element::AddIsotope(), pyG4Element::f_GetRelativeAbundanceVector(), G4Element::GetA(), G4Element::GetAtomicShell(), G4Element::GetElement(), G4Element::GetElementTable(), G4Element::GetfCoulomb(), G4Element::GetfRadTsai(), G4Element::GetIndex(), G4Element::GetIonisation(), G4Element::GetIsotope(), G4Element::GetIsotopeVector(), G4Element::GetN(), G4Element::GetName(), G4Element::GetNbOfAtomicShells(), G4Element::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4Element::GetSymbol(), G4Element::GetZ(), pyG4Element::Print(), and G4Element::SetName().
Referenced by BOOST_PYTHON_MODULE().
void export_G4ElementTable ()
Definition at line 41 of file pyG4ElementTable.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4ElementTable.cc
Referenced by BOOST_PYTHON_MODULE().
void export_G4Isotope ()
Definition at line 58 of file pyG4Isotope.cc.
View newest version in sPHENIX GitHub at line 58 of file pyG4Isotope.cc
References G4Isotope::GetA(), G4Isotope::GetIndex(), G4Isotope::GetIsotope(), G4Isotope::GetIsotopeTable(), G4Isotope::GetN(), G4Isotope::GetName(), G4Isotope::GetNumberOfIsotopes(), G4Isotope::GetZ(), pyG4Element::Print(), and G4Isotope::SetName().
Referenced by BOOST_PYTHON_MODULE().
void export_G4Material ()
Definition at line 115 of file pyG4Material.cc.
View newest version in sPHENIX GitHub at line 115 of file pyG4Material.cc
References G4Material::AddMaterial(), pyG4Material::f1_AddElement, pyG4Material::f1_GetMaterial, pyG4Material::f2_AddElement, pyG4Material::f2_GetMaterial, pyG4Material::f3_GetMaterial, pyG4Material::f_GetAtomicNumDensityVector(), pyG4Material::f_GetAtomsVector(), pyG4Material::f_GetFractionVector(), pyG4Material::f_GetVecNbOfAtomsPerVolume(), G4Material::GetA(), G4Material::GetChemicalFormula(), G4Material::GetDensity(), G4Material::GetElectronDensity(), G4Material::GetElement(), G4Material::GetElementVector(), G4Material::GetIndex(), G4Material::GetIonisation(), G4Material::GetMaterialPropertiesTable(), G4Material::GetMaterialTable(), G4Material::GetName(), G4Material::GetNuclearInterLength(), G4Material::GetNumberOfMaterials(), G4Material::GetPressure(), G4Material::GetRadlen(), G4Material::GetSandiaTable(), G4Material::GetState(), G4Material::GetTemperature(), G4Material::GetTotNbOfAtomsPerVolume(), G4Material::GetTotNbOfElectPerVolume(), G4Material::GetZ(), kStateGas, kStateLiquid, kStateSolid, kStateUndefined, pyG4Element::Print(), G4Material::SetChemicalFormula(), G4Material::SetMaterialPropertiesTable(), and G4Material::SetName().
Referenced by BOOST_PYTHON_MODULE().
void export_G4MaterialTable ()
Definition at line 41 of file pyG4MaterialTable.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4MaterialTable.cc
Referenced by BOOST_PYTHON_MODULE().
void export_G4NistManager ()
Definition at line 91 of file pyG4NistManager.cc.
View newest version in sPHENIX GitHub at line 91 of file pyG4NistManager.cc
References G4NistManager::ConstructNewGasMaterial(), G4NistManager::FindOrBuildMaterial(), G4NistManager::GetElement(), G4NistManager::GetIsotopeMass(), G4NistManager::GetMaterial(), G4NistManager::GetNumberOfElements(), G4NistManager::GetNumberOfMaterials(), G4NistManager::GetVerbose(), G4NistManager::GetZ(), G4NistManager::Instance(), G4NistManager::ListMaterials(), G4NistManager::PrintG4Element(), G4NistManager::PrintG4Material(), and G4NistManager::SetVerbose().
Referenced by BOOST_PYTHON_MODULE().