ECCE @ EIC Software: G4IonChuFluctuationModel Class Reference
G4IonChuFluctuationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4IonChuFluctuationModel.hh>
Public Member Functions
G4IonChuFluctuationModel (const G4String &name)
~G4IonChuFluctuationModel ()
G4double TheValue (const G4DynamicParticle *particle, const G4Material *material)
G4double TheValue (const G4ParticleDefinition *aParticle, const G4Material *material, G4double kineticEnergy)
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle) const
G4bool IsInCharge (const G4DynamicParticle *particle, const G4Material *material) const
G4bool IsInCharge (const G4ParticleDefinition *aParticle, const G4Material *material) const
Public Member Functions inherited from G4VLowEnergyModel
G4VLowEnergyModel (const G4String &name)
virtual ~G4VLowEnergyModel ()
Private Member Functions
G4double ChuFluctuationModel (const G4Material *material, G4double kineticEnergy, G4double particleMass) const
Detailed Description
Definition at line 58 of file G4IonChuFluctuationModel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4IonChuFluctuationModel.hh
Constructor & Destructor Documentation
G4IonChuFluctuationModel::G4IonChuFluctuationModel (const G4String & name)
Definition at line 70 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 70 of file G4IonChuFluctuationModel.cc
G4IonChuFluctuationModel::~G4IonChuFluctuationModel ()
Definition at line 76 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 76 of file G4IonChuFluctuationModel.cc
Member Function Documentation
G4double G4IonChuFluctuationModel::ChuFluctuationModel (const G4Material * material, G4double kineticEnergy, G4double particleMass) const private
Definition at line 154 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 154 of file G4IonChuFluctuationModel.cc
References a, source.hepunit::amu_c2, energy, G4Material::GetElectronDensity(), G4Material::GetTotNbOfAtomsPerVolume(), and MeV.
Referenced by TheValue().
G4double G4IonChuFluctuationModel::HighEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 108 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 108 of file G4IonChuFluctuationModel.cc
References TeV.
G4double G4IonChuFluctuationModel::HighEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 124 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 124 of file G4IonChuFluctuationModel.cc
References TeV.
G4bool G4IonChuFluctuationModel::IsInCharge (const G4DynamicParticle * particle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 138 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 138 of file G4IonChuFluctuationModel.cc
References true.
G4bool G4IonChuFluctuationModel::IsInCharge (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 146 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 146 of file G4IonChuFluctuationModel.cc
References true.
G4double G4IonChuFluctuationModel::LowEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 116 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 116 of file G4IonChuFluctuationModel.cc
G4double G4IonChuFluctuationModel::LowEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 131 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 131 of file G4IonChuFluctuationModel.cc
G4double G4IonChuFluctuationModel::TheValue (const G4DynamicParticle * particle, const G4Material * material) virtual
Implements G4VLowEnergyModel.
Definition at line 81 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 81 of file G4IonChuFluctuationModel.cc
References ChuFluctuationModel(), energy, G4DynamicParticle::GetKineticEnergy(), and G4DynamicParticle::GetMass().
G4double G4IonChuFluctuationModel::TheValue (const G4ParticleDefinition * aParticle, const G4Material * material, G4double kineticEnergy) virtual
Implements G4VLowEnergyModel.
Definition at line 94 of file G4IonChuFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 94 of file G4IonChuFluctuationModel.cc
References ChuFluctuationModel(), and G4ParticleDefinition::GetPDGMass().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4IonChuFluctuationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4IonChuFluctuationModel.cc