ECCE @ EIC Software: G4RDVRangeTest Class Reference
G4RDVRangeTest Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDVRangeTest.hh>
Public Member Functions
G4RDVRangeTest ()
virtual ~G4RDVRangeTest ()
virtual G4bool Escape (const G4ParticleDefinition *particle, const G4MaterialCutsCouple *couple, G4double energy, G4double safety) const =0
Detailed Description
Definition at line 50 of file G4RDVRangeTest.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RDVRangeTest.hh
Constructor & Destructor Documentation
G4RDVRangeTest::G4RDVRangeTest () inline
Definition at line 54 of file G4RDVRangeTest.hh.
View newest version in sPHENIX GitHub at line 54 of file G4RDVRangeTest.hh
virtual G4RDVRangeTest::~G4RDVRangeTest () inline virtual
Definition at line 56 of file G4RDVRangeTest.hh.
View newest version in sPHENIX GitHub at line 56 of file G4RDVRangeTest.hh
Member Function Documentation
virtual G4bool G4RDVRangeTest::Escape (const G4ParticleDefinition * particle, const G4MaterialCutsCouple * couple, G4double energy, G4double safety) const pure virtual
Implemented in G4RDRangeNoTest, and G4RDRangeTest.
Referenced by G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), and G4LowEnergyPolarizedCompton::PostStepDoIt().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDVRangeTest.hh