ECCE @ EIC Software: G4EmSaturation Class Reference
G4EmSaturation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmSaturation.hh>
Public Member Functions
G4EmSaturation (G4int verb)
virtual ~G4EmSaturation ()
virtual G4double VisibleEnergyDeposition (const G4ParticleDefinition *, const G4MaterialCutsCouple *, G4double length, G4double edepTotal, G4double edepNIEL=0.0) const
void InitialiseG4Saturation ()
G4double FindG4BirksCoefficient (const G4Material *)
void DumpBirksCoefficients ()
void DumpG4BirksCoefficients ()
G4double VisibleEnergyDepositionAtAStep (const G4Step *) const
void SetVerbose (G4int)
Private Member Functions
G4EmSaturation & operator= (const G4EmSaturation &right)=delete
G4EmSaturation (const G4EmSaturation &)=delete
void InitialiseBirksCoefficient (const G4Material *)
void InitialiseG4materials ()
Private Attributes
const G4ParticleDefinition * electron
const G4ParticleDefinition * proton
G4NistManager * nist
G4int verbose
G4int nG4Birks
G4int nWarnings
Static Private Attributes
static G4int nMaterials = 0
static std::vector< G4double > massFactors
static std::vector< G4double > effCharges
static std::vector< G4double > g4MatData
static std::vector< G4String > g4MatNames
Detailed Description
Definition at line 70 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 70 of file G4EmSaturation.hh
Constructor & Destructor Documentation
G4EmSaturation::G4EmSaturation (G4int verb) explicit
Definition at line 62 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 62 of file G4EmSaturation.cc
References electron, G4NistManager::Instance(), nG4Birks, nist, nWarnings, proton, and verbose.
G4EmSaturation::~G4EmSaturation () virtual
Definition at line 75 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 75 of file G4EmSaturation.cc
G4EmSaturation::G4EmSaturation (const G4EmSaturation &) private delete
Member Function Documentation
void G4EmSaturation::DumpBirksCoefficients ()
Definition at line 236 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 236 of file G4EmSaturation.cc
References cm2, effCharges, Acts::UnitConstants::g, G4cout, G4endl, G4IonisParamMat::GetBirksConstant(), G4Material::GetDensity(), G4Material::GetIonisation(), G4Material::GetMaterialTable(), G4Material::GetName(), massFactors, mat, MeV, mm, and nMaterials.
Referenced by InitialiseG4Saturation().
void G4EmSaturation::DumpG4BirksCoefficients ()
Definition at line 255 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 255 of file G4EmSaturation.cc
References G4cout, G4endl, g4MatData, g4MatNames, MeV, mm, and nG4Birks.
G4double G4EmSaturation::FindG4BirksCoefficient (const G4Material * mat)
Definition at line 159 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 159 of file G4EmSaturation.cc
References G4cout, G4endl, g4MatData, g4MatNames, G4Material::GetName(), InitialiseG4materials(), MeV, mm, nG4Birks, and verbose.
void G4EmSaturation::InitialiseBirksCoefficient (const G4Material * mat) private
Definition at line 180 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 180 of file G4EmSaturation.cc
References effCharges, electron, FatalException, G4ParticleTable::FindParticle(), G4Exception(), g4MatData, g4MatNames, G4NistManager::GetAtomicMassAmu(), G4IonisParamMat::GetBirksConstant(), G4Material::GetElementVector(), G4Material::GetIndex(), G4Material::GetIonisation(), G4Material::GetName(), G4Material::GetNumberOfElements(), G4ParticleTable::GetParticleTable(), G4Material::GetVecNbOfAtomsPerVolume(), G4Element::GetZ(), incremental_prev_tag::idx, massFactors, nG4Birks, nist, norm, proton, source.hepunit::proton_mass_c2, G4IonisParamMat::SetBirksConstant(), w, and Z.
Referenced by InitialiseG4Saturation().
void G4EmSaturation::InitialiseG4materials () private
Definition at line 268 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 268 of file G4EmSaturation.cc
References g4MatData, g4MatNames, MeV, mm, and nG4Birks.
Referenced by FindG4BirksCoefficient(), and InitialiseG4Saturation().
void G4EmSaturation::InitialiseG4Saturation ()
Definition at line 143 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 143 of file G4EmSaturation.cc
References DumpBirksCoefficients(), effCharges, G4Material::GetMaterialTable(), G4Material::GetNumberOfMaterials(), InitialiseBirksCoefficient(), InitialiseG4materials(), massFactors, nG4Birks, nMaterials, and verbose.
Referenced by G4EmParameters::SetBirksActive().
G4EmSaturation& G4EmSaturation::operator= (const G4EmSaturation & right) private delete
void G4EmSaturation::SetVerbose (G4int val) inline
Definition at line 133 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 133 of file G4EmSaturation.hh
References verbose.
Referenced by PHG4SteppingAction::GetVisibleEnergyDeposition().
G4double G4EmSaturation::VisibleEnergyDeposition (const G4ParticleDefinition * p, const G4MaterialCutsCouple * couple, G4double length, G4double edepTotal, G4double edepNIEL = 0.0) const virtual
Definition at line 80 of file G4EmSaturation.cc.
View newest version in sPHENIX GitHub at line 80 of file G4EmSaturation.cc
References edep, effCharges, electron, G4IonisParamMat::GetBirksConstant(), G4Material::GetIndex(), G4Material::GetIonisation(), G4MaterialCutsCouple::GetMaterial(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4LossTableManager::GetRange(), incremental_prev_tag::idx, G4LossTableManager::Instance(), BTOF::length, massFactors, max, and proton.
Referenced by VisibleEnergyDepositionAtAStep().
G4double G4EmSaturation::VisibleEnergyDepositionAtAStep (const G4Step * step) const inline
Definition at line 140 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 140 of file G4EmSaturation.hh
References G4Track::GetMaterialCutsCouple(), G4Step::GetNonIonizingEnergyDeposit(), G4Track::GetParticleDefinition(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), and VisibleEnergyDeposition().
Referenced by PHG4SteppingAction::GetVisibleEnergyDeposition(), and G4Scintillation::PostStepDoIt().
Member Data Documentation
std::vector< G4double > G4EmSaturation::effCharges static private
Definition at line 124 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 124 of file G4EmSaturation.hh
Referenced by DumpBirksCoefficients(), InitialiseBirksCoefficient(), InitialiseG4Saturation(), and VisibleEnergyDeposition().
const G4ParticleDefinition* G4EmSaturation::electron private
Definition at line 112 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 112 of file G4EmSaturation.hh
Referenced by G4EmSaturation(), InitialiseBirksCoefficient(), and VisibleEnergyDeposition().
std::vector< G4double > G4EmSaturation::g4MatData static private
Definition at line 127 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 127 of file G4EmSaturation.hh
Referenced by DumpG4BirksCoefficients(), FindG4BirksCoefficient(), InitialiseBirksCoefficient(), and InitialiseG4materials().
std::vector< G4String > G4EmSaturation::g4MatNames static private
Definition at line 128 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 128 of file G4EmSaturation.hh
Referenced by DumpG4BirksCoefficients(), FindG4BirksCoefficient(), InitialiseBirksCoefficient(), and InitialiseG4materials().
std::vector< G4double > G4EmSaturation::massFactors static private
Definition at line 123 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 123 of file G4EmSaturation.hh
Referenced by DumpBirksCoefficients(), InitialiseBirksCoefficient(), InitialiseG4Saturation(), and VisibleEnergyDeposition().
G4int G4EmSaturation::nG4Birks private
Definition at line 117 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 117 of file G4EmSaturation.hh
Referenced by DumpG4BirksCoefficients(), FindG4BirksCoefficient(), G4EmSaturation(), InitialiseBirksCoefficient(), InitialiseG4materials(), and InitialiseG4Saturation().
G4NistManager* G4EmSaturation::nist private
Definition at line 114 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 114 of file G4EmSaturation.hh
Referenced by G4EmSaturation(), and InitialiseBirksCoefficient().
G4int G4EmSaturation::nMaterials = 0 static private
Definition at line 120 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 120 of file G4EmSaturation.hh
Referenced by DumpBirksCoefficients(), and InitialiseG4Saturation().
G4int G4EmSaturation::nWarnings private
Definition at line 118 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 118 of file G4EmSaturation.hh
Referenced by G4EmSaturation().
const G4ParticleDefinition* G4EmSaturation::proton private
Definition at line 113 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 113 of file G4EmSaturation.hh
Referenced by G4EmSaturation(), InitialiseBirksCoefficient(), and VisibleEnergyDeposition().
G4int G4EmSaturation::verbose private
Definition at line 116 of file G4EmSaturation.hh.
View newest version in sPHENIX GitHub at line 116 of file G4EmSaturation.hh
Referenced by FindG4BirksCoefficient(), G4EmSaturation(), InitialiseG4Saturation(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmSaturation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmSaturation.cc