ECCE @ EIC Software: CML2CInputData Class Reference
CML2CInputData Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2CInputData.hh>
Public Member Functions
CML2CInputData (void)
~CML2CInputData (void)
G4bool getbOnlyVisio ()
void setbOnlyVisio (G4bool val)
void setPhaseSpaceCentre (G4ThreeVector val)
void setPhaseSpaceHalfSize (G4ThreeVector val)
void setbSavePhaseSPace (G4bool val)
void setbForcePhaseSpaceBeforeJaws (G4bool val)
void setbStopAtPhaseSpace (G4bool val)
void setPhaseSpaceOutFile (G4String val)
void setbSaveROG (G4bool val)
void setROGOutFile (G4String val)
void setMaxNumberOfEvents (G4int val)
void setNmaxLoop (G4int val)
G4double getMaxNumberOfEvents ()
void setBCompareExp (G4bool val)
void setFileExperimentalData (G4String val)
void setFileExperimentalDataOut (G4String val)
void setNBeams (G4int val)
void setNMaxParticlesInRamPlanePhaseSpace (G4int val)
void setSaving_in_Selected_Voxels_every_events (G4int val)
void setSaving_in_ROG_Voxels_every_events (G4int val)
void setMax_N_particles_in_PhSp_File (G4int val)
void setVoxelsX (G4int val)
void setVoxelsY (G4int val)
void setVoxelsZ (G4int val)
Public Attributes
G4bool bOnlyVisio
SInputData inputData
CML2MainMessenger * ML2MainMessenger
Detailed Description
Definition at line 54 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 54 of file ML2CInputData.hh
Constructor & Destructor Documentation
CML2CInputData::CML2CInputData (void)
Definition at line 46 of file ML2CInputData.cc.
View newest version in sPHENIX GitHub at line 46 of file ML2CInputData.cc
References bOnlyVisio, and ML2MainMessenger.
CML2CInputData::~CML2CInputData (void)
Definition at line 54 of file ML2CInputData.cc.
View newest version in sPHENIX GitHub at line 54 of file ML2CInputData.cc
Member Function Documentation
G4bool CML2CInputData::getbOnlyVisio () inline
Definition at line 60 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 60 of file ML2CInputData.hh
References bOnlyVisio.
Referenced by main().
G4double CML2CInputData::getMaxNumberOfEvents () inline
Definition at line 75 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 75 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::maxNumberOfEvents.
void CML2CInputData::setBCompareExp (G4bool val) inline
Definition at line 77 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2CInputData.hh
References SGeneralData::bCompareExp, SInputData::generalData, and inputData.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setbForcePhaseSpaceBeforeJaws (G4bool val) inline
Definition at line 66 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2CInputData.hh
References SGeneralData::bForcePhaseSpaceBeforeJaws, SInputData::generalData, and inputData.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setbOnlyVisio (G4bool val) inline
Definition at line 62 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 62 of file ML2CInputData.hh
References bOnlyVisio.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setbSavePhaseSPace (G4bool val) inline
Definition at line 65 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 65 of file ML2CInputData.hh
References SGeneralData::bSavePhaseSpace, SInputData::generalData, and inputData.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setbSaveROG (G4bool val) inline
Definition at line 70 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 70 of file ML2CInputData.hh
References SGeneralData::bSaveROG, SInputData::generalData, and inputData.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setbStopAtPhaseSpace (G4bool val) inline
Definition at line 67 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 67 of file ML2CInputData.hh
References SGeneralData::bStopAtPhaseSpace, SInputData::generalData, and inputData.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setFileExperimentalData (G4String val) inline
Definition at line 78 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 78 of file ML2CInputData.hh
References SGeneralData::fileExperimentalData, SInputData::generalData, and inputData.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setFileExperimentalDataOut (G4String val) inline
Definition at line 79 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2CInputData.hh
References SGeneralData::fileExperimentalDataOut, SInputData::generalData, and inputData.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setMax_N_particles_in_PhSp_File (G4int val) inline
Definition at line 86 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 86 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::max_N_particles_in_PhSp_File.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setMaxNumberOfEvents (G4int val) inline
Definition at line 73 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 73 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::maxNumberOfEvents.
Referenced by CML2MainMessenger::CML2MainMessenger(), and CML2MainMessenger::SetNewValue().
void CML2CInputData::setNBeams (G4int val) inline
Definition at line 81 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 81 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::nBeam.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setNmaxLoop (G4int val) inline
Definition at line 74 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 74 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::nMaxLoop.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setNMaxParticlesInRamPlanePhaseSpace (G4int val) inline
Definition at line 82 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 82 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::nMaxParticlesInRamPlanePhaseSpace.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setPhaseSpaceCentre (G4ThreeVector val) inline
Definition at line 63 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 63 of file ML2CInputData.hh
References SGeneralData::centrePhaseSpace, SInputData::generalData, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), inputData, and CLHEP::Hep3Vector::set().
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setPhaseSpaceHalfSize (G4ThreeVector val) inline
Definition at line 64 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 64 of file ML2CInputData.hh
References SInputData::generalData, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), SGeneralData::halfSizePhaseSpace, inputData, and CLHEP::Hep3Vector::set().
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setPhaseSpaceOutFile (G4String val) inline
Definition at line 68 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 68 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::PhaseSpaceOutFile.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setROGOutFile (G4String val) inline
Definition at line 71 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 71 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::ROGOutFile.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setSaving_in_ROG_Voxels_every_events (G4int val) inline
Definition at line 85 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 85 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::saving_in_ROG_Voxels_every_events.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setSaving_in_Selected_Voxels_every_events (G4int val) inline
Definition at line 84 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 84 of file ML2CInputData.hh
References SInputData::generalData, inputData, and SGeneralData::saving_in_Selected_Voxels_every_events.
Referenced by CML2MainMessenger::SetNewValue().
void CML2CInputData::setVoxelsX (G4int val) inline
Definition at line 89 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 89 of file ML2CInputData.hh
References inputData, SvoxelSegmentation::nX, and SInputData::voxelSegmentation.
Referenced by CML2MainMessenger::CML2MainMessenger(), and CML2MainMessenger::SetNewValue().
void CML2CInputData::setVoxelsY (G4int val) inline
Definition at line 90 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 90 of file ML2CInputData.hh
References inputData, SvoxelSegmentation::nY, and SInputData::voxelSegmentation.
Referenced by CML2MainMessenger::CML2MainMessenger(), and CML2MainMessenger::SetNewValue().
void CML2CInputData::setVoxelsZ (G4int val) inline
Definition at line 91 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 91 of file ML2CInputData.hh
References inputData, SvoxelSegmentation::nZ, and SInputData::voxelSegmentation.
Referenced by CML2MainMessenger::CML2MainMessenger(), and CML2MainMessenger::SetNewValue().
Member Data Documentation
G4bool CML2CInputData::bOnlyVisio
Definition at line 93 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 93 of file ML2CInputData.hh
Referenced by CML2CInputData(), getbOnlyVisio(), main(), and setbOnlyVisio().
SInputData CML2CInputData::inputData
Definition at line 94 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 94 of file ML2CInputData.hh
Referenced by getMaxNumberOfEvents(), main(), setBCompareExp(), setbForcePhaseSpaceBeforeJaws(), setbSavePhaseSPace(), setbSaveROG(), setbStopAtPhaseSpace(), setFileExperimentalData(), setFileExperimentalDataOut(), setMax_N_particles_in_PhSp_File(), setMaxNumberOfEvents(), setNBeams(), setNmaxLoop(), setNMaxParticlesInRamPlanePhaseSpace(), setPhaseSpaceCentre(), setPhaseSpaceHalfSize(), setPhaseSpaceOutFile(), setROGOutFile(), setSaving_in_ROG_Voxels_every_events(), setSaving_in_Selected_Voxels_every_events(), setVoxelsX(), setVoxelsY(), and setVoxelsZ().
CML2MainMessenger* CML2CInputData::ML2MainMessenger
Definition at line 95 of file ML2CInputData.hh.
View newest version in sPHENIX GitHub at line 95 of file ML2CInputData.hh
Referenced by CML2CInputData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2CInputData.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2CInputData.cc