ECCE @ EIC Software: G4GPSModel Class Reference
G4GPSModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4GPSModel.hh>
Public Member Functions
G4GPSModel (const G4Colour &colour=G4Colour(1., 0., 0., 0.3))
virtual ~G4GPSModel ()
void DescribeYourselfTo (G4VGraphicsScene &)
G4String GetCurrentDescription () const
G4String GetCurrentTag () const
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
virtual G4bool Validate (G4bool warn=true)
Protected Attributes
G4Colour fColour
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Private Member Functions
G4GPSModel (const G4GPSModel &)
G4GPSModel & operator= (const G4GPSModel &)
Detailed Description
Definition at line 45 of file G4GPSModel.hh.
View newest version in sPHENIX GitHub at line 45 of file G4GPSModel.hh
Constructor & Destructor Documentation
G4GPSModel::G4GPSModel (const G4Colour & colour = G4Colour(1.,0.,0.,0.3))
Definition at line 51 of file G4GPSModel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4GPSModel.cc
References fColour, G4VModel::fGlobalDescription, G4VModel::fGlobalTag, and G4VModel::fType.
G4GPSModel::~G4GPSModel () virtual
Definition at line 61 of file G4GPSModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4GPSModel.cc
G4GPSModel::G4GPSModel (const G4GPSModel &) private
Member Function Documentation
void G4GPSModel::DescribeYourselfTo (G4VGraphicsScene & sceneHandler) virtual
Implements G4VModel.
Definition at line 73 of file G4GPSModel.cc.
View newest version in sPHENIX GitHub at line 73 of file G4GPSModel.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::AddSolid(), G4VGraphicsScene::BeginPrimitives(), G4VGraphicsScene::EndPrimitives(), fColour, G4SPSPosDistribution::GetCentreCoords(), G4GeneralParticleSourceData::GetCurrentSource(), G4SPSPosDistribution::GetHalfX(), G4SPSPosDistribution::GetHalfY(), G4SPSPosDistribution::GetHalfZ(), G4GeometryTolerance::GetInstance(), G4SPSPosDistribution::GetParAlpha(), G4SPSPosDistribution::GetParPhi(), G4SPSPosDistribution::GetParTheta(), G4SPSPosDistribution::GetPosDisShape(), G4SingleParticleSource::GetPosDist(), G4SPSPosDistribution::GetPosDisType(), G4SPSPosDistribution::GetRadius(), G4SPSPosDistribution::GetRadius0(), G4SPSPosDistribution::GetRotx(), G4SPSPosDistribution::GetRoty(), G4SPSPosDistribution::GetRotz(), G4GeneralParticleSourceData::GetSourceVectorSize(), G4GeometryTolerance::GetSurfaceTolerance(), CLHEP::HepXHat, CLHEP::HepYHat, CLHEP::HepZHat, G4GeneralParticleSourceData::Instance(), G4VGraphicsScene::PostAddSolid(), G4VGraphicsScene::PreAddSolid(), G4VisAttributes::SetColour(), G4VisAttributes::SetForceSolid(), G4VMarker::SetPosition(), G4VMarker::SetScreenDiameter(), G4Visible::SetVisAttributes(), Acts::Test::transform, and twopi.
G4String G4GPSModel::GetCurrentDescription () const virtual
Reimplemented from G4VModel.
Definition at line 68 of file G4GPSModel.cc.
View newest version in sPHENIX GitHub at line 68 of file G4GPSModel.cc
References GetCurrentTag().
G4String G4GPSModel::GetCurrentTag () const virtual
Reimplemented from G4VModel.
Definition at line 63 of file G4GPSModel.cc.
View newest version in sPHENIX GitHub at line 63 of file G4GPSModel.cc
Referenced by GetCurrentDescription().
G4GPSModel& G4GPSModel::operator= (const G4GPSModel &) private
Member Data Documentation
G4Colour G4GPSModel::fColour protected
Definition at line 67 of file G4GPSModel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4GPSModel.hh
Referenced by DescribeYourselfTo(), and G4GPSModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4GPSModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4GPSModel.cc