ECCE @ EIC Software: G4CrossSectionFactoryRegistry Class Reference
G4CrossSectionFactoryRegistry Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionFactoryRegistry.hh>
Public Member Functions
G4VBaseXSFactory * GetFactory (const G4String &name, G4bool abortIfNotFound=true) const
void Register (const G4String &name, G4VBaseXSFactory *factory)
Static Public Member Functions
static
G4CrossSectionFactoryRegistry * Instance ()
Private Member Functions
G4CrossSectionFactoryRegistry ()
G4CrossSectionFactoryRegistry (const G4CrossSectionFactoryRegistry &)
G4CrossSectionFactoryRegistry & operator= (const G4CrossSectionFactoryRegistry &)
Private Attributes
std::map< G4String,
G4VBaseXSFactory * > factories
Static Private Attributes
static
G4CrossSectionFactoryRegistry * instance = 0
Friends
std::ostream & operator<< (std::ostream &, const G4CrossSectionFactoryRegistry &)
Detailed Description
Definition at line 48 of file G4CrossSectionFactoryRegistry.hh.
View newest version in sPHENIX GitHub at line 48 of file G4CrossSectionFactoryRegistry.hh
Constructor & Destructor Documentation
G4CrossSectionFactoryRegistry::G4CrossSectionFactoryRegistry () private
Definition at line 47 of file G4CrossSectionFactoryRegistry.cc.
View newest version in sPHENIX GitHub at line 47 of file G4CrossSectionFactoryRegistry.cc
References instance.
Referenced by Instance().
G4CrossSectionFactoryRegistry::G4CrossSectionFactoryRegistry (const G4CrossSectionFactoryRegistry &) private
Definition at line 52 of file G4CrossSectionFactoryRegistry.cc.
View newest version in sPHENIX GitHub at line 52 of file G4CrossSectionFactoryRegistry.cc
References FatalException, and G4Exception().
Member Function Documentation
G4VBaseXSFactory * G4CrossSectionFactoryRegistry::GetFactory (const G4String & name, G4bool abortIfNotFound = true) const
Definition at line 78 of file G4CrossSectionFactoryRegistry.cc.
View newest version in sPHENIX GitHub at line 78 of file G4CrossSectionFactoryRegistry.cc
References factories, FatalException, G4Exception(), if(), and it.
Referenced by G4CrossSectionDataSetRegistry::GetCrossSectionDataSet().
G4CrossSectionFactoryRegistry * G4CrossSectionFactoryRegistry::Instance (void) static
Definition at line 39 of file G4CrossSectionFactoryRegistry.cc.
View newest version in sPHENIX GitHub at line 39 of file G4CrossSectionFactoryRegistry.cc
References G4CrossSectionFactoryRegistry(), and instance.
Referenced by G4CrossSectionFactory< T, mode >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 0 >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 1 >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 2 >::G4CrossSectionFactory(), and G4CrossSectionDataSetRegistry::GetCrossSectionDataSet().
G4CrossSectionFactoryRegistry & G4CrossSectionFactoryRegistry::operator= (const G4CrossSectionFactoryRegistry &) private
Definition at line 57 of file G4CrossSectionFactoryRegistry.cc.
View newest version in sPHENIX GitHub at line 57 of file G4CrossSectionFactoryRegistry.cc
References FatalException, and G4Exception().
void G4CrossSectionFactoryRegistry::Register (const G4String & name, G4VBaseXSFactory * factory)
Definition at line 64 of file G4CrossSectionFactoryRegistry.cc.
View newest version in sPHENIX GitHub at line 64 of file G4CrossSectionFactoryRegistry.cc
References factories, G4Exception(), and JustWarning.
Referenced by G4CrossSectionFactory< T, mode >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 0 >::G4CrossSectionFactory(), G4CrossSectionFactory< T, 1 >::G4CrossSectionFactory(), and G4CrossSectionFactory< T, 2 >::G4CrossSectionFactory().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & msg, const G4CrossSectionFactoryRegistry & rhs) friend
Definition at line 98 of file G4CrossSectionFactoryRegistry.cc.
View newest version in sPHENIX GitHub at line 98 of file G4CrossSectionFactoryRegistry.cc
Member Data Documentation
std::map<G4String, G4VBaseXSFactory*> G4CrossSectionFactoryRegistry::factories private
Definition at line 52 of file G4CrossSectionFactoryRegistry.hh.
View newest version in sPHENIX GitHub at line 52 of file G4CrossSectionFactoryRegistry.hh
Referenced by GetFactory(), and Register().
G4CrossSectionFactoryRegistry * G4CrossSectionFactoryRegistry::instance = 0 static private
Definition at line 53 of file G4CrossSectionFactoryRegistry.hh.
View newest version in sPHENIX GitHub at line 53 of file G4CrossSectionFactoryRegistry.hh
Referenced by G4CrossSectionFactoryRegistry(), and Instance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionFactoryRegistry.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4CrossSectionFactoryRegistry.cc