ECCE @ EIC Software: G4eeTo3PiModel Class Reference
G4eeTo3PiModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeTo3PiModel.hh>
Public Member Functions
G4eeTo3PiModel (G4eeCrossSections *, G4double, G4double)
virtual ~G4eeTo3PiModel ()
virtual G4double PeakEnergy () const override
virtual G4double ComputeCrossSection (G4double) const override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, G4double, const G4ThreeVector &) override
Public Member Functions inherited from G4Vee2hadrons
G4Vee2hadrons (G4eeCrossSections *cr, G4double vlowEnergy, G4double vhighEnergy, G4double vdelta)
virtual ~G4Vee2hadrons ()
G4PhysicsVector * PhysicsVector () const
G4double LowEnergy () const
G4double HighEnergy () const
Private Member Functions
G4eeTo3PiModel & operator= (const G4eeTo3PiModel &right)=delete
G4eeTo3PiModel (const G4eeTo3PiModel &)=delete
Private Attributes
G4double massPi
G4double massPi0
G4double massOm
G4double massPhi
G4double gmax
Additional Inherited Members
Protected Attributes inherited from G4Vee2hadrons
G4eeCrossSections * cross
Detailed Description
Definition at line 58 of file G4eeTo3PiModel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4eeTo3PiModel.hh
Constructor & Destructor Documentation
G4eeTo3PiModel::G4eeTo3PiModel (G4eeCrossSections * cr, G4double maxkinEnergy, G4double binWidth) explicit
Definition at line 65 of file G4eeTo3PiModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4eeTo3PiModel.cc
References G4cout, G4endl, G4ParticleDefinition::GetPDGMass(), gmax, massOm, massPhi, massPi, massPi0, MeV, G4PionPlus::PionPlus(), and G4PionZero::PionZero().
G4eeTo3PiModel::~G4eeTo3PiModel () virtual
Definition at line 84 of file G4eeTo3PiModel.cc.
View newest version in sPHENIX GitHub at line 84 of file G4eeTo3PiModel.cc
G4eeTo3PiModel::G4eeTo3PiModel (const G4eeTo3PiModel &) private delete
Member Function Documentation
G4double G4eeTo3PiModel::ComputeCrossSection (G4double e) const override virtual
Implements G4Vee2hadrons.
Definition at line 98 of file G4eeTo3PiModel.cc.
View newest version in sPHENIX GitHub at line 98 of file G4eeTo3PiModel.cc
References G4Vee2hadrons::cross, and G4eeCrossSections::CrossSection3pi().
G4eeTo3PiModel& G4eeTo3PiModel::operator= (const G4eeTo3PiModel & right) private delete
G4double G4eeTo3PiModel::PeakEnergy () const override virtual
Implements G4Vee2hadrons.
Definition at line 89 of file G4eeTo3PiModel.cc.
View newest version in sPHENIX GitHub at line 89 of file G4eeTo3PiModel.cc
References e, G4Vee2hadrons::HighEnergy(), massOm, and massPhi.
void G4eeTo3PiModel::SampleSecondaries (std::vector< G4DynamicParticle * > * newp, G4double e, const G4ThreeVector & direction) override virtual
Implements G4Vee2hadrons.
Definition at line 105 of file G4eeTo3PiModel.cc.
View newest version in sPHENIX GitHub at line 105 of file G4eeTo3PiModel.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4Vee2hadrons::cross, G4eeCrossSections::DpRho(), e, CLHEP::HepLorentzVector::e(), e2, G4cout, G4endl, G4RandomDirection(), G4UniformRand, gmax, CLHEP::HepLorentzVector::m2(), massPi, massPi0, nmax, G4InuclParticleNames::nn, norm, G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), CLHEP::HepLorentzVector::rotateUz(), CLHEP::HepLorentzVector::set(), CLHEP::Hep3Vector::x(), CLHEP::HepLorentzVector::x(), x1, CLHEP::Hep3Vector::y(), CLHEP::HepLorentzVector::y(), CLHEP::Hep3Vector::z(), and CLHEP::HepLorentzVector::z().
Member Data Documentation
G4double G4eeTo3PiModel::gmax private
Definition at line 84 of file G4eeTo3PiModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4eeTo3PiModel.hh
Referenced by G4eeTo3PiModel(), and SampleSecondaries().
G4double G4eeTo3PiModel::massOm private
Definition at line 82 of file G4eeTo3PiModel.hh.
View newest version in sPHENIX GitHub at line 82 of file G4eeTo3PiModel.hh
Referenced by G4eeTo3PiModel(), and PeakEnergy().
G4double G4eeTo3PiModel::massPhi private
Definition at line 83 of file G4eeTo3PiModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4eeTo3PiModel.hh
Referenced by G4eeTo3PiModel(), and PeakEnergy().
G4double G4eeTo3PiModel::massPi private
Definition at line 80 of file G4eeTo3PiModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4eeTo3PiModel.hh
Referenced by G4eeTo3PiModel(), and SampleSecondaries().
G4double G4eeTo3PiModel::massPi0 private
Definition at line 81 of file G4eeTo3PiModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4eeTo3PiModel.hh
Referenced by G4eeTo3PiModel(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeTo3PiModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/src/G4eeTo3PiModel.cc