ECCE @ EIC Software: G4RDShellVacancy Class Reference
G4RDShellVacancy Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDShellVacancy.hh>
Public Member Functions
G4RDShellVacancy ()
~G4RDShellVacancy ()
std::vector< G4int > GenerateNumberOfIonisations (const G4MaterialCutsCouple *couple, G4double incidentEnergy, G4double eLoss) const
void AddXsiTable (G4RDVEMDataSet *set)
Private Member Functions
G4double AverageNOfIonisations (const G4MaterialCutsCouple *couple, G4int index, G4double energy, G4double eLoss) const
Private Attributes
std::vector< G4RDVEMDataSet * > xsis
Detailed Description
Definition at line 53 of file G4RDShellVacancy.hh.
View newest version in sPHENIX GitHub at line 53 of file G4RDShellVacancy.hh
Constructor & Destructor Documentation
G4RDShellVacancy::G4RDShellVacancy ()
Definition at line 43 of file G4RDShellVacancy.cc.
View newest version in sPHENIX GitHub at line 43 of file G4RDShellVacancy.cc
G4RDShellVacancy::~G4RDShellVacancy ()
Definition at line 47 of file G4RDShellVacancy.cc.
View newest version in sPHENIX GitHub at line 47 of file G4RDShellVacancy.cc
References k, and xsis.
Member Function Documentation
void G4RDShellVacancy::AddXsiTable (G4RDVEMDataSet * set)
Definition at line 58 of file G4RDShellVacancy.cc.
View newest version in sPHENIX GitHub at line 58 of file G4RDShellVacancy.cc
References xsis.
Referenced by G4LowEnergyIonisation::BuildLossTable().
G4double G4RDShellVacancy::AverageNOfIonisations (const G4MaterialCutsCouple * couple, G4int index, G4double energy, G4double eLoss) const private
Definition at line 93 of file G4RDShellVacancy.cc.
View newest version in sPHENIX GitHub at line 93 of file G4RDShellVacancy.cc
References G4RDVEMDataSet::FindValue(), G4MaterialCutsCouple::GetIndex(), and xsis.
Referenced by GenerateNumberOfIonisations().
std::vector< G4int > G4RDShellVacancy::GenerateNumberOfIonisations (const G4MaterialCutsCouple * couple, G4double incidentEnergy, G4double eLoss) const
Definition at line 64 of file G4RDShellVacancy.cc.
View newest version in sPHENIX GitHub at line 64 of file G4RDShellVacancy.cc
References AverageNOfIonisations(), G4Poisson(), G4MaterialCutsCouple::GetMaterial(), G4Material::GetNumberOfElements(), and material().
Referenced by G4LowEnergyIonisation::DeexciteAtom().
Member Data Documentation
std::vector<G4RDVEMDataSet*> G4RDShellVacancy::xsis private
Definition at line 74 of file G4RDShellVacancy.hh.
View newest version in sPHENIX GitHub at line 74 of file G4RDShellVacancy.hh
Referenced by AddXsiTable(), AverageNOfIonisations(), and ~G4RDShellVacancy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDShellVacancy.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDShellVacancy.cc