ECCE @ EIC Software: CLHEP::HepEulerAngles Class Reference
CLHEP::HepEulerAngles Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/EulerAngles.h>
Public Member Functions
HepEulerAngles ()
HepEulerAngles (double phi, double theta, double psi)
double getPhi () const
double phi () const
EA & setPhi (double phi)
double getTheta () const
double theta () const
EA & setTheta (double theta)
double getPsi () const
double psi () const
EA & setPsi (double psi)
EA & set (double phi, double theta, double psi)
int compare (const EA &ea) const
bool operator== (const EA &ea) const
bool operator!= (const EA &ea) const
bool operator< (const EA &ea) const
bool operator<= (const EA &ea) const
bool operator> (const EA &ea) const
bool operator>= (const EA &ea) const
bool isNear (const EA &ea, double epsilon=tolerance) const
double howNear (const EA &ea) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Protected Types
typedef HepEulerAngles EA
Protected Member Functions
double distance (const HepEulerAngles &ex) const
Protected Attributes
double phi_
double theta_
double psi_
Static Protected Attributes
static double tolerance = Hep3Vector::ToleranceTicks * 1.0e-8
Friends
std::ostream & operator<< (std::ostream &os, const EA &ea)
std::istream & operator>> (std::istream &is, EA &ea)
Detailed Description
Author
Definition at line 38 of file EulerAngles.h.
View newest version in sPHENIX GitHub at line 38 of file EulerAngles.h
Member Typedef Documentation
typedef HepEulerAngles CLHEP::HepEulerAngles::EA protected
Definition at line 41 of file EulerAngles.h.
View newest version in sPHENIX GitHub at line 41 of file EulerAngles.h
Constructor & Destructor Documentation
CLHEP::HepEulerAngles::HepEulerAngles () inline
CLHEP::HepEulerAngles::HepEulerAngles (double phi, double theta, double psi) inline
Member Function Documentation
int CLHEP::HepEulerAngles::compare (const EA & ea) const inline
double CLHEP::HepEulerAngles::distance (const HepEulerAngles & ex) const protected
Definition at line 64 of file EulerAngles.cc.
View newest version in sPHENIX GitHub at line 64 of file EulerAngles.cc
References d, sum, and CLHEP::ZMpvEulerAnglesRep().
Referenced by howNear(), and isNear().
double CLHEP::HepEulerAngles::getPhi () const inline
double CLHEP::HepEulerAngles::getPsi () const inline
double CLHEP::HepEulerAngles::getTheta () const inline
static double CLHEP::HepEulerAngles::getTolerance () inline static
double CLHEP::HepEulerAngles::howNear (const EA & ea) const
Definition at line 90 of file EulerAngles.cc.
View newest version in sPHENIX GitHub at line 90 of file EulerAngles.cc
References distance().
bool CLHEP::HepEulerAngles::isNear (const EA & ea, double epsilon = tolerance) const
Definition at line 83 of file EulerAngles.cc.
View newest version in sPHENIX GitHub at line 83 of file EulerAngles.cc
References distance(), and epsilon().
bool CLHEP::HepEulerAngles::operator!= (const EA & ea) const inline
bool CLHEP::HepEulerAngles::operator< (const EA & ea) const inline
bool CLHEP::HepEulerAngles::operator<= (const EA & ea) const inline
bool CLHEP::HepEulerAngles::operator== (const EA & ea) const inline
bool CLHEP::HepEulerAngles::operator> (const EA & ea) const inline
bool CLHEP::HepEulerAngles::operator>= (const EA & ea) const inline
double CLHEP::HepEulerAngles::phi () const inline
Referenced by CLHEP::HepRotation::HepRotation(), CLHEP::operator<<(), CLHEP::HepRotation::phi(), CLHEP::Hep3Vector::rotate(), CLHEP::HepRotation::set(), and CLHEP::ZMpvEulerAnglesRep().
double CLHEP::HepEulerAngles::psi () const inline
Referenced by arorie(), CLHEP::HepRotation::HepRotation(), luindf(), CLHEP::operator<<(), CLHEP::HepRotation::psi(), pyindf(), CLHEP::Hep3Vector::rotate(), CLHEP::HepRotation::set(), and CLHEP::ZMpvEulerAnglesRep().
EA& CLHEP::HepEulerAngles::set (double phi, double theta, double psi) inline
Referenced by CLHEP::operator>>().
EA& CLHEP::HepEulerAngles::setPhi (double phi) inline
EA& CLHEP::HepEulerAngles::setPsi (double psi) inline
EA& CLHEP::HepEulerAngles::setTheta (double theta) inline
static double CLHEP::HepEulerAngles::setTolerance (double tol) inline static
double CLHEP::HepEulerAngles::theta () const inline
Referenced by CLHEP::HepRotation::HepRotation(), CLHEP::operator<<(), CLHEP::Hep3Vector::rotate(), CLHEP::HepRotation::set(), and CLHEP::ZMpvEulerAnglesRep().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const EA & ea) friend
std::istream& operator>> (std::istream & is, EA & ea) friend
Member Data Documentation
double CLHEP::HepEulerAngles::phi_ protected
Definition at line 101 of file EulerAngles.h.
View newest version in sPHENIX GitHub at line 101 of file EulerAngles.h
double CLHEP::HepEulerAngles::psi_ protected
Definition at line 103 of file EulerAngles.h.
View newest version in sPHENIX GitHub at line 103 of file EulerAngles.h
double CLHEP::HepEulerAngles::theta_ protected
Definition at line 102 of file EulerAngles.h.
View newest version in sPHENIX GitHub at line 102 of file EulerAngles.h
double CLHEP::HepEulerAngles::tolerance = Hep3Vector::ToleranceTicks * 1.0e-8 static protected
Definition at line 42 of file EulerAngles.h.
View newest version in sPHENIX GitHub at line 42 of file EulerAngles.h
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/EulerAngles.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/EulerAngles.cc