ECCE @ EIC Software: CexmcPhysicsManager Class Reference
CexmcPhysicsManager Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcPhysicsManager.hh>
Public Member Functions
CexmcPhysicsManager ()
virtual ~CexmcPhysicsManager ()
virtual CexmcProductionModel * GetProductionModel (void)=0
virtual G4bool IsStudiedProcessAllowed (void) const =0
virtual void ResampleTrackLengthInTarget (const G4Track *track, const G4StepPoint *stepPoint=NULL)=0
virtual void SetupConstructionHook (const CexmcSetup *setup)=0
G4bool OnlyBeamParticleCanTriggerStudiedProcess (void) const
void IncrementNumberOfTriggeredStudiedInteractions (void)
void ResetNumberOfTriggeredStudiedInteractions (void)
G4double GetProposedMaxIL (void) const
void SetMaxIL (const G4ThreeVector &direction)
void SetMaxILCorrection (G4double value)
void SetProposedMaxIL (G4double value)
Protected Member Functions
virtual void CalculateBasicMaxIL (const G4ThreeVector &direction)=0
Protected Attributes
G4double basicMaxIL
G4double maxILCorrection
G4double proposedMaxIL
G4int numberOfTriggeredStudiedInteractions
G4bool onlyBeamParticleCanTriggerStudiedProcess
Private Attributes
CexmcPhysicsManagerMessenger * messenger
Detailed Description
Definition at line 58 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 58 of file CexmcPhysicsManager.hh
Constructor & Destructor Documentation
CexmcPhysicsManager::CexmcPhysicsManager ()
Definition at line 48 of file CexmcPhysicsManager.cc.
View newest version in sPHENIX GitHub at line 48 of file CexmcPhysicsManager.cc
References messenger.
CexmcPhysicsManager::~CexmcPhysicsManager () virtual
Definition at line 57 of file CexmcPhysicsManager.cc.
View newest version in sPHENIX GitHub at line 57 of file CexmcPhysicsManager.cc
References messenger.
Member Function Documentation
virtual void CexmcPhysicsManager::CalculateBasicMaxIL (const G4ThreeVector & direction) protected pure virtual
Implemented in CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >.
Referenced by SetMaxIL().
virtual CexmcProductionModel* CexmcPhysicsManager::GetProductionModel (void) pure virtual
Implemented in CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >.
Referenced by CexmcEventAction::CexmcEventAction(), CexmcTrackingAction::CexmcTrackingAction(), CexmcEventAction::EndOfEventAction(), CexmcRunAction::EndOfRunAction(), and main().
G4double CexmcPhysicsManager::GetProposedMaxIL (void) const inline
Definition at line 131 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 131 of file CexmcPhysicsManager.hh
References proposedMaxIL.
void CexmcPhysicsManager::IncrementNumberOfTriggeredStudiedInteractions (void) inline
Definition at line 117 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 117 of file CexmcPhysicsManager.hh
References numberOfTriggeredStudiedInteractions.
Referenced by CexmcStudiedProcess::PostStepDoIt().
virtual G4bool CexmcPhysicsManager::IsStudiedProcessAllowed (void) const pure virtual
Implemented in CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >.
Referenced by CexmcStudiedProcess::PostStepGetPhysicalInteractionLength().
G4bool CexmcPhysicsManager::OnlyBeamParticleCanTriggerStudiedProcess (void) const inline
Definition at line 110 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 110 of file CexmcPhysicsManager.hh
References onlyBeamParticleCanTriggerStudiedProcess.
Referenced by CexmcTrackingAction::PreUserTrackingAction().
virtual void CexmcPhysicsManager::ResampleTrackLengthInTarget (const G4Track * track, const G4StepPoint * stepPoint = NULL) pure virtual
Implemented in CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >.
Referenced by CexmcTrackingAction::SetupIncidentParticleTrackInfo(), and CexmcSteppingAction::UserSteppingAction().
void CexmcPhysicsManager::ResetNumberOfTriggeredStudiedInteractions (void) inline
Definition at line 124 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 124 of file CexmcPhysicsManager.hh
References numberOfTriggeredStudiedInteractions.
Referenced by CexmcEventAction::BeginOfEventAction().
void CexmcPhysicsManager::SetMaxIL (const G4ThreeVector & direction) inline
Definition at line 137 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 137 of file CexmcPhysicsManager.hh
References basicMaxIL, CalculateBasicMaxIL(), maxILCorrection, and proposedMaxIL.
Referenced by CexmcParticleGun::SetOrigDirection().
void CexmcPhysicsManager::SetMaxILCorrection (G4double value) inline
Definition at line 144 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 144 of file CexmcPhysicsManager.hh
References basicMaxIL, maxILCorrection, and proposedMaxIL.
Referenced by CexmcPhysicsManagerMessenger::SetNewValue().
void CexmcPhysicsManager::SetProposedMaxIL (G4double value) inline
Definition at line 151 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 151 of file CexmcPhysicsManager.hh
References proposedMaxIL.
virtual void CexmcPhysicsManager::SetupConstructionHook (const CexmcSetup * setup) pure virtual
Implemented in CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >.
Referenced by CexmcSetup::Construct().
Member Data Documentation
G4double CexmcPhysicsManager::basicMaxIL protected
Definition at line 95 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 95 of file CexmcPhysicsManager.hh
Referenced by SetMaxIL(), and SetMaxILCorrection().
G4double CexmcPhysicsManager::maxILCorrection protected
Definition at line 97 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 97 of file CexmcPhysicsManager.hh
Referenced by SetMaxIL(), and SetMaxILCorrection().
CexmcPhysicsManagerMessenger* CexmcPhysicsManager::messenger private
Definition at line 106 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 106 of file CexmcPhysicsManager.hh
Referenced by CexmcPhysicsManager(), and ~CexmcPhysicsManager().
G4int CexmcPhysicsManager::numberOfTriggeredStudiedInteractions protected
Definition at line 101 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 101 of file CexmcPhysicsManager.hh
Referenced by IncrementNumberOfTriggeredStudiedInteractions(), and ResetNumberOfTriggeredStudiedInteractions().
G4bool CexmcPhysicsManager::onlyBeamParticleCanTriggerStudiedProcess protected
Definition at line 103 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 103 of file CexmcPhysicsManager.hh
Referenced by OnlyBeamParticleCanTriggerStudiedProcess().
G4double CexmcPhysicsManager::proposedMaxIL protected
Definition at line 99 of file CexmcPhysicsManager.hh.
View newest version in sPHENIX GitHub at line 99 of file CexmcPhysicsManager.hh
Referenced by GetProposedMaxIL(), SetMaxIL(), SetMaxILCorrection(), and SetProposedMaxIL().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcPhysicsManager.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcPhysicsManager.cc