ECCE @ EIC Software: G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable Class Reference
G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PhysicalVolumeModel.hh>
Public Member Functions
G4PhysicalVolumeModelTouchable (const std::vector< G4PhysicalVolumeNodeID > &fullPVPath)
const G4ThreeVector & GetTranslation (G4int depth) const
const G4RotationMatrix * GetRotation (G4int depth) const
G4VPhysicalVolume * GetVolume (G4int depth) const
G4VSolid * GetSolid (G4int depth) const
G4int GetReplicaNumber (G4int depth) const
G4int GetHistoryDepth () const
Public Member Functions inherited from G4VTouchable
G4VTouchable ()
virtual ~G4VTouchable ()
G4int GetCopyNumber (G4int depth=0) const
virtual G4int MoveUpHistory (G4int num_levels=1)
virtual void UpdateYourself (G4VPhysicalVolume *pPhysVol, const G4NavigationHistory *history=nullptr)
virtual const G4NavigationHistory * GetHistory () const
Private Attributes
const std::vector
< G4PhysicalVolumeNodeID > & fFullPVPath
Detailed Description
Definition at line 120 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4PhysicalVolumeModel.hh
Constructor & Destructor Documentation
G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::G4PhysicalVolumeModelTouchable (const std::vector< G4PhysicalVolumeNodeID > & fullPVPath)
Definition at line 1009 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 1009 of file G4PhysicalVolumeModel.cc
Member Function Documentation
G4int G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetHistoryDepth () const inline virtual
Reimplemented from G4VTouchable.
Definition at line 129 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4PhysicalVolumeModel.hh
References fFullPVPath.
G4int G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetReplicaNumber (G4int depth) const virtual
Reimplemented from G4VTouchable.
Definition at line 1064 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 1064 of file G4PhysicalVolumeModel.cc
References FatalErrorInArgument, G4PhysicalVolumeModel::fFullPVPath, and G4Exception().
const G4RotationMatrix * G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetRotation (G4int depth) const virtual
Implements G4VTouchable.
Definition at line 1026 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 1026 of file G4PhysicalVolumeModel.cc
References FatalErrorInArgument, G4PhysicalVolumeModel::fFullPVPath, and G4Exception().
G4VSolid * G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetSolid (G4int depth) const virtual
Reimplemented from G4VTouchable.
Definition at line 1052 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 1052 of file G4PhysicalVolumeModel.cc
References FatalErrorInArgument, G4PhysicalVolumeModel::fFullPVPath, and G4Exception().
const G4ThreeVector & G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetTranslation (G4int depth) const virtual
Implements G4VTouchable.
Definition at line 1012 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 1012 of file G4PhysicalVolumeModel.cc
References FatalErrorInArgument, fFullPVPath, and G4Exception().
G4VPhysicalVolume * G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetVolume (G4int depth) const virtual
Reimplemented from G4VTouchable.
Definition at line 1040 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 1040 of file G4PhysicalVolumeModel.cc
References FatalErrorInArgument, G4PhysicalVolumeModel::fFullPVPath, and G4Exception().
Member Data Documentation
const std::vector<G4PhysicalVolumeNodeID>& G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::fFullPVPath private
Definition at line 131 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 131 of file G4PhysicalVolumeModel.hh
Referenced by GetHistoryDepth(), and GetTranslation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PhysicalVolumeModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4PhysicalVolumeModel.cc