ECCE @ EIC Software: G4FTFPAntiBarionBuilder Class Reference
G4FTFPAntiBarionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPAntiBarionBuilder.hh>
Public Member Functions
G4FTFPAntiBarionBuilder (G4bool quasiElastic=false)
virtual ~G4FTFPAntiBarionBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4AntiProtonInelasticProcess *aP) finaloverride
virtual void Build (G4AntiNeutronInelasticProcess *aP) finaloverride
virtual void Build (G4AntiDeuteronInelasticProcess *aP) finaloverride
virtual void Build (G4AntiTritonInelasticProcess *aP) finaloverride
virtual void Build (G4AntiHe3InelasticProcess *aP) finaloverride
virtual void Build (G4AntiAlphaInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double val) finaloverride
virtual void SetMaxEnergy (G4double val) finaloverride
Public Member Functions inherited from G4VAntiBarionBuilder
G4VAntiBarionBuilder ()=default
virtual ~G4VAntiBarionBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4LundStringFragmentation * theLund
G4VCrossSectionDataSet * theAntiNucleonData
G4VComponentCrossSection * theAntiNucleonXS
G4double theMin
G4double theMax
Detailed Description
Definition at line 58 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4FTFPAntiBarionBuilder.hh
Constructor & Destructor Documentation
G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder (G4bool quasiElastic = false)
Definition at line 48 of file G4FTFPAntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4FTFPAntiBarionBuilder.cc
References G4CrossSectionDataSetRegistry::GetComponentCrossSection(), G4HadronicParameters::GetMaxEnergy(), GeV, G4HadronicParameters::Instance(), G4CrossSectionDataSetRegistry::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theAntiNucleonData, theAntiNucleonXS, theCascade, theLund, theMax, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4FTFPAntiBarionBuilder::~G4FTFPAntiBarionBuilder () virtual
Definition at line 78 of file G4FTFPAntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 78 of file G4FTFPAntiBarionBuilder.cc
References theLund, theQuasiElastic, and theStringDecay.
Member Function Documentation
virtual void G4FTFPAntiBarionBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VAntiBarionBuilder.
Definition at line 64 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4FTFPAntiBarionBuilder.hh
void G4FTFPAntiBarionBuilder::Build (G4AntiProtonInelasticProcess * aP) final override virtual
Implements G4VAntiBarionBuilder.
Definition at line 88 of file G4FTFPAntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 88 of file G4FTFPAntiBarionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theAntiNucleonData, theMax, theMin, and theModel.
void G4FTFPAntiBarionBuilder::Build (G4AntiNeutronInelasticProcess * aP) final override virtual
Implements G4VAntiBarionBuilder.
Definition at line 97 of file G4FTFPAntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 97 of file G4FTFPAntiBarionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theAntiNucleonData, theMax, theMin, and theModel.
void G4FTFPAntiBarionBuilder::Build (G4AntiDeuteronInelasticProcess * aP) final override virtual
Implements G4VAntiBarionBuilder.
Definition at line 106 of file G4FTFPAntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 106 of file G4FTFPAntiBarionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theAntiNucleonData, theMax, theMin, and theModel.
void G4FTFPAntiBarionBuilder::Build (G4AntiTritonInelasticProcess * aP) final override virtual
Implements G4VAntiBarionBuilder.
Definition at line 115 of file G4FTFPAntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 115 of file G4FTFPAntiBarionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theAntiNucleonData, theMax, theMin, and theModel.
void G4FTFPAntiBarionBuilder::Build (G4AntiHe3InelasticProcess * aP) final override virtual
Implements G4VAntiBarionBuilder.
Definition at line 124 of file G4FTFPAntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 124 of file G4FTFPAntiBarionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theAntiNucleonData, theMax, theMin, and theModel.
void G4FTFPAntiBarionBuilder::Build (G4AntiAlphaInelasticProcess * aP) final override virtual
Implements G4VAntiBarionBuilder.
Definition at line 133 of file G4FTFPAntiBarionBuilder.cc.
View newest version in sPHENIX GitHub at line 133 of file G4FTFPAntiBarionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theAntiNucleonData, theMax, theMin, and theModel.
virtual void G4FTFPAntiBarionBuilder::SetMaxEnergy (G4double val) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 73 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FTFPAntiBarionBuilder.hh
References theMax.
virtual void G4FTFPAntiBarionBuilder::SetMinEnergy (G4double val) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 72 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4FTFPAntiBarionBuilder.hh
References theMin.
Member Data Documentation
G4VCrossSectionDataSet* G4FTFPAntiBarionBuilder::theAntiNucleonData private
Definition at line 85 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 85 of file G4FTFPAntiBarionBuilder.hh
Referenced by Build(), and G4FTFPAntiBarionBuilder().
G4VComponentCrossSection* G4FTFPAntiBarionBuilder::theAntiNucleonXS private
Definition at line 86 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 86 of file G4FTFPAntiBarionBuilder.hh
Referenced by G4FTFPAntiBarionBuilder().
G4GeneratorPrecompoundInterface* G4FTFPAntiBarionBuilder::theCascade private
Definition at line 79 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FTFPAntiBarionBuilder.hh
Referenced by G4FTFPAntiBarionBuilder().
G4LundStringFragmentation* G4FTFPAntiBarionBuilder::theLund private
Definition at line 83 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4FTFPAntiBarionBuilder.hh
Referenced by G4FTFPAntiBarionBuilder(), and ~G4FTFPAntiBarionBuilder().
G4double G4FTFPAntiBarionBuilder::theMax private
Definition at line 88 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 88 of file G4FTFPAntiBarionBuilder.hh
Referenced by Build(), G4FTFPAntiBarionBuilder(), and SetMaxEnergy().
G4double G4FTFPAntiBarionBuilder::theMin private
Definition at line 87 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 87 of file G4FTFPAntiBarionBuilder.hh
Referenced by Build(), G4FTFPAntiBarionBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4FTFPAntiBarionBuilder::theModel private
Definition at line 78 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FTFPAntiBarionBuilder.hh
Referenced by Build(), and G4FTFPAntiBarionBuilder().
G4QuasiElasticChannel* G4FTFPAntiBarionBuilder::theQuasiElastic private
Definition at line 82 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4FTFPAntiBarionBuilder.hh
Referenced by G4FTFPAntiBarionBuilder(), and ~G4FTFPAntiBarionBuilder().
G4ExcitedStringDecay* G4FTFPAntiBarionBuilder::theStringDecay private
Definition at line 81 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4FTFPAntiBarionBuilder.hh
Referenced by G4FTFPAntiBarionBuilder(), and ~G4FTFPAntiBarionBuilder().
G4FTFModel* G4FTFPAntiBarionBuilder::theStringModel private
Definition at line 80 of file G4FTFPAntiBarionBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FTFPAntiBarionBuilder.hh
Referenced by G4FTFPAntiBarionBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPAntiBarionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFPAntiBarionBuilder.cc