ECCE @ EIC Software: GFlashShowerModelMessenger Class Reference
GFlashShowerModelMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashShowerModelMessenger.hh>
Public Member Functions
GFlashShowerModelMessenger (GFlashShowerModel *myModel)
~GFlashShowerModelMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
GFlashShowerModel * myModel
G4UIdirectory * myParaDir
G4UIcmdWithAnInteger * FlagCmd
G4UIcmdWithAnInteger * ContCmd
G4UIcmdWithADouble * StepInX0Cmd
G4UIcmdWithADoubleAndUnit * EmaxCmd
G4UIcmdWithADoubleAndUnit * EminCmd
G4UIcmdWithADoubleAndUnit * EkillCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 55 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file GFlashShowerModelMessenger.hh
Constructor & Destructor Documentation
GFlashShowerModelMessenger::GFlashShowerModelMessenger (GFlashShowerModel * myModel)
Definition at line 53 of file GFlashShowerModelMessenger.cc.
View newest version in sPHENIX GitHub at line 53 of file GFlashShowerModelMessenger.cc
References G4UIcommand::AvailableForStates(), ContCmd, EkillCmd, EmaxCmd, EminCmd, FlagCmd, G4State_Idle, G4State_PreInit, myModel, myParaDir, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcommand::SetGuidance(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetUnitCategory(), and StepInX0Cmd.
GFlashShowerModelMessenger::~GFlashShowerModelMessenger ()
Definition at line 94 of file GFlashShowerModelMessenger.cc.
View newest version in sPHENIX GitHub at line 94 of file GFlashShowerModelMessenger.cc
References ContCmd, EkillCmd, EmaxCmd, EminCmd, FlagCmd, and StepInX0Cmd.
Member Function Documentation
G4String GFlashShowerModelMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 143 of file GFlashShowerModelMessenger.cc.
View newest version in sPHENIX GitHub at line 143 of file GFlashShowerModelMessenger.cc
References EkillCmd, G4Electron::ElectronDefinition(), EmaxCmd, EminCmd, FlagCmd, GFlashParticleBounds::GetEneToKill(), GFlashShowerModel::GetFlagParamType(), GFlashParticleBounds::GetMaxEneToParametrise(), GFlashParticleBounds::GetMinEneToParametrise(), GeV, myModel, and GFlashShowerModel::PBound.
Referenced by SetNewValue().
void GFlashShowerModelMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 106 of file GFlashShowerModelMessenger.cc.
View newest version in sPHENIX GitHub at line 106 of file GFlashShowerModelMessenger.cc
References ContCmd, EkillCmd, G4Electron::ElectronDefinition(), EmaxCmd, EminCmd, FlagCmd, GetCurrentValue(), G4UIcmdWithADouble::GetNewDoubleValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), myModel, GFlashShowerModel::PBound, GFlashParticleBounds::SetEneToKill(), GFlashShowerModel::SetFlagParamType(), GFlashShowerModel::SetFlagParticleContainment(), GFlashParticleBounds::SetMaxEneToParametrise(), GFlashParticleBounds::SetMinEneToParametrise(), GFlashShowerModel::SetStepInX0(), and StepInX0Cmd.
Member Data Documentation
G4UIcmdWithAnInteger* GFlashShowerModelMessenger::ContCmd private
Definition at line 70 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file GFlashShowerModelMessenger.hh
Referenced by GFlashShowerModelMessenger(), SetNewValue(), and ~GFlashShowerModelMessenger().
G4UIcmdWithADoubleAndUnit* GFlashShowerModelMessenger::EkillCmd private
Definition at line 74 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file GFlashShowerModelMessenger.hh
Referenced by GetCurrentValue(), GFlashShowerModelMessenger(), SetNewValue(), and ~GFlashShowerModelMessenger().
G4UIcmdWithADoubleAndUnit* GFlashShowerModelMessenger::EmaxCmd private
Definition at line 72 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file GFlashShowerModelMessenger.hh
Referenced by GetCurrentValue(), GFlashShowerModelMessenger(), SetNewValue(), and ~GFlashShowerModelMessenger().
G4UIcmdWithADoubleAndUnit* GFlashShowerModelMessenger::EminCmd private
Definition at line 73 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file GFlashShowerModelMessenger.hh
Referenced by GetCurrentValue(), GFlashShowerModelMessenger(), SetNewValue(), and ~GFlashShowerModelMessenger().
G4UIcmdWithAnInteger* GFlashShowerModelMessenger::FlagCmd private
Definition at line 69 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file GFlashShowerModelMessenger.hh
Referenced by GetCurrentValue(), GFlashShowerModelMessenger(), SetNewValue(), and ~GFlashShowerModelMessenger().
GFlashShowerModel* GFlashShowerModelMessenger::myModel private
Definition at line 67 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file GFlashShowerModelMessenger.hh
Referenced by GetCurrentValue(), GFlashShowerModelMessenger(), and SetNewValue().
G4UIdirectory* GFlashShowerModelMessenger::myParaDir private
Definition at line 68 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file GFlashShowerModelMessenger.hh
Referenced by GFlashShowerModelMessenger().
G4UIcmdWithADouble* GFlashShowerModelMessenger::StepInX0Cmd private
Definition at line 71 of file GFlashShowerModelMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file GFlashShowerModelMessenger.hh
Referenced by GFlashShowerModelMessenger(), SetNewValue(), and ~GFlashShowerModelMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashShowerModelMessenger.hh
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/src/GFlashShowerModelMessenger.cc