ECCE @ EIC Software: G4LightTargetCollider Class Reference
G4LightTargetCollider Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4LightTargetCollider.hh>
Public Member Functions
G4LightTargetCollider ()
virtual ~G4LightTargetCollider ()
void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
void setVerboseLevel (G4int verbose=0)
Public Member Functions inherited from G4CascadeColliderBase
G4CascadeColliderBase (const G4String &name, G4int verbose=0)
virtual ~G4CascadeColliderBase ()
virtual void rescatter (G4InuclParticle *, G4KineticTrackVector *, G4V3DNucleus *, G4CollisionOutput &)
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Private Member Functions
G4LightTargetCollider (const G4LightTargetCollider &)
G4LightTargetCollider & operator= (const G4LightTargetCollider &)
G4double GammaDCrossSection (G4double)
NucleonPair AbsorptionOnDeuteron (G4InuclParticle *bullet)
ScatteringProducts SingleNucleonScattering (const G4InuclElementaryParticle &projectile, const G4InuclElementaryParticle &targetNucleon)
Private Attributes
G4ElementaryParticleCollider * theElementaryParticleCollider
G4CollisionOutput output
G4CascadeFinalStateGenerator fsGen
G4double mP
G4double mN
G4double mD
G4double pFermiD
Additional Inherited Members
Protected Member Functions inherited from G4CascadeColliderBase
virtual G4bool useEPCollider (G4InuclParticle *bullet, G4InuclParticle *target) const
virtual G4bool inelasticInteractionPossible (G4InuclParticle *bullet, G4InuclParticle *target, G4double ekin) const
virtual G4bool validateOutput (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &fragment, G4CollisionOutput &output)
virtual G4bool validateOutput (G4InuclParticle *bullet, G4InuclParticle *target, const std::vector< G4InuclElementaryParticle > &particles)
Protected Attributes inherited from G4CascadeColliderBase
G4InteractionCase interCase
G4CascadeCheckBalance * balance
Detailed Description
Definition at line 52 of file G4LightTargetCollider.hh.
View newest version in sPHENIX GitHub at line 52 of file G4LightTargetCollider.hh
Constructor & Destructor Documentation
G4LightTargetCollider::G4LightTargetCollider ()
Definition at line 55 of file G4LightTargetCollider.cc.
View newest version in sPHENIX GitHub at line 55 of file G4LightTargetCollider.cc
References G4Deuteron::Deuteron(), G4ParticleDefinition::GetPDGMass(), CLHEP::GeV, mD, mN, mP, G4Neutron::Neutron(), pFermiD, and G4Proton::Proton().
G4LightTargetCollider::~G4LightTargetCollider () virtual
Definition at line 65 of file G4LightTargetCollider.cc.
View newest version in sPHENIX GitHub at line 65 of file G4LightTargetCollider.cc
References theElementaryParticleCollider.
G4LightTargetCollider::G4LightTargetCollider (const G4LightTargetCollider &) private
Member Function Documentation
NucleonPair G4LightTargetCollider::AbsorptionOnDeuteron (G4InuclParticle * bullet) private
Definition at line 239 of file G4LightTargetCollider.cc.
View newest version in sPHENIX GitHub at line 239 of file G4LightTargetCollider.cc
References CLHEP::HepLorentzVector::boost(), FatalException, G4Exception(), G4RandomDirection(), G4Gamma::Gamma(), G4InuclParticle::getDefinition(), G4InuclParticle::getEnergy(), G4InuclParticle::getMass(), G4InuclParticle::getMomModule(), mD, mN, mP, G4InuclParticleNames::neutron, G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), G4InuclParticleNames::proton, S(), CLHEP::HepLorentzVector::setE(), and CLHEP::HepLorentzVector::setVect().
Referenced by collide().
void G4LightTargetCollider::collide (G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & globalOutput) virtual
Implements G4VCascadeCollider.
Definition at line 78 of file G4LightTargetCollider.cc.
View newest version in sPHENIX GitHub at line 78 of file G4LightTargetCollider.cc
References AbsorptionOnDeuteron(), G4CollisionOutput::addOutgoingParticle(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4ElementaryParticleCollider::collide(), G4Deuteron::Deuteron(), FatalException, CLHEP::HepLorentzVector::findBoostToCM(), G4cout, G4endl, G4Exception(), G4RandomDirection(), G4UniformRand, GammaDCrossSection(), G4CascadeChannel::getCrossSection(), G4InuclParticle::getDefinition(), G4InuclParticle::getKineticEnergy(), G4InuclParticle::getMomentum(), G4ParticleDefinition::GetParticleName(), G4CascadeChannelTables::GetTable(), JustWarning, mD, mN, mP, G4Neutron::Neutron(), pFermiD, G4Proton::Proton(), G4CollisionOutput::reset(), SingleNucleonScattering(), theElementaryParticleCollider, G4CollisionOutput::trivialise(), G4CascadeColliderBase::useEPCollider(), and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::ApplyYourself().
G4double G4LightTargetCollider::GammaDCrossSection (G4double gammaEnergy) private
Definition at line 221 of file G4LightTargetCollider.cc.
View newest version in sPHENIX GitHub at line 221 of file G4LightTargetCollider.cc
Referenced by collide().
G4LightTargetCollider& G4LightTargetCollider::operator= (const G4LightTargetCollider &) private
void G4LightTargetCollider::setVerboseLevel (G4int verbose = 0) virtual
Reimplemented from G4CascadeColliderBase.
Definition at line 71 of file G4LightTargetCollider.cc.
View newest version in sPHENIX GitHub at line 71 of file G4LightTargetCollider.cc
References output, G4CollisionOutput::setVerboseLevel(), G4CascadeColliderBase::setVerboseLevel(), theElementaryParticleCollider, and G4VCascadeCollider::verboseLevel.
ScatteringProducts G4LightTargetCollider::SingleNucleonScattering (const G4InuclElementaryParticle & projectile, const G4InuclElementaryParticle & targetNucleon) private
Definition at line 305 of file G4LightTargetCollider.cc.
View newest version in sPHENIX GitHub at line 305 of file G4LightTargetCollider.cc
References G4CascadeFinalStateGenerator::Configure(), fsGen, G4Exception(), G4INCL::PhaseSpaceGenerator::generate(), G4HadDecayGenerator::Generate(), G4InuclParticle::getDefinition(), G4InuclParticle::getKineticEnergy(), G4InuclParticle::getMomentum(), G4InuclElementaryParticle::getParticleMass(), G4CascadeChannelTables::GetTable(), JustWarning, CLHEP::HepLorentzVector::mag(), mass, and G4InuclElementaryParticle::type().
Referenced by collide().
Member Data Documentation
G4CascadeFinalStateGenerator G4LightTargetCollider::fsGen private
Definition at line 74 of file G4LightTargetCollider.hh.
View newest version in sPHENIX GitHub at line 74 of file G4LightTargetCollider.hh
Referenced by SingleNucleonScattering().
G4double G4LightTargetCollider::mD private
Definition at line 83 of file G4LightTargetCollider.hh.
View newest version in sPHENIX GitHub at line 83 of file G4LightTargetCollider.hh
Referenced by AbsorptionOnDeuteron(), collide(), and G4LightTargetCollider().
G4double G4LightTargetCollider::mN private
Definition at line 82 of file G4LightTargetCollider.hh.
View newest version in sPHENIX GitHub at line 82 of file G4LightTargetCollider.hh
Referenced by AbsorptionOnDeuteron(), collide(), and G4LightTargetCollider().
G4double G4LightTargetCollider::mP private
Definition at line 81 of file G4LightTargetCollider.hh.
View newest version in sPHENIX GitHub at line 81 of file G4LightTargetCollider.hh
Referenced by AbsorptionOnDeuteron(), collide(), and G4LightTargetCollider().
G4CollisionOutput G4LightTargetCollider::output private
Definition at line 65 of file G4LightTargetCollider.hh.
View newest version in sPHENIX GitHub at line 65 of file G4LightTargetCollider.hh
Referenced by setVerboseLevel().
G4double G4LightTargetCollider::pFermiD private
Definition at line 84 of file G4LightTargetCollider.hh.
View newest version in sPHENIX GitHub at line 84 of file G4LightTargetCollider.hh
Referenced by collide(), and G4LightTargetCollider().
G4ElementaryParticleCollider* G4LightTargetCollider::theElementaryParticleCollider private
Definition at line 63 of file G4LightTargetCollider.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LightTargetCollider.hh
Referenced by collide(), setVerboseLevel(), and ~G4LightTargetCollider().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4LightTargetCollider.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4LightTargetCollider.cc