ECCE @ EIC Software: TRACKING Namespace Reference
TRACKING Namespace Reference
Functions
PHG4TrackFastSim * FastKalmanFilter (nullptr)
PHG4TrackFastSim * FastKalmanFilterSiliconTrack (nullptr)
PHG4TrackFastSim * FastKalmanFilterInnerTrack (nullptr)
Variables
string TrackNodeName = "TrackMap"
std::set< std::string > ProjectionNames
Function Documentation
PHG4TrackFastSim* TRACKING::FastKalmanFilter (nullptr)
Referenced by Barrel(), BMMGSetup(), BToFSetup(), DIRCSetup(), ETOFSetup(), HTOFSetup(), make_barrel_layer(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), make_forward_station(), make_forward_station_basic(), make_GEM_station(), make_LANL_FST_station(), mRICHSetup(), RICHSetup(), RWellSetup(), Tracking_Reco(), TrackingInit(), and TRDSetup().
PHG4TrackFastSim* TRACKING::FastKalmanFilterInnerTrack (nullptr)
Referenced by Barrel(), make_barrel_layer(), make_barrel_layer_basic(), make_forward_station(), make_forward_station_basic(), make_GEM_station(), make_LANL_FST_station(), RWellSetup(), Tracking_Reco(), and TrackingInit().
PHG4TrackFastSim* TRACKING::FastKalmanFilterSiliconTrack (nullptr)
Referenced by Barrel(), make_LANL_FST_station(), RWellSetup(), Tracking_Reco(), and TrackingInit().
Variable Documentation
std::set<std::string> TRACKING::ProjectionNames
Definition at line 76 of file GlobalVariables.C.
View newest version in sPHENIX GitHub at line 76 of file GlobalVariables.C
Referenced by BarrelFastKalmanFilterConfigBARR(), BarrelFastKalmanFilterConfigSVTX(), BToFSetup(), DIRCSetup(), ETOFSetup(), Fun4All_runEvaluators(), HTOFSetup(), make_barrel_layer(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), make_forward_station(), make_forward_station_basic(), make_GEM_station(), mRICHSetup(), RICHSetup(), RWellSetup(), Tracking_Eval(), Tracking_Reco(), and TRDSetup().
string TRACKING::TrackNodeName = "TrackMap"
Definition at line 68 of file GlobalVariables.C.
View newest version in sPHENIX GitHub at line 68 of file GlobalVariables.C
Referenced by Jet_FwdReco(), Jet_Reco(), Tracking_Eval(), and Tracking_Reco().