ECCE @ EIC Software: G4VEvaporation Class Reference
G4VEvaporation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4VEvaporation.hh>
Public Member Functions
G4VEvaporation ()
virtual ~G4VEvaporation ()
virtual void BreakFragment (G4FragmentVector *, G4Fragment *theNucleus)
virtual void InitialiseChannels ()
virtual void SetPhotonEvaporation (G4VEvaporationChannel *ptr)
void SetFermiBreakUp (G4VFermiBreakUp *ptr)
G4VFermiBreakUp * GetFermiBreakUp () const
G4VEvaporationChannel * GetPhotonEvaporation ()
G4VEvaporationChannel * GetFissionChannel ()
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
size_t GetNumberOfChannels () const
Protected Member Functions
void CleanChannels ()
Protected Attributes
G4VEvaporationChannel * thePhotonEvaporation
G4VFermiBreakUp * theFBU
G4int OPTxs
G4bool useSICB
std::vector
< G4VEvaporationChannel * > * theChannels
G4VEvaporationFactory * theChannelFactory
Private Member Functions
G4VEvaporation (const G4VEvaporation &right)=delete
const G4VEvaporation & operator= (const G4VEvaporation &right)=delete
G4bool operator== (const G4VEvaporation &right) const =delete
G4bool operator!= (const G4VEvaporation &right) const =delete
Detailed Description
Definition at line 52 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VEvaporation.hh
Constructor & Destructor Documentation
G4VEvaporation::G4VEvaporation () explicit
Definition at line 37 of file G4VEvaporation.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VEvaporation.cc
G4VEvaporation::~G4VEvaporation () virtual
Definition at line 42 of file G4VEvaporation.cc.
View newest version in sPHENIX GitHub at line 42 of file G4VEvaporation.cc
References CleanChannels(), theChannelFactory, and thePhotonEvaporation.
G4VEvaporation::G4VEvaporation (const G4VEvaporation & right) private delete
Member Function Documentation
void G4VEvaporation::BreakFragment (G4FragmentVector * , G4Fragment * theNucleus) virtual
Reimplemented in G4Evaporation.
Definition at line 75 of file G4VEvaporation.cc.
View newest version in sPHENIX GitHub at line 75 of file G4VEvaporation.cc
Referenced by G4ExcitationHandler::BreakItUp().
void G4VEvaporation::CleanChannels () protected
Definition at line 49 of file G4VEvaporation.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VEvaporation.cc
References theChannels.
Referenced by G4Evaporation::SetCombinedChannel(), G4Evaporation::SetDefaultChannel(), G4Evaporation::SetGEMChannel(), G4Evaporation::SetGEMVIChannel(), and ~G4VEvaporation().
G4VFermiBreakUp * G4VEvaporation::GetFermiBreakUp () const inline
Definition at line 108 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 108 of file G4VEvaporation.hh
References theFBU.
G4VEvaporationChannel * G4VEvaporation::GetFissionChannel () inline
Definition at line 118 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VEvaporation.hh
References theChannels.
Referenced by G4INCLXXInterface::G4INCLXXInterface().
size_t G4VEvaporation::GetNumberOfChannels () const inline
Definition at line 133 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 133 of file G4VEvaporation.hh
References theChannels.
Referenced by G4ExcitationHandler::SetDeexChannelsType().
G4VEvaporationChannel * G4VEvaporation::GetPhotonEvaporation () inline
Definition at line 113 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VEvaporation.hh
References thePhotonEvaporation.
Referenced by G4ExcitationHandler::SetEvaporation().
void G4VEvaporation::InitialiseChannels () virtual
Reimplemented in G4Evaporation.
Definition at line 61 of file G4VEvaporation.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VEvaporation.cc
Referenced by G4ExcitationHandler::Initialise().
G4bool G4VEvaporation::operator!= (const G4VEvaporation & right) const private delete
const G4VEvaporation& G4VEvaporation::operator= (const G4VEvaporation & right) private delete
G4bool G4VEvaporation::operator== (const G4VEvaporation & right) const private delete
void G4VEvaporation::SetFermiBreakUp (G4VFermiBreakUp * ptr) inline
Definition at line 103 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 103 of file G4VEvaporation.hh
References theFBU.
Referenced by G4ExcitationHandler::SetEvaporation(), and G4ExcitationHandler::SetFermiModel().
void G4VEvaporation::SetOPTxs (G4int opt) inline
Definition at line 123 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 123 of file G4VEvaporation.hh
References OPTxs.
void G4VEvaporation::SetPhotonEvaporation (G4VEvaporationChannel * ptr) virtual
Definition at line 64 of file G4VEvaporation.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VEvaporation.cc
References theChannels, and thePhotonEvaporation.
Referenced by G4Evaporation::G4Evaporation(), and G4ExcitationHandler::SetPhotonEvaporation().
void G4VEvaporation::UseSICB (G4bool use) inline
Definition at line 128 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 128 of file G4VEvaporation.hh
References useSICB.
Member Data Documentation
G4int G4VEvaporation::OPTxs protected
Definition at line 89 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VEvaporation.hh
Referenced by G4WilsonAblationModel::G4WilsonAblationModel(), G4Evaporation::InitialiseChannelFactory(), and SetOPTxs().
G4VEvaporationFactory* G4VEvaporation::theChannelFactory protected
Definition at line 93 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VEvaporation.hh
Referenced by G4Evaporation::G4Evaporation(), G4WilsonAblationModel::G4WilsonAblationModel(), G4Evaporation::InitialiseChannelFactory(), G4Evaporation::SetCombinedChannel(), G4Evaporation::SetDefaultChannel(), G4Evaporation::SetGEMChannel(), G4Evaporation::SetGEMVIChannel(), and ~G4VEvaporation().
std::vector<G4VEvaporationChannel*>* G4VEvaporation::theChannels protected
Definition at line 92 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VEvaporation.hh
Referenced by CleanChannels(), G4WilsonAblationModel::G4WilsonAblationModel(), GetFissionChannel(), GetNumberOfChannels(), G4Evaporation::InitialiseChannelFactory(), and SetPhotonEvaporation().
G4VFermiBreakUp* G4VEvaporation::theFBU protected
Definition at line 87 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VEvaporation.hh
Referenced by G4Evaporation::BreakFragment(), GetFermiBreakUp(), and SetFermiBreakUp().
G4VEvaporationChannel* G4VEvaporation::thePhotonEvaporation protected
Definition at line 86 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VEvaporation.hh
Referenced by GetPhotonEvaporation(), G4Evaporation::SetCombinedChannel(), G4Evaporation::SetDefaultChannel(), G4Evaporation::SetGEMChannel(), G4Evaporation::SetGEMVIChannel(), SetPhotonEvaporation(), and ~G4VEvaporation().
G4bool G4VEvaporation::useSICB protected
Definition at line 90 of file G4VEvaporation.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VEvaporation.hh
Referenced by G4WilsonAblationModel::G4WilsonAblationModel(), and UseSICB().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4VEvaporation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/src/G4VEvaporation.cc