ECCE @ EIC Software: ClusterSBPoints Class Reference
ClusterSBPoints Class Reference
define a cluster of SB Points
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/ClusterSBPoints.hh>
Public Member Functions
ClusterSBPoints (std::set< SBPoint * > pPoints)
~ClusterSBPoints ()
bool IsDSB () const
bool IsSSB () const
unsigned int GetSize () const
void AddSBPoint (SBPoint *pSBPoint)
G4ThreeVector GetBarycenter () const
G4double GetEdep () const
void FindAllPointsPossible (std::vector< SBPoint * > *ptToCheck, G4int minPts, G4double minDist)
void NoticeInternalPts ()
will set to all store SBPoint they are part of this cluster
bool HasIn (const SBPoint *, G4double)
bool HasInBarycenter (const SBPoint *, G4double)
void MergeWith (ClusterSBPoints *)
std::set< SBPoint * > GetRegistredSBPoints () const
void Clear ()
Private Member Functions
void UpdateDoubleStrand ()
Private Attributes
unsigned int fSize
bool fIsDoubleSB
std::set< SBPoint * > fpRegisteredSBPoints
Detailed Description
define a cluster of SB Points
Definition at line 47 of file ClusterSBPoints.hh.
View newest version in sPHENIX GitHub at line 47 of file ClusterSBPoints.hh
Constructor & Destructor Documentation
ClusterSBPoints::ClusterSBPoints (std::set< SBPoint * > pPoints)
Definition at line 46 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 46 of file ClusterSBPoints.cc
References AddSBPoint(), and UpdateDoubleStrand().
ClusterSBPoints::~ClusterSBPoints ()
Definition at line 59 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 59 of file ClusterSBPoints.cc
References Clear().
Member Function Documentation
void ClusterSBPoints::AddSBPoint (SBPoint * pSBPoint)
Definition at line 78 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 78 of file ClusterSBPoints.cc
References fpRegisteredSBPoints, SBPoint::SetCluster(), and UpdateDoubleStrand().
Referenced by ClusterSBPoints(), FindAllPointsPossible(), and MergeWith().
void ClusterSBPoints::Clear ()
Definition at line 64 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 64 of file ClusterSBPoints.cc
References fpRegisteredSBPoints.
Referenced by MergeWith(), and ~ClusterSBPoints().
void ClusterSBPoints::FindAllPointsPossible (std::vector< SBPoint * > * ptToCheck, G4int minPts, G4double minDist)
Definition at line 191 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 191 of file ClusterSBPoints.cc
References AddSBPoint(), fpRegisteredSBPoints, GetSize(), and HasInBarycenter().
G4ThreeVector ClusterSBPoints::GetBarycenter () const
Definition at line 89 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 89 of file ClusterSBPoints.cc
References fpRegisteredSBPoints, x, y, and z.
Referenced by HasInBarycenter().
G4double ClusterSBPoints::GetEdep () const
Definition at line 113 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 113 of file ClusterSBPoints.cc
References fpRegisteredSBPoints.
std::set<SBPoint* > ClusterSBPoints::GetRegistredSBPoints () const inline
Definition at line 84 of file ClusterSBPoints.hh.
View newest version in sPHENIX GitHub at line 84 of file ClusterSBPoints.hh
References fpRegisteredSBPoints.
Referenced by MergeWith().
unsigned int ClusterSBPoints::GetSize () const inline
Definition at line 63 of file ClusterSBPoints.hh.
View newest version in sPHENIX GitHub at line 63 of file ClusterSBPoints.hh
References fpRegisteredSBPoints.
Referenced by FindAllPointsPossible().
bool ClusterSBPoints::HasIn (const SBPoint * pPtToCheck, G4double pMinDist)
Definition at line 223 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 223 of file ClusterSBPoints.cc
References AreOnTheSameCluster(), and fpRegisteredSBPoints.
bool ClusterSBPoints::HasInBarycenter (const SBPoint * pPtToCheck, G4double pMinDist)
Definition at line 246 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 246 of file ClusterSBPoints.cc
References GetBarycenter(), SBPoint::GetPosition(), nm, CLHEP::Hep3Vector::x(), x1, x2, CLHEP::Hep3Vector::y(), y1, y2, CLHEP::Hep3Vector::z(), z1, and z2.
Referenced by FindAllPointsPossible().
bool ClusterSBPoints::IsDSB () const inline
Definition at line 53 of file ClusterSBPoints.hh.
View newest version in sPHENIX GitHub at line 53 of file ClusterSBPoints.hh
References fIsDoubleSB.
Referenced by IsSSB().
bool ClusterSBPoints::IsSSB () const inline
Definition at line 58 of file ClusterSBPoints.hh.
View newest version in sPHENIX GitHub at line 58 of file ClusterSBPoints.hh
References IsDSB().
void ClusterSBPoints::MergeWith (ClusterSBPoints * pCluster)
this will insert all registredSBPoint from the given cluster to this cluster.
Definition at line 273 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 273 of file ClusterSBPoints.cc
References AddSBPoint(), Clear(), and GetRegistredSBPoints().
void ClusterSBPoints::NoticeInternalPts ()
will set to all store SBPoint they are part of this cluster
void ClusterSBPoints::UpdateDoubleStrand () private
Definition at line 128 of file ClusterSBPoints.cc.
View newest version in sPHENIX GitHub at line 128 of file ClusterSBPoints.cc
References fIsDoubleSB, and fpRegisteredSBPoints.
Referenced by AddSBPoint(), and ClusterSBPoints().
Member Data Documentation
bool ClusterSBPoints::fIsDoubleSB private
Definition at line 95 of file ClusterSBPoints.hh.
View newest version in sPHENIX GitHub at line 95 of file ClusterSBPoints.hh
Referenced by IsDSB(), and UpdateDoubleStrand().
std::set<SBPoint* > ClusterSBPoints::fpRegisteredSBPoints private
Definition at line 97 of file ClusterSBPoints.hh.
View newest version in sPHENIX GitHub at line 97 of file ClusterSBPoints.hh
Referenced by AddSBPoint(), Clear(), FindAllPointsPossible(), GetBarycenter(), GetEdep(), GetRegistredSBPoints(), GetSize(), HasIn(), and UpdateDoubleStrand().
unsigned int ClusterSBPoints::fSize private
Definition at line 94 of file ClusterSBPoints.hh.
View newest version in sPHENIX GitHub at line 94 of file ClusterSBPoints.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/ClusterSBPoints.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/src/ClusterSBPoints.cc