ECCE @ EIC Software: G4VEnergySpectrum Class Reference
G4VEnergySpectrum Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VEnergySpectrum.hh>
Public Member Functions
G4VEnergySpectrum ()
virtual ~G4VEnergySpectrum ()
virtual G4double Probability (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const =0
virtual G4double AverageEnergy (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const =0
virtual G4double SampleEnergy (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const =0
virtual G4double MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z=0, const G4ParticleDefinition *pd=0) const =0
virtual G4double Excitation (G4int Z, G4double kineticEnergy) const =0
virtual void PrintData () const =0
Private Member Functions
G4VEnergySpectrum (const G4VEnergySpectrum &)
G4VEnergySpectrum & operator= (const G4VEnergySpectrum &right)
Detailed Description
Definition at line 59 of file G4VEnergySpectrum.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VEnergySpectrum.hh
Constructor & Destructor Documentation
G4VEnergySpectrum::G4VEnergySpectrum () inline
Definition at line 64 of file G4VEnergySpectrum.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VEnergySpectrum.hh
virtual G4VEnergySpectrum::~G4VEnergySpectrum () inline virtual
Definition at line 66 of file G4VEnergySpectrum.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VEnergySpectrum.hh
G4VEnergySpectrum::G4VEnergySpectrum (const G4VEnergySpectrum &) private
Member Function Documentation
virtual G4double G4VEnergySpectrum::AverageEnergy (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const pure virtual
Implemented in G4eBremsstrahlungSpectrum, and G4eIonisationSpectrum.
Referenced by G4LivermoreIonisationModel::ComputeDEDXPerVolume().
virtual G4double G4VEnergySpectrum::Excitation (G4int Z, G4double kineticEnergy) const pure virtual
Implemented in G4eBremsstrahlungSpectrum, and G4eIonisationSpectrum.
Referenced by G4LivermoreIonisationModel::ComputeDEDXPerVolume().
virtual G4double G4VEnergySpectrum::MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z = 0, const G4ParticleDefinition * pd = 0) const pure virtual
Implemented in G4eBremsstrahlungSpectrum, and G4eIonisationSpectrum.
Referenced by G4LivermoreIonisationModel::SampleSecondaries().
G4VEnergySpectrum& G4VEnergySpectrum::operator= (const G4VEnergySpectrum & right) private
virtual void G4VEnergySpectrum::PrintData () const pure virtual
Implemented in G4eBremsstrahlungSpectrum, and G4eIonisationSpectrum.
Referenced by G4LivermoreIonisationModel::Initialise().
virtual G4double G4VEnergySpectrum::Probability (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const pure virtual
Implemented in G4eBremsstrahlungSpectrum, and G4eIonisationSpectrum.
Referenced by G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::GetCrossSectionAboveThresholdForElement(), and G4eIonisationCrossSectionHandler::GetCrossSectionAboveThresholdForElement().
virtual G4double G4VEnergySpectrum::SampleEnergy (G4int Z, G4double minKineticEnergy, G4double maxKineticEnergy, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const pure virtual
Implemented in G4eBremsstrahlungSpectrum, and G4eIonisationSpectrum.
Referenced by G4LivermoreIonisationModel::SampleSecondaries().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VEnergySpectrum.hh