ECCE @ EIC Software: WLSEventAction Class Reference
WLSEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSEventAction.hh>
Public Member Functions
WLSEventAction (WLSRunAction *)
virtual ~WLSEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
G4int GetEventNo ()
void SetEventVerbose (G4int)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
WLSRunAction * fRunAction
WLSEventActionMessenger * fEventMessenger
G4int fVerboseLevel
G4int fMPPCCollID
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 43 of file WLSEventAction.hh.
View newest version in sPHENIX GitHub at line 43 of file WLSEventAction.hh
Constructor & Destructor Documentation
WLSEventAction::WLSEventAction (WLSRunAction * runaction)
Definition at line 53 of file WLSEventAction.cc.
View newest version in sPHENIX GitHub at line 53 of file WLSEventAction.cc
References fEventMessenger, and fMPPCCollID.
WLSEventAction::~WLSEventAction () virtual
Definition at line 63 of file WLSEventAction.cc.
View newest version in sPHENIX GitHub at line 63 of file WLSEventAction.cc
References fEventMessenger.
Member Function Documentation
void WLSEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 70 of file WLSEventAction.cc.
View newest version in sPHENIX GitHub at line 70 of file WLSEventAction.cc
References fVerboseLevel, G4cout, G4endl, and G4Event::GetEventID().
void WLSEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 82 of file WLSEventAction.cc.
View newest version in sPHENIX GitHub at line 82 of file WLSEventAction.cc
References fMPPCCollID, fRunAction, fVerboseLevel, G4cout, G4endl, G4Threading::G4GetThreadId(), G4SDManager::GetCollectionID(), G4Event::GetEventID(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), WLSRunAction::GetRndmFreq(), and G4SDManager::GetSDMpointer().
G4int WLSEventAction::GetEventNo ()
Definition at line 118 of file WLSEventAction.cc.
View newest version in sPHENIX GitHub at line 118 of file WLSEventAction.cc
References G4UserEventAction::fpEventManager, G4EventManager::GetConstCurrentEvent(), and G4Event::GetEventID().
void WLSEventAction::SetEventVerbose (G4int level)
Definition at line 125 of file WLSEventAction.cc.
View newest version in sPHENIX GitHub at line 125 of file WLSEventAction.cc
References fVerboseLevel.
Referenced by WLSEventActionMessenger::SetNewValue().
Member Data Documentation
WLSEventActionMessenger* WLSEventAction::fEventMessenger private
Definition at line 61 of file WLSEventAction.hh.
View newest version in sPHENIX GitHub at line 61 of file WLSEventAction.hh
Referenced by WLSEventAction(), and ~WLSEventAction().
G4int WLSEventAction::fMPPCCollID private
Definition at line 65 of file WLSEventAction.hh.
View newest version in sPHENIX GitHub at line 65 of file WLSEventAction.hh
Referenced by EndOfEventAction(), and WLSEventAction().
WLSRunAction* WLSEventAction::fRunAction private
Definition at line 60 of file WLSEventAction.hh.
View newest version in sPHENIX GitHub at line 60 of file WLSEventAction.hh
Referenced by EndOfEventAction().
G4int WLSEventAction::fVerboseLevel private
Definition at line 63 of file WLSEventAction.hh.
View newest version in sPHENIX GitHub at line 63 of file WLSEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), and SetEventVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSEventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSEventAction.cc