ECCE @ EIC Software: RE05StackingAction Class Reference
RE05StackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05StackingAction.hh>
Public Member Functions
RE05StackingAction ()
virtual ~RE05StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
void SetNRequestMuon (G4int val)
G4int GetNRequestMuon () const
void SetNRequestIsoMuon (G4int val)
G4int GetNRequestIsoMuon () const
void SetNIsolation (G4int val)
G4int GetNIsolation () const
void SetRoIAngle (G4double val)
G4double GetRoIAngle () const
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Private Member Functions
G4bool InsideRoI (const G4Track *aTrack, G4double ang)
G4VHitsCollection * GetCollection (G4String colName)
Private Attributes
RE05TrackerHitsCollection * fTrkHits
RE05MuonHitsCollection * fMuonHits
RE05StackingActionMessenger * fMessenger
G4int fStage
G4int fReqMuon
G4int fReqIsoMuon
G4int fReqIso
G4double fAngRoI
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 44 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 44 of file RE05StackingAction.hh
Constructor & Destructor Documentation
RE05StackingAction::RE05StackingAction ()
Definition at line 46 of file RE05StackingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file RE05StackingAction.cc
References fMessenger.
RE05StackingAction::~RE05StackingAction () virtual
Definition at line 59 of file RE05StackingAction.cc.
View newest version in sPHENIX GitHub at line 59 of file RE05StackingAction.cc
References fMessenger.
Member Function Documentation
G4ClassificationOfNewTrack RE05StackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 65 of file RE05StackingAction.cc.
View newest version in sPHENIX GitHub at line 65 of file RE05StackingAction.cc
References fAngRoI, fKill, fStage, fSuspend, fUrgent, fWaiting, G4Track::GetDefinition(), G4Track::GetParentID(), G4ParticleDefinition::GetPDGCharge(), G4Track::GetTrackStatus(), InsideRoI(), G4MuonMinus::MuonMinusDefinition(), and G4MuonPlus::MuonPlusDefinition().
G4VHitsCollection * RE05StackingAction::GetCollection (G4String colName) private
Definition at line 131 of file RE05StackingAction.cc.
View newest version in sPHENIX GitHub at line 131 of file RE05StackingAction.cc
References G4SDManager::GetCollectionID(), G4RunManager::GetCurrentEvent(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4RunManager::GetRunManager(), and G4SDManager::GetSDMpointer().
Referenced by InsideRoI(), and NewStage().
G4int RE05StackingAction::GetNIsolation () const inline
Definition at line 75 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 75 of file RE05StackingAction.hh
References fReqIso.
Referenced by RE05StackingActionMessenger::GetCurrentValue().
G4int RE05StackingAction::GetNRequestIsoMuon () const inline
Definition at line 73 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 73 of file RE05StackingAction.hh
References fReqIsoMuon.
Referenced by RE05StackingActionMessenger::GetCurrentValue().
G4int RE05StackingAction::GetNRequestMuon () const inline
Definition at line 71 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 71 of file RE05StackingAction.hh
References fReqMuon.
Referenced by RE05StackingActionMessenger::GetCurrentValue().
G4double RE05StackingAction::GetRoIAngle () const inline
Definition at line 77 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 77 of file RE05StackingAction.hh
References fAngRoI.
Referenced by RE05StackingActionMessenger::GetCurrentValue().
G4bool RE05StackingAction::InsideRoI (const G4Track * aTrack, G4double ang) private
Definition at line 108 of file RE05StackingAction.cc.
View newest version in sPHENIX GitHub at line 108 of file RE05StackingAction.cc
References CLHEP::Hep3Vector::angle(), G4THitsCollection< T >::entries(), fMuonHits, G4cerr, G4endl, GetCollection(), and G4Track::GetPosition().
Referenced by ClassifyNewTrack().
void RE05StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 147 of file RE05StackingAction.cc.
View newest version in sPHENIX GitHub at line 147 of file RE05StackingAction.cc
References CLHEP::Hep3Vector::angle(), G4StackManager::clear(), G4THitsCollection< T >::entries(), fAngRoI, fMuonHits, fReqIso, fReqIsoMuon, fReqMuon, fStage, fTrkHits, G4cerr, G4endl, GetCollection(), G4StackManager::ReClassify(), and G4UserStackingAction::stackManager.
void RE05StackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 220 of file RE05StackingAction.cc.
View newest version in sPHENIX GitHub at line 220 of file RE05StackingAction.cc
References fMuonHits, fStage, and fTrkHits.
void RE05StackingAction::SetNIsolation (G4int val) inline
Definition at line 74 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 74 of file RE05StackingAction.hh
References fReqIso.
Referenced by RE05StackingActionMessenger::SetNewValue().
void RE05StackingAction::SetNRequestIsoMuon (G4int val) inline
Definition at line 72 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 72 of file RE05StackingAction.hh
References fReqIsoMuon.
Referenced by RE05StackingActionMessenger::SetNewValue().
void RE05StackingAction::SetNRequestMuon (G4int val) inline
Definition at line 70 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 70 of file RE05StackingAction.hh
References fReqMuon.
Referenced by RE05StackingActionMessenger::SetNewValue().
void RE05StackingAction::SetRoIAngle (G4double val) inline
Definition at line 76 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 76 of file RE05StackingAction.hh
References fAngRoI.
Referenced by RE05StackingActionMessenger::SetNewValue().
Member Data Documentation
G4double RE05StackingAction::fAngRoI private
Definition at line 67 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 67 of file RE05StackingAction.hh
Referenced by ClassifyNewTrack(), GetRoIAngle(), NewStage(), and SetRoIAngle().
RE05StackingActionMessenger* RE05StackingAction::fMessenger private
Definition at line 61 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file RE05StackingAction.hh
Referenced by RE05StackingAction(), and ~RE05StackingAction().
RE05MuonHitsCollection* RE05StackingAction::fMuonHits private
Definition at line 60 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file RE05StackingAction.hh
Referenced by InsideRoI(), NewStage(), and PrepareNewEvent().
G4int RE05StackingAction::fReqIso private
Definition at line 66 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 66 of file RE05StackingAction.hh
Referenced by GetNIsolation(), NewStage(), and SetNIsolation().
G4int RE05StackingAction::fReqIsoMuon private
Definition at line 65 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file RE05StackingAction.hh
Referenced by GetNRequestIsoMuon(), NewStage(), and SetNRequestIsoMuon().
G4int RE05StackingAction::fReqMuon private
Definition at line 64 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file RE05StackingAction.hh
Referenced by GetNRequestMuon(), NewStage(), and SetNRequestMuon().
G4int RE05StackingAction::fStage private
Definition at line 63 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file RE05StackingAction.hh
Referenced by ClassifyNewTrack(), NewStage(), and PrepareNewEvent().
RE05TrackerHitsCollection* RE05StackingAction::fTrkHits private
Definition at line 59 of file RE05StackingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file RE05StackingAction.hh
Referenced by NewStage(), and PrepareNewEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/src/RE05StackingAction.cc