ECCE @ EIC Software: G4LENDBertiniGammaElectroNuclearBuilder Class Reference
G4LENDBertiniGammaElectroNuclearBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/include/G4LENDBertiniGammaElectroNuclearBuilder.hh>
Public Member Functions
G4LENDBertiniGammaElectroNuclearBuilder (G4bool eNucl)
virtual ~G4LENDBertiniGammaElectroNuclearBuilder ()
virtual void Build ()
Public Member Functions inherited from G4BertiniElectroNuclearBuilder
G4BertiniElectroNuclearBuilder (G4bool eNucl)
virtual ~G4BertiniElectroNuclearBuilder ()
Private Types
using base = G4BertiniElectroNuclearBuilder
Additional Inherited Members
Protected Attributes inherited from G4BertiniElectroNuclearBuilder
G4PhotoNuclearProcess * thePhotoNuclearProcess
G4ElectronNuclearProcess * theElectronNuclearProcess
G4PositronNuclearProcess * thePositronNuclearProcess
G4ElectroVDNuclearModel * theElectroReaction
G4CascadeInterface * theGammaReaction
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4QGSModel< G4GammaParticipants > * theStringModel
G4QGSMFragmentation * theFragmentation
G4ExcitedStringDecay * theStringDecay
G4bool wasActivated
G4bool eActivated
Detailed Description
Definition at line 49 of file G4LENDBertiniGammaElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 49 of file G4LENDBertiniGammaElectroNuclearBuilder.hh
Member Typedef Documentation
using G4LENDBertiniGammaElectroNuclearBuilder::base = G4BertiniElectroNuclearBuilder private
Definition at line 52 of file G4LENDBertiniGammaElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4LENDBertiniGammaElectroNuclearBuilder.hh
Constructor & Destructor Documentation
G4LENDBertiniGammaElectroNuclearBuilder::G4LENDBertiniGammaElectroNuclearBuilder (G4bool eNucl)
Definition at line 52 of file G4LENDBertiniGammaElectroNuclearBuilder.cc.
View newest version in sPHENIX GitHub at line 52 of file G4LENDBertiniGammaElectroNuclearBuilder.cc
G4LENDBertiniGammaElectroNuclearBuilder::~G4LENDBertiniGammaElectroNuclearBuilder () virtual
Definition at line 57 of file G4LENDBertiniGammaElectroNuclearBuilder.cc.
View newest version in sPHENIX GitHub at line 57 of file G4LENDBertiniGammaElectroNuclearBuilder.cc
Member Function Documentation
void G4LENDBertiniGammaElectroNuclearBuilder::Build (void) virtual
Reimplemented from G4BertiniElectroNuclearBuilder.
Definition at line 69 of file G4LENDBertiniGammaElectroNuclearBuilder.cc.
View newest version in sPHENIX GitHub at line 69 of file G4LENDBertiniGammaElectroNuclearBuilder.cc
References G4HadronicProcess::AddDataSet(), G4BertiniElectroNuclearBuilder::Build(), G4LENDModel::DumpLENDTargetInfo(), G4Exception(), G4Gamma::Gamma(), JustWarning, message(), MeV, G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4BertiniElectroNuclearBuilder::theGammaReaction, and G4BertiniElectroNuclearBuilder::thePhotoNuclearProcess.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/include/G4LENDBertiniGammaElectroNuclearBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/src/G4LENDBertiniGammaElectroNuclearBuilder.cc