ECCE @ EIC Software: F04UserTrackInformation Class Reference
F04UserTrackInformation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04UserTrackInformation.hh>
Public Member Functions
F04UserTrackInformation ()
virtual ~F04UserTrackInformation ()
void SetTrackStatusFlag (TrackStatus s)
TrackStatus GetTrackStatusFlag () const
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
virtual void Print () const
const G4String & GetType () const
Private Attributes
TrackStatus fStatus
Additional Inherited Members
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Detailed Description
Definition at line 45 of file F04UserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 45 of file F04UserTrackInformation.hh
Constructor & Destructor Documentation
F04UserTrackInformation::F04UserTrackInformation ()
Definition at line 35 of file F04UserTrackInformation.cc.
View newest version in sPHENIX GitHub at line 35 of file F04UserTrackInformation.cc
F04UserTrackInformation::~F04UserTrackInformation () virtual
Definition at line 40 of file F04UserTrackInformation.cc.
View newest version in sPHENIX GitHub at line 40 of file F04UserTrackInformation.cc
Member Function Documentation
TrackStatus F04UserTrackInformation::GetTrackStatusFlag () const inline
Definition at line 54 of file F04UserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 54 of file F04UserTrackInformation.hh
References fStatus.
Referenced by F04TrackingAction::PostUserTrackingAction(), and F04SteppingAction::UserSteppingAction().
void F04UserTrackInformation::SetTrackStatusFlag (TrackStatus s) inline
Definition at line 53 of file F04UserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 53 of file F04UserTrackInformation.hh
References fStatus.
Referenced by F04TrackingAction::PreUserTrackingAction(), and F04SteppingAction::UserSteppingAction().
Member Data Documentation
TrackStatus F04UserTrackInformation::fStatus private
Definition at line 58 of file F04UserTrackInformation.hh.
View newest version in sPHENIX GitHub at line 58 of file F04UserTrackInformation.hh
Referenced by GetTrackStatusFlag(), and SetTrackStatusFlag().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04UserTrackInformation.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04UserTrackInformation.cc