ECCE @ EIC Software: G4DCtable Class Reference
G4DCtable Class Reference
#include <geant4/tree/geant4-10.6-release/source/readout/include/G4DCtable.hh>
Public Member Functions
G4DCtable ()
~G4DCtable ()
G4int Registor (G4String SDname, G4String DCname)
G4int GetCollectionID (G4String DCname) const
G4int GetCollectionID (G4VDigitizerModule *aDM) const
G4int entries () const
G4String GetDMname (G4int i) const
G4String GetDCname (G4int i) const
Private Attributes
std::vector< G4String > DMlist
std::vector< G4String > DClist
Detailed Description
Definition at line 50 of file G4DCtable.hh.
View newest version in sPHENIX GitHub at line 50 of file G4DCtable.hh
Constructor & Destructor Documentation
G4DCtable::G4DCtable ()
Definition at line 32 of file G4DCtable.cc.
View newest version in sPHENIX GitHub at line 32 of file G4DCtable.cc
G4DCtable::~G4DCtable ()
Definition at line 34 of file G4DCtable.cc.
View newest version in sPHENIX GitHub at line 34 of file G4DCtable.cc
Member Function Documentation
G4int G4DCtable::entries () const inline
Definition at line 66 of file G4DCtable.hh.
View newest version in sPHENIX GitHub at line 66 of file G4DCtable.hh
References DClist.
Referenced by G4DigiManager::GetCollectionCapacity(), GetDCname(), GetDMname(), and G4DigiManager::SetDigiCollection().
G4int G4DCtable::GetCollectionID (G4String DCname) const
Definition at line 45 of file G4DCtable.cc.
View newest version in sPHENIX GitHub at line 45 of file G4DCtable.cc
References DClist, DMlist, G4String::index(), and int().
Referenced by G4DigiManager::GetDigiCollectionID().
G4int G4DCtable::GetCollectionID (G4VDigitizerModule * aDM) const
Definition at line 76 of file G4DCtable.cc.
View newest version in sPHENIX GitHub at line 76 of file G4DCtable.cc
References DMlist, G4cerr, G4endl, G4VDigitizerModule::GetCollectionName(), G4VDigitizerModule::GetName(), G4VDigitizerModule::GetNumberOfCollections(), and k.
G4String G4DCtable::GetDCname (G4int i) const inline
Definition at line 73 of file G4DCtable.hh.
View newest version in sPHENIX GitHub at line 73 of file G4DCtable.hh
References DClist, and entries().
G4String G4DCtable::GetDMname (G4int i) const inline
Definition at line 68 of file G4DCtable.hh.
View newest version in sPHENIX GitHub at line 68 of file G4DCtable.hh
References DMlist, and entries().
G4int G4DCtable::Registor (G4String SDname, G4String DCname)
Definition at line 36 of file G4DCtable.cc.
View newest version in sPHENIX GitHub at line 36 of file G4DCtable.cc
References DClist, DMlist, and int().
Referenced by G4DigiManager::AddNewModule().
Member Data Documentation
std::vector<G4String> G4DCtable::DClist private
Definition at line 63 of file G4DCtable.hh.
View newest version in sPHENIX GitHub at line 63 of file G4DCtable.hh
Referenced by entries(), GetCollectionID(), GetDCname(), and Registor().
std::vector<G4String> G4DCtable::DMlist private
Definition at line 62 of file G4DCtable.hh.
View newest version in sPHENIX GitHub at line 62 of file G4DCtable.hh
Referenced by GetCollectionID(), GetDMname(), and Registor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/readout/include/G4DCtable.hh
geant4/tree/geant4-10.6-release/source/readout/src/G4DCtable.cc