ECCE @ EIC Software: G4BinaryPiKBuilder Class Reference
G4BinaryPiKBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BinaryPiKBuilder.hh>
Public Member Functions
G4BinaryPiKBuilder ()
virtual ~G4BinaryPiKBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonPlusInelasticProcess *) finaloverride
virtual void Build (G4KaonMinusInelasticProcess *) finaloverride
virtual void Build (G4KaonZeroLInelasticProcess *) finaloverride
virtual void Build (G4KaonZeroSInelasticProcess *) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPiKBuilder
G4VPiKBuilder ()=default
virtual ~G4VPiKBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4BinaryCascade * theModel
G4double theMin
G4double theMax
Detailed Description
Definition at line 52 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BinaryPiKBuilder.hh
Constructor & Destructor Documentation
G4BinaryPiKBuilder::G4BinaryPiKBuilder ()
Definition at line 49 of file G4BinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 49 of file G4BinaryPiKBuilder.cc
References GeV, G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual G4BinaryPiKBuilder::~G4BinaryPiKBuilder () inline virtual
Definition at line 56 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4BinaryPiKBuilder.hh
Member Function Documentation
virtual void G4BinaryPiKBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPiKBuilder.
Definition at line 58 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BinaryPiKBuilder.hh
void G4BinaryPiKBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 59 of file G4BinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 59 of file G4BinaryPiKBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4BinaryPiKBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPiKBuilder.
Definition at line 68 of file G4BinaryPiKBuilder.cc.
View newest version in sPHENIX GitHub at line 68 of file G4BinaryPiKBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4BinaryPiKBuilder::Build (G4KaonPlusInelasticProcess *) inline final override virtual
Implements G4VPiKBuilder.
Definition at line 61 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryPiKBuilder.hh
virtual void G4BinaryPiKBuilder::Build (G4KaonMinusInelasticProcess *) inline final override virtual
Implements G4VPiKBuilder.
Definition at line 62 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BinaryPiKBuilder.hh
virtual void G4BinaryPiKBuilder::Build (G4KaonZeroLInelasticProcess *) inline final override virtual
Implements G4VPiKBuilder.
Definition at line 63 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4BinaryPiKBuilder.hh
virtual void G4BinaryPiKBuilder::Build (G4KaonZeroSInelasticProcess *) inline final override virtual
Implements G4VPiKBuilder.
Definition at line 64 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BinaryPiKBuilder.hh
virtual void G4BinaryPiKBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 67 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4BinaryPiKBuilder.hh
References theMax.
virtual void G4BinaryPiKBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 66 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4BinaryPiKBuilder.hh
References theMin.
Member Data Documentation
G4double G4BinaryPiKBuilder::theMax private
Definition at line 74 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4BinaryPiKBuilder.hh
Referenced by Build(), G4BinaryPiKBuilder(), and SetMaxEnergy().
G4double G4BinaryPiKBuilder::theMin private
Definition at line 73 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4BinaryPiKBuilder.hh
Referenced by Build(), G4BinaryPiKBuilder(), and SetMinEnergy().
G4BinaryCascade* G4BinaryPiKBuilder::theModel private
Definition at line 72 of file G4BinaryPiKBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BinaryPiKBuilder.hh
Referenced by Build(), and G4BinaryPiKBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BinaryPiKBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4BinaryPiKBuilder.cc