ECCE @ EIC Software: G4GeometryCellStep Class Reference
G4GeometryCellStep Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4GeometryCellStep.hh>
Public Member Functions
G4GeometryCellStep (const G4GeometryCell &preCell, const G4GeometryCell &postCell)
~G4GeometryCellStep ()
const G4GeometryCell & GetPreGeometryCell () const
const G4GeometryCell & GetPostGeometryCell () const
G4bool GetCrossBoundary () const
void SetPreGeometryCell (const G4GeometryCell &preCell)
void SetPostGeometryCell (const G4GeometryCell &postCell)
void SetCrossBoundary (G4bool b)
Private Attributes
G4GeometryCell fPreGeometryCell
G4GeometryCell fPostGeometryCell
G4bool fCrossBoundary = false
Detailed Description
Definition at line 47 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 47 of file G4GeometryCellStep.hh
Constructor & Destructor Documentation
G4GeometryCellStep::G4GeometryCellStep (const G4GeometryCell & preCell, const G4GeometryCell & postCell)
Definition at line 33 of file G4GeometryCellStep.cc.
View newest version in sPHENIX GitHub at line 33 of file G4GeometryCellStep.cc
G4GeometryCellStep::~G4GeometryCellStep ()
Definition at line 39 of file G4GeometryCellStep.cc.
View newest version in sPHENIX GitHub at line 39 of file G4GeometryCellStep.cc
Member Function Documentation
G4bool G4GeometryCellStep::GetCrossBoundary () const inline
Definition at line 113 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 113 of file G4GeometryCellStep.hh
References fCrossBoundary.
Referenced by operator<<().
const G4GeometryCell & G4GeometryCellStep::GetPostGeometryCell () const inline
Definition at line 107 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 107 of file G4GeometryCellStep.hh
References fPostGeometryCell.
Referenced by operator<<().
const G4GeometryCell & G4GeometryCellStep::GetPreGeometryCell () const inline
Definition at line 101 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 101 of file G4GeometryCellStep.hh
References fPreGeometryCell.
Referenced by operator<<().
void G4GeometryCellStep::SetCrossBoundary (G4bool b) inline
Definition at line 95 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 95 of file G4GeometryCellStep.hh
References b, and fCrossBoundary.
void G4GeometryCellStep::SetPostGeometryCell (const G4GeometryCell & postCell) inline
Definition at line 89 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 89 of file G4GeometryCellStep.hh
References fPostGeometryCell.
void G4GeometryCellStep::SetPreGeometryCell (const G4GeometryCell & preCell) inline
Definition at line 83 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 83 of file G4GeometryCellStep.hh
References fPreGeometryCell.
Member Data Documentation
G4bool G4GeometryCellStep::fCrossBoundary = false private
Definition at line 77 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 77 of file G4GeometryCellStep.hh
Referenced by GetCrossBoundary(), and SetCrossBoundary().
G4GeometryCell G4GeometryCellStep::fPostGeometryCell private
Definition at line 76 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GeometryCellStep.hh
Referenced by GetPostGeometryCell(), and SetPostGeometryCell().
G4GeometryCell G4GeometryCellStep::fPreGeometryCell private
Definition at line 75 of file G4GeometryCellStep.hh.
View newest version in sPHENIX GitHub at line 75 of file G4GeometryCellStep.hh
Referenced by GetPreGeometryCell(), and SetPreGeometryCell().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4GeometryCellStep.hh
geant4/tree/geant4-10.6-release/source/geometry/biasing/src/G4GeometryCellStep.cc