ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/ptwXY.h File Reference
ptwXY.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <nf_utilities.h>
#include <ptwX.h>
Classes
struct ptwXYPoint_s
struct ptwXY_interpolationOtherInfo
struct ptwXYOverflowPoint_s
struct ptwXYPoints_s
Macros
#define ptwXY_minimumSize 10 /* This must be > 0 otherwise some logic will fail. */
#define ptwXY_minimumOverflowSize 4 /* This must be > 0 otherwise some logic will fail. */
#define ptwXY_maxBiSectionMax 20
#define ptwXY_minAccuracy 1e-14
#define ptwXY_sectionSubdivideMax 1 << 16
#define ClosestAllowXFactor 10
#define ptwXY_union_fill 1 /* If filling, union is filled with y value of first ptw. */
#define ptwXY_union_trim 2 /* If trimming, union in only over common domain of ptw1 and ptw2. */
#define ptwXY_union_mergeClosePoints 4 /* If true, union calls ptwXY_mergeClosePoints with eps = 4 * DBL_EPSILON. */
Typedefs
typedef enum ptwXY_dataFrom_e ptwXY_dataFrom
typedef enum ptwXY_group_normType_e ptwXY_group_normType
typedef enum ptwXY_sigma_e ptwXY_sigma
typedef enum ptwXY_interpolation_e ptwXY_interpolation
typedef enum
ptwXY_lessEqualGreaterX_e ptwXY_lessEqualGreaterX
typedef struct ptwXYPoint_s ptwXYPoint
typedef nfu_status(* ptwXY_createFromFunction_callback)(double x, double *y, void *argList)
typedef nfu_status(* ptwXY_applyFunction_callback)(ptwXYPoint *point, void *argList)
typedef nfu_status(* ptwXY_getValue_callback)(void *argList, double x, double *y, double x1, double y1, double x2, double y2)
typedef struct ptwXYOverflowPoint_s ptwXYOverflowPoint
typedef struct ptwXYPoints_s ptwXYPoints
Enumerations
enum ptwXY_dataFrom_e { ptwXY_dataFrom_Unknown, ptwXY_dataFrom_Points, ptwXY_dataFrom_Overflow }
enum ptwXY_group_normType_e { ptwXY_group_normType_none, ptwXY_group_normType_dx, ptwXY_group_normType_norm }
enum ptwXY_sigma_e { ptwXY_sigma_none, ptwXY_sigma_plusMinus, ptwXY_sigma_Minus, ptwXY_sigma_plus }
enum ptwXY_interpolation_e {
ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog,
ptwXY_interpolationFlat, ptwXY_interpolationOther
}
enum ptwXY_lessEqualGreaterX_e {
ptwXY_lessEqualGreaterX_empty, ptwXY_lessEqualGreaterX_lessThan, ptwXY_lessEqualGreaterX_equal, ptwXY_lessEqualGreaterX_between,
ptwXY_lessEqualGreaterX_greater
}
Functions
ptwXYPoints * ptwXY_new (ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const *interpolationOtherInfo, double biSectionMax, double accuracy, int64_t primarySize, int64_t secondarySize, nfu_status *status, int userFlag)
nfu_status ptwXY_setup (ptwXYPoints *ptwXY, ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const *interpolationOtherInfo, double biSectionMax, double accuracy, int64_t primarySize, int64_t secondarySize, int userFlag)
ptwXYPoints * ptwXY_create (ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const *interpolationOtherInfo, double biSectionMax, double accuracy, int64_t primarySize, int64_t secondarySize, int64_t length, double const *xy, nfu_status *status, int userFlag)
ptwXYPoints * ptwXY_createFrom_Xs_Ys (ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const *interpolationOtherInfo, double biSectionMax, double accuracy, int64_t primarySize, int64_t secondarySize, int64_t length, double const *Xs, double const *Ys, nfu_status *status, int userFlag)
nfu_status ptwXY_copy (ptwXYPoints *dest, ptwXYPoints *src)
ptwXYPoints * ptwXY_clone (ptwXYPoints *ptwXY, nfu_status *status)
ptwXYPoints * ptwXY_cloneToInterpolation (ptwXYPoints *ptwXY, ptwXY_interpolation interpolationTo, nfu_status *status)
ptwXYPoints * ptwXY_slice (ptwXYPoints *ptwXY, int64_t index1, int64_t index2, int64_t secondarySize, nfu_status *status)
ptwXYPoints * ptwXY_xSlice (ptwXYPoints *ptwXY, double xMin, double xMax, int64_t secondarySize, int fill, nfu_status *status)
ptwXYPoints * ptwXY_xMinSlice (ptwXYPoints *ptwXY, double xMin, int64_t secondarySize, int fill, nfu_status *status)
ptwXYPoints * ptwXY_xMaxSlice (ptwXYPoints *ptwXY, double xMax, int64_t secondarySize, int fill, nfu_status *status)
ptwXY_interpolation ptwXY_getInterpolation (ptwXYPoints *ptwXY)
char const * ptwXY_getInterpolationString (ptwXYPoints *ptwXY)
nfu_status ptwXY_getStatus (ptwXYPoints *ptwXY)
int ptwXY_getUserFlag (ptwXYPoints *ptwXY)
void ptwXY_setUserFlag (ptwXYPoints *ptwXY, int userFlag)
double ptwXY_getAccuracy (ptwXYPoints *ptwXY)
double ptwXY_setAccuracy (ptwXYPoints *ptwXY, double accuracy)
double ptwXY_getBiSectionMax (ptwXYPoints *ptwXY)
double ptwXY_setBiSectionMax (ptwXYPoints *ptwXY, double biSectionMax)
nfu_status ptwXY_reallocatePoints (ptwXYPoints *ptwXY, int64_t size, int forceSmallerResize)
nfu_status ptwXY_reallocateOverflowPoints (ptwXYPoints *ptwXY, int64_t size)
nfu_status ptwXY_coalescePoints (ptwXYPoints *ptwXY, int64_t size, ptwXYPoint *newPoint, int forceSmallerResize)
nfu_status ptwXY_simpleCoalescePoints (ptwXYPoints *ptwXY)
nfu_status ptwXY_clear (ptwXYPoints *ptwXY)
nfu_status ptwXY_release (ptwXYPoints *ptwXY)
ptwXYPoints * ptwXY_free (ptwXYPoints *ptwXY)
int64_t ptwXY_length (ptwXYPoints *ptwXY)
int64_t ptwXY_getNonOverflowLength (ptwXYPoints const *ptwXY)
nfu_status ptwXY_setXYData (ptwXYPoints *ptwXY, int64_t length, double const *xy)
nfu_status ptwXY_setXYDataFromXsAndYs (ptwXYPoints *ptwXY, int64_t length, double const *x, double const *y)
nfu_status ptwXY_deletePoints (ptwXYPoints *ptwXY, int64_t i1, int64_t i2)
ptwXYPoint * ptwXY_getPointAtIndex (ptwXYPoints *ptwXY, int64_t index)
ptwXYPoint * ptwXY_getPointAtIndex_Unsafely (ptwXYPoints *ptwXY, int64_t index)
nfu_status ptwXY_getXYPairAtIndex (ptwXYPoints *ptwXY, int64_t index, double *x, double *y)
ptwXY_lessEqualGreaterX ptwXY_getPointsAroundX (ptwXYPoints *ptwXY, double x, ptwXYOverflowPoint *lessThanEqualXPoint, ptwXYOverflowPoint *greaterThanXPoint)
ptwXY_lessEqualGreaterX ptwXY_getPointsAroundX_closeIsEqual (ptwXYPoints *ptwXY, double x, ptwXYOverflowPoint *lessThanEqualXPoint, ptwXYOverflowPoint *greaterThanXPoint, double eps, int *closeIsEqual, ptwXYPoint **closePoint)
nfu_status ptwXY_getValueAtX (ptwXYPoints *ptwXY, double x, double *y)
nfu_status ptwXY_setValueAtX (ptwXYPoints *ptwXY, double x, double y)
nfu_status ptwXY_setValueAtX_overrideIfClose (ptwXYPoints *ptwXY, double x, double y, double eps, int override)
nfu_status ptwXY_mergeFromXsAndYs (ptwXYPoints *ptwXY, int length, double *xs, double *ys)
nfu_status ptwXY_mergeFromXYs (ptwXYPoints *ptwXY, int length, double *xys)
nfu_status ptwXY_appendXY (ptwXYPoints *ptwXY, double x, double y)
nfu_status ptwXY_setXYPairAtIndex (ptwXYPoints *ptwXY, int64_t index, double x, double y)
nfu_status ptwXY_getSlopeAtX (ptwXYPoints *ptwXY, double x, const char side, double *slope)
double ptwXY_getXMinAndFrom (ptwXYPoints *ptwXY, ptwXY_dataFrom *dataFrom)
double ptwXY_getXMin (ptwXYPoints *ptwXY)
double ptwXY_getXMaxAndFrom (ptwXYPoints *ptwXY, ptwXY_dataFrom *dataFrom)
double ptwXY_getXMax (ptwXYPoints *ptwXY)
double ptwXY_getYMin (ptwXYPoints *ptwXY)
double ptwXY_getYMax (ptwXYPoints *ptwXY)
nfu_status ptwXY_clip (ptwXYPoints *ptwXY1, double yMin, double yMax)
nfu_status ptwXY_thicken (ptwXYPoints *ptwXY1, int sectionSubdivideMax, double dxMax, double fxMax)
ptwXYPoints * ptwXY_thin (ptwXYPoints *ptwXY1, double accuracy, nfu_status *status)
nfu_status ptwXY_trim (ptwXYPoints *ptwXY)
ptwXYPoints * ptwXY_union (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status, int unionOptions)
nfu_status ptwXY_scaleOffsetXAndY (ptwXYPoints *ptwXY, double xScale, double xOffset, double yScale, double yOffset)
nfu_status ptwXY_abs (ptwXYPoints *ptwXY)
nfu_status ptwXY_neg (ptwXYPoints *ptwXY)
nfu_status ptwXY_slopeOffset (ptwXYPoints *ptwXY, double slope, double offset)
nfu_status ptwXY_add_double (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_sub_doubleFrom (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_sub_fromDouble (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_mul_double (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_div_doubleFrom (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_div_fromDouble (ptwXYPoints *ptwXY, double value)
nfu_status ptwXY_mod (ptwXYPoints *ptwXY, double m, int pythonMod)
ptwXYPoints * ptwXY_binary_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, double v1, double v2, double v1v2, nfu_status *status)
ptwXYPoints * ptwXY_add_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_sub_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_mul_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_mul2_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_div_ptwXY (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status, int safeDivide)
nfu_status ptwXY_pow (ptwXYPoints *ptwXY, double p)
nfu_status ptwXY_exp (ptwXYPoints *ptwXY, double a)
ptwXYPoints * ptwXY_convolution (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status, int mode)
nfu_status ptwXY_interpolatePoint (ptwXY_interpolation interpolation, double x, double *y, double x1, double y1, double x2, double y2)
ptwXYPoints * ptwXY_flatInterpolationToLinear (ptwXYPoints *ptwXY, double lowerEps, double upperEps, nfu_status *status)
ptwXYPoints * ptwXY_toOtherInterpolation (ptwXYPoints *ptwXY, ptwXY_interpolation interpolation, double accuracy, nfu_status *status)
ptwXYPoints * ptwXY_unitbaseInterpolate (double w, double w1, ptwXYPoints *ptwXY1, double w2, ptwXYPoints *ptwXY2, nfu_status *status)
ptwXYPoints * ptwXY_toUnitbase (ptwXYPoints *ptwXY, nfu_status *status)
ptwXYPoints * ptwXY_fromUnitbase (ptwXYPoints *ptwXY, double xMin, double xMax, nfu_status *status)
ptwXPoints * ptwXY_getXArray (ptwXYPoints *ptwXY, nfu_status *status)
nfu_status ptwXY_dullEdges (ptwXYPoints *ptwXY, double lowerEps, double upperEps, int positiveXOnly)
nfu_status ptwXY_mergeClosePoints (ptwXYPoints *ptwXY, double epsilon)
ptwXYPoints * ptwXY_intersectionWith_ptwX (ptwXYPoints *ptwXY, ptwXPoints *ptwX, nfu_status *status)
nfu_status ptwXY_areDomainsMutual (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2)
nfu_status ptwXY_tweakDomainsToMutualify (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, int epsilonFactor, double epsilon)
nfu_status ptwXY_mutualifyDomains (ptwXYPoints *ptwXY1, double lowerEps1, double upperEps1, int positiveXOnly1, ptwXYPoints *ptwXY2, double lowerEps2, double upperEps2, int positiveXOnly2)
nfu_status ptwXY_copyToC_XY (ptwXYPoints *ptwXY, int64_t index1, int64_t index2, int64_t allocatedSize, int64_t *numberOfPoints, double *xy)
nfu_status ptwXY_valueTo_ptwXAndY (ptwXYPoints *ptwXY, double **xs, double **ys)
ptwXYPoints * ptwXY_valueTo_ptwXY (double x1, double x2, double y, nfu_status *status)
ptwXYPoints * ptwXY_createGaussianCenteredSigma1 (double accuracy, nfu_status *status)
ptwXYPoints * ptwXY_createGaussian (double accuracy, double xCenter, double sigma, double amplitude, double xMin, double xMax, double dullEps, nfu_status *status)
void ptwXY_update_biSectionMax (ptwXYPoints *ptwXY1, double oldLength)
ptwXYPoints * ptwXY_createFromFunction (int n, double *xs, ptwXY_createFromFunction_callback func, void *argList, double accuracy, int checkForRoots, int biSectionMax, nfu_status *status)
ptwXYPoints * ptwXY_createFromFunction2 (ptwXPoints *xs, ptwXY_createFromFunction_callback func, void *argList, double accuracy, int checkForRoots, int biSectionMax, nfu_status *status)
nfu_status ptwXY_applyFunction (ptwXYPoints *ptwXY1, ptwXY_applyFunction_callback func, void *argList, int checkForRoots)
ptwXYPoints * ptwXY_fromString (char const *str, ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const *interpolationOtherInfo, double biSectionMax, double accuracy, char **endCharacter, nfu_status *status)
void ptwXY_showInteralStructure (ptwXYPoints *ptwXY, FILE *f, int printPointersAsNull)
void ptwXY_simpleWrite (ptwXYPoints *ptwXY, FILE *f, char *format)
void ptwXY_simplePrint (ptwXYPoints *ptwXY, char *format)
nfu_status ptwXY_f_integrate (ptwXY_interpolation interpolation, double x1, double y1, double x2, double y2, double *value)
double ptwXY_integrate (ptwXYPoints *ptwXY, double xMin, double xMax, nfu_status *status)
double ptwXY_integrateDomain (ptwXYPoints *ptwXY, nfu_status *status)
nfu_status ptwXY_normalize (ptwXYPoints *ptwXY1)
double ptwXY_integrateDomainWithWeight_x (ptwXYPoints *ptwXY, nfu_status *status)
double ptwXY_integrateWithWeight_x (ptwXYPoints *ptwXY, double xMin, double xMax, nfu_status *status)
double ptwXY_integrateDomainWithWeight_sqrt_x (ptwXYPoints *ptwXY, nfu_status *status)
double ptwXY_integrateWithWeight_sqrt_x (ptwXYPoints *ptwXY, double xMin, double xMax, nfu_status *status)
ptwXPoints * ptwXY_groupOneFunction (ptwXYPoints *ptwXY, ptwXPoints *groupBoundaries, ptwXY_group_normType normType, ptwXPoints *ptwX_norm, nfu_status *status)
ptwXPoints * ptwXY_groupTwoFunctions (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, ptwXPoints *groupBoundaries, ptwXY_group_normType normType, ptwXPoints *ptwX_norm, nfu_status *status)
ptwXPoints * ptwXY_groupThreeFunctions (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, ptwXYPoints *ptwXY3, ptwXPoints *groupBoundaries, ptwXY_group_normType normType, ptwXPoints *ptwX_norm, nfu_status *status)
ptwXPoints * ptwXY_runningIntegral (ptwXYPoints *ptwXY, nfu_status *status)
double ptwXY_integrateWithFunction (ptwXYPoints *ptwXY, ptwXY_createFromFunction_callback func, void *argList, double xMin, double xMax, int degree, int recursionLimit, double tolerance, nfu_status *status)
Macro Definition Documentation
#define ClosestAllowXFactor 10
Definition at line 25 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 25 of file ptwXY.h
Referenced by ptwXY_applyFunction2(), ptwXY_createFromFunction(), ptwXY_createFromFunctionBisect(), ptwXY_div_s_ptwXY(), and ptwXY_mul2_s_ptwXY().
#define ptwXY_maxBiSectionMax 20
Definition at line 22 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 22 of file ptwXY.h
Referenced by ptwXY_setBiSectionMax(), ptwXY_setup(), ptwXY_update_biSectionMax(), and ptwXY_valueTo_ptwXY().
#define ptwXY_minAccuracy 1e-14
Definition at line 23 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 23 of file ptwXY.h
Referenced by ptwXY_setAccuracy(), ptwXY_setup(), and ptwXY_valueTo_ptwXY().
#define ptwXY_minimumOverflowSize 4 /* This must be > 0 otherwise some logic will fail. */
Definition at line 21 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 21 of file ptwXY.h
Referenced by ptwXY_reallocateOverflowPoints().
#define ptwXY_minimumSize 10 /* This must be > 0 otherwise some logic will fail. */
Definition at line 20 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 20 of file ptwXY.h
Referenced by ptwXY_reallocatePoints(), and ptwXY_union().
#define ptwXY_sectionSubdivideMax 1 << 16
Definition at line 24 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 24 of file ptwXY.h
Referenced by ptwXY_thicken().
#define ptwXY_union_fill 1 /* If filling, union is filled with y value of first ptw. */
Definition at line 31 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 31 of file ptwXY.h
Referenced by ptwXY_binary_ptwXY(), ptwXY_div_ptwXY(), ptwXY_div_ptwXY_forFlats(), ptwXY_groupThreeFunctions(), ptwXY_groupTwoFunctions(), and ptwXY_union().
#define ptwXY_union_mergeClosePoints 4 /* If true, union calls ptwXY_mergeClosePoints with eps = 4 * DBL_EPSILON. */
Definition at line 33 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 33 of file ptwXY.h
Referenced by ptwXY_binary_ptwXY(), ptwXY_div_ptwXY(), ptwXY_div_ptwXY_forFlats(), and ptwXY_union().
#define ptwXY_union_trim 2 /* If trimming, union in only over common domain of ptw1 and ptw2. */
Definition at line 32 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 32 of file ptwXY.h
Referenced by ptwXY_union().
Typedef Documentation
typedef nfu_status(* ptwXY_applyFunction_callback)(ptwXYPoint *point, void *argList)
Definition at line 66 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 66 of file ptwXY.h
typedef nfu_status(* ptwXY_createFromFunction_callback)(double x, double *y, void *argList)
Definition at line 65 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 65 of file ptwXY.h
typedef enum ptwXY_dataFrom_e ptwXY_dataFrom
typedef nfu_status(* ptwXY_getValue_callback)(void *argList, double x, double *y, double x1, double y1, double x2, double y2)
Definition at line 67 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 67 of file ptwXY.h
typedef enum ptwXY_group_normType_e ptwXY_group_normType
typedef enum ptwXY_interpolation_e ptwXY_interpolation
typedef enum ptwXY_lessEqualGreaterX_e ptwXY_lessEqualGreaterX
typedef enum ptwXY_sigma_e ptwXY_sigma
typedef struct ptwXYOverflowPoint_s ptwXYOverflowPoint
typedef struct ptwXYPoint_s ptwXYPoint
typedef struct ptwXYPoints_s ptwXYPoints
Enumeration Type Documentation
enum ptwXY_dataFrom_e
Enumerator:
ptwXY_dataFrom_Unknown
ptwXY_dataFrom_Points
ptwXY_dataFrom_Overflow
Definition at line 27 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 27 of file ptwXY.h
enum ptwXY_group_normType_e
Enumerator:
ptwXY_group_normType_none
ptwXY_group_normType_dx
ptwXY_group_normType_norm
Definition at line 28 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 28 of file ptwXY.h
enum ptwXY_interpolation_e
Enumerator:
ptwXY_interpolationLinLin
ptwXY_interpolationLinLog
ptwXY_interpolationLogLin
ptwXY_interpolationLogLog
ptwXY_interpolationFlat
ptwXY_interpolationOther
Definition at line 35 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 35 of file ptwXY.h
enum ptwXY_lessEqualGreaterX_e
Enumerator:
ptwXY_lessEqualGreaterX_empty
ptwXY_lessEqualGreaterX_lessThan
ptwXY_lessEqualGreaterX_equal
ptwXY_lessEqualGreaterX_between
ptwXY_lessEqualGreaterX_greater
Definition at line 57 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 57 of file ptwXY.h
enum ptwXY_sigma_e
Enumerator:
ptwXY_sigma_none
ptwXY_sigma_plusMinus
ptwXY_sigma_Minus
ptwXY_sigma_plus
Definition at line 34 of file ptwXY.h.
View newest version in sPHENIX GitHub at line 34 of file ptwXY.h
Function Documentation
nfu_status ptwXY_abs (ptwXYPoints * ptwXY)
Definition at line 19 of file ptwXY_unitaryOperators.cc.
View newest version in sPHENIX GitHub at line 19 of file ptwXY_unitaryOperators.cc
References ptwXYOverflowPoint_s::next, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
nfu_status ptwXY_add_double (ptwXYPoints * ptwXY, double value)
Definition at line 40 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 40 of file ptwXY_binaryOperators.cc
References ptwXY_slopeOffset().
Referenced by MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
ptwXYPoints* ptwXY_add_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 138 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 138 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::length, ptwXY_binary_ptwXY(), ptwXY_clone(), and sum.
Referenced by MCGIDI_target_heated_read(), and ptwXY_unitbaseInterpolate().
nfu_status ptwXY_appendXY (ptwXYPoints * ptwXY, double x, double y)
Definition at line 1062 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1062 of file ptwXY_core.cc
References ptwXYOverflowPoint_s::index, ptwXYPoints_s::length, ptwXYOverflowPoint_s::next, nfu_Okay, nfu_XNotAscending, ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYPoints_s::overflowPoints, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXYOverflowPoint_s::prior, ptwXY_coalescePoints(), ptwXY_getNonOverflowLength(), ptwXY_getXMaxAndFrom(), ptwXYPoint_s::x, x, ptwXYPoint_s::y, and y.
nfu_status ptwXY_applyFunction (ptwXYPoints * ptwXY1, ptwXY_applyFunction_callback func, void * argList, int checkForRoots)
Definition at line 146 of file ptwXY_misc.cc.
View newest version in sPHENIX GitHub at line 146 of file ptwXY_misc.cc
References ptwXYPoints_s::biSectionMax, func, ptwXYPoints_s::interpolation, ptwXYPoints_s::length, nfu_invalidInterpolation, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_applyFunction2(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_simpleCoalescePoints(), ptwXY_update_biSectionMax(), ptwXYPoints_s::status, ptwXYPoint_s::y, y1, and y2.
Referenced by ptwXY_pow().
nfu_status ptwXY_areDomainsMutual (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2)
Definition at line 257 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 257 of file ptwXY_convenient.cc
References ptwXYPoints_s::length, n1, nfu_domainsNotMutual, nfu_empty, nfu_Okay, nfu_tooFewPoints, ptwXY_getPointAtIndex_Unsafely(), ptwXYPoints_s::status, ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by ptwXY_binary_ptwXY(), ptwXY_div_ptwXY(), and ptwXY_mutualifyDomains().
ptwXYPoints* ptwXY_binary_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, double v1, double v2, double v1v2, nfu_status * status)
Definition at line 108 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 108 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, BTOF::length, n, nfu_invalidInterpolation, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_areDomainsMutual(), ptwXY_free(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_union(), ptwXY_union_fill, ptwXY_union_mergeClosePoints, ptwXYPoint_s::x, ptwXYPoint_s::y, and y.
Referenced by ptwXY_add_ptwXY(), ptwXY_mul_ptwXY(), and ptwXY_sub_ptwXY().
nfu_status ptwXY_clear (ptwXYPoints * ptwXY)
Definition at line 536 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 536 of file ptwXY_core.cc
References ptwXYPoints_s::length, ptwXYOverflowPoint_s::next, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYOverflowPoint_s::prior, and ptwXYPoints_s::status.
Referenced by ptwXY_clip(), ptwXY_copy(), and ptwXY_setXYDataFromXsAndYs().
nfu_status ptwXY_clip (ptwXYPoints * ptwXY1, double yMin, double yMax)
Definition at line 25 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 25 of file ptwXY_methods.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::allocatedSize, ptwXYPoints_s::biSectionMax, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, ptwXYPoints_s::length, n, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_clear(), ptwXY_clip2(), ptwXY_free(), ptwXY_getPointAtIndex_Unsafely(), ptwXY_getYMax(), ptwXY_getYMin(), ptwXY_interpolationOther, ptwXY_new(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, ptwXYPoints_s::userFlag, ptwXYPoint_s::x, x2, ptwXYPoint_s::y, and y2.
ptwXYPoints* ptwXY_clone (ptwXYPoints * ptwXY, nfu_status * status)
Definition at line 208 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 208 of file ptwXY_core.cc
References ptwXYPoints_s::length, ptwXYPoints_s::overflowAllocatedSize, and ptwXY_slice().
Referenced by GIDI_settings_processedFlux::GIDI_settings_processedFlux(), GIDI_settings_processedFlux::operator=(), ptwXY_add_ptwXY(), ptwXY_cloneToInterpolation(), ptwXY_fromUnitbase(), ptwXY_intersectionWith_ptwX(), ptwXY_mul_ptwXY(), ptwXY_sub_ptwXY(), ptwXY_thin(), ptwXY_toOtherInterpolation(), ptwXY_toUnitbase(), ptwXY_unitbaseInterpolate(), and ptwXY_xSlice().
ptwXYPoints* ptwXY_cloneToInterpolation (ptwXYPoints * ptwXY, ptwXY_interpolation interpolationTo, nfu_status * status)
Definition at line 215 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 215 of file ptwXY_core.cc
References ptwXY_interpolationOtherInfo::argList, flatInterpolationString, ptwXY_interpolationOtherInfo::getValueFunc, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, ptwXY_interpolationOtherInfo::interpolationString, linLinInterpolationString, linLogInterpolationString, logLinInterpolationString, logLogInterpolationString, n1, nfu_free(), nfu_otherInterpolation, ptwXY_clone(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, and ptwXY_interpolationOther.
Referenced by ptwXY_toOtherInterpolation().
nfu_status ptwXY_coalescePoints (ptwXYPoints * ptwXY, int64_t size, ptwXYPoint * newPoint, int forceSmallerResize)
Definition at line 469 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 469 of file ptwXY_core.cc
References ptwXYPoints_s::allocatedSize, BTOF::length, ptwXYPoints_s::length, ptwXYOverflowPoint_s::next, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXYOverflowPoint_s::prior, ptwXY_getNonOverflowLength(), ptwXY_reallocatePoints(), ptwXYPoints_s::status, and ptwXYPoint_s::x.
Referenced by ptwXY_appendXY(), ptwXY_createGaussianCenteredSigma1(), ptwXY_reallocateOverflowPoints(), ptwXY_setValueAtX_overrideIfClose(), ptwXY_simpleCoalescePoints(), and ptwXY_xSlice().
ptwXYPoints* ptwXY_convolution (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status, int mode)
Definition at line 96 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 96 of file ptwXY_functions.cc
References ptwXYPoints_s::accuracy, c, dy, f1, f2, ptwXYPoints_s::interpolation, ptwXYPoints_s::length, n, n1, nfu_Okay, nfu_tooFewPoints, nfu_unsupportedInterpolation, ptwXYPoints_s::points, ptwXY_convolution2(), ptwXY_convolution3(), ptwXY_free(), ptwXY_interpolationLinLin, ptwXY_new(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXYPoint_s::x, and y.
nfu_status ptwXY_copy (ptwXYPoints * dest, ptwXYPoints * src)
Definition at line 148 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 148 of file ptwXY_core.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::allocatedSize, ptwXY_interpolationOtherInfo::argList, ptwXYPoints_s::biSectionMax, ptwXY_interpolationOtherInfo::getValueFunc, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, ptwXY_interpolationOtherInfo::interpolationString, ptwXYPoints_s::length, ptwXYPoints_s::minFractional_dx, ptwXYOverflowPoint_s::next, nfu_free(), nfu_mallocError, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_clear(), ptwXY_getNonOverflowLength(), ptwXY_interpolationLinLin, ptwXY_interpolationOther, ptwXY_reallocatePoints(), ptwXYPoints_s::status, ptwXYPoints_s::userFlag, and ptwXYPoint_s::x.
nfu_status ptwXY_copyToC_XY (ptwXYPoints * ptwXY, int64_t index1, int64_t index2, int64_t allocatedSize, int64_t * numberOfPoints, double * xy)
Definition at line 424 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 424 of file ptwXY_convenient.cc
References d, Acts::index1, ptwXYPoints_s::length, nfu_insufficientMemory, nfu_Okay, ptwXYPoints_s::points, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, ptwXYPoint_s::x, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_create (ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const * interpolationOtherInfo, double biSectionMax, double accuracy, int64_t primarySize, int64_t secondarySize, int64_t length, double const * xy, nfu_status * status, int userFlag)
Definition at line 108 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 108 of file ptwXY_core.cc
References BTOF::length, nfu_Okay, ptwXY_free(), ptwXY_new(), and ptwXY_setXYData().
Referenced by MCGIDI_misc_Data2ptwXYPointsInUnitsOf(), MCGIDI_target_heated_read(), and ptwXY_fromString().
ptwXYPoints* ptwXY_createFrom_Xs_Ys (ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const * interpolationOtherInfo, double biSectionMax, double accuracy, int64_t primarySize, int64_t secondarySize, int64_t length, double const * Xs, double const * Ys, nfu_status * status, int userFlag)
Definition at line 126 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 126 of file ptwXY_core.cc
References BTOF::length, ptwXYPoints_s::length, ptwXYPoints_s::points, ptwXY_new(), ptwXYPoint_s::x, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_createFromFunction (int n, double * xs, ptwXY_createFromFunction_callback func, void * argList, double accuracy, int checkForRoots, int biSectionMax, nfu_status * status)
Definition at line 40 of file ptwXY_misc.cc.
View newest version in sPHENIX GitHub at line 40 of file ptwXY_misc.cc
References ClosestAllowXFactor, DBL_EPSILON, eps, check_license::err(), func, ptwXYPoints_s::length, n, nfu_Okay, nfu_tooFewPoints, nfu_XNotAscending, ptwXYPoints_s::points, ptwXY_createFromFunctionBisect(), ptwXY_createFromFunctionZeroCrossing(), ptwXY_free(), ptwXY_interpolationLinLin, ptwXY_new(), ptwXY_setValueAtX_overrideIfClose(), ptwXY_simpleCoalescePoints(), ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y1, and y2.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), nf_Legendre_to_ptwXY(), and ptwXY_createFromFunction2().
ptwXYPoints* ptwXY_createFromFunction2 (ptwXPoints * xs, ptwXY_createFromFunction_callback func, void * argList, double accuracy, int checkForRoots, int biSectionMax, nfu_status * status)
Definition at line 89 of file ptwXY_misc.cc.
View newest version in sPHENIX GitHub at line 89 of file ptwXY_misc.cc
References ptwXPoints_s::length, ptwXPoints_s::points, and ptwXY_createFromFunction().
ptwXYPoints* ptwXY_createGaussian (double accuracy, double xCenter, double sigma, double amplitude, double xMin, double xMax, double dullEps, nfu_status * status)
Definition at line 566 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 566 of file ptwXY_convenient.cc
References BTOF::length, ptwXYPoints_s::length, ptwXYPoints_s::points, ptwXY_createGaussianCenteredSigma1(), ptwXY_free(), ptwXY_xSlice(), ptwXYPoint_s::x, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_createGaussianCenteredSigma1 (double accuracy, nfu_status * status)
Definition at line 492 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 492 of file ptwXY_convenient.cc
References ptwXYPoints_s::accuracy, e, G4Exp(), G4Log(), ptwXYPoints_s::length, n, nfu_Okay, Acts::UnitConstants::pm, ptwXYPoints_s::points, G4InuclParticleNames::pp, ptwXY_coalescePoints(), ptwXY_createGaussianCenteredSigma1_2(), ptwXY_free(), ptwXY_interpolationLinLin, ptwXY_new(), ptwXY_setValueAtX(), x1, x2, y1, and y2.
Referenced by ptwXY_createGaussian().
nfu_status ptwXY_deletePoints (ptwXYPoints * ptwXY, int64_t i1, int64_t i2)
Definition at line 660 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 660 of file ptwXY_core.cc
References ptwXYPoints_s::length, n, nfu_badIndex, nfu_Okay, ptwXYPoints_s::points, ptwXY_simpleCoalescePoints(), and ptwXYPoints_s::status.
nfu_status ptwXY_div_doubleFrom (ptwXYPoints * ptwXY, double value)
Definition at line 44 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 44 of file ptwXY_binaryOperators.cc
References nfu_divByZero, ptwXY_slopeOffset(), and ptwXYPoints_s::status.
nfu_status ptwXY_div_fromDouble (ptwXYPoints * ptwXY, double value)
Definition at line 53 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 53 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, ptwXYOverflowPoint_s::next, nfu_divByZero, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXY_interpolationOther, ptwXYPoints_s::status, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_div_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status, int safeDivide)
Definition at line 288 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 288 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, k, BTOF::length, ptwXYPoints_s::length, n, nfu_divByZero, nfu_getNAN(), nfu_isNAN(), nfu_Okay, nfu_otherInterpolation, nfu_XOutsideDomain, ptwXYPoints_s::points, ptwXY_areDomainsMutual(), ptwXY_div_ptwXY_forFlats(), ptwXY_div_s_ptwXY(), ptwXY_free(), ptwXY_getSlopeAtX(), ptwXY_getValueAtX(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXY_union(), ptwXY_union_fill, ptwXY_union_mergeClosePoints, ptwXY_update_biSectionMax(), s1, v1, v2, ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
nfu_status ptwXY_dullEdges (ptwXYPoints * ptwXY, double lowerEps, double upperEps, int positiveXOnly)
Definition at line 42 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 42 of file ptwXY_convenient.cc
References dx, ptwXYPoints_s::interpolation, ptwXYPoints_s::length, minEps, nfu_invalidInterpolation, nfu_Okay, nfu_otherInterpolation, ptwXY_getPointAtIndex_Unsafely(), ptwXY_getValueAtX(), ptwXY_interpolatePoint(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_setValueAtX(), sign(), ptwXYPoints_s::status, ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
Referenced by MCGIDI_reaction_fixDomains(), and ptwXY_mutualifyDomains().
nfu_status ptwXY_exp (ptwXYPoints * ptwXY, double a)
Definition at line 43 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 43 of file ptwXY_functions.cc
References G4Exp(), ptwXYPoints_s::interpolation, BTOF::length, ptwXYPoints_s::length, nfu_invalidInterpolation, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_exp_s(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y1, y2, z1, and z2.
nfu_status ptwXY_f_integrate (ptwXY_interpolation interpolation, double x1, double y1, double x2, double y2, double * value)
Definition at line 34 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 34 of file ptwXY_integration.cc
References a, e, f, G4Log(), G4Pow::GetInstance(), int(), n, nfu_badIntegrationInput, nfu_Okay, nfu_otherInterpolation, G4Pow::powA(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, ptwXY_interpolationOther, r, x1, y1, y2, and z.
Referenced by ptwXY_integrate(), and ptwXY_runningIntegral().
ptwXYPoints* ptwXY_flatInterpolationToLinear (ptwXYPoints * ptwXY, double lowerEps, double upperEps, nfu_status * status)
Definition at line 74 of file ptwXY_interpolation.cc.
View newest version in sPHENIX GitHub at line 74 of file ptwXY_interpolation.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, ptwXYPoints_s::interpolation, BTOF::length, ptwXYPoints_s::length, minEps, n, nfu_badInput, nfu_invalidInterpolation, nfu_Okay, ptwXYPoints_s::overflowLength, ptwXYPoints_s::points, ptwXY_flatInterpolationToLinear_eps(), ptwXY_free(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_new(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXYPoints_s::userFlag, ptwXYPoint_s::x, x, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_free (ptwXYPoints * ptwXY)
Definition at line 574 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 574 of file ptwXY_core.cc
References nfu_free(), and ptwXY_release().
Referenced by GIDI_settings_processedFlux::GIDI_settings_processedFlux(), GIDI_settings_processedFlux::groupFunction(), MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_energy_release(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM(), MCGIDI_misc_Data2ptwXYPointsInUnitsOf(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parsePolynomialMultiplicity(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), MCGIDI_product_release(), MCGIDI_reaction_release(), MCGIDI_target_heated_read(), MCGIDI_target_heated_release(), GIDI_settings_processedFlux::operator=(), ptwXY_binary_ptwXY(), ptwXY_clip(), ptwXY_convolution(), ptwXY_create(), ptwXY_createFromFunction(), ptwXY_createGaussian(), ptwXY_createGaussianCenteredSigma1(), ptwXY_div_ptwXY(), ptwXY_div_ptwXY_forFlats(), ptwXY_flatInterpolationToLinear(), ptwXY_groupOneFunction(), ptwXY_groupThreeFunctions(), ptwXY_groupTwoFunctions(), ptwXY_intersectionWith_ptwX(), ptwXY_mul2_ptwXY(), ptwXY_sub_ptwXY(), ptwXY_thin(), ptwXY_toOtherInterpolation(), ptwXY_union(), ptwXY_unitbaseInterpolate(), ptwXY_xSlice(), and GIDI_settings_processedFlux::~GIDI_settings_processedFlux().
ptwXYPoints* ptwXY_fromString (char const * str, ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const * interpolationOtherInfo, double biSectionMax, double accuracy, char ** endCharacter, nfu_status * status)
Definition at line 236 of file ptwXY_misc.cc.
View newest version in sPHENIX GitHub at line 236 of file ptwXY_misc.cc
References nfu_free(), nfu_oddNumberOfValues, nfu_Okay, nfu_stringToListOfDoubles(), and ptwXY_create().
ptwXYPoints* ptwXY_fromUnitbase (ptwXYPoints * ptwXY, double xMin, double xMax, nfu_status * status)
Definition at line 331 of file ptwXY_interpolation.cc.
View newest version in sPHENIX GitHub at line 331 of file ptwXY_interpolation.cc
References DBL_EPSILON, dx, BTOF::length, ptwXYPoints_s::length, n, nfu_tooFewPoints, ptwXYPoints_s::points, ptwXY_clone(), ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by ptwXY_unitbaseInterpolate().
double ptwXY_getAccuracy (ptwXYPoints * ptwXY)
Definition at line 372 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 372 of file ptwXY_core.cc
References ptwXYPoints_s::accuracy.
double ptwXY_getBiSectionMax (ptwXYPoints * ptwXY)
Definition at line 390 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 390 of file ptwXY_core.cc
References ptwXYPoints_s::biSectionMax.
ptwXY_interpolation ptwXY_getInterpolation (ptwXYPoints * ptwXY)
Definition at line 337 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 337 of file ptwXY_core.cc
References ptwXYPoints_s::interpolation.
Referenced by MCGIDI_energy_parseGeneralEvaporationFromTOM().
char const* ptwXY_getInterpolationString (ptwXYPoints * ptwXY)
Definition at line 344 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 344 of file ptwXY_core.cc
References ptwXYPoints_s::interpolationOtherInfo, and ptwXY_interpolationOtherInfo::interpolationString.
int64_t ptwXY_getNonOverflowLength (ptwXYPoints const * ptwXY)
Definition at line 590 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 590 of file ptwXY_core.cc
References ptwXYPoints_s::length, and ptwXYPoints_s::overflowLength.
Referenced by ptwXY_abs(), ptwXY_appendXY(), ptwXY_coalescePoints(), ptwXY_copy(), ptwXY_div_fromDouble(), ptwXY_getPointsAroundX_closeIsEqual(), ptwXY_getXMaxAndFrom(), ptwXY_getXMinAndFrom(), ptwXY_getYMax(), ptwXY_getYMin(), ptwXY_mod(), ptwXY_neg(), ptwXY_setValueAtX_overrideIfClose(), ptwXY_showInteralStructure(), and ptwXY_slopeOffset().
ptwXYPoint* ptwXY_getPointAtIndex (ptwXYPoints * ptwXY, int64_t index)
Definition at line 675 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 675 of file ptwXY_core.cc
References ptwXYPoints_s::length, nfu_Okay, ptwXY_getPointAtIndex_Unsafely(), and ptwXYPoints_s::status.
Referenced by ptwXY_getXYPairAtIndex(), ptwXY_showInteralStructure(), and ptwXY_simpleWrite().
ptwXYPoint* ptwXY_getPointAtIndex_Unsafely (ptwXYPoints * ptwXY, int64_t index)
Definition at line 684 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 684 of file ptwXY_core.cc
References ptwXYOverflowPoint_s::index, ptwXYOverflowPoint_s::next, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, and ptwXYPoints_s::points.
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_KalbachMann_parseFromTOM2(), ptwXY_areDomainsMutual(), ptwXY_clip(), ptwXY_dullEdges(), ptwXY_getPointAtIndex(), ptwXY_getSlopeAtX(), ptwXY_mutualifyDomains(), and ptwXY_tweakDomainsToMutualify().
ptwXY_lessEqualGreaterX ptwXY_getPointsAroundX (ptwXYPoints * ptwXY, double x, ptwXYOverflowPoint * lessThanEqualXPoint, ptwXYOverflowPoint * greaterThanXPoint)
Definition at line 710 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 710 of file ptwXY_core.cc
References ptwXY_getPointsAroundX_closeIsEqual().
Referenced by ptwXY_convolution2(), ptwXY_getSlopeAtX(), and ptwXY_getValueAtX().
ptwXY_lessEqualGreaterX ptwXY_getPointsAroundX_closeIsEqual (ptwXYPoints * ptwXY, double x, ptwXYOverflowPoint * lessThanEqualXPoint, ptwXYOverflowPoint * greaterThanXPoint, double eps, int * closeIsEqual, ptwXYPoint ** closePoint)
Definition at line 720 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 720 of file ptwXY_core.cc
References ptwXYOverflowPoint_s::index, ptwXYPoints_s::length, ptwXYOverflowPoint_s::next, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXYOverflowPoint_s::prior, ptwXY_dataFrom_Points, ptwXY_getNonOverflowLength(), ptwXY_getXMaxAndFrom(), ptwXY_getXMinAndFrom(), ptwXY_initialOverflowPoint(), ptwXY_lessEqualGreaterX_between, ptwXY_lessEqualGreaterX_empty, ptwXY_lessEqualGreaterX_equal, ptwXY_lessEqualGreaterX_greater, ptwXY_lessEqualGreaterX_lessThan, ptwXYPoint_s::x, and x.
Referenced by ptwXY_getPointsAroundX(), and ptwXY_setValueAtX_overrideIfClose().
nfu_status ptwXY_getSlopeAtX (ptwXYPoints * ptwXY, double x, const char side, double * slope)
Definition at line 1139 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1139 of file ptwXY_core.cc
References ptwXYOverflowPoint_s::index, ptwXYPoints_s::length, nfu_badInput, nfu_Okay, nfu_XOutsideDomain, ptwXYOverflowPoint_s::point, ptwXY_getPointAtIndex_Unsafely(), ptwXY_getPointsAroundX(), ptwXY_lessEqualGreaterX_between, ptwXY_lessEqualGreaterX_empty, ptwXY_lessEqualGreaterX_equal, ptwXY_lessEqualGreaterX_greater, ptwXY_lessEqualGreaterX_lessThan, ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by ptwXY_div_ptwXY().
nfu_status ptwXY_getStatus (ptwXYPoints * ptwXY)
Definition at line 351 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 351 of file ptwXY_core.cc
References ptwXYPoints_s::status.
Referenced by nf_Legendre_from_ptwXY().
int ptwXY_getUserFlag (ptwXYPoints * ptwXY)
Definition at line 358 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 358 of file ptwXY_core.cc
References ptwXYPoints_s::userFlag.
nfu_status ptwXY_getValueAtX (ptwXYPoints * ptwXY, double x, double * y)
Definition at line 844 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 844 of file ptwXY_core.cc
References ptwXY_interpolationOtherInfo::argList, ptwXY_interpolationOtherInfo::getValueFunc, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, nfu_Okay, nfu_XOutsideDomain, ptwXYOverflowPoint_s::point, ptwXY_getPointsAroundX(), ptwXY_interpolatePoint(), ptwXY_lessEqualGreaterX_between, ptwXY_lessEqualGreaterX_empty, ptwXY_lessEqualGreaterX_equal, ptwXY_lessEqualGreaterX_greater, ptwXY_lessEqualGreaterX_lessThan, ptwXYPoints_s::status, ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by MCGIDI_reaction_getCrossSectionAtE(), MCGIDI_sampling_ptwXY_getValueAtX(), MCGIDI_target_heated_getTotalCrossSectionAtE(), ptwXY_div_ptwXY(), ptwXY_div_s_ptwXY(), ptwXY_dullEdges(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_intersectionWith_ptwX(), and ptwXY_xSlice().
ptwXPoints* ptwXY_getXArray (ptwXYPoints * ptwXY, nfu_status * status)
Definition at line 24 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 24 of file ptwXY_convenient.cc
References ptwXPoints_s::length, ptwXYPoints_s::length, n, nfu_Okay, ptwXPoints_s::points, ptwXYPoints_s::points, ptwX_new(), ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, and ptwXYPoint_s::x.
double ptwXY_getXMax (ptwXYPoints * ptwXY)
Definition at line 1239 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1239 of file ptwXY_core.cc
References ptwXY_getXMaxAndFrom().
Referenced by GIDI_settings_processedFlux::groupFunction(), MCGIDI_product_sampleMultiplicity(), MCGIDI_reaction_parseFromTOM(), MCGIDI_sampling_ptwXY_getValueAtX(), ptwXY_convolution3(), ptwXY_integrateDomain(), ptwXY_integrateDomainWithWeight_sqrt_x(), ptwXY_integrateDomainWithWeight_x(), ptwXY_xMinSlice(), and ptwXY_xSlice().
double ptwXY_getXMaxAndFrom (ptwXYPoints * ptwXY, ptwXY_dataFrom * dataFrom)
Definition at line 1215 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1215 of file ptwXY_core.cc
References ptwXYPoints_s::length, nfu_getNAN(), ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXYOverflowPoint_s::prior, ptwXY_dataFrom_Overflow, ptwXY_dataFrom_Points, ptwXY_dataFrom_Unknown, ptwXY_getNonOverflowLength(), ptwXYPoint_s::x, and x.
Referenced by ptwXY_appendXY(), ptwXY_getPointsAroundX_closeIsEqual(), and ptwXY_getXMax().
double ptwXY_getXMin (ptwXYPoints * ptwXY)
Definition at line 1206 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1206 of file ptwXY_core.cc
References ptwXY_getXMinAndFrom().
Referenced by GIDI_settings_processedFlux::groupFunction(), MCGIDI_reaction_parseFromTOM(), MCGIDI_sampling_ptwXY_getValueAtX(), ptwXY_convolution3(), ptwXY_integrateDomain(), ptwXY_integrateDomainWithWeight_sqrt_x(), ptwXY_integrateDomainWithWeight_x(), ptwXY_xMaxSlice(), and ptwXY_xSlice().
double ptwXY_getXMinAndFrom (ptwXYPoints * ptwXY, ptwXY_dataFrom * dataFrom)
Definition at line 1182 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1182 of file ptwXY_core.cc
References ptwXYOverflowPoint_s::next, nfu_getNAN(), ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_dataFrom_Overflow, ptwXY_dataFrom_Points, ptwXY_dataFrom_Unknown, ptwXY_getNonOverflowLength(), and ptwXYPoint_s::x.
Referenced by ptwXY_getPointsAroundX_closeIsEqual(), and ptwXY_getXMin().
nfu_status ptwXY_getXYPairAtIndex (ptwXYPoints * ptwXY, int64_t index, double * x, double * y)
Definition at line 698 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 698 of file ptwXY_core.cc
References nfu_badIndex, nfu_Okay, ptwXY_getPointAtIndex(), ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM(), and nf_Legendre_from_ptwXY().
double ptwXY_getYMax (ptwXYPoints * ptwXY)
Definition at line 1269 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1269 of file ptwXY_core.cc
References ptwXYPoints_s::length, n, ptwXYOverflowPoint_s::next, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), and ptwXYPoint_s::y.
Referenced by MCGIDI_product_parseFromTOM(), and ptwXY_clip().
double ptwXY_getYMin (ptwXYPoints * ptwXY)
Definition at line 1248 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1248 of file ptwXY_core.cc
References ptwXYPoints_s::length, n, ptwXYOverflowPoint_s::next, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXYPoint_s::y, and y.
Referenced by MCGIDI_product_parseFromTOM(), and ptwXY_clip().
ptwXPoints* ptwXY_groupOneFunction (ptwXYPoints * ptwXY, ptwXPoints * groupBoundaries, ptwXY_group_normType normType, ptwXPoints * ptwX_norm, nfu_status * status)
Definition at line 363 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 363 of file ptwXY_integration.cc
References check_license::err(), f, ptwXYPoints_s::interpolation, ptwXPoints_s::length, ptwXYPoints_s::length, nfu_badNorm, nfu_divByZero, nfu_Okay, nfu_otherInterpolation, ptwXPoints_s::points, ptwXYPoints_s::points, ptwX_createLine(), ptwX_free(), ptwX_length(), ptwX_new(), ptwXY_free(), ptwXY_group_normType_dx, ptwXY_group_normType_norm, ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_intersectionWith_ptwX(), ptwXY_simpleCoalescePoints(), ptwXPoints_s::status, sum, ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y1, and y2.
ptwXPoints* ptwXY_groupThreeFunctions (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, ptwXYPoints * ptwXY3, ptwXPoints * groupBoundaries, ptwXY_group_normType normType, ptwXPoints * ptwX_norm, nfu_status * status)
Definition at line 528 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 528 of file ptwXY_integration.cc
References check_license::err(), f, ff, fff, Acts::UnitConstants::g, Acts::UnitConstants::h, hh, ptwXYPoints_s::interpolation, ptwXPoints_s::length, ptwXYPoints_s::length, nfu_badNorm, nfu_divByZero, nfu_Okay, nfu_otherInterpolation, ptwXPoints_s::points, ptwXYPoints_s::points, ptwX_createLine(), ptwX_free(), ptwX_length(), ptwX_new(), ptwXY_free(), ptwXY_group_normType_dx, ptwXY_group_normType_norm, ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_intersectionWith_ptwX(), ptwXY_simpleCoalescePoints(), ptwXY_tweakDomainsToMutualify(), ptwXY_union(), ptwXY_union_fill, ptwXPoints_s::status, sum, ptwXYPoint_s::x, x1, x2, and ptwXYPoint_s::y.
ptwXPoints* ptwXY_groupTwoFunctions (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, ptwXPoints * groupBoundaries, ptwXY_group_normType normType, ptwXPoints * ptwX_norm, nfu_status * status)
Definition at line 435 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 435 of file ptwXY_integration.cc
References check_license::err(), f, ff, Acts::UnitConstants::g, ptwXYPoints_s::interpolation, ptwXPoints_s::length, ptwXYPoints_s::length, nfu_badNorm, nfu_divByZero, nfu_Okay, nfu_otherInterpolation, ptwXPoints_s::points, ptwXYPoints_s::points, ptwX_createLine(), ptwX_free(), ptwX_length(), ptwX_new(), ptwXY_free(), ptwXY_group_normType_dx, ptwXY_group_normType_norm, ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_intersectionWith_ptwX(), ptwXY_simpleCoalescePoints(), ptwXY_tweakDomainsToMutualify(), ptwXY_union(), ptwXY_union_fill, ptwXPoints_s::status, sum, ptwXYPoint_s::x, x1, x2, and ptwXYPoint_s::y.
Referenced by GIDI_settings_processedFlux::groupFunction().
double ptwXY_integrate (ptwXYPoints * ptwXY, double xMin, double xMax, nfu_status * status)
Definition at line 118 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 118 of file ptwXY_integration.cc
References ptwXYPoints_s::interpolation, ptwXYPoints_s::length, n, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_f_integrate(), ptwXY_interpolatePoint(), ptwXY_interpolationOther, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, sum, ptwXYPoint_s::x, x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
Referenced by ptwXY_integrateDomain().
double ptwXY_integrateDomain (ptwXYPoints * ptwXY, nfu_status * status)
Definition at line 181 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 181 of file ptwXY_integration.cc
References ptwXYPoints_s::length, nfu_Okay, ptwXY_getXMax(), ptwXY_getXMin(), ptwXY_integrate(), and ptwXYPoints_s::status.
Referenced by MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM(), and ptwXY_normalize().
double ptwXY_integrateDomainWithWeight_sqrt_x (ptwXYPoints * ptwXY, nfu_status * status)
Definition at line 284 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 284 of file ptwXY_integration.cc
References ptwXYPoints_s::length, nfu_Okay, ptwXY_getXMax(), ptwXY_getXMin(), ptwXY_integrateWithWeight_sqrt_x(), and ptwXYPoints_s::status.
double ptwXY_integrateDomainWithWeight_x (ptwXYPoints * ptwXY, nfu_status * status)
Definition at line 210 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 210 of file ptwXY_integration.cc
References ptwXYPoints_s::length, nfu_Okay, ptwXY_getXMax(), ptwXY_getXMin(), ptwXY_integrateWithWeight_x(), and ptwXYPoints_s::status.
double ptwXY_integrateWithFunction (ptwXYPoints * ptwXY, ptwXY_createFromFunction_callback func, void * argList, double xMin, double xMax, int degree, int recursionLimit, double tolerance, nfu_status * status)
Definition at line 657 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 657 of file ptwXY_integration.cc
References ptwXY_integrateWithFunctionInfo_s::argList, ptwXY_integrateWithFunctionInfo_s::degree, degree, ptwXY_integrateWithFunctionInfo_s::func, func, ptwXY_integrateWithFunctionInfo_s::interpolation, ptwXYPoints_s::interpolation, ptwXYPoints_s::length, n1, nf_GnG_adaptiveQuadrature(), nfu_Okay, ptwXYPoints_s::points, ptwXY_integrateWithFunction2(), ptwXY_integrateWithFunction3(), ptwXY_simpleCoalescePoints(), sign(), ptwXYPoints_s::status, ptwXYPoint_s::x, x, ptwXY_integrateWithFunctionInfo_s::x1, ptwXY_integrateWithFunctionInfo_s::x2, ptwXYPoint_s::y, ptwXY_integrateWithFunctionInfo_s::y1, and ptwXY_integrateWithFunctionInfo_s::y2.
double ptwXY_integrateWithWeight_sqrt_x (ptwXYPoints * ptwXY, double xMin, double xMax, nfu_status * status)
Definition at line 293 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 293 of file ptwXY_integration.cc
References c, ptwXYPoints_s::interpolation, ptwXYPoints_s::length, n, nfu_Okay, nfu_unsupportedInterpolation, ptwXYPoints_s::points, ptwXY_interpolatePoint(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, sum, ptwXYPoint_s::x, x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
Referenced by ptwXY_integrateDomainWithWeight_sqrt_x().
double ptwXY_integrateWithWeight_x (ptwXYPoints * ptwXY, double xMin, double xMax, nfu_status * status)
Definition at line 219 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 219 of file ptwXY_integration.cc
References ptwXYPoints_s::interpolation, ptwXYPoints_s::length, n, nfu_Okay, nfu_unsupportedInterpolation, ptwXYPoints_s::points, ptwXY_interpolatePoint(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, sum, ptwXYPoint_s::x, x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
Referenced by ptwXY_integrateDomainWithWeight_x().
nfu_status ptwXY_interpolatePoint (ptwXY_interpolation interpolation, double x, double * y, double x1, double y1, double x2, double y2)
Definition at line 30 of file ptwXY_interpolation.cc.
View newest version in sPHENIX GitHub at line 30 of file ptwXY_interpolation.cc
References G4Exp(), G4Log(), nfu_invalidInterpolation, nfu_Okay, nfu_otherInterpolation, ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, ptwXY_interpolationOther, x, y1, and y2.
Referenced by ptwXY_applyFunction2(), ptwXY_applyFunctionZeroCrossing(), ptwXY_convolution2(), ptwXY_createFromFunctionBisect(), ptwXY_dullEdges(), ptwXY_getValueAtX(), ptwXY_integrate(), ptwXY_integrateWithFunction3(), ptwXY_integrateWithWeight_sqrt_x(), ptwXY_integrateWithWeight_x(), ptwXY_thicken(), ptwXY_thin2(), and ptwXY_union().
ptwXYPoints* ptwXY_intersectionWith_ptwX (ptwXYPoints * ptwXY, ptwXPoints * ptwX, nfu_status * status)
Definition at line 194 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 194 of file ptwXY_convenient.cc
References ptwXYPoints_s::interpolation, ptwXYPoints_s::length, n, nfu_Okay, nfu_otherInterpolation, ptwXPoints_s::points, ptwXYPoints_s::points, ptwX_length(), ptwXY_clone(), ptwXY_free(), ptwXY_getValueAtX(), ptwXY_interpolationOther, ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXPoints_s::status, ptwXYPoints_s::status, ptwXYPoint_s::x, x, and y.
Referenced by ptwXY_groupOneFunction(), ptwXY_groupThreeFunctions(), and ptwXY_groupTwoFunctions().
int64_t ptwXY_length (ptwXYPoints * ptwXY)
Definition at line 583 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 583 of file ptwXY_core.cc
References ptwXYPoints_s::length.
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_product_parseFromTOM(), nf_Legendre_from_ptwXY(), and ptwXY_valueTo_ptwXAndY().
nfu_status ptwXY_mergeClosePoints (ptwXYPoints * ptwXY, double epsilon)
Definition at line 141 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 141 of file ptwXY_convenient.cc
References DBL_EPSILON, k, ptwXYPoints_s::length, n, nfu_Okay, ptwXYPoints_s::points, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, ptwXYPoint_s::x, x, ptwXYPoint_s::y, and y.
Referenced by ptwXY_union().
nfu_status ptwXY_mergeFromXsAndYs (ptwXYPoints * ptwXY, int length, double * xs, double * ys)
Definition at line 966 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 966 of file ptwXY_core.cc
References ptwXY_mergeFrom().
nfu_status ptwXY_mergeFromXYs (ptwXYPoints * ptwXY, int length, double * xys)
Definition at line 973 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 973 of file ptwXY_core.cc
References BTOF::length, nfu_badInput, nfu_free(), nfu_malloc(), nfu_mallocError, nfu_Okay, and ptwXY_mergeFrom().
nfu_status ptwXY_mod (ptwXYPoints * ptwXY, double m, int pythonMod)
Definition at line 76 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 76 of file ptwXY_binaryOperators.cc
References ptwXYOverflowPoint_s::next, nfu_divByZero, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXY_mod2(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_mul2_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 187 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 187 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::interpolation, BTOF::length, ptwXYPoints_s::length, n, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_free(), ptwXY_getValueAtX_ignore_XOutsideDomainError(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_mul2_s_ptwXY(), ptwXY_mul_ptwXY(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXY_update_biSectionMax(), v1, v2, ptwXYPoint_s::x, x, x1, x2, ptwXYPoint_s::y, y1, and y2.
nfu_status ptwXY_mul_double (ptwXYPoints * ptwXY, double value)
Definition at line 43 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 43 of file ptwXY_binaryOperators.cc
References ptwXY_slopeOffset().
ptwXYPoints* ptwXY_mul_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 171 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 171 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::length, ptwXY_binary_ptwXY(), and ptwXY_clone().
Referenced by ptwXY_mul2_ptwXY().
nfu_status ptwXY_mutualifyDomains (ptwXYPoints * ptwXY1, double lowerEps1, double upperEps1, int positiveXOnly1, ptwXYPoints * ptwXY2, double lowerEps2, double upperEps2, int positiveXOnly2)
Definition at line 368 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 368 of file ptwXY_convenient.cc
References ptwXYPoints_s::interpolation, ptwXYPoints_s::length, n1, nfu_domainsNotMutual, nfu_empty, nfu_invalidInterpolation, nfu_Okay, nfu_otherInterpolation, ptwXY_areDomainsMutual(), ptwXY_dullEdges(), ptwXY_getPointAtIndex_Unsafely(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXYPoint_s::x, and ptwXYPoint_s::y.
nfu_status ptwXY_neg (ptwXYPoints * ptwXY)
Definition at line 34 of file ptwXY_unitaryOperators.cc.
View newest version in sPHENIX GitHub at line 34 of file ptwXY_unitaryOperators.cc
References ptwXYOverflowPoint_s::next, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
Referenced by ptwXY_sub_ptwXY().
ptwXYPoints* ptwXY_new (ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const * interpolationOtherInfo, double biSectionMax, double accuracy, int64_t primarySize, int64_t secondarySize, nfu_status * status, int userFlag)
Definition at line 29 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 29 of file ptwXY_core.cc
References nfu_calloc(), nfu_free(), nfu_mallocError, nfu_Okay, ptwXY_setup(), and ptwXYPoints_s::status.
Referenced by MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parsePolynomialMultiplicity(), ptwXY_clip(), ptwXY_convolution(), ptwXY_create(), ptwXY_createFrom_Xs_Ys(), ptwXY_createFromFunction(), ptwXY_createGaussianCenteredSigma1(), ptwXY_flatInterpolationToLinear(), ptwXY_slice(), ptwXY_thin(), ptwXY_union(), ptwXY_valueTo_ptwXY(), and ptwXY_xSlice().
nfu_status ptwXY_normalize (ptwXYPoints * ptwXY1)
Definition at line 190 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 190 of file ptwXY_integration.cc
References ptwXYPoints_s::length, nfu_badNorm, nfu_Okay, ptwXYPoints_s::points, ptwXY_integrateDomain(), sum, and ptwXYPoint_s::y.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM().
nfu_status ptwXY_pow (ptwXYPoints * ptwXY, double p)
Definition at line 24 of file ptwXY_functions.cc.
View newest version in sPHENIX GitHub at line 24 of file ptwXY_functions.cc
References ptwXY_applyFunction(), and ptwXY_pow_callback().
nfu_status ptwXY_reallocateOverflowPoints (ptwXYPoints * ptwXY, int64_t size)
Definition at line 439 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 439 of file ptwXY_core.cc
References ptwXYPoints_s::length, ptwXYPoints_s::mallocFailedSize, nfu_mallocError, nfu_Okay, nfu_realloc(), ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::overflowLength, ptwXYPoints_s::overflowPoints, ptwXY_coalescePoints(), ptwXY_minimumOverflowSize, and ptwXYPoints_s::status.
Referenced by ptwXY_setup().
nfu_status ptwXY_reallocatePoints (ptwXYPoints * ptwXY, int64_t size, int forceSmallerResize)
Definition at line 410 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 410 of file ptwXY_core.cc
References ptwXYPoints_s::allocatedSize, BTOF::length, ptwXYPoints_s::length, ptwXYPoints_s::mallocFailedSize, nfu_mallocError, nfu_Okay, nfu_realloc(), ptwXYPoints_s::points, ptwXY_minimumSize, and ptwXYPoints_s::status.
Referenced by ptwXY_coalescePoints(), ptwXY_copy(), ptwXY_mergeFrom(), ptwXY_setup(), ptwXY_setXYData(), and ptwXY_setXYDataFromXsAndYs().
nfu_status ptwXY_release (ptwXYPoints * ptwXY)
Definition at line 549 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 549 of file ptwXY_core.cc
References ptwXYPoints_s::allocatedSize, ptwXY_interpolationOtherInfo::argList, ptwXY_interpolationOtherInfo::getValueFunc, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, ptwXY_interpolationOtherInfo::interpolationString, ptwXYPoints_s::length, nfu_free(), nfu_Okay, ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::overflowLength, ptwXYPoints_s::overflowPoints, ptwXYPoints_s::points, ptwXY_interpolationLinLin, and ptwXY_interpolationOther.
Referenced by ptwXY_free(), and ptwXY_setup().
ptwXPoints* ptwXY_runningIntegral (ptwXYPoints * ptwXY, nfu_status * status)
Definition at line 632 of file ptwXY_integration.cc.
View newest version in sPHENIX GitHub at line 632 of file ptwXY_integration.cc
References check_license::err(), ptwXYPoints_s::interpolation, ptwXYPoints_s::length, nfu_Okay, ptwXYPoints_s::points, ptwX_free(), ptwX_new(), ptwX_setPointAtIndex(), ptwXY_f_integrate(), ptwXY_simpleCoalescePoints(), sum, ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_fromTOM_pdfOfX(), and MCGIDI_KalbachMann_parseFromTOM2().
nfu_status ptwXY_scaleOffsetXAndY (ptwXYPoints * ptwXY, double xScale, double xOffset, double yScale, double yOffset)
Definition at line 481 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 481 of file ptwXY_methods.cc
References BTOF::length, ptwXYPoints_s::length, nfu_Okay, nfu_XNotAscending, ptwXYPoints_s::points, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, tmp, ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by MCGIDI_misc_Data2ptwXYPointsInUnitsOf().
double ptwXY_setAccuracy (ptwXYPoints * ptwXY, double accuracy)
Definition at line 379 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 379 of file ptwXY_core.cc
References ptwXYPoints_s::accuracy, and ptwXY_minAccuracy.
Referenced by ptwXY_setup().
double ptwXY_setBiSectionMax (ptwXYPoints * ptwXY, double biSectionMax)
Definition at line 397 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 397 of file ptwXY_core.cc
References ptwXYPoints_s::biSectionMax, and ptwXY_maxBiSectionMax.
Referenced by ptwXY_setup().
nfu_status ptwXY_setup (ptwXYPoints * ptwXY, ptwXY_interpolation interpolation, ptwXY_interpolationOtherInfo const * interpolationOtherInfo, double biSectionMax, double accuracy, int64_t primarySize, int64_t secondarySize, int userFlag)
Definition at line 46 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 46 of file ptwXY_core.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::allocatedSize, ptwXY_interpolationOtherInfo::argList, ptwXYPoints_s::biSectionMax, flatInterpolationString, ptwXY_interpolationOtherInfo::getValueFunc, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, ptwXY_interpolationOtherInfo::interpolationString, ptwXYPoints_s::length, linLinInterpolationString, linLogInterpolationString, logLinInterpolationString, logLogInterpolationString, ptwXYPoints_s::mallocFailedSize, nfu_mallocError, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYPoints_s::overflowPoints, ptwXYPoints_s::points, ptwXY_initialOverflowPoint(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, ptwXY_interpolationOther, ptwXY_maxBiSectionMax, ptwXY_minAccuracy, ptwXY_reallocateOverflowPoints(), ptwXY_reallocatePoints(), ptwXY_release(), ptwXY_setAccuracy(), ptwXY_setBiSectionMax(), ptwXY_setUserFlag(), ptwXY_sigma_none, ptwXYPoints_s::status, ptwXYPoints_s::typeX, ptwXYPoints_s::typeY, and ptwXYPoints_s::userFlag.
Referenced by ptwXY_new().
void ptwXY_setUserFlag (ptwXYPoints * ptwXY, int userFlag)
Definition at line 365 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 365 of file ptwXY_core.cc
References ptwXYPoints_s::userFlag.
Referenced by ptwXY_setup().
nfu_status ptwXY_setValueAtX (ptwXYPoints * ptwXY, double x, double y)
Definition at line 876 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 876 of file ptwXY_core.cc
References ptwXY_setValueAtX_overrideIfClose().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_product_parsePolynomialMultiplicity(), ptwXY_applyFunction2(), ptwXY_applyFunctionZeroCrossing(), ptwXY_clip(), ptwXY_clip2(), ptwXY_convolution(), ptwXY_convolution3(), ptwXY_createGaussianCenteredSigma1(), ptwXY_createGaussianCenteredSigma1_2(), ptwXY_div_ptwXY(), ptwXY_div_s_ptwXY(), ptwXY_dullEdges(), ptwXY_exp_s(), ptwXY_flatInterpolationToLinear(), ptwXY_intersectionWith_ptwX(), ptwXY_LinLogToLinLin(), ptwXY_LogLinToLinLin(), ptwXY_LogLogToLinLin(), ptwXY_mul2_ptwXY(), ptwXY_mul2_s_ptwXY(), ptwXY_otherToLinLin(), ptwXY_thicken(), ptwXY_valueTo_ptwXY(), and ptwXY_xSlice().
nfu_status ptwXY_setValueAtX_overrideIfClose (ptwXYPoints * ptwXY, double x, double y, double eps, int override)
Definition at line 883 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 883 of file ptwXY_core.cc
References ptwXYOverflowPoint_s::index, ptwXYPoints_s::length, ptwXYOverflowPoint_s::next, nfu_Okay, ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYPoints_s::overflowPoints, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXYOverflowPoint_s::prior, ptwXY_coalescePoints(), ptwXY_getNonOverflowLength(), ptwXY_getPointsAroundX_closeIsEqual(), ptwXY_lessEqualGreaterX_between, ptwXY_lessEqualGreaterX_empty, ptwXY_lessEqualGreaterX_equal, ptwXY_lessEqualGreaterX_greater, ptwXY_lessEqualGreaterX_lessThan, ptwXYPoints_s::status, ptwXYPoint_s::x, x, ptwXYPoint_s::y, and y.
Referenced by ptwXY_createFromFunction(), ptwXY_createFromFunctionBisect(), ptwXY_createFromFunctionZeroCrossing(), and ptwXY_setValueAtX().
nfu_status ptwXY_setXYData (ptwXYPoints * ptwXY, int64_t length, double const * xy)
Definition at line 597 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 597 of file ptwXY_core.cc
References ptwXYPoints_s::allocatedSize, d, BTOF::length, ptwXYPoints_s::length, ptwXYOverflowPoint_s::next, nfu_Okay, nfu_XNotAscending, ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYPoints_s::points, ptwXYOverflowPoint_s::prior, ptwXY_reallocatePoints(), ptwXYPoints_s::status, ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by ptwXY_create().
nfu_status ptwXY_setXYDataFromXsAndYs (ptwXYPoints * ptwXY, int64_t length, double const * x, double const * y)
Definition at line 631 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 631 of file ptwXY_core.cc
References ptwXYPoints_s::allocatedSize, BTOF::length, ptwXYPoints_s::length, nfu_Okay, nfu_XNotAscending, ptwXYPoints_s::points, ptwXY_clear(), ptwXY_reallocatePoints(), ptwXYPoints_s::status, ptwXYPoint_s::x, x, ptwXYPoint_s::y, and y.
nfu_status ptwXY_setXYPairAtIndex (ptwXYPoints * ptwXY, int64_t index, double x, double y)
Definition at line 1098 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 1098 of file ptwXY_core.cc
References ptwXYOverflowPoint_s::index, ptwXYPoints_s::length, ptwXYOverflowPoint_s::next, nfu_badIndex, nfu_badIndexForX, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXYOverflowPoint_s::prior, ptwXYPoints_s::status, ptwXYPoint_s::x, x, ptwXYPoint_s::y, and y.
void ptwXY_showInteralStructure (ptwXYPoints * ptwXY, FILE * f, int printPointersAsNull)
Definition at line 253 of file ptwXY_misc.cc.
View newest version in sPHENIX GitHub at line 253 of file ptwXY_misc.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::allocatedSize, ptwXY_interpolationOtherInfo::argList, ptwXYPoints_s::biSectionMax, ptwXY_interpolationOtherInfo::getValueFunc, ptwXYOverflowPoint_s::index, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, ptwXY_interpolationOtherInfo::interpolationString, ptwXYPoints_s::length, ptwXYPoints_s::mallocFailedSize, ptwXYPoints_s::minFractional_dx, n, ptwXYOverflowPoint_s::next, ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::overflowHeader, ptwXYPoints_s::overflowLength, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXY_getPointAtIndex(), ptwXYPoints_s::status, ptwXYPoints_s::userFlag, ptwXYPoint_s::x, and ptwXYPoint_s::y.
nfu_status ptwXY_simpleCoalescePoints (ptwXYPoints * ptwXY)
Definition at line 529 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 529 of file ptwXY_core.cc
References ptwXYPoints_s::length, and ptwXY_coalescePoints().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_product_parseFromTOM(), ptwXY_applyFunction(), ptwXY_clip(), ptwXY_convolution(), ptwXY_copyToC_XY(), ptwXY_createFromFunction(), ptwXY_deletePoints(), ptwXY_div_ptwXY(), ptwXY_exp(), ptwXY_flatInterpolationToLinear(), ptwXY_getXArray(), ptwXY_groupOneFunction(), ptwXY_groupThreeFunctions(), ptwXY_groupTwoFunctions(), ptwXY_integrate(), ptwXY_integrateWithFunction(), ptwXY_integrateWithWeight_sqrt_x(), ptwXY_integrateWithWeight_x(), ptwXY_intersectionWith_ptwX(), ptwXY_mergeClosePoints(), ptwXY_mergeFrom(), ptwXY_mul2_ptwXY(), ptwXY_runningIntegral(), ptwXY_scaleOffsetXAndY(), ptwXY_slice(), ptwXY_thicken(), ptwXY_thin(), ptwXY_toOtherInterpolation2(), ptwXY_trim(), ptwXY_union(), and ptwXY_valueTo_ptwXAndY().
void ptwXY_simplePrint (ptwXYPoints * ptwXY, char * format)
Definition at line 298 of file ptwXY_misc.cc.
View newest version in sPHENIX GitHub at line 298 of file ptwXY_misc.cc
References ptwXY_simpleWrite().
void ptwXY_simpleWrite (ptwXYPoints * ptwXY, FILE * f, char * format)
Definition at line 285 of file ptwXY_misc.cc.
View newest version in sPHENIX GitHub at line 285 of file ptwXY_misc.cc
References ptwXYPoints_s::length, ptwXY_getPointAtIndex(), ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by ptwXY_simplePrint().
ptwXYPoints* ptwXY_slice (ptwXYPoints * ptwXY, int64_t index1, int64_t index2, int64_t secondarySize, nfu_status * status)
Definition at line 248 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 248 of file ptwXY_core.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, Acts::index1, Acts::index2, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, BTOF::length, ptwXYPoints_s::length, n, nfu_badIndex, nfu_badSelf, nfu_Okay, ptwXYPoints_s::points, ptwXY_new(), ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, and ptwXYPoints_s::userFlag.
Referenced by ptwXY_clone().
nfu_status ptwXY_slopeOffset (ptwXYPoints * ptwXY, double slope, double offset)
Definition at line 25 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 25 of file ptwXY_binaryOperators.cc
References ptwXYOverflowPoint_s::next, nfu_Okay, offset, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
Referenced by ptwXY_add_double(), ptwXY_div_doubleFrom(), ptwXY_mul_double(), ptwXY_sub_doubleFrom(), and ptwXY_sub_fromDouble().
nfu_status ptwXY_sub_doubleFrom (ptwXYPoints * ptwXY, double value)
Definition at line 41 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 41 of file ptwXY_binaryOperators.cc
References ptwXY_slopeOffset().
nfu_status ptwXY_sub_fromDouble (ptwXYPoints * ptwXY, double value)
Definition at line 42 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 42 of file ptwXY_binaryOperators.cc
References ptwXY_slopeOffset().
ptwXYPoints* ptwXY_sub_ptwXY (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 154 of file ptwXY_binaryOperators.cc.
View newest version in sPHENIX GitHub at line 154 of file ptwXY_binaryOperators.cc
References ptwXYPoints_s::length, nfu_Okay, ptwXY_binary_ptwXY(), ptwXY_clone(), ptwXY_free(), and ptwXY_neg().
nfu_status ptwXY_thicken (ptwXYPoints * ptwXY1, int sectionSubdivideMax, double dxMax, double fxMax)
Definition at line 144 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 144 of file ptwXY_methods.cc
References dx, G4Exp(), G4Log(), int(), ptwXYPoints_s::interpolation, ptwXYPoints_s::length, nfu_badInput, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_interpolatePoint(), ptwXY_interpolationOther, ptwXY_sectionSubdivideMax, ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXY_thicken_linear_dx(), ptwXYPoint_s::x, x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
ptwXYPoints* ptwXY_thin (ptwXYPoints * ptwXY1, double accuracy, nfu_status * status)
Definition at line 211 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 211 of file ptwXY_methods.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, BTOF::length, ptwXYPoints_s::length, nfu_calloc(), nfu_free(), nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::overflowLength, ptwXYPoints_s::points, ptwXY_clone(), ptwXY_free(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_new(), ptwXY_simpleCoalescePoints(), ptwXY_thin2(), ptwXYPoints_s::userFlag, ptwXYPoint_s::y, y1, y2, and y3.
ptwXYPoints* ptwXY_toOtherInterpolation (ptwXYPoints * ptwXY, ptwXY_interpolation interpolation, double accuracy, nfu_status * status)
Definition at line 153 of file ptwXY_interpolation.cc.
View newest version in sPHENIX GitHub at line 153 of file ptwXY_interpolation.cc
References ptwXYPoints_s::accuracy, ptwXY_interpolationOtherInfo::argList, func, ptwXY_interpolationOtherInfo::getValueFunc, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, n1, nfu_Okay, nfu_unsupportedInterpolationConversion, ptwXY_clone(), ptwXY_cloneToInterpolation(), ptwXY_free(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, ptwXY_interpolationOther, ptwXY_LinLogToLinLin(), ptwXY_LogLinToLinLin(), ptwXY_LogLogToLinLin(), ptwXY_otherToLinLin(), ptwXY_toOtherInterpolation2(), and ptwXYPoints_s::status.
ptwXYPoints* ptwXY_toUnitbase (ptwXYPoints * ptwXY, nfu_status * status)
Definition at line 306 of file ptwXY_interpolation.cc.
View newest version in sPHENIX GitHub at line 306 of file ptwXY_interpolation.cc
References dx, BTOF::length, ptwXYPoints_s::length, n, nfu_tooFewPoints, ptwXYPoints_s::points, ptwXY_clone(), ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by ptwXY_unitbaseInterpolate().
nfu_status ptwXY_trim (ptwXYPoints * ptwXY)
Definition at line 315 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 315 of file ptwXY_methods.cc
References BTOF::length, ptwXYPoints_s::length, nfu_Okay, ptwXYPoints_s::points, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
nfu_status ptwXY_tweakDomainsToMutualify (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, int epsilonFactor, double epsilon)
Definition at line 295 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 295 of file ptwXY_convenient.cc
References DBL_EPSILON, ptwXYPoints_s::length, n1, nfu_domainsNotMutual, nfu_empty, nfu_Okay, nfu_tooFewPoints, ptwXY_getPointAtIndex_Unsafely(), ptwXYPoints_s::status, sum, ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by ptwXY_groupThreeFunctions(), and ptwXY_groupTwoFunctions().
ptwXYPoints* ptwXY_union (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status, int unionOptions)
Definition at line 349 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 349 of file ptwXY_methods.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, DBL_EPSILON, ptwXYPoints_s::interpolation, BTOF::length, ptwXYPoints_s::length, n, n1, nfu_Okay, nfu_otherInterpolation, nfu_tooFewPoints, ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::points, ptwXY_free(), ptwXY_interpolatePoint(), ptwXY_interpolationOther, ptwXY_mergeClosePoints(), ptwXY_minimumSize, ptwXY_new(), ptwXY_simpleCoalescePoints(), ptwXY_union_fill, ptwXY_union_mergeClosePoints, ptwXY_union_trim, ptwXYPoints_s::status, ptwXYPoints_s::userFlag, ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
Referenced by ptwXY_binary_ptwXY(), ptwXY_div_ptwXY(), ptwXY_div_ptwXY_forFlats(), ptwXY_groupThreeFunctions(), and ptwXY_groupTwoFunctions().
ptwXYPoints* ptwXY_unitbaseInterpolate (double w, double w1, ptwXYPoints * ptwXY1, double w2, ptwXYPoints * ptwXY2, nfu_status * status)
Definition at line 363 of file ptwXY_interpolation.cc.
View newest version in sPHENIX GitHub at line 363 of file ptwXY_interpolation.cc
References a, f, Acts::UnitConstants::g, BTOF::length, ptwXYPoints_s::length, n1, nfu_XOutsideDomain, ptwXYPoints_s::points, ptwXY_add_ptwXY(), ptwXY_clone(), ptwXY_free(), ptwXY_fromUnitbase(), ptwXY_toUnitbase(), r, ptwXYPoint_s::x, and ptwXYPoint_s::y.
void ptwXY_update_biSectionMax (ptwXYPoints * ptwXY1, double oldLength)
Definition at line 31 of file ptwXY_misc.cc.
View newest version in sPHENIX GitHub at line 31 of file ptwXY_misc.cc
References ptwXYPoints_s::biSectionMax, G4Log(), ptwXYPoints_s::length, and ptwXY_maxBiSectionMax.
Referenced by ptwXY_applyFunction(), ptwXY_div_ptwXY(), and ptwXY_mul2_ptwXY().
nfu_status ptwXY_valueTo_ptwXAndY (ptwXYPoints * ptwXY, double ** xs, double ** ys)
Definition at line 450 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 450 of file ptwXY_convenient.cc
References BTOF::length, nfu_mallocError, nfu_Okay, ptwXYPoints_s::points, ptwXY_length(), ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, ptwXYPoint_s::x, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_valueTo_ptwXY (double x1, double x2, double y, nfu_status * status)
Definition at line 477 of file ptwXY_convenient.cc.
View newest version in sPHENIX GitHub at line 477 of file ptwXY_convenient.cc
References n, nfu_Okay, nfu_XNotAscending, ptwXY_interpolationLinLin, ptwXY_maxBiSectionMax, ptwXY_minAccuracy, ptwXY_new(), and ptwXY_setValueAtX().
ptwXYPoints* ptwXY_xMaxSlice (ptwXYPoints * ptwXY, double xMax, int64_t secondarySize, int fill, nfu_status * status)
Definition at line 326 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 326 of file ptwXY_core.cc
References ptwXYPoints_s::length, ptwXY_getXMin(), and ptwXY_xSlice().
ptwXYPoints* ptwXY_xMinSlice (ptwXYPoints * ptwXY, double xMin, int64_t secondarySize, int fill, nfu_status * status)
Definition at line 315 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 315 of file ptwXY_core.cc
References ptwXYPoints_s::length, ptwXY_getXMax(), and ptwXY_xSlice().
ptwXYPoints* ptwXY_xSlice (ptwXYPoints * ptwXY, double xMin, double xMax, int64_t secondarySize, int fill, nfu_status * status)
Definition at line 274 of file ptwXY_core.cc.
View newest version in sPHENIX GitHub at line 274 of file ptwXY_core.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, ptwXYPoints_s::length, n, nfu_Okay, ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::points, ptwXY_clone(), ptwXY_coalescePoints(), ptwXY_free(), ptwXY_getValueAtX(), ptwXY_getXMax(), ptwXY_getXMin(), ptwXY_new(), ptwXY_setValueAtX(), ptwXYPoints_s::status, ptwXYPoints_s::userFlag, ptwXYPoint_s::x, and y.
Referenced by GIDI_settings_processedFlux::groupFunction(), ptwXY_createGaussian(), ptwXY_xMaxSlice(), and ptwXY_xMinSlice().