ECCE @ EIC Software: ExN04SteppingAction Class Reference
ExN04SteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04SteppingAction.hh>
Public Member Functions
ExN04SteppingAction ()
virtual ~ExN04SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
ExN04SteppingAction ()
virtual ~ExN04SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 37 of file ExN04SteppingAction.hh.
View newest version in sPHENIX GitHub at line 37 of file ExN04SteppingAction.hh
Constructor & Destructor Documentation
ExN04SteppingAction::ExN04SteppingAction ()
Definition at line 42 of file ExN04SteppingAction.cc.
View newest version in sPHENIX GitHub at line 42 of file ExN04SteppingAction.cc
ExN04SteppingAction::~ExN04SteppingAction () virtual
Definition at line 48 of file ExN04SteppingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file ExN04SteppingAction.cc
ExN04SteppingAction::ExN04SteppingAction ()
virtual ExN04SteppingAction::~ExN04SteppingAction () virtual
Member Function Documentation
void ExN04SteppingAction::UserSteppingAction (const G4Step * theStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 53 of file ExN04SteppingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file ExN04SteppingAction.cc
References fAlive, fSuspend, G4Track::GetDefinition(), G4VPhysicalVolume::GetName(), G4Track::GetParentID(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetTrack(), G4Track::GetTrackStatus(), G4MuonMinus::MuonMinusDefinition(), G4MuonPlus::MuonPlusDefinition(), and G4Track::SetTrackStatus().
virtual void ExN04SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/ExN04SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/src/ExN04SteppingAction.cc