ECCE @ EIC Software: G4PAIModelData Class Reference
G4PAIModelData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIModelData.hh>
Public Member Functions
G4PAIModelData (G4double tmin, G4double tmax, G4int verbose)
~G4PAIModelData ()
void Initialise (const G4MaterialCutsCouple *, G4PAIModel *)
G4double DEDXPerVolume (G4int coupleIndex, G4double scaledTkin, G4double cut) const
G4double CrossSectionPerVolume (G4int coupleIndex, G4double scaledTkin, G4double tcut, G4double tmax) const
G4double SampleAlongStepTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double tmax, G4double stepFactor) const
G4double SamplePostStepTransfer (G4int coupleIndex, G4double scaledTkin, G4double tmin, G4double tmax) const
Private Member Functions
G4double GetEnergyTransfer (G4int coupleIndex, size_t iPlace, G4double position) const
G4PAIModelData & operator= (const G4PAIModelData &right)=delete
G4PAIModelData (const G4PAIModelData &)=delete
Private Attributes
G4int fTotBin
G4double fLowestKineticEnergy
G4double fHighestKineticEnergy
G4PhysicsLogVector * fParticleEnergyVector
G4PAIySection fPAIySection
G4SandiaTable fSandia
std::vector< G4PhysicsTable * > fPAIxscBank
std::vector< G4PhysicsTable * > fPAIdEdxBank
std::vector< G4PhysicsLogVector * > fdEdxTable
Detailed Description
Definition at line 67 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PAIModelData.hh
Constructor & Destructor Documentation
G4PAIModelData::G4PAIModelData (G4double tmin, G4double tmax, G4int verbose) explicit
Definition at line 57 of file G4PAIModelData.cc.
View newest version in sPHENIX GitHub at line 57 of file G4PAIModelData.cc
References G4cout, G4endl, GeV, keV, max, and TeV.
G4PAIModelData::~G4PAIModelData ()
Definition at line 89 of file G4PAIModelData.cc.
View newest version in sPHENIX GitHub at line 89 of file G4PAIModelData.cc
References n.
G4PAIModelData::G4PAIModelData (const G4PAIModelData &) private delete
Member Function Documentation
G4double G4PAIModelData::CrossSectionPerVolume (G4int coupleIndex, G4double scaledTkin, G4double tcut, G4double tmax) const
Definition at line 244 of file G4PAIModelData.cc.
View newest version in sPHENIX GitHub at line 244 of file G4PAIModelData.cc
References Acts::VectorHelpers::cross(), max, and one.
Referenced by G4PAIModel::CrossSectionPerVolume().
G4double G4PAIModelData::DEDXPerVolume (G4int coupleIndex, G4double scaledTkin, G4double cut) const
Definition at line 202 of file G4PAIModelData.cc.
View newest version in sPHENIX GitHub at line 202 of file G4PAIModelData.cc
References max, and one.
Referenced by G4PAIModel::ComputeDEDXPerVolume().
G4double G4PAIModelData::GetEnergyTransfer (G4int coupleIndex, size_t iPlace, G4double position) const private
Definition at line 462 of file G4PAIModelData.cc.
View newest version in sPHENIX GitHub at line 462 of file G4PAIModelData.cc
References G4PhysicsVector::Energy(), G4UniformRand, G4PhysicsVector::GetMaxEnergy(), G4PhysicsVector::GetVectorLength(), v, G4PhysicsVector::Value(), x1, x2, y1, and y2.
void G4PAIModelData::Initialise (const G4MaterialCutsCouple * couple, G4PAIModel * model)
Definition at line 110 of file G4PAIModelData.cc.
View newest version in sPHENIX GitHub at line 110 of file G4PAIModelData.cc
References G4PAIModel::ComputeMaxEnergy(), eV, G4MaterialCutsCouple::GetMaterial(), G4PhysicsTable::insertAt(), k, mat, n, source.hepunit::proton_mass_c2, G4PhysicsFreeVector::PutValue(), G4PhysicsVector::PutValue(), and t.
Referenced by G4PAIModel::Initialise().
G4PAIModelData& G4PAIModelData::operator= (const G4PAIModelData & right) private delete
G4double G4PAIModelData::SampleAlongStepTransfer (G4int coupleIndex, G4double kinEnergy, G4double scaledTkin, G4double tmax, G4double stepFactor) const
Definition at line 288 of file G4PAIModelData.cc.
View newest version in sPHENIX GitHub at line 288 of file G4PAIModelData.cc
References e1, e2, G4PhysicsVector::Energy(), G4Poisson(), G4UniformRand, G4PhysicsVector::GetMaxEnergy(), min, one, position, v1, v2, and G4PhysicsVector::Value().
Referenced by G4PAIModel::SampleFluctuations().
G4double G4PAIModelData::SamplePostStepTransfer (G4int coupleIndex, G4double scaledTkin, G4double tmin, G4double tmax) const
Definition at line 382 of file G4PAIModelData.cc.
View newest version in sPHENIX GitHub at line 382 of file G4PAIModelData.cc
References emax, CEMC_TOWER::emin, G4PhysicsVector::Energy(), G4UniformRand, G4PhysicsVector::GetMaxEnergy(), max, min, one, v1, v2, and G4PhysicsVector::Value().
Referenced by G4PAIModel::SampleSecondaries().
Member Data Documentation
std::vector<G4PhysicsLogVector*> G4PAIModelData::fdEdxTable private
Definition at line 113 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PAIModelData.hh
G4double G4PAIModelData::fHighestKineticEnergy private
Definition at line 104 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 104 of file G4PAIModelData.hh
G4double G4PAIModelData::fLowestKineticEnergy private
Definition at line 103 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 103 of file G4PAIModelData.hh
std::vector<G4PhysicsTable*> G4PAIModelData::fPAIdEdxBank private
Definition at line 112 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PAIModelData.hh
std::vector<G4PhysicsTable*> G4PAIModelData::fPAIxscBank private
Definition at line 111 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 111 of file G4PAIModelData.hh
G4PAIySection G4PAIModelData::fPAIySection private
Definition at line 108 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PAIModelData.hh
G4PhysicsLogVector* G4PAIModelData::fParticleEnergyVector private
Definition at line 106 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 106 of file G4PAIModelData.hh
G4SandiaTable G4PAIModelData::fSandia private
Definition at line 109 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 109 of file G4PAIModelData.hh
G4int G4PAIModelData::fTotBin private
Definition at line 102 of file G4PAIModelData.hh.
View newest version in sPHENIX GitHub at line 102 of file G4PAIModelData.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIModelData.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4PAIModelData.cc