ECCE @ EIC Software: ElectronRunAction Class Reference
ElectronRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/include/ElectronRunAction.hh>
Public Member Functions
ElectronRunAction (const G4String &)
virtual ~ElectronRunAction ()
virtual G4Run * GenerateRun ()
virtual void EndOfRunAction (const G4Run *)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void BeginOfRunAction (const G4Run *aRun)
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4String fOutputFileSpec
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 40 of file ElectronRunAction.hh.
View newest version in sPHENIX GitHub at line 40 of file ElectronRunAction.hh
Constructor & Destructor Documentation
ElectronRunAction::ElectronRunAction (const G4String & outputFile)
Definition at line 38 of file ElectronRunAction.cc.
View newest version in sPHENIX GitHub at line 38 of file ElectronRunAction.cc
References G4RunManager::GetRunManager(), and G4RunManager::SetPrintProgress().
ElectronRunAction::~ElectronRunAction () virtual
Definition at line 46 of file ElectronRunAction.cc.
View newest version in sPHENIX GitHub at line 46 of file ElectronRunAction.cc
Member Function Documentation
void ElectronRunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 58 of file ElectronRunAction.cc.
View newest version in sPHENIX GitHub at line 58 of file ElectronRunAction.cc
References ElectronRun::DumpData(), fOutputFileSpec, G4cout, G4endl, and G4Run::GetNumberOfEvent().
G4Run * ElectronRunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 51 of file ElectronRunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file ElectronRunAction.cc
Member Data Documentation
G4String ElectronRunAction::fOutputFileSpec private
Definition at line 51 of file ElectronRunAction.hh.
View newest version in sPHENIX GitHub at line 51 of file ElectronRunAction.hh
Referenced by EndOfRunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/include/ElectronRunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering2/src/ElectronRunAction.cc