ECCE @ EIC Software: G4EMDataSet Class Reference
G4EMDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4EMDataSet.hh>
Public Member Functions
G4EMDataSet (G4int argZ, G4VDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double yUnit=CLHEP::barn, G4bool random=false)
G4EMDataSet (G4int argZ, G4DataVector *xData, G4DataVector *data, G4VDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double yUnit=CLHEP::barn, G4bool random=false)
G4EMDataSet (G4int argZ, G4DataVector *xData, G4DataVector *data, G4DataVector *xLogData, G4DataVector *Logdata, G4VDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double yUnit=CLHEP::barn, G4bool random=false)
virtual ~G4EMDataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4VEMDataSet * GetComponent (G4int) const
virtual void AddComponent (G4VEMDataSet *)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int) const
virtual const G4DataVector & GetData (G4int) const
virtual const G4DataVector & GetLogEnergies (G4int) const
virtual const G4DataVector & GetLogData (G4int) const
virtual void SetEnergiesData (G4DataVector *xData, G4DataVector *data, G4int componentId)
virtual void SetLogEnergiesData (G4DataVector *xData, G4DataVector *data, G4DataVector *xLogData, G4DataVector *Logdata, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool LoadNonLogData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int componentId=0) const
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Private Member Functions
size_t FindLowerBound (G4double energy) const
size_t FindLowerBound (G4double x, G4DataVector *values) const
G4double IntegrationFunction (G4double x)
virtual void BuildPdf ()
G4String FullFileName (const G4String &fileName) const
G4EMDataSet ()
G4EMDataSet (const G4EMDataSet &copy)
G4EMDataSet & operator= (const G4EMDataSet &right)
Private Attributes
G4int z
G4DataVector * energies
G4DataVector * data
G4DataVector * log_energies
G4DataVector * log_data
G4VDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
G4DataVector * pdf
G4bool randomSet
Detailed Description
Definition at line 57 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 57 of file G4EMDataSet.hh
Constructor & Destructor Documentation
G4EMDataSet::G4EMDataSet (G4int argZ, G4VDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double yUnit = CLHEP::barn, G4bool random = false)
Definition at line 62 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 62 of file G4EMDataSet.cc
References algorithm, BuildPdf(), FatalException, G4Exception(), and randomSet.
G4EMDataSet::G4EMDataSet (G4int argZ, G4DataVector * xData, G4DataVector * data, G4VDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double yUnit = CLHEP::barn, G4bool random = false)
Definition at line 84 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 84 of file G4EMDataSet.cc
References algorithm, BuildPdf(), energies, FatalException, G4Exception(), and randomSet.
G4EMDataSet::G4EMDataSet (G4int argZ, G4DataVector * xData, G4DataVector * data, G4DataVector * xLogData, G4DataVector * Logdata, G4VDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double yUnit = CLHEP::barn, G4bool random = false)
Definition at line 115 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 115 of file G4EMDataSet.cc
References algorithm, BuildPdf(), energies, FatalException, G4Exception(), log_data, log_energies, and randomSet.
G4EMDataSet::~G4EMDataSet () virtual
Definition at line 150 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 150 of file G4EMDataSet.cc
References algorithm, data, energies, log_data, log_energies, and pdf.
G4EMDataSet::G4EMDataSet () private
G4EMDataSet::G4EMDataSet (const G4EMDataSet & copy) private
Member Function Documentation
virtual void G4EMDataSet::AddComponent (G4VEMDataSet *) inline virtual
Implements G4VEMDataSet.
Definition at line 92 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 92 of file G4EMDataSet.hh
void G4EMDataSet::BuildPdf () private virtual
Definition at line 482 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 482 of file G4EMDataSet.cc
References IntegrationFunction(), G4Integrator< T, F >::Legendre96(), pdf, and sum.
Referenced by G4EMDataSet(), LoadData(), and LoadNonLogData().
size_t G4EMDataSet::FindLowerBound (G4double energy) const private
Definition at line 432 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 432 of file G4EMDataSet.cc
References energies.
Referenced by FindValue(), IntegrationFunction(), and RandomSelect().
size_t G4EMDataSet::FindLowerBound (G4double x, G4DataVector * values) const private
Definition at line 449 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 449 of file G4EMDataSet.cc
G4double G4EMDataSet::FindValue (G4double x, G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 160 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 160 of file G4EMDataSet.cc
References algorithm, G4VDataSetAlgorithm::Calculate(), energies, FindLowerBound(), log_data, and log_energies.
G4String G4EMDataSet::FullFileName (const G4String & fileName) const private
Definition at line 466 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 466 of file G4EMDataSet.cc
References FatalException, G4Exception(), and z.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
virtual const G4VEMDataSet* G4EMDataSet::GetComponent (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 90 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 90 of file G4EMDataSet.hh
virtual const G4DataVector& G4EMDataSet::GetData (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 97 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 97 of file G4EMDataSet.hh
References data.
virtual const G4DataVector& G4EMDataSet::GetEnergies (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 96 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 96 of file G4EMDataSet.hh
References energies.
virtual const G4DataVector& G4EMDataSet::GetLogData (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 99 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 99 of file G4EMDataSet.hh
References log_data.
virtual const G4DataVector& G4EMDataSet::GetLogEnergies (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 98 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 98 of file G4EMDataSet.hh
References log_energies.
G4double G4EMDataSet::IntegrationFunction (G4double x) private
Definition at line 540 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 540 of file G4EMDataSet.cc
References algorithm, bin, G4VDataSetAlgorithm::Calculate(), G4LinInterpolation::Calculate(), energies, FindLowerBound(), and y.
Referenced by BuildPdf().
G4bool G4EMDataSet::LoadData (const G4String & fileName) virtual
Implements G4VEMDataSet.
Definition at line 248 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 248 of file G4EMDataSet.cc
References a, b, BuildPdf(), data, e, energies, FatalException, FullFileName(), G4Exception(), in, log_data, log_energies, message(), randomSet, unitData, and unitEnergies.
G4bool G4EMDataSet::LoadNonLogData (const G4String & fileName) virtual
Implements G4VEMDataSet.
Definition at line 306 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 306 of file G4EMDataSet.cc
References a, BuildPdf(), FatalException, FullFileName(), G4Exception(), in, k, message(), randomSet, SetEnergiesData(), unitData, and unitEnergies.
virtual size_t G4EMDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 94 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 94 of file G4EMDataSet.hh
G4EMDataSet& G4EMDataSet::operator= (const G4EMDataSet & right) private
void G4EMDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 178 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 178 of file G4EMDataSet.cc
References energies, G4cout, G4endl, pdf, unitData, and unitEnergies.
G4double G4EMDataSet::RandomSelect (G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 511 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 511 of file G4EMDataSet.cc
References algorithm, bin, G4VDataSetAlgorithm::Calculate(), G4LinInterpolation::Calculate(), energies, FatalException, FindLowerBound(), G4Exception(), G4UniformRand, pdf, and x.
G4bool G4EMDataSet::SaveData (const G4String & fileName) const virtual
Implements G4VEMDataSet.
Definition at line 360 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 360 of file G4EMDataSet.cc
References energies, FatalException, FullFileName(), G4Exception(), left, message(), unitData, and unitEnergies.
void G4EMDataSet::SetEnergiesData (G4DataVector * xData, G4DataVector * data, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 190 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 190 of file G4EMDataSet.cc
References data, energies, FatalException, and G4Exception().
Referenced by LoadNonLogData().
void G4EMDataSet::SetLogEnergiesData (G4DataVector * xData, G4DataVector * data, G4DataVector * xLogData, G4DataVector * Logdata, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 214 of file G4EMDataSet.cc.
View newest version in sPHENIX GitHub at line 214 of file G4EMDataSet.cc
References data, energies, FatalException, G4Exception(), log_data, and log_energies.
Member Data Documentation
G4VDataSetAlgorithm* G4EMDataSet::algorithm private
Definition at line 140 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 140 of file G4EMDataSet.hh
Referenced by FindValue(), G4EMDataSet(), IntegrationFunction(), RandomSelect(), and ~G4EMDataSet().
G4DataVector* G4EMDataSet::data private
Definition at line 136 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 136 of file G4EMDataSet.hh
Referenced by GetData(), LoadData(), SetEnergiesData(), SetLogEnergiesData(), and ~G4EMDataSet().
G4DataVector* G4EMDataSet::energies private
Definition at line 135 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 135 of file G4EMDataSet.hh
Referenced by FindLowerBound(), FindValue(), G4EMDataSet(), GetEnergies(), IntegrationFunction(), LoadData(), PrintData(), RandomSelect(), SaveData(), SetEnergiesData(), SetLogEnergiesData(), and ~G4EMDataSet().
G4DataVector* G4EMDataSet::log_data private
Definition at line 138 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 138 of file G4EMDataSet.hh
Referenced by FindValue(), G4EMDataSet(), GetLogData(), LoadData(), SetLogEnergiesData(), and ~G4EMDataSet().
G4DataVector* G4EMDataSet::log_energies private
Definition at line 137 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 137 of file G4EMDataSet.hh
Referenced by FindValue(), G4EMDataSet(), GetLogEnergies(), LoadData(), SetLogEnergiesData(), and ~G4EMDataSet().
G4DataVector* G4EMDataSet::pdf private
Definition at line 145 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 145 of file G4EMDataSet.hh
Referenced by BuildPdf(), PrintData(), RandomSelect(), and ~G4EMDataSet().
G4bool G4EMDataSet::randomSet private
Definition at line 146 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 146 of file G4EMDataSet.hh
Referenced by G4EMDataSet(), LoadData(), and LoadNonLogData().
G4double G4EMDataSet::unitData private
Definition at line 143 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 143 of file G4EMDataSet.hh
Referenced by LoadData(), LoadNonLogData(), PrintData(), and SaveData().
G4double G4EMDataSet::unitEnergies private
Definition at line 142 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 142 of file G4EMDataSet.hh
Referenced by LoadData(), LoadNonLogData(), PrintData(), and SaveData().
G4int G4EMDataSet::z private
Definition at line 133 of file G4EMDataSet.hh.
View newest version in sPHENIX GitHub at line 133 of file G4EMDataSet.hh
Referenced by FullFileName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4EMDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4EMDataSet.cc