ECCE @ EIC Software: G4ParticleHPPartial Class Reference
G4ParticleHPPartial Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPPartial.hh>
Public Member Functions
G4ParticleHPPartial (G4int n)
G4ParticleHPPartial (G4int n1, G4int n2)
void InitInterpolation (G4int i, std::istream &aDataFile)
void InitInterpolation (std::istream &aDataFile)
void Init (std::istream &aDataFile)
void InitData (G4int i, std::istream &aDataFile, G4double unit=1.)
~G4ParticleHPPartial ()
G4int GetNumberOfEnergies ()
void SetX (G4int i, G4double x)
void SetT (G4int i, G4double x)
void SetX (G4int i, G4int j, G4double x)
void SetY (G4int i, G4int j, G4double y)
void DoneSetXY (G4int i)
G4double GetX (G4int i)
G4double GetT (G4int i)
G4double GetX (G4int i, G4int j)
G4double GetY (G4int i, G4int j)
G4double GetY (G4int i, G4double e)
G4int GetNEntries (G4int i)
G4ParticleHPVector * GetY (G4double e1)
G4double Sample (G4double x)
Private Attributes
G4double * X
G4double * T
G4ParticleHPVector * data
G4int nData
G4InterpolationManager theManager
G4ParticleHPInterpolator theInt
Detailed Description
Definition at line 41 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPPartial.hh
Constructor & Destructor Documentation
G4ParticleHPPartial::G4ParticleHPPartial (G4int n) inline
Definition at line 45 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPPartial.hh
References n, nData, T, and X.
G4ParticleHPPartial::G4ParticleHPPartial (G4int n1, G4int n2) inline
Definition at line 53 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPPartial.hh
References max, n1, nData, T, and X.
G4ParticleHPPartial::~G4ParticleHPPartial () inline
Definition at line 101 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPPartial.hh
References data, T, and X.
Member Function Documentation
void G4ParticleHPPartial::DoneSetXY (G4int i) inline
Definition at line 113 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleHPPartial.hh
Referenced by G4ParticleHPElasticFS::Init().
G4int G4ParticleHPPartial::GetNEntries (G4int i) inline
Definition at line 120 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ParticleHPPartial.hh
Referenced by Sample().
G4int G4ParticleHPPartial::GetNumberOfEnergies () inline
Definition at line 107 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPPartial.hh
References nData.
G4double G4ParticleHPPartial::GetT (G4int i) inline
Definition at line 116 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ParticleHPPartial.hh
References T.
G4double G4ParticleHPPartial::GetX (G4int i) inline
Definition at line 115 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ParticleHPPartial.hh
References X.
Referenced by GetY(), and Sample().
G4double G4ParticleHPPartial::GetX (G4int i, G4int j) inline
Definition at line 117 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ParticleHPPartial.hh
G4double G4ParticleHPPartial::GetY (G4int i, G4int j) inline
Definition at line 118 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ParticleHPPartial.hh
Referenced by G4ParticleHPPhotonDist::GetPhotons(), GetY(), and Sample().
G4double G4ParticleHPPartial::GetY (G4int i, G4double e) inline
Definition at line 119 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ParticleHPPartial.hh
G4ParticleHPVector * G4ParticleHPPartial::GetY (G4double e1)
Definition at line 38 of file G4ParticleHPPartial.cc.
View newest version in sPHENIX GitHub at line 38 of file G4ParticleHPPartial.cc
References e1, G4InterpolationManager::GetScheme(), GetX(), GetY(), G4ParticleHPInterpolator::Interpolate(), min, nData, G4ParticleHPVector::SetData(), G4ParticleHPVector::SetInterpolationManager(), G4ParticleHPVector::SetScheme(), theInt, theManager, X, x1, x2, y, y1, and y2.
void G4ParticleHPPartial::Init (std::istream & aDataFile) inline
Definition at line 71 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ParticleHPPartial.hh
References e, CLHEP::eV, InitData(), nData, and SetX().
Referenced by G4ParticleHPPhotonDist::InitEnergies().
void G4ParticleHPPartial::InitData (G4int i, std::istream & aDataFile, G4double unit = 1.) inline
Definition at line 84 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPPartial.hh
References demo::pg, SetX(), and SetY().
Referenced by Init(), and G4ParticleHPAngular::Init().
void G4ParticleHPPartial::InitInterpolation (G4int i, std::istream & aDataFile) inline
Definition at line 61 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPPartial.hh
Referenced by G4ParticleHPElasticFS::Init(), G4ParticleHPAngular::Init(), and G4ParticleHPPhotonDist::InitEnergies().
void G4ParticleHPPartial::InitInterpolation (std::istream & aDataFile) inline
Definition at line 66 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPPartial.hh
References G4InterpolationManager::Init(), and theManager.
G4double G4ParticleHPPartial::Sample (G4double x)
Definition at line 105 of file G4ParticleHPPartial.cc.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPPartial.cc
References kdfinder::abs(), GetNEntries(), G4InterpolationManager::GetScheme(), GetX(), GetY(), G4ParticleHPInterpolator::Interpolate(), nData, G4ParticleHPVector::Sample(), G4ParticleHPVector::SetInterpolationManager(), G4ParticleHPVector::SetScheme(), G4ParticleHPVector::SetX(), G4ParticleHPVector::SetY(), theInt, theManager, X, x, x1, x2, y1, and y2.
Referenced by G4ParticleHPElasticFS::ApplyYourself(), and G4ParticleHPAngular::SampleAndUpdate().
void G4ParticleHPPartial::SetT (G4int i, G4double x) inline
Definition at line 110 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPPartial.hh
References T, and x.
Referenced by G4ParticleHPElasticFS::Init(), and G4ParticleHPAngular::Init().
void G4ParticleHPPartial::SetX (G4int i, G4double x) inline
Definition at line 109 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPPartial.hh
References X, and x.
Referenced by G4ParticleHPElasticFS::Init(), Init(), G4ParticleHPAngular::Init(), and InitData().
void G4ParticleHPPartial::SetX (G4int i, G4int j, G4double x) inline
Definition at line 111 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPPartial.hh
void G4ParticleHPPartial::SetY (G4int i, G4int j, G4double y) inline
Definition at line 112 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPPartial.hh
Referenced by G4ParticleHPElasticFS::Init(), and InitData().
Member Data Documentation
G4ParticleHPVector* G4ParticleHPPartial::data private
Definition at line 128 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleHPPartial.hh
Referenced by ~G4ParticleHPPartial().
G4int G4ParticleHPPartial::nData private
Definition at line 131 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ParticleHPPartial.hh
Referenced by G4ParticleHPPartial(), GetNumberOfEnergies(), GetY(), Init(), and Sample().
G4double* G4ParticleHPPartial::T private
Definition at line 127 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ParticleHPPartial.hh
Referenced by G4ParticleHPPartial(), GetT(), SetT(), and ~G4ParticleHPPartial().
G4ParticleHPInterpolator G4ParticleHPPartial::theInt private
Definition at line 133 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ParticleHPPartial.hh
Referenced by GetY(), and Sample().
G4InterpolationManager G4ParticleHPPartial::theManager private
Definition at line 132 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ParticleHPPartial.hh
Referenced by GetY(), InitInterpolation(), and Sample().
G4double* G4ParticleHPPartial::X private
Definition at line 126 of file G4ParticleHPPartial.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleHPPartial.hh
Referenced by G4ParticleHPPartial(), GetX(), GetY(), Sample(), SetX(), and ~G4ParticleHPPartial().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPPartial.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPPartial.cc