ECCE @ EIC Software: G4HadronicEPTestMessenger Class Reference
G4HadronicEPTestMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4HadronicEPTestMessenger.hh>
Public Member Functions
G4HadronicEPTestMessenger (G4HadronicProcessStore *theProcessStore)
~G4HadronicEPTestMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4HadronicProcessStore * theProcessStore
G4UIdirectory * heptstDirectory
G4UIcmdWithAnInteger * reportLvlCmd
G4UIcmdWithADouble * procRelLvlCmd
G4UIcmdWithADoubleAndUnit * procAbsLvlCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 50 of file G4HadronicEPTestMessenger.hh.
View newest version in sPHENIX GitHub at line 50 of file G4HadronicEPTestMessenger.hh
Constructor & Destructor Documentation
G4HadronicEPTestMessenger::G4HadronicEPTestMessenger (G4HadronicProcessStore * theProcessStore)
Definition at line 34 of file G4HadronicEPTestMessenger.cc.
View newest version in sPHENIX GitHub at line 34 of file G4HadronicEPTestMessenger.cc
References heptstDirectory, procAbsLvlCmd, procRelLvlCmd, reportLvlCmd, G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
G4HadronicEPTestMessenger::~G4HadronicEPTestMessenger ()
Definition at line 68 of file G4HadronicEPTestMessenger.cc.
View newest version in sPHENIX GitHub at line 68 of file G4HadronicEPTestMessenger.cc
References heptstDirectory, procAbsLvlCmd, procRelLvlCmd, and reportLvlCmd.
Member Function Documentation
void G4HadronicEPTestMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 77 of file G4HadronicEPTestMessenger.cc.
View newest version in sPHENIX GitHub at line 77 of file G4HadronicEPTestMessenger.cc
References G4UIcmdWithADouble::GetNewDoubleValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), procAbsLvlCmd, procRelLvlCmd, reportLvlCmd, G4HadronicProcessStore::SetEpReportLevel(), G4HadronicProcessStore::SetProcessAbsLevel(), G4HadronicProcessStore::SetProcessRelLevel(), and theProcessStore.
Member Data Documentation
G4UIdirectory* G4HadronicEPTestMessenger::heptstDirectory private
Definition at line 62 of file G4HadronicEPTestMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4HadronicEPTestMessenger.hh
Referenced by G4HadronicEPTestMessenger(), and ~G4HadronicEPTestMessenger().
G4UIcmdWithADoubleAndUnit* G4HadronicEPTestMessenger::procAbsLvlCmd private
Definition at line 65 of file G4HadronicEPTestMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4HadronicEPTestMessenger.hh
Referenced by G4HadronicEPTestMessenger(), SetNewValue(), and ~G4HadronicEPTestMessenger().
G4UIcmdWithADouble* G4HadronicEPTestMessenger::procRelLvlCmd private
Definition at line 64 of file G4HadronicEPTestMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4HadronicEPTestMessenger.hh
Referenced by G4HadronicEPTestMessenger(), SetNewValue(), and ~G4HadronicEPTestMessenger().
G4UIcmdWithAnInteger* G4HadronicEPTestMessenger::reportLvlCmd private
Definition at line 63 of file G4HadronicEPTestMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4HadronicEPTestMessenger.hh
Referenced by G4HadronicEPTestMessenger(), SetNewValue(), and ~G4HadronicEPTestMessenger().
G4HadronicProcessStore* G4HadronicEPTestMessenger::theProcessStore private
Definition at line 60 of file G4HadronicEPTestMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file G4HadronicEPTestMessenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4HadronicEPTestMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/src/G4HadronicEPTestMessenger.cc