ECCE @ EIC Software: G4DNAModelInterface Class Reference
G4DNAModelInterface Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAModelInterface.hh>
Public Member Functions
G4DNAModelInterface (const G4String &nam)
G4DNAModelManager Constructor.
virtual ~G4DNAModelInterface ()
~G4DNAModelManager Destructor
virtual void Initialise (const G4ParticleDefinition *particle, const G4DataVector &cuts)
Initialise Initialise method to call all the initialise methods of the registered models.
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
CrossSectionPerVolume Method called by the process and used to call the CrossSectionPerVolume method of the registered models. The method also calculates through G4DNAMolecularMaterial the number of molecule per volume unit for the current material or (component of a composite material).
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *fVect, const G4MaterialCutsCouple *couple, const G4DynamicParticle *aDynamicElectron, G4double tmin, G4double tmax)
SampleSecondaries Used to call the SampleSecondaries method of the registered models. A sampling is done to select a component if the material is a composite one.
void RegisterModel (G4VDNAModel *model)
RegisterModel Method used to associate a model with the interaction.
void RegisterModel (G4VEmModel *model, const G4ParticleDefinition *particle)
G4String GetSelectedMaterial ()
GetSelectedMaterial To allow the user to retrieve the selected material in case of a composite material.
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Types
typedef std::map< const
G4String,std::map< const
G4String, std::vector
< G4VDNAModel * > > > MaterialParticleModelTable
Private Member Functions
void BuildMaterialParticleModelTable (const G4ParticleDefinition *p)
BuildMaterialParticleModelTable Method used to build a map allowing the code to quickly retrieve the good model for a particle/material couple.
void BuildMaterialMolPerVolTable ()
void InsertModelInTable (const G4String &matName, const G4String &pName)
InsertModelInTable Used to put a model in the table after performing some checks.
G4VDNAModel * GetDNAModel (const G4String &material, const G4String &particle, G4double ekin)
GetDNAModel.
G4double GetNumMoleculePerVolumeUnitForMaterial (const G4Material *mat)
G4double GetNumMolPerVolUnitForComponentInComposite (const G4Material *component, const G4Material *composite)
G4DNAModelInterface (const G4DNAModelInterface &)
G4DNAModelInterface & operator= (const G4DNAModelInterface &right)
Private Attributes
const G4String fName
name of the interaction
G4ParticleChangeForGamma * fpParticleChangeForGamma
pointer used to change the characteristics of the current particle
std::vector< G4VDNAModel * > fRegisteredModels
vector containing all the registered models
std::map< const G4String,
G4double > fMaterialCS
map used to share information between CrossSectionPerVolume and SampleSecondaries
G4double fCSsumTot
value which contains the sum of all the component cross sections in case of a composite material
G4String fSampledMat
for the user to retrieve selected material/component
MaterialParticleModelTable fMaterialParticleModelTable
map: [materialName][particleName] = vector of models
std::map< G4String, const
std::vector< double > * > fMaterialMolPerVol
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 45 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 45 of file G4DNAModelInterface.hh
Member Typedef Documentation
typedef std::map<const G4String ,std::map<const G4String , std::vector<G4VDNAModel*> > > G4DNAModelInterface::MaterialParticleModelTable private
Definition at line 135 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 135 of file G4DNAModelInterface.hh
Constructor & Destructor Documentation
G4DNAModelInterface::G4DNAModelInterface (const G4String & nam)
G4DNAModelManager Constructor.
Parameters
nam
Definition at line 37 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 37 of file G4DNAModelInterface.cc
G4DNAModelInterface::~G4DNAModelInterface () virtual
~G4DNAModelManager Destructor
Definition at line 45 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 45 of file G4DNAModelInterface.cc
References fRegisteredModels.
G4DNAModelInterface::G4DNAModelInterface (const G4DNAModelInterface &) private
Member Function Documentation
void G4DNAModelInterface::BuildMaterialMolPerVolTable () private
Definition at line 402 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 402 of file G4DNAModelInterface.cc
References G4String::first(), fMaterialMolPerVol, fMaterialParticleModelTable, G4Material::GetMaterialTable(), G4Material::GetName(), G4DNAMolecularMaterial::GetNumMolPerVolTableFor(), G4DNAMolecularMaterial::Initialize(), G4DNAMolecularMaterial::Instance(), and it.
Referenced by Initialise().
void G4DNAModelInterface::BuildMaterialParticleModelTable (const G4ParticleDefinition * p) private
BuildMaterialParticleModelTable Method used to build a map allowing the code to quickly retrieve the good model for a particle/material couple.
Parameters
p
Definition at line 330 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 330 of file G4DNAModelInterface.cc
References G4Material::GetMatComponents(), G4Material::GetMaterialTable(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), InsertModelInTable(), it, k, and mat.
Referenced by Initialise().
G4double G4DNAModelInterface::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
CrossSectionPerVolume Method called by the process and used to call the CrossSectionPerVolume method of the registered models. The method also calculates through G4DNAMolecularMaterial the number of molecule per volume unit for the current material or (component of a composite material).
Parameters
material
p
ekin
emin
emax
Returns
the final cross section value times with the number of molecule per volume unit
Reimplemented from G4VEmModel.
Definition at line 84 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 84 of file G4DNAModelInterface.cc
References G4VDNAModel::CrossSectionPerVolume(), fCSsumTot, fMaterialCS, fSampledMat, GetDNAModel(), G4Material::GetMatComponents(), G4Material::GetName(), GetNumMoleculePerVolumeUnitForMaterial(), GetNumMolPerVolUnitForComponentInComposite(), G4ParticleDefinition::GetParticleName(), and it.
G4VDNAModel * G4DNAModelInterface::GetDNAModel (const G4String & material, const G4String & particle, G4double ekin) private
GetDNAModel.
Parameters
material
particle
ekin
Returns
G4VDNAModel* Return the model corresponding to the material, particle and energy specified. This method will check the energy range of the models to find to good one for the current ekin.
Definition at line 586 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 586 of file G4DNAModelInterface.cc
References fMaterialParticleModelTable, material(), and particle.
Referenced by CrossSectionPerVolume(), and SampleSecondaries().
G4double G4DNAModelInterface::GetNumMoleculePerVolumeUnitForMaterial (const G4Material * mat) private
Definition at line 636 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 636 of file G4DNAModelInterface.cc
References fMaterialMolPerVol, G4Material::GetIndex(), and G4Material::GetName().
Referenced by CrossSectionPerVolume().
G4double G4DNAModelInterface::GetNumMolPerVolUnitForComponentInComposite (const G4Material * component, const G4Material * composite) private
Definition at line 643 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 643 of file G4DNAModelInterface.cc
References fMaterialMolPerVol, G4Material::GetIndex(), and G4Material::GetName().
Referenced by CrossSectionPerVolume().
G4String G4DNAModelInterface::GetSelectedMaterial () inline
GetSelectedMaterial To allow the user to retrieve the selected material in case of a composite material.
Returns
the last selected material by SampleSecondaries.
Definition at line 119 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 119 of file G4DNAModelInterface.hh
References fSampledMat.
void G4DNAModelInterface::Initialise (const G4ParticleDefinition * particle, const G4DataVector & cuts) virtual
Initialise Initialise method to call all the initialise methods of the registered models.
Parameters
particle
cuts
Implements G4VEmModel.
Definition at line 56 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 56 of file G4DNAModelInterface.cc
References BuildMaterialMolPerVolTable(), BuildMaterialParticleModelTable(), DBL_MAX, fpParticleChangeForGamma, fRegisteredModels, G4VEmModel::GetParticleChangeForGamma(), G4VEmModel::SetHighEnergyLimit(), and G4VEmModel::SetLowEnergyLimit().
void G4DNAModelInterface::InsertModelInTable (const G4String & matName, const G4String & pName) private
InsertModelInTable Used to put a model in the table after performing some checks.
Parameters
matName
pName
Definition at line 437 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 437 of file G4DNAModelInterface.cc
References kdfinder::abs(), eV, FatalException, fMaterialParticleModelTable, fName, fRegisteredModels, G4Exception(), and it.
Referenced by BuildMaterialParticleModelTable().
G4DNAModelInterface& G4DNAModelInterface::operator= (const G4DNAModelInterface & right) private
void G4DNAModelInterface::RegisterModel (G4VDNAModel * model)
RegisterModel Method used to associate a model with the interaction.
Parameters
model
Definition at line 316 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 316 of file G4DNAModelInterface.cc
References fRegisteredModels.
Referenced by RegisterModel().
void G4DNAModelInterface::RegisterModel (G4VEmModel * model, const G4ParticleDefinition * particle)
Definition at line 321 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 321 of file G4DNAModelInterface.cc
References G4VEmModel::GetName(), and RegisterModel().
void G4DNAModelInterface::SampleSecondaries (std::vector< G4DynamicParticle * > * fVect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicElectron, G4double tmin, G4double tmax) virtual
SampleSecondaries Used to call the SampleSecondaries method of the registered models. A sampling is done to select a component if the material is a composite one.
Parameters
fVect
couple
aDynamicElectron
tmin
tmax
Implements G4VEmModel.
Definition at line 208 of file G4DNAModelInterface.cc.
View newest version in sPHENIX GitHub at line 208 of file G4DNAModelInterface.cc
References DBL_MAX, FatalException, fCSsumTot, fMaterialCS, fpParticleChangeForGamma, fSampledMat, G4Exception(), G4UniformRand, GetDNAModel(), G4DynamicParticle::GetKineticEnergy(), G4Material::GetMatComponents(), G4MaterialCutsCouple::GetMaterial(), G4Material::GetName(), G4DynamicParticle::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), it, and G4VDNAModel::SampleSecondaries().
Member Data Documentation
G4double G4DNAModelInterface::fCSsumTot private
value which contains the sum of all the component cross sections in case of a composite material
Definition at line 131 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 131 of file G4DNAModelInterface.hh
Referenced by CrossSectionPerVolume(), and SampleSecondaries().
std::map<const G4String, G4double> G4DNAModelInterface::fMaterialCS private
map used to share information between CrossSectionPerVolume and SampleSecondaries
Definition at line 129 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 129 of file G4DNAModelInterface.hh
Referenced by CrossSectionPerVolume(), and SampleSecondaries().
std::map<G4String, const std::vector<double>* > G4DNAModelInterface::fMaterialMolPerVol private
Definition at line 138 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 138 of file G4DNAModelInterface.hh
Referenced by BuildMaterialMolPerVolTable(), GetNumMoleculePerVolumeUnitForMaterial(), and GetNumMolPerVolUnitForComponentInComposite().
MaterialParticleModelTable G4DNAModelInterface::fMaterialParticleModelTable private
map: [materialName][particleName] = vector of models
Definition at line 136 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 136 of file G4DNAModelInterface.hh
Referenced by BuildMaterialMolPerVolTable(), GetDNAModel(), and InsertModelInTable().
const G4String G4DNAModelInterface::fName private
name of the interaction
Definition at line 123 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 123 of file G4DNAModelInterface.hh
Referenced by InsertModelInTable().
G4ParticleChangeForGamma* G4DNAModelInterface::fpParticleChangeForGamma private
pointer used to change the characteristics of the current particle
Definition at line 125 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 125 of file G4DNAModelInterface.hh
Referenced by Initialise(), and SampleSecondaries().
std::vector<G4VDNAModel*> G4DNAModelInterface::fRegisteredModels private
vector containing all the registered models
Definition at line 127 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 127 of file G4DNAModelInterface.hh
Referenced by Initialise(), InsertModelInTable(), RegisterModel(), and ~G4DNAModelInterface().
G4String G4DNAModelInterface::fSampledMat private
for the user to retrieve selected material/component
Definition at line 133 of file G4DNAModelInterface.hh.
View newest version in sPHENIX GitHub at line 133 of file G4DNAModelInterface.hh
Referenced by CrossSectionPerVolume(), GetSelectedMaterial(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAModelInterface.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAModelInterface.cc