ECCE @ EIC Software: G4eLowEnergyLoss Class Reference
G4eLowEnergyLoss Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4eLowEnergyLoss.hh>
Public Member Functions
G4eLowEnergyLoss (const G4String &)
~G4eLowEnergyLoss ()
G4bool IsApplicable (const G4ParticleDefinition &)
void BuildDEDXTable (const G4ParticleDefinition &aParticleType)
G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &Step)
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)=0
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step)=0
void ActivateFluorescence (G4bool val)
G4bool Fluorescence () const
Public Member Functions inherited from G4RDVeLowEnergyLoss
G4RDVeLowEnergyLoss (const G4String &, G4ProcessType aType=fNotDefined)
G4RDVeLowEnergyLoss (G4RDVeLowEnergyLoss &)
virtual ~G4RDVeLowEnergyLoss ()
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static void SetNbOfProcesses (G4int nb)
static void PlusNbOfProcesses ()
static void MinusNbOfProcesses ()
static G4int GetNbOfProcesses ()
static void SetLowerBoundEloss (G4double val)
static void SetUpperBoundEloss (G4double val)
static void SetNbinEloss (G4int nb)
static G4double GetLowerBoundEloss ()
static G4double GetUpperBoundEloss ()
static G4int GetNbinEloss ()
Static Public Member Functions inherited from G4RDVeLowEnergyLoss
static void SetRndmStep (G4bool value)
static void SetEnlossFluc (G4bool value)
static void SetStepFunction (G4double c1, G4double c2)
Protected Member Functions
virtual std::vector
< G4DynamicParticle * > * DeexciteAtom (const G4MaterialCutsCouple *, G4double, G4double)
Protected Member Functions inherited from G4RDVeLowEnergyLoss
G4double GetLossWithFluct (const G4DynamicParticle *aParticle, const G4MaterialCutsCouple *couple, G4double MeanLoss, G4double step)
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4PhysicsTable * theLossTable
G4double MinKineticEnergy
G4double Charge
G4double lastCharge
Protected Attributes inherited from G4RDVeLowEnergyLoss
const G4Material * lastMaterial
G4int imat
G4double f1Fluct
G4double f2Fluct
G4double e1Fluct
G4double e2Fluct
G4double rateFluct
G4double ipotFluct
G4double e1LogFluct
G4double e2LogFluct
G4double ipotLogFluct
const G4int nmaxCont1
const G4int nmaxCont2
Static Protected Attributes
static G4PhysicsTable * theDEDXElectronTable = 0
static G4PhysicsTable * theDEDXPositronTable = 0
static G4PhysicsTable * theRangeElectronTable = 0
static G4PhysicsTable * theRangePositronTable = 0
static G4PhysicsTable * theInverseRangeElectronTable = 0
static G4PhysicsTable * theInverseRangePositronTable = 0
static G4PhysicsTable * theLabTimeElectronTable = 0
static G4PhysicsTable * theLabTimePositronTable = 0
static G4PhysicsTable * theProperTimeElectronTable = 0
static G4PhysicsTable * theProperTimePositronTable = 0
static G4int NbOfProcesses = 2
static G4int CounterOfElectronProcess = 0
static G4int CounterOfPositronProcess = 0
static G4PhysicsTable ** RecorderOfElectronProcess
static G4PhysicsTable ** RecorderOfPositronProcess
Static Protected Attributes inherited from G4RDVeLowEnergyLoss
static G4double ParticleMass
static G4double taulow
static G4double tauhigh
static G4double ltaulow
static G4double ltauhigh
static G4double dRoverRange = 20*perCent
static G4double finalRange = 200*micrometer
static G4double c1lim = dRoverRange
static G4double c2lim = 2.*(1.-dRoverRange)*finalRange
static G4double c3lim = -(1.-dRoverRange)*finalRange*finalRange
static G4bool rndmStepFlag = false
static G4bool EnlossFlucFlag = true
Private Member Functions
G4double GetConstraints (const G4DynamicParticle *aParticle, const G4MaterialCutsCouple *couple)
G4eLowEnergyLoss (G4eLowEnergyLoss &)
G4eLowEnergyLoss & operator= (const G4eLowEnergyLoss &right)
Private Attributes
G4PhysicsTable * theDEDXTable
G4int CounterOfProcess
G4PhysicsTable ** RecorderOfProcess
G4double fdEdx
G4double fRangeNow
G4double linLossLimit
G4ParticleChangeForLoss fParticleChange
G4bool theFluo
Static Private Attributes
static G4int NbinEloss = 360
static G4double LowerBoundEloss = 10.*eV
static G4double UpperBoundEloss = 100.*GeV
static G4double RTable
static G4double LOGRTable
static G4PhysicsTable * theeRangeCoeffATable = 0
static G4PhysicsTable * theeRangeCoeffBTable = 0
static G4PhysicsTable * theeRangeCoeffCTable = 0
static G4PhysicsTable * thepRangeCoeffATable = 0
static G4PhysicsTable * thepRangeCoeffBTable = 0
static G4PhysicsTable * thepRangeCoeffCTable = 0
static G4EnergyLossMessenger * eLossMessenger = 0
Additional Inherited Members
Static Protected Member Functions inherited from G4RDVeLowEnergyLoss
static G4PhysicsTable * BuildRangeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *theRangeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildLabTimeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *theLabTimeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildProperTimeTable (G4PhysicsTable *theDEDXTable, G4PhysicsTable *ProperTimeTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffATable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffATable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffBTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffBTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildRangeCoeffCTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theCoeffCTable, G4double Tmin, G4double Tmax, G4int nbin)
static G4PhysicsTable * BuildInverseRangeTable (G4PhysicsTable *theRangeTable, G4PhysicsTable *theRangeCoeffATable, G4PhysicsTable *theRangeCoeffBTable, G4PhysicsTable *theRangeCoeffCTable, G4PhysicsTable *theInverseRangeTable, G4double Tmin, G4double Tmax, G4int nbin)
Detailed Description
Definition at line 85 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 85 of file G4eLowEnergyLoss.hh
Constructor & Destructor Documentation
G4eLowEnergyLoss::G4eLowEnergyLoss (const G4String & processName)
Definition at line 125 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 125 of file G4eLowEnergyLoss.cc
References eLossMessenger.
G4eLowEnergyLoss::~G4eLowEnergyLoss ()
Definition at line 146 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 146 of file G4eLowEnergyLoss.cc
References G4PhysicsTable::clearAndDestroy(), and theLossTable.
G4eLowEnergyLoss::G4eLowEnergyLoss (G4eLowEnergyLoss &) private
Member Function Documentation
void G4eLowEnergyLoss::ActivateFluorescence (G4bool val)
G4VParticleChange * G4eLowEnergyLoss::AlongStepDoIt (const G4Track & track, const G4Step & Step) virtual
Implements G4RDVeLowEnergyLoss.
Definition at line 397 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 397 of file G4eLowEnergyLoss.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, Charge, DeexciteAtom(), deltaR(), E, edep, G4Electron::Electron(), G4RDVeLowEnergyLoss::EnlossFlucFlag, fdEdx, fRangeNow, fStopAndKill, fStopButAlive, G4UniformRand, G4Track::GetDynamicParticle(), G4StepPoint::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4Track::GetMaterialCutsCouple(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4EnergyLossTables::GetPreciseEnergyFromRange(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4ParticleChange::Initialize(), linLossLimit, LowerBoundEloss, MinKineticEnergy, part, position, G4Positron::Positron(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), r, G4VParticleChange::SetNumberOfSecondaries(), t, theFluo, Acts::VectorHelpers::time(), and UpperBoundEloss.
void G4eLowEnergyLoss::BuildDEDXTable (const G4ParticleDefinition & aParticleType)
Definition at line 206 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 206 of file G4eLowEnergyLoss.cc
References G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildLabTimeTable(), G4RDVeLowEnergyLoss::BuildProperTimeTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffATable(), G4RDVeLowEnergyLoss::BuildRangeCoeffBTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffCTable(), G4RDVeLowEnergyLoss::BuildRangeTable(), Charge, G4PhysicsTable::clearAndDestroy(), CounterOfElectronProcess, CounterOfPositronProcess, CounterOfProcess, G4Electron::Electron(), eplus, G4cout, G4endl, G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4PhysicsTable::insert(), LOGRTable, LowerBoundEloss, NbinEloss, NbOfProcesses, G4RDVeLowEnergyLoss::ParticleMass, G4Positron::Positron(), G4PhysicsVector::PutValue(), RecorderOfElectronProcess, RecorderOfPositronProcess, RecorderOfProcess, G4EnergyLossTables::Register(), RTable, theDEDXElectronTable, theDEDXPositronTable, theDEDXTable, theeRangeCoeffATable, theeRangeCoeffBTable, theeRangeCoeffCTable, theInverseRangeElectronTable, theInverseRangePositronTable, theLabTimeElectronTable, theLabTimePositronTable, thepRangeCoeffATable, thepRangeCoeffBTable, thepRangeCoeffCTable, theProperTimeElectronTable, theProperTimePositronTable, theRangeElectronTable, theRangePositronTable, UpperBoundEloss, and G4VProcess::verboseLevel.
Referenced by G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
virtual std::vector<G4DynamicParticle*>* G4eLowEnergyLoss::DeexciteAtom (const G4MaterialCutsCouple * , G4double , G4double) inline protected virtual
Reimplemented in G4LowEnergyIonisation.
Definition at line 152 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 152 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt().
G4bool G4eLowEnergyLoss::Fluorescence () const
Referenced by G4LowEnergyIonisation::PostStepDoIt().
G4double G4eLowEnergyLoss::GetConstraints (const G4DynamicParticle * aParticle, const G4MaterialCutsCouple * couple) private
G4double G4eLowEnergyLoss::GetContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety) virtual
Implements G4RDVeLowEnergyLoss.
G4double G4eLowEnergyLoss::GetLowerBoundEloss () static
Definition at line 190 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 190 of file G4eLowEnergyLoss.cc
References LowerBoundEloss.
Referenced by G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
virtual G4double G4eLowEnergyLoss::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) pure virtual
Implements G4RDVeLowEnergyLoss.
Implemented in G4LowEnergyBremsstrahlung, and G4LowEnergyIonisation.
G4int G4eLowEnergyLoss::GetNbinEloss () static
Definition at line 200 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 200 of file G4eLowEnergyLoss.cc
References NbinEloss.
Referenced by G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
G4int G4eLowEnergyLoss::GetNbOfProcesses () static
Definition at line 170 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 170 of file G4eLowEnergyLoss.cc
References NbOfProcesses.
G4double G4eLowEnergyLoss::GetUpperBoundEloss () static
Definition at line 195 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 195 of file G4eLowEnergyLoss.cc
References UpperBoundEloss.
Referenced by G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
G4bool G4eLowEnergyLoss::IsApplicable (const G4ParticleDefinition &) virtual
Reimplemented from G4VProcess.
Reimplemented in G4LowEnergyBremsstrahlung, and G4LowEnergyIonisation.
void G4eLowEnergyLoss::MinusNbOfProcesses () static
Definition at line 165 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 165 of file G4eLowEnergyLoss.cc
References NbOfProcesses.
G4eLowEnergyLoss& G4eLowEnergyLoss::operator= (const G4eLowEnergyLoss & right) private
void G4eLowEnergyLoss::PlusNbOfProcesses () static
Definition at line 160 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 160 of file G4eLowEnergyLoss.cc
References NbOfProcesses.
virtual G4VParticleChange* G4eLowEnergyLoss::PostStepDoIt (const G4Track & track, const G4Step & step) pure virtual
Implements G4RDVeLowEnergyLoss.
Implemented in G4LowEnergyBremsstrahlung, and G4LowEnergyIonisation.
void G4eLowEnergyLoss::SetLowerBoundEloss (G4double val) static
Definition at line 175 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 175 of file G4eLowEnergyLoss.cc
References LowerBoundEloss.
void G4eLowEnergyLoss::SetNbinEloss (G4int nb) static
Definition at line 185 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 185 of file G4eLowEnergyLoss.cc
References NbinEloss.
void G4eLowEnergyLoss::SetNbOfProcesses (G4int nb) static
Definition at line 155 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 155 of file G4eLowEnergyLoss.cc
References NbOfProcesses.
void G4eLowEnergyLoss::SetUpperBoundEloss (G4double val) static
Definition at line 180 of file G4eLowEnergyLoss.cc.
View newest version in sPHENIX GitHub at line 180 of file G4eLowEnergyLoss.cc
References UpperBoundEloss.
Member Data Documentation
G4double G4eLowEnergyLoss::Charge protected
Definition at line 162 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 162 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt(), and BuildDEDXTable().
G4int G4eLowEnergyLoss::CounterOfElectronProcess = 0 static protected
Definition at line 185 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 185 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable(), G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
G4int G4eLowEnergyLoss::CounterOfPositronProcess = 0 static protected
Definition at line 186 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 186 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable(), G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
G4int G4eLowEnergyLoss::CounterOfProcess private
Definition at line 203 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 203 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4EnergyLossMessenger * G4eLowEnergyLoss::eLossMessenger = 0 static private
Definition at line 235 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 235 of file G4eLowEnergyLoss.hh
Referenced by G4eLowEnergyLoss().
G4double G4eLowEnergyLoss::fdEdx private
Definition at line 206 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 206 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt().
G4ParticleChangeForLoss G4eLowEnergyLoss::fParticleChange private
Definition at line 213 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 213 of file G4eLowEnergyLoss.hh
G4double G4eLowEnergyLoss::fRangeNow private
Definition at line 207 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 207 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt().
G4double G4eLowEnergyLoss::lastCharge protected
Definition at line 162 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 162 of file G4eLowEnergyLoss.hh
G4double G4eLowEnergyLoss::linLossLimit private
Definition at line 209 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 209 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt().
G4double G4eLowEnergyLoss::LOGRTable static private
Definition at line 223 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 223 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4double G4eLowEnergyLoss::LowerBoundEloss = 10.*eV static private
Definition at line 221 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 221 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt(), BuildDEDXTable(), GetLowerBoundEloss(), and SetLowerBoundEloss().
G4double G4eLowEnergyLoss::MinKineticEnergy protected
Definition at line 158 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 158 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt().
G4int G4eLowEnergyLoss::NbinEloss = 360 static private
Definition at line 219 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 219 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable(), GetNbinEloss(), and SetNbinEloss().
G4int G4eLowEnergyLoss::NbOfProcesses = 2 static protected
Definition at line 184 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 184 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable(), GetNbOfProcesses(), MinusNbOfProcesses(), PlusNbOfProcesses(), and SetNbOfProcesses().
G4PhysicsTable ** G4eLowEnergyLoss::RecorderOfElectronProcess static protected
Initial value:
=
                                           new G4PhysicsTable*[10]
Definition at line 187 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 187 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable(), G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
G4PhysicsTable ** G4eLowEnergyLoss::RecorderOfPositronProcess static protected
Initial value:
=
                                           new G4PhysicsTable*[10]
Definition at line 188 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 188 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable(), G4LowEnergyIonisation::BuildPhysicsTable(), and G4LowEnergyBremsstrahlung::BuildPhysicsTable().
G4PhysicsTable** G4eLowEnergyLoss::RecorderOfProcess private
Definition at line 204 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 204 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4double G4eLowEnergyLoss::RTable static private
Definition at line 223 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 223 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theDEDXElectronTable = 0 static protected
Definition at line 165 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 165 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theDEDXPositronTable = 0 static protected
Definition at line 166 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 166 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable* G4eLowEnergyLoss::theDEDXTable private
Definition at line 201 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 201 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theeRangeCoeffATable = 0 static private
Definition at line 228 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 228 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theeRangeCoeffBTable = 0 static private
Definition at line 229 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 229 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theeRangeCoeffCTable = 0 static private
Definition at line 230 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 230 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4bool G4eLowEnergyLoss::theFluo private
Definition at line 237 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 237 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt().
G4PhysicsTable * G4eLowEnergyLoss::theInverseRangeElectronTable = 0 static protected
Definition at line 171 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 171 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theInverseRangePositronTable = 0 static protected
Definition at line 172 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 172 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theLabTimeElectronTable = 0 static protected
Definition at line 175 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 175 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theLabTimePositronTable = 0 static protected
Definition at line 176 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 176 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable* G4eLowEnergyLoss::theLossTable protected
Definition at line 154 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 154 of file G4eLowEnergyLoss.hh
Referenced by G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), and ~G4eLowEnergyLoss().
G4PhysicsTable * G4eLowEnergyLoss::thepRangeCoeffATable = 0 static private
Definition at line 231 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 231 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::thepRangeCoeffBTable = 0 static private
Definition at line 232 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 232 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::thepRangeCoeffCTable = 0 static private
Definition at line 233 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 233 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theProperTimeElectronTable = 0 static protected
Definition at line 177 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 177 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theProperTimePositronTable = 0 static protected
Definition at line 178 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 178 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theRangeElectronTable = 0 static protected
Definition at line 167 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 167 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4PhysicsTable * G4eLowEnergyLoss::theRangePositronTable = 0 static protected
Definition at line 168 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 168 of file G4eLowEnergyLoss.hh
Referenced by BuildDEDXTable().
G4double G4eLowEnergyLoss::UpperBoundEloss = 100.*GeV static private
Definition at line 222 of file G4eLowEnergyLoss.hh.
View newest version in sPHENIX GitHub at line 222 of file G4eLowEnergyLoss.hh
Referenced by AlongStepDoIt(), BuildDEDXTable(), GetUpperBoundEloss(), and SetUpperBoundEloss().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4eLowEnergyLoss.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4eLowEnergyLoss.cc