ECCE @ EIC Software: PrimaryGeneratorAction Class Reference
PrimaryGeneratorAction Class Reference
The primary generator action class with particle gun.
#include <geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PrimaryGeneratorAction.hh>
Inherits G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VStateDependent, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VStateDependent, G4VUserPrimaryGeneratorAction, G4VStateDependent, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VStateDependent, G4VUserPrimaryGeneratorAction, G4VStateDependent, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VStateDependent, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, G4VUserPrimaryGeneratorAction, and G4VUserPrimaryGeneratorAction.
Public Member Functions
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic ()
void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic ()
void SetRndmBeam (G4double val)
void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
void SetEmission (G4int)
CLHEP::HepMatrix GetMatrix ()
PrimaryGeneratorAction (AnalysisManager *)
~PrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *anEvent)
PrimaryGeneratorAction (DetectorConstruction *)
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic (G4int)
void SetRndmBeam (G4double val)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic ()
void SetRndmBeam (G4double val)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
void SetRndmBeam (G4bool val)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic ()
void SetRndmBeam (G4double val)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic ()
void SetRndmBeam (G4double val)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetRndmBeam (G4double val)
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetRndmBeam (G4double val)
virtual void GeneratePrimaries (G4Event *)
void ResetEbeamCumul ()
G4double GetEbeamCumul ()
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
void SelectAction (G4int i)
G4int GetSelectedAction ()
PrimaryGeneratorAction0 * GetAction0 ()
PrimaryGeneratorAction1 * GetAction1 ()
PrimaryGeneratorAction2 * GetAction2 ()
PrimaryGeneratorAction3 * GetAction3 ()
PrimaryGeneratorAction4 * GetAction4 ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic ()
void SetRndmBeam (G4double val)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
const G4ParticleGun * GetParticleGun () const
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
const G4ParticleGun * GetParticleGun () const
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
~PrimaryGeneratorAction () override
void GeneratePrimaries (G4Event *event) override
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun () const
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
G4double GetGunArea ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun () const
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun () const
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun () const
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun () const
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun () const
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetRndmBeam (G4double val)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetBeamRadius (G4double val)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
G4double GetBeamRadius ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void RunInitialisation (G4double, G4double)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
G4int GetWallCount ()
void AddWallCount (G4int wc)
G4int GetCavityCount ()
void AddCavityCount (G4int cc)
PrimaryGeneratorAction (DetectorConstruction *pDet)
virtual ~PrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *anEvent)
void SetBeamEnergy (G4double val)
void SetBeamSigmaE (G4double val)
void SetBeamX (G4double val)
void SetBeamY (G4double val)
void SetBeamZ (G4double val)
void SetBeamSigmaX (G4double val)
void SetBeamSigmaY (G4double val)
void SetBeamSigmaZ (G4double val)
void SetBeamMinCosTheta (G4double val)
void SetSigmaTheta (G4double val)
void SetVerbose (G4int val)
void SetRandom (const G4String &type)
G4bool GetVerbose () const
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
void SetOptPhotonPolar ()
void SetOptPhotonPolar (G4double)
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *event)
void SetRandomFlag (G4bool value)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *event)
void SetRandomFlag (G4bool value)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *event)
void SetRandomFlag (G4bool value)
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *event)
void SetRandomFlag (G4bool value)
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction (DetectorConstruction *)
~PrimaryGeneratorAction ()
void SetDefaultKinematic ()
void SetRndmBeam (G4double value)
void SetTimeExposure (G4double value)
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
G4double GetTimeExposure ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
PrimaryGeneratorAction ()
~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
G4ParticleGun * GetParticleGun ()
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Public Attributes
G4int fEmission
Private Member Functions
G4double XYofAngle (G4double)
PrimaryGeneratorAction & operator= (const PrimaryGeneratorAction &right)
PrimaryGeneratorAction (const PrimaryGeneratorAction &)
PrimaryGeneratorAction & operator= (const PrimaryGeneratorAction &right)
PrimaryGeneratorAction (const PrimaryGeneratorAction &)
PrimaryGeneratorAction & operator= (const PrimaryGeneratorAction &right)
PrimaryGeneratorAction (const PrimaryGeneratorAction &)
PrimaryGeneratorAction & operator= (const PrimaryGeneratorAction &right)
PrimaryGeneratorAction (const PrimaryGeneratorAction &)
PrimaryGeneratorAction & operator= (const PrimaryGeneratorAction &right)
PrimaryGeneratorAction (const PrimaryGeneratorAction &)
void InitializeMe ()
PrimaryGeneratorAction & operator= (const PrimaryGeneratorAction &right)
PrimaryGeneratorAction (const PrimaryGeneratorAction &)
Private Attributes
G4ParticleGun * particleGun
DetectorConstruction * Detector
G4double beam
PrimaryGeneratorMessenger * gunMessenger
G4ParticleGun * fParticleGun
DetectorConstruction * fDetector
PrimaryGeneratorMessenger * fGunMessenger
G4double fAngleMax
G4bool fShoot
CLHEP::HepMatrix fBeamMatrix
G4GeneralParticleSource * gun
AnalysisManager * analysis
G4double fRndmBeam
G4bool fRndmBeam
G4double fEbeamCumul
TestParameters * fParam
G4GeneralParticleSource * fParticleGun
PrimaryGeneratorAction0 * fAction0
PrimaryGeneratorAction1 * fAction1
PrimaryGeneratorAction2 * fAction2
PrimaryGeneratorAction3 * fAction3
PrimaryGeneratorAction4 * fAction4
G4int fSelectedAction
PrimaryGenerator * fPrimaryGenerator
G4GeneralParticleSource * fGPS
G4bool bPrimPositionDefined
HistoManager * fHisto
G4ParticleGun * fpParticleGun
std::unique_ptr< G4ParticleGun > fpParticleGun
const DetectorConstruction * fDetector
G4double fGunArea
G4double fZ0
G4double fR2World
G4double fRBeam
G4double fEffWallThick
G4double fCavityThickness
G4double fMassWallRatio
G4int fNwall
G4int fNcavity
G4int fVerbose
PrimaryGeneratorMessenger * fMessenger
G4int fCounter
G4double fX0
G4double fY0
G4double fSigmaX
G4double fSigmaY
G4double fSigmaZ
G4double fRMax2
G4double fSigmaE
G4double fSigmaTheta
G4double fEnergy
G4double fMinCosTheta
G4ThreeVector fPosition
G4ThreeVector fDirection
G4String fGauss
G4ParticleGun * fparticleGun
G4double fTimeExposure
Detailed Description
The primary generator action class with particle gun.
PrimaryGeneratorAction class.
The primary generator action class with particle gum.
It defines a single particle which hits the calorimeter perpendicular to the input face. The type of the particle can be changed via the G4 build-in commands of G4ParticleGun class (see the macros provided with this example).
Definition at line 42 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 42 of file PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction * DC)
Definition at line 44 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 44 of file PrimaryGeneratorAction.cc
References particleGun, and SetDefaultKinematic().
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
Definition at line 53 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.cc
References particleGun.
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
Definition at line 44 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 44 of file PrimaryGeneratorAction.cc
References fParticleGun.
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (AnalysisManager * pAnalysis)
Definition at line 34 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 34 of file PrimaryGeneratorAction.cc
References analysis, and gun.
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (const PrimaryGeneratorAction &) private
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (const PrimaryGeneratorAction &) private
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (const PrimaryGeneratorAction &) private
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (const PrimaryGeneratorAction &) private
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (const PrimaryGeneratorAction &) private
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction () override
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction * pDet)
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (const PrimaryGeneratorAction &) private
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction ()
virtual PrimaryGeneratorAction::~PrimaryGeneratorAction () virtual
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction (DetectorConstruction *)
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
PrimaryGeneratorAction::PrimaryGeneratorAction ()
PrimaryGeneratorAction::~PrimaryGeneratorAction ()
Member Function Documentation
void PrimaryGeneratorAction::AddCavityCount (G4int cc) inline
Definition at line 61 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 61 of file PrimaryGeneratorAction.hh
References fNcavity.
void PrimaryGeneratorAction::AddWallCount (G4int wc) inline
Definition at line 58 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 58 of file PrimaryGeneratorAction.hh
References fNwall.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
void PrimaryGeneratorAction::GeneratePrimaries (G4Event * event) override virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
void PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
void PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
a) Partilces directed to "square" on the XY plane of bounding slice (or YZ, XZ)
b) Partilces directed to "disk" on the XY plane of bounding slice (or YZ, XZ)
c) Partilces directed towards the bounding slice (default option!)
Implements G4VUserPrimaryGeneratorAction.
Definition at line 73 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 73 of file PrimaryGeneratorAction.cc
References G4ParticleGun::GeneratePrimaryVertex(), and particleGun.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event * event) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event * event) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event * event) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event * event) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
void PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
PrimaryGeneratorAction0* PrimaryGeneratorAction::GetAction0 () inline
Definition at line 67 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 67 of file PrimaryGeneratorAction.hh
References fAction0.
PrimaryGeneratorAction1* PrimaryGeneratorAction::GetAction1 () inline
Definition at line 68 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 68 of file PrimaryGeneratorAction.hh
References fAction1.
PrimaryGeneratorAction2* PrimaryGeneratorAction::GetAction2 () inline
Definition at line 69 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file PrimaryGeneratorAction.hh
References fAction2.
PrimaryGeneratorAction3* PrimaryGeneratorAction::GetAction3 () inline
Definition at line 70 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 70 of file PrimaryGeneratorAction.hh
References fAction3.
PrimaryGeneratorAction4* PrimaryGeneratorAction::GetAction4 () inline
Definition at line 71 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 71 of file PrimaryGeneratorAction.hh
References fAction4.
G4double PrimaryGeneratorAction::GetBeamRadius () inline
Definition at line 57 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction.hh
References fRBeam.
Referenced by Run::SurveyConvergence().
G4int PrimaryGeneratorAction::GetCavityCount () inline
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
References fNcavity.
G4double PrimaryGeneratorAction::GetEbeamCumul () inline
Definition at line 57 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction.hh
References fEbeamCumul.
G4double PrimaryGeneratorAction::GetGunArea () inline
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
References fGunArea.
CLHEP::HepMatrix PrimaryGeneratorAction::GetMatrix () inline
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
References fBeamMatrix.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun ()
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 52 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 52 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun * PrimaryGeneratorAction::GetParticleGun () inline
Definition at line 52 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorAction.hh
References particleGun.
Referenced by RunAction::BeginOfRunAction(), RunAction::ComputeMscHighland(), RunAction::ComputeTheory(), EventAction::EndOfEventAction(), Run::EndOfRun(), Run::FillPerEvent(), Run::Run(), Run::SurveyConvergence(), and EventAction::WriteFibers().
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun () inline
Definition at line 52 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorAction.hh
References particleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 52 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 52 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
const G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
const G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 56 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 56 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 56 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 56 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 56 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 56 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction.hh
References fpParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 57 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 57 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 57 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 58 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 58 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 59 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 59 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 59 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryGeneratorAction.hh
References fpParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4ParticleGun* PrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 62 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 62 of file PrimaryGeneratorAction.hh
References fParticleGun.
G4int PrimaryGeneratorAction::GetSelectedAction () inline
Definition at line 65 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PrimaryGeneratorAction.hh
References fSelectedAction.
G4double PrimaryGeneratorAction::GetTimeExposure () inline
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
References fTimeExposure.
G4bool PrimaryGeneratorAction::GetVerbose () const inline
Definition at line 91 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 91 of file PrimaryGeneratorAction.hh
References fVerbose.
G4int PrimaryGeneratorAction::GetWallCount () inline
Definition at line 57 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction.hh
References fNwall.
void PrimaryGeneratorAction::InitializeMe () private
Definition at line 65 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 65 of file PrimaryGeneratorAction.cc
References fCounter, fDetector, fDirection, fGauss, fMessenger, fMinCosTheta, fParticleGun, fPosition, fRMax2, fSigmaE, fSigmaTheta, fSigmaX, fSigmaY, fSigmaZ, fVerbose, fX0, fY0, fZ0, DetectorConstruction::GetVerbose(), MeV, mm, and SetBeamEnergy().
virtual G4bool PrimaryGeneratorAction::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
virtual G4bool PrimaryGeneratorAction::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
G4bool PrimaryGeneratorAction::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
Definition at line 74 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 74 of file PrimaryGeneratorAction.cc
References eV, G4ParticleTable::FindParticle(), fParticleGun, G4State_Idle, G4ParticleTable::GetParticleTable(), particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
virtual G4bool PrimaryGeneratorAction::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
virtual G4bool PrimaryGeneratorAction::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
virtual G4bool PrimaryGeneratorAction::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
PrimaryGeneratorAction& PrimaryGeneratorAction::operator= (const PrimaryGeneratorAction & right) private
PrimaryGeneratorAction& PrimaryGeneratorAction::operator= (const PrimaryGeneratorAction & right) private
PrimaryGeneratorAction& PrimaryGeneratorAction::operator= (const PrimaryGeneratorAction & right) private
PrimaryGeneratorAction& PrimaryGeneratorAction::operator= (const PrimaryGeneratorAction & right) private
PrimaryGeneratorAction& PrimaryGeneratorAction::operator= (const PrimaryGeneratorAction & right) private
PrimaryGeneratorAction& PrimaryGeneratorAction::operator= (const PrimaryGeneratorAction & right) private
void PrimaryGeneratorAction::ResetEbeamCumul () inline
Definition at line 56 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction.hh
References fEbeamCumul.
void PrimaryGeneratorAction::RunInitialisation (G4double effWall, G4double massR)
Definition at line 67 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 67 of file PrimaryGeneratorAction.cc
References fCavityThickness, fDetector, fEffWallThick, fMassWallRatio, fNcavity, fNwall, and DetectorConstruction::GetCavityThickness().
Referenced by Run::Run().
void PrimaryGeneratorAction::SelectAction (G4int i) inline
Definition at line 64 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 64 of file PrimaryGeneratorAction.hh
References fSelectedAction.
void PrimaryGeneratorAction::SetBeamEnergy (G4double val)
Definition at line 177 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 177 of file PrimaryGeneratorAction.cc
References fDetector, fEnergy, and DetectorConstruction::SetMaxEnergy().
Referenced by InitializeMe().
void PrimaryGeneratorAction::SetBeamMinCosTheta (G4double val) inline
Definition at line 86 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 86 of file PrimaryGeneratorAction.hh
References fMinCosTheta.
void PrimaryGeneratorAction::SetBeamRadius (G4double val) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fRBeam.
void PrimaryGeneratorAction::SetBeamSigmaE (G4double val) inline
Definition at line 79 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 79 of file PrimaryGeneratorAction.hh
References fSigmaE.
void PrimaryGeneratorAction::SetBeamSigmaX (G4double val) inline
Definition at line 83 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 83 of file PrimaryGeneratorAction.hh
References fSigmaX.
void PrimaryGeneratorAction::SetBeamSigmaY (G4double val) inline
Definition at line 84 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 84 of file PrimaryGeneratorAction.hh
References fSigmaY.
void PrimaryGeneratorAction::SetBeamSigmaZ (G4double val) inline
Definition at line 85 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 85 of file PrimaryGeneratorAction.hh
References fSigmaY.
void PrimaryGeneratorAction::SetBeamX (G4double val) inline
Definition at line 80 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 80 of file PrimaryGeneratorAction.hh
References fX0.
void PrimaryGeneratorAction::SetBeamY (G4double val) inline
Definition at line 81 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 81 of file PrimaryGeneratorAction.hh
References fY0.
void PrimaryGeneratorAction::SetBeamZ (G4double val) inline
Definition at line 82 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 82 of file PrimaryGeneratorAction.hh
References fZ0.
void PrimaryGeneratorAction::SetDefaultKinematic ()
Definition at line 60 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.cc
References cm, Detector, G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), DetectorConstruction::GetSize(), MeV, particle, particleGun, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
Referenced by PrimaryGeneratorAction(), and PrimaryGeneratorMessenger::SetNewValue().
void PrimaryGeneratorAction::SetDefaultKinematic ()
void PrimaryGeneratorAction::SetDefaultKinematic ()
void PrimaryGeneratorAction::SetDefaultKinematic ()
void PrimaryGeneratorAction::SetDefaultKinematic ()
void PrimaryGeneratorAction::SetDefaultKinematic ()
void PrimaryGeneratorAction::SetDefaultKinematic ()
void PrimaryGeneratorAction::SetDefaultKinematic ()
void PrimaryGeneratorAction::SetDefaultKinematic (G4int front)
Definition at line 73 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 73 of file PrimaryGeneratorAction.cc
References cm, fDetector, G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), DetectorConstruction::GetSize(), MeV, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
void PrimaryGeneratorAction::SetEmission (G4int value)
Definition at line 283 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 283 of file PrimaryGeneratorAction.cc
References fEmission.
void PrimaryGeneratorAction::SetOptPhotonPolar ()
Definition at line 86 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 86 of file PrimaryGeneratorAction.cc
References angle, deg, and G4UniformRand.
void PrimaryGeneratorAction::SetOptPhotonPolar (G4double angle)
Definition at line 94 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 94 of file PrimaryGeneratorAction.cc
References CLHEP::Hep3Vector::cross(), fParticleGun, G4cout, G4endl, G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleMomentumDirection(), G4ParticleDefinition::GetParticleName(), CLHEP::normal(), and G4ParticleGun::SetParticlePolarization().
void PrimaryGeneratorAction::SetRandom (const G4String & type) inline
Definition at line 89 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 89 of file PrimaryGeneratorAction.hh
References fGauss.
void PrimaryGeneratorAction::SetRandomFlag (G4bool value)
void PrimaryGeneratorAction::SetRandomFlag (G4bool value)
void PrimaryGeneratorAction::SetRandomFlag (G4bool value)
void PrimaryGeneratorAction::SetRandomFlag (G4bool value)
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 50 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 50 of file PrimaryGeneratorAction.hh
References beam.
Referenced by PrimaryGeneratorMessenger::SetNewValue().
void PrimaryGeneratorAction::SetRndmBeam (G4bool val) inline
Definition at line 52 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double value) inline
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetRndmBeam (G4double val) inline
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
References fRndmBeam.
void PrimaryGeneratorAction::SetSigmaTheta (G4double val) inline
Definition at line 87 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 87 of file PrimaryGeneratorAction.hh
References fSigmaTheta.
void PrimaryGeneratorAction::SetTimeExposure (G4double value) inline
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
References fTimeExposure.
void PrimaryGeneratorAction::SetVerbose (G4int val) inline
Definition at line 88 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 88 of file PrimaryGeneratorAction.hh
References fVerbose.
G4double PrimaryGeneratorAction::XYofAngle (G4double angle) private
Definition at line 290 of file PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 290 of file PrimaryGeneratorAction.cc
Member Data Documentation
AnalysisManager* PrimaryGeneratorAction::analysis private
Definition at line 50 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 50 of file PrimaryGeneratorAction.hh
Referenced by PrimaryGeneratorAction().
G4double PrimaryGeneratorAction::beam private
Definition at line 57 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction.hh
Referenced by SetRndmBeam().
G4bool PrimaryGeneratorAction::bPrimPositionDefined private
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
DetectorConstruction * PrimaryGeneratorAction::Detector private
Definition at line 56 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction.hh
Referenced by SetDefaultKinematic().
PrimaryGeneratorAction0* PrimaryGeneratorAction::fAction0 private
Definition at line 76 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 76 of file PrimaryGeneratorAction.hh
Referenced by GetAction0().
PrimaryGeneratorAction1* PrimaryGeneratorAction::fAction1 private
Definition at line 77 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 77 of file PrimaryGeneratorAction.hh
Referenced by GetAction1().
PrimaryGeneratorAction2* PrimaryGeneratorAction::fAction2 private
Definition at line 78 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 78 of file PrimaryGeneratorAction.hh
Referenced by GetAction2().
PrimaryGeneratorAction3* PrimaryGeneratorAction::fAction3 private
Definition at line 79 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 79 of file PrimaryGeneratorAction.hh
Referenced by GetAction3().
PrimaryGeneratorAction4* PrimaryGeneratorAction::fAction4 private
Definition at line 80 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 80 of file PrimaryGeneratorAction.hh
Referenced by GetAction4().
G4double PrimaryGeneratorAction::fAngleMax private
Definition at line 74 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 74 of file PrimaryGeneratorAction.hh
CLHEP::HepMatrix PrimaryGeneratorAction::fBeamMatrix private
Definition at line 79 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 79 of file PrimaryGeneratorAction.hh
Referenced by GetMatrix().
G4double PrimaryGeneratorAction::fCavityThickness private
Definition at line 69 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file PrimaryGeneratorAction.hh
Referenced by RunInitialisation().
G4int PrimaryGeneratorAction::fCounter private
Definition at line 105 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 105 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe().
const DetectorConstruction* PrimaryGeneratorAction::fDetector private
Definition at line 63 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 63 of file PrimaryGeneratorAction.hh
DetectorConstruction * PrimaryGeneratorAction::fDetector private
Definition at line 70 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 70 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), RunInitialisation(), SetBeamEnergy(), and SetDefaultKinematic().
G4ThreeVector PrimaryGeneratorAction::fDirection private
Definition at line 114 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 114 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe().
G4double PrimaryGeneratorAction::fEbeamCumul private
Definition at line 65 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PrimaryGeneratorAction.hh
Referenced by GetEbeamCumul(), and ResetEbeamCumul().
G4double PrimaryGeneratorAction::fEffWallThick private
Definition at line 68 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 68 of file PrimaryGeneratorAction.hh
Referenced by RunInitialisation().
G4int PrimaryGeneratorAction::fEmission
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
Referenced by SetEmission().
G4double PrimaryGeneratorAction::fEnergy private
Definition at line 111 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 111 of file PrimaryGeneratorAction.hh
Referenced by SetBeamEnergy().
G4String PrimaryGeneratorAction::fGauss private
Definition at line 115 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 115 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), and SetRandom().
G4GeneralParticleSource* PrimaryGeneratorAction::fGPS private
Definition at line 49 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 49 of file PrimaryGeneratorAction.hh
G4double PrimaryGeneratorAction::fGunArea private
Definition at line 65 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file PrimaryGeneratorAction.hh
Referenced by GetGunArea().
PrimaryGeneratorMessenger * PrimaryGeneratorAction::fGunMessenger private
Definition at line 72 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file PrimaryGeneratorAction.hh
HistoManager * PrimaryGeneratorAction::fHisto private
Definition at line 69 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file PrimaryGeneratorAction.hh
G4double PrimaryGeneratorAction::fMassWallRatio private
Definition at line 70 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 70 of file PrimaryGeneratorAction.hh
Referenced by RunInitialisation().
PrimaryGeneratorMessenger* PrimaryGeneratorAction::fMessenger private
Definition at line 101 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 101 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe().
G4double PrimaryGeneratorAction::fMinCosTheta private
Definition at line 112 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 112 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), and SetBeamMinCosTheta().
G4int PrimaryGeneratorAction::fNcavity private
Definition at line 71 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 71 of file PrimaryGeneratorAction.hh
Referenced by AddCavityCount(), GetCavityCount(), and RunInitialisation().
G4int PrimaryGeneratorAction::fNwall private
Definition at line 71 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 71 of file PrimaryGeneratorAction.hh
Referenced by AddWallCount(), GetWallCount(), and RunInitialisation().
TestParameters* PrimaryGeneratorAction::fParam private
Definition at line 72 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 72 of file PrimaryGeneratorAction.hh
G4ParticleGun* PrimaryGeneratorAction::fparticleGun private
Definition at line 45 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 45 of file PrimaryGeneratorAction.hh
G4GeneralParticleSource* PrimaryGeneratorAction::fParticleGun private
Definition at line 53 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file PrimaryGeneratorAction.hh
G4ParticleGun * PrimaryGeneratorAction::fParticleGun private
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
Referenced by GetParticleGun(), InitializeMe(), Notify(), PrimaryGeneratorAction(), SetDefaultKinematic(), and SetOptPhotonPolar().
G4ThreeVector PrimaryGeneratorAction::fPosition private
Definition at line 113 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 113 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe().
std::unique_ptr<G4ParticleGun> PrimaryGeneratorAction::fpParticleGun private
Definition at line 43 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 43 of file PrimaryGeneratorAction.hh
G4ParticleGun * PrimaryGeneratorAction::fpParticleGun private
Definition at line 52 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file PrimaryGeneratorAction.hh
Referenced by GetParticleGun().
PrimaryGenerator* PrimaryGeneratorAction::fPrimaryGenerator private
Definition at line 54 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file PrimaryGeneratorAction.hh
G4double PrimaryGeneratorAction::fR2World private
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
G4double PrimaryGeneratorAction::fRBeam private
Definition at line 62 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 62 of file PrimaryGeneratorAction.hh
Referenced by GetBeamRadius(), and SetBeamRadius().
G4double PrimaryGeneratorAction::fRMax2 private
Definition at line 108 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 108 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe().
G4bool PrimaryGeneratorAction::fRndmBeam private
Definition at line 59 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryGeneratorAction.hh
G4double PrimaryGeneratorAction::fRndmBeam private
Definition at line 62 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 62 of file PrimaryGeneratorAction.hh
Referenced by SetRndmBeam().
G4int PrimaryGeneratorAction::fSelectedAction private
Definition at line 81 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 81 of file PrimaryGeneratorAction.hh
Referenced by GetSelectedAction(), and SelectAction().
G4bool PrimaryGeneratorAction::fShoot private
Definition at line 76 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 76 of file PrimaryGeneratorAction.hh
G4double PrimaryGeneratorAction::fSigmaE private
Definition at line 109 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 109 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), and SetBeamSigmaE().
G4double PrimaryGeneratorAction::fSigmaTheta private
Definition at line 110 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 110 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), and SetSigmaTheta().
G4double PrimaryGeneratorAction::fSigmaX private
Definition at line 107 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 107 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), and SetBeamSigmaX().
G4double PrimaryGeneratorAction::fSigmaY private
Definition at line 107 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 107 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), SetBeamSigmaY(), and SetBeamSigmaZ().
G4double PrimaryGeneratorAction::fSigmaZ private
Definition at line 107 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 107 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe().
G4double PrimaryGeneratorAction::fTimeExposure private
Definition at line 66 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 66 of file PrimaryGeneratorAction.hh
Referenced by GetTimeExposure(), and SetTimeExposure().
G4int PrimaryGeneratorAction::fVerbose private
Definition at line 100 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 100 of file PrimaryGeneratorAction.hh
Referenced by GetVerbose(), InitializeMe(), and SetVerbose().
G4double PrimaryGeneratorAction::fX0 private
Definition at line 106 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 106 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), and SetBeamX().
G4double PrimaryGeneratorAction::fY0 private
Definition at line 106 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 106 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), and SetBeamY().
G4double PrimaryGeneratorAction::fZ0 private
Definition at line 60 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 60 of file PrimaryGeneratorAction.hh
Referenced by InitializeMe(), and SetBeamZ().
G4GeneralParticleSource* PrimaryGeneratorAction::gun private
Definition at line 49 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 49 of file PrimaryGeneratorAction.hh
Referenced by PrimaryGeneratorAction().
PrimaryGeneratorMessenger* PrimaryGeneratorAction::gunMessenger private
Definition at line 59 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file PrimaryGeneratorAction.hh
G4ParticleGun * PrimaryGeneratorAction::particleGun private
Definition at line 55 of file PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 55 of file PrimaryGeneratorAction.hh
Referenced by test.MyPrimaryGeneratorAction::__init__(), GeneratePrimaries(), GetParticleGun(), PrimaryGeneratorAction(), SetDefaultKinematic(), and ~PrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx01/shared/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx02/shared/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx03/shared/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/shared/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm4/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/userPrimaryGenerator/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/channeling/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/geometry/transforms/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr00/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr08/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnaphysics/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/icsd/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI01/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/extensibleFactory/shared/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/factory/shared/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/genericPL/shared/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/physicslists/shared/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/include/PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx01/shared/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx02/shared/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx03/shared/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/shared/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm10/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm4/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm8/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/userPrimaryGenerator/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/channeling/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/dmparticle/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/geometry/transforms/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr00/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr08/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnaphysics/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/icsd/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microprox/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microyz/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI01/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/extensibleFactory/shared/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/factory/shared/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/genericPL/shared/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/physicslists/shared/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/src/PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/src/PrimaryGeneratorAction.cc