ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4TwistedTubs.cc File Reference
pyG4TwistedTubs.cc File Reference
#include <boost/python.hpp>
#include "G4TwistedTubs.hh"
Namespaces
namespace pyG4TwistedTubs
Functions
G4TwistedTubs * pyG4TwistedTubs::f1_CreateTwistedTubs (const G4String &name, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4double dphi)
G4TwistedTubs * pyG4TwistedTubs::f2_CreateTwistedTubs (const G4String &name, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4int nseg, G4double totphi)
G4TwistedTubs * pyG4TwistedTubs::f3_CreateTwistedTubs (const G4String &name, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4double dphi)
G4TwistedTubs * pyG4TwistedTubs::f4_CreateTwistedTubs (const G4String &name, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4int nseg, G4double totphi)
void export_G4TwistedTubs ()
Variables
G4double(G4TwistedTubs::* pyG4TwistedTubs::f1_GetEndInnerRadius)(G4int) const = &G4TwistedTubs::GetEndInnerRadius
G4double(G4TwistedTubs::* pyG4TwistedTubs::f2_GetEndInnerRadius)(G4int) const = &G4TwistedTubs::GetEndInnerRadius
G4double(G4TwistedTubs::* pyG4TwistedTubs::f1_GetEndOuterRadius)(G4int) const = &G4TwistedTubs::GetEndOuterRadius
G4double(G4TwistedTubs::* pyG4TwistedTubs::f2_GetEndOuterRadius)() const = &G4TwistedTubs::GetEndOuterRadius
Function Documentation
void export_G4TwistedTubs ()
Definition at line 112 of file pyG4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 112 of file pyG4TwistedTubs.cc
References pyG4TwistedTubs::f1_CreateTwistedTubs(), pyG4TwistedTubs::f1_GetEndInnerRadius, pyG4TwistedTubs::f1_GetEndOuterRadius, pyG4TwistedTubs::f2_CreateTwistedTubs(), pyG4TwistedTubs::f2_GetEndInnerRadius, pyG4TwistedTubs::f2_GetEndOuterRadius, pyG4TwistedTubs::f3_CreateTwistedTubs(), pyG4TwistedTubs::f4_CreateTwistedTubs(), G4TwistedTubs::GetDPhi(), G4TwistedTubs::GetEndPhi(), G4TwistedTubs::GetEndZ(), G4TwistedTubs::GetInnerRadius(), G4TwistedTubs::GetInnerStereo(), G4TwistedTubs::GetKappa(), G4TwistedTubs::GetOuterRadius(), G4TwistedTubs::GetOuterStereo(), G4TwistedTubs::GetPhiTwist(), G4TwistedTubs::GetTanInnerStereo(), G4TwistedTubs::GetTanInnerStereo2(), G4TwistedTubs::GetTanOuterStereo(), G4TwistedTubs::GetTanOuterStereo2(), G4TwistedTubs::GetZHalfLength(), and init().
Referenced by BOOST_PYTHON_MODULE().