ECCE @ EIC Software: G4hImpactIonisation Class Reference
G4hImpactIonisation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4hImpactIonisation.hh>
Public Member Functions
G4hImpactIonisation (const G4String &processName="hImpactIoni")
~G4hImpactIonisation ()
G4bool IsApplicable (const G4ParticleDefinition &)
void BuildPhysicsTable (const G4ParticleDefinition &aParticleType)
G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, enum G4ForceCondition *condition)
void PrintInfoDefinition () const
void SetHighEnergyForProtonParametrisation (G4double energy)
void SetLowEnergyForProtonParametrisation (G4double energy)
void SetHighEnergyForAntiProtonParametrisation (G4double energy)
void SetLowEnergyForAntiProtonParametrisation (G4double energy)
G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety)
void SetElectronicStoppingPowerModel (const G4ParticleDefinition *aParticle, const G4String &dedxTable)
void SetNuclearStoppingPowerModel (const G4String &dedxTable)
void SetNuclearStoppingOn ()
void SetNuclearStoppingOff ()
void SetBarkasOn ()
void SetBarkasOff ()
void SetPixe (const G4bool)
G4VParticleChange * AlongStepDoIt (const G4Track &trackData, const G4Step &stepData)
G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &Step)
G4double ComputeDEDX (const G4ParticleDefinition *aParticle, const G4MaterialCutsCouple *couple, G4double kineticEnergy)
void SetCutForSecondaryPhotons (G4double cut)
void SetCutForAugerElectrons (G4double cut)
void ActivateAugerElectronProduction (G4bool val)
void SetPixeCrossSectionK (const G4String &name)
void SetPixeCrossSectionL (const G4String &name)
void SetPixeCrossSectionM (const G4String &name)
void SetPixeProjectileMinEnergy (G4double energy)
void SetPixeProjectileMaxEnergy (G4double energy)
Public Member Functions inherited from G4hRDEnergyLoss
G4hRDEnergyLoss (const G4String &)
~G4hRDEnergyLoss ()
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
void InitializeMe ()
void InitializeParametrisation ()
void BuildLossTable (const G4ParticleDefinition &aParticleType)
void BuildLambdaTable (const G4ParticleDefinition &aParticleType)
void SetProtonElectronicStoppingPowerModel (const G4String &dedxTable)
void SetAntiProtonElectronicStoppingPowerModel (const G4String &dedxTable)
G4double MicroscopicCrossSection (const G4ParticleDefinition &aParticleType, G4double kineticEnergy, G4double atomicNumber, G4double deltaCutInEnergy) const
G4double GetConstraints (const G4DynamicParticle *particle, const G4MaterialCutsCouple *couple)
G4double ProtonParametrisedDEDX (const G4MaterialCutsCouple *couple, G4double kineticEnergy) const
G4double AntiProtonParametrisedDEDX (const G4MaterialCutsCouple *couple, G4double kineticEnergy) const
G4double DeltaRaysEnergy (const G4MaterialCutsCouple *couple, G4double kineticEnergy, G4double particleMass) const
G4double BarkasTerm (const G4Material *material, G4double kineticEnergy) const
G4double BlochTerm (const G4Material *material, G4double kineticEnergy, G4double cSquare) const
G4double ElectronicLossFluctuation (const G4DynamicParticle *particle, const G4MaterialCutsCouple *material, G4double meanLoss, G4double step) const
G4hImpactIonisation & operator= (const G4hImpactIonisation &right)
G4hImpactIonisation (const G4hImpactIonisation &)
Private Attributes
G4VLowEnergyModel * betheBlochModel
G4VLowEnergyModel * protonModel
G4VLowEnergyModel * antiprotonModel
G4VLowEnergyModel * theIonEffChargeModel
G4VLowEnergyModel * theNuclearStoppingModel
G4VLowEnergyModel * theIonChuFluctuationModel
G4VLowEnergyModel * theIonYangFluctuationModel
G4String protonTable
G4String antiprotonTable
G4String theNuclearTable
G4double protonLowEnergy
G4double protonHighEnergy
G4double antiprotonLowEnergy
G4double antiprotonHighEnergy
G4bool nStopping
G4bool theBarkas
G4DataVector cutForDelta
G4DataVector cutForGamma
G4double minGammaEnergy
G4double minElectronEnergy
G4PhysicsTable * theMeanFreePathTable
const G4double paramStepLimit
G4double fdEdx
G4double fRangeNow
G4double charge
G4double chargeSquare
G4double initialMass
G4double fBarkas
G4PixeCrossSectionHandler * pixeCrossSectionHandler
G4AtomicDeexcitation atomicDeexcitation
G4String modelK
G4String modelL
G4String modelM
G4double eMinPixe
G4double eMaxPixe
G4bool pixeIsActive
Additional Inherited Members
Static Public Member Functions inherited from G4hRDEnergyLoss
static G4int GetNumberOfProcesses ()
static void SetNumberOfProcesses (G4int number)
static void PlusNumberOfProcesses ()
static void MinusNumberOfProcesses ()
static void SetdRoverRange (G4double value)
static void SetRndmStep (G4bool value)
static void SetEnlossFluc (G4bool value)
static void SetStepFunction (G4double c1, G4double c2)
Protected Member Functions inherited from G4hRDEnergyLoss
G4bool CutsWhereModified ()
Static Protected Member Functions inherited from G4hRDEnergyLoss
static void BuildDEDXTable (const G4ParticleDefinition &aParticleType)
Protected Attributes inherited from G4hRDEnergyLoss
const G4double MaxExcitationNumber
const G4double probLimFluct
const long nmaxDirectFluct
const long nmaxCont1
const long nmaxCont2
G4PhysicsTable * theLossTable
G4double linLossLimit
G4double MinKineticEnergy
Static Protected Attributes inherited from G4hRDEnergyLoss
static G4ThreadLocal
G4PhysicsTable * theDEDXpTable = 0
static G4ThreadLocal
G4PhysicsTable * theDEDXpbarTable = 0
static G4ThreadLocal
G4PhysicsTable * theRangepTable = 0
static G4ThreadLocal
G4PhysicsTable * theRangepbarTable = 0
static G4ThreadLocal
G4PhysicsTable * theInverseRangepTable = 0
static G4ThreadLocal
G4PhysicsTable * theInverseRangepbarTable = 0
static G4ThreadLocal
G4PhysicsTable * theLabTimepTable = 0
static G4ThreadLocal
G4PhysicsTable * theLabTimepbarTable = 0
static G4ThreadLocal
G4PhysicsTable * theProperTimepTable = 0
static G4ThreadLocal
G4PhysicsTable * theProperTimepbarTable = 0
static G4ThreadLocal
G4PhysicsTable ** RecorderOfpProcess = 0
static G4ThreadLocal
G4PhysicsTable ** RecorderOfpbarProcess = 0
static G4ThreadLocal G4int CounterOfpProcess = 0
static G4ThreadLocal G4int CounterOfpbarProcess = 0
static G4ThreadLocal G4double ParticleMass
static G4ThreadLocal G4double ptableElectronCutInRange = 0.0
static G4ThreadLocal G4double pbartableElectronCutInRange = 0.0
static G4ThreadLocal G4double Charge
static G4ThreadLocal G4double LowestKineticEnergy = 1e-05
static G4ThreadLocal G4double HighestKineticEnergy = 1.e5
static G4ThreadLocal G4int TotBin = 360
static G4ThreadLocal G4double RTable
static G4ThreadLocal G4double LOGRTable
static G4ThreadLocal G4double dRoverRange = 0.20
static G4ThreadLocal G4double finalRange = 0.2
static G4ThreadLocal G4double c1lim = 0.20
static G4ThreadLocal G4double c2lim = 0.32
static G4ThreadLocal G4double c3lim = -0.032
static G4ThreadLocal G4bool rndmStepFlag = false
static G4ThreadLocal G4bool EnlossFlucFlag = true
Detailed Description
Definition at line 74 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 74 of file G4hImpactIonisation.hh
Constructor & Destructor Documentation
G4hImpactIonisation::G4hImpactIonisation (const G4String & processName = "hImpactIoni")
Definition at line 82 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 82 of file G4hImpactIonisation.cc
References InitializeMe().
G4hImpactIonisation::~G4hImpactIonisation ()
Definition at line 131 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 131 of file G4hImpactIonisation.cc
References antiprotonModel, betheBlochModel, G4PhysicsTable::clearAndDestroy(), cutForDelta, pixeCrossSectionHandler, protonModel, theIonChuFluctuationModel, theIonEffChargeModel, theIonYangFluctuationModel, theMeanFreePathTable, and theNuclearStoppingModel.
G4hImpactIonisation::G4hImpactIonisation (const G4hImpactIonisation &) private
Member Function Documentation
void G4hImpactIonisation::ActivateAugerElectronProduction (G4bool val)
Definition at line 1706 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 1706 of file G4hImpactIonisation.cc
References G4AtomicDeexcitation::ActivateAugerElectronProduction(), and atomicDeexcitation.
G4VParticleChange * G4hImpactIonisation::AlongStepDoIt (const G4Track & trackData, const G4Step & stepData) virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 717 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 717 of file G4hImpactIonisation.cc
References G4AntiProton::AntiProton(), G4VProcess::aParticleChange, charge, chargeSquare, ElectronicLossFluctuation(), G4hRDEnergyLoss::EnlossFlucFlag, fBarkas, fdEdx, fRangeNow, fStopAndKill, fStopButAlive, G4ProcessManager::GetAtRestProcessVector(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4MaterialCutsCouple::GetMaterial(), G4Track::GetMaterialCutsCouple(), G4EnergyLossTables::GetPreciseEnergyFromRange(), G4ParticleDefinition::GetProcessManager(), G4Step::GetStepLength(), G4hRDEnergyLoss::HighestKineticEnergy, G4ParticleChange::Initialize(), G4hRDEnergyLoss::linLossLimit, material(), G4hRDEnergyLoss::MinKineticEnergy, nStopping, particle, G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4InuclParticleNames::proton, G4Proton::Proton(), source.hepunit::proton_mass_c2, protonHighEnergy, G4ProcessVector::size(), theNuclearStoppingModel, and G4VLowEnergyModel::TheValue().
G4double G4hImpactIonisation::AntiProtonParametrisedDEDX (const G4MaterialCutsCouple * couple, G4double kineticEnergy) const private
Definition at line 866 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 866 of file G4hImpactIonisation.cc
References G4AntiProton::AntiProton(), antiprotonLowEnergy, antiprotonModel, DeltaRaysEnergy(), G4cout, G4endl, G4MaterialCutsCouple::GetMaterial(), G4Material::GetName(), G4VLowEnergyModel::IsInCharge(), material(), MeV, mm, G4Proton::Proton(), source.hepunit::proton_mass_c2, protonLowEnergy, protonModel, G4VLowEnergyModel::TheValue(), and G4VProcess::verboseLevel.
Referenced by BuildLossTable(), and ComputeDEDX().
G4double G4hImpactIonisation::BarkasTerm (const G4Material * material, G4double kineticEnergy) const private
Definition at line 1305 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 1305 of file G4hImpactIonisation.cc
References G4ThreadLocal, material(), MeV, source.hepunit::proton_mass_c2, source.hepunit::twopi_mc2_rcl2, and X.
Referenced by GetConstraints().
G4double G4hImpactIonisation::BlochTerm (const G4Material * material, G4double kineticEnergy, G4double cSquare) const private
Definition at line 1417 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 1417 of file G4hImpactIonisation.cc
References material(), source.hepunit::proton_mass_c2, source.hepunit::twopi_mc2_rcl2, and y.
Referenced by GetConstraints().
void G4hImpactIonisation::BuildLambdaTable (const G4ParticleDefinition & aParticleType) private
Definition at line 445 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 445 of file G4hImpactIonisation.cc
References charge, chargeSquare, G4PhysicsTable::clearAndDestroy(), cutForDelta, DBL_MAX, eplus, G4cout, G4endl, G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4PhysicsVector::GetLowEdgeEnergy(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetNumberOfElements(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4hRDEnergyLoss::HighestKineticEnergy, initialMass, G4PhysicsTable::insert(), G4hRDEnergyLoss::LowestKineticEnergy, material(), MicroscopicCrossSection(), G4PhysicsVector::PutValue(), theMeanFreePathTable, G4hRDEnergyLoss::TotBin, G4VProcess::verboseLevel, and Z.
Referenced by BuildPhysicsTable().
void G4hImpactIonisation::BuildLossTable (const G4ParticleDefinition & aParticleType) private
Definition at line 347 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 347 of file G4hImpactIonisation.cc
References antiprotonHighEnergy, AntiProtonParametrisedDEDX(), betheBlochModel, charge, chargeSquare, G4PhysicsTable::clearAndDestroy(), DeltaRaysEnergy(), G4cout, G4endl, G4PhysicsVector::GetLowEdgeEnergy(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetName(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4hRDEnergyLoss::HighestKineticEnergy, G4PhysicsTable::insert(), G4hRDEnergyLoss::LowestKineticEnergy, material(), MeV, mm, G4InuclParticleNames::proton, G4Proton::Proton(), source.hepunit::proton_mass_c2, protonHighEnergy, ProtonParametrisedDEDX(), G4PhysicsVector::PutValue(), G4hRDEnergyLoss::theLossTable, G4VLowEnergyModel::TheValue(), G4hRDEnergyLoss::TotBin, and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable().
void G4hImpactIonisation::BuildPhysicsTable (const G4ParticleDefinition & aParticleType) virtual
Reimplemented from G4VProcess.
Definition at line 190 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 190 of file G4hImpactIonisation.cc
References G4AntiProton::AntiProton(), G4hRDEnergyLoss::BuildDEDXTable(), BuildLambdaTable(), BuildLossTable(), charge, chargeSquare, G4hRDEnergyLoss::CounterOfpbarProcess, G4hRDEnergyLoss::CounterOfpProcess, cutForDelta, cutForGamma, G4hRDEnergyLoss::CutsWhereModified(), eplus, G4cout, G4endl, G4ProductionCutsTable::GetEnergyCutsVector(), G4Material::GetIonisation(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4IonisParamMat::GetMeanExcitationEnergy(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4hRDEnergyLoss::HighestKineticEnergy, InitializeParametrisation(), initialMass, G4hRDEnergyLoss::LowestKineticEnergy, material(), max, MeV, minGammaEnergy, PrintInfoDefinition(), G4InuclParticleNames::proton, G4Proton::Proton(), source.hepunit::proton_mass_c2, G4hRDEnergyLoss::RecorderOfpbarProcess, G4hRDEnergyLoss::RecorderOfpProcess, G4EnergyLossTables::Register(), G4hRDEnergyLoss::theDEDXpTable, G4hRDEnergyLoss::theInverseRangepTable, theIonEffChargeModel, G4hRDEnergyLoss::theLabTimepTable, G4hRDEnergyLoss::theLossTable, theMeanFreePathTable, G4hRDEnergyLoss::theProperTimepTable, G4hRDEnergyLoss::theRangepTable, G4hRDEnergyLoss::TotBin, and G4VProcess::verboseLevel.
G4double G4hImpactIonisation::ComputeDEDX (const G4ParticleDefinition * aParticle, const G4MaterialCutsCouple * couple, G4double kineticEnergy)
Definition at line 1265 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 1265 of file G4hImpactIonisation.cc
References G4AntiProton::AntiProton(), antiprotonHighEnergy, AntiProtonParametrisedDEDX(), charge, G4EnergyLossTables::GetDEDX(), G4MaterialCutsCouple::GetMaterial(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), material(), G4InuclParticleNames::proton, G4Proton::Proton(), source.hepunit::proton_mass_c2, protonHighEnergy, ProtonParametrisedDEDX(), theIonEffChargeModel, and G4VLowEnergyModel::TheValue().
G4double G4hImpactIonisation::DeltaRaysEnergy (const G4MaterialCutsCouple * couple, G4double kineticEnergy, G4double particleMass) const private
Definition at line 916 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 916 of file G4hImpactIonisation.cc
References cutForDelta, source.hepunit::electron_mass_c2, G4Material::GetElectronDensity(), G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), material(), max, source.hepunit::twopi_mc2_rcl2, and x.
Referenced by AntiProtonParametrisedDEDX(), BuildLossTable(), and ProtonParametrisedDEDX().
G4double G4hImpactIonisation::ElectronicLossFluctuation (const G4DynamicParticle * particle, const G4MaterialCutsCouple * material, G4double meanLoss, G4double step) const private
Definition at line 1452 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 1452 of file G4hImpactIonisation.cc
References C(), charge, source.hepunit::electron_mass_c2, eV, G4Poisson(), G4UniformRand, G4Material::GetElectronDensity(), G4IonisParamMat::GetEnergy0fluct(), G4IonisParamMat::GetEnergy1fluct(), G4IonisParamMat::GetEnergy2fluct(), G4IonisParamMat::GetF1fluct(), G4IonisParamMat::GetF2fluct(), G4Material::GetIonisation(), G4IonisParamMat::GetLogEnergy1fluct(), G4IonisParamMat::GetLogEnergy2fluct(), G4IonisParamMat::GetLogMeanExcEnergy(), G4IonisParamMat::GetMeanExcitationEnergy(), G4IonisParamMat::GetRateionexcfluct(), G4Material::GetTotNbOfAtomsPerVolume(), k, keV, material(), max, particle, source.hepunit::proton_mass_c2, G4INCL::DeJongSpin::shoot(), Acts::Test::step(), source.hepunit::twopi_mc2_rcl2, and w.
Referenced by AlongStepDoIt().
G4double G4hImpactIonisation::GetConstraints (const G4DynamicParticle * particle, const G4MaterialCutsCouple * couple) private
Definition at line 622 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 622 of file G4hImpactIonisation.cc
References G4AntiProton::AntiProton(), antiprotonHighEnergy, BarkasTerm(), BlochTerm(), charge, chargeSquare, G4hRDEnergyLoss::dRoverRange, dx, fBarkas, fdEdx, G4hRDEnergyLoss::finalRange, fRangeNow, G4EnergyLossTables::GetDEDX(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), G4EnergyLossTables::GetRange(), idxG4ElectronCut, material(), min, paramStepLimit, G4InuclParticleNames::proton, G4Proton::Proton(), source.hepunit::proton_mass_c2, protonHighEnergy, r, theBarkas, and x.
Referenced by GetContinuousStepLimit().
G4double G4hImpactIonisation::GetContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety) inline virtual
Implements G4VContinuousDiscreteProcess.
Definition at line 293 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 293 of file G4hImpactIonisation.hh
References GetConstraints(), G4Track::GetDynamicParticle(), G4Track::GetMaterialCutsCouple(), and Acts::Test::step().
G4double G4hImpactIonisation::GetMeanFreePath (const G4Track & track, G4double previousStepSize, enum G4ForceCondition * condition) virtual
Implements G4hRDEnergyLoss.
Definition at line 588 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 588 of file G4hImpactIonisation.cc
References charge, chargeSquare, DBL_MAX, eplus, G4DynamicParticle::GetCharge(), G4Track::GetDynamicParticle(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4MaterialCutsCouple::GetMaterial(), G4Track::GetMaterialCutsCouple(), G4hRDEnergyLoss::HighestKineticEnergy, initialMass, G4hRDEnergyLoss::LowestKineticEnergy, material(), NotForced, theIonEffChargeModel, and G4VLowEnergyModel::TheValue().
void G4hImpactIonisation::InitializeMe () private
Definition at line 105 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 105 of file G4hImpactIonisation.cc
References antiprotonHighEnergy, antiprotonLowEnergy, eMaxPixe, eMinPixe, eV, GeV, G4hRDEnergyLoss::HighestKineticEnergy, keV, G4hRDEnergyLoss::LowestKineticEnergy, MeV, minElectronEnergy, minGammaEnergy, G4hRDEnergyLoss::MinKineticEnergy, modelK, modelL, modelM, protonHighEnergy, protonLowEnergy, G4hRDEnergyLoss::TotBin, and G4VProcess::verboseLevel.
Referenced by G4hImpactIonisation().
void G4hImpactIonisation::InitializeParametrisation () private
Definition at line 174 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 174 of file G4hImpactIonisation.cc
References antiprotonModel, antiprotonTable, betheBlochModel, G4VLowEnergyModel::HighEnergyLimit(), min, protonHighEnergy, protonModel, protonTable, theIonChuFluctuationModel, theIonEffChargeModel, theIonYangFluctuationModel, theNuclearStoppingModel, and theNuclearTable.
Referenced by BuildPhysicsTable().
G4bool G4hImpactIonisation::IsApplicable (const G4ParticleDefinition & particle) inline virtual
Reimplemented from G4VProcess.
Definition at line 310 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 310 of file G4hImpactIonisation.hh
References G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), and CLHEP::proton_mass_c2.
G4double G4hImpactIonisation::MicroscopicCrossSection (const G4ParticleDefinition & aParticleType, G4double kineticEnergy, G4double atomicNumber, G4double deltaCutInEnergy) const private
Definition at line 530 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 530 of file G4hImpactIonisation.cc
References source.hepunit::electron_mass_c2, energy, G4ParticleDefinition::GetPDGSpin(), initialMass, and source.hepunit::twopi_mc2_rcl2.
Referenced by BuildLambdaTable().
G4hImpactIonisation& G4hImpactIonisation::operator= (const G4hImpactIonisation & right) private
G4VParticleChange * G4hImpactIonisation::PostStepDoIt (const G4Track & track, const G4Step & Step) virtual
Implements G4hRDEnergyLoss.
Definition at line 951 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 951 of file G4hImpactIonisation.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, atomicDeexcitation, G4InuclSpecialFunctions::bindingEnergy(), G4AtomicShell::BindingEnergy(), cutForDelta, e, G4Electron::Electron(), source.hepunit::electron_mass_c2, eMaxPixe, eMinPixe, fStopAndKill, fStopButAlive, G4UniformRand, G4Gamma::Gamma(), G4AtomicDeexcitation::GenerateParticles(), G4Track::GetDefinition(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), G4ParticleDefinition::GetProcessManager(), G4ParticleChange::Initialize(), G4AtomicTransitionManager::Instance(), G4PixeCrossSectionHandler::LoadShellData(), mass, material(), minElectronEnergy, minGammaEnergy, G4hRDEnergyLoss::MinKineticEnergy, modelK, modelL, modelM, phi, pixeCrossSectionHandler, G4VContinuousDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), G4Proton::ProtonDefinition(), r, CLHEP::Hep3Vector::rotateUz(), G4PixeCrossSectionHandler::SelectRandomAtom(), G4PixeCrossSectionHandler::SelectRandomShell(), G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetKineticEnergy(), G4DynamicParticle::SetMomentumDirection(), G4VParticleChange::SetNumberOfSecondaries(), G4AtomicTransitionManager::Shell(), G4AtomicShell::ShellId(), twopi, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
void G4hImpactIonisation::PrintInfoDefinition () const
Definition at line 1713 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 1713 of file G4hImpactIonisation.cc
References antiprotonHighEnergy, antiprotonLowEnergy, antiprotonTable, cutForDelta, eV, false, G4cout, G4endl, G4MaterialCutsCouple::GetIndex(), G4Material::GetIonisation(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4IonisParamMat::GetMeanExcitationEnergy(), G4Material::GetName(), G4VProcess::GetProcessName(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4hRDEnergyLoss::HighestKineticEnergy, keV, G4hRDEnergyLoss::LowestKineticEnergy, material(), MeV, nStopping, protonHighEnergy, protonLowEnergy, protonTable, TeV, theBarkas, theNuclearTable, and G4hRDEnergyLoss::TotBin.
Referenced by BuildPhysicsTable().
G4double G4hImpactIonisation::ProtonParametrisedDEDX (const G4MaterialCutsCouple * couple, G4double kineticEnergy) const private
Definition at line 831 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 831 of file G4hImpactIonisation.cc
References DeltaRaysEnergy(), G4cout, G4endl, G4MaterialCutsCouple::GetMaterial(), G4Material::GetName(), material(), MeV, mm, G4InuclParticleNames::proton, G4Proton::Proton(), source.hepunit::proton_mass_c2, protonLowEnergy, protonModel, G4VLowEnergyModel::TheValue(), and G4VProcess::verboseLevel.
Referenced by BuildLossTable(), and ComputeDEDX().
void G4hImpactIonisation::SetAntiProtonElectronicStoppingPowerModel (const G4String & dedxTable) inline private
Definition at line 195 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 195 of file G4hImpactIonisation.hh
References antiprotonTable.
Referenced by SetElectronicStoppingPowerModel().
void G4hImpactIonisation::SetBarkasOff () inline
Definition at line 147 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 147 of file G4hImpactIonisation.hh
References theBarkas.
void G4hImpactIonisation::SetBarkasOn () inline
Definition at line 144 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 144 of file G4hImpactIonisation.hh
References theBarkas.
void G4hImpactIonisation::SetCutForAugerElectrons (G4double cut)
Definition at line 1699 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 1699 of file G4hImpactIonisation.cc
References minElectronEnergy.
void G4hImpactIonisation::SetCutForSecondaryPhotons (G4double cut)
Definition at line 1692 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 1692 of file G4hImpactIonisation.cc
References minGammaEnergy.
void G4hImpactIonisation::SetElectronicStoppingPowerModel (const G4ParticleDefinition * aParticle, const G4String & dedxTable)
Definition at line 156 of file G4hImpactIonisation.cc.
View newest version in sPHENIX GitHub at line 156 of file G4hImpactIonisation.cc
References G4ParticleDefinition::GetPDGCharge(), SetAntiProtonElectronicStoppingPowerModel(), and SetProtonElectronicStoppingPowerModel().
void G4hImpactIonisation::SetHighEnergyForAntiProtonParametrisation (G4double energy) inline
Definition at line 109 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 109 of file G4hImpactIonisation.hh
References antiprotonHighEnergy, and energy.
void G4hImpactIonisation::SetHighEnergyForProtonParametrisation (G4double energy) inline
Definition at line 99 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 99 of file G4hImpactIonisation.hh
References energy, and protonHighEnergy.
void G4hImpactIonisation::SetLowEnergyForAntiProtonParametrisation (G4double energy) inline
Definition at line 114 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 114 of file G4hImpactIonisation.hh
References antiprotonLowEnergy, and energy.
void G4hImpactIonisation::SetLowEnergyForProtonParametrisation (G4double energy) inline
Definition at line 104 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 104 of file G4hImpactIonisation.hh
References energy, and protonLowEnergy.
void G4hImpactIonisation::SetNuclearStoppingOff () inline
Definition at line 141 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 141 of file G4hImpactIonisation.hh
References nStopping.
void G4hImpactIonisation::SetNuclearStoppingOn () inline
Definition at line 138 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 138 of file G4hImpactIonisation.hh
References nStopping.
Referenced by SetNuclearStoppingPowerModel().
void G4hImpactIonisation::SetNuclearStoppingPowerModel (const G4String & dedxTable) inline
Definition at line 130 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 130 of file G4hImpactIonisation.hh
References SetNuclearStoppingOn(), and theNuclearTable.
void G4hImpactIonisation::SetPixe (const G4bool) inline
Definition at line 150 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 150 of file G4hImpactIonisation.hh
References pixeIsActive.
void G4hImpactIonisation::SetPixeCrossSectionK (const G4String & name) inline
Definition at line 176 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 176 of file G4hImpactIonisation.hh
References modelK.
void G4hImpactIonisation::SetPixeCrossSectionL (const G4String & name) inline
Definition at line 177 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 177 of file G4hImpactIonisation.hh
References modelL.
void G4hImpactIonisation::SetPixeCrossSectionM (const G4String & name) inline
Definition at line 178 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 178 of file G4hImpactIonisation.hh
References modelM.
void G4hImpactIonisation::SetPixeProjectileMaxEnergy (G4double energy) inline
Definition at line 180 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 180 of file G4hImpactIonisation.hh
References eMaxPixe, and energy.
void G4hImpactIonisation::SetPixeProjectileMinEnergy (G4double energy) inline
Definition at line 179 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 179 of file G4hImpactIonisation.hh
References eMinPixe, and energy.
void G4hImpactIonisation::SetProtonElectronicStoppingPowerModel (const G4String & dedxTable) inline private
Definition at line 191 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 191 of file G4hImpactIonisation.hh
References protonTable.
Referenced by SetElectronicStoppingPowerModel().
Member Data Documentation
G4double G4hImpactIonisation::antiprotonHighEnergy private
Definition at line 259 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 259 of file G4hImpactIonisation.hh
Referenced by BuildLossTable(), ComputeDEDX(), GetConstraints(), InitializeMe(), PrintInfoDefinition(), and SetHighEnergyForAntiProtonParametrisation().
G4double G4hImpactIonisation::antiprotonLowEnergy private
Definition at line 258 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 258 of file G4hImpactIonisation.hh
Referenced by AntiProtonParametrisedDEDX(), InitializeMe(), PrintInfoDefinition(), and SetLowEnergyForAntiProtonParametrisation().
G4VLowEnergyModel* G4hImpactIonisation::antiprotonModel private
Definition at line 242 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 242 of file G4hImpactIonisation.hh
Referenced by AntiProtonParametrisedDEDX(), InitializeParametrisation(), and ~G4hImpactIonisation().
G4String G4hImpactIonisation::antiprotonTable private
Definition at line 252 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 252 of file G4hImpactIonisation.hh
Referenced by InitializeParametrisation(), PrintInfoDefinition(), and SetAntiProtonElectronicStoppingPowerModel().
G4AtomicDeexcitation G4hImpactIonisation::atomicDeexcitation private
Definition at line 281 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 281 of file G4hImpactIonisation.hh
Referenced by ActivateAugerElectronProduction(), and PostStepDoIt().
G4VLowEnergyModel* G4hImpactIonisation::betheBlochModel private
Definition at line 240 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 240 of file G4hImpactIonisation.hh
Referenced by BuildLossTable(), InitializeParametrisation(), and ~G4hImpactIonisation().
G4double G4hImpactIonisation::charge private
Definition at line 275 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 275 of file G4hImpactIonisation.hh
Referenced by AlongStepDoIt(), BuildLambdaTable(), BuildLossTable(), BuildPhysicsTable(), ComputeDEDX(), GetConstraints(), and GetMeanFreePath().
G4double G4hImpactIonisation::chargeSquare private
Definition at line 276 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 276 of file G4hImpactIonisation.hh
Referenced by AlongStepDoIt(), BuildLambdaTable(), BuildLossTable(), BuildPhysicsTable(), GetConstraints(), and GetMeanFreePath().
G4DataVector G4hImpactIonisation::cutForDelta private
Definition at line 265 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 265 of file G4hImpactIonisation.hh
Referenced by BuildLambdaTable(), BuildPhysicsTable(), DeltaRaysEnergy(), PostStepDoIt(), PrintInfoDefinition(), and ~G4hImpactIonisation().
G4DataVector G4hImpactIonisation::cutForGamma private
Definition at line 266 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 266 of file G4hImpactIonisation.hh
Referenced by BuildPhysicsTable().
G4double G4hImpactIonisation::eMaxPixe private
Definition at line 286 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 286 of file G4hImpactIonisation.hh
Referenced by InitializeMe(), PostStepDoIt(), and SetPixeProjectileMaxEnergy().
G4double G4hImpactIonisation::eMinPixe private
Definition at line 285 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 285 of file G4hImpactIonisation.hh
Referenced by InitializeMe(), PostStepDoIt(), and SetPixeProjectileMinEnergy().
G4double G4hImpactIonisation::fBarkas private
Definition at line 278 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 278 of file G4hImpactIonisation.hh
Referenced by AlongStepDoIt(), and GetConstraints().
G4double G4hImpactIonisation::fdEdx private
Definition at line 273 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 273 of file G4hImpactIonisation.hh
Referenced by AlongStepDoIt(), and GetConstraints().
G4double G4hImpactIonisation::fRangeNow private
Definition at line 274 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 274 of file G4hImpactIonisation.hh
Referenced by AlongStepDoIt(), and GetConstraints().
G4double G4hImpactIonisation::initialMass private
Definition at line 277 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 277 of file G4hImpactIonisation.hh
Referenced by BuildLambdaTable(), BuildPhysicsTable(), GetMeanFreePath(), and MicroscopicCrossSection().
G4double G4hImpactIonisation::minElectronEnergy private
Definition at line 268 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 268 of file G4hImpactIonisation.hh
Referenced by InitializeMe(), PostStepDoIt(), and SetCutForAugerElectrons().
G4double G4hImpactIonisation::minGammaEnergy private
Definition at line 267 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 267 of file G4hImpactIonisation.hh
Referenced by BuildPhysicsTable(), InitializeMe(), PostStepDoIt(), and SetCutForSecondaryPhotons().
G4String G4hImpactIonisation::modelK private
Definition at line 282 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 282 of file G4hImpactIonisation.hh
Referenced by InitializeMe(), PostStepDoIt(), and SetPixeCrossSectionK().
G4String G4hImpactIonisation::modelL private
Definition at line 283 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 283 of file G4hImpactIonisation.hh
Referenced by InitializeMe(), PostStepDoIt(), and SetPixeCrossSectionL().
G4String G4hImpactIonisation::modelM private
Definition at line 284 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 284 of file G4hImpactIonisation.hh
Referenced by InitializeMe(), PostStepDoIt(), and SetPixeCrossSectionM().
G4bool G4hImpactIonisation::nStopping private
Definition at line 262 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 262 of file G4hImpactIonisation.hh
Referenced by AlongStepDoIt(), PrintInfoDefinition(), SetNuclearStoppingOff(), and SetNuclearStoppingOn().
const G4double G4hImpactIonisation::paramStepLimit private
Definition at line 271 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 271 of file G4hImpactIonisation.hh
Referenced by GetConstraints().
G4PixeCrossSectionHandler* G4hImpactIonisation::pixeCrossSectionHandler private
Definition at line 280 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 280 of file G4hImpactIonisation.hh
Referenced by PostStepDoIt(), and ~G4hImpactIonisation().
G4bool G4hImpactIonisation::pixeIsActive private
Definition at line 288 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 288 of file G4hImpactIonisation.hh
Referenced by SetPixe().
G4double G4hImpactIonisation::protonHighEnergy private
Definition at line 257 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 257 of file G4hImpactIonisation.hh
Referenced by AlongStepDoIt(), BuildLossTable(), ComputeDEDX(), GetConstraints(), InitializeMe(), InitializeParametrisation(), PrintInfoDefinition(), and SetHighEnergyForProtonParametrisation().
G4double G4hImpactIonisation::protonLowEnergy private
Definition at line 256 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 256 of file G4hImpactIonisation.hh
Referenced by AntiProtonParametrisedDEDX(), InitializeMe(), PrintInfoDefinition(), ProtonParametrisedDEDX(), and SetLowEnergyForProtonParametrisation().
G4VLowEnergyModel* G4hImpactIonisation::protonModel private
Definition at line 241 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 241 of file G4hImpactIonisation.hh
Referenced by AntiProtonParametrisedDEDX(), InitializeParametrisation(), ProtonParametrisedDEDX(), and ~G4hImpactIonisation().
G4String G4hImpactIonisation::protonTable private
Definition at line 251 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 251 of file G4hImpactIonisation.hh
Referenced by InitializeParametrisation(), PrintInfoDefinition(), and SetProtonElectronicStoppingPowerModel().
G4bool G4hImpactIonisation::theBarkas private
Definition at line 263 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 263 of file G4hImpactIonisation.hh
Referenced by GetConstraints(), PrintInfoDefinition(), SetBarkasOff(), and SetBarkasOn().
G4VLowEnergyModel* G4hImpactIonisation::theIonChuFluctuationModel private
Definition at line 245 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 245 of file G4hImpactIonisation.hh
Referenced by InitializeParametrisation(), and ~G4hImpactIonisation().
G4VLowEnergyModel* G4hImpactIonisation::theIonEffChargeModel private
Definition at line 243 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 243 of file G4hImpactIonisation.hh
Referenced by BuildPhysicsTable(), ComputeDEDX(), GetMeanFreePath(), InitializeParametrisation(), and ~G4hImpactIonisation().
G4VLowEnergyModel* G4hImpactIonisation::theIonYangFluctuationModel private
Definition at line 246 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 246 of file G4hImpactIonisation.hh
Referenced by InitializeParametrisation(), and ~G4hImpactIonisation().
G4PhysicsTable* G4hImpactIonisation::theMeanFreePathTable private
Definition at line 269 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 269 of file G4hImpactIonisation.hh
Referenced by BuildLambdaTable(), BuildPhysicsTable(), and ~G4hImpactIonisation().
G4VLowEnergyModel* G4hImpactIonisation::theNuclearStoppingModel private
Definition at line 244 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 244 of file G4hImpactIonisation.hh
Referenced by AlongStepDoIt(), InitializeParametrisation(), and ~G4hImpactIonisation().
G4String G4hImpactIonisation::theNuclearTable private
Definition at line 253 of file G4hImpactIonisation.hh.
View newest version in sPHENIX GitHub at line 253 of file G4hImpactIonisation.hh
Referenced by InitializeParametrisation(), PrintInfoDefinition(), and SetNuclearStoppingPowerModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4hImpactIonisation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/src/G4hImpactIonisation.cc