ECCE @ EIC Software: G4Event Class Reference
G4Event Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4Event.hh>
Public Member Functions
G4Event ()
G4Event (G4int evID)
~G4Event ()
void * operator new (size_t)
void operator delete (void *anEvent)
G4bool operator== (const G4Event &right) const
G4bool operator!= (const G4Event &right) const
void Print () const
void Draw () const
void SetEventID (G4int i)
void SetHCofThisEvent (G4HCofThisEvent *value)
void SetDCofThisEvent (G4DCofThisEvent *value)
void SetTrajectoryContainer (G4TrajectoryContainer *value)
void SetEventAborted ()
void SetRandomNumberStatus (G4String &st)
void SetRandomNumberStatusForProcessing (G4String &st)
void KeepTheEvent (G4bool vl=true)
G4bool ToBeKept () const
void KeepForPostProcessing () const
void PostProcessingFinished () const
G4int GetNumberOfGrips () const
G4int GetEventID () const
void AddPrimaryVertex (G4PrimaryVertex *aPrimaryVertex)
G4int GetNumberOfPrimaryVertex () const
G4PrimaryVertex * GetPrimaryVertex (G4int i=0) const
G4HCofThisEvent * GetHCofThisEvent () const
G4DCofThisEvent * GetDCofThisEvent () const
G4TrajectoryContainer * GetTrajectoryContainer () const
G4bool IsAborted () const
void SetUserInformation (G4VUserEventInformation *anInfo)
G4VUserEventInformation * GetUserInformation () const
const G4String & GetRandomNumberStatus () const
const G4String & GetRandomNumberStatusForProcessing () const
Private Member Functions
G4Event (const G4Event &)
G4Event & operator= (const G4Event &)
Private Attributes
G4int eventID
G4PrimaryVertex * thePrimaryVertex
G4int numberOfPrimaryVertex
G4HCofThisEvent * HC
G4DCofThisEvent * DC
G4TrajectoryContainer * trajectoryContainer
G4bool eventAborted
G4VUserEventInformation * userInfo
G4String * randomNumberStatus
G4bool validRandomNumberStatus
G4String * randomNumberStatusForProcessing
G4bool validRandomNumberStatusForProcessing
G4bool keepTheEvent
G4int grips
Detailed Description
Definition at line 51 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 51 of file G4Event.hh
Constructor & Destructor Documentation
G4Event::G4Event ()
Definition at line 45 of file G4Event.cc.
View newest version in sPHENIX GitHub at line 45 of file G4Event.cc
G4Event::G4Event (G4int evID)
Definition at line 56 of file G4Event.cc.
View newest version in sPHENIX GitHub at line 56 of file G4Event.cc
G4Event::~G4Event ()
Definition at line 67 of file G4Event.cc.
View newest version in sPHENIX GitHub at line 67 of file G4Event.cc
References G4TrajectoryContainer::clearAndDestroy(), G4PrimaryVertex::ClearNext(), DC, G4PrimaryVertex::GetNext(), HC, randomNumberStatus, randomNumberStatusForProcessing, thePrimaryVertex, trajectoryContainer, and userInfo.
G4Event::G4Event (const G4Event &) inline private
Definition at line 74 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 74 of file G4Event.hh
Member Function Documentation
void G4Event::AddPrimaryVertex (G4PrimaryVertex * aPrimaryVertex) inline
Definition at line 153 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 153 of file G4Event.hh
References numberOfPrimaryVertex, G4PrimaryVertex::SetNext(), and thePrimaryVertex.
Referenced by export_G4Event(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4HEPEvtInterface::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), and G4RayShooter::Shoot().
void G4Event::Draw () const
Definition at line 105 of file G4Event.cc.
View newest version in sPHENIX GitHub at line 105 of file G4Event.cc
References DC, G4VDigiCollection::DrawAllDigi(), G4VHitsCollection::DrawAllHits(), G4TrajectoryContainer::entries(), G4DCofThisEvent::GetCapacity(), G4HCofThisEvent::GetCapacity(), G4VVisManager::GetConcreteInstance(), G4DCofThisEvent::GetDC(), G4HCofThisEvent::GetHC(), HC, and trajectoryContainer.
Referenced by export_G4Event().
G4DCofThisEvent* G4Event::GetDCofThisEvent () const inline
Definition at line 186 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 186 of file G4Event.hh
References DC.
Referenced by G4DigiManager::GetDigiCollection(), G4DigiManager::SetDigiCollection(), and G4PersistencyManager::Store().
G4int G4Event::GetEventID () const inline
Definition at line 150 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 150 of file G4Event.hh
References eventID.
Referenced by ExGflashEventAction::BeginOfEventAction(), eRositaEventAction::BeginOfEventAction(), CCalEventAction::BeginOfEventAction(), F04EventAction::BeginOfEventAction(), FCALTBEventAction::BeginOfEventAction(), WLSEventAction::BeginOfEventAction(), PurgMagEventAction::BeginOfEventAction(), IORTEventAction::BeginOfEventAction(), doiPETEventAction::BeginOfEventAction(), RMC01EventAction::BeginOfEventAction(), GammaRayTelEventAction::BeginOfEventAction(), XrayFluoEventAction::BeginOfEventAction(), RMC01AdjointEventAction::BeginOfEventAction(), UltraEventAction::BeginOfEventAction(), DMXEventAction::BeginOfEventAction(), RMC01AnalysisManager::ComputeMeanEdepAndError(), G4VisManager::Draw(), RMC01AnalysisManager::EndOfEvent(), ScoreSpecies::EndOfEvent(), G4VisManager::EndOfEvent(), ExN04EventAction::EndOfEventAction(), RE05EventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), F04EventAction::EndOfEventAction(), ExN02EventAction::EndOfEventAction(), ExP01EventAction::EndOfEventAction(), WLSEventAction::EndOfEventAction(), RE04EventAction::EndOfEventAction(), RE02EventAction::EndOfEventAction(), doiPETEventAction::EndOfEventAction(), GammaRayTelEventAction::EndOfEventAction(), export_G4Event(), G4Pevent::G4Pevent(), G4WorkerRunManager::GenerateEvent(), G4RunManager::GenerateEvent(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), FCALPrimaryGeneratorAction::GeneratePrimaries(), G01PrimaryGeneratorAction::GeneratePrimaries(), G04PrimaryGeneratorAction::GeneratePrimaries(), UltraPrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), F04EventAction::GetEventNo(), WLSEventAction::GetEventNo(), G4VisCommandSceneAddEventID::EventID::operator()(), PrimaryKiller::ProcessHits(), G4WorkerRunManager::ProcessOneEvent(), G4RTRun::RecordEvent(), G4PersistencyManager::Retrieve(), G4WorkerRunManager::rndmSaveThisEvent(), G4RunManager::rndmSaveThisEvent(), WLSSteppingAction::SaveRandomStatus(), G4PersistencyManager::Store(), G4RunManager::UpdateScoring(), and EventAction::WriteFibers().
G4HCofThisEvent* G4Event::GetHCofThisEvent () const inline
Definition at line 184 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 184 of file G4Event.hh
References HC.
Referenced by G4EventManager::DoProcessing(), ExGflashEventAction::EndOfEventAction(), RE05EventAction::EndOfEventAction(), G4HumanPhantomEventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), B3aEventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), WLSEventAction::EndOfEventAction(), GammaRayTelEventAction::EndOfEventAction(), UltraEventAction::EndOfEventAction(), DMXEventAction::EndOfEventAction(), XrayFluoEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), RE01StackingAction::GetCalCollection(), RE05StackingAction::GetCollection(), ExN04StackingAction::GetCollection(), G4DigiManager::GetHitsCollection(), RE06Run::RecordEvent(), ElectronRun::RecordEvent(), ML2Run::RecordEvent(), B03Run::RecordEvent(), B02Run::RecordEvent(), B01Run::RecordEvent(), DicomRun::RecordEvent(), Dicom2Run::RecordEvent(), RE02Run::RecordEvent(), TSRun::RecordEvent(), G4PersistencyManager::Store(), and G4RunManager::UpdateScoring().
G4int G4Event::GetNumberOfGrips () const inline
Definition at line 146 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 146 of file G4Event.hh
References grips.
Referenced by G4RunManager::CleanUpUnnecessaryEvents(), and G4RunManager::StackPreviousEvent().
G4int G4Event::GetNumberOfPrimaryVertex () const inline
Definition at line 163 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 163 of file G4Event.hh
References numberOfPrimaryVertex.
Referenced by G4EventManager::DoProcessing(), RE01EventAction::EndOfEventAction(), export_G4Event(), RE01PrimaryGeneratorAction::GeneratePrimaries(), and Par02PrimaryGeneratorAction::GeneratePrimaries().
G4PrimaryVertex* G4Event::GetPrimaryVertex (G4int i = 0) const inline
Definition at line 166 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 166 of file G4Event.hh
References G4PrimaryVertex::GetNext(), numberOfPrimaryVertex, and thePrimaryVertex.
Referenced by PHG4TruthEventAction::EndOfEventAction(), ExGflashEventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), export_G4Event(), Par02PrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction1::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), and G4PrimaryTransformer::GimmePrimaries().
const G4String& G4Event::GetRandomNumberStatus () const inline
Definition at line 200 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 200 of file G4Event.hh
References G4Exception(), JustWarning, randomNumberStatus, and validRandomNumberStatus.
const G4String& G4Event::GetRandomNumberStatusForProcessing () const inline
Definition at line 208 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 208 of file G4Event.hh
References G4Exception(), JustWarning, randomNumberStatusForProcessing, and validRandomNumberStatusForProcessing.
G4TrajectoryContainer* G4Event::GetTrajectoryContainer () const inline
Definition at line 188 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 188 of file G4Event.hh
References trajectoryContainer.
Referenced by DMXEventAction::drawTracks(), CexmcEventAction::DrawTrajectories(), ExGflashEventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), ExN02EventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), ExP01EventAction::EndOfEventAction(), RE04EventAction::EndOfEventAction(), RE02EventAction::EndOfEventAction(), G4BlineEventAction::EndOfEventAction(), ITTrackingInteractivity::EndTracking(), export_G4Event(), G4TheRayTracer::GenerateColour(), and G4RTRun::RecordEvent().
G4VUserEventInformation* G4Event::GetUserInformation () const inline
Definition at line 198 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 198 of file G4Event.hh
References userInfo.
Referenced by CexmcRunManager::DoCommonEventLoop(), CexmcEventAction::EndOfEventAction(), export_G4Event(), and G4EventManager::GetUserInformation().
G4bool G4Event::IsAborted () const inline
Definition at line 194 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 194 of file G4Event.hh
References eventAborted.
Referenced by export_G4Event(), and Run::RecordEvent().
void G4Event::KeepForPostProcessing () const inline
Definition at line 138 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 138 of file G4Event.hh
References grips.
Referenced by G4VisManager::EndOfEvent().
void G4Event::KeepTheEvent (G4bool vl = true) inline
Definition at line 134 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 134 of file G4Event.hh
References keepTheEvent.
Referenced by G4EventManager::KeepTheCurrentEvent().
void G4Event::operator delete (void * anEvent) inline
Definition at line 227 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 227 of file G4Event.hh
References anEventAllocator().
void * G4Event::operator new (size_t) inline
Definition at line 221 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Event.hh
References anEventAllocator().
G4bool G4Event::operator!= (const G4Event & right) const
Definition at line 95 of file G4Event.cc.
View newest version in sPHENIX GitHub at line 95 of file G4Event.cc
References eventID.
G4Event& G4Event::operator= (const G4Event &) inline private
Definition at line 75 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 75 of file G4Event.hh
G4bool G4Event::operator== (const G4Event & right) const
Definition at line 90 of file G4Event.cc.
View newest version in sPHENIX GitHub at line 90 of file G4Event.cc
References eventID.
void G4Event::PostProcessingFinished () const inline
Definition at line 140 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 140 of file G4Event.hh
References FatalException, G4Exception(), and grips.
void G4Event::Print (void) const
Definition at line 100 of file G4Event.cc.
View newest version in sPHENIX GitHub at line 100 of file G4Event.cc
References eventID, G4cout, and G4endl.
Referenced by export_G4Event().
void G4Event::SetDCofThisEvent (G4DCofThisEvent * value) inline
Definition at line 118 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 118 of file G4Event.hh
References DC.
Referenced by G4DigiManager::SetDigiCollection().
void G4Event::SetEventAborted () inline
Definition at line 122 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 122 of file G4Event.hh
References eventAborted.
Referenced by G4RunManager::AbortEvent(), G4RunManager::AbortRun(), and export_G4Event().
void G4Event::SetEventID (G4int i) inline
Definition at line 114 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 114 of file G4Event.hh
References eventID.
Referenced by export_G4Event(), G4WorkerRunManager::GenerateEvent(), G4MTRunManager::SetUpAnEvent(), and G4MTRunManager::SetUpNEvents().
void G4Event::SetHCofThisEvent (G4HCofThisEvent * value) inline
Definition at line 116 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 116 of file G4Event.hh
References HC.
Referenced by G4EventManager::DoProcessing().
void G4Event::SetRandomNumberStatus (G4String & st) inline
Definition at line 124 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 124 of file G4Event.hh
References randomNumberStatus, and validRandomNumberStatus.
Referenced by G4WorkerRunManager::GenerateEvent(), G4RunManager::GenerateEvent(), and G4EventManager::ProcessOneEvent().
void G4Event::SetRandomNumberStatusForProcessing (G4String & st) inline
Definition at line 129 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 129 of file G4Event.hh
References randomNumberStatusForProcessing, and validRandomNumberStatusForProcessing.
Referenced by G4EventManager::DoProcessing().
void G4Event::SetTrajectoryContainer (G4TrajectoryContainer * value) inline
Definition at line 120 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 120 of file G4Event.hh
References trajectoryContainer.
Referenced by G4EventManager::DoProcessing(), and ITTrackingInteractivity::EndTracking().
void G4Event::SetUserInformation (G4VUserEventInformation * anInfo) inline
Definition at line 197 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 197 of file G4Event.hh
References userInfo.
Referenced by CexmcEventAction::EndOfEventAction(), export_G4Event(), and G4EventManager::SetUserInformation().
G4bool G4Event::ToBeKept () const inline
Definition at line 136 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 136 of file G4Event.hh
References keepTheEvent.
Referenced by G4RunManager::CleanUpPreviousEvents(), G4RunManager::CleanUpUnnecessaryEvents(), G4VisManager::EndOfEvent(), and G4RunManager::StackPreviousEvent().
Member Data Documentation
G4DCofThisEvent* G4Event::DC private
Definition at line 89 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 89 of file G4Event.hh
Referenced by Draw(), GetDCofThisEvent(), SetDCofThisEvent(), and ~G4Event().
G4bool G4Event::eventAborted private
Definition at line 96 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Event.hh
Referenced by IsAborted(), and SetEventAborted().
G4int G4Event::eventID private
Definition at line 79 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 79 of file G4Event.hh
Referenced by GetEventID(), operator!=(), operator==(), Print(), and SetEventID().
G4int G4Event::grips mutable private
Definition at line 111 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 111 of file G4Event.hh
Referenced by GetNumberOfGrips(), KeepForPostProcessing(), and PostProcessingFinished().
G4HCofThisEvent* G4Event::HC private
Definition at line 86 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 86 of file G4Event.hh
Referenced by Draw(), GetHCofThisEvent(), SetHCofThisEvent(), and ~G4Event().
G4bool G4Event::keepTheEvent private
Definition at line 110 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 110 of file G4Event.hh
Referenced by KeepTheEvent(), and ToBeKept().
G4int G4Event::numberOfPrimaryVertex private
Definition at line 83 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 83 of file G4Event.hh
Referenced by AddPrimaryVertex(), GetNumberOfPrimaryVertex(), and GetPrimaryVertex().
G4String* G4Event::randomNumberStatus private
Definition at line 102 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 102 of file G4Event.hh
Referenced by GetRandomNumberStatus(), SetRandomNumberStatus(), and ~G4Event().
G4String* G4Event::randomNumberStatusForProcessing private
Definition at line 106 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 106 of file G4Event.hh
Referenced by GetRandomNumberStatusForProcessing(), SetRandomNumberStatusForProcessing(), and ~G4Event().
G4PrimaryVertex* G4Event::thePrimaryVertex private
Definition at line 82 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 82 of file G4Event.hh
Referenced by AddPrimaryVertex(), GetPrimaryVertex(), and ~G4Event().
G4TrajectoryContainer* G4Event::trajectoryContainer private
Definition at line 92 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 92 of file G4Event.hh
Referenced by Draw(), GetTrajectoryContainer(), SetTrajectoryContainer(), and ~G4Event().
G4VUserEventInformation* G4Event::userInfo private
Definition at line 99 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 99 of file G4Event.hh
Referenced by GetUserInformation(), SetUserInformation(), and ~G4Event().
G4bool G4Event::validRandomNumberStatus private
Definition at line 103 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 103 of file G4Event.hh
Referenced by GetRandomNumberStatus(), and SetRandomNumberStatus().
G4bool G4Event::validRandomNumberStatusForProcessing private
Definition at line 107 of file G4Event.hh.
View newest version in sPHENIX GitHub at line 107 of file G4Event.hh
Referenced by GetRandomNumberStatusForProcessing(), and SetRandomNumberStatusForProcessing().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4Event.hh
geant4/tree/geant4-10.6-release/source/event/src/G4Event.cc