ECCE @ EIC Software: PHG4FCalDetector Class Reference
PHG4FCalDetector Class Reference
#include <fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4FCalDetector.h>
Public Member Functions
PHG4FCalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &name)
virtual ~PHG4FCalDetector (void)
virtual void ConstructMe (G4LogicalVolume *world)
virtual G4UserSteppingAction * GetSteppingAction ()
bool isInScintillator (G4VPhysicalVolume *volume)
int getScintillatorLayer (G4VPhysicalVolume *volume)
unsigned int computeIndex (unsigned int layer, G4double x, G4double y, G4double z, G4double &xcenter, G4double &ycenter, G4double &zcenter)
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void PostConstruction ()
Optional PostConstruction call after all geometry is constructed.
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Member Functions
G4Material * SetMaterial (G4String)
Private Attributes
G4double length
G4double absorber_thickness
G4double scintillator_thickness
unsigned int nlayers
unsigned int segments_per_column
unsigned int segments_per_thickness
G4double z_position
G4double layer_separation
G4Material * AbsorberMaterial
G4Material * ScintillatorMaterial
std::map< unsigned int, G4Box * > absorber_solid_
std::map< unsigned int,
G4LogicalVolume * > absorber_logic_
std::map< unsigned int,
G4VPhysicalVolume * > absorber_physi_
std::map< unsigned int, G4Box * > scintillator_solid_
std::map< unsigned int,
G4LogicalVolume * > scintillator_logic_
std::map< unsigned int,
G4VPhysicalVolume * > scintillator_physi_
G4Region * _region
Additional Inherited Members
Static Public Member Functions inherited from PHG4Detector
static G4Material * GetDetectorMaterial (const std::string &name, const bool quit=true)
static G4Element * GetDetectorElement (const std::string &name, const bool quit=true)
Detailed Description
Definition at line 23 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 23 of file PHG4FCalDetector.h
Constructor & Destructor Documentation
PHG4FCalDetector::PHG4FCalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & name)
Definition at line 30 of file PHG4FCalDetector.cc.
View newest version in sPHENIX GitHub at line 30 of file PHG4FCalDetector.cc
virtual PHG4FCalDetector::~PHG4FCalDetector (void) inline virtual
Definition at line 28 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 28 of file PHG4FCalDetector.h
Member Function Documentation
unsigned int PHG4FCalDetector::computeIndex (unsigned int layer, G4double x, G4double y, G4double z, G4double & xcenter, G4double & ycenter, G4double & zcenter)
Definition at line 57 of file PHG4FCalDetector.cc.
View newest version in sPHENIX GitHub at line 57 of file PHG4FCalDetector.cc
References absorber_thickness, int(), layer_separation, length, scintillator_thickness, segments_per_column, segments_per_thickness, z_position, and ETOF::z_start.
Referenced by PHG4FCalSteppingAction::UserSteppingAction().
void PHG4FCalDetector::ConstructMe (G4LogicalVolume * world) virtual
Implements PHG4Detector.
Definition at line 76 of file PHG4FCalDetector.cc.
View newest version in sPHENIX GitHub at line 76 of file PHG4FCalDetector.cc
References _region, absorber_logic_, absorber_physi_, absorber_solid_, absorber_thickness, AbsorberMaterial, G4Region::AddRootLogicalVolume(), cm, g4zmq::exit(), G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), G4TTL::layer, layer_separation, length, nlayers, scintillator_logic_, scintillator_physi_, scintillator_solid_, scintillator_thickness, ScintillatorMaterial, G4VisAttributes::SetForceSolid(), G4Region::SetRegionalSteppingAction(), G4VisAttributes::SetVisibility(), and z_position.
int PHG4FCalDetector::getScintillatorLayer (G4VPhysicalVolume * volume)
Definition at line 169 of file PHG4FCalDetector.cc.
View newest version in sPHENIX GitHub at line 169 of file PHG4FCalDetector.cc
References scintillator_physi_.
Referenced by PHG4FCalSteppingAction::UserSteppingAction().
virtual G4UserSteppingAction* PHG4FCalDetector::GetSteppingAction (void) inline virtual
Reimplemented from PHG4Detector.
Definition at line 32 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 32 of file PHG4FCalDetector.h
References _region, and G4Region::GetRegionalSteppingAction().
Referenced by PHG4FCalSubsystem::process_event().
bool PHG4FCalDetector::isInScintillator (G4VPhysicalVolume * volume)
Definition at line 157 of file PHG4FCalDetector.cc.
View newest version in sPHENIX GitHub at line 157 of file PHG4FCalDetector.cc
References scintillator_physi_.
Referenced by PHG4FCalSteppingAction::UserSteppingAction().
G4Material * PHG4FCalDetector::SetMaterial (G4String material) private
Definition at line 46 of file PHG4FCalDetector.cc.
View newest version in sPHENIX GitHub at line 46 of file PHG4FCalDetector.cc
References PHG4Detector::GetDetectorMaterial().
Member Data Documentation
G4Region* PHG4FCalDetector::_region private
Definition at line 63 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4FCalDetector.h
Referenced by ConstructMe(), and GetSteppingAction().
std::map<unsigned int, G4LogicalVolume*> PHG4FCalDetector::absorber_logic_ private
Definition at line 56 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 56 of file PHG4FCalDetector.h
Referenced by ConstructMe().
std::map<unsigned int, G4VPhysicalVolume*> PHG4FCalDetector::absorber_physi_ private
Definition at line 57 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 57 of file PHG4FCalDetector.h
Referenced by ConstructMe().
std::map<unsigned int, G4Box*> PHG4FCalDetector::absorber_solid_ private
Definition at line 55 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 55 of file PHG4FCalDetector.h
Referenced by ConstructMe().
G4double PHG4FCalDetector::absorber_thickness private
Definition at line 45 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4FCalDetector.h
Referenced by computeIndex(), and ConstructMe().
G4Material* PHG4FCalDetector::AbsorberMaterial private
Definition at line 52 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 52 of file PHG4FCalDetector.h
Referenced by ConstructMe().
G4double PHG4FCalDetector::layer_separation private
Definition at line 48 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 48 of file PHG4FCalDetector.h
Referenced by computeIndex(), and ConstructMe().
G4double PHG4FCalDetector::length private
Definition at line 45 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4FCalDetector.h
Referenced by computeIndex(), and ConstructMe().
unsigned int PHG4FCalDetector::nlayers private
Definition at line 46 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4FCalDetector.h
Referenced by ConstructMe().
std::map<unsigned int, G4LogicalVolume*> PHG4FCalDetector::scintillator_logic_ private
Definition at line 60 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 60 of file PHG4FCalDetector.h
Referenced by ConstructMe().
std::map<unsigned int, G4VPhysicalVolume*> PHG4FCalDetector::scintillator_physi_ private
Definition at line 61 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4FCalDetector.h
Referenced by ConstructMe(), getScintillatorLayer(), and isInScintillator().
std::map<unsigned int, G4Box*> PHG4FCalDetector::scintillator_solid_ private
Definition at line 59 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 59 of file PHG4FCalDetector.h
Referenced by ConstructMe().
G4double PHG4FCalDetector::scintillator_thickness private
Definition at line 45 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4FCalDetector.h
Referenced by computeIndex(), and ConstructMe().
G4Material* PHG4FCalDetector::ScintillatorMaterial private
Definition at line 53 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 53 of file PHG4FCalDetector.h
Referenced by ConstructMe().
unsigned int PHG4FCalDetector::segments_per_column private
Definition at line 46 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4FCalDetector.h
Referenced by computeIndex().
unsigned int PHG4FCalDetector::segments_per_thickness private
Definition at line 46 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 46 of file PHG4FCalDetector.h
Referenced by computeIndex().
G4double PHG4FCalDetector::z_position private
Definition at line 47 of file PHG4FCalDetector.h.
View newest version in sPHENIX GitHub at line 47 of file PHG4FCalDetector.h
Referenced by computeIndex(), and ConstructMe().
The documentation for this class was generated from the following files:
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4FCalDetector.h
fun4all_eicdetectors/blob/master/simulation/g4simulation/g4eiccalos/PHG4FCalDetector.cc