ECCE @ EIC Software: G4Tet Class Reference
G4Tet Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4Tet.hh>
Public Member Functions
G4Tet (const G4String &pName, const G4ThreeVector &anchor, const G4ThreeVector &p1, const G4ThreeVector &p2, const G4ThreeVector &p3, G4bool *degeneracyFlag=nullptr)
virtual ~G4Tet ()
void SetVertices (const G4ThreeVector &anchor, const G4ThreeVector &p1, const G4ThreeVector &p2, const G4ThreeVector &p3)
void GetVertices (G4ThreeVector &anchor, G4ThreeVector &p1, G4ThreeVector &p2, G4ThreeVector &p3) const
std::vector< G4ThreeVector > GetVertices () const
void PrintWarnings (G4bool)
G4bool CheckDegeneracy (const G4ThreeVector &p0, const G4ThreeVector &p1, const G4ThreeVector &p2, const G4ThreeVector &p3) const
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
G4ThreeVector GetPointOnSurface () const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4VisExtent GetExtent () const
G4Polyhedron * CreatePolyhedron () const
G4Polyhedron * GetPolyhedron () const
G4Tet (__void__ &)
G4Tet (const G4Tet &rhs)
G4Tet & operator= (const G4Tet &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
void Initialize (const G4ThreeVector &p0, const G4ThreeVector &p1, const G4ThreeVector &p2, const G4ThreeVector &p3)
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double halfTolerance = 0
G4double fCubicVolume = 0
G4double fSurfaceArea = 0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
G4ThreeVector fVertex [4]
G4ThreeVector fNormal [4]
G4double fDist [4] = {0}
G4double fArea [4] = {0}
G4ThreeVector fBmin
G4ThreeVector fBmax
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 55 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 55 of file G4Tet.hh
Constructor & Destructor Documentation
G4Tet::G4Tet (const G4String & pName, const G4ThreeVector & anchor, const G4ThreeVector & p1, const G4ThreeVector & p2, const G4ThreeVector & p3, G4bool * degeneracyFlag = nullptr)
Definition at line 66 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 66 of file G4Tet.cc
References kdfinder::abs(), CheckDegeneracy(), Acts::VectorHelpers::cross(), FatalException, G4Exception(), G4VSolid::GetName(), halfTolerance, Initialize(), G4VSolid::kCarTolerance, and message().
Referenced by Clone().
G4Tet::~G4Tet () virtual
Definition at line 113 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 113 of file G4Tet.cc
References fpPolyhedron.
G4Tet::G4Tet (__void__ & a)
Definition at line 104 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 104 of file G4Tet.cc
G4Tet::G4Tet (const G4Tet & rhs)
Definition at line 122 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 122 of file G4Tet.cc
References fArea, fBmax, fBmin, fCubicVolume, fDist, fNormal, fSurfaceArea, fVertex, and halfTolerance.
Member Function Documentation
G4ThreeVector G4Tet::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 430 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 430 of file G4Tet.cc
References d, DBL_MAX, CLHEP::Hep3Vector::dot(), fDist, and fNormal.
Referenced by SurfaceNormal().
void G4Tet::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 319 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 319 of file G4Tet.cc
References fBmax, and fBmin.
Referenced by CalculateExtent().
G4bool G4Tet::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 329 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 329 of file G4Tet.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), Acts::concept::exists, GetVertices(), pMax, x, y, and z.
G4bool G4Tet::CheckDegeneracy (const G4ThreeVector & p0, const G4ThreeVector & p1, const G4ThreeVector & p2, const G4ThreeVector & p3) const
Definition at line 173 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 173 of file G4Tet.cc
References kdfinder::abs(), Acts::VectorHelpers::cross(), k, and G4VSolid::kCarTolerance.
Referenced by G4Tet(), and SetVertices().
G4VSolid * G4Tet::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 553 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 553 of file G4Tet.cc
References G4Tet().
void G4Tet::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 309 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 309 of file G4Tet.cc
G4Polyhedron * G4Tet::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 646 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 646 of file G4Tet.cc
References HepPolyhedron::createPolyhedron(), CLHEP::Hep3Vector::cross(), CLHEP::Hep3Vector::dot(), fVertex, k2, v1, v2, and v3.
Referenced by G4ArrowModel::G4ArrowModel(), and GetPolyhedron().
void G4Tet::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 626 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 626 of file G4Tet.cc
References G4VGraphicsScene::AddSolid().
G4double G4Tet::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 447 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 447 of file G4Tet.cc
References DBL_MAX, CLHEP::Hep3Vector::dot(), fDist, fNormal, halfTolerance, kInfinity, max, and min.
G4double G4Tet::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 474 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 474 of file G4Tet.cc
References CLHEP::Hep3Vector::dot(), fDist, fNormal, and max.
G4double G4Tet::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 487 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 487 of file G4Tet.cc
References DBL_MAX, CLHEP::Hep3Vector::dot(), fDist, fNormal, halfTolerance, k, and tmp.
G4double G4Tet::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 531 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 531 of file G4Tet.cc
References CLHEP::Hep3Vector::dot(), fDist, fNormal, and min.
G4double G4Tet::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 608 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 608 of file G4Tet.cc
References fCubicVolume.
G4GeometryType G4Tet::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 544 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 544 of file G4Tet.cc
Referenced by StreamInfo().
G4VisExtent G4Tet::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 635 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 635 of file G4Tet.cc
References fBmax, fBmin, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4ThreeVector G4Tet::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 583 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 583 of file G4Tet.cc
References e1, e2, fArea, fSurfaceArea, fVertex, G4QuickRand(), r1, and r2.
G4Polyhedron * G4Tet::GetPolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 678 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 678 of file G4Tet.cc
References CreatePolyhedron(), fpPolyhedron, fRebuildPolyhedron, HepPolyhedron::GetNumberOfRotationSteps(), G4Polyhedron::GetNumberOfRotationStepsAtTimeOfCreation(), and G4TemplateAutoLock< _Mutex_t >::unlock().
G4double G4Tet::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 617 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 617 of file G4Tet.cc
References fSurfaceArea.
void G4Tet::GetVertices (G4ThreeVector & anchor, G4ThreeVector & p1, G4ThreeVector & p2, G4ThreeVector & p3) const
Definition at line 282 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 282 of file G4Tet.cc
References fVertex.
Referenced by PHG4GDMLWriteSolids::TetWrite(), and G4GDMLWriteSolids::TetWrite().
std::vector< G4ThreeVector > G4Tet::GetVertices () const
Definition at line 297 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 297 of file G4Tet.cc
References fVertex.
Referenced by CalculateExtent().
void G4Tet::Initialize (const G4ThreeVector & p0, const G4ThreeVector & p1, const G4ThreeVector & p2, const G4ThreeVector & p3) private
Definition at line 202 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 202 of file G4Tet.cc
References kdfinder::abs(), Acts::VectorHelpers::cross(), CLHEP::Hep3Vector::dot(), fArea, fBmax, fBmin, fCubicVolume, fDist, fNormal, fSurfaceArea, fVertex, CLHEP::Hep3Vector::mag(), max, min, norm, CLHEP::Hep3Vector::unit(), and Acts::Test::volume.
Referenced by G4Tet(), and SetVertices().
EInside G4Tet::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 379 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 379 of file G4Tet.cc
References CLHEP::Hep3Vector::dot(), fDist, fNormal, halfTolerance, kInside, kOutside, kSurface, and max.
G4Tet & G4Tet::operator= (const G4Tet & rhs)
Definition at line 140 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 140 of file G4Tet.cc
References fArea, fBmax, fBmin, fCubicVolume, fDist, fNormal, fpPolyhedron, fRebuildPolyhedron, fSurfaceArea, fVertex, halfTolerance, and G4VSolid::operator=().
void G4Tet::PrintWarnings (G4bool) inline
Definition at line 85 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 85 of file G4Tet.hh
void G4Tet::SetVertices (const G4ThreeVector & anchor, const G4ThreeVector & p1, const G4ThreeVector & p2, const G4ThreeVector & p3)
Definition at line 250 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 250 of file G4Tet.cc
References kdfinder::abs(), CheckDegeneracy(), Acts::VectorHelpers::cross(), FatalException, fRebuildPolyhedron, G4Exception(), G4VSolid::GetName(), Initialize(), and message().
std::ostream & G4Tet::StreamInfo (std::ostream & os) const virtual
Implements G4VSolid.
Definition at line 562 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 562 of file G4Tet.cc
References fVertex, GetEntityType(), G4VSolid::GetName(), and mm.
G4ThreeVector G4Tet::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 393 of file G4Tet.cc.
View newest version in sPHENIX GitHub at line 393 of file G4Tet.cc
References kdfinder::abs(), ApproxSurfaceNormal(), G4VSolid::DumpInfo(), fDist, fNormal, G4cout, G4Exception(), G4VSolid::GetName(), halfTolerance, JustWarning, k, message(), mm, norm, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4Tet::fArea[4] = {0} private
Definition at line 168 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 168 of file G4Tet.hh
Referenced by G4Tet(), GetPointOnSurface(), Initialize(), and operator=().
G4ThreeVector G4Tet::fBmax private
Definition at line 169 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 169 of file G4Tet.hh
Referenced by BoundingLimits(), G4Tet(), GetExtent(), Initialize(), and operator=().
G4ThreeVector G4Tet::fBmin private
Definition at line 169 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 169 of file G4Tet.hh
Referenced by BoundingLimits(), G4Tet(), GetExtent(), Initialize(), and operator=().
G4double G4Tet::fCubicVolume = 0 private
Definition at line 160 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 160 of file G4Tet.hh
Referenced by G4Tet(), GetCubicVolume(), Initialize(), and operator=().
G4double G4Tet::fDist[4] = {0} private
Definition at line 167 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 167 of file G4Tet.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4Tet(), Initialize(), Inside(), operator=(), and SurfaceNormal().
G4ThreeVector G4Tet::fNormal[4] private
Definition at line 166 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 166 of file G4Tet.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4Tet(), Initialize(), Inside(), operator=(), and SurfaceNormal().
G4Polyhedron* G4Tet::fpPolyhedron = nullptr mutable private
Definition at line 163 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 163 of file G4Tet.hh
Referenced by GetPolyhedron(), operator=(), and ~G4Tet().
G4bool G4Tet::fRebuildPolyhedron = false mutable private
Definition at line 162 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 162 of file G4Tet.hh
Referenced by GetPolyhedron(), operator=(), and SetVertices().
G4double G4Tet::fSurfaceArea = 0 private
Definition at line 161 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 161 of file G4Tet.hh
Referenced by G4Tet(), GetPointOnSurface(), GetSurfaceArea(), Initialize(), and operator=().
G4ThreeVector G4Tet::fVertex[4] private
Definition at line 165 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 165 of file G4Tet.hh
Referenced by CreatePolyhedron(), G4Tet(), GetPointOnSurface(), GetVertices(), Initialize(), operator=(), and StreamInfo().
G4double G4Tet::halfTolerance = 0 private
Definition at line 159 of file G4Tet.hh.
View newest version in sPHENIX GitHub at line 159 of file G4Tet.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Tet(), Inside(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4Tet.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4Tet.cc