ECCE @ EIC Software: G4PSCylinderSurfaceCurrent3D Class Reference
G4PSCylinderSurfaceCurrent3D Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSCylinderSurfaceCurrent3D.hh>
Public Member Functions
G4PSCylinderSurfaceCurrent3D (G4String name, G4int direction, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
G4PSCylinderSurfaceCurrent3D (G4String name, G4int direction, const G4String &unit, G4int ni=1, G4int nj=1, G4int nk=1, G4int depi=2, G4int depj=1, G4int depk=0)
virtual ~G4PSCylinderSurfaceCurrent3D ()
Public Member Functions inherited from G4PSCylinderSurfaceCurrent
G4PSCylinderSurfaceCurrent (G4String name, G4int direction, G4int depth=0)
G4PSCylinderSurfaceCurrent (G4String name, G4int direction, const G4String &unit, G4int depth=0)
virtual ~G4PSCylinderSurfaceCurrent ()
void Weighted (G4bool flg=true)
void DivideByArea (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4int GetIndex (G4Step *)
Protected Member Functions inherited from G4PSCylinderSurfaceCurrent
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
G4int IsSelectedSurface (G4Step *, G4Tubs *)
virtual void DefineUnitAndCategory ()
Protected Member Functions inherited from G4VPrimitiveScorer
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int fDepthi
G4int fDepthj
G4int fDepthk
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 53 of file G4PSCylinderSurfaceCurrent3D.hh.
View newest version in sPHENIX GitHub at line 53 of file G4PSCylinderSurfaceCurrent3D.hh
Constructor & Destructor Documentation
G4PSCylinderSurfaceCurrent3D::G4PSCylinderSurfaceCurrent3D (G4String name, G4int direction, G4int ni = 1, G4int nj = 1, G4int nk = 1, G4int depi = 2, G4int depj = 1, G4int depk = 0)
Definition at line 50 of file G4PSCylinderSurfaceCurrent3D.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PSCylinderSurfaceCurrent3D.cc
References G4VPrimitiveScorer::fNi, G4VPrimitiveScorer::fNj, and G4VPrimitiveScorer::fNk.
G4PSCylinderSurfaceCurrent3D::G4PSCylinderSurfaceCurrent3D (G4String name, G4int direction, const G4String & unit, G4int ni = 1, G4int nj = 1, G4int nk = 1, G4int depi = 2, G4int depj = 1, G4int depk = 0)
Definition at line 62 of file G4PSCylinderSurfaceCurrent3D.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PSCylinderSurfaceCurrent3D.cc
References G4VPrimitiveScorer::fNi, G4VPrimitiveScorer::fNj, G4VPrimitiveScorer::fNk, and G4PSCylinderSurfaceCurrent::SetUnit().
G4PSCylinderSurfaceCurrent3D::~G4PSCylinderSurfaceCurrent3D () virtual
Definition at line 76 of file G4PSCylinderSurfaceCurrent3D.cc.
View newest version in sPHENIX GitHub at line 76 of file G4PSCylinderSurfaceCurrent3D.cc
Member Function Documentation
G4int G4PSCylinderSurfaceCurrent3D::GetIndex (G4Step * aStep) protected virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 79 of file G4PSCylinderSurfaceCurrent3D.cc.
View newest version in sPHENIX GitHub at line 79 of file G4PSCylinderSurfaceCurrent3D.cc
References fDepthi, fDepthj, fDepthk, G4VPrimitiveScorer::fNj, G4VPrimitiveScorer::fNk, G4Step::GetPreStepPoint(), G4VTouchable::GetReplicaNumber(), G4StepPoint::GetTouchable(), and k.
Member Data Documentation
G4int G4PSCylinderSurfaceCurrent3D::fDepthi private
Definition at line 69 of file G4PSCylinderSurfaceCurrent3D.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PSCylinderSurfaceCurrent3D.hh
Referenced by GetIndex().
G4int G4PSCylinderSurfaceCurrent3D::fDepthj private
Definition at line 69 of file G4PSCylinderSurfaceCurrent3D.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PSCylinderSurfaceCurrent3D.hh
Referenced by GetIndex().
G4int G4PSCylinderSurfaceCurrent3D::fDepthk private
Definition at line 69 of file G4PSCylinderSurfaceCurrent3D.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PSCylinderSurfaceCurrent3D.hh
Referenced by GetIndex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSCylinderSurfaceCurrent3D.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSCylinderSurfaceCurrent3D.cc