ECCE @ EIC Software: G4AdjointPrimaryGenerator Class Reference
G4AdjointPrimaryGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4AdjointPrimaryGenerator.hh>
Public Member Functions
G4AdjointPrimaryGenerator ()
~G4AdjointPrimaryGenerator ()
void GenerateAdjointPrimaryVertex (G4Event *anEvt, G4ParticleDefinition *adj_part, G4double E1, G4double E2)
void GenerateFwdPrimaryVertex (G4Event *anEvt, G4ParticleDefinition *adj_part, G4double E1, G4double E2)
void SetSphericalAdjointPrimarySource (G4double radius, G4ThreeVector pos)
void SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume (const G4String &volume_name)
void ComputeAccumulatedDepthVectorAlongBackRay (G4ThreeVector glob_pos, G4ThreeVector direction, G4double ekin, G4ParticleDefinition *aPartDef)
G4double SampleDistanceAlongBackRayAndComputeWeightCorrection (G4double &weight_corr)
Private Member Functions
G4AdjointPrimaryGenerator (const G4AdjointPrimaryGenerator &)
G4AdjointPrimaryGenerator & operator= (const G4AdjointPrimaryGenerator &)
Private Attributes
G4AdjointPosOnPhysVolGenerator * theG4AdjointPosOnPhysVolGenerator
G4SingleParticleSource * theSingleParticleSource
G4String type_of_adjoint_source
G4double radius_spherical_source
G4ThreeVector center_spherical_source
G4Navigator * fLinearNavigator
G4PhysicsOrderedFreeVector * theAccumulatedDepthVector
Detailed Description
Definition at line 66 of file G4AdjointPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 66 of file G4AdjointPrimaryGenerator.hh
Constructor & Destructor Documentation
G4AdjointPrimaryGenerator::G4AdjointPrimaryGenerator ()
Definition at line 52 of file G4AdjointPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 52 of file G4AdjointPrimaryGenerator.cc
References center_spherical_source, G4SingleParticleSource::GetAngDist(), G4SingleParticleSource::GetEneDist(), G4AdjointPosOnPhysVolGenerator::GetInstance(), G4SingleParticleSource::GetPosDist(), G4SPSEneDistribution::SetAlpha(), G4SPSAngDistribution::SetAngDistType(), G4SPSEneDistribution::SetEnergyDisType(), G4SPSPosDistribution::SetPosDisType(), theG4AdjointPosOnPhysVolGenerator, theSingleParticleSource, and type_of_adjoint_source.
G4AdjointPrimaryGenerator::~G4AdjointPrimaryGenerator ()
Definition at line 69 of file G4AdjointPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 69 of file G4AdjointPrimaryGenerator.cc
References theSingleParticleSource.
G4AdjointPrimaryGenerator::G4AdjointPrimaryGenerator (const G4AdjointPrimaryGenerator &) private
Member Function Documentation
void G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay (G4ThreeVector glob_pos, G4ThreeVector direction, G4double ekin, G4ParticleDefinition * aPartDef)
Definition at line 153 of file G4AdjointPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 153 of file G4AdjointPrimaryGenerator.cc
References G4Navigator::ComputeStep(), fLinearNavigator, G4Material::GetDensity(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetTransportationManager(), G4PhysicsOrderedFreeVector::InsertValues(), G4Navigator::LocateGlobalPointAndSetup(), and theAccumulatedDepthVector.
void G4AdjointPrimaryGenerator::GenerateAdjointPrimaryVertex (G4Event * anEvt, G4ParticleDefinition * adj_part, G4double E1, G4double E2)
Definition at line 75 of file G4AdjointPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 75 of file G4AdjointPrimaryGenerator.cc
References e, G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume(), G4SingleParticleSource::GeneratePrimaryVertex(), G4SingleParticleSource::GetAngDist(), G4SingleParticleSource::GetEneDist(), G4SingleParticleSource::GetPosDist(), pos(), G4SPSPosDistribution::SetCentreCoords(), G4SPSEneDistribution::SetEmax(), G4SPSEneDistribution::SetEmin(), G4SingleParticleSource::SetParticleDefinition(), G4SPSAngDistribution::SetParticleMomentumDirection(), theG4AdjointPosOnPhysVolGenerator, theSingleParticleSource, and type_of_adjoint_source.
void G4AdjointPrimaryGenerator::GenerateFwdPrimaryVertex (G4Event * anEvt, G4ParticleDefinition * adj_part, G4double E1, G4double E2)
Definition at line 104 of file G4AdjointPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 104 of file G4AdjointPrimaryGenerator.cc
References e, G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume(), G4SingleParticleSource::GeneratePrimaryVertex(), G4SingleParticleSource::GetAngDist(), G4SingleParticleSource::GetEneDist(), G4SingleParticleSource::GetPosDist(), pos(), G4SPSPosDistribution::SetCentreCoords(), G4SPSEneDistribution::SetEmax(), G4SPSEneDistribution::SetEmin(), G4SingleParticleSource::SetParticleDefinition(), G4SPSAngDistribution::SetParticleMomentumDirection(), theG4AdjointPosOnPhysVolGenerator, theSingleParticleSource, and type_of_adjoint_source.
Referenced by G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
G4AdjointPrimaryGenerator& G4AdjointPrimaryGenerator::operator= (const G4AdjointPrimaryGenerator &) private
G4double G4AdjointPrimaryGenerator::SampleDistanceAlongBackRayAndComputeWeightCorrection (G4double & weight_corr)
Definition at line 203 of file G4AdjointPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 203 of file G4AdjointPrimaryGenerator.cc
References G4PhysicsVector::FindLinearEnergy(), G4UniformRand, and theAccumulatedDepthVector.
void G4AdjointPrimaryGenerator::SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume (const G4String & volume_name)
Definition at line 143 of file G4AdjointPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 143 of file G4AdjointPrimaryGenerator.cc
References G4AdjointPosOnPhysVolGenerator::DefinePhysicalVolume1(), G4SingleParticleSource::GetAngDist(), G4SingleParticleSource::GetPosDist(), G4SPSAngDistribution::SetAngDistType(), G4SPSPosDistribution::SetPosDisType(), theG4AdjointPosOnPhysVolGenerator, theSingleParticleSource, and type_of_adjoint_source.
Referenced by G4AdjointPrimaryGeneratorAction::SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume().
void G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource (G4double radius, G4ThreeVector pos)
Definition at line 128 of file G4AdjointPrimaryGenerator.cc.
View newest version in sPHENIX GitHub at line 128 of file G4AdjointPrimaryGenerator.cc
References center_spherical_source, G4SingleParticleSource::GetAngDist(), G4SingleParticleSource::GetPosDist(), halfpi, pi, radius, radius_spherical_source, G4SPSAngDistribution::SetAngDistType(), G4SPSPosDistribution::SetCentreCoords(), G4SPSAngDistribution::SetMaxTheta(), G4SPSAngDistribution::SetMinTheta(), G4SPSPosDistribution::SetPosDisShape(), G4SPSPosDistribution::SetPosDisType(), G4SPSPosDistribution::SetRadius(), theSingleParticleSource, and type_of_adjoint_source.
Referenced by G4AdjointPrimaryGeneratorAction::SetSphericalAdjointPrimarySource().
Member Data Documentation
G4ThreeVector G4AdjointPrimaryGenerator::center_spherical_source private
Definition at line 96 of file G4AdjointPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AdjointPrimaryGenerator.hh
Referenced by G4AdjointPrimaryGenerator(), and SetSphericalAdjointPrimarySource().
G4Navigator* G4AdjointPrimaryGenerator::fLinearNavigator private
Definition at line 97 of file G4AdjointPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AdjointPrimaryGenerator.hh
Referenced by ComputeAccumulatedDepthVectorAlongBackRay().
G4double G4AdjointPrimaryGenerator::radius_spherical_source private
Definition at line 95 of file G4AdjointPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 95 of file G4AdjointPrimaryGenerator.hh
Referenced by SetSphericalAdjointPrimarySource().
G4PhysicsOrderedFreeVector* G4AdjointPrimaryGenerator::theAccumulatedDepthVector private
Definition at line 98 of file G4AdjointPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AdjointPrimaryGenerator.hh
Referenced by ComputeAccumulatedDepthVectorAlongBackRay(), and SampleDistanceAlongBackRayAndComputeWeightCorrection().
G4AdjointPosOnPhysVolGenerator* G4AdjointPrimaryGenerator::theG4AdjointPosOnPhysVolGenerator private
Definition at line 88 of file G4AdjointPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 88 of file G4AdjointPrimaryGenerator.hh
Referenced by G4AdjointPrimaryGenerator(), GenerateAdjointPrimaryVertex(), GenerateFwdPrimaryVertex(), and SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume().
G4SingleParticleSource* G4AdjointPrimaryGenerator::theSingleParticleSource private
Definition at line 90 of file G4AdjointPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 90 of file G4AdjointPrimaryGenerator.hh
Referenced by G4AdjointPrimaryGenerator(), GenerateAdjointPrimaryVertex(), GenerateFwdPrimaryVertex(), SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume(), SetSphericalAdjointPrimarySource(), and ~G4AdjointPrimaryGenerator().
G4String G4AdjointPrimaryGenerator::type_of_adjoint_source private
Definition at line 94 of file G4AdjointPrimaryGenerator.hh.
View newest version in sPHENIX GitHub at line 94 of file G4AdjointPrimaryGenerator.hh
Referenced by G4AdjointPrimaryGenerator(), GenerateAdjointPrimaryVertex(), GenerateFwdPrimaryVertex(), SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume(), and SetSphericalAdjointPrimarySource().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4AdjointPrimaryGenerator.hh
geant4/tree/geant4-10.6-release/source/event/src/G4AdjointPrimaryGenerator.cc