ECCE @ EIC Software: G4Element Class Reference
G4Element Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4Element.hh>
Public Member Functions
G4Element (const G4String &name, const G4String &symbol, G4double Zeff, G4double Aeff)
G4Element (const G4String &name, const G4String &symbol, G4int nbIsotopes)
void AddIsotope (G4Isotope *isotope, G4double RelativeAbundance)
virtual ~G4Element ()
const G4String & GetName () const
const G4String & GetSymbol () const
G4double GetZ () const
G4int GetZasInt () const
G4double GetN () const
G4double GetAtomicMassAmu () const
G4double GetA () const
G4bool GetNaturalAbundanceFlag () const
void SetNaturalAbundanceFlag (G4bool)
G4int GetNbOfAtomicShells () const
G4double GetAtomicShell (G4int index) const
G4int GetNbOfShellElectrons (G4int index) const
size_t GetNumberOfIsotopes () const
G4IsotopeVector * GetIsotopeVector () const
G4double * GetRelativeAbundanceVector () const
const G4Isotope * GetIsotope (G4int iso) const
size_t GetIndex () const
G4double GetfCoulomb () const
G4double GetfRadTsai () const
G4IonisParamElm * GetIonisation () const
G4Element (__void__ &)
void SetName (const G4String &name)
Static Public Member Functions
static G4ElementTable * GetElementTable ()
static size_t GetNumberOfElements ()
static G4Element * GetElement (G4String name, G4bool warning=true)
Private Member Functions
void InitializePointers ()
void ComputeDerivedQuantities ()
void ComputeCoulombFactor ()
void ComputeLradTsaiFactor ()
void AddNaturalIsotopes ()
G4Element (G4Element &)=delete
const G4Element & operator= (const G4Element &)=delete
G4bool operator== (const G4Element &) const =delete
G4bool operator!= (const G4Element &) const =delete
Private Attributes
G4String fName
G4String fSymbol
G4double fZeff
G4double fNeff
G4double fAeff
G4int fZ
G4int fNbOfAtomicShells
G4double * fAtomicShells
G4int * fNbOfShellElectrons
G4int fNumberOfIsotopes
G4IsotopeVector * theIsotopeVector
G4double * fRelativeAbundanceVector
size_t fIndexInTable
G4bool fNaturalAbundance
G4double fCoulomb
G4double fRadTsai
G4IonisParamElm * fIonisation
Static Private Attributes
static G4ElementTable theElementTable
Friends
std::ostream & operator<< (std::ostream &, const G4Element *)
std::ostream & operator<< (std::ostream &, const G4Element &)
std::ostream & operator<< (std::ostream &, G4ElementTable)
Detailed Description
Definition at line 96 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Element.hh
Constructor & Destructor Documentation
G4Element::G4Element (const G4String & name, const G4String & symbol, G4double Zeff, G4double Aeff)
Definition at line 74 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 74 of file G4Element.cc
References kdfinder::abs(), AddNaturalIsotopes(), ComputeDerivedQuantities(), fAeff, FatalException, fAtomicShells, fNbOfAtomicShells, fNbOfShellElectrons, fNeff, fZeff, Acts::UnitConstants::g, G4endl, G4Exception(), G4lrint(), G4AtomicShells::GetBindingEnergy(), G4AtomicShells::GetNumberOfElectrons(), G4AtomicShells::GetNumberOfShells(), InitializePointers(), JustWarning, mole, and perMillion.
G4Element::G4Element (const G4String & name, const G4String & symbol, G4int nbIsotopes)
Definition at line 127 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 127 of file G4Element.cc
References FatalException, fRelativeAbundanceVector, G4Exception(), InitializePointers(), n, and theIsotopeVector.
G4Element::~G4Element () virtual
Definition at line 252 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 252 of file G4Element.cc
References fAtomicShells, fIndexInTable, fIonisation, fNbOfShellElectrons, fRelativeAbundanceVector, theElementTable, and theIsotopeVector.
G4Element::G4Element (__void__ &)
Definition at line 244 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 244 of file G4Element.cc
References InitializePointers().
G4Element::G4Element (G4Element &) private delete
Member Function Documentation
void G4Element::AddIsotope (G4Isotope * isotope, G4double RelativeAbundance)
Definition at line 151 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 151 of file G4Element.cc
References ComputeDerivedQuantities(), fAeff, FatalException, fAtomicShells, fName, fNbOfAtomicShells, fNbOfShellElectrons, fNeff, fNumberOfIsotopes, fRelativeAbundanceVector, fZeff, Acts::UnitConstants::g, G4Exception(), G4AtomicShells::GetBindingEnergy(), G4AtomicShells::GetNumberOfElectrons(), G4AtomicShells::GetNumberOfShells(), G4Isotope::GetZ(), mole, and theIsotopeVector.
Referenced by G4NistElementBuilder::BuildElement(), G4tgbElement::BuildG4ElementFromIsotopes(), GB03DetectorConstruction::DefineMaterials(), RE06DetectorConstruction::DefineMaterials(), FFDetectorConstruction::DefineMaterials(), ExN03DetectorConstruction::DefineMaterials(), export_G4Element(), DetectorConstruction::MaterialWithSingleIsotope(), G4GDMLReadMaterials::MixtureRead(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
void G4Element::AddNaturalIsotopes () private
Definition at line 324 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 324 of file G4Element.cc
References fName, fNaturalAbundance, fNumberOfIsotopes, fRelativeAbundanceVector, fSymbol, fZeff, G4lrint(), G4NistManager::GetIsotopeAbundance(), G4NistManager::GetNistElementNames(), G4NistManager::GetNistFirstIsotopeN(), G4NistManager::GetNumberOfNistIsotopes(), incremental_prev_tag::idx, G4NistManager::Instance(), n, N, theIsotopeVector, x, and Z.
Referenced by G4Element().
void G4Element::ComputeCoulombFactor () private
Definition at line 286 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 286 of file G4Element.cc
References fCoulomb, source.hepunit::fine_structure_const, fZeff, k1, and k2.
Referenced by ComputeDerivedQuantities().
void G4Element::ComputeDerivedQuantities () private
Definition at line 266 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 266 of file G4Element.cc
References ComputeCoulombFactor(), ComputeLradTsaiFactor(), fIndexInTable, fIonisation, fZ, fZeff, G4lrint(), and theElementTable.
Referenced by AddIsotope(), and G4Element().
void G4Element::ComputeLradTsaiFactor () private
Definition at line 301 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 301 of file G4Element.cc
References source.hepunit::alpha_rcl2, fCoulomb, fRadTsai, fZeff, G4Log(), and G4lrint().
Referenced by ComputeDerivedQuantities().
G4double G4Element::GetA () const inline
Definition at line 138 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 138 of file G4Element.hh
References fAeff.
Referenced by G4ErrorFreeTrajState::CalculateEffectiveZandA(), MuCrossSections::CR_PerAtom(), FFDetectorConstruction::DefineMaterials(), G4tgbGeometryDumper::DumpElement(), G4GDMLWriteMaterials::ElementWrite(), PHG4GDMLWriteMaterials::ElementWrite(), export_G4Element(), GVFlashShowerParameterisation::GetEffA(), G4NativeScreenedCoulombCrossSection::LoadData(), G4LindhardRobinsonPartition::PartitionNIEL(), G4VLEPTSModel::ReadParam(), and G4hNuclearStoppingModel::StoppingPower().
G4double G4Element::GetAtomicMassAmu () const inline
Definition at line 135 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 135 of file G4Element.hh
References fNeff.
G4double G4Element::GetAtomicShell (G4int index) const
Definition at line 366 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 366 of file G4Element.cc
References FatalException, fAtomicShells, fName, fNbOfAtomicShells, fZeff, and G4Exception().
Referenced by G4AdjointPhotoElectricModel::AdjointCrossSectionPerAtom(), export_G4Element(), G4QAOLowEnergyLoss::GetOscillatorEnergy(), G4KleinNishinaModel::SampleSecondaries(), and G4PEEffectFluoModel::SampleSecondaries().
G4Element * G4Element::GetElement (G4String name, G4bool warning = true) static
Definition at line 411 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 411 of file G4Element.cc
References G4cout, G4endl, GetName(), and theElementTable.
Referenced by RE06DetectorConstruction::AddMaterial(), PHG4TTLDetector::BuildBarrelTTL(), PHG4TTLDetector::BuildForwardTTL(), EicFRichDetector::element_material(), export_G4Element(), PHG4CrystalCalorimeterDetector::GetCarbonFiber(), PHG4HybridHomogeneousCalorimeterDetector::GetCarbonFiber(), PHG4Detector::GetDetectorElement(), G4GDMLReadMaterials::GetElement(), PHG4ForwardDualReadoutDetector::GetPMMAMaterial(), PHG4ForwardDualReadoutDetector::GetQuartzMaterial(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetTedlarMaterial(), and PHG4HybridHomogeneousCalorimeterDetector::GetVM2000Material().
G4ElementTable * G4Element::GetElementTable () static
Definition at line 397 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 397 of file G4Element.cc
References theElementTable.
Referenced by G4ParticleHPData::addPhysicsVector(), G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4AdjointCSManager::BuildCrossSectionMatrices(), G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), G4VRangeToEnergyConverter::BuildLossTable(), G4ParticleHPCapture::BuildPhysicsTable(), G4ParticleHPJENDLHEData::BuildPhysicsTable(), G4ParticleHPFission::BuildPhysicsTable(), G4ParticleHPElastic::BuildPhysicsTable(), G4ParticleHPFissionData::BuildPhysicsTable(), G4ParticleHPCaptureData::BuildPhysicsTable(), G4ParticleHPElasticData::BuildPhysicsTable(), G4ParticleHPInelasticData::BuildPhysicsTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPInelastic::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), ExP02DetectorConstruction::Construct(), G4HadronHElasticPhysics::ConstructProcess(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4ParticleHPFissionData::DumpPhysicsTable(), G4ParticleHPCaptureData::DumpPhysicsTable(), G4ParticleHPElasticData::DumpPhysicsTable(), G4ParticleHPInelasticData::DumpPhysicsTable(), ExP02GeoTree::ExP02GeoTree(), export_G4Element(), CCalMaterialFactory::findElement(), G4NistElementBuilder::FindElement(), G4NistElementBuilder::FindOrBuildElement(), G4FissLib::G4FissLib(), G4ParticleHPData::G4ParticleHPData(), G4NistManager::GetElement(), G4LivermoreBremsstrahlungModel::Initialise(), G4NuclNuclDiffuseElastic::Initialise(), G4DiffuseElasticV2::Initialise(), G4DiffuseElastic::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), G4BetheHeitlerModel::InitialiseElementData(), G4eBremsstrahlungRelModel::InitialiseElementData(), G4PairProductionRelModel::InitialiseElementData(), G03DetectorConstruction::ListOfMaterials(), G02DetectorConstruction::ListOfMaterials(), G4NistManager::PrintG4Element(), CCalMaterialFactory::readElements(), G4ExcitationHandler::SetParameters(), G4GDMLRead::StripNames(), and G4NistManager::~G4NistManager().
G4double G4Element::GetfCoulomb () const inline
Definition at line 190 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 190 of file G4Element.hh
References fCoulomb.
Referenced by export_G4Element(), G4BetheHeitlerModel::InitialiseElementData(), G4eBremsstrahlungRelModel::InitialiseElementData(), G4PairProductionRelModel::InitialiseElementData(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), and G4eBremParametrizedModel::SetCurrentElement().
G4double G4Element::GetfRadTsai () const inline
Definition at line 194 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 194 of file G4Element.hh
References fRadTsai.
Referenced by export_G4Element().
size_t G4Element::GetIndex () const inline
Definition at line 181 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Element.hh
References fIndexInTable.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4AdjointCSManager::ComputeAdjointCS(), export_G4Element(), G4NistElementBuilder::FindOrBuildElement(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4ParticleHPJENDLHEData::IsApplicable(), G4ParticleHPThermalScatteringData::IsApplicable(), G4ParticleHPData::MakePhysicsVector(), and G4VEmAdjointModel::SelectCSMatrix().
G4IonisParamElm* G4Element::GetIonisation () const inline
Definition at line 198 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 198 of file G4Element.hh
References fIonisation.
Referenced by G4IonisParamMat::ComputeIonParameters(), G4IonisParamMat::ComputeMeanParameters(), export_G4Element(), G4BetheHeitlerModel::InitialiseElementData(), G4PairProductionRelModel::InitialiseElementData(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), and G4BetheHeitlerModel::SampleSecondaries().
const G4Isotope* G4Element::GetIsotope (G4int iso) const inline
Definition at line 169 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 169 of file G4Element.hh
References theIsotopeVector.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4ParticleHPJENDLHEData::BuildPhysicsTable(), G4Nucleus::ChooseParameters(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4GDMLWriteMaterials::ElementWrite(), PHG4GDMLWriteMaterials::ElementWrite(), export_G4Element(), G4ParticleHPJENDLHEData::GetCrossSection(), G4CrossSectionDataStore::GetCrossSection(), G4ParticleHPElementData::Init(), G4LENDCrossSection::IsIsoApplicable(), G4ParticleHPChannel::Register(), G4CrossSectionDataStore::SampleZandA(), G4NeutronInelasticXS::SelectIsotope(), G4NeutronElasticXS::SelectIsotope(), G4ParticleInelasticXS::SelectIsotope(), G4NeutronCaptureXS::SelectIsotope(), G4VCrossSectionDataSet::SelectIsotope(), G4VEmModel::SelectIsotopeNumber(), G4ElementSelector::SelectZandA(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
G4IsotopeVector* G4Element::GetIsotopeVector () const inline
Definition at line 162 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 162 of file G4Element.hh
References theIsotopeVector.
Referenced by G4VCrossSectionDataSet::ComputeCrossSection(), G4tgbGeometryDumper::DumpElement(), export_G4Element(), G4MuNeutrinoNucleusTotXsc::GetElementCrossSection(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), and G4ElementSelector::SelectZandA().
G4double G4Element::GetN () const inline
Definition at line 134 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 134 of file G4Element.hh
References fNeff.
Referenced by G4AdjointCSManager::BuildCrossSectionMatrices(), G4Nucleus::ChooseParameters(), G4EmCalculator::ComputeCrossSectionPerAtom(), G4VEmModel::ComputeCrossSectionPerAtom(), G4ICRU49NuclearStoppingModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeIonParameters(), export_G4Element(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4VComponentCrossSection::GetElasticElementCrossSection(), G4ChargeExchangeProcess::GetElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXsc(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscNS(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscPDG(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXsc(), G4VComponentCrossSection::GetInelasticElementCrossSection(), G4QAOLowEnergyLoss::GetOscillatorEnergy(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4VComponentCrossSection::GetTotalElementCrossSection(), and G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget().
const G4String& G4Element::GetName (void) const inline
Definition at line 126 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 126 of file G4Element.hh
References fName.
Referenced by G4Material::AddElement(), G4ParticleHPInelastic::ApplyYourself(), G4HadronStoppingProcess::AtRestDoIt(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4ParticleHPChannelList::DumpInfo(), G4ParticleHPChannel::DumpInfo(), G4GDMLWriteMaterials::ElementWrite(), PHG4GDMLWriteMaterials::ElementWrite(), export_G4Element(), G4tgbMaterialMgr::FindOrBuildG4Element(), G4CrystalExtension::GetAtomBase(), G4CrossSectionDataStore::GetCrossSection(), GetElement(), G4ChargeExchangeProcess::GetElementCrossSection(), G4CrossSectionDataStore::GetIsoCrossSection(), G4VCrossSectionDataSet::GetIsoCrossSection(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4NistManager::PrintG4Element(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4GDMLRead::StripNames(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
G4bool G4Element::GetNaturalAbundanceFlag () const inline
Definition at line 261 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 261 of file G4Element.hh
References fNaturalAbundance.
Referenced by G4CrossSectionDataStore::GetCrossSection(), and G4NeutronElasticXS::SelectIsotope().
G4int G4Element::GetNbOfAtomicShells () const inline
Definition at line 146 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 146 of file G4Element.hh
References fNbOfAtomicShells.
Referenced by G4AdjointPhotoElectricModel::AdjointCrossSectionPerAtom(), export_G4Element(), G4KleinNishinaModel::SampleSecondaries(), and G4PEEffectFluoModel::SampleSecondaries().
G4int G4Element::GetNbOfShellElectrons (G4int index) const
Definition at line 381 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 381 of file G4Element.cc
References FatalException, fName, fNbOfAtomicShells, fNbOfShellElectrons, fZeff, and G4Exception().
Referenced by G4KleinNishinaModel::SampleSecondaries().
size_t G4Element::GetNumberOfElements () static
Definition at line 404 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 404 of file G4Element.cc
References theElementTable.
Referenced by G4ParticleHPData::addPhysicsVector(), G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), G4VRangeToEnergyConverter::BuildLossTable(), G4ParticleHPCapture::BuildPhysicsTable(), G4ParticleHPJENDLHEData::BuildPhysicsTable(), G4ParticleHPFission::BuildPhysicsTable(), G4ParticleHPElastic::BuildPhysicsTable(), G4ParticleHPFissionData::BuildPhysicsTable(), G4ParticleHPCaptureData::BuildPhysicsTable(), G4ParticleHPElasticData::BuildPhysicsTable(), G4ParticleHPInelasticData::BuildPhysicsTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPInelastic::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4ParticleHPFissionData::DumpPhysicsTable(), G4ParticleHPCaptureData::DumpPhysicsTable(), G4ParticleHPElasticData::DumpPhysicsTable(), G4ParticleHPInelasticData::DumpPhysicsTable(), export_G4Element(), G4FissLib::G4FissLib(), G4ParticleHPData::G4ParticleHPData(), G4LivermoreBremsstrahlungModel::Initialise(), G4NuclNuclDiffuseElastic::Initialise(), G4DiffuseElasticV2::Initialise(), G4DiffuseElastic::Initialise(), G4VAtomDeexcitation::InitialiseAtomicDeexcitation(), and G4VRangeToEnergyConverter::operator=().
size_t G4Element::GetNumberOfIsotopes () const inline
Definition at line 158 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 158 of file G4Element.hh
References fNumberOfIsotopes.
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4Nucleus::ChooseParameters(), G4VCrossSectionDataSet::ComputeCrossSection(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4tgbGeometryDumper::DumpElement(), G4GDMLWriteMaterials::ElementWrite(), PHG4GDMLWriteMaterials::ElementWrite(), export_G4Element(), G4ParticleHPJENDLHEData::GetCrossSection(), G4CrossSectionDataStore::GetCrossSection(), G4MuNeutrinoNucleusTotXsc::GetElementCrossSection(), G4ParticleHPElementData::Init(), G4LENDCrossSection::IsIsoApplicable(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4ParticleHPChannel::Register(), G4CrossSectionDataStore::SampleZandA(), G4NeutronInelasticXS::SelectIsotope(), G4ParticleInelasticXS::SelectIsotope(), G4NeutronElasticXS::SelectIsotope(), G4NeutronCaptureXS::SelectIsotope(), G4VCrossSectionDataSet::SelectIsotope(), G4VEmModel::SelectIsotopeNumber(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
G4double* G4Element::GetRelativeAbundanceVector () const inline
Definition at line 166 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 166 of file G4Element.hh
References fRelativeAbundanceVector.
Referenced by G4Nucleus::ChooseParameters(), G4VCrossSectionDataSet::ComputeCrossSection(), G4tgbGeometryDumper::DumpElement(), G4GDMLWriteMaterials::ElementWrite(), PHG4GDMLWriteMaterials::ElementWrite(), G4ParticleHPJENDLHEData::GetCrossSection(), G4CrossSectionDataStore::GetCrossSection(), G4MuNeutrinoNucleusTotXsc::GetElementCrossSection(), G4ParticleHPElementData::Init(), G4ParticleHPChannel::Register(), G4CrossSectionDataStore::SampleZandA(), G4NeutronElasticXS::SelectIsotope(), G4NeutronInelasticXS::SelectIsotope(), G4ParticleInelasticXS::SelectIsotope(), G4NeutronCaptureXS::SelectIsotope(), G4VCrossSectionDataSet::SelectIsotope(), G4VEmModel::SelectIsotopeNumber(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), G4ElementSelector::SelectZandA(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
const G4String& G4Element::GetSymbol () const inline
Definition at line 127 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 127 of file G4Element.hh
References fSymbol.
Referenced by G4tgbGeometryDumper::DumpElement(), and export_G4Element().
G4double G4Element::GetZ () const inline
Definition at line 130 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 130 of file G4Element.hh
References fZeff.
Referenced by G4RDVCrossSectionHandler::ActiveElements(), G4VCrossSectionHandler::ActiveElements(), G4PixeCrossSectionHandler::ActiveElements(), G4AdjointPhotoElectricModel::AdjointCrossSectionPerAtom(), G4ParticleHPThermalScattering::ApplyYourself(), G4RDAugerData::BuildAugerTransitionTable(), G4AugerData::BuildAugerTransitionTable(), G4AdjointCSManager::BuildCrossSectionMatrices(), G4ScreenedCoulombCrossSection::BuildMFPTables(), G4ParticleHPJENDLHEData::BuildPhysicsTable(), G4ErrorFreeTrajState::CalculateEffectiveZandA(), G4Nucleus::ChooseParameters(), G4AdjointCSManager::ComputeAdjointCS(), G4EmCalculator::ComputeCrossSectionPerAtom(), G4VEmModel::ComputeCrossSectionPerAtom(), G4ICRU49NuclearStoppingModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeIonParameters(), G4PAIySection::ComputeLowEnergyCof(), G4PAIxSection::ComputeLowEnergyCof(), G4IonisParamMat::ComputeMeanParameters(), G4HadronHElasticPhysics::ConstructProcess(), MuCrossSections::CR_PerAtom(), G4LENDModel::create_used_target_map(), G4LENDCrossSection::create_used_target_map(), G4ICRU73QOModel::DEDX(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), G4tgbGeometryDumper::DumpElement(), G4GDMLWriteMaterials::ElementWrite(), PHG4GDMLWriteMaterials::ElementWrite(), export_G4Element(), G4ParticleHPJENDLHEData::GetCrossSection(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), GVFlashShowerParameterisation::GetEffZ(), G4ChargeExchangeProcess::GetElementCrossSection(), G4QAOLowEnergyLoss::GetOscillatorEnergy(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4ParticleHPElementData::Init(), G4GSPWACorrections::InitDataMaterial(), G4GSPWACorrections::InitDataPerElement(), G4EmSaturation::InitialiseBirksCoefficient(), G4eBremsstrahlungRelModel::InitialiseElementData(), G4GSMottCorrection::InitMCDataMaterial(), G4GSMottCorrection::InitMCDataPerElement(), G4hIonEffChargeSquare::IonEffChargeSquare(), G4RDBremsstrahlungParameters::LoadData(), G4eIonisationParameters::LoadData(), G4RDeIonisationParameters::LoadData(), G4BremsstrahlungParameters::LoadData(), G4NativeScreenedCoulombCrossSection::LoadData(), G4LindhardRobinsonPartition::PartitionNIEL(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4ParticleHPChannel::Register(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4XrayRayleighModel::SampleSecondaries(), G4LivermoreRayleighModel::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), HistoManager::ScoreNewTrack(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), G4ElementSelector::SelectZandA(), G4hParametrisedLossModel::StoppingPower(), and G4hNuclearStoppingModel::StoppingPower().
G4int G4Element::GetZasInt () const inline
Definition at line 131 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 131 of file G4Element.hh
References fZ.
Referenced by G4SBBremTable::BuildSamplingTables(), G4EmCalculator::CheckMaterial(), G4VCrossSectionDataSet::ComputeCrossSection(), G4EmCalculator::ComputeCrossSectionPerShell(), G4IonisParamMat::ComputeDensityEffectOnFly(), G4ICRU73QOModel::DEDX(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4CrossSectionDataStore::GetCrossSection(), G4GammaConversionToMuons::GetCrossSectionPerAtom(), G4VComponentCrossSection::GetElasticElementCrossSection(), G4HadronicProcess::GetElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXsc(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscNS(), G4ComponentGGHadronNucleusXsc::GetHadronNucleonXscPDG(), G4ComponentGGHadronNucleusXsc::GetHNinelasticXsc(), G4VComponentCrossSection::GetInelasticElementCrossSection(), G4VComponentCrossSection::GetTotalElementCrossSection(), G4BetheHeitlerModel::InitialiseElementData(), G4PairProductionRelModel::InitialiseElementData(), G4VEmModel::InitialiseForMaterial(), G4GSPWACorrections::LoadDataElement(), G4GSMottCorrection::LoadMCDataElement(), G4GammaConversionToMuons::PostStepDoIt(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4BetheHeitlerModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PairProductionRelModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4CrossSectionDataStore::SampleZandA(), G4NeutronElasticXS::SelectIsotope(), G4NeutronInelasticXS::SelectIsotope(), G4ParticleInelasticXS::SelectIsotope(), G4NeutronCaptureXS::SelectIsotope(), and G4VEmModel::SelectRandomAtomNumber().
void G4Element::InitializePointers () private
Definition at line 218 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 218 of file G4Element.cc
References fAeff, fAtomicShells, fCoulomb, fIndexInTable, fIonisation, fNaturalAbundance, fNbOfAtomicShells, fNbOfShellElectrons, fNeff, fNumberOfIsotopes, fRadTsai, fRelativeAbundanceVector, fZ, fZeff, and theIsotopeVector.
Referenced by G4Element().
G4bool G4Element::operator!= (const G4Element &) const private delete
const G4Element& G4Element::operator= (const G4Element &) private delete
G4bool G4Element::operator== (const G4Element &) const private delete
void G4Element::SetName (const G4String & name) inline
Definition at line 213 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 213 of file G4Element.hh
References fName.
Referenced by export_G4Element(), and G4GDMLRead::StripNames().
void G4Element::SetNaturalAbundanceFlag (G4bool val) inline
Definition at line 266 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 266 of file G4Element.hh
References fNaturalAbundance.
Referenced by G4NistElementBuilder::BuildElement().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & flux, const G4Element * element) friend
Definition at line 431 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 431 of file G4Element.cc
std::ostream& operator<< (std::ostream & flux, const G4Element & element) friend
Definition at line 458 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 458 of file G4Element.cc
std::ostream& operator<< (std::ostream & flux, G4ElementTable ElementTable) friend
Definition at line 466 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 466 of file G4Element.cc
Member Data Documentation
G4double G4Element::fAeff private
Definition at line 235 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 235 of file G4Element.hh
Referenced by AddIsotope(), G4Element(), GetA(), InitializePointers(), and operator<<().
G4double* G4Element::fAtomicShells private
Definition at line 239 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 239 of file G4Element.hh
Referenced by AddIsotope(), G4Element(), GetAtomicShell(), InitializePointers(), and ~G4Element().
G4double G4Element::fCoulomb private
Definition at line 256 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 256 of file G4Element.hh
Referenced by ComputeCoulombFactor(), ComputeLradTsaiFactor(), GetfCoulomb(), and InitializePointers().
size_t G4Element::fIndexInTable private
Definition at line 250 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 250 of file G4Element.hh
Referenced by ComputeDerivedQuantities(), GetIndex(), InitializePointers(), and ~G4Element().
G4IonisParamElm* G4Element::fIonisation private
Definition at line 258 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 258 of file G4Element.hh
Referenced by ComputeDerivedQuantities(), GetIonisation(), InitializePointers(), and ~G4Element().
G4String G4Element::fName private
Definition at line 231 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 231 of file G4Element.hh
Referenced by AddIsotope(), AddNaturalIsotopes(), GetAtomicShell(), GetName(), GetNbOfShellElectrons(), operator<<(), and SetName().
G4bool G4Element::fNaturalAbundance private
Definition at line 251 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 251 of file G4Element.hh
Referenced by AddNaturalIsotopes(), GetNaturalAbundanceFlag(), InitializePointers(), and SetNaturalAbundanceFlag().
G4int G4Element::fNbOfAtomicShells private
Definition at line 238 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 238 of file G4Element.hh
Referenced by AddIsotope(), G4Element(), GetAtomicShell(), GetNbOfAtomicShells(), GetNbOfShellElectrons(), and InitializePointers().
G4int* G4Element::fNbOfShellElectrons private
Definition at line 240 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 240 of file G4Element.hh
Referenced by AddIsotope(), G4Element(), GetNbOfShellElectrons(), InitializePointers(), and ~G4Element().
G4double G4Element::fNeff private
Definition at line 234 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Element.hh
Referenced by AddIsotope(), G4Element(), GetAtomicMassAmu(), GetN(), InitializePointers(), and operator<<().
G4int G4Element::fNumberOfIsotopes private
Definition at line 243 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 243 of file G4Element.hh
Referenced by AddIsotope(), AddNaturalIsotopes(), GetNumberOfIsotopes(), InitializePointers(), and operator<<().
G4double G4Element::fRadTsai private
Definition at line 257 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 257 of file G4Element.hh
Referenced by ComputeLradTsaiFactor(), GetfRadTsai(), and InitializePointers().
G4double* G4Element::fRelativeAbundanceVector private
Definition at line 245 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 245 of file G4Element.hh
Referenced by AddIsotope(), AddNaturalIsotopes(), G4Element(), GetRelativeAbundanceVector(), InitializePointers(), operator<<(), and ~G4Element().
G4String G4Element::fSymbol private
Definition at line 232 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 232 of file G4Element.hh
Referenced by AddNaturalIsotopes(), GetSymbol(), and operator<<().
G4int G4Element::fZ private
Definition at line 236 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 236 of file G4Element.hh
Referenced by ComputeDerivedQuantities(), GetZasInt(), and InitializePointers().
G4double G4Element::fZeff private
Definition at line 233 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 233 of file G4Element.hh
Referenced by AddIsotope(), AddNaturalIsotopes(), ComputeCoulombFactor(), ComputeDerivedQuantities(), ComputeLradTsaiFactor(), G4Element(), GetAtomicShell(), GetNbOfShellElectrons(), GetZ(), InitializePointers(), and operator<<().
G4ElementTable G4Element::theElementTable static private
Definition at line 249 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 249 of file G4Element.hh
Referenced by ComputeDerivedQuantities(), GetElement(), GetElementTable(), GetNumberOfElements(), and ~G4Element().
G4IsotopeVector* G4Element::theIsotopeVector private
Definition at line 244 of file G4Element.hh.
View newest version in sPHENIX GitHub at line 244 of file G4Element.hh
Referenced by AddIsotope(), AddNaturalIsotopes(), G4Element(), GetIsotope(), GetIsotopeVector(), InitializePointers(), operator<<(), and ~G4Element().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4Element.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4Element.cc