ECCE @ EIC Software: G4ChargeExchangeProcess Class Reference
G4ChargeExchangeProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4ChargeExchangeProcess.hh>
Public Member Functions
G4ChargeExchangeProcess (const G4String &procName="chargeExchange")
virtual ~G4ChargeExchangeProcess ()
virtual G4bool IsApplicable (const G4ParticleDefinition &aParticleType)
virtual void BuildPhysicsTable (const G4ParticleDefinition &aParticleType)
virtual void DumpPhysicsTable (const G4ParticleDefinition &aParticleType)
virtual G4double GetElementCrossSection (const G4DynamicParticle *aParticle, const G4Element *anElement, const G4Material *mat=0)
Public Member Functions inherited from G4HadronicProcess
G4HadronicProcess (const G4String &processName="Hadronic", G4ProcessType procType=fHadronic)
G4HadronicProcess (const G4String &processName, G4HadronicProcessType subType)
~G4HadronicProcess () override
void RegisterMe (G4HadronicInteraction *a)
G4double GetElementCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
G4double GetMicroscopicCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
void PreparePhysicsTable (const G4ParticleDefinition &) override
void DumpPhysicsTable (const G4ParticleDefinition &p)
void AddDataSet (G4VCrossSectionDataSet *aDataSet)
std::vector
< G4HadronicInteraction * > & GetHadronicInteractionList ()
G4HadronicInteraction * GetHadronicModel (const G4String &)
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *) override
const G4Nucleus * GetTargetNucleus () const
const G4Isotope * GetTargetIsotope ()
void ProcessDescription (std::ostream &outFile) const override
void BiasCrossSectionByFactor (G4double aScale)
void MultiplyCrossSectionBy (G4double factor)
G4double CrossSectionFactor () const
void SetIntegral (G4bool val)
void SetEpReportLevel (G4int level)
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
std::pair< G4double, G4double > GetEnergyMomentumCheckLevels () const
G4CrossSectionDataStore * GetCrossSectionDataStore ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Attributes
const G4ParticleDefinition * theParticle
const G4ParticleDefinition * theProton
const G4ParticleDefinition * theNeutron
const G4ParticleDefinition * theAProton
const G4ParticleDefinition * theANeutron
const G4ParticleDefinition * thePiPlus
const G4ParticleDefinition * thePiMinus
const G4ParticleDefinition * thePiZero
const G4ParticleDefinition * theKPlus
const G4ParticleDefinition * theKMinus
const G4ParticleDefinition * theK0S
const G4ParticleDefinition * theK0L
const G4ParticleDefinition * theL
const G4ParticleDefinition * theAntiL
const G4ParticleDefinition * theSPlus
const G4ParticleDefinition * theASPlus
const G4ParticleDefinition * theSMinus
const G4ParticleDefinition * theASMinus
const G4ParticleDefinition * theS0
const G4ParticleDefinition * theAS0
const G4ParticleDefinition * theXiMinus
const G4ParticleDefinition * theXi0
const G4ParticleDefinition * theAXiMinus
const G4ParticleDefinition * theAXi0
const G4ParticleDefinition * theOmega
const G4ParticleDefinition * theAOmega
const G4ParticleDefinition * theD
const G4ParticleDefinition * theT
const G4ParticleDefinition * theA
const G4ParticleDefinition * theHe3
G4CrossSectionDataStore * store
G4PhysicsLinearVector * factors
G4double thEnergy
G4int pPDG
G4bool first
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4HadronicProcess
G4HadronicInteraction * ChooseHadronicInteraction (const G4HadProjectile &aHadProjectile, G4Nucleus &aTargetNucleus, const G4Material *aMaterial, const G4Element *anElement)
G4Nucleus * GetTargetNucleusPointer ()
void DumpState (const G4Track &, const G4String &, G4ExceptionDescription &)
G4HadronicInteraction * GetHadronicInteraction () const
G4double GetLastCrossSection ()
void FillResult (G4HadFinalState *aR, const G4Track &aT)
G4HadFinalState * CheckResult (const G4HadProjectile &thePro, const G4Nucleus &targetNucleus, G4HadFinalState *result)
void CheckEnergyMomentumConservation (const G4Track &, const G4Nucleus &)
Protected Attributes inherited from G4HadronicProcess
G4HadProjectile thePro
G4ParticleChange * theTotalResult
G4double fWeight
G4int epReportLevel
Detailed Description
Definition at line 52 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ChargeExchangeProcess.hh
Constructor & Destructor Documentation
G4ChargeExchangeProcess::G4ChargeExchangeProcess (const G4String & procName = "chargeExchange")
Definition at line 57 of file G4ChargeExchangeProcess.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ChargeExchangeProcess.cc
References G4HadronicProcess::AddDataSet(), G4Alpha::Alpha(), G4AntiLambda::AntiLambda(), G4AntiNeutron::AntiNeutron(), G4AntiOmegaMinus::AntiOmegaMinus(), G4AntiProton::AntiProton(), G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiSigmaZero::AntiSigmaZero(), G4AntiXiMinus::AntiXiMinus(), G4AntiXiZero::AntiXiZero(), G4Deuteron::Deuteron(), G4He3::He3(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), G4Lambda::Lambda(), MeV, G4Neutron::Neutron(), G4OmegaMinus::OmegaMinus(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), pPDG, G4Proton::Proton(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), theA, theANeutron, theAntiL, theAOmega, theAProton, theAS0, theASMinus, theASPlus, theAXi0, theAXiMinus, theD, theHe3, theK0L, theK0S, theKMinus, theKPlus, theL, thEnergy, theNeutron, theOmega, thePiMinus, thePiPlus, thePiZero, theProton, theS0, theSMinus, theSPlus, theT, theXi0, theXiMinus, G4Triton::Triton(), G4VProcess::verboseLevel, G4XiMinus::XiMinus(), and G4XiZero::XiZero().
G4ChargeExchangeProcess::~G4ChargeExchangeProcess () virtual
Definition at line 95 of file G4ChargeExchangeProcess.cc.
View newest version in sPHENIX GitHub at line 95 of file G4ChargeExchangeProcess.cc
References factors.
Member Function Documentation
void G4ChargeExchangeProcess::BuildPhysicsTable (const G4ParticleDefinition & aParticleType) virtual
Reimplemented from G4HadronicProcess.
Definition at line 101 of file G4ChargeExchangeProcess.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ChargeExchangeProcess.cc
References G4HadronicProcess::BuildPhysicsTable(), F, factors, first, G4cout, G4endl, G4HadronicProcess::GetCrossSectionDataStore(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), GeV, n, pPDG, G4PhysicsVector::PutValue(), store, theK0L, theK0S, theKMinus, theKPlus, theParticle, thePiMinus, thePiPlus, and G4VProcess::verboseLevel.
void G4ChargeExchangeProcess::DumpPhysicsTable (const G4ParticleDefinition & aParticleType) virtual
Definition at line 195 of file G4ChargeExchangeProcess.cc.
View newest version in sPHENIX GitHub at line 195 of file G4ChargeExchangeProcess.cc
References G4CrossSectionDataStore::DumpPhysicsTable(), and store.
G4double G4ChargeExchangeProcess::GetElementCrossSection (const G4DynamicParticle * aParticle, const G4Element * anElement, const G4Material * mat = 0) virtual
Definition at line 135 of file G4ChargeExchangeProcess.cc.
View newest version in sPHENIX GitHub at line 135 of file G4ChargeExchangeProcess.cc
References A(), b, factors, G4cout, G4endl, G4CrossSectionDataStore::GetCrossSection(), G4Pow::GetInstance(), G4DynamicParticle::GetKineticEnergy(), G4Element::GetN(), G4Element::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalMomentum(), G4PhysicsVector::GetValue(), G4Element::GetZ(), GeV, millibarn, G4Pow::powA(), store, theANeutron, theAProton, theKMinus, theKPlus, thEnergy, theNeutron, theParticle, thePiMinus, thePiPlus, theProton, G4VProcess::verboseLevel, x, and Z.
G4bool G4ChargeExchangeProcess::IsApplicable (const G4ParticleDefinition & aParticleType) virtual
Reimplemented from G4VProcess.
Definition at line 183 of file G4ChargeExchangeProcess.cc.
View newest version in sPHENIX GitHub at line 183 of file G4ChargeExchangeProcess.cc
References theANeutron, theAProton, theK0L, theK0S, theKMinus, theKPlus, theL, theNeutron, thePiMinus, thePiPlus, and theProton.
Member Data Documentation
G4PhysicsLinearVector* G4ChargeExchangeProcess::factors private
Definition at line 105 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), GetElementCrossSection(), and ~G4ChargeExchangeProcess().
G4bool G4ChargeExchangeProcess::first private
Definition at line 110 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable().
G4int G4ChargeExchangeProcess::pPDG private
Definition at line 109 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), and G4ChargeExchangeProcess().
G4CrossSectionDataStore* G4ChargeExchangeProcess::store private
Definition at line 104 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), DumpPhysicsTable(), and GetElementCrossSection().
const G4ParticleDefinition* G4ChargeExchangeProcess::theA private
Definition at line 101 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theANeutron private
Definition at line 77 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess(), GetElementCrossSection(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::theAntiL private
Definition at line 86 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theAOmega private
Definition at line 98 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theAProton private
Definition at line 76 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess(), GetElementCrossSection(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::theAS0 private
Definition at line 92 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theASMinus private
Definition at line 90 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theASPlus private
Definition at line 88 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theAXi0 private
Definition at line 96 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theAXiMinus private
Definition at line 95 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theD private
Definition at line 99 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theHe3 private
Definition at line 102 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theK0L private
Definition at line 84 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), G4ChargeExchangeProcess(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::theK0S private
Definition at line 83 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), G4ChargeExchangeProcess(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::theKMinus private
Definition at line 82 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), G4ChargeExchangeProcess(), GetElementCrossSection(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::theKPlus private
Definition at line 81 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), G4ChargeExchangeProcess(), GetElementCrossSection(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::theL private
Definition at line 85 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess(), and IsApplicable().
G4double G4ChargeExchangeProcess::thEnergy private
Definition at line 107 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess(), and GetElementCrossSection().
const G4ParticleDefinition* G4ChargeExchangeProcess::theNeutron private
Definition at line 75 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess(), GetElementCrossSection(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::theOmega private
Definition at line 97 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theParticle private
Definition at line 72 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
const G4ParticleDefinition* G4ChargeExchangeProcess::thePiMinus private
Definition at line 79 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), G4ChargeExchangeProcess(), GetElementCrossSection(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::thePiPlus private
Definition at line 78 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ChargeExchangeProcess.hh
Referenced by BuildPhysicsTable(), G4ChargeExchangeProcess(), GetElementCrossSection(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::thePiZero private
Definition at line 80 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theProton private
Definition at line 74 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess(), GetElementCrossSection(), and IsApplicable().
const G4ParticleDefinition* G4ChargeExchangeProcess::theS0 private
Definition at line 91 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theSMinus private
Definition at line 89 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theSPlus private
Definition at line 87 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theT private
Definition at line 100 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theXi0 private
Definition at line 94 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
const G4ParticleDefinition* G4ChargeExchangeProcess::theXiMinus private
Definition at line 93 of file G4ChargeExchangeProcess.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ChargeExchangeProcess.hh
Referenced by G4ChargeExchangeProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4ChargeExchangeProcess.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4ChargeExchangeProcess.cc