ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcException.hh File Reference
CexmcException.hh File Reference
#include <stdexcept>
#include <G4Types.hh>
Classes
class CexmcException
Enumerations
enum CexmcExceptionType {
CexmcUnknownException, CexmcSystemException, CexmcEventActionIsNotInitialized, CexmcCmdLineParseException,
CexmcPreinitException, CexmcFileCompressException, CexmcReadProjectIncomplete, CexmcProjectExists,
CexmcCmdIsNotAllowed, CexmcBadAngularRange, CexmcBadThreshold, CexmcBadCalorimeterTriggerAlgorithm,
CexmcBadOCVetoAlgorithm, CexmcBadOCVetoFraction, CexmcCalorimeterRegionNotInitialized, CexmcCalorimeterGeometryDataNotInitialized,
CexmcMultipleDetectorRoles, CexmcKinematicsException, CexmcPoorEventData, CexmcIncompatibleGeometry,
CexmcIncompleteProductionModel, CexmcIncompatibleProductionModel, CexmcBeamAndIncidentParticlesMismatch, CexmcInvalidAngularRange,
CexmcWeirdException
}
Functions
void ThrowExceptionIfProjectIsRead (CexmcExceptionType type, G4bool extraCond=true)
Enumeration Type Documentation
enum CexmcExceptionType
Enumerator:
CexmcUnknownException
CexmcSystemException
CexmcEventActionIsNotInitialized
CexmcCmdLineParseException
CexmcPreinitException
CexmcFileCompressException
CexmcReadProjectIncomplete
CexmcProjectExists
CexmcCmdIsNotAllowed
CexmcBadAngularRange
CexmcBadThreshold
CexmcBadCalorimeterTriggerAlgorithm
CexmcBadOCVetoAlgorithm
CexmcBadOCVetoFraction
CexmcCalorimeterRegionNotInitialized
CexmcCalorimeterGeometryDataNotInitialized
CexmcMultipleDetectorRoles
CexmcKinematicsException
CexmcPoorEventData
CexmcIncompatibleGeometry
CexmcIncompleteProductionModel
CexmcIncompatibleProductionModel
CexmcBeamAndIncidentParticlesMismatch
CexmcInvalidAngularRange
CexmcWeirdException
Definition at line 51 of file CexmcException.hh.
View newest version in sPHENIX GitHub at line 51 of file CexmcException.hh
Function Documentation
void ThrowExceptionIfProjectIsRead (CexmcExceptionType type, G4bool extraCond = true)
Definition at line 179 of file CexmcException.cc.
View newest version in sPHENIX GitHub at line 179 of file CexmcException.cc
References G4RunManager::GetRunManager(), and CexmcRunManager::ProjectIsRead().
Referenced by CexmcEnergyDepositDigitizer::AddCrystalResolutionRange(), CexmcProductionModel::ApplyFermiMotion(), CexmcEnergyDepositDigitizer::ApplyFiniteCrystalResolution(), CexmcEnergyDepositDigitizer::ClearCrystalResolutionData(), CexmcParticleGun::SetBeamParticle(), CexmcEnergyDepositDigitizer::SetCalorimeterLeftThreshold(), CexmcEnergyDepositDigitizer::SetCalorimeterRightThreshold(), CexmcEnergyDepositDigitizer::SetCalorimetersThreshold(), CexmcEnergyDepositDigitizer::SetCalorimeterTriggerAlgorithm(), CexmcPrimaryGeneratorAction::SetFwhmDirX(), CexmcPrimaryGeneratorAction::SetFwhmDirY(), CexmcPrimaryGeneratorAction::SetFwhmMomentumAmp(), CexmcPrimaryGeneratorAction::SetFwhmPosX(), CexmcPrimaryGeneratorAction::SetFwhmPosY(), CexmcEnergyDepositDigitizer::SetMonitorThreshold(), CexmcParticleGun::SetOrigDirection(), CexmcParticleGun::SetOrigMomentumAmp(), CexmcParticleGun::SetOrigPosition(), CexmcEnergyDepositDigitizer::SetOuterCrystalsVetoAlgorithm(), CexmcEnergyDepositDigitizer::SetOuterCrystalsVetoFraction(), CexmcEnergyDepositDigitizer::SetVetoCounterLeftThreshold(), CexmcEnergyDepositDigitizer::SetVetoCounterRightThreshold(), and CexmcEnergyDepositDigitizer::SetVetoCountersThreshold().