ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/nf_specialFunctions.h File Reference
nf_specialFunctions.h File Reference
#include <math.h>
#include <float.h>
#include <nf_utilities.h>
Functions
double nf_polevl (double x, double coef[], int N)
double nf_p1evl (double x, double coef[], int N)
double nf_exponentialIntegral (int n, double x, nfu_status *status)
double nf_gammaFunction (double x, nfu_status *status)
double nf_logGammaFunction (double x, nfu_status *status)
double nf_incompleteGammaFunction (double a, double x, nfu_status *status)
double nf_incompleteGammaFunctionComplementary (double a, double x, nfu_status *status)
double nf_amc_log_factorial (int)
double nf_amc_factorial (int)
double nf_amc_wigner_3j (int, int, int, int, int, int)
double nf_amc_wigner_6j (int, int, int, int, int, int)
double nf_amc_wigner_9j (int, int, int, int, int, int, int, int, int)
double nf_amc_racah (int, int, int, int, int, int)
double nf_amc_clebsh_gordan (int, int, int, int, int)
double nf_amc_z_coefficient (int, int, int, int, int, int)
double nf_amc_zbar_coefficient (int, int, int, int, int, int)
double nf_amc_reduced_matrix_element (int, int, int, int, int, int, int)
Function Documentation
double nf_amc_clebsh_gordan (int , int , int , int , int)
Definition at line 288 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 288 of file nf_angularMomentumCoupling.cc
References kdfinder::abs(), cg1(), cg2(), cg3(), m2, m3, MAX_FACTORIAL, x1, x2, x3, y1, y2, and y3.
Referenced by nf_amc_reduced_matrix_element(), nf_amc_wigner_3j(), nf_amc_z_coefficient(), and nf_amc_zbar_coefficient().
double nf_amc_factorial (int)
Definition at line 96 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 96 of file nf_angularMomentumCoupling.cc
References G4Exp(), and nf_amc_log_factorial().
double nf_amc_log_factorial (int)
Definition at line 85 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 85 of file nf_angularMomentumCoupling.cc
References MAX_FACTORIAL, n, and nf_amc_log_fact.
Referenced by nf_amc_factorial().
double nf_amc_racah (int , int , int , int , int , int)
Definition at line 253 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 253 of file nf_angularMomentumCoupling.cc
References nf_amc_wigner_6j().
Referenced by nf_amc_wigner_9j(), nf_amc_z_coefficient(), and nf_amc_zbar_coefficient().
double nf_amc_reduced_matrix_element (int , int , int , int , int , int , int)
Definition at line 473 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 473 of file nf_angularMomentumCoupling.cc
References kdfinder::abs(), M_PI, nf_amc_clebsh_gordan(), parity(), x1, x2, and x3.
double nf_amc_wigner_3j (int , int , int , int , int , int)
Definition at line 105 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 105 of file nf_angularMomentumCoupling.cc
References nf_amc_clebsh_gordan().
double nf_amc_wigner_6j (int , int , int , int , int , int)
Definition at line 121 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 121 of file nf_angularMomentumCoupling.cc
References w6j0(), w6j1(), and x.
Referenced by nf_amc_racah().
double nf_amc_wigner_9j (int , int , int , int , int , int , int , int , int)
Definition at line 226 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 226 of file nf_angularMomentumCoupling.cc
References kdfinder::abs(), max3(), min3(), and nf_amc_racah().
double nf_amc_z_coefficient (int , int , int , int , int , int)
Definition at line 437 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 437 of file nf_angularMomentumCoupling.cc
References nf_amc_clebsh_gordan(), nf_amc_racah(), and z.
double nf_amc_zbar_coefficient (int , int , int , int , int , int)
Definition at line 453 of file nf_angularMomentumCoupling.cc.
View newest version in sPHENIX GitHub at line 453 of file nf_angularMomentumCoupling.cc
References nf_amc_clebsh_gordan(), and nf_amc_racah().
double nf_exponentialIntegral (int n, double x, nfu_status * status)
Definition at line 28 of file nf_exponentialIntegral.cc.
View newest version in sPHENIX GitHub at line 28 of file nf_exponentialIntegral.cc
References a, b, c, d, EPS, EULER, FPMIN, G4Exp(), G4Log(), Acts::UnitConstants::h, isfinite, MAXIT, n, nfu_badInput, nfu_failedToConverge, nfu_Okay, and x.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM_callback_g().
double nf_gammaFunction (double x, nfu_status * status)
Definition at line 126 of file nf_gammaFunctions.cc.
View newest version in sPHENIX GitHub at line 126 of file nf_gammaFunctions.cc
References DBL_MAX, E, e, int(), isfinite, M_PI, nf_polevl(), nfu_badInput, nfu_Okay, P, Q, stirf(), x, and z.
Referenced by nf_incompleteGammaFunction(), and nf_incompleteGammaFunctionComplementary().
double nf_incompleteGammaFunction (double a, double x, nfu_status * status)
Definition at line 155 of file nf_incompleteGammaFunctions.cc.
View newest version in sPHENIX GitHub at line 155 of file nf_incompleteGammaFunctions.cc
References a, KF_timing::ax, c, DBL_EPSILON, G4Exp(), G4Log(), isfinite, nf_gammaFunction(), nf_incompleteGammaFunctionComplementary(), nfu_badInput, nfu_Okay, and r.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM_callback_g(), and nf_incompleteGammaFunctionComplementary().
double nf_incompleteGammaFunctionComplementary (double a, double x, nfu_status * status)
Definition at line 88 of file nf_incompleteGammaFunctions.cc.
View newest version in sPHENIX GitHub at line 88 of file nf_incompleteGammaFunctions.cc
References a, KF_timing::ax, big, biginv, c, DBL_EPSILON, G4Exp(), G4Log(), isfinite, nf_gammaFunction(), nf_incompleteGammaFunction(), nfu_badInput, nfu_Okay, r, t, x, y, and z.
Referenced by MCGIDI_energy_parseMadlandNixFromTOM_callback_g(), and nf_incompleteGammaFunction().
double nf_logGammaFunction (double x, nfu_status * status)
Definition at line 206 of file nf_gammaFunctions.cc.
View newest version in sPHENIX GitHub at line 206 of file nf_gammaFunctions.cc
References isfinite, lgam(), nfu_badInput, and nfu_Okay.
double nf_p1evl (double x, double coef[], int N)
Definition at line 67 of file nf_polevl.cc.
View newest version in sPHENIX GitHub at line 67 of file nf_polevl.cc
Referenced by lgam().
double nf_polevl (double x, double coef[], int N)
Definition at line 46 of file nf_polevl.cc.
View newest version in sPHENIX GitHub at line 46 of file nf_polevl.cc
References N.
Referenced by lgam(), nf_gammaFunction(), and stirf().