ECCE @ EIC Software: CCalHit Class Reference
CCalHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalHit.hh>
Public Member Functions
CCalHit ()
~CCalHit ()
CCalHit (const CCalHit &right)
const CCalHit & operator= (const CCalHit &right)
G4bool operator== (const CCalHit &)
void print ()
CLHEP::Hep3Vector getEntry () const
void setEntry (CLHEP::Hep3Vector xyz)
G4double getIncidentEnergy () const
void setIncidentEnergy (G4double e)
G4int getTrackID () const
void setTrackID (G4int i)
unsigned int getUnitID () const
void setUnitID (unsigned int i)
G4double getTimeSlice () const
void setTimeSlice (G4double d)
G4int getTimeSliceID () const
G4double getEnergyDeposit () const
void setEnergyDeposit (const G4double e)
void addEnergyDeposit (const CCalHit &aHit)
void addEnergyDeposit (const G4double e)
Private Attributes
CLHEP::Hep3Vector entry
G4double theIncidentEnergy
G4int theTrackID
unsigned int theUnitID
G4double theTimeSlice
G4double theEnergyDeposit
Friends
std::ostream & operator<< (std::ostream &, const CCalHit &)
Detailed Description
Definition at line 52 of file CCalHit.hh.
View newest version in sPHENIX GitHub at line 52 of file CCalHit.hh
Constructor & Destructor Documentation
CCalHit::CCalHit ()
Definition at line 35 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 35 of file CCalHit.cc
CCalHit::~CCalHit ()
Definition at line 41 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 41 of file CCalHit.cc
CCalHit::CCalHit (const CCalHit & right)
Definition at line 44 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 44 of file CCalHit.cc
Member Function Documentation
void CCalHit::addEnergyDeposit (const CCalHit & aHit)
Definition at line 90 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 90 of file CCalHit.cc
References getEnergyDeposit().
Referenced by CCalG4Hit::addEnergyDeposit().
void CCalHit::addEnergyDeposit (const G4double e)
Definition at line 94 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 94 of file CCalHit.cc
References e, and theEnergyDeposit.
G4double CCalHit::getEnergyDeposit () const
Definition at line 86 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 86 of file CCalHit.cc
References theEnergyDeposit.
Referenced by addEnergyDeposit(), CCalEventAction::EndOfEventAction(), and operator<<().
CLHEP::Hep3Vector CCalHit::getEntry () const
Definition at line 65 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 65 of file CCalHit.cc
References entry.
Referenced by operator<<().
G4double CCalHit::getIncidentEnergy () const
Definition at line 68 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 68 of file CCalHit.cc
References theIncidentEnergy.
Referenced by operator<<().
G4double CCalHit::getTimeSlice () const
Definition at line 77 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 77 of file CCalHit.cc
References theTimeSlice.
Referenced by CCalEventAction::EndOfEventAction().
G4int CCalHit::getTimeSliceID () const
Definition at line 79 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 79 of file CCalHit.cc
References theTimeSlice.
Referenced by CCaloSD::hitExists(), and operator<<().
G4int CCalHit::getTrackID () const
Definition at line 71 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 71 of file CCalHit.cc
References theTrackID.
Referenced by CCaloSD::hitExists(), and operator<<().
unsigned int CCalHit::getUnitID () const
Definition at line 74 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 74 of file CCalHit.cc
References theUnitID.
Referenced by CCalEventAction::EndOfEventAction(), CCaloSD::hitExists(), and operator<<().
const CCalHit & CCalHit::operator= (const CCalHit & right)
Definition at line 54 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 54 of file CCalHit.cc
References entry, theEnergyDeposit, theIncidentEnergy, theTimeSlice, theTrackID, and theUnitID.
Referenced by CCalG4Hit::operator=().
G4bool CCalHit::operator== (const CCalHit &) inline
Definition at line 62 of file CCalHit.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalHit.hh
void CCalHit::print ()
Definition at line 99 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 99 of file CCalHit.cc
References G4cout.
void CCalHit::setEnergyDeposit (const G4double e)
Definition at line 82 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 82 of file CCalHit.cc
References e, and theEnergyDeposit.
void CCalHit::setEntry (CLHEP::Hep3Vector xyz)
Definition at line 66 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 66 of file CCalHit.cc
References entry.
Referenced by CCaloSD::createNewHit().
void CCalHit::setIncidentEnergy (G4double e)
Definition at line 69 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 69 of file CCalHit.cc
References e, and theIncidentEnergy.
Referenced by CCaloSD::createNewHit().
void CCalHit::setTimeSlice (G4double d)
Definition at line 78 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 78 of file CCalHit.cc
References d, and theTimeSlice.
Referenced by CCaloSD::createNewHit().
void CCalHit::setTrackID (G4int i)
Definition at line 72 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 72 of file CCalHit.cc
References theTrackID.
Referenced by CCaloSD::createNewHit().
void CCalHit::setUnitID (unsigned int i)
Definition at line 75 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 75 of file CCalHit.cc
References theUnitID.
Referenced by CCaloSD::createNewHit().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCalHit & hit) friend
Definition at line 104 of file CCalHit.cc.
View newest version in sPHENIX GitHub at line 104 of file CCalHit.cc
Member Data Documentation
CLHEP::Hep3Vector CCalHit::entry private
Definition at line 91 of file CCalHit.hh.
View newest version in sPHENIX GitHub at line 91 of file CCalHit.hh
Referenced by getEntry(), operator=(), and setEntry().
G4double CCalHit::theEnergyDeposit private
Definition at line 96 of file CCalHit.hh.
View newest version in sPHENIX GitHub at line 96 of file CCalHit.hh
Referenced by addEnergyDeposit(), getEnergyDeposit(), operator=(), and setEnergyDeposit().
G4double CCalHit::theIncidentEnergy private
Definition at line 92 of file CCalHit.hh.
View newest version in sPHENIX GitHub at line 92 of file CCalHit.hh
Referenced by getIncidentEnergy(), operator=(), and setIncidentEnergy().
G4double CCalHit::theTimeSlice private
Definition at line 95 of file CCalHit.hh.
View newest version in sPHENIX GitHub at line 95 of file CCalHit.hh
Referenced by getTimeSlice(), getTimeSliceID(), operator=(), and setTimeSlice().
G4int CCalHit::theTrackID private
Definition at line 93 of file CCalHit.hh.
View newest version in sPHENIX GitHub at line 93 of file CCalHit.hh
Referenced by getTrackID(), operator=(), and setTrackID().
unsigned int CCalHit::theUnitID private
Definition at line 94 of file CCalHit.hh.
View newest version in sPHENIX GitHub at line 94 of file CCalHit.hh
Referenced by getUnitID(), operator=(), and setUnitID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalHit.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalHit.cc