ECCE @ EIC Software: B1ConRun Class Reference
B1ConRun Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/include/B1ConRun.hh>
Public Member Functions
B1ConRun ()
virtual ~B1ConRun ()
virtual void Merge (const G4Run *)
virtual void AddEdep (G4double edep)
G4int GetNumberOfEvent () const
G4double GetEdepPerEvent (G4int i) const
Public Member Functions inherited from B1Run
B1Run ()
virtual ~B1Run ()
G4double GetEdep () const
G4double GetEdep2 () const
B1Run ()
virtual ~B1Run ()
void AddEdep (G4double edep)
G4double GetEdep () const
G4double GetEdep2 () const
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
virtual void RecordEvent (const G4Event *)
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
std::vector< G4double > fEdepEventVector
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Run class which extends B1Run
Definition at line 41 of file B1ConRun.hh.
View newest version in sPHENIX GitHub at line 41 of file B1ConRun.hh
Constructor & Destructor Documentation
B1ConRun::B1ConRun ()
Definition at line 34 of file B1ConRun.cc.
View newest version in sPHENIX GitHub at line 34 of file B1ConRun.cc
B1ConRun::~B1ConRun () virtual
Definition at line 41 of file B1ConRun.cc.
View newest version in sPHENIX GitHub at line 41 of file B1ConRun.cc
Member Function Documentation
void B1ConRun::AddEdep (G4double edep) virtual
Reimplemented from B1Run.
Definition at line 59 of file B1ConRun.cc.
View newest version in sPHENIX GitHub at line 59 of file B1ConRun.cc
References B1Run::AddEdep(), and fEdepEventVector.
G4double B1ConRun::GetEdepPerEvent (G4int i) const inline
Definition at line 53 of file B1ConRun.hh.
View newest version in sPHENIX GitHub at line 53 of file B1ConRun.hh
References fEdepEventVector.
Referenced by B1ConRunAction::EndOfRunAction().
G4int B1ConRun::GetNumberOfEvent () const inline
Definition at line 52 of file B1ConRun.hh.
View newest version in sPHENIX GitHub at line 52 of file B1ConRun.hh
References fEdepEventVector.
Referenced by B1ConRunAction::EndOfRunAction().
void B1ConRun::Merge (const G4Run * aRun) virtual
Reimplemented from B1Run.
Definition at line 46 of file B1ConRun.cc.
View newest version in sPHENIX GitHub at line 46 of file B1ConRun.cc
References fEdepEventVector, and B1Run::Merge().
Member Data Documentation
std::vector<G4double> B1ConRun::fEdepEventVector private
Definition at line 56 of file B1ConRun.hh.
View newest version in sPHENIX GitHub at line 56 of file B1ConRun.hh
Referenced by AddEdep(), GetEdepPerEvent(), GetNumberOfEvent(), and Merge().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/include/B1ConRun.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/src/B1ConRun.cc