ECCE @ EIC Software: MarshaledG4HitsCollection Class Reference
MarshaledG4HitsCollection Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/MarshaledG4THitsCollection.h>
Public Member Functions
MarshaledG4HitsCollection (G4HitsCollection *objptr)
MarshaledG4HitsCollection (void *buf, char isUnmarshaling= 'u')
~MarshaledG4HitsCollection ()
G4HitsCollection * unmarshal ()
void unmarshalTo (G4HitsCollection *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4HitsCollection (G4HitsCollection *objptr)
MarshaledG4HitsCollection (void *buf, char chIsUnmarshaling= 'u')
~MarshaledG4HitsCollection ()
G4HitsCollection * unmarshal ()
void unmarshalTo (G4HitsCollection *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4HitsCollection (G4HitsCollection *objptr)
MarshaledG4HitsCollection (void *buf, char isUnmarshaling= 'u')
~MarshaledG4HitsCollection ()
G4HitsCollection * unmarshal ()
void unmarshalTo (G4HitsCollection *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4HitsCollection (G4HitsCollection *objptr)
MarshaledG4HitsCollection (void *buf, char chIsUnmarshaling= 'u')
~MarshaledG4HitsCollection ()
G4HitsCollection * unmarshal ()
void unmarshalTo (G4HitsCollection *obj)
void marshal1 ()
void unmarshal1 ()
Public Member Functions inherited from MarshaledObj
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
Public Attributes
G4HitsCollection * param
ShadowedMarshaledG4HitsCollection * Shadowed_param
Additional Inherited Members
Static Public Member Functions inherited from MarshaledObj
static int ROUND_UP (int x)
static int ROUND_UP (int x)
Protected Attributes inherited from MarshaledObj
int msh_typechoice
char * msh_buffer
char * msh_field_begin
size_t msh_size
char * msh_cursor
size_t msh_extent
bool msh_isUnmarshalDone
Detailed Description
Definition at line 30 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 30 of file MarshaledG4THitsCollection.h
Constructor & Destructor Documentation
MarshaledG4HitsCollection::MarshaledG4HitsCollection (G4HitsCollection * objptr) inline
Definition at line 39 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 39 of file MarshaledG4THitsCollection.h
References marshal1(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledG4HitsCollection::MarshaledG4HitsCollection (void * buf, char isUnmarshaling = 'u') inline
Definition at line 49 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 49 of file MarshaledG4THitsCollection.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledG4HitsCollection::~MarshaledG4HitsCollection () inline
Definition at line 54 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 54 of file MarshaledG4THitsCollection.h
MarshaledG4HitsCollection::MarshaledG4HitsCollection (G4HitsCollection * objptr) inline
Definition at line 37 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 37 of file MarshaledG4THitsCollection.h
References marshal1(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledG4HitsCollection::MarshaledG4HitsCollection (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 47 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 47 of file MarshaledG4THitsCollection.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledG4HitsCollection::~MarshaledG4HitsCollection () inline
Definition at line 52 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 52 of file MarshaledG4THitsCollection.h
MarshaledG4HitsCollection::MarshaledG4HitsCollection (G4HitsCollection * objptr) inline
Definition at line 47 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 47 of file MarshaledG4THitsCollection.h
References marshal1(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledG4HitsCollection::MarshaledG4HitsCollection (void * buf, char isUnmarshaling = 'u') inline
Definition at line 57 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 57 of file MarshaledG4THitsCollection.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledG4HitsCollection::~MarshaledG4HitsCollection () inline
Definition at line 62 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 62 of file MarshaledG4THitsCollection.h
MarshaledG4HitsCollection::MarshaledG4HitsCollection (G4HitsCollection * objptr) inline
Definition at line 43 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 43 of file MarshaledG4THitsCollection.h
References marshal1(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledG4HitsCollection::MarshaledG4HitsCollection (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 53 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 53 of file MarshaledG4THitsCollection.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledG4HitsCollection::~MarshaledG4HitsCollection () inline
Definition at line 58 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 58 of file MarshaledG4THitsCollection.h
Member Function Documentation
void MarshaledG4HitsCollection::marshal1 () inline
Definition at line 89 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 89 of file MarshaledG4THitsCollection.h
References MarshaledObj::EXTEND_BUFFER(), MarshaledObj::getBuffer(), MarshaledObj::getBufferSize(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
void MarshaledG4HitsCollection::marshal1 () inline
Definition at line 91 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 91 of file MarshaledG4THitsCollection.h
References MarshaledObj::EXTEND_BUFFER(), MarshaledObj::getBuffer(), MarshaledObj::getBufferSize(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledG4HitsCollection().
void MarshaledG4HitsCollection::marshal1 () inline
Definition at line 95 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 95 of file MarshaledG4THitsCollection.h
References MarshaledObj::EXTEND_BUFFER(), MarshaledObj::getBuffer(), MarshaledObj::getBufferSize(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
void MarshaledG4HitsCollection::marshal1 () inline
Definition at line 99 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 99 of file MarshaledG4THitsCollection.h
References MarshaledObj::EXTEND_BUFFER(), MarshaledObj::getBuffer(), MarshaledObj::getBufferSize(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
G4HitsCollection* MarshaledG4HitsCollection::unmarshal () inline
Definition at line 58 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 58 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
G4HitsCollection* MarshaledG4HitsCollection::unmarshal () inline
Definition at line 60 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 60 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
G4HitsCollection* MarshaledG4HitsCollection::unmarshal () inline
Definition at line 64 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 64 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
G4HitsCollection* MarshaledG4HitsCollection::unmarshal () inline
Definition at line 68 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 68 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
void MarshaledG4HitsCollection::unmarshal1 () inline
Definition at line 140 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 140 of file MarshaledG4THitsCollection.h
References MarshaledObj::getBufferSize(), int(), MarshaledObj::msh_cursor, param, and MarshaledExN02TrackerHit::unmarshal().
Referenced by unmarshal(), and unmarshalTo().
void MarshaledG4HitsCollection::unmarshal1 () inline
Definition at line 141 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 141 of file MarshaledG4THitsCollection.h
References MarshaledObj::getBufferSize(), int(), MarshaledObj::msh_cursor, param, and MarshaledExN02TrackerHit::unmarshal().
void MarshaledG4HitsCollection::unmarshal1 () inline
Definition at line 194 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 194 of file MarshaledG4THitsCollection.h
References MarshaledObj::getBufferSize(), int(), MarshaledObj::msh_cursor, param, MarshaledExN04MuonHit::unmarshal(), MarshaledExN04TrackerHit::unmarshal(), and MarshaledExN04CalorimeterHit::unmarshal().
void MarshaledG4HitsCollection::unmarshal1 () inline
Definition at line 195 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 195 of file MarshaledG4THitsCollection.h
References MarshaledObj::getBufferSize(), int(), MarshaledObj::msh_cursor, param, MarshaledExN04MuonHit::unmarshal(), MarshaledExN04TrackerHit::unmarshal(), and MarshaledExN04CalorimeterHit::unmarshal().
void MarshaledG4HitsCollection::unmarshalTo (G4HitsCollection * obj) inline
Definition at line 75 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 75 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
void MarshaledG4HitsCollection::unmarshalTo (G4HitsCollection * obj) inline
Definition at line 77 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 77 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
Referenced by MarshaledG4THitsCollection< T >::unmarshal1().
void MarshaledG4HitsCollection::unmarshalTo (G4HitsCollection * obj) inline
Definition at line 81 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 81 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
void MarshaledG4HitsCollection::unmarshalTo (G4HitsCollection * obj) inline
Definition at line 85 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 85 of file MarshaledG4THitsCollection.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
Member Data Documentation
G4HitsCollection * MarshaledG4HitsCollection::param
Definition at line 32 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 32 of file MarshaledG4THitsCollection.h
Referenced by marshal1(), MarshaledG4HitsCollection(), unmarshal(), unmarshal1(), and unmarshalTo().
ShadowedMarshaledG4HitsCollection * MarshaledG4HitsCollection::Shadowed_param
Definition at line 33 of file MarshaledG4THitsCollection.h.
View newest version in sPHENIX GitHub at line 33 of file MarshaledG4THitsCollection.h
Referenced by MarshaledG4HitsCollection(), unmarshal(), and unmarshalTo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/MarshaledG4THitsCollection.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/MarshaledG4THitsCollection.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/AnnotatedFiles/MarshaledG4THitsCollection.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/MarshaledG4THitsCollection.h