ECCE @ EIC Software: G4UnionSolid Class Reference
G4UnionSolid Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/Boolean/include/G4UnionSolid.hh>
Public Member Functions
G4UnionSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB)
G4UnionSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB, G4RotationMatrix *rotMatrix, const G4ThreeVector &transVector)
G4UnionSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB, const G4Transform3D &transform)
virtual ~G4UnionSolid ()
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
G4UnionSolid (__void__ &)
G4UnionSolid (const G4UnionSolid &rhs)
G4UnionSolid & operator= (const G4UnionSolid &rhs)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
Public Member Functions inherited from G4BooleanSolid
G4BooleanSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB)
G4BooleanSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB, G4RotationMatrix *rotMatrix, const G4ThreeVector &transVector)
G4BooleanSolid (const G4String &pName, G4VSolid *pSolidA, G4VSolid *pSolidB, const G4Transform3D &transform)
virtual ~G4BooleanSolid ()
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
virtual G4Polyhedron * GetPolyhedron () const
std::ostream & StreamInfo (std::ostream &os) const
G4int GetCubVolStatistics () const
G4double GetCubVolEpsilon () const
void SetCubVolStatistics (G4int st)
void SetCubVolEpsilon (G4double ep)
G4int GetAreaStatistics () const
G4double GetAreaAccuracy () const
void SetAreaStatistics (G4int st)
void SetAreaAccuracy (G4double ep)
G4ThreeVector GetPointOnSurface () const
G4BooleanSolid (__void__ &)
G4BooleanSolid (const G4BooleanSolid &rhs)
G4BooleanSolid & operator= (const G4BooleanSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Attributes
G4ThreeVector fPMin
G4ThreeVector fPMax
Additional Inherited Members
Protected Member Functions inherited from G4BooleanSolid
void GetListOfPrimitives (std::vector< std::pair< G4VSolid *, G4Transform3D >> &, const G4Transform3D &) const
G4Polyhedron * StackPolyhedron (HepPolyhedronProcessor &, const G4VSolid *) const
Protected Attributes inherited from G4BooleanSolid
G4VSolid * fPtrSolidA = nullptr
G4VSolid * fPtrSolidB = nullptr
Detailed Description
Definition at line 45 of file G4UnionSolid.hh.
View newest version in sPHENIX GitHub at line 45 of file G4UnionSolid.hh
Constructor & Destructor Documentation
G4UnionSolid::G4UnionSolid (const G4String & pName, G4VSolid * pSolidA, G4VSolid * pSolidB)
Definition at line 51 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 51 of file G4UnionSolid.cc
References BoundingLimits(), fPMax, fPMin, and G4VSolid::kCarTolerance.
Referenced by Clone().
G4UnionSolid::G4UnionSolid (const G4String & pName, G4VSolid * pSolidA, G4VSolid * pSolidB, G4RotationMatrix * rotMatrix, const G4ThreeVector & transVector)
Definition at line 67 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 67 of file G4UnionSolid.cc
References BoundingLimits(), fPMax, fPMin, and G4VSolid::kCarTolerance.
G4UnionSolid::G4UnionSolid (const G4String & pName, G4VSolid * pSolidA, G4VSolid * pSolidB, const G4Transform3D & transform)
Definition at line 86 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 86 of file G4UnionSolid.cc
References BoundingLimits(), fPMax, fPMin, and G4VSolid::kCarTolerance.
G4UnionSolid::~G4UnionSolid () virtual
Definition at line 113 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 113 of file G4UnionSolid.cc
G4UnionSolid::G4UnionSolid (__void__ & a)
Definition at line 104 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 104 of file G4UnionSolid.cc
G4UnionSolid::G4UnionSolid (const G4UnionSolid & rhs)
Definition at line 121 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 121 of file G4UnionSolid.cc
References fPMax, and fPMin.
Member Function Documentation
void G4UnionSolid::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 151 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 151 of file G4UnionSolid.cc
References G4VSolid::BoundingLimits(), G4VSolid::DumpInfo(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4Exception(), G4VSolid::GetName(), JustWarning, max, maxA, message(), min, pMax, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4UnionSolid().
G4bool G4UnionSolid::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 186 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 186 of file G4UnionSolid.cc
References G4VSolid::CalculateExtent(), false, G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, kInfinity, max, maxA, min, and true.
G4VSolid * G4UnionSolid::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 488 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 488 of file G4UnionSolid.cc
References G4UnionSolid().
void G4UnionSolid::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 498 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 498 of file G4UnionSolid.cc
G4Polyhedron * G4UnionSolid::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 519 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 519 of file G4UnionSolid.cc
References HepPolyhedronProcessor::execute(), processor, and G4BooleanSolid::StackPolyhedron().
Referenced by G4VisCommandSceneAddLogo::G4Logo::G4Logo().
void G4UnionSolid::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 509 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 509 of file G4UnionSolid.cc
References G4VGraphicsScene::AddSolid().
G4double G4UnionSolid::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 286 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 286 of file G4UnionSolid.cc
References G4VSolid::DistanceToIn(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, Inside(), kInside, and min.
G4double G4UnionSolid::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 315 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 315 of file G4UnionSolid.cc
References distA, G4VSolid::DistanceToIn(), distB, G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, Inside(), kInside, and min.
G4double G4UnionSolid::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 342 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 342 of file G4UnionSolid.cc
References G4VSolid::DistanceToOut(), false, G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, Inside(), G4VSolid::Inside(), G4VSolid::kCarTolerance, kOutside, mm, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4UnionSolid::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 429 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 429 of file G4UnionSolid.cc
References G4VSolid::DistanceToOut(), G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4cerr, G4cout, G4endl, Inside(), G4VSolid::Inside(), kInside, kOutside, kSurface, and max.
G4GeometryType G4UnionSolid::GetEntityType () const virtual
Reimplemented from G4BooleanSolid.
Definition at line 479 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 479 of file G4UnionSolid.cc
EInside G4UnionSolid::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 220 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 220 of file G4UnionSolid.cc
References fPMax, fPMin, G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetRadialTolerance(), G4VSolid::Inside(), kInside, kOutside, kSurface, max, G4VSolid::SurfaceNormal(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToIn(), DistanceToOut(), and SurfaceNormal().
G4UnionSolid & G4UnionSolid::operator= (const G4UnionSolid & rhs)
Definition at line 132 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 132 of file G4UnionSolid.cc
References fPMax, fPMin, and G4BooleanSolid::operator=().
G4ThreeVector G4UnionSolid::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 246 of file G4UnionSolid.cc.
View newest version in sPHENIX GitHub at line 246 of file G4UnionSolid.cc
References G4BooleanSolid::fPtrSolidA, G4BooleanSolid::fPtrSolidB, G4Exception(), G4VSolid::GetName(), Inside(), G4VSolid::Inside(), JustWarning, kOutside, kSurface, message(), G4VSolid::SurfaceNormal(), and CLHEP::Hep3Vector::unit().
Member Data Documentation
G4ThreeVector G4UnionSolid::fPMax private
Definition at line 115 of file G4UnionSolid.hh.
View newest version in sPHENIX GitHub at line 115 of file G4UnionSolid.hh
Referenced by G4UnionSolid(), Inside(), and operator=().
G4ThreeVector G4UnionSolid::fPMin private
Definition at line 115 of file G4UnionSolid.hh.
View newest version in sPHENIX GitHub at line 115 of file G4UnionSolid.hh
Referenced by G4UnionSolid(), Inside(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/Boolean/include/G4UnionSolid.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/Boolean/src/G4UnionSolid.cc