ECCE @ EIC Software: PHG4EtaParameterization Class Reference
PHG4EtaParameterization Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4EtaParameterization.h>
Public Member Functions
PHG4EtaParameterization (unsigned int neta, double minEta, double maxEta, double startPhi, double deltaPhi, double radiusIn, double radiusOut, double centerZ)
~PHG4EtaParameterization () override
virtual void Print (std::ostream &os=std::cout) const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const override
void ComputeDimensions (G4Tubs &ring, const G4int copyNo, const G4VPhysicalVolume *physVol) const override
int GetIEta (int copyNo) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
unsigned int _neta
double _minEta
double _maxEta
double _startPhi
double _deltaPhi
double _radiusIn
double _radiusOut
double _centerZ
std::vector< double > _zpos
std::vector< double > _zhalf
std::vector< double > _phi0
std::vector< double > _phi1
std::vector< int > _ieta
std::vector< int > _iphi
Detailed Description
Definition at line 18 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4EtaParameterization.h
Constructor & Destructor Documentation
PHG4EtaParameterization::PHG4EtaParameterization (unsigned int neta, double minEta, double maxEta, double startPhi, double deltaPhi, double radiusIn, double radiusOut, double centerZ)
Definition at line 16 of file PHG4EtaParameterization.cc.
View newest version in sPHENIX GitHub at line 16 of file PHG4EtaParameterization.cc
References _centerZ, _deltaPhi, _ieta, _maxEta, _minEta, _neta, _radiusIn, _radiusOut, _startPhi, _zhalf, _zpos, g4zmq::exit(), and BTOF::zpos.
PHG4EtaParameterization::~PHG4EtaParameterization () override
Definition at line 93 of file PHG4EtaParameterization.cc.
View newest version in sPHENIX GitHub at line 93 of file PHG4EtaParameterization.cc
Member Function Documentation
void PHG4EtaParameterization::ComputeDimensions (G4Tubs & ring, const G4int copyNo, const G4VPhysicalVolume * physVol) const override virtual
Reimplemented from G4VPVParameterisation.
Definition at line 115 of file PHG4EtaParameterization.cc.
View newest version in sPHENIX GitHub at line 115 of file PHG4EtaParameterization.cc
References _deltaPhi, _radiusIn, _radiusOut, _startPhi, _zhalf, G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), and G4Tubs::SetZHalfLength().
void PHG4EtaParameterization::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const override virtual
Implements G4VPVParameterisation.
Definition at line 107 of file PHG4EtaParameterization.cc.
View newest version in sPHENIX GitHub at line 107 of file PHG4EtaParameterization.cc
References _zpos, Acts::Test::origin(), G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
int PHG4EtaParameterization::GetIEta (int copyNo) const inline
Definition at line 43 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 43 of file PHG4EtaParameterization.h
References _ieta.
void PHG4EtaParameterization::Print (std::ostream & os = std::cout) const virtual
Definition at line 99 of file PHG4EtaParameterization.cc.
View newest version in sPHENIX GitHub at line 99 of file PHG4EtaParameterization.cc
References _neta, _zpos, and field_utils::copy().
Member Data Documentation
double PHG4EtaParameterization::_centerZ private
Definition at line 68 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4EtaParameterization.h
Referenced by PHG4EtaParameterization().
double PHG4EtaParameterization::_deltaPhi private
Definition at line 65 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4EtaParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaParameterization().
std::vector<int> PHG4EtaParameterization::_ieta private
Definition at line 73 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4EtaParameterization.h
Referenced by GetIEta(), and PHG4EtaParameterization().
std::vector<int> PHG4EtaParameterization::_iphi private
Definition at line 74 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4EtaParameterization.h
double PHG4EtaParameterization::_maxEta private
Definition at line 63 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4EtaParameterization.h
Referenced by PHG4EtaParameterization().
double PHG4EtaParameterization::_minEta private
Definition at line 62 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 62 of file PHG4EtaParameterization.h
Referenced by PHG4EtaParameterization().
unsigned int PHG4EtaParameterization::_neta private
Definition at line 61 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 61 of file PHG4EtaParameterization.h
Referenced by PHG4EtaParameterization(), and Print().
std::vector<double> PHG4EtaParameterization::_phi0 private
Definition at line 71 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4EtaParameterization.h
std::vector<double> PHG4EtaParameterization::_phi1 private
Definition at line 72 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4EtaParameterization.h
double PHG4EtaParameterization::_radiusIn private
Definition at line 66 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4EtaParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaParameterization().
double PHG4EtaParameterization::_radiusOut private
Definition at line 67 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4EtaParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaParameterization().
double PHG4EtaParameterization::_startPhi private
Definition at line 64 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4EtaParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaParameterization().
std::vector<double> PHG4EtaParameterization::_zhalf private
Definition at line 70 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4EtaParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaParameterization().
std::vector<double> PHG4EtaParameterization::_zpos private
Definition at line 69 of file PHG4EtaParameterization.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4EtaParameterization.h
Referenced by ComputeTransformation(), PHG4EtaParameterization(), and Print().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4EtaParameterization.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4EtaParameterization.cc