ECCE @ EIC Software: G4FluoData Class Reference
G4FluoData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4FluoData.hh>
Public Member Functions
G4FluoData (const G4String &dir)
~G4FluoData ()
size_t NumberOfVacancies () const
G4int VacancyId (G4int vacancyIndex) const
size_t NumberOfTransitions (G4int vacancyIndex) const
G4int StartShellId (G4int initIndex, G4int vacancyIndex) const
G4double StartShellEnergy (G4int initIndex, G4int vacancyIndex) const
G4double StartShellProb (G4int initIndex, G4int vacancyIndex) const
void LoadData (G4int Z)
void PrintData ()
Private Member Functions
G4FluoData & operator= (const G4FluoData &right)
G4FluoData (const G4FluoData &)
Private Attributes
std::map< G4int, G4DataVector
*, std::less< G4int > > idMap
std::map< G4int, G4DataVector
*, std::less< G4int > > energyMap
std::map< G4int, G4DataVector
*, std::less< G4int > > probabilityMap
std::vector< G4int > nInitShells
G4int numberOfVacancies
std::map< G4int, std::vector
< G4FluoTransition * >
, std::less< G4int > > fluoTransitionTable
G4String fluoDirectory
Detailed Description
Definition at line 52 of file G4FluoData.hh.
View newest version in sPHENIX GitHub at line 52 of file G4FluoData.hh
Constructor & Destructor Documentation
G4FluoData::G4FluoData (const G4String & dir)
Definition at line 44 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 44 of file G4FluoData.cc
References dir, fluoDirectory, and numberOfVacancies.
G4FluoData::~G4FluoData ()
Definition at line 50 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 50 of file G4FluoData.cc
References energyMap, idMap, pos(), and probabilityMap.
G4FluoData::G4FluoData (const G4FluoData &) private
Member Function Documentation
void G4FluoData::LoadData (G4int Z)
Definition at line 195 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 195 of file G4FluoData.cc
References a, e, energyMap, FatalException, file, fluoDirectory, G4Exception(), idMap, k, MeV, n, nInitShells, numberOfVacancies, and probabilityMap.
Referenced by G4AtomicTransitionManager::Initialise().
size_t G4FluoData::NumberOfTransitions (G4int vacancyIndex) const
Definition at line 97 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 97 of file G4FluoData.cc
References G4Exception(), JustWarning, n, nInitShells, and numberOfVacancies.
Referenced by G4AtomicTransitionManager::Initialise(), and PrintData().
size_t G4FluoData::NumberOfVacancies () const
Definition at line 71 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 71 of file G4FluoData.cc
References numberOfVacancies.
G4FluoData& G4FluoData::operator= (const G4FluoData & right) private
void G4FluoData::PrintData (void)
Definition at line 320 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 320 of file G4FluoData.cc
References e, G4cout, G4endl, k, MeV, NumberOfTransitions(), numberOfVacancies, StartShellEnergy(), StartShellId(), and StartShellProb().
G4double G4FluoData::StartShellEnergy (G4int initIndex, G4int vacancyIndex) const
Definition at line 143 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 143 of file G4FluoData.cc
References energyMap, FatalErrorInArgument, G4Exception(), n, numberOfVacancies, and pos().
Referenced by G4AtomicTransitionManager::Initialise(), and PrintData().
G4int G4FluoData::StartShellId (G4int initIndex, G4int vacancyIndex) const
Definition at line 115 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 115 of file G4FluoData.cc
References FatalErrorInArgument, G4Exception(), idMap, n, numberOfVacancies, and pos().
Referenced by G4AtomicTransitionManager::Initialise(), and PrintData().
G4double G4FluoData::StartShellProb (G4int initIndex, G4int vacancyIndex) const
Definition at line 168 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 168 of file G4FluoData.cc
References G4Exception(), JustWarning, n, numberOfVacancies, pos(), and probabilityMap.
Referenced by G4AtomicTransitionManager::Initialise(), and PrintData().
G4int G4FluoData::VacancyId (G4int vacancyIndex) const
Definition at line 76 of file G4FluoData.cc.
View newest version in sPHENIX GitHub at line 76 of file G4FluoData.cc
References FatalErrorInArgument, G4Exception(), idMap, n, numberOfVacancies, and pos().
Referenced by G4AtomicTransitionManager::Initialise().
Member Data Documentation
std::map<G4int,G4DataVector*,std::less<G4int> > G4FluoData::energyMap private
Definition at line 99 of file G4FluoData.hh.
View newest version in sPHENIX GitHub at line 99 of file G4FluoData.hh
Referenced by LoadData(), StartShellEnergy(), and ~G4FluoData().
G4String G4FluoData::fluoDirectory private
Definition at line 104 of file G4FluoData.hh.
View newest version in sPHENIX GitHub at line 104 of file G4FluoData.hh
Referenced by G4FluoData(), and LoadData().
std::map<G4int,std::vector<G4FluoTransition*>,std::less<G4int> > G4FluoData::fluoTransitionTable private
Definition at line 103 of file G4FluoData.hh.
View newest version in sPHENIX GitHub at line 103 of file G4FluoData.hh
std::map<G4int,G4DataVector*,std::less<G4int> > G4FluoData::idMap private
Definition at line 98 of file G4FluoData.hh.
View newest version in sPHENIX GitHub at line 98 of file G4FluoData.hh
Referenced by LoadData(), StartShellId(), VacancyId(), and ~G4FluoData().
std::vector<G4int> G4FluoData::nInitShells private
Definition at line 101 of file G4FluoData.hh.
View newest version in sPHENIX GitHub at line 101 of file G4FluoData.hh
Referenced by LoadData(), and NumberOfTransitions().
G4int G4FluoData::numberOfVacancies private
Definition at line 102 of file G4FluoData.hh.
View newest version in sPHENIX GitHub at line 102 of file G4FluoData.hh
Referenced by G4FluoData(), LoadData(), NumberOfTransitions(), NumberOfVacancies(), PrintData(), StartShellEnergy(), StartShellId(), StartShellProb(), and VacancyId().
std::map<G4int,G4DataVector*,std::less<G4int> > G4FluoData::probabilityMap private
Definition at line 100 of file G4FluoData.hh.
View newest version in sPHENIX GitHub at line 100 of file G4FluoData.hh
Referenced by LoadData(), StartShellProb(), and ~G4FluoData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4FluoData.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4FluoData.cc