ECCE @ EIC Software: dualRICH_aerogel Class Reference
dualRICH_aerogel Class Reference
#include <ecce-detectors/blob/master/FastPID/dRICH/dualRICH.h>
Public Member Functions
dualRICH_aerogel ()
virtual ~dualRICH_aerogel ()=default
Public Member Functions inherited from genericRICH
genericRICH ()=default
virtual ~genericRICH ()=default
void setIndex (double val)
void setEfficiency (double val)
void setMinPhotons (double val)
void setThresholdMode (bool val)
void setChromaticSigma (int n, double *valx, double *valy)
void setPositionSigma (int n, double *valx, double *valy)
void setEmissionSigma (int n, double *valx, double *valy)
void setFieldSigma (int n, double *valx, double *valy)
void setTrackingSigma (int n, double *valx, double *valy)
double numSigma (double eta, double p, PID::type PID) override
double maxP (double eta, double nsigma, PID::type PID) override
double minP (double eta, double nsigma, PID::type PID) override
double cherenkovAngle (double p, double m) const
double cherenkovThreshold (double m) const
double numberOfPhotons (double angle) const
double numberOfDetectedPhotons (double angle) const
double cherenkovAngleSigma (double eta, double p, double m) const
Public Member Functions inherited from genericDetector
genericDetector ()=default
virtual ~genericDetector ()=default
void setType (EDetector_t val)
void setName (string val)
void setLength (double val)
void setRadius (double val)
void setPositionZ (double val)
void setRadiusIn (double val)
void setRadiusOut (double val)
void setMagneticField (double val)
virtual bool valid (double eta, double p) override
string name () override
void description () override
double maxPt (double eta, double numSigma, PID::type PID)
double minPt (double eta, double numSigma, PID::type PID)
Public Member Functions inherited from PID
PID ()
virtual ~PID ()
virtual double maxP (double eta, double p, double numSigma, PID::type PID)=0
Additional Inherited Members
Public Types inherited from genericDetector
enum EDetector_t { kBarrel, kForward }
Protected Member Functions inherited from genericDetector
double etaMin ()
double etaMax ()
double ptMin ()
double pMin (double eta)
bool isHit (double eta, double p)
double trackLength (double eta)
Protected Attributes inherited from genericRICH
double mIndex = 1.0014
double mEfficiency = 0.25
double mMinPhotons = 3.
TGraph * mChromaticSigma = nullptr
TGraph * mPositionSigma = nullptr
TGraph * mEmissionSigma = nullptr
TGraph * mFieldSigma = nullptr
TGraph * mTrackingSigma = nullptr
bool mThresholdMode = true
Detailed Description
Author
R+Preghenella pregh.nosp@m.enel.nosp@m.la@bo.nosp@m..inf.nosp@m.n.it
Date
April 2020 dualRICH aerogel
Definition at line 12 of file dualRICH.h.
View newest version in sPHENIX GitHub at line 12 of file dualRICH.h
Constructor & Destructor Documentation
dualRICH_aerogel::dualRICH_aerogel ()
geometry
radiator
overall photon-detection efficiency
single-photon angular resolution
Definition at line 19 of file dualRICH.h.
View newest version in sPHENIX GitHub at line 19 of file dualRICH.h
References angle, genericDetector::kForward, genericRICH::setChromaticSigma(), genericRICH::setEfficiency(), genericRICH::setEmissionSigma(), genericRICH::setFieldSigma(), genericRICH::setIndex(), genericDetector::setLength(), genericDetector::setName(), genericRICH::setPositionSigma(), genericDetector::setPositionZ(), genericDetector::setRadiusIn(), genericDetector::setRadiusOut(), genericRICH::setTrackingSigma(), and genericDetector::setType().
virtual dualRICH_aerogel::~dualRICH_aerogel () virtual default
The documentation for this class was generated from the following file:
ecce-detectors/blob/master/FastPID/dRICH/dualRICH.h