ECCE @ EIC Software: G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 > Struct Template Reference
G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 > Struct Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeData.hh>
Public Types
enum {
N02 =N2, N23 =N2+N3, N24 =N23+N4, N25 =N24+N5,
N26 =N25+N6, N27 =N26+N7, N28 =N27+N8, N29 =N28+N9
}
enum { N8D =N8?N8:1, N9D =N9?N9:1 }
enum { NM =N9?8:N8?7:6, NXS =N29 }
Public Member Functions
G4int maxMultiplicity () const
void print (std::ostream &os=G4cout) const
void print (G4int mult, std::ostream &os) const
void printXsec (const G4double(&xsec)[NE], std::ostream &os) const
G4CascadeData (const G4int(&the2bfs)[N2][2], const G4int(&the3bfs)[N3][3], const G4int(&the4bfs)[N4][4], const G4int(&the5bfs)[N5][5], const G4int(&the6bfs)[N6][6], const G4int(&the7bfs)[N7][7], const G4double(&xsec)[NXS][NE], G4int ini, const G4String &aName="G4CascadeData")
G4CascadeData (const G4int(&the2bfs)[N2][2], const G4int(&the3bfs)[N3][3], const G4int(&the4bfs)[N4][4], const G4int(&the5bfs)[N5][5], const G4int(&the6bfs)[N6][6], const G4int(&the7bfs)[N7][7], const G4double(&xsec)[NXS][NE], const G4double(&theTot)[NE], G4int ini, const G4String &aName="G4CascadeData")
G4CascadeData (const G4int(&the2bfs)[N2][2], const G4int(&the3bfs)[N3][3], const G4int(&the4bfs)[N4][4], const G4int(&the5bfs)[N5][5], const G4int(&the6bfs)[N6][6], const G4int(&the7bfs)[N7][7], const G4int(&the8bfs)[N8D][8], const G4int(&the9bfs)[N9D][9], const G4double(&xsec)[NXS][NE], G4int ini, const G4String &aName="G4CascadeData")
G4CascadeData (const G4int(&the2bfs)[N2][2], const G4int(&the3bfs)[N3][3], const G4int(&the4bfs)[N4][4], const G4int(&the5bfs)[N5][5], const G4int(&the6bfs)[N6][6], const G4int(&the7bfs)[N7][7], const G4int(&the8bfs)[N8D][8], const G4int(&the9bfs)[N9D][9], const G4double(&xsec)[NXS][NE], const G4double(&theTot)[NE], G4int ini, const G4String &aName="G4CascadeData")
void initialize ()
Public Attributes
G4int index [9]
G4double multiplicities [NM][NE]
const G4int(& x2bfs)[N2][2]
const G4int(& x3bfs)[N3][3]
const G4int(& x4bfs)[N4][4]
const G4int(& x5bfs)[N5][5]
const G4int(& x6bfs)[N6][6]
const G4int(& x7bfs)[N7][7]
const G4int(& x8bfs)[N8D][8]
const G4int(& x9bfs)[N9D][9]
const G4double(& crossSections)[NXS][NE]
G4double sum [NE]
const G4double(& tot)[NE]
G4double inelastic [NE]
const G4String name
const G4int initialState
Static Public Attributes
static const G4int empty8bfs [1][8] = {{0}}
static const G4int empty9bfs [1][9] = {{0}}
Detailed Description
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0>
struct G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >
Definition at line 52 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 52 of file G4CascadeData.hh
Member Enumeration Documentation
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> anonymous enum
Enumerator:
N02
N23
N24
N25
N26
N27
N28
N29
Definition at line 55 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 55 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> anonymous enum
Enumerator:
N8D
N9D
Definition at line 58 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 58 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> anonymous enum
Enumerator:
NM
NXS
Definition at line 60 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 60 of file G4CascadeData.hh
Constructor & Destructor Documentation
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::G4CascadeData (const G4int(&) the2bfs[N2][2], const G4int(&) the3bfs[N3][3], const G4int(&) the4bfs[N4][4], const G4int(&) the5bfs[N5][5], const G4int(&) the6bfs[N6][6], const G4int(&) the7bfs[N7][7], const G4double(&) xsec[NXS][NE], G4int ini, const G4String & aName = "G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >") inline
Definition at line 94 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 94 of file G4CascadeData.hh
References G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::initialize().
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::G4CascadeData (const G4int(&) the2bfs[N2][2], const G4int(&) the3bfs[N3][3], const G4int(&) the4bfs[N4][4], const G4int(&) the5bfs[N5][5], const G4int(&) the6bfs[N6][6], const G4int(&) the7bfs[N7][7], const G4double(&) xsec[NXS][NE], const G4double(&) theTot[NE], G4int ini, const G4String & aName = "G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >") inline
Definition at line 106 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 106 of file G4CascadeData.hh
References G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::initialize().
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::G4CascadeData (const G4int(&) the2bfs[N2][2], const G4int(&) the3bfs[N3][3], const G4int(&) the4bfs[N4][4], const G4int(&) the5bfs[N5][5], const G4int(&) the6bfs[N6][6], const G4int(&) the7bfs[N7][7], const G4int(&) the8bfs[N8D][8], const G4int(&) the9bfs[N9D][9], const G4double(&) xsec[NXS][NE], G4int ini, const G4String & aName = "G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >") inline
Definition at line 118 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 118 of file G4CascadeData.hh
References G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::initialize().
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::G4CascadeData (const G4int(&) the2bfs[N2][2], const G4int(&) the3bfs[N3][3], const G4int(&) the4bfs[N4][4], const G4int(&) the5bfs[N5][5], const G4int(&) the6bfs[N6][6], const G4int(&) the7bfs[N7][7], const G4int(&) the8bfs[N8D][8], const G4int(&) the9bfs[N9D][9], const G4double(&) xsec[NXS][NE], const G4double(&) theTot[NE], G4int ini, const G4String & aName = "G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >") inline
Definition at line 131 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 131 of file G4CascadeData.hh
References G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::initialize().
Member Function Documentation
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> void G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::initialize ()
Referenced by G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::G4CascadeData().
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4int G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::maxMultiplicity () const inline
Definition at line 86 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 86 of file G4CascadeData.hh
References G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::NM.
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> void G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::print (std::ostream & os = G4cout) const
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> void G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::print (G4int mult, std::ostream & os) const
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> void G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::printXsec (const G4double(&) xsec[NE], std::ostream & os) const
Member Data Documentation
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4double(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::crossSections)[NXS][NE]
Definition at line 73 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 73 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::empty8bfs = {{0}} static
Definition at line 80 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 80 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::empty9bfs = {{0}} static
Definition at line 81 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 81 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4int G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::index[9]
Definition at line 62 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 62 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4double G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::inelastic[NE]
Definition at line 78 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 78 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::initialState
Definition at line 84 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 84 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4double G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::multiplicities[NM][NE]
Definition at line 63 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 63 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4String G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::name
Definition at line 83 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 83 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> G4double G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::sum[NE]
Definition at line 75 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 75 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4double(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::tot)[NE]
Definition at line 76 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::x2bfs)[N2][2]
Definition at line 65 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 65 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::x3bfs)[N3][3]
Definition at line 66 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 66 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::x4bfs)[N4][4]
Definition at line 67 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 67 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::x5bfs)[N5][5]
Definition at line 68 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 68 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::x6bfs)[N6][6]
Definition at line 69 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 69 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::x7bfs)[N7][7]
Definition at line 70 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 70 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::x8bfs)[N8D][8]
Definition at line 71 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 71 of file G4CascadeData.hh
template<int NE, int N2, int N3, int N4, int N5, int N6, int N7, int N8 = 0, int N9 = 0> const G4int(& G4CascadeData< NE, N2, N3, N4, N5, N6, N7, N8, N9 >::x9bfs)[N9D][9]
Definition at line 72 of file G4CascadeData.hh.
View newest version in sPHENIX GitHub at line 72 of file G4CascadeData.hh
The documentation for this struct was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeData.hh