ECCE @ EIC Software: G4XMesonBaryonElastic Class Reference
G4XMesonBaryonElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XMesonBaryonElastic.hh>
Public Member Functions
G4XMesonBaryonElastic ()
virtual ~G4XMesonBaryonElastic ()
G4bool operator== (const G4XMesonBaryonElastic &right) const
G4bool operator!= (const G4XMesonBaryonElastic &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4bool IsValid (G4double e) const
virtual G4String Name () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Private Member Functions
G4XMesonBaryonElastic (const G4XMesonBaryonElastic &right)
const G4XMesonBaryonElastic & operator= (const G4XMesonBaryonElastic &right)
Private Attributes
G4double lowLimit
G4double highLimit
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 50 of file G4XMesonBaryonElastic.hh.
View newest version in sPHENIX GitHub at line 50 of file G4XMesonBaryonElastic.hh
Constructor & Destructor Documentation
G4XMesonBaryonElastic::G4XMesonBaryonElastic ()
Definition at line 38 of file G4XMesonBaryonElastic.cc.
View newest version in sPHENIX GitHub at line 38 of file G4XMesonBaryonElastic.cc
References DBL_MAX, highLimit, and lowLimit.
G4XMesonBaryonElastic::~G4XMesonBaryonElastic () virtual
Definition at line 47 of file G4XMesonBaryonElastic.cc.
View newest version in sPHENIX GitHub at line 47 of file G4XMesonBaryonElastic.cc
G4XMesonBaryonElastic::G4XMesonBaryonElastic (const G4XMesonBaryonElastic & right) private
Member Function Documentation
G4double G4XMesonBaryonElastic::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 63 of file G4XMesonBaryonElastic.cc.
View newest version in sPHENIX GitHub at line 63 of file G4XMesonBaryonElastic.cc
References G4XAqmElastic::CrossSection(), G4XPDGElastic::CrossSection(), G4VCrossSectionSource::FindLightParticle(), G4Gamma::GammaDefinition(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetFormationTime(), G4KineticTrack::GetPosition(), pdg, G4PionPlus::PionPlusDefinition(), and G4Proton::ProtonDefinition().
virtual const G4CrossSectionVector* G4XMesonBaryonElastic::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 64 of file G4XMesonBaryonElastic.hh.
View newest version in sPHENIX GitHub at line 64 of file G4XMesonBaryonElastic.hh
G4bool G4XMesonBaryonElastic::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 117 of file G4XMesonBaryonElastic.cc.
View newest version in sPHENIX GitHub at line 117 of file G4XMesonBaryonElastic.cc
References highLimit, G4VCrossSectionSource::InLimits(), and lowLimit.
G4String G4XMesonBaryonElastic::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 109 of file G4XMesonBaryonElastic.cc.
View newest version in sPHENIX GitHub at line 109 of file G4XMesonBaryonElastic.cc
G4bool G4XMesonBaryonElastic::operator!= (const G4XMesonBaryonElastic & right) const
Definition at line 57 of file G4XMesonBaryonElastic.cc.
View newest version in sPHENIX GitHub at line 57 of file G4XMesonBaryonElastic.cc
const G4XMesonBaryonElastic& G4XMesonBaryonElastic::operator= (const G4XMesonBaryonElastic & right) private
G4bool G4XMesonBaryonElastic::operator== (const G4XMesonBaryonElastic & right) const
Definition at line 51 of file G4XMesonBaryonElastic.cc.
View newest version in sPHENIX GitHub at line 51 of file G4XMesonBaryonElastic.cc
Member Data Documentation
G4double G4XMesonBaryonElastic::highLimit private
Definition at line 80 of file G4XMesonBaryonElastic.hh.
View newest version in sPHENIX GitHub at line 80 of file G4XMesonBaryonElastic.hh
Referenced by G4XMesonBaryonElastic(), and IsValid().
G4double G4XMesonBaryonElastic::lowLimit private
Definition at line 79 of file G4XMesonBaryonElastic.hh.
View newest version in sPHENIX GitHub at line 79 of file G4XMesonBaryonElastic.hh
Referenced by G4XMesonBaryonElastic(), and IsValid().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XMesonBaryonElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XMesonBaryonElastic.cc