ECCE @ EIC Software: B4cDetectorConstruction Class Reference
B4cDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B4/B4c/include/B4cDetectorConstruction.hh>
Public Member Functions
B4cDetectorConstruction ()
virtual ~B4cDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
G4VPhysicalVolume * DefineVolumes ()
Private Attributes
G4bool fCheckOverlaps
G4int fNofLayers
Static Private Attributes
static G4ThreadLocal
G4GlobalMagFieldMessenger * fMagFieldMessenger = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Detector construction class to define materials and geometry. The calorimeter is a box made of a given number of layers. A layer consists of an absorber plate and of a detection gap. The layer is replicated.
Four parameters define the geometry of the calorimeter :
the thickness of an absorber plate,
the thickness of a gap,
the number of layers,
the transverse size of the calorimeter (the input face is a square).
In ConstructSDandField() sensitive detectors of B4cCalorimeterSD type are created and associated with the Absorber and Gap volumes. In addition a transverse uniform magnetic field is defined via G4GlobalMagFieldMessenger class.
Definition at line 55 of file B4cDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file B4cDetectorConstruction.hh
Constructor & Destructor Documentation
B4cDetectorConstruction::B4cDetectorConstruction ()
Definition at line 57 of file B4cDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 57 of file B4cDetectorConstruction.cc
B4cDetectorConstruction::~B4cDetectorConstruction () virtual
Definition at line 66 of file B4cDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 66 of file B4cDetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * B4cDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 72 of file B4cDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 72 of file B4cDetectorConstruction.cc
References DefineMaterials(), and DefineVolumes().
void B4cDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 274 of file B4cDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 274 of file B4cDetectorConstruction.cc
References G4SDManager::AddNewDetector(), fMagFieldMessenger, fNofLayers, G4SDManager::GetSDMpointer(), G4AutoDelete::Register(), G4VUserDetectorConstruction::SetSensitiveDetector(), and G4GlobalMagFieldMessenger::SetVerboseLevel().
void B4cDetectorConstruction::DefineMaterials () private
Definition at line 83 of file B4cDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 83 of file B4cDetectorConstruction.cc
References a, cm3, e, Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetMaterialTable(), G4NistManager::Instance(), kelvin, kStateGas, mole, pascal, source.hepunit::universe_mean_density, and z.
Referenced by Construct().
G4VPhysicalVolume * B4cDetectorConstruction::DefineVolumes () private
Definition at line 106 of file B4cDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 106 of file B4cDetectorConstruction.cc
References cm, FatalException, fCheckOverlaps, fNofLayers, G4cout, G4endl, G4Exception(), G4VisAttributes::GetInvisible(), G4Material::GetMaterial(), kZAxis, and mm.
Referenced by Construct().
Member Data Documentation
G4bool B4cDetectorConstruction::fCheckOverlaps private
Definition at line 76 of file B4cDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file B4cDetectorConstruction.hh
Referenced by DefineVolumes().
G4ThreadLocal G4GlobalMagFieldMessenger * B4cDetectorConstruction::fMagFieldMessenger = 0 static private
Definition at line 73 of file B4cDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file B4cDetectorConstruction.hh
Referenced by ConstructSDandField().
G4int B4cDetectorConstruction::fNofLayers private
Definition at line 77 of file B4cDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 77 of file B4cDetectorConstruction.hh
Referenced by ConstructSDandField(), and DefineVolumes().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B4/B4c/include/B4cDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/basic/B4/B4c/src/B4cDetectorConstruction.cc