ECCE @ EIC Software: G4TrackStack Class Reference
G4TrackStack Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4TrackStack.hh>
Public Member Functions
G4TrackStack ()
G4TrackStack (size_t n)
~G4TrackStack ()
G4TrackStack & operator= (const G4TrackStack &)=delete
G4bool operator== (const G4TrackStack &) const =delete
G4bool operator!= (const G4TrackStack &) const =delete
void PushToStack (const G4StackedTrack &aStackedTrack)
G4StackedTrack PopFromStack ()
void TransferTo (G4TrackStack *aStack)
void TransferTo (G4SmartTrackStack *aStack)
void clearAndDestroy ()
size_t GetNTrack () const
size_t GetMaxNTrack () const
G4int GetSafetyValue1 () const
G4int GetSafetyValue2 () const
G4int GetNStick () const
G4double getTotalEnergy (void) const
void SetSafetyValue2 (G4int x)
Private Attributes
G4int safetyValue1
G4int safetyValue2
G4int nstick
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 44 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 44 of file G4TrackStack.hh
Constructor & Destructor Documentation
G4TrackStack::G4TrackStack () inline
Definition at line 48 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 48 of file G4TrackStack.hh
G4TrackStack::G4TrackStack (size_t n) inline
Definition at line 50 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 50 of file G4TrackStack.hh
G4TrackStack::~G4TrackStack ()
Definition at line 34 of file G4TrackStack.cc.
View newest version in sPHENIX GitHub at line 34 of file G4TrackStack.cc
References clearAndDestroy().
Member Function Documentation
void G4TrackStack::clearAndDestroy ()
Definition at line 39 of file G4TrackStack.cc.
View newest version in sPHENIX GitHub at line 39 of file G4TrackStack.cc
References clear().
Referenced by G4SmartTrackStack::clearAndDestroy(), G4StackManager::ClearPostponeStack(), G4StackManager::ClearUrgentStack(), G4StackManager::ClearWaitingStack(), G4StackManager::PrepareNewEvent(), G4StackManager::TransferStackedTracks(), and ~G4TrackStack().
size_t G4TrackStack::GetMaxNTrack () const inline
Definition at line 69 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 69 of file G4TrackStack.hh
Referenced by G4StackManager::~G4StackManager().
G4int G4TrackStack::GetNStick () const inline
Definition at line 72 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 72 of file G4TrackStack.hh
References nstick.
size_t G4TrackStack::GetNTrack () const inline
Definition at line 68 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 68 of file G4TrackStack.hh
Referenced by G4SmartTrackStack::dumpStatistics(), G4StackManager::GetNPostponedTrack(), G4StackManager::GetNTotalTrack(), G4StackManager::GetNUrgentTrack(), G4StackManager::GetNWaitingTrack(), G4StackManager::PrepareNewEvent(), G4SmartTrackStack::PushToStack(), G4StackManager::ReClassify(), and G4StackManager::TransferOneStackedTrack().
G4int G4TrackStack::GetSafetyValue1 () const inline
Definition at line 70 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 70 of file G4TrackStack.hh
References safetyValue1.
Referenced by G4SmartTrackStack::PushToStack().
G4int G4TrackStack::GetSafetyValue2 () const inline
Definition at line 71 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 71 of file G4TrackStack.hh
References safetyValue2.
Referenced by G4SmartTrackStack::PushToStack().
G4double G4TrackStack::getTotalEnergy (void) const
Definition at line 66 of file G4TrackStack.cc.
View newest version in sPHENIX GitHub at line 66 of file G4TrackStack.cc
Referenced by G4SmartTrackStack::dumpStatistics().
G4bool G4TrackStack::operator!= (const G4TrackStack &) const delete
G4TrackStack& G4TrackStack::operator= (const G4TrackStack &) delete
G4bool G4TrackStack::operator== (const G4TrackStack &) const delete
G4StackedTrack G4TrackStack::PopFromStack () inline
Definition at line 61 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 61 of file G4TrackStack.hh
Referenced by G4SmartTrackStack::PopFromStack(), G4StackManager::PopNextTrack(), G4StackManager::PrepareNewEvent(), G4StackManager::ReClassify(), G4StackManager::TransferOneStackedTrack(), and TransferTo().
void G4TrackStack::PushToStack (const G4StackedTrack & aStackedTrack) inline
Definition at line 59 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 59 of file G4TrackStack.hh
Referenced by G4StackManager::PrepareNewEvent(), G4StackManager::PushOneTrack(), G4SmartTrackStack::PushToStack(), G4StackManager::ReClassify(), and G4StackManager::TransferOneStackedTrack().
void G4TrackStack::SetSafetyValue2 (G4int x) inline
Definition at line 75 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 75 of file G4TrackStack.hh
References safetyValue2, and x.
void G4TrackStack::TransferTo (G4TrackStack * aStack)
Definition at line 49 of file G4TrackStack.cc.
View newest version in sPHENIX GitHub at line 49 of file G4TrackStack.cc
References clear().
Referenced by G4StackManager::PopNextTrack(), G4StackManager::PrepareNewEvent(), G4StackManager::ReClassify(), G4StackManager::TransferStackedTracks(), and G4SmartTrackStack::TransferTo().
void G4TrackStack::TransferTo (G4SmartTrackStack * aStack)
Definition at line 58 of file G4TrackStack.cc.
View newest version in sPHENIX GitHub at line 58 of file G4TrackStack.cc
References PopFromStack(), and G4SmartTrackStack::PushToStack().
Member Data Documentation
G4int G4TrackStack::nstick private
Definition at line 81 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 81 of file G4TrackStack.hh
Referenced by GetNStick().
G4int G4TrackStack::safetyValue1 private
Definition at line 79 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 79 of file G4TrackStack.hh
Referenced by GetSafetyValue1().
G4int G4TrackStack::safetyValue2 private
Definition at line 80 of file G4TrackStack.hh.
View newest version in sPHENIX GitHub at line 80 of file G4TrackStack.hh
Referenced by GetSafetyValue2(), and SetSafetyValue2().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4TrackStack.hh
geant4/tree/geant4-10.6-release/source/event/src/G4TrackStack.cc