ECCE @ EIC Software: G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration Class Reference
G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration Class Reference
Class for storing and comparing sorted nucleon configurations.
Public Types
typedef G4int NucleonItem
Public Member Functions
SortedNucleonConfiguration ()
Constructor.
SortedNucleonConfiguration (const SortedNucleonConfiguration &rhs)
Copy constructor.
~SortedNucleonConfiguration ()
Destructor.
void swap (SortedNucleonConfiguration &rhs)
Helper method for the assignment operator.
SortedNucleonConfiguration & operator= (const SortedNucleonConfiguration &rhs)
Assignment operator.
G4bool operator< (const SortedNucleonConfiguration &rhs) const
Order operator for SortedNucleonConfiguration.
void fill (NucleonItem *config, size_t n)
Fill configuration with array of NucleonItem.
Private Attributes
size_t theSize
Size of the array.
NucleonItem * nucleons
The real array.
Detailed Description
Class for storing and comparing sorted nucleon configurations.
This class is actually just a wrapper around an array of Particle* pointers. It provides a lexicographical comparison operator (SortedNucleonConfiguration::operator<) for inclusion in std::set containers.
Definition at line 243 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 243 of file G4INCLClusteringModelIntercomparison.hh
Member Typedef Documentation
typedef G4int G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::NucleonItem
Definition at line 246 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 246 of file G4INCLClusteringModelIntercomparison.hh
Constructor & Destructor Documentation
G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::SortedNucleonConfiguration () inline
Constructor.
Definition at line 249 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 249 of file G4INCLClusteringModelIntercomparison.hh
G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::SortedNucleonConfiguration (const SortedNucleonConfiguration & rhs) inline
Copy constructor.
Definition at line 252 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 252 of file G4INCLClusteringModelIntercomparison.hh
References field_utils::copy(), nucleons, and theSize.
G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::~SortedNucleonConfiguration () inline
Destructor.
Definition at line 260 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 260 of file G4INCLClusteringModelIntercomparison.hh
References nucleons.
Member Function Documentation
void G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::fill (NucleonItem * config, size_t n) inline
Fill configuration with array of NucleonItem.
Definition at line 288 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 288 of file G4INCLClusteringModelIntercomparison.hh
References field_utils::copy(), n, nucleons, and theSize.
Referenced by G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom().
G4bool G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::operator< (const SortedNucleonConfiguration & rhs) const inline
Order operator for SortedNucleonConfiguration.
The comparison is done lexicographically (i.e. from the first element to the last).
Definition at line 282 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 282 of file G4INCLClusteringModelIntercomparison.hh
References nucleons, and theSize.
SortedNucleonConfiguration& G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::operator= (const SortedNucleonConfiguration & rhs) inline
Assignment operator.
Definition at line 271 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 271 of file G4INCLClusteringModelIntercomparison.hh
References swap().
void G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::swap (SortedNucleonConfiguration & rhs) inline
Helper method for the assignment operator.
Definition at line 265 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 265 of file G4INCLClusteringModelIntercomparison.hh
References nucleons, boost::swap(), and theSize.
Referenced by operator=().
Member Data Documentation
NucleonItem* G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::nucleons private
The real array.
Definition at line 300 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 300 of file G4INCLClusteringModelIntercomparison.hh
Referenced by fill(), operator<(), SortedNucleonConfiguration(), swap(), and ~SortedNucleonConfiguration().
size_t G4INCL::ClusteringModelIntercomparison::SortedNucleonConfiguration::theSize private
Size of the array.
Definition at line 297 of file G4INCLClusteringModelIntercomparison.hh.
View newest version in sPHENIX GitHub at line 297 of file G4INCLClusteringModelIntercomparison.hh
Referenced by fill(), operator<(), SortedNucleonConfiguration(), and swap().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLClusteringModelIntercomparison.hh