ECCE @ EIC Software: ServiceProperties Class Reference
ServiceProperties Class Reference
Public Member Functions
ServiceProperties ()
ServiceProperties (const string &name, const double &rad_len_copper, const double &rad_len_aluminum, const double &rad_len_water, const double &rad_len_plastic, const double &rad_len_carbon, const double &rad_len_iron, const double &z_south, const double &z_north, const double &r_south, const double &r_north)
virtual ~ServiceProperties ()
const string get_name ()
const double get_rad_len_copper ()
const double get_rad_len_aluminum ()
const double get_rad_len_water ()
const double get_rad_len_plastic ()
const double get_rad_len_carbon ()
const double get_rad_len_iron ()
const double get_z_south ()
const double get_z_north ()
const double get_r_south ()
const double get_r_north ()
Private Attributes
const string m_name = "service"
const double m_rad_len_copper = 0.0
const double m_rad_len_aluminum = 0.0
const double m_rad_len_water = 0.0
const double m_rad_len_plastic = 0.0
const double m_rad_len_carbon = 0.0
const double m_rad_len_iron = 0.0
const double m_z_south = 0.0
const double m_z_north = 0.0
const double m_r_south = 0.0
const double m_r_north = 0.0
Detailed Description
Definition at line 23 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 23 of file G4_TrackingSupport.C
Constructor & Destructor Documentation
ServiceProperties::ServiceProperties ()
ServiceProperties::ServiceProperties (const string & name, const double & rad_len_copper, const double & rad_len_aluminum, const double & rad_len_water, const double & rad_len_plastic, const double & rad_len_carbon, const double & rad_len_iron, const double & z_south, const double & z_north, const double & r_south, const double & r_north) explicit
Definition at line 67 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 67 of file G4_TrackingSupport.C
virtual ServiceProperties::~ServiceProperties () inline virtual
Definition at line 40 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 40 of file G4_TrackingSupport.C
Member Function Documentation
const string ServiceProperties::get_name (void)
Definition at line 92 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 92 of file G4_TrackingSupport.C
References m_name.
Referenced by TrackingServiceCone(), and TrackingServiceCylinder().
const double ServiceProperties::get_r_north ()
Definition at line 102 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 102 of file G4_TrackingSupport.C
References m_r_north.
const double ServiceProperties::get_r_south ()
Definition at line 101 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 101 of file G4_TrackingSupport.C
References m_r_south.
const double ServiceProperties::get_rad_len_aluminum ()
Definition at line 94 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 94 of file G4_TrackingSupport.C
References m_rad_len_aluminum.
Referenced by get_thickness().
const double ServiceProperties::get_rad_len_carbon ()
Definition at line 97 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 97 of file G4_TrackingSupport.C
References m_rad_len_carbon.
Referenced by get_thickness().
const double ServiceProperties::get_rad_len_copper ()
Definition at line 93 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 93 of file G4_TrackingSupport.C
References m_rad_len_copper.
const double ServiceProperties::get_rad_len_iron ()
Definition at line 98 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 98 of file G4_TrackingSupport.C
References m_rad_len_iron.
Referenced by get_thickness().
const double ServiceProperties::get_rad_len_plastic ()
Definition at line 96 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 96 of file G4_TrackingSupport.C
References m_rad_len_plastic.
Referenced by get_thickness().
const double ServiceProperties::get_rad_len_water ()
Definition at line 95 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 95 of file G4_TrackingSupport.C
References m_rad_len_water.
Referenced by get_thickness().
const double ServiceProperties::get_z_north ()
Definition at line 100 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 100 of file G4_TrackingSupport.C
References m_z_north.
Referenced by TrackingServiceCone(), and TrackingServiceCylinder().
const double ServiceProperties::get_z_south ()
Definition at line 99 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 99 of file G4_TrackingSupport.C
References m_z_south.
Referenced by TrackingServiceCone(), and TrackingServiceCylinder().
Member Data Documentation
const string ServiceProperties::m_name = "service" private
Definition at line 55 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 55 of file G4_TrackingSupport.C
Referenced by get_name().
const double ServiceProperties::m_r_north = 0.0 private
Definition at line 65 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 65 of file G4_TrackingSupport.C
Referenced by get_r_north().
const double ServiceProperties::m_r_south = 0.0 private
Definition at line 64 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 64 of file G4_TrackingSupport.C
Referenced by get_r_south().
const double ServiceProperties::m_rad_len_aluminum = 0.0 private
Definition at line 57 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 57 of file G4_TrackingSupport.C
Referenced by get_rad_len_aluminum().
const double ServiceProperties::m_rad_len_carbon = 0.0 private
Definition at line 60 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 60 of file G4_TrackingSupport.C
Referenced by get_rad_len_carbon().
const double ServiceProperties::m_rad_len_copper = 0.0 private
Definition at line 56 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 56 of file G4_TrackingSupport.C
Referenced by get_rad_len_copper().
const double ServiceProperties::m_rad_len_iron = 0.0 private
Definition at line 61 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 61 of file G4_TrackingSupport.C
Referenced by get_rad_len_iron().
const double ServiceProperties::m_rad_len_plastic = 0.0 private
Definition at line 59 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 59 of file G4_TrackingSupport.C
Referenced by get_rad_len_plastic().
const double ServiceProperties::m_rad_len_water = 0.0 private
Definition at line 58 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 58 of file G4_TrackingSupport.C
Referenced by get_rad_len_water().
const double ServiceProperties::m_z_north = 0.0 private
Definition at line 63 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 63 of file G4_TrackingSupport.C
Referenced by get_z_north().
const double ServiceProperties::m_z_south = 0.0 private
Definition at line 62 of file G4_TrackingSupport.C.
View newest version in sPHENIX GitHub at line 62 of file G4_TrackingSupport.C
Referenced by get_z_south().
The documentation for this class was generated from the following file:
macros/blob/master/common/G4_TrackingSupport.C