ECCE @ EIC Software: G4GammaGeneralProcess Class Reference
G4GammaGeneralProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4GammaGeneralProcess.hh>
Public Member Functions
G4GammaGeneralProcess ()
virtual ~G4GammaGeneralProcess ()
G4bool IsApplicable (const G4ParticleDefinition &) final
void AddEmProcess (G4VEmProcess *)
void AddMMProcess (G4GammaConversionToMuons *)
void AddHadProcess (G4HadronicProcess *)
void ProcessDescription (std::ostream &outFile) const final
void PreparePhysicsTable (const G4ParticleDefinition &) final
void BuildPhysicsTable (const G4ParticleDefinition &) final
void StartTracking (G4Track *) final
G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) final
G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) final
G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) final
G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) final
const G4String & GetProcessName () const
G4int GetProcessSubType () const
G4VEmProcess * GetEmProcess (const G4String &name) final
Public Member Functions inherited from G4VEmProcess
G4VEmProcess (const G4String &name, G4ProcessType type=fElectromagnetic)
virtual ~G4VEmProcess ()
virtual void PrintInfo ()
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double ComputeCrossSectionPerAtom (G4double kineticEnergy, G4double Z, G4double A=0., G4double cut=0.0)
G4double MeanFreePath (const G4Track &track)
G4double GetLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple)
G4double GetLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple, G4double logKinEnergy)
void SetLambdaBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
void SetMinKinEnergyPrim (G4double e)
void SetMaxKinEnergy (G4double e)
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * LambdaTablePrim () const
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * SecondaryParticle () const
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t idxRegion) const
void AddEmModel (G4int, G4VEmModel *, const G4Region *region=nullptr)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
void UpdateEmModel (const G4String &, G4double, G4double)
G4int GetNumberOfModels () const
G4int GetNumberOfRegionModels (size_t couple_index) const
G4VEmModel * GetRegionModel (G4int idx, size_t couple_index) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
const G4VEmModel * GetCurrentModel () const
const G4Element * GetCurrentElement () const
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
G4double CrossSectionBiasingFactor () const
void ActivateForcedInteraction (G4double length=0.0, const G4String &r="", G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void SetEmMasterProcess (const G4VEmProcess *)
void SetIntegral (G4bool val)
void SetBuildTableFlag (G4bool val)
void CurrentSetup (const G4MaterialCutsCouple *, G4double energy)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
void InitialiseProcess (const G4ParticleDefinition *) final
G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) final
Protected Member Functions inherited from G4VEmProcess
virtual void StreamProcessInfo (std::ostream &) const
virtual G4double MinPrimaryEnergy (const G4ParticleDefinition *, const G4Material *)
G4VEmModel * SelectModel (G4double kinEnergy, size_t index)
G4PhysicsVector * LambdaPhysicsVector (const G4MaterialCutsCouple *)
G4int LambdaBinning () const
G4double MinKinEnergy () const
G4double MaxKinEnergy () const
G4double PolarAngleLimit () const
G4bool IsIntegral () const
G4double RecalculateLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple)
G4ParticleChangeForGamma * GetParticleChange ()
void SetParticle (const G4ParticleDefinition *p)
void SetSecondaryParticle (const G4ParticleDefinition *p)
size_t CurrentMaterialCutsCoupleIndex () const
const G4MaterialCutsCouple * MaterialCutsCouple () const
G4bool ApplyCuts () const
G4double GetGammaEnergyCut ()
G4double GetElectronEnergyCut ()
void SetStartFromNullFlag (G4bool val)
void SetSplineFlag (G4bool val)
const G4Element * GetTargetElement () const
const G4Isotope * GetTargetIsotope () const
Private Member Functions
G4double TotalCrossSectionPerVolume ()
G4double ComputeGeneralLambda (size_t idxe, size_t idxt)
G4double GetProbability (size_t idxt)
void SelectedProcess (const G4Track &track, G4VProcess *ptr)
G4VParticleChange * SampleSecondaries (const G4Track &, const G4Step &, G4VEmProcess *)
G4VParticleChange * SampleSecondaries (const G4Track &, const G4Step &, G4HadronicProcess *)
G4GammaGeneralProcess (G4GammaGeneralProcess &)
G4GammaGeneralProcess & operator= (const G4GammaGeneralProcess &right)
Private Attributes
G4VEmProcess * thePhotoElectric
G4VEmProcess * theCompton
G4VEmProcess * theConversionEE
G4VEmProcess * theRayleigh
G4HadronicProcess * theGammaNuclear
G4GammaConversionToMuons * theConversionMM
G4VProcess * selectedProc
G4double minPEEnergy
G4double minEEEnergy
G4double minMMEnergy
G4double peLambda
G4double preStepLogE
G4double factor
size_t nLowE
size_t nHighE
size_t idxEnergy
G4bool splineFlag
Static Private Attributes
static G4EmDataHandler * theHandler = nullptr
static const size_t nTables = 15
static G4bool theT [nTables]
static G4String nameT [nTables]
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VEmProcess
G4LossTableManager * lManager
G4EmParameters * theParameters
G4EmBiasingManager * biasManager
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theElectron
G4ParticleChangeForGamma fParticleChange
std::vector< G4DynamicParticle * > secParticles
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t currentCoupleIndex
size_t basedCoupleIndex
G4int mainSecondaries
G4int secID
G4int fluoID
G4int augerID
G4int biasID
G4bool isTheMaster
G4double mfpKinEnergy
G4double preStepKinEnergy
G4double preStepLogKinEnergy
G4double preStepLambda
Detailed Description
Definition at line 68 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 68 of file G4GammaGeneralProcess.hh
Constructor & Destructor Documentation
G4GammaGeneralProcess::G4GammaGeneralProcess () explicit
Definition at line 85 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 85 of file G4GammaGeneralProcess.cc
References factor, fGammaGeneralProcess, idxEnergy, preStepLogE, selectedProc, G4VEmProcess::SetParticle(), G4VProcess::SetProcessSubType(), G4VProcess::SetVerboseLevel(), theCompton, theConversionEE, theConversionMM, G4VEmProcess::theGamma, theGammaNuclear, thePhotoElectric, and theRayleigh.
G4GammaGeneralProcess::~G4GammaGeneralProcess () virtual
Definition at line 110 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 110 of file G4GammaGeneralProcess.cc
References G4VEmProcess::isTheMaster, and theHandler.
G4GammaGeneralProcess::G4GammaGeneralProcess (G4GammaGeneralProcess &) private
Member Function Documentation
void G4GammaGeneralProcess::AddEmProcess (G4VEmProcess * ptr)
Definition at line 129 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 129 of file G4GammaGeneralProcess.cc
References fComptonScattering, fGammaConversion, fPhotoElectricEffect, fRayleigh, G4VProcess::GetProcessSubType(), theCompton, theConversionEE, thePhotoElectric, and theRayleigh.
Referenced by G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), and G4EmStandardPhysics_option2::ConstructProcess().
void G4GammaGeneralProcess::AddHadProcess (G4HadronicProcess * ptr)
Definition at line 148 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 148 of file G4GammaGeneralProcess.cc
References theGammaNuclear.
Referenced by G4BertiniElectroNuclearBuilder::Build(), and G4EmExtraPhysics::ConstructGammaElectroNuclear().
void G4GammaGeneralProcess::AddMMProcess (G4GammaConversionToMuons * ptr)
Definition at line 141 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 141 of file G4GammaGeneralProcess.cc
References theConversionMM.
Referenced by G4EmExtraPhysics::ConstructProcess().
void G4GammaGeneralProcess::BuildPhysicsTable (const G4ParticleDefinition & part) final virtual
Reimplemented from G4VEmProcess.
Definition at line 253 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 253 of file G4GammaGeneralProcess.cc
References G4GammaConversionToMuons::BuildPhysicsTable(), G4HadronicProcess::BuildPhysicsTable(), G4VEmProcess::BuildPhysicsTable(), G4CrossSectionDataStore::ComputeCrossSection(), G4GammaConversionToMuons::ComputeMeanFreePath(), DBL_MAX, e, G4cout, G4endl, G4Log(), G4Gamma::Gamma(), G4HadronicProcess::GetCrossSectionDataStore(), G4LossTableBuilder::GetFlag(), G4VEmProcess::GetLambda(), G4EmDataHandler::GetMasterProcess(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), GetProcessName(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetTableBuilder(), G4EmDataHandler::GetTables(), G4ProductionCutsTable::GetTableSize(), incremental_prev_tag::idx, G4VEmProcess::isTheMaster, k, G4VEmProcess::lManager, material(), G4InuclParticleNames::nn, nTables, G4VEmProcess::SetEmMasterProcess(), G4DynamicParticle::SetKineticEnergy(), splineFlag, sum, theCompton, theConversionEE, theConversionMM, theGammaNuclear, theHandler, thePhotoElectric, theRayleigh, theT, and G4VProcess::verboseLevel.
G4double G4GammaGeneralProcess::ComputeGeneralLambda (size_t idxe, size_t idxt) inline private
Definition at line 186 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 186 of file G4GammaGeneralProcess.hh
References G4VEmProcess::basedCoupleIndex, factor, G4EmDataHandler::GetVector(), idxEnergy, G4PhysicsVector::LogVectorValue(), G4VEmProcess::preStepKinEnergy, preStepLogE, and theHandler.
Referenced by TotalCrossSectionPerVolume().
G4VEmProcess * G4GammaGeneralProcess::GetEmProcess (const G4String & name) final virtual
Reimplemented from G4VEmProcess.
Definition at line 796 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 796 of file G4GammaGeneralProcess.cc
References G4VProcess::GetProcessName(), theCompton, theConversionEE, thePhotoElectric, and theRayleigh.
G4double G4GammaGeneralProcess::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) final protected virtual
Reimplemented from G4VEmProcess.
Definition at line 757 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 757 of file G4GammaGeneralProcess.cc
References G4VEmProcess::MeanFreePath(), and NotForced.
G4double G4GammaGeneralProcess::GetProbability (size_t idxt) inline private
Definition at line 195 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 195 of file G4GammaGeneralProcess.hh
References G4VEmProcess::basedCoupleIndex, G4EmDataHandler::GetVector(), G4PhysicsVector::LogVectorValue(), G4VEmProcess::preStepKinEnergy, preStepLogE, theHandler, and theT.
Referenced by PostStepDoIt().
const G4String & G4GammaGeneralProcess::GetProcessName () const
Definition at line 779 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 779 of file G4GammaGeneralProcess.cc
References G4VProcess::GetProcessName(), and selectedProc.
Referenced by BuildPhysicsTable(), PreparePhysicsTable(), and RetrievePhysicsTable().
G4int G4GammaGeneralProcess::GetProcessSubType () const
Definition at line 788 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 788 of file G4GammaGeneralProcess.cc
References fGammaGeneralProcess, G4VProcess::GetProcessSubType(), and selectedProc.
void G4GammaGeneralProcess::InitialiseProcess (const G4ParticleDefinition *) final protected virtual
Implements G4VEmProcess.
Definition at line 185 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 185 of file G4GammaGeneralProcess.cc
References G4lrint(), G4ProductionCutsTable::GetProductionCutsTable(), G4LossTableManager::GetTableBuilder(), G4ProductionCutsTable::GetTableSize(), G4VEmProcess::isTheMaster, G4VEmProcess::lManager, G4EmDataHandler::MakeTable(), max, G4EmParameters::MaxKinEnergy(), minEEEnergy, G4EmParameters::MinKinEnergy(), minMMEnergy, minPEEnergy, nHighE, nLowE, nTables, G4EmParameters::NumberOfBinsPerDecade(), G4EmDataHandler::SetMasterProcess(), G4PhysicsTableHelper::SetPhysicsVector(), G4PhysicsVector::SetSpline(), splineFlag, theCompton, theConversionEE, theConversionMM, theGammaNuclear, theHandler, G4VEmProcess::theParameters, thePhotoElectric, theRayleigh, and theT.
Referenced by PreparePhysicsTable().
G4bool G4GammaGeneralProcess::IsApplicable (const G4ParticleDefinition &) final virtual
Implements G4VEmProcess.
Definition at line 122 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 122 of file G4GammaGeneralProcess.cc
G4GammaGeneralProcess& G4GammaGeneralProcess::operator= (const G4GammaGeneralProcess & right) private
G4VParticleChange * G4GammaGeneralProcess::PostStepDoIt (const G4Track & track, const G4Step & step) final virtual
Reimplemented from G4VEmProcess.
Definition at line 582 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 582 of file G4GammaGeneralProcess.cc
References G4VEmProcess::fParticleChange, G4UniformRand, GetProbability(), idxEnergy, G4ParticleChangeForGamma::InitializeForPostStep(), peLambda, G4GammaConversionToMuons::PostStepDoIt(), G4VEmProcess::preStepLambda, SampleSecondaries(), SelectedProcess(), theCompton, theConversionEE, theConversionMM, theGammaNuclear, G4VProcess::theNumberOfInteractionLengthLeft, thePhotoElectric, theRayleigh, and x.
G4double G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) final virtual
Reimplemented from G4VEmProcess.
Definition at line 483 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 483 of file G4GammaGeneralProcess.cc
References G4VEmProcess::basedCoupleIndex, G4VEmProcess::currentCouple, G4VEmProcess::currentCoupleIndex, G4VProcess::currentInteractionLength, G4VEmProcess::currentMaterial, DBL_MAX, energy, factor, G4Log(), G4UniformRand, G4Track::GetDynamicParticle(), G4MaterialCutsCouple::GetIndex(), G4Track::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4Track::GetMaterialCutsCouple(), mat, max, NotForced, G4VEmProcess::preStepKinEnergy, G4VEmProcess::preStepLambda, preStepLogE, G4VProcess::theInitialNumberOfInteractionLength, G4VProcess::theNumberOfInteractionLengthLeft, TotalCrossSectionPerVolume(), and x.
void G4GammaGeneralProcess::PreparePhysicsTable (const G4ParticleDefinition & part) final virtual
Reimplemented from G4VEmProcess.
Definition at line 155 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 155 of file G4GammaGeneralProcess.cc
References G4VEmProcess::currentCouple, G4VEmProcess::currentMaterial, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), GetProcessName(), idxEnergy, InitialiseProcess(), G4LossTableManager::IsMaster(), G4VEmProcess::isTheMaster, G4VEmProcess::lManager, G4HadronicProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VProcess::PreparePhysicsTable(), G4VEmProcess::preStepLambda, G4VEmProcess::SetParticle(), G4VProcess::SetVerboseLevel(), theCompton, theConversionEE, theConversionMM, theGammaNuclear, G4VEmProcess::theParameters, thePhotoElectric, theRayleigh, G4EmParameters::Verbose(), G4VProcess::verboseLevel, and G4EmParameters::WorkerVerbose().
void G4GammaGeneralProcess::ProcessDescription (std::ostream & outFile) const final virtual
Reimplemented from G4VEmProcess.
Definition at line 767 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 767 of file G4GammaGeneralProcess.cc
References G4VEmProcess::ProcessDescription(), G4HadronicProcess::ProcessDescription(), G4VProcess::ProcessDescription(), theCompton, theConversionEE, theConversionMM, theGammaNuclear, thePhotoElectric, and theRayleigh.
G4bool G4GammaGeneralProcess::RetrievePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii) final virtual
Reimplemented from G4VEmProcess.
Definition at line 720 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 720 of file G4GammaGeneralProcess.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetPhysicsTableFileName(), GetProcessName(), nameT, nTables, G4EmDataHandler::RetrievePhysicsTable(), G4VEmProcess::RetrievePhysicsTable(), theCompton, theConversionEE, theHandler, thePhotoElectric, theRayleigh, theT, and G4VProcess::verboseLevel.
G4VParticleChange * G4GammaGeneralProcess::SampleSecondaries (const G4Track & track, const G4Step & step, G4VEmProcess * proc) inline private
Definition at line 213 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 213 of file G4GammaGeneralProcess.hh
References G4VEmProcess::currentCouple, G4VEmProcess::CurrentSetup(), G4VEmProcess::PostStepDoIt(), G4VEmProcess::preStepKinEnergy, and SelectedProcess().
Referenced by PostStepDoIt().
G4VParticleChange * G4GammaGeneralProcess::SampleSecondaries (const G4Track & track, const G4Step & step, G4HadronicProcess * proc) private
Definition at line 676 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 676 of file G4GammaGeneralProcess.cc
References G4CrossSectionDataStore::ComputeCrossSection(), G4HadronicProcess::GetCrossSectionDataStore(), G4Track::GetDynamicParticle(), G4Track::GetMaterial(), G4HadronicProcess::PostStepDoIt(), SelectedProcess(), and theGammaNuclear.
void G4GammaGeneralProcess::SelectedProcess (const G4Track & track, G4VProcess * ptr) inline private
Definition at line 204 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 204 of file G4GammaGeneralProcess.hh
References selectedProc, and track.
Referenced by PostStepDoIt(), and SampleSecondaries().
void G4GammaGeneralProcess::StartTracking (G4Track *) final virtual
Reimplemented from G4VEmProcess.
Definition at line 475 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 475 of file G4GammaGeneralProcess.cc
References G4VEmProcess::currentMaterial, and G4VProcess::theNumberOfInteractionLengthLeft.
G4bool G4GammaGeneralProcess::StorePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii = false) final virtual
Reimplemented from G4VEmProcess.
Definition at line 687 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 687 of file G4GammaGeneralProcess.cc
References G4VProcess::GetPhysicsTableFileName(), G4VEmProcess::isTheMaster, nameT, nTables, G4EmDataHandler::StorePhysicsTable(), G4VEmProcess::StorePhysicsTable(), theCompton, theConversionEE, theHandler, thePhotoElectric, theRayleigh, and theT.
G4double G4GammaGeneralProcess::TotalCrossSectionPerVolume () private
Definition at line 543 of file G4GammaGeneralProcess.cc.
View newest version in sPHENIX GitHub at line 543 of file G4GammaGeneralProcess.cc
References ComputeGeneralLambda(), Acts::VectorHelpers::cross(), G4VEmProcess::currentCouple, G4VEmProcess::GetLambda(), minEEEnergy, minMMEnergy, minPEEnergy, peLambda, G4VEmProcess::preStepKinEnergy, preStepLogE, and thePhotoElectric.
Referenced by PostStepGetPhysicalInteractionLength().
Member Data Documentation
G4double G4GammaGeneralProcess::factor private
Definition at line 175 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 175 of file G4GammaGeneralProcess.hh
Referenced by ComputeGeneralLambda(), G4GammaGeneralProcess(), and PostStepGetPhysicalInteractionLength().
size_t G4GammaGeneralProcess::idxEnergy private
Definition at line 179 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 179 of file G4GammaGeneralProcess.hh
Referenced by ComputeGeneralLambda(), G4GammaGeneralProcess(), PostStepDoIt(), and PreparePhysicsTable().
G4double G4GammaGeneralProcess::minEEEnergy private
Definition at line 171 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 171 of file G4GammaGeneralProcess.hh
Referenced by InitialiseProcess(), and TotalCrossSectionPerVolume().
G4double G4GammaGeneralProcess::minMMEnergy private
Definition at line 172 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 172 of file G4GammaGeneralProcess.hh
Referenced by InitialiseProcess(), and TotalCrossSectionPerVolume().
G4double G4GammaGeneralProcess::minPEEnergy private
Definition at line 170 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 170 of file G4GammaGeneralProcess.hh
Referenced by InitialiseProcess(), and TotalCrossSectionPerVolume().
G4String G4GammaGeneralProcess::nameT static private
Initial value:
=
  {"0","1","2","3","4","5","6","7","8",
   "9","10","11","12","13","14"}
Definition at line 160 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 160 of file G4GammaGeneralProcess.hh
Referenced by RetrievePhysicsTable(), and StorePhysicsTable().
size_t G4GammaGeneralProcess::nHighE private
Definition at line 178 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 178 of file G4GammaGeneralProcess.hh
Referenced by InitialiseProcess().
size_t G4GammaGeneralProcess::nLowE private
Definition at line 177 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 177 of file G4GammaGeneralProcess.hh
Referenced by InitialiseProcess().
const size_t G4GammaGeneralProcess::nTables = 15 static private
Definition at line 158 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 158 of file G4GammaGeneralProcess.hh
Referenced by BuildPhysicsTable(), InitialiseProcess(), RetrievePhysicsTable(), and StorePhysicsTable().
G4double G4GammaGeneralProcess::peLambda private
Definition at line 173 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 173 of file G4GammaGeneralProcess.hh
Referenced by PostStepDoIt(), and TotalCrossSectionPerVolume().
G4double G4GammaGeneralProcess::preStepLogE private
Definition at line 174 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 174 of file G4GammaGeneralProcess.hh
Referenced by ComputeGeneralLambda(), G4GammaGeneralProcess(), GetProbability(), PostStepGetPhysicalInteractionLength(), and TotalCrossSectionPerVolume().
G4VProcess* G4GammaGeneralProcess::selectedProc private
Definition at line 168 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 168 of file G4GammaGeneralProcess.hh
Referenced by G4GammaGeneralProcess(), GetProcessName(), GetProcessSubType(), and SelectedProcess().
G4bool G4GammaGeneralProcess::splineFlag private
Definition at line 180 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 180 of file G4GammaGeneralProcess.hh
Referenced by BuildPhysicsTable(), and InitialiseProcess().
G4VEmProcess* G4GammaGeneralProcess::theCompton private
Definition at line 163 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 163 of file G4GammaGeneralProcess.hh
Referenced by AddEmProcess(), BuildPhysicsTable(), G4GammaGeneralProcess(), GetEmProcess(), InitialiseProcess(), PostStepDoIt(), PreparePhysicsTable(), ProcessDescription(), RetrievePhysicsTable(), and StorePhysicsTable().
G4VEmProcess* G4GammaGeneralProcess::theConversionEE private
Definition at line 164 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 164 of file G4GammaGeneralProcess.hh
Referenced by AddEmProcess(), BuildPhysicsTable(), G4GammaGeneralProcess(), GetEmProcess(), InitialiseProcess(), PostStepDoIt(), PreparePhysicsTable(), ProcessDescription(), RetrievePhysicsTable(), and StorePhysicsTable().
G4GammaConversionToMuons* G4GammaGeneralProcess::theConversionMM private
Definition at line 167 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 167 of file G4GammaGeneralProcess.hh
Referenced by AddMMProcess(), BuildPhysicsTable(), G4GammaGeneralProcess(), InitialiseProcess(), PostStepDoIt(), PreparePhysicsTable(), and ProcessDescription().
G4HadronicProcess* G4GammaGeneralProcess::theGammaNuclear private
Definition at line 166 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 166 of file G4GammaGeneralProcess.hh
Referenced by AddHadProcess(), BuildPhysicsTable(), G4GammaGeneralProcess(), InitialiseProcess(), PostStepDoIt(), PreparePhysicsTable(), ProcessDescription(), and SampleSecondaries().
G4EmDataHandler * G4GammaGeneralProcess::theHandler = nullptr static private
Definition at line 157 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 157 of file G4GammaGeneralProcess.hh
Referenced by BuildPhysicsTable(), ComputeGeneralLambda(), GetProbability(), InitialiseProcess(), RetrievePhysicsTable(), StorePhysicsTable(), and ~G4GammaGeneralProcess().
G4VEmProcess* G4GammaGeneralProcess::thePhotoElectric private
Definition at line 162 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 162 of file G4GammaGeneralProcess.hh
Referenced by AddEmProcess(), BuildPhysicsTable(), G4GammaGeneralProcess(), GetEmProcess(), InitialiseProcess(), PostStepDoIt(), PreparePhysicsTable(), ProcessDescription(), RetrievePhysicsTable(), StorePhysicsTable(), and TotalCrossSectionPerVolume().
G4VEmProcess* G4GammaGeneralProcess::theRayleigh private
Definition at line 165 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 165 of file G4GammaGeneralProcess.hh
Referenced by AddEmProcess(), BuildPhysicsTable(), G4GammaGeneralProcess(), GetEmProcess(), InitialiseProcess(), PostStepDoIt(), PreparePhysicsTable(), ProcessDescription(), RetrievePhysicsTable(), and StorePhysicsTable().
G4bool G4GammaGeneralProcess::theT static private
Initial value:
=
  {true,false,true,true,false,false,true,true,true,
   false,true,true,true,false,false}
Definition at line 159 of file G4GammaGeneralProcess.hh.
View newest version in sPHENIX GitHub at line 159 of file G4GammaGeneralProcess.hh
Referenced by BuildPhysicsTable(), GetProbability(), InitialiseProcess(), RetrievePhysicsTable(), and StorePhysicsTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4GammaGeneralProcess.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/src/G4GammaGeneralProcess.cc