ECCE @ EIC Software: CLHEP::Ranlux64Engine Class Reference
CLHEP::Ranlux64Engine Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/Ranlux64Engine.h>
Public Member Functions
Ranlux64Engine (std::istream &is)
Ranlux64Engine ()
Ranlux64Engine (long seed, int lux=1)
Ranlux64Engine (int rowIndex, int colIndex, int lux)
virtual ~Ranlux64Engine ()
double flat ()
void flatArray (const int size, double *vect)
void setSeed (long seed, int lux=1)
void setSeeds (const long *seeds, int lux=1)
void saveStatus (const char filename[]="Ranlux64.conf") const
void restoreStatus (const char filename[]="Ranlux64.conf")
void showStatus () const
int getLuxury () const
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
virtual std::istream & getState (std::istream &is)
std::string name () const
std::vector< unsigned long > put () const
bool get (const std::vector< unsigned long > &v)
bool getState (const std::vector< unsigned long > &v)
Public Member Functions inherited from CLHEP::HepRandomEngine
HepRandomEngine ()
virtual ~HepRandomEngine ()
bool operator== (const HepRandomEngine &engine)
bool operator!= (const HepRandomEngine &engine)
long getSeed () const
const long * getSeeds () const
virtual operator double ()
virtual operator float ()
virtual operator unsigned int ()
Static Public Member Functions
static std::string beginTag ()
static std::string engineName ()
Static Public Member Functions inherited from CLHEP::HepRandomEngine
static std::string beginTag ()
static HepRandomEngine * newEngine (std::istream &is)
static HepRandomEngine * newEngine (const std::vector< unsigned long > &v)
Static Public Attributes
static const unsigned int VECTOR_STATE_SIZE = 30
Private Member Functions
void update ()
void advance (int dozens)
Private Attributes
int pDiscard
int pDozens
int endIters
int luxury
int index
double randoms [12]
double carry
Additional Inherited Members
Static Protected Member Functions inherited from CLHEP::HepRandomEngine
static double exponent_bit_32 ()
static double mantissa_bit_12 ()
static double mantissa_bit_24 ()
static double mantissa_bit_32 ()
static double twoToMinus_32 ()
static double twoToMinus_48 ()
static double twoToMinus_49 ()
static double twoToMinus_53 ()
static double nearlyTwoToMinus_54 ()
static bool checkFile (std::istream &file, const std::string &filename, const std::string &classname, const std::string &methodname)
Protected Attributes inherited from CLHEP::HepRandomEngine
long theSeed
const long * theSeeds
Detailed Description
Author
Definition at line 48 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 48 of file Ranlux64Engine.h
Constructor & Destructor Documentation
CLHEP::Ranlux64Engine::Ranlux64Engine (std::istream & is)
Definition at line 148 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 148 of file Ranlux64Engine.cc
CLHEP::Ranlux64Engine::Ranlux64Engine ()
Definition at line 104 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 104 of file Ranlux64Engine.cc
References kdfinder::abs(), advance(), CLHEP::HepRandom::getTheTableSeeds(), luxury, mask, and setSeeds().
CLHEP::Ranlux64Engine::Ranlux64Engine (long seed, int lux = 1)
Definition at line 124 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 124 of file Ranlux64Engine.cc
References advance(), CLHEP::lux, luxury, seed, and setSeeds().
CLHEP::Ranlux64Engine::Ranlux64Engine (int rowIndex, int colIndex, int lux)
Definition at line 134 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 134 of file Ranlux64Engine.cc
References kdfinder::abs(), CLHEP::HepRandom::getTheTableSeeds(), CLHEP::lux, luxury, mask, and setSeeds().
CLHEP::Ranlux64Engine::~Ranlux64Engine () virtual
Definition at line 154 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 154 of file Ranlux64Engine.cc
Member Function Documentation
void CLHEP::Ranlux64Engine::advance (int dozens) private
Definition at line 256 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 256 of file Ranlux64Engine.cc
References carry, k, one, randoms, CLHEP::HepRandomEngine::twoToMinus_48(), y1, y2, y3, and zero.
Referenced by Ranlux64Engine(), and update().
std::string CLHEP::Ranlux64Engine::beginTag () static
Definition at line 637 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 637 of file Ranlux64Engine.cc
static std::string CLHEP::Ranlux64Engine::engineName () inline static
Definition at line 91 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 91 of file Ranlux64Engine.h
Referenced by restoreStatus().
double CLHEP::Ranlux64Engine::flat () virtual
Implements CLHEP::HepRandomEngine.
Definition at line 156 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 156 of file Ranlux64Engine.cc
References index, randoms, CLHEP::HepRandomEngine::twoToMinus_49(), and update().
Referenced by flatArray().
void CLHEP::Ranlux64Engine::flatArray (const int size, double * vect) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 373 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 373 of file Ranlux64Engine.cc
References flat().
std::istream & CLHEP::Ranlux64Engine::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 619 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 619 of file Ranlux64Engine.cc
References getState(), and CLHEP::MarkerLen.
bool CLHEP::Ranlux64Engine::get (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 683 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 683 of file Ranlux64Engine.cc
References getState().
int CLHEP::Ranlux64Engine::getLuxury () const inline
Definition at line 82 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 82 of file Ranlux64Engine.h
References luxury.
Referenced by G4WorkerRunManager::G4WorkerRunManager(), and G4UserWorkerThreadInitialization::SetupRNGEngine().
std::istream & CLHEP::Ranlux64Engine::getState (std::istream & is) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 641 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 641 of file Ranlux64Engine.cc
References carry, endIters, index, luxury, CLHEP::MarkerLen, pDiscard, pDozens, CLHEP::possibleKeywordInput(), randoms, CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
Referenced by get(), and restoreStatus().
bool CLHEP::Ranlux64Engine::getState (const std::vector< unsigned long > & v) virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 692 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 692 of file Ranlux64Engine.cc
References carry, index, CLHEP::DoubConv::longs2double(), luxury, pDiscard, randoms, t, and VECTOR_STATE_SIZE.
std::string CLHEP::Ranlux64Engine::name () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 102 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 102 of file Ranlux64Engine.cc
std::ostream & CLHEP::Ranlux64Engine::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 592 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 592 of file Ranlux64Engine.cc
References put(), and v.
std::vector< unsigned long > CLHEP::Ranlux64Engine::put () const virtual
Reimplemented from CLHEP::HepRandomEngine.
Definition at line 603 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 603 of file Ranlux64Engine.cc
References carry, CLHEP::DoubConv::dto2longs(), index, luxury, pDiscard, randoms, t, and v.
Referenced by put(), and saveStatus().
void CLHEP::Ranlux64Engine::restoreStatus (const char filename[] = "Ranlux64.conf") virtual
Implements CLHEP::HepRandomEngine.
Definition at line 539 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 539 of file Ranlux64Engine.cc
References carry, CLHEP::HepRandomEngine::checkFile(), endIters, engineName(), getState(), in, index, luxury, pDiscard, pDozens, CLHEP::possibleKeywordInput(), randoms, CLHEP::HepRandomEngine::theSeed, v, and VECTOR_STATE_SIZE.
void CLHEP::Ranlux64Engine::saveStatus (const char filename[] = "Ranlux64.conf") const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 527 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 527 of file Ranlux64Engine.cc
References put(), and v.
void CLHEP::Ranlux64Engine::setSeed (long seed, int lux = 1) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 379 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 379 of file Ranlux64Engine.cc
References carry, endIters, index, luxury, pDiscard, pDozens, randoms, seed, CLHEP::HepRandomEngine::theSeed, CLHEP::HepRandomEngine::twoToMinus_32(), and CLHEP::HepRandomEngine::twoToMinus_48().
Referenced by setSeeds().
void CLHEP::Ranlux64Engine::setSeeds (const long * seeds, int lux = 1) virtual
Implements CLHEP::HepRandomEngine.
Definition at line 454 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 454 of file Ranlux64Engine.cc
References carry, endIters, index, luxury, pDiscard, pDozens, randoms, setSeed(), CLHEP::HepRandomEngine::theSeed, CLHEP::HepRandomEngine::theSeeds, CLHEP::HepRandomEngine::twoToMinus_32(), and CLHEP::HepRandomEngine::twoToMinus_48().
Referenced by Ranlux64Engine().
void CLHEP::Ranlux64Engine::showStatus () const virtual
Implements CLHEP::HepRandomEngine.
Definition at line 576 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 576 of file Ranlux64Engine.cc
References carry, index, luxury, pDiscard, randoms, and CLHEP::HepRandomEngine::theSeed.
void CLHEP::Ranlux64Engine::update () private
Definition at line 166 of file Ranlux64Engine.cc.
View newest version in sPHENIX GitHub at line 166 of file Ranlux64Engine.cc
References advance(), carry, endIters, index, CLHEP::m, CLHEP::ns, pDozens, randoms, CLHEP::HepRandomEngine::twoToMinus_48(), and y1.
Referenced by flat().
Member Data Documentation
double CLHEP::Ranlux64Engine::carry private
Definition at line 111 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 111 of file Ranlux64Engine.h
Referenced by advance(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), showStatus(), and update().
int CLHEP::Ranlux64Engine::endIters private
Definition at line 106 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 106 of file Ranlux64Engine.h
Referenced by getState(), restoreStatus(), setSeed(), setSeeds(), and update().
int CLHEP::Ranlux64Engine::index private
Definition at line 109 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 109 of file Ranlux64Engine.h
Referenced by flat(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), showStatus(), and update().
int CLHEP::Ranlux64Engine::luxury private
Definition at line 107 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 107 of file Ranlux64Engine.h
Referenced by getLuxury(), getState(), put(), Ranlux64Engine(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
int CLHEP::Ranlux64Engine::pDiscard private
Definition at line 104 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 104 of file Ranlux64Engine.h
Referenced by getState(), put(), restoreStatus(), setSeed(), setSeeds(), and showStatus().
int CLHEP::Ranlux64Engine::pDozens private
Definition at line 105 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 105 of file Ranlux64Engine.h
Referenced by getState(), restoreStatus(), setSeed(), setSeeds(), and update().
double CLHEP::Ranlux64Engine::randoms[12] private
Definition at line 110 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 110 of file Ranlux64Engine.h
Referenced by advance(), flat(), getState(), put(), restoreStatus(), setSeed(), setSeeds(), showStatus(), and update().
const unsigned int CLHEP::Ranlux64Engine::VECTOR_STATE_SIZE = 30 static
Definition at line 97 of file Ranlux64Engine.h.
View newest version in sPHENIX GitHub at line 97 of file Ranlux64Engine.h
Referenced by getState(), and restoreStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/Ranlux64Engine.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/Ranlux64Engine.cc