ECCE @ EIC Software: B3StackingAction Class Reference
B3StackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/include/B3StackingAction.hh>
Public Member Functions
B3StackingAction ()
virtual ~B3StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
B3StackingAction ()
virtual ~B3StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Stacking action class : manage the newly generated particles
One wishes do not track secondary neutrino.Therefore one kills it immediately, before created particles will put in a stack.
Definition at line 41 of file B3StackingAction.hh.
View newest version in sPHENIX GitHub at line 41 of file B3StackingAction.hh
Constructor & Destructor Documentation
B3StackingAction::B3StackingAction ()
Definition at line 37 of file B3StackingAction.cc.
View newest version in sPHENIX GitHub at line 37 of file B3StackingAction.cc
B3StackingAction::~B3StackingAction () virtual
Definition at line 42 of file B3StackingAction.cc.
View newest version in sPHENIX GitHub at line 42 of file B3StackingAction.cc
B3StackingAction::B3StackingAction ()
virtual B3StackingAction::~B3StackingAction () virtual
Member Function Documentation
G4ClassificationOfNewTrack B3StackingAction::ClassifyNewTrack (const G4Track * track) virtual
Reimplemented from G4UserStackingAction.
Definition at line 48 of file B3StackingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file B3StackingAction.cc
References fKill, fUrgent, G4Track::GetDefinition(), G4Track::GetParentID(), and G4NeutrinoE::NeutrinoE().
virtual G4ClassificationOfNewTrack B3StackingAction::ClassifyNewTrack (const G4Track *) virtual
Reimplemented from G4UserStackingAction.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/include/B3StackingAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/include/B3StackingAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/src/B3StackingAction.cc
geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/src/B3StackingAction.cc