ECCE @ EIC Software: G4H1Messenger Class Reference
G4H1Messenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4H1Messenger.hh>
Public Member Functions
G4H1Messenger (G4VAnalysisManager *manager)
virtual ~G4H1Messenger ()
virtual void SetNewValue (G4UIcommand *command, G4String value) final
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void CreateH1Cmd ()
void SetH1Cmd ()
Private Attributes
G4VAnalysisManager * fManager
Associated class.
std::unique_ptr
< G4AnalysisMessengerHelper > fHelper
std::unique_ptr< G4UIdirectory > fDirectory
std::unique_ptr< G4UIcommand > fCreateH1Cmd
std::unique_ptr< G4UIcommand > fSetH1Cmd
std::unique_ptr< G4UIcommand > fSetH1XCmd
std::unique_ptr< G4UIcommand > fSetH1TitleCmd
std::unique_ptr< G4UIcommand > fSetH1XAxisCmd
std::unique_ptr< G4UIcommand > fSetH1YAxisCmd
std::unique_ptr< G4UIcommand > fSetH1XAxisLogCmd
std::unique_ptr< G4UIcommand > fSetH1YAxisLogCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 49 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 49 of file G4H1Messenger.hh
Constructor & Destructor Documentation
G4H1Messenger::G4H1Messenger (G4VAnalysisManager * manager) explicit
Definition at line 49 of file G4H1Messenger.cc.
View newest version in sPHENIX GitHub at line 49 of file G4H1Messenger.cc
References CreateH1Cmd(), fDirectory, fHelper, fSetH1TitleCmd, fSetH1XAxisCmd, fSetH1XAxisLogCmd, fSetH1XCmd, fSetH1YAxisCmd, fSetH1YAxisLogCmd, and SetH1Cmd().
G4H1Messenger::~G4H1Messenger () virtual
Definition at line 78 of file G4H1Messenger.cc.
View newest version in sPHENIX GitHub at line 78 of file G4H1Messenger.cc
Member Function Documentation
void G4H1Messenger::CreateH1Cmd () private
Definition at line 86 of file G4H1Messenger.cc.
View newest version in sPHENIX GitHub at line 86 of file G4H1Messenger.cc
References fCreateH1Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4H1Messenger().
void G4H1Messenger::SetH1Cmd () private
Definition at line 145 of file G4H1Messenger.cc.
View newest version in sPHENIX GitHub at line 145 of file G4H1Messenger.cc
References fSetH1Cmd, G4State_Idle, and G4State_PreInit.
Referenced by G4H1Messenger().
void G4H1Messenger::SetNewValue (G4UIcommand * command, G4String value) final virtual
Reimplemented from G4UImessenger.
Definition at line 199 of file G4H1Messenger.cc.
View newest version in sPHENIX GitHub at line 199 of file G4H1Messenger.cc
References G4UIcommand::ConvertToBool(), G4UIcommand::ConvertToInt(), G4VAnalysisManager::CreateH1(), fCreateH1Cmd, fHelper, fManager, G4AnalysisMessengerHelper::BinData::fNbins, G4AnalysisMessengerHelper::BinData::fSbinScheme, fSetH1Cmd, fSetH1TitleCmd, fSetH1XAxisCmd, fSetH1XAxisLogCmd, fSetH1XCmd, fSetH1YAxisCmd, fSetH1YAxisLogCmd, G4AnalysisMessengerHelper::BinData::fSfcn, G4AnalysisMessengerHelper::BinData::fSunit, G4AnalysisMessengerHelper::BinData::fVmax, G4AnalysisMessengerHelper::BinData::fVmin, G4UIcommand::GetParameterEntries(), G4Analysis::GetUnitValue(), Dataset::parameters, G4VAnalysisManager::SetH1(), G4VAnalysisManager::SetH1Title(), G4VAnalysisManager::SetH1XAxisIsLog(), G4VAnalysisManager::SetH1XAxisTitle(), G4VAnalysisManager::SetH1YAxisIsLog(), G4VAnalysisManager::SetH1YAxisTitle(), title(), G4Analysis::Tokenize(), and xaxis.
Member Data Documentation
std::unique_ptr<G4UIcommand> G4H1Messenger::fCreateH1Cmd private
Definition at line 66 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4H1Messenger.hh
Referenced by CreateH1Cmd(), and SetNewValue().
std::unique_ptr<G4UIdirectory> G4H1Messenger::fDirectory private
Definition at line 64 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4H1Messenger.hh
Referenced by G4H1Messenger().
std::unique_ptr<G4AnalysisMessengerHelper> G4H1Messenger::fHelper private
Definition at line 63 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4H1Messenger.hh
Referenced by G4H1Messenger(), and SetNewValue().
G4VAnalysisManager* G4H1Messenger::fManager private
Associated class.
Definition at line 62 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4H1Messenger.hh
Referenced by SetNewValue().
std::unique_ptr<G4UIcommand> G4H1Messenger::fSetH1Cmd private
Definition at line 67 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4H1Messenger.hh
Referenced by SetH1Cmd(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H1Messenger::fSetH1TitleCmd private
Definition at line 69 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4H1Messenger.hh
Referenced by G4H1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H1Messenger::fSetH1XAxisCmd private
Definition at line 70 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4H1Messenger.hh
Referenced by G4H1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H1Messenger::fSetH1XAxisLogCmd private
Definition at line 72 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4H1Messenger.hh
Referenced by G4H1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H1Messenger::fSetH1XCmd private
Definition at line 68 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4H1Messenger.hh
Referenced by G4H1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H1Messenger::fSetH1YAxisCmd private
Definition at line 71 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4H1Messenger.hh
Referenced by G4H1Messenger(), and SetNewValue().
std::unique_ptr<G4UIcommand> G4H1Messenger::fSetH1YAxisLogCmd private
Definition at line 73 of file G4H1Messenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4H1Messenger.hh
Referenced by G4H1Messenger(), and SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4H1Messenger.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4H1Messenger.cc