ECCE @ EIC Software: G4DecayTable Class Reference
G4DecayTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4DecayTable.hh>
Public Types
typedef std::vector
< G4VDecayChannel * > G4VDecayChannelVector
Public Member Functions
G4DecayTable ()
~G4DecayTable ()
G4bool operator== (const G4DecayTable &right) const
G4bool operator!= (const G4DecayTable &right) const
void Insert (G4VDecayChannel *aChannel)
G4int entries () const
G4VDecayChannel * SelectADecayChannel (G4double parentMass=-1.)
G4VDecayChannel * GetDecayChannel (G4int index) const
G4VDecayChannel * operator[] (G4int index)
void DumpInfo () const
Private Member Functions
G4DecayTable (const G4DecayTable &)
G4DecayTable & operator= (const G4DecayTable &)
Private Attributes
G4ParticleDefinition * parent
G4VDecayChannelVector * channels
Detailed Description
Definition at line 49 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 49 of file G4DecayTable.hh
Member Typedef Documentation
typedef std::vector<G4VDecayChannel*> G4DecayTable::G4VDecayChannelVector
Definition at line 57 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 57 of file G4DecayTable.hh
Constructor & Destructor Documentation
G4DecayTable::G4DecayTable ()
Definition at line 42 of file G4DecayTable.cc.
View newest version in sPHENIX GitHub at line 42 of file G4DecayTable.cc
References channels.
G4DecayTable::~G4DecayTable ()
Definition at line 48 of file G4DecayTable.cc.
View newest version in sPHENIX GitHub at line 48 of file G4DecayTable.cc
References channels, and parent.
G4DecayTable::G4DecayTable (const G4DecayTable &) inline private
Definition at line 67 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 67 of file G4DecayTable.hh
Member Function Documentation
void G4DecayTable::DumpInfo () const
Definition at line 119 of file G4DecayTable.cc.
View newest version in sPHENIX GitHub at line 119 of file G4DecayTable.cc
References channels, G4cout, G4endl, G4ParticleDefinition::GetParticleName(), and parent.
Referenced by G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4IsotopeProperty::DumpInfo(), G4ParticleDefinition::DumpTable(), export_G4DecayTable(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), and G4DecayTableMessenger::SetNewValue().
G4int G4DecayTable::entries () const inline
Definition at line 99 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 99 of file G4DecayTable.hh
References channels.
Referenced by G4DecayWithSpin::AtRestDoIt(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4IonTable::CreateIon(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4KineticTrack::G4KineticTrack(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4SampleResonance::GetMinimumMass(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4TextPPRetriever::ModifyPropertyTable(), G4DecayWithSpin::PostStepDoIt(), and G4MTRunManagerKernel::SetUpDecayChannels().
G4VDecayChannel * G4DecayTable::GetDecayChannel (G4int index) const inline
Definition at line 112 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 112 of file G4DecayTable.hh
References channels.
Referenced by G4DecayWithSpin::AtRestDoIt(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4IonTable::CreateIon(), G4KineticTrack::Decay(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4KineticTrack::G4KineticTrack(), G4TextPPReporter::GeneratePropertyTable(), G4HtmlPPReporter::GeneratePropertyTable(), G4SampleResonance::GetMinimumMass(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4TextPPRetriever::ModifyPropertyTable(), G4DecayWithSpin::PostStepDoIt(), G4DecayTableMessenger::SetCurrentParticle(), G4DecayTableMessenger::SetNewValue(), and G4MTRunManagerKernel::SetUpDecayChannels().
void G4DecayTable::Insert (G4VDecayChannel * aChannel)
Definition at line 61 of file G4DecayTable.cc.
View newest version in sPHENIX GitHub at line 61 of file G4DecayTable.cc
References channels, G4cout, G4endl, G4VDecayChannel::GetBR(), G4VDecayChannel::GetParent(), G4ParticleDefinition::GetParticleName(), and parent.
Referenced by G4ExcitedMesonConstructor::Add2EtaMode(), G4ExcitedMesonConstructor::Add2KMode(), G4ExcitedMesonConstructor::Add2KPiMode(), G4ExcitedMesonConstructor::Add2PiEtaMode(), G4ExcitedMesonConstructor::Add2PiMode(), G4ExcitedMesonConstructor::Add2PiOmegaMode(), G4ExcitedMesonConstructor::Add2PiRhoMode(), G4ExcitedMesonConstructor::Add3PiMode(), G4ExcitedMesonConstructor::Add4PiMode(), G4ExcitedSigmaConstructor::AddDeltaKMode(), G4ExcitedDeltaConstructor::AddDeltaPiMode(), G4ExcitedNucleonConstructor::AddDeltaPiMode(), G4ExcitedMesonConstructor::AddKEtaMode(), G4ExcitedMesonConstructor::AddKKStarMode(), G4ExcitedMesonConstructor::AddKOmegaMode(), G4ExcitedMesonConstructor::AddKPiMode(), G4ExcitedMesonConstructor::AddKRhoMode(), G4ExcitedMesonConstructor::AddKStar2PiMode(), G4ExcitedMesonConstructor::AddKStarPiMode(), G4ExcitedMesonConstructor::AddKTwoPiMode(), G4ExcitedLambdaConstructor::AddLambdaEtaMode(), G4ExcitedLambdaConstructor::AddLambdaGammaMode(), G4ExcitedXiConstructor::AddLambdaKMode(), G4ExcitedNucleonConstructor::AddLambdaKMode(), G4ExcitedLambdaConstructor::AddLambdaOmegaMode(), G4ExcitedSigmaConstructor::AddLambdaPiMode(), G4ExcitedSigmaConstructor::AddLambdaStarPiMode(), G4ExcitedNucleonConstructor::AddN2PiMode(), G4ExcitedNucleonConstructor::AddNEtaMode(), G4ExcitedNucleonConstructor::AddNGammaMode(), G4ExcitedDeltaConstructor::AddNGammaMode(), G4ExcitedSigmaConstructor::AddNKMode(), G4ExcitedLambdaConstructor::AddNKMode(), G4ExcitedSigmaConstructor::AddNKStarMode(), G4ExcitedLambdaConstructor::AddNKStarMode(), G4ExcitedNucleonConstructor::AddNOmegaMode(), G4ExcitedNucleonConstructor::AddNPiMode(), G4ExcitedDeltaConstructor::AddNPiMode(), G4ExcitedDeltaConstructor::AddNRhoMode(), G4ExcitedNucleonConstructor::AddNRhoMode(), G4ExcitedDeltaConstructor::AddNStarPiMode(), G4ExcitedNucleonConstructor::AddNStarPiMode(), G4ExcitedMesonConstructor::AddPiA2Mode(), G4ExcitedMesonConstructor::AddPiEtaMode(), G4ExcitedMesonConstructor::AddPiF0Mode(), G4ExcitedMesonConstructor::AddPiF2Mode(), G4ExcitedMesonConstructor::AddPiGammaMode(), G4ExcitedMesonConstructor::AddPiOmegaMode(), G4ExcitedMesonConstructor::AddPiRhoMode(), G4ExcitedMesonConstructor::AddRhoEtaMode(), G4ExcitedMesonConstructor::AddRhoGammaMode(), G4ExcitedSigmaConstructor::AddSigmaEtaMode(), G4ExcitedXiConstructor::AddSigmaKMode(), G4ExcitedSigmaConstructor::AddSigmaPiMode(), G4ExcitedLambdaConstructor::AddSigmaPiMode(), G4ExcitedLambdaConstructor::AddSigmaStarPiMode(), G4ExcitedSigmaConstructor::AddSigmaStarPiMode(), G4ExcitedXiConstructor::AddXiGammaMode(), G4ExcitedXiConstructor::AddXiPiMode(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4ShortLivedConstructor::ConstructBaryons(), G4ShortLivedConstructor::ConstructMesons(), G4EtaPrime::Definition(), G4KaonZeroLong::Definition(), G4TauMinus::Definition(), G4AntiSigmaPlus::Definition(), G4AntiSigmacPlus::Definition(), G4KaonMinus::Definition(), G4AntiNeutron::Definition(), G4Lambda::Definition(), G4KaonPlus::Definition(), G4Eta::Definition(), G4KaonZeroShort::Definition(), G4MuonMinus::Definition(), G4AntiSigmaMinus::Definition(), G4OmegaMinus::Definition(), G4SigmacPlusPlus::Definition(), G4AntiKaonZero::Definition(), G4AntiOmegaMinus::Definition(), G4SigmaMinus::Definition(), G4XiZero::Definition(), G4SigmacPlus::Definition(), G4AntiSigmacPlusPlus::Definition(), G4MuonPlus::Definition(), G4TauPlus::Definition(), G4PionMinus::Definition(), G4SigmaPlus::Definition(), G4AntiSigmacZero::Definition(), G4PionZero::Definition(), G4AntiXiMinus::Definition(), G4AntiLambda::Definition(), G4SigmacZero::Definition(), G4KaonZero::Definition(), G4PionPlus::Definition(), G4AntiXiZero::Definition(), G4SigmaZero::Definition(), G4XiMinus::Definition(), G4AntiSigmaZero::Definition(), G4SigmabPlus::Definition(), G4AntiSigmabMinus::Definition(), G4Neutron::Definition(), G4SigmabMinus::Definition(), G4AntiSigmabZero::Definition(), G4AntiSigmabPlus::Definition(), G4SigmabZero::Definition(), G4LDMPhoton::LDMPhotonDefinition(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), and F04PhysicsListMessenger::SetNewValue().
G4bool G4DecayTable::operator!= (const G4DecayTable & right) const inline
Definition at line 73 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 73 of file G4DecayTable.hh
G4DecayTable& G4DecayTable::operator= (const G4DecayTable &) inline private
Definition at line 68 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 68 of file G4DecayTable.hh
G4bool G4DecayTable::operator== (const G4DecayTable & right) const inline
Definition at line 72 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 72 of file G4DecayTable.hh
G4VDecayChannel * G4DecayTable::operator[] (G4int index) inline
Definition at line 105 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 105 of file G4DecayTable.hh
References channels.
G4VDecayChannel * G4DecayTable::SelectADecayChannel (G4double parentMass = -1.)
Definition at line 84 of file G4DecayTable.cc.
View newest version in sPHENIX GitHub at line 84 of file G4DecayTable.cc
References channels, G4cout, G4endl, G4UniformRand, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), parent, and sum.
Referenced by G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4IntraNucleiCascader::decayTrappedParticle(), G4RadioactiveDecayBase::DoDecay(), and G4RadioactiveDecay::DoDecay().
Member Data Documentation
G4VDecayChannelVector* G4DecayTable::channels private
Definition at line 95 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 95 of file G4DecayTable.hh
Referenced by DumpInfo(), entries(), G4DecayTable(), GetDecayChannel(), Insert(), operator[](), SelectADecayChannel(), and ~G4DecayTable().
G4ParticleDefinition* G4DecayTable::parent private
Definition at line 94 of file G4DecayTable.hh.
View newest version in sPHENIX GitHub at line 94 of file G4DecayTable.hh
Referenced by DumpInfo(), Insert(), SelectADecayChannel(), and ~G4DecayTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4DecayTable.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4DecayTable.cc