ECCE @ EIC Software: G4QGSBinaryProtonBuilder Class Reference
G4QGSBinaryProtonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBinaryProtonBuilder.hh>
Public Member Functions
G4QGSBinaryProtonBuilder (G4bool quasiElastic=false)
virtual ~G4QGSBinaryProtonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4ProtonInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VProtonBuilder
G4VProtonBuilder ()=default
virtual ~G4VProtonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4BinaryCascade * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4double theMin
Detailed Description
Definition at line 57 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4QGSBinaryProtonBuilder.hh
Constructor & Destructor Documentation
G4QGSBinaryProtonBuilder::G4QGSBinaryProtonBuilder (G4bool quasiElastic = false)
Definition at line 48 of file G4QGSBinaryProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4QGSBinaryProtonBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSBinaryProtonBuilder::~G4QGSBinaryProtonBuilder () virtual
Definition at line 78 of file G4QGSBinaryProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 78 of file G4QGSBinaryProtonBuilder.cc
References theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4QGSBinaryProtonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VProtonBuilder.
Definition at line 63 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4QGSBinaryProtonBuilder.hh
void G4QGSBinaryProtonBuilder::Build (G4ProtonInelasticProcess * aP) final override virtual
Implements G4VProtonBuilder.
Definition at line 70 of file G4QGSBinaryProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 70 of file G4QGSBinaryProtonBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicParameters::Instance(), G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSBinaryProtonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 66 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4QGSBinaryProtonBuilder.hh
References theMin.
Member Data Documentation
G4BinaryCascade* G4QGSBinaryProtonBuilder::theCascade private
Definition at line 72 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QGSBinaryProtonBuilder.hh
Referenced by G4QGSBinaryProtonBuilder().
G4double G4QGSBinaryProtonBuilder::theMin private
Definition at line 76 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSBinaryProtonBuilder.hh
Referenced by Build(), G4QGSBinaryProtonBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSBinaryProtonBuilder::theModel private
Definition at line 71 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QGSBinaryProtonBuilder.hh
Referenced by Build(), and G4QGSBinaryProtonBuilder().
G4QuasiElasticChannel* G4QGSBinaryProtonBuilder::theQuasiElastic private
Definition at line 75 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSBinaryProtonBuilder.hh
Referenced by G4QGSBinaryProtonBuilder(), and ~G4QGSBinaryProtonBuilder().
G4ExcitedStringDecay* G4QGSBinaryProtonBuilder::theStringDecay private
Definition at line 74 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QGSBinaryProtonBuilder.hh
Referenced by G4QGSBinaryProtonBuilder(), and ~G4QGSBinaryProtonBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSBinaryProtonBuilder::theStringModel private
Definition at line 73 of file G4QGSBinaryProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QGSBinaryProtonBuilder.hh
Referenced by G4QGSBinaryProtonBuilder(), and ~G4QGSBinaryProtonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBinaryProtonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSBinaryProtonBuilder.cc