ECCE @ EIC Software: G4ParticleHPNTInelasticFS Class Reference
G4ParticleHPNTInelasticFS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPNTInelasticFS.hh>
Public Member Functions
G4ParticleHPNTInelasticFS ()
~G4ParticleHPNTInelasticFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &aFSType, G4ParticleDefinition *)
G4HadFinalState * ApplyYourself (const G4HadProjectile &theTrack)
G4ParticleHPFinalState * New ()
Public Member Functions inherited from G4ParticleHPInelasticBaseFS
G4ParticleHPInelasticBaseFS ()
virtual ~G4ParticleHPInelasticBaseFS ()
void BaseApply (const G4HadProjectile &theTrack, G4ParticleDefinition **theDefs, G4int nDef)
void InitGammas (G4double AR, G4double ZR)
virtual G4double GetXsec (G4double anEnergy)
virtual G4ParticleHPVector * GetXsec ()
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Protected Attributes inherited from G4ParticleHPInelasticBaseFS
G4ParticleHPVector * theXsection
G4ParticleHPEnergyDistribution * theEnergyDistribution
G4ParticleHPAngular * theAngularDistribution
G4ParticleHPEnAngCorrelation * theEnergyAngData
G4ParticleHPPhotonDist * theFinalStatePhotons
G4double theNuclearMassDifference
G4ParticleHPDeExGammas theGammas
G4String gammaPath
G4double Qvalue
Detailed Description
Definition at line 41 of file G4ParticleHPNTInelasticFS.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPNTInelasticFS.hh
Constructor & Destructor Documentation
G4ParticleHPNTInelasticFS::G4ParticleHPNTInelasticFS () inline
Definition at line 45 of file G4ParticleHPNTInelasticFS.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPNTInelasticFS.hh
Referenced by New().
G4ParticleHPNTInelasticFS::~G4ParticleHPNTInelasticFS () inline
Definition at line 46 of file G4ParticleHPNTInelasticFS.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPNTInelasticFS.hh
Member Function Documentation
G4HadFinalState * G4ParticleHPNTInelasticFS::ApplyYourself (const G4HadProjectile & theTrack) virtual
Implements G4ParticleHPInelasticBaseFS.
Definition at line 36 of file G4ParticleHPNTInelasticFS.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleHPNTInelasticFS.cc
References G4ParticleHPInelasticBaseFS::BaseApply(), G4Cache< VALTYPE >::Get(), G4Neutron::Neutron(), G4ParticleHPFinalState::theResult, and G4Triton::Triton().
void G4ParticleHPNTInelasticFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & aFSType, G4ParticleDefinition * projectile) virtual
Reimplemented from G4ParticleHPInelasticBaseFS.
Definition at line 52 of file G4ParticleHPNTInelasticFS.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPNTInelasticFS.cc
References A(), G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4He3::He3(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticBaseFS::InitGammas(), G4Neutron::Neutron(), G4Proton::Proton(), G4Triton::Triton(), and Z.
G4ParticleHPFinalState* G4ParticleHPNTInelasticFS::New () inline virtual
Implements G4ParticleHPInelasticBaseFS.
Definition at line 49 of file G4ParticleHPNTInelasticFS.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPNTInelasticFS.hh
References G4ParticleHPNTInelasticFS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPNTInelasticFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPNTInelasticFS.cc