ECCE @ EIC Software: RE04DetectorConstruction Class Reference
RE04DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/include/RE04DetectorConstruction.hh>
Public Member Functions
RE04DetectorConstruction ()
virtual ~RE04DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
void SetupGeometry ()
Private Attributes
G4Material * fAir
G4Material * fWater
G4Material * fPb
G4VPhysicalVolume * fWorldPhys
G4bool fConstructed
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
User detector construction class
void DefineMaterials() defines materials
void SetupGeometry() creates the world volume and detector geometries
Definition at line 49 of file RE04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 49 of file RE04DetectorConstruction.hh
Constructor & Destructor Documentation
RE04DetectorConstruction::RE04DetectorConstruction ()
Definition at line 47 of file RE04DetectorContruction.cc.
View newest version in sPHENIX GitHub at line 47 of file RE04DetectorContruction.cc
RE04DetectorConstruction::~RE04DetectorConstruction () virtual
Definition at line 53 of file RE04DetectorContruction.cc.
View newest version in sPHENIX GitHub at line 53 of file RE04DetectorContruction.cc
Member Function Documentation
G4VPhysicalVolume * RE04DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 57 of file RE04DetectorContruction.cc.
View newest version in sPHENIX GitHub at line 57 of file RE04DetectorContruction.cc
References DefineMaterials(), fConstructed, fWorldPhys, and SetupGeometry().
void RE04DetectorConstruction::DefineMaterials (void) private
Definition at line 69 of file RE04DetectorContruction.cc.
View newest version in sPHENIX GitHub at line 69 of file RE04DetectorContruction.cc
References fAir, G4NistManager::FindOrBuildMaterial(), fPb, fWater, G4cout, G4endl, G4Material::GetMaterialTable(), and G4NistManager::Instance().
Referenced by Construct().
void RE04DetectorConstruction::SetupGeometry () private
Definition at line 90 of file RE04DetectorContruction.cc.
View newest version in sPHENIX GitHub at line 90 of file RE04DetectorContruction.cc
References cm, fAir, fWorldPhys, G4VisAttributes::GetInvisible(), m, G4LogicalVolume::SetVisAttributes(), and G4VisAttributes::SetVisibility().
Referenced by Construct().
Member Data Documentation
G4Material* RE04DetectorConstruction::fAir private
Definition at line 63 of file RE04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 63 of file RE04DetectorConstruction.hh
Referenced by DefineMaterials(), and SetupGeometry().
G4bool RE04DetectorConstruction::fConstructed private
Definition at line 67 of file RE04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file RE04DetectorConstruction.hh
Referenced by Construct().
G4Material* RE04DetectorConstruction::fPb private
Definition at line 65 of file RE04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 65 of file RE04DetectorConstruction.hh
Referenced by DefineMaterials().
G4Material* RE04DetectorConstruction::fWater private
Definition at line 64 of file RE04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 64 of file RE04DetectorConstruction.hh
Referenced by DefineMaterials().
G4VPhysicalVolume* RE04DetectorConstruction::fWorldPhys private
Definition at line 66 of file RE04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file RE04DetectorConstruction.hh
Referenced by Construct(), and SetupGeometry().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/include/RE04DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/src/RE04DetectorContruction.cc