ECCE @ EIC Software: PHG4PrimaryGeneratorAction Class Reference
PHG4PrimaryGeneratorAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4PrimaryGeneratorAction.h>
Public Member Functions
PHG4PrimaryGeneratorAction ()
~PHG4PrimaryGeneratorAction () override
void GeneratePrimaries (G4Event *anEvent) override
void SetInEvent (PHG4InEvent *const inevt)
set top node (from where particle list is retrieved for passing to geant
void Verbosity (const int val)
Set/Get verbosity.
int Verbosity () const
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Protected Attributes
int verbosity
Private Attributes
PHG4InEvent * inEvent
temporary pointer to input event on node tree
Detailed Description
Definition at line 11 of file PHG4PrimaryGeneratorAction.h.
View newest version in sPHENIX GitHub at line 11 of file PHG4PrimaryGeneratorAction.h
Constructor & Destructor Documentation
PHG4PrimaryGeneratorAction::PHG4PrimaryGeneratorAction () inline
Definition at line 14 of file PHG4PrimaryGeneratorAction.h.
View newest version in sPHENIX GitHub at line 14 of file PHG4PrimaryGeneratorAction.h
PHG4PrimaryGeneratorAction::~PHG4PrimaryGeneratorAction () inline override
Definition at line 20 of file PHG4PrimaryGeneratorAction.h.
View newest version in sPHENIX GitHub at line 20 of file PHG4PrimaryGeneratorAction.h
Member Function Documentation
void PHG4PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) override virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 30 of file PHG4PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 30 of file PHG4PrimaryGeneratorAction.cc
References G4Event::AddPrimaryVertex(), cm, g4zmq::exit(), G4ParticleTable::FindParticle(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), GeV, mass, nanosecond, PHWHERE, position, PHG4UserPrimaryParticleInformation::set_user_barcode(), G4PrimaryParticle::SetCharge(), G4PrimaryParticle::SetKineticEnergy(), G4PrimaryParticle::SetMass(), G4PrimaryParticle::SetMomentum(), G4PrimaryParticle::SetMomentumDirection(), G4PrimaryParticle::SetPolarization(), G4PrimaryParticle::SetUserInformation(), v, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void PHG4PrimaryGeneratorAction::SetInEvent (PHG4InEvent *const inevt) inline
set top node (from where particle list is retrieved for passing to geant
Definition at line 27 of file PHG4PrimaryGeneratorAction.h.
View newest version in sPHENIX GitHub at line 27 of file PHG4PrimaryGeneratorAction.h
References inEvent.
Referenced by PHG4Reco::process_event().
void PHG4PrimaryGeneratorAction::Verbosity (const int val) inline
Set/Get verbosity.
Definition at line 33 of file PHG4PrimaryGeneratorAction.h.
View newest version in sPHENIX GitHub at line 33 of file PHG4PrimaryGeneratorAction.h
References verbosity.
int PHG4PrimaryGeneratorAction::Verbosity () const inline
Definition at line 34 of file PHG4PrimaryGeneratorAction.h.
View newest version in sPHENIX GitHub at line 34 of file PHG4PrimaryGeneratorAction.h
References verbosity.
Member Data Documentation
PHG4InEvent* PHG4PrimaryGeneratorAction::inEvent private
temporary pointer to input event on node tree
Definition at line 41 of file PHG4PrimaryGeneratorAction.h.
View newest version in sPHENIX GitHub at line 41 of file PHG4PrimaryGeneratorAction.h
Referenced by SetInEvent().
int PHG4PrimaryGeneratorAction::verbosity protected
Definition at line 37 of file PHG4PrimaryGeneratorAction.h.
View newest version in sPHENIX GitHub at line 37 of file PHG4PrimaryGeneratorAction.h
Referenced by Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4PrimaryGeneratorAction.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4PrimaryGeneratorAction.cc