ECCE @ EIC Software: LXeStackingAction Class Reference
LXeStackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeStackingAction.hh>
Public Member Functions
LXeStackingAction (LXeEventAction *)
virtual ~LXeStackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Private Attributes
LXeEventAction * fEventAction
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 39 of file LXeStackingAction.hh.
View newest version in sPHENIX GitHub at line 39 of file LXeStackingAction.hh
Constructor & Destructor Documentation
LXeStackingAction::LXeStackingAction (LXeEventAction * ea)
Definition at line 45 of file LXeStackingAction.cc.
View newest version in sPHENIX GitHub at line 45 of file LXeStackingAction.cc
LXeStackingAction::~LXeStackingAction () virtual
Definition at line 51 of file LXeStackingAction.cc.
View newest version in sPHENIX GitHub at line 51 of file LXeStackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack LXeStackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 56 of file LXeStackingAction.cc.
View newest version in sPHENIX GitHub at line 56 of file LXeStackingAction.cc
References fEventAction, fUrgent, G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4Track::GetParentID(), G4VProcess::GetProcessName(), LXeEventAction::IncPhotonCount_Ceren(), LXeEventAction::IncPhotonCount_Scint(), and G4OpticalPhoton::OpticalPhotonDefinition().
void LXeStackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 76 of file LXeStackingAction.cc.
View newest version in sPHENIX GitHub at line 76 of file LXeStackingAction.cc
void LXeStackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 80 of file LXeStackingAction.cc.
View newest version in sPHENIX GitHub at line 80 of file LXeStackingAction.cc
Member Data Documentation
LXeEventAction* LXeStackingAction::fEventAction private
Definition at line 51 of file LXeStackingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file LXeStackingAction.hh
Referenced by ClassifyNewTrack().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeStackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeStackingAction.cc