ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/G4ScreenedNuclearRecoil.cc File Reference
G4ScreenedNuclearRecoil.cc File Reference
Implementation of the G4ScreenedNuclearRecoil class.
#include <stdio.h>
#include "globals.hh"
#include "G4ScreenedNuclearRecoil.hh"
#include "G4ParticleTypes.hh"
#include "G4ParticleTable.hh"
#include "G4IonTable.hh"
#include "G4VParticleChange.hh"
#include "G4ParticleChangeForLoss.hh"
#include "G4DataVector.hh"
#include "G4Track.hh"
#include "G4Step.hh"
#include "G4Material.hh"
#include "G4Element.hh"
#include "G4Isotope.hh"
#include "G4MaterialCutsCouple.hh"
#include "G4ElementVector.hh"
#include "G4IsotopeVector.hh"
#include "G4EmProcessSubType.hh"
#include "G4ParticleDefinition.hh"
#include "G4DynamicParticle.hh"
#include "G4ProcessManager.hh"
#include "G4StableIsotopes.hh"
#include "G4LindhardPartition.hh"
#include "Randomize.hh"
#include <iostream>
#include <iomanip>
#include "c2_factory.hh"
#include <vector>
Typedefs
typedef c2_ptr< G4double > c2p
Functions
G4_c2_function & ZBLScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double *auval)
G4_c2_function & MoliereScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double *auval)
G4_c2_function & LJScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double *auval)
G4_c2_function & LJZBLScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double *auval)
static G4double cm_energy (G4double a1, G4double a2, G4double t0)
static G4double thetac (G4double m1, G4double mass2, G4double eratio)
Variables
static c2_factory< G4double > c2
Detailed Description
Implementation of the G4ScreenedNuclearRecoil class.
Definition in file G4ScreenedNuclearRecoil.cc.
Typedef Documentation
typedef c2_ptr<G4double> c2p
Definition at line 126 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 126 of file G4ScreenedNuclearRecoil.cc
Function Documentation
static G4double cm_energy (G4double a1, G4double a2, G4double t0) inline static
Definition at line 978 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 978 of file G4ScreenedNuclearRecoil.cc
References source.hepunit::amu_c2, and f.
Referenced by G4NativeScreenedCoulombCrossSection::LoadData().
G4_c2_function& LJScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double * auval)
Definition at line 898 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 898 of file G4ScreenedNuclearRecoil.cc
References angstrom, c2_factory< float_type >::lin_log_interpolating_function(), phi, r, and y.
Referenced by G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection(), and LJZBLScreening().
G4_c2_function& LJZBLScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double * auval)
connector in between. These numbers are selected so the switchover
Definition at line 930 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 930 of file G4ScreenedNuclearRecoil.cc
References c2_piecewise_function_p< float_type >::append_function(), c2_factory< float_type >::connector_function(), LJScreening(), c2_factory< float_type >::piecewise_function(), c2_const_ptr< float_type >::release_for_return(), c2_function< float_type >::set_domain(), c2_function< float_type >::xmax(), c2_function< float_type >::xmin(), and ZBLScreening().
Referenced by G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection().
G4_c2_function& MoliereScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double * auval)
Definition at line 866 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 866 of file G4ScreenedNuclearRecoil.cc
References angstrom, c2_factory< float_type >::lin_log_interpolating_function(), phi, r, and sum.
Referenced by G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection().
static G4double thetac (G4double m1, G4double mass2, G4double eratio) inline static
Definition at line 990 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 990 of file G4ScreenedNuclearRecoil.cc
Referenced by G4NativeScreenedCoulombCrossSection::LoadData().
G4_c2_function& ZBLScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double * auval)
Definition at line 834 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 834 of file G4ScreenedNuclearRecoil.cc
References angstrom, c2_factory< float_type >::lin_log_interpolating_function(), phi, r, and sum.
Referenced by G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection(), and LJZBLScreening().
Variable Documentation
c2_factory<G4double> c2 static
Definition at line 125 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 125 of file G4ScreenedNuclearRecoil.cc