ECCE @ EIC Software: c2_typed_ptr< float_type, c2_class > Class Template Reference
c2_typed_ptr< float_type, c2_class > Class Template Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/c2_function.hh>
Public Member Functions
c2_typed_ptr ()
construct the container with no function
c2_typed_ptr (c2_class< float_type > &f)
construct the container with a pre-defined function
c2_typed_ptr (const c2_typed_ptr< float_type, c2_class > &src)
copy constructor
c2_class< float_type > & get () const
get a reference to our owned function
c2_class< float_type > * operator-> () const
get a checked pointer to our owned function
c2_class< float_type > * get_ptr () const
get an unchecked pointer to our owned function
operator c2_class< float_type > & () const
void operator= (const c2_typed_ptr< float_type, c2_class > &f)
fill the container from another container
void operator= (c2_class< float_type > &f)
fill the container with a function
Public Member Functions inherited from c2_const_ptr< float_type >
c2_const_ptr ()
construct the container with no function
c2_const_ptr (const c2_function< float_type > &f)
construct the container with a pre-defined function
c2_const_ptr (const c2_const_ptr< float_type > &src)
copy constructor
void set_function (const c2_function< float_type > *f)
const c2_const_ptr< float_type > & operator= (const c2_const_ptr< float_type > &f)
fill the container from another container
const c2_function< float_type > & operator= (const c2_function< float_type > &f)
fill the container with a function
void release_for_return ()
release the function without destroying it, so it can be returned from a function
void unset_function (void)
clear the function
~c2_const_ptr ()
destructor
const c2_function< float_type > & get () const
get a reference to our owned function
const c2_function< float_type > * get_ptr () const
get an unchecked pointer to our owned function
const c2_function< float_type > * operator-> () const
get a checked pointer to our owned function
bool valid () const
check if we have a valid function
operator const c2_function< float_type > & () const
type coercion operator which lets us use a pointer as if it were a const c2_function
float_type operator() (float_type x) const
convenience operator to make us look like a function
float_type operator() (float_type x, float_type *yprime, float_type *yprime2) const
convenience operator to make us look like a function
c2_sum_p< float_type > & operator+ (const c2_function< float_type > &rhs) const
factory function to create a c2_sum_p from a regular algebraic expression.
c2_diff_p< float_type > & operator- (const c2_function< float_type > &rhs) const
c2_product_p< float_type > & operator* (const c2_function< float_type > &rhs) const
c2_ratio_p< float_type > & operator/ (const c2_function< float_type > &rhs) const
c2_composed_function_p
< float_type > & operator() (const c2_function< float_type > &inner) const
compose this function outside another.
Private Member Functions
void operator= (const c2_const_ptr< float_type > &)
void operator= (const c2_function< float_type > &)
Additional Inherited Members
Protected Attributes inherited from c2_const_ptr< float_type >
const c2_function< float_type > * func
Detailed Description
template<typename float_type, template< typename > class c2_class>
class c2_typed_ptr< float_type, c2_class >
Definition at line 836 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 836 of file c2_function.hh
Constructor & Destructor Documentation
template<typename float_type, template< typename > class c2_class> c2_typed_ptr< float_type, c2_class >::c2_typed_ptr () inline
construct the container with no function
Definition at line 840 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 840 of file c2_function.hh
template<typename float_type, template< typename > class c2_class> c2_typed_ptr< float_type, c2_class >::c2_typed_ptr (c2_class< float_type > & f) inline
construct the container with a pre-defined function
Parameters
f the function to store
Definition at line 843 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 843 of file c2_function.hh
References c2_const_ptr< float_type >::set_function().
template<typename float_type, template< typename > class c2_class> c2_typed_ptr< float_type, c2_class >::c2_typed_ptr (const c2_typed_ptr< float_type, c2_class > & src) inline
copy constructor
Parameters
src the container to copy
Definition at line 847 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 847 of file c2_function.hh
References c2_typed_ptr< float_type, c2_class >::get_ptr(), and c2_const_ptr< float_type >::set_function().
Member Function Documentation
template<typename float_type, template< typename > class c2_class> c2_class<float_type>& c2_typed_ptr< float_type, c2_class >::get (void) const inline
get a reference to our owned function
Definition at line 851 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 851 of file c2_function.hh
References c2_const_ptr< float_type >::get().
template<typename float_type, template< typename > class c2_class> c2_class<float_type>* c2_typed_ptr< float_type, c2_class >::get_ptr () const inline
get an unchecked pointer to our owned function
Definition at line 860 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 860 of file c2_function.hh
References c2_const_ptr< float_type >::func.
Referenced by c2_typed_ptr< float_type, c2_class >::c2_typed_ptr(), and c2_typed_ptr< float_type, c2_class >::operator=().
template<typename float_type, template< typename > class c2_class> c2_typed_ptr< float_type, c2_class >::operator c2_class< float_type > & () const inline
Definition at line 864 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 864 of file c2_function.hh
template<typename float_type, template< typename > class c2_class> c2_class<float_type>* c2_typed_ptr< float_type, c2_class >::operator-> () const inline
get a checked pointer to our owned function
Definition at line 857 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 857 of file c2_function.hh
template<typename float_type, template< typename > class c2_class> void c2_typed_ptr< float_type, c2_class >::operator= (const c2_typed_ptr< float_type, c2_class > & f) inline
fill the container from another container
Parameters
f the container to copy
Definition at line 867 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 867 of file c2_function.hh
References c2_typed_ptr< float_type, c2_class >::get_ptr(), and c2_const_ptr< float_type >::set_function().
template<typename float_type, template< typename > class c2_class> void c2_typed_ptr< float_type, c2_class >::operator= (c2_class< float_type > & f) inline
fill the container with a function
Parameters
f the function
Definition at line 871 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 871 of file c2_function.hh
References c2_const_ptr< float_type >::set_function().
template<typename float_type, template< typename > class c2_class> void c2_typed_ptr< float_type, c2_class >::operator= (const c2_const_ptr< float_type > &) inline private
Definition at line 874 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 874 of file c2_function.hh
template<typename float_type, template< typename > class c2_class> void c2_typed_ptr< float_type, c2_class >::operator= (const c2_function< float_type > &) inline private
Definition at line 875 of file c2_function.hh.
View newest version in sPHENIX GitHub at line 875 of file c2_function.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/c2_function.hh