ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/G4gsrotm.cc File Reference
G4gsrotm.cc File Reference
#include "G3toG4.hh"
#include "G3RotTable.hh"
#include "G3toG4RotationMatrix.hh"
#include "G4PhysicalConstants.hh"
#include "G4ThreeVector.hh"
Functions
void PG4gsrotm (G4String *tokens)
void G4gsrotm (G4int irot, G4double theta1, G4double phi1, G4double theta2, G4double phi2, G4double theta3, G4double phi3)
Function Documentation
void G4gsrotm (G4int irot, G4double theta1, G4double phi1, G4double theta2, G4double phi2, G4double theta3, G4double phi3)
Definition at line 53 of file G4gsrotm.cc.
View newest version in sPHENIX GitHub at line 53 of file G4gsrotm.cc
References kdfinder::abs(), CLHEP::Hep3Vector::cross(), FatalException, G3Rot, G4cerr, G4endl, G4Exception(), pi, G3RotTable::Put(), G3toG4RotationMatrix::SetRotationMatrixByRow(), x, y, and z.
Referenced by G4BuildGeom(), and PG4gsrotm().
void PG4gsrotm (G4String * tokens)
Definition at line 34 of file G4gsrotm.cc.
View newest version in sPHENIX GitHub at line 34 of file G4gsrotm.cc
References G3fillParams(), G4gsrotm(), Ipar, PTgsrotm, and Rpar.
Referenced by G3CLEval().