ECCE @ EIC Software: G4AnyMethod Class Reference
G4AnyMethod Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4AnyMethod.hh>
Classes
struct FuncRef
struct FuncRef1
struct FuncRef2
class Placeholder
Public Member Functions
G4AnyMethod ()
template<class S , class T >
G4AnyMethod (S(T::*f)())
template<class S , class T , class A0 >
G4AnyMethod (S(T::*f)(A0))
template<class S , class T , class A0 , class A1 >
G4AnyMethod (S(T::*f)(A0, A1))
G4AnyMethod (const G4AnyMethod &other)
~G4AnyMethod ()
G4AnyMethod & Swap (G4AnyMethod &rhs)
template<class S , class T >
G4AnyMethod & operator= (S(T::*f)())
template<class S , class T , class A0 >
G4AnyMethod & operator= (S(T::*f)(A0))
template<class S , class T , class A0 , class A1 >
G4AnyMethod & operator= (S(T::*f)(A0, A1))
G4AnyMethod & operator= (const G4AnyMethod &rhs)
bool Empty () const
void operator() (void *obj)
void operator() (void *obj, const std::string &a0)
size_t NArg () const
const std::type_info & ArgType (size_t n=0) const
Private Attributes
Placeholder * fContent
size_t narg
Detailed Description
This class represents any object method. The class only holds a member pointer.
Definition at line 81 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 81 of file G4AnyMethod.hh
Constructor & Destructor Documentation
G4AnyMethod::G4AnyMethod () inline
contructor
Definition at line 84 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 84 of file G4AnyMethod.hh
Referenced by operator=().
template<class S , class T > G4AnyMethod::G4AnyMethod (S(T::*)() f) inline
Definition at line 85 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 85 of file G4AnyMethod.hh
References f, and fContent.
template<class S , class T , class A0 > G4AnyMethod::G4AnyMethod (S(T::*)(A0) f) inline
Definition at line 88 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 88 of file G4AnyMethod.hh
References f, and fContent.
template<class S , class T , class A0 , class A1 > G4AnyMethod::G4AnyMethod (S(T::*)(A0, A1) f) inline
Definition at line 91 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 91 of file G4AnyMethod.hh
References f, and fContent.
G4AnyMethod::G4AnyMethod (const G4AnyMethod & other) inline
Definition at line 94 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 94 of file G4AnyMethod.hh
G4AnyMethod::~G4AnyMethod () inline
destructor
Definition at line 97 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AnyMethod.hh
References fContent.
Member Function Documentation
const std::type_info& G4AnyMethod::ArgType (size_t n = 0) const inline
Definition at line 142 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 142 of file G4AnyMethod.hh
References G4AnyMethod::Placeholder::ArgType(), fContent, n, and void().
bool G4AnyMethod::Empty () const inline
Query
Definition at line 129 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 129 of file G4AnyMethod.hh
References fContent.
size_t G4AnyMethod::NArg () const inline
Number of arguments
Definition at line 140 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 140 of file G4AnyMethod.hh
References narg.
Referenced by G4GenericMessenger::DeclareMethod(), G4GenericMessenger::DeclareMethodWithUnit(), and G4GenericMessenger::SetNewValue().
void G4AnyMethod::operator() (void * obj) inline
call operator
Definition at line 133 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 133 of file G4AnyMethod.hh
References fContent.
void G4AnyMethod::operator() (void * obj, const std::string & a0) inline
Definition at line 136 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 136 of file G4AnyMethod.hh
References a0, and fContent.
template<class S , class T > G4AnyMethod& G4AnyMethod::operator= (S(T::*)() f) inline
Asignment operator
Definition at line 107 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AnyMethod.hh
References G4AnyMethod(), and narg.
template<class S , class T , class A0 > G4AnyMethod& G4AnyMethod::operator= (S(T::*)(A0) f) inline
Definition at line 112 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 112 of file G4AnyMethod.hh
References G4AnyMethod(), and narg.
template<class S , class T , class A0 , class A1 > G4AnyMethod& G4AnyMethod::operator= (S(T::*)(A0, A1) f) inline
Definition at line 117 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 117 of file G4AnyMethod.hh
References G4AnyMethod(), and narg.
G4AnyMethod& G4AnyMethod::operator= (const G4AnyMethod & rhs) inline
Asigment operator
Definition at line 123 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 123 of file G4AnyMethod.hh
References G4AnyMethod(), and narg.
G4AnyMethod& G4AnyMethod::Swap (G4AnyMethod & rhs) inline
Definition at line 101 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AnyMethod.hh
References fContent, narg, and boost::swap().
Member Data Documentation
Placeholder* G4AnyMethod::fContent private
Definition at line 223 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 223 of file G4AnyMethod.hh
Referenced by ArgType(), Empty(), G4AnyMethod(), operator()(), Swap(), and ~G4AnyMethod().
size_t G4AnyMethod::narg private
Definition at line 224 of file G4AnyMethod.hh.
View newest version in sPHENIX GitHub at line 224 of file G4AnyMethod.hh
Referenced by NArg(), operator=(), and Swap().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4AnyMethod.hh