ECCE @ EIC Software: G4tgbPlaceParameterisation Class Reference
G4tgbPlaceParameterisation Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbPlaceParameterisation.hh>
Public Member Functions
G4tgbPlaceParameterisation (G4tgrPlaceParameterisation *tgrParam)
virtual ~G4tgbPlaceParameterisation ()
virtual void ComputeTransformation (const G4int, G4VPhysicalVolume *) const
void CheckNExtraData (G4tgrPlaceParameterisation *tgrParam, G4int nWcheck, WLSIZEtype st, const G4String &methodName)
G4int GetNCopies () const
EAxis GetAxis () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
Protected Attributes
G4int theNCopies
EAxis theAxis
G4ThreeVector theTranslation
G4RotationMatrix * theRotationMatrix
Detailed Description
Definition at line 52 of file G4tgbPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 52 of file G4tgbPlaceParameterisation.hh
Constructor & Destructor Documentation
G4tgbPlaceParameterisation::G4tgbPlaceParameterisation (G4tgrPlaceParameterisation * tgrParam)
Definition at line 44 of file G4tgbPlaceParameterisation.cc.
View newest version in sPHENIX GitHub at line 44 of file G4tgbPlaceParameterisation.cc
References G4tgbRotationMatrixMgr::FindOrBuildG4RotMatrix(), G4tgbRotationMatrixMgr::GetInstance(), G4tgrPlaceParameterisation::GetRotMatName(), and theRotationMatrix.
G4tgbPlaceParameterisation::~G4tgbPlaceParameterisation () virtual
Definition at line 51 of file G4tgbPlaceParameterisation.cc.
View newest version in sPHENIX GitHub at line 51 of file G4tgbPlaceParameterisation.cc
References theRotationMatrix.
Member Function Documentation
void G4tgbPlaceParameterisation::CheckNExtraData (G4tgrPlaceParameterisation * tgrParam, G4int nWcheck, WLSIZEtype st, const G4String & methodName)
Definition at line 62 of file G4tgbPlaceParameterisation.cc.
View newest version in sPHENIX GitHub at line 62 of file G4tgbPlaceParameterisation.cc
References G4tgrUtils::CheckListSize(), G4UIcommand::ConvertToString(), FatalException, G4cerr, G4endl, G4Exception(), G4tgrPlaceParameterisation::GetExtraData(), and G4tgrPlace::GetType().
Referenced by G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), and G4tgbPlaceParamSquare::G4tgbPlaceParamSquare().
void G4tgbPlaceParameterisation::ComputeTransformation (const G4int , G4VPhysicalVolume *) const virtual
Implements G4VPVParameterisation.
Reimplemented in G4tgbPlaceParamCircle, G4tgbPlaceParamLinear, and G4tgbPlaceParamSquare.
Definition at line 57 of file G4tgbPlaceParameterisation.cc.
View newest version in sPHENIX GitHub at line 57 of file G4tgbPlaceParameterisation.cc
EAxis G4tgbPlaceParameterisation::GetAxis () const inline
Definition at line 66 of file G4tgbPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 66 of file G4tgbPlaceParameterisation.hh
References theAxis.
Referenced by G4tgbVolume::ConstructG4PhysVol().
G4int G4tgbPlaceParameterisation::GetNCopies () const inline
Definition at line 65 of file G4tgbPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 65 of file G4tgbPlaceParameterisation.hh
References theNCopies.
Referenced by G4tgbVolume::ConstructG4PhysVol().
Member Data Documentation
EAxis G4tgbPlaceParameterisation::theAxis protected
Definition at line 71 of file G4tgbPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgbPlaceParameterisation.hh
Referenced by G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), G4tgbPlaceParamSquare::G4tgbPlaceParamSquare(), and GetAxis().
G4int G4tgbPlaceParameterisation::theNCopies protected
Definition at line 70 of file G4tgbPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 70 of file G4tgbPlaceParameterisation.hh
Referenced by G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamCircle::ComputeTransformation(), G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), G4tgbPlaceParamSquare::G4tgbPlaceParamSquare(), and GetNCopies().
G4RotationMatrix* G4tgbPlaceParameterisation::theRotationMatrix protected
Definition at line 73 of file G4tgbPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 73 of file G4tgbPlaceParameterisation.hh
Referenced by G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamLinear::ComputeTransformation(), G4tgbPlaceParamCircle::ComputeTransformation(), G4tgbPlaceParameterisation(), and ~G4tgbPlaceParameterisation().
G4ThreeVector G4tgbPlaceParameterisation::theTranslation protected
Definition at line 72 of file G4tgbPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 72 of file G4tgbPlaceParameterisation.hh
Referenced by G4tgbPlaceParamSquare::ComputeTransformation(), G4tgbPlaceParamLinear::ComputeTransformation(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), and G4tgbPlaceParamSquare::G4tgbPlaceParamSquare().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbPlaceParameterisation.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbPlaceParameterisation.cc