ECCE @ EIC Software: LXeDetectorMessenger Class Reference
LXeDetectorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeDetectorMessenger.hh>
Public Member Functions
LXeDetectorMessenger (LXeDetectorConstruction *)
virtual ~LXeDetectorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
LXeDetectorConstruction * fLXeDetector
G4UIdirectory * fDetectorDir
G4UIdirectory * fVolumesDir
G4UIcmdWith3VectorAndUnit * fDimensionsCmd
G4UIcmdWithADoubleAndUnit * fHousingThicknessCmd
G4UIcmdWithADoubleAndUnit * fPmtRadiusCmd
G4UIcmdWithAnInteger * fNxCmd
G4UIcmdWithAnInteger * fNyCmd
G4UIcmdWithAnInteger * fNzCmd
G4UIcmdWithABool * fSphereCmd
G4UIcmdWithADouble * fReflectivityCmd
G4UIcmdWithABool * fWlsCmd
G4UIcmdWithABool * fLxeCmd
G4UIcmdWithAnInteger * fNFibersCmd
G4UIcommand * fDefaultsCmd
G4UIcmdWithADouble * fMainScintYield
G4UIcmdWithADouble * fWLSScintYield
G4UIcmdWithAnInteger * fSaveThresholdCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 46 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 46 of file LXeDetectorMessenger.hh
Constructor & Destructor Documentation
LXeDetectorMessenger::LXeDetectorMessenger (LXeDetectorConstruction * detector)
Definition at line 47 of file LXeDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 47 of file LXeDetectorMessenger.cc
References G4UIcommand::AvailableForStates(), fDefaultsCmd, fDetectorDir, fDimensionsCmd, fHousingThicknessCmd, fLxeCmd, fMainScintYield, fNFibersCmd, fNxCmd, fNyCmd, fNzCmd, fPmtRadiusCmd, fReflectivityCmd, fSaveThresholdCmd, fSphereCmd, fVolumesDir, fWlsCmd, fWLSScintYield, G4State_Idle, G4State_PreInit, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), and G4UIcommand::SetToBeBroadcasted().
LXeDetectorMessenger::~LXeDetectorMessenger () virtual
Definition at line 152 of file LXeDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 152 of file LXeDetectorMessenger.cc
References fDefaultsCmd, fDetectorDir, fDimensionsCmd, fHousingThicknessCmd, fLxeCmd, fMainScintYield, fNFibersCmd, fNxCmd, fNyCmd, fNzCmd, fPmtRadiusCmd, fReflectivityCmd, fSaveThresholdCmd, fSphereCmd, fVolumesDir, fWlsCmd, and fWLSScintYield.
Member Function Documentation
void LXeDetectorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 175 of file LXeDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 175 of file LXeDetectorMessenger.cc
References fDefaultsCmd, fDimensionsCmd, fHousingThicknessCmd, fLxeCmd, fLXeDetector, fMainScintYield, fNFibersCmd, fNxCmd, fNyCmd, fNzCmd, fPmtRadiusCmd, fReflectivityCmd, fSaveThresholdCmd, fSphereCmd, fWlsCmd, fWLSScintYield, G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADouble::GetNewDoubleValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4RunManager::GetRunManager(), G4RunManager::ReinitializeGeometry(), LXeDetectorConstruction::SetDefaults(), LXeDetectorConstruction::SetDimensions(), LXeDetectorConstruction::SetHousingReflectivity(), LXeDetectorConstruction::SetHousingThickness(), LXeDetectorConstruction::SetMainVolumeOn(), LXeDetectorConstruction::SetNFibers(), LXeDetectorConstruction::SetNX(), LXeDetectorConstruction::SetNY(), LXeDetectorConstruction::SetNZ(), LXeDetectorConstruction::SetPMTRadius(), LXeDetectorConstruction::SetSaveThreshold(), LXeDetectorConstruction::SetSphereOn(), LXeDetectorConstruction::SetWLSScintYield(), and LXeDetectorConstruction::SetWLSSlabOn().
Member Data Documentation
G4UIcommand* LXeDetectorMessenger::fDefaultsCmd private
Definition at line 71 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIdirectory* LXeDetectorMessenger::fDetectorDir private
Definition at line 58 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), and ~LXeDetectorMessenger().
G4UIcmdWith3VectorAndUnit* LXeDetectorMessenger::fDimensionsCmd private
Definition at line 60 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithADoubleAndUnit* LXeDetectorMessenger::fHousingThicknessCmd private
Definition at line 61 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithABool* LXeDetectorMessenger::fLxeCmd private
Definition at line 69 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
LXeDetectorConstruction* LXeDetectorMessenger::fLXeDetector private
Definition at line 57 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file LXeDetectorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADouble* LXeDetectorMessenger::fMainScintYield private
Definition at line 72 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithAnInteger* LXeDetectorMessenger::fNFibersCmd private
Definition at line 70 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithAnInteger* LXeDetectorMessenger::fNxCmd private
Definition at line 63 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithAnInteger* LXeDetectorMessenger::fNyCmd private
Definition at line 64 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithAnInteger* LXeDetectorMessenger::fNzCmd private
Definition at line 65 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithADoubleAndUnit* LXeDetectorMessenger::fPmtRadiusCmd private
Definition at line 62 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithADouble* LXeDetectorMessenger::fReflectivityCmd private
Definition at line 67 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithAnInteger* LXeDetectorMessenger::fSaveThresholdCmd private
Definition at line 74 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithABool* LXeDetectorMessenger::fSphereCmd private
Definition at line 66 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIdirectory* LXeDetectorMessenger::fVolumesDir private
Definition at line 59 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), and ~LXeDetectorMessenger().
G4UIcmdWithABool* LXeDetectorMessenger::fWlsCmd private
Definition at line 68 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
G4UIcmdWithADouble* LXeDetectorMessenger::fWLSScintYield private
Definition at line 73 of file LXeDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file LXeDetectorMessenger.hh
Referenced by LXeDetectorMessenger(), SetNewValue(), and ~LXeDetectorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeDetectorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeDetectorMessenger.cc