ECCE @ EIC Software: G4PolarizationManager Class Reference
G4PolarizationManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizationManager.hh>
Public Member Functions
virtual ~G4PolarizationManager ()
void ListVolumes ()
void Clean ()
void SetVolumePolarization (G4LogicalVolume *lVol, const G4ThreeVector &pol)
void SetVolumePolarization (const G4String &lVolName, const G4ThreeVector &pol)
const G4ThreeVector & GetVolumePolarization (G4LogicalVolume *lVol) const
bool IsPolarized (G4LogicalVolume *lVol) const
void SetVerbose (G4int val)
G4int GetVerbose () const
void SetActivated (G4bool val)
bool IsActivated () const
Static Public Member Functions
static G4PolarizationManager * GetInstance ()
static void Dispose ()
Private Member Functions
G4PolarizationManager ()
Private Attributes
G4ThreeVector zeroPolarization
PolarizationMap volumePolarizations
G4PolarizationMessenger * messenger
G4int verboseLevel
G4bool activated
Static Private Attributes
static G4ThreadLocal
G4PolarizationManager * instance = nullptr
Detailed Description
Definition at line 58 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PolarizationManager.hh
Constructor & Destructor Documentation
G4PolarizationManager::~G4PolarizationManager () virtual
Definition at line 72 of file G4PolarizationManager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4PolarizationManager.cc
G4PolarizationManager::G4PolarizationManager () private
Definition at line 66 of file G4PolarizationManager.cc.
View newest version in sPHENIX GitHub at line 66 of file G4PolarizationManager.cc
References messenger.
Referenced by GetInstance().
Member Function Documentation
void G4PolarizationManager::Clean () inline
Definition at line 125 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 125 of file G4PolarizationManager.hh
References volumePolarizations.
void G4PolarizationManager::Dispose () static
Definition at line 57 of file G4PolarizationManager.cc.
View newest version in sPHENIX GitHub at line 57 of file G4PolarizationManager.cc
References instance.
G4PolarizationManager * G4PolarizationManager::GetInstance (void) static
Definition at line 51 of file G4PolarizationManager.cc.
View newest version in sPHENIX GitHub at line 51 of file G4PolarizationManager.cc
References G4PolarizationManager(), and instance.
Referenced by G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
G4int G4PolarizationManager::GetVerbose () const inline
Definition at line 116 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 116 of file G4PolarizationManager.hh
References verboseLevel.
Referenced by G4PolarizationMessenger::GetCurrentValue().
const G4ThreeVector & G4PolarizationManager::GetVolumePolarization (G4LogicalVolume * lVol) const inline
Definition at line 96 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 96 of file G4PolarizationManager.hh
References activated, volumePolarizations, and zeroPolarization.
Referenced by G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
bool G4PolarizationManager::IsActivated () const inline
Definition at line 121 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 121 of file G4PolarizationManager.hh
References activated.
bool G4PolarizationManager::IsPolarized (G4LogicalVolume * lVol) const inline
Definition at line 106 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 106 of file G4PolarizationManager.hh
References activated, and volumePolarizations.
Referenced by G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), and G4PolarizedAnnihilationModel::SampleSecondaries().
void G4PolarizationManager::ListVolumes ()
Definition at line 76 of file G4PolarizationManager.cc.
View newest version in sPHENIX GitHub at line 76 of file G4PolarizationManager.cc
References activated, G4cout, G4endl, and volumePolarizations.
Referenced by G4PolarizationMessenger::SetNewValue().
void G4PolarizationManager::SetActivated (G4bool val) inline
Definition at line 120 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4PolarizationManager.hh
References activated.
Referenced by G4PolarizationMessenger::SetNewValue().
void G4PolarizationManager::SetVerbose (G4int val) inline
Definition at line 115 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PolarizationManager.hh
References verboseLevel.
Referenced by G4PolarizationMessenger::SetNewValue().
void G4PolarizationManager::SetVolumePolarization (G4LogicalVolume * lVol, const G4ThreeVector & pol)
Definition at line 88 of file G4PolarizationManager.cc.
View newest version in sPHENIX GitHub at line 88 of file G4PolarizationManager.cc
References G4cout, G4endl, G4LogicalVolume::GetName(), verboseLevel, and volumePolarizations.
Referenced by G4PolarizationMessenger::SetNewValue().
void G4PolarizationManager::SetVolumePolarization (const G4String & lVolName, const G4ThreeVector & pol)
Definition at line 96 of file G4PolarizationManager.cc.
View newest version in sPHENIX GitHub at line 96 of file G4PolarizationManager.cc
References G4cout, G4endl, verboseLevel, and volumePolarizations.
Member Data Documentation
G4bool G4PolarizationManager::activated private
Definition at line 88 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PolarizationManager.hh
Referenced by GetVolumePolarization(), IsActivated(), IsPolarized(), ListVolumes(), and SetActivated().
G4ThreadLocal G4PolarizationManager * G4PolarizationManager::instance = nullptr static private
Definition at line 90 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PolarizationManager.hh
Referenced by Dispose(), and GetInstance().
G4PolarizationMessenger* G4PolarizationManager::messenger private
Definition at line 85 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 85 of file G4PolarizationManager.hh
Referenced by G4PolarizationManager().
G4int G4PolarizationManager::verboseLevel private
Definition at line 87 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 87 of file G4PolarizationManager.hh
Referenced by GetVerbose(), SetVerbose(), and SetVolumePolarization().
PolarizationMap G4PolarizationManager::volumePolarizations private
Definition at line 84 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 84 of file G4PolarizationManager.hh
Referenced by Clean(), GetVolumePolarization(), IsPolarized(), ListVolumes(), and SetVolumePolarization().
G4ThreeVector G4PolarizationManager::zeroPolarization private
Definition at line 83 of file G4PolarizationManager.hh.
View newest version in sPHENIX GitHub at line 83 of file G4PolarizationManager.hh
Referenced by GetVolumePolarization().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizationManager.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizationManager.cc