ECCE @ EIC Software: G4PVDivisionFactory Class Reference
G4PVDivisionFactory Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4PVDivisionFactory.hh>
Public Member Functions
virtual ~G4PVDivisionFactory ()
virtual G4VPhysicalVolume * CreatePVDivision (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset)
virtual G4VPhysicalVolume * CreatePVDivision (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical, const EAxis pAxis, const G4int nReplicas, const G4double offset)
virtual G4VPhysicalVolume * CreatePVDivision (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical, const EAxis pAxis, const G4double width, const G4double offset)
virtual G4VPhysicalVolume * CreatePVDivision (const G4String &pName, G4LogicalVolume *pLogical, G4LogicalVolume *pMotherLogical, const G4VPVParameterisation *param)
virtual G4bool IsPVDivision (const G4VPhysicalVolume *pv) const
Public Member Functions inherited from G4VPVDivisionFactory
virtual ~G4VPVDivisionFactory ()
Static Public Member Functions
static G4PVDivisionFactory * GetInstance ()
Static Public Member Functions inherited from G4VPVDivisionFactory
static G4VPVDivisionFactory * Instance ()
Protected Member Functions
G4PVDivisionFactory ()
Protected Member Functions inherited from G4VPVDivisionFactory
G4VPVDivisionFactory ()
Additional Inherited Members
Static Protected Attributes inherited from G4VPVDivisionFactory
static G4ThreadLocal
G4VPVDivisionFactory * fgInstance = nullptr
Detailed Description
Definition at line 43 of file G4PVDivisionFactory.hh.
View newest version in sPHENIX GitHub at line 43 of file G4PVDivisionFactory.hh
Constructor & Destructor Documentation
G4PVDivisionFactory::~G4PVDivisionFactory () virtual
Definition at line 46 of file G4PVDivisionFactory.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PVDivisionFactory.cc
G4PVDivisionFactory::G4PVDivisionFactory () protected
Definition at line 37 of file G4PVDivisionFactory.cc.
View newest version in sPHENIX GitHub at line 37 of file G4PVDivisionFactory.cc
Referenced by GetInstance().
Member Function Documentation
G4VPhysicalVolume * G4PVDivisionFactory::CreatePVDivision (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMother, const EAxis pAxis, const G4int nReplicas, const G4double width, const G4double offset) virtual
Implements G4VPVDivisionFactory.
Definition at line 64 of file G4PVDivisionFactory.cc.
View newest version in sPHENIX GitHub at line 64 of file G4PVDivisionFactory.cc
G4VPhysicalVolume * G4PVDivisionFactory::CreatePVDivision (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMotherLogical, const EAxis pAxis, const G4int nReplicas, const G4double offset) virtual
Implements G4VPVDivisionFactory.
Definition at line 82 of file G4PVDivisionFactory.cc.
View newest version in sPHENIX GitHub at line 82 of file G4PVDivisionFactory.cc
G4VPhysicalVolume * G4PVDivisionFactory::CreatePVDivision (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMotherLogical, const EAxis pAxis, const G4double width, const G4double offset) virtual
Implements G4VPVDivisionFactory.
Definition at line 99 of file G4PVDivisionFactory.cc.
View newest version in sPHENIX GitHub at line 99 of file G4PVDivisionFactory.cc
G4VPhysicalVolume * G4PVDivisionFactory::CreatePVDivision (const G4String & pName, G4LogicalVolume * pLogical, G4LogicalVolume * pMotherLogical, const G4VPVParameterisation * param) virtual
Implements G4VPVDivisionFactory.
Definition at line 116 of file G4PVDivisionFactory.cc.
View newest version in sPHENIX GitHub at line 116 of file G4PVDivisionFactory.cc
References FatalException, G4Exception(), G4VDivisionParameterisation::GetAxis(), G4VDivisionParameterisation::GetNoDiv(), G4VDivisionParameterisation::GetOffset(), G4VDivisionParameterisation::GetWidth(), offset, and width.
G4PVDivisionFactory * G4PVDivisionFactory::GetInstance (void) static
Definition at line 52 of file G4PVDivisionFactory.cc.
View newest version in sPHENIX GitHub at line 52 of file G4PVDivisionFactory.cc
References G4VPVDivisionFactory::fgInstance, and G4PVDivisionFactory().
Referenced by G4GDMLReadStructure::DivisionvolRead().
G4bool G4PVDivisionFactory::IsPVDivision (const G4VPhysicalVolume * pv) const virtual
Implements G4VPVDivisionFactory.
Definition at line 150 of file G4PVDivisionFactory.cc.
View newest version in sPHENIX GitHub at line 150 of file G4PVDivisionFactory.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4PVDivisionFactory.hh
geant4/tree/geant4-10.6-release/source/geometry/divisions/src/G4PVDivisionFactory.cc