ECCE @ EIC Software: G4ConcreteMesonBaryonToResonance Class Reference
G4ConcreteMesonBaryonToResonance Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4ConcreteMesonBaryonToResonance.hh>
Public Member Functions
G4ConcreteMesonBaryonToResonance (const G4ParticleDefinition *aPrimary, const G4ParticleDefinition *bPriamry, const G4ParticleDefinition *aSecondary, const G4String &partWidthLabel)
virtual ~G4ConcreteMesonBaryonToResonance ()
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const std::vector
< G4String > & GetListOfColliders (G4int) const
virtual G4String GetName () const
G4bool operator== (const G4ConcreteMesonBaryonToResonance &right) const
G4bool operator!= (const G4ConcreteMesonBaryonToResonance &right) const
Public Member Functions inherited from G4VAnnihilationCollision
G4VAnnihilationCollision ()
virtual ~G4VAnnihilationCollision ()
G4bool operator== (const G4VAnnihilationCollision &right) const
G4bool operator!= (const G4VAnnihilationCollision &right) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4VAngularDistribution * GetAngularDistribution () const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const
virtual const
G4ParticleDefinition * GetOutgoingParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Private Member Functions
G4ConcreteMesonBaryonToResonance (const G4ConcreteMesonBaryonToResonance &)
G4ConcreteMesonBaryonToResonance & operator= (const G4ConcreteMesonBaryonToResonance &)
Static Private Member Functions
static void InitialisePointers ()
static G4BaryonWidth & theBaryonWidth ()
static G4BaryonPartialWidth & theBaryonPartialWidth ()
static G4ParticleTypeConverter & myConv ()
Private Attributes
G4VCrossSectionSource * crossSectionSource
const G4ParticleDefinition * thePrimary1
const G4ParticleDefinition * thePrimary2
const G4ParticleDefinition * theSecondary
Static Private Attributes
static G4BaryonWidth * baryonWidth = nullptr
static G4BaryonPartialWidth * baryonPartialWidth = nullptr
static G4ParticleTypeConverter * particleTypeConverter = nullptr
Detailed Description
Definition at line 45 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ConcreteMesonBaryonToResonance.hh
Constructor & Destructor Documentation
G4ConcreteMesonBaryonToResonance::G4ConcreteMesonBaryonToResonance (const G4ParticleDefinition * aPrimary, const G4ParticleDefinition * bPriamry, const G4ParticleDefinition * aSecondary, const G4String & partWidthLabel)
Definition at line 57 of file G4ConcreteMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ConcreteMesonBaryonToResonance.cc
References crossSectionSource, InitialisePointers(), theBaryonPartialWidth(), and theBaryonWidth().
G4ConcreteMesonBaryonToResonance::~G4ConcreteMesonBaryonToResonance () virtual
Definition at line 70 of file G4ConcreteMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ConcreteMesonBaryonToResonance.cc
References crossSectionSource.
G4ConcreteMesonBaryonToResonance::G4ConcreteMesonBaryonToResonance (const G4ConcreteMesonBaryonToResonance &) private
Member Function Documentation
virtual const G4VCrossSectionSource* G4ConcreteMesonBaryonToResonance::GetCrossSectionSource () const inline protected virtual
Implements G4VCollision.
Definition at line 81 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ConcreteMesonBaryonToResonance.hh
References crossSectionSource.
virtual const std::vector<G4String>& G4ConcreteMesonBaryonToResonance::GetListOfColliders (G4int) const inline virtual
Implements G4VCollision.
Definition at line 60 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ConcreteMesonBaryonToResonance.hh
virtual G4String G4ConcreteMesonBaryonToResonance::GetName (void) const inline virtual
Implements G4VCollision.
Definition at line 67 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ConcreteMesonBaryonToResonance.hh
const G4ParticleDefinition * G4ConcreteMesonBaryonToResonance::GetOutgoingParticle (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const protected virtual
Implements G4VAnnihilationCollision.
Definition at line 102 of file G4ConcreteMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 102 of file G4ConcreteMesonBaryonToResonance.cc
References G4cerr, G4endl, G4KineticTrack::GetDefinition(), G4ParticleTypeConverter::GetGenericType(), G4ParticleDefinition::GetPDGiIsospin3(), myConv(), and theSecondary.
void G4ConcreteMesonBaryonToResonance::InitialisePointers () static private
Definition at line 75 of file G4ConcreteMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ConcreteMesonBaryonToResonance.cc
References baryonPartialWidth, baryonWidth, G4MUTEXLOCK, G4MUTEXUNLOCK, and particleTypeConverter.
Referenced by G4ConcreteMesonBaryonToResonance(), myConv(), theBaryonPartialWidth(), and theBaryonWidth().
G4bool G4ConcreteMesonBaryonToResonance::IsInCharge (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCollision.
Definition at line 92 of file G4ConcreteMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ConcreteMesonBaryonToResonance.cc
References myConv(), thePrimary1, and thePrimary2.
G4ParticleTypeConverter & G4ConcreteMesonBaryonToResonance::myConv () static private
Definition at line 51 of file G4ConcreteMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ConcreteMesonBaryonToResonance.cc
References InitialisePointers(), and particleTypeConverter.
Referenced by GetOutgoingParticle(), and IsInCharge().
G4bool G4ConcreteMesonBaryonToResonance::operator!= (const G4ConcreteMesonBaryonToResonance & right) const
G4ConcreteMesonBaryonToResonance& G4ConcreteMesonBaryonToResonance::operator= (const G4ConcreteMesonBaryonToResonance &) private
G4bool G4ConcreteMesonBaryonToResonance::operator== (const G4ConcreteMesonBaryonToResonance & right) const
G4BaryonPartialWidth & G4ConcreteMesonBaryonToResonance::theBaryonPartialWidth () static private
Definition at line 45 of file G4ConcreteMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ConcreteMesonBaryonToResonance.cc
References baryonPartialWidth, and InitialisePointers().
Referenced by G4ConcreteMesonBaryonToResonance().
G4BaryonWidth & G4ConcreteMesonBaryonToResonance::theBaryonWidth () static private
Definition at line 39 of file G4ConcreteMesonBaryonToResonance.cc.
View newest version in sPHENIX GitHub at line 39 of file G4ConcreteMesonBaryonToResonance.cc
References baryonWidth, and InitialisePointers().
Referenced by G4ConcreteMesonBaryonToResonance().
Member Data Documentation
G4BaryonPartialWidth * G4ConcreteMesonBaryonToResonance::baryonPartialWidth = nullptr static private
Definition at line 101 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ConcreteMesonBaryonToResonance.hh
Referenced by InitialisePointers(), and theBaryonPartialWidth().
G4BaryonWidth * G4ConcreteMesonBaryonToResonance::baryonWidth = nullptr static private
Definition at line 100 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ConcreteMesonBaryonToResonance.hh
Referenced by InitialisePointers(), and theBaryonWidth().
G4VCrossSectionSource* G4ConcreteMesonBaryonToResonance::crossSectionSource private
Definition at line 91 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ConcreteMesonBaryonToResonance.hh
Referenced by G4ConcreteMesonBaryonToResonance(), GetCrossSectionSource(), and ~G4ConcreteMesonBaryonToResonance().
G4ParticleTypeConverter * G4ConcreteMesonBaryonToResonance::particleTypeConverter = nullptr static private
Definition at line 102 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ConcreteMesonBaryonToResonance.hh
Referenced by InitialisePointers(), and myConv().
const G4ParticleDefinition* G4ConcreteMesonBaryonToResonance::thePrimary1 private
Definition at line 92 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ConcreteMesonBaryonToResonance.hh
Referenced by IsInCharge().
const G4ParticleDefinition* G4ConcreteMesonBaryonToResonance::thePrimary2 private
Definition at line 93 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ConcreteMesonBaryonToResonance.hh
Referenced by IsInCharge().
const G4ParticleDefinition* G4ConcreteMesonBaryonToResonance::theSecondary private
Definition at line 94 of file G4ConcreteMesonBaryonToResonance.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ConcreteMesonBaryonToResonance.hh
Referenced by GetOutgoingParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4ConcreteMesonBaryonToResonance.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4ConcreteMesonBaryonToResonance.cc