ECCE @ EIC Software: G4Integrator< T, F > Class Template Reference
G4Integrator< T, F > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4Integrator.hh>
Public Member Functions
G4Integrator ()
~G4Integrator ()
G4double Simpson (T &typeT, F f, G4double a, G4double b, G4int n)
G4double Simpson (T *ptrT, F f, G4double a, G4double b, G4int n)
G4double Simpson (G4double(*f)(G4double), G4double a, G4double b, G4int n)
G4double AdaptiveGauss (T &typeT, F f, G4double a, G4double b, G4double e)
G4double AdaptiveGauss (T *ptrT, F f, G4double a, G4double b, G4double e)
G4double AdaptiveGauss (G4double(*f)(G4double), G4double a, G4double b, G4double e)
G4double Legendre (T &typeT, F f, G4double a, G4double b, G4int n)
G4double Legendre (T *ptrT, F f, G4double a, G4double b, G4int n)
G4double Legendre (G4double(*f)(G4double), G4double a, G4double b, G4int n)
G4double Legendre10 (T &typeT, F f, G4double a, G4double b)
G4double Legendre10 (T *ptrT, F f, G4double a, G4double b)
G4double Legendre10 (G4double(*f)(G4double), G4double a, G4double b)
G4double Legendre96 (T &typeT, F f, G4double a, G4double b)
G4double Legendre96 (T *ptrT, F f, G4double a, G4double b)
G4double Legendre96 (G4double(*f)(G4double), G4double a, G4double b)
G4double Chebyshev (T &typeT, F f, G4double a, G4double b, G4int n)
G4double Chebyshev (T *ptrT, F f, G4double a, G4double b, G4int n)
G4double Chebyshev (G4double(*f)(G4double), G4double a, G4double b, G4int n)
G4double Laguerre (T &typeT, F f, G4double alpha, G4int n)
G4double Laguerre (T *ptrT, F f, G4double alpha, G4int n)
G4double Laguerre (G4double(*f)(G4double), G4double alpha, G4int n)
G4double Hermite (T &typeT, F f, G4int n)
G4double Hermite (T *ptrT, F f, G4int n)
G4double Hermite (G4double(*f)(G4double), G4int n)
G4double Jacobi (T &typeT, F f, G4double alpha, G4double beta, G4int n)
G4double Jacobi (T *ptrT, F f, G4double alpha, G4double beta, G4int n)
G4double Jacobi (G4double(*f)(G4double), G4double alpha, G4double beta, G4int n)
Protected Member Functions
G4double Gauss (T &typeT, F f, G4double a, G4double b)
G4double Gauss (T *ptrT, F f, G4double a, G4double b)
G4double Gauss (G4double(*f)(G4double), G4double a, G4double b)
void AdaptGauss (T &typeT, F f, G4double a, G4double b, G4double e, G4double &sum, G4int &n)
void AdaptGauss (T *typeT, F f, G4double a, G4double b, G4double e, G4double &sum, G4int &n)
void AdaptGauss (G4double(*f)(G4double), G4double a, G4double b, G4double e, G4double &sum, G4int &n)
G4double GammaLogarithm (G4double xx)
Detailed Description
template<class T, class F>
class G4Integrator< T, F >
Definition at line 48 of file G4Integrator.hh.
View newest version in sPHENIX GitHub at line 48 of file G4Integrator.hh
Constructor & Destructor Documentation
template<class T, class F> G4Integrator< T, F >::G4Integrator () inline
Definition at line 52 of file G4Integrator.hh.
View newest version in sPHENIX GitHub at line 52 of file G4Integrator.hh
template<class T, class F> G4Integrator< T, F >::~G4Integrator () inline
Definition at line 53 of file G4Integrator.hh.
View newest version in sPHENIX GitHub at line 53 of file G4Integrator.hh
Member Function Documentation
template<class T, class F> void G4Integrator< T, F >::AdaptGauss (T & typeT, F f, G4double a, G4double b, G4double e, G4double & sum, G4int & n) protected
template<class T, class F> void G4Integrator< T, F >::AdaptGauss (T * typeT, F f, G4double a, G4double b, G4double e, G4double & sum, G4int & n) protected
template<class T, class F> void G4Integrator< T, F >::AdaptGauss (G4double(*)(G4double) f, G4double a, G4double b, G4double e, G4double & sum, G4int & n) protected
template<class T, class F> G4double G4Integrator< T, F >::AdaptiveGauss (T & typeT, F f, G4double a, G4double b, G4double e)
Referenced by G4NuclNuclDiffuseElastic::TestAngleTable(), and G4DiffuseElastic::TestAngleTable().
template<class T, class F> G4double G4Integrator< T, F >::AdaptiveGauss (T * ptrT, F f, G4double a, G4double b, G4double e)
template<class T, class F> G4double G4Integrator< T, F >::AdaptiveGauss (G4double(*)(G4double) f, G4double a, G4double b, G4double e)
template<class T, class F> G4double G4Integrator< T, F >::Chebyshev (T & typeT, F f, G4double a, G4double b, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Chebyshev (T * ptrT, F f, G4double a, G4double b, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Chebyshev (G4double(*)(G4double) f, G4double a, G4double b, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::GammaLogarithm (G4double xx) protected
template<class T, class F> G4double G4Integrator< T, F >::Gauss (T & typeT, F f, G4double a, G4double b) protected
template<class T, class F> G4double G4Integrator< T, F >::Gauss (T * ptrT, F f, G4double a, G4double b) protected
template<class T, class F> G4double G4Integrator< T, F >::Gauss (G4double(*)(G4double) f, G4double a, G4double b) protected
template<class T, class F> G4double G4Integrator< T, F >::Hermite (T & typeT, F f, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Hermite (T * ptrT, F f, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Hermite (G4double(*)(G4double) f, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Jacobi (T & typeT, F f, G4double alpha, G4double beta, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Jacobi (T * ptrT, F f, G4double alpha, G4double beta, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Jacobi (G4double(*)(G4double) f, G4double alpha, G4double beta, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Laguerre (T & typeT, F f, G4double alpha, G4int n)
Referenced by G4SynchrotronRadiationInMat::GetAngleK(), G4SynchrotronRadiationInMat::GetEnergyProbSR(), and G4SynchrotronRadiationInMat::GetIntProbSR().
template<class T, class F> G4double G4Integrator< T, F >::Laguerre (T * ptrT, F f, G4double alpha, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Laguerre (G4double(*)(G4double) f, G4double alpha, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Legendre (T & typeT, F f, G4double a, G4double b, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Legendre (T * ptrT, F f, G4double a, G4double b, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Legendre (G4double(*)(G4double) f, G4double a, G4double b, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Legendre10 (T & typeT, F f, G4double a, G4double b)
Referenced by G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4NuclNuclDiffuseElastic::BuildAngleTable(), G4DiffuseElasticV2::BuildAngleTable(), G4DiffuseElastic::BuildAngleTable(), G4VXTRenergyLoss::BuildEnergyTable(), G4hhElastic::BuildTableT(), G4hhElastic::BuildTableTest(), G4InitXscPAI::IntegralCherenkov(), G4InitXscPAI::IntegralPAIdEdx(), G4InitXscPAI::IntegralPAIxSection(), G4InitXscPAI::IntegralPlasmon(), G4NuclNuclDiffuseElastic::SampleThetaCMS(), G4DiffuseElastic::SampleThetaCMS(), G4NuclNuclDiffuseElastic::TestAngleTable(), G4DiffuseElastic::TestAngleTable(), and G4VXTRenergyLoss::XTRNSpectralDensity().
template<class T, class F> G4double G4Integrator< T, F >::Legendre10 (T * ptrT, F f, G4double a, G4double b)
template<class T, class F> G4double G4Integrator< T, F >::Legendre10 (G4double(*)(G4double) f, G4double a, G4double b)
template<class T, class F> G4double G4Integrator< T, F >::Legendre96 (T & typeT, F f, G4double a, G4double b)
Referenced by G4VXTRenergyLoss::BuildGlobalAngleTable(), G4DataSet::BuildPdf(), G4RDEMDataSet::BuildPdf(), G4EMDataSet::BuildPdf(), G4NuclNuclDiffuseElastic::GetCint(), G4NuclNuclDiffuseElastic::GetErfInt(), G4NuclNuclDiffuseElastic::GetSint(), G4NeutronElectronElModel::Initialise(), G4NuclNuclDiffuseElastic::IntegralElasticProb(), G4DiffuseElastic::IntegralElasticProb(), G4NuclNuclDiffuseElastic::SampleThetaCMS(), G4DiffuseElastic::SampleThetaCMS(), G4VXTRenergyLoss::SpectralXTRdEdx(), G4NuclNuclDiffuseElastic::TestAngleTable(), G4DiffuseElastic::TestAngleTable(), G4VXTRenergyLoss::XTRNAngleDensity(), and G4VXTRenergyLoss::XTRNSpectralDensity().
template<class T, class F> G4double G4Integrator< T, F >::Legendre96 (T * ptrT, F f, G4double a, G4double b)
template<class T, class F> G4double G4Integrator< T, F >::Legendre96 (G4double(*)(G4double) f, G4double a, G4double b)
template<class T, class F> G4double G4Integrator< T, F >::Simpson (T & typeT, F f, G4double a, G4double b, G4int n)
Referenced by G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForScatProj(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerAtomForSecond(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForScatProj(), G4VEmAdjointModel::ComputeAdjointCrossSectionVectorPerVolumeForSecond(), G4KineticTrack::IntegrandFunction4(), G4KineticTrack::IntegrateCMMomentum(), and G4KineticTrack::IntegrateCMMomentum2().
template<class T, class F> G4double G4Integrator< T, F >::Simpson (T * ptrT, F f, G4double a, G4double b, G4int n)
template<class T, class F> G4double G4Integrator< T, F >::Simpson (G4double(*)(G4double) f, G4double a, G4double b, G4int n)
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4Integrator.hh