ECCE @ EIC Software: CLHEP::DoubConv Class Reference
CLHEP::DoubConv Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/DoubConv.h>
Classes
union DB8
Static Public Member Functions
static std::vector< unsigned long > dto2longs (double d)
static double longs2double (const std::vector< unsigned long > &v)
static std::string d2x (double d)
Static Private Member Functions
static void fill_byte_order ()
Static Private Attributes
static CLHEP_THREAD_LOCAL bool byte_order_known = false
static CLHEP_THREAD_LOCAL int byte_order [8]
Detailed Description
Definition at line 28 of file DoubConv.h.
View newest version in sPHENIX GitHub at line 28 of file DoubConv.h
Member Function Documentation
std::string CLHEP::DoubConv::d2x (double d) static
Definition at line 81 of file DoubConv.cc.
View newest version in sPHENIX GitHub at line 81 of file DoubConv.cc
References CLHEP::DoubConv::DB8::b, byte_order, byte_order_known, CLHEP::DoubConv::DB8::d, d, Acts::Test::db, fill_byte_order(), int(), and k.
std::vector< unsigned long > CLHEP::DoubConv::dto2longs (double d) static
Definition at line 93 of file DoubConv.cc.
View newest version in sPHENIX GitHub at line 93 of file DoubConv.cc
References CLHEP::DoubConv::DB8::b, byte_order, byte_order_known, CLHEP::DoubConv::DB8::d, d, Acts::Test::db, fill_byte_order(), and v.
Referenced by CLHEP::RandPoissonQ::put(), CLHEP::RandStudentT::put(), CLHEP::RandPoisson::put(), CLHEP::NonRandomEngine::put(), CLHEP::RandExponential::put(), CLHEP::RandChiSquare::put(), CLHEP::RandGamma::put(), CLHEP::RandBinomial::put(), CLHEP::Ranlux64Engine::put(), CLHEP::HepJamesRandom::put(), CLHEP::RandExpZiggurat::put(), CLHEP::RandGauss::put(), CLHEP::RandGeneral::put(), CLHEP::RandBreitWigner::put(), CLHEP::RandFlat::put(), CLHEP::RandGauss::saveDistState(), and CLHEP::RandGauss::saveEngineStatus().
void CLHEP::DoubConv::fill_byte_order () static private
Definition at line 18 of file DoubConv.cc.
View newest version in sPHENIX GitHub at line 18 of file DoubConv.cc
References CLHEP::DoubConv::DB8::b, byte_order, byte_order_known, CLHEP::DoubConv::DB8::d, k, n, x, y, and z.
Referenced by d2x(), dto2longs(), and longs2double().
double CLHEP::DoubConv::longs2double (const std::vector< unsigned long > & v) static
Definition at line 109 of file DoubConv.cc.
View newest version in sPHENIX GitHub at line 109 of file DoubConv.cc
References CLHEP::DoubConv::DB8::b, byte_order, byte_order_known, CLHEP::DoubConv::DB8::d, Acts::Test::db, and fill_byte_order().
Referenced by CLHEP::RandPoissonQ::get(), CLHEP::RandStudentT::get(), CLHEP::RandPoisson::get(), CLHEP::RandExponential::get(), CLHEP::RandChiSquare::get(), CLHEP::RandBinomial::get(), CLHEP::RandGamma::get(), CLHEP::RandExpZiggurat::get(), CLHEP::RandGauss::get(), CLHEP::RandGeneral::get(), CLHEP::RandBreitWigner::get(), CLHEP::RandFlat::get(), CLHEP::NonRandomEngine::getState(), CLHEP::HepJamesRandom::getState(), CLHEP::Ranlux64Engine::getState(), CLHEP::RandGauss::restoreDistState(), and CLHEP::RandGauss::restoreEngineStatus().
Member Data Documentation
CLHEP_THREAD_LOCAL int CLHEP::DoubConv::byte_order static private
Definition at line 60 of file DoubConv.h.
View newest version in sPHENIX GitHub at line 60 of file DoubConv.h
Referenced by d2x(), dto2longs(), fill_byte_order(), and longs2double().
CLHEP_THREAD_LOCAL bool CLHEP::DoubConv::byte_order_known = false static private
Definition at line 59 of file DoubConv.h.
View newest version in sPHENIX GitHub at line 59 of file DoubConv.h
Referenced by d2x(), dto2longs(), fill_byte_order(), and longs2double().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/DoubConv.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/DoubConv.cc