ECCE @ EIC Software: G4StatMFMacroMultiplicity Class Reference
G4StatMFMacroMultiplicity Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroMultiplicity.hh>
Public Member Functions
G4StatMFMacroMultiplicity (const G4double anA, const G4double kappa, const G4double temp, const G4double nu, std::vector< G4VStatMFMacroCluster * > *ClusterVector)
~G4StatMFMacroMultiplicity ()
G4double operator() (const G4double mu)
G4double GetMeanMultiplicity (void) const
G4double GetChemicalPotentialMu (void) const
G4double CalcChemicalPotentialMu (void)
Private Member Functions
G4StatMFMacroMultiplicity ()
G4StatMFMacroMultiplicity (const G4StatMFMacroMultiplicity &)
G4StatMFMacroMultiplicity & operator= (const G4StatMFMacroMultiplicity &right)
G4bool operator== (const G4StatMFMacroMultiplicity &right) const
G4bool operator!= (const G4StatMFMacroMultiplicity &right) const
G4double CalcMeanA (const G4double mu)
Private Attributes
G4double theA
G4double _Kappa
G4double _MeanMultiplicity
G4double _MeanTemperature
G4double _ChemPotentialMu
G4double _ChemPotentialNu
std::vector
< G4VStatMFMacroCluster * > * _theClusters
Detailed Description
Definition at line 42 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 42 of file G4StatMFMacroMultiplicity.hh
Constructor & Destructor Documentation
G4StatMFMacroMultiplicity::G4StatMFMacroMultiplicity (const G4double anA, const G4double kappa, const G4double temp, const G4double nu, std::vector< G4VStatMFMacroCluster * > * ClusterVector) inline
Definition at line 46 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 46 of file G4StatMFMacroMultiplicity.hh
G4StatMFMacroMultiplicity::~G4StatMFMacroMultiplicity () inline
Definition at line 60 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 60 of file G4StatMFMacroMultiplicity.hh
G4StatMFMacroMultiplicity::G4StatMFMacroMultiplicity () inline private
Definition at line 67 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 67 of file G4StatMFMacroMultiplicity.hh
G4StatMFMacroMultiplicity::G4StatMFMacroMultiplicity (const G4StatMFMacroMultiplicity &) inline private
Definition at line 70 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 70 of file G4StatMFMacroMultiplicity.hh
Member Function Documentation
G4double G4StatMFMacroMultiplicity::CalcChemicalPotentialMu (void)
Definition at line 62 of file G4StatMFMacroMultiplicity.cc.
View newest version in sPHENIX GitHub at line 62 of file G4StatMFMacroMultiplicity.cc
References _ChemPotentialMu, _ChemPotentialNu, _MeanTemperature, _theClusters, kdfinder::abs(), G4StatMFParameters::Beta(), G4Solver< Function >::Brent(), G4cout, G4endl, G4StatMFParameters::GetCoulomb(), G4StatMFParameters::GetE0(), G4StatMFParameters::GetGamma0(), G4Pow::GetInstance(), G4Solver< Function >::GetRoot(), operator()(), G4Solver< Function >::SetIntervalLimits(), G4Pow::Z13(), and G4Pow::Z23().
Referenced by G4StatMFMacroChemicalPotential::CalcChemicalPotentialMu().
G4double G4StatMFMacroMultiplicity::CalcMeanA (const G4double mu) private
Definition at line 141 of file G4StatMFMacroMultiplicity.cc.
View newest version in sPHENIX GitHub at line 141 of file G4StatMFMacroMultiplicity.cc
References _ChemPotentialNu, _Kappa, _MeanMultiplicity, _MeanTemperature, _theClusters, G4StatMFParameters::Getr0(), n, pi, and theA.
Referenced by operator()().
G4double G4StatMFMacroMultiplicity::GetChemicalPotentialMu (void) const inline
Definition at line 82 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 82 of file G4StatMFMacroMultiplicity.hh
References _ChemPotentialMu.
G4double G4StatMFMacroMultiplicity::GetMeanMultiplicity (void) const inline
Definition at line 80 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 80 of file G4StatMFMacroMultiplicity.hh
References _MeanMultiplicity.
Referenced by G4StatMFMacroChemicalPotential::CalcChemicalPotentialMu().
G4bool G4StatMFMacroMultiplicity::operator!= (const G4StatMFMacroMultiplicity & right) const private
Definition at line 56 of file G4StatMFMacroMultiplicity.cc.
View newest version in sPHENIX GitHub at line 56 of file G4StatMFMacroMultiplicity.cc
G4double G4StatMFMacroMultiplicity::operator() (const G4double mu) inline
Definition at line 62 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 62 of file G4StatMFMacroMultiplicity.hh
References CalcMeanA(), and theA.
Referenced by CalcChemicalPotentialMu().
G4StatMFMacroMultiplicity & G4StatMFMacroMultiplicity::operator= (const G4StatMFMacroMultiplicity & right) private
Definition at line 43 of file G4StatMFMacroMultiplicity.cc.
View newest version in sPHENIX GitHub at line 43 of file G4StatMFMacroMultiplicity.cc
G4bool G4StatMFMacroMultiplicity::operator== (const G4StatMFMacroMultiplicity & right) const private
Definition at line 49 of file G4StatMFMacroMultiplicity.cc.
View newest version in sPHENIX GitHub at line 49 of file G4StatMFMacroMultiplicity.cc
Member Data Documentation
G4double G4StatMFMacroMultiplicity::_ChemPotentialMu private
Definition at line 100 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 100 of file G4StatMFMacroMultiplicity.hh
Referenced by CalcChemicalPotentialMu(), and GetChemicalPotentialMu().
G4double G4StatMFMacroMultiplicity::_ChemPotentialNu private
Definition at line 102 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 102 of file G4StatMFMacroMultiplicity.hh
Referenced by CalcChemicalPotentialMu(), and CalcMeanA().
G4double G4StatMFMacroMultiplicity::_Kappa private
Definition at line 94 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 94 of file G4StatMFMacroMultiplicity.hh
Referenced by CalcMeanA().
G4double G4StatMFMacroMultiplicity::_MeanMultiplicity private
Definition at line 96 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 96 of file G4StatMFMacroMultiplicity.hh
Referenced by CalcMeanA(), and GetMeanMultiplicity().
G4double G4StatMFMacroMultiplicity::_MeanTemperature private
Definition at line 98 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 98 of file G4StatMFMacroMultiplicity.hh
Referenced by CalcChemicalPotentialMu(), and CalcMeanA().
std::vector<G4VStatMFMacroCluster*>* G4StatMFMacroMultiplicity::_theClusters private
Definition at line 104 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 104 of file G4StatMFMacroMultiplicity.hh
Referenced by CalcChemicalPotentialMu(), and CalcMeanA().
G4double G4StatMFMacroMultiplicity::theA private
Definition at line 92 of file G4StatMFMacroMultiplicity.hh.
View newest version in sPHENIX GitHub at line 92 of file G4StatMFMacroMultiplicity.hh
Referenced by CalcMeanA(), and operator()().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroMultiplicity.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMacroMultiplicity.cc