ECCE @ EIC Software: G4EmCorrections Class Reference
G4EmCorrections Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmCorrections.hh>
Public Member Functions
G4EmCorrections (G4int verb)
virtual ~G4EmCorrections ()
G4double HighOrderCorrections (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy, G4double cutEnergy)
G4double IonHighOrderCorrections (const G4ParticleDefinition *, const G4MaterialCutsCouple *, G4double kineticEnergy)
G4double ComputeIonCorrections (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double IonBarkasCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double Bethe (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double SpinCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double KShellCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double LShellCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double ShellCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double ShellCorrectionSTD (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double DensityCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double BarkasCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double BlochCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double MottCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
void AddStoppingData (G4int Z, G4int A, const G4String &materialName, G4PhysicsVector *dVector)
void InitialiseForNewRun ()
G4double EffectiveChargeCorrection (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double EffectiveChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
void SetIonisationModels (G4VEmModel *m1=nullptr, G4VEmModel *m2=nullptr)
G4int GetNumberOfStoppingVectors () const
void SetVerbose (G4int verb)
Private Member Functions
void Initialise ()
void BuildCorrectionVector ()
void SetupKinematics (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
G4double KShell (G4double theta, G4double eta)
G4double LShell (G4double theta, G4double eta)
G4int Index (G4double x, const G4double *y, G4int n) const
G4double Value (G4double xv, G4double x1, G4double x2, G4double y1, G4double y2) const
G4double Value2 (G4double xv, G4double yv, G4double x1, G4double x2, G4double y1, G4double y2, G4double z11, G4double z21, G4double z12, G4double z22) const
G4EmCorrections & operator= (const G4EmCorrections &right)=delete
G4EmCorrections (const G4EmCorrections &)=delete
Private Attributes
G4Pow * g4calc
G4double alpha2
std::vector< const G4Material * > currmat
std::map< G4int, std::vector
< G4double > > thcorr
size_t ncouples
const G4ParticleDefinition * particle
const G4ParticleDefinition * curParticle
const G4Material * material
const G4Material * curMaterial
const G4ElementVector * theElementVector
const G4double * atomDensity
G4PhysicsVector * curVector
G4IonTable * ionTable
G4VEmModel * ionLEModel
G4VEmModel * ionHEModel
G4double kinEnergy
G4double mass
G4double massFactor
G4double eth
G4double tau
G4double gamma
G4double bg2
G4double beta2
G4double beta
G4double ba2
G4double tmax
G4double charge
G4double q2
G4double eCorrMin
G4double eCorrMax
G4int verbose
G4int nK
G4int nL
G4int nEtaK
G4int nEtaL
G4int nbinCorr
G4int numberOfElements
G4int nIons
G4int idx
G4int currentZ
std::vector< G4int > Zion
std::vector< G4int > Aion
std::vector< G4String > materialName
std::vector< const
G4ParticleDefinition * > ionList
std::vector< const G4Material * > materialList
std::vector< G4PhysicsVector * > stopData
G4bool isMaster
G4ionEffectiveCharge effCharge
Static Private Attributes
static const G4double ZD [11]
static const G4double UK [20]
static const G4double VK [20]
static G4double ZK [20] = {0.0}
static const G4double Eta [29]
static G4double CK [20][29]
static G4double CL [26][28]
static const G4double UL [26]
static G4double VL [26] = {0.0}
static G4LPhysicsFreeVector * BarkasCorr = nullptr
static G4LPhysicsFreeVector * ThetaK = nullptr
static G4LPhysicsFreeVector * ThetaL = nullptr
Detailed Description
Definition at line 70 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 70 of file G4EmCorrections.hh
Constructor & Destructor Documentation
G4EmCorrections::G4EmCorrections (G4int verb) explicit
Definition at line 111 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 111 of file G4EmCorrections.cc
References alpha2, atomDensity, ba2, BarkasCorr, beta, beta2, bg2, charge, curMaterial, curParticle, currentZ, curVector, eCorrMax, eCorrMin, eth, CLHEP::fine_structure_const, g4calc, gamma, G4Pow::GetInstance(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), idx, Initialise(), ionHEModel, ionLEModel, ionTable, isMaster, CLHEP::keV, kinEnergy, mass, massFactor, material, CLHEP::MeV, nbinCorr, ncouples, nEtaK, nEtaL, nIons, nK, nL, numberOfElements, particle, q2, tau, theElementVector, tmax, and verbose.
G4EmCorrections::~G4EmCorrections () virtual
Definition at line 156 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 156 of file G4EmCorrections.cc
References BarkasCorr, isMaster, nIons, stopData, ThetaK, and ThetaL.
G4EmCorrections::G4EmCorrections (const G4EmCorrections &) private delete
Member Function Documentation
void G4EmCorrections::AddStoppingData (G4int Z, G4int A, const G4String & materialName, G4PhysicsVector * dVector)
Definition at line 815 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 815 of file G4EmCorrections.cc
References Aion, G4cout, G4endl, ionList, materialList, materialName, nIons, stopData, verbose, and Zion.
Referenced by G4ionIonisation::AddStoppingData(), and G4WaterStopping::Initialise().
G4double G4EmCorrections::BarkasCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 676 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 676 of file G4EmCorrections.cc
References atomDensity, b, ba2, BarkasCorr, beta, charge, G4PhysicsVector::Energy(), G4Exp(), G4Log(), G4Material::GetName(), G4Material::GetTotNbOfAtomsPerVolume(), material, numberOfElements, SetupKinematics(), G4PhysicsVector::Value(), X, and Z.
Referenced by G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), ComputeIonCorrections(), G4LindhardSorensenIonModel::CorrectionsAlongStep(), HighOrderCorrections(), and IonBarkasCorrection().
G4double G4EmCorrections::Bethe (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 325 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 325 of file G4EmCorrections.cc
References beta2, bg2, source.hepunit::electron_mass_c2, G4Log(), G4Material::GetIonisation(), G4IonisParamMat::GetMeanExcitationEnergy(), material, SetupKinematics(), and tmax.
G4double G4EmCorrections::BlochCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 730 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 730 of file G4EmCorrections.cc
References ba2, q2, SetupKinematics(), and y2.
Referenced by ComputeIonCorrections(), and HighOrderCorrections().
void G4EmCorrections::BuildCorrectionVector () private
Definition at line 840 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 840 of file G4EmCorrections.cc
References A(), Aion, G4VEmModel::ComputeDEDXPerVolume(), ComputeIonCorrections(), curMaterial, curParticle, currentZ, e, eCorrMax, eCorrMin, effCharge, G4ionEffectiveCharge::EffectiveChargeSquareRatio(), G4PhysicsVector::Energy(), eth, G4cout, G4endl, G4GenericIon::GenericIon(), G4ParticleDefinition::GetBaryonNumber(), G4IonTable::GetIon(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), idx, ionHEModel, ionLEModel, ionList, ionTable, massFactor, materialName, MeV, nbinCorr, source.hepunit::proton_mass_c2, G4PhysicsVector::PutValue(), G4PhysicsVector::SetSpline(), stopData, v, verbose, Z, and Zion.
Referenced by EffectiveChargeCorrection().
G4double G4EmCorrections::ComputeIonCorrections (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 243 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 243 of file G4EmCorrections.cc
References BarkasCorrection(), beta2, BlochCorrection(), charge, G4cout, G4endl, G4Material::GetElectronDensity(), material, MeV, MottCorrection(), q2, SetupKinematics(), sum, tau, source.hepunit::twopi_mc2_rcl2, and verbose.
Referenced by BuildCorrectionVector(), and IonHighOrderCorrections().
G4double G4EmCorrections::DensityCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 649 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 649 of file G4EmCorrections.cc
References bg2, G4Exp(), G4Log(), G4IonisParamMat::GetAdensity(), G4IonisParamMat::GetCdensity(), G4Material::GetIonisation(), G4IonisParamMat::GetMdensity(), G4IonisParamMat::GetX0density(), G4IonisParamMat::GetX1density(), material, SetupKinematics(), and x.
G4double G4EmCorrections::EffectiveChargeCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 766 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 766 of file G4EmCorrections.cc
References source.hepunit::amu_c2, BuildCorrectionVector(), curMaterial, curParticle, currentZ, curVector, CLHEP::eplus, G4cout, G4endl, G4ParticleDefinition::GetAtomicNumber(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), idx, ionList, massFactor, mat, materialList, MeV, nIons, source.hepunit::proton_mass_c2, stopData, G4PhysicsVector::Value(), verbose, and Zion.
Referenced by G4BetheBlochModel::CorrectionsAlongStep(), G4BraggIonModel::CorrectionsAlongStep(), G4AtimaEnergyLossModel::GetChargeSquareRatio(), G4BetheBlochModel::GetChargeSquareRatio(), G4BraggIonModel::GetChargeSquareRatio(), G4BraggModel::GetChargeSquareRatio(), and G4EmCalculator::UpdateParticle().
G4double G4EmCorrections::EffectiveChargeSquareRatio (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) inline
Definition at line 317 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 317 of file G4EmCorrections.hh
References effCharge, and G4ionEffectiveCharge::EffectiveChargeSquareRatio().
Referenced by G4BetheBlochModel::CorrectionsAlongStep(), G4BraggIonModel::CorrectionsAlongStep(), G4AtimaEnergyLossModel::GetChargeSquareRatio(), G4BetheBlochModel::GetChargeSquareRatio(), G4BraggModel::GetChargeSquareRatio(), G4BraggIonModel::GetChargeSquareRatio(), G4UAtomicDeexcitation::GetShellIonisationCrossSectionPerAtom(), G4ContinuousGainOfEnergy::SetDynamicMassCharge(), and G4EmCalculator::UpdateParticle().
G4int G4EmCorrections::GetNumberOfStoppingVectors () const inline
Definition at line 303 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 303 of file G4EmCorrections.hh
References nIons.
Referenced by G4ionIonisation::StreamProcessInfo().
G4double G4EmCorrections::GetParticleCharge (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) inline
Definition at line 309 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 309 of file G4EmCorrections.hh
References effCharge, and G4ionEffectiveCharge::EffectiveCharge().
Referenced by G4AtimaEnergyLossModel::GetParticleCharge(), G4BetheBlochModel::GetParticleCharge(), G4BraggIonModel::GetParticleCharge(), and G4BraggModel::GetParticleCharge().
G4double G4EmCorrections::HighOrderCorrections (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy, G4double cutEnergy)
Definition at line 198 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 198 of file G4EmCorrections.cc
References BarkasCorrection(), beta2, BlochCorrection(), G4cout, G4endl, G4Material::GetElectronDensity(), G4Material::GetName(), KShellCorrection(), LShellCorrection(), material, MeV, MottCorrection(), q2, SetupKinematics(), ShellCorrection(), sum, tau, source.hepunit::twopi_mc2_rcl2, and verbose.
Referenced by G4BetheBlochModel::ComputeDEDXPerVolume(), and G4MuBetheBlochModel::ComputeDEDXPerVolume().
G4int G4EmCorrections::Index (G4double x, const G4double * y, G4int n) const inline private
Definition at line 270 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 270 of file G4EmCorrections.hh
Referenced by KShell(), and LShell().
void G4EmCorrections::Initialise () private
Definition at line 938 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 938 of file G4EmCorrections.cc
References b, BarkasCorr, c, CK, CL, Eta, G4Log(), isMaster, G4Threading::IsMasterThread(), nEtaK, nEtaL, nK, nL, G4LPhysicsFreeVector::PutValues(), G4PhysicsVector::SetSpline(), SL, ThetaK, ThetaL, UK, UL, VK, VL, and ZK.
Referenced by G4EmCorrections().
void G4EmCorrections::InitialiseForNewRun ()
Definition at line 915 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 915 of file G4EmCorrections.cc
References clear(), currmat, G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), it, materialList, materialName, ncouples, nIons, and thcorr.
Referenced by G4ionIonisation::InitialiseEnergyLossProcess().
G4double G4EmCorrections::IonBarkasCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 233 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 233 of file G4EmCorrections.cc
References BarkasCorrection(), beta2, G4Material::GetElectronDensity(), material, q2, and source.hepunit::twopi_mc2_rcl2.
Referenced by G4BetheBlochModel::ComputeDEDXPerVolume().
G4double G4EmCorrections::IonHighOrderCorrections (const G4ParticleDefinition * p, const G4MaterialCutsCouple * couple, G4double kineticEnergy)
Definition at line 275 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 275 of file G4EmCorrections.cc
References ComputeIonCorrections(), currmat, e, eth, G4cout, G4endl, G4lrint(), G4MaterialCutsCouple::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), inveplus, ionHEModel, ncouples, source.hepunit::proton_mass_c2, sum, thcorr, v, verbose, and Z.
Referenced by G4BetheBlochModel::CorrectionsAlongStep().
G4double G4EmCorrections::KShell (G4double theta, G4double eta) private
Definition at line 416 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 416 of file G4EmCorrections.cc
References CK, Acts::VectorHelpers::eta(), Eta, Index(), nEtaK, nK, UK, Value(), Value2(), VK, x, y, and ZK.
Referenced by KShellCorrection(), and ShellCorrection().
G4double G4EmCorrections::KShellCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 349 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 349 of file G4EmCorrections.cc
References alpha2, atomDensity, ba2, Acts::VectorHelpers::eta(), f, G4Material::GetTotNbOfAtomsPerVolume(), KShell(), material, numberOfElements, SetupKinematics(), ThetaK, G4PhysicsVector::Value(), Z, and Z2.
Referenced by HighOrderCorrections().
G4double G4EmCorrections::LShell (G4double theta, G4double eta) private
Definition at line 464 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 464 of file G4EmCorrections.cc
References CL, Acts::VectorHelpers::eta(), Eta, Index(), nEtaL, nL, UL, Value(), Value2(), VL, x, and y.
Referenced by LShellCorrection(), and ShellCorrection().
G4double G4EmCorrections::LShellCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 378 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 378 of file G4EmCorrections.cc
References alpha2, atomDensity, ba2, Acts::VectorHelpers::eta(), f, G4AtomicShells::GetNumberOfElectrons(), G4AtomicShells::GetNumberOfShells(), G4Material::GetTotNbOfAtomsPerVolume(), LShell(), material, min, nmax, numberOfElements, SetupKinematics(), ThetaL, G4PhysicsVector::Value(), Z, Z2, and ZD.
Referenced by HighOrderCorrections().
G4double G4EmCorrections::MottCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 754 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 754 of file G4EmCorrections.cc
References beta, charge, source.hepunit::fine_structure_const, CLHEP::pi, and SetupKinematics().
Referenced by ComputeIonCorrections(), and HighOrderCorrections().
G4EmCorrections& G4EmCorrections::operator= (const G4EmCorrections & right) private delete
void G4EmCorrections::SetIonisationModels (G4VEmModel * m1 = nullptr, G4VEmModel * m2 = nullptr) inline
Definition at line 297 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 297 of file G4EmCorrections.hh
References ionHEModel, and ionLEModel.
Referenced by G4ionIonisation::InitialiseEnergyLossProcess().
void G4EmCorrections::SetupKinematics (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy) private
Definition at line 167 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 167 of file G4EmCorrections.cc
References alpha2, atomDensity, ba2, beta, beta2, bg2, charge, effCharge, G4ionEffectiveCharge::EffectiveCharge(), CLHEP::electron_mass_c2, gamma, G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), inveplus, kinEnergy, mass, mat, material, numberOfElements, particle, q2, ratio, tau, theElementVector, and tmax.
Referenced by BarkasCorrection(), Bethe(), BlochCorrection(), ComputeIonCorrections(), DensityCorrection(), HighOrderCorrections(), KShellCorrection(), LShellCorrection(), MottCorrection(), ShellCorrection(), ShellCorrectionSTD(), and SpinCorrection().
void G4EmCorrections::SetVerbose (G4int verb) inline
Definition at line 324 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 324 of file G4EmCorrections.hh
References verbose.
Referenced by G4LossTableManager::ResetParameters().
G4double G4EmCorrections::ShellCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 546 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 546 of file G4EmCorrections.cc
References alpha2, atomDensity, ba2, Acts::VectorHelpers::eta(), f, G4AtomicShells::GetNumberOfElectrons(), G4AtomicShells::GetNumberOfShells(), G4Material::GetTotNbOfAtomsPerVolume(), KShell(), LShell(), material, min, nmax, norm, numberOfElements, SetupKinematics(), ThetaK, ThetaL, G4PhysicsVector::Value(), Z, Z2, and ZD.
Referenced by G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4MuBetheBlochModel::ComputeDEDXPerVolume(), and HighOrderCorrections().
G4double G4EmCorrections::ShellCorrectionSTD (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 512 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 512 of file G4EmCorrections.cc
References bg2, G4Log(), G4Material::GetIonisation(), G4IonisParamMat::GetShellCorrectionVector(), G4IonisParamMat::GetTaul(), k, mass, material, MeV, SetupKinematics(), tau, and x.
G4double G4EmCorrections::SpinCorrection (const G4ParticleDefinition * p, const G4Material * mat, G4double kineticEnergy)
Definition at line 338 of file G4EmCorrections.cc.
View newest version in sPHENIX GitHub at line 338 of file G4EmCorrections.cc
References kinEnergy, mass, SetupKinematics(), and tmax.
G4double G4EmCorrections::Value (G4double xv, G4double x1, G4double x2, G4double y1, G4double y2) const inline private
Definition at line 278 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 278 of file G4EmCorrections.hh
References x1, and y1.
Referenced by KShell(), and LShell().
G4double G4EmCorrections::Value2 (G4double xv, G4double yv, G4double x1, G4double x2, G4double y1, G4double y2, G4double z11, G4double z21, G4double z12, G4double z22) const inline private
Definition at line 284 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 284 of file G4EmCorrections.hh
References x1.
Referenced by KShell(), and LShell().
Member Data Documentation
std::vector<G4int> G4EmCorrections::Aion private
Definition at line 257 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 257 of file G4EmCorrections.hh
Referenced by AddStoppingData(), and BuildCorrectionVector().
G4double G4EmCorrections::alpha2 private
Definition at line 207 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 207 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), KShellCorrection(), LShellCorrection(), SetupKinematics(), and ShellCorrection().
const G4double* G4EmCorrections::atomDensity private
Definition at line 218 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 218 of file G4EmCorrections.hh
Referenced by BarkasCorrection(), G4EmCorrections(), KShellCorrection(), LShellCorrection(), SetupKinematics(), and ShellCorrection().
G4double G4EmCorrections::ba2 private
Definition at line 235 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 235 of file G4EmCorrections.hh
Referenced by BarkasCorrection(), BlochCorrection(), G4EmCorrections(), KShellCorrection(), LShellCorrection(), SetupKinematics(), and ShellCorrection().
G4LPhysicsFreeVector * G4EmCorrections::BarkasCorr = nullptr static private
Definition at line 203 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 203 of file G4EmCorrections.hh
Referenced by BarkasCorrection(), G4EmCorrections(), Initialise(), and ~G4EmCorrections().
G4double G4EmCorrections::beta private
Definition at line 234 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 234 of file G4EmCorrections.hh
Referenced by BarkasCorrection(), G4EmCorrections(), MottCorrection(), and SetupKinematics().
G4double G4EmCorrections::beta2 private
Definition at line 233 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 233 of file G4EmCorrections.hh
Referenced by Bethe(), ComputeIonCorrections(), G4EmCorrections(), HighOrderCorrections(), IonBarkasCorrection(), and SetupKinematics().
G4double G4EmCorrections::bg2 private
Definition at line 232 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 232 of file G4EmCorrections.hh
Referenced by Bethe(), DensityCorrection(), G4EmCorrections(), SetupKinematics(), and ShellCorrectionSTD().
G4double G4EmCorrections::charge private
Definition at line 237 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 237 of file G4EmCorrections.hh
Referenced by BarkasCorrection(), ComputeIonCorrections(), G4EmCorrections(), MottCorrection(), and SetupKinematics().
G4double G4EmCorrections::CK static private
Definition at line 198 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 198 of file G4EmCorrections.hh
Referenced by Initialise(), and KShell().
G4double G4EmCorrections::CL static private
Definition at line 199 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 199 of file G4EmCorrections.hh
Referenced by Initialise(), and LShell().
const G4Material* G4EmCorrections::curMaterial private
Definition at line 216 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 216 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), EffectiveChargeCorrection(), and G4EmCorrections().
const G4ParticleDefinition* G4EmCorrections::curParticle private
Definition at line 214 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 214 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), EffectiveChargeCorrection(), and G4EmCorrections().
G4int G4EmCorrections::currentZ private
Definition at line 255 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 255 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), EffectiveChargeCorrection(), and G4EmCorrections().
std::vector<const G4Material*> G4EmCorrections::currmat private
Definition at line 209 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 209 of file G4EmCorrections.hh
Referenced by InitialiseForNewRun(), and IonHighOrderCorrections().
G4PhysicsVector* G4EmCorrections::curVector private
Definition at line 220 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 220 of file G4EmCorrections.hh
Referenced by EffectiveChargeCorrection(), and G4EmCorrections().
G4double G4EmCorrections::eCorrMax private
Definition at line 240 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 240 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), and G4EmCorrections().
G4double G4EmCorrections::eCorrMin private
Definition at line 239 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 239 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), and G4EmCorrections().
G4ionEffectiveCharge G4EmCorrections::effCharge private
Definition at line 266 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 266 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), EffectiveChargeSquareRatio(), GetParticleCharge(), and SetupKinematics().
const G4double G4EmCorrections::Eta static private
Initial value:
= {0.005, 0.007, 0.01, 0.015, 0.02,
                            0.03,  0.04,  0.05, 0.06,  0.08,
                            0.1,   0.15,  0.2,  0.3,   0.4,
                            0.5,   0.6,   0.7,  0.8,   1.0,
                            1.2,   1.4,   1.5,  1.7,   2.0, 3.0, 5.0, 7.0, 10.}
Definition at line 197 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 197 of file G4EmCorrections.hh
Referenced by Initialise(), KShell(), and LShell().
G4double G4EmCorrections::eth private
Definition at line 229 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 229 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), G4EmCorrections(), and IonHighOrderCorrections().
G4Pow* G4EmCorrections::g4calc private
Definition at line 191 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 191 of file G4EmCorrections.hh
Referenced by G4EmCorrections().
G4double G4EmCorrections::gamma private
Definition at line 231 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 231 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), and SetupKinematics().
G4int G4EmCorrections::idx private
Definition at line 254 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 254 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), EffectiveChargeCorrection(), and G4EmCorrections().
G4VEmModel* G4EmCorrections::ionHEModel private
Definition at line 224 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 224 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), G4EmCorrections(), IonHighOrderCorrections(), and SetIonisationModels().
G4VEmModel* G4EmCorrections::ionLEModel private
Definition at line 223 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 223 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), G4EmCorrections(), and SetIonisationModels().
std::vector<const G4ParticleDefinition*> G4EmCorrections::ionList private
Definition at line 260 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 260 of file G4EmCorrections.hh
Referenced by AddStoppingData(), BuildCorrectionVector(), and EffectiveChargeCorrection().
G4IonTable* G4EmCorrections::ionTable private
Definition at line 222 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 222 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), and G4EmCorrections().
G4bool G4EmCorrections::isMaster private
Definition at line 265 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 265 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), Initialise(), and ~G4EmCorrections().
G4double G4EmCorrections::kinEnergy private
Definition at line 226 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 226 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), SetupKinematics(), and SpinCorrection().
G4double G4EmCorrections::mass private
Definition at line 227 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 227 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), SetupKinematics(), ShellCorrectionSTD(), and SpinCorrection().
G4double G4EmCorrections::massFactor private
Definition at line 228 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 228 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), EffectiveChargeCorrection(), and G4EmCorrections().
const G4Material* G4EmCorrections::material private
Definition at line 215 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 215 of file G4EmCorrections.hh
Referenced by BarkasCorrection(), Bethe(), ComputeIonCorrections(), DensityCorrection(), G4EmCorrections(), HighOrderCorrections(), IonBarkasCorrection(), KShellCorrection(), LShellCorrection(), SetupKinematics(), ShellCorrection(), and ShellCorrectionSTD().
std::vector<const G4Material*> G4EmCorrections::materialList private
Definition at line 262 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 262 of file G4EmCorrections.hh
Referenced by AddStoppingData(), EffectiveChargeCorrection(), and InitialiseForNewRun().
std::vector<G4String> G4EmCorrections::materialName private
Definition at line 258 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 258 of file G4EmCorrections.hh
Referenced by AddStoppingData(), BuildCorrectionVector(), and InitialiseForNewRun().
G4int G4EmCorrections::nbinCorr private
Definition at line 249 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 249 of file G4EmCorrections.hh
Referenced by BuildCorrectionVector(), and G4EmCorrections().
size_t G4EmCorrections::ncouples private
Definition at line 211 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 211 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), InitialiseForNewRun(), and IonHighOrderCorrections().
G4int G4EmCorrections::nEtaK private
Definition at line 246 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 246 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), Initialise(), and KShell().
G4int G4EmCorrections::nEtaL private
Definition at line 247 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 247 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), Initialise(), and LShell().
G4int G4EmCorrections::nIons private
Definition at line 253 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 253 of file G4EmCorrections.hh
Referenced by AddStoppingData(), EffectiveChargeCorrection(), G4EmCorrections(), GetNumberOfStoppingVectors(), InitialiseForNewRun(), and ~G4EmCorrections().
G4int G4EmCorrections::nK private
Definition at line 244 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 244 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), Initialise(), and KShell().
G4int G4EmCorrections::nL private
Definition at line 245 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 245 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), Initialise(), and LShell().
G4int G4EmCorrections::numberOfElements private
Definition at line 250 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 250 of file G4EmCorrections.hh
Referenced by BarkasCorrection(), G4EmCorrections(), KShellCorrection(), LShellCorrection(), SetupKinematics(), and ShellCorrection().
const G4ParticleDefinition* G4EmCorrections::particle private
Definition at line 213 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 213 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), and SetupKinematics().
G4double G4EmCorrections::q2 private
Definition at line 238 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 238 of file G4EmCorrections.hh
Referenced by BlochCorrection(), ComputeIonCorrections(), G4EmCorrections(), HighOrderCorrections(), IonBarkasCorrection(), and SetupKinematics().
std::vector<G4PhysicsVector*> G4EmCorrections::stopData private
Definition at line 263 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 263 of file G4EmCorrections.hh
Referenced by AddStoppingData(), BuildCorrectionVector(), EffectiveChargeCorrection(), and ~G4EmCorrections().
G4double G4EmCorrections::tau private
Definition at line 230 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 230 of file G4EmCorrections.hh
Referenced by ComputeIonCorrections(), G4EmCorrections(), HighOrderCorrections(), SetupKinematics(), and ShellCorrectionSTD().
std::map< G4int, std::vector<G4double> > G4EmCorrections::thcorr private
Definition at line 210 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 210 of file G4EmCorrections.hh
Referenced by InitialiseForNewRun(), and IonHighOrderCorrections().
const G4ElementVector* G4EmCorrections::theElementVector private
Definition at line 217 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 217 of file G4EmCorrections.hh
Referenced by G4EmCorrections(), and SetupKinematics().
G4LPhysicsFreeVector * G4EmCorrections::ThetaK = nullptr static private
Definition at line 204 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 204 of file G4EmCorrections.hh
Referenced by Initialise(), KShellCorrection(), ShellCorrection(), and ~G4EmCorrections().
G4LPhysicsFreeVector * G4EmCorrections::ThetaL = nullptr static private
Definition at line 205 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 205 of file G4EmCorrections.hh
Referenced by Initialise(), LShellCorrection(), ShellCorrection(), and ~G4EmCorrections().
G4double G4EmCorrections::tmax private
Definition at line 236 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 236 of file G4EmCorrections.hh
Referenced by Bethe(), G4EmCorrections(), SetupKinematics(), and SpinCorrection().
const G4double G4EmCorrections::UK static private
Initial value:
= {1.9999, 2.0134, 2.0258, 2.0478, 2.0662,
                           2.0817, 2.0945, 2.0999, 2.1049, 2.1132,
                           2.1197, 2.1246, 2.1280, 2.1292, 2.1301,
                           2.1310, 2.1310, 2.1300, 2.1283, 2.1271}
Definition at line 194 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 194 of file G4EmCorrections.hh
Referenced by Initialise(), and KShell().
const G4double G4EmCorrections::UL static private
Initial value:
= {0.1215, 0.5265, 0.8411, 1.0878, 1.2828,
                           1.4379, 1.5032, 1.5617, 1.6608, 1.7401,
                           1.8036, 1.8543, 1.8756, 1.8945, 1.9262,
                           1.9508, 1.9696, 1.9836, 1.9890, 1.9935,
                           2.0001, 2.0039, 2.0053, 2.0049, 2.0040, 2.0028}
Definition at line 200 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 200 of file G4EmCorrections.hh
Referenced by Initialise(), and LShell().
G4int G4EmCorrections::verbose private
Definition at line 242 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 242 of file G4EmCorrections.hh
Referenced by AddStoppingData(), BuildCorrectionVector(), ComputeIonCorrections(), EffectiveChargeCorrection(), G4EmCorrections(), HighOrderCorrections(), IonHighOrderCorrections(), and SetVerbose().
const G4double G4EmCorrections::VK static private
Initial value:
= {8.3410, 8.3373, 8.3340, 8.3287, 8.3247,
                           8.3219, 8.3201, 8.3194, 8.3191, 8.3188,
                           8.3191, 8.3199, 8.3211, 8.3218, 8.3226,
                           8.3244, 8.3264, 8.3285, 8.3308, 8.3320}
Definition at line 195 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 195 of file G4EmCorrections.hh
Referenced by Initialise(), and KShell().
G4double G4EmCorrections::VL = {0.0} static private
Definition at line 201 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 201 of file G4EmCorrections.hh
Referenced by Initialise(), and LShell().
const G4double G4EmCorrections::ZD static private
Initial value:
=
    {0., 0., 0., 1.72, 2.09, 2.48, 2.82, 3.16, 3.53, 3.84, 4.15}
Definition at line 193 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 193 of file G4EmCorrections.hh
Referenced by LShellCorrection(), and ShellCorrection().
std::vector<G4int> G4EmCorrections::Zion private
Definition at line 256 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 256 of file G4EmCorrections.hh
Referenced by AddStoppingData(), BuildCorrectionVector(), and EffectiveChargeCorrection().
G4double G4EmCorrections::ZK = {0.0} static private
Definition at line 196 of file G4EmCorrections.hh.
View newest version in sPHENIX GitHub at line 196 of file G4EmCorrections.hh
Referenced by Initialise(), and KShell().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmCorrections.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmCorrections.cc