ECCE @ EIC Software: G4DataVector Class Reference
G4DataVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4DataVector.hh>
Public Types
enum { T_G4DataVector = 100 }
Public Member Functions
G4DataVector ()
G4DataVector (const G4DataVector &)=default
G4DataVector (G4DataVector &&)=default
G4DataVector (size_t cap)
G4DataVector (size_t cap, G4double value)
virtual ~G4DataVector ()
G4DataVector & operator= (const G4DataVector &)=default
G4DataVector & operator= (G4DataVector &&)=default
void insertAt (size_t, const G4double &)
size_t index (const G4double &)
G4bool contains (const G4double &) const
G4bool remove (const G4double &)
size_t removeAll (const G4double &)
G4bool Store (std::ofstream &fOut, G4bool ascii=false)
G4bool Retrieve (std::ifstream &fIn, G4bool ascii=false)
Friends
std::ostream & operator<< (std::ostream &, const G4DataVector &)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 49 of file G4DataVector.hh.
View newest version in sPHENIX GitHub at line 49 of file G4DataVector.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
T_G4DataVector
Definition at line 90 of file G4DataVector.hh.
View newest version in sPHENIX GitHub at line 90 of file G4DataVector.hh
Constructor & Destructor Documentation
G4DataVector::G4DataVector ()
Definition at line 41 of file G4DataVector.cc.
View newest version in sPHENIX GitHub at line 41 of file G4DataVector.cc
G4DataVector::G4DataVector (const G4DataVector &) default
G4DataVector::G4DataVector (G4DataVector &&) default
G4DataVector::G4DataVector (size_t cap) explicit
Definition at line 46 of file G4DataVector.cc.
View newest version in sPHENIX GitHub at line 46 of file G4DataVector.cc
G4DataVector::G4DataVector (size_t cap, G4double value)
Definition at line 51 of file G4DataVector.cc.
View newest version in sPHENIX GitHub at line 51 of file G4DataVector.cc
G4DataVector::~G4DataVector () virtual
Definition at line 56 of file G4DataVector.cc.
View newest version in sPHENIX GitHub at line 56 of file G4DataVector.cc
Member Function Documentation
G4bool G4DataVector::contains (const G4double &) const inline
Referenced by G4RDVCrossSectionHandler::ActiveElements(), G4VCrossSectionHandler::ActiveElements(), G4PixeCrossSectionHandler::ActiveElements(), G4RDAugerData::BuildAugerTransitionTable(), G4AugerData::BuildAugerTransitionTable(), G4eIonisationParameters::LoadData(), G4RDBremsstrahlungParameters::LoadData(), G4RDeIonisationParameters::LoadData(), and G4BremsstrahlungParameters::LoadData().
size_t G4DataVector::index (const G4double &) inline
void G4DataVector::insertAt (size_t , const G4double &) inline
G4DataVector& G4DataVector::operator= (const G4DataVector &) default
G4DataVector& G4DataVector::operator= (G4DataVector &&) default
G4bool G4DataVector::remove (const G4double &) inline
size_t G4DataVector::removeAll (const G4double &) inline
G4bool G4DataVector::Retrieve (std::ifstream & fIn, G4bool ascii = false)
Definition at line 85 of file G4DataVector.cc.
View newest version in sPHENIX GitHub at line 85 of file G4DataVector.cc
References clear(), G4cerr, G4endl, and true.
Referenced by G4OrderedTable::Retrieve().
G4bool G4DataVector::Store (std::ofstream & fOut, G4bool ascii = false)
Definition at line 60 of file G4DataVector.cc.
View newest version in sPHENIX GitHub at line 60 of file G4DataVector.cc
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4DataVector & pv) friend
Definition at line 136 of file G4DataVector.cc.
View newest version in sPHENIX GitHub at line 136 of file G4DataVector.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4DataVector.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4DataVector.cc