ECCE @ EIC Software: G4INCL::StrangeAbsorbtionChannel Class Reference
G4INCL::StrangeAbsorbtionChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLStrangeAbsorbtionChannel.hh>
Public Member Functions
StrangeAbsorbtionChannel (Particle *, Particle *)
virtual ~StrangeAbsorbtionChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
void sampleAngles (G4double *, G4double *, G4double *)
INCL_DECLARE_ALLOCATION_POOL (StrangeAbsorbtionChannel)
Private Attributes
Particle * particle1
Particle * particle2
Detailed Description
Definition at line 48 of file G4INCLStrangeAbsorbtionChannel.hh.
View newest version in sPHENIX GitHub at line 48 of file G4INCLStrangeAbsorbtionChannel.hh
Constructor & Destructor Documentation
G4INCL::StrangeAbsorbtionChannel::StrangeAbsorbtionChannel (Particle * p1, Particle * p2)
Definition at line 47 of file G4INCLStrangeAbsorbtionChannel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4INCLStrangeAbsorbtionChannel.cc
G4INCL::StrangeAbsorbtionChannel::~StrangeAbsorbtionChannel () virtual
Definition at line 53 of file G4INCLStrangeAbsorbtionChannel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4INCLStrangeAbsorbtionChannel.cc
Member Function Documentation
void G4INCL::StrangeAbsorbtionChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 62 of file G4INCLStrangeAbsorbtionChannel.cc.
View newest version in sPHENIX GitHub at line 62 of file G4INCLStrangeAbsorbtionChannel.cc
References G4INCL::FinalState::addModifiedParticle(), G4INCL::Particle::adjustEnergyFromMomentum(), e, G4INCL::ParticleTable::getINCLMass(), G4INCL::Particle::getMass(), G4INCL::Particle::getMomentum(), G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), INCL_ERROR, G4INCL::Particle::isNucleon(), G4INCL::ParticleConfig::isPair(), G4INCL::KMinus, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::ThreeVector::mag(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::Neutron, G4InuclParticleNames::nucleon(), particle1, particle2, G4INCL::ThreeVector::perp(), G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, sampleAngles(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setType(), G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, t1, t2, and G4INCL::KinematicsUtils::totalEnergyInCM().
G4INCL::StrangeAbsorbtionChannel::INCL_DECLARE_ALLOCATION_POOL (StrangeAbsorbtionChannel) private
void G4INCL::StrangeAbsorbtionChannel::sampleAngles (G4double * ctet_par, G4double * stet_par, G4double * phi_par) private
Definition at line 55 of file G4INCLStrangeAbsorbtionChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLStrangeAbsorbtionChannel.cc
References kdfinder::abs(), G4INCL::Random::shoot(), G4INCL::Math::sign(), and G4INCL::Math::twoPi.
Referenced by fillFinalState().
Member Data Documentation
Particle* G4INCL::StrangeAbsorbtionChannel::particle1 private
Definition at line 57 of file G4INCLStrangeAbsorbtionChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLStrangeAbsorbtionChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::StrangeAbsorbtionChannel::particle2 private
Definition at line 57 of file G4INCLStrangeAbsorbtionChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLStrangeAbsorbtionChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLStrangeAbsorbtionChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLStrangeAbsorbtionChannel.cc