ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/plot/plotG.cc File Reference
plotG.cc File Reference
#include "CanvasInTab.hh"
#include <fstream>
#include <string>
#include <sstream>
#include <vector>
#include <set>
#include <map>
#include <iostream>
#include <iomanip>
#include <locale>
#include <cstring>
#include <TApplication.h>
#include <TGApplication.h>
#include <TTree.h>
#include <TNtuple.h>
#include <TBranch.h>
#include <TProfile.h>
#include <TGraph.h>
#include <TAxis.h>
#include <TGraphErrors.h>
#include <TROOT.h>
#include <TCanvas.h>
#include <TFile.h>
#include <TGFileBrowser.h>
#include <TGFileDialog.h>
#include <TChain.h>
#include <TColor.h>
Classes
struct SpeciesInfoAOS
struct SpeciesInfoSOA
Macros
#define USE_CANVASINTAB
#define _PROCESS_ONE_FILE_ ProcessSingleFile
Functions
const TGFileInfo * OpenRootFile ()
void ProcessSingleFile (TFile *file)
int ProcessSingleFile (const char *filePath)
int main (int argc, char **argv)
Macro Definition Documentation
#define _PROCESS_ONE_FILE_ ProcessSingleFile
Definition at line 338 of file plotG.cc.
View newest version in sPHENIX GitHub at line 338 of file plotG.cc
Referenced by main().
#define USE_CANVASINTAB
Definition at line 26 of file plotG.cc.
View newest version in sPHENIX GitHub at line 26 of file plotG.cc
Function Documentation
int main (int argc, char ** argv)
Definition at line 341 of file plotG.cc.
View newest version in sPHENIX GitHub at line 341 of file plotG.cc
References _PROCESS_ONE_FILE_, and OpenRootFile().
const TGFileInfo* OpenRootFile ()
Definition at line 64 of file plotG.cc.
View newest version in sPHENIX GitHub at line 64 of file plotG.cc
Referenced by main().
void ProcessSingleFile (TFile * file)
Definition at line 158 of file plotG.cc.
View newest version in sPHENIX GitHub at line 158 of file plotG.cc
References CanvasInTab::AddCanvas(), color(), e, g4zmq::exit(), SpeciesInfoAOS::fG, SpeciesInfoSOA::fG, SpeciesInfoAOS::fG2, SpeciesInfoSOA::fGerr, SpeciesInfoAOS::fName, SpeciesInfoSOA::fName, SpeciesInfoAOS::fNEvent, SpeciesInfoAOS::fNumber, SpeciesInfoSOA::fRelatErr, SpeciesInfoSOA::fTime, CanvasInTab::GetCanvas(), CanvasInTab::GetNCanvas(), it, nentries, Acts::VectorHelpers::time(), nlohmann::to_string(), and gammaraytel::tree.
Referenced by ProcessSingleFile().
int ProcessSingleFile (const char * filePath)
Definition at line 307 of file plotG.cc.
View newest version in sPHENIX GitHub at line 307 of file plotG.cc
References g4zmq::exit(), file, and ProcessSingleFile().