ECCE @ EIC Software: G4VCSGface Class Reference
G4VCSGface Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VCSGface.hh>
Public Member Functions
G4VCSGface ()
virtual ~G4VCSGface ()
virtual G4bool Intersect (const G4ThreeVector &p, const G4ThreeVector &v, G4bool outgoing, G4double surfTolerance, G4double &distance, G4double &distFromSurface, G4ThreeVector &normal, G4bool &allBehind)=0
virtual G4double Distance (const G4ThreeVector &p, G4bool outgoing)=0
virtual EInside Inside (const G4ThreeVector &p, G4double tolerance, G4double *bestDistance)=0
virtual G4ThreeVector Normal (const G4ThreeVector &p, G4double *bestDistance)=0
virtual G4double Extent (const G4ThreeVector axis)=0
virtual void CalculateExtent (const EAxis axis, const G4VoxelLimits &voxelLimit, const G4AffineTransform &tranform, G4SolidExtentList &extentList)=0
virtual G4VCSGface * Clone ()=0
virtual G4double SurfaceArea ()=0
virtual G4ThreeVector GetPointOnFace ()=0
Detailed Description
Definition at line 264 of file G4VCSGface.hh.
View newest version in sPHENIX GitHub at line 264 of file G4VCSGface.hh
Constructor & Destructor Documentation
G4VCSGface::G4VCSGface () inline
Definition at line 268 of file G4VCSGface.hh.
View newest version in sPHENIX GitHub at line 268 of file G4VCSGface.hh
virtual G4VCSGface::~G4VCSGface () inline virtual
Definition at line 269 of file G4VCSGface.hh.
View newest version in sPHENIX GitHub at line 269 of file G4VCSGface.hh
Member Function Documentation
virtual void G4VCSGface::CalculateExtent (const EAxis axis, const G4VoxelLimits & voxelLimit, const G4AffineTransform & tranform, G4SolidExtentList & extentList) pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
Referenced by G4VCSGfaceted::CalculateExtent().
virtual G4VCSGface* G4VCSGface::Clone () pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
Referenced by G4VCSGfaceted::CopyStuff().
virtual G4double G4VCSGface::Distance (const G4ThreeVector & p, G4bool outgoing) pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
Referenced by G4VCSGfaceted::DistanceToIn(), and G4VCSGfaceted::DistanceToOut().
virtual G4double G4VCSGface::Extent (const G4ThreeVector axis) pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
virtual G4ThreeVector G4VCSGface::GetPointOnFace () pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
virtual EInside G4VCSGface::Inside (const G4ThreeVector & p, G4double tolerance, G4double * bestDistance) pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
virtual G4bool G4VCSGface::Intersect (const G4ThreeVector & p, const G4ThreeVector & v, G4bool outgoing, G4double surfTolerance, G4double & distance, G4double & distFromSurface, G4ThreeVector & normal, G4bool & allBehind) pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
virtual G4ThreeVector G4VCSGface::Normal (const G4ThreeVector & p, G4double * bestDistance) pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
virtual G4double G4VCSGface::SurfaceArea () pure virtual
Implemented in G4PolyhedraSide, G4PolyconeSide, and G4PolyPhiFace.
Referenced by G4VCSGfaceted::GetPointOnSurfaceGeneric().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VCSGface.hh