ECCE @ EIC Software: CLHEP::DualRand::IntegerCong Class Reference
CLHEP::DualRand::IntegerCong Class Reference
Public Member Functions
IntegerCong ()
IntegerCong (unsigned int seed, int streamNumber)
operator unsigned int ()
void put (std::ostream &os) const
void put (std::vector< unsigned long > &v) const
void get (std::istream &is)
bool get (std::vector< unsigned long >::const_iterator &iv)
Private Attributes
unsigned int state
unsigned int multiplier
unsigned int addend
Detailed Description
Definition at line 122 of file DualRand.h.
View newest version in sPHENIX GitHub at line 122 of file DualRand.h
Constructor & Destructor Documentation
CLHEP::DualRand::IntegerCong::IntegerCong ()
Definition at line 442 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 442 of file DualRand.cc
CLHEP::DualRand::IntegerCong::IntegerCong (unsigned int seed, int streamNumber)
Definition at line 449 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 449 of file DualRand.cc
Member Function Documentation
void CLHEP::DualRand::IntegerCong::get (std::istream & is)
Definition at line 491 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 491 of file DualRand.cc
References CLHEP::MarkerLen.
Referenced by CLHEP::DualRand::getState(), and CLHEP::DualRand::restoreStatus().
bool CLHEP::DualRand::IntegerCong::get (std::vector< unsigned long >::const_iterator & iv)
Definition at line 518 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 518 of file DualRand.cc
CLHEP::DualRand::IntegerCong::operator unsigned int ()
Definition at line 469 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 469 of file DualRand.cc
void CLHEP::DualRand::IntegerCong::put (std::ostream & os) const
Definition at line 473 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 473 of file DualRand.cc
References gammaraytel::pr.
Referenced by CLHEP::DualRand::put(), and CLHEP::DualRand::showStatus().
void CLHEP::DualRand::IntegerCong::put (std::vector< unsigned long > & v) const
Definition at line 485 of file DualRand.cc.
View newest version in sPHENIX GitHub at line 485 of file DualRand.cc
Member Data Documentation
unsigned int CLHEP::DualRand::IntegerCong::addend private
Definition at line 132 of file DualRand.h.
View newest version in sPHENIX GitHub at line 132 of file DualRand.h
unsigned int CLHEP::DualRand::IntegerCong::multiplier private
Definition at line 132 of file DualRand.h.
View newest version in sPHENIX GitHub at line 132 of file DualRand.h
unsigned int CLHEP::DualRand::IntegerCong::state private
Definition at line 132 of file DualRand.h.
View newest version in sPHENIX GitHub at line 132 of file DualRand.h
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/DualRand.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/DualRand.cc