ECCE @ EIC Software: G4InuclCollider Class Reference
G4InuclCollider Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclCollider.hh>
Public Member Functions
G4InuclCollider ()
virtual ~G4InuclCollider ()
void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
void rescatter (G4InuclParticle *bullet, G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus, G4CollisionOutput &globalOutput)
void setVerboseLevel (G4int verbose=0)
void useCascadeDeexcitation ()
void usePreCompoundDeexcitation ()
Public Member Functions inherited from G4CascadeColliderBase
G4CascadeColliderBase (const G4String &name, G4int verbose=0)
virtual ~G4CascadeColliderBase ()
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Protected Member Functions
void deexcite (const G4Fragment &fragment, G4CollisionOutput &globalOutput)
G4bool photonuclearOkay (G4CollisionOutput &checkOutput) const
Protected Member Functions inherited from G4CascadeColliderBase
virtual G4bool useEPCollider (G4InuclParticle *bullet, G4InuclParticle *target) const
virtual G4bool inelasticInteractionPossible (G4InuclParticle *bullet, G4InuclParticle *target, G4double ekin) const
virtual G4bool validateOutput (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &fragment, G4CollisionOutput &output)
virtual G4bool validateOutput (G4InuclParticle *bullet, G4InuclParticle *target, const std::vector< G4InuclElementaryParticle > &particles)
Protected Member Functions inherited from G4VCascadeCollider
virtual void setName (const G4String &name)
Private Member Functions
G4InuclCollider (const G4InuclCollider &)
G4InuclCollider & operator= (const G4InuclCollider &)
Private Attributes
G4ElementaryParticleCollider * theElementaryParticleCollider
G4IntraNucleiCascader * theIntraNucleiCascader
G4VCascadeDeexcitation * theDeexcitation
G4CollisionOutput output
G4CollisionOutput DEXoutput
Additional Inherited Members
Protected Attributes inherited from G4CascadeColliderBase
G4InteractionCase interCase
G4CascadeCheckBalance * balance
Detailed Description
Definition at line 60 of file G4InuclCollider.hh.
View newest version in sPHENIX GitHub at line 60 of file G4InuclCollider.hh
Constructor & Destructor Documentation
G4InuclCollider::G4InuclCollider ()
Definition at line 87 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 87 of file G4InuclCollider.cc
G4InuclCollider::~G4InuclCollider () virtual
Definition at line 93 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 93 of file G4InuclCollider.cc
References theDeexcitation, theElementaryParticleCollider, and theIntraNucleiCascader.
G4InuclCollider::G4InuclCollider (const G4InuclCollider &) private
Member Function Documentation
void G4InuclCollider::collide (G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & globalOutput) virtual
Implements G4VCascadeCollider.
Definition at line 130 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 130 of file G4InuclCollider.cc
References ab, G4CollisionOutput::acceptable(), G4CollisionOutput::add(), G4CollisionOutput::boostToLabFrame(), G4InteractionCase::code(), G4ElementaryParticleCollider::collide(), G4IntraNucleiCascader::collide(), deexcite(), G4cerr, G4cout, G4endl, G4InuclNuclei::getA(), G4InteractionCase::getBullet(), G4InuclParticle::getDefinition(), G4LorentzConvertor::getKinEnergyInTheTRS(), G4ParticleDefinition::GetParticleName(), G4CollisionOutput::getRecoilFragment(), G4CascadeChannelTables::GetTable(), G4InteractionCase::getTarget(), G4LorentzConvertor::getTRSMomentum(), G4InuclNuclei::getZ(), G4InteractionCase::hadNucleus(), G4CascadeColliderBase::inelasticInteractionPossible(), G4CascadeColliderBase::interCase, output, photonuclearOkay(), G4CollisionOutput::removeRecoilFragment(), G4CollisionOutput::reset(), G4InteractionCase::set(), G4CollisionOutput::setOnShell(), CLHEP::HepLorentzVector::setZ(), theElementaryParticleCollider, theIntraNucleiCascader, G4LorentzConvertor::toTheTargetRestFrame(), G4LorentzConvertor::trivial(), G4CollisionOutput::trivialise(), G4InuclElementaryParticle::type(), G4CascadeColliderBase::useEPCollider(), G4InteractionCase::valid(), and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::ApplyYourself().
void G4InuclCollider::deexcite (const G4Fragment & fragment, G4CollisionOutput & globalOutput) protected
Definition at line 316 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 316 of file G4InuclCollider.cc
References G4CollisionOutput::add(), G4VCascadeDeexcitation::deExcite(), DEXoutput, G4cout, G4endl, G4Fragment::GetA_asInt(), G4CollisionOutput::reset(), theDeexcitation, G4CascadeColliderBase::validateOutput(), and G4VCascadeCollider::verboseLevel.
Referenced by collide(), and rescatter().
G4InuclCollider& G4InuclCollider::operator= (const G4InuclCollider &) private
G4bool G4InuclCollider::photonuclearOkay (G4CollisionOutput & checkOutput) const protected
Definition at line 338 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 338 of file G4InuclCollider.cc
References G4cout, G4endl, G4InteractionCase::getBullet(), G4InuclParticle::getKineticEnergy(), G4InuclParticle::getMass(), G4CollisionOutput::getOutgoingNuclei(), G4InteractionCase::getTarget(), G4CascadeColliderBase::interCase, G4InuclElementaryParticle::isElectron(), G4InuclElementaryParticle::isPhoton(), G4CollisionOutput::numberOfOutgoingNuclei(), G4InteractionCase::twoNuclei(), and G4VCascadeCollider::verboseLevel.
Referenced by collide().
void G4InuclCollider::rescatter (G4InuclParticle * bullet, G4KineticTrackVector * theSecondaries, G4V3DNucleus * theNucleus, G4CollisionOutput & globalOutput) virtual
Reimplemented from G4CascadeColliderBase.
Definition at line 288 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 288 of file G4InuclCollider.cc
References G4CollisionOutput::add(), deexcite(), G4cout, G4endl, G4CollisionOutput::getRecoilFragment(), output, G4CollisionOutput::removeRecoilFragment(), G4IntraNucleiCascader::rescatter(), G4CollisionOutput::reset(), theIntraNucleiCascader, and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::Propagate().
void G4InuclCollider::setVerboseLevel (G4int verbose = 0) virtual
Reimplemented from G4CascadeColliderBase.
Definition at line 101 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 101 of file G4InuclCollider.cc
References DEXoutput, output, G4VCascadeCollider::setVerboseLevel(), G4CollisionOutput::setVerboseLevel(), G4CascadeColliderBase::setVerboseLevel(), G4IntraNucleiCascader::setVerboseLevel(), theDeexcitation, theElementaryParticleCollider, theIntraNucleiCascader, and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::SetVerboseLevel().
void G4InuclCollider::useCascadeDeexcitation ()
Definition at line 115 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 115 of file G4InuclCollider.cc
References G4VCascadeCollider::setVerboseLevel(), theDeexcitation, and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::useCascadeDeexcitation().
void G4InuclCollider::usePreCompoundDeexcitation ()
Definition at line 121 of file G4InuclCollider.cc.
View newest version in sPHENIX GitHub at line 121 of file G4InuclCollider.cc
References G4VCascadeCollider::setVerboseLevel(), theDeexcitation, and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::usePreCompoundDeexcitation().
Member Data Documentation
G4CollisionOutput G4InuclCollider::DEXoutput private
Definition at line 91 of file G4InuclCollider.hh.
View newest version in sPHENIX GitHub at line 91 of file G4InuclCollider.hh
Referenced by deexcite(), and setVerboseLevel().
G4CollisionOutput G4InuclCollider::output private
Definition at line 90 of file G4InuclCollider.hh.
View newest version in sPHENIX GitHub at line 90 of file G4InuclCollider.hh
Referenced by collide(), rescatter(), and setVerboseLevel().
G4VCascadeDeexcitation* G4InuclCollider::theDeexcitation private
Definition at line 88 of file G4InuclCollider.hh.
View newest version in sPHENIX GitHub at line 88 of file G4InuclCollider.hh
Referenced by deexcite(), setVerboseLevel(), useCascadeDeexcitation(), usePreCompoundDeexcitation(), and ~G4InuclCollider().
G4ElementaryParticleCollider* G4InuclCollider::theElementaryParticleCollider private
Definition at line 85 of file G4InuclCollider.hh.
View newest version in sPHENIX GitHub at line 85 of file G4InuclCollider.hh
Referenced by collide(), setVerboseLevel(), and ~G4InuclCollider().
G4IntraNucleiCascader* G4InuclCollider::theIntraNucleiCascader private
Definition at line 86 of file G4InuclCollider.hh.
View newest version in sPHENIX GitHub at line 86 of file G4InuclCollider.hh
Referenced by collide(), rescatter(), setVerboseLevel(), and ~G4InuclCollider().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclCollider.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4InuclCollider.cc