ECCE @ EIC Software: G4DecayProducts Class Reference
G4DecayProducts Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4DecayProducts.hh>
Public Types
typedef std::vector
< G4DynamicParticle * > G4DecayProductVector
Public Member Functions
G4DecayProducts ()
G4DecayProducts (const G4DynamicParticle &aParticle)
G4DecayProducts (const G4DecayProducts &right)
G4DecayProducts & operator= (const G4DecayProducts &right)
~G4DecayProducts ()
G4bool operator== (const G4DecayProducts &right) const
G4bool operator!= (const G4DecayProducts &right) const
const G4DynamicParticle * GetParentParticle () const
void SetParentParticle (const G4DynamicParticle &aParticle)
void Boost (G4double totalEnergy, const G4ThreeVector &momentumDirection)
void Boost (G4double betax, G4double betay, G4double betaz)
G4DynamicParticle * PopProducts ()
G4int PushProducts (G4DynamicParticle *aParticle)
G4DynamicParticle * operator[] (G4int anIndex) const
G4int entries () const
G4bool IsChecked () const
void DumpInfo () const
Private Attributes
G4int numberOfProducts
G4DynamicParticle * theParentParticle
G4DecayProductVector * theProductVector
Detailed Description
Definition at line 46 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 46 of file G4DecayProducts.hh
Member Typedef Documentation
typedef std::vector<G4DynamicParticle*> G4DecayProducts::G4DecayProductVector
Definition at line 93 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 93 of file G4DecayProducts.hh
Constructor & Destructor Documentation
G4DecayProducts::G4DecayProducts ()
Definition at line 49 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 49 of file G4DecayProducts.cc
References theProductVector.
Referenced by G4DecayProducts(), and operator=().
G4DecayProducts::G4DecayProducts (const G4DynamicParticle & aParticle)
Definition at line 55 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 55 of file G4DecayProducts.cc
References theParentParticle, and theProductVector.
G4DecayProducts::G4DecayProducts (const G4DecayProducts & right)
Definition at line 62 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 62 of file G4DecayProducts.cc
References G4DecayProducts(), G4DynamicParticle::GetPreAssignedDecayProducts(), G4DynamicParticle::GetPreAssignedDecayProperTime(), numberOfProducts, G4DynamicParticle::SetPreAssignedDecayProducts(), G4DynamicParticle::SetPreAssignedDecayProperTime(), theParentParticle, and theProductVector.
G4DecayProducts::~G4DecayProducts ()
Definition at line 125 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 125 of file G4DecayProducts.cc
References numberOfProducts, theParentParticle, and theProductVector.
Member Function Documentation
void G4DecayProducts::Boost (G4double totalEnergy, const G4ThreeVector & momentumDirection)
Definition at line 176 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 176 of file G4DecayProducts.cc
References G4DynamicParticle::GetMass(), mass, theParentParticle, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4RadioactiveDecay::DecayIt(), and G4IntraNucleiCascader::decayTrappedParticle().
void G4DecayProducts::Boost (G4double betax, G4double betay, G4double betaz)
Definition at line 188 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 188 of file G4DecayProducts.cc
References CLHEP::HepLorentzVector::boost(), DBL_MIN, energy, G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetTotalEnergy(), G4DynamicParticle::GetTotalMomentum(), mass, momentum, numberOfProducts, G4DynamicParticle::Set4Momentum(), theParentParticle, theProductVector, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4DecayProducts::DumpInfo () const
Definition at line 311 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 311 of file G4DecayProducts.cc
References G4DynamicParticle::DumpInfo(), G4cout, G4endl, numberOfProducts, theParentParticle, and theProductVector.
Referenced by G4RadioactiveDecayBase::DecayAnalog(), G4KL3DecayChannel::DecayIt(), G4NeutronBetaDecayChannel::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4MuonDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4RadioactiveDecay::DecayIt(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4PhaseSpaceDecayChannel::OneBodyDecayIt(), G4GeneralPhaseSpaceDecay::OneBodyDecayIt(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), and G4GeneralPhaseSpaceDecay::TwoBodyDecayIt().
G4int G4DecayProducts::entries () const inline
Definition at line 85 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 85 of file G4DecayProducts.hh
References numberOfProducts.
Referenced by G4Radioactivation::AddDeexcitationSpectrumForBiasMode(), G4RadioactiveDecay::AddDeexcitationSpectrumForBiasMode(), G4PrimaryTransformer::CheckDynamicParticle(), G4RadioactiveDecayBase::CollimateDecay(), G4RadioactiveDecay::CollimateDecay(), G4PionDecayMakeSpin::DaughterPolarization(), G4KineticTrack::Decay(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), and G4IntraNucleiCascader::decayTrappedParticle().
const G4DynamicParticle* G4DecayProducts::GetParentParticle () const inline
Definition at line 72 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 72 of file G4DecayProducts.hh
References theParentParticle.
Referenced by G4PionDecayMakeSpin::DaughterPolarization().
G4bool G4DecayProducts::IsChecked () const
Definition at line 241 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 241 of file G4DecayProducts.cc
References DBL_MIN, e, energy, G4cout, G4endl, G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetTotalEnergy(), G4DynamicParticle::GetTotalMomentum(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), CLHEP::Hep3Vector::mag(), mass, MeV, momentum, numberOfProducts, part, theParentParticle, and theProductVector.
Referenced by G4RadioactiveDecayBase::DecayAnalog(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), and G4RadioactiveDecay::DecayIt().
G4bool G4DecayProducts::operator!= (const G4DecayProducts & right) const inline
Definition at line 113 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 113 of file G4DecayProducts.hh
G4DecayProducts & G4DecayProducts::operator= (const G4DecayProducts & right)
Definition at line 89 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 89 of file G4DecayProducts.cc
References G4DecayProducts(), G4DynamicParticle::GetPreAssignedDecayProducts(), G4DynamicParticle::GetPreAssignedDecayProperTime(), numberOfProducts, G4DynamicParticle::SetPreAssignedDecayProducts(), G4DynamicParticle::SetPreAssignedDecayProperTime(), theParentParticle, and theProductVector.
G4bool G4DecayProducts::operator== (const G4DecayProducts & right) const inline
Definition at line 107 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 107 of file G4DecayProducts.hh
G4DynamicParticle * G4DecayProducts::operator[] (G4int anIndex) const
Definition at line 160 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 160 of file G4DecayProducts.cc
References numberOfProducts, and theProductVector.
G4DynamicParticle * G4DecayProducts::PopProducts ()
Definition at line 141 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 141 of file G4DecayProducts.cc
References numberOfProducts, part, and theProductVector.
Referenced by G4Radioactivation::AddDeexcitationSpectrumForBiasMode(), G4RadioactiveDecay::AddDeexcitationSpectrumForBiasMode(), G4KineticTrack::Decay(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), and G4RadioactiveDecay::DecayIt().
G4int G4DecayProducts::PushProducts (G4DynamicParticle * aParticle)
Definition at line 153 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 153 of file G4DecayProducts.cc
References numberOfProducts, and theProductVector.
Referenced by G4AlphaDecay::DecayIt(), G4TritonDecay::DecayIt(), G4ECDecay::DecayIt(), G4ProtonDecay::DecayIt(), G4NeutronDecay::DecayIt(), G4SFDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4ITDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4NeutronBetaDecayChannel::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4MuonDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4Pythia6Decayer::ImportDecayProducts(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4PhaseSpaceDecayChannel::OneBodyDecayIt(), G4GeneralPhaseSpaceDecay::OneBodyDecayIt(), G4PrimaryTransformer::SetDecayProducts(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), and G4GeneralPhaseSpaceDecay::TwoBodyDecayIt().
void G4DecayProducts::SetParentParticle (const G4DynamicParticle & aParticle)
Definition at line 169 of file G4DecayProducts.cc.
View newest version in sPHENIX GitHub at line 169 of file G4DecayProducts.cc
References theParentParticle.
Member Data Documentation
G4int G4DecayProducts::numberOfProducts private
Definition at line 96 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 96 of file G4DecayProducts.hh
Referenced by Boost(), DumpInfo(), entries(), G4DecayProducts(), IsChecked(), operator=(), operator[](), PopProducts(), PushProducts(), and ~G4DecayProducts().
G4DynamicParticle* G4DecayProducts::theParentParticle private
Definition at line 97 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 97 of file G4DecayProducts.hh
Referenced by Boost(), DumpInfo(), G4DecayProducts(), GetParentParticle(), IsChecked(), operator=(), SetParentParticle(), and ~G4DecayProducts().
G4DecayProductVector* G4DecayProducts::theProductVector private
Definition at line 98 of file G4DecayProducts.hh.
View newest version in sPHENIX GitHub at line 98 of file G4DecayProducts.hh
Referenced by Boost(), DumpInfo(), G4DecayProducts(), IsChecked(), operator=(), operator[](), PopProducts(), PushProducts(), and ~G4DecayProducts().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4DecayProducts.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4DecayProducts.cc