ECCE @ EIC Software: G4VPhononProcess Class Reference
G4VPhononProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4VPhononProcess.hh>
Public Member Functions
G4VPhononProcess (const G4String &processName)
virtual ~G4VPhononProcess ()
virtual G4bool IsApplicable (const G4ParticleDefinition &aPD)
virtual void StartTracking (G4Track *track)
virtual void EndTracking ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4int GetPolarization (const G4Track &track) const
virtual G4int GetPolarization (const G4Track *track) const
virtual G4int ChoosePolarization (G4double Ldos, G4double STdos, G4double FTdos) const
virtual G4Track * CreateSecondary (G4int polarization, const G4ThreeVector &K, G4double energy) const
Protected Member Functions inherited from G4VDiscreteProcess
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)=0
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4PhononTrackMap * trackKmap
const G4LatticePhysical * theLattice
Private Member Functions
G4VPhononProcess (G4VPhononProcess &)
G4VPhononProcess & operator= (const G4VPhononProcess &right)
Private Attributes
const G4Track * currentTrack
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 41 of file G4VPhononProcess.hh.
View newest version in sPHENIX GitHub at line 41 of file G4VPhononProcess.hh
Constructor & Destructor Documentation
G4VPhononProcess::G4VPhononProcess (const G4String & processName)
Definition at line 53 of file G4VPhononProcess.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VPhononProcess.cc
G4VPhononProcess::~G4VPhononProcess () virtual
Definition at line 58 of file G4VPhononProcess.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VPhononProcess.cc
G4VPhononProcess::G4VPhononProcess (G4VPhononProcess &) private
Member Function Documentation
G4int G4VPhononProcess::ChoosePolarization (G4double Ldos, G4double STdos, G4double FTdos) const protected virtual
Definition at line 103 of file G4VPhononProcess.cc.
View newest version in sPHENIX GitHub at line 103 of file G4VPhononProcess.cc
References G4UniformRand, G4PhononPolarization::Long, norm, G4PhononPolarization::TransFast, and G4PhononPolarization::TransSlow.
Referenced by G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), and G4PhononScattering::PostStepDoIt().
G4Track * G4VPhononProcess::CreateSecondary (G4int polarization, const G4ThreeVector & K, G4double energy) const protected virtual
Definition at line 119 of file G4VPhononProcess.cc.
View newest version in sPHENIX GitHub at line 119 of file G4VPhononProcess.cc
References currentTrack, G4cout, G4endl, G4PhononPolarization::Get(), G4Track::GetGlobalTime(), G4PhononTrackMap::GetK(), G4Track::GetPosition(), G4VProcess::GetProcessName(), CLHEP::Hep3Vector::mag(), G4LatticePhysical::MapKtoV(), G4LatticePhysical::MapKtoVDir(), G4LatticePhysical::RotateToGlobal(), G4PhononTrackMap::SetK(), G4Track::SetVelocity(), theLattice, trackKmap, G4Track::UseGivenVelocity(), and G4VProcess::verboseLevel.
Referenced by G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), and G4PhononScattering::PostStepDoIt().
void G4VPhononProcess::EndTracking () virtual
Reimplemented from G4VProcess.
Definition at line 86 of file G4VPhononProcess.cc.
View newest version in sPHENIX GitHub at line 86 of file G4VPhononProcess.cc
References currentTrack, G4VProcess::EndTracking(), G4PhononTrackMap::RemoveTrack(), theLattice, and trackKmap.
G4int G4VPhononProcess::GetPolarization (const G4Track & track) const protected virtual
Definition at line 96 of file G4VPhononProcess.cc.
View newest version in sPHENIX GitHub at line 96 of file G4VPhononProcess.cc
References G4PhononPolarization::Get(), and G4Track::GetParticleDefinition().
Referenced by GetPolarization(), and G4PhononReflection::PostStepDoIt().
virtual G4int G4VPhononProcess::GetPolarization (const G4Track * track) const inline protected virtual
Definition at line 56 of file G4VPhononProcess.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VPhononProcess.hh
References GetPolarization().
G4bool G4VPhononProcess::IsApplicable (const G4ParticleDefinition & aPD) virtual
Reimplemented from G4VProcess.
Reimplemented in G4PhononDownconversion.
Definition at line 63 of file G4VPhononProcess.cc.
View newest version in sPHENIX GitHub at line 63 of file G4VPhononProcess.cc
References G4PhononLong::Definition(), G4PhononTransSlow::Definition(), and G4PhononTransFast::Definition().
G4VPhononProcess& G4VPhononProcess::operator= (const G4VPhononProcess & right) private
void G4VPhononProcess::StartTracking (G4Track * track) virtual
Reimplemented from G4VProcess.
Definition at line 72 of file G4VPhononProcess.cc.
View newest version in sPHENIX GitHub at line 72 of file G4VPhononProcess.cc
References currentTrack, G4PhononTrackMap::Find(), G4LatticeManager::GetLattice(), G4LatticeManager::GetLatticeManager(), G4Track::GetMomentumDirection(), G4Track::GetVolume(), G4PhononTrackMap::SetK(), G4VProcess::StartTracking(), theLattice, track, and trackKmap.
Member Data Documentation
const G4Track* G4VPhononProcess::currentTrack private
Definition at line 74 of file G4VPhononProcess.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VPhononProcess.hh
Referenced by CreateSecondary(), EndTracking(), and StartTracking().
const G4LatticePhysical* G4VPhononProcess::theLattice protected
Definition at line 71 of file G4VPhononProcess.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VPhononProcess.hh
Referenced by CreateSecondary(), EndTracking(), G4PhononScattering::GetMeanFreePath(), G4PhononDownconversion::GetMeanFreePath(), G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), G4PhononScattering::PostStepDoIt(), G4PhononDownconversion::PostStepDoIt(), G4PhononReflection::PostStepDoIt(), and StartTracking().
G4PhononTrackMap* G4VPhononProcess::trackKmap protected
Definition at line 70 of file G4VPhononProcess.hh.
View newest version in sPHENIX GitHub at line 70 of file G4VPhononProcess.hh
Referenced by CreateSecondary(), EndTracking(), G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), and StartTracking().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4VPhononProcess.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/src/G4VPhononProcess.cc