ECCE @ EIC Software: G4BFieldIntegrationDriver Class Reference
G4BFieldIntegrationDriver Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4BFieldIntegrationDriver.hh>
Public Member Functions
G4BFieldIntegrationDriver (std::unique_ptr< G4VIntegrationDriver > smallStepDriver, std::unique_ptr< G4VIntegrationDriver > largeStepDriver)
G4BFieldIntegrationDriver (const G4BFieldIntegrationDriver &)=delete
const G4BFieldIntegrationDriver & operator= (const G4BFieldIntegrationDriver &)=delete
virtual G4double AdvanceChordLimited (G4FieldTrack &track, G4double hstep, G4double eps, G4double chordDistance) override
virtual G4bool AccurateAdvance (G4FieldTrack &track, G4double hstep, G4double eps, G4double hinitial=0) override
virtual G4bool DoesReIntegrate () override
virtual void GetDerivatives (const G4FieldTrack &track, G4double dydx[]) const override
virtual void GetDerivatives (const G4FieldTrack &track, G4double dydx[], G4double field[]) const override
virtual void SetEquationOfMotion (G4EquationOfMotion *equation) override
virtual G4EquationOfMotion * GetEquationOfMotion () override
virtual const
G4MagIntegratorStepper * GetStepper () const override
virtual G4MagIntegratorStepper * GetStepper () override
virtual G4double ComputeNewStepSize (G4double errMaxNorm, G4double hstepCurrent) override
virtual void SetVerboseLevel (G4int level) override
virtual G4int GetVerboseLevel () const override
virtual void OnComputeStep () override
virtual void OnStartTracking () override
void PrintStatistics () const
Public Member Functions inherited from G4VIntegrationDriver
virtual ~G4VIntegrationDriver ()=default
virtual void RenewStepperAndAdjust (G4MagIntegratorStepper *pItsStepper)
virtual G4bool QuickAdvance (G4FieldTrack &, const G4double[], G4double, G4double &, G4double &)
Private Member Functions
G4double CurvatureRadius (const G4FieldTrack &track) const
void GetFieldValue (const G4FieldTrack &track, G4double Field[]) const
Private Attributes
std::unique_ptr
< G4VIntegrationDriver > fSmallStepDriver
std::unique_ptr
< G4VIntegrationDriver > fLargeStepDriver
G4VIntegrationDriver * fCurrDriver = nullptr
G4Mag_EqRhs * fEquation = nullptr
G4int fSmallDriverSteps = 0
G4int fLargeDriverSteps = 0
Additional Inherited Members
Static Protected Attributes inherited from G4VIntegrationDriver
static constexpr G4double max_stepping_increase = 5
static constexpr G4double max_stepping_decrease = 0.1
Detailed Description
Definition at line 42 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 42 of file G4BFieldIntegrationDriver.hh
Constructor & Destructor Documentation
G4BFieldIntegrationDriver::G4BFieldIntegrationDriver (std::unique_ptr< G4VIntegrationDriver > smallStepDriver, std::unique_ptr< G4VIntegrationDriver > largeStepDriver)
Definition at line 62 of file G4BFieldIntegrationDriver.cc.
View newest version in sPHENIX GitHub at line 62 of file G4BFieldIntegrationDriver.cc
References FatalException, fLargeStepDriver, fSmallStepDriver, and G4Exception().
G4BFieldIntegrationDriver::G4BFieldIntegrationDriver (const G4BFieldIntegrationDriver &) delete
Member Function Documentation
virtual G4bool G4BFieldIntegrationDriver::AccurateAdvance (G4FieldTrack & track, G4double hstep, G4double eps, G4double hinitial = 0) inline override virtual
Implements G4VIntegrationDriver.
Definition at line 58 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BFieldIntegrationDriver.hh
References G4VIntegrationDriver::AccurateAdvance(), and fCurrDriver.
G4double G4BFieldIntegrationDriver::AdvanceChordLimited (G4FieldTrack & track, G4double hstep, G4double eps, G4double chordDistance) override virtual
Implements G4VIntegrationDriver.
Definition at line 78 of file G4BFieldIntegrationDriver.cc.
View newest version in sPHENIX GitHub at line 78 of file G4BFieldIntegrationDriver.cc
References G4VIntegrationDriver::AdvanceChordLimited(), CurvatureRadius(), fCurrDriver, fLargeDriverSteps, fLargeStepDriver, fSmallDriverSteps, fSmallStepDriver, min, G4VIntegrationDriver::OnComputeStep(), radius, and twopi.
virtual G4double G4BFieldIntegrationDriver::ComputeNewStepSize (G4double errMaxNorm, G4double hstepCurrent) inline override virtual
Implements G4VIntegrationDriver.
Definition at line 104 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 104 of file G4BFieldIntegrationDriver.hh
References G4VIntegrationDriver::ComputeNewStepSize(), and fCurrDriver.
G4double G4BFieldIntegrationDriver::CurvatureRadius (const G4FieldTrack & track) const private
Definition at line 117 of file G4BFieldIntegrationDriver.cc.
View newest version in sPHENIX GitHub at line 117 of file G4BFieldIntegrationDriver.cc
References kdfinder::abs(), DBL_MAX, eplus, G4Mag_EqRhs::FCof(), fEquation, GetFieldValue(), G4FieldTrack::GetMomentum(), CLHEP::Hep3Vector::mag2(), and G4Field::MAX_NUMBER_OF_COMPONENTS.
Referenced by AdvanceChordLimited().
virtual G4bool G4BFieldIntegrationDriver::DoesReIntegrate () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 66 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 66 of file G4BFieldIntegrationDriver.hh
References G4VIntegrationDriver::DoesReIntegrate(), and fCurrDriver.
virtual void G4BFieldIntegrationDriver::GetDerivatives (const G4FieldTrack & track, G4double dydx[]) const inline override virtual
Implements G4VIntegrationDriver.
Definition at line 72 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 72 of file G4BFieldIntegrationDriver.hh
References fCurrDriver, and G4VIntegrationDriver::GetDerivatives().
virtual void G4BFieldIntegrationDriver::GetDerivatives (const G4FieldTrack & track, G4double dydx[], G4double field[]) const inline override virtual
Implements G4VIntegrationDriver.
Definition at line 79 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 79 of file G4BFieldIntegrationDriver.hh
References fCurrDriver, and G4VIntegrationDriver::GetDerivatives().
virtual G4EquationOfMotion* G4BFieldIntegrationDriver::GetEquationOfMotion () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 88 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 88 of file G4BFieldIntegrationDriver.hh
References fCurrDriver, and G4VIntegrationDriver::GetEquationOfMotion().
void G4BFieldIntegrationDriver::GetFieldValue (const G4FieldTrack & track, G4double Field[]) const private
Definition at line 138 of file G4BFieldIntegrationDriver.cc.
View newest version in sPHENIX GitHub at line 138 of file G4BFieldIntegrationDriver.cc
References fEquation, G4EquationOfMotion::GetFieldValue(), G4FieldTrack::GetLabTimeOfFlight(), G4FieldTrack::GetPosition(), pos(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CurvatureRadius().
virtual const G4MagIntegratorStepper* G4BFieldIntegrationDriver::GetStepper () const inline override virtual
Implements G4VIntegrationDriver.
Definition at line 94 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 94 of file G4BFieldIntegrationDriver.hh
References fCurrDriver, and G4VIntegrationDriver::GetStepper().
virtual G4MagIntegratorStepper* G4BFieldIntegrationDriver::GetStepper () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 99 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 99 of file G4BFieldIntegrationDriver.hh
References fCurrDriver, and G4VIntegrationDriver::GetStepper().
virtual G4int G4BFieldIntegrationDriver::GetVerboseLevel () const inline override virtual
Implements G4VIntegrationDriver.
Definition at line 116 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 116 of file G4BFieldIntegrationDriver.hh
References fCurrDriver, and G4VIntegrationDriver::GetVerboseLevel().
virtual void G4BFieldIntegrationDriver::OnComputeStep () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 121 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 121 of file G4BFieldIntegrationDriver.hh
References fLargeStepDriver, and fSmallStepDriver.
virtual void G4BFieldIntegrationDriver::OnStartTracking () inline override virtual
Implements G4VIntegrationDriver.
Definition at line 127 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 127 of file G4BFieldIntegrationDriver.hh
References fLargeStepDriver, and fSmallStepDriver.
const G4BFieldIntegrationDriver& G4BFieldIntegrationDriver::operator= (const G4BFieldIntegrationDriver &) delete
void G4BFieldIntegrationDriver::PrintStatistics () const
Definition at line 148 of file G4BFieldIntegrationDriver.cc.
View newest version in sPHENIX GitHub at line 148 of file G4BFieldIntegrationDriver.cc
References fLargeDriverSteps, fSmallDriverSteps, and G4cout.
void G4BFieldIntegrationDriver::SetEquationOfMotion (G4EquationOfMotion * equation) override virtual
Implements G4VIntegrationDriver.
Definition at line 109 of file G4BFieldIntegrationDriver.cc.
View newest version in sPHENIX GitHub at line 109 of file G4BFieldIntegrationDriver.cc
References fEquation, fLargeStepDriver, and fSmallStepDriver.
virtual void G4BFieldIntegrationDriver::SetVerboseLevel (G4int level) inline override virtual
Implements G4VIntegrationDriver.
Definition at line 110 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 110 of file G4BFieldIntegrationDriver.hh
References fLargeStepDriver, and fSmallStepDriver.
Member Data Documentation
G4VIntegrationDriver* G4BFieldIntegrationDriver::fCurrDriver = nullptr private
Definition at line 144 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 144 of file G4BFieldIntegrationDriver.hh
Referenced by AccurateAdvance(), AdvanceChordLimited(), ComputeNewStepSize(), DoesReIntegrate(), GetDerivatives(), GetEquationOfMotion(), GetStepper(), and GetVerboseLevel().
G4Mag_EqRhs* G4BFieldIntegrationDriver::fEquation = nullptr private
Definition at line 145 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 145 of file G4BFieldIntegrationDriver.hh
Referenced by CurvatureRadius(), GetFieldValue(), and SetEquationOfMotion().
G4int G4BFieldIntegrationDriver::fLargeDriverSteps = 0 private
Definition at line 148 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 148 of file G4BFieldIntegrationDriver.hh
Referenced by AdvanceChordLimited(), and PrintStatistics().
std::unique_ptr<G4VIntegrationDriver> G4BFieldIntegrationDriver::fLargeStepDriver private
Definition at line 143 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 143 of file G4BFieldIntegrationDriver.hh
Referenced by AdvanceChordLimited(), G4BFieldIntegrationDriver(), OnComputeStep(), OnStartTracking(), SetEquationOfMotion(), and SetVerboseLevel().
G4int G4BFieldIntegrationDriver::fSmallDriverSteps = 0 private
Definition at line 147 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 147 of file G4BFieldIntegrationDriver.hh
Referenced by AdvanceChordLimited(), and PrintStatistics().
std::unique_ptr<G4VIntegrationDriver> G4BFieldIntegrationDriver::fSmallStepDriver private
Definition at line 142 of file G4BFieldIntegrationDriver.hh.
View newest version in sPHENIX GitHub at line 142 of file G4BFieldIntegrationDriver.hh
Referenced by AdvanceChordLimited(), G4BFieldIntegrationDriver(), OnComputeStep(), OnStartTracking(), SetEquationOfMotion(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4BFieldIntegrationDriver.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4BFieldIntegrationDriver.cc