ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/G4BuildGeom.cc File Reference
G4BuildGeom.cc File Reference
#include <iomanip>
#include <fstream>
#include "globals.hh"
#include "G3toG4.hh"
#include "G3MatTable.hh"
#include "G3MedTable.hh"
#include "G3RotTable.hh"
#include "G3VolTable.hh"
#include "G3PartTable.hh"
#include "G3DetTable.hh"
#include "G3toG4BuildTree.hh"
#include "G4GeometryManager.hh"
#include "G4LogicalVolume.hh"
#include "G4LogicalVolumeStore.hh"
#include "G4PVPlacement.hh"
#include "G4VisAttributes.hh"
Functions
void G3CLRead (G4String &, char *)
void checkVol (G4LogicalVolume *, G4int)
void checkVol ()
G4LogicalVolume * G4BuildGeom (G4String &inFile)
Variables
std::ofstream ofile
Function Documentation
void checkVol (G4LogicalVolume * _lvol, G4int level)
Definition at line 117 of file G4BuildGeom.cc.
View newest version in sPHENIX GitHub at line 117 of file G4BuildGeom.cc
References G4cout, G4endl, and G4LogicalVolume::GetName().
Referenced by checkVol(), and G4BuildGeom().
void checkVol ()
Definition at line 109 of file G4BuildGeom.cc.
View newest version in sPHENIX GitHub at line 109 of file G4BuildGeom.cc
References checkVol(), and G4LogicalVolumeStore::GetInstance().
void G3CLRead (G4String & , char *)
Definition at line 98 of file clparse.cc.
View newest version in sPHENIX GitHub at line 98 of file clparse.cc
References G3CLEval(), G3CLTokens(), G4endl, ofile, and G4String::readLine().
Referenced by G4BuildGeom().
G4LogicalVolume* G4BuildGeom (G4String & inFile)
Definition at line 54 of file G4BuildGeom.cc.
View newest version in sPHENIX GitHub at line 54 of file G4BuildGeom.cc
References checkVol(), G3CLRead(), G3Det, G3Part, G3toG4BuildTree(), G3Vol, G4cout, G4endl, G4gsrotm(), G3VolTable::GetFirstVTE(), G4VisAttributes::GetInvisible(), G3VolTableEntry::GetLV(), G3VolTableEntry::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetVisAttributes(), G3DetTable::PrintAll(), G3PartTable::PrintAll(), G3VolTable::PrintAll(), and G4LogicalVolume::SetVisAttributes().
Referenced by G3toG4DetectorConstruction::Construct().
Variable Documentation
std::ofstream ofile
Definition at line 44 of file clparse.cc.
View newest version in sPHENIX GitHub at line 44 of file clparse.cc
Referenced by G4VScoreWriter::DumpAllQuantitiesToFile(), G4VScoreWriter::DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), PHTpcEventExporter::exportEvent(), G3CLEval(), G3CLRead(), G3fillParams(), if(), main(), runLCELoop(), G4GMocrenIO::storeData2(), G4GMocrenIO::storeData3(), and G4GMocrenIO::storeData4().