ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4Tubs.cc File Reference
pyG4Tubs.cc File Reference
#include <boost/python.hpp>
#include "G4Tubs.hh"
Namespaces
namespace pyG4Tubs
Functions
G4Tubs * pyG4Tubs::CreateTubs (const G4String &name, G4double pRMin, G4double pRMax, G4double pDz, G4double pSPhi, G4double pDPhi)
void export_G4Tubs ()
Function Documentation
void export_G4Tubs ()
Definition at line 54 of file pyG4Tubs.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4Tubs.cc
References pyG4Tubs::CreateTubs(), G4Tubs::GetDeltaPhiAngle(), G4Tubs::GetDPhi(), G4Tubs::GetDz(), G4Tubs::GetInnerRadius(), G4Tubs::GetOuterRadius(), G4Tubs::GetRMax(), G4Tubs::GetRMin(), G4Tubs::GetSPhi(), G4Tubs::GetStartPhiAngle(), G4Tubs::GetZHalfLength(), init(), G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), and G4Tubs::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().