ECCE @ EIC Software: G4ElementData Class Reference
G4ElementData Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4ElementData.hh>
Public Member Functions
G4ElementData ()
~G4ElementData ()
void InitialiseForElement (G4int Z, G4PhysicsVector *v)
void InitialiseForElement (G4int Z, G4Physics2DVector *v)
void InitialiseForComponent (G4int Z, G4int nComponents=0)
void AddComponent (G4int Z, G4int id, G4PhysicsVector *v)
void SetName (const G4String &nam)
G4PhysicsVector * GetElementData (G4int Z)
G4Physics2DVector * GetElement2DData (G4int Z)
size_t GetNumberOfComponents (G4int Z)
G4int GetComponentID (G4int Z, size_t idx)
G4PhysicsVector * GetComponentDataByIndex (G4int Z, size_t idx)
G4PhysicsVector * GetComponentDataByID (G4int Z, G4int id)
G4double GetValueForElement (G4int Z, G4double kinEnergy)
G4double GetValueForComponent (G4int Z, size_t idx, G4double kinEnergy)
Private Member Functions
G4ElementData & operator= (const G4ElementData &right)=delete
G4ElementData (const G4ElementData &)=delete
Private Attributes
G4PhysicsVector * elmData [maxNumElements]
G4Physics2DVector * elm2Data [maxNumElements]
std::vector< G4PhysicsVector * > compData [maxNumElements]
std::vector< G4int > compID [maxNumElements]
size_t compLength [maxNumElements]
G4String name
Detailed Description
Definition at line 55 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ElementData.hh
Constructor & Destructor Documentation
G4ElementData::G4ElementData () explicit
Definition at line 47 of file G4ElementData.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ElementData.cc
References compLength, elm2Data, elmData, and maxNumElements.
G4ElementData::~G4ElementData ()
Definition at line 59 of file G4ElementData.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ElementData.cc
References compData, compLength, elm2Data, elmData, maxNumElements, and n.
G4ElementData::G4ElementData (const G4ElementData &) private delete
Member Function Documentation
void G4ElementData::AddComponent (G4int Z, G4int id, G4PhysicsVector * v)
Definition at line 121 of file G4ElementData.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ElementData.cc
References compData, compID, compLength, FatalException, G4cout, G4endl, G4Exception(), maxNumElements, and Z.
Referenced by G4LivermorePolarizedPhotoElectricGDModel::ReadData(), G4LivermorePolarizedPhotoElectricModel::ReadData(), and G4LivermorePhotoElectricModel::ReadData().
G4PhysicsVector * G4ElementData::GetComponentDataByID (G4int Z, G4int id) inline
Definition at line 154 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ElementData.hh
References compData, compID, compLength, v, and Z.
G4PhysicsVector * G4ElementData::GetComponentDataByIndex (G4int Z, size_t idx) inline
Definition at line 148 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 148 of file G4ElementData.hh
References compData, and incremental_prev_tag::idx.
Referenced by G4LivermorePhotoElectricModel::GetBindingEnergy().
G4int G4ElementData::GetComponentID (G4int Z, size_t idx) inline
Definition at line 142 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ElementData.hh
References compID, and incremental_prev_tag::idx.
Referenced by G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), and G4LivermorePhotoElectricModel::SampleSecondaries().
G4Physics2DVector * G4ElementData::GetElement2DData (G4int Z) inline
Definition at line 131 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ElementData.hh
References elm2Data, and Z.
Referenced by G4MuonVDNuclearModel::CalculateEMVertex(), G4MuPairProductionModel::FindScaledEnergy(), G4MuPairProductionModel::StoreTables(), G4ePairProduction::StreamProcessInfo(), and G4MuPairProduction::StreamProcessInfo().
G4PhysicsVector * G4ElementData::GetElementData (G4int Z) inline
Definition at line 125 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ElementData.hh
References elmData, and Z.
size_t G4ElementData::GetNumberOfComponents (G4int Z) inline
Definition at line 137 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ElementData.hh
References compLength, and Z.
G4double G4ElementData::GetValueForComponent (G4int Z, size_t idx, G4double kinEnergy) inline
Definition at line 173 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ElementData.hh
References compData.
Referenced by G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), and G4LivermorePhotoElectricModel::SampleSecondaries().
G4double G4ElementData::GetValueForElement (G4int Z, G4double kinEnergy) inline
Definition at line 167 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ElementData.hh
References elmData, G4PhysicsVector::Value(), and Z.
void G4ElementData::InitialiseForComponent (G4int Z, G4int nComponents = 0)
Definition at line 99 of file G4ElementData.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ElementData.cc
References clear(), compData, compID, compLength, FatalException, G4cout, G4endl, G4Exception(), maxNumElements, n, and Z.
Referenced by G4LivermorePolarizedPhotoElectricGDModel::ReadData(), G4LivermorePolarizedPhotoElectricModel::ReadData(), and G4LivermorePhotoElectricModel::ReadData().
void G4ElementData::InitialiseForElement (G4int Z, G4PhysicsVector * v)
Definition at line 73 of file G4ElementData.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ElementData.cc
References elmData, FatalException, G4cout, G4endl, G4Exception(), maxNumElements, v, and Z.
Referenced by G4MuonVDNuclearModel::MakeSamplingTable(), G4MuPairProductionModel::MakeSamplingTables(), and G4MuPairProductionModel::RetrieveTables().
void G4ElementData::InitialiseForElement (G4int Z, G4Physics2DVector * v)
Definition at line 86 of file G4ElementData.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ElementData.cc
References elm2Data, FatalException, G4cout, G4endl, G4Exception(), maxNumElements, v, and Z.
G4ElementData& G4ElementData::operator= (const G4ElementData & right) private delete
void G4ElementData::SetName (const G4String & nam) inline
Definition at line 119 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ElementData.hh
Member Data Documentation
std::vector<G4PhysicsVector*> G4ElementData::compData[maxNumElements] private
Definition at line 113 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ElementData.hh
Referenced by AddComponent(), GetComponentDataByID(), GetComponentDataByIndex(), GetValueForComponent(), InitialiseForComponent(), and ~G4ElementData().
std::vector<G4int> G4ElementData::compID[maxNumElements] private
Definition at line 114 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ElementData.hh
Referenced by AddComponent(), GetComponentDataByID(), GetComponentID(), and InitialiseForComponent().
size_t G4ElementData::compLength[maxNumElements] private
Definition at line 115 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ElementData.hh
Referenced by AddComponent(), G4ElementData(), GetComponentDataByID(), GetNumberOfComponents(), InitialiseForComponent(), and ~G4ElementData().
G4Physics2DVector* G4ElementData::elm2Data[maxNumElements] private
Definition at line 112 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ElementData.hh
Referenced by G4ElementData(), GetElement2DData(), InitialiseForElement(), and ~G4ElementData().
G4PhysicsVector* G4ElementData::elmData[maxNumElements] private
Definition at line 111 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ElementData.hh
Referenced by G4ElementData(), GetElementData(), GetValueForElement(), InitialiseForElement(), and ~G4ElementData().
G4String G4ElementData::name private
Definition at line 116 of file G4ElementData.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ElementData.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4ElementData.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4ElementData.cc