ECCE @ EIC Software: G4Polyhedra Class Reference
G4Polyhedra Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4Polyhedra.hh>
Public Member Functions
G4Polyhedra (const G4String &name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numZPlanes, const G4double zPlane[], const G4double rInner[], const G4double rOuter[])
G4Polyhedra (const G4String &name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numRZ, const G4double r[], const G4double z[])
virtual ~G4Polyhedra ()
EInside Inside (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
G4ThreeVector GetPointOnSurface () const
std::ostream & StreamInfo (std::ostream &os) const
G4Polyhedron * CreatePolyhedron () const
G4bool Reset ()
G4int GetNumSide () const
G4double GetStartPhi () const
G4double GetEndPhi () const
G4double GetSinStartPhi () const
G4double GetCosStartPhi () const
G4double GetSinEndPhi () const
G4double GetCosEndPhi () const
G4bool IsOpen () const
G4bool IsGeneric () const
G4int GetNumRZCorner () const
G4PolyhedraSideRZ GetCorner (const G4int index) const
G4PolyhedraHistorical * GetOriginalParameters () const
void SetOriginalParameters (G4PolyhedraHistorical *pars)
G4Polyhedra (__void__ &)
G4Polyhedra (const G4Polyhedra &source)
G4Polyhedra & operator= (const G4Polyhedra &source)
Public Member Functions inherited from G4VCSGfaceted
G4VCSGfaceted (const G4String &name)
virtual ~G4VCSGfaceted ()
G4VCSGfaceted (const G4VCSGfaceted &source)
G4VCSGfaceted & operator= (const G4VCSGfaceted &source)
virtual G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
virtual G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
virtual G4double DistanceToOut (const G4ThreeVector &p) const
virtual void DescribeYourselfTo (G4VGraphicsScene &scene) const
virtual G4VisExtent GetExtent () const
virtual G4Polyhedron * GetPolyhedron () const
G4int GetCubVolStatistics () const
G4double GetCubVolEpsilon () const
void SetCubVolStatistics (G4int st)
void SetCubVolEpsilon (G4double ep)
G4int GetAreaStatistics () const
G4double GetAreaAccuracy () const
void SetAreaStatistics (G4int st)
void SetAreaAccuracy (G4double ep)
virtual G4double GetCubicVolume ()
virtual G4double GetSurfaceArea ()
G4VCSGfaceted (__void__ &)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Member Functions
void SetOriginalParameters (G4ReduciblePolygon *rz)
void Create (G4double phiStart, G4double phiTotal, G4int numSide, G4ReduciblePolygon *rz)
void CopyStuff (const G4Polyhedra &source)
void DeleteStuff ()
G4ThreeVector GetPointOnPlane (G4ThreeVector p0, G4ThreeVector p1, G4ThreeVector p2, G4ThreeVector p3) const
G4ThreeVector GetPointOnTriangle (G4ThreeVector p0, G4ThreeVector p1, G4ThreeVector p2) const
G4ThreeVector GetPointOnSurfaceCorners () const
Protected Member Functions inherited from G4VCSGfaceted
virtual G4double DistanceTo (const G4ThreeVector &p, const G4bool outgoing) const
G4ThreeVector GetPointOnSurfaceGeneric () const
void CopyStuff (const G4VCSGfaceted &source)
void DeleteStuff ()
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes
G4int numSide = 0
G4double startPhi
G4double endPhi
G4bool phiIsOpen = false
G4bool genericPgon = false
G4int numCorner = 0
G4PolyhedraSideRZ * corners = nullptr
G4PolyhedraHistorical * original_parameters = nullptr
G4EnclosingCylinder * enclosingCylinder = nullptr
Protected Attributes inherited from G4VCSGfaceted
G4int numFace = 0
G4VCSGface ** faces = nullptr
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 74 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 74 of file G4Polyhedra.hh
Constructor & Destructor Documentation
G4Polyhedra::G4Polyhedra (const G4String & name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numZPlanes, const G4double zPlane[], const G4double rInner[], const G4double rOuter[])
Definition at line 68 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 68 of file G4Polyhedra.cc
References Create(), DBL_EPSILON, G4VSolid::DumpInfo(), FatalErrorInArgument, G4endl, G4Exception(), G4VSolid::GetName(), message(), G4PolyhedraHistorical::Num_z_planes, G4PolyhedraHistorical::numSide, G4PolyhedraHistorical::Opening_angle, original_parameters, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, G4ReduciblePolygon::ScaleA(), G4PolyhedraHistorical::Start_angle, twopi, and G4PolyhedraHistorical::Z_values.
Referenced by Clone().
G4Polyhedra::G4Polyhedra (const G4String & name, G4double phiStart, G4double phiTotal, G4int numSide, G4int numRZ, const G4double r[], const G4double z[])
Definition at line 151 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 151 of file G4Polyhedra.cc
References Create(), FatalErrorInArgument, G4endl, G4Exception(), G4VSolid::GetName(), message(), and SetOriginalParameters().
G4Polyhedra::~G4Polyhedra () virtual
Definition at line 368 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 368 of file G4Polyhedra.cc
References corners, enclosingCylinder, and original_parameters.
G4Polyhedra::G4Polyhedra (__void__ & a)
Definition at line 361 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 361 of file G4Polyhedra.cc
G4Polyhedra::G4Polyhedra (const G4Polyhedra & source)
Definition at line 377 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 377 of file G4Polyhedra.cc
References CopyStuff().
Member Function Documentation
void G4Polyhedra::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 531 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 531 of file G4Polyhedra.cc
References G4VSolid::DumpInfo(), G4Exception(), GetCorner(), GetCosStartPhi(), GetEndPhi(), G4VSolid::GetName(), GetNumRZCorner(), GetNumSide(), GetSinStartPhi(), GetStartPhi(), IsOpen(), JustWarning, k, kInfinity, message(), pMax, G4PolyhedraSideRZ::r, rmax(), CLHEP::Hep3Vector::set(), twopi, CLHEP::Hep3Vector::x(), x, xmax, xmin, xx, CLHEP::Hep3Vector::y(), y, ymax, ymin, G4PolyhedraSideRZ::z, and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4Polyhedra::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 599 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 599 of file G4Polyhedra.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), emax, CEMC_TOWER::emin, G4Exception(), GetCorner(), GetCosStartPhi(), GetEndPhi(), G4VoxelLimits::GetMaxExtent(), G4VoxelLimits::GetMinExtent(), G4VSolid::GetName(), GetNumRZCorner(), GetNumSide(), GetSinStartPhi(), GetStartPhi(), IsOpen(), JustWarning, k, G4VSolid::kCarTolerance, kInfinity, message(), pMax, G4GeomTools::PolygonArea(), G4PolyhedraSideRZ::r, G4GeomTools::RemoveRedundantVertices(), reverse, G4GeomTools::TriangulatePolygon(), twopi, x, y, and G4PolyhedraSideRZ::z.
G4VSolid * G4Polyhedra::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 731 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 731 of file G4Polyhedra.cc
References G4Polyhedra().
void G4Polyhedra::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 715 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 715 of file G4Polyhedra.cc
References G4VPVParameterisation::ComputeDimensions().
void G4Polyhedra::CopyStuff (const G4Polyhedra & source) protected
Definition at line 402 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 402 of file G4Polyhedra.cc
References corners, enclosingCylinder, endPhi, G4VCSGfaceted::fpPolyhedron, G4VCSGfaceted::fRebuildPolyhedron, genericPgon, numCorner, numSide, original_parameters, phiIsOpen, and startPhi.
Referenced by G4Polyhedra(), and operator=().
void G4Polyhedra::Create (G4double phiStart, G4double phiTotal, G4int numSide, G4ReduciblePolygon * rz) protected
Definition at line 185 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 185 of file G4Polyhedra.cc
References G4ReduciblePolygon::Amin(), G4ReduciblePolygon::Area(), G4ReduciblePolygonIterator::Begin(), corners, G4ReduciblePolygon::CrossesItself(), DBL_EPSILON, enclosingCylinder, endPhi, G4VCSGfaceted::faces, FatalErrorInArgument, G4endl, G4Exception(), G4ReduciblePolygonIterator::GetA(), G4ReduciblePolygonIterator::GetB(), G4VSolid::GetName(), G4VSolid::kCarTolerance, kInfinity, message(), G4ReduciblePolygonIterator::Next(), numCorner, G4VCSGfaceted::numFace, numSide, G4ReduciblePolygon::NumVertices(), phiIsOpen, G4PolyhedraSideRZ::r, G4ReduciblePolygon::RemoveDuplicateVertices(), G4ReduciblePolygon::RemoveRedundantVertices(), G4ReduciblePolygon::ReverseOrder(), startPhi, twopi, and G4PolyhedraSideRZ::z.
Referenced by G4Polyhedra(), and Reset().
G4Polyhedron * G4Polyhedra::CreatePolyhedron () const virtual
Creates user defined polyhedron. This function allows to the user to define arbitrary polyhedron. The faces of the polyhedron should be either triangles or planar quadrilateral. Nodes of a face are defined by indexes pointing to the elements in the xyz array. Numeration of the elements in the array starts from 1 (like in fortran). The indexes can be positive or negative. Negative sign means that the corresponding edge is invisible. The normal of the face should be directed to exterior of the polyhedron.
Parameters
Nnodes number of nodes
Nfaces number of faces
xyz nodes
faces_vec faces (quadrilaterals or triangles)
Returns
status of the operation - is non-zero in case of problem
Implements G4VCSGfaceted.
Definition at line 1052 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 1052 of file G4Polyhedra.cc
References a, A(), ab, kdfinder::abs(), b, B(), C(), c, corners, HepPolyhedron::createPolyhedron(), d, endPhi, G4Exception(), genericPgon, G4VSolid::GetName(), JustWarning, G4VSolid::kCarTolerance, message(), G4PolyhedraHistorical::Num_z_planes, numCorner, G4PolyhedraHistorical::numSide, numSide, G4PolyhedraHistorical::Opening_angle, original_parameters, phi, phiIsOpen, G4PolyhedraSideRZ::r, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, G4PolyhedraHistorical::Start_angle, startPhi, twopi, G4PolyhedraSideRZ::z, and G4PolyhedraHistorical::Z_values.
void G4Polyhedra::DeleteStuff () protected
G4double G4Polyhedra::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 507 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 507 of file G4Polyhedra.cc
References G4VCSGfaceted::DistanceToIn(), enclosingCylinder, kInfinity, and G4EnclosingCylinder::ShouldMiss().
G4double G4Polyhedra::DistanceToIn (const G4ThreeVector & p) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 524 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 524 of file G4Polyhedra.cc
References G4VCSGfaceted::DistanceToIn().
G4PolyhedraSideRZ G4Polyhedra::GetCorner (const G4int index) const inline
Referenced by BoundingLimits(), CalculateExtent(), G4tgbGeometryDumper::GetSolidParams(), PHG4GDMLWriteSolids::PolyhedraWrite(), and G4GDMLWriteSolids::PolyhedraWrite().
G4double G4Polyhedra::GetCosEndPhi () const inline
G4double G4Polyhedra::GetCosStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Polyhedra::GetEndPhi () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4VParameterisationPolyhedra::ConvertRadiusFactor(), export_G4Polyhedra(), G4ParameterisationPolyhedraPhi::G4ParameterisationPolyhedraPhi(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), and G4ParameterisationPolyhedraPhi::GetMaxParameter().
G4GeometryType G4Polyhedra::GetEntityType () const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 724 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 724 of file G4Polyhedra.cc
G4int G4Polyhedra::GetNumRZCorner () const inline
Referenced by BoundingLimits(), CalculateExtent(), export_G4Polyhedra(), G4tgbGeometryDumper::GetSolidParams(), PHG4GDMLWriteSolids::PolyhedraWrite(), and G4GDMLWriteSolids::PolyhedraWrite().
G4int G4Polyhedra::GetNumSide () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), export_G4Polyhedra(), G4ParameterisationPolyhedraPhi::G4ParameterisationPolyhedraPhi(), and G4tgbGeometryDumper::GetSolidParams().
G4PolyhedraHistorical* G4Polyhedra::GetOriginalParameters () const inline
Referenced by G4tgbVolume::BuildSolidForDivision(), G4ParameterisationPolyhedraPhi::CheckParametersValidity(), G4ParameterisationPolyhedraRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationPolyhedraPhi::ComputeDimensions(), G4VParameterisationPolyhedra::ConvertRadiusFactor(), G4ParameterisationPolyhedraRho::G4ParameterisationPolyhedraRho(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), G4ParameterisationPolyhedraRho::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Polyhedra_dimensionsWrite(), PHG4GDMLWriteParamvol::Polyhedra_dimensionsWrite(), PHG4GDMLWriteSolids::PolyhedraWrite(), and G4GDMLWriteSolids::PolyhedraWrite().
G4ThreeVector G4Polyhedra::GetPointOnPlane (G4ThreeVector p0, G4ThreeVector p1, G4ThreeVector p2, G4ThreeVector p3) const protected
Definition at line 791 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 791 of file G4Polyhedra.cc
References CLHEP::normal(), G4INCL::DeJongSpin::shoot(), t, Acts::UnitConstants::u, v, and w.
Referenced by GetPointOnSurface().
G4ThreeVector G4Polyhedra::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 836 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 836 of file G4Polyhedra.cc
References a, b, endPhi, genericPgon, GetPointOnPlane(), G4VCSGfaceted::GetPointOnSurfaceGeneric(), G4PolyhedraHistorical::Num_z_planes, numSide, original_parameters, phiIsOpen, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, G4INCL::DeJongSpin::shoot(), sqr(), startPhi, twopi, and G4PolyhedraHistorical::Z_values.
G4ThreeVector G4Polyhedra::GetPointOnSurfaceCorners () const protected
G4ThreeVector G4Polyhedra::GetPointOnTriangle (G4ThreeVector p0, G4ThreeVector p1, G4ThreeVector p2) const protected
Definition at line 821 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 821 of file G4Polyhedra.cc
References G4INCL::DeJongSpin::shoot(), v, and w.
G4double G4Polyhedra::GetSinEndPhi () const inline
G4double G4Polyhedra::GetSinStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Polyhedra::GetStartPhi () const inline
Referenced by BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4VParameterisationPolyhedra::ConvertRadiusFactor(), export_G4Polyhedra(), G4ParameterisationPolyhedraPhi::G4ParameterisationPolyhedraPhi(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), G4ParameterisationPolyhedraPhi::GetMaxParameter(), and G4tgbGeometryDumper::GetSolidParams().
EInside G4Polyhedra::Inside (const G4ThreeVector & p) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 489 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 489 of file G4Polyhedra.cc
References enclosingCylinder, G4VCSGfaceted::Inside(), kOutside, and G4EnclosingCylinder::MustBeOutside().
G4bool G4Polyhedra::IsGeneric () const inline
Referenced by export_G4Polyhedra(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), PHG4GDMLWriteSolids::PolyhedraWrite(), and G4GDMLWriteSolids::PolyhedraWrite().
G4bool G4Polyhedra::IsOpen () const inline
Referenced by BoundingLimits(), CalculateExtent(), and export_G4Polyhedra().
G4Polyhedra & G4Polyhedra::operator= (const G4Polyhedra & source)
Definition at line 385 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 385 of file G4Polyhedra.cc
References CopyStuff(), corners, enclosingCylinder, G4VCSGfaceted::operator=(), and original_parameters.
G4bool G4Polyhedra::Reset ()
Definition at line 449 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 449 of file G4Polyhedra.cc
References corners, Create(), G4VCSGfaceted::DeleteStuff(), enclosingCylinder, G4endl, G4Exception(), genericPgon, G4VSolid::GetName(), JustWarning, message(), G4PolyhedraHistorical::Num_z_planes, G4PolyhedraHistorical::numSide, G4PolyhedraHistorical::Opening_angle, original_parameters, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, G4PolyhedraHistorical::Start_angle, and G4PolyhedraHistorical::Z_values.
Referenced by G4ParameterisationPolyhedraRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationPolyhedraPhi::ComputeDimensions(), and G4ParameterisationPolyhedraZ::ComputeDimensions().
void G4Polyhedra::SetOriginalParameters (G4PolyhedraHistorical * pars) inline
Referenced by G4ParameterisationPolyhedraRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), G4ParameterisationPolyhedraPhi::ComputeDimensions(), G4ParameterisationPolyhedraZ::ComputeDimensions(), and G4Polyhedra().
void G4Polyhedra::SetOriginalParameters (G4ReduciblePolygon * rz) protected
Definition at line 1310 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 1310 of file G4Polyhedra.cc
References G4ReduciblePolygon::Bmax(), corners, endPhi, G4endl, G4Exception(), G4VSolid::GetName(), JustWarning, G4VSolid::kCarTolerance, message(), G4PolyhedraHistorical::Num_z_planes, numCorner, G4PolyhedraHistorical::numSide, numSide, G4PolyhedraHistorical::Opening_angle, original_parameters, r, G4PolyhedraSideRZ::r, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, G4PolyhedraHistorical::Start_angle, startPhi, G4ReduciblePolygon::StartWithZMin(), Z, G4PolyhedraSideRZ::z, z, G4PolyhedraHistorical::Z_values, and Zmax.
std::ostream & G4Polyhedra::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4VCSGfaceted.
Definition at line 738 of file G4Polyhedra.cc.
View newest version in sPHENIX GitHub at line 738 of file G4Polyhedra.cc
References corners, degree, endPhi, genericPgon, G4VSolid::GetName(), G4PolyhedraHistorical::Num_z_planes, numCorner, numSide, original_parameters, G4PolyhedraSideRZ::r, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, startPhi, G4PolyhedraSideRZ::z, and G4PolyhedraHistorical::Z_values.
Member Data Documentation
G4PolyhedraSideRZ* G4Polyhedra::corners = nullptr protected
Definition at line 189 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 189 of file G4Polyhedra.hh
Referenced by CopyStuff(), Create(), CreatePolyhedron(), operator=(), Reset(), SetOriginalParameters(), StreamInfo(), and ~G4Polyhedra().
G4EnclosingCylinder* G4Polyhedra::enclosingCylinder = nullptr protected
Definition at line 192 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 192 of file G4Polyhedra.hh
Referenced by CopyStuff(), Create(), DistanceToIn(), Inside(), operator=(), Reset(), and ~G4Polyhedra().
G4double G4Polyhedra::endPhi protected
Definition at line 185 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 185 of file G4Polyhedra.hh
Referenced by CopyStuff(), Create(), CreatePolyhedron(), GetPointOnSurface(), SetOriginalParameters(), and StreamInfo().
G4bool G4Polyhedra::genericPgon = false protected
Definition at line 187 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 187 of file G4Polyhedra.hh
Referenced by CopyStuff(), CreatePolyhedron(), GetPointOnSurface(), Reset(), and StreamInfo().
G4int G4Polyhedra::numCorner = 0 protected
Definition at line 188 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 188 of file G4Polyhedra.hh
Referenced by CopyStuff(), Create(), CreatePolyhedron(), SetOriginalParameters(), and StreamInfo().
G4int G4Polyhedra::numSide = 0 protected
Definition at line 183 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 183 of file G4Polyhedra.hh
Referenced by CopyStuff(), Create(), CreatePolyhedron(), GetPointOnSurface(), SetOriginalParameters(), and StreamInfo().
G4PolyhedraHistorical* G4Polyhedra::original_parameters = nullptr protected
Definition at line 190 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 190 of file G4Polyhedra.hh
Referenced by CopyStuff(), CreatePolyhedron(), G4Polyhedra(), GetPointOnSurface(), operator=(), Reset(), SetOriginalParameters(), StreamInfo(), and ~G4Polyhedra().
G4bool G4Polyhedra::phiIsOpen = false protected
Definition at line 186 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 186 of file G4Polyhedra.hh
Referenced by CopyStuff(), Create(), CreatePolyhedron(), and GetPointOnSurface().
G4double G4Polyhedra::startPhi protected
Definition at line 184 of file G4Polyhedra.hh.
View newest version in sPHENIX GitHub at line 184 of file G4Polyhedra.hh
Referenced by CopyStuff(), Create(), CreatePolyhedron(), GetPointOnSurface(), SetOriginalParameters(), and StreamInfo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4Polyhedra.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4Polyhedra.cc