ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/ptwXY_methods.cc File Reference
ptwXY_methods.cc File Reference
#include <cmath>
#include <float.h>
#include "ptwXY.h"
Functions
static nfu_status ptwXY_clip2 (ptwXYPoints *ptwXY1, double y, double x1, double y1, double x2, double y2)
static double ptwXY_thicken_linear_dx (int sectionSubdivideMax, double dxMax, double x1, double x2)
static nfu_status ptwXY_thin2 (ptwXYPoints *thinned, char *thin, double accuracy, int64_t i1, int64_t i2)
nfu_status ptwXY_clip (ptwXYPoints *ptwXY1, double yMin, double yMax)
nfu_status ptwXY_thicken (ptwXYPoints *ptwXY1, int sectionSubdivideMax, double dxMax, double fxMax)
ptwXYPoints * ptwXY_thin (ptwXYPoints *ptwXY1, double accuracy, nfu_status *status)
nfu_status ptwXY_trim (ptwXYPoints *ptwXY)
ptwXYPoints * ptwXY_union (ptwXYPoints *ptwXY1, ptwXYPoints *ptwXY2, nfu_status *status, int unionOptions)
nfu_status ptwXY_scaleOffsetXAndY (ptwXYPoints *ptwXY, double xScale, double xOffset, double yScale, double yOffset)
Function Documentation
nfu_status ptwXY_clip (ptwXYPoints * ptwXY1, double yMin, double yMax)
Definition at line 25 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 25 of file ptwXY_methods.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::allocatedSize, ptwXYPoints_s::biSectionMax, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, ptwXYPoints_s::length, n, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_clear(), ptwXY_clip2(), ptwXY_free(), ptwXY_getPointAtIndex_Unsafely(), ptwXY_getYMax(), ptwXY_getYMin(), ptwXY_interpolationOther, ptwXY_new(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, ptwXYPoints_s::userFlag, ptwXYPoint_s::x, x2, ptwXYPoint_s::y, and y2.
static nfu_status ptwXY_clip2 (ptwXYPoints * ptwXY1, double y, double x1, double y1, double x2, double y2) static
Definition at line 126 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 126 of file ptwXY_methods.cc
References nfu_Okay, ptwXY_setValueAtX(), x, x1, and y1.
Referenced by ptwXY_clip().
nfu_status ptwXY_scaleOffsetXAndY (ptwXYPoints * ptwXY, double xScale, double xOffset, double yScale, double yOffset)
Definition at line 481 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 481 of file ptwXY_methods.cc
References BTOF::length, ptwXYPoints_s::length, nfu_Okay, nfu_XNotAscending, ptwXYPoints_s::points, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, tmp, ptwXYPoint_s::x, and ptwXYPoint_s::y.
Referenced by MCGIDI_misc_Data2ptwXYPointsInUnitsOf().
nfu_status ptwXY_thicken (ptwXYPoints * ptwXY1, int sectionSubdivideMax, double dxMax, double fxMax)
Definition at line 144 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 144 of file ptwXY_methods.cc
References dx, G4Exp(), G4Log(), int(), ptwXYPoints_s::interpolation, ptwXYPoints_s::length, nfu_badInput, nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::points, ptwXY_interpolatePoint(), ptwXY_interpolationOther, ptwXY_sectionSubdivideMax, ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), ptwXY_thicken_linear_dx(), ptwXYPoint_s::x, x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
static double ptwXY_thicken_linear_dx (int sectionSubdivideMax, double dxMax, double x1, double x2) static
Definition at line 295 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 295 of file ptwXY_methods.cc
References dx, e, int(), and x1.
Referenced by ptwXY_thicken().
ptwXYPoints* ptwXY_thin (ptwXYPoints * ptwXY1, double accuracy, nfu_status * status)
Definition at line 211 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 211 of file ptwXY_methods.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, ptwXYPoints_s::interpolation, ptwXYPoints_s::interpolationOtherInfo, BTOF::length, ptwXYPoints_s::length, nfu_calloc(), nfu_free(), nfu_Okay, nfu_otherInterpolation, ptwXYPoints_s::overflowLength, ptwXYPoints_s::points, ptwXY_clone(), ptwXY_free(), ptwXY_interpolationFlat, ptwXY_interpolationOther, ptwXY_new(), ptwXY_simpleCoalescePoints(), ptwXY_thin2(), ptwXYPoints_s::userFlag, ptwXYPoint_s::y, y1, y2, and y3.
static nfu_status ptwXY_thin2 (ptwXYPoints * thinned, char * thin, double accuracy, int64_t i1, int64_t i2) static
Definition at line 264 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 264 of file ptwXY_methods.cc
References Acts::Test::dY, ptwXYPoints_s::interpolation, nfu_Okay, ptwXYPoints_s::points, ptwXY_interpolatePoint(), ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
Referenced by ptwXY_thin().
nfu_status ptwXY_trim (ptwXYPoints * ptwXY)
Definition at line 315 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 315 of file ptwXY_methods.cc
References BTOF::length, ptwXYPoints_s::length, nfu_Okay, ptwXYPoints_s::points, ptwXY_simpleCoalescePoints(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
ptwXYPoints* ptwXY_union (ptwXYPoints * ptwXY1, ptwXYPoints * ptwXY2, nfu_status * status, int unionOptions)
Definition at line 349 of file ptwXY_methods.cc.
View newest version in sPHENIX GitHub at line 349 of file ptwXY_methods.cc
References ptwXYPoints_s::accuracy, ptwXYPoints_s::biSectionMax, DBL_EPSILON, ptwXYPoints_s::interpolation, BTOF::length, ptwXYPoints_s::length, n, n1, nfu_Okay, nfu_otherInterpolation, nfu_tooFewPoints, ptwXYPoints_s::overflowAllocatedSize, ptwXYPoints_s::points, ptwXY_free(), ptwXY_interpolatePoint(), ptwXY_interpolationOther, ptwXY_mergeClosePoints(), ptwXY_minimumSize, ptwXY_new(), ptwXY_simpleCoalescePoints(), ptwXY_union_fill, ptwXY_union_mergeClosePoints, ptwXY_union_trim, ptwXYPoints_s::status, ptwXYPoints_s::userFlag, ptwXYPoint_s::x, x1, x2, ptwXYPoint_s::y, y, y1, and y2.
Referenced by ptwXY_binary_ptwXY(), ptwXY_div_ptwXY(), ptwXY_div_ptwXY_forFlats(), ptwXY_groupThreeFunctions(), and ptwXY_groupTwoFunctions().