ECCE @ EIC Software: G4EmModelActivator Class Reference
G4EmModelActivator Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4EmModelActivator.hh>
Public Member Functions
G4EmModelActivator (const G4String &emphys="")
Private Member Functions
void ActivatePAI ()
void ActivateMicroElec ()
void ActivateEmOptions ()
void FindOrAddProcess (const G4ParticleDefinition *, const G4String &)
void AddStandardScattering (const G4ParticleDefinition *, G4EmConfigurator *, G4VMscModel *, const G4String &, G4double, G4double)
G4bool HasMsc (G4ProcessManager *) const
G4VMscModel * GetGSModel ()
G4EmModelActivator & operator= (const G4EmModelActivator &right)=delete
G4EmModelActivator (const G4EmModelActivator &)=delete
Private Attributes
G4EmParameters * theParameters
G4String baseName
Detailed Description
Definition at line 58 of file G4EmModelActivator.hh.
View newest version in sPHENIX GitHub at line 58 of file G4EmModelActivator.hh
Constructor & Destructor Documentation
G4EmModelActivator::G4EmModelActivator (const G4String & emphys = "") explicit
Definition at line 121 of file G4EmModelActivator.cc.
View newest version in sPHENIX GitHub at line 121 of file G4EmModelActivator.cc
References ActivateEmOptions(), ActivateMicroElec(), ActivatePAI(), G4EmParameters::Instance(), G4EmParameters::RegionsMicroElec(), G4EmParameters::RegionsPAI(), G4EmParameters::RegionsPhysics(), and theParameters.
G4EmModelActivator::G4EmModelActivator (const G4EmModelActivator &) private delete
Member Function Documentation
void G4EmModelActivator::ActivateEmOptions () private
Definition at line 145 of file G4EmModelActivator.cc.
View newest version in sPHENIX GitHub at line 145 of file G4EmModelActivator.cc
References AddStandardScattering(), G4LossTableManager::AtomDeexcitation(), baseName, G4EmParameters::DefineRegParamForDeex(), G4Electron::Electron(), G4LossTableManager::EmConfigurator(), FindOrAddProcess(), G4ParticleTable::FindParticle(), fMinimal, fUseDistanceToBoundary, fUseSafety, fUseSafetyPlus, G4cout, G4endl, G4Gamma::Gamma(), GetGSModel(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), GeV, G4EmParameters::Instance(), G4LossTableManager::Instance(), G4Threading::IsMasterThread(), MeV, G4EmParameters::MscEnergyLimit(), particle, G4EmParticleList::PartNames(), G4Positron::Positron(), G4Proton::Proton(), reg, G4EmParameters::RegionsPhysics(), sc, G4EmParameters::SetAugerCascade(), G4EmParameters::SetDeexActiveRegion(), G4EmParameters::SetDeexcitationIgnoreCut(), G4EmConfigurator::SetExtraEmModel(), G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLocked(), G4EmParameters::SetNumberOfBinsPerDecade(), G4VEmModel::SetPolarAngleLimit(), G4VMscModel::SetRangeFactor(), G4VMscModel::SetSkin(), G4VMscModel::SetStepLimitType(), G4EmParameters::SetUseMottCorrection(), TeV, theParameters, G4EmParameters::TypesPhysics(), and G4EmParameters::Verbose().
Referenced by G4EmModelActivator().
void G4EmModelActivator::ActivateMicroElec () private
Definition at line 515 of file G4EmModelActivator.cc.
View newest version in sPHENIX GitHub at line 515 of file G4EmModelActivator.cc
References G4ProcessManager::AddDiscreteProcess(), G4Electron::Electron(), G4LossTableManager::EmConfigurator(), eV, G4cout, G4endl, G4GenericIon::GenericIon(), G4ParticleDefinition::GetProcessManager(), HasMsc(), G4LossTableManager::Instance(), keV, MeV, G4Proton::Proton(), reg, G4EmParameters::RegionsMicroElec(), G4VEmModel::SetActivationHighEnergyLimit(), G4VEmModel::SetActivationLowEnergyLimit(), G4EmConfigurator::SetExtraEmModel(), TeV, theParameters, and G4EmParameters::Verbose().
Referenced by G4EmModelActivator().
void G4EmModelActivator::ActivatePAI () private
Definition at line 431 of file G4EmModelActivator.cc.
View newest version in sPHENIX GitHub at line 431 of file G4EmModelActivator.cc
References G4Electron::Electron(), G4ParticleTable::FindParticle(), Acts::UnitConstants::fm, G4cout, G4endl, G4GenericIon::GenericIon(), G4LossTableManager::GetEnergyLossProcessVector(), G4RegionStore::GetInstance(), G4ParticleTable::GetParticleTable(), G4RegionStore::GetRegion(), G4LossTableManager::Instance(), G4MuonMinus::MuonMinus(), G4MuonPlus::MuonPlus(), G4EmParameters::ParticlesPAI(), G4Positron::Positron(), r, G4EmParameters::RegionsPAI(), theParameters, G4EmParameters::TypesPAI(), v, and G4EmParameters::Verbose().
Referenced by G4EmModelActivator().
void G4EmModelActivator::AddStandardScattering (const G4ParticleDefinition * part, G4EmConfigurator * em_config, G4VMscModel * mscmod, const G4String & reg, G4double e1, G4double e2) private
Definition at line 719 of file G4EmModelActivator.cc.
View newest version in sPHENIX GitHub at line 719 of file G4EmModelActivator.cc
References FindOrAddProcess(), G4ParticleDefinition::GetParticleName(), pname(), G4VEmModel::SetActivationLowEnergyLimit(), G4EmConfigurator::SetExtraEmModel(), and G4VEmModel::SetLocked().
Referenced by ActivateEmOptions().
void G4EmModelActivator::FindOrAddProcess (const G4ParticleDefinition * part, const G4String & name) private
Definition at line 746 of file G4EmModelActivator.cc.
View newest version in sPHENIX GitHub at line 746 of file G4EmModelActivator.cc
References G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::GetProcessList(), G4ProcessManager::GetProcessListLength(), G4ParticleDefinition::GetProcessManager(), Acts::UnitConstants::pm, and G4VEmProcess::SetEmModel().
Referenced by ActivateEmOptions(), and AddStandardScattering().
G4VMscModel * G4EmModelActivator::GetGSModel () private
Definition at line 706 of file G4EmModelActivator.cc.
View newest version in sPHENIX GitHub at line 706 of file G4EmModelActivator.cc
References fUseSafetyPlus, G4VEmModel::SetLocked(), G4GoudsmitSaundersonMscModel::SetOptionMottCorrection(), G4VMscModel::SetRangeFactor(), G4VMscModel::SetSkin(), and G4VMscModel::SetStepLimitType().
Referenced by ActivateEmOptions().
G4bool G4EmModelActivator::HasMsc (G4ProcessManager * pm) const private
Definition at line 688 of file G4EmModelActivator.cc.
View newest version in sPHENIX GitHub at line 688 of file G4EmModelActivator.cc
References fMultipleScattering, G4ProcessManager::GetProcessList(), and G4ProcessManager::GetProcessListLength().
Referenced by ActivateMicroElec().
G4EmModelActivator& G4EmModelActivator::operator= (const G4EmModelActivator & right) private delete
Member Data Documentation
G4String G4EmModelActivator::baseName private
Definition at line 86 of file G4EmModelActivator.hh.
View newest version in sPHENIX GitHub at line 86 of file G4EmModelActivator.hh
Referenced by ActivateEmOptions().
G4EmParameters* G4EmModelActivator::theParameters private
Definition at line 85 of file G4EmModelActivator.hh.
View newest version in sPHENIX GitHub at line 85 of file G4EmModelActivator.hh
Referenced by ActivateEmOptions(), ActivateMicroElec(), ActivatePAI(), and G4EmModelActivator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4EmModelActivator.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/src/G4EmModelActivator.cc