ECCE @ EIC Software: GunPrimaryGeneratorAction Class Reference
GunPrimaryGeneratorAction Class Reference
The primary generator class with particle gun.
#include <geant4/tree/geant4-10.6-release/examples/extended/common/include/GunPrimaryGeneratorAction.hh>
Public Member Functions
GunPrimaryGeneratorAction (const G4String &particleName="geantino", G4double energy=1.*CLHEP::MeV, G4ThreeVector position=G4ThreeVector(0, 0, 0), G4ThreeVector momentumDirection=G4ThreeVector(0, 0, 1))
~GunPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
GunPrimaryGeneratorAction (const G4String &particleName="geantino", G4double energy=1.*CLHEP::MeV, G4ThreeVector position=G4ThreeVector(0, 0, 0), G4ThreeVector momentumDirection=G4ThreeVector(0, 0, 1))
~GunPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
GunPrimaryGeneratorAction (const G4String &particleName="geantino", G4double energy=1.*CLHEP::MeV, G4ThreeVector position=G4ThreeVector(0, 0, 0), G4ThreeVector momentumDirection=G4ThreeVector(0, 0, 1))
~GunPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
Detailed Description
The primary generator class with particle gun.
Author
I. Hrivnacova; IPN Orsay
Definition at line 47 of file GunPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 47 of file GunPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
GunPrimaryGeneratorAction::GunPrimaryGeneratorAction (const G4String & particleName = "geantino", G4double energy = 1.*CLHEP::MeV, G4ThreeVector position = G4ThreeVector(0,0,0), G4ThreeVector momentumDirection = G4ThreeVector(0,0,1))
Definition at line 39 of file GunPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 39 of file GunPrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
GunPrimaryGeneratorAction::~GunPrimaryGeneratorAction ()
Definition at line 62 of file GunPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 62 of file GunPrimaryGeneratorAction.cc
References fParticleGun.
GunPrimaryGeneratorAction::GunPrimaryGeneratorAction (const G4String & particleName = "geantino", G4double energy = 1.*CLHEP::MeV, G4ThreeVector position = G4ThreeVector(0, 0, 0), G4ThreeVector momentumDirection = G4ThreeVector(0, 0, 1))
GunPrimaryGeneratorAction::~GunPrimaryGeneratorAction ()
GunPrimaryGeneratorAction::GunPrimaryGeneratorAction (const G4String & particleName = "geantino", G4double energy = 1.*CLHEP::MeV, G4ThreeVector position = G4ThreeVector(0, 0, 0), G4ThreeVector momentumDirection = G4ThreeVector(0, 0, 1))
GunPrimaryGeneratorAction::~GunPrimaryGeneratorAction ()
Member Function Documentation
void GunPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 69 of file GunPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 69 of file GunPrimaryGeneratorAction.cc
References fParticleGun, and G4ParticleGun::GeneratePrimaryVertex().
virtual void GunPrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
virtual void GunPrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
Member Data Documentation
G4ParticleGun * GunPrimaryGeneratorAction::fParticleGun private
Definition at line 62 of file GunPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 62 of file GunPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GunPrimaryGeneratorAction(), and ~GunPrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/common/include/GunPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/pythia/decayer6/common/include/GunPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/g3tog4/clGeometry/common/include/GunPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/common/src/GunPrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/pythia/decayer6/common/src/GunPrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/extended/g3tog4/clGeometry/common/src/GunPrimaryGeneratorAction.cc