ECCE @ EIC Software: G4NIELCalculator Class Reference
G4NIELCalculator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4NIELCalculator.hh>
Public Member Functions
G4NIELCalculator (G4VEmModel *, G4int verb)
~G4NIELCalculator ()
void Initialise ()
G4double ComputeNIEL (const G4Step *)
G4double RecoilEnergy (const G4Step *)
void AddEmModel (G4VEmModel *)
Private Member Functions
G4NIELCalculator & operator= (const G4NIELCalculator &right)=delete
G4NIELCalculator (const G4NIELCalculator &)=delete
Private Attributes
G4VEmModel * fModel
G4int fVerbose
Detailed Description
Definition at line 60 of file G4NIELCalculator.hh.
View newest version in sPHENIX GitHub at line 60 of file G4NIELCalculator.hh
Constructor & Destructor Documentation
G4NIELCalculator::G4NIELCalculator (G4VEmModel * mod, G4int verb) explicit
Definition at line 60 of file G4NIELCalculator.cc.
View newest version in sPHENIX GitHub at line 60 of file G4NIELCalculator.cc
References fModel, fVerbose, G4cout, G4endl, G4VEmModel::GetName(), G4LossTableManager::Instance(), and G4LossTableManager::SetNIELCalculator().
G4NIELCalculator::~G4NIELCalculator ()
Definition at line 72 of file G4NIELCalculator.cc.
View newest version in sPHENIX GitHub at line 72 of file G4NIELCalculator.cc
G4NIELCalculator::G4NIELCalculator (const G4NIELCalculator &) private delete
Member Function Documentation
void G4NIELCalculator::AddEmModel (G4VEmModel * mod)
Definition at line 77 of file G4NIELCalculator.cc.
View newest version in sPHENIX GitHub at line 77 of file G4NIELCalculator.cc
References fModel, fVerbose, G4cout, G4endl, and G4VEmModel::GetName().
G4double G4NIELCalculator::ComputeNIEL (const G4Step * step)
Definition at line 95 of file G4NIELCalculator.cc.
View newest version in sPHENIX GitHub at line 95 of file G4NIELCalculator.cc
References G4VEmModel::ComputeDEDXPerVolume(), fModel, G4StepPoint::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4StepPoint::GetMaterialCutsCouple(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetPDGMass(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4Step::GetTrack(), BTOF::length, CLHEP::MeV, min, part, T, T1, T2, and track.
void G4NIELCalculator::Initialise ()
Definition at line 90 of file G4NIELCalculator.cc.
View newest version in sPHENIX GitHub at line 90 of file G4NIELCalculator.cc
Referenced by G4LossTableManager::BuildPhysicsTable().
G4NIELCalculator& G4NIELCalculator::operator= (const G4NIELCalculator & right) private delete
G4double G4NIELCalculator::RecoilEnergy (const G4Step * step)
Definition at line 120 of file G4NIELCalculator.cc.
View newest version in sPHENIX GitHub at line 120 of file G4NIELCalculator.cc
References G4Step::GetSecondaryInCurrentStep(), G4ParticleDefinition::IsGeneralIon(), part, and track.
Member Data Documentation
G4VEmModel* G4NIELCalculator::fModel private
Definition at line 86 of file G4NIELCalculator.hh.
View newest version in sPHENIX GitHub at line 86 of file G4NIELCalculator.hh
Referenced by AddEmModel(), ComputeNIEL(), and G4NIELCalculator().
G4int G4NIELCalculator::fVerbose private
Definition at line 87 of file G4NIELCalculator.hh.
View newest version in sPHENIX GitHub at line 87 of file G4NIELCalculator.hh
Referenced by AddEmModel(), and G4NIELCalculator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4NIELCalculator.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4NIELCalculator.cc