ECCE @ EIC Software: G4VTwoBodyAngDst Class Reference
G4VTwoBodyAngDst Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4VTwoBodyAngDst.hh>
Public Member Functions
G4VTwoBodyAngDst (const G4String &name, G4int verbose=0)
virtual ~G4VTwoBodyAngDst ()
virtual G4double GetCosTheta (const G4double &ekin, const G4double &pcm) const =0
virtual void setVerboseLevel (G4int verbose=0)
virtual const G4String & GetName () const
Protected Attributes
G4String theName
G4int verboseLevel
Detailed Description
Definition at line 41 of file G4VTwoBodyAngDst.hh.
View newest version in sPHENIX GitHub at line 41 of file G4VTwoBodyAngDst.hh
Constructor & Destructor Documentation
G4VTwoBodyAngDst::G4VTwoBodyAngDst (const G4String & name, G4int verbose = 0)
Definition at line 34 of file G4VTwoBodyAngDst.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VTwoBodyAngDst.cc
References G4cout, G4endl, theName, and verboseLevel.
virtual G4VTwoBodyAngDst::~G4VTwoBodyAngDst () inline virtual
Definition at line 44 of file G4VTwoBodyAngDst.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VTwoBodyAngDst.hh
Member Function Documentation
virtual G4double G4VTwoBodyAngDst::GetCosTheta (const G4double & ekin, const G4double & pcm) const pure virtual
Implemented in G4NumIntTwoBodyAngDst< NKEBINS, NANGLES >, G4NumIntTwoBodyAngDst< 11, 19 >, G4NumIntTwoBodyAngDst< 15, 19 >, G4ParamExpTwoBodyAngDst< NKEBINS >, G4ParamExpTwoBodyAngDst< 10 >, G4ParamExpTwoBodyAngDst< 9 >, G4InuclParamAngDst, and G4VThreeBodyAngDst.
Referenced by G4CascadeFinalStateAlgorithm::GenerateCosTheta(), and G4CascadeFinalStateAlgorithm::GenerateTwoBody().
virtual const G4String& G4VTwoBodyAngDst::GetName (void) const inline virtual
Definition at line 49 of file G4VTwoBodyAngDst.hh.
View newest version in sPHENIX GitHub at line 49 of file G4VTwoBodyAngDst.hh
References theName.
Referenced by G4CascadeFinalStateAlgorithm::ChooseGenerators().
virtual void G4VTwoBodyAngDst::setVerboseLevel (G4int verbose = 0) inline virtual
Definition at line 48 of file G4VTwoBodyAngDst.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VTwoBodyAngDst.hh
References verboseLevel.
Referenced by G4TwoBodyAngularDist::passVerbose().
Member Data Documentation
G4String G4VTwoBodyAngDst::theName protected
Definition at line 52 of file G4VTwoBodyAngDst.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VTwoBodyAngDst.hh
Referenced by G4VTwoBodyAngDst(), and GetName().
G4int G4VTwoBodyAngDst::verboseLevel protected
Definition at line 53 of file G4VTwoBodyAngDst.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VTwoBodyAngDst.hh
Referenced by G4VTwoBodyAngDst(), and setVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4VTwoBodyAngDst.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4VTwoBodyAngDst.cc