ECCE @ EIC Software: G4AdjointPhotoElectricModel Class Reference
G4AdjointPhotoElectricModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointPhotoElectricModel.hh>
Public Member Functions
G4AdjointPhotoElectricModel ()
~G4AdjointPhotoElectricModel ()
virtual void SampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)
virtual G4double AdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double GetAdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
G4double AdjointCrossSectionPerAtom (const G4Element *anElement, G4double electronEnergy)
void SetTheDirectPEEffectModel (G4PEEffectFluoModel *aModel)
virtual void CorrectPostStepWeight (G4ParticleChange *fParticleChange, G4double old_weight, G4double adjointPrimKinEnergy, G4double projectileKinEnergy, G4bool IsScatProjToProjCase)
Public Member Functions inherited from G4VEmAdjointModel
G4VEmAdjointModel (const G4String &nam)
virtual ~G4VEmAdjointModel ()
virtual G4double DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerAtomPrimToScatPrim (G4double kinEnergyProj, G4double kinEnergyScatProj, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerVolumePrimToSecond (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
virtual G4double DiffCrossSectionPerVolumePrimToScatPrim (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyScatProj)
virtual G4double GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForScatProjToProjCase (G4double PrimAdjEnergy, G4double Tcut=0)
virtual G4double GetSecondAdjEnergyMaxForProdToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy)
void DefineCurrentMaterial (const G4MaterialCutsCouple *couple)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerAtomForSecond (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerAtomForScatProj (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerVolumeForSecond (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerVolumeForScatProj (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
void SetCSMatrices (std::vector< G4AdjointCSMatrix * > *Vec1CSMatrix, std::vector< G4AdjointCSMatrix * > *Vec2CSMatrix)
G4ParticleDefinition * GetAdjointEquivalentOfDirectPrimaryParticleDefinition ()
G4ParticleDefinition * GetAdjointEquivalentOfDirectSecondaryParticleDefinition ()
G4double GetHighEnergyLimit ()
G4double GetLowEnergyLimit ()
void SetHighEnergyLimit (G4double aVal)
void SetLowEnergyLimit (G4double aVal)
void DefineDirectEMModel (G4VEmModel *aModel)
void SetAdjointEquivalentOfDirectPrimaryParticleDefinition (G4ParticleDefinition *aPart)
void SetAdjointEquivalentOfDirectSecondaryParticleDefinition (G4ParticleDefinition *aPart)
void SetSecondPartOfSameType (G4bool aBool)
G4bool GetSecondPartOfSameType ()
void SetUseMatrix (G4bool aBool)
void SetUseMatrixPerElement (G4bool aBool)
void SetUseOnlyOneMatrixForAllElements (G4bool aBool)
void SetApplyCutInRange (G4bool aBool)
G4bool GetUseMatrix ()
G4bool GetUseMatrixPerElement ()
G4bool GetUseOnlyOneMatrixForAllElements ()
G4bool GetApplyCutInRange ()
G4String GetName ()
virtual void SetCSBiasingFactor (G4double aVal)
void SetCorrectWeightForPostStepInModel (G4bool aBool)
void SetAdditionalWeightCorrectionFactorForPostStepOutsideModel (G4double factor)
Private Member Functions
void DefineCurrentMaterialAndElectronEnergy (const G4MaterialCutsCouple *aCouple, G4double eEnergy)
Private Attributes
G4double xsec [40]
G4double totAdjointCS
G4double totBiasedAdjointCS
G4double factorCSBiasing
G4double pre_step_AdjointCS
G4double post_step_AdjointCS
G4double shell_prob [40][40]
G4PEEffectFluoModel * theDirectPEEffectModel
size_t index_element
G4double current_eEnergy
Additional Inherited Members
Protected Member Functions inherited from G4VEmAdjointModel
G4double DiffCrossSectionFunction1 (G4double kinEnergyProj)
G4double DiffCrossSectionFunction2 (G4double kinEnergyProj)
G4double DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj (G4double EkinProd)
G4double SampleAdjSecEnergyFromCSMatrix (size_t MatrixIndex, G4double prim_energy, G4bool IsScatProjToProjCase)
G4double SampleAdjSecEnergyFromCSMatrix (G4double prim_energy, G4bool IsScatProjToProjCase)
void SelectCSMatrix (G4bool IsScatProjToProjCase)
virtual G4double SampleAdjSecEnergyFromDiffCrossSectionPerAtom (G4double prim_energy, G4bool IsScatProjToProjCase)
Protected Attributes inherited from G4VEmAdjointModel
G4VEmModel * theDirectEMModel
G4VParticleChange * pParticleChange
const G4String name
G4int ASelectedNucleus
G4int ZSelectedNucleus
G4Material * SelectedMaterial
G4double kinEnergyProdForIntegration
G4double kinEnergyScatProjForIntegration
G4double kinEnergyProjForIntegration
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForProdToProjBackwardScattering
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForScatProjToProjBackwardScattering
std::vector< G4double > CS_Vs_ElementForScatProjToProjCase
std::vector< G4double > CS_Vs_ElementForProdToProjCase
G4double lastCS
G4double lastAdjointCSForScatProjToProjCase
G4double lastAdjointCSForProdToProjCase
G4ParticleDefinition * theAdjEquivOfDirectPrimPartDef
G4ParticleDefinition * theAdjEquivOfDirectSecondPartDef
G4ParticleDefinition * theDirectPrimaryPartDef
G4bool second_part_of_same_type
G4double preStepEnergy
G4Material * currentMaterial
G4MaterialCutsCouple * currentCouple
size_t currentMaterialIndex
size_t currentCoupleIndex
G4double currentTcutForDirectPrim
G4double currentTcutForDirectSecond
G4bool ApplyCutInRange
G4double mass_ratio_product
G4double mass_ratio_projectile
G4double HighEnergyLimit
G4double LowEnergyLimit
G4double CS_biasing_factor
G4bool UseMatrix
G4bool UseMatrixPerElement
G4bool UseOnlyOneMatrixForAllElements
size_t indexOfUsedCrossSectionMatrix
size_t model_index
G4bool correct_weight_for_post_step_in_model
G4double additional_weight_correction_factor_for_post_step_outside_model
Detailed Description
Definition at line 61 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AdjointPhotoElectricModel.hh
Constructor & Destructor Documentation
G4AdjointPhotoElectricModel::G4AdjointPhotoElectricModel ()
Definition at line 41 of file G4AdjointPhotoElectricModel.cc.
View newest version in sPHENIX GitHub at line 41 of file G4AdjointPhotoElectricModel.cc
References G4AdjointElectron::AdjointElectron(), G4AdjointGamma::AdjointGamma(), current_eEnergy, factorCSBiasing, G4Gamma::Gamma(), index_element, post_step_AdjointCS, pre_step_AdjointCS, G4VEmAdjointModel::second_part_of_same_type, G4VEmAdjointModel::SetApplyCutInRange(), G4VEmAdjointModel::SetUseMatrix(), G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef, theDirectPEEffectModel, G4VEmAdjointModel::theDirectPrimaryPartDef, totAdjointCS, and totBiasedAdjointCS.
G4AdjointPhotoElectricModel::~G4AdjointPhotoElectricModel ()
Definition at line 65 of file G4AdjointPhotoElectricModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4AdjointPhotoElectricModel.cc
Member Function Documentation
G4double G4AdjointPhotoElectricModel::AdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 190 of file G4AdjointPhotoElectricModel.cc.
View newest version in sPHENIX GitHub at line 190 of file G4AdjointPhotoElectricModel.cc
References AdjointCrossSectionPerAtom(), current_eEnergy, G4VEmAdjointModel::currentCouple, G4VEmAdjointModel::currentMaterial, DefineCurrentMaterialAndElectronEnergy(), factorCSBiasing, G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4Material::GetVecNbOfAtomsPerVolume(), index_element, G4VEmAdjointModel::lastCS, min, totAdjointCS, totBiasedAdjointCS, and xsec.
Referenced by GetAdjointCrossSection(), and SampleSecondaries().
G4double G4AdjointPhotoElectricModel::AdjointCrossSectionPerAtom (const G4Element * anElement, G4double electronEnergy)
Definition at line 233 of file G4AdjointPhotoElectricModel.cc.
View newest version in sPHENIX GitHub at line 233 of file G4AdjointPhotoElectricModel.cc
References G4PEEffectFluoModel::ComputeCrossSectionPerAtom(), G4Gamma::Gamma(), G4Element::GetAtomicShell(), G4Element::GetNbOfAtomicShells(), G4Element::GetZ(), index_element, shell_prob, theDirectPEEffectModel, and Z.
Referenced by AdjointCrossSection().
void G4AdjointPhotoElectricModel::CorrectPostStepWeight (G4ParticleChange * fParticleChange, G4double old_weight, G4double adjointPrimKinEnergy, G4double projectileKinEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 168 of file G4AdjointPhotoElectricModel.cc.
View newest version in sPHENIX GitHub at line 168 of file G4AdjointPhotoElectricModel.cc
References factorCSBiasing, G4AdjointCSManager::GetAdjointCSManager(), G4AdjointCSManager::GetPostStepWeightCorrection(), post_step_AdjointCS, pre_step_AdjointCS, G4VParticleChange::ProposeParentWeight(), G4VParticleChange::SetParentWeightByProcess(), and G4VParticleChange::SetSecondaryWeightByProcess().
Referenced by SampleSecondaries().
void G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy (const G4MaterialCutsCouple * aCouple, G4double eEnergy) private
Definition at line 265 of file G4AdjointPhotoElectricModel.cc.
View newest version in sPHENIX GitHub at line 265 of file G4AdjointPhotoElectricModel.cc
References current_eEnergy, G4VEmAdjointModel::currentCouple, G4VEmAdjointModel::currentCoupleIndex, G4VEmAdjointModel::currentMaterial, G4VEmAdjointModel::currentMaterialIndex, G4MaterialCutsCouple::GetIndex(), G4Material::GetIndex(), G4MaterialCutsCouple::GetMaterial(), G4VEmModel::SetCurrentCouple(), and theDirectPEEffectModel.
Referenced by AdjointCrossSection().
G4double G4AdjointPhotoElectricModel::GetAdjointCrossSection (const G4MaterialCutsCouple * aCouple, G4double primEnergy, G4bool IsScatProjToProjCase) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 225 of file G4AdjointPhotoElectricModel.cc.
View newest version in sPHENIX GitHub at line 225 of file G4AdjointPhotoElectricModel.cc
References AdjointCrossSection().
void G4AdjointPhotoElectricModel::SampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange) virtual
Implements G4VEmAdjointModel.
Definition at line 70 of file G4AdjointPhotoElectricModel.cc.
View newest version in sPHENIX GitHub at line 70 of file G4AdjointPhotoElectricModel.cc
References G4ParticleChange::AddSecondary(), AdjointCrossSection(), G4AdjointGamma::AdjointGamma(), b, CorrectPostStepWeight(), G4VEmAdjointModel::currentMaterial, source.hepunit::electron_mass_c2, fStopAndKill, G4UniformRand, G4Track::GetDynamicParticle(), G4Material::GetElementVector(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), G4Material::GetNumberOfElements(), G4Track::GetWeight(), index_element, post_step_AdjointCS, pre_step_AdjointCS, G4VParticleChange::ProposeTrackStatus(), return(), CLHEP::Hep3Vector::rotateUz(), shell_prob, totAdjointCS, twopi, and xsec.
void G4AdjointPhotoElectricModel::SetTheDirectPEEffectModel (G4PEEffectFluoModel * aModel) inline
Definition at line 85 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4AdjointPhotoElectricModel.hh
References G4VEmAdjointModel::DefineDirectEMModel(), and theDirectPEEffectModel.
Member Data Documentation
G4double G4AdjointPhotoElectricModel::current_eEnergy private
Definition at line 109 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AdjointPhotoElectricModel.hh
Referenced by AdjointCrossSection(), DefineCurrentMaterialAndElectronEnergy(), and G4AdjointPhotoElectricModel().
G4double G4AdjointPhotoElectricModel::factorCSBiasing private
Definition at line 99 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 99 of file G4AdjointPhotoElectricModel.hh
Referenced by AdjointCrossSection(), CorrectPostStepWeight(), and G4AdjointPhotoElectricModel().
size_t G4AdjointPhotoElectricModel::index_element private
Definition at line 108 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4AdjointPhotoElectricModel.hh
Referenced by AdjointCrossSection(), AdjointCrossSectionPerAtom(), G4AdjointPhotoElectricModel(), and SampleSecondaries().
G4double G4AdjointPhotoElectricModel::post_step_AdjointCS private
Definition at line 101 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AdjointPhotoElectricModel.hh
Referenced by CorrectPostStepWeight(), G4AdjointPhotoElectricModel(), and SampleSecondaries().
G4double G4AdjointPhotoElectricModel::pre_step_AdjointCS private
Definition at line 100 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 100 of file G4AdjointPhotoElectricModel.hh
Referenced by CorrectPostStepWeight(), G4AdjointPhotoElectricModel(), and SampleSecondaries().
G4double G4AdjointPhotoElectricModel::shell_prob[40][40] private
Definition at line 104 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AdjointPhotoElectricModel.hh
Referenced by AdjointCrossSectionPerAtom(), and SampleSecondaries().
G4PEEffectFluoModel* G4AdjointPhotoElectricModel::theDirectPEEffectModel private
Definition at line 107 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AdjointPhotoElectricModel.hh
Referenced by AdjointCrossSectionPerAtom(), DefineCurrentMaterialAndElectronEnergy(), G4AdjointPhotoElectricModel(), and SetTheDirectPEEffectModel().
G4double G4AdjointPhotoElectricModel::totAdjointCS private
Definition at line 97 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AdjointPhotoElectricModel.hh
Referenced by AdjointCrossSection(), G4AdjointPhotoElectricModel(), and SampleSecondaries().
G4double G4AdjointPhotoElectricModel::totBiasedAdjointCS private
Definition at line 98 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AdjointPhotoElectricModel.hh
Referenced by AdjointCrossSection(), and G4AdjointPhotoElectricModel().
G4double G4AdjointPhotoElectricModel::xsec[40] private
Definition at line 96 of file G4AdjointPhotoElectricModel.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AdjointPhotoElectricModel.hh
Referenced by AdjointCrossSection(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointPhotoElectricModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/src/G4AdjointPhotoElectricModel.cc