ECCE @ EIC Software: G4Tubs Class Reference
G4Tubs Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Tubs.hh>
Public Member Functions
G4Tubs (const G4String &pName, G4double pRMin, G4double pRMax, G4double pDz, G4double pSPhi, G4double pDPhi)
virtual ~G4Tubs ()
G4double GetInnerRadius () const
G4double GetOuterRadius () const
G4double GetZHalfLength () const
G4double GetStartPhiAngle () const
G4double GetDeltaPhiAngle () const
G4double GetSinStartPhi () const
G4double GetCosStartPhi () const
G4double GetSinEndPhi () const
G4double GetCosEndPhi () const
void SetInnerRadius (G4double newRMin)
void SetOuterRadius (G4double newRMax)
void SetZHalfLength (G4double newDz)
void SetStartPhiAngle (G4double newSPhi, G4bool trig=true)
void SetDeltaPhiAngle (G4double newDPhi)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pmin, G4double &pmax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Tubs (__void__ &)
G4Tubs (const G4Tubs &rhs)
G4Tubs & operator= (const G4Tubs &rhs)
G4double GetRMin () const
G4double GetRMax () const
G4double GetDz () const
G4double GetSPhi () const
G4double GetDPhi () const
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual G4VisExtent GetExtent () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Types
enum ESide {
kNull, kRMin, kRMax, kSPhi,
kEPhi, kPZ, kMZ
}
enum ENorm {
kNRMin, kNRMax, kNSPhi, kNEPhi,
kNZ
}
Protected Member Functions
void Initialize ()
void CheckSPhiAngle (G4double sPhi)
void CheckDPhiAngle (G4double dPhi)
void CheckPhiAngles (G4double sPhi, G4double dPhi)
void InitializeTrigonometry ()
G4double FastInverseRxy (const G4ThreeVector &pos, G4double invRad, G4double normalTolerance) const
virtual G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes
G4double kRadTolerance
G4double kAngTolerance
G4double fRMin
G4double fRMax
G4double fDz
G4double fSPhi
G4double fDPhi
G4double sinCPhi
G4double cosCPhi
G4double cosHDPhi
G4double cosHDPhiOT
G4double cosHDPhiIT
G4double sinSPhi
G4double cosSPhi
G4double sinEPhi
G4double cosEPhi
G4bool fPhiFullTube
G4double fInvRmax
G4double fInvRmin
G4double halfCarTolerance
G4double halfRadTolerance
G4double halfAngTolerance
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Static Protected Attributes
static constexpr G4double kNormTolerance = 1.0e-6
Detailed Description
Definition at line 74 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 74 of file G4Tubs.hh
Member Enumeration Documentation
enum G4Tubs::ENorm protected
Enumerator:
kNRMin
kNRMax
kNSPhi
kNEPhi
kNZ
Definition at line 208 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 208 of file G4Tubs.hh
enum G4Tubs::ESide protected
Enumerator:
kNull
kRMin
kRMax
kSPhi
kEPhi
kPZ
kMZ
Definition at line 204 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 204 of file G4Tubs.hh
Constructor & Destructor Documentation
G4Tubs::G4Tubs (const G4String & pName, G4double pRMin, G4double pRMax, G4double pDz, G4double pSPhi, G4double pDPhi)
Definition at line 60 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 60 of file G4Tubs.cc
References CheckPhiAngles(), FatalException, G4endl, G4Exception(), G4GeometryTolerance::GetAngularTolerance(), G4GeometryTolerance::GetInstance(), G4VSolid::GetName(), G4GeometryTolerance::GetRadialTolerance(), halfAngTolerance, halfCarTolerance, halfRadTolerance, kAngTolerance, G4VSolid::kCarTolerance, kRadTolerance, and message().
Referenced by Clone().
G4Tubs::~G4Tubs () virtual
Definition at line 116 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 116 of file G4Tubs.cc
G4Tubs::G4Tubs (__void__ & a)
Definition at line 101 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 101 of file G4Tubs.cc
G4Tubs::G4Tubs (const G4Tubs & rhs)
Definition at line 124 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 124 of file G4Tubs.cc
Member Function Documentation
G4ThreeVector G4Tubs::ApproxSurfaceNormal (const G4ThreeVector & p) const protected virtual
Definition at line 600 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 600 of file G4Tubs.cc
References cosEPhi, cosSPhi, G4VSolid::DumpInfo(), fDPhi, fDz, fPhiFullTube, fRMax, fRMin, fSPhi, G4Exception(), JustWarning, kNEPhi, kNRMax, kNRMin, kNSPhi, kNZ, norm, phi, sinEPhi, sinSPhi, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SurfaceNormal().
void G4Tubs::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 189 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 189 of file G4Tubs.cc
References G4GeomTools::DiskExtent(), G4VSolid::DumpInfo(), dz, G4Exception(), GetCosEndPhi(), GetCosStartPhi(), GetDeltaPhiAngle(), GetInnerRadius(), G4VSolid::GetName(), GetOuterRadius(), GetSinEndPhi(), GetSinStartPhi(), GetZHalfLength(), JustWarning, message(), pMax, rmax(), CLHEP::Hep3Vector::set(), twopi, CLHEP::Hep2Vector::x(), CLHEP::Hep3Vector::x(), CLHEP::Hep2Vector::y(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4Tubs::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pmin, G4double & pmax) const virtual
Implements G4VSolid.
Definition at line 232 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 232 of file G4Tubs.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), deg, dz, GetCosEndPhi(), GetCosStartPhi(), GetDeltaPhiAngle(), GetInnerRadius(), GetOuterRadius(), GetSinEndPhi(), GetSinStartPhi(), GetZHalfLength(), k, pMax, rmax(), and twopi.
void G4Tubs::CheckDPhiAngle (G4double dPhi) inline protected
void G4Tubs::CheckPhiAngles (G4double sPhi, G4double dPhi) inline protected
Referenced by G4Tubs().
void G4Tubs::CheckSPhiAngle (G4double sPhi) inline protected
G4VSolid * G4Tubs::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 1643 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1643 of file G4Tubs.cc
References G4Tubs().
void G4Tubs::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 178 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 178 of file G4Tubs.cc
References G4VPVParameterisation::ComputeDimensions().
G4Polyhedron * G4Tubs::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 1750 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1750 of file G4Tubs.cc
References fDPhi, fDz, fRMax, fRMin, and fSPhi.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and G4ArrowModel::G4ArrowModel().
void G4Tubs::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 1745 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1745 of file G4Tubs.cc
References G4VGraphicsScene::AddSolid().
G4double G4Tubs::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 732 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 732 of file G4Tubs.cc
References b, c, cosCPhi, cosEPhi, cosHDPhiIT, cosSPhi, d, fDz, fInvRmin, fPhiFullTube, fRMax, fRMin, halfCarTolerance, halfRadTolerance, kInfinity, kRadTolerance, sinCPhi, sinEPhi, sinSPhi, t1, t2, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Tubs::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1108 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1108 of file G4Tubs.cc
References cosCPhi, cosEPhi, cosHDPhi, cosSPhi, fDz, fPhiFullTube, fRMax, fRMin, sinCPhi, sinEPhi, sinSPhi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Tubs::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 1152 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1152 of file G4Tubs.cc
References b, c, cosCPhi, cosEPhi, cosSPhi, d2, deltaR(), G4VSolid::DumpInfo(), false, FastInverseRxy(), fDPhi, fDz, fInvRmax, fPhiFullTube, fRMax, fRMin, fSPhi, G4cout, G4endl, G4Exception(), halfAngTolerance, halfCarTolerance, JustWarning, G4VSolid::kCarTolerance, kEPhi, kInfinity, kMZ, kNormTolerance, kNull, kPZ, kRadTolerance, kRMax, kRMin, kSPhi, message(), mm, pi, sinCPhi, sinEPhi, sinSPhi, t1, t2, true, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Tubs::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 1574 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1574 of file G4Tubs.cc
References cosCPhi, cosEPhi, cosSPhi, G4VSolid::DumpInfo(), fDz, fPhiFullTube, fRMax, fRMin, G4cout, G4endl, G4Exception(), Inside(), JustWarning, kOutside, mm, sinCPhi, sinEPhi, sinSPhi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Tubs::FastInverseRxy (const G4ThreeVector & pos, G4double invRad, G4double normalTolerance) const inline protected
Referenced by DistanceToOut().
G4double G4Tubs::GetCosEndPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Tubs::GetCosStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Tubs::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
Referenced by STCyclotronDetectorConstruction::Construct().
G4double G4Tubs::GetDeltaPhiAngle () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), G4ParameterisationTubsPhi::G4ParameterisationTubsPhi(), G4ParameterisationTubsPhi::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteSolids::TubeWrite(), and G4GDMLWriteSolids::TubeWrite().
G4double G4Tubs::GetDPhi () const inline
Referenced by export_G4Tubs().
G4double G4Tubs::GetDz () const inline
Referenced by export_G4Tubs().
G4GeometryType G4Tubs::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 1634 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1634 of file G4Tubs.cc
G4double G4Tubs::GetInnerRadius () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), G4ParameterisationTubsRho::G4ParameterisationTubsRho(), G4ParameterisationTubsRho::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteSolids::TubeWrite(), and G4GDMLWriteSolids::TubeWrite().
G4double G4Tubs::GetOuterRadius () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), G4ParameterisationTubsRho::G4ParameterisationTubsRho(), FFPrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationTubsRho::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteSolids::TubeWrite(), and G4GDMLWriteSolids::TubeWrite().
G4ThreeVector G4Tubs::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 1675 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1675 of file G4Tubs.cc
References cosEPhi, cosSPhi, fDPhi, fDz, fRMax, fRMin, fSPhi, G4CSGSolid::GetRadiusInRing(), phi, G4INCL::DeJongSpin::shoot(), sinEPhi, sinSPhi, and twopi.
G4double G4Tubs::GetRMax () const inline
Referenced by export_G4Tubs().
G4double G4Tubs::GetRMin () const inline
Referenced by export_G4Tubs().
G4double G4Tubs::GetSinEndPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Tubs::GetSinStartPhi () const inline
Referenced by BoundingLimits(), and CalculateExtent().
G4double G4Tubs::GetSPhi () const inline
Referenced by export_G4Tubs().
G4double G4Tubs::GetStartPhiAngle () const inline
Referenced by G4tgbVolume::BuildSolidForDivision(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), G4tgbGeometryDumper::GetSolidParams(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteSolids::TubeWrite(), and G4GDMLWriteSolids::TubeWrite().
G4double G4Tubs::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
G4double G4Tubs::GetZHalfLength () const inline
Referenced by G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), CalculateExtent(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeTransformation(), UltraDetectorConstruction::ConstructUVscope(), export_G4Tubs(), G4ParameterisationTubsZ::G4ParameterisationTubsZ(), FFPrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationTubsZ::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteParamvol::Tube_dimensionsWrite(), PHG4GDMLWriteSolids::TubeWrite(), and G4GDMLWriteSolids::TubeWrite().
void G4Tubs::Initialize () inline protected
void G4Tubs::InitializeTrigonometry () inline protected
EInside G4Tubs::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 342 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 342 of file G4Tubs.cc
References fDPhi, fDz, fPhiFullTube, fRMax, fRMin, fSPhi, halfAngTolerance, halfCarTolerance, halfRadTolerance, in, kInside, kOutside, kSurface, r2, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToOut().
G4Tubs & G4Tubs::operator= (const G4Tubs & rhs)
Definition at line 144 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 144 of file G4Tubs.cc
References cosCPhi, cosEPhi, cosHDPhi, cosHDPhiIT, cosHDPhiOT, cosSPhi, fDPhi, fDz, fInvRmax, fInvRmin, fPhiFullTube, fRMax, fRMin, fSPhi, halfAngTolerance, halfCarTolerance, halfRadTolerance, kAngTolerance, kRadTolerance, G4CSGSolid::operator=(), sinCPhi, sinEPhi, and sinSPhi.
void G4Tubs::SetDeltaPhiAngle (G4double newDPhi) inline
Referenced by PHG4EtaParameterization::ComputeDimensions(), PHG4EtaPhiParameterization::ComputeDimensions(), ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), and export_G4Tubs().
void G4Tubs::SetInnerRadius (G4double newRMin) inline
Referenced by PHG4EtaParameterization::ComputeDimensions(), PHG4EtaPhiParameterization::ComputeDimensions(), ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), and export_G4Tubs().
void G4Tubs::SetOuterRadius (G4double newRMax) inline
Referenced by PHG4EtaParameterization::ComputeDimensions(), PHG4EtaPhiParameterization::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), ExN04CalorimeterParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), STCyclotronDetectorConstruction::SetTargetDiameter(), and DetectorConstruction::UpdateParameters().
void G4Tubs::SetStartPhiAngle (G4double newSPhi, G4bool trig = true) inline
Referenced by PHG4EtaParameterization::ComputeDimensions(), PHG4EtaPhiParameterization::ComputeDimensions(), ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), and export_G4Tubs().
void G4Tubs::SetZHalfLength (G4double newDz) inline
Referenced by PHG4EtaParameterization::ComputeDimensions(), PHG4EtaPhiParameterization::ComputeDimensions(), ExN04CalorimeterParametrisation::ComputeDimensions(), ExN04TrackerParametrisation::ComputeDimensions(), RE01CalorimeterParametrisation::ComputeDimensions(), RE05TrackerParametrisation::ComputeDimensions(), RE01TrackerParametrisation::ComputeDimensions(), RE05CalorimeterParametrisation::ComputeDimensions(), B2bChamberParameterisation::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), NeuronLoadDataFile::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), export_G4Tubs(), STCyclotronDetectorConstruction::SetFoilThickness(), ElectronBenchmarkDetector::SetPrimFoilThickness(), STCyclotronDetectorConstruction::SetTargetThickness(), and DetectorConstruction::UpdateParameters().
std::ostream & G4Tubs::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 1652 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 1652 of file G4Tubs.cc
References degree, fDPhi, fDz, fRMax, fRMin, fSPhi, G4VSolid::GetName(), and mm.
G4ThreeVector G4Tubs::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 509 of file G4Tubs.cc.
View newest version in sPHENIX GitHub at line 509 of file G4Tubs.cc
References ApproxSurfaceNormal(), cosEPhi, cosSPhi, fDPhi, fDz, fPhiFullTube, fRMax, fRMin, fSPhi, G4cout, G4endl, G4Exception(), halfAngTolerance, halfCarTolerance, JustWarning, kInfinity, norm, sinEPhi, sinSPhi, twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4Tubs::cosCPhi protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4Tubs::cosEPhi protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Tubs::cosHDPhi protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by DistanceToIn(), and operator=().
G4double G4Tubs::cosHDPhiIT protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by DistanceToIn(), and operator=().
G4double G4Tubs::cosHDPhiOT protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by operator=().
G4double G4Tubs::cosSPhi protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Tubs::fDPhi protected
Definition at line 219 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 219 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Tubs::fDz protected
Definition at line 219 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 219 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Tubs::fInvRmax protected
Definition at line 232 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 232 of file G4Tubs.hh
Referenced by DistanceToOut(), and operator=().
G4double G4Tubs::fInvRmin protected
Definition at line 232 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 232 of file G4Tubs.hh
Referenced by DistanceToIn(), and operator=().
G4bool G4Tubs::fPhiFullTube protected
Definition at line 228 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 228 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4Tubs::fRMax protected
Definition at line 219 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 219 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Tubs::fRMin protected
Definition at line 219 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 219 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Tubs::fSPhi protected
Definition at line 219 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 219 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4Tubs::halfAngTolerance protected
Definition at line 236 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 236 of file G4Tubs.hh
Referenced by DistanceToOut(), G4Tubs(), Inside(), operator=(), and SurfaceNormal().
G4double G4Tubs::halfCarTolerance protected
Definition at line 236 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 236 of file G4Tubs.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Tubs(), Inside(), operator=(), and SurfaceNormal().
G4double G4Tubs::halfRadTolerance protected
Definition at line 236 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 236 of file G4Tubs.hh
Referenced by DistanceToIn(), G4Tubs(), Inside(), and operator=().
G4double G4Tubs::kAngTolerance protected
Definition at line 210 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 210 of file G4Tubs.hh
Referenced by G4Tubs(), and operator=().
constexpr G4double G4Tubs::kNormTolerance = 1.0e-6 static protected
Definition at line 214 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 214 of file G4Tubs.hh
Referenced by DistanceToOut().
G4double G4Tubs::kRadTolerance protected
Definition at line 210 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 210 of file G4Tubs.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Tubs(), and operator=().
G4double G4Tubs::sinCPhi protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by DistanceToIn(), DistanceToOut(), and operator=().
G4double G4Tubs::sinEPhi protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
G4double G4Tubs::sinSPhi protected
Definition at line 223 of file G4Tubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Tubs.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Tubs.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/src/G4Tubs.cc