ECCE @ EIC Software: G4TritonPHPBuilder Class Reference
G4TritonPHPBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4TritonPHPBuilder.hh>
Public Member Functions
G4TritonPHPBuilder ()
virtual ~G4TritonPHPBuilder ()
virtual void Build (G4TritonInelasticProcess *aP) finaloverride
virtual void Build (G4HadronElasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VTritonBuilder
G4VTritonBuilder ()=default
virtual ~G4VTritonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4double theMin
G4double theMax
G4ParticleHPInelastic * theParticlePHPModel
Detailed Description
Definition at line 49 of file G4TritonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 49 of file G4TritonPHPBuilder.hh
Constructor & Destructor Documentation
G4TritonPHPBuilder::G4TritonPHPBuilder ()
Definition at line 34 of file G4TritonPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 34 of file G4TritonPHPBuilder.cc
References MeV, theMax, theMin, and theParticlePHPModel.
virtual G4TritonPHPBuilder::~G4TritonPHPBuilder () inline virtual
Definition at line 53 of file G4TritonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 53 of file G4TritonPHPBuilder.hh
Member Function Documentation
void G4TritonPHPBuilder::Build (G4TritonInelasticProcess * aP) final override virtual
Implements G4VTritonBuilder.
Definition at line 48 of file G4TritonPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4TritonPHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4HadronicInteraction::SetMinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), theMax, theMin, theParticlePHPModel, and G4Triton::Triton().
void G4TritonPHPBuilder::Build (G4HadronElasticProcess * aP) final override virtual
Implements G4VTritonBuilder.
Definition at line 42 of file G4TritonPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 42 of file G4TritonPHPBuilder.cc
References G4cout, and G4endl.
virtual void G4TritonPHPBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 63 of file G4TritonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4TritonPHPBuilder.hh
References theMax.
virtual void G4TritonPHPBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 59 of file G4TritonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4TritonPHPBuilder.hh
References theMin.
Member Data Documentation
G4double G4TritonPHPBuilder::theMax private
Definition at line 72 of file G4TritonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4TritonPHPBuilder.hh
Referenced by Build(), G4TritonPHPBuilder(), and SetMaxEnergy().
G4double G4TritonPHPBuilder::theMin private
Definition at line 71 of file G4TritonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4TritonPHPBuilder.hh
Referenced by Build(), G4TritonPHPBuilder(), and SetMinEnergy().
G4ParticleHPInelastic* G4TritonPHPBuilder::theParticlePHPModel private
Definition at line 73 of file G4TritonPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4TritonPHPBuilder.hh
Referenced by Build(), and G4TritonPHPBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4TritonPHPBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4TritonPHPBuilder.cc