ECCE @ EIC Software: G4StatMFMicroCanonical Class Reference
G4StatMFMicroCanonical Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMicroCanonical.hh>
Classes
struct DeleteFragment
Public Types
enum { MaxAllowedMultiplicity = 4 }
Public Member Functions
G4StatMFMicroCanonical (const G4Fragment &theFragment)
~G4StatMFMicroCanonical ()
G4StatMFChannel * ChooseAandZ (const G4Fragment &theFragment)
Public Member Functions inherited from G4VStatMFEnsemble
G4VStatMFEnsemble ()
virtual ~G4VStatMFEnsemble ()
G4double GetMeanMultiplicity (void) const
G4double GetMeanTemperature (void) const
Private Member Functions
G4StatMFMicroCanonical ()
G4StatMFMicroCanonical (const G4StatMFMicroCanonical &right)
G4StatMFMicroCanonical & operator= (const G4StatMFMicroCanonical &right)
G4bool operator== (const G4StatMFMicroCanonical &right) const
G4bool operator!= (const G4StatMFMicroCanonical &right) const
void Initialize (const G4Fragment &theFragment)
G4double CalcEntropyOfCompoundNucleus (const G4Fragment &theFragment, G4double &TConf)
G4double CalcFreeInternalEnergy (const G4Fragment &theFragment, G4double T)
G4double CalcInvLevelDensity (G4int anA)
Private Attributes
std::vector
< G4StatMFMicroManager * > _ThePartitionManagerVector
G4double _WCompoundNucleus
Additional Inherited Members
Protected Attributes inherited from G4VStatMFEnsemble
G4double __FreeInternalE0
G4double __MeanTemperature
G4double __MeanEntropy
G4double __MeanMultiplicity
Detailed Description
Definition at line 46 of file G4StatMFMicroCanonical.hh.
View newest version in sPHENIX GitHub at line 46 of file G4StatMFMicroCanonical.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
MaxAllowedMultiplicity
Definition at line 76 of file G4StatMFMicroCanonical.hh.
View newest version in sPHENIX GitHub at line 76 of file G4StatMFMicroCanonical.hh
Constructor & Destructor Documentation
G4StatMFMicroCanonical::G4StatMFMicroCanonical (const G4Fragment & theFragment)
Definition at line 40 of file G4StatMFMicroCanonical.cc.
View newest version in sPHENIX GitHub at line 40 of file G4StatMFMicroCanonical.cc
References Initialize().
G4StatMFMicroCanonical::~G4StatMFMicroCanonical ()
Definition at line 47 of file G4StatMFMicroCanonical.cc.
View newest version in sPHENIX GitHub at line 47 of file G4StatMFMicroCanonical.cc
References _ThePartitionManagerVector.
G4StatMFMicroCanonical::G4StatMFMicroCanonical () inline private
Definition at line 58 of file G4StatMFMicroCanonical.hh.
View newest version in sPHENIX GitHub at line 58 of file G4StatMFMicroCanonical.hh
G4StatMFMicroCanonical::G4StatMFMicroCanonical (const G4StatMFMicroCanonical & right) private
Member Function Documentation
G4double G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus (const G4Fragment & theFragment, G4double & TConf) private
Definition at line 170 of file G4StatMFMicroCanonical.cc.
View newest version in sPHENIX GitHub at line 170 of file G4StatMFMicroCanonical.cc
References G4VStatMFEnsemble::__FreeInternalE0, A(), A13, kdfinder::abs(), CalcFreeInternalEnergy(), CalcInvLevelDensity(), G4StatMFParameters::DBetaDT(), eps, G4cout, G4endl, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4Pow::GetInstance(), max, MeV, and G4Pow::Z13().
Referenced by Initialize().
G4double G4StatMFMicroCanonical::CalcFreeInternalEnergy (const G4Fragment & theFragment, G4double T) private
Definition at line 146 of file G4StatMFMicroCanonical.cc.
View newest version in sPHENIX GitHub at line 146 of file G4StatMFMicroCanonical.cc
References A(), A13, G4StatMFParameters::Beta(), G4StatMFParameters::DBetaDT(), source.hepunit::elm_coupling, G4Fragment::GetA_asInt(), G4StatMFParameters::GetE0(), G4StatMFParameters::GetEpsilon0(), G4StatMFParameters::GetGamma0(), G4Pow::GetInstance(), G4StatMFParameters::Getr0(), G4Fragment::GetZ_asInt(), Z, and G4Pow::Z13().
Referenced by CalcEntropyOfCompoundNucleus().
G4double G4StatMFMicroCanonical::CalcInvLevelDensity (G4int anA) private
Definition at line 265 of file G4StatMFMicroCanonical.cc.
View newest version in sPHENIX GitHub at line 265 of file G4StatMFMicroCanonical.cc
References G4StatMFParameters::GetEpsilon0().
Referenced by CalcEntropyOfCompoundNucleus().
G4StatMFChannel * G4StatMFMicroCanonical::ChooseAandZ (const G4Fragment & theFragment) virtual
Implements G4VStatMFEnsemble.
Definition at line 237 of file G4StatMFMicroCanonical.cc.
View newest version in sPHENIX GitHub at line 237 of file G4StatMFMicroCanonical.cc
References G4VStatMFEnsemble::__MeanTemperature, _ThePartitionManagerVector, _WCompoundNucleus, G4StatMFChannel::CreateFragment(), G4UniformRand, G4Fragment::GetA_asInt(), G4Fragment::GetZ_asInt(), and it.
void G4StatMFMicroCanonical::Initialize (const G4Fragment & theFragment) private
Definition at line 57 of file G4StatMFMicroCanonical.cc.
View newest version in sPHENIX GitHub at line 57 of file G4StatMFMicroCanonical.cc
References G4VStatMFEnsemble::__FreeInternalE0, G4VStatMFEnsemble::__MeanEntropy, G4VStatMFEnsemble::__MeanMultiplicity, G4VStatMFEnsemble::__MeanTemperature, _ThePartitionManagerVector, _WCompoundNucleus, A(), CalcEntropyOfCompoundNucleus(), source.hepunit::elm_coupling, G4Fragment::GetA_asInt(), G4StatMFParameters::GetBeta0(), G4StatMFParameters::GetE0(), G4Fragment::GetExcitationEnergy(), G4StatMFParameters::GetGamma0(), G4Pow::GetInstance(), G4StatMFParameters::Getr0(), G4Fragment::GetZ_asInt(), it, MaxAllowedMultiplicity, x, Z, G4Pow::Z13(), and G4Pow::Z23().
Referenced by G4StatMFMicroCanonical().
G4bool G4StatMFMicroCanonical::operator!= (const G4StatMFMicroCanonical & right) const private
G4StatMFMicroCanonical& G4StatMFMicroCanonical::operator= (const G4StatMFMicroCanonical & right) private
G4bool G4StatMFMicroCanonical::operator== (const G4StatMFMicroCanonical & right) const private
Member Data Documentation
std::vector<G4StatMFMicroManager*> G4StatMFMicroCanonical::_ThePartitionManagerVector private
Definition at line 97 of file G4StatMFMicroCanonical.hh.
View newest version in sPHENIX GitHub at line 97 of file G4StatMFMicroCanonical.hh
Referenced by ChooseAandZ(), Initialize(), and ~G4StatMFMicroCanonical().
G4double G4StatMFMicroCanonical::_WCompoundNucleus private
Definition at line 100 of file G4StatMFMicroCanonical.hh.
View newest version in sPHENIX GitHub at line 100 of file G4StatMFMicroCanonical.hh
Referenced by ChooseAandZ(), and Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMicroCanonical.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMicroCanonical.cc