ECCE @ EIC Software: G4FTFPProtonBuilder Class Reference
G4FTFPProtonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPProtonBuilder.hh>
Public Member Functions
G4FTFPProtonBuilder (G4bool quasiElastic=false)
virtual ~G4FTFPProtonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4ProtonInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VProtonBuilder
G4VProtonBuilder ()=default
virtual ~G4VProtonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4FTFModel * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4LundStringFragmentation * theLund
G4double theMin
G4double theMax
Detailed Description
Definition at line 56 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4FTFPProtonBuilder.hh
Constructor & Destructor Documentation
G4FTFPProtonBuilder::G4FTFPProtonBuilder (G4bool quasiElastic = false)
Definition at line 50 of file G4FTFPProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 50 of file G4FTFPProtonBuilder.cc
References G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theLund, theMax, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4FTFPProtonBuilder::~G4FTFPProtonBuilder () virtual
Definition at line 86 of file G4FTFPProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 86 of file G4FTFPProtonBuilder.cc
References theLund, theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4FTFPProtonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VProtonBuilder.
Definition at line 63 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4FTFPProtonBuilder.hh
void G4FTFPProtonBuilder::Build (G4ProtonInelasticProcess * aP) final override virtual
Implements G4VProtonBuilder.
Definition at line 76 of file G4FTFPProtonBuilder.cc.
View newest version in sPHENIX GitHub at line 76 of file G4FTFPProtonBuilder.cc
References G4HadronicProcess::AddDataSet(), G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4FTFPProtonBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 67 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4FTFPProtonBuilder.hh
References theMax.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels(), and G4HadronPhysicsQGSP_BIC_HP::CreateModels().
virtual void G4FTFPProtonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 66 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4FTFPProtonBuilder.hh
References theMin.
Referenced by G4HadronPhysicsQGSP_BIC_AllHP::CreateModels(), and G4HadronPhysicsQGSP_BIC_HP::CreateModels().
Member Data Documentation
G4GeneratorPrecompoundInterface* G4FTFPProtonBuilder::theCascade private
Definition at line 73 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FTFPProtonBuilder.hh
Referenced by G4FTFPProtonBuilder().
G4LundStringFragmentation* G4FTFPProtonBuilder::theLund private
Definition at line 77 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FTFPProtonBuilder.hh
Referenced by G4FTFPProtonBuilder(), and ~G4FTFPProtonBuilder().
G4double G4FTFPProtonBuilder::theMax private
Definition at line 79 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FTFPProtonBuilder.hh
Referenced by Build(), G4FTFPProtonBuilder(), and SetMaxEnergy().
G4double G4FTFPProtonBuilder::theMin private
Definition at line 78 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FTFPProtonBuilder.hh
Referenced by Build(), G4FTFPProtonBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4FTFPProtonBuilder::theModel private
Definition at line 72 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4FTFPProtonBuilder.hh
Referenced by Build(), and G4FTFPProtonBuilder().
G4QuasiElasticChannel* G4FTFPProtonBuilder::theQuasiElastic private
Definition at line 76 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FTFPProtonBuilder.hh
Referenced by G4FTFPProtonBuilder(), and ~G4FTFPProtonBuilder().
G4ExcitedStringDecay* G4FTFPProtonBuilder::theStringDecay private
Definition at line 75 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FTFPProtonBuilder.hh
Referenced by G4FTFPProtonBuilder(), and ~G4FTFPProtonBuilder().
G4FTFModel* G4FTFPProtonBuilder::theStringModel private
Definition at line 74 of file G4FTFPProtonBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FTFPProtonBuilder.hh
Referenced by G4FTFPProtonBuilder(), and ~G4FTFPProtonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4FTFPProtonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4FTFPProtonBuilder.cc