ECCE @ EIC Software: G4PolarizedGammaConversion Class Reference
G4PolarizedGammaConversion Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedGammaConversion.hh>
Public Member Functions
G4PolarizedGammaConversion (const G4String &processName="pol-conv", G4ProcessType type=fElectromagnetic)
virtual ~G4PolarizedGammaConversion ()
G4bool IsApplicable (const G4ParticleDefinition &) override
virtual void PrintInfo () override
Public Member Functions inherited from G4VEmProcess
G4VEmProcess (const G4String &name, G4ProcessType type=fElectromagnetic)
virtual ~G4VEmProcess ()
virtual void ProcessDescription (std::ostream &outFile) const override
virtual void PreparePhysicsTable (const G4ParticleDefinition &) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
virtual void StartTracking (G4Track *) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
virtual G4VEmProcess * GetEmProcess (const G4String &name)
G4double CrossSectionPerVolume (G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double ComputeCrossSectionPerAtom (G4double kineticEnergy, G4double Z, G4double A=0., G4double cut=0.0)
G4double MeanFreePath (const G4Track &track)
G4double GetLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple)
G4double GetLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple, G4double logKinEnergy)
void SetLambdaBinning (G4int nbins)
void SetMinKinEnergy (G4double e)
void SetMinKinEnergyPrim (G4double e)
void SetMaxKinEnergy (G4double e)
G4PhysicsTable * LambdaTable () const
G4PhysicsTable * LambdaTablePrim () const
const G4ParticleDefinition * Particle () const
const G4ParticleDefinition * SecondaryParticle () const
G4VEmModel * SelectModelForMaterial (G4double kinEnergy, size_t idxRegion) const
void AddEmModel (G4int, G4VEmModel *, const G4Region *region=nullptr)
void SetEmModel (G4VEmModel *, G4int index=0)
G4VEmModel * EmModel (size_t index=0) const
void UpdateEmModel (const G4String &, G4double, G4double)
G4int GetNumberOfModels () const
G4int GetNumberOfRegionModels (size_t couple_index) const
G4VEmModel * GetRegionModel (G4int idx, size_t couple_index) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
const G4VEmModel * GetCurrentModel () const
const G4Element * GetCurrentElement () const
void SetCrossSectionBiasingFactor (G4double f, G4bool flag=true)
G4double CrossSectionBiasingFactor () const
void ActivateForcedInteraction (G4double length=0.0, const G4String &r="", G4bool flag=true)
void ActivateSecondaryBiasing (const G4String &region, G4double factor, G4double energyLimit)
void SetEmMasterProcess (const G4VEmProcess *)
void SetIntegral (G4bool val)
void SetBuildTableFlag (G4bool val)
void CurrentSetup (const G4MaterialCutsCouple *, G4double energy)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void InitialiseProcess (const G4ParticleDefinition *) override
Protected Member Functions inherited from G4VEmProcess
virtual void StreamProcessInfo (std::ostream &) const
virtual G4double MinPrimaryEnergy (const G4ParticleDefinition *, const G4Material *)
G4VEmModel * SelectModel (G4double kinEnergy, size_t index)
virtual G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
G4PhysicsVector * LambdaPhysicsVector (const G4MaterialCutsCouple *)
G4int LambdaBinning () const
G4double MinKinEnergy () const
G4double MaxKinEnergy () const
G4double PolarAngleLimit () const
G4bool IsIntegral () const
G4double RecalculateLambda (G4double kinEnergy, const G4MaterialCutsCouple *couple)
G4ParticleChangeForGamma * GetParticleChange ()
void SetParticle (const G4ParticleDefinition *p)
void SetSecondaryParticle (const G4ParticleDefinition *p)
size_t CurrentMaterialCutsCoupleIndex () const
const G4MaterialCutsCouple * MaterialCutsCouple () const
G4bool ApplyCuts () const
G4double GetGammaEnergyCut ()
G4double GetElectronEnergyCut ()
void SetStartFromNullFlag (G4bool val)
void SetSplineFlag (G4bool val)
const G4Element * GetTargetElement () const
const G4Isotope * GetTargetIsotope () const
Private Member Functions
G4PolarizedGammaConversion & operator= (const G4PolarizedGammaConversion &right)=delete
G4PolarizedGammaConversion (const G4PolarizedGammaConversion &)=delete
Private Attributes
G4bool isInitialised
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VEmProcess
G4LossTableManager * lManager
G4EmParameters * theParameters
G4EmBiasingManager * biasManager
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theElectron
G4ParticleChangeForGamma fParticleChange
std::vector< G4DynamicParticle * > secParticles
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t currentCoupleIndex
size_t basedCoupleIndex
G4int mainSecondaries
G4int secID
G4int fluoID
G4int augerID
G4int biasID
G4bool isTheMaster
G4double mfpKinEnergy
G4double preStepKinEnergy
G4double preStepLogKinEnergy
G4double preStepLambda
Detailed Description
Definition at line 61 of file G4PolarizedGammaConversion.hh.
View newest version in sPHENIX GitHub at line 61 of file G4PolarizedGammaConversion.hh
Constructor & Destructor Documentation
G4PolarizedGammaConversion::G4PolarizedGammaConversion (const G4String & processName = "pol-conv", G4ProcessType type = fElectromagnetic) explicit
Definition at line 51 of file G4PolarizedGammaConversion.cc.
View newest version in sPHENIX GitHub at line 51 of file G4PolarizedGammaConversion.cc
References G4Electron::Electron(), source.hepunit::electron_mass_c2, fGammaConversion, G4VEmProcess::SetBuildTableFlag(), G4VEmProcess::SetLambdaBinning(), G4VEmProcess::SetMinKinEnergy(), G4VProcess::SetProcessSubType(), and G4VEmProcess::SetSecondaryParticle().
G4PolarizedGammaConversion::~G4PolarizedGammaConversion () virtual
Definition at line 65 of file G4PolarizedGammaConversion.cc.
View newest version in sPHENIX GitHub at line 65 of file G4PolarizedGammaConversion.cc
G4PolarizedGammaConversion::G4PolarizedGammaConversion (const G4PolarizedGammaConversion &) private delete
Member Function Documentation
void G4PolarizedGammaConversion::InitialiseProcess (const G4ParticleDefinition *) override protected virtual
Implements G4VEmProcess.
Definition at line 77 of file G4PolarizedGammaConversion.cc.
View newest version in sPHENIX GitHub at line 77 of file G4PolarizedGammaConversion.cc
References G4VEmProcess::AddEmModel(), source.hepunit::electron_mass_c2, emax, CEMC_TOWER::emin, G4VEmProcess::EmModel(), G4EmParameters::Instance(), isInitialised, max, G4EmParameters::MaxKinEnergy(), G4EmParameters::MinKinEnergy(), G4VEmProcess::SetEmModel(), G4VEmModel::SetHighEnergyLimit(), and G4VEmModel::SetLowEnergyLimit().
G4bool G4PolarizedGammaConversion::IsApplicable (const G4ParticleDefinition & p) override virtual
Implements G4VEmProcess.
Definition at line 70 of file G4PolarizedGammaConversion.cc.
View newest version in sPHENIX GitHub at line 70 of file G4PolarizedGammaConversion.cc
References G4Gamma::Gamma().
G4PolarizedGammaConversion& G4PolarizedGammaConversion::operator= (const G4PolarizedGammaConversion & right) private delete
void G4PolarizedGammaConversion::PrintInfo () override virtual
Reimplemented from G4VEmProcess.
Definition at line 93 of file G4PolarizedGammaConversion.cc.
View newest version in sPHENIX GitHub at line 93 of file G4PolarizedGammaConversion.cc
Member Data Documentation
G4bool G4PolarizedGammaConversion::isInitialised private
Definition at line 88 of file G4PolarizedGammaConversion.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PolarizedGammaConversion.hh
Referenced by InitialiseProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/include/G4PolarizedGammaConversion.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/polarisation/src/G4PolarizedGammaConversion.cc