ECCE @ EIC Software: G4INCL::ParticleTable Namespace Reference
G4INCL::ParticleTable Namespace Reference
Typedefs
typedef G4double(* NuclearMassFn)(const G4int, const G4int, const G4int)
typedef G4double(* ParticleMassFn)(const ParticleType)
typedef G4double(* SeparationEnergyFn)(const ParticleType, const G4int, const G4int)
typedef G4double(* FermiMomentumFn)(const G4int, const G4int)
Functions
void initialize (Config const *const theConfig=0)
Initialize the particle table.
G4int getIsospin (const ParticleType t)
Get the isospin of a particle.
std::string getName (const ParticleType t)
Get the native INCL name of the particle.
std::string getShortName (const ParticleType t)
Get the short INCL name of the particle.
std::string getName (const ParticleSpecies &s)
Get the native INCL name of the particle.
std::string getShortName (const ParticleSpecies &s)
Get the short INCL name of the particle.
std::string getName (const G4int A, const G4int Z)
Get the native INCL name of the ion.
std::string getShortName (const G4int A, const G4int Z)
Get the short INCL name of the ion.
G4double getINCLMass (const G4int A, const G4int Z, const G4int S)
Get INCL nuclear mass (in MeV/c^2)
G4double getINCLMass (const ParticleType t)
Get INCL particle mass (in MeV/c^2)
G4double getRealMass (const G4INCL::ParticleType t)
Get particle mass (in MeV/c^2)
G4double getRealMass (const G4int A, const G4int Z, const G4int S=0)
Get nuclear mass (in MeV/c^2)
G4double getTableQValue (const G4int A1, const G4int Z1, const G4int S1, const G4int A2, const G4int Z2, const G4int S2)
Get Q-value (in MeV/c^2)
G4double getTableQValue (const G4int A1, const G4int Z1, const G4int S1, const G4int A2, const G4int Z2, const G4int S2, const G4int A3, const G4int Z3, const G4int S3)
Get Q-value (in MeV/c^2)
G4double getTableSpeciesMass (const ParticleSpecies &p)
G4int getMassNumber (const ParticleType t)
Get mass number from particle type.
G4int getChargeNumber (const ParticleType t)
Get charge number from particle type.
G4int getStrangenessNumber (const ParticleType t)
Get strangeness number from particle type.
G4double getNuclearRadius (const ParticleType t, const G4int A, const G4int Z)
G4double getLargestNuclearRadius (const G4int A, const G4int Z)
G4double getRadiusParameter (const ParticleType t, const G4int A, const G4int Z)
G4double getMaximumNuclearRadius (const ParticleType t, const G4int A, const G4int Z)
G4double getSurfaceDiffuseness (const ParticleType t, const G4int A, const G4int Z)
G4double getMomentumRMS (const G4int A, const G4int Z)
Return the RMS of the momentum distribution (light clusters)
G4double getSeparationEnergyINCL (const ParticleType t, const G4int, const G4int)
Return INCL's default separation energy.
G4double getSeparationEnergyReal (const ParticleType t, const G4int A, const G4int Z)
Return the real separation energy.
G4double getSeparationEnergyRealForLight (const ParticleType t, const G4int A, const G4int Z)
Return the real separation energy only for light nuclei.
G4double getProtonSeparationEnergy ()
Getter for protonSeparationEnergy.
G4double getNeutronSeparationEnergy ()
Getter for neutronSeparationEnergy.
void setProtonSeparationEnergy (const G4double s)
Setter for protonSeparationEnergy.
void setNeutronSeparationEnergy (const G4double s)
Setter for protonSeparationEnergy.
std::string getElementName (const G4int Z)
Get the name of the element from the atomic number.
std::string getIUPACElementName (const G4int Z)
Get the name of an unnamed element from the IUPAC convention.
G4int parseElement (std::string pS)
Get the name of the element from the atomic number.
G4int parseIUPACElement (std::string const &pS)
Parse a IUPAC element name.
IsotopicDistribution const & getNaturalIsotopicDistribution (const G4int Z)
G4int drawRandomNaturalIsotope (const G4int Z)
G4double getFermiMomentumConstant (const G4int, const G4int)
Return the constant value of the Fermi momentum.
G4double getFermiMomentumConstantLight (const G4int A, const G4int Z)
Return the constant value of the Fermi momentum - special for light.
G4double getFermiMomentumMassDependent (const G4int A, const G4int)
Return the value Fermi momentum from a fit.
G4double getRPCorrelationCoefficient (const ParticleType t)
Get the value of the r-p correlation coefficient.
G4double getNeutronSkin ()
Get the thickness of the neutron skin.
G4double getNeutronHalo ()
Get the size of the neutron halo.
ParticleType getPionType (const G4int isosp)
Get the type of pion.
ParticleType getNucleonType (const G4int isosp)
Get the type of nucleon.
ParticleType getDeltaType (const G4int isosp)
Get the type of delta.
ParticleType getSigmaType (const G4int isosp)
Get the type of sigma.
ParticleType getKaonType (const G4int isosp)
Get the type of kaon.
ParticleType getAntiKaonType (const G4int isosp)
Get the type of antikaon.
G4double getWidth (const ParticleType t)
Get particle width (in s)
G4double getLambdaSeparationEnergy ()
void setLambdaSeparationEnergy (const G4double s)
Variables
const G4int maxClusterMass = 12
const G4int maxClusterCharge = 8
const G4int clusterTableZSize = maxClusterCharge+1
const G4int clusterTableASize = maxClusterMass+1
const G4int clusterTableSSize = 4
const G4double effectiveNucleonMass = 938.2796
const G4double effectiveNucleonMass2 = 8.8036860777616e5
const G4double effectiveDeltaMass = 1232.0
const G4double effectiveDeltaWidth = 130.0
const G4double effectivePionMass = 138.0
const G4double effectiveLambdaMass = 1115.683
const G4double effectiveSigmaMass = 1197.45
const G4double effectiveKaonMass = 497.614
const G4double effectiveAntiKaonMass = 497.614
const G4double effectiveEtaMass = 547.862
const G4double effectiveOmegaMass = 782.65
const G4double effectiveEtaPrimeMass = 957.78
const G4double effectivePhotonMass = 0.0
G4ThreadLocal G4double minDeltaMass = 0.
G4ThreadLocal G4double minDeltaMass2 = 0.
G4ThreadLocal G4double minDeltaMassRndm = 0.
G4ThreadLocal NuclearMassFn getTableMass = NULL
Static pointer to the mass function for nuclei.
G4ThreadLocal ParticleMassFn getTableParticleMass = NULL
Static pointer to the mass function for particles.
G4ThreadLocal SeparationEnergyFn getSeparationEnergy = NULL
Static pointer to the separation-energy function.
G4ThreadLocal FermiMomentumFn getFermiMomentum = NULL
Typedef Documentation
typedef G4double(* G4INCL::ParticleTable::FermiMomentumFn)(const G4int, const G4int)
Definition at line 231 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 231 of file G4INCLParticleTable.hh
typedef G4double(* G4INCL::ParticleTable::NuclearMassFn)(const G4int, const G4int, const G4int)
Definition at line 218 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 218 of file G4INCLParticleTable.hh
typedef G4double(* G4INCL::ParticleTable::ParticleMassFn)(const ParticleType)
Definition at line 219 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 219 of file G4INCLParticleTable.hh
typedef G4double(* G4INCL::ParticleTable::SeparationEnergyFn)(const ParticleType, const G4int, const G4int)
Definition at line 226 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 226 of file G4INCLParticleTable.hh
Function Documentation
G4int G4INCL::ParticleTable::drawRandomNaturalIsotope (const G4int Z)
Definition at line 1183 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1183 of file G4INCLParticleTable.cc
Referenced by G4INCL::INCL::prepareReaction().
ParticleType G4INCL::ParticleTable::getAntiKaonType (const G4int isosp)
Get the type of antikaon.
Definition at line 1288 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1288 of file G4INCLParticleTable.cc
References G4INCL::KMinus, and G4INCL::KZeroBar.
Referenced by G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), and G4INCL::NKbToNKb2piChannel::fillFinalState().
G4int G4INCL::ParticleTable::getChargeNumber (const ParticleType t)
Get charge number from particle type.
Definition at line 870 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 870 of file G4INCLParticleTable.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
ParticleType G4INCL::ParticleTable::getDeltaType (const G4int isosp)
Get the type of delta.
Definition at line 1248 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1248 of file G4INCLParticleTable.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, and G4INCL::DeltaZero.
Referenced by G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), and G4INCL::NDeltaToDeltaSKChannel::fillFinalState().
std::string G4INCL::ParticleTable::getElementName (const G4int Z)
Get the name of the element from the atomic number.
Definition at line 1134 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1134 of file G4INCLParticleTable.cc
References getIUPACElementName(), INCL_WARN, and Z.
Referenced by getName(), and getShortName().
G4double G4INCL::ParticleTable::getFermiMomentumConstant (const G4int , const G4int)
Return the constant value of the Fermi momentum.
Definition at line 1187 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1187 of file G4INCLParticleTable.cc
Referenced by getFermiMomentumConstantLight(), and initialize().
G4double G4INCL::ParticleTable::getFermiMomentumConstantLight (const G4int A, const G4int Z)
Return the constant value of the Fermi momentum - special for light.
This function should always return PhysicalConstants::Pf for heavy nuclei, and values from the momentumRMS table for light nuclei.
Parameters
A mass number
Z charge number
Definition at line 1191 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1191 of file G4INCLParticleTable.cc
References A(), clusterTableASize, clusterTableZSize, getFermiMomentumConstant(), G4INCL::Math::sqrtFiveThirds, and Z.
Referenced by initialize().
G4double G4INCL::ParticleTable::getFermiMomentumMassDependent (const G4int A, const G4int)
Return the value Fermi momentum from a fit.
This function returns a fitted Fermi momentum, based on data from Moniz et al., Phys. Rev. Lett. 26 (1971) 445. The fitted functional form is
with MeV/ , MeV/ and .
Parameters
A mass number
Definition at line 1200 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1200 of file G4INCLParticleTable.cc
Referenced by initialize().
G4double G4INCL::ParticleTable::getINCLMass (const G4int A, const G4int Z, const G4int S)
Get INCL nuclear mass (in MeV/c^2)
Definition at line 794 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 794 of file G4INCLParticleTable.cc
References kdfinder::abs(), G4INCL::Lambda, G4INCL::Neutron, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::Proton, and Z.
Referenced by G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::Particle::getEmissionQValueCorrection(), G4INCL::Particle::getINCLMass(), G4INCL::Particle::getTransferQValueCorrection(), G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), G4INCL::NuclearPotential::NuclearPotentialConstant::initialize(), initialize(), and G4INCL::CrossSectionsMultiPionsAndResonances::omegaNToPiN().
G4double G4INCL::ParticleTable::getINCLMass (const ParticleType t)
Get INCL particle mass (in MeV/c^2)
Definition at line 665 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 665 of file G4INCLParticleTable.cc
References G4INCL::Eta, G4INCL::EtaPrime, INCL_ERROR, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
G4int G4INCL::ParticleTable::getIsospin (const ParticleType t)
Get the isospin of a particle.
Definition at line 478 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 478 of file G4INCLParticleTable.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, INCL_ERROR, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
Referenced by G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::Nucleus::insertParticle(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaLK(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaSK(), G4INCL::CrossSectionsStrangeness::NDeltaToNLK(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsStrangeness::NDeltaToNNKKb(), G4INCL::CrossSectionsStrangeness::NDeltaToNSK(), G4INCL::CrossSectionsStrangeness::NKbToL2pi(), G4INCL::CrossSectionsStrangeness::NKbToLpi(), G4INCL::CrossSectionsStrangeness::NKbToNKb(), G4INCL::CrossSectionsStrangeness::NKbToNKb2pi(), G4INCL::CrossSectionsStrangeness::NKbToNKbpi(), G4INCL::CrossSectionsStrangeness::NKbToS2pi(), G4INCL::CrossSectionsStrangeness::NKbToSpi(), G4INCL::CrossSectionsStrangeness::NKToNK(), G4INCL::CrossSectionsStrangeness::NKToNK2pi(), G4INCL::CrossSectionsStrangeness::NKToNKpi(), G4INCL::CrossSectionsMultiPions::NNElastic(), G4INCL::CrossSectionsMultiPions::NNOnePi(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNThreePi(), G4INCL::CrossSectionsStrangeness::NNToMissingStrangeness(), G4INCL::CrossSectionsINCL46::NNToNDelta(), G4INCL::CrossSectionsMultiPions::NNToNDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNDeltaOmega(), G4INCL::CrossSectionsStrangeness::NNToNLK2pi(), G4INCL::CrossSectionsStrangeness::NNToNLKpi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaExclu(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaxPi(), G4INCL::CrossSectionsStrangeness::NNToNNKKb(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmega(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaExclu(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaFourPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaOnePiOrDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaThreePi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaTwoPi(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaxPi(), G4INCL::CrossSectionsStrangeness::NNToNSK2pi(), G4INCL::CrossSectionsStrangeness::NNToNSKpi(), G4INCL::CrossSectionsMultiPions::NNTot(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), G4INCL::CrossSectionsStrangeness::NpiToLK(), G4INCL::CrossSectionsStrangeness::NpiToLK2pi(), G4INCL::CrossSectionsStrangeness::NpiToLKpi(), G4INCL::CrossSectionsStrangeness::NpiToSK(), G4INCL::CrossSectionsStrangeness::NpiToSK2pi(), G4INCL::CrossSectionsStrangeness::NpiToSKpi(), G4INCL::CrossSectionsStrangeness::NSToNL(), G4INCL::CrossSectionsStrangeness::NSToNS(), G4INCL::CrossSectionsMultiPions::piNIne(), G4INCL::CrossSectionsMultiPions::piNOnePi(), G4INCL::CrossSectionsINCL46::piNToDelta(), G4INCL::CrossSectionsMultiPions::piNToDelta(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToEtaN(), G4INCL::CrossSectionsMultiPionsAndResonances::piNToOmegaN(), G4INCL::CrossSectionsMultiPions::piNTot(), and G4INCL::CrossSectionsMultiPions::piNTwoPi().
std::string G4INCL::ParticleTable::getIUPACElementName (const G4int Z)
Get the name of an unnamed element from the IUPAC convention.
Definition at line 1144 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1144 of file G4INCLParticleTable.cc
References Acts::Test::transform, and Z.
Referenced by getElementName().
ParticleType G4INCL::ParticleTable::getKaonType (const G4int isosp)
Get the type of kaon.
Definition at line 1278 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1278 of file G4INCLParticleTable.cc
References G4INCL::KPlus, and G4INCL::KZero.
Referenced by G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), and G4INCL::NDeltaToDeltaSKChannel::fillFinalState().
G4double G4INCL::ParticleTable::getLambdaSeparationEnergy ()
Definition at line 1126 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1126 of file G4INCLParticleTable.cc
G4double G4INCL::ParticleTable::getLargestNuclearRadius (const G4int A, const G4int Z)
Definition at line 978 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 978 of file G4INCLParticleTable.cc
References getNuclearRadius(), G4INCL::Math::max(), G4INCL::Neutron, and G4INCL::Proton.
Referenced by G4INCL::CoulombNonRelativistic::getCoulombRadius(), G4INCL::CoulombNone::maxImpactParameter(), G4INCL::CoulombNonRelativistic::maxImpactParameter(), and G4INCL::StandardPropagationModel::shootComposite().
G4int G4INCL::ParticleTable::getMassNumber (const ParticleType t)
Get mass number from particle type.
Definition at line 835 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 835 of file G4INCLParticleTable.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
G4double G4INCL::ParticleTable::getMaximumNuclearRadius (const ParticleType t, const G4int A, const G4int Z)
Definition at line 1034 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1034 of file G4INCLParticleTable.cc
References getNuclearRadius(), getSurfaceDiffuseness(), and INCL_ERROR.
Referenced by G4INCL::NuclearDensityFactory::createRCDFTable(), G4INCL::NuclearDensityFactory::createRPCorrelationTable(), and G4INCL::INCL::initUniverseRadius().
G4double G4INCL::ParticleTable::getMomentumRMS (const G4int A, const G4int Z)
Return the RMS of the momentum distribution (light clusters)
Definition at line 1082 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1082 of file G4INCLParticleTable.cc
References getFermiMomentum, and G4INCL::Math::sqrtThreeFifths.
Referenced by G4INCL::NuclearDensityFactory::createPCDFTable().
std::string G4INCL::ParticleTable::getName (const ParticleType t)
Get the native INCL name of the particle.
Definition at line 559 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 559 of file G4INCLParticleTable.cc
References G4INCL::Composite, G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
Referenced by G4INCL::Particle::dump(), getName(), G4INCL::Cluster::print(), G4INCL::Particle::print(), and G4INCL::Config::summary().
std::string G4INCL::ParticleTable::getName (const ParticleSpecies & s)
Get the native INCL name of the particle.
Definition at line 538 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 538 of file G4INCLParticleTable.cc
References G4INCL::Composite, getName(), G4INCL::ParticleSpecies::theA, G4INCL::ParticleSpecies::theType, and G4INCL::ParticleSpecies::theZ.
std::string G4INCL::ParticleTable::getName (const G4int A, const G4int Z)
Get the native INCL name of the ion.
Definition at line 545 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 545 of file G4INCLParticleTable.cc
References A(), and getElementName().
IsotopicDistribution const & G4INCL::ParticleTable::getNaturalIsotopicDistribution (const G4int Z)
Definition at line 1179 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1179 of file G4INCLParticleTable.cc
Referenced by G4INCL::INCL::initUniverseRadius().
G4double G4INCL::ParticleTable::getNeutronHalo ()
Get the size of the neutron halo.
Definition at line 1215 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1215 of file G4INCLParticleTable.cc
G4double G4INCL::ParticleTable::getNeutronSeparationEnergy ()
Getter for neutronSeparationEnergy.
Definition at line 1124 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1124 of file G4INCLParticleTable.cc
G4double G4INCL::ParticleTable::getNeutronSkin ()
Get the thickness of the neutron skin.
Definition at line 1213 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1213 of file G4INCLParticleTable.cc
G4double G4INCL::ParticleTable::getNuclearRadius (const ParticleType t, const G4int A, const G4int Z)
Definition at line 950 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 950 of file G4INCLParticleTable.cc
References A(), getRadiusParameter(), getSurfaceDiffuseness(), INCL_DEBUG, INCL_ERROR, and Z.
Referenced by G4INCL::PauliStandard::getBlockingProbability(), getLargestNuclearRadius(), getMaximumNuclearRadius(), G4INCL::NuclearDensity::getTransmissionRadius(), and G4INCL::INCL::initMaxInteractionDistance().
ParticleType G4INCL::ParticleTable::getNucleonType (const G4int isosp)
Get the type of nucleon.
Definition at line 1238 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1238 of file G4INCLParticleTable.cc
References G4INCL::Neutron, and G4INCL::Proton.
Referenced by G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), and G4INCL::NDeltaToNLKChannel::fillFinalState().
ParticleType G4INCL::ParticleTable::getPionType (const G4int isosp)
Get the type of pion.
Definition at line 1225 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1225 of file G4INCLParticleTable.cc
References G4INCL::PiMinus, G4INCL::PiPlus, and G4INCL::PiZero.
Referenced by G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), and G4INCL::NKbToLpiChannel::fillFinalState().
G4double G4INCL::ParticleTable::getProtonSeparationEnergy ()
Getter for protonSeparationEnergy.
Definition at line 1122 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1122 of file G4INCLParticleTable.cc
G4double G4INCL::ParticleTable::getRadiusParameter (const ParticleType t, const G4int A, const G4int Z)
Definition at line 982 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 982 of file G4INCLParticleTable.cc
References A(), G4INCL::HFB::getRadiusParameterHFB(), getRPCorrelationCoefficient(), G4INCL::HFB::getSurfaceDiffusenessHFB(), INCL_DEBUG, INCL_ERROR, G4INCL::Lambda, G4INCL::Neutron, and Z.
Referenced by G4INCL::NuclearDensityFactory::createRCDFTable(), G4INCL::NuclearDensityFactory::createRPCorrelationTable(), and getNuclearRadius().
G4double G4INCL::ParticleTable::getRealMass (const G4INCL::ParticleType t)
Get particle mass (in MeV/c^2)
Definition at line 710 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 710 of file G4INCLParticleTable.cc
References G4INCL::Eta, G4INCL::EtaPrime, INCL_ERROR, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
Referenced by G4INCL::Nucleus::computeTotalEnergy(), G4INCL::EventInfo::fillInverseKinematics(), G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), getRealMass(), G4INCL::Particle::getRealMass(), initialize(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaExcluIso(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNEtaIso(), G4INCL::CrossSectionsMultiPionsAndResonances::NNToNNOmegaExcluIso(), G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToEtaN(), and G4INCL::CrossSectionsMultiPionsAndResonances::piMinuspToOmegaN().
G4double G4INCL::ParticleTable::getRealMass (const G4int A, const G4int Z, const G4int S = 0)
Get nuclear mass (in MeV/c^2)
Definition at line 766 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 766 of file G4INCLParticleTable.cc
References kdfinder::abs(), getRealMass(), MeV, G4INCL::PiMinus, G4INCL::PiPlus, and Z.
G4double G4INCL::ParticleTable::getRPCorrelationCoefficient (const ParticleType t)
Get the value of the r-p correlation coefficient.
Parameters
t the type of the particle (Proton or Neutron)
Returns
the value of the r-p correlation coefficient
Definition at line 1208 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1208 of file G4INCLParticleTable.cc
References t.
Referenced by getRadiusParameter(), getSurfaceDiffuseness(), and G4INCL::ParticleSampler::ParticleSampler().
G4double G4INCL::ParticleTable::getSeparationEnergyINCL (const ParticleType t, const G4int , const G4int)
Return INCL's default separation energy.
Definition at line 1087 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1087 of file G4INCLParticleTable.cc
References INCL_ERROR, G4INCL::Lambda, G4INCL::Neutron, and G4INCL::Proton.
Referenced by getSeparationEnergyRealForLight(), and initialize().
G4double G4INCL::ParticleTable::getSeparationEnergyReal (const ParticleType t, const G4int A, const G4int Z)
Return the real separation energy.
Definition at line 1100 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1100 of file G4INCLParticleTable.cc
References A(), getTableMass, getTableParticleMass, INCL_ERROR, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Proton, and Z.
Referenced by getSeparationEnergyRealForLight(), and initialize().
G4double G4INCL::ParticleTable::getSeparationEnergyRealForLight (const ParticleType t, const G4int A, const G4int Z)
Return the real separation energy only for light nuclei.
Definition at line 1114 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1114 of file G4INCLParticleTable.cc
References clusterTableASize, clusterTableZSize, getSeparationEnergyINCL(), and getSeparationEnergyReal().
Referenced by initialize().
std::string G4INCL::ParticleTable::getShortName (const ParticleType t)
Get the short INCL name of the particle.
Definition at line 612 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 612 of file G4INCLParticleTable.cc
References G4INCL::Composite, G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
Referenced by G4INCL::CoulombNonRelativistic::getCoulombRadius(), and getShortName().
std::string G4INCL::ParticleTable::getShortName (const ParticleSpecies & s)
Get the short INCL name of the particle.
Definition at line 531 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 531 of file G4INCLParticleTable.cc
References G4INCL::Composite, getShortName(), G4INCL::ParticleSpecies::theA, G4INCL::ParticleSpecies::theType, and G4INCL::ParticleSpecies::theZ.
std::string G4INCL::ParticleTable::getShortName (const G4int A, const G4int Z)
Get the short INCL name of the ion.
Definition at line 551 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 551 of file G4INCLParticleTable.cc
References A(), and getElementName().
ParticleType G4INCL::ParticleTable::getSigmaType (const G4int isosp)
Get the type of sigma.
Definition at line 1265 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1265 of file G4INCLParticleTable.cc
References G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
Referenced by G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), and G4INCL::NDeltaToNSKChannel::fillFinalState().
G4int G4INCL::ParticleTable::getStrangenessNumber (const ParticleType t)
Get strangeness number from particle type.
Definition at line 909 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 909 of file G4INCLParticleTable.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
G4double G4INCL::ParticleTable::getSurfaceDiffuseness (const ParticleType t, const G4int A, const G4int Z)
Definition at line 1048 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1048 of file G4INCLParticleTable.cc
References a, G4INCL::HFB::getRadiusParameterHFB(), getRPCorrelationCoefficient(), G4INCL::HFB::getSurfaceDiffusenessHFB(), INCL_ERROR, G4INCL::Lambda, and G4INCL::Neutron.
Referenced by G4INCL::NuclearDensityFactory::createRCDFTable(), G4INCL::NuclearDensityFactory::createRPCorrelationTable(), getMaximumNuclearRadius(), and getNuclearRadius().
G4double G4INCL::ParticleTable::getTableQValue (const G4int A1, const G4int Z1, const G4int S1, const G4int A2, const G4int Z2, const G4int S2)
Get Q-value (in MeV/c^2)
Uses the getTableMass function to compute the Q-value for the following reaction:
Definition at line 820 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 820 of file G4INCLParticleTable.cc
References getTableMass.
Referenced by G4INCL::Particle::getEmissionQValueCorrection(), and G4INCL::Particle::getTransferQValueCorrection().
G4double G4INCL::ParticleTable::getTableQValue (const G4int A1, const G4int Z1, const G4int S1, const G4int A2, const G4int Z2, const G4int S2, const G4int A3, const G4int Z3, const G4int S3)
Get Q-value (in MeV/c^2)
Uses the getTableMass function to compute the Q-value for the following reaction:
Definition at line 824 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 824 of file G4INCLParticleTable.cc
References getTableMass.
G4double G4INCL::ParticleTable::getTableSpeciesMass (const ParticleSpecies & p)
Definition at line 828 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 828 of file G4INCLParticleTable.cc
References G4INCL::Composite, getTableMass, getTableParticleMass, G4INCL::ParticleSpecies::theA, G4INCL::ParticleSpecies::theS, G4INCL::ParticleSpecies::theType, and G4INCL::ParticleSpecies::theZ.
Referenced by G4INCL::CoulombNonRelativistic::minimumDistance().
G4double G4INCL::ParticleTable::getWidth (const ParticleType t)
Get particle width (in s)
Definition at line 1298 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1298 of file G4INCLParticleTable.cc
References G4INCL::Eta, G4INCL::EtaPrime, INCL_ERROR, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::Omega, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::SigmaMinus, G4INCL::SigmaPlus, and G4INCL::SigmaZero.
Referenced by G4INCL::SigmaZeroDecayChannel::computeDecayTime(), G4INCL::Nucleus::decayOutgoingPionResonances(), and G4INCL::Nucleus::decayOutgoingSigmaZero().
void G4INCL::ParticleTable::initialize (Config const *const theConfig = 0)
Initialize the particle table.
Definition at line 336 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 336 of file G4INCLParticleTable.cc
References G4INCL::ConstantFermiMomentum, G4INCL::ConstantLightFermiMomentum, effectiveDeltaMass, effectiveDeltaWidth, G4ParticleTable::FindParticle(), getFermiMomentum, G4INCL::Config::getFermiMomentum(), getFermiMomentumConstant(), getFermiMomentumConstantLight(), getFermiMomentumMassDependent(), G4INCL::Config::getFermiMomentumType(), getINCLMass(), G4INCL::Config::getINCLXXDataFilePath(), G4ParticleTable::GetIonTable(), G4INCL::Config::getNeutronHalo(), G4INCL::Config::getNeutronSkin(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), getRealMass(), G4INCL::Config::getRPCorrelationCoefficient(), getSeparationEnergy, getSeparationEnergyINCL(), getSeparationEnergyReal(), getSeparationEnergyRealForLight(), G4INCL::Config::getSeparationEnergyType(), getTableMass, getTableParticleMass, G4INCL::Config::getUseRealMasses(), INCL_FATAL, G4INCL::INCLSeparationEnergy, G4INCL::HFB::initialize(), G4INCL::Clustering::initialize(), G4INCL::MassDependentFermiMomentum, MeV, minDeltaMass, minDeltaMass2, minDeltaMassRndm, G4INCL::Neutron, G4INCL::PhysicalConstants::Pf, G4INCL::Proton, G4INCL::RealForLightSeparationEnergy, G4INCL::RealSeparationEnergy, and G4INCL::UnknownParticle.
Referenced by G4INCL::INCL::INCL().
G4int G4INCL::ParticleTable::parseElement (std::string pS)
Get the name of the element from the atomic number.
Definition at line 1153 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1153 of file G4INCLParticleTable.cc
References parseIUPACElement(), and Acts::Test::transform.
Referenced by G4INCL::ParticleSpecies::parseElement().
G4int G4INCL::ParticleTable::parseIUPACElement (std::string const & pS)
Parse a IUPAC element name.
Note: this function is UGLY. Look at it at your own peril.
Parameters
pS a normalised string (lowercase)
Returns
the charge number of the nuclide, or zero on fail
Definition at line 1165 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1165 of file G4INCLParticleTable.cc
References Acts::Test::transform, and Z.
Referenced by G4INCL::ParticleSpecies::parseElement(), parseElement(), and G4INCL::ParticleSpecies::parseIUPACElement().
void G4INCL::ParticleTable::setLambdaSeparationEnergy (const G4double s)
Definition at line 1132 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1132 of file G4INCLParticleTable.cc
void G4INCL::ParticleTable::setNeutronSeparationEnergy (const G4double s)
Setter for protonSeparationEnergy.
Definition at line 1130 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1130 of file G4INCLParticleTable.cc
Referenced by G4INCL::Nucleus::Nucleus().
void G4INCL::ParticleTable::setProtonSeparationEnergy (const G4double s)
Setter for protonSeparationEnergy.
Definition at line 1128 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1128 of file G4INCLParticleTable.cc
Referenced by G4INCL::Nucleus::Nucleus().
Variable Documentation
const G4int G4INCL::ParticleTable::clusterTableASize = maxClusterMass+1
Definition at line 66 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLParticleTable.hh
Referenced by getFermiMomentumConstantLight(), and getSeparationEnergyRealForLight().
const G4int G4INCL::ParticleTable::clusterTableSSize = 4
Definition at line 67 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLParticleTable.hh
const G4int G4INCL::ParticleTable::clusterTableZSize = maxClusterCharge+1
Definition at line 65 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 65 of file G4INCLParticleTable.hh
Referenced by getFermiMomentumConstantLight(), and getSeparationEnergyRealForLight().
const G4double G4INCL::ParticleTable::effectiveAntiKaonMass = 497.614
Definition at line 77 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 77 of file G4INCLParticleTable.hh
const G4double G4INCL::ParticleTable::effectiveDeltaMass = 1232.0
Definition at line 71 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 71 of file G4INCLParticleTable.hh
Referenced by initialize(), G4INCL::NDeltaToDeltaSKChannel::sampleDeltaMass(), G4INCL::NDeltaToDeltaLKChannel::sampleDeltaMass(), G4INCL::NDeltaEtaProductionChannel::sampleDeltaMass(), G4INCL::DeltaProductionChannel::sampleDeltaMass(), and G4INCL::NDeltaOmegaProductionChannel::sampleDeltaMass().
const G4double G4INCL::ParticleTable::effectiveDeltaWidth = 130.0
Definition at line 72 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 72 of file G4INCLParticleTable.hh
Referenced by initialize(), G4INCL::NDeltaToDeltaSKChannel::sampleDeltaMass(), G4INCL::NDeltaToDeltaLKChannel::sampleDeltaMass(), G4INCL::NDeltaEtaProductionChannel::sampleDeltaMass(), G4INCL::DeltaProductionChannel::sampleDeltaMass(), and G4INCL::NDeltaOmegaProductionChannel::sampleDeltaMass().
const G4double G4INCL::ParticleTable::effectiveEtaMass = 547.862
Definition at line 78 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 78 of file G4INCLParticleTable.hh
const G4double G4INCL::ParticleTable::effectiveEtaPrimeMass = 957.78
Definition at line 80 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 80 of file G4INCLParticleTable.hh
const G4double G4INCL::ParticleTable::effectiveKaonMass = 497.614
Definition at line 76 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 76 of file G4INCLParticleTable.hh
Referenced by G4INCL::NDeltaToDeltaLKChannel::sampleDeltaMass(), and G4INCL::NDeltaToDeltaSKChannel::sampleDeltaMass().
const G4double G4INCL::ParticleTable::effectiveLambdaMass = 1115.683
Definition at line 74 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 74 of file G4INCLParticleTable.hh
Referenced by G4INCL::NDeltaToDeltaLKChannel::sampleDeltaMass().
const G4double G4INCL::ParticleTable::effectiveNucleonMass = 938.2796
Definition at line 69 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 69 of file G4INCLParticleTable.hh
Referenced by G4INCL::DeltaDecayChannel::computeDecayTime(), G4INCL::Nucleus::computeTotalEnergy(), G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4INCL::BystrickyEvaluator< N >::eval(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NDeltaToNN(), G4INCL::CrossSectionsMultiPions::NNElastic(), G4INCL::CrossSectionsMultiPions::NNElasticFixed(), G4INCL::CrossSectionsMultiPions::NNOnePiOrDelta(), G4INCL::CrossSectionsMultiPions::NNThreePi(), G4INCL::CrossSectionsINCL46::NNToNDelta(), G4INCL::CrossSectionsMultiPions::NNTotFixed(), G4INCL::CrossSectionsMultiPions::NNTwoPi(), G4INCL::NDeltaEtaProductionChannel::sampleDeltaMass(), G4INCL::NDeltaOmegaProductionChannel::sampleDeltaMass(), and G4INCL::DeltaProductionChannel::sampleDeltaMass().
const G4double G4INCL::ParticleTable::effectiveNucleonMass2 = 8.8036860777616e5
Definition at line 70 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 70 of file G4INCLParticleTable.hh
Referenced by G4INCL::BystrickyEvaluator< N >::eval(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::CrossSectionsINCL46::NDeltaToNN(), and G4INCL::CrossSectionsMultiPions::NDeltaToNN().
const G4double G4INCL::ParticleTable::effectiveOmegaMass = 782.65
Definition at line 79 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 79 of file G4INCLParticleTable.hh
const G4double G4INCL::ParticleTable::effectivePhotonMass = 0.0
Definition at line 81 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 81 of file G4INCLParticleTable.hh
const G4double G4INCL::ParticleTable::effectivePionMass = 138.0
Definition at line 73 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 73 of file G4INCLParticleTable.hh
Referenced by G4INCL::DeltaDecayChannel::computeDecayTime(), and G4INCL::CrossSectionsINCL46::NNToNDelta().
const G4double G4INCL::ParticleTable::effectiveSigmaMass = 1197.45
Definition at line 75 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 75 of file G4INCLParticleTable.hh
Referenced by G4INCL::NDeltaToDeltaSKChannel::sampleDeltaMass().
G4ThreadLocal FermiMomentumFn G4INCL::ParticleTable::getFermiMomentum = NULL
Definition at line 1223 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1223 of file G4INCLParticleTable.cc
Referenced by G4INCL::NuclearDensityFactory::createPCDFTable(), getMomentumRMS(), G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), G4INCL::NuclearPotential::NuclearPotentialConstant::initialize(), and initialize().
G4ThreadLocal SeparationEnergyFn G4INCL::ParticleTable::getSeparationEnergy = NULL
Static pointer to the separation-energy function.
Definition at line 1222 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1222 of file G4INCLParticleTable.cc
Referenced by G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize(), G4INCL::NuclearPotential::NuclearPotentialConstant::initialize(), and initialize().
G4ThreadLocal NuclearMassFn G4INCL::ParticleTable::getTableMass = NULL
Static pointer to the mass function for nuclei.
Definition at line 1220 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1220 of file G4INCLParticleTable.cc
Referenced by G4INCL::ProjectileRemnant::addAllDynamicalSpectators(), G4INCL::ProjectileRemnant::addDynamicalSpectator(), G4INCL::ProjectileRemnant::addMostDynamicalSpectators(), G4INCL::Nucleus::computeRecoilKinematics(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::Nucleus::finalizeProjectileRemnant(), G4INCL::KinematicsUtils::gammaFromKineticEnergy(), G4INCL::Nucleus::getConservationBalance(), G4INCL::Particle::getEmissionQValueCorrection(), getSeparationEnergyReal(), G4INCL::Particle::getTableMass(), getTableQValue(), getTableSpeciesMass(), initialize(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), G4INCL::INCL::RecoilFunctor::scaleParticleEnergies(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
G4ThreadLocal ParticleMassFn G4INCL::ParticleTable::getTableParticleMass = NULL
Static pointer to the mass function for particles.
Definition at line 1221 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1221 of file G4INCLParticleTable.cc
Referenced by G4INCL::KinematicsUtils::gammaFromKineticEnergy(), getSeparationEnergyReal(), G4INCL::Particle::getTableMass(), getTableSpeciesMass(), initialize(), and G4INCL::StandardPropagationModel::shootParticle().
const G4int G4INCL::ParticleTable::maxClusterCharge = 8
Definition at line 63 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 63 of file G4INCLParticleTable.hh
const G4int G4INCL::ParticleTable::maxClusterMass = 12
Definition at line 62 of file G4INCLParticleTable.hh.
View newest version in sPHENIX GitHub at line 62 of file G4INCLParticleTable.hh
Referenced by G4INCL::ClusteringModelIntercomparison::ClusteringModelIntercomparison().
G4ThreadLocal G4double G4INCL::ParticleTable::minDeltaMass = 0.
Definition at line 1217 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1217 of file G4INCLParticleTable.cc
Referenced by G4INCL::InteractionAvatar::enforceEnergyConservation(), initialize(), G4INCL::InteractionAvatar::postInteraction(), G4INCL::NDeltaToDeltaSKChannel::sampleDeltaMass(), G4INCL::NDeltaToDeltaLKChannel::sampleDeltaMass(), G4INCL::NDeltaEtaProductionChannel::sampleDeltaMass(), G4INCL::DeltaProductionChannel::sampleDeltaMass(), G4INCL::NDeltaOmegaProductionChannel::sampleDeltaMass(), and G4INCL::InteractionAvatar::ViolationEEnergyFunctor::setParticleEnergy().
G4ThreadLocal G4double G4INCL::ParticleTable::minDeltaMass2 = 0.
Definition at line 1218 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1218 of file G4INCLParticleTable.cc
Referenced by initialize(), and G4INCL::InteractionAvatar::ViolationEEnergyFunctor::setParticleEnergy().
G4ThreadLocal G4double G4INCL::ParticleTable::minDeltaMassRndm = 0.
Definition at line 1219 of file G4INCLParticleTable.cc.
View newest version in sPHENIX GitHub at line 1219 of file G4INCLParticleTable.cc
Referenced by initialize(), G4INCL::NDeltaToDeltaSKChannel::sampleDeltaMass(), G4INCL::NDeltaToDeltaLKChannel::sampleDeltaMass(), G4INCL::NDeltaEtaProductionChannel::sampleDeltaMass(), G4INCL::DeltaProductionChannel::sampleDeltaMass(), and G4INCL::NDeltaOmegaProductionChannel::sampleDeltaMass().