ECCE @ EIC Software: G4LogConsts Namespace Reference
G4LogConsts Namespace Reference
Classes
union ieee754
Functions
G4double get_log_px (const G4double x)
G4double get_log_qx (const G4double x)
uint64_t dp2uint64 (G4double x)
G4double uint642dp (uint64_t ll)
G4float uint322sp (G4int x)
uint32_t sp2uint32 (G4float x)
G4double getMantExponent (const G4double x, G4double &fe)
Like frexp but vectorising and the exponent is a double.
G4float getMantExponentf (const G4float x, G4float &fe)
Like frexp but vectorising and the exponent is a float.
G4float get_log_poly (const G4float x)
Variables
const G4double LOG_UPPER_LIMIT = 1e307
const G4double LOG_LOWER_LIMIT = 0
const G4double SQRTH = 0.70710678118654752440
const G4float MAXNUMF = 3.4028234663852885981170418348451692544e38f
const G4float LOGF_UPPER_LIMIT = MAXNUMF
const G4float LOGF_LOWER_LIMIT = 0
const G4float PX1logf = 7.0376836292E-2f
const G4float PX2logf = -1.1514610310E-1f
const G4float PX3logf = 1.1676998740E-1f
const G4float PX4logf = -1.2420140846E-1f
const G4float PX5logf = 1.4249322787E-1f
const G4float PX6logf = -1.6668057665E-1f
const G4float PX7logf = 2.0000714765E-1f
const G4float PX8logf = -2.4999993993E-1f
const G4float PX9logf = 3.3333331174E-1f
const G4float SQRTHF = 0.707106781186547524f
Function Documentation
uint64_t G4LogConsts::dp2uint64 (G4double x) inline
Definition at line 149 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 149 of file G4Log.hh
References G4LogConsts::ieee754::d, G4LogConsts::ieee754::ll, tmp, and x.
Referenced by getMantExponent().
G4float G4LogConsts::get_log_poly (const G4float x) inline
Definition at line 284 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 284 of file G4Log.hh
References PX1logf, PX2logf, PX3logf, PX4logf, PX5logf, PX6logf, PX7logf, PX8logf, PX9logf, x, and y.
Referenced by G4Logf().
G4double G4LogConsts::get_log_px (const G4double x) inline
Definition at line 102 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 102 of file G4Log.hh
References x.
Referenced by G4Log().
G4double G4LogConsts::get_log_qx (const G4double x) inline
Definition at line 125 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 125 of file G4Log.hh
References x.
Referenced by G4Log().
G4double G4LogConsts::getMantExponent (const G4double x, G4double & fe) inline
Like frexp but vectorising and the exponent is a double.
Definition at line 188 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 188 of file G4Log.hh
References dp2uint64(), e, le, n, and uint642dp().
Referenced by G4Log().
G4float G4LogConsts::getMantExponentf (const G4float x, G4float & fe) inline
Like frexp but vectorising and the exponent is a float.
Definition at line 212 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 212 of file G4Log.hh
References e, n, sp2uint32(), and uint322sp().
Referenced by G4Logf().
uint32_t G4LogConsts::sp2uint32 (G4float x) inline
Definition at line 179 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 179 of file G4Log.hh
References G4LogConsts::ieee754::f, G4LogConsts::ieee754::i, tmp, and x.
Referenced by getMantExponentf().
G4float G4LogConsts::uint322sp (G4int x) inline
Definition at line 169 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 169 of file G4Log.hh
References G4LogConsts::ieee754::f, G4LogConsts::ieee754::i, tmp, and x.
Referenced by getMantExponentf().
G4double G4LogConsts::uint642dp (uint64_t ll) inline
Definition at line 159 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 159 of file G4Log.hh
References G4LogConsts::ieee754::d, G4LogConsts::ieee754::ll, and tmp.
Referenced by getMantExponent().
Variable Documentation
const G4double G4LogConsts::LOG_LOWER_LIMIT = 0
Definition at line 79 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 79 of file G4Log.hh
Referenced by G4Log().
const G4double G4LogConsts::LOG_UPPER_LIMIT = 1e307
Definition at line 78 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 78 of file G4Log.hh
Referenced by G4Log().
const G4float G4LogConsts::LOGF_LOWER_LIMIT = 0
Definition at line 272 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 272 of file G4Log.hh
Referenced by G4Logf().
const G4float G4LogConsts::LOGF_UPPER_LIMIT = MAXNUMF
Definition at line 271 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 271 of file G4Log.hh
Referenced by G4Logf().
const G4float G4LogConsts::MAXNUMF = 3.4028234663852885981170418348451692544e38f
Definition at line 82 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 82 of file G4Log.hh
const G4float G4LogConsts::PX1logf = 7.0376836292E-2f
Definition at line 274 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 274 of file G4Log.hh
Referenced by get_log_poly().
const G4float G4LogConsts::PX2logf = -1.1514610310E-1f
Definition at line 275 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 275 of file G4Log.hh
Referenced by get_log_poly().
const G4float G4LogConsts::PX3logf = 1.1676998740E-1f
Definition at line 276 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 276 of file G4Log.hh
Referenced by get_log_poly().
const G4float G4LogConsts::PX4logf = -1.2420140846E-1f
Definition at line 277 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 277 of file G4Log.hh
Referenced by get_log_poly().
const G4float G4LogConsts::PX5logf = 1.4249322787E-1f
Definition at line 278 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 278 of file G4Log.hh
Referenced by get_log_poly().
const G4float G4LogConsts::PX6logf = -1.6668057665E-1f
Definition at line 279 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 279 of file G4Log.hh
Referenced by get_log_poly().
const G4float G4LogConsts::PX7logf = 2.0000714765E-1f
Definition at line 280 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 280 of file G4Log.hh
Referenced by get_log_poly().
const G4float G4LogConsts::PX8logf = -2.4999993993E-1f
Definition at line 281 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 281 of file G4Log.hh
Referenced by get_log_poly().
const G4float G4LogConsts::PX9logf = 3.3333331174E-1f
Definition at line 282 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 282 of file G4Log.hh
Referenced by get_log_poly().
const G4double G4LogConsts::SQRTH = 0.70710678118654752440
Definition at line 81 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 81 of file G4Log.hh
Referenced by G4Log().
const G4float G4LogConsts::SQRTHF = 0.707106781186547524f
Definition at line 305 of file G4Log.hh.
View newest version in sPHENIX GitHub at line 305 of file G4Log.hh
Referenced by G4Logf().