ECCE @ EIC Software: G4LowEWentzelVIModel Class Reference
G4LowEWentzelVIModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LowEWentzelVIModel.hh>
Public Member Functions
G4LowEWentzelVIModel ()
virtual ~G4LowEWentzelVIModel ()
virtual G4double ComputeTruePathLengthLimit (const G4Track &track, G4double &currentMinimalStep)
Public Member Functions inherited from G4WentzelVIModel
G4WentzelVIModel (G4bool comb=true, const G4String &nam="WentzelVIUni")
virtual ~G4WentzelVIModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual void StartTracking (G4Track *) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double KineticEnergy, G4double AtomicNumber, G4double AtomicWeight=0., G4double cut=DBL_MAX, G4double emax=DBL_MAX) override
virtual G4ThreeVector & SampleScattering (const G4ThreeVector &, G4double safety) override
virtual G4double ComputeGeomPathLength (G4double truePathLength) override
virtual G4double ComputeTrueStepLength (G4double geomStepLength) override
void SetFixedCut (G4double)
G4double GetFixedCut () const
void SetWVICrossSection (G4WentzelOKandVIxSection *)
G4WentzelOKandVIxSection * GetWVICrossSection ()
void SetUseSecondMoment (G4bool)
G4bool UseSecondMoment () const
G4PhysicsTable * GetSecondMomentTable ()
G4double SecondMoment (const G4ParticleDefinition *, const G4MaterialCutsCouple *, G4double kineticEnergy)
void SetSingleScatteringFactor (G4double)
void DefineMaterial (const G4MaterialCutsCouple *)
Public Member Functions inherited from G4VMscModel
G4VMscModel (const G4String &nam)
~G4VMscModel () override
void InitialiseParameters (const G4ParticleDefinition *)
void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double tmax) override
void SetStepLimitType (G4MscStepLimitType)
void SetLateralDisplasmentFlag (G4bool val)
void SetRangeFactor (G4double)
void SetGeomFactor (G4double)
void SetSkin (G4double)
void SetLambdaLimit (G4double)
void SetSafetyFactor (G4double)
void SetSampleZ (G4bool)
G4VEnergyLossProcess * GetIonisation () const
void SetIonisation (G4VEnergyLossProcess *, const G4ParticleDefinition *part)
G4double ComputeSafety (const G4ThreeVector &position, G4double limit=DBL_MAX)
G4double ComputeGeomLimit (const G4Track &, G4double &presafety, G4double limit)
G4double GetDEDX (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetDEDX (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double GetRange (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple)
G4double GetRange (const G4ParticleDefinition *part, G4double kineticEnergy, const G4MaterialCutsCouple *couple, G4double logKineticEnergy)
G4double GetEnergy (const G4ParticleDefinition *part, G4double range, const G4MaterialCutsCouple *couple)
G4double GetTransportMeanFreePath (const G4ParticleDefinition *part, G4double kinEnergy)
G4double GetTransportMeanFreePath (const G4ParticleDefinition *part, G4double kinEnergy, G4double logKinEnergy)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
G4LowEWentzelVIModel & operator= (const G4LowEWentzelVIModel &right)
G4LowEWentzelVIModel (const G4LowEWentzelVIModel &)
Additional Inherited Members
Protected Member Functions inherited from G4WentzelVIModel
G4double ComputeTransportXSectionPerVolume (G4double cosTheta)
void SetupParticle (const G4ParticleDefinition *)
Protected Attributes inherited from G4WentzelVIModel
G4WentzelOKandVIxSection * wokvi
G4double tlimitminfix
G4double ssFactor
G4double invssFactor
G4double preKinEnergy
G4double tPathLength
G4double zPathLength
G4double lambdaeff
G4double currentRange
G4double cosTetMaxNuc
G4int currentMaterialIndex
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
const G4ParticleDefinition * particle
G4ParticleChangeForMSC * fParticleChange
const G4DataVector * currentCuts
G4double invsqrt12
G4double fixedCut
G4double effKinEnergy
G4double cosThetaMin
G4double cosThetaMax
G4PhysicsTable * fSecondMoments
size_t idx2
G4int minNCollisions
G4int nelments
std::vector< G4double > xsecn
std::vector< G4double > prob
G4double xtsec
G4double numlimit
G4double lowEnergyLimit
G4bool singleScatteringMode
G4bool isCombined
G4bool useSecondMoment
Detailed Description
Definition at line 57 of file G4LowEWentzelVIModel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4LowEWentzelVIModel.hh
Constructor & Destructor Documentation
G4LowEWentzelVIModel::G4LowEWentzelVIModel ()
Definition at line 57 of file G4LowEWentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 57 of file G4LowEWentzelVIModel.cc
References G4WentzelVIModel::SetSingleScatteringFactor().
G4LowEWentzelVIModel::~G4LowEWentzelVIModel () virtual
Definition at line 65 of file G4LowEWentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4LowEWentzelVIModel.cc
G4LowEWentzelVIModel::G4LowEWentzelVIModel (const G4LowEWentzelVIModel &) private
Member Function Documentation
G4double G4LowEWentzelVIModel::ComputeTruePathLengthLimit (const G4Track & track, G4double & currentMinimalStep) virtual
Reimplemented from G4WentzelVIModel.
Definition at line 70 of file G4LowEWentzelVIModel.cc.
View newest version in sPHENIX GitHub at line 70 of file G4LowEWentzelVIModel.cc
References G4VMscModel::ComputeGeomLimit(), G4VMscModel::ComputeSafety(), G4VMscModel::ConvertTrueToGeom(), G4WentzelVIModel::cosTetMaxNuc, G4WentzelVIModel::currentCouple, G4WentzelVIModel::currentMaterial, G4WentzelVIModel::currentRange, G4WentzelVIModel::DefineMaterial(), G4VMscModel::facgeom, G4VMscModel::facrange, G4VMscModel::facsafety, fGeomBoundary, fUseDistanceToBoundary, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4Material::GetRadlen(), G4VMscModel::GetRange(), G4StepPoint::GetSafety(), G4Track::GetStep(), G4StepPoint::GetStepStatus(), G4VMscModel::GetTransportMeanFreePath(), G4WentzelVIModel::lambdaeff, max, min, G4WentzelVIModel::particle, G4WentzelVIModel::preKinEnergy, G4WentzelOKandVIxSection::SetupKinematic(), G4WentzelVIModel::singleScatteringMode, G4InuclParticleNames::sp, G4VMscModel::steppingAlgorithm, G4WentzelVIModel::tlimitminfix, and G4WentzelVIModel::wokvi.
G4LowEWentzelVIModel& G4LowEWentzelVIModel::operator= (const G4LowEWentzelVIModel & right) private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LowEWentzelVIModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4LowEWentzelVIModel.cc