ECCE @ EIC Software: G4ITTypeManager Class Reference
G4ITTypeManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITType.hh>
Public Member Functions
G4ITType NewType ()
size_t size () const
void ReserveRessource ()
void ReleaseRessource ()
Static Public Member Functions
static G4ITTypeManager * Instance ()
static void DeleteInstance ()
Private Member Functions
G4ITTypeManager ()
virtual ~G4ITTypeManager ()
Private Attributes
G4ITType fLastType
size_t fRessource
Static Private Attributes
static G4ITTypeManager * fgInstance = 0
static G4ThreadLocal
G4ITTypeManager * fgInstance_local = 0
Detailed Description
Definition at line 92 of file G4ITType.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ITType.hh
Constructor & Destructor Documentation
G4ITTypeManager::G4ITTypeManager () private
Definition at line 90 of file G4ITType.cc.
View newest version in sPHENIX GitHub at line 90 of file G4ITType.cc
References fLastType, and fRessource.
Referenced by Instance().
G4ITTypeManager::~G4ITTypeManager () private virtual
Definition at line 96 of file G4ITType.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ITType.cc
Member Function Documentation
void G4ITTypeManager::DeleteInstance () static
Definition at line 66 of file G4ITType.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ITType.cc
References deleteMutex, and fgInstance.
Referenced by ReleaseRessource().
G4ITTypeManager * G4ITTypeManager::Instance (void) static
Definition at line 57 of file G4ITType.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ITType.cc
References fgInstance, and G4ITTypeManager().
Referenced by G4Scheduler::Clear(), G4Scheduler::Create(), and G4ITType::size().
G4ITType G4ITTypeManager::NewType ()
Definition at line 104 of file G4ITType.cc.
View newest version in sPHENIX GitHub at line 104 of file G4ITType.cc
References fLastType.
void G4ITTypeManager::ReleaseRessource ()
Definition at line 82 of file G4ITType.cc.
View newest version in sPHENIX GitHub at line 82 of file G4ITType.cc
References DeleteInstance(), fRessource, and ressourceMutex.
Referenced by G4Scheduler::Clear().
void G4ITTypeManager::ReserveRessource ()
Definition at line 76 of file G4ITType.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ITType.cc
References fRessource, and ressourceMutex.
Referenced by G4Scheduler::Create().
size_t G4ITTypeManager::size (void) const
Definition at line 99 of file G4ITType.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ITType.cc
References fLastType.
Referenced by G4ITType::size().
Member Data Documentation
G4ITTypeManager * G4ITTypeManager::fgInstance = 0 static private
Definition at line 95 of file G4ITType.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ITType.hh
Referenced by DeleteInstance(), and Instance().
G4ThreadLocal G4ITTypeManager * G4ITTypeManager::fgInstance_local = 0 static private
Definition at line 96 of file G4ITType.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ITType.hh
G4ITType G4ITTypeManager::fLastType private
Definition at line 97 of file G4ITType.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ITType.hh
Referenced by G4ITTypeManager(), NewType(), and size().
size_t G4ITTypeManager::fRessource private
Definition at line 101 of file G4ITType.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ITType.hh
Referenced by G4ITTypeManager(), ReleaseRessource(), and ReserveRessource().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITType.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITType.cc