ECCE @ EIC Software: G4EmDNAChemistry_option2 Class Reference
G4EmDNAChemistry_option2 Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4EmDNAChemistry_option2.hh>
Public Member Functions
G4EmDNAChemistry_option2 ()
virtual ~G4EmDNAChemistry_option2 () override
void ConstructParticle () override
void ConstructMolecule () override
void ConstructProcess () override
void ConstructDissociationChannels () override
void ConstructReactionTable (G4DNAMolecularReactionTable *pTable) override
void ConstructTimeStepModel (G4DNAMolecularReactionTable *pTable) override
Public Member Functions inherited from G4VUserChemistryList
G4VUserChemistryList (bool flag=true)
virtual ~G4VUserChemistryList ()
bool IsPhysicsConstructor ()
void ThisIsAPhysicsConstructor (bool flag=true)
void BuildPhysicsTable ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VUserChemistryList
void RegisterTimeStepModel (G4VITStepModel *timeStepModel, double startingTime=0)
void BuildPhysicsTable (G4MoleculeDefinition *)
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VUserChemistryList
int verboseLevel
bool fIsPhysicsConstructor
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 37 of file G4EmDNAChemistry_option2.hh.
View newest version in sPHENIX GitHub at line 37 of file G4EmDNAChemistry_option2.hh
Constructor & Destructor Documentation
G4EmDNAChemistry_option2::G4EmDNAChemistry_option2 ()
Definition at line 63 of file G4EmDNAChemistry_option2.cc.
View newest version in sPHENIX GitHub at line 63 of file G4EmDNAChemistry_option2.cc
References G4DNAChemistryManager::Instance(), and G4DNAChemistryManager::SetChemistryList().
G4EmDNAChemistry_option2::~G4EmDNAChemistry_option2 () override virtual
Definition at line 71 of file G4EmDNAChemistry_option2.cc.
View newest version in sPHENIX GitHub at line 71 of file G4EmDNAChemistry_option2.cc
Member Function Documentation
void G4EmDNAChemistry_option2::ConstructDissociationChannels () override virtual
Reimplemented from G4VUserChemistryList.
Definition at line 162 of file G4EmDNAChemistry_option2.cc.
View newest version in sPHENIX GitHub at line 162 of file G4EmDNAChemistry_option2.cc
References G4MoleculeDefinition::AddDecayChannel(), G4ElectronOccupancy::AddElectron(), G4MolecularDissociationChannel::AddProduct(), G4H2O::Definition(), G4DNAWaterExcitationStructure::ExcitationEnergy(), G4MoleculeTable::GetConfiguration(), G4MoleculeDefinition::GetGroundStateElectronOccupancy(), H, G4MoleculeTable::Instance(), G4MoleculeDefinition::NewConfigurationWithElectronOccupancy(), G4ElectronOccupancy::RemoveElectron(), G4MolecularDissociationChannel::SetDisplacementType(), G4MolecularDissociationChannel::SetEnergy(), and G4MolecularDissociationChannel::SetProbability().
void G4EmDNAChemistry_option2::ConstructMolecule () override virtual
Reimplemented from G4VUserChemistryList.
Definition at line 76 of file G4EmDNAChemistry_option2.cc.
View newest version in sPHENIX GitHub at line 76 of file G4EmDNAChemistry_option2.cc
References source.hepunit::Avogadro, source.hepunit::c_squared, G4DamagedDeoxyribose::Definition(), G4DamagedAdenine::Definition(), G4Electron::Definition(), G4H2O::Definition(), G4H2::Definition(), G4H3O::Definition(), G4OH::Definition(), G4Hydrogen::Definition(), G4Electron_aq::Definition(), G4H2O2::Definition(), G4DamagedGuanine::Definition(), G4DamagedThymine::Definition(), G4DamagedCytosine::Definition(), G4Deoxyribose::Definition(), G4Phosphate::Definition(), G4Adenine::Definition(), G4Guanine::Definition(), G4Thymine::Definition(), G4Cytosine::Definition(), G4ModifiedHistone::Definition(), G4Histone::Definition(), e, Acts::UnitConstants::g, G4MoleculeTable::Instance(), m2, and G4MolecularConfiguration::SetMass().
Referenced by ConstructParticle().
void G4EmDNAChemistry_option2::ConstructParticle (void) inline override virtual
Implements G4VPhysicsConstructor.
Definition at line 45 of file G4EmDNAChemistry_option2.hh.
View newest version in sPHENIX GitHub at line 45 of file G4EmDNAChemistry_option2.hh
References ConstructMolecule().
void G4EmDNAChemistry_option2::ConstructProcess (void) override virtual
Reimplemented from G4VUserChemistryList.
Definition at line 669 of file G4EmDNAChemistry_option2.cc.
View newest version in sPHENIX GitHub at line 669 of file G4EmDNAChemistry_option2.cc
References G4Electron::Definition(), G4H2O::Definition(), G4VEmProcess::EmModel(), eV, G4DNASancheExcitationModel::ExtendLowEnergyLimit(), G4MoleculeTable::GetDefintionIterator(), G4PhysicsListHelper::GetPhysicsListHelper(), G4ParticleDefinition::GetProcessManager(), G4ProcessTable::GetProcessTable(), G4DNAChemistryManager::Initialize(), G4MoleculeTable::Instance(), G4DNAChemistryManager::Instance(), G4VPhysicsConstructor::RegisterProcess(), G4MoleculeIterator< MOLECULE >::reset(), G4DNAMolecularDissociation::SetDisplacer(), G4VProcess::SetVerboseLevel(), and G4MoleculeIterator< MOLECULE >::value().
void G4EmDNAChemistry_option2::ConstructReactionTable (G4DNAMolecularReactionTable * pTable) override virtual
Implements G4VUserChemistryList.
Definition at line 419 of file G4EmDNAChemistry_option2.cc.
View newest version in sPHENIX GitHub at line 419 of file G4EmDNAChemistry_option2.cc
References G4DNAMolecularReactionData::AddProduct(), G4Hydrogen::Definition(), G4H2O2::Definition(), G4H3O::Definition(), G4OH::Definition(), G4Electron_aq::Definition(), G4H2::Definition(), e, G4MoleculeTable::GetConfiguration(), H, histone, G4MoleculeTable::Instance(), m3, mole, nm, G4DNAMolecularReactionData::SetEffectiveReactionRadius(), and G4DNAMolecularReactionTable::SetReaction().
void G4EmDNAChemistry_option2::ConstructTimeStepModel (G4DNAMolecularReactionTable * pTable) override virtual
Implements G4VUserChemistryList.
Definition at line 742 of file G4EmDNAChemistry_option2.cc.
View newest version in sPHENIX GitHub at line 742 of file G4EmDNAChemistry_option2.cc
References G4DNAMolecularReactionTable::PrintTable(), G4VUserChemistryList::RegisterTimeStepModel(), and G4DNAMolecularStepByStepModel::SetReactionModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4EmDNAChemistry_option2.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/src/G4EmDNAChemistry_option2.cc