ECCE @ EIC Software: B3PrimaryGeneratorAction Class Reference
B3PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/include/B3PrimaryGeneratorAction.hh>
Public Member Functions
B3PrimaryGeneratorAction ()
virtual ~B3PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
const G4ParticleGun * GetParticleGun () const
B3PrimaryGeneratorAction ()
virtual ~B3PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
const G4ParticleGun * GetParticleGun () const
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
Detailed Description
The primary generator action class with particle gum.
It defines an ion (F18), at rest, randomly distribued within a zone in a patient defined in GeneratePrimaries(). Ion F18 can be changed with the G4ParticleGun commands (see run2.mac).
Definition at line 46 of file B3PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 46 of file B3PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
B3PrimaryGeneratorAction::B3PrimaryGeneratorAction ()
Definition at line 44 of file B3PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 44 of file B3PrimaryGeneratorAction.cc
References eV, G4ParticleTable::FindParticle(), fParticleGun, G4ParticleTable::GetParticleTable(), particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
B3PrimaryGeneratorAction::~B3PrimaryGeneratorAction () virtual
Definition at line 64 of file B3PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 64 of file B3PrimaryGeneratorAction.cc
References fParticleGun.
B3PrimaryGeneratorAction::B3PrimaryGeneratorAction ()
virtual B3PrimaryGeneratorAction::~B3PrimaryGeneratorAction () virtual
Member Function Documentation
void B3PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
G4double x0 = 0*cm, y0 = 0*cm, z0 = 0*cm; G4double dx0 = 0*cm, dy0 = 0*cm, dz0 = 0*cm;
Implements G4VUserPrimaryGeneratorAction.
Definition at line 71 of file B3PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 71 of file B3PrimaryGeneratorAction.cc
References A(), G4ChargedGeantino::ChargedGeantino(), cm, eplus, fParticleGun, G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4ParticleGun::GetParticleDefinition(), keV, particle, G4ParticleGun::SetParticleCharge(), G4ParticleGun::SetParticleDefinition(), G4VPrimaryGenerator::SetParticlePosition(), Z, and G4InuclParticleNames::z0.
virtual void B3PrimaryGeneratorAction::GeneratePrimaries (G4Event *) virtual
Implements G4VUserPrimaryGeneratorAction.
const G4ParticleGun* B3PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 54 of file B3PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file B3PrimaryGeneratorAction.hh
References fParticleGun.
const G4ParticleGun* B3PrimaryGeneratorAction::GetParticleGun (void) const inline
Definition at line 54 of file B3PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file B3PrimaryGeneratorAction.hh
References fParticleGun.
Referenced by B3aRunAction::EndOfRunAction(), and B3bRunAction::EndOfRunAction().
Member Data Documentation
G4ParticleGun * B3PrimaryGeneratorAction::fParticleGun private
Definition at line 57 of file B3PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file B3PrimaryGeneratorAction.hh
Referenced by B3PrimaryGeneratorAction(), GeneratePrimaries(), GetParticleGun(), and ~B3PrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/include/B3PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/include/B3PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B3/B3a/src/B3PrimaryGeneratorAction.cc
geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/src/B3PrimaryGeneratorAction.cc