ECCE @ EIC Software: G4UserTrackingAction Class Reference
G4UserTrackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4UserTrackingAction.hh>
Inherited by CB_G4UserTrackingAction, CexmcTrackingAction, CML2TrackingAction, ExN04TrackingAction, ExN04TrackingAction, F04TrackingAction, G4AdjointTrackingAction, G4MultiTrackingAction, G4RTTrackingAction, ITTrackingAction, ITTrackingAction, LXeTrackingAction, MCTruthTrackingAction, Par02TrackingAction, PHG4PhenixTrackingAction, PHG4TrackingAction, PurgMagTrackingAction, RE01TrackingAction, RE04TrackingAction, RE05TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, and WLSTrackingAction.
Public Member Functions
G4UserTrackingAction ()
virtual ~G4UserTrackingAction ()
virtual void SetTrackingManagerPointer (G4TrackingManager *pValue)
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
Protected Attributes
G4TrackingManager * fpTrackingManager
Detailed Description
Definition at line 53 of file G4UserTrackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file G4UserTrackingAction.hh
Constructor & Destructor Documentation
G4UserTrackingAction::G4UserTrackingAction ()
Definition at line 44 of file G4UserTrackingAction.cc.
View newest version in sPHENIX GitHub at line 44 of file G4UserTrackingAction.cc
References FatalException, G4Exception(), and G4ParticleTable::GetParticleTable().
G4UserTrackingAction::~G4UserTrackingAction () virtual
Definition at line 63 of file G4UserTrackingAction.cc.
View newest version in sPHENIX GitHub at line 63 of file G4UserTrackingAction.cc
Member Function Documentation
virtual void G4UserTrackingAction::PostUserTrackingAction (const G4Track *) inline virtual
Reimplemented in G4MultiTrackingAction, G4RTTrackingAction, TrackingAction, G4AdjointTrackingAction, TrackingAction, TrackingAction, TrackingAction, Par02TrackingAction, MCTruthTrackingAction, ITTrackingAction, CB_G4UserTrackingAction, PurgMagTrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, RE04TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, ITTrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, LXeTrackingAction, TrackingAction, F04TrackingAction, RE01TrackingAction, TrackingAction, TrackingAction, PHG4TruthTrackingAction, PHG4PhenixTrackingAction, and PHG4TrackingAction.
Definition at line 68 of file G4UserTrackingAction.hh.
View newest version in sPHENIX GitHub at line 68 of file G4UserTrackingAction.hh
Referenced by ITTrackingInteractivity::EndTracking(), export_G4UserTrackingAction(), CB_G4UserTrackingAction::PostUserTrackingAction(), G4AdjointTrackingAction::PostUserTrackingAction(), and G4TrackingManager::ProcessOneTrack().
virtual void G4UserTrackingAction::PreUserTrackingAction (const G4Track *) inline virtual
Reimplemented in G4MultiTrackingAction, G4RTTrackingAction, TrackingAction, G4AdjointTrackingAction, CexmcTrackingAction, TrackingAction, TrackingAction, TrackingAction, CML2TrackingAction, MCTruthTrackingAction, TrackingAction, ITTrackingAction, Par02TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, RE04TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, TrackingAction, ITTrackingAction, TrackingAction, TrackingAction, WLSTrackingAction, TrackingAction, TrackingAction, CB_G4UserTrackingAction, LXeTrackingAction, TrackingAction, F04TrackingAction, ExN04TrackingAction, RE01TrackingAction, RE05TrackingAction, ExN04TrackingAction, TrackingAction, PHG4TruthTrackingAction, PHG4PhenixTrackingAction, and PHG4TrackingAction.
Definition at line 67 of file G4UserTrackingAction.hh.
View newest version in sPHENIX GitHub at line 67 of file G4UserTrackingAction.hh
Referenced by export_G4UserTrackingAction(), CB_G4UserTrackingAction::PreUserTrackingAction(), G4AdjointTrackingAction::PreUserTrackingAction(), G4TrackingManager::ProcessOneTrack(), and ITTrackingInteractivity::StartTracking().
void G4UserTrackingAction::SetTrackingManagerPointer (G4TrackingManager * pValue) virtual
Reimplemented in G4MultiTrackingAction.
Definition at line 69 of file G4UserTrackingAction.cc.
View newest version in sPHENIX GitHub at line 69 of file G4UserTrackingAction.cc
References fpTrackingManager.
Referenced by G4TrackingManager::SetUserAction().
Member Data Documentation
G4TrackingManager* G4UserTrackingAction::fpTrackingManager protected
Definition at line 75 of file G4UserTrackingAction.hh.
View newest version in sPHENIX GitHub at line 75 of file G4UserTrackingAction.hh
Referenced by PHG4TruthTrackingAction::PostUserTrackingAction(), RE01TrackingAction::PostUserTrackingAction(), LXeTrackingAction::PostUserTrackingAction(), MCTruthTrackingAction::PostUserTrackingAction(), ExN04TrackingAction::PreUserTrackingAction(), RE01TrackingAction::PreUserTrackingAction(), RE05TrackingAction::PreUserTrackingAction(), F04TrackingAction::PreUserTrackingAction(), LXeTrackingAction::PreUserTrackingAction(), WLSTrackingAction::PreUserTrackingAction(), RE04TrackingAction::PreUserTrackingAction(), MCTruthTrackingAction::PreUserTrackingAction(), CML2TrackingAction::PreUserTrackingAction(), G4RTTrackingAction::PreUserTrackingAction(), and SetTrackingManagerPointer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4UserTrackingAction.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4UserTrackingAction.cc