ECCE @ EIC Software: AnalysisManager Class Reference
AnalysisManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/include/AnalysisManager.hh>
Public Member Functions
void Score (G4double eDep)
AnalysisManager ()
~AnalysisManager ()
void book ()
void SetPrimaryEnergy (G4double energy)
void StoreEnergyDeposition (G4double edep)
void FillSecondaries (G4int AA, G4double charge, G4double energy)
void finish ()
Static Public Member Functions
static AnalysisManager * Instance ()
static void Destroy ()
Protected Member Functions
AnalysisManager ()
virtual ~AnalysisManager ()
AnalysisManager (const AnalysisManager &only)
const AnalysisManager & operator= (const AnalysisManager &only)
Private Attributes
std::ofstream outFile
std::ofstream outFileT
G4bool factoryOn
G4int fNtColId [MaxNtCol]
Static Private Attributes
static AnalysisManager * instance = 0
Detailed Description
Definition at line 34 of file AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 34 of file AnalysisManager.hh
Constructor & Destructor Documentation
AnalysisManager::AnalysisManager () protected
Definition at line 58 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 58 of file AnalysisManager.cc
References outFile.
Referenced by Instance().
AnalysisManager::~AnalysisManager () protected virtual
Definition at line 65 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 65 of file AnalysisManager.cc
References outFile, and outFileT.
AnalysisManager::AnalysisManager (const AnalysisManager & only) protected
AnalysisManager::AnalysisManager ()
AnalysisManager::~AnalysisManager ()
Member Function Documentation
void AnalysisManager::book ()
Definition at line 54 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 54 of file AnalysisManager.cc
References factoryOn, fNtColId, G4cout, G4endl, G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::OpenFile(), G4VAnalysisManager::SetFirstNtupleId(), G4VAnalysisManager::SetNtupleDirectoryName(), and G4VAnalysisManager::SetVerboseLevel().
void AnalysisManager::Destroy (void) static
Definition at line 46 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 46 of file AnalysisManager.cc
References instance.
Referenced by eRositaRunAction::EndOfRunAction().
void AnalysisManager::FillSecondaries (G4int AA, G4double charge, G4double energy)
Definition at line 112 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 112 of file AnalysisManager.cc
References fNtColId, and G4ToolsAnalysisManager::Instance().
void AnalysisManager::finish ()
Definition at line 122 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 122 of file AnalysisManager.cc
References factoryOn, and G4ToolsAnalysisManager::Instance().
AnalysisManager * AnalysisManager::Instance (void) static
Definition at line 32 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 32 of file AnalysisManager.cc
References AnalysisManager(), and instance.
Referenced by eRositaRunAction::BeginOfRunAction(), eRositaRunAction::EndOfRunAction(), and eRositaTrackerHit::PrintToFile().
const AnalysisManager& AnalysisManager::operator= (const AnalysisManager & only) protected
void AnalysisManager::Score (G4double eDep)
Definition at line 72 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 72 of file AnalysisManager.cc
References outFile.
Referenced by eRositaTrackerHit::PrintToFile().
void AnalysisManager::SetPrimaryEnergy (G4double energy)
Definition at line 98 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 98 of file AnalysisManager.cc
References fNtColId, and G4ToolsAnalysisManager::Instance().
void AnalysisManager::StoreEnergyDeposition (G4double edep)
Definition at line 105 of file AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 105 of file AnalysisManager.cc
References fNtColId, and G4ToolsAnalysisManager::Instance().
Member Data Documentation
G4bool AnalysisManager::factoryOn private
Definition at line 60 of file AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 60 of file AnalysisManager.hh
Referenced by book(), and finish().
G4int AnalysisManager::fNtColId[MaxNtCol] private
Definition at line 61 of file AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 61 of file AnalysisManager.hh
Referenced by book(), FillSecondaries(), SetPrimaryEnergy(), and StoreEnergyDeposition().
AnalysisManager * AnalysisManager::instance = 0 static private
Definition at line 68 of file AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 68 of file AnalysisManager.hh
Referenced by Destroy(), and Instance().
std::ofstream AnalysisManager::outFile private
Definition at line 69 of file AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 69 of file AnalysisManager.hh
Referenced by AnalysisManager(), Score(), and ~AnalysisManager().
std::ofstream AnalysisManager::outFileT private
Definition at line 70 of file AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 70 of file AnalysisManager.hh
Referenced by ~AnalysisManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/include/AnalysisManager.hh
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/include/AnalysisManager.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/src/AnalysisManager.cc
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/src/AnalysisManager.cc