ECCE @ EIC Software: G4CrossSectionInelastic Class Reference
G4CrossSectionInelastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionInelastic.hh>
Public Member Functions
G4CrossSectionInelastic (G4VComponentCrossSection *, G4int zmin=1, G4int zmax=256, G4double Emin=0.0, G4double Emax=DBL_MAX)
virtual ~G4CrossSectionInelastic ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=0)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=0)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void CrossSectionDescription (std::ostream &) const
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Member Functions
G4CrossSectionInelastic & operator= (const G4CrossSectionInelastic &right)
G4CrossSectionInelastic (const G4CrossSectionInelastic &)
Private Attributes
G4NistManager * nist
G4VComponentCrossSection * component
G4int Zmin
G4int Zmax
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 60 of file G4CrossSectionInelastic.hh.
View newest version in sPHENIX GitHub at line 60 of file G4CrossSectionInelastic.hh
Constructor & Destructor Documentation
G4CrossSectionInelastic::G4CrossSectionInelastic (G4VComponentCrossSection * c, G4int zmin = 1, G4int zmax = 256, G4double Emin = 0.0, G4double Emax = DBL_MAX)
Definition at line 54 of file G4CrossSectionInelastic.cc.
View newest version in sPHENIX GitHub at line 54 of file G4CrossSectionInelastic.cc
References G4NistManager::Instance(), nist, G4VCrossSectionDataSet::SetMaxKinEnergy(), and G4VCrossSectionDataSet::SetMinKinEnergy().
G4CrossSectionInelastic::~G4CrossSectionInelastic () virtual
Definition at line 65 of file G4CrossSectionInelastic.cc.
View newest version in sPHENIX GitHub at line 65 of file G4CrossSectionInelastic.cc
G4CrossSectionInelastic::G4CrossSectionInelastic (const G4CrossSectionInelastic &) private
Member Function Documentation
void G4CrossSectionInelastic::BuildPhysicsTable (const G4ParticleDefinition & p) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 86 of file G4CrossSectionInelastic.cc.
View newest version in sPHENIX GitHub at line 86 of file G4CrossSectionInelastic.cc
References kdfinder::abs(), G4VComponentCrossSection::BuildPhysicsTable(), component, G4ParticleDefinition::GetBaryonNumber(), G4HadronicParameters::Instance(), G4VCrossSectionDataSet::SetMaxKinEnergy(), and Zmax.
void G4CrossSectionInelastic::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 104 of file G4CrossSectionInelastic.cc.
View newest version in sPHENIX GitHub at line 104 of file G4CrossSectionInelastic.cc
References component, and G4VComponentCrossSection::Description().
void G4CrossSectionInelastic::DumpPhysicsTable (const G4ParticleDefinition & p) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 98 of file G4CrossSectionInelastic.cc.
View newest version in sPHENIX GitHub at line 98 of file G4CrossSectionInelastic.cc
References component, and G4VComponentCrossSection::DumpPhysicsTable().
G4double G4CrossSectionInelastic::GetElementCrossSection (const G4DynamicParticle * p, G4int Z, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 77 of file G4CrossSectionInelastic.cc.
View newest version in sPHENIX GitHub at line 77 of file G4CrossSectionInelastic.cc
References component, G4NistManager::GetAtomicMassAmu(), G4DynamicParticle::GetDefinition(), G4VComponentCrossSection::GetInelasticElementCrossSection(), G4DynamicParticle::GetKineticEnergy(), nist, and Z.
G4bool G4CrossSectionInelastic::IsElementApplicable (const G4DynamicParticle * p, G4int Z, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 68 of file G4CrossSectionInelastic.cc.
View newest version in sPHENIX GitHub at line 68 of file G4CrossSectionInelastic.cc
References e, G4DynamicParticle::GetKineticEnergy(), G4VCrossSectionDataSet::GetMaxKinEnergy(), G4VCrossSectionDataSet::GetMinKinEnergy(), and Zmin.
G4CrossSectionInelastic& G4CrossSectionInelastic::operator= (const G4CrossSectionInelastic & right) private
Member Data Documentation
G4VComponentCrossSection* G4CrossSectionInelastic::component private
Definition at line 93 of file G4CrossSectionInelastic.hh.
View newest version in sPHENIX GitHub at line 93 of file G4CrossSectionInelastic.hh
Referenced by BuildPhysicsTable(), CrossSectionDescription(), DumpPhysicsTable(), and GetElementCrossSection().
G4NistManager* G4CrossSectionInelastic::nist private
Definition at line 92 of file G4CrossSectionInelastic.hh.
View newest version in sPHENIX GitHub at line 92 of file G4CrossSectionInelastic.hh
Referenced by G4CrossSectionInelastic(), and GetElementCrossSection().
G4int G4CrossSectionInelastic::Zmax private
Definition at line 95 of file G4CrossSectionInelastic.hh.
View newest version in sPHENIX GitHub at line 95 of file G4CrossSectionInelastic.hh
Referenced by BuildPhysicsTable().
G4int G4CrossSectionInelastic::Zmin private
Definition at line 94 of file G4CrossSectionInelastic.hh.
View newest version in sPHENIX GitHub at line 94 of file G4CrossSectionInelastic.hh
Referenced by IsElementApplicable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionInelastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4CrossSectionInelastic.cc