ECCE @ EIC Software: G4Generator2BN Class Reference
G4Generator2BN Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4Generator2BN.hh>
Public Member Functions
G4Generator2BN (const G4String &name="")
virtual ~G4Generator2BN ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double out_energy, G4int Z, const G4Material *mat=0)
void PrintGeneratorInformation () const
void SetInterpolationThetaIncrement (G4double increment)
G4double GetInterpolationThetaIncrement ()
void SetGammaCutValue (G4double cutValue)
G4double GetGammaCutValue ()
void ConstructMajorantSurface ()
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material *)
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr)
const G4String & GetName () const
Protected Member Functions
G4double CalculateFkt (G4double k, G4double theta, G4double A, G4double c) const
G4double Calculatedsdkdt (G4double kout, G4double theta, G4double Eel) const
Private Member Functions
G4Generator2BN & operator= (const G4Generator2BN &right)
G4Generator2BN (const G4Generator2BN &)
Private Attributes
G4Generator2BS fGenerator2BS
G4double b
G4int index_min
G4int index_max
G4double kmin
G4double Ekmin
G4double dtheta
G4double kcut
G4int nwarn
Static Private Attributes
static G4double Atab [320]
static G4double ctab [320]
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 61 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 61 of file G4Generator2BN.hh
Constructor & Destructor Documentation
G4Generator2BN::G4Generator2BN (const G4String & name = "")
Definition at line 156 of file G4Generator2BN.cc.
View newest version in sPHENIX GitHub at line 156 of file G4Generator2BN.cc
References b, dtheta, Ekmin, eV, index_max, index_min, kcut, kmin, nwarn, and rad.
G4Generator2BN::~G4Generator2BN () virtual
Definition at line 180 of file G4Generator2BN.cc.
View newest version in sPHENIX GitHub at line 180 of file G4Generator2BN.cc
G4Generator2BN::G4Generator2BN (const G4Generator2BN &) private
Member Function Documentation
G4double G4Generator2BN::Calculatedsdkdt (G4double kout, G4double theta, G4double Eel) const protected
Definition at line 269 of file G4Generator2BN.cc.
View newest version in sPHENIX GitHub at line 269 of file G4Generator2BN.cc
References E, source.hepunit::electron_mass_c2, epsilon(), k, k2, LL, MeV, pi, Q, Z, and Z2.
Referenced by ConstructMajorantSurface(), and SampleDirection().
G4double G4Generator2BN::CalculateFkt (G4double k, G4double theta, G4double A, G4double c) const protected
Definition at line 262 of file G4Generator2BN.cc.
View newest version in sPHENIX GitHub at line 262 of file G4Generator2BN.cc
References b, and theta().
Referenced by ConstructMajorantSurface().
void G4Generator2BN::ConstructMajorantSurface ()
Definition at line 335 of file G4Generator2BN.cc.
View newest version in sPHENIX GitHub at line 335 of file G4Generator2BN.cc
References A(), Atab, b, c, Calculatedsdkdt(), CalculateFkt(), ctab, dtheta, source.hepunit::electron_mass_c2, G4cout, G4endl, index_max, index_min, k, G4InuclParticleNames::k0, kcut, kmin, pi, ratio, theta(), and v.
G4double G4Generator2BN::GetGammaCutValue () inline
Definition at line 83 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 83 of file G4Generator2BN.hh
References kcut.
G4double G4Generator2BN::GetInterpolationThetaIncrement () inline
Definition at line 80 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 80 of file G4Generator2BN.hh
References dtheta.
G4Generator2BN& G4Generator2BN::operator= (const G4Generator2BN & right) private
void G4Generator2BN::PrintGeneratorInformation () const
Definition at line 427 of file G4Generator2BN.cc.
View newest version in sPHENIX GitHub at line 427 of file G4Generator2BN.cc
References G4cout, and G4endl.
G4ThreeVector & G4Generator2BN::SampleDirection (const G4DynamicParticle * dp, G4double out_energy, G4int Z, const G4Material * mat = 0) virtual
Implements G4VEmAngularDistribution.
Definition at line 183 of file G4Generator2BN.cc.
View newest version in sPHENIX GitHub at line 183 of file G4Generator2BN.cc
References A(), Atab, b, c, Calculatedsdkdt(), ctab, fGenerator2BS, G4VEmAngularDistribution::fLocalDirection, G4cout, G4endl, G4Exp(), G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetTotalEnergy(), index_max, index_min, k, max, MeV, nwarn, phi, CLHEP::pi, pi2, CLHEP::Hep3Vector::rotateUz(), G4Generator2BS::SampleDirection(), CLHEP::Hep3Vector::set(), t, twopi, Acts::UnitConstants::u, and y.
void G4Generator2BN::SetGammaCutValue (G4double cutValue) inline
Definition at line 82 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 82 of file G4Generator2BN.hh
References kcut.
void G4Generator2BN::SetInterpolationThetaIncrement (G4double increment) inline
Definition at line 79 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 79 of file G4Generator2BN.hh
References dtheta.
Member Data Documentation
G4double G4Generator2BN::Atab static private
Definition at line 105 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 105 of file G4Generator2BN.hh
Referenced by ConstructMajorantSurface(), and SampleDirection().
G4double G4Generator2BN::b private
Definition at line 100 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 100 of file G4Generator2BN.hh
Referenced by CalculateFkt(), ConstructMajorantSurface(), G4Generator2BN(), and SampleDirection().
G4double G4Generator2BN::ctab static private
Definition at line 106 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 106 of file G4Generator2BN.hh
Referenced by ConstructMajorantSurface(), and SampleDirection().
G4double G4Generator2BN::dtheta private
Definition at line 103 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 103 of file G4Generator2BN.hh
Referenced by ConstructMajorantSurface(), G4Generator2BN(), GetInterpolationThetaIncrement(), and SetInterpolationThetaIncrement().
G4double G4Generator2BN::Ekmin private
Definition at line 102 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 102 of file G4Generator2BN.hh
Referenced by G4Generator2BN().
G4Generator2BS G4Generator2BN::fGenerator2BS private
Definition at line 98 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 98 of file G4Generator2BN.hh
Referenced by SampleDirection().
G4int G4Generator2BN::index_max private
Definition at line 101 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 101 of file G4Generator2BN.hh
Referenced by ConstructMajorantSurface(), G4Generator2BN(), and SampleDirection().
G4int G4Generator2BN::index_min private
Definition at line 101 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 101 of file G4Generator2BN.hh
Referenced by ConstructMajorantSurface(), G4Generator2BN(), and SampleDirection().
G4double G4Generator2BN::kcut private
Definition at line 104 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 104 of file G4Generator2BN.hh
Referenced by ConstructMajorantSurface(), G4Generator2BN(), GetGammaCutValue(), and SetGammaCutValue().
G4double G4Generator2BN::kmin private
Definition at line 102 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 102 of file G4Generator2BN.hh
Referenced by ConstructMajorantSurface(), and G4Generator2BN().
G4int G4Generator2BN::nwarn private
Definition at line 108 of file G4Generator2BN.hh.
View newest version in sPHENIX GitHub at line 108 of file G4Generator2BN.hh
Referenced by G4Generator2BN(), and SampleDirection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4Generator2BN.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4Generator2BN.cc