ECCE @ EIC Software: CLHEP::RandGaussZiggurat Class Reference
CLHEP::RandGaussZiggurat Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGaussZiggurat.h>
Public Member Functions
RandGaussZiggurat (HepRandomEngine &anEngine, double mean=0.0, double stdDev=1.0)
RandGaussZiggurat (HepRandomEngine *anEngine, double mean=0.0, double stdDev=1.0)
virtual ~RandGaussZiggurat ()
float fire ()
float fire (float mean, float stdDev)
void fireArray (const int size, float *vect)
void fireArray (const int size, double *vect)
void fireArray (const int size, float *vect, float mean, float stdDev)
void fireArray (const int size, double *vect, double mean, double stdDev)
virtual double operator() ()
virtual double operator() (double mean, double stdDev)
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::RandGauss
RandGauss (HepRandomEngine &anEngine, double mean=0.0, double stdDev=1.0)
RandGauss (HepRandomEngine *anEngine, double mean=0.0, double stdDev=1.0)
virtual ~RandGauss ()
double fire ()
double fire (double mean, double stdDev)
void fireArray (const int size, double *vect)
void fireArray (const int size, double *vect, double mean, double stdDev)
bool getF () const
void setF (bool val)
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static float shoot ()
static float shoot (float mean, float stdDev)
static void shootArray (const int size, float *vect, float mean=0.0, float stdDev=1.0)
static void shootArray (const int size, double *vect, double mean=0.0, double stdDev=1.0)
static float shoot (HepRandomEngine *anotherEngine)
static float shoot (HepRandomEngine *anotherEngine, float mean, float stdDev)
static void shootArray (HepRandomEngine *anotherEngine, const int size, float *vect, float mean=0.0, float stdDev=1.0)
static void shootArray (HepRandomEngine *anotherEngine, const int size, double *vect, double mean=0.0, double stdDev=1.0)
static std::string distributionName ()
static bool ziggurat_init ()
Static Public Member Functions inherited from CLHEP::RandGauss
static double shoot ()
static double shoot (double mean, double stdDev)
static void shootArray (const int size, double *vect, double mean=0.0, double stdDev=1.0)
static double shoot (HepRandomEngine *anEngine)
static double shoot (HepRandomEngine *anEngine, double mean, double stdDev)
static void shootArray (HepRandomEngine *anEngine, const int size, double *vect, double mean=0.0, double stdDev=1.0)
static std::string distributionName ()
static bool getFlag ()
static void setFlag (bool val)
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Static Protected Member Functions
static unsigned long ziggurat_SHR3 (HepRandomEngine *anEngine)
static float ziggurat_UNI (HepRandomEngine *anEngine)
static float ziggurat_RNOR (HepRandomEngine *anEngine)
static float ziggurat_nfix (long hz, HepRandomEngine *anEngine)
Static Protected Member Functions inherited from CLHEP::RandGauss
static double getVal ()
static void setVal (double nextVal)
Static Protected Attributes
static CLHEP_THREAD_LOCAL
unsigned long kn [128]
static CLHEP_THREAD_LOCAL
unsigned long ke [256]
static CLHEP_THREAD_LOCAL float wn [128]
static CLHEP_THREAD_LOCAL float fn [128]
static CLHEP_THREAD_LOCAL float we [256]
static CLHEP_THREAD_LOCAL float fe [256]
static CLHEP_THREAD_LOCAL bool ziggurat_is_init = false
Private Member Functions
RandGaussZiggurat (const RandGaussZiggurat &d)
Additional Inherited Members
Protected Member Functions inherited from CLHEP::RandGauss
double normal ()
Protected Attributes inherited from CLHEP::RandGauss
double defaultMean
double defaultStdDev
std::shared_ptr< HepRandomEngine > localEngine
Detailed Description
Author
ATLAS
Definition at line 37 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 37 of file RandGaussZiggurat.h
Constructor & Destructor Documentation
CLHEP::RandGaussZiggurat::RandGaussZiggurat (HepRandomEngine & anEngine, double mean = 0.0, double stdDev = 1.0) inline
Definition at line 137 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 137 of file RandGaussZiggurat.h
CLHEP::RandGaussZiggurat::RandGaussZiggurat (HepRandomEngine * anEngine, double mean = 0.0, double stdDev = 1.0) inline
Definition at line 141 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 141 of file RandGaussZiggurat.h
CLHEP::RandGaussZiggurat::~RandGaussZiggurat () virtual
Definition at line 14 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 14 of file RandGaussZiggurat.cc
CLHEP::RandGaussZiggurat::RandGaussZiggurat (const RandGaussZiggurat & d) private
Member Function Documentation
static std::string CLHEP::RandGaussZiggurat::distributionName () inline static
Definition at line 87 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 87 of file RandGaussZiggurat.h
HepRandomEngine & CLHEP::RandGaussZiggurat::engine () virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 12 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 12 of file RandGaussZiggurat.cc
References CLHEP::RandGauss::engine().
float CLHEP::RandGaussZiggurat::fire () inline
Definition at line 67 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 67 of file RandGaussZiggurat.h
References CLHEP::RandGauss::defaultMean, CLHEP::RandGauss::defaultStdDev, CLHEP::RandGauss::localEngine, and ziggurat_RNOR().
Referenced by fireArray().
float CLHEP::RandGaussZiggurat::fire (float mean, float stdDev) inline
Definition at line 69 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 69 of file RandGaussZiggurat.h
References CLHEP::RandGauss::localEngine, and ziggurat_RNOR().
void CLHEP::RandGaussZiggurat::fireArray (const int size, float * vect)
Definition at line 137 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 137 of file RandGaussZiggurat.cc
References CLHEP::RandGauss::defaultMean, CLHEP::RandGauss::defaultStdDev, and fire().
void CLHEP::RandGaussZiggurat::fireArray (const int size, double * vect)
Definition at line 144 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 144 of file RandGaussZiggurat.cc
References CLHEP::RandGauss::defaultMean, CLHEP::RandGauss::defaultStdDev, and fire().
void CLHEP::RandGaussZiggurat::fireArray (const int size, float * vect, float mean, float stdDev)
Definition at line 151 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 151 of file RandGaussZiggurat.cc
References fire().
void CLHEP::RandGaussZiggurat::fireArray (const int size, double * vect, double mean, double stdDev)
Definition at line 158 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 158 of file RandGaussZiggurat.cc
References fire().
std::istream & CLHEP::RandGaussZiggurat::get (std::istream & is) virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 173 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 173 of file RandGaussZiggurat.cc
References CLHEP::RandGauss::get(), and name().
std::string CLHEP::RandGaussZiggurat::name () const virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 17 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 17 of file RandGaussZiggurat.cc
Referenced by get(), and put().
double CLHEP::RandGaussZiggurat::operator() () virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 101 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 101 of file RandGaussZiggurat.cc
References CLHEP::RandGauss::defaultMean, CLHEP::RandGauss::defaultStdDev, CLHEP::RandGauss::localEngine, and ziggurat_RNOR().
double CLHEP::RandGaussZiggurat::operator() (double mean, double stdDev) virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 105 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 105 of file RandGaussZiggurat.cc
References CLHEP::RandGauss::localEngine, and ziggurat_RNOR().
std::ostream & CLHEP::RandGaussZiggurat::put (std::ostream & os) const virtual
Reimplemented from CLHEP::RandGauss.
Definition at line 165 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 165 of file RandGaussZiggurat.cc
References name(), gammaraytel::pr, and CLHEP::RandGauss::put().
static float CLHEP::RandGaussZiggurat::shoot () inline static
Definition at line 49 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 49 of file RandGaussZiggurat.h
References CLHEP::HepRandom::getTheEngine(), and ziggurat_RNOR().
Referenced by shootArray().
static float CLHEP::RandGaussZiggurat::shoot (float mean, float stdDev) inline static
Definition at line 50 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 50 of file RandGaussZiggurat.h
References shoot().
Referenced by shoot().
static float CLHEP::RandGaussZiggurat::shoot (HepRandomEngine * anotherEngine) inline static
Definition at line 58 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 58 of file RandGaussZiggurat.h
References ziggurat_RNOR().
static float CLHEP::RandGaussZiggurat::shoot (HepRandomEngine * anotherEngine, float mean, float stdDev) inline static
Definition at line 59 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 59 of file RandGaussZiggurat.h
References shoot().
Referenced by shoot().
void CLHEP::RandGaussZiggurat::shootArray (const int size, float * vect, float mean = 0.0, float stdDev = 1.0) static
Definition at line 109 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 109 of file RandGaussZiggurat.cc
References shoot().
void CLHEP::RandGaussZiggurat::shootArray (const int size, double * vect, double mean = 0.0, double stdDev = 1.0) static
Definition at line 116 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 116 of file RandGaussZiggurat.cc
References shoot().
void CLHEP::RandGaussZiggurat::shootArray (HepRandomEngine * anotherEngine, const int size, float * vect, float mean = 0.0, float stdDev = 1.0) static
Definition at line 123 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 123 of file RandGaussZiggurat.cc
References shoot().
void CLHEP::RandGaussZiggurat::shootArray (HepRandomEngine * anotherEngine, const int size, double * vect, double mean = 0.0, double stdDev = 1.0) static
Definition at line 130 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 130 of file RandGaussZiggurat.cc
References shoot().
bool CLHEP::RandGaussZiggurat::ziggurat_init () static
Definition at line 22 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 22 of file RandGaussZiggurat.cc
References fe, fn, ke, kn, we, wn, and ziggurat_is_init.
Referenced by ziggurat_nfix(), and ziggurat_RNOR().
float CLHEP::RandGaussZiggurat::ziggurat_nfix (long hz, HepRandomEngine * anEngine) static protected
Definition at line 73 of file RandGaussZiggurat.cc.
View newest version in sPHENIX GitHub at line 73 of file RandGaussZiggurat.cc
References kdfinder::abs(), fn, kn, r, wn, x, y, ziggurat_init(), ziggurat_is_init, ziggurat_SHR3(), and ziggurat_UNI().
Referenced by ziggurat_RNOR().
static float CLHEP::RandGaussZiggurat::ziggurat_RNOR (HepRandomEngine * anEngine) inline static protected
Definition at line 115 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 115 of file RandGaussZiggurat.h
References kdfinder::abs(), Acts::Test::hz, kn, wn, ziggurat_init(), ziggurat_is_init, ziggurat_nfix(), and ziggurat_SHR3().
Referenced by fire(), operator()(), and shoot().
static unsigned long CLHEP::RandGaussZiggurat::ziggurat_SHR3 (HepRandomEngine * anEngine) inline static protected
Definition at line 113 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 113 of file RandGaussZiggurat.h
Referenced by ziggurat_nfix(), and ziggurat_RNOR().
static float CLHEP::RandGaussZiggurat::ziggurat_UNI (HepRandomEngine * anEngine) inline static protected
Definition at line 114 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 114 of file RandGaussZiggurat.h
References CLHEP::HepRandomEngine::flat().
Referenced by ziggurat_nfix().
Member Data Documentation
CLHEP_THREAD_LOCAL float CLHEP::RandGaussZiggurat::fe static protected
Definition at line 109 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 109 of file RandGaussZiggurat.h
Referenced by ziggurat_init().
CLHEP_THREAD_LOCAL float CLHEP::RandGaussZiggurat::fn static protected
Definition at line 109 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 109 of file RandGaussZiggurat.h
Referenced by ziggurat_init(), and ziggurat_nfix().
CLHEP_THREAD_LOCAL unsigned long CLHEP::RandGaussZiggurat::ke static protected
Definition at line 108 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 108 of file RandGaussZiggurat.h
Referenced by ziggurat_init().
CLHEP_THREAD_LOCAL unsigned long CLHEP::RandGaussZiggurat::kn static protected
Definition at line 108 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 108 of file RandGaussZiggurat.h
Referenced by ziggurat_init(), ziggurat_nfix(), and ziggurat_RNOR().
CLHEP_THREAD_LOCAL float CLHEP::RandGaussZiggurat::we static protected
Definition at line 109 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 109 of file RandGaussZiggurat.h
Referenced by ziggurat_init().
CLHEP_THREAD_LOCAL float CLHEP::RandGaussZiggurat::wn static protected
Definition at line 109 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 109 of file RandGaussZiggurat.h
Referenced by ziggurat_init(), ziggurat_nfix(), and ziggurat_RNOR().
CLHEP_THREAD_LOCAL bool CLHEP::RandGaussZiggurat::ziggurat_is_init = false static protected
Definition at line 111 of file RandGaussZiggurat.h.
View newest version in sPHENIX GitHub at line 111 of file RandGaussZiggurat.h
Referenced by ziggurat_init(), ziggurat_nfix(), and ziggurat_RNOR().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGaussZiggurat.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandGaussZiggurat.cc