ECCE @ EIC Software: G4tgrPlaceParameterisation Class Reference
G4tgrPlaceParameterisation Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrPlaceParameterisation.hh>
Public Member Functions
G4tgrPlaceParameterisation ()
~G4tgrPlaceParameterisation ()
G4tgrPlaceParameterisation (const std::vector< G4String > &p)
const G4String & GetParamType () const
std::vector< G4double > GetExtraData () const
const G4String & GetRotMatName () const
Public Member Functions inherited from G4tgrPlace
G4tgrPlace ()
virtual ~G4tgrPlace ()
const G4String & GetParentName () const
G4tgrVolume * GetVolume () const
unsigned int GetCopyNo () const
const G4String & GetType () const
void SetVolume (G4tgrVolume *vol)
void SetType (const G4String &typ)
virtual G4ThreeVector GetPlacement () const
Private Attributes
G4String theParamType
std::vector< G4double > theExtraData
G4String theRotMatName
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrPlaceParameterisation &obj)
Additional Inherited Members
Protected Attributes inherited from G4tgrPlace
G4tgrVolume * theVolume
G4String theParentName
unsigned int theCopyNo
G4String theType
Detailed Description
Definition at line 56 of file G4tgrPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 56 of file G4tgrPlaceParameterisation.hh
Constructor & Destructor Documentation
G4tgrPlaceParameterisation::G4tgrPlaceParameterisation ()
Definition at line 41 of file G4tgrPlaceParameterisation.cc.
View newest version in sPHENIX GitHub at line 41 of file G4tgrPlaceParameterisation.cc
G4tgrPlaceParameterisation::~G4tgrPlaceParameterisation ()
Definition at line 47 of file G4tgrPlaceParameterisation.cc.
View newest version in sPHENIX GitHub at line 47 of file G4tgrPlaceParameterisation.cc
G4tgrPlaceParameterisation::G4tgrPlaceParameterisation (const std::vector< G4String > & p)
Definition at line 54 of file G4tgrPlaceParameterisation.cc.
View newest version in sPHENIX GitHub at line 54 of file G4tgrPlaceParameterisation.cc
References G4tgrUtils::CheckWLsize(), G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), G4tgrPlace::theCopyNo, theExtraData, theParamType, G4tgrPlace::theParentName, theRotMatName, G4tgrPlace::theType, and WLSIZE_GE.
Member Function Documentation
std::vector<G4double> G4tgrPlaceParameterisation::GetExtraData () const inline
Definition at line 70 of file G4tgrPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 70 of file G4tgrPlaceParameterisation.hh
References theExtraData.
Referenced by G4tgbPlaceParameterisation::CheckNExtraData(), G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), and G4tgbPlaceParamSquare::G4tgbPlaceParamSquare().
const G4String& G4tgrPlaceParameterisation::GetParamType () const inline
Definition at line 68 of file G4tgrPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 68 of file G4tgrPlaceParameterisation.hh
References theParamType.
Referenced by G4tgbVolume::ConstructG4PhysVol(), G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), and G4tgbPlaceParamSquare::G4tgbPlaceParamSquare().
const G4String& G4tgrPlaceParameterisation::GetRotMatName () const inline
Definition at line 71 of file G4tgrPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgrPlaceParameterisation.hh
References theRotMatName.
Referenced by G4tgbPlaceParameterisation::G4tgbPlaceParameterisation().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrPlaceParameterisation & obj) friend
Definition at line 90 of file G4tgrPlaceParameterisation.cc.
View newest version in sPHENIX GitHub at line 90 of file G4tgrPlaceParameterisation.cc
Member Data Documentation
std::vector<G4double> G4tgrPlaceParameterisation::theExtraData private
Definition at line 78 of file G4tgrPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 78 of file G4tgrPlaceParameterisation.hh
Referenced by G4tgrPlaceParameterisation(), GetExtraData(), and operator<<().
G4String G4tgrPlaceParameterisation::theParamType private
Definition at line 77 of file G4tgrPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 77 of file G4tgrPlaceParameterisation.hh
Referenced by G4tgrPlaceParameterisation(), GetParamType(), and operator<<().
G4String G4tgrPlaceParameterisation::theRotMatName private
Definition at line 81 of file G4tgrPlaceParameterisation.hh.
View newest version in sPHENIX GitHub at line 81 of file G4tgrPlaceParameterisation.hh
Referenced by G4tgrPlaceParameterisation(), GetRotMatName(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrPlaceParameterisation.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrPlaceParameterisation.cc