ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/externals/zlib/src/gzlib.c File Reference
gzlib.c File Reference
#include "gzguts.h"
Macros
#define LSEEK lseek
Functions
local void gz_reset OF ((gz_statep))
local gzFile gz_open OF ((const void *, int, const char *))
local void gz_reset (gz_statep state)
local gzFile gz_open (void *path, int fd, const char *mode) const
gzFile ZEXPORT gzopen (char *path, const char *mode) const
gzFile ZEXPORT gzopen64 (char *path, const char *mode) const
gzFile ZEXPORT gzdopen (int fd, const char *mode)
int ZEXPORT gzbuffer (gzFile file, unsigned size)
int ZEXPORT gzrewind (gzFile file)
z_off64_t ZEXPORT gzseek64 (gzFile file, z_off64_t offset, int whence)
z_off_t ZEXPORT gzseek (gzFile file, z_off_t offset, int whence)
z_off64_t ZEXPORT gztell64 (gzFile file)
z_off_t ZEXPORT gztell (gzFile file)
z_off64_t ZEXPORT gzoffset64 (gzFile file)
z_off_t ZEXPORT gzoffset (gzFile file)
int ZEXPORT gzeof (gzFile file)
const char *ZEXPORT gzerror (gzFile file, int *errnum)
void ZEXPORT gzclearerr (gzFile file)
void ZLIB_INTERNAL gz_error (gz_statep state, int err, const char *msg)
unsigned ZLIB_INTERNAL gz_intmax ()
Macro Definition Documentation
#define LSEEK lseek
Definition at line 14 of file gzlib.c.
View newest version in sPHENIX GitHub at line 14 of file gzlib.c
Referenced by gz_open(), gzoffset64(), gzrewind(), and gzseek64().
Function Documentation
void ZLIB_INTERNAL gz_error (gz_statep state, int err, const char * msg)
Definition at line 579 of file gzlib.c.
View newest version in sPHENIX GitHub at line 579 of file gzlib.c
References check_license::err(), void(), Z_BUF_ERROR, Z_MEM_ERROR, and Z_OK.
Referenced by gz_comp(), gz_decomp(), gz_init(), gz_load(), gz_look(), gz_reset(), gzclearerr(), gzclose_r(), gzclose_w(), gzfread(), gzfwrite(), gzputs(), gzread(), gzseek64(), gzungetc(), and gzwrite().
unsigned ZLIB_INTERNAL gz_intmax ()
Definition at line 625 of file gzlib.c.
View newest version in sPHENIX GitHub at line 625 of file gzlib.c
local gzFile gz_open (void * path, int fd, const char * mode) const
Definition at line 91 of file gzlib.c.
View newest version in sPHENIX GitHub at line 91 of file gzlib.c
References GZ_APPEND, GZ_NONE, GZ_READ, gz_reset(), GZ_WRITE, GZBUFSIZE, LSEEK, Acts::open, void(), Z_DEFAULT_COMPRESSION, Z_DEFAULT_STRATEGY, Z_FILTERED, Z_FIXED, Z_HUFFMAN_ONLY, and Z_RLE.
Referenced by gzdopen(), gzopen(), and gzopen64().
local void gz_reset (gz_statep state)
Definition at line 75 of file gzlib.c.
View newest version in sPHENIX GitHub at line 75 of file gzlib.c
References gz_error(), GZ_READ, LOOK, and Z_OK.
Referenced by gz_open(), and gzrewind().
int ZEXPORT gzbuffer (gzFile file, unsigned size)
Definition at line 316 of file gzlib.c.
View newest version in sPHENIX GitHub at line 316 of file gzlib.c
References GZ_READ, and GZ_WRITE.
Referenced by buffer::makeBuffer().
void ZEXPORT gzclearerr (gzFile file)
Definition at line 553 of file gzlib.c.
View newest version in sPHENIX GitHub at line 553 of file gzlib.c
References gz_error(), GZ_READ, GZ_WRITE, and Z_OK.
gzFile ZEXPORT gzdopen (int fd, const char * mode)
Definition at line 286 of file gzlib.c.
View newest version in sPHENIX GitHub at line 286 of file gzlib.c
References fd, gz_open(), and void().
int ZEXPORT gzeof (gzFile file)
Definition at line 515 of file gzlib.c.
View newest version in sPHENIX GitHub at line 515 of file gzlib.c
References GZ_READ, and GZ_WRITE.
const char* ZEXPORT gzerror (gzFile file, int * errnum)
Definition at line 532 of file gzlib.c.
View newest version in sPHENIX GitHub at line 532 of file gzlib.c
References GZ_READ, GZ_WRITE, and Z_MEM_ERROR.
z_off_t ZEXPORT gzoffset (gzFile file)
Definition at line 505 of file gzlib.c.
View newest version in sPHENIX GitHub at line 505 of file gzlib.c
References gzoffset64().
z_off64_t ZEXPORT gzoffset64 (gzFile file)
Definition at line 482 of file gzlib.c.
View newest version in sPHENIX GitHub at line 482 of file gzlib.c
References GZ_READ, GZ_WRITE, LSEEK, and offset.
Referenced by gzoffset().
gzFile ZEXPORT gzopen (char * path, const char * mode) const
Definition at line 270 of file gzlib.c.
View newest version in sPHENIX GitHub at line 270 of file gzlib.c
References gz_open().
gzFile ZEXPORT gzopen64 (char * path, const char * mode) const
Definition at line 278 of file gzlib.c.
View newest version in sPHENIX GitHub at line 278 of file gzlib.c
References gz_open().
int ZEXPORT gzrewind (gzFile file)
Definition at line 343 of file gzlib.c.
View newest version in sPHENIX GitHub at line 343 of file gzlib.c
References GZ_READ, gz_reset(), LSEEK, Z_BUF_ERROR, and Z_OK.
Referenced by gzseek64().
z_off_t ZEXPORT gzseek (gzFile file, z_off_t offset, int whence)
Definition at line 443 of file gzlib.c.
View newest version in sPHENIX GitHub at line 443 of file gzlib.c
References gzseek64().
z_off64_t ZEXPORT gzseek64 (gzFile file, z_off64_t offset, int whence)
Definition at line 366 of file gzlib.c.
View newest version in sPHENIX GitHub at line 366 of file gzlib.c
References COPY, GT_OFF, gz_error(), GZ_READ, GZ_WRITE, gzrewind(), LSEEK, n, offset, Z_BUF_ERROR, and Z_OK.
Referenced by gzseek().
z_off_t ZEXPORT gztell (gzFile file)
Definition at line 472 of file gzlib.c.
View newest version in sPHENIX GitHub at line 472 of file gzlib.c
References gztell64().
z_off64_t ZEXPORT gztell64 (gzFile file)
Definition at line 455 of file gzlib.c.
View newest version in sPHENIX GitHub at line 455 of file gzlib.c
References GZ_READ, and GZ_WRITE.
Referenced by gztell().
local void gz_reset OF ((gz_statep))
local gzFile gz_open OF ((const void *, int, const char *))