ECCE @ EIC Software: G4ParticleHPHash Class Reference
G4ParticleHPHash Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPHash.hh>
Public Member Functions
G4ParticleHPHash ()
~G4ParticleHPHash ()
G4ParticleHPHash (const G4ParticleHPHash &aHash)
G4ParticleHPHash & operator= (const G4ParticleHPHash &aHash)
void Clear ()
G4bool Prepared () const
void SetData (G4int index, G4double x, G4double y)
G4int GetMinIndex (G4double e) const
Private Attributes
G4bool prepared
G4ParticleHPHash * theUpper
std::vector< int > theIndex
std::vector
< G4ParticleHPDataPoint > theData
Detailed Description
Definition at line 36 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleHPHash.hh
Constructor & Destructor Documentation
G4ParticleHPHash::G4ParticleHPHash () inline
Definition at line 39 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleHPHash.hh
References prepared, and theUpper.
Referenced by G4ParticleHPHash(), operator=(), and SetData().
G4ParticleHPHash::~G4ParticleHPHash () inline
Definition at line 45 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPHash.hh
References theUpper.
G4ParticleHPHash::G4ParticleHPHash (const G4ParticleHPHash & aHash) inline
Definition at line 50 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPHash.hh
References G4ParticleHPHash(), prepared, theData, theIndex, and theUpper.
Member Function Documentation
void G4ParticleHPHash::Clear () inline
Definition at line 83 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPHash.hh
References Clear(), prepared, theData, theIndex, and theUpper.
Referenced by G4ParticleHPVector::CleanUp(), Clear(), G4ParticleHPVector::ReHash(), and G4ParticleHPVector::~G4ParticleHPVector().
G4int G4ParticleHPHash::GetMinIndex (G4double e) const inline
Definition at line 111 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPHash.hh
References e, GetMinIndex(), theData, theIndex, and theUpper.
Referenced by GetMinIndex(), and G4ParticleHPVector::GetXsec().
G4ParticleHPHash& G4ParticleHPHash::operator= (const G4ParticleHPHash & aHash) inline
Definition at line 65 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ParticleHPHash.hh
References G4ParticleHPHash(), theData, theIndex, and theUpper.
G4bool G4ParticleHPHash::Prepared () const inline
Definition at line 96 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPHash.hh
References prepared.
Referenced by G4ParticleHPVector::GetXsec(), G4ParticleHPVector::Merge(), and G4ParticleHPVector::ThinOut().
void G4ParticleHPHash::SetData (G4int index, G4double x, G4double y) inline
Definition at line 97 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPHash.hh
References G4ParticleHPHash(), prepared, G4ParticleHPDataPoint::SetData(), SetData(), theData, theIndex, and theUpper.
Referenced by G4ParticleHPVector::Hash(), G4ParticleHPVector::Init(), and SetData().
Member Data Documentation
G4bool G4ParticleHPHash::prepared private
Definition at line 137 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ParticleHPHash.hh
Referenced by Clear(), G4ParticleHPHash(), Prepared(), and SetData().
std::vector<G4ParticleHPDataPoint> G4ParticleHPHash::theData private
Definition at line 140 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ParticleHPHash.hh
Referenced by Clear(), G4ParticleHPHash(), GetMinIndex(), operator=(), and SetData().
std::vector<int> G4ParticleHPHash::theIndex private
Definition at line 139 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ParticleHPHash.hh
Referenced by Clear(), G4ParticleHPHash(), GetMinIndex(), operator=(), and SetData().
G4ParticleHPHash* G4ParticleHPHash::theUpper private
Definition at line 138 of file G4ParticleHPHash.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ParticleHPHash.hh
Referenced by Clear(), G4ParticleHPHash(), GetMinIndex(), operator=(), SetData(), and ~G4ParticleHPHash().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPHash.hh