ECCE @ EIC Software: G4ParticleHPData Class Reference
G4ParticleHPData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPData.hh>
Public Member Functions
G4ParticleHPData (G4ParticleDefinition *projectile)
~G4ParticleHPData ()
G4PhysicsVector * MakePhysicsVector (G4Element *thE, G4ParticleHPFissionData *theP)
G4PhysicsVector * MakePhysicsVector (G4Element *thE, G4ParticleHPCaptureData *theP)
G4PhysicsVector * MakePhysicsVector (G4Element *thE, G4ParticleHPElasticData *theP)
G4PhysicsVector * MakePhysicsVector (G4Element *thE, G4ParticleHPInelasticData *theP)
G4PhysicsVector * DoPhysicsVector (G4ParticleHPVector *theVector)
Static Public Member Functions
static G4ParticleHPData * Instance (G4ParticleDefinition *projectile)
Private Member Functions
void addPhysicsVector ()
Private Attributes
std::vector
< G4ParticleHPElementData * > theData
G4int numEle
G4ParticleDefinition * theProjectile
G4String theDataDirVariable
Detailed Description
Definition at line 45 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPData.hh
Constructor & Destructor Documentation
G4ParticleHPData::G4ParticleHPData (G4ParticleDefinition * projectile)
Definition at line 35 of file G4ParticleHPData.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleHPData.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4Element::GetElementTable(), G4Element::GetNumberOfElements(), G4He3::He3(), lightions::Init(), G4Neutron::Neutron(), numEle, G4Proton::Proton(), theData, theDataDirVariable, and G4Triton::Triton().
Referenced by Instance().
G4ParticleHPData::~G4ParticleHPData ()
Definition at line 62 of file G4ParticleHPData.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ParticleHPData.cc
References it, and theData.
Member Function Documentation
void G4ParticleHPData::addPhysicsVector () private
Definition at line 95 of file G4ParticleHPData.cc.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPData.cc
References G4Element::GetElementTable(), G4Element::GetNumberOfElements(), lightions::Init(), numEle, theData, theDataDirVariable, and theProjectile.
Referenced by MakePhysicsVector().
G4PhysicsVector * G4ParticleHPData::DoPhysicsVector (G4ParticleHPVector * theVector)
Definition at line 76 of file G4ParticleHPData.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleHPData.cc
References emax, CEMC_TOWER::emin, G4ParticleHPVector::GetVectorLength(), G4ParticleHPVector::GetX(), G4ParticleHPVector::GetY(), and G4LPhysicsFreeVector::PutValues().
Referenced by MakePhysicsVector().
G4ParticleHPData * G4ParticleHPData::Instance (G4ParticleDefinition * projectile) static
Definition at line 68 of file G4ParticleHPData.cc.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPData.cc
References G4ParticleHPData(), and G4ThreadLocal.
Referenced by G4ParticleHPFissionData::BuildPhysicsTable(), G4ParticleHPCaptureData::BuildPhysicsTable(), G4ParticleHPElasticData::BuildPhysicsTable(), and G4ParticleHPInelasticData::BuildPhysicsTable().
G4PhysicsVector* G4ParticleHPData::MakePhysicsVector (G4Element * thE, G4ParticleHPFissionData * theP) inline
Definition at line 53 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPData.hh
References addPhysicsVector(), DoPhysicsVector(), G4Element::GetIndex(), numEle, and theData.
Referenced by G4ParticleHPFissionData::BuildPhysicsTable(), G4ParticleHPCaptureData::BuildPhysicsTable(), G4ParticleHPElasticData::BuildPhysicsTable(), and G4ParticleHPInelasticData::BuildPhysicsTable().
G4PhysicsVector* G4ParticleHPData::MakePhysicsVector (G4Element * thE, G4ParticleHPCaptureData * theP) inline
Definition at line 58 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPData.hh
References addPhysicsVector(), DoPhysicsVector(), G4Element::GetIndex(), numEle, and theData.
G4PhysicsVector* G4ParticleHPData::MakePhysicsVector (G4Element * thE, G4ParticleHPElasticData * theP) inline
Definition at line 63 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ParticleHPData.hh
References addPhysicsVector(), DoPhysicsVector(), G4Element::GetIndex(), numEle, and theData.
G4PhysicsVector* G4ParticleHPData::MakePhysicsVector (G4Element * thE, G4ParticleHPInelasticData * theP) inline
Definition at line 68 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPData.hh
References addPhysicsVector(), DoPhysicsVector(), G4Element::GetIndex(), numEle, and theData.
Member Data Documentation
G4int G4ParticleHPData::numEle private
Definition at line 83 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPData.hh
Referenced by addPhysicsVector(), G4ParticleHPData(), and MakePhysicsVector().
std::vector< G4ParticleHPElementData* > G4ParticleHPData::theData private
Definition at line 82 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPData.hh
Referenced by addPhysicsVector(), G4ParticleHPData(), MakePhysicsVector(), and ~G4ParticleHPData().
G4String G4ParticleHPData::theDataDirVariable private
Definition at line 87 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPData.hh
Referenced by addPhysicsVector(), and G4ParticleHPData().
G4ParticleDefinition* G4ParticleHPData::theProjectile private
Definition at line 86 of file G4ParticleHPData.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPData.hh
Referenced by addPhysicsVector().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPData.cc