ECCE @ EIC Software: G4TrackStateID< T > Class Template Reference
G4TrackStateID< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4TrackState.hh>
Static Public Member Functions
static int GetID ()
Private Member Functions
G4TrackStateID ()
~G4TrackStateID ()
Static Private Attributes
static const int fID
Additional Inherited Members
Protected Member Functions inherited from G4VTrackStateID
G4VTrackStateID ()
virtual ~G4VTrackStateID ()
Static Protected Member Functions inherited from G4VTrackStateID
static int Create ()
Static Protected Attributes inherited from G4VTrackStateID
static int fgLastID = 0
Detailed Description
template<class T>
class G4TrackStateID< T >
Definition at line 66 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 66 of file G4TrackState.hh
Constructor & Destructor Documentation
template<class T > G4TrackStateID< T >::G4TrackStateID () inline private
Definition at line 74 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 74 of file G4TrackState.hh
template<class T > G4TrackStateID< T >::~G4TrackStateID () inline private
Definition at line 75 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 75 of file G4TrackState.hh
Member Function Documentation
template<class T > static int G4TrackStateID< T >::GetID () inline static
Definition at line 69 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 69 of file G4TrackState.hh
References G4TrackStateID< T >::fID.
Referenced by G4TrackStateBase< G4ITNavigator >::GetID(), G4TrackStateBase< G4ITNavigator >::ID(), and G4TrackState< G4ITNavigator >::ID().
Member Data Documentation
template<class T > const int G4TrackStateID< T >::fID static private
Definition at line 72 of file G4TrackState.hh.
View newest version in sPHENIX GitHub at line 72 of file G4TrackState.hh
Referenced by G4TrackStateID< T >::GetID().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4TrackState.hh