ECCE @ EIC Software: G4RDeBremsstrahlungSpectrum Class Reference
G4RDeBremsstrahlungSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDeBremsstrahlungSpectrum.hh>
Public Member Functions
G4RDeBremsstrahlungSpectrum (const G4DataVector &bins, const G4String &name)
~G4RDeBremsstrahlungSpectrum ()
G4double Probability (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const
G4double AverageEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const
G4double SampleEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const
G4double MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z=0, const G4ParticleDefinition *pd=0) const
G4double Excitation (G4int Z, G4double kineticEnergy) const
void PrintData () const
Public Member Functions inherited from G4RDVEnergySpectrum
G4RDVEnergySpectrum ()
virtual ~G4RDVEnergySpectrum ()
Private Member Functions
G4double IntSpectrum (G4double xMin, G4double xMax, const G4DataVector &p) const
G4double AverageValue (G4double xMin, G4double xMax, const G4DataVector &p) const
G4double Function (G4double x, const G4DataVector &p) const
G4RDeBremsstrahlungSpectrum (const G4RDeBremsstrahlungSpectrum &)
G4RDeBremsstrahlungSpectrum & operator= (const G4RDeBremsstrahlungSpectrum &right)
Private Attributes
G4RDBremsstrahlungParameters * theBRparam
G4double lowestE
size_t length
G4int verbose
const G4DataVector xp
Detailed Description
Definition at line 64 of file G4RDeBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RDeBremsstrahlungSpectrum.hh
Constructor & Destructor Documentation
G4RDeBremsstrahlungSpectrum::G4RDeBremsstrahlungSpectrum (const G4DataVector & bins, const G4String & name)
Definition at line 54 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 54 of file G4RDeBremsstrahlungSpectrum.cc
References length, theBRparam, verbose, and xp.
G4RDeBremsstrahlungSpectrum::~G4RDeBremsstrahlungSpectrum ()
Definition at line 66 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 66 of file G4RDeBremsstrahlungSpectrum.cc
References theBRparam.
G4RDeBremsstrahlungSpectrum::G4RDeBremsstrahlungSpectrum (const G4RDeBremsstrahlungSpectrum &) private
Member Function Documentation
G4double G4RDeBremsstrahlungSpectrum::AverageEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 119 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 119 of file G4RDeBremsstrahlungSpectrum.cc
References AverageValue(), c, e, G4cout, G4endl, IntSpectrum(), length, lowestE, max, MeV, min, G4RDBremsstrahlungParameters::Parameter(), G4RDBremsstrahlungParameters::ParameterC(), theBRparam, G4InuclParticleNames::tm, verbose, x, y, and G4InuclParticleNames::z0.
G4double G4RDeBremsstrahlungSpectrum::AverageValue (G4double xMin, G4double xMax, const G4DataVector & p) const private
Definition at line 246 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 246 of file G4RDeBremsstrahlungSpectrum.cc
References k, length, max, min, sum, x1, x2, xp, z1, and z2.
Referenced by AverageEnergy().
G4double G4RDeBremsstrahlungSpectrum::Excitation (G4int Z, G4double kineticEnergy) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 301 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 301 of file G4RDeBremsstrahlungSpectrum.cc
G4double G4RDeBremsstrahlungSpectrum::Function (G4double x, const G4DataVector & p) const private
Definition at line 277 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 277 of file G4RDeBremsstrahlungSpectrum.cc
References f, length, and xp.
Referenced by SampleEnergy().
G4double G4RDeBremsstrahlungSpectrum::IntSpectrum (G4double xMin, G4double xMax, const G4DataVector & p) const private
Definition at line 220 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 220 of file G4RDeBremsstrahlungSpectrum.cc
References k, length, max, min, sum, x1, x2, xp, z1, and z2.
Referenced by AverageEnergy(), and Probability().
G4double G4RDeBremsstrahlungSpectrum::MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 306 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 306 of file G4RDeBremsstrahlungSpectrum.cc
G4RDeBremsstrahlungSpectrum& G4RDeBremsstrahlungSpectrum::operator= (const G4RDeBremsstrahlungSpectrum & right) private
void G4RDeBremsstrahlungSpectrum::PrintData (void) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 298 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 298 of file G4RDeBremsstrahlungSpectrum.cc
References G4RDBremsstrahlungParameters::PrintData(), and theBRparam.
G4double G4RDeBremsstrahlungSpectrum::Probability (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 72 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 72 of file G4RDeBremsstrahlungSpectrum.cc
References e, G4cout, G4endl, IntSpectrum(), length, lowestE, max, MeV, min, G4RDBremsstrahlungParameters::Parameter(), theBRparam, G4InuclParticleNames::tm, verbose, x, xp, y, and G4InuclParticleNames::z0.
G4double G4RDeBremsstrahlungSpectrum::SampleEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 173 of file G4RDeBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 173 of file G4RDeBremsstrahlungSpectrum.cc
References e, Function(), G4cout, G4endl, G4UniformRand, length, lowestE, max, min, G4RDBremsstrahlungParameters::Parameter(), theBRparam, G4InuclParticleNames::tm, x, and xp.
Member Data Documentation
size_t G4RDeBremsstrahlungSpectrum::length private
Definition at line 118 of file G4RDeBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 118 of file G4RDeBremsstrahlungSpectrum.hh
Referenced by AverageEnergy(), AverageValue(), Function(), G4RDeBremsstrahlungSpectrum(), IntSpectrum(), Probability(), and SampleEnergy().
G4double G4RDeBremsstrahlungSpectrum::lowestE private
Definition at line 117 of file G4RDeBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 117 of file G4RDeBremsstrahlungSpectrum.hh
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4RDBremsstrahlungParameters* G4RDeBremsstrahlungSpectrum::theBRparam private
Definition at line 116 of file G4RDeBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 116 of file G4RDeBremsstrahlungSpectrum.hh
Referenced by AverageEnergy(), G4RDeBremsstrahlungSpectrum(), PrintData(), Probability(), SampleEnergy(), and ~G4RDeBremsstrahlungSpectrum().
G4int G4RDeBremsstrahlungSpectrum::verbose private
Definition at line 119 of file G4RDeBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 119 of file G4RDeBremsstrahlungSpectrum.hh
Referenced by AverageEnergy(), G4RDeBremsstrahlungSpectrum(), and Probability().
const G4DataVector G4RDeBremsstrahlungSpectrum::xp private
Definition at line 121 of file G4RDeBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 121 of file G4RDeBremsstrahlungSpectrum.hh
Referenced by AverageValue(), Function(), G4RDeBremsstrahlungSpectrum(), IntSpectrum(), Probability(), and SampleEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDeBremsstrahlungSpectrum.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDeBremsstrahlungSpectrum.cc