ECCE @ EIC Software: G4NormalNavigation Class Reference
G4NormalNavigation Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4NormalNavigation.hh>
Public Member Functions
G4NormalNavigation ()
~G4NormalNavigation ()
G4bool LevelLocate (G4NavigationHistory &history, const G4VPhysicalVolume *blockedVol, const G4int blockedNum, const G4ThreeVector &globalPoint, const G4ThreeVector *globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector &localPoint)
G4double ComputeStep (const G4ThreeVector &localPoint, const G4ThreeVector &localDirection, const G4double currentProposedStepLength, G4double &newSafety, G4NavigationHistory &history, G4bool &validExitNormal, G4ThreeVector &exitNormal, G4bool &exiting, G4bool &entering, G4VPhysicalVolume *(*pBlockedPhysical), G4int &blockedReplicaNo)
G4double ComputeSafety (const G4ThreeVector &globalpoint, const G4NavigationHistory &history, const G4double pMaxLength=DBL_MAX)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
void CheckMode (G4bool mode)
Private Attributes
G4bool fCheck = false
G4NavigationLogger * fLogger
Detailed Description
Definition at line 51 of file G4NormalNavigation.hh.
View newest version in sPHENIX GitHub at line 51 of file G4NormalNavigation.hh
Constructor & Destructor Documentation
G4NormalNavigation::G4NormalNavigation ()
Definition at line 40 of file G4NormalNavigation.cc.
View newest version in sPHENIX GitHub at line 40 of file G4NormalNavigation.cc
References fLogger.
G4NormalNavigation::~G4NormalNavigation ()
Definition at line 49 of file G4NormalNavigation.cc.
View newest version in sPHENIX GitHub at line 49 of file G4NormalNavigation.cc
References fLogger.
Member Function Documentation
void G4NormalNavigation::CheckMode (G4bool mode) inline
G4double G4NormalNavigation::ComputeSafety (const G4ThreeVector & globalpoint, const G4NavigationHistory & history, const G4double pMaxLength = DBL_MAX)
Definition at line 332 of file G4NormalNavigation.cc.
View newest version in sPHENIX GitHub at line 332 of file G4NormalNavigation.cc
References G4NavigationLogger::ComputeSafetyLog(), G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), fCheck, fLogger, G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetNoDaughters(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTopVolume(), G4VPhysicalVolume::GetTranslation(), and G4AffineTransform::Invert().
Referenced by G4RegularNavigation::ComputeSafety(), G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), and G4ITNavigator2::ComputeSafety().
G4double G4NormalNavigation::ComputeStep (const G4ThreeVector & localPoint, const G4ThreeVector & localDirection, const G4double currentProposedStepLength, G4double & newSafety, G4NavigationHistory & history, G4bool & validExitNormal, G4ThreeVector & exitNormal, G4bool & exiting, G4bool & entering, G4VPhysicalVolume ** pBlockedPhysical, G4int & blockedReplicaNo)
Definition at line 64 of file G4NormalNavigation.cc.
View newest version in sPHENIX GitHub at line 64 of file G4NormalNavigation.cc
References G4NavigationLogger::AlongComputeStepLog(), G4NavigationLogger::CheckAndReportBadNormal(), G4NavigationLogger::CheckDaughterEntryPoint(), DBL_MAX, G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), CLHEP::Hep3Vector::dot(), fCheck, fLogger, G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetNoDaughters(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTopVolume(), G4VPhysicalVolume::GetTranslation(), CLHEP::HepRotation::inverse(), G4AffineTransform::Invert(), kInfinity, kMinExitingNormalCosine, G4NavigationLogger::PostComputeStepLog(), G4NavigationLogger::PreComputeStepLog(), G4NavigationLogger::PrintDaughterLog(), and G4NavigationLogger::ReportOutsideMother().
Referenced by G4RegularNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), and G4RegularNavigation::ComputeStepSkippingEqualMaterials().
G4int G4NormalNavigation::GetVerboseLevel () const
Definition at line 397 of file G4NormalNavigation.cc.
View newest version in sPHENIX GitHub at line 397 of file G4NormalNavigation.cc
References fLogger, and G4NavigationLogger::GetVerboseLevel().
G4bool G4NormalNavigation::LevelLocate (G4NavigationHistory & history, const G4VPhysicalVolume * blockedVol, const G4int blockedNum, const G4ThreeVector & globalPoint, const G4ThreeVector * globalDirection, const G4bool pLocatedOnEdge, G4ThreeVector & localPoint) inline
Referenced by G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), and G4ITNavigator2::LocateGlobalPointAndSetup().
void G4NormalNavigation::SetVerboseLevel (G4int level)
Definition at line 406 of file G4NormalNavigation.cc.
View newest version in sPHENIX GitHub at line 406 of file G4NormalNavigation.cc
References fLogger, and G4NavigationLogger::SetVerboseLevel().
Member Data Documentation
G4bool G4NormalNavigation::fCheck = false private
Definition at line 103 of file G4NormalNavigation.hh.
View newest version in sPHENIX GitHub at line 103 of file G4NormalNavigation.hh
Referenced by ComputeSafety(), and ComputeStep().
G4NavigationLogger* G4NormalNavigation::fLogger private
Definition at line 104 of file G4NormalNavigation.hh.
View newest version in sPHENIX GitHub at line 104 of file G4NormalNavigation.hh
Referenced by ComputeSafety(), ComputeStep(), G4NormalNavigation(), GetVerboseLevel(), SetVerboseLevel(), and ~G4NormalNavigation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4NormalNavigation.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4NormalNavigation.cc