ECCE @ EIC Software: G4VisCommandGeometrySetForceLineSegmentsPerCircle Class Reference
G4VisCommandGeometrySetForceLineSegmentsPerCircle Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometrySet.hh>
Public Member Functions
G4VisCommandGeometrySetForceLineSegmentsPerCircle ()
virtual ~G4VisCommandGeometrySetForceLineSegmentsPerCircle ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Private Member Functions
G4VisCommandGeometrySetForceLineSegmentsPerCircle (const G4VisCommandGeometrySetForceLineSegmentsPerCircle &)
G4VisCommandGeometrySetForceLineSegmentsPerCircle & operator= (const G4VisCommandGeometrySetForceLineSegmentsPerCircle &)
Private Attributes
G4UIcommand * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Types inherited from G4VVisCommandGeometry
typedef std::map
< G4LogicalVolume *, const
G4VisAttributes * >
::const_iterator VisAttsMapIterator
Protected Member Functions inherited from G4VVisCommandGeometrySet
void Set (G4String logVolName, const G4VVisCommandGeometrySetFunction &, G4int requestedDepth)
void SetLVVisAtts (G4LogicalVolume *, const G4VVisCommandGeometrySetFunction &, G4int depth, G4int requestedDepth)
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommandGeometry
static std::map
< G4LogicalVolume *, const
G4VisAttributes * > fVisAttsMap
Detailed Description
Definition at line 235 of file G4VisCommandsGeometrySet.hh.
View newest version in sPHENIX GitHub at line 235 of file G4VisCommandsGeometrySet.hh
Constructor & Destructor Documentation
G4VisCommandGeometrySetForceLineSegmentsPerCircle::G4VisCommandGeometrySetForceLineSegmentsPerCircle ()
Definition at line 287 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 287 of file G4VisCommandsGeometrySet.cc
References fpCommand, G4UIparameter::SetDefaultValue(), G4UIparameter::SetGuidance(), G4UIcommand::SetGuidance(), and G4UIcommand::SetParameter().
G4VisCommandGeometrySetForceLineSegmentsPerCircle::~G4VisCommandGeometrySetForceLineSegmentsPerCircle () virtual
Definition at line 314 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 314 of file G4VisCommandsGeometrySet.cc
References fpCommand.
G4VisCommandGeometrySetForceLineSegmentsPerCircle::G4VisCommandGeometrySetForceLineSegmentsPerCircle (const G4VisCommandGeometrySetForceLineSegmentsPerCircle &) private
Member Function Documentation
G4String G4VisCommandGeometrySetForceLineSegmentsPerCircle::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 320 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 320 of file G4VisCommandsGeometrySet.cc
G4VisCommandGeometrySetForceLineSegmentsPerCircle& G4VisCommandGeometrySetForceLineSegmentsPerCircle::operator= (const G4VisCommandGeometrySetForceLineSegmentsPerCircle &) private
void G4VisCommandGeometrySetForceLineSegmentsPerCircle::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 326 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 326 of file G4VisCommandsGeometrySet.cc
References G4ArrayOps::Set().
Member Data Documentation
G4UIcommand* G4VisCommandGeometrySetForceLineSegmentsPerCircle::fpCommand private
Definition at line 247 of file G4VisCommandsGeometrySet.hh.
View newest version in sPHENIX GitHub at line 247 of file G4VisCommandsGeometrySet.hh
Referenced by G4VisCommandGeometrySetForceLineSegmentsPerCircle(), and ~G4VisCommandGeometrySetForceLineSegmentsPerCircle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometrySet.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsGeometrySet.cc