ECCE @ EIC Software: PrimaryGeneratorAction3 Class Reference
PrimaryGeneratorAction3 Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/include/PrimaryGeneratorAction3.hh>
Public Member Functions
PrimaryGeneratorAction3 (G4ParticleGun *)
~PrimaryGeneratorAction3 ()
void GeneratePrimaries (G4Event *)
G4ThreeVector GetNewUz ()
G4double GetAlphaMax ()
Private Attributes
G4ThreeVector fNewUz
G4double fAlphaMax
G4ParticleGun * fParticleGun
Detailed Description
Definition at line 46 of file PrimaryGeneratorAction3.hh.
View newest version in sPHENIX GitHub at line 46 of file PrimaryGeneratorAction3.hh
Constructor & Destructor Documentation
PrimaryGeneratorAction3::PrimaryGeneratorAction3 (G4ParticleGun * gun)
Definition at line 47 of file PrimaryGeneratorAction3.cc.
View newest version in sPHENIX GitHub at line 47 of file PrimaryGeneratorAction3.cc
References deg, fAlphaMax, fNewUz, phi, and theta().
PrimaryGeneratorAction3::~PrimaryGeneratorAction3 ()
Definition at line 62 of file PrimaryGeneratorAction3.cc.
View newest version in sPHENIX GitHub at line 62 of file PrimaryGeneratorAction3.cc
Member Function Documentation
void PrimaryGeneratorAction3::GeneratePrimaries (G4Event * anEvent)
Definition at line 67 of file PrimaryGeneratorAction3.cc.
View newest version in sPHENIX GitHub at line 67 of file PrimaryGeneratorAction3.cc
References dir, fAlphaMax, fNewUz, fParticleGun, G4UniformRand, G4ParticleGun::GeneratePrimaryVertex(), MeV, CLHEP::Hep3Vector::rotateUz(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and twopi.
G4double PrimaryGeneratorAction3::GetAlphaMax () inline
Definition at line 57 of file PrimaryGeneratorAction3.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction3.hh
References fAlphaMax.
G4ThreeVector PrimaryGeneratorAction3::GetNewUz () inline
Definition at line 56 of file PrimaryGeneratorAction3.hh.
View newest version in sPHENIX GitHub at line 56 of file PrimaryGeneratorAction3.hh
References fNewUz.
Member Data Documentation
G4double PrimaryGeneratorAction3::fAlphaMax private
Definition at line 61 of file PrimaryGeneratorAction3.hh.
View newest version in sPHENIX GitHub at line 61 of file PrimaryGeneratorAction3.hh
Referenced by GeneratePrimaries(), GetAlphaMax(), and PrimaryGeneratorAction3().
G4ThreeVector PrimaryGeneratorAction3::fNewUz private
Definition at line 57 of file PrimaryGeneratorAction3.hh.
View newest version in sPHENIX GitHub at line 57 of file PrimaryGeneratorAction3.hh
Referenced by GeneratePrimaries(), GetNewUz(), and PrimaryGeneratorAction3().
G4ParticleGun* PrimaryGeneratorAction3::fParticleGun private
Definition at line 63 of file PrimaryGeneratorAction3.hh.
View newest version in sPHENIX GitHub at line 63 of file PrimaryGeneratorAction3.hh
Referenced by GeneratePrimaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/include/PrimaryGeneratorAction3.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/src/PrimaryGeneratorAction3.cc