ECCE @ EIC Software: CCalHall Class Reference
CCalHall Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalHall.hh>
Public Member Functions
CCalHall (const G4String &name)
virtual ~CCalHall ()
G4String getMaterial () const
G4double getDy_2Hall () const
G4double getDx_2Hall () const
Public Member Functions inherited from CCalDetector
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (G4int i) const
G4int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Protected Member Functions
virtual G4int readFile ()
virtual void constructDaughters ()
Protected Member Functions inherited from CCalDetector
G4int buildFromFile ()
Private Attributes
G4String genMaterial
G4double dy_2Hall
G4double dx_2Hall
Additional Inherited Members
Protected Attributes inherited from CCalDetector
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
G4int constructFlag
Detailed Description
Definition at line 35 of file CCalHall.hh.
View newest version in sPHENIX GitHub at line 35 of file CCalHall.hh
Constructor & Destructor Documentation
CCalHall::CCalHall (const G4String & name)
Definition at line 40 of file CCalHall.cc.
View newest version in sPHENIX GitHub at line 40 of file CCalHall.cc
CCalHall::~CCalHall () virtual
Definition at line 42 of file CCalHall.cc.
View newest version in sPHENIX GitHub at line 42 of file CCalHall.cc
Member Function Documentation
void CCalHall::constructDaughters () protected virtual
Implements CCalDetector.
Reimplemented in CCalG4Hall.
Definition at line 75 of file CCalHall.cc.
View newest version in sPHENIX GitHub at line 75 of file CCalHall.cc
References CCalDetector::addDetector().
G4double CCalHall::getDx_2Hall () const inline
Definition at line 45 of file CCalHall.hh.
View newest version in sPHENIX GitHub at line 45 of file CCalHall.hh
References dx_2Hall.
Referenced by CCalG4Hall::constructIn().
G4double CCalHall::getDy_2Hall () const inline
Definition at line 44 of file CCalHall.hh.
View newest version in sPHENIX GitHub at line 44 of file CCalHall.hh
References dy_2Hall.
Referenced by CCalG4Hall::constructIn().
G4String CCalHall::getMaterial () const inline
Definition at line 43 of file CCalHall.hh.
View newest version in sPHENIX GitHub at line 43 of file CCalHall.hh
References genMaterial.
Referenced by CCalG4Hall::constructIn().
G4int CCalHall::readFile () protected virtual
Implements CCalDetector.
Definition at line 44 of file CCalHall.cc.
View newest version in sPHENIX GitHub at line 44 of file CCalHall.cc
References dx_2Hall, dy_2Hall, CCalDetector::File(), findDO(), G4cout, G4endl, genMaterial, jump(), openGeomFile(), CCalDetector::pathName, readName(), and tab().
Member Data Documentation
G4double CCalHall::dx_2Hall private
Definition at line 54 of file CCalHall.hh.
View newest version in sPHENIX GitHub at line 54 of file CCalHall.hh
Referenced by getDx_2Hall(), and readFile().
G4double CCalHall::dy_2Hall private
Definition at line 53 of file CCalHall.hh.
View newest version in sPHENIX GitHub at line 53 of file CCalHall.hh
Referenced by getDy_2Hall(), and readFile().
G4String CCalHall::genMaterial private
Definition at line 52 of file CCalHall.hh.
View newest version in sPHENIX GitHub at line 52 of file CCalHall.hh
Referenced by getMaterial(), and readFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalHall.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalHall.cc