ECCE @ EIC Software: G4DeexPrecoParameters Class Reference
G4DeexPrecoParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4DeexPrecoParameters.hh>
Public Member Functions
G4DeexPrecoParameters ()
~G4DeexPrecoParameters ()
void SetDefaults ()
std::ostream & StreamInfo (std::ostream &os) const
void Dump () const
G4double GetLevelDensity () const
G4double GetR0 () const
G4double GetTransitionsR0 () const
G4double GetFBUEnergyLimit () const
G4double GetFermiEnergy () const
G4double GetPrecoLowEnergy () const
G4double GetPrecoHighEnergy () const
G4double GetPhenoFactor () const
G4double GetMinExcitation () const
G4double GetMaxLifeTime () const
G4double GetMinExPerNucleounForMF () const
G4int GetInternalConversionID () const
G4int GetMinZForPreco () const
G4int GetMinAForPreco () const
G4int GetPrecoModelType () const
G4int GetDeexModelType () const
G4int GetTwoJMAX () const
G4int GetUploadZ () const
G4int GetVerbose () const
G4bool NeverGoBack () const
G4bool UseSoftCutoff () const
G4bool UseCEM () const
G4bool UseGNASH () const
G4bool UseHETC () const
G4bool UseAngularGen () const
G4bool PrecoDummy () const
G4bool CorrelatedGamma () const
G4bool GetInternalConversionFlag () const
G4bool GetLevelDensityFlag () const
G4bool GetDiscreteExcitationFlag () const
G4bool StoreICLevelData () const
G4DeexChannelType GetDeexChannelsType () const
void SetLevelDensity (G4double)
void SetR0 (G4double)
void SetTransitionsR0 (G4double)
void SetFBUEnergyLimit (G4double)
void SetFermiEnergy (G4double)
void SetPrecoLowEnergy (G4double)
void SetPrecoHighEnergy (G4double)
void SetPhenoFactor (G4double)
void SetMinExcitation (G4double)
void SetMaxLifeTime (G4double)
void SetMinExPerNucleounForMF (G4double)
void SetMinEForMultiFrag (G4double)
void SetMinZForPreco (G4int)
void SetMinAForPreco (G4int)
void SetPrecoModelType (G4int)
void SetDeexModelType (G4int)
void SetTwoJMAX (G4int)
void SetUploadZ (G4int)
void SetVerbose (G4int)
void SetNeverGoBack (G4bool)
void SetUseSoftCutoff (G4bool)
void SetUseCEM (G4bool)
void SetUseGNASH (G4bool)
void SetUseHETC (G4bool)
void SetUseAngularGen (G4bool)
void SetPrecoDummy (G4bool)
void SetCorrelatedGamma (G4bool)
void SetStoreICLevelData (G4bool)
void SetStoreAllLevels (G4bool)
void SetInternalConversionFlag (G4bool)
void SetLevelDensityFlag (G4bool)
void SetDiscreteExcitationFlag (G4bool)
void SetDeexChannelsType (G4DeexChannelType)
void SetUseFilesNEW (G4bool)
Private Member Functions
G4bool IsLocked () const
G4DeexPrecoParameters (const G4DeexPrecoParameters &right)=delete
const G4DeexPrecoParameters & operator= (const G4DeexPrecoParameters &right)=delete
G4bool operator== (const G4DeexPrecoParameters &right) const =delete
G4bool operator!= (const G4DeexPrecoParameters &right) const =delete
Private Attributes
G4DeexParametersMessenger * theMessenger
G4StateManager * fStateManager
G4double fLevelDensity
G4double fR0
G4double fTransitionsR0
G4double fFBUEnergyLimit
G4double fFermiEnergy
G4double fPrecoLowEnergy
G4double fPrecoHighEnergy
G4double fPhenoFactor
G4double fMinExcitation
G4double fMaxLifeTime
G4double fMinExPerNucleounForMF
G4int fPrecoType
G4int fDeexType
G4int fInternalConversionID
G4int fTwoJMAX
G4int fMinZForPreco
G4int fMinAForPreco
G4int fMaxZ
G4int fVerbose
G4bool fNeverGoBack
G4bool fUseSoftCutoff
G4bool fUseCEM
G4bool fUseGNASH
G4bool fUseHETC
G4bool fUseAngularGen
G4bool fPrecoDummy
G4bool fCorrelatedGamma
G4bool fStoreAllLevels
G4bool fInternalConversion
G4bool fLD
G4bool fFD
G4DeexChannelType fDeexChannelType
Friends
std::ostream & operator<< (std::ostream &os, const G4DeexPrecoParameters &)
Detailed Description
Definition at line 51 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 51 of file G4DeexPrecoParameters.hh
Constructor & Destructor Documentation
G4DeexPrecoParameters::G4DeexPrecoParameters () explicit
Definition at line 43 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 43 of file G4DeexPrecoParameters.cc
References SetDefaults().
G4DeexPrecoParameters::~G4DeexPrecoParameters ()
Definition at line 48 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 48 of file G4DeexPrecoParameters.cc
References theMessenger.
G4DeexPrecoParameters::G4DeexPrecoParameters (const G4DeexPrecoParameters & right) private delete
Member Function Documentation
G4bool G4DeexPrecoParameters::CorrelatedGamma () const inline
Definition at line 416 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 416 of file G4DeexPrecoParameters.hh
References fCorrelatedGamma.
Referenced by G4PhotonEvaporation::Initialise(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
void G4DeexPrecoParameters::Dump () const
Definition at line 335 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 335 of file G4DeexPrecoParameters.cc
References G4cout, G4Threading::IsMasterThread(), and StreamInfo().
Referenced by G4ExcitationHandler::Initialise().
G4DeexChannelType G4DeexPrecoParameters::GetDeexChannelsType () const inline
Definition at line 441 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 441 of file G4DeexPrecoParameters.hh
References fDeexChannelType.
Referenced by G4Evaporation::InitialiseChannels().
G4int G4DeexPrecoParameters::GetDeexModelType () const inline
Definition at line 361 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 361 of file G4DeexPrecoParameters.hh
References fDeexType.
Referenced by G4VEmissionProbability::Initialise().
G4bool G4DeexPrecoParameters::GetDiscreteExcitationFlag () const inline
Definition at line 436 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 436 of file G4DeexPrecoParameters.hh
References fFD.
Referenced by G4VEmissionProbability::Initialise().
G4double G4DeexPrecoParameters::GetFBUEnergyLimit () const inline
Definition at line 301 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 301 of file G4DeexPrecoParameters.hh
References fFBUEnergyLimit.
Referenced by G4FermiFragmentsPoolVI::G4FermiFragmentsPoolVI().
G4double G4DeexPrecoParameters::GetFermiEnergy () const inline
Definition at line 306 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 306 of file G4DeexPrecoParameters.hh
References fFermiEnergy.
Referenced by G4PreCompoundEmission::G4PreCompoundEmission(), and G4PreCompoundTransitions::G4PreCompoundTransitions().
G4bool G4DeexPrecoParameters::GetInternalConversionFlag () const inline
Definition at line 426 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 426 of file G4DeexPrecoParameters.hh
References fInternalConversion.
Referenced by G4PhotonEvaporation::Initialise(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4int G4DeexPrecoParameters::GetInternalConversionID () const inline
Definition at line 341 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 341 of file G4DeexPrecoParameters.hh
References fInternalConversionID.
Referenced by G4NeutronRadCapture::InitialiseModel().
G4double G4DeexPrecoParameters::GetLevelDensity () const inline
Definition at line 286 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 286 of file G4DeexPrecoParameters.hh
References fLevelDensity.
Referenced by G4NuclearLevelData::GetLevelDensity().
G4bool G4DeexPrecoParameters::GetLevelDensityFlag () const inline
Definition at line 431 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 431 of file G4DeexPrecoParameters.hh
References fLD.
Referenced by G4NuclearLevelData::GetLevelDensity(), and G4NuclearLevelData::GetPairingCorrection().
G4double G4DeexPrecoParameters::GetMaxLifeTime () const inline
Definition at line 331 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 331 of file G4DeexPrecoParameters.hh
References fMaxLifeTime.
Referenced by G4FermiFragmentsPoolVI::G4FermiFragmentsPoolVI(), G4PhotonEvaporation::Initialise(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4int G4DeexPrecoParameters::GetMinAForPreco () const inline
Definition at line 351 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 351 of file G4DeexPrecoParameters.hh
References fMinAForPreco.
Referenced by G4PreCompoundModel::InitialiseModel().
G4double G4DeexPrecoParameters::GetMinExcitation () const inline
Definition at line 326 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 326 of file G4DeexPrecoParameters.hh
References fMinExcitation.
Referenced by G4FermiFragmentsPoolVI::G4FermiFragmentsPoolVI(), G4PhotonEvaporation::Initialise(), G4Evaporation::InitialiseChannels(), and G4NeutronRadCapture::InitialiseModel().
G4double G4DeexPrecoParameters::GetMinExPerNucleounForMF () const inline
Definition at line 336 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 336 of file G4DeexPrecoParameters.hh
References fMinExPerNucleounForMF.
G4int G4DeexPrecoParameters::GetMinZForPreco () const inline
Definition at line 346 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 346 of file G4DeexPrecoParameters.hh
References fMinZForPreco.
Referenced by G4PreCompoundModel::InitialiseModel().
G4double G4DeexPrecoParameters::GetPhenoFactor () const inline
Definition at line 321 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 321 of file G4DeexPrecoParameters.hh
References fPhenoFactor.
G4double G4DeexPrecoParameters::GetPrecoHighEnergy () const inline
Definition at line 316 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 316 of file G4DeexPrecoParameters.hh
References fPrecoHighEnergy.
Referenced by G4PreCompoundModel::InitialiseModel().
G4double G4DeexPrecoParameters::GetPrecoLowEnergy () const inline
Definition at line 311 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 311 of file G4DeexPrecoParameters.hh
References fPrecoLowEnergy.
Referenced by G4PreCompoundModel::InitialiseModel().
G4int G4DeexPrecoParameters::GetPrecoModelType () const inline
Definition at line 356 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 356 of file G4DeexPrecoParameters.hh
References fPrecoType.
Referenced by G4PreCompoundModel::InitialiseModel().
G4double G4DeexPrecoParameters::GetR0 () const inline
Definition at line 291 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 291 of file G4DeexPrecoParameters.hh
References fR0.
Referenced by G4HETCFragment::G4HETCFragment(), G4PreCompoundIon::G4PreCompoundIon(), and G4PreCompoundFragment::GetOpt0().
G4double G4DeexPrecoParameters::GetTransitionsR0 () const inline
Definition at line 296 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 296 of file G4DeexPrecoParameters.hh
References fTransitionsR0.
Referenced by G4PreCompoundTransitions::G4PreCompoundTransitions().
G4int G4DeexPrecoParameters::GetTwoJMAX () const inline
Definition at line 366 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 366 of file G4DeexPrecoParameters.hh
References fTwoJMAX.
Referenced by G4PhotonEvaporation::Initialise(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
G4int G4DeexPrecoParameters::GetUploadZ () const inline
Definition at line 371 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 371 of file G4DeexPrecoParameters.hh
References fMaxZ.
G4int G4DeexPrecoParameters::GetVerbose () const inline
Definition at line 376 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 376 of file G4DeexPrecoParameters.hh
References fVerbose.
Referenced by G4VEmissionProbability::Initialise(), G4PhotonEvaporation::Initialise(), and G4Evaporation::InitialiseChannels().
G4bool G4DeexPrecoParameters::IsLocked () const private
Definition at line 345 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 345 of file G4DeexPrecoParameters.cc
References fStateManager, G4State_PreInit, G4StateManager::GetCurrentState(), and G4Threading::IsMasterThread().
Referenced by SetCorrelatedGamma(), SetDeexChannelsType(), SetDeexModelType(), SetDiscreteExcitationFlag(), SetFBUEnergyLimit(), SetFermiEnergy(), SetInternalConversionFlag(), SetLevelDensity(), SetLevelDensityFlag(), SetMaxLifeTime(), SetMinAForPreco(), SetMinExcitation(), SetMinExPerNucleounForMF(), SetMinZForPreco(), SetNeverGoBack(), SetPhenoFactor(), SetPrecoDummy(), SetPrecoHighEnergy(), SetPrecoLowEnergy(), SetPrecoModelType(), SetR0(), SetStoreICLevelData(), SetTransitionsR0(), SetTwoJMAX(), SetUploadZ(), SetUseAngularGen(), SetUseCEM(), SetUseGNASH(), SetUseHETC(), SetUseSoftCutoff(), and SetVerbose().
G4bool G4DeexPrecoParameters::NeverGoBack () const inline
Definition at line 381 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 381 of file G4DeexPrecoParameters.hh
References fNeverGoBack.
Referenced by G4PreCompoundModel::InitialiseModel().
G4bool G4DeexPrecoParameters::operator!= (const G4DeexPrecoParameters & right) const private delete
const G4DeexPrecoParameters& G4DeexPrecoParameters::operator= (const G4DeexPrecoParameters & right) private delete
G4bool G4DeexPrecoParameters::operator== (const G4DeexPrecoParameters & right) const private delete
G4bool G4DeexPrecoParameters::PrecoDummy () const inline
Definition at line 411 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 411 of file G4DeexPrecoParameters.hh
References fPrecoDummy.
Referenced by G4PreCompoundModel::InitialiseModel().
void G4DeexPrecoParameters::SetCorrelatedGamma (G4bool val)
Definition at line 250 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 250 of file G4DeexPrecoParameters.cc
References fCorrelatedGamma, and IsLocked().
Referenced by G4DeexParametersMessenger::SetNewValue().
void G4DeexPrecoParameters::SetDeexChannelsType (G4DeexChannelType val)
Definition at line 285 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 285 of file G4DeexPrecoParameters.cc
References fDeexChannelType, and IsLocked().
Referenced by G4IonINCLXXPhysics::G4IonINCLXXPhysics(), G4IonPhysicsPHP::G4IonPhysicsPHP(), G4IonPhysicsXS::G4IonPhysicsXS(), and G4IonQMDPhysics::G4IonQMDPhysics().
void G4DeexPrecoParameters::SetDeexModelType (G4int n)
Definition at line 183 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 183 of file G4DeexPrecoParameters.cc
References fDeexType, IsLocked(), and n.
void G4DeexPrecoParameters::SetDefaults ()
Definition at line 53 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 53 of file G4DeexPrecoParameters.cc
References CLHEP::eV, fCombined, fCorrelatedGamma, fDeexChannelType, fDeexType, CLHEP::fermi, fFBUEnergyLimit, fFD, fFermiEnergy, fInternalConversion, fInternalConversionID, fLD, fLevelDensity, fMaxLifeTime, fMaxZ, fMinAForPreco, fMinExcitation, fMinExPerNucleounForMF, fMinZForPreco, fNeverGoBack, fPhenoFactor, fPrecoDummy, fPrecoHighEnergy, fPrecoLowEnergy, fPrecoType, fR0, fStateManager, fStoreAllLevels, fTransitionsR0, fTwoJMAX, fUseAngularGen, fUseCEM, fUseGNASH, fUseHETC, fUseSoftCutoff, fVerbose, G4MUTEXLOCK, G4MUTEXUNLOCK, G4StateManager::GetStateManager(), CLHEP::GeV, CLHEP::MeV, CLHEP::microsecond, G4PhysicsModelCatalog::Register(), and theMessenger.
Referenced by G4DeexPrecoParameters().
void G4DeexPrecoParameters::SetDiscreteExcitationFlag (G4bool val)
Definition at line 279 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 279 of file G4DeexPrecoParameters.cc
References fFD, and IsLocked().
void G4DeexPrecoParameters::SetFBUEnergyLimit (G4double val)
Definition at line 117 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 117 of file G4DeexPrecoParameters.cc
References fFBUEnergyLimit, and IsLocked().
void G4DeexPrecoParameters::SetFermiEnergy (G4double val)
Definition at line 123 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 123 of file G4DeexPrecoParameters.cc
References fFermiEnergy, and IsLocked().
void G4DeexPrecoParameters::SetInternalConversionFlag (G4bool val)
Definition at line 267 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 267 of file G4DeexPrecoParameters.cc
References fInternalConversion, and IsLocked().
Referenced by G4DeexParametersMessenger::SetNewValue().
void G4DeexPrecoParameters::SetLevelDensity (G4double val)
Definition at line 99 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 99 of file G4DeexPrecoParameters.cc
References fLevelDensity, IsLocked(), and CLHEP::MeV.
void G4DeexPrecoParameters::SetLevelDensityFlag (G4bool val)
Definition at line 273 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 273 of file G4DeexPrecoParameters.cc
References fLD, and IsLocked().
void G4DeexPrecoParameters::SetMaxLifeTime (G4double val)
Definition at line 153 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 153 of file G4DeexPrecoParameters.cc
References fMaxLifeTime, and IsLocked().
Referenced by BiasedRDPhysics::BiasedRDPhysics(), LBE::ConstructGeneral(), DMXPhysicsList::DMXPhysicsList(), and G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics().
void G4DeexPrecoParameters::SetMinAForPreco (G4int n)
Definition at line 171 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 171 of file G4DeexPrecoParameters.cc
References fMinAForPreco, IsLocked(), and n.
void G4DeexPrecoParameters::SetMinEForMultiFrag (G4double)
void G4DeexPrecoParameters::SetMinExcitation (G4double val)
Definition at line 147 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 147 of file G4DeexPrecoParameters.cc
References fMinExcitation, and IsLocked().
void G4DeexPrecoParameters::SetMinExPerNucleounForMF (G4double val)
Definition at line 159 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 159 of file G4DeexPrecoParameters.cc
References fMinExPerNucleounForMF, and IsLocked().
void G4DeexPrecoParameters::SetMinZForPreco (G4int n)
Definition at line 165 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 165 of file G4DeexPrecoParameters.cc
References fMinZForPreco, IsLocked(), and n.
void G4DeexPrecoParameters::SetNeverGoBack (G4bool val)
Definition at line 207 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 207 of file G4DeexPrecoParameters.cc
References fNeverGoBack, and IsLocked().
void G4DeexPrecoParameters::SetPhenoFactor (G4double val)
Definition at line 141 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 141 of file G4DeexPrecoParameters.cc
References fPhenoFactor, and IsLocked().
void G4DeexPrecoParameters::SetPrecoDummy (G4bool val)
Definition at line 243 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 243 of file G4DeexPrecoParameters.cc
References fDeexChannelType, fDummy, fPrecoDummy, and IsLocked().
void G4DeexPrecoParameters::SetPrecoHighEnergy (G4double val)
Definition at line 135 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 135 of file G4DeexPrecoParameters.cc
References fPrecoHighEnergy, and IsLocked().
void G4DeexPrecoParameters::SetPrecoLowEnergy (G4double val)
Definition at line 129 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 129 of file G4DeexPrecoParameters.cc
References fPrecoLowEnergy, and IsLocked().
void G4DeexPrecoParameters::SetPrecoModelType (G4int n)
Definition at line 177 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 177 of file G4DeexPrecoParameters.cc
References fPrecoType, IsLocked(), and n.
void G4DeexPrecoParameters::SetR0 (G4double val)
Definition at line 105 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 105 of file G4DeexPrecoParameters.cc
References fR0, and IsLocked().
void G4DeexPrecoParameters::SetStoreAllLevels (G4bool val)
Definition at line 262 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 262 of file G4DeexPrecoParameters.cc
References SetStoreICLevelData().
Referenced by LBE::ConstructGeneral().
void G4DeexPrecoParameters::SetStoreICLevelData (G4bool val)
Definition at line 256 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 256 of file G4DeexPrecoParameters.cc
References fStoreAllLevels, and IsLocked().
Referenced by BiasedRDPhysics::BiasedRDPhysics(), DMXPhysicsList::DMXPhysicsList(), G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics(), G4DeexParametersMessenger::SetNewValue(), and SetStoreAllLevels().
void G4DeexPrecoParameters::SetTransitionsR0 (G4double val)
Definition at line 111 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 111 of file G4DeexPrecoParameters.cc
References fTransitionsR0, and IsLocked().
void G4DeexPrecoParameters::SetTwoJMAX (G4int n)
Definition at line 189 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 189 of file G4DeexPrecoParameters.cc
References fTwoJMAX, IsLocked(), and n.
Referenced by G4DeexParametersMessenger::SetNewValue().
void G4DeexPrecoParameters::SetUploadZ (G4int z)
Definition at line 195 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 195 of file G4DeexPrecoParameters.cc
References fMaxZ, IsLocked(), and z.
Referenced by G4DeexParametersMessenger::SetNewValue().
void G4DeexPrecoParameters::SetUseAngularGen (G4bool val)
Definition at line 237 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 237 of file G4DeexPrecoParameters.cc
References fUseAngularGen, and IsLocked().
void G4DeexPrecoParameters::SetUseCEM (G4bool val)
Definition at line 219 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 219 of file G4DeexPrecoParameters.cc
References fUseCEM, and IsLocked().
void G4DeexPrecoParameters::SetUseFilesNEW (G4bool) inline
Definition at line 203 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 203 of file G4DeexPrecoParameters.hh
void G4DeexPrecoParameters::SetUseGNASH (G4bool val)
Definition at line 225 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 225 of file G4DeexPrecoParameters.cc
References fUseGNASH, and IsLocked().
void G4DeexPrecoParameters::SetUseHETC (G4bool val)
Definition at line 231 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 231 of file G4DeexPrecoParameters.cc
References fUseHETC, and IsLocked().
void G4DeexPrecoParameters::SetUseSoftCutoff (G4bool val)
Definition at line 213 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 213 of file G4DeexPrecoParameters.cc
References fUseSoftCutoff, and IsLocked().
void G4DeexPrecoParameters::SetVerbose (G4int n)
Definition at line 201 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 201 of file G4DeexPrecoParameters.cc
References fVerbose, IsLocked(), and n.
Referenced by G4DeexParametersMessenger::SetNewValue().
G4bool G4DeexPrecoParameters::StoreICLevelData () const inline
Definition at line 421 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 421 of file G4DeexPrecoParameters.hh
References fStoreAllLevels.
Referenced by G4LevelReader::LevelManager(), G4RadioactiveDecayBase::StreamInfo(), and G4RadioactiveDecay::StreamInfo().
std::ostream & G4DeexPrecoParameters::StreamInfo (std::ostream & os) const
Definition at line 291 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 291 of file G4DeexPrecoParameters.cc
References fCorrelatedGamma, fDeexChannelType, fDeexType, fFBUEnergyLimit, fFD, fInternalConversion, fInternalConversionID, fLD, fLevelDensity, fMaxLifeTime, fMaxZ, fMinExcitation, fMinExPerNucleounForMF, fPrecoDummy, fPrecoHighEnergy, fPrecoLowEnergy, fPrecoType, fStoreAllLevels, fTwoJMAX, incremental_prev_tag::idx, CLHEP::keV, CLHEP::MeV, CLHEP::ns, and CLHEP::prec.
Referenced by Dump(), and operator<<().
G4bool G4DeexPrecoParameters::UseAngularGen () const inline
Definition at line 406 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 406 of file G4DeexPrecoParameters.hh
References fUseAngularGen.
Referenced by G4PreCompoundEmission::G4PreCompoundEmission().
G4bool G4DeexPrecoParameters::UseCEM () const inline
Definition at line 391 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 391 of file G4DeexPrecoParameters.hh
References fUseCEM.
Referenced by G4PreCompoundModel::InitialiseModel().
G4bool G4DeexPrecoParameters::UseGNASH () const inline
Definition at line 396 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 396 of file G4DeexPrecoParameters.hh
References fUseGNASH.
Referenced by G4PreCompoundModel::InitialiseModel().
G4bool G4DeexPrecoParameters::UseHETC () const inline
Definition at line 401 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 401 of file G4DeexPrecoParameters.hh
References fUseHETC.
Referenced by G4PreCompoundModel::InitialiseModel().
G4bool G4DeexPrecoParameters::UseSoftCutoff () const inline
Definition at line 386 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 386 of file G4DeexPrecoParameters.hh
References fUseSoftCutoff.
Referenced by G4PreCompoundModel::InitialiseModel().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4DeexPrecoParameters & par) friend
Definition at line 340 of file G4DeexPrecoParameters.cc.
View newest version in sPHENIX GitHub at line 340 of file G4DeexPrecoParameters.cc
Member Data Documentation
G4bool G4DeexPrecoParameters::fCorrelatedGamma private
Definition at line 272 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 272 of file G4DeexPrecoParameters.hh
Referenced by CorrelatedGamma(), SetCorrelatedGamma(), SetDefaults(), and StreamInfo().
G4DeexChannelType G4DeexPrecoParameters::fDeexChannelType private
Definition at line 279 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 279 of file G4DeexPrecoParameters.hh
Referenced by GetDeexChannelsType(), SetDeexChannelsType(), SetDefaults(), SetPrecoDummy(), and StreamInfo().
G4int G4DeexPrecoParameters::fDeexType private
Definition at line 249 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 249 of file G4DeexPrecoParameters.hh
Referenced by GetDeexModelType(), SetDeexModelType(), SetDefaults(), and StreamInfo().
G4double G4DeexPrecoParameters::fFBUEnergyLimit private
Definition at line 228 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 228 of file G4DeexPrecoParameters.hh
Referenced by GetFBUEnergyLimit(), SetDefaults(), SetFBUEnergyLimit(), and StreamInfo().
G4bool G4DeexPrecoParameters::fFD private
Definition at line 276 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 276 of file G4DeexPrecoParameters.hh
Referenced by GetDiscreteExcitationFlag(), SetDefaults(), SetDiscreteExcitationFlag(), and StreamInfo().
G4double G4DeexPrecoParameters::fFermiEnergy private
Definition at line 231 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 231 of file G4DeexPrecoParameters.hh
Referenced by GetFermiEnergy(), SetDefaults(), and SetFermiEnergy().
G4bool G4DeexPrecoParameters::fInternalConversion private
Definition at line 274 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 274 of file G4DeexPrecoParameters.hh
Referenced by GetInternalConversionFlag(), SetDefaults(), SetInternalConversionFlag(), and StreamInfo().
G4int G4DeexPrecoParameters::fInternalConversionID private
Definition at line 252 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 252 of file G4DeexPrecoParameters.hh
Referenced by GetInternalConversionID(), SetDefaults(), and StreamInfo().
G4bool G4DeexPrecoParameters::fLD private
Definition at line 275 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 275 of file G4DeexPrecoParameters.hh
Referenced by GetLevelDensityFlag(), SetDefaults(), SetLevelDensityFlag(), and StreamInfo().
G4double G4DeexPrecoParameters::fLevelDensity private
Definition at line 219 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 219 of file G4DeexPrecoParameters.hh
Referenced by GetLevelDensity(), SetDefaults(), SetLevelDensity(), and StreamInfo().
G4double G4DeexPrecoParameters::fMaxLifeTime private
Definition at line 242 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 242 of file G4DeexPrecoParameters.hh
Referenced by GetMaxLifeTime(), SetDefaults(), SetMaxLifeTime(), and StreamInfo().
G4int G4DeexPrecoParameters::fMaxZ private
Definition at line 259 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 259 of file G4DeexPrecoParameters.hh
Referenced by GetUploadZ(), SetDefaults(), SetUploadZ(), and StreamInfo().
G4int G4DeexPrecoParameters::fMinAForPreco private
Definition at line 257 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 257 of file G4DeexPrecoParameters.hh
Referenced by GetMinAForPreco(), SetDefaults(), and SetMinAForPreco().
G4double G4DeexPrecoParameters::fMinExcitation private
Definition at line 241 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 241 of file G4DeexPrecoParameters.hh
Referenced by GetMinExcitation(), SetDefaults(), SetMinExcitation(), and StreamInfo().
G4double G4DeexPrecoParameters::fMinExPerNucleounForMF private
Definition at line 245 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 245 of file G4DeexPrecoParameters.hh
Referenced by GetMinExPerNucleounForMF(), SetDefaults(), SetMinExPerNucleounForMF(), and StreamInfo().
G4int G4DeexPrecoParameters::fMinZForPreco private
Definition at line 256 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 256 of file G4DeexPrecoParameters.hh
Referenced by GetMinZForPreco(), SetDefaults(), and SetMinZForPreco().
G4bool G4DeexPrecoParameters::fNeverGoBack private
Definition at line 263 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 263 of file G4DeexPrecoParameters.hh
Referenced by NeverGoBack(), SetDefaults(), and SetNeverGoBack().
G4double G4DeexPrecoParameters::fPhenoFactor private
Definition at line 238 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 238 of file G4DeexPrecoParameters.hh
Referenced by GetPhenoFactor(), SetDefaults(), and SetPhenoFactor().
G4bool G4DeexPrecoParameters::fPrecoDummy private
Definition at line 269 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 269 of file G4DeexPrecoParameters.hh
Referenced by PrecoDummy(), SetDefaults(), SetPrecoDummy(), and StreamInfo().
G4double G4DeexPrecoParameters::fPrecoHighEnergy private
Definition at line 235 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 235 of file G4DeexPrecoParameters.hh
Referenced by GetPrecoHighEnergy(), SetDefaults(), SetPrecoHighEnergy(), and StreamInfo().
G4double G4DeexPrecoParameters::fPrecoLowEnergy private
Definition at line 234 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 234 of file G4DeexPrecoParameters.hh
Referenced by GetPrecoLowEnergy(), SetDefaults(), SetPrecoLowEnergy(), and StreamInfo().
G4int G4DeexPrecoParameters::fPrecoType private
Definition at line 248 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 248 of file G4DeexPrecoParameters.hh
Referenced by GetPrecoModelType(), SetDefaults(), SetPrecoModelType(), and StreamInfo().
G4double G4DeexPrecoParameters::fR0 private
Definition at line 222 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 222 of file G4DeexPrecoParameters.hh
Referenced by GetR0(), SetDefaults(), and SetR0().
G4StateManager* G4DeexPrecoParameters::fStateManager private
Definition at line 216 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 216 of file G4DeexPrecoParameters.hh
Referenced by IsLocked(), and SetDefaults().
G4bool G4DeexPrecoParameters::fStoreAllLevels private
Definition at line 273 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 273 of file G4DeexPrecoParameters.hh
Referenced by SetDefaults(), SetStoreICLevelData(), StoreICLevelData(), and StreamInfo().
G4double G4DeexPrecoParameters::fTransitionsR0 private
Definition at line 225 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 225 of file G4DeexPrecoParameters.hh
Referenced by GetTransitionsR0(), SetDefaults(), and SetTransitionsR0().
G4int G4DeexPrecoParameters::fTwoJMAX private
Definition at line 253 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 253 of file G4DeexPrecoParameters.hh
Referenced by GetTwoJMAX(), SetDefaults(), SetTwoJMAX(), and StreamInfo().
G4bool G4DeexPrecoParameters::fUseAngularGen private
Definition at line 268 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 268 of file G4DeexPrecoParameters.hh
Referenced by SetDefaults(), SetUseAngularGen(), and UseAngularGen().
G4bool G4DeexPrecoParameters::fUseCEM private
Definition at line 265 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 265 of file G4DeexPrecoParameters.hh
Referenced by SetDefaults(), SetUseCEM(), and UseCEM().
G4bool G4DeexPrecoParameters::fUseGNASH private
Definition at line 266 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 266 of file G4DeexPrecoParameters.hh
Referenced by SetDefaults(), SetUseGNASH(), and UseGNASH().
G4bool G4DeexPrecoParameters::fUseHETC private
Definition at line 267 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 267 of file G4DeexPrecoParameters.hh
Referenced by SetDefaults(), SetUseHETC(), and UseHETC().
G4bool G4DeexPrecoParameters::fUseSoftCutoff private
Definition at line 264 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 264 of file G4DeexPrecoParameters.hh
Referenced by SetDefaults(), SetUseSoftCutoff(), and UseSoftCutoff().
G4int G4DeexPrecoParameters::fVerbose private
Definition at line 260 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 260 of file G4DeexPrecoParameters.hh
Referenced by GetVerbose(), SetDefaults(), and SetVerbose().
G4DeexParametersMessenger* G4DeexPrecoParameters::theMessenger private
Definition at line 215 of file G4DeexPrecoParameters.hh.
View newest version in sPHENIX GitHub at line 215 of file G4DeexPrecoParameters.hh
Referenced by SetDefaults(), and ~G4DeexPrecoParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4DeexPrecoParameters.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/src/G4DeexPrecoParameters.cc