ECCE @ EIC Software: GB02BOptrMultiParticleForceCollision Class Reference
GB02BOptrMultiParticleForceCollision Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB02/include/GB02BOptrMultiParticleForceCollision.hh>
Public Member Functions
GB02BOptrMultiParticleForceCollision ()
virtual ~GB02BOptrMultiParticleForceCollision ()
void AddParticle (G4String particleName)
virtual void StartTracking (const G4Track *track) final
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartRun ()
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final
void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced) final
void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced) final
void ExitBiasing (const G4Track *, const G4BiasingProcessInterface *) final
Private Attributes
std::map< const
G4ParticleDefinition
*, G4BOptrForceCollision * > fBOptrForParticle
std::vector< const
G4ParticleDefinition * > fParticlesToBias
G4BOptrForceCollision * fCurrentOperator
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Detailed Description
Definition at line 38 of file GB02BOptrMultiParticleForceCollision.hh.
View newest version in sPHENIX GitHub at line 38 of file GB02BOptrMultiParticleForceCollision.hh
Constructor & Destructor Documentation
GB02BOptrMultiParticleForceCollision::GB02BOptrMultiParticleForceCollision ()
Definition at line 38 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 38 of file GB02BOptrMultiParticleForceCollision.cc
virtual GB02BOptrMultiParticleForceCollision::~GB02BOptrMultiParticleForceCollision () inline virtual
Definition at line 41 of file GB02BOptrMultiParticleForceCollision.hh.
View newest version in sPHENIX GitHub at line 41 of file GB02BOptrMultiParticleForceCollision.hh
Member Function Documentation
void GB02BOptrMultiParticleForceCollision::AddParticle (G4String particleName)
Definition at line 45 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 45 of file GB02BOptrMultiParticleForceCollision.cc
References fBOptrForParticle, G4ParticleTable::FindParticle(), fParticlesToBias, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), JustWarning, and particle.
Referenced by GB02DetectorConstruction::ConstructSDandField().
void GB02BOptrMultiParticleForceCollision::ExitBiasing (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final private virtual
Reimplemented from G4VBiasingOperator.
Definition at line 154 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 154 of file GB02BOptrMultiParticleForceCollision.cc
References G4VBiasingOperator::ExitingBiasing(), and fCurrentOperator.
void GB02BOptrMultiParticleForceCollision::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * operationApplied, const G4VParticleChange * particleChangeProduced) final private virtual
Reimplemented from G4VBiasingOperator.
Definition at line 119 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 119 of file GB02BOptrMultiParticleForceCollision.cc
References fCurrentOperator, and G4VBiasingOperator::ReportOperationApplied().
void GB02BOptrMultiParticleForceCollision::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation * finalStateOperationApplied, const G4VParticleChange * particleChangeProduced) final private virtual
Reimplemented from G4VBiasingOperator.
Definition at line 135 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 135 of file GB02BOptrMultiParticleForceCollision.cc
References fCurrentOperator, and G4VBiasingOperator::ReportOperationApplied().
G4VBiasingOperation * GB02BOptrMultiParticleForceCollision::ProposeFinalStateBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final private virtual
Implements G4VBiasingOperator.
Definition at line 96 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 96 of file GB02BOptrMultiParticleForceCollision.cc
References fCurrentOperator, and G4VBiasingOperator::GetProposedFinalStateBiasingOperation().
G4VBiasingOperation * GB02BOptrMultiParticleForceCollision::ProposeNonPhysicsBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final private virtual
Implements G4VBiasingOperator.
Definition at line 84 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 84 of file GB02BOptrMultiParticleForceCollision.cc
References fCurrentOperator, and G4VBiasingOperator::GetProposedNonPhysicsBiasingOperation().
G4VBiasingOperation * GB02BOptrMultiParticleForceCollision::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final private virtual
Implements G4VBiasingOperator.
Definition at line 72 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 72 of file GB02BOptrMultiParticleForceCollision.cc
References fCurrentOperator, and G4VBiasingOperator::GetProposedOccurenceBiasingOperation().
void GB02BOptrMultiParticleForceCollision::StartTracking (const G4Track * track) final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 106 of file GB02BOptrMultiParticleForceCollision.cc.
View newest version in sPHENIX GitHub at line 106 of file GB02BOptrMultiParticleForceCollision.cc
References fBOptrForParticle, fCurrentOperator, G4Track::GetParticleDefinition(), and it.
Member Data Documentation
std::map< const G4ParticleDefinition*, G4BOptrForceCollision* > GB02BOptrMultiParticleForceCollision::fBOptrForParticle private
Definition at line 86 of file GB02BOptrMultiParticleForceCollision.hh.
View newest version in sPHENIX GitHub at line 86 of file GB02BOptrMultiParticleForceCollision.hh
Referenced by AddParticle(), and StartTracking().
G4BOptrForceCollision* GB02BOptrMultiParticleForceCollision::fCurrentOperator private
Definition at line 88 of file GB02BOptrMultiParticleForceCollision.hh.
View newest version in sPHENIX GitHub at line 88 of file GB02BOptrMultiParticleForceCollision.hh
Referenced by ExitBiasing(), OperationApplied(), ProposeFinalStateBiasingOperation(), ProposeNonPhysicsBiasingOperation(), ProposeOccurenceBiasingOperation(), and StartTracking().
std::vector< const G4ParticleDefinition* > GB02BOptrMultiParticleForceCollision::fParticlesToBias private
Definition at line 87 of file GB02BOptrMultiParticleForceCollision.hh.
View newest version in sPHENIX GitHub at line 87 of file GB02BOptrMultiParticleForceCollision.hh
Referenced by AddParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB02/include/GB02BOptrMultiParticleForceCollision.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB02/src/GB02BOptrMultiParticleForceCollision.cc