ECCE @ EIC Software: RE04Trajectory Class Reference
RE04Trajectory Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/include/RE04Trajectory.hh>
Public Member Functions
RE04Trajectory ()
RE04Trajectory (const G4Track *aTrack)
RE04Trajectory (RE04Trajectory &)
virtual ~RE04Trajectory ()
void * operator new (size_t)
void operator delete (void *)
int operator== (const RE04Trajectory &right) const
virtual G4int GetTrackID () const
virtual G4int GetParentID () const
virtual G4String GetParticleName () const
virtual G4double GetCharge () const
virtual G4int GetPDGEncoding () const
virtual G4double GetInitialKineticEnergy () const
virtual G4ThreeVector GetInitialMomentum () const
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void DrawTrajectory () const
virtual void AppendStep (const G4Step *aStep)
virtual int GetPointEntries () const
virtual G4VTrajectoryPoint * GetPoint (G4int i) const
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4ParticleDefinition * GetParticleDefinition ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
Private Attributes
TrajectoryPointContainer * fPositionRecord
G4int fTrackID
G4int fParentID
G4int fPDGEncoding
G4double fPDGCharge
G4String fParticleName
G4double fInitialKineticEnergy
G4ThreeVector fInitialMomentum
Detailed Description
User trajectory class
new, delete and "==" operators are overwritten
get functions G4int GetTrackID() const, G4int GetParentID() const, G4String GetParticleName() const, G4double GetCharge() const, G4int GetPDGEncoding() const, G4double GetInitialKineticEnergy() const and G4ThreeVector GetInitialMomentum() const
void ShowTrajectory(std::ostream& os=G4cout) const invokes the default implementation
void DrawTrajectory() const invokes the default implementation
void AppendStep(const G4Step* aStep) adds a user trajectory point object, RE04TrajectoryPoint
int GetPointEntries() const returns the number of point entries
G4VTrajectoryPoint* GetPoint(G4int i) const gets the i-th trajectory point
void MergeTrajectory(G4VTrajectory* secondTrajectory) adds a trajectory to a TrajectoryPointContainer, fPositionRecord
G4ParticleDefinition* GetParticleDefinition() get a particle definition from G4ParticleTable
const std::map<G4String,G4AttDef>* GetAttDefs() const defines the track ID, the parent ID, the particle name, the charge, the PDG encoding, the initial kinetic energy, the initial momentum, the initial momentum magnitude and the number of points as attiributes
std::vector<G4AttValue>* CreateAttValues() const sets and returns the attributes
Definition at line 89 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 89 of file RE04Trajectory.hh
Constructor & Destructor Documentation
RE04Trajectory::RE04Trajectory ()
Definition at line 47 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 47 of file RE04Trajectory.cc
RE04Trajectory::RE04Trajectory (const G4Track * aTrack)
Definition at line 55 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 55 of file RE04Trajectory.cc
References fInitialKineticEnergy, fInitialMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fPositionRecord, fTrackID, G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4Track::GetMaterial(), G4Track::GetMomentum(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4Track::GetPosition(), and G4Track::GetTrackID().
RE04Trajectory::RE04Trajectory (RE04Trajectory & right)
Definition at line 72 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 72 of file RE04Trajectory.cc
References fInitialKineticEnergy, fInitialMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fPositionRecord, and fTrackID.
RE04Trajectory::~RE04Trajectory () virtual
Definition at line 92 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 92 of file RE04Trajectory.cc
References fPositionRecord.
Member Function Documentation
void RE04Trajectory::AppendStep (const G4Step * aStep) virtual
Implements G4VTrajectory.
Definition at line 204 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 204 of file RE04Trajectory.cc
References fPositionRecord, G4StepPoint::GetMaterial(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), and G4Step::GetPreStepPoint().
std::vector< G4AttValue > * RE04Trajectory::CreateAttValues () const virtual
Reimplemented from G4VTrajectory.
Definition at line 166 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 166 of file RE04Trajectory.cc
References G4UIcommand::ConvertToString(), fInitialKineticEnergy, fInitialMomentum, fParentID, fParticleName, fPDGCharge, fPDGEncoding, fTrackID, G4BestUnit, G4cout, GetAttDefs(), GetPointEntries(), CLHEP::Hep3Vector::mag(), and Acts::Test::values.
void RE04Trajectory::DrawTrajectory () const virtual
Reimplemented from G4VTrajectory.
Definition at line 114 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 114 of file RE04Trajectory.cc
References G4VTrajectory::DrawTrajectory().
const std::map< G4String, G4AttDef > * RE04Trajectory::GetAttDefs () const virtual
Reimplemented from G4VTrajectory.
Definition at line 122 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 122 of file RE04Trajectory.cc
References G4AttDefStore::GetInstance(), pdg, pid, and G4InuclParticleNames::pn.
Referenced by CreateAttValues().
virtual G4double RE04Trajectory::GetCharge () const inline virtual
Implements G4VTrajectory.
Definition at line 118 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 118 of file RE04Trajectory.hh
References fPDGCharge.
virtual G4double RE04Trajectory::GetInitialKineticEnergy () const inline virtual
Definition at line 122 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 122 of file RE04Trajectory.hh
References fInitialKineticEnergy.
virtual G4ThreeVector RE04Trajectory::GetInitialMomentum () const inline virtual
Implements G4VTrajectory.
Definition at line 124 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 124 of file RE04Trajectory.hh
References fInitialMomentum.
virtual G4int RE04Trajectory::GetParentID () const inline virtual
Implements G4VTrajectory.
Definition at line 114 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 114 of file RE04Trajectory.hh
References fParentID.
G4ParticleDefinition * RE04Trajectory::GetParticleDefinition ()
Definition at line 212 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 212 of file RE04Trajectory.cc
References fParticleName, and G4ParticleTable::GetParticleTable().
virtual G4String RE04Trajectory::GetParticleName () const inline virtual
Implements G4VTrajectory.
Definition at line 116 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 116 of file RE04Trajectory.hh
References fParticleName.
virtual G4int RE04Trajectory::GetPDGEncoding () const inline virtual
Implements G4VTrajectory.
Definition at line 120 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 120 of file RE04Trajectory.hh
References fPDGEncoding.
virtual G4VTrajectoryPoint* RE04Trajectory::GetPoint (G4int i) const inline virtual
Implements G4VTrajectory.
Definition at line 133 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 133 of file RE04Trajectory.hh
References fPositionRecord.
virtual int RE04Trajectory::GetPointEntries () const inline virtual
Implements G4VTrajectory.
Definition at line 132 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 132 of file RE04Trajectory.hh
References fPositionRecord.
Referenced by CreateAttValues(), and MergeTrajectory().
virtual G4int RE04Trajectory::GetTrackID () const inline virtual
Implements G4VTrajectory.
Definition at line 112 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 112 of file RE04Trajectory.hh
References fTrackID.
void RE04Trajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) virtual
Implements G4VTrajectory.
Definition at line 218 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 218 of file RE04Trajectory.cc
References fPositionRecord, and GetPointEntries().
void RE04Trajectory::operator delete (void * aTrajectory) inline
Definition at line 165 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 165 of file RE04Trajectory.hh
References faTrajAllocator.
void * RE04Trajectory::operator new (size_t) inline
Definition at line 159 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 159 of file RE04Trajectory.hh
References faTrajAllocator.
int RE04Trajectory::operator== (const RE04Trajectory & right) const inline
Definition at line 108 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 108 of file RE04Trajectory.hh
void RE04Trajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented from G4VTrajectory.
Definition at line 106 of file RE04Trajectory.cc.
View newest version in sPHENIX GitHub at line 106 of file RE04Trajectory.cc
References G4VTrajectory::ShowTrajectory().
Referenced by RE04EventAction::EndOfEventAction().
Member Data Documentation
G4double RE04Trajectory::fInitialKineticEnergy private
Definition at line 152 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 152 of file RE04Trajectory.hh
Referenced by CreateAttValues(), GetInitialKineticEnergy(), and RE04Trajectory().
G4ThreeVector RE04Trajectory::fInitialMomentum private
Definition at line 153 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 153 of file RE04Trajectory.hh
Referenced by CreateAttValues(), GetInitialMomentum(), and RE04Trajectory().
G4int RE04Trajectory::fParentID private
Definition at line 148 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 148 of file RE04Trajectory.hh
Referenced by CreateAttValues(), GetParentID(), and RE04Trajectory().
G4String RE04Trajectory::fParticleName private
Definition at line 151 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 151 of file RE04Trajectory.hh
Referenced by CreateAttValues(), GetParticleDefinition(), GetParticleName(), and RE04Trajectory().
G4double RE04Trajectory::fPDGCharge private
Definition at line 150 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 150 of file RE04Trajectory.hh
Referenced by CreateAttValues(), GetCharge(), and RE04Trajectory().
G4int RE04Trajectory::fPDGEncoding private
Definition at line 149 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 149 of file RE04Trajectory.hh
Referenced by CreateAttValues(), GetPDGEncoding(), and RE04Trajectory().
TrajectoryPointContainer* RE04Trajectory::fPositionRecord private
Definition at line 146 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 146 of file RE04Trajectory.hh
Referenced by AppendStep(), GetPoint(), GetPointEntries(), MergeTrajectory(), RE04Trajectory(), and ~RE04Trajectory().
G4int RE04Trajectory::fTrackID private
Definition at line 147 of file RE04Trajectory.hh.
View newest version in sPHENIX GitHub at line 147 of file RE04Trajectory.hh
Referenced by CreateAttValues(), GetTrackID(), and RE04Trajectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/include/RE04Trajectory.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/src/RE04Trajectory.cc