ECCE @ EIC Software: G4tgrVolume Class Reference
G4tgrVolume Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrVolume.hh>
Public Member Functions
G4tgrVolume ()
G4tgrVolume (const std::vector< G4String > &wl)
G4tgrVolume (const G4tgrVolume &vol)
virtual ~G4tgrVolume ()
virtual G4tgrPlace * AddPlace (const std::vector< G4String > &wl)
G4tgrPlaceDivRep * AddPlaceReplica (const std::vector< G4String > &wl)
G4tgrPlaceParameterisation * AddPlaceParam (const std::vector< G4String > &wl)
void AddVisibility (const std::vector< G4String > &wl)
void AddRGBColour (const std::vector< G4String > &wl)
void AddCheckOverlaps (const std::vector< G4String > &wl)
const G4String & GetName () const
void SetName (const G4String &name)
const G4String & GetType () const
G4tgrSolid * GetSolid () const
const G4String & GetMaterialName () const
const std::vector< G4tgrPlace * > GetPlacements () const
G4bool GetVisibility () const
G4double * GetColour () const
G4double * GetRGBColour () const
G4bool GetCheckOverlaps () const
virtual G4tgrVolume * GetVolume (G4int ii) const
Protected Attributes
G4String theName
G4String theType
G4String theMaterialName
G4tgrSolid * theSolid
std::vector< G4tgrPlace * > thePlacements
G4bool theVisibility
G4double * theRGBColour
G4bool theCheckOverlaps
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrVolume &obj)
Detailed Description
Definition at line 59 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 59 of file G4tgrVolume.hh
Constructor & Destructor Documentation
G4tgrVolume::G4tgrVolume ()
Definition at line 48 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 48 of file G4tgrVolume.cc
G4tgrVolume::G4tgrVolume (const std::vector< G4String > & wl)
Definition at line 64 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 64 of file G4tgrVolume.cc
References G4tgrVolumeMgr::CreateSolid(), G4tgrVolumeMgr::FindSolid(), G4cout, G4endl, G4tgrVolumeMgr::GetInstance(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), theCheckOverlaps, theMaterialName, theName, theRGBColour, theSolid, theType, and theVisibility.
G4tgrVolume::G4tgrVolume (const G4tgrVolume & vol)
Definition at line 112 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 112 of file G4tgrVolume.cc
References GetCheckOverlaps(), GetMaterialName(), GetName(), GetPlacements(), GetRGBColour(), GetSolid(), GetType(), GetVisibility(), theCheckOverlaps, theMaterialName, theName, thePlacements, theRGBColour, theSolid, theType, and theVisibility.
G4tgrVolume::~G4tgrVolume () virtual
Definition at line 57 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 57 of file G4tgrVolume.cc
References theRGBColour.
Member Function Documentation
void G4tgrVolume::AddCheckOverlaps (const std::vector< G4String > & wl)
------— Set check overlaps
Definition at line 270 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 270 of file G4tgrVolume.cc
References G4tgrUtils::CheckWLsize(), G4tgrUtils::GetBool(), theCheckOverlaps, and WLSIZE_GE.
G4tgrPlace * G4tgrVolume::AddPlace (const std::vector< G4String > & wl) virtual
Reimplemented in G4tgrVolumeAssembly.
Definition at line 137 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 137 of file G4tgrVolume.cc
References G4tgrUtils::CheckWLsize(), FatalErrorInArgument, G4cout, G4endl, G4Exception(), G4tgrPlace::GetCopyNo(), G4tgrVolumeMgr::GetInstance(), G4tgrPlace::GetParentName(), G4tgrPlace::GetType(), G4tgrMessenger::GetVerboseLevel(), readPY::pl, G4tgrVolumeMgr::RegisterParentChild(), G4tgrPlace::SetVolume(), theName, thePlacements, and WLSIZE_EQ.
Referenced by G4tgrLineProcessor::ProcessLine().
G4tgrPlaceParameterisation * G4tgrVolume::AddPlaceParam (const std::vector< G4String > & wl)
Definition at line 217 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 217 of file G4tgrVolume.cc
References G4cout, G4endl, G4tgrVolumeMgr::GetInstance(), G4tgrPlace::GetParentName(), G4tgrMessenger::GetVerboseLevel(), readPY::pl, G4tgrVolumeMgr::RegisterParentChild(), G4tgrPlace::SetVolume(), theName, and thePlacements.
Referenced by G4tgrLineProcessor::ProcessLine().
G4tgrPlaceDivRep * G4tgrVolume::AddPlaceReplica (const std::vector< G4String > & wl)
Definition at line 179 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 179 of file G4tgrVolume.cc
References G4tgrUtils::CheckWLsize(), G4cout, G4endl, G4Exception(), G4tgrUtils::GetDouble(), G4tgrVolumeMgr::GetInstance(), G4tgrPlace::GetParentName(), G4tgrMessenger::GetVerboseLevel(), JustWarning, readPY::pl, G4tgrVolumeMgr::RegisterParentChild(), G4tgrPlace::SetType(), G4tgrPlace::SetVolume(), theName, thePlacements, WLSIZE_GE, and WLSIZE_LE.
Referenced by G4tgrLineProcessor::ProcessLine().
void G4tgrVolume::AddRGBColour (const std::vector< G4String > & wl)
------— Set transparency
Definition at line 252 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 252 of file G4tgrVolume.cc
References G4tgrUtils::CheckWLsize(), G4tgrUtils::GetDouble(), theRGBColour, and WLSIZE_GE.
void G4tgrVolume::AddVisibility (const std::vector< G4String > & wl)
Definition at line 241 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 241 of file G4tgrVolume.cc
References G4tgrUtils::CheckWLsize(), G4tgrUtils::GetBool(), theVisibility, and WLSIZE_EQ.
G4bool G4tgrVolume::GetCheckOverlaps () const inline
Definition at line 99 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 99 of file G4tgrVolume.hh
References theCheckOverlaps.
Referenced by G4tgbVolume::ConstructG4PhysVol(), and G4tgrVolume().
G4double* G4tgrVolume::GetColour () const inline
Definition at line 96 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 96 of file G4tgrVolume.hh
References theRGBColour.
Referenced by G4tgbVolume::GetColour().
const G4String& G4tgrVolume::GetMaterialName () const inline
Definition at line 92 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 92 of file G4tgrVolume.hh
References theMaterialName.
Referenced by G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), and G4tgrVolume().
const G4String& G4tgrVolume::GetName (void) const inline
Definition at line 88 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 88 of file G4tgrVolume.hh
References theName.
Referenced by G4tgbDetectorConstruction::Construct(), G4tgbDetectorBuilder::ConstructDetector(), G4tgbVolume::ConstructG4Volumes(), G4tgrVolumeMgr::DumpSummary(), G4tgrVolumeMgr::DumpVolumeLeaf(), G4tgrVolume(), G4tgbVolume::GetName(), G4tgrVolumeMgr::GetTopVolume(), G4tgrVolumeMgr::RegisterMe(), and G4tgrVolumeMgr::UnRegisterMe().
const std::vector<G4tgrPlace*> G4tgrVolume::GetPlacements () const inline
Definition at line 94 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 94 of file G4tgrVolume.hh
References thePlacements.
Referenced by G4tgrVolume(), and G4tgrVolumeMgr::GetTopVolume().
G4double* G4tgrVolume::GetRGBColour () const inline
Definition at line 97 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 97 of file G4tgrVolume.hh
References theRGBColour.
Referenced by G4tgrVolume().
G4tgrSolid* G4tgrVolume::GetSolid () const inline
Definition at line 91 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 91 of file G4tgrVolume.hh
References theSolid.
Referenced by G4tgbVolume::ConstructG4Volumes(), G4tgrSolidBoolean::G4tgrSolidBoolean(), and G4tgrVolume().
const G4String& G4tgrVolume::GetType () const inline
Definition at line 90 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 90 of file G4tgrVolume.hh
References theType.
Referenced by G4tgbVolume::ConstructG4PhysVol(), G4tgbVolume::ConstructG4Volumes(), G4tgrLineProcessor::FindVolume(), G4tgrVolume(), and G4tgrVolumeMgr::GetTopVolume().
G4bool G4tgrVolume::GetVisibility () const inline
Definition at line 95 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 95 of file G4tgrVolume.hh
References theVisibility.
Referenced by G4tgrVolume(), and G4tgbVolume::GetVisibility().
G4tgrVolume * G4tgrVolume::GetVolume (G4int ii) const virtual
Definition at line 126 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 126 of file G4tgrVolume.cc
References G4UIcommand::ConvertToString(), FatalException, and G4Exception().
void G4tgrVolume::SetName (const G4String & name) inline
Definition at line 89 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 89 of file G4tgrVolume.hh
References theName.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrVolume & obj) friend
Definition at line 282 of file G4tgrVolume.cc.
View newest version in sPHENIX GitHub at line 282 of file G4tgrVolume.cc
Member Data Documentation
G4bool G4tgrVolume::theCheckOverlaps protected
Definition at line 120 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 120 of file G4tgrVolume.hh
Referenced by AddCheckOverlaps(), G4tgrVolume(), GetCheckOverlaps(), and operator<<().
G4String G4tgrVolume::theMaterialName protected
Definition at line 111 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 111 of file G4tgrVolume.hh
Referenced by G4tgrVolume(), G4tgrVolumeDivision::G4tgrVolumeDivision(), GetMaterialName(), and operator<<().
G4String G4tgrVolume::theName protected
Definition at line 107 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 107 of file G4tgrVolume.hh
Referenced by G4tgrVolumeAssembly::AddPlace(), AddPlace(), AddPlaceParam(), AddPlaceReplica(), G4tgrVolume(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), G4tgrVolumeDivision::G4tgrVolumeDivision(), GetName(), operator<<(), and SetName().
std::vector<G4tgrPlace*> G4tgrVolume::thePlacements protected
Definition at line 115 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 115 of file G4tgrVolume.hh
Referenced by G4tgrVolumeAssembly::AddPlace(), AddPlace(), AddPlaceParam(), AddPlaceReplica(), G4tgrVolume(), GetPlacements(), and operator<<().
G4double* G4tgrVolume::theRGBColour protected
Definition at line 119 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 119 of file G4tgrVolume.hh
Referenced by AddRGBColour(), G4tgrVolume(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), G4tgrVolumeDivision::G4tgrVolumeDivision(), GetColour(), GetRGBColour(), operator<<(), and ~G4tgrVolume().
G4tgrSolid* G4tgrVolume::theSolid protected
Definition at line 113 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 113 of file G4tgrVolume.hh
Referenced by G4tgrVolume(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), G4tgrVolumeDivision::G4tgrVolumeDivision(), and GetSolid().
G4String G4tgrVolume::theType protected
Definition at line 109 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 109 of file G4tgrVolume.hh
Referenced by G4tgrVolume(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), G4tgrVolumeDivision::G4tgrVolumeDivision(), GetType(), and operator<<().
G4bool G4tgrVolume::theVisibility protected
Definition at line 118 of file G4tgrVolume.hh.
View newest version in sPHENIX GitHub at line 118 of file G4tgrVolume.hh
Referenced by AddVisibility(), G4tgrVolume(), G4tgrVolumeAssembly::G4tgrVolumeAssembly(), G4tgrVolumeDivision::G4tgrVolumeDivision(), GetVisibility(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrVolume.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrVolume.cc