ECCE @ EIC Software: pyG4VisAttributes Namespace Reference
pyG4VisAttributes Namespace Reference
Variables
void(G4VisAttributes::* f1_SetColor)(const G4Color &)
void(G4VisAttributes::* f2_SetColor)(G4double, G4double, G4double, G4double)
void(G4VisAttributes::* f1_SetColour)(const G4Colour &)
void(G4VisAttributes::* f2_SetColour)(G4double, G4double, G4double, G4double)
Variable Documentation
void(G4VisAttributes::* pyG4VisAttributes::f1_SetColor)(const G4Color &)
Initial value:
=
  &G4VisAttributes::SetColor
Definition at line 43 of file pyG4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 43 of file pyG4VisAttributes.cc
Referenced by BOOST_PYTHON_MODULE(), and export_G4VisAttributes().
void(G4VisAttributes::* pyG4VisAttributes::f1_SetColour)(const G4Colour &)
Initial value:
=
  &G4VisAttributes::SetColour
Definition at line 52 of file pyG4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 52 of file pyG4VisAttributes.cc
Referenced by export_G4VisAttributes().
void(G4VisAttributes::* pyG4VisAttributes::f2_SetColor)(G4double, G4double, G4double, G4double)
Initial value:
=
  &G4VisAttributes::SetColor
Definition at line 46 of file pyG4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 46 of file pyG4VisAttributes.cc
Referenced by BOOST_PYTHON_MODULE(), and export_G4VisAttributes().
void(G4VisAttributes::* pyG4VisAttributes::f2_SetColour)(G4double, G4double, G4double, G4double)
Initial value:
=
  &G4VisAttributes::SetColour
Definition at line 55 of file pyG4VisAttributes.cc.
View newest version in sPHENIX GitHub at line 55 of file pyG4VisAttributes.cc
Referenced by export_G4VisAttributes().