ECCE @ EIC Software: G4Hdf5FileManager Class Reference
G4Hdf5FileManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/hdf5/include/G4Hdf5FileManager.hh>
Public Types
using NtupleType = tools::hdf5::ntuple
using NtupleDescriptionType = G4TNtupleDescription< NtupleType >
Public Member Functions
G4Hdf5FileManager (const G4AnalysisManagerState &state)
~G4Hdf5FileManager ()
virtual G4bool OpenFile (const G4String &fileName) final
virtual G4bool WriteFile () final
virtual G4bool CloseFile () final
G4bool WriteHistoDirectory ()
G4bool WriteNtupleDirectory ()
void CloseAfterHnWrite ()
void SetBasketSize (unsigned int basketSize)
hid_t GetFile () const
hid_t GetHistoDirectory () const
hid_t GetNtupleDirectory () const
unsigned int GetBasketSize () const
Public Member Functions inherited from G4VFileManager
G4VFileManager (const G4AnalysisManagerState &state)
virtual ~G4VFileManager ()
virtual G4bool SetFileName (const G4String &fileName) final
void LockHistoDirectoryName ()
void LockNtupleDirectoryName ()
G4bool SetHistoDirectoryName (const G4String &dirName)
G4bool SetNtupleDirectoryName (const G4String &dirName)
G4bool IsOpenFile () const
G4String GetHistoDirectoryName () const
G4String GetNtupleDirectoryName () const
Public Member Functions inherited from G4BaseFileManager
G4BaseFileManager (const G4AnalysisManagerState &state)
virtual ~G4BaseFileManager ()
G4String GetFileName () const
G4String GetFullFileName (const G4String &baseFileName="", G4bool isPerThread=true) const
G4String GetHnFileName (const G4String &hnType, const G4String &hnName) const
G4String GetNtupleFileName (const G4String &ntupleName) const
G4String GetNtupleFileName (G4int ntupleFileNumber) const
G4String GetPlotFileName () const
G4String GetFileType () const
Private Member Functions
G4bool CreateDirectory (const G4String &directoryType, const G4String &directoryName, hid_t &directory)
G4bool WriteDirectory (const G4String &directoryType, const G4String &directoryName, hid_t &directory)
Private Attributes
hid_t fFile
hid_t fHistoDirectory
hid_t fNtupleDirectory
unsigned int fBasketSize
Static Private Attributes
static const G4String fgkDefaultDirectoryName = "default"
Additional Inherited Members
Protected Member Functions inherited from G4BaseFileManager
G4String TakeOffExtension (G4String &name) const
Protected Attributes inherited from G4VFileManager
G4bool fIsOpenFile
G4String fHistoDirectoryName
G4String fNtupleDirectoryName
G4bool fLockFileName
G4bool fLockHistoDirectoryName
G4bool fLockNtupleDirectoryName
Detailed Description
Definition at line 45 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 45 of file G4Hdf5FileManager.hh
Member Typedef Documentation
using G4Hdf5FileManager::NtupleDescriptionType = G4TNtupleDescription<NtupleType>
Definition at line 53 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 53 of file G4Hdf5FileManager.hh
using G4Hdf5FileManager::NtupleType = tools::hdf5::ntuple
Definition at line 52 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 52 of file G4Hdf5FileManager.hh
Constructor & Destructor Documentation
G4Hdf5FileManager::G4Hdf5FileManager (const G4AnalysisManagerState & state) explicit
Definition at line 41 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 41 of file G4Hdf5FileManager.cc
G4Hdf5FileManager::~G4Hdf5FileManager ()
Definition at line 50 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 50 of file G4Hdf5FileManager.cc
Member Function Documentation
void G4Hdf5FileManager::CloseAfterHnWrite ()
Definition at line 257 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 257 of file G4Hdf5FileManager.cc
References fFile, and fHistoDirectory.
G4bool G4Hdf5FileManager::CloseFile () final virtual
Implements G4VFileManager.
Definition at line 212 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 212 of file G4Hdf5FileManager.cc
References fFile, fHistoDirectory, G4VFileManager::fIsOpenFile, G4VFileManager::fLockFileName, fNtupleDirectory, G4BaseFileManager::fState, G4BaseFileManager::GetFullFileName(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4Hdf5FileManager::CreateDirectory (const G4String & directoryType, const G4String & directoryName, hid_t & directory) private
Definition at line 58 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 58 of file G4Hdf5FileManager.cc
References fFile, fgkDefaultDirectoryName, G4BaseFileManager::fState, G4Exception(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, G4AnalysisVerbose::Message(), and message().
Referenced by OpenFile().
unsigned int G4Hdf5FileManager::GetBasketSize () const inline
Definition at line 103 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 103 of file G4Hdf5FileManager.hh
References fBasketSize.
hid_t G4Hdf5FileManager::GetFile () const inline
Definition at line 94 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 94 of file G4Hdf5FileManager.hh
References fFile.
hid_t G4Hdf5FileManager::GetHistoDirectory () const inline
Definition at line 97 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 97 of file G4Hdf5FileManager.hh
References fHistoDirectory.
hid_t G4Hdf5FileManager::GetNtupleDirectory () const inline
Definition at line 100 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 100 of file G4Hdf5FileManager.hh
References fNtupleDirectory.
G4bool G4Hdf5FileManager::OpenFile (const G4String & fileName) final virtual
Implements G4VFileManager.
Definition at line 165 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 165 of file G4Hdf5FileManager.cc
References CreateDirectory(), fFile, G4BaseFileManager::fFileName, fHistoDirectory, G4VFileManager::fHistoDirectoryName, G4VFileManager::fIsOpenFile, G4VFileManager::fLockFileName, G4VFileManager::fLockHistoDirectoryName, G4VFileManager::fLockNtupleDirectoryName, fNtupleDirectory, G4VFileManager::fNtupleDirectoryName, G4Exception(), G4BaseFileManager::GetFullFileName(), JustWarning, WriteHistoDirectory(), and WriteNtupleDirectory().
void G4Hdf5FileManager::SetBasketSize (unsigned int basketSize) inline
Definition at line 91 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 91 of file G4Hdf5FileManager.hh
G4bool G4Hdf5FileManager::WriteDirectory (const G4String & directoryType, const G4String & directoryName, hid_t & directory) private
Definition at line 119 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 119 of file G4Hdf5FileManager.cc
References G4Exception(), JustWarning, and message().
Referenced by WriteHistoDirectory(), and WriteNtupleDirectory().
G4bool G4Hdf5FileManager::WriteFile () final virtual
Implements G4VFileManager.
Definition at line 205 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 205 of file G4Hdf5FileManager.cc
G4bool G4Hdf5FileManager::WriteHistoDirectory ()
Definition at line 245 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 245 of file G4Hdf5FileManager.cc
References fHistoDirectory, G4VFileManager::fHistoDirectoryName, and WriteDirectory().
Referenced by OpenFile().
G4bool G4Hdf5FileManager::WriteNtupleDirectory ()
Definition at line 251 of file G4Hdf5FileManager.cc.
View newest version in sPHENIX GitHub at line 251 of file G4Hdf5FileManager.cc
References fNtupleDirectory, G4VFileManager::fNtupleDirectoryName, and WriteDirectory().
Referenced by OpenFile().
Member Data Documentation
unsigned int G4Hdf5FileManager::fBasketSize private
Definition at line 86 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 86 of file G4Hdf5FileManager.hh
Referenced by GetBasketSize().
hid_t G4Hdf5FileManager::fFile private
Definition at line 83 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 83 of file G4Hdf5FileManager.hh
Referenced by CloseAfterHnWrite(), CloseFile(), CreateDirectory(), GetFile(), and OpenFile().
const G4String G4Hdf5FileManager::fgkDefaultDirectoryName = "default" static private
Definition at line 80 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 80 of file G4Hdf5FileManager.hh
Referenced by CreateDirectory().
hid_t G4Hdf5FileManager::fHistoDirectory private
Definition at line 84 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 84 of file G4Hdf5FileManager.hh
Referenced by CloseAfterHnWrite(), CloseFile(), GetHistoDirectory(), OpenFile(), and WriteHistoDirectory().
hid_t G4Hdf5FileManager::fNtupleDirectory private
Definition at line 85 of file G4Hdf5FileManager.hh.
View newest version in sPHENIX GitHub at line 85 of file G4Hdf5FileManager.hh
Referenced by CloseFile(), GetNtupleDirectory(), OpenFile(), and WriteNtupleDirectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/hdf5/include/G4Hdf5FileManager.hh
geant4/tree/geant4-10.6-release/source/analysis/hdf5/src/G4Hdf5FileManager.cc