ECCE @ EIC Software: G4GIDI_map Class Reference
G4GIDI_map Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4GIDI_map.hh>
Public Member Functions
G4GIDI_map (std::string &dataDirectory)
~G4GIDI_map ()
std::string path (void)
std::string fileName (void)
Public Attributes
GIDI::statusMessageReporting smr
GIDI::MCGIDI_map * map
Detailed Description
Definition at line 38 of file G4GIDI_map.hh.
View newest version in sPHENIX GitHub at line 38 of file G4GIDI_map.hh
Constructor & Destructor Documentation
G4GIDI_map::G4GIDI_map (std::string & dataDirectory)
Definition at line 37 of file G4GIDI_map.cc.
View newest version in sPHENIX GitHub at line 37 of file G4GIDI_map.cc
References MCGIDI_map_readFile(), smr_initialize(), smr_isOk(), smr_print(), and smr_status_Ok.
G4GIDI_map::~G4GIDI_map (void)
Definition at line 49 of file G4GIDI_map.cc.
View newest version in sPHENIX GitHub at line 49 of file G4GIDI_map.cc
References MCGIDI_map_free(), and smr_release().
Member Function Documentation
std::string G4GIDI_map::fileName (void)
Definition at line 57 of file G4GIDI_map.cc.
View newest version in sPHENIX GitHub at line 57 of file G4GIDI_map.cc
std::string G4GIDI_map::path (void)
Definition at line 64 of file G4GIDI_map.cc.
View newest version in sPHENIX GitHub at line 64 of file G4GIDI_map.cc
Member Data Documentation
GIDI::MCGIDI_map* G4GIDI_map::map
Definition at line 42 of file G4GIDI_map.hh.
View newest version in sPHENIX GitHub at line 42 of file G4GIDI_map.hh
GIDI::statusMessageReporting G4GIDI_map::smr
Definition at line 41 of file G4GIDI_map.hh.
View newest version in sPHENIX GitHub at line 41 of file G4GIDI_map.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4GIDI_map.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4GIDI_map.cc