ECCE @ EIC Software: G4ParticleHPDataPoint Class Reference
G4ParticleHPDataPoint Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPDataPoint.hh>
Public Member Functions
G4ParticleHPDataPoint ()
G4ParticleHPDataPoint (G4double e, G4double x)
G4ParticleHPDataPoint & operator= (const G4ParticleHPDataPoint &aSet)=default
G4double GetEnergy () const
G4double GetXsection () const
void SetEnergy (G4double e)
void SetXsection (G4double x)
G4double GetX () const
G4double GetY () const
void SetX (G4double e)
void SetY (G4double x)
void SetData (G4double e, G4double x)
Private Attributes
G4double energy
G4double xSec
Detailed Description
Definition at line 35 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleHPDataPoint.hh
Constructor & Destructor Documentation
G4ParticleHPDataPoint::G4ParticleHPDataPoint () inline
Definition at line 39 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleHPDataPoint.hh
References energy, and xSec.
G4ParticleHPDataPoint::G4ParticleHPDataPoint (G4double e, G4double x) inline
Definition at line 40 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPDataPoint.hh
References e, energy, x, and xSec.
Member Function Documentation
G4double G4ParticleHPDataPoint::GetEnergy () const inline
Definition at line 46 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPDataPoint.hh
References energy.
G4double G4ParticleHPDataPoint::GetX () const inline
Definition at line 52 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPDataPoint.hh
References energy.
Referenced by G4ParticleHPVector::Dump(), G4ParticleHPVector::Get15percentBorder(), G4ParticleHPVector::Get50percentBorder(), G4ParticleHPVector::GetEnergy(), G4ParticleHPVector::GetMeanX(), G4ParticleHPVector::GetX(), G4ParticleHPVector::GetXsec(), G4ParticleHPVector::Integrate(), G4ParticleHPVector::IntegrateAndNormalise(), G4ParticleHPVector::Sample(), G4ParticleHPVector::SampleLin(), G4ParticleHPVector::SetPoint(), and G4ParticleHPVector::ThinOut().
G4double G4ParticleHPDataPoint::GetXsection () const inline
Definition at line 47 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPDataPoint.hh
References xSec.
G4double G4ParticleHPDataPoint::GetY () const inline
Definition at line 53 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPDataPoint.hh
References xSec.
Referenced by G4ParticleHPVector::Dump(), G4ParticleHPVector::GetMeanX(), G4ParticleHPVector::GetXsec(), G4ParticleHPVector::GetY(), G4ParticleHPVector::Integrate(), G4ParticleHPVector::IntegrateAndNormalise(), G4ParticleHPVector::Sample(), G4ParticleHPVector::SetPoint(), and G4ParticleHPVector::ThinOut().
G4ParticleHPDataPoint& G4ParticleHPDataPoint::operator= (const G4ParticleHPDataPoint & aSet) default
void G4ParticleHPDataPoint::SetData (G4double e, G4double x) inline
Definition at line 58 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPDataPoint.hh
References e, energy, x, and xSec.
Referenced by G4ParticleHPVector::SetData(), and G4ParticleHPHash::SetData().
void G4ParticleHPDataPoint::SetEnergy (G4double e) inline
Definition at line 49 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPDataPoint.hh
References e, and energy.
void G4ParticleHPDataPoint::SetX (G4double e) inline
Definition at line 55 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPDataPoint.hh
References e, and energy.
Referenced by G4ParticleHPVector::SetEnergy(), and G4ParticleHPVector::SetX().
void G4ParticleHPDataPoint::SetXsection (G4double x) inline
Definition at line 50 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPDataPoint.hh
References x, and xSec.
void G4ParticleHPDataPoint::SetY (G4double x) inline
Definition at line 56 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPDataPoint.hh
References x, and xSec.
Referenced by G4ParticleHPVector::SetXsec(), G4ParticleHPVector::SetY(), and G4ParticleHPVector::Times().
Member Data Documentation
G4double G4ParticleHPDataPoint::energy private
Definition at line 62 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ParticleHPDataPoint.hh
Referenced by G4ParticleHPDataPoint(), GetEnergy(), GetX(), SetData(), SetEnergy(), and SetX().
G4double G4ParticleHPDataPoint::xSec private
Definition at line 63 of file G4ParticleHPDataPoint.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ParticleHPDataPoint.hh
Referenced by G4ParticleHPDataPoint(), GetXsection(), GetY(), SetData(), SetXsection(), and SetY().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPDataPoint.hh