ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackPointInfo.hh File Reference
CexmcTrackPointInfo.hh File Reference
#include <iosfwd>
#include <G4ThreeVector.hh>
#include <G4ParticleDefinition.hh>
#include <G4Allocator.hh>
#include <G4UnitsTable.hh>
#include <G4Types.hh>
#include "CexmcCommon.hh"
Classes
struct CexmcTrackPointInfo
Functions
std::ostream & operator<< (std::ostream &out, const CexmcTrackPointInfo &trackPointInfo)
Variables
G4Allocator< CexmcTrackPointInfo > trackPointInfoAllocator
Function Documentation
std::ostream& operator<< (std::ostream & out, const CexmcTrackPointInfo & trackPointInfo)
Definition at line 48 of file CexmcTrackPointInfo.cc.
View newest version in sPHENIX GitHub at line 48 of file CexmcTrackPointInfo.cc
References CexmcBeamParticleTrack, CexmcNucleusParticleTrack, CexmcOutputParticleDecayProductTrack, CexmcOutputParticleTrack, CexmcTrackPointInfo::directionLocal, CexmcTrackPointInfo::directionWorld, G4BestUnit, G4ParticleDefinition::GetParticleName(), CexmcTrackPointInfo::IsValid(), CexmcTrackPointInfo::momentumAmp, CexmcTrackPointInfo::particle, CexmcTrackPointInfo::positionLocal, CexmcTrackPointInfo::positionWorld, CLHEP::prec, CexmcTrackPointInfo::trackId, CexmcTrackPointInfo::trackType, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Variable Documentation
G4Allocator< CexmcTrackPointInfo > trackPointInfoAllocator
Definition at line 50 of file CexmcCommon.cc.
View newest version in sPHENIX GitHub at line 50 of file CexmcCommon.cc