ECCE @ EIC Software: G4StatMFMicroPartition Class Reference
G4StatMFMicroPartition Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMicroPartition.hh>
Public Member Functions
G4StatMFMicroPartition (G4int A, G4int Z)
~G4StatMFMicroPartition ()
G4bool operator== (const G4StatMFMicroPartition &right) const
G4bool operator!= (const G4StatMFMicroPartition &right) const
G4StatMFChannel * ChooseZ (G4int A0, G4int Z0, G4double MeanT)
G4double GetProbability (void)
void SetPartitionFragment (G4int anA)
void Normalize (G4double Normalization)
G4double CalcPartitionProbability (G4double U, G4double FreeInternalE0, G4double SCompound)
G4double GetTemperature (void)
G4double GetEntropy (void)
Private Member Functions
G4StatMFMicroPartition ()
G4StatMFMicroPartition (const G4StatMFMicroPartition &right)
G4StatMFMicroPartition & operator= (const G4StatMFMicroPartition &right)
void CoulombFreeEnergy (G4int anA)
G4double CalcPartitionTemperature (G4double U, G4double FreeInternalE0)
G4double GetPartitionEnergy (G4double T)
G4double GetCoulombEnergy (void)
G4double GetDegeneracyFactor (G4int A)
G4double InvLevelDensity (G4double Af)
Private Attributes
G4int theA
G4int theZ
G4double _Probability
G4double _Temperature
G4double _Entropy
std::vector< G4int > _thePartition
std::vector< G4double > _theCoulombFreeEnergy
Detailed Description
Definition at line 40 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 40 of file G4StatMFMicroPartition.hh
Constructor & Destructor Documentation
G4StatMFMicroPartition::G4StatMFMicroPartition (G4int A, G4int Z) inline
Definition at line 44 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 44 of file G4StatMFMicroPartition.hh
G4StatMFMicroPartition::~G4StatMFMicroPartition () inline
Definition at line 50 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 50 of file G4StatMFMicroPartition.hh
G4StatMFMicroPartition::G4StatMFMicroPartition () inline private
Definition at line 55 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 55 of file G4StatMFMicroPartition.hh
G4StatMFMicroPartition::G4StatMFMicroPartition (const G4StatMFMicroPartition & right) private
Definition at line 41 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 41 of file G4StatMFMicroPartition.cc
Member Function Documentation
G4double G4StatMFMicroPartition::CalcPartitionProbability (G4double U, G4double FreeInternalE0, G4double SCompound)
Definition at line 228 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 228 of file G4StatMFMicroPartition.cc
References _Entropy, _Probability, _Temperature, _thePartition, CalcPartitionTemperature(), G4StatMFParameters::DBetaDT(), source.hepunit::elm_coupling, f, fermi, G4Exp(), G4Log(), GetDegeneracyFactor(), G4Pow::GetInstance(), G4StatMFParameters::Getr0(), InvLevelDensity(), G4Pow::logZ(), max, pi, T, theA, G4Pow::Z13(), and G4Pow::Z23().
Referenced by G4StatMFMicroManager::Initialize().
G4double G4StatMFMicroPartition::CalcPartitionTemperature (G4double U, G4double FreeInternalE0) private
Definition at line 173 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 173 of file G4StatMFMicroPartition.cc
References kdfinder::abs(), eps, G4cout, G4endl, GetPartitionEnergy(), max, MeV, and theA.
Referenced by CalcPartitionProbability().
G4StatMFChannel * G4StatMFMicroPartition::ChooseZ (G4int A0, G4int Z0, G4double MeanT)
Definition at line 317 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 317 of file G4StatMFMicroPartition.cc
References _thePartition, kdfinder::abs(), G4StatMFChannel::CreateFragment(), G4StatMFParameters::GetGamma0(), and G4INCL::DeJongSpin::shoot().
void G4StatMFMicroPartition::CoulombFreeEnergy (G4int anA) private
Definition at line 69 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 69 of file G4StatMFMicroPartition.cc
References _theCoulombFreeEnergy, G4StatMFParameters::GetCoulomb(), G4Pow::GetInstance(), theA, and theZ.
Referenced by SetPartitionFragment().
G4double G4StatMFMicroPartition::GetCoulombEnergy (void) private
Definition at line 95 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 95 of file G4StatMFMicroPartition.cc
References _theCoulombFreeEnergy, _thePartition, G4Pow::A13(), source.hepunit::elm_coupling, G4Pow::GetInstance(), G4StatMFParameters::GetKappaCoulomb(), G4StatMFParameters::Getr0(), theA, theZ, G4Pow::Z13(), and G4Pow::Z23().
G4double G4StatMFMicroPartition::GetDegeneracyFactor (G4int A) private
Definition at line 304 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 304 of file G4StatMFMicroPartition.cc
Referenced by CalcPartitionProbability().
G4double G4StatMFMicroPartition::GetEntropy (void) inline
Definition at line 92 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 92 of file G4StatMFMicroPartition.hh
References _Entropy.
Referenced by G4StatMFMicroManager::Initialize().
G4double G4StatMFMicroPartition::GetPartitionEnergy (G4double T) private
Definition at line 112 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 112 of file G4StatMFMicroPartition.cc
References _theCoulombFreeEnergy, _thePartition, G4Pow::A13(), G4StatMFParameters::Beta(), G4StatMFParameters::DBetaDT(), source.hepunit::elm_coupling, G4StatMFParameters::GetE0(), G4StatMFParameters::GetGamma0(), G4Pow::GetInstance(), G4StatMFParameters::GetKappaCoulomb(), G4StatMFParameters::Getr0(), InvLevelDensity(), theA, theZ, G4Pow::Z13(), and G4Pow::Z23().
Referenced by CalcPartitionTemperature().
G4double G4StatMFMicroPartition::GetProbability (void) inline
Definition at line 71 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 71 of file G4StatMFMicroPartition.hh
References _Probability.
G4double G4StatMFMicroPartition::GetTemperature (void) inline
Definition at line 87 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 87 of file G4StatMFMicroPartition.hh
References _Temperature.
Referenced by G4StatMFMicroManager::Initialize().
G4double G4StatMFMicroPartition::InvLevelDensity (G4double Af) inline private
Definition at line 110 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 110 of file G4StatMFMicroPartition.hh
References G4StatMFParameters::GetEpsilon0().
Referenced by CalcPartitionProbability(), and GetPartitionEnergy().
void G4StatMFMicroPartition::Normalize (G4double Normalization) inline
Definition at line 80 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 80 of file G4StatMFMicroPartition.hh
References _Probability.
G4bool G4StatMFMicroPartition::operator!= (const G4StatMFMicroPartition & right) const
Definition at line 63 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 63 of file G4StatMFMicroPartition.cc
G4StatMFMicroPartition & G4StatMFMicroPartition::operator= (const G4StatMFMicroPartition & right) private
Definition at line 49 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 49 of file G4StatMFMicroPartition.cc
G4bool G4StatMFMicroPartition::operator== (const G4StatMFMicroPartition & right) const
Definition at line 56 of file G4StatMFMicroPartition.cc.
View newest version in sPHENIX GitHub at line 56 of file G4StatMFMicroPartition.cc
void G4StatMFMicroPartition::SetPartitionFragment (G4int anA) inline
Definition at line 74 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 74 of file G4StatMFMicroPartition.hh
References _thePartition, and CoulombFreeEnergy().
Referenced by G4StatMFMicroManager::Initialize().
Member Data Documentation
G4double G4StatMFMicroPartition::_Entropy private
Definition at line 131 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 131 of file G4StatMFMicroPartition.hh
Referenced by CalcPartitionProbability(), and GetEntropy().
G4double G4StatMFMicroPartition::_Probability private
Definition at line 125 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 125 of file G4StatMFMicroPartition.hh
Referenced by CalcPartitionProbability(), GetProbability(), and Normalize().
G4double G4StatMFMicroPartition::_Temperature private
Definition at line 128 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 128 of file G4StatMFMicroPartition.hh
Referenced by CalcPartitionProbability(), and GetTemperature().
std::vector<G4double> G4StatMFMicroPartition::_theCoulombFreeEnergy private
Definition at line 136 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 136 of file G4StatMFMicroPartition.hh
Referenced by CoulombFreeEnergy(), GetCoulombEnergy(), and GetPartitionEnergy().
std::vector<G4int> G4StatMFMicroPartition::_thePartition private
Definition at line 134 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 134 of file G4StatMFMicroPartition.hh
Referenced by CalcPartitionProbability(), ChooseZ(), GetCoulombEnergy(), GetPartitionEnergy(), and SetPartitionFragment().
G4int G4StatMFMicroPartition::theA private
Definition at line 121 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 121 of file G4StatMFMicroPartition.hh
Referenced by CalcPartitionProbability(), CalcPartitionTemperature(), CoulombFreeEnergy(), GetCoulombEnergy(), and GetPartitionEnergy().
G4int G4StatMFMicroPartition::theZ private
Definition at line 122 of file G4StatMFMicroPartition.hh.
View newest version in sPHENIX GitHub at line 122 of file G4StatMFMicroPartition.hh
Referenced by CoulombFreeEnergy(), GetCoulombEnergy(), and GetPartitionEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMicroPartition.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMicroPartition.cc