ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalutils.cc File Reference
CCalutils.cc File Reference
#include "CCalutils.hh"
#include "G4ios.hh"
#include "G4UnitsTable.hh"
#include <sstream>
Functions
G4String operator+ (const G4String &str, const G4int i)
G4String operator+ (const G4String &str, const G4double i)
std::ifstream & readName (std::ifstream &is, G4String &name)
std::ifstream & findDO (std::ifstream &is, const G4String &str)
std::ostream & tab (std::ostream &os)
std::istream & jump (std::istream &is)
G4bool openGeomFile (std::ifstream &is, const G4String &pathname, const G4String &filename)
Function Documentation
std::ifstream& findDO (std::ifstream & is, const G4String & str)
Definition at line 72 of file CCalutils.cc.
View newest version in sPHENIX GitHub at line 72 of file CCalutils.cc
Referenced by CCalMagneticField::CCalMagneticField(), CCalRotationMatrixFactory::CCalRotationMatrixFactory(), CCalMaterialFactory::readElements(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), and CCalMaterialFactory::readMaterials().
std::istream& jump (std::istream & is)
Definition at line 95 of file CCalutils.cc.
View newest version in sPHENIX GitHub at line 95 of file CCalutils.cc
References second.
Referenced by CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), CCalMaterialFactory::readElements(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), CCalVisualisable::readFile(), and CCalMaterialFactory::readMaterials().
G4bool openGeomFile (std::ifstream & is, const G4String & pathname, const G4String & filename)
Definition at line 116 of file CCalutils.cc.
View newest version in sPHENIX GitHub at line 116 of file CCalutils.cc
References INPUTHEPMC::filename, G4cerr, and G4endl.
Referenced by CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalMagneticField::CCalMagneticField(), CCalRotationMatrixFactory::CCalRotationMatrixFactory(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), CCalMaterialFactory::readElements(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), CCalVisualisable::readFile(), and CCalMaterialFactory::readMaterials().
G4String operator+ (const G4String & str, const G4int i)
Definition at line 37 of file CCalutils.cc.
View newest version in sPHENIX GitHub at line 37 of file CCalutils.cc
G4String operator+ (const G4String & str, const G4double i)
Definition at line 45 of file CCalutils.cc.
View newest version in sPHENIX GitHub at line 45 of file CCalutils.cc
std::ifstream& readName (std::ifstream & is, G4String & name)
Definition at line 53 of file CCalutils.cc.
View newest version in sPHENIX GitHub at line 53 of file CCalutils.cc
References G4String::both, and G4String::strip().
Referenced by CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), CCalMaterialFactory::readElements(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), CCalVisualisable::readFile(), and CCalMaterialFactory::readMaterials().
std::ostream& tab (std::ostream & os)
Definition at line 89 of file CCalutils.cc.
View newest version in sPHENIX GitHub at line 89 of file CCalutils.cc
Referenced by CCalGeometryConfiguration::CCalGeometryConfiguration(), CCalMagneticField::CCalMagneticField(), CCalSensitiveConfiguration::CCalSensitiveConfiguration(), G4PenelopeBremsstrahlungAngular::ClearTables(), CCalDetectorConstruction::Construct(), CCalG4Hcal::constructAbsorberLayer(), CCalG4Ecal::constructGlobal(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Ecal::constructIn(), CCalG4Hcal::constructScintillatorLayer(), PHG4HybridHomogeneousCalorimeterDetector::CrystalTable(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), CCalG4Able::PhysicalVolume(), CCalHall::readFile(), CCalEcal::readFile(), CCalHcal::readFile(), CCalVisualisable::readFile(), and CCalG4Able::setVisType().