ECCE @ EIC Software: ExGflashDetectorConstruction Class Reference
ExGflashDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflasha/include/ExGflashDetectorConstruction.hh>
Public Member Functions
ExGflashDetectorConstruction ()
~ExGflashDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
void SetLBining (G4ThreeVector)
void SetRBining (G4ThreeVector)
void SetVerbose (G4int val)
void SetMaterial (G4String mat)
G4int GetVerbose () const
G4int GetnLtot () const
G4int GetnRtot () const
G4double GetdLradl () const
G4double GetdRradl () const
G4double GetSDRadLen () const
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4int fNbOfCrystals
G4double fCrystalWidth
G4double fCrystalLength
G4LogicalVolume * fCrystal_log
G4Material * fDetMat
G4Region * fRegion
G4double fSDRadLen
G4int fVerbose
G4int fNLtot
G4int fNRtot
G4double fDLradl
G4double fDRradl
ExGflashMessenger * fGflashMessenger
Static Private Attributes
static G4ThreadLocal
GFlashShowerModel * fFastShowerModel = 0
static G4ThreadLocal
GFlashHomoShowerParameterisation * fParameterisation = 0
static G4ThreadLocal
GFlashParticleBounds * fParticleBounds = 0
static G4ThreadLocal
GFlashHitMaker * fHitMaker = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 49 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 49 of file ExGflashDetectorConstruction.hh
Constructor & Destructor Documentation
ExGflashDetectorConstruction::ExGflashDetectorConstruction ()
Definition at line 78 of file ExGflashDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 78 of file ExGflashDetectorConstruction.cc
References cm, fCrystalLength, fCrystalWidth, fGflashMessenger, G4cout, and G4endl.
ExGflashDetectorConstruction::~ExGflashDetectorConstruction ()
Definition at line 93 of file ExGflashDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 93 of file ExGflashDetectorConstruction.cc
References fFastShowerModel, fGflashMessenger, fHitMaker, fParameterisation, and fParticleBounds.
Member Function Documentation
G4VPhysicalVolume * ExGflashDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 104 of file ExGflashDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 104 of file ExGflashDetectorConstruction.cc
References G4Region::AddRootLogicalVolume(), cm, fCrystal_log, fCrystalLength, fCrystalWidth, fDetMat, G4NistManager::FindOrBuildMaterial(), fNbOfCrystals, fRegion, G4cout, G4endl, G4VisAttributes::GetInvisible(), G4Material::GetRadlen(), G4NistManager::Instance(), n, G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), and BTOF::zpos.
void ExGflashDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 239 of file ExGflashDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 239 of file ExGflashDetectorConstruction.cc
References G4SDManager::AddNewDetector(), fCrystal_log, fDetMat, fFastShowerModel, fHitMaker, fParameterisation, fParticleBounds, fRegion, fSDRadLen, G4cout, G4endl, G4Material::GetRadlen(), G4SDManager::GetSDMpointer(), GFlashShowerModel::SetHitMaker(), GFlashShowerModel::SetParameterisation(), GFlashShowerModel::SetParticleBounds(), and G4LogicalVolume::SetSensitiveDetector().
G4double ExGflashDetectorConstruction::GetdLradl () const inline
Definition at line 68 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 68 of file ExGflashDetectorConstruction.hh
References fDLradl.
Referenced by ExGflashHistoManager::Book().
G4double ExGflashDetectorConstruction::GetdRradl () const inline
Definition at line 69 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 69 of file ExGflashDetectorConstruction.hh
References fDRradl.
Referenced by ExGflashHistoManager::Book().
G4int ExGflashDetectorConstruction::GetnLtot () const inline
Definition at line 66 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file ExGflashDetectorConstruction.hh
References fNLtot.
Referenced by ExGflashHistoManager::Book().
G4int ExGflashDetectorConstruction::GetnRtot () const inline
Definition at line 67 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file ExGflashDetectorConstruction.hh
References fNRtot.
Referenced by ExGflashHistoManager::Book().
G4double ExGflashDetectorConstruction::GetSDRadLen () const inline
Definition at line 71 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 71 of file ExGflashDetectorConstruction.hh
References fSDRadLen.
G4int ExGflashDetectorConstruction::GetVerbose () const inline
Definition at line 64 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 64 of file ExGflashDetectorConstruction.hh
References fVerbose.
void ExGflashDetectorConstruction::SetLBining (G4ThreeVector Value)
Definition at line 276 of file ExGflashDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 276 of file ExGflashDetectorConstruction.cc
References fDLradl, fNLtot, G4cout, G4endl, and kMaxBin.
Referenced by ExGflashMessenger::SetNewValue().
void ExGflashDetectorConstruction::SetMaterial (G4String mat)
Definition at line 302 of file ExGflashDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 302 of file ExGflashDetectorConstruction.cc
References fCrystal_log, fDetMat, G4NistManager::FindOrBuildMaterial(), fParameterisation, fSDRadLen, G4Material::GetRadlen(), G4RunManager::GetRunManager(), G4NistManager::Instance(), G4RunManager::PhysicsHasBeenModified(), GVFlashShowerParameterisation::PrintMaterial(), GFlashHomoShowerParameterisation::SetMaterial(), and G4LogicalVolume::SetMaterial().
Referenced by ExGflashMessenger::SetNewValue().
void ExGflashDetectorConstruction::SetRBining (G4ThreeVector Value)
Definition at line 289 of file ExGflashDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 289 of file ExGflashDetectorConstruction.cc
References fDRradl, fNRtot, G4cout, G4endl, and kMaxBin.
Referenced by ExGflashMessenger::SetNewValue().
void ExGflashDetectorConstruction::SetVerbose (G4int val) inline
Definition at line 60 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 60 of file ExGflashDetectorConstruction.hh
References fVerbose.
Referenced by ExGflashMessenger::SetNewValue().
Member Data Documentation
G4LogicalVolume* ExGflashDetectorConstruction::fCrystal_log private
Definition at line 79 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 79 of file ExGflashDetectorConstruction.hh
Referenced by Construct(), ConstructSDandField(), and SetMaterial().
G4double ExGflashDetectorConstruction::fCrystalLength private
Definition at line 77 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 77 of file ExGflashDetectorConstruction.hh
Referenced by Construct(), and ExGflashDetectorConstruction().
G4double ExGflashDetectorConstruction::fCrystalWidth private
Definition at line 76 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file ExGflashDetectorConstruction.hh
Referenced by Construct(), and ExGflashDetectorConstruction().
G4Material* ExGflashDetectorConstruction::fDetMat private
Definition at line 80 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file ExGflashDetectorConstruction.hh
Referenced by Construct(), ConstructSDandField(), and SetMaterial().
G4double ExGflashDetectorConstruction::fDLradl private
Definition at line 87 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file ExGflashDetectorConstruction.hh
Referenced by GetdLradl(), and SetLBining().
G4double ExGflashDetectorConstruction::fDRradl private
Definition at line 87 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file ExGflashDetectorConstruction.hh
Referenced by GetdRradl(), and SetRBining().
G4ThreadLocal GFlashShowerModel * ExGflashDetectorConstruction::fFastShowerModel = 0 static private
Definition at line 91 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file ExGflashDetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflashDetectorConstruction().
ExGflashMessenger* ExGflashDetectorConstruction::fGflashMessenger private
Definition at line 89 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 89 of file ExGflashDetectorConstruction.hh
Referenced by ExGflashDetectorConstruction(), and ~ExGflashDetectorConstruction().
G4ThreadLocal GFlashHitMaker * ExGflashDetectorConstruction::fHitMaker = 0 static private
Definition at line 94 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file ExGflashDetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflashDetectorConstruction().
G4int ExGflashDetectorConstruction::fNbOfCrystals private
Definition at line 74 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 74 of file ExGflashDetectorConstruction.hh
Referenced by Construct().
G4int ExGflashDetectorConstruction::fNLtot private
Definition at line 86 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 86 of file ExGflashDetectorConstruction.hh
Referenced by GetnLtot(), and SetLBining().
G4int ExGflashDetectorConstruction::fNRtot private
Definition at line 86 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 86 of file ExGflashDetectorConstruction.hh
Referenced by GetnRtot(), and SetRBining().
G4ThreadLocal GFlashHomoShowerParameterisation * ExGflashDetectorConstruction::fParameterisation = 0 static private
Definition at line 92 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 92 of file ExGflashDetectorConstruction.hh
Referenced by ConstructSDandField(), SetMaterial(), and ~ExGflashDetectorConstruction().
G4ThreadLocal GFlashParticleBounds * ExGflashDetectorConstruction::fParticleBounds = 0 static private
Definition at line 93 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 93 of file ExGflashDetectorConstruction.hh
Referenced by ConstructSDandField(), and ~ExGflashDetectorConstruction().
G4Region* ExGflashDetectorConstruction::fRegion private
Definition at line 81 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 81 of file ExGflashDetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4double ExGflashDetectorConstruction::fSDRadLen private
Definition at line 83 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 83 of file ExGflashDetectorConstruction.hh
Referenced by ConstructSDandField(), GetSDRadLen(), and SetMaterial().
G4int ExGflashDetectorConstruction::fVerbose private
Definition at line 85 of file ExGflashDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file ExGflashDetectorConstruction.hh
Referenced by GetVerbose(), and SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflasha/include/ExGflashDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflasha/src/ExGflashDetectorConstruction.cc