ECCE @ EIC Software: HadrontherapyMatrix Class Reference
HadrontherapyMatrix Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyMatrix.hh>
Public Member Functions
~HadrontherapyMatrix ()
void PrintNuclides ()
void ClearHitTrack ()
G4int * GetHitTrack (G4int i, G4int j, G4int k)
void Initialize ()
void Clear ()
G4bool Fill (G4int, G4ParticleDefinition *particleDef, G4int i, G4int j, G4int k, G4double energyDeposit, G4bool fluence=false)
void Fill (G4int i, G4int j, G4int k, G4double energyDeposit)
void StoreMatrix (G4String file, void *data, size_t psize)
void StoreFluenceData ()
void StoreDoseData ()
void StoreDoseFluenceAscii (G4String filename="")
G4int Index (G4int i, G4int j, G4int k)
G4double * GetMatrix ()
G4int GetNvoxel ()
G4int GetNumberOfVoxelAlongX ()
G4int GetNumberOfVoxelAlongY ()
G4int GetNumberOfVoxelAlongZ ()
Static Public Member Functions
static HadrontherapyMatrix * GetInstance ()
static HadrontherapyMatrix * GetInstance (G4int nX, G4int nY, G4int nZ, G4double mass)
Static Public Attributes
static G4bool secondary = false
Private Member Functions
HadrontherapyMatrix (G4int numberOfVoxelAlongX, G4int numberOfVoxelAlongY, G4int numberOfVoxelAlongZ, G4double massOfVoxel)
Private Attributes
G4int numberOfVoxelAlongX
G4int numberOfVoxelAlongY
G4int numberOfVoxelAlongZ
G4double massOfVoxel
G4double * matrix
G4int * hitTrack
G4String stdFile
G4String filename
std::ofstream ofs
std::vector< ion > ionStore
G4double doseUnit
Static Private Attributes
static HadrontherapyMatrix * instance = NULL
Detailed Description
Definition at line 97 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 97 of file HadrontherapyMatrix.hh
Constructor & Destructor Documentation
HadrontherapyMatrix::HadrontherapyMatrix (G4int numberOfVoxelAlongX, G4int numberOfVoxelAlongY, G4int numberOfVoxelAlongZ, G4double massOfVoxel) private
Definition at line 88 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 88 of file HadrontherapyMatrix.cc
References ClearHitTrack(), FatalException, G4cout, G4endl, G4Exception(), hitTrack, mass, massOfVoxel, matrix, numberOfVoxelAlongX, numberOfVoxelAlongY, and numberOfVoxelAlongZ.
Referenced by GetInstance().
HadrontherapyMatrix::~HadrontherapyMatrix ()
Definition at line 123 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 123 of file HadrontherapyMatrix.cc
References Clear(), hitTrack, and matrix.
Member Function Documentation
void HadrontherapyMatrix::Clear ()
Definition at line 131 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 131 of file HadrontherapyMatrix.cc
References ionStore.
Referenced by Initialize(), and ~HadrontherapyMatrix().
void HadrontherapyMatrix::ClearHitTrack ()
Definition at line 170 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 170 of file HadrontherapyMatrix.cc
References hitTrack, numberOfVoxelAlongX, numberOfVoxelAlongY, and numberOfVoxelAlongZ.
Referenced by HadrontherapyMatrix().
G4bool HadrontherapyMatrix::Fill (G4int trackID, G4ParticleDefinition * particleDef, G4int i, G4int j, G4int k, G4double energyDeposit, G4bool fluence = false)
Definition at line 190 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 190 of file HadrontherapyMatrix.cc
References A(), ion::dose, ion::fluence, Index(), ionStore, numberOfVoxelAlongX, numberOfVoxelAlongY, numberOfVoxelAlongZ, secondary, and Z.
void HadrontherapyMatrix::Fill (G4int i, G4int j, G4int k, G4double energyDeposit)
Definition at line 408 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 408 of file HadrontherapyMatrix.cc
References Index(), and matrix.
G4int * HadrontherapyMatrix::GetHitTrack (G4int i, G4int j, G4int k)
Definition at line 177 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 177 of file HadrontherapyMatrix.cc
References hitTrack, and Index().
HadrontherapyMatrix * HadrontherapyMatrix::GetInstance () static
Definition at line 71 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 71 of file HadrontherapyMatrix.cc
References instance.
Referenced by HadrontherapyEventAction::EndOfEventAction(), HadrontherapyLet::HadrontherapyLet(), main(), HadrontherapyDetectorSD::ProcessHits(), HadrontherapyAnalysisFileMessenger::SetNewValue(), and HadrontherapyDetectorConstruction::UpdateGeometry().
HadrontherapyMatrix * HadrontherapyMatrix::GetInstance (G4int nX, G4int nY, G4int nZ, G4double mass) static
Definition at line 79 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 79 of file HadrontherapyMatrix.cc
References HadrontherapyMatrix(), Initialize(), and instance.
G4double* HadrontherapyMatrix::GetMatrix () inline
Definition at line 156 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 156 of file HadrontherapyMatrix.hh
References matrix.
G4int HadrontherapyMatrix::GetNumberOfVoxelAlongX () inline
Definition at line 160 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 160 of file HadrontherapyMatrix.hh
References numberOfVoxelAlongX.
G4int HadrontherapyMatrix::GetNumberOfVoxelAlongY () inline
Definition at line 161 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 161 of file HadrontherapyMatrix.hh
References numberOfVoxelAlongY.
G4int HadrontherapyMatrix::GetNumberOfVoxelAlongZ () inline
Definition at line 162 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 162 of file HadrontherapyMatrix.hh
References numberOfVoxelAlongZ.
G4int HadrontherapyMatrix::GetNvoxel () inline
Definition at line 158 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 158 of file HadrontherapyMatrix.hh
References numberOfVoxelAlongZ.
G4int HadrontherapyMatrix::Index (G4int i, G4int j, G4int k) inline
Definition at line 153 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 153 of file HadrontherapyMatrix.hh
References k.
Referenced by Fill(), GetHitTrack(), StoreDoseFluenceAscii(), and StoreMatrix().
void HadrontherapyMatrix::Initialize ()
Definition at line 144 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 144 of file HadrontherapyMatrix.cc
References Clear(), matrix, numberOfVoxelAlongX, numberOfVoxelAlongY, and numberOfVoxelAlongZ.
Referenced by GetInstance().
void HadrontherapyMatrix::PrintNuclides ()
Definition at line 159 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 159 of file HadrontherapyMatrix.cc
References G4cout, G4endl, and ionStore.
void HadrontherapyMatrix::StoreDoseData ()
Definition at line 322 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 322 of file HadrontherapyMatrix.cc
References dose, ionStore, and StoreMatrix().
void HadrontherapyMatrix::StoreDoseFluenceAscii (G4String filename = "")
Definition at line 336 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 336 of file HadrontherapyMatrix.cc
References a, doseUnit, filename, G4cout, G4endl, Index(), ionStore, k, left, massOfVoxel, matrix, n, numberOfVoxelAlongX, numberOfVoxelAlongY, numberOfVoxelAlongZ, ofs, secondary, stdFile, and width.
void HadrontherapyMatrix::StoreFluenceData ()
Definition at line 313 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 313 of file HadrontherapyMatrix.cc
References ionStore, and StoreMatrix().
void HadrontherapyMatrix::StoreMatrix (G4String file, void * data, size_t psize)
Definition at line 275 of file HadrontherapyMatrix.cc.
View newest version in sPHENIX GitHub at line 275 of file HadrontherapyMatrix.cc
References G4endl, Index(), k, n, numberOfVoxelAlongX, numberOfVoxelAlongY, numberOfVoxelAlongZ, and ofs.
Referenced by StoreDoseData(), and StoreFluenceData().
Member Data Documentation
G4double HadrontherapyMatrix::doseUnit private
Definition at line 179 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 179 of file HadrontherapyMatrix.hh
Referenced by StoreDoseFluenceAscii().
G4String HadrontherapyMatrix::filename private
Definition at line 173 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 173 of file HadrontherapyMatrix.hh
Referenced by StoreDoseFluenceAscii().
G4int* HadrontherapyMatrix::hitTrack private
Definition at line 172 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 172 of file HadrontherapyMatrix.hh
Referenced by ClearHitTrack(), GetHitTrack(), HadrontherapyMatrix(), and ~HadrontherapyMatrix().
HadrontherapyMatrix * HadrontherapyMatrix::instance = NULL static private
Definition at line 165 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 165 of file HadrontherapyMatrix.hh
Referenced by GetInstance().
std::vector<ion> HadrontherapyMatrix::ionStore private
Definition at line 177 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 177 of file HadrontherapyMatrix.hh
Referenced by Clear(), Fill(), PrintNuclides(), StoreDoseData(), StoreDoseFluenceAscii(), and StoreFluenceData().
G4double HadrontherapyMatrix::massOfVoxel private
Definition at line 169 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 169 of file HadrontherapyMatrix.hh
Referenced by HadrontherapyMatrix(), and StoreDoseFluenceAscii().
G4double* HadrontherapyMatrix::matrix private
Definition at line 171 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 171 of file HadrontherapyMatrix.hh
Referenced by Fill(), GetMatrix(), HadrontherapyMatrix(), Initialize(), StoreDoseFluenceAscii(), and ~HadrontherapyMatrix().
G4int HadrontherapyMatrix::numberOfVoxelAlongX private
Definition at line 166 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 166 of file HadrontherapyMatrix.hh
Referenced by ClearHitTrack(), Fill(), GetNumberOfVoxelAlongX(), HadrontherapyMatrix(), Initialize(), StoreDoseFluenceAscii(), and StoreMatrix().
G4int HadrontherapyMatrix::numberOfVoxelAlongY private
Definition at line 167 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 167 of file HadrontherapyMatrix.hh
Referenced by ClearHitTrack(), Fill(), GetNumberOfVoxelAlongY(), HadrontherapyMatrix(), Initialize(), StoreDoseFluenceAscii(), and StoreMatrix().
G4int HadrontherapyMatrix::numberOfVoxelAlongZ private
Definition at line 168 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 168 of file HadrontherapyMatrix.hh
Referenced by ClearHitTrack(), Fill(), GetNumberOfVoxelAlongZ(), GetNvoxel(), HadrontherapyMatrix(), Initialize(), StoreDoseFluenceAscii(), and StoreMatrix().
std::ofstream HadrontherapyMatrix::ofs private
Definition at line 174 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 174 of file HadrontherapyMatrix.hh
Referenced by StoreDoseFluenceAscii(), and StoreMatrix().
G4bool HadrontherapyMatrix::secondary = false static
Definition at line 114 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 114 of file HadrontherapyMatrix.hh
Referenced by Fill(), and StoreDoseFluenceAscii().
G4String HadrontherapyMatrix::stdFile private
Definition at line 173 of file HadrontherapyMatrix.hh.
View newest version in sPHENIX GitHub at line 173 of file HadrontherapyMatrix.hh
Referenced by StoreDoseFluenceAscii().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyMatrix.hh
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapyMatrix.cc