ECCE @ EIC Software: G4INCL::TransmissionChannel Class Reference
G4INCL::TransmissionChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLTransmissionChannel.hh>
Public Member Functions
TransmissionChannel (Nucleus *n, Particle *p)
TransmissionChannel (Nucleus *n, Particle *p, const G4double TOut)
TransmissionChannel (Nucleus *n, Particle *p, const G4double kOut, const G4double cosR)
virtual ~TransmissionChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
void particleLeaves ()
Modify particle that leaves the nucleus.
G4double initializeKineticEnergyOutside ()
Kinetic energy of the transmitted particle.
Private Attributes
Nucleus *const theNucleus
Particle *const theParticle
const G4bool refraction
True if refraction should be applied.
const G4double pOutMag
Momentum of the particle outside the nucleus.
const G4double kineticEnergyOutside
Kinetic energy of the particle outside the nucleus.
const G4double cosRefractionAngle
Cosine of the refraction angle.
Detailed Description
Definition at line 48 of file G4INCLTransmissionChannel.hh.
View newest version in sPHENIX GitHub at line 48 of file G4INCLTransmissionChannel.hh
Constructor & Destructor Documentation
G4INCL::TransmissionChannel::TransmissionChannel (Nucleus * n, Particle * p)
Definition at line 42 of file G4INCLTransmissionChannel.cc.
View newest version in sPHENIX GitHub at line 42 of file G4INCLTransmissionChannel.cc
G4INCL::TransmissionChannel::TransmissionChannel (Nucleus * n, Particle * p, const G4double TOut)
Definition at line 50 of file G4INCLTransmissionChannel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4INCLTransmissionChannel.cc
G4INCL::TransmissionChannel::TransmissionChannel (Nucleus * n, Particle * p, const G4double kOut, const G4double cosR)
Definition at line 58 of file G4INCLTransmissionChannel.cc.
View newest version in sPHENIX GitHub at line 58 of file G4INCLTransmissionChannel.cc
G4INCL::TransmissionChannel::~TransmissionChannel () virtual
Definition at line 66 of file G4INCLTransmissionChannel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4INCLTransmissionChannel.cc
Member Function Documentation
void G4INCL::TransmissionChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 113 of file G4INCLTransmissionChannel.cc.
View newest version in sPHENIX GitHub at line 113 of file G4INCLTransmissionChannel.cc
References G4INCL::FinalState::addOutgoingParticle(), G4INCL::Particle::getA(), G4INCL::Particle::getEmissionQValueCorrection(), G4INCL::Particle::getEnergy(), G4INCL::Particle::getMass(), G4INCL::Particle::getPotentialEnergy(), G4INCL::Particle::getS(), G4INCL::Particle::getTableMass(), G4INCL::Particle::getZ(), particleLeaves(), G4INCL::FinalState::setTotalEnergyBeforeInteraction(), theNucleus, and theParticle.
G4double G4INCL::TransmissionChannel::initializeKineticEnergyOutside () private
Kinetic energy of the transmitted particle.
Calculate the kinetic energy of the particle outside the nucleus, if the value has not been provided as a pre-calculated argument to the constructor.
Definition at line 68 of file G4INCLTransmissionChannel.cc.
View newest version in sPHENIX GitHub at line 68 of file G4INCLTransmissionChannel.cc
References G4INCL::Particle::getA(), G4INCL::Particle::getEmissionQValueCorrection(), G4INCL::Particle::getEnergy(), G4INCL::Particle::getMass(), G4INCL::Particle::getPotentialEnergy(), G4INCL::Particle::getS(), G4INCL::Particle::getZ(), theNucleus, and theParticle.
void G4INCL::TransmissionChannel::particleLeaves () private
Modify particle that leaves the nucleus.
Modify the particle momentum and/or position when the particle leaves the nucleus.
Definition at line 84 of file G4INCLTransmissionChannel.cc.
View newest version in sPHENIX GitHub at line 84 of file G4INCLTransmissionChannel.cc
References G4INCL::Particle::adjustMomentumFromEnergy(), cosRefractionAngle, G4INCL::ThreeVector::dot(), G4INCL::Particle::getMass(), G4INCL::Particle::getMomentum(), G4INCL::Particle::getPosition(), kineticEnergyOutside, G4INCL::ThreeVector::mag2(), momentum, CLHEP::normal(), pOutMag, r2, refraction, G4INCL::Particle::setEnergy(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setPotentialEnergy(), G4INCL::Particle::setTableMass(), and theParticle.
Referenced by fillFinalState().
Member Data Documentation
const G4double G4INCL::TransmissionChannel::cosRefractionAngle private
Cosine of the refraction angle.
Definition at line 86 of file G4INCLTransmissionChannel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4INCLTransmissionChannel.hh
Referenced by particleLeaves().
const G4double G4INCL::TransmissionChannel::kineticEnergyOutside private
Kinetic energy of the particle outside the nucleus.
Definition at line 83 of file G4INCLTransmissionChannel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4INCLTransmissionChannel.hh
Referenced by particleLeaves().
const G4double G4INCL::TransmissionChannel::pOutMag private
Momentum of the particle outside the nucleus.
Definition at line 80 of file G4INCLTransmissionChannel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4INCLTransmissionChannel.hh
Referenced by particleLeaves().
const G4bool G4INCL::TransmissionChannel::refraction private
True if refraction should be applied.
Definition at line 77 of file G4INCLTransmissionChannel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4INCLTransmissionChannel.hh
Referenced by particleLeaves().
Nucleus* const G4INCL::TransmissionChannel::theNucleus private
Definition at line 73 of file G4INCLTransmissionChannel.hh.
View newest version in sPHENIX GitHub at line 73 of file G4INCLTransmissionChannel.hh
Referenced by fillFinalState(), and initializeKineticEnergyOutside().
Particle* const G4INCL::TransmissionChannel::theParticle private
Definition at line 74 of file G4INCLTransmissionChannel.hh.
View newest version in sPHENIX GitHub at line 74 of file G4INCLTransmissionChannel.hh
Referenced by fillFinalState(), initializeKineticEnergyOutside(), and particleLeaves().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLTransmissionChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLTransmissionChannel.cc