ECCE @ EIC Software: CML2Acc1 Class Reference
CML2Acc1 Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Acc1.hh>
Public Member Functions
CML2Acc1 (void)
~CML2Acc1 (void)
void Construct (G4VPhysicalVolume *PVWorld, G4double iso)
G4double getBeforeJaws_Z_PhaseSpacePosition ()
void writeInfo ()
Public Member Functions inherited from CML2Accelerator
CML2Accelerator (void)
virtual ~CML2Accelerator (void)
void reset ()
void setJaw1X (G4double val)
void setJaw2X (G4double val)
void setJaw1Y (G4double val)
void setJaw2Y (G4double val)
void setIsoCentre (G4double val)
void setidEnergy (G4int val)
void setLeavesAx (G4double val)
void setLeavesBx (G4double val)
int getidEnergy ()
Static Public Member Functions
static CML2Acc1 * GetInstance (void)
Private Member Functions
void buildMaterial_SSteel1 ()
void SetJawAperture (G4int idJaw, G4ThreeVector &centre, G4ThreeVector halfSize, G4RotationMatrix *cRotation)
bool target ()
bool primaryCollimator ()
bool vacuumWindow ()
bool flatteningFilter ()
bool ionizationChamber ()
bool Jaw1X ()
bool Jaw2X ()
bool Jaw1Y ()
bool Jaw2Y ()
bool mirror ()
bool MLC ()
Private Attributes
G4Material * steel1
CML2Acc1Messenger * acc1Messenger
G4VPhysicalVolume * PVWorld
Static Private Attributes
static CML2Acc1 * instance = 0
Additional Inherited Members
Public Attributes inherited from CML2Accelerator
G4double jaw1XAperture
G4double jaw2XAperture
G4double jaw1YAperture
G4double jaw2YAperture
G4double isoCentre
std::vector< G4double > vec_leavesA
std::vector< G4double > vec_leavesB
G4int idEnergy
Detailed Description
Definition at line 66 of file ML2Acc1.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Acc1.hh
Constructor & Destructor Documentation
CML2Acc1::CML2Acc1 (void)
Definition at line 53 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 53 of file ML2Acc1.cc
CML2Acc1::~CML2Acc1 (void)
Definition at line 60 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 60 of file ML2Acc1.cc
Member Function Documentation
void CML2Acc1::buildMaterial_SSteel1 () private
Definition at line 81 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 81 of file ML2Acc1.cc
References cm3, Acts::UnitConstants::g, and mole.
void CML2Acc1::Construct (G4VPhysicalVolume * PVWorld, G4double iso) virtual
Reimplemented from CML2Accelerator.
Definition at line 96 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 96 of file ML2Acc1.cc
bool CML2Acc1::flatteningFilter () private
Definition at line 304 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 304 of file ML2Acc1.cc
References G4Region::AddRootLogicalVolume(), cm, deg, G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), mm, G4Colour::Red(), CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), CLHEP::Hep3Vector::setZ(), and G4InuclParticleNames::z0.
G4double CML2Acc1::getBeforeJaws_Z_PhaseSpacePosition () inline virtual
Reimplemented from CML2Accelerator.
Definition at line 73 of file ML2Acc1.hh.
View newest version in sPHENIX GitHub at line 73 of file ML2Acc1.hh
CML2Acc1 * CML2Acc1::GetInstance (void) static
Definition at line 65 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 65 of file ML2Acc1.cc
References instance.
Referenced by CML2AcceleratorConstruction::design().
bool CML2Acc1::ionizationChamber () private
Definition at line 356 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 356 of file ML2Acc1.cc
References G4Region::AddRootLogicalVolume(), G4Colour::Blue(), cm, deg, G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), material(), mm, CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and G4Colour::Yellow().
bool CML2Acc1::Jaw1X () private
Definition at line 508 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 508 of file ML2Acc1.cc
References G4Region::AddRootLogicalVolume(), G4Colour::Blue(), cm, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), mm, CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), and G4Region::SetProductionCuts().
bool CML2Acc1::Jaw1Y () private
Definition at line 587 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 587 of file ML2Acc1.cc
References cm, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), mm, G4Colour::Red(), and CLHEP::Hep3Vector::set().
bool CML2Acc1::Jaw2X () private
Definition at line 551 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 551 of file ML2Acc1.cc
References cm, G4Colour::Cyan(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), mm, and CLHEP::Hep3Vector::set().
bool CML2Acc1::Jaw2Y () private
Definition at line 623 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 623 of file ML2Acc1.cc
References cm, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4Colour::Magenta(), mm, and CLHEP::Hep3Vector::set().
bool CML2Acc1::mirror () private
Definition at line 436 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 436 of file ML2Acc1.cc
References cm, deg, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), and mm.
bool CML2Acc1::MLC () private
Definition at line 659 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 659 of file ML2Acc1.cc
References cm, G4Colour::Cyan(), G4NistManager::FindOrBuildMaterial(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4Colour::Green(), G4NistManager::Instance(), int(), mm, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::setX(), and CLHEP::Hep3Vector::setY().
bool CML2Acc1::primaryCollimator () private
Definition at line 177 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 177 of file ML2Acc1.cc
References G4Region::AddRootLogicalVolume(), cm, deg, G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), G4Colour::Magenta(), CLHEP::HepRotation::rotateX(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), and G4VisAttributes::SetVisibility().
void CML2Acc1::SetJawAperture (G4int idJaw, G4ThreeVector & centre, G4ThreeVector halfSize, G4RotationMatrix * cRotation) private
Definition at line 463 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 463 of file ML2Acc1.cc
References dx, dy, dz, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::Hep3Vector::set(), theta(), x, y, and z.
bool CML2Acc1::target () private
Definition at line 113 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 113 of file ML2Acc1.cc
References cm, G4Colour::Cyan(), G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), m, G4Colour::Magenta(), G4ProductionCuts::SetProductionCut(), and G4Region::SetProductionCuts().
bool CML2Acc1::vacuumWindow () private
Definition at line 278 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 278 of file ML2Acc1.cc
References cm, deg, G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), mm, G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), and G4Colour::Yellow().
void CML2Acc1::writeInfo () virtual
Reimplemented from CML2Accelerator.
Definition at line 74 of file ML2Acc1.cc.
View newest version in sPHENIX GitHub at line 74 of file ML2Acc1.cc
References G4cout, G4endl, and mm.
Member Data Documentation
CML2Acc1Messenger* CML2Acc1::acc1Messenger private
Definition at line 80 of file ML2Acc1.hh.
View newest version in sPHENIX GitHub at line 80 of file ML2Acc1.hh
CML2Acc1 * CML2Acc1::instance = 0 static private
Definition at line 77 of file ML2Acc1.hh.
View newest version in sPHENIX GitHub at line 77 of file ML2Acc1.hh
G4VPhysicalVolume* CML2Acc1::PVWorld private
Definition at line 95 of file ML2Acc1.hh.
View newest version in sPHENIX GitHub at line 95 of file ML2Acc1.hh
G4Material* CML2Acc1::steel1 private
Definition at line 79 of file ML2Acc1.hh.
View newest version in sPHENIX GitHub at line 79 of file ML2Acc1.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Acc1.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2Acc1.cc