ECCE @ EIC Software: G4BOptnForceCommonTruncatedExp Class Reference
G4BOptnForceCommonTruncatedExp Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnForceCommonTruncatedExp.hh>
Public Member Functions
G4BOptnForceCommonTruncatedExp (G4String name)
virtual ~G4BOptnForceCommonTruncatedExp ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &)
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection processSelection)
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *)
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)
G4ILawCommonTruncatedExp * GetCommonTruncatedExpLaw ()
G4ILawForceFreeFlight * GetForceFreeFlightLaw ()
void Initialize (const G4Track *)
void UpdateForStep (const G4Step *)
void Sample ()
const G4ThreeVector & GetInitialMomentum () const
G4double GetMaximumDistance () const
void ChooseProcessToApply ()
const G4VProcess * GetProcessToApply () const
void AddCrossSection (const G4VProcess *, G4double)
size_t GetNumberOfSharing () const
void SetInteractionOccured (G4bool b)
G4bool GetInteractionOccured () const
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4ILawCommonTruncatedExp * fCommonTruncatedExpLaw
G4ILawForceFreeFlight * fForceFreeFlightLaw
G4double fTotalCrossSection
std::map< const G4VProcess
*, G4double > fCrossSections
size_t fNumberOfSharing
const G4VProcess * fProcessToApply
G4bool fInteractionOccured
G4ThreeVector fInitialMomentum
G4double fMaximumDistance
G4ParticleChangeForNothing fDummyParticleChange
Detailed Description
Definition at line 59 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BOptnForceCommonTruncatedExp.hh
Constructor & Destructor Documentation
G4BOptnForceCommonTruncatedExp::G4BOptnForceCommonTruncatedExp (G4String name)
Definition at line 34 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 34 of file G4BOptnForceCommonTruncatedExp.cc
References fCommonTruncatedExpLaw, fForceFreeFlightLaw, and fTotalCrossSection.
G4BOptnForceCommonTruncatedExp::~G4BOptnForceCommonTruncatedExp () virtual
Definition at line 47 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 47 of file G4BOptnForceCommonTruncatedExp.cc
References fCommonTruncatedExpLaw, and fForceFreeFlightLaw.
Member Function Documentation
void G4BOptnForceCommonTruncatedExp::AddCrossSection (const G4VProcess * process, G4double crossSection)
Definition at line 116 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 116 of file G4BOptnForceCommonTruncatedExp.cc
References fCrossSections, fNumberOfSharing, and fTotalCrossSection.
Referenced by G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
G4VParticleChange * G4BOptnForceCommonTruncatedExp::ApplyFinalStateBiasing (const G4BiasingProcessInterface * callingProcess, const G4Track * track, const G4Step * step, G4bool & forceFinalState) virtual
Implements G4VBiasingOperation.
Definition at line 76 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 76 of file G4BOptnForceCommonTruncatedExp.cc
References fDummyParticleChange, fInteractionOccured, fProcessToApply, G4BiasingProcessInterface::GetAlongStepGPIL(), G4BiasingProcessInterface::GetPostStepGPIL(), G4BiasingProcessInterface::GetWrappedProcess(), G4ParticleChangeForNothing::Initialize(), and G4VProcess::PostStepDoIt().
void G4BOptnForceCommonTruncatedExp::ChooseProcessToApply ()
Definition at line 167 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 167 of file G4BOptnForceCommonTruncatedExp.cc
References fCrossSections, fProcessToApply, fTotalCrossSection, G4UniformRand, and it.
Referenced by Sample().
virtual G4double G4BOptnForceCommonTruncatedExp::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition *) inline virtual
Implements G4VBiasingOperation.
Definition at line 78 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 78 of file G4BOptnForceCommonTruncatedExp.hh
References DBL_MAX.
virtual G4VParticleChange* G4BOptnForceCommonTruncatedExp::GenerateBiasingFinalState (const G4Track * , const G4Step *) inline virtual
Implements G4VBiasingOperation.
Definition at line 81 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 81 of file G4BOptnForceCommonTruncatedExp.hh
G4ILawCommonTruncatedExp* G4BOptnForceCommonTruncatedExp::GetCommonTruncatedExpLaw () inline
Definition at line 88 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 88 of file G4BOptnForceCommonTruncatedExp.hh
References fCommonTruncatedExpLaw.
G4ILawForceFreeFlight* G4BOptnForceCommonTruncatedExp::GetForceFreeFlightLaw () inline
Definition at line 92 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BOptnForceCommonTruncatedExp.hh
References fForceFreeFlightLaw.
const G4ThreeVector& G4BOptnForceCommonTruncatedExp::GetInitialMomentum () const inline
Definition at line 100 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 100 of file G4BOptnForceCommonTruncatedExp.hh
References fInitialMomentum.
Referenced by G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
G4bool G4BOptnForceCommonTruncatedExp::GetInteractionOccured () const inline
Definition at line 107 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 107 of file G4BOptnForceCommonTruncatedExp.hh
References fInteractionOccured.
Referenced by G4BOptrForceCollision::OperationApplied().
G4double G4BOptnForceCommonTruncatedExp::GetMaximumDistance () const inline
Definition at line 101 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 101 of file G4BOptnForceCommonTruncatedExp.hh
References fMaximumDistance.
Referenced by G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
size_t G4BOptnForceCommonTruncatedExp::GetNumberOfSharing () const inline
Definition at line 105 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 105 of file G4BOptnForceCommonTruncatedExp.hh
References fNumberOfSharing.
Referenced by G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
const G4VProcess* G4BOptnForceCommonTruncatedExp::GetProcessToApply () const inline
Definition at line 103 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 103 of file G4BOptnForceCommonTruncatedExp.hh
References fProcessToApply.
void G4BOptnForceCommonTruncatedExp::Initialize (const G4Track * track)
Definition at line 124 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 124 of file G4BOptnForceCommonTruncatedExp.cc
References DBL_MIN, G4VSolid::DistanceToOut(), fCommonTruncatedExpLaw, fCrossSections, fInitialMomentum, fInteractionOccured, fMaximumDistance, fNumberOfSharing, fProcessToApply, fTotalCrossSection, G4VPhysicalVolume::GetLogicalVolume(), G4Track::GetMomentum(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4LogicalVolume::GetSolid(), G4TransportationManager::GetTransportationManager(), G4Track::GetVolume(), and G4ILawCommonTruncatedExp::SetMaximumDistance().
Referenced by G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
virtual G4double G4BOptnForceCommonTruncatedExp::ProposeAlongStepLimit (const G4BiasingProcessInterface *) inline virtual
Reimplemented from G4VBiasingOperation.
Definition at line 71 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 71 of file G4BOptnForceCommonTruncatedExp.hh
References DBL_MAX.
G4GPILSelection G4BOptnForceCommonTruncatedExp::ProposeGPILSelection (const G4GPILSelection processSelection) virtual
Reimplemented from G4VBiasingOperation.
Definition at line 70 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 70 of file G4BOptnForceCommonTruncatedExp.cc
References NotCandidateForSelection.
const G4VBiasingInteractionLaw * G4BOptnForceCommonTruncatedExp::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * callingProcess, G4ForceCondition & proposeForceCondition) virtual
Implements G4VBiasingOperation.
Definition at line 54 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 54 of file G4BOptnForceCommonTruncatedExp.cc
References fCommonTruncatedExpLaw, fForceFreeFlightLaw, Forced, fProcessToApply, and G4BiasingProcessInterface::GetWrappedProcess().
void G4BOptnForceCommonTruncatedExp::Sample ()
Definition at line 158 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 158 of file G4BOptnForceCommonTruncatedExp.cc
References ChooseProcessToApply(), fCommonTruncatedExpLaw, fCrossSections, fProcessToApply, fTotalCrossSection, G4VBiasingInteractionLaw::Sample(), G4ILawCommonTruncatedExp::SetForceCrossSection(), and G4ILawCommonTruncatedExp::SetSelectedProcessXSfraction().
Referenced by G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
void G4BOptnForceCommonTruncatedExp::SetInteractionOccured (G4bool b) inline
Definition at line 106 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 106 of file G4BOptnForceCommonTruncatedExp.hh
References b, and fInteractionOccured.
void G4BOptnForceCommonTruncatedExp::UpdateForStep (const G4Step * step)
Definition at line 146 of file G4BOptnForceCommonTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 146 of file G4BOptnForceCommonTruncatedExp.cc
References fCommonTruncatedExpLaw, fCrossSections, fMaximumDistance, fNumberOfSharing, fProcessToApply, fTotalCrossSection, G4ILawCommonTruncatedExp::GetMaximumDistance(), G4Step::GetStepLength(), and G4VBiasingInteractionLaw::UpdateForStep().
Referenced by G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
Member Data Documentation
G4ILawCommonTruncatedExp* G4BOptnForceCommonTruncatedExp::fCommonTruncatedExpLaw private
Definition at line 110 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 110 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by G4BOptnForceCommonTruncatedExp(), GetCommonTruncatedExpLaw(), Initialize(), ProvideOccurenceBiasingInteractionLaw(), Sample(), UpdateForStep(), and ~G4BOptnForceCommonTruncatedExp().
std::map< const G4VProcess*, G4double > G4BOptnForceCommonTruncatedExp::fCrossSections private
Definition at line 113 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 113 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by AddCrossSection(), ChooseProcessToApply(), Initialize(), Sample(), and UpdateForStep().
G4ParticleChangeForNothing G4BOptnForceCommonTruncatedExp::fDummyParticleChange private
Definition at line 119 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 119 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by ApplyFinalStateBiasing().
G4ILawForceFreeFlight* G4BOptnForceCommonTruncatedExp::fForceFreeFlightLaw private
Definition at line 111 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 111 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by G4BOptnForceCommonTruncatedExp(), GetForceFreeFlightLaw(), ProvideOccurenceBiasingInteractionLaw(), and ~G4BOptnForceCommonTruncatedExp().
G4ThreeVector G4BOptnForceCommonTruncatedExp::fInitialMomentum private
Definition at line 117 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 117 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by GetInitialMomentum(), and Initialize().
G4bool G4BOptnForceCommonTruncatedExp::fInteractionOccured private
Definition at line 116 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 116 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by ApplyFinalStateBiasing(), GetInteractionOccured(), Initialize(), and SetInteractionOccured().
G4double G4BOptnForceCommonTruncatedExp::fMaximumDistance private
Definition at line 118 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 118 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by GetMaximumDistance(), Initialize(), and UpdateForStep().
size_t G4BOptnForceCommonTruncatedExp::fNumberOfSharing private
Definition at line 114 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 114 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by AddCrossSection(), GetNumberOfSharing(), Initialize(), and UpdateForStep().
const G4VProcess* G4BOptnForceCommonTruncatedExp::fProcessToApply private
Definition at line 115 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 115 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by ApplyFinalStateBiasing(), ChooseProcessToApply(), GetProcessToApply(), Initialize(), ProvideOccurenceBiasingInteractionLaw(), Sample(), and UpdateForStep().
G4double G4BOptnForceCommonTruncatedExp::fTotalCrossSection private
Definition at line 112 of file G4BOptnForceCommonTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 112 of file G4BOptnForceCommonTruncatedExp.hh
Referenced by AddCrossSection(), ChooseProcessToApply(), G4BOptnForceCommonTruncatedExp(), Initialize(), Sample(), and UpdateForStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnForceCommonTruncatedExp.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BOptnForceCommonTruncatedExp.cc