ECCE @ EIC Software: G4IT Class Reference
G4IT Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4IT.hh>
Public Member Functions
G4IT ()
G4IT (G4Track *)
virtual ~G4IT ()
virtual void Print () const
virtual const G4String & GetName () const =0
virtual G4bool diff (const G4IT &right) const =0
virtual G4bool equal (const G4IT &right) const =0
G4bool operator< (const G4IT &right) const
G4bool operator== (const G4IT &right) const
G4bool operator!= (const G4IT &right) const
void SetTrack (G4Track *)
G4Track * GetTrack ()
const G4Track * GetTrack () const
void RecordCurrentPositionNTime ()
const G4ThreeVector & GetPosition () const
double operator[] (int i) const
const G4ThreeVector & GetPreStepPosition () const
G4double GetPreStepLocalTime () const
G4double GetPreStepGlobalTime () const
void SetPrevious (G4IT *)
void SetNext (G4IT *)
G4IT * GetPrevious ()
G4IT * GetNext ()
const G4IT * GetPrevious () const
const G4IT * GetNext () const
void SetITBox (G4ITBox *)
const G4ITBox * GetITBox () const
void TakeOutBox ()
void SetNode (G4KDNode_Base *)
G4KDNode_Base * GetNode () const
void SetParentID (int, int)
void GetParentID (int &, int &)
G4TrackingInformation * GetTrackingInfo ()
G4TrackListNode * GetListNode ()
void SetListNode (G4TrackListNode *node)
virtual const G4ITType GetITType () const =0
virtual G4ITType GetITSubType () const
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
const G4String & GetType () const
Protected Member Functions
G4IT (const G4IT &)
G4IT & operator= (const G4IT &)
Protected Attributes
G4Track * fpTrack
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Private Attributes
G4ITBox * fpITBox
G4IT * fpPreviousIT
G4IT * fpNextIT
G4KDNode_Base * fpKDNode
int fParentID_A
int fParentID_B
G4TrackingInformation * fpTrackingInformation
G4TrackListNode * fpTrackNode
Detailed Description
G4IT is a interface which allows the inheriting object to be tracked using G4ITStepProcessor The inheriting class must implement the operator < , == and != in order to enable the sorting out. also the concrete header of MyIT ("MyIt.hh") should contain : ITDef(MyIT) and the source of MyIT.cc : ITImp(MyIT)
Definition at line 87 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 87 of file G4IT.hh
Constructor & Destructor Documentation
G4IT::G4IT ()
Definition at line 67 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 67 of file G4IT.cc
References fParentID_A, fParentID_B, fpITBox, fpKDNode, and fpTrackNode.
G4IT::G4IT (G4Track * aTrack)
Definition at line 124 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 124 of file G4IT.cc
References fParentID_A, fParentID_B, fpITBox, fpKDNode, fpTrack, fpTrackNode, and RecordCurrentPositionNTime().
G4IT::~G4IT () virtual
Definition at line 160 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 160 of file G4IT.cc
References fpTrackingInformation, and TakeOutBox().
G4IT::G4IT (const G4IT &) protected
Definition at line 82 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 82 of file G4IT.cc
References fParentID_A, fParentID_B, fpITBox, fpKDNode, and fpTrackNode.
Member Function Documentation
virtual G4bool G4IT::diff (const G4IT & right) const pure virtual
Referenced by operator<().
virtual G4bool G4IT::equal (const G4IT & right) const pure virtual
Referenced by operator==().
const G4ITBox * G4IT::GetITBox () const inline
Definition at line 183 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 183 of file G4IT.hh
References fpITBox.
virtual G4ITType G4IT::GetITSubType () const inline virtual
Reimplemented in G4Molecule.
Definition at line 159 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 159 of file G4IT.hh
Referenced by G4ITTrackHolder::PushDelayed(), and G4ITTrackHolder::PushTo().
virtual const G4ITType G4IT::GetITType () const pure virtual
Referenced by operator<(), operator==(), and G4AllITFinder::Push().
G4TrackListNode* G4IT::GetListNode () inline
Definition at line 148 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 148 of file G4IT.hh
References fpTrackNode.
Referenced by G4FastList< G4Track >::__GetNode(), G4FastList< G4Track >::Flag(), G4FastList< G4Track >::GetList(), and G4FastList< G4Track >::GetNode().
virtual const G4String& G4IT::GetName () const pure virtual
Implemented in G4Molecule.
Referenced by G4FastList< G4Track >::__GetNode(), G4ITTrackHolder::_PushTrack(), G4ITModelProcessor::CalculateMinTimeStep(), G4FastList< G4Track >::CheckFlag(), G4ITStepProcessor::ComputeInteractionLength(), G4ITModelProcessor::ComputeTrackReaction(), G4DNABrownianTransportation::Diffusion(), G4FastList< G4Track >::Flag(), G4ITTrackHolder::KillTracks(), G4ITSteppingVerbose::PostStepVerbose(), G4ITSteppingVerbose::PreStepVerbose(), and G4ITSteppingVerbose::TrackingStarted().
G4IT * G4IT::GetNext () inline
Definition at line 208 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 208 of file G4IT.hh
References fpNextIT.
Referenced by G4ITBox::Extract(), G4ITBox::TransferTo(), and G4ITBox::~G4ITBox().
const G4IT * G4IT::GetNext () const inline
Definition at line 245 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 245 of file G4IT.hh
References fpNextIT.
G4KDNode_Base * G4IT::GetNode () const inline
Definition at line 255 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 255 of file G4IT.hh
References fpKDNode.
void G4IT::GetParentID (int & p_a, int & p_b) inline
Definition at line 234 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 234 of file G4IT.hh
References fParentID_A, and fParentID_B.
const G4ThreeVector & G4IT::GetPosition () const
Definition at line 214 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 214 of file G4IT.cc
References fpTrack, G4Track::GetPosition(), and GetTrack().
G4double G4IT::GetPreStepGlobalTime () const
Definition at line 228 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 228 of file G4IT.cc
References fpTrackingInformation, and G4TrackingInformation::GetPreStepGlobalTime().
G4double G4IT::GetPreStepLocalTime () const
Definition at line 233 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 233 of file G4IT.cc
References fpTrackingInformation, and G4TrackingInformation::GetPreStepLocalTime().
const G4ThreeVector & G4IT::GetPreStepPosition () const
Definition at line 238 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 238 of file G4IT.cc
References fpTrackingInformation, and G4TrackingInformation::GetPreStepPosition().
G4IT * G4IT::GetPrevious () inline
Definition at line 203 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 203 of file G4IT.hh
References fpPreviousIT.
Referenced by G4ITBox::Extract(), and G4ITBox::FindIT().
const G4IT * G4IT::GetPrevious () const inline
Definition at line 240 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 240 of file G4IT.hh
References fpPreviousIT.
G4Track * G4IT::GetTrack () inline
Definition at line 218 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 218 of file G4IT.hh
References fpTrack.
Referenced by G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), and GetPosition().
const G4Track * G4IT::GetTrack () const inline
Definition at line 223 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 223 of file G4IT.hh
References fpTrack.
G4TrackingInformation* G4IT::GetTrackingInfo () inline
Definition at line 143 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 143 of file G4IT.hh
References fpTrackingInformation.
Referenced by G4ITTransportation::AlongStepGetPhysicalInteractionLength(), ITTrackingInteractivity::AppendStep(), G4DNABrownianTransportation::ComputeGeomLimit(), G4ITStepProcessor::DoDefinePhysicalStepLength(), ITTrackingInteractivity::EndTracking(), G4ITStepProcessor::InitDefineStep(), G4ITLeadingTracks::PrepareLeadingTracks(), G4ITLeadingTracks::Reset(), G4ITStepProcessor::SetInitialStep(), G4ITStepProcessor::SetTrack(), G4ITStepProcessor::SetupMembers(), ITTrackingInteractivity::StartTracking(), and G4VITProcess::StartTracking().
G4bool G4IT::operator!= (const G4IT & right) const
Definition at line 202 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 202 of file G4IT.cc
References operator==().
G4bool G4IT::operator< (const G4IT & right) const
Definition at line 180 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 180 of file G4IT.cc
References diff(), and GetITType().
G4IT & G4IT::operator= (const G4IT & right) protected
Definition at line 97 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 97 of file G4IT.cc
References FatalException, fParentID_A, fParentID_B, fpITBox, fpKDNode, fpNextIT, fpPreviousIT, fpTrack, fpTrackingInformation, fpTrackNode, and G4Exception().
G4bool G4IT::operator== (const G4IT & right) const
Definition at line 193 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 193 of file G4IT.cc
References equal(), and GetITType().
Referenced by operator!=().
double G4IT::operator[] (int i) const
Definition at line 207 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 207 of file G4IT.cc
References fpTrack, and G4Track::GetPosition().
virtual void G4IT::Print (void) const inline virtual
Reimplemented from G4VUserTrackInformation.
Definition at line 97 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 97 of file G4IT.hh
void G4IT::RecordCurrentPositionNTime ()
Definition at line 220 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 220 of file G4IT.cc
References fpTrack, fpTrackingInformation, and G4TrackingInformation::RecordCurrentPositionNTime().
Referenced by G4IT().
void G4IT::SetITBox (G4ITBox * aITBox) inline
Definition at line 188 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 188 of file G4IT.hh
References fpITBox.
Referenced by G4ITBox::Extract(), and G4ITBox::Push().
void G4IT::SetListNode (G4TrackListNode * node) inline
Definition at line 152 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 152 of file G4IT.hh
References fpTrackNode.
Referenced by G4FastListNode< G4Track >::DetachYourSelf(), and G4FastList< G4Track >::Flag().
void G4IT::SetNext (G4IT * aIT) inline
Definition at line 198 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 198 of file G4IT.hh
References fpNextIT.
Referenced by G4ITBox::Extract(), and G4ITBox::Push().
void G4IT::SetNode (G4KDNode_Base * aNode) inline
Definition at line 250 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 250 of file G4IT.hh
References fpKDNode.
void G4IT::SetParentID (int p_a, int p_b) inline
Definition at line 228 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 228 of file G4IT.hh
References fParentID_A, and fParentID_B.
Referenced by G4ITModelProcessor::ComputeTrackReaction().
void G4IT::SetPrevious (G4IT * aIT) inline
Definition at line 193 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 193 of file G4IT.hh
References fpPreviousIT.
Referenced by G4ITBox::Extract(), and G4ITBox::Push().
void G4IT::SetTrack (G4Track * track) inline
Definition at line 213 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 213 of file G4IT.hh
References fpTrack, and track.
void G4IT::TakeOutBox ()
Definition at line 139 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 139 of file G4IT.cc
References G4ITBox::Extract(), fpITBox, fpKDNode, fpTrackNode, and InactiveNode().
Referenced by ~G4IT().
Member Data Documentation
int G4IT::fParentID_A private
Definition at line 175 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 175 of file G4IT.hh
Referenced by G4IT(), GetParentID(), operator=(), and SetParentID().
int G4IT::fParentID_B private
Definition at line 176 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 176 of file G4IT.hh
Referenced by G4IT(), GetParentID(), operator=(), and SetParentID().
G4ITBox* G4IT::fpITBox private
Definition at line 170 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 170 of file G4IT.hh
Referenced by G4IT(), GetITBox(), operator=(), SetITBox(), and TakeOutBox().
G4KDNode_Base* G4IT::fpKDNode private
Definition at line 173 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 173 of file G4IT.hh
Referenced by G4IT(), GetNode(), operator=(), SetNode(), and TakeOutBox().
G4IT* G4IT::fpNextIT private
Definition at line 172 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 172 of file G4IT.hh
Referenced by GetNext(), operator=(), and SetNext().
G4IT* G4IT::fpPreviousIT private
Definition at line 171 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 171 of file G4IT.hh
Referenced by GetPrevious(), operator=(), and SetPrevious().
G4Track* G4IT::fpTrack protected
Definition at line 167 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 167 of file G4IT.hh
Referenced by G4Molecule::BuildTrack(), G4IT(), GetPosition(), GetTrack(), operator=(), operator[](), RecordCurrentPositionNTime(), SetTrack(), and G4Molecule::~G4Molecule().
G4TrackingInformation* G4IT::fpTrackingInformation private
Definition at line 178 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 178 of file G4IT.hh
Referenced by GetPreStepGlobalTime(), GetPreStepLocalTime(), GetPreStepPosition(), GetTrackingInfo(), operator=(), RecordCurrentPositionNTime(), and ~G4IT().
G4TrackListNode* G4IT::fpTrackNode private
Definition at line 179 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 179 of file G4IT.hh
Referenced by G4IT(), GetListNode(), operator=(), SetListNode(), and TakeOutBox().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4IT.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4IT.cc