ECCE @ EIC Software: XrayFluoAnalysisMessenger Class Reference
XrayFluoAnalysisMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoAnalysisMessenger.hh>
Public Member Functions
XrayFluoAnalysisMessenger (XrayFluoAnalysisManager *)
~XrayFluoAnalysisMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
XrayFluoAnalysisManager * xrayFluoAnalysis
G4UIdirectory * XrayFluoAnalysisDir
G4UIcmdWithAString * outputFileCommand
G4UIcmdWithABool * physicFlagCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 55 of file XrayFluoAnalysisMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file XrayFluoAnalysisMessenger.hh
Constructor & Destructor Documentation
XrayFluoAnalysisMessenger::XrayFluoAnalysisMessenger (XrayFluoAnalysisManager * analysisManager)
Definition at line 40 of file XrayFluoAnalysisMessenger.cc.
View newest version in sPHENIX GitHub at line 40 of file XrayFluoAnalysisMessenger.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, outputFileCommand, physicFlagCmd, G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithABool::SetParameterName(), and XrayFluoAnalysisDir.
XrayFluoAnalysisMessenger::~XrayFluoAnalysisMessenger ()
Definition at line 64 of file XrayFluoAnalysisMessenger.cc.
View newest version in sPHENIX GitHub at line 64 of file XrayFluoAnalysisMessenger.cc
References XrayFluoAnalysisDir.
Member Function Documentation
void XrayFluoAnalysisMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 73 of file XrayFluoAnalysisMessenger.cc.
View newest version in sPHENIX GitHub at line 73 of file XrayFluoAnalysisMessenger.cc
References G4UIcmdWithABool::GetNewBoolValue(), outputFileCommand, physicFlagCmd, XrayFluoAnalysisManager::SetOutputFileName(), XrayFluoAnalysisManager::SetPhysicFlag(), and xrayFluoAnalysis.
Member Data Documentation
G4UIcmdWithAString* XrayFluoAnalysisMessenger::outputFileCommand private
Definition at line 69 of file XrayFluoAnalysisMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file XrayFluoAnalysisMessenger.hh
Referenced by SetNewValue(), and XrayFluoAnalysisMessenger().
G4UIcmdWithABool* XrayFluoAnalysisMessenger::physicFlagCmd private
Definition at line 70 of file XrayFluoAnalysisMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file XrayFluoAnalysisMessenger.hh
Referenced by SetNewValue(), and XrayFluoAnalysisMessenger().
XrayFluoAnalysisManager* XrayFluoAnalysisMessenger::xrayFluoAnalysis private
Definition at line 67 of file XrayFluoAnalysisMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file XrayFluoAnalysisMessenger.hh
Referenced by SetNewValue().
G4UIdirectory* XrayFluoAnalysisMessenger::XrayFluoAnalysisDir private
Definition at line 68 of file XrayFluoAnalysisMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file XrayFluoAnalysisMessenger.hh
Referenced by XrayFluoAnalysisMessenger(), and ~XrayFluoAnalysisMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoAnalysisMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoAnalysisMessenger.cc