ECCE @ EIC Software: G4INCL::ParticleEntryAvatar Class Reference
G4INCL::ParticleEntryAvatar Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLParticleEntryAvatar.hh>
Public Member Functions
ParticleEntryAvatar (G4double, G4INCL::Nucleus *, G4INCL::Particle *)
virtual ~ParticleEntryAvatar ()
virtual G4INCL::IChannel * getChannel ()
ParticleList getParticles () const
virtual void preInteraction ()
virtual void postInteraction (FinalState *)
std::string dump () const
Public Member Functions inherited from G4INCL::IAvatar
IAvatar ()
IAvatar (G4double time)
virtual ~IAvatar ()
FinalState * getFinalState ()
void fillFinalState (FinalState *fs)
G4double getTime () const
AvatarType getType () const
G4bool isACollision () const
G4bool isADecay () const
void setType (AvatarType t)
long getID () const
std::string toString ()
Private Attributes
Nucleus * theNucleus
Particle * theParticle
Additional Inherited Members
Protected Attributes inherited from G4INCL::IAvatar
G4double theTime
Detailed Description
Definition at line 47 of file G4INCLParticleEntryAvatar.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLParticleEntryAvatar.hh
Constructor & Destructor Documentation
G4INCL::ParticleEntryAvatar::ParticleEntryAvatar (G4double time, G4INCL::Nucleus * nucleus, G4INCL::Particle * particle)
Definition at line 47 of file G4INCLParticleEntryAvatar.cc.
View newest version in sPHENIX GitHub at line 47 of file G4INCLParticleEntryAvatar.cc
References G4INCL::ParticleEntryAvatarType, and G4INCL::IAvatar::setType().
G4INCL::ParticleEntryAvatar::~ParticleEntryAvatar () virtual
Definition at line 55 of file G4INCLParticleEntryAvatar.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLParticleEntryAvatar.cc
Member Function Documentation
std::string G4INCL::ParticleEntryAvatar::dump () const virtual
Implements G4INCL::IAvatar.
Definition at line 58 of file G4INCLParticleEntryAvatar.cc.
View newest version in sPHENIX GitHub at line 58 of file G4INCLParticleEntryAvatar.cc
References G4INCL::Particle::dump(), theParticle, and G4INCL::IAvatar::theTime.
IChannel * G4INCL::ParticleEntryAvatar::getChannel () virtual
Implements G4INCL::IAvatar.
Definition at line 71 of file G4INCLParticleEntryAvatar.cc.
View newest version in sPHENIX GitHub at line 71 of file G4INCLParticleEntryAvatar.cc
References theNucleus, and theParticle.
ParticleList G4INCL::ParticleEntryAvatar::getParticles () const inline virtual
Implements G4INCL::IAvatar.
Definition at line 52 of file G4INCLParticleEntryAvatar.hh.
View newest version in sPHENIX GitHub at line 52 of file G4INCLParticleEntryAvatar.hh
References theParticle.
void G4INCL::ParticleEntryAvatar::postInteraction (FinalState *) virtual
Implements G4INCL::IAvatar.
Definition at line 67 of file G4INCLParticleEntryAvatar.cc.
View newest version in sPHENIX GitHub at line 67 of file G4INCLParticleEntryAvatar.cc
References G4INCL::Particle::rpCorrelate(), and theParticle.
virtual void G4INCL::ParticleEntryAvatar::preInteraction () inline virtual
Implements G4INCL::IAvatar.
Definition at line 58 of file G4INCLParticleEntryAvatar.hh.
View newest version in sPHENIX GitHub at line 58 of file G4INCLParticleEntryAvatar.hh
Member Data Documentation
Nucleus* G4INCL::ParticleEntryAvatar::theNucleus private
Definition at line 63 of file G4INCLParticleEntryAvatar.hh.
View newest version in sPHENIX GitHub at line 63 of file G4INCLParticleEntryAvatar.hh
Referenced by getChannel().
Particle* G4INCL::ParticleEntryAvatar::theParticle private
Definition at line 64 of file G4INCLParticleEntryAvatar.hh.
View newest version in sPHENIX GitHub at line 64 of file G4INCLParticleEntryAvatar.hh
Referenced by dump(), getChannel(), getParticles(), and postInteraction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLParticleEntryAvatar.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLParticleEntryAvatar.cc