ECCE @ EIC Software: G4LEPTSDiffXS Class Reference
G4LEPTSDiffXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4LEPTSDiffXS.hh>
Public Member Functions
G4LEPTSDiffXS (std::string)
void readDXS ()
void BuildCDXS ()
void BuildCDXS (G4double, G4double)
void NormalizeCDXS ()
void InterpolateCDXS ()
void PrintDXS (int)
G4double SampleAngle (G4double)
G4double SampleAngleMT (G4double, G4double)
G4double SampleAngleEthylene (G4double, G4double)
G4bool IsFileFound () const
Private Attributes
std::string fileName
int NumAng
int INumAng
int NumEn
char DXSTypeName [8]
int DXSType
G4double Eb [100]
G4double DXS [100][190]
G4double CDXS [100][190]
G4double ICDXS [100][19000]
G4double KT [100][190]
G4double IKT [100][19000]
G4bool bFileFound
Detailed Description
Definition at line 32 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 32 of file G4LEPTSDiffXS.hh
Constructor & Destructor Documentation
G4LEPTSDiffXS::G4LEPTSDiffXS (std::string file)
Definition at line 41 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 41 of file G4LEPTSDiffXS.cc
References file.
Member Function Documentation
void G4LEPTSDiffXS::BuildCDXS ()
Definition at line 147 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 147 of file G4LEPTSDiffXS.cc
void G4LEPTSDiffXS::BuildCDXS (G4double E, G4double El)
Definition at line 124 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 124 of file G4LEPTSDiffXS.cc
References sum.
void G4LEPTSDiffXS::InterpolateCDXS ()
Definition at line 172 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 172 of file G4LEPTSDiffXS.cc
References dx, e, eps, G4Exp(), x, x1, x2, y1, y2, z1, and z2.
G4bool G4LEPTSDiffXS::IsFileFound () const inline
Definition at line 48 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 48 of file G4LEPTSDiffXS.hh
References bFileFound.
void G4LEPTSDiffXS::NormalizeCDXS ()
Definition at line 155 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 155 of file G4LEPTSDiffXS.cc
void G4LEPTSDiffXS::PrintDXS (int NE)
Definition at line 330 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 330 of file G4LEPTSDiffXS.cc
References G4cout, G4endl, and NE.
void G4LEPTSDiffXS::readDXS ()
Definition at line 54 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 54 of file G4LEPTSDiffXS.cc
References A(), E, fclose(), fp, G4cout, G4endl, CLHEP::twopi, and void().
G4double G4LEPTSDiffXS::SampleAngle (G4double Energy)
Definition at line 219 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 219 of file G4LEPTSDiffXS.cc
References G4UniformRand, CLHEP::twopi, and x.
G4double G4LEPTSDiffXS::SampleAngleEthylene (G4double E, G4double El)
Definition at line 251 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 251 of file G4LEPTSDiffXS.cc
G4double G4LEPTSDiffXS::SampleAngleMT (G4double Energy, G4double Elost)
Definition at line 263 of file G4LEPTSDiffXS.cc.
View newest version in sPHENIX GitHub at line 263 of file G4LEPTSDiffXS.cc
References e, G4UniformRand, and x.
Member Data Documentation
G4bool G4LEPTSDiffXS::bFileFound private
Definition at line 65 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 65 of file G4LEPTSDiffXS.hh
Referenced by IsFileFound().
G4double G4LEPTSDiffXS::CDXS[100][190] private
Definition at line 61 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 61 of file G4LEPTSDiffXS.hh
G4double G4LEPTSDiffXS::DXS[100][190] private
Definition at line 61 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 61 of file G4LEPTSDiffXS.hh
int G4LEPTSDiffXS::DXSType private
Definition at line 58 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 58 of file G4LEPTSDiffXS.hh
char G4LEPTSDiffXS::DXSTypeName[8] private
Definition at line 57 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 57 of file G4LEPTSDiffXS.hh
G4double G4LEPTSDiffXS::Eb[100] private
Definition at line 59 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 59 of file G4LEPTSDiffXS.hh
std::string G4LEPTSDiffXS::fileName private
Definition at line 53 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 53 of file G4LEPTSDiffXS.hh
G4double G4LEPTSDiffXS::ICDXS[100][19000] private
Definition at line 61 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 61 of file G4LEPTSDiffXS.hh
G4double G4LEPTSDiffXS::IKT[100][19000] private
Definition at line 63 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LEPTSDiffXS.hh
int G4LEPTSDiffXS::INumAng private
Definition at line 55 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 55 of file G4LEPTSDiffXS.hh
G4double G4LEPTSDiffXS::KT[100][190] private
Definition at line 63 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LEPTSDiffXS.hh
int G4LEPTSDiffXS::NumAng private
Definition at line 54 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 54 of file G4LEPTSDiffXS.hh
int G4LEPTSDiffXS::NumEn private
Definition at line 56 of file G4LEPTSDiffXS.hh.
View newest version in sPHENIX GitHub at line 56 of file G4LEPTSDiffXS.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4LEPTSDiffXS.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4LEPTSDiffXS.cc