ECCE @ EIC Software: G4SPSPosDistribution Class Reference
G4SPSPosDistribution Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4SPSPosDistribution.hh>
Classes
struct thread_data_t
Public Member Functions
G4SPSPosDistribution ()
~G4SPSPosDistribution ()
void SetPosDisType (G4String)
void SetPosDisShape (G4String)
void SetCentreCoords (G4ThreeVector)
void SetPosRot1 (G4ThreeVector)
void SetPosRot2 (G4ThreeVector)
void SetHalfX (G4double)
void SetHalfY (G4double)
void SetHalfZ (G4double)
void SetRadius (G4double)
void SetRadius0 (G4double)
void SetBeamSigmaInR (G4double)
void SetBeamSigmaInX (G4double)
void SetBeamSigmaInY (G4double)
void SetParAlpha (G4double)
void SetParTheta (G4double)
void SetParPhi (G4double)
void ConfineSourceToVolume (G4String)
void SetBiasRndm (G4SPSRandomGenerator *a)
void SetVerbosity (G4int a)
G4ThreeVector GenerateOne ()
G4String GetPosDisType () const
G4String GetPosDisShape () const
G4ThreeVector GetCentreCoords () const
G4double GetHalfX () const
G4double GetHalfY () const
G4double GetHalfZ () const
G4double GetRadius () const
G4double GetRadius0 () const
G4double GetParAlpha () const
G4double GetParTheta () const
G4double GetParPhi () const
const G4ThreeVector & GetRotx () const
const G4ThreeVector & GetRoty () const
const G4ThreeVector & GetRotz () const
G4bool GetConfined () const
const G4String & GetConfineVolume () const
G4ThreeVector GetSideRefVec1 () const
G4ThreeVector GetSideRefVec2 () const
G4ThreeVector GetSideRefVec3 () const
G4String GetSourcePosType () const
G4ThreeVector GetParticlePos () const
Private Member Functions
void GenerateRotationMatrices ()
void GeneratePointSource (G4ThreeVector &outoutPos)
void GeneratePointsInBeam (G4ThreeVector &outoutPos)
void GeneratePointsInPlane (G4ThreeVector &outoutPos)
void GeneratePointsOnSurface (G4ThreeVector &outputPos)
void GeneratePointsInVolume (G4ThreeVector &outputPos)
G4bool IsSourceConfined (G4ThreeVector &outputPos)
Private Attributes
G4String SourcePosType
G4String Shape
G4ThreeVector CentreCoords
G4ThreeVector Rotx
G4ThreeVector Roty
G4ThreeVector Rotz
G4double halfx
G4double halfy
G4double halfz
G4double Radius
G4double Radius0
G4double SR
G4double SX
G4double SY
G4double ParAlpha
G4double ParTheta
G4double ParPhi
G4bool Confine
G4String VolName
G4int verbosityLevel
G4Cache< thread_data_t > ThreadData
G4Mutex a_mutex
G4SPSRandomGenerator * PosRndm
Detailed Description
Andrea Dotti Feb 2015 Important: This is a shared class between threads. Only one thread should use the set-methods here. Note that this is exactly what is achieved using UI commands. If you use the set methods to set defaults in your application take care that only one thread is executing them. In addition take care of calling these methods before the run is started Do not use these setters during the event loop
Definition at line 162 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 162 of file G4SPSPosDistribution.hh
Constructor & Destructor Documentation
G4SPSPosDistribution::G4SPSPosDistribution ()
Definition at line 69 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 69 of file G4SPSPosDistribution.cc
References a_mutex, CentreCoords, Confine, G4MUTEXINIT, halfx, halfy, halfz, CLHEP::HepXHat, CLHEP::HepYHat, CLHEP::HepZHat, ParAlpha, ParPhi, ParTheta, Radius, Radius0, Rotx, Roty, Rotz, Shape, SourcePosType, SR, SX, SY, verbosityLevel, and VolName.
G4SPSPosDistribution::~G4SPSPosDistribution ()
Definition at line 94 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 94 of file G4SPSPosDistribution.cc
References a_mutex, and G4MUTEXDESTROY.
Member Function Documentation
void G4SPSPosDistribution::ConfineSourceToVolume (G4String Vname)
Definition at line 277 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 277 of file G4SPSPosDistribution.cc
References Confine, G4cout, G4endl, G4PhysicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetName(), verbosityLevel, and VolName.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
G4ThreeVector G4SPSPosDistribution::GenerateOne ()
Definition at line 1174 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 1174 of file G4SPSPosDistribution.cc
References Confine, G4endl, G4Exception(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GeneratePointSource(), G4Cache< VALTYPE >::Get(), IsSourceConfined(), JustWarning, SourcePosType, and ThreadData.
Referenced by G4SingleParticleSource::GeneratePrimaryVertex().
void G4SPSPosDistribution::GeneratePointsInBeam (G4ThreeVector & outoutPos) private
Definition at line 334 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 334 of file G4SPSPosDistribution.cc
References CentreCoords, G4cout, G4endl, G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), halfx, halfy, PosRndm, Radius, Rotx, Roty, Rotz, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), Shape, G4INCL::DeJongSpin::shoot(), SX, SY, verbosityLevel, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by GenerateOne().
void G4SPSPosDistribution::GeneratePointsInPlane (G4ThreeVector & outoutPos) private
Definition at line 394 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 394 of file G4SPSPosDistribution.cc
References CentreCoords, G4SPSPosDistribution::thread_data_t::CSideRefVec1, G4SPSPosDistribution::thread_data_t::CSideRefVec2, G4SPSPosDistribution::thread_data_t::CSideRefVec3, G4cerr, G4cout, G4endl, G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), G4Cache< VALTYPE >::Get(), halfx, halfy, PosRndm, Radius, Radius0, Rotx, Roty, Rotz, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), Shape, SourcePosType, ThreadData, verbosityLevel, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by GenerateOne().
void G4SPSPosDistribution::GeneratePointsInVolume (G4ThreeVector & outputPos) private
Definition at line 1017 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 1017 of file G4SPSPosDistribution.cc
References CentreCoords, CLHEP::Hep3Vector::cross(), G4SPSPosDistribution::thread_data_t::CSideRefVec1, G4SPSPosDistribution::thread_data_t::CSideRefVec2, G4SPSPosDistribution::thread_data_t::CSideRefVec3, G4cout, G4endl, G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), G4SPSRandomGenerator::GenRandZ(), G4Cache< VALTYPE >::Get(), halfx, halfy, halfz, ParAlpha, ParPhi, ParTheta, PosRndm, Radius, Rotx, Roty, Rotz, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), Shape, SourcePosType, ThreadData, CLHEP::Hep3Vector::unit(), verbosityLevel, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by GenerateOne().
void G4SPSPosDistribution::GeneratePointsOnSurface (G4ThreeVector & outputPos) private
Definition at line 514 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 514 of file G4SPSPosDistribution.cc
References CentreCoords, CLHEP::Hep3Vector::cross(), G4SPSPosDistribution::thread_data_t::CSideRefVec1, G4SPSPosDistribution::thread_data_t::CSideRefVec2, G4SPSPosDistribution::thread_data_t::CSideRefVec3, G4cout, G4endl, G4UniformRand, G4SPSRandomGenerator::GenRandPosPhi(), G4SPSRandomGenerator::GenRandPosTheta(), G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), G4SPSRandomGenerator::GenRandZ(), G4Cache< VALTYPE >::Get(), Acts::UnitConstants::h, halfx, halfy, halfz, ParAlpha, ParPhi, ParTheta, phi, pi, PosRndm, Radius, Rotx, Roty, Rotz, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), Shape, SourcePosType, theta(), ThreadData, twopi, CLHEP::Hep3Vector::unit(), verbosityLevel, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by GenerateOne().
void G4SPSPosDistribution::GeneratePointSource (G4ThreeVector & outoutPos) private
Definition at line 324 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 324 of file G4SPSPosDistribution.cc
References CentreCoords, G4cerr, G4endl, SourcePosType, and verbosityLevel.
Referenced by GenerateOne().
void G4SPSPosDistribution::GenerateRotationMatrices () private
Definition at line 259 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 259 of file G4SPSPosDistribution.cc
References CLHEP::Hep3Vector::cross(), G4cout, G4endl, Rotx, Roty, Rotz, CLHEP::Hep3Vector::unit(), and verbosityLevel.
Referenced by SetPosRot1(), and SetPosRot2().
G4ThreeVector G4SPSPosDistribution::GetCentreCoords () const
Definition at line 203 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 203 of file G4SPSPosDistribution.cc
References CentreCoords.
Referenced by G4GPSModel::DescribeYourselfTo(), and G4GeneralParticleSource::ListSource().
G4bool G4SPSPosDistribution::GetConfined () const inline
Definition at line 218 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 218 of file G4SPSPosDistribution.hh
References Confine.
const G4String& G4SPSPosDistribution::GetConfineVolume () const inline
Definition at line 219 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 219 of file G4SPSPosDistribution.hh
References VolName.
G4double G4SPSPosDistribution::GetHalfX () const
Definition at line 208 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 208 of file G4SPSPosDistribution.cc
References halfx.
Referenced by G4GPSModel::DescribeYourselfTo().
G4double G4SPSPosDistribution::GetHalfY () const
Definition at line 213 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 213 of file G4SPSPosDistribution.cc
References halfy.
Referenced by G4GPSModel::DescribeYourselfTo().
G4double G4SPSPosDistribution::GetHalfZ () const
Definition at line 218 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 218 of file G4SPSPosDistribution.cc
References halfz.
Referenced by G4GPSModel::DescribeYourselfTo().
G4double G4SPSPosDistribution::GetParAlpha () const inline
Definition at line 212 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 212 of file G4SPSPosDistribution.hh
References ParAlpha.
Referenced by G4GPSModel::DescribeYourselfTo().
G4double G4SPSPosDistribution::GetParPhi () const inline
Definition at line 214 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 214 of file G4SPSPosDistribution.hh
References ParPhi.
Referenced by G4GPSModel::DescribeYourselfTo().
G4double G4SPSPosDistribution::GetParTheta () const inline
Definition at line 213 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 213 of file G4SPSPosDistribution.hh
References ParTheta.
Referenced by G4GPSModel::DescribeYourselfTo().
G4ThreeVector G4SPSPosDistribution::GetParticlePos () const
Definition at line 243 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 243 of file G4SPSPosDistribution.cc
References G4Cache< VALTYPE >::Get(), and ThreadData.
Referenced by G4SPSAngDistribution::GenerateFocusedFlux().
G4String G4SPSPosDistribution::GetPosDisShape () const
Definition at line 198 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 198 of file G4SPSPosDistribution.cc
References Shape.
Referenced by G4GPSModel::DescribeYourselfTo(), and G4GeneralParticleSource::ListSource().
G4String G4SPSPosDistribution::GetPosDisType () const
Definition at line 193 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 193 of file G4SPSPosDistribution.cc
References SourcePosType.
Referenced by G4GPSModel::DescribeYourselfTo(), UltraPrimaryGeneratorAction::GeneratePrimaries(), and G4GeneralParticleSource::ListSource().
G4double G4SPSPosDistribution::GetRadius () const
Definition at line 223 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 223 of file G4SPSPosDistribution.cc
References Radius.
Referenced by G4GPSModel::DescribeYourselfTo().
G4double G4SPSPosDistribution::GetRadius0 () const inline
Definition at line 211 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 211 of file G4SPSPosDistribution.hh
References Radius0.
Referenced by G4GPSModel::DescribeYourselfTo().
const G4ThreeVector& G4SPSPosDistribution::GetRotx () const inline
Definition at line 215 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 215 of file G4SPSPosDistribution.hh
References Rotx.
Referenced by G4GPSModel::DescribeYourselfTo().
const G4ThreeVector& G4SPSPosDistribution::GetRoty () const inline
Definition at line 216 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 216 of file G4SPSPosDistribution.hh
References Roty.
Referenced by G4GPSModel::DescribeYourselfTo().
const G4ThreeVector& G4SPSPosDistribution::GetRotz () const inline
Definition at line 217 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 217 of file G4SPSPosDistribution.hh
References Rotz.
Referenced by G4GPSModel::DescribeYourselfTo().
G4ThreeVector G4SPSPosDistribution::GetSideRefVec1 () const
Definition at line 247 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 247 of file G4SPSPosDistribution.cc
References G4Cache< VALTYPE >::Get(), and ThreadData.
Referenced by G4SPSAngDistribution::GenerateCosineLawFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), and G4SPSAngDistribution::GenerateUserDefFlux().
G4ThreeVector G4SPSPosDistribution::GetSideRefVec2 () const
Definition at line 251 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 251 of file G4SPSPosDistribution.cc
References G4Cache< VALTYPE >::Get(), and ThreadData.
Referenced by G4SPSAngDistribution::GenerateCosineLawFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), and G4SPSAngDistribution::GenerateUserDefFlux().
G4ThreeVector G4SPSPosDistribution::GetSideRefVec3 () const
Definition at line 255 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 255 of file G4SPSPosDistribution.cc
References G4Cache< VALTYPE >::Get(), and ThreadData.
Referenced by G4SPSAngDistribution::GenerateCosineLawFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), and G4SPSAngDistribution::GenerateUserDefFlux().
G4String G4SPSPosDistribution::GetSourcePosType () const
Definition at line 239 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 239 of file G4SPSPosDistribution.cc
References SourcePosType.
Referenced by G4SPSAngDistribution::GenerateCosineLawFlux(), and G4SPSAngDistribution::GenerateIsotropicFlux().
G4bool G4SPSPosDistribution::IsSourceConfined (G4ThreeVector & outputPos) private
Definition at line 1147 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 1147 of file G4SPSPosDistribution.cc
References Confine, G4cout, G4endl, G4VPhysicalVolume::GetName(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetTransportationManager(), G4Navigator::LocateGlobalPointAndSetup(), verbosityLevel, and VolName.
Referenced by GenerateOne().
void G4SPSPosDistribution::SetBeamSigmaInR (G4double r)
Definition at line 162 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 162 of file G4SPSPosDistribution.cc
References r, SR, SX, and SY.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetBeamSigmaInX (G4double r)
Definition at line 168 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 168 of file G4SPSPosDistribution.cc
References r, and SX.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetBeamSigmaInY (G4double r)
Definition at line 173 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 173 of file G4SPSPosDistribution.cc
References r, and SY.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetBiasRndm (G4SPSRandomGenerator * a)
Definition at line 228 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 228 of file G4SPSPosDistribution.cc
References a, a_mutex, and PosRndm.
Referenced by G4SingleParticleSource::G4SingleParticleSource().
void G4SPSPosDistribution::SetCentreCoords (G4ThreeVector coordsOfCentre)
Definition at line 109 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 109 of file G4SPSPosDistribution.cc
References CentreCoords.
Referenced by G4AdjointPrimaryGenerator::GenerateAdjointPrimaryVertex(), G4AdjointPrimaryGenerator::GenerateFwdPrimaryVertex(), G4GeneralParticleSourceMessenger::SetNewValue(), and G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource().
void G4SPSPosDistribution::SetHalfX (G4double xhalf)
Definition at line 137 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 137 of file G4SPSPosDistribution.cc
References halfx.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetHalfY (G4double yhalf)
Definition at line 142 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 142 of file G4SPSPosDistribution.cc
References halfy.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetHalfZ (G4double zhalf)
Definition at line 147 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 147 of file G4SPSPosDistribution.cc
References halfz.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetParAlpha (G4double paralp)
Definition at line 178 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 178 of file G4SPSPosDistribution.cc
References ParAlpha.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetParPhi (G4double parphi)
Definition at line 188 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 188 of file G4SPSPosDistribution.cc
References ParPhi.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetParTheta (G4double parthe)
Definition at line 183 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 183 of file G4SPSPosDistribution.cc
References ParTheta.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetPosDisShape (G4String shapeType)
Definition at line 104 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 104 of file G4SPSPosDistribution.cc
References Shape.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue(), and G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource().
void G4SPSPosDistribution::SetPosDisType (G4String PosType)
Important: This is a shared class between threads. Only one thread should use the set-methods here. Note that this is achieved by UI commands. If you use these methods to set defaults in your application take care that only one thread is executing them. In addition take care of calling these methods before the run is started Do not use these setters during the event loop
Definition at line 99 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 99 of file G4SPSPosDistribution.cc
References SourcePosType.
Referenced by G4AdjointPrimaryGenerator::G4AdjointPrimaryGenerator(), G4AdjointPrimaryGenerator::SetAdjointPrimarySourceOnAnExtSurfaceOfAVolume(), G4GeneralParticleSourceMessenger::SetNewValue(), and G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource().
void G4SPSPosDistribution::SetPosRot1 (G4ThreeVector posrot1)
Definition at line 114 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 114 of file G4SPSPosDistribution.cc
References G4cout, G4endl, GenerateRotationMatrices(), Rotx, and verbosityLevel.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetPosRot2 (G4ThreeVector posrot2)
Definition at line 125 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 125 of file G4SPSPosDistribution.cc
References G4cout, G4endl, GenerateRotationMatrices(), Roty, and verbosityLevel.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetRadius (G4double rds)
Definition at line 152 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 152 of file G4SPSPosDistribution.cc
References Radius.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue(), and G4AdjointPrimaryGenerator::SetSphericalAdjointPrimarySource().
void G4SPSPosDistribution::SetRadius0 (G4double rds)
Definition at line 157 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 157 of file G4SPSPosDistribution.cc
References Radius0.
Referenced by G4GeneralParticleSourceMessenger::SetNewValue().
void G4SPSPosDistribution::SetVerbosity (G4int a)
Definition at line 234 of file G4SPSPosDistribution.cc.
View newest version in sPHENIX GitHub at line 234 of file G4SPSPosDistribution.cc
References a, and verbosityLevel.
Referenced by G4SingleParticleSource::SetVerbosity().
Member Data Documentation
G4Mutex G4SPSPosDistribution::a_mutex private
Definition at line 286 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 286 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), SetBiasRndm(), and ~G4SPSPosDistribution().
G4ThreeVector G4SPSPosDistribution::CentreCoords private
Definition at line 258 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 258 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GeneratePointSource(), GetCentreCoords(), and SetCentreCoords().
G4bool G4SPSPosDistribution::Confine private
Definition at line 280 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 280 of file G4SPSPosDistribution.hh
Referenced by ConfineSourceToVolume(), G4SPSPosDistribution(), GenerateOne(), GetConfined(), and IsSourceConfined().
G4double G4SPSPosDistribution::halfx private
Definition at line 264 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 264 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetHalfX(), and SetHalfX().
G4double G4SPSPosDistribution::halfy private
Definition at line 265 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 265 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetHalfY(), and SetHalfY().
G4double G4SPSPosDistribution::halfz private
Definition at line 266 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 266 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetHalfZ(), and SetHalfZ().
G4double G4SPSPosDistribution::ParAlpha private
Definition at line 276 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 276 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetParAlpha(), and SetParAlpha().
G4double G4SPSPosDistribution::ParPhi private
Definition at line 278 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 278 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetParPhi(), and SetParPhi().
G4double G4SPSPosDistribution::ParTheta private
Definition at line 277 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 277 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetParTheta(), and SetParTheta().
G4SPSRandomGenerator* G4SPSPosDistribution::PosRndm private
Definition at line 287 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 287 of file G4SPSPosDistribution.hh
Referenced by GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), and SetBiasRndm().
G4double G4SPSPosDistribution::Radius private
Definition at line 268 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 268 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetRadius(), and SetRadius().
G4double G4SPSPosDistribution::Radius0 private
Definition at line 270 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 270 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInPlane(), GetRadius0(), and SetRadius0().
G4ThreeVector G4SPSPosDistribution::Rotx private
Definition at line 260 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 260 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GenerateRotationMatrices(), GetRotx(), and SetPosRot1().
G4ThreeVector G4SPSPosDistribution::Roty private
Definition at line 261 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 261 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GenerateRotationMatrices(), GetRoty(), and SetPosRot2().
G4ThreeVector G4SPSPosDistribution::Rotz private
Definition at line 262 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 262 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GenerateRotationMatrices(), and GetRotz().
G4String G4SPSPosDistribution::Shape private
Definition at line 256 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 256 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetPosDisShape(), and SetPosDisShape().
G4String G4SPSPosDistribution::SourcePosType private
Definition at line 254 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 254 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GenerateOne(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GeneratePointSource(), GetPosDisType(), GetSourcePosType(), and SetPosDisType().
G4double G4SPSPosDistribution::SR private
Definition at line 272 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 272 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), and SetBeamSigmaInR().
G4double G4SPSPosDistribution::SX private
Definition at line 273 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 273 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), SetBeamSigmaInR(), and SetBeamSigmaInX().
G4double G4SPSPosDistribution::SY private
Definition at line 274 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 274 of file G4SPSPosDistribution.hh
Referenced by G4SPSPosDistribution(), GeneratePointsInBeam(), SetBeamSigmaInR(), and SetBeamSigmaInY().
G4Cache<thread_data_t> G4SPSPosDistribution::ThreadData private
Definition at line 284 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 284 of file G4SPSPosDistribution.hh
Referenced by GenerateOne(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GetParticlePos(), GetSideRefVec1(), GetSideRefVec2(), and GetSideRefVec3().
G4int G4SPSPosDistribution::verbosityLevel private
Definition at line 283 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 283 of file G4SPSPosDistribution.hh
Referenced by ConfineSourceToVolume(), G4SPSPosDistribution(), GeneratePointsInBeam(), GeneratePointsInPlane(), GeneratePointsInVolume(), GeneratePointsOnSurface(), GeneratePointSource(), GenerateRotationMatrices(), IsSourceConfined(), SetPosRot1(), SetPosRot2(), and SetVerbosity().
G4String G4SPSPosDistribution::VolName private
Definition at line 281 of file G4SPSPosDistribution.hh.
View newest version in sPHENIX GitHub at line 281 of file G4SPSPosDistribution.hh
Referenced by ConfineSourceToVolume(), G4SPSPosDistribution(), GetConfineVolume(), and IsSourceConfined().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4SPSPosDistribution.hh
geant4/tree/geant4-10.6-release/source/event/src/G4SPSPosDistribution.cc