ECCE @ EIC Software: G4UserSteppingAction Class Reference
G4UserSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4UserSteppingAction.hh>
Inherited by B1SteppingAction, B1SteppingAction, B1SteppingAction, B4aSteppingAction, B4bSteppingAction, BrachySteppingAction, CB_G4UserSteppingAction, CCalSteppingAction, CexmcSteppingAction, CML2SteppingAction, demo.MySteppingAction, DMXSteppingAction, doiPETSteppingAction, eRositaSteppingAction, ExN02SteppingAction, ExN04SteppingAction, ExN04SteppingAction, ExP01SteppingAction, F04SteppingAction, F05SteppingAction, FCALSteppingAction, FW::Geant4::MMSteppingAction, G4AdjointSteppingAction, G4BlineSteppingAction, G4HumanPhantomSteppingAction, G4MSSteppingAction, G4MultiSteppingAction, G4RTSteppingAction, H02SteppingAction, HadrontherapySteppingAction, IORTSteppingAction, ITSteppingAction, ITSteppingAction, LXeSteppingAction, OpNoviceSteppingAction, PHG4FCalSteppingAction, PHG4FPbScRegionSteppingAction, PHG4PhenixSteppingAction, PHG4RICHSteppingAction, PurgMagSteppingAction, RE01SteppingAction, RE04SteppingAction, RE05SteppingAction, root_test.MySteppingAction, run.MySteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, test.MySteppingAction, test.MySteppingAction, WLSSteppingAction, XrayFluoSteppingAction, and XrayTelSteppingAction.
Public Member Functions
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
virtual void UserSteppingAction (const G4Step *)
Protected Attributes
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 50 of file G4UserSteppingAction.hh.
View newest version in sPHENIX GitHub at line 50 of file G4UserSteppingAction.hh
Constructor & Destructor Documentation
G4UserSteppingAction::G4UserSteppingAction ()
Definition at line 48 of file G4UserSteppingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file G4UserSteppingAction.cc
References FatalException, G4Exception(), and G4ParticleTable::GetParticleTable().
G4UserSteppingAction::~G4UserSteppingAction () virtual
Definition at line 67 of file G4UserSteppingAction.cc.
View newest version in sPHENIX GitHub at line 67 of file G4UserSteppingAction.cc
Member Function Documentation
void G4UserSteppingAction::SetSteppingManagerPointer (G4SteppingManager * pValue) virtual
Reimplemented in G4MultiSteppingAction.
Definition at line 73 of file G4UserSteppingAction.cc.
View newest version in sPHENIX GitHub at line 73 of file G4UserSteppingAction.cc
References fpSteppingManager.
Referenced by G4TrackingManager::SetUserAction().
virtual void G4UserSteppingAction::UserSteppingAction (const G4Step *) inline virtual
Reimplemented in G4AdjointSteppingAction, XrayTelSteppingAction, G4MultiSteppingAction, DMXSteppingAction, SteppingAction, CexmcSteppingAction, SteppingAction, IORTSteppingAction, G4BlineSteppingAction, CML2SteppingAction, PurgMagSteppingAction, SteppingAction, G4RTSteppingAction, SteppingAction, SteppingAction, WLSSteppingAction, doiPETSteppingAction, HadrontherapySteppingAction, SteppingAction, SteppingAction, ITSteppingAction, SteppingAction, G4MSSteppingAction, XrayFluoSteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, B4aSteppingAction, SteppingAction, SteppingAction, SteppingAction, B1SteppingAction, B1SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, B1SteppingAction, SteppingAction, SteppingAction, B4bSteppingAction, SteppingAction, SteppingAction, SteppingAction, F04SteppingAction, F05SteppingAction, SteppingAction, SteppingAction, SteppingAction, ExP01SteppingAction, PHG4RICHSteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, LXeSteppingAction, FCALSteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, ITSteppingAction, SteppingAction, ExN02SteppingAction, RE04SteppingAction, FW::Geant4::MMSteppingAction, OpNoviceSteppingAction, SteppingAction, CCalSteppingAction, SteppingAction, SteppingAction, SteppingAction, SteppingAction, CB_G4UserSteppingAction, BrachySteppingAction, ExN04SteppingAction, RE01SteppingAction, RE05SteppingAction, G4HumanPhantomSteppingAction, ExN04SteppingAction, SteppingAction, H02SteppingAction, PHG4PhenixSteppingAction, PHG4FPbScRegionSteppingAction, and PHG4FCalSteppingAction.
Definition at line 64 of file G4UserSteppingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file G4UserSteppingAction.hh
Referenced by ITTrackingInteractivity::AppendStep(), export_G4UserSteppingAction(), G4SteppingManager::Stepping(), CB_G4UserSteppingAction::UserSteppingAction(), and G4AdjointSteppingAction::UserSteppingAction().
Member Data Documentation
G4SteppingManager* G4UserSteppingAction::fpSteppingManager protected
Definition at line 71 of file G4UserSteppingAction.hh.
View newest version in sPHENIX GitHub at line 71 of file G4UserSteppingAction.hh
Referenced by SetSteppingManagerPointer(), BrachySteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), and LXeSteppingAction::UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4UserSteppingAction.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4UserSteppingAction.cc