ECCE @ EIC Software: G4TBFieldMessenger Class Reference
G4TBFieldMessenger Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/G4TBFieldMessenger.hh>
Public Member Functions
G4TBFieldMessenger (G4TBMagneticFieldSetup *)
virtual ~G4TBFieldMessenger ()
void SetNewValue (G4UIcommand *, G4String)
void SetNewValue (G4UIcommand *, G4int)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4TBMagneticFieldSetup * fEFieldSetup
G4UIdirectory * G4TBdetDir
G4UIcmdWithAnInteger * StepperCmd
G4UIcmdWithADoubleAndUnit * ElFieldCmd
G4UIcmdWithADoubleAndUnit * MinStepCmd
G4UIcmdWithoutParameter * UpdateCmd
G4UIcmdWithAString * AbsMaterCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 51 of file G4TBFieldMessenger.hh.
View newest version in sPHENIX GitHub at line 51 of file G4TBFieldMessenger.hh
Constructor & Destructor Documentation
G4TBFieldMessenger::G4TBFieldMessenger (G4TBMagneticFieldSetup * pEMfield)
Definition at line 48 of file G4TBFieldMessenger.cc.
View newest version in sPHENIX GitHub at line 48 of file G4TBFieldMessenger.cc
References AbsMaterCmd, G4UIcommand::AvailableForStates(), ElFieldCmd, G4State_Idle, G4State_PreInit, G4TBdetDir, MinStepCmd, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), StepperCmd, and UpdateCmd.
G4TBFieldMessenger::~G4TBFieldMessenger () virtual
Definition at line 92 of file G4TBFieldMessenger.cc.
View newest version in sPHENIX GitHub at line 92 of file G4TBFieldMessenger.cc
References AbsMaterCmd, ElFieldCmd, G4TBdetDir, MinStepCmd, StepperCmd, and UpdateCmd.
Member Function Documentation
void G4TBFieldMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 107 of file G4TBFieldMessenger.cc.
View newest version in sPHENIX GitHub at line 107 of file G4TBFieldMessenger.cc
References ElFieldCmd, fEFieldSetup, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), MinStepCmd, G4TBMagneticFieldSetup::SetFieldValue(), G4TBMagneticFieldSetup::SetMinStep(), G4TBMagneticFieldSetup::SetStepperType(), StepperCmd, UpdateCmd, and G4TBMagneticFieldSetup::UpdateField().
void G4TBFieldMessenger::SetNewValue (G4UIcommand * , G4int)
Member Data Documentation
G4UIcmdWithAString* G4TBFieldMessenger::AbsMaterCmd private
Definition at line 71 of file G4TBFieldMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4TBFieldMessenger.hh
Referenced by G4TBFieldMessenger(), and ~G4TBFieldMessenger().
G4UIcmdWithADoubleAndUnit* G4TBFieldMessenger::ElFieldCmd private
Definition at line 67 of file G4TBFieldMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4TBFieldMessenger.hh
Referenced by G4TBFieldMessenger(), SetNewValue(), and ~G4TBFieldMessenger().
G4TBMagneticFieldSetup* G4TBFieldMessenger::fEFieldSetup private
Definition at line 62 of file G4TBFieldMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4TBFieldMessenger.hh
Referenced by SetNewValue().
G4UIdirectory* G4TBFieldMessenger::G4TBdetDir private
Definition at line 64 of file G4TBFieldMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4TBFieldMessenger.hh
Referenced by G4TBFieldMessenger(), and ~G4TBFieldMessenger().
G4UIcmdWithADoubleAndUnit* G4TBFieldMessenger::MinStepCmd private
Definition at line 68 of file G4TBFieldMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4TBFieldMessenger.hh
Referenced by G4TBFieldMessenger(), SetNewValue(), and ~G4TBFieldMessenger().
G4UIcmdWithAnInteger* G4TBFieldMessenger::StepperCmd private
Definition at line 66 of file G4TBFieldMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4TBFieldMessenger.hh
Referenced by G4TBFieldMessenger(), SetNewValue(), and ~G4TBFieldMessenger().
G4UIcmdWithoutParameter* G4TBFieldMessenger::UpdateCmd private
Definition at line 69 of file G4TBFieldMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4TBFieldMessenger.hh
Referenced by G4TBFieldMessenger(), SetNewValue(), and ~G4TBFieldMessenger().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/G4TBFieldMessenger.hh
coresoftware/blob/master/simulation/g4simulation/g4main/G4TBFieldMessenger.cc