ECCE @ EIC Software: G4PAIPhotModel Class Reference
G4PAIPhotModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIPhotModel.hh>
Public Member Functions
G4PAIPhotModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="PAI")
~G4PAIPhotModel () final
void Initialise (const G4ParticleDefinition *, const G4DataVector &) final
void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) final
G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *couple) final
G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy) final
G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) final
void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) final
G4double SampleFluctuations (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double, G4double, G4double) final
G4double Dispersion (const G4Material *, const G4DynamicParticle *, G4double, G4double) final
void DefineForRegion (const G4Region *r) final
G4PAIPhotData * GetPAIPhotData ()
const std::vector< const
G4MaterialCutsCouple * > & GetVectorOfCouples ()
G4double ComputeMaxEnergy (G4double scaledEnergy)
void SetVerboseLevel (G4int verbose)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Public Member Functions inherited from G4VEmFluctuationModel
G4VEmFluctuationModel (const G4String &nam)
virtual ~G4VEmFluctuationModel ()
virtual void InitialiseMe (const G4ParticleDefinition *)
virtual void SetParticleAndCharge (const G4ParticleDefinition *, G4double q2)
const G4String & GetName () const
Protected Member Functions
G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kinEnergy) final
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
G4int FindCoupleIndex (const G4MaterialCutsCouple *)
void SetParticle (const G4ParticleDefinition *p)
G4PAIPhotModel & operator= (const G4PAIPhotModel &right)=delete
G4PAIPhotModel (const G4PAIPhotModel &)=delete
Private Attributes
G4int fVerbose
G4PAIPhotData * fModelData
std::vector< const
G4MaterialCutsCouple * > fMaterialCutsCoupleVector
std::vector< const G4Region * > fPAIRegionVector
const G4ParticleDefinition * fParticle
const G4ParticleDefinition * fElectron
const G4ParticleDefinition * fPositron
G4ParticleChangeForLoss * fParticleChange
G4double fMass
G4double fRatio
G4double fChargeSquare
G4double fLowestTcut
Additional Inherited Members
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 63 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 63 of file G4PAIPhotModel.hh
Constructor & Destructor Documentation
G4PAIPhotModel::G4PAIPhotModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "PAI") explicit
Definition at line 72 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 72 of file G4PAIPhotModel.cc
References G4Electron::Electron(), CLHEP::eV, fElectron, fLowestTcut, fParticleChange, fPositron, G4Positron::Positron(), G4VEmModel::SetAngularDistribution(), and SetParticle().
G4PAIPhotModel::~G4PAIPhotModel () final
Definition at line 93 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 93 of file G4PAIPhotModel.cc
References fModelData, and G4VEmModel::IsMaster().
G4PAIPhotModel::G4PAIPhotModel (const G4PAIPhotModel &) private delete
Member Function Documentation
G4double G4PAIPhotModel::ComputeDEDXPerVolume (const G4Material * , const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy) final virtual
Reimplemented from G4VEmModel.
Definition at line 204 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 204 of file G4PAIPhotModel.cc
References G4VEmModel::CurrentCouple(), G4PAIPhotData::DEDXPerVolume(), fChargeSquare, FindCoupleIndex(), fModelData, fRatio, MaxSecondaryEnergy(), and min.
G4double G4PAIPhotModel::ComputeMaxEnergy (G4double scaledEnergy) inline
Definition at line 159 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4PAIPhotModel.hh
References fParticle, fRatio, and MaxSecondaryEnergy().
Referenced by G4PAIPhotData::Initialise().
G4double G4PAIPhotModel::CrossSectionPerVolume (const G4Material * , const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) final virtual
Reimplemented from G4VEmModel.
Definition at line 221 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 221 of file G4PAIPhotModel.cc
References G4PAIPhotData::CrossSectionPerVolume(), G4VEmModel::CurrentCouple(), fChargeSquare, FindCoupleIndex(), fModelData, fRatio, MaxSecondaryEnergy(), and min.
void G4PAIPhotModel::DefineForRegion (const G4Region * r) final virtual
Reimplemented from G4VEmModel.
Definition at line 454 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 454 of file G4PAIPhotModel.cc
References fPAIRegionVector.
G4double G4PAIPhotModel::Dispersion (const G4Material * material, const G4DynamicParticle * aParticle, G4double tmax, G4double step) final virtual
Implements G4VEmFluctuationModel.
Definition at line 406 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 406 of file G4PAIPhotModel.cc
References eplus, G4DynamicParticle::GetCharge(), G4Material::GetElectronDensity(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), and source.hepunit::twopi_mc2_rcl2.
G4int G4PAIPhotModel::FindCoupleIndex (const G4MaterialCutsCouple * couple) inline private
Definition at line 169 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4PAIPhotModel.hh
References fMaterialCutsCoupleVector, and incremental_prev_tag::idx.
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), SampleFluctuations(), and SampleSecondaries().
G4PAIPhotData * G4PAIPhotModel::GetPAIPhotData () inline
Definition at line 148 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4PAIPhotModel.hh
References fModelData.
Referenced by InitialiseLocal().
const std::vector< const G4MaterialCutsCouple * > & G4PAIPhotModel::GetVectorOfCouples () inline
Definition at line 154 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4PAIPhotModel.hh
References fMaterialCutsCoupleVector.
Referenced by InitialiseLocal().
void G4PAIPhotModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) final virtual
Implements G4VEmModel.
Definition at line 101 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 101 of file G4PAIPhotModel.cc
References G4Region::FindCouple(), fMaterialCutsCoupleVector, fModelData, fPAIRegionVector, fParticleChange, fRatio, fVerbose, G4cout, G4endl, G4Exception(), G4MaterialCutsCouple::GetIndex(), G4RegionStore::GetInstance(), G4Material::GetMaterialTable(), G4Region::GetName(), G4Material::GetName(), G4Material::GetNumberOfMaterials(), G4VEmModel::GetParticleChangeForLoss(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), G4PAIPhotData::Initialise(), G4VEmModel::InitialiseElementSelectors(), G4VEmModel::IsMaster(), JustWarning, G4VEmModel::LowEnergyLimit(), mat, n, reg, and SetParticle().
void G4PAIPhotModel::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) final virtual
Reimplemented from G4VEmModel.
Definition at line 186 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 186 of file G4PAIPhotModel.cc
References fMaterialCutsCoupleVector, fModelData, G4VEmModel::GetElementSelectors(), GetPAIPhotData(), GetVectorOfCouples(), and G4VEmModel::SetElementSelectors().
G4double G4PAIPhotModel::MaxSecondaryEnergy (const G4ParticleDefinition * p, G4double kinEnergy) final protected virtual
Reimplemented from G4VEmModel.
Definition at line 437 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 437 of file G4PAIPhotModel.cc
References source.hepunit::electron_mass_c2, fElectron, fMass, fPositron, ratio, and SetParticle().
Referenced by ComputeDEDXPerVolume(), ComputeMaxEnergy(), CrossSectionPerVolume(), and SampleSecondaries().
G4double G4PAIPhotModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple * couple) final virtual
Reimplemented from G4VEmModel.
Definition at line 196 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 196 of file G4PAIPhotModel.cc
References fLowestTcut.
G4PAIPhotModel& G4PAIPhotModel::operator= (const G4PAIPhotModel & right) private delete
G4double G4PAIPhotModel::SampleFluctuations (const G4MaterialCutsCouple * matCC, const G4DynamicParticle * aParticle, G4double , G4double step, G4double eloss) final virtual
Implements G4VEmFluctuationModel.
Definition at line 366 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 366 of file G4PAIPhotModel.cc
References fChargeSquare, FindCoupleIndex(), fModelData, fRatio, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4PAIPhotData::SampleAlongStepPhotonTransfer(), G4PAIPhotData::SampleAlongStepPlasmonTransfer(), and SetParticle().
void G4PAIPhotModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * matCC, const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) final virtual
Implements G4VEmModel.
Definition at line 247 of file G4PAIPhotModel.cc.
View newest version in sPHENIX GitHub at line 247 of file G4PAIPhotModel.cc
References dir, fElectron, FindCoupleIndex(), fMass, fModelData, fParticle, fParticleChange, fRatio, G4cout, G4endl, G4lrint(), G4UniformRand, G4Gamma::Gamma(), G4VEmModel::GetAngularDistribution(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4PAIPhotData::GetPlasmonRatio(), G4Element::GetZ(), MaxSecondaryEnergy(), phi, G4VParticleChange::ProposeLocalEnergyDeposit(), CLHEP::Hep3Vector::rotateUz(), G4PAIPhotData::SamplePostStepPhotonTransfer(), G4PAIPhotData::SamplePostStepPlasmonTransfer(), G4VEmModel::SelectTargetAtom(), G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetKineticEnergy(), G4DynamicParticle::SetMomentumDirection(), SetParticle(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), twopi, CLHEP::Hep3Vector::unit(), and Z.
void G4PAIPhotModel::SetParticle (const G4ParticleDefinition * p) inline private
Definition at line 182 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4PAIPhotModel.hh
References CLHEP::eplus, fChargeSquare, fMass, fParticle, fRatio, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), and CLHEP::proton_mass_c2.
Referenced by G4PAIPhotModel(), Initialise(), MaxSecondaryEnergy(), SampleFluctuations(), and SampleSecondaries().
void G4PAIPhotModel::SetVerboseLevel (G4int verbose) inline
Definition at line 164 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 164 of file G4PAIPhotModel.hh
References fVerbose.
Member Data Documentation
G4double G4PAIPhotModel::fChargeSquare private
Definition at line 144 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 144 of file G4PAIPhotModel.hh
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), SampleFluctuations(), and SetParticle().
const G4ParticleDefinition* G4PAIPhotModel::fElectron private
Definition at line 138 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 138 of file G4PAIPhotModel.hh
Referenced by G4PAIPhotModel(), MaxSecondaryEnergy(), and SampleSecondaries().
G4double G4PAIPhotModel::fLowestTcut private
Definition at line 145 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 145 of file G4PAIPhotModel.hh
Referenced by G4PAIPhotModel(), and MinEnergyCut().
G4double G4PAIPhotModel::fMass private
Definition at line 142 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 142 of file G4PAIPhotModel.hh
Referenced by MaxSecondaryEnergy(), SampleSecondaries(), and SetParticle().
std::vector<const G4MaterialCutsCouple*> G4PAIPhotModel::fMaterialCutsCoupleVector private
Definition at line 134 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 134 of file G4PAIPhotModel.hh
Referenced by FindCoupleIndex(), GetVectorOfCouples(), Initialise(), and InitialiseLocal().
G4PAIPhotData* G4PAIPhotModel::fModelData private
Definition at line 132 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 132 of file G4PAIPhotModel.hh
Referenced by ComputeDEDXPerVolume(), CrossSectionPerVolume(), GetPAIPhotData(), Initialise(), InitialiseLocal(), SampleFluctuations(), SampleSecondaries(), and ~G4PAIPhotModel().
std::vector<const G4Region*> G4PAIPhotModel::fPAIRegionVector private
Definition at line 135 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 135 of file G4PAIPhotModel.hh
Referenced by DefineForRegion(), and Initialise().
const G4ParticleDefinition* G4PAIPhotModel::fParticle private
Definition at line 137 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 137 of file G4PAIPhotModel.hh
Referenced by ComputeMaxEnergy(), SampleSecondaries(), and SetParticle().
G4ParticleChangeForLoss* G4PAIPhotModel::fParticleChange private
Definition at line 140 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 140 of file G4PAIPhotModel.hh
Referenced by G4PAIPhotModel(), Initialise(), and SampleSecondaries().
const G4ParticleDefinition* G4PAIPhotModel::fPositron private
Definition at line 139 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 139 of file G4PAIPhotModel.hh
Referenced by G4PAIPhotModel(), and MaxSecondaryEnergy().
G4double G4PAIPhotModel::fRatio private
Definition at line 143 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 143 of file G4PAIPhotModel.hh
Referenced by ComputeDEDXPerVolume(), ComputeMaxEnergy(), CrossSectionPerVolume(), Initialise(), SampleFluctuations(), SampleSecondaries(), and SetParticle().
G4int G4PAIPhotModel::fVerbose private
Definition at line 130 of file G4PAIPhotModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PAIPhotModel.hh
Referenced by Initialise(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIPhotModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4PAIPhotModel.cc