ECCE @ EIC Software: G4AugerTransition Class Reference
G4AugerTransition Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4AugerTransition.hh>
Public Member Functions
G4AugerTransition (G4int finalShell, std::vector< G4int > transIds, const std::map< G4int, std::vector< G4int >, std::less< G4int > > *idMap, const std::map< G4int, G4DataVector, std::less< G4int > > *energyMap, const std::map< G4int, G4DataVector, std::less< G4int > > *probabilityMap)
~G4AugerTransition ()
const std::vector< G4int > * AugerOriginatingShellIds (G4int startShellId) const
const std::vector< G4int > * TransitionOriginatingShellIds () const
const G4DataVector * AugerTransitionEnergies (G4int startShellId) const
const G4DataVector * AugerTransitionProbabilities (G4int startShellId) const
G4int FinalShellId () const
G4int AugerOriginatingShellId (G4int index, G4int startShellId) const
G4double AugerTransitionEnergy (G4int index, G4int startShellId) const
G4double AugerTransitionProbability (G4int index, G4int startShellId) const
G4int TransitionOriginatingShellId (G4int index) const
Private Attributes
G4int finalShellId
std::map< G4int, std::vector
< G4int >, std::less< G4int > > augerOriginatingShellIdsMap
std::map< G4int, G4DataVector,
std::less< G4int > > augerTransitionEnergiesMap
std::map< G4int, G4DataVector,
std::less< G4int > > augerTransitionProbabilitiesMap
std::vector< G4int > transitionOriginatingShellIds
Detailed Description
Definition at line 54 of file G4AugerTransition.hh.
View newest version in sPHENIX GitHub at line 54 of file G4AugerTransition.hh
Constructor & Destructor Documentation
G4AugerTransition::G4AugerTransition (G4int finalShell, std::vector< G4int > transIds, const std::map< G4int, std::vector< G4int >, std::less< G4int > > * idMap, const std::map< G4int, G4DataVector, std::less< G4int > > * energyMap, const std::map< G4int, G4DataVector, std::less< G4int > > * probabilityMap)
Definition at line 44 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 44 of file G4AugerTransition.cc
References augerOriginatingShellIdsMap, augerTransitionEnergiesMap, augerTransitionProbabilitiesMap, finalShellId, and transitionOriginatingShellIds.
G4AugerTransition::~G4AugerTransition ()
Definition at line 58 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 58 of file G4AugerTransition.cc
Member Function Documentation
G4int G4AugerTransition::AugerOriginatingShellId (G4int index, G4int startShellId) const
Definition at line 147 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 147 of file G4AugerTransition.cc
References AugerOriginatingShellIds(), n, and pos().
Referenced by G4UAtomicDeexcitation::GenerateAuger().
const std::vector< G4int > * G4AugerTransition::AugerOriginatingShellIds (G4int startShellId) const
Definition at line 66 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 66 of file G4AugerTransition.cc
References augerOriginatingShellIdsMap, G4cout, and G4endl.
Referenced by AugerOriginatingShellId().
const G4DataVector * G4AugerTransition::AugerTransitionEnergies (G4int startShellId) const
Definition at line 95 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 95 of file G4AugerTransition.cc
References augerTransitionEnergiesMap, G4Exception(), and JustWarning.
Referenced by AugerTransitionEnergy().
G4double G4AugerTransition::AugerTransitionEnergy (G4int index, G4int startShellId) const
Definition at line 160 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 160 of file G4AugerTransition.cc
References AugerTransitionEnergies(), energy, and pos().
Referenced by G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
const G4DataVector * G4AugerTransition::AugerTransitionProbabilities (G4int startShellId) const
Definition at line 114 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 114 of file G4AugerTransition.cc
References augerTransitionProbabilitiesMap, G4Exception(), and JustWarning.
Referenced by AugerTransitionProbability(), G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
G4double G4AugerTransition::AugerTransitionProbability (G4int index, G4int startShellId) const
Definition at line 174 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 174 of file G4AugerTransition.cc
References AugerTransitionProbabilities(), and pos().
Referenced by G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
G4int G4AugerTransition::FinalShellId () const
Definition at line 139 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 139 of file G4AugerTransition.cc
References finalShellId.
Referenced by G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
G4int G4AugerTransition::TransitionOriginatingShellId (G4int index) const
Definition at line 187 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 187 of file G4AugerTransition.cc
References transitionOriginatingShellIds.
const std::vector< G4int > * G4AugerTransition::TransitionOriginatingShellIds () const
Definition at line 85 of file G4AugerTransition.cc.
View newest version in sPHENIX GitHub at line 85 of file G4AugerTransition.cc
References transitionOriginatingShellIds.
Referenced by G4AtomicDeexcitation::GenerateAuger(), and G4UAtomicDeexcitation::GenerateAuger().
Member Data Documentation
std::map<G4int,std::vector<G4int>,std::less<G4int> > G4AugerTransition::augerOriginatingShellIdsMap private
Definition at line 115 of file G4AugerTransition.hh.
View newest version in sPHENIX GitHub at line 115 of file G4AugerTransition.hh
Referenced by AugerOriginatingShellIds(), and G4AugerTransition().
std::map<G4int,G4DataVector,std::less<G4int> > G4AugerTransition::augerTransitionEnergiesMap private
Definition at line 116 of file G4AugerTransition.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AugerTransition.hh
Referenced by AugerTransitionEnergies(), and G4AugerTransition().
std::map<G4int,G4DataVector,std::less<G4int> > G4AugerTransition::augerTransitionProbabilitiesMap private
Definition at line 117 of file G4AugerTransition.hh.
View newest version in sPHENIX GitHub at line 117 of file G4AugerTransition.hh
Referenced by AugerTransitionProbabilities(), and G4AugerTransition().
G4int G4AugerTransition::finalShellId private
Definition at line 114 of file G4AugerTransition.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AugerTransition.hh
Referenced by FinalShellId(), and G4AugerTransition().
std::vector<G4int> G4AugerTransition::transitionOriginatingShellIds private
Definition at line 118 of file G4AugerTransition.hh.
View newest version in sPHENIX GitHub at line 118 of file G4AugerTransition.hh
Referenced by G4AugerTransition(), TransitionOriginatingShellId(), and TransitionOriginatingShellIds().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4AugerTransition.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4AugerTransition.cc