ECCE @ EIC Software: G4LorentzConvertor Class Reference
G4LorentzConvertor Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4LorentzConvertor.hh>
Public Member Functions
G4LorentzConvertor ()
G4LorentzConvertor (const G4LorentzVector &bmom, G4double bmass, const G4LorentzVector &tmom, G4double tmass)
G4LorentzConvertor (const G4InuclParticle *bullet, const G4InuclParticle *target)
void setVerbose (G4int vb=0)
void setBullet (const G4InuclParticle *bullet)
void setTarget (const G4InuclParticle *target)
void setBullet (const G4InuclParticle &bullet)
void setTarget (const G4InuclParticle &target)
void setBullet (const G4LorentzVector &bmom)
void setTarget (const G4LorentzVector &bmom)
void setBullet (const G4LorentzVector &bmom, G4double bmass)
void setTarget (const G4LorentzVector &tmom, G4double tmass)
void toTheCenterOfMass ()
void toTheTargetRestFrame ()
void fillKinematics ()
G4LorentzVector backToTheLab (const G4LorentzVector &mom) const
const G4LorentzVector & getBullet () const
const G4LorentzVector & getTarget () const
G4double getKinEnergyInTheTRS () const
G4double getTotalSCMEnergy () const
G4double getSCMMomentum () const
G4double getTRSMomentum () const
G4LorentzVector rotate (const G4LorentzVector &mom) const
G4LorentzVector rotate (const G4LorentzVector &mom1, const G4LorentzVector &mom) const
G4bool reflectionNeeded () const
G4bool trivial () const
void printBullet () const
void printTarget () const
Private Attributes
G4int verboseLevel
G4LorentzVector bullet_mom
G4LorentzVector target_mom
G4LorentzVector scm_momentum
G4ThreeVector scm_direction
G4ThreeVector velocity
G4double v2
G4double ecm_tot
G4double valong
G4bool degenerated
Static Private Attributes
static const G4double small = 1.0e-10
Detailed Description
Definition at line 44 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 44 of file G4LorentzConvertor.hh
Constructor & Destructor Documentation
G4LorentzConvertor::G4LorentzConvertor ()
Definition at line 46 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 46 of file G4LorentzConvertor.cc
G4LorentzConvertor::G4LorentzConvertor (const G4LorentzVector & bmom, G4double bmass, const G4LorentzVector & tmom, G4double tmass)
Definition at line 50 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 50 of file G4LorentzConvertor.cc
References setBullet(), and setTarget().
G4LorentzConvertor::G4LorentzConvertor (const G4InuclParticle * bullet, const G4InuclParticle * target)
Definition at line 58 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 58 of file G4LorentzConvertor.cc
References setBullet(), and setTarget().
Member Function Documentation
G4LorentzVector G4LorentzConvertor::backToTheLab (const G4LorentzVector & mom) const
Definition at line 134 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 134 of file G4LorentzConvertor.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::e(), G4cout, G4endl, mom, small, v2, velocity, verboseLevel, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by G4CollisionOutput::boostToLabFrame(), G4ElementaryParticleCollider::collide(), G4NonEquilibriumEvaporator::deExcite(), G4EquilibriumEvaporator::deExcite(), and G4NucleiModel::initializeCascad().
void G4LorentzConvertor::fillKinematics ()
Definition at line 112 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 112 of file G4LorentzConvertor.cc
References bullet_mom, degenerated, CLHEP::Hep3Vector::dot(), ecm_tot, G4cout, G4endl, m, CLHEP::Hep3Vector::mag2(), scm_direction, scm_momentum, small, target_mom, CLHEP::Hep3Vector::unit(), v2, valong, CLHEP::HepLorentzVector::vect(), velocity, and verboseLevel.
Referenced by toTheCenterOfMass(), and toTheTargetRestFrame().
const G4LorentzVector& G4LorentzConvertor::getBullet () const inline
Definition at line 92 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 92 of file G4LorentzConvertor.hh
References bullet_mom.
G4double G4LorentzConvertor::getKinEnergyInTheTRS () const
Definition at line 156 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 156 of file G4LorentzConvertor.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), bullet_mom, CLHEP::HepLorentzVector::e(), G4cout, G4endl, CLHEP::HepLorentzVector::m(), target_mom, and verboseLevel.
Referenced by G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), G4NucleiModel::inverseMeanFreePath(), and G4CascadeFinalStateAlgorithm::SaveKinematics().
G4double G4LorentzConvertor::getSCMMomentum () const inline
Definition at line 97 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 97 of file G4LorentzConvertor.hh
References CLHEP::HepLorentzVector::rho(), and scm_momentum.
const G4LorentzVector& G4LorentzConvertor::getTarget () const inline
Definition at line 93 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 93 of file G4LorentzConvertor.hh
References target_mom.
G4double G4LorentzConvertor::getTotalSCMEnergy () const inline
Definition at line 96 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 96 of file G4LorentzConvertor.hh
References ecm_tot.
Referenced by G4ElementaryParticleCollider::collide().
G4double G4LorentzConvertor::getTRSMomentum () const
Definition at line 165 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 165 of file G4LorentzConvertor.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), bullet_mom, G4cout, G4endl, CLHEP::HepLorentzVector::rho(), target_mom, and verboseLevel.
Referenced by G4InuclCollider::collide().
void G4LorentzConvertor::printBullet () const
Definition at line 288 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 288 of file G4LorentzConvertor.cc
References bullet_mom, CLHEP::HepLorentzVector::e(), G4cout, G4endl, CLHEP::HepLorentzVector::m(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), and CLHEP::HepLorentzVector::pz().
Referenced by setBullet().
void G4LorentzConvertor::printTarget () const
Definition at line 294 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 294 of file G4LorentzConvertor.cc
References CLHEP::HepLorentzVector::e(), G4cout, G4endl, CLHEP::HepLorentzVector::m(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), and target_mom.
Referenced by setTarget().
G4bool G4LorentzConvertor::reflectionNeeded () const
Definition at line 264 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 264 of file G4LorentzConvertor.cc
References degenerated, G4cout, G4endl, scm_momentum, small, v2, verboseLevel, and CLHEP::HepLorentzVector::z().
Referenced by G4CollisionOutput::boostToLabFrame().
G4LorentzVector G4LorentzConvertor::rotate (const G4LorentzVector & mom) const
Definition at line 174 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 174 of file G4LorentzConvertor.cc
References CLHEP::Hep3Vector::cross(), degenerated, G4cerr, G4cout, G4endl, CLHEP::Hep3Vector::mag(), mom, scm_direction, CLHEP::HepLorentzVector::setVect(), small, CLHEP::Hep3Vector::unit(), valong, velocity, verboseLevel, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
Referenced by G4CollisionOutput::boostToLabFrame(), G4CascadeFinalStateAlgorithm::FillDirManyBody(), G4CascadeFinalStateAlgorithm::FillDirThreeBody(), and G4CascadeFinalStateAlgorithm::GenerateTwoBody().
G4LorentzVector G4LorentzConvertor::rotate (const G4LorentzVector & mom1, const G4LorentzVector & mom) const
Definition at line 214 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 214 of file G4LorentzConvertor.cc
References CLHEP::Hep3Vector::cross(), CLHEP::Hep3Vector::dot(), G4cerr, G4cout, G4endl, CLHEP::Hep3Vector::mag(), mom, CLHEP::HepLorentzVector::setVect(), small, CLHEP::Hep3Vector::unit(), v2, CLHEP::HepLorentzVector::vect(), velocity, verboseLevel, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), and CLHEP::HepLorentzVector::z().
void G4LorentzConvertor::setBullet (const G4InuclParticle * bullet)
Definition at line 66 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 66 of file G4LorentzConvertor.cc
References G4InuclParticle::getMomentum().
Referenced by G4ElementaryParticleCollider::collide(), G4NonEquilibriumEvaporator::deExcite(), G4EquilibriumEvaporator::deExcite(), G4LorentzConvertor(), G4NucleiModel::inverseMeanFreePath(), and G4CascadeFinalStateAlgorithm::SaveKinematics().
void G4LorentzConvertor::setBullet (const G4InuclParticle & bullet) inline
Definition at line 59 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 59 of file G4LorentzConvertor.hh
References setBullet().
Referenced by setBullet().
void G4LorentzConvertor::setBullet (const G4LorentzVector & bmom) inline
Definition at line 63 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LorentzConvertor.hh
References bullet_mom, printBullet(), and verboseLevel.
void G4LorentzConvertor::setBullet (const G4LorentzVector & bmom, G4double bmass) inline
Definition at line 74 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 74 of file G4LorentzConvertor.hh
References bullet_mom, printBullet(), CLHEP::HepLorentzVector::setVectM(), CLHEP::HepLorentzVector::vect(), and verboseLevel.
void G4LorentzConvertor::setTarget (const G4InuclParticle * target)
Definition at line 70 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 70 of file G4LorentzConvertor.cc
References G4InuclParticle::getMomentum().
Referenced by G4ElementaryParticleCollider::collide(), G4NonEquilibriumEvaporator::deExcite(), G4EquilibriumEvaporator::deExcite(), G4LorentzConvertor(), G4NucleiModel::inverseMeanFreePath(), and G4CascadeFinalStateAlgorithm::SaveKinematics().
void G4LorentzConvertor::setTarget (const G4InuclParticle & target) inline
Definition at line 60 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 60 of file G4LorentzConvertor.hh
References setTarget().
Referenced by setTarget().
void G4LorentzConvertor::setTarget (const G4LorentzVector & bmom) inline
Definition at line 68 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 68 of file G4LorentzConvertor.hh
References printTarget(), target_mom, and verboseLevel.
void G4LorentzConvertor::setTarget (const G4LorentzVector & tmom, G4double tmass) inline
Definition at line 79 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 79 of file G4LorentzConvertor.hh
References printTarget(), CLHEP::HepLorentzVector::setVectM(), target_mom, CLHEP::HepLorentzVector::vect(), and verboseLevel.
void G4LorentzConvertor::setVerbose (G4int vb = 0) inline
Definition at line 54 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 54 of file G4LorentzConvertor.hh
References verboseLevel.
Referenced by G4ElementaryParticleCollider::collide(), and G4CascadeFinalStateAlgorithm::SetVerboseLevel().
void G4LorentzConvertor::toTheCenterOfMass ()
Definition at line 77 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 77 of file G4LorentzConvertor.cc
References CLHEP::HepLorentzVector::boost(), bullet_mom, fillKinematics(), G4cout, G4endl, scm_momentum, CLHEP::HepLorentzVector::setVect(), target_mom, CLHEP::HepLorentzVector::vect(), velocity, and verboseLevel.
Referenced by G4ElementaryParticleCollider::collide(), G4NucleiModel::inverseMeanFreePath(), and G4CascadeFinalStateAlgorithm::SaveKinematics().
void G4LorentzConvertor::toTheTargetRestFrame ()
Definition at line 94 of file G4LorentzConvertor.cc.
View newest version in sPHENIX GitHub at line 94 of file G4LorentzConvertor.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), bullet_mom, fillKinematics(), G4cout, G4endl, scm_momentum, target_mom, CLHEP::HepLorentzVector::vect(), velocity, and verboseLevel.
Referenced by G4InuclCollider::collide(), G4NonEquilibriumEvaporator::deExcite(), G4EquilibriumEvaporator::deExcite(), and G4NucleiModel::initializeCascad().
G4bool G4LorentzConvertor::trivial () const inline
Definition at line 107 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 107 of file G4LorentzConvertor.hh
References degenerated.
Referenced by G4InuclCollider::collide().
Member Data Documentation
G4LorentzVector G4LorentzConvertor::bullet_mom private
Definition at line 117 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 117 of file G4LorentzConvertor.hh
Referenced by fillKinematics(), getBullet(), getKinEnergyInTheTRS(), getTRSMomentum(), printBullet(), setBullet(), toTheCenterOfMass(), and toTheTargetRestFrame().
G4bool G4LorentzConvertor::degenerated private
Definition at line 128 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 128 of file G4LorentzConvertor.hh
Referenced by fillKinematics(), reflectionNeeded(), rotate(), and trivial().
G4double G4LorentzConvertor::ecm_tot private
Definition at line 126 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 126 of file G4LorentzConvertor.hh
Referenced by fillKinematics(), and getTotalSCMEnergy().
G4ThreeVector G4LorentzConvertor::scm_direction private
Definition at line 121 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 121 of file G4LorentzConvertor.hh
Referenced by fillKinematics(), and rotate().
G4LorentzVector G4LorentzConvertor::scm_momentum private
Definition at line 120 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 120 of file G4LorentzConvertor.hh
Referenced by fillKinematics(), getSCMMomentum(), reflectionNeeded(), toTheCenterOfMass(), and toTheTargetRestFrame().
const G4double G4LorentzConvertor::small = 1.0e-10 static private
Definition at line 114 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 114 of file G4LorentzConvertor.hh
Referenced by backToTheLab(), fillKinematics(), reflectionNeeded(), and rotate().
G4LorentzVector G4LorentzConvertor::target_mom private
Definition at line 118 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 118 of file G4LorentzConvertor.hh
Referenced by fillKinematics(), getKinEnergyInTheTRS(), getTarget(), getTRSMomentum(), printTarget(), setTarget(), toTheCenterOfMass(), and toTheTargetRestFrame().
G4double G4LorentzConvertor::v2 private
Definition at line 125 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 125 of file G4LorentzConvertor.hh
Referenced by backToTheLab(), fillKinematics(), reflectionNeeded(), and rotate().
G4double G4LorentzConvertor::valong private
Definition at line 127 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 127 of file G4LorentzConvertor.hh
Referenced by fillKinematics(), and rotate().
G4ThreeVector G4LorentzConvertor::velocity private
Definition at line 124 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 124 of file G4LorentzConvertor.hh
Referenced by backToTheLab(), fillKinematics(), rotate(), toTheCenterOfMass(), and toTheTargetRestFrame().
G4int G4LorentzConvertor::verboseLevel private
Definition at line 116 of file G4LorentzConvertor.hh.
View newest version in sPHENIX GitHub at line 116 of file G4LorentzConvertor.hh
Referenced by backToTheLab(), fillKinematics(), getKinEnergyInTheTRS(), getTRSMomentum(), reflectionNeeded(), rotate(), setBullet(), setTarget(), setVerbose(), toTheCenterOfMass(), and toTheTargetRestFrame().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4LorentzConvertor.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4LorentzConvertor.cc