ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/MCGIDI.h File Reference
MCGIDI.h File Reference
#include <GIDI_settings.hh>
#include <map>
#include <vector>
#include <statusMessageReporting.h>
#include <ptwXY.h>
#include <xDataTOM.h>
#include "MCGIDI_mass.h"
#include "MCGIDI_map.h"
Classes
class MCGIDI_quantitiesLookupModes
struct MCGIDI_samplingMultiplicityBias_s
class MCGIDI_samplingMethods
class MCGIDI_samplingSettings
struct MCGIDI_GammaBranching_s
struct MCGIDI_POP_s
struct MCGIDI_POPs_s
struct MCGIDI_particle_s
struct MCGIDI_decaySamplingInfo_s
struct MCGIDI_productInfo_s
struct MCGIDI_productsInfo_s
struct MCGIDI_sampledProductsData_s
struct MCGIDI_sampledProductsDatas_s
struct MCGIDI_pdfOfX_s
struct MCGIDI_pdfsOfXGivenW_s
struct MCGIDI_pdfsOfXGivenW_sampled_s
struct MCGIDI_angular_s
struct MCGIDI_energyWeightedFunctional_s
struct MCGIDI_energyWeightedFunctionals_s
struct MCGIDI_energyNBodyPhaseSpace_s
struct MCGIDI_energy_s
struct MCGIDI_energyAngular_s
struct MCGIDI_angularEnergy_s
struct MCGIDI_KalbachMann_ras_s
struct MCGIDI_KalbachMann_s
struct MCGIDI_distribution_s
struct MCGIDI_outputChannel_s
struct MCGIDI_product_s
struct MCGIDI_reaction_s
struct MCGIDI_target_heated_s
struct MCGIDI_target_heated_info_s
struct MCGIDI_target_s
Macros
#define MCGIDI_VERSION_MAJOR 1
#define MCGIDI_VERSION_MINOR 0
#define MCGIDI_VERSION_PATCHLEVEL 0
#define MCGIDI_crossSectionType_grouped 1
#define MCGIDI_crossSectionType_pointwise 2
#define MCGIDI_nullReaction -10001
#define MCGIDI_speedOfLight_cm_sec 2.99792458e10
#define MCGIDI_AMU2MeV 931.494028
#define MCGIDI_particleLevel_continuum -1
#define MCGIDI_particleLevel_sum -2
Typedefs
typedef struct
MCGIDI_GammaBranching_s MCGIDI_GammaBranching
typedef struct MCGIDI_POP_s MCGIDI_POP
typedef struct MCGIDI_POPs_s MCGIDI_POPs
typedef struct MCGIDI_particle_s MCGIDI_particle
typedef struct MCGIDI_target_s MCGIDI_target
typedef struct
MCGIDI_target_heated_info_s MCGIDI_target_heated_info
typedef struct
MCGIDI_target_heated_sorted_s MCGIDI_target_heated_sorted
typedef struct
MCGIDI_target_heated_s MCGIDI_target_heated
typedef struct MCGIDI_reaction_s MCGIDI_reaction
typedef struct
MCGIDI_outputChannel_s MCGIDI_outputChannel
typedef struct MCGIDI_product_s MCGIDI_product
typedef struct
MCGIDI_distribution_s MCGIDI_distribution
typedef struct MCGIDI_KalbachMann_s MCGIDI_KalbachMann
typedef struct
MCGIDI_KalbachMann_ras_s MCGIDI_KalbachMann_ras
typedef struct MCGIDI_pdfOfX_s MCGIDI_pdfOfX
typedef struct
MCGIDI_pdfsOfXGivenW_s MCGIDI_pdfsOfXGivenW
typedef struct
MCGIDI_pdfsOfXGivenW_sampled_s MCGIDI_pdfsOfXGivenW_sampled
typedef struct MCGIDI_angular_s MCGIDI_angular
typedef struct
MCGIDI_energyWeightedFunctional_s MCGIDI_energyWeightedFunctional
typedef struct
MCGIDI_energyWeightedFunctionals_s MCGIDI_energyWeightedFunctionals
typedef struct
MCGIDI_energyNBodyPhaseSpace_s MCGIDI_energyNBodyPhaseSpace
typedef struct MCGIDI_energy_s MCGIDI_energy
typedef struct
MCGIDI_energyAngular_s MCGIDI_energyAngular
typedef struct
MCGIDI_angularEnergy_s MCGIDI_angularEnergy
typedef struct
MCGIDI_decaySamplingInfo_s MCGIDI_decaySamplingInfo
typedef struct
MCGIDI_productsInfo_s MCGIDI_productsInfo
typedef struct MCGIDI_productInfo_s MCGIDI_productInfo
typedef struct
MCGIDI_sampledProductsData_s MCGIDI_sampledProductsData
typedef struct
MCGIDI_sampledProductsDatas_s MCGIDI_sampledProductsDatas
typedef struct
MCGIDI_samplingMultiplicityBias_s MCGIDI_samplingMultiplicityBias
typedef std::map< int, enum
GIDI::MCGIDI_transportability > transportabilitiesMap
Enumerations
enum MCGIDI_quantityLookupMode { MCGIDI_quantityLookupMode_pointwise, MCGIDI_quantityLookupMode_grouped }
enum MCGIDI_transportability { MCGIDI_transportability_unknown, MCGIDI_transportability_none, MCGIDI_transportability_partial, MCGIDI_transportability_full }
enum MCGIDI_reactionType {
MCGIDI_reactionType_unknown_e, MCGIDI_reactionType_null_e, MCGIDI_reactionType_elastic_e, MCGIDI_reactionType_scattering_e,
MCGIDI_reactionType_nuclearIsomerTransmutation_e, MCGIDI_reactionType_nuclearLevelTransition_e, MCGIDI_reactionType_capture_e, MCGIDI_reactionType_fission_e,
MCGIDI_reactionType_sumOfRemainingOutputChannels_e, MCGIDI_reactionType_atomic_e
}
enum MCGIDI_channelGenre {
MCGIDI_channelGenre_undefined_e, MCGIDI_channelGenre_twoBody_e, MCGIDI_channelGenre_uncorrelated_e, MCGIDI_channelGenre_sumOfRemaining_e,
MCGIDI_channelGenre_twoBodyDecay_e, MCGIDI_channelGenre_uncorrelatedDecay_e
}
enum MCGIDI_productMultiplicityType {
MCGIDI_productMultiplicityType_invalid_e, MCGIDI_productMultiplicityType_unknown_e, MCGIDI_productMultiplicityType_integer_e, MCGIDI_productMultiplicityType_energyDependent_e,
MCGIDI_productMultiplicityType_gammaBranching_e, MCGIDI_productMultiplicityType_mixed_e
}
enum MCGIDI_distributionType {
MCGIDI_distributionType_none_e, MCGIDI_distributionType_unknown_e, MCGIDI_distributionType_angular_e, MCGIDI_distributionType_KalbachMann_e,
MCGIDI_distributionType_uncorrelated_e, MCGIDI_distributionType_energyAngular_e, MCGIDI_distributionType_angularEnergy_e
}
enum MCGIDI_angularType { MCGIDI_angularType_isotropic, MCGIDI_angularType_recoil, MCGIDI_angularType_linear }
enum MCGIDI_energyType {
MCGIDI_energyType_unknown, MCGIDI_energyType_primaryGamma, MCGIDI_energyType_discreteGamma, MCGIDI_energyType_linear,
MCGIDI_energyType_generalEvaporation, MCGIDI_energyType_simpleMaxwellianFission, MCGIDI_energyType_evaporation, MCGIDI_energyType_Watt,
MCGIDI_energyType_MadlandNix, MCGIDI_energyType_NBodyPhaseSpace, MCGIDI_energyType_weightedFunctional
}
Functions
char const * MCGIDI_version (void)
int MCGIDI_versionMajor (void)
int MCGIDI_versionMinor (void)
int MCGIDI_versionPatchLevel (void)
MCGIDI_target * MCGIDI_target_new (statusMessageReporting *smr)
int MCGIDI_target_initialize (statusMessageReporting *smr, MCGIDI_target *target)
MCGIDI_target * MCGIDI_target_newRead (statusMessageReporting *smr, const char *fileName)
int MCGIDI_target_readFromMapViaPoPIDs (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_map *map, const char *evaluation, int projectile_PoPID, int target_PoPID)
int MCGIDI_target_readFromMap (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_map *map, const char *evaluation, const char *projectileName, const char *targetName)
MCGIDI_target * MCGIDI_target_newReadFromMapViaPoPIDs (statusMessageReporting *smr, MCGIDI_map *map, const char *evaluation, int projectile_PoPID, int target_PoPID)
MCGIDI_target * MCGIDI_target_newReadFromMap (statusMessageReporting *smr, MCGIDI_map *map, const char *evaluation, const char *projectileName, const char *targetName)
MCGIDI_target * MCGIDI_target_free (statusMessageReporting *smr, MCGIDI_target *target)
int MCGIDI_target_release (statusMessageReporting *smr, MCGIDI_target *target)
int MCGIDI_target_read (statusMessageReporting *smr, MCGIDI_target *target, const char *fileName)
char const * MCGIDI_target_getAttributesValue (statusMessageReporting *smr, MCGIDI_target *target, char const *name)
int MCGIDI_target_getTemperatures (statusMessageReporting *smr, MCGIDI_target *target, double *temperatures)
int MCGIDI_target_readHeatedTarget (statusMessageReporting *smr, MCGIDI_target *target, int index)
MCGIDI_target_heated * MCGIDI_target_getHeatedTargetAtIndex_ReadIfNeeded (statusMessageReporting *smr, MCGIDI_target *target, int index)
MCGIDI_target_heated * MCGIDI_target_getHeatedTargetAtTIndex (statusMessageReporting *smr, MCGIDI_target *target, int index)
int MCGIDI_target_numberOfReactions (statusMessageReporting *smr, MCGIDI_target *target)
enum MCGIDI_reactionType MCGIDI_target_getReactionTypeAtIndex (statusMessageReporting *smr, MCGIDI_target *target, int index)
MCGIDI_reaction * MCGIDI_target_getReactionAtIndex (MCGIDI_target *target, int index)
MCGIDI_reaction * MCGIDI_target_getReactionAtIndex_smr (statusMessageReporting *smr, MCGIDI_target *target, int index)
int MCGIDI_target_numberOfProductionReactions (statusMessageReporting *smr, MCGIDI_target *target)
transportabilitiesMap const * MCGIDI_target_getUniqueProducts (statusMessageReporting *smr, MCGIDI_target *target)
int MCGIDI_target_recast (statusMessageReporting *smr, MCGIDI_target *target, GIDI_settings &settings)
int MCGIDI_target_getDomain (statusMessageReporting *smr, MCGIDI_target *target, double *EMin, double *EMax)
double MCGIDI_target_getTotalCrossSectionAtTAndE (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_quantitiesLookupModes &modes, bool sampling)
double MCGIDI_target_getIndexReactionCrossSectionAtE (statusMessageReporting *smr, MCGIDI_target *target, int index, MCGIDI_quantitiesLookupModes &modes, bool sampling)
int MCGIDI_target_sampleReaction (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_quantitiesLookupModes &modes, double totalXSec, double(*userrng)(void *), void *rngState)
int MCGIDI_target_sampleNullReactionProductsAtE (statusMessageReporting *smr, MCGIDI_target *target, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, MCGIDI_sampledProductsDatas *productDatas)
int MCGIDI_target_sampleIndexReactionProductsAtE (statusMessageReporting *smr, MCGIDI_target *target, int index, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, MCGIDI_sampledProductsDatas *productData)
double MCGIDI_target_getIndexReactionFinalQ (statusMessageReporting *smr, MCGIDI_target *target, int index, MCGIDI_quantitiesLookupModes &modes)
MCGIDI_target_heated * MCGIDI_target_heated_new (statusMessageReporting *smr)
int MCGIDI_target_heated_initialize (statusMessageReporting *smr, MCGIDI_target_heated *target)
MCGIDI_target_heated * MCGIDI_target_heated_newRead (statusMessageReporting *smr, const char *fileName)
MCGIDI_target_heated * MCGIDI_target_heated_free (statusMessageReporting *smr, MCGIDI_target_heated *target)
int MCGIDI_target_heated_release (statusMessageReporting *smr, MCGIDI_target_heated *target)
int MCGIDI_target_heated_read (statusMessageReporting *smr, MCGIDI_target_heated *target, const char *fileName)
int MCGIDI_target_heated_numberOfReactions (statusMessageReporting *smr, MCGIDI_target_heated *target)
int MCGIDI_target_heated_numberOfProductionReactions (statusMessageReporting *smr, MCGIDI_target_heated *target)
MCGIDI_reaction * MCGIDI_target_heated_getReactionAtIndex (MCGIDI_target_heated *target, int index)
MCGIDI_reaction * MCGIDI_target_heated_getReactionAtIndex_smr (statusMessageReporting *smr, MCGIDI_target_heated *target, int index)
MCGIDI_POP * MCGIDI_target_heated_getPOPForProjectile (statusMessageReporting *smr, MCGIDI_target_heated *target)
MCGIDI_POP * MCGIDI_target_heated_getPOPForTarget (statusMessageReporting *smr, MCGIDI_target_heated *target)
double MCGIDI_target_heated_getProjectileMass_MeV (statusMessageReporting *smr, MCGIDI_target_heated *target)
double MCGIDI_target_heated_getTargetMass_MeV (statusMessageReporting *smr, MCGIDI_target_heated *target)
int MCGIDI_target_heated_getEnergyGrid (statusMessageReporting *smr, MCGIDI_target_heated *target, double **energyGrid)
double MCGIDI_target_heated_getTotalCrossSectionAtE (statusMessageReporting *smr, MCGIDI_target_heated *target, MCGIDI_quantitiesLookupModes &modes, bool sampling)
double MCGIDI_target_heated_getIndexReactionCrossSectionAtE (statusMessageReporting *smr, MCGIDI_target_heated *target, int index, MCGIDI_quantitiesLookupModes &modes, bool sampling)
int MCGIDI_target_heated_sampleIndexReactionProductsAtE (statusMessageReporting *smr, MCGIDI_target_heated *target, int index, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, MCGIDI_sampledProductsDatas *productData)
double MCGIDI_target_heated_getReactionsThreshold (statusMessageReporting *smr, MCGIDI_target_heated *target, int index)
int MCGIDI_target_heated_getReactionsDomain (statusMessageReporting *smr, MCGIDI_target_heated *target, int index, double *EMin, double *EMax)
double MCGIDI_target_heated_getIndexReactionFinalQ (statusMessageReporting *smr, MCGIDI_target_heated *target, int index, MCGIDI_quantitiesLookupModes &modes)
transportabilitiesMap const * MCGIDI_target_heated_getUniqueProducts (statusMessageReporting *smr, MCGIDI_target_heated *target)
int MCGIDI_target_heated_recast (statusMessageReporting *smr, MCGIDI_target_heated *target, GIDI_settings &settings)
MCGIDI_reaction * MCGIDI_reaction_new (statusMessageReporting *smr)
int MCGIDI_reaction_initialize (statusMessageReporting *smr, MCGIDI_reaction *reaction)
MCGIDI_reaction * MCGIDI_reaction_free (statusMessageReporting *smr, MCGIDI_reaction *reaction)
int MCGIDI_reaction_release (statusMessageReporting *smr, MCGIDI_reaction *reaction)
int MCGIDI_reaction_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_target_heated *target, MCGIDI_POPs *pops, MCGIDI_reaction *reaction)
enum MCGIDI_reactionType MCGIDI_reaction_getReactionType (statusMessageReporting *smr, MCGIDI_reaction *reaction)
MCGIDI_target_heated * MCGIDI_reaction_getTargetHeated (statusMessageReporting *smr, MCGIDI_reaction *reaction)
double MCGIDI_reaction_getProjectileMass_MeV (statusMessageReporting *smr, MCGIDI_reaction *reaction)
double MCGIDI_reaction_getTargetMass_MeV (statusMessageReporting *smr, MCGIDI_reaction *reaction)
int MCGIDI_reaction_getDomain (statusMessageReporting *smr, MCGIDI_reaction *reaction, double *EMin, double *EMax)
int MCGIDI_reaction_fixDomains (statusMessageReporting *smr, MCGIDI_reaction *reaction, double EMin, double EMax, nfu_status *status)
double MCGIDI_reaction_getCrossSectionAtE (statusMessageReporting *smr, MCGIDI_reaction *reaction, MCGIDI_quantitiesLookupModes &modes, bool sampling)
double MCGIDI_reaction_getFinalQ (statusMessageReporting *smr, MCGIDI_reaction *reaction, MCGIDI_quantitiesLookupModes &modes)
int MCGIDI_reaction_getENDF_MTNumber (MCGIDI_reaction *reaction)
int MCGIDI_reaction_getENDL_CSNumbers (MCGIDI_reaction *reaction, int *S)
int MCGIDI_reaction_recast (statusMessageReporting *smr, MCGIDI_reaction *reaction, GIDI_settings &settings, GIDI_settings_particle const *projectileSettings, double temperature_MeV, ptwXPoints *totalGroupedCrossSection)
MCGIDI_productsInfo * MCGIDI_reaction_getProductsInfo (MCGIDI_reaction *reaction)
int MCGIDI_productsInfo_getNumberOfUniqueProducts (MCGIDI_productsInfo *productsInfo)
int MCGIDI_productsInfo_getPoPsIndexAtIndex (MCGIDI_productsInfo *productsInfo, int index)
enum MCGIDI_productMultiplicityType MCGIDI_productsInfo_getMultiplicityTypeAtIndex (MCGIDI_productsInfo *productsInfo, int index)
int MCGIDI_productsInfo_getIntegerMultiplicityAtIndex (MCGIDI_productsInfo *productsInfo, int index)
int MCGIDI_productsInfo_getTransportableAtIndex (MCGIDI_productsInfo *productsInfo, int index)
MCGIDI_POPs * MCGIDI_POPs_new (statusMessageReporting *smr, int size)
int MCGIDI_POPs_initial (statusMessageReporting *smr, MCGIDI_POPs *pops, int size)
void * MCGIDI_POPs_free (MCGIDI_POPs *pops)
int MCGIDI_POPs_release (MCGIDI_POPs *pops)
MCGIDI_POP * MCGIDI_POPs_addParticleIfNeeded (statusMessageReporting *smr, MCGIDI_POPs *pops, char const *name, double mass_MeV, double level_MeV, MCGIDI_POP *parent, int globalParticle)
int MCGIDI_POPs_findParticleIndex (MCGIDI_POPs *pops, char const *name)
MCGIDI_POP * MCGIDI_POPs_findParticle (MCGIDI_POPs *pops, char const *name)
void MCGIDI_POPs_writeSortedList (MCGIDI_POPs *pops, FILE *f)
void MCGIDI_POPs_printSortedList (MCGIDI_POPs *pops)
MCGIDI_POP * MCGIDI_POP_new (statusMessageReporting *smr, char const *name, double mass_MeV, double level_MeV, MCGIDI_POP *parent)
MCGIDI_POP * MCGIDI_POP_free (MCGIDI_POP *pop)
MCGIDI_POP * MCGIDI_POP_release (MCGIDI_POP *pop)
double MCGIDI_POP_getMass_MeV (MCGIDI_POP *pop)
MCGIDI_particle * MCGIDI_particle_new (statusMessageReporting *smr)
int MCGIDI_particle_initialize (statusMessageReporting *smr, MCGIDI_particle *particle)
MCGIDI_particle * MCGIDI_particle_free (statusMessageReporting *smr, MCGIDI_particle *particle)
int MCGIDI_particle_release (statusMessageReporting *smr, MCGIDI_particle *particle)
int MCGIDI_particle_freeInternalList (statusMessageReporting *smr)
MCGIDI_particle * MCGIDI_particle_getInternalID (statusMessageReporting *smr, const char *const name, MCGIDI_POPs *pops)
int MCGIDI_particle_printInternalSortedList (statusMessageReporting *smr)
MCGIDI_outputChannel * MCGIDI_outputChannel_new (statusMessageReporting *smr)
int MCGIDI_outputChannel_initialize (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
MCGIDI_outputChannel * MCGIDI_outputChannel_free (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
int MCGIDI_outputChannel_release (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
int MCGIDI_outputChannel_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_POPs *pops, MCGIDI_outputChannel *outputChannel, MCGIDI_reaction *reaction, MCGIDI_product *parent)
int MCGIDI_outputChannel_numberOfProducts (MCGIDI_outputChannel *outputChannel)
MCGIDI_product * MCGIDI_outputChannel_getProductAtIndex (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, int i)
int MCGIDI_outputChannel_getDomain (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, double *EMin, double *EMax)
MCGIDI_target_heated * MCGIDI_outputChannel_getTargetHeated (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
double MCGIDI_outputChannel_getProjectileMass_MeV (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
double MCGIDI_outputChannel_getTargetMass_MeV (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
double MCGIDI_outputChannel_getQ_MeV (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, double e_in)
double MCGIDI_outputChannel_getFinalQ (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, double e_in)
int MCGIDI_outputChannel_sampleProductsAtE (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, MCGIDI_sampledProductsDatas *productDatas, double *masses)
MCGIDI_product * MCGIDI_product_new (statusMessageReporting *smr)
int MCGIDI_product_initialize (statusMessageReporting *smr, MCGIDI_product *product)
MCGIDI_product * MCGIDI_product_free (statusMessageReporting *smr, MCGIDI_product *product)
int MCGIDI_product_release (statusMessageReporting *smr, MCGIDI_product *product)
int MCGIDI_product_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_outputChannel *outputChannel, MCGIDI_POPs *pops, MCGIDI_product *product, int *delayedNeutronIndex)
int MCGIDI_product_getDomain (statusMessageReporting *smr, MCGIDI_product *product, double *EMin, double *EMax)
int MCGIDI_product_setTwoBodyMasses (statusMessageReporting *smr, MCGIDI_product *product, double projectileMass_MeV, double targetMass_MeV, double productMass_MeV, double residualMass_MeV)
double MCGIDI_product_getMass_MeV (statusMessageReporting *smr, MCGIDI_product *product)
MCGIDI_target_heated * MCGIDI_product_getTargetHeated (statusMessageReporting *smr, MCGIDI_product *product)
double MCGIDI_product_getProjectileMass_MeV (statusMessageReporting *smr, MCGIDI_product *product)
double MCGIDI_product_getTargetMass_MeV (statusMessageReporting *smr, MCGIDI_product *product)
int MCGIDI_product_sampleMultiplicity (statusMessageReporting *smr, MCGIDI_product *product, double e_in, double r)
int MCGIDI_product_sampleMu (statusMessageReporting *smr, MCGIDI_product *product, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
int MCGIDI_sampledProducts_initialize (statusMessageReporting *smr, MCGIDI_sampledProductsDatas *sampledProductsDatas, int incrementSize)
int MCGIDI_sampledProducts_release (statusMessageReporting *smr, MCGIDI_sampledProductsDatas *sampledProductsDatas)
int MCGIDI_sampledProducts_remalloc (statusMessageReporting *smr, MCGIDI_sampledProductsDatas *sampledProductsDatas)
int MCGIDI_sampledProducts_addProduct (statusMessageReporting *smr, MCGIDI_sampledProductsDatas *sampledProductsDatas, MCGIDI_sampledProductsData *sampledProductsData)
int MCGIDI_sampledProducts_number (MCGIDI_sampledProductsDatas *sampledProductsDatas)
MCGIDI_sampledProductsData * MCGIDI_sampledProducts_getProductAtIndex (MCGIDI_sampledProductsDatas *sampledProductsDatas, int index)
MCGIDI_distribution * MCGIDI_distribution_new (statusMessageReporting *smr)
int MCGIDI_distribution_initialize (statusMessageReporting *smr, MCGIDI_distribution *distribution)
MCGIDI_distribution * MCGIDI_distribution_free (statusMessageReporting *smr, MCGIDI_distribution *distribution)
int MCGIDI_distribution_release (statusMessageReporting *smr, MCGIDI_distribution *distribution)
int MCGIDI_distribution_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_product *product, MCGIDI_POPs *pops, ptwXYPoints *norms)
MCGIDI_angular * MCGIDI_angular_new (statusMessageReporting *smr)
int MCGIDI_angular_initialize (statusMessageReporting *smr, MCGIDI_angular *angular)
MCGIDI_angular * MCGIDI_angular_free (statusMessageReporting *smr, MCGIDI_angular *angular)
int MCGIDI_angular_release (statusMessageReporting *smr, MCGIDI_angular *angular)
int MCGIDI_angular_setTwoBodyMasses (statusMessageReporting *smr, MCGIDI_angular *angular, double projectileMass_MeV, double targetMass_MeV, double productMass_MeV, double residualMass_MeV)
int MCGIDI_angular_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution, ptwXYPoints *norms)
int MCGIDI_angular_sampleMu (statusMessageReporting *smr, MCGIDI_angular *angular, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
MCGIDI_energy * MCGIDI_energy_new (statusMessageReporting *smr)
int MCGIDI_energy_initialize (statusMessageReporting *smr, MCGIDI_energy *energy)
MCGIDI_energy * MCGIDI_energy_free (statusMessageReporting *smr, MCGIDI_energy *energy)
int MCGIDI_energy_release (statusMessageReporting *smr, MCGIDI_energy *energy)
int MCGIDI_energy_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution, ptwXYPoints *norms, enum MCGIDI_energyType energyType, double gammaEnergy_MeV)
int MCGIDI_energy_sampleEnergy (statusMessageReporting *smr, MCGIDI_energy *energy, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
int MCGIDI_energyAngular_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
MCGIDI_energyAngular * MCGIDI_energyAngular_new (statusMessageReporting *smr)
int MCGIDI_energyAngular_initialize (statusMessageReporting *smr, MCGIDI_energyAngular *energyAngular)
MCGIDI_energyAngular * MCGIDI_energyAngular_free (statusMessageReporting *smr, MCGIDI_energyAngular *energyAngular)
int MCGIDI_energyAngular_release (statusMessageReporting *smr, MCGIDI_energyAngular *energyAngular)
int MCGIDI_energyAngular_sampleDistribution (statusMessageReporting *smr, MCGIDI_distribution *distribution, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
MCGIDI_angularEnergy * MCGIDI_angularEnergy_new (statusMessageReporting *smr)
int MCGIDI_angularEnergy_initialize (statusMessageReporting *smr, MCGIDI_angularEnergy *energyAngular)
MCGIDI_angularEnergy * MCGIDI_angularEnergy_free (statusMessageReporting *smr, MCGIDI_angularEnergy *energyAngular)
int MCGIDI_angularEnergy_release (statusMessageReporting *smr, MCGIDI_angularEnergy *energyAngular)
int MCGIDI_angularEnergy_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
int MCGIDI_angularEnergy_sampleDistribution (statusMessageReporting *smr, MCGIDI_angularEnergy *angularEnergy, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
MCGIDI_KalbachMann * MCGIDI_KalbachMann_new (statusMessageReporting *smr, ptwXY_interpolation interpolationWY, ptwXY_interpolation interpolationXY)
int MCGIDI_KalbachMann_initialize (statusMessageReporting *smr, MCGIDI_KalbachMann *KalbachMann, ptwXY_interpolation interpolationWY, ptwXY_interpolation interpolationXY)
MCGIDI_KalbachMann * MCGIDI_KalbachMann_free (statusMessageReporting *smr, MCGIDI_KalbachMann *KalbachMann)
int MCGIDI_KalbachMann_release (statusMessageReporting *smr, MCGIDI_KalbachMann *KalbachMann)
int MCGIDI_KalbachMann_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
int MCGIDI_KalbachMann_sampleEp (statusMessageReporting *smr, MCGIDI_KalbachMann *KalbachMann, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
int MCGIDI_uncorrelated_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution, ptwXYPoints *norms, enum MCGIDI_energyType energyType, double gammaEnergy_MeV)
int MCGIDI_uncorrelated_sampleDistribution (statusMessageReporting *smr, MCGIDI_distribution *distribution, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
int MCGIDI_LLNLAngular_angularEnergy_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
int MCGIDI_kinetics_2BodyReaction (statusMessageReporting *smr, MCGIDI_angular *angular, double K, double mu, double phi, MCGIDI_sampledProductsData *outgoingData)
int MCGIDI_kinetics_COMKineticEnergy2LabEnergyAndMomentum (statusMessageReporting *smr, double beta, double e_kinetic_com, double mu, double phi, double m3cc, double m4cc, MCGIDI_sampledProductsData *outgoingData)
int MCGIDI_kinetics_COM2Lab (statusMessageReporting *smr, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, double masses[3])
int MCGIDI_sampling_pdfsOfXGivenW_initialize (statusMessageReporting *smr, MCGIDI_pdfsOfXGivenW *dists)
int MCGIDI_sampling_pdfsOfXGivenW_release (statusMessageReporting *smr, MCGIDI_pdfsOfXGivenW *dists)
int MCGIDI_sampling_pdfsOfX_release (statusMessageReporting *smr, MCGIDI_pdfOfX *dist)
int MCGIDI_sampling_sampleX_from_pdfsOfXGivenW (MCGIDI_pdfsOfXGivenW *dists, MCGIDI_pdfsOfXGivenW_sampled *sampled, double r)
int MCGIDI_sampling_sampleX_from_pdfOfX (MCGIDI_pdfOfX *dist, MCGIDI_pdfsOfXGivenW_sampled *sampled, double r)
int MCGIDI_sampling_doubleDistribution (statusMessageReporting *smr, MCGIDI_pdfsOfXGivenW *pdfOfWGivenV, MCGIDI_pdfsOfXGivenW *pdfOfXGivenVAndW, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
int MCGIDI_sampling_interpolationValues (statusMessageReporting *smr, ptwXY_interpolation interpolation, double *ws, double y1, double y2, double *y)
double MCGIDI_sampling_ptwXY_getValueAtX (ptwXYPoints *ptwXY, double x1)
int MCGIDI_misc_NumberOfZSymbols (void)
const char * MCGIDI_misc_ZToSymbol (int iZ)
int MCGIDI_misc_symbolToZ (const char *Z)
int MCGIDI_miscNameToZAm (statusMessageReporting *smr, const char *name, int *Z, int *A, int *m, int *level)
xDataTOM_Int MCGIDI_misc_binarySearch (xDataTOM_Int n, double *ds, double d)
int MCGIDI_misc_PQUStringToDouble (statusMessageReporting *smr, char const *str, char const *unit, double conversion, double *value)
int MCGIDI_misc_PQUStringToDoubleInUnitOf (statusMessageReporting *smr, char const *str, char const *toUnit, double *value)
void MCGIDI_misc_updateTransportabilitiesMap (transportabilitiesMap *transportabilities, int PoPID, enum MCGIDI_transportability transportability)
void MCGIDI_misc_updateTransportabilitiesMap2 (transportabilitiesMap *transportabilities, int PoPID, int transportable)
Variables
const char * MCGIDI_productGenre_unknown
const char * MCGIDI_productGenre_twoBody_angular
const char * MCGIDI_productGenre_twoBody_formFactor
const char * MCGIDI_productGenre_NBody_angular_energy
const char * MCGIDI_productGenre_NBody_pairProduction
Macro Definition Documentation
#define MCGIDI_AMU2MeV 931.494028
Definition at line 184 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 184 of file MCGIDI.h
Referenced by MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_particle_getInternalID(), and MCGIDI_target_heated_parseParticle().
#define MCGIDI_crossSectionType_grouped 1
Definition at line 178 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 178 of file MCGIDI.h
#define MCGIDI_crossSectionType_pointwise 2
Definition at line 179 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 179 of file MCGIDI.h
#define MCGIDI_nullReaction -10001
Definition at line 181 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 181 of file MCGIDI.h
Referenced by MCGIDI_target_sampleReaction().
#define MCGIDI_particleLevel_continuum -1
Definition at line 221 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 221 of file MCGIDI.h
Referenced by MCGIDI_miscNameToZAm_getLevel().
#define MCGIDI_particleLevel_sum -2
Definition at line 222 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 222 of file MCGIDI.h
Referenced by MCGIDI_miscNameToZAm_getLevel().
#define MCGIDI_speedOfLight_cm_sec 2.99792458e10
Definition at line 183 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 183 of file MCGIDI.h
Referenced by MCGIDI_kinetics_COMKineticEnergy2LabEnergyAndMomentum(), MCGIDI_outputChannel_sampleProductsAtE(), and MCGIDI_target_sampleNullReactionProductsAtE().
#define MCGIDI_VERSION_MAJOR 1
Definition at line 8 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 8 of file MCGIDI.h
Referenced by MCGIDI_version(), and MCGIDI_versionMajor().
#define MCGIDI_VERSION_MINOR 0
Definition at line 9 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 9 of file MCGIDI.h
Referenced by MCGIDI_version(), and MCGIDI_versionMinor().
#define MCGIDI_VERSION_PATCHLEVEL 0
Definition at line 10 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 10 of file MCGIDI.h
Referenced by MCGIDI_version(), and MCGIDI_versionPatchLevel().
Typedef Documentation
typedef struct MCGIDI_angular_s MCGIDI_angular
Definition at line 58 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 58 of file MCGIDI.h
typedef struct MCGIDI_angularEnergy_s MCGIDI_angularEnergy
Definition at line 64 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 64 of file MCGIDI.h
typedef struct MCGIDI_decaySamplingInfo_s MCGIDI_decaySamplingInfo
Definition at line 66 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 66 of file MCGIDI.h
typedef struct MCGIDI_distribution_s MCGIDI_distribution
Definition at line 52 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 52 of file MCGIDI.h
typedef struct MCGIDI_energy_s MCGIDI_energy
Definition at line 62 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 62 of file MCGIDI.h
typedef struct MCGIDI_energyAngular_s MCGIDI_energyAngular
Definition at line 63 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 63 of file MCGIDI.h
typedef struct MCGIDI_energyNBodyPhaseSpace_s MCGIDI_energyNBodyPhaseSpace
Definition at line 61 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 61 of file MCGIDI.h
typedef struct MCGIDI_energyWeightedFunctional_s MCGIDI_energyWeightedFunctional
Definition at line 59 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 59 of file MCGIDI.h
typedef struct MCGIDI_energyWeightedFunctionals_s MCGIDI_energyWeightedFunctionals
Definition at line 60 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 60 of file MCGIDI.h
typedef struct MCGIDI_GammaBranching_s MCGIDI_GammaBranching
Definition at line 41 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 41 of file MCGIDI.h
typedef struct MCGIDI_KalbachMann_s MCGIDI_KalbachMann
Definition at line 53 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 53 of file MCGIDI.h
typedef struct MCGIDI_KalbachMann_ras_s MCGIDI_KalbachMann_ras
Definition at line 54 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 54 of file MCGIDI.h
typedef struct MCGIDI_outputChannel_s MCGIDI_outputChannel
Definition at line 50 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 50 of file MCGIDI.h
typedef struct MCGIDI_particle_s MCGIDI_particle
Definition at line 44 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 44 of file MCGIDI.h
typedef struct MCGIDI_pdfOfX_s MCGIDI_pdfOfX
Definition at line 55 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 55 of file MCGIDI.h
typedef struct MCGIDI_pdfsOfXGivenW_s MCGIDI_pdfsOfXGivenW
Definition at line 56 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 56 of file MCGIDI.h
typedef struct MCGIDI_pdfsOfXGivenW_sampled_s MCGIDI_pdfsOfXGivenW_sampled
Definition at line 57 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 57 of file MCGIDI.h
typedef struct MCGIDI_POP_s MCGIDI_POP
Definition at line 42 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 42 of file MCGIDI.h
typedef struct MCGIDI_POPs_s MCGIDI_POPs
Definition at line 43 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 43 of file MCGIDI.h
typedef struct MCGIDI_product_s MCGIDI_product
Definition at line 51 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 51 of file MCGIDI.h
typedef struct MCGIDI_productInfo_s MCGIDI_productInfo
Definition at line 68 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 68 of file MCGIDI.h
typedef struct MCGIDI_productsInfo_s MCGIDI_productsInfo
Definition at line 67 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 67 of file MCGIDI.h
typedef struct MCGIDI_reaction_s MCGIDI_reaction
Definition at line 49 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 49 of file MCGIDI.h
typedef struct MCGIDI_sampledProductsData_s MCGIDI_sampledProductsData
Definition at line 69 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 69 of file MCGIDI.h
typedef struct MCGIDI_sampledProductsDatas_s MCGIDI_sampledProductsDatas
Definition at line 70 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 70 of file MCGIDI.h
typedef struct MCGIDI_samplingMultiplicityBias_s MCGIDI_samplingMultiplicityBias
Definition at line 114 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 114 of file MCGIDI.h
typedef struct MCGIDI_target_s MCGIDI_target
Definition at line 45 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 45 of file MCGIDI.h
typedef struct MCGIDI_target_heated_s MCGIDI_target_heated
Definition at line 48 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 48 of file MCGIDI.h
typedef struct MCGIDI_target_heated_info_s MCGIDI_target_heated_info
Definition at line 46 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 46 of file MCGIDI.h
typedef struct MCGIDI_target_heated_sorted_s MCGIDI_target_heated_sorted
Definition at line 47 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 47 of file MCGIDI.h
typedef std::map<int, enum GIDI::MCGIDI_transportability> transportabilitiesMap
Definition at line 171 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 171 of file MCGIDI.h
Enumeration Type Documentation
enum MCGIDI_angularType
Enumerator:
MCGIDI_angularType_isotropic
MCGIDI_angularType_recoil
MCGIDI_angularType_linear
Definition at line 212 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 212 of file MCGIDI.h
enum MCGIDI_channelGenre
Enumerator:
MCGIDI_channelGenre_undefined_e
MCGIDI_channelGenre_twoBody_e
MCGIDI_channelGenre_uncorrelated_e
MCGIDI_channelGenre_sumOfRemaining_e
MCGIDI_channelGenre_twoBodyDecay_e
MCGIDI_channelGenre_uncorrelatedDecay_e
Definition at line 202 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 202 of file MCGIDI.h
enum MCGIDI_distributionType
Enumerator:
MCGIDI_distributionType_none_e
MCGIDI_distributionType_unknown_e
MCGIDI_distributionType_angular_e
MCGIDI_distributionType_KalbachMann_e
MCGIDI_distributionType_uncorrelated_e
MCGIDI_distributionType_energyAngular_e
MCGIDI_distributionType_angularEnergy_e
Definition at line 208 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 208 of file MCGIDI.h
enum MCGIDI_energyType
Enumerator:
MCGIDI_energyType_unknown
MCGIDI_energyType_primaryGamma
MCGIDI_energyType_discreteGamma
MCGIDI_energyType_linear
MCGIDI_energyType_generalEvaporation
MCGIDI_energyType_simpleMaxwellianFission
MCGIDI_energyType_evaporation
MCGIDI_energyType_Watt
MCGIDI_energyType_MadlandNix
MCGIDI_energyType_NBodyPhaseSpace
MCGIDI_energyType_weightedFunctional
Definition at line 214 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 214 of file MCGIDI.h
enum MCGIDI_productMultiplicityType
Enumerator:
MCGIDI_productMultiplicityType_invalid_e
MCGIDI_productMultiplicityType_unknown_e
MCGIDI_productMultiplicityType_integer_e
MCGIDI_productMultiplicityType_energyDependent_e
MCGIDI_productMultiplicityType_gammaBranching_e
MCGIDI_productMultiplicityType_mixed_e
Definition at line 205 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 205 of file MCGIDI.h
enum MCGIDI_quantityLookupMode
Enumerator:
MCGIDI_quantityLookupMode_pointwise
Pointwise data are used to determine a quantity's value an energy E.
MCGIDI_quantityLookupMode_grouped
Grouped data are used to determine a quantity's value an energy E.
Definition at line 77 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 77 of file MCGIDI.h
enum MCGIDI_reactionType
Enumerator:
MCGIDI_reactionType_unknown_e
MCGIDI_reactionType_null_e
MCGIDI_reactionType_elastic_e
MCGIDI_reactionType_scattering_e
MCGIDI_reactionType_nuclearIsomerTransmutation_e
MCGIDI_reactionType_nuclearLevelTransition_e
MCGIDI_reactionType_capture_e
MCGIDI_reactionType_fission_e
MCGIDI_reactionType_sumOfRemainingOutputChannels_e
MCGIDI_reactionType_atomic_e
Definition at line 186 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 186 of file MCGIDI.h
enum MCGIDI_transportability
Enumerator:
MCGIDI_transportability_unknown
This enum is used to give the transportability status for a particle in a reaction or target. Particle is not a product of this reaction or target.
MCGIDI_transportability_none
Particle is a product but has not distribution data.
MCGIDI_transportability_partial
Particle is a product and has some distribution data.
MCGIDI_transportability_full
Definition at line 160 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 160 of file MCGIDI.h
Function Documentation
MCGIDI_angular* MCGIDI_angular_free (statusMessageReporting * smr, MCGIDI_angular * angular)
Definition at line 39 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_angular.cc
References MCGIDI_angular_release(), and smr_freeMemory().
Referenced by MCGIDI_angular_new(), MCGIDI_angular_parseFromTOM(), MCGIDI_distribution_release(), and MCGIDI_LLNLAngular_angularEnergy_parseFromTOM().
int MCGIDI_angular_initialize (statusMessageReporting * smr, MCGIDI_angular * angular)
Definition at line 31 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_angular.cc
Referenced by MCGIDI_angular_new(), and MCGIDI_angular_release().
MCGIDI_angular* MCGIDI_angular_new (statusMessageReporting * smr)
Definition at line 20 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_angular.cc
References MCGIDI_angular_free(), MCGIDI_angular_initialize(), and smr_malloc2.
Referenced by MCGIDI_angular_parseFromTOM().
int MCGIDI_angular_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution, ptwXYPoints * norms)
Definition at line 72 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 72 of file MCGIDI_angular.cc
References MCGIDI_distribution_s::angular, MCGIDI_pdfOfX_s::cdf, MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_angular_s::dists, check_license::err(), MCGIDI_angular_s::frame, int(), MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, xDataTOM_W_XYs_s::length, MCGIDI_angular_free(), MCGIDI_angular_new(), MCGIDI_angularType_isotropic, MCGIDI_angularType_linear, MCGIDI_angularType_recoil, MCGIDI_distributionType_angular_e, MCGIDI_fromTOM_interpolation(), MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf(), MCGIDI_misc_getProductFrame(), MCGIDI_misc_getUnitConversionFactor(), n, nfu_Okay, nfu_statusMessage(), norm, MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_pdfOfX_s::numberOfXs, MCGIDI_pdfOfX_s::pdf, ptwX_free(), ptwX_getPointAtIndex_Unsafely(), ptwXY_free(), ptwXY_getPointAtIndex_Unsafely(), ptwXY_length(), ptwXY_runningIntegral(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), smr_isOk(), smr_malloc2, smr_setReportError2, smr_unknownID, xDataTOM_W_XYs_s::subAxes, MCGIDI_angular_s::type, MCGIDI_distribution_s::type, xDataTOM_XYs_s::value, MCGIDI_pdfsOfXGivenW_s::Ws, ptwXYPoint_s::x, xDataTOM_frame_invalid, xDataTOM_getAttributesValueInElement(), xDataTOM_subAxes_getUnit(), xDataTOME_getOneElementByName(), xDataTOME_getXDataIfID(), MCGIDI_pdfOfX_s::Xs, xDataTOM_W_XYs_s::XYs, and ptwXYPoint_s::y.
Referenced by MCGIDI_distribution_parseFromTOM(), MCGIDI_LLNLAngular_angularEnergy_parseFromTOM(), and MCGIDI_uncorrelated_parseFromTOM().
int MCGIDI_angular_release (statusMessageReporting * smr, MCGIDI_angular * angular)
Definition at line 48 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 48 of file MCGIDI_angular.cc
References MCGIDI_angular_s::dists, MCGIDI_angular_initialize(), and MCGIDI_sampling_pdfsOfXGivenW_release().
Referenced by MCGIDI_angular_free().
int MCGIDI_angular_sampleMu (statusMessageReporting * smr, MCGIDI_angular * angular, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 182 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 182 of file MCGIDI_angular.cc
References MCGIDI_angular_s::dists, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_angular_s::frame, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_angularType_isotropic, MCGIDI_angularType_linear, MCGIDI_angularType_recoil, MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_isOk(), smr_setReportError2, smr_unknownID, MCGIDI_angular_s::type, MCGIDI_pdfsOfXGivenW_sampled_s::w, and MCGIDI_pdfsOfXGivenW_sampled_s::x.
Referenced by MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_product_sampleMu(), and MCGIDI_uncorrelated_sampleDistribution().
int MCGIDI_angular_setTwoBodyMasses (statusMessageReporting * smr, MCGIDI_angular * angular, double projectileMass_MeV, double targetMass_MeV, double productMass_MeV, double residualMass_MeV)
Definition at line 59 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 59 of file MCGIDI_angular.cc
References MCGIDI_angular_s::productMass_MeV, MCGIDI_angular_s::projectileMass_MeV, MCGIDI_angular_s::residualMass_MeV, and MCGIDI_angular_s::targetMass_MeV.
Referenced by MCGIDI_product_setTwoBodyMasses().
MCGIDI_angularEnergy* MCGIDI_angularEnergy_free (statusMessageReporting * smr, MCGIDI_angularEnergy * energyAngular)
Definition at line 40 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 40 of file MCGIDI_angularEnergy.cc
References MCGIDI_angularEnergy_release(), and smr_freeMemory().
Referenced by MCGIDI_angularEnergy_new(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), and MCGIDI_distribution_release().
int MCGIDI_angularEnergy_initialize (statusMessageReporting * smr, MCGIDI_angularEnergy * energyAngular)
Definition at line 32 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 32 of file MCGIDI_angularEnergy.cc
Referenced by MCGIDI_angularEnergy_new(), and MCGIDI_angularEnergy_release().
MCGIDI_angularEnergy* MCGIDI_angularEnergy_new (statusMessageReporting * smr)
Definition at line 21 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 21 of file MCGIDI_angularEnergy.cc
References MCGIDI_angularEnergy_free(), MCGIDI_angularEnergy_initialize(), and smr_malloc2.
Referenced by MCGIDI_angularEnergy_parsePointwiseFromTOM(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
int MCGIDI_angularEnergy_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution)
Definition at line 65 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 65 of file MCGIDI_angularEnergy.cc
References check_license::err(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), smr_setReportError2, smr_unknownID, xDataTOM_getAttributesValueInElement(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_distribution_parseFromTOM().
int MCGIDI_angularEnergy_release (statusMessageReporting * smr, MCGIDI_angularEnergy * energyAngular)
Definition at line 49 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 49 of file MCGIDI_angularEnergy.cc
References MCGIDI_angularEnergy_initialize(), MCGIDI_sampling_pdfsOfXGivenW_release(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_angularEnergy_s::pdfOfEpGivenEAndMu, MCGIDI_angularEnergy_s::pdfOfMuGivenE, and smr_freeMemory().
Referenced by MCGIDI_angularEnergy_free().
int MCGIDI_angularEnergy_sampleDistribution (statusMessageReporting * smr, MCGIDI_angularEnergy * angularEnergy, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 175 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 175 of file MCGIDI_angularEnergy.cc
References MCGIDI_decaySamplingInfo_s::frame, MCGIDI_angularEnergy_s::frame, MCGIDI_sampling_doubleDistribution(), MCGIDI_angularEnergy_s::pdfOfEpGivenEAndMu, and MCGIDI_angularEnergy_s::pdfOfMuGivenE.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
MCGIDI_distribution* MCGIDI_distribution_free (statusMessageReporting * smr, MCGIDI_distribution * distribution)
Definition at line 38 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 38 of file MCGIDI_distribution.cc
References MCGIDI_distribution_release(), and smr_freeMemory().
Referenced by MCGIDI_distribution_new().
int MCGIDI_distribution_initialize (statusMessageReporting * smr, MCGIDI_distribution * distribution)
Definition at line 30 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 30 of file MCGIDI_distribution.cc
Referenced by MCGIDI_distribution_new(), MCGIDI_distribution_parseFromTOM(), and MCGIDI_distribution_release().
MCGIDI_distribution* MCGIDI_distribution_new (statusMessageReporting * smr)
Definition at line 19 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 19 of file MCGIDI_distribution.cc
References MCGIDI_distribution_free(), MCGIDI_distribution_initialize(), and smr_malloc2.
int MCGIDI_distribution_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_product * product, MCGIDI_POPs * pops, ptwXYPoints * norms)
Definition at line 61 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 61 of file MCGIDI_distribution.cc
References MCGIDI_product_s::distribution, check_license::err(), MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_distribution_initialize(), MCGIDI_distribution_release(), MCGIDI_distributionType_none_e, MCGIDI_distributionType_unknown_e, MCGIDI_energyAngular_parseFromTOM(), MCGIDI_energyType_discreteGamma, MCGIDI_energyType_primaryGamma, MCGIDI_energyType_unknown, MCGIDI_LLNLAngular_angularEnergy_parseFromTOM(), MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_uncorrelated_parseFromTOM(), MCGIDI_POP_s::name, MCGIDI_product_s::pop, MCGIDI_distribution_s::product, smr_setReportError2, smr_unknownID, MCGIDI_distribution_s::type, xDataTOM_getAttributesValueInElement(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_product_parseFromTOM().
int MCGIDI_distribution_release (statusMessageReporting * smr, MCGIDI_distribution * distribution)
Definition at line 47 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 47 of file MCGIDI_distribution.cc
References MCGIDI_distribution_s::angular, MCGIDI_distribution_s::angularEnergy, MCGIDI_distribution_s::energy, MCGIDI_distribution_s::energyAngular, MCGIDI_distribution_s::KalbachMann, MCGIDI_angular_free(), MCGIDI_angularEnergy_free(), MCGIDI_distribution_initialize(), MCGIDI_energy_free(), MCGIDI_energyAngular_free(), and MCGIDI_KalbachMann_free().
Referenced by MCGIDI_distribution_free(), MCGIDI_distribution_parseFromTOM(), and MCGIDI_product_release().
MCGIDI_energy* MCGIDI_energy_free (statusMessageReporting * smr, MCGIDI_energy * energy)
Definition at line 65 of file MCGIDI_energy.cc.
View newest version in sPHENIX GitHub at line 65 of file MCGIDI_energy.cc
References MCGIDI_energy_release(), and smr_freeMemory().
Referenced by MCGIDI_distribution_release(), MCGIDI_energy_new(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseWeightFromTOM(), and MCGIDI_energy_release().
int MCGIDI_energy_initialize (statusMessageReporting * smr, MCGIDI_energy * energy)
Definition at line 57 of file MCGIDI_energy.cc.
View newest version in sPHENIX GitHub at line 57 of file MCGIDI_energy.cc
Referenced by MCGIDI_energy_new(), and MCGIDI_energy_release().
MCGIDI_energy* MCGIDI_energy_new (statusMessageReporting * smr)
Definition at line 46 of file MCGIDI_energy.cc.
View newest version in sPHENIX GitHub at line 46 of file MCGIDI_energy.cc
References energy, MCGIDI_energy_free(), MCGIDI_energy_initialize(), and smr_malloc2.
Referenced by MCGIDI_energy_parseFromTOM(), and MCGIDI_energy_parseWeightFromTOM().
int MCGIDI_energy_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution, ptwXYPoints * norms, enum MCGIDI_energyType energyType, double gammaEnergy_MeV)
Definition at line 97 of file MCGIDI_energy.cc.
View newest version in sPHENIX GitHub at line 97 of file MCGIDI_energy.cc
References MCGIDI_energy_s::dists, MCGIDI_energy_s::e_inCOMFactor, energy, MCGIDI_distribution_s::energy, check_license::err(), MCGIDI_energy_s::frame, MCGIDI_energy_s::gammaEnergy_MeV, MCGIDI_energy_free(), MCGIDI_energy_new(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energy_parseWeightedFunctionalsFromTOM(), MCGIDI_energyType_discreteGamma, MCGIDI_energyType_linear, MCGIDI_energyType_primaryGamma, MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_misc_getProductFrame(), MCGIDI_product_getProjectileMass_MeV(), MCGIDI_product_getTargetMass_MeV(), MCGIDI_energy_s::primaryGammaMassFactor, MCGIDI_distribution_s::product, smr_setReportError2, smr_unknownID, MCGIDI_energy_s::type, xDataTOM_frame_invalid, xDataTOM_frame_lab, xDataTOM_getAttributesValueInElement(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_uncorrelated_parseFromTOM().
int MCGIDI_energy_release (statusMessageReporting * smr, MCGIDI_energy * energy)
Definition at line 74 of file MCGIDI_energy.cc.
View newest version in sPHENIX GitHub at line 74 of file MCGIDI_energy.cc
References MCGIDI_energy_s::dists, MCGIDI_energyWeightedFunctional_s::energy, MCGIDI_energy_s::g, MCGIDI_energy_free(), MCGIDI_energy_initialize(), MCGIDI_energyType_generalEvaporation, MCGIDI_energyType_NBodyPhaseSpace, MCGIDI_energyType_weightedFunctional, MCGIDI_sampling_pdfsOfX_release(), MCGIDI_sampling_pdfsOfXGivenW_release(), MCGIDI_energyWeightedFunctionals_s::numberOfWeights, ptwXY_free(), MCGIDI_energy_s::theta, MCGIDI_energy_s::type, MCGIDI_energy_s::Watt_a, MCGIDI_energy_s::Watt_b, MCGIDI_energyWeightedFunctional_s::weight, MCGIDI_energyWeightedFunctionals_s::weightedFunctional, and MCGIDI_energy_s::weightedFunctionals.
Referenced by MCGIDI_energy_free().
int MCGIDI_energy_sampleEnergy (statusMessageReporting * smr, MCGIDI_energy * energy, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 497 of file MCGIDI_energy.cc.
View newest version in sPHENIX GitHub at line 497 of file MCGIDI_energy.cc
References MCGIDI_energy_s::dists, MCGIDI_energy_s::e_inCOMFactor, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_energy_s::frame, MCGIDI_energy_s::g, MCGIDI_energy_s::gammaEnergy_MeV, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_energy_s::gInterpolation, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, MCGIDI_energyNBodyPhaseSpace_s::massFactor, MCGIDI_energy_sampleEvaporation(), MCGIDI_energy_sampleSimpleMaxwellianFission(), MCGIDI_energy_sampleWatt(), MCGIDI_energy_sampleWeightedFunctional(), MCGIDI_energyType_discreteGamma, MCGIDI_energyType_evaporation, MCGIDI_energyType_generalEvaporation, MCGIDI_energyType_linear, MCGIDI_energyType_MadlandNix, MCGIDI_energyType_NBodyPhaseSpace, MCGIDI_energyType_primaryGamma, MCGIDI_energyType_simpleMaxwellianFission, MCGIDI_energyType_Watt, MCGIDI_energyType_weightedFunctional, MCGIDI_sampling_ptwXY_getValueAtX(), MCGIDI_sampling_sampleX_from_pdfOfX(), MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_energy_s::NBodyPhaseSpace, MCGIDI_energy_s::primaryGammaMassFactor, MCGIDI_energyNBodyPhaseSpace_s::Q_MeV, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_isOk(), smr_setReportError2, smr_unknownID, theta(), MCGIDI_energy_s::theta, MCGIDI_energy_s::type, MCGIDI_energy_s::U, MCGIDI_pdfsOfXGivenW_sampled_s::w, MCGIDI_energy_s::Watt_a, MCGIDI_energy_s::Watt_b, and MCGIDI_pdfsOfXGivenW_sampled_s::x.
Referenced by MCGIDI_energy_sampleWeightedFunctional(), and MCGIDI_uncorrelated_sampleDistribution().
MCGIDI_energyAngular* MCGIDI_energyAngular_free (statusMessageReporting * smr, MCGIDI_energyAngular * energyAngular)
Definition at line 39 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_energyAngular.cc
References MCGIDI_energyAngular_release(), and smr_freeMemory().
Referenced by MCGIDI_distribution_release(), MCGIDI_energyAngular_linear_parseFromTOM(), and MCGIDI_energyAngular_new().
int MCGIDI_energyAngular_initialize (statusMessageReporting * smr, MCGIDI_energyAngular * energyAngular)
Definition at line 31 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_energyAngular.cc
Referenced by MCGIDI_energyAngular_new(), and MCGIDI_energyAngular_release().
MCGIDI_energyAngular* MCGIDI_energyAngular_new (statusMessageReporting * smr)
Definition at line 20 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_energyAngular.cc
References MCGIDI_energyAngular_free(), MCGIDI_energyAngular_initialize(), and smr_malloc2.
Referenced by MCGIDI_energyAngular_linear_parseFromTOM().
int MCGIDI_energyAngular_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution)
Definition at line 64 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 64 of file MCGIDI_energyAngular.cc
References check_license::err(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_KalbachMann_parseFromTOM(), smr_setReportError2, smr_unknownID, xDataTOM_getAttributesValueInElement(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_distribution_parseFromTOM().
int MCGIDI_energyAngular_release (statusMessageReporting * smr, MCGIDI_energyAngular * energyAngular)
Definition at line 48 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 48 of file MCGIDI_energyAngular.cc
References MCGIDI_energyAngular_initialize(), MCGIDI_sampling_pdfsOfXGivenW_release(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_energyAngular_s::pdfOfEpGivenE, MCGIDI_energyAngular_s::pdfOfMuGivenEAndEp, and smr_freeMemory().
Referenced by MCGIDI_energyAngular_free().
int MCGIDI_energyAngular_sampleDistribution (statusMessageReporting * smr, MCGIDI_distribution * distribution, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 180 of file MCGIDI_energyAngular.cc.
View newest version in sPHENIX GitHub at line 180 of file MCGIDI_energyAngular.cc
References MCGIDI_distribution_s::energyAngular, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_energyAngular_s::frame, MCGIDI_sampling_doubleDistribution(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_energyAngular_s::pdfOfEpGivenE, and MCGIDI_energyAngular_s::pdfOfMuGivenEAndEp.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
MCGIDI_KalbachMann* MCGIDI_KalbachMann_free (statusMessageReporting * smr, MCGIDI_KalbachMann * KalbachMann)
Definition at line 61 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 61 of file MCGIDI_KalbachMann.cc
References MCGIDI_KalbachMann_release(), and smr_freeMemory().
Referenced by MCGIDI_distribution_release(), MCGIDI_KalbachMann_new(), and MCGIDI_KalbachMann_parseFromTOM().
int MCGIDI_KalbachMann_initialize (statusMessageReporting * smr, MCGIDI_KalbachMann * KalbachMann, ptwXY_interpolation interpolationWY, ptwXY_interpolation interpolationXY)
Definition at line 51 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 51 of file MCGIDI_KalbachMann.cc
References MCGIDI_KalbachMann_s::dists, MCGIDI_pdfsOfXGivenW_s::interpolationWY, and MCGIDI_pdfsOfXGivenW_s::interpolationXY.
Referenced by MCGIDI_KalbachMann_new(), and MCGIDI_KalbachMann_release().
MCGIDI_KalbachMann* MCGIDI_KalbachMann_new (statusMessageReporting * smr, ptwXY_interpolation interpolationWY, ptwXY_interpolation interpolationXY)
Definition at line 39 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_KalbachMann.cc
References MCGIDI_KalbachMann_free(), MCGIDI_KalbachMann_initialize(), and smr_malloc2.
Referenced by MCGIDI_KalbachMann_parseFromTOM().
int MCGIDI_KalbachMann_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution)
Definition at line 89 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 89 of file MCGIDI_KalbachMann.cc
References MCGIDI_POP_s::A, xDataTOM_xDataInfo_s::axes, xDataTOM_KalbachMann_s::coefficients, xDataTOM_xDataInfo_s::data, MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_KalbachMann_s::dists, MCGIDI_KalbachMann_s::energyToMeVFactor, check_license::err(), MCGIDI_KalbachMann_s::frame, MCGIDI_distribution_s::KalbachMann, MCGIDI_KalbachMann_s::Ma, MCGIDI_KalbachMann_s::massFactor, MCGIDI_KalbachMann_s::mb, MCGIDI_distributionType_KalbachMann_e, MCGIDI_fromTOM_interpolation(), MCGIDI_KalbachMann_free(), MCGIDI_KalbachMann_new(), MCGIDI_KalbachMann_parseFromTOM2(), MCGIDI_KalbachMann_S_a_or_b(), MCGIDI_misc_getProductFrame(), MCGIDI_misc_getUnitConversionFactor(), MCGIDI_product_getTargetHeated(), MCGIDI_target_heated_getPOPForProjectile(), MCGIDI_target_heated_getPOPForTarget(), xDataTOM_KalbachMann_s::numberOfEnergies, MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_product_s::pop, MCGIDI_distribution_s::product, MCGIDI_KalbachMann_s::ras, MCGIDI_KalbachMann_s::Sa, MCGIDI_KalbachMann_s::Sb, smr_isOk(), smr_malloc2, xDataTOM_KalbachMann_s::type, MCGIDI_distribution_s::type, MCGIDI_pdfsOfXGivenW_s::Ws, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getUnit(), xDataTOM_frame_invalid, xDataTOM_KalbachMannType_fra, xDataTOME_getOneElementByName(), and MCGIDI_POP_s::Z.
Referenced by MCGIDI_energyAngular_parseFromTOM().
int MCGIDI_KalbachMann_release (statusMessageReporting * smr, MCGIDI_KalbachMann * KalbachMann)
Definition at line 70 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 70 of file MCGIDI_KalbachMann.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_KalbachMann_s::dists, MCGIDI_KalbachMann_initialize(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, ptwXY_interpolationLinLin, MCGIDI_KalbachMann_s::ras, MCGIDI_KalbachMann_ras_s::rs, smr_freeMemory(), MCGIDI_pdfsOfXGivenW_s::Ws, and MCGIDI_pdfOfX_s::Xs.
Referenced by MCGIDI_KalbachMann_free().
int MCGIDI_KalbachMann_sampleEp (statusMessageReporting * smr, MCGIDI_KalbachMann * KalbachMann, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 294 of file MCGIDI_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 294 of file MCGIDI_KalbachMann.cc
References a, MCGIDI_KalbachMann_ras_s::as, C1, C2, MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_KalbachMann_s::dists, MCGIDI_KalbachMann_s::energyToMeVFactor, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_pdfsOfXGivenW_sampled_s::frac, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_KalbachMann_s::frame, G4Exp(), G4Log(), MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_pdfsOfXGivenW_sampled_s::interpolationWY, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, MCGIDI_pdfsOfXGivenW_sampled_s::iW, MCGIDI_pdfsOfXGivenW_sampled_s::iX1, MCGIDI_pdfsOfXGivenW_sampled_s::iX2, MCGIDI_KalbachMann_s::Ma, MCGIDI_KalbachMann_s::massFactor, MCGIDI_KalbachMann_s::mb, MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_pdfsOfXGivenW_s::numberOfWs, ptwXY_interpolationFlat, ptwXY_interpolationLinLin, r, r2, MCGIDI_KalbachMann_s::ras, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_KalbachMann_ras_s::rs, MCGIDI_KalbachMann_s::Sb, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_isOk(), T, MCGIDI_pdfsOfXGivenW_sampled_s::w, MCGIDI_pdfsOfXGivenW_sampled_s::x, X1, and MCGIDI_pdfOfX_s::Xs.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
int MCGIDI_kinetics_2BodyReaction (statusMessageReporting * smr, MCGIDI_angular * angular, double K, double mu, double phi, MCGIDI_sampledProductsData * outgoingData)
Definition at line 18 of file MCGIDI_kinetics.cc.
View newest version in sPHENIX GitHub at line 18 of file MCGIDI_kinetics.cc
References e, m2, m3, MCGIDI_kinetics_COMKineticEnergy2LabEnergyAndMomentum(), MCGIDI_angular_s::productMass_MeV, MCGIDI_angular_s::projectileMass_MeV, MCGIDI_angular_s::residualMass_MeV, MCGIDI_angular_s::targetMass_MeV, and x.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
int MCGIDI_kinetics_COM2Lab (statusMessageReporting * smr, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, double masses[3])
Definition at line 105 of file MCGIDI_kinetics.cc.
View newest version in sPHENIX GitHub at line 105 of file MCGIDI_kinetics.cc
References a, b, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_decaySamplingInfo_s::mu, smr_setReportError2, smr_unknownID, xDataTOM_frame_centerOfMass, and xDataTOM_frame_lab.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
int MCGIDI_kinetics_COMKineticEnergy2LabEnergyAndMomentum (statusMessageReporting * smr, double beta, double e_kinetic_com, double mu, double phi, double m3cc, double m4cc, MCGIDI_sampledProductsData * outgoingData)
Definition at line 38 of file MCGIDI_kinetics.cc.
View newest version in sPHENIX GitHub at line 38 of file MCGIDI_kinetics.cc
References e, MCGIDI_sampledProductsData_s::isVelocity, MCGIDI_sampledProductsData_s::kineticEnergy, MCGIDI_speedOfLight_cm_sec, MCGIDI_sampledProductsData_s::px_vx, MCGIDI_sampledProductsData_s::py_vy, MCGIDI_sampledProductsData_s::pz_vz, and x.
Referenced by MCGIDI_kinetics_2BodyReaction().
int MCGIDI_LLNLAngular_angularEnergy_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution)
Definition at line 22 of file MCGIDI_LLNLAngular_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 22 of file MCGIDI_LLNLAngular_angularEnergy.cc
References MCGIDI_distribution_s::angular, check_license::err(), MCGIDI_angular_free(), MCGIDI_angular_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_distribution_parseFromTOM().
xDataTOM_Int MCGIDI_misc_binarySearch (xDataTOM_Int n, double * ds, double d)
Definition at line 228 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 228 of file MCGIDI_misc.cc
References imax.
Referenced by MCGIDI_sampling_doubleDistribution(), MCGIDI_sampling_sampleX_from_pdfOfX(), and MCGIDI_sampling_sampleX_from_pdfsOfXGivenW().
int MCGIDI_misc_NumberOfZSymbols (void)
Definition at line 54 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 54 of file MCGIDI_misc.cc
References ZSymbols.
Referenced by MCGIDI_misc_symbolToZ(), and MCGIDI_misc_ZToSymbol().
int MCGIDI_misc_PQUStringToDouble (statusMessageReporting * smr, char const * str, char const * unit, double conversion, double * value)
Definition at line 330 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 330 of file MCGIDI_misc.cc
References e, smr_setReportError2, and smr_unknownID.
Referenced by MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), and MCGIDI_target_heated_parseParticle().
int MCGIDI_misc_PQUStringToDoubleInUnitOf (statusMessageReporting * smr, char const * str, char const * toUnit, double * value)
Definition at line 356 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 356 of file MCGIDI_misc.cc
References e1, MCGIDI_misc_getUnitConversionFactor(), s1, smr_isOk(), smr_setReportError2, and smr_unknownID.
Referenced by MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_product_parseFromTOM(), and MCGIDI_target_heated_parseParticleLevel().
int MCGIDI_misc_symbolToZ (const char * Z)
Definition at line 69 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 69 of file MCGIDI_misc.cc
References MCGIDI_misc_NumberOfZSymbols(), n, ZSymbol::symbol, and ZSymbols.
Referenced by MCGIDI_miscNameToZAm().
void MCGIDI_misc_updateTransportabilitiesMap (transportabilitiesMap * transportabilities, int PoPID, enum MCGIDI_transportability transportability)
Definition at line 482 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 482 of file MCGIDI_misc.cc
References MCGIDI_transportability_full, MCGIDI_transportability_none, MCGIDI_transportability_partial, and MCGIDI_transportability_unknown.
Referenced by MCGIDI_misc_updateTransportabilitiesMap2(), and MCGIDI_target_heated_read().
void MCGIDI_misc_updateTransportabilitiesMap2 (transportabilitiesMap * transportabilities, int PoPID, int transportable)
Definition at line 524 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 524 of file MCGIDI_misc.cc
References MCGIDI_misc_updateTransportabilitiesMap(), MCGIDI_transportability_full, and MCGIDI_transportability_none.
Referenced by MCGIDI_reaction_addReturnProduct().
const char* MCGIDI_misc_ZToSymbol (int iZ)
Definition at line 61 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 61 of file MCGIDI_misc.cc
References MCGIDI_misc_NumberOfZSymbols(), ZSymbol::symbol, and ZSymbols.
Referenced by G4GIDI_Misc_Z_A_m_ToName().
int MCGIDI_miscNameToZAm (statusMessageReporting * smr, const char * name, int * Z, int * A, int * m, int * level)
Definition at line 81 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 81 of file MCGIDI_misc.cc
References e, int(), MCGIDI_misc_symbolToZ(), MCGIDI_miscNameToZAm_getLevel(), smr_isOk(), smr_setReportError2, and smr_unknownID.
Referenced by G4GIDI_Misc_channelCompound(), MCGIDI_particle_getInternalID(), and MCGIDI_POP_new().
MCGIDI_outputChannel* MCGIDI_outputChannel_free (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 39 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_release(), and smr_freeMemory().
Referenced by MCGIDI_outputChannel_new().
int MCGIDI_outputChannel_getDomain (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, double * EMin, double * EMax)
Definition at line 153 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 153 of file MCGIDI_outputChannel.cc
References MCGIDI_product_getDomain(), MCGIDI_reaction_getDomain(), MCGIDI_outputChannel_s::parent, and MCGIDI_outputChannel_s::reaction.
Referenced by MCGIDI_product_getDomain().
double MCGIDI_outputChannel_getFinalQ (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, double e_in)
Definition at line 192 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 192 of file MCGIDI_outputChannel.cc
References MCGIDI_product_s::decayChannel, MCGIDI_outputChannel_s::genre, MCGIDI_channelGenre_undefined_e, MCGIDI_outputChannel_getFinalQ(), MCGIDI_outputChannel_s::numberOfProducts, MCGIDI_outputChannel_s::products, Q, MCGIDI_outputChannel_s::Q, and smr_isOk().
Referenced by MCGIDI_outputChannel_getFinalQ().
MCGIDI_product* MCGIDI_outputChannel_getProductAtIndex (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, int i)
Definition at line 142 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 142 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_s::numberOfProducts, MCGIDI_outputChannel_s::products, smr_setReportError2, and smr_unknownID.
Referenced by G4GIDI_target::getElasticFinalState(), and MCGIDI_reaction_ParseDetermineReactionProducts().
double MCGIDI_outputChannel_getProjectileMass_MeV (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 169 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 169 of file MCGIDI_outputChannel.cc
References MCGIDI_product_getProjectileMass_MeV(), MCGIDI_reaction_getProjectileMass_MeV(), MCGIDI_outputChannel_s::parent, and MCGIDI_outputChannel_s::reaction.
Referenced by MCGIDI_product_getProjectileMass_MeV().
double MCGIDI_outputChannel_getQ_MeV (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, double e_in)
Definition at line 185 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 185 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_s::Q.
Referenced by MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), and MCGIDI_reaction_ParseDetermineReactionProducts().
MCGIDI_target_heated* MCGIDI_outputChannel_getTargetHeated (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 161 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 161 of file MCGIDI_outputChannel.cc
References MCGIDI_product_getTargetHeated(), MCGIDI_reaction_getTargetHeated(), MCGIDI_outputChannel_s::parent, and MCGIDI_outputChannel_s::reaction.
Referenced by MCGIDI_product_getTargetHeated().
double MCGIDI_outputChannel_getTargetMass_MeV (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 177 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 177 of file MCGIDI_outputChannel.cc
References MCGIDI_product_getTargetMass_MeV(), MCGIDI_reaction_getTargetMass_MeV(), MCGIDI_outputChannel_s::parent, and MCGIDI_outputChannel_s::reaction.
Referenced by MCGIDI_product_getTargetMass_MeV().
int MCGIDI_outputChannel_initialize (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 31 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_outputChannel.cc
Referenced by MCGIDI_outputChannel_new(), MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_outputChannel_release().
MCGIDI_outputChannel* MCGIDI_outputChannel_new (statusMessageReporting * smr)
Definition at line 20 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_free(), MCGIDI_outputChannel_initialize(), and smr_malloc2.
int MCGIDI_outputChannel_numberOfProducts (MCGIDI_outputChannel * outputChannel)
Definition at line 135 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 135 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_s::numberOfProducts.
Referenced by MCGIDI_reaction_ParseDetermineReactionProducts().
int MCGIDI_outputChannel_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_POPs * pops, MCGIDI_outputChannel * outputChannel, MCGIDI_reaction * reaction, MCGIDI_product * parent)
Definition at line 61 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 61 of file MCGIDI_outputChannel.cc
References MCGIDI_POP_s::A, MCGIDI_reaction_s::ENDF_MT, check_license::err(), MCGIDI_outputChannel_s::genre, MCGIDI_AMU2MeV, MCGIDI_channelGenre_sumOfRemaining_e, MCGIDI_channelGenre_twoBody_e, MCGIDI_channelGenre_uncorrelated_e, MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_outputChannel_initialize(), MCGIDI_outputChannel_release(), MCGIDI_product_getMass_MeV(), MCGIDI_product_parseFromTOM(), MCGIDI_product_setTwoBodyMasses(), MCGIDI_reaction_getProjectileMass_MeV(), MCGIDI_reaction_getTargetMass_MeV(), n, xDataTOM_element_s::name, MCGIDI_outputChannel_s::numberOfProducts, MCGIDI_outputChannel_s::parent, MCGIDI_product_s::pop, printf(), MCGIDI_outputChannel_s::products, Q, MCGIDI_outputChannel_s::Q, MCGIDI_outputChannel_s::QIsFloat, MCGIDI_outputChannel_s::reaction, smr_malloc2, smr_setReportError2, smr_setReportError2p, smr_unknownID, xDataTOM_getAttributesValueInElement(), xDataTOM_numberOfElementsByName(), xDataTOME_getFirstElement(), xDataTOME_getNextElement(), and MCGIDI_POP_s::Z.
Referenced by MCGIDI_product_parseFromTOM(), and MCGIDI_reaction_parseFromTOM().
int MCGIDI_outputChannel_release (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 48 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 48 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_initialize(), MCGIDI_product_release(), MCGIDI_outputChannel_s::numberOfProducts, MCGIDI_outputChannel_s::products, and smr_freeMemory().
Referenced by MCGIDI_outputChannel_free(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_product_release(), and MCGIDI_reaction_release().
int MCGIDI_outputChannel_sampleProductsAtE (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, MCGIDI_sampledProductsDatas * productDatas, double * masses)
Definition at line 208 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 208 of file MCGIDI_outputChannel.cc
References MCGIDI_distribution_s::angular, MCGIDI_distribution_s::angularEnergy, MCGIDI_sampledProductsData_s::birthTimeSec, MCGIDI_product_s::decayChannel, MCGIDI_sampledProductsData_s::delayedNeutronIndex, MCGIDI_product_s::delayedNeutronIndex, MCGIDI_sampledProductsData_s::delayedNeutronRate, MCGIDI_product_s::delayedNeutronRate, MCGIDI_product_s::distribution, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_decaySamplingInfo_s::frame, G4Log(), MCGIDI_outputChannel_s::genre, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_decaySamplingInfo_s::isVelocity, MCGIDI_sampledProductsData_s::isVelocity, MCGIDI_distribution_s::KalbachMann, MCGIDI_sampledProductsData_s::kineticEnergy, M_PI, MCGIDI_POP_s::mass_MeV, MCGIDI_angular_sampleMu(), MCGIDI_angularEnergy_sampleDistribution(), MCGIDI_channelGenre_sumOfRemaining_e, MCGIDI_channelGenre_twoBody_e, MCGIDI_channelGenre_twoBodyDecay_e, MCGIDI_channelGenre_uncorrelated_e, MCGIDI_channelGenre_uncorrelatedDecay_e, MCGIDI_channelGenre_undefined_e, MCGIDI_distributionType_angularEnergy_e, MCGIDI_distributionType_energyAngular_e, MCGIDI_distributionType_KalbachMann_e, MCGIDI_distributionType_none_e, MCGIDI_distributionType_uncorrelated_e, MCGIDI_energyAngular_sampleDistribution(), MCGIDI_KalbachMann_sampleEp(), MCGIDI_kinetics_2BodyReaction(), MCGIDI_kinetics_COM2Lab(), MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_product_getMass_MeV(), MCGIDI_product_sampleMultiplicity(), MCGIDI_reaction_getProjectileMass_MeV(), MCGIDI_reaction_getTargetMass_MeV(), MCGIDI_sampledProducts_addProduct(), MCGIDI_speedOfLight_cm_sec, MCGIDI_uncorrelated_sampleDistribution(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_product_s::multiplicity, MCGIDI_POP_s::name, MCGIDI_sampledProductsDatas_s::numberOfProducts, MCGIDI_outputChannel_s::numberOfProducts, phi, MCGIDI_decaySamplingInfo_s::pop, MCGIDI_sampledProductsData_s::pop, MCGIDI_product_s::pop, printf(), MCGIDI_outputChannel_s::products, MCGIDI_sampledProductsData_s::px_vx, MCGIDI_sampledProductsData_s::py_vy, MCGIDI_sampledProductsData_s::pz_vz, MCGIDI_outputChannel_s::reaction, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, smr_isOk(), MCGIDI_distribution_s::type, and xDataTOM_frame_centerOfMass.
Referenced by MCGIDI_outputChannel_sampleProductsAtE(), and MCGIDI_target_heated_sampleIndexReactionProductsAtE().
MCGIDI_particle* MCGIDI_particle_free (statusMessageReporting * smr, MCGIDI_particle * particle)
Definition at line 39 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_particle.cc
References MCGIDI_particle_release(), MCGIDI_particle_s::next, numberOfParticles, particleList, particleListEnd, particleSortedList, MCGIDI_particle_s::prior, and smr_freeMemory().
Referenced by MCGIDI_particle_freeInternalList(), and MCGIDI_particle_getInternalID().
int MCGIDI_particle_freeInternalList (statusMessageReporting * smr)
Definition at line 70 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 70 of file MCGIDI_particle.cc
References MCGIDI_particle_free(), particleList, particleSortedList, and smr_freeMemory().
MCGIDI_particle* MCGIDI_particle_getInternalID (statusMessageReporting * smr, const char *const name, MCGIDI_POPs * pops)
Definition at line 79 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 79 of file MCGIDI_particle.cc
References A(), MCGIDI_particle_s::A, check_license::err(), incrementalSizeOfList, initialSizeOfList, m, MCGIDI_particle_s::m, MCGIDI_POP_s::mass_MeV, MCGIDI_particle_s::mass_MeV, max, MCGIDI_AMU2MeV, MCGIDI_miscNameToZAm(), MCGIDI_particle_free(), MCGIDI_particle_new(), MCGIDI_particleMass_AMU(), MCGIDI_POPs_findParticle(), min, MCGIDI_particle_s::name, MCGIDI_particle_s::next, numberOfParticles, MCGIDI_particle_s::ordinal, particle, particleList, particleListEnd, particleSortedList, MCGIDI_particle_s::prior, sizeOfParticleSortedList, smr_allocateCopyString(), smr_isOk(), smr_realloc2, Z, and MCGIDI_particle_s::Z.
int MCGIDI_particle_initialize (statusMessageReporting * smr, MCGIDI_particle * particle)
Definition at line 31 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_particle.cc
Referenced by MCGIDI_particle_new().
MCGIDI_particle* MCGIDI_particle_new (statusMessageReporting * smr)
Definition at line 20 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_particle.cc
References MCGIDI_particle_initialize(), particle, and smr_malloc2.
Referenced by MCGIDI_particle_getInternalID().
int MCGIDI_particle_printInternalSortedList (statusMessageReporting * smr)
Definition at line 159 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 159 of file MCGIDI_particle.cc
References numberOfParticles, particleSortedList, and printf().
int MCGIDI_particle_release (statusMessageReporting * smr, MCGIDI_particle * particle)
Definition at line 62 of file MCGIDI_particle.cc.
View newest version in sPHENIX GitHub at line 62 of file MCGIDI_particle.cc
References MCGIDI_particle_s::name, and smr_freeMemory().
Referenced by MCGIDI_particle_free().
MCGIDI_POP* MCGIDI_POP_free (MCGIDI_POP * pop)
Definition at line 191 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 191 of file MCGIDI_pop.cc
References MCGIDI_POP_release(), and smr_freeMemory().
Referenced by MCGIDI_POPs_release().
double MCGIDI_POP_getMass_MeV (MCGIDI_POP * pop)
Definition at line 212 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 212 of file MCGIDI_pop.cc
References MCGIDI_POP_s::mass_MeV.
Referenced by MCGIDI_product_getMass_MeV(), MCGIDI_target_heated_getProjectileMass_MeV(), and MCGIDI_target_heated_getTargetMass_MeV().
MCGIDI_POP* MCGIDI_POP_new (statusMessageReporting * smr, char const * name, double mass_MeV, double level_MeV, MCGIDI_POP * parent)
Definition at line 165 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 165 of file MCGIDI_pop.cc
References A(), MCGIDI_POP_s::A, MCGIDI_POP_s::gammas, MCGIDI_POP_s::level, MCGIDI_POP_s::level_MeV, m, MCGIDI_POP_s::m, MCGIDI_POP_s::mass_MeV, MCGIDI_miscNameToZAm(), MCGIDI_POP_s::name, MCGIDI_POP_s::next, MCGIDI_POP_s::numberOfGammaBranchs, MCGIDI_POP_s::parent, smr_allocateCopyString2, smr_freeMemory(), smr_malloc2, Z, and MCGIDI_POP_s::Z.
Referenced by MCGIDI_POPs_addParticleIfNeeded().
MCGIDI_POP* MCGIDI_POP_release (MCGIDI_POP * pop)
Definition at line 201 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 201 of file MCGIDI_pop.cc
References MCGIDI_POP_s::gammas, MCGIDI_POP_s::name, MCGIDI_POP_s::numberOfGammaBranchs, and smr_freeMemory().
Referenced by MCGIDI_POP_free().
MCGIDI_POP* MCGIDI_POPs_addParticleIfNeeded (statusMessageReporting * smr, MCGIDI_POPs * pops, char const * name, double mass_MeV, double level_MeV, MCGIDI_POP * parent, int globalParticle)
Definition at line 67 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 67 of file MCGIDI_pop.cc
References MCGIDI_POPs_s::first, MCGIDI_POP_s::globalPoPsIndex, MCGIDI_POPs_s::increment, MCGIDI_POPs_s::last, lPoPs_addParticleIfNeeded(), MCGIDI_POP_new(), MCGIDI_POPs_findParticleIndex(), MCGIDI_POP_s::next, MCGIDI_POPs_s::numberOfPOPs, MCGIDI_POPs_s::size, smr_freeMemory(), smr_malloc2, and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_target_heated_parseParticle(), and MCGIDI_target_heated_parseParticleLevel().
MCGIDI_POP* MCGIDI_POPs_findParticle (MCGIDI_POPs * pops, char const * name)
Definition at line 133 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 133 of file MCGIDI_pop.cc
References MCGIDI_POPs_findParticleIndex(), and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_particle_getInternalID(), MCGIDI_product_parseFromTOM(), MCGIDI_target_heated_parseParticleGammas(), and MCGIDI_target_heated_read().
int MCGIDI_POPs_findParticleIndex (MCGIDI_POPs * pops, char const * name)
Definition at line 104 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 104 of file MCGIDI_pop.cc
References max, min, MCGIDI_POP_s::name, MCGIDI_POPs_s::numberOfPOPs, and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_POPs_addParticleIfNeeded(), and MCGIDI_POPs_findParticle().
void* MCGIDI_POPs_free (MCGIDI_POPs * pops)
Definition at line 41 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 41 of file MCGIDI_pop.cc
References MCGIDI_POPs_release(), and smr_freeMemory().
int MCGIDI_POPs_initial (statusMessageReporting * smr, MCGIDI_POPs * pops, int size)
Definition at line 30 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 30 of file MCGIDI_pop.cc
References MCGIDI_POPs_s::increment.
Referenced by MCGIDI_POPs_new(), MCGIDI_POPs_release(), and MCGIDI_target_heated_initialize().
MCGIDI_POPs* MCGIDI_POPs_new (statusMessageReporting * smr, int size)
Definition at line 19 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 19 of file MCGIDI_pop.cc
References MCGIDI_POPs_initial(), smr_freeMemory(), and smr_malloc2.
void MCGIDI_POPs_printSortedList (MCGIDI_POPs * pops)
Definition at line 153 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 153 of file MCGIDI_pop.cc
References MCGIDI_POPs_writeSortedList().
int MCGIDI_POPs_release (MCGIDI_POPs * pops)
Definition at line 51 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 51 of file MCGIDI_pop.cc
References MCGIDI_POPs_s::first, MCGIDI_POP_free(), MCGIDI_POPs_initial(), MCGIDI_POP_s::next, smr_freeMemory(), and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_POPs_free(), and MCGIDI_target_heated_release().
void MCGIDI_POPs_writeSortedList (MCGIDI_POPs * pops, FILE * f)
Definition at line 143 of file MCGIDI_pop.cc.
View newest version in sPHENIX GitHub at line 143 of file MCGIDI_pop.cc
References MCGIDI_POP_s::mass_MeV, MCGIDI_POP_s::name, MCGIDI_POPs_s::numberOfPOPs, and MCGIDI_POPs_s::sorted.
Referenced by MCGIDI_POPs_printSortedList().
MCGIDI_product* MCGIDI_product_free (statusMessageReporting * smr, MCGIDI_product * product)
Definition at line 51 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 51 of file MCGIDI_product.cc
References MCGIDI_product_release(), and smr_freeMemory().
Referenced by MCGIDI_product_new().
int MCGIDI_product_getDomain (statusMessageReporting * smr, MCGIDI_product * product, double * EMin, double * EMax)
Definition at line 282 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 282 of file MCGIDI_product.cc
References MCGIDI_outputChannel_getDomain(), and MCGIDI_product_s::outputChannel.
Referenced by MCGIDI_outputChannel_getDomain(), and MCGIDI_product_parsePolynomialMultiplicity().
double MCGIDI_product_getMass_MeV (statusMessageReporting * smr, MCGIDI_product * product)
Definition at line 297 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 297 of file MCGIDI_product.cc
References MCGIDI_POP_getMass_MeV(), and MCGIDI_product_s::pop.
Referenced by MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_outputChannel_sampleProductsAtE().
double MCGIDI_product_getProjectileMass_MeV (statusMessageReporting * smr, MCGIDI_product * product)
Definition at line 311 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 311 of file MCGIDI_product.cc
References MCGIDI_outputChannel_getProjectileMass_MeV(), and MCGIDI_product_s::outputChannel.
Referenced by MCGIDI_energy_parseFromTOM(), and MCGIDI_outputChannel_getProjectileMass_MeV().
MCGIDI_target_heated* MCGIDI_product_getTargetHeated (statusMessageReporting * smr, MCGIDI_product * product)
Definition at line 304 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 304 of file MCGIDI_product.cc
References MCGIDI_outputChannel_getTargetHeated(), and MCGIDI_product_s::outputChannel.
Referenced by MCGIDI_KalbachMann_parseFromTOM(), and MCGIDI_outputChannel_getTargetHeated().
double MCGIDI_product_getTargetMass_MeV (statusMessageReporting * smr, MCGIDI_product * product)
Definition at line 318 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 318 of file MCGIDI_product.cc
References MCGIDI_outputChannel_getTargetMass_MeV(), and MCGIDI_product_s::outputChannel.
Referenced by MCGIDI_energy_parseFromTOM(), and MCGIDI_outputChannel_getTargetMass_MeV().
int MCGIDI_product_initialize (statusMessageReporting * smr, MCGIDI_product * product)
Definition at line 42 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 42 of file MCGIDI_product.cc
References MCGIDI_product_s::delayedNeutronIndex.
Referenced by MCGIDI_product_new(), MCGIDI_product_parseFromTOM(), and MCGIDI_product_release().
MCGIDI_product* MCGIDI_product_new (statusMessageReporting * smr)
Definition at line 31 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_product.cc
References MCGIDI_product_free(), MCGIDI_product_initialize(), and smr_malloc2.
int MCGIDI_product_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_outputChannel * outputChannel, MCGIDI_POPs * pops, MCGIDI_product * product, int * delayedNeutronIndex)
Definition at line 82 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 82 of file MCGIDI_product.cc
References MCGIDI_product_s::decayChannel, MCGIDI_product_s::delayedNeutronIndex, MCGIDI_product_s::delayedNeutronRate, e, check_license::err(), MCGIDI_product_s::label, MCGIDI_distribution_parseFromTOM(), MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf(), MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_POPs_findParticle(), MCGIDI_product_initialize(), MCGIDI_product_parsePiecewiseMultiplicity(), MCGIDI_product_parsePolynomialMultiplicity(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), MCGIDI_product_release(), MCGIDI_product_s::multiplicity, MCGIDI_product_s::multiplicityVsEnergy, MCGIDI_POP_s::name, nfu_Okay, nfu_statusMessage(), MCGIDI_product_s::norms, MCGIDI_product_s::outputChannel, MCGIDI_product_s::pop, ptwXY_free(), ptwXY_getYMax(), ptwXY_getYMin(), ptwXY_interpolationLinLin, ptwXY_length(), ptwXY_new(), ptwXY_simpleCoalescePoints(), smr_allocateCopyString2, smr_setReportError2, smr_setReportError2p, smr_unknownID, xDataTOM_getAttributesValueInElement(), xDataTOME_convertAttributeToInteger(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_outputChannel_parseFromTOM().
int MCGIDI_product_release (statusMessageReporting * smr, MCGIDI_product * product)
Definition at line 60 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 60 of file MCGIDI_product.cc
References MCGIDI_product_s::decayChannel, MCGIDI_product_s::distribution, MCGIDI_product_s::label, MCGIDI_distribution_release(), MCGIDI_outputChannel_release(), MCGIDI_product_initialize(), MCGIDI_product_s::multiplicityVsEnergy, MCGIDI_product_s::norms, MCGIDI_product_s::numberOfPiecewiseMultiplicities, MCGIDI_product_s::piecewiseMultiplicities, ptwXY_free(), and smr_freeMemory().
Referenced by MCGIDI_outputChannel_release(), MCGIDI_product_free(), and MCGIDI_product_parseFromTOM().
int MCGIDI_product_sampleMu (statusMessageReporting * smr, MCGIDI_product * product, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 348 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 348 of file MCGIDI_product.cc
References MCGIDI_distribution_s::angular, MCGIDI_product_s::distribution, MCGIDI_angular_sampleMu(), MCGIDI_distributionType_angular_e, smr_setReportError2, smr_unknownID, and MCGIDI_distribution_s::type.
Referenced by G4GIDI_target::getElasticFinalState().
int MCGIDI_product_sampleMultiplicity (statusMessageReporting * smr, MCGIDI_product * product, double e_in, double r)
Definition at line 325 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 325 of file MCGIDI_product.cc
References int(), MCGIDI_sampling_ptwXY_getValueAtX(), MCGIDI_product_s::multiplicityVsEnergy, norm, MCGIDI_product_s::norms, MCGIDI_product_s::numberOfPiecewiseMultiplicities, MCGIDI_product_s::piecewiseMultiplicities, ptwXY_getXMax(), and y.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
int MCGIDI_product_setTwoBodyMasses (statusMessageReporting * smr, MCGIDI_product * product, double projectileMass_MeV, double targetMass_MeV, double productMass_MeV, double residualMass_MeV)
Definition at line 289 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 289 of file MCGIDI_product.cc
References MCGIDI_distribution_s::angular, MCGIDI_product_s::distribution, and MCGIDI_angular_setTwoBodyMasses().
Referenced by MCGIDI_outputChannel_parseFromTOM().
int MCGIDI_productsInfo_getIntegerMultiplicityAtIndex (MCGIDI_productsInfo * productsInfo, int index)
Definition at line 550 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 550 of file MCGIDI_reaction.cc
References MCGIDI_productInfo_s::multiplicity, MCGIDI_productsInfo_s::numberOfProducts, and MCGIDI_productsInfo_s::productInfo.
enum MCGIDI_productMultiplicityType MCGIDI_productsInfo_getMultiplicityTypeAtIndex (MCGIDI_productsInfo * productsInfo, int index)
Definition at line 542 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 542 of file MCGIDI_reaction.cc
References MCGIDI_productMultiplicityType_invalid_e, MCGIDI_productsInfo_s::numberOfProducts, MCGIDI_productsInfo_s::productInfo, and MCGIDI_productInfo_s::productMultiplicityType.
int MCGIDI_productsInfo_getNumberOfUniqueProducts (MCGIDI_productsInfo * productsInfo)
Definition at line 527 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 527 of file MCGIDI_reaction.cc
References MCGIDI_productsInfo_s::numberOfProducts.
int MCGIDI_productsInfo_getPoPsIndexAtIndex (MCGIDI_productsInfo * productsInfo, int index)
Definition at line 534 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 534 of file MCGIDI_reaction.cc
References MCGIDI_productInfo_s::globalPoPsIndex, MCGIDI_productsInfo_s::numberOfProducts, and MCGIDI_productsInfo_s::productInfo.
int MCGIDI_productsInfo_getTransportableAtIndex (MCGIDI_productsInfo * productsInfo, int index)
Definition at line 558 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 558 of file MCGIDI_reaction.cc
References MCGIDI_productsInfo_s::numberOfProducts, MCGIDI_productsInfo_s::productInfo, and MCGIDI_productInfo_s::transportable.
int MCGIDI_reaction_fixDomains (statusMessageReporting * smr, MCGIDI_reaction * reaction, double EMin, double EMax, nfu_status * status)
Definition at line 366 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 366 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::crossSection, e, MCGIDI_reaction_s::EMax, MCGIDI_reaction_s::EMin, nfu_Okay, and ptwXY_dullEdges().
Referenced by MCGIDI_target_heated_read().
MCGIDI_reaction* MCGIDI_reaction_free (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 60 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 60 of file MCGIDI_reaction.cc
References MCGIDI_reaction_release(), and smr_freeMemory().
Referenced by MCGIDI_reaction_new().
double MCGIDI_reaction_getCrossSectionAtE (statusMessageReporting * smr, MCGIDI_reaction * reaction, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 380 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 380 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::crossSection, MCGIDI_reaction_s::crossSectionGrouped, MCGIDI_reaction_s::EMax, MCGIDI_reaction_s::EMin, MCGIDI_quantitiesLookupModes::getCrossSectionMode(), MCGIDI_quantitiesLookupModes::getGroupIndex(), MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_quantityLookupMode_grouped, MCGIDI_quantityLookupMode_pointwise, ptwX_getPointAtIndex(), ptwXY_getValueAtX(), smr_setReportError2, smr_unknownID, MCGIDI_reaction_s::thresholdGroupedDeltaCrossSection, and MCGIDI_reaction_s::thresholdGroupIndex.
Referenced by MCGIDI_target_heated_getIndexReactionCrossSectionAtE().
int MCGIDI_reaction_getDomain (statusMessageReporting * smr, MCGIDI_reaction * reaction, double * EMin, double * EMax)
Definition at line 350 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 350 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::domainValuesPresent, MCGIDI_reaction_s::EMax, and MCGIDI_reaction_s::EMin.
Referenced by MCGIDI_outputChannel_getDomain(), and MCGIDI_target_heated_read().
int MCGIDI_reaction_getENDF_MTNumber (MCGIDI_reaction * reaction)
Definition at line 415 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 415 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::ENDF_MT.
Referenced by G4GIDI_target::init(), MCGIDI_reaction_ParseReactionTypeAndDetermineProducts(), and MCGIDI_reaction_setENDL_CSNumbers().
int MCGIDI_reaction_getENDL_CSNumbers (MCGIDI_reaction * reaction, int * S)
Definition at line 422 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 422 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::ENDL_C, and MCGIDI_reaction_s::ENDL_S.
double MCGIDI_reaction_getFinalQ (statusMessageReporting * smr, MCGIDI_reaction * reaction, MCGIDI_quantitiesLookupModes & modes)
Definition at line 408 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 408 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::finalQ.
Referenced by MCGIDI_target_heated_getIndexReactionFinalQ().
MCGIDI_productsInfo* MCGIDI_reaction_getProductsInfo (MCGIDI_reaction * reaction)
Definition at line 489 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 489 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::productsInfo.
double MCGIDI_reaction_getProjectileMass_MeV (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 336 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 336 of file MCGIDI_reaction.cc
References MCGIDI_target_heated_getProjectileMass_MeV(), and MCGIDI_reaction_s::target.
Referenced by MCGIDI_outputChannel_getProjectileMass_MeV(), MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_outputChannel_sampleProductsAtE().
enum MCGIDI_reactionType MCGIDI_reaction_getReactionType (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 322 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 322 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::reactionType.
Referenced by MCGIDI_target_getReactionTypeAtIndex().
MCGIDI_target_heated* MCGIDI_reaction_getTargetHeated (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 329 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 329 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::target.
Referenced by MCGIDI_outputChannel_getTargetHeated().
double MCGIDI_reaction_getTargetMass_MeV (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 343 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 343 of file MCGIDI_reaction.cc
References MCGIDI_target_heated_getTargetMass_MeV(), and MCGIDI_reaction_s::target.
Referenced by MCGIDI_outputChannel_getTargetMass_MeV(), MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_outputChannel_sampleProductsAtE().
int MCGIDI_reaction_initialize (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 42 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 42 of file MCGIDI_reaction.cc
References MCGIDI_reaction_initialize2(), and MCGIDI_reaction_s::transportabilities.
Referenced by MCGIDI_reaction_new(), and MCGIDI_reaction_parseFromTOM().
MCGIDI_reaction* MCGIDI_reaction_new (statusMessageReporting * smr)
Definition at line 31 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_reaction.cc
References MCGIDI_reaction_free(), MCGIDI_reaction_initialize(), and smr_malloc2.
int MCGIDI_reaction_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_target_heated * target, MCGIDI_POPs * pops, MCGIDI_reaction * reaction)
Definition at line 84 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 84 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::attributes, MCGIDI_reaction_s::crossSection, MCGIDI_reaction_s::domainValuesPresent, MCGIDI_reaction_s::EMax, MCGIDI_reaction_s::EMin, MCGIDI_reaction_s::ENDF_MT, check_license::err(), MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_reaction_initialize(), MCGIDI_reaction_ParseReactionTypeAndDetermineProducts(), MCGIDI_reaction_release(), MCGIDI_reactionType_unknown_e, MCGIDI_reaction_s::outputChannel, MCGIDI_reaction_s::outputChannelStr, ptwXY_getXMax(), ptwXY_getXMin(), MCGIDI_reaction_s::reactionType, smr_allocateCopyString2, smr_setReportError2, smr_unknownID, MCGIDI_reaction_s::target, xDataTOM_getAttributesValueInElement(), xDataTOM_interpolationFlag_linear, xDataTOME_convertAttributeToInteger(), xDataTOME_copyAttributionList(), xDataTOME_getInterpolation(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_target_heated_parseReaction().
int MCGIDI_reaction_recast (statusMessageReporting * smr, MCGIDI_reaction * reaction, GIDI_settings & settings, GIDI_settings_particle const * projectileSettings, double temperature_MeV, ptwXPoints * totalGroupedCrossSection)
Definition at line 496 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 496 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::crossSection, MCGIDI_reaction_s::crossSectionGrouped, MCGIDI_reaction_s::EMin, GIDI_settings_particle::getGroup(), GIDI_settings_particle::groupFunction(), nfu_Okay, ptwX_add_ptwX(), ptwX_free(), ptwX_getPointAtIndex(), MCGIDI_reaction_s::thresholdGroupDomain, MCGIDI_reaction_s::thresholdGroupedDeltaCrossSection, and MCGIDI_reaction_s::thresholdGroupIndex.
Referenced by MCGIDI_target_heated_recast().
int MCGIDI_reaction_release (statusMessageReporting * smr, MCGIDI_reaction * reaction)
Definition at line 69 of file MCGIDI_reaction.cc.
View newest version in sPHENIX GitHub at line 69 of file MCGIDI_reaction.cc
References MCGIDI_reaction_s::attributes, MCGIDI_reaction_s::crossSection, MCGIDI_reaction_s::crossSectionGrouped, MCGIDI_outputChannel_release(), MCGIDI_reaction_initialize2(), MCGIDI_reaction_s::outputChannel, MCGIDI_reaction_s::outputChannelStr, MCGIDI_productsInfo_s::productInfo, MCGIDI_reaction_s::productsInfo, ptwX_free(), ptwXY_free(), smr_freeMemory(), MCGIDI_reaction_s::transportabilities, and xDataTOMAL_release().
Referenced by MCGIDI_reaction_free(), MCGIDI_reaction_parseFromTOM(), and MCGIDI_target_heated_release().
int MCGIDI_sampledProducts_addProduct (statusMessageReporting * smr, MCGIDI_sampledProductsDatas * sampledProductsDatas, MCGIDI_sampledProductsData * sampledProductsData)
Definition at line 398 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 398 of file MCGIDI_product.cc
References MCGIDI_sampledProducts_remalloc(), MCGIDI_sampledProductsDatas_s::numberAllocated, MCGIDI_sampledProductsDatas_s::numberOfProducts, and MCGIDI_sampledProductsDatas_s::products.
Referenced by MCGIDI_outputChannel_sampleProductsAtE(), and MCGIDI_target_sampleNullReactionProductsAtE().
MCGIDI_sampledProductsData* MCGIDI_sampledProducts_getProductAtIndex (MCGIDI_sampledProductsDatas * sampledProductsDatas, int index)
Definition at line 417 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 417 of file MCGIDI_product.cc
References MCGIDI_sampledProductsDatas_s::numberOfProducts, and MCGIDI_sampledProductsDatas_s::products.
int MCGIDI_sampledProducts_initialize (statusMessageReporting * smr, MCGIDI_sampledProductsDatas * sampledProductsDatas, int incrementSize)
Definition at line 362 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 362 of file MCGIDI_product.cc
References MCGIDI_sampledProductsDatas_s::incrementSize, MCGIDI_sampledProducts_remalloc(), MCGIDI_sampledProductsDatas_s::numberAllocated, MCGIDI_sampledProductsDatas_s::numberOfProducts, and MCGIDI_sampledProductsDatas_s::products.
Referenced by G4GIDI_target::getFinalState().
int MCGIDI_sampledProducts_number (MCGIDI_sampledProductsDatas * sampledProductsDatas)
Definition at line 410 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 410 of file MCGIDI_product.cc
References MCGIDI_sampledProductsDatas_s::numberOfProducts.
int MCGIDI_sampledProducts_release (statusMessageReporting * smr, MCGIDI_sampledProductsDatas * sampledProductsDatas)
Definition at line 374 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 374 of file MCGIDI_product.cc
References MCGIDI_sampledProductsDatas_s::products, and smr_freeMemory().
Referenced by G4GIDI_target::getFinalState().
int MCGIDI_sampledProducts_remalloc (statusMessageReporting * smr, MCGIDI_sampledProductsDatas * sampledProductsDatas)
Definition at line 382 of file MCGIDI_product.cc.
View newest version in sPHENIX GitHub at line 382 of file MCGIDI_product.cc
References MCGIDI_sampledProductsDatas_s::incrementSize, MCGIDI_sampledProductsDatas_s::numberAllocated, MCGIDI_sampledProductsDatas_s::numberOfProducts, MCGIDI_sampledProductsDatas_s::products, and smr_realloc2.
Referenced by MCGIDI_sampledProducts_addProduct(), and MCGIDI_sampledProducts_initialize().
int MCGIDI_sampling_doubleDistribution (statusMessageReporting * smr, MCGIDI_pdfsOfXGivenW * pdfOfWGivenV, MCGIDI_pdfsOfXGivenW * pdfOfXGivenVAndW, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 141 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 141 of file MCGIDI_sampling.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, MCGIDI_misc_binarySearch(), MCGIDI_sampling_interpolationValues(), MCGIDI_sampling_sampleX_from_pdfOfX(), MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_pdfsOfXGivenW_s::numberOfWs, ptwXY_interpolationFlat, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_pdfsOfXGivenW_sampled_s::smr, w, MCGIDI_pdfsOfXGivenW_sampled_s::w, MCGIDI_pdfsOfXGivenW_s::Ws, x, and MCGIDI_pdfsOfXGivenW_sampled_s::x.
Referenced by MCGIDI_angularEnergy_sampleDistribution(), and MCGIDI_energyAngular_sampleDistribution().
int MCGIDI_sampling_interpolationValues (statusMessageReporting * smr, ptwXY_interpolation interpolation, double * ws, double y1, double y2, double * y)
Definition at line 187 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 187 of file MCGIDI_sampling.cc
References G4Log(), G4Pow::GetInstance(), G4Pow::powA(), ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, smr_setReportError2, and smr_unknownID.
Referenced by MCGIDI_sampling_doubleDistribution().
int MCGIDI_sampling_pdfsOfX_release (statusMessageReporting * smr, MCGIDI_pdfOfX * dist)
Definition at line 41 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 41 of file MCGIDI_sampling.cc
References smr_freeMemory(), and MCGIDI_pdfOfX_s::Xs.
Referenced by MCGIDI_energy_release(), and MCGIDI_sampling_pdfsOfXGivenW_release().
int MCGIDI_sampling_pdfsOfXGivenW_initialize (statusMessageReporting * smr, MCGIDI_pdfsOfXGivenW * dists)
Definition at line 20 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_sampling.cc
Referenced by MCGIDI_sampling_pdfsOfXGivenW_release().
int MCGIDI_sampling_pdfsOfXGivenW_release (statusMessageReporting * smr, MCGIDI_pdfsOfXGivenW * dists)
Definition at line 28 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 28 of file MCGIDI_sampling.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_sampling_pdfsOfX_release(), MCGIDI_sampling_pdfsOfXGivenW_initialize(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, smr_freeMemory(), and MCGIDI_pdfsOfXGivenW_s::Ws.
Referenced by MCGIDI_angular_release(), MCGIDI_angularEnergy_release(), MCGIDI_energy_release(), MCGIDI_energyAngular_release(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
double MCGIDI_sampling_ptwXY_getValueAtX (ptwXYPoints * ptwXY, double x1)
Definition at line 212 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 212 of file MCGIDI_sampling.cc
References nfu_XOutsideDomain, ptwXY_getValueAtX(), ptwXY_getXMax(), ptwXY_getXMin(), and y1.
Referenced by MCGIDI_energy_sampleEnergy(), MCGIDI_energy_sampleWeightedFunctional(), and MCGIDI_product_sampleMultiplicity().
int MCGIDI_sampling_sampleX_from_pdfOfX (MCGIDI_pdfOfX * dist, MCGIDI_pdfsOfXGivenW_sampled * sampled, double r)
Definition at line 98 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 98 of file MCGIDI_sampling.cc
References MCGIDI_pdfOfX_s::cdf, d1, d2, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, iX, MCGIDI_pdfsOfXGivenW_sampled_s::iX1, MCGIDI_misc_binarySearch(), MCGIDI_pdfOfX_s::numberOfXs, MCGIDI_pdfOfX_s::pdf, ptwXY_interpolationFlat, s1, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_setReportError2, smr_unknownID, MCGIDI_pdfsOfXGivenW_sampled_s::x, and MCGIDI_pdfOfX_s::Xs.
Referenced by MCGIDI_energy_sampleEnergy(), MCGIDI_sampling_doubleDistribution(), and MCGIDI_sampling_sampleX_from_pdfsOfXGivenW().
int MCGIDI_sampling_sampleX_from_pdfsOfXGivenW (MCGIDI_pdfsOfXGivenW * dists, MCGIDI_pdfsOfXGivenW_sampled * sampled, double r)
Definition at line 49 of file MCGIDI_sampling.cc.
View newest version in sPHENIX GitHub at line 49 of file MCGIDI_sampling.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_pdfsOfXGivenW_sampled_s::frac, G4Log(), G4Pow::GetInstance(), MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, MCGIDI_pdfsOfXGivenW_sampled_s::interpolationXY, MCGIDI_pdfsOfXGivenW_sampled_s::iW, MCGIDI_pdfsOfXGivenW_sampled_s::iX1, MCGIDI_pdfsOfXGivenW_sampled_s::iX2, MCGIDI_misc_binarySearch(), MCGIDI_sampling_sampleX_from_pdfOfX(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, G4Pow::powA(), ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_setReportError2, smr_unknownID, MCGIDI_pdfsOfXGivenW_sampled_s::w, MCGIDI_pdfsOfXGivenW_s::Ws, and MCGIDI_pdfsOfXGivenW_sampled_s::x.
Referenced by MCGIDI_angular_sampleMu(), MCGIDI_energy_sampleEnergy(), MCGIDI_KalbachMann_sampleEp(), and MCGIDI_sampling_doubleDistribution().
MCGIDI_target* MCGIDI_target_free (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 114 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 114 of file MCGIDI_target.cc
References MCGIDI_target_release(), and smr_freeMemory().
Referenced by MCGIDI_target_new(), and G4GIDI_target::~G4GIDI_target().
char const* MCGIDI_target_getAttributesValue (statusMessageReporting * smr, MCGIDI_target * target, char const * name)
Definition at line 245 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 245 of file MCGIDI_target.cc
References MCGIDI_target_s::attributes, and xDataTOMAL_getAttributesValue().
int MCGIDI_target_getDomain (statusMessageReporting * smr, MCGIDI_target * target, double * EMin, double * EMax)
Definition at line 382 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 382 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, MCGIDI_target_heated_getReactionsDomain(), and MCGIDI_target_numberOfReactions().
MCGIDI_target_heated* MCGIDI_target_getHeatedTargetAtIndex_ReadIfNeeded (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 289 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 289 of file MCGIDI_target.cc
References MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_target_readHeatedTarget(), MCGIDI_target_s::nHeatedTargets, smr_setReportError2, and smr_unknownID.
MCGIDI_target_heated* MCGIDI_target_getHeatedTargetAtTIndex (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 301 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 301 of file MCGIDI_target.cc
References MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_target_s::nHeatedTargets, smr_setReportError2, and smr_unknownID.
double MCGIDI_target_getIndexReactionCrossSectionAtE (statusMessageReporting * smr, MCGIDI_target * target, int index, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 402 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 402 of file MCGIDI_target.cc
References MCGIDI_quantitiesLookupModes::getTemperature(), MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_heated_getIndexReactionCrossSectionAtE(), MCGIDI_target_s::nReadHeatedTargets, MCGIDI_target_s::readHeatedTargets, and MCGIDI_target_heated_info_s::temperature.
Referenced by MCGIDI_target_sampleReaction(), G4GIDI_target::sampleChannelCrossSectionAtE(), and G4GIDI_target::sumChannelCrossSectionAtE().
double MCGIDI_target_getIndexReactionFinalQ (statusMessageReporting * smr, MCGIDI_target * target, int index, MCGIDI_quantitiesLookupModes & modes)
Definition at line 493 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 493 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_getIndexReactionFinalQ().
MCGIDI_reaction* MCGIDI_target_getReactionAtIndex (MCGIDI_target * target, int index)
Definition at line 333 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 333 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_getReactionAtIndex().
MCGIDI_reaction* MCGIDI_target_getReactionAtIndex_smr (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 340 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 340 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_getReactionAtIndex_smr().
enum MCGIDI_reactionType MCGIDI_target_getReactionTypeAtIndex (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 323 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 323 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, MCGIDI_reaction_getReactionType(), MCGIDI_reactionType_unknown_e, and MCGIDI_target_heated_getReactionAtIndex_smr().
int MCGIDI_target_getTemperatures (statusMessageReporting * smr, MCGIDI_target * target, double * temperatures)
Definition at line 252 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 252 of file MCGIDI_target.cc
References MCGIDI_target_s::heatedTargets, MCGIDI_target_s::nHeatedTargets, and MCGIDI_target_heated_info_s::temperature.
Referenced by G4GIDI_target::getTemperatures().
double MCGIDI_target_getTotalCrossSectionAtTAndE (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 358 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 358 of file MCGIDI_target.cc
References MCGIDI_quantitiesLookupModes::getTemperature(), MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_heated_getTotalCrossSectionAtE(), MCGIDI_target_s::nReadHeatedTargets, MCGIDI_target_s::readHeatedTargets, and MCGIDI_target_heated_info_s::temperature.
Referenced by G4GIDI_target::getTotalCrossSectionAtE().
transportabilitiesMap const* MCGIDI_target_getUniqueProducts (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 501 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 501 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_getUniqueProducts().
MCGIDI_target_heated* MCGIDI_target_heated_free (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 64 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 64 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_release(), and smr_freeMemory().
Referenced by MCGIDI_target_release().
int MCGIDI_target_heated_getEnergyGrid (statusMessageReporting * smr, MCGIDI_target_heated * target, double ** energyGrid)
double MCGIDI_target_heated_getIndexReactionCrossSectionAtE (statusMessageReporting * smr, MCGIDI_target_heated * target, int index, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 496 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 496 of file MCGIDI_target_heated.cc
References MCGIDI_reaction_getCrossSectionAtE(), and MCGIDI_target_heated_getReactionAtIndex_smr().
Referenced by MCGIDI_target_getIndexReactionCrossSectionAtE().
double MCGIDI_target_heated_getIndexReactionFinalQ (statusMessageReporting * smr, MCGIDI_target_heated * target, int index, MCGIDI_quantitiesLookupModes & modes)
Definition at line 542 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 542 of file MCGIDI_target_heated.cc
References MCGIDI_reaction_getFinalQ(), and MCGIDI_target_heated_getReactionAtIndex_smr().
Referenced by MCGIDI_target_getIndexReactionFinalQ().
MCGIDI_POP* MCGIDI_target_heated_getPOPForProjectile (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 433 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 433 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::projectilePOP.
Referenced by MCGIDI_KalbachMann_parseFromTOM().
MCGIDI_POP* MCGIDI_target_heated_getPOPForTarget (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 440 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 440 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::targetPOP.
Referenced by MCGIDI_KalbachMann_parseFromTOM().
double MCGIDI_target_heated_getProjectileMass_MeV (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 447 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 447 of file MCGIDI_target_heated.cc
References MCGIDI_POP_getMass_MeV(), and MCGIDI_target_heated_s::projectilePOP.
Referenced by MCGIDI_reaction_getProjectileMass_MeV().
MCGIDI_reaction* MCGIDI_target_heated_getReactionAtIndex (MCGIDI_target_heated * target, int index)
Definition at line 401 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 401 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::reactions.
Referenced by G4GIDI_target::getChannelIDs(), G4GIDI_target::init(), MCGIDI_target_getReactionAtIndex(), MCGIDI_target_heated_getReactionAtIndex_smr(), MCGIDI_target_heated_getReactionsDomain(), MCGIDI_target_heated_getReactionsThreshold(), and MCGIDI_target_sampleReaction().
MCGIDI_reaction* MCGIDI_target_heated_getReactionAtIndex_smr (statusMessageReporting * smr, MCGIDI_target_heated * target, int index)
Definition at line 409 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 409 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_getReactionAtIndex(), MCGIDI_POP_s::name, MCGIDI_target_heated_s::projectilePOP, smr_setReportError2, smr_unknownID, and MCGIDI_target_heated_s::targetPOP.
Referenced by G4GIDI_target::getChannelsID(), G4GIDI_target::getElasticFinalState(), MCGIDI_target_getReactionAtIndex_smr(), MCGIDI_target_getReactionTypeAtIndex(), MCGIDI_target_heated_getIndexReactionCrossSectionAtE(), MCGIDI_target_heated_getIndexReactionFinalQ(), and MCGIDI_target_heated_sampleIndexReactionProductsAtE().
int MCGIDI_target_heated_getReactionsDomain (statusMessageReporting * smr, MCGIDI_target_heated * target, int index, double * EMin, double * EMax)
Definition at line 530 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 530 of file MCGIDI_target_heated.cc
References MCGIDI_reaction_s::EMax, MCGIDI_reaction_s::EMin, and MCGIDI_target_heated_getReactionAtIndex().
Referenced by G4GIDI_target::getReactionsDomain(), and MCGIDI_target_getDomain().
double MCGIDI_target_heated_getReactionsThreshold (statusMessageReporting * smr, MCGIDI_target_heated * target, int index)
Definition at line 520 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 520 of file MCGIDI_target_heated.cc
References MCGIDI_reaction_s::EMin, and MCGIDI_target_heated_getReactionAtIndex().
Referenced by G4GIDI_target::getReactionsThreshold().
double MCGIDI_target_heated_getTargetMass_MeV (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 454 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 454 of file MCGIDI_target_heated.cc
References MCGIDI_POP_getMass_MeV(), and MCGIDI_target_heated_s::targetPOP.
Referenced by MCGIDI_reaction_getTargetMass_MeV().
double MCGIDI_target_heated_getTotalCrossSectionAtE (statusMessageReporting * smr, MCGIDI_target_heated * target, MCGIDI_quantitiesLookupModes & modes, bool sampling)
Definition at line 461 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 461 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::crossSection, MCGIDI_target_heated_s::crossSectionGrouped, MCGIDI_target_heated_s::crossSectionGroupedForSampling, MCGIDI_target_heated_s::EMax, MCGIDI_target_heated_s::EMin, MCGIDI_quantitiesLookupModes::getCrossSectionMode(), MCGIDI_quantitiesLookupModes::getGroupIndex(), MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_quantityLookupMode_grouped, MCGIDI_quantityLookupMode_pointwise, ptwX_getPointAtIndex(), ptwX_length(), ptwXY_getValueAtX(), smr_setReportError2, and smr_unknownID.
Referenced by MCGIDI_target_getTotalCrossSectionAtTAndE().
transportabilitiesMap const* MCGIDI_target_heated_getUniqueProducts (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 553 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 553 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::transportabilities.
Referenced by MCGIDI_target_getUniqueProducts().
int MCGIDI_target_heated_initialize (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 43 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 43 of file MCGIDI_target_heated.cc
References MCGIDI_POPs_initial(), MCGIDI_target_heated_s::pops, and MCGIDI_target_heated_s::transportabilities.
Referenced by MCGIDI_target_heated_new().
MCGIDI_target_heated* MCGIDI_target_heated_new (statusMessageReporting * smr)
Definition at line 32 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 32 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_initialize(), smr_freeMemory(), and smr_malloc2.
Referenced by MCGIDI_target_heated_newRead().
MCGIDI_target_heated* MCGIDI_target_heated_newRead (statusMessageReporting * smr, const char * fileName)
Definition at line 53 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 53 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_new(), MCGIDI_target_heated_read(), and smr_freeMemory().
Referenced by MCGIDI_target_readHeatedTarget().
int MCGIDI_target_heated_numberOfProductionReactions (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 394 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 394 of file MCGIDI_target_heated.cc
Referenced by MCGIDI_target_numberOfProductionReactions().
int MCGIDI_target_heated_numberOfReactions (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 387 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 387 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::numberOfReactions.
Referenced by MCGIDI_target_numberOfReactions().
int MCGIDI_target_heated_read (statusMessageReporting * smr, MCGIDI_target_heated * target, const char * fileName)
Definition at line 92 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 92 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::absPath, xDataTOM_element_s::attributes, MCGIDI_target_heated_s::attributes, MCGIDI_reaction_s::crossSection, MCGIDI_target_heated_s::crossSection, e, e1, MCGIDI_target_heated_s::EMax, MCGIDI_target_heated_s::EMin, check_license::err(), MCGIDI_misc_getUnitConversionFactor(), MCGIDI_misc_pointerToTOMAttributeIfAllOk3, MCGIDI_misc_updateTransportabilitiesMap(), MCGIDI_POPs_findParticle(), MCGIDI_reaction_fixDomains(), MCGIDI_reaction_getDomain(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_parseReaction(), MCGIDI_target_heated_release(), n, xDataTOM_element_s::name, nfu_statusMessage(), MCGIDI_target_heated_s::numberOfReactions, MCGIDI_target_heated_s::path, MCGIDI_target_heated_s::pops, printf(), MCGIDI_target_heated_s::projectilePOP, ptwXY_add_ptwXY(), ptwXY_create(), ptwXY_free(), ptwXY_interpolationLinLin, MCGIDI_target_heated_s::reactions, smr_allocateCopyString2, smr_isOk(), smr_malloc2, smr_setReportError2, smr_unknownID, MCGIDI_target_heated_s::targetPOP, MCGIDI_target_heated_s::temperature_MeV, MCGIDI_reaction_s::transportabilities, MCGIDI_target_heated_s::transportabilities, xDataTOM_freeTOM(), xDataTOM_getAttributesValueInElement(), xDataTOM_getDocumentsElement(), xDataTOM_importFile(), xDataTOM_numberOfElementsByName(), xDataTOMAL_copyAttributionList(), xDataTOME_getFirstElement(), xDataTOME_getNextElement(), xDataTOME_getOneElementByName(), and xDataTOMMisc_getAbsPath().
Referenced by MCGIDI_target_heated_newRead().
int MCGIDI_target_heated_recast (statusMessageReporting * smr, MCGIDI_target_heated * target, GIDI_settings & settings)
Definition at line 560 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 560 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::crossSectionGrouped, MCGIDI_target_heated_s::crossSectionGroupedForSampling, check_license::err(), GIDI_settings_particle::getNumberOfGroups(), GIDI_settings::getParticle(), MCGIDI_POP_s::globalPoPsIndex, GIDI_settings_particle::isEnergyMode_grouped(), MCGIDI_reaction_recast(), MCGIDI_POP_s::name, nfu_statusMessage(), MCGIDI_target_heated_s::numberOfReactions, MCGIDI_target_heated_s::projectilePOP, ptwX_clone(), ptwX_createLine(), ptwX_free(), ptwX_getPointAtIndex_Unsafely(), ptwX_setPointAtIndex(), MCGIDI_target_heated_s::reactions, smr_setReportError2, smr_unknownID, MCGIDI_target_heated_s::temperature_MeV, MCGIDI_reaction_s::thresholdGroupedDeltaCrossSection, and MCGIDI_reaction_s::thresholdGroupIndex.
Referenced by MCGIDI_target_recast().
int MCGIDI_target_heated_release (statusMessageReporting * smr, MCGIDI_target_heated * target)
Definition at line 73 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 73 of file MCGIDI_target_heated.cc
References MCGIDI_target_heated_s::absPath, MCGIDI_target_heated_s::attributes, MCGIDI_target_heated_s::crossSection, MCGIDI_target_heated_s::crossSectionGrouped, MCGIDI_target_heated_s::crossSectionGroupedForSampling, MCGIDI_POPs_release(), MCGIDI_reaction_release(), MCGIDI_target_heated_s::numberOfReactions, MCGIDI_target_heated_s::path, MCGIDI_target_heated_s::pops, ptwX_free(), ptwXY_free(), MCGIDI_target_heated_s::reactions, smr_freeMemory(), MCGIDI_target_heated_s::transportabilities, and xDataTOMAL_release().
Referenced by MCGIDI_target_heated_free(), and MCGIDI_target_heated_read().
int MCGIDI_target_heated_sampleIndexReactionProductsAtE (statusMessageReporting * smr, MCGIDI_target_heated * target, int index, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, MCGIDI_sampledProductsDatas * productData)
Definition at line 508 of file MCGIDI_target_heated.cc.
View newest version in sPHENIX GitHub at line 508 of file MCGIDI_target_heated.cc
References MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_target_heated_getReactionAtIndex_smr(), MCGIDI_sampledProductsDatas_s::numberOfProducts, and MCGIDI_reaction_s::outputChannel.
Referenced by G4GIDI_target::getFinalState(), and MCGIDI_target_sampleIndexReactionProductsAtE().
int MCGIDI_target_initialize (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 44 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 44 of file MCGIDI_target.cc
Referenced by MCGIDI_target_new(), MCGIDI_target_read(), and MCGIDI_target_release().
MCGIDI_target* MCGIDI_target_new (statusMessageReporting * smr)
Definition at line 33 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 33 of file MCGIDI_target.cc
References MCGIDI_target_free(), MCGIDI_target_initialize(), and smr_malloc2.
Referenced by MCGIDI_target_newRead().
MCGIDI_target* MCGIDI_target_newRead (statusMessageReporting * smr, const char * fileName)
Definition at line 52 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 52 of file MCGIDI_target.cc
References MCGIDI_target_new(), MCGIDI_target_read(), and smr_freeMemory().
Referenced by G4GIDI_target::init(), MCGIDI_target_newReadFromMap(), and MCGIDI_target_newReadFromMapViaPoPIDs().
MCGIDI_target* MCGIDI_target_newReadFromMap (statusMessageReporting * smr, MCGIDI_map * map, const char * evaluation, const char * projectileName, const char * targetName)
Definition at line 99 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 99 of file MCGIDI_target.cc
References MCGIDI_map_findTarget(), MCGIDI_target_newRead(), and smr_freeMemory().
MCGIDI_target* MCGIDI_target_newReadFromMapViaPoPIDs (statusMessageReporting * smr, MCGIDI_map * map, const char * evaluation, int projectile_PoPID, int target_PoPID)
Definition at line 85 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 85 of file MCGIDI_target.cc
References MCGIDI_map_findTargetViaPoPIDs(), MCGIDI_target_newRead(), and smr_freeMemory().
int MCGIDI_target_numberOfProductionReactions (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 347 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 347 of file MCGIDI_target.cc
References MCGIDI_target_heated_numberOfProductionReactions().
Referenced by G4GIDI_target::getNumberOfProductionChannels().
int MCGIDI_target_numberOfReactions (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 316 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 316 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_numberOfReactions().
Referenced by G4GIDI_target::getChannelIDs(), G4GIDI_target::getNumberOfChannels(), G4GIDI_target::init(), MCGIDI_target_getDomain(), and MCGIDI_target_sampleReaction().
int MCGIDI_target_read (statusMessageReporting * smr, MCGIDI_target * target, const char * fileName)
Definition at line 143 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 143 of file MCGIDI_target.cc
References _MCGIDI_target_releaseAndReturnOne(), MCGIDI_target_s::absPath, MCGIDI_target_s::baseHeatedTarget, MCGIDI_target_heated_info_s::contents, MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_misc_getAbsPath(), MCGIDI_misc_setMessageError_Element(), MCGIDI_target_initialize(), MCGIDI_target_readHeatedTarget(), MCGIDI_target_release(), xDataXML_element_s::name, MCGIDI_target_s::nHeatedTargets, MCGIDI_target_heated_info_s::ordinal, MCGIDI_target_heated_info_s::path, MCGIDI_target_s::path, MCGIDI_target_s::readHeatedTargets, smr_allocateCopyString2, smr_malloc2, smr_setReportError2, smr_setReportError2p, smr_unknownID, MCGIDI_target_heated_info_s::temperature, xDataXML_convertAttributeToDouble(), xDataXML_freeDoc(), xDataXML_getAttributesValueInElement(), xDataXML_getDocumentsElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), and xDataXML_importFile2().
Referenced by MCGIDI_target_newRead(), MCGIDI_target_readFromMap(), and MCGIDI_target_readFromMapViaPoPIDs().
int MCGIDI_target_readFromMap (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_map * map, const char * evaluation, const char * projectileName, const char * targetName)
Definition at line 74 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 74 of file MCGIDI_target.cc
References MCGIDI_map_findTarget(), and MCGIDI_target_read().
int MCGIDI_target_readFromMapViaPoPIDs (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_map * map, const char * evaluation, int projectile_PoPID, int target_PoPID)
Definition at line 63 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 63 of file MCGIDI_target.cc
References MCGIDI_map_findTargetViaPoPIDs(), and MCGIDI_target_read().
int MCGIDI_target_readHeatedTarget (statusMessageReporting * smr, MCGIDI_target * target, int index)
Definition at line 262 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 262 of file MCGIDI_target.cc
References MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_target_heated_newRead(), MCGIDI_target_s::nHeatedTargets, MCGIDI_target_s::nReadHeatedTargets, MCGIDI_target_heated_s::ordinal, MCGIDI_target_heated_info_s::ordinal, MCGIDI_target_heated_info_s::path, MCGIDI_target_heated_s::projectilePOP, MCGIDI_target_s::projectilePOP, MCGIDI_target_s::readHeatedTargets, smr_setReportError2, smr_unknownID, MCGIDI_target_heated_s::targetPOP, MCGIDI_target_s::targetPOP, and MCGIDI_target_heated_info_s::temperature.
Referenced by MCGIDI_target_getHeatedTargetAtIndex_ReadIfNeeded(), MCGIDI_target_read(), and G4GIDI_target::readTemperature().
int MCGIDI_target_recast (statusMessageReporting * smr, MCGIDI_target * target, GIDI_settings & settings)
Definition at line 508 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 508 of file MCGIDI_target.cc
References MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_heated_recast(), MCGIDI_target_s::nReadHeatedTargets, and MCGIDI_target_s::readHeatedTargets.
int MCGIDI_target_release (statusMessageReporting * smr, MCGIDI_target * target)
Definition at line 123 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 123 of file MCGIDI_target.cc
References MCGIDI_target_s::absPath, MCGIDI_target_s::attributes, MCGIDI_target_heated_info_s::contents, MCGIDI_target_heated_info_s::heatedTarget, MCGIDI_target_s::heatedTargets, MCGIDI_target_heated_free(), MCGIDI_target_initialize(), MCGIDI_target_s::nHeatedTargets, MCGIDI_target_heated_info_s::path, MCGIDI_target_s::path, MCGIDI_target_s::readHeatedTargets, smr_freeMemory(), and xDataTOMAL_release().
Referenced by _MCGIDI_target_releaseAndReturnOne(), MCGIDI_target_free(), and MCGIDI_target_read().
int MCGIDI_target_sampleIndexReactionProductsAtE (statusMessageReporting * smr, MCGIDI_target * target, int index, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, MCGIDI_sampledProductsDatas * productData)
Definition at line 485 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 485 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, and MCGIDI_target_heated_sampleIndexReactionProductsAtE().
int MCGIDI_target_sampleNullReactionProductsAtE (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, MCGIDI_sampledProductsDatas * productDatas)
Definition at line 461 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 461 of file MCGIDI_target.cc
References MCGIDI_sampledProductsData_s::birthTimeSec, MCGIDI_sampledProductsData_s::delayedNeutronIndex, MCGIDI_sampledProductsData_s::delayedNeutronRate, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_decaySamplingInfo_s::isVelocity, MCGIDI_sampledProductsData_s::isVelocity, MCGIDI_sampledProductsData_s::kineticEnergy, MCGIDI_POP_s::mass_MeV, MCGIDI_sampledProducts_addProduct(), MCGIDI_speedOfLight_cm_sec, MCGIDI_sampledProductsDatas_s::numberOfProducts, MCGIDI_sampledProductsData_s::pop, MCGIDI_target_s::projectilePOP, MCGIDI_sampledProductsData_s::px_vx, MCGIDI_sampledProductsData_s::py_vy, and MCGIDI_sampledProductsData_s::pz_vz.
int MCGIDI_target_sampleReaction (statusMessageReporting * smr, MCGIDI_target * target, MCGIDI_quantitiesLookupModes & modes, double totalXSec, double(*)(void *) userrng, void * rngState)
Definition at line 426 of file MCGIDI_target.cc.
View newest version in sPHENIX GitHub at line 426 of file MCGIDI_target.cc
References MCGIDI_target_s::baseHeatedTarget, e, MCGIDI_reaction_s::EMin, MCGIDI_quantitiesLookupModes::getCrossSectionMode(), MCGIDI_quantitiesLookupModes::getGroupIndex(), MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_quantitiesLookupModes::getTemperature(), MCGIDI_nullReaction, MCGIDI_quantityLookupMode_grouped, MCGIDI_target_getIndexReactionCrossSectionAtE(), MCGIDI_target_heated_getReactionAtIndex(), MCGIDI_target_numberOfReactions(), smr_setReportError2, smr_unknownID, MCGIDI_reaction_s::thresholdGroupDomain, and MCGIDI_reaction_s::thresholdGroupIndex.
int MCGIDI_uncorrelated_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution, ptwXYPoints * norms, enum MCGIDI_energyType energyType, double gammaEnergy_MeV)
Definition at line 18 of file MCGIDI_uncorrelated.cc.
View newest version in sPHENIX GitHub at line 18 of file MCGIDI_uncorrelated.cc
References check_license::err(), MCGIDI_angular_parseFromTOM(), MCGIDI_distributionType_uncorrelated_e, MCGIDI_energy_parseFromTOM(), MCGIDI_energyType_discreteGamma, MCGIDI_energyType_primaryGamma, MCGIDI_distribution_s::type, and xDataTOME_getOneElementByName().
Referenced by MCGIDI_distribution_parseFromTOM().
int MCGIDI_uncorrelated_sampleDistribution (statusMessageReporting * smr, MCGIDI_distribution * distribution, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 43 of file MCGIDI_uncorrelated.cc.
View newest version in sPHENIX GitHub at line 43 of file MCGIDI_uncorrelated.cc
References MCGIDI_distribution_s::angular, MCGIDI_distribution_s::energy, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_angular_sampleMu(), and MCGIDI_energy_sampleEnergy().
Referenced by MCGIDI_outputChannel_sampleProductsAtE().
char const* MCGIDI_version (void)
Definition at line 13 of file MCGIDI_version.cc.
View newest version in sPHENIX GitHub at line 13 of file MCGIDI_version.cc
References MCGIDI_VERSION_MAJOR, MCGIDI_VERSION_MINOR, MCGIDI_VERSION_PATCHLEVEL, and versionStr.
int MCGIDI_versionMajor (void)
Definition at line 21 of file MCGIDI_version.cc.
View newest version in sPHENIX GitHub at line 21 of file MCGIDI_version.cc
References MCGIDI_VERSION_MAJOR.
int MCGIDI_versionMinor (void)
Definition at line 22 of file MCGIDI_version.cc.
View newest version in sPHENIX GitHub at line 22 of file MCGIDI_version.cc
References MCGIDI_VERSION_MINOR.
int MCGIDI_versionPatchLevel (void)
Definition at line 23 of file MCGIDI_version.cc.
View newest version in sPHENIX GitHub at line 23 of file MCGIDI_version.cc
References MCGIDI_VERSION_PATCHLEVEL.
Variable Documentation
const char * MCGIDI_productGenre_NBody_angular_energy
const char * MCGIDI_productGenre_NBody_pairProduction
const char * MCGIDI_productGenre_twoBody_angular
const char * MCGIDI_productGenre_twoBody_formFactor
const char* MCGIDI_productGenre_unknown