ECCE @ EIC Software: G4tgbMaterialMixtureByWeight Class Reference
G4tgbMaterialMixtureByWeight Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMixtureByWeight.hh>
Public Member Functions
G4tgbMaterialMixtureByWeight ()
G4tgbMaterialMixtureByWeight (G4tgrMaterial *tgr)
~G4tgbMaterialMixtureByWeight ()
G4Material * BuildG4Material ()
Public Member Functions inherited from G4tgbMaterialMixture
G4tgbMaterialMixture ()
virtual ~G4tgbMaterialMixture ()
virtual const G4String & GetComponent (G4int i) const
virtual G4double GetFraction (G4int i) const
G4tgbMaterialMixture & operator= (const G4tgbMaterialMixture &)
Public Member Functions inherited from G4tgbMaterial
G4tgbMaterial ()
virtual ~G4tgbMaterial ()
G4tgbMaterial (G4tgrMaterial *tgr)
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfMaterials () const
G4double GetA () const
G4double GetZ () const
const G4String & GetType () const
G4tgrMaterial * GetTgrMate () const
Additional Inherited Members
Protected Member Functions inherited from G4tgbMaterialMixture
virtual void TransformToFractionsByWeight ()
Protected Attributes inherited from G4tgbMaterial
G4tgrMaterial * theTgrMate
G4Material * theG4Mate
Detailed Description
Definition at line 49 of file G4tgbMaterialMixtureByWeight.hh.
View newest version in sPHENIX GitHub at line 49 of file G4tgbMaterialMixtureByWeight.hh
Constructor & Destructor Documentation
G4tgbMaterialMixtureByWeight::G4tgbMaterialMixtureByWeight ()
Definition at line 43 of file G4tgbMaterialMixtureByWeight.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgbMaterialMixtureByWeight.cc
G4tgbMaterialMixtureByWeight::G4tgbMaterialMixtureByWeight (G4tgrMaterial * tgr)
Definition at line 55 of file G4tgbMaterialMixtureByWeight.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgbMaterialMixtureByWeight.cc
References G4tgbMaterial::theTgrMate.
G4tgbMaterialMixtureByWeight::~G4tgbMaterialMixtureByWeight ()
Definition at line 49 of file G4tgbMaterialMixtureByWeight.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgbMaterialMixtureByWeight.cc
Member Function Documentation
G4Material * G4tgbMaterialMixtureByWeight::BuildG4Material () virtual
Implements G4tgbMaterial.
Definition at line 62 of file G4tgbMaterialMixtureByWeight.cc.
View newest version in sPHENIX GitHub at line 62 of file G4tgbMaterialMixtureByWeight.cc
References G4Material::AddElement(), G4Material::AddMaterial(), cm3, FatalException, G4tgbMaterialMgr::FindOrBuildG4Element(), G4tgbMaterialMgr::FindOrBuildG4Material(), Acts::UnitConstants::g, G4cout, G4endl, G4Exception(), G4tgbMaterialMixture::GetComponent(), G4tgrMaterial::GetDensity(), G4tgbMaterialMixture::GetFraction(), G4tgbMaterialMgr::GetInstance(), G4tgrMaterial::GetName(), G4tgrMaterial::GetNumberOfComponents(), G4tgrMaterial::GetPressure(), G4tgrMaterial::GetState(), G4tgrMaterial::GetTemperature(), G4Material::GetTemperature(), G4tgrMessenger::GetVerboseLevel(), kelvin, and G4tgbMaterial::theTgrMate.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialMixtureByWeight.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbMaterialMixtureByWeight.cc