ECCE @ EIC Software: G4PionPlusField Class Reference
G4PionPlusField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4PionPlusField.hh>
Public Member Functions
G4PionPlusField (G4V3DNucleus *nucleus, G4double coeff=0.042 *CLHEP::fermi)
virtual ~G4PionPlusField ()
virtual G4double GetField (const G4ThreeVector &aPosition)
virtual G4double GetBarrier ()
virtual G4double GetCoeff ()
Public Member Functions inherited from G4VNuclearField
G4VNuclearField (G4V3DNucleus *aNucleus=0)
virtual ~G4VNuclearField ()
void SetNucleus (G4V3DNucleus *aNucleus)
Private Member Functions
G4PionPlusField (const G4PionPlusField &right)
const G4PionPlusField & operator= (const G4PionPlusField &right)
G4bool operator== (const G4PionPlusField &right) const
G4bool operator!= (const G4PionPlusField &right) const
Private Attributes
G4double theCoeff
Additional Inherited Members
Protected Attributes inherited from G4VNuclearField
G4V3DNucleus * theNucleus
const G4double radius
Detailed Description
Definition at line 47 of file G4PionPlusField.hh.
View newest version in sPHENIX GitHub at line 47 of file G4PionPlusField.hh
Constructor & Destructor Documentation
G4PionPlusField::G4PionPlusField (G4V3DNucleus * nucleus, G4double coeff = 0.042*CLHEP::fermi)
Definition at line 49 of file G4PionPlusField.cc.
View newest version in sPHENIX GitHub at line 49 of file G4PionPlusField.cc
References theCoeff.
G4PionPlusField::~G4PionPlusField () virtual
Definition at line 56 of file G4PionPlusField.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PionPlusField.cc
G4PionPlusField::G4PionPlusField (const G4PionPlusField & right) private
Member Function Documentation
G4double G4PionPlusField::GetBarrier () virtual
Implements G4VNuclearField.
Definition at line 79 of file G4PionPlusField.cc.
View newest version in sPHENIX GitHub at line 79 of file G4PionPlusField.cc
References A(), G4V3DNucleus::GetCharge(), G4Pow::GetInstance(), G4V3DNucleus::GetMassNumber(), MeV, G4VNuclearField::theNucleus, Z, and G4Pow::Z13().
Referenced by GetField().
virtual G4double G4PionPlusField::GetCoeff () inline virtual
Reimplemented from G4VNuclearField.
Definition at line 62 of file G4PionPlusField.hh.
View newest version in sPHENIX GitHub at line 62 of file G4PionPlusField.hh
References theCoeff.
G4double G4PionPlusField::GetField (const G4ThreeVector & aPosition) virtual
Implements G4VNuclearField.
Definition at line 59 of file G4PionPlusField.cc.
View newest version in sPHENIX GitHub at line 59 of file G4PionPlusField.cc
References A(), G4InuclSpecialFunctions::bindingEnergy(), GetBarrier(), G4NucleiProperties::GetBindingEnergy(), G4V3DNucleus::GetCharge(), G4VNuclearDensity::GetDensity(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNuclearDensity(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc, CLHEP::Hep3Vector::mag(), source.hepunit::neutron_mass_c2, pi, G4PionPlus::PionPlus(), source.hepunit::proton_mass_c2, G4VNuclearField::radius, theCoeff, G4VNuclearField::theNucleus, and Z.
G4bool G4PionPlusField::operator!= (const G4PionPlusField & right) const private
const G4PionPlusField& G4PionPlusField::operator= (const G4PionPlusField & right) private
G4bool G4PionPlusField::operator== (const G4PionPlusField & right) const private
Member Data Documentation
G4double G4PionPlusField::theCoeff private
Definition at line 65 of file G4PionPlusField.hh.
View newest version in sPHENIX GitHub at line 65 of file G4PionPlusField.hh
Referenced by G4PionPlusField(), GetCoeff(), and GetField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4PionPlusField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4PionPlusField.cc