ECCE @ EIC Software: G4PhysicalVolumeModel::G4PhysicalVolumeNodeID Class Reference
G4PhysicalVolumeModel::G4PhysicalVolumeNodeID Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PhysicalVolumeModel.hh>
Public Member Functions
G4PhysicalVolumeNodeID (G4VPhysicalVolume *pPV=0, G4int iCopyNo=0, G4int depth=0, const G4Transform3D &transform=G4Transform3D(), G4bool drawn=true)
G4VPhysicalVolume * GetPhysicalVolume () const
G4int GetCopyNo () const
G4int GetNonCulledDepth () const
const G4Transform3D & GetTransform () const
G4bool GetDrawn () const
void SetDrawn (G4bool drawn)
G4bool operator< (const G4PhysicalVolumeNodeID &right) const
Private Attributes
G4VPhysicalVolume * fpPV
G4int fCopyNo
G4int fNonCulledDepth
G4Transform3D fTransform
G4bool fDrawn
Detailed Description
Definition at line 91 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PhysicalVolumeModel.hh
Constructor & Destructor Documentation
G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::G4PhysicalVolumeNodeID (G4VPhysicalVolume * pPV = 0, G4int iCopyNo = 0, G4int depth = 0, const G4Transform3D & transform = G4Transform3D(), G4bool drawn = true) inline
Definition at line 94 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PhysicalVolumeModel.hh
Member Function Documentation
G4int G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetCopyNo () const inline
Definition at line 105 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4PhysicalVolumeModel.hh
References fCopyNo.
Referenced by JA::Insert(), and JA::PrintTree().
G4bool G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetDrawn () const inline
Definition at line 108 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PhysicalVolumeModel.hh
References fDrawn.
G4int G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetNonCulledDepth () const inline
Definition at line 106 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4PhysicalVolumeModel.hh
References fNonCulledDepth.
G4VPhysicalVolume* G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetPhysicalVolume (void) const inline
Definition at line 104 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4PhysicalVolumeModel.hh
References fpPV.
Referenced by JA::Insert(), and JA::PrintTree().
const G4Transform3D& G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::GetTransform () const inline
Definition at line 107 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4PhysicalVolumeModel.hh
References fTransform.
G4bool G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::operator< (const G4PhysicalVolumeNodeID & right) const
Definition at line 965 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 965 of file G4PhysicalVolumeModel.cc
References right.
void G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::SetDrawn (G4bool drawn) inline
Definition at line 109 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4PhysicalVolumeModel.hh
References fDrawn.
Member Data Documentation
G4int G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::fCopyNo private
Definition at line 113 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PhysicalVolumeModel.hh
Referenced by GetCopyNo().
G4bool G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::fDrawn private
Definition at line 116 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4PhysicalVolumeModel.hh
Referenced by GetDrawn(), and SetDrawn().
G4int G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::fNonCulledDepth private
Definition at line 114 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4PhysicalVolumeModel.hh
Referenced by GetNonCulledDepth().
G4VPhysicalVolume* G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::fpPV private
Definition at line 112 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PhysicalVolumeModel.hh
Referenced by GetPhysicalVolume().
G4Transform3D G4PhysicalVolumeModel::G4PhysicalVolumeNodeID::fTransform private
Definition at line 115 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PhysicalVolumeModel.hh
Referenced by GetTransform().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PhysicalVolumeModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4PhysicalVolumeModel.cc