ECCE @ EIC Software: G4ChannelingMaterialData Class Reference
G4ChannelingMaterialData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingMaterialData.hh>
Public Member Functions
G4ChannelingMaterialData (const G4String &)
virtual ~G4ChannelingMaterialData ()
void Print () const
void SetFilename (const G4String &)
void SetFilenameElement (const G4String &, std::string)
G4ChannelingECHARM * GetPot ()
G4ChannelingECHARM * GetEFX ()
G4ChannelingECHARM * GetEFY ()
G4ChannelingECHARM * GetNuD ()
G4ChannelingECHARM * GetElD ()
G4ChannelingECHARM * GetPotEl (std::string name)
G4ChannelingECHARM * GetEFXEl (std::string name)
G4ChannelingECHARM * GetEFYEl (std::string name)
G4ChannelingECHARM * GetNuDEl (std::string name)
G4ChannelingECHARM * GetElDEl (std::string name)
virtual G4bool IsBent ()
virtual G4ThreeVector GetBR (G4ThreeVector &v3)
virtual void SetBR (const G4String &)
virtual void SetBR (G4double)
Public Member Functions inherited from G4VMaterialExtension
G4VMaterialExtension (const G4String &name)
virtual name ~G4VMaterialExtension ()
const std::size_t & GetHash () const
const G4String & GetName () const
Protected Attributes
G4PhysicsVector * fVectorR
G4bool bIsBent
Protected Attributes inherited from G4VMaterialExtension
const G4String & fName
const std::size_t fHash
Private Attributes
G4ChannelingECHARM * fPotential
G4ChannelingECHARM * fElectricFieldX
G4ChannelingECHARM * fElectricFieldY
G4ChannelingECHARM * fNucleiDensity
G4ChannelingECHARM * fElectronDensity
std::unordered_map
< std::string,
G4ChannelingECHARM * > fPotentialElement
std::unordered_map
< std::string,
G4ChannelingECHARM * > fElectricFieldXElement
std::unordered_map
< std::string,
G4ChannelingECHARM * > fElectricFieldYElement
std::unordered_map
< std::string,
G4ChannelingECHARM * > fNucleiDensityElement
std::unordered_map
< std::string,
G4ChannelingECHARM * > fElectronDensityElement
Detailed Description
Definition at line 41 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ChannelingMaterialData.hh
Constructor & Destructor Documentation
G4ChannelingMaterialData::G4ChannelingMaterialData (const G4String & name)
Definition at line 36 of file G4ChannelingMaterialData.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ChannelingMaterialData.cc
G4ChannelingMaterialData::~G4ChannelingMaterialData () virtual
Definition at line 128 of file G4ChannelingMaterialData.cc.
View newest version in sPHENIX GitHub at line 128 of file G4ChannelingMaterialData.cc
Member Function Documentation
virtual G4ThreeVector G4ChannelingMaterialData::GetBR (G4ThreeVector & v3) inline virtual
Definition at line 85 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChannelingMaterialData.hh
References fVectorR, G4PhysicsVector::Value(), and CLHEP::Hep3Vector::z().
Referenced by G4Channeling::PostStepDoIt(), and G4Channeling::UpdateParameters().
G4ChannelingECHARM* G4ChannelingMaterialData::GetEFX () inline
Definition at line 54 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ChannelingMaterialData.hh
References fElectricFieldX.
Referenced by G4Channeling::UpdateParameters().
G4ChannelingECHARM* G4ChannelingMaterialData::GetEFXEl (std::string name) inline
Definition at line 68 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ChannelingMaterialData.hh
References fElectricFieldXElement.
G4ChannelingECHARM* G4ChannelingMaterialData::GetEFY () inline
Definition at line 55 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ChannelingMaterialData.hh
References fElectricFieldY.
Referenced by G4Channeling::UpdateParameters().
G4ChannelingECHARM* G4ChannelingMaterialData::GetEFYEl (std::string name) inline
Definition at line 69 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ChannelingMaterialData.hh
References fElectricFieldYElement.
G4ChannelingECHARM* G4ChannelingMaterialData::GetElD () inline
Definition at line 57 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ChannelingMaterialData.hh
References fElectronDensity.
Referenced by G4Channeling::UpdateParameters().
G4ChannelingECHARM* G4ChannelingMaterialData::GetElDEl (std::string name) inline
Definition at line 71 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ChannelingMaterialData.hh
References fElectronDensityElement.
G4ChannelingECHARM* G4ChannelingMaterialData::GetNuD () inline
Definition at line 56 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ChannelingMaterialData.hh
References fNucleiDensity.
Referenced by G4Channeling::UpdateParameters().
G4ChannelingECHARM* G4ChannelingMaterialData::GetNuDEl (std::string name) inline
Definition at line 70 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ChannelingMaterialData.hh
References fNucleiDensityElement.
G4ChannelingECHARM* G4ChannelingMaterialData::GetPot () inline
Definition at line 53 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ChannelingMaterialData.hh
References fPotential.
Referenced by G4Channeling::UpdateParameters().
G4ChannelingECHARM* G4ChannelingMaterialData::GetPotEl (std::string name) inline
Definition at line 67 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ChannelingMaterialData.hh
References fPotentialElement.
virtual G4bool G4ChannelingMaterialData::IsBent () inline virtual
Definition at line 81 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ChannelingMaterialData.hh
References bIsBent.
Referenced by G4Channeling::PostStepDoIt(), and G4Channeling::UpdateParameters().
void G4ChannelingMaterialData::Print (void) const inline virtual
Implements G4VMaterialExtension.
Definition at line 48 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ChannelingMaterialData.hh
References G4cout, and G4endl.
void G4ChannelingMaterialData::SetBR (const G4String & filename) virtual
Definition at line 102 of file G4ChannelingMaterialData.cc.
View newest version in sPHENIX GitHub at line 102 of file G4ChannelingMaterialData.cc
References bIsBent, DBL_MAX, fVectorR, G4cout, G4endl, CLHEP::meter, CLHEP::millimeter, and G4PhysicsVector::PutValue().
void G4ChannelingMaterialData::SetBR (G4double val) virtual
Definition at line 93 of file G4ChannelingMaterialData.cc.
View newest version in sPHENIX GitHub at line 93 of file G4ChannelingMaterialData.cc
References bIsBent, DBL_MAX, fVectorR, and G4PhysicsVector::PutValue().
void G4ChannelingMaterialData::SetFilename (const G4String & fileName)
Definition at line 48 of file G4ChannelingMaterialData.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ChannelingMaterialData.cc
References CLHEP::eV, fElectricFieldX, fElectricFieldY, fElectronDensity, fNucleiDensity, fPotential, G4cout, G4endl, and CLHEP::m.
void G4ChannelingMaterialData::SetFilenameElement (const G4String & fileName, std::string elementName)
Definition at line 70 of file G4ChannelingMaterialData.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ChannelingMaterialData.cc
References CLHEP::eV, fElectricFieldXElement, fElectricFieldYElement, fElectronDensityElement, fNucleiDensityElement, fPotentialElement, G4cout, G4endl, and CLHEP::m.
Member Data Documentation
G4bool G4ChannelingMaterialData::bIsBent protected
Definition at line 93 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ChannelingMaterialData.hh
Referenced by IsBent(), and SetBR().
G4ChannelingECHARM* G4ChannelingMaterialData::fElectricFieldX private
Definition at line 61 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ChannelingMaterialData.hh
Referenced by GetEFX(), and SetFilename().
std::unordered_map<std::string,G4ChannelingECHARM*> G4ChannelingMaterialData::fElectricFieldXElement private
Definition at line 75 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ChannelingMaterialData.hh
Referenced by GetEFXEl(), and SetFilenameElement().
G4ChannelingECHARM* G4ChannelingMaterialData::fElectricFieldY private
Definition at line 62 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ChannelingMaterialData.hh
Referenced by GetEFY(), and SetFilename().
std::unordered_map<std::string,G4ChannelingECHARM*> G4ChannelingMaterialData::fElectricFieldYElement private
Definition at line 76 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ChannelingMaterialData.hh
Referenced by GetEFYEl(), and SetFilenameElement().
G4ChannelingECHARM* G4ChannelingMaterialData::fElectronDensity private
Definition at line 64 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ChannelingMaterialData.hh
Referenced by GetElD(), and SetFilename().
std::unordered_map<std::string,G4ChannelingECHARM*> G4ChannelingMaterialData::fElectronDensityElement private
Definition at line 78 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ChannelingMaterialData.hh
Referenced by GetElDEl(), and SetFilenameElement().
G4ChannelingECHARM* G4ChannelingMaterialData::fNucleiDensity private
Definition at line 63 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ChannelingMaterialData.hh
Referenced by GetNuD(), and SetFilename().
std::unordered_map<std::string,G4ChannelingECHARM*> G4ChannelingMaterialData::fNucleiDensityElement private
Definition at line 77 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ChannelingMaterialData.hh
Referenced by GetNuDEl(), and SetFilenameElement().
G4ChannelingECHARM* G4ChannelingMaterialData::fPotential private
Definition at line 57 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ChannelingMaterialData.hh
Referenced by GetPot(), and SetFilename().
std::unordered_map<std::string,G4ChannelingECHARM*> G4ChannelingMaterialData::fPotentialElement private
Definition at line 71 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ChannelingMaterialData.hh
Referenced by GetPotEl(), and SetFilenameElement().
G4PhysicsVector* G4ChannelingMaterialData::fVectorR protected
Definition at line 92 of file G4ChannelingMaterialData.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChannelingMaterialData.hh
Referenced by GetBR(), and SetBR().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/include/G4ChannelingMaterialData.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/channeling/src/G4ChannelingMaterialData.cc