ECCE @ EIC Software: G4GeneralPhaseSpaceDecay Class Reference
G4GeneralPhaseSpaceDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4GeneralPhaseSpaceDecay.hh>
Public Member Functions
G4GeneralPhaseSpaceDecay (G4int Verbose=1)
G4GeneralPhaseSpaceDecay (const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="")
G4GeneralPhaseSpaceDecay (const G4String &theParentName, G4double theParentMass, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="")
G4GeneralPhaseSpaceDecay (const G4String &theParentName, G4double theParentMass, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2, const G4String &theDaughterName3, const G4double *masses)
G4GeneralPhaseSpaceDecay (const G4String &theParentName, G4double theParentMass, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2, const G4String &theDaughterName3, const G4String &theDaughterName4, const G4double *masses)
virtual ~G4GeneralPhaseSpaceDecay ()
G4double GetParentMass () const
void SetParentMass (const G4double aParentMass)
virtual G4DecayProducts * DecayIt (G4double mass=0.0)
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Static Public Member Functions
static G4double Pmx (G4double e, G4double p1, G4double p2)
Protected Member Functions
G4DecayProducts * OneBodyDecayIt ()
G4DecayProducts * TwoBodyDecayIt ()
G4DecayProducts * ThreeBodyDecayIt ()
G4DecayProducts * ManyBodyDecayIt ()
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Private Attributes
G4double parentmass
const G4double * theDaughterMasses
Additional Inherited Members
Protected Attributes inherited from G4VDecayChannel
G4String kinematics_name
G4double rbranch
G4int numberOfDaughters
G4String * parent_name
G4String ** daughters_name
G4double rangeMass
G4ThreeVector parent_polarization
G4ParticleTable * particletable
G4int verboseLevel
G4ParticleDefinition * G4MT_parent
G4ParticleDefinition ** G4MT_daughters
G4double G4MT_parent_mass
G4double * G4MT_daughters_mass
G4double * G4MT_daughters_width
G4Mutex daughtersMutex
G4Mutex parentMutex
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 44 of file G4GeneralPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 44 of file G4GeneralPhaseSpaceDecay.hh
Constructor & Destructor Documentation
G4GeneralPhaseSpaceDecay::G4GeneralPhaseSpaceDecay (G4int Verbose = 1)
Definition at line 48 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 48 of file G4GeneralPhaseSpaceDecay.cc
References G4cout, G4endl, and G4VDecayChannel::GetVerboseLevel().
G4GeneralPhaseSpaceDecay::G4GeneralPhaseSpaceDecay (const G4String & theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String & theDaughterName1, const G4String & theDaughterName2 = "", const G4String & theDaughterName3 = "")
Definition at line 55 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 55 of file G4GeneralPhaseSpaceDecay.cc
References G4cout, G4endl, G4VDecayChannel::G4MT_parent, G4ParticleDefinition::GetPDGMass(), G4VDecayChannel::GetVerboseLevel(), and parentmass.
G4GeneralPhaseSpaceDecay::G4GeneralPhaseSpaceDecay (const G4String & theParentName, G4double theParentMass, G4double theBR, G4int theNumberOfDaughters, const G4String & theDaughterName1, const G4String & theDaughterName2 = "", const G4String & theDaughterName3 = "")
Definition at line 81 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 81 of file G4GeneralPhaseSpaceDecay.cc
References G4cout, G4endl, and G4VDecayChannel::GetVerboseLevel().
G4GeneralPhaseSpaceDecay::G4GeneralPhaseSpaceDecay (const G4String & theParentName, G4double theParentMass, G4double theBR, G4int theNumberOfDaughters, const G4String & theDaughterName1, const G4String & theDaughterName2, const G4String & theDaughterName3, const G4double * masses)
Definition at line 100 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 100 of file G4GeneralPhaseSpaceDecay.cc
References G4cout, G4endl, and G4VDecayChannel::GetVerboseLevel().
G4GeneralPhaseSpaceDecay::G4GeneralPhaseSpaceDecay (const G4String & theParentName, G4double theParentMass, G4double theBR, G4int theNumberOfDaughters, const G4String & theDaughterName1, const G4String & theDaughterName2, const G4String & theDaughterName3, const G4String & theDaughterName4, const G4double * masses)
Definition at line 120 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 120 of file G4GeneralPhaseSpaceDecay.cc
References G4cout, G4endl, and G4VDecayChannel::GetVerboseLevel().
G4GeneralPhaseSpaceDecay::~G4GeneralPhaseSpaceDecay () virtual
Definition at line 142 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 142 of file G4GeneralPhaseSpaceDecay.cc
Member Function Documentation
G4DecayProducts * G4GeneralPhaseSpaceDecay::DecayIt (G4double mass = 0.0) virtual
Implements G4VDecayChannel.
Definition at line 146 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 146 of file G4GeneralPhaseSpaceDecay.cc
References G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), G4VDecayChannel::DumpInfo(), G4cout, G4endl, G4VDecayChannel::GetVerboseLevel(), ManyBodyDecayIt(), G4VDecayChannel::numberOfDaughters, OneBodyDecayIt(), G4VDecayChannel::parent_name, ThreeBodyDecayIt(), and TwoBodyDecayIt().
Referenced by G4KineticTrack::Decay().
G4double G4GeneralPhaseSpaceDecay::GetParentMass () const inline
Definition at line 107 of file G4GeneralPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 107 of file G4GeneralPhaseSpaceDecay.hh
References parentmass.
G4DecayProducts * G4GeneralPhaseSpaceDecay::ManyBodyDecayIt () protected
Definition at line 381 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 381 of file G4GeneralPhaseSpaceDecay.cc
References CLHEP::HepLorentzVector::boost(), G4VDecayChannel::daughters_name, G4DecayProducts::DumpInfo(), G4cout, G4endl, G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4DynamicParticle::Get4Momentum(), G4ParticleDefinition::GetPDGMass(), G4VDecayChannel::GetVerboseLevel(), GeV, Acts::index1, Acts::index2, G4VDecayChannel::numberOfDaughters, G4VDecayChannel::parent_name, parentmass, phi, Pmx(), G4DecayProducts::PushProducts(), rad, G4DynamicParticle::Set4Momentum(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4InuclParticleNames::sm, twopi, weight, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DecayIt().
G4DecayProducts * G4GeneralPhaseSpaceDecay::OneBodyDecayIt () protected
Definition at line 182 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 182 of file G4GeneralPhaseSpaceDecay.cc
References G4DecayProducts::DumpInfo(), G4cout, G4endl, G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4VDecayChannel::GetVerboseLevel(), and G4DecayProducts::PushProducts().
Referenced by DecayIt().
G4double G4GeneralPhaseSpaceDecay::Pmx (G4double e, G4double p1, G4double p2) inline static
Definition at line 120 of file G4GeneralPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 120 of file G4GeneralPhaseSpaceDecay.hh
References e.
Referenced by ManyBodyDecayIt(), and TwoBodyDecayIt().
void G4GeneralPhaseSpaceDecay::SetParentMass (const G4double aParentMass) inline
Definition at line 112 of file G4GeneralPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 112 of file G4GeneralPhaseSpaceDecay.hh
References parentmass.
G4DecayProducts * G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt () protected
Definition at line 259 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 259 of file G4GeneralPhaseSpaceDecay.cc
References G4DecayProducts::DumpInfo(), energy, FatalException, G4cout, G4endl, G4Exception(), G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4ParticleDefinition::GetPDGMass(), G4VDecayChannel::GetVerboseLevel(), GeV, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), mom, parentmass, phi, G4DecayProducts::PushProducts(), rad, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), theDaughterMasses, and twopi.
Referenced by DecayIt().
G4DecayProducts * G4GeneralPhaseSpaceDecay::TwoBodyDecayIt () protected
Definition at line 209 of file G4GeneralPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 209 of file G4GeneralPhaseSpaceDecay.cc
References G4DecayProducts::DumpInfo(), G4cout, G4endl, G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4ParticleDefinition::GetPDGMass(), G4VDecayChannel::GetVerboseLevel(), parentmass, phi, Pmx(), G4DecayProducts::PushProducts(), rad, theDaughterMasses, and twopi.
Referenced by DecayIt().
Member Data Documentation
G4double G4GeneralPhaseSpaceDecay::parentmass private
Definition at line 100 of file G4GeneralPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 100 of file G4GeneralPhaseSpaceDecay.hh
Referenced by G4GeneralPhaseSpaceDecay(), GetParentMass(), ManyBodyDecayIt(), SetParentMass(), ThreeBodyDecayIt(), and TwoBodyDecayIt().
const G4double* G4GeneralPhaseSpaceDecay::theDaughterMasses private
Definition at line 101 of file G4GeneralPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 101 of file G4GeneralPhaseSpaceDecay.hh
Referenced by ThreeBodyDecayIt(), and TwoBodyDecayIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4GeneralPhaseSpaceDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4GeneralPhaseSpaceDecay.cc