ECCE @ EIC Software: G4MPIhistoMerger Class Reference
G4MPIhistoMerger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/include/G4MPIhistoMerger.hh>
Public Member Functions
G4MPIhistoMerger ()
G4MPIhistoMerger (G4VAnalysisManager *mgr, G4int destination=G4MPImanager::kRANK_MASTER, G4int verbosity=0)
void SetDestinationRank (G4int i)
void SetScoringManager (G4VAnalysisManager *mgr)
void SetVerbosity (G4int ver)
void Merge ()
Private Attributes
G4VAnalysisManager * manager
G4int destination
G4int verboseLevel
Detailed Description
Definition at line 38 of file G4MPIhistoMerger.hh.
View newest version in sPHENIX GitHub at line 38 of file G4MPIhistoMerger.hh
Constructor & Destructor Documentation
G4MPIhistoMerger::G4MPIhistoMerger ()
Definition at line 38 of file G4MPIhistoMerger.cc.
View newest version in sPHENIX GitHub at line 38 of file G4MPIhistoMerger.cc
G4MPIhistoMerger::G4MPIhistoMerger (G4VAnalysisManager * mgr, G4int destination = G4MPImanager::kRANK_MASTER, G4int verbosity = 0)
Definition at line 42 of file G4MPIhistoMerger.cc.
View newest version in sPHENIX GitHub at line 42 of file G4MPIhistoMerger.cc
Member Function Documentation
void G4MPIhistoMerger::Merge ()
Definition at line 45 of file G4MPIhistoMerger.cc.
View newest version in sPHENIX GitHub at line 45 of file G4MPIhistoMerger.cc
References destination, G4cout, G4endl, G4MPImanager::GetComm(), G4MPImanager::GetManager(), G4MPImanager::kTAG_HISTO, manager, G4VAnalysisManager::Merge(), and verboseLevel.
Referenced by RunActionMaster::EndOfRunAction().
void G4MPIhistoMerger::SetDestinationRank (G4int i) inline
Definition at line 46 of file G4MPIhistoMerger.hh.
View newest version in sPHENIX GitHub at line 46 of file G4MPIhistoMerger.hh
References destination.
void G4MPIhistoMerger::SetScoringManager (G4VAnalysisManager * mgr) inline
Definition at line 47 of file G4MPIhistoMerger.hh.
View newest version in sPHENIX GitHub at line 47 of file G4MPIhistoMerger.hh
References manager.
void G4MPIhistoMerger::SetVerbosity (G4int ver) inline
Definition at line 48 of file G4MPIhistoMerger.hh.
View newest version in sPHENIX GitHub at line 48 of file G4MPIhistoMerger.hh
References verboseLevel.
Referenced by RunActionMaster::EndOfRunAction().
Member Data Documentation
G4int G4MPIhistoMerger::destination private
Definition at line 54 of file G4MPIhistoMerger.hh.
View newest version in sPHENIX GitHub at line 54 of file G4MPIhistoMerger.hh
Referenced by Merge(), and SetDestinationRank().
G4VAnalysisManager* G4MPIhistoMerger::manager private
Definition at line 53 of file G4MPIhistoMerger.hh.
View newest version in sPHENIX GitHub at line 53 of file G4MPIhistoMerger.hh
Referenced by Merge(), and SetScoringManager().
G4int G4MPIhistoMerger::verboseLevel private
Definition at line 55 of file G4MPIhistoMerger.hh.
View newest version in sPHENIX GitHub at line 55 of file G4MPIhistoMerger.hh
Referenced by Merge(), and SetVerbosity().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/include/G4MPIhistoMerger.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/src/G4MPIhistoMerger.cc