ECCE @ EIC Software: G4TrajectoryDrawByOriginVolume Class Reference
G4TrajectoryDrawByOriginVolume Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByOriginVolume.hh>
Public Member Functions
G4TrajectoryDrawByOriginVolume (const G4String &name="Unspecified", G4VisTrajContext *context=0)
virtual ~G4TrajectoryDrawByOriginVolume ()
virtual void Draw (const G4VTrajectory &trajectory, const G4bool &visible=true) const
virtual void Print (std::ostream &ostr) const
void SetDefault (const G4String &)
void SetDefault (const G4Colour &)
void Set (const G4String &particle, const G4String &colour)
void Set (const G4String &particle, const G4Colour &colour)
Public Member Functions inherited from G4VTrajectoryModel
G4VTrajectoryModel (const G4String &name, G4VisTrajContext *fpContext=0)
virtual ~G4VTrajectoryModel ()
G4String Name () const
const G4VisTrajContext & GetContext () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Private Attributes
G4ModelColourMap< G4String > fMap
G4Colour fDefault
Detailed Description
Definition at line 42 of file G4TrajectoryDrawByOriginVolume.hh.
View newest version in sPHENIX GitHub at line 42 of file G4TrajectoryDrawByOriginVolume.hh
Constructor & Destructor Documentation
G4TrajectoryDrawByOriginVolume::G4TrajectoryDrawByOriginVolume (const G4String & name = "Unspecified", G4VisTrajContext * context = 0)
Definition at line 36 of file G4TrajectoryDrawByOriginVolume.cc.
View newest version in sPHENIX GitHub at line 36 of file G4TrajectoryDrawByOriginVolume.cc
G4TrajectoryDrawByOriginVolume::~G4TrajectoryDrawByOriginVolume () virtual
Definition at line 41 of file G4TrajectoryDrawByOriginVolume.cc.
View newest version in sPHENIX GitHub at line 41 of file G4TrajectoryDrawByOriginVolume.cc
Member Function Documentation
void G4TrajectoryDrawByOriginVolume::Draw (const G4VTrajectory & trajectory, const G4bool & visible = true) const virtual
Implements G4VTrajectoryModel.
Definition at line 44 of file G4TrajectoryDrawByOriginVolume.cc.
View newest version in sPHENIX GitHub at line 44 of file G4TrajectoryDrawByOriginVolume.cc
References G4TrajectoryDrawerUtils::DrawLineAndPoints(), fDefault, fMap, G4cout, G4endl, G4ModelColourMap< T >::GetColour(), G4VTrajectoryModel::GetContext(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4TransportationManager::GetNavigatorForTracking(), G4VTrajectory::GetPoint(), G4VTrajectoryPoint::GetPosition(), G4TransportationManager::GetTransportationManager(), G4VTrajectoryModel::GetVerbose(), G4Navigator::LocateGlobalPointAndSetup(), G4VTrajectoryModel::Name(), Acts::Test::navigator, G4VisTrajContext::Print(), G4VisTrajContext::SetLineColour(), and Acts::Test::volume.
void G4TrajectoryDrawByOriginVolume::Print (std::ostream & ostr) const virtual
Implements G4VTrajectoryModel.
Definition at line 118 of file G4TrajectoryDrawByOriginVolume.cc.
View newest version in sPHENIX GitHub at line 118 of file G4TrajectoryDrawByOriginVolume.cc
References fDefault, fMap, G4VTrajectoryModel::GetContext(), G4VTrajectoryModel::Name(), G4VisTrajContext::Print(), and G4ModelColourMap< T >::Print().
void G4TrajectoryDrawByOriginVolume::Set (const G4String & particle, const G4String & colour)
Definition at line 106 of file G4TrajectoryDrawByOriginVolume.cc.
View newest version in sPHENIX GitHub at line 106 of file G4TrajectoryDrawByOriginVolume.cc
References fMap, and G4ModelColourMap< T >::Set().
void G4TrajectoryDrawByOriginVolume::Set (const G4String & particle, const G4Colour & colour)
Definition at line 112 of file G4TrajectoryDrawByOriginVolume.cc.
View newest version in sPHENIX GitHub at line 112 of file G4TrajectoryDrawByOriginVolume.cc
References fMap, and particle.
void G4TrajectoryDrawByOriginVolume::SetDefault (const G4String & colour)
Definition at line 83 of file G4TrajectoryDrawByOriginVolume.cc.
View newest version in sPHENIX GitHub at line 83 of file G4TrajectoryDrawByOriginVolume.cc
References G4Exception(), G4Colour::GetColour(), and JustWarning.
void G4TrajectoryDrawByOriginVolume::SetDefault (const G4Colour & colour)
Definition at line 100 of file G4TrajectoryDrawByOriginVolume.cc.
View newest version in sPHENIX GitHub at line 100 of file G4TrajectoryDrawByOriginVolume.cc
References fDefault.
Member Data Documentation
G4Colour G4TrajectoryDrawByOriginVolume::fDefault private
Definition at line 68 of file G4TrajectoryDrawByOriginVolume.hh.
View newest version in sPHENIX GitHub at line 68 of file G4TrajectoryDrawByOriginVolume.hh
Referenced by Draw(), Print(), and SetDefault().
G4ModelColourMap<G4String> G4TrajectoryDrawByOriginVolume::fMap private
Definition at line 67 of file G4TrajectoryDrawByOriginVolume.hh.
View newest version in sPHENIX GitHub at line 67 of file G4TrajectoryDrawByOriginVolume.hh
Referenced by Draw(), Print(), and Set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByOriginVolume.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoryDrawByOriginVolume.cc