ECCE @ EIC Software: G4tgrIsotope Class Reference
G4tgrIsotope Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrIsotope.hh>
Public Member Functions
G4tgrIsotope ()
~G4tgrIsotope ()
G4tgrIsotope (const std::vector< G4String > &wl)
const G4String & GetName () const
G4int GetZ () const
G4int GetN () const
G4double GetA () const
Private Attributes
G4String theName
G4int theZ
G4int theN
G4double theA
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrIsotope &obj)
Detailed Description
Definition at line 46 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 46 of file G4tgrIsotope.hh
Constructor & Destructor Documentation
G4tgrIsotope::G4tgrIsotope ()
Definition at line 43 of file G4tgrIsotope.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgrIsotope.cc
G4tgrIsotope::~G4tgrIsotope ()
Definition at line 50 of file G4tgrIsotope.cc.
View newest version in sPHENIX GitHub at line 50 of file G4tgrIsotope.cc
G4tgrIsotope::G4tgrIsotope (const std::vector< G4String > & wl)
Definition at line 56 of file G4tgrIsotope.cc.
View newest version in sPHENIX GitHub at line 56 of file G4tgrIsotope.cc
References G4tgrUtils::CheckWLsize(), Acts::UnitConstants::g, G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), mole, theA, theN, theName, theZ, and WLSIZE_EQ.
Member Function Documentation
G4double G4tgrIsotope::GetA () const inline
Definition at line 62 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 62 of file G4tgrIsotope.hh
References theA.
Referenced by G4tgbIsotope::BuildG4Isotope().
G4int G4tgrIsotope::GetN () const inline
Definition at line 61 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgrIsotope.hh
References theN.
Referenced by G4tgbIsotope::BuildG4Isotope().
const G4String& G4tgrIsotope::GetName (void) const inline
Definition at line 59 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 59 of file G4tgrIsotope.hh
References theName.
Referenced by G4tgrMaterialFactory::AddIsotope(), G4tgbIsotope::BuildG4Isotope(), and G4tgbIsotope::GetName().
G4int G4tgrIsotope::GetZ () const inline
Definition at line 60 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 60 of file G4tgrIsotope.hh
References theZ.
Referenced by G4tgbIsotope::BuildG4Isotope().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrIsotope & obj) friend
Definition at line 75 of file G4tgrIsotope.cc.
View newest version in sPHENIX GitHub at line 75 of file G4tgrIsotope.cc
Member Data Documentation
G4double G4tgrIsotope::theA private
Definition at line 71 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgrIsotope.hh
Referenced by G4tgrIsotope(), GetA(), and operator<<().
G4int G4tgrIsotope::theN private
Definition at line 70 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 70 of file G4tgrIsotope.hh
Referenced by G4tgrIsotope(), GetN(), and operator<<().
G4String G4tgrIsotope::theName private
Definition at line 68 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 68 of file G4tgrIsotope.hh
Referenced by G4tgrIsotope(), GetName(), and operator<<().
G4int G4tgrIsotope::theZ private
Definition at line 69 of file G4tgrIsotope.hh.
View newest version in sPHENIX GitHub at line 69 of file G4tgrIsotope.hh
Referenced by G4tgrIsotope(), GetZ(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrIsotope.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrIsotope.cc