ECCE @ EIC Software: ExErrorMagneticField Class Reference
ExErrorMagneticField Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/errorpropagation/include/ExErrorMagneticField.hh>
Public Member Functions
ExErrorMagneticField (G4ThreeVector)
ExErrorMagneticField ()
void SetFieldValue (G4double fieldValue)
void SetFieldValue (G4ThreeVector fieldVector)
Public Member Functions inherited from G4UniformMagField
G4UniformMagField (const G4ThreeVector &FieldVector)
G4UniformMagField (G4double vField, G4double vTheta, G4double vPhi)
virtual ~G4UniformMagField () override
G4UniformMagField (const G4UniformMagField &p)
G4UniformMagField & operator= (const G4UniformMagField &p)
virtual void GetFieldValue (const G4double yTrack[4], G4double *MagField) const overridefinal
void SetFieldValue (const G4ThreeVector &newFieldValue)
G4ThreeVector GetConstantFieldValue () const
virtual G4Field * Clone () const override
Public Member Functions inherited from G4MagneticField
G4MagneticField ()
virtual ~G4MagneticField ()
G4MagneticField (const G4MagneticField &r)
G4MagneticField & operator= (const G4MagneticField &p)
G4bool DoesFieldChangeEnergy () const
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Protected Member Functions
G4FieldManager * GetGlobalFieldManager ()
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Magnetic field class
A uniform 1 kilogauss field along the Z axis
History: Created: May 2007
Author
P. Arce
Definition at line 47 of file ExErrorMagneticField.hh.
View newest version in sPHENIX GitHub at line 47 of file ExErrorMagneticField.hh
Constructor & Destructor Documentation
ExErrorMagneticField::ExErrorMagneticField (G4ThreeVector fieldVector)
Definition at line 44 of file ExErrorMagneticField.cc.
View newest version in sPHENIX GitHub at line 44 of file ExErrorMagneticField.cc
References G4FieldManager::CreateChordFinder(), GetGlobalFieldManager(), and G4FieldManager::SetDetectorField().
ExErrorMagneticField::ExErrorMagneticField ()
Definition at line 36 of file ExErrorMagneticField.cc.
View newest version in sPHENIX GitHub at line 36 of file ExErrorMagneticField.cc
References G4FieldManager::CreateChordFinder(), GetGlobalFieldManager(), and G4FieldManager::SetDetectorField().
Member Function Documentation
G4FieldManager * ExErrorMagneticField::GetGlobalFieldManager () protected
Definition at line 77 of file ExErrorMagneticField.cc.
View newest version in sPHENIX GitHub at line 77 of file ExErrorMagneticField.cc
References G4TransportationManager::GetFieldManager(), and G4TransportationManager::GetTransportationManager().
Referenced by ExErrorMagneticField(), and SetFieldValue().
void ExErrorMagneticField::SetFieldValue (G4double fieldValue)
Definition at line 52 of file ExErrorMagneticField.cc.
View newest version in sPHENIX GitHub at line 52 of file ExErrorMagneticField.cc
References G4UniformMagField::SetFieldValue().
Referenced by ExErrorDetectorConstruction::SetMagField().
void ExErrorMagneticField::SetFieldValue (G4ThreeVector fieldVector)
Definition at line 59 of file ExErrorMagneticField.cc.
View newest version in sPHENIX GitHub at line 59 of file ExErrorMagneticField.cc
References GetGlobalFieldManager(), G4FieldManager::SetDetectorField(), and G4UniformMagField::SetFieldValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/errorpropagation/include/ExErrorMagneticField.hh
geant4/tree/geant4-10.6-release/examples/extended/errorpropagation/src/ExErrorMagneticField.cc