ECCE @ EIC Software: G4Bessel Class Reference
G4Bessel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4Bessel.hh>
Public Member Functions
G4Bessel ()
~G4Bessel ()
G4double I0 (G4double)
G4double I1 (G4double)
G4double K0 (G4double)
G4double K1 (G4double)
G4double pI0 (G4double)
G4double pI1 (G4double)
G4double pK0 (G4double)
G4double pK1 (G4double)
Detailed Description
Definition at line 66 of file G4Bessel.hh.
View newest version in sPHENIX GitHub at line 66 of file G4Bessel.hh
Constructor & Destructor Documentation
G4Bessel::G4Bessel ()
Definition at line 72 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 72 of file G4Bessel.cc
G4Bessel::~G4Bessel ()
Definition at line 76 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 76 of file G4Bessel.cc
Member Function Documentation
G4double G4Bessel::I0 (G4double x)
Definition at line 80 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 80 of file G4Bessel.cc
References kdfinder::abs(), KF_timing::ax, G4Exp(), G4Pow::GetInstance(), I, P1, P2, G4Pow::powN(), and y.
Referenced by K0().
G4double G4Bessel::I1 (G4double x)
Definition at line 150 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 150 of file G4Bessel.cc
References kdfinder::abs(), KF_timing::ax, G4Exp(), G4Pow::GetInstance(), I, P1, P2, G4Pow::powN(), and y.
Referenced by K1().
G4double G4Bessel::K0 (G4double x)
Definition at line 116 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 116 of file G4Bessel.cc
References G4Exp(), G4Log(), I0(), P1, P2, x, and y.
G4double G4Bessel::K1 (G4double x)
Definition at line 188 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 188 of file G4Bessel.cc
References G4Exp(), G4Log(), I1(), P1, P2, x, and y.
G4double G4Bessel::pI0 (G4double x)
Definition at line 222 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 222 of file G4Bessel.cc
References A10, A11, kdfinder::abs(), E, G4Exp(), I, twopi, x, and y.
Referenced by pK0(), and pK1().
G4double G4Bessel::pI1 (G4double x)
Definition at line 265 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 265 of file G4Bessel.cc
References A10, A11, kdfinder::abs(), G4Exp(), I, twopi, x, and y.
Referenced by pK1().
G4double G4Bessel::pK0 (G4double x)
Definition at line 310 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 310 of file G4Bessel.cc
References C(), G4Log(), pI0(), t, x, and y.
Referenced by pK1().
G4double G4Bessel::pK1 (G4double x)
Definition at line 351 of file G4Bessel.cc.
View newest version in sPHENIX GitHub at line 351 of file G4Bessel.cc
References pI0(), pI1(), and pK0().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4Bessel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4Bessel.cc