ECCE @ EIC Software: G4ReactionProduct Class Reference
G4ReactionProduct Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4ReactionProduct.hh>
Public Member Functions
G4ReactionProduct ()
G4ReactionProduct (const G4ParticleDefinition *aParticleDefinition)
~G4ReactionProduct ()
G4ReactionProduct (const G4ReactionProduct &right)
void * operator new (size_t)
void operator delete (void *aReactionProduct)
G4ReactionProduct & operator= (const G4ReactionProduct &right)
G4ReactionProduct & operator= (const G4DynamicParticle &right)
G4ReactionProduct & operator= (const G4HadProjectile &right)
G4bool operator== (const G4ReactionProduct &right) const
G4bool operator!= (const G4ReactionProduct &right) const
const G4ParticleDefinition * GetDefinition () const
void SetDefinition (const G4ParticleDefinition *aParticleDefinition)
void SetDefinitionAndUpdateE (const G4ParticleDefinition *aParticleDefinition)
void SetMomentum (const G4double x, const G4double y, const G4double z)
void SetMomentum (const G4double x, const G4double y)
void SetMomentum (const G4double z)
void SetMomentum (const G4ThreeVector &mom)
G4ThreeVector GetMomentum () const
G4double GetTotalMomentum () const
G4double GetTotalEnergy () const
void SetKineticEnergy (const G4double en)
G4double GetKineticEnergy () const
void SetTotalEnergy (const G4double en)
void SetMass (const G4double mas)
G4double GetMass () const
void SetTOF (const G4double t)
G4double GetTOF () const
void SetSide (const G4int sid)
G4int GetSide () const
void SetCreatorModel (const G4int mod)
G4int GetCreatorModel () const
void SetNewlyAdded (const G4bool f)
G4bool GetNewlyAdded () const
void SetMayBeKilled (const G4bool f)
G4bool GetMayBeKilled () const
void SetZero ()
void Lorentz (const G4ReactionProduct &p1, const G4ReactionProduct &p2)
G4double Angle (const G4ReactionProduct &p) const
void SetPositionInNucleus (G4double x, G4double y, G4double z)
void SetPositionInNucleus (G4ThreeVector &aPosition)
G4ThreeVector GetPositionInNucleus () const
G4double GetXPositionInNucleus () const
G4double GetYPositionInNucleus () const
G4double GetZPositionInNucleus () const
void SetFormationTime (G4double aTime)
G4double GetFormationTime () const
void HasInitialStateParton (G4bool aFlag)
G4bool HasInitialStateParton () const
Private Attributes
const G4ParticleDefinition * theParticleDefinition
G4ThreeVector positionInNucleus
G4double formationTime
G4bool hasInitialStateParton
G4double mass
G4ThreeVector momentum
G4double totalEnergy
G4double kineticEnergy
G4double timeOfFlight
G4int side
G4int theCreatorModel
G4bool NewlyAdded
G4bool MayBeKilled
Friends
G4ReactionProduct operator+ (const G4ReactionProduct &p1, const G4ReactionProduct &p2)
G4ReactionProduct operator- (const G4ReactionProduct &p1, const G4ReactionProduct &p2)
G4ReactionProduct operator* (const G4double aDouble, const G4ReactionProduct &p2)
Detailed Description
Definition at line 53 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ReactionProduct.hh
Constructor & Destructor Documentation
G4ReactionProduct::G4ReactionProduct ()
Definition at line 39 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 39 of file G4ReactionProduct.cc
References SetMomentum(), and SetPositionInNucleus().
G4ReactionProduct::G4ReactionProduct (const G4ParticleDefinition * aParticleDefinition)
Definition at line 56 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ReactionProduct.cc
References formationTime, G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), hasInitialStateParton, kineticEnergy, mass, MayBeKilled, NewlyAdded, SetMomentum(), SetPositionInNucleus(), side, theCreatorModel, theParticleDefinition, timeOfFlight, and totalEnergy.
G4ReactionProduct::~G4ReactionProduct () inline
Definition at line 77 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ReactionProduct.hh
G4ReactionProduct::G4ReactionProduct (const G4ReactionProduct & right)
Definition at line 74 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ReactionProduct.cc
References formationTime, hasInitialStateParton, kineticEnergy, mass, MayBeKilled, momentum, NewlyAdded, positionInNucleus, side, theCreatorModel, theParticleDefinition, timeOfFlight, and totalEnergy.
Member Function Documentation
G4double G4ReactionProduct::Angle (const G4ReactionProduct & p) const
Definition at line 228 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 228 of file G4ReactionProduct.cc
References a, kdfinder::abs(), momentum, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4int G4ReactionProduct::GetCreatorModel () const inline
Definition at line 168 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ReactionProduct.hh
References theCreatorModel.
const G4ParticleDefinition* G4ReactionProduct::GetDefinition () const inline
Definition at line 107 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ReactionProduct.hh
References theParticleDefinition.
Referenced by G4ParaFissionModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4QGSParticipants::BuildInteractions(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4RPGInelastic::CheckQnums(), G4ParticleHPInelasticCompFS::CompositeApply(), G4QGSParticipants::DeterminePartonMomenta(), G4FissionProductYieldDist::G4GetFission(), G4VSplitableHadron::G4VSplitableHadron(), G4FTFModel::Init(), G4RPGPiMinusInelastic::InitialCollision(), G4RPGPiPlusInelastic::InitialCollision(), G4RPGProtonInelastic::InitialCollision(), G4RPGNeutronInelastic::InitialCollision(), G4FissionProductYieldDist::MakeG4DynamicParticle(), G4RPGInelastic::MarkLeadingStrangeParticle(), G4RPGReaction::NuclearReaction(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4RPGPionSuppression::ReactionStage(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGReaction::Rotate(), G4ParticleHPProduct::Sample(), G4RPGInelastic::SetUpChange(), G4RPGNeutronInelastic::SlowNeutron(), and G4ParticleHPInelasticCompFS::two_body_reaction().
G4double G4ReactionProduct::GetFormationTime () const inline
Definition at line 208 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 208 of file G4ReactionProduct.hh
References formationTime.
G4double G4ReactionProduct::GetKineticEnergy () const inline
Definition at line 138 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ReactionProduct.hh
References kineticEnergy.
Referenced by G4RPGReaction::AddBlackTrackParticles(), G4NRESP71M03::ApplyMechanismABE(), G4RPGProtonInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPFSFissionFS::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4RPGInelastic::CalculateMomenta(), G4ParticleHPInelasticCompFS::CompositeApply(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPFSFissionFS::GetPhotons(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4RPGPiPlusInelastic::InitialCollision(), G4RPGPiMinusInelastic::InitialCollision(), G4RPGNeutronInelastic::InitialCollision(), G4RPGProtonInelastic::InitialCollision(), G4RPGReaction::NuclearReaction(), G4BinaryCascade::ProductsAddFinalState(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4RPGReaction::Rotate(), G4ParticleHPProduct::Sample(), G4ParticleHPAngular::SampleAndUpdate(), SetDefinitionAndUpdateE(), G4RPGInelastic::SetUpChange(), and G4RPGNeutronInelastic::SlowNeutron().
G4double G4ReactionProduct::GetMass () const inline
Definition at line 150 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ReactionProduct.hh
References mass.
Referenced by G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4RPGInelastic::CalculateMomenta(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4ParticleHPInelasticCompFS::CompositeApply(), G4NRESP71M03::DKINMA(), G4Nucleus::GetBiasedThermalNucleus(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPNBodyPhaseSpace::GetEmax(), G4Nucleus::GetThermalNucleus(), G4FTFModel::Init(), G4RPGInelastic::MarkLeadingStrangeParticle(), G4RPGReaction::MomentumCheck(), G4RPGReaction::NuclearReaction(), G4RPGPionSuppression::ReactionStage(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContEnergyAngular::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4GammaParticipants::SelectInteractions(), G4QGSParticipants::SelectInteractions(), SetDefinitionAndUpdateE(), G4RPGInelastic::SetUpChange(), G4RPGNeutronInelastic::SlowNeutron(), and G4ParticleHPInelasticCompFS::two_body_reaction().
G4bool G4ReactionProduct::GetMayBeKilled () const inline
Definition at line 180 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 180 of file G4ReactionProduct.hh
References MayBeKilled.
G4ThreeVector G4ReactionProduct::GetMomentum (void) const inline
Definition at line 123 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ReactionProduct.hh
References momentum.
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4QGSParticipants::BuildInteractions(), G4RPGInelastic::CalculateMomenta(), G4ParticleHPInelasticCompFS::CompositeApply(), G4RPGReaction::Defs1(), G4NRESP71M03::DKINMA(), G4BinaryCascade::FillVoidNucleusProducts(), G4VSplitableHadron::G4VSplitableHadron(), G4Nucleus::GetBiasedThermalNucleus(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4FTFModel::Init(), G4FissionProductYieldDist::MakeG4DynamicParticle(), G4RPGReaction::MomentumCheck(), G4RPGReaction::NuclearReaction(), ReactionProduct4Mom::operator()(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4RPGReaction::Rotate(), G4ParticleHPEnAngCorrelation::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4GammaParticipants::SelectInteractions(), G4QGSParticipants::SelectInteractions(), SetDefinitionAndUpdateE(), G4RPGInelastic::SetUpChange(), and G4RPGNeutronInelastic::SlowNeutron().
G4bool G4ReactionProduct::GetNewlyAdded () const inline
Definition at line 174 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ReactionProduct.hh
References NewlyAdded.
G4ThreeVector G4ReactionProduct::GetPositionInNucleus () const inline
Definition at line 201 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 201 of file G4ReactionProduct.hh
References positionInNucleus.
G4int G4ReactionProduct::GetSide () const inline
Definition at line 162 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ReactionProduct.hh
References side.
Referenced by G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), and G4RPGFragmentation::ReduceEnergiesOfSecondaries().
G4double G4ReactionProduct::GetTOF () const inline
Definition at line 156 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ReactionProduct.hh
References timeOfFlight.
Referenced by G4MuMinusCapturePrecompound::ApplyYourself().
G4double G4ReactionProduct::GetTotalEnergy (void) const inline
Definition at line 129 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ReactionProduct.hh
References totalEnergy.
Referenced by G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4QGSParticipants::BuildInteractions(), G4ParticleHPInelasticCompFS::CompositeApply(), G4NRESP71M03::DKINMA(), G4BinaryCascade::FillVoidNucleusProducts(), G4VSplitableHadron::G4VSplitableHadron(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4ParticleHPPhotonDist::GetPhotons(), G4FTFModel::Init(), ReactionProduct4Mom::operator()(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4RPGPionSuppression::ReactionStage(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4FTFModel::ReggeonCascade(), G4ParticleHPEnAngCorrelation::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
G4double G4ReactionProduct::GetTotalMomentum () const inline
Definition at line 126 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ReactionProduct.hh
References kdfinder::abs(), kineticEnergy, mass, and totalEnergy.
Referenced by G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4RPGInelastic::CalculateMomenta(), G4ParticleHPInelasticCompFS::CompositeApply(), G4BinaryCascade::FillVoidNucleusProducts(), G4ParticleHPDeExGammas::GetDecayGammas(), G4ParticleHPPhotonDist::GetPhotons(), G4RPGReaction::MomentumCheck(), G4RPGReaction::NuclearReaction(), G4RPGPionSuppression::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4FTFModel::ReggeonCascade(), G4RPGReaction::Rotate(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPAngular::SampleAndUpdate(), and G4ParticleHPInelasticCompFS::two_body_reaction().
G4double G4ReactionProduct::GetXPositionInNucleus () const inline
Definition at line 202 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 202 of file G4ReactionProduct.hh
References positionInNucleus, and CLHEP::Hep3Vector::x().
G4double G4ReactionProduct::GetYPositionInNucleus () const inline
Definition at line 203 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 203 of file G4ReactionProduct.hh
References positionInNucleus, and CLHEP::Hep3Vector::y().
G4double G4ReactionProduct::GetZPositionInNucleus () const inline
Definition at line 204 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 204 of file G4ReactionProduct.hh
References positionInNucleus, and CLHEP::Hep3Vector::z().
void G4ReactionProduct::HasInitialStateParton (G4bool aFlag) inline
Definition at line 210 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 210 of file G4ReactionProduct.hh
References hasInitialStateParton.
Referenced by operator+(), and operator-().
G4bool G4ReactionProduct::HasInitialStateParton () const inline
Definition at line 212 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 212 of file G4ReactionProduct.hh
References hasInitialStateParton.
void G4ReactionProduct::Lorentz (const G4ReactionProduct & p1, const G4ReactionProduct & p2)
Definition at line 209 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 209 of file G4ReactionProduct.cc
References a, mass, momentum, SetMass(), SetMomentum(), SetTotalEnergy(), totalEnergy, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPFSFissionFS::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::CompositeApply(), G4NRESP71M03::DKINMA(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4ParticleHPFSFissionFS::GetPhotons(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4RPGReaction::NuclearReaction(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPEnAngCorrelation::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4ParticleHPInelasticCompFS::two_body_reaction(), and G4ParticleHPInelasticCompFS::use_nresp71_model().
void G4ReactionProduct::operator delete (void * aReactionProduct) inline
Definition at line 91 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ReactionProduct.hh
References aRPAllocator().
void* G4ReactionProduct::operator new (size_t) inline
Definition at line 82 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ReactionProduct.hh
References aRPAllocator().
G4bool G4ReactionProduct::operator!= (const G4ReactionProduct & right) const inline
Definition at line 104 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ReactionProduct.hh
G4ReactionProduct & G4ReactionProduct::operator= (const G4ReactionProduct & right)
Definition at line 92 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ReactionProduct.cc
References formationTime, hasInitialStateParton, kineticEnergy, mass, MayBeKilled, momentum, NewlyAdded, positionInNucleus, side, theCreatorModel, theParticleDefinition, timeOfFlight, and totalEnergy.
G4ReactionProduct & G4ReactionProduct::operator= (const G4DynamicParticle & right)
Definition at line 113 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 113 of file G4ReactionProduct.cc
References formationTime, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentum(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), G4DynamicParticle::GetTotalEnergy(), hasInitialStateParton, kineticEnergy, mass, MayBeKilled, momentum, NewlyAdded, SetPositionInNucleus(), side, theCreatorModel, theParticleDefinition, timeOfFlight, and totalEnergy.
G4ReactionProduct & G4ReactionProduct::operator= (const G4HadProjectile & right)
Definition at line 132 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 132 of file G4ReactionProduct.cc
References CLHEP::HepLorentzVector::e(), formationTime, G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), hasInitialStateParton, kineticEnergy, mass, MayBeKilled, momentum, NewlyAdded, SetPositionInNucleus(), side, theCreatorModel, theParticleDefinition, timeOfFlight, totalEnergy, and CLHEP::HepLorentzVector::vect().
G4bool G4ReactionProduct::operator== (const G4ReactionProduct & right) const inline
Definition at line 101 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ReactionProduct.hh
void G4ReactionProduct::SetCreatorModel (const G4int mod) inline
Definition at line 165 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ReactionProduct.hh
References theCreatorModel.
Referenced by G4ExcitationHandler::BreakItUp(), G4BinaryCascade::DecayVoidNucleus(), G4BinaryCascade::DeExcite(), G4BinaryCascade::FillVoidNucleusProducts(), G4BinaryCascade::ProductsAddFinalState(), and G4BinaryCascade::Propagate1H1().
void G4ReactionProduct::SetDefinition (const G4ParticleDefinition * aParticleDefinition)
Definition at line 163 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 163 of file G4ReactionProduct.cc
References G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), kineticEnergy, mass, theParticleDefinition, timeOfFlight, and totalEnergy.
Referenced by G4RPGReaction::AddBlackTrackParticles(), G4NRESP71M03::ApplyMechanismABE(), G4NRESP71M03::ApplyMechanismI_NBeA2A(), G4NRESP71M03::ApplyMechanismII_ACN2A(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPFSFissionFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4ParticleHPInelasticCompFS::CompositeApply(), G4ParticleHPPhotonDist::GetPhotons(), G4RPGPiMinusInelastic::InitialCollision(), G4RPGPiPlusInelastic::InitialCollision(), G4RPGNeutronInelastic::InitialCollision(), G4RPGProtonInelastic::InitialCollision(), G4RPGReaction::NuclearReaction(), G4DecayStrongResonances::Propagate(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), SetDefinitionAndUpdateE(), G4RPGInelastic::SetUpPions(), and G4ParticleHPInelasticCompFS::two_body_reaction().
void G4ReactionProduct::SetDefinitionAndUpdateE (const G4ParticleDefinition * aParticleDefinition)
Definition at line 151 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 151 of file G4ReactionProduct.cc
References DBL_MIN, GetKineticEnergy(), GetMass(), GetMomentum(), CLHEP::Hep3Vector::mag(), G4InuclParticleNames::pp, SetDefinition(), SetKineticEnergy(), and SetMomentum().
Referenced by G4ParticleHPCaptureFS::ApplyYourself(), G4RPGKMinusInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGOmegaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiOmegaMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGLambdaInelastic::Cascade(), G4RPGKZeroInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGSigmaMinusInelastic::Cascade(), G4RPGKPlusInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGAntiKZeroInelastic::Cascade(), G4RPGPionSuppression::ReactionStage(), G4RPGStrangeProduction::ReactionStage(), G4RPGFragmentation::ReactionStage(), and G4RPGInelastic::SetUpChange().
void G4ReactionProduct::SetFormationTime (G4double aTime) inline
Definition at line 206 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 206 of file G4ReactionProduct.hh
References formationTime.
Referenced by G4ExcitationHandler::BreakItUp(), operator+(), and operator-().
void G4ReactionProduct::SetKineticEnergy (const G4double en) inline
Definition at line 132 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ReactionProduct.hh
References kineticEnergy, mass, and totalEnergy.
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ParticleHPFSFissionFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4RPGInelastic::CalculateMomenta(), G4ParticleHPInelasticCompFS::CompositeApply(), G4BinaryCascade::FillVoidNucleusProducts(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4Nucleus::GetThermalNucleus(), G4RPGReaction::NuclearReaction(), G4RPGTwoCluster::ReactionStage(), G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGReaction::Rotate(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPAngular::SampleAndUpdate(), SetDefinitionAndUpdateE(), G4RPGNeutronInelastic::SlowNeutron(), and G4ParticleHPInelasticCompFS::use_nresp71_model().
void G4ReactionProduct::SetMass (const G4double mas) inline
Definition at line 147 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ReactionProduct.hh
References mass.
Referenced by G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4RPGAntiProtonInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiLambdaInelastic::Cascade(), G4RPGAntiNeutronInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4NRESP71M03::DKINMA(), G4Nucleus::GetThermalNucleus(), Lorentz(), G4RPGReaction::NuclearReaction(), operator+(), operator-(), G4DecayStrongResonances::Propagate(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4ParticleHPEnAngCorrelation::Sample(), and G4ParticleHPAngular::SampleAndUpdate().
void G4ReactionProduct::SetMayBeKilled (const G4bool f) inline
Definition at line 177 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 177 of file G4ReactionProduct.hh
References f, and MayBeKilled.
Referenced by G4RPGPiMinusInelastic::InitialCollision(), G4RPGPiPlusInelastic::InitialCollision(), and G4RPGStrangeProduction::ReactionStage().
void G4ReactionProduct::SetMomentum (const G4double x, const G4double y, const G4double z)
Definition at line 174 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 174 of file G4ReactionProduct.cc
References momentum, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
Referenced by G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ExcitationHandler::BreakItUp(), G4RPGInelastic::CalculateMomenta(), G4ParticleHPInelasticCompFS::CompositeApply(), G4BinaryCascade::DecayVoidNucleus(), G4BinaryCascade::DeExcite(), G4RPGReaction::Defs1(), G4NRESP71M03::DKINMA(), G4BinaryCascade::FillVoidNucleusProducts(), G4FissionProductYieldDist::G4GetFission(), G4ReactionProduct(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4ParticleHPDeExGammas::GetDecayGammas(), G4ParticleHPPhotonDist::GetPhotons(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4Nucleus::GetThermalNucleus(), G4BinaryCascade::HighEnergyModelFSProducts(), Lorentz(), G4RPGReaction::MomentumCheck(), G4RPGReaction::NuclearReaction(), operator+(), operator-(), G4BinaryCascade::ProductsAddFinalState(), G4DecayStrongResonances::Propagate(), G4GeneratorPrecompoundInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4RPGReaction::Rotate(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPEnAngCorrelation::Sample(), G4ParticleHPAngular::SampleAndUpdate(), SetDefinitionAndUpdateE(), SetZero(), G4RPGNeutronInelastic::SlowNeutron(), G4ParticleHPInelasticCompFS::two_body_reaction(), and G4ParticleHPInelasticCompFS::use_nresp71_model().
void G4ReactionProduct::SetMomentum (const G4double x, const G4double y)
Definition at line 182 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 182 of file G4ReactionProduct.cc
References momentum, CLHEP::Hep3Vector::setX(), and CLHEP::Hep3Vector::setY().
void G4ReactionProduct::SetMomentum (const G4double z)
Definition at line 189 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 189 of file G4ReactionProduct.cc
References momentum, and CLHEP::Hep3Vector::setZ().
void G4ReactionProduct::SetMomentum (const G4ThreeVector & mom) inline
Definition at line 120 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ReactionProduct.hh
References mom, and momentum.
void G4ReactionProduct::SetNewlyAdded (const G4bool f) inline
Definition at line 171 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 171 of file G4ReactionProduct.hh
References f, and NewlyAdded.
Referenced by G4BinaryCascade::FillVoidNucleusProducts(), G4BinaryCascade::HighEnergyModelFSProducts(), G4BinaryCascade::ProductsAddFinalState(), G4RPGTwoCluster::ReactionStage(), and G4RPGFragmentation::ReactionStage().
void G4ReactionProduct::SetPositionInNucleus (G4double x, G4double y, G4double z) inline
Definition at line 189 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 189 of file G4ReactionProduct.hh
References positionInNucleus, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::Hep3Vector::setZ().
Referenced by G4ReactionProduct(), operator+(), operator-(), operator=(), and SetZero().
void G4ReactionProduct::SetPositionInNucleus (G4ThreeVector & aPosition) inline
Definition at line 196 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 196 of file G4ReactionProduct.hh
References positionInNucleus.
void G4ReactionProduct::SetSide (const G4int sid) inline
Definition at line 159 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ReactionProduct.hh
References side.
Referenced by G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGPiMinusInelastic::InitialCollision(), G4RPGPiPlusInelastic::InitialCollision(), G4RPGNeutronInelastic::InitialCollision(), G4RPGProtonInelastic::InitialCollision(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), and G4RPGInelastic::SetUpPions().
void G4ReactionProduct::SetTOF (const G4double t) inline
Definition at line 153 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ReactionProduct.hh
References t, and timeOfFlight.
Referenced by G4RPGTwoBody::ReactionStage(), and G4RPGTwoCluster::ReactionStage().
void G4ReactionProduct::SetTotalEnergy (const G4double en) inline
Definition at line 141 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ReactionProduct.hh
References kineticEnergy, mass, and totalEnergy.
Referenced by G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ExcitationHandler::BreakItUp(), G4BinaryCascade::DecayVoidNucleus(), G4BinaryCascade::DeExcite(), G4NRESP71M03::DKINMA(), G4BinaryCascade::FillVoidNucleusProducts(), G4ParticleHPPhotonDist::GetPhotons(), G4Nucleus::GetThermalNucleus(), G4BinaryCascade::HighEnergyModelFSProducts(), Lorentz(), G4RPGReaction::MomentumCheck(), G4RPGReaction::NuclearReaction(), operator+(), operator-(), G4BinaryCascade::ProductsAddFinalState(), G4DecayStrongResonances::Propagate(), G4GeneratorPrecompoundInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4ParticleHPEnAngCorrelation::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4RPGNeutronInelastic::SlowNeutron(), and G4ParticleHPInelasticCompFS::two_body_reaction().
void G4ReactionProduct::SetZero ()
Definition at line 194 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 194 of file G4ReactionProduct.cc
References formationTime, hasInitialStateParton, kineticEnergy, mass, NewlyAdded, SetMomentum(), SetPositionInNucleus(), side, theCreatorModel, timeOfFlight, and totalEnergy.
Referenced by G4RPGFragmentation::ReduceEnergiesOfSecondaries().
Friends And Related Function Documentation
G4ReactionProduct operator* (const G4double aDouble, const G4ReactionProduct & p2) friend
Definition at line 61 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ReactionProduct.hh
G4ReactionProduct operator+ (const G4ReactionProduct & p1, const G4ReactionProduct & p2) friend
Definition at line 245 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 245 of file G4ReactionProduct.cc
G4ReactionProduct operator- (const G4ReactionProduct & p1, const G4ReactionProduct & p2) friend
Definition at line 267 of file G4ReactionProduct.cc.
View newest version in sPHENIX GitHub at line 267 of file G4ReactionProduct.cc
Member Data Documentation
G4double G4ReactionProduct::formationTime private
Definition at line 220 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 220 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetFormationTime(), operator=(), SetFormationTime(), and SetZero().
G4bool G4ReactionProduct::hasInitialStateParton private
Definition at line 221 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 221 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), HasInitialStateParton(), operator=(), and SetZero().
G4double G4ReactionProduct::kineticEnergy private
Definition at line 230 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 230 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetKineticEnergy(), GetTotalMomentum(), operator=(), SetDefinition(), SetKineticEnergy(), SetTotalEnergy(), and SetZero().
G4double G4ReactionProduct::mass private
Definition at line 225 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 225 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetMass(), GetTotalMomentum(), Lorentz(), operator=(), SetDefinition(), SetKineticEnergy(), SetMass(), SetTotalEnergy(), and SetZero().
G4bool G4ReactionProduct::MayBeKilled private
Definition at line 243 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 243 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetMayBeKilled(), operator=(), and SetMayBeKilled().
G4ThreeVector G4ReactionProduct::momentum private
Definition at line 227 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 227 of file G4ReactionProduct.hh
Referenced by Angle(), G4ReactionProduct(), GetMomentum(), Lorentz(), operator+(), operator-(), operator=(), and SetMomentum().
G4bool G4ReactionProduct::NewlyAdded private
Definition at line 242 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 242 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetNewlyAdded(), operator=(), SetNewlyAdded(), and SetZero().
G4ThreeVector G4ReactionProduct::positionInNucleus private
Definition at line 219 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 219 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetPositionInNucleus(), GetXPositionInNucleus(), GetYPositionInNucleus(), GetZPositionInNucleus(), operator=(), and SetPositionInNucleus().
G4int G4ReactionProduct::side private
Definition at line 236 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 236 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetSide(), operator=(), SetSide(), and SetZero().
G4int G4ReactionProduct::theCreatorModel private
Definition at line 238 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 238 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetCreatorModel(), operator=(), SetCreatorModel(), and SetZero().
const G4ParticleDefinition* G4ReactionProduct::theParticleDefinition private
Definition at line 216 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 216 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetDefinition(), operator=(), and SetDefinition().
G4double G4ReactionProduct::timeOfFlight private
Definition at line 232 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 232 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetTOF(), operator=(), SetDefinition(), SetTOF(), and SetZero().
G4double G4ReactionProduct::totalEnergy private
Definition at line 229 of file G4ReactionProduct.hh.
View newest version in sPHENIX GitHub at line 229 of file G4ReactionProduct.hh
Referenced by G4ReactionProduct(), GetTotalEnergy(), GetTotalMomentum(), Lorentz(), operator+(), operator-(), operator=(), SetDefinition(), SetKineticEnergy(), SetTotalEnergy(), and SetZero().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4ReactionProduct.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4ReactionProduct.cc