ECCE @ EIC Software: G4RPGReaction Class Reference
G4RPGReaction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGReaction.hh>
Public Member Functions
G4RPGReaction ()
virtual ~G4RPGReaction ()
G4bool ReactionStage (const G4HadProjectile *, G4ReactionProduct &, G4bool &, const G4DynamicParticle *, G4ReactionProduct &, G4bool &, const G4Nucleus &, G4ReactionProduct &, G4FastVector< G4ReactionProduct, 256 > &, G4int &, G4bool, G4ReactionProduct &)
void AddBlackTrackParticles (const G4double, const G4int, const G4double, const G4int, const G4ReactionProduct &, G4int, G4int, const G4Nucleus &, G4FastVector< G4ReactionProduct, 256 > &, G4int &)
G4double GenerateNBodyEvent (const G4double totalEnergy, const G4bool constantCrossSection, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
G4double GenerateNBodyEventT (const G4double totalEnergy, const G4bool constantCrossSection, std::vector< G4ReactionProduct * > &list)
void NuclearReaction (G4FastVector< G4ReactionProduct, 4 > &vec, G4int &vecLen, const G4HadProjectile *originalIncident, const G4Nucleus &aNucleus, const G4double theAtomicMass, const G4double *massVec)
Protected Member Functions
void Rotate (const G4double numberofFinalStateNucleons, const G4ThreeVector &temp, const G4ReactionProduct &modifiedOriginal, const G4HadProjectile *originalIncident, const G4Nucleus &targetNucleus, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
void Defs1 (const G4ReactionProduct &modifiedOriginal, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
std::pair< G4int, G4int > GetFinalStateNucleons (const G4DynamicParticle *originalTarget, const G4FastVector< G4ReactionProduct, 256 > &vec, const G4int &vecLen)
void MomentumCheck (const G4ReactionProduct &modifiedOriginal, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
G4double normal ()
G4ThreeVector Isotropic (const G4double &)
Detailed Description
Definition at line 46 of file G4RPGReaction.hh.
View newest version in sPHENIX GitHub at line 46 of file G4RPGReaction.hh
Constructor & Destructor Documentation
G4RPGReaction::G4RPGReaction () inline
Definition at line 50 of file G4RPGReaction.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RPGReaction.hh
virtual G4RPGReaction::~G4RPGReaction () inline virtual
Definition at line 52 of file G4RPGReaction.hh.
View newest version in sPHENIX GitHub at line 52 of file G4RPGReaction.hh
Member Function Documentation
void G4RPGReaction::AddBlackTrackParticles (const G4double epnb, const G4int npnb, const G4double edta, const G4int ndta, const G4ReactionProduct & modifiedOriginal, G4int PinNucleus, G4int NinNucleus, const G4Nucleus & targetNucleus, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen)
Definition at line 57 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4RPGReaction.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4Exp(), G4UniformRand, G4Nucleus::GetA_asInt(), G4ReactionProduct::GetKineticEnergy(), G4Nucleus::GetZ_asInt(), GeV, max, MeV, min, G4Neutron::Neutron(), phi, G4InuclParticleNames::pp, G4Proton::Proton(), ran(), G4ReactionProduct::SetDefinition(), G4FastVector< Type, N >::SetElement(), G4Triton::Triton(), and twopi.
Referenced by G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), and G4RPGFragmentation::ReactionStage().
void G4RPGReaction::Defs1 (const G4ReactionProduct & modifiedOriginal, G4ReactionProduct & currentParticle, G4ReactionProduct & targetParticle, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen) protected
Definition at line 693 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 693 of file G4RPGReaction.cc
References kdfinder::abs(), G4ReactionProduct::GetMomentum(), halfpi, CLHEP::Hep3Vector::mag(), MeV, G4ReactionProduct::SetMomentum(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4RPGTwoBody::ReactionStage(), and Rotate().
G4double G4RPGReaction::GenerateNBodyEvent (const G4double totalEnergy, const G4bool constantCrossSection, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen)
Definition at line 311 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 311 of file G4RPGReaction.cc
References a, b, c, Acts::Test::cb, energy, G4cerr, G4endl, G4Exp(), G4Log(), G4UniformRand, GeV, mass, max, min, ran(), G4InuclParticleNames::s0, s1, G4InuclParticleNames::sm, twopi, and weight.
Referenced by NuclearReaction(), and G4RPGTwoCluster::ReactionStage().
G4double G4RPGReaction::GenerateNBodyEventT (const G4double totalEnergy, const G4bool constantCrossSection, std::vector< G4ReactionProduct * > & list)
Definition at line 500 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 500 of file G4RPGReaction.cc
References a, b, c, Acts::Test::cb, energy, G4cerr, G4endl, G4Exp(), G4Log(), G4UniformRand, GeV, mass, max, min, ran(), G4InuclParticleNames::s0, s1, G4InuclParticleNames::sm, twopi, and weight.
Referenced by G4RPGFragmentation::ReactionStage().
std::pair< G4int, G4int > G4RPGReaction::GetFinalStateNucleons (const G4DynamicParticle * originalTarget, const G4FastVector< G4ReactionProduct, 256 > & vec, const G4int & vecLen) protected
Definition at line 1011 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 1011 of file G4RPGReaction.cc
References G4DynamicParticle::GetDefinition(), and G4ParticleDefinition::GetParticleName().
Referenced by G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), and G4RPGFragmentation::ReactionStage().
G4ThreeVector G4RPGReaction::Isotropic (const G4double & pp) protected
Definition at line 1043 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 1043 of file G4RPGReaction.cc
References G4UniformRand, phi, and twopi.
Referenced by G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), and G4RPGFragmentation::ReduceEnergiesOfSecondaries().
void G4RPGReaction::MomentumCheck (const G4ReactionProduct & modifiedOriginal, G4ReactionProduct & currentParticle, G4ReactionProduct & targetParticle, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen) protected
Definition at line 1054 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 1054 of file G4RPGReaction.cc
References G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4ReactionProduct::GetTotalMomentum(), CLHEP::Hep3Vector::mag(), MeV, G4ReactionProduct::SetMomentum(), and G4ReactionProduct::SetTotalEnergy().
G4double G4RPGReaction::normal () protected
Definition at line 685 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 685 of file G4RPGReaction.cc
References G4UniformRand, and ran().
Referenced by G4RPGTwoBody::ReactionStage(), G4RPGFragmentation::ReactionStage(), and Rotate().
void G4RPGReaction::NuclearReaction (G4FastVector< G4ReactionProduct, 4 > & vec, G4int & vecLen, const G4HadProjectile * originalIncident, const G4Nucleus & aNucleus, const G4double theAtomicMass, const G4double * massVec)
Definition at line 1094 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 1094 of file G4RPGReaction.cc
References A(), G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4UniformRand, G4Gamma::Gamma(), GenerateNBodyEvent(), G4Nucleus::GetA_asInt(), G4ReactionProduct::GetDefinition(), G4ReactionProduct::GetKineticEnergy(), G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4ParticleDefinition::GetPDGMass(), G4ReactionProduct::GetTotalMomentum(), GeV, G4FastVector< Type, N >::Initialize(), G4ReactionProduct::Lorentz(), CLHEP::Hep3Vector::mag(), max, MeV, min, G4Neutron::Neutron(), G4InuclParticleNames::pp, G4Proton::Proton(), ran(), G4ReactionProduct::SetDefinition(), G4FastVector< Type, N >::SetElement(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), G4Triton::Triton(), twopi, and v.
Referenced by G4RPGNeutronInelastic::SlowNeutron(), and G4RPGProtonInelastic::SlowProton().
G4bool G4RPGReaction::ReactionStage (const G4HadProjectile * , G4ReactionProduct & , G4bool & , const G4DynamicParticle * , G4ReactionProduct & , G4bool & , const G4Nucleus & , G4ReactionProduct & , G4FastVector< G4ReactionProduct, 256 > & , G4int & , G4bool , G4ReactionProduct &)
Definition at line 37 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 37 of file G4RPGReaction.cc
References G4cout, and G4endl.
void G4RPGReaction::Rotate (const G4double numberofFinalStateNucleons, const G4ThreeVector & temp, const G4ReactionProduct & modifiedOriginal, const G4HadProjectile * originalIncident, const G4Nucleus & targetNucleus, G4ReactionProduct & currentParticle, G4ReactionProduct & targetParticle, G4FastVector< G4ReactionProduct, 256 > & vec, G4int & vecLen) protected
Definition at line 749 of file G4RPGReaction.cc.
View newest version in sPHENIX GitHub at line 749 of file G4RPGReaction.cc
References CLHEP::Hep3Vector::cross(), Defs1(), CLHEP::Hep3Vector::dot(), e, G4Exp(), G4Log(), G4UniformRand, G4Nucleus::GetA_asInt(), G4ReactionProduct::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4ReactionProduct::GetKineticEnergy(), G4ReactionProduct::GetMomentum(), G4ParticleDefinition::GetParticleSubType(), G4ReactionProduct::GetTotalMomentum(), GeV, CLHEP::Hep3Vector::mag(), max, MeV, normal(), phi, pi, G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4PionZero::PionZero(), G4InuclParticleNames::pp, r1, r2, CLHEP::Hep3Vector::rotate(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), and twopi.
Referenced by G4RPGTwoCluster::ReactionStage().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGReaction.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/src/G4RPGReaction.cc