ECCE @ EIC Software: G4StatMFParameters Class Reference
G4StatMFParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFParameters.hh>
Public Member Functions
G4StatMFParameters ()
~G4StatMFParameters ()
Static Public Member Functions
static G4double GetKappa ()
static G4double GetKappaCoulomb ()
static G4double GetEpsilon0 ()
static G4double GetE0 ()
static G4double GetBeta0 ()
static G4double GetGamma0 ()
static G4double GetCriticalTemp ()
static G4double Getr0 ()
static G4double GetCoulomb ()
static G4double Beta (G4double T)
static G4double DBetaDT (G4double T)
static G4double GetMaxAverageMultiplicity (G4int A)
Static Public Attributes
static const G4double fKappa = 1.0
static const G4double fKappaCoulomb = 2.0
static const G4double fEpsilon0 = 16.0*MeV
static const G4double fE0 = 16.0*MeV
static const G4double fBeta0 = 18.0*MeV
static const G4double fGamma0 = 25.0*MeV
static const G4double fCriticalTemp = 18.0*MeV
static const G4double fr0 = 1.17*fermi
static const G4double fCoulomb
Detailed Description
Definition at line 36 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 36 of file G4StatMFParameters.hh
Constructor & Destructor Documentation
G4StatMFParameters::G4StatMFParameters ()
Definition at line 58 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 58 of file G4StatMFParameters.cc
G4StatMFParameters::~G4StatMFParameters ()
Definition at line 61 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 61 of file G4StatMFParameters.cc
Member Function Documentation
G4double G4StatMFParameters::Beta (G4double T) static
Definition at line 109 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 109 of file G4StatMFParameters.cc
References fBeta0, fCriticalTemp, T, and tmp.
Referenced by G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroMultiNucleon::CalcEnergy(), G4StatMFFragment::CalcExcitationEnergy(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4StatMFMacroMultiNucleon::CalcMeanMultiplicity(), and G4StatMFMicroPartition::GetPartitionEnergy().
G4double G4StatMFParameters::DBetaDT (G4double T) static
Definition at line 122 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 122 of file G4StatMFParameters.cc
References fBeta0, fCriticalTemp, T, and tmp.
Referenced by G4StatMFMacroMultiNucleon::CalcEnergy(), G4StatMFMacroMultiNucleon::CalcEntropy(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4StatMFFragment::CalcExcitationEnergy(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4StatMFMicroPartition::CalcPartitionProbability(), G4StatMFFragment::GetEnergy(), and G4StatMFMicroPartition::GetPartitionEnergy().
G4double G4StatMFParameters::GetBeta0 () static
Definition at line 84 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 84 of file G4StatMFParameters.cc
References fBeta0.
Referenced by G4StatMFFragment::CalcExcitationEnergy(), G4StatMFFragment::GetEnergy(), G4StatMFMicroCanonical::Initialize(), and G4StatMFMacroCanonical::Initialize().
G4double G4StatMFParameters::GetCoulomb () static
Definition at line 104 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 104 of file G4StatMFParameters.cc
References fCoulomb.
Referenced by G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), G4StatMFMacroTriNucleon::CalcEnergy(), G4StatMFMacroTetraNucleon::CalcEnergy(), G4StatMFMacroNucleon::CalcEnergy(), G4StatMFMacroBiNucleon::CalcEnergy(), G4StatMFMacroMultiNucleon::CalcEnergy(), G4StatMF::CalcEnergy(), G4StatMFMacroNucleon::CalcMeanMultiplicity(), G4StatMFMacroTetraNucleon::CalcMeanMultiplicity(), G4StatMFMacroTriNucleon::CalcMeanMultiplicity(), G4StatMFMacroBiNucleon::CalcMeanMultiplicity(), G4StatMFMacroMultiNucleon::CalcMeanMultiplicity(), G4StatMFMacroMultiNucleon::CalcZARatio(), G4StatMFMacroCanonical::ChooseZ(), G4StatMFMicroPartition::CoulombFreeEnergy(), and G4StatMFFragment::GetCoulombEnergy().
G4double G4StatMFParameters::GetCriticalTemp () static
Definition at line 94 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 94 of file G4StatMFParameters.cc
References fCriticalTemp.
Referenced by G4StatMFFragment::GetEnergy().
G4double G4StatMFParameters::GetE0 () static
Definition at line 79 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 79 of file G4StatMFParameters.cc
References fE0.
Referenced by G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroMultiNucleon::CalcEnergy(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4StatMFMacroMultiNucleon::CalcMeanMultiplicity(), G4StatMFMicroPartition::GetPartitionEnergy(), G4StatMFMicroCanonical::Initialize(), and G4StatMFMacroCanonical::Initialize().
G4double G4StatMFParameters::GetEpsilon0 () static
Definition at line 74 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 74 of file G4StatMFParameters.cc
References fEpsilon0.
Referenced by G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4VStatMFMacroCluster::CalcInvLevelDensity(), G4StatMFMicroCanonical::CalcInvLevelDensity(), G4StatMFFragment::GetInvLevelDensity(), and G4StatMFMicroPartition::InvLevelDensity().
G4double G4StatMFParameters::GetGamma0 () static
Definition at line 89 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 89 of file G4StatMFParameters.cc
References fGamma0.
Referenced by G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), G4StatMFMacroMultiNucleon::CalcEnergy(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4StatMFMacroMultiNucleon::CalcMeanMultiplicity(), G4StatMFMacroMultiNucleon::CalcZARatio(), G4StatMFMicroPartition::ChooseZ(), G4StatMFMacroCanonical::ChooseZ(), G4StatMFMicroPartition::GetPartitionEnergy(), G4StatMFMicroCanonical::Initialize(), and G4StatMFMacroCanonical::Initialize().
G4double G4StatMFParameters::GetKappa () static
Definition at line 64 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 64 of file G4StatMFParameters.cc
References fKappa.
G4double G4StatMFParameters::GetKappaCoulomb () static
Definition at line 69 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 69 of file G4StatMFParameters.cc
References fKappaCoulomb.
Referenced by G4StatMFMacroTemperature::FragsExcitEnergy(), G4StatMFMicroPartition::GetCoulombEnergy(), G4StatMFMicroPartition::GetPartitionEnergy(), and G4StatMFChannel::SolveEqOfMotion().
G4double G4StatMFParameters::GetMaxAverageMultiplicity (G4int A) static
Definition at line 137 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 137 of file G4StatMFParameters.cc
Referenced by G4StatMF::BreakItUp().
G4double G4StatMFParameters::Getr0 () static
Definition at line 99 of file G4StatMFParameters.cc.
View newest version in sPHENIX GitHub at line 99 of file G4StatMFParameters.cc
References fr0.
Referenced by G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4StatMFMacroMultiplicity::CalcMeanA(), G4StatMFMicroPartition::CalcPartitionProbability(), G4StatMFMacroCanonical::CalculateTemperature(), G4StatMFMacroTemperature::FragsExcitEnergy(), G4StatMFMicroPartition::GetCoulombEnergy(), G4StatMFMicroPartition::GetPartitionEnergy(), G4StatMFMicroCanonical::Initialize(), G4StatMFMacroCanonical::Initialize(), G4StatMFChannel::PlaceFragments(), and G4StatMFChannel::SolveEqOfMotion().
Member Data Documentation
const G4double G4StatMFParameters::fBeta0 = 18.0*MeV static
Definition at line 80 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 80 of file G4StatMFParameters.hh
Referenced by Beta(), DBetaDT(), and GetBeta0().
const G4double G4StatMFParameters::fCoulomb static
Initial value:
= 0.6*(CLHEP::elm_coupling/fr0)*
  (1.0 - 1.0/std::pow(1.0+fKappaCoulomb,1./3.))
Definition at line 87 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 87 of file G4StatMFParameters.hh
Referenced by GetCoulomb().
const G4double G4StatMFParameters::fCriticalTemp = 18.0*MeV static
Definition at line 83 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 83 of file G4StatMFParameters.hh
Referenced by Beta(), DBetaDT(), and GetCriticalTemp().
const G4double G4StatMFParameters::fE0 = 16.0*MeV static
Definition at line 79 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 79 of file G4StatMFParameters.hh
Referenced by GetE0().
const G4double G4StatMFParameters::fEpsilon0 = 16.0*MeV static
Definition at line 77 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 77 of file G4StatMFParameters.hh
Referenced by GetEpsilon0().
const G4double G4StatMFParameters::fGamma0 = 25.0*MeV static
Definition at line 81 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 81 of file G4StatMFParameters.hh
Referenced by GetGamma0().
const G4double G4StatMFParameters::fKappa = 1.0 static
Definition at line 73 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 73 of file G4StatMFParameters.hh
Referenced by GetKappa().
const G4double G4StatMFParameters::fKappaCoulomb = 2.0 static
Definition at line 75 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 75 of file G4StatMFParameters.hh
Referenced by GetKappaCoulomb().
const G4double G4StatMFParameters::fr0 = 1.17*fermi static
Definition at line 85 of file G4StatMFParameters.hh.
View newest version in sPHENIX GitHub at line 85 of file G4StatMFParameters.hh
Referenced by Getr0().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFParameters.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFParameters.cc