ECCE @ EIC Software: G4DigiManager Class Reference
G4DigiManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/readout/include/G4DigiManager.hh>
Public Member Functions
~G4DigiManager ()
G4DigiManager (const G4DigiManager &)=delete
G4DigiManager & operator= (const G4DigiManager &)=delete
void AddNewModule (G4VDigitizerModule *DM)
void Digitize (G4String mName)
G4VDigitizerModule * FindDigitizerModule (G4String mName)
const G4VHitsCollection * GetHitsCollection (G4int HCID, G4int eventID=0)
const G4VDigiCollection * GetDigiCollection (G4int DCID, G4int eventID=0)
G4int GetHitsCollectionID (G4String HCname)
G4int GetDigiCollectionID (G4String DCname)
void SetDigiCollection (G4int DCID, G4VDigiCollection *aDC)
void SetVerboseLevel (G4int vl)
void List () const
G4int GetVerboseLevel () const
G4int GetCollectionCapacity () const
G4int GetModuleCapacity () const
G4DCtable * GetDCtable () const
void RestoreDCtable (G4DCtable *dc)
Static Public Member Functions
static G4DigiManager * GetDMpointer ()
static G4DigiManager * GetDMpointerIfExist ()
Protected Member Functions
G4DigiManager ()
Private Attributes
G4int verboseLevel
std::vector< G4VDigitizerModule * > DMtable
G4DCtable * DCtable
G4DMmessenger * theMessenger
G4RunManager * runManager
G4SDManager * SDManager
Static Private Attributes
static G4ThreadLocal
G4DigiManager * fDManager = 0
Detailed Description
Definition at line 52 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 52 of file G4DigiManager.hh
Constructor & Destructor Documentation
G4DigiManager::~G4DigiManager ()
Definition at line 62 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 62 of file G4DigiManager.cc
References DCtable, DMtable, int(), and theMessenger.
G4DigiManager::G4DigiManager (const G4DigiManager &) delete
G4DigiManager::G4DigiManager () protected
Definition at line 54 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 54 of file G4DigiManager.cc
References DCtable, G4RunManager::GetRunManager(), G4SDManager::GetSDMpointer(), runManager, SDManager, and theMessenger.
Referenced by GetDMpointer().
Member Function Documentation
void G4DigiManager::AddNewModule (G4VDigitizerModule * DM)
Definition at line 72 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4DigiManager.cc
References DCtable, DMtable, G4cout, G4endl, G4VDigitizerModule::GetCollectionName(), G4VDigitizerModule::GetName(), G4VDigitizerModule::GetNumberOfCollections(), int(), G4DCtable::Registor(), runManager, G4RunManager::SetDCtable(), and verboseLevel.
Referenced by CexmcEventAction::CexmcEventAction(), and GammaRayTelEventAction::GammaRayTelEventAction().
void G4DigiManager::Digitize (G4String mName)
Definition at line 110 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 110 of file G4DigiManager.cc
References G4VDigitizerModule::Digitize(), FindDigitizerModule(), G4cout, and G4endl.
Referenced by G4DMmessenger::SetNewValue().
G4VDigitizerModule * G4DigiManager::FindDigitizerModule (G4String mName)
Definition at line 119 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 119 of file G4DigiManager.cc
References DMtable, and int().
Referenced by Digitize(), and GammaRayTelEventAction::EndOfEventAction().
G4int G4DigiManager::GetCollectionCapacity () const inline
Definition at line 106 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 106 of file G4DigiManager.hh
References DCtable, and G4DCtable::entries().
G4DCtable* G4DigiManager::GetDCtable () const inline
Definition at line 110 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 110 of file G4DigiManager.hh
References DCtable.
const G4VDigiCollection * G4DigiManager::GetDigiCollection (G4int DCID, G4int eventID = 0)
Definition at line 143 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 143 of file G4DigiManager.cc
References G4RunManager::GetCurrentEvent(), G4DCofThisEvent::GetDC(), G4Event::GetDCofThisEvent(), G4RunManager::GetPreviousEvent(), and runManager.
Referenced by GammaRayTelEventAction::EndOfEventAction().
G4int G4DigiManager::GetDigiCollectionID (G4String DCname)
Definition at line 163 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 163 of file G4DigiManager.cc
References DCtable, G4cout, G4endl, and G4DCtable::GetCollectionID().
Referenced by GammaRayTelDigitizer::Digitize(), GammaRayTelEventAction::EndOfEventAction(), and G4VDigitizerModule::StoreDigiCollection().
G4DigiManager * G4DigiManager::GetDMpointer () static
Definition at line 42 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 42 of file G4DigiManager.cc
References fDManager, and G4DigiManager().
Referenced by CexmcEventAction::CexmcEventAction(), GammaRayTelDigitizer::Digitize(), CexmcTrackPointsDigitizer::Digitize(), CexmcEnergyDepositDigitizer::Digitize(), GammaRayTelEventAction::EndOfEventAction(), CexmcEventAction::EndOfEventAction(), G4VDigitizerModule::G4VDigitizerModule(), and GammaRayTelEventAction::GammaRayTelEventAction().
G4DigiManager * G4DigiManager::GetDMpointerIfExist () static
Definition at line 51 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 51 of file G4DigiManager.cc
References fDManager.
const G4VHitsCollection * G4DigiManager::GetHitsCollection (G4int HCID, G4int eventID = 0)
Definition at line 128 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 128 of file G4DigiManager.cc
References G4RunManager::GetCurrentEvent(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4RunManager::GetPreviousEvent(), and runManager.
Referenced by GammaRayTelDigitizer::Digitize(), CexmcTrackPointsDigitizer::Digitize(), and CexmcEnergyDepositDigitizer::Digitize().
G4int G4DigiManager::GetHitsCollectionID (G4String HCname)
Definition at line 158 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 158 of file G4DigiManager.cc
References G4SDManager::GetCollectionID(), and SDManager.
Referenced by GammaRayTelDigitizer::Digitize(), CexmcTrackPointsDigitizer::Digitize(), and CexmcEnergyDepositDigitizer::Digitize().
G4int G4DigiManager::GetModuleCapacity () const inline
Definition at line 108 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 108 of file G4DigiManager.hh
References DMtable.
G4int G4DigiManager::GetVerboseLevel () const inline
Definition at line 104 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DigiManager.hh
References verboseLevel.
void G4DigiManager::List () const
Definition at line 207 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 207 of file G4DigiManager.cc
References DMtable, G4cout, G4endl, and int().
Referenced by G4DMmessenger::SetNewValue().
G4DigiManager& G4DigiManager::operator= (const G4DigiManager &) delete
void G4DigiManager::RestoreDCtable (G4DCtable * dc) inline
Definition at line 112 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 112 of file G4DigiManager.hh
References DCtable.
void G4DigiManager::SetDigiCollection (G4int DCID, G4VDigiCollection * aDC)
Definition at line 171 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 171 of file G4DigiManager.cc
References G4DCofThisEvent::AddDigiCollection(), DCtable, G4DCtable::entries(), G4cout, G4endl, G4RunManager::GetCurrentEvent(), G4Event::GetDCofThisEvent(), G4VDigiCollection::GetName(), runManager, G4Event::SetDCofThisEvent(), and verboseLevel.
Referenced by G4VDigitizerModule::StoreDigiCollection().
void G4DigiManager::SetVerboseLevel (G4int vl)
Definition at line 200 of file G4DigiManager.cc.
View newest version in sPHENIX GitHub at line 200 of file G4DigiManager.cc
References DMtable, int(), and verboseLevel.
Referenced by G4DMmessenger::SetNewValue().
Member Data Documentation
G4DCtable* G4DigiManager::DCtable private
Definition at line 127 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 127 of file G4DigiManager.hh
Referenced by AddNewModule(), G4DigiManager(), GetCollectionCapacity(), GetDCtable(), GetDigiCollectionID(), RestoreDCtable(), SetDigiCollection(), and ~G4DigiManager().
std::vector<G4VDigitizerModule*> G4DigiManager::DMtable private
Definition at line 126 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 126 of file G4DigiManager.hh
Referenced by AddNewModule(), FindDigitizerModule(), GetModuleCapacity(), List(), SetVerboseLevel(), and ~G4DigiManager().
G4ThreadLocal G4DigiManager * G4DigiManager::fDManager = 0 static private
Definition at line 124 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4DigiManager.hh
Referenced by GetDMpointer(), and GetDMpointerIfExist().
G4RunManager* G4DigiManager::runManager private
Definition at line 129 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 129 of file G4DigiManager.hh
Referenced by AddNewModule(), G4DigiManager(), GetDigiCollection(), GetHitsCollection(), and SetDigiCollection().
G4SDManager* G4DigiManager::SDManager private
Definition at line 130 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 130 of file G4DigiManager.hh
Referenced by G4DigiManager(), and GetHitsCollectionID().
G4DMmessenger* G4DigiManager::theMessenger private
Definition at line 128 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 128 of file G4DigiManager.hh
Referenced by G4DigiManager(), and ~G4DigiManager().
G4int G4DigiManager::verboseLevel private
Definition at line 125 of file G4DigiManager.hh.
View newest version in sPHENIX GitHub at line 125 of file G4DigiManager.hh
Referenced by AddNewModule(), GetVerboseLevel(), SetDigiCollection(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/readout/include/G4DigiManager.hh
geant4/tree/geant4-10.6-release/source/readout/src/G4DigiManager.cc