ECCE @ EIC Software: G4PrimaryTransformer Class Reference
G4PrimaryTransformer Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4PrimaryTransformer.hh>
Public Member Functions
G4PrimaryTransformer ()
virtual ~G4PrimaryTransformer ()
G4TrackVector * GimmePrimaries (G4Event *anEvent, G4int trackIDCounter=0)
void CheckUnknown ()
void SetVerboseLevel (G4int vl)
void SetUnknnownParticleDefined (G4bool vl)
G4bool GetUnknownParticleDefined () const
Protected Member Functions
void GenerateTracks (G4PrimaryVertex *primaryVertex)
void GenerateSingleTrack (G4PrimaryParticle *primaryParticle, G4double x0, G4double y0, G4double z0, G4double t0, G4double wv)
void SetDecayProducts (G4PrimaryParticle *mother, G4DynamicParticle *motherDP)
G4bool CheckDynamicParticle (G4DynamicParticle *DP)
virtual G4ParticleDefinition * GetDefinition (G4PrimaryParticle *pp)
virtual G4bool IsGoodForTrack (G4ParticleDefinition *pd)
Protected Attributes
G4TrackVector TV
G4ParticleTable * particleTable
G4int verboseLevel
G4int trackID
G4ParticleDefinition * unknown
G4bool unknownParticleDefined
G4ParticleDefinition * opticalphoton
G4bool opticalphotonDefined
G4int nWarn
Detailed Description
Definition at line 46 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 46 of file G4PrimaryTransformer.hh
Constructor & Destructor Documentation
G4PrimaryTransformer::G4PrimaryTransformer ()
Definition at line 42 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 42 of file G4PrimaryTransformer.cc
References CheckUnknown(), G4ParticleTable::GetParticleTable(), and particleTable.
G4PrimaryTransformer::~G4PrimaryTransformer () virtual
Definition at line 52 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 52 of file G4PrimaryTransformer.cc
Member Function Documentation
G4bool G4PrimaryTransformer::CheckDynamicParticle (G4DynamicParticle * DP) protected
Definition at line 306 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 306 of file G4PrimaryTransformer.cc
References G4DecayProducts::entries(), G4cerr, G4endl, G4Exception(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetPreAssignedDecayProducts(), IsGoodForTrack(), and JustWarning.
void G4PrimaryTransformer::CheckUnknown ()
Definition at line 55 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 55 of file G4PrimaryTransformer.cc
References G4ParticleTable::FindParticle(), opticalphoton, opticalphotonDefined, particleTable, unknown, and unknownParticleDefined.
Referenced by G4PrimaryTransformer(), and G4RunManagerKernel::RunInitialization().
void G4PrimaryTransformer::GenerateSingleTrack (G4PrimaryParticle * primaryParticle, G4double x0, G4double y0, G4double z0, G4double t0, G4double wv) protected
Definition at line 116 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 116 of file G4PrimaryTransformer.cc
References G4DynamicParticle::AddElectron(), angle, CLHEP::Hep3Vector::cross(), DBL_MAX, deg, eplus, G4cerr, G4cout, G4endl, G4Exception(), G4UniformRand, G4ParticleDefinition::GetAtomicNumber(), G4PrimaryParticle::GetCharge(), G4PrimaryParticle::GetDaughter(), G4PrimaryParticle::GetKineticEnergy(), G4PrimaryParticle::GetMass(), G4PrimaryParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4PrimaryParticle::GetMomentumDirection(), G4PrimaryParticle::GetNext(), G4ParticleDefinition::GetParticleName(), G4PrimaryParticle::GetPDGcode(), G4ParticleDefinition::GetPDGEncoding(), G4PrimaryParticle::GetPolarization(), G4PrimaryParticle::GetPolX(), G4PrimaryParticle::GetPolY(), G4PrimaryParticle::GetPolZ(), G4PrimaryParticle::GetProperTime(), G4PrimaryParticle::GetWeight(), JustWarning, CLHEP::Hep3Vector::mag2(), CLHEP::normal(), G4DynamicParticle::SetCharge(), G4DynamicParticle::SetMass(), G4Track::SetParentID(), G4DynamicParticle::SetPDGcode(), G4DynamicParticle::SetPolarization(), G4DynamicParticle::SetPreAssignedDecayProperTime(), G4DynamicParticle::SetPrimaryParticle(), G4Track::SetTrackID(), G4PrimaryParticle::SetTrackID(), G4Track::SetWeight(), track, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by GenerateTracks().
void G4PrimaryTransformer::GenerateTracks (G4PrimaryVertex * primaryVertex) protected
Definition at line 87 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 87 of file G4PrimaryTransformer.cc
References G4cout, G4endl, GenerateSingleTrack(), G4PrimaryParticle::GetNext(), G4PrimaryVertex::GetPrimary(), G4PrimaryVertex::GetT0(), G4PrimaryVertex::GetWeight(), G4PrimaryVertex::GetX0(), G4PrimaryVertex::GetY0(), G4PrimaryVertex::GetZ0(), mm, nanosecond, G4PrimaryVertex::Print(), T0, and verboseLevel.
Referenced by GimmePrimaries().
G4ParticleDefinition * G4PrimaryTransformer::GetDefinition (G4PrimaryParticle * pp) protected virtual
Definition at line 319 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 319 of file G4PrimaryTransformer.cc
References G4ParticleTable::FindParticle(), G4PrimaryParticle::GetG4code(), G4PrimaryParticle::GetPDGcode(), G4ParticleDefinition::IsShortLived(), particleTable, unknown, and unknownParticleDefined.
G4bool G4PrimaryTransformer::GetUnknownParticleDefined () const inline
Definition at line 77 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 77 of file G4PrimaryTransformer.hh
References unknownParticleDefined.
G4TrackVector * G4PrimaryTransformer::GimmePrimaries (G4Event * anEvent, G4int trackIDCounter = 0)
Definition at line 69 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 69 of file G4PrimaryTransformer.cc
References GenerateTracks(), G4PrimaryVertex::GetNext(), G4Event::GetPrimaryVertex(), trackID, and TV.
Referenced by G4EventManager::DoProcessing().
G4bool G4PrimaryTransformer::IsGoodForTrack (G4ParticleDefinition * pd) protected virtual
Definition at line 327 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 327 of file G4PrimaryTransformer.cc
References G4ParticleDefinition::GetDecayTable(), and G4ParticleDefinition::IsShortLived().
Referenced by CheckDynamicParticle().
void G4PrimaryTransformer::SetDecayProducts (G4PrimaryParticle * mother, G4DynamicParticle * motherDP) protected
Definition at line 235 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 235 of file G4PrimaryTransformer.cc
References DBL_MAX, G4cout, G4endl, G4PrimaryParticle::GetCharge(), G4PrimaryParticle::GetDaughter(), G4PrimaryParticle::GetMass(), G4PrimaryParticle::GetMomentum(), G4PrimaryParticle::GetNext(), G4ParticleDefinition::GetParticleName(), G4PrimaryParticle::GetPDGcode(), G4PrimaryParticle::GetPolX(), G4PrimaryParticle::GetPolY(), G4PrimaryParticle::GetPolZ(), G4DynamicParticle::GetPreAssignedDecayProducts(), G4PrimaryParticle::GetProperTime(), G4DecayProducts::PushProducts(), G4DynamicParticle::SetCharge(), G4DynamicParticle::SetMass(), G4DynamicParticle::SetPolarization(), G4DynamicParticle::SetPreAssignedDecayProducts(), G4DynamicParticle::SetPreAssignedDecayProperTime(), and G4DynamicParticle::SetPrimaryParticle().
void G4PrimaryTransformer::SetUnknnownParticleDefined (G4bool vl)
Definition at line 296 of file G4PrimaryTransformer.cc.
View newest version in sPHENIX GitHub at line 296 of file G4PrimaryTransformer.cc
References G4cerr, G4endl, unknown, and unknownParticleDefined.
void G4PrimaryTransformer::SetVerboseLevel (G4int vl) inline
Definition at line 69 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PrimaryTransformer.hh
References verboseLevel.
Referenced by G4EventManager::SetVerboseLevel().
Member Data Documentation
G4int G4PrimaryTransformer::nWarn protected
Definition at line 66 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 66 of file G4PrimaryTransformer.hh
G4ParticleDefinition* G4PrimaryTransformer::opticalphoton protected
Definition at line 63 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 63 of file G4PrimaryTransformer.hh
Referenced by CheckUnknown().
G4bool G4PrimaryTransformer::opticalphotonDefined protected
Definition at line 64 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 64 of file G4PrimaryTransformer.hh
Referenced by CheckUnknown().
G4ParticleTable* G4PrimaryTransformer::particleTable protected
Definition at line 57 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 57 of file G4PrimaryTransformer.hh
Referenced by CheckUnknown(), G4PrimaryTransformer(), and GetDefinition().
G4int G4PrimaryTransformer::trackID protected
Definition at line 59 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PrimaryTransformer.hh
Referenced by GimmePrimaries().
G4TrackVector G4PrimaryTransformer::TV protected
Definition at line 56 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 56 of file G4PrimaryTransformer.hh
Referenced by GimmePrimaries().
G4ParticleDefinition* G4PrimaryTransformer::unknown protected
Definition at line 61 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 61 of file G4PrimaryTransformer.hh
Referenced by CheckUnknown(), GetDefinition(), and SetUnknnownParticleDefined().
G4bool G4PrimaryTransformer::unknownParticleDefined protected
Definition at line 62 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 62 of file G4PrimaryTransformer.hh
Referenced by CheckUnknown(), GetDefinition(), GetUnknownParticleDefined(), and SetUnknnownParticleDefined().
G4int G4PrimaryTransformer::verboseLevel protected
Definition at line 58 of file G4PrimaryTransformer.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PrimaryTransformer.hh
Referenced by GenerateTracks(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4PrimaryTransformer.hh
geant4/tree/geant4-10.6-release/source/event/src/G4PrimaryTransformer.cc