ECCE @ EIC Software: G4VisFilterManager< T > Class Template Reference
G4VisFilterManager< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisFilterManager.hh>
Public Types
typedef G4VFilter< T > Filter
typedef G4VModelFactory< Filter > Factory
Public Member Functions
G4VisFilterManager (const G4String &)
virtual ~G4VisFilterManager ()
void Register (Filter *)
void Register (Factory *)
bool Accept (const T &)
G4String Placement () const
void SetMode (const FilterMode::Mode &)
void SetMode (const G4String &)
FilterMode::Mode GetMode () const
void Print (std::ostream &ostr, const G4String &name="") const
const std::vector< Filter * > & FilterList () const
const std::vector< Factory * > & FactoryList () const
Private Attributes
G4String fPlacement
FilterMode::Mode fMode
std::vector< Factory * > fFactoryList
std::vector< Filter * > fFilterList
std::vector< G4UImessenger * > fMessengerList
Detailed Description
template<typename T>
class G4VisFilterManager< T >
Definition at line 46 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VisFilterManager.hh
Member Typedef Documentation
template<typename T> typedef G4VModelFactory<Filter> G4VisFilterManager< T >::Factory
Definition at line 57 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VisFilterManager.hh
template<typename T> typedef G4VFilter<T> G4VisFilterManager< T >::Filter
Definition at line 56 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VisFilterManager.hh
Constructor & Destructor Documentation
template<typename T > G4VisFilterManager< T >::G4VisFilterManager (const G4String & placement)
Definition at line 93 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VisFilterManager.hh
References G4VisFilterManager< T >::fMode, and FilterMode::Hard.
template<typename T > G4VisFilterManager< T >::~G4VisFilterManager () virtual
Definition at line 100 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 100 of file G4VisFilterManager.hh
Member Function Documentation
template<typename T> bool G4VisFilterManager< T >::Accept (const T & obj)
Definition at line 143 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 143 of file G4VisFilterManager.hh
Referenced by G4VisManager::FilterDigi(), G4VisManager::FilterHit(), and G4VisManager::FilterTrajectory().
template<typename T > const std::vector< G4VModelFactory< G4VFilter< T > > * > & G4VisFilterManager< T >::FactoryList () const
Definition at line 238 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 238 of file G4VisFilterManager.hh
Referenced by G4VisManager::PrintAvailableModels().
template<typename T > const std::vector< G4VFilter< T > * > & G4VisFilterManager< T >::FilterList () const
Definition at line 231 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 231 of file G4VisFilterManager.hh
Referenced by G4VisManager::PrintAvailableModels().
template<typename T > FilterMode::Mode G4VisFilterManager< T >::GetMode () const
Definition at line 192 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 192 of file G4VisFilterManager.hh
Referenced by G4VisManager::DispatchToModel().
template<typename T > G4String G4VisFilterManager< T >::Placement () const
Definition at line 158 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 158 of file G4VisFilterManager.hh
Referenced by G4VisManager::RegisterMessengers().
template<typename T > void G4VisFilterManager< T >::Print (std::ostream & ostr, const G4String & name = "") const
Definition at line 199 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 199 of file G4VisFilterManager.hh
References G4String::isNull().
template<typename T > void G4VisFilterManager< T >::Register (Filter * filter)
Definition at line 127 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 127 of file G4VisFilterManager.hh
Referenced by G4VisManager::RegisterModel(), and G4VisManager::RegisterModelFactory().
template<typename T > void G4VisFilterManager< T >::Register (Factory * factory)
Definition at line 134 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 134 of file G4VisFilterManager.hh
template<typename T > void G4VisFilterManager< T >::SetMode (const FilterMode::Mode & mode)
Definition at line 185 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 185 of file G4VisFilterManager.hh
template<typename T > void G4VisFilterManager< T >::SetMode (const G4String & mode)
Definition at line 165 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 165 of file G4VisFilterManager.hh
References G4Exception(), FilterMode::Hard, JustWarning, FilterMode::Soft, and G4String::toLower().
Member Data Documentation
template<typename T> std::vector<Factory*> G4VisFilterManager< T >::fFactoryList private
Definition at line 86 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VisFilterManager.hh
template<typename T> std::vector<Filter*> G4VisFilterManager< T >::fFilterList private
Definition at line 87 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VisFilterManager.hh
template<typename T> std::vector<G4UImessenger*> G4VisFilterManager< T >::fMessengerList private
Definition at line 88 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VisFilterManager.hh
template<typename T> FilterMode::Mode G4VisFilterManager< T >::fMode private
Definition at line 85 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VisFilterManager.hh
Referenced by G4VisFilterManager< T >::G4VisFilterManager().
template<typename T> G4String G4VisFilterManager< T >::fPlacement private
Definition at line 84 of file G4VisFilterManager.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VisFilterManager.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisFilterManager.hh