ECCE @ EIC Software: G4VUserPrimaryGeneratorAction Class Reference
G4VUserPrimaryGeneratorAction Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VUserPrimaryGeneratorAction.hh>
Inherited by B01PrimaryGeneratorAction, B02PrimaryGeneratorAction, B03PrimaryGeneratorAction, B1PrimaryGeneratorAction, B1PrimaryGeneratorAction, B1PrimaryGeneratorAction, B2PrimaryGeneratorAction, B2PrimaryGeneratorAction, B2PrimaryGeneratorAction, B3PrimaryGeneratorAction, B3PrimaryGeneratorAction, B4PrimaryGeneratorAction, B4PrimaryGeneratorAction, B4PrimaryGeneratorAction, B4PrimaryGeneratorAction, B5PrimaryGeneratorAction, BrachyPrimaryGeneratorAction, CCalPrimaryGeneratorAction, CexmcPrimaryGeneratorAction, CML2PrimaryGenerationAction, demo.MyPrimaryGeneratorAction, Dicom2PrimaryGeneratorAction, DicomPrimaryGeneratorAction, DMXPrimaryGeneratorAction, doiPETPrimaryGeneratorAction, ElectronPrimaryGeneratorAction, eRositaPrimaryGeneratorAction, ExGflashPrimaryGeneratorAction, ExGflashPrimaryGeneratorAction, ExGflashPrimaryGeneratorAction, ExGflashPrimaryGeneratorAction, ExN02PrimaryGeneratorAction, ExN04PrimaryGeneratorAction, ExN04PrimaryGeneratorAction, ExP01PrimaryGeneratorAction, ExP02PrimaryGeneratorAction, ExTGPrimaryGeneratorAction, ExUCNPrimaryGeneratorAction, F01PrimaryGeneratorAction, F02PrimaryGeneratorAction, F03PrimaryGeneratorAction, F04PrimaryGeneratorAction, F05PrimaryGeneratorAction, F06PrimaryGeneratorAction, FCALPrimaryGeneratorAction, FFPrimaryGeneratorAction, FW::Geant4::MMPrimaryGeneratorAction, G01PrimaryGeneratorAction, G02PrimaryGeneratorAction, G03PrimaryGeneratorAction, G04PrimaryGeneratorAction, G4AdjointPrimaryGeneratorAction, G4BlinePrimaryGeneratorAction, G4HumanPhantomPrimaryGeneratorAction, G4RTPrimaryGeneratorAction, GammaKnifePrimaryGeneratorAction, GammaRayTelPrimaryGeneratorAction, GB01PrimaryGeneratorAction, GB02PrimaryGeneratorAction, GB03PrimaryGeneratorAction, GB04PrimaryGeneratorAction, GB05PrimaryGeneratorAction, GB06PrimaryGeneratorAction, GB07PrimaryGeneratorAction, GpsPrimaryGeneratorAction, GpsPrimaryGeneratorAction, GpsPrimaryGeneratorAction, GunPrimaryGeneratorAction, GunPrimaryGeneratorAction, GunPrimaryGeneratorAction, H02PrimaryGeneratorAction, HadrontherapyPrimaryGeneratorAction, IORTPrimaryGeneratorAction, LXePrimaryGeneratorAction, MedicalBeam, MedicalBeam, MedicalBeam, MedicalBeam, MyPrimaryGeneratorActionFromFile, OpNovicePrimaryGeneratorAction, Par01PrimaryGeneratorAction, Par02PrimaryGeneratorAction, ParticleGunAction, PHG4PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PurgMagPrimaryGeneratorAction, pyG4VUserPrimaryGeneratorAction::CB_G4VUserPrimaryGeneratorAction, QPrimaryGeneratorAction, RE01PrimaryGeneratorAction, RE02PrimaryGeneratorAction, RE03PrimaryGeneratorAction, RE04PrimaryGeneratorAction, RE05PrimaryGeneratorAction, RE06PrimaryGeneratorAction, RMC01PrimaryGeneratorAction, root_test.MyPrimaryGeneratorAction, run.MyPrimaryGeneratorAction, STCyclotronPrimaryGeneratorAction, test.MyPrimaryGeneratorAction, test.MyPrimaryGeneratorAction, TSPrimaryGeneratorAction, UltraPrimaryGeneratorAction, WLSPrimaryGeneratorAction, XPrimaryGeneratorAction, XrayFluoMercuryPrimaryGeneratorAction, XrayFluoPlanePrimaryGeneratorAction, XrayFluoPrimaryGeneratorAction, and XrayTelPrimaryGeneratorAction.
Public Member Functions
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)=0
Detailed Description
Definition at line 47 of file G4VUserPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VUserPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
G4VUserPrimaryGeneratorAction::G4VUserPrimaryGeneratorAction ()
Definition at line 33 of file G4VUserPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VUserPrimaryGeneratorAction.cc
References FatalException, G4Exception(), and G4ParticleTable::GetParticleTable().
G4VUserPrimaryGeneratorAction::~G4VUserPrimaryGeneratorAction () virtual
Definition at line 49 of file G4VUserPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 49 of file G4VUserPrimaryGeneratorAction.cc
Member Function Documentation
virtual void G4VUserPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) pure virtual
Implemented in MedicalBeam, G4AdjointPrimaryGeneratorAction, PrimaryGeneratorAction, CML2PrimaryGenerationAction, CCalPrimaryGeneratorAction, XrayTelPrimaryGeneratorAction, MedicalBeam, MedicalBeam, MedicalBeam, G4BlinePrimaryGeneratorAction, CexmcPrimaryGeneratorAction, GammaRayTelPrimaryGeneratorAction, DMXPrimaryGeneratorAction, PrimaryGeneratorAction, XrayFluoPrimaryGeneratorAction, PrimaryGeneratorAction, FFPrimaryGeneratorAction, DicomPrimaryGeneratorAction, UltraPrimaryGeneratorAction, doiPETPrimaryGeneratorAction, IORTPrimaryGeneratorAction, RMC01PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, G02PrimaryGeneratorAction, XrayFluoMercuryPrimaryGeneratorAction, XrayFluoPlanePrimaryGeneratorAction, PrimaryGeneratorAction, WLSPrimaryGeneratorAction, G03PrimaryGeneratorAction, PurgMagPrimaryGeneratorAction, GunPrimaryGeneratorAction, GunPrimaryGeneratorAction, GunPrimaryGeneratorAction, PrimaryGeneratorAction, MyPrimaryGeneratorActionFromFile, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, RE02PrimaryGeneratorAction, B5PrimaryGeneratorAction, PrimaryGeneratorAction, F01PrimaryGeneratorAction, F02PrimaryGeneratorAction, F03PrimaryGeneratorAction, TSPrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, F04PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, ParticleGunAction, QPrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, Dicom2PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, ExP01PrimaryGeneratorAction, PrimaryGeneratorAction, RE04PrimaryGeneratorAction, B1PrimaryGeneratorAction, B1PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, OpNovicePrimaryGeneratorAction, B1PrimaryGeneratorAction, B2PrimaryGeneratorAction, B2PrimaryGeneratorAction, B3PrimaryGeneratorAction, B3PrimaryGeneratorAction, B4PrimaryGeneratorAction, B4PrimaryGeneratorAction, B4PrimaryGeneratorAction, B4PrimaryGeneratorAction, GpsPrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, GpsPrimaryGeneratorAction, ExUCNPrimaryGeneratorAction, F05PrimaryGeneratorAction, F06PrimaryGeneratorAction, GpsPrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, B2PrimaryGeneratorAction, ExN02PrimaryGeneratorAction, G01PrimaryGeneratorAction, G04PrimaryGeneratorAction, ExP02PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, FW::Geant4::MMPrimaryGeneratorAction, PrimaryGeneratorAction, HadrontherapyPrimaryGeneratorAction, FCALPrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, BrachyPrimaryGeneratorAction, PrimaryGeneratorAction, H02PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, Par02PrimaryGeneratorAction, eRositaPrimaryGeneratorAction, STCyclotronPrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, LXePrimaryGeneratorAction, ExN04PrimaryGeneratorAction, RE01PrimaryGeneratorAction, RE05PrimaryGeneratorAction, ExN04PrimaryGeneratorAction, Par01PrimaryGeneratorAction, ExTGPrimaryGeneratorAction, RE03PrimaryGeneratorAction, G4RTPrimaryGeneratorAction, G4HumanPhantomPrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, B01PrimaryGeneratorAction, B02PrimaryGeneratorAction, B03PrimaryGeneratorAction, GB04PrimaryGeneratorAction, GB05PrimaryGeneratorAction, PrimaryGeneratorAction, XPrimaryGeneratorAction, ElectronPrimaryGeneratorAction, RE06PrimaryGeneratorAction, pyG4VUserPrimaryGeneratorAction::CB_G4VUserPrimaryGeneratorAction, GB01PrimaryGeneratorAction, GB02PrimaryGeneratorAction, GB03PrimaryGeneratorAction, GB06PrimaryGeneratorAction, GB07PrimaryGeneratorAction, PrimaryGeneratorAction, ExGflashPrimaryGeneratorAction, ExGflashPrimaryGeneratorAction, ExGflashPrimaryGeneratorAction, ExGflashPrimaryGeneratorAction, GammaKnifePrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, PrimaryGeneratorAction, and PHG4PrimaryGeneratorAction.
Referenced by export_G4VUserPrimaryGeneratorAction(), G4WorkerRunManager::GenerateEvent(), G4RunManager::GenerateEvent(), and G4BlinePrimaryGeneratorAction::GeneratePrimaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VUserPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VUserPrimaryGeneratorAction.cc