ECCE @ EIC Software: RE02PSNofStep Class Reference
RE02PSNofStep Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/include/RE02PSNofStep.hh>
Public Member Functions
RE02PSNofStep (G4String name, G4int nx, G4int ny, G4int nz)
virtual ~RE02PSNofStep ()
Public Member Functions inherited from G4PSNofStep
G4PSNofStep (G4String name, G4int depth=0)
virtual ~G4PSNofStep ()
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
void SetBoundaryFlag (G4bool flg=true)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4int GetIndex (G4Step *)
Protected Member Functions inherited from G4PSNofStep
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VPrimitiveScorer
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int fNx
G4int fNy
G4int fNz
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 44 of file RE02PSNofStep.hh.
View newest version in sPHENIX GitHub at line 44 of file RE02PSNofStep.hh
Constructor & Destructor Documentation
RE02PSNofStep::RE02PSNofStep (G4String name, G4int nx, G4int ny, G4int nz)
Definition at line 60 of file RE02PSNofStep.cc.
View newest version in sPHENIX GitHub at line 60 of file RE02PSNofStep.cc
RE02PSNofStep::~RE02PSNofStep () virtual
Definition at line 65 of file RE02PSNofStep.cc.
View newest version in sPHENIX GitHub at line 65 of file RE02PSNofStep.cc
Member Function Documentation
G4int RE02PSNofStep::GetIndex (G4Step * aStep) protected virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 69 of file RE02PSNofStep.cc.
View newest version in sPHENIX GitHub at line 69 of file RE02PSNofStep.cc
References fNx, fNy, fNz, G4Step::GetPreStepPoint(), G4VTouchable::GetReplicaNumber(), G4StepPoint::GetTouchable(), and tmp.
Member Data Documentation
G4int RE02PSNofStep::fNx private
Definition at line 54 of file RE02PSNofStep.hh.
View newest version in sPHENIX GitHub at line 54 of file RE02PSNofStep.hh
Referenced by GetIndex().
G4int RE02PSNofStep::fNy private
Definition at line 54 of file RE02PSNofStep.hh.
View newest version in sPHENIX GitHub at line 54 of file RE02PSNofStep.hh
Referenced by GetIndex().
G4int RE02PSNofStep::fNz private
Definition at line 54 of file RE02PSNofStep.hh.
View newest version in sPHENIX GitHub at line 54 of file RE02PSNofStep.hh
Referenced by GetIndex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/include/RE02PSNofStep.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/src/RE02PSNofStep.cc