ECCE @ EIC Software: TrackingAction Class Reference
TrackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/TrackingAction.hh>
Public Member Functions
TrackingAction (DetectorConstruction *)
~TrackingAction ()
void PreUserTrackingAction (const G4Track *)
void PostUserTrackingAction (const G4Track *)
TrackingAction (DetectorConstruction *detector=0)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
void SetDetector (DetectorConstruction *detector)
std::map< const
G4ParticleDefinition *, int > & GetNParticlesCreatedInTarget ()
std::map< const
G4ParticleDefinition *, int > & GetNParticlesCreatedInWorld ()
TrackingAction (PrimaryGeneratorAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (DetectorConstruction *)
~TrackingAction ()
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (PrimaryGeneratorAction *)
~TrackingAction ()
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (RunAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
virtual ~TrackingAction ()
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (DetectorConstruction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (DetectorConstruction *, EventAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (DetectorConstruction *, RunAction *)
virtual ~TrackingAction ()
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
virtual ~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
TrackingAction (PrimaryGeneratorAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
~TrackingAction ()
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
void UpdateTrackInfo (G4double, G4double, G4double)
TrackingAction (EventAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (EventAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
virtual ~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
virtual ~TrackingAction ()
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
~TrackingAction ()
void Initialize ()
virtual void PreUserTrackingAction (const G4Track *)
std::map< const
G4ParticleDefinition *, int > & GetNParticlesCreatedInTarget ()
std::map< const
G4ParticleDefinition *, int > & GetNParticlesCreatedInWorld ()
TrackingAction ()
~TrackingAction ()
void Initialize ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
std::map< const
G4ParticleDefinition *, int > & GetNParticlesCreatedInTarget ()
std::map< const
G4ParticleDefinition *, int > & GetNParticlesCreatedInWorld ()
TrackingAction (PrimaryGeneratorAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
virtual ~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
virtual void Initialize ()
TrackingAction (PrimaryGeneratorAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (PrimaryGeneratorAction *)
~TrackingAction ()
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (DetectorConstruction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction ()
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
void AddEdepCavity (G4double de)
TrackingAction ()
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
void AddEdepCavity (G4double de)
TrackingAction ()
virtual ~TrackingAction ()
void PreUserTrackingAction (const G4Track *)
void PostUserTrackingAction (const G4Track *)
TrackingAction ()
virtual ~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (EventAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
TrackingAction (EventAction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
void SetFullChain (G4bool flag)
void SetTimeWindow (G4double, G4double)
TrackingAction (DetectorConstruction *)
~TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
Public Member Functions inherited from G4UserTrackingAction
G4UserTrackingAction ()
virtual ~G4UserTrackingAction ()
virtual void SetTrackingManagerPointer (G4TrackingManager *pValue)
Private Member Functions
TrackingAction & operator= (const TrackingAction &right)
TrackingAction (const TrackingAction &)
TrackingAction (const TrackingAction &right)
const TrackingAction & operator= (const TrackingAction &right)
Private Attributes
DetectorConstruction * detector
DetectorConstruction * fDetector
G4Region * fTargetRegion
std::map< const
G4ParticleDefinition *, int > fNParticleInTarget
std::map< const
G4ParticleDefinition *, int > fNParticleInWorld
PrimaryGeneratorAction * fPrimary
RunAction * fRunAction
G4double fEkin1
EventAction * fEventAction
G4double fXstartAbs
G4double fXendAbs
G4double fPrimaryCharge
G4double fDirX
HistoManager * fHisto
G4ThreeVector fNewUz
G4int fNbStep1
G4int fNbStep2
G4double fTrackLen1
G4double fTrackLen2
G4double fTime1
G4double fTime2
G4Region * fpTargetRegion
G4double fTrackLength
G4double fZend
G4double fEdepCavity
G4double fTimeBirth
G4double fTimeEnd
EventAction * fEvent
TrackingMessenger * fTrackMessenger
G4double fCharge
G4double fMass
G4bool fFullChain
G4double fTime_birth
G4double fTime_end
G4double fTimeWindow1
G4double fTimeWindow2
Additional Inherited Members
Protected Attributes inherited from G4UserTrackingAction
G4TrackingManager * fpTrackingManager
Detailed Description
Definition at line 40 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 40 of file TrackingAction.hh
Constructor & Destructor Documentation
TrackingAction::TrackingAction (DetectorConstruction * det)
Definition at line 46 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file TrackingAction.cc
TrackingAction::~TrackingAction () inline
Definition at line 45 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 45 of file TrackingAction.hh
TrackingAction::TrackingAction (DetectorConstruction * detector = 0)
TrackingAction::~TrackingAction ()
TrackingAction::TrackingAction (PrimaryGeneratorAction * prim)
Definition at line 46 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file TrackingAction.cc
TrackingAction::~TrackingAction () inline
Definition at line 46 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file TrackingAction.hh
TrackingAction::TrackingAction (DetectorConstruction *)
TrackingAction::~TrackingAction () inline
Definition at line 47 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file TrackingAction.hh
TrackingAction::TrackingAction (PrimaryGeneratorAction *)
TrackingAction::~TrackingAction () inline
Definition at line 47 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file TrackingAction.hh
TrackingAction::TrackingAction (RunAction * runaction)
Definition at line 40 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 40 of file TrackingAction.cc
References fEkin1.
TrackingAction::~TrackingAction () inline
Definition at line 47 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file TrackingAction.hh
TrackingAction::TrackingAction ()
Definition at line 41 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file TrackingAction.cc
virtual TrackingAction::~TrackingAction () inline virtual
Definition at line 44 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 44 of file TrackingAction.hh
TrackingAction::TrackingAction (DetectorConstruction *)
TrackingAction::~TrackingAction () inline
Definition at line 47 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file TrackingAction.hh
TrackingAction::TrackingAction (DetectorConstruction * DET, EventAction * EA)
Definition at line 48 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file TrackingAction.cc
References fDirX, fPrimaryCharge, fXendAbs, and fXstartAbs.
TrackingAction::~TrackingAction () inline
Definition at line 48 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 48 of file TrackingAction.hh
TrackingAction::TrackingAction (DetectorConstruction * det, RunAction * run)
Definition at line 40 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 40 of file TrackingAction.cc
virtual TrackingAction::~TrackingAction () virtual
TrackingAction::TrackingAction ()
virtual TrackingAction::~TrackingAction () virtual
TrackingAction::TrackingAction (const TrackingAction &) private
TrackingAction::TrackingAction ()
TrackingAction::~TrackingAction () inline
Definition at line 46 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file TrackingAction.hh
TrackingAction::TrackingAction (PrimaryGeneratorAction *)
TrackingAction::~TrackingAction () inline
Definition at line 49 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 49 of file TrackingAction.hh
TrackingAction::TrackingAction ()
TrackingAction::~TrackingAction ()
TrackingAction::TrackingAction ()
TrackingAction::~TrackingAction () inline
Definition at line 45 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 45 of file TrackingAction.hh
TrackingAction::TrackingAction (EventAction * event)
Definition at line 49 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 49 of file TrackingAction.cc
TrackingAction::~TrackingAction () inline
Definition at line 47 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file TrackingAction.hh
TrackingAction::TrackingAction ()
TrackingAction::~TrackingAction () inline
Definition at line 45 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 45 of file TrackingAction.hh
TrackingAction::TrackingAction (EventAction *)
TrackingAction::~TrackingAction () inline
Definition at line 47 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file TrackingAction.hh
TrackingAction::TrackingAction ()
virtual TrackingAction::~TrackingAction () virtual
TrackingAction::TrackingAction ()
virtual TrackingAction::~TrackingAction () inline virtual
Definition at line 34 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 34 of file TrackingAction.hh
TrackingAction::TrackingAction ()
TrackingAction::~TrackingAction ()
TrackingAction::TrackingAction ()
TrackingAction::~TrackingAction ()
TrackingAction::TrackingAction (PrimaryGeneratorAction *)
TrackingAction::~TrackingAction () inline
Definition at line 43 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 43 of file TrackingAction.hh
TrackingAction::TrackingAction ()
virtual TrackingAction::~TrackingAction () virtual
TrackingAction::TrackingAction (PrimaryGeneratorAction *)
TrackingAction::~TrackingAction () inline
Definition at line 62 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 62 of file TrackingAction.hh
TrackingAction::TrackingAction (PrimaryGeneratorAction *)
TrackingAction::~TrackingAction () inline
Definition at line 43 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 43 of file TrackingAction.hh
TrackingAction::TrackingAction (DetectorConstruction *)
TrackingAction::~TrackingAction () inline
Definition at line 48 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 48 of file TrackingAction.hh
TrackingAction::TrackingAction ()
TrackingAction::~TrackingAction ()
TrackingAction::TrackingAction ()
TrackingAction::~TrackingAction ()
TrackingAction::TrackingAction ()
virtual TrackingAction::~TrackingAction () virtual
TrackingAction::TrackingAction (const TrackingAction & right) private
TrackingAction::TrackingAction ()
virtual TrackingAction::~TrackingAction () inline virtual
Definition at line 42 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 42 of file TrackingAction.hh
TrackingAction::TrackingAction (EventAction *)
TrackingAction::~TrackingAction ()
TrackingAction::TrackingAction (EventAction *)
TrackingAction::~TrackingAction ()
TrackingAction::TrackingAction (DetectorConstruction *)
TrackingAction::~TrackingAction () inline
Definition at line 47 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file TrackingAction.hh
Member Function Documentation
void TrackingAction::AddEdepCavity (G4double de) inline
Definition at line 50 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 50 of file TrackingAction.hh
void TrackingAction::AddEdepCavity (G4double de) inline
Definition at line 52 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file TrackingAction.hh
References fEdepCavity.
std::map<const G4ParticleDefinition*, int>& TrackingAction::GetNParticlesCreatedInTarget () inline
Definition at line 52 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file TrackingAction.hh
References fNParticleInTarget.
Referenced by RunAction::EndWorker().
std::map<const G4ParticleDefinition*, int>& TrackingAction::GetNParticlesCreatedInTarget () inline
Definition at line 55 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file TrackingAction.hh
References fNParticleInTarget.
std::map<const G4ParticleDefinition*, int>& TrackingAction::GetNParticlesCreatedInTarget () inline
Definition at line 63 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file TrackingAction.hh
References fNParticleInTarget.
std::map<const G4ParticleDefinition*, int>& TrackingAction::GetNParticlesCreatedInWorld () inline
Definition at line 57 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file TrackingAction.hh
References fNParticleInWorld.
Referenced by RunAction::EndWorker().
std::map<const G4ParticleDefinition*, int>& TrackingAction::GetNParticlesCreatedInWorld () inline
Definition at line 60 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file TrackingAction.hh
References fNParticleInWorld.
std::map<const G4ParticleDefinition*, int>& TrackingAction::GetNParticlesCreatedInWorld () inline
Definition at line 68 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 68 of file TrackingAction.hh
References fNParticleInWorld.
virtual void TrackingAction::Initialize () virtual
Implements RunInitObserver.
void TrackingAction::Initialize () virtual
Implements RunInitObserver.
Definition at line 113 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 113 of file TrackingAction.cc
References fpTargetRegion, G4RegionStore::GetInstance(), and G4RegionStore::GetRegion().
void TrackingAction::Initialize () virtual
Implements RunInitObserver.
const TrackingAction& TrackingAction::operator= (const TrackingAction & right) private
TrackingAction& TrackingAction::operator= (const TrackingAction & right) private
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
void TrackingAction::PostUserTrackingAction (const G4Track * track) virtual
Reimplemented from G4UserTrackingAction.
Definition at line 57 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file TrackingAction.cc
References Run::DetailedLeakage(), detector, source.hepunit::electron_mass_c2, DetectorConstruction::GetCalorThickness(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4RunManager::GetNonConstCurrentRun(), G4Track::GetPosition(), DetectorConstruction::GetPvolWorld(), G4RunManager::GetRunManager(), G4Track::GetVolume(), G4Positron::Positron(), and x.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PostUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
void TrackingAction::PreUserTrackingAction (const G4Track * track) virtual
Reimplemented from G4UserTrackingAction.
Definition at line 52 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 52 of file TrackingAction.cc
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
virtual void TrackingAction::PreUserTrackingAction (const G4Track *) virtual
Reimplemented from G4UserTrackingAction.
void TrackingAction::SetDetector (DetectorConstruction * detector) inline
Definition at line 47 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 47 of file TrackingAction.hh
References detector, and fDetector.
void TrackingAction::SetFullChain (G4bool flag) inline
Definition at line 53 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file TrackingAction.hh
References fFullChain.
Referenced by TrackingMessenger::SetNewValue().
void TrackingAction::SetTimeWindow (G4double t1, G4double dt)
Definition at line 70 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 70 of file TrackingAction.cc
References fTimeWindow1, fTimeWindow2, and t1.
Referenced by TrackingMessenger::SetNewValue().
void TrackingAction::UpdateTrackInfo (G4double ekin, G4double trackl, G4double time)
Definition at line 60 of file TrackingAction.cc.
View newest version in sPHENIX GitHub at line 60 of file TrackingAction.cc
References eV, fNbStep1, fNbStep2, fTime1, fTime2, fTrackLen1, fTrackLen2, and Acts::VectorHelpers::time().
Member Data Documentation
DetectorConstruction* TrackingAction::detector private
Definition at line 51 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file TrackingAction.hh
Referenced by PostUserTrackingAction(), and SetDetector().
G4double TrackingAction::fCharge private
Definition at line 60 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file TrackingAction.hh
DetectorConstruction * TrackingAction::fDetector private
Definition at line 63 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file TrackingAction.hh
Referenced by SetDetector().
G4double TrackingAction::fDirX private
Definition at line 59 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file TrackingAction.hh
Referenced by TrackingAction().
G4double TrackingAction::fEdepCavity private
Definition at line 50 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 50 of file TrackingAction.hh
Referenced by AddEdepCavity().
G4double TrackingAction::fEkin1 private
Definition at line 55 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file TrackingAction.hh
Referenced by TrackingAction().
EventAction* TrackingAction::fEvent private
Definition at line 57 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file TrackingAction.hh
EventAction * TrackingAction::fEventAction private
Definition at line 55 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file TrackingAction.hh
G4bool TrackingAction::fFullChain private
Definition at line 61 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file TrackingAction.hh
Referenced by SetFullChain().
HistoManager* TrackingAction::fHisto private
Definition at line 70 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 70 of file TrackingAction.hh
G4double TrackingAction::fMass private
Definition at line 60 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file TrackingAction.hh
G4int TrackingAction::fNbStep1 private
Definition at line 53 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file TrackingAction.hh
Referenced by UpdateTrackInfo().
G4int TrackingAction::fNbStep2 private
Definition at line 53 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file TrackingAction.hh
Referenced by UpdateTrackInfo().
G4ThreeVector TrackingAction::fNewUz private
Definition at line 58 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file TrackingAction.hh
std::map< const G4ParticleDefinition *, int > TrackingAction::fNParticleInTarget private
Definition at line 65 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file TrackingAction.hh
Referenced by GetNParticlesCreatedInTarget().
std::map< const G4ParticleDefinition *, int > TrackingAction::fNParticleInWorld private
Definition at line 66 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 66 of file TrackingAction.hh
Referenced by GetNParticlesCreatedInWorld().
PrimaryGeneratorAction * TrackingAction::fPrimary private
Definition at line 52 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file TrackingAction.hh
G4double TrackingAction::fPrimaryCharge private
Definition at line 58 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file TrackingAction.hh
Referenced by TrackingAction().
G4Region * TrackingAction::fpTargetRegion private
Definition at line 66 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 66 of file TrackingAction.hh
Referenced by Initialize().
RunAction * TrackingAction::fRunAction private
Definition at line 53 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file TrackingAction.hh
G4Region* TrackingAction::fTargetRegion private
Definition at line 64 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file TrackingAction.hh
G4double TrackingAction::fTime1 private
Definition at line 55 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file TrackingAction.hh
Referenced by UpdateTrackInfo().
G4double TrackingAction::fTime2 private
Definition at line 55 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file TrackingAction.hh
Referenced by UpdateTrackInfo().
G4double TrackingAction::fTime_birth private
Definition at line 63 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file TrackingAction.hh
G4double TrackingAction::fTime_end private
Definition at line 63 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file TrackingAction.hh
G4double TrackingAction::fTimeBirth private
Definition at line 55 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file TrackingAction.hh
G4double TrackingAction::fTimeEnd private
Definition at line 55 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file TrackingAction.hh
G4double TrackingAction::fTimeWindow1 private
Definition at line 64 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file TrackingAction.hh
Referenced by SetTimeWindow().
G4double TrackingAction::fTimeWindow2 private
Definition at line 64 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file TrackingAction.hh
Referenced by SetTimeWindow().
G4double TrackingAction::fTrackLen1 private
Definition at line 54 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file TrackingAction.hh
Referenced by UpdateTrackInfo().
G4double TrackingAction::fTrackLen2 private
Definition at line 54 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file TrackingAction.hh
Referenced by UpdateTrackInfo().
G4double TrackingAction::fTrackLength private
Definition at line 51 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file TrackingAction.hh
TrackingMessenger* TrackingAction::fTrackMessenger private
Definition at line 58 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file TrackingAction.hh
G4double TrackingAction::fXendAbs private
Definition at line 57 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file TrackingAction.hh
Referenced by TrackingAction().
G4double TrackingAction::fXstartAbs private
Definition at line 57 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file TrackingAction.hh
Referenced by TrackingAction().
G4double TrackingAction::fZend private
Definition at line 56 of file TrackingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file TrackingAction.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/include/TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/src/TrackingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/src/TrackingAction.cc