ECCE @ EIC Software: doiPETDetectorConstructionMessenger Class Reference
doiPETDetectorConstructionMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/doiPET/include/doiPETDetectorConstructionMessenger.hh>
Public Member Functions
doiPETDetectorConstructionMessenger (doiPETDetectorConstruction *)
~doiPETDetectorConstructionMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
doiPETDetectorConstruction * Detector
G4UIdirectory * Dir
G4UIcmdWithAString * ChoosePhantomCmd
G4UIcmdWith3VectorAndUnit * changeThePhantomPositionCmd
G4UIcmdWithADoubleAndUnit * changePhantomRadiusCmd
G4UIcmdWithADoubleAndUnit * changePhantomLengthCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 59 of file doiPETDetectorConstructionMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file doiPETDetectorConstructionMessenger.hh
Constructor & Destructor Documentation
doiPETDetectorConstructionMessenger::doiPETDetectorConstructionMessenger (doiPETDetectorConstruction * det)
Definition at line 54 of file doiPETDetectorConstructionMessenger.cc.
View newest version in sPHENIX GitHub at line 54 of file doiPETDetectorConstructionMessenger.cc
References G4UIcommand::AvailableForStates(), changePhantomLengthCmd, changePhantomRadiusCmd, changeThePhantomPositionCmd, ChoosePhantomCmd, Dir, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
doiPETDetectorConstructionMessenger::~doiPETDetectorConstructionMessenger ()
Definition at line 92 of file doiPETDetectorConstructionMessenger.cc.
View newest version in sPHENIX GitHub at line 92 of file doiPETDetectorConstructionMessenger.cc
References changePhantomLengthCmd, changePhantomRadiusCmd, changeThePhantomPositionCmd, ChoosePhantomCmd, and Dir.
Member Function Documentation
void doiPETDetectorConstructionMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 105 of file doiPETDetectorConstructionMessenger.cc.
View newest version in sPHENIX GitHub at line 105 of file doiPETDetectorConstructionMessenger.cc
References doiPETDetectorConstruction::ChangePhantom(), changePhantomLengthCmd, changePhantomRadiusCmd, changeThePhantomPositionCmd, ChoosePhantomCmd, Detector, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), doiPETDetectorConstruction::SetPhantomLength(), and doiPETDetectorConstruction::SetPhantomRadius().
Member Data Documentation
G4UIcmdWithADoubleAndUnit* doiPETDetectorConstructionMessenger::changePhantomLengthCmd private
Definition at line 77 of file doiPETDetectorConstructionMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file doiPETDetectorConstructionMessenger.hh
Referenced by doiPETDetectorConstructionMessenger(), SetNewValue(), and ~doiPETDetectorConstructionMessenger().
G4UIcmdWithADoubleAndUnit* doiPETDetectorConstructionMessenger::changePhantomRadiusCmd private
Definition at line 76 of file doiPETDetectorConstructionMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file doiPETDetectorConstructionMessenger.hh
Referenced by doiPETDetectorConstructionMessenger(), SetNewValue(), and ~doiPETDetectorConstructionMessenger().
G4UIcmdWith3VectorAndUnit* doiPETDetectorConstructionMessenger::changeThePhantomPositionCmd private
Definition at line 75 of file doiPETDetectorConstructionMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file doiPETDetectorConstructionMessenger.hh
Referenced by doiPETDetectorConstructionMessenger(), SetNewValue(), and ~doiPETDetectorConstructionMessenger().
G4UIcmdWithAString* doiPETDetectorConstructionMessenger::ChoosePhantomCmd private
Definition at line 73 of file doiPETDetectorConstructionMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file doiPETDetectorConstructionMessenger.hh
Referenced by doiPETDetectorConstructionMessenger(), SetNewValue(), and ~doiPETDetectorConstructionMessenger().
doiPETDetectorConstruction* doiPETDetectorConstructionMessenger::Detector private
Definition at line 70 of file doiPETDetectorConstructionMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file doiPETDetectorConstructionMessenger.hh
Referenced by SetNewValue().
G4UIdirectory* doiPETDetectorConstructionMessenger::Dir private
Definition at line 72 of file doiPETDetectorConstructionMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file doiPETDetectorConstructionMessenger.hh
Referenced by doiPETDetectorConstructionMessenger(), and ~doiPETDetectorConstructionMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/doiPET/include/doiPETDetectorConstructionMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/doiPET/src/doiPETDetectorConstructionMessenger.cc