ECCE @ EIC Software: RE01CalorimeterHit Class Reference
RE01CalorimeterHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01CalorimeterHit.hh>
Public Member Functions
RE01CalorimeterHit (G4LogicalVolume *logVol, G4int z, G4int phi)
virtual ~RE01CalorimeterHit ()
void * operator new (size_t)
void operator delete (void *aHit)
virtual void Draw ()
virtual void Print ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
G4int GetZ ()
G4int GetPhi ()
void SetEdep (G4double de)
void AddEdep (G4double de)
G4double GetEdep ()
G4double GetEdepByATrack ()
void ClearEdepByATrack ()
void SetPos (G4ThreeVector xyz)
void SetRot (G4RotationMatrix rmat)
void SetTrackInformation (const G4Track *aTrack)
RE01TrackInformation * GetTrackInformation ()
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
Private Attributes
G4int fZCellID
G4int fPhiCellID
G4double fEdep
G4ThreeVector fPos
G4RotationMatrix fRot
const G4LogicalVolume * fPLogV
G4double fEdepByATrack
RE01TrackInformation fTrackInfo
Detailed Description
Definition at line 48 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 48 of file RE01CalorimeterHit.hh
Constructor & Destructor Documentation
RE01CalorimeterHit::RE01CalorimeterHit (G4LogicalVolume * logVol, G4int z, G4int phi)
Definition at line 48 of file RE01CalorimeterHit.cc.
View newest version in sPHENIX GitHub at line 48 of file RE01CalorimeterHit.cc
RE01CalorimeterHit::~RE01CalorimeterHit () virtual
Definition at line 55 of file RE01CalorimeterHit.cc.
View newest version in sPHENIX GitHub at line 55 of file RE01CalorimeterHit.cc
Member Function Documentation
void RE01CalorimeterHit::AddEdep (G4double de) inline
Definition at line 66 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 66 of file RE01CalorimeterHit.hh
References fEdep, and fEdepByATrack.
void RE01CalorimeterHit::ClearEdepByATrack () inline
Definition at line 72 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 72 of file RE01CalorimeterHit.hh
References fEdepByATrack, and fTrackInfo.
std::vector< G4AttValue > * RE01CalorimeterHit::CreateAttValues () const virtual
Reimplemented from G4VHit.
Definition at line 112 of file RE01CalorimeterHit.cc.
View newest version in sPHENIX GitHub at line 112 of file RE01CalorimeterHit.cc
References G4UIcommand::ConvertToString(), fEdep, fEdepByATrack, fPhiCellID, fPLogV, fPos, fZCellID, G4BestUnit, G4LogicalVolume::GetName(), and Acts::Test::values.
void RE01CalorimeterHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 59 of file RE01CalorimeterHit.cc.
View newest version in sPHENIX GitHub at line 59 of file RE01CalorimeterHit.cc
References G4VVisManager::Draw(), fPLogV, fPos, fRot, G4VVisManager::GetConcreteInstance(), G4LogicalVolume::GetVisAttributes(), G4VisAttributes::SetColour(), G4VisAttributes::SetForceSolid(), and G4VisAttributes::SetForceWireframe().
const std::map< G4String, G4AttDef > * RE01CalorimeterHit::GetAttDefs () const virtual
Reimplemented from G4VHit.
Definition at line 77 of file RE01CalorimeterHit.cc.
View newest version in sPHENIX GitHub at line 77 of file RE01CalorimeterHit.cc
References energy, G4AttDefStore::GetInstance(), and pos().
G4double RE01CalorimeterHit::GetEdep () inline
Definition at line 68 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 68 of file RE01CalorimeterHit.hh
References fEdep.
G4double RE01CalorimeterHit::GetEdepByATrack () inline
Definition at line 70 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 70 of file RE01CalorimeterHit.hh
References fEdepByATrack.
G4int RE01CalorimeterHit::GetPhi () inline
Definition at line 63 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 63 of file RE01CalorimeterHit.hh
References fPhiCellID.
RE01TrackInformation* RE01CalorimeterHit::GetTrackInformation () inline
Definition at line 84 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 84 of file RE01CalorimeterHit.hh
References fTrackInfo.
G4int RE01CalorimeterHit::GetZ () inline
Definition at line 62 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 62 of file RE01CalorimeterHit.hh
References fZCellID.
void RE01CalorimeterHit::operator delete (void * aHit) inline
Definition at line 110 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 110 of file RE01CalorimeterHit.hh
References RE01CalorimeterHitAllocator.
void * RE01CalorimeterHit::operator new (size_t) inline
Definition at line 103 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 103 of file RE01CalorimeterHit.hh
References RE01CalorimeterHitAllocator.
void RE01CalorimeterHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 144 of file RE01CalorimeterHit.cc.
View newest version in sPHENIX GitHub at line 144 of file RE01CalorimeterHit.cc
References fEdep, fPhiCellID, fZCellID, G4cout, G4endl, and GeV.
void RE01CalorimeterHit::SetEdep (G4double de) inline
Definition at line 64 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 64 of file RE01CalorimeterHit.hh
References fEdep, and fEdepByATrack.
Referenced by RE01CalorimeterSD::ProcessHits().
void RE01CalorimeterHit::SetPos (G4ThreeVector xyz) inline
Definition at line 74 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 74 of file RE01CalorimeterHit.hh
References fPos.
Referenced by RE01CalorimeterSD::ProcessHits().
void RE01CalorimeterHit::SetRot (G4RotationMatrix rmat) inline
Definition at line 76 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 76 of file RE01CalorimeterHit.hh
References fRot.
Referenced by RE01CalorimeterSD::ProcessHits().
void RE01CalorimeterHit::SetTrackInformation (const G4Track * aTrack) inline
Definition at line 78 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 78 of file RE01CalorimeterHit.hh
References fTrackInfo, and G4Track::GetUserInformation().
Referenced by RE01CalorimeterSD::ProcessHits().
Member Data Documentation
G4double RE01CalorimeterHit::fEdep private
Definition at line 90 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 90 of file RE01CalorimeterHit.hh
Referenced by AddEdep(), CreateAttValues(), GetEdep(), Print(), and SetEdep().
G4double RE01CalorimeterHit::fEdepByATrack private
Definition at line 94 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 94 of file RE01CalorimeterHit.hh
Referenced by AddEdep(), ClearEdepByATrack(), CreateAttValues(), GetEdepByATrack(), and SetEdep().
G4int RE01CalorimeterHit::fPhiCellID private
Definition at line 89 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 89 of file RE01CalorimeterHit.hh
Referenced by CreateAttValues(), GetPhi(), and Print().
const G4LogicalVolume* RE01CalorimeterHit::fPLogV private
Definition at line 93 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 93 of file RE01CalorimeterHit.hh
Referenced by CreateAttValues(), and Draw().
G4ThreeVector RE01CalorimeterHit::fPos private
Definition at line 91 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 91 of file RE01CalorimeterHit.hh
Referenced by CreateAttValues(), Draw(), and SetPos().
G4RotationMatrix RE01CalorimeterHit::fRot private
Definition at line 92 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 92 of file RE01CalorimeterHit.hh
Referenced by Draw(), and SetRot().
RE01TrackInformation RE01CalorimeterHit::fTrackInfo private
Definition at line 95 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 95 of file RE01CalorimeterHit.hh
Referenced by ClearEdepByATrack(), GetTrackInformation(), and SetTrackInformation().
G4int RE01CalorimeterHit::fZCellID private
Definition at line 88 of file RE01CalorimeterHit.hh.
View newest version in sPHENIX GitHub at line 88 of file RE01CalorimeterHit.hh
Referenced by CreateAttValues(), GetZ(), and Print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01CalorimeterHit.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/src/RE01CalorimeterHit.cc