ECCE @ EIC Software: RMC01DetectorConstruction Class Reference
RMC01DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/RMC01DetectorConstruction.hh>
Public Member Functions
RMC01DetectorConstruction ()
virtual ~RMC01DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
void UpdateGeometry ()
void SetSensitiveVolumeHeight (G4double h)
void SetSensitiveVolumeRadius (G4double r)
void SetShieldingThickness (G4double d)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
G4VPhysicalVolume * ConstructSimpleGeometry ()
Private Attributes
RMC01DetectorMessenger * fDetectorMessenger
G4double fShield_Thickness
G4double fSensitive_cylinder_H
G4double fSensitive_cylinder_Rout
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 57 of file RMC01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 57 of file RMC01DetectorConstruction.hh
Constructor & Destructor Documentation
RMC01DetectorConstruction::RMC01DetectorConstruction ()
Definition at line 65 of file RMC01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 65 of file RMC01DetectorConstruction.cc
References fDetectorMessenger.
RMC01DetectorConstruction::~RMC01DetectorConstruction () virtual
Definition at line 77 of file RMC01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 77 of file RMC01DetectorConstruction.cc
References fDetectorMessenger.
Member Function Documentation
G4VPhysicalVolume * RMC01DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 83 of file RMC01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 83 of file RMC01DetectorConstruction.cc
References ConstructSimpleGeometry(), and DefineMaterials().
G4VPhysicalVolume * RMC01DetectorConstruction::ConstructSimpleGeometry () private
Definition at line 132 of file RMC01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 132 of file RMC01DetectorConstruction.cc
References G4SDManager::AddNewDetector(), G4PhysicalVolumeStore::Clean(), G4LogicalVolumeStore::Clean(), G4SolidStore::Clean(), cm, fSensitive_cylinder_H, fSensitive_cylinder_Rout, fShield_Thickness, G4PhysicalVolumeStore::GetInstance(), G4LogicalVolumeStore::GetInstance(), G4SolidStore::GetInstance(), G4GeometryManager::GetInstance(), G4Material::GetMaterial(), G4SDManager::GetSDMpointer(), mm, G4GeometryManager::OpenGeometry(), G4LogicalVolume::SetSensitiveDetector(), and twopi.
Referenced by Construct().
void RMC01DetectorConstruction::DefineMaterials () private
Definition at line 91 of file RMC01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 91 of file RMC01DetectorConstruction.cc
References a, G4Material::AddElement(), cm3, e, Acts::UnitConstants::g, kelvin, kStateGas, mg, mole, N, pascal, source.hepunit::universe_mean_density, and z.
Referenced by Construct().
void RMC01DetectorConstruction::SetSensitiveVolumeHeight (G4double h)
Definition at line 256 of file RMC01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 256 of file RMC01DetectorConstruction.cc
References fSensitive_cylinder_H, and Acts::UnitConstants::h.
Referenced by RMC01DetectorMessenger::SetNewValue().
void RMC01DetectorConstruction::SetSensitiveVolumeRadius (G4double r)
Definition at line 250 of file RMC01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 250 of file RMC01DetectorConstruction.cc
References fSensitive_cylinder_Rout, and r.
Referenced by RMC01DetectorMessenger::SetNewValue().
void RMC01DetectorConstruction::SetShieldingThickness (G4double d)
Definition at line 262 of file RMC01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 262 of file RMC01DetectorConstruction.cc
References d, and fShield_Thickness.
Referenced by RMC01DetectorMessenger::SetNewValue().
void RMC01DetectorConstruction::UpdateGeometry ()
Member Data Documentation
RMC01DetectorMessenger* RMC01DetectorConstruction::fDetectorMessenger private
Definition at line 74 of file RMC01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 74 of file RMC01DetectorConstruction.hh
Referenced by RMC01DetectorConstruction(), and ~RMC01DetectorConstruction().
G4double RMC01DetectorConstruction::fSensitive_cylinder_H private
Definition at line 79 of file RMC01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 79 of file RMC01DetectorConstruction.hh
Referenced by ConstructSimpleGeometry(), and SetSensitiveVolumeHeight().
G4double RMC01DetectorConstruction::fSensitive_cylinder_Rout private
Definition at line 80 of file RMC01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file RMC01DetectorConstruction.hh
Referenced by ConstructSimpleGeometry(), and SetSensitiveVolumeRadius().
G4double RMC01DetectorConstruction::fShield_Thickness private
Definition at line 78 of file RMC01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 78 of file RMC01DetectorConstruction.hh
Referenced by ConstructSimpleGeometry(), and SetShieldingThickness().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/RMC01DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/src/RMC01DetectorConstruction.cc