ECCE @ EIC Software: RE01StackingAction Class Reference
RE01StackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01StackingAction.hh>
Public Member Functions
RE01StackingAction ()
virtual ~RE01StackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Private Member Functions
G4VHitsCollection * GetCalCollection ()
Private Attributes
G4int fStage
G4int fCalorimeterHitsColID
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 40 of file RE01StackingAction.hh.
View newest version in sPHENIX GitHub at line 40 of file RE01StackingAction.hh
Constructor & Destructor Documentation
RE01StackingAction::RE01StackingAction ()
Definition at line 47 of file RE01StackingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file RE01StackingAction.cc
RE01StackingAction::~RE01StackingAction () virtual
Definition at line 53 of file RE01StackingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file RE01StackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack RE01StackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 58 of file RE01StackingAction.cc.
View newest version in sPHENIX GitHub at line 58 of file RE01StackingAction.cc
References fSuspend, fUrgent, fWaiting, G4Track::GetParentID(), G4Track::GetTrackStatus(), G4Track::GetUserInformation(), RE01TrackInformation::SetSourceTrackInformation(), RE01TrackInformation::SetTrackingStatus(), and G4Track::SetUserInformation().
G4VHitsCollection * RE01StackingAction::GetCalCollection () private
Definition at line 88 of file RE01StackingAction.cc.
View newest version in sPHENIX GitHub at line 88 of file RE01StackingAction.cc
References fCalorimeterHitsColID, G4SDManager::GetCollectionID(), G4RunManager::GetCurrentEvent(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4RunManager::GetRunManager(), and G4SDManager::GetSDMpointer().
Referenced by NewStage().
void RE01StackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 104 of file RE01StackingAction.cc.
View newest version in sPHENIX GitHub at line 104 of file RE01StackingAction.cc
References G4THitsCollection< T >::entries(), fStage, fUrgent, fWaiting, G4cout, G4endl, GetCalCollection(), G4StackManager::GetNUrgentTrack(), GeV, G4UserStackingAction::stackManager, G4StackManager::TransferOneStackedTrack(), and G4StackManager::TransferStackedTracks().
void RE01StackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 171 of file RE01StackingAction.cc.
View newest version in sPHENIX GitHub at line 171 of file RE01StackingAction.cc
References fStage.
Member Data Documentation
G4int RE01StackingAction::fCalorimeterHitsColID private
Definition at line 55 of file RE01StackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file RE01StackingAction.hh
Referenced by GetCalCollection().
G4int RE01StackingAction::fStage private
Definition at line 54 of file RE01StackingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file RE01StackingAction.hh
Referenced by NewStage(), and PrepareNewEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01StackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/src/RE01StackingAction.cc