ECCE @ EIC Software: G4MonopoleTransportation Class Reference
G4MonopoleTransportation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/include/G4MonopoleTransportation.hh>
Public Member Functions
G4MonopoleTransportation (const G4Monopole *p, G4int verbosityLevel=1)
~G4MonopoleTransportation ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &stepData)
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &stepData)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4ForceCondition *pForceCond)
G4PropagatorInField * GetPropagatorInField ()
void SetPropagatorInField (G4PropagatorInField *pFieldPropagator)
G4double GetThresholdWarningEnergy () const
G4double GetThresholdImportantEnergy () const
G4int GetThresholdTrials () const
void SetThresholdWarningEnergy (G4double newEnWarn)
void SetThresholdImportantEnergy (G4double newEnImp)
void SetThresholdTrials (G4int newMaxTrials)
G4double GetMaxEnergyKilled () const
G4double GetSumEnergyKilled () const
void ResetKilledStatistics (G4int report=1)
void EnableShortStepOptimisation (G4bool optimise=true)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
G4double GetZmagFieldValue () const
virtual void StartTracking (G4Track *aTrack)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4bool DoesGlobalFieldExist ()
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Private Attributes
const G4Monopole * fParticleDef
G4MonopoleFieldSetup * fMagSetup
G4Navigator * fLinearNavigator
G4PropagatorInField * fFieldPropagator
G4ThreeVector fTransportEndPosition
G4ThreeVector fTransportEndMomentumDir
G4double fTransportEndKineticEnergy
G4ThreeVector fTransportEndSpin
G4bool fMomentumChanged
G4bool fEndGlobalTimeComputed
G4double fCandidateEndGlobalTime
G4bool fParticleIsLooping
G4TouchableHandle fCurrentTouchableHandle
G4bool fGeometryLimitedStep
G4ThreeVector fPreviousSftOrigin
G4double fPreviousSafety
G4ParticleChangeForTransport fParticleChange
G4double endpointDistance
G4double fThreshold_Warning_Energy
G4double fThreshold_Important_Energy
G4int fThresholdTrials
G4int fNoLooperTrials
G4double fSumEnergyKilled
G4double fMaxEnergyKilled
G4bool fShortStepOptimisation
G4SafetyHelper * fpSafetyHelper
G4int noCalls
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 65 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 65 of file G4MonopoleTransportation.hh
Constructor & Destructor Documentation
G4MonopoleTransportation::G4MonopoleTransportation (const G4Monopole * p, G4int verbosityLevel = 1)
Definition at line 62 of file G4MonopoleTransportation.cc.
View newest version in sPHENIX GitHub at line 62 of file G4MonopoleTransportation.cc
References fCandidateEndGlobalTime, fCurrentTouchableHandle, fEndGlobalTimeComputed, fFieldPropagator, fLinearNavigator, fMagSetup, fpSafetyHelper, DetectorConstruction::GetMonopoleFieldSetup(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetPropagatorInField(), G4RunManager::GetRunManager(), G4TransportationManager::GetSafetyHelper(), G4TransportationManager::GetTransportationManager(), G4RunManager::GetUserDetectorConstruction(), G4Threading::IsMasterThread(), G4Threading::IsMultithreadedApplication(), G4VProcess::SetProcessSubType(), TRANSPORTATION, and G4VProcess::verboseLevel.
G4MonopoleTransportation::~G4MonopoleTransportation ()
Definition at line 123 of file G4MonopoleTransportation.cc.
View newest version in sPHENIX GitHub at line 123 of file G4MonopoleTransportation.cc
References fMaxEnergyKilled, fSumEnergyKilled, G4cout, G4endl, and G4VProcess::verboseLevel.
Member Function Documentation
G4VParticleChange * G4MonopoleTransportation::AlongStepDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Definition at line 414 of file G4MonopoleTransportation.cc.
View newest version in sPHENIX GitHub at line 414 of file G4MonopoleTransportation.cc
References fCandidateEndGlobalTime, fEndGlobalTimeComputed, fFieldPropagator, fMaxEnergyKilled, fMomentumChanged, fNoLooperTrials, fParticleChange, fParticleIsLooping, fStopAndKill, fSumEnergyKilled, fThreshold_Important_Energy, fThreshold_Warning_Energy, fThresholdTrials, fTransportEndKineticEnergy, fTransportEndMomentumDir, fTransportEndPosition, fTransportEndSpin, G4cout, G4endl, G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4Step::GetPreStepPoint(), G4Track::GetProperTime(), G4Track::GetStepLength(), G4Track::GetTotalEnergy(), G4StepPoint::GetVelocity(), G4Track::GetVelocity(), G4PropagatorInField::GimmeTrajectoryVectorAndForgetIt(), G4ParticleChangeForTransport::Initialize(), MeV, noCalls, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeGlobalTime(), G4ParticleChange::ProposeMomentumDirection(), G4ParticleChange::ProposePolarization(), G4ParticleChange::ProposePosition(), G4ParticleChange::ProposeProperTime(), G4VParticleChange::ProposeTrackStatus(), G4ParticleChangeForTransport::SetMomentumChanged(), G4ParticleChangeForTransport::SetPointerToVectorOfAuxiliaryPoints(), and G4VProcess::verboseLevel.
G4double G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 143 of file G4MonopoleTransportation.cc.
View newest version in sPHENIX GitHub at line 143 of file G4MonopoleTransportation.cc
References CandidateForSelection, G4Navigator::ComputeSafety(), G4PropagatorInField::ComputeStep(), G4Navigator::ComputeStep(), G4FieldManager::ConfigureForTrack(), endpointDistance, false, fCandidateEndGlobalTime, fEndGlobalTimeComputed, fFieldPropagator, fGeometryLimitedStep, G4PropagatorInField::FindAndSetFieldManager(), fLinearNavigator, fMagSetup, fMomentumChanged, fParticleChange, fParticleDef, fParticleIsLooping, fPreviousSafety, fPreviousSftOrigin, fpSafetyHelper, fShortStepOptimisation, fTransportEndKineticEnergy, fTransportEndMomentumDir, fTransportEndPosition, fTransportEndSpin, G4cout, G4endl, G4DynamicParticle::GetCharge(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4FieldTrack::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4FieldTrack::GetLabTimeOfFlight(), G4FieldTrack::GetMomentumDir(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), G4Track::GetPolarization(), G4FieldTrack::GetPosition(), G4Track::GetPosition(), G4Track::GetProperTime(), G4FieldTrack::GetSpin(), G4DynamicParticle::GetTotalMomentum(), G4Track::GetVelocity(), G4Track::GetVolume(), G4PropagatorInField::IsParticleLooping(), CLHEP::Hep3Vector::mag2(), G4Monopole::MagneticCharge(), G4VParticleChange::ProposeTrueStepLength(), G4SafetyHelper::SetCurrentSafety(), G4MonopoleFieldSetup::SetStepperAndChordFinder(), sqr(), and true.
virtual G4VParticleChange* G4MonopoleTransportation::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 134 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 134 of file G4MonopoleTransportation.hh
virtual G4double G4MonopoleTransportation::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VProcess.
Definition at line 128 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 128 of file G4MonopoleTransportation.hh
G4bool G4MonopoleTransportation::DoesGlobalFieldExist () protected
Referenced by StartTracking().
void G4MonopoleTransportation::EnableShortStepOptimisation (G4bool optimise = true) inline
G4double G4MonopoleTransportation::GetMaxEnergyKilled () const inline
G4PropagatorInField* G4MonopoleTransportation::GetPropagatorInField ()
G4double G4MonopoleTransportation::GetSumEnergyKilled () const inline
G4double G4MonopoleTransportation::GetThresholdImportantEnergy () const inline
G4int G4MonopoleTransportation::GetThresholdTrials () const inline
G4double G4MonopoleTransportation::GetThresholdWarningEnergy () const inline
G4double G4MonopoleTransportation::GetZmagFieldValue () const inline
Definition at line 140 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 140 of file G4MonopoleTransportation.hh
References fMagSetup, and GetZmagFieldValue().
Referenced by GetZmagFieldValue().
G4VParticleChange * G4MonopoleTransportation::PostStepDoIt (const G4Track & track, const G4Step & stepData) virtual
Implements G4VProcess.
Definition at line 549 of file G4MonopoleTransportation.cc.
View newest version in sPHENIX GitHub at line 549 of file G4MonopoleTransportation.cc
References fCurrentTouchableHandle, fGeometryLimitedStep, fLinearNavigator, fParticleChange, fStopAndKill, G4VPhysicalVolume::GetLogicalVolume(), G4MaterialCutsCouple::GetMaterial(), G4LogicalVolume::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4LogicalVolume::GetMaterialCutsCouple(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4MaterialCutsCouple::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4LogicalVolume::GetSensitiveDetector(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), G4VTouchable::GetVolume(), G4Navigator::LocateGlobalPointWithinVolume(), G4VParticleChange::ProposeTrackStatus(), G4Navigator::SetGeometricallyLimitedStep(), G4ParticleChangeForTransport::SetMaterialCutsCoupleInTouchable(), G4ParticleChangeForTransport::SetMaterialInTouchable(), G4ParticleChangeForTransport::SetSensitiveDetectorInTouchable(), G4ParticleChangeForTransport::SetTouchableHandle(), and true.
G4double G4MonopoleTransportation::PostStepGetPhysicalInteractionLength (const G4Track & , G4double previousStepSize, G4ForceCondition * pForceCond) virtual
Implements G4VProcess.
Definition at line 539 of file G4MonopoleTransportation.cc.
View newest version in sPHENIX GitHub at line 539 of file G4MonopoleTransportation.cc
References DBL_MAX, and Forced.
void G4MonopoleTransportation::ResetKilledStatistics (G4int report = 1) inline
void G4MonopoleTransportation::SetPropagatorInField (G4PropagatorInField * pFieldPropagator)
void G4MonopoleTransportation::SetThresholdImportantEnergy (G4double newEnImp) inline
void G4MonopoleTransportation::SetThresholdTrials (G4int newMaxTrials) inline
void G4MonopoleTransportation::SetThresholdWarningEnergy (G4double newEnWarn) inline
void G4MonopoleTransportation::StartTracking (G4Track * aTrack) virtual
Reimplemented from G4VProcess.
Definition at line 653 of file G4MonopoleTransportation.cc.
View newest version in sPHENIX GitHub at line 653 of file G4MonopoleTransportation.cc
References G4FieldManagerStore::ClearAllChordFindersState(), G4PropagatorInField::ClearPropagatorState(), DoesGlobalFieldExist(), fCurrentTouchableHandle, fFieldPropagator, fNoLooperTrials, fPreviousSafety, fPreviousSftOrigin, G4FieldManagerStore::GetInstance(), G4Track::GetTouchableHandle(), and G4VProcess::StartTracking().
Member Data Documentation
G4double G4MonopoleTransportation::endpointDistance private
Definition at line 184 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 184 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4double G4MonopoleTransportation::fCandidateEndGlobalTime private
Definition at line 167 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 167 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and G4MonopoleTransportation().
G4TouchableHandle G4MonopoleTransportation::fCurrentTouchableHandle private
Definition at line 172 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 172 of file G4MonopoleTransportation.hh
Referenced by G4MonopoleTransportation(), PostStepDoIt(), and StartTracking().
G4bool G4MonopoleTransportation::fEndGlobalTimeComputed private
Definition at line 166 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 166 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and G4MonopoleTransportation().
G4PropagatorInField* G4MonopoleTransportation::fFieldPropagator private
Definition at line 157 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 157 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation(), and StartTracking().
G4bool G4MonopoleTransportation::fGeometryLimitedStep private
Definition at line 174 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 174 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and PostStepDoIt().
G4Navigator* G4MonopoleTransportation::fLinearNavigator private
Definition at line 156 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 156 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation(), and PostStepDoIt().
G4MonopoleFieldSetup* G4MonopoleTransportation::fMagSetup private
Definition at line 154 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 154 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation(), and GetZmagFieldValue().
G4double G4MonopoleTransportation::fMaxEnergyKilled private
Definition at line 201 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 201 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and ~G4MonopoleTransportation().
G4bool G4MonopoleTransportation::fMomentumChanged private
Definition at line 164 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 164 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4int G4MonopoleTransportation::fNoLooperTrials private
Definition at line 198 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 198 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and StartTracking().
G4ParticleChangeForTransport G4MonopoleTransportation::fParticleChange private
Definition at line 181 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 181 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and PostStepDoIt().
const G4Monopole* G4MonopoleTransportation::fParticleDef private
Definition at line 152 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 152 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4bool G4MonopoleTransportation::fParticleIsLooping private
Definition at line 170 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 170 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4double G4MonopoleTransportation::fPreviousSafety private
Definition at line 178 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 178 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4ThreeVector G4MonopoleTransportation::fPreviousSftOrigin private
Definition at line 177 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 177 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4SafetyHelper* G4MonopoleTransportation::fpSafetyHelper private
Definition at line 207 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 207 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and G4MonopoleTransportation().
G4bool G4MonopoleTransportation::fShortStepOptimisation private
Definition at line 205 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 205 of file G4MonopoleTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4double G4MonopoleTransportation::fSumEnergyKilled private
Definition at line 200 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 200 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and ~G4MonopoleTransportation().
G4double G4MonopoleTransportation::fThreshold_Important_Energy private
Definition at line 189 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 189 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt().
G4double G4MonopoleTransportation::fThreshold_Warning_Energy private
Definition at line 188 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 188 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt().
G4int G4MonopoleTransportation::fThresholdTrials private
Definition at line 190 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 190 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt().
G4double G4MonopoleTransportation::fTransportEndKineticEnergy private
Definition at line 162 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 162 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4ThreeVector G4MonopoleTransportation::fTransportEndMomentumDir private
Definition at line 161 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 161 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4ThreeVector G4MonopoleTransportation::fTransportEndPosition private
Definition at line 160 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 160 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4ThreeVector G4MonopoleTransportation::fTransportEndSpin private
Definition at line 163 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 163 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt(), and AlongStepGetPhysicalInteractionLength().
G4int G4MonopoleTransportation::noCalls private
Definition at line 208 of file G4MonopoleTransportation.hh.
View newest version in sPHENIX GitHub at line 208 of file G4MonopoleTransportation.hh
Referenced by AlongStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/include/G4MonopoleTransportation.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/src/G4MonopoleTransportation.cc