ECCE @ EIC Software: G4LineSection Class Reference
G4LineSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4LineSection.hh>
Public Member Functions
G4LineSection (const G4ThreeVector &PntA, const G4ThreeVector &PntB)
G4double Dist (G4ThreeVector OtherPnt) const
G4double GetABdistanceSq () const
Static Public Member Functions
static G4double Distline (const G4ThreeVector &OtherPnt, const G4ThreeVector &LinePntA, const G4ThreeVector &LinePntB)
Private Attributes
G4ThreeVector EndpointA
G4ThreeVector VecAtoB
G4double fABdistanceSq = 0.0
Detailed Description
Definition at line 42 of file G4LineSection.hh.
View newest version in sPHENIX GitHub at line 42 of file G4LineSection.hh
Constructor & Destructor Documentation
G4LineSection::G4LineSection (const G4ThreeVector & PntA, const G4ThreeVector & PntB)
Definition at line 33 of file G4LineSection.cc.
View newest version in sPHENIX GitHub at line 33 of file G4LineSection.cc
References fABdistanceSq, CLHEP::Hep3Vector::mag2(), and VecAtoB.
Member Function Documentation
G4double G4LineSection::Dist (G4ThreeVector OtherPnt) const
Definition at line 40 of file G4LineSection.cc.
View newest version in sPHENIX GitHub at line 40 of file G4LineSection.cc
References CLHEP::Hep3Vector::dot(), EndpointA, fABdistanceSq, CLHEP::Hep3Vector::mag2(), and VecAtoB.
Referenced by Distline().
G4double G4LineSection::Distline (const G4ThreeVector & OtherPnt, const G4ThreeVector & LinePntA, const G4ThreeVector & LinePntB) inline static
Definition at line 72 of file G4LineSection.hh.
View newest version in sPHENIX GitHub at line 72 of file G4LineSection.hh
References Dist().
Referenced by G4DormandPrinceRK56::DistChord(), G4RKG3_Stepper::DistChord(), G4CashKarpRKF45::DistChord(), G4DormandPrinceRK78::DistChord(), G4ConstRK4::DistChord(), G4FSALBogackiShampine45::DistChord(), G4RK547FEq3::DistChord(), G4RK547FEq1::DistChord(), G4RK547FEq2::DistChord(), G4MagErrorStepper::DistChord(), G4NystromRK4::DistChord(), G4BogackiShampine23::DistChord(), G4DormandPrince745::DistChord(), G4FSALDormandPrince745::DistChord(), G4TsitourasRK45::DistChord(), G4DoLoMcPriRK34::DistChord(), and G4BogackiShampine45::DistChord().
G4double G4LineSection::GetABdistanceSq () const inline
Definition at line 66 of file G4LineSection.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LineSection.hh
References fABdistanceSq.
Member Data Documentation
G4ThreeVector G4LineSection::EndpointA private
Definition at line 58 of file G4LineSection.hh.
View newest version in sPHENIX GitHub at line 58 of file G4LineSection.hh
Referenced by Dist().
G4double G4LineSection::fABdistanceSq = 0.0 private
Definition at line 60 of file G4LineSection.hh.
View newest version in sPHENIX GitHub at line 60 of file G4LineSection.hh
Referenced by Dist(), G4LineSection(), and GetABdistanceSq().
G4ThreeVector G4LineSection::VecAtoB private
Definition at line 59 of file G4LineSection.hh.
View newest version in sPHENIX GitHub at line 59 of file G4LineSection.hh
Referenced by Dist(), and G4LineSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4LineSection.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4LineSection.cc