ECCE @ EIC Software: G4AuxiliaryNavServices Class Reference
G4AuxiliaryNavServices Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4AuxiliaryNavServices.hh>
Static Public Member Functions
static G4bool CheckPointOnSurface (const G4VSolid *sampleSolid, const G4ThreeVector &localPoint, const G4ThreeVector *globalDirection, const G4AffineTransform &sampleTransform, const G4bool locatedOnEdge)
static G4bool CheckPointExiting (const G4VSolid *sampleSolid, const G4ThreeVector &localPoint, const G4ThreeVector *globalDirection, const G4AffineTransform &sampleTransform)
static void ReportTolerances ()
Detailed Description
Definition at line 43 of file G4AuxiliaryNavServices.hh.
View newest version in sPHENIX GitHub at line 43 of file G4AuxiliaryNavServices.hh
Member Function Documentation
static G4bool G4AuxiliaryNavServices::CheckPointExiting (const G4VSolid * sampleSolid, const G4ThreeVector & localPoint, const G4ThreeVector * globalDirection, const G4AffineTransform & sampleTransform) static
static G4bool G4AuxiliaryNavServices::CheckPointOnSurface (const G4VSolid * sampleSolid, const G4ThreeVector & localPoint, const G4ThreeVector * globalDirection, const G4AffineTransform & sampleTransform, const G4bool locatedOnEdge) static
Referenced by G4ParameterisedNavigation::LevelLocate().
void G4AuxiliaryNavServices::ReportTolerances () static
Definition at line 39 of file G4AuxiliaryNavServices.cc.
View newest version in sPHENIX GitHub at line 39 of file G4AuxiliaryNavServices.cc
References G4cout, G4endl, G4GeometryTolerance::GetAngularTolerance(), G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetRadialTolerance(), and G4GeometryTolerance::GetSurfaceTolerance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4AuxiliaryNavServices.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4AuxiliaryNavServices.cc