ECCE @ EIC Software: B03PVolumeStore Class Reference
B03PVolumeStore Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/include/B03PVolumeStore.hh>
Public Member Functions
B03PVolumeStore ()
~B03PVolumeStore ()
void AddPVolume (const G4GeometryCell &cell)
const G4VPhysicalVolume * GetPVolume (const G4String &name) const
G4String GetPNames () const
Private Attributes
B03SetGeometryCell fSetGeometryCell
Detailed Description
Definition at line 52 of file B03PVolumeStore.hh.
View newest version in sPHENIX GitHub at line 52 of file B03PVolumeStore.hh
Constructor & Destructor Documentation
B03PVolumeStore::B03PVolumeStore ()
Definition at line 46 of file B03PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 46 of file B03PVolumeStore.cc
B03PVolumeStore::~B03PVolumeStore ()
Definition at line 50 of file B03PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 50 of file B03PVolumeStore.cc
Member Function Documentation
void B03PVolumeStore::AddPVolume (const G4GeometryCell & cell)
Definition at line 54 of file B03PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 54 of file B03PVolumeStore.cc
References fSetGeometryCell, G4cout, G4endl, and it.
Referenced by B03ImportanceDetectorConstruction::Construct().
G4String B03PVolumeStore::GetPNames () const
Definition at line 90 of file B03PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 90 of file B03PVolumeStore.cc
References fSetGeometryCell, G4VPhysicalVolume::GetName(), and it.
Referenced by B03ImportanceDetectorConstruction::ListPhysNamesAsG4String().
const G4VPhysicalVolume * B03PVolumeStore::GetPVolume (const G4String & name) const
Definition at line 72 of file B03PVolumeStore.cc.
View newest version in sPHENIX GitHub at line 72 of file B03PVolumeStore.cc
References fSetGeometryCell, G4cout, G4endl, G4VPhysicalVolume::GetName(), and it.
Referenced by B03ImportanceDetectorConstruction::GetGeometryCell(), and B03ImportanceDetectorConstruction::GetPhysicalVolumeByName().
Member Data Documentation
B03SetGeometryCell B03PVolumeStore::fSetGeometryCell private
Definition at line 62 of file B03PVolumeStore.hh.
View newest version in sPHENIX GitHub at line 62 of file B03PVolumeStore.hh
Referenced by AddPVolume(), GetPNames(), and GetPVolume().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/include/B03PVolumeStore.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/src/B03PVolumeStore.cc