ECCE @ EIC Software: kdfinder Namespace Reference
kdfinder Namespace Reference
Classes
class TVector
class Helix
class Data
struct Circle
struct Line
class CircleFit
class LinearFit
struct KDPointCloud
struct KDTriplet
class TrackCandidate
Functions
template<typename T >
T rnd_gauss (T mean, T stddev)
template<class T >
T abs (const TVector< T > &v)
template<class T >
TVector< T > cross_product (const TVector< T > &v1, const TVector< T > &v2)
template<class T >
TVector< T > operator+ (const TVector< T > &v1, const TVector< T > &v2)
template<class T >
TVector< T > operator- (const TVector< T > &v1, const TVector< T > &v2)
template<class T >
T operator* (const TVector< T > &v1, const TVector< T > &v2)
template<class T >
TVector< T > operator* (const TVector< T > &v, double c)
template<class T >
TVector< T > operator* (T c, const TVector< T > &v)
template<class T >
TVector< T > operator/ (const TVector< T > &v, double c)
template<typename T >
T DistanceToCircle (Circle< T > *circle, T x, T y)
template<typename T >
T DistanceToCircle (T a, T b, T r, T x, T y)
template<typename T >
T DistanceToLine (T a, T b, T x, T y)
template<typename T >
bool pointsort (std::vector< T > a, std::vector< T > b)
template<typename T >
bool tripletsort (KDTriplet< T > a, KDTriplet< T > b)
template<typename T >
T angle_between_vectors (T x1, T y1, T z1, T x2, T y2, T z2)
template<typename T >
void make_triplets (size_t triplet_begin, size_t triplet_end, std::vector< std::vector< double >> &hits, nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< T, KDPointCloud< T >>, KDPointCloud< T >, 3 > &index, std::vector< std::vector< KDTriplet< T >>> &triplets, T search_radius=10, T search_angle=M_PI/8)
template<typename T >
std::vector< std::vector
< std::vector< T > > > find_tracks (std::vector< std::vector< T >> &points, std::vector< std::vector< T >> &unused_hits, T search_radius=10, T search_angle=M_PI/8, size_t min_track_size=10, size_t nthreads=1, bool stats=false)
template<typename T >
std::vector< std::vector
< std::vector< T > > > find_tracks_iterative (std::vector< std::vector< T >> &hits, std::vector< std::vector< T >> &unused_hits, T search_radius1=10, T search_angle1=M_PI/8, size_t min_track_size1=10, T search_radius2=12, T search_angle2=M_PI/8, size_t min_track_size2=6, size_t nthreads=1, bool stats=false)
template<typename T >
std::vector< TrackCandidate< T > * > get_track_candidates (std::vector< std::vector< std::vector< T >>> &tracks, T B, bool stats=false)
template<typename T >
bool candidatesort (const TrackCandidate< T > *a, const TrackCandidate< T > *b)
template<typename T >
bool candidatesortradius (const TrackCandidate< T > *a, const TrackCandidate< T > *b)
template<typename T >
bool ismergedcandidate (const TrackCandidate< T > *o)
template<typename T >
std::vector< TrackCandidate< T > * > merge_track_candidates (std::vector< TrackCandidate< T > * > &candidates, T c_tanl=5.0, T c_xy=5.0, T c_dist=60.0, bool stats=false)
template<typename T >
bool elementsort (const std::tuple< T, Helix< T > *, size_t > a, const std::tuple< T, Helix< T > *, size_t > b)
template<typename T >
bool vertexsort (const std::pair< std::vector< T >, std::vector< size_t >> a, const std::pair< std::vector< T >, std::vector< size_t >> b)
template<typename T >
std::vector< std::pair
< std::vector< T >
, std::vector< size_t > > > find_vertex_seeds (std::vector< TrackCandidate< T > * > &candidates, T x0=0, T y0=0, T c_z_dist=0.5, T c_xy_dist=2.0, T c_min_tracks=3, bool stats=false)
template<typename T >
size_t get_track_color (T pt)
template<typename T >
std::string export_candidates_json (std::vector< TrackCandidate< T > * > &candidates, std::vector< std::vector< T >> &hits, size_t run=0, size_t event_number=0, size_t evt_time=0, double B=-0.5)
template<typename T >
std::string export_json (std::vector< std::vector< std::vector< T >>> &tracks, std::vector< std::vector< T >> &hits, size_t run=0, size_t event_number=0, size_t evt_time=0, double B=-0.5)
template<typename T >
std::string export_candidates_json_old (std::vector< TrackCandidate< T > * > &candidates, std::vector< ulong > &trigger_ids, size_t run=0, size_t event_number=0, size_t evt_time=0, T B=-0.5, bool round=false)
Function Documentation
template<class T > T kdfinder::abs (const TVector< T > & v) inline
Definition at line 393 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 393 of file kdfinder.hpp
References kdfinder::TVector< T >::mag().
Referenced by EmcCluster::ABS(), nanoflann::L1_Adaptor< T, DataSource, _DistanceType >::accum_dist(), G4INCLXXInterface::AccurateProjectile(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::addCompatibleTracksToVertex(), AllSi_Al_support_Detector::addDetectorSection(), G4Material::AddElement(), F04FocusSolenoid::AddFieldValue(), HistoManager::AddLeakingParticle(), G4Material::AddMaterial(), Run::AddMscProjTheta(), PHG4InEvent::AddVtxCommon(), G4ParticleHPFinalState::adjust_final_state(), G4VIntersectionLocator::AdjustmentOfFoundIntersection(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), G4MagHelicalStepper::AdvanceHelix(), G4NuclearStopping::AlongStepDoIt(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), G4Abla::AMOMENT(), G4GHEKinematicsVector::Ang(), G4ReactionProduct::Angle(), G4VXTRenergyLoss::AngleXTRdEdx(), PHSartreParticleTrigger::Apply(), PHPy8JetTrigger::Apply(), PHPy6JetTrigger::Apply(), PHPy8ParticleTrigger::Apply(), PHPy6ForwardElectronTrig::Apply(), PHPy6ParticleTrigger::Apply(), G4INCL::Nucleus::applyFinalState(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LFission::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ChordFinder::ApproxCurvePointS(), Acts::Test::approximatelyEqual(), G4Box::ApproxSurfaceNormal(), G4EllipticalTube::ApproxSurfaceNormal(), G4Ellipsoid::ApproxSurfaceNormal(), G4Trd::ApproxSurfaceNormal(), G4EllipticalCone::ApproxSurfaceNormal(), G4Para::ApproxSurfaceNormal(), G4Trap::ApproxSurfaceNormal(), ODDModuleHelper::assembleRectangularModule(), CLHEP::HepRotation::axis(), Acts::SolenoidBField::B_r(), Acts::SolenoidBField::B_z(), kdfinder::Helix< T >::bad(), G4HadronBuilder::Barion(), G4ParticleHPInelasticBaseFS::BaseApply(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), G4ReflectedSolid::BoundingLimits(), Acts::detail::boundState(), Acts::AtlasStepper< ConstantBField >::boundState(), G4StatMF::BreakItUp(), G4WilsonAblationModel::BreakItUp(), PHG4mRICHDetector::build_mRICH_wall_eside_proj(), G4Voxelizer::BuildBoundaries(), buildEndcapRouting(), PHG4TTLDetector::BuildForwardTTL(), G4QGSParticipants::BuildInteractions(), Acts::TGeoLayerBuilder::buildLayers(), KFParticle_Tools::buildMother(), G4SmartVoxelHeader::BuildNodes(), G4CrossSectionElastic::BuildPhysicsTable(), G4CrossSectionInelastic::BuildPhysicsTable(), Acts::CylinderVolumeBounds::buildSurfaceBounds(), KFParticle_DST::buildSvtxTrack(), AnnularFieldSim::calc_unit_field(), G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4StatMFFragment::CalcExcitationEnergy(), G4StatMFMicroPartition::CalcPartitionTemperature(), G4StatMFMacroTemperature::CalcTemperature(), G4hhElastic::CalculateBqQ123(), G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), KFParticle_Tools::calculateEllipsoidRadius(), KFParticle_Tools::calculateEllipsoidVolume(), G4MuonVDNuclearModel::CalculateEMVertex(), G4TessellatedSolid::CalculateExtent(), G4RPGInelastic::CalculateMomenta(), G4DiffuseElasticV2::CalculateNuclearRad(), G4DiffuseElastic::CalculateNuclearRad(), G4OpBoundaryProcess::CalculateReflectivity(), PHTpcResiduals::calculateTpcResiduals(), G4DNAPTBAugerModel::CalculAugerEnergyFor(), G4QMDCollision::CalFinalStateOfTheBinaryCollision(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDMeanField::CalGraduate(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4ConvergenceTester::calStat(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::canRecoverFromNoCompatibleTracks(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::canRemoveNonCompatibleTrackFromSeedTracks(), G4RPGAntiProtonInelastic::Cascade(), CellParameterisation::CellParameterisation(), Acts::DD4hepLayerBuilder::centralLayers(), CylinderGeomMicromegas::check_radius(), Acts::Test::checkCloseCovariance(), Acts::ConeBounds::checkConsistency(), Acts::AnnulusBounds::checkConsistency(), G4Tet::CheckDegeneracy(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4CascadeInterface::checkFinalResult(), G4PDGCodeChecker::CheckForBaryons(), G4PDGCodeChecker::CheckForNuclei(), G4PDGCodeChecker::CheckForQuarks(), DecayFinder::checkIfCorrectParticle(), G4FastStep::CheckIt(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), GPUTPCTrackParam::CheckNumericalQuality(), G4HadronicProcess::CheckResult(), G4ReflectionFactory::CheckScale(), Acts::BinningData::checkSubStructure(), Rossegger::CheckZeroes(), G4StatMFMacroCanonical::ChooseA(), G4DiffractiveSplitableHadron::ChooseStringEnds(), G4StatMFMicroPartition::ChooseZ(), G4StatMFMacroCanonical::ChooseZ(), G4Nucleus::Cinema(), kdfinder::CircleFit< T >::CircleFitByChernovHoussam(), kdfinder::CircleFit< T >::CircleFitByHyper(), kdfinder::CircleFit< T >::CircleFitByPratt(), kdfinder::CircleFit< T >::CircleFitByTaubin(), PHSiliconTpcTrackMatching::cleanVertexMap(), G4BoundingEnvelope::ClipEdgesByVoxel(), Acts::Test::float_compare_internal::closeAbs(), Acts::Test::float_compare_internal::closeOrSmall(), G4FermiFragmentsPoolVI::ClosestChannels(), RawClusterBuilderkV3::cluster(), G4JpegCoder::CodeHuffman(), G4ParticleHPInelasticCompFS::CompositeApply(), G4ChatterjeeCrossSection::ComputeCrossSection(), G4KalbachCrossSection::ComputeCrossSection(), G4RToEConvForGamma::ComputeCrossSection(), G4ICRU49NuclearStoppingModel::ComputeDEDXPerVolume(), G4DensityEffectCalculator::ComputeDensityCorrection(), G4IonisParamMat::ComputeDensityEffectParameters(), Acts::BoundaryCheck::computeEuclideanClosestPointOnRectangle(), DetectorConstruction::ComputeGeomParameters(), G4SandiaTable::ComputeMatSandiaMatrix(), RunAction::ComputeMscHighland(), Run::ComputeMscHighland(), Acts::computeMultipleScatteringTheta0(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), EventAction::ComputeStrandBreaks(), G4UrbanMscModel::ComputeTheta0(), G4UrbanAdjointMscModel::ComputeTheta0(), Acts::IntegrationTest::constant_field_propagation(), Acts::GenericCuboidVolumeBounds::construct(), Acts::TGeoDetectorElement::construct(), PHG4Sector::PHG4SectorConstructor::Construct_Sectors(), G4tgbVolume::ConstructG4PhysVol(), CCalG4Ecal::constructGlobal(), PHG4ForwardDualReadoutDetector::ConstructMe(), PHG4BarrelEcalDetector::ConstructMe(), G4GenericBiasingPhysics::ConstructProcess(), PHG4BarrelEcalDetector::ConstructTower(), GPUTPCTrackParam::CorrectForMeanMaterial(), FW::TruthVerticesToTracksAlgorithm::correctPhiThetaPeriodicity(), CLHEP::correctPsiPhi(), G4BinaryCascade::CorrectShortlivedFinalsForFermi(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4GHEKinematicsVector::CosAng(), G4Pythia6Decayer::CountProducts(), Acts::AtlasStepper< ConstantBField >::covarianceTransport(), Acts::AnnulusBounds::coversFullAzimuth(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), create_element(), Acts::CylinderVolumeHelper::createContainerTrackingVolume(), DNAParser::CreateCutSolid(), Acts::CylinderVolumeHelper::createCylinderLayer(), Acts::CylinderVolumeHelper::createDiscLayer(), Acts::CylinderVolumeHelper::createGapTrackingVolume(), Acts::IntegrationTest::createPlanarTransform(), Acts::Test::createPlanarTransform(), G4GenericPolycone::CreatePolyhedron(), G4VTwistedFaceted::CreatePolyhedron(), G4Polyhedra::CreatePolyhedron(), G4TwistedTubs::CreatePolyhedron(), Acts::Seedfinder< external_spacepoint_t >::createSeedsForGroup(), Acts::detail::VerticesHelper::createSegment(), Acts::CartesianSegmentation::createSegmentationSurfaces(), G4DiffractiveExcitation::CreateStrings(), Acts::CylinderVolumeHelper::createTrackingVolume(), RunAction::CriticalEnergy(), G4AdjointCrossSurfChecker::CrossingASphere(), G4BFieldIntegrationDriver::CurvatureRadius(), kdfinder::Helix< T >::curvatureSignedDistance(), Acts::detail::curvilinearState(), Acts::AtlasStepper< ConstantBField >::curvilinearState(), Acts::LayerCreator::cylinderLayer(), G4BinaryCascade::DebugApplyCollisionFail(), G4BinaryCascade::DebugEpConservation(), G4BinaryCascade::DebugFinalEpConservation(), G4Abla::DeexcitationAblaxx(), G4RPGReaction::Defs1(), G4GHEKinematicsVector::Defs1(), G4INCL::CrossSectionsINCL46::deltaProduction(), G4QGSParticipants::DeterminePartonMomenta(), G4OpBoundaryProcess::DielectricDielectric(), G4DiffractiveSplitableHadron::Diquark(), G4LundStringFragmentation::Diquark_AntiDiquark_aboveThreshold_lastSplitting(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), G4Abla::direct(), Acts::LayerCreator::discLayer(), G4GeomTools::DiskExtent(), kdfinder::Helix< T >::distance(), Acts::EllipseBounds::distanceToBoundary(), Acts::AnnulusBounds::distanceToBoundary(), G4MultiUnion::DistanceToIn(), G4EllipticalTube::DistanceToIn(), G4Box::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4Trd::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4Torus::DistanceToIn(), G4Para::DistanceToIn(), G4Trap::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Box::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Trd::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4Para::DistanceToOut(), G4Trap::DistanceToOut(), G4ProjectileFragmentCrossSection::doit(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), G4PathFinder::DoNextCurvedStep(), G4ITPathFinder::DoNextCurvedStep(), LXeTrajectory::DrawTrajectory(), G4Abla::DSIGN(), G3Division::Dvn2(), G3Division::Dvt(), G3Division::Dvt2(), G4Abla::eflmac(), kdfinder::CircleFit< T >::eigen2x2(), G4CascadeCheckBalance::ekinOkay(), G4INCL::CrossSectionsINCL46::elasticNNLegacy(), G4GeomTools::EllipsePerimeter(), G4GeomTools::EllipticConeLateralArea(), Acts::detail::VerticesHelper::ellispoidVertices(), LiteCaloEval::End(), Acts::DD4hepLayerBuilder::endcapLayers(), HistoManager::EndOfEvent(), Run::EndOfRun(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4CascadeCheckBalance::energyOkay(), Acts::detail::ensureThetaBounds(), G4RKFieldIntegrator::Erf(), CLHEP::HepStat::erfQ(), Acts::CylinderVolumeHelper::estimateAndCheckDimension(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), DSTEmulator::evaluate_tracks(), TrackEvaluation::evaluate_tracks(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), FW::TrackSelector::execute(), FW::ParticleSmearing::execute(), FW::ParticleSelector::execute(), Acts::PropagatorOptions< action_list_t, aborter_list_t >::extend(), PerspectiveVisAction::ExtendedDraw(), Acts::Polyhedron::extent(), TpcSpaceChargeReconstructionHelper::extrapolate_phi1(), Acts::fieldMapperRZ(), Acts::fieldMapperXYZ(), KFParticle_nTuple::fillBranch(), Analysis::FillDose(), G4INCL::Nucleus::fillEventInfo(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4CascadeRecoilMaker::fillRecoil(), G4HadronicProcess::FillResult(), G4BinaryCascade::FillVoidNucleusProducts(), GPUTPCTrackParam::Filter(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed(), G4VScatteringCollision::FinalState(), Acts::ZScanVertexFinder< vfitter_t >::find(), CylinderGeomMicromegas::find_strip_from_local_coords(), CylinderGeomMicromegas::find_tile_cylindrical(), CylinderGeomMicromegas::find_tile_planar(), DecayFinder::findDecay(), G4SPBaryon::FindDiquark(), HepPolyhedron::FindNeighbour(), G4NuclearPolarizationStore::FindOrBuild(), G4SPBaryon::FindQuark(), G4StatMF::FindTemperatureOfBreakingChannel(), G4IntraNucleiCascader::finishCascade(), G4Abla::fissionDistri(), G4ExcitedStringDecay::FragmentStrings(), BEmcRec::fTowerDist(), Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), G3CalcParamsFn(), G3fillParams(), G4BetaDecayCorrections::G4BetaDecayCorrections(), G4InuclSpecialFunctions::G4cbrt(), PHTruthClustering::G4ClusterSize(), SvtxTruthEval::G4ClusterSize(), G4ConcreteNNToDeltaDeltastar::G4ConcreteNNToDeltaDeltastar(), G4DNAIons::G4DNAIons(), G4DynamicParticle::G4DynamicParticle(), G4Element::G4Element(), G4gsmixt(), G4gsrotm(), G4IntersectingCone::G4IntersectingCone(), G4Ions::G4Ions(), G4mplIonisationModel::G4mplIonisationModel(), G4mplIonisationWithDeltaModel::G4mplIonisationWithDeltaModel(), G4Para::G4Para(), G4ParticleDefinition::G4ParticleDefinition(), G4Parton::G4Parton(), G4RandomPointOnEllipse(), G4RandomPointOnEllipsoid(), G4Reggeons::G4Reggeons(), G4Tet::G4Tet(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnABoxBoundary(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), G4PhotonEvaporation::GenerateGamma(), G4PolarizationTransition::GenerateGammaCosTheta(), G4PolarizationTransition::GenerateGammaPhi(), G4Clebsch::GenerateIso3(), STCyclotronPrimaryGeneratorAction::GeneratePrimaries(), RawClusterBuilderTopo::get_adjacent_towers_by_ID(), TruthJetInput::get_input(), PHG4Sector::Sector_Geometry::get_max_R(), PHGenFitTrkFitter::get_rotation_matrix(), PHGenFitTrkFitter::get_vertex_error_uvn(), G4KineticTrack::GetActualMass(), G4VXTRenergyLoss::GetAngleVector(), G4VDecayChannel::GetAngularMomentum(), G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), GPUTPCTrackParam::GetDCAPoint(), G4PDGCodeChecker::GetDigits(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getDistanceAndMomentum(), EmcCluster::GetE9(), G4PhotonEvaporation::GetEmissionProbability(), RunAction::GetEnergyFromCSDARange(), RunAction::GetEnergyFromRestrictedRange(), G4NuclNuclDiffuseElastic::GetErfComp(), ECCEhpDIRCFastPIDMap::getFastSmearLogLikelihood(), ECCEmRICHFastPIDMap::getFastSmearLogLikelihood(), ECCEdRICHFastPIDMap::getFastSmearLogLikelihood(), H02Field::GetFieldValue(), ExN04Field::GetFieldValue(), RE05Field::GetFieldValue(), RE01Field::GetFieldValue(), EMField::GetFieldValue(), G4OpenGLFontBaseStore::GetFontInfo(), G4PhotoNuclearCrossSection::GetFunctions(), G4ElectroNuclearCrossSection::GetFunctions(), G4EnergyRangeManager::GetHadronicInteraction(), KFParticle_truthAndDetTools::getHepMCInfo(), G4INCL::ParticleTable::getINCLMass(), G4ComponentAntiNuclNuclearXS::GetInelasticElementCrossSection(), G4ParticleHPKallbachMannSyst::GetKallbachZero(), G4LundStringFragmentation::GetLightConeZ(), G4QGSMFragmentation::GetLightConeZ(), G4ElasticHadrNucleusHE::GetLightFq2(), ALICEKF::GetLineClusterResiduals(), G4ParameterisationPolyconeZ::GetMaxParameter(), G4ParameterisationPolyhedraZ::GetMaxParameter(), G4FTFParameters::GetMinMass(), G4MuonicAtomHelper::GetMuonCaptureRate(), G4MuonMinusBoundDecay::GetMuonCaptureRate(), HepPolyhedron::GetNextEdgeIndices(), HepPolyhedron::GetNextVertexIndex(), HepPolyhedron::GetNormal(), PHHepMCParticleSelectorDecayProductChain::GetParent(), G4CascadParticle::getPathToTheNextZone(), G4ParticleHPPhotonDist::GetPhotons(), G4QMDMeanField::GetPotential(), BEmcProfile::GetProb(), G4SPBaryon::GetProbability(), G4ElasticHadrNucleusHE::GetQ2_2(), G4NuclNuclDiffuseElastic::GetRatioGen(), G4INCL::ParticleTable::getRealMass(), GPUTPCTrackParam::GetS(), G4ScreeningMottCrossSection::GetScatteringAngle(), PHActsTrackProjection::getSquareTowerEnergies(), AnnularFieldSim::GetStepDistortion(), EmcCluster::GetSubClusters(), HepPolyhedron::GetSurfaceArea(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4ComponentAntiNuclNuclearXS::GetTotalElementCrossSection(), G4ReactionProduct::GetTotalMomentum(), G4QMDMeanField::GetTotalPotential(), HepPolyhedron::GetUnitNormal(), G4QGSMSplitableHadron::GetValenceQuarkFlavors(), HepPolyhedron::GetVolume(), G4ParticleHPVector::GetXsec(), G4ParticleHPJENDLHEData::getXSfromThisIsotope(), Acts::ConeSurface::globalToLocal(), Acts::CylinderSurface::globalToLocal(), Acts::CylinderVolumeHelper::glueTrackingVolumes(), kdfinder::CircleFit< T >::GradientHessian(), G4ElasticHadrNucleusHE::HadrNucDifferCrSec(), G4HadronNucleonXsc::HadronNucleonXsc(), G4HadronNucleonXsc::HadronNucleonXscVU(), G4ElasticHadrNucleusHE::HadronProtonQ2(), G4ParticleHPChannel::Harmonise(), kdfinder::Helix< T >::Helix(), CLHEP::HepJamesRandom::HepJamesRandom(), HepPolyhedronCons::HepPolyhedronCons(), HepPolyhedronParaboloid::HepPolyhedronParaboloid(), G4Bessel::I0(), G4Bessel::I1(), G4Pythia6Decayer::ImportDecayProducts(), Acts::RiddersPropagator< propagator_t >::inconsistentDerivativesOnDisc(), PHPythia6::Init(), G4ParticleHPFFFissionFS::Init(), G4ParticleHPCaptureFS::Init(), G4ParticleHPDeExGammas::Init(), G4ParticleHPFissionBaseFS::Init(), G4FTFModel::Init(), G4ParticleHPElasticFS::Init(), G4ParticleHPIsoData::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), G4FTFParameters::InitForInteraction(), G4NeutronElectronElXsc::Initialise(), G4VMscModel::InitialiseParameters(), G4Tet::Initialize(), G4WendtFissionFragmentGenerator::InitializeANucleus(), G4DNAModelInterface::InsertModelInTable(), Acts::GenericCuboidVolumeBounds::inside(), G4EllipticalTube::Inside(), Acts::CutoutCylinderVolumeBounds::inside(), G4Box::Inside(), Acts::CuboidVolumeBounds::inside(), G4Ellipsoid::Inside(), G4Trd::Inside(), Acts::TrapezoidVolumeBounds::inside(), G4EllipticalCone::Inside(), G4Para::Inside(), Acts::CylinderVolumeBounds::inside(), G4Trap::Inside(), Acts::CylinderBounds::inside3D(), G4ParticleHPVector::Integrate(), G4ParticleHPVector::IntegrateAndNormalise(), G4VEmissionProbability::IntegrateProbability(), G4UPiNuclearCrossSection::Interpolate(), G4alphaIonisation::IsApplicable(), G4ParticleHPVector::IsBlocked(), G4GeomTools::IsConvex(), G4Abla::ISIGN(), G4FermiFragmentsPoolVI::IsInThePool(), G4LundStringFragmentation::IsItFragmentable(), Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::isMergedVertex(), HepGeom::Transform3D::isNear(), Acts::SurfaceArrayCreator::isSurfaceEquivalent(), Acts::BoundaryCheck::isTolerated(), BEmcRec::iTowerDist(), G4INCL::NKbToSpiChannel::KaonMomentum(), Acts::LayerArrayCreator::layerArray(), Acts::HelicalTrackLinearizer< propagator_t, propagator_options_t >::linearizeTrack(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4FissionParameters::LocalExp(), G4CompetitiveFission::LocalExp(), main(), QAG4SimulationKFParticle::makeHepLV(), G4Trap::MakePlane(), G4Trap::MakePlanes(), G4ParticleHPVector::Merge(), G4HadronBuilder::Meson(), G4Voxelizer::MinDistanceToBox(), FW::Generic::modulePositionsCylinder(), Acts::Test::CylindricalTrackingGeometry::modulePositionsCylinder(), Acts::AtlasStepper< ConstantBField >::momentum(), G4CascadeCheckBalance::momentumOkay(), CLHEP::MTwistEngine::MTwistEngine(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaLK(), G4INCL::CrossSectionsStrangeness::NDeltaToDeltaSK(), G4INCL::CrossSectionsStrangeness::NDeltaToNLK(), G4INCL::CrossSectionsStrangeness::NDeltaToNNKKb(), G4INCL::CrossSectionsStrangeness::NDeltaToNSK(), G4LevelManager::NearestLevelIndex(), G4DensityEffectCalculator::Newton(), nf_amc_clebsh_gordan(), nf_amc_reduced_matrix_element(), nf_amc_wigner_9j(), ActsFatras::Casts::AbsVz::operator()(), ActsFatras::BetheHeitler::operator()(), ActsFatras::detail::GeneralMixture::operator()(), ActsFatras::Casts::AbsEta::operator()(), Acts::PathLimitReached::operator()(), Acts::Test::EndOfWorld::operator()(), Acts::Test::SurfaceObserver< Surface >::operator()(), Acts::Test::MaterialScattering::operator()(), Acts::Test::MinimalOutlierFinder::operator()(), nanoflann::L1_Adaptor< T, DataSource, _DistanceType >::operator()(), operator+(), G4FermiFragment::operator==(), G4PenelopeComptonModel::OscillatorTotalCrossSection(), G4QMDGroundStateNucleus::packNucleons(), DecayFinder::parseDecayDescriptor(), G4NuclearRadii::ParticleRadius(), Acts::PlaneSurface::pathCorrection(), Acts::ConeSurface::pathCorrection(), kdfinder::Helix< T >::pathLength(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::performNewtonApproximation(), PG4gsmixt(), G4Bessel::pI0(), G4Bessel::pI1(), PHG4BarrelEcalDetector::PlaceTower(), Acts::PlaneSurface::PlaneSurface(), AnnularFieldSim::PlotFieldSlices(), Acts::PlaneSurface::polyhedronRepresentation(), Acts::ConeSurface::polyhedronRepresentation(), G4GammaConversionToMuons::PostStepDoIt(), G4Pow::powN(), Par02TrackingAction::PreUserTrackingAction(), G4HadronicProcessStore::Print(), PHRTreeSeeding::Process(), PHG4InEventCompress::process_event(), RawClusterPositionCorrection::process_event(), RawClusterDeadAreaMask::process_event(), QAG4SimulationUpsilon::process_event(), PHHepMCParticleSelectorDecayProductChain::process_event(), PHG4VertexSelection::process_event(), ParticleFlowReco::process_event(), CaloTriggerSim::process_event(), QAG4SimulationKFParticle::process_event(), TPCDataStreamEmulator::process_event(), CaloCalibEmc_Pi0::process_event(), PHG4TpcElectronDrift::process_event(), PHGenFitTrackProjection::process_event(), PHG4MicromegasHitReco::process_event(), PHTpcCentralMembraneClusterizer::process_event(), PHMicromegasTpcTrackMatching::process_event(), eIDMLInterface::process_event(), RawTowerCombiner::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), CellularAutomaton_v1::process_single_triplet(), TpcSpaceChargeReconstruction::process_track(), demo.ScoreSD::ProcessHits(), PHG4TruthEventAction::ProcessShowers(), G4NuclNuclDiffuseElastic::Profile(), G4NuclNuclDiffuseElastic::ProfileNear(), PHSimpleKFProp::PropagateTrack(), ptwX_close(), kdfinder::CircleFit< T >::pythag(), G4Abla::qrot(), G4LundStringFragmentation::Quark_AntiQuark_lastSplitting(), G4LundStringFragmentation::Quark_Diquark_lastSplitting(), Acts::ConeBounds::r(), CLHEP::RanecuEngine::RanecuEngine(), Acts::Extent::range(), CLHEP::Ranlux64Engine::Ranlux64Engine(), CLHEP::RanluxEngine::RanluxEngine(), G4AdjointComptonModel::RapidSampleSecondaries(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4AblaDataFile::readData(), readFile(), RawTowerBuilderByHitIndexBECAL::ReadGeometryFromTable(), CCalMaterialFactory::readMaterials(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4Fancy3DNucleus::ReduceSum(), G4VIntersectionLocator::ReEstimateEndpoint(), Acts::TGeoLayerBuilder::registerSplit(), G4CascadeCheckBalance::relativeE(), G4CascadeCheckBalance::relativeKE(), G4CascadeCheckBalance::relativeP(), G4GeomTools::RemoveRedundantVertices(), G4InitXscPAI::RePartDielectricConst(), kdfinder::LinearFit< T >::RobustFit(), kdfinder::LinearFit< T >::rofunc(), GPUTPCTrackParam::Rotate(), HepPolyhedron::RotateAroundZ(), CLHEP::HepRotation::rotateAxes(), Acts::detail::roundWithPrecision(), CLHEP::safe_acos(), G4MultiUnion::SafetyFromOutsideNumberNode(), G4ParticleHPMadlandNixSpectrum::Sample(), G4ParticleHPPartial::Sample(), G4INCL::StrangeAbsorbtionChannel::sampleAngles(), G4INCL::PionResonanceDecayChannel::sampleAngles(), G4INCL::DeltaDecayChannel::sampleAngles(), G4INCL::SigmaZeroDecayChannel::sampleAngles(), G4hhElastic::SampleBisectionalT(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4DipBustGenerator::SampleCosTheta(), G4FermiBreakUpVI::SampleDecay(), G4DeltaAngle::SampleDirection(), G4UrbanAdjointMscModel::SampleDisplacement(), G4UrbanAdjointMscModel::SampleDisplacementNew(), TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), G4PolarizationTransition::SampleGammaTransition(), G4AntiNuclElastic::SampleInvariantT(), G4HadronElastic::SampleInvariantT(), G4hhElastic::SampleInvariantT(), G4ParticleHPVector::SampleLin(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4UrbanMscModel::SampleScattering(), G4AdjointComptonModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4eeToHadronsModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4QMDGroundStateNucleus::samplingMomentum(), G4INCL::InteractionAvatar::ViolationEMomentumFunctor::scaleParticleMomenta(), G4QuasiElasticChannel::Scatter(), G4DynamicParticle::Set4Momentum(), G4EqEMFieldWithSpin::SetChargeMomentumMass(), G4RepleteEofM::SetChargeMomentumMass(), G4EqEMFieldWithEDM::SetChargeMomentumMass(), G4Mag_SpinEqRhs::SetChargeMomentumMass(), CLHEP::RanecuEngine::setIndex(), G4VLongitudinalStringDecay::SetMinimalStringMass(), G4HadFinalState::SetMomentumChange(), G4VisCommandSceneAddScale::SetNewValue(), G4INCL::InteractionAvatar::ViolationEEnergyFunctor::setParticleEnergy(), G4WorkerThread::SetPinAffinity(), HepPolyhedron::SetReferences(), CLHEP::RanecuEngine::setSeed(), CLHEP::RanecuEngine::setSeeds(), HepPolyhedron::SetSideFacets(), G4WentzelOKandVIxSection::SetupParticle(), G4Tet::SetVertices(), G4AtimaEnergyLossModel::sezi_dedx_e(), kdfinder::CircleFit< T >::SigmaWithLargeCircleOption(), G4RPGNeutronInelastic::SlowNeutron(), Acts::solenoidFieldMapper(), G4INCL::RootFinder::solve(), G4ElectroNuclearCrossSection::SolveTheEquation(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), XTRTransparentRegRadModel::SpectralXTRdEdx(), G4LevelManager::SpinTwo(), G4LundStringFragmentation::SplitLast(), G4MesonSplitter::SplitMeson(), Acts::AtlasStepper< bfield_t >::State::State(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::step(), Acts::AtlasStepper< ConstantBField >::step(), G4HelixMixedStepper::Stepper(), AnnularFieldSim::sum_full3d_field_at(), G4PAIxSection::SumOverBorder(), G4PAIySection::SumOverInterCerenkov(), G4PAIxSection::SumOverInterCerenkov(), G4PAIxSection::SumOverInterMM(), G4PAIySection::SumOverInterPlasmon(), G4PAIxSection::SumOverInterPlasmon(), G4PAIxSection::SumOverInterResonance(), G4PAIySection::SumOverInterval(), G4PAIxSection::SumOverInterval(), G4PAIySection::SumOverIntervaldEdx(), G4PAIxSection::SumOverIntervaldEdx(), G4EllipticalTube::SurfaceNormal(), G4Box::SurfaceNormal(), G4Ellipsoid::SurfaceNormal(), G4Tet::SurfaceNormal(), G4Trd::SurfaceNormal(), G4ExtrudedSolid::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4Para::SurfaceNormal(), G4Trap::SurfaceNormal(), Acts::Frustum< value_t, DIM, SIDES >::svg(), G4hNuclearStoppingModel::TheValue(), G4ParticleHPVector::ThinOut(), G4AblaInterface::toG4ParticleDefinition(), Acts::ConstrainedStep::toString(), TrackingServiceCone(), TrackingServiceCylinder(), Acts::CylinderVolumeBuilder::trackingVolume(), HepGeom::Transform3D::Transform3D(), CLHEP::transformSmall(), G4RKPropagation::Transport(), GPUTPCTrackParam::TransportToX(), G4FTFAnnihilation::UnpackBaryon(), G4DiffractiveExcitation::UnpackMeson(), Acts::AtlasStepper< ConstantBField >::update(), PHG4TruthTrackingAction::UpdateG4ParticleStack(), AnnularFieldSim::UpdateOmegaTau(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), G4Abla::utilabs(), ActsEvaluator::visitTrackStates(), w6j0(), G4NuclWatcher::watch(), G4Clebsch::Weight(), G4CascadeRecoilMaker::wholeEvent(), G4Abla::width(), Acts::RiddersPropagator< propagator_t >::wiggleDimension(), CLHEP::RandGaussZiggurat::ziggurat_nfix(), and CLHEP::RandGaussZiggurat::ziggurat_RNOR().
template<typename T > T kdfinder::angle_between_vectors (T x1, T y1, T z1, T x2, T y2, T z2)
Definition at line 2773 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2773 of file kdfinder.hpp
References c1, c2, d1, d2, and T.
Referenced by make_triplets().
template<typename T > bool kdfinder::candidatesort (const TrackCandidate< T > * a, const TrackCandidate< T > * b)
Definition at line 3188 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3188 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::nhits().
template<typename T > bool kdfinder::candidatesortradius (const TrackCandidate< T > * a, const TrackCandidate< T > * b)
Definition at line 3194 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3194 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::minR().
template<class T > TVector<T> kdfinder::cross_product (const TVector< T > & v1, const TVector< T > & v2) inline
Definition at line 399 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 399 of file kdfinder.hpp
References kdfinder::TVector< T >::cross().
template<typename T > T kdfinder::DistanceToCircle (Circle< T > * circle, T x, T y)
Definition at line 1334 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1334 of file kdfinder.hpp
References kdfinder::Circle< T >::a, kdfinder::Circle< T >::b, and kdfinder::Circle< T >::r.
template<typename T > T kdfinder::DistanceToCircle (T a, T b, T r, T x, T y)
Definition at line 1340 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1340 of file kdfinder.hpp
template<typename T > T kdfinder::DistanceToLine (T a, T b, T x, T y)
Definition at line 1346 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 1346 of file kdfinder.hpp
template<typename T > bool kdfinder::elementsort (const std::tuple< T, Helix< T > *, size_t > a, const std::tuple< T, Helix< T > *, size_t > b)
Definition at line 3302 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3302 of file kdfinder.hpp
References a, and b.
template<typename T > std::string kdfinder::export_candidates_json (std::vector< TrackCandidate< T > * > & candidates, std::vector< std::vector< T >> & hits, size_t run = 0, size_t event_number = 0, size_t evt_time = 0, double B = -0.5)
Definition at line 3480 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3480 of file kdfinder.hpp
References B(), color(), hits(), BTOF::length, mom, pt, sign(), and T.
template<typename T > std::string kdfinder::export_candidates_json_old (std::vector< TrackCandidate< T > * > & candidates, std::vector< ulong > & trigger_ids, size_t run = 0, size_t event_number = 0, size_t evt_time = 0, T B = -0.5, bool round = false)
Definition at line 3639 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3639 of file kdfinder.hpp
References B(), color(), BTOF::length, mom, pt, round(), sign(), and T.
template<typename T > std::string kdfinder::export_json (std::vector< std::vector< std::vector< T >>> & tracks, std::vector< std::vector< T >> & hits, size_t run = 0, size_t event_number = 0, size_t evt_time = 0, double B = -0.5)
Definition at line 3561 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3561 of file kdfinder.hpp
References B(), and hits().
template<typename T > std::vector<std::vector<std::vector<T> > > kdfinder::find_tracks (std::vector< std::vector< T >> & points, std::vector< std::vector< T >> & unused_hits, T search_radius = 10, T search_angle = M_PI / 8, size_t min_track_size = 10, size_t nthreads = 1, bool stats = false)
Definition at line 2873 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2873 of file kdfinder.hpp
References nanoflann::KDTreeSingleIndexAdaptor< Distance, DatasetAdaptor, DIM, IndexType >::buildIndex(), hits(), n1, kdfinder::KDTriplet< T >::n1, kdfinder::KDTriplet< T >::n2, kdfinder::KDPointCloud< T >::pts, t, and track.
template<typename T > std::vector<std::vector<std::vector<T> > > kdfinder::find_tracks_iterative (std::vector< std::vector< T >> & hits, std::vector< std::vector< T >> & unused_hits, T search_radius1 = 10, T search_angle1 = M_PI / 8, size_t min_track_size1 = 10, T search_radius2 = 12, T search_angle2 = M_PI / 8, size_t min_track_size2 = 6, size_t nthreads = 1, bool stats = false)
Definition at line 3125 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3125 of file kdfinder.hpp
References hits().
template<typename T > std::vector<std::pair<std::vector<T>, std::vector<size_t> > > kdfinder::find_vertex_seeds (std::vector< TrackCandidate< T > * > & candidates, T x0 = 0, T y0 = 0, T c_z_dist = 0.5, T c_xy_dist = 2.0, T c_min_tracks = 3, bool stats = false)
Definition at line 3315 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3315 of file kdfinder.hpp
References kdfinder::Helix< T >::at(), dz, elements, it, k, kdfinder::Helix< T >::pathLength(), kdfinder::TVector< T >::perp(), pos(), start(), T, kdfinder::TVector< T >::x(), kdfinder::TVector< T >::y(), and kdfinder::TVector< T >::z().
template<typename T > std::vector<TrackCandidate<T>*> kdfinder::get_track_candidates (std::vector< std::vector< std::vector< T >>> & tracks, T B, bool stats = false)
Definition at line 3153 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3153 of file kdfinder.hpp
References B(), kdfinder::TrackCandidate< T >::isFitted(), and kdfinder::TrackCandidate< T >::refit().
template<typename T > size_t kdfinder::get_track_color (T pt)
Definition at line 3449 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3449 of file kdfinder.hpp
References b, Acts::UnitConstants::g, int(), min, r, and T.
template<typename T > bool kdfinder::ismergedcandidate (const TrackCandidate< T > * o)
Definition at line 3200 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3200 of file kdfinder.hpp
References kdfinder::TrackCandidate< T >::nhits().
template<typename T > void kdfinder::make_triplets (size_t triplet_begin, size_t triplet_end, std::vector< std::vector< double >> & hits, nanoflann::KDTreeSingleIndexAdaptor< nanoflann::L2_Simple_Adaptor< T, KDPointCloud< T >>, KDPointCloud< T >, 3 > & index, std::vector< std::vector< KDTriplet< T >>> & triplets, T search_radius = 10, T search_angle = M_PI / 8)
Definition at line 2782 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2782 of file kdfinder.hpp
References angle, kdfinder::KDTriplet< T >::angle, angle_between_vectors(), kdfinder::KDTriplet< T >::dist1, kdfinder::KDTriplet< T >::dist2, Acts::UnitConstants::h, hits(), M_PI, kdfinder::KDTriplet< T >::n1, kdfinder::KDTriplet< T >::n2, nanoflann::SearchParams::sorted, T, and t.
template<typename T > std::vector<TrackCandidate<T>*> kdfinder::merge_track_candidates (std::vector< TrackCandidate< T > * > & candidates, T c_tanl = 5.0, T c_xy = 5.0, T c_dist = 60.0, bool stats = false)
Definition at line 3206 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3206 of file kdfinder.hpp
References start(), and T.
template<class T > T kdfinder::operator* (const TVector< T > & v1, const TVector< T > & v2) inline
Definition at line 419 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 419 of file kdfinder.hpp
References v1.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::value().
template<class T > TVector<T> kdfinder::operator* (const TVector< T > & v, double c) inline
Definition at line 425 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 425 of file kdfinder.hpp
References v.
template<class T > TVector<T> kdfinder::operator* (T c, const TVector< T > & v) inline
Definition at line 431 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 431 of file kdfinder.hpp
References v.
template<class T > TVector<T> kdfinder::operator+ (const TVector< T > & v1, const TVector< T > & v2) inline
Definition at line 406 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 406 of file kdfinder.hpp
References v1.
template<class T > TVector<T> kdfinder::operator- (const TVector< T > & v1, const TVector< T > & v2) inline
Definition at line 413 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 413 of file kdfinder.hpp
References v1.
template<class T > TVector<T> kdfinder::operator/ (const TVector< T > & v, double c) inline
Definition at line 437 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 437 of file kdfinder.hpp
References v.
template<typename T > bool kdfinder::pointsort (std::vector< T > a, std::vector< T > b)
Definition at line 2761 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2761 of file kdfinder.hpp
template<typename T > T kdfinder::rnd_gauss (T mean, T stddev)
Definition at line 63 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 63 of file kdfinder.hpp
References gauss, r, T, Acts::UnitConstants::u, and v.
template<typename T > bool kdfinder::tripletsort (KDTriplet< T > a, KDTriplet< T > b)
Definition at line 2767 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 2767 of file kdfinder.hpp
References kdfinder::KDTriplet< T >::dist1, and kdfinder::KDTriplet< T >::dist2.
template<typename T > bool kdfinder::vertexsort (const std::pair< std::vector< T >, std::vector< size_t >> a, const std::pair< std::vector< T >, std::vector< size_t >> b)
Definition at line 3308 of file kdfinder.hpp.
View newest version in sPHENIX GitHub at line 3308 of file kdfinder.hpp
References a, and b.