ECCE @ EIC Software: G4hBetheBlochModel Class Reference
G4hBetheBlochModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hBetheBlochModel.hh>
Public Member Functions
G4hBetheBlochModel (const G4String &name)
~G4hBetheBlochModel ()
G4double TheValue (const G4DynamicParticle *particle, const G4Material *material)
G4double TheValue (const G4ParticleDefinition *aParticle, const G4Material *material, G4double kineticEnergy)
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle) const
G4bool IsInCharge (const G4DynamicParticle *particle, const G4Material *material) const
G4bool IsInCharge (const G4ParticleDefinition *aParticle, const G4Material *material) const
Public Member Functions inherited from G4VLowEnergyModel
G4VLowEnergyModel (const G4String &name)
virtual ~G4VLowEnergyModel ()
Private Member Functions
G4double BetheBlochFormula (const G4Material *material, G4double kineticEnergy, G4double particleMass) const
Private Attributes
G4double lowEnergyLimit
G4double highEnergyLimit
const G4double twoln10
const G4double bg2lim
const G4double taulim
Detailed Description
Definition at line 59 of file G4hBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4hBetheBlochModel.hh
Constructor & Destructor Documentation
G4hBetheBlochModel::G4hBetheBlochModel (const G4String & name)
Definition at line 63 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 63 of file G4hBetheBlochModel.cc
G4hBetheBlochModel::~G4hBetheBlochModel ()
Definition at line 74 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 74 of file G4hBetheBlochModel.cc
Member Function Documentation
G4double G4hBetheBlochModel::BetheBlochFormula (const G4Material * material, G4double kineticEnergy, G4double particleMass) const private
Definition at line 156 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 156 of file G4hBetheBlochModel.cc
References bg2lim, Acts::Test::delta, source.hepunit::electron_mass_c2, G4IonisParamMat::GetAdensity(), G4IonisParamMat::GetCdensity(), G4Material::GetElectronDensity(), G4Material::GetIonisation(), G4IonisParamMat::GetMdensity(), G4IonisParamMat::GetMeanExcitationEnergy(), G4IonisParamMat::GetShellCorrectionVector(), G4IonisParamMat::GetTaul(), G4IonisParamMat::GetX0density(), G4IonisParamMat::GetX1density(), k, taulim, twoln10, source.hepunit::twopi_mc2_rcl2, and x.
Referenced by TheValue().
G4double G4hBetheBlochModel::HighEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 104 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 104 of file G4hBetheBlochModel.cc
References highEnergyLimit.
G4double G4hBetheBlochModel::HighEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 124 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 124 of file G4hBetheBlochModel.cc
References highEnergyLimit.
G4bool G4hBetheBlochModel::IsInCharge (const G4DynamicParticle * particle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 140 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 140 of file G4hBetheBlochModel.cc
References true.
G4bool G4hBetheBlochModel::IsInCharge (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 148 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 148 of file G4hBetheBlochModel.cc
References true.
G4double G4hBetheBlochModel::LowEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 113 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 113 of file G4hBetheBlochModel.cc
References G4Material::GetIonisation(), G4ParticleDefinition::GetPDGMass(), and G4IonisParamMat::GetTaul().
G4double G4hBetheBlochModel::LowEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 132 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 132 of file G4hBetheBlochModel.cc
References lowEnergyLimit.
G4double G4hBetheBlochModel::TheValue (const G4DynamicParticle * particle, const G4Material * material) virtual
Implements G4VLowEnergyModel.
Definition at line 79 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 79 of file G4hBetheBlochModel.cc
References BetheBlochFormula(), energy, G4DynamicParticle::GetKineticEnergy(), and G4DynamicParticle::GetMass().
G4double G4hBetheBlochModel::TheValue (const G4ParticleDefinition * aParticle, const G4Material * material, G4double kineticEnergy) virtual
Implements G4VLowEnergyModel.
Definition at line 92 of file G4hBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 92 of file G4hBetheBlochModel.cc
References BetheBlochFormula(), and G4ParticleDefinition::GetPDGMass().
Member Data Documentation
const G4double G4hBetheBlochModel::bg2lim private
Definition at line 106 of file G4hBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4hBetheBlochModel.hh
Referenced by BetheBlochFormula().
G4double G4hBetheBlochModel::highEnergyLimit private
Definition at line 101 of file G4hBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4hBetheBlochModel.hh
Referenced by HighEnergyLimit().
G4double G4hBetheBlochModel::lowEnergyLimit private
Definition at line 100 of file G4hBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 100 of file G4hBetheBlochModel.hh
Referenced by LowEnergyLimit().
const G4double G4hBetheBlochModel::taulim private
Definition at line 107 of file G4hBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4hBetheBlochModel.hh
Referenced by BetheBlochFormula().
const G4double G4hBetheBlochModel::twoln10 private
Definition at line 105 of file G4hBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4hBetheBlochModel.hh
Referenced by BetheBlochFormula().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4hBetheBlochModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4hBetheBlochModel.cc