ECCE @ EIC Software: RE06SteppingVerbose Class Reference
RE06SteppingVerbose Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/include/RE06SteppingVerbose.hh>
Public Member Functions
RE06SteppingVerbose ()
virtual ~RE06SteppingVerbose ()
void InitializeTimers ()
void Report ()
virtual void NewStep ()
virtual void StepInfo ()
virtual void TrackBanner ()
virtual void AtRestDoItInvoked ()
virtual void AlongStepDoItAllDone ()
virtual void PostStepDoItAllDone ()
virtual void AlongStepDoItOneByOne ()
virtual void PostStepDoItOneByOne ()
virtual void TrackingStarted ()
virtual void DPSLStarted ()
virtual void DPSLUserLimit ()
virtual void DPSLPostStep ()
virtual void DPSLAlongStep ()
virtual void VerboseTrack ()
virtual void VerboseParticleChange ()
Public Member Functions inherited from G4VSteppingVerbose
virtual ~G4VSteppingVerbose ()
void CopyState ()
void SetManager (G4SteppingManager *const)
Private Member Functions
G4int FindRegion (G4Region *)
Private Attributes
std::vector< G4SliceTimer * > fTimers
G4int fNofRegions
G4int fNofTimers
G4int fRegIdx
G4bool fEp
Additional Inherited Members
Static Public Member Functions inherited from G4VSteppingVerbose
static void SetInstance (G4VSteppingVerbose *Instance)
static G4VSteppingVerbose * GetInstance ()
static G4int GetSilent ()
static void SetSilent (G4int fSilent)
static G4int GetSilentStepInfo ()
static void SetSilentStepInfo (G4int fSilent)
Protected Types inherited from G4VSteppingVerbose
typedef std::vector< G4int > G4SelectedAtRestDoItVector
typedef std::vector< G4int > G4SelectedAlongStepDoItVector
typedef std::vector< G4int > G4SelectedPostStepDoItVector
Protected Member Functions inherited from G4VSteppingVerbose
G4VSteppingVerbose ()
Protected Attributes inherited from G4VSteppingVerbose
G4SteppingManager * fManager
G4UserSteppingAction * fUserSteppingAction
G4double PhysicalStep
G4double GeometricalStep
G4double CorrectedStep
G4bool PreStepPointIsGeom
G4bool FirstStep
G4StepStatus fStepStatus
G4double TempInitVelocity
G4double TempVelocity
G4double Mass
G4double sumEnergyChange
G4VParticleChange * fParticleChange
G4Track * fTrack
G4TrackVector * fSecondary
G4Step * fStep
G4StepPoint * fPreStepPoint
G4StepPoint * fPostStepPoint
G4VPhysicalVolume * fCurrentVolume
G4VSensitiveDetector * fSensitive
G4VProcess * fCurrentProcess
G4ProcessVector * fAtRestDoItVector
G4ProcessVector * fAlongStepDoItVector
G4ProcessVector * fPostStepDoItVector
G4ProcessVector * fAtRestGetPhysIntVector
G4ProcessVector * fAlongStepGetPhysIntVector
G4ProcessVector * fPostStepGetPhysIntVector
size_t MAXofAtRestLoops
size_t MAXofAlongStepLoops
size_t MAXofPostStepLoops
G4double currentMinimumStep
G4double numberOfInteractionLengthLeft
size_t fAtRestDoItProcTriggered
size_t fAlongStepDoItProcTriggered
size_t fPostStepDoItProcTriggered
G4int fN2ndariesAtRestDoIt
G4int fN2ndariesAlongStepDoIt
G4int fN2ndariesPostStepDoIt
G4Navigator * fNavigator
G4int verboseLevel
G4SelectedAtRestDoItVector * fSelectedAtRestDoItVector
G4SelectedAlongStepDoItVector * fSelectedAlongStepDoItVector
G4SelectedPostStepDoItVector * fSelectedPostStepDoItVector
G4double fPreviousStepSize
G4TouchableHandle fTouchableHandle
G4SteppingControl StepControlFlag
G4double physIntLength
G4ForceCondition fCondition
G4GPILSelection fGPILSelection
Static Protected Attributes inherited from G4VSteppingVerbose
static G4ThreadLocal
G4VSteppingVerbose * fInstance = 0
static G4ThreadLocal G4int Silent = 0
static G4ThreadLocal G4int SilentStepInfo = 0
Detailed Description
Definition at line 42 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 42 of file RE06SteppingVerbose.hh
Constructor & Destructor Documentation
RE06SteppingVerbose::RE06SteppingVerbose ()
Definition at line 44 of file RE06SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 44 of file RE06SteppingVerbose.cc
RE06SteppingVerbose::~RE06SteppingVerbose () virtual
Definition at line 54 of file RE06SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 54 of file RE06SteppingVerbose.cc
References fNofTimers, and fTimers.
Member Function Documentation
virtual void RE06SteppingVerbose::AlongStepDoItAllDone () inline virtual
Implements G4VSteppingVerbose.
Definition at line 57 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 57 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::AlongStepDoItOneByOne () inline virtual
Implements G4VSteppingVerbose.
Definition at line 59 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 59 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::AtRestDoItInvoked () inline virtual
Implements G4VSteppingVerbose.
Definition at line 56 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 56 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::DPSLAlongStep () inline virtual
Implements G4VSteppingVerbose.
Definition at line 65 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 65 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::DPSLPostStep () inline virtual
Implements G4VSteppingVerbose.
Definition at line 64 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 64 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::DPSLStarted () inline virtual
Implements G4VSteppingVerbose.
Definition at line 62 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 62 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::DPSLUserLimit () inline virtual
Implements G4VSteppingVerbose.
Definition at line 63 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 63 of file RE06SteppingVerbose.hh
G4int RE06SteppingVerbose::FindRegion (G4Region * rgn) private
Definition at line 135 of file RE06SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 135 of file RE06SteppingVerbose.cc
References G4RegionStore::GetInstance().
Referenced by NewStep().
void RE06SteppingVerbose::InitializeTimers ()
Definition at line 63 of file RE06SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 63 of file RE06SteppingVerbose.cc
References fEp, G4VSteppingVerbose::fManager, fNofRegions, fNofTimers, fRegIdx, fTimers, G4RegionStore::GetInstance(), G4RunManagerKernel::GetRunManagerKernel(), G4RunManagerKernel::GetTrackingManager(), G4TrackingManager::SetVerboseLevel(), and G4SteppingManager::SetVerboseLevel().
Referenced by RE06RunAction::BeginOfRunAction().
void RE06SteppingVerbose::NewStep () virtual
Implements G4VSteppingVerbose.
Definition at line 107 of file RE06SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 107 of file RE06SteppingVerbose.cc
References G4VSteppingVerbose::CopyState(), G4Electron::ElectronDefinition(), fEp, FindRegion(), fNofRegions, fRegIdx, fTimers, G4VSteppingVerbose::fTrack, G4Track::GetDefinition(), G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), G4LogicalVolume::GetRegion(), G4Track::GetStep(), G4Positron::PositronDefinition(), and reg.
virtual void RE06SteppingVerbose::PostStepDoItAllDone () inline virtual
Implements G4VSteppingVerbose.
Definition at line 58 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 58 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::PostStepDoItOneByOne () inline virtual
Implements G4VSteppingVerbose.
Definition at line 60 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 60 of file RE06SteppingVerbose.hh
void RE06SteppingVerbose::Report ()
Definition at line 88 of file RE06SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 88 of file RE06SteppingVerbose.cc
References fNofRegions, fTimers, G4cout, G4endl, and G4RegionStore::GetInstance().
Referenced by RE06RunAction::EndOfRunAction().
void RE06SteppingVerbose::StepInfo () virtual
Implements G4VSteppingVerbose.
Definition at line 122 of file RE06SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 122 of file RE06SteppingVerbose.cc
References fEp, fNofRegions, fRegIdx, and fTimers.
virtual void RE06SteppingVerbose::TrackBanner () inline virtual
Definition at line 55 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 55 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::TrackingStarted () inline virtual
Implements G4VSteppingVerbose.
Definition at line 61 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 61 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::VerboseParticleChange () inline virtual
Implements G4VSteppingVerbose.
Definition at line 67 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 67 of file RE06SteppingVerbose.hh
virtual void RE06SteppingVerbose::VerboseTrack () inline virtual
Implements G4VSteppingVerbose.
Definition at line 66 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 66 of file RE06SteppingVerbose.hh
Member Data Documentation
G4bool RE06SteppingVerbose::fEp private
Definition at line 76 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 76 of file RE06SteppingVerbose.hh
Referenced by InitializeTimers(), NewStep(), and StepInfo().
G4int RE06SteppingVerbose::fNofRegions private
Definition at line 73 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 73 of file RE06SteppingVerbose.hh
Referenced by InitializeTimers(), NewStep(), Report(), and StepInfo().
G4int RE06SteppingVerbose::fNofTimers private
Definition at line 74 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 74 of file RE06SteppingVerbose.hh
Referenced by InitializeTimers(), and ~RE06SteppingVerbose().
G4int RE06SteppingVerbose::fRegIdx private
Definition at line 75 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 75 of file RE06SteppingVerbose.hh
Referenced by InitializeTimers(), NewStep(), and StepInfo().
std::vector<G4SliceTimer*> RE06SteppingVerbose::fTimers private
Definition at line 72 of file RE06SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 72 of file RE06SteppingVerbose.hh
Referenced by InitializeTimers(), NewStep(), Report(), StepInfo(), and ~RE06SteppingVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/include/RE06SteppingVerbose.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/src/RE06SteppingVerbose.cc