ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_angular.cc File Reference
MCGIDI_angular.cc File Reference
#include <string.h>
#include <cmath>
#include "MCGIDI_fromTOM.h"
#include "MCGIDI_misc.h"
#include "MCGIDI_private.h"
Functions
MCGIDI_angular * MCGIDI_angular_new (statusMessageReporting *smr)
int MCGIDI_angular_initialize (statusMessageReporting *, MCGIDI_angular *angular)
MCGIDI_angular * MCGIDI_angular_free (statusMessageReporting *smr, MCGIDI_angular *angular)
int MCGIDI_angular_release (statusMessageReporting *smr, MCGIDI_angular *angular)
int MCGIDI_angular_setTwoBodyMasses (statusMessageReporting *, MCGIDI_angular *angular, double projectileMass_MeV, double targetMass_MeV, double productMass_MeV, double residualMass_MeV)
int MCGIDI_angular_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution, ptwXYPoints *norms)
int MCGIDI_angular_sampleMu (statusMessageReporting *smr, MCGIDI_angular *angular, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
Function Documentation
MCGIDI_angular* MCGIDI_angular_free (statusMessageReporting * smr, MCGIDI_angular * angular)
Definition at line 39 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_angular.cc
References MCGIDI_angular_release(), and smr_freeMemory().
Referenced by MCGIDI_angular_new(), MCGIDI_angular_parseFromTOM(), MCGIDI_distribution_release(), and MCGIDI_LLNLAngular_angularEnergy_parseFromTOM().
int MCGIDI_angular_initialize (statusMessageReporting * , MCGIDI_angular * angular)
Definition at line 31 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_angular.cc
Referenced by MCGIDI_angular_new(), and MCGIDI_angular_release().
MCGIDI_angular* MCGIDI_angular_new (statusMessageReporting * smr)
Definition at line 20 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_angular.cc
References MCGIDI_angular_free(), MCGIDI_angular_initialize(), and smr_malloc2.
Referenced by MCGIDI_angular_parseFromTOM().
int MCGIDI_angular_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution, ptwXYPoints * norms)
Definition at line 72 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 72 of file MCGIDI_angular.cc
References MCGIDI_distribution_s::angular, MCGIDI_pdfOfX_s::cdf, MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_angular_s::dists, check_license::err(), MCGIDI_angular_s::frame, int(), MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, xDataTOM_W_XYs_s::length, MCGIDI_angular_free(), MCGIDI_angular_new(), MCGIDI_angularType_isotropic, MCGIDI_angularType_linear, MCGIDI_angularType_recoil, MCGIDI_distributionType_angular_e, MCGIDI_fromTOM_interpolation(), MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf(), MCGIDI_misc_getProductFrame(), MCGIDI_misc_getUnitConversionFactor(), n, nfu_Okay, nfu_statusMessage(), norm, MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_pdfOfX_s::numberOfXs, MCGIDI_pdfOfX_s::pdf, ptwX_free(), ptwX_getPointAtIndex_Unsafely(), ptwXY_free(), ptwXY_getPointAtIndex_Unsafely(), ptwXY_length(), ptwXY_runningIntegral(), ptwXY_setValueAtX(), ptwXY_simpleCoalescePoints(), smr_isOk(), smr_malloc2, smr_setReportError2, smr_unknownID, xDataTOM_W_XYs_s::subAxes, MCGIDI_angular_s::type, MCGIDI_distribution_s::type, xDataTOM_XYs_s::value, MCGIDI_pdfsOfXGivenW_s::Ws, ptwXYPoint_s::x, xDataTOM_frame_invalid, xDataTOM_getAttributesValueInElement(), xDataTOM_subAxes_getUnit(), xDataTOME_getOneElementByName(), xDataTOME_getXDataIfID(), MCGIDI_pdfOfX_s::Xs, xDataTOM_W_XYs_s::XYs, and ptwXYPoint_s::y.
Referenced by MCGIDI_distribution_parseFromTOM(), MCGIDI_LLNLAngular_angularEnergy_parseFromTOM(), and MCGIDI_uncorrelated_parseFromTOM().
int MCGIDI_angular_release (statusMessageReporting * smr, MCGIDI_angular * angular)
Definition at line 48 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 48 of file MCGIDI_angular.cc
References MCGIDI_angular_s::dists, MCGIDI_angular_initialize(), and MCGIDI_sampling_pdfsOfXGivenW_release().
Referenced by MCGIDI_angular_free().
int MCGIDI_angular_sampleMu (statusMessageReporting * smr, MCGIDI_angular * angular, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 182 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 182 of file MCGIDI_angular.cc
References MCGIDI_angular_s::dists, MCGIDI_decaySamplingInfo_s::frame, MCGIDI_angular_s::frame, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_angularType_isotropic, MCGIDI_angularType_linear, MCGIDI_angularType_recoil, MCGIDI_sampling_sampleX_from_pdfsOfXGivenW(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, MCGIDI_pdfsOfXGivenW_sampled_s::smr, smr_isOk(), smr_setReportError2, smr_unknownID, MCGIDI_angular_s::type, MCGIDI_pdfsOfXGivenW_sampled_s::w, and MCGIDI_pdfsOfXGivenW_sampled_s::x.
Referenced by MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_product_sampleMu(), and MCGIDI_uncorrelated_sampleDistribution().
int MCGIDI_angular_setTwoBodyMasses (statusMessageReporting * , MCGIDI_angular * angular, double projectileMass_MeV, double targetMass_MeV, double productMass_MeV, double residualMass_MeV)
Definition at line 59 of file MCGIDI_angular.cc.
View newest version in sPHENIX GitHub at line 59 of file MCGIDI_angular.cc
References MCGIDI_angular_s::productMass_MeV, MCGIDI_angular_s::projectileMass_MeV, MCGIDI_angular_s::residualMass_MeV, and MCGIDI_angular_s::targetMass_MeV.
Referenced by MCGIDI_product_setTwoBodyMasses().