ECCE @ EIC Software: G4ParticleHPDiscreteTwoBody Class Reference
G4ParticleHPDiscreteTwoBody Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPDiscreteTwoBody.hh>
Public Member Functions
G4ParticleHPDiscreteTwoBody ()
~G4ParticleHPDiscreteTwoBody ()
void Init (std::istream &aDataFile)
G4ReactionProduct * Sample (G4double anEnergy, G4double massCode, G4double mass)
G4double MeanEnergyOfThisInteraction ()
Public Member Functions inherited from G4VParticleHPEnergyAngular
G4VParticleHPEnergyAngular ()
virtual ~G4VParticleHPEnergyAngular ()
void SetProjectileRP (G4ReactionProduct *aIncidentParticleRP)
void SetTarget (G4ReactionProduct *aTarget)
G4ReactionProduct * GetTarget ()
G4ReactionProduct * GetProjectileRP ()
G4ReactionProduct * GetCMS ()
void SetQValue (G4double aValue)
virtual void ClearHistories ()
Private Attributes
G4int nEnergy
G4InterpolationManager theManager
G4ParticleHPLegendreTable * theCoeff
G4ParticleHPInterpolator theInt
G4bool bCheckDiffCoeffRepr
Additional Inherited Members
Protected Member Functions inherited from G4VParticleHPEnergyAngular
G4double GetQValue ()
Detailed Description
Definition at line 42 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPDiscreteTwoBody.hh
Constructor & Destructor Documentation
G4ParticleHPDiscreteTwoBody::G4ParticleHPDiscreteTwoBody () inline
Definition at line 46 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPDiscreteTwoBody.hh
References bCheckDiffCoeffRepr, nEnergy, and theCoeff.
G4ParticleHPDiscreteTwoBody::~G4ParticleHPDiscreteTwoBody () inline
Definition at line 53 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPDiscreteTwoBody.hh
References theCoeff.
Member Function Documentation
void G4ParticleHPDiscreteTwoBody::Init (std::istream & aDataFile) inline virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 58 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPDiscreteTwoBody.hh
References energy, CLHEP::eV, G4ParticleHPLegendreTable::Init(), G4InterpolationManager::Init(), nEnergy, G4ParticleHPLegendreTable::SetCoeff(), G4ParticleHPLegendreTable::SetRepresentation(), theCoeff, theManager, and y.
G4double G4ParticleHPDiscreteTwoBody::MeanEnergyOfThisInteraction () inline virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 86 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPDiscreteTwoBody.hh
G4ReactionProduct * G4ParticleHPDiscreteTwoBody::Sample (G4double anEnergy, G4double massCode, G4double mass) virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 49 of file G4ParticleHPDiscreteTwoBody.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPDiscreteTwoBody.cc
References A(), G4Alpha::Alpha(), bCheckDiffCoeffRepr, G4Deuteron::Deuteron(), G4Electron::Electron(), G4cout, G4endl, G4UniformRand, G4Gamma::Gamma(), G4ParticleHPLegendreTable::GetEnergy(), G4ReactionProduct::GetMass(), G4ParticleHPLegendreTable::GetNumberOfPoly(), G4VParticleHPEnergyAngular::GetProjectileRP(), G4VParticleHPEnergyAngular::GetQValue(), G4ParticleHPLegendreTable::GetRepresentation(), G4InterpolationManager::GetScheme(), G4VParticleHPEnergyAngular::GetTarget(), G4ReactionProduct::GetTotalMomentum(), G4ParticleHPVector::GetVectorLength(), G4ParticleHPVector::GetX(), G4ParticleHPVector::GetY(), G4He3::He3(), G4InterpolationManager::Init(), G4ParticleHPInterpolator::Interpolate(), it, LINLIN, LOGLIN, G4ParticleHPVector::Merge(), nEnergy, G4Neutron::Neutron(), phi, G4Positron::Positron(), G4Proton::Proton(), G4ParticleHPVector::Sample(), G4ParticleHPLegendreStore::SampleDiscreteTwoBody(), G4ParticleHPLegendreStore::SetCoeff(), G4ParticleHPVector::SetData(), G4ReactionProduct::SetDefinition(), G4ParticleHPVector::SetInterpolationManager(), G4ReactionProduct::SetKineticEnergy(), G4ParticleHPLegendreStore::SetManager(), G4ReactionProduct::SetMomentum(), G4ParticleHPVector::SetX(), G4ParticleHPVector::SetY(), theCoeff, theInt, theManager, theta(), G4Triton::Triton(), CLHEP::twopi, x, x1, x2, y, y1, y2, and Z.
Member Data Documentation
G4bool G4ParticleHPDiscreteTwoBody::bCheckDiffCoeffRepr private
Definition at line 98 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPDiscreteTwoBody.hh
Referenced by G4ParticleHPDiscreteTwoBody(), and Sample().
G4int G4ParticleHPDiscreteTwoBody::nEnergy private
Definition at line 90 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ParticleHPDiscreteTwoBody.hh
Referenced by G4ParticleHPDiscreteTwoBody(), Init(), and Sample().
G4ParticleHPLegendreTable* G4ParticleHPDiscreteTwoBody::theCoeff private
Definition at line 92 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPDiscreteTwoBody.hh
Referenced by G4ParticleHPDiscreteTwoBody(), Init(), Sample(), and ~G4ParticleHPDiscreteTwoBody().
G4ParticleHPInterpolator G4ParticleHPDiscreteTwoBody::theInt private
Definition at line 96 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPDiscreteTwoBody.hh
Referenced by Sample().
G4InterpolationManager G4ParticleHPDiscreteTwoBody::theManager private
Definition at line 91 of file G4ParticleHPDiscreteTwoBody.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPDiscreteTwoBody.hh
Referenced by Init(), and Sample().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPDiscreteTwoBody.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPDiscreteTwoBody.cc