ECCE @ EIC Software: G4ResonanceID Class Reference
G4ResonanceID Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4ResonanceID.hh>
Public Member Functions
G4bool IsDelta1232 (G4int pdg)
G4bool IsDelta1600 (G4int pdg)
G4bool IsDelta1620 (G4int pdg)
G4bool IsDelta1700 (G4int pdg)
G4bool IsDelta1900 (G4int pdg)
G4bool IsDelta1905 (G4int pdg)
G4bool IsDelta1910 (G4int pdg)
G4bool IsDelta1920 (G4int pdg)
G4bool IsDelta1930 (G4int pdg)
G4bool IsDelta1950 (G4int pdg)
G4bool IsN1440 (G4int pdg)
G4bool IsN1520 (G4int pdg)
G4bool IsN1535 (G4int pdg)
G4bool IsN1650 (G4int pdg)
G4bool IsN1675 (G4int pdg)
G4bool IsN1680 (G4int pdg)
G4bool IsN1700 (G4int pdg)
G4bool IsN1710 (G4int pdg)
G4bool IsN1720 (G4int pdg)
G4bool IsN1900 (G4int pdg)
G4bool IsN1990 (G4int pdg)
G4bool IsN2090 (G4int pdg)
G4bool IsN2190 (G4int pdg)
G4bool IsN2220 (G4int pdg)
G4bool IsN2250 (G4int pdg)
G4bool IsL1405 (G4int pdg)
G4bool IsL1520 (G4int pdg)
G4bool IsL1600 (G4int pdg)
G4bool IsL1670 (G4int pdg)
G4bool IsL1690 (G4int pdg)
G4bool IsL1800 (G4int pdg)
G4bool IsL1810 (G4int pdg)
G4bool IsL1820 (G4int pdg)
G4bool IsL1830 (G4int pdg)
G4bool IsL1890 (G4int pdg)
G4bool IsL2100 (G4int pdg)
G4bool IsL2110 (G4int pdg)
G4bool IsS1192 (G4int pdg)
G4bool IsS1385 (G4int pdg)
G4bool IsS1660 (G4int pdg)
G4bool IsS1670 (G4int pdg)
G4bool IsS1750 (G4int pdg)
G4bool IsS1775 (G4int pdg)
G4bool IsS1915 (G4int pdg)
G4bool IsS1940 (G4int pdg)
G4bool IsS2030 (G4int pdg)
G4bool IsX1530 (G4int pdg)
G4bool IsX1690 (G4int pdg)
G4bool IsX1820 (G4int pdg)
G4bool IsX1950 (G4int pdg)
G4bool IsX2030 (G4int pdg)
Detailed Description
Definition at line 31 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 31 of file G4ResonanceID.hh
Member Function Documentation
G4bool G4ResonanceID::IsDelta1232 (G4int pdg) inline
Definition at line 34 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 34 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1600 (G4int pdg) inline
Definition at line 35 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 35 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1620 (G4int pdg) inline
Definition at line 36 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 36 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1700 (G4int pdg) inline
Definition at line 37 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 37 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1900 (G4int pdg) inline
Definition at line 38 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 38 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1905 (G4int pdg) inline
Definition at line 39 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1910 (G4int pdg) inline
Definition at line 40 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1920 (G4int pdg) inline
Definition at line 41 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1930 (G4int pdg) inline
Definition at line 42 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsDelta1950 (G4int pdg) inline
Definition at line 43 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsL1405 (G4int pdg) inline
Definition at line 61 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1520 (G4int pdg) inline
Definition at line 62 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1600 (G4int pdg) inline
Definition at line 63 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1670 (G4int pdg) inline
Definition at line 64 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1690 (G4int pdg) inline
Definition at line 65 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1800 (G4int pdg) inline
Definition at line 66 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1810 (G4int pdg) inline
Definition at line 67 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1820 (G4int pdg) inline
Definition at line 68 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1830 (G4int pdg) inline
Definition at line 69 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL1890 (G4int pdg) inline
Definition at line 70 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL2100 (G4int pdg) inline
Definition at line 71 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsL2110 (G4int pdg) inline
Definition at line 72 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsN1440 (G4int pdg) inline
Definition at line 45 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1520 (G4int pdg) inline
Definition at line 46 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1535 (G4int pdg) inline
Definition at line 47 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1650 (G4int pdg) inline
Definition at line 48 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1675 (G4int pdg) inline
Definition at line 49 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1680 (G4int pdg) inline
Definition at line 50 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1700 (G4int pdg) inline
Definition at line 51 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1710 (G4int pdg) inline
Definition at line 52 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1720 (G4int pdg) inline
Definition at line 53 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1900 (G4int pdg) inline
Definition at line 54 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN1990 (G4int pdg) inline
Definition at line 55 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN2090 (G4int pdg) inline
Definition at line 56 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN2190 (G4int pdg) inline
Definition at line 57 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN2220 (G4int pdg) inline
Definition at line 58 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsN2250 (G4int pdg) inline
Definition at line 59 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ResonanceID.hh
Referenced by G4DetailedBalancePhaseSpaceIntegral::G4DetailedBalancePhaseSpaceIntegral().
G4bool G4ResonanceID::IsS1192 (G4int pdg) inline
Definition at line 74 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsS1385 (G4int pdg) inline
Definition at line 75 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsS1660 (G4int pdg) inline
Definition at line 76 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsS1670 (G4int pdg) inline
Definition at line 77 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsS1750 (G4int pdg) inline
Definition at line 78 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsS1775 (G4int pdg) inline
Definition at line 79 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsS1915 (G4int pdg) inline
Definition at line 80 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsS1940 (G4int pdg) inline
Definition at line 81 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsS2030 (G4int pdg) inline
Definition at line 82 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsX1530 (G4int pdg) inline
Definition at line 84 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsX1690 (G4int pdg) inline
Definition at line 85 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsX1820 (G4int pdg) inline
Definition at line 86 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsX1950 (G4int pdg) inline
Definition at line 87 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ResonanceID.hh
G4bool G4ResonanceID::IsX2030 (G4int pdg) inline
Definition at line 88 of file G4ResonanceID.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ResonanceID.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4ResonanceID.hh