ECCE @ EIC Software: CCalGeometryConfiguration Class Reference
CCalGeometryConfiguration Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalGeometryConfiguration.hh>
Classes
struct GCInfo
Public Member Functions
~CCalGeometryConfiguration ()
G4int getConstructFlag (const G4String &n)
G4String getFileName (const G4String &n)
CCalGeometryConfTable & getConfTable ()
Static Public Member Functions
static CCalGeometryConfiguration * getInstance ()
Private Types
typedef std::map< G4String,
GCInfo, std::less< G4String > > CCalGeometryConfTable
Private Member Functions
CCalGeometryConfiguration ()
Private Attributes
CCalGeometryConfTable theConfiguration
Static Private Attributes
static CCalGeometryConfiguration * instance = 0
Detailed Description
Definition at line 37 of file CCalGeometryConfiguration.hh.
View newest version in sPHENIX GitHub at line 37 of file CCalGeometryConfiguration.hh
Member Typedef Documentation
typedef std::map<G4String, GCInfo, std::less<G4String> > CCalGeometryConfiguration::CCalGeometryConfTable private
Definition at line 44 of file CCalGeometryConfiguration.hh.
View newest version in sPHENIX GitHub at line 44 of file CCalGeometryConfiguration.hh
Constructor & Destructor Documentation
CCalGeometryConfiguration::~CCalGeometryConfiguration () inline
Definition at line 47 of file CCalGeometryConfiguration.hh.
View newest version in sPHENIX GitHub at line 47 of file CCalGeometryConfiguration.hh
CCalGeometryConfiguration::CCalGeometryConfiguration () private
Definition at line 78 of file CCalGeometryConfiguration.cc.
View newest version in sPHENIX GitHub at line 78 of file CCalGeometryConfiguration.cc
References CCalGeometryConfiguration::GCInfo::ConstructFlag, FatalException, CCalGeometryConfiguration::GCInfo::FileName, G4cout, G4endl, G4Exception(), jump(), openGeomFile(), readName(), tab(), and theConfiguration.
Referenced by getInstance().
Member Function Documentation
CCalGeometryConfTable& CCalGeometryConfiguration::getConfTable () inline
Definition at line 54 of file CCalGeometryConfiguration.hh.
View newest version in sPHENIX GitHub at line 54 of file CCalGeometryConfiguration.hh
References theConfiguration.
G4int CCalGeometryConfiguration::getConstructFlag (const G4String & n)
Definition at line 48 of file CCalGeometryConfiguration.cc.
View newest version in sPHENIX GitHub at line 48 of file CCalGeometryConfiguration.cc
References G4cerr, G4endl, it, and theConfiguration.
Referenced by CCalDetector::CCalDetector().
G4String CCalGeometryConfiguration::getFileName (const G4String & n)
Definition at line 63 of file CCalGeometryConfiguration.cc.
View newest version in sPHENIX GitHub at line 63 of file CCalGeometryConfiguration.cc
References G4cerr, G4endl, it, and theConfiguration.
Referenced by CCalDetector::CCalDetector().
CCalGeometryConfiguration * CCalGeometryConfiguration::getInstance () static
Definition at line 41 of file CCalGeometryConfiguration.cc.
View newest version in sPHENIX GitHub at line 41 of file CCalGeometryConfiguration.cc
References CCalGeometryConfiguration(), and instance.
Referenced by CCalDetector::CCalDetector(), and CCalG4Able::PhysicalVolume().
Member Data Documentation
CCalGeometryConfiguration * CCalGeometryConfiguration::instance = 0 static private
Definition at line 62 of file CCalGeometryConfiguration.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalGeometryConfiguration.hh
Referenced by getInstance().
CCalGeometryConfTable CCalGeometryConfiguration::theConfiguration private
Definition at line 63 of file CCalGeometryConfiguration.hh.
View newest version in sPHENIX GitHub at line 63 of file CCalGeometryConfiguration.hh
Referenced by CCalGeometryConfiguration(), getConfTable(), getConstructFlag(), and getFileName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalGeometryConfiguration.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalGeometryConfiguration.cc