ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4Trap.cc File Reference
pyG4Trap.cc File Reference
#include <boost/python.hpp>
#include "G4Trap.hh"
Namespaces
namespace pyG4Trap
Functions
G4Trap * pyG4Trap::f1_CreateTrap (const G4String &name)
G4Trap * pyG4Trap::f2_CreateTrap (const G4String &name, G4double pDz, G4double pTheta, G4double pPhi, G4double pDy1, G4double pDx1, G4double pDx2, G4double pAlp1, G4double pDy2, G4double pDx3, G4double pDx4, G4double pAlp2)
G4Trap * pyG4Trap::f3_CreateTrap (const G4String &name, const std::vector< G4ThreeVector > &pt)
G4Trap * pyG4Trap::f4_CreateTrap (const G4String &name, G4double pZ, G4double pY, G4double pX, G4double pLTX)
G4Trap * pyG4Trap::f5_CreateTrap (const G4String &name, G4double pDx1, G4double pDx2, G4double pDy1, G4double pDy2, G4double pDz)
G4Trap * pyG4Trap::f6_CreateTrap (const G4String &name, G4double pDx, G4double pDy, G4double pDz, G4double pAlpha, G4double pTheta, G4double pPhi)
void export_G4Trap ()
Function Documentation
void export_G4Trap ()
Definition at line 101 of file pyG4Trap.cc.
View newest version in sPHENIX GitHub at line 101 of file pyG4Trap.cc
References pyG4Trap::f1_CreateTrap(), pyG4Trap::f2_CreateTrap(), pyG4Trap::f3_CreateTrap(), pyG4Trap::f4_CreateTrap(), pyG4Trap::f5_CreateTrap(), pyG4Trap::f6_CreateTrap(), G4Trap::GetSidePlane(), G4Trap::GetSymAxis(), G4Trap::GetTanAlpha1(), G4Trap::GetTanAlpha2(), G4Trap::GetXHalfLength1(), G4Trap::GetXHalfLength2(), G4Trap::GetXHalfLength3(), G4Trap::GetXHalfLength4(), G4Trap::GetYHalfLength1(), G4Trap::GetYHalfLength2(), G4Trap::GetZHalfLength(), init(), and G4Trap::SetAllParameters().
Referenced by BOOST_PYTHON_MODULE().