ECCE @ EIC Software: BiasingOperator Class Reference
BiasingOperator Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr08/include/BiasingOperator.hh>
Public Member Functions
BiasingOperator ()
virtual ~BiasingOperator ()
void AddParticle (G4String particleName)
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *, const G4BiasingProcessInterface *)
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void StartRun ()
virtual void StartTracking (const G4Track *)
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Attributes
std::vector< const
G4ParticleDefinition * > fParticlesToBias
BiasingOperation * fBiasingOperation
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions inherited from G4VBiasingOperator
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Detailed Description
Definition at line 45 of file BiasingOperator.hh.
View newest version in sPHENIX GitHub at line 45 of file BiasingOperator.hh
Constructor & Destructor Documentation
BiasingOperator::BiasingOperator ()
Definition at line 42 of file BiasingOperator.cc.
View newest version in sPHENIX GitHub at line 42 of file BiasingOperator.cc
References fBiasingOperation.
virtual BiasingOperator::~BiasingOperator () inline virtual
Definition at line 53 of file BiasingOperator.hh.
View newest version in sPHENIX GitHub at line 53 of file BiasingOperator.hh
Member Function Documentation
void BiasingOperator::AddParticle (G4String particleName)
Definition at line 48 of file BiasingOperator.cc.
View newest version in sPHENIX GitHub at line 48 of file BiasingOperator.cc
References G4ParticleTable::FindParticle(), fParticlesToBias, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), JustWarning, and particle.
G4VBiasingOperation * BiasingOperator::ProposeFinalStateBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final virtual
Implements G4VBiasingOperator.
Definition at line 63 of file BiasingOperator.cc.
View newest version in sPHENIX GitHub at line 63 of file BiasingOperator.cc
References fBiasingOperation, G4VProcess::GetProcessName(), and G4BiasingProcessInterface::GetWrappedProcess().
virtual G4VBiasingOperation* BiasingOperator::ProposeNonPhysicsBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline virtual
Implements G4VBiasingOperator.
Definition at line 58 of file BiasingOperator.hh.
View newest version in sPHENIX GitHub at line 58 of file BiasingOperator.hh
virtual G4VBiasingOperation* BiasingOperator::ProposeOccurenceBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline virtual
Implements G4VBiasingOperator.
Definition at line 60 of file BiasingOperator.hh.
View newest version in sPHENIX GitHub at line 60 of file BiasingOperator.hh
Member Data Documentation
BiasingOperation* BiasingOperator::fBiasingOperation private
Definition at line 64 of file BiasingOperator.hh.
View newest version in sPHENIX GitHub at line 64 of file BiasingOperator.hh
Referenced by BiasingOperator(), and ProposeFinalStateBiasingOperation().
std::vector< const G4ParticleDefinition* > BiasingOperator::fParticlesToBias private
Definition at line 63 of file BiasingOperator.hh.
View newest version in sPHENIX GitHub at line 63 of file BiasingOperator.hh
Referenced by AddParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr08/include/BiasingOperator.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr08/src/BiasingOperator.cc