ECCE @ EIC Software: G4Material Class Reference
G4Material Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4Material.hh>
Public Member Functions
G4Material (const G4String &name, G4double z, G4double a, G4double density, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material (const G4String &name, G4double density, G4int nComponents, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material (const G4String &name, G4double density, const G4Material *baseMaterial, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
void AddElement (G4Element *element, G4int nAtoms)
void AddElement (G4Element *element, G4double fraction)
void AddMaterial (G4Material *material, G4double fraction)
virtual ~G4Material ()
const G4String & GetName () const
const G4String & GetChemicalFormula () const
G4double GetFreeElectronDensity () const
G4double GetDensity () const
G4State GetState () const
G4double GetTemperature () const
G4double GetPressure () const
size_t GetNumberOfElements () const
const G4ElementVector * GetElementVector () const
const G4double * GetFractionVector () const
const G4int * GetAtomsVector () const
const G4Element * GetElement (G4int iel) const
const G4double * GetVecNbOfAtomsPerVolume () const
G4double GetTotNbOfAtomsPerVolume () const
G4double GetTotNbOfElectPerVolume () const
const G4double * GetAtomicNumDensityVector () const
G4double GetElectronDensity () const
G4double GetRadlen () const
G4double GetNuclearInterLength () const
G4IonisParamMat * GetIonisation () const
G4SandiaTable * GetSandiaTable () const
const G4Material * GetBaseMaterial () const
const std::map< G4Material
*, G4double > & GetMatComponents () const
G4double GetMassOfMolecule () const
void SetChemicalFormula (const G4String &chF)
void SetFreeElectronDensity (G4double)
void ComputeDensityEffectOnFly (G4bool)
G4double GetZ () const
G4double GetA () const
void SetMaterialPropertiesTable (G4MaterialPropertiesTable *anMPT)
G4MaterialPropertiesTable * GetMaterialPropertiesTable () const
size_t GetIndex () const
G4Material (__void__ &)
void SetName (const G4String &name)
virtual G4bool IsExtended () const
Static Public Member Functions
static G4MaterialTable * GetMaterialTable ()
static size_t GetNumberOfMaterials ()
static G4Material * GetMaterial (const G4String &name, G4bool warning=true)
static G4Material * GetMaterial (G4double z, G4double a, G4double dens)
static G4Material * GetMaterial (size_t nComp, G4double dens)
Private Member Functions
G4bool operator== (const G4Material &) const
G4bool operator!= (const G4Material &) const
G4Material (const G4Material &)
const G4Material & operator= (const G4Material &)
void InitializePointers ()
void ComputeDerivedQuantities ()
void ComputeRadiationLength ()
void ComputeNuclearInterLength ()
void CopyPointersOfBaseMaterial ()
Private Attributes
const G4Material * fBaseMaterial
G4MaterialPropertiesTable * fMaterialPropertiesTable
G4ElementVector * theElementVector
G4double * fMassFractionVector
G4int * fAtomsVector
G4double * fVecNbOfAtomsPerVolume
G4IonisParamMat * fIonisation
G4SandiaTable * fSandiaTable
G4double fDensity
G4double fFreeElecDensity
G4double fTemp
G4double fPressure
G4double fTotNbOfAtomsPerVolume
G4double fTotNbOfElectPerVolume
G4double fRadlen
G4double fNuclInterLen
G4double fMassOfMolecule
G4State fState
size_t fIndexInTable
G4int maxNbComponents
G4int fArrayLength
G4int fNumberOfComponents
G4int fNumberOfElements
std::map< G4Material *, G4double > fMatComponents
G4String fName
G4String fChemicalFormula
Static Private Attributes
static G4MaterialTable theMaterialTable
Friends
std::ostream & operator<< (std::ostream &, const G4Material *)
std::ostream & operator<< (std::ostream &, const G4Material &)
std::ostream & operator<< (std::ostream &, G4MaterialTable)
Detailed Description
Definition at line 117 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 117 of file G4Material.hh
Constructor & Destructor Documentation
G4Material::G4Material (const G4String & name, G4double z, G4double a, G4double density, G4State state = kStateUndefined, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 95 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 95 of file G4Material.cc
References CLHEP::Avogadro, cm3, ComputeDerivedQuantities(), fArrayLength, fDensity, G4NistManager::FindOrBuildElement(), fMassFractionVector, fMassOfMolecule, fNumberOfComponents, fNumberOfElements, fPressure, fState, fTemp, Acts::UnitConstants::g, G4cout, G4endl, G4lrint(), InitializePointers(), G4NistManager::Instance(), source.hepunit::kGasThreshold, kStateGas, kStateSolid, kStateUndefined, maxNbComponents, theElementVector, and source.hepunit::universe_mean_density.
G4Material::G4Material (const G4String & name, G4double density, G4int nComponents, G4State state = kStateUndefined, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 148 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 148 of file G4Material.cc
References cm3, fArrayLength, fDensity, fNumberOfComponents, fNumberOfElements, fPressure, fState, fTemp, Acts::UnitConstants::g, G4cout, G4endl, InitializePointers(), source.hepunit::kGasThreshold, kStateGas, kStateSolid, kStateUndefined, maxNbComponents, theElementVector, and source.hepunit::universe_mean_density.
G4Material::G4Material (const G4String & name, G4double density, const G4Material * baseMaterial, G4State state = kStateUndefined, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 187 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 187 of file G4Material.cc
References cm3, CopyPointersOfBaseMaterial(), fBaseMaterial, fChemicalFormula, fDensity, fMassOfMolecule, fNumberOfComponents, fNumberOfElements, fPressure, fState, fTemp, Acts::UnitConstants::g, G4cout, G4endl, GetChemicalFormula(), GetMassOfMolecule(), GetNumberOfElements(), InitializePointers(), maxNbComponents, and source.hepunit::universe_mean_density.
G4Material::~G4Material () virtual
Definition at line 233 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 233 of file G4Material.cc
References fAtomsVector, fBaseMaterial, fIndexInTable, fIonisation, fMassFractionVector, fSandiaTable, fVecNbOfAtomsPerVolume, theElementVector, and theMaterialTable.
G4Material::G4Material (__void__ &)
Definition at line 225 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 225 of file G4Material.cc
References InitializePointers().
G4Material::G4Material (const G4Material &) private
Member Function Documentation
void G4Material::AddElement (G4Element * element, G4int nAtoms)
Definition at line 369 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 369 of file G4Material.cc
References source.hepunit::Avogadro, ComputeDerivedQuantities(), fArrayLength, FatalException, fAtomsVector, fMassFractionVector, fMassOfMolecule, fName, fNumberOfComponents, fNumberOfElements, G4cout, G4endl, G4Exception(), maxNbComponents, theElementVector, and w.
Referenced by RE06DetectorConstruction::AddMaterial(), PHG4TTLDetector::BuildBarrelTTL(), PHG4TTLDetector::BuildForwardTTL(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4NistMaterialBuilder::BuildMaterial(), B03DetectorConstruction::Construct(), RE01DetectorConstruction::Construct(), B01DetectorConstruction::Construct(), B02DetectorConstruction::Construct(), GeometryConstruction::Construct(), OpNoviceDetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), PHG4TRDDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), UltraDetectorConstruction::ConstructTableMaterials(), XrayTelDetectorConstruction::ConstructTelescope(), G4HumanPhantomMaterial::DefineMaterials(), BrachyMaterial::DefineMaterials(), RE05DetectorConstruction::DefineMaterials(), B3DetectorConstruction::DefineMaterials(), ElectronBenchmarkDetector::DefineMaterials(), GB03DetectorConstruction::DefineMaterials(), RE06DetectorConstruction::DefineMaterials(), doiPETDetectorConstruction::DefineMaterials(), FFDetectorConstruction::DefineMaterials(), DetectorConstruction::DefineMaterials(), RMC01DetectorConstruction::DefineMaterials(), LXeDetectorConstruction::DefineMaterials(), G4EicDircDetector::DefineMaterials(), F02DetectorConstruction::DefineMaterials(), F01DetectorConstruction::DefineMaterials(), PHG4Reco::DefineMaterials(), ExN03DetectorConstruction::DefineMaterials(), F03DetectorConstruction::DefineMaterials(), PurgMagDetectorConstruction::DefineMaterials(), GammaRayTelDetectorConstruction::DefineMaterials(), EicFRichDetector::element_material(), FCALMaterialConsultant::FCALMaterialConsultant(), CCalMaterialFactory::findMaterial(), G4gsmate(), G4gsmixt(), PHG4CrystalCalorimeterDetector::GetCarbonFiber(), PHG4HybridHomogeneousCalorimeterDetector::GetCarbonFiber(), PHG4BarrelEcalDetector::GetCarbonFiber(), PHG4LFHcalDetector::GetCoatingMaterial(), PHG4ForwardEcalDetector::GetCoatingMaterial(), PHG4ForwardDualReadoutDetector::GetPMMAMaterial(), PHG4ForwardDualReadoutDetector::GetQuartzMaterial(), PHG4BarrelEcalDetector::GetSciGlass(), PHG4LFHcalDetector::GetScintillatorMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetScintillatorMaterial(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetScintillatorMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetTedlarMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetVM2000Material(), PHG4ForwardEcalDetector::GetWLSFiberFEMCMaterial(), PHG4LFHcalDetector::GetWLSFiberMaterial(), DicomDetectorConstruction::InitialisationOfMaterials(), Materials::Initialise(), G03DetectorConstruction::ListOfMaterials(), G02DetectorConstruction::ListOfMaterials(), EICG4LumiDetector::MakeTower(), EICG4ZDCStructure::Materials(), DetectorConstruction::MaterialWithSingleIsotope(), G4GDMLReadMaterials::MixtureRead(), TrentoPassiveProtonBeamLine::SetDefaultDimensions(), G3toG4DetectorConstruction::SimpleConstruct(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
void G4Material::AddElement (G4Element * element, G4double fraction)
Definition at line 411 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 411 of file G4Material.cc
References kdfinder::abs(), ComputeDerivedQuantities(), fArrayLength, FatalException, fAtomsVector, fMassFractionVector, fName, fNumberOfComponents, fNumberOfElements, G4cout, G4endl, G4Exception(), G4lrint(), GetA(), G4Element::GetName(), JustWarning, maxNbComponents, perThousand, and theElementVector.
void G4Material::AddMaterial (G4Material * material, G4double fraction)
store massFraction of material component
Definition at line 475 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 475 of file G4Material.cc
References kdfinder::abs(), ComputeDerivedQuantities(), fArrayLength, FatalException, fAtomsVector, fMassFractionVector, fMatComponents, fName, fNumberOfComponents, fNumberOfElements, G4cout, G4endl, G4Exception(), G4lrint(), GetA(), GetElementVector(), GetFractionVector(), GetName(), GetNumberOfElements(), JustWarning, material(), maxNbComponents, perThousand, theElementVector, and v1.
Referenced by PHG4TTLDetector::BuildBarrelTTL(), G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), PHG4CylinderStripDetector::BuildMaterials(), DetectorALICE06::Construct(), PHG4TRDDetector::ConstructMe(), PHG4ECAPToFDetector::ConstructMe(), PHG4TpcDetector::CreateCompositeMaterial(), PHG4TpcEndCapDetector::CreateCompositeMaterial(), WLSMaterials::CreateMaterials(), XrayFluoNistMaterials::CreateMaterials(), DetectorConstruction::DefineMaterials(), F02DetectorConstruction::DefineMaterials(), F01DetectorConstruction::DefineMaterials(), PHG4Reco::DefineMaterials(), F03DetectorConstruction::DefineMaterials(), ExN03DetectorConstruction::DefineMaterials(), PurgMagDetectorConstruction::DefineMaterials(), GammaRayTelDetectorConstruction::DefineMaterials(), EicFRichDetector::element_material(), export_G4Material(), FCALMaterialConsultant::FCALMaterialConsultant(), PHG4LFHcalDetector::GetCoatingMaterial(), PHG4ForwardEcalDetector::GetCoatingMaterial(), Materials::Initialise(), EICG4LumiDetector::MakeTower(), G4GDMLReadMaterials::MixtureRead(), and TrentoPassiveProtonBeamLine::SetDefaultDimensions().
void G4Material::ComputeDensityEffectOnFly (G4bool val)
Definition at line 623 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 623 of file G4Material.cc
References G4IonisParamMat::ComputeDensityEffectOnFly(), fIonisation, G4MUTEXLOCK, and G4MUTEXUNLOCK.
Referenced by CopyPointersOfBaseMaterial(), and G4NistManager::SetDensityEffectCalculatorFlag().
void G4Material::ComputeDerivedQuantities () private
Definition at line 298 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 298 of file G4Material.cc
References source.hepunit::Avogadro, ComputeNuclearInterLength(), ComputeRadiationLength(), CLHEP::eV, fDensity, fFreeElecDensity, fIonisation, fMassFractionVector, fNumberOfElements, fSandiaTable, fState, fTotNbOfAtomsPerVolume, fTotNbOfElectPerVolume, fVecNbOfAtomsPerVolume, G4AtomicShells::GetNumberOfFreeElectrons(), and kStateGas.
Referenced by AddElement(), AddMaterial(), and G4Material().
void G4Material::ComputeNuclearInterLength () private
Definition at line 577 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 577 of file G4Material.cc
References A(), source.hepunit::amu, CLHEP::cm2, DBL_MAX, fNuclInterLen, fNumberOfElements, fVecNbOfAtomsPerVolume, CLHEP::g, G4Exp(), G4Log(), and Z.
Referenced by ComputeDerivedQuantities().
void G4Material::ComputeRadiationLength () private
Definition at line 566 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 566 of file G4Material.cc
References DBL_MAX, fNumberOfElements, fRadlen, and fVecNbOfAtomsPerVolume.
Referenced by ComputeDerivedQuantities().
void G4Material::CopyPointersOfBaseMaterial () private
Definition at line 331 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 331 of file G4Material.cc
References ComputeDensityEffectOnFly(), fAtomsVector, fBaseMaterial, fDensity, fFreeElecDensity, fIonisation, fMassFractionVector, fMaterialPropertiesTable, fNuclInterLen, fNumberOfElements, fRadlen, fSandiaTable, fState, fTotNbOfAtomsPerVolume, fTotNbOfElectPerVolume, fVecNbOfAtomsPerVolume, GetAtomsVector(), GetDensity(), G4IonisParamMat::GetDensityEffectCalculator(), GetElementVector(), GetFractionVector(), GetFreeElectronDensity(), GetIonisation(), GetMaterialPropertiesTable(), G4IonisParamMat::GetMeanExcitationEnergy(), GetNuclearInterLength(), GetRadlen(), GetSandiaTable(), GetState(), GetTotNbOfAtomsPerVolume(), GetTotNbOfElectPerVolume(), GetVecNbOfAtomsPerVolume(), kStateUndefined, G4IonisParamMat::SetMeanExcitationEnergy(), theElementVector, and v.
Referenced by G4Material().
G4double G4Material::GetA () const
Definition at line 714 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 714 of file G4Material.cc
References FatalException, fName, fNumberOfElements, G4cout, G4Exception(), and theElementVector.
Referenced by AddElement(), AddMaterial(), RunAction::BeginOfRunAction(), G4tgbGeometryDumper::DumpMaterial(), export_G4Material(), GVFlashShowerParameterisation::GetEffA(), GetMaterial(), main(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), and FW::Geant4::MMSteppingAction::UserSteppingAction().
const G4double* G4Material::GetAtomicNumDensityVector () const inline
Definition at line 210 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 210 of file G4Material.hh
References fVecNbOfAtomsPerVolume.
Referenced by G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4RToEConvForGamma::BuildAbsorptionLengthVector(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), G4hImpactIonisation::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4VRangeToEnergyConverter::BuildRangeVector(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4ICRU49NuclearStoppingModel::ComputeDEDXPerVolume(), G4eBremParametrizedModel::ComputeDEDXPerVolume(), G4LivermoreIonisationModel::ComputeDEDXPerVolume(), G4MuPairProductionModel::ComputeDEDXPerVolume(), G4MuBremsstrahlungModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeIonParameters(), G4ICRU73QOModel::DEDX(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4hIonEffChargeSquare::IonEffChargeSquare(), G4ElementSelector::SelectZandA(), G4EmCorrections::SetupKinematics(), G4hParametrisedLossModel::StoppingPower(), and G4hNuclearStoppingModel::StoppingPower().
const G4int* G4Material::GetAtomsVector () const inline
Definition at line 192 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 192 of file G4Material.hh
References fAtomsVector.
Referenced by CopyPointersOfBaseMaterial(), EICG4dRICHGas::EICG4dRICHGas(), G4VLEPTSModel::ReadParam(), and G4hParametrisedLossModel::StoppingPower().
const G4Material* G4Material::GetBaseMaterial () const inline
Definition at line 227 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 227 of file G4Material.hh
References fBaseMaterial.
Referenced by G4BetheBlochModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeDensityEffectParameters(), G4BetheBlochModel::CorrectionsAlongStep(), G4LivermorePolarizedPhotoElectricModel::CrossSectionPerVolume(), G4LivermorePhotoElectricModel::CrossSectionPerVolume(), G4MicroElecElasticModel::CrossSectionPerVolume(), G4MuElecElasticModel::CrossSectionPerVolume(), G4MicroElecInelasticModel::CrossSectionPerVolume(), G4MuElecInelasticModel::CrossSectionPerVolume(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), G4VEmProcess::DefineMaterial(), CompareMaterial::operator()(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4Region::ScanVolumeTree(), and G4VEmModel::SetCurrentCouple().
const G4String& G4Material::GetChemicalFormula () const inline
Definition at line 172 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 172 of file G4Material.hh
References fChemicalFormula.
Referenced by export_G4Material(), G4IonisParamMat::FindMeanExcitationEnergy(), G4Material(), G4hICRU49He::HasMaterial(), G4hICRU49p::HasMaterial(), G4BraggModel::HasMaterial(), G4BraggIonModel::HasMaterial(), G4ASTARStopping::Initialise(), G4PSTARStopping::Initialise(), G4hParametrisedLossModel::MolecIsInZiegler1988(), and G4BraggModel::MolecIsInZiegler1988().
G4double G4Material::GetDensity () const inline
Definition at line 174 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 174 of file G4Material.hh
References fDensity.
Referenced by CML2ExpVoxels::add(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddSolid(), RunAction::BeginOfRunAction(), G4NistManager::BuildMaterialWithNewDensity(), G4VLEPTSModel::BuildMeanFreePathTable(), G4ProductionCutsTable::CheckMaterialInfo(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), G4EmCalculator::ComputeDEDX(), G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeDensityEffectParameters(), G4TablesForExtrapolator::ComputeElectronDEDX(), G4SandiaTable::ComputeMatSandiaMatrixPAI(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4EmCalculator::ComputeNuclearDEDX(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4MIRDLeftLegBone::Construct(), G4MIRDRightKidney::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLiver::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDPelvis::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDRightLeg::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDSkull::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDLeftLung::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDThyroid::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDBrain::Construct(), G4MIRDHeart::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDUterus::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDTrunk::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDHead::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDPancreas::Construct(), G4MIRDRightArmBone::Construct(), G4MIRDUrinaryBladder::Construct(), DetectorBarr90::Construct(), DetectorHarris73::Construct(), DetectorWatase86::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), DetectorBari05::Construct(), CML2Ph_BoxInBox::Construct(), G4NistMaterialBuilder::ConstructNewGasMaterial(), G4VRangeToEnergyConverter::Convert(), CopyPointersOfBaseMaterial(), PHG4TpcDetector::CreateCompositeMaterial(), PHG4TpcEndCapDetector::CreateCompositeMaterial(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4LivermorePolarizedPhotoElectricModel::CrossSectionPerVolume(), G4LivermorePhotoElectricModel::CrossSectionPerVolume(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), PHG4Reco::DefineMaterials(), G4PhysicalVolumeModel::DescribeAndDescend(), G4AtimaFluctuations::Dispersion(), G4EmSaturation::DumpBirksCoefficients(), G4tgbGeometryDumper::DumpMaterial(), Run::EndOfRun(), HistoManager::EndOfRun(), export_G4Material(), G4InitXscPAI::G4InitXscPAI(), G4PAIxSection::G4PAIxSection(), G4EmCalculator::GetDEDX(), G4VMscModel::GetEnergy(), G4HepRepSceneHandler::getGeometryInstance(), G4LogicalVolume::GetMass(), GetMaterial(), G4QAOLowEnergyLoss::GetOscillatorEnergy(), G4VMscModel::GetRange(), G4GSPWACorrections::InitDataMaterial(), G4PAIySection::Initialize(), G4PAIxSection::Initialize(), G4GSMottCorrection::InitMCDataMaterial(), G4GoudsmitSaundersonTable::InitMoliereMSCParams(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4PSDoseDeposit::ProcessHits(), G4PhysicalVolumeMassScene::ProcessVolume(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial(), G4ASCIITreeSceneHandler::RequestPrimitives(), Run::Run(), G4IonisParamMat::SetDensityEffectParameters(), GFlashSamplingShowerParameterisation::SetMaterial(), GFlashHomoShowerParameterisation::SetMaterial(), DicomIntersectVolume::SetNewValue(), EICG4dRICHAerogel::setOpticalParams(), EICG4dRICHGas::setOpticalParams(), G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight(), and FW::Geant4::MMSteppingAction::UserSteppingAction().
G4double G4Material::GetElectronDensity () const inline
Definition at line 211 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 211 of file G4Material.hh
References fTotNbOfElectPerVolume.
Referenced by G4AdjointComptonModel::AdjointCrossSection(), G4AdjointhIonisationModel::AdjointCrossSection(), G4hBetheBlochModel::BetheBlochFormula(), G4ForwardXrayTR::BuildXrayTRtables(), G4IonChuFluctuationModel::ChuFluctuationModel(), G4mplIonisationModel::ComputeDEDXAhlen(), G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), MyMollerBhabhaModel::ComputeDEDXPerVolume(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4ICRU73QOModel::ComputeDEDXPerVolume(), G4MuBetheBlochModel::ComputeDEDXPerVolume(), G4BraggIonModel::ComputeDEDXPerVolume(), G4BraggModel::ComputeDEDXPerVolume(), G4EmCorrections::ComputeIonCorrections(), G4LindhardSorensenIonModel::CorrectionsAlongStep(), G4eeToHadronsModel::CrossSectionPerVolume(), G4eeToHadronsMultiModel::CrossSectionPerVolume(), G4eplusTo3GammaOKVIModel::CrossSectionPerVolume(), G4eplusTo2GammaOKVIModel::CrossSectionPerVolume(), G4eeToTwoGammaModel::CrossSectionPerVolume(), G4AtimaEnergyLossModel::CrossSectionPerVolume(), G4MollerBhabhaModel::CrossSectionPerVolume(), G4LindhardSorensenIonModel::CrossSectionPerVolume(), G4BetheBlochModel::CrossSectionPerVolume(), G4ICRU73QOModel::CrossSectionPerVolume(), G4MuBetheBlochModel::CrossSectionPerVolume(), G4BraggIonModel::CrossSectionPerVolume(), G4BraggModel::CrossSectionPerVolume(), G4hImpactIonisation::DeltaRaysEnergy(), G4BohrFluctuations::Dispersion(), G4UniversalFluctuation::Dispersion(), G4IonFluctuations::Dispersion(), G4mplIonisationModel::Dispersion(), G4PAIPhotModel::Dispersion(), G4mplIonisationWithDeltaModel::Dispersion(), G4PAIModel::Dispersion(), G4hImpactIonisation::ElectronicLossFluctuation(), export_G4Material(), G4InitXscPAI::G4InitXscPAI(), G4StrawTubeXTRadiator::G4StrawTubeXTRadiator(), G4VXTRenergyLoss::G4VXTRenergyLoss(), G4RDVeLowEnergyLoss::GetLossWithFluct(), G4EmCorrections::HighOrderCorrections(), G4mplIonisationModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4PAIySection::Initialize(), G4PAIxSection::Initialize(), G4EmCorrections::IonBarkasCorrection(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4UniversalFluctuation::SampleFluctuations(), G4SeltzerBergerModel::SetupForMaterial(), G4eBremsstrahlungRelModel::SetupForMaterial(), G4eBremParametrizedModel::SetupForMaterial(), G4EnergyLossForExtrapolator::SetupKinematics(), and G4IonYangFluctuationModel::YangFluctuationModel().
const G4Element* G4Material::GetElement (G4int iel) const inline
Definition at line 196 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 196 of file G4Material.hh
References theElementVector.
Referenced by G4CrystalExtension::AddAtomBase(), G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), DicomDetectorConstruction::BuildMaterialWithChangingDensity(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4ErrorFreeTrajState::CalculateEffectiveZandA(), CexmcHadronicProcess::CalculateTargetNucleus(), G4EmCalculator::CheckMaterial(), G4AdjointCSManager::ComputeAdjointCS(), G4CrossSectionDataStore::ComputeCrossSection(), G4IonisParamMat::ComputeDensityEffectOnFly(), G4PAIySection::ComputeLowEnergyCof(), G4PAIxSection::ComputeLowEnergyCof(), G4VEmModel::CrossSectionPerVolume(), EICG4dRICHGas::EICG4dRICHGas(), Run::EndOfRun(), export_G4Material(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4CrystalExtension::GetAtomBase(), G4CrystalExtension::GetAtomPos(), GVFlashShowerParameterisation::GetEffA(), GVFlashShowerParameterisation::GetEffZ(), G4QAOLowEnergyLoss::GetOscillatorEnergy(), G4VEmModel::InitialiseForMaterial(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4LindhardRobinsonPartition::PartitionNIEL(), G4VLEPTSModel::ReadParam(), G4AdjointCSManager::SampleElementFromCSMatrices(), G4CrossSectionDataStore::SampleZandA(), G4VEmAdjointModel::SelectCSMatrix(), G4VEmModel::SelectRandomAtom(), G4VEmModel::SelectRandomAtomNumber(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
const G4ElementVector* G4Material::GetElementVector () const inline
Definition at line 184 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 184 of file G4Material.hh
References theElementVector.
Referenced by G4RDVCrossSectionHandler::ActiveElements(), G4VCrossSectionHandler::ActiveElements(), G4PixeCrossSectionHandler::ActiveElements(), AddMaterial(), G4AdjointPhotoElectricModel::AdjointCrossSection(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4RToEConvForGamma::BuildAbsorptionLengthVector(), G4AugerData::BuildAugerTransitionTable(), G4RDAugerData::BuildAugerTransitionTable(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PenelopeRayleighModel::BuildFormFactorTable(), G4hImpactIonisation::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4ScreenedCoulombCrossSection::BuildMFPTables(), G4PenelopeOscillatorManager::BuildOscillatorTable(), G4VRangeToEnergyConverter::BuildRangeVector(), G4SBBremTable::BuildSamplingTables(), G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), G4PenelopeBremsstrahlungAngular::CalculateEffectiveZ(), G4Nucleus::ChooseParameters(), G4eBremsstrahlungRelModel::ComputeDEDXPerVolume(), G4ICRU49NuclearStoppingModel::ComputeDEDXPerVolume(), G4eBremParametrizedModel::ComputeDEDXPerVolume(), G4LivermoreIonisationModel::ComputeDEDXPerVolume(), G4MuPairProductionModel::ComputeDEDXPerVolume(), G4MuBremsstrahlungModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeDensityEffectParameters(), G4WentzelVIRelModel::ComputeEffectiveMass(), G4IonisParamMat::ComputeFluctModel(), G4IonisParamMat::ComputeIonParameters(), G4SandiaTable::ComputeMatSandiaMatrix(), G4SandiaTable::ComputeMatSandiaMatrixPAI(), G4SandiaTable::ComputeMatTable(), G4GammaConversionToMuons::ComputeMeanFreePath(), G4IonisParamMat::ComputeMeanParameters(), G4WentzelVIModel::ComputeSecondMoment(), G4CrystalExtension::ComputeStructureFactor(), G4CrystalExtension::ComputeStructureFactorGeometrical(), G4WentzelVIModel::ComputeTransportXSectionPerVolume(), CopyPointersOfBaseMaterial(), MuCrossSections::CR_Macroscopic(), G4AnnihiToMuPair::CrossSectionPerVolume(), G4ICRU73QOModel::DEDX(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), G4LowEnergyIonisation::DeexciteAtom(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4tgbGeometryDumper::DumpMaterial(), export_G4Material(), G4EmElementSelector::G4EmElementSelector(), G4HadElementSelector::G4HadElementSelector(), G4CrystalExtension::GetAtomPos(), G4HadronicProcessStore::GetCaptureCrossSectionPerVolume(), G4HadronicProcessStore::GetChargeExchangeCrossSectionPerVolume(), G4CrossSectionDataStore::GetCrossSection(), G4HadronicProcessStore::GetElasticCrossSectionPerVolume(), G4MuNeutrinoNucleusTotXsc::GetElementCrossSection(), G4HadronicProcessStore::GetFissionCrossSectionPerVolume(), G4HadronicProcessStore::GetInelasticCrossSectionPerVolume(), G4GSPWACorrections::InitDataMaterial(), G4GSPWACorrections::InitDataPerElement(), G4LivermoreRayleighModel::Initialise(), G4LivermoreGammaConversionModelRC::Initialise(), G4LivermoreNuclearGammaConversionModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4PenelopeGammaConversionModel::InitializeScreeningFunctions(), G4GSMottCorrection::InitMCDataMaterial(), G4GSMottCorrection::InitMCDataPerElement(), G4GoudsmitSaundersonTable::InitMoliereMSCParams(), G4hIonEffChargeSquare::IonEffChargeSquare(), G4RDBremsstrahlungParameters::LoadData(), G4eIonisationParameters::LoadData(), G4RDeIonisationParameters::LoadData(), G4BremsstrahlungParameters::LoadData(), G4NativeScreenedCoulombCrossSection::LoadData(), G4hCoulombScatteringModel::MinPrimaryEnergy(), G4eCoulombScatteringModel::MinPrimaryEnergy(), G4WentzelVIModel::SampleScattering(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VCrossSectionHandler::SelectRandomAtom(), G4PixeCrossSectionHandler::SelectRandomAtom(), G4GammaConversionToMuons::SelectRandomAtom(), G4RDVCrossSectionHandler::SelectRandomElement(), G4VCrossSectionHandler::SelectRandomElement(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), G4ElementSelector::SelectZandA(), G4EmCorrections::SetupKinematics(), G4hParametrisedLossModel::StoppingPower(), G4hNuclearStoppingModel::StoppingPower(), FW::Geant4::MMSteppingAction::UserSteppingAction(), G4RDVCrossSectionHandler::ValueForMaterial(), G4PixeCrossSectionHandler::ValueForMaterial(), and G4VCrossSectionHandler::ValueForMaterial().
const G4double* G4Material::GetFractionVector () const inline
Definition at line 188 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 188 of file G4Material.hh
References fMassFractionVector.
Referenced by AddMaterial(), G4PenelopeRayleighModel::BuildFormFactorTable(), DicomDetectorConstruction::BuildMaterialWithChangingDensity(), G4PenelopeOscillatorManager::BuildOscillatorTable(), G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), G4PenelopeBremsstrahlungAngular::CalculateEffectiveZ(), G4ErrorFreeTrajState::CalculateEffectiveZandA(), G4IonisParamMat::ComputeFluctModel(), G4SandiaTable::ComputeMatSandiaMatrixPAI(), G4SandiaTable::ComputeMatTable(), CopyPointersOfBaseMaterial(), G4tgbGeometryDumper::DumpMaterial(), GVFlashShowerParameterisation::GetEffA(), GVFlashShowerParameterisation::GetEffZ(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), and FW::Geant4::MMSteppingAction::UserSteppingAction().
G4double G4Material::GetFreeElectronDensity () const inline
Definition at line 173 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 173 of file G4Material.hh
References fFreeElecDensity.
Referenced by CopyPointersOfBaseMaterial(), and G4DensityEffectCalculator::G4DensityEffectCalculator().
size_t G4Material::GetIndex () const inline
Definition at line 254 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 254 of file G4Material.hh
References fIndexInTable.
Referenced by G4NistMaterialBuilder::BuildMaterial(), G4VLEPTSModel::BuildMeanFreePathTable(), G4VLEPTSModel::BuildPhysicsTable(), G4AdjointCSManager::ComputeAdjointCS(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4VRangeToEnergyConverter::Convert(), G4DNAUeharaScreenedRutherfordElasticModel::CrossSectionPerVolume(), G4DNAScreenedRutherfordElasticModel::CrossSectionPerVolume(), G4DNADingfelderChargeDecreaseModel::CrossSectionPerVolume(), G4DNADingfelderChargeIncreaseModel::CrossSectionPerVolume(), G4DNABornExcitationModel1::CrossSectionPerVolume(), G4DNAMeltonAttachmentModel::CrossSectionPerVolume(), G4DNAChampionElasticModel::CrossSectionPerVolume(), G4DNASancheExcitationModel::CrossSectionPerVolume(), G4DNAELSEPAElasticModel::CrossSectionPerVolume(), G4DNABornExcitationModel2::CrossSectionPerVolume(), G4DNAMillerGreenExcitationModel::CrossSectionPerVolume(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::CrossSectionPerVolume(), G4DNABornIonisationModel1::CrossSectionPerVolume(), G4DNABornIonisationModel2::CrossSectionPerVolume(), G4DNAIonElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNACPA100ElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNATransformElectronModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4PEEffectFluoModel::CrossSectionPerVolume(), G4TDNAOneStepThermalizationModel< MODEL >::CrossSectionPerVolume(), G4GoudsmitSaundersonMscModel::CrossSectionPerVolume(), G4VEmAdjointModel::DefineCurrentMaterial(), G4AdjointPhotoElectricModel::DefineCurrentMaterialAndElectronEnergy(), G4ContinuousGainOfEnergy::DefineMaterial(), G4DNABrownianTransportation::Diffusion(), export_G4Material(), G4DNAElectronHoleRecombination::FindReactant(), G4InitXscPAI::G4InitXscPAI(), G4PAIxSection::G4PAIxSection(), G4StrawTubeXTRadiator::G4StrawTubeXTRadiator(), G4VXTRenergyLoss::G4VXTRenergyLoss(), WLSPrimaryGeneratorAction::GeneratePrimaries(), G4Cerenkov::GetAverageNumberOfPhotons(), G4EnergyLossTables::GetDEDX(), G4EnergyLossTables::GetDeltaLabTime(), G4EnergyLossTables::GetDeltaProperTime(), G4EnergyLossTables::GetLabTime(), G4VLEPTSModel::GetMeanFreePath(), G4OpRayleigh::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4DNAMolecularMaterial::GetMolecularConfiguration(), G4DNADummyModel::GetNumMoleculePerVolumeUnitForMaterial(), G4DNAModelInterface::GetNumMoleculePerVolumeUnitForMaterial(), G4DNAModelInterface::GetNumMolPerVolUnitForComponentInComposite(), G4EnergyLossTables::GetPreciseDEDX(), G4EnergyLossTables::GetPreciseEnergyFromRange(), G4EnergyLossTables::GetPreciseRangeFromEnergy(), G4EnergyLossTables::GetProperTime(), G4EnergyLossTables::GetRange(), G4GoudsmitSaundersonMscModel::GetTransportMeanFreePath(), G4GoudsmitSaundersonMscModel::GetTransportMeanFreePathOnly(), G4GSPWACorrections::InitDataMaterial(), G4GSPWACorrections::InitDataPerMaterials(), G4EmSaturation::InitialiseBirksCoefficient(), G4GSMottCorrection::InitMCDataMaterial(), G4GSMottCorrection::InitMCDataPerMaterials(), G4GoudsmitSaundersonTable::InitMoliereMSCParams(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4OpWLS::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4DNAMolecularMaterial::RecordMolecularMaterial(), G4PixeCrossSectionHandler::SelectRandomAtom(), G4DNAMolecularMaterial::SetMolecularConfiguration(), G4EnergyLossForExtrapolator::SetupKinematics(), and G4EmSaturation::VisibleEnergyDeposition().
G4IonisParamMat* G4Material::GetIonisation () const inline
Definition at line 220 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 220 of file G4Material.hh
References fIonisation.
Referenced by G4EmCorrections::Bethe(), G4hBetheBlochModel::BetheBlochFormula(), SteppingAction::BirksAttenuation(), G4NistMaterialBuilder::BuildMaterial(), G4hImpactIonisation::BuildPhysicsTable(), G4mplIonisationModel::ComputeDEDXAhlen(), G4mplIonisationWithDeltaModel::ComputeDEDXAhlen(), MyMollerBhabhaModel::ComputeDEDXPerVolume(), G4AtimaEnergyLossModel::ComputeDEDXPerVolume(), G4MollerBhabhaModel::ComputeDEDXPerVolume(), G4LindhardSorensenIonModel::ComputeDEDXPerVolume(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4MuBetheBlochModel::ComputeDEDXPerVolume(), G4DensityEffectCalculator::ComputeDensityCorrection(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), OpNoviceDetectorConstruction::Construct(), CopyPointersOfBaseMaterial(), WLSMaterials::CreateMaterials(), G4HumanPhantomMaterial::DefineMaterials(), BrachyMaterial::DefineMaterials(), doiPETDetectorConstruction::DefineMaterials(), DetectorConstruction::DefineMaterials(), LXeDetectorConstruction::DefineMaterials(), PHG4Reco::DefineMaterials(), ExN03DetectorConstruction::DefineMaterials(), G4EmCorrections::DensityCorrection(), G4AtimaFluctuations::Dispersion(), G4IonFluctuations::Dispersion(), G4EmSaturation::DumpBirksCoefficients(), G4tgbGeometryDumper::DumpMaterial(), G4ElectronIonPair::DumpMeanEnergyPerIonPair(), G4ionEffectiveCharge::EffectiveCharge(), G4hImpactIonisation::ElectronicLossFluctuation(), export_G4Material(), G4ElectronIonPair::FindG4MeanEnergyPerIonPair(), G4tgbMaterialMgr::FindOrBuildG4Material(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4RDVeLowEnergyLoss::GetLossWithFluct(), PHG4LFHcalDetector::GetScintillatorMaterial(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetScintillatorMaterial(), G4EmSaturation::InitialiseBirksCoefficient(), G4GoudsmitSaundersonTable::InitSCPCorrection(), G4hBetheBlochModel::LowEnergyLimit(), G4GDMLReadMaterials::MaterialRead(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), G4AtimaEnergyLossModel::MinEnergyCut(), G4LindhardSorensenIonModel::MinEnergyCut(), G4BetheBlochModel::MinEnergyCut(), G4MuBetheBlochModel::MinEnergyCut(), G4BraggIonModel::MinEnergyCut(), G4IonParametrisedLossModel::MinEnergyCut(), G4mplIonisationWithDeltaModel::MinEnergyCut(), G4CoulombScattering::MinPrimaryEnergy(), operator<<(), G4hImpactIonisation::PrintInfoDefinition(), G4IonFluctuations::RelativisticFactor(), G4UniversalFluctuation::SampleFluctuations(), G4IonisParamMat::SetDensityEffectParameters(), DetectorConstruction::SetPairEnergy(), DetectorConstruction::SetTankMaterial(), G4WentzelVIRelXSection::SetupKinematic(), G4WentzelOKandVIxSection::SetupKinematic(), G4EmCorrections::ShellCorrectionSTD(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and G4EmSaturation::VisibleEnergyDeposition().
G4double G4Material::GetMassOfMolecule () const inline
Definition at line 235 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 235 of file G4Material.hh
References fMassOfMolecule.
Referenced by G4DNASecondOrderReaction::BuildPhysicsTable(), G4Material(), and G4DNAMolecularMaterial::SearchMolecularMaterial().
const std::map<G4Material*,G4double>& G4Material::GetMatComponents () const inline
Definition at line 231 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 231 of file G4Material.hh
References fMatComponents.
Referenced by G4DNAModelInterface::BuildMaterialParticleModelTable(), G4DNAModelInterface::CrossSectionPerVolume(), G4DNAModelInterface::SampleSecondaries(), and G4DNAMolecularMaterial::SearchMolecularMaterial().
G4Material * G4Material::GetMaterial (const G4String & name, G4bool warning = true) static
Definition at line 651 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 651 of file G4Material.cc
References G4cout, G4endl, GetName(), and theMaterialTable.
Referenced by G4DNABrownianTransportation::BuildPhysicsTable(), G4ProductionCutsTable::CheckMaterialInfo(), PHG4PhenixDetector::Construct(), QDetectorConstruction::Construct(), MyDetectorConstruction::Construct(), RE04ParallelWorldConstruction::Construct(), B5DetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), test::ConstructGeom(), run::ConstructGeom(), test_voxel::ConstructGeom(), Lesson1::ConstructGeom(), demo::ConstructGeom(), DetectorConstruction::ConstructMaterials(), UltraDetectorConstruction::ConstructReflector(), RMC01DetectorConstruction::ConstructSimpleGeometry(), UltraDetectorConstruction::ConstructUVscope(), ElectronBenchmarkDetector::CreateExitWindow(), ElectronBenchmarkDetector::CreateHeliumBag(), ElectronBenchmarkDetector::CreateMonitor(), ElectronBenchmarkDetector::CreateScorer(), G4EzWorld::CreateWorld(), ElectronBenchmarkDetector::CreateWorld(), G4DNADummyModel::CrossSectionPerVolume(), B2aDetectorConstruction::DefineVolumes(), B2bDetectorConstruction::DefineVolumes(), B4cDetectorConstruction::DefineVolumes(), B4dDetectorConstruction::DefineVolumes(), B4DetectorConstruction::DefineVolumes(), PHG4Detector::DisplayVolume(), WLSDetectorConstruction::FindMaterial(), G4EmCalculator::FindMaterial(), PHG4Detector::GetDetectorMaterial(), ePHENIXRICH::ePHENIXRICHConstruction::GetDetectorMaterial(), BrachyMaterial::GetMat(), F04Materials::GetMaterial(), G4HumanPhantomMaterial::GetMaterial(), WLSMaterials::GetMaterial(), XrayFluoNistMaterials::GetMaterial(), Materials::GetMaterial(), G4GDMLReadMaterials::GetMaterial(), G4DNAUeharaScreenedRutherfordElasticModel::Initialise(), G4DNAScreenedRutherfordElasticModel::Initialise(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADummyModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNABornExcitationModel1::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4DNASancheExcitationModel::Initialise(), G4DNAELSEPAElasticModel::Initialise(), G4DNABornExcitationModel2::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4DNAIonElasticModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4DNATransformElectronModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4TDNAOneStepThermalizationModel< MODEL >::Initialise(), LXeMainVolume::LXeMainVolume(), LXeWLSFiber::LXeWLSFiber(), LXeWLSSlab::LXeWLSSlab(), RE04ParallelWorldParam::RE04ParallelWorldParam(), GB03DetectorConstruction::SetAbsorberMaterial(), RE06DetectorConstruction::SetAbsorberMaterial(), ExN03DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetCavityMaterial(), ExN02DetectorConstruction::setChamberMaterial(), ExP01DetectorConstruction::SetChamberMaterial(), DetectorConstruction::SetContainerMaterial(), GammaRayTelDetectorConstruction::SetConverterMaterial(), DetectorConstruction::SetCytoMaterial(), GB03DetectorConstruction::SetGapMaterial(), RE06DetectorConstruction::SetGapMaterial(), ExN03DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGasMaterial(), DetectorConstruction::SetMaterialScatter(), G4DNAMolecularMaterial::SetMolecularConfiguration(), DetectorConstruction::SetNuclMaterial(), BrachyDetectorConstruction::SetPhantomMaterial(), ElectronBenchmarkDetector::SetPrimFoilMaterial(), ExN02DetectorConstruction::setTargetMaterial(), ExP01DetectorConstruction::SetTargetMaterial(), DetectorConstruction::SetWallMaterial(), DetectorConstruction::SetWorldMaterial(), and G4ProductionCutsTable::UpdateCoupleTable().
G4Material * G4Material::GetMaterial (G4double z, G4double a, G4double dens) static
Definition at line 672 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 672 of file G4Material.cc
References GetA(), GetDensity(), GetNumberOfElements(), GetZ(), mat, and theMaterialTable.
G4Material * G4Material::GetMaterial (size_t nComp, G4double dens) static
Definition at line 687 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 687 of file G4Material.cc
References GetDensity(), GetNumberOfElements(), mat, and theMaterialTable.
G4MaterialPropertiesTable* G4Material::GetMaterialPropertiesTable () const inline
Definition at line 250 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 250 of file G4Material.hh
References fMaterialPropertiesTable.
Referenced by WLSPrimaryGeneratorAction::BuildEmissionSpectrum(), G4OpRayleigh::BuildPhysicsTable(), G4OpWLS::BuildPhysicsTable(), G4Cerenkov::BuildThePhysicsTable(), G4Scintillation::BuildThePhysicsTable(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4Track::CalculateVelocityForOpticalPhoton(), CopyPointersOfBaseMaterial(), PHG4HybridHomogeneousCalorimeterDetector::CrystalTable(), EICG4dRICHOptics::EICG4dRICHOptics(), export_G4Material(), WLSPrimaryGeneratorAction::GeneratePrimaries(), G4OpMieHG::GetMeanFreePath(), G4OpAbsorption::GetMeanFreePath(), G4OpWLS::GetMeanFreePath(), G4UCNAbsorption::GetMeanFreePath(), G4UCNMultiScattering::GetMeanFreePath(), G4UCNLoss::GetMeanFreePath(), G4OpBoundaryProcess::GetReflectivity(), G4Scintillation::GetScintillationYieldByParticleType(), PHG4SteppingAction::GetScintLightYield(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4OpMieHG::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4GDMLReadMaterials::PropertyRead(), G4GDMLWriteMaterials::PropertyWrite(), and PHG4GDMLWriteMaterials::PropertyWrite().
G4MaterialTable * G4Material::GetMaterialTable () static
Definition at line 637 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 637 of file G4Material.cc
References theMaterialTable.
Referenced by G4RDVCrossSectionHandler::ActiveElements(), G4VCrossSectionHandler::ActiveElements(), G4PixeCrossSectionHandler::ActiveElements(), G4AugerData::BuildAugerTransitionTable(), G4RDAugerData::BuildAugerTransitionTable(), G4AdjointCSManager::BuildCrossSectionMatrices(), G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), WLSPrimaryGeneratorAction::BuildEmissionSpectrum(), G4DNAModelInterface::BuildMaterialMolPerVolTable(), G4DNAModelInterface::BuildMaterialParticleModelTable(), G4ScreenedCoulombCrossSection::BuildMFPTables(), G4NistMaterialBuilder::BuildNistMaterial(), G4VLEPTSModel::BuildPhysicsTable(), G4OpRayleigh::BuildPhysicsTable(), G4OpWLS::BuildPhysicsTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4Cerenkov::BuildThePhysicsTable(), G4Scintillation::BuildThePhysicsTable(), DicomPhantomZSliceHeader::CheckMaterialExists(), G4TablesForExtrapolator::ComputeElectronDEDX(), G4VXTRenergyLoss::ComputeGasPhotoAbsCof(), G4PAIxSection::ComputeLowEnergyCof(), G4StrawTubeXTRadiator::ComputeMediumPhotoAbsCof(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4VXTRenergyLoss::ComputePlatePhotoAbsCof(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), B3DetectorConstruction::Construct(), eRositaDetectorConstruction::Construct(), G03DetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), G02DetectorConstruction::Construct(), ExErrorDetectorConstruction::Construct(), RE02DetectorConstruction::Construct(), B5DetectorConstruction::ConstructMaterials(), UltraDetectorConstruction::ConstructTableMaterials(), G4VRangeToEnergyConverter::Convert(), F04Materials::CreateMaterials(), XrayFluoNistMaterials::CreateMaterials(), RE04DetectorConstruction::DefineMaterials(), ElectronBenchmarkDetector::DefineMaterials(), GB03DetectorConstruction::DefineMaterials(), B2bDetectorConstruction::DefineMaterials(), B2aDetectorConstruction::DefineMaterials(), ExUCNDetectorConstruction::DefineMaterials(), B4cDetectorConstruction::DefineMaterials(), B4dDetectorConstruction::DefineMaterials(), RE06DetectorConstruction::DefineMaterials(), B4DetectorConstruction::DefineMaterials(), F06DetectorConstruction::DefineMaterials(), F05DetectorConstruction::DefineMaterials(), DetectorConstruction::DefineMaterials(), F02DetectorConstruction::DefineMaterials(), F01DetectorConstruction::DefineMaterials(), F03DetectorConstruction::DefineMaterials(), ExN03DetectorConstruction::DefineMaterials(), PurgMagDetectorConstruction::DefineMaterials(), GammaRayTelDetectorConstruction::DefineMaterials(), G4EmSaturation::DumpBirksCoefficients(), G4ElectronIonPair::DumpMeanEnergyPerIonPair(), export_G4Material(), CCalMaterialFactory::findG4Material(), G4NistMaterialBuilder::FindMaterial(), G4PAIxSection::G4PAIxSection(), G4SandiaTable::G4SandiaTable(), GB03DetectorMessenger::GB03DetectorMessenger(), WLSPrimaryGeneratorAction::GeneratePrimaries(), G4DNAMolecularMaterial::GetDensityTableFor(), G4VXTRenergyLoss::GetGasCompton(), G4NistManager::GetMaterial(), getMaterialTable(), G4DNAMolecularMaterial::GetNumMolPerVolTableFor(), G4VXTRenergyLoss::GetPlateCompton(), G4TablesForExtrapolator::Initialisation(), G4LEPTSElasticModel::Initialise(), G4ICRU90StoppingData::Initialise(), G4PEEffectFluoModel::Initialise(), G4ASTARStopping::Initialise(), G4PSTARStopping::Initialise(), G4PAIPhotModel::Initialise(), G4PAIModel::Initialise(), G4ICRU73QOModel::Initialise(), G4HadronXSDataTable::Initialise(), G4EmSaturation::InitialiseG4Saturation(), G4DNAMolecularMaterial::Initialize(), G4DNAMolecularMaterial::InitializeDensity(), G4GoudsmitSaundersonTable::InitMoliereMSCParams(), G4VDNAModel::IsMaterialDefine(), G03DetectorConstruction::ListOfMaterials(), G02DetectorConstruction::ListOfMaterials(), G4eIonisationParameters::LoadData(), G4RDBremsstrahlungParameters::LoadData(), G4RDeIonisationParameters::LoadData(), G4BremsstrahlungParameters::LoadData(), G4NativeScreenedCoulombCrossSection::LoadData(), main(), G4NistManager::PrintG4Material(), RE06DetectorMessenger::RE06DetectorMessenger(), DicomDetectorConstruction::ReadPhantomDataNew(), F03DetectorConstruction::SetAbsorberMaterial(), F01DetectorConstruction::SetAbsorberMaterial(), F02DetectorConstruction::SetAbsorberMaterial(), F03DetectorConstruction::SetWorldMaterial(), F02DetectorConstruction::SetWorldMaterial(), F01DetectorConstruction::SetWorldMaterial(), G4ProductionCutsTable::StoreMaterialInfo(), G4GDMLRead::StripNames(), RE06DetectorMessenger::UpdateMaterialList(), and G4NistManager::~G4NistManager().
const G4String& G4Material::GetName (void) const inline
Definition at line 171 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 171 of file G4Material.hh
References fName.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), AddMaterial(), G4GMocrenFileSceneHandler::AddSolid(), G4ErrorEnergyLoss::AlongStepDoIt(), G4VContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), XrayFluoAnalysisManager::analyseStepping(), G4hImpactIonisation::AntiProtonParametrisedDEDX(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4EmCorrections::BarkasCorrection(), RunAction::BeginOfRunAction(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PenelopeRayleighModel::BuildFormFactorTable(), G4hImpactIonisation::BuildLossTable(), G4DNAModelInterface::BuildMaterialMolPerVolTable(), G4DNAModelInterface::BuildMaterialParticleModelTable(), PHG4CylinderStripDetector::BuildMaterials(), G4PenelopeOscillatorManager::BuildOscillatorTable(), G4VLEPTSModel::BuildPhysicsTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4PenelopeBremsstrahlungModel::BuildXSTable(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4ProductionCutsTable::CheckMaterialCutsCoupleInfo(), G4EmCalculator::ComputeCrossSectionPerVolume(), G4PenelopeIonisationModel::ComputeDEDXPerVolume(), G4DensityEffectCalculator::ComputeDensityCorrection(), G4IonisParamMat::ComputeDensityEffectParameters(), G4TablesForExtrapolator::ComputeElectronDEDX(), DicomPhantomParameterisationColour::ComputeMaterial(), G4SandiaTable::ComputeMatSandiaMatrix(), G4SandiaTable::ComputeMatSandiaMatrixPAI(), G4SandiaTable::ComputeMatTable(), G4EmCalculator::ComputeMeanFreePath(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), PHG4PhenixDetector::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLeftLegBone::Construct(), G4MIRDLiver::Construct(), G4MIRDRightKidney::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDBrain::Construct(), G4MIRDRightLeg::Construct(), G4MIRDSkull::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDThyroid::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDPelvis::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightTeste::Construct(), G4MIRDThymus::Construct(), G4MIRDStomach::Construct(), G4MIRDSpleen::Construct(), G4MIRDHead::Construct(), G4MIRDTrunk::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDPancreas::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDUrinaryBladder::Construct(), G4MIRDRightArmBone::Construct(), DetectorBarr90::Construct(), DetectorHarris73::Construct(), DetectorWatase86::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), DetectorBari05::Construct(), FFDetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), F03DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), PurgMagDetectorConstruction::ConstructCalorimeter(), G4tgbVolume::ConstructG4LogVol(), DetectorConstruction::ConstructVolumes(), G4VRangeToEnergyConverter::Convert(), RE04TrajectoryPoint::CreateAttValues(), G4PhysicalVolumeModel::CreateCurrentAttValues(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4PenelopeIonisationCrossSection::CrossSection(), G4PenelopeComptonModel::CrossSectionPerVolume(), G4DNAModelInterface::CrossSectionPerVolume(), G4PenelopeBremsstrahlungModel::CrossSectionPerVolume(), G4PenelopeIonisationModel::CrossSectionPerVolume(), B2aDetectorConstruction::DefineVolumes(), B2bDetectorConstruction::DefineVolumes(), G4EmElementSelector::Dump(), G4PenelopeOscillatorManager::Dump(), G4EmSaturation::DumpBirksCoefficients(), G4ProductionCutsTable::DumpCouples(), G4CrossSectionDataStore::DumpFastPath(), G4PenelopeRayleighModel::DumpFormFactorTable(), DetectorConstruction::DumpGeometryParameters(), G4ElectronIonPair::DumpMeanEnergyPerIonPair(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4ExceptionHandler::DumpTrackInfo(), G4EmCorrections::EffectiveChargeCorrection(), Run::EndOfRun(), HistoManager::EndOfRun(), export_G4Material(), G4DensityEffectCalculator::FermiDeltaCalculation(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4EmSaturation::FindG4BirksCoefficient(), G4ElectronIonPair::FindG4MeanEnergyPerIonPair(), G4IonisParamMat::FindMeanExcitationEnergy(), G4tgbMaterialMgr::FindOrBuildG4Material(), G4PenelopeIonisationCrossSection::FindShellIDIndex(), G4ForwardXrayTR::G4ForwardXrayTR(), G4StrawTubeXTRadiator::G4StrawTubeXTRadiator(), G4VXTRenergyLoss::G4VXTRenergyLoss(), WLSPrimaryGeneratorAction::GeneratePrimaries(), GB03DetectorConstruction::GetAbsorberMaterial(), RE06DetectorConstruction::GetAbsorberMaterial(), G4PenelopeOscillatorManager::GetAtomsPerMolecule(), G4CrossSectionDataStore::GetCrossSection(), G4EmCalculator::GetCrossSectionPerVolume(), G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple(), G4EmCalculator::GetCSDARange(), G4EmCalculator::GetDEDX(), G4PenelopeIonisationXSHandler::GetDensityCorrection(), G4PenelopeBremsstrahlungFS::GetEffectiveZSquared(), G4VCrossSectionDataSet::GetElementCrossSection(), G4PenelopeRayleighModel::GetFSquared(), GB03DetectorConstruction::GetGapMaterial(), RE06DetectorConstruction::GetGapMaterial(), G4HepRepSceneHandler::getGeometryInstance(), G4ESTARStopping::GetIndex(), G4CrossSectionDataStore::GetIsoCrossSection(), G4VCrossSectionDataSet::GetIsoCrossSection(), G4EmCalculator::GetKinEnergy(), G4LatticeManager::GetLattice(), Materials::GetMaterial(), GetMaterial(), G4PenelopeOscillatorManager::GetMeanExcitationEnergy(), G4EmCalculator::GetMeanFreePath(), G4PenelopeOscillatorManager::GetNumberOfZAtomsPerMolecule(), G4DNAModelInterface::GetNumMoleculePerVolumeUnitForMaterial(), G4DNAModelInterface::GetNumMolPerVolUnitForComponentInComposite(), G4PenelopeOscillatorManager::GetOscillatorCompton(), G4PenelopeOscillatorManager::GetOscillatorIonisation(), G4PenelopeOscillatorManager::GetOscillatorTableCompton(), G4PenelopeOscillatorManager::GetOscillatorTableIonisation(), G4PenelopeOscillatorManager::GetPlasmaEnergySquared(), G4PenelopeRayleighModel::GetPMaxTable(), PhysicsList::GetRange(), G4EmCalculator::GetRangeFromRestricteDEDX(), PHG4SteppingAction::GetScintLightYield(), G4QAOLowEnergyLoss::GetShellEnergy(), G4QAOLowEnergyLoss::GetShellStrength(), G4PenelopeOscillatorManager::GetTotalA(), G4PenelopeOscillatorManager::GetTotalZ(), G4EmCorrections::HighOrderCorrections(), G4LEPTSElasticModel::Initialise(), G4ICRU90StoppingData::Initialise(), G4ASTARStopping::Initialise(), G4PSTARStopping::Initialise(), G4PAIPhotModel::Initialise(), G4PAIModel::Initialise(), G4EmModelManager::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4PenelopeBremsstrahlungFS::InitializeEnergySampling(), InitializePointers(), G4PenelopeRayleighModel::InitializeSamplingAlgorithm(), G4PenelopeGammaConversionModel::InitializeScreeningFunctions(), G4LatticeManager::LoadLattice(), main(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), operator<<(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4DNASecondOrderReaction::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), XrayFluoMercuryDetectorConstruction::PrintApparateParameters(), XrayFluoPlaneDetectorConstruction::PrintApparateParameters(), XrayFluoDetectorConstruction::PrintApparateParameters(), GB03DetectorConstruction::PrintCalorParameters(), RE06DetectorConstruction::PrintCalorParameters(), DetectorConstruction::PrintCalorParameters(), ExN03DetectorConstruction::PrintCalorParameters(), F03DetectorConstruction::PrintCalorParameters(), F02DetectorConstruction::PrintCalorParameters(), F01DetectorConstruction::PrintCalorParameters(), G4NistManager::PrintG4Material(), DetectorConstruction::PrintGeometry(), DetectorConstruction::PrintGeomParameters(), G4hImpactIonisation::PrintInfoDefinition(), GVFlashShowerParameterisation::PrintMaterial(), G4DNAMolecularMaterial::PrintNotAMolecularMaterial(), DetectorConstruction::PrintParameters(), GammaRayTelDetectorConstruction::PrintPayloadParameters(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4GDMLWriteMaterials::PropertyWrite(), PHG4GDMLWriteMaterials::PropertyWrite(), G4hImpactIonisation::ProtonParametrisedDEDX(), DicomDetectorConstruction::ReadPhantomDataFile(), DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial(), G4ExtendedMaterial::RegisterExtension(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4ExtendedMaterial::RetrieveExtension(), Run::Run(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4VLEPTSModel::SampleEnergyLoss(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4DNAModelInterface::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), F03DetectorConstruction::SetAbsorberMaterial(), F01DetectorConstruction::SetAbsorberMaterial(), F02DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetContainerMaterial(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), PHG4MvtxDetector::SetDisplayProperty(), DetectorConstruction::SetGasMaterial(), G4IonisParamMat::SetMeanExcitationEnergy(), DetectorConstruction::SetTankMaterial(), G4EmCalculator::SetupMaterial(), F03DetectorConstruction::SetWorldMaterial(), F01DetectorConstruction::SetWorldMaterial(), F02DetectorConstruction::SetWorldMaterial(), G4EnergySplitter::SplitEnergyInVolumes(), G4ProductionCutsTable::StoreMaterialCutsCoupleInfo(), G4GDMLRead::StripNames(), G4ParallelWorldProcess::SwitchMaterial(), G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight(), PHG4GDMLWriteStructure::TraverseVolumeTree(), G4GDMLWriteStructure::TraverseVolumeTree(), G4EmCalculator::UpdateParticle(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), FW::Geant4::MMSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), RE04SteppingAction::UserSteppingAction(), G4FastPathHadronicCrossSection::cycleCountEntry::~cycleCountEntry(), and G4FastPathHadronicCrossSection::fastPathEntry::~fastPathEntry().
G4double G4Material::GetNuclearInterLength () const inline
Definition at line 217 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Material.hh
References fNuclInterLen.
Referenced by CopyPointersOfBaseMaterial(), export_G4Material(), G4ErrorFreeTrajState::PropagateErrorMSC(), FW::Geant4::MMSteppingAction::UserSteppingAction(), and G4MSSteppingAction::UserSteppingAction().
size_t G4Material::GetNumberOfElements () const inline
Definition at line 180 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 180 of file G4Material.hh
References fNumberOfElements.
Referenced by G4RDVCrossSectionHandler::ActiveElements(), G4VCrossSectionHandler::ActiveElements(), G4PixeCrossSectionHandler::ActiveElements(), AddMaterial(), G4AdjointPhotoElectricModel::AdjointCrossSection(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), RunAction::BeginOfRunAction(), G4RToEConvForGamma::BuildAbsorptionLengthVector(), G4RDAugerData::BuildAugerTransitionTable(), G4AugerData::BuildAugerTransitionTable(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PenelopeRayleighModel::BuildFormFactorTable(), G4hImpactIonisation::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), DicomDetectorConstruction::BuildMaterialWithChangingDensity(), G4ScreenedCoulombCrossSection::BuildMFPTables(), G4PenelopeOscillatorManager::BuildOscillatorTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4VRangeToEnergyConverter::BuildRangeVector(), G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), G4PenelopeBremsstrahlungAngular::CalculateEffectiveZ(), G4ErrorFreeTrajState::CalculateEffectiveZandA(), CexmcHadronicProcess::CalculateTargetNucleus(), G4EmCalculator::CheckMaterial(), G4Nucleus::ChooseParameters(), G4AdjointCSManager::ComputeAdjointCS(), G4CrossSectionDataStore::ComputeCrossSection(), G4ICRU49NuclearStoppingModel::ComputeDEDXPerVolume(), G4eBremParametrizedModel::ComputeDEDXPerVolume(), G4LivermoreIonisationModel::ComputeDEDXPerVolume(), G4MuPairProductionModel::ComputeDEDXPerVolume(), G4MuBremsstrahlungModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeDensityEffectOnFly(), G4IonisParamMat::ComputeDensityEffectParameters(), G4WentzelVIRelModel::ComputeEffectiveMass(), G4IonisParamMat::ComputeFluctModel(), G4IonisParamMat::ComputeIonParameters(), G4PAIySection::ComputeLowEnergyCof(), G4PAIxSection::ComputeLowEnergyCof(), G4SandiaTable::ComputeMatSandiaMatrix(), G4SandiaTable::ComputeMatSandiaMatrixPAI(), G4SandiaTable::ComputeMatTable(), G4GammaConversionToMuons::ComputeMeanFreePath(), G4IonisParamMat::ComputeMeanParameters(), G4WentzelVIModel::ComputeSecondMoment(), G4WentzelVIModel::ComputeTransportXSectionPerVolume(), MuCrossSections::CR_Macroscopic(), RunAction::CriticalEnergy(), G4AnnihiToMuPair::CrossSectionPerVolume(), G4VEmModel::CrossSectionPerVolume(), G4ICRU73QOModel::DEDX(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), G4LowEnergyIonisation::DeexciteAtom(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecondApproximated2(), G4tgbGeometryDumper::DumpMaterial(), EICG4dRICHGas::EICG4dRICHGas(), Run::EndOfRun(), G4IonFluctuations::Factor(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4EmElementSelector::G4EmElementSelector(), G4HadElementSelector::G4HadElementSelector(), G4Material(), G4RDShellVacancy::GenerateNumberOfIonisations(), G4ShellVacancy::GenerateNumberOfIonisations(), G4HadronicProcessStore::GetCaptureCrossSectionPerVolume(), G4HadronicProcessStore::GetChargeExchangeCrossSectionPerVolume(), G4CrossSectionDataStore::GetCrossSection(), GVFlashShowerParameterisation::GetEffA(), GVFlashShowerParameterisation::GetEffZ(), G4HadronicProcessStore::GetElasticCrossSectionPerVolume(), G4HadronicProcessStore::GetFissionCrossSectionPerVolume(), G4HadronicProcessStore::GetInelasticCrossSectionPerVolume(), GetMaterial(), G4QAOLowEnergyLoss::GetShellEnergy(), G4QAOLowEnergyLoss::GetShellStrength(), G4hICRU49He::HasMaterial(), G4hSRIM2000p::HasMaterial(), G4hZiegler1985p::HasMaterial(), G4hICRU49p::HasMaterial(), G4GSPWACorrections::InitDataMaterial(), G4LivermoreRayleighModel::Initialise(), G4LivermoreGammaConversionModelRC::Initialise(), G4LivermoreNuclearGammaConversionModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermoreGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4LowEPComptonModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4HadronXSDataTable::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4VEmModel::InitialiseForMaterial(), G4PenelopeGammaConversionModel::InitializeScreeningFunctions(), G4GSMottCorrection::InitMCDataMaterial(), G4GoudsmitSaundersonTable::InitMoliereMSCParams(), G4hIonEffChargeSquare::IonEffChargeSquare(), G4QAOLowEnergyLoss::IsInCharge(), G4eIonisationParameters::LoadData(), G4RDBremsstrahlungParameters::LoadData(), G4BremsstrahlungParameters::LoadData(), G4RDeIonisationParameters::LoadData(), G4NativeScreenedCoulombCrossSection::LoadData(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4hCoulombScatteringModel::MinPrimaryEnergy(), G4eCoulombScatteringModel::MinPrimaryEnergy(), G4LindhardRobinsonPartition::PartitionNIEL(), G4VLEPTSModel::ReadParam(), G4WentzelVIModel::SampleScattering(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4CrossSectionDataStore::SampleZandA(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VCrossSectionHandler::SelectRandomAtom(), G4PixeCrossSectionHandler::SelectRandomAtom(), G4GammaConversionToMuons::SelectRandomAtom(), G4VEmModel::SelectRandomAtom(), G4VEmModel::SelectRandomAtomNumber(), G4RDVCrossSectionHandler::SelectRandomElement(), G4VCrossSectionHandler::SelectRandomElement(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), G4ElementSelector::SelectZandA(), G4EmCorrections::SetupKinematics(), G4hICRU49He::StoppingPower(), G4hSRIM2000p::StoppingPower(), G4hZiegler1985p::StoppingPower(), G4hICRU49p::StoppingPower(), G4hParametrisedLossModel::StoppingPower(), G4hNuclearStoppingModel::StoppingPower(), G4BraggModel::StoppingPower(), G4BraggIonModel::StoppingPower(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), STCyclotronDetectorConstruction::UpdateMaterial(), FW::Geant4::MMSteppingAction::UserSteppingAction(), G4RDVCrossSectionHandler::ValueForMaterial(), G4PixeCrossSectionHandler::ValueForMaterial(), G4VCrossSectionHandler::ValueForMaterial(), and G4IonYangFluctuationModel::YangFluctuationModel().
size_t G4Material::GetNumberOfMaterials () static
Definition at line 644 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 644 of file G4Material.cc
References theMaterialTable.
Referenced by G4RDVCrossSectionHandler::ActiveElements(), G4VCrossSectionHandler::ActiveElements(), G4PixeCrossSectionHandler::ActiveElements(), G4RDAugerData::BuildAugerTransitionTable(), G4AugerData::BuildAugerTransitionTable(), G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), WLSPrimaryGeneratorAction::BuildEmissionSpectrum(), G4ScreenedCoulombCrossSection::BuildMFPTables(), G4VLEPTSModel::BuildPhysicsTable(), G4OpRayleigh::BuildPhysicsTable(), G4OpWLS::BuildPhysicsTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4EnergyLossForExtrapolator::BuildTables(), G4Cerenkov::BuildThePhysicsTable(), G4Scintillation::BuildThePhysicsTable(), G4ElectronIonPair::DumpMeanEnergyPerIonPair(), export_G4Material(), G4SandiaTable::G4SandiaTable(), GB03DetectorMessenger::GB03DetectorMessenger(), G4GSPWACorrections::InitDataPerMaterials(), G4TablesForExtrapolator::Initialisation(), G4ICRU90StoppingData::Initialise(), G4PEEffectFluoModel::Initialise(), G4ASTARStopping::Initialise(), G4PSTARStopping::Initialise(), G4PAIPhotModel::Initialise(), G4PAIModel::Initialise(), G4HadronXSDataTable::Initialise(), G4EmSaturation::InitialiseG4Saturation(), G4GSMottCorrection::InitMCDataPerMaterials(), G4BremsstrahlungParameters::LoadData(), G4RDeIonisationParameters::LoadData(), G4RDBremsstrahlungParameters::LoadData(), G4eIonisationParameters::LoadData(), G4NativeScreenedCoulombCrossSection::LoadData(), RE06DetectorMessenger::RE06DetectorMessenger(), and RE06DetectorMessenger::UpdateMaterialList().
G4double G4Material::GetPressure () const inline
Definition at line 177 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 177 of file G4Material.hh
References fPressure.
Referenced by G4NistManager::BuildMaterialWithNewDensity(), G4IonisParamMat::ComputeDensityEffectParameters(), G4NistMaterialBuilder::ConstructNewGasMaterial(), PHG4Reco::DefineMaterials(), G4tgbGeometryDumper::DumpMaterial(), export_G4Material(), G4GDMLWriteMaterials::MaterialWrite(), and PHG4GDMLWriteMaterials::MaterialWrite().
G4double G4Material::GetRadlen () const inline
Definition at line 214 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 214 of file G4Material.hh
References fRadlen.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), RunAction::BeginOfRunAction(), RunAction::ComputeMscHighland(), Run::ComputeMscHighland(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), ExGflashDetectorConstruction::Construct(), ExGflashDetectorConstruction::ConstructSDandField(), CopyPointersOfBaseMaterial(), G4PhysicalVolumeModel::CreateCurrentAttValues(), RunAction::CriticalEnergy(), Run::EndOfRun(), HistoManager::EndOfRun(), Par01EMShowerModel::Explode(), export_G4Material(), Run::FillPerEvent(), G4HepRepSceneHandler::getGeometryInstance(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4PairProductionRelModel::SampleSecondaries(), ExGflashDetectorConstruction::SetMaterial(), GFlashSamplingShowerParameterisation::SetMaterial(), GFlashHomoShowerParameterisation::SetMaterial(), G4eBremsstrahlungRelModel::SetupForMaterial(), G4PairProductionRelModel::SetupForMaterial(), G4EnergyLossForExtrapolator::SetupKinematics(), DetectorConstruction::UpdateParameters(), FW::Geant4::MMSteppingAction::UserSteppingAction(), and G4MSSteppingAction::UserSteppingAction().
G4SandiaTable* G4Material::GetSandiaTable () const inline
Definition at line 223 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Material.hh
References fSandiaTable.
Referenced by G4PEEffectFluoModel::ComputeCrossSectionPerAtom(), G4VXTRenergyLoss::ComputeGasPhotoAbsCof(), G4StrawTubeXTRadiator::ComputeMediumPhotoAbsCof(), G4VXTRenergyLoss::ComputePlatePhotoAbsCof(), CopyPointersOfBaseMaterial(), G4LivermorePolarizedPhotoElectricModel::CrossSectionPerVolume(), G4LivermorePhotoElectricModel::CrossSectionPerVolume(), G4PEEffectFluoModel::CrossSectionPerVolume(), and export_G4Material().
G4State G4Material::GetState () const inline
Definition at line 175 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 175 of file G4Material.hh
References fState.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4NistManager::BuildMaterialWithNewDensity(), G4IonisParamMat::ComputeDensityEffectParameters(), G4NistMaterialBuilder::ConstructNewGasMaterial(), CopyPointersOfBaseMaterial(), G4PhysicalVolumeModel::CreateCurrentAttValues(), RunAction::CriticalEnergy(), PHG4Reco::DefineMaterials(), G4tgbGeometryDumper::DumpMaterial(), export_G4Material(), G4IonFluctuations::Factor(), G4ForwardXrayTR::GetEnergyTR(), G4HepRepSceneHandler::getGeometryInstance(), G4hICRU49He::HasMaterial(), G4hICRU49p::HasMaterial(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4hParametrisedLossModel::MolecIsInZiegler1988(), G4BraggModel::MolecIsInZiegler1988(), G4ForwardXrayTR::PostStepDoIt(), and G4IonYangFluctuationModel::YangFluctuationModel().
G4double G4Material::GetTemperature () const inline
Definition at line 176 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 176 of file G4Material.hh
References fTemp.
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDFission::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4ParticleHPChannel::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4NistManager::BuildMaterialWithNewDensity(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4ParticleHPInelasticCompFS::CompositeApply(), G4IonisParamMat::ComputeDensityEffectParameters(), G4DNABrownianTransportation::ComputeStep(), G4NistMaterialBuilder::ConstructNewGasMaterial(), PHG4Reco::DefineMaterials(), G4tgbGeometryDumper::DumpMaterial(), export_G4Material(), G4DNAElectronHoleRecombination::FindReactant(), G4Nucleus::G4Nucleus(), G4ParticleHPThermalScatteringData::GetCoherentCrossSection(), G4ParticleHPThermalScatteringData::GetCrossSection(), G4ParticleHPThermalScatteringData::GetIncoherentCrossSection(), G4ParticleHPThermalScatteringData::GetInelasticCrossSection(), G4LENDCrossSection::GetIsoCrossSection(), G4GDMLWriteMaterials::MaterialWrite(), and PHG4GDMLWriteMaterials::MaterialWrite().
G4double G4Material::GetTotNbOfAtomsPerVolume () const inline
Definition at line 203 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 203 of file G4Material.hh
References fTotNbOfAtomsPerVolume.
Referenced by G4EmCorrections::BarkasCorrection(), G4PenelopeOscillatorManager::BuildOscillatorTable(), G4Nucleus::ChooseParameters(), G4IonChuFluctuationModel::ChuFluctuationModel(), MyMollerBhabhaModel::ComputeDEDXPerVolume(), G4PenelopeBremsstrahlungModel::ComputeDEDXPerVolume(), G4PenelopeIonisationModel::ComputeDEDXPerVolume(), G4IonisParamMat::ComputeDensityEffectParameters(), CopyPointersOfBaseMaterial(), G4MuElecElasticModel::CrossSectionPerVolume(), G4MicroElecElasticModel::CrossSectionPerVolume(), G4MuElecInelasticModel::CrossSectionPerVolume(), G4PenelopeComptonModel::CrossSectionPerVolume(), G4MicroElecInelasticModel::CrossSectionPerVolume(), G4PenelopeBremsstrahlungModel::CrossSectionPerVolume(), G4PenelopeIonisationModel::CrossSectionPerVolume(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), G4hImpactIonisation::ElectronicLossFluctuation(), Run::EndOfRun(), export_G4Material(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4UCNAbsorption::GetMeanFreePath(), G4UCNMultiScattering::GetMeanFreePath(), G4UCNLoss::GetMeanFreePath(), G4GSPWACorrections::InitDataMaterial(), G4PenelopeGammaConversionModel::InitializeScreeningFunctions(), G4GSMottCorrection::InitMCDataMaterial(), G4GoudsmitSaundersonTable::InitMoliereMSCParams(), G4EmCorrections::KShellCorrection(), G4EmCorrections::LShellCorrection(), G4hParametrisedLossModel::MolecIsInZiegler1988(), G4BraggModel::MolecIsInZiegler1988(), G4ScreenedNuclearRecoil::PostStepDoIt(), G4VEmModel::SelectRandomAtomNumber(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), G4EmCorrections::ShellCorrection(), G4hICRU49He::StoppingPower(), G4hParametrisedLossModel::StoppingPower(), and G4IonYangFluctuationModel::YangFluctuationModel().
G4double G4Material::GetTotNbOfElectPerVolume () const inline
Definition at line 206 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 206 of file G4Material.hh
References fTotNbOfElectPerVolume.
Referenced by G4IonisParamMat::ComputeDensityEffectParameters(), G4IonisParamMat::ComputeMeanParameters(), CopyPointersOfBaseMaterial(), G4BraggIonModel::DEDX(), export_G4Material(), G4BremsstrahlungParameters::LoadData(), G4RDBremsstrahlungParameters::LoadData(), and G4hICRU49He::StoppingPower().
const G4double* G4Material::GetVecNbOfAtomsPerVolume () const inline
Definition at line 200 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 200 of file G4Material.hh
References fVecNbOfAtomsPerVolume.
Referenced by G4AdjointPhotoElectricModel::AdjointCrossSection(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4ScreenedCoulombCrossSection::BuildMFPTables(), G4Nucleus::ChooseParameters(), G4AdjointCSManager::ComputeAdjointCS(), G4CrossSectionDataStore::ComputeCrossSection(), G4IonisParamMat::ComputeDensityEffectParameters(), G4SandiaTable::ComputeMatSandiaMatrix(), G4GammaConversionToMuons::ComputeMeanFreePath(), G4IonisParamMat::ComputeMeanParameters(), G4WentzelVIModel::ComputeSecondMoment(), G4WentzelVIModel::ComputeTransportXSectionPerVolume(), CopyPointersOfBaseMaterial(), MuCrossSections::CR_Macroscopic(), G4AnnihiToMuPair::CrossSectionPerVolume(), G4VEmModel::CrossSectionPerVolume(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4HadronicProcessStore::GetCaptureCrossSectionPerVolume(), G4HadronicProcessStore::GetChargeExchangeCrossSectionPerVolume(), G4CrossSectionDataStore::GetCrossSection(), G4HadronicProcessStore::GetElasticCrossSectionPerVolume(), G4HadronicProcessStore::GetFissionCrossSectionPerVolume(), G4HadronicProcessStore::GetInelasticCrossSectionPerVolume(), G4GSPWACorrections::InitDataMaterial(), G4EmElementSelector::Initialise(), G4EmSaturation::InitialiseBirksCoefficient(), G4PenelopeGammaConversionModel::InitializeScreeningFunctions(), G4GSMottCorrection::InitMCDataMaterial(), G4GoudsmitSaundersonTable::InitMoliereMSCParams(), G4LindhardRobinsonPartition::PartitionNIEL(), G4GammaConversionToMuons::SelectRandomAtom(), G4VEmModel::SelectRandomAtomNumber(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), G4RDVCrossSectionHandler::ValueForMaterial(), G4PixeCrossSectionHandler::ValueForMaterial(), and G4VCrossSectionHandler::ValueForMaterial().
G4double G4Material::GetZ () const
Definition at line 701 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 701 of file G4Material.cc
References FatalException, fName, fNumberOfElements, G4cout, G4Exception(), and theElementVector.
Referenced by RunAction::BeginOfRunAction(), RunAction::CriticalEnergy(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), G4tgbGeometryDumper::DumpMaterial(), export_G4Material(), GVFlashShowerParameterisation::GetEffZ(), GetMaterial(), G4QAOLowEnergyLoss::GetNumberOfShell(), G4QAOLowEnergyLoss::GetShellEnergy(), G4QAOLowEnergyLoss::GetShellStrength(), G4hIonEffChargeSquare::IonEffChargeSquare(), main(), G4GDMLWriteMaterials::MaterialWrite(), PHG4GDMLWriteMaterials::MaterialWrite(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VCrossSectionHandler::SelectRandomAtom(), G4PixeCrossSectionHandler::SelectRandomAtom(), G4hSRIM2000p::StoppingPower(), G4hICRU49He::StoppingPower(), G4hICRU49p::StoppingPower(), G4hZiegler1985p::StoppingPower(), G4hParametrisedLossModel::StoppingPower(), G4BraggModel::StoppingPower(), G4BraggIonModel::StoppingPower(), and FW::Geant4::MMSteppingAction::UserSteppingAction().
void G4Material::InitializePointers () private
Definition at line 253 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 253 of file G4Material.cc
References fArrayLength, fAtomsVector, fBaseMaterial, fChemicalFormula, fDensity, fFreeElecDensity, fIndexInTable, fIonisation, fMassFractionVector, fMassOfMolecule, fMaterialPropertiesTable, fName, fNuclInterLen, fNumberOfComponents, fNumberOfElements, fPressure, fRadlen, fSandiaTable, fState, fTemp, fTotNbOfAtomsPerVolume, fTotNbOfElectPerVolume, fVecNbOfAtomsPerVolume, G4cout, G4endl, GetName(), kStateUndefined, maxNbComponents, theElementVector, and theMaterialTable.
Referenced by G4Material().
G4bool G4Material::IsExtended () const virtual
Reimplemented in G4ExtendedMaterial.
Definition at line 795 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 795 of file G4Material.cc
Referenced by operator<<().
G4bool G4Material::operator!= (const G4Material &) const private
const G4Material& G4Material::operator= (const G4Material &) private
G4bool G4Material::operator== (const G4Material &) const private
void G4Material::SetChemicalFormula (const G4String & chF)
Definition at line 597 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 597 of file G4Material.cc
References fChemicalFormula, G4MUTEXLOCK, and G4MUTEXUNLOCK.
Referenced by G4NistMaterialBuilder::BuildMaterial(), and export_G4Material().
void G4Material::SetFreeElectronDensity (G4double val)
Definition at line 610 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 610 of file G4Material.cc
References fFreeElecDensity, G4MUTEXLOCK, and G4MUTEXUNLOCK.
void G4Material::SetMaterialPropertiesTable (G4MaterialPropertiesTable * anMPT)
Definition at line 802 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 802 of file G4Material.cc
References fMaterialPropertiesTable, G4MUTEXLOCK, and G4MUTEXUNLOCK.
Referenced by OpNoviceDetectorConstruction::Construct(), UltraDetectorConstruction::ConstructTableMaterials(), WLSMaterials::CreateMaterials(), PHG4HybridHomogeneousCalorimeterDetector::CrystalTable(), ExUCNDetectorConstruction::DefineMaterials(), LXeDetectorConstruction::DefineMaterials(), G4EicDircDetector::DefineMaterials(), PHG4Reco::DefineMaterials(), export_G4Material(), PHG4ForwardDualReadoutDetector::GetPMMAMaterial(), PHG4ForwardDualReadoutDetector::GetQuartzMaterial(), PHG4LFHcalDetector::GetScintillatorMaterial(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetScintillatorMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetVM2000Material(), PHG4ForwardEcalDetector::GetWLSFiberFEMCMaterial(), PHG4LFHcalDetector::GetWLSFiberMaterial(), G4GDMLReadMaterials::PropertyRead(), EICG4dRICHOptics::setMatPropTable(), and DetectorConstruction::SetTankMaterial().
void G4Material::SetName (const G4String & name) inline
Definition at line 283 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 283 of file G4Material.hh
References fName.
Referenced by export_G4Material(), and G4GDMLRead::StripNames().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & flux, const G4Material * material) friend
Definition at line 727 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 727 of file G4Material.cc
std::ostream& operator<< (std::ostream & flux, const G4Material & material) friend
Definition at line 772 of file G4Material.cc.
View newest version in sPHENIX GitHub at line 772 of file G4Material.cc
std::ostream& operator<< (std::ostream & flux, G4MaterialTable ElementTable) friend
Definition at line 466 of file G4Element.cc.
View newest version in sPHENIX GitHub at line 466 of file G4Element.cc
Member Data Documentation
G4int G4Material::fArrayLength private
Definition at line 347 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 347 of file G4Material.hh
Referenced by AddElement(), AddMaterial(), G4Material(), and InitializePointers().
G4int* G4Material::fAtomsVector private
Definition at line 316 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 316 of file G4Material.hh
Referenced by AddElement(), AddMaterial(), CopyPointersOfBaseMaterial(), GetAtomsVector(), InitializePointers(), and ~G4Material().
const G4Material* G4Material::fBaseMaterial private
Definition at line 311 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 311 of file G4Material.hh
Referenced by CopyPointersOfBaseMaterial(), G4Material(), GetBaseMaterial(), InitializePointers(), and ~G4Material().
G4String G4Material::fChemicalFormula private
Definition at line 356 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 356 of file G4Material.hh
Referenced by G4Material(), GetChemicalFormula(), InitializePointers(), operator<<(), and SetChemicalFormula().
G4double G4Material::fDensity private
Definition at line 331 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 331 of file G4Material.hh
Referenced by ComputeDerivedQuantities(), CopyPointersOfBaseMaterial(), G4Material(), GetDensity(), InitializePointers(), and operator<<().
G4double G4Material::fFreeElecDensity private
Definition at line 332 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 332 of file G4Material.hh
Referenced by ComputeDerivedQuantities(), CopyPointersOfBaseMaterial(), GetFreeElectronDensity(), InitializePointers(), and SetFreeElectronDensity().
size_t G4Material::fIndexInTable private
Definition at line 344 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 344 of file G4Material.hh
Referenced by GetIndex(), InitializePointers(), and ~G4Material().
G4IonisParamMat* G4Material::fIonisation private
Definition at line 328 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 328 of file G4Material.hh
Referenced by ComputeDensityEffectOnFly(), ComputeDerivedQuantities(), CopyPointersOfBaseMaterial(), GetIonisation(), InitializePointers(), and ~G4Material().
G4double* G4Material::fMassFractionVector private
Definition at line 315 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 315 of file G4Material.hh
Referenced by AddElement(), AddMaterial(), ComputeDerivedQuantities(), CopyPointersOfBaseMaterial(), G4Material(), GetFractionVector(), InitializePointers(), operator<<(), and ~G4Material().
G4double G4Material::fMassOfMolecule private
Definition at line 340 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 340 of file G4Material.hh
Referenced by AddElement(), G4Material(), GetMassOfMolecule(), and InitializePointers().
std::map<G4Material*,G4double> G4Material::fMatComponents private
Definition at line 352 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 352 of file G4Material.hh
Referenced by AddMaterial(), and GetMatComponents().
G4MaterialPropertiesTable* G4Material::fMaterialPropertiesTable private
Definition at line 312 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 312 of file G4Material.hh
Referenced by CopyPointersOfBaseMaterial(), GetMaterialPropertiesTable(), InitializePointers(), and SetMaterialPropertiesTable().
G4String G4Material::fName private
Definition at line 355 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 355 of file G4Material.hh
Referenced by AddElement(), AddMaterial(), GetA(), GetName(), GetZ(), InitializePointers(), operator<<(), and SetName().
G4double G4Material::fNuclInterLen private
Definition at line 339 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 339 of file G4Material.hh
Referenced by ComputeNuclearInterLength(), CopyPointersOfBaseMaterial(), GetNuclearInterLength(), InitializePointers(), and operator<<().
G4int G4Material::fNumberOfComponents private
Definition at line 348 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 348 of file G4Material.hh
Referenced by AddElement(), AddMaterial(), G4Material(), and InitializePointers().
G4int G4Material::fNumberOfElements private
Definition at line 350 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 350 of file G4Material.hh
Referenced by AddElement(), AddMaterial(), ComputeDerivedQuantities(), ComputeNuclearInterLength(), ComputeRadiationLength(), CopyPointersOfBaseMaterial(), G4Material(), GetA(), GetNumberOfElements(), GetZ(), InitializePointers(), and operator<<().
G4double G4Material::fPressure private
Definition at line 334 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 334 of file G4Material.hh
Referenced by G4Material(), GetPressure(), InitializePointers(), and operator<<().
G4double G4Material::fRadlen private
Definition at line 338 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 338 of file G4Material.hh
Referenced by ComputeRadiationLength(), CopyPointersOfBaseMaterial(), GetRadlen(), InitializePointers(), and operator<<().
G4SandiaTable* G4Material::fSandiaTable private
Definition at line 329 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 329 of file G4Material.hh
Referenced by ComputeDerivedQuantities(), CopyPointersOfBaseMaterial(), GetSandiaTable(), InitializePointers(), and ~G4Material().
G4State G4Material::fState private
Definition at line 342 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 342 of file G4Material.hh
Referenced by ComputeDerivedQuantities(), CopyPointersOfBaseMaterial(), G4Material(), GetState(), and InitializePointers().
G4double G4Material::fTemp private
Definition at line 333 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 333 of file G4Material.hh
Referenced by G4Material(), GetTemperature(), InitializePointers(), and operator<<().
G4double G4Material::fTotNbOfAtomsPerVolume private
Definition at line 336 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 336 of file G4Material.hh
Referenced by ComputeDerivedQuantities(), CopyPointersOfBaseMaterial(), GetTotNbOfAtomsPerVolume(), InitializePointers(), and operator<<().
G4double G4Material::fTotNbOfElectPerVolume private
Definition at line 337 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 337 of file G4Material.hh
Referenced by ComputeDerivedQuantities(), CopyPointersOfBaseMaterial(), GetElectronDensity(), GetTotNbOfElectPerVolume(), and InitializePointers().
G4double* G4Material::fVecNbOfAtomsPerVolume private
Definition at line 326 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 326 of file G4Material.hh
Referenced by ComputeDerivedQuantities(), ComputeNuclearInterLength(), ComputeRadiationLength(), CopyPointersOfBaseMaterial(), GetAtomicNumDensityVector(), GetVecNbOfAtomsPerVolume(), InitializePointers(), operator<<(), and ~G4Material().
G4int G4Material::maxNbComponents private
Definition at line 346 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 346 of file G4Material.hh
Referenced by AddElement(), AddMaterial(), G4Material(), and InitializePointers().
G4ElementVector* G4Material::theElementVector private
Definition at line 314 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 314 of file G4Material.hh
Referenced by AddElement(), AddMaterial(), CopyPointersOfBaseMaterial(), G4Material(), GetA(), GetElement(), GetElementVector(), GetZ(), InitializePointers(), operator<<(), and ~G4Material().
G4MaterialTable G4Material::theMaterialTable static private
Definition at line 319 of file G4Material.hh.
View newest version in sPHENIX GitHub at line 319 of file G4Material.hh
Referenced by GetMaterial(), GetMaterialTable(), GetNumberOfMaterials(), InitializePointers(), and ~G4Material().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4Material.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4Material.cc