ECCE @ EIC Software: RE05PrimaryGeneratorAction Class Reference
RE05PrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05PrimaryGeneratorAction.hh>
Public Member Functions
RE05PrimaryGeneratorAction ()
virtual ~RE05PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
void SetHEPEvtGenerator (G4bool option)
G4bool GetHEPEvtGenerator ()
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4VPrimaryGenerator * fParticleGun
RE05PrimaryGeneratorMessenger * fMessenger
G4bool fUseHEPEvt
Static Private Attributes
static G4VPrimaryGenerator * fHEPEvt = 0
Detailed Description
Definition at line 41 of file RE05PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 41 of file RE05PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
RE05PrimaryGeneratorAction::RE05PrimaryGeneratorAction ()
Definition at line 51 of file RE05PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 51 of file RE05PrimaryGeneratorAction.cc
References cm, fHEPEvt, INPUTHEPMC::filename, G4ParticleTable::FindParticle(), fMessenger, fParticleGun, fUseHEPEvt, G4ParticleTable::GetParticleTable(), GeV, particle, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), and G4TemplateAutoLock< _Mutex_t >::unlock().
RE05PrimaryGeneratorAction::~RE05PrimaryGeneratorAction () virtual
Definition at line 83 of file RE05PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 83 of file RE05PrimaryGeneratorAction.cc
References fHEPEvt, fMessenger, and fParticleGun.
Member Function Documentation
void RE05PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 93 of file RE05PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 93 of file RE05PrimaryGeneratorAction.cc
References fHEPEvt, fParticleGun, fUseHEPEvt, and G4VPrimaryGenerator::GeneratePrimaryVertex().
G4bool RE05PrimaryGeneratorAction::GetHEPEvtGenerator () inline
Definition at line 59 of file RE05PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file RE05PrimaryGeneratorAction.hh
References fUseHEPEvt.
Referenced by RE05PrimaryGeneratorMessenger::GetCurrentValue().
void RE05PrimaryGeneratorAction::SetHEPEvtGenerator (G4bool option) inline
Definition at line 57 of file RE05PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file RE05PrimaryGeneratorAction.hh
References fUseHEPEvt.
Referenced by RE05PrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
G4VPrimaryGenerator * RE05PrimaryGeneratorAction::fHEPEvt = 0 static private
Definition at line 51 of file RE05PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 51 of file RE05PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), RE05PrimaryGeneratorAction(), and ~RE05PrimaryGeneratorAction().
RE05PrimaryGeneratorMessenger* RE05PrimaryGeneratorAction::fMessenger private
Definition at line 53 of file RE05PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 53 of file RE05PrimaryGeneratorAction.hh
Referenced by RE05PrimaryGeneratorAction(), and ~RE05PrimaryGeneratorAction().
G4VPrimaryGenerator* RE05PrimaryGeneratorAction::fParticleGun private
Definition at line 52 of file RE05PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file RE05PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), RE05PrimaryGeneratorAction(), and ~RE05PrimaryGeneratorAction().
G4bool RE05PrimaryGeneratorAction::fUseHEPEvt private
Definition at line 54 of file RE05PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 54 of file RE05PrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetHEPEvtGenerator(), RE05PrimaryGeneratorAction(), and SetHEPEvtGenerator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/src/RE05PrimaryGeneratorAction.cc