ECCE @ EIC Software: G4ParameterisationParaX Class Reference
G4ParameterisationParaX Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPara.hh>
Public Member Functions
G4ParameterisationParaX (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
~G4ParameterisationParaX ()
G4double GetMaxParameter () const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Para &para, const G4int copyNo, const G4VPhysicalVolume *pv) const
Public Member Functions inherited from G4VParameterisationPara
G4VParameterisationPara (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
virtual ~G4VParameterisationPara ()
Public Member Functions inherited from G4VDivisionParameterisation
G4VDivisionParameterisation (EAxis axis, G4int nDiv, G4double width, G4double offset, DivisionType divType, G4VSolid *motherSolid=nullptr)
virtual ~G4VDivisionParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
const G4String & GetType () const
EAxis GetAxis () const
G4int GetNoDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4VSolid * GetMotherSolid () const
void SetType (const G4String &type)
G4int VolumeFirstCopyNo () const
void SetHalfGap (G4double hg)
G4double GetHalfGap () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Additional Inherited Members
Protected Member Functions inherited from G4VDivisionParameterisation
void ChangeRotMatrix (G4VPhysicalVolume *physVol, G4double rotZ=0.0) const
G4int CalculateNDiv (G4double motherDim, G4double width, G4double offset) const
G4double CalculateWidth (G4double motherDim, G4int nDiv, G4double offset) const
virtual void CheckParametersValidity ()
void CheckOffset (G4double maxPar)
void CheckNDivAndWidth (G4double maxPar)
G4double OffsetZ () const
Protected Attributes inherited from G4VDivisionParameterisation
G4String ftype
EAxis faxis
G4int fnDiv = 0
G4double fwidth = 0.0
G4double foffset = 0.0
DivisionType fDivisionType
G4VSolid * fmotherSolid = nullptr
G4bool fReflectedSolid = false
G4bool fDeleteSolid = false
G4int theVoluFirstCopyNo = 1
G4double kCarTolerance
G4double fhgap = 0.0
Static Protected Attributes inherited from G4VDivisionParameterisation
static G4ThreadLocal
G4RotationMatrix * fRot = nullptr
static const G4int verbose = 5
Detailed Description
Definition at line 69 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParameterisationPara.hh
Constructor & Destructor Documentation
G4ParameterisationParaX::G4ParameterisationParaX (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid * msolid, DivisionType divType)
Definition at line 85 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ParameterisationPara.cc
References G4VDivisionParameterisation::CalculateNDiv(), G4VDivisionParameterisation::CalculateWidth(), G4VDivisionParameterisation::CheckParametersValidity(), DivNDIV, DivWIDTH, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Para::GetXHalfLength(), offset, G4VDivisionParameterisation::SetType(), and G4VDivisionParameterisation::verbose.
G4ParameterisationParaX::~G4ParameterisationParaX ()
Definition at line 122 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 122 of file G4ParameterisationPara.cc
Member Function Documentation
void G4ParameterisationParaX::ComputeDimensions (G4Para & para, const G4int copyNo, const G4VPhysicalVolume * pv) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 155 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 155 of file G4ParameterisationPara.cc
References G4VSolid::DumpInfo(), G4VDivisionParameterisation::fhgap, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Para::GetSymAxis(), G4Para::GetTanAlpha(), G4Para::GetYHalfLength(), G4Para::GetZHalfLength(), CLHEP::Hep3Vector::phi(), G4Para::SetAllParameters(), CLHEP::Hep3Vector::theta(), and G4VDivisionParameterisation::verbose.
void G4ParameterisationParaX::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 88 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 90 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 92 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 94 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 96 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 98 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 100 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 102 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 104 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 106 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 108 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 110 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParameterisationPara.hh
void G4ParameterisationParaX::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VDivisionParameterisation.
Definition at line 129 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 129 of file G4ParameterisationPara.cc
References G4VDivisionParameterisation::faxis, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::foffset, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Para::GetXHalfLength(), Acts::Test::origin(), G4VPhysicalVolume::SetTranslation(), CLHEP::Hep3Vector::setX(), and G4VDivisionParameterisation::verbose.
G4double G4ParameterisationParaX::GetMaxParameter () const virtual
Implements G4VDivisionParameterisation.
Definition at line 115 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 115 of file G4ParameterisationPara.cc
References G4VDivisionParameterisation::fmotherSolid, and G4Para::GetXHalfLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPara.hh
geant4/tree/geant4-10.6-release/source/geometry/divisions/src/G4ParameterisationPara.cc