ECCE @ EIC Software: G4VisModelManager< typename > Class Template Reference
G4VisModelManager< typename > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisManager.hh>
Public Types
typedef G4VisListManager< Model > List
typedef G4VModelFactory< Model > Factory
Public Member Functions
G4VisModelManager (const G4String &)
virtual ~G4VisModelManager ()
void Register (Model *)
void Register (Factory *)
void SetCurrent (const G4String &)
const Model * Current () const
G4String Placement () const
void Print (std::ostream &ostr, const G4String &name="") const
const List * ListManager () const
const std::vector< Factory * > & FactoryList () const
Private Member Functions
G4VisModelManager (const G4VisModelManager &)
G4VisModelManager & operator= (const G4VisModelManager &)
Private Attributes
G4String fPlacement
List * fpModelList
std::vector< Factory * > fFactoryList
std::vector< G4UImessenger * > fMessengerList
Detailed Description
template<typename>
class G4VisModelManager< typename >
Definition at line 113 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VisManager.hh
Member Typedef Documentation
template<typename > typedef G4VModelFactory<Model> G4VisModelManager< typename >::Factory
Definition at line 48 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VisModelManager.hh
template<typename > typedef G4VisListManager<Model> G4VisModelManager< typename >::List
Definition at line 47 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VisModelManager.hh
Constructor & Destructor Documentation
template<typename Model > G4VisModelManager< Model >::G4VisModelManager (const G4String & placement)
Definition at line 87 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VisModelManager.hh
template<typename Model > G4VisModelManager< Model >::~G4VisModelManager () virtual
Definition at line 93 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VisModelManager.hh
template<typename > G4VisModelManager< typename >::G4VisModelManager (const G4VisModelManager< typename > &) private
Member Function Documentation
template<typename Model > const Model * G4VisModelManager< Model >::Current () const
Definition at line 140 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 140 of file G4VisModelManager.hh
Referenced by G4VisManager::CurrentTrajDrawModel().
template<typename Model > const std::vector< G4VModelFactory< Model > * > & G4VisModelManager< Model >::FactoryList () const
Definition at line 182 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 182 of file G4VisModelManager.hh
Referenced by G4VisManager::PrintAvailableModels().
template<typename Model > const G4VisListManager< Model > * G4VisModelManager< Model >::ListManager () const
Definition at line 175 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 175 of file G4VisModelManager.hh
Referenced by G4VisManager::PrintAvailableModels().
template<typename > G4VisModelManager& G4VisModelManager< typename >::operator= (const G4VisModelManager< typename > &) private
template<typename Model > G4String G4VisModelManager< Model >::Placement () const
Definition at line 147 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 147 of file G4VisModelManager.hh
Referenced by G4VisManager::RegisterMessengers().
template<typename Model > void G4VisModelManager< Model >::Print (std::ostream & ostr, const G4String & name = "") const
Definition at line 154 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 154 of file G4VisModelManager.hh
template<typename Model > void G4VisModelManager< Model >::Register (Model * model)
Definition at line 115 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 115 of file G4VisModelManager.hh
Referenced by G4VisManager::CurrentTrajDrawModel(), G4VisManager::RegisterModel(), and G4VisManager::RegisterModelFactory().
template<typename Model > void G4VisModelManager< Model >::Register (Factory * factory)
Definition at line 122 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 122 of file G4VisModelManager.hh
template<typename Model > void G4VisModelManager< Model >::SetCurrent (const G4String & model)
Definition at line 133 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 133 of file G4VisModelManager.hh
Referenced by G4VisManager::SelectTrajectoryModel().
Member Data Documentation
template<typename > std::vector<Factory*> G4VisModelManager< typename >::fFactoryList private
Definition at line 81 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VisModelManager.hh
template<typename > std::vector<G4UImessenger*> G4VisModelManager< typename >::fMessengerList private
Definition at line 82 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VisModelManager.hh
template<typename > G4String G4VisModelManager< typename >::fPlacement private
Definition at line 79 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VisModelManager.hh
template<typename > List* G4VisModelManager< typename >::fpModelList private
Definition at line 80 of file G4VisModelManager.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VisModelManager.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisManager.hh
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisModelManager.hh