ECCE @ EIC Software: G4INCL::NuclearDensity Class Reference
G4INCL::NuclearDensity Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNuclearDensity.hh>
Public Member Functions
NuclearDensity (const G4int A, const G4int Z, const G4int S, InterpolationTable const *const rpCorrelationTableProton, InterpolationTable const *const rpCorrelationTableNeutron, InterpolationTable const *const rpCorrelationTableLambda)
~NuclearDensity ()
NuclearDensity (const NuclearDensity &rhs)
Copy constructor.
NuclearDensity & operator= (const NuclearDensity &rhs)
Assignment operator.
void swap (NuclearDensity &rhs)
Helper method for the assignment operator.
G4double getMaxRFromP (const ParticleType t, const G4double p) const
Get the maximum allowed radius for a given momentum.
G4double getMinPFromR (const ParticleType t, const G4double r) const
G4double getMaximumRadius () const
G4double getTransmissionRadius (Particle const *const p) const
The radius used for calculating the transmission coefficient.
G4double getTransmissionRadius (ParticleType type) const
The radius used for calculating the transmission coefficient.
G4int getA () const
Get the mass number.
G4int getZ () const
Get the charge number.
G4int getS () const
Get the strange number.
G4double getProtonNuclearRadius () const
void setProtonNuclearRadius (const G4double r)
Private Member Functions
void initializeTransmissionRadii ()
Initialize the transmission radius.
Private Attributes
G4int theA
G4int theZ
G4int theS
G4double theMaximumRadius
G4double theProtonNuclearRadius
Represents INCL4.5's R0 variable.
G4double transmissionRadius [UnknownParticle]
InterpolationTable const * rFromP [UnknownParticle]
InterpolationTable const * pFromR [UnknownParticle]
Detailed Description
Definition at line 54 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 54 of file G4INCLNuclearDensity.hh
Constructor & Destructor Documentation
G4INCL::NuclearDensity::NuclearDensity (const G4int A, const G4int Z, const G4int S, InterpolationTable const *const rpCorrelationTableProton, InterpolationTable const *const rpCorrelationTableNeutron, InterpolationTable const *const rpCorrelationTableLambda)
Definition at line 45 of file G4INCLNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 45 of file G4INCLNuclearDensity.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, INCL_DEBUG, initializeTransmissionRadii(), G4INCL::Lambda, G4INCL::Neutron, pFromR, print(), G4INCL::Proton, rFromP, theA, theS, theZ, and G4INCL::UnknownParticle.
G4INCL::NuclearDensity::~NuclearDensity ()
Definition at line 101 of file G4INCLNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 101 of file G4INCLNuclearDensity.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Lambda, G4INCL::Neutron, pFromR, and G4INCL::Proton.
G4INCL::NuclearDensity::NuclearDensity (const NuclearDensity & rhs)
Copy constructor.
Definition at line 113 of file G4INCLNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 113 of file G4INCLNuclearDensity.cc
References field_utils::copy(), G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Lambda, G4INCL::Neutron, pFromR, G4INCL::Proton, rFromP, transmissionRadius, and G4INCL::UnknownParticle.
Member Function Documentation
G4int G4INCL::NuclearDensity::getA () const inline
Get the mass number.
Definition at line 104 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 104 of file G4INCLNuclearDensity.hh
References theA.
G4double G4INCL::NuclearDensity::getMaximumRadius () const inline
Definition at line 78 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 78 of file G4INCLNuclearDensity.hh
References theMaximumRadius.
Referenced by G4INCL::KinematicsUtils::getLocalEnergy().
G4double G4INCL::NuclearDensity::getMaxRFromP (const ParticleType t, const G4double p) const
Get the maximum allowed radius for a given momentum.
Parameters
t type of the particle
p absolute value of the particle momentum, divided by the relevant Fermi momentum.
Returns
maximum allowed radius.
Definition at line 188 of file G4INCLNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 188 of file G4INCLNuclearDensity.cc
References rFromP.
Referenced by G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::Nucleus::getSurfaceRadius(), G4INCL::ParticleSampler::sampleOneParticleWithFuzzyRPCorrelation(), and G4INCL::ParticleSampler::sampleOneParticleWithRPCorrelation().
G4double G4INCL::NuclearDensity::getMinPFromR (const ParticleType t, const G4double r) const
Definition at line 193 of file G4INCLNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 193 of file G4INCLNuclearDensity.cc
References pFromR, and r.
Referenced by G4INCL::KinematicsUtils::getLocalEnergy().
G4double G4INCL::NuclearDensity::getProtonNuclearRadius () const inline
Definition at line 112 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 112 of file G4INCLNuclearDensity.hh
References theProtonNuclearRadius.
Referenced by G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), and G4INCL::ClusteringModelIntercomparison::getCluster().
G4int G4INCL::NuclearDensity::getS () const inline
Get the strange number.
Definition at line 110 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 110 of file G4INCLNuclearDensity.hh
References theS.
G4double G4INCL::NuclearDensity::getTransmissionRadius (Particle const *const p) const inline
The radius used for calculating the transmission coefficient.
Returns
the radius
Definition at line 84 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 84 of file G4INCLNuclearDensity.hh
References G4INCL::Composite, G4INCL::Particle::getA(), G4INCL::ParticleTable::getNuclearRadius(), G4INCL::Particle::getType(), G4INCL::Particle::getZ(), t, and transmissionRadius.
Referenced by G4INCL::CoulombNonRelativistic::distortOut(), and G4INCL::Nucleus::getTransmissionBarrier().
G4double G4INCL::NuclearDensity::getTransmissionRadius (ParticleType type) const inline
The radius used for calculating the transmission coefficient.
Returns
the radius
Definition at line 98 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 98 of file G4INCLNuclearDensity.hh
References transmissionRadius.
G4int G4INCL::NuclearDensity::getZ () const inline
Get the charge number.
Definition at line 107 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 107 of file G4INCLNuclearDensity.hh
References theZ.
void G4INCL::NuclearDensity::initializeTransmissionRadii () private
Initialize the transmission radius.
Definition at line 169 of file G4INCLNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 169 of file G4INCLNuclearDensity.cc
References G4INCL::Composite, G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::KMinus, G4INCL::KPlus, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, theProtonNuclearRadius, and transmissionRadius.
Referenced by NuclearDensity().
NuclearDensity & G4INCL::NuclearDensity::operator= (const NuclearDensity & rhs)
Assignment operator.
Definition at line 141 of file G4INCLNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 141 of file G4INCLNuclearDensity.cc
References swap().
void G4INCL::NuclearDensity::setProtonNuclearRadius (const G4double r) inline
Definition at line 113 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 113 of file G4INCLNuclearDensity.hh
References r, and theProtonNuclearRadius.
void G4INCL::NuclearDensity::swap (NuclearDensity & rhs)
Helper method for the assignment operator.
Definition at line 147 of file G4INCLNuclearDensity.cc.
View newest version in sPHENIX GitHub at line 147 of file G4INCLNuclearDensity.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Lambda, G4INCL::Neutron, pFromR, G4INCL::Proton, rFromP, boost::swap(), theA, theMaximumRadius, theProtonNuclearRadius, theS, theZ, transmissionRadius, and G4INCL::UnknownParticle.
Referenced by operator=().
Member Data Documentation
InterpolationTable const* G4INCL::NuclearDensity::pFromR[UnknownParticle] private
Definition at line 129 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 129 of file G4INCLNuclearDensity.hh
Referenced by getMinPFromR(), NuclearDensity(), swap(), and ~NuclearDensity().
InterpolationTable const* G4INCL::NuclearDensity::rFromP[UnknownParticle] private
Definition at line 128 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 128 of file G4INCLNuclearDensity.hh
Referenced by getMaxRFromP(), NuclearDensity(), and swap().
G4int G4INCL::NuclearDensity::theA private
Definition at line 120 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 120 of file G4INCLNuclearDensity.hh
Referenced by getA(), NuclearDensity(), and swap().
G4double G4INCL::NuclearDensity::theMaximumRadius private
Definition at line 121 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 121 of file G4INCLNuclearDensity.hh
Referenced by getMaximumRadius(), and swap().
G4double G4INCL::NuclearDensity::theProtonNuclearRadius private
Represents INCL4.5's R0 variable.
Definition at line 123 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 123 of file G4INCLNuclearDensity.hh
Referenced by getProtonNuclearRadius(), initializeTransmissionRadii(), setProtonNuclearRadius(), and swap().
G4int G4INCL::NuclearDensity::theS private
Definition at line 120 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 120 of file G4INCLNuclearDensity.hh
Referenced by getS(), NuclearDensity(), and swap().
G4int G4INCL::NuclearDensity::theZ private
Definition at line 120 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 120 of file G4INCLNuclearDensity.hh
Referenced by getZ(), NuclearDensity(), and swap().
G4double G4INCL::NuclearDensity::transmissionRadius[UnknownParticle] private
Definition at line 126 of file G4INCLNuclearDensity.hh.
View newest version in sPHENIX GitHub at line 126 of file G4INCLNuclearDensity.hh
Referenced by getTransmissionRadius(), initializeTransmissionRadii(), NuclearDensity(), and swap().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNuclearDensity.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNuclearDensity.cc