ECCE @ EIC Software: G4UnstableFragmentBreakUp Class Reference
G4UnstableFragmentBreakUp Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4UnstableFragmentBreakUp.hh>
Public Member Functions
G4UnstableFragmentBreakUp ()
virtual ~G4UnstableFragmentBreakUp ()
virtual G4bool BreakUpChain (G4FragmentVector *, G4Fragment *) final
virtual G4double GetEmissionProbability (G4Fragment *fragment) final
void SetVerbose (G4int val)
Public Member Functions inherited from G4VEvaporationChannel
G4VEvaporationChannel (const G4String &aName="")
virtual ~G4VEvaporationChannel ()
virtual void Initialise ()
virtual G4double GetLifeTime (G4Fragment *theNucleus)
virtual G4Fragment * EmittedFragment (G4Fragment *theNucleus)
G4FragmentVector * BreakUpFragment (G4Fragment *theNucleus)
virtual void Dump () const
virtual void SetICM (G4bool)
virtual void RDMForced (G4bool)
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
Private Member Functions
G4UnstableFragmentBreakUp (const G4UnstableFragmentBreakUp &right)
const G4UnstableFragmentBreakUp & operator= (const G4UnstableFragmentBreakUp &right)
G4bool operator== (const G4UnstableFragmentBreakUp &right) const
G4bool operator!= (const G4UnstableFragmentBreakUp &right) const
Private Attributes
G4double masses [6]
G4NuclearLevelData * fLevelData
G4int fVerbose
Static Private Attributes
static const G4int Zfr [6] = {0, 1, 1, 1, 2, 2}
static const G4int Afr [6] = {1, 1, 2, 3, 3, 4}
Additional Inherited Members
Protected Attributes inherited from G4VEvaporationChannel
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 56 of file G4UnstableFragmentBreakUp.hh.
View newest version in sPHENIX GitHub at line 56 of file G4UnstableFragmentBreakUp.hh
Constructor & Destructor Documentation
G4UnstableFragmentBreakUp::G4UnstableFragmentBreakUp () explicit
Definition at line 58 of file G4UnstableFragmentBreakUp.cc.
View newest version in sPHENIX GitHub at line 58 of file G4UnstableFragmentBreakUp.cc
References Afr, fLevelData, G4NuclearLevelData::GetInstance(), G4NucleiProperties::GetNuclearMass(), masses, and Zfr.
G4UnstableFragmentBreakUp::~G4UnstableFragmentBreakUp () virtual
Definition at line 66 of file G4UnstableFragmentBreakUp.cc.
View newest version in sPHENIX GitHub at line 66 of file G4UnstableFragmentBreakUp.cc
G4UnstableFragmentBreakUp::G4UnstableFragmentBreakUp (const G4UnstableFragmentBreakUp & right) private
Member Function Documentation
G4bool G4UnstableFragmentBreakUp::BreakUpChain (G4FragmentVector * results, G4Fragment * nucleus) final virtual
Reimplemented from G4VEvaporationChannel.
Definition at line 69 of file G4UnstableFragmentBreakUp.cc.
View newest version in sPHENIX GitHub at line 69 of file G4UnstableFragmentBreakUp.cc
References A(), Afr, CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), dir, e, CLHEP::HepLorentzVector::e(), e2, CLHEP::eV, fLevelData, fVerbose, G4cout, G4endl, G4RandomDirection(), G4UniformRand, G4Fragment::GetA_asInt(), G4Fragment::GetCreationTime(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelManager(), G4Fragment::GetMomentum(), G4NucleiProperties::GetNuclearMass(), G4Fragment::GetZ_asInt(), incremental_prev_tag::idx, CLHEP::HepLorentzVector::mag(), mass, masses, max, CLHEP::MeV, mom, CLHEP::HepLorentzVector::set(), G4Fragment::SetCreationTime(), G4Fragment::SetMomentum(), G4Fragment::SetZandA_asInt(), Acts::VectorHelpers::time(), CLHEP::Hep3Vector::unit(), v, CLHEP::HepLorentzVector::vect(), Z, and Zfr.
Referenced by G4Evaporation::BreakFragment().
G4double G4UnstableFragmentBreakUp::GetEmissionProbability (G4Fragment * fragment) final virtual
Implements G4VEvaporationChannel.
Definition at line 184 of file G4UnstableFragmentBreakUp.cc.
View newest version in sPHENIX GitHub at line 184 of file G4UnstableFragmentBreakUp.cc
G4bool G4UnstableFragmentBreakUp::operator!= (const G4UnstableFragmentBreakUp & right) const private
const G4UnstableFragmentBreakUp& G4UnstableFragmentBreakUp::operator= (const G4UnstableFragmentBreakUp & right) private
G4bool G4UnstableFragmentBreakUp::operator== (const G4UnstableFragmentBreakUp & right) const private
void G4UnstableFragmentBreakUp::SetVerbose (G4int val) inline
Definition at line 69 of file G4UnstableFragmentBreakUp.hh.
View newest version in sPHENIX GitHub at line 69 of file G4UnstableFragmentBreakUp.hh
References fVerbose.
Referenced by G4Evaporation::InitialiseChannels().
Member Data Documentation
const G4int G4UnstableFragmentBreakUp::Afr = {1, 1, 2, 3, 3, 4} static private
Definition at line 80 of file G4UnstableFragmentBreakUp.hh.
View newest version in sPHENIX GitHub at line 80 of file G4UnstableFragmentBreakUp.hh
Referenced by BreakUpChain(), and G4UnstableFragmentBreakUp().
G4NuclearLevelData* G4UnstableFragmentBreakUp::fLevelData private
Definition at line 83 of file G4UnstableFragmentBreakUp.hh.
View newest version in sPHENIX GitHub at line 83 of file G4UnstableFragmentBreakUp.hh
Referenced by BreakUpChain(), and G4UnstableFragmentBreakUp().
G4int G4UnstableFragmentBreakUp::fVerbose private
Definition at line 84 of file G4UnstableFragmentBreakUp.hh.
View newest version in sPHENIX GitHub at line 84 of file G4UnstableFragmentBreakUp.hh
Referenced by BreakUpChain(), and SetVerbose().
G4double G4UnstableFragmentBreakUp::masses[6] private
Definition at line 81 of file G4UnstableFragmentBreakUp.hh.
View newest version in sPHENIX GitHub at line 81 of file G4UnstableFragmentBreakUp.hh
Referenced by BreakUpChain(), and G4UnstableFragmentBreakUp().
const G4int G4UnstableFragmentBreakUp::Zfr = {0, 1, 1, 1, 2, 2} static private
Definition at line 79 of file G4UnstableFragmentBreakUp.hh.
View newest version in sPHENIX GitHub at line 79 of file G4UnstableFragmentBreakUp.hh
Referenced by BreakUpChain(), and G4UnstableFragmentBreakUp().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/include/G4UnstableFragmentBreakUp.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/evaporation/src/G4UnstableFragmentBreakUp.cc