ECCE @ EIC Software: G4PreCompoundModel Class Reference
G4PreCompoundModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundModel.hh>
Public Member Functions
G4PreCompoundModel (G4ExcitationHandler *ptr=nullptr)
virtual ~G4PreCompoundModel ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &thePrimary, G4Nucleus &theNucleus) final
virtual G4ReactionProductVector * DeExcite (G4Fragment &aFragment) final
virtual void BuildPhysicsTable (const G4ParticleDefinition &) final
virtual void InitialiseModel () final
virtual void ModelDescription (std::ostream &outFile) const final
virtual void DeExciteModelDescription (std::ostream &outFile) const final
void UseHETCEmission ()
void UseDefaultEmission ()
void UseGNASHTransition ()
void UseDefaultTransition ()
void SetOPTxs (G4int opt)
void UseSICB ()
void UseNGB ()
void UseSCO ()
void UseCEMtr ()
Public Member Functions inherited from G4VPreCompoundModel
G4VPreCompoundModel (G4ExcitationHandler *ptr=nullptr, const G4String &modelName="PrecompoundModel")
virtual ~G4VPreCompoundModel ()
void SetExcitationHandler (G4ExcitationHandler *ptr)
G4ExcitationHandler * GetExcitationHandler () const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
Private Member Functions
void PerformEquilibriumEmission (const G4Fragment &aFragment, G4ReactionProductVector *theResult) const
void PrintWarning (const G4String &mname)
G4PreCompoundModel (const G4PreCompoundModel &)=delete
const G4PreCompoundModel & operator= (const G4PreCompoundModel &right)=delete
G4bool operator== (const G4PreCompoundModel &right) const =delete
G4bool operator!= (const G4PreCompoundModel &right) const =delete
Private Attributes
G4PreCompoundEmission * theEmission
G4VPreCompoundTransitions * theTransition
G4NuclearLevelData * fNuclData
const G4ParticleDefinition * proton
const G4ParticleDefinition * neutron
G4double fLowLimitExc
G4double fHighLimitExc
G4bool useSCO
G4bool isInitialised
G4bool isActive
G4int minZ
G4int minA
G4HadFinalState theResult
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 62 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 62 of file G4PreCompoundModel.hh
Constructor & Destructor Documentation
G4PreCompoundModel::G4PreCompoundModel (G4ExcitationHandler * ptr = nullptr) explicit
Definition at line 69 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4PreCompoundModel.cc
References DBL_MAX, fHighLimitExc, fLowLimitExc, fNuclData, G4NuclearLevelData::GetInstance(), G4Neutron::Neutron(), neutron, G4Proton::Proton(), proton, and G4VPreCompoundModel::SetExcitationHandler().
G4PreCompoundModel::~G4PreCompoundModel () virtual
Definition at line 85 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 85 of file G4PreCompoundModel.cc
References G4VPreCompoundModel::GetExcitationHandler(), theEmission, and theTransition.
G4PreCompoundModel::G4PreCompoundModel (const G4PreCompoundModel &) private delete
Member Function Documentation
G4HadFinalState * G4PreCompoundModel::ApplyYourself (const G4HadProjectile & thePrimary, G4Nucleus & theNucleus) final virtual
Implements G4HadronicInteraction.
Definition at line 136 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 136 of file G4PreCompoundModel.cc
References A(), G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), DeExcite(), FatalException, G4Exception(), G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4HadProjectile::GetGlobalTime(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetParticleName(), G4Nucleus::GetZ_asInt(), mass, neutron, proton, G4Fragment::SetCreationTime(), G4Fragment::SetNumberOfExcitedParticle(), G4Fragment::SetNumberOfHoles(), G4HadFinalState::SetStatusChange(), stopAndKill, theResult, Acts::VectorHelpers::time(), and Z.
void G4PreCompoundModel::BuildPhysicsTable (const G4ParticleDefinition &) final virtual
Reimplemented from G4HadronicInteraction.
Definition at line 94 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 94 of file G4PreCompoundModel.cc
References InitialiseModel().
G4ReactionProductVector * G4PreCompoundModel::DeExcite (G4Fragment & aFragment) final virtual
Implements G4VPreCompoundModel.
Definition at line 201 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 201 of file G4PreCompoundModel.cc
References A(), G4VPreCompoundTransitions::CalculateProbability(), fHighLimitExc, fNuclData, G4Exception(), G4Exp(), G4lrint(), G4UniformRand, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetNumberOfExcitons(), G4PreCompoundEmission::GetTotalProbability(), G4VPreCompoundTransitions::GetTransitionProb1(), G4VPreCompoundTransitions::GetTransitionProb2(), G4VPreCompoundTransitions::GetTransitionProb3(), G4Fragment::GetZ_asInt(), InitialiseModel(), isActive, isInitialised, JustWarning, minA, minZ, P1, P2, G4PreCompoundEmission::PerformEmission(), PerformEquilibriumEmission(), G4VPreCompoundTransitions::PerformTransition(), CLHEP::pi2, theEmission, theTransition, useSCO, x, and Z.
Referenced by G4LowEGammaNuclearModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), ApplyYourself(), and G4NeutrinoNucleusModel::RecoilDeexcitation().
void G4PreCompoundModel::DeExciteModelDescription (std::ostream & outFile) const final virtual
Implements G4VPreCompoundModel.
Definition at line 409 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 409 of file G4PreCompoundModel.cc
void G4PreCompoundModel::InitialiseModel () final virtual
Reimplemented from G4HadronicInteraction.
Definition at line 101 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 101 of file G4PreCompoundModel.cc
References fHighLimitExc, fLowLimitExc, fNuclData, G4VPreCompoundModel::GetExcitationHandler(), G4DeexPrecoParameters::GetMinAForPreco(), G4DeexPrecoParameters::GetMinZForPreco(), G4NuclearLevelData::GetParameters(), G4DeexPrecoParameters::GetPrecoHighEnergy(), G4DeexPrecoParameters::GetPrecoLowEnergy(), G4DeexPrecoParameters::GetPrecoModelType(), G4ExcitationHandler::Initialise(), isActive, isInitialised, minA, minZ, G4DeexPrecoParameters::NeverGoBack(), G4DeexPrecoParameters::PrecoDummy(), G4PreCompoundEmission::SetHETCModel(), G4PreCompoundEmission::SetOPTxs(), theEmission, theTransition, G4DeexPrecoParameters::UseCEM(), G4VPreCompoundTransitions::UseCEMtr(), G4DeexPrecoParameters::UseGNASH(), G4DeexPrecoParameters::UseHETC(), G4VPreCompoundTransitions::UseNGB(), useSCO, and G4DeexPrecoParameters::UseSoftCutoff().
Referenced by BuildPhysicsTable(), and DeExcite().
void G4PreCompoundModel::ModelDescription (std::ostream & outFile) const final virtual
Reimplemented from G4HadronicInteraction.
Definition at line 385 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 385 of file G4PreCompoundModel.cc
G4bool G4PreCompoundModel::operator!= (const G4PreCompoundModel & right) const private delete
const G4PreCompoundModel& G4PreCompoundModel::operator= (const G4PreCompoundModel & right) private delete
G4bool G4PreCompoundModel::operator== (const G4PreCompoundModel & right) const private delete
void G4PreCompoundModel::PerformEquilibriumEmission (const G4Fragment & aFragment, G4ReactionProductVector * theResult) const inline private
Definition at line 138 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 138 of file G4PreCompoundModel.hh
References G4ExcitationHandler::BreakItUp(), and G4VPreCompoundModel::GetExcitationHandler().
Referenced by DeExcite().
void G4PreCompoundModel::PrintWarning (const G4String & mname) private
Definition at line 371 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 371 of file G4PreCompoundModel.cc
References G4Exception(), and JustWarning.
Referenced by SetOPTxs(), UseCEMtr(), UseDefaultEmission(), UseDefaultTransition(), UseGNASHTransition(), UseHETCEmission(), UseNGB(), UseSCO(), and UseSICB().
void G4PreCompoundModel::SetOPTxs (G4int opt)
Definition at line 346 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 346 of file G4PreCompoundModel.cc
References PrintWarning().
void G4PreCompoundModel::UseCEMtr ()
Definition at line 366 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 366 of file G4PreCompoundModel.cc
References PrintWarning().
void G4PreCompoundModel::UseDefaultEmission ()
Definition at line 331 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 331 of file G4PreCompoundModel.cc
References PrintWarning().
void G4PreCompoundModel::UseDefaultTransition ()
Definition at line 341 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 341 of file G4PreCompoundModel.cc
References PrintWarning().
void G4PreCompoundModel::UseGNASHTransition ()
Definition at line 336 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 336 of file G4PreCompoundModel.cc
References PrintWarning().
void G4PreCompoundModel::UseHETCEmission ()
Definition at line 326 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 326 of file G4PreCompoundModel.cc
References PrintWarning().
void G4PreCompoundModel::UseNGB ()
Definition at line 356 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 356 of file G4PreCompoundModel.cc
References PrintWarning().
void G4PreCompoundModel::UseSCO ()
Definition at line 361 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 361 of file G4PreCompoundModel.cc
References PrintWarning().
void G4PreCompoundModel::UseSICB ()
Definition at line 351 of file G4PreCompoundModel.cc.
View newest version in sPHENIX GitHub at line 351 of file G4PreCompoundModel.cc
References PrintWarning().
Member Data Documentation
G4double G4PreCompoundModel::fHighLimitExc private
Definition at line 123 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 123 of file G4PreCompoundModel.hh
Referenced by DeExcite(), G4PreCompoundModel(), and InitialiseModel().
G4double G4PreCompoundModel::fLowLimitExc private
Definition at line 122 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 122 of file G4PreCompoundModel.hh
Referenced by G4PreCompoundModel(), and InitialiseModel().
G4NuclearLevelData* G4PreCompoundModel::fNuclData private
Definition at line 117 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PreCompoundModel.hh
Referenced by DeExcite(), G4PreCompoundModel(), and InitialiseModel().
G4bool G4PreCompoundModel::isActive private
Definition at line 128 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4PreCompoundModel.hh
Referenced by DeExcite(), and InitialiseModel().
G4bool G4PreCompoundModel::isInitialised private
Definition at line 127 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 127 of file G4PreCompoundModel.hh
Referenced by DeExcite(), and InitialiseModel().
G4int G4PreCompoundModel::minA private
Definition at line 131 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 131 of file G4PreCompoundModel.hh
Referenced by DeExcite(), and InitialiseModel().
G4int G4PreCompoundModel::minZ private
Definition at line 130 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PreCompoundModel.hh
Referenced by DeExcite(), and InitialiseModel().
const G4ParticleDefinition* G4PreCompoundModel::neutron private
Definition at line 120 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4PreCompoundModel.hh
Referenced by ApplyYourself(), and G4PreCompoundModel().
const G4ParticleDefinition* G4PreCompoundModel::proton private
Definition at line 119 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4PreCompoundModel.hh
Referenced by ApplyYourself(), and G4PreCompoundModel().
G4PreCompoundEmission* G4PreCompoundModel::theEmission private
Definition at line 115 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4PreCompoundModel.hh
Referenced by DeExcite(), InitialiseModel(), and ~G4PreCompoundModel().
G4HadFinalState G4PreCompoundModel::theResult private
Definition at line 133 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 133 of file G4PreCompoundModel.hh
Referenced by ApplyYourself().
G4VPreCompoundTransitions* G4PreCompoundModel::theTransition private
Definition at line 116 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4PreCompoundModel.hh
Referenced by DeExcite(), InitialiseModel(), and ~G4PreCompoundModel().
G4bool G4PreCompoundModel::useSCO private
Definition at line 126 of file G4PreCompoundModel.hh.
View newest version in sPHENIX GitHub at line 126 of file G4PreCompoundModel.hh
Referenced by DeExcite(), and InitialiseModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4PreCompoundModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4PreCompoundModel.cc