ECCE @ EIC Software: GIDI_settings_processedFlux Class Reference
GIDI_settings_processedFlux Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh>
Public Member Functions
GIDI_settings_processedFlux (GIDI_settings_flux const &flux, GIDI::ptwXPoints *groupX)
GIDI_settings_processedFlux (GIDI_settings_processedFlux const &flux)
GIDI_settings_processedFlux & operator= (const GIDI_settings_processedFlux &flux)
~GIDI_settings_processedFlux ()
double getTemperature () const
GIDI::ptwXPoints * groupFunction (GIDI::statusMessageReporting *smr, GIDI::ptwXPoints *groupX, GIDI::ptwXYPoints *ptwXY1, int order) const
Private Attributes
GIDI_settings_flux mFlux
std::vector< GIDI::ptwXYPoints * > mFluxXY
std::vector< GIDI::ptwXPoints * > mGroupedFlux
Detailed Description
Definition at line 171 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 171 of file GIDI_settings.hh
Constructor & Destructor Documentation
GIDI_settings_processedFlux::GIDI_settings_processedFlux (GIDI_settings_flux const & flux, GIDI::ptwXPoints * groupX)
GIDI_settings_processedFlux::GIDI_settings_processedFlux (GIDI_settings_processedFlux const & flux)
Definition at line 156 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 156 of file GIDI_settings_particle.cc
References check_license::err(), int(), mFlux, mFluxXY, mGroupedFlux, ptwX_clone(), ptwX_free(), ptwXY_clone(), ptwXY_free(), and GIDI_settings_flux::size().
GIDI_settings_processedFlux::~GIDI_settings_processedFlux ()
Definition at line 205 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 205 of file GIDI_settings_particle.cc
References mFluxXY, mGroupedFlux, ptwX_free(), and ptwXY_free().
Member Function Documentation
double GIDI_settings_processedFlux::getTemperature () const inline
Definition at line 184 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 184 of file GIDI_settings.hh
References GIDI_settings_flux::getTemperature(), and mFlux.
ptwXPoints * GIDI_settings_processedFlux::groupFunction (GIDI::statusMessageReporting * smr, GIDI::ptwXPoints * groupX, GIDI::ptwXYPoints * ptwXY1, int order) const
Definition at line 213 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 213 of file GIDI_settings_particle.cc
References mFluxXY, mGroupedFlux, ptwXY_free(), ptwXY_getXMax(), ptwXY_getXMin(), ptwXY_group_normType_norm, ptwXY_groupTwoFunctions(), and ptwXY_xSlice().
Referenced by GIDI_settings_particle::groupFunction().
GIDI_settings_processedFlux & GIDI_settings_processedFlux::operator= (const GIDI_settings_processedFlux & flux)
Definition at line 178 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 178 of file GIDI_settings_particle.cc
References check_license::err(), int(), mFlux, mFluxXY, mGroupedFlux, ptwX_clone(), ptwX_free(), ptwXY_clone(), ptwXY_free(), and GIDI_settings_flux::size().
Member Data Documentation
GIDI_settings_flux GIDI_settings_processedFlux::mFlux private
Definition at line 174 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 174 of file GIDI_settings.hh
Referenced by getTemperature(), GIDI_settings_processedFlux(), and operator=().
std::vector<GIDI::ptwXYPoints *> GIDI_settings_processedFlux::mFluxXY private
Definition at line 175 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 175 of file GIDI_settings.hh
Referenced by GIDI_settings_processedFlux(), groupFunction(), operator=(), and ~GIDI_settings_processedFlux().
std::vector<GIDI::ptwXPoints *> GIDI_settings_processedFlux::mGroupedFlux private
Definition at line 176 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 176 of file GIDI_settings.hh
Referenced by GIDI_settings_processedFlux(), groupFunction(), operator=(), and ~GIDI_settings_processedFlux().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/GIDI_settings_particle.cc