ECCE @ EIC Software: G4EmParticleList Class Reference
G4EmParticleList Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4EmParticleList.hh>
Public Member Functions
G4EmParticleList ()
~G4EmParticleList ()
const std::vector< G4String > & PartNames () const
Private Attributes
std::vector< G4String > pNames
Detailed Description
Definition at line 50 of file G4EmParticleList.hh.
View newest version in sPHENIX GitHub at line 50 of file G4EmParticleList.hh
Constructor & Destructor Documentation
G4EmParticleList::G4EmParticleList () explicit
Definition at line 40 of file G4EmParticleList.cc.
View newest version in sPHENIX GitHub at line 40 of file G4EmParticleList.cc
References pNames.
G4EmParticleList::~G4EmParticleList ()
Definition at line 58 of file G4EmParticleList.cc.
View newest version in sPHENIX GitHub at line 58 of file G4EmParticleList.cc
Member Function Documentation
const std::vector< G4String > & G4EmParticleList::PartNames () const
Definition at line 61 of file G4EmParticleList.cc.
View newest version in sPHENIX GitHub at line 61 of file G4EmParticleList.cc
References pNames.
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), and G4EmStandardPhysics_option2::ConstructProcess().
Member Data Documentation
std::vector<G4String> G4EmParticleList::pNames private
Definition at line 61 of file G4EmParticleList.hh.
View newest version in sPHENIX GitHub at line 61 of file G4EmParticleList.hh
Referenced by G4EmParticleList(), and PartNames().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/include/G4EmParticleList.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/electromagnetic/src/G4EmParticleList.cc