ECCE @ EIC Software: G4He3Builder Class Reference
G4He3Builder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4He3Builder.hh>
Public Member Functions
G4He3Builder ()
virtual ~G4He3Builder ()
virtual void Build () finaloverride
virtual void RegisterMe (G4PhysicsBuilderInterface *aB) finaloverride
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4He3InelasticProcess * theHe3Inelastic
std::vector< G4VHe3Builder * > theModelCollections
G4bool wasActivated
Detailed Description
Definition at line 47 of file G4He3Builder.hh.
View newest version in sPHENIX GitHub at line 47 of file G4He3Builder.hh
Constructor & Destructor Documentation
G4He3Builder::G4He3Builder ()
Definition at line 57 of file G4He3Builder.cc.
View newest version in sPHENIX GitHub at line 57 of file G4He3Builder.cc
References theHe3Inelastic.
virtual G4He3Builder::~G4He3Builder () inline virtual
Definition at line 51 of file G4He3Builder.hh.
View newest version in sPHENIX GitHub at line 51 of file G4He3Builder.hh
Member Function Documentation
void G4He3Builder::Build (void) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 44 of file G4He3Builder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4He3Builder.cc
References G4ProcessManager::AddDiscreteProcess(), G4ParticleDefinition::GetProcessManager(), G4He3::He3(), theHe3Inelastic, theModelCollections, and wasActivated.
void G4He3Builder::RegisterMe (G4PhysicsBuilderInterface * aB) final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 62 of file G4He3Builder.cc.
View newest version in sPHENIX GitHub at line 62 of file G4He3Builder.cc
References G4PhysicsBuilderInterface::RegisterMe(), and theModelCollections.
Member Data Documentation
G4He3InelasticProcess* G4He3Builder::theHe3Inelastic private
Definition at line 57 of file G4He3Builder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4He3Builder.hh
Referenced by Build(), and G4He3Builder().
std::vector<G4VHe3Builder *> G4He3Builder::theModelCollections private
Definition at line 59 of file G4He3Builder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4He3Builder.hh
Referenced by Build(), and RegisterMe().
G4bool G4He3Builder::wasActivated private
Definition at line 61 of file G4He3Builder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4He3Builder.hh
Referenced by Build().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4He3Builder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4He3Builder.cc