ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/MCGIDI_misc.h File Reference
MCGIDI_misc.h File Reference
#include <statusMessageReporting.h>
#include <xDataTOM_importXML_private.h>
#include "MCGIDI_private.h"
Macros
#define MCGIDI_misc_pointerToTOMAttributeIfAllOk2(smr, required, attributes, name) MCGIDI_misc_pointerToTOMAttributeIfAllOk(smr, NULL, required, attributes, name, __FILE__, __LINE__)
#define MCGIDI_misc_pointerToTOMAttributeIfAllOk3(smr, path, required, attributes, name) MCGIDI_misc_pointerToTOMAttributeIfAllOk(smr, path, required, attributes, name, __FILE__, __LINE__)
#define MCGIDI_misc_pointerToAttributeIfAllOk2(smr, element, required, attributes, name) MCGIDI_misc_pointerToAttributeIfAllOk(smr, element, NULL, required, attributes, name, __FILE__, __LINE__)
#define MCGIDI_misc_pointerToAttributeIfAllOk3(smr, path, required, attributes, name) MCGIDI_misc_pointerToAttributeIfAllOk(smr, NULL, path, required, attributes, name, __FILE__, __LINE__)
Functions
char const * MCGIDI_misc_pointerToTOMAttributeIfAllOk (statusMessageReporting *smr, char const *path, int required, xDataTOM_attributionList *attributes, char const *name, char const *file, int line)
char const * MCGIDI_misc_pointerToAttributeIfAllOk (statusMessageReporting *smr, xDataXML_element *element, char const *path, int required, xDataTOM_attributionList *attributes, char const *name, char const *file, int line)
int MCGIDI_misc_setMessageError_Element (statusMessageReporting *smr, void *userInterface, xDataXML_element *element, char const *file, int line, int code, char const *fmt,...)
char * MCGIDI_misc_getAbsPath (statusMessageReporting *smr, char const *fileName)
int MCGIDI_misc_copyXMLAttributesToTOM (statusMessageReporting *smr, xDataTOM_attributionList *TOM, xDataXML_attributionList *XML)
enum xDataTOM_frame MCGIDI_misc_getProductFrame (statusMessageReporting *smr, xDataTOM_element *frameElement)
double MCGIDI_misc_getUnitConversionFactor (statusMessageReporting *smr, char const *fromUnit, char const *toUnit)
ptwXYPoints * MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf (statusMessageReporting *smr, xDataTOM_XYs *XYs, ptwXY_interpolation interpolation, char const *units[2])
ptwXYPoints * MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf (statusMessageReporting *smr, xDataTOM_element *linear, char const *toUnits[2])
Macro Definition Documentation
#define MCGIDI_misc_pointerToAttributeIfAllOk2 (smr, element, required, attributes, name) MCGIDI_misc_pointerToAttributeIfAllOk(smr, element, NULL, required, attributes, name, __FILE__, __LINE__)
Definition at line 31 of file MCGIDI_misc.h.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_misc.h
#define MCGIDI_misc_pointerToAttributeIfAllOk3 (smr, path, required, attributes, name) MCGIDI_misc_pointerToAttributeIfAllOk(smr, NULL, path, required, attributes, name, __FILE__, __LINE__)
Definition at line 33 of file MCGIDI_misc.h.
View newest version in sPHENIX GitHub at line 33 of file MCGIDI_misc.h
#define MCGIDI_misc_pointerToTOMAttributeIfAllOk2 (smr, required, attributes, name) MCGIDI_misc_pointerToTOMAttributeIfAllOk(smr, NULL, required, attributes, name, __FILE__, __LINE__)
Definition at line 26 of file MCGIDI_misc.h.
View newest version in sPHENIX GitHub at line 26 of file MCGIDI_misc.h
#define MCGIDI_misc_pointerToTOMAttributeIfAllOk3 (smr, path, required, attributes, name) MCGIDI_misc_pointerToTOMAttributeIfAllOk(smr, path, required, attributes, name, __FILE__, __LINE__)
Definition at line 28 of file MCGIDI_misc.h.
View newest version in sPHENIX GitHub at line 28 of file MCGIDI_misc.h
Referenced by MCGIDI_target_heated_read().
Function Documentation
int MCGIDI_misc_copyXMLAttributesToTOM (statusMessageReporting * smr, xDataTOM_attributionList * TOM, xDataXML_attributionList * XML)
Definition at line 296 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 296 of file MCGIDI_misc.cc
References check_license::err(), xDataXML_attribute_s::name, xDataXML_attribute_s::value, xDataTOMAL_addAttribute(), xDataTOMAL_initial(), xDataTOMAL_release(), and xDataXML_attributeByIndex().
ptwXYPoints* MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf (statusMessageReporting * smr, xDataTOM_element * linear, char const * toUnits[2])
Definition at line 424 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 424 of file MCGIDI_misc.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_axes_s::axis, BTOF::length, MCGIDI_fromTOM_interpolation(), MCGIDI_misc_Data2ptwXYPointsInUnitsOf(), xDataTOM_axes_s::numberOfAxes, smr_setReportError2, smr_unknownID, xDataTOM_axis_s::unit, xDataTOM_element_s::xDataInfo, and xDataTOM_XYs_getDataFromXDataInfo().
Referenced by MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), and MCGIDI_reaction_parseFromTOM().
ptwXYPoints* MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf (statusMessageReporting * smr, xDataTOM_XYs * XYs, ptwXY_interpolation interpolation, char const * units[2])
Definition at line 405 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 405 of file MCGIDI_misc.cc
References BTOF::length, MCGIDI_misc_Data2ptwXYPointsInUnitsOf(), smr_isOk(), xDataTOM_XYs_s::subAxes, xDataTOM_subAxes_getUnit(), and xDataTOM_XYs_getData().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfsOfXGivenW(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
char* MCGIDI_misc_getAbsPath (statusMessageReporting * smr, char const * fileName)
Definition at line 250 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 250 of file MCGIDI_misc.cc
References g4zmq::cwd(), int(), n, smr_malloc2, smr_setReportError2p, and smr_unknownID.
Referenced by MCGIDI_target_read().
enum xDataTOM_frame MCGIDI_misc_getProductFrame (statusMessageReporting * smr, xDataTOM_element * frameElement)
Definition at line 315 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 315 of file MCGIDI_misc.cc
References MCGIDI_token_productFrame, smr_setReportError2, smr_unknownID, xDataTOM_axis_stringToFrame(), xDataTOM_frame_invalid, and xDataTOM_getAttributesValueInElement().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_KalbachMann_parseFromTOM(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
double MCGIDI_misc_getUnitConversionFactor (statusMessageReporting * smr, char const * fromUnit, char const * toUnit)
Definition at line 381 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 381 of file MCGIDI_misc.cc
References e, smr_setReportError2, and smr_unknownID.
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_misc_Data2ptwXYPointsInUnitsOf(), MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_product_parsePolynomialMultiplicity(), and MCGIDI_target_heated_read().
char const* MCGIDI_misc_pointerToAttributeIfAllOk (statusMessageReporting * smr, xDataXML_element * element, char const * path, int required, xDataTOM_attributionList * attributes, char const * name, char const * file, int line)
Definition at line 184 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 184 of file MCGIDI_misc.cc
References MCGIDI_misc_setMessageError_Element(), smr_isOk(), smr_setReportError(), smr_unknownID, and xDataTOMAL_getAttributesValue().
char const* MCGIDI_misc_pointerToTOMAttributeIfAllOk (statusMessageReporting * smr, char const * path, int required, xDataTOM_attributionList * attributes, char const * name, char const * file, int line)
Definition at line 168 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 168 of file MCGIDI_misc.cc
References smr_isOk(), smr_setReportError(), smr_unknownID, and xDataTOMAL_getAttributesValue().
int MCGIDI_misc_setMessageError_Element (statusMessageReporting * smr, void * userInterface, xDataXML_element * element, char const * file, int line, int code, char const * fmt, ...)
Definition at line 204 of file MCGIDI_misc.cc.
View newest version in sPHENIX GitHub at line 204 of file MCGIDI_misc.cc
References xDataXML_element_s::name, smr_freeMemory(), smr_setReportError(), smr_unknownID, smr_vallocateFormatMessage(), and smr_vsetReportError().
Referenced by MCGIDI_misc_pointerToAttributeIfAllOk(), and MCGIDI_target_read().