ECCE @ EIC Software: G4QGSMFragmentation Class Reference
G4QGSMFragmentation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4QGSMFragmentation.hh>
Public Member Functions
G4QGSMFragmentation ()
~G4QGSMFragmentation ()
virtual G4KineticTrackVector * FragmentString (const G4ExcitedString &theString)
Public Member Functions inherited from G4VLongitudinalStringDecay
G4VLongitudinalStringDecay ()
virtual ~G4VLongitudinalStringDecay ()
void AddNewParticles ()
void EraseNewParticles ()
void SetMinMasses ()
void SetMinimalStringMass (const G4FragmentingString *const string)
void SetMinimalStringMass2 (const G4double aValue)
G4int SampleQuarkFlavor (void)
G4ThreeVector SampleQuarkPt (G4double ptMax=-1.)
void SetSigmaTransverseMomentum (G4double aQT)
void SetStrangenessSuppression (G4double aValue)
void SetDiquarkSuppression (G4double aValue)
void SetDiquarkBreakProbability (G4double aValue)
void SetVectorMesonProbability (G4double aValue)
void SetSpinThreeHalfBarionProbability (G4double aValue)
void SetScalarMesonMixings (std::vector< G4double > aVector)
void SetVectorMesonMixings (std::vector< G4double > aVector)
void SetStringTensionParameter (G4double aValue)
void SetProbCCbar (G4double aValue)
void SetProbEta_c (G4double aValue)
void SetProbBBbar (G4double aValue)
void SetProbEta_b (G4double aValue)
Private Member Functions
G4QGSMFragmentation (const G4QGSMFragmentation &right)
const G4QGSMFragmentation & operator= (const G4QGSMFragmentation &right)
G4bool operator== (const G4QGSMFragmentation &right) const
G4bool operator!= (const G4QGSMFragmentation &right) const
virtual G4bool StopFragmenting (const G4FragmentingString *const string)
virtual G4bool IsItFragmentable (const G4FragmentingString *const string)
virtual G4bool SplitLast (G4FragmentingString *string, G4KineticTrackVector *LeftVector, G4KineticTrackVector *RightVector)
virtual void Sample4Momentum (G4LorentzVector *Mom, G4double Mass, G4LorentzVector *AntiMom, G4double AntiMass, G4double InitialMass)
virtual G4KineticTrack * Splitup (G4FragmentingString *string, G4FragmentingString *&newString)
virtual G4ParticleDefinition * DiQuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)
virtual G4LorentzVector * SplitEandP (G4ParticleDefinition *pHadron, G4FragmentingString *string, G4FragmentingString *newString)
virtual G4double GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition *pHadron, G4double Px, G4double Py)
void SetFFq2q ()
void SetFFq2qq ()
void SetFFqq2qq ()
void SetFFqq2q ()
Private Attributes
G4double arho
G4double aphi
G4double aJPs
G4double aUps
G4double an
G4double ala
G4double alaC
G4double alaB
G4double aXi
G4double aXiC
G4double aXiB
G4double aXiCC
G4double aXiCB
G4double aXiBB
G4double aksi
G4double alft
G4double FFq2q [5][5][2]
G4double FFq2qq [5][15][2]
G4double FFqq2q [15][5][2]
G4double FFqq2qq [15][5][2]
G4int IndexDiQ [5][5]
Additional Inherited Members
Public Attributes inherited from G4VLongitudinalStringDecay
G4double Mass_of_light_quark
G4double Mass_of_s_quark
G4double Mass_of_c_quark
G4double Mass_of_b_quark
G4double Mass_of_string_junction
G4double minMassQQbarStr [5][5]
G4double minMassQDiQStr [5][5][5]
G4double MinimalStringMass
G4double MinimalStringMass2
G4int Qcharge [5]
G4int Meson [5][5][7]
G4double MesonWeight [5][5][7]
G4int Baryon [5][5][5][4]
G4double BaryonWeight [5][5][5][4]
G4double Prob_QQbar [5]
G4int DecayQuark
G4int NewQuark
G4ParticleDefinition * FS_LeftHadron [350]
G4ParticleDefinition * FS_RightHadron [350]
G4double FS_Weight [350]
G4int NumberOf_FS
Protected Types inherited from G4VLongitudinalStringDecay
typedef std::pair
< G4ParticleDefinition
*, G4ParticleDefinition * > pDefPair
typedef G4ParticleDefinition
*(G4HadronBuilder::* Pcreate)(G4ParticleDefinition *, G4ParticleDefinition *)
Protected Member Functions inherited from G4VLongitudinalStringDecay
virtual void SetMassCut (G4double aValue)
G4double GetMassCut ()
G4KineticTrackVector * ProduceOneHadron (const G4ExcitedString *const theString)
G4double PossibleHadronMass (const G4FragmentingString *const string, Pcreate build=0, pDefPair *pdefs=0)
G4ParticleDefinition * FindParticle (G4int Encoding)
G4ExcitedString * CopyExcited (const G4ExcitedString &string)
virtual G4ParticleDefinition * QuarkSplitup (G4ParticleDefinition *decay, G4ParticleDefinition *&created)
pDefPair CreatePartonPair (G4int NeedParticle, G4bool AllowDiquarks=true)
void CalculateHadronTimePosition (G4double theInitialStringMass, G4KineticTrackVector *)
void ConstructParticle ()
G4ParticleDefinition * CreateHadron (G4int id1, G4int id2, G4bool theGivenSpin, G4int theSpin)
G4double GetDiquarkSuppress ()
G4double GetDiquarkBreakProb ()
G4double GetStrangeSuppress ()
G4int GetClusterLoopInterrupt ()
G4double GetProbCCbar ()
G4double GetProbEta_c ()
G4double GetProbBBbar ()
G4double GetProbEta_b ()
G4double GetStringTensionParameter ()
Protected Attributes inherited from G4VLongitudinalStringDecay
G4double MassCut
G4double SigmaQT
G4double DiquarkSuppress
G4double DiquarkBreakProb
G4double StrangeSuppress
G4int StringLoopInterrupt
G4int ClusterLoopInterrupt
G4HadronBuilder * hadronizer
G4double pspin_meson
G4double pspin_barion
std::vector< G4double > vectorMesonMix
std::vector< G4double > scalarMesonMix
G4double ProbCCbar
G4double ProbEta_c
G4double ProbBBbar
G4double ProbEta_b
G4double ProbCB
G4double MaxMass
G4bool PastInitPhase
G4double Kappa
std::vector
< G4ParticleDefinition * > NewParticles
Detailed Description
Definition at line 39 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 39 of file G4QGSMFragmentation.hh
Constructor & Destructor Documentation
G4QGSMFragmentation::G4QGSMFragmentation ()
Definition at line 49 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 49 of file G4QGSMFragmentation.cc
References aJPs, aksi, ala, alaB, alaC, alft, an, aphi, arho, aUps, aXi, aXiB, aXiBB, aXiC, aXiCB, aXiCC, GeV, IndexDiQ, G4VLongitudinalStringDecay::MassCut, G4VLongitudinalStringDecay::SetDiquarkBreakProbability(), G4VLongitudinalStringDecay::SetDiquarkSuppression(), SetFFq2q(), SetFFq2qq(), SetFFqq2q(), SetFFqq2qq(), G4VLongitudinalStringDecay::SetMinMasses(), G4VLongitudinalStringDecay::SetProbBBbar(), G4VLongitudinalStringDecay::SetProbCCbar(), and G4VLongitudinalStringDecay::SetStrangenessSuppression().
G4QGSMFragmentation::~G4QGSMFragmentation ()
Definition at line 100 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 100 of file G4QGSMFragmentation.cc
G4QGSMFragmentation::G4QGSMFragmentation (const G4QGSMFragmentation & right) private
Member Function Documentation
G4ParticleDefinition * G4QGSMFragmentation::DiQuarkSplitup (G4ParticleDefinition * decay, G4ParticleDefinition *& created) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 386 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 386 of file G4QGSMFragmentation.cc
References kdfinder::abs(), G4HadronBuilder::Build(), G4VLongitudinalStringDecay::CreatePartonPair(), G4VLongitudinalStringDecay::DecayQuark, G4VLongitudinalStringDecay::DiquarkBreakProb, G4VLongitudinalStringDecay::FindParticle(), G4UniformRand, G4ParticleDefinition::GetPDGEncoding(), G4VLongitudinalStringDecay::GetStrangeSuppress(), G4VLongitudinalStringDecay::hadronizer, max, min, G4VLongitudinalStringDecay::NewQuark, and G4VLongitudinalStringDecay::SetStrangenessSuppression().
Referenced by Splitup().
G4KineticTrackVector * G4QGSMFragmentation::FragmentString (const G4ExcitedString & theString) virtual
Implements G4VLongitudinalStringDecay.
Definition at line 105 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 105 of file G4QGSMFragmentation.cc
References C1, G4VLongitudinalStringDecay::CalculateHadronTimePosition(), G4VLongitudinalStringDecay::CopyExcited(), G4cout, G4endl, G4Parton::Get4Momentum(), G4ExcitedString::Get4Momentum(), G4KineticTrack::Get4Momentum(), G4FragmentingString::GetDecayDirection(), G4KineticTrack::GetDefinition(), G4ExcitedString::GetDirection(), G4KineticTrack::GetFormationTime(), G4ExcitedString::GetLeftParton(), G4ParticleDefinition::GetParticleName(), G4Parton::GetPDGcode(), G4ExcitedString::GetPosition(), G4KineticTrack::GetPosition(), G4ExcitedString::GetRightParton(), CLHEP::HepLorentzRotation::inverse(), IsItFragmentable(), CLHEP::HepLorentzVector::mag(), G4VLongitudinalStringDecay::PastInitPhase, G4VLongitudinalStringDecay::ProduceOneHadron(), CLHEP::HepLorentzVector::pz(), G4KineticTrack::Set4Momentum(), G4KineticTrack::SetFormationTime(), G4VLongitudinalStringDecay::SetMinimalStringMass(), G4KineticTrack::SetPosition(), SplitLast(), Splitup(), StopFragmenting(), G4VLongitudinalStringDecay::StringLoopInterrupt, and G4ExcitedString::TransformToAlignedCms().
G4double G4QGSMFragmentation::GetLightConeZ (G4double zmin, G4double zmax, G4int PartonEncoding, G4ParticleDefinition * pHadron, G4double Px, G4double Py) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 538 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 538 of file G4QGSMFragmentation.cc
References kdfinder::abs(), d1, d2, G4VLongitudinalStringDecay::DecayQuark, FFq2q, FFq2qq, FFqq2q, FFqq2qq, G4cout, G4endl, G4UniformRand, G4Pow::GetInstance(), IndexDiQ, G4VLongitudinalStringDecay::NewQuark, G4Pow::powA(), r1, r2, and z.
Referenced by SplitEandP().
G4bool G4QGSMFragmentation::IsItFragmentable (const G4FragmentingString *const string) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 263 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 263 of file G4QGSMFragmentation.cc
References G4VLongitudinalStringDecay::MassCut, G4VLongitudinalStringDecay::PossibleHadronMass(), and sqr().
Referenced by FragmentString().
G4bool G4QGSMFragmentation::operator!= (const G4QGSMFragmentation & right) const private
const G4QGSMFragmentation& G4QGSMFragmentation::operator= (const G4QGSMFragmentation & right) private
G4bool G4QGSMFragmentation::operator== (const G4QGSMFragmentation & right) const private
void G4QGSMFragmentation::Sample4Momentum (G4LorentzVector * Mom, G4double Mass, G4LorentzVector * AntiMom, G4double AntiMass, G4double InitialMass) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 705 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 705 of file G4QGSMFragmentation.cc
References G4UniformRand, phi, pi, CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), and sqr().
Referenced by SplitLast().
void G4QGSMFragmentation::SetFFq2q () private
Definition at line 728 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 728 of file G4QGSMFragmentation.cc
References aJPs, alft, aphi, arho, aUps, and FFq2q.
Referenced by G4QGSMFragmentation().
void G4QGSMFragmentation::SetFFq2qq () private
Definition at line 741 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 741 of file G4QGSMFragmentation.cc
References ala, alaB, alaC, alft, an, arho, aXi, aXiB, aXiBB, aXiC, aXiCB, aXiCC, and FFq2qq.
Referenced by G4QGSMFragmentation().
void G4QGSMFragmentation::SetFFqq2q () private
Definition at line 764 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 764 of file G4QGSMFragmentation.cc
References aJPs, alft, an, aphi, arho, aUps, and FFqq2q.
Referenced by G4QGSMFragmentation().
void G4QGSMFragmentation::SetFFqq2qq () private
Definition at line 777 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 777 of file G4QGSMFragmentation.cc
References aJPs, alft, an, aphi, arho, aUps, and FFqq2qq.
Referenced by G4QGSMFragmentation().
G4LorentzVector * G4QGSMFragmentation::SplitEandP (G4ParticleDefinition * pHadron, G4FragmentingString * string, G4FragmentingString * newString) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 444 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 444 of file G4QGSMFragmentation.cc
References G4cout, G4endl, G4FragmentingString::GetDecayDirection(), G4FragmentingString::GetDecayParton(), GetLightConeZ(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), CLHEP::Hep3Vector::mag2(), G4FragmentingString::Mass(), G4VLongitudinalStringDecay::MinimalStringMass, G4VLongitudinalStringDecay::SampleQuarkPt(), G4VLongitudinalStringDecay::SetMinimalStringMass(), CLHEP::HepLorentzVector::setPz(), CLHEP::Hep3Vector::setZ(), sqr(), G4VLongitudinalStringDecay::StringLoopInterrupt, CLHEP::HepLorentzVector::vect(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and z.
Referenced by Splitup().
G4bool G4QGSMFragmentation::SplitLast (G4FragmentingString * string, G4KineticTrackVector * LeftVector, G4KineticTrackVector * RightVector) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 603 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 603 of file G4QGSMFragmentation.cc
References CLHEP::HepLorentzVector::boost(), G4HadronBuilder::BuildLowSpin(), G4VLongitudinalStringDecay::CreatePartonPair(), G4FragmentingString::DecayIsQuark(), G4cout, G4endl, G4FragmentingString::GetLeftParton(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4FragmentingString::GetRightParton(), G4VLongitudinalStringDecay::hadronizer, CLHEP::HepLorentzVector::mag(), G4VLongitudinalStringDecay::MaxMass, Sample4Momentum(), and G4FragmentingString::StableIsQuark().
Referenced by FragmentString().
G4KineticTrack * G4QGSMFragmentation::Splitup (G4FragmentingString * string, G4FragmentingString *& newString) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 293 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 293 of file G4QGSMFragmentation.cc
References G4FragmentingString::DecayIsQuark(), DiQuarkSplitup(), G4cout, G4endl, G4Exp(), G4UniformRand, G4FragmentingString::GetDecayParton(), G4VLongitudinalStringDecay::GetDiquarkSuppress(), G4FragmentingString::GetLeftParton(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetPDGEncoding(), G4FragmentingString::GetRightParton(), G4FragmentingString::Mass(), G4VLongitudinalStringDecay::QuarkSplitup(), G4VLongitudinalStringDecay::SetDiquarkSuppression(), and SplitEandP().
Referenced by FragmentString().
G4bool G4QGSMFragmentation::StopFragmenting (const G4FragmentingString *const string) private virtual
Implements G4VLongitudinalStringDecay.
Definition at line 270 of file G4QGSMFragmentation.cc.
View newest version in sPHENIX GitHub at line 270 of file G4QGSMFragmentation.cc
References e, G4cout, G4endl, G4Exp(), G4UniformRand, G4FragmentingString::IsAFourQuarkString(), G4FragmentingString::Mass(), G4VLongitudinalStringDecay::MinimalStringMass, and G4VLongitudinalStringDecay::SetMinimalStringMass().
Referenced by FragmentString().
Member Data Documentation
G4double G4QGSMFragmentation::aJPs private
Definition at line 85 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 85 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), SetFFq2q(), SetFFqq2q(), and SetFFqq2qq().
G4double G4QGSMFragmentation::aksi private
Definition at line 99 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 99 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation().
G4double G4QGSMFragmentation::ala private
Definition at line 88 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 88 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::alaB private
Definition at line 91 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 91 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::alaC private
Definition at line 90 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 90 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::alft private
Definition at line 100 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 100 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), SetFFq2q(), SetFFq2qq(), SetFFqq2q(), and SetFFqq2qq().
G4double G4QGSMFragmentation::an private
Definition at line 87 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 87 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), SetFFq2qq(), SetFFqq2q(), and SetFFqq2qq().
G4double G4QGSMFragmentation::aphi private
Definition at line 84 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 84 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), SetFFq2q(), SetFFqq2q(), and SetFFqq2qq().
G4double G4QGSMFragmentation::arho private
Definition at line 83 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), SetFFq2q(), SetFFq2qq(), SetFFqq2q(), and SetFFqq2qq().
G4double G4QGSMFragmentation::aUps private
Definition at line 86 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 86 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), SetFFq2q(), SetFFqq2q(), and SetFFqq2qq().
G4double G4QGSMFragmentation::aXi private
Definition at line 92 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 92 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::aXiB private
Definition at line 94 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 94 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::aXiBB private
Definition at line 97 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 97 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::aXiC private
Definition at line 93 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 93 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::aXiCB private
Definition at line 96 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 96 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::aXiCC private
Definition at line 95 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 95 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and SetFFq2qq().
G4double G4QGSMFragmentation::FFq2q[5][5][2] private
Definition at line 102 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 102 of file G4QGSMFragmentation.hh
Referenced by GetLightConeZ(), and SetFFq2q().
G4double G4QGSMFragmentation::FFq2qq[5][15][2] private
Definition at line 103 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 103 of file G4QGSMFragmentation.hh
Referenced by GetLightConeZ(), and SetFFq2qq().
G4double G4QGSMFragmentation::FFqq2q[15][5][2] private
Definition at line 104 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 104 of file G4QGSMFragmentation.hh
Referenced by GetLightConeZ(), and SetFFqq2q().
G4double G4QGSMFragmentation::FFqq2qq[15][5][2] private
Definition at line 105 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 105 of file G4QGSMFragmentation.hh
Referenced by GetLightConeZ(), and SetFFqq2qq().
G4int G4QGSMFragmentation::IndexDiQ[5][5] private
Definition at line 113 of file G4QGSMFragmentation.hh.
View newest version in sPHENIX GitHub at line 113 of file G4QGSMFragmentation.hh
Referenced by G4QGSMFragmentation(), and GetLightConeZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4QGSMFragmentation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/src/G4QGSMFragmentation.cc