ECCE @ EIC Software: G4H3ToolsManager Class Reference
G4H3ToolsManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4H3ToolsManager.hh>
Public Member Functions
G4H3ToolsManager (const G4AnalysisManagerState &state)
virtual ~G4H3ToolsManager ()
G4int AddH3 (const G4String &name, tools::histo::h3d *h3d)
void AddH3Vector (const std::vector< tools::histo::h3d * > &h3Vector)
tools::histo::h3d * GetH3 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
std::vector< tools::histo::h3d * >
::iterator BeginH3 ()
std::vector< tools::histo::h3d * >
::iterator EndH3 ()
std::vector< tools::histo::h3d * >
::const_iterator BeginConstH3 () const
std::vector< tools::histo::h3d * >
::const_iterator EndConstH3 () const
const std::vector
< tools::histo::h3d * > & GetH3Vector () const
const std::vector
< G4HnInformation * > & GetHnVector () const
Public Member Functions inherited from G4VH3Manager
G4VH3Manager ()
virtual ~G4VH3Manager ()
G4VH3Manager (const G4VH3Manager &rhs)=delete
G4VH3Manager & operator= (const G4VH3Manager &rhs)=delete
Public Member Functions inherited from G4THnManager< tools::histo::h3d >
G4THnManager (const G4AnalysisManagerState &state, const G4String &hnType)
virtual ~G4THnManager ()
G4bool Reset ()
G4bool IsEmpty () const
Protected Member Functions
virtual G4int CreateH3 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinScheme="linear", const G4String &ybinScheme="linear", const G4String &zbinScheme="linear") final
virtual G4int CreateH3 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none") final
virtual G4bool SetH3 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinScheme="linear", const G4String &ybinScheme="linear", const G4String &zbinScheme="linear") final
virtual G4bool SetH3 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none") final
virtual G4bool ScaleH3 (G4int id, G4double factor) final
virtual G4bool FillH3 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0) final
virtual G4int GetH3Id (const G4String &name, G4bool warn=true) const final
virtual G4int GetH3Nxbins (G4int id) const final
virtual G4double GetH3Xmin (G4int id) const final
virtual G4double GetH3Xmax (G4int id) const final
virtual G4double GetH3XWidth (G4int id) const final
virtual G4int GetH3Nybins (G4int id) const final
virtual G4double GetH3Ymin (G4int id) const final
virtual G4double GetH3Ymax (G4int id) const final
virtual G4double GetH3YWidth (G4int id) const final
virtual G4int GetH3Nzbins (G4int id) const final
virtual G4double GetH3Zmin (G4int id) const final
virtual G4double GetH3Zmax (G4int id) const final
virtual G4double GetH3ZWidth (G4int id) const final
virtual G4bool SetH3Title (G4int id, const G4String &title) final
virtual G4bool SetH3XAxisTitle (G4int id, const G4String &title) final
virtual G4bool SetH3YAxisTitle (G4int id, const G4String &title) final
virtual G4bool SetH3ZAxisTitle (G4int id, const G4String &title) final
virtual G4String GetH3Title (G4int id) const final
virtual G4String GetH3XAxisTitle (G4int id) const final
virtual G4String GetH3YAxisTitle (G4int id) const final
virtual G4String GetH3ZAxisTitle (G4int id) const final
virtual G4bool WriteOnAscii (std::ofstream &output) final
virtual std::shared_ptr
< G4HnManager > GetHnManager () final
Protected Member Functions inherited from G4THnManager< tools::histo::h3d >
void AddTVector (const std::vector< tools::histo::h3d * > &tVector)
std::vector< tools::histo::h3d * >
::iterator BeginT ()
std::vector< tools::histo::h3d * >
::iterator EndT ()
std::vector< tools::histo::h3d * >
::const_iterator BeginConstT () const
std::vector< tools::histo::h3d * >
::const_iterator EndConstT () const
tools::histo::h3d * GetTInFunction (G4int id, G4String functionName, G4bool warn=true, G4bool onlyIfActive=true) const
G4int RegisterT (tools::histo::h3d *t, const G4String &name)
G4int GetTId (const G4String &name, G4bool warn=true) const
Private Member Functions
void AddH3Information (const G4String &name, const G4String &xunitName, const G4String &yunitName, const G4String &zunitName, const G4String &xfcnName, const G4String &yfcnName, const G4String &zfcnName, G4BinScheme xbinScheme, G4BinScheme ybinScheme, G4BinScheme zbinScheme) const
Static Private Attributes
static const G4int kDimension = 3
Additional Inherited Members
Protected Attributes inherited from G4THnManager< tools::histo::h3d >
const G4AnalysisManagerState & fState
std::vector< tools::histo::h3d * > fTVector
std::map< G4String, G4int > fNameIdMap
std::shared_ptr< G4HnManager > fHnManager
Detailed Description
Definition at line 52 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 52 of file G4H3ToolsManager.hh
Constructor & Destructor Documentation
G4H3ToolsManager::G4H3ToolsManager (const G4AnalysisManagerState & state) explicit
Definition at line 44 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 44 of file G4H3ToolsManager.cc
G4H3ToolsManager::~G4H3ToolsManager () virtual
Definition at line 50 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 50 of file G4H3ToolsManager.cc
Member Function Documentation
G4int G4H3ToolsManager::AddH3 (const G4String & name, tools::histo::h3d * h3d)
Definition at line 723 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 723 of file G4H3ToolsManager.cc
References AddH3Information(), G4THnManager< tools::histo::h3d >::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h3d >::RegisterT().
Referenced by G4CsvAnalysisReader::ReadH3Impl(), G4XmlAnalysisReader::ReadH3Impl(), G4RootAnalysisReader::ReadH3Impl(), and G4Hdf5AnalysisReader::ReadH3Impl().
void G4H3ToolsManager::AddH3Information (const G4String & name, const G4String & xunitName, const G4String & yunitName, const G4String & zunitName, const G4String & xfcnName, const G4String & yfcnName, const G4String & zfcnName, G4BinScheme xbinScheme, G4BinScheme ybinScheme, G4BinScheme zbinScheme) const private
Definition at line 275 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 275 of file G4H3ToolsManager.cc
References G4HnInformation::AddDimension(), and G4THnManager< tools::histo::h3d >::fHnManager.
Referenced by AddH3(), and CreateH3().
void G4H3ToolsManager::AddH3Vector (const std::vector< tools::histo::h3d * > & h3Vector)
Definition at line 747 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 747 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::AddTVector().
Referenced by G4XmlAnalysisManager::WriteH3(), G4CsvAnalysisManager::WriteH3(), G4Hdf5AnalysisManager::WriteH3(), and G4RootAnalysisManager::WriteH3().
std::vector< tools::histo::h3d * >::const_iterator G4H3ToolsManager::BeginConstH3 () const inline
Definition at line 206 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 206 of file G4H3ToolsManager.hh
References G4THnManager< tools::histo::h3d >::BeginConstT().
std::vector< tools::histo::h3d * >::iterator G4H3ToolsManager::BeginH3 () inline
Definition at line 199 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 199 of file G4H3ToolsManager.hh
References G4THnManager< tools::histo::h3d >::BeginT().
G4int G4H3ToolsManager::CreateH3 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinScheme = "linear", const G4String & ybinScheme = "linear", const G4String & zbinScheme = "linear") final protected virtual
Implements G4VH3Manager.
Definition at line 297 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 297 of file G4H3ToolsManager.cc
References AddH3Information(), G4THnManager< tools::histo::h3d >::fState, G4Analysis::GetBinScheme(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h3d >::RegisterT().
G4int G4H3ToolsManager::CreateH3 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const std::vector< G4double > & zedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none") final protected virtual
Implements G4VH3Manager.
Definition at line 345 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 345 of file G4H3ToolsManager.cc
References AddH3Information(), G4THnManager< tools::histo::h3d >::fState, G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4THnManager< tools::histo::h3d >::RegisterT().
std::vector< tools::histo::h3d * >::const_iterator G4H3ToolsManager::EndConstH3 () const inline
Definition at line 210 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 210 of file G4H3ToolsManager.hh
References G4THnManager< tools::histo::h3d >::EndConstT().
std::vector< tools::histo::h3d * >::iterator G4H3ToolsManager::EndH3 () inline
Definition at line 202 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 202 of file G4H3ToolsManager.hh
References G4THnManager< tools::histo::h3d >::EndT().
G4bool G4H3ToolsManager::FillH3 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight = 1.0) final protected virtual
Implements G4VH3Manager.
Definition at line 477 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 477 of file G4H3ToolsManager.cc
References G4HnDimensionInformation::fFcn, G4THnManager< tools::histo::h3d >::fHnManager, G4THnManager< tools::histo::h3d >::fState, G4HnDimensionInformation::fUnit, G4AnalysisManagerState::GetIsActivation(), G4THnManager< tools::histo::h3d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), G4Analysis::kX, G4Analysis::kY, G4Analysis::kZ, G4AnalysisVerbose::Message(), and weight.
tools::histo::h3d * G4H3ToolsManager::GetH3 (G4int id, G4bool warn = true, G4bool onlyIfActive = true) const
Definition at line 754 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 754 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::GetTInFunction().
G4int G4H3ToolsManager::GetH3Id (const G4String & name, G4bool warn = true) const final protected virtual
Implements G4VH3Manager.
Definition at line 516 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 516 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::GetTId().
G4int G4H3ToolsManager::GetH3Nxbins (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 522 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 522 of file G4H3ToolsManager.cc
References G4Analysis::GetNbins(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kX.
G4int G4H3ToolsManager::GetH3Nybins (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 560 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 560 of file G4H3ToolsManager.cc
References G4Analysis::GetNbins(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kY.
G4int G4H3ToolsManager::GetH3Nzbins (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 598 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 598 of file G4H3ToolsManager.cc
References G4Analysis::GetNbins(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kZ.
G4String G4H3ToolsManager::GetH3Title (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 672 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 672 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::GetTitle().
const std::vector< tools::histo::h3d * > & G4H3ToolsManager::GetH3Vector () const inline
Definition at line 213 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 213 of file G4H3ToolsManager.hh
References G4THnManager< tools::histo::h3d >::fTVector.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4XmlAnalysisManager::WriteH3(), G4CsvAnalysisManager::WriteH3(), G4Hdf5AnalysisManager::WriteH3(), and G4RootAnalysisManager::WriteH3().
G4String G4H3ToolsManager::GetH3XAxisTitle (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 681 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 681 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kX.
G4double G4H3ToolsManager::GetH3Xmax (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 542 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 542 of file G4H3ToolsManager.cc
References G4Analysis::GetMax(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kX.
G4double G4H3ToolsManager::GetH3Xmin (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 531 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 531 of file G4H3ToolsManager.cc
References G4Analysis::GetMin(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kX.
G4double G4H3ToolsManager::GetH3XWidth (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 551 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 551 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager, G4THnManager< tools::histo::h3d >::GetTInFunction(), G4Analysis::GetWidth(), and G4Analysis::kX.
G4String G4H3ToolsManager::GetH3YAxisTitle (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 690 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 690 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kY.
G4double G4H3ToolsManager::GetH3Ymax (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 580 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 580 of file G4H3ToolsManager.cc
References G4Analysis::GetMax(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kY.
G4double G4H3ToolsManager::GetH3Ymin (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 569 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 569 of file G4H3ToolsManager.cc
References G4Analysis::GetMin(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kY.
G4double G4H3ToolsManager::GetH3YWidth (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 589 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 589 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager, G4THnManager< tools::histo::h3d >::GetTInFunction(), G4Analysis::GetWidth(), and G4Analysis::kY.
G4String G4H3ToolsManager::GetH3ZAxisTitle (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 699 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 699 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager, G4Analysis::GetAxisTitle(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kZ.
G4double G4H3ToolsManager::GetH3Zmax (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 618 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 618 of file G4H3ToolsManager.cc
References G4Analysis::GetMax(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kZ.
G4double G4H3ToolsManager::GetH3Zmin (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 607 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 607 of file G4H3ToolsManager.cc
References G4Analysis::GetMin(), G4THnManager< tools::histo::h3d >::GetTInFunction(), and G4Analysis::kZ.
G4double G4H3ToolsManager::GetH3ZWidth (G4int id) const final protected virtual
Implements G4VH3Manager.
Definition at line 627 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 627 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager, G4THnManager< tools::histo::h3d >::GetTInFunction(), G4Analysis::GetWidth(), and G4Analysis::kZ.
std::shared_ptr< G4HnManager > G4H3ToolsManager::GetHnManager () inline final protected virtual
Implements G4VH3Manager.
Definition at line 219 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 219 of file G4H3ToolsManager.hh
References G4THnManager< tools::histo::h3d >::fHnManager.
const std::vector< G4HnInformation * > & G4H3ToolsManager::GetHnVector () const inline
Definition at line 216 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 216 of file G4H3ToolsManager.hh
References G4THnManager< tools::histo::h3d >::fHnManager.
Referenced by G4ToolsAnalysisManager::MergeImpl(), G4XmlAnalysisManager::WriteH3(), G4CsvAnalysisManager::WriteH3(), G4Hdf5AnalysisManager::WriteH3(), and G4RootAnalysisManager::WriteH3().
G4bool G4H3ToolsManager::ScaleH3 (G4int id, G4double factor) final protected virtual
Implements G4VH3Manager.
Definition at line 468 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 468 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::GetTInFunction().
G4bool G4H3ToolsManager::SetH3 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinScheme = "linear", const G4String & ybinScheme = "linear", const G4String & zbinScheme = "linear") final protected virtual
Implements G4VH3Manager.
Definition at line 384 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 384 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager, G4THnManager< tools::histo::h3d >::fState, G4Analysis::GetBinScheme(), G4THnManager< tools::histo::h3d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4H3ToolsManager::SetH3 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const std::vector< G4double > & zedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none") final protected virtual
Implements G4VH3Manager.
Definition at line 430 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 430 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager, G4THnManager< tools::histo::h3d >::fState, G4THnManager< tools::histo::h3d >::GetTInFunction(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4H3ToolsManager::SetH3Title (G4int id, const G4String & title) final protected virtual
Implements G4VH3Manager.
Definition at line 636 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 636 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::GetTInFunction(), and SetTitle().
G4bool G4H3ToolsManager::SetH3XAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VH3Manager.
Definition at line 645 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 645 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::GetTInFunction(), G4Analysis::kX, and G4Analysis::SetAxisTitle().
G4bool G4H3ToolsManager::SetH3YAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VH3Manager.
Definition at line 654 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 654 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::GetTInFunction(), G4Analysis::kY, and G4Analysis::SetAxisTitle().
G4bool G4H3ToolsManager::SetH3ZAxisTitle (G4int id, const G4String & title) final protected virtual
Implements G4VH3Manager.
Definition at line 663 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 663 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::GetTInFunction(), G4Analysis::kZ, and G4Analysis::SetAxisTitle().
G4bool G4H3ToolsManager::WriteOnAscii (std::ofstream & output) final protected virtual
Implements G4VH3Manager.
Definition at line 708 of file G4H3ToolsManager.cc.
View newest version in sPHENIX GitHub at line 708 of file G4H3ToolsManager.cc
References G4THnManager< tools::histo::h3d >::fHnManager.
Member Data Documentation
const G4int G4H3ToolsManager::kDimension = 3 static private
Definition at line 195 of file G4H3ToolsManager.hh.
View newest version in sPHENIX GitHub at line 195 of file G4H3ToolsManager.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/hntools/include/G4H3ToolsManager.hh
geant4/tree/geant4-10.6-release/source/analysis/hntools/src/G4H3ToolsManager.cc