ECCE @ EIC Software: B4bRunData Class Reference
B4bRunData Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B4/B4b/include/B4bRunData.hh>
Public Member Functions
B4bRunData ()
virtual ~B4bRunData ()
void Add (G4int id, G4double de, G4double dl)
void FillPerEvent ()
void Reset ()
G4String GetVolumeName (G4int id) const
G4double GetEdep (G4int id) const
G4double GetTrackLength (G4int id) const
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
std::array< G4String, kDim > fVolumeNames
std::array< G4double, kDim > fEdep
std::array< G4double, kDim > fTrackLength
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Run data class
It defines data members to hold the energy deposit and track lengths of charged particles in Absober and Gap layers.
In order to reduce the number of data members a 2-dimensions array is introduced for each quantity:
fEdep[], fTrackLength[].
The data are collected step by step in B4bSteppingAction, and the accumulated values are filled in histograms and entuple event by event in B4EventAction.
Definition at line 57 of file B4bRunData.hh.
View newest version in sPHENIX GitHub at line 57 of file B4bRunData.hh
Constructor & Destructor Documentation
B4bRunData::B4bRunData ()
Definition at line 38 of file B4bRunData.cc.
View newest version in sPHENIX GitHub at line 38 of file B4bRunData.cc
virtual B4bRunData::~B4bRunData () virtual
Member Function Documentation
void B4bRunData::Add (G4int id, G4double de, G4double dl) inline
Definition at line 81 of file B4bRunData.hh.
View newest version in sPHENIX GitHub at line 81 of file B4bRunData.hh
References fEdep, and fTrackLength.
Referenced by B4bSteppingAction::UserSteppingAction().
void B4bRunData::FillPerEvent ()
Referenced by B4bEventAction::EndOfEventAction().
G4double B4bRunData::GetEdep (G4int id) const inline
Definition at line 90 of file B4bRunData.hh.
View newest version in sPHENIX GitHub at line 90 of file B4bRunData.hh
References fEdep.
G4double B4bRunData::GetTrackLength (G4int id) const inline
Definition at line 94 of file B4bRunData.hh.
View newest version in sPHENIX GitHub at line 94 of file B4bRunData.hh
References fTrackLength.
G4String B4bRunData::GetVolumeName (G4int id) const inline
Definition at line 86 of file B4bRunData.hh.
View newest version in sPHENIX GitHub at line 86 of file B4bRunData.hh
References fVolumeNames.
void B4bRunData::Reset ()
Referenced by B4bEventAction::BeginOfEventAction().
Member Data Documentation
std::array<G4double, kDim> B4bRunData::fEdep private
Definition at line 75 of file B4bRunData.hh.
View newest version in sPHENIX GitHub at line 75 of file B4bRunData.hh
Referenced by Add(), and GetEdep().
std::array<G4double, kDim> B4bRunData::fTrackLength private
Definition at line 76 of file B4bRunData.hh.
View newest version in sPHENIX GitHub at line 76 of file B4bRunData.hh
Referenced by Add(), and GetTrackLength().
std::array<G4String, kDim> B4bRunData::fVolumeNames private
Definition at line 74 of file B4bRunData.hh.
View newest version in sPHENIX GitHub at line 74 of file B4bRunData.hh
Referenced by GetVolumeName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B4/B4b/include/B4bRunData.hh
geant4/tree/geant4-10.6-release/examples/basic/B4/B4b/src/B4bRunData.cc