ECCE @ EIC Software: G4QGSBinaryNeutronBuilder Class Reference
G4QGSBinaryNeutronBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBinaryNeutronBuilder.hh>
Public Member Functions
G4QGSBinaryNeutronBuilder (G4bool quasiElastic=false)
virtual ~G4QGSBinaryNeutronBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4HadronFissionProcess *) finaloverride
virtual void Build (G4HadronCaptureProcess *) finaloverride
virtual void Build (G4NeutronInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VNeutronBuilder
G4VNeutronBuilder ()=default
virtual ~G4VNeutronBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4BinaryCascade * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4double theMin
Detailed Description
Definition at line 58 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4QGSBinaryNeutronBuilder.hh
Constructor & Destructor Documentation
G4QGSBinaryNeutronBuilder::G4QGSBinaryNeutronBuilder (G4bool quasiElastic = false)
Definition at line 49 of file G4QGSBinaryNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 49 of file G4QGSBinaryNeutronBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSBinaryNeutronBuilder::~G4QGSBinaryNeutronBuilder () virtual
Definition at line 71 of file G4QGSBinaryNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 71 of file G4QGSBinaryNeutronBuilder.cc
References theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4QGSBinaryNeutronBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 64 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QGSBinaryNeutronBuilder.hh
virtual void G4QGSBinaryNeutronBuilder::Build (G4HadronFissionProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 65 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QGSBinaryNeutronBuilder.hh
virtual void G4QGSBinaryNeutronBuilder::Build (G4HadronCaptureProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 66 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4QGSBinaryNeutronBuilder.hh
void G4QGSBinaryNeutronBuilder::Build (G4NeutronInelasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 79 of file G4QGSBinaryNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 79 of file G4QGSBinaryNeutronBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicParameters::Instance(), G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSBinaryNeutronBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 69 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4QGSBinaryNeutronBuilder.hh
References theMin.
Member Data Documentation
G4BinaryCascade* G4QGSBinaryNeutronBuilder::theCascade private
Definition at line 75 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSBinaryNeutronBuilder.hh
Referenced by G4QGSBinaryNeutronBuilder().
G4double G4QGSBinaryNeutronBuilder::theMin private
Definition at line 80 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4QGSBinaryNeutronBuilder.hh
Referenced by Build(), G4QGSBinaryNeutronBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSBinaryNeutronBuilder::theModel private
Definition at line 74 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QGSBinaryNeutronBuilder.hh
Referenced by Build(), and G4QGSBinaryNeutronBuilder().
G4QuasiElasticChannel* G4QGSBinaryNeutronBuilder::theQuasiElastic private
Definition at line 78 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSBinaryNeutronBuilder.hh
Referenced by G4QGSBinaryNeutronBuilder(), and ~G4QGSBinaryNeutronBuilder().
G4ExcitedStringDecay* G4QGSBinaryNeutronBuilder::theStringDecay private
Definition at line 77 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QGSBinaryNeutronBuilder.hh
Referenced by G4QGSBinaryNeutronBuilder(), and ~G4QGSBinaryNeutronBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSBinaryNeutronBuilder::theStringModel private
Definition at line 76 of file G4QGSBinaryNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSBinaryNeutronBuilder.hh
Referenced by G4QGSBinaryNeutronBuilder(), and ~G4QGSBinaryNeutronBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBinaryNeutronBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSBinaryNeutronBuilder.cc