ECCE @ EIC Software: G4INCL::OmegaNElasticChannel Class Reference
G4INCL::OmegaNElasticChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLOmegaNElasticChannel.hh>
Public Member Functions
OmegaNElasticChannel (Particle *, Particle *)
virtual ~OmegaNElasticChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
INCL_DECLARE_ALLOCATION_POOL (OmegaNElasticChannel)
Private Attributes
Particle * particle1
Particle * particle2
Detailed Description
Definition at line 47 of file G4INCLOmegaNElasticChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLOmegaNElasticChannel.hh
Constructor & Destructor Documentation
G4INCL::OmegaNElasticChannel::OmegaNElasticChannel (Particle * p1, Particle * p2)
Definition at line 47 of file G4INCLOmegaNElasticChannel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4INCLOmegaNElasticChannel.cc
G4INCL::OmegaNElasticChannel::~OmegaNElasticChannel () virtual
Definition at line 53 of file G4INCLOmegaNElasticChannel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4INCLOmegaNElasticChannel.cc
Member Function Documentation
void G4INCL::OmegaNElasticChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 57 of file G4INCLOmegaNElasticChannel.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLOmegaNElasticChannel.cc
References G4INCL::FinalState::addModifiedParticle(), G4INCL::Particle::getEnergy(), G4INCL::Particle::getMass(), G4INCL::Particle::isNucleon(), G4INCL::Random::normVector(), G4InuclParticleNames::nucleon(), particle1, particle2, G4InuclParticleNames::pn, G4INCL::Particle::setEnergy(), and G4INCL::Particle::setMomentum().
G4INCL::OmegaNElasticChannel::INCL_DECLARE_ALLOCATION_POOL (OmegaNElasticChannel) private
Member Data Documentation
Particle* G4INCL::OmegaNElasticChannel::particle1 private
Definition at line 55 of file G4INCLOmegaNElasticChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLOmegaNElasticChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::OmegaNElasticChannel::particle2 private
Definition at line 55 of file G4INCLOmegaNElasticChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLOmegaNElasticChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLOmegaNElasticChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLOmegaNElasticChannel.cc