ECCE @ EIC Software: G4AffineTransform Class Reference
G4AffineTransform Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4AffineTransform.hh>
Public Member Functions
G4AffineTransform ()
G4AffineTransform (const G4ThreeVector &tlate)
G4AffineTransform (const G4RotationMatrix &rot)
G4AffineTransform (const G4RotationMatrix &rot, const G4ThreeVector &tlate)
G4AffineTransform (const G4RotationMatrix *rot, const G4ThreeVector &tlate)
G4AffineTransform (const G4AffineTransform &rhs)
G4AffineTransform (G4AffineTransform &&rhs)=default
G4AffineTransform & operator= (const G4AffineTransform &rhs)
G4AffineTransform & operator= (G4AffineTransform &&rhs)=default
~G4AffineTransform ()
G4AffineTransform operator* (const G4AffineTransform &tf) const
G4AffineTransform & operator*= (const G4AffineTransform &tf)
G4AffineTransform & Product (const G4AffineTransform &tf1, const G4AffineTransform &tf2)
G4AffineTransform & InverseProduct (const G4AffineTransform &tf1, const G4AffineTransform &tf2)
G4ThreeVector TransformPoint (const G4ThreeVector &vec) const
G4ThreeVector InverseTransformPoint (const G4ThreeVector &vec) const
G4ThreeVector TransformAxis (const G4ThreeVector &axis) const
G4ThreeVector InverseTransformAxis (const G4ThreeVector &axis) const
void ApplyPointTransform (G4ThreeVector &vec) const
void ApplyAxisTransform (G4ThreeVector &axis) const
G4AffineTransform Inverse () const
G4AffineTransform & Invert ()
G4AffineTransform & operator+= (const G4ThreeVector &tlate)
G4AffineTransform & operator-= (const G4ThreeVector &tlate)
G4bool operator== (const G4AffineTransform &tf) const
G4bool operator!= (const G4AffineTransform &tf) const
G4double operator[] (const G4int n) const
G4bool IsRotated () const
G4bool IsTranslated () const
G4RotationMatrix NetRotation () const
G4RotationMatrix InverseNetRotation () const
G4ThreeVector NetTranslation () const
G4ThreeVector InverseNetTranslation () const
void SetNetRotation (const G4RotationMatrix &rot)
void SetNetTranslation (const G4ThreeVector &tlate)
operator G4Transform3D () const
Private Member Functions
G4AffineTransform (const G4double prxx, const G4double prxy, const G4double prxz, const G4double pryx, const G4double pryy, const G4double pryz, const G4double przx, const G4double przy, const G4double przz, const G4double ptx, const G4double pty, const G4double ptz)
Private Attributes
G4double rxx
G4double rxy
G4double rxz
G4double ryx
G4double ryy
G4double ryz
G4double rzx
G4double rzy
G4double rzz
G4double tx
G4double ty
G4double tz
Detailed Description
Definition at line 69 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 69 of file G4AffineTransform.hh
Constructor & Destructor Documentation
G4AffineTransform::G4AffineTransform () inline
G4AffineTransform::G4AffineTransform (const G4ThreeVector & tlate) inline
G4AffineTransform::G4AffineTransform (const G4RotationMatrix & rot) inline
G4AffineTransform::G4AffineTransform (const G4RotationMatrix & rot, const G4ThreeVector & tlate) inline
G4AffineTransform::G4AffineTransform (const G4RotationMatrix * rot, const G4ThreeVector & tlate) inline
G4AffineTransform::G4AffineTransform (const G4AffineTransform & rhs) inline
G4AffineTransform::G4AffineTransform (G4AffineTransform && rhs) inline default
G4AffineTransform::~G4AffineTransform () inline
G4AffineTransform::G4AffineTransform (const G4double prxx, const G4double prxy, const G4double prxz, const G4double pryx, const G4double pryy, const G4double pryz, const G4double przx, const G4double przy, const G4double przz, const G4double ptx, const G4double pty, const G4double ptz) inline private
Member Function Documentation
void G4AffineTransform::ApplyAxisTransform (G4ThreeVector & axis) const inline
Referenced by DicomIntersectVolume::SetNewValue().
void G4AffineTransform::ApplyPointTransform (G4ThreeVector & vec) const inline
Referenced by G4PolyconeSide::CalculateExtent(), and DicomIntersectVolume::SetNewValue().
G4AffineTransform G4AffineTransform::Inverse () const inline
Referenced by F04FocusSolenoid::AddFieldValue(), F04SimpleSolenoid::AddFieldValue(), G4ITNavigator1::ComputeStep(), G4ITNavigator1::ComputeStepLog(), F04ElementField::Construct(), G4DrawVoxels::DrawVoxels(), G4FastTrack::FRecordsAffineTransformation(), G4DisplacedSolid::G4DisplacedSolid(), F04PrimaryGeneratorAction::GeneratePrimaries(), CexmcReconstructor::ReconstructTargetPoint(), and CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::SetupConstructionHook().
G4RotationMatrix G4AffineTransform::InverseNetRotation () const inline
Referenced by G4TouchableHistory::G4TouchableHistory().
G4ThreeVector G4AffineTransform::InverseNetTranslation () const inline
Referenced by G4TouchableHistory::G4TouchableHistory().
G4AffineTransform& G4AffineTransform::InverseProduct (const G4AffineTransform & tf1, const G4AffineTransform & tf2) inline
G4ThreeVector G4AffineTransform::InverseTransformAxis (const G4ThreeVector & axis) const inline
Referenced by G4RegularNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4Navigator::GetGlobalExitNormal(), and G4Navigator::GetLocalExitNormal().
G4ThreeVector G4AffineTransform::InverseTransformPoint (const G4ThreeVector & vec) const inline
Referenced by G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4RegularNavigation::ComputeStep(), and G4RegularNavigation::ComputeStepSkippingEqualMaterials().
G4AffineTransform& G4AffineTransform::Invert () inline
Referenced by G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), ExN04CalorimeterSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), G4VoxelSafety::SafetyForVoxelNode(), and DicomIntersectVolume::SetNewValue().
G4bool G4AffineTransform::IsRotated () const inline
Referenced by G4DisplacedSolid::BoundingLimits().
G4bool G4AffineTransform::IsTranslated () const inline
G4RotationMatrix G4AffineTransform::NetRotation () const inline
Referenced by G4ScaledSolid::CalculateExtent(), G4DrawVoxels::DrawVoxels(), G4ErrorCylSurfaceTarget::Dump(), G4DisplacedSolid::GetFrameRotation(), G4VIntersectionLocator::GetGlobalSurfaceNormal(), G4DisplacedSolid::GetObjectRotation(), G4TouchableHistory::GetRotation(), ExN04CalorimeterSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), and G4DisplacedSolid::StreamInfo().
G4ThreeVector G4AffineTransform::NetTranslation () const inline
Referenced by G4AdjointCrossSurfChecker::AddaSphericalSurfaceWithCenterAtTheCenterOfAVolume(), G4DisplacedSolid::BoundingLimits(), G4ScaledSolid::CalculateExtent(), G4DrawVoxels::DrawVoxels(), G4ErrorCylSurfaceTarget::Dump(), G4DisplacedSolid::GetFrameTranslation(), G4VIntersectionLocator::GetGlobalSurfaceNormal(), G4DisplacedSolid::GetObjectTranslation(), G4ErrorCylSurfaceTarget::GetTangentPlane(), G4TouchableHistory::GetTranslation(), ExN04CalorimeterSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), CexmcReconstructor::ReconstructEntryPoints(), and G4DisplacedSolid::StreamInfo().
G4AffineTransform::operator G4Transform3D () const inline
G4bool G4AffineTransform::operator!= (const G4AffineTransform & tf) const inline
G4AffineTransform G4AffineTransform::operator* (const G4AffineTransform & tf) const inline
G4AffineTransform& G4AffineTransform::operator*= (const G4AffineTransform & tf) inline
G4AffineTransform& G4AffineTransform::operator+= (const G4ThreeVector & tlate) inline
G4AffineTransform& G4AffineTransform::operator-= (const G4ThreeVector & tlate) inline
G4AffineTransform& G4AffineTransform::operator= (const G4AffineTransform & rhs) inline
G4AffineTransform& G4AffineTransform::operator= (G4AffineTransform && rhs) inline default
G4bool G4AffineTransform::operator== (const G4AffineTransform & tf) const inline
G4double G4AffineTransform::operator[] (const G4int n) const inline
G4AffineTransform& G4AffineTransform::Product (const G4AffineTransform & tf1, const G4AffineTransform & tf2) inline
Referenced by G4DisplacedSolid::CalculateExtent().
void G4AffineTransform::SetNetRotation (const G4RotationMatrix & rot) inline
Referenced by CexmcSetup::ReadTransforms(), G4DisplacedSolid::SetFrameRotation(), and G4DisplacedSolid::SetObjectRotation().
void G4AffineTransform::SetNetTranslation (const G4ThreeVector & tlate) inline
Referenced by CexmcSetup::ReadTransforms(), G4DisplacedSolid::SetFrameTranslation(), and G4DisplacedSolid::SetObjectTranslation().
G4ThreeVector G4AffineTransform::TransformAxis (const G4ThreeVector & axis) const inline
Referenced by F04FocusSolenoid::AddFieldValue(), F04SimpleSolenoid::AddFieldValue(), G4RayTrajectory::AppendStep(), G4PolyPhiFace::CalculateExtent(), G4PolyconeSide::CalculateExtent(), G4PolyhedraSide::CalculateExtent(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4DisplacedSolid::DistanceToIn(), G4DisplacedSolid::DistanceToOut(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4ErrorCylSurfaceTarget::GetDistanceFromPoint(), G4ITNavigator1::GetGlobalExitNormal(), G4ITNavigator2::GetGlobalExitNormal(), G4VIntersectionLocator::GetGlobalSurfaceNormal(), G4RegularNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CexmcReconstructor::ReconstructEntryPoints(), CexmcReconstructor::ReconstructTargetPoint(), G4FastTrack::SetCurrentTrack(), and G4DisplacedSolid::SurfaceNormal().
G4ThreeVector G4AffineTransform::TransformPoint (const G4ThreeVector & vec) const inline
Referenced by F04FocusSolenoid::AddFieldValue(), F04SimpleSolenoid::AddFieldValue(), G4ReplicaNavigation::BackLocate(), G4PolyPhiFace::CalculateExtent(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4ReplicaNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), F04ElementField::Construct(), G4DNAMolecularDissociation::DecayIt(), G4DisplacedSolid::DistanceToIn(), G4DisplacedSolid::DistanceToOut(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnTheExtSurfaceOfThePhysicalVolume(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4ErrorCylSurfaceTarget::GetDistanceFromPoint(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4Navigator::GetLocalExitNormalAndCheck(), G4ITNavigator1::GetLocalExitNormalAndCheck(), G4ITNavigator2::GetLocalExitNormalAndCheck(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4DisplacedSolid::GetPointOnSurface(), G4ITNavigator2::GetRandomInCurrentVolume(), G4ErrorCylSurfaceTarget::GetTangentPlane(), G4DisplacedSolid::Inside(), G4ITNavigator2::InsideCurrentVolume(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), ScreenSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), CexmcReconstructor::ReconstructEntryPoints(), CexmcReconstructor::ReconstructTargetPoint(), G4FastTrack::SetCurrentTrack(), CCaloSD::SetToLocal(), PHG4SteppingAction::StoreLocalCoordinate(), G4DisplacedSolid::SurfaceNormal(), PHG4OuterHcalSteppingAction::UserSteppingAction(), and doiPETSteppingAction::UserSteppingAction().
Member Data Documentation
G4double G4AffineTransform::rxx private
Definition at line 185 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 185 of file G4AffineTransform.hh
G4double G4AffineTransform::rxy private
Definition at line 185 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 185 of file G4AffineTransform.hh
G4double G4AffineTransform::rxz private
Definition at line 185 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 185 of file G4AffineTransform.hh
G4double G4AffineTransform::ryx private
Definition at line 186 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 186 of file G4AffineTransform.hh
G4double G4AffineTransform::ryy private
Definition at line 186 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 186 of file G4AffineTransform.hh
G4double G4AffineTransform::ryz private
Definition at line 186 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 186 of file G4AffineTransform.hh
G4double G4AffineTransform::rzx private
Definition at line 187 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 187 of file G4AffineTransform.hh
G4double G4AffineTransform::rzy private
Definition at line 187 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 187 of file G4AffineTransform.hh
G4double G4AffineTransform::rzz private
Definition at line 187 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 187 of file G4AffineTransform.hh
G4double G4AffineTransform::tx private
Definition at line 188 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 188 of file G4AffineTransform.hh
G4double G4AffineTransform::ty private
Definition at line 188 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 188 of file G4AffineTransform.hh
G4double G4AffineTransform::tz private
Definition at line 188 of file G4AffineTransform.hh.
View newest version in sPHENIX GitHub at line 188 of file G4AffineTransform.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4AffineTransform.hh