ECCE @ EIC Software: G4TransportationManager Class Reference
G4TransportationManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4TransportationManager.hh>
Public Member Functions
G4PropagatorInField * GetPropagatorInField () const
void SetPropagatorInField (G4PropagatorInField *newFieldPropagator)
G4FieldManager * GetFieldManager () const
void SetFieldManager (G4FieldManager *newFieldManager)
G4Navigator * GetNavigatorForTracking () const
void SetNavigatorForTracking (G4Navigator *newNavigator)
void SetWorldForTracking (G4VPhysicalVolume *theWorld)
size_t GetNoActiveNavigators () const
std::vector< G4Navigator * >
::iterator GetActiveNavigatorsIterator ()
size_t GetNoWorlds () const
std::vector< G4VPhysicalVolume * >
::iterator GetWorldsIterator ()
G4SafetyHelper * GetSafetyHelper () const
G4VPhysicalVolume * GetParallelWorld (const G4String &worldName)
G4VPhysicalVolume * IsWorldExisting (const G4String &worldName)
G4Navigator * GetNavigator (const G4String &worldName)
G4Navigator * GetNavigator (G4VPhysicalVolume *aWorld)
G4bool RegisterWorld (G4VPhysicalVolume *aWorld)
void DeRegisterNavigator (G4Navigator *aNavigator)
G4int ActivateNavigator (G4Navigator *aNavigator)
void DeActivateNavigator (G4Navigator *aNavigator)
void InactivateAll ()
void ClearParallelWorlds ()
~G4TransportationManager ()
Static Public Member Functions
static G4TransportationManager * GetTransportationManager ()
static G4TransportationManager * GetInstanceIfExist ()
static G4Navigator * GetFirstTrackingNavigator ()
static void SetFirstTrackingNavigator (G4Navigator *nav)
Protected Member Functions
G4TransportationManager ()
Private Member Functions
void ClearNavigators ()
void DeRegisterWorld (G4VPhysicalVolume *aWorld)
Private Attributes
std::vector< G4Navigator * > fNavigators
std::vector< G4Navigator * > fActiveNavigators
std::vector< G4VPhysicalVolume * > fWorlds
G4PropagatorInField * fPropagatorInField
G4FieldManager * fFieldManager
G4GeometryMessenger * fGeomMessenger
G4SafetyHelper * fSafetyHelper
Static Private Attributes
static G4ThreadLocal
G4TransportationManager * fTransportationManager = nullptr
static G4Navigator * fFirstTrackingNavigator = nullptr
Detailed Description
Definition at line 53 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 53 of file G4TransportationManager.hh
Constructor & Destructor Documentation
G4TransportationManager::~G4TransportationManager ()
Definition at line 90 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 90 of file G4TransportationManager.cc
References ClearNavigators(), fGeomMessenger, fPropagatorInField, fSafetyHelper, and fTransportationManager.
G4TransportationManager::G4TransportationManager () protected
Definition at line 54 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 54 of file G4TransportationManager.cc
References G4Navigator::Activate(), G4Navigator::Clone(), fActiveNavigators, FatalException, fFieldManager, fFirstTrackingNavigator, fGeomMessenger, fNavigators, fPropagatorInField, fSafetyHelper, fTransportationManager, fWorlds, G4Exception(), G4Navigator::GetExternalNavigation(), and G4Navigator::GetWorldVolume().
Referenced by GetTransportationManager().
Member Function Documentation
G4int G4TransportationManager::ActivateNavigator (G4Navigator * aNavigator)
Definition at line 313 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 313 of file G4TransportationManager.cc
References G4Navigator::Activate(), fActiveNavigators, FatalException, fNavigators, G4Exception(), G4VPhysicalVolume::GetName(), G4Navigator::GetWorldVolume(), and message().
Referenced by G4CoupledTransportation::G4CoupledTransportation(), G4SafetyHelper::InitialiseNavigator(), G4WeightCutOffProcess::StartTracking(), G4ImportanceProcess::StartTracking(), G4WeightWindowProcess::StartTracking(), G4ParallelWorldScoringProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), G4FastSimulationManagerProcess::StartTracking(), G4ParallelGeometriesLimiterProcess::StartTracking(), and G4CoupledTransportation::StartTracking().
void G4TransportationManager::ClearNavigators () private
Definition at line 160 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 160 of file G4TransportationManager.cc
References fActiveNavigators, fNavigators, and fWorlds.
Referenced by ~G4TransportationManager().
void G4TransportationManager::ClearParallelWorlds ()
Definition at line 461 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 461 of file G4TransportationManager.cc
References fActiveNavigators, fNavigators, and fWorlds.
Referenced by G4WorkerRunManager::InitializeGeometry(), and G4RunManager::ReinitializeGeometry().
void G4TransportationManager::DeActivateNavigator (G4Navigator * aNavigator)
Definition at line 346 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 346 of file G4TransportationManager.cc
References fActiveNavigators, fNavigators, G4Exception(), G4VPhysicalVolume::GetName(), G4Navigator::GetWorldVolume(), JustWarning, and message().
Referenced by G4FastSimulationManagerProcess::EndTracking(), and G4ParallelGeometriesLimiterProcess::EndTracking().
void G4TransportationManager::DeRegisterNavigator (G4Navigator * aNavigator)
Definition at line 275 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 275 of file G4TransportationManager.cc
References DeRegisterWorld(), FatalException, fNavigators, G4Exception(), G4VPhysicalVolume::GetName(), G4Navigator::GetWorldVolume(), JustWarning, and message().
void G4TransportationManager::DeRegisterWorld (G4VPhysicalVolume * aWorld) private
Definition at line 437 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 437 of file G4TransportationManager.cc
References fWorlds, G4Exception(), G4VPhysicalVolume::GetName(), JustWarning, and message().
Referenced by DeRegisterNavigator().
std::vector<G4Navigator*>::iterator G4TransportationManager::GetActiveNavigatorsIterator () inline
Referenced by G4PathFinder::ComputeSafety(), G4MultiNavigator::GetGlobalExitNormal(), G4PathFinder::Locate(), G4MultiNavigator::LocateGlobalPointAndSetup(), G4MultiNavigator::LocateGlobalPointWithinVolume(), G4OpBoundaryProcess::PostStepDoIt(), G4MultiNavigator::PrepareNavigators(), G4PathFinder::PrepareNewTrack(), G4PathFinder::ReLocate(), and G4MultiNavigator::ResetHierarchyAndLocate().
G4FieldManager* G4TransportationManager::GetFieldManager () const inline
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), CCalDetectorConstruction::Construct(), RE01DetectorConstruction::ConstructSDandField(), RE05DetectorConstruction::ConstructSDandField(), ExUCNDetectorConstruction::ConstructSDandField(), F05DetectorConstruction::ConstructSDandField(), F06DetectorConstruction::ConstructSDandField(), PurgMagDetectorConstruction::ConstructSDandField(), G4VFieldModel::DescribeYourselfTo(), G4ITTransportation::DoesGlobalFieldExist(), export_G4TransportationManager(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), PHG4OuterHcalField::GetFieldValue(), ExErrorMagneticField::GetGlobalFieldManager(), ExN02MagneticField::GetGlobalFieldManager(), ExP01MagneticField::GetGlobalFieldManager(), G4TBMagneticFieldSetup::GetGlobalFieldManager(), F03FieldSetup::GetGlobalFieldManager(), G4MonopoleFieldSetup::GetGlobalFieldManager(), F02ElectricFieldSetup::GetGlobalFieldManager(), F01FieldSetup::GetGlobalFieldManager(), F04GlobalField::GetGlobalFieldManager(), G4ErrorPropagatorManager::InitFieldForBackwards(), F01FieldSetup::InitialiseAll(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), G4ErrorFreeTrajState::PropagateError(), G4GlobalMagFieldMessenger::SetField(), ExN03DetectorConstruction::SetMagField(), and DetectorConstruction::SetMagField().
G4Navigator * G4TransportationManager::GetFirstTrackingNavigator () static
Definition at line 483 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 483 of file G4TransportationManager.cc
References fFirstTrackingNavigator.
G4TransportationManager * G4TransportationManager::GetInstanceIfExist () static
Definition at line 118 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 118 of file G4TransportationManager.cc
References fTransportationManager.
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
G4Navigator * G4TransportationManager::GetNavigator (const G4String & worldName)
Definition at line 202 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 202 of file G4TransportationManager.cc
References FatalException, fNavigators, G4Exception(), IsWorldExisting(), message(), and G4Navigator::SetWorldVolume().
Referenced by G4WeightCutOffProcess::SetParallelWorld(), G4ImportanceProcess::SetParallelWorld(), G4ParallelWorldScoringProcess::SetParallelWorld(), G4WeightWindowProcess::SetParallelWorld(), G4ParallelWorldProcess::SetParallelWorld(), and G4FastSimulationManagerProcess::StartTracking().
G4Navigator * G4TransportationManager::GetNavigator (G4VPhysicalVolume * aWorld)
Definition at line 241 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 241 of file G4TransportationManager.cc
References FatalException, fNavigators, fWorlds, G4Exception(), G4VPhysicalVolume::GetName(), message(), and G4Navigator::SetWorldVolume().
G4Navigator* G4TransportationManager::GetNavigatorForTracking () const inline
Referenced by G4ParallelGeometriesLimiterProcess::AddParallelWorld(), G4RayTrajectory::AppendStep(), G4MultiNavigator::CheckMassWorld(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), G4TheRayTracer::CreateBitMap(), G4VFieldModel::DescribeYourselfTo(), DMXParticleSource::DMXParticleSource(), DMXStackingAction::DMXStackingAction(), G4EventManager::DoProcessing(), G4MaterialScanner::DoScan(), G4TrajectoryDrawByOriginVolume::Draw(), G4PathFinder::EnableParallelNavigation(), G4TrajectoryOriginVolumeFilter::Evaluate(), export_G4TransportationManager(), G4FastTrack::FRecordsAffineTransformation(), G4CoupledTransportation::G4CoupledTransportation(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), G4GeometrySampler::G4GeometrySampler(), G4ImportanceConfigurator::G4ImportanceConfigurator(), G4MonopoleTransportation::G4MonopoleTransportation(), G4MultiNavigator::G4MultiNavigator(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4Transportation::G4Transportation(), GetParallelWorld(), G4GeometryMessenger::Init(), G4SafetyHelper::InitialiseNavigator(), G4ITTransportationManager::Initialize(), G4SPSPosDistribution::IsSourceConfined(), G4FastSimulationManager::ListTitle(), GFlashHitMaker::make(), G4VTransitionRadiation::PostStepDoIt(), G4GeometryMessenger::ResetNavigator(), G4GeometryMessenger::SetCheckMode(), G4GeometryMessenger::SetPushFlag(), G4GeometryMessenger::SetVerbosity(), G4WeightWindowStore::SetWorldVolume(), G4IStore::SetWorldVolume(), G4ErrorPropagatorManager::StartNavigator(), G4FastSimulationManagerProcess::StartTracking(), and G4CoupledTransportation::StartTracking().
size_t G4TransportationManager::GetNoActiveNavigators () const inline
size_t G4TransportationManager::GetNoWorlds () const inline
Referenced by G4RunManagerKernel::CheckRegions(), G4MTRunManager::ConstructScoringWorlds(), G4TouchableUtils::FindTouchableProperties(), G4ITTransportationManager::Initialize(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), and G4PhysicalVolumeModel::Validate().
G4VPhysicalVolume * G4TransportationManager::GetParallelWorld (const G4String & worldName)
Definition at line 178 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 178 of file G4TransportationManager.cc
References G4VPhysicalVolume::GetLogicalVolume(), GetNavigatorForTracking(), G4LogicalVolume::GetSolid(), G4Navigator::GetWorldVolume(), IsWorldExisting(), and RegisterWorld().
Referenced by G4ParallelWorldPhysics::ConstructProcess(), G4RunManager::ConstructScoringWorlds(), G4ImportanceConfigurator::G4ImportanceConfigurator(), G4VUserParallelWorld::GetWorld(), GFlashHitMaker::make(), G4WeightCutOffProcess::SetParallelWorld(), G4ImportanceProcess::SetParallelWorld(), G4WeightWindowProcess::SetParallelWorld(), G4ParallelWorldScoringProcess::SetParallelWorld(), G4ParallelWorldProcess::SetParallelWorld(), G4WeightWindowStore::SetParallelWorldVolume(), and G4IStore::SetParallelWorldVolume().
G4PropagatorInField* G4TransportationManager::GetPropagatorInField () const inline
Referenced by G4DecayWithSpin::AtRestDoIt(), G4BlineTracer::ComputeBlines(), CCalDetectorConstruction::Construct(), F04GlobalField::ConstructField(), ExUCNDetectorConstruction::ConstructSDandField(), F05DetectorConstruction::ConstructSDandField(), export_G4TransportationManager(), PHG4OuterHcalSteppingAction::FieldChecker(), G4CoupledTransportation::G4CoupledTransportation(), G4ITTransportation::G4ITTransportation(), G4MonopoleTransportation::G4MonopoleTransportation(), G4PathFinder::G4PathFinder(), G4SynchrotronRadiation::G4SynchrotronRadiation(), G4SynchrotronRadiationInMat::G4SynchrotronRadiationInMat(), G4Transportation::G4Transportation(), DetectorConstruction::SetMaxStepLength(), G4TrackingMessenger::SetNewValue(), and G4ErrorPropagatorManager::StartNavigator().
G4SafetyHelper* G4TransportationManager::GetSafetyHelper () const inline
Referenced by G4PathFinder::EnableParallelNavigation(), G4CoupledTransportation::G4CoupledTransportation(), G4MonopoleTransportation::G4MonopoleTransportation(), G4MuNeutrinoNucleusProcess::G4MuNeutrinoNucleusProcess(), G4NeutrinoElectronProcess::G4NeutrinoElectronProcess(), G4Transportation::G4Transportation(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMscModel::GetParticleChangeForMSC(), G4PathFinder::PrepareNewTrack(), and G4VMultipleScattering::PreparePhysicsTable().
G4TransportationManager * G4TransportationManager::GetTransportationManager () static
Definition at line 104 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 104 of file G4TransportationManager.cc
References fTransportationManager, and G4TransportationManager().
Referenced by G4Scene::AddWorldIfEmpty(), G4RayTrajectory::AppendStep(), G4DecayWithSpin::AtRestDoIt(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4RunManagerKernel::CheckRegions(), G4VPrimaryGenerator::CheckVertexInsideWorld(), HepMCG4Interface::CheckVertexInsideWorld(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), G4BlineTracer::ComputeBlines(), H02DetectorConstruction::Construct(), CCalDetectorConstruction::Construct(), ExN04DetectorConstruction::Construct(), F04ElementField::Construct(), F04GlobalField::ConstructField(), G4ParallelWorldPhysics::ConstructProcess(), G4MTRunManager::ConstructScoringWorlds(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), RE01DetectorConstruction::ConstructSDandField(), RE05DetectorConstruction::ConstructSDandField(), ExUCNDetectorConstruction::ConstructSDandField(), F05DetectorConstruction::ConstructSDandField(), F06DetectorConstruction::ConstructSDandField(), PurgMagDetectorConstruction::ConstructSDandField(), G4TheRayTracer::CreateBitMap(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4RunManagerKernel::DefineWorldVolume(), G4VFieldModel::DescribeYourselfTo(), DMXParticleSource::DMXParticleSource(), DMXStackingAction::DMXStackingAction(), G4ITTransportation::DoesGlobalFieldExist(), G4EventManager::DoProcessing(), G4MaterialScanner::DoScan(), G4TrajectoryDrawByOriginVolume::Draw(), G4DrawVoxels::DrawVoxels(), G4CoupledTransportation::EndTracking(), G4TrajectoryOriginVolumeFilter::Evaluate(), export_G4TransportationManager(), PHG4OuterHcalSteppingAction::FieldChecker(), Par01PionShowerModel::FillFakeStep(), Par01EMShowerModel::FillFakeStep(), G4TouchableUtils::FindTouchableProperties(), G4FastTrack::FRecordsAffineTransformation(), G4CoupledTransportation::G4CoupledTransportation(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), G4GeometrySampler::G4GeometrySampler(), G4ImportanceConfigurator::G4ImportanceConfigurator(), G4ImportanceProcess::G4ImportanceProcess(), G4ITTransportation::G4ITTransportation(), G4MonopoleTransportation::G4MonopoleTransportation(), G4MultiNavigator::G4MultiNavigator(), G4MuNeutrinoNucleusProcess::G4MuNeutrinoNucleusProcess(), G4NeutrinoElectronProcess::G4NeutrinoElectronProcess(), G4ParallelGeometriesLimiterProcess::G4ParallelGeometriesLimiterProcess(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4PathFinder::G4PathFinder(), G4SteppingManager::G4SteppingManager(), G4SynchrotronRadiation::G4SynchrotronRadiation(), G4SynchrotronRadiationInMat::G4SynchrotronRadiationInMat(), G4Transportation::G4Transportation(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), F04PrimaryGeneratorAction::GeneratePrimaries(), G4VisManager::GeometryHasChanged(), PHG4OuterHcalField::GetFieldValue(), ExErrorMagneticField::GetGlobalFieldManager(), ExN02MagneticField::GetGlobalFieldManager(), ExP01MagneticField::GetGlobalFieldManager(), F03FieldSetup::GetGlobalFieldManager(), G4TBMagneticFieldSetup::GetGlobalFieldManager(), G4MonopoleFieldSetup::GetGlobalFieldManager(), F02ElectricFieldSetup::GetGlobalFieldManager(), F01FieldSetup::GetGlobalFieldManager(), F04GlobalField::GetGlobalFieldManager(), G4VMscModel::GetParticleChangeForMSC(), G4VUserParallelWorld::GetWorld(), G4ErrorPropagatorManager::InitFieldForBackwards(), G4TDNAOneStepThermalizationModel< MODEL >::Initialise(), F01FieldSetup::InitialiseAll(), G4SafetyHelper::InitialiseNavigator(), G4BOptnForceCommonTruncatedExp::Initialize(), G4ITTransportationManager::Initialize(), G4WorkerRunManager::InitializeGeometry(), G4ErrorRunManagerHelper::InitializeGeometry(), G4SPSPosDistribution::IsSourceConfined(), G4FastSimulationManager::ListTitle(), main(), GFlashHitMaker::make(), G4VTransitionRadiation::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), G4VMultipleScattering::PreparePhysicsTable(), G4ErrorFreeTrajState::PropagateError(), G4RunManager::ReinitializeGeometry(), G4BlineTracer::ResetChordFinders(), G4GlobalMagFieldMessenger::SetField(), ExN03DetectorConstruction::SetMagField(), DetectorConstruction::SetMagField(), DetectorConstruction::SetMaxStepLength(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4TrackingMessenger::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), G4WeightWindowStore::SetParallelWorldVolume(), G4IStore::SetParallelWorldVolume(), G4RTPrimaryGeneratorAction::SetUp(), G4WeightWindowStore::SetWorldVolume(), G4IStore::SetWorldVolume(), G4GlobalFastSimulationManager::ShowSetup(), G4ErrorPropagatorManager::StartNavigator(), G4FastSimulationManagerProcess::StartTracking(), G4CoupledTransportation::StartTracking(), G4PhysicalVolumeModel::Validate(), G4RunManagerKernel::WorkerDefineWorldVolume(), and G4RunManagerKernel::WorkerUpdateWorldVolume().
std::vector<G4VPhysicalVolume*>::iterator G4TransportationManager::GetWorldsIterator () inline
Referenced by G4RunManagerKernel::CheckRegions(), G4MTRunManager::ConstructScoringWorlds(), G4TouchableUtils::FindTouchableProperties(), G4ITTransportationManager::Initialize(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), and G4PhysicalVolumeModel::Validate().
void G4TransportationManager::InactivateAll ()
Definition at line 376 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 376 of file G4TransportationManager.cc
References fActiveNavigators, and fNavigators.
Referenced by G4CoupledTransportation::EndTracking().
G4VPhysicalVolume * G4TransportationManager::IsWorldExisting (const G4String & worldName)
Definition at line 398 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 398 of file G4TransportationManager.cc
References fNavigators, and fWorlds.
Referenced by G4ParallelGeometriesLimiterProcess::AddParallelWorld(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), GetNavigator(), GetParallelWorld(), G4ParallelGeometriesLimiterProcess::GetParallelWorldIndex(), G4ParallelGeometriesLimiterProcess::RemoveParallelWorld(), G4FastSimulationManagerProcess::SetWorldVolume(), and G4RunManagerKernel::WorkerUpdateWorldVolume().
G4bool G4TransportationManager::RegisterWorld (G4VPhysicalVolume * aWorld)
Definition at line 417 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 417 of file G4TransportationManager.cc
References fWorlds.
Referenced by GetParallelWorld(), G4RunManagerKernel::WorkerDefineWorldVolume(), and G4RunManagerKernel::WorkerUpdateWorldVolume().
void G4TransportationManager::SetFieldManager (G4FieldManager * newFieldManager)
Definition at line 128 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 128 of file G4TransportationManager.cc
References fFieldManager, and fPropagatorInField.
Referenced by export_G4TransportationManager().
void G4TransportationManager::SetFirstTrackingNavigator (G4Navigator * nav) static
Definition at line 493 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 493 of file G4TransportationManager.cc
References fFirstTrackingNavigator.
void G4TransportationManager::SetNavigatorForTracking (G4Navigator * newNavigator)
Definition at line 147 of file G4TransportationManager.cc.
View newest version in sPHENIX GitHub at line 147 of file G4TransportationManager.cc
References fActiveNavigators, fNavigators, fPropagatorInField, and G4PropagatorInField::SetNavigatorForPropagating().
Referenced by export_G4TransportationManager(), and G4ErrorPropagatorManager::StartNavigator().
void G4TransportationManager::SetPropagatorInField (G4PropagatorInField * newFieldPropagator) inline
Referenced by export_G4TransportationManager().
void G4TransportationManager::SetWorldForTracking (G4VPhysicalVolume * theWorld) inline
Referenced by G4RunManagerKernel::DefineWorldVolume(), and G4RunManagerKernel::WorkerDefineWorldVolume().
Member Data Documentation
std::vector<G4Navigator*> G4TransportationManager::fActiveNavigators private
Definition at line 143 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 143 of file G4TransportationManager.hh
Referenced by ActivateNavigator(), ClearNavigators(), ClearParallelWorlds(), DeActivateNavigator(), G4TransportationManager(), InactivateAll(), and SetNavigatorForTracking().
G4FieldManager* G4TransportationManager::fFieldManager private
Definition at line 149 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 149 of file G4TransportationManager.hh
Referenced by G4TransportationManager(), and SetFieldManager().
G4Navigator * G4TransportationManager::fFirstTrackingNavigator = nullptr static private
Definition at line 155 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 155 of file G4TransportationManager.hh
Referenced by G4TransportationManager(), GetFirstTrackingNavigator(), and SetFirstTrackingNavigator().
G4GeometryMessenger* G4TransportationManager::fGeomMessenger private
Definition at line 150 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 150 of file G4TransportationManager.hh
Referenced by G4TransportationManager(), and ~G4TransportationManager().
std::vector<G4Navigator*> G4TransportationManager::fNavigators private
Definition at line 141 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 141 of file G4TransportationManager.hh
Referenced by ActivateNavigator(), ClearNavigators(), ClearParallelWorlds(), DeActivateNavigator(), DeRegisterNavigator(), G4TransportationManager(), GetNavigator(), InactivateAll(), IsWorldExisting(), and SetNavigatorForTracking().
G4PropagatorInField* G4TransportationManager::fPropagatorInField private
Definition at line 148 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 148 of file G4TransportationManager.hh
Referenced by G4TransportationManager(), SetFieldManager(), SetNavigatorForTracking(), and ~G4TransportationManager().
G4SafetyHelper* G4TransportationManager::fSafetyHelper private
Definition at line 151 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 151 of file G4TransportationManager.hh
Referenced by G4TransportationManager(), and ~G4TransportationManager().
G4ThreadLocal G4TransportationManager * G4TransportationManager::fTransportationManager = nullptr static private
Definition at line 153 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 153 of file G4TransportationManager.hh
Referenced by G4TransportationManager(), GetInstanceIfExist(), GetTransportationManager(), and ~G4TransportationManager().
std::vector<G4VPhysicalVolume*> G4TransportationManager::fWorlds private
Definition at line 145 of file G4TransportationManager.hh.
View newest version in sPHENIX GitHub at line 145 of file G4TransportationManager.hh
Referenced by ClearNavigators(), ClearParallelWorlds(), DeRegisterWorld(), G4TransportationManager(), GetNavigator(), IsWorldExisting(), and RegisterWorld().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4TransportationManager.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4TransportationManager.cc