ECCE @ EIC Software: G4AdjointeIonisationModel Class Reference
G4AdjointeIonisationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointeIonisationModel.hh>
Public Member Functions
G4AdjointeIonisationModel ()
virtual ~G4AdjointeIonisationModel ()
virtual void SampleSecondaries (const G4Track &aTrack, G4bool IsScatProjToProjCase, G4ParticleChange *fParticleChange)
virtual G4double DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A=0.)
Public Member Functions inherited from G4VEmAdjointModel
G4VEmAdjointModel (const G4String &nam)
virtual ~G4VEmAdjointModel ()
virtual G4double AdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double GetAdjointCrossSection (const G4MaterialCutsCouple *aCouple, G4double primEnergy, G4bool IsScatProjToProjCase)
virtual G4double DiffCrossSectionPerAtomPrimToScatPrim (G4double kinEnergyProj, G4double kinEnergyScatProj, G4double Z, G4double A=0.)
virtual G4double DiffCrossSectionPerVolumePrimToSecond (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyProd)
virtual G4double DiffCrossSectionPerVolumePrimToScatPrim (const G4Material *aMaterial, G4double kinEnergyProj, G4double kinEnergyScatProj)
virtual G4double GetSecondAdjEnergyMaxForScatProjToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForScatProjToProjCase (G4double PrimAdjEnergy, G4double Tcut=0)
virtual G4double GetSecondAdjEnergyMaxForProdToProjCase (G4double PrimAdjEnergy)
virtual G4double GetSecondAdjEnergyMinForProdToProjCase (G4double PrimAdjEnergy)
void DefineCurrentMaterial (const G4MaterialCutsCouple *couple)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerAtomForSecond (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerAtomForScatProj (G4double kinEnergyProd, G4double Z, G4double A=0., G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerVolumeForSecond (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
std::vector< std::vector
< double > * > ComputeAdjointCrossSectionVectorPerVolumeForScatProj (G4Material *aMaterial, G4double kinEnergyProd, G4int nbin_pro_decade=10)
void SetCSMatrices (std::vector< G4AdjointCSMatrix * > *Vec1CSMatrix, std::vector< G4AdjointCSMatrix * > *Vec2CSMatrix)
G4ParticleDefinition * GetAdjointEquivalentOfDirectPrimaryParticleDefinition ()
G4ParticleDefinition * GetAdjointEquivalentOfDirectSecondaryParticleDefinition ()
G4double GetHighEnergyLimit ()
G4double GetLowEnergyLimit ()
void SetHighEnergyLimit (G4double aVal)
void SetLowEnergyLimit (G4double aVal)
void DefineDirectEMModel (G4VEmModel *aModel)
void SetAdjointEquivalentOfDirectPrimaryParticleDefinition (G4ParticleDefinition *aPart)
void SetAdjointEquivalentOfDirectSecondaryParticleDefinition (G4ParticleDefinition *aPart)
void SetSecondPartOfSameType (G4bool aBool)
G4bool GetSecondPartOfSameType ()
void SetUseMatrix (G4bool aBool)
void SetUseMatrixPerElement (G4bool aBool)
void SetUseOnlyOneMatrixForAllElements (G4bool aBool)
void SetApplyCutInRange (G4bool aBool)
G4bool GetUseMatrix ()
G4bool GetUseMatrixPerElement ()
G4bool GetUseOnlyOneMatrixForAllElements ()
G4bool GetApplyCutInRange ()
G4String GetName ()
virtual void SetCSBiasingFactor (G4double aVal)
void SetCorrectWeightForPostStepInModel (G4bool aBool)
void SetAdditionalWeightCorrectionFactorForPostStepOutsideModel (G4double factor)
Private Member Functions
G4double DiffCrossSectionMoller (G4double kinEnergyProj, G4double kinEnergyProd)
Private Attributes
G4bool WithRapidSampling
Additional Inherited Members
Protected Member Functions inherited from G4VEmAdjointModel
G4double DiffCrossSectionFunction1 (G4double kinEnergyProj)
G4double DiffCrossSectionFunction2 (G4double kinEnergyProj)
G4double DiffCrossSectionPerVolumeFunctionForIntegrationOverEkinProj (G4double EkinProd)
G4double SampleAdjSecEnergyFromCSMatrix (size_t MatrixIndex, G4double prim_energy, G4bool IsScatProjToProjCase)
G4double SampleAdjSecEnergyFromCSMatrix (G4double prim_energy, G4bool IsScatProjToProjCase)
void SelectCSMatrix (G4bool IsScatProjToProjCase)
virtual G4double SampleAdjSecEnergyFromDiffCrossSectionPerAtom (G4double prim_energy, G4bool IsScatProjToProjCase)
virtual void CorrectPostStepWeight (G4ParticleChange *fParticleChange, G4double old_weight, G4double adjointPrimKinEnergy, G4double projectileKinEnergy, G4bool IsScatProjToProjCase)
Protected Attributes inherited from G4VEmAdjointModel
G4VEmModel * theDirectEMModel
G4VParticleChange * pParticleChange
const G4String name
G4int ASelectedNucleus
G4int ZSelectedNucleus
G4Material * SelectedMaterial
G4double kinEnergyProdForIntegration
G4double kinEnergyScatProjForIntegration
G4double kinEnergyProjForIntegration
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForProdToProjBackwardScattering
std::vector< G4AdjointCSMatrix * > * pOnCSMatrixForScatProjToProjBackwardScattering
std::vector< G4double > CS_Vs_ElementForScatProjToProjCase
std::vector< G4double > CS_Vs_ElementForProdToProjCase
G4double lastCS
G4double lastAdjointCSForScatProjToProjCase
G4double lastAdjointCSForProdToProjCase
G4ParticleDefinition * theAdjEquivOfDirectPrimPartDef
G4ParticleDefinition * theAdjEquivOfDirectSecondPartDef
G4ParticleDefinition * theDirectPrimaryPartDef
G4bool second_part_of_same_type
G4double preStepEnergy
G4Material * currentMaterial
G4MaterialCutsCouple * currentCouple
size_t currentMaterialIndex
size_t currentCoupleIndex
G4double currentTcutForDirectPrim
G4double currentTcutForDirectSecond
G4bool ApplyCutInRange
G4double mass_ratio_product
G4double mass_ratio_projectile
G4double HighEnergyLimit
G4double LowEnergyLimit
G4double CS_biasing_factor
G4bool UseMatrix
G4bool UseMatrixPerElement
G4bool UseOnlyOneMatrixForAllElements
size_t indexOfUsedCrossSectionMatrix
size_t model_index
G4bool correct_weight_for_post_step_in_model
G4double additional_weight_correction_factor_for_post_step_outside_model
Detailed Description
Definition at line 51 of file G4AdjointeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 51 of file G4AdjointeIonisationModel.hh
Constructor & Destructor Documentation
G4AdjointeIonisationModel::G4AdjointeIonisationModel ()
Definition at line 41 of file G4AdjointeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 41 of file G4AdjointeIonisationModel.cc
References G4AdjointElectron::AdjointElectron(), G4VEmAdjointModel::ApplyCutInRange, G4VEmAdjointModel::CS_biasing_factor, G4Electron::Electron(), G4VEmAdjointModel::second_part_of_same_type, G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef, G4VEmAdjointModel::theDirectPrimaryPartDef, G4VEmAdjointModel::UseMatrix, G4VEmAdjointModel::UseMatrixPerElement, G4VEmAdjointModel::UseOnlyOneMatrixForAllElements, and WithRapidSampling.
G4AdjointeIonisationModel::~G4AdjointeIonisationModel () virtual
Definition at line 60 of file G4AdjointeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 60 of file G4AdjointeIonisationModel.cc
Member Function Documentation
G4double G4AdjointeIonisationModel::DiffCrossSectionMoller (G4double kinEnergyProj, G4double kinEnergyProd) private
Definition at line 197 of file G4AdjointeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 197 of file G4AdjointeIonisationModel.cc
References source.hepunit::electron_mass_c2, energy, fac, G4InuclParticleNames::gam, source.hepunit::twopi_mc2_rcl2, x, and y.
Referenced by DiffCrossSectionPerAtomPrimToSecond().
G4double G4AdjointeIonisationModel::DiffCrossSectionPerAtomPrimToSecond (G4double kinEnergyProj, G4double kinEnergyProd, G4double Z, G4double A = 0.) virtual
Reimplemented from G4VEmAdjointModel.
Definition at line 175 of file G4AdjointeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 175 of file G4AdjointeIonisationModel.cc
References DiffCrossSectionMoller(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForProdToProjCase(), and G4VEmAdjointModel::GetSecondAdjEnergyMinForProdToProjCase().
void G4AdjointeIonisationModel::SampleSecondaries (const G4Track & aTrack, G4bool IsScatProjToProjCase, G4ParticleChange * fParticleChange) virtual
Implements G4VEmAdjointModel.
Definition at line 64 of file G4AdjointeIonisationModel.cc.
View newest version in sPHENIX GitHub at line 64 of file G4AdjointeIonisationModel.cc
References G4ParticleChange::AddSecondary(), G4VEmAdjointModel::CorrectPostStepWeight(), G4VEmAdjointModel::currentMaterial, G4VEmAdjointModel::currentTcutForDirectSecond, G4VEmAdjointModel::DiffCrossSectionPerVolumePrimToScatPrim(), G4VEmAdjointModel::DiffCrossSectionPerVolumePrimToSecond(), Emax, Emin, fStopAndKill, G4UniformRand, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGMass(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMaxForScatProjToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForProdToProjCase(), G4VEmAdjointModel::GetSecondAdjEnergyMinForScatProjToProjCase(), G4DynamicParticle::GetTotalMomentum(), G4Track::GetWeight(), G4VEmAdjointModel::HighEnergyLimit, G4VEmAdjointModel::lastAdjointCSForProdToProjCase, G4VEmAdjointModel::lastAdjointCSForScatProjToProjCase, G4VEmAdjointModel::lastCS, phi, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeParentWeight(), G4VParticleChange::ProposeTrackStatus(), CLHEP::Hep3Vector::rotateUz(), G4VEmAdjointModel::SampleAdjSecEnergyFromCSMatrix(), G4VParticleChange::SetParentWeightByProcess(), G4VParticleChange::SetSecondaryWeightByProcess(), G4VEmAdjointModel::theAdjEquivOfDirectPrimPartDef, G4VEmAdjointModel::theAdjEquivOfDirectSecondPartDef, CLHEP::Hep3Vector::unit(), and WithRapidSampling.
Member Data Documentation
G4bool G4AdjointeIonisationModel::WithRapidSampling private
Definition at line 77 of file G4AdjointeIonisationModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AdjointeIonisationModel.hh
Referenced by G4AdjointeIonisationModel(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/include/G4AdjointeIonisationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/adjoint/src/G4AdjointeIonisationModel.cc