ECCE @ EIC Software: G4PersistencyManager Class Reference
G4PersistencyManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4PersistencyManager.hh>
Public Member Functions
G4PersistencyManager (G4PersistencyCenter *pc, std::string n)
virtual ~G4PersistencyManager ()
virtual G4PersistencyManager * Create ()
std::string GetName ()
virtual G4VPEventIO * EventIO ()
virtual G4VPHitIO * HitIO ()
virtual G4VPDigitIO * DigitIO ()
virtual G4VMCTruthIO * MCTruthIO ()
virtual G4VTransactionManager * TransactionManager ()
virtual void Initialize ()
void SetVerboseLevel (int v)
G4bool Store (const G4Event *evt)
G4bool Retrieve (G4Event *&evt)
G4bool Store (const G4Run *)
G4bool Retrieve (G4Run *&)
G4bool Store (const G4VPhysicalVolume *)
G4bool Retrieve (G4VPhysicalVolume *&)
Public Member Functions inherited from G4VPersistencyManager
virtual ~G4VPersistencyManager ()
Static Protected Member Functions
static G4PersistencyManager * GetPersistencyManager ()
Protected Attributes
G4PersistencyCenter * f_pc
int m_verbose
Private Attributes
std::string nameMgr
G4bool f_is_initialized
Friends
class G4PersistencyCenter
Additional Inherited Members
Static Public Member Functions inherited from G4VPersistencyManager
static G4VPersistencyManager * GetPersistencyManager ()
Protected Member Functions inherited from G4VPersistencyManager
G4VPersistencyManager ()
Detailed Description
Definition at line 114 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 114 of file G4PersistencyManager.hh
Constructor & Destructor Documentation
G4PersistencyManager::G4PersistencyManager (G4PersistencyCenter * pc, std::string n)
Definition at line 38 of file G4PersistencyManager.cc.
View newest version in sPHENIX GitHub at line 38 of file G4PersistencyManager.cc
References f_pc, m_verbose, and G4PersistencyCenter::VerboseLevel().
G4PersistencyManager::~G4PersistencyManager () virtual
Definition at line 45 of file G4PersistencyManager.cc.
View newest version in sPHENIX GitHub at line 45 of file G4PersistencyManager.cc
Member Function Documentation
virtual G4PersistencyManager* G4PersistencyManager::Create () inline virtual
Reimplemented in G4PersistencyManagerT< T >.
Definition at line 127 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 127 of file G4PersistencyManager.hh
Referenced by G4PersistencyCenter::SelectSystem().
virtual G4VPDigitIO* G4PersistencyManager::DigitIO () inline virtual
Reimplemented in G4PersistencyManagerT< T >.
Definition at line 141 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 141 of file G4PersistencyManager.hh
Referenced by G4PersistencyManagerT< T >::DigitIO(), SetVerboseLevel(), and Store().
virtual G4VPEventIO* G4PersistencyManager::EventIO () inline virtual
Reimplemented in G4PersistencyManagerT< T >.
Definition at line 133 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 133 of file G4PersistencyManager.hh
Referenced by G4PersistencyManagerT< T >::EventIO(), Retrieve(), SetVerboseLevel(), and Store().
std::string G4PersistencyManager::GetName (void) inline
Definition at line 130 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PersistencyManager.hh
References nameMgr.
Referenced by G4PersistencyManagerT< T >::Create(), and G4PersistencyCenter::RegisterPersistencyManager().
G4PersistencyManager * G4PersistencyManager::GetPersistencyManager () static protected
Definition at line 49 of file G4PersistencyManager.cc.
View newest version in sPHENIX GitHub at line 49 of file G4PersistencyManager.cc
References G4PersistencyCenter::CurrentPersistencyManager(), and G4PersistencyCenter::GetPersistencyCenter().
virtual G4VPHitIO* G4PersistencyManager::HitIO () inline virtual
Reimplemented in G4PersistencyManagerT< T >.
Definition at line 137 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 137 of file G4PersistencyManager.hh
Referenced by G4PersistencyManagerT< T >::HitIO(), SetVerboseLevel(), and Store().
virtual void G4PersistencyManager::Initialize () inline virtual
Reimplemented in G4PersistencyManagerT< T >.
Definition at line 153 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 153 of file G4PersistencyManager.hh
Referenced by Retrieve(), and Store().
virtual G4VMCTruthIO* G4PersistencyManager::MCTruthIO () inline virtual
Reimplemented in G4PersistencyManagerT< T >.
Definition at line 145 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 145 of file G4PersistencyManager.hh
Referenced by G4PersistencyManagerT< T >::MCTruthIO(), SetVerboseLevel(), and Store().
G4bool G4PersistencyManager::Retrieve (G4Event *& evt) virtual
Implements G4VPersistencyManager.
Definition at line 230 of file G4PersistencyManager.cc.
View newest version in sPHENIX GitHub at line 230 of file G4PersistencyManager.cc
References G4VTransactionManager::Abort(), G4VTransactionManager::Commit(), G4PersistencyCenter::CurrentReadFile(), G4PersistencyCenter::CurrentRetrieveMode(), EventIO(), f_is_initialized, f_pc, false, file, G4cerr, G4cout, G4endl, G4Event::GetEventID(), Initialize(), m_verbose, G4VPEventIO::Retrieve(), TransactionManager(), and true.
G4bool G4PersistencyManager::Retrieve (G4Run *&) inline virtual
Implements G4VPersistencyManager.
Definition at line 169 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 169 of file G4PersistencyManager.hh
G4bool G4PersistencyManager::Retrieve (G4VPhysicalVolume *&) inline virtual
Implements G4VPersistencyManager.
Definition at line 175 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 175 of file G4PersistencyManager.hh
void G4PersistencyManager::SetVerboseLevel (int v)
Definition at line 55 of file G4PersistencyManager.cc.
View newest version in sPHENIX GitHub at line 55 of file G4PersistencyManager.cc
References DigitIO(), EventIO(), G4cout, G4endl, G4DCIOcatalog::GetDCIOcatalog(), G4DCIOcatalog::GetDCIOmanager(), G4HCIOcatalog::GetHCIOcatalog(), G4HCIOcatalog::GetHCIOmanager(), HitIO(), m_verbose, MCTruthIO(), nameMgr, G4DCIOcatalog::NumberOfDCIOmanager(), G4HCIOcatalog::NumberOfHCIOmanager(), G4VPEventIO::SetVerboseLevel(), G4VTransactionManager::SetVerboseLevel(), G4VMCTruthIO::SetVerboseLevel(), G4HCIOcatalog::SetVerboseLevel(), G4DCIOcatalog::SetVerboseLevel(), G4VPDigitIO::SetVerboseLevel(), G4VPHitIO::SetVerboseLevel(), G4VPHitsCollectionIO::SetVerboseLevel(), G4VPDigitsCollectionIO::SetVerboseLevel(), TransactionManager(), and v.
Referenced by G4PersistencyCenter::SelectSystem(), G4PersistencyManagerT< T >::SetVerboseLevel(), and G4PersistencyCenter::SetVerboseLevel().
G4bool G4PersistencyManager::Store (const G4Event * evt) virtual
Implements G4VPersistencyManager.
Definition at line 88 of file G4PersistencyManager.cc.
View newest version in sPHENIX GitHub at line 88 of file G4PersistencyManager.cc
References G4VTransactionManager::Abort(), G4VTransactionManager::Commit(), G4PersistencyCenter::CurrentStoreMode(), G4PersistencyCenter::CurrentWriteFile(), DigitIO(), EventIO(), f_is_initialized, f_pc, file, G4cerr, G4cout, G4endl, G4Event::GetDCofThisEvent(), G4Event::GetEventID(), G4Event::GetHCofThisEvent(), G4INCL::PhysicalConstants::hc, HitIO(), Initialize(), kOff, kOn, m_verbose, MCTruthIO(), G4VMCTruthIO::Store(), G4VPHitIO::Store(), G4VPDigitIO::Store(), G4VPEventIO::Store(), and TransactionManager().
G4bool G4PersistencyManager::Store (const G4Run *) inline virtual
Implements G4VPersistencyManager.
Definition at line 166 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 166 of file G4PersistencyManager.hh
G4bool G4PersistencyManager::Store (const G4VPhysicalVolume *) inline virtual
Implements G4VPersistencyManager.
Definition at line 172 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 172 of file G4PersistencyManager.hh
virtual G4VTransactionManager* G4PersistencyManager::TransactionManager () inline virtual
Reimplemented in G4PersistencyManagerT< T >.
Definition at line 149 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 149 of file G4PersistencyManager.hh
Referenced by Retrieve(), SetVerboseLevel(), Store(), and G4PersistencyManagerT< T >::TransactionManager().
Friends And Related Function Documentation
friend class G4PersistencyCenter friend
Definition at line 117 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PersistencyManager.hh
Member Data Documentation
G4bool G4PersistencyManager::f_is_initialized private
Definition at line 188 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 188 of file G4PersistencyManager.hh
Referenced by Retrieve(), and Store().
G4PersistencyCenter* G4PersistencyManager::f_pc protected
Definition at line 183 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 183 of file G4PersistencyManager.hh
Referenced by G4PersistencyManagerT< T >::Create(), G4PersistencyManager(), Retrieve(), and Store().
int G4PersistencyManager::m_verbose protected
Definition at line 184 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 184 of file G4PersistencyManager.hh
Referenced by G4PersistencyManager(), G4PersistencyManagerT< T >::G4PersistencyManagerT(), Retrieve(), SetVerboseLevel(), and Store().
std::string G4PersistencyManager::nameMgr private
Definition at line 187 of file G4PersistencyManager.hh.
View newest version in sPHENIX GitHub at line 187 of file G4PersistencyManager.hh
Referenced by GetName(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4PersistencyManager.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4PersistencyManager.cc