ECCE @ EIC Software: Par02Smearer Class Reference
Par02Smearer Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02Smearer.hh>
Public Member Functions
G4ThreeVector SmearMomentum (const G4Track *aTrack, G4double aResolution=-1)
G4double SmearEnergy (const G4Track *aTrack, G4double aResolution=-1)
G4ThreeVector SmearGaussian (const G4Track *aTrackOriginal, G4double aResolution)
G4double Gauss (G4double aMean, G4double aStandardDeviation)
Static Public Member Functions
static Par02Smearer * Instance ()
Protected Member Functions
Par02Smearer ()
A default constructor.
~Par02Smearer ()
Private Attributes
CLHEP::HepRandomEngine * fRandomEngine
CLHEP random engine.
CLHEP::RandGauss * fRandomGauss
CLHEP random engine used in gaussian smearing.
Static Private Attributes
static Par02Smearer * fPar02Smearer = 0
A pointer to Par02Smearer object.
Detailed Description
Smearing of the particle momentum or energy.
A singleton class used to smear (alter) the particle momentum (for tracking detectors) and energy (for calorimeters). In case the resolution is given, the momentum (energy) is smeared with Gaussian distribution.
Author
Anna Zaborowska
Definition at line 46 of file Par02Smearer.hh.
View newest version in sPHENIX GitHub at line 46 of file Par02Smearer.hh
Constructor & Destructor Documentation
Par02Smearer::Par02Smearer () protected
A default constructor.
Definition at line 46 of file Par02Smearer.cc.
View newest version in sPHENIX GitHub at line 46 of file Par02Smearer.cc
References fRandomEngine, fRandomGauss, seed, and Acts::VectorHelpers::time().
Referenced by Instance().
Par02Smearer::~Par02Smearer () protected
Definition at line 54 of file Par02Smearer.cc.
View newest version in sPHENIX GitHub at line 54 of file Par02Smearer.cc
Member Function Documentation
G4double Par02Smearer::Gauss (G4double aMean, G4double aStandardDeviation)
Returns a random number from a Gaussian distribution.
Parameters
aMean The mean of the Gaussian distribution.
aStandardDeviation The standard deviation of a Gaussian distribution.
Definition at line 102 of file Par02Smearer.cc.
View newest version in sPHENIX GitHub at line 102 of file Par02Smearer.cc
References CLHEP::RandGauss::fire(), and fRandomGauss.
Referenced by SmearEnergy(), and SmearGaussian().
Par02Smearer * Par02Smearer::Instance (void) static
Allows the access to the unique Par02Smearer class object.
Returns
A pointer to the Par02Smearer class.
Definition at line 58 of file Par02Smearer.cc.
View newest version in sPHENIX GitHub at line 58 of file Par02Smearer.cc
References fPar02Smearer, and Par02Smearer().
Referenced by Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), and Par02FastSimModelTracker::DoIt().
G4double Par02Smearer::SmearEnergy (const G4Track * aTrack, G4double aResolution = -1)
Smears the energy deposit with a given resolution.
Parameters
aTrack A track to smear.
aResolution A resolution. Gaussian smearing is done with a given resolution as a standard deviation.
Definition at line 74 of file Par02Smearer.cc.
View newest version in sPHENIX GitHub at line 74 of file Par02Smearer.cc
References Gauss(), and G4Track::GetKineticEnergy().
G4ThreeVector Par02Smearer::SmearGaussian (const G4Track * aTrackOriginal, G4double aResolution)
First possible type of smearing. Smears the momentum with a given resolution.
Parameters
aTrackOriginal A track to smear.
aResolution A resolution taken as a standard deviation of a Gaussian distribution.
Definition at line 91 of file Par02Smearer.cc.
View newest version in sPHENIX GitHub at line 91 of file Par02Smearer.cc
References Gauss(), G4Track::GetMomentum(), G4Track::GetPosition(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SmearMomentum().
G4ThreeVector Par02Smearer::SmearMomentum (const G4Track * aTrack, G4double aResolution = -1)
Smears the momentum with a given resolution.
Parameters
aTrack A track to smear.
aResolution A resolution. Gaussian smearing is done with a given resolution as a standard deviation.
Definition at line 67 of file Par02Smearer.cc.
View newest version in sPHENIX GitHub at line 67 of file Par02Smearer.cc
References SmearGaussian().
Member Data Documentation
Par02Smearer * Par02Smearer::fPar02Smearer = 0 static private
A pointer to Par02Smearer object.
Definition at line 86 of file Par02Smearer.hh.
View newest version in sPHENIX GitHub at line 86 of file Par02Smearer.hh
Referenced by Instance().
CLHEP::HepRandomEngine* Par02Smearer::fRandomEngine private
CLHEP random engine.
Definition at line 89 of file Par02Smearer.hh.
View newest version in sPHENIX GitHub at line 89 of file Par02Smearer.hh
Referenced by Par02Smearer().
CLHEP::RandGauss* Par02Smearer::fRandomGauss private
CLHEP random engine used in gaussian smearing.
Definition at line 92 of file Par02Smearer.hh.
View newest version in sPHENIX GitHub at line 92 of file Par02Smearer.hh
Referenced by Gauss(), and Par02Smearer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02Smearer.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/src/Par02Smearer.cc