ECCE @ EIC Software: G4HadronElastic Class Reference
G4HadronElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4HadronElastic.hh>
Public Member Functions
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) override
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A) override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Protected Attributes
G4double pLocalTmax
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Private Attributes
G4ParticleDefinition * theProton
G4ParticleDefinition * theNeutron
G4ParticleDefinition * theDeuteron
G4ParticleDefinition * theAlpha
G4double lowestEnergyLimit
G4int nwarn
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Detailed Description
Definition at line 48 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 48 of file G4HadronElastic.hh
Constructor & Destructor Documentation
G4HadronElastic::G4HadronElastic (const G4String & name = "hElasticLHEP") explicit
Definition at line 48 of file G4HadronElastic.cc.
View newest version in sPHENIX GitHub at line 48 of file G4HadronElastic.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), eV, G4HadronicInteraction::GetMaxEnergy(), GeV, G4HadronicParameters::Instance(), lowestEnergyLimit, G4Neutron::Neutron(), nwarn, pLocalTmax, G4Proton::Proton(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theAlpha, theDeuteron, theNeutron, and theProton.
G4HadronElastic::~G4HadronElastic () override
Definition at line 63 of file G4HadronElastic.cc.
View newest version in sPHENIX GitHub at line 63 of file G4HadronElastic.cc
Member Function Documentation
G4HadFinalState * G4HadronElastic::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) override virtual
Implements G4HadronicInteraction.
Reimplemented in G4LEHadronProtonElastic, G4NeutronElectronElModel, G4NeutrinoElectronNcModel, G4LEpp, and G4LEnp.
Definition at line 78 of file G4HadronElastic.cc.
View newest version in sPHENIX GitHub at line 78 of file G4HadronElastic.cc
References A(), G4HadFinalState::AddSecondary(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4HadFinalState::Clear(), CLHEP::HepLorentzVector::e(), e1, G4cout, G4endl, G4Exception(), G4UniformRand, G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4HadronicInteraction::GetModelName(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4HadronicInteraction::GetRecoilEnergyThreshold(), G4Nucleus::GetZ_asInt(), GeV, G4He3::He3(), JustWarning, lowestEnergyLimit, max, MeV, nwarn, phi, pLocalTmax, SampleInvariantT(), G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetLocalEnergyDeposit(), G4HadFinalState::SetMomentumChange(), t, theAlpha, theDeuteron, G4HadronicInteraction::theParticleChange, theProton, G4Triton::Triton(), CLHEP::twopi, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, and Z.
G4double G4HadronElastic::ComputeMomentumCMS (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) inline
Definition at line 101 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 101 of file G4HadronElastic.hh
References G4NucleiProperties::GetNuclearMass(), and G4ParticleDefinition::GetPDGMass().
G4double G4HadronElastic::GetSlopeCof (const G4int pdg)
Definition at line 273 of file G4HadronElastic.cc.
View newest version in sPHENIX GitHub at line 273 of file G4HadronElastic.cc
G4double G4HadronElastic::LowestEnergyLimit () const inline
Definition at line 95 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 95 of file G4HadronElastic.hh
References lowestEnergyLimit.
Referenced by G4NeutrinoElectronNcModel::ApplyYourself(), and G4NeutronElectronElModel::ApplyYourself().
void G4HadronElastic::ModelDescription (std::ostream & outFile) const override virtual
Reimplemented from G4HadronicInteraction.
Reimplemented in G4NeutronElectronElModel, and G4NeutrinoElectronNcModel.
Definition at line 67 of file G4HadronElastic.cc.
View newest version in sPHENIX GitHub at line 67 of file G4HadronElastic.cc
G4double G4HadronElastic::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) override virtual
Reimplemented from G4HadronicInteraction.
Reimplemented in G4hhElastic, G4NuclNuclDiffuseElastic, G4LEHadronProtonElastic, G4LEnp, G4LEpp, and G4LowEHadronElastic.
Definition at line 205 of file G4HadronElastic.cc.
View newest version in sPHENIX GitHub at line 205 of file G4HadronElastic.cc
References A(), kdfinder::abs(), bb, G4Exp(), G4Log(), G4UniformRand, G4Pow::GetInstance(), G4ParticleDefinition::GetPDGEncoding(), GeV, GeV2, CLHEP::MeV, pdg, pLocalTmax, G4Pow::powZ(), s1, G4Pow::Z13(), and G4Pow::Z23().
Referenced by ApplyYourself(), G4LowEHadronElastic::SampleInvariantT(), G4ChipsElasticModel::SampleInvariantT(), and G4ElasticHadrNucleusHE::SampleInvariantT().
void G4HadronElastic::SetLowestEnergyLimit (G4double value) inline
Definition at line 90 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 90 of file G4HadronElastic.hh
References lowestEnergyLimit.
Referenced by G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel(), and G4NeutronElectronElModel::G4NeutronElectronElModel().
Member Data Documentation
G4double G4HadronElastic::lowestEnergyLimit private
Definition at line 86 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 86 of file G4HadronElastic.hh
Referenced by ApplyYourself(), G4HadronElastic(), LowestEnergyLimit(), and SetLowestEnergyLimit().
G4int G4HadronElastic::nwarn private
Definition at line 87 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 87 of file G4HadronElastic.hh
Referenced by ApplyYourself(), and G4HadronElastic().
G4double G4HadronElastic::pLocalTmax protected
Definition at line 77 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HadronElastic.hh
Referenced by ApplyYourself(), G4HadronElastic(), G4LowEHadronElastic::SampleInvariantT(), SampleInvariantT(), and G4ElasticHadrNucleusHE::SampleInvariantT().
G4ParticleDefinition* G4HadronElastic::theAlpha private
Definition at line 84 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HadronElastic.hh
Referenced by ApplyYourself(), and G4HadronElastic().
G4ParticleDefinition* G4HadronElastic::theDeuteron private
Definition at line 83 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 83 of file G4HadronElastic.hh
Referenced by ApplyYourself(), and G4HadronElastic().
G4ParticleDefinition* G4HadronElastic::theNeutron private
Definition at line 82 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 82 of file G4HadronElastic.hh
Referenced by G4HadronElastic().
G4ParticleDefinition* G4HadronElastic::theProton private
Definition at line 81 of file G4HadronElastic.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HadronElastic.hh
Referenced by ApplyYourself(), and G4HadronElastic().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4HadronElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4HadronElastic.cc