ECCE @ EIC Software: CCalMaterial Class Reference
CCalMaterial Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalMaterial.hh>
Public Types
enum FractionType { FTWeight, FTVolume }
Public Member Functions
CCalMaterial (G4String mat, G4double dens, G4int nelem, CCalMaterial **constituents, G4double *weights, FractionType=FTWeight)
CCalMaterial (const CCalMaterial &)
virtual ~CCalMaterial ()
G4String Name () const
G4double Density () const
G4int NElements () const
G4String Element (G4int i) const
G4double Weight (G4int i) const
G4bool operator== (const CCalMaterial &) const
G4bool operator!= (const CCalMaterial &) const
CCalMaterial & operator= (const CCalMaterial &)
Protected Member Functions
CCalMaterial ()
void computeDensity (int nconst, CCalMaterial **constituents, double *weights, FractionType ft)
void closeMaterial ()
Protected Attributes
G4String name
G4double density
G4int nElem
G4String * theElements
G4double * theWeights
Friends
std::ostream & operator<< (std::ostream &, const CCalMaterial &)
Detailed Description
Definition at line 36 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 36 of file CCalMaterial.hh
Member Enumeration Documentation
enum CCalMaterial::FractionType
Enumerator:
FTWeight
FTVolume
Definition at line 42 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 42 of file CCalMaterial.hh
Constructor & Destructor Documentation
CCalMaterial::CCalMaterial (G4String mat, G4double dens, G4int nelem, CCalMaterial ** constituents, G4double * weights, FractionType ft = FTWeight)
Definition at line 35 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 35 of file CCalMaterial.cc
References closeMaterial(), computeDensity(), Density(), density, Element(), FTWeight, nElem, NElements(), theElements, theWeights, and Weight().
CCalMaterial::CCalMaterial (const CCalMaterial & mat)
Definition at line 67 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 67 of file CCalMaterial.cc
References nElem, theElements, and theWeights.
CCalMaterial::~CCalMaterial () virtual
Definition at line 77 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 77 of file CCalMaterial.cc
References theElements, and theWeights.
CCalMaterial::CCalMaterial () inline protected
Definition at line 64 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 64 of file CCalMaterial.hh
Member Function Documentation
void CCalMaterial::closeMaterial () protected
Definition at line 129 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 129 of file CCalMaterial.cc
References G4cout, G4endl, nElem, norm, theElements, and theWeights.
Referenced by CCalAMaterial::CCalAMaterial(), and CCalMaterial().
void CCalMaterial::computeDensity (int nconst, CCalMaterial ** constituents, double * weights, FractionType ft) protected
Definition at line 84 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 84 of file CCalMaterial.cc
References Density(), density, FTWeight, mass, and Acts::Test::volume.
Referenced by CCalAMaterial::CCalAMaterial(), and CCalMaterial().
G4double CCalMaterial::Density () const inline
Definition at line 53 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 53 of file CCalMaterial.hh
References density.
Referenced by CCalMaterial(), computeDensity(), and CCalMaterialFactory::findMaterial().
G4String CCalMaterial::Element (G4int i) const inline
Definition at line 55 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 55 of file CCalMaterial.hh
References theElements.
Referenced by CCalAMaterial::CCalAMaterial(), CCalMaterial(), and CCalMaterialFactory::findMaterial().
G4String CCalMaterial::Name () const inline
Definition at line 52 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 52 of file CCalMaterial.hh
References name.
Referenced by CCalMaterialFactory::findMaterial().
G4int CCalMaterial::NElements () const inline
Definition at line 54 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 54 of file CCalMaterial.hh
References nElem.
Referenced by CCalAMaterial::CCalAMaterial(), CCalMaterial(), and CCalMaterialFactory::findMaterial().
G4bool CCalMaterial::operator!= (const CCalMaterial & mat) const
Definition at line 125 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 125 of file CCalMaterial.cc
References name.
CCalMaterial & CCalMaterial::operator= (const CCalMaterial & mat)
Definition at line 102 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 102 of file CCalMaterial.cc
References density, name, nElem, theElements, and theWeights.
G4bool CCalMaterial::operator== (const CCalMaterial & mat) const
Definition at line 121 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 121 of file CCalMaterial.cc
References name.
G4double CCalMaterial::Weight (G4int i) const inline
Definition at line 56 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 56 of file CCalMaterial.hh
References theWeights.
Referenced by CCalAMaterial::CCalAMaterial(), CCalMaterial(), and CCalMaterialFactory::findMaterial().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCalMaterial & mat) friend
Definition at line 177 of file CCalMaterial.cc.
View newest version in sPHENIX GitHub at line 177 of file CCalMaterial.cc
Member Data Documentation
G4double CCalMaterial::density protected
Definition at line 72 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 72 of file CCalMaterial.hh
Referenced by CCalAMaterial::CCalAMaterial(), CCalMaterial(), computeDensity(), Density(), operator<<(), CCalAMaterial::operator=(), and operator=().
G4String CCalMaterial::name protected
Definition at line 71 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 71 of file CCalMaterial.hh
Referenced by CCalAMaterial::CCalAMaterial(), Name(), operator!=(), operator<<(), CCalAMaterial::operator=(), operator=(), and operator==().
G4int CCalMaterial::nElem protected
Definition at line 73 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 73 of file CCalMaterial.hh
Referenced by CCalAMaterial::CCalAMaterial(), CCalMaterial(), closeMaterial(), NElements(), operator<<(), CCalAMaterial::operator=(), and operator=().
G4String* CCalMaterial::theElements protected
Definition at line 74 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 74 of file CCalMaterial.hh
Referenced by CCalAMaterial::CCalAMaterial(), CCalMaterial(), closeMaterial(), Element(), operator<<(), CCalAMaterial::operator=(), operator=(), and ~CCalMaterial().
G4double* CCalMaterial::theWeights protected
Definition at line 75 of file CCalMaterial.hh.
View newest version in sPHENIX GitHub at line 75 of file CCalMaterial.hh
Referenced by CCalAMaterial::CCalAMaterial(), CCalMaterial(), closeMaterial(), operator<<(), CCalAMaterial::operator=(), operator=(), Weight(), and ~CCalMaterial().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalMaterial.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalMaterial.cc