ECCE @ EIC Software: G4ComponentGGNuclNuclXsc Class Reference
G4ComponentGGNuclNuclXsc Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ComponentGGNuclNuclXsc.hh>
Public Member Functions
G4ComponentGGNuclNuclXsc ()
virtual ~G4ComponentGGNuclNuclXsc ()
G4double GetTotalElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double A) final
G4double GetTotalIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A) final
G4double GetInelasticElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double A) final
G4double GetInelasticIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A) final
G4double GetElasticElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double A) final
G4double GetElasticIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A) final
G4double ComputeQuasiElasticRatio (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A) final
void BuildPhysicsTable (const G4ParticleDefinition &) final
void DumpPhysicsTable (const G4ParticleDefinition &) final
void Description (std::ostream &) const final
G4double GetZandACrossSection (const G4DynamicParticle *, G4int Z, G4int A)
G4double GetCoulombBarier (const G4DynamicParticle *, G4double Z, G4double A, G4double pR, G4double tR)
G4double ComputeCoulombBarier (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A, G4double pR, G4double tR)
G4double GetRatioSD (const G4DynamicParticle *, G4double At, G4double Zt)
G4double GetRatioQE (const G4DynamicParticle *, G4double At, G4double Zt)
G4double GetElasticGlauberGribov (const G4DynamicParticle *, G4int Z, G4int A)
G4double GetInelasticGlauberGribov (const G4DynamicParticle *, G4int Z, G4int A)
G4double GetTotalGlauberGribovXsc () const
G4double GetElasticGlauberGribovXsc () const
G4double GetInelasticGlauberGribovXsc () const
G4double GetProductionGlauberGribovXsc () const
G4double GetDiffractionGlauberGribovXsc () const
Public Member Functions inherited from G4VComponentCrossSection
G4VComponentCrossSection (const G4String &nam="")
virtual ~G4VComponentCrossSection ()
G4double GetTotalElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
G4double GetInelasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
G4double GetElasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
const G4String & GetName () const
Private Member Functions
void ComputeCrossSections (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A)
Private Attributes
G4double fTotalXsc
G4double fElasticXsc
G4double fInelasticXsc
G4double fProductionXsc
G4double fDiffractionXsc
G4double fEnergy
const G4ParticleDefinition * theProton
const G4ParticleDefinition * theNeutron
G4ComponentGGHadronNucleusXsc * fHadrNucl
G4HadronNucleonXsc * fHNXsc
const G4ParticleDefinition * fParticle
G4int fZ
G4int fA
Detailed Description
Definition at line 52 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ComponentGGNuclNuclXsc.hh
Constructor & Destructor Documentation
G4ComponentGGNuclNuclXsc::G4ComponentGGNuclNuclXsc ()
Definition at line 43 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ComponentGGNuclNuclXsc.cc
References fHadrNucl, fHNXsc, G4Neutron::Neutron(), G4Proton::Proton(), theNeutron, and theProton.
G4ComponentGGNuclNuclXsc::~G4ComponentGGNuclNuclXsc () virtual
Definition at line 54 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ComponentGGNuclNuclXsc.cc
References fHNXsc.
Member Function Documentation
void G4ComponentGGNuclNuclXsc::BuildPhysicsTable (const G4ParticleDefinition &) final virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 132 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 132 of file G4ComponentGGNuclNuclXsc.cc
G4double G4ComponentGGNuclNuclXsc::ComputeCoulombBarier (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A, G4double pR, G4double tR)
Definition at line 238 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 238 of file G4ComponentGGNuclNuclXsc.cc
References CLHEP::fine_structure_const, G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), CLHEP::hbarc, inve, and ratio.
Referenced by ComputeCrossSections(), and GetCoulombBarier().
void G4ComponentGGNuclNuclXsc::ComputeCrossSections (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A) private
Definition at line 161 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 161 of file G4ComponentGGNuclNuclXsc.cc
References A(), ComputeCoulombBarier(), G4ComponentGGHadronNucleusXsc::ComputeCrossSections(), e, fA, fDiffractionXsc, fElasticXsc, fEnergy, fHadrNucl, fHNXsc, fInelasticXsc, fParticle, fProductionXsc, fTotalXsc, fZ, G4Log(), G4lrint(), G4ParticleDefinition::GetBaryonNumber(), G4ComponentGGHadronNucleusXsc::GetDiffractionGlauberGribovXsc(), G4ComponentGGHadronNucleusXsc::GetElasticGlauberGribovXsc(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribovXsc(), G4HadronNucleonXsc::GetInelasticHadronNucleonXsc(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4ComponentGGHadronNucleusXsc::GetProductionGlauberGribovXsc(), G4ComponentGGHadronNucleusXsc::GetTotalGlauberGribovXsc(), G4HadronNucleonXsc::HadronNucleonXscNS(), inve, max, min, CLHEP::pi, CLHEP::proton_mass_c2, G4NuclearRadii::Radius(), ratio, theNeutron, theProton, and Z.
Referenced by ComputeQuasiElasticRatio(), GetElasticElementCrossSection(), GetElasticGlauberGribov(), GetElasticIsotopeCrossSection(), GetInelasticElementCrossSection(), GetInelasticGlauberGribov(), GetInelasticIsotopeCrossSection(), GetRatioQE(), GetRatioSD(), GetTotalElementCrossSection(), GetTotalIsotopeCrossSection(), and GetZandACrossSection().
G4double G4ComponentGGNuclNuclXsc::ComputeQuasiElasticRatio (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A) final virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 121 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), fInelasticXsc, and fProductionXsc.
void G4ComponentGGNuclNuclXsc::Description (std::ostream & outFile) const final virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 144 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 144 of file G4ComponentGGNuclNuclXsc.cc
void G4ComponentGGNuclNuclXsc::DumpPhysicsTable (const G4ParticleDefinition &) final virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 137 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 137 of file G4ComponentGGNuclNuclXsc.cc
References G4cout, and G4endl.
G4double G4ComponentGGNuclNuclXsc::GetCoulombBarier (const G4DynamicParticle * dp, G4double Z, G4double A, G4double pR, G4double tR) inline
Definition at line 178 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 178 of file G4ComponentGGNuclNuclXsc.hh
References ComputeCoulombBarier(), G4lrint(), G4DynamicParticle::GetDefinition(), and G4DynamicParticle::GetKineticEnergy().
G4double G4ComponentGGNuclNuclXsc::GetDiffractionGlauberGribovXsc () const inline
Definition at line 119 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ComponentGGNuclNuclXsc.hh
References fDiffractionXsc.
G4double G4ComponentGGNuclNuclXsc::GetElasticElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double A) final virtual
Implements G4VComponentCrossSection.
Definition at line 101 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), fElasticXsc, and G4lrint().
G4double G4ComponentGGNuclNuclXsc::GetElasticGlauberGribov (const G4DynamicParticle * dp, G4int Z, G4int A) inline
Definition at line 144 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ComponentGGNuclNuclXsc.hh
References A(), ComputeCrossSections(), fElasticXsc, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and Z.
G4double G4ComponentGGNuclNuclXsc::GetElasticGlauberGribovXsc () const inline
Definition at line 116 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ComponentGGNuclNuclXsc.hh
References fElasticXsc.
G4double G4ComponentGGNuclNuclXsc::GetElasticIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A) final virtual
Implements G4VComponentCrossSection.
Definition at line 111 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 111 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), and fElasticXsc.
G4double G4ComponentGGNuclNuclXsc::GetInelasticElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double A) final virtual
Implements G4VComponentCrossSection.
Definition at line 81 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 81 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), fInelasticXsc, and G4lrint().
Referenced by G4ParticleInelasticXS::GetElementCrossSection(), G4ParticleInelasticXS::Initialise(), and G4ParticleInelasticXS::IsoCrossSection().
G4double G4ComponentGGNuclNuclXsc::GetInelasticGlauberGribov (const G4DynamicParticle * dp, G4int Z, G4int A) inline
Definition at line 152 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ComponentGGNuclNuclXsc.hh
References A(), ComputeCrossSections(), fInelasticXsc, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and Z.
G4double G4ComponentGGNuclNuclXsc::GetInelasticGlauberGribovXsc () const inline
Definition at line 117 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ComponentGGNuclNuclXsc.hh
References fInelasticXsc.
G4double G4ComponentGGNuclNuclXsc::GetInelasticIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A) final virtual
Implements G4VComponentCrossSection.
Definition at line 91 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 91 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), and fInelasticXsc.
G4double G4ComponentGGNuclNuclXsc::GetProductionGlauberGribovXsc () const inline
Definition at line 118 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ComponentGGNuclNuclXsc.hh
References fProductionXsc.
G4double G4ComponentGGNuclNuclXsc::GetRatioQE (const G4DynamicParticle * aParticle, G4double At, G4double Zt)
Definition at line 279 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 279 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), fInelasticXsc, fProductionXsc, G4lrint(), G4DynamicParticle::GetDefinition(), and G4DynamicParticle::GetKineticEnergy().
G4double G4ComponentGGNuclNuclXsc::GetRatioSD (const G4DynamicParticle * aParticle, G4double At, G4double Zt)
Definition at line 265 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 265 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), fDiffractionXsc, fInelasticXsc, G4lrint(), G4DynamicParticle::GetDefinition(), and G4DynamicParticle::GetKineticEnergy().
G4double G4ComponentGGNuclNuclXsc::GetTotalElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double A) final virtual
Implements G4VComponentCrossSection.
Definition at line 61 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), fTotalXsc, and G4lrint().
G4double G4ComponentGGNuclNuclXsc::GetTotalGlauberGribovXsc () const inline
Definition at line 115 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ComponentGGNuclNuclXsc.hh
References fTotalXsc.
G4double G4ComponentGGNuclNuclXsc::GetTotalIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A) final virtual
Implements G4VComponentCrossSection.
Definition at line 71 of file G4ComponentGGNuclNuclXsc.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ComponentGGNuclNuclXsc.cc
References ComputeCrossSections(), and fTotalXsc.
G4double G4ComponentGGNuclNuclXsc::GetZandACrossSection (const G4DynamicParticle * dp, G4int Z, G4int A) inline
Definition at line 170 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 170 of file G4ComponentGGNuclNuclXsc.hh
References A(), ComputeCrossSections(), fInelasticXsc, G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), and Z.
Member Data Documentation
G4int G4ComponentGGNuclNuclXsc::fA private
Definition at line 140 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections().
G4double G4ComponentGGNuclNuclXsc::fDiffractionXsc private
Definition at line 128 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), GetDiffractionGlauberGribovXsc(), and GetRatioSD().
G4double G4ComponentGGNuclNuclXsc::fElasticXsc private
Definition at line 127 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), GetElasticElementCrossSection(), GetElasticGlauberGribov(), GetElasticGlauberGribovXsc(), and GetElasticIsotopeCrossSection().
G4double G4ComponentGGNuclNuclXsc::fEnergy private
Definition at line 130 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections().
G4ComponentGGHadronNucleusXsc* G4ComponentGGNuclNuclXsc::fHadrNucl private
Definition at line 135 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), and G4ComponentGGNuclNuclXsc().
G4HadronNucleonXsc* G4ComponentGGNuclNuclXsc::fHNXsc private
Definition at line 136 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 136 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), G4ComponentGGNuclNuclXsc(), and ~G4ComponentGGNuclNuclXsc().
G4double G4ComponentGGNuclNuclXsc::fInelasticXsc private
Definition at line 127 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), ComputeQuasiElasticRatio(), GetInelasticElementCrossSection(), GetInelasticGlauberGribov(), GetInelasticGlauberGribovXsc(), GetInelasticIsotopeCrossSection(), GetRatioQE(), GetRatioSD(), and GetZandACrossSection().
const G4ParticleDefinition* G4ComponentGGNuclNuclXsc::fParticle private
Definition at line 139 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections().
G4double G4ComponentGGNuclNuclXsc::fProductionXsc private
Definition at line 128 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), ComputeQuasiElasticRatio(), GetProductionGlauberGribovXsc(), and GetRatioQE().
G4double G4ComponentGGNuclNuclXsc::fTotalXsc private
Definition at line 127 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), GetTotalElementCrossSection(), GetTotalGlauberGribovXsc(), and GetTotalIsotopeCrossSection().
G4int G4ComponentGGNuclNuclXsc::fZ private
Definition at line 140 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections().
const G4ParticleDefinition* G4ComponentGGNuclNuclXsc::theNeutron private
Definition at line 133 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), and G4ComponentGGNuclNuclXsc().
const G4ParticleDefinition* G4ComponentGGNuclNuclXsc::theProton private
Definition at line 132 of file G4ComponentGGNuclNuclXsc.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ComponentGGNuclNuclXsc.hh
Referenced by ComputeCrossSections(), and G4ComponentGGNuclNuclXsc().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ComponentGGNuclNuclXsc.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ComponentGGNuclNuclXsc.cc