ECCE @ EIC Software: GB07BOptrLeadingParticle Class Reference
GB07BOptrLeadingParticle Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB07/include/GB07BOptrLeadingParticle.hh>
Public Member Functions
GB07BOptrLeadingParticle (G4String operatorName="LeadingParticleBiasingOperator")
virtual ~GB07BOptrLeadingParticle ()
virtual void StartRun () final
virtual void StartTracking (const G4Track *track) final
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
virtual void Configure ()
virtual void ConfigureForWorker ()
virtual void EndTracking ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *, const G4BiasingProcessInterface *) final
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *, const G4BiasingProcessInterface *) final
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final
Private Attributes
G4BOptnLeadingParticle * fLeadingParticleBiasingOperation
const G4VProcess * fAnnihilation
const G4VProcess * fConversion
const G4VProcess * fDecay
const G4VProcess * fTwoParticleProcess
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Protected Member Functions inherited from G4VBiasingOperator
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
virtual void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
virtual void ExitBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
Detailed Description
Definition at line 38 of file GB07BOptrLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 38 of file GB07BOptrLeadingParticle.hh
Constructor & Destructor Documentation
GB07BOptrLeadingParticle::GB07BOptrLeadingParticle (G4String operatorName = "LeadingParticleBiasingOperator")
Definition at line 43 of file GB07BOptrLeadingParticle.cc.
View newest version in sPHENIX GitHub at line 43 of file GB07BOptrLeadingParticle.cc
References fLeadingParticleBiasingOperation.
GB07BOptrLeadingParticle::~GB07BOptrLeadingParticle () virtual
Definition at line 56 of file GB07BOptrLeadingParticle.cc.
View newest version in sPHENIX GitHub at line 56 of file GB07BOptrLeadingParticle.cc
References fLeadingParticleBiasingOperation.
Member Function Documentation
G4VBiasingOperation * GB07BOptrLeadingParticle::ProposeFinalStateBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final private virtual
Implements G4VBiasingOperator.
Definition at line 65 of file GB07BOptrLeadingParticle.cc.
View newest version in sPHENIX GitHub at line 65 of file GB07BOptrLeadingParticle.cc
References fLeadingParticleBiasingOperation, fTwoParticleProcess, and G4BOptnLeadingParticle::SetFurtherKillingProbability().
virtual G4VBiasingOperation* GB07BOptrLeadingParticle::ProposeNonPhysicsBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline final private virtual
Implements G4VBiasingOperator.
Definition at line 49 of file GB07BOptrLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 49 of file GB07BOptrLeadingParticle.hh
virtual G4VBiasingOperation* GB07BOptrLeadingParticle::ProposeOccurenceBiasingOperation (const G4Track * , const G4BiasingProcessInterface *) inline final private virtual
Implements G4VBiasingOperator.
Definition at line 54 of file GB07BOptrLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 54 of file GB07BOptrLeadingParticle.hh
void GB07BOptrLeadingParticle::StartRun () final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 99 of file GB07BOptrLeadingParticle.cc.
View newest version in sPHENIX GitHub at line 99 of file GB07BOptrLeadingParticle.cc
References G4PionZero::Definition(), G4Positron::Definition(), G4Gamma::Definition(), fAnnihilation, fConversion, fDecay, G4ProcessManager::GetProcessList(), and G4ParticleDefinition::GetProcessManager().
void GB07BOptrLeadingParticle::StartTracking (const G4Track * track) final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 144 of file GB07BOptrLeadingParticle.cc.
View newest version in sPHENIX GitHub at line 144 of file GB07BOptrLeadingParticle.cc
References G4PionZero::Definition(), G4Positron::Definition(), G4Gamma::Definition(), fAnnihilation, fConversion, fDecay, fTwoParticleProcess, and G4Track::GetDefinition().
Member Data Documentation
const G4VProcess* GB07BOptrLeadingParticle::fAnnihilation private
Definition at line 77 of file GB07BOptrLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 77 of file GB07BOptrLeadingParticle.hh
Referenced by StartRun(), and StartTracking().
const G4VProcess* GB07BOptrLeadingParticle::fConversion private
Definition at line 78 of file GB07BOptrLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 78 of file GB07BOptrLeadingParticle.hh
Referenced by StartRun(), and StartTracking().
const G4VProcess* GB07BOptrLeadingParticle::fDecay private
Definition at line 79 of file GB07BOptrLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 79 of file GB07BOptrLeadingParticle.hh
Referenced by StartRun(), and StartTracking().
G4BOptnLeadingParticle* GB07BOptrLeadingParticle::fLeadingParticleBiasingOperation private
Definition at line 73 of file GB07BOptrLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 73 of file GB07BOptrLeadingParticle.hh
Referenced by GB07BOptrLeadingParticle(), ProposeFinalStateBiasingOperation(), and ~GB07BOptrLeadingParticle().
const G4VProcess* GB07BOptrLeadingParticle::fTwoParticleProcess private
Definition at line 80 of file GB07BOptrLeadingParticle.hh.
View newest version in sPHENIX GitHub at line 80 of file GB07BOptrLeadingParticle.hh
Referenced by ProposeFinalStateBiasingOperation(), and StartTracking().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB07/include/GB07BOptrLeadingParticle.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB07/src/GB07BOptrLeadingParticle.cc