ECCE @ EIC Software: XrayTelRunAction Class Reference
XrayTelRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/include/XrayTelRunAction.hh>
Public Member Functions
XrayTelRunAction ()
~XrayTelRunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 65 of file XrayTelRunAction.hh.
View newest version in sPHENIX GitHub at line 65 of file XrayTelRunAction.hh
Constructor & Destructor Documentation
XrayTelRunAction::XrayTelRunAction ()
Definition at line 73 of file XrayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 73 of file XrayTelRunAction.cc
XrayTelRunAction::~XrayTelRunAction ()
Definition at line 77 of file XrayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 77 of file XrayTelRunAction.cc
Member Function Documentation
void XrayTelRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 81 of file XrayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 81 of file XrayTelRunAction.cc
References static_analysis_results::analysis(), G4UImanager::ApplyCommand(), XrayTelAnalysis::book(), G4cout, G4endl, G4VVisManager::GetConcreteInstance(), XrayTelAnalysis::getInstance(), G4Run::GetRunID(), G4UImanager::GetUIpointer(), and G4UserRunAction::IsMaster().
void XrayTelRunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 99 of file XrayTelRunAction.cc.
View newest version in sPHENIX GitHub at line 99 of file XrayTelRunAction.cc
References static_analysis_results::analysis(), G4UImanager::ApplyCommand(), XrayTelAnalysis::finish(), G4VVisManager::GetConcreteInstance(), XrayTelAnalysis::getInstance(), G4UImanager::GetUIpointer(), and G4UserRunAction::IsMaster().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/include/XrayTelRunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_telescope/src/XrayTelRunAction.cc