ECCE @ EIC Software: G4VParticleHPEnergyAngular Class Reference
G4VParticleHPEnergyAngular Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4VParticleHPEnergyAngular.hh>
Classes
struct toBeCached
Public Member Functions
G4VParticleHPEnergyAngular ()
virtual ~G4VParticleHPEnergyAngular ()
virtual void Init (std::istream &aDataFile)=0
virtual G4ReactionProduct * Sample (G4double anEnergy, G4double massCode, G4double mass)=0
virtual G4double MeanEnergyOfThisInteraction ()=0
void SetProjectileRP (G4ReactionProduct *aIncidentParticleRP)
void SetTarget (G4ReactionProduct *aTarget)
G4ReactionProduct * GetTarget ()
G4ReactionProduct * GetProjectileRP ()
G4ReactionProduct * GetCMS ()
void SetQValue (G4double aValue)
virtual void ClearHistories ()
Protected Member Functions
G4double GetQValue ()
Private Attributes
G4double theQValue
G4Cache< toBeCached > fCache
Detailed Description
Definition at line 41 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 41 of file G4VParticleHPEnergyAngular.hh
Constructor & Destructor Documentation
G4VParticleHPEnergyAngular::G4VParticleHPEnergyAngular () inline
Definition at line 54 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VParticleHPEnergyAngular.hh
References fCache, G4Cache< VALTYPE >::Put(), and theQValue.
virtual G4VParticleHPEnergyAngular::~G4VParticleHPEnergyAngular () inline virtual
Definition at line 61 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VParticleHPEnergyAngular.hh
Member Function Documentation
virtual void G4VParticleHPEnergyAngular::ClearHistories () inline virtual
Reimplemented in G4ParticleHPContEnergyAngular.
Definition at line 106 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 106 of file G4VParticleHPEnergyAngular.hh
Referenced by G4ParticleHPProduct::Sample().
G4ReactionProduct* G4VParticleHPEnergyAngular::GetCMS () inline
Definition at line 94 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 94 of file G4VParticleHPEnergyAngular.hh
References fCache, and G4Cache< VALTYPE >::Get().
G4ReactionProduct* G4VParticleHPEnergyAngular::GetProjectileRP () inline
Definition at line 89 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VParticleHPEnergyAngular.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPNBodyPhaseSpace::GetEmax(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), and G4ParticleHPContEnergyAngular::Sample().
G4double G4VParticleHPEnergyAngular::GetQValue () inline protected
Definition at line 112 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VParticleHPEnergyAngular.hh
References theQValue.
Referenced by G4ParticleHPNBodyPhaseSpace::GetEmax(), G4ParticleHPIsotropic::Sample(), and G4ParticleHPDiscreteTwoBody::Sample().
G4ReactionProduct* G4VParticleHPEnergyAngular::GetTarget (void) inline
Definition at line 84 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VParticleHPEnergyAngular.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPNBodyPhaseSpace::GetEmax(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), and G4ParticleHPContEnergyAngular::Sample().
virtual void G4VParticleHPEnergyAngular::Init (std::istream & aDataFile) pure virtual
Implemented in G4ParticleHPContEnergyAngular, G4ParticleHPLabAngularEnergy, G4ParticleHPNBodyPhaseSpace, G4ParticleHPDiscreteTwoBody, and G4ParticleHPIsotropic.
Referenced by G4ParticleHPProduct::Init().
virtual G4double G4VParticleHPEnergyAngular::MeanEnergyOfThisInteraction () pure virtual
Implemented in G4ParticleHPNBodyPhaseSpace, G4ParticleHPContEnergyAngular, G4ParticleHPDiscreteTwoBody, G4ParticleHPLabAngularEnergy, and G4ParticleHPIsotropic.
Referenced by G4ParticleHPProduct::MeanEnergyOfThisInteraction().
virtual G4ReactionProduct* G4VParticleHPEnergyAngular::Sample (G4double anEnergy, G4double massCode, G4double mass) pure virtual
Implemented in G4ParticleHPContEnergyAngular, G4ParticleHPDiscreteTwoBody, G4ParticleHPLabAngularEnergy, G4ParticleHPNBodyPhaseSpace, and G4ParticleHPIsotropic.
Referenced by G4ParticleHPProduct::Sample().
void G4VParticleHPEnergyAngular::SetProjectileRP (G4ReactionProduct * aIncidentParticleRP) inline
Definition at line 74 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VParticleHPEnergyAngular.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPProduct::Sample().
void G4VParticleHPEnergyAngular::SetQValue (G4double aValue) inline
Definition at line 101 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 101 of file G4VParticleHPEnergyAngular.hh
References theQValue.
Referenced by G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPProduct::Init().
void G4VParticleHPEnergyAngular::SetTarget (G4ReactionProduct * aTarget) inline
Definition at line 79 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VParticleHPEnergyAngular.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPProduct::Sample().
Member Data Documentation
G4Cache<toBeCached> G4VParticleHPEnergyAngular::fCache private
Definition at line 118 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 118 of file G4VParticleHPEnergyAngular.hh
Referenced by G4VParticleHPEnergyAngular(), GetCMS(), GetProjectileRP(), GetTarget(), SetProjectileRP(), and SetTarget().
G4double G4VParticleHPEnergyAngular::theQValue private
Definition at line 116 of file G4VParticleHPEnergyAngular.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VParticleHPEnergyAngular.hh
Referenced by G4VParticleHPEnergyAngular(), GetQValue(), and SetQValue().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4VParticleHPEnergyAngular.hh