ECCE @ EIC Software: CCaloSD Class Reference
CCaloSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCaloSD.hh>
Public Member Functions
CCaloSD (G4String aSDname, CCalVOrganization *numberingScheme)
virtual ~CCaloSD ()
void Initialize (G4HCofThisEvent *HCE)
G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
void EndOfEvent (G4HCofThisEvent *HCE)
void clear ()
void DrawAll ()
void PrintAll ()
void SetPrimaryID (G4int i)
G4int GetPrimaryID ()
void SetOrganization (CCalVOrganization *org)
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Member Functions
G4ThreeVector SetToLocal (const G4ThreeVector &globalPoint) const
void getStepInfo (const G4Step *aStep)
G4bool hitExists ()
void createNewHit ()
void updateHit ()
void StoreHit (CCalG4Hit *ahit)
void ResetForNewPrimary ()
void summarize ()
G4double curve_LY (const G4StepPoint *stepPoint)
Private Attributes
G4ThreeVector EntrancePoint
G4float IncidentEnergy
G4int PrimID
G4int HCID
G4String SDname
CCalG4HitCollection * theHC
G4int TSID
CCalG4Hit * CurrentHit
const G4Track * theTrack
G4VPhysicalVolume * CurrentPV
G4VPhysicalVolume * PreviousPV
unsigned int UnitID
unsigned int PreviousUnitID
G4int PrimaryID
G4int TSliceID
G4double TSlice
const G4StepPoint * PreStepPoint
const G4StepPoint * PostStepPoint
G4float EdepositEM
G4float EdepositEHAD
G4ThreeVector HitPoint
CCalVOrganization * theDescription
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 59 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 59 of file CCaloSD.hh
Constructor & Destructor Documentation
CCaloSD::CCaloSD (G4String aSDname, CCalVOrganization * numberingScheme)
Definition at line 42 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 42 of file CCaloSD.cc
References CCalSDList::addCalo(), G4VSensitiveDetector::collectionName, G4cout, G4endl, CCalSDList::getInstance(), and G4CollectionNameVector::insert().
CCaloSD::~CCaloSD () virtual
Definition at line 59 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 59 of file CCaloSD.cc
References theDescription.
Member Function Documentation
void CCaloSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 263 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 263 of file CCaloSD.cc
void CCaloSD::createNewHit () private
Definition at line 182 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 182 of file CCaloSD.cc
References CurrentHit, CurrentPV, EntrancePoint, G4cout, G4endl, G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4TouchableHistory::GetHistoryDepth(), G4VPhysicalVolume::GetName(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4TouchableHistory::GetReplicaNumber(), G4Track::GetTotalEnergy(), G4Track::GetTouchable(), G4Track::GetTrackID(), IncidentEnergy, PrimaryID, CCalHit::setEntry(), CCalHit::setIncidentEnergy(), CCalHit::setTimeSlice(), CCalHit::setTrackID(), CCalHit::setUnitID(), StoreHit(), theTrack, TSlice, TSliceID, UnitID, and updateHit().
Referenced by ProcessHits().
G4double CCaloSD::curve_LY (const G4StepPoint * stepPoint) private
Definition at line 281 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 281 of file CCaloSD.cc
References G4cout, G4endl, G4StepPoint::GetPosition(), SetToLocal(), weight, and CLHEP::Hep3Vector::z().
Referenced by getStepInfo().
void CCaloSD::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 266 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 266 of file CCaloSD.cc
void CCaloSD::EndOfEvent (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 256 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 256 of file CCaloSD.cc
References summarize().
G4int CCaloSD::GetPrimaryID () inline
Definition at line 77 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 77 of file CCaloSD.hh
References PrimaryID.
void CCaloSD::getStepInfo (const G4Step * aStep) private
Definition at line 93 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 93 of file CCaloSD.cc
References CurrentPV, curve_LY(), EdepositEHAD, EdepositEM, G4Track::GetDefinition(), G4StepPoint::GetGlobalTime(), G4VPhysicalVolume::GetName(), G4ParticleDefinition::GetParticleName(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4Step::GetTrack(), CCalVOrganization::GetUnitID(), G4VTouchable::GetVolume(), HitPoint, it, min, nanosecond, pname(), PostStepPoint, PreStepPoint, theDescription, theTrack, TSlice, TSliceID, UnitID, and weight.
Referenced by ProcessHits().
G4bool CCaloSD::hitExists () private
Definition at line 130 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 130 of file CCaloSD.cc
References CurrentHit, CurrentPV, G4THitsCollection< T >::entries(), CCalHit::getTimeSliceID(), CCalHit::getTrackID(), CCalHit::getUnitID(), PreviousPV, PreviousUnitID, PrimaryID, PrimID, ResetForNewPrimary(), theHC, TSID, TSliceID, UnitID, and updateHit().
Referenced by ProcessHits().
void CCaloSD::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 63 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 63 of file CCaloSD.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, G4cout, G4endl, G4SDManager::GetCollectionID(), G4SDManager::GetSDMpointer(), HCID, PrimID, SDname, theHC, and TSID.
void CCaloSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 269 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 269 of file CCaloSD.cc
References G4cout, G4endl, G4VHitsCollection::GetName(), G4THitsCollection< T >::PrintAllHits(), and theHC.
G4bool CCaloSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) virtual
Implements G4VSensitiveDetector.
Definition at line 82 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 82 of file CCaloSD.cc
References createNewHit(), EdepositEHAD, EdepositEM, CLHEP::eV, f, getStepInfo(), G4Step::GetTotalEnergyDeposit(), and hitExists().
void CCaloSD::ResetForNewPrimary () private
Definition at line 164 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 164 of file CCaloSD.cc
References EntrancePoint, G4StepPoint::GetKineticEnergy(), HitPoint, IncidentEnergy, PreStepPoint, and SetToLocal().
Referenced by hitExists().
void CCaloSD::SetOrganization (CCalVOrganization * org)
Definition at line 274 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 274 of file CCaloSD.cc
References theDescription.
void CCaloSD::SetPrimaryID (G4int i) inline
Definition at line 76 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 76 of file CCaloSD.hh
References PrimaryID.
Referenced by CCalStackingAction::initialize(), and CCalStackingAction::setPrimaryID().
G4ThreeVector CCaloSD::SetToLocal (const G4ThreeVector & globalPoint) const private
Definition at line 247 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 247 of file CCaloSD.cc
References G4VTouchable::GetHistory(), G4NavigationHistory::GetTopTransform(), G4StepPoint::GetTouchable(), PreStepPoint, and G4AffineTransform::TransformPoint().
Referenced by curve_LY(), and ResetForNewPrimary().
void CCaloSD::StoreHit (CCalG4Hit * ahit) private
Definition at line 171 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 171 of file CCaloSD.cc
References G4cout, G4endl, G4THitsCollection< T >::insert(), PrimID, and theHC.
Referenced by createNewHit().
void CCaloSD::summarize () private
Definition at line 260 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 260 of file CCaloSD.cc
Referenced by EndOfEvent().
void CCaloSD::updateHit () private
Definition at line 231 of file CCaloSD.cc.
View newest version in sPHENIX GitHub at line 231 of file CCaloSD.cc
References CCalG4Hit::addEnergyDeposit(), CurrentHit, CurrentPV, EdepositEHAD, EdepositEM, G4cout, G4endl, MeV, PreviousPV, PreviousUnitID, PrimaryID, PrimID, TSID, TSliceID, and UnitID.
Referenced by createNewHit(), and hitExists().
Member Data Documentation
CCalG4Hit* CCaloSD::CurrentHit private
Definition at line 106 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 106 of file CCaloSD.hh
Referenced by createNewHit(), hitExists(), and updateHit().
G4VPhysicalVolume* CCaloSD::CurrentPV private
Definition at line 108 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 108 of file CCaloSD.hh
Referenced by createNewHit(), getStepInfo(), hitExists(), and updateHit().
G4float CCaloSD::EdepositEHAD private
Definition at line 116 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 116 of file CCaloSD.hh
Referenced by getStepInfo(), ProcessHits(), and updateHit().
G4float CCaloSD::EdepositEM private
Definition at line 116 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 116 of file CCaloSD.hh
Referenced by getStepInfo(), ProcessHits(), and updateHit().
G4ThreeVector CCaloSD::EntrancePoint private
Definition at line 97 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 97 of file CCaloSD.hh
Referenced by createNewHit(), and ResetForNewPrimary().
G4int CCaloSD::HCID private
Definition at line 101 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 101 of file CCaloSD.hh
Referenced by Initialize().
G4ThreeVector CCaloSD::HitPoint private
Definition at line 117 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 117 of file CCaloSD.hh
Referenced by getStepInfo(), and ResetForNewPrimary().
G4float CCaloSD::IncidentEnergy private
Definition at line 98 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 98 of file CCaloSD.hh
Referenced by createNewHit(), and ResetForNewPrimary().
const G4StepPoint* CCaloSD::PostStepPoint private
Definition at line 115 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 115 of file CCaloSD.hh
Referenced by getStepInfo().
const G4StepPoint* CCaloSD::PreStepPoint private
Definition at line 114 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 114 of file CCaloSD.hh
Referenced by getStepInfo(), ResetForNewPrimary(), and SetToLocal().
G4VPhysicalVolume* CCaloSD::PreviousPV private
Definition at line 109 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 109 of file CCaloSD.hh
Referenced by hitExists(), and updateHit().
unsigned int CCaloSD::PreviousUnitID private
Definition at line 110 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 110 of file CCaloSD.hh
Referenced by hitExists(), and updateHit().
G4int CCaloSD::PrimaryID private
Definition at line 111 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 111 of file CCaloSD.hh
Referenced by createNewHit(), GetPrimaryID(), hitExists(), SetPrimaryID(), and updateHit().
G4int CCaloSD::PrimID private
Definition at line 99 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 99 of file CCaloSD.hh
Referenced by hitExists(), Initialize(), StoreHit(), and updateHit().
G4String CCaloSD::SDname private
Definition at line 102 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 102 of file CCaloSD.hh
Referenced by Initialize().
CCalVOrganization* CCaloSD::theDescription private
Definition at line 119 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 119 of file CCaloSD.hh
Referenced by getStepInfo(), SetOrganization(), and ~CCaloSD().
CCalG4HitCollection* CCaloSD::theHC private
Definition at line 103 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 103 of file CCaloSD.hh
Referenced by hitExists(), Initialize(), PrintAll(), and StoreHit().
const G4Track* CCaloSD::theTrack private
Definition at line 107 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 107 of file CCaloSD.hh
Referenced by createNewHit(), and getStepInfo().
G4int CCaloSD::TSID private
Definition at line 105 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 105 of file CCaloSD.hh
Referenced by hitExists(), Initialize(), and updateHit().
G4double CCaloSD::TSlice private
Definition at line 112 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 112 of file CCaloSD.hh
Referenced by createNewHit(), and getStepInfo().
G4int CCaloSD::TSliceID private
Definition at line 111 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 111 of file CCaloSD.hh
Referenced by createNewHit(), getStepInfo(), hitExists(), and updateHit().
unsigned int CCaloSD::UnitID private
Definition at line 110 of file CCaloSD.hh.
View newest version in sPHENIX GitHub at line 110 of file CCaloSD.hh
Referenced by createNewHit(), getStepInfo(), hitExists(), and updateHit().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCaloSD.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCaloSD.cc