ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/PoPs_data.cc File Reference
PoPs_data.cc File Reference
#include <string.h>
#include "PoPs.h"
#include "PoPs_private.h"
#include "PoPs_data.h"
Functions
static double PoPs_getBDFLS_mass (char const *name, PoP *pop, double mass)
int PoPs_particleReadDatabase (statusMessageReporting *smr, char const *)
PoP * PoPs_particleCreateLoadInfo (statusMessageReporting *smr, const char *name)
int PoPs_particleLoadInfo (statusMessageReporting *smr, const char *name, PoP *pop)
int PoPs_setBDFLS_File (char const *name)
Variables
static void * BDFLS_Data = NULL
Function Documentation
static double PoPs_getBDFLS_mass (char const * name, PoP * pop, double mass) static
Definition at line 100 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 100 of file PoPs_data.cc
References BDFLS_Data, mass, and PoPs_genre_lepton.
Referenced by PoPs_particleLoadInfo().
PoP* PoPs_particleCreateLoadInfo (statusMessageReporting * smr, const char * name)
Definition at line 61 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 61 of file PoPs_data.cc
References PoP_free(), PoP_new(), and PoPs_particleLoadInfo().
Referenced by lPoPs_addParticleIfNeeded(), and PoPs_particleReadDatabase().
int PoPs_particleLoadInfo (statusMessageReporting * smr, const char * name, PoP * pop)
Definition at line 73 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 73 of file PoPs_data.cc
References PoP_s::A, PoP_s::genre, PoPDatas::genre, PoP_s::l, mass, PoP_s::mass, PoP_s::massUnit, n, N, PoPDatas::N, PoP_s::name, PoPDatas::nuclearLevel, PoPDatas, PoPs_getBDFLS_mass(), smr_allocateCopyString2, smr_freeMemory(), smr_setReportError2, smr_unknownID, unitsDB_addUnitIfNeeded(), PoP_s::Z, and PoPDatas::Z.
Referenced by PoPs_particleCreateLoadInfo().
int PoPs_particleReadDatabase (statusMessageReporting * smr, char const *)
Definition at line 36 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 36 of file PoPs_data.cc
References PoP_s::A, PoP_s::genre, lPoPs_addParticleIfNeeded(), n1, PoP_free(), PoPDatas, PoPs_addParticleIfNeeded(), PoPs_genre_atom, PoPs_particleCreateLoadInfo(), smr_isOk(), and PoP_s::Z.
Referenced by PoPs_readDatabase().
int PoPs_setBDFLS_File (char const * name)
Definition at line 121 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 121 of file PoPs_data.cc
References BDFLS_Data.
Variable Documentation
void* BDFLS_Data = NULL static
Definition at line 95 of file PoPs_data.cc.
View newest version in sPHENIX GitHub at line 95 of file PoPs_data.cc
Referenced by PoPs_getBDFLS_mass(), and PoPs_setBDFLS_File().