ECCE @ EIC Software: G4UIcmdWithAString Class Reference
G4UIcmdWithAString Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcmdWithAString.hh>
Public Member Functions
G4UIcmdWithAString (const char *theCommandPath, G4UImessenger *theMessenger)
void SetParameterName (const char *theName, G4bool omittable, G4bool currentAsDefault=false)
void SetCandidates (const char *candidateList)
void SetDefaultValue (const char *defVal)
Public Member Functions inherited from G4UIcommand
G4UIcommand ()
G4UIcommand (const char *theCommandPath, G4UImessenger *theMessenger, G4bool tBB=true)
virtual ~G4UIcommand ()
G4bool operator== (const G4UIcommand &right) const
G4bool operator!= (const G4UIcommand &right) const
virtual G4int DoIt (G4String parameterList)
G4String GetCurrentValue ()
void AvailableForStates (G4ApplicationState s1)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4, G4ApplicationState s5)
G4bool IsAvailable ()
virtual void List ()
void SetRange (const char *rs)
const G4String & GetRange () const
size_t GetGuidanceEntries () const
const G4String & GetGuidanceLine (G4int i) const
const G4String & GetCommandPath () const
const G4String & GetCommandName () const
size_t GetParameterEntries () const
G4UIparameter * GetParameter (G4int i) const
std::vector< G4ApplicationState > * GetStateList ()
G4UImessenger * GetMessenger () const
void SetParameter (G4UIparameter *const newParameter)
void SetGuidance (const char *aGuidance)
const G4String GetTitle () const
void SetToBeBroadcasted (G4bool val)
G4bool ToBeBroadcasted () const
void SetToBeFlushed (G4bool val)
G4bool ToBeFlushed () const
void SetWorkerThreadOnly (G4bool val=true)
G4bool IsWorkerThreadOnly () const
void CommandFailed (G4int errCode, G4ExceptionDescription &ed)
void CommandFailed (G4ExceptionDescription &ed)
G4int IfCommandFailed ()
G4String & GetFailureDescription ()
void ResetFailure ()
Additional Inherited Members
Static Public Member Functions inherited from G4UIcommand
static G4String ConvertToString (G4bool boolVal)
static G4String ConvertToString (G4int intValue)
static G4String ConvertToString (G4double doubleValue)
static G4String ConvertToString (G4double doubleValue, const char *unitName)
static G4String ConvertToString (G4ThreeVector vec)
static G4String ConvertToString (G4ThreeVector vec, const char *unitName)
static G4bool ConvertToBool (const char *st)
static G4int ConvertToInt (const char *st)
static G4double ConvertToDouble (const char *st)
static G4double ConvertToDimensionedDouble (const char *st)
static G4ThreeVector ConvertTo3Vector (const char *st)
static G4ThreeVector ConvertToDimensioned3Vector (const char *st)
static G4double ValueOf (const char *unitName)
static G4String CategoryOf (const char *unitName)
static G4String UnitsList (const char *unitCategory)
Protected Types inherited from G4UIcommand
using yystype = G4UItokenNum::yystype
using tokenNum = G4UItokenNum::tokenNum
Protected Member Functions inherited from G4UIcommand
G4int CheckNewValue (const char *newValue)
Protected Attributes inherited from G4UIcommand
G4bool toBeBroadcasted
G4bool toBeFlushed
G4bool workerThreadOnly
G4int commandFailureCode
G4String failureDescription
Detailed Description
Definition at line 41 of file G4UIcmdWithAString.hh.
View newest version in sPHENIX GitHub at line 41 of file G4UIcmdWithAString.hh
Constructor & Destructor Documentation
G4UIcmdWithAString::G4UIcmdWithAString (const char * theCommandPath, G4UImessenger * theMessenger)
Definition at line 33 of file G4UIcmdWithAString.cc.
View newest version in sPHENIX GitHub at line 33 of file G4UIcmdWithAString.cc
Member Function Documentation
void G4UIcmdWithAString::SetCandidates (const char * candidateList)
Definition at line 49 of file G4UIcmdWithAString.cc.
View newest version in sPHENIX GitHub at line 49 of file G4UIcmdWithAString.cc
References G4UIcommand::GetParameter(), and G4UIparameter::SetParameterCandidates().
Referenced by CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CexmcRunManagerMessenger::CexmcRunManagerMessenger(), DMXEventActionMessenger::DMXEventActionMessenger(), F01PrimaryGeneratorMessenger::F01PrimaryGeneratorMessenger(), F02PrimaryGeneratorMessenger::F02PrimaryGeneratorMessenger(), F03PrimaryGeneratorMessenger::F03PrimaryGeneratorMessenger(), F04PrimaryGeneratorMessenger::F04PrimaryGeneratorMessenger(), FCALTBEventActionMessenger::FCALTBEventActionMessenger(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4EmLowEParametersMessenger::G4EmLowEParametersMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4HumanPhantomMessenger::G4HumanPhantomMessenger(), G4ModelCmdSetAuxPtsFillStyle< M >::G4ModelCmdSetAuxPtsFillStyle(), G4ModelCmdSetAuxPtsSizeType< M >::G4ModelCmdSetAuxPtsSizeType(), G4ModelCmdSetAuxPtsType< M >::G4ModelCmdSetAuxPtsType(), G4ModelCmdSetStepPtsFillStyle< M >::G4ModelCmdSetStepPtsFillStyle(), G4ModelCmdSetStepPtsSizeType< M >::G4ModelCmdSetStepPtsSizeType(), G4ModelCmdSetStepPtsType< M >::G4ModelCmdSetStepPtsType(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticleHPMessenger::G4ParticleHPMessenger(), G4ParticleMessenger::G4ParticleMessenger(), G4PersistencyCenterMessenger::G4PersistencyCenterMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandManagerMode< Manager >::G4VisCommandManagerMode(), G4VisCommandSetTextLayout::G4VisCommandSetTextLayout(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerDefaultStyle::G4VisCommandViewerDefaultStyle(), GammaRayTelAnalysisMessenger::GammaRayTelAnalysisMessenger(), GB03DetectorMessenger::GB03DetectorMessenger(), G4UserPhysicsListMessenger::GetCurrentValue(), G4ParticleMessenger::GetCurrentValue(), HadrontherapyEventActionMessenger::HadrontherapyEventActionMessenger(), IORTEventActionMessenger::IORTEventActionMessenger(), RE05PrimaryGeneratorMessenger::RE05PrimaryGeneratorMessenger(), RE06DetectorMessenger::RE06DetectorMessenger(), G4ParticleMessenger::SetNewValue(), RE06DetectorMessenger::UpdateMaterialList(), WLSDetectorMessenger::WLSDetectorMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoEventActionMessenger::XrayFluoEventActionMessenger(), XrayFluoMercuryDetectorMessenger::XrayFluoMercuryDetectorMessenger(), XrayFluoMercuryPrimaryGeneratorMessenger::XrayFluoMercuryPrimaryGeneratorMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), XrayFluoPlanePrimaryGeneratorMessenger::XrayFluoPlanePrimaryGeneratorMessenger(), and XrayFluoPrimaryGeneratorMessenger::XrayFluoPrimaryGeneratorMessenger().
void G4UIcmdWithAString::SetDefaultValue (const char * defVal)
Definition at line 56 of file G4UIcmdWithAString.cc.
View newest version in sPHENIX GitHub at line 56 of file G4UIcmdWithAString.cc
References G4UIcommand::GetParameter(), and G4UIparameter::SetDefaultValue().
Referenced by CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CexmcRunManagerMessenger::CexmcRunManagerMessenger(), CML2PrimaryGenerationActionMessenger::CML2PrimaryGenerationActionMessenger(), DetectorConstructionMessenger::DetectorConstructionMessenger(), DMXRunActionMessenger::DMXRunActionMessenger(), F01DetectorMessenger::F01DetectorMessenger(), F01PrimaryGeneratorMessenger::F01PrimaryGeneratorMessenger(), F02DetectorMessenger::F02DetectorMessenger(), F02PrimaryGeneratorMessenger::F02PrimaryGeneratorMessenger(), F03DetectorMessenger::F03DetectorMessenger(), F03PrimaryGeneratorMessenger::F03PrimaryGeneratorMessenger(), F04DetectorMessenger::F04DetectorMessenger(), F04PrimaryGeneratorMessenger::F04PrimaryGeneratorMessenger(), F04RunActionMessenger::F04RunActionMessenger(), FCALTBEventActionMessenger::FCALTBEventActionMessenger(), G02DetectorMessenger::G02DetectorMessenger(), G03DetectorMessenger::G03DetectorMessenger(), G4FastSimulationMessenger::G4FastSimulationMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4HumanPhantomMessenger::G4HumanPhantomMessenger(), G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger(), G4LocalThreadCoutMessenger::G4LocalThreadCoutMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4NistMessenger::G4NistMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticleMessenger::G4ParticleMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4RadioactivationMessenger::G4RadioactivationMessenger(), G4RTMessenger::G4RTMessenger(), G4RunMessenger::G4RunMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4SDmessenger::G4SDmessenger(), G4TBFieldMessenger::G4TBFieldMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandSetTextLayout::G4VisCommandSetTextLayout(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), GammaRayTelAnalysisMessenger::GammaRayTelAnalysisMessenger(), HadrontherapyAnalysisFileMessenger::HadrontherapyAnalysisFileMessenger(), HadrontherapyEventActionMessenger::HadrontherapyEventActionMessenger(), HadrontherapyPrimaryGeneratorMessenger::HadrontherapyPrimaryGeneratorMessenger(), IORTEventActionMessenger::IORTEventActionMessenger(), RE05PrimaryGeneratorMessenger::RE05PrimaryGeneratorMessenger(), RunMessenger::RunMessenger(), WLSRunActionMessenger::WLSRunActionMessenger(), XrayFluoAnalysisMessenger::XrayFluoAnalysisMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoEventActionMessenger::XrayFluoEventActionMessenger(), XrayFluoMercuryDetectorMessenger::XrayFluoMercuryDetectorMessenger(), XrayFluoMercuryPrimaryGeneratorMessenger::XrayFluoMercuryPrimaryGeneratorMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), XrayFluoPlanePrimaryGeneratorMessenger::XrayFluoPlanePrimaryGeneratorMessenger(), and XrayFluoPrimaryGeneratorMessenger::XrayFluoPrimaryGeneratorMessenger().
void G4UIcmdWithAString::SetParameterName (const char * theName, G4bool omittable, G4bool currentAsDefault = false)
Definition at line 41 of file G4UIcmdWithAString.cc.
View newest version in sPHENIX GitHub at line 41 of file G4UIcmdWithAString.cc
References G4UIparameter::SetCurrentAsDefault(), G4UIparameter::SetOmittable(), and G4UIparameter::SetParameterName().
Referenced by B2aDetectorMessenger::B2aDetectorMessenger(), B2bDetectorMessenger::B2bDetectorMessenger(), BrachyPhysicsListMessenger::BrachyPhysicsListMessenger(), CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger(), CexmcChargeExchangeReconstructorMessenger::CexmcChargeExchangeReconstructorMessenger(), CexmcEnergyDepositDigitizerMessenger::CexmcEnergyDepositDigitizerMessenger(), CexmcParticleGunMessenger::CexmcParticleGunMessenger(), CexmcReconstructorMessenger::CexmcReconstructorMessenger(), CexmcRunManagerMessenger::CexmcRunManagerMessenger(), DetectorConstructionMessenger::DetectorConstructionMessenger(), DetectorMessenger::DetectorMessenger(), DicomIntersectVolume::DicomIntersectVolume(), DMXEventActionMessenger::DMXEventActionMessenger(), DMXRunActionMessenger::DMXRunActionMessenger(), doiPETDetectorConstructionMessenger::doiPETDetectorConstructionMessenger(), ElectronBenchmarkDetectorMessenger::ElectronBenchmarkDetectorMessenger(), ExGflashMessenger::ExGflashMessenger(), ExN02DetectorMessenger::ExN02DetectorMessenger(), ExN03DetectorMessenger::ExN03DetectorMessenger(), ExP01DetectorMessenger::ExP01DetectorMessenger(), F01DetectorMessenger::F01DetectorMessenger(), F01PrimaryGeneratorMessenger::F01PrimaryGeneratorMessenger(), F02DetectorMessenger::F02DetectorMessenger(), F02PrimaryGeneratorMessenger::F02PrimaryGeneratorMessenger(), F03DetectorMessenger::F03DetectorMessenger(), F03PrimaryGeneratorMessenger::F03PrimaryGeneratorMessenger(), F04DetectorMessenger::F04DetectorMessenger(), F04PrimaryGeneratorMessenger::F04PrimaryGeneratorMessenger(), F04RunActionMessenger::F04RunActionMessenger(), FCALTBEventActionMessenger::FCALTBEventActionMessenger(), G4ScoreQuantityMessenger::FilterCommands(), G02DetectorMessenger::G02DetectorMessenger(), G03DetectorMessenger::G03DetectorMessenger(), G4AdjointSimMessenger::G4AdjointSimMessenger(), G4DMmessenger::G4DMmessenger(), G4EmLowEParametersMessenger::G4EmLowEParametersMessenger(), G4EmParametersMessenger::G4EmParametersMessenger(), G4FastSimulationMessenger::G4FastSimulationMessenger(), G4GDMLMessenger::G4GDMLMessenger(), G4GMocrenMessenger::G4GMocrenMessenger(), G4HepRepMessenger::G4HepRepMessenger(), G4HumanPhantomMessenger::G4HumanPhantomMessenger(), G4INCLXXInterfaceMessenger::G4INCLXXInterfaceMessenger(), G4LocalThreadCoutMessenger::G4LocalThreadCoutMessenger(), G4MatScanMessenger::G4MatScanMessenger(), G4NistMessenger::G4NistMessenger(), G4OpticalPhysicsMessenger::G4OpticalPhysicsMessenger(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ParticleHPMessenger::G4ParticleHPMessenger(), G4ParticleMessenger::G4ParticleMessenger(), G4PersistencyCenterMessenger::G4PersistencyCenterMessenger(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4RadioactivationMessenger::G4RadioactivationMessenger(), G4RTMessenger::G4RTMessenger(), G4RunMessenger::G4RunMessenger(), G4ScoringMessenger::G4ScoringMessenger(), G4SDmessenger::G4SDmessenger(), G4TBFieldMessenger::G4TBFieldMessenger(), G4UIcontrolMessenger::G4UIcontrolMessenger(), G4UserPhysicsListMessenger::G4UserPhysicsListMessenger(), G4VisCommandListManagerList< Manager >::G4VisCommandListManagerList(), G4VisCommandListManagerSelect< Manager >::G4VisCommandListManagerSelect(), G4VisCommandManagerMode< Manager >::G4VisCommandManagerMode(), G4VisCommandModelCreate< Factory >::G4VisCommandModelCreate(), G4VisCommandSetTextLayout::G4VisCommandSetTextLayout(), G4VisCommandsTouchableSet::G4VisCommandsTouchableSet(), G4VisCommandsViewerSet::G4VisCommandsViewerSet(), G4VisCommandViewerDefaultStyle::G4VisCommandViewerDefaultStyle(), GammaKnifePhysicsListMessenger::GammaKnifePhysicsListMessenger(), GammaRayTelAnalysisMessenger::GammaRayTelAnalysisMessenger(), GammaRayTelDetectorMessenger::GammaRayTelDetectorMessenger(), GammaRayTelPhysicsListMessenger::GammaRayTelPhysicsListMessenger(), GB03DetectorMessenger::GB03DetectorMessenger(), HadrontherapyAnalysisFileMessenger::HadrontherapyAnalysisFileMessenger(), HadrontherapyEventActionMessenger::HadrontherapyEventActionMessenger(), HadrontherapyParameterMessenger::HadrontherapyParameterMessenger(), HadrontherapyPhysicsListMessenger::HadrontherapyPhysicsListMessenger(), HistoManagerMessenger::HistoManagerMessenger(), IORTEventActionMessenger::IORTEventActionMessenger(), IORTPhysicsListMessenger::IORTPhysicsListMessenger(), ML2PhysicsListMessenger::ML2PhysicsListMessenger(), PhysicsListMessenger::PhysicsListMessenger(), G4ScoreQuantityMessenger::QuantityCommands(), RE05PrimaryGeneratorMessenger::RE05PrimaryGeneratorMessenger(), RE06DetectorMessenger::RE06DetectorMessenger(), RunMessenger::RunMessenger(), STCyclotronDetectorMessenger::STCyclotronDetectorMessenger(), WLSRunActionMessenger::WLSRunActionMessenger(), XrayFluoAnalysisMessenger::XrayFluoAnalysisMessenger(), XrayFluoDetectorMessenger::XrayFluoDetectorMessenger(), XrayFluoEventActionMessenger::XrayFluoEventActionMessenger(), XrayFluoMercuryDetectorMessenger::XrayFluoMercuryDetectorMessenger(), XrayFluoMercuryPrimaryGeneratorMessenger::XrayFluoMercuryPrimaryGeneratorMessenger(), XrayFluoPhysicsListMessenger::XrayFluoPhysicsListMessenger(), XrayFluoPlaneDetectorMessenger::XrayFluoPlaneDetectorMessenger(), XrayFluoPlanePrimaryGeneratorMessenger::XrayFluoPlanePrimaryGeneratorMessenger(), and XrayFluoPrimaryGeneratorMessenger::XrayFluoPrimaryGeneratorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIcmdWithAString.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIcmdWithAString.cc