ECCE @ EIC Software: G4BertiniNeutronBuilder Class Reference
G4BertiniNeutronBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BertiniNeutronBuilder.hh>
Public Member Functions
G4BertiniNeutronBuilder ()
virtual ~G4BertiniNeutronBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4HadronFissionProcess *) finaloverride
virtual void Build (G4HadronCaptureProcess *) finaloverride
virtual void Build (G4NeutronInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VNeutronBuilder
G4VNeutronBuilder ()=default
virtual ~G4VNeutronBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4CascadeInterface * theModel
G4double theMin
G4double theMax
Detailed Description
Definition at line 52 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BertiniNeutronBuilder.hh
Constructor & Destructor Documentation
G4BertiniNeutronBuilder::G4BertiniNeutronBuilder ()
Definition at line 48 of file G4BertiniNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4BertiniNeutronBuilder.cc
References G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), theMax, theMin, and theModel.
virtual G4BertiniNeutronBuilder::~G4BertiniNeutronBuilder () inline virtual
Definition at line 56 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4BertiniNeutronBuilder.hh
Member Function Documentation
virtual void G4BertiniNeutronBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 58 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BertiniNeutronBuilder.hh
virtual void G4BertiniNeutronBuilder::Build (G4HadronFissionProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 59 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BertiniNeutronBuilder.hh
virtual void G4BertiniNeutronBuilder::Build (G4HadronCaptureProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 60 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4BertiniNeutronBuilder.hh
void G4BertiniNeutronBuilder::Build (G4NeutronInelasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 56 of file G4BertiniNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 56 of file G4BertiniNeutronBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4BertiniNeutronBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 64 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BertiniNeutronBuilder.hh
References theMax.
virtual void G4BertiniNeutronBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 63 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 63 of file G4BertiniNeutronBuilder.hh
References theMin.
Member Data Documentation
G4double G4BertiniNeutronBuilder::theMax private
Definition at line 71 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 71 of file G4BertiniNeutronBuilder.hh
Referenced by Build(), G4BertiniNeutronBuilder(), and SetMaxEnergy().
G4double G4BertiniNeutronBuilder::theMin private
Definition at line 70 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BertiniNeutronBuilder.hh
Referenced by Build(), G4BertiniNeutronBuilder(), and SetMinEnergy().
G4CascadeInterface* G4BertiniNeutronBuilder::theModel private
Definition at line 69 of file G4BertiniNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BertiniNeutronBuilder.hh
Referenced by Build(), and G4BertiniNeutronBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BertiniNeutronBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4BertiniNeutronBuilder.cc