ECCE @ EIC Software: G4CellScoreComposer Class Reference
G4CellScoreComposer Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4CellScoreComposer.hh>
Public Member Functions
G4CellScoreComposer ()
~G4CellScoreComposer ()
void EstimatorCalculation (const G4Step &step)
void TrackEnters ()
void NewTrackPopedUp ()
void SetCollisionWeight (G4double weight)
void SetImportnace (G4double importance)
const G4CellScoreValues & GetStandardCellScoreValues () const
Private Attributes
G4CellScoreValues fSCScoreValues
Detailed Description
Definition at line 50 of file G4CellScoreComposer.hh.
View newest version in sPHENIX GitHub at line 50 of file G4CellScoreComposer.hh
Constructor & Destructor Documentation
G4CellScoreComposer::G4CellScoreComposer ()
Definition at line 38 of file G4CellScoreComposer.cc.
View newest version in sPHENIX GitHub at line 38 of file G4CellScoreComposer.cc
G4CellScoreComposer::~G4CellScoreComposer ()
Definition at line 42 of file G4CellScoreComposer.cc.
View newest version in sPHENIX GitHub at line 42 of file G4CellScoreComposer.cc
Member Function Documentation
void G4CellScoreComposer::EstimatorCalculation (const G4Step & step)
Definition at line 45 of file G4CellScoreComposer.cc.
View newest version in sPHENIX GitHub at line 45 of file G4CellScoreComposer.cc
References e, FatalException, fSCScoreValues, G4CellScoreValues::fSumSL, G4CellScoreValues::fSumSLW, G4CellScoreValues::fSumSLW_v, G4CellScoreValues::fSumSLWE, G4CellScoreValues::fSumSLWE_v, G4Exception(), G4StepPoint::GetKineticEnergy(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4StepPoint::GetVelocity(), G4StepPoint::GetWeight(), and v.
const G4CellScoreValues & G4CellScoreComposer::GetStandardCellScoreValues () const
Definition at line 81 of file G4CellScoreComposer.cc.
View newest version in sPHENIX GitHub at line 81 of file G4CellScoreComposer.cc
References G4CellScoreValues::fAverageTrackWeight, G4CellScoreValues::fFluxWeightedEnergy, G4CellScoreValues::fNumberWeightedEnergy, fSCScoreValues, G4CellScoreValues::fSumSL, G4CellScoreValues::fSumSLW, G4CellScoreValues::fSumSLW_v, G4CellScoreValues::fSumSLWE, and G4CellScoreValues::fSumSLWE_v.
Referenced by operator<<().
void G4CellScoreComposer::NewTrackPopedUp ()
Definition at line 70 of file G4CellScoreComposer.cc.
View newest version in sPHENIX GitHub at line 70 of file G4CellScoreComposer.cc
References fSCScoreValues, and G4CellScoreValues::fSumPopulation.
void G4CellScoreComposer::SetCollisionWeight (G4double weight)
Definition at line 74 of file G4CellScoreComposer.cc.
View newest version in sPHENIX GitHub at line 74 of file G4CellScoreComposer.cc
References fSCScoreValues, G4CellScoreValues::fSumCollisions, G4CellScoreValues::fSumCollisionsWeight, and weight.
void G4CellScoreComposer::SetImportnace (G4double importance)
Definition at line 96 of file G4CellScoreComposer.cc.
View newest version in sPHENIX GitHub at line 96 of file G4CellScoreComposer.cc
References G4CellScoreValues::fImportance, and fSCScoreValues.
void G4CellScoreComposer::TrackEnters ()
Definition at line 67 of file G4CellScoreComposer.cc.
View newest version in sPHENIX GitHub at line 67 of file G4CellScoreComposer.cc
References fSCScoreValues, and G4CellScoreValues::fSumTracksEntering.
Member Data Documentation
G4CellScoreValues G4CellScoreComposer::fSCScoreValues mutable private
Definition at line 78 of file G4CellScoreComposer.hh.
View newest version in sPHENIX GitHub at line 78 of file G4CellScoreComposer.hh
Referenced by EstimatorCalculation(), GetStandardCellScoreValues(), NewTrackPopedUp(), SetCollisionWeight(), SetImportnace(), and TrackEnters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4CellScoreComposer.hh
geant4/tree/geant4-10.6-release/source/digits_hits/detector/src/G4CellScoreComposer.cc