ECCE @ EIC Software: G4LEPTSVibExcitationModel Class Reference
G4LEPTSVibExcitationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4LEPTSVibExcitationModel.hh>
Public Member Functions
G4LEPTSVibExcitationModel (const G4String &modelName="G4LEPTSVibExcitationModel")
~G4LEPTSVibExcitationModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin=0.0, G4double tmax=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
Public Member Functions inherited from G4VLEPTSModel
G4VLEPTSModel (const G4String &processName)
~G4VLEPTSModel ()
void BuildPhysicsTable (const G4ParticleDefinition &aParticleType)
G4double GetMeanFreePath (const G4Material *mate, const G4ParticleDefinition *aParticle, G4double kineticEnergy)
G4ThreeVector SampleNewDirection (const G4Material *aMaterial, G4ThreeVector Dir, G4double e, G4double el)
G4double SampleAngle (const G4Material *aMaterial, G4double e, G4double el)
G4ThreeVector SampleNewDirection (G4ThreeVector Dir, G4double ang)
G4VLEPTSModel & operator= (const G4VLEPTSModel &right)
G4VLEPTSModel (const G4VLEPTSModel &)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Additional Inherited Members
Protected Member Functions inherited from G4VLEPTSModel
void Init ()
G4bool ReadParam (G4String fileName, const G4Material *aMaterial)
virtual std::map< G4int,
std::vector< G4double > > ReadIXS (G4String fileName, const G4Material *aMaterial)
G4double SampleEnergyLoss (const G4Material *aMaterial, G4double eMin, G4double eMax)
void BuildMeanFreePathTable (const G4Material *aMaterial, std::map< G4int, std::vector< G4double > > &integralXS)
Protected Attributes inherited from G4VLEPTSModel
G4PhysicsTable * theMeanFreePathTable
G4double theLowestEnergyLimit
G4double theHighestEnergyLimit
G4int theNumbBinTable
std::map< const G4Material
*, G4double > theIonisPot
std::map< const G4Material
*, G4double > theIonisPotInt
std::map< const G4Material
*, G4double > theMolecularMass
std::map< const G4Material
*, G4LEPTSDiffXS * > theDiffXS
std::map< const G4Material
*, G4LEPTSDistribution * > theRMTDistr
std::map< const G4Material
*, G4LEPTSElossDistr * > theElostDistr
std::map< const G4Material
*, G4LEPTSDistribution * > theElostDistr2
std::map< const G4Material
*, G4int > theNXSdat
std::map< const G4Material
*, G4int > theNXSsub
G4bool isInitialised
XSType theXSType
G4int verboseLevel
Detailed Description
Definition at line 31 of file G4LEPTSVibExcitationModel.hh.
View newest version in sPHENIX GitHub at line 31 of file G4LEPTSVibExcitationModel.hh
Constructor & Destructor Documentation
G4LEPTSVibExcitationModel::G4LEPTSVibExcitationModel (const G4String & modelName = "G4LEPTSVibExcitationModel")
Definition at line 30 of file G4LEPTSVibExcitationModel.cc.
View newest version in sPHENIX GitHub at line 30 of file G4LEPTSVibExcitationModel.cc
References G4VLEPTSModel::theXSType, and XSVibration.
G4LEPTSVibExcitationModel::~G4LEPTSVibExcitationModel ()
Definition at line 37 of file G4LEPTSVibExcitationModel.cc.
View newest version in sPHENIX GitHub at line 37 of file G4LEPTSVibExcitationModel.cc
Member Function Documentation
G4double G4LEPTSVibExcitationModel::CrossSectionPerVolume (const G4Material * mate, const G4ParticleDefinition * aParticle, G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 54 of file G4LEPTSVibExcitationModel.cc.
View newest version in sPHENIX GitHub at line 54 of file G4LEPTSVibExcitationModel.cc
References G4VLEPTSModel::GetMeanFreePath().
void G4LEPTSVibExcitationModel::Initialise (const G4ParticleDefinition * aParticle, const G4DataVector &) virtual
Implements G4VEmModel.
Definition at line 42 of file G4LEPTSVibExcitationModel.cc.
View newest version in sPHENIX GitHub at line 42 of file G4LEPTSVibExcitationModel.cc
References G4VLEPTSModel::BuildPhysicsTable(), fParticleChangeForGamma, G4VEmModel::GetParticleChangeForGamma(), and G4VLEPTSModel::Init().
void G4LEPTSVibExcitationModel::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * mateCuts, const G4DynamicParticle * aDynamicParticle, G4double tmin = 0.0, G4double tmax = DBL_MAX) virtual
Implements G4VEmModel.
Definition at line 66 of file G4LEPTSVibExcitationModel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4LEPTSVibExcitationModel.cc
References CLHEP::eV, fParticleChangeForGamma, G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4VLEPTSModel::SampleNewDirection(), and G4ParticleChangeForGamma::SetProposedKineticEnergy().
Member Data Documentation
G4ParticleChangeForGamma* G4LEPTSVibExcitationModel::fParticleChangeForGamma private
Definition at line 54 of file G4LEPTSVibExcitationModel.hh.
View newest version in sPHENIX GitHub at line 54 of file G4LEPTSVibExcitationModel.hh
Referenced by Initialise(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4LEPTSVibExcitationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4LEPTSVibExcitationModel.cc