ECCE @ EIC Software: G4RichTrajectory Class Reference
G4RichTrajectory Class Reference
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4RichTrajectory.hh>
Public Member Functions
G4RichTrajectory ()
G4RichTrajectory (const G4Track *aTrack)
G4RichTrajectory (G4RichTrajectory &)
virtual ~G4RichTrajectory ()
G4RichTrajectory & operator= (const G4RichTrajectory &)=delete
G4int operator== (const G4RichTrajectory &r) const
void * operator new (size_t)
void operator delete (void *)
void ShowTrajectory (std::ostream &os=G4cout) const
void DrawTrajectory () const
void AppendStep (const G4Step *aStep)
void MergeTrajectory (G4VTrajectory *secondTrajectory)
G4int GetPointEntries () const
G4VTrajectoryPoint * GetPoint (G4int i) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4Trajectory
G4Trajectory ()
G4Trajectory (const G4Track *aTrack)
G4Trajectory (G4Trajectory &)
virtual ~G4Trajectory ()
void * operator new (size_t)
void operator delete (void *)
G4int operator== (const G4Trajectory &r) const
G4int GetTrackID () const
G4int GetParentID () const
G4String GetParticleName () const
G4double GetCharge () const
G4int GetPDGEncoding () const
G4double GetInitialKineticEnergy () const
G4ThreeVector GetInitialMomentum () const
G4ParticleDefinition * GetParticleDefinition ()
Public Member Functions inherited from G4VTrajectory
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
Private Types
using RichTrajectoryPointsContainer = std::vector< G4VTrajectoryPoint * >
Private Attributes
RichTrajectoryPointsContainer * fpRichPointsContainer
G4TouchableHandle fpInitialVolume
G4TouchableHandle fpInitialNextVolume
const G4VProcess * fpCreatorProcess
G4int fCreatorModelID
G4TouchableHandle fpFinalVolume
G4TouchableHandle fpFinalNextVolume
const G4VProcess * fpEndingProcess
G4double fFinalKineticEnergy
Detailed Description
Definition at line 57 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 57 of file G4RichTrajectory.hh
Member Typedef Documentation
using G4RichTrajectory::RichTrajectoryPointsContainer = std::vector<G4VTrajectoryPoint*> private
Definition at line 59 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 59 of file G4RichTrajectory.hh
Constructor & Destructor Documentation
G4RichTrajectory::G4RichTrajectory ()
Definition at line 66 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 66 of file G4RichTrajectory.cc
G4RichTrajectory::G4RichTrajectory (const G4Track * aTrack)
Definition at line 75 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 75 of file G4RichTrajectory.cc
References fCreatorModelID, fFinalKineticEnergy, fpCreatorProcess, fpEndingProcess, fpFinalNextVolume, fpFinalVolume, fpInitialNextVolume, fpInitialVolume, fpRichPointsContainer, G4Track::GetCreatorModelID(), G4Track::GetCreatorProcess(), G4Track::GetKineticEnergy(), G4Track::GetNextTouchableHandle(), and G4Track::GetTouchableHandle().
G4RichTrajectory::G4RichTrajectory (G4RichTrajectory & right)
Definition at line 100 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 100 of file G4RichTrajectory.cc
References fCreatorModelID, fFinalKineticEnergy, fpCreatorProcess, fpEndingProcess, fpFinalNextVolume, fpFinalVolume, fpInitialNextVolume, fpInitialVolume, and fpRichPointsContainer.
G4RichTrajectory::~G4RichTrajectory () virtual
Definition at line 120 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 120 of file G4RichTrajectory.cc
References fpRichPointsContainer.
Member Function Documentation
void G4RichTrajectory::AppendStep (const G4Step * aStep) virtual
Reimplemented from G4Trajectory.
Definition at line 133 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 133 of file G4RichTrajectory.cc
References fFinalKineticEnergy, fpEndingProcess, fpFinalNextVolume, fpFinalVolume, fpRichPointsContainer, G4Track::GetCurrentStepNumber(), G4StepPoint::GetKineticEnergy(), G4Track::GetNextTouchableHandle(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4Step::GetTotalEnergyDeposit(), G4Track::GetTouchableHandle(), G4Step::GetTrack(), and track.
std::vector< G4AttValue > * G4RichTrajectory::CreateAttValues () const virtual
Reimplemented from G4Trajectory.
Definition at line 252 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 252 of file G4RichTrajectory.cc
References G4UIcommand::ConvertToString(), G4Trajectory::CreateAttValues(), fCreatorModelID, fFinalKineticEnergy, fpCreatorProcess, fpEndingProcess, fpFinalNextVolume, fpFinalVolume, fpInitialNextVolume, fpInitialVolume, G4BestUnit, G4cout, GetAttDefs(), G4PhysicsModelCatalog::GetModelName(), G4VProcess::GetProcessName(), G4VProcess::GetProcessType(), G4VProcess::GetProcessTypeName(), G4VTouchable::GetVolume(), Path(), and Acts::Test::values.
void G4RichTrajectory::DrawTrajectory () const virtual
Reimplemented from G4Trajectory.
Definition at line 172 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 172 of file G4RichTrajectory.cc
References G4VTrajectory::DrawTrajectory().
const std::map< G4String, G4AttDef > * G4RichTrajectory::GetAttDefs () const virtual
Reimplemented from G4Trajectory.
Definition at line 179 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 179 of file G4RichTrajectory.cc
References G4Trajectory::GetAttDefs(), and G4AttDefStore::GetInstance().
Referenced by CreateAttValues(), G4VisCommandList::SetNewValue(), and G4VisCommandSceneAddTrajectories::SetNewValue().
G4VTrajectoryPoint* G4RichTrajectory::GetPoint (G4int i) const inline virtual
Reimplemented from G4Trajectory.
Definition at line 82 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 82 of file G4RichTrajectory.hh
References fpRichPointsContainer.
Referenced by G4TrajectoryDrawByEncounteredVolume::Draw(), and G4TrajectoryEncounteredVolumeFilter::Evaluate().
G4int G4RichTrajectory::GetPointEntries () const inline virtual
Reimplemented from G4Trajectory.
Definition at line 81 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 81 of file G4RichTrajectory.hh
References fpRichPointsContainer.
Referenced by G4TrajectoryDrawByEncounteredVolume::Draw(), G4TrajectoryEncounteredVolumeFilter::Evaluate(), and MergeTrajectory().
void G4RichTrajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) virtual
Reimplemented from G4Trajectory.
Definition at line 150 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 150 of file G4RichTrajectory.cc
References fpRichPointsContainer, and GetPointEntries().
void G4RichTrajectory::operator delete (void * aRichTrajectory) inline
Definition at line 111 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 111 of file G4RichTrajectory.hh
References aRichTrajectoryAllocator().
void * G4RichTrajectory::operator new (size_t) inline
Definition at line 104 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 104 of file G4RichTrajectory.hh
References aRichTrajectoryAllocator().
G4RichTrajectory& G4RichTrajectory::operator= (const G4RichTrajectory &) delete
G4int G4RichTrajectory::operator== (const G4RichTrajectory & r) const inline
Definition at line 71 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RichTrajectory.hh
void G4RichTrajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented from G4Trajectory.
Definition at line 165 of file G4RichTrajectory.cc.
View newest version in sPHENIX GitHub at line 165 of file G4RichTrajectory.cc
References G4VTrajectory::ShowTrajectory().
Member Data Documentation
G4int G4RichTrajectory::fCreatorModelID private
Definition at line 95 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RichTrajectory.hh
Referenced by CreateAttValues(), and G4RichTrajectory().
G4double G4RichTrajectory::fFinalKineticEnergy private
Definition at line 99 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 99 of file G4RichTrajectory.hh
Referenced by AppendStep(), CreateAttValues(), and G4RichTrajectory().
const G4VProcess* G4RichTrajectory::fpCreatorProcess private
Definition at line 94 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RichTrajectory.hh
Referenced by CreateAttValues(), and G4RichTrajectory().
const G4VProcess* G4RichTrajectory::fpEndingProcess private
Definition at line 98 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 98 of file G4RichTrajectory.hh
Referenced by AppendStep(), CreateAttValues(), and G4RichTrajectory().
G4TouchableHandle G4RichTrajectory::fpFinalNextVolume private
Definition at line 97 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 97 of file G4RichTrajectory.hh
Referenced by AppendStep(), CreateAttValues(), and G4RichTrajectory().
G4TouchableHandle G4RichTrajectory::fpFinalVolume private
Definition at line 96 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 96 of file G4RichTrajectory.hh
Referenced by AppendStep(), CreateAttValues(), and G4RichTrajectory().
G4TouchableHandle G4RichTrajectory::fpInitialNextVolume private
Definition at line 93 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 93 of file G4RichTrajectory.hh
Referenced by CreateAttValues(), and G4RichTrajectory().
G4TouchableHandle G4RichTrajectory::fpInitialVolume private
Definition at line 92 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RichTrajectory.hh
Referenced by CreateAttValues(), and G4RichTrajectory().
RichTrajectoryPointsContainer* G4RichTrajectory::fpRichPointsContainer private
Definition at line 91 of file G4RichTrajectory.hh.
View newest version in sPHENIX GitHub at line 91 of file G4RichTrajectory.hh
Referenced by AppendStep(), G4RichTrajectory(), GetPoint(), GetPointEntries(), MergeTrajectory(), and ~G4RichTrajectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4RichTrajectory.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4RichTrajectory.cc