ECCE @ EIC Software: G4GlobalFastSimulationManager Class Reference
G4GlobalFastSimulationManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4GlobalFastSimulationManager.hh>
Public Member Functions
G4VFastSimulationModel * GetFastSimulationModel (const G4String &modelName, const G4VFastSimulationModel *previousFound=0) const
~G4GlobalFastSimulationManager ()
void AddFastSimulationManager (G4FastSimulationManager *)
void RemoveFastSimulationManager (G4FastSimulationManager *)
void AddFSMP (G4FastSimulationManagerProcess *)
void RemoveFSMP (G4FastSimulationManagerProcess *)
void FastSimulationNeedsToBeClosed ()
void ShowSetup ()
void ListEnvelopes (const G4String &aName="all", listType aListType=NAMES_ONLY)
void ListEnvelopes (const G4ParticleDefinition *)
void ActivateFastSimulationModel (const G4String &)
void InActivateFastSimulationModel (const G4String &)
Static Public Member Functions
static
G4GlobalFastSimulationManager * GetGlobalFastSimulationManager ()
static
G4GlobalFastSimulationManager * GetInstance ()
Private Member Functions
G4GlobalFastSimulationManager ()
void DisplayRegion (G4Region *motherRegion, G4int depth, std::vector< G4ParticleDefinition * > &particles) const
Private Attributes
G4FastSimulationMessenger * fTheFastSimulationMessenger
G4FastSimulationVector
< G4FastSimulationManager > ManagedManagers
G4FastSimulationVector
< G4FastSimulationManagerProcess > fFSMPVector
Static Private Attributes
static G4ThreadLocal
G4GlobalFastSimulationManager * fGlobalFastSimulationManager = 0
Detailed Description
Definition at line 84 of file G4GlobalFastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 84 of file G4GlobalFastSimulationManager.hh
Constructor & Destructor Documentation
G4GlobalFastSimulationManager::~G4GlobalFastSimulationManager ()
Definition at line 95 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 95 of file G4GlobalFastSimulationManager.cc
References fTheFastSimulationMessenger.
G4GlobalFastSimulationManager::G4GlobalFastSimulationManager () private
Definition at line 87 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 87 of file G4GlobalFastSimulationManager.cc
References fTheFastSimulationMessenger.
Referenced by GetGlobalFastSimulationManager().
Member Function Documentation
void G4GlobalFastSimulationManager::ActivateFastSimulationModel (const G4String & aName)
Definition at line 126 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 126 of file G4GlobalFastSimulationManager.cc
References G4cout, G4endl, and ManagedManagers.
Referenced by G4FastSimulationMessenger::SetNewValue().
void G4GlobalFastSimulationManager::AddFastSimulationManager (G4FastSimulationManager * fsmanager)
Definition at line 105 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 105 of file G4GlobalFastSimulationManager.cc
References ManagedManagers.
void G4GlobalFastSimulationManager::AddFSMP (G4FastSimulationManagerProcess * fp)
Definition at line 116 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 116 of file G4GlobalFastSimulationManager.cc
References fFSMPVector.
Referenced by G4FastSimulationManagerProcess::G4FastSimulationManagerProcess().
void G4GlobalFastSimulationManager::DisplayRegion (G4Region * motherRegion, G4int depth, std::vector< G4ParticleDefinition * > & particles) const private
Definition at line 205 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 205 of file G4GlobalFastSimulationManager.cc
References G4ParticleTable::entries(), G4cout, G4endl, G4Region::GetFastSimulationManager(), G4FastSimulationManager::GetFastSimulationModelList(), G4PhysicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMotherLogical(), G4Region::GetName(), G4ParticleTable::GetParticle(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4LogicalVolume::GetRegion(), I, and G4LogicalVolume::IsRootRegion().
Referenced by ShowSetup().
void G4GlobalFastSimulationManager::FastSimulationNeedsToBeClosed ()
G4VFastSimulationModel * G4GlobalFastSimulationManager::GetFastSimulationModel (const G4String & modelName, const G4VFastSimulationModel * previousFound = 0) const
Definition at line 298 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 298 of file G4GlobalFastSimulationManager.cc
References ManagedManagers.
G4GlobalFastSimulationManager * G4GlobalFastSimulationManager::GetGlobalFastSimulationManager () static
Definition at line 70 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 70 of file G4GlobalFastSimulationManager.cc
References fGlobalFastSimulationManager, and G4GlobalFastSimulationManager().
Referenced by G4FastSimulationManager::G4FastSimulationManager(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), GetInstance(), G4FastSimulationManager::~G4FastSimulationManager(), and G4FastSimulationManagerProcess::~G4FastSimulationManagerProcess().
G4GlobalFastSimulationManager * G4GlobalFastSimulationManager::GetInstance (void) static
Definition at line 79 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 79 of file G4GlobalFastSimulationManager.cc
References GetGlobalFastSimulationManager().
void G4GlobalFastSimulationManager::InActivateFastSimulationModel (const G4String & aName)
Definition at line 139 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 139 of file G4GlobalFastSimulationManager.cc
References G4cout, G4endl, and ManagedManagers.
Referenced by G4FastSimulationMessenger::SetNewValue().
void G4GlobalFastSimulationManager::ListEnvelopes (const G4String & aName = "all", listType aListType = NAMES_ONLY)
Definition at line 255 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 255 of file G4GlobalFastSimulationManager.cc
References G4cout, G4endl, ISAPPLICABLE, ManagedManagers, and NAMES_ONLY.
Referenced by G4FastSimulationMessenger::SetNewValue().
void G4GlobalFastSimulationManager::ListEnvelopes (const G4ParticleDefinition * aPD)
Definition at line 291 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 291 of file G4GlobalFastSimulationManager.cc
References ManagedManagers.
void G4GlobalFastSimulationManager::RemoveFastSimulationManager (G4FastSimulationManager * fsmanager)
Definition at line 111 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 111 of file G4GlobalFastSimulationManager.cc
References ManagedManagers, and G4FastSimulationVector< T >::remove().
void G4GlobalFastSimulationManager::RemoveFSMP (G4FastSimulationManagerProcess * fp)
Definition at line 121 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 121 of file G4GlobalFastSimulationManager.cc
References fFSMPVector, and G4FastSimulationVector< T >::remove().
Referenced by G4FastSimulationManagerProcess::~G4FastSimulationManagerProcess().
void G4GlobalFastSimulationManager::ShowSetup ()
Definition at line 154 of file G4GlobalFastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 154 of file G4GlobalFastSimulationManager.cc
References G4ProcessVector::contains(), DisplayRegion(), G4ParticleTable::entries(), fFSMPVector, G4cout, G4endl, G4RegionStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4Region::GetName(), G4VPhysicalVolume::GetName(), G4ParticleTable::GetParticle(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4LogicalVolume::GetRegion(), G4TransportationManager::GetTransportationManager(), particle, and Acts::Test::world.
Referenced by G4FastSimulationMessenger::SetNewValue().
Member Data Documentation
G4FastSimulationVector<G4FastSimulationManagerProcess> G4GlobalFastSimulationManager::fFSMPVector private
Definition at line 162 of file G4GlobalFastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 162 of file G4GlobalFastSimulationManager.hh
Referenced by AddFSMP(), RemoveFSMP(), and ShowSetup().
G4ThreadLocal G4GlobalFastSimulationManager * G4GlobalFastSimulationManager::fGlobalFastSimulationManager = 0 static private
Definition at line 159 of file G4GlobalFastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 159 of file G4GlobalFastSimulationManager.hh
Referenced by GetGlobalFastSimulationManager().
G4FastSimulationMessenger* G4GlobalFastSimulationManager::fTheFastSimulationMessenger private
Definition at line 160 of file G4GlobalFastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 160 of file G4GlobalFastSimulationManager.hh
Referenced by G4GlobalFastSimulationManager(), and ~G4GlobalFastSimulationManager().
G4FastSimulationVector<G4FastSimulationManager> G4GlobalFastSimulationManager::ManagedManagers private
Definition at line 161 of file G4GlobalFastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 161 of file G4GlobalFastSimulationManager.hh
Referenced by ActivateFastSimulationModel(), AddFastSimulationManager(), GetFastSimulationModel(), InActivateFastSimulationModel(), ListEnvelopes(), and RemoveFastSimulationManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4GlobalFastSimulationManager.hh
geant4/tree/geant4-10.6-release/source/processes/parameterisation/src/G4GlobalFastSimulationManager.cc