ECCE @ EIC Software: G4WorkerThread Class Reference
G4WorkerThread Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4WorkerThread.hh>
Public Member Functions
void SetThreadId (G4int threadId)
G4int GetThreadId () const
void SetNumberThreads (G4int numnberThreads)
G4int GetNumberThreads () const
void SetPinAffinity (G4int aff) const
Static Public Member Functions
static void BuildGeometryAndPhysicsVector ()
static void DestroyGeometryAndPhysicsVector ()
static void UpdateGeometryAndPhysicsVectorFromMaster ()
Private Attributes
G4int threadId
G4int numThreads
Detailed Description
Definition at line 42 of file G4WorkerThread.hh.
View newest version in sPHENIX GitHub at line 42 of file G4WorkerThread.hh
Member Function Documentation
void G4WorkerThread::BuildGeometryAndPhysicsVector () static
Definition at line 62 of file G4WorkerThread.cc.
View newest version in sPHENIX GitHub at line 62 of file G4WorkerThread.cc
References G4TWorkspacePool< T >::CreateAndUseWorkspace(), G4ParticlesWorkspace::GetPool(), G4PhysicsListWorkspace::GetPool(), G4SolidsWorkspace::GetPool(), and G4GeometryWorkspace::GetPool().
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
void G4WorkerThread::DestroyGeometryAndPhysicsVector () static
Definition at line 73 of file G4WorkerThread.cc.
View newest version in sPHENIX GitHub at line 73 of file G4WorkerThread.cc
References G4TWorkspacePool< T >::CleanUpAndDestroyAllWorkspaces(), G4ParticlesWorkspace::GetPool(), G4PhysicsListWorkspace::GetPool(), G4SolidsWorkspace::GetPool(), and G4GeometryWorkspace::GetPool().
Referenced by G4MTRunManagerKernel::StartThread().
G4int G4WorkerThread::GetNumberThreads () const
Definition at line 57 of file G4WorkerThread.cc.
View newest version in sPHENIX GitHub at line 57 of file G4WorkerThread.cc
References numThreads.
G4int G4WorkerThread::GetThreadId () const
Definition at line 47 of file G4WorkerThread.cc.
View newest version in sPHENIX GitHub at line 47 of file G4WorkerThread.cc
References threadId.
Referenced by G4WorkerRunManager::rndmSaveThisEvent(), G4WorkerRunManager::rndmSaveThisRun(), SetPinAffinity(), G4MTRunManagerKernel::StartThread(), and G4WorkerRunManager::StoreRNGStatus().
void G4WorkerThread::SetNumberThreads (G4int numnberThreads)
Definition at line 52 of file G4WorkerThread.cc.
View newest version in sPHENIX GitHub at line 52 of file G4WorkerThread.cc
References numThreads.
Referenced by G4MTRunManager::CreateAndStartWorkers().
void G4WorkerThread::SetPinAffinity (G4int aff) const
Definition at line 199 of file G4WorkerThread.cc.
View newest version in sPHENIX GitHub at line 199 of file G4WorkerThread.cc
References kdfinder::abs(), G4cout, G4endl, G4Exception(), G4Threading::G4GetNumberOfCores(), G4Threading::G4SetPinAffinity(), GetThreadId(), JustWarning, offset, and t.
Referenced by G4MTRunManagerKernel::StartThread().
void G4WorkerThread::SetThreadId (G4int threadId)
Definition at line 42 of file G4WorkerThread.cc.
View newest version in sPHENIX GitHub at line 42 of file G4WorkerThread.cc
References threadId.
Referenced by G4MTRunManager::CreateAndStartWorkers().
void G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster () static
Definition at line 83 of file G4WorkerThread.cc.
View newest version in sPHENIX GitHub at line 83 of file G4WorkerThread.cc
References G4SolidsWorkspace::DestroyWorkspace(), G4GeometryWorkspace::DestroyWorkspace(), G4Region::GetFastSimulationManager(), G4LogicalVolume::GetFieldManager(), G4LogicalVolumeStore::GetInstance(), G4RegionStore::GetInstance(), G4LogicalVolume::GetMasterFieldManager(), G4LogicalVolume::GetMasterSensitiveDetector(), G4SolidsWorkspace::GetPool(), G4GeometryWorkspace::GetPool(), G4Region::GetRegionalSteppingAction(), G4LogicalVolume::GetSensitiveDetector(), G4TWorkspacePool< T >::GetWorkspace(), G4SolidsWorkspace::InitialiseWorkspace(), G4GeometryWorkspace::InitialiseWorkspace(), it, reg, second, G4Region::SetFastSimulationManager(), G4LogicalVolume::SetFieldManager(), G4Region::SetRegionalSteppingAction(), and G4LogicalVolume::SetSensitiveDetector().
Referenced by G4WorkerRunManager::DoWork().
Member Data Documentation
G4int G4WorkerThread::numThreads private
Definition at line 60 of file G4WorkerThread.hh.
View newest version in sPHENIX GitHub at line 60 of file G4WorkerThread.hh
Referenced by GetNumberThreads(), and SetNumberThreads().
G4int G4WorkerThread::threadId private
Definition at line 59 of file G4WorkerThread.hh.
View newest version in sPHENIX GitHub at line 59 of file G4WorkerThread.hh
Referenced by GetThreadId(), and SetThreadId().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4WorkerThread.hh
geant4/tree/geant4-10.6-release/source/run/src/G4WorkerThread.cc