ECCE @ EIC Software: G4INCL::NLToNSChannel Class Reference
G4INCL::NLToNSChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNLToNSChannel.hh>
Public Member Functions
NLToNSChannel (Particle *, Particle *)
virtual ~NLToNSChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
INCL_DECLARE_ALLOCATION_POOL (NLToNSChannel)
Private Attributes
Particle * particle1
Particle * particle2
Detailed Description
Definition at line 47 of file G4INCLNLToNSChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLNLToNSChannel.hh
Constructor & Destructor Documentation
G4INCL::NLToNSChannel::NLToNSChannel (Particle * p1, Particle * p2)
Definition at line 49 of file G4INCLNLToNSChannel.cc.
View newest version in sPHENIX GitHub at line 49 of file G4INCLNLToNSChannel.cc
G4INCL::NLToNSChannel::~NLToNSChannel () virtual
Definition at line 53 of file G4INCLNLToNSChannel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4INCLNLToNSChannel.cc
Member Function Documentation
void G4INCL::NLToNSChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 55 of file G4INCLNLToNSChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNLToNSChannel.cc
References G4INCL::FinalState::addModifiedParticle(), G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getMass(), G4INCL::ParticleTable::getNucleonType(), G4INCL::ParticleTable::getSigmaType(), G4INCL::Particle::getType(), G4INCL::Particle::isNucleon(), G4InuclParticleNames::lambda, my, G4INCL::Random::normVector(), G4InuclParticleNames::nucleon(), particle1, particle2, G4INCL::Particle::setEnergy(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setType(), G4INCL::Random::shoot(), G4INCL::SigmaZero, and G4INCL::KinematicsUtils::totalEnergyInCM().
G4INCL::NLToNSChannel::INCL_DECLARE_ALLOCATION_POOL (NLToNSChannel) private
Member Data Documentation
Particle* G4INCL::NLToNSChannel::particle1 private
Definition at line 55 of file G4INCLNLToNSChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNLToNSChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::NLToNSChannel::particle2 private
Definition at line 55 of file G4INCLNLToNSChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNLToNSChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNLToNSChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNLToNSChannel.cc