ECCE @ EIC Software: ITTrackingInteractivity Class Reference
ITTrackingInteractivity Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/ITTrackingInteractivity.hh>
Public Member Functions
ITTrackingInteractivity ()
virtual ~ITTrackingInteractivity ()
virtual void Initialize ()
virtual void StartTracking (G4Track *)
virtual void AppendStep (G4Track *track, G4Step *step)
virtual void EndTracking (G4Track *)
virtual void Finalize ()
void SetUserAction (G4UserTrackingAction *)
G4UserTrackingAction * GetUserTrackingAction ()
void SetUserAction (G4UserSteppingAction *)
G4UserSteppingAction * GetUserSteppingAction ()
ITTrackingInteractivity ()
~ITTrackingInteractivity () override
void Initialize () override
void StartTracking (G4Track *) override
void AppendStep (G4Track *track, G4Step *step) override
void EndTracking (G4Track *) override
void Finalize () override
void SetUserAction (G4UserTrackingAction *)
std::unique_ptr
< G4UserTrackingAction > GetUserTrackingAction ()
void SetUserAction (G4UserSteppingAction *)
std::unique_ptr
< G4UserSteppingAction > GetUserSteppingAction ()
ITTrackingInteractivity ()
virtual ~ITTrackingInteractivity ()
virtual void Initialize ()
virtual void StartTracking (G4Track *)
virtual void AppendStep (G4Track *track, G4Step *step)
virtual void EndTracking (G4Track *)
virtual void Finalize ()
void SetUserAction (G4UserTrackingAction *)
G4UserTrackingAction * GetUserTrackingAction ()
void SetUserAction (G4UserSteppingAction *)
G4UserSteppingAction * GetUserSteppingAction ()
Public Member Functions inherited from G4ITTrackingInteractivity
G4ITTrackingInteractivity (G4VITSteppingVerbose *verbose=0)
virtual ~G4ITTrackingInteractivity ()
virtual void TrackBanner (G4Track *, const G4String &message="")
void SetVerbose (int flag)
G4int GetVerboseLevel () const
void SetSteppingVerboseLevel (G4int level)
G4int GetSteppingVerboseLevel () const
G4VITSteppingVerbose * GetSteppingVerbose ()
void SetSteppingVerbose (G4VITSteppingVerbose *verbose)
Private Attributes
G4UserTrackingAction * fpUserTrackingAction
G4UserSteppingAction * fpUserSteppingAction
int fStoreTrajectory
std::vector< G4VTrajectory * > fTrajectories
std::unique_ptr
< G4UserTrackingAction > fpUserTrackingAction
std::unique_ptr
< G4UserSteppingAction > fpUserSteppingAction
Additional Inherited Members
Protected Attributes inherited from G4ITTrackingInteractivity
int fVerboseLevel
Detailed Description
Definition at line 48 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 48 of file ITTrackingInteractivity.hh
Constructor & Destructor Documentation
ITTrackingInteractivity::ITTrackingInteractivity ()
Definition at line 64 of file ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 64 of file ITTrackingInteractivity.cc
References fpUserSteppingAction, fpUserTrackingAction, fStoreTrajectory, and G4ITTrackingInteractivity::fVerboseLevel.
ITTrackingInteractivity::~ITTrackingInteractivity () virtual
Definition at line 86 of file ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 86 of file ITTrackingInteractivity.cc
References fpUserSteppingAction, fpUserTrackingAction, G4EventManager::GetEventManager(), G4EventManager::GetUserSteppingAction(), and G4EventManager::GetUserTrackingAction().
ITTrackingInteractivity::ITTrackingInteractivity ()
ITTrackingInteractivity::~ITTrackingInteractivity () override
ITTrackingInteractivity::ITTrackingInteractivity ()
virtual ITTrackingInteractivity::~ITTrackingInteractivity () virtual
Member Function Documentation
void ITTrackingInteractivity::AppendStep (G4Track * track, G4Step * step) override virtual
Reimplemented from G4ITTrackingInteractivity.
void ITTrackingInteractivity::AppendStep (G4Track * track, G4Step * step) virtual
Reimplemented from G4ITTrackingInteractivity.
Definition at line 171 of file ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 171 of file ITTrackingInteractivity.cc
References G4VTrajectory::AppendStep(), G4Trajectory_Lock::fpTrajectory, fpUserSteppingAction, fStoreTrajectory, GetIT(), G4IT::GetTrackingInfo(), G4TrackingInformation::GetTrajectory_Lock(), and G4UserSteppingAction::UserSteppingAction().
virtual void ITTrackingInteractivity::AppendStep (G4Track * track, G4Step * step) virtual
Reimplemented from G4ITTrackingInteractivity.
void ITTrackingInteractivity::EndTracking (G4Track *) override virtual
Reimplemented from G4ITTrackingInteractivity.
void ITTrackingInteractivity::EndTracking (G4Track * track) virtual
Reimplemented from G4ITTrackingInteractivity.
Definition at line 218 of file ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 218 of file ITTrackingInteractivity.cc
References G4Trajectory_Lock::fpTrajectory, fpUserTrackingAction, fStopButAlive, fStoreTrajectory, fSuspend, fTrajectories, G4ITTrackingInteractivity::fVerboseLevel, G4EventManager::GetEventManager(), GetIT(), G4EventManager::GetNonconstCurrentEvent(), G4IT::GetTrackingInfo(), G4Track::GetTrackStatus(), G4TrackingInformation::GetTrajectory_Lock(), G4Event::GetTrajectoryContainer(), G4TrajectoryContainer::insert(), G4UserTrackingAction::PostUserTrackingAction(), G4TrackingInformation::SetTrajectory_Lock(), G4Event::SetTrajectoryContainer(), G4VTrajectory::ShowTrajectory(), and G4ITTrackingInteractivity::TrackBanner().
virtual void ITTrackingInteractivity::EndTracking (G4Track *) virtual
Reimplemented from G4ITTrackingInteractivity.
void ITTrackingInteractivity::Finalize () override virtual
Reimplemented from G4ITTrackingInteractivity.
void ITTrackingInteractivity::Finalize () virtual
Reimplemented from G4ITTrackingInteractivity.
Definition at line 283 of file ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 283 of file ITTrackingInteractivity.cc
References G4VVisManager::Draw(), fTrajectories, G4VVisManager::GetConcreteInstance(), and it.
virtual void ITTrackingInteractivity::Finalize () virtual
Reimplemented from G4ITTrackingInteractivity.
std::unique_ptr<G4UserSteppingAction> ITTrackingInteractivity::GetUserSteppingAction () inline
G4UserSteppingAction * ITTrackingInteractivity::GetUserSteppingAction () inline
Definition at line 85 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 85 of file ITTrackingInteractivity.hh
References fpUserSteppingAction.
G4UserSteppingAction* ITTrackingInteractivity::GetUserSteppingAction () inline
std::unique_ptr<G4UserTrackingAction> ITTrackingInteractivity::GetUserTrackingAction () inline
G4UserTrackingAction * ITTrackingInteractivity::GetUserTrackingAction () inline
Definition at line 91 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 91 of file ITTrackingInteractivity.hh
References fpUserTrackingAction.
G4UserTrackingAction* ITTrackingInteractivity::GetUserTrackingAction () inline
void ITTrackingInteractivity::Initialize () override virtual
Reimplemented from G4ITTrackingInteractivity.
void ITTrackingInteractivity::Initialize () virtual
Reimplemented from G4ITTrackingInteractivity.
Definition at line 119 of file ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 119 of file ITTrackingInteractivity.cc
References fStoreTrajectory, G4ITTrackingInteractivity::fVerboseLevel, G4EventManager::GetEventManager(), G4TrackingManager::GetStoreTrajectory(), G4EventManager::GetTrackingManager(), and G4TrackingManager::GetVerboseLevel().
virtual void ITTrackingInteractivity::Initialize () virtual
Reimplemented from G4ITTrackingInteractivity.
void ITTrackingInteractivity::SetUserAction (G4UserTrackingAction *)
void ITTrackingInteractivity::SetUserAction (G4UserSteppingAction *)
void ITTrackingInteractivity::SetUserAction (G4UserTrackingAction * trackAct) inline
Definition at line 73 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 73 of file ITTrackingInteractivity.hh
References fpUserTrackingAction.
void ITTrackingInteractivity::SetUserAction (G4UserSteppingAction * stepAct) inline
Definition at line 79 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 79 of file ITTrackingInteractivity.hh
References fpUserSteppingAction.
void ITTrackingInteractivity::SetUserAction (G4UserTrackingAction *)
void ITTrackingInteractivity::SetUserAction (G4UserSteppingAction *)
void ITTrackingInteractivity::StartTracking (G4Track *) override virtual
Reimplemented from G4ITTrackingInteractivity.
void ITTrackingInteractivity::StartTracking (G4Track * track) virtual
Reimplemented from G4ITTrackingInteractivity.
Definition at line 129 of file ITTrackingInteractivity.cc.
View newest version in sPHENIX GitHub at line 129 of file ITTrackingInteractivity.cc
References G4Trajectory_Lock::fpTrajectory, fpUserTrackingAction, fStoreTrajectory, G4ITTrackingInteractivity::fVerboseLevel, GetIT(), G4VSteppingVerbose::GetSilent(), G4IT::GetTrackingInfo(), G4TrackingInformation::GetTrajectory_Lock(), G4UserTrackingAction::PreUserTrackingAction(), G4TrackingInformation::SetTrajectory_Lock(), and G4ITTrackingInteractivity::TrackBanner().
virtual void ITTrackingInteractivity::StartTracking (G4Track *) virtual
Reimplemented from G4ITTrackingInteractivity.
Member Data Documentation
G4UserSteppingAction * ITTrackingInteractivity::fpUserSteppingAction private
Definition at line 51 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 51 of file ITTrackingInteractivity.hh
Referenced by AppendStep(), GetUserSteppingAction(), ITTrackingInteractivity(), SetUserAction(), and ~ITTrackingInteractivity().
std::unique_ptr<G4UserSteppingAction> ITTrackingInteractivity::fpUserSteppingAction private
Definition at line 63 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 63 of file ITTrackingInteractivity.hh
G4UserTrackingAction * ITTrackingInteractivity::fpUserTrackingAction private
Definition at line 50 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 50 of file ITTrackingInteractivity.hh
Referenced by EndTracking(), GetUserTrackingAction(), ITTrackingInteractivity(), SetUserAction(), StartTracking(), and ~ITTrackingInteractivity().
std::unique_ptr<G4UserTrackingAction> ITTrackingInteractivity::fpUserTrackingAction private
Definition at line 61 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 61 of file ITTrackingInteractivity.hh
int ITTrackingInteractivity::fStoreTrajectory private
Definition at line 52 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 52 of file ITTrackingInteractivity.hh
Referenced by AppendStep(), EndTracking(), Initialize(), ITTrackingInteractivity(), and StartTracking().
std::vector< G4VTrajectory * > ITTrackingInteractivity::fTrajectories private
Definition at line 53 of file ITTrackingInteractivity.hh.
View newest version in sPHENIX GitHub at line 53 of file ITTrackingInteractivity.hh
Referenced by EndTracking(), and Finalize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/ITTrackingInteractivity.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/include/ITTrackingInteractivity.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/ITTrackingInteractivity.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/ITTrackingInteractivity.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/src/ITTrackingInteractivity.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/ITTrackingInteractivity.cc