var dir_33dc7f3d2038756a593124fa267ac13c =
[
    [ "G4AngleDirect.cc", "d9/d04/G4AngleDirect_8cc.html", null ],
    [ "G4DummyModel.cc", "d9/d27/G4DummyModel_8cc.html", null ],
    [ "G4ElectronIonPair.cc", "d8/dfa/G4ElectronIonPair_8cc.html", null ],
    [ "G4EmBiasingManager.cc", "d8/d92/G4EmBiasingManager_8cc.html", null ],
    [ "G4EmCalculator.cc", "d2/de9/G4EmCalculator_8cc.html", null ],
    [ "G4EmConfigurator.cc", "db/de0/G4EmConfigurator_8cc.html", null ],
    [ "G4EmCorrections.cc", "da/d1f/G4EmCorrections_8cc.html", "da/d1f/G4EmCorrections_8cc" ],
    [ "G4EmDataHandler.cc", "db/db2/G4EmDataHandler_8cc.html", null ],
    [ "G4EmElementSelector.cc", "df/d19/G4EmElementSelector_8cc.html", null ],
    [ "G4EmExtraParameters.cc", "d6/db8/G4EmExtraParameters_8cc.html", null ],
    [ "G4EmExtraParametersMessenger.cc", "df/df9/G4EmExtraParametersMessenger_8cc.html", null ],
    [ "G4EmLowEParameters.cc", "df/d17/G4EmLowEParameters_8cc.html", null ],
    [ "G4EmLowEParametersMessenger.cc", "d3/d1f/G4EmLowEParametersMessenger_8cc.html", null ],
    [ "G4EmModelManager.cc", "d3/d9b/G4EmModelManager_8cc.html", null ],
    [ "G4EmMultiModel.cc", "d6/da5/G4EmMultiModel_8cc.html", null ],
    [ "G4EmParameters.cc", "d4/d31/G4EmParameters_8cc.html", "d4/d31/G4EmParameters_8cc" ],
    [ "G4EmParametersMessenger.cc", "d5/dde/G4EmParametersMessenger_8cc.html", null ],
    [ "G4EmProcessOptions.cc", "d1/d13/G4EmProcessOptions_8cc.html", null ],
    [ "G4EmSaturation.cc", "d8/d17/G4EmSaturation_8cc.html", null ],
    [ "G4EnergyLossTables.cc", "da/dfa/G4EnergyLossTables_8cc.html", null ],
    [ "G4ionEffectiveCharge.cc", "d2/d02/G4ionEffectiveCharge_8cc.html", null ],
    [ "G4LossTableBuilder.cc", "dd/d0b/G4LossTableBuilder_8cc.html", null ],
    [ "G4LossTableManager.cc", "d1/dc8/G4LossTableManager_8cc.html", null ],
    [ "G4NIELCalculator.cc", "dc/d47/G4NIELCalculator_8cc.html", null ],
    [ "G4VAtomDeexcitation.cc", "dc/db3/G4VAtomDeexcitation_8cc.html", null ],
    [ "G4VEmAngularDistribution.cc", "d8/db3/G4VEmAngularDistribution_8cc.html", null ],
    [ "G4VEmFluctuationModel.cc", "d6/dbb/G4VEmFluctuationModel_8cc.html", null ],
    [ "G4VEmModel.cc", "d5/d44/G4VEmModel_8cc.html", null ],
    [ "G4VEmProcess.cc", "d1/d93/G4VEmProcess_8cc.html", null ],
    [ "G4VEnergyLossProcess.cc", "de/dc9/G4VEnergyLossProcess_8cc.html", null ],
    [ "G4VMscModel.cc", "d1/d47/G4VMscModel_8cc.html", null ],
    [ "G4VMultipleScattering.cc", "dd/d00/G4VMultipleScattering_8cc.html", null ]
];