ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/G4ScreenedNuclearRecoil.hh File Reference
G4ScreenedNuclearRecoil.hh File Reference
Definition of the G4ScreenedNuclearRecoil class.
#include "globals.hh"
#include "G4VDiscreteProcess.hh"
#include "G4ParticleChange.hh"
#include "c2_function.hh"
#include "G4PhysicalConstants.hh"
#include "G4SystemOfUnits.hh"
#include <map>
#include <vector>
Classes
struct G4ScreeningTables
class G4ScreenedCoulombCrossSectionInfo
class G4ScreenedCoulombCrossSection
struct G4CoulombKinematicsInfo
class G4ScreenedCollisionStage
class G4ScreenedCoulombClassicalKinematics
class G4SingleScatter
class G4ScreenedNuclearRecoil
A process which handles screened Coulomb collisions between nuclei.
class G4NativeScreenedCoulombCrossSection
Typedefs
typedef c2_const_ptr< G4double > G4_c2_const_ptr
typedef c2_ptr< G4double > G4_c2_ptr
typedef c2_function< G4double > G4_c2_function
typedef struct G4ScreeningTables G4ScreeningTables
typedef struct
G4CoulombKinematicsInfo G4CoulombKinematicsInfo
Functions
G4_c2_function & ZBLScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double *auval)
G4_c2_function & MoliereScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double *auval)
G4_c2_function & LJScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double *auval)
G4_c2_function & LJZBLScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double *auval)
Detailed Description
Definition of the G4ScreenedNuclearRecoil class.
Definition in file G4ScreenedNuclearRecoil.hh.
Typedef Documentation
typedef c2_const_ptr<G4double> G4_c2_const_ptr
Definition at line 74 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ScreenedNuclearRecoil.hh
typedef c2_function<G4double> G4_c2_function
Definition at line 78 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ScreenedNuclearRecoil.hh
typedef c2_ptr<G4double> G4_c2_ptr
Definition at line 77 of file G4ScreenedNuclearRecoil.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ScreenedNuclearRecoil.hh
typedef struct G4CoulombKinematicsInfo G4CoulombKinematicsInfo
typedef struct G4ScreeningTables G4ScreeningTables
Function Documentation
G4_c2_function& LJScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double * auval)
Definition at line 898 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 898 of file G4ScreenedNuclearRecoil.cc
References angstrom, c2_factory< float_type >::lin_log_interpolating_function(), phi, r, and y.
Referenced by G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection(), and LJZBLScreening().
G4_c2_function& LJZBLScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double * auval)
connector in between. These numbers are selected so the switchover
Definition at line 930 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 930 of file G4ScreenedNuclearRecoil.cc
References c2_piecewise_function_p< float_type >::append_function(), c2_factory< float_type >::connector_function(), LJScreening(), c2_factory< float_type >::piecewise_function(), c2_const_ptr< float_type >::release_for_return(), c2_function< float_type >::set_domain(), c2_function< float_type >::xmax(), c2_function< float_type >::xmin(), and ZBLScreening().
Referenced by G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection().
G4_c2_function& MoliereScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double * auval)
Definition at line 866 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 866 of file G4ScreenedNuclearRecoil.cc
References angstrom, c2_factory< float_type >::lin_log_interpolating_function(), phi, r, and sum.
Referenced by G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection().
G4_c2_function& ZBLScreening (G4int z1, G4int z2, size_t npoints, G4double rMax, G4double * auval)
Definition at line 834 of file G4ScreenedNuclearRecoil.cc.
View newest version in sPHENIX GitHub at line 834 of file G4ScreenedNuclearRecoil.cc
References angstrom, c2_factory< float_type >::lin_log_interpolating_function(), phi, r, and sum.
Referenced by G4NativeScreenedCoulombCrossSection::G4NativeScreenedCoulombCrossSection(), and LJZBLScreening().