ECCE @ EIC Software: G4HnInformation Class Reference
G4HnInformation Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4HnInformation.hh>
Public Member Functions
G4HnInformation (const G4String &name, G4int nofDimensions)
fActivation (true)
fAscii (false)
fPlotting (false)
G4HnInformation ()=delete
void AddHnDimensionInformation (const G4HnDimensionInformation &hnDimensionInformation)
void AddDimension (const G4String &unitName, const G4String &fcnName, G4BinScheme binScheme)
void SetDimension (G4int dimension, const G4String &unitName, const G4String &fcnName, G4BinScheme binScheme)
void SetIsLogAxis (G4int axis, G4bool isLog)
void SetActivation (G4bool activation)
void SetAscii (G4bool ascii)
void SetPlotting (G4bool plotting)
G4String GetName () const
G4HnDimensionInformation * GetHnDimensionInformation (G4int dimension)
G4bool GetIsLogAxis (G4int axis) const
G4bool GetActivation () const
G4bool GetAscii () const
G4bool GetPlotting () const
Private Attributes
G4String fName
std::vector
< G4HnDimensionInformation > fHnDimensionInformations
std::vector< G4bool > fIsLogAxis
G4bool fActivation
G4bool fAscii
G4bool fPlotting
Detailed Description
Definition at line 94 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 94 of file G4HnInformation.hh
Constructor & Destructor Documentation
G4HnInformation::G4HnInformation (const G4String & name, G4int nofDimensions) inline
Definition at line 97 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 97 of file G4HnInformation.hh
G4HnInformation::G4HnInformation () delete
Member Function Documentation
void G4HnInformation::AddDimension (const G4String & unitName, const G4String & fcnName, G4BinScheme binScheme) inline
Definition at line 144 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 144 of file G4HnInformation.hh
References fHnDimensionInformations, G4Analysis::GetFunction(), and G4Analysis::GetUnitValue().
Referenced by G4H1ToolsManager::AddH1Information(), G4H2ToolsManager::AddH2Information(), G4H3ToolsManager::AddH3Information(), G4P1ToolsManager::AddP1Information(), and G4P2ToolsManager::AddP2Information().
void G4HnInformation::AddHnDimensionInformation (const G4HnDimensionInformation & hnDimensionInformation) inline
Definition at line 140 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 140 of file G4HnInformation.hh
References fHnDimensionInformations.
G4HnInformation::fActivation (true)
G4HnInformation::fAscii (false)
G4HnInformation::fPlotting (false) inline
Definition at line 103 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 103 of file G4HnInformation.hh
References fHnDimensionInformations.
G4bool G4HnInformation::GetActivation () const inline
Definition at line 187 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 187 of file G4HnInformation.hh
References fActivation.
Referenced by G4PlotManager::PlotAndWrite().
G4bool G4HnInformation::GetAscii () const inline
Definition at line 190 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 190 of file G4HnInformation.hh
References fAscii.
G4HnDimensionInformation * G4HnInformation::GetHnDimensionInformation (G4int dimension) inline
Definition at line 181 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 181 of file G4HnInformation.hh
References fHnDimensionInformations.
Referenced by SetDimension().
G4bool G4HnInformation::GetIsLogAxis (G4int axis) const inline
Definition at line 184 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 184 of file G4HnInformation.hh
References fIsLogAxis.
Referenced by G4PlotManager::PlotAndWrite().
G4String G4HnInformation::GetName (void) const inline
Definition at line 178 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 178 of file G4HnInformation.hh
References fName.
Referenced by G4PlotManager::PlotAndWrite().
G4bool G4HnInformation::GetPlotting () const inline
Definition at line 193 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 193 of file G4HnInformation.hh
References fPlotting.
Referenced by G4PlotManager::PlotAndWrite().
void G4HnInformation::SetActivation (G4bool activation) inline
Definition at line 169 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 169 of file G4HnInformation.hh
References fActivation.
void G4HnInformation::SetAscii (G4bool ascii) inline
Definition at line 172 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 172 of file G4HnInformation.hh
References fAscii.
void G4HnInformation::SetDimension (G4int dimension, const G4String & unitName, const G4String & fcnName, G4BinScheme binScheme) inline
Definition at line 153 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 153 of file G4HnInformation.hh
References G4Analysis::GetFunction(), GetHnDimensionInformation(), and G4Analysis::GetUnitValue().
void G4HnInformation::SetIsLogAxis (G4int axis, G4bool isLog) inline
Definition at line 166 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 166 of file G4HnInformation.hh
References fIsLogAxis.
void G4HnInformation::SetPlotting (G4bool plotting) inline
Definition at line 175 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 175 of file G4HnInformation.hh
References fPlotting.
Member Data Documentation
G4bool G4HnInformation::fActivation private
Definition at line 133 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 133 of file G4HnInformation.hh
Referenced by GetActivation(), and SetActivation().
G4bool G4HnInformation::fAscii private
Definition at line 134 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 134 of file G4HnInformation.hh
Referenced by GetAscii(), and SetAscii().
std::vector<G4HnDimensionInformation> G4HnInformation::fHnDimensionInformations private
Definition at line 131 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 131 of file G4HnInformation.hh
Referenced by AddDimension(), AddHnDimensionInformation(), fPlotting(), and GetHnDimensionInformation().
std::vector<G4bool> G4HnInformation::fIsLogAxis private
Definition at line 132 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 132 of file G4HnInformation.hh
Referenced by GetIsLogAxis(), and SetIsLogAxis().
G4String G4HnInformation::fName private
Definition at line 130 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 130 of file G4HnInformation.hh
Referenced by GetName().
G4bool G4HnInformation::fPlotting private
Definition at line 135 of file G4HnInformation.hh.
View newest version in sPHENIX GitHub at line 135 of file G4HnInformation.hh
Referenced by GetPlotting(), and SetPlotting().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4HnInformation.hh