ECCE @ EIC Software: TSPrimaryGeneratorAction Class Reference
TSPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/include/TSPrimaryGeneratorAction.hh>
Public Member Functions
TSPrimaryGeneratorAction ()
virtual ~TSPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fGun
Detailed Description
Definition at line 49 of file TSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 49 of file TSPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
TSPrimaryGeneratorAction::TSPrimaryGeneratorAction ()
Definition at line 54 of file TSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 54 of file TSPrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), CLHEP::MeV, and particle.
TSPrimaryGeneratorAction::~TSPrimaryGeneratorAction () virtual
Definition at line 70 of file TSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 70 of file TSPrimaryGeneratorAction.cc
Member Function Documentation
void TSPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 77 of file TSPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 77 of file TSPrimaryGeneratorAction.cc
References dir, G4UniformRand, TSDetectorConstruction::GetWorldDimensions(), TSDetectorConstruction::Instance(), CLHEP::Hep3Vector::mag(), pos(), TIMEMORY_AUTO_TIMER, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4ParticleGun* TSPrimaryGeneratorAction::fGun private
Definition at line 59 of file TSPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 59 of file TSPrimaryGeneratorAction.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/include/TSPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/ThreadsafeScorers/src/TSPrimaryGeneratorAction.cc