ECCE @ EIC Software: G4FastVector< Type, N > Class Template Reference
G4FastVector< Type, N > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4FastVector.hh>
Public Member Functions
G4FastVector ()
~G4FastVector ()
Type * operator[] (G4int anIndex) const
void Initialize (G4int items)
void SetElement (G4int anIndex, Type *anElement)
Private Attributes
Type * theArray [N]
Type ** ptr
Detailed Description
template<class Type, G4int N>
class G4FastVector< Type, N >
Definition at line 42 of file G4FastVector.hh.
View newest version in sPHENIX GitHub at line 42 of file G4FastVector.hh
Constructor & Destructor Documentation
template<class Type, G4int N> G4FastVector< Type, N >::G4FastVector () inline
Definition at line 49 of file G4FastVector.hh.
View newest version in sPHENIX GitHub at line 49 of file G4FastVector.hh
References G4FastVector< Type, N >::ptr, and G4FastVector< Type, N >::theArray.
template<class Type, G4int N> G4FastVector< Type, N >::~G4FastVector () inline
Definition at line 51 of file G4FastVector.hh.
View newest version in sPHENIX GitHub at line 51 of file G4FastVector.hh
References G4FastVector< Type, N >::ptr, and G4FastVector< Type, N >::theArray.
Member Function Documentation
template<class Type, G4int N> void G4FastVector< Type, N >::Initialize (G4int items) inline
Definition at line 62 of file G4FastVector.hh.
View newest version in sPHENIX GitHub at line 62 of file G4FastVector.hh
References N, G4FastVector< Type, N >::ptr, and G4FastVector< Type, N >::theArray.
Referenced by G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4RPGInelastic::CalculateMomenta(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4RPGReaction::NuclearReaction(), G4RPGTwoCluster::ReactionStage(), G4RPGNeutronInelastic::SlowNeutron(), and G4RPGProtonInelastic::SlowProton().
template<class Type, G4int N> Type* G4FastVector< Type, N >::operator[] (G4int anIndex) const inline
Definition at line 56 of file G4FastVector.hh.
View newest version in sPHENIX GitHub at line 56 of file G4FastVector.hh
References G4FastVector< Type, N >::ptr.
template<class Type, G4int N> void G4FastVector< Type, N >::SetElement (G4int anIndex, Type * anElement) inline
Definition at line 75 of file G4FastVector.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FastVector.hh
References G4FastVector< Type, N >::ptr.
Referenced by G4RPGReaction::AddBlackTrackParticles(), G4ParticleChangeForRadDecay::AddSecondary(), G4VParticleChange::AddSecondary(), G4RPGInelastic::CalculateMomenta(), G4RPGXiMinusInelastic::Cascade(), G4RPGAntiSigmaPlusInelastic::Cascade(), G4RPGAntiSigmaMinusInelastic::Cascade(), G4RPGAntiXiMinusInelastic::Cascade(), G4RPGAntiXiZeroInelastic::Cascade(), G4RPGXiZeroInelastic::Cascade(), G4VParticleChange::G4VParticleChange(), G4RPGPiMinusInelastic::InitialCollision(), G4RPGPiPlusInelastic::InitialCollision(), G4RPGNeutronInelastic::InitialCollision(), G4RPGProtonInelastic::InitialCollision(), G4RPGReaction::NuclearReaction(), G4ParticleChangeForDecay::operator=(), G4ParticleChange::operator=(), G4ParticleChangeForGamma::operator=(), G4VParticleChange::operator=(), G4ParticleChangeForLoss::operator=(), G4RPGStrangeProduction::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), and G4RPGInelastic::SetUpPions().
Member Data Documentation
template<class Type, G4int N> Type** G4FastVector< Type, N >::ptr private
Definition at line 85 of file G4FastVector.hh.
View newest version in sPHENIX GitHub at line 85 of file G4FastVector.hh
Referenced by G4FastVector< Type, N >::G4FastVector(), G4FastVector< Type, N >::Initialize(), G4FastVector< Type, N >::operator[](), G4FastVector< Type, N >::SetElement(), and G4FastVector< Type, N >::~G4FastVector().
template<class Type, G4int N> Type* G4FastVector< Type, N >::theArray[N] private
Definition at line 84 of file G4FastVector.hh.
View newest version in sPHENIX GitHub at line 84 of file G4FastVector.hh
Referenced by G4FastVector< Type, N >::G4FastVector(), G4FastVector< Type, N >::Initialize(), and G4FastVector< Type, N >::~G4FastVector().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/management/include/G4FastVector.hh