ECCE @ EIC Software: F02DetectorMessenger Class Reference
F02DetectorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02DetectorMessenger.hh>
Public Member Functions
F02DetectorMessenger (F02DetectorConstruction *)
virtual ~F02DetectorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
F02DetectorConstruction * fDetector
G4UIdirectory * fDetDir
G4UIcmdWithAString * fAbsMaterCmd
G4UIcmdWithADoubleAndUnit * fAbsThickCmd
G4UIcmdWithADoubleAndUnit * fAbsRadCmd
G4UIcmdWithADoubleAndUnit * fAbsZposCmd
G4UIcmdWithAString * fWorldMaterCmd
G4UIcmdWithADoubleAndUnit * fWorldZCmd
G4UIcmdWithADoubleAndUnit * fWorldRCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 50 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 50 of file F02DetectorMessenger.hh
Constructor & Destructor Documentation
F02DetectorMessenger::F02DetectorMessenger (F02DetectorConstruction * det)
Definition at line 44 of file F02DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 44 of file F02DetectorMessenger.cc
References G4UIcommand::AvailableForStates(), fAbsMaterCmd, fAbsRadCmd, fAbsThickCmd, fAbsZposCmd, fDetDir, fWorldMaterCmd, fWorldRCmd, fWorldZCmd, G4State_Idle, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcommand::SetToBeBroadcasted().
F02DetectorMessenger::~F02DetectorMessenger () virtual
Definition at line 115 of file F02DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 115 of file F02DetectorMessenger.cc
References fAbsMaterCmd, fAbsRadCmd, fAbsThickCmd, fAbsZposCmd, fDetDir, fWorldMaterCmd, fWorldRCmd, and fWorldZCmd.
Member Function Documentation
void F02DetectorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 129 of file F02DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 129 of file F02DetectorMessenger.cc
References fAbsMaterCmd, fAbsRadCmd, fAbsThickCmd, fAbsZposCmd, fDetector, fWorldMaterCmd, fWorldRCmd, fWorldZCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), F02DetectorConstruction::SetAbsorberMaterial(), F02DetectorConstruction::SetAbsorberRadius(), F02DetectorConstruction::SetAbsorberThickness(), F02DetectorConstruction::SetAbsorberZpos(), F02DetectorConstruction::SetWorldMaterial(), F02DetectorConstruction::SetWorldSizeR(), and F02DetectorConstruction::SetWorldSizeZ().
Member Data Documentation
G4UIcmdWithAString* F02DetectorMessenger::fAbsMaterCmd private
Definition at line 64 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file F02DetectorMessenger.hh
Referenced by F02DetectorMessenger(), SetNewValue(), and ~F02DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F02DetectorMessenger::fAbsRadCmd private
Definition at line 66 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file F02DetectorMessenger.hh
Referenced by F02DetectorMessenger(), SetNewValue(), and ~F02DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F02DetectorMessenger::fAbsThickCmd private
Definition at line 65 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file F02DetectorMessenger.hh
Referenced by F02DetectorMessenger(), SetNewValue(), and ~F02DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F02DetectorMessenger::fAbsZposCmd private
Definition at line 68 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file F02DetectorMessenger.hh
Referenced by F02DetectorMessenger(), SetNewValue(), and ~F02DetectorMessenger().
G4UIdirectory* F02DetectorMessenger::fDetDir private
Definition at line 62 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file F02DetectorMessenger.hh
Referenced by F02DetectorMessenger(), and ~F02DetectorMessenger().
F02DetectorConstruction* F02DetectorMessenger::fDetector private
Definition at line 60 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file F02DetectorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* F02DetectorMessenger::fWorldMaterCmd private
Definition at line 70 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file F02DetectorMessenger.hh
Referenced by F02DetectorMessenger(), SetNewValue(), and ~F02DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F02DetectorMessenger::fWorldRCmd private
Definition at line 72 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file F02DetectorMessenger.hh
Referenced by F02DetectorMessenger(), SetNewValue(), and ~F02DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F02DetectorMessenger::fWorldZCmd private
Definition at line 71 of file F02DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file F02DetectorMessenger.hh
Referenced by F02DetectorMessenger(), SetNewValue(), and ~F02DetectorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02DetectorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field02/src/F02DetectorMessenger.cc