ECCE @ EIC Software: G02PrimaryGeneratorAction Class Reference
G02PrimaryGeneratorAction Class Reference
Primary generator action used in GDML read/write example.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/include/G02PrimaryGeneratorAction.hh>
Public Member Functions
G02PrimaryGeneratorAction ()
~G02PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * fParticleGun
G4ParticleTable * fParticleTable
Detailed Description
Primary generator action used in GDML read/write example.
Definition at line 50 of file G02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 50 of file G02PrimaryGeneratorAction.hh
Constructor & Destructor Documentation
G02PrimaryGeneratorAction::G02PrimaryGeneratorAction ()
Definition at line 43 of file G02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 43 of file G02PrimaryGeneratorAction.cc
References G4ParticleTable::FindParticle(), fParticleGun, fParticleTable, G4ParticleTable::GetParticleTable(), MeV, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), and G4VPrimaryGenerator::SetParticlePosition().
G02PrimaryGeneratorAction::~G02PrimaryGeneratorAction ()
Definition at line 70 of file G02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 70 of file G02PrimaryGeneratorAction.cc
References fParticleGun.
Member Function Documentation
void G02PrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 77 of file G02PrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 77 of file G02PrimaryGeneratorAction.cc
References fParticleGun, and G4ParticleGun::GeneratePrimaryVertex().
Member Data Documentation
G4ParticleGun* G02PrimaryGeneratorAction::fParticleGun private
Definition at line 65 of file G02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file G02PrimaryGeneratorAction.hh
Referenced by G02PrimaryGeneratorAction(), GeneratePrimaries(), and ~G02PrimaryGeneratorAction().
G4ParticleTable* G02PrimaryGeneratorAction::fParticleTable private
Definition at line 66 of file G02PrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 66 of file G02PrimaryGeneratorAction.hh
Referenced by G02PrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/include/G02PrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/src/G02PrimaryGeneratorAction.cc