ECCE @ EIC Software: G4LogicalVolumeStore Class Reference
G4LogicalVolumeStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4LogicalVolumeStore.hh>
Public Member Functions
G4LogicalVolume * GetVolume (const G4String &name, G4bool verbose=true) const
virtual ~G4LogicalVolumeStore ()
Static Public Member Functions
static void Register (G4LogicalVolume *pVolume)
static void DeRegister (G4LogicalVolume *pVolume)
static G4LogicalVolumeStore * GetInstance ()
static void SetNotifier (G4VStoreNotifier *pNotifier)
static void Clean ()
Protected Member Functions
G4LogicalVolumeStore ()
Static Private Attributes
static G4LogicalVolumeStore * fgInstance = nullptr
static G4ThreadLocal
G4VStoreNotifier * fgNotifier = nullptr
static G4ThreadLocal G4bool locked = false
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 58 of file G4LogicalVolumeStore.hh.
View newest version in sPHENIX GitHub at line 58 of file G4LogicalVolumeStore.hh
Constructor & Destructor Documentation
G4LogicalVolumeStore::~G4LogicalVolumeStore () virtual
Definition at line 58 of file G4LogicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 58 of file G4LogicalVolumeStore.cc
References Clean(), and G4LogicalVolume::Clean().
G4LogicalVolumeStore::G4LogicalVolumeStore () protected
Definition at line 48 of file G4LogicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 48 of file G4LogicalVolumeStore.cc
Member Function Documentation
void G4LogicalVolumeStore::Clean () static
Definition at line 68 of file G4LogicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 68 of file G4LogicalVolumeStore.cc
References fgNotifier, G4cout, G4endl, GetInstance(), G4GeometryManager::IsGeometryClosed(), locked, G4VNotifier::NotifyDeRegistration(), and pos().
Referenced by PHG4PhenixDetector::Construct(), F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), G4RunManager::ReinitializeGeometry(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), XrayFluoDetectorConstruction::UpdateGeometry(), and ~G4LogicalVolumeStore().
void G4LogicalVolumeStore::DeRegister (G4LogicalVolume * pVolume) static
Definition at line 133 of file G4LogicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 133 of file G4LogicalVolumeStore.cc
References fgNotifier, GetInstance(), locked, and G4VNotifier::NotifyDeRegistration().
Referenced by G4LogicalVolume::~G4LogicalVolume().
G4LogicalVolumeStore * G4LogicalVolumeStore::GetInstance (void) static
Definition at line 176 of file G4LogicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 176 of file G4LogicalVolumeStore.cc
References fgInstance.
Referenced by G4GeometryManager::BuildOptimisations(), G4RunManagerKernel::CheckRegularGeometry(), checkVol(), Clean(), G4VUserDetectorConstruction::CloneF(), G4VUserDetectorConstruction::CloneSD(), PHG4PhenixDetector::Construct(), GB06ParallelWorldForSlices::Construct(), F04DetectorConstruction::Construct(), WLSDetectorConstruction::Construct(), DetectorConstruction::ConstructCalorimeter(), F02DetectorConstruction::ConstructCalorimeter(), F01DetectorConstruction::ConstructCalorimeter(), F03DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), GB06ParallelWorldForSlices::ConstructSD(), GB05DetectorConstruction::ConstructSDandField(), GB07DetectorConstruction::ConstructSDandField(), GB01DetectorConstruction::ConstructSDandField(), GB02DetectorConstruction::ConstructSDandField(), GB06DetectorConstruction::ConstructSDandField(), GB04DetectorConstruction::ConstructSDandField(), RMC01DetectorConstruction::ConstructSimpleGeometry(), DetectorConstruction::ConstructVolumes(), ElectronBenchmarkDetector::CreateGeometry(), DetectorConstruction::DefineVolumes(), G4GeometryManager::DeleteOptimisations(), DeRegister(), G4RadioactiveDecayBase::DeselectAVolume(), G4RadioactiveDecay::DeselectAVolume(), B2PrimaryGeneratorAction::GeneratePrimaries(), B4PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), DetectorConstruction::GetAbsorberMaterial(), DicomIntersectVolume::GetLogicalVolumes(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4Region::GetParentRegion(), G4GDMLReadStructure::GetVolume(), GetVolume(), G4GDMLParser::ImportRegions(), main(), Register(), G4RunManager::ReinitializeGeometry(), G4BlineTracer::ResetChordFinders(), G4RadioactiveDecayBase::SelectAllVolumes(), G4RadioactiveDecay::SelectAllVolumes(), G4RadioactiveDecayBase::SelectAVolume(), G4RadioactiveDecay::SelectAVolume(), G4VVisCommandGeometrySet::Set(), G4VisCommandGeometryList::SetNewValue(), G4GDMLMessenger::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), SetNotifier(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), G4ScoringRealWorld::SetupGeometry(), CexmcSetup::SetupSpecialVolumes(), G4GDMLRead::StripNames(), G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster(), and F04SteppingAction::UserSteppingAction().
G4LogicalVolume * G4LogicalVolumeStore::GetVolume (const G4String & name, G4bool verbose = true) const
Definition at line 154 of file G4LogicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 154 of file G4LogicalVolumeStore.cc
References G4endl, G4Exception(), GetInstance(), JustWarning, and message().
Referenced by GB06ParallelWorldForSlices::Construct(), GB06ParallelWorldForSlices::ConstructSD(), GB05DetectorConstruction::ConstructSDandField(), GB07DetectorConstruction::ConstructSDandField(), GB06DetectorConstruction::ConstructSDandField(), GB01DetectorConstruction::ConstructSDandField(), GB02DetectorConstruction::ConstructSDandField(), GB04DetectorConstruction::ConstructSDandField(), B2PrimaryGeneratorAction::GeneratePrimaries(), B4PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), DetectorConstruction::GetAbsorberMaterial(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4GDMLReadStructure::GetVolume(), G4GDMLParser::ImportRegions(), G4GDMLMessenger::SetNewValue(), and F04SteppingAction::UserSteppingAction().
void G4LogicalVolumeStore::Register (G4LogicalVolume * pVolume) static
Definition at line 123 of file G4LogicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 123 of file G4LogicalVolumeStore.cc
References fgNotifier, GetInstance(), and G4VNotifier::NotifyRegistration().
Referenced by G4LogicalVolume::G4LogicalVolume().
void G4LogicalVolumeStore::SetNotifier (G4VStoreNotifier * pNotifier) static
Definition at line 113 of file G4LogicalVolumeStore.cc.
View newest version in sPHENIX GitHub at line 113 of file G4LogicalVolumeStore.cc
References fgNotifier, and GetInstance().
Member Data Documentation
G4LogicalVolumeStore * G4LogicalVolumeStore::fgInstance = nullptr static private
Definition at line 86 of file G4LogicalVolumeStore.hh.
View newest version in sPHENIX GitHub at line 86 of file G4LogicalVolumeStore.hh
Referenced by GetInstance().
G4ThreadLocal G4VStoreNotifier * G4LogicalVolumeStore::fgNotifier = nullptr static private
Definition at line 87 of file G4LogicalVolumeStore.hh.
View newest version in sPHENIX GitHub at line 87 of file G4LogicalVolumeStore.hh
Referenced by Clean(), DeRegister(), Register(), and SetNotifier().
G4ThreadLocal G4bool G4LogicalVolumeStore::locked = false static private
Definition at line 88 of file G4LogicalVolumeStore.hh.
View newest version in sPHENIX GitHub at line 88 of file G4LogicalVolumeStore.hh
Referenced by Clean(), and DeRegister().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4LogicalVolumeStore.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4LogicalVolumeStore.cc