ECCE @ EIC Software: WLSStackingAction Class Reference
WLSStackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSStackingAction.hh>
Public Member Functions
WLSStackingAction ()
virtual ~WLSStackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Private Attributes
G4int fPhotonCounter
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 40 of file WLSStackingAction.hh.
View newest version in sPHENIX GitHub at line 40 of file WLSStackingAction.hh
Constructor & Destructor Documentation
WLSStackingAction::WLSStackingAction ()
Definition at line 41 of file WLSStackingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file WLSStackingAction.cc
WLSStackingAction::~WLSStackingAction () virtual
Definition at line 45 of file WLSStackingAction.cc.
View newest version in sPHENIX GitHub at line 45 of file WLSStackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack WLSStackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 50 of file WLSStackingAction.cc.
View newest version in sPHENIX GitHub at line 50 of file WLSStackingAction.cc
References fPhotonCounter, fUrgent, G4Track::GetDefinition(), G4Track::GetParentID(), and G4OpticalPhoton::OpticalPhotonDefinition().
void WLSStackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 70 of file WLSStackingAction.cc.
View newest version in sPHENIX GitHub at line 70 of file WLSStackingAction.cc
void WLSStackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 77 of file WLSStackingAction.cc.
View newest version in sPHENIX GitHub at line 77 of file WLSStackingAction.cc
References fPhotonCounter.
Member Data Documentation
G4int WLSStackingAction::fPhotonCounter private
Definition at line 55 of file WLSStackingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file WLSStackingAction.hh
Referenced by ClassifyNewTrack(), and PrepareNewEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSStackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSStackingAction.cc