ECCE @ EIC Software: G4coutFormatters Namespace Reference
G4coutFormatters Namespace Reference
Namespaces
namespace ID
Typedefs
using SetupStyle_f = std::function< G4int(G4coutDestination *)>
using String_V = std::vector< G4String >
Functions
String_V Names ()
G4int HandleStyle (G4coutDestination *dest, const G4String &style)
void SetMasterStyle (const G4String &)
G4String GetMasterStyle ()
void SetupStyleGlobally (const G4String &news)
void RegisterNewStyle (const G4String &name, SetupStyle_f &formatter)
Typedef Documentation
using G4coutFormatters::SetupStyle_f = typedef std::function<G4int(G4coutDestination*)>
Definition at line 74 of file G4coutFormatters.hh.
View newest version in sPHENIX GitHub at line 74 of file G4coutFormatters.hh
using G4coutFormatters::String_V = typedef std::vector<G4String>
Definition at line 76 of file G4coutFormatters.hh.
View newest version in sPHENIX GitHub at line 76 of file G4coutFormatters.hh
Function Documentation
G4String G4coutFormatters::GetMasterStyle ()
Definition at line 123 of file G4coutFormatters.cc.
View newest version in sPHENIX GitHub at line 123 of file G4coutFormatters.cc
G4int G4coutFormatters::HandleStyle (G4coutDestination * dest, const G4String & style)
Definition at line 147 of file G4coutFormatters.cc.
View newest version in sPHENIX GitHub at line 147 of file G4coutFormatters.cc
Referenced by SetupStyleGlobally().
String_V G4coutFormatters::Names ()
Definition at line 137 of file G4coutFormatters.cc.
View newest version in sPHENIX GitHub at line 137 of file G4coutFormatters.cc
void G4coutFormatters::RegisterNewStyle (const G4String & name, SetupStyle_f & formatter)
Definition at line 153 of file G4coutFormatters.cc.
View newest version in sPHENIX GitHub at line 153 of file G4coutFormatters.cc
References G4Exception(), and JustWarning.
void G4coutFormatters::SetMasterStyle (const G4String & news)
Definition at line 118 of file G4coutFormatters.cc.
View newest version in sPHENIX GitHub at line 118 of file G4coutFormatters.cc
Referenced by SetupStyleGlobally().
void G4coutFormatters::SetupStyleGlobally (const G4String & news)
Definition at line 128 of file G4coutFormatters.cc.
View newest version in sPHENIX GitHub at line 128 of file G4coutFormatters.cc
References G4cerrbuf, G4coutbuf, HandleStyle(), G4strstreambuf::SetDestination(), and SetMasterStyle().