ECCE @ EIC Software: G4EzVolume Class Reference
G4EzVolume Class Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ezgeom/G4EzVolume.hh>
Public Member Functions
G4EzVolume ()
G4EzVolume (const G4String &aname)
~G4EzVolume ()
void CreateBoxVolume (G4Material *amaterial, G4double dx, G4double dy, G4double dz)
void CreateTubeVolume (G4Material *amaterial, G4double rmin, G4double rmax, G4double dz, G4double phi0=0., G4double dphi=360 *deg)
void CreateConeVolume (G4Material *amaterial, G4double rmin1, G4double rmax1, G4double rmin2, G4double rmax2, G4double dz, G4double phi0=0., G4double dphi=360.*deg)
void CreateSphereVolume (G4Material *amaterial, G4double rmin, G4double rmax, G4double phi0=0., G4double dphi=360.*deg, G4double theta0=0., G4double dtheta=180.*deg)
void CreateOrbVolume (G4Material *amaterial, G4double rmax)
G4VPhysicalVolume * PlaceIt (const G4ThreeVector &pos, G4int ncopy=0, G4EzVolume *parent=0)
G4VPhysicalVolume * PlaceIt (const G4Transform3D &transform, G4int ncopy=0, G4EzVolume *parent=0)
G4VPhysicalVolume * ReplicateIt (G4EzVolume *parent, EAxis pAxis, G4int nReplicas, G4double width, G4double offset=0)
G4ThreeVector VoxelizeIt (G4int nx, G4int ny, G4int nz)
void SetSensitiveDetector (G4VSensitiveDetector *asd)
const G4String & GetName () const
void SetSolid (G4VSolid *asolid)
const G4VSolid * GetSolid () const
void SetMaterial (G4Material *amaterial)
G4Material * GetMaterial () const
G4int GetNofPlacements () const
void SetVisibility (G4bool qvisible)
void SetColor (const G4Color &color)
void SetColor (G4double red, G4double green, G4double blue)
Protected Attributes
G4String name
G4VSolid * solid
G4LogicalVolume * lv
G4LogicalVolume * lvsub
G4VisAttributes * va
G4int nplacement
Detailed Description
Definition at line 51 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 51 of file G4EzVolume.hh
Constructor & Destructor Documentation
G4EzVolume::G4EzVolume ()
Definition at line 53 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 53 of file G4EzVolume.cc
G4EzVolume::G4EzVolume (const G4String & aname)
Definition at line 64 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 64 of file G4EzVolume.cc
G4EzVolume::~G4EzVolume ()
Definition at line 73 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 73 of file G4EzVolume.cc
Member Function Documentation
void G4EzVolume::CreateBoxVolume (G4Material * amaterial, G4double dx, G4double dy, G4double dz)
Definition at line 80 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 80 of file G4EzVolume.cc
References G4cout, and G4endl.
Referenced by BOOST_PYTHON_MODULE().
void G4EzVolume::CreateConeVolume (G4Material * amaterial, G4double rmin1, G4double rmax1, G4double rmin2, G4double rmax2, G4double dz, G4double phi0 = 0., G4double dphi = 360.*deg)
Definition at line 121 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 121 of file G4EzVolume.cc
References G4cout, and G4endl.
Referenced by BOOST_PYTHON_MODULE().
void G4EzVolume::CreateOrbVolume (G4Material * amaterial, G4double rmax)
Definition at line 167 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 167 of file G4EzVolume.cc
References G4cout, and G4endl.
Referenced by BOOST_PYTHON_MODULE().
void G4EzVolume::CreateSphereVolume (G4Material * amaterial, G4double rmin, G4double rmax, G4double phi0 = 0., G4double dphi = 360.*deg, G4double theta0 = 0., G4double dtheta = 180.*deg)
Definition at line 145 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 145 of file G4EzVolume.cc
References G4cout, and G4endl.
Referenced by BOOST_PYTHON_MODULE().
void G4EzVolume::CreateTubeVolume (G4Material * amaterial, G4double rmin, G4double rmax, G4double dz, G4double phi0 = 0., G4double dphi = 360*deg)
Definition at line 100 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 100 of file G4EzVolume.cc
References G4cout, and G4endl.
Referenced by BOOST_PYTHON_MODULE().
G4Material * G4EzVolume::GetMaterial () const inline
Definition at line 142 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 142 of file G4EzVolume.hh
Referenced by BOOST_PYTHON_MODULE().
const G4String & G4EzVolume::GetName () const inline
Definition at line 130 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 130 of file G4EzVolume.hh
G4int G4EzVolume::GetNofPlacements () const inline
Definition at line 148 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 148 of file G4EzVolume.hh
const G4VSolid * G4EzVolume::GetSolid () const inline
Definition at line 134 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 134 of file G4EzVolume.hh
Referenced by BOOST_PYTHON_MODULE().
G4VPhysicalVolume* G4EzVolume::PlaceIt (const G4ThreeVector & pos, G4int ncopy = 0, G4EzVolume * parent = 0)
G4VPhysicalVolume* G4EzVolume::PlaceIt (const G4Transform3D & transform, G4int ncopy = 0, G4EzVolume * parent = 0)
G4VPhysicalVolume * G4EzVolume::ReplicateIt (G4EzVolume * parent, EAxis pAxis, G4int nReplicas, G4double width, G4double offset = 0)
Definition at line 236 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 236 of file G4EzVolume.cc
References G4cout, and G4endl.
Referenced by BOOST_PYTHON_MODULE().
void G4EzVolume::SetColor (const G4Color & color) inline
Definition at line 155 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 155 of file G4EzVolume.hh
void G4EzVolume::SetColor (G4double red, G4double green, G4double blue) inline
Definition at line 160 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 160 of file G4EzVolume.hh
void G4EzVolume::SetMaterial (G4Material * amaterial) inline
Definition at line 136 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 136 of file G4EzVolume.hh
References EmPlot::SetMaterial().
Referenced by BOOST_PYTHON_MODULE().
void G4EzVolume::SetSensitiveDetector (G4VSensitiveDetector * asd)
Definition at line 300 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 300 of file G4EzVolume.cc
Referenced by BOOST_PYTHON_MODULE().
void G4EzVolume::SetSolid (G4VSolid * asolid) inline
Definition at line 132 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 132 of file G4EzVolume.hh
Referenced by BOOST_PYTHON_MODULE().
void G4EzVolume::SetVisibility (G4bool qvisible) inline
Definition at line 150 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 150 of file G4EzVolume.hh
Referenced by BOOST_PYTHON_MODULE().
G4ThreeVector G4EzVolume::VoxelizeIt (G4int nx, G4int ny, G4int nz)
Definition at line 256 of file G4EzVolume.cc.
View newest version in sPHENIX GitHub at line 256 of file G4EzVolume.cc
References dx, dy, dz, G4cout, G4endl, and kXAxis.
Referenced by BOOST_PYTHON_MODULE().
Member Data Documentation
G4LogicalVolume* G4EzVolume::lv protected
Definition at line 56 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 56 of file G4EzVolume.hh
G4LogicalVolume* G4EzVolume::lvsub protected
Definition at line 57 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 57 of file G4EzVolume.hh
G4String G4EzVolume::name protected
Definition at line 54 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 54 of file G4EzVolume.hh
Referenced by mcscore.MCParticle::printout().
G4int G4EzVolume::nplacement protected
Definition at line 59 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 59 of file G4EzVolume.hh
G4VSolid* G4EzVolume::solid protected
Definition at line 55 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 55 of file G4EzVolume.hh
G4VisAttributes* G4EzVolume::va protected
Definition at line 58 of file G4EzVolume.hh.
View newest version in sPHENIX GitHub at line 58 of file G4EzVolume.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ezgeom/G4EzVolume.hh
geant4/tree/geant4-10.6-release/environments/g4py/tests/g4pytest/ezgeom/G4EzVolume.cc