ECCE @ EIC Software: G4eeCrossSections Class Reference
G4eeCrossSections Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeCrossSections.hh>
Public Member Functions
G4eeCrossSections ()
virtual ~G4eeCrossSections ()
G4double CrossSection2pi (G4double)
G4double CrossSection3pi (G4double)
G4double CrossSectionPi0G (G4double)
G4double CrossSectionEtaG (G4double)
G4double CrossSection2Kcharged (G4double)
G4double CrossSection2Kneutral (G4double)
std::complex< G4double > DpRho (G4double e)
Private Member Functions
void Initialise ()
G4double Width2p (G4double s_inv, G4double mres, G4double gconst, G4double br, G4double mp)
G4double Width3p (G4double s_inv, G4double mres, G4double gconst, G4double br)
G4double PhaseSpace3p (G4double e)
G4double WidthPg (G4double s_inv, G4double mres, G4double gconst, G4double br, G4double mp)
G4double WidthRho (G4double e)
G4double WidthOm (G4double e)
G4double WidthPhi (G4double e)
std::complex< G4double > DpOm (G4double e)
std::complex< G4double > DpPhi (G4double e)
G4eeCrossSections & operator= (const G4eeCrossSections &right)=delete
G4eeCrossSections (const G4eeCrossSections &)=delete
Private Attributes
G4double MsPi
G4double MsPi0
G4double MsEta
G4double MsEtap
G4double MsKs
G4double MsKc
G4double MsRho
G4double MsOm
G4double MsF0
G4double MsA0
G4double MsPhi
G4double MsK892
G4double MsK0892
G4double GRho
G4double GOm
G4double GPhi
G4double GK892
G4double GK0892
G4double PhRho
G4double PhOm
G4double PhPhi
G4double PhRhoPi
G4double BrRhoPiG
G4double BrRhoPi0G
G4double BrRhoEtaG
G4double BrRhoEe
G4double BrOm3Pi
G4double BrOmPi0G
G4double BrOmEtaG
G4double BrOm2Pi
G4double PhOm2Pi
G4double BrOmEe
G4double BrPhi2Kc
G4double BrPhiKsKl
G4double BrPhi3Pi
G4double BrPhiPi0G
G4double BrPhiEtaG
G4double BrPhi2Pi
G4double PhPhi2Pi
G4double BrPhiEe
G4double MeVnb
G4double Alpha
G4double AOmRho
G4double ARhoPRho
G4double cterm
G4double mssig
G4double gsig
G4double brsigpipi
G4double msrho1450
G4double msrho1700
G4double grho1450
G4double grho1700
G4double arhoompi0
G4double arho1450ompi0
G4double arho1700ompi0
G4double phrhoompi0
G4double phrho1450ompi0
G4double phrho1700ompi0
G4double aomrhopi0
G4double phomrhopi0
G4double arhopi0pi0g
G4double aompi0pi0g
G4double phrhopi0pi0g
G4double phompi0pi0g
G4double brrho1450ompi0
G4double brrho1450pipi
G4double brrho1700ompi0
G4double brrho1700pipi
G4double aphirhopi0
G4double phphirhopi0
G4double arhosigg
G4double phrhosigg
G4double aomsigg
G4double phomsigg
G4double MsRho3
G4double MsOm3
G4double MsPhi3
G4PhysicsVector * ph3p
Detailed Description
Definition at line 57 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 57 of file G4eeCrossSections.hh
Constructor & Destructor Documentation
G4eeCrossSections::G4eeCrossSections ()
Definition at line 67 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 67 of file G4eeCrossSections.cc
G4eeCrossSections::~G4eeCrossSections () virtual
Definition at line 74 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 74 of file G4eeCrossSections.cc
G4eeCrossSections::G4eeCrossSections (const G4eeCrossSections &) private delete
Member Function Documentation
G4double G4eeCrossSections::CrossSection2Kcharged (G4double e)
Definition at line 276 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 276 of file G4eeCrossSections.cc
References Acts::VectorHelpers::cross(), e, norm, and pi.
Referenced by G4ee2KChargedModel::ComputeCrossSection().
G4double G4eeCrossSections::CrossSection2Kneutral (G4double e)
Definition at line 291 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 291 of file G4eeCrossSections.cc
References Acts::VectorHelpers::cross(), e, norm, and pi.
Referenced by G4ee2KNeutralModel::ComputeCrossSection().
G4double G4eeCrossSections::CrossSection2pi (G4double e)
Definition at line 192 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 192 of file G4eeCrossSections.cc
References Acts::VectorHelpers::cross(), e, norm, and pi.
Referenced by G4eeToTwoPiModel::ComputeCrossSection().
G4double G4eeCrossSections::CrossSection3pi (G4double e)
Definition at line 215 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 215 of file G4eeCrossSections.cc
References Acts::VectorHelpers::cross(), e, norm, and pi.
Referenced by G4eeTo3PiModel::ComputeCrossSection().
G4double G4eeCrossSections::CrossSectionEtaG (G4double e)
Definition at line 255 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 255 of file G4eeCrossSections.cc
References Acts::VectorHelpers::cross(), e, norm, and pi.
Referenced by G4eeToPGammaModel::ComputeCrossSection().
G4double G4eeCrossSections::CrossSectionPi0G (G4double e)
Definition at line 234 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 234 of file G4eeCrossSections.cc
References Acts::VectorHelpers::cross(), e, norm, and pi.
Referenced by G4eeToPGammaModel::ComputeCrossSection().
complex< G4double > G4eeCrossSections::DpOm (G4double e) private
Definition at line 401 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 401 of file G4eeCrossSections.cc
References d.
complex< G4double > G4eeCrossSections::DpPhi (G4double e) private
Definition at line 409 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 409 of file G4eeCrossSections.cc
References d.
complex< G4double > G4eeCrossSections::DpRho (G4double e)
Definition at line 393 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 393 of file G4eeCrossSections.cc
References d.
Referenced by G4eeTo3PiModel::SampleSecondaries().
void G4eeCrossSections::Initialise () private
Definition at line 79 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 79 of file G4eeCrossSections.cc
References Alpha, degree, G4Eta::Eta(), source.hepunit::fine_structure_const, G4ParticleDefinition::GetPDGMass(), G4KaonPlus::KaonPlus(), G4KaonZeroLong::KaonZeroLong(), MeV, nanobarn, pi, G4PionPlus::PionPlus(), and G4PionZero::PionZero().
G4eeCrossSections& G4eeCrossSections::operator= (const G4eeCrossSections & right) private delete
G4double G4eeCrossSections::PhaseSpace3p (G4double e) private
Definition at line 329 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 329 of file G4eeCrossSections.cc
References MeV, x, and y.
G4double G4eeCrossSections::Width2p (G4double s_inv, G4double mres, G4double gconst, G4double br, G4double mp) private
Definition at line 306 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 306 of file G4eeCrossSections.cc
References f, and G4InuclParticleNames::s0.
G4double G4eeCrossSections::Width3p (G4double s_inv, G4double mres, G4double gconst, G4double br) private
Definition at line 318 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 318 of file G4eeCrossSections.cc
References w, and x.
G4double G4eeCrossSections::WidthOm (G4double e) private
Definition at line 366 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 366 of file G4eeCrossSections.cc
References e, and w.
G4double G4eeCrossSections::WidthPg (G4double s_inv, G4double mres, G4double gconst, G4double br, G4double mp) private
Definition at line 346 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 346 of file G4eeCrossSections.cc
References f, and G4InuclParticleNames::s0.
G4double G4eeCrossSections::WidthPhi (G4double e) private
Definition at line 379 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 379 of file G4eeCrossSections.cc
References e, and w.
G4double G4eeCrossSections::WidthRho (G4double e) private
Definition at line 358 of file G4eeCrossSections.cc.
View newest version in sPHENIX GitHub at line 358 of file G4eeCrossSections.cc
References w.
Member Data Documentation
G4double G4eeCrossSections::Alpha private
Definition at line 115 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 115 of file G4eeCrossSections.hh
G4double G4eeCrossSections::aompi0pi0g private
Definition at line 120 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 120 of file G4eeCrossSections.hh
G4double G4eeCrossSections::AOmRho private
Definition at line 116 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 116 of file G4eeCrossSections.hh
G4double G4eeCrossSections::aomrhopi0 private
Definition at line 119 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 119 of file G4eeCrossSections.hh
G4double G4eeCrossSections::aomsigg private
Definition at line 123 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 123 of file G4eeCrossSections.hh
G4double G4eeCrossSections::aphirhopi0 private
Definition at line 122 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 122 of file G4eeCrossSections.hh
G4double G4eeCrossSections::arho1450ompi0 private
Definition at line 118 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 118 of file G4eeCrossSections.hh
G4double G4eeCrossSections::arho1700ompi0 private
Definition at line 118 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 118 of file G4eeCrossSections.hh
G4double G4eeCrossSections::arhoompi0 private
Definition at line 118 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 118 of file G4eeCrossSections.hh
G4double G4eeCrossSections::arhopi0pi0g private
Definition at line 120 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 120 of file G4eeCrossSections.hh
G4double G4eeCrossSections::ARhoPRho private
Definition at line 116 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 116 of file G4eeCrossSections.hh
G4double G4eeCrossSections::arhosigg private
Definition at line 123 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 123 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrOm2Pi private
Definition at line 113 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 113 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrOm3Pi private
Definition at line 112 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 112 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrOmEe private
Definition at line 113 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 113 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrOmEtaG private
Definition at line 113 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 113 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrOmPi0G private
Definition at line 113 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 113 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrPhi2Kc private
Definition at line 114 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 114 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrPhi2Pi private
Definition at line 115 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 115 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrPhi3Pi private
Definition at line 114 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 114 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrPhiEe private
Definition at line 115 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 115 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrPhiEtaG private
Definition at line 114 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 114 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrPhiKsKl private
Definition at line 114 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 114 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrPhiPi0G private
Definition at line 114 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 114 of file G4eeCrossSections.hh
G4double G4eeCrossSections::brrho1450ompi0 private
Definition at line 121 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 121 of file G4eeCrossSections.hh
G4double G4eeCrossSections::brrho1450pipi private
Definition at line 121 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 121 of file G4eeCrossSections.hh
G4double G4eeCrossSections::brrho1700ompi0 private
Definition at line 121 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 121 of file G4eeCrossSections.hh
G4double G4eeCrossSections::brrho1700pipi private
Definition at line 122 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 122 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrRhoEe private
Definition at line 112 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 112 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrRhoEtaG private
Definition at line 112 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 112 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrRhoPi0G private
Definition at line 112 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 112 of file G4eeCrossSections.hh
G4double G4eeCrossSections::BrRhoPiG private
Definition at line 112 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 112 of file G4eeCrossSections.hh
G4double G4eeCrossSections::brsigpipi private
Definition at line 116 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 116 of file G4eeCrossSections.hh
G4double G4eeCrossSections::cterm private
Definition at line 116 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 116 of file G4eeCrossSections.hh
G4double G4eeCrossSections::GK0892 private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::GK892 private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::GOm private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::GPhi private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::GRho private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::grho1450 private
Definition at line 117 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 117 of file G4eeCrossSections.hh
G4double G4eeCrossSections::grho1700 private
Definition at line 117 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 117 of file G4eeCrossSections.hh
G4double G4eeCrossSections::gsig private
Definition at line 116 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 116 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MeVnb private
Definition at line 115 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 115 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsA0 private
Definition at line 110 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 110 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsEta private
Definition at line 109 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsEtap private
Definition at line 109 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsF0 private
Definition at line 110 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 110 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsK0892 private
Definition at line 110 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 110 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsK892 private
Definition at line 110 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 110 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsKc private
Definition at line 109 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsKs private
Definition at line 109 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsOm private
Definition at line 109 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsOm3 private
Definition at line 125 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 125 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsPhi private
Definition at line 110 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 110 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsPhi3 private
Definition at line 125 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 125 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsPi private
Definition at line 109 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsPi0 private
Definition at line 109 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsRho private
Definition at line 109 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeCrossSections.hh
G4double G4eeCrossSections::msrho1450 private
Definition at line 117 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 117 of file G4eeCrossSections.hh
G4double G4eeCrossSections::msrho1700 private
Definition at line 117 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 117 of file G4eeCrossSections.hh
G4double G4eeCrossSections::MsRho3 private
Definition at line 125 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 125 of file G4eeCrossSections.hh
G4double G4eeCrossSections::mssig private
Definition at line 116 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 116 of file G4eeCrossSections.hh
G4PhysicsVector* G4eeCrossSections::ph3p private
Definition at line 127 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 127 of file G4eeCrossSections.hh
G4double G4eeCrossSections::PhOm private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::PhOm2Pi private
Definition at line 113 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 113 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phompi0pi0g private
Definition at line 120 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 120 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phomrhopi0 private
Definition at line 119 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 119 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phomsigg private
Definition at line 123 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 123 of file G4eeCrossSections.hh
G4double G4eeCrossSections::PhPhi private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::PhPhi2Pi private
Definition at line 115 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 115 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phphirhopi0 private
Definition at line 122 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 122 of file G4eeCrossSections.hh
G4double G4eeCrossSections::PhRho private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phrho1450ompi0 private
Definition at line 119 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 119 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phrho1700ompi0 private
Definition at line 119 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 119 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phrhoompi0 private
Definition at line 118 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 118 of file G4eeCrossSections.hh
G4double G4eeCrossSections::PhRhoPi private
Definition at line 111 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phrhopi0pi0g private
Definition at line 120 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 120 of file G4eeCrossSections.hh
G4double G4eeCrossSections::phrhosigg private
Definition at line 123 of file G4eeCrossSections.hh.
View newest version in sPHENIX GitHub at line 123 of file G4eeCrossSections.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeCrossSections.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/src/G4eeCrossSections.cc