ECCE @ EIC Software: GIDI_settings_particle Class Reference
GIDI_settings_particle Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh>
Public Member Functions
GIDI_settings_particle (int PoPId, bool transporting, int energyMode)
GIDI_settings_particle (GIDI_settings_particle const &particle)
int initialize (int PoPId, bool transporting, int energyMode)
~GIDI_settings_particle ()
int addFlux (GIDI::statusMessageReporting *smr, GIDI_settings_flux const &flux)
GIDI_settings_processedFlux const * nearestFluxToTemperature (double temperature) const
int getGroupIndexFromEnergy (double e_in, bool encloseOutOfRange) const
int getNumberOfGroups (void) const
int getPoPId (void) const
int getEnergyMode (void) const
bool getTransporting (void) const
GIDI_settings_group getGroup (void) const
GIDI_settings_flux const * getFlux (double temperature) const
GIDI::ptwXPoints * groupFunction (GIDI::statusMessageReporting *smr, GIDI::ptwXYPoints *ptwXY1, double temperature, int order) const
void setGroup (GIDI_settings_group const &group)
bool isEnergyMode_continuous (void) const
bool isEnergyMode_grouped (void) const
bool isEnergyMode_fixedGrid (void) const
Private Member Functions
GIDI_settings_flux const * getProcessedFlux (double temperature) const
Private Attributes
int mPoPId
bool mTransporting
int mEnergyMode
GIDI_settings_group mGroup
GIDI::ptwXPoints * mGroupX
std::vector
< GIDI_settings_processedFlux > mProcessedFluxes
Detailed Description
Definition at line 188 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 188 of file GIDI_settings.hh
Constructor & Destructor Documentation
GIDI_settings_particle::GIDI_settings_particle (int PoPId, bool transporting, int energyMode)
Definition at line 16 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 16 of file GIDI_settings_particle.cc
References initialize().
GIDI_settings_particle::GIDI_settings_particle (GIDI_settings_particle const & particle)
Definition at line 23 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 23 of file GIDI_settings_particle.cc
References initialize(), mEnergyMode, mGroup, mPoPId, mProcessedFluxes, mTransporting, and setGroup().
GIDI_settings_particle::~GIDI_settings_particle ()
Definition at line 68 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 68 of file GIDI_settings_particle.cc
References mGroupX, and ptwX_free().
Member Function Documentation
int GIDI_settings_particle::addFlux (GIDI::statusMessageReporting * smr, GIDI_settings_flux const & flux)
Definition at line 75 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 75 of file GIDI_settings_particle.cc
References GIDI_settings_flux::getTemperature(), mGroupX, and mProcessedFluxes.
int GIDI_settings_particle::getEnergyMode (void) const inline
Definition at line 209 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 209 of file GIDI_settings.hh
References mEnergyMode.
GIDI_settings_flux const* GIDI_settings_particle::getFlux (double temperature) const
GIDI_settings_group GIDI_settings_particle::getGroup (void) const inline
Definition at line 211 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 211 of file GIDI_settings.hh
References mGroup.
Referenced by MCGIDI_reaction_recast().
int GIDI_settings_particle::getGroupIndexFromEnergy (double e_in, bool encloseOutOfRange) const inline
Definition at line 206 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 206 of file GIDI_settings.hh
References GIDI_settings_group::getGroupIndexFromEnergy(), and mGroup.
Referenced by MCGIDI_quantitiesLookupModes::setGroupIndex().
int GIDI_settings_particle::getNumberOfGroups (void) const inline
Definition at line 207 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 207 of file GIDI_settings.hh
References GIDI_settings_group::getNumberOfGroups(), and mGroup.
Referenced by MCGIDI_target_heated_recast().
int GIDI_settings_particle::getPoPId (void) const inline
Definition at line 208 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 208 of file GIDI_settings.hh
References mPoPId.
Referenced by GIDI_settings::addParticle().
GIDI_settings_flux const* GIDI_settings_particle::getProcessedFlux (double temperature) const private
bool GIDI_settings_particle::getTransporting (void) const inline
Definition at line 210 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 210 of file GIDI_settings.hh
References mTransporting.
ptwXPoints * GIDI_settings_particle::groupFunction (GIDI::statusMessageReporting * smr, GIDI::ptwXYPoints * ptwXY1, double temperature, int order) const
Definition at line 118 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 118 of file GIDI_settings_particle.cc
References GIDI_settings_processedFlux::groupFunction(), mGroupX, and nearestFluxToTemperature().
Referenced by MCGIDI_reaction_recast().
int GIDI_settings_particle::initialize (int PoPId, bool transporting, int energyMode)
Definition at line 34 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 34 of file GIDI_settings_particle.cc
References GIDI_settings_projectileEnergyMode_continuousEnergy, GIDI_settings_projectileEnergyMode_grouped, mEnergyMode, mGroup, mGroupX, mPoPId, mTransporting, and setGroup().
Referenced by GIDI_settings_particle().
bool GIDI_settings_particle::isEnergyMode_continuous (void) const inline
Definition at line 216 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 216 of file GIDI_settings.hh
References GIDI_settings_projectileEnergyMode_continuousEnergy, and mEnergyMode.
bool GIDI_settings_particle::isEnergyMode_fixedGrid (void) const inline
Definition at line 218 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 218 of file GIDI_settings.hh
References GIDI_settings_projectileEnergyMode_fixedGrid, and mEnergyMode.
bool GIDI_settings_particle::isEnergyMode_grouped (void) const inline
Definition at line 217 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 217 of file GIDI_settings.hh
References GIDI_settings_projectileEnergyMode_grouped, and mEnergyMode.
Referenced by MCGIDI_target_heated_recast().
GIDI_settings_processedFlux const * GIDI_settings_particle::nearestFluxToTemperature (double temperature) const
Definition at line 90 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 90 of file GIDI_settings_particle.cc
References mProcessedFluxes.
Referenced by groupFunction().
void GIDI_settings_particle::setGroup (GIDI_settings_group const & group)
Definition at line 53 of file GIDI_settings_particle.cc.
View newest version in sPHENIX GitHub at line 53 of file GIDI_settings_particle.cc
References int(), mGroup, mGroupX, GIDI_settings_group::pointer(), ptwX_create(), ptwX_free(), and GIDI_settings_group::size().
Referenced by GIDI_settings_particle(), and initialize().
Member Data Documentation
int GIDI_settings_particle::mEnergyMode private
Definition at line 193 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 193 of file GIDI_settings.hh
Referenced by getEnergyMode(), GIDI_settings_particle(), initialize(), isEnergyMode_continuous(), isEnergyMode_fixedGrid(), and isEnergyMode_grouped().
GIDI_settings_group GIDI_settings_particle::mGroup private
Definition at line 194 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 194 of file GIDI_settings.hh
Referenced by getGroup(), getGroupIndexFromEnergy(), getNumberOfGroups(), GIDI_settings_particle(), initialize(), and setGroup().
GIDI::ptwXPoints* GIDI_settings_particle::mGroupX private
Definition at line 195 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 195 of file GIDI_settings.hh
Referenced by addFlux(), groupFunction(), initialize(), setGroup(), and ~GIDI_settings_particle().
int GIDI_settings_particle::mPoPId private
Definition at line 191 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 191 of file GIDI_settings.hh
Referenced by getPoPId(), GIDI_settings_particle(), and initialize().
std::vector<GIDI_settings_processedFlux> GIDI_settings_particle::mProcessedFluxes private
Definition at line 196 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 196 of file GIDI_settings.hh
Referenced by addFlux(), GIDI_settings_particle(), and nearestFluxToTemperature().
bool GIDI_settings_particle::mTransporting private
Definition at line 192 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 192 of file GIDI_settings.hh
Referenced by getTransporting(), GIDI_settings_particle(), and initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/GIDI_settings_particle.cc