ECCE @ EIC Software: G4NuclideTable Class Reference
G4NuclideTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4NuclideTable.hh>
Public Types
typedef std::vector
< G4IsotopeProperty * > G4IsotopeList
Public Member Functions
virtual ~G4NuclideTable ()
void GenerateNuclide ()
void SetThresholdOfHalfLife (G4double)
G4double GetThresholdOfHalfLife ()
void SetLevelTolerance (G4double x)
G4double GetLevelTolerance ()
void AddState (G4int, G4int, G4double, G4double, G4int ionJ=0, G4double ionMu=0.0)
void AddState (G4int, G4int, G4double, G4int, G4double, G4int ionJ=0, G4double ionMu=0.0)
void AddState (G4int, G4int, G4double, G4Ions::G4FloatLevelBase, G4double, G4int ionJ=0, G4double ionMu=0.0)
size_t GetSizeOfIsotopeList ()
virtual G4IsotopeProperty * GetIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb=G4Ions::G4FloatLevelBase::no_Float)
virtual G4IsotopeProperty * GetIsotopeByIsoLvl (G4int Z, G4int A, G4int lvl=0)
size_t entries () const
G4IsotopeProperty * GetIsotopeByIndex (size_t idx) const
Public Member Functions inherited from G4VIsotopeTable
G4VIsotopeTable ()
G4VIsotopeTable (const G4String &)
G4VIsotopeTable (const G4VIsotopeTable &)
G4VIsotopeTable & operator= (const G4VIsotopeTable &)
virtual ~G4VIsotopeTable ()
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
void DumpTable (G4int Zmin=1, G4int Zmax=118)
const G4String & GetName () const
Static Public Member Functions
static G4NuclideTable * GetInstance ()
static G4NuclideTable * GetNuclideTable ()
static G4double GetTrancationError (G4double eex)
static G4double Round (G4double eex)
static G4long Trancate (G4double eex)
static G4double Tolerance ()
Protected Member Functions
void FillHardCodeList ()
Private Types
enum {
idxZ =0, idxA, idxEnergy, idxLife,
idxSpin, idxMu
}
Private Member Functions
G4NuclideTable ()
G4double StripFloatLevelBase (G4double E, G4int &flbIndex)
G4Ions::G4FloatLevelBase StripFloatLevelBase (G4String)
Private Attributes
G4double threshold_of_half_life
G4double minimum_threshold_of_half_life
G4IsotopeList * fUserDefinedList
std::map< G4int, std::multimap
< G4double, G4IsotopeProperty * > > map_pre_load_list
std::map< G4int, std::multimap
< G4double, G4IsotopeProperty * > > map_full_list
G4IsotopeList * fIsotopeList
G4double flevelTolerance
G4NuclideTableMessenger * fMessenger
Detailed Description
Definition at line 58 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 58 of file G4NuclideTable.hh
Member Typedef Documentation
typedef std::vector<G4IsotopeProperty*> G4NuclideTable::G4IsotopeList
Definition at line 73 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 73 of file G4NuclideTable.hh
Member Enumeration Documentation
anonymous enum private
Enumerator:
idxZ
idxA
idxEnergy
idxLife
idxSpin
idxMu
Definition at line 161 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 161 of file G4NuclideTable.hh
Constructor & Destructor Documentation
G4NuclideTable::G4NuclideTable () private
Definition at line 62 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 62 of file G4NuclideTable.cc
References fIsotopeList, fMessenger, and GenerateNuclide().
G4NuclideTable::~G4NuclideTable () virtual
Definition at line 78 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 78 of file G4NuclideTable.cc
References fIsotopeList, it, map_full_list, and map_pre_load_list.
Member Function Documentation
void G4NuclideTable::AddState (G4int ionZ, G4int ionA, G4double ionE, G4double ionLife, G4int ionJ = 0, G4double ionMu = 0.0)
Definition at line 289 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 289 of file G4NuclideTable.cc
References G4Threading::IsMasterThread(), and StripFloatLevelBase().
void G4NuclideTable::AddState (G4int ionZ, G4int ionA, G4double ionE, G4int flbIndex, G4double ionLife, G4int ionJ = 0, G4double ionMu = 0.0)
Definition at line 298 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 298 of file G4NuclideTable.cc
References fIsotopeList, fUserDefinedList, G4Threading::IsMasterThread(), G4IsotopeProperty::SetAtomicMass(), G4IsotopeProperty::SetAtomicNumber(), G4IsotopeProperty::SetDecayTable(), G4IsotopeProperty::SetEnergy(), G4IsotopeProperty::SetFloatLevelBase(), G4IsotopeProperty::SetIsomerLevel(), G4IsotopeProperty::SetiSpin(), G4IsotopeProperty::SetLifeTime(), and G4IsotopeProperty::SetMagneticMoment().
void G4NuclideTable::AddState (G4int ionZ, G4int ionA, G4double ionE, G4Ions::G4FloatLevelBase flb, G4double ionLife, G4int ionJ = 0, G4double ionMu = 0.0)
Definition at line 324 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 324 of file G4NuclideTable.cc
References fIsotopeList, fUserDefinedList, G4Threading::IsMasterThread(), G4IsotopeProperty::SetAtomicMass(), G4IsotopeProperty::SetAtomicNumber(), G4IsotopeProperty::SetDecayTable(), G4IsotopeProperty::SetEnergy(), G4IsotopeProperty::SetFloatLevelBase(), G4IsotopeProperty::SetIsomerLevel(), G4IsotopeProperty::SetiSpin(), G4IsotopeProperty::SetLifeTime(), and G4IsotopeProperty::SetMagneticMoment().
size_t G4NuclideTable::entries () const inline
Definition at line 173 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 173 of file G4NuclideTable.hh
References fIsotopeList.
Referenced by G4IonTable::PreloadNuclide().
void G4NuclideTable::FillHardCodeList () protected
Definition at line 168 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 168 of file G4NuclideTable.cc
void G4NuclideTable::GenerateNuclide ()
Definition at line 173 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 173 of file G4NuclideTable.cc
References FatalException, INPUTHEPMC::filename, fIsotopeList, G4Exception(), it, joule, keV, map_full_list, map_pre_load_list, minimum_threshold_of_half_life, ns, second, G4IsotopeProperty::SetAtomicMass(), G4IsotopeProperty::SetAtomicNumber(), G4IsotopeProperty::SetDecayTable(), G4IsotopeProperty::SetEnergy(), G4IsotopeProperty::SetFloatLevelBase(), G4IsotopeProperty::SetIsomerLevel(), G4IsotopeProperty::SetiSpin(), G4IsotopeProperty::SetLifeTime(), G4IsotopeProperty::SetMagneticMoment(), StripFloatLevelBase(), tesla, and threshold_of_half_life.
Referenced by G4NuclideTable(), G4IonTable::PreloadNuclide(), and SetThresholdOfHalfLife().
G4NuclideTable * G4NuclideTable::GetInstance (void) static
Definition at line 56 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 56 of file G4NuclideTable.cc
References instance.
Referenced by PhysicsList::AddRadioactiveDecay(), BiasedRDPhysics::BiasedRDPhysics(), LBE::ConstructGeneral(), DMXPhysicsList::DMXPhysicsList(), EICPhysicsList::EICPhysicsList(), G4RadioactiveDecayPhysics::G4RadioactiveDecayPhysics(), GetNuclideTable(), GetTrancationError(), Round(), STCyclotronPhysicsList::STCyclotronPhysicsList(), Tolerance(), and Trancate().
G4IsotopeProperty * G4NuclideTable::GetIsotope (G4int Z, G4int A, G4double E, G4Ions::G4FloatLevelBase flb = G4Ions::G4FloatLevelBase::no_Float) virtual
Implements G4VIsotopeTable.
Definition at line 107 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 107 of file G4NuclideTable.cc
References A(), DBL_MAX, flevelTolerance, fUserDefinedList, G4IsotopeProperty::GetEnergy(), it, map_pre_load_list, and second.
Referenced by GetIsotopeByIsoLvl().
G4IsotopeProperty * G4NuclideTable::GetIsotopeByIndex (size_t idx) const inline
Definition at line 179 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 179 of file G4NuclideTable.hh
References fIsotopeList, and incremental_prev_tag::idx.
Referenced by G4IonTable::PreloadNuclide().
G4IsotopeProperty * G4NuclideTable::GetIsotopeByIsoLvl (G4int Z, G4int A, G4int lvl = 0) virtual
Reimplemented from G4VIsotopeTable.
Definition at line 161 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 161 of file G4NuclideTable.cc
References GetIsotope().
G4double G4NuclideTable::GetLevelTolerance () inline
Definition at line 93 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 93 of file G4NuclideTable.hh
References flevelTolerance.
Referenced by G4IonTable::FindIon(), G4IonTable::FindIonInMaster(), GetTrancationError(), Round(), Tolerance(), and Trancate().
static G4NuclideTable* G4NuclideTable::GetNuclideTable () inline static
Definition at line 73 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 73 of file G4NuclideTable.hh
References GetInstance().
Referenced by G4IonTable::DestroyWorkerG4IonTable(), G4IonTable::PrepareNuclideTable(), and G4IonTable::~G4IonTable().
size_t G4NuclideTable::GetSizeOfIsotopeList () inline
Definition at line 104 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 104 of file G4NuclideTable.hh
References fIsotopeList.
G4double G4NuclideTable::GetThresholdOfHalfLife () inline
Definition at line 90 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 90 of file G4NuclideTable.hh
References threshold_of_half_life.
static G4double G4NuclideTable::GetTrancationError (G4double eex) inline static
Definition at line 129 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 129 of file G4NuclideTable.hh
References GetInstance(), and GetLevelTolerance().
static G4double G4NuclideTable::Round (G4double eex) inline static
Definition at line 132 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 132 of file G4NuclideTable.hh
References GetInstance(), GetLevelTolerance(), and round().
void G4NuclideTable::SetLevelTolerance (G4double x) inline
Definition at line 92 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 92 of file G4NuclideTable.hh
References flevelTolerance, and x.
Referenced by EICPhysicsList::EICPhysicsList(), G4NuclideTableMessenger::SetNewValue(), and STCyclotronPhysicsList::STCyclotronPhysicsList().
void G4NuclideTable::SetThresholdOfHalfLife (G4double t)
Definition at line 349 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 349 of file G4NuclideTable.cc
References GenerateNuclide(), G4Threading::IsMasterThread(), t, and threshold_of_half_life.
Referenced by PhysicsList::AddRadioactiveDecay(), EICPhysicsList::EICPhysicsList(), G4NuclideTableMessenger::SetNewValue(), and STCyclotronPhysicsList::STCyclotronPhysicsList().
G4double G4NuclideTable::StripFloatLevelBase (G4double E, G4int & flbIndex) private
Definition at line 357 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 357 of file G4NuclideTable.cc
References eV, and int().
Referenced by AddState(), and GenerateNuclide().
G4Ions::G4FloatLevelBase G4NuclideTable::StripFloatLevelBase (G4String sFLB) private
Definition at line 364 of file G4NuclideTable.cc.
View newest version in sPHENIX GitHub at line 364 of file G4NuclideTable.cc
References FatalException, G4Ions::FloatLevelBase(), G4Exception(), and noFloat.
static G4double G4NuclideTable::Tolerance () inline static
Definition at line 138 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 138 of file G4NuclideTable.hh
References GetInstance(), and GetLevelTolerance().
static G4long G4NuclideTable::Trancate (G4double eex) inline static
Definition at line 135 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 135 of file G4NuclideTable.hh
References GetInstance(), and GetLevelTolerance().
Member Data Documentation
G4IsotopeList* G4NuclideTable::fIsotopeList private
Definition at line 163 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 163 of file G4NuclideTable.hh
Referenced by AddState(), entries(), G4NuclideTable(), GenerateNuclide(), GetIsotopeByIndex(), GetSizeOfIsotopeList(), and ~G4NuclideTable().
G4double G4NuclideTable::flevelTolerance private
Definition at line 164 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 164 of file G4NuclideTable.hh
Referenced by GetIsotope(), GetLevelTolerance(), and SetLevelTolerance().
G4NuclideTableMessenger* G4NuclideTable::fMessenger private
Definition at line 165 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 165 of file G4NuclideTable.hh
Referenced by G4NuclideTable().
G4IsotopeList* G4NuclideTable::fUserDefinedList private
Definition at line 145 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 145 of file G4NuclideTable.hh
Referenced by AddState(), and GetIsotope().
std::map< G4int , std::multimap< G4double , G4IsotopeProperty* > > G4NuclideTable::map_full_list private
Definition at line 152 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 152 of file G4NuclideTable.hh
Referenced by GenerateNuclide(), and ~G4NuclideTable().
std::map< G4int , std::multimap< G4double , G4IsotopeProperty* > > G4NuclideTable::map_pre_load_list private
Definition at line 151 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 151 of file G4NuclideTable.hh
Referenced by GenerateNuclide(), GetIsotope(), and ~G4NuclideTable().
G4double G4NuclideTable::minimum_threshold_of_half_life private
Definition at line 144 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 144 of file G4NuclideTable.hh
Referenced by GenerateNuclide().
G4double G4NuclideTable::threshold_of_half_life private
Definition at line 143 of file G4NuclideTable.hh.
View newest version in sPHENIX GitHub at line 143 of file G4NuclideTable.hh
Referenced by GenerateNuclide(), GetThresholdOfHalfLife(), and SetThresholdOfHalfLife().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4NuclideTable.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4NuclideTable.cc