ECCE @ EIC Software: GB03BOptnSplitOrKillOnBoundary Class Reference
GB03BOptnSplitOrKillOnBoundary Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB03/include/GB03BOptnSplitOrKillOnBoundary.hh>
Public Member Functions
GB03BOptnSplitOrKillOnBoundary (G4String name)
virtual ~GB03BOptnSplitOrKillOnBoundary ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &)
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *condition)
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)
void SetSplittingFactor (G4int splittingFactor)
void SetApplyProbability (G4double proba)
G4int GetSplittingFactor () const
G4double GetApplyProbability () const
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4ParticleChange fParticleChange
G4ParticleChangeForNothing fParticleChangeForNothing
G4int fSplittingFactor
G4double fApplyProbability
Detailed Description
Definition at line 39 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 39 of file GB03BOptnSplitOrKillOnBoundary.hh
Constructor & Destructor Documentation
GB03BOptnSplitOrKillOnBoundary::GB03BOptnSplitOrKillOnBoundary (G4String name)
Definition at line 35 of file GB03BOptnSplitOrKillOnBoundary.cc.
View newest version in sPHENIX GitHub at line 35 of file GB03BOptnSplitOrKillOnBoundary.cc
GB03BOptnSplitOrKillOnBoundary::~GB03BOptnSplitOrKillOnBoundary () virtual
Definition at line 43 of file GB03BOptnSplitOrKillOnBoundary.cc.
View newest version in sPHENIX GitHub at line 43 of file GB03BOptnSplitOrKillOnBoundary.cc
Member Function Documentation
virtual G4VParticleChange* GB03BOptnSplitOrKillOnBoundary::ApplyFinalStateBiasing (const G4BiasingProcessInterface * , const G4Track * , const G4Step * , G4bool &) inline virtual
Implements G4VBiasingOperation.
Definition at line 55 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 55 of file GB03BOptnSplitOrKillOnBoundary.hh
G4double GB03BOptnSplitOrKillOnBoundary::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition * condition) virtual
Implements G4VBiasingOperation.
Definition at line 49 of file GB03BOptnSplitOrKillOnBoundary.cc.
View newest version in sPHENIX GitHub at line 49 of file GB03BOptnSplitOrKillOnBoundary.cc
References DBL_MAX, and Forced.
G4VParticleChange * GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState (const G4Track * track, const G4Step * step) virtual
Implements G4VBiasingOperation.
Definition at line 63 of file GB03BOptnSplitOrKillOnBoundary.cc.
View newest version in sPHENIX GitHub at line 63 of file GB03BOptnSplitOrKillOnBoundary.cc
References G4ParticleChange::AddSecondary(), fApplyProbability, fGeomBoundary, fParticleChange, fParticleChangeForNothing, fSplittingFactor, fStopAndKill, G4UniformRand, G4Track::GetCurrentStepNumber(), G4Track::GetMomentum(), G4Step::GetPostStepPoint(), G4StepPoint::GetStepStatus(), G4Track::GetWeight(), G4ParticleChangeForNothing::Initialize(), G4ParticleChange::Initialize(), G4VParticleChange::ProposeParentWeight(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::SetNumberOfSecondaries(), G4VParticleChange::SetSecondaryWeightByProcess(), G4Track::SetWeight(), and CLHEP::Hep3Vector::z().
G4double GB03BOptnSplitOrKillOnBoundary::GetApplyProbability () const inline
Definition at line 97 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 97 of file GB03BOptnSplitOrKillOnBoundary.hh
References fApplyProbability.
G4int GB03BOptnSplitOrKillOnBoundary::GetSplittingFactor () const inline
Definition at line 96 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 96 of file GB03BOptnSplitOrKillOnBoundary.hh
References fSplittingFactor.
virtual const G4VBiasingInteractionLaw* GB03BOptnSplitOrKillOnBoundary::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition &) inline virtual
Implements G4VBiasingOperation.
Definition at line 52 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 52 of file GB03BOptnSplitOrKillOnBoundary.hh
void GB03BOptnSplitOrKillOnBoundary::SetApplyProbability (G4double proba) inline
Definition at line 93 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 93 of file GB03BOptnSplitOrKillOnBoundary.hh
References fApplyProbability.
Referenced by GB03BOptrGeometryBasedBiasing::StartRun().
void GB03BOptnSplitOrKillOnBoundary::SetSplittingFactor (G4int splittingFactor) inline
Definition at line 79 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 79 of file GB03BOptnSplitOrKillOnBoundary.hh
References fSplittingFactor.
Referenced by GB03BOptrGeometryBasedBiasing::StartRun().
Member Data Documentation
G4double GB03BOptnSplitOrKillOnBoundary::fApplyProbability private
Definition at line 103 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 103 of file GB03BOptnSplitOrKillOnBoundary.hh
Referenced by GenerateBiasingFinalState(), GetApplyProbability(), and SetApplyProbability().
G4ParticleChange GB03BOptnSplitOrKillOnBoundary::fParticleChange private
Definition at line 100 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 100 of file GB03BOptnSplitOrKillOnBoundary.hh
Referenced by GenerateBiasingFinalState().
G4ParticleChangeForNothing GB03BOptnSplitOrKillOnBoundary::fParticleChangeForNothing private
Definition at line 101 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 101 of file GB03BOptnSplitOrKillOnBoundary.hh
Referenced by GenerateBiasingFinalState().
G4int GB03BOptnSplitOrKillOnBoundary::fSplittingFactor private
Definition at line 102 of file GB03BOptnSplitOrKillOnBoundary.hh.
View newest version in sPHENIX GitHub at line 102 of file GB03BOptnSplitOrKillOnBoundary.hh
Referenced by GenerateBiasingFinalState(), GetSplittingFactor(), and SetSplittingFactor().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB03/include/GB03BOptnSplitOrKillOnBoundary.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB03/src/GB03BOptnSplitOrKillOnBoundary.cc