ECCE @ EIC Software: G4MIRDSkull Class Reference
G4MIRDSkull Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4MIRDSkull.hh>
Public Member Functions
G4MIRDSkull ()
~G4MIRDSkull ()
G4VPhysicalVolume * Construct (const G4String &, G4VPhysicalVolume *, const G4String &, G4bool, G4bool)
Public Member Functions inherited from G4VOrgan
G4VOrgan ()
virtual ~G4VOrgan ()
Detailed Description
Definition at line 40 of file G4MIRDSkull.hh.
View newest version in sPHENIX GitHub at line 40 of file G4MIRDSkull.hh
Constructor & Destructor Documentation
G4MIRDSkull::G4MIRDSkull ()
Definition at line 51 of file G4MIRDSkull.cc.
View newest version in sPHENIX GitHub at line 51 of file G4MIRDSkull.cc
G4MIRDSkull::~G4MIRDSkull ()
Definition at line 55 of file G4MIRDSkull.cc.
View newest version in sPHENIX GitHub at line 55 of file G4MIRDSkull.cc
Member Function Documentation
G4VPhysicalVolume * G4MIRDSkull::Construct (const G4String & volumeName, G4VPhysicalVolume * mother, const G4String & colourName, G4bool wireFrame, G4bool) virtual
Implements G4VOrgan.
Definition at line 60 of file G4MIRDSkull.cc.
View newest version in sPHENIX GitHub at line 60 of file G4MIRDSkull.cc
References KF_timing::ax, cm, cm3, Acts::UnitConstants::g, G4cout, G4endl, G4VSolid::GetCubicVolume(), G4Material::GetDensity(), G4LogicalVolume::GetMaterial(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4LogicalVolume::GetSolid(), gram, material(), mm, G4VisAttributes::SetForceSolid(), G4VisAttributes::SetLineWidth(), and G4LogicalVolume::SetVisAttributes().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4MIRDSkull.hh
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/src/G4MIRDSkull.cc