ECCE @ EIC Software: G4IDataSet Class Reference
G4IDataSet Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4IDataSet.hh>
Public Member Functions
G4IDataSet ()
virtual ~G4IDataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const =0
virtual void PrintData (void) const =0
virtual const G4IDataSet * GetComponent (G4int componentId) const =0
virtual void AddComponent (G4IDataSet *dataSet)=0
virtual size_t NumberOfComponents (void) const =0
virtual const G4DataVector & GetEnergies (G4int componentId) const =0
virtual const G4DataVector & GetData (G4int componentId) const =0
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *data, G4int component=0)=0
virtual G4bool LoadData (const G4String &fileName)=0
virtual G4bool SaveData (const G4String &fileName) const =0
virtual G4double RandomSelect (G4int componentId=0) const =0
Private Member Functions
G4IDataSet (const G4IDataSet &copy)
G4IDataSet & operator= (const G4IDataSet &right)
Detailed Description
Definition at line 49 of file G4IDataSet.hh.
View newest version in sPHENIX GitHub at line 49 of file G4IDataSet.hh
Constructor & Destructor Documentation
G4IDataSet::G4IDataSet () inline
Definition at line 52 of file G4IDataSet.hh.
View newest version in sPHENIX GitHub at line 52 of file G4IDataSet.hh
virtual G4IDataSet::~G4IDataSet () inline virtual
Definition at line 53 of file G4IDataSet.hh.
View newest version in sPHENIX GitHub at line 53 of file G4IDataSet.hh
G4IDataSet::G4IDataSet (const G4IDataSet & copy) private
Member Function Documentation
virtual void G4IDataSet::AddComponent (G4IDataSet * dataSet) pure virtual
Implemented in G4DataSet, G4PixeShellDataSet, and G4CompositeDataSet.
Referenced by G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials().
virtual G4double G4IDataSet::FindValue (G4double x, G4int componentId = 0) const pure virtual
Implemented in G4DataSet, G4PixeShellDataSet, and G4CompositeDataSet.
Referenced by G4CompositeDataSet::FindValue(), G4PixeCrossSectionHandler::FindValue(), G4PixeCrossSectionHandler::SelectRandomAtom(), and G4PixeCrossSectionHandler::SelectRandomShell().
virtual const G4IDataSet* G4IDataSet::GetComponent (G4int componentId) const pure virtual
Implemented in G4DataSet, G4PixeShellDataSet, and G4CompositeDataSet.
Referenced by G4PixeCrossSectionHandler::FindValue(), G4PixeCrossSectionHandler::SelectRandomAtom(), and G4PixeCrossSectionHandler::SelectRandomShell().
virtual const G4DataVector& G4IDataSet::GetData (G4int componentId) const pure virtual
Implemented in G4PixeShellDataSet, G4DataSet, and G4CompositeDataSet.
Referenced by G4CompositeDataSet::GetData(), and G4PixeShellDataSet::GetData().
virtual const G4DataVector& G4IDataSet::GetEnergies (G4int componentId) const pure virtual
Implemented in G4PixeShellDataSet, G4DataSet, and G4CompositeDataSet.
Referenced by G4CompositeDataSet::GetEnergies(), and G4PixeShellDataSet::GetEnergies().
virtual G4bool G4IDataSet::LoadData (const G4String & fileName) pure virtual
Implemented in G4PixeShellDataSet, G4CompositeDataSet, and G4DataSet.
Referenced by G4CompositeDataSet::LoadData(), G4PixeShellDataSet::LoadData(), and G4PixeCrossSectionHandler::LoadShellData().
virtual size_t G4IDataSet::NumberOfComponents (void) const pure virtual
Implemented in G4PixeShellDataSet, G4DataSet, and G4CompositeDataSet.
Referenced by G4PixeCrossSectionHandler::FindValue(), G4PixeCrossSectionHandler::NumberOfComponents(), and G4PixeCrossSectionHandler::SelectRandomShell().
G4IDataSet& G4IDataSet::operator= (const G4IDataSet & right) private
virtual void G4IDataSet::PrintData (void) const pure virtual
Implemented in G4DataSet, G4PixeShellDataSet, and G4CompositeDataSet.
Referenced by G4CompositeDataSet::PrintData(), G4PixeShellDataSet::PrintData(), and G4PixeCrossSectionHandler::PrintData().
virtual G4double G4IDataSet::RandomSelect (G4int componentId = 0) const pure virtual
Implemented in G4PixeShellDataSet, G4CompositeDataSet, and G4DataSet.
Referenced by G4CompositeDataSet::RandomSelect().
virtual G4bool G4IDataSet::SaveData (const G4String & fileName) const pure virtual
Implemented in G4PixeShellDataSet, G4CompositeDataSet, and G4DataSet.
Referenced by G4CompositeDataSet::SaveData().
virtual void G4IDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * data, G4int component = 0) pure virtual
Implemented in G4PixeShellDataSet, G4CompositeDataSet, and G4DataSet.
Referenced by G4CompositeDataSet::SetEnergiesData(), and G4PixeShellDataSet::SetEnergiesData().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/pii/include/G4IDataSet.hh