ECCE @ EIC Software: G4EquilibriumEvaporator Class Reference
G4EquilibriumEvaporator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4EquilibriumEvaporator.hh>
Public Member Functions
G4EquilibriumEvaporator ()
virtual ~G4EquilibriumEvaporator ()
virtual void setVerboseLevel (G4int verbose)
virtual void deExcite (const G4Fragment &target, G4CollisionOutput &output)
Public Member Functions inherited from G4CascadeDeexciteBase
G4CascadeDeexciteBase (const char *name)
virtual ~G4CascadeDeexciteBase ()
Public Member Functions inherited from G4VCascadeDeexcitation
G4VCascadeDeexcitation (const G4String &name)
virtual ~G4VCascadeDeexcitation ()
virtual void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Private Member Functions
virtual G4bool explosion (G4int a, G4int z, G4double e) const
virtual G4bool explosion (const G4Fragment &target) const
G4bool goodRemnant (G4int a, G4int z) const
G4double getE0 (G4int A) const
G4double getPARLEVDEN (G4int A, G4int Z) const
G4double getQF (G4double x, G4double x2, G4int a, G4int z, G4double e) const
G4double getAF (G4double x, G4int a, G4int z, G4double e) const
G4EquilibriumEvaporator (const G4EquilibriumEvaporator &)
G4EquilibriumEvaporator & operator= (const G4EquilibriumEvaporator &)
Private Attributes
G4InuclSpecialFunctions::paraMaker theParaMaker
std::pair< std::vector
< G4double >, std::vector
< G4double > > parms
G4CollisionOutput fission_output
G4CascadeInterpolator< 72 > QFinterp
G4Fissioner theFissioner
G4BigBanger theBigBanger
Additional Inherited Members
Protected Member Functions inherited from G4CascadeDeexciteBase
virtual G4bool validateOutput (const G4Fragment &target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclElementaryParticle > &particles)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclNuclei > &fragments)
void getTargetData (const G4Fragment &target)
const G4Fragment & makeFragment (G4LorentzVector mom, G4int A, G4int Z, G4double EX=0.)
const G4Fragment & makeFragment (G4int A, G4int Z, G4double EX=0.)
Protected Attributes inherited from G4CascadeDeexciteBase
G4CascadeCheckBalance * balance
G4int A
G4int Z
G4LorentzVector PEX
G4double EEXS
G4Fragment aFragment
Detailed Description
Definition at line 57 of file G4EquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 57 of file G4EquilibriumEvaporator.hh
Constructor & Destructor Documentation
G4EquilibriumEvaporator::G4EquilibriumEvaporator ()
Definition at line 152 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 152 of file G4EquilibriumEvaporator.cc
References parms.
G4EquilibriumEvaporator::~G4EquilibriumEvaporator () virtual
Definition at line 159 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 159 of file G4EquilibriumEvaporator.cc
G4EquilibriumEvaporator::G4EquilibriumEvaporator (const G4EquilibriumEvaporator &) private
Member Function Documentation
void G4EquilibriumEvaporator::deExcite (const G4Fragment & target, G4CollisionOutput & output) virtual
Implements G4VCascadeDeexcitation.
Definition at line 170 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 170 of file G4EquilibriumEvaporator.cc
References G4CascadeDeexciteBase::A, A13, G4CollisionOutput::addOutgoingNucleus(), G4CollisionOutput::addOutgoingParticle(), G4CollisionOutput::addRecoilFragment(), G4LorentzConvertor::backToTheLab(), G4InuclSpecialFunctions::bindingEnergy(), G4CollisionOutput::boostToLabFrame(), G4BigBanger::deExcite(), G4Fissioner::deExcite(), CLHEP::HepLorentzVector::e(), G4CascadeDeexciteBase::EEXS, G4InuclParticle::Equilib, explosion(), fission_output, G, G4InuclSpecialFunctions::G4cbrt(), G4cout, G4endl, G4Exp(), G4UniformRand, G4InuclSpecialFunctions::generateWithRandomAngles(), getAF(), G4InuclSpecialFunctions::getAL(), getE0(), G4InuclNuclei::getNucleiMass(), G4CollisionOutput::getOutgoingNuclei(), G4CollisionOutput::getOutgoingParticles(), G4InuclSpecialFunctions::paraMaker::getParams(), getPARLEVDEN(), G4InuclElementaryParticle::getParticleMass(), getQF(), G4CollisionOutput::getRecoilFragment(), G4CascadeDeexciteBase::getTargetData(), GeV, goodRemnant(), G4InuclSpecialFunctions::inuclRndm(), m, G4CascadeDeexciteBase::makeFragment(), mass, mom, G4CollisionOutput::numberOfFragments(), parms, G4CascadeDeexciteBase::PEX, G4InuclParticleNames::photon, G4InuclParticleNames::proton, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), Q, G4CollisionOutput::reset(), S(), G4LorentzConvertor::setBullet(), G4LorentzConvertor::setTarget(), SL, theBigBanger, theFissioner, theParaMaker, TM, G4LorentzConvertor::toTheTargetRestFrame(), Acts::UnitConstants::u, G4CascadeDeexciteBase::validateOutput(), G4VCascadeCollider::verboseLevel, X, X1, X2, Xmax, G4CascadeDeexciteBase::Z, and Z1.
Referenced by G4EvaporationInuclCollider::deExcite(), and G4CascadeDeexcitation::deExcite().
G4bool G4EquilibriumEvaporator::explosion (G4int a, G4int z, G4double e) const private virtual
Reimplemented from G4CascadeDeexciteBase.
Definition at line 653 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 653 of file G4EquilibriumEvaporator.cc
References G4InuclSpecialFunctions::bindingEnergy(), G4cout, G4endl, G4VCascadeCollider::verboseLevel, and z.
Referenced by deExcite().
virtual G4bool G4EquilibriumEvaporator::explosion (const G4Fragment & target) const inline private virtual
Reimplemented from G4CascadeDeexciteBase.
Definition at line 71 of file G4EquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 71 of file G4EquilibriumEvaporator.hh
References G4CascadeDeexciteBase::explosion().
G4double G4EquilibriumEvaporator::getAF (G4double x, G4int a, G4int z, G4double e) const private
Definition at line 713 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 713 of file G4EquilibriumEvaporator.cc
References G4cout, G4endl, and G4VCascadeCollider::verboseLevel.
Referenced by deExcite().
G4double G4EquilibriumEvaporator::getE0 (G4int A) const private
Definition at line 743 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 743 of file G4EquilibriumEvaporator.cc
References G4cout, G4endl, and G4VCascadeCollider::verboseLevel.
Referenced by deExcite().
G4double G4EquilibriumEvaporator::getPARLEVDEN (G4int A, G4int Z) const private
Definition at line 731 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 731 of file G4EquilibriumEvaporator.cc
References G4cout, G4endl, and G4VCascadeCollider::verboseLevel.
Referenced by deExcite().
G4double G4EquilibriumEvaporator::getQF (G4double x, G4double x2, G4int a, G4int z, G4double e) const private
Definition at line 682 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 682 of file G4EquilibriumEvaporator.cc
References A13, G4InuclSpecialFunctions::G4cbrt(), G4cout, G4endl, G4CascadeInterpolator< NBINS >::interpolate(), QFinterp, G4VCascadeCollider::verboseLevel, X1, and x2.
Referenced by deExcite().
G4bool G4EquilibriumEvaporator::goodRemnant (G4int a, G4int z) const private
Definition at line 672 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 672 of file G4EquilibriumEvaporator.cc
References G4cout, G4endl, G4VCascadeCollider::verboseLevel, and z.
Referenced by deExcite().
G4EquilibriumEvaporator& G4EquilibriumEvaporator::operator= (const G4EquilibriumEvaporator &) private
void G4EquilibriumEvaporator::setVerboseLevel (G4int verbose) virtual
Reimplemented from G4CascadeDeexciteBase.
Definition at line 161 of file G4EquilibriumEvaporator.cc.
View newest version in sPHENIX GitHub at line 161 of file G4EquilibriumEvaporator.cc
References G4CascadeDeexciteBase::setVerboseLevel(), theBigBanger, and theFissioner.
Referenced by G4CascadeDeexcitation::setVerboseLevel().
Member Data Documentation
G4CollisionOutput G4EquilibriumEvaporator::fission_output private
Definition at line 85 of file G4EquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 85 of file G4EquilibriumEvaporator.hh
Referenced by deExcite().
std::pair<std::vector<G4double>, std::vector<G4double> > G4EquilibriumEvaporator::parms private
Definition at line 84 of file G4EquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 84 of file G4EquilibriumEvaporator.hh
Referenced by deExcite(), and G4EquilibriumEvaporator().
G4CascadeInterpolator<72> G4EquilibriumEvaporator::QFinterp private
Definition at line 88 of file G4EquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 88 of file G4EquilibriumEvaporator.hh
Referenced by getQF().
G4BigBanger G4EquilibriumEvaporator::theBigBanger private
Definition at line 91 of file G4EquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 91 of file G4EquilibriumEvaporator.hh
Referenced by deExcite(), and setVerboseLevel().
G4Fissioner G4EquilibriumEvaporator::theFissioner private
Definition at line 90 of file G4EquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 90 of file G4EquilibriumEvaporator.hh
Referenced by deExcite(), and setVerboseLevel().
G4InuclSpecialFunctions::paraMaker G4EquilibriumEvaporator::theParaMaker private
Definition at line 77 of file G4EquilibriumEvaporator.hh.
View newest version in sPHENIX GitHub at line 77 of file G4EquilibriumEvaporator.hh
Referenced by deExcite().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4EquilibriumEvaporator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4EquilibriumEvaporator.cc