ECCE @ EIC Software: G4ParticleHPAngular Class Reference
G4ParticleHPAngular Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPAngular.hh>
Classes
struct toBeCached
Public Member Functions
G4ParticleHPAngular ()
~G4ParticleHPAngular ()
void Init (std::istream &aDataFile)
void SampleAndUpdate (G4ReactionProduct &anIncidentParticle)
void SetTarget (const G4ReactionProduct &aTarget)
void SetProjectileRP (const G4ReactionProduct &anIncidentParticleRP)
G4double GetTargetMass ()
Private Attributes
G4int theAngularDistributionType
G4int frameFlag
G4bool theIsoFlag
G4ParticleHPLegendreStore * theCoefficients
G4ParticleHPPartial * theProbArray
G4double targetMass
G4Cache< toBeCached > fCache
Detailed Description
Definition at line 45 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPAngular.hh
Constructor & Destructor Documentation
G4ParticleHPAngular::G4ParticleHPAngular () inline
Definition at line 56 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPAngular.hh
References fCache, frameFlag, G4Cache< VALTYPE >::Put(), targetMass, theAngularDistributionType, theCoefficients, theIsoFlag, and theProbArray.
G4ParticleHPAngular::~G4ParticleHPAngular () inline
Definition at line 69 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleHPAngular.hh
References theCoefficients, and theProbArray.
Member Function Documentation
G4double G4ParticleHPAngular::GetTargetMass () inline
Definition at line 89 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPAngular.hh
References targetMass.
Referenced by G4ParticleHPInelasticBaseFS::BaseApply().
void G4ParticleHPAngular::Init (std::istream & aDataFile)
Definition at line 41 of file G4ParticleHPAngular.cc.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPAngular.cc
References energy, eV, frameFlag, G4cout, G4endl, G4ParticleHPLegendreStore::Init(), G4ParticleHPPartial::InitData(), G4ParticleHPPartial::InitInterpolation(), G4ParticleHPLegendreStore::InitInterpolation(), G4ParticleHPLegendreStore::SetCoeff(), G4ParticleHPPartial::SetT(), G4ParticleHPLegendreStore::SetTemperature(), G4ParticleHPPartial::SetX(), targetMass, theAngularDistributionType, theCoefficients, theIsoFlag, and theProbArray.
Referenced by G4ParticleHPFSFissionFS::Init(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), and G4FissionLibrary::Init().
void G4ParticleHPAngular::SampleAndUpdate (G4ReactionProduct & anIncidentParticle)
Definition at line 100 of file G4ParticleHPAngular.cc.
View newest version in sPHENIX GitHub at line 100 of file G4ParticleHPAngular.cc
References fCache, frameFlag, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4ReactionProduct::GetKineticEnergy(), G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), G4ReactionProduct::Lorentz(), mom, phi, G4ParticleHPPartial::Sample(), G4ParticleHPLegendreStore::SampleMax(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), theAngularDistributionType, theCoefficients, theIsoFlag, theProbArray, theta(), and twopi.
Referenced by G4ParticleHPFSFissionFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::CompositeApply().
void G4ParticleHPAngular::SetProjectileRP (const G4ReactionProduct & anIncidentParticleRP) inline
Definition at line 84 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleHPAngular.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::InitDistributionInitialState(), G4ParticleHPFissionBaseFS::SetNeutronRP(), and G4ParticleHPFSFissionFS::SetNeutronRP().
void G4ParticleHPAngular::SetTarget (const G4ReactionProduct & aTarget) inline
Definition at line 79 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPAngular.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::InitDistributionInitialState(), G4ParticleHPFissionBaseFS::SetTarget(), and G4ParticleHPFSFissionFS::SetTarget().
Member Data Documentation
G4Cache<toBeCached> G4ParticleHPAngular::fCache private
Definition at line 114 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleHPAngular.hh
Referenced by G4ParticleHPAngular(), SampleAndUpdate(), SetProjectileRP(), and SetTarget().
G4int G4ParticleHPAngular::frameFlag private
Definition at line 103 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPAngular.hh
Referenced by G4ParticleHPAngular(), Init(), and SampleAndUpdate().
G4double G4ParticleHPAngular::targetMass private
Definition at line 112 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPAngular.hh
Referenced by G4ParticleHPAngular(), GetTargetMass(), and Init().
G4int G4ParticleHPAngular::theAngularDistributionType private
Definition at line 102 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ParticleHPAngular.hh
Referenced by G4ParticleHPAngular(), Init(), and SampleAndUpdate().
G4ParticleHPLegendreStore* G4ParticleHPAngular::theCoefficients private
Definition at line 107 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPAngular.hh
Referenced by G4ParticleHPAngular(), Init(), SampleAndUpdate(), and ~G4ParticleHPAngular().
G4bool G4ParticleHPAngular::theIsoFlag private
Definition at line 105 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPAngular.hh
Referenced by G4ParticleHPAngular(), Init(), and SampleAndUpdate().
G4ParticleHPPartial* G4ParticleHPAngular::theProbArray private
Definition at line 109 of file G4ParticleHPAngular.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPAngular.hh
Referenced by G4ParticleHPAngular(), Init(), SampleAndUpdate(), and ~G4ParticleHPAngular().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPAngular.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPAngular.cc