ECCE @ EIC Software: macros/blob/master/common/G4_hFarFwdBeamLine_EIC.C File Reference
G4_hFarFwdBeamLine_EIC.C File Reference
#include <GlobalVariables.C>
#include <g4detectors/BeamLineMagnetSubsystem.h>
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4detectors/PHG4ConeSubsystem.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <eicg4zdc/EICG4ZDCHitTree.h>
#include <eicg4zdc/EICG4ZDCNtuple.h>
#include <eicg4zdc/EICG4ZDCSubsystem.h>
#include <eicg4b0/EICG4B0Subsystem.h>
#include <eicg4b0ecal/EICG4B0ECALSubsystem.h>
#include <eicg4rp/EICG4RPSubsystem.h>
#include <eiceval/FarForwardEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <TSystem.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
namespace hFarFwdBeamLine
Macros
#define MACRO_G4HFARFWDBEAMLINE_EIC_C
Functions
float PosFlip (float pos)
float AngleFlip (float angle)
float MagFieldFlip (float Bfield)
PHG4CylinderSubsystem * hFarFwdBeamLine::hFarFwdBeamLineEnclosure (nullptr)
void hFarFwdBeamLineInit ()
void hFarFwdDefineMagnets (PHG4Reco *g4Reco)
void hFarFwdDefineDetectorsIP6 (PHG4Reco *g4Reco)
void hFarFwdDefineDetectorsIP8 (PHG4Reco *g4Reco)
void hFarFwdDefineBeamPipe (PHG4Reco *g4Reco)
void FFR_Eval (const std::string &outputfile)
Variables
bool Enable::HFARFWD_MAGNETS = false
bool Enable::HFARFWD_VIRTUAL_DETECTORS = false
bool Enable::HFARFWD_PIPE = false
bool Enable::HFARFWD_OVERLAPCHECK = false
int Enable::HFARFWD_VERBOSITY = 0
bool Enable::ZDC_DISABLE_BLACKHOLE = false
bool Enable::B0_DISABLE_HITPLANE = false
bool Enable::B0_FULLHITPLANE = false
bool Enable::B0_VAR_PIPE_HOLE = false
bool Enable::B0_CIRCLE_PIPE_HOLE = false
bool Enable::RP_DISABLE_HITPLANE = false
bool Enable::B0ECALTOWERS = true
bool Enable::HFARFWD_MAGNETS_IP6 = false
bool Enable::HFARFWD_MAGNETS_IP8 = false
bool Enable::HFARFWD_VIRTUAL_DETECTORS_IP6 = false
bool Enable::HFARFWD_VIRTUAL_DETECTORS_IP8 = false
bool Enable::FFR_EVAL = false
double hFarFwdBeamLine::starting_z = 500
double hFarFwdBeamLine::enclosure_z_max = NAN
double hFarFwdBeamLine::enclosure_r_max = NAN
double hFarFwdBeamLine::enclosure_center = NAN
BeamLineMagnetSubsystem * hFarFwdBeamLine::B0Magnet = (nullptr)
double hFarFwdBeamLine::B0Magnet_x = NAN
double hFarFwdBeamLine::B0Magnet_y = NAN
double hFarFwdBeamLine::B0Magnet_z = NAN
Macro Definition Documentation
#define MACRO_G4HFARFWDBEAMLINE_EIC_C
Definition at line 2 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_hFarFwdBeamLine_EIC.C
Function Documentation
float AngleFlip (float angle)
Definition at line 1371 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 1371 of file G4_hFarFwdBeamLine_EIC.C
References angle, and Enable::HFARFWD_MAGNETS_IP6.
Referenced by hFarFwdDefineBeamPipe(), hFarFwdDefineDetectorsIP6(), hFarFwdDefineDetectorsIP8(), and hFarFwdDefineMagnets().
void FFR_Eval (const std::string & outputfile)
Definition at line 1390 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 1390 of file G4_hFarFwdBeamLine_EIC.C
References Enable::EEMC_VERBOSITY, Fun4AllServer::instance(), Enable::IP6, max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), and Fun4All_runEvaluators().
void hFarFwdBeamLineInit ()
Definition at line 80 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 80 of file G4_hFarFwdBeamLine_EIC.C
References hFarFwdBeamLine::enclosure_center, hFarFwdBeamLine::enclosure_r_max, hFarFwdBeamLine::enclosure_z_max, Enable::HFARFWD_MAGNETS, Enable::HFARFWD_MAGNETS_IP6, Enable::HFARFWD_MAGNETS_IP8, Enable::HFARFWD_VIRTUAL_DETECTORS, Enable::HFARFWD_VIRTUAL_DETECTORS_IP6, Enable::HFARFWD_VIRTUAL_DETECTORS_IP8, Enable::IP6, Enable::IP8, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, and hFarFwdBeamLine::starting_z.
Referenced by G4Init().
void hFarFwdDefineBeamPipe (PHG4Reco * g4Reco)
Definition at line 1256 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 1256 of file G4_hFarFwdBeamLine_EIC.C
References AngleFlip(), Enable::HFARFWD_VERBOSITY, max, nm, PosFlip(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), and Enable::VERBOSITY.
void hFarFwdDefineDetectorsIP6 (PHG4Reco * g4Reco)
Fun4All default B0 planes
Choice 3 Hit planes with real detector geometry
Definition at line 302 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 302 of file G4_hFarFwdBeamLine_EIC.C
References B0TrackFastSim::add_phg4hits(), B0TrackFastSim::add_zplane_state(), AngleFlip(), Enable::B0_CIRCLE_PIPE_HOLE, Enable::B0_DISABLE_HITPLANE, Enable::B0_FULLHITPLANE, Enable::B0_VAR_PIPE_HOLE, Enable::B0ECAL, Enable::B0ECALTOWERS, hFarFwdBeamLine::B0Magnet, hFarFwdBeamLine::B0Magnet_x, hFarFwdBeamLine::B0Magnet_y, hFarFwdBeamLine::B0Magnet_z, B0TRACKING::B0ProjectionNames, Enable::BEAM_COLLISION_SETTING, hFarFwdBeamLine::enclosure_center, B0TRACKING::FastKalmanFilter(), B0TRACKING::FastKalmanFilterB0Track(), Enable::HFARBWD_E_ENERGY, Enable::HFARFWD_ION_ENERGY, Enable::HFARFWD_OVERLAPCHECK, Enable::HFARFWD_VERBOSITY, Enable::HFARFWD_VIRTUAL_DETECTORS_IP6, Enable::HFARFWD_VIRTUAL_DETECTORS_IP8, hFarFwdBeamLine::hFarFwdBeamLineEnclosure(), G4TTL::layer, max, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PosFlip(), G4B0TRACKING::PositionResolution(), PHG4Reco::registerSubsystem(), Enable::RP_DISABLE_HITPLANE, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), Enable::VERBOSITY, B0TrackFastSim::Vertical_Plane, and Enable::ZDC_DISABLE_BLACKHOLE.
Referenced by G4Setup().
void hFarFwdDefineDetectorsIP8 (PHG4Reco * g4Reco)
Fun4All default B0 planes
Choice 3 Hit planes with real detector geometry
Definition at line 764 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 764 of file G4_hFarFwdBeamLine_EIC.C
References B0TrackFastSim::add_phg4hits(), B0TrackFastSim::add_zplane_state(), AngleFlip(), Enable::B0_CIRCLE_PIPE_HOLE, Enable::B0_DISABLE_HITPLANE, Enable::B0_FULLHITPLANE, Enable::B0_VAR_PIPE_HOLE, Enable::B0ECAL, Enable::B0ECALTOWERS, hFarFwdBeamLine::B0Magnet, hFarFwdBeamLine::B0Magnet_x, hFarFwdBeamLine::B0Magnet_y, hFarFwdBeamLine::B0Magnet_z, B0TRACKING::B0ProjectionNames, Enable::BEAM_COLLISION_SETTING, BeamLineMagnetSubsystem::CanBeMotherSubsystem(), hFarFwdBeamLine::enclosure_center, B0TRACKING::FastKalmanFilter(), B0TRACKING::FastKalmanFilterB0Track(), Enable::HFARBWD_E_ENERGY, Enable::HFARFWD_ION_ENERGY, Enable::HFARFWD_OVERLAPCHECK, Enable::HFARFWD_VERBOSITY, Enable::HFARFWD_VIRTUAL_DETECTORS_IP6, Enable::HFARFWD_VIRTUAL_DETECTORS_IP8, hFarFwdBeamLine::hFarFwdBeamLineEnclosure(), G4TTL::layer, max, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PosFlip(), G4B0TRACKING::PositionResolution(), PHG4Reco::registerSubsystem(), Enable::RP_DISABLE_HITPLANE, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), Enable::VERBOSITY, B0TrackFastSim::Vertical_Plane, and Enable::ZDC_DISABLE_BLACKHOLE.
Referenced by G4Setup().
void hFarFwdDefineMagnets (PHG4Reco * g4Reco)
Definition at line 114 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 114 of file G4_hFarFwdBeamLine_EIC.C
References angle, AngleFlip(), hFarFwdBeamLine::B0Magnet, hFarFwdBeamLine::B0Magnet_x, hFarFwdBeamLine::B0Magnet_y, hFarFwdBeamLine::B0Magnet_z, PHG4DetectorSubsystem::BlackHole(), PHG4CylinderSubsystem::CanBeMotherSubsystem(), hFarFwdBeamLine::enclosure_center, hFarFwdBeamLine::enclosure_r_max, hFarFwdBeamLine::enclosure_z_max, Enable::HFARFWD_ION_ENERGY, Enable::HFARFWD_MAGNETS_IP6, Enable::HFARFWD_MAGNETS_IP8, Enable::HFARFWD_OVERLAPCHECK, Enable::HFARFWD_VERBOSITY, hFarFwdBeamLine::hFarFwdBeamLineEnclosure(), BTOF::length, MagFieldFlip(), max, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PosFlip(), PHG4Reco::registerSubsystem(), PHG4CylinderSubsystem::set_color(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4Subsystem::SetMotherSubsystem(), hFarFwdBeamLine::starting_z, PHG4DetectorSubsystem::SuperDetector(), Enable::VERBOSITY, Fun4AllBase::Verbosity(), x, y, and z.
Referenced by G4Setup().
float MagFieldFlip (float Bfield)
Definition at line 1379 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 1379 of file G4_hFarFwdBeamLine_EIC.C
References Enable::HFARFWD_MAGNETS_IP6.
Referenced by hFarFwdDefineMagnets().
float PosFlip (float pos)
Definition at line 1363 of file G4_hFarFwdBeamLine_EIC.C.
View newest version in sPHENIX GitHub at line 1363 of file G4_hFarFwdBeamLine_EIC.C
References Enable::HFARFWD_MAGNETS_IP6, and pos().
Referenced by hFarFwdDefineBeamPipe(), hFarFwdDefineDetectorsIP6(), hFarFwdDefineDetectorsIP8(), and hFarFwdDefineMagnets().