ECCE @ EIC Software: G4DNABornExcitationModel1 Class Reference
G4DNABornExcitationModel1 Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNABornExcitationModel1.hh>
Public Member Functions
G4DNABornExcitationModel1 (const G4ParticleDefinition *p=0, const G4String &nam="DNABornExcitationModel")
virtual ~G4DNABornExcitationModel1 ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &=*(new G4DataVector()))
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
void SelectStationary (G4bool input)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
G4int RandomSelect (G4double energy)
G4DNABornExcitationModel1 & operator= (const G4DNABornExcitationModel1 &right)
G4DNABornExcitationModel1 (const G4DNABornExcitationModel1 &)
Private Attributes
G4bool statCode
const std::vector< G4double > * fpMolWaterDensity
G4bool isInitialised
G4int verboseLevel
const G4ParticleDefinition * fParticleDefinition
G4double fLowEnergy
G4double fHighEnergy
G4String fTableFile
G4DNACrossSectionDataSet * fTableData
G4DNAWaterExcitationStructure waterStructure
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 42 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 42 of file G4DNABornExcitationModel1.hh
Constructor & Destructor Documentation
G4DNABornExcitationModel1::G4DNABornExcitationModel1 (const G4ParticleDefinition * p = 0, const G4String & nam = "DNABornExcitationModel")
Definition at line 40 of file G4DNABornExcitationModel1.cc.
View newest version in sPHENIX GitHub at line 40 of file G4DNABornExcitationModel1.cc
References fHighEnergy, fLowEnergy, fParticleChangeForGamma, fParticleDefinition, fpMolWaterDensity, G4cout, G4endl, statCode, and verboseLevel.
G4DNABornExcitationModel1::~G4DNABornExcitationModel1 () virtual
Definition at line 70 of file G4DNABornExcitationModel1.cc.
View newest version in sPHENIX GitHub at line 70 of file G4DNABornExcitationModel1.cc
References fTableData.
G4DNABornExcitationModel1::G4DNABornExcitationModel1 (const G4DNABornExcitationModel1 &) private
Member Function Documentation
G4double G4DNABornExcitationModel1::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 137 of file G4DNABornExcitationModel1.cc.
View newest version in sPHENIX GitHub at line 137 of file G4DNABornExcitationModel1.cc
References cm, eV, fHighEnergy, G4DNACrossSectionDataSet::FindValue(), fLowEnergy, fParticleDefinition, fTableData, G4cout, G4endl, G4Material::GetIndex(), G4ParticleDefinition::GetParticleName(), and verboseLevel.
G4double G4DNABornExcitationModel1::GetPartialCrossSection (const G4Material * , G4int level, const G4ParticleDefinition * particle, G4double kineticEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 214 of file G4DNABornExcitationModel1.cc.
View newest version in sPHENIX GitHub at line 214 of file G4DNABornExcitationModel1.cc
References FatalException, G4VEMDataSet::FindValue(), fParticleDefinition, fTableData, G4Exception(), and G4DNACrossSectionDataSet::GetComponent().
void G4DNABornExcitationModel1::Initialise (const G4ParticleDefinition * particle, const G4DataVector & = *(new G4DataVector())) virtual
Implements G4VEmModel.
Definition at line 79 of file G4DNABornExcitationModel1.cc.
View newest version in sPHENIX GitHub at line 79 of file G4DNABornExcitationModel1.cc
References eV, FatalException, fHighEnergy, fLowEnergy, fParticleChangeForGamma, fParticleDefinition, fpMolWaterDensity, fTableData, fTableFile, G4cout, G4endl, G4Exception(), G4Material::GetMaterial(), G4DNAMolecularMaterial::GetNumMolPerVolTableFor(), G4VEmModel::GetParticleChangeForGamma(), G4ParticleDefinition::GetParticleName(), G4VEmModel::HighEnergyLimit(), G4DNAMolecularMaterial::Instance(), isInitialised, keV, G4DNACrossSectionDataSet::LoadData(), G4VEmModel::LowEnergyLimit(), m, MeV, particle, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), and verboseLevel.
G4DNABornExcitationModel1& G4DNABornExcitationModel1::operator= (const G4DNABornExcitationModel1 & right) private
G4int G4DNABornExcitationModel1::RandomSelect (G4double energy) private
Definition at line 232 of file G4DNABornExcitationModel1.cc.
View newest version in sPHENIX GitHub at line 232 of file G4DNABornExcitationModel1.cc
References G4VEMDataSet::FindValue(), fTableData, G4UniformRand, G4DNACrossSectionDataSet::GetComponent(), n, and G4DNACrossSectionDataSet::NumberOfComponents().
Referenced by SampleSecondaries().
void G4DNABornExcitationModel1::SampleSecondaries (std::vector< G4DynamicParticle * > * , const G4MaterialCutsCouple * , const G4DynamicParticle * aDynamicParticle, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 177 of file G4DNABornExcitationModel1.cc.
View newest version in sPHENIX GitHub at line 177 of file G4DNABornExcitationModel1.cc
References G4DNAChemistryManager::CreateWaterMolecule(), eExcitedMolecule, G4DNAWaterExcitationStructure::ExcitationEnergy(), fParticleChangeForGamma, G4cout, G4endl, G4ParticleChangeForGamma::GetCurrentTrack(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4DNAChemistryManager::Instance(), k, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), RandomSelect(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), statCode, verboseLevel, and waterStructure.
void G4DNABornExcitationModel1::SelectStationary (G4bool input) inline
Definition at line 104 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DNABornExcitationModel1.hh
References statCode.
Referenced by G4EmDNAPhysics_stationary::ConstructProcess().
Member Data Documentation
G4double G4DNABornExcitationModel1::fHighEnergy private
Definition at line 88 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 88 of file G4DNABornExcitationModel1.hh
Referenced by CrossSectionPerVolume(), G4DNABornExcitationModel1(), and Initialise().
G4double G4DNABornExcitationModel1::fLowEnergy private
Definition at line 87 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 87 of file G4DNABornExcitationModel1.hh
Referenced by CrossSectionPerVolume(), G4DNABornExcitationModel1(), and Initialise().
G4ParticleChangeForGamma* G4DNABornExcitationModel1::fParticleChangeForGamma protected
Definition at line 74 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 74 of file G4DNABornExcitationModel1.hh
Referenced by G4DNABornExcitationModel1(), Initialise(), and SampleSecondaries().
const G4ParticleDefinition* G4DNABornExcitationModel1::fParticleDefinition private
Definition at line 85 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 85 of file G4DNABornExcitationModel1.hh
Referenced by CrossSectionPerVolume(), G4DNABornExcitationModel1(), GetPartialCrossSection(), and Initialise().
const std::vector<G4double>* G4DNABornExcitationModel1::fpMolWaterDensity private
Definition at line 81 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 81 of file G4DNABornExcitationModel1.hh
Referenced by G4DNABornExcitationModel1(), and Initialise().
G4DNACrossSectionDataSet* G4DNABornExcitationModel1::fTableData private
Definition at line 90 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 90 of file G4DNABornExcitationModel1.hh
Referenced by CrossSectionPerVolume(), GetPartialCrossSection(), Initialise(), RandomSelect(), and ~G4DNABornExcitationModel1().
G4String G4DNABornExcitationModel1::fTableFile private
Definition at line 89 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 89 of file G4DNABornExcitationModel1.hh
Referenced by Initialise().
G4bool G4DNABornExcitationModel1::isInitialised private
Definition at line 83 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DNABornExcitationModel1.hh
Referenced by Initialise().
G4bool G4DNABornExcitationModel1::statCode private
Definition at line 78 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 78 of file G4DNABornExcitationModel1.hh
Referenced by G4DNABornExcitationModel1(), SampleSecondaries(), and SelectStationary().
G4int G4DNABornExcitationModel1::verboseLevel private
Definition at line 84 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DNABornExcitationModel1.hh
Referenced by CrossSectionPerVolume(), G4DNABornExcitationModel1(), Initialise(), and SampleSecondaries().
G4DNAWaterExcitationStructure G4DNABornExcitationModel1::waterStructure private
Definition at line 95 of file G4DNABornExcitationModel1.hh.
View newest version in sPHENIX GitHub at line 95 of file G4DNABornExcitationModel1.hh
Referenced by SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNABornExcitationModel1.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNABornExcitationModel1.cc