ECCE @ EIC Software: G4StackManager Class Reference
G4StackManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4StackManager.hh>
Public Member Functions
G4StackManager ()
~G4StackManager ()
G4int PushOneTrack (G4Track *newTrack, G4VTrajectory *newTrajectory=0)
G4Track * PopNextTrack (G4VTrajectory **newTrajectory)
G4int PrepareNewEvent ()
void ReClassify ()
void SetNumberOfAdditionalWaitingStacks (G4int iAdd)
void TransferStackedTracks (G4ClassificationOfNewTrack origin, G4ClassificationOfNewTrack destination)
void TransferOneStackedTrack (G4ClassificationOfNewTrack origin, G4ClassificationOfNewTrack destination)
void clear ()
void ClearUrgentStack ()
void ClearWaitingStack (int i=0)
void ClearPostponeStack ()
G4int GetNTotalTrack () const
G4int GetNUrgentTrack () const
G4int GetNWaitingTrack (int i=0) const
G4int GetNPostponedTrack () const
void SetVerboseLevel (G4int const value)
void SetUserStackingAction (G4UserStackingAction *value)
Private Member Functions
const G4StackManager & operator= (const G4StackManager &right)
G4bool operator== (const G4StackManager &right) const
G4bool operator!= (const G4StackManager &right) const
G4ClassificationOfNewTrack DefaultClassification (G4Track *aTrack)
Private Attributes
G4UserStackingAction * userStackingAction
G4int verboseLevel
G4TrackStack * urgentStack
G4TrackStack * waitingStack
G4TrackStack * postponeStack
G4StackingMessenger * theMessenger
std::vector< G4TrackStack * > additionalWaitingStacks
G4int numberOfAdditionalWaitingStacks
Detailed Description
Definition at line 61 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 61 of file G4StackManager.hh
Constructor & Destructor Documentation
G4StackManager::G4StackManager ()
Definition at line 38 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 38 of file G4StackManager.cc
References postponeStack, theMessenger, urgentStack, and waitingStack.
G4StackManager::~G4StackManager ()
Definition at line 53 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 53 of file G4StackManager.cc
References additionalWaitingStacks, G4cout, G4endl, G4TrackStack::GetMaxNTrack(), numberOfAdditionalWaitingStacks, postponeStack, theMessenger, urgentStack, userStackingAction, verboseLevel, and waitingStack.
Member Function Documentation
void G4StackManager::clear (void)
Definition at line 483 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 483 of file G4StackManager.cc
References ClearUrgentStack(), ClearWaitingStack(), and numberOfAdditionalWaitingStacks.
Referenced by G4EventManager::AbortCurrentEvent(), export_G4StackManager(), ExN04StackingAction::NewStage(), and RE05StackingAction::NewStage().
void G4StackManager::ClearPostponeStack ()
Definition at line 504 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 504 of file G4StackManager.cc
References G4TrackStack::clearAndDestroy(), and postponeStack.
Referenced by export_G4StackManager(), and G4StackingMessenger::SetNewValue().
void G4StackManager::ClearUrgentStack ()
Definition at line 490 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 490 of file G4StackManager.cc
References G4TrackStack::clearAndDestroy(), and urgentStack.
Referenced by clear(), export_G4StackManager(), and G4StackingMessenger::SetNewValue().
void G4StackManager::ClearWaitingStack (int i = 0)
Definition at line 495 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 495 of file G4StackManager.cc
References additionalWaitingStacks, G4TrackStack::clearAndDestroy(), numberOfAdditionalWaitingStacks, and waitingStack.
Referenced by clear(), export_G4StackManager(), and G4StackingMessenger::SetNewValue().
G4ClassificationOfNewTrack G4StackManager::DefaultClassification (G4Track * aTrack) private
Definition at line 546 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 546 of file G4StackManager.cc
References fPostpone, fPostponeToNextEvent, fUrgent, and G4Track::GetTrackStatus().
Referenced by PrepareNewEvent(), and PushOneTrack().
G4int G4StackManager::GetNPostponedTrack () const
Definition at line 530 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 530 of file G4StackManager.cc
References G4TrackStack::GetNTrack(), and postponeStack.
Referenced by PrepareNewEvent(), and G4StackingMessenger::SetNewValue().
G4int G4StackManager::GetNTotalTrack () const
Definition at line 509 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 509 of file G4StackManager.cc
References additionalWaitingStacks, G4TrackStack::GetNTrack(), n, numberOfAdditionalWaitingStacks, postponeStack, urgentStack, and waitingStack.
Referenced by G4EventManager::DoProcessing(), export_G4StackManager(), and StackingAction::NewStage().
G4int G4StackManager::GetNUrgentTrack () const
Definition at line 516 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 516 of file G4StackManager.cc
References G4TrackStack::GetNTrack(), and urgentStack.
Referenced by export_G4StackManager(), RE01StackingAction::NewStage(), CCalStackingAction::NewStage(), PopNextTrack(), PushOneTrack(), ReClassify(), and G4StackingMessenger::SetNewValue().
G4int G4StackManager::GetNWaitingTrack (int i = 0) const
Definition at line 521 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 521 of file G4StackManager.cc
References additionalWaitingStacks, G4TrackStack::GetNTrack(), numberOfAdditionalWaitingStacks, and waitingStack.
Referenced by export_G4StackManager(), PopNextTrack(), and G4StackingMessenger::SetNewValue().
G4bool G4StackManager::operator!= (const G4StackManager & right) const private
Definition at line 80 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 80 of file G4StackManager.cc
const G4StackManager & G4StackManager::operator= (const G4StackManager & right) private
Definition at line 77 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 77 of file G4StackManager.cc
G4bool G4StackManager::operator== (const G4StackManager & right) const private
Definition at line 78 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 78 of file G4StackManager.cc
G4Track * G4StackManager::PopNextTrack (G4VTrajectory ** newTrajectory)
Definition at line 164 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 164 of file G4StackManager.cc
References additionalWaitingStacks, G4cout, G4endl, GetNUrgentTrack(), GetNWaitingTrack(), G4Track::GetParentID(), G4StackedTrack::GetTrack(), G4Track::GetTrackID(), G4StackedTrack::GetTrajectory(), G4UserStackingAction::NewStage(), numberOfAdditionalWaitingStacks, G4TrackStack::PopFromStack(), G4TrackStack::TransferTo(), urgentStack, userStackingAction, verboseLevel, and waitingStack.
Referenced by G4EventManager::DoProcessing().
G4int G4StackManager::PrepareNewEvent ()
Definition at line 261 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 261 of file G4StackManager.cc
References additionalWaitingStacks, G4UserStackingAction::ClassifyNewTrack(), G4TrackStack::clearAndDestroy(), DefaultClassification(), FatalException, fKill, fPostpone, fUrgent, fWaiting, G4cout, G4endl, G4Exception(), GetNPostponedTrack(), G4TrackStack::GetNTrack(), G4StackedTrack::GetTrack(), G4StackedTrack::GetTrajectory(), numberOfAdditionalWaitingStacks, G4TrackStack::PopFromStack(), postponeStack, G4UserStackingAction::PrepareNewEvent(), G4TrackStack::PushToStack(), G4Track::SetParentID(), G4Track::SetTrackID(), G4TrackStack::TransferTo(), urgentStack, userStackingAction, verboseLevel, and waitingStack.
Referenced by G4EventManager::DoProcessing().
G4int G4StackManager::PushOneTrack (G4Track * newTrack, G4VTrajectory * newTrajectory = 0)
Definition at line 91 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 91 of file G4StackManager.cc
References additionalWaitingStacks, G4UserStackingAction::ClassifyNewTrack(), DefaultClassification(), FatalException, fKill, fPostpone, fUrgent, fWaiting, G4cout, G4endl, G4Exception(), G4Track::GetCreatorProcess(), GetNUrgentTrack(), G4Track::GetParentID(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleDefinitionID(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4Track::GetTrackID(), numberOfAdditionalWaitingStacks, postponeStack, G4TrackStack::PushToStack(), urgentStack, userStackingAction, verboseLevel, and waitingStack.
Referenced by G4EventManager::DoProcessing(), and G4EventManager::StackTracks().
void G4StackManager::ReClassify ()
Definition at line 217 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 217 of file G4StackManager.cc
References additionalWaitingStacks, G4UserStackingAction::ClassifyNewTrack(), FatalException, fKill, fPostpone, fUrgent, fWaiting, G4endl, G4Exception(), G4TrackStack::GetNTrack(), GetNUrgentTrack(), G4StackedTrack::GetTrack(), G4StackedTrack::GetTrajectory(), numberOfAdditionalWaitingStacks, G4TrackStack::PopFromStack(), postponeStack, G4TrackStack::PushToStack(), G4TrackStack::TransferTo(), urgentStack, userStackingAction, and waitingStack.
Referenced by export_G4StackManager(), ExN04StackingAction::NewStage(), CCalStackingAction::NewStage(), RE05StackingAction::NewStage(), and G4AdjointStackingAction::NewStage().
void G4StackManager::SetNumberOfAdditionalWaitingStacks (G4int iAdd)
Definition at line 333 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 333 of file G4StackManager.cc
References additionalWaitingStacks, and numberOfAdditionalWaitingStacks.
Referenced by G4EventManager::SetNumberOfAdditionalWaitingStacks().
void G4StackManager::SetUserStackingAction (G4UserStackingAction * value)
Definition at line 540 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 540 of file G4StackManager.cc
References G4UserStackingAction::SetStackManager(), and userStackingAction.
Referenced by G4EventManager::SetUserAction().
void G4StackManager::SetVerboseLevel (G4int const value)
Definition at line 535 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 535 of file G4StackManager.cc
References verboseLevel.
Referenced by export_G4StackManager(), G4StackingMessenger::SetNewValue(), and G4EventManager::SetVerboseLevel().
void G4StackManager::TransferOneStackedTrack (G4ClassificationOfNewTrack origin, G4ClassificationOfNewTrack destination)
Definition at line 414 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 414 of file G4StackManager.cc
References additionalWaitingStacks, fKill, fPostpone, fUrgent, fWaiting, G4TrackStack::GetNTrack(), G4StackedTrack::GetTrack(), G4StackedTrack::GetTrajectory(), numberOfAdditionalWaitingStacks, G4TrackStack::PopFromStack(), postponeStack, G4TrackStack::PushToStack(), urgentStack, and waitingStack.
Referenced by RE01StackingAction::NewStage().
void G4StackManager::TransferStackedTracks (G4ClassificationOfNewTrack origin, G4ClassificationOfNewTrack destination)
Definition at line 353 of file G4StackManager.cc.
View newest version in sPHENIX GitHub at line 353 of file G4StackManager.cc
References additionalWaitingStacks, G4TrackStack::clearAndDestroy(), fKill, fPostpone, fUrgent, fWaiting, numberOfAdditionalWaitingStacks, postponeStack, G4TrackStack::TransferTo(), urgentStack, and waitingStack.
Referenced by RE01StackingAction::NewStage().
Member Data Documentation
std::vector<G4TrackStack*> G4StackManager::additionalWaitingStacks private
Definition at line 119 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4StackManager.hh
Referenced by ClearWaitingStack(), GetNTotalTrack(), GetNWaitingTrack(), PopNextTrack(), PrepareNewEvent(), PushOneTrack(), ReClassify(), SetNumberOfAdditionalWaitingStacks(), TransferOneStackedTrack(), TransferStackedTracks(), and ~G4StackManager().
G4int G4StackManager::numberOfAdditionalWaitingStacks private
Definition at line 120 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4StackManager.hh
Referenced by clear(), ClearWaitingStack(), GetNTotalTrack(), GetNWaitingTrack(), PopNextTrack(), PrepareNewEvent(), PushOneTrack(), ReClassify(), SetNumberOfAdditionalWaitingStacks(), TransferOneStackedTrack(), TransferStackedTracks(), and ~G4StackManager().
G4TrackStack* G4StackManager::postponeStack private
Definition at line 117 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 117 of file G4StackManager.hh
Referenced by ClearPostponeStack(), G4StackManager(), GetNPostponedTrack(), GetNTotalTrack(), PrepareNewEvent(), PushOneTrack(), ReClassify(), TransferOneStackedTrack(), TransferStackedTracks(), and ~G4StackManager().
G4StackingMessenger* G4StackManager::theMessenger private
Definition at line 118 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 118 of file G4StackManager.hh
Referenced by G4StackManager(), and ~G4StackManager().
G4TrackStack* G4StackManager::urgentStack private
Definition at line 114 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 114 of file G4StackManager.hh
Referenced by ClearUrgentStack(), G4StackManager(), GetNTotalTrack(), GetNUrgentTrack(), PopNextTrack(), PrepareNewEvent(), PushOneTrack(), ReClassify(), TransferOneStackedTrack(), TransferStackedTracks(), and ~G4StackManager().
G4UserStackingAction* G4StackManager::userStackingAction private
Definition at line 109 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 109 of file G4StackManager.hh
Referenced by PopNextTrack(), PrepareNewEvent(), PushOneTrack(), ReClassify(), SetUserStackingAction(), and ~G4StackManager().
G4int G4StackManager::verboseLevel private
Definition at line 110 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 110 of file G4StackManager.hh
Referenced by PopNextTrack(), PrepareNewEvent(), PushOneTrack(), SetVerboseLevel(), and ~G4StackManager().
G4TrackStack* G4StackManager::waitingStack private
Definition at line 116 of file G4StackManager.hh.
View newest version in sPHENIX GitHub at line 116 of file G4StackManager.hh
Referenced by ClearWaitingStack(), G4StackManager(), GetNTotalTrack(), GetNWaitingTrack(), PopNextTrack(), PrepareNewEvent(), PushOneTrack(), ReClassify(), TransferOneStackedTrack(), TransferStackedTracks(), and ~G4StackManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4StackManager.hh
geant4/tree/geant4-10.6-release/source/event/src/G4StackManager.cc