ECCE @ EIC Software: ECCEhpDIRCFastPIDMap Class Reference
ECCEhpDIRCFastPIDMap Class Reference
ECCEhpDIRCFastPIDMap Import from DrcPidFast.
#include <ecce-detectors/blob/master/FastPID/ECCEhpDIRCFastPIDMap.h>
Classes
struct DrcPidInfo
Public Member Functions
ECCEhpDIRCFastPIDMap ()
virtual ~ECCEhpDIRCFastPIDMap ()
PIDCandidate_LogLikelihood_map getFastSmearLogLikelihood (int truth_pid, const double momentum, const double theta) const override
void ReadMap (const std::string &name)
read Cherenkov track resolution map from a file
TH2F * GetTrrMap ()
Public Member Functions inherited from ECCEFastPIDMap
ECCEFastPIDMap (const std::string &name="ECCEFastPIDMap")
virtual ~ECCEFastPIDMap ()
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Private Member Functions
static int get_pid (int pdg)
static EICPIDDefs::PIDCandidate get_PIDCandidate (int id)
Private Attributes
TH2F * fTrrMap = nullptr
double fMass [5] = {0}
TF1 * fMs_mom = nullptr
TF1 * fMs_thickness = nullptr
double fMs_thickness_max = (0)
Additional Inherited Members
Public Types inherited from ECCEFastPIDMap
typedef std::map
< EICPIDDefs::PIDCandidate,
float > PIDCandidate_LogLikelihood_map
Detailed Description
ECCEhpDIRCFastPIDMap Import from DrcPidFast.
Definition at line 25 of file ECCEhpDIRCFastPIDMap.h.
View newest version in sPHENIX GitHub at line 25 of file ECCEhpDIRCFastPIDMap.h
Constructor & Destructor Documentation
ECCEhpDIRCFastPIDMap::ECCEhpDIRCFastPIDMap ()
Definition at line 23 of file ECCEhpDIRCFastPIDMap.cc.
View newest version in sPHENIX GitHub at line 23 of file ECCEhpDIRCFastPIDMap.cc
References e, fMass, fMs_mom, fMs_thickness, and fMs_thickness_max.
ECCEhpDIRCFastPIDMap::~ECCEhpDIRCFastPIDMap () virtual
Definition at line 52 of file ECCEhpDIRCFastPIDMap.cc.
View newest version in sPHENIX GitHub at line 52 of file ECCEhpDIRCFastPIDMap.cc
Member Function Documentation
int ECCEhpDIRCFastPIDMap::get_pid (int pdg) static private
Definition at line 166 of file ECCEhpDIRCFastPIDMap.cc.
View newest version in sPHENIX GitHub at line 166 of file ECCEhpDIRCFastPIDMap.cc
References pid.
Referenced by getFastSmearLogLikelihood().
EICPIDDefs::PIDCandidate ECCEhpDIRCFastPIDMap::get_PIDCandidate (int id) static private
Definition at line 181 of file ECCEhpDIRCFastPIDMap.cc.
View newest version in sPHENIX GitHub at line 181 of file ECCEhpDIRCFastPIDMap.cc
References EICPIDDefs::ElectronCandiate, EICPIDDefs::InvalidCandiate, EICPIDDefs::KaonCandiate, EICPIDDefs::MuonCandiate, EICPIDDefs::PionCandiate, and EICPIDDefs::ProtonCandiate.
Referenced by getFastSmearLogLikelihood().
ECCEhpDIRCFastPIDMap::PIDCandidate_LogLikelihood_map ECCEhpDIRCFastPIDMap::getFastSmearLogLikelihood (int truth_pid, const double momentum, const double theta) const override virtual
Implements ECCEFastPIDMap.
Definition at line 55 of file ECCEhpDIRCFastPIDMap.cc.
View newest version in sPHENIX GitHub at line 55 of file ECCEhpDIRCFastPIDMap.cc
References kdfinder::abs(), alpha, bin, ECCEhpDIRCFastPIDMap::DrcPidInfo::cangle, ECCEhpDIRCFastPIDMap::DrcPidInfo::cctr, Acts::Test::delta, fMass, fMs_mom, fMs_thickness, fMs_thickness_max, fTrrMap, get_pid(), get_PIDCandidate(), max, momentum, pid, ECCEhpDIRCFastPIDMap::DrcPidInfo::probability, ECCEhpDIRCFastPIDMap::DrcPidInfo::sigma, sum, and theta().
TH2F* ECCEhpDIRCFastPIDMap::GetTrrMap () inline
Definition at line 37 of file ECCEhpDIRCFastPIDMap.h.
View newest version in sPHENIX GitHub at line 37 of file ECCEhpDIRCFastPIDMap.h
References fTrrMap.
void ECCEhpDIRCFastPIDMap::ReadMap (const std::string & name)
read Cherenkov track resolution map from a file
Definition at line 158 of file ECCEhpDIRCFastPIDMap.cc.
View newest version in sPHENIX GitHub at line 158 of file ECCEhpDIRCFastPIDMap.cc
References file, and fTrrMap.
Referenced by DIRCReco().
Member Data Documentation
double ECCEhpDIRCFastPIDMap::fMass[5] = {0} private
Definition at line 55 of file ECCEhpDIRCFastPIDMap.h.
View newest version in sPHENIX GitHub at line 55 of file ECCEhpDIRCFastPIDMap.h
Referenced by ECCEhpDIRCFastPIDMap(), and getFastSmearLogLikelihood().
TF1* ECCEhpDIRCFastPIDMap::fMs_mom = nullptr private
Definition at line 56 of file ECCEhpDIRCFastPIDMap.h.
View newest version in sPHENIX GitHub at line 56 of file ECCEhpDIRCFastPIDMap.h
Referenced by ECCEhpDIRCFastPIDMap(), and getFastSmearLogLikelihood().
TF1* ECCEhpDIRCFastPIDMap::fMs_thickness = nullptr private
Definition at line 57 of file ECCEhpDIRCFastPIDMap.h.
View newest version in sPHENIX GitHub at line 57 of file ECCEhpDIRCFastPIDMap.h
Referenced by ECCEhpDIRCFastPIDMap(), and getFastSmearLogLikelihood().
double ECCEhpDIRCFastPIDMap::fMs_thickness_max = (0) private
Definition at line 58 of file ECCEhpDIRCFastPIDMap.h.
View newest version in sPHENIX GitHub at line 58 of file ECCEhpDIRCFastPIDMap.h
Referenced by ECCEhpDIRCFastPIDMap(), and getFastSmearLogLikelihood().
TH2F* ECCEhpDIRCFastPIDMap::fTrrMap = nullptr private
Definition at line 54 of file ECCEhpDIRCFastPIDMap.h.
View newest version in sPHENIX GitHub at line 54 of file ECCEhpDIRCFastPIDMap.h
Referenced by getFastSmearLogLikelihood(), GetTrrMap(), and ReadMap().
The documentation for this class was generated from the following files:
ecce-detectors/blob/master/FastPID/ECCEhpDIRCFastPIDMap.h
ecce-detectors/blob/master/FastPID/ECCEhpDIRCFastPIDMap.cc