ECCE @ EIC Software: B2bDetectorMessenger Class Reference
B2bDetectorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/include/B2bDetectorMessenger.hh>
Public Member Functions
B2bDetectorMessenger (B2bDetectorConstruction *)
virtual ~B2bDetectorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
B2bDetectorMessenger (B2bDetectorConstruction *)
virtual ~B2bDetectorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
B2bDetectorConstruction * fDetectorConstruction
G4UIdirectory * fB2Directory
G4UIdirectory * fDetDirectory
G4UIcmdWithAString * fTargMatCmd
G4UIcmdWithAString * fChamMatCmd
G4UIcmdWithADoubleAndUnit * fStepMaxCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Messenger class that defines commands for B2bDetectorConstruction.
It implements commands:
/B2/det/setTargetMaterial name
/B2/det/setChamberMaterial name
/B2/det/stepMax value unit
Definition at line 50 of file B2bDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 50 of file B2bDetectorMessenger.hh
Constructor & Destructor Documentation
B2bDetectorMessenger::B2bDetectorMessenger (B2bDetectorConstruction * Det)
Definition at line 39 of file B2bDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 39 of file B2bDetectorMessenger.cc
References G4UIcommand::AvailableForStates(), fB2Directory, fChamMatCmd, fDetDirectory, fStepMaxCmd, fTargMatCmd, G4State_Idle, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
B2bDetectorMessenger::~B2bDetectorMessenger () virtual
Definition at line 68 of file B2bDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 68 of file B2bDetectorMessenger.cc
References fB2Directory, fChamMatCmd, fDetDirectory, fStepMaxCmd, and fTargMatCmd.
B2bDetectorMessenger::B2bDetectorMessenger (B2bDetectorConstruction *)
virtual B2bDetectorMessenger::~B2bDetectorMessenger () virtual
Member Function Documentation
void B2bDetectorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 79 of file B2bDetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 79 of file B2bDetectorMessenger.cc
References fChamMatCmd, fDetectorConstruction, fStepMaxCmd, fTargMatCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), B2bDetectorConstruction::SetChamberMaterial(), B2bDetectorConstruction::SetMaxStep(), and B2bDetectorConstruction::SetTargetMaterial().
virtual void B2bDetectorMessenger::SetNewValue (G4UIcommand * , G4String) virtual
Reimplemented from G4UImessenger.
Member Data Documentation
G4UIdirectory * B2bDetectorMessenger::fB2Directory private
Definition at line 61 of file B2bDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file B2bDetectorMessenger.hh
Referenced by B2bDetectorMessenger(), and ~B2bDetectorMessenger().
G4UIcmdWithAString * B2bDetectorMessenger::fChamMatCmd private
Definition at line 65 of file B2bDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file B2bDetectorMessenger.hh
Referenced by B2bDetectorMessenger(), SetNewValue(), and ~B2bDetectorMessenger().
G4UIdirectory * B2bDetectorMessenger::fDetDirectory private
Definition at line 62 of file B2bDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file B2bDetectorMessenger.hh
Referenced by B2bDetectorMessenger(), and ~B2bDetectorMessenger().
B2bDetectorConstruction * B2bDetectorMessenger::fDetectorConstruction private
Definition at line 59 of file B2bDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file B2bDetectorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADoubleAndUnit * B2bDetectorMessenger::fStepMaxCmd private
Definition at line 67 of file B2bDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file B2bDetectorMessenger.hh
Referenced by B2bDetectorMessenger(), SetNewValue(), and ~B2bDetectorMessenger().
G4UIcmdWithAString * B2bDetectorMessenger::fTargMatCmd private
Definition at line 64 of file B2bDetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file B2bDetectorMessenger.hh
Referenced by B2bDetectorMessenger(), SetNewValue(), and ~B2bDetectorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/include/B2bDetectorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/include/B2bDetectorMessenger.hh
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/src/B2bDetectorMessenger.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/src/B2bDetectorMessenger.cc