ECCE @ EIC Software: CCalPrimaryGeneratorMessenger Class Reference
CCalPrimaryGeneratorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalPrimaryGeneratorMessenger.hh>
Public Member Functions
CCalPrimaryGeneratorMessenger (CCalPrimaryGeneratorAction *myGun)
~CCalPrimaryGeneratorMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
CCalPrimaryGeneratorAction * myAction
G4UIcmdWithAnInteger * verboseCmd
G4UIcmdWithAString * rndmCmd
G4UIcmdWithAString * scanCmd
G4UIcmdWithADoubleAndUnit * minEnergyCmd
G4UIcmdWithADoubleAndUnit * maxEnergyCmd
G4UIcmdWithADoubleAndUnit * minPhiCmd
G4UIcmdWithADoubleAndUnit * maxPhiCmd
G4UIcmdWithADouble * minEtaCmd
G4UIcmdWithADouble * maxEtaCmd
G4UIcmdWithAnInteger * stepsPhiCmd
G4UIcmdWithAnInteger * stepsEtaCmd
G4UIcmdWithAnInteger * runNoCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 44 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 44 of file CCalPrimaryGeneratorMessenger.hh
Constructor & Destructor Documentation
CCalPrimaryGeneratorMessenger::CCalPrimaryGeneratorMessenger (CCalPrimaryGeneratorAction * myGun)
Definition at line 43 of file CCalPrimaryGeneratorMessenger.cc.
View newest version in sPHENIX GitHub at line 43 of file CCalPrimaryGeneratorMessenger.cc
References G4UIcommand::AvailableForStates(), G4State_Idle, G4State_PreInit, maxEnergyCmd, maxEtaCmd, maxPhiCmd, minEnergyCmd, minEtaCmd, minPhiCmd, pi, rndmCmd, runNoCmd, scanCmd, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), stepsEtaCmd, stepsPhiCmd, and verboseCmd.
CCalPrimaryGeneratorMessenger::~CCalPrimaryGeneratorMessenger ()
Definition at line 132 of file CCalPrimaryGeneratorMessenger.cc.
View newest version in sPHENIX GitHub at line 132 of file CCalPrimaryGeneratorMessenger.cc
References maxEnergyCmd, maxEtaCmd, maxPhiCmd, minEnergyCmd, minEtaCmd, minPhiCmd, rndmCmd, runNoCmd, scanCmd, stepsEtaCmd, stepsPhiCmd, and verboseCmd.
Member Function Documentation
void CCalPrimaryGeneratorMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 161 of file CCalPrimaryGeneratorMessenger.cc.
View newest version in sPHENIX GitHub at line 161 of file CCalPrimaryGeneratorMessenger.cc
References G4UIcmdWithADouble::GetNewDoubleValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), maxEnergyCmd, maxEtaCmd, maxPhiCmd, minEnergyCmd, minEtaCmd, minPhiCmd, myAction, rndmCmd, runNoCmd, scanCmd, CCalPrimaryGeneratorAction::SetMaximumEnergy(), CCalPrimaryGeneratorAction::SetMaximumEta(), CCalPrimaryGeneratorAction::SetMaximumPhi(), CCalPrimaryGeneratorAction::SetMinimumEnergy(), CCalPrimaryGeneratorAction::SetMinimumEta(), CCalPrimaryGeneratorAction::SetMinimumPhi(), CCalPrimaryGeneratorAction::SetRandom(), CCalPrimaryGeneratorAction::SetRunNo(), CCalPrimaryGeneratorAction::SetScan(), CCalPrimaryGeneratorAction::SetStepsEta(), CCalPrimaryGeneratorAction::SetStepsPhi(), CCalPrimaryGeneratorAction::SetVerboseLevel(), stepsEtaCmd, stepsPhiCmd, and verboseCmd.
Member Data Documentation
G4UIcmdWithADoubleAndUnit* CCalPrimaryGeneratorMessenger::maxEnergyCmd private
Definition at line 59 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithADouble* CCalPrimaryGeneratorMessenger::maxEtaCmd private
Definition at line 63 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithADoubleAndUnit* CCalPrimaryGeneratorMessenger::maxPhiCmd private
Definition at line 61 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithADoubleAndUnit* CCalPrimaryGeneratorMessenger::minEnergyCmd private
Definition at line 58 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithADouble* CCalPrimaryGeneratorMessenger::minEtaCmd private
Definition at line 62 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithADoubleAndUnit* CCalPrimaryGeneratorMessenger::minPhiCmd private
Definition at line 60 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
CCalPrimaryGeneratorAction* CCalPrimaryGeneratorMessenger::myAction private
Definition at line 53 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 53 of file CCalPrimaryGeneratorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* CCalPrimaryGeneratorMessenger::rndmCmd private
Definition at line 56 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithAnInteger* CCalPrimaryGeneratorMessenger::runNoCmd private
Definition at line 66 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithAString* CCalPrimaryGeneratorMessenger::scanCmd private
Definition at line 57 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithAnInteger* CCalPrimaryGeneratorMessenger::stepsEtaCmd private
Definition at line 65 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithAnInteger* CCalPrimaryGeneratorMessenger::stepsPhiCmd private
Definition at line 64 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
G4UIcmdWithAnInteger* CCalPrimaryGeneratorMessenger::verboseCmd private
Definition at line 55 of file CCalPrimaryGeneratorMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file CCalPrimaryGeneratorMessenger.hh
Referenced by CCalPrimaryGeneratorMessenger(), SetNewValue(), and ~CCalPrimaryGeneratorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalPrimaryGeneratorMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalPrimaryGeneratorMessenger.cc