ECCE @ EIC Software: G4OutBitStream Class Reference
G4OutBitStream Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTOutBitStream.hh>
Public Member Functions
G4OutBitStream (int size)
~G4OutBitStream ()
void SetBits (int v, int numBits)
void SetByte (u_char dat)
void SetWord (u_int dat)
void CopyByte (const char *src, int n)
u_char * GetStreamAddress (void)
int GetStreamSize (void)
Protected Member Functions
void IncBuf (void)
void FullBit (void)
void Set8Bits (u_char v, int numBits)
void SetFewBits (u_char v, int numBits)
void SetBits2Byte (u_char v, int numBits)
Protected Attributes
u_char * mHeadOfBuf
u_char * mBuf
u_char * mEndOfBuf
int mBitPos
int mWriteFlag
Detailed Description
Definition at line 43 of file G4RTOutBitStream.hh.
View newest version in sPHENIX GitHub at line 43 of file G4RTOutBitStream.hh
Constructor & Destructor Documentation
G4OutBitStream::G4OutBitStream (int size)
Definition at line 37 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 37 of file G4RTOutBitStream.cc
References mBitPos, mBuf, mEndOfBuf, mHeadOfBuf, and mWriteFlag.
G4OutBitStream::~G4OutBitStream ()
Definition at line 54 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 54 of file G4RTOutBitStream.cc
References mBuf.
Member Function Documentation
void G4OutBitStream::CopyByte (const char * src, int n)
Definition at line 157 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 157 of file G4RTOutBitStream.cc
References FullBit(), mBuf, mEndOfBuf, and n.
Referenced by G4JpegCoder::WriteHeader().
void G4OutBitStream::FullBit (void) protected
Definition at line 124 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 124 of file G4RTOutBitStream.cc
References BitFullMaskT, mBitPos, and SetFewBits().
Referenced by CopyByte(), SetByte(), and SetWord().
u_char* G4OutBitStream::GetStreamAddress (void) inline
Definition at line 53 of file G4RTOutBitStream.hh.
View newest version in sPHENIX GitHub at line 53 of file G4RTOutBitStream.hh
References mHeadOfBuf.
Referenced by G4JpegCoder::GetJpegData().
int G4OutBitStream::GetStreamSize (void) inline
Definition at line 54 of file G4RTOutBitStream.hh.
View newest version in sPHENIX GitHub at line 54 of file G4RTOutBitStream.hh
Referenced by G4JpegCoder::GetJpegData().
void G4OutBitStream::IncBuf (void) protected
Definition at line 60 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 60 of file G4RTOutBitStream.cc
References mBuf, mEndOfBuf, and mWriteFlag.
Referenced by SetBits2Byte(), SetByte(), SetFewBits(), and SetWord().
void G4OutBitStream::Set8Bits (u_char v, int numBits) protected
Definition at line 114 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 114 of file G4RTOutBitStream.cc
References mBitPos, SetBits2Byte(), and SetFewBits().
Referenced by SetBits().
void G4OutBitStream::SetBits (int v, int numBits)
Definition at line 69 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 69 of file G4RTOutBitStream.cc
References Set8Bits().
Referenced by G4JpegCoder::CodeHuffman().
void G4OutBitStream::SetBits2Byte (u_char v, int numBits) protected
Definition at line 98 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 98 of file G4RTOutBitStream.cc
References BitFullMaskT, IncBuf(), mBitPos, and mBuf.
Referenced by Set8Bits().
void G4OutBitStream::SetByte (u_char dat)
Definition at line 131 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 131 of file G4RTOutBitStream.cc
References FullBit(), IncBuf(), mBuf, and mWriteFlag.
Referenced by G4JpegCoder::WriteEOI(), and G4JpegCoder::WriteHeader().
void G4OutBitStream::SetFewBits (u_char v, int numBits) protected
Definition at line 83 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 83 of file G4RTOutBitStream.cc
References BitFullMaskT, IncBuf(), mBitPos, and mBuf.
Referenced by FullBit(), and Set8Bits().
void G4OutBitStream::SetWord (u_int dat)
Definition at line 143 of file G4RTOutBitStream.cc.
View newest version in sPHENIX GitHub at line 143 of file G4RTOutBitStream.cc
References FullBit(), IncBuf(), mBuf, and mWriteFlag.
Referenced by G4JpegCoder::WriteHeader().
Member Data Documentation
int G4OutBitStream::mBitPos protected
Definition at line 61 of file G4RTOutBitStream.hh.
View newest version in sPHENIX GitHub at line 61 of file G4RTOutBitStream.hh
Referenced by FullBit(), G4OutBitStream(), Set8Bits(), SetBits2Byte(), and SetFewBits().
u_char* G4OutBitStream::mBuf protected
Definition at line 59 of file G4RTOutBitStream.hh.
View newest version in sPHENIX GitHub at line 59 of file G4RTOutBitStream.hh
Referenced by CopyByte(), G4OutBitStream(), IncBuf(), SetBits2Byte(), SetByte(), SetFewBits(), SetWord(), and ~G4OutBitStream().
u_char* G4OutBitStream::mEndOfBuf protected
Definition at line 60 of file G4RTOutBitStream.hh.
View newest version in sPHENIX GitHub at line 60 of file G4RTOutBitStream.hh
Referenced by CopyByte(), G4OutBitStream(), and IncBuf().
u_char* G4OutBitStream::mHeadOfBuf protected
Definition at line 54 of file G4RTOutBitStream.hh.
View newest version in sPHENIX GitHub at line 54 of file G4RTOutBitStream.hh
Referenced by G4OutBitStream(), and GetStreamAddress().
int G4OutBitStream::mWriteFlag protected
Definition at line 62 of file G4RTOutBitStream.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RTOutBitStream.hh
Referenced by G4OutBitStream(), IncBuf(), SetByte(), and SetWord().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTOutBitStream.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4RTOutBitStream.cc