ECCE @ EIC Software: RE01DetectorConstruction Class Reference
RE01DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01DetectorConstruction.hh>
Public Member Functions
RE01DetectorConstruction ()
virtual ~RE01DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4double fExpHall_x
G4double fExpHall_y
G4double fExpHall_z
G4double fTrkTubs_rmax
G4double fTrkTubs_rmin
G4double fTrkTubs_dz
G4double fTrkTubs_sphi
G4double fTrkTubs_dphi
G4int fNotrkLayers
G4double fTracker_radius [5]
G4double fTracker_thick
G4double fTracker_length [5]
G4double fCaloTubs_rmax
G4double fCaloTubs_rmin
G4double fCaloTubs_dz
G4double fCaloTubs_sphi
G4double fCaloTubs_dphi
G4int fNocaloLayers
G4double fAbsorber_thick
G4double fScinti_thick
G4int fSegmentsinZ
G4double fCaloRing_rmax
G4double fCaloRing_rmin
G4double fCaloRing_dz
G4double fCaloRing_sphi
G4double fCaloRing_dphi
G4int fSegmentsinPhi
G4double fCaloCell_rmax
G4double fCaloCell_rmin
G4double fCaloCell_dz
G4double fCaloCell_sphi
G4double fCaloCell_dphi
G4LogicalVolume * fTrackerLayer_log
G4LogicalVolume * fCalorimeter_log
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 40 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 40 of file RE01DetectorConstruction.hh
Constructor & Destructor Documentation
RE01DetectorConstruction::RE01DetectorConstruction ()
RE01DetectorConstruction::~RE01DetectorConstruction () virtual
Definition at line 68 of file RE01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 68 of file RE01DetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * RE01DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 72 of file RE01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 72 of file RE01DetectorConstruction.cc
References a, G4Material::AddElement(), G4Region::AddRootLogicalVolume(), cm3, fCalorimeter_log, fCaloRing_dphi, fCaloRing_dz, fCaloRing_rmax, fCaloRing_rmin, fCaloRing_sphi, fCaloTubs_dphi, fCaloTubs_dz, fCaloTubs_rmax, fCaloTubs_rmin, fCaloTubs_sphi, fExpHall_x, fExpHall_y, fExpHall_z, G4NistManager::FindOrBuildMaterial(), fNocaloLayers, fNotrkLayers, fTrackerLayer_log, fTrkTubs_dphi, fTrkTubs_dz, fTrkTubs_rmax, fTrkTubs_rmin, fTrkTubs_sphi, Acts::UnitConstants::g, G4RegionStore::GetInstance(), G4NistManager::Instance(), kXAxis, mole, RE01RegionInformation::Print(), RE01RegionInformation::SetCalorimeter(), G4VisAttributes::SetForceWireframe(), G4LogicalVolume::SetRegion(), RE01RegionInformation::SetTracker(), G4Region::SetUserInformation(), G4LogicalVolume::SetVisAttributes(), and RE01RegionInformation::SetWorld().
void RE01DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 205 of file RE01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 205 of file RE01DetectorConstruction.cc
References G4SDManager::AddNewDetector(), G4FieldManager::CreateChordFinder(), fTrackerLayer_log, G4TransportationManager::GetFieldManager(), G4SDManager::GetSDMpointer(), G4TransportationManager::GetTransportationManager(), G4FieldManager::SetDetectorField(), and G4VUserDetectorConstruction::SetSensitiveDetector().
Member Data Documentation
G4double RE01DetectorConstruction::fAbsorber_thick private
Definition at line 54 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 54 of file RE01DetectorConstruction.hh
G4double RE01DetectorConstruction::fCaloCell_dphi private
Definition at line 69 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 69 of file RE01DetectorConstruction.hh
G4double RE01DetectorConstruction::fCaloCell_dz private
Definition at line 67 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file RE01DetectorConstruction.hh
G4double RE01DetectorConstruction::fCaloCell_rmax private
Definition at line 65 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 65 of file RE01DetectorConstruction.hh
G4double RE01DetectorConstruction::fCaloCell_rmin private
Definition at line 66 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file RE01DetectorConstruction.hh
G4double RE01DetectorConstruction::fCaloCell_sphi private
Definition at line 68 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 68 of file RE01DetectorConstruction.hh
G4LogicalVolume* RE01DetectorConstruction::fCalorimeter_log private
Definition at line 54 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 54 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloRing_dphi private
Definition at line 62 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 62 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloRing_dz private
Definition at line 60 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 60 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloRing_rmax private
Definition at line 58 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 58 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloRing_rmin private
Definition at line 59 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 59 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloRing_sphi private
Definition at line 61 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 61 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloTubs_dphi private
Definition at line 51 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 51 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloTubs_dz private
Definition at line 49 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 49 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloTubs_rmax private
Definition at line 47 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 47 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloTubs_rmin private
Definition at line 48 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 48 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fCaloTubs_sphi private
Definition at line 50 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 50 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fExpHall_x private
Definition at line 32 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 32 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fExpHall_y private
Definition at line 33 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 33 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fExpHall_z private
Definition at line 34 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 34 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4int RE01DetectorConstruction::fNocaloLayers private
Definition at line 53 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 53 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4int RE01DetectorConstruction::fNotrkLayers private
Definition at line 42 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 42 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fScinti_thick private
Definition at line 55 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file RE01DetectorConstruction.hh
G4int RE01DetectorConstruction::fSegmentsinPhi private
Definition at line 64 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 64 of file RE01DetectorConstruction.hh
G4int RE01DetectorConstruction::fSegmentsinZ private
Definition at line 57 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 57 of file RE01DetectorConstruction.hh
G4double RE01DetectorConstruction::fTracker_length[5] private
Definition at line 45 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 45 of file RE01DetectorConstruction.hh
G4double RE01DetectorConstruction::fTracker_radius[5] private
Definition at line 43 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 43 of file RE01DetectorConstruction.hh
G4double RE01DetectorConstruction::fTracker_thick private
Definition at line 44 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 44 of file RE01DetectorConstruction.hh
G4LogicalVolume* RE01DetectorConstruction::fTrackerLayer_log private
Definition at line 53 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 53 of file RE01DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4double RE01DetectorConstruction::fTrkTubs_dphi private
Definition at line 40 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 40 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fTrkTubs_dz private
Definition at line 38 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 38 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fTrkTubs_rmax private
Definition at line 36 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 36 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fTrkTubs_rmin private
Definition at line 37 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 37 of file RE01DetectorConstruction.hh
Referenced by Construct().
G4double RE01DetectorConstruction::fTrkTubs_sphi private
Definition at line 39 of file RE01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 39 of file RE01DetectorConstruction.hh
Referenced by Construct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/include/RE01DetectorParameterDef.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE01/src/RE01DetectorConstruction.cc