ECCE @ EIC Software: G4PhysicsOrderedFreeVector Class Reference
G4PhysicsOrderedFreeVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4PhysicsOrderedFreeVector.hh>
Public Member Functions
G4PhysicsOrderedFreeVector ()
G4PhysicsOrderedFreeVector (G4double *Energies, G4double *Values, size_t VectorLength)
virtual ~G4PhysicsOrderedFreeVector ()
void InsertValues (G4double energy, G4double value)
G4double GetEnergy (G4double aValue)
G4double GetMaxValue ()
G4double GetMinValue ()
G4double GetMaxLowEdgeEnergy ()
G4double GetMinLowEdgeEnergy ()
Public Member Functions inherited from G4PhysicsVector
G4PhysicsVector (G4bool spline=false)
G4PhysicsVector (const G4PhysicsVector &)
G4PhysicsVector & operator= (const G4PhysicsVector &)
virtual ~G4PhysicsVector ()
G4double Value (G4double theEnergy, size_t &lastidx) const
G4double LogVectorValue (const G4double theEnergy, const G4double theLogEnergy) const
G4double Value (G4double theEnergy) const
G4double GetValue (G4double theEnergy, G4bool &isOutRange) const
G4bool operator== (const G4PhysicsVector &right) const
G4bool operator!= (const G4PhysicsVector &right) const
G4double operator[] (const size_t index) const
G4double operator() (const size_t index) const
void PutValue (size_t index, G4double theValue)
virtual void ScaleVector (G4double factorE, G4double factorV)
G4double Energy (size_t index) const
G4double GetMaxEnergy () const
G4double GetLowEdgeEnergy (size_t binNumber) const
size_t GetVectorLength () const
size_t FindBin (G4double energy, size_t idx) const
size_t ComputeLogVectorBin (const G4double logenergy) const
void FillSecondDerivatives ()
void ComputeSecDerivatives ()
void ComputeSecondDerivatives (G4double firstPointDerivative, G4double endPointDerivative)
G4double FindLinearEnergy (G4double rand) const
G4bool IsFilledVectorExist () const
G4PhysicsVectorType GetType () const
void SetSpline (G4bool)
G4bool Store (std::ofstream &fOut, G4bool ascii=false) const
virtual G4bool Retrieve (std::ifstream &fIn, G4bool ascii=false)
void DumpValues (G4double unitE=1.0, G4double unitV=1.0) const
void SetVerboseLevel (G4int value)
G4double Interpolation (size_t idx, G4double energy) const
Private Member Functions
size_t FindValueBinLocation (G4double aValue)
G4double LinearInterpolationOfEnergy (G4double aValue, size_t theLocBin)
Additional Inherited Members
Protected Member Functions inherited from G4PhysicsVector
void DeleteData ()
void CopyData (const G4PhysicsVector &vec)
void PrintPutValueError (size_t index)
Protected Attributes inherited from G4PhysicsVector
G4PhysicsVectorType type
G4double edgeMin
G4double edgeMax
size_t numberOfNodes
G4PVDataVector dataVector
G4PVDataVector binVector
G4PVDataVector secDerivative
G4double invdBin
G4double baseBin
G4int verboseLevel
Detailed Description
Definition at line 66 of file G4PhysicsOrderedFreeVector.hh.
View newest version in sPHENIX GitHub at line 66 of file G4PhysicsOrderedFreeVector.hh
Constructor & Destructor Documentation
G4PhysicsOrderedFreeVector::G4PhysicsOrderedFreeVector ()
Definition at line 53 of file G4PhysicsOrderedFreeVector.cc.
View newest version in sPHENIX GitHub at line 53 of file G4PhysicsOrderedFreeVector.cc
References T_G4PhysicsOrderedFreeVector, and G4PhysicsVector::type.
G4PhysicsOrderedFreeVector::G4PhysicsOrderedFreeVector (G4double * Energies, G4double * Values, size_t VectorLength)
Definition at line 59 of file G4PhysicsOrderedFreeVector.cc.
View newest version in sPHENIX GitHub at line 59 of file G4PhysicsOrderedFreeVector.cc
References G4PhysicsVector::binVector, G4PhysicsVector::dataVector, InsertValues(), T_G4PhysicsOrderedFreeVector, and G4PhysicsVector::type.
G4PhysicsOrderedFreeVector::~G4PhysicsOrderedFreeVector () virtual
Definition at line 75 of file G4PhysicsOrderedFreeVector.cc.
View newest version in sPHENIX GitHub at line 75 of file G4PhysicsOrderedFreeVector.cc
Member Function Documentation
size_t G4PhysicsOrderedFreeVector::FindValueBinLocation (G4double aValue) private
Definition at line 109 of file G4PhysicsOrderedFreeVector.cc.
View newest version in sPHENIX GitHub at line 109 of file G4PhysicsOrderedFreeVector.cc
References bin, G4PhysicsVector::dataVector, min, and G4PhysicsVector::numberOfNodes.
Referenced by GetEnergy().
G4double G4PhysicsOrderedFreeVector::GetEnergy (G4double aValue)
Definition at line 95 of file G4PhysicsOrderedFreeVector.cc.
View newest version in sPHENIX GitHub at line 95 of file G4PhysicsOrderedFreeVector.cc
References e, G4PhysicsVector::edgeMax, G4PhysicsVector::edgeMin, FindValueBinLocation(), GetMaxValue(), GetMinValue(), and LinearInterpolationOfEnergy().
Referenced by G4SPSEneDistribution::GenEpnHistEnergies(), WLSPrimaryGeneratorAction::GeneratePrimaries(), G4SPSAngDistribution::GenerateUserDefPhi(), G4SPSAngDistribution::GenerateUserDefTheta(), G4SPSRandomGenerator::GenRandEnergy(), G4SPSRandomGenerator::GenRandPhi(), G4SPSRandomGenerator::GenRandPosPhi(), G4SPSRandomGenerator::GenRandPosTheta(), G4SPSRandomGenerator::GenRandTheta(), G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), G4SPSRandomGenerator::GenRandZ(), G4SPSEneDistribution::GenUserHistEnergies(), G4Cerenkov::GetAverageNumberOfPhotons(), G4OpWLS::PostStepDoIt(), and G4Scintillation::PostStepDoIt().
G4double G4PhysicsOrderedFreeVector::GetMaxLowEdgeEnergy () inline
Definition at line 124 of file G4PhysicsOrderedFreeVector.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PhysicsOrderedFreeVector.hh
References G4PhysicsVector::binVector.
Referenced by G4SPSEneDistribution::ArbInterpolate(), G4Cerenkov::GetAverageNumberOfPhotons(), and G4Cerenkov::PostStepDoIt().
G4double G4PhysicsOrderedFreeVector::GetMaxValue () inline
Definition at line 112 of file G4PhysicsOrderedFreeVector.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PhysicsOrderedFreeVector.hh
References G4PhysicsVector::dataVector.
Referenced by WLSPrimaryGeneratorAction::GeneratePrimaries(), G4Cerenkov::GetAverageNumberOfPhotons(), GetEnergy(), G4Scintillation::GetScintillationYieldByParticleType(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), and G4Cerenkov::PostStepGetPhysicalInteractionLength().
G4double G4PhysicsOrderedFreeVector::GetMinLowEdgeEnergy () inline
Definition at line 130 of file G4PhysicsOrderedFreeVector.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PhysicsOrderedFreeVector.hh
References G4PhysicsVector::binVector.
Referenced by G4SPSEneDistribution::ArbInterpolate(), G4Cerenkov::GetAverageNumberOfPhotons(), and G4Cerenkov::PostStepDoIt().
G4double G4PhysicsOrderedFreeVector::GetMinValue () inline
Definition at line 118 of file G4PhysicsOrderedFreeVector.hh.
View newest version in sPHENIX GitHub at line 118 of file G4PhysicsOrderedFreeVector.hh
References G4PhysicsVector::dataVector.
Referenced by G4Cerenkov::GetAverageNumberOfPhotons(), and GetEnergy().
void G4PhysicsOrderedFreeVector::InsertValues (G4double energy, G4double value)
Definition at line 78 of file G4PhysicsOrderedFreeVector.cc.
View newest version in sPHENIX GitHub at line 78 of file G4PhysicsOrderedFreeVector.cc
References G4PhysicsVector::binVector, G4PhysicsVector::dataVector, G4PhysicsVector::edgeMax, G4PhysicsVector::edgeMin, energy, and G4PhysicsVector::numberOfNodes.
Referenced by G4MaterialPropertiesTable::AddEntry(), G4SPSEneDistribution::ArbEnergyHisto(), G4SPSEneDistribution::ArbEnergyHistoFile(), G4Cerenkov::BuildThePhysicsTable(), G4MaterialPropertiesTable::CalculateGROUPVEL(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), G4SPSEneDistribution::ConvertEPNToEnergy(), G4SPSEneDistribution::EpnEnergyHisto(), G4SPSEneDistribution::ExpInterpolation(), G4PhysicsOrderedFreeVector(), G4SPSEneDistribution::GenEpnHistEnergies(), G4SPSAngDistribution::GenerateUserDefPhi(), G4SPSAngDistribution::GenerateUserDefTheta(), G4SPSRandomGenerator::GenRandEnergy(), G4SPSRandomGenerator::GenRandPhi(), G4SPSRandomGenerator::GenRandPosPhi(), G4SPSRandomGenerator::GenRandPosTheta(), G4SPSRandomGenerator::GenRandTheta(), G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), G4SPSRandomGenerator::GenRandZ(), G4SPSEneDistribution::GenUserHistEnergies(), G4SPSEneDistribution::LinearInterpolation(), G4SPSEneDistribution::LogInterpolation(), G4GDMLReadMaterials::PropertyRead(), G4GDMLReadSolids::PropertyRead(), G4SPSRandomGenerator::SetEnergyBias(), G4SPSRandomGenerator::SetPhiBias(), G4SPSRandomGenerator::SetPosPhiBias(), G4SPSRandomGenerator::SetPosThetaBias(), G4SPSRandomGenerator::SetThetaBias(), G4SPSRandomGenerator::SetXBias(), G4SPSRandomGenerator::SetYBias(), G4SPSRandomGenerator::SetZBias(), G4SPSEneDistribution::SplineInterpolation(), G4SPSAngDistribution::UserDefAngPhi(), G4SPSAngDistribution::UserDefAngTheta(), and G4SPSEneDistribution::UserEnergyHisto().
G4double G4PhysicsOrderedFreeVector::LinearInterpolationOfEnergy (G4double aValue, size_t theLocBin) private
Definition at line 117 of file G4PhysicsOrderedFreeVector.cc.
View newest version in sPHENIX GitHub at line 117 of file G4PhysicsOrderedFreeVector.cc
References bin, G4PhysicsVector::binVector, and G4PhysicsVector::dataVector.
Referenced by GetEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4PhysicsOrderedFreeVector.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4PhysicsOrderedFreeVector.cc