ECCE @ EIC Software: Dicom2Run Class Reference
Dicom2Run Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/include/Dicom2Run.hh>
Public Types
typedef G4VTHitsVector
< G4StatAnalysis, std::vector
< G4StatAnalysis > > Dicom2RunVector
Public Member Functions
Dicom2Run ()
Dicom2Run (const std::vector< G4String > mfdName)
virtual ~Dicom2Run ()
virtual void RecordEvent (const G4Event *)
size_t GetNumberOfHitsMap () const
Dicom2RunVector * GetHitsVector (G4int i) const
Dicom2RunVector * GetHitsVector (const G4String &detName, const G4String &colName) const
Dicom2RunVector * GetHitsVector (const G4String &fullName) const
void ConstructMFD (const std::vector< G4String > &)
virtual void Merge (const G4Run *)
Public Member Functions inherited from DicomRun
DicomRun ()
DicomRun (const std::vector< G4String > mfdName)
virtual ~DicomRun ()
size_t GetNumberOfHitsMap () const
G4THitsMap< G4double > * GetHitsMap (G4int i) const
G4THitsMap< G4double > * GetHitsMap (const G4String &detName, const G4String &colName) const
G4THitsMap< G4double > * GetHitsMap (const G4String &fullName) const
void ConstructMFD (const std::vector< G4String > &)
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
std::vector< G4String > fCollName
std::vector< G4int > fCollID
std::vector< Dicom2RunVector * > fRunMap
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Dicom2Run class
Demonstrates how to use G4StatAnalysis as a vector of objects (instead of vector of pointers to objects) to reduce memory consumption
Definition at line 52 of file Dicom2Run.hh.
View newest version in sPHENIX GitHub at line 52 of file Dicom2Run.hh
Member Typedef Documentation
typedef G4VTHitsVector<G4StatAnalysis, std::vector<G4StatAnalysis> > Dicom2Run::Dicom2RunVector
Definition at line 56 of file Dicom2Run.hh.
View newest version in sPHENIX GitHub at line 56 of file Dicom2Run.hh
Constructor & Destructor Documentation
Dicom2Run::Dicom2Run ()
(Description) Dicom2Run Class is for accumulating scored quantities which is scored using G4MutiFunctionalDetector and G4VPrimitiveScorer. Accumulation is done using G4THitsVector object.
The constructor Dicom2Run(const std::vector<G4String> mfdName) needs a vector filled with MultiFunctionalDetector names which was assigned at instantiation of MultiFunctionalDetector(MFD). Then Dicom2Run constructor automatically scans primitive scorers in the MFD, and obtains collectionIDs of all collections associated to those primitive scorers. Futhermore, the G4THitsVector objects for accumulating during a RUN are automatically created too. (*) Collection Name is same as primitive scorer name.
The resultant information is kept inside Dicom2Run objects as data members. std::vector<G4String> fCollName; // Collection Name, std::vector<G4int> fCollID; // Collection ID, std::vector<Dicom2RunVector*> fRunMap; // HitsVector for RUN.
The resualtant HitsVector objects are obtain using access method, GetHitsVector(..).
Definition at line 69 of file Dicom2Run.cc.
View newest version in sPHENIX GitHub at line 69 of file Dicom2Run.cc
Dicom2Run::Dicom2Run (const std::vector< G4String > mfdName)
Definition at line 77 of file Dicom2Run.cc.
View newest version in sPHENIX GitHub at line 77 of file Dicom2Run.cc
References ConstructMFD().
Dicom2Run::~Dicom2Run () virtual
Definition at line 87 of file Dicom2Run.cc.
View newest version in sPHENIX GitHub at line 87 of file Dicom2Run.cc
References fCollID, fCollName, and fRunMap.
Member Function Documentation
void Dicom2Run::ConstructMFD (const std::vector< G4String > & mfdName)
Definition at line 104 of file Dicom2Run.cc.
View newest version in sPHENIX GitHub at line 104 of file Dicom2Run.cc
References DicomRun::ConstructMFD(), fCollID, fCollName, G4SDManager::FindSensitiveDetector(), fRunMap, G4cout, G4endl, G4SDManager::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4MultiFunctionalDetector::GetNumberOfPrimitives(), G4MultiFunctionalDetector::GetPrimitive(), and G4SDManager::GetSDMpointer().
Referenced by Dicom2Run().
Dicom2RunVector* Dicom2Run::GetHitsVector (G4int i) const inline
Definition at line 75 of file Dicom2Run.hh.
View newest version in sPHENIX GitHub at line 75 of file Dicom2Run.hh
References fRunMap.
Referenced by Dicom2RunAction::EndOfRunAction(), and GetHitsVector().
Dicom2Run::Dicom2RunVector * Dicom2Run::GetHitsVector (const G4String & detName, const G4String & colName) const
Definition at line 231 of file Dicom2Run.cc.
View newest version in sPHENIX GitHub at line 231 of file Dicom2Run.cc
References GetHitsVector().
Dicom2Run::Dicom2RunVector * Dicom2Run::GetHitsVector (const G4String & fullName) const
Definition at line 243 of file Dicom2Run.cc.
View newest version in sPHENIX GitHub at line 243 of file Dicom2Run.cc
References fCollName, fRunMap, G4Exception(), and JustWarning.
size_t Dicom2Run::GetNumberOfHitsMap () const inline
Definition at line 71 of file Dicom2Run.hh.
View newest version in sPHENIX GitHub at line 71 of file Dicom2Run.hh
References fRunMap.
void Dicom2Run::Merge (const G4Run * aRun) virtual
Reimplemented from DicomRun.
Definition at line 208 of file Dicom2Run.cc.
View newest version in sPHENIX GitHub at line 208 of file Dicom2Run.cc
References Copy(), fCollID, fCollName, fRunMap, and DicomRun::Merge().
void Dicom2Run::RecordEvent (const G4Event * aEvent) virtual
Reimplemented from DicomRun.
Definition at line 165 of file Dicom2Run.cc.
View newest version in sPHENIX GitHub at line 165 of file Dicom2Run.cc
References fCollID, fRunMap, G4cout, G4endl, G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), and DicomRun::RecordEvent().
Member Data Documentation
std::vector<G4int> Dicom2Run::fCollID private
Definition at line 87 of file Dicom2Run.hh.
View newest version in sPHENIX GitHub at line 87 of file Dicom2Run.hh
Referenced by ConstructMFD(), Merge(), RecordEvent(), and ~Dicom2Run().
std::vector<G4String> Dicom2Run::fCollName private
Definition at line 86 of file Dicom2Run.hh.
View newest version in sPHENIX GitHub at line 86 of file Dicom2Run.hh
Referenced by ConstructMFD(), GetHitsVector(), Merge(), and ~Dicom2Run().
std::vector<Dicom2RunVector*> Dicom2Run::fRunMap private
Definition at line 88 of file Dicom2Run.hh.
View newest version in sPHENIX GitHub at line 88 of file Dicom2Run.hh
Referenced by ConstructMFD(), GetHitsVector(), GetNumberOfHitsMap(), Merge(), RecordEvent(), and ~Dicom2Run().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/include/Dicom2Run.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM2/src/Dicom2Run.cc