ECCE @ EIC Software: G4ExcitedNucleonConstructor Class Reference
G4ExcitedNucleonConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedNucleonConstructor.hh>
Public Types
enum { NStates = 15 }
enum { NumberOfDecayModes = 9 }
Public Member Functions
G4ExcitedNucleonConstructor ()
virtual ~G4ExcitedNucleonConstructor ()
Public Member Functions inherited from G4ExcitedBaryonConstructor
G4ExcitedBaryonConstructor (G4int nStates=0, G4int isoSpin=0)
virtual ~G4ExcitedBaryonConstructor ()
virtual void Construct (G4int indexOfState=-1)
Protected Member Functions
virtual G4int GetEncoding (G4int iIsoSpin3, G4int idxState)
virtual G4bool Exist (G4int)
virtual G4int GetQuarkContents (G4int, G4int)
virtual G4String GetName (G4int iIso3, G4int iState)
virtual G4String GetMultipletName (G4int iState)
virtual G4double GetMass (G4int state, G4int iso)
virtual G4double GetWidth (G4int state, G4int iso)
virtual G4int GetiSpin (G4int iState)
virtual G4int GetiParity (G4int iState)
virtual G4int GetEncodingOffset (G4int iState)
virtual G4DecayTable * CreateDecayTable (const G4String &name, G4int iIso3, G4int iState, G4bool fAnti=false)
Protected Member Functions inherited from G4ExcitedBaryonConstructor
virtual void ConstructParticle (G4int indexOfState)
virtual void ConstructAntiParticle (G4int indexOfState)
virtual G4double GetCharge (G4int iIsoSpin3)
Private Types
enum { NucleonIsoSpin = 1 }
enum {
NGamma =0, NPi =1, NEta =2, NOmega =3,
NRho =4, N2Pi =5, DeltaPi =6, NStarPi =7,
LambdaK = 8
}
Private Member Functions
G4DecayTable * AddNGammaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNEtaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNOmegaMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNRhoMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddN2PiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddDeltaPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddNStarPiMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
G4DecayTable * AddLambdaKMode (G4DecayTable *table, const G4String &name, G4double br, G4int iIso3, G4bool fAnti)
Static Private Attributes
static const char * name [NStates]
static const G4double mass [NStates]
static const G4double width [NStates]
static const G4int iSpin [NStates]
static const G4int iParity [NStates]
static const G4int encodingOffset [NStates]
static const G4double bRatio [NStates][NumberOfDecayModes]
Additional Inherited Members
Protected Attributes inherited from G4ExcitedBaryonConstructor
G4int NumberOfStates
G4int iIsoSpin
const G4String type
const G4int iConjugation
const G4int iGParity
const G4int leptonNumber
const G4int baryonNumber
Detailed Description
Definition at line 42 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ExcitedNucleonConstructor.hh
Member Enumeration Documentation
anonymous enum private
Enumerator:
NucleonIsoSpin
Definition at line 92 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ExcitedNucleonConstructor.hh
anonymous enum
Enumerator:
NumberOfDecayModes
Definition at line 103 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ExcitedNucleonConstructor.hh
anonymous enum private
Enumerator:
NGamma
NPi
NEta
NOmega
NRho
N2Pi
DeltaPi
NStarPi
LambdaK
Definition at line 105 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ExcitedNucleonConstructor.hh
anonymous enum
Enumerator:
NStates
Definition at line 90 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ExcitedNucleonConstructor.hh
Constructor & Destructor Documentation
G4ExcitedNucleonConstructor::G4ExcitedNucleonConstructor ()
Definition at line 46 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ExcitedNucleonConstructor.cc
G4ExcitedNucleonConstructor::~G4ExcitedNucleonConstructor () virtual
Definition at line 52 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ExcitedNucleonConstructor.cc
Member Function Documentation
G4DecayTable * G4ExcitedNucleonConstructor::AddDeltaPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 422 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 422 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert(), and r.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::AddLambdaKMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 506 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 506 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert(), and G4InuclParticleNames::lambda.
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::AddN2PiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 314 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 314 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::AddNEtaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 211 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 211 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::AddNGammaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 134 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 134 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::AddNOmegaMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 236 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 236 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::AddNPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 158 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 158 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::AddNRhoMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 261 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 261 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::AddNStarPiMode (G4DecayTable * table, const G4String & name, G4double br, G4int iIso3, G4bool fAnti) private
Definition at line 369 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 369 of file G4ExcitedNucleonConstructor.cc
References G4DecayTable::Insert().
Referenced by CreateDecayTable().
G4DecayTable * G4ExcitedNucleonConstructor::CreateDecayTable (const G4String & name, G4int iIso3, G4int iState, G4bool fAnti = false) protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 85 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ExcitedNucleonConstructor.cc
References AddDeltaPiMode(), AddLambdaKMode(), AddN2PiMode(), AddNEtaMode(), AddNGammaMode(), AddNOmegaMode(), AddNPiMode(), AddNRhoMode(), AddNStarPiMode(), bRatio, DeltaPi, LambdaK, N2Pi, NEta, NGamma, NOmega, NPi, NRho, and NStarPi.
virtual G4bool G4ExcitedNucleonConstructor::Exist (G4int) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 55 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ExcitedNucleonConstructor.hh
G4int G4ExcitedNucleonConstructor::GetEncoding (G4int iIsoSpin3, G4int idxState) protected virtual
Reimplemented from G4ExcitedBaryonConstructor.
Definition at line 56 of file G4ExcitedNucleonConstructor.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ExcitedNucleonConstructor.cc
References G4ExcitedBaryonConstructor::GetEncoding(), GetEncodingOffset(), GetiSpin(), and GetQuarkContents().
G4int G4ExcitedNucleonConstructor::GetEncodingOffset (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 136 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 136 of file G4ExcitedNucleonConstructor.hh
References encodingOffset.
Referenced by GetEncoding().
G4int G4ExcitedNucleonConstructor::GetiParity (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 130 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ExcitedNucleonConstructor.hh
References iParity.
G4int G4ExcitedNucleonConstructor::GetiSpin (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 124 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ExcitedNucleonConstructor.hh
References iSpin.
Referenced by GetEncoding().
G4double G4ExcitedNucleonConstructor::GetMass (G4int state, G4int iso) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 112 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ExcitedNucleonConstructor.hh
References mass.
G4String G4ExcitedNucleonConstructor::GetMultipletName (G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 167 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ExcitedNucleonConstructor.hh
G4String G4ExcitedNucleonConstructor::GetName (G4int iIso3, G4int iState) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 173 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ExcitedNucleonConstructor.hh
References particle.
G4int G4ExcitedNucleonConstructor::GetQuarkContents (G4int iQ, G4int iIso3) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 142 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ExcitedNucleonConstructor.hh
Referenced by GetEncoding().
G4double G4ExcitedNucleonConstructor::GetWidth (G4int state, G4int iso) inline protected virtual
Implements G4ExcitedBaryonConstructor.
Definition at line 118 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ExcitedNucleonConstructor.hh
References width.
Member Data Documentation
const G4double G4ExcitedNucleonConstructor::bRatio static private
Initial value:
=
{
   {  0.0, 0.70,  0.0,  0.0,  0.0,  0.05,  0.25,  0.0,  0.0},
   {  0.0, 0.60,  0.0,  0.0,  0.0,  0.15,  0.25,  0.0,  0.0},
   {0.001, 0.55, 0.35,  0.0,  0.0,  0.05,  0.00, 0.05,  0.0},
   {  0.0, 0.65, 0.05,  0.0,  0.0,  0.05,  0.10, 0.05, 0.10},
   {  0.0, 0.45,  0.0,  0.0,  0.0,  0.00,  0.55,  0.0,  0.0},
   {  0.0, 0.65,  0.0,  0.0,  0.0,  0.20,  0.15,  0.0,  0.0},
   {  0.0, 0.10, 0.05,  0.0, 0.05,  0.45,  0.35,  0.0,  0.0},
   {  0.0, 0.15, 0.20,  0.0, 0.05,  0.20,  0.20, 0.10, 0.10},
   {  0.0, 0.15, 0.00,  0.0, 0.25,  0.45,  0.10, 0.00, 0.05},
   {  0.0, 0.35,  0.0, 0.55, 0.05,  0.00,  0.05,  0.0,  0.0},
   {  0.0, 0.05,  0.0,  0.0, 0.15,  0.25,  0.30, 0.15, 0.10},
   {  0.0, 0.60, 0.05,  0.0, 0.25,  0.05,  0.05,  0.0,  0.0},
   {  0.0, 0.35,  0.0, 0.00, 0.30,  0.15,  0.15, 0.05,  0.0},
   {  0.0, 0.35,  0.0,  0.0, 0.25,  0.20,  0.20,  0.0,  0.0},
   {  0.0, 0.30,  0.0, 0.00, 0.25,  0.20,  0.20, 0.05,  0.0}
}
Definition at line 108 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ExcitedNucleonConstructor.hh
Referenced by CreateDecayTable().
const G4int G4ExcitedNucleonConstructor::encodingOffset static private
Initial value:
= {
   10000,       0,  20000,  30000,       0,
   10000,   20000,  40000,  30000,   40000,
   10000,   50000,       0,     0,   10000
}
Definition at line 100 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ExcitedNucleonConstructor.hh
Referenced by GetEncodingOffset().
const G4int G4ExcitedNucleonConstructor::iParity static private
Initial value:
= {
  +1,  -1,   -1,  -1,  -1,
  +1,  -1,   +1,  +1,  +1,
  +1,  -1,   +1,  -1,  -1
}
Definition at line 99 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ExcitedNucleonConstructor.hh
Referenced by GetiParity().
const G4int G4ExcitedNucleonConstructor::iSpin static private
Initial value:
= {
    1,   3,   1,   1,   5,
    5,   3,   1,   3,   3,
    7,   3,   7,   9,   9
}
Definition at line 98 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ExcitedNucleonConstructor.hh
Referenced by GetiSpin().
const G4double G4ExcitedNucleonConstructor::mass static private
Initial value:
= {
  1.430*GeV, 1.515*GeV, 1.535*GeV, 1.655*GeV,  1.675*GeV,
  1.685*GeV, 1.700*GeV, 1.710*GeV, 1.720*GeV,  1.900*GeV,
  1.950*GeV, 2.080*GeV, 2.190*GeV, 2.250*GeV,  2.275*GeV
}
Definition at line 96 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ExcitedNucleonConstructor.hh
Referenced by GetMass().
const char * G4ExcitedNucleonConstructor::name static private
Initial value:
= {
   "N(1440)", "N(1520)", "N(1535)", "N(1650)", "N(1675)",
   "N(1680)", "N(1700)", "N(1710)", "N(1720)", "N(1900)",
   "N(1990)", "N(2090)", "N(2190)", "N(2220)", "N(2250)"
}
Definition at line 95 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ExcitedNucleonConstructor.hh
const G4double G4ExcitedNucleonConstructor::width static private
Initial value:
= {
  350.0*MeV, 115.0*MeV, 150.0*MeV, 140.0*MeV, 150.0*MeV,
  130.0*MeV, 150.0*MeV, 100.0*MeV, 250.0*MeV, 500.0*MeV,
  555.0*MeV, 350.0*MeV, 500.0*MeV, 400.0*MeV, 500.0*MeV
}
Definition at line 97 of file G4ExcitedNucleonConstructor.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ExcitedNucleonConstructor.hh
Referenced by GetWidth().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/shortlived/include/G4ExcitedNucleonConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/shortlived/src/G4ExcitedNucleonConstructor.cc