ECCE @ EIC Software: G4StatMFMacroNucleon Class Reference
G4StatMFMacroNucleon Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroNucleon.hh>
Public Member Functions
G4StatMFMacroNucleon ()
~G4StatMFMacroNucleon ()
G4double CalcMeanMultiplicity (const G4double FreeVol, const G4double mu, const G4double nu, const G4double T)
G4double CalcZARatio (const G4double)
G4double CalcEnergy (const G4double T)
G4double CalcEntropy (const G4double T, const G4double FreeVol)
Public Member Functions inherited from G4VStatMFMacroCluster
G4VStatMFMacroCluster (const G4int Size)
virtual ~G4VStatMFMacroCluster ()
G4bool operator== (const G4VStatMFMacroCluster &right) const
G4bool operator!= (const G4VStatMFMacroCluster &right) const
G4double GetMeanMultiplicity (void) const
G4double GetInvLevelDensity (void) const
void SetZARatio (const G4double value)
G4double GetZARatio (void) const
void SetSize (const G4double value)
G4double GetSize (void) const
Private Member Functions
G4StatMFMacroNucleon (const G4StatMFMacroNucleon &right)
G4StatMFMacroNucleon & operator= (const G4StatMFMacroNucleon &right)
G4bool operator== (const G4StatMFMacroNucleon &right) const
G4bool operator!= (const G4StatMFMacroNucleon &right) const
Private Attributes
G4double _NeutronMeanMultiplicity
G4double _ProtonMeanMultiplicity
Additional Inherited Members
Protected Attributes inherited from G4VStatMFMacroCluster
G4int theA
G4double _InvLevelDensity
G4double _Entropy
G4double theZARatio
G4double _MeanMultiplicity
G4double _Energy
Detailed Description
Definition at line 36 of file G4StatMFMacroNucleon.hh.
View newest version in sPHENIX GitHub at line 36 of file G4StatMFMacroNucleon.hh
Constructor & Destructor Documentation
G4StatMFMacroNucleon::G4StatMFMacroNucleon ()
Definition at line 37 of file G4StatMFMacroNucleon.cc.
View newest version in sPHENIX GitHub at line 37 of file G4StatMFMacroNucleon.cc
G4StatMFMacroNucleon::~G4StatMFMacroNucleon ()
Definition at line 42 of file G4StatMFMacroNucleon.cc.
View newest version in sPHENIX GitHub at line 42 of file G4StatMFMacroNucleon.cc
G4StatMFMacroNucleon::G4StatMFMacroNucleon (const G4StatMFMacroNucleon & right) private
Member Function Documentation
G4double G4StatMFMacroNucleon::CalcEnergy (const G4double T) virtual
Implements G4VStatMFMacroCluster.
Definition at line 77 of file G4StatMFMacroNucleon.cc.
View newest version in sPHENIX GitHub at line 77 of file G4StatMFMacroNucleon.cc
References G4VStatMFMacroCluster::_Energy, G4StatMFParameters::GetCoulomb(), T, and G4VStatMFMacroCluster::theZARatio.
G4double G4StatMFMacroNucleon::CalcEntropy (const G4double T, const G4double FreeVol) virtual
Implements G4VStatMFMacroCluster.
Definition at line 83 of file G4StatMFMacroNucleon.cc.
View newest version in sPHENIX GitHub at line 83 of file G4StatMFMacroNucleon.cc
References _NeutronMeanMultiplicity, _ProtonMeanMultiplicity, fermi, G4Log(), and G4VStatMFMacroCluster::theA.
G4double G4StatMFMacroNucleon::CalcMeanMultiplicity (const G4double FreeVol, const G4double mu, const G4double nu, const G4double T) virtual
Implements G4VStatMFMacroCluster.
Definition at line 46 of file G4StatMFMacroNucleon.cc.
View newest version in sPHENIX GitHub at line 46 of file G4StatMFMacroNucleon.cc
References G4VStatMFMacroCluster::_MeanMultiplicity, _NeutronMeanMultiplicity, _ProtonMeanMultiplicity, degeneracy, fermi, G4Exp(), G4StatMFParameters::GetCoulomb(), and T.
G4double G4StatMFMacroNucleon::CalcZARatio (const G4double) inline virtual
Implements G4VStatMFMacroCluster.
Definition at line 47 of file G4StatMFMacroNucleon.hh.
View newest version in sPHENIX GitHub at line 47 of file G4StatMFMacroNucleon.hh
References _NeutronMeanMultiplicity, _ProtonMeanMultiplicity, and G4VStatMFMacroCluster::theZARatio.
G4bool G4StatMFMacroNucleon::operator!= (const G4StatMFMacroNucleon & right) const private
G4StatMFMacroNucleon& G4StatMFMacroNucleon::operator= (const G4StatMFMacroNucleon & right) private
G4bool G4StatMFMacroNucleon::operator== (const G4StatMFMacroNucleon & right) const private
Member Data Documentation
G4double G4StatMFMacroNucleon::_NeutronMeanMultiplicity private
Definition at line 71 of file G4StatMFMacroNucleon.hh.
View newest version in sPHENIX GitHub at line 71 of file G4StatMFMacroNucleon.hh
Referenced by CalcEntropy(), CalcMeanMultiplicity(), and CalcZARatio().
G4double G4StatMFMacroNucleon::_ProtonMeanMultiplicity private
Definition at line 72 of file G4StatMFMacroNucleon.hh.
View newest version in sPHENIX GitHub at line 72 of file G4StatMFMacroNucleon.hh
Referenced by CalcEntropy(), CalcMeanMultiplicity(), and CalcZARatio().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroNucleon.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMacroNucleon.cc