ECCE @ EIC Software: G4HadLeadBias Class Reference
G4HadLeadBias Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4HadLeadBias.hh>
Public Member Functions
virtual G4HadFinalState * Bias (G4HadFinalState *result)
virtual ~G4HadLeadBias ()
Public Member Functions inherited from G4VLeadingParticleBiasing
G4VLeadingParticleBiasing ()
virtual ~G4VLeadingParticleBiasing ()
Detailed Description
Definition at line 33 of file G4HadLeadBias.hh.
View newest version in sPHENIX GitHub at line 33 of file G4HadLeadBias.hh
Constructor & Destructor Documentation
virtual G4HadLeadBias::~G4HadLeadBias () inline virtual
Definition at line 37 of file G4HadLeadBias.hh.
View newest version in sPHENIX GitHub at line 37 of file G4HadLeadBias.hh
Member Function Documentation
G4HadFinalState * G4HadLeadBias::Bias (G4HadFinalState * result) virtual
Implements G4VLeadingParticleBiasing.
Definition at line 34 of file G4HadLeadBias.cc.
View newest version in sPHENIX GitHub at line 34 of file G4HadLeadBias.cc
References G4HadFinalState::AddSecondaries(), buffer, G4HadFinalState::ClearSecondaries(), emax, G4UniformRand, G4Gamma::Gamma(), G4ParticleDefinition::GetBaryonNumber(), G4DynamicParticle::GetDefinition(), G4HadFinalState::GetEnergyChange(), G4DynamicParticle::GetKineticEnergy(), G4ParticleDefinition::GetLeptonNumber(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4HadFinalState::GetSecondary(), G4HadFinalState::GetStatusChange(), G4HadSecondary::GetWeight(), isAlive, maxE, G4PionZero::PionZero(), and weight.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/include/G4HadLeadBias.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/management/src/G4HadLeadBias.cc