ECCE @ EIC Software: CML2Acc2 Class Reference
CML2Acc2 Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Acc2.hh>
Public Member Functions
CML2Acc2 (void)
~CML2Acc2 (void)
void Construct (G4VPhysicalVolume *PVWorld, G4double isoCentre)
G4double getBeforeJaws_Z_PhaseSpacePosition ()
void writeInfo ()
Public Member Functions inherited from CML2Accelerator
CML2Accelerator (void)
virtual ~CML2Accelerator (void)
void reset ()
void setJaw1X (G4double val)
void setJaw2X (G4double val)
void setJaw1Y (G4double val)
void setJaw2Y (G4double val)
void setIsoCentre (G4double val)
void setidEnergy (G4int val)
void setLeavesAx (G4double val)
void setLeavesBx (G4double val)
int getidEnergy ()
Static Public Member Functions
static CML2Acc2 * GetInstance (void)
Private Member Functions
void SetJawAperture (G4int idJaw, G4ThreeVector &centre, G4ThreeVector halfSize, G4RotationMatrix *cRotation)
bool target ()
bool primaryCollimator ()
bool vacuumWindow ()
bool flatteningFilter ()
bool ionizationChamber ()
bool mirror ()
bool Jaw1X ()
bool Jaw2X ()
bool Jaw1Y ()
bool Jaw2Y ()
bool MLC ()
Private Attributes
CML2Acc2Messenger * acc2Messenger
G4VPhysicalVolume * PVWorld
Static Private Attributes
static CML2Acc2 * instance = 0
Additional Inherited Members
Public Attributes inherited from CML2Accelerator
G4double jaw1XAperture
G4double jaw2XAperture
G4double jaw1YAperture
G4double jaw2YAperture
G4double isoCentre
std::vector< G4double > vec_leavesA
std::vector< G4double > vec_leavesB
G4int idEnergy
Detailed Description
Definition at line 66 of file ML2Acc2.hh.
View newest version in sPHENIX GitHub at line 66 of file ML2Acc2.hh
Constructor & Destructor Documentation
CML2Acc2::CML2Acc2 (void)
Definition at line 53 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 53 of file ML2Acc2.cc
CML2Acc2::~CML2Acc2 (void)
Definition at line 59 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 59 of file ML2Acc2.cc
Member Function Documentation
void CML2Acc2::Construct (G4VPhysicalVolume * PVWorld, G4double isoCentre) virtual
Reimplemented from CML2Accelerator.
Definition at line 108 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 108 of file ML2Acc2.cc
bool CML2Acc2::flatteningFilter () private
Definition at line 365 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 365 of file ML2Acc2.cc
References a, G4Region::AddRootLogicalVolume(), cm, G4Colour::Cyan(), G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), mm, CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), and G4VisAttributes::SetVisibility().
G4double CML2Acc2::getBeforeJaws_Z_PhaseSpacePosition () inline virtual
Reimplemented from CML2Accelerator.
Definition at line 74 of file ML2Acc2.hh.
View newest version in sPHENIX GitHub at line 74 of file ML2Acc2.hh
CML2Acc2 * CML2Acc2::GetInstance (void) static
Definition at line 65 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 65 of file ML2Acc2.cc
References instance.
Referenced by CML2AcceleratorConstruction::design().
bool CML2Acc2::ionizationChamber () private
Definition at line 604 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 604 of file ML2Acc2.cc
References G4Region::AddRootLogicalVolume(), G4Colour::Blue(), cm, deg, G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), mm, CLHEP::Hep3Vector::set(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and G4Colour::Yellow().
bool CML2Acc2::Jaw1X () private
Definition at line 722 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 722 of file ML2Acc2.cc
References G4Region::AddRootLogicalVolume(), G4Colour::Blue(), cm, G4NistManager::FindOrBuildMaterial(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4NistManager::Instance(), mm, CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), and G4VisAttributes::SetVisibility().
bool CML2Acc2::Jaw1Y () private
Definition at line 788 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 788 of file ML2Acc2.cc
References G4Region::AddRootLogicalVolume(), cm, G4NistManager::FindOrBuildMaterial(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4NistManager::Instance(), mm, G4Colour::Red(), CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), and G4VisAttributes::SetVisibility().
bool CML2Acc2::Jaw2X () private
Definition at line 756 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 756 of file ML2Acc2.cc
References G4Region::AddRootLogicalVolume(), G4Colour::Blue(), cm, G4NistManager::FindOrBuildMaterial(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4NistManager::Instance(), mm, CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), and G4VisAttributes::SetVisibility().
bool CML2Acc2::Jaw2Y () private
Definition at line 821 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 821 of file ML2Acc2.cc
References G4Region::AddRootLogicalVolume(), cm, G4NistManager::FindOrBuildMaterial(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4NistManager::Instance(), mm, G4Colour::Red(), CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), and G4Region::SetProductionCuts().
bool CML2Acc2::mirror () private
Definition at line 695 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 695 of file ML2Acc2.cc
References cm, deg, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), and mm.
bool CML2Acc2::MLC () private
Definition at line 854 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 854 of file ML2Acc2.cc
References a, G4Region::AddRootLogicalVolume(), cm, deg, G4NistManager::FindOrBuildMaterial(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), G4Colour::Green(), G4NistManager::Instance(), int(), mm, CLHEP::Hep3Vector::set(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), and CLHEP::twopi.
bool CML2Acc2::primaryCollimator () private
Definition at line 284 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 284 of file ML2Acc2.cc
References G4Region::AddRootLogicalVolume(), cm, deg, G4NistManager::FindOrBuildMaterial(), G4Colour::Green(), G4NistManager::Instance(), mm, G4VisAttributes::SetForceSolid(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and G4Colour::White().
void CML2Acc2::SetJawAperture (G4int idJaw, G4ThreeVector & centre, G4ThreeVector halfSize, G4RotationMatrix * cRotation) private
Definition at line 124 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 124 of file ML2Acc2.cc
References dx, dy, CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::Hep3Vector::set(), theta(), x, y, and z.
bool CML2Acc2::target () private
Definition at line 168 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 168 of file ML2Acc2.cc
References G4Region::AddRootLogicalVolume(), cm, G4NistManager::FindOrBuildMaterial(), G4Box::GetZHalfLength(), G4NistManager::Instance(), mm, G4Colour::Red(), G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and G4Colour::Yellow().
bool CML2Acc2::vacuumWindow () private
Definition at line 339 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 339 of file ML2Acc2.cc
References G4Region::AddRootLogicalVolume(), cm, deg, G4NistManager::FindOrBuildMaterial(), G4NistManager::Instance(), mm, G4ProductionCuts::SetProductionCut(), G4Region::SetProductionCuts(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), and G4Colour::Yellow().
void CML2Acc2::writeInfo () virtual
Reimplemented from CML2Accelerator.
Definition at line 73 of file ML2Acc2.cc.
View newest version in sPHENIX GitHub at line 73 of file ML2Acc2.cc
References G4cout, G4endl, int(), and mm.
Member Data Documentation
CML2Acc2Messenger* CML2Acc2::acc2Messenger private
Definition at line 80 of file ML2Acc2.hh.
View newest version in sPHENIX GitHub at line 80 of file ML2Acc2.hh
CML2Acc2 * CML2Acc2::instance = 0 static private
Definition at line 81 of file ML2Acc2.hh.
View newest version in sPHENIX GitHub at line 81 of file ML2Acc2.hh
G4VPhysicalVolume* CML2Acc2::PVWorld private
Definition at line 96 of file ML2Acc2.hh.
View newest version in sPHENIX GitHub at line 96 of file ML2Acc2.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/include/ML2Acc2.hh
geant4/tree/geant4-10.6-release/examples/advanced/medical_linac/src/ML2Acc2.cc