ECCE @ EIC Software: G4GDMLReadStructure Class Reference
G4GDMLReadStructure Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadStructure.hh>
Public Member Functions
G4GDMLReadStructure ()
virtual ~G4GDMLReadStructure ()
G4VPhysicalVolume * GetPhysvol (const G4String &) const
G4LogicalVolume * GetVolume (const G4String &) const
G4AssemblyVolume * GetAssembly (const G4String &) const
G4GDMLAuxListType GetVolumeAuxiliaryInformation (G4LogicalVolume *) const
G4VPhysicalVolume * GetWorldVolume (const G4String &)
const G4GDMLAuxMapType * GetAuxMap () const
void Clear ()
virtual void VolumeRead (const xercesc::DOMElement *const)
virtual void Volume_contentRead (const xercesc::DOMElement *const)
virtual void StructureRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadParamvol
virtual void ParamvolRead (const xercesc::DOMElement *const, G4LogicalVolume *)
virtual void Paramvol_contentRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadSetup
G4String GetSetup (const G4String &)
virtual void SetupRead (const xercesc::DOMElement *const element)
Public Member Functions inherited from G4GDMLReadSolids
G4VSolid * GetSolid (const G4String &) const
G4SurfaceProperty * GetSurfaceProperty (const G4String &) const
virtual void SolidsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadMaterials
G4Element * GetElement (const G4String &, G4bool verbose=true) const
G4Isotope * GetIsotope (const G4String &, G4bool verbose=true) const
G4Material * GetMaterial (const G4String &, G4bool verbose=true) const
virtual void MaterialsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadDefine
G4bool IsValidID (const G4String &) const
G4double GetConstant (const G4String &)
G4double GetVariable (const G4String &)
G4double GetQuantity (const G4String &)
G4ThreeVector GetPosition (const G4String &)
G4ThreeVector GetRotation (const G4String &)
G4ThreeVector GetScale (const G4String &)
G4GDMLMatrix GetMatrix (const G4String &)
virtual void DefineRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLRead
virtual void ExtensionRead (const xercesc::DOMElement *const)
virtual void UserinfoRead (const xercesc::DOMElement *const)
void Read (const G4String &, G4bool validation, G4bool isModule, G4bool strip=true)
void StripNames () const
void StripName (G4String &) const
void OverlapCheck (G4bool)
const G4GDMLAuxListType * GetAuxList () const
Protected Member Functions
void AssemblyRead (const xercesc::DOMElement *const)
void DivisionvolRead (const xercesc::DOMElement *const)
G4LogicalVolume * FileRead (const xercesc::DOMElement *const)
void PhysvolRead (const xercesc::DOMElement *const, G4AssemblyVolume *assembly=0)
void ReplicavolRead (const xercesc::DOMElement *const, G4int number)
void ReplicaRead (const xercesc::DOMElement *const replicaElement, G4LogicalVolume *logvol, G4int number)
EAxis AxisRead (const xercesc::DOMElement *const axisElement)
G4double QuantityRead (const xercesc::DOMElement *const readElement)
void BorderSurfaceRead (const xercesc::DOMElement *const)
void SkinSurfaceRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLReadParamvol
G4GDMLReadParamvol ()
virtual ~G4GDMLReadParamvol ()
void Box_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Trd_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Trap_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Tube_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Cone_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Sphere_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Orb_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Torus_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Ellipsoid_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Para_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Hype_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Polycone_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Polyhedra_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void ParameterisedRead (const xercesc::DOMElement *const)
void ParametersRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLReadSetup
G4GDMLReadSetup ()
virtual ~G4GDMLReadSetup ()
Protected Member Functions inherited from G4GDMLReadSolids
G4GDMLReadSolids ()
virtual ~G4GDMLReadSolids ()
void BooleanRead (const xercesc::DOMElement *const, const BooleanOp)
void BoxRead (const xercesc::DOMElement *const)
void ConeRead (const xercesc::DOMElement *const)
void ElconeRead (const xercesc::DOMElement *const)
void EllipsoidRead (const xercesc::DOMElement *const)
void EltubeRead (const xercesc::DOMElement *const)
void XtruRead (const xercesc::DOMElement *const)
void HypeRead (const xercesc::DOMElement *const)
void MultiUnionNodeRead (const xercesc::DOMElement *const, G4MultiUnion *const)
void MultiUnionRead (const xercesc::DOMElement *const)
void OrbRead (const xercesc::DOMElement *const)
void ParaRead (const xercesc::DOMElement *const)
void ParaboloidRead (const xercesc::DOMElement *const)
void PolyconeRead (const xercesc::DOMElement *const)
void GenericPolyconeRead (const xercesc::DOMElement *const)
void PolyhedraRead (const xercesc::DOMElement *const)
void GenericPolyhedraRead (const xercesc::DOMElement *const)
G4QuadrangularFacet * QuadrangularRead (const xercesc::DOMElement *const)
void ReflectedSolidRead (const xercesc::DOMElement *const)
void ScaledSolidRead (const xercesc::DOMElement *const)
G4ExtrudedSolid::ZSection SectionRead (const xercesc::DOMElement *const, G4double)
void SphereRead (const xercesc::DOMElement *const)
void TessellatedRead (const xercesc::DOMElement *const)
void TetRead (const xercesc::DOMElement *const)
void TorusRead (const xercesc::DOMElement *const)
void GenTrapRead (const xercesc::DOMElement *const)
void TrapRead (const xercesc::DOMElement *const)
void TrdRead (const xercesc::DOMElement *const)
void TubeRead (const xercesc::DOMElement *const)
void CutTubeRead (const xercesc::DOMElement *const)
void TwistedboxRead (const xercesc::DOMElement *const)
void TwistedtrapRead (const xercesc::DOMElement *const)
void TwistedtrdRead (const xercesc::DOMElement *const)
void TwistedtubsRead (const xercesc::DOMElement *const)
G4TriangularFacet * TriangularRead (const xercesc::DOMElement *const)
G4TwoVector TwoDimVertexRead (const xercesc::DOMElement *const, G4double)
zplaneType ZplaneRead (const xercesc::DOMElement *const)
rzPointType RZPointRead (const xercesc::DOMElement *const)
void OpticalSurfaceRead (const xercesc::DOMElement *const)
void PropertyRead (const xercesc::DOMElement *const, G4OpticalSurface *)
Protected Member Functions inherited from G4GDMLReadMaterials
G4GDMLReadMaterials ()
virtual ~G4GDMLReadMaterials ()
G4double AtomRead (const xercesc::DOMElement *const)
G4int CompositeRead (const xercesc::DOMElement *const, G4String &)
G4double DRead (const xercesc::DOMElement *const)
G4double PRead (const xercesc::DOMElement *const)
G4double TRead (const xercesc::DOMElement *const)
G4double MEERead (const xercesc::DOMElement *const)
void ElementRead (const xercesc::DOMElement *const)
G4double FractionRead (const xercesc::DOMElement *const, G4String &)
void IsotopeRead (const xercesc::DOMElement *const)
void MaterialRead (const xercesc::DOMElement *const)
void MixtureRead (const xercesc::DOMElement *const, G4Element *)
void MixtureRead (const xercesc::DOMElement *const, G4Material *)
void PropertyRead (const xercesc::DOMElement *const, G4Material *)
Protected Member Functions inherited from G4GDMLReadDefine
G4GDMLReadDefine ()
virtual ~G4GDMLReadDefine ()
G4RotationMatrix GetRotationMatrix (const G4ThreeVector &)
void VectorRead (const xercesc::DOMElement *const, G4ThreeVector &)
G4String RefRead (const xercesc::DOMElement *const)
void ConstantRead (const xercesc::DOMElement *const)
void MatrixRead (const xercesc::DOMElement *const)
void PositionRead (const xercesc::DOMElement *const)
void RotationRead (const xercesc::DOMElement *const)
void ScaleRead (const xercesc::DOMElement *const)
void VariableRead (const xercesc::DOMElement *const)
void QuantityRead (const xercesc::DOMElement *const)
void ExpressionRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLRead
G4GDMLRead ()
virtual ~G4GDMLRead ()
G4String Transcode (const XMLCh *const)
G4String GenerateName (const G4String &name, G4bool strip=false)
G4String Strip (const G4String &) const
void GeneratePhysvolName (const G4String &, G4VPhysicalVolume *)
void LoopRead (const xercesc::DOMElement *const, void(G4GDMLRead::*)(const xercesc::DOMElement *const))
G4GDMLAuxStructType AuxiliaryRead (const xercesc::DOMElement *const auxElem)
Protected Attributes
G4GDMLAuxMapType auxMap
G4GDMLAssemblyMapType assemblyMap
G4LogicalVolume * pMotherLogical
std::map< std::string,
G4VPhysicalVolume * > setuptoPV
G4bool strip
Protected Attributes inherited from G4GDMLReadParamvol
G4GDMLParameterisation * parameterisation
Protected Attributes inherited from G4GDMLReadSetup
std::map< G4String, G4String > setupMap
Detailed Description
Definition at line 54 of file G4GDMLReadStructure.hh.
View newest version in sPHENIX GitHub at line 54 of file G4GDMLReadStructure.hh
Constructor & Destructor Documentation
G4GDMLReadStructure::G4GDMLReadStructure ()
Definition at line 48 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 48 of file G4GDMLReadStructure.cc
G4GDMLReadStructure::~G4GDMLReadStructure () virtual
Definition at line 53 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 53 of file G4GDMLReadStructure.cc
Member Function Documentation
void G4GDMLReadStructure::AssemblyRead (const xercesc::DOMElement * const assemblyElement) protected
Definition at line 618 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 618 of file G4GDMLReadStructure.cc
References assemblyMap, FatalException, G4cout, G4endl, G4Exception(), G4GDMLRead::GenerateName(), PhysvolRead(), and G4GDMLRead::Transcode().
Referenced by StructureRead().
EAxis G4GDMLReadStructure::AxisRead (const xercesc::DOMElement *const axisElement) protected
Definition at line 496 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 496 of file G4GDMLReadStructure.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), kPhi, kRho, kUndefined, kXAxis, kYAxis, kZAxis, and G4GDMLRead::Transcode().
Referenced by ReplicaRead().
void G4GDMLReadStructure::BorderSurfaceRead (const xercesc::DOMElement * const bordersurfaceElement) protected
Definition at line 59 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 59 of file G4GDMLReadStructure.cc
References FatalException, G4Exception(), G4GDMLRead::GenerateName(), GetPhysvol(), G4GDMLReadSolids::GetSurfaceProperty(), G4GDMLReadDefine::RefRead(), G4GDMLRead::Strip(), and G4GDMLRead::Transcode().
Referenced by StructureRead().
void G4GDMLReadStructure::Clear ()
Definition at line 904 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 904 of file G4GDMLReadStructure.cc
References auxMap, G4GDMLEvaluator::Clear(), G4GDMLRead::eval, and setuptoPV.
void G4GDMLReadStructure::DivisionvolRead (const xercesc::DOMElement * const divisionvolElement) protected
Definition at line 124 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 124 of file G4GDMLReadStructure.cc
References G4ReflectionFactory::Divide(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), G4GDMLEvaluator::EvaluateInteger(), FatalException, G4String::first(), G4Exception(), G4GDMLRead::GenerateName(), G4GDMLRead::GeneratePhysvolName(), G4UnitDefinition::GetCategory(), G4PVDivisionFactory::GetInstance(), G4LogicalVolume::GetName(), G4UnitDefinition::GetValueOf(), GetVolume(), G4ReflectionFactory::Instance(), kPhi, kRho, kUndefined, kXAxis, kYAxis, kZAxis, offset, pMotherLogical, G4GDMLReadDefine::RefRead(), G4GDMLRead::Transcode(), and width.
Referenced by Volume_contentRead().
G4LogicalVolume * G4GDMLReadStructure::FileRead (const xercesc::DOMElement * const fileElement) protected
Definition at line 228 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 228 of file G4GDMLReadStructure.cc
References auxMap, FatalException, G4Exception(), G4GDMLRead::GenerateName(), GetAuxMap(), G4GDMLReadSetup::GetSetup(), GetVolume(), pos(), G4GDMLRead::Read(), G4GDMLRead::Transcode(), and G4GDMLRead::validate.
Referenced by PhysvolRead().
G4AssemblyVolume * G4GDMLReadStructure::GetAssembly (const G4String & ref) const
Definition at line 865 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 865 of file G4GDMLReadStructure.cc
References assemblyMap, and pos().
Referenced by BeastMagnetDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), PHG4EICMvtxDetector::ConstructMvtx(), PHG4MvtxDetector::ConstructMvtx(), PHG4MvtxDetector::ConstructMvtxPassiveVol(), and PhysvolRead().
const G4GDMLAuxMapType* G4GDMLReadStructure::GetAuxMap () const inline
Definition at line 67 of file G4GDMLReadStructure.hh.
View newest version in sPHENIX GitHub at line 67 of file G4GDMLReadStructure.hh
References auxMap.
Referenced by FileRead().
G4VPhysicalVolume * G4GDMLReadStructure::GetPhysvol (const G4String & ref) const
Definition at line 833 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 833 of file G4GDMLReadStructure.cc
References FatalException, G4Exception(), G4PhysicalVolumeStore::GetInstance(), and G4PhysicalVolumeStore::GetVolume().
Referenced by BorderSurfaceRead().
G4LogicalVolume * G4GDMLReadStructure::GetVolume (const G4String & ref) const virtual
Implements G4GDMLRead.
Definition at line 849 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 849 of file G4GDMLReadStructure.cc
References FatalException, G4Exception(), G4LogicalVolumeStore::GetInstance(), and G4LogicalVolumeStore::GetVolume().
Referenced by AllSiliconTrackerDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), DivisionvolRead(), FileRead(), GetWorldVolume(), PhysvolRead(), ReplicavolRead(), and SkinSurfaceRead().
G4GDMLAuxListType G4GDMLReadStructure::GetVolumeAuxiliaryInformation (G4LogicalVolume * logvol) const
Definition at line 873 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 873 of file G4GDMLReadStructure.cc
References auxMap, and pos().
G4VPhysicalVolume * G4GDMLReadStructure::GetWorldVolume (const G4String & setupName)
Definition at line 881 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 881 of file G4GDMLReadStructure.cc
References G4GDMLRead::dostrip, G4GDMLRead::GenerateName(), G4VisAttributes::GetInvisible(), G4LogicalVolume::GetName(), G4GDMLReadSetup::GetSetup(), GetVolume(), setuptoPV, G4LogicalVolume::SetVisAttributes(), and Acts::Test::volume.
void G4GDMLReadStructure::PhysvolRead (const xercesc::DOMElement * const physvolElement, G4AssemblyVolume * assembly = 0) protected
Definition at line 289 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 289 of file G4GDMLReadStructure.cc
References G4AssemblyVolume::AddPlacedAssembly(), G4AssemblyVolume::AddPlacedVolume(), G4GDMLRead::check, G4GDMLRead::eval, G4GDMLEvaluator::EvaluateInteger(), FatalException, FileRead(), G4String::first(), G4Exception(), G4GDMLRead::GenerateName(), G4GDMLRead::GeneratePhysvolName(), GetAssembly(), G4LogicalVolume::GetName(), G4GDMLReadDefine::GetPosition(), G4GDMLReadDefine::GetRotation(), G4GDMLReadDefine::GetRotationMatrix(), G4GDMLReadDefine::GetScale(), GetVolume(), G4ReflectionFactory::Instance(), G4AssemblyVolume::MakeImprint(), G4ReflectionFactory::Place(), pMotherLogical, position, G4GDMLReadDefine::RefRead(), scale, G4GDMLRead::Transcode(), Acts::Test::transform, G4GDMLReadDefine::VectorRead(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by AssemblyRead(), and Volume_contentRead().
G4double G4GDMLReadStructure::QuantityRead (const xercesc::DOMElement *const readElement) protected
Definition at line 538 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 538 of file G4GDMLReadStructure.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by ReplicaRead().
void G4GDMLReadStructure::ReplicaRead (const xercesc::DOMElement *const replicaElement, G4LogicalVolume * logvol, G4int number) protected
Definition at line 439 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 439 of file G4GDMLReadStructure.cc
References AxisRead(), FatalException, G4String::first(), G4Exception(), G4GDMLRead::GenerateName(), G4GDMLRead::GeneratePhysvolName(), G4LogicalVolume::GetName(), G4GDMLReadDefine::GetPosition(), G4GDMLReadDefine::GetRotation(), G4ReflectionFactory::Instance(), kUndefined, offset, pMotherLogical, position, QuantityRead(), G4GDMLReadDefine::RefRead(), G4ReflectionFactory::Replicate(), G4GDMLRead::Transcode(), G4GDMLReadDefine::VectorRead(), and width.
Referenced by ReplicavolRead().
void G4GDMLReadStructure::ReplicavolRead (const xercesc::DOMElement * const replicavolElement, G4int number) protected
Definition at line 403 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 403 of file G4GDMLReadStructure.cc
References FatalException, G4Exception(), G4GDMLRead::GenerateName(), GetVolume(), G4GDMLReadDefine::RefRead(), ReplicaRead(), and G4GDMLRead::Transcode().
Referenced by Volume_contentRead().
void G4GDMLReadStructure::SkinSurfaceRead (const xercesc::DOMElement * const skinsurfaceElement) protected
Definition at line 654 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 654 of file G4GDMLReadStructure.cc
References FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4GDMLReadSolids::GetSurfaceProperty(), GetVolume(), G4GDMLReadDefine::RefRead(), G4GDMLRead::Strip(), and G4GDMLRead::Transcode().
Referenced by StructureRead().
void G4GDMLReadStructure::StructureRead (const xercesc::DOMElement * const structureElement) virtual
Implements G4GDMLRead.
Definition at line 798 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 798 of file G4GDMLReadStructure.cc
References AssemblyRead(), BorderSurfaceRead(), FatalException, G4cout, G4endl, G4Exception(), G4GDMLRead::LoopRead(), SkinSurfaceRead(), G4GDMLRead::StructureRead(), G4GDMLRead::Transcode(), and VolumeRead().
void G4GDMLReadStructure::Volume_contentRead (const xercesc::DOMElement * const volumeElement) virtual
Implements G4GDMLRead.
Definition at line 720 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 720 of file G4GDMLReadStructure.cc
References DivisionvolRead(), G4GDMLRead::eval, G4GDMLEvaluator::EvaluateInteger(), FatalException, G4cout, G4endl, G4Exception(), G4GDMLRead::LoopRead(), G4GDMLReadParamvol::ParamvolRead(), PhysvolRead(), pMotherLogical, ReplicavolRead(), G4GDMLRead::Transcode(), and G4GDMLRead::Volume_contentRead().
Referenced by G03ColorReader::VolumeRead(), and VolumeRead().
void G4GDMLReadStructure::VolumeRead (const xercesc::DOMElement * const volumeElement) virtual
Reimplemented in G03ColorReader.
Definition at line 576 of file G4GDMLReadStructure.cc.
View newest version in sPHENIX GitHub at line 576 of file G4GDMLReadStructure.cc
References G4GDMLRead::AuxiliaryRead(), auxMap, FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4GDMLReadMaterials::GetMaterial(), G4GDMLReadSolids::GetSolid(), pMotherLogical, G4GDMLReadDefine::RefRead(), G4GDMLRead::Transcode(), and Volume_contentRead().
Referenced by StructureRead().
Member Data Documentation
G4GDMLAssemblyMapType G4GDMLReadStructure::assemblyMap protected
Definition at line 92 of file G4GDMLReadStructure.hh.
View newest version in sPHENIX GitHub at line 92 of file G4GDMLReadStructure.hh
Referenced by AssemblyRead(), and GetAssembly().
G4GDMLAuxMapType G4GDMLReadStructure::auxMap protected
Definition at line 91 of file G4GDMLReadStructure.hh.
View newest version in sPHENIX GitHub at line 91 of file G4GDMLReadStructure.hh
Referenced by Clear(), FileRead(), GetAuxMap(), GetVolumeAuxiliaryInformation(), G03ColorReader::VolumeRead(), and VolumeRead().
G4LogicalVolume* G4GDMLReadStructure::pMotherLogical protected
Definition at line 93 of file G4GDMLReadStructure.hh.
View newest version in sPHENIX GitHub at line 93 of file G4GDMLReadStructure.hh
Referenced by DivisionvolRead(), PhysvolRead(), ReplicaRead(), Volume_contentRead(), G03ColorReader::VolumeRead(), and VolumeRead().
std::map<std::string, G4VPhysicalVolume*> G4GDMLReadStructure::setuptoPV protected
Definition at line 94 of file G4GDMLReadStructure.hh.
View newest version in sPHENIX GitHub at line 94 of file G4GDMLReadStructure.hh
Referenced by Clear(), and GetWorldVolume().
G4bool G4GDMLReadStructure::strip protected
Definition at line 95 of file G4GDMLReadStructure.hh.
View newest version in sPHENIX GitHub at line 95 of file G4GDMLReadStructure.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadStructure.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLReadStructure.cc