ECCE @ EIC Software: G4ElectronOccupancy Class Reference
G4ElectronOccupancy Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4ElectronOccupancy.hh>
Public Types
enum { MaxSizeOfOrbit = 20 }
Public Member Functions
G4ElectronOccupancy (G4int sizeOrbit=MaxSizeOfOrbit)
G4ElectronOccupancy (const G4ElectronOccupancy &right)
virtual ~G4ElectronOccupancy ()
void * operator new (size_t)
void operator delete (void *aElectronOccupancy)
G4ElectronOccupancy & operator= (const G4ElectronOccupancy &right)
G4bool operator== (const G4ElectronOccupancy &right) const
G4bool operator!= (const G4ElectronOccupancy &right) const
G4int GetTotalOccupancy () const
G4int GetOccupancy (G4int orbit) const
G4int AddElectron (G4int orbit, G4int number=1)
G4int RemoveElectron (G4int orbit, G4int number=1)
G4int GetSizeOfOrbit () const
void DumpInfo () const
Private Attributes
G4int theSizeOfOrbit
G4int theTotalOccupancy
G4int * theOccupancies
Detailed Description
Definition at line 61 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ElectronOccupancy.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
MaxSizeOfOrbit
Definition at line 64 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ElectronOccupancy.hh
Constructor & Destructor Documentation
G4ElectronOccupancy::G4ElectronOccupancy (G4int sizeOrbit = MaxSizeOfOrbit)
Definition at line 48 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ElectronOccupancy.cc
References MaxSizeOfOrbit, theOccupancies, theSizeOfOrbit, and theTotalOccupancy.
G4ElectronOccupancy::G4ElectronOccupancy (const G4ElectronOccupancy & right)
Definition at line 75 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ElectronOccupancy.cc
References theOccupancies, theSizeOfOrbit, and theTotalOccupancy.
G4ElectronOccupancy::~G4ElectronOccupancy () virtual
Definition at line 66 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ElectronOccupancy.cc
References theOccupancies, theSizeOfOrbit, and theTotalOccupancy.
Member Function Documentation
G4int G4ElectronOccupancy::AddElectron (G4int orbit, G4int number = 1)
Definition at line 139 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 139 of file G4ElectronOccupancy.cc
References G4Exception(), JustWarning, theOccupancies, theSizeOfOrbit, and theTotalOccupancy.
Referenced by G4MolecularConfiguration::AddElectron(), G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), G4EmDNAChemistry_option2::ConstructDissociationChannels(), G4MolecularConfiguration::ExciteMolecule(), G4MolecularConfiguration::MoveOneElectron(), and G4MoleculeDefinition::SetLevelOccupation().
void G4ElectronOccupancy::DumpInfo () const
Definition at line 129 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 129 of file G4ElectronOccupancy.cc
References G4cout, G4endl, theOccupancies, and theSizeOfOrbit.
G4int G4ElectronOccupancy::GetOccupancy (G4int orbit) const inline
Definition at line 137 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ElectronOccupancy.hh
References theOccupancies, and theSizeOfOrbit.
Referenced by G4MolecularConfiguration::IonizeMolecule(), G4MolecularConfiguration::MoveOneElectron(), comparator::operator()(), G4MolecularConfiguration::RemoveElectron(), and G4MoleculeDefinition::SetLevelOccupation().
G4int G4ElectronOccupancy::GetSizeOfOrbit () const inline
Definition at line 125 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ElectronOccupancy.hh
References theSizeOfOrbit.
Referenced by G4MoleculeDefinition::GetNbMolecularShells(), comparator::operator()(), and G4MoleculeDefinition::Serialize().
G4int G4ElectronOccupancy::GetTotalOccupancy () const inline
Definition at line 131 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ElectronOccupancy.hh
References theTotalOccupancy.
Referenced by G4MoleculeDefinition::GetNbElectrons(), and comparator::operator()().
void G4ElectronOccupancy::operator delete (void * aElectronOccupancy) inline
Definition at line 119 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ElectronOccupancy.hh
References aElectronOccupancyAllocator().
void * G4ElectronOccupancy::operator new (size_t) inline
Definition at line 110 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ElectronOccupancy.hh
References aElectronOccupancyAllocator().
G4bool G4ElectronOccupancy::operator!= (const G4ElectronOccupancy & right) const
Definition at line 124 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 124 of file G4ElectronOccupancy.cc
References right.
G4ElectronOccupancy & G4ElectronOccupancy::operator= (const G4ElectronOccupancy & right)
Definition at line 89 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 89 of file G4ElectronOccupancy.cc
References theOccupancies, theSizeOfOrbit, and theTotalOccupancy.
G4bool G4ElectronOccupancy::operator== (const G4ElectronOccupancy & right) const
Definition at line 107 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 107 of file G4ElectronOccupancy.cc
References MaxSizeOfOrbit, theOccupancies, and theSizeOfOrbit.
G4int G4ElectronOccupancy::RemoveElectron (G4int orbit, G4int number = 1)
Definition at line 158 of file G4ElectronOccupancy.cc.
View newest version in sPHENIX GitHub at line 158 of file G4ElectronOccupancy.cc
References G4Exception(), JustWarning, theOccupancies, theSizeOfOrbit, and theTotalOccupancy.
Referenced by G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), G4EmDNAChemistry_option2::ConstructDissociationChannels(), G4MolecularConfiguration::ExciteMolecule(), G4Molecule::G4Molecule(), G4MolecularConfiguration::IonizeMolecule(), G4MolecularConfiguration::MoveOneElectron(), G4MolecularConfiguration::RemoveElectron(), and G4MoleculeDefinition::SetLevelOccupation().
Member Data Documentation
G4int* G4ElectronOccupancy::theOccupancies private
Definition at line 100 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ElectronOccupancy.hh
Referenced by AddElectron(), DumpInfo(), G4ElectronOccupancy(), GetOccupancy(), operator=(), operator==(), RemoveElectron(), and ~G4ElectronOccupancy().
G4int G4ElectronOccupancy::theSizeOfOrbit private
Definition at line 98 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ElectronOccupancy.hh
Referenced by AddElectron(), DumpInfo(), G4ElectronOccupancy(), GetOccupancy(), GetSizeOfOrbit(), operator=(), operator==(), RemoveElectron(), and ~G4ElectronOccupancy().
G4int G4ElectronOccupancy::theTotalOccupancy private
Definition at line 99 of file G4ElectronOccupancy.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ElectronOccupancy.hh
Referenced by AddElectron(), G4ElectronOccupancy(), GetTotalOccupancy(), operator=(), RemoveElectron(), and ~G4ElectronOccupancy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4ElectronOccupancy.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4ElectronOccupancy.cc