ECCE @ EIC Software: CexmcTrackPointsDigitizer Class Reference
CexmcTrackPointsDigitizer Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackPointsDigitizer.hh>
Public Member Functions
CexmcTrackPointsDigitizer (const G4String &name)
void Digitize (void)
const CexmcTrackPointInfo & GetMonitorTP (void) const
const CexmcTrackPointInfo & GetTargetTPBeamParticle (void) const
const CexmcTrackPointInfo & GetTargetTPOutputParticle (void) const
const CexmcTrackPointInfo & GetTargetTPNucleusParticle (void) const
const CexmcTrackPointInfo & GetTargetTPOutputParticleDecayProductParticle (G4int index) const
const CexmcTrackPointInfo & GetVetoCounterTPLeft (void) const
const CexmcTrackPointInfo & GetVetoCounterTPRight (void) const
const CexmcTrackPointInfo & GetCalorimeterTPLeft (void) const
const CexmcTrackPointInfo & GetCalorimeterTPRight (void) const
G4bool HasTriggered (void) const
Public Member Functions inherited from G4VDigitizerModule
G4VDigitizerModule (const G4String &modName)
virtual ~G4VDigitizerModule ()
G4bool operator== (const G4VDigitizerModule &right) const
G4bool operator!= (const G4VDigitizerModule &right) const
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int i) const
G4String GetName () const
void SetVerboseLevel (G4int val)
Private Member Functions
void InitializeData (void)
Private Attributes
CexmcTrackPointInfo monitorTP
CexmcTrackPointInfo targetTPBeamParticle
CexmcTrackPointInfo targetTPOutputParticle
CexmcTrackPointInfo targetTPNucleusParticle
CexmcTrackPointInfo targetTPOutputParticleDecayProductParticle [2]
CexmcTrackPointInfo vetoCounterTPLeft
CexmcTrackPointInfo vetoCounterTPRight
CexmcTrackPointInfo calorimeterTPLeft
CexmcTrackPointInfo calorimeterTPRight
G4bool hasTriggered
CexmcSetup::CalorimeterGeometryData calorimeterGeometry
Additional Inherited Members
Protected Member Functions inherited from G4VDigitizerModule
void StoreDigiCollection (G4VDigiCollection *aDC)
void StoreDigiCollection (G4int DCID, G4VDigiCollection *aDC)
Protected Attributes inherited from G4VDigitizerModule
G4DigiManager * DigiManager
G4String moduleName
std::vector< G4String > collectionName
G4int verboseLevel
Detailed Description
Definition at line 54 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 54 of file CexmcTrackPointsDigitizer.hh
Constructor & Destructor Documentation
CexmcTrackPointsDigitizer::CexmcTrackPointsDigitizer (const G4String & name) explicit
Definition at line 55 of file CexmcTrackPointsDigitizer.cc.
View newest version in sPHENIX GitHub at line 55 of file CexmcTrackPointsDigitizer.cc
References calorimeterGeometry, CexmcSetup::GetCalorimeterGeometry(), G4RunManager::GetRunManager(), and G4RunManager::GetUserDetectorConstruction().
Member Function Documentation
void CexmcTrackPointsDigitizer::Digitize (void) virtual
Implements G4VDigitizerModule.
Definition at line 83 of file CexmcTrackPointsDigitizer.cc.
View newest version in sPHENIX GitHub at line 83 of file CexmcTrackPointsDigitizer.cc
References calorimeterGeometry, calorimeterTPLeft, calorimeterTPRight, CexmcBeamParticleTrack, CexmcCalorimeterDetectorRole, CexmcDetectorRoleName, CexmcDetectorTypeName, CexmcLeft, CexmcMonitorDetectorRole, CexmcNucleusParticleTrack, CexmcOutputParticleDecayProductTrack, CexmcOutputParticleTrack, CexmcRight, CexmcTargetDetectorRole, CexmcTPDetector, CexmcVetoCounterDetectorRole, CexmcSetup::CalorimeterGeometryData::crystalHeight, CexmcSetup::CalorimeterGeometryData::crystalWidth, CexmcTrackPointsInCalorimeter::GetColumn(), G4DigiManager::GetDMpointer(), G4DigiManager::GetHitsCollection(), G4DigiManager::GetHitsCollectionID(), CexmcTrackPointsInCalorimeter::GetRow(), CexmcTrackPointsInLeftRightSet::GetSide(), hasTriggered, InitializeData(), CexmcTrackPointInfo::IsValid(), k, monitorTP, CexmcSetup::CalorimeterGeometryData::nCrystalsInColumn, CexmcSetup::CalorimeterGeometryData::nCrystalsInRow, CexmcTrackPointInfo::positionLocal, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), targetTPBeamParticle, targetTPNucleusParticle, targetTPOutputParticle, targetTPOutputParticleDecayProductParticle, vetoCounterTPLeft, vetoCounterTPRight, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by CexmcEventAction::EndOfEventAction().
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetCalorimeterTPLeft (void) const inline
Definition at line 169 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 169 of file CexmcTrackPointsDigitizer.hh
References calorimeterTPLeft.
Referenced by CexmcEventAction::MakeTrackPointsStore().
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetCalorimeterTPRight (void) const inline
Definition at line 176 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 176 of file CexmcTrackPointsDigitizer.hh
References calorimeterTPRight.
Referenced by CexmcEventAction::MakeTrackPointsStore().
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetMonitorTP (void) const inline
Definition at line 116 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 116 of file CexmcTrackPointsDigitizer.hh
References monitorTP.
Referenced by CexmcEventAction::MakeTrackPointsStore().
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetTargetTPBeamParticle (void) const inline
Definition at line 123 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 123 of file CexmcTrackPointsDigitizer.hh
References targetTPBeamParticle.
Referenced by CexmcEventAction::MakeTrackPointsStore().
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetTargetTPNucleusParticle (void) const inline
Definition at line 137 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 137 of file CexmcTrackPointsDigitizer.hh
References targetTPNucleusParticle.
Referenced by CexmcEventAction::MakeTrackPointsStore().
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetTargetTPOutputParticle (void) const inline
Definition at line 130 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 130 of file CexmcTrackPointsDigitizer.hh
References targetTPOutputParticle.
Referenced by CexmcEventAction::MakeTrackPointsStore().
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetTargetTPOutputParticleDecayProductParticle (G4int index) const inline
Definition at line 144 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 144 of file CexmcTrackPointsDigitizer.hh
References targetTPOutputParticleDecayProductParticle.
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetVetoCounterTPLeft (void) const inline
Definition at line 155 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 155 of file CexmcTrackPointsDigitizer.hh
References vetoCounterTPLeft.
Referenced by CexmcEventAction::MakeTrackPointsStore().
const CexmcTrackPointInfo & CexmcTrackPointsDigitizer::GetVetoCounterTPRight (void) const inline
Definition at line 162 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 162 of file CexmcTrackPointsDigitizer.hh
References vetoCounterTPRight.
Referenced by CexmcEventAction::MakeTrackPointsStore().
G4bool CexmcTrackPointsDigitizer::HasTriggered (void) const inline
Definition at line 182 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 182 of file CexmcTrackPointsDigitizer.hh
References hasTriggered.
Referenced by CexmcEventAction::EndOfEventAction().
void CexmcTrackPointsDigitizer::InitializeData (void) private
Definition at line 65 of file CexmcTrackPointsDigitizer.cc.
View newest version in sPHENIX GitHub at line 65 of file CexmcTrackPointsDigitizer.cc
References calorimeterTPLeft, calorimeterTPRight, CexmcInvalidTrackId(), hasTriggered, monitorTP, targetTPBeamParticle, targetTPNucleusParticle, targetTPOutputParticle, targetTPOutputParticleDecayProductParticle, CexmcTrackPointInfo::trackId, vetoCounterTPLeft, and vetoCounterTPRight.
Referenced by Digitize().
Member Data Documentation
CexmcSetup::CalorimeterGeometryData CexmcTrackPointsDigitizer::calorimeterGeometry private
Definition at line 111 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 111 of file CexmcTrackPointsDigitizer.hh
Referenced by CexmcTrackPointsDigitizer(), and Digitize().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::calorimeterTPLeft private
Definition at line 104 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 104 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetCalorimeterTPLeft(), and InitializeData().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::calorimeterTPRight private
Definition at line 106 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 106 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetCalorimeterTPRight(), and InitializeData().
G4bool CexmcTrackPointsDigitizer::hasTriggered private
Definition at line 108 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 108 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), HasTriggered(), and InitializeData().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::monitorTP private
Definition at line 90 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 90 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetMonitorTP(), and InitializeData().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::targetTPBeamParticle private
Definition at line 92 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 92 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetTargetTPBeamParticle(), and InitializeData().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::targetTPNucleusParticle private
Definition at line 96 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 96 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetTargetTPNucleusParticle(), and InitializeData().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::targetTPOutputParticle private
Definition at line 94 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 94 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetTargetTPOutputParticle(), and InitializeData().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::targetTPOutputParticleDecayProductParticle[2] private
Definition at line 98 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 98 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetTargetTPOutputParticleDecayProductParticle(), and InitializeData().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::vetoCounterTPLeft private
Definition at line 100 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 100 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetVetoCounterTPLeft(), and InitializeData().
CexmcTrackPointInfo CexmcTrackPointsDigitizer::vetoCounterTPRight private
Definition at line 102 of file CexmcTrackPointsDigitizer.hh.
View newest version in sPHENIX GitHub at line 102 of file CexmcTrackPointsDigitizer.hh
Referenced by Digitize(), GetVetoCounterTPRight(), and InitializeData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackPointsDigitizer.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcTrackPointsDigitizer.cc