ECCE @ EIC Software: G4ParticleHPFCFissionFS Class Reference
G4ParticleHPFCFissionFS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFCFissionFS.hh>
Public Member Functions
G4ParticleHPFCFissionFS ()
~G4ParticleHPFCFissionFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4DynamicParticleVector * ApplyYourself (G4int nNeutrons)
G4ParticleHPFinalState * New ()
Public Member Functions inherited from G4ParticleHPFissionBaseFS
G4ParticleHPFissionBaseFS ()
virtual ~G4ParticleHPFissionBaseFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &bit, G4ParticleDefinition *)
G4DynamicParticleVector * ApplyYourself (G4int Prompt)
virtual G4double GetXsec (G4double anEnergy)
virtual G4ParticleHPVector * GetXsec ()
void SetNeutronRP (const G4ReactionProduct &aNeutron)
void SetTarget (const G4ReactionProduct &aTarget)
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Private Member Functions
G4HadFinalState * ApplyYourself (const G4HadProjectile &)
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Detailed Description
Definition at line 37 of file G4ParticleHPFCFissionFS.hh.
View newest version in sPHENIX GitHub at line 37 of file G4ParticleHPFCFissionFS.hh
Constructor & Destructor Documentation
G4ParticleHPFCFissionFS::G4ParticleHPFCFissionFS () inline
Definition at line 41 of file G4ParticleHPFCFissionFS.hh.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPFCFissionFS.hh
References G4ParticleHPFinalState::hasXsec.
Referenced by New().
G4ParticleHPFCFissionFS::~G4ParticleHPFCFissionFS () inline
Definition at line 42 of file G4ParticleHPFCFissionFS.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPFCFissionFS.hh
Member Function Documentation
G4DynamicParticleVector * G4ParticleHPFCFissionFS::ApplyYourself (G4int nNeutrons)
Definition at line 40 of file G4ParticleHPFCFissionFS.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPFCFissionFS.cc
References G4ParticleHPFissionBaseFS::ApplyYourself().
Referenced by G4ParticleHPFissionFS::ApplyYourself().
G4HadFinalState* G4ParticleHPFCFissionFS::ApplyYourself (const G4HadProjectile &) inline private virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 52 of file G4ParticleHPFCFissionFS.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPFCFissionFS.hh
void G4ParticleHPFCFissionFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & aFSType, G4ParticleDefinition * projectile) virtual
Implements G4ParticleHPFinalState.
Definition at line 34 of file G4ParticleHPFCFissionFS.cc.
View newest version in sPHENIX GitHub at line 34 of file G4ParticleHPFCFissionFS.cc
References G4ParticleHPFissionBaseFS::Init().
Referenced by G4ParticleHPFissionFS::Init().
G4ParticleHPFinalState* G4ParticleHPFCFissionFS::New () inline virtual
Implements G4ParticleHPFinalState.
Definition at line 45 of file G4ParticleHPFCFissionFS.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPFCFissionFS.hh
References G4ParticleHPFCFissionFS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFCFissionFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPFCFissionFS.cc