ECCE @ EIC Software: G4RToEConvForGamma Class Reference
G4RToEConvForGamma Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4RToEConvForGamma.hh>
Public Member Functions
G4RToEConvForGamma ()
virtual ~G4RToEConvForGamma ()
Public Member Functions inherited from G4VRangeToEnergyConverter
G4VRangeToEnergyConverter ()
G4VRangeToEnergyConverter (const G4VRangeToEnergyConverter &right)
G4VRangeToEnergyConverter & operator= (const G4VRangeToEnergyConverter &right)
virtual ~G4VRangeToEnergyConverter ()
G4bool operator== (const G4VRangeToEnergyConverter &right) const
G4bool operator!= (const G4VRangeToEnergyConverter &right) const
virtual G4double Convert (G4double rangeCut, const G4Material *material)
const G4ParticleDefinition * GetParticleType () const
const G4PhysicsTable * GetLossTable () const
virtual void Reset ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Protected Types
typedef G4LossTable G4CrossSectionTable
Protected Types inherited from G4VRangeToEnergyConverter
typedef G4PhysicsTable G4LossTable
typedef G4PhysicsLogVector G4LossVector
typedef G4PhysicsLogVector G4RangeVector
Protected Member Functions
virtual G4double ComputeLoss (G4double AtomicNumber, G4double KineticEnergy)
virtual void BuildRangeVector (const G4Material *aMaterial, G4RangeVector *rangeVector)
void BuildAbsorptionLengthVector (const G4Material *aMaterial, G4RangeVector *rangeVector)
G4double ComputeCrossSection (G4double AtomicNumber, G4double KineticEnergy)
Protected Member Functions inherited from G4VRangeToEnergyConverter
virtual void BuildLossTable ()
G4double ConvertCutToKineticEnergy (G4RangeVector *theRangeVector, G4double theCutInLength, size_t materialIndex) const
Protected Attributes
G4double Z
G4double s200keV
G4double s1keV
G4double tmin
G4double tlow
G4double smin
G4double slow
G4double cmin
G4double clow
G4double chigh
Protected Attributes inherited from G4VRangeToEnergyConverter
G4double fMaxEnergyCut
const G4ParticleDefinition * theParticle
G4LossTable * theLossTable
G4int NumberOfElements
const G4int TotBin
std::vector< G4RangeVector * > fRangeVectorStore
Additional Inherited Members
Static Public Member Functions inherited from G4VRangeToEnergyConverter
static void SetEnergyRange (G4double lowedge, G4double highedge)
static G4double GetLowEdgeEnergy ()
static G4double GetHighEdgeEnergy ()
static G4double GetMaxEnergyCut ()
static void SetMaxEnergyCut (G4double value)
Static Protected Attributes inherited from G4VRangeToEnergyConverter
static G4double LowestEnergy = 0.99e-3*MeV
static G4double HighestEnergy = 100.0e6*MeV
static G4double MaxEnergyCut = 10.0*GeV
Detailed Description
Definition at line 50 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RToEConvForGamma.hh
Member Typedef Documentation
typedef G4LossTable G4RToEConvForGamma::G4CrossSectionTable protected
Definition at line 73 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 73 of file G4RToEConvForGamma.hh
Constructor & Destructor Documentation
G4RToEConvForGamma::G4RToEConvForGamma ()
Definition at line 43 of file G4RToEConvForGamma.cc.
View newest version in sPHENIX GitHub at line 43 of file G4RToEConvForGamma.cc
References G4ParticleTable::FindParticle(), G4cout, G4endl, G4ParticleTable::GetParticleTable(), G4VRangeToEnergyConverter::GetVerboseLevel(), and G4VRangeToEnergyConverter::theParticle.
G4RToEConvForGamma::~G4RToEConvForGamma () virtual
Definition at line 62 of file G4RToEConvForGamma.cc.
View newest version in sPHENIX GitHub at line 62 of file G4RToEConvForGamma.cc
Member Function Documentation
void G4RToEConvForGamma::BuildAbsorptionLengthVector (const G4Material * aMaterial, G4RangeVector * rangeVector) protected
Definition at line 70 of file G4RToEConvForGamma.cc.
View newest version in sPHENIX GitHub at line 70 of file G4RToEConvForGamma.cc
References G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Material::GetNumberOfElements(), G4PhysicsVector::PutValue(), G4VRangeToEnergyConverter::theLossTable, and G4VRangeToEnergyConverter::TotBin.
Referenced by BuildRangeVector().
void G4RToEConvForGamma::BuildRangeVector (const G4Material * aMaterial, G4RangeVector * rangeVector) inline protected virtual
Reimplemented from G4VRangeToEnergyConverter.
Definition at line 97 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 97 of file G4RToEConvForGamma.hh
References BuildAbsorptionLengthVector().
G4double G4RToEConvForGamma::ComputeCrossSection (G4double AtomicNumber, G4double KineticEnergy) protected
Definition at line 104 of file G4RToEConvForGamma.cc.
View newest version in sPHENIX GitHub at line 104 of file G4RToEConvForGamma.cc
References kdfinder::abs(), barn, chigh, clow, cmin, keV, MeV, s1keV, s200keV, slow, smin, tlow, tmin, and Z.
Referenced by ComputeLoss().
G4double G4RToEConvForGamma::ComputeLoss (G4double AtomicNumber, G4double KineticEnergy) inline protected virtual
Implements G4VRangeToEnergyConverter.
Definition at line 90 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RToEConvForGamma.hh
References ComputeCrossSection().
Member Data Documentation
G4double G4RToEConvForGamma::chigh protected
Definition at line 85 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::clow protected
Definition at line 85 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::cmin protected
Definition at line 85 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::s1keV protected
Definition at line 82 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 82 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::s200keV protected
Definition at line 82 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 82 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::slow protected
Definition at line 84 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 84 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::smin protected
Definition at line 84 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 84 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::tlow protected
Definition at line 83 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::tmin protected
Definition at line 83 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
G4double G4RToEConvForGamma::Z protected
Definition at line 81 of file G4RToEConvForGamma.hh.
View newest version in sPHENIX GitHub at line 81 of file G4RToEConvForGamma.hh
Referenced by ComputeCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4RToEConvForGamma.hh
geant4/tree/geant4-10.6-release/source/processes/cuts/src/G4RToEConvForGamma.cc