ECCE @ EIC Software: GammaRayTelEventAction Class Reference
GammaRayTelEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelEventAction.hh>
Public Member Functions
GammaRayTelEventAction (GammaRayTelRunAction *runAction=0)
virtual ~GammaRayTelEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
void SetDrawFlag (G4String val)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
G4int trackerCollID
G4int calorimeterCollID
G4int anticoincidenceCollID
G4String drawFlag
GammaRayTelRunAction * theRunAction
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 52 of file GammaRayTelEventAction.hh.
View newest version in sPHENIX GitHub at line 52 of file GammaRayTelEventAction.hh
Constructor & Destructor Documentation
GammaRayTelEventAction::GammaRayTelEventAction (GammaRayTelRunAction * runAction = 0)
Definition at line 68 of file GammaRayTelEventAction.cc.
View newest version in sPHENIX GitHub at line 68 of file GammaRayTelEventAction.cc
References G4DigiManager::AddNewModule(), and G4DigiManager::GetDMpointer().
GammaRayTelEventAction::~GammaRayTelEventAction () virtual
Definition at line 79 of file GammaRayTelEventAction.cc.
View newest version in sPHENIX GitHub at line 79 of file GammaRayTelEventAction.cc
Member Function Documentation
void GammaRayTelEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 84 of file GammaRayTelEventAction.cc.
View newest version in sPHENIX GitHub at line 84 of file GammaRayTelEventAction.cc
References anticoincidenceCollID, calorimeterCollID, G4cout, G4endl, G4SDManager::GetCollectionID(), G4Event::GetEventID(), G4SDManager::GetSDMpointer(), and trackerCollID.
void GammaRayTelEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 105 of file GammaRayTelEventAction.cc.
View newest version in sPHENIX GitHub at line 105 of file GammaRayTelEventAction.cc
References static_analysis_results::analysis(), GammaRayTelDigitizer::Digitize(), GammaRayTelAnalysis::EndOfEvent(), G4TDigiCollection< T >::entries(), G4THitsCollection< T >::entries(), FatalException, G4DigiManager::FindDigitizerModule(), G4cout, G4endl, G4Exception(), G4DigiManager::GetDigiCollection(), G4DigiManager::GetDigiCollectionID(), G4DigiManager::GetDMpointer(), G4Event::GetEventID(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), GammaRayTelAnalysis::GetHisto2DMode(), GammaRayTelAnalysis::getInstance(), GammaRayTelRunAction::GetOutputFile(), GammaRayTelAnalysis::InsertEnergy(), GammaRayTelAnalysis::InsertHits(), GammaRayTelAnalysis::InsertPositionXZ(), GammaRayTelAnalysis::InsertPositionYZ(), keV, mm, GammaRayTelAnalysis::setNtuple(), theRunAction, trackerCollID, x, y, and z.
void GammaRayTelEventAction::SetDrawFlag (G4String val) inline
Definition at line 63 of file GammaRayTelEventAction.hh.
View newest version in sPHENIX GitHub at line 63 of file GammaRayTelEventAction.hh
Member Data Documentation
G4int GammaRayTelEventAction::anticoincidenceCollID private
Definition at line 69 of file GammaRayTelEventAction.hh.
View newest version in sPHENIX GitHub at line 69 of file GammaRayTelEventAction.hh
Referenced by BeginOfEventAction().
G4int GammaRayTelEventAction::calorimeterCollID private
Definition at line 68 of file GammaRayTelEventAction.hh.
View newest version in sPHENIX GitHub at line 68 of file GammaRayTelEventAction.hh
Referenced by BeginOfEventAction().
G4String GammaRayTelEventAction::drawFlag private
Definition at line 70 of file GammaRayTelEventAction.hh.
View newest version in sPHENIX GitHub at line 70 of file GammaRayTelEventAction.hh
GammaRayTelRunAction* GammaRayTelEventAction::theRunAction private
Definition at line 72 of file GammaRayTelEventAction.hh.
View newest version in sPHENIX GitHub at line 72 of file GammaRayTelEventAction.hh
Referenced by EndOfEventAction().
G4int GammaRayTelEventAction::trackerCollID private
Definition at line 63 of file GammaRayTelEventAction.hh.
View newest version in sPHENIX GitHub at line 63 of file GammaRayTelEventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelEventAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelEventAction.cc