ECCE @ EIC Software: cheprep::ZipOutputStreamBuffer Class Reference
cheprep::ZipOutputStreamBuffer Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/ZipOutputStreamBuffer.h>
Public Member Functions
ZipOutputStreamBuffer (std::streambuf *buffer)
int overflow (int c)
void closeEntry ()
void close ()
void putNextEntry (const std::string &name, bool compress)
void setMethod (int method)
void setComment (const std::string &comment)
virtual ~ZipOutputStreamBuffer ()
Public Member Functions inherited from cheprep::DeflateOutputStreamBuffer
DeflateOutputStreamBuffer (std::streambuf *buffer)
void init (bool compress)
void finish ()
virtual ~DeflateOutputStreamBuffer ()
Private Attributes
std::string comment
bool closed
ZipEntry * entry
std::vector< ZipEntry * > * entries
Static Private Attributes
static const unsigned int LOCSIG = 0x04034b50
static const unsigned int EXTSIG = 0x08074b50
static const unsigned int CENSIG = 0x02014b50
static const unsigned int ENDSIG = 0x06054b50
static const unsigned int VERSIONMADE = 0x0014
static const unsigned int VERSIONEXTRACT = 0x0014
static const unsigned int GENFLAG = 0x0008
Additional Inherited Members
Protected Member Functions inherited from cheprep::DeflateOutputStreamBuffer
int overflow (int c=EOF)
bool flushOut ()
void putUI (unsigned int ui)
void putUS (unsigned short us)
void putUB (unsigned char ub)
void putS (const std::string s)
std::streampos pos ()
unsigned int getSize ()
unsigned int getCRC ()
Detailed Description
Definition at line 18 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 18 of file ZipOutputStreamBuffer.h
Constructor & Destructor Documentation
cheprep::ZipOutputStreamBuffer::ZipOutputStreamBuffer (std::streambuf * buffer)
Definition at line 16 of file ZipOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 16 of file ZipOutputStreamBuffer.cc
References closed, entries, and entry.
cheprep::ZipOutputStreamBuffer::~ZipOutputStreamBuffer () virtual
Definition at line 139 of file ZipOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 139 of file ZipOutputStreamBuffer.cc
References close().
Member Function Documentation
void cheprep::ZipOutputStreamBuffer::close (void)
Definition at line 48 of file ZipOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 48 of file ZipOutputStreamBuffer.cc
References CENSIG, closed, closeEntry(), comment, cheprep::ZipEntry::crc, cheprep::ZipEntry::csize, cheprep::ZipEntry::date, ENDSIG, entries, entry, GENFLAG, cheprep::ZipEntry::method, cheprep::ZipEntry::name, cheprep::ZipEntry::offset, cheprep::DeflateOutputStreamBuffer::pos(), cheprep::DeflateOutputStreamBuffer::putS(), cheprep::DeflateOutputStreamBuffer::putUI(), cheprep::DeflateOutputStreamBuffer::putUS(), cheprep::ZipEntry::size, cheprep::ZipEntry::time, VERSIONEXTRACT, and VERSIONMADE.
Referenced by ~ZipOutputStreamBuffer().
void cheprep::ZipOutputStreamBuffer::closeEntry ()
Definition at line 30 of file ZipOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 30 of file ZipOutputStreamBuffer.cc
References closed, cheprep::ZipEntry::crc, cheprep::ZipEntry::csize, cheprep::ZipEntry::data, entry, EXTSIG, cheprep::DeflateOutputStreamBuffer::finish(), cheprep::DeflateOutputStreamBuffer::getCRC(), cheprep::DeflateOutputStreamBuffer::getSize(), cheprep::DeflateOutputStreamBuffer::pos(), cheprep::DeflateOutputStreamBuffer::putUI(), and cheprep::ZipEntry::size.
Referenced by close(), and putNextEntry().
int cheprep::ZipOutputStreamBuffer::overflow (int c)
Definition at line 26 of file ZipOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 26 of file ZipOutputStreamBuffer.cc
References cheprep::DeflateOutputStreamBuffer::overflow().
void cheprep::ZipOutputStreamBuffer::putNextEntry (const std::string & name, bool compress)
Definition at line 95 of file ZipOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 95 of file ZipOutputStreamBuffer.cc
References closed, closeEntry(), cheprep::ZipEntry::crc, cheprep::ZipEntry::data, cheprep::ZipEntry::date, entries, entry, GENFLAG, cheprep::DeflateOutputStreamBuffer::init(), LOCSIG, cheprep::ZipEntry::method, cheprep::ZipEntry::name, cheprep::ZipEntry::offset, cheprep::DeflateOutputStreamBuffer::pos(), cheprep::DeflateOutputStreamBuffer::putS(), cheprep::DeflateOutputStreamBuffer::putUI(), cheprep::DeflateOutputStreamBuffer::putUS(), cheprep::ZipEntry::time, Acts::VectorHelpers::time(), G4InuclParticleNames::tm, and VERSIONEXTRACT.
void cheprep::ZipOutputStreamBuffer::setComment (const std::string & comment)
Definition at line 134 of file ZipOutputStreamBuffer.cc.
View newest version in sPHENIX GitHub at line 134 of file ZipOutputStreamBuffer.cc
References c, closed, and comment.
void cheprep::ZipOutputStreamBuffer::setMethod (int method)
Member Data Documentation
const unsigned int cheprep::ZipOutputStreamBuffer::CENSIG = 0x02014b50 static private
Definition at line 47 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 47 of file ZipOutputStreamBuffer.h
Referenced by close().
bool cheprep::ZipOutputStreamBuffer::closed private
Definition at line 41 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 41 of file ZipOutputStreamBuffer.h
Referenced by close(), closeEntry(), putNextEntry(), setComment(), and ZipOutputStreamBuffer().
std::string cheprep::ZipOutputStreamBuffer::comment private
Definition at line 39 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 39 of file ZipOutputStreamBuffer.h
Referenced by close(), and setComment().
const unsigned int cheprep::ZipOutputStreamBuffer::ENDSIG = 0x06054b50 static private
Definition at line 48 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 48 of file ZipOutputStreamBuffer.h
Referenced by close().
std::vector<ZipEntry*>* cheprep::ZipOutputStreamBuffer::entries private
Definition at line 43 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 43 of file ZipOutputStreamBuffer.h
Referenced by close(), putNextEntry(), and ZipOutputStreamBuffer().
ZipEntry* cheprep::ZipOutputStreamBuffer::entry private
Definition at line 42 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 42 of file ZipOutputStreamBuffer.h
Referenced by close(), closeEntry(), putNextEntry(), and ZipOutputStreamBuffer().
const unsigned int cheprep::ZipOutputStreamBuffer::EXTSIG = 0x08074b50 static private
Definition at line 46 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 46 of file ZipOutputStreamBuffer.h
Referenced by closeEntry().
const unsigned int cheprep::ZipOutputStreamBuffer::GENFLAG = 0x0008 static private
Definition at line 52 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 52 of file ZipOutputStreamBuffer.h
Referenced by close(), and putNextEntry().
const unsigned int cheprep::ZipOutputStreamBuffer::LOCSIG = 0x04034b50 static private
Definition at line 45 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 45 of file ZipOutputStreamBuffer.h
Referenced by putNextEntry().
const unsigned int cheprep::ZipOutputStreamBuffer::VERSIONEXTRACT = 0x0014 static private
Definition at line 51 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 51 of file ZipOutputStreamBuffer.h
Referenced by close(), and putNextEntry().
const unsigned int cheprep::ZipOutputStreamBuffer::VERSIONMADE = 0x0014 static private
Definition at line 50 of file ZipOutputStreamBuffer.h.
View newest version in sPHENIX GitHub at line 50 of file ZipOutputStreamBuffer.h
Referenced by close().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/ZipOutputStreamBuffer.h
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/ZipOutputStreamBuffer.cc