ECCE @ EIC Software: G4Clebsch Class Reference
G4Clebsch Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4Clebsch.hh>
Static Public Member Functions
static G4double ClebschGordanCoeff (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJ)
static G4double ClebschGordan (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJ)
static std::vector< G4double > GenerateIso3 (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJOut1, G4int twoJOut2)
static G4double Weight (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJOut1, G4int twoJOut2)
static G4double Wigner3J (G4double j1, G4double j2, G4double j3, G4double m1, G4double m2, G4double m3)
static G4double Wigner3J (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJ3)
static G4double Wigner3J (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJ3, G4int twoM3)
static G4double NormalizedClebschGordan (G4int twoJ, G4int twom, G4int twoJ1, G4int twoJ2, G4int twom1, G4int twom2)
static G4double TriangleCoeff (G4int twoA, G4int twoB, G4int twoC)
static G4double Wigner6J (G4int twoJ1, G4int twoJ2, G4int twoJ3, G4int twoJ4, G4int twoJ5, G4int twoJ6)
static G4double RacahWCoeff (G4int twoJ1, G4int twoJ2, G4int twoJ, G4int twoJ3, G4int twoJ12, G4int twoJ23)
static G4double Wigner9J (G4int twoJ1, G4int twoJ2, G4int twoJ3, G4int twoJ4, G4int twoJ5, G4int twoJ6, G4int twoJ7, G4int twoJ8, G4int twoJ9)
static G4double WignerLittleD (G4int twoJ, G4int twoM, G4int twoN, G4double cosTheta)
Detailed Description
Definition at line 62 of file G4Clebsch.hh.
View newest version in sPHENIX GitHub at line 62 of file G4Clebsch.hh
Member Function Documentation
G4double G4Clebsch::ClebschGordan (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJ) static
Definition at line 106 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 106 of file G4Clebsch.cc
G4double G4Clebsch::ClebschGordanCoeff (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJ) static
Definition at line 37 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 37 of file G4Clebsch.cc
References G4Exception(), G4Exp(), G4POWLOGFACTMAX, G4Pow::GetInstance(), JustWarning, k, BoundingBox::kMax, BoundingBox::kMin, G4Pow::logfactorial(), and sign().
std::vector< G4double > G4Clebsch::GenerateIso3 (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJOut1, G4int twoJOut2) static
Definition at line 116 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 116 of file G4Clebsch.cc
References kdfinder::abs(), G4Exception(), G4UniformRand, JustWarning, max, min, and sum.
Referenced by G4VXResonance::IsospinCorrection().
G4double G4Clebsch::NormalizedClebschGordan (G4int twoJ, G4int twom, G4int twoJ1, G4int twoJ2, G4int twom1, G4int twom2) static
Definition at line 380 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 380 of file G4Clebsch.cc
References sum.
Referenced by G4XAnnihilationChannel::NormalizedClebsch().
static G4double G4Clebsch::RacahWCoeff (G4int twoJ1, G4int twoJ2, G4int twoJ, G4int twoJ3, G4int twoJ12, G4int twoJ23) static
G4double G4Clebsch::TriangleCoeff (G4int twoA, G4int twoB, G4int twoC) static
Definition at line 407 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 407 of file G4Clebsch.cc
References G4Exp(), G4Pow::GetInstance(), and G4Pow::logfactorial().
G4double G4Clebsch::Weight (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJOut1, G4int twoJOut2) static
Definition at line 320 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 320 of file G4Clebsch.cc
References kdfinder::abs(), max, and min.
Referenced by G4VXResonance::DetailedBalance(), and G4VXResonance::IsospinCorrection().
G4double G4Clebsch::Wigner3J (G4double j1, G4double j2, G4double j3, G4double m1, G4double m2, G4double m3) static
Definition at line 345 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 345 of file G4Clebsch.cc
Referenced by G4PolarizationTransition::F3Coefficient(), G4PolarizationTransition::FCoefficient(), and G4PolarizationTransition::SampleGammaTransition().
G4double G4Clebsch::Wigner3J (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJ3) static
Definition at line 359 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 359 of file G4Clebsch.cc
G4double G4Clebsch::Wigner3J (G4int twoJ1, G4int twoM1, G4int twoJ2, G4int twoM2, G4int twoJ3, G4int twoM3) static
Definition at line 369 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 369 of file G4Clebsch.cc
G4double G4Clebsch::Wigner6J (G4int twoJ1, G4int twoJ2, G4int twoJ3, G4int twoJ4, G4int twoJ5, G4int twoJ6) static
Definition at line 432 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 432 of file G4Clebsch.cc
References G4Exception(), G4Exp(), G4POWLOGFACTMAX, G4Pow::GetInstance(), JustWarning, k, BoundingBox::kMax, BoundingBox::kMin, G4Pow::logfactorial(), and sign().
Referenced by G4PolarizationTransition::FCoefficient().
G4double G4Clebsch::Wigner9J (G4int twoJ1, G4int twoJ2, G4int twoJ3, G4int twoJ4, G4int twoJ5, G4int twoJ6, G4int twoJ7, G4int twoJ8, G4int twoJ9) static
Definition at line 533 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 533 of file G4Clebsch.cc
References sign(), and sum.
Referenced by G4PolarizationTransition::F3Coefficient().
G4double G4Clebsch::WignerLittleD (G4int twoJ, G4int twoM, G4int twoN, G4double cosTheta) static
Definition at line 609 of file G4Clebsch.cc.
View newest version in sPHENIX GitHub at line 609 of file G4Clebsch.cc
References d, G4Exp(), G4Log(), G4Pow::GetInstance(), k, BoundingBox::kMax, BoundingBox::kMin, G4Pow::logfactorial(), and sign().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4Clebsch.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4Clebsch.cc