ECCE @ EIC Software: DicomVFile Class Reference
DicomVFile Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomVFile.hh>
Public Member Functions
DicomVFile ()
DicomVFile (DcmDataset *dset)
~DicomVFile ()
void SetFileName (G4String fName)
Protected Member Functions
virtual void ReadData ()=0
virtual std::vector< G4double > Read1Data (DcmDataset *dset, DcmTagKey tagKey, G4int nData)
virtual OFString Read1DataStr (DcmDataset *dset, DcmTagKey tagKey)
Protected Attributes
DcmDataset * theDataset
G4String fFileName
Detailed Description
Definition at line 35 of file DicomVFile.hh.
View newest version in sPHENIX GitHub at line 35 of file DicomVFile.hh
Constructor & Destructor Documentation
DicomVFile::DicomVFile () inline
Definition at line 38 of file DicomVFile.hh.
View newest version in sPHENIX GitHub at line 38 of file DicomVFile.hh
DicomVFile::DicomVFile (DcmDataset * dset)
Definition at line 35 of file DicomVFile.cc.
View newest version in sPHENIX GitHub at line 35 of file DicomVFile.cc
DicomVFile::~DicomVFile () inline
Definition at line 40 of file DicomVFile.hh.
View newest version in sPHENIX GitHub at line 40 of file DicomVFile.hh
Member Function Documentation
std::vector< G4double > DicomVFile::Read1Data (DcmDataset * dset, DcmTagKey tagKey, G4int nData) protected virtual
Definition at line 40 of file DicomVFile.cc.
View newest version in sPHENIX GitHub at line 40 of file DicomVFile.cc
References G4cout, G4Exception(), JustWarning, and nlohmann::to_string().
Referenced by DicomVFileImage::ReadData().
OFString DicomVFile::Read1DataStr (DcmDataset * dset, DcmTagKey tagKey) protected virtual
Definition at line 71 of file DicomVFile.cc.
View newest version in sPHENIX GitHub at line 71 of file DicomVFile.cc
References G4cout, G4Exception(), JustWarning, and nlohmann::to_string().
virtual void DicomVFile::ReadData () protected pure virtual
Implemented in DicomFilePlan, DicomFileStructure, DicomFileCT_NOdcmrt, and DicomVFileImage.
void DicomVFile::SetFileName (G4String fName) inline
Definition at line 42 of file DicomVFile.hh.
View newest version in sPHENIX GitHub at line 42 of file DicomVFile.hh
References fFileName, and fName.
Referenced by DicomFileMgr::AddFile().
Member Data Documentation
G4String DicomVFile::fFileName protected
Definition at line 55 of file DicomVFile.hh.
View newest version in sPHENIX GitHub at line 55 of file DicomVFile.hh
Referenced by DicomFilePET::DumpActivitiesToTextFile(), DicomFileCT::DumpDensitiesToTextFile(), DicomVFileImage::DumpHeaderToTextFile(), DicomFileCT::DumpMateIDsToTextFile(), DicomFileCT::DumpStructureIDsToTextFile(), and SetFileName().
DcmDataset* DicomVFile::theDataset protected
Definition at line 52 of file DicomVFile.hh.
View newest version in sPHENIX GitHub at line 52 of file DicomVFile.hh
Referenced by DicomVFileImage::ReadData(), DicomFileStructure::ReadData(), DicomFilePlan::ReadData(), and DicomVFileImage::ReadPixelData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomVFile.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/src/DicomVFile.cc