ECCE @ EIC Software: G4LENDGammaCrossSection Class Reference
G4LENDGammaCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDGammaCrossSection.hh>
Public Member Functions
G4LENDGammaCrossSection (G4ParticleDefinition *pd)
~G4LENDGammaCrossSection ()
void BuildPhysicsTable (const G4ParticleDefinition &)
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int, G4int, const G4Isotope *, const G4Element *, const G4Material *)
G4int SelectChannel (const G4DynamicParticle *, G4int, G4int, const G4Isotope *, const G4Element *, const G4Material *)
Public Member Functions inherited from G4LENDCrossSection
G4LENDCrossSection (const G4String name="")
~G4LENDCrossSection ()
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int, G4int, const G4Element *, const G4Material *)
void DumpPhysicsTable (const G4ParticleDefinition &)
void DumpLENDTargetInfo (G4bool force=false)
void ChangeDefaultEvaluation (G4String name_tmp)
void AllowNaturalAbundanceTarget ()
void AllowAnyCandidateTarget ()
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Attributes
G4LENDInelasticCrossSection * inelasticXS
G4LENDFissionCrossSection * fissionXS
Additional Inherited Members
Protected Member Functions inherited from G4LENDCrossSection
void create_used_target_map ()
G4GIDI_target * get_target_from_map (G4int nuclear_code)
virtual G4double getLENDCrossSection (G4GIDI_target *, G4double, G4double)
G4double GetUltraLowEnergyExtrapolatedXS (G4double, G4double, G4double, G4double, G4double)
Protected Attributes inherited from G4LENDCrossSection
G4ParticleDefinition * proj
Detailed Description
Definition at line 49 of file G4LENDGammaCrossSection.hh.
View newest version in sPHENIX GitHub at line 49 of file G4LENDGammaCrossSection.hh
Constructor & Destructor Documentation
G4LENDGammaCrossSection::G4LENDGammaCrossSection (G4ParticleDefinition * pd)
Definition at line 46 of file G4LENDGammaCrossSection.cc.
View newest version in sPHENIX GitHub at line 46 of file G4LENDGammaCrossSection.cc
References fissionXS, inelasticXS, and G4LENDCrossSection::proj.
G4LENDGammaCrossSection::~G4LENDGammaCrossSection () inline
Definition at line 53 of file G4LENDGammaCrossSection.hh.
View newest version in sPHENIX GitHub at line 53 of file G4LENDGammaCrossSection.hh
Member Function Documentation
void G4LENDGammaCrossSection::BuildPhysicsTable (const G4ParticleDefinition & pd) virtual
Reimplemented from G4LENDCrossSection.
Definition at line 54 of file G4LENDGammaCrossSection.cc.
View newest version in sPHENIX GitHub at line 54 of file G4LENDGammaCrossSection.cc
References G4LENDCrossSection::BuildPhysicsTable(), G4LENDCrossSection::create_used_target_map(), fissionXS, and inelasticXS.
Referenced by G4LENDGammaModel::BuildPhysicsTable().
G4double G4LENDGammaCrossSection::GetIsoCrossSection (const G4DynamicParticle * dp, G4int iZ, G4int iA, const G4Isotope * isotope, const G4Element * , const G4Material * material) virtual
Reimplemented from G4LENDCrossSection.
Definition at line 62 of file G4LENDGammaCrossSection.cc.
View newest version in sPHENIX GitHub at line 62 of file G4LENDGammaCrossSection.cc
References fissionXS, G4LENDCrossSection::GetIsoCrossSection(), and inelasticXS.
G4int G4LENDGammaCrossSection::SelectChannel (const G4DynamicParticle * dp, G4int iZ, G4int iA, const G4Isotope * isotope, const G4Element * , const G4Material * material)
Definition at line 76 of file G4LENDGammaCrossSection.cc.
View newest version in sPHENIX GitHub at line 76 of file G4LENDGammaCrossSection.cc
References fissionXS, G4UniformRand, G4LENDCrossSection::GetIsoCrossSection(), inelasticXS, and G4INCL::CrossSections::total().
Referenced by G4LENDGammaModel::ApplyYourself().
Member Data Documentation
G4LENDFissionCrossSection* G4LENDGammaCrossSection::fissionXS private
Definition at line 67 of file G4LENDGammaCrossSection.hh.
View newest version in sPHENIX GitHub at line 67 of file G4LENDGammaCrossSection.hh
Referenced by BuildPhysicsTable(), G4LENDGammaCrossSection(), GetIsoCrossSection(), and SelectChannel().
G4LENDInelasticCrossSection* G4LENDGammaCrossSection::inelasticXS private
Definition at line 66 of file G4LENDGammaCrossSection.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LENDGammaCrossSection.hh
Referenced by BuildPhysicsTable(), G4LENDGammaCrossSection(), GetIsoCrossSection(), and SelectChannel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDGammaCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4LENDGammaCrossSection.cc