ECCE @ EIC Software: G4VFSALIntegrationStepper Class Reference
G4VFSALIntegrationStepper Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4VFSALIntegrationStepper.hh>
Public Member Functions
G4VFSALIntegrationStepper (G4EquationOfMotion *Equation, G4int numIntegrationVariables, G4int numStateVariables=12)
virtual ~G4VFSALIntegrationStepper ()=default
G4VFSALIntegrationStepper (const G4VFSALIntegrationStepper &)=delete
G4VFSALIntegrationStepper & operator= (const G4VFSALIntegrationStepper &)=delete
virtual void Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[], G4double lastDydx[])=0
virtual G4double DistChord () const =0
void NormaliseTangentVector (G4double vec[6])
void NormalisePolarizationVector (G4double vec[12])
void RightHandSide (const double y[], double dydx[])
G4int GetNumberOfVariables () const
G4int GetNumberOfStateVariables () const
virtual G4int IntegratorOrder () const =0
G4EquationOfMotion * GetEquationOfMotion ()
void SetEquationOfMotion (G4EquationOfMotion *newEquation)
G4int GetfNoRHSCalls ()
void increasefNORHSCalls ()
void ResetfNORHSCalls ()
Private Attributes
G4EquationOfMotion * fEquation_Rhs = nullptr
const G4int fNoIntegrationVariables = 0
const G4int fNoStateVariables = 0
G4int fNoRHSCalls = 0
Detailed Description
Definition at line 49 of file G4VFSALIntegrationStepper.hh.
View newest version in sPHENIX GitHub at line 49 of file G4VFSALIntegrationStepper.hh
Constructor & Destructor Documentation
G4VFSALIntegrationStepper::G4VFSALIntegrationStepper (G4EquationOfMotion * Equation, G4int numIntegrationVariables, G4int numStateVariables = 12)
Definition at line 37 of file G4VFSALIntegrationStepper.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VFSALIntegrationStepper.cc
virtual G4VFSALIntegrationStepper::~G4VFSALIntegrationStepper () virtual default
G4VFSALIntegrationStepper::G4VFSALIntegrationStepper (const G4VFSALIntegrationStepper &) delete
Member Function Documentation
virtual G4double G4VFSALIntegrationStepper::DistChord () const pure virtual
Implemented in G4FSALDormandPrince745, and G4FSALBogackiShampine45.
G4EquationOfMotion* G4VFSALIntegrationStepper::GetEquationOfMotion () inline
G4int G4VFSALIntegrationStepper::GetfNoRHSCalls () inline
Definition at line 106 of file G4VFSALIntegrationStepper.hh.
View newest version in sPHENIX GitHub at line 106 of file G4VFSALIntegrationStepper.hh
References fNoRHSCalls.
G4int G4VFSALIntegrationStepper::GetNumberOfStateVariables () const inline
Referenced by G4FSALBogackiShampine45::G4FSALBogackiShampine45().
G4int G4VFSALIntegrationStepper::GetNumberOfVariables () const inline
Referenced by G4FSALDormandPrince745::interpolate(), G4FSALBogackiShampine45::interpolate(), G4FSALDormandPrince745::Interpolate(), G4FSALDormandPrince745::SetupInterpolate(), G4FSALDormandPrince745::Stepper(), and G4FSALBogackiShampine45::Stepper().
void G4VFSALIntegrationStepper::increasefNORHSCalls ()
Definition at line 46 of file G4VFSALIntegrationStepper.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VFSALIntegrationStepper.cc
References fNoRHSCalls.
Referenced by RightHandSide().
virtual G4int G4VFSALIntegrationStepper::IntegratorOrder () const pure virtual
Implemented in G4FSALDormandPrince745, and G4FSALBogackiShampine45.
void G4VFSALIntegrationStepper::NormalisePolarizationVector (G4double vec[12]) inline
void G4VFSALIntegrationStepper::NormaliseTangentVector (G4double vec[6]) inline
G4VFSALIntegrationStepper& G4VFSALIntegrationStepper::operator= (const G4VFSALIntegrationStepper &) delete
void G4VFSALIntegrationStepper::ResetfNORHSCalls () inline
Definition at line 108 of file G4VFSALIntegrationStepper.hh.
View newest version in sPHENIX GitHub at line 108 of file G4VFSALIntegrationStepper.hh
References fNoRHSCalls.
void G4VFSALIntegrationStepper::RightHandSide (const double y[], double dydx[])
Definition at line 51 of file G4VFSALIntegrationStepper.cc.
View newest version in sPHENIX GitHub at line 51 of file G4VFSALIntegrationStepper.cc
References fEquation_Rhs, increasefNORHSCalls(), and G4EquationOfMotion::RightHandSide().
Referenced by G4FSALBogackiShampine45::interpolate(), G4FSALDormandPrince745::SetupInterpolate(), G4FSALDormandPrince745::Stepper(), and G4FSALBogackiShampine45::Stepper().
void G4VFSALIntegrationStepper::SetEquationOfMotion (G4EquationOfMotion * newEquation) inline
virtual void G4VFSALIntegrationStepper::Stepper (const G4double y[], const G4double dydx[], G4double h, G4double yout[], G4double yerr[], G4double lastDydx[]) pure virtual
Implemented in G4FSALBogackiShampine45, and G4FSALDormandPrince745.
Member Data Documentation
G4EquationOfMotion* G4VFSALIntegrationStepper::fEquation_Rhs = nullptr private
Definition at line 112 of file G4VFSALIntegrationStepper.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VFSALIntegrationStepper.hh
Referenced by RightHandSide().
const G4int G4VFSALIntegrationStepper::fNoIntegrationVariables = 0 private
Definition at line 113 of file G4VFSALIntegrationStepper.hh.
View newest version in sPHENIX GitHub at line 113 of file G4VFSALIntegrationStepper.hh
G4int G4VFSALIntegrationStepper::fNoRHSCalls = 0 private
Definition at line 116 of file G4VFSALIntegrationStepper.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VFSALIntegrationStepper.hh
Referenced by GetfNoRHSCalls(), increasefNORHSCalls(), and ResetfNORHSCalls().
const G4int G4VFSALIntegrationStepper::fNoStateVariables = 0 private
Definition at line 114 of file G4VFSALIntegrationStepper.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VFSALIntegrationStepper.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4VFSALIntegrationStepper.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4VFSALIntegrationStepper.cc