ECCE @ EIC Software: G4CascadeChannelTables Class Reference
G4CascadeChannelTables Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeChannelTables.hh>
Public Member Functions
~G4CascadeChannelTables ()
Static Public Member Functions
static const G4CascadeChannel * GetTable (G4int initialState)
static const G4CascadeChannel * GetTable (G4int had1, G4int had2)
static void Print (std::ostream &os=G4cout)
static void PrintTable (G4int initialState, std::ostream &os=G4cout)
Private Types
typedef std::map< G4int,
G4CascadeChannel * > TableMap
Private Member Functions
G4CascadeChannelTables ()
const G4CascadeChannel * FindTable (G4int initialState) const
Static Private Member Functions
static const
G4CascadeChannelTables & instance ()
Private Attributes
TableMap tables
Static Private Attributes
static G4ThreadLocal
G4CascadeChannelTables * theInstance = 0
Detailed Description
Definition at line 52 of file G4CascadeChannelTables.hh.
View newest version in sPHENIX GitHub at line 52 of file G4CascadeChannelTables.hh
Member Typedef Documentation
typedef std::map<G4int, G4CascadeChannel*> G4CascadeChannelTables::TableMap private
Definition at line 76 of file G4CascadeChannelTables.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CascadeChannelTables.hh
Constructor & Destructor Documentation
G4CascadeChannelTables::~G4CascadeChannelTables ()
Definition at line 140 of file G4CascadeChannelTables.cc.
View newest version in sPHENIX GitHub at line 140 of file G4CascadeChannelTables.cc
G4CascadeChannelTables::G4CascadeChannelTables () private
Definition at line 102 of file G4CascadeChannelTables.cc.
View newest version in sPHENIX GitHub at line 102 of file G4CascadeChannelTables.cc
References G4InuclParticleNames::gam, G4InuclParticleNames::k0, G4InuclParticleNames::k0b, G4InuclParticleNames::kmi, G4InuclParticleNames::kpl, G4InuclParticleNames::lam, G4InuclParticleNames::mum, G4InuclParticleNames::neu, G4InuclParticleNames::om, G4InuclParticleNames::pi0, G4InuclParticleNames::pim, G4InuclParticleNames::pip, G4InuclParticleNames::pro, G4InuclParticleNames::s0, G4InuclParticleNames::sm, G4InuclParticleNames::sp, G4InuclParticleNames::xi0, and G4InuclParticleNames::xim.
Member Function Documentation
const G4CascadeChannel * G4CascadeChannelTables::FindTable (G4int initialState) const private
Definition at line 166 of file G4CascadeChannelTables.cc.
View newest version in sPHENIX GitHub at line 166 of file G4CascadeChannelTables.cc
References G4cout, and G4endl.
const G4CascadeChannel * G4CascadeChannelTables::GetTable (G4int initialState) static
Definition at line 152 of file G4CascadeChannelTables.cc.
View newest version in sPHENIX GitHub at line 152 of file G4CascadeChannelTables.cc
References instance.
Referenced by G4LightTargetCollider::collide(), G4InuclCollider::collide(), G4ElementaryParticleCollider::collide(), G4IntraNucleiCascader::decayTrappedParticle(), G4ElementaryParticleCollider::generateMultiplicity(), G4ElementaryParticleCollider::generateOutgoingPartTypes(), G4CascadeInterface::Initialize(), G4CascadeInterface::IsApplicable(), G4IntraNucleiCascader::particleCanInteract(), G4LightTargetCollider::SingleNucleonScattering(), and G4NucleiModel::totalCrossSection().
const G4CascadeChannel * G4CascadeChannelTables::GetTable (G4int had1, G4int had2) static
Definition at line 159 of file G4CascadeChannelTables.cc.
View newest version in sPHENIX GitHub at line 159 of file G4CascadeChannelTables.cc
const G4CascadeChannelTables & G4CascadeChannelTables::instance () static private
Definition at line 90 of file G4CascadeChannelTables.cc.
View newest version in sPHENIX GitHub at line 90 of file G4CascadeChannelTables.cc
References G4AutoDelete::Register().
void G4CascadeChannelTables::Print (std::ostream & os = G4cout) static
Definition at line 177 of file G4CascadeChannelTables.cc.
View newest version in sPHENIX GitHub at line 177 of file G4CascadeChannelTables.cc
References instance.
Referenced by G4ElementaryParticleCollider::collide().
void G4CascadeChannelTables::PrintTable (G4int initialState, std::ostream & os = G4cout) static
Definition at line 185 of file G4CascadeChannelTables.cc.
View newest version in sPHENIX GitHub at line 185 of file G4CascadeChannelTables.cc
References G4CascadeChannel::printTable().
Member Data Documentation
TableMap G4CascadeChannelTables::tables private
Definition at line 77 of file G4CascadeChannelTables.hh.
View newest version in sPHENIX GitHub at line 77 of file G4CascadeChannelTables.hh
G4ThreadLocal G4CascadeChannelTables * G4CascadeChannelTables::theInstance = 0 static private
Definition at line 69 of file G4CascadeChannelTables.hh.
View newest version in sPHENIX GitHub at line 69 of file G4CascadeChannelTables.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeChannelTables.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeChannelTables.cc