ECCE @ EIC Software: G4WorkerRunManagerKernel Class Reference
G4WorkerRunManagerKernel Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4WorkerRunManagerKernel.hh>
Public Member Functions
G4WorkerRunManagerKernel ()
virtual ~G4WorkerRunManagerKernel ()
Public Member Functions inherited from G4RunManagerKernel
G4RunManagerKernel ()
virtual ~G4RunManagerKernel ()
void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
void WorkerDefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
void SetPhysics (G4VUserPhysicsList *uPhys)
void InitializePhysics ()
G4bool RunInitialization (G4bool fakeRun=false)
void RunTermination ()
void WorkerUpdateWorldVolume ()
void UpdateRegion ()
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
void GeometryHasBeenModified ()
void PhysicsHasBeenModified ()
G4EventManager * GetEventManager () const
G4StackManager * GetStackManager () const
G4TrackingManager * GetTrackingManager () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
G4PrimaryTransformer * GetPrimaryTransformer () const
const G4String & GetVersionString () const
void SetVerboseLevel (G4int vl)
void SetGeometryToBeOptimized (G4bool vl)
G4int GetNumberOfParallelWorld () const
void SetNumberOfParallelWorld (G4int i)
G4VUserPhysicsList * GetPhysicsList () const
G4VPhysicalVolume * GetCurrentWorld () const
G4int GetNumberOfStaticAllocators () const
Protected Member Functions
void SetupShadowProcess () const
Protected Member Functions inherited from G4RunManagerKernel
G4RunManagerKernel (RMKType rmkType)
void SetupDefaultRegion ()
void SetupPhysics ()
void ResetNavigator ()
void BuildPhysicsTables (G4bool fakeRun)
void CheckRegions ()
void PropagateGenericIonID ()
Additional Inherited Members
Public Types inherited from G4RunManagerKernel
enum RMKType { sequentialRMK, masterRMK, workerRMK }
Static Public Member Functions inherited from G4RunManagerKernel
static G4RunManagerKernel * GetRunManagerKernel ()
Protected Attributes inherited from G4RunManagerKernel
RMKType runManagerKernelType
G4Region * defaultRegion
G4Region * defaultRegionForParallelWorld
G4bool geometryNeedsToBeClosed
Detailed Description
Definition at line 59 of file G4WorkerRunManagerKernel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4WorkerRunManagerKernel.hh
Constructor & Destructor Documentation
G4WorkerRunManagerKernel::G4WorkerRunManagerKernel ()
Definition at line 30 of file G4WorkerRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 30 of file G4WorkerRunManagerKernel.cc
References FatalException, and G4Exception().
G4WorkerRunManagerKernel::~G4WorkerRunManagerKernel () virtual
Definition at line 42 of file G4WorkerRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 42 of file G4WorkerRunManagerKernel.cc
References G4ParticleTable::DestroyWorkerG4ParticleTable(), and G4ParticleTable::GetParticleTable().
Member Function Documentation
void G4WorkerRunManagerKernel::SetupShadowProcess () const protected virtual
Reimplemented from G4RunManagerKernel.
Definition at line 47 of file G4WorkerRunManagerKernel.cc.
View newest version in sPHENIX GitHub at line 47 of file G4WorkerRunManagerKernel.cc
References FatalException, G4cout, G4endl, G4Exception(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetMasterProcessManager(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), incremental_prev_tag::idx, Acts::UnitConstants::pm, G4ParticleTableIterator< K, V >::reset(), G4ProcessVector::size(), theParticleIterator, and G4ParticleTableIterator< K, V >::value().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4WorkerRunManagerKernel.hh
geant4/tree/geant4-10.6-release/source/run/src/G4WorkerRunManagerKernel.cc