ECCE @ EIC Software: G4TwistedTubs Class Reference
G4TwistedTubs Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistedTubs.hh>
Classes
class LastState
class LastValue
class LastValueWithDoubleVector
class LastVector
Public Member Functions
G4TwistedTubs (const G4String &pname, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4double dphi)
G4TwistedTubs (const G4String &pname, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4int nseg, G4double totphi)
G4TwistedTubs (const G4String &pname, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4double dphi)
G4TwistedTubs (const G4String &pname, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4int nseg, G4double totphi)
virtual ~G4TwistedTubs ()
void ComputeDimensions (G4VPVParameterisation *, const G4int, const G4VPhysicalVolume *)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcnorm=false, G4bool *validnorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4Polyhedron * CreatePolyhedron () const
G4Polyhedron * GetPolyhedron () const
std::ostream & StreamInfo (std::ostream &os) const
G4double GetDPhi () const
G4double GetPhiTwist () const
G4double GetInnerRadius () const
G4double GetOuterRadius () const
G4double GetInnerStereo () const
G4double GetOuterStereo () const
G4double GetZHalfLength () const
G4double GetKappa () const
G4double GetTanInnerStereo () const
G4double GetTanInnerStereo2 () const
G4double GetTanOuterStereo () const
G4double GetTanOuterStereo2 () const
G4double GetEndZ (G4int i) const
G4double GetEndPhi (G4int i) const
G4double GetEndInnerRadius (G4int i) const
G4double GetEndOuterRadius (G4int i) const
G4double GetEndInnerRadius () const
G4double GetEndOuterRadius () const
G4VisExtent GetExtent () const
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
G4ThreeVector GetPointOnSurface () const
G4TwistedTubs (__void__ &)
G4TwistedTubs (const G4TwistedTubs &rhs)
G4TwistedTubs & operator= (const G4TwistedTubs &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
void SetFields (G4double phitwist, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz)
void CreateSurfaces ()
Private Attributes
G4double fPhiTwist
G4double fInnerRadius
G4double fOuterRadius
G4double fEndZ [2]
G4double fDPhi
G4double fZHalfLength
G4double fInnerStereo
G4double fOuterStereo
G4double fTanInnerStereo
G4double fTanOuterStereo
G4double fKappa
G4double fEndInnerRadius [2]
G4double fEndOuterRadius [2]
G4double fEndPhi [2]
G4double fInnerRadius2
G4double fOuterRadius2
G4double fTanInnerStereo2
G4double fTanOuterStereo2
G4double fEndZ2 [2]
G4VTwistSurface * fLowerEndcap
G4VTwistSurface * fUpperEndcap
G4VTwistSurface * fLatterTwisted
G4VTwistSurface * fFormerTwisted
G4VTwistSurface * fInnerHype
G4VTwistSurface * fOuterHype
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
LastState fLastInside
LastVector fLastNormal
LastValue fLastDistanceToIn
LastValue fLastDistanceToOut
LastValueWithDoubleVector fLastDistanceToInWithV
LastValueWithDoubleVector fLastDistanceToOutWithV
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Detailed Description
Definition at line 54 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 54 of file G4TwistedTubs.hh
Constructor & Destructor Documentation
G4TwistedTubs::G4TwistedTubs (const G4String & pname, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4double dphi)
Definition at line 61 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 61 of file G4TwistedTubs.cc
References CreateSurfaces(), DBL_MIN, FatalErrorInArgument, G4Exception(), PHG4HcalDefs::innerrad, PHG4HcalDefs::outerrad, and SetFields().
Referenced by Clone().
G4TwistedTubs::G4TwistedTubs (const G4String & pname, G4double twistedangle, G4double endinnerrad, G4double endouterrad, G4double halfzlen, G4int nseg, G4double totphi)
Definition at line 92 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 92 of file G4TwistedTubs.cc
References CreateSurfaces(), DBL_MIN, FatalErrorInArgument, fDPhi, G4endl, G4Exception(), PHG4HcalDefs::innerrad, message(), PHG4HcalDefs::outerrad, and SetFields().
G4TwistedTubs::G4TwistedTubs (const G4String & pname, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4double dphi)
Definition at line 134 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 134 of file G4TwistedTubs.cc
References CreateSurfaces(), DBL_MIN, FatalErrorInArgument, G4Exception(), and SetFields().
G4TwistedTubs::G4TwistedTubs (const G4String & pname, G4double twistedangle, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz, G4int nseg, G4double totphi)
Definition at line 155 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 155 of file G4TwistedTubs.cc
References CreateSurfaces(), DBL_MIN, FatalErrorInArgument, fDPhi, G4endl, G4Exception(), message(), and SetFields().
G4TwistedTubs::~G4TwistedTubs () virtual
Definition at line 201 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 201 of file G4TwistedTubs.cc
References fFormerTwisted, fInnerHype, fLatterTwisted, fLowerEndcap, fOuterHype, fpPolyhedron, and fUpperEndcap.
G4TwistedTubs::G4TwistedTubs (__void__ & a)
Definition at line 189 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 189 of file G4TwistedTubs.cc
G4TwistedTubs::G4TwistedTubs (const G4TwistedTubs & rhs)
Definition at line 215 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 215 of file G4TwistedTubs.cc
References CreateSurfaces(), fEndInnerRadius, fEndOuterRadius, fEndPhi, fEndZ, and fEndZ2.
Member Function Documentation
void G4TwistedTubs::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 308 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 308 of file G4TwistedTubs.cc
References G4VSolid::DumpInfo(), fEndOuterRadius, fZHalfLength, G4Exception(), G4VSolid::GetName(), JustWarning, message(), pMax, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4TwistedTubs::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 335 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 335 of file G4TwistedTubs.cc
References BoundingLimits(), and G4BoundingEnvelope::CalculateExtent().
G4VSolid * G4TwistedTubs::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 1001 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 1001 of file G4TwistedTubs.cc
References G4TwistedTubs().
void G4TwistedTubs::ComputeDimensions (G4VPVParameterisation * , const G4int , const G4VPhysicalVolume *) virtual
Reimplemented from G4VSolid.
Definition at line 296 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 296 of file G4TwistedTubs.cc
References FatalException, and G4Exception().
G4Polyhedron * G4TwistedTubs::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 876 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 876 of file G4TwistedTubs.cc
References kdfinder::abs(), HepPolyhedron::createPolyhedron(), fDPhi, fFormerTwisted, fInnerHype, fLatterTwisted, fLowerEndcap, fOuterHype, fPhiTwist, fUpperEndcap, G4VTwistSurface::GetFacets(), HepPolyhedron::GetNumberOfRotationSteps(), k, max, n, and twopi.
Referenced by GetPolyhedron().
void G4TwistedTubs::CreateSurfaces () private
Definition at line 932 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 932 of file G4TwistedTubs.cc
References fDPhi, fEndInnerRadius, fEndOuterRadius, fEndPhi, fEndZ, fFormerTwisted, fInnerHype, fInnerRadius, fKappa, fLatterTwisted, fLowerEndcap, fOuterHype, fOuterRadius, fTanInnerStereo, fTanOuterStereo, fUpperEndcap, n, CLHEP::HepRotation::rotateZ(), and G4VTwistSurface::SetNeighbours().
Referenced by G4TwistedTubs(), and operator=().
void G4TwistedTubs::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 854 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 854 of file G4TwistedTubs.cc
References G4VGraphicsScene::AddSolid().
G4double G4TwistedTubs::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 460 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 460 of file G4TwistedTubs.cc
References G4VTwistSurface::DistanceToIn(), fFormerTwisted, fInnerHype, fLastDistanceToIn, fLastDistanceToInWithV, fLatterTwisted, fLowerEndcap, fOuterHype, fUpperEndcap, Inside(), kInfinity, kInside, kSurface, CLHEP::normal(), G4TwistedTubs::LastValueWithDoubleVector::p, CLHEP::Hep3Vector::set(), SurfaceNormal(), G4TwistedTubs::LastValue::value, G4TwistedTubs::LastValueWithDoubleVector::value, G4TwistedTubs::LastValueWithDoubleVector::vec, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4TwistedTubs::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 550 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 550 of file G4TwistedTubs.cc
References G4VTwistSurface::DistanceTo(), FatalException, fFormerTwisted, fInnerHype, fLastDistanceToIn, fLatterTwisted, fLowerEndcap, fOuterHype, fUpperEndcap, G4Exception(), Inside(), kInfinity, kInside, kOutside, kSurface, G4TwistedTubs::LastValue::p, CLHEP::Hep3Vector::set(), G4TwistedTubs::LastValue::value, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4TwistedTubs::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcnorm = false, G4bool * validnorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 629 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 629 of file G4TwistedTubs.cc
References G4VTwistSurface::DistanceToOut(), fFormerTwisted, fInnerHype, fLastDistanceToOutWithV, fLastNormal, fLatterTwisted, fLowerEndcap, fOuterHype, fUpperEndcap, G4VTwistSurface::GetNormal(), Inside(), G4VTwistSurface::IsValidNorm(), kInfinity, kOutside, kSurface, CLHEP::normal(), G4TwistedTubs::LastValueWithDoubleVector::p, CLHEP::Hep3Vector::set(), G4TwistedTubs::LastVector::surface, SurfaceNormal(), G4TwistedTubs::LastValueWithDoubleVector::value, G4TwistedTubs::LastValueWithDoubleVector::vec, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4TwistedTubs::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 740 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 740 of file G4TwistedTubs.cc
References G4VTwistSurface::DistanceTo(), FatalException, fFormerTwisted, fInnerHype, fLastDistanceToOut, fLatterTwisted, fLowerEndcap, fOuterHype, fUpperEndcap, G4Exception(), Inside(), kInfinity, kInside, kOutside, kSurface, G4TwistedTubs::LastValue::p, CLHEP::Hep3Vector::set(), G4TwistedTubs::LastValue::value, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4TwistedTubs::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 1009 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 1009 of file G4TwistedTubs.cc
References fCubicVolume, fDPhi, fInnerRadius, fOuterRadius, and fZHalfLength.
G4double G4TwistedTubs::GetDPhi () const inline
Definition at line 129 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 129 of file G4TwistedTubs.hh
References fDPhi.
Referenced by export_G4TwistedTubs(), G4tgbGeometryDumper::GetSolidParams(), PHG4GDMLWriteSolids::TwistedtubsWrite(), and G4GDMLWriteSolids::TwistedtubsWrite().
G4double G4TwistedTubs::GetEndInnerRadius (G4int i) const inline
Definition at line 145 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 145 of file G4TwistedTubs.hh
References fEndInnerRadius.
G4double G4TwistedTubs::GetEndInnerRadius () const inline
Definition at line 149 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 149 of file G4TwistedTubs.hh
References fEndInnerRadius.
Referenced by GetPointOnSurface().
G4double G4TwistedTubs::GetEndOuterRadius (G4int i) const inline
Definition at line 147 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 147 of file G4TwistedTubs.hh
References fEndOuterRadius.
G4double G4TwistedTubs::GetEndOuterRadius () const inline
Definition at line 152 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 152 of file G4TwistedTubs.hh
References fEndOuterRadius.
Referenced by GetPointOnSurface().
G4double G4TwistedTubs::GetEndPhi (G4int i) const inline
Definition at line 144 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 144 of file G4TwistedTubs.hh
References fEndPhi.
Referenced by export_G4TwistedTubs().
G4double G4TwistedTubs::GetEndZ (G4int i) const inline
Definition at line 143 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 143 of file G4TwistedTubs.hh
References fEndZ.
Referenced by export_G4TwistedTubs(), and G4GDMLWriteSolids::TwistedtubsWrite().
G4GeometryType G4TwistedTubs::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 993 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 993 of file G4TwistedTubs.cc
G4VisExtent G4TwistedTubs::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 862 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 862 of file G4TwistedTubs.cc
References fEndOuterRadius, and fZHalfLength.
G4double G4TwistedTubs::GetInnerRadius () const inline
Definition at line 131 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 131 of file G4TwistedTubs.hh
References fInnerRadius.
Referenced by export_G4TwistedTubs(), G4tgbGeometryDumper::GetSolidParams(), PHG4GDMLWriteSolids::TwistedtubsWrite(), and G4GDMLWriteSolids::TwistedtubsWrite().
G4double G4TwistedTubs::GetInnerStereo () const inline
Definition at line 133 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 133 of file G4TwistedTubs.hh
References fInnerStereo.
Referenced by export_G4TwistedTubs().
G4double G4TwistedTubs::GetKappa () const inline
Definition at line 136 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 136 of file G4TwistedTubs.hh
References fKappa.
Referenced by export_G4TwistedTubs().
G4double G4TwistedTubs::GetOuterRadius () const inline
Definition at line 132 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 132 of file G4TwistedTubs.hh
References fOuterRadius.
Referenced by export_G4TwistedTubs(), G4tgbGeometryDumper::GetSolidParams(), PHG4GDMLWriteSolids::TwistedtubsWrite(), and G4GDMLWriteSolids::TwistedtubsWrite().
G4double G4TwistedTubs::GetOuterStereo () const inline
Definition at line 134 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 134 of file G4TwistedTubs.hh
References fOuterStereo.
Referenced by export_G4TwistedTubs().
G4double G4TwistedTubs::GetPhiTwist () const inline
Definition at line 130 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 130 of file G4TwistedTubs.hh
References fPhiTwist.
Referenced by export_G4TwistedTubs(), G4tgbGeometryDumper::GetSolidParams(), PHG4GDMLWriteSolids::TwistedtubsWrite(), and G4GDMLWriteSolids::TwistedtubsWrite().
G4ThreeVector G4TwistedTubs::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 1030 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 1030 of file G4TwistedTubs.cc
References fEndZ, fFormerTwisted, fInnerHype, fLatterTwisted, fLowerEndcap, fOuterHype, fUpperEndcap, G4VTwistSurface::GetBoundaryMax(), G4VTwistSurface::GetBoundaryMin(), GetEndInnerRadius(), GetEndOuterRadius(), G4VTwistSurface::GetSurfaceArea(), phi, MATSCAN::phimin, r, rmax(), G4INCL::DeJongSpin::shoot(), sqr(), G4VTwistSurface::SurfacePoint(), x, xmax, xmin, and z.
G4Polyhedron * G4TwistedTubs::GetPolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 913 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 913 of file G4TwistedTubs.cc
References CreatePolyhedron(), fpPolyhedron, fRebuildPolyhedron, HepPolyhedron::GetNumberOfRotationSteps(), G4Polyhedron::GetNumberOfRotationStepsAtTimeOfCreation(), and G4TemplateAutoLock< _Mutex_t >::unlock().
G4double G4TwistedTubs::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 1020 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 1020 of file G4TwistedTubs.cc
References fSurfaceArea, and G4VSolid::GetSurfaceArea().
G4double G4TwistedTubs::GetTanInnerStereo () const inline
Definition at line 138 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 138 of file G4TwistedTubs.hh
References fTanInnerStereo.
Referenced by export_G4TwistedTubs().
G4double G4TwistedTubs::GetTanInnerStereo2 () const inline
Definition at line 139 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 139 of file G4TwistedTubs.hh
References fTanInnerStereo2.
Referenced by export_G4TwistedTubs().
G4double G4TwistedTubs::GetTanOuterStereo () const inline
Definition at line 140 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 140 of file G4TwistedTubs.hh
References fTanOuterStereo.
Referenced by export_G4TwistedTubs().
G4double G4TwistedTubs::GetTanOuterStereo2 () const inline
Definition at line 141 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 141 of file G4TwistedTubs.hh
References fTanOuterStereo2.
Referenced by export_G4TwistedTubs().
G4double G4TwistedTubs::GetZHalfLength () const inline
Definition at line 135 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 135 of file G4TwistedTubs.hh
References fZHalfLength.
Referenced by export_G4TwistedTubs(), G4tgbGeometryDumper::GetSolidParams(), and PHG4GDMLWriteSolids::TwistedtubsWrite().
EInside G4TwistedTubs::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 354 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 354 of file G4TwistedTubs.cc
References fInnerHype, fLastInside, fOuterHype, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetRadialTolerance(), CLHEP::Hep3Vector::getRho(), G4TwistedTubs::LastState::inside, kInside, kOutside, kSurface, G4TwistedTubs::LastState::p, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToIn(), and DistanceToOut().
G4TwistedTubs & G4TwistedTubs::operator= (const G4TwistedTubs & rhs)
Definition at line 248 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 248 of file G4TwistedTubs.cc
References CreateSurfaces(), fCubicVolume, fDPhi, fEndInnerRadius, fEndOuterRadius, fEndPhi, fEndZ, fEndZ2, fFormerTwisted, fInnerHype, fInnerRadius, fInnerRadius2, fInnerStereo, fKappa, fLastDistanceToIn, fLastDistanceToInWithV, fLastDistanceToOut, fLastDistanceToOutWithV, fLastInside, fLastNormal, fLatterTwisted, fLowerEndcap, fOuterHype, fOuterRadius, fOuterRadius2, fOuterStereo, fPhiTwist, fpPolyhedron, fRebuildPolyhedron, fSurfaceArea, fTanInnerStereo, fTanInnerStereo2, fTanOuterStereo, fTanOuterStereo2, fUpperEndcap, fZHalfLength, and G4VSolid::operator=().
void G4TwistedTubs::SetFields (G4double phitwist, G4double innerrad, G4double outerrad, G4double negativeEndz, G4double positiveEndz) inline private
Definition at line 343 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 343 of file G4TwistedTubs.hh
References fCubicVolume, fEndInnerRadius, fEndOuterRadius, fEndPhi, fEndZ, fEndZ2, fInnerRadius, fInnerRadius2, fInnerStereo, fKappa, fOuterRadius, fOuterRadius2, fOuterStereo, fPhiTwist, fTanInnerStereo, fTanInnerStereo2, fTanOuterStereo, fTanOuterStereo2, fZHalfLength, G4cout, G4endl, PHG4HcalDefs::innerrad, PHG4HcalDefs::outerrad, and parity().
Referenced by G4TwistedTubs().
std::ostream & G4TwistedTubs::StreamInfo (std::ostream & os) const virtual
Implements G4VSolid.
Definition at line 821 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 821 of file G4TwistedTubs.cc
References degree, fDPhi, fEndInnerRadius, fEndOuterRadius, fEndZ, fInnerRadius, fInnerStereo, fOuterRadius, fOuterStereo, fPhiTwist, G4VSolid::GetName(), and mm.
G4ThreeVector G4TwistedTubs::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 406 of file G4TwistedTubs.cc.
View newest version in sPHENIX GitHub at line 406 of file G4TwistedTubs.cc
References G4VTwistSurface::DistanceTo(), fFormerTwisted, fInnerHype, fLastNormal, fLatterTwisted, fLowerEndcap, fOuterHype, fUpperEndcap, G4VTwistSurface::GetNormal(), kInfinity, G4TwistedTubs::LastVector::p, CLHEP::Hep3Vector::set(), G4TwistedTubs::LastVector::surface, G4TwistedTubs::LastVector::vec, CLHEP::Hep3Vector::x(), xx, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToIn(), and DistanceToOut().
Member Data Documentation
G4double G4TwistedTubs::fCubicVolume = 0.0 private
Definition at line 223 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 223 of file G4TwistedTubs.hh
Referenced by GetCubicVolume(), operator=(), and SetFields().
G4double G4TwistedTubs::fDPhi private
Definition at line 198 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 198 of file G4TwistedTubs.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), G4TwistedTubs(), GetCubicVolume(), GetDPhi(), operator=(), and StreamInfo().
G4double G4TwistedTubs::fEndInnerRadius[2] private
Definition at line 206 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 206 of file G4TwistedTubs.hh
Referenced by CreateSurfaces(), G4TwistedTubs(), GetEndInnerRadius(), operator=(), SetFields(), and StreamInfo().
G4double G4TwistedTubs::fEndOuterRadius[2] private
Definition at line 207 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 207 of file G4TwistedTubs.hh
Referenced by BoundingLimits(), CreateSurfaces(), G4TwistedTubs(), GetEndOuterRadius(), GetExtent(), operator=(), SetFields(), and StreamInfo().
G4double G4TwistedTubs::fEndPhi[2] private
Definition at line 208 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 208 of file G4TwistedTubs.hh
Referenced by CreateSurfaces(), G4TwistedTubs(), GetEndPhi(), operator=(), and SetFields().
G4double G4TwistedTubs::fEndZ[2] private
Definition at line 197 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 197 of file G4TwistedTubs.hh
Referenced by CreateSurfaces(), G4TwistedTubs(), GetEndZ(), GetPointOnSurface(), operator=(), SetFields(), and StreamInfo().
G4double G4TwistedTubs::fEndZ2[2] private
Definition at line 214 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 214 of file G4TwistedTubs.hh
Referenced by G4TwistedTubs(), operator=(), and SetFields().
G4VTwistSurface* G4TwistedTubs::fFormerTwisted private
Definition at line 219 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 219 of file G4TwistedTubs.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4TwistedTubs().
G4VTwistSurface* G4TwistedTubs::fInnerHype private
Definition at line 220 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 220 of file G4TwistedTubs.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), SurfaceNormal(), and ~G4TwistedTubs().
G4double G4TwistedTubs::fInnerRadius private
Definition at line 195 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 195 of file G4TwistedTubs.hh
Referenced by CreateSurfaces(), GetCubicVolume(), GetInnerRadius(), operator=(), SetFields(), and StreamInfo().
G4double G4TwistedTubs::fInnerRadius2 private
Definition at line 210 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 210 of file G4TwistedTubs.hh
Referenced by operator=(), and SetFields().
G4double G4TwistedTubs::fInnerStereo private
Definition at line 201 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 201 of file G4TwistedTubs.hh
Referenced by GetInnerStereo(), operator=(), SetFields(), and StreamInfo().
G4double G4TwistedTubs::fKappa private
Definition at line 205 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 205 of file G4TwistedTubs.hh
Referenced by CreateSurfaces(), GetKappa(), operator=(), and SetFields().
LastValue G4TwistedTubs::fLastDistanceToIn private
Definition at line 329 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 329 of file G4TwistedTubs.hh
Referenced by DistanceToIn(), and operator=().
LastValueWithDoubleVector G4TwistedTubs::fLastDistanceToInWithV private
Definition at line 331 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 331 of file G4TwistedTubs.hh
Referenced by DistanceToIn(), and operator=().
LastValue G4TwistedTubs::fLastDistanceToOut private
Definition at line 330 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 330 of file G4TwistedTubs.hh
Referenced by DistanceToOut(), and operator=().
LastValueWithDoubleVector G4TwistedTubs::fLastDistanceToOutWithV private
Definition at line 332 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 332 of file G4TwistedTubs.hh
Referenced by DistanceToOut(), and operator=().
LastState G4TwistedTubs::fLastInside private
Definition at line 327 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 327 of file G4TwistedTubs.hh
Referenced by Inside(), and operator=().
LastVector G4TwistedTubs::fLastNormal private
Definition at line 328 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 328 of file G4TwistedTubs.hh
Referenced by DistanceToOut(), operator=(), and SurfaceNormal().
G4VTwistSurface* G4TwistedTubs::fLatterTwisted private
Definition at line 218 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 218 of file G4TwistedTubs.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4TwistedTubs().
G4VTwistSurface* G4TwistedTubs::fLowerEndcap private
Definition at line 216 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 216 of file G4TwistedTubs.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4TwistedTubs().
G4VTwistSurface* G4TwistedTubs::fOuterHype private
Definition at line 221 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 221 of file G4TwistedTubs.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), Inside(), operator=(), SurfaceNormal(), and ~G4TwistedTubs().
G4double G4TwistedTubs::fOuterRadius private
Definition at line 196 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 196 of file G4TwistedTubs.hh
Referenced by CreateSurfaces(), GetCubicVolume(), GetOuterRadius(), operator=(), SetFields(), and StreamInfo().
G4double G4TwistedTubs::fOuterRadius2 private
Definition at line 211 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 211 of file G4TwistedTubs.hh
Referenced by operator=(), and SetFields().
G4double G4TwistedTubs::fOuterStereo private
Definition at line 202 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 202 of file G4TwistedTubs.hh
Referenced by GetOuterStereo(), operator=(), SetFields(), and StreamInfo().
G4double G4TwistedTubs::fPhiTwist private
Definition at line 194 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 194 of file G4TwistedTubs.hh
Referenced by CreatePolyhedron(), GetPhiTwist(), operator=(), SetFields(), and StreamInfo().
G4Polyhedron* G4TwistedTubs::fpPolyhedron = nullptr mutable private
Definition at line 227 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 227 of file G4TwistedTubs.hh
Referenced by GetPolyhedron(), operator=(), and ~G4TwistedTubs().
G4bool G4TwistedTubs::fRebuildPolyhedron = false mutable private
Definition at line 226 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 226 of file G4TwistedTubs.hh
Referenced by GetPolyhedron(), and operator=().
G4double G4TwistedTubs::fSurfaceArea = 0.0 private
Definition at line 224 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 224 of file G4TwistedTubs.hh
Referenced by GetSurfaceArea(), and operator=().
G4double G4TwistedTubs::fTanInnerStereo private
Definition at line 203 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 203 of file G4TwistedTubs.hh
Referenced by CreateSurfaces(), GetTanInnerStereo(), operator=(), and SetFields().
G4double G4TwistedTubs::fTanInnerStereo2 private
Definition at line 212 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 212 of file G4TwistedTubs.hh
Referenced by GetTanInnerStereo2(), operator=(), and SetFields().
G4double G4TwistedTubs::fTanOuterStereo private
Definition at line 204 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 204 of file G4TwistedTubs.hh
Referenced by CreateSurfaces(), GetTanOuterStereo(), operator=(), and SetFields().
G4double G4TwistedTubs::fTanOuterStereo2 private
Definition at line 213 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 213 of file G4TwistedTubs.hh
Referenced by GetTanOuterStereo2(), operator=(), and SetFields().
G4VTwistSurface* G4TwistedTubs::fUpperEndcap private
Definition at line 217 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 217 of file G4TwistedTubs.hh
Referenced by CreatePolyhedron(), CreateSurfaces(), DistanceToIn(), DistanceToOut(), GetPointOnSurface(), operator=(), SurfaceNormal(), and ~G4TwistedTubs().
G4double G4TwistedTubs::fZHalfLength private
Definition at line 199 of file G4TwistedTubs.hh.
View newest version in sPHENIX GitHub at line 199 of file G4TwistedTubs.hh
Referenced by BoundingLimits(), GetCubicVolume(), GetExtent(), GetZHalfLength(), operator=(), and SetFields().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4TwistedTubs.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4TwistedTubs.cc