ECCE @ EIC Software: ExP01ChamberParameterisation Class Reference
ExP01ChamberParameterisation Class Reference
Chamber parameterisation for the persistency example.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/include/ExP01ChamberParameterisation.hh>
Public Member Functions
ExP01ChamberParameterisation (G4int NoChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
~ExP01ChamberParameterisation ()
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Box &trackerLayer, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4int fNoChambers
G4double fStartZ
G4double fHalfWidth
G4double fSpacing
G4double fHalfLengthFirst
G4double fHalfLengthIncr
Detailed Description
Chamber parameterisation for the persistency example.
Definition at line 66 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 66 of file ExP01ChamberParameterisation.hh
Constructor & Destructor Documentation
ExP01ChamberParameterisation::ExP01ChamberParameterisation (G4int NoChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
Definition at line 42 of file ExP01ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 42 of file ExP01ChamberParameterisation.cc
References FatalException, fHalfLengthFirst, fHalfLengthIncr, fHalfWidth, fNoChambers, fSpacing, fStartZ, and G4Exception().
ExP01ChamberParameterisation::~ExP01ChamberParameterisation ()
Definition at line 73 of file ExP01ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 73 of file ExP01ChamberParameterisation.cc
Member Function Documentation
void ExP01ChamberParameterisation::ComputeDimensions (G4Box & trackerLayer, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 90 of file ExP01ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 90 of file ExP01ChamberParameterisation.cc
References G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), and G4Box::SetZHalfLength().
void ExP01ChamberParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 87 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 87 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 88 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 88 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 89 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 90 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 90 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 91 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 92 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 92 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 93 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 93 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 94 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 94 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 95 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 95 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 96 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 96 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 97 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 97 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 98 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 98 of file ExP01ChamberParameterisation.hh
void ExP01ChamberParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Definition at line 79 of file ExP01ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 79 of file ExP01ChamberParameterisation.cc
References Acts::Test::origin(), G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
Member Data Documentation
G4double ExP01ChamberParameterisation::fHalfLengthFirst private
Definition at line 106 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 106 of file ExP01ChamberParameterisation.hh
Referenced by ExP01ChamberParameterisation().
G4double ExP01ChamberParameterisation::fHalfLengthIncr private
Definition at line 107 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 107 of file ExP01ChamberParameterisation.hh
Referenced by ExP01ChamberParameterisation().
G4double ExP01ChamberParameterisation::fHalfWidth private
Definition at line 104 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 104 of file ExP01ChamberParameterisation.hh
Referenced by ExP01ChamberParameterisation().
G4int ExP01ChamberParameterisation::fNoChambers private
Definition at line 102 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 102 of file ExP01ChamberParameterisation.hh
Referenced by ExP01ChamberParameterisation().
G4double ExP01ChamberParameterisation::fSpacing private
Definition at line 105 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 105 of file ExP01ChamberParameterisation.hh
Referenced by ExP01ChamberParameterisation().
G4double ExP01ChamberParameterisation::fStartZ private
Definition at line 103 of file ExP01ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 103 of file ExP01ChamberParameterisation.hh
Referenced by ExP01ChamberParameterisation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/include/ExP01ChamberParameterisation.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/P01/src/ExP01ChamberParameterisation.cc