ECCE @ EIC Software: CLHEP::HepRandomEngine Class Reference
CLHEP::HepRandomEngine Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandomEngine.h>
Public Member Functions
HepRandomEngine ()
virtual ~HepRandomEngine ()
bool operator== (const HepRandomEngine &engine)
bool operator!= (const HepRandomEngine &engine)
virtual double flat ()=0
virtual void flatArray (const int size, double *vect)=0
virtual void setSeed (long seed, int)=0
virtual void setSeeds (const long *seeds, int)=0
virtual void saveStatus (const char filename[]="Config.conf") const =0
virtual void restoreStatus (const char filename[]="Config.conf")=0
virtual void showStatus () const =0
virtual std::string name () const =0
virtual std::ostream & put (std::ostream &os) const
virtual std::istream & get (std::istream &is)
virtual std::istream & getState (std::istream &is)
virtual std::vector< unsigned
long > put () const
virtual bool get (const std::vector< unsigned long > &v)
virtual bool getState (const std::vector< unsigned long > &v)
long getSeed () const
const long * getSeeds () const
virtual operator double ()
virtual operator float ()
virtual operator unsigned int ()
Static Public Member Functions
static std::string beginTag ()
static HepRandomEngine * newEngine (std::istream &is)
static HepRandomEngine * newEngine (const std::vector< unsigned long > &v)
Static Protected Member Functions
static double exponent_bit_32 ()
static double mantissa_bit_12 ()
static double mantissa_bit_24 ()
static double mantissa_bit_32 ()
static double twoToMinus_32 ()
static double twoToMinus_48 ()
static double twoToMinus_49 ()
static double twoToMinus_53 ()
static double nearlyTwoToMinus_54 ()
static bool checkFile (std::istream &file, const std::string &filename, const std::string &classname, const std::string &methodname)
Protected Attributes
long theSeed
const long * theSeeds
Detailed Description
Author
Gabri.nosp@m.ele..nosp@m.Cosmo.nosp@m.@cer.nosp@m.n.ch
Definition at line 53 of file RandomEngine.h.
View newest version in sPHENIX GitHub at line 53 of file RandomEngine.h
Constructor & Destructor Documentation
CLHEP::HepRandomEngine::HepRandomEngine ()
Definition at line 24 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 24 of file RandomEngine.cc
CLHEP::HepRandomEngine::~HepRandomEngine () virtual
Definition at line 29 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 29 of file RandomEngine.cc
Member Function Documentation
std::string CLHEP::HepRandomEngine::beginTag () static
Definition at line 65 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 65 of file RandomEngine.cc
bool CLHEP::HepRandomEngine::checkFile (std::istream & file, const std::string & filename, const std::string & classname, const std::string & methodname) static protected
Definition at line 44 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 44 of file RandomEngine.cc
Referenced by CLHEP::MTwistEngine::restoreStatus(), CLHEP::HepJamesRandom::restoreStatus(), CLHEP::Ranlux64Engine::restoreStatus(), CLHEP::RanshiEngine::restoreStatus(), CLHEP::RanecuEngine::restoreStatus(), CLHEP::DualRand::restoreStatus(), and CLHEP::RanluxEngine::restoreStatus().
static double CLHEP::HepRandomEngine::exponent_bit_32 () inline static protected
virtual double CLHEP::HepRandomEngine::flat () pure virtual
Implemented in CLHEP::RanluxEngine, CLHEP::MixMaxRng, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::Ranlux64Engine, CLHEP::NonRandomEngine, CLHEP::RanecuEngine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
Referenced by G4UniversalFluctuation::AddExcitation(), G4FermiPhaseSpaceDecay::BetaKopylov(), G4FPYSamplingOps::G4SampleUniform(), CLHEP::RandBinomial::genBinomial(), CLHEP::RandChiSquare::genChiSquare(), CLHEP::RandGamma::genGamma(), CLHEP::normal(), CLHEP::RandPoissonQ::poissonDeviateSmall(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4ModifiedTsai::SampleCosTheta(), G4FermiBreakUpVI::SampleDecay(), G4UrbanMscModel::SampleDisplacement(), G4UrbanAdjointMscModel::SampleDisplacement(), G4UrbanMscModel::SampleDisplacementNew(), G4UrbanAdjointMscModel::SampleDisplacementNew(), G4VEmissionProbability::SampleEnergy(), G4SBBremTable::SampleEnergyTransfer(), G4IonFluctuations::SampleFluctuations(), G4UniversalFluctuation::SampleGauss(), G4PreCompoundFragment::SampleKineticEnergy(), G4EvaporationProbability::SampleKineticEnergy(), G4WentzelVIModel::SampleScattering(), G4UrbanMscModel::SampleScattering(), G4UrbanAdjointMscModel::SampleScattering(), G4BoldyshevTripletModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4WentzelOKandVIxSection::SampleSingleScattering(), CLHEP::RandBreitWigner::shoot(), CLHEP::RandGauss::shoot(), CLHEP::RandFlat::shoot(), CLHEP::RandPoisson::shoot(), CLHEP::RandStudentT::shoot(), G4UrbanMscModel::SimpleScattering(), G4UrbanAdjointMscModel::SimpleScattering(), CLHEP::RandGaussZiggurat::ziggurat_UNI(), and CLHEP::RandExpZiggurat::ziggurat_UNI().
virtual void CLHEP::HepRandomEngine::flatArray (const int size, double * vect) pure virtual
Implemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::Ranlux64Engine, CLHEP::NonRandomEngine, CLHEP::RanecuEngine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
Referenced by G4MTRunManager::InitializeEventLoop(), G4MTRunManager::RefillSeeds(), G4SBBremTable::SampleEnergyTransfer(), G4SeltzerBergerModel::SampleEnergyTransfer(), G4UniversalFluctuation::SampleFluctuations(), G4BetheHeitler5DModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), and CLHEP::RandFlat::shootArray().
std::istream & CLHEP::HepRandomEngine::get (std::istream & is) virtual
Reimplemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, CLHEP::Ranlux64Engine, CLHEP::MTwistEngine, and CLHEP::NonRandomEngine.
Definition at line 60 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 60 of file RandomEngine.cc
Referenced by CLHEP::HepRandom::engine(), CLHEP::HepRandom::getTheEngine(), and CLHEP::operator>>().
bool CLHEP::HepRandomEngine::get (const std::vector< unsigned long > & v) virtual
Reimplemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, CLHEP::Ranlux64Engine, CLHEP::MTwistEngine, and CLHEP::NonRandomEngine.
Definition at line 79 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 79 of file RandomEngine.cc
long CLHEP::HepRandomEngine::getSeed () const inline
Definition at line 112 of file RandomEngine.h.
View newest version in sPHENIX GitHub at line 112 of file RandomEngine.h
References theSeed.
const long* CLHEP::HepRandomEngine::getSeeds () const inline
Definition at line 115 of file RandomEngine.h.
View newest version in sPHENIX GitHub at line 115 of file RandomEngine.h
References theSeeds.
std::istream & CLHEP::HepRandomEngine::getState (std::istream & is) virtual
Reimplemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, CLHEP::Ranlux64Engine, CLHEP::MTwistEngine, and CLHEP::NonRandomEngine.
Definition at line 69 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 69 of file RandomEngine.cc
Referenced by CLHEP::makeAnEngine().
bool CLHEP::HepRandomEngine::getState (const std::vector< unsigned long > & v) virtual
Reimplemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, CLHEP::Ranlux64Engine, CLHEP::MTwistEngine, and CLHEP::NonRandomEngine.
Definition at line 83 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 83 of file RandomEngine.cc
static double CLHEP::HepRandomEngine::mantissa_bit_12 () inline static protected
Referenced by CLHEP::RanluxEngine::flat(), and CLHEP::RanluxEngine::flatArray().
static double CLHEP::HepRandomEngine::mantissa_bit_24 () inline static protected
Referenced by CLHEP::RanluxEngine::flat(), CLHEP::RanluxEngine::flatArray(), CLHEP::RanluxEngine::getState(), CLHEP::RanluxEngine::put(), CLHEP::RanluxEngine::setSeed(), and CLHEP::RanluxEngine::setSeeds().
static double CLHEP::HepRandomEngine::mantissa_bit_32 () inline static protected
virtual std::string CLHEP::HepRandomEngine::name () const pure virtual
Implemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, CLHEP::Ranlux64Engine, CLHEP::MTwistEngine, and CLHEP::NonRandomEngine.
Referenced by CLHEP::StaticRandomStates::restore().
static double CLHEP::HepRandomEngine::nearlyTwoToMinus_54 () inline static protected
Referenced by CLHEP::MTwistEngine::flat(), CLHEP::RanshiEngine::flat(), and CLHEP::DualRand::flat().
HepRandomEngine * CLHEP::HepRandomEngine::newEngine (std::istream & is) static
Definition at line 88 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 88 of file RandomEngine.cc
References CLHEP::EngineFactory::newEngine().
Referenced by CLHEP::StaticRandomStates::restore().
HepRandomEngine * CLHEP::HepRandomEngine::newEngine (const std::vector< unsigned long > & v) static
Definition at line 93 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 93 of file RandomEngine.cc
References CLHEP::EngineFactory::newEngine().
CLHEP::HepRandomEngine::operator double () virtual
Reimplemented in CLHEP::RanluxEngine, CLHEP::MixMaxRng, CLHEP::DualRand, CLHEP::RanecuEngine, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
Definition at line 31 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 31 of file RandomEngine.cc
References G4AblaRandom::flat().
CLHEP::HepRandomEngine::operator float () virtual
Reimplemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
Definition at line 35 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 35 of file RandomEngine.cc
References G4AblaRandom::flat().
CLHEP::HepRandomEngine::operator unsigned int () virtual
Reimplemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
Definition at line 39 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 39 of file RandomEngine.cc
References G4AblaRandom::flat().
bool CLHEP::HepRandomEngine::operator!= (const HepRandomEngine & engine) inline
bool CLHEP::HepRandomEngine::operator== (const HepRandomEngine & engine) inline
std::ostream & CLHEP::HepRandomEngine::put (std::ostream & os) const virtual
Reimplemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, CLHEP::Ranlux64Engine, CLHEP::MTwistEngine, and CLHEP::NonRandomEngine.
Definition at line 56 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 56 of file RandomEngine.cc
Referenced by CLHEP::operator<<().
std::vector< unsigned long > CLHEP::HepRandomEngine::put () const virtual
Reimplemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::RanecuEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::HepJamesRandom, CLHEP::Ranlux64Engine, CLHEP::MTwistEngine, and CLHEP::NonRandomEngine.
Definition at line 74 of file RandomEngine.cc.
View newest version in sPHENIX GitHub at line 74 of file RandomEngine.cc
References v.
virtual void CLHEP::HepRandomEngine::restoreStatus (const char filename[] = "Config.conf") pure virtual
Implemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::DualRand, CLHEP::RanecuEngine, CLHEP::RanshiEngine, CLHEP::Ranlux64Engine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
Referenced by CLHEP::RandGauss::restoreEngineStatus(), CLHEP::RandFlat::restoreEngineStatus(), and HepMCFlowAfterBurner::RestoreRandomState().
virtual void CLHEP::HepRandomEngine::saveStatus (const char filename[] = "Config.conf") const pure virtual
Implemented in CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::DualRand, CLHEP::RanecuEngine, CLHEP::RanshiEngine, CLHEP::Ranlux64Engine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
Referenced by CLHEP::RandGauss::saveEngineStatus(), CLHEP::RandFlat::saveEngineStatus(), and HepMCFlowAfterBurner::SaveRandomState().
virtual void CLHEP::HepRandomEngine::setSeed (long seed, int) pure virtual
Implemented in CLHEP::NonRandomEngine, CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::DualRand, CLHEP::RanshiEngine, CLHEP::RanecuEngine, CLHEP::Ranlux64Engine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
Referenced by FW::Geant4::MMPrimaryGeneratorAction::MMPrimaryGeneratorAction().
virtual void CLHEP::HepRandomEngine::setSeeds (const long * seeds, int) pure virtual
Implemented in CLHEP::NonRandomEngine, CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::DualRand, CLHEP::RanecuEngine, CLHEP::RanshiEngine, CLHEP::Ranlux64Engine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
virtual void CLHEP::HepRandomEngine::showStatus () const pure virtual
Implemented in CLHEP::NonRandomEngine, CLHEP::MixMaxRng, CLHEP::RanluxEngine, CLHEP::DualRand, CLHEP::RanecuEngine, CLHEP::RanshiEngine, CLHEP::Ranlux64Engine, CLHEP::HepJamesRandom, and CLHEP::MTwistEngine.
static double CLHEP::HepRandomEngine::twoToMinus_32 () inline static protected
Referenced by CLHEP::MTwistEngine::flat(), CLHEP::RanshiEngine::flat(), CLHEP::DualRand::flat(), CLHEP::Ranlux64Engine::setSeed(), and CLHEP::Ranlux64Engine::setSeeds().
static double CLHEP::HepRandomEngine::twoToMinus_48 () inline static protected
Referenced by CLHEP::Ranlux64Engine::advance(), CLHEP::Ranlux64Engine::setSeed(), CLHEP::Ranlux64Engine::setSeeds(), and CLHEP::Ranlux64Engine::update().
static double CLHEP::HepRandomEngine::twoToMinus_49 () inline static protected
Referenced by CLHEP::Ranlux64Engine::flat().
static double CLHEP::HepRandomEngine::twoToMinus_53 () inline static protected
Referenced by CLHEP::MTwistEngine::flat(), CLHEP::RanshiEngine::flat(), and CLHEP::DualRand::flat().
Member Data Documentation
long CLHEP::HepRandomEngine::theSeed protected
Definition at line 142 of file RandomEngine.h.
View newest version in sPHENIX GitHub at line 142 of file RandomEngine.h
Referenced by CLHEP::DualRand::DualRand(), getSeed(), CLHEP::MTwistEngine::getState(), CLHEP::Ranlux64Engine::getState(), CLHEP::HepJamesRandom::getState(), CLHEP::RanshiEngine::getState(), CLHEP::DualRand::getState(), CLHEP::RanecuEngine::getState(), CLHEP::RanluxEngine::getState(), CLHEP::MixMaxRng::getState(), CLHEP::HepJamesRandom::HepJamesRandom(), CLHEP::MixMaxRng::MixMaxRng(), CLHEP::MTwistEngine::put(), CLHEP::MixMaxRng::put(), CLHEP::RanecuEngine::put(), CLHEP::RanecuEngine::RanecuEngine(), CLHEP::RanluxEngine::RanluxEngine(), CLHEP::RanshiEngine::RanshiEngine(), CLHEP::MTwistEngine::restoreStatus(), CLHEP::HepJamesRandom::restoreStatus(), CLHEP::Ranlux64Engine::restoreStatus(), CLHEP::RanshiEngine::restoreStatus(), CLHEP::RanecuEngine::restoreStatus(), CLHEP::DualRand::restoreStatus(), CLHEP::RanluxEngine::restoreStatus(), CLHEP::MTwistEngine::saveStatus(), CLHEP::RanecuEngine::setIndex(), CLHEP::MTwistEngine::setSeed(), CLHEP::HepJamesRandom::setSeed(), CLHEP::Ranlux64Engine::setSeed(), CLHEP::RanecuEngine::setSeed(), CLHEP::DualRand::setSeed(), CLHEP::MixMaxRng::setSeed(), CLHEP::RanluxEngine::setSeed(), CLHEP::Ranlux64Engine::setSeeds(), CLHEP::RanshiEngine::setSeeds(), CLHEP::RanecuEngine::setSeeds(), CLHEP::RanluxEngine::setSeeds(), CLHEP::MixMaxRng::setSeeds(), CLHEP::MTwistEngine::showStatus(), CLHEP::HepJamesRandom::showStatus(), CLHEP::Ranlux64Engine::showStatus(), CLHEP::RanshiEngine::showStatus(), CLHEP::DualRand::showStatus(), CLHEP::RanecuEngine::showStatus(), and CLHEP::RanluxEngine::showStatus().
const long* CLHEP::HepRandomEngine::theSeeds protected
Definition at line 143 of file RandomEngine.h.
View newest version in sPHENIX GitHub at line 143 of file RandomEngine.h
Referenced by getSeeds(), CLHEP::RanecuEngine::RanecuEngine(), CLHEP::RanecuEngine::setIndex(), CLHEP::RanecuEngine::setSeed(), CLHEP::MTwistEngine::setSeeds(), CLHEP::HepJamesRandom::setSeeds(), CLHEP::Ranlux64Engine::setSeeds(), CLHEP::RanecuEngine::setSeeds(), CLHEP::RanshiEngine::setSeeds(), CLHEP::DualRand::setSeeds(), CLHEP::RanluxEngine::setSeeds(), and CLHEP::MixMaxRng::setSeeds().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandomEngine.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandomEngine.cc