ECCE @ EIC Software: G4UCNMultiScattering Class Reference
G4UCNMultiScattering Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/include/G4UCNMultiScattering.hh>
Public Member Functions
G4UCNMultiScattering (const G4String &processName="UCNMultiScattering", G4ProcessType type=fUCN)
virtual ~G4UCNMultiScattering ()
G4bool IsApplicable (const G4ParticleDefinition &aParticleType)
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *condition)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep)
G4ThreeVector Scatter ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4UCNMultiScattering (const G4UCNMultiScattering &right)
G4UCNMultiScattering & operator= (const G4UCNMultiScattering &right)
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 65 of file G4UCNMultiScattering.hh.
View newest version in sPHENIX GitHub at line 65 of file G4UCNMultiScattering.hh
Constructor & Destructor Documentation
G4UCNMultiScattering::G4UCNMultiScattering (const G4String & processName = "UCNMultiScattering", G4ProcessType type = fUCN)
Definition at line 68 of file G4UCNMultiScattering.cc.
View newest version in sPHENIX GitHub at line 68 of file G4UCNMultiScattering.cc
References fUCNMultiScattering, G4cout, G4endl, G4VProcess::GetProcessName(), G4VProcess::SetProcessSubType(), and G4VProcess::verboseLevel.
G4UCNMultiScattering::~G4UCNMultiScattering () virtual
Definition at line 85 of file G4UCNMultiScattering.cc.
View newest version in sPHENIX GitHub at line 85 of file G4UCNMultiScattering.cc
G4UCNMultiScattering::G4UCNMultiScattering (const G4UCNMultiScattering & right) private
Member Function Documentation
G4double G4UCNMultiScattering::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition * condition) virtual
Implements G4VDiscreteProcess.
Definition at line 117 of file G4UCNMultiScattering.cc.
View newest version in sPHENIX GitHub at line 117 of file G4UCNMultiScattering.cc
References barn, DBL_MAX, G4MaterialPropertiesTable::GetConstProperty(), G4Track::GetMaterial(), G4Material::GetMaterialPropertiesTable(), and G4Material::GetTotNbOfAtomsPerVolume().
G4bool G4UCNMultiScattering::IsApplicable (const G4ParticleDefinition & aParticleType) inline virtual
Reimplemented from G4VProcess.
Definition at line 115 of file G4UCNMultiScattering.hh.
View newest version in sPHENIX GitHub at line 115 of file G4UCNMultiScattering.hh
References G4Neutron::NeutronDefinition().
G4UCNMultiScattering& G4UCNMultiScattering::operator= (const G4UCNMultiScattering & right) private
G4VParticleChange * G4UCNMultiScattering::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 95 of file G4UCNMultiScattering.cc.
View newest version in sPHENIX GitHub at line 95 of file G4UCNMultiScattering.cc
References G4VProcess::aParticleChange, cm, G4cout, G4endl, G4Track::GetGlobalTime(), G4VPhysicalVolume::GetName(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPostStepPoint(), G4Track::GetProperTime(), G4Track::GetTrackLength(), G4ParticleChange::Initialize(), G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeMomentumDirection(), Scatter(), and G4VProcess::verboseLevel.
G4ThreeVector G4UCNMultiScattering::Scatter ()
Definition at line 150 of file G4UCNMultiScattering.cc.
View newest version in sPHENIX GitHub at line 150 of file G4UCNMultiScattering.cc
References G4UniformRand, phi, pi, and theta().
Referenced by PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/include/G4UCNMultiScattering.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/src/G4UCNMultiScattering.cc