ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_outputChannel.cc File Reference
MCGIDI_outputChannel.cc File Reference
#include <string.h>
#include <cmath>
#include "MCGIDI.h"
#include "MCGIDI_misc.h"
Functions
MCGIDI_outputChannel * MCGIDI_outputChannel_new (statusMessageReporting *smr)
int MCGIDI_outputChannel_initialize (statusMessageReporting *, MCGIDI_outputChannel *outputChannel)
MCGIDI_outputChannel * MCGIDI_outputChannel_free (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
int MCGIDI_outputChannel_release (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
int MCGIDI_outputChannel_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_POPs *pops, MCGIDI_outputChannel *outputChannel, MCGIDI_reaction *reaction, MCGIDI_product *parent)
int MCGIDI_outputChannel_numberOfProducts (MCGIDI_outputChannel *outputChannel)
MCGIDI_product * MCGIDI_outputChannel_getProductAtIndex (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, int i)
int MCGIDI_outputChannel_getDomain (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, double *EMin, double *EMax)
MCGIDI_target_heated * MCGIDI_outputChannel_getTargetHeated (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
double MCGIDI_outputChannel_getProjectileMass_MeV (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
double MCGIDI_outputChannel_getTargetMass_MeV (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel)
double MCGIDI_outputChannel_getQ_MeV (statusMessageReporting *, MCGIDI_outputChannel *outputChannel, double)
double MCGIDI_outputChannel_getFinalQ (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, double e_in)
int MCGIDI_outputChannel_sampleProductsAtE (statusMessageReporting *smr, MCGIDI_outputChannel *outputChannel, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo, MCGIDI_sampledProductsDatas *productDatas, double *masses_)
Function Documentation
MCGIDI_outputChannel* MCGIDI_outputChannel_free (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 39 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 39 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_release(), and smr_freeMemory().
Referenced by MCGIDI_outputChannel_new().
int MCGIDI_outputChannel_getDomain (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, double * EMin, double * EMax)
Definition at line 153 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 153 of file MCGIDI_outputChannel.cc
References MCGIDI_product_getDomain(), MCGIDI_reaction_getDomain(), MCGIDI_outputChannel_s::parent, and MCGIDI_outputChannel_s::reaction.
Referenced by MCGIDI_product_getDomain().
double MCGIDI_outputChannel_getFinalQ (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, double e_in)
Definition at line 192 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 192 of file MCGIDI_outputChannel.cc
References MCGIDI_product_s::decayChannel, MCGIDI_outputChannel_s::genre, MCGIDI_channelGenre_undefined_e, MCGIDI_outputChannel_getFinalQ(), MCGIDI_outputChannel_s::numberOfProducts, MCGIDI_outputChannel_s::products, Q, MCGIDI_outputChannel_s::Q, and smr_isOk().
Referenced by MCGIDI_outputChannel_getFinalQ().
MCGIDI_product* MCGIDI_outputChannel_getProductAtIndex (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, int i)
Definition at line 142 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 142 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_s::numberOfProducts, MCGIDI_outputChannel_s::products, smr_setReportError2, and smr_unknownID.
Referenced by G4GIDI_target::getElasticFinalState(), and MCGIDI_reaction_ParseDetermineReactionProducts().
double MCGIDI_outputChannel_getProjectileMass_MeV (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 169 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 169 of file MCGIDI_outputChannel.cc
References MCGIDI_product_getProjectileMass_MeV(), MCGIDI_reaction_getProjectileMass_MeV(), MCGIDI_outputChannel_s::parent, and MCGIDI_outputChannel_s::reaction.
Referenced by MCGIDI_product_getProjectileMass_MeV().
double MCGIDI_outputChannel_getQ_MeV (statusMessageReporting * , MCGIDI_outputChannel * outputChannel, double)
Definition at line 185 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 185 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_s::Q.
Referenced by MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), and MCGIDI_reaction_ParseDetermineReactionProducts().
MCGIDI_target_heated* MCGIDI_outputChannel_getTargetHeated (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 161 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 161 of file MCGIDI_outputChannel.cc
References MCGIDI_product_getTargetHeated(), MCGIDI_reaction_getTargetHeated(), MCGIDI_outputChannel_s::parent, and MCGIDI_outputChannel_s::reaction.
Referenced by MCGIDI_product_getTargetHeated().
double MCGIDI_outputChannel_getTargetMass_MeV (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 177 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 177 of file MCGIDI_outputChannel.cc
References MCGIDI_product_getTargetMass_MeV(), MCGIDI_reaction_getTargetMass_MeV(), MCGIDI_outputChannel_s::parent, and MCGIDI_outputChannel_s::reaction.
Referenced by MCGIDI_product_getTargetMass_MeV().
int MCGIDI_outputChannel_initialize (statusMessageReporting * , MCGIDI_outputChannel * outputChannel)
Definition at line 31 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_outputChannel.cc
Referenced by MCGIDI_outputChannel_new(), MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_outputChannel_release().
MCGIDI_outputChannel* MCGIDI_outputChannel_new (statusMessageReporting * smr)
Definition at line 20 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 20 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_free(), MCGIDI_outputChannel_initialize(), and smr_malloc2.
int MCGIDI_outputChannel_numberOfProducts (MCGIDI_outputChannel * outputChannel)
Definition at line 135 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 135 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_s::numberOfProducts.
Referenced by MCGIDI_reaction_ParseDetermineReactionProducts().
int MCGIDI_outputChannel_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_POPs * pops, MCGIDI_outputChannel * outputChannel, MCGIDI_reaction * reaction, MCGIDI_product * parent)
Definition at line 61 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 61 of file MCGIDI_outputChannel.cc
References MCGIDI_POP_s::A, MCGIDI_reaction_s::ENDF_MT, check_license::err(), MCGIDI_outputChannel_s::genre, MCGIDI_AMU2MeV, MCGIDI_channelGenre_sumOfRemaining_e, MCGIDI_channelGenre_twoBody_e, MCGIDI_channelGenre_uncorrelated_e, MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_outputChannel_initialize(), MCGIDI_outputChannel_release(), MCGIDI_product_getMass_MeV(), MCGIDI_product_parseFromTOM(), MCGIDI_product_setTwoBodyMasses(), MCGIDI_reaction_getProjectileMass_MeV(), MCGIDI_reaction_getTargetMass_MeV(), n, xDataTOM_element_s::name, MCGIDI_outputChannel_s::numberOfProducts, MCGIDI_outputChannel_s::parent, MCGIDI_product_s::pop, printf(), MCGIDI_outputChannel_s::products, Q, MCGIDI_outputChannel_s::Q, MCGIDI_outputChannel_s::QIsFloat, MCGIDI_outputChannel_s::reaction, smr_malloc2, smr_setReportError2, smr_setReportError2p, smr_unknownID, xDataTOM_getAttributesValueInElement(), xDataTOM_numberOfElementsByName(), xDataTOME_getFirstElement(), xDataTOME_getNextElement(), and MCGIDI_POP_s::Z.
Referenced by MCGIDI_product_parseFromTOM(), and MCGIDI_reaction_parseFromTOM().
int MCGIDI_outputChannel_release (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel)
Definition at line 48 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 48 of file MCGIDI_outputChannel.cc
References MCGIDI_outputChannel_initialize(), MCGIDI_product_release(), MCGIDI_outputChannel_s::numberOfProducts, MCGIDI_outputChannel_s::products, and smr_freeMemory().
Referenced by MCGIDI_outputChannel_free(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_product_release(), and MCGIDI_reaction_release().
int MCGIDI_outputChannel_sampleProductsAtE (statusMessageReporting * smr, MCGIDI_outputChannel * outputChannel, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo, MCGIDI_sampledProductsDatas * productDatas, double * masses_)
Definition at line 208 of file MCGIDI_outputChannel.cc.
View newest version in sPHENIX GitHub at line 208 of file MCGIDI_outputChannel.cc
References MCGIDI_distribution_s::angular, MCGIDI_distribution_s::angularEnergy, MCGIDI_sampledProductsData_s::birthTimeSec, MCGIDI_product_s::decayChannel, MCGIDI_sampledProductsData_s::delayedNeutronIndex, MCGIDI_product_s::delayedNeutronIndex, MCGIDI_sampledProductsData_s::delayedNeutronRate, MCGIDI_product_s::delayedNeutronRate, MCGIDI_product_s::distribution, MCGIDI_decaySamplingInfo_s::Ep, MCGIDI_decaySamplingInfo_s::frame, G4Log(), MCGIDI_outputChannel_s::genre, MCGIDI_quantitiesLookupModes::getProjectileEnergy(), MCGIDI_decaySamplingInfo_s::isVelocity, MCGIDI_sampledProductsData_s::isVelocity, MCGIDI_distribution_s::KalbachMann, MCGIDI_sampledProductsData_s::kineticEnergy, M_PI, MCGIDI_POP_s::mass_MeV, MCGIDI_angular_sampleMu(), MCGIDI_angularEnergy_sampleDistribution(), MCGIDI_channelGenre_sumOfRemaining_e, MCGIDI_channelGenre_twoBody_e, MCGIDI_channelGenre_twoBodyDecay_e, MCGIDI_channelGenre_uncorrelated_e, MCGIDI_channelGenre_uncorrelatedDecay_e, MCGIDI_channelGenre_undefined_e, MCGIDI_distributionType_angularEnergy_e, MCGIDI_distributionType_energyAngular_e, MCGIDI_distributionType_KalbachMann_e, MCGIDI_distributionType_none_e, MCGIDI_distributionType_uncorrelated_e, MCGIDI_energyAngular_sampleDistribution(), MCGIDI_KalbachMann_sampleEp(), MCGIDI_kinetics_2BodyReaction(), MCGIDI_kinetics_COM2Lab(), MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_product_getMass_MeV(), MCGIDI_product_sampleMultiplicity(), MCGIDI_reaction_getProjectileMass_MeV(), MCGIDI_reaction_getTargetMass_MeV(), MCGIDI_sampledProducts_addProduct(), MCGIDI_speedOfLight_cm_sec, MCGIDI_uncorrelated_sampleDistribution(), MCGIDI_decaySamplingInfo_s::mu, MCGIDI_product_s::multiplicity, MCGIDI_POP_s::name, MCGIDI_sampledProductsDatas_s::numberOfProducts, MCGIDI_outputChannel_s::numberOfProducts, phi, MCGIDI_decaySamplingInfo_s::pop, MCGIDI_sampledProductsData_s::pop, MCGIDI_product_s::pop, printf(), MCGIDI_outputChannel_s::products, MCGIDI_sampledProductsData_s::px_vx, MCGIDI_sampledProductsData_s::py_vy, MCGIDI_sampledProductsData_s::pz_vz, MCGIDI_outputChannel_s::reaction, MCGIDI_decaySamplingInfo_s::rng, MCGIDI_decaySamplingInfo_s::rngState, smr_isOk(), MCGIDI_distribution_s::type, and xDataTOM_frame_centerOfMass.
Referenced by MCGIDI_outputChannel_sampleProductsAtE(), and MCGIDI_target_heated_sampleIndexReactionProductsAtE().