ECCE @ EIC Software: G4HadronicInteraction Class Reference
G4HadronicInteraction Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4HadronicInteraction.hh>
Public Member Functions
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)=0
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Protected Member Functions
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Private Member Functions
G4HadronicInteraction (const G4HadronicInteraction &right)=delete
const G4HadronicInteraction & operator= (const G4HadronicInteraction &right)=delete
G4bool operator== (const G4HadronicInteraction &right) const =delete
G4bool operator!= (const G4HadronicInteraction &right) const =delete
Private Attributes
G4HadronicInteractionRegistry * registry
G4double recoilEnergyThreshold
G4String theModelName
std::pair< G4double, G4double > epCheckLevels
std::vector< std::pair
< G4double, const G4Material * > > theMinEnergyList
std::vector< std::pair
< G4double, const G4Material * > > theMaxEnergyList
std::vector< std::pair
< G4double, const G4Element * > > theMinEnergyListElements
std::vector< std::pair
< G4double, const G4Element * > > theMaxEnergyListElements
std::vector< const G4Material * > theBlockedList
std::vector< const G4Element * > theBlockedListElements
Detailed Description
Definition at line 63 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 63 of file G4HadronicInteraction.hh
Constructor & Destructor Documentation
G4HadronicInteraction::G4HadronicInteraction (const G4String & modelName = "HadronicModel") explicit
Definition at line 41 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 41 of file G4HadronicInteraction.cc
References G4HadronicParameters::GetMaxEnergy(), G4HadronicInteractionRegistry::Instance(), G4HadronicParameters::Instance(), G4HadronicInteractionRegistry::RegisterMe(), registry, and theMaxEnergy.
G4HadronicInteraction::~G4HadronicInteraction () virtual
Definition at line 51 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HadronicInteraction.cc
References registry, and G4HadronicInteractionRegistry::RemoveMe().
G4HadronicInteraction::G4HadronicInteraction (const G4HadronicInteraction & right) private delete
Member Function Documentation
void G4HadronicInteraction::ActivateFor (const G4Material * aMaterial) inline
Definition at line 120 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 120 of file G4HadronicInteraction.hh
References Block(), GetMaxEnergy(), GetMinEnergy(), SetMaxEnergy(), and SetMinEnergy().
void G4HadronicInteraction::ActivateFor (const G4Element * anElement) inline
Definition at line 128 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 128 of file G4HadronicInteraction.hh
References Block(), GetMaxEnergy(), GetMinEnergy(), SetMaxEnergy(), and SetMinEnergy().
virtual G4HadFinalState* G4HadronicInteraction::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) pure virtual
Implemented in G4FissLib, G4INCLXXInterface, G4CascadeInterface, G4ParticleHPInelastic, G4UrQMD1_3Model, G4WilsonAbrasionModel, G4EMDissociation, G4ParticleHPThermalScattering, G4HIJING_Model, G4CRMCModel, G4BinaryCascade, G4LMsdGenerator, G4MuonMinusBoundDecay, G4EmCaptureCascade, G4NeutrinoNucleusModel, G4NuMuNucleusNcModel, G4MuMinusCapturePrecompound, G4LFission, G4PreCompoundModel, CexmcChargeExchangeProductionModel< OutputParticle >, G4LENDInelastic, G4NuMuNucleusCcModel, G4QMDReaction, G4GeneratorPrecompoundInterface, G4TheoFSGenerator, G4LEHadronProtonElastic, G4NeutronElectronElModel, G4LENDFission, G4NeutrinoElectronNcModel, G4LENDCapture, G4LENDElastic, G4NeutrinoElectronCcModel, G4ChargeExchange, G4NeutronRadCapture, G4LENDModel, G4ParticleHPFission, G4LowEIonFragmentation, G4LENDGammaModel, G4RPGKLongInelastic, G4HadronElastic, G4ParaFissionModel, G4LENDCombinedModel, G4RPGAntiKZeroInelastic, G4AblaInterface, G4ElectroVDNuclearModel, G4MuonVDNuclearModel, G4ParticleHPCapture, G4RPGKShortInelastic, G4RPGXiZeroInelastic, G4ParticleHPElastic, G4RPGAntiXiZeroInelastic, G4RPGKPlusInelastic, G4RPGKZeroInelastic, G4RPGLambdaInelastic, G4RPGSigmaMinusInelastic, G4LowEGammaNuclearModel, G4RPGAntiNeutronInelastic, G4RPGAntiOmegaMinusInelastic, G4RPGAntiSigmaMinusInelastic, G4RPGAntiXiMinusInelastic, G4RPGOmegaMinusInelastic, G4LEpp, G4LENDorBERTModel, G4VHighEnergyGenerator, G4RPGAntiLambdaInelastic, G4RPGAntiProtonInelastic, G4RPGAntiSigmaPlusInelastic, G4RPGSigmaPlusInelastic, G4RPGXiMinusInelastic, G4LEnp, G4RPGKMinusInelastic, G4RPGNeutronInelastic, G4RPGProtonInelastic, G4RPGPiMinusInelastic, G4RPGPiPlusInelastic, and G4BinaryLightIonReaction.
Referenced by G4LENDorBERTModel::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4MuonicAtomDecay::DecayIt(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), CexmcHadronicProcess::PostStepDoIt(), and G4HadronicProcess::PostStepDoIt().
void G4HadronicInteraction::Block () inline protected
Definition at line 165 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 165 of file G4HadronicInteraction.hh
References isBlocked.
Referenced by ActivateFor(), DeActivateFor(), SetMaxEnergy(), and SetMinEnergy().
void G4HadronicInteraction::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented in G4ParticleHPInelastic, G4ParticleHPThermalScattering, G4PreCompoundModel, G4ParticleHPElastic, G4ParticleHPFission, G4LENDModel, G4ParticleHPCapture, G4LENDCombinedModel, G4LENDGammaModel, and G4LENDorBERTModel.
Definition at line 56 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 56 of file G4HadronicInteraction.cc
void G4HadronicInteraction::DeActivateFor (const G4Material * aMaterial)
Definition at line 174 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 174 of file G4HadronicInteraction.cc
References Block(), and theBlockedList.
Referenced by G4HadronHElasticPhysics::ConstructProcess().
void G4HadronicInteraction::DeActivateFor (const G4Element * anElement)
Definition at line 180 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 180 of file G4HadronicInteraction.cc
References Block(), and theBlockedListElements.
std::pair< G4double, G4double > G4HadronicInteraction::GetEnergyMomentumCheckLevels () const virtual
Reimplemented in G4TheoFSGenerator.
Definition at line 211 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 211 of file G4HadronicInteraction.cc
References epCheckLevels.
Referenced by G4HadronicProcess::CheckEnergyMomentumConservation(), and G4TheoFSGenerator::GetEnergyMomentumCheckLevels().
const std::pair< G4double, G4double > G4HadronicInteraction::GetFatalEnergyCheckLevels () const virtual
Reimplemented in G4FissLib, G4ParticleHPInelastic, G4ParticleHPThermalScattering, G4LFission, G4LENDFission, G4ParticleHPFission, G4ParticleHPCapture, and G4ParticleHPElastic.
Definition at line 204 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 204 of file G4HadronicInteraction.cc
References GeV, and perCent.
Referenced by G4HadronicProcess::CheckResult().
G4double G4HadronicInteraction::GetMaxEnergy () const inline
Definition at line 96 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 96 of file G4HadronicInteraction.hh
References theMaxEnergy.
Referenced by ActivateFor(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), G4IonPhysics::ConstructProcess(), G4ChargeExchange::G4ChargeExchange(), G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4HadronElastic::G4HadronElastic(), G4hhElastic::G4hhElastic(), G4LowEGammaNuclearModel::G4LowEGammaNuclearModel(), G4NeutrinoElectronCcModel::G4NeutrinoElectronCcModel(), G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel(), G4NeutronRadCapture::G4NeutronRadCapture(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), G4EnergyRangeManager::GetHadronicInteraction(), and G4HadronicProcessStore::Print().
G4double G4HadronicInteraction::GetMaxEnergy (const G4Material * aMaterial, const G4Element * anElement) const
Definition at line 125 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 125 of file G4HadronicInteraction.cc
References IsBlocked(), theMaxEnergy, theMaxEnergyList, and theMaxEnergyListElements.
G4double G4HadronicInteraction::GetMinEnergy () const inline
Definition at line 83 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 83 of file G4HadronicInteraction.hh
References theMinEnergy.
Referenced by ActivateFor(), G4EnergyRangeManager::GetHadronicInteraction(), and G4HadronicProcessStore::Print().
G4double G4HadronicInteraction::GetMinEnergy (const G4Material * aMaterial, const G4Element * anElement) const
Definition at line 75 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 75 of file G4HadronicInteraction.cc
References DBL_MAX, IsBlocked(), theMinEnergy, theMinEnergyList, and theMinEnergyListElements.
const G4String& G4HadronicInteraction::GetModelName () const inline
Definition at line 115 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 115 of file G4HadronicInteraction.hh
References theModelName.
Referenced by G4HadronElastic::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4HadronStoppingProcess::AtRestDoIt(), G4VHadronPhysics::BuildModel(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4HadronicProcess::CheckResult(), G4ChargeExchangePhysics::ConstructProcess(), G4MuonicAtomDecay::DecayIt(), G4LENDModel::DumpLENDTargetInfo(), G4INCLXXInterface::GetDeExcitationModelName(), G4EnergyRangeManager::GetHadronicInteraction(), G4VHighEnergyGenerator::GetProjectileNucleus(), G4VPartonStringModel::ModelDescription(), G4TheoFSGenerator::ModelDescription(), G4BinaryCascade::ModelDescription(), G4LMsdGenerator::ModelDescription(), G4VHadronPhysics::NewModel(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4HadronicProcessStore::PrintModelHtml(), G4BinaryCascade::PropagateModelDescription(), G4HadronicProcessStore::RegisterInteraction(), G4HadronicProcess::RegisterMe(), and G4LENDModel::returnUnchanged().
G4double G4HadronicInteraction::GetRecoilEnergyThreshold () const inline
Definition at line 141 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 141 of file G4HadronicInteraction.hh
References recoilEnergyThreshold.
Referenced by G4HadronElastic::ApplyYourself(), and G4ChargeExchange::ApplyYourself().
G4int G4HadronicInteraction::GetVerboseLevel () const inline
Definition at line 109 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 109 of file G4HadronicInteraction.hh
References verboseLevel.
void G4HadronicInteraction::InitialiseModel () virtual
Reimplemented in G4ElasticHadrNucleusHE, G4PreCompoundModel, G4NuMuNucleusNcModel, G4NuMuNucleusCcModel, G4NeutronRadCapture, and G4LowEGammaNuclearModel.
Definition at line 59 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 59 of file G4HadronicInteraction.cc
G4bool G4HadronicInteraction::IsApplicable (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Reimplemented in G4CascadeInterface, G4LMsdGenerator, G4hhElastic, G4DiffuseElastic, G4NeutrinoNucleusModel, G4NuMuNucleusNcModel, G4DiffuseElasticV2, G4NuMuNucleusCcModel, G4NeutronElectronElModel, G4NeutrinoElectronNcModel, and G4NeutrinoElectronCcModel.
Definition at line 69 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 69 of file G4HadronicInteraction.cc
G4bool G4HadronicInteraction::IsBlocked (const G4Material * aMaterial) const
Definition at line 187 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 187 of file G4HadronicInteraction.cc
References mat, and theBlockedList.
G4bool G4HadronicInteraction::IsBlocked (const G4Element * anElement) const
Definition at line 196 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 196 of file G4HadronicInteraction.cc
References theBlockedListElements.
G4bool G4HadronicInteraction::IsBlocked () const inline protected
Definition at line 164 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 164 of file G4HadronicInteraction.hh
References isBlocked.
Referenced by GetMaxEnergy(), and GetMinEnergy().
void G4HadronicInteraction::ModelDescription (std::ostream & outFile) const virtual
Reimplemented in G4NeutrinoNucleusModel, G4INCLXXInterface, G4CascadeInterface, G4ElasticHadrNucleusHE, G4ParticleHPInelastic, G4WilsonAbrasionModel, G4ParticleHPThermalScattering, G4NuMuNucleusNcModel, G4NuMuNucleusCcModel, G4VIntraNuclearTransportModel, G4LMsdGenerator, G4BinaryCascade, G4NeutronElectronElModel, G4MuonMinusBoundDecay, G4PreCompoundModel, G4QMDReaction, G4EmCaptureCascade, G4LFission, G4MuMinusCapturePrecompound, G4HadronElastic, G4NeutrinoElectronNcModel, G4NeutrinoElectronCcModel, G4FTFModel, G4TheoFSGenerator, G4ParticleHPElastic, G4ParticleHPFission, G4VHighEnergyGenerator, G4VPartonStringModel, G4ParticleHPCapture, G4QGSModel< ParticipantType >, G4QGSModel< G4GammaParticipants >, G4QGSModel< G4QGSParticipants >, G4ChipsElasticModel, G4AblaInterface, G4ElectroVDNuclearModel, G4MuonVDNuclearModel, and G4BinaryLightIonReaction.
Definition at line 216 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 216 of file G4HadronicInteraction.cc
Referenced by G4HadronicProcessStore::PrintModelHtml().
G4bool G4HadronicInteraction::operator!= (const G4HadronicInteraction & right) const private delete
const G4HadronicInteraction& G4HadronicInteraction::operator= (const G4HadronicInteraction & right) private delete
G4bool G4HadronicInteraction::operator== (const G4HadronicInteraction & right) const private delete
G4double G4HadronicInteraction::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) virtual
Reimplemented in G4ElasticHadrNucleusHE, G4DiffuseElastic, G4hhElastic, G4DiffuseElasticV2, G4NuclNuclDiffuseElastic, G4LEHadronProtonElastic, G4ChipsElasticModel, G4HadronElastic, G4LEnp, G4LEpp, G4AntiNuclElastic, and G4LowEHadronElastic.
Definition at line 63 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 63 of file G4HadronicInteraction.cc
void G4HadronicInteraction::SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel) inline
Definition at line 149 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 149 of file G4HadronicInteraction.hh
References epCheckLevels.
Referenced by G4BinaryCascade::G4BinaryCascade(), G4CascadeInterface::G4CascadeInterface(), and G4FTFModel::G4FTFModel().
void G4HadronicInteraction::SetMaxEnergy (const G4double anEnergy) inline
Definition at line 102 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 102 of file G4HadronicInteraction.hh
References theMaxEnergy.
Referenced by ActivateFor(), G4IonINCLXXPhysics::AddProcess(), BiasingOperation::BiasingOperation(), G4ProtonPHPBuilder::Build(), G4AlphaPHPBuilder::Build(), G4NeutronLENDBuilder::Build(), G4NeutronPHPBuilder::Build(), G4BertiniElectroNuclearBuilder::Build(), G4He3PHPBuilder::Build(), G4DeuteronPHPBuilder::Build(), G4TritonPHPBuilder::Build(), G4BinaryProtonBuilder::Build(), G4LENDBertiniGammaElectroNuclearBuilder::Build(), G4BertiniPiKBuilder::Build(), G4PrecoProtonBuilder::Build(), G4BinaryTritonBuilder::Build(), G4BertiniProtonBuilder::Build(), G4BinaryAlphaBuilder::Build(), G4BinaryDeuteronBuilder::Build(), G4BinaryHe3Builder::Build(), G4BinaryPiKBuilder::Build(), G4BinaryPionBuilder::Build(), G4BertiniKaonBuilder::Build(), G4BertiniNeutronBuilder::Build(), G4BertiniPionBuilder::Build(), G4BinaryNeutronBuilder::Build(), G4PrecoNeutronBuilder::Build(), G4FTFBinaryKaonBuilder::Build(), G4INCLXXPionBuilder::Build(), G4QGSBinaryProtonBuilder::Build(), G4FTFBinaryPionBuilder::Build(), G4FTFBinaryProtonBuilder::Build(), G4FTFPKaonBuilder::Build(), G4FTFPPionBuilder::Build(), G4FTFPProtonBuilder::Build(), G4INCLXXNeutronBuilder::Build(), G4QGSBinaryKaonBuilder::Build(), G4QGSBinaryPionBuilder::Build(), G4QGSPKaonBuilder::Build(), G4QGSPLundStrFragmProtonBuilder::Build(), G4FTFPAntiBarionBuilder::Build(), G4QGSBinaryPiKBuilder::Build(), G4QGSPPiKBuilder::Build(), G4QGSPPionBuilder::Build(), G4QGSPProtonBuilder::Build(), G4FTFBinaryNeutronBuilder::Build(), G4FTFPPiKBuilder::Build(), G4QGSBinaryNeutronBuilder::Build(), G4FTFPNeutronBuilder::Build(), G4QGSPNeutronBuilder::Build(), G4INCLXXProtonBuilder::Build(), G4VHadronPhysics::BuildModel(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), G4EmExtraPhysics::ConstructLENDGammaNuclear(), ProtonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), GammaLeptoNuclearPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), GammaNuclearPhysics::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), G4IonPhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4HadronPhysicsFTFP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsINCLXX::ExtraConfiguration(), G4BertiniKaonBuilder::G4BertiniKaonBuilder(), G4BertiniPiKBuilder::G4BertiniPiKBuilder(), G4BertiniPionBuilder::G4BertiniPionBuilder(), G4BinaryCascade::G4BinaryCascade(), G4BinaryPiKBuilder::G4BinaryPiKBuilder(), G4BinaryPionBuilder::G4BinaryPionBuilder(), G4ChargeExchange::G4ChargeExchange(), G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4EMDissociation::G4EMDissociation(), G4FissLib::G4FissLib(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronElastic::G4HadronElastic(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicAbsorptionFritiofWithBinaryCascade::G4HadronicAbsorptionFritiofWithBinaryCascade(), G4hhElastic::G4hhElastic(), G4HyperonFTFPBuilder::G4HyperonFTFPBuilder(), G4INCLXXPionBuilder::G4INCLXXPionBuilder(), G4LEHadronProtonElastic::G4LEHadronProtonElastic(), G4LENDModel::G4LENDModel(), G4LEnp::G4LEnp(), G4LEpp::G4LEpp(), G4LFission::G4LFission(), G4LowEGammaNuclearModel::G4LowEGammaNuclearModel(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4NeutrinoElectronCcModel::G4NeutrinoElectronCcModel(), G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel(), G4NeutrinoNucleusModel::G4NeutrinoNucleusModel(), G4NeutronElectronElModel::G4NeutronElectronElModel(), G4NeutronRadCapture::G4NeutronRadCapture(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), G4NuMuNucleusNcModel::G4NuMuNucleusNcModel(), G4ParaFissionModel::G4ParaFissionModel(), G4ParticleHPCapture::G4ParticleHPCapture(), G4ParticleHPElastic::G4ParticleHPElastic(), G4ParticleHPFission::G4ParticleHPFission(), G4ParticleHPInelastic::G4ParticleHPInelastic(), G4ParticleHPThermalScattering::G4ParticleHPThermalScattering(), G4RPGAntiKZeroInelastic::G4RPGAntiKZeroInelastic(), G4RPGAntiLambdaInelastic::G4RPGAntiLambdaInelastic(), G4RPGAntiNeutronInelastic::G4RPGAntiNeutronInelastic(), G4RPGAntiOmegaMinusInelastic::G4RPGAntiOmegaMinusInelastic(), G4RPGAntiProtonInelastic::G4RPGAntiProtonInelastic(), G4RPGAntiSigmaMinusInelastic::G4RPGAntiSigmaMinusInelastic(), G4RPGAntiSigmaPlusInelastic::G4RPGAntiSigmaPlusInelastic(), G4RPGAntiXiMinusInelastic::G4RPGAntiXiMinusInelastic(), G4RPGAntiXiZeroInelastic::G4RPGAntiXiZeroInelastic(), G4RPGKLongInelastic::G4RPGKLongInelastic(), G4RPGKMinusInelastic::G4RPGKMinusInelastic(), G4RPGKPlusInelastic::G4RPGKPlusInelastic(), G4RPGKShortInelastic::G4RPGKShortInelastic(), G4RPGKZeroInelastic::G4RPGKZeroInelastic(), G4RPGLambdaInelastic::G4RPGLambdaInelastic(), G4RPGNucleonInelastic::G4RPGNucleonInelastic(), G4RPGOmegaMinusInelastic::G4RPGOmegaMinusInelastic(), G4RPGPionInelastic::G4RPGPionInelastic(), G4RPGSigmaMinusInelastic::G4RPGSigmaMinusInelastic(), G4RPGSigmaPlusInelastic::G4RPGSigmaPlusInelastic(), G4RPGXiMinusInelastic::G4RPGXiMinusInelastic(), G4RPGXiZeroInelastic::G4RPGXiZeroInelastic(), G4WilsonAbrasionModel::G4WilsonAbrasionModel(), and G4VHadronPhysics::NewModel().
void G4HadronicInteraction::SetMaxEnergy (G4double anEnergy, const G4Element * anElement)
Definition at line 145 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 145 of file G4HadronicInteraction.cc
References Block(), and theMaxEnergyListElements.
void G4HadronicInteraction::SetMaxEnergy (G4double anEnergy, const G4Material * aMaterial)
Definition at line 160 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 160 of file G4HadronicInteraction.cc
References Block(), and theMaxEnergyList.
void G4HadronicInteraction::SetMinEnergy (G4double anEnergy) inline
Definition at line 89 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 89 of file G4HadronicInteraction.hh
References theMinEnergy.
Referenced by ActivateFor(), BiasingOperation::BiasingOperation(), G4AlphaPHPBuilder::Build(), G4NeutronLENDBuilder::Build(), G4ProtonPHPBuilder::Build(), G4NeutronPHPBuilder::Build(), G4BertiniElectroNuclearBuilder::Build(), G4He3PHPBuilder::Build(), G4DeuteronPHPBuilder::Build(), G4TritonPHPBuilder::Build(), G4BinaryProtonBuilder::Build(), G4LENDBertiniGammaElectroNuclearBuilder::Build(), G4PrecoProtonBuilder::Build(), G4BinaryPionBuilder::Build(), G4BinaryTritonBuilder::Build(), G4BertiniPiKBuilder::Build(), G4BinaryAlphaBuilder::Build(), G4BinaryDeuteronBuilder::Build(), G4BinaryHe3Builder::Build(), G4BertiniProtonBuilder::Build(), G4BinaryPiKBuilder::Build(), G4BertiniKaonBuilder::Build(), G4BertiniNeutronBuilder::Build(), G4BertiniPionBuilder::Build(), G4BinaryNeutronBuilder::Build(), G4PrecoNeutronBuilder::Build(), G4FTFBinaryKaonBuilder::Build(), G4INCLXXPionBuilder::Build(), G4QGSBinaryProtonBuilder::Build(), G4FTFBinaryPionBuilder::Build(), G4FTFBinaryProtonBuilder::Build(), G4FTFPKaonBuilder::Build(), G4FTFPPionBuilder::Build(), G4FTFPProtonBuilder::Build(), G4INCLXXNeutronBuilder::Build(), G4QGSBinaryKaonBuilder::Build(), G4QGSBinaryPionBuilder::Build(), G4QGSPKaonBuilder::Build(), G4QGSPLundStrFragmProtonBuilder::Build(), G4FTFBinaryPiKBuilder::Build(), G4FTFPAntiBarionBuilder::Build(), G4QGSBinaryPiKBuilder::Build(), G4FTFBinaryNeutronBuilder::Build(), G4QGSPPiKBuilder::Build(), G4QGSPPionBuilder::Build(), G4QGSPProtonBuilder::Build(), G4FTFPPiKBuilder::Build(), G4QGSBinaryNeutronBuilder::Build(), G4FTFPNeutronBuilder::Build(), G4QGSPNeutronBuilder::Build(), G4INCLXXProtonBuilder::Build(), G4VHadronPhysics::BuildModel(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), B03PhysicsList::ConstructHad(), DMXPhysicsList::ConstructHad(), LBE::ConstructHad(), G4EmExtraPhysics::ConstructLENDGammaNuclear(), ProtonPhysics::ConstructProcess(), KaonPhysics::ConstructProcess(), AntiBaryonPhysics::ConstructProcess(), NeutronPhysics::ConstructProcess(), HyperonPhysics::ConstructProcess(), PionPhysics::ConstructProcess(), GammaLeptoNuclearPhysics::ConstructProcess(), IonPhysics::ConstructProcess(), HadronElasticPhysicsHP::ConstructProcess(), NeutronHPphysics::ConstructProcess(), G4HadronElasticPhysicsPHP::ConstructProcess(), G4HadronElasticPhysicsHP::ConstructProcess(), G4HadronElasticPhysicsLEND::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4IonPhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), G4IonPhysicsPHP::ConstructProcess(), G4IonINCLXXPhysics::ConstructProcess(), G4IonQMDPhysics::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess(), G4HadronPhysicsQGSP_BIC_HP::ConstructProcess(), GammaRayTelIonPhysics::ConstructProcess(), GammaRayTelHadronPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::CreateModels(), G4HadronPhysicsFTFP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsShieldingLEND::ExtraConfiguration(), G4HadronPhysicsShielding::ExtraConfiguration(), G4HadronPhysicsQGSP_BERT_HP::ExtraConfiguration(), G4HadronPhysicsINCLXX::ExtraConfiguration(), G4BertiniKaonBuilder::G4BertiniKaonBuilder(), G4BertiniPiKBuilder::G4BertiniPiKBuilder(), G4BertiniPionBuilder::G4BertiniPionBuilder(), G4BinaryCascade::G4BinaryCascade(), G4BinaryPiKBuilder::G4BinaryPiKBuilder(), G4BinaryPionBuilder::G4BinaryPionBuilder(), G4ChargeExchange::G4ChargeExchange(), G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4ElectroVDNuclearModel::G4ElectroVDNuclearModel(), G4EMDissociation::G4EMDissociation(), G4FissLib::G4FissLib(), G4FTFBinaryKaonBuilder::G4FTFBinaryKaonBuilder(), G4FTFBinaryNeutronBuilder::G4FTFBinaryNeutronBuilder(), G4FTFBinaryPiKBuilder::G4FTFBinaryPiKBuilder(), G4FTFBinaryPionBuilder::G4FTFBinaryPionBuilder(), G4FTFBinaryProtonBuilder::G4FTFBinaryProtonBuilder(), G4FTFPAntiBarionBuilder::G4FTFPAntiBarionBuilder(), G4FTFPKaonBuilder::G4FTFPKaonBuilder(), G4FTFPNeutronBuilder::G4FTFPNeutronBuilder(), G4FTFPPiKBuilder::G4FTFPPiKBuilder(), G4FTFPPionBuilder::G4FTFPPionBuilder(), G4FTFPProtonBuilder::G4FTFPProtonBuilder(), G4HadronElastic::G4HadronElastic(), G4HadronicAbsorptionBertini::G4HadronicAbsorptionBertini(), G4HadronicAbsorptionFritiof::G4HadronicAbsorptionFritiof(), G4HadronicAbsorptionFritiofWithBinaryCascade::G4HadronicAbsorptionFritiofWithBinaryCascade(), G4hhElastic::G4hhElastic(), G4HyperonFTFPBuilder::G4HyperonFTFPBuilder(), G4INCLXXPionBuilder::G4INCLXXPionBuilder(), G4LEHadronProtonElastic::G4LEHadronProtonElastic(), G4LENDModel::G4LENDModel(), G4LEnp::G4LEnp(), G4LEpp::G4LEpp(), G4LFission::G4LFission(), G4LowEGammaNuclearModel::G4LowEGammaNuclearModel(), G4MuonVDNuclearModel::G4MuonVDNuclearModel(), G4NeutrinoElectronCcModel::G4NeutrinoElectronCcModel(), G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel(), G4NeutrinoNucleusModel::G4NeutrinoNucleusModel(), G4NeutronElectronElModel::G4NeutronElectronElModel(), G4NeutronRadCapture::G4NeutronRadCapture(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), G4NuMuNucleusNcModel::G4NuMuNucleusNcModel(), G4ParaFissionModel::G4ParaFissionModel(), G4ParticleHPCapture::G4ParticleHPCapture(), G4ParticleHPElastic::G4ParticleHPElastic(), G4ParticleHPFission::G4ParticleHPFission(), G4ParticleHPInelastic::G4ParticleHPInelastic(), G4ParticleHPThermalScattering::G4ParticleHPThermalScattering(), G4RPGAntiKZeroInelastic::G4RPGAntiKZeroInelastic(), G4RPGAntiLambdaInelastic::G4RPGAntiLambdaInelastic(), G4RPGAntiNeutronInelastic::G4RPGAntiNeutronInelastic(), G4RPGAntiOmegaMinusInelastic::G4RPGAntiOmegaMinusInelastic(), G4RPGAntiProtonInelastic::G4RPGAntiProtonInelastic(), G4RPGAntiSigmaMinusInelastic::G4RPGAntiSigmaMinusInelastic(), G4RPGAntiSigmaPlusInelastic::G4RPGAntiSigmaPlusInelastic(), G4RPGAntiXiMinusInelastic::G4RPGAntiXiMinusInelastic(), G4RPGAntiXiZeroInelastic::G4RPGAntiXiZeroInelastic(), G4RPGKLongInelastic::G4RPGKLongInelastic(), G4RPGKMinusInelastic::G4RPGKMinusInelastic(), G4RPGKPlusInelastic::G4RPGKPlusInelastic(), G4RPGKShortInelastic::G4RPGKShortInelastic(), G4RPGKZeroInelastic::G4RPGKZeroInelastic(), G4RPGLambdaInelastic::G4RPGLambdaInelastic(), G4RPGNucleonInelastic::G4RPGNucleonInelastic(), G4RPGOmegaMinusInelastic::G4RPGOmegaMinusInelastic(), G4RPGPionInelastic::G4RPGPionInelastic(), G4RPGSigmaMinusInelastic::G4RPGSigmaMinusInelastic(), G4RPGSigmaPlusInelastic::G4RPGSigmaPlusInelastic(), G4RPGXiMinusInelastic::G4RPGXiMinusInelastic(), G4RPGXiZeroInelastic::G4RPGXiZeroInelastic(), G4WilsonAbrasionModel::G4WilsonAbrasionModel(), G4NeutrinoElectronCcModel::IsApplicable(), and G4VHadronPhysics::NewModel().
void G4HadronicInteraction::SetMinEnergy (G4double anEnergy, const G4Element * anElement)
Definition at line 95 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 95 of file G4HadronicInteraction.cc
References Block(), and theMinEnergyListElements.
void G4HadronicInteraction::SetMinEnergy (G4double anEnergy, const G4Material * aMaterial)
Definition at line 110 of file G4HadronicInteraction.cc.
View newest version in sPHENIX GitHub at line 110 of file G4HadronicInteraction.cc
References Block(), and theMinEnergyList.
void G4HadronicInteraction::SetModelName (const G4String & nam) inline protected
Definition at line 161 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 161 of file G4HadronicInteraction.hh
References theModelName.
void G4HadronicInteraction::SetRecoilEnergyThreshold (G4double val) inline
Definition at line 138 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 138 of file G4HadronicInteraction.hh
References recoilEnergyThreshold.
Referenced by G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), and G4MuNeutrinoNucleusProcess::PostStepDoIt().
void G4HadronicInteraction::SetVerboseLevel (G4int value) inline
Definition at line 112 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 112 of file G4HadronicInteraction.hh
References verboseLevel.
Referenced by G4PreCompoundDeexcitation::setVerboseLevel(), and G4CascadeInterface::SetVerboseLevel().
Member Data Documentation
std::pair<G4double, G4double> G4HadronicInteraction::epCheckLevels private
Definition at line 198 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 198 of file G4HadronicInteraction.hh
Referenced by GetEnergyMomentumCheckLevels(), and SetEnergyMomentumCheckLevels().
G4bool G4HadronicInteraction::isBlocked protected
Definition at line 183 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 183 of file G4HadronicInteraction.hh
Referenced by Block(), G4WilsonAbrasionModel::G4WilsonAbrasionModel(), and IsBlocked().
G4double G4HadronicInteraction::recoilEnergyThreshold private
Definition at line 194 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 194 of file G4HadronicInteraction.hh
Referenced by GetRecoilEnergyThreshold(), and SetRecoilEnergyThreshold().
G4HadronicInteractionRegistry* G4HadronicInteraction::registry private
Definition at line 192 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 192 of file G4HadronicInteraction.hh
Referenced by G4HadronicInteraction(), and ~G4HadronicInteraction().
std::vector<const G4Material *> G4HadronicInteraction::theBlockedList private
Definition at line 204 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 204 of file G4HadronicInteraction.hh
Referenced by DeActivateFor(), and IsBlocked().
std::vector<const G4Element *> G4HadronicInteraction::theBlockedListElements private
Definition at line 205 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 205 of file G4HadronicInteraction.hh
Referenced by DeActivateFor(), and IsBlocked().
G4double G4HadronicInteraction::theMaxEnergy protected
Definition at line 181 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 181 of file G4HadronicInteraction.hh
Referenced by G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4HadronicInteraction(), G4hhElastic::G4hhElastic(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), GetMaxEnergy(), and SetMaxEnergy().
std::vector<std::pair<G4double, const G4Material *> > G4HadronicInteraction::theMaxEnergyList private
Definition at line 201 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 201 of file G4HadronicInteraction.hh
Referenced by GetMaxEnergy(), and SetMaxEnergy().
std::vector<std::pair<G4double, const G4Element *> > G4HadronicInteraction::theMaxEnergyListElements private
Definition at line 203 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 203 of file G4HadronicInteraction.hh
Referenced by GetMaxEnergy(), and SetMaxEnergy().
G4double G4HadronicInteraction::theMinEnergy protected
Definition at line 180 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 180 of file G4HadronicInteraction.hh
Referenced by G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4hhElastic::G4hhElastic(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), GetMinEnergy(), and SetMinEnergy().
std::vector<std::pair<G4double, const G4Material *> > G4HadronicInteraction::theMinEnergyList private
Definition at line 200 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 200 of file G4HadronicInteraction.hh
Referenced by GetMinEnergy(), and SetMinEnergy().
std::vector<std::pair<G4double, const G4Element *> > G4HadronicInteraction::theMinEnergyListElements private
Definition at line 202 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 202 of file G4HadronicInteraction.hh
Referenced by GetMinEnergy(), and SetMinEnergy().
G4String G4HadronicInteraction::theModelName private
Definition at line 196 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 196 of file G4HadronicInteraction.hh
Referenced by GetModelName(), and SetModelName().
G4HadFinalState G4HadronicInteraction::theParticleChange protected
Definition at line 167 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 167 of file G4HadronicInteraction.hh
Referenced by G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LENDFission::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4LFission::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4ParticleHPThermalScattering::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4MuonVDNuclearModel::CalculateEMVertex(), G4MuonVDNuclearModel::CalculateHadronicVertex(), G4ElectroVDNuclearModel::CalculateHadronicVertex(), G4NeutrinoNucleusModel::CoherentPion(), G4CascadeInterface::copyOutputToHadronicResult(), G4BinaryCascade::DebugEpConservation(), G4BinaryCascade::DebugFinalEpConservation(), G4NeutrinoNucleusModel::FinalBarion(), G4NeutrinoNucleusModel::FinalMeson(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4CascadeInterface::NoInteraction(), G4CascadeInterface::Propagate(), G4NeutrinoNucleusModel::RecoilDeexcitation(), G4RPGInelastic::SetUpChange(), G4RPGNeutronInelastic::SlowNeutron(), G4RPGProtonInelastic::SlowProton(), G4LEHadronProtonElastic::~G4LEHadronProtonElastic(), G4LEnp::~G4LEnp(), and G4LFission::~G4LFission().
G4int G4HadronicInteraction::verboseLevel protected
Definition at line 172 of file G4HadronicInteraction.hh.
View newest version in sPHENIX GitHub at line 172 of file G4HadronicInteraction.hh
Referenced by G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LFission::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4CascadeInterface::ApplyYourself(), G4CascadeInterface::checkFinalResult(), G4CascadeInterface::copyOutputToHadronicResult(), G4CascadeInterface::copyOutputToReactionProducts(), G4LENDModel::create_used_target_map(), G4CascadeInterface::createBullet(), G4CascadeInterface::createTarget(), G4ElasticHadrNucleusHE::DefineHadronValues(), G4ElasticHadrNucleusHE::FillData(), G4ElasticHadrNucleusHE::FillFq2(), G4DiffuseElastic::G4DiffuseElastic(), G4DiffuseElasticV2::G4DiffuseElasticV2(), G4ElasticHadrNucleusHE::G4ElasticHadrNucleusHE(), G4EMDissociation::G4EMDissociation(), G4hhElastic::G4hhElastic(), G4NuclNuclDiffuseElastic::G4NuclNuclDiffuseElastic(), G4WilsonAbrasionModel::G4WilsonAbrasionModel(), G4ElasticHadrNucleusHE::GetFt(), G4ElasticHadrNucleusHE::GetLightFq2(), G4ElasticHadrNucleusHE::GetQ2_2(), GetVerboseLevel(), G4ElasticHadrNucleusHE::HadronNucleusQ2_2(), G4ElasticHadrNucleusHE::HadronProtonQ2(), G4LFission::init(), G4NuclNuclDiffuseElastic::Initialise(), G4DiffuseElasticV2::Initialise(), G4DiffuseElastic::Initialise(), G4NuclNuclDiffuseElastic::InitialiseOnFly(), G4DiffuseElasticV2::InitialiseOnFly(), G4DiffuseElastic::InitialiseOnFly(), G4CascadeInterface::makeDynamicParticle(), G4CascadeInterface::NoInteraction(), G4CascadeInterface::Propagate(), G4ElasticHadrNucleusHE::SampleInvariantT(), G4AntiNuclElastic::SampleThetaCMS(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4WilsonAbrasionModel::SetUseAblation(), G4WilsonAbrasionModel::SetVerboseLevel(), SetVerboseLevel(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), and G4DiffuseElastic::ThetaLabToThetaCMS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/include/G4HadronicInteraction.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/management/src/G4HadronicInteraction.cc