ECCE @ EIC Software: G4NeutronRadCapture Class Reference
G4NeutronRadCapture Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/include/G4NeutronRadCapture.hh>
Public Member Functions
G4NeutronRadCapture ()
virtual ~G4NeutronRadCapture ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) final
virtual void InitialiseModel () final
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4NeutronRadCapture & operator= (const G4NeutronRadCapture &right)=delete
G4NeutronRadCapture (const G4NeutronRadCapture &)=delete
Private Attributes
G4int icID
const G4ParticleDefinition * electron
G4double lowestEnergyLimit
G4double minExcitation
G4VEvaporationChannel * photonEvaporation
G4IonTable * theTableOfIons
G4LorentzVector lab4mom
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 51 of file G4NeutronRadCapture.hh.
View newest version in sPHENIX GitHub at line 51 of file G4NeutronRadCapture.hh
Constructor & Destructor Documentation
G4NeutronRadCapture::G4NeutronRadCapture () explicit
Definition at line 55 of file G4NeutronRadCapture.cc.
View newest version in sPHENIX GitHub at line 55 of file G4NeutronRadCapture.cc
References G4Electron::Electron(), electron, CLHEP::eV, G4ParticleTable::GetIonTable(), G4HadronicInteraction::GetMaxEnergy(), G4ParticleTable::GetParticleTable(), CLHEP::GeV, icID, G4HadronicParameters::Instance(), CLHEP::keV, lowestEnergyLimit, minExcitation, G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), and theTableOfIons.
G4NeutronRadCapture::~G4NeutronRadCapture () virtual
Definition at line 70 of file G4NeutronRadCapture.cc.
View newest version in sPHENIX GitHub at line 70 of file G4NeutronRadCapture.cc
References photonEvaporation.
G4NeutronRadCapture::G4NeutronRadCapture (const G4NeutronRadCapture &) private delete
Member Function Documentation
G4HadFinalState * G4NeutronRadCapture::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) final virtual
Implements G4HadronicInteraction.
Definition at line 88 of file G4NeutronRadCapture.cc.
View newest version in sPHENIX GitHub at line 88 of file G4NeutronRadCapture.cc
References A(), G4HadFinalState::AddSecondary(), G4Alpha::Alpha(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4VEvaporationChannel::BreakUpFragment(), G4HadFinalState::Clear(), G4Deuteron::Deuteron(), CLHEP::HepLorentzVector::e(), e1, electron, f, G4cout, G4endl, G4RandomDirection(), G4Gamma::Gamma(), G4HadProjectile::Get4Momentum(), G4Fragment::GetA_asInt(), G4Nucleus::GetA_asInt(), G4Fragment::GetCreationTime(), G4Fragment::GetExcitationEnergy(), G4HadProjectile::GetGlobalTime(), G4IonTable::GetIon(), G4HadProjectile::GetKineticEnergy(), G4Fragment::GetMomentum(), G4NucleiProperties::GetNuclearMass(), G4Fragment::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4Fragment::GetZ_asInt(), G4Nucleus::GetZ_asInt(), G4He3::He3(), icID, lab4mom, lowestEnergyLimit, CLHEP::HepLorentzVector::mag(), mass, max, MeV, minExcitation, n, noFloat, photonEvaporation, CLHEP::HepLorentzVector::set(), G4HadSecondary::SetCreatorModelType(), G4HadFinalState::SetStatusChange(), G4HadSecondary::SetTime(), stopAndKill, G4HadronicInteraction::theParticleChange, theTableOfIons, Acts::VectorHelpers::time(), G4Triton::Triton(), CLHEP::Hep3Vector::unit(), v, CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
void G4NeutronRadCapture::InitialiseModel () final virtual
Reimplemented from G4HadronicInteraction.
Definition at line 75 of file G4NeutronRadCapture.cc.
View newest version in sPHENIX GitHub at line 75 of file G4NeutronRadCapture.cc
References G4NuclearLevelData::GetInstance(), G4DeexPrecoParameters::GetInternalConversionID(), G4DeexPrecoParameters::GetMinExcitation(), G4NuclearLevelData::GetParameters(), icID, G4VEvaporationChannel::Initialise(), minExcitation, photonEvaporation, and G4VEvaporationChannel::SetICM().
G4NeutronRadCapture& G4NeutronRadCapture::operator= (const G4NeutronRadCapture & right) private delete
Member Data Documentation
const G4ParticleDefinition* G4NeutronRadCapture::electron private
Definition at line 70 of file G4NeutronRadCapture.hh.
View newest version in sPHENIX GitHub at line 70 of file G4NeutronRadCapture.hh
Referenced by ApplyYourself(), and G4NeutronRadCapture().
G4int G4NeutronRadCapture::icID private
Definition at line 69 of file G4NeutronRadCapture.hh.
View newest version in sPHENIX GitHub at line 69 of file G4NeutronRadCapture.hh
Referenced by ApplyYourself(), G4NeutronRadCapture(), and InitialiseModel().
G4LorentzVector G4NeutronRadCapture::lab4mom private
Definition at line 75 of file G4NeutronRadCapture.hh.
View newest version in sPHENIX GitHub at line 75 of file G4NeutronRadCapture.hh
Referenced by ApplyYourself().
G4double G4NeutronRadCapture::lowestEnergyLimit private
Definition at line 71 of file G4NeutronRadCapture.hh.
View newest version in sPHENIX GitHub at line 71 of file G4NeutronRadCapture.hh
Referenced by ApplyYourself(), and G4NeutronRadCapture().
G4double G4NeutronRadCapture::minExcitation private
Definition at line 72 of file G4NeutronRadCapture.hh.
View newest version in sPHENIX GitHub at line 72 of file G4NeutronRadCapture.hh
Referenced by ApplyYourself(), G4NeutronRadCapture(), and InitialiseModel().
G4VEvaporationChannel* G4NeutronRadCapture::photonEvaporation private
Definition at line 73 of file G4NeutronRadCapture.hh.
View newest version in sPHENIX GitHub at line 73 of file G4NeutronRadCapture.hh
Referenced by ApplyYourself(), InitialiseModel(), and ~G4NeutronRadCapture().
G4IonTable* G4NeutronRadCapture::theTableOfIons private
Definition at line 74 of file G4NeutronRadCapture.hh.
View newest version in sPHENIX GitHub at line 74 of file G4NeutronRadCapture.hh
Referenced by ApplyYourself(), and G4NeutronRadCapture().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/include/G4NeutronRadCapture.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/photon_evaporation/src/G4NeutronRadCapture.cc