ECCE @ EIC Software: G4hhElastic Class Reference
G4hhElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4hhElastic.hh>
Public Member Functions
G4hhElastic ()
G4hhElastic (G4ParticleDefinition *target, G4ParticleDefinition *projectile, G4double plab)
G4hhElastic (G4ParticleDefinition *target, G4ParticleDefinition *projectile)
virtual ~G4hhElastic ()
virtual G4bool IsApplicable (const G4HadProjectile &, G4Nucleus &)
void Initialise ()
void BuildTableT (G4ParticleDefinition *target, G4ParticleDefinition *projectile)
void BuildTableTest (G4ParticleDefinition *target, G4ParticleDefinition *projectile, G4double plab)
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int, G4int)
G4double SampleBisectionalT (const G4ParticleDefinition *p, G4double plab)
G4double SampleTest (G4double tMin)
G4double GetTransfer (G4int iMomentum, G4int iTransfer, G4double position)
void SetParameters ()
void SetSigmaTot (G4double stot)
void SetSpp (G4double spp)
G4double GetSpp ()
void SetParametersCMS (G4double plab)
G4double GetBq ()
G4double GetBQ ()
G4double GetBqQ ()
void SetBq (G4double b)
void SetBQ (G4double b)
void SetBqQ (G4double b)
G4double GetRhoReIm ()
void CalculateBQ (G4double b)
void CalculateBqQ13 (G4double b)
void CalculateBqQ12 (G4double b)
void CalculateBqQ123 (G4double b)
void SetRA (G4double rn, G4double pq, G4double pQ)
void SetRB (G4double rn, G4double pq, G4double pQ)
void SetAlphaP (G4double a)
void SetImCof (G4double a)
G4double GetImCof ()
void SetLambda (G4double L)
void SetEta (G4double E)
void SetCofF2 (G4double f)
void SetCofF3 (G4double f)
G4double GetCofF2 ()
G4double GetCofF3 ()
G4double GetRA ()
G4double GetRq ()
G4double GetRQ ()
G4double GetRB ()
G4double GetRg ()
G4double GetRG ()
G4complex Pomeron ()
G4complex Phi13 ()
G4complex Phi14 ()
G4complex Phi23 ()
G4complex Phi24 ()
G4complex GetF1qQgG (G4double qp)
G4double GetdsdtF1qQgG (G4double s, G4double q)
G4complex GetF2qQgG (G4double qp)
G4double GetdsdtF12qQgG (G4double s, G4double q)
G4complex GetF3qQgG (G4double qp)
G4double GetdsdtF123qQgG (G4double q)
G4double GetdsdtF13qQG (G4double s, G4double q)
G4complex GetAqq ()
G4complex GetAQQ ()
G4complex GetAqQ ()
G4double GetCofS1 ()
G4double GetCofS2 ()
G4double GetCofS3 ()
G4double GetOpticalRatio ()
G4complex GetF1 (G4double qp)
G4double GetdsdtF1 (G4double s, G4double q)
G4complex GetF2 (G4double qp)
G4double GetdsdtF12 (G4double s, G4double q)
G4complex GetF3 (G4double qp)
G4double GetdsdtF123 (G4double q)
G4double GetExpRatioF123 (G4double s, G4double q)
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4ParticleDefinition * fTarget
G4ParticleDefinition * fProjectile
G4ParticleDefinition * theProton
G4ParticleDefinition * theNeutron
G4ParticleDefinition * thePionPlus
G4ParticleDefinition * thePionMinus
G4double lowEnergyRecoilLimit
G4double lowEnergyLimitHE
G4double lowEnergyLimitQ
G4double lowestEnergyLimit
G4double plabLowLimit
G4int fEnergyBin
G4int fBinT
G4PhysicsLogVector * fEnergyVector
G4PhysicsTable * fTableT
std::vector< G4PhysicsTable * > fBankT
G4double fMff2
G4double fMQ
G4double fMq
G4double fMassTarg
G4double fMassProj
G4double fMassSum2
G4double fMassDif2
G4double fRA
G4double fRQ
G4double fRq
G4double fAlpha
G4double fBeta
G4double fRB
G4double fRG
G4double fRg
G4double fGamma
G4double fDelta
G4double fAlphaP
G4double fLambdaFF
G4double fLambda
G4double fEta
G4double fImCof
G4double fCofF2
G4double fCofF3
G4double fRhoReIm
G4double fExpSlope
G4double fSo
G4double fSigmaTot
G4double fBq
G4double fBQ
G4double fBqQ
G4double fOptRatio
G4double fSpp
G4double fPcms
G4double fQcof
G4int fInTkin
G4double fOldTkin
G4HadronNucleonXsc * fHadrNuclXsc
Static Private Attributes
static const G4double theNuclNuclData [19][6]
static const G4double thePiKaNuclData [8][6]
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 61 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 61 of file G4hhElastic.hh
Constructor & Destructor Documentation
G4hhElastic::G4hhElastic ()
Definition at line 73 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 73 of file G4hhElastic.cc
References fBinT, fEnergyBin, fEnergyVector, fHadrNuclXsc, fInTkin, fOldTkin, fOptRatio, fPcms, fProjectile, fRhoReIm, fSigmaTot, fSpp, fTableT, fTarget, G4HadronicInteraction::GetMaxEnergy(), GeV, Initialise(), G4HadronicParameters::Instance(), keV, lowEnergyLimitHE, lowEnergyLimitQ, lowEnergyRecoilLimit, lowestEnergyLimit, MeV, G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), plabLowLimit, G4Proton::Proton(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), SetParameters(), G4HadronicInteraction::theMaxEnergy, G4HadronicInteraction::theMinEnergy, theNeutron, thePionMinus, thePionPlus, theProton, and G4HadronicInteraction::verboseLevel.
G4hhElastic::G4hhElastic (G4ParticleDefinition * target, G4ParticleDefinition * projectile, G4double plab)
Definition at line 114 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 114 of file G4hhElastic.cc
References fBinT, fEnergyBin, fEnergyVector, fHadrNuclXsc, fInTkin, fMassDif2, fMassProj, fMassSum2, fMassTarg, fOldTkin, fOptRatio, fPcms, fProjectile, fRhoReIm, fSigmaTot, fSpp, fTableT, fTarget, G4HadronicInteraction::GetMaxEnergy(), G4ParticleDefinition::GetPDGMass(), GeV, G4HadronicParameters::Instance(), keV, lowEnergyLimitHE, lowEnergyLimitQ, lowEnergyRecoilLimit, lowestEnergyLimit, MeV, G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), plabLowLimit, G4Proton::Proton(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), SetParameters(), SetParametersCMS(), G4HadronicInteraction::theMaxEnergy, G4HadronicInteraction::theMinEnergy, theNeutron, thePionMinus, thePionPlus, theProton, and G4HadronicInteraction::verboseLevel.
G4hhElastic::G4hhElastic (G4ParticleDefinition * target, G4ParticleDefinition * projectile)
Definition at line 159 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 159 of file G4hhElastic.cc
References fBinT, fEnergyBin, fEnergyVector, fHadrNuclXsc, fInTkin, fMassDif2, fMassProj, fMassSum2, fMassTarg, fOldTkin, fOptRatio, fPcms, fProjectile, fRhoReIm, fSigmaTot, fSpp, fTableT, fTarget, G4HadronicInteraction::GetMaxEnergy(), G4ParticleDefinition::GetPDGMass(), GeV, G4HadronicParameters::Instance(), keV, lowEnergyLimitHE, lowEnergyLimitQ, lowEnergyRecoilLimit, lowestEnergyLimit, MeV, G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), plabLowLimit, G4Proton::Proton(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), SetParameters(), G4HadronicInteraction::theMaxEnergy, G4HadronicInteraction::theMinEnergy, theNeutron, thePionMinus, thePionPlus, theProton, and G4HadronicInteraction::verboseLevel.
G4hhElastic::~G4hhElastic () virtual
Definition at line 205 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 205 of file G4hhElastic.cc
References fBankT, fEnergyVector, fHadrNuclXsc, fTableT, and it.
Member Function Documentation
void G4hhElastic::BuildTableT (G4ParticleDefinition * target, G4ParticleDefinition * projectile)
Definition at line 254 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 254 of file G4hhElastic.cc
References Acts::Test::delta, fBinT, fEnergyBin, fEnergyVector, fMassDif2, fMassProj, fMassSum2, fMassTarg, fPcms, fProjectile, fTableT, fTarget, GetdsdtF123(), GetdsdtF123qQgG(), G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGMass(), GeV, G4PhysicsTable::insertAt(), G4Integrator< T, F >::Legendre10(), MeV, G4PhysicsFreeVector::PutValue(), SetParametersCMS(), sum, t1, and t2.
Referenced by Initialise().
void G4hhElastic::BuildTableTest (G4ParticleDefinition * target, G4ParticleDefinition * projectile, G4double plab)
Definition at line 520 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 520 of file G4hhElastic.cc
References Acts::Test::delta, fBankT, fBinT, fMassDif2, fMassProj, fMassSum2, fMassTarg, fPcms, fProjectile, fSpp, fTableT, fTarget, G4cout, G4endl, GetdsdtF123(), GetdsdtF123qQgG(), G4ParticleDefinition::GetPDGMass(), GeV, G4PhysicsTable::insertAt(), G4Integrator< T, F >::Legendre10(), MeV, G4PhysicsFreeVector::PutValue(), sum, t1, and t2.
void G4hhElastic::CalculateBQ (G4double b) inline
Definition at line 957 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 957 of file G4hhElastic.hh
References a, A(), b, B(), c, D(), d, fBq, fBQ, fOptRatio, G4cout, G4endl, GetCofS1(), GetCofS2(), GetCofS3(), r1, r2, return(), s1, x1, x2, x3, y1, y2, and y3.
void G4hhElastic::CalculateBqQ12 (G4double b) inline
Definition at line 786 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 786 of file G4hhElastic.hh
References fBq, fBQ, fEta, fLambda, fSigmaTot, G4cout, G4endl, CLHEP::hbarc, Phi13(), Phi14(), Phi23(), Phi24(), CLHEP::pi, ratio, and return().
void G4hhElastic::CalculateBqQ123 (G4double b) inline
Definition at line 812 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 812 of file G4hhElastic.hh
References A(), kdfinder::abs(), B(), C(), e, fBq, fBQ, fCofF2, fCofF3, fEta, fLambda, fOptRatio, fSigmaTot, G4cout, G4endl, CLHEP::hbarc, Phi13(), Phi14(), Phi23(), Phi24(), CLHEP::pi, return(), x1, and x2.
void G4hhElastic::CalculateBqQ13 (G4double b) inline
Definition at line 763 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 763 of file G4hhElastic.hh
References fAlpha, fBQ, fBqQ, fSigmaTot, G4cout, G4endl, CLHEP::hbarc, Phi14(), Phi24(), CLHEP::pi, ratio, and return().
G4complex G4hhElastic::GetAqq () inline
Definition at line 867 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 867 of file G4hhElastic.hh
References fAlphaP, fImCof, fLambda, fRq, fSo, fSpp, G4Log(), and CLHEP::pi.
Referenced by GetAqQ(), GetCofS2(), GetF1(), GetF2(), and GetF3().
G4complex G4hhElastic::GetAQQ () inline
Definition at line 880 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 880 of file G4hhElastic.hh
References fAlphaP, fImCof, fLambda, fRQ, fSo, fSpp, G4Log(), and CLHEP::pi.
Referenced by GetAqQ(), GetCofS3(), GetF1(), GetF2(), and GetF3().
G4complex G4hhElastic::GetAqQ () inline
Definition at line 893 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 893 of file G4hhElastic.hh
References GetAqq(), GetAQQ(), and z.
Referenced by GetCofS1(), GetCofS2(), GetCofS3(), GetF1(), GetF2(), and GetF3().
G4double G4hhElastic::GetBq () inline
Definition at line 169 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 169 of file G4hhElastic.hh
References fBq.
G4double G4hhElastic::GetBQ () inline
Definition at line 170 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 170 of file G4hhElastic.hh
References fBQ.
G4double G4hhElastic::GetBqQ () inline
Definition at line 171 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 171 of file G4hhElastic.hh
References fBqQ.
G4double G4hhElastic::GetCofF2 () inline
Definition at line 191 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 191 of file G4hhElastic.hh
References fCofF2.
G4double G4hhElastic::GetCofF3 () inline
Definition at line 192 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 192 of file G4hhElastic.hh
References fCofF3.
G4double G4hhElastic::GetCofS1 () inline
Definition at line 903 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 903 of file G4hhElastic.hh
References fCofF2, fLambda, fSigmaTot, GetAqQ(), CLHEP::hbarc, CLHEP::pi, and z.
Referenced by CalculateBQ().
G4double G4hhElastic::GetCofS2 () inline
Definition at line 916 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 916 of file G4hhElastic.hh
References fCofF3, fLambda, fSigmaTot, GetAqq(), GetAqQ(), CLHEP::hbarc, CLHEP::pi, and z.
Referenced by CalculateBQ().
G4double G4hhElastic::GetCofS3 () inline
Definition at line 929 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 929 of file G4hhElastic.hh
References fCofF3, fLambda, fSigmaTot, GetAQQ(), GetAqQ(), CLHEP::hbarc, CLHEP::pi, and z.
Referenced by CalculateBQ().
G4double G4hhElastic::GetdsdtF1 (G4double s, G4double q) inline
Definition at line 1042 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 1042 of file G4hhElastic.hh
References F1, fSpp, GetF1(), CLHEP::pi, and CLHEP::proton_mass_c2.
G4double G4hhElastic::GetdsdtF12 (G4double s, G4double q) inline
Definition at line 1085 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 1085 of file G4hhElastic.hh
References F1, fSpp, GetF1(), GetF2(), CLHEP::pi, and CLHEP::proton_mass_c2.
G4double G4hhElastic::GetdsdtF123 (G4double q) inline
Definition at line 1128 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 1128 of file G4hhElastic.hh
References F1, fCofF2, fCofF3, fSpp, GetF1(), GetF2(), GetF3(), CLHEP::pi, and CLHEP::proton_mass_c2.
Referenced by BuildTableT(), and BuildTableTest().
G4double G4hhElastic::GetdsdtF123qQgG (G4double q) inline
Definition at line 746 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 746 of file G4hhElastic.hh
References fCofF2, fCofF3, fMassDif2, fMassSum2, fSpp, GetF1qQgG(), GetF2qQgG(), GetF3qQgG(), and CLHEP::pi.
Referenced by BuildTableT(), and BuildTableTest().
G4double G4hhElastic::GetdsdtF12qQgG (G4double s, G4double q) inline
Definition at line 676 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 676 of file G4hhElastic.hh
References F12, fMassDif2, fMassSum2, fSpp, GetF1qQgG(), GetF2qQgG(), and CLHEP::pi.
G4double G4hhElastic::GetdsdtF13qQG (G4double s, G4double q) inline
Definition at line 584 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 584 of file G4hhElastic.hh
References F1, F13, F3, fAlpha, fBeta, fBQ, fBqQ, fEta, fGamma, fLambda, fMassDif2, fMassSum2, fSigmaTot, fSpp, CLHEP::hbarc, k, Phi14(), Phi24(), and CLHEP::pi.
G4double G4hhElastic::GetdsdtF1qQgG (G4double s, G4double q) inline
Definition at line 627 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 627 of file G4hhElastic.hh
References F1, fMassDif2, fMassSum2, fSpp, GetF1qQgG(), and CLHEP::pi.
G4double G4hhElastic::GetExpRatioF123 (G4double s, G4double q) inline
Definition at line 1143 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 1143 of file G4hhElastic.hh
References F1, F10, fCofF2, fCofF3, fExpSlope, fRhoReIm, fSpp, G4Exp(), GetF1(), GetF2(), GetF3(), CLHEP::pi, CLHEP::proton_mass_c2, and ratio.
G4complex G4hhElastic::GetF1 (G4double qp) inline
Definition at line 1024 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 1024 of file G4hhElastic.hh
References fBq, fBQ, fSigmaTot, fSpp, GetAqq(), GetAQQ(), GetAqQ(), CLHEP::hbarc, k, CLHEP::pi, and CLHEP::proton_mass_c2.
Referenced by GetdsdtF1(), GetdsdtF12(), GetdsdtF123(), and GetExpRatioF123().
G4complex G4hhElastic::GetF1qQgG (G4double qp) inline
Definition at line 562 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 562 of file G4hhElastic.hh
References fAlpha, fBeta, fBq, fBQ, fDelta, fEta, fGamma, fLambda, fMassDif2, fMassSum2, fSigmaTot, fSpp, CLHEP::hbarc, k, Phi13(), Phi14(), Phi23(), Phi24(), and CLHEP::pi.
Referenced by GetdsdtF123qQgG(), GetdsdtF12qQgG(), and GetdsdtF1qQgG().
G4complex G4hhElastic::GetF2 (G4double qp) inline
Definition at line 1057 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 1057 of file G4hhElastic.hh
References fBq, fBQ, fLambda, fSigmaTot, fSpp, GetAqq(), GetAQQ(), GetAqQ(), CLHEP::hbarc, k, CLHEP::pi, CLHEP::proton_mass_c2, z1, and z2.
Referenced by GetdsdtF12(), GetdsdtF123(), and GetExpRatioF123().
G4complex G4hhElastic::GetF2qQgG (G4double qp) inline
Definition at line 643 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 643 of file G4hhElastic.hh
References fAlpha, fBq, fBQ, fDelta, fEta, fGamma, fLambda, fMassDif2, fMassSum2, fSigmaTot, fSpp, CLHEP::hbarc, k, Phi13(), Phi14(), Phi23(), Phi24(), and CLHEP::pi.
Referenced by GetdsdtF123qQgG(), and GetdsdtF12qQgG().
G4complex G4hhElastic::GetF3 (G4double qp) inline
Definition at line 1100 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 1100 of file G4hhElastic.hh
References fBq, fBQ, fLambda, fSigmaTot, fSpp, GetAqq(), GetAQQ(), GetAqQ(), CLHEP::hbarc, k, CLHEP::pi, CLHEP::proton_mass_c2, z1, and z2.
Referenced by GetdsdtF123(), and GetExpRatioF123().
G4complex G4hhElastic::GetF3qQgG (G4double qp) inline
Definition at line 692 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 692 of file G4hhElastic.hh
References fAlpha, fBeta, fBq, fBQ, fDelta, fEta, fGamma, fLambda, fMassDif2, fMassSum2, fSigmaTot, fSpp, CLHEP::hbarc, k, Phi13(), Phi14(), Phi23(), Phi24(), and CLHEP::pi.
Referenced by GetdsdtF123qQgG().
G4double G4hhElastic::GetImCof () inline
Definition at line 186 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 186 of file G4hhElastic.hh
References fImCof.
G4double G4hhElastic::GetOpticalRatio () inline
Definition at line 942 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 942 of file G4hhElastic.hh
References fOptRatio.
G4double G4hhElastic::GetRA () inline
Definition at line 194 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 194 of file G4hhElastic.hh
References fRA.
Referenced by SetParametersCMS().
G4double G4hhElastic::GetRB () inline
Definition at line 198 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 198 of file G4hhElastic.hh
References fRB.
Referenced by SetParametersCMS().
G4double G4hhElastic::GetRg () inline
Definition at line 199 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 199 of file G4hhElastic.hh
References fRg.
G4double G4hhElastic::GetRG () inline
Definition at line 200 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 200 of file G4hhElastic.hh
References fRG.
G4double G4hhElastic::GetRhoReIm () inline
Definition at line 175 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 175 of file G4hhElastic.hh
References fRhoReIm.
G4double G4hhElastic::GetRq () inline
Definition at line 195 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 195 of file G4hhElastic.hh
References fRq.
G4double G4hhElastic::GetRQ () inline
Definition at line 196 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 196 of file G4hhElastic.hh
References fRQ.
G4double G4hhElastic::GetSpp () inline
Definition at line 166 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 166 of file G4hhElastic.hh
References fSpp.
G4double G4hhElastic::GetTransfer (G4int iMomentum, G4int iTransfer, G4double position)
Definition at line 629 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 629 of file G4hhElastic.cc
References Acts::Test::delta, epsilon(), fTableT, G4UniformRand, x1, x2, y1, and y2.
Referenced by SampleBisectionalT(), SampleInvariantT(), and SampleTest().
void G4hhElastic::Initialise ()
Definition at line 230 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 230 of file G4hhElastic.cc
References BuildTableT(), fBankT, fProjectile, fTableT, fTarget, G4KaonPlus::KaonPlus(), G4PionPlus::PionPlus(), and G4Proton::Proton().
Referenced by G4hhElastic().
G4bool G4hhElastic::IsApplicable (const G4HadProjectile & projectile, G4Nucleus & nucleus) inline virtual
Reimplemented from G4HadronicInteraction.
Definition at line 256 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 256 of file G4hhElastic.hh
References G4HadProjectile::GetDefinition(), G4Nucleus::GetZ_asInt(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), and G4Proton::Proton().
G4complex G4hhElastic::Phi13 () inline
Definition at line 520 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 520 of file G4hhElastic.hh
References fRg, fRq, and Pomeron().
Referenced by CalculateBqQ12(), CalculateBqQ123(), GetF1qQgG(), GetF2qQgG(), and GetF3qQgG().
G4complex G4hhElastic::Phi14 () inline
Definition at line 530 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 530 of file G4hhElastic.hh
References fRG, fRq, and Pomeron().
Referenced by CalculateBqQ12(), CalculateBqQ123(), CalculateBqQ13(), GetdsdtF13qQG(), GetF1qQgG(), GetF2qQgG(), and GetF3qQgG().
G4complex G4hhElastic::Phi23 () inline
Definition at line 540 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 540 of file G4hhElastic.hh
References fRg, fRQ, and Pomeron().
Referenced by CalculateBqQ12(), CalculateBqQ123(), GetF1qQgG(), GetF2qQgG(), and GetF3qQgG().
G4complex G4hhElastic::Phi24 () inline
Definition at line 550 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 550 of file G4hhElastic.hh
References fRG, fRQ, and Pomeron().
Referenced by CalculateBqQ12(), CalculateBqQ123(), CalculateBqQ13(), GetdsdtF13qQG(), GetF1qQgG(), GetF2qQgG(), and GetF3qQgG().
G4complex G4hhElastic::Pomeron () inline
Definition at line 509 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 509 of file G4hhElastic.hh
References fAlphaP, fImCof, fSo, fSpp, G4Log(), and CLHEP::pi.
Referenced by Phi13(), Phi14(), Phi23(), and Phi24().
G4double G4hhElastic::SampleBisectionalT (const G4ParticleDefinition * p, G4double plab)
Definition at line 439 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 439 of file G4hhElastic.cc
References kdfinder::abs(), Acts::Test::delta, fBankT, fBinT, fEnergyBin, fInTkin, fOldTkin, fTableT, G4UniformRand, G4ParticleDefinition::GetPDGMass(), GetTransfer(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), position, G4Proton::Proton(), t, and y2.
G4double G4hhElastic::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int , G4int) virtual
Reimplemented from G4HadronElastic.
Definition at line 322 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 322 of file G4hhElastic.cc
References kdfinder::abs(), Acts::Test::delta, fBankT, fBinT, fEnergyBin, fInTkin, fOldTkin, fTableT, G4UniformRand, G4ParticleDefinition::GetPDGMass(), GetTransfer(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4Neutron::Neutron(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), position, G4Proton::Proton(), t, and t2.
G4double G4hhElastic::SampleTest (G4double tMin)
Definition at line 593 of file G4hhElastic.cc.
View newest version in sPHENIX GitHub at line 593 of file G4hhElastic.cc
References fBankT, fBinT, fTableT, G4UniformRand, GetTransfer(), position, and t.
void G4hhElastic::SetAlphaP (G4double a) inline
Definition at line 184 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 184 of file G4hhElastic.hh
References a, and fAlphaP.
void G4hhElastic::SetBq (G4double b) inline
Definition at line 172 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 172 of file G4hhElastic.hh
References b, and fBq.
Referenced by SetParametersCMS().
void G4hhElastic::SetBQ (G4double b) inline
Definition at line 173 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 173 of file G4hhElastic.hh
References b, and fBQ.
Referenced by SetParametersCMS().
void G4hhElastic::SetBqQ (G4double b) inline
Definition at line 174 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 174 of file G4hhElastic.hh
References b, and fBqQ.
void G4hhElastic::SetCofF2 (G4double f) inline
Definition at line 189 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 189 of file G4hhElastic.hh
References f, and fCofF2.
Referenced by SetParametersCMS().
void G4hhElastic::SetCofF3 (G4double f) inline
Definition at line 190 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 190 of file G4hhElastic.hh
References f, and fCofF3.
Referenced by SetParametersCMS().
void G4hhElastic::SetEta (G4double E) inline
Definition at line 188 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 188 of file G4hhElastic.hh
References E, and fEta.
Referenced by SetParametersCMS().
void G4hhElastic::SetImCof (G4double a) inline
Definition at line 185 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 185 of file G4hhElastic.hh
References a, and fImCof.
Referenced by SetParametersCMS().
void G4hhElastic::SetLambda (G4double L) inline
Definition at line 187 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 187 of file G4hhElastic.hh
References fLambda, and L.
Referenced by SetParametersCMS().
void G4hhElastic::SetParameters () inline
Definition at line 271 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 271 of file G4hhElastic.hh
References fAlpha, fAlphaP, fBeta, fBq, fBQ, fBqQ, fCofF2, fCofF3, fDelta, fEta, fExpSlope, fGamma, fImCof, fLambda, fLambdaFF, fMff2, fMQ, fMq, fQcof, fRA, fRB, fRG, fRg, fRQ, fRq, fSo, and CLHEP::GeV.
Referenced by G4hhElastic().
void G4hhElastic::SetParametersCMS (G4double plab) inline
Definition at line 316 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 316 of file G4hhElastic.hh
References fDelta, fGamma, fHadrNuclXsc, fMassDif2, fMassProj, fMassSum2, fMassTarg, fPcms, fProjectile, fSigmaTot, fSpp, fTarget, G4HadronNucleonXsc::GetHadronNucleonXscNS(), GetRA(), GetRB(), CLHEP::GeV, CLHEP::MeV, SetBq(), SetBQ(), SetCofF2(), SetCofF3(), SetEta(), SetImCof(), SetLambda(), SetRA(), SetRB(), theNuclNuclData, and thePiKaNuclData.
Referenced by BuildTableT(), and G4hhElastic().
void G4hhElastic::SetRA (G4double rn, G4double pq, G4double pQ) inline
Definition at line 487 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 487 of file G4hhElastic.hh
References fRA, fRQ, and fRq.
Referenced by SetParametersCMS().
void G4hhElastic::SetRB (G4double rn, G4double pq, G4double pQ) inline
Definition at line 498 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 498 of file G4hhElastic.hh
References fRB, fRG, fRg, and demo::pg.
Referenced by SetParametersCMS().
void G4hhElastic::SetSigmaTot (G4double stot) inline
Definition at line 164 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 164 of file G4hhElastic.hh
References fSigmaTot.
void G4hhElastic::SetSpp (G4double spp) inline
Definition at line 165 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 165 of file G4hhElastic.hh
References fSpp.
Member Data Documentation
G4double G4hhElastic::fAlpha private
Definition at line 132 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 132 of file G4hhElastic.hh
Referenced by CalculateBqQ13(), GetdsdtF13qQG(), GetF1qQgG(), GetF2qQgG(), GetF3qQgG(), and SetParameters().
G4double G4hhElastic::fAlphaP private
Definition at line 141 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 141 of file G4hhElastic.hh
Referenced by GetAqq(), GetAQQ(), Pomeron(), SetAlphaP(), and SetParameters().
std::vector<G4PhysicsTable*> G4hhElastic::fBankT private
Definition at line 113 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 113 of file G4hhElastic.hh
Referenced by BuildTableTest(), Initialise(), SampleBisectionalT(), SampleInvariantT(), SampleTest(), and ~G4hhElastic().
G4double G4hhElastic::fBeta private
Definition at line 133 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 133 of file G4hhElastic.hh
Referenced by GetdsdtF13qQG(), GetF1qQgG(), GetF3qQgG(), and SetParameters().
G4int G4hhElastic::fBinT private
Definition at line 109 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 109 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), SampleBisectionalT(), SampleInvariantT(), and SampleTest().
G4double G4hhElastic::fBq private
Definition at line 153 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 153 of file G4hhElastic.hh
Referenced by CalculateBQ(), CalculateBqQ12(), CalculateBqQ123(), GetBq(), GetF1(), GetF1qQgG(), GetF2(), GetF2qQgG(), GetF3(), GetF3qQgG(), SetBq(), and SetParameters().
G4double G4hhElastic::fBQ private
Definition at line 154 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 154 of file G4hhElastic.hh
Referenced by CalculateBQ(), CalculateBqQ12(), CalculateBqQ123(), CalculateBqQ13(), GetBQ(), GetdsdtF13qQG(), GetF1(), GetF1qQgG(), GetF2(), GetF2qQgG(), GetF3(), GetF3qQgG(), SetBQ(), and SetParameters().
G4double G4hhElastic::fBqQ private
Definition at line 155 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 155 of file G4hhElastic.hh
Referenced by CalculateBqQ13(), GetBqQ(), GetdsdtF13qQG(), SetBqQ(), and SetParameters().
G4double G4hhElastic::fCofF2 private
Definition at line 146 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 146 of file G4hhElastic.hh
Referenced by CalculateBqQ123(), GetCofF2(), GetCofS1(), GetdsdtF123(), GetdsdtF123qQgG(), GetExpRatioF123(), SetCofF2(), and SetParameters().
G4double G4hhElastic::fCofF3 private
Definition at line 147 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 147 of file G4hhElastic.hh
Referenced by CalculateBqQ123(), GetCofF3(), GetCofS2(), GetCofS3(), GetdsdtF123(), GetdsdtF123qQgG(), GetExpRatioF123(), SetCofF3(), and SetParameters().
G4double G4hhElastic::fDelta private
Definition at line 139 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 139 of file G4hhElastic.hh
Referenced by GetF1qQgG(), GetF2qQgG(), GetF3qQgG(), SetParameters(), and SetParametersCMS().
G4int G4hhElastic::fEnergyBin private
Definition at line 108 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 108 of file G4hhElastic.hh
Referenced by BuildTableT(), G4hhElastic(), SampleBisectionalT(), and SampleInvariantT().
G4PhysicsLogVector* G4hhElastic::fEnergyVector private
Definition at line 111 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 111 of file G4hhElastic.hh
Referenced by BuildTableT(), G4hhElastic(), and ~G4hhElastic().
G4double G4hhElastic::fEta private
Definition at line 144 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 144 of file G4hhElastic.hh
Referenced by CalculateBqQ12(), CalculateBqQ123(), GetdsdtF13qQG(), GetF1qQgG(), GetF2qQgG(), GetF3qQgG(), SetEta(), and SetParameters().
G4double G4hhElastic::fExpSlope private
Definition at line 149 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 149 of file G4hhElastic.hh
Referenced by GetExpRatioF123(), and SetParameters().
G4double G4hhElastic::fGamma private
Definition at line 138 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 138 of file G4hhElastic.hh
Referenced by GetdsdtF13qQG(), GetF1qQgG(), GetF2qQgG(), GetF3qQgG(), SetParameters(), and SetParametersCMS().
G4HadronNucleonXsc* G4hhElastic::fHadrNuclXsc private
Definition at line 247 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 247 of file G4hhElastic.hh
Referenced by G4hhElastic(), SetParametersCMS(), and ~G4hhElastic().
G4double G4hhElastic::fImCof private
Definition at line 145 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 145 of file G4hhElastic.hh
Referenced by GetAqq(), GetAQQ(), GetImCof(), Pomeron(), SetImCof(), and SetParameters().
G4int G4hhElastic::fInTkin private
Definition at line 243 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 243 of file G4hhElastic.hh
Referenced by G4hhElastic(), SampleBisectionalT(), and SampleInvariantT().
G4double G4hhElastic::fLambda private
Definition at line 143 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 143 of file G4hhElastic.hh
Referenced by CalculateBqQ12(), CalculateBqQ123(), GetAqq(), GetAQQ(), GetCofS1(), GetCofS2(), GetCofS3(), GetdsdtF13qQG(), GetF1qQgG(), GetF2(), GetF2qQgG(), GetF3(), GetF3qQgG(), SetLambda(), and SetParameters().
G4double G4hhElastic::fLambdaFF private
Definition at line 142 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 142 of file G4hhElastic.hh
Referenced by SetParameters().
G4double G4hhElastic::fMassDif2 private
Definition at line 126 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 126 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), GetdsdtF123qQgG(), GetdsdtF12qQgG(), GetdsdtF13qQG(), GetdsdtF1qQgG(), GetF1qQgG(), GetF2qQgG(), GetF3qQgG(), and SetParametersCMS().
G4double G4hhElastic::fMassProj private
Definition at line 124 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 124 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), and SetParametersCMS().
G4double G4hhElastic::fMassSum2 private
Definition at line 125 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 125 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), GetdsdtF123qQgG(), GetdsdtF12qQgG(), GetdsdtF13qQG(), GetdsdtF1qQgG(), GetF1qQgG(), GetF2qQgG(), GetF3qQgG(), and SetParametersCMS().
G4double G4hhElastic::fMassTarg private
Definition at line 123 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 123 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), and SetParametersCMS().
G4double G4hhElastic::fMff2 private
Definition at line 119 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 119 of file G4hhElastic.hh
Referenced by SetParameters().
G4double G4hhElastic::fMQ private
Definition at line 120 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 120 of file G4hhElastic.hh
Referenced by SetParameters().
G4double G4hhElastic::fMq private
Definition at line 121 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 121 of file G4hhElastic.hh
Referenced by SetParameters().
G4double G4hhElastic::fOldTkin private
Definition at line 244 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 244 of file G4hhElastic.hh
Referenced by G4hhElastic(), SampleBisectionalT(), and SampleInvariantT().
G4double G4hhElastic::fOptRatio private
Definition at line 156 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 156 of file G4hhElastic.hh
Referenced by CalculateBQ(), CalculateBqQ123(), G4hhElastic(), and GetOpticalRatio().
G4double G4hhElastic::fPcms private
Definition at line 158 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 158 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), and SetParametersCMS().
G4ParticleDefinition* G4hhElastic::fProjectile private
Definition at line 95 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 95 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), Initialise(), and SetParametersCMS().
G4double G4hhElastic::fQcof private
Definition at line 159 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 159 of file G4hhElastic.hh
Referenced by SetParameters().
G4double G4hhElastic::fRA private
Definition at line 129 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 129 of file G4hhElastic.hh
Referenced by GetRA(), SetParameters(), and SetRA().
G4double G4hhElastic::fRB private
Definition at line 135 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 135 of file G4hhElastic.hh
Referenced by GetRB(), SetParameters(), and SetRB().
G4double G4hhElastic::fRG private
Definition at line 136 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 136 of file G4hhElastic.hh
Referenced by GetRG(), Phi14(), Phi24(), SetParameters(), and SetRB().
G4double G4hhElastic::fRg private
Definition at line 137 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 137 of file G4hhElastic.hh
Referenced by GetRg(), Phi13(), Phi23(), SetParameters(), and SetRB().
G4double G4hhElastic::fRhoReIm private
Definition at line 148 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 148 of file G4hhElastic.hh
Referenced by G4hhElastic(), GetExpRatioF123(), and GetRhoReIm().
G4double G4hhElastic::fRQ private
Definition at line 130 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 130 of file G4hhElastic.hh
Referenced by GetAQQ(), GetRQ(), Phi23(), Phi24(), SetParameters(), and SetRA().
G4double G4hhElastic::fRq private
Definition at line 131 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 131 of file G4hhElastic.hh
Referenced by GetAqq(), GetRq(), Phi13(), Phi14(), SetParameters(), and SetRA().
G4double G4hhElastic::fSigmaTot private
Definition at line 152 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 152 of file G4hhElastic.hh
Referenced by CalculateBqQ12(), CalculateBqQ123(), CalculateBqQ13(), G4hhElastic(), GetCofS1(), GetCofS2(), GetCofS3(), GetdsdtF13qQG(), GetF1(), GetF1qQgG(), GetF2(), GetF2qQgG(), GetF3(), GetF3qQgG(), SetParametersCMS(), and SetSigmaTot().
G4double G4hhElastic::fSo private
Definition at line 150 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 150 of file G4hhElastic.hh
Referenced by GetAqq(), GetAQQ(), Pomeron(), and SetParameters().
G4double G4hhElastic::fSpp private
Definition at line 157 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 157 of file G4hhElastic.hh
Referenced by BuildTableTest(), G4hhElastic(), GetAqq(), GetAQQ(), GetdsdtF1(), GetdsdtF12(), GetdsdtF123(), GetdsdtF123qQgG(), GetdsdtF12qQgG(), GetdsdtF13qQG(), GetdsdtF1qQgG(), GetExpRatioF123(), GetF1(), GetF1qQgG(), GetF2(), GetF2qQgG(), GetF3(), GetF3qQgG(), GetSpp(), Pomeron(), SetParametersCMS(), and SetSpp().
G4PhysicsTable* G4hhElastic::fTableT private
Definition at line 112 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 112 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), GetTransfer(), Initialise(), SampleBisectionalT(), SampleInvariantT(), SampleTest(), and ~G4hhElastic().
G4ParticleDefinition* G4hhElastic::fTarget private
Definition at line 94 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 94 of file G4hhElastic.hh
Referenced by BuildTableT(), BuildTableTest(), G4hhElastic(), Initialise(), and SetParametersCMS().
G4double G4hhElastic::lowEnergyLimitHE private
Definition at line 103 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 103 of file G4hhElastic.hh
Referenced by G4hhElastic().
G4double G4hhElastic::lowEnergyLimitQ private
Definition at line 104 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 104 of file G4hhElastic.hh
Referenced by G4hhElastic().
G4double G4hhElastic::lowEnergyRecoilLimit private
Definition at line 102 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 102 of file G4hhElastic.hh
Referenced by G4hhElastic().
G4double G4hhElastic::lowestEnergyLimit private
Definition at line 105 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 105 of file G4hhElastic.hh
Referenced by G4hhElastic().
G4double G4hhElastic::plabLowLimit private
Definition at line 106 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 106 of file G4hhElastic.hh
Referenced by G4hhElastic().
G4ParticleDefinition* G4hhElastic::theNeutron private
Definition at line 97 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 97 of file G4hhElastic.hh
Referenced by G4hhElastic().
const G4double G4hhElastic::theNuclNuclData static private
Initial value:
=
{
  { 2.76754,  4.8,  4.8,  0.05, 0.742441, 10.5 },
  { 3.07744,  5.4,  5.4,  0.02, 0.83818,  6.5  },
  { 3.36305,  5.2,  5.2,  0.02, 0.838893, 7.5  },
  { 4.32941,  6,  6,  0.03, 0.769389, 7.5  },
  { 4.62126,  6,  6,  0.03, 0.770111, 6.5  },
  { 5.47416,  4.5,  4.5,  0.03, 0.813185, 7.5  },
  { 6.15088,  6.5,  6.5,  0.02, 0.799539, 6.5  },
  { 6.77474,  5.2,  5.2,  0.03, 0.784901, 7.5  },
  { 9.77775,  7,  7,  0.03, 0.742531, 6.5  },
  { 10.4728,  5.2,  5.2,  0.03, 0.780439, 7.5  },
  { 13.7631,  7,  7,  0.008,  0.8664,         5.0  },
  { 19.4184,  6.8,  6.8,  0.009,  0.861337, 2.5  },
  { 23.5, 6.8,  6.8,  0.007,  0.878112, 1.5  },
  { 24.1362,  7.2,  7.2,  0.008,  0.864745, 5.5  },
  { 52.8, 6.8,  6.8,  0.008,  0.871929, 1.5  },
  { 546,        7.4,  7.4,  0.013,  0.845877, 5.5  },
  { 1960, 7.8,  7.8,  0.022,  0.809062, 7.5  },
  { 7000, 8,  8,  0.024,  0.820441, 5.5  },
  { 13000,  8.5,  8.5,  0.03, 0.796721, 10.5  }
}
Definition at line 245 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 245 of file G4hhElastic.hh
Referenced by SetParametersCMS().
const G4double G4hhElastic::thePiKaNuclData static private
Initial value:
=
{
  { 2.5627,     3.8,    3.3,    0.22,   0.222,          1.5 },
  { 2.93928,    4.3,    3.8,    0.2,    0.250601,       1.3 },
  { 3.22326,  4.8,  4.3,  0.13, 0.32751,  2.5 },
  { 7.80704,  5.5,  5,  0.13, 0.340631, 2.5 },
  { 9.7328, 5,  4.5,  0.05, 0.416319, 5.5  },
  { 13.7315,  5.3,  4.8,  0.05, 0.418426, 5.5  },
  { 16.6359,  6.3,  5.8,  0.05, 0.423817, 5.5  },
  { 19.3961,  5,  4.5,  0.05, 0.413477, 3.5  }
}
Definition at line 246 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 246 of file G4hhElastic.hh
Referenced by SetParametersCMS().
G4ParticleDefinition* G4hhElastic::thePionMinus private
Definition at line 99 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 99 of file G4hhElastic.hh
Referenced by G4hhElastic().
G4ParticleDefinition* G4hhElastic::thePionPlus private
Definition at line 98 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 98 of file G4hhElastic.hh
Referenced by G4hhElastic().
G4ParticleDefinition* G4hhElastic::theProton private
Definition at line 96 of file G4hhElastic.hh.
View newest version in sPHENIX GitHub at line 96 of file G4hhElastic.hh
Referenced by G4hhElastic().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4hhElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4hhElastic.cc