ECCE @ EIC Software: G4HepRepSceneHandler Class Reference
G4HepRepSceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/G4HepRepSceneHandler.hh>
Public Member Functions
G4HepRepSceneHandler (G4VGraphicsSystem &system, const G4String &name="")
virtual ~G4HepRepSceneHandler ()
void AddSolid (const G4Box &box)
void AddSolid (const G4Cons &cons)
void AddSolid (const G4Tubs &tubs)
void AddSolid (const G4Trd &trd)
void AddSolid (const G4Trap &trap)
void AddSolid (const G4Sphere &sphere)
void AddSolid (const G4Para &para)
void AddSolid (const G4Torus &torus)
void AddSolid (const G4Polycone &polycone)
void AddSolid (const G4Polyhedra &polyhedra)
void AddSolid (const G4Orb &orb)
void AddSolid (const G4Ellipsoid &ellipsoid)
void AddSolid (const G4TessellatedSolid &tess)
void AddSolid (const G4VSolid &solid)
void AddCompound (const G4VTrajectory &)
void AddCompound (const G4VHit &hit)
void AddCompound (const G4VDigi &digi)
void AddCompound (const G4THitsMap< G4double > &hits)
void AddCompound (const G4THitsMap< G4StatDouble > &hits)
void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &visAttribs)
void PostAddSolid ()
void AddPrimitive (const G4Polyline &)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polyhedron &)
void AddPrimitive (const G4Polymarker &)
void AddPrimitive (const G4Scale &scale)
void BeginPrimitives (const G4Transform3D &objectTransformation)
void EndPrimitives ()
void BeginModeling ()
void EndModeling ()
void openHepRep ()
bool closeHepRep (bool final=false)
void openFile (G4String name)
void closeFile ()
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearStore ()
virtual void ClearTransientStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Private Member Functions
G4HepRepSceneHandler (const G4HepRepSceneHandler &)
G4HepRepSceneHandler & operator= (const G4HepRepSceneHandler &)
G4bool dontWrite ()
void setColor (HEPREP::HepRepAttribute *attribute, const G4Color &color, const G4String &key=G4String("Color"))
G4Color getColorFor (const G4Visible &visible)
G4Color getColorFor (const G4VSolid &solid)
void setVisibility (HEPREP::HepRepAttribute *attribute, const G4VSolid &solid)
void setLine (HEPREP::HepRepAttribute *attribute, const G4VSolid &solid)
void setVisibility (HEPREP::HepRepAttribute *attribute, const G4Visible &visible)
void setLine (HEPREP::HepRepAttribute *attribute, const G4Visible &visible)
void setMarker (HEPREP::HepRepAttribute *attribute, const G4VMarker &marker)
void setAttribute (HEPREP::HepRepAttribute *attribute, G4String name, char *value)
void setAttribute (HEPREP::HepRepAttribute *attribute, G4String name, G4String value)
void setAttribute (HEPREP::HepRepAttribute *attribute, G4String name, bool value)
void setAttribute (HEPREP::HepRepAttribute *attribute, G4String name, double value)
void setAttribute (HEPREP::HepRepAttribute *attribute, G4String name, int value)
void setAttribute (HEPREP::HepRepAttribute *attribute, G4String name, double red, double green, double blue, double alpha)
bool isEventData ()
void open (G4String name)
void close ()
void writeLayers (HEPREP::HepRep *heprep)
void addAttributes (HEPREP::HepRepInstance *instance, HEPREP::HepRepType *type)
void addAttDefs (HEPREP::HepRepDefinition *definition, const std::map< G4String, G4AttDef > *attDefs)
void addAttVals (HEPREP::HepRepAttribute *attribute, const std::map< G4String, G4AttDef > *attDefs, std::vector< G4AttValue > *attValues)
void addTopLevelAttributes (HEPREP::HepRepType *type)
HEPREP::HepRepInstance * getGeometryOrEventInstance (HEPREP::HepRepType *type)
HEPREP::HepRep * getHepRep ()
HEPREP::HepRep * getHepRepGeometry ()
HEPREP::HepRepInstanceTree * getGeometryInstanceTree ()
HEPREP::HepRepInstance * getGeometryInstance (G4LogicalVolume *volume, G4Material *material, int depth)
HEPREP::HepRepInstance * getGeometryInstance (G4String volumeName, int depth)
HEPREP::HepRepInstance * getGeometryRootInstance ()
HEPREP::HepRepTypeTree * getGeometryTypeTree ()
HEPREP::HepRepType * getGeometryType (G4String volumeName, int depth)
HEPREP::HepRepType * getGeometryRootType ()
HEPREP::HepRepInstanceTree * getEventInstanceTree ()
HEPREP::HepRepInstance * getEventInstance ()
HEPREP::HepRepTypeTree * getEventTypeTree ()
HEPREP::HepRepType * getEventType ()
HEPREP::HepRepType * getTrajectoryType ()
HEPREP::HepRepType * getHitType ()
HEPREP::HepRepType * getCalHitType ()
HEPREP::HepRepType * getCalHitFaceType ()
G4String getFullTypeName (G4String volumeName, int depth)
G4String getParentTypeName (int currentDepth)
Private Attributes
G4Transform3D transform
std::ostream * out
HEPREP::HepRepFactory * factory
HEPREP::HepRepWriter * writer
G4String geometryLayer
G4String eventLayer
G4String calHitLayer
G4String trajectoryLayer
G4String hitLayer
G4String rootVolumeName
G4String baseName
G4String eventNumberPrefix
G4String eventNumberSuffix
G4int eventNumber
G4int eventNumberWidth
G4String extension
G4bool writeBinary
G4bool writeZip
G4bool writeGZ
G4bool writeMultipleFiles
const G4VHit * currentHit
const G4VTrajectory * currentTrack
HEPREP::HepRep * _heprep
HEPREP::HepRep * _heprepGeometry
HEPREP::HepRepInstanceTree * _geometryInstanceTree
std::vector
< HEPREP::HepRepInstance * > _geometryInstance
HEPREP::HepRepInstance * _geometryRootInstance
HEPREP::HepRepTypeTree * _geometryTypeTree
std::vector< G4String > _geometryTypeName
std::map< G4String,
HEPREP::HepRepType * > _geometryType
HEPREP::HepRepType * _geometryRootType
HEPREP::HepRepInstanceTree * _eventInstanceTree
HEPREP::HepRepInstance * _eventInstance
HEPREP::HepRepTypeTree * _eventTypeTree
HEPREP::HepRepType * _eventType
HEPREP::HepRepType * _trajectoryType
HEPREP::HepRepType * _hitType
HEPREP::HepRepType * _calHitType
HEPREP::HepRepType * _calHitFaceType
std::map< int, G4String > materialState
Static Private Attributes
static G4int sceneIdCount = 0
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Detailed Description
Author
Mark Donszelmann
Definition at line 63 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 63 of file G4HepRepSceneHandler.hh
Constructor & Destructor Documentation
G4HepRepSceneHandler::G4HepRepSceneHandler (G4VGraphicsSystem & system, const G4String & name = "")
Definition at line 92 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 92 of file G4HepRepSceneHandler.cc
References factory, kStateGas, kStateLiquid, kStateSolid, kStateUndefined, materialState, openHepRep(), and writer.
G4HepRepSceneHandler::~G4HepRepSceneHandler () virtual
Definition at line 134 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 134 of file G4HepRepSceneHandler.cc
References close(), factory, G4VSceneHandler::GetGraphicsSystem(), and G4HepRep::removeSceneHandler().
G4HepRepSceneHandler::G4HepRepSceneHandler (const G4HepRepSceneHandler &) private
Member Function Documentation
void G4HepRepSceneHandler::addAttDefs (HEPREP::HepRepDefinition * definition, const std::map< G4String, G4AttDef > * attDefs) private
Definition at line 1302 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1302 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepDefinition::addAttDef().
Referenced by addAttributes().
void G4HepRepSceneHandler::addAttributes (HEPREP::HepRepInstance * instance, HEPREP::HepRepType * type) private
Definition at line 1142 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1142 of file G4HepRepSceneHandler.cc
References addAttDefs(), addAttVals(), HEPREP::HepRepAttribute::addAttValue(), G4VHit::CreateAttValues(), G4VTrajectory::CreateAttValues(), currentHit, currentTrack, G4VHit::GetAttDefs(), G4VTrajectory::GetAttDefs(), and getHitType().
Referenced by AddPrimitive(), and AddSolid().
void G4HepRepSceneHandler::addAttVals (HEPREP::HepRepAttribute * attribute, const std::map< G4String, G4AttDef > * attDefs, std::vector< G4AttValue > * attValues) private
Definition at line 1314 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1314 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepPoint::getX(), in, int(), pos(), and setAttribute().
Referenced by addAttributes().
void G4HepRepSceneHandler::AddCompound (const G4VTrajectory & trajectory) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1005 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1005 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddCompound(), currentTrack, and dontWrite().
void G4HepRepSceneHandler::AddCompound (const G4VHit & hit) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1017 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1017 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddCompound(), currentHit, and dontWrite().
void G4HepRepSceneHandler::AddCompound (const G4VDigi & digi) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 86 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 86 of file G4HepRepSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4HepRepSceneHandler::AddCompound (const G4THitsMap< G4double > & hits) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 89 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 89 of file G4HepRepSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4HepRepSceneHandler::AddCompound (const G4THitsMap< G4StatDouble > & hits) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 92 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 92 of file G4HepRepSceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4HepRepSceneHandler::AddPrimitive (const G4Polyline & line) virtual
Implements G4VSceneHandler.
Definition at line 755 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 755 of file G4HepRepSceneHandler.cc
References addAttributes(), HEPREP::HepRepFactory::createHepRepInstance(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), factory, G4VSceneHandler::fProcessing2D, G4VSceneHandler::fpVisAttribs, G4Exception(), G4VSceneHandler::GetColor(), getEventInstance(), getTrajectoryType(), G4Visible::GetVisAttributes(), instance, JustWarning, setColor(), setLine(), setVisibility(), transform, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepSceneHandler::AddPrimitive (const G4Text &) virtual
Implements G4VSceneHandler.
Definition at line 943 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 943 of file G4HepRepSceneHandler.cc
References dontWrite().
void G4HepRepSceneHandler::AddPrimitive (const G4Circle & circle) virtual
Implements G4VSceneHandler.
Definition at line 844 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 844 of file G4HepRepSceneHandler.cc
References addAttributes(), HEPREP::HepRepFactory::createHepRepInstance(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), factory, G4VSceneHandler::fProcessing2D, G4VSceneHandler::fpVisAttribs, G4Exception(), G4VSceneHandler::GetColor(), getEventInstance(), getHitType(), G4VMarker::GetPosition(), G4Visible::GetVisAttributes(), instance, JustWarning, setColor(), setMarker(), setVisibility(), transform, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepSceneHandler::AddPrimitive (const G4Square & square) virtual
Implements G4VSceneHandler.
Definition at line 967 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 967 of file G4HepRepSceneHandler.cc
References addAttributes(), HEPREP::HepRepFactory::createHepRepInstance(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), factory, G4VSceneHandler::fProcessing2D, G4Exception(), getColorFor(), getEventInstance(), getHitType(), G4VMarker::GetPosition(), instance, JustWarning, setColor(), setMarker(), setVisibility(), transform, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepSceneHandler::AddPrimitive (const G4Polyhedron & polyhedron) virtual
Implements G4VSceneHandler.
Definition at line 879 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 879 of file G4HepRepSceneHandler.cc
References addAttributes(), HEPREP::HepRepFactory::createHepRepInstance(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), factory, G4VSceneHandler::fpModel, G4VSceneHandler::fProcessing2D, G4VSceneHandler::fpVisAttribs, G4Exception(), getCalHitFaceType(), getCalHitType(), G4VSceneHandler::GetColor(), G4PhysicalVolumeModel::GetCurrentDepth(), getGeometryInstance(), getGeometryOrEventInstance(), HepPolyhedron::GetNextNormal(), HepPolyhedron::GetNextVertex(), HepPolyhedron::GetNoFacets(), G4Visible::GetVisAttributes(), instance, isEventData(), JustWarning, setAttribute(), setColor(), setLine(), setVisibility(), and transform.
void G4HepRepSceneHandler::AddPrimitive (const G4Polymarker & line) virtual
Reimplemented from G4VSceneHandler.
Definition at line 792 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 792 of file G4HepRepSceneHandler.cc
References addAttributes(), G4Polymarker::circles, HEPREP::HepRepFactory::createHepRepInstance(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), G4Polymarker::dots, factory, G4VSceneHandler::fProcessing2D, G4VSceneHandler::fpVisAttribs, G4Exception(), G4VSceneHandler::GetColor(), getEventInstance(), getHitType(), G4Polymarker::GetMarkerType(), G4Visible::GetVisAttributes(), instance, JustWarning, setAttribute(), setColor(), setMarker(), setVisibility(), G4Polymarker::squares, transform, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepSceneHandler::AddPrimitive (const G4Scale & scale) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1000 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1000 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddPrimitive(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4Box & box) virtual
Reimplemented from G4VSceneHandler.
Definition at line 467 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 467 of file G4HepRepSceneHandler.cc
References addAttributes(), G4VSceneHandler::AddSolid(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), dx, dy, dz, factory, getCalHitType(), getColorFor(), getGeometryOrEventInstance(), G4HepRepMessenger::GetInstance(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), instance, setAttribute(), setColor(), setLine(), setVisibility(), transform, G4HepRepMessenger::useSolids(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepSceneHandler::AddSolid (const G4Cons & cons) virtual
Reimplemented from G4VSceneHandler.
Definition at line 523 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 523 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepAttribute::addAttValue(), G4VSceneHandler::AddSolid(), HEPREP::HepRepFactory::createHepRepInstance(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), factory, G4VSceneHandler::fpModel, getColorFor(), G4PhysicalVolumeModel::GetCurrentDepth(), G4PhysicalVolumeModel::GetCurrentLV(), G4PhysicalVolumeModel::GetCurrentMaterial(), G4Cons::GetDeltaPhiAngle(), getGeometryInstance(), getGeometryType(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4HepRepMessenger::GetInstance(), G4LogicalVolume::GetName(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4Cons::GetZHalfLength(), instance, setAttribute(), setColor(), setLine(), setVisibility(), transform, twopi, G4HepRepMessenger::useSolids(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepSceneHandler::AddSolid (const G4Tubs & tubs) virtual
Reimplemented from G4VSceneHandler.
Definition at line 587 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 587 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepAttribute::addAttValue(), G4VSceneHandler::AddSolid(), HEPREP::HepRepFactory::createHepRepInstance(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), factory, G4VSceneHandler::fpModel, getColorFor(), G4PhysicalVolumeModel::GetCurrentDepth(), G4PhysicalVolumeModel::GetCurrentLV(), G4PhysicalVolumeModel::GetCurrentMaterial(), G4Tubs::GetDeltaPhiAngle(), getGeometryInstance(), getGeometryType(), G4Tubs::GetInnerRadius(), G4HepRepMessenger::GetInstance(), G4LogicalVolume::GetName(), G4Tubs::GetOuterRadius(), G4Tubs::GetZHalfLength(), instance, setAttribute(), setColor(), setLine(), setVisibility(), transform, twopi, G4HepRepMessenger::useSolids(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepSceneHandler::AddSolid (const G4Trd & trd) virtual
Reimplemented from G4VSceneHandler.
Definition at line 647 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 647 of file G4HepRepSceneHandler.cc
References addAttributes(), G4VSceneHandler::AddSolid(), HEPREP::HepRepFactory::createHepRepPoint(), dontWrite(), dz, factory, getCalHitType(), getColorFor(), getGeometryOrEventInstance(), G4HepRepMessenger::GetInstance(), G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), instance, setAttribute(), setColor(), setLine(), setVisibility(), transform, G4HepRepMessenger::useSolids(), HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
void G4HepRepSceneHandler::AddSolid (const G4Trap & trap) virtual
Reimplemented from G4VSceneHandler.
Definition at line 704 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 704 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4Sphere & sphere) virtual
Reimplemented from G4VSceneHandler.
Definition at line 709 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 709 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4Para & para) virtual
Reimplemented from G4VSceneHandler.
Definition at line 714 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 714 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4Torus & torus) virtual
Reimplemented from G4VSceneHandler.
Definition at line 719 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 719 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4Polycone & polycone) virtual
Reimplemented from G4VSceneHandler.
Definition at line 724 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 724 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4Polyhedra & polyhedra) virtual
Reimplemented from G4VSceneHandler.
Definition at line 729 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 729 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4Orb & orb) virtual
Reimplemented from G4VSceneHandler.
Definition at line 734 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 734 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4Ellipsoid & ellipsoid) virtual
Reimplemented from G4VSceneHandler.
Definition at line 739 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 739 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4TessellatedSolid & tess) virtual
Reimplemented from G4VSceneHandler.
Definition at line 744 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 744 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::AddSolid (const G4VSolid & solid) virtual
Reimplemented from G4VSceneHandler.
Definition at line 749 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 749 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::AddSolid(), and dontWrite().
void G4HepRepSceneHandler::addTopLevelAttributes (HEPREP::HepRepType * type) private
Definition at line 1408 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1408 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepDefinition::addAttDef(), HEPREP::HepRepAttribute::addAttValue(), G4Date, G4Version, G4VSceneHandler::GetCurrentViewer(), G4HepRepMessenger::GetInstance(), G4VViewer::GetViewParameters(), G4ViewParameters::GetViewpointDirection(), G4ViewParameters::GetZoomFactor(), Dataset::parameters, HepGeom::BasicVector3D< T >::phi(), HepGeom::BasicVector3D< T >::theta(), G4HepRepMessenger::useSolids(), and G4HepRepMessenger::writeInvisibles().
Referenced by getEventType(), and getGeometryRootType().
void G4HepRepSceneHandler::BeginModeling () virtual
Reimplemented from G4VSceneHandler.
Definition at line 452 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 452 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::BeginModeling().
void G4HepRepSceneHandler::BeginPrimitives (const G4Transform3D & objectTransformation) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1048 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1048 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::BeginPrimitives(), and transform.
void G4HepRepSceneHandler::close (void) private
Definition at line 412 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 412 of file G4HepRepSceneHandler.cc
References closeFile(), closeHepRep(), G4VSceneHandler::GetCurrentViewer(), G4HepRepViewer::reset(), writeMultipleFiles, and writer.
Referenced by ~G4HepRepSceneHandler().
void G4HepRepSceneHandler::closeFile ()
Definition at line 434 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 434 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepWriter::close(), out, and writer.
Referenced by close(), and closeHepRep().
bool G4HepRepSceneHandler::closeHepRep (bool final = false)
Returns true if the HepRep was (already) closed, false if the HepRep is still open
Definition at line 294 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 294 of file G4HepRepSceneHandler.cc
References _eventInstanceTree, _geometryInstanceTree, _heprep, _heprepGeometry, HEPREP::HepRepInstanceTree::addInstanceTree(), HEPREP::HepRepWriter::addProperty(), G4HepRepMessenger::appendGeometry(), baseName, closeFile(), HEPREP::HepRepFactory::createHepRepTreeID(), G4VViewer::DrawView(), eventNumber, eventNumberPrefix, eventNumberSuffix, eventNumberWidth, extension, factory, getCalHitFaceType(), getCalHitType(), G4VSceneHandler::GetCurrentViewer(), getEventInstanceTree(), getEventType(), getGeometryInstanceTree(), getHitType(), G4HepRepMessenger::GetInstance(), G4VSceneHandler::GetName(), G4VSceneHandler::GetScene(), getTrajectoryType(), open(), openFile(), HEPREP::HepRepWriter::write(), writeBinary, writeLayers(), writeMultipleFiles, and writer.
Referenced by close(), and G4HepRepViewer::ShowView().
G4bool G4HepRepSceneHandler::dontWrite () private
Definition at line 1066 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1066 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::fpVisAttribs, G4HepRepMessenger::GetInstance(), G4VisAttributes::IsVisible(), and G4HepRepMessenger::writeInvisibles().
Referenced by AddCompound(), AddPrimitive(), and AddSolid().
void G4HepRepSceneHandler::EndModeling () virtual
Reimplemented from G4VSceneHandler.
Definition at line 460 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 460 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::EndModeling().
void G4HepRepSceneHandler::EndPrimitives () virtual
Reimplemented from G4VSceneHandler.
Definition at line 1058 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1058 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::EndPrimitives().
HepRepType * G4HepRepSceneHandler::getCalHitFaceType () private
Definition at line 1754 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1754 of file G4HepRepSceneHandler.cc
References _calHitFaceType, HEPREP::HepRepAttribute::addAttValue(), HEPREP::HepRepFactory::createHepRepType(), factory, and getCalHitType().
Referenced by AddPrimitive(), and closeHepRep().
HepRepType * G4HepRepSceneHandler::getCalHitType () private
Definition at line 1744 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1744 of file G4HepRepSceneHandler.cc
References _calHitType, HEPREP::HepRepAttribute::addAttValue(), calHitLayer, HEPREP::HepRepFactory::createHepRepType(), factory, and getEventType().
Referenced by AddPrimitive(), AddSolid(), closeHepRep(), and getCalHitFaceType().
G4Color G4HepRepSceneHandler::getColorFor (const G4Visible & visible) private
Definition at line 1088 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1088 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::fpVisAttribs, G4VSceneHandler::GetColor(), and G4Visible::GetVisAttributes().
Referenced by AddPrimitive(), and AddSolid().
G4Color G4HepRepSceneHandler::getColorFor (const G4VSolid & solid) private
Definition at line 1083 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1083 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::GetColor().
HepRepInstance * G4HepRepSceneHandler::getEventInstance () private
Definition at line 1670 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1670 of file G4HepRepSceneHandler.cc
References _eventInstance, HEPREP::HepRepFactory::createHepRepInstance(), factory, getEventInstanceTree(), and getEventType().
Referenced by AddPrimitive(), and getGeometryOrEventInstance().
HepRepInstanceTree * G4HepRepSceneHandler::getEventInstanceTree () private
Definition at line 1661 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1661 of file G4HepRepSceneHandler.cc
References _eventInstanceTree, HEPREP::HepRep::addInstanceTree(), HEPREP::HepRepFactory::createHepRepInstanceTree(), factory, getEventTypeTree(), and getHepRep().
Referenced by closeHepRep(), and getEventInstance().
HepRepType * G4HepRepSceneHandler::getEventType () private
Definition at line 1689 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1689 of file G4HepRepSceneHandler.cc
References _eventType, HEPREP::HepRepAttribute::addAttValue(), addTopLevelAttributes(), HEPREP::HepRepFactory::createHepRepType(), eventLayer, factory, and getEventTypeTree().
Referenced by closeHepRep(), getCalHitType(), getEventInstance(), getHitType(), and getTrajectoryType().
HepRepTypeTree * G4HepRepSceneHandler::getEventTypeTree () private
Definition at line 1678 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1678 of file G4HepRepSceneHandler.cc
References _eventTypeTree, HEPREP::HepRep::addTypeTree(), HEPREP::HepRepFactory::createHepRepTreeID(), HEPREP::HepRepFactory::createHepRepTypeTree(), factory, and getHepRep().
Referenced by getEventInstanceTree(), and getEventType().
G4String G4HepRepSceneHandler::getFullTypeName (G4String volumeName, int depth) private
Definition at line 1632 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1632 of file G4HepRepSceneHandler.cc
References _geometryType, _geometryTypeName, HEPREP::HepRepFactory::createHepRepType(), factory, getGeometryRootType(), and rootVolumeName.
Referenced by getGeometryType().
HepRepInstance * G4HepRepSceneHandler::getGeometryInstance (G4LogicalVolume * volume, G4Material * material, int depth) private
Definition at line 1507 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1507 of file G4HepRepSceneHandler.cc
References G4Material::GetDensity(), G4VSolid::GetEntityType(), G4VSolid::GetName(), G4Material::GetName(), G4LogicalVolume::GetName(), G4Material::GetRadlen(), G4LogicalVolume::GetRegion(), G4LogicalVolume::GetSolid(), G4Material::GetState(), instance, G4LogicalVolume::IsRootRegion(), kStateUndefined, materialState, and setAttribute().
Referenced by AddPrimitive(), AddSolid(), and getGeometryOrEventInstance().
HepRepInstance * G4HepRepSceneHandler::getGeometryInstance (G4String volumeName, int depth) private
Definition at line 1531 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1531 of file G4HepRepSceneHandler.cc
References _geometryInstance, HEPREP::HepRepFactory::createHepRepInstance(), factory, getGeometryRootInstance(), getGeometryType(), and instance.
HepRepInstanceTree * G4HepRepSceneHandler::getGeometryInstanceTree () private
Definition at line 1484 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1484 of file G4HepRepSceneHandler.cc
References _geometryInstanceTree, HEPREP::HepRep::addInstanceTree(), G4HepRepMessenger::appendGeometry(), HEPREP::HepRepFactory::createHepRepInstanceTree(), factory, getGeometryTypeTree(), getHepRep(), getHepRepGeometry(), and G4HepRepMessenger::GetInstance().
Referenced by closeHepRep(), and getGeometryRootInstance().
HepRepInstance * G4HepRepSceneHandler::getGeometryOrEventInstance (HEPREP::HepRepType * type) private
Definition at line 1454 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1454 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepFactory::createHepRepInstance(), factory, G4VSceneHandler::fpModel, G4PhysicalVolumeModel::GetCurrentDepth(), G4PhysicalVolumeModel::GetCurrentLV(), G4PhysicalVolumeModel::GetCurrentMaterial(), getEventInstance(), getGeometryInstance(), and isEventData().
Referenced by AddPrimitive(), and AddSolid().
HepRepInstance * G4HepRepSceneHandler::getGeometryRootInstance () private
Definition at line 1499 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1499 of file G4HepRepSceneHandler.cc
References _geometryRootInstance, HEPREP::HepRepFactory::createHepRepInstance(), factory, getGeometryInstanceTree(), and getGeometryRootType().
Referenced by getGeometryInstance().
HepRepType * G4HepRepSceneHandler::getGeometryRootType () private
Definition at line 1568 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1568 of file G4HepRepSceneHandler.cc
References _geometryRootType, _geometryType, HEPREP::HepRepDefinition::addAttDef(), HEPREP::HepRepAttribute::addAttValue(), addTopLevelAttributes(), HEPREP::HepRepFactory::createHepRepType(), factory, geometryLayer, getGeometryTypeTree(), HEPREP::HepRepType::getName(), and rootVolumeName.
Referenced by getFullTypeName(), getGeometryRootInstance(), and getGeometryType().
HepRepType * G4HepRepSceneHandler::getGeometryType (G4String volumeName, int depth) private
Definition at line 1613 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1613 of file G4HepRepSceneHandler.cc
References _geometryType, HEPREP::HepRepFactory::createHepRepType(), factory, getFullTypeName(), getGeometryRootType(), and getParentTypeName().
Referenced by AddSolid(), and getGeometryInstance().
HepRepTypeTree * G4HepRepSceneHandler::getGeometryTypeTree () private
Definition at line 1552 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1552 of file G4HepRepSceneHandler.cc
References _geometryTypeTree, HEPREP::HepRep::addTypeTree(), G4HepRepMessenger::appendGeometry(), HEPREP::HepRepFactory::createHepRepTreeID(), HEPREP::HepRepFactory::createHepRepTypeTree(), factory, getHepRep(), getHepRepGeometry(), and G4HepRepMessenger::GetInstance().
Referenced by getGeometryInstanceTree(), and getGeometryRootType().
HepRep * G4HepRepSceneHandler::getHepRep () private
Definition at line 1468 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1468 of file G4HepRepSceneHandler.cc
References _heprep, HEPREP::HepRepFactory::createHepRep(), and factory.
Referenced by getEventInstanceTree(), getEventTypeTree(), getGeometryInstanceTree(), and getGeometryTypeTree().
HepRep * G4HepRepSceneHandler::getHepRepGeometry () private
Definition at line 1476 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1476 of file G4HepRepSceneHandler.cc
References _heprepGeometry, HEPREP::HepRepFactory::createHepRep(), and factory.
Referenced by getGeometryInstanceTree(), and getGeometryTypeTree().
HepRepType * G4HepRepSceneHandler::getHitType () private
Definition at line 1731 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1731 of file G4HepRepSceneHandler.cc
References _hitType, HEPREP::HepRepAttribute::addAttValue(), HEPREP::HepRepFactory::createHepRepType(), factory, getEventType(), and hitLayer.
Referenced by addAttributes(), AddPrimitive(), and closeHepRep().
G4String G4HepRepSceneHandler::getParentTypeName (int currentDepth) private
Definition at line 1657 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1657 of file G4HepRepSceneHandler.cc
References _geometryTypeName, and rootVolumeName.
Referenced by getGeometryType().
HepRepType * G4HepRepSceneHandler::getTrajectoryType () private
Definition at line 1713 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1713 of file G4HepRepSceneHandler.cc
References _trajectoryType, HEPREP::HepRepAttribute::addAttValue(), HEPREP::HepRepFactory::createHepRepType(), factory, getEventType(), and trajectoryLayer.
Referenced by AddPrimitive(), and closeHepRep().
bool G4HepRepSceneHandler::isEventData () private
Definition at line 1402 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1402 of file G4HepRepSceneHandler.cc
References currentHit, currentTrack, G4VSceneHandler::fpModel, and G4VSceneHandler::fReadyForTransients.
Referenced by AddPrimitive(), and getGeometryOrEventInstance().
void G4HepRepSceneHandler::open (G4String name) private
Definition at line 148 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 148 of file G4HepRepSceneHandler.cc
References baseName, HEPREP::HepRepFactory::createHepRepWriter(), eventNumber, eventNumberPrefix, eventNumberSuffix, eventNumberWidth, extension, factory, G4HepRepMessenger::getEventNumberSuffix(), G4HepRepMessenger::GetInstance(), openFile(), out, writeBinary, writeGZ, writeMultipleFiles, writer, and writeZip.
Referenced by closeHepRep().
void G4HepRepSceneHandler::openFile (G4String name)
Definition at line 429 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 429 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepFactory::createHepRepWriter(), factory, out, writeGZ, writer, and writeZip.
Referenced by closeHepRep(), and open().
void G4HepRepSceneHandler::openHepRep ()
Definition at line 264 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 264 of file G4HepRepSceneHandler.cc
References _calHitFaceType, _calHitType, _eventInstance, _eventInstanceTree, _eventType, _eventTypeTree, _geometryInstance, _geometryInstanceTree, _geometryRootInstance, _geometryRootType, _geometryType, _geometryTypeName, _geometryTypeTree, _heprep, _heprepGeometry, _hitType, and _trajectoryType.
Referenced by G4HepRepSceneHandler(), and G4HepRepViewer::ShowView().
G4HepRepSceneHandler& G4HepRepSceneHandler::operator= (const G4HepRepSceneHandler &) private
void G4HepRepSceneHandler::PostAddSolid () virtual
Reimplemented from G4VSceneHandler.
Definition at line 1040 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1040 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::PostAddSolid().
void G4HepRepSceneHandler::PreAddSolid (const G4Transform3D & objectTransformation, const G4VisAttributes & visAttribs) virtual
Reimplemented from G4VSceneHandler.
Definition at line 1028 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1028 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::PreAddSolid(), and transform.
void G4HepRepSceneHandler::setAttribute (HEPREP::HepRepAttribute * attribute, G4String name, char * value) inline private
Definition at line 145 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 145 of file G4HepRepSceneHandler.hh
Referenced by addAttVals(), AddPrimitive(), AddSolid(), getGeometryInstance(), setColor(), setLine(), setMarker(), and setVisibility().
void G4HepRepSceneHandler::setAttribute (HEPREP::HepRepAttribute * attribute, G4String name, G4String value) private
Definition at line 1185 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1185 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepAttribute::addAttValue(), HEPREP::HepRepAttribute::getAttValue(), HEPREP::HepRepAttribute::getAttValueFromNode(), HEPREP::HepRepPoint::getInstance(), HEPREP::HepRepAttValue::getString(), HEPREP::HepRepInstance::getType(), and instance.
void G4HepRepSceneHandler::setAttribute (HEPREP::HepRepAttribute * attribute, G4String name, bool value) private
Definition at line 1207 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1207 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepAttribute::addAttValue(), HEPREP::HepRepAttribute::getAttValue(), HEPREP::HepRepAttribute::getAttValueFromNode(), HEPREP::HepRepAttValue::getBoolean(), HEPREP::HepRepPoint::getInstance(), HEPREP::HepRepInstance::getType(), and instance.
void G4HepRepSceneHandler::setAttribute (HEPREP::HepRepAttribute * attribute, G4String name, double value) private
Definition at line 1229 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1229 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepAttribute::addAttValue(), HEPREP::HepRepAttribute::getAttValue(), HEPREP::HepRepAttribute::getAttValueFromNode(), HEPREP::HepRepAttValue::getDouble(), HEPREP::HepRepPoint::getInstance(), HEPREP::HepRepInstance::getType(), and instance.
void G4HepRepSceneHandler::setAttribute (HEPREP::HepRepAttribute * attribute, G4String name, int value) private
Definition at line 1251 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1251 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepAttribute::addAttValue(), HEPREP::HepRepAttribute::getAttValue(), HEPREP::HepRepAttribute::getAttValueFromNode(), HEPREP::HepRepPoint::getInstance(), HEPREP::HepRepAttValue::getInteger(), HEPREP::HepRepInstance::getType(), and instance.
void G4HepRepSceneHandler::setAttribute (HEPREP::HepRepAttribute * attribute, G4String name, double red, double green, double blue, double alpha) private
Definition at line 1273 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1273 of file G4HepRepSceneHandler.cc
References HEPREP::HepRepAttribute::addAttValue(), color(), HEPREP::HepRepAttribute::getAttValue(), HEPREP::HepRepAttribute::getAttValueFromNode(), HEPREP::HepRepAttValue::getColor(), HEPREP::HepRepPoint::getInstance(), HEPREP::HepRepInstance::getType(), and instance.
void G4HepRepSceneHandler::setColor (HEPREP::HepRepAttribute * attribute, const G4Color & color, const G4String & key = G4String("Color")) private
Definition at line 1071 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1071 of file G4HepRepSceneHandler.cc
References G4Colour::GetAlpha(), G4Colour::GetBlue(), G4Colour::GetGreen(), G4Colour::GetRed(), and setAttribute().
Referenced by AddPrimitive(), AddSolid(), and setMarker().
void G4HepRepSceneHandler::setLine (HEPREP::HepRepAttribute * attribute, const G4VSolid & solid) private
Definition at line 1103 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1103 of file G4HepRepSceneHandler.cc
References setAttribute().
Referenced by AddPrimitive(), and AddSolid().
void G4HepRepSceneHandler::setLine (HEPREP::HepRepAttribute * attribute, const G4Visible & visible) private
Definition at line 1107 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1107 of file G4HepRepSceneHandler.cc
References G4VisAttributes::dashed, G4VisAttributes::dotted, G4VisAttributes::GetLineStyle(), G4VisAttributes::GetLineWidth(), G4Visible::GetVisAttributes(), setAttribute(), and G4VisAttributes::unbroken.
void G4HepRepSceneHandler::setMarker (HEPREP::HepRepAttribute * attribute, const G4VMarker & marker) private
Definition at line 1127 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1127 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::fpVisAttribs, G4VSceneHandler::GetColor(), G4VMarker::GetFillStyle(), G4VSceneHandler::GetMarkerRadius(), G4Visible::GetVisAttributes(), G4VMarker::noFill, G4VSceneHandler::screen, setAttribute(), and setColor().
Referenced by AddPrimitive().
void G4HepRepSceneHandler::setVisibility (HEPREP::HepRepAttribute * attribute, const G4VSolid & solid) private
Definition at line 1093 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1093 of file G4HepRepSceneHandler.cc
References G4VSceneHandler::fpVisAttribs, G4VisAttributes::IsVisible(), and setAttribute().
Referenced by AddPrimitive(), and AddSolid().
void G4HepRepSceneHandler::setVisibility (HEPREP::HepRepAttribute * attribute, const G4Visible & visible) private
Definition at line 1097 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1097 of file G4HepRepSceneHandler.cc
References G4Visible::GetVisAttributes(), G4VisAttributes::IsVisible(), and setAttribute().
void G4HepRepSceneHandler::writeLayers (HEPREP::HepRep * heprep) private
Definition at line 443 of file G4HepRepSceneHandler.cc.
View newest version in sPHENIX GitHub at line 443 of file G4HepRepSceneHandler.cc
References HEPREP::HepRep::addLayer(), calHitLayer, eventLayer, geometryLayer, hitLayer, and trajectoryLayer.
Referenced by closeHepRep().
Member Data Documentation
HEPREP::HepRepType* G4HepRepSceneHandler::_calHitFaceType private
Definition at line 227 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 227 of file G4HepRepSceneHandler.hh
Referenced by getCalHitFaceType(), and openHepRep().
HEPREP::HepRepType* G4HepRepSceneHandler::_calHitType private
Definition at line 226 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 226 of file G4HepRepSceneHandler.hh
Referenced by getCalHitType(), and openHepRep().
HEPREP::HepRepInstance* G4HepRepSceneHandler::_eventInstance private
Definition at line 221 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 221 of file G4HepRepSceneHandler.hh
Referenced by getEventInstance(), and openHepRep().
HEPREP::HepRepInstanceTree* G4HepRepSceneHandler::_eventInstanceTree private
Definition at line 220 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 220 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), getEventInstanceTree(), and openHepRep().
HEPREP::HepRepType* G4HepRepSceneHandler::_eventType private
Definition at line 223 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 223 of file G4HepRepSceneHandler.hh
Referenced by getEventType(), and openHepRep().
HEPREP::HepRepTypeTree* G4HepRepSceneHandler::_eventTypeTree private
Definition at line 222 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 222 of file G4HepRepSceneHandler.hh
Referenced by getEventTypeTree(), and openHepRep().
std::vector<HEPREP::HepRepInstance*> G4HepRepSceneHandler::_geometryInstance private
Definition at line 214 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 214 of file G4HepRepSceneHandler.hh
Referenced by getGeometryInstance(), and openHepRep().
HEPREP::HepRepInstanceTree* G4HepRepSceneHandler::_geometryInstanceTree private
Definition at line 213 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 213 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), getGeometryInstanceTree(), and openHepRep().
HEPREP::HepRepInstance* G4HepRepSceneHandler::_geometryRootInstance private
Definition at line 215 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 215 of file G4HepRepSceneHandler.hh
Referenced by getGeometryRootInstance(), and openHepRep().
HEPREP::HepRepType* G4HepRepSceneHandler::_geometryRootType private
Definition at line 219 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 219 of file G4HepRepSceneHandler.hh
Referenced by getGeometryRootType(), and openHepRep().
std::map<G4String, HEPREP::HepRepType*> G4HepRepSceneHandler::_geometryType private
Definition at line 218 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 218 of file G4HepRepSceneHandler.hh
Referenced by getFullTypeName(), getGeometryRootType(), getGeometryType(), and openHepRep().
std::vector<G4String> G4HepRepSceneHandler::_geometryTypeName private
Definition at line 217 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 217 of file G4HepRepSceneHandler.hh
Referenced by getFullTypeName(), getParentTypeName(), and openHepRep().
HEPREP::HepRepTypeTree* G4HepRepSceneHandler::_geometryTypeTree private
Definition at line 216 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 216 of file G4HepRepSceneHandler.hh
Referenced by getGeometryTypeTree(), and openHepRep().
HEPREP::HepRep* G4HepRepSceneHandler::_heprep private
Definition at line 211 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 211 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), getHepRep(), and openHepRep().
HEPREP::HepRep* G4HepRepSceneHandler::_heprepGeometry private
Definition at line 212 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 212 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), getHepRepGeometry(), and openHepRep().
HEPREP::HepRepType* G4HepRepSceneHandler::_hitType private
Definition at line 225 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 225 of file G4HepRepSceneHandler.hh
Referenced by getHitType(), and openHepRep().
HEPREP::HepRepType* G4HepRepSceneHandler::_trajectoryType private
Definition at line 224 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 224 of file G4HepRepSceneHandler.hh
Referenced by getTrajectoryType(), and openHepRep().
G4String G4HepRepSceneHandler::baseName private
Definition at line 197 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 197 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), and open().
G4String G4HepRepSceneHandler::calHitLayer private
Definition at line 193 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 193 of file G4HepRepSceneHandler.hh
Referenced by getCalHitType(), and writeLayers().
const G4VHit* G4HepRepSceneHandler::currentHit private
Definition at line 207 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 207 of file G4HepRepSceneHandler.hh
Referenced by addAttributes(), AddCompound(), and isEventData().
const G4VTrajectory* G4HepRepSceneHandler::currentTrack private
Definition at line 208 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 208 of file G4HepRepSceneHandler.hh
Referenced by addAttributes(), AddCompound(), and isEventData().
G4String G4HepRepSceneHandler::eventLayer private
Definition at line 193 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 193 of file G4HepRepSceneHandler.hh
Referenced by getEventType(), and writeLayers().
G4int G4HepRepSceneHandler::eventNumber private
Definition at line 200 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 200 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), and open().
G4String G4HepRepSceneHandler::eventNumberPrefix private
Definition at line 198 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 198 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), and open().
G4String G4HepRepSceneHandler::eventNumberSuffix private
Definition at line 199 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 199 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), and open().
G4int G4HepRepSceneHandler::eventNumberWidth private
Definition at line 201 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 201 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), and open().
G4String G4HepRepSceneHandler::extension private
Definition at line 202 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 202 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), and open().
HEPREP::HepRepFactory* G4HepRepSceneHandler::factory private
Definition at line 126 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 126 of file G4HepRepSceneHandler.hh
Referenced by AddPrimitive(), AddSolid(), closeHepRep(), G4HepRepSceneHandler(), getCalHitFaceType(), getCalHitType(), getEventInstance(), getEventInstanceTree(), getEventType(), getEventTypeTree(), getFullTypeName(), getGeometryInstance(), getGeometryInstanceTree(), getGeometryOrEventInstance(), getGeometryRootInstance(), getGeometryRootType(), getGeometryType(), getGeometryTypeTree(), getHepRep(), getHepRepGeometry(), getHitType(), getTrajectoryType(), open(), openFile(), and ~G4HepRepSceneHandler().
G4String G4HepRepSceneHandler::geometryLayer private
Definition at line 193 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 193 of file G4HepRepSceneHandler.hh
Referenced by getGeometryRootType(), and writeLayers().
G4String G4HepRepSceneHandler::hitLayer private
Definition at line 194 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 194 of file G4HepRepSceneHandler.hh
Referenced by getHitType(), and writeLayers().
std::map<int, G4String> G4HepRepSceneHandler::materialState private
Definition at line 229 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 229 of file G4HepRepSceneHandler.hh
Referenced by G4HepRepSceneHandler(), and getGeometryInstance().
std::ostream* G4HepRepSceneHandler::out private
Definition at line 125 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 125 of file G4HepRepSceneHandler.hh
Referenced by closeFile(), open(), and openFile().
G4String G4HepRepSceneHandler::rootVolumeName private
Definition at line 195 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 195 of file G4HepRepSceneHandler.hh
Referenced by getFullTypeName(), getGeometryRootType(), and getParentTypeName().
G4int G4HepRepSceneHandler::sceneIdCount = 0 static private
Definition at line 121 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 121 of file G4HepRepSceneHandler.hh
G4String G4HepRepSceneHandler::trajectoryLayer private
Definition at line 194 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 194 of file G4HepRepSceneHandler.hh
Referenced by getTrajectoryType(), and writeLayers().
G4Transform3D G4HepRepSceneHandler::transform private
Definition at line 123 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 123 of file G4HepRepSceneHandler.hh
Referenced by AddPrimitive(), AddSolid(), BeginPrimitives(), and PreAddSolid().
G4bool G4HepRepSceneHandler::writeBinary private
Definition at line 203 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 203 of file G4HepRepSceneHandler.hh
Referenced by closeHepRep(), and open().
G4bool G4HepRepSceneHandler::writeGZ private
Definition at line 205 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 205 of file G4HepRepSceneHandler.hh
Referenced by open(), and openFile().
G4bool G4HepRepSceneHandler::writeMultipleFiles private
Definition at line 206 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 206 of file G4HepRepSceneHandler.hh
Referenced by close(), closeHepRep(), and open().
HEPREP::HepRepWriter* G4HepRepSceneHandler::writer private
Definition at line 127 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 127 of file G4HepRepSceneHandler.hh
Referenced by close(), closeFile(), closeHepRep(), G4HepRepSceneHandler(), open(), and openFile().
G4bool G4HepRepSceneHandler::writeZip private
Definition at line 204 of file G4HepRepSceneHandler.hh.
View newest version in sPHENIX GitHub at line 204 of file G4HepRepSceneHandler.hh
Referenced by open(), and openFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/G4HepRepSceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/G4HepRepSceneHandler.cc