ECCE @ EIC Software: G4CascadeDeexcitation Class Reference
G4CascadeDeexcitation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeDeexcitation.hh>
Public Member Functions
G4CascadeDeexcitation ()
virtual ~G4CascadeDeexcitation ()
virtual void setVerboseLevel (G4int verbose)
virtual void deExcite (const G4Fragment &fragment, G4CollisionOutput &globalOutput)
Public Member Functions inherited from G4CascadeDeexciteBase
G4CascadeDeexciteBase (const char *name)
virtual ~G4CascadeDeexciteBase ()
Public Member Functions inherited from G4VCascadeDeexcitation
G4VCascadeDeexcitation (const G4String &name)
virtual ~G4VCascadeDeexcitation ()
virtual void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Private Member Functions
G4CascadeDeexcitation (const G4CascadeDeexcitation &)
G4CascadeDeexcitation & operator= (const G4CascadeDeexcitation &)
Private Attributes
G4BigBanger * theBigBanger
G4NonEquilibriumEvaporator * theNonEquilibriumEvaporator
G4EquilibriumEvaporator * theEquilibriumEvaporator
G4CollisionOutput tempOutput
Additional Inherited Members
Protected Member Functions inherited from G4CascadeDeexciteBase
virtual G4bool explosion (const G4Fragment &target) const
virtual G4bool explosion (G4int A, G4int Z, G4double excitation) const
virtual G4bool validateOutput (const G4Fragment &target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclElementaryParticle > &particles)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclNuclei > &fragments)
void getTargetData (const G4Fragment &target)
const G4Fragment & makeFragment (G4LorentzVector mom, G4int A, G4int Z, G4double EX=0.)
const G4Fragment & makeFragment (G4int A, G4int Z, G4double EX=0.)
Protected Attributes inherited from G4CascadeDeexciteBase
G4CascadeCheckBalance * balance
G4int A
G4int Z
G4LorentzVector PEX
G4double EEXS
G4Fragment aFragment
Detailed Description
Definition at line 48 of file G4CascadeDeexcitation.hh.
View newest version in sPHENIX GitHub at line 48 of file G4CascadeDeexcitation.hh
Constructor & Destructor Documentation
G4CascadeDeexcitation::G4CascadeDeexcitation ()
Definition at line 46 of file G4CascadeDeexcitation.cc.
View newest version in sPHENIX GitHub at line 46 of file G4CascadeDeexcitation.cc
G4CascadeDeexcitation::~G4CascadeDeexcitation () virtual
Definition at line 52 of file G4CascadeDeexcitation.cc.
View newest version in sPHENIX GitHub at line 52 of file G4CascadeDeexcitation.cc
References theBigBanger, theEquilibriumEvaporator, and theNonEquilibriumEvaporator.
G4CascadeDeexcitation::G4CascadeDeexcitation (const G4CascadeDeexcitation &) private
Member Function Documentation
void G4CascadeDeexcitation::deExcite (const G4Fragment & fragment, G4CollisionOutput & globalOutput) virtual
Implements G4VCascadeDeexcitation.
Definition at line 68 of file G4CascadeDeexcitation.cc.
View newest version in sPHENIX GitHub at line 68 of file G4CascadeDeexcitation.cc
References G4CollisionOutput::add(), G4CollisionOutput::addOutgoingParticles(), G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4EquilibriumEvaporator::deExcite(), G4CascadeDeexciteBase::explosion(), G4cout, G4endl, G4CollisionOutput::getOutgoingParticles(), G4CollisionOutput::getRecoilFragment(), G4CollisionOutput::printCollisionOutput(), G4CollisionOutput::reset(), tempOutput, theBigBanger, theEquilibriumEvaporator, theNonEquilibriumEvaporator, and G4VCascadeCollider::verboseLevel.
G4CascadeDeexcitation& G4CascadeDeexcitation::operator= (const G4CascadeDeexcitation &) private
void G4CascadeDeexcitation::setVerboseLevel (G4int verbose) virtual
Reimplemented from G4CascadeDeexciteBase.
Definition at line 58 of file G4CascadeDeexcitation.cc.
View newest version in sPHENIX GitHub at line 58 of file G4CascadeDeexcitation.cc
References G4CascadeDeexciteBase::setVerboseLevel(), G4EquilibriumEvaporator::setVerboseLevel(), theBigBanger, theEquilibriumEvaporator, and theNonEquilibriumEvaporator.
Member Data Documentation
G4CollisionOutput G4CascadeDeexcitation::tempOutput private
Definition at line 64 of file G4CascadeDeexcitation.hh.
View newest version in sPHENIX GitHub at line 64 of file G4CascadeDeexcitation.hh
Referenced by deExcite().
G4BigBanger* G4CascadeDeexcitation::theBigBanger private
Definition at line 60 of file G4CascadeDeexcitation.hh.
View newest version in sPHENIX GitHub at line 60 of file G4CascadeDeexcitation.hh
Referenced by deExcite(), setVerboseLevel(), and ~G4CascadeDeexcitation().
G4EquilibriumEvaporator* G4CascadeDeexcitation::theEquilibriumEvaporator private
Definition at line 62 of file G4CascadeDeexcitation.hh.
View newest version in sPHENIX GitHub at line 62 of file G4CascadeDeexcitation.hh
Referenced by deExcite(), setVerboseLevel(), and ~G4CascadeDeexcitation().
G4NonEquilibriumEvaporator* G4CascadeDeexcitation::theNonEquilibriumEvaporator private
Definition at line 61 of file G4CascadeDeexcitation.hh.
View newest version in sPHENIX GitHub at line 61 of file G4CascadeDeexcitation.hh
Referenced by deExcite(), setVerboseLevel(), and ~G4CascadeDeexcitation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeDeexcitation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeDeexcitation.cc