ECCE @ EIC Software: macros/blob/master/common/G4_FwdJets.C File Reference
G4_FwdJets.C File Reference
#include <g4jets/ClusterJetInput.h>
#include <g4jets/FastJetAlgo.h>
#include <g4jets/JetReco.h>
#include <g4jets/TowerJetInput.h>
#include <g4jets/TruthJetInput.h>
#include <g4jets/TrackJetInput.h>
#include <g4eval/JetEvaluator.h>
#include <fun4all/Fun4AllServer.h>
Namespaces
namespace Enable
Macros
#define MACRO_G4FWDJETS_C
Functions
void Jet_FwdRecoInit ()
void Jet_FwdReco ()
void Jet_FwdEval (const std::string &outfilepath=".", const std::string &prepend="")
Variables
bool Enable::FWDJETS = false
bool Enable::FWDJETS_EVAL = false
int Enable::FWDJETS_VERBOSITY = 0
Macro Definition Documentation
#define MACRO_G4FWDJETS_C
Definition at line 2 of file G4_FwdJets.C.
View newest version in sPHENIX GitHub at line 2 of file G4_FwdJets.C
Function Documentation
void Jet_FwdEval (const std::string & outfilepath = ".", const std::string & prepend = "")
Definition at line 131 of file G4_FwdJets.C.
View newest version in sPHENIX GitHub at line 131 of file G4_FwdJets.C
References Enable::FWDJETS_VERBOSITY, Fun4AllServer::instance(), max, Fun4AllServer::registerSubsystem(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), and Fun4All_runEvaluators().
void Jet_FwdReco ()
Definition at line 29 of file G4_FwdJets.C.
View newest version in sPHENIX GitHub at line 29 of file G4_FwdJets.C
References JetReco::add_algo(), JetReco::add_input(), Jet::ANTIKT, Jet::CEMC_CLUSTER, Jet::CEMC_TOWER, Jet::EEMC_CLUSTER, Jet::EEMC_TOWER, Jet::FEMC_CLUSTER, Jet::FEMC_TOWER, Jet::FHCAL_CLUSTER, Jet::FHCAL_TOWER, Enable::FWDJETS_VERBOSITY, Jet::HCALIN_CLUSTER, Jet::HCALIN_TOWER, Jet::HCALOUT_CLUSTER, Jet::HCALOUT_TOWER, Fun4AllServer::instance(), max, Jet::PARTICLE, Fun4AllServer::registerSubsystem(), JetReco::set_algo_node(), JetReco::set_input_node(), Jet::TRACK, TRACKING::TrackNodeName, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), and Fun4All_G4_EICDetector_AnaTutorial().
void Jet_FwdRecoInit ()
Definition at line 27 of file G4_FwdJets.C.
View newest version in sPHENIX GitHub at line 27 of file G4_FwdJets.C