ECCE @ EIC Software: G4DAWNFILESceneHandler Class Reference
G4DAWNFILESceneHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/FukuiRenderer/include/G4DAWNFILESceneHandler.hh>
Public Member Functions
G4DAWNFILESceneHandler (G4DAWNFILE &system, const G4String &name="")
virtual ~G4DAWNFILESceneHandler ()
void AddPrimitive (const G4Polyline &line)
void AddPrimitive (const G4Polyhedron &p)
void AddPrimitive (const G4Text &)
void AddPrimitive (const G4Circle &)
void AddPrimitive (const G4Square &)
void AddPrimitive (const G4Polymarker &polymarker)
void AddPrimitive (const G4Scale &scale)
virtual void BeginModeling ()
virtual void EndModeling ()
virtual void BeginPrimitives (const G4Transform3D &objectTransformation)
virtual void EndPrimitives ()
void AddSolid (const G4Box &box)
void AddSolid (const G4Cons &cons)
void AddSolid (const G4Tubs &tubs)
void AddSolid (const G4Trd &trd)
void AddSolid (const G4Trap &trap)
void AddSolid (const G4Sphere &sphere)
void AddSolid (const G4Para &para)
void AddSolid (const G4Torus &torus)
void AddSolid (const G4Polycone &polycone)
void AddSolid (const G4Polyhedra &polyhedra)
void AddSolid (const G4Orb &orb)
void AddSolid (const G4Ellipsoid &ellipsoid)
void AddSolid (const G4TessellatedSolid &tess)
void AddSolid (const G4VSolid &solid)
void AddCompound (const G4VTrajectory &traj)
void AddCompound (const G4VHit &hit)
void AddCompound (const G4VDigi &digi)
void AddCompound (const G4THitsMap< G4double > &hits)
void AddCompound (const G4THitsMap< G4StatDouble > &hits)
void ClearTransientStore ()
void FRBeginModeling ()
void FREndModeling ()
G4bool FRIsInModeling ()
G4bool IsSavingG4Prim (void)
void BeginSavingG4Prim (void)
void EndSavingG4Prim (void)
void SetG4PrimFileName ()
G4DAWNFILE & GetSystem ()
void SendBoundingBox (void)
const char * GetG4PrimFileName ()
void SendStr (const char *char_string)
void SendStrInt (const char *char_string, G4int ival)
void SendStrInt3 (const char *char_string, G4int ival1, G4int ival2, G4int ival3)
void SendStrInt4 (const char *char_string, G4int ival1, G4int ival2, G4int ival3, G4int ival4)
void SendStrDouble (const char *char_string, G4double dval)
void SendStrDouble2 (const char *char_string, G4double dval1, G4double dval2)
void SendStrDouble3 (const char *char_string, G4double dval1, G4double dval2, G4double dval3)
void SendStrDouble4 (const char *char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4)
void SendStrDouble5 (const char *char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5)
void SendStrDouble6 (const char *char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5, G4double dval6)
void SendStrDouble7 (const char *char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5, G4double dval6, G4double dval7)
void SendStrDouble11 (const char *char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5, G4double dval6, G4double dval7, G4double dval8, G4double dval9, G4double dval10, G4double dval11)
void SendIntDouble3 (G4int ival, G4double dval1, G4double dval2, G4double dval3)
void SendInt3Str (G4int ival1, G4int ival2, G4int ival3, const char *char_string)
void SendInt4Str (G4int ival1, G4int ival2, G4int ival3, G4int ival4, const char *char_string)
void SendStrDouble3Str (const char *char_string1, G4double dval1, G4double dval2, G4double dval3, const char *char_string2)
void SendStrDouble6Str (const char *char_string1, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5, G4double dval6, const char *char_string2)
void SendInt (G4int val)
void SendDouble (G4double val)
Public Member Functions inherited from G4VSceneHandler
G4VSceneHandler (G4VGraphicsSystem &system, G4int id, const G4String &name="")
virtual ~G4VSceneHandler ()
virtual void PreAddSolid (const G4Transform3D &objectTransformation, const G4VisAttributes &)
virtual void PostAddSolid ()
virtual void BeginPrimitives2D (const G4Transform3D &objectTransformation=G4Transform3D())
virtual void EndPrimitives2D ()
virtual const G4VisExtent & GetExtent () const
const G4String & GetName () const
G4int GetSceneHandlerId () const
G4int GetViewCount () const
G4VGraphicsSystem * GetGraphicsSystem () const
G4Scene * GetScene () const
const G4ViewerList & GetViewerList () const
G4VModel * GetModel () const
G4VViewer * GetCurrentViewer () const
G4bool GetMarkForClearingTransientStore () const
G4bool IsReadyForTransients () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetTransientsDrawnThisRun () const
const G4Transform3D & GetObjectTransformation () const
void SetName (const G4String &)
void SetCurrentViewer (G4VViewer *)
virtual void SetScene (G4Scene *)
G4ViewerList & SetViewerList ()
void SetModel (G4VModel *)
void SetMarkForClearingTransientStore (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetTransientsDrawnThisRun (G4bool)
void SetObjectTransformation (const G4Transform3D &)
const G4Colour & GetColour ()
const G4Colour & GetColor ()
const G4Colour & GetTextColour (const G4Text &)
const G4Colour & GetTextColor (const G4Text &)
G4double GetLineWidth (const G4VisAttributes *)
G4ViewParameters::DrawingStyle GetDrawingStyle (const G4VisAttributes *)
G4int GetNumberOfCloudPoints (const G4VisAttributes *) const
G4bool GetAuxEdgeVisible (const G4VisAttributes *)
G4int GetNoOfSides (const G4VisAttributes *)
G4double GetMarkerSize (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerDiameter (const G4VMarker &, MarkerSizeType &)
G4double GetMarkerRadius (const G4VMarker &, MarkerSizeType &)
G4ModelingParameters * CreateModelingParameters ()
void DrawEvent (const G4Event *)
void DrawEndOfRunModels ()
template<class T >
void AddSolidT (const T &solid)
template<class T >
void AddSolidWithAuxiliaryEdges (const T &solid)
G4int IncrementViewCount ()
virtual void ClearStore ()
void AddViewerToList (G4VViewer *pView)
void RemoveViewerFromList (G4VViewer *pView)
Public Member Functions inherited from G4VGraphicsScene
G4VGraphicsScene ()
virtual ~G4VGraphicsScene ()
Private Member Functions
G4bool SendVisAttributes (const G4VisAttributes *pAV)
G4bool IsVisible (void)
void SendTransformedCoordinates (void)
void SendPhysVolName (void)
void SendNdiv (void)
Private Attributes
G4DAWNFILE & fSystem
G4FRofstream fPrimDest
G4bool FRflag_in_modeling
G4bool flag_saving_g4_prim
const int COMMAND_BUF_SIZE
char fG4PrimDestDir [256]
char fG4PrimFileName [256]
G4int fMaxFileNum
G4int fPrec
G4int fPrec2
Static Private Attributes
static G4int fSceneIdCount = 0
Friends
class G4DAWNFILEViewer
Additional Inherited Members
Public Types inherited from G4VSceneHandler
enum MarkerSizeType { world, screen }
Protected Member Functions inherited from G4VSceneHandler
virtual void ProcessScene ()
virtual void RequestPrimitives (const G4VSolid &solid)
virtual G4DisplacedSolid * CreateSectionSolid ()
virtual G4DisplacedSolid * CreateCutawaySolid ()
void LoadAtts (const G4Visible &, G4AttHolder *)
Protected Attributes inherited from G4VSceneHandler
G4VGraphicsSystem & fSystem
const G4int fSceneHandlerId
G4String fName
G4int fViewCount
G4ViewerList fViewerList
G4VViewer * fpViewer
G4Scene * fpScene
G4bool fMarkForClearingTransientStore
G4bool fReadyForTransients
G4bool fTransientsDrawnThisEvent
G4bool fTransientsDrawnThisRun
G4bool fProcessingSolid
G4bool fProcessing2D
G4VModel * fpModel
G4Transform3D fObjectTransformation
G4int fNestingDepth
const G4VisAttributes * fpVisAttribs
const G4Transform3D fIdentityTransformation
Detailed Description
Definition at line 46 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 46 of file G4DAWNFILESceneHandler.hh
Constructor & Destructor Documentation
G4DAWNFILESceneHandler::G4DAWNFILESceneHandler (G4DAWNFILE & system, const G4String & name = "")
Definition at line 86 of file G4DAWNFILESceneHandler.cc.
View newest version in sPHENIX GitHub at line 86 of file G4DAWNFILESceneHandler.cc
References DEFAULT_G4PRIM_FILE_NAME, fG4PrimDestDir, fG4PrimFileName, fMaxFileNum, fPrec, fPrec2, and FR_MAX_FILE_NUM.
G4DAWNFILESceneHandler::~G4DAWNFILESceneHandler () virtual
Definition at line 128 of file G4DAWNFILESceneHandler.cc.
View newest version in sPHENIX GitHub at line 128 of file G4DAWNFILESceneHandler.cc
References G4VisManager::errors, fPrimDest, FREndModeling(), G4cout, G4endl, G4VisManager::GetVerbosity(), and G4FRofstream::IsOpen().
Member Function Documentation
void G4DAWNFILESceneHandler::AddCompound (const G4VTrajectory & traj) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 100 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 100 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4DAWNFILESceneHandler::AddCompound (const G4VHit & hit) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 103 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 103 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4DAWNFILESceneHandler::AddCompound (const G4VDigi & digi) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 106 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 106 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4DAWNFILESceneHandler::AddCompound (const G4THitsMap< G4double > & hits) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 109 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 109 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4DAWNFILESceneHandler::AddCompound (const G4THitsMap< G4StatDouble > & hits) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 112 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 112 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddCompound().
void G4DAWNFILESceneHandler::AddPrimitive (const G4Polyline & line) virtual
Implements G4VSceneHandler.
void G4DAWNFILESceneHandler::AddPrimitive (const G4Polyhedron & p) virtual
Implements G4VSceneHandler.
void G4DAWNFILESceneHandler::AddPrimitive (const G4Text &) virtual
Implements G4VSceneHandler.
void G4DAWNFILESceneHandler::AddPrimitive (const G4Circle &) virtual
Implements G4VSceneHandler.
void G4DAWNFILESceneHandler::AddPrimitive (const G4Square &) virtual
Implements G4VSceneHandler.
void G4DAWNFILESceneHandler::AddPrimitive (const G4Polymarker & polymarker) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 65 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 65 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4DAWNFILESceneHandler::AddPrimitive (const G4Scale & scale) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 67 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 67 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddPrimitive().
void G4DAWNFILESceneHandler::AddSolid (const G4Box & box) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::AddSolid (const G4Cons & cons) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::AddSolid (const G4Tubs & tubs) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::AddSolid (const G4Trd & trd) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::AddSolid (const G4Trap & trap) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::AddSolid (const G4Sphere & sphere) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::AddSolid (const G4Para & para) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::AddSolid (const G4Torus & torus) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::AddSolid (const G4Polycone & polycone) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 84 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4DAWNFILESceneHandler::AddSolid (const G4Polyhedra & polyhedra) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 87 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 87 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4DAWNFILESceneHandler::AddSolid (const G4Orb & orb) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 90 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 90 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4DAWNFILESceneHandler::AddSolid (const G4Ellipsoid & ellipsoid) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 93 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 93 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4DAWNFILESceneHandler::AddSolid (const G4TessellatedSolid & tess) inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 96 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 96 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::AddSolid().
void G4DAWNFILESceneHandler::AddSolid (const G4VSolid & solid) virtual
Reimplemented from G4VSceneHandler.
virtual void G4DAWNFILESceneHandler::BeginModeling () inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 70 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 70 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::BeginModeling().
virtual void G4DAWNFILESceneHandler::BeginPrimitives (const G4Transform3D & objectTransformation) virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::BeginSavingG4Prim (void)
Definition at line 210 of file G4DAWNFILESceneHandler.cc.
View newest version in sPHENIX GitHub at line 210 of file G4DAWNFILESceneHandler.cc
References G4VisManager::errors, fG4PrimFileName, flag_saving_g4_prim, fPrimDest, FR_G4_PRIM_HEADER, G4cout, G4endl, G4VisManager::GetVerbosity(), IsSavingG4Prim(), G4FRofstream::Open(), SendStr(), SetG4PrimFileName(), and true.
Referenced by FRBeginModeling().
void G4DAWNFILESceneHandler::ClearTransientStore () virtual
Reimplemented from G4VSceneHandler.
virtual void G4DAWNFILESceneHandler::EndModeling () inline virtual
Reimplemented from G4VSceneHandler.
Definition at line 71 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 71 of file G4DAWNFILESceneHandler.hh
References G4VSceneHandler::EndModeling().
virtual void G4DAWNFILESceneHandler::EndPrimitives () virtual
Reimplemented from G4VSceneHandler.
void G4DAWNFILESceneHandler::EndSavingG4Prim (void)
Definition at line 233 of file G4DAWNFILESceneHandler.cc.
View newest version in sPHENIX GitHub at line 233 of file G4DAWNFILESceneHandler.cc
References G4FRofstream::Close(), G4VisManager::errors, false, flag_saving_g4_prim, fPrimDest, G4cout, G4endl, G4VisManager::GetVerbosity(), and IsSavingG4Prim().
void G4DAWNFILESceneHandler::FRBeginModeling (void)
Definition at line 253 of file G4DAWNFILESceneHandler.cc.
View newest version in sPHENIX GitHub at line 253 of file G4DAWNFILESceneHandler.cc
References BeginSavingG4Prim(), G4VisManager::errors, FR_BEGIN_MODELING, FR_OPEN_DEVICE, FR_SET_CAMERA, FRflag_in_modeling, FRIsInModeling(), G4cout, G4endl, G4VisManager::GetVerbosity(), SendBoundingBox(), SendStr(), and true.
Referenced by G4DAWNFILEViewer::ClearView(), and G4DAWNFILEViewer::DrawView().
void G4DAWNFILESceneHandler::FREndModeling ()
Referenced by G4DAWNFILEViewer::ShowView(), and ~G4DAWNFILESceneHandler().
G4bool G4DAWNFILESceneHandler::FRIsInModeling () inline
Definition at line 121 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 121 of file G4DAWNFILESceneHandler.hh
References FRflag_in_modeling.
Referenced by FRBeginModeling(), and G4DAWNFILEViewer::ShowView().
const char* G4DAWNFILESceneHandler::GetG4PrimFileName () inline
Definition at line 130 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 130 of file G4DAWNFILESceneHandler.hh
References fG4PrimFileName.
Referenced by G4DAWNFILEViewer::G4DAWNFILEViewer(), and G4DAWNFILEViewer::ShowView().
G4DAWNFILE& G4DAWNFILESceneHandler::GetSystem () inline
Definition at line 128 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 128 of file G4DAWNFILESceneHandler.hh
References fSystem.
G4bool G4DAWNFILESceneHandler::IsSavingG4Prim (void) inline
Definition at line 123 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 123 of file G4DAWNFILESceneHandler.hh
References flag_saving_g4_prim.
Referenced by BeginSavingG4Prim(), and EndSavingG4Prim().
G4bool G4DAWNFILESceneHandler::IsVisible (void) private
void G4DAWNFILESceneHandler::SendBoundingBox (void)
Referenced by FRBeginModeling().
void G4DAWNFILESceneHandler::SendDouble (G4double val)
void G4DAWNFILESceneHandler::SendInt (G4int val)
void G4DAWNFILESceneHandler::SendInt3Str (G4int ival1, G4int ival2, G4int ival3, const char * char_string)
void G4DAWNFILESceneHandler::SendInt4Str (G4int ival1, G4int ival2, G4int ival3, G4int ival4, const char * char_string)
void G4DAWNFILESceneHandler::SendIntDouble3 (G4int ival, G4double dval1, G4double dval2, G4double dval3)
void G4DAWNFILESceneHandler::SendNdiv (void) private
void G4DAWNFILESceneHandler::SendPhysVolName (void) private
void G4DAWNFILESceneHandler::SendStr (const char * char_string)
Referenced by BeginSavingG4Prim(), G4DAWNFILEViewer::ClearView(), and FRBeginModeling().
void G4DAWNFILESceneHandler::SendStrDouble (const char * char_string, G4double dval)
void G4DAWNFILESceneHandler::SendStrDouble11 (const char * char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5, G4double dval6, G4double dval7, G4double dval8, G4double dval9, G4double dval10, G4double dval11)
void G4DAWNFILESceneHandler::SendStrDouble2 (const char * char_string, G4double dval1, G4double dval2)
void G4DAWNFILESceneHandler::SendStrDouble3 (const char * char_string, G4double dval1, G4double dval2, G4double dval3)
void G4DAWNFILESceneHandler::SendStrDouble3Str (const char * char_string1, G4double dval1, G4double dval2, G4double dval3, const char * char_string2)
void G4DAWNFILESceneHandler::SendStrDouble4 (const char * char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4)
void G4DAWNFILESceneHandler::SendStrDouble5 (const char * char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5)
void G4DAWNFILESceneHandler::SendStrDouble6 (const char * char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5, G4double dval6)
void G4DAWNFILESceneHandler::SendStrDouble6Str (const char * char_string1, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5, G4double dval6, const char * char_string2)
void G4DAWNFILESceneHandler::SendStrDouble7 (const char * char_string, G4double dval1, G4double dval2, G4double dval3, G4double dval4, G4double dval5, G4double dval6, G4double dval7)
void G4DAWNFILESceneHandler::SendStrInt (const char * char_string, G4int ival)
void G4DAWNFILESceneHandler::SendStrInt3 (const char * char_string, G4int ival1, G4int ival2, G4int ival3)
void G4DAWNFILESceneHandler::SendStrInt4 (const char * char_string, G4int ival1, G4int ival2, G4int ival3, G4int ival4)
void G4DAWNFILESceneHandler::SendTransformedCoordinates (void) private
G4bool G4DAWNFILESceneHandler::SendVisAttributes (const G4VisAttributes * pAV) private
void G4DAWNFILESceneHandler::SetG4PrimFileName ()
Definition at line 144 of file G4DAWNFILESceneHandler.cc.
View newest version in sPHENIX GitHub at line 144 of file G4DAWNFILESceneHandler.cc
References DEFAULT_G4PRIM_FILE_NAME, G4VisManager::errors, fG4PrimDestDir, fG4PrimFileName, INPUTHEPMC::filename, fin, fMaxFileNum, G4cout, G4endl, G4PRIM_FILE_HEADER, and G4VisManager::GetVerbosity().
Referenced by BeginSavingG4Prim().
Friends And Related Function Documentation
friend class G4DAWNFILEViewer friend
Definition at line 48 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 48 of file G4DAWNFILESceneHandler.hh
Member Data Documentation
const int G4DAWNFILESceneHandler::COMMAND_BUF_SIZE private
Definition at line 257 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 257 of file G4DAWNFILESceneHandler.hh
char G4DAWNFILESceneHandler::fG4PrimDestDir[256] private
Definition at line 259 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 259 of file G4DAWNFILESceneHandler.hh
Referenced by G4DAWNFILESceneHandler(), and SetG4PrimFileName().
char G4DAWNFILESceneHandler::fG4PrimFileName[256] private
Definition at line 260 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 260 of file G4DAWNFILESceneHandler.hh
Referenced by BeginSavingG4Prim(), G4DAWNFILEViewer::ClearView(), G4DAWNFILESceneHandler(), GetG4PrimFileName(), and SetG4PrimFileName().
G4bool G4DAWNFILESceneHandler::flag_saving_g4_prim private
Definition at line 255 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 255 of file G4DAWNFILESceneHandler.hh
Referenced by BeginSavingG4Prim(), EndSavingG4Prim(), and IsSavingG4Prim().
G4int G4DAWNFILESceneHandler::fMaxFileNum private
Definition at line 261 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 261 of file G4DAWNFILESceneHandler.hh
Referenced by G4DAWNFILESceneHandler(), and SetG4PrimFileName().
G4int G4DAWNFILESceneHandler::fPrec private
Definition at line 263 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 263 of file G4DAWNFILESceneHandler.hh
Referenced by G4DAWNFILESceneHandler().
G4int G4DAWNFILESceneHandler::fPrec2 private
Definition at line 263 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 263 of file G4DAWNFILESceneHandler.hh
Referenced by G4DAWNFILESceneHandler().
G4FRofstream G4DAWNFILESceneHandler::fPrimDest private
Definition at line 245 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 245 of file G4DAWNFILESceneHandler.hh
Referenced by BeginSavingG4Prim(), G4DAWNFILEViewer::ClearView(), EndSavingG4Prim(), and ~G4DAWNFILESceneHandler().
G4bool G4DAWNFILESceneHandler::FRflag_in_modeling private
Definition at line 246 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 246 of file G4DAWNFILESceneHandler.hh
Referenced by G4DAWNFILEViewer::ClearView(), FRBeginModeling(), and FRIsInModeling().
G4int G4DAWNFILESceneHandler::fSceneIdCount = 0 static private
Definition at line 243 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 243 of file G4DAWNFILESceneHandler.hh
G4DAWNFILE& G4DAWNFILESceneHandler::fSystem private
Definition at line 242 of file G4DAWNFILESceneHandler.hh.
View newest version in sPHENIX GitHub at line 242 of file G4DAWNFILESceneHandler.hh
Referenced by GetSystem().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/FukuiRenderer/include/G4DAWNFILESceneHandler.hh
geant4/tree/geant4-10.6-release/source/visualization/FukuiRenderer/src/G4DAWNFILESceneHandler.cc