ECCE @ EIC Software: G4VTHitsVector< T, Vector_t > Class Template Reference
G4VTHitsVector< T, Vector_t > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4THitsVector.hh>
Public Types
typedef G4VTHitsVector< T,
Vector_t > this_type
typedef T value_type
typedef Vector_t vector_type
typedef vector_type::iterator iterator
typedef vector_type::const_iterator const_iterator
typedef Vector_t::value_type store_type
typedef std::pair< G4int,
store_type > pair_t
typedef std::map< G4int,
store_type > map_t
typedef std::unordered_map
< G4int, store_type > uomap_t
typedef std::multimap< G4int,
store_type > mmap_t
typedef
std::unordered_multimap< G4int,
store_type > uommap_t
Public Member Functions
G4VTHitsVector (G4int init_size=0)
G4VTHitsVector (G4String detName, G4String colNam, G4int init_size=0)
virtual ~G4VTHitsVector ()
G4bool operator== (const this_type &rhs) const
virtual void DrawAllHits ()
virtual void PrintAllHits ()
Vector_t * GetContainer () const
Vector_t::size_type size ()
Vector_t::size_type GetIndex (iterator itr)
Vector_t::size_type GetIndex (const_iterator itr) const
template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0>
T * GetObject (G4int idx) const
template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0>
T * GetObject (iterator itr) const
template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0>
const T * GetObject (const_iterator itr) const
template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0>
T * GetObject (G4int idx) const
template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0>
T * GetObject (iterator itr) const
template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0>
const T * GetObject (const_iterator itr) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
Vector_t * GetVector () const
std::size_t entries () const
void clear ()
virtual G4VHit * GetHit (std::size_t) const
virtual std::size_t GetSize () const
map_t * GetMap () const
template<typename U = T, typename V = store_type, enable_if_t< (is_fundamental_t(U)&&is_pointer_t(V)), int > = 0>
store_type allocate () const
template<typename U = T, typename V = store_type, enable_if_t< (!is_fundamental_t(U)&&is_pointer_t(V)), int > = 0>
store_type allocate () const
template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0>
store_type null () const
template<typename U = T, typename V = store_type, enable_if_t< (is_fundamental_t(U)&&!is_pointer_t(V)), int > = 0>
store_type allocate () const
template<typename U = T, typename V = store_type, enable_if_t< (!is_fundamental_t(U)&&!is_pointer_t(V)), int > = 0>
store_type allocate () const
template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0>
store_type null () const
template<typename U , typename VectorU_t , enable_if_t< (is_pointer_t(typename VectorU_t::value_type)), int > = 0>
this_type & operator+= (const G4VTHitsVector< U, VectorU_t > &right) const
template<typename U , typename VectorU_t , enable_if_t< (!is_pointer_t(typename VectorU_t::value_type)), int > = 0>
this_type & operator+= (const G4VTHitsVector< U, VectorU_t > &right) const
template<typename U , typename MapU_t , enable_if_t< (is_pointer_t(typename MapU_t::mapped_type)), int > = 0>
this_type & operator+= (const G4VTHitsMap< U, MapU_t > &right) const
template<typename U , typename MapU_t , enable_if_t< !(is_pointer_t(typename MapU_t::mapped_type)), int > = 0>
this_type & operator+= (const G4VTHitsMap< U, MapU_t > &right) const
template<typename U = T, enable_if_t< is_same_t(U, T), int > = 0>
std::size_t add (const G4int &key, U *&aHit) const
template<typename U = T, enable_if_t< !is_same_t(U, T), int > = 0>
std::size_t add (const G4int &key, U *&aHit) const
template<typename U = T, enable_if_t< is_same_t(U, T), int > = 0>
std::size_t add (const G4int &key, U &aHit) const
template<typename U = T, enable_if_t< !is_same_t(U, T), int > = 0>
std::size_t add (const G4int &key, U &aHit) const
template<typename U = T, enable_if_t< is_same_t(U, T), int > = 0>
std::size_t set (const G4int &key, U *&aHit) const
template<typename U = T, enable_if_t< !is_same_t(U, T), int > = 0>
std::size_t set (const G4int &key, U *&aHit) const
template<typename U = T, enable_if_t< is_same_t(U, T), int > = 0>
std::size_t set (const G4int &key, U &aHit) const
template<typename U = T, enable_if_t< !is_same_t(U, T), int > = 0>
std::size_t set (const G4int &key, U &aHit) const
T * at (G4int key) const
T * operator[] (G4int key) const
Public Member Functions inherited from G4HitsCollection
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
G4HitsCollection ()
G4HitsCollection (G4String detName, G4String colNam)
virtual ~G4HitsCollection ()
G4bool operator== (const G4HitsCollection &right) const
Public Member Functions inherited from G4VHitsCollection
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
G4String GetName ()
G4String GetSDname ()
virtual G4VHit * GetHit (size_t) const
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
G4String GetName ()
G4String GetSDname ()
virtual G4VHit * GetHit (size_t) const
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
const G4String & GetName () const
const G4String & GetSDname () const
void SetColID (G4int i)
G4int GetColID () const
virtual G4VHit * GetHit (size_t) const
Protected Member Functions
template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0>
void resize (vector_type *&theHitsVector, const G4int &key) const
template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0>
void resize (vector_type *&theHitsVector, const G4int &key) const
vector_type * GetVector (const G4int &key) const
template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
void _assign (vector_type *&theHitsVector, const G4int &key, T &val) const
template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
void _assign (vector_type *&theHitsVector, const G4int &key, T *&val) const
template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
void _add (vector_type *&theHitsVector, const G4int &key, T &val) const
template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
void _add (vector_type *&theHitsVector, const G4int &key, T *&val) const
template<typename V , typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
void _add (vector_type *&theHitsVector, const G4int &key, V &val) const
template<typename V , typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
void _add (vector_type *&theHitsVector, const G4int &key, V *&val) const
template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
T & get (U &val) const
template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
void delete_contents (vector_type *&theHitsVector) const
template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0>
T & get_reference (U &val) const
template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0>
void _assign (vector_type *&theHitsVector, const G4int &key, T &val) const
template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0>
void _assign (vector_type *&theHitsVector, const G4int &key, T *&val) const
template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0>
void _add (vector_type *&theHitsVector, const G4int &key, T &val) const
template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0>
void _add (vector_type *&theHitsVector, const G4int &key, T *&val) const
template<typename V , typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0>
void _add (vector_type *&theHitsVector, const G4int &key, V &val) const
template<typename V , typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0>
void _add (vector_type *&theHitsVector, const G4int &key, V *&val) const
template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0>
void delete_contents (vector_type *&) const
template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0>
T & get_reference (U &val) const
Private Types
template<bool _Bp, typename _Tp = void>
using enable_if_t = typename std::enable_if< _Bp, _Tp >::type
Additional Inherited Members
Protected Attributes inherited from G4HitsCollection
void * theCollection
Detailed Description
template<typename T, typename Vector_t = std::deque<T*>>
class G4VTHitsVector< T, Vector_t >
Definition at line 52 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 52 of file G4THitsVector.hh
Member Typedef Documentation
template<typename T, typename Vector_t = std::deque<T*>> typedef vector_type::const_iterator G4VTHitsVector< T, Vector_t >::const_iterator
Definition at line 59 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 59 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<bool _Bp, typename _Tp = void> using G4VTHitsVector< T, Vector_t >::enable_if_t = typename std::enable_if<_Bp, _Tp>::type private
Definition at line 84 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 84 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef vector_type::iterator G4VTHitsVector< T, Vector_t >::iterator
Definition at line 58 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 58 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef std::map<G4int, store_type> G4VTHitsVector< T, Vector_t >::map_t
Definition at line 63 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 63 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef std::multimap<G4int, store_type> G4VTHitsVector< T, Vector_t >::mmap_t
Definition at line 65 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 65 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef std::pair<G4int, store_type> G4VTHitsVector< T, Vector_t >::pair_t
Definition at line 62 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 62 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef Vector_t::value_type G4VTHitsVector< T, Vector_t >::store_type
Definition at line 61 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 61 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef G4VTHitsVector<T, Vector_t> G4VTHitsVector< T, Vector_t >::this_type
Definition at line 55 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 55 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef std::unordered_map<G4int, store_type> G4VTHitsVector< T, Vector_t >::uomap_t
Definition at line 64 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 64 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef std::unordered_multimap<G4int, store_type> G4VTHitsVector< T, Vector_t >::uommap_t
Definition at line 66 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 66 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef T G4VTHitsVector< T, Vector_t >::value_type
Definition at line 56 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 56 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> typedef Vector_t G4VTHitsVector< T, Vector_t >::vector_type
Definition at line 57 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 57 of file G4THitsVector.hh
Constructor & Destructor Documentation
template<typename T , typename Vector_t > G4VTHitsVector< T, Vector_t >::G4VTHitsVector (G4int init_size = 0)
Definition at line 578 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 578 of file G4THitsVector.hh
template<typename T , typename Vector_t > G4VTHitsVector< T, Vector_t >::G4VTHitsVector (G4String detName, G4String colNam, G4int init_size = 0)
Definition at line 591 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 591 of file G4THitsVector.hh
References G4VTHitsVector< T, Vector_t >::GetVector(), G4VTHitsVector< T, Vector_t >::resize(), and G4HitsCollection::theCollection.
template<typename T , typename Vector_t > G4VTHitsVector< T, Vector_t >::~G4VTHitsVector () virtual
Definition at line 606 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 606 of file G4THitsVector.hh
Member Function Documentation
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_add (vector_type *& theHitsVector, const G4int & key, T & val) const inline protected
Definition at line 455 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 455 of file G4THitsVector.hh
Referenced by G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::add().
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_add (vector_type *& theHitsVector, const G4int & key, T *& val) const inline protected
Definition at line 462 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 462 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename V , typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_add (vector_type *& theHitsVector, const G4int & key, V & val) const inline protected
Definition at line 469 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 469 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename V , typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_add (vector_type *& theHitsVector, const G4int & key, V *& val) const inline protected
Definition at line 476 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 476 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_add (vector_type *& theHitsVector, const G4int & key, T & val) const inline protected
Definition at line 524 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 524 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_add (vector_type *& theHitsVector, const G4int & key, T *& val) const inline protected
Definition at line 531 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 531 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename V , typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_add (vector_type *& theHitsVector, const G4int & key, V & val) const inline protected
Definition at line 539 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 539 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename V , typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_add (vector_type *& theHitsVector, const G4int & key, V *& val) const inline protected
Definition at line 547 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 547 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_assign (vector_type *& theHitsVector, const G4int & key, T & val) const inline protected
Definition at line 439 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 439 of file G4THitsVector.hh
Referenced by G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::resize(), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::set().
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_assign (vector_type *& theHitsVector, const G4int & key, T *& val) const inline protected
Definition at line 447 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 447 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_assign (vector_type *& theHitsVector, const G4int & key, T & val) const inline protected
Definition at line 509 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 509 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::_assign (vector_type *& theHitsVector, const G4int & key, T *& val) const inline protected
Definition at line 516 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 516 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, enable_if_t< is_same_t(U, T), int > = 0> std::size_t G4VTHitsVector< T, Vector_t >::add (const G4int & key, U *& aHit) const inline
Definition at line 278 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 278 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, enable_if_t< !is_same_t(U, T), int > = 0> std::size_t G4VTHitsVector< T, Vector_t >::add (const G4int & key, U *& aHit) const inline
Definition at line 289 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 289 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, enable_if_t< is_same_t(U, T), int > = 0> std::size_t G4VTHitsVector< T, Vector_t >::add (const G4int & key, U & aHit) const inline
Definition at line 302 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 302 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, enable_if_t< !is_same_t(U, T), int > = 0> std::size_t G4VTHitsVector< T, Vector_t >::add (const G4int & key, U & aHit) const inline
Definition at line 313 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 313 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, typename V = store_type, enable_if_t< (is_fundamental_t(U)&&is_pointer_t(V)), int > = 0> store_type G4VTHitsVector< T, Vector_t >::allocate () const inline
Definition at line 172 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 172 of file G4THitsVector.hh
Referenced by G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::add(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::operator+=(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::resize(), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::set().
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, typename V = store_type, enable_if_t< (!is_fundamental_t(U)&&is_pointer_t(V)), int > = 0> store_type G4VTHitsVector< T, Vector_t >::allocate () const inline
Definition at line 181 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 181 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, typename V = store_type, enable_if_t< (is_fundamental_t(U)&&!is_pointer_t(V)), int > = 0> store_type G4VTHitsVector< T, Vector_t >::allocate () const inline
Definition at line 198 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 198 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, typename V = store_type, enable_if_t< (!is_fundamental_t(U)&&!is_pointer_t(V)), int > = 0> store_type G4VTHitsVector< T, Vector_t >::allocate () const inline
Definition at line 206 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 206 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> T* G4VTHitsVector< T, Vector_t >::at (G4int key) const inline
Definition at line 383 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 383 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> iterator G4VTHitsVector< T, Vector_t >::begin () inline
Definition at line 138 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 138 of file G4THitsVector.hh
Referenced by Dicom2RunAction::EndOfRunAction(), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::GetIndex().
template<typename T, typename Vector_t = std::deque<T*>> const_iterator G4VTHitsVector< T, Vector_t >::begin () const inline
Definition at line 140 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 140 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> const_iterator G4VTHitsVector< T, Vector_t >::cbegin () const inline
Definition at line 142 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 142 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> const_iterator G4VTHitsVector< T, Vector_t >::cend () const inline
Definition at line 143 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 143 of file G4THitsVector.hh
template<typename T , typename Vector_t > void G4VTHitsVector< T, Vector_t >::clear (void) inline
Definition at line 668 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 668 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::delete_contents (vector_type *& theHitsVector) const inline protected
Definition at line 490 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 490 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0> void G4VTHitsVector< T, Vector_t >::delete_contents (vector_type *&) const inline protected
Definition at line 554 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 554 of file G4THitsVector.hh
template<typename T , typename Vector_t > void G4VTHitsVector< T, Vector_t >::DrawAllHits () virtual
Reimplemented from G4VHitsCollection.
Definition at line 641 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 641 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> iterator G4VTHitsVector< T, Vector_t >::end () inline
Definition at line 139 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 139 of file G4THitsVector.hh
Referenced by Dicom2RunAction::EndOfRunAction().
template<typename T, typename Vector_t = std::deque<T*>> const_iterator G4VTHitsVector< T, Vector_t >::end () const inline
Definition at line 141 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 141 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> std::size_t G4VTHitsVector< T, Vector_t >::entries () const inline
Definition at line 151 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 151 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> T& G4VTHitsVector< T, Vector_t >::get (U & val) const inline protected
Definition at line 483 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 483 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< is_pointer_t(U), int > = 0> T& G4VTHitsVector< T, Vector_t >::get_reference (U & val) const inline protected
Definition at line 498 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 498 of file G4THitsVector.hh
Referenced by G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::add(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::at(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::operator[](), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::set().
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< !is_pointer_t(U), int > = 0> T& G4VTHitsVector< T, Vector_t >::get_reference (U & val) const inline protected
Definition at line 559 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 559 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> Vector_t* G4VTHitsVector< T, Vector_t >::GetContainer () const inline
Definition at line 102 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 102 of file G4THitsVector.hh
Referenced by G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::begin(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::cbegin(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::cend(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::end(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::GetObject(), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::size().
template<typename T, typename Vector_t = std::deque<T*>> virtual G4VHit* G4VTHitsVector< T, Vector_t >::GetHit (std::size_t) const inline virtual
Definition at line 157 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 157 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> Vector_t::size_type G4VTHitsVector< T, Vector_t >::GetIndex (iterator itr) inline
Definition at line 108 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 108 of file G4THitsVector.hh
Referenced by Dicom2RunAction::EndOfRunAction().
template<typename T, typename Vector_t = std::deque<T*>> Vector_t::size_type G4VTHitsVector< T, Vector_t >::GetIndex (const_iterator itr) const inline
Definition at line 111 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 111 of file G4THitsVector.hh
template<typename T , typename Vector_t > G4VTHitsVector< T, Vector_t >::map_t * G4VTHitsVector< T, Vector_t >::GetMap () const inline
Definition at line 625 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 625 of file G4THitsVector.hh
References G4ThreadLocalStatic.
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0> T* G4VTHitsVector< T, Vector_t >::GetObject (G4int idx) const inline
Definition at line 115 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 115 of file G4THitsVector.hh
Referenced by Dicom2RunAction::EndOfRunAction().
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0> T* G4VTHitsVector< T, Vector_t >::GetObject (iterator itr) const inline
Definition at line 119 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 119 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0> const T* G4VTHitsVector< T, Vector_t >::GetObject (const_iterator itr) const inline
Definition at line 123 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 123 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0> T* G4VTHitsVector< T, Vector_t >::GetObject (G4int idx) const inline
Definition at line 127 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 127 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0> T* G4VTHitsVector< T, Vector_t >::GetObject (iterator itr) const inline
Definition at line 131 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 131 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0> const T* G4VTHitsVector< T, Vector_t >::GetObject (const_iterator itr) const inline
Definition at line 135 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 135 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> virtual std::size_t G4VTHitsVector< T, Vector_t >::GetSize () const inline virtual
Reimplemented from G4VHitsCollection.
Definition at line 158 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 158 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> Vector_t* G4VTHitsVector< T, Vector_t >::GetVector () const inline
Definition at line 146 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 146 of file G4THitsVector.hh
Referenced by G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::add(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::at(), G4VTHitsVector< T, Vector_t >::G4VTHitsVector(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::GetVector(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::operator+=(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::operator[](), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::set().
template<typename T, typename Vector_t = std::deque<T*>> vector_type* G4VTHitsVector< T, Vector_t >::GetVector (const G4int & key) const inline protected
Definition at line 426 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 426 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0> store_type G4VTHitsVector< T, Vector_t >::null () const inline
Definition at line 187 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 187 of file G4THitsVector.hh
Referenced by G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::operator+=(), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::resize().
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0> store_type G4VTHitsVector< T, Vector_t >::null () const inline
Definition at line 212 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 212 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U , typename VectorU_t , enable_if_t< (is_pointer_t(typename VectorU_t::value_type)), int > = 0> this_type& G4VTHitsVector< T, Vector_t >::operator+= (const G4VTHitsVector< U, VectorU_t > & right) const inline
Definition at line 222 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 222 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U , typename VectorU_t , enable_if_t< (!is_pointer_t(typename VectorU_t::value_type)), int > = 0> this_type& G4VTHitsVector< T, Vector_t >::operator+= (const G4VTHitsVector< U, VectorU_t > & right) const inline
Definition at line 236 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 236 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U , typename MapU_t , enable_if_t< (is_pointer_t(typename MapU_t::mapped_type)), int > = 0> this_type& G4VTHitsVector< T, Vector_t >::operator+= (const G4VTHitsMap< U, MapU_t > & right) const inline
Definition at line 249 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 249 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U , typename MapU_t , enable_if_t< !(is_pointer_t(typename MapU_t::mapped_type)), int > = 0> this_type& G4VTHitsVector< T, Vector_t >::operator+= (const G4VTHitsMap< U, MapU_t > & right) const inline
Definition at line 259 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 259 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> G4bool G4VTHitsVector< T, Vector_t >::operator== (const this_type & rhs) const
Definition at line 616 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 616 of file G4THitsVector.hh
References G4VHitsCollection::collectionName.
template<typename T, typename Vector_t = std::deque<T*>> T* G4VTHitsVector< T, Vector_t >::operator[] (G4int key) const inline
Definition at line 390 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 390 of file G4THitsVector.hh
template<typename T , typename Vector_t > void G4VTHitsVector< T, Vector_t >::PrintAllHits () virtual
Reimplemented from G4VHitsCollection.
Definition at line 647 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 647 of file G4THitsVector.hh
References G4cout, and G4endl.
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (is_pointer_t(U)), int > = 0> void G4VTHitsVector< T, Vector_t >::resize (vector_type *& theHitsVector, const G4int & key) const inline protected
Definition at line 401 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 401 of file G4THitsVector.hh
Referenced by G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::at(), G4VTHitsVector< T, Vector_t >::G4VTHitsVector(), G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::GetVector(), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::operator[]().
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = store_type, enable_if_t< (!is_pointer_t(U)), int > = 0> void G4VTHitsVector< T, Vector_t >::resize (vector_type *& theHitsVector, const G4int & key) const inline protected
Definition at line 418 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 418 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, enable_if_t< is_same_t(U, T), int > = 0> std::size_t G4VTHitsVector< T, Vector_t >::set (const G4int & key, U *& aHit) const inline
Definition at line 330 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 330 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, enable_if_t< !is_same_t(U, T), int > = 0> std::size_t G4VTHitsVector< T, Vector_t >::set (const G4int & key, U *& aHit) const inline
Definition at line 341 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 341 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, enable_if_t< is_same_t(U, T), int > = 0> std::size_t G4VTHitsVector< T, Vector_t >::set (const G4int & key, U & aHit) const inline
Definition at line 360 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 360 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> template<typename U = T, enable_if_t< !is_same_t(U, T), int > = 0> std::size_t G4VTHitsVector< T, Vector_t >::set (const G4int & key, U & aHit) const inline
Definition at line 371 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 371 of file G4THitsVector.hh
template<typename T, typename Vector_t = std::deque<T*>> Vector_t::size_type G4VTHitsVector< T, Vector_t >::size (void) inline
Definition at line 105 of file G4THitsVector.hh.
View newest version in sPHENIX GitHub at line 105 of file G4THitsVector.hh
Referenced by Dicom2RunAction::EndOfRunAction(), and G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >::GetObject().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4THitsVector.hh