ECCE @ EIC Software: CLHEP::HepRotation Class Reference
CLHEP::HepRotation Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/Rotation.h>
Classes
class HepRotation_row
Public Member Functions
HepRotation ()
HepRotation (const HepRotation &m)
HepRotation (HepRotation &&m)=default
HepRotation (const HepRotationX &m)
HepRotation (const HepRotationY &m)
HepRotation (const HepRotationZ &m)
HepRotation & set (const Hep3Vector &axis, double delta)
HepRotation (const Hep3Vector &axis, double delta)
HepRotation & set (const HepAxisAngle &ax)
HepRotation (const HepAxisAngle &ax)
HepRotation & set (double phi, double theta, double psi)
HepRotation (double phi, double theta, double psi)
HepRotation & set (const HepEulerAngles &e)
HepRotation (const HepEulerAngles &e)
HepRotation (const Hep3Vector &colX, const Hep3Vector &colY, const Hep3Vector &colZ)
HepRotation & set (const Hep3Vector &colX, const Hep3Vector &colY, const Hep3Vector &colZ)
HepRotation & setRows (const Hep3Vector &rowX, const Hep3Vector &rowY, const Hep3Vector &rowZ)
HepRotation & set (const HepRotationX &r)
HepRotation & set (const HepRotationY &r)
HepRotation & set (const HepRotationZ &r)
HepRotation & operator= (const HepRotation &r)
HepRotation & operator= (HepRotation &&r)=default
HepRotation & operator= (const HepRotationX &r)
HepRotation & operator= (const HepRotationY &r)
HepRotation & operator= (const HepRotationZ &r)
HepRotation & set (const HepRep3x3 &m)
HepRotation (const HepRep3x3 &m)
~HepRotation ()
Hep3Vector colX () const
Hep3Vector colY () const
Hep3Vector colZ () const
Hep3Vector rowX () const
Hep3Vector rowY () const
Hep3Vector rowZ () const
double xx () const
double xy () const
double xz () const
double yx () const
double yy () const
double yz () const
double zx () const
double zy () const
double zz () const
HepRep3x3 rep3x3 () const
const HepRotation_row operator[] (int) const
double operator() (int, int) const
double getPhi () const
double getTheta () const
double getPsi () const
double phi () const
double theta () const
double psi () const
HepEulerAngles eulerAngles () const
double getDelta () const
Hep3Vector getAxis () const
double delta () const
Hep3Vector axis () const
HepAxisAngle axisAngle () const
void getAngleAxis (double &delta, Hep3Vector &axis) const
double phiX () const
double phiY () const
double phiZ () const
double thetaX () const
double thetaY () const
double thetaZ () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
double xt () const
double yt () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepRep4x4 rep4x4 () const
void setPhi (double phi)
void setTheta (double theta)
void setPsi (double psi)
void setAxis (const Hep3Vector &axis)
void setDelta (double delta)
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
bool isIdentity () const
int compare (const HepRotation &r) const
bool operator== (const HepRotation &r) const
bool operator!= (const HepRotation &r) const
bool operator< (const HepRotation &r) const
bool operator> (const HepRotation &r) const
bool operator<= (const HepRotation &r) const
bool operator>= (const HepRotation &r) const
double distance2 (const HepRotation &r) const
double howNear (const HepRotation &r) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
double distance2 (const HepBoost &lt) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoost &lt) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoost &lt, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
Hep3Vector operator() (const Hep3Vector &p) const
Hep3Vector operator* (const Hep3Vector &p) const
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &w) const
HepRotation operator* (const HepRotation &r) const
HepRotation operator* (const HepRotationX &rx) const
HepRotation operator* (const HepRotationY &ry) const
HepRotation operator* (const HepRotationZ &rz) const
HepRotation & operator*= (const HepRotation &r)
HepRotation & transform (const HepRotation &r)
HepRotation & operator*= (const HepRotationX &r)
HepRotation & operator*= (const HepRotationY &r)
HepRotation & operator*= (const HepRotationZ &r)
HepRotation & transform (const HepRotationX &r)
HepRotation & transform (const HepRotationY &r)
HepRotation & transform (const HepRotationZ &r)
HepRotation & rotateX (double delta)
HepRotation & rotateY (double delta)
HepRotation & rotateZ (double delta)
HepRotation & rotate (double delta, const Hep3Vector &axis)
HepRotation & rotate (double delta, const Hep3Vector *axis)
HepRotation & rotateAxes (const Hep3Vector &newX, const Hep3Vector &newY, const Hep3Vector &newZ)
HepRotation inverse () const
HepRotation & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Static Public Attributes
static DLL_API const HepRotation IDENTITY
Protected Member Functions
HepRotation (double mxx, double mxy, double mxz, double myx, double myy, double myz, double mzx, double mzy, double mzz)
Protected Attributes
double rxx
double rxy
double rxz
double ryx
double ryy
double ryz
double rzx
double rzy
double rzz
Private Member Functions
bool setCols (const Hep3Vector &u1, const Hep3Vector &u2, const Hep3Vector &u3, double u1u2, Hep3Vector &v1, Hep3Vector &v2, Hep3Vector &v3) const
void setArbitrarily (const Hep3Vector &colX, Hep3Vector &v1, Hep3Vector &v2, Hep3Vector &v3) const
Friends
HepRotation operator* (const HepRotationX &rx, const HepRotation &r)
HepRotation operator* (const HepRotationY &ry, const HepRotation &r)
HepRotation operator* (const HepRotationZ &rz, const HepRotation &r)
Detailed Description
Author
Definition at line 46 of file Rotation.h.
View newest version in sPHENIX GitHub at line 46 of file Rotation.h
Constructor & Destructor Documentation
CLHEP::HepRotation::HepRotation () inline
Referenced by rotateAxes().
CLHEP::HepRotation::HepRotation (const HepRotation & m) inline
CLHEP::HepRotation::HepRotation (HepRotation && m) inline default
CLHEP::HepRotation::HepRotation (const HepRotationX & m) inline
CLHEP::HepRotation::HepRotation (const HepRotationY & m) inline
CLHEP::HepRotation::HepRotation (const HepRotationZ & m) inline
CLHEP::HepRotation::HepRotation (const Hep3Vector & axis, double delta)
Definition at line 54 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 54 of file RotationA.cc
CLHEP::HepRotation::HepRotation (const HepAxisAngle & ax)
Definition at line 61 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 61 of file RotationA.cc
References CLHEP::HepAxisAngle::axis(), and CLHEP::HepAxisAngle::delta().
CLHEP::HepRotation::HepRotation (double phi, double theta, double psi)
Definition at line 57 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 57 of file RotationE.cc
CLHEP::HepRotation::HepRotation (const HepEulerAngles & e)
Definition at line 64 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 64 of file RotationE.cc
References CLHEP::HepEulerAngles::phi(), CLHEP::HepEulerAngles::psi(), and CLHEP::HepEulerAngles::theta().
CLHEP::HepRotation::HepRotation (const Hep3Vector & colX, const Hep3Vector & colY, const Hep3Vector & colZ)
Definition at line 135 of file RotationC.cc.
View newest version in sPHENIX GitHub at line 135 of file RotationC.cc
CLHEP::HepRotation::HepRotation (const HepRep3x3 & m) inline
CLHEP::HepRotation::~HepRotation () inline
CLHEP::HepRotation::HepRotation (double mxx, double mxy, double mxz, double myx, double myy, double myz, double mzx, double mzy, double mzz) inline protected
Member Function Documentation
Hep3Vector CLHEP::HepRotation::axis () const
Definition at line 79 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 79 of file RotationA.cc
References kdfinder::abs(), e, eps, rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, rzz, CLHEP::Hep3Vector::unit(), x, y, and z.
Referenced by axisAngle(), export_G4RotationMatrix(), rectify(), and setDelta().
HepAxisAngle CLHEP::HepRotation::axisAngle () const
Definition at line 124 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 124 of file RotationA.cc
References axis(), and delta().
Referenced by CLHEP::HepLorentzRotation::decompose(), and decompose().
HepLorentzVector CLHEP::HepRotation::col1 () const inline
HepLorentzVector CLHEP::HepRotation::col2 () const inline
HepLorentzVector CLHEP::HepRotation::col3 () const inline
HepLorentzVector CLHEP::HepRotation::col4 () const inline
Hep3Vector CLHEP::HepRotation::colX () const inline
Referenced by G4tgbVolume::ConstructG4PhysVol(), G4tgbGeometryDumper::DumpPVPlacement(), and export_G4RotationMatrix().
Hep3Vector CLHEP::HepRotation::colY () const inline
Referenced by G4tgbVolume::ConstructG4PhysVol(), G4tgbGeometryDumper::DumpPVPlacement(), and export_G4RotationMatrix().
Hep3Vector CLHEP::HepRotation::colZ () const inline
Referenced by G4tgbVolume::ConstructG4PhysVol(), G4tgbGeometryDumper::DumpPVPlacement(), and export_G4RotationMatrix().
int CLHEP::HepRotation::compare (const HepRotation & r) const
Definition at line 177 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 177 of file Rotation.cc
References rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, and rzz.
Referenced by export_G4ThreeVector().
void CLHEP::HepRotation::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 23 of file RotationP.cc.
View newest version in sPHENIX GitHub at line 23 of file RotationP.cc
References axisAngle(), and CLHEP::Hep3Vector::set().
void CLHEP::HepRotation::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 28 of file RotationP.cc.
View newest version in sPHENIX GitHub at line 28 of file RotationP.cc
References axisAngle(), and CLHEP::Hep3Vector::set().
double CLHEP::HepRotation::delta () const
Definition at line 66 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 66 of file RotationA.cc
References CLHEP::pi, rxx, ryy, and rzz.
Referenced by axisAngle(), export_G4RotationMatrix(), rectify(), and setAxis().
double CLHEP::HepRotation::distance2 (const HepRotation & r) const
Definition at line 33 of file RotationP.cc.
View newest version in sPHENIX GitHub at line 33 of file RotationP.cc
References rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, rzz, and sum.
Referenced by CLHEP::HepLorentzRotation::distance2(), distance2(), howNear(), CLHEP::HepLorentzRotation::isNear(), and isNear().
double CLHEP::HepRotation::distance2 (const HepBoost & lt) const
Definition at line 39 of file RotationL.cc.
View newest version in sPHENIX GitHub at line 39 of file RotationL.cc
References distance2().
double CLHEP::HepRotation::distance2 (const HepLorentzRotation & lt) const
Definition at line 29 of file RotationL.cc.
View newest version in sPHENIX GitHub at line 29 of file RotationL.cc
References a, b, CLHEP::Hep3Vector::beta(), CLHEP::HepLorentzRotation::decompose(), distance2(), and r.
HepEulerAngles CLHEP::HepRotation::eulerAngles () const
Definition at line 201 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 201 of file RotationE.cc
References c1, CLHEP::correctPsiPhi(), rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, rzz, s1, and CLHEP::safe_acos().
Referenced by phi(), and psi().
void CLHEP::HepRotation::getAngleAxis (double & delta, Hep3Vector & axis) const
Definition at line 152 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 152 of file Rotation.cc
References x, xx(), xy(), xz(), y, yx(), yy(), yz(), z, zx(), zy(), and zz().
Hep3Vector CLHEP::HepRotation::getAxis () const inline
Referenced by export_G4RotationMatrix().
double CLHEP::HepRotation::getDelta () const inline
Referenced by export_G4RotationMatrix().
double CLHEP::HepRotation::getPhi () const inline
Referenced by export_G4RotationMatrix(), and export_G4ThreeVector().
double CLHEP::HepRotation::getPsi () const inline
Referenced by export_G4RotationMatrix().
double CLHEP::HepRotation::getTheta () const inline
Referenced by export_G4RotationMatrix(), and export_G4ThreeVector().
static double CLHEP::HepRotation::getTolerance () inline static
Referenced by export_G4ThreeVector().
double CLHEP::HepRotation::howNear (const HepRotation & r) const
Definition at line 41 of file RotationP.cc.
View newest version in sPHENIX GitHub at line 41 of file RotationP.cc
References distance2().
Referenced by export_G4ThreeVector(), and export_G4TwoVector().
double CLHEP::HepRotation::howNear (const HepBoost & lt) const
Definition at line 47 of file RotationL.cc.
View newest version in sPHENIX GitHub at line 47 of file RotationL.cc
References distance2().
double CLHEP::HepRotation::howNear (const HepLorentzRotation & lt) const
Definition at line 43 of file RotationL.cc.
View newest version in sPHENIX GitHub at line 43 of file RotationL.cc
References distance2().
HepRotation CLHEP::HepRotation::inverse () const inline
Referenced by G4GMocrenFileSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddSolid(), G4INCLXXInterface::ApplyYourself(), G4ReflectedSolid::BoundingLimits(), G4ScaledSolid::CalculateExtent(), G4ReflectedSolid::CalculateExtent(), G4NavigationLogger::CheckAndReportBadNormal(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), F04DetectorConstruction::ConstructDetector(), WLSDetectorConstruction::ConstructDetector(), G4NRESP71M03::DKINMA(), B5HodoscopeHit::Draw(), B5EmCalorimeterHit::Draw(), B5HadCalorimeterHit::Draw(), G4GMocrenFileSceneHandler::EndSavingGdd(), export_G4RotationMatrix(), export_G4Transform3D(), G4DisplacedSolid::G4DisplacedSolid(), G4ErrorCylSurfaceTarget::G4ErrorCylSurfaceTarget(), G4PVPlacement::G4PVPlacement(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4QuadrupoleMagField::GetFieldValue(), G4VPhysicalVolume::GetObjectRotation(), G4TwistTubsHypeSide::GetRhoAtPZ(), NeuronLoadDataFile::NeuralNetworkDATAfile(), G4STRead::PhysvolRead(), DetectorConstruction::PlaceWithEulerAngles(), DetectorConstruction::PlaceWithInverseMatrix(), G4TwistTubsSide::ProjectAtPXPZ(), G4TwistTrapParallelSide::ProjectPoint(), G4TwistBoxSide::ProjectPoint(), G4TwistTrapAlphaSide::ProjectPoint(), DetectorConstruction::ResiduesView(), G4LogicalCrystalVolume::SetMillerOrientation(), NeuronLoadDataFile::SingleNeuronSWCfile(), and G4GDMLWriteStructure::TraverseVolumeTree().
HepRotation& CLHEP::HepRotation::invert () inline
Referenced by CCalRotationMatrixFactory::AddMatrix(), export_G4RotationMatrix(), G4LatticePhysical::SetPhysicalOrientation(), and setRows().
bool CLHEP::HepRotation::isIdentity () const
Definition at line 171 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 171 of file Rotation.cc
References rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, and rzz.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), export_G4RotationMatrix(), and G4PVPlacement::NewPtrRotMatrix().
bool CLHEP::HepRotation::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 45 of file RotationP.cc.
View newest version in sPHENIX GitHub at line 45 of file RotationP.cc
References distance2(), and epsilon().
Referenced by export_G4ThreeVector(), and export_G4TwoVector().
bool CLHEP::HepRotation::isNear (const HepBoost & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 56 of file RotationL.cc.
View newest version in sPHENIX GitHub at line 56 of file RotationL.cc
References distance2(), and epsilon().
bool CLHEP::HepRotation::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 51 of file RotationL.cc.
View newest version in sPHENIX GitHub at line 51 of file RotationL.cc
References distance2(), and epsilon().
double CLHEP::HepRotation::norm2 () const
Definition at line 50 of file RotationP.cc.
View newest version in sPHENIX GitHub at line 50 of file RotationP.cc
References rxx, ryy, and rzz.
Referenced by CLHEP::HepBoostX::distance2(), CLHEP::HepBoostZ::distance2(), CLHEP::HepBoostY::distance2(), CLHEP::HepBoost::distance2(), CLHEP::HepLorentzRotation::distance2(), CLHEP::HepBoostZ::isNear(), CLHEP::HepBoostX::isNear(), CLHEP::HepBoostY::isNear(), CLHEP::HepBoost::isNear(), CLHEP::HepLorentzRotation::isNear(), and CLHEP::HepLorentzRotation::norm2().
bool CLHEP::HepRotation::operator!= (const HepRotation & r) const inline
double CLHEP::HepRotation::operator() (int i, int j) const
Definition at line 27 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 27 of file Rotation.cc
References xx(), xy(), xz(), yx(), yy(), yz(), zx(), zy(), and zz().
Hep3Vector CLHEP::HepRotation::operator() (const Hep3Vector & p) const inline
HepLorentzVector CLHEP::HepRotation::operator() (const HepLorentzVector & w) const inline
Hep3Vector CLHEP::HepRotation::operator* (const Hep3Vector & p) const inline
HepLorentzVector CLHEP::HepRotation::operator* (const HepLorentzVector & w) const inline
HepRotation CLHEP::HepRotation::operator* (const HepRotation & r) const inline
HepRotation CLHEP::HepRotation::operator* (const HepRotationX & rx) const inline
HepRotation CLHEP::HepRotation::operator* (const HepRotationY & ry) const inline
HepRotation CLHEP::HepRotation::operator* (const HepRotationZ & rz) const inline
HepRotation& CLHEP::HepRotation::operator*= (const HepRotation & r) inline
HepRotation& CLHEP::HepRotation::operator*= (const HepRotationX & r) inline
HepRotation& CLHEP::HepRotation::operator*= (const HepRotationY & r) inline
HepRotation& CLHEP::HepRotation::operator*= (const HepRotationZ & r) inline
bool CLHEP::HepRotation::operator< (const HepRotation & r) const inline
bool CLHEP::HepRotation::operator<= (const HepRotation & r) const inline
HepRotation& CLHEP::HepRotation::operator= (const HepRotation & r) inline
HepRotation& CLHEP::HepRotation::operator= (HepRotation && r) inline default
HepRotation& CLHEP::HepRotation::operator= (const HepRotationX & r) inline
HepRotation& CLHEP::HepRotation::operator= (const HepRotationY & r) inline
HepRotation& CLHEP::HepRotation::operator= (const HepRotationZ & r) inline
bool CLHEP::HepRotation::operator== (const HepRotation & r) const inline
bool CLHEP::HepRotation::operator> (const HepRotation & r) const inline
bool CLHEP::HepRotation::operator>= (const HepRotation & r) const inline
const HepRotation_row CLHEP::HepRotation::operator[] (int) const inline
double CLHEP::HepRotation::phi () const
Definition at line 70 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 70 of file RotationE.cc
References eulerAngles(), CLHEP::HepEulerAngles::phi(), CLHEP::pi, rzx, rzy, and rzz.
Referenced by export_G4RotationMatrix(), export_G4ThreeVector(), export_G4TwoVector(), setPsi(), and setTheta().
double CLHEP::HepRotation::phiX () const
Definition at line 128 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 128 of file Rotation.cc
References xx(), and yx().
Referenced by G4HepRepFileSceneHandler::AddSolid(), BeamLineMagnetDetector::ConstructMe(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), and operator<<().
double CLHEP::HepRotation::phiY () const
Definition at line 132 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 132 of file Rotation.cc
References xy(), and yy().
Referenced by G4HepRepFileSceneHandler::AddSolid(), BeamLineMagnetDetector::ConstructMe(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), and operator<<().
double CLHEP::HepRotation::phiZ () const
Definition at line 136 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 136 of file Rotation.cc
References xz(), and yz().
Referenced by G4HepRepFileSceneHandler::AddSolid(), BeamLineMagnetDetector::ConstructMe(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), and operator<<().
std::ostream & CLHEP::HepRotation::print (std::ostream & os) const
Definition at line 21 of file RotationIO.cc.
View newest version in sPHENIX GitHub at line 21 of file RotationIO.cc
References xx(), xy(), xz(), yx(), yy(), yz(), zx(), zy(), and zz().
Referenced by PHG4BlockDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), DetectorConstruction::PlaceWithAxialRotations(), DetectorConstruction::PlaceWithDirectMatrix(), DetectorConstruction::PlaceWithEulerAngles(), DetectorConstruction::PlaceWithInverseMatrix(), G4ReflectedSolid::StreamInfo(), and G4DisplacedSolid::StreamInfo().
double CLHEP::HepRotation::psi () const
Definition at line 110 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 110 of file RotationE.cc
References eulerAngles(), CLHEP::pi, CLHEP::HepEulerAngles::psi(), rxz, ryz, and rzz.
Referenced by export_G4RotationMatrix(), setPhi(), and setTheta().
void CLHEP::HepRotation::rectify ()
Definition at line 152 of file RotationC.cc.
View newest version in sPHENIX GitHub at line 152 of file RotationC.cc
References axis(), delta(), rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, rzz, Acts::UnitConstants::u, and CLHEP::Hep3Vector::unit().
Referenced by CLHEP::HepLorentzRotation::decompose(), G4GDMLWriteDefine::GetAngles(), PHG4GDMLWriteDefine::GetAngles(), and G4GDMLReadDefine::GetRotationMatrix().
HepRep3x3 CLHEP::HepRotation::rep3x3 () const inline
Referenced by G4tgbGeometryDumper::MatDeterminant().
HepRep4x4 CLHEP::HepRotation::rep4x4 () const inline
Referenced by CLHEP::operator*(), CLHEP::HepBoost::operator*(), and CLHEP::HepLorentzRotation::set().
HepRotation & CLHEP::HepRotation::rotate (double delta, const Hep3Vector & axis)
Definition at line 46 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 46 of file Rotation.cc
References dx, dy, dz, CLHEP::Hep3Vector::mag(), transform(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4tgbPlaceParamCircle::ComputeTransformation(), DNAParser::CreateCutSolid(), export_G4TwoVector(), DetectorConstruction::PlaceWithAxialRotations(), and CLHEP::Hep3Vector::rotate().
HepRotation& CLHEP::HepRotation::rotate (double delta, const Hep3Vector * axis) inline
HepRotation & CLHEP::HepRotation::rotateAxes (const Hep3Vector & newX, const Hep3Vector & newY, const Hep3Vector & newZ)
Definition at line 104 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 104 of file Rotation.cc
References kdfinder::abs(), CLHEP::Hep3Vector::cross(), CLHEP::Hep3Vector::dot(), HepRotation(), CLHEP::Hep3Vector::mag2(), transform(), w, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CCalRotationMatrixFactory::AddMatrix(), and export_G4RotationMatrix().
HepRotation & CLHEP::HepRotation::rotateX (double delta)
Definition at line 65 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 65 of file Rotation.cc
References c1, ryx, ryy, ryz, rzx, rzy, rzz, s1, x1, y1, and z1.
Referenced by AllSi_Al_support_Detector::addDetectorSection(), EicFRichDetector::addDetectorSection(), PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_sector2(), PHG4mRICHDetector::build_mRICH_wall_eside(), PHG4mRICHDetector::build_mRICH_wall_eside_proj(), PHG4mRICHDetector::build_mRICH_wall_hside(), PHG4TTLDetector::BuildBarrelTTL(), PHG4TTLDetector::BuildForwardTTL(), G4tgbRotationMatrix::BuildG4RotMatrixFrom3(), NeuronLoadDataFile::ComputeTransformation(), G4MIRDLiver::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDRightLeg::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDHead::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDRightBreast::Construct(), G4MIRDTrunk::Construct(), G4MIRDUterus::Construct(), G4MIRDRightArmBone::Construct(), B5DetectorConstruction::Construct(), FCALTestbeamSetup::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), DetectorConstruction::ConstructCalorimeter(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), DetectorConstruction::ConstructLine(), PHG4EnvelopeDetector::ConstructMe(), EICG4ZDCDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), PHG4CEmcTestBeamDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), G4EicDircDetector::ConstructMe(), PHG4EICForwardEcalDetector::ConstructMe(), PHG4BackwardHcalDetector::ConstructMe(), PHG4ForwardHcalDetector::ConstructMe(), PHG4ProjCrystalCalorimeterDetector::ConstructMe(), PHG4CrystalCalorimeterDetector::ConstructMe(), PHG4LFHcalDetector::ConstructMe(), PHG4ForwardDualReadoutDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), PHG4ForwardEcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4ProjCrystalCalorimeterDetector::ConstructProjectiveCrystals(), PHG4OuterHcalDetector::ConstructSteelPlate(), PHG4LFHcalDetector::ConstructTower(), export_G4RotationMatrix(), export_G4ThreeVector(), LaserDrivenBeamLine::FaradayCup(), PHG4ProjCrystalCalorimeterDetector::Fill4x4Unit(), PHG4ProjCrystalCalorimeterDetector::FillSpecialUnit(), G4tgrUtils::GetRotationFromDirection(), G4GDMLReadDefine::GetRotationMatrix(), LXeMainVolume::LXeMainVolume(), G4GDMLReadParamvol::ParametersRead(), CML2Acc1::primaryCollimator(), CML2AcceleratorConstruction::rotateAccelerator(), CexmcSetup::RotateMatrix(), G4VScoringMesh::RotateX(), CML2Acc1::SetJawAperture(), CML2Acc2::SetJawAperture(), CML2AccSaturn::SetJawAperture(), DicomIntersectVolume::SetNewValue(), XrayFluoPlaneDetectorConstruction::UpdateGeometry(), XrayFluoMercuryDetectorConstruction::UpdateGeometry(), and XrayFluoDetectorConstruction::UpdateGeometry().
HepRotation & CLHEP::HepRotation::rotateY (double delta)
Definition at line 78 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 78 of file Rotation.cc
References c1, rxx, rxy, rxz, rzx, rzy, rzz, s1, x1, y1, and z1.
Referenced by AllSi_Al_support_Detector::addDetectorSection(), EicFRichDetector::addDetectorSection(), G4INCLXXInterface::ApplyYourself(), B5DetectorConstruction::B5DetectorConstruction(), PHG4mRICHDetector::build_mRICH_wall_eside_proj(), PHG4mRICHDetector::build_mRICH_wall_hside(), PHG4TTLDetector::BuildBarrelTTL(), G4tgbRotationMatrix::BuildG4RotMatrixFrom3(), LaserDrivenBeamLine::Collimator(), NeuronLoadDataFile::ComputeTransformation(), G4MIRDRightLeg::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDRightBreast::Construct(), G4MIRDPancreas::Construct(), G4MIRDTrunk::Construct(), G4MIRDHead::Construct(), G4MIRDLeftBreast::Construct(), B3DetectorConstruction::Construct(), IORTDetectorConstruction::ConstructDisc(), DetectorConstruction::ConstructLine(), EICG4RPDetector::ConstructMe(), PHG4PSTOFDetector::ConstructMe(), PHG4EnvelopeDetector::ConstructMe(), EICG4ZDCDetector::ConstructMe(), EICG4B0Detector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), PHG4CEmcTestBeamDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), PHG4BbcDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), PHG4EICForwardEcalDetector::ConstructMe(), PHG4BackwardHcalDetector::ConstructMe(), PHG4ForwardHcalDetector::ConstructMe(), PHG4ProjCrystalCalorimeterDetector::ConstructMe(), PHG4CrystalCalorimeterDetector::ConstructMe(), PHG4LFHcalDetector::ConstructMe(), PHG4ForwardDualReadoutDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4ForwardEcalDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), PHG4MvtxDetector::ConstructMvtxPassiveVol(), PHG4ProjCrystalCalorimeterDetector::ConstructProjectiveCrystals(), PHG4LFHcalDetector::ConstructTower(), G4NeutronBetaDecayChannel::DecayIt(), LaserDrivenBeamLine::Entrancehole(), LaserDrivenBeamLine::EntrancePipe(), LaserDrivenBeamLine::Exithole(), LaserDrivenBeamLine::ExitPipe(), LaserDrivenBeamLine::ExitWindow(), export_G4RotationMatrix(), export_G4ThreeVector(), LaserDrivenBeamLine::FaradayCup(), PHG4ProjCrystalCalorimeterDetector::Fill4x4Unit(), PHG4ProjCrystalCalorimeterDetector::FillSpecialUnit(), LaserDrivenBeamLine::FinalCollimator(), G4tgrUtils::GetRotationFromDirection(), G4GDMLReadDefine::GetRotationMatrix(), PassiveProtonBeamLine::HadrontherapyBeamCollimators(), PassiveCarbonBeamLine::HadrontherapyBeamFinalCollimator(), PassiveProtonBeamLine::HadrontherapyBeamFinalCollimator(), PassiveCarbonBeamLine::HadrontherapyBeamNozzle(), PassiveProtonBeamLine::HadrontherapyBeamNozzle(), PassiveProtonBeamLine::HadrontherapyBeamScatteringFoils(), PassiveCarbonBeamLine::HadrontherapyPMMACollimator(), TrentoPassiveProtonBeamLine::HadrontherapyRidgeFilter(), PassiveCarbonBeamLine::HadrontherapyRippleFilter(), Collimator100BeamLine::IortBeamLineBlocks(), Collimator50BeamLine::IortBeamLineBlocks(), Collimator40BeamLine::IortBeamLineBlocks(), Collimator60BeamLine::IortBeamLineBlocks(), Collimator70BeamLine::IortBeamLineBlocks(), Collimator80BeamLine::IortBeamLineBlocks(), Collimator80BeamLine::IortBeamLineFinalCollimator(), Collimator100BeamLine::IortBeamLineFinalCollimator(), Collimator40BeamLine::IortBeamLineFinalCollimator(), Collimator70BeamLine::IortBeamLineFinalCollimator(), Collimator50BeamLine::IortBeamLineFinalCollimator(), Collimator60BeamLine::IortBeamLineFinalCollimator(), Collimator60BeamLine::IortBeamLineJunctions(), Collimator100BeamLine::IortBeamLineJunctions(), Collimator80BeamLine::IortBeamLineJunctions(), Collimator50BeamLine::IortBeamLineJunctions(), Collimator70BeamLine::IortBeamLineJunctions(), Collimator40BeamLine::IortBeamLineJunctions(), Collimator80BeamLine::IortBeamLineMonitorChambers(), Collimator100BeamLine::IortBeamLineMonitorChambers(), Collimator40BeamLine::IortBeamLineMonitorChambers(), Collimator50BeamLine::IortBeamLineMonitorChambers(), Collimator60BeamLine::IortBeamLineMonitorChambers(), Collimator70BeamLine::IortBeamLineMonitorChambers(), Collimator100BeamLine::IortBeamLineTitaniumWindows(), Collimator60BeamLine::IortBeamLineTitaniumWindows(), Collimator40BeamLine::IortBeamLineTitaniumWindows(), Collimator70BeamLine::IortBeamLineTitaniumWindows(), Collimator50BeamLine::IortBeamLineTitaniumWindows(), Collimator80BeamLine::IortBeamLineTitaniumWindows(), Collimator80BeamLine::IortBeamLineVacuumSource(), Collimator100BeamLine::IortBeamLineVacuumSource(), Collimator70BeamLine::IortBeamLineVacuumSource(), Collimator50BeamLine::IortBeamLineVacuumSource(), Collimator60BeamLine::IortBeamLineVacuumSource(), Collimator40BeamLine::IortBeamLineVacuumSource(), LXeMainVolume::LXeMainVolume(), LXeWLSSlab::LXeWLSSlab(), G4GDMLReadParamvol::ParametersRead(), PHG4BarrelEcalDetector::PlaceTower(), DetectorConstruction::PlaceWithAxialRotations(), LaserDrivenBeamLine::Quadrupole(), CML2AcceleratorConstruction::rotateAccelerator(), CexmcSetup::RotateMatrix(), G4VScoringMesh::RotateY(), B5DetectorConstruction::SetArmAngle(), CML2Acc1::SetJawAperture(), CML2Acc2::SetJawAperture(), CML2AccSaturn::SetJawAperture(), G4LogicalCrystalVolume::SetMillerOrientation(), and DicomIntersectVolume::SetNewValue().
HepRotation & CLHEP::HepRotation::rotateZ (double delta)
Definition at line 91 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 91 of file Rotation.cc
References c1, rxx, rxy, rxz, ryx, ryy, ryz, s1, x1, y1, and z1.
Referenced by AllSi_Al_support_Detector::addDetectorSection(), EicFRichDetector::addDetectorSection(), G4VTwistSurface::AmIOnLeftSide(), G4INCLXXInterface::ApplyYourself(), PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_sector2(), PHG4TTLDetector::BuildBarrelTTL(), PHG4TTLDetector::BuildForwardTTL(), G4tgbRotationMatrix::BuildG4RotMatrixFrom3(), HadrontherapyModulator::BuildSteps(), G4VDivisionParameterisation::ChangeRotMatrix(), NeuronLoadDataFile::ComputeTransformation(), H02DetectorConstruction::Construct(), ExN04DetectorConstruction::Construct(), G4MIRDThyroid::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDRightBreast::Construct(), G4MIRDRightLung::Construct(), RE05DetectorConstruction::Construct(), B3DetectorConstruction::Construct(), FCALCryostatVolumes::Construct(), FCALEMModule::Construct(), FCALHadModule::Construct(), doiPETDetectorConstruction::Construct(), PHG4InnerHcalDetector::ConstructInnerHcal(), PHG4InttDetector::ConstructIntt(), DetectorConstruction::ConstructLine(), G4JLeicVTXDetector::ConstructMe(), G4JLeicDIRCDetector::ConstructMe(), PHG4PSTOFDetector::ConstructMe(), PHG4EnvelopeDetector::ConstructMe(), EICG4ZDCDetector::ConstructMe(), PHG4CylinderStripDetector::ConstructMe(), PHG4ConeDetector::ConstructMe(), PHG4BlockDetector::ConstructMe(), PHG4CylinderDetector::ConstructMe(), AllSiliconTrackerDetector::ConstructMe(), PHG4CEmcTestBeamDetector::ConstructMe(), PHG4EPDDetector::ConstructMe(), PHG4TpcEndCapDetector::ConstructMe(), G4LBLVtxDetector::ConstructMe(), PHG4ZDCDetector::ConstructMe(), G4EicDircDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), PHG4EICForwardEcalDetector::ConstructMe(), PHG4BackwardHcalDetector::ConstructMe(), PHG4ForwardHcalDetector::ConstructMe(), PHG4ProjCrystalCalorimeterDetector::ConstructMe(), PHG4ForwardDualReadoutDetector::ConstructMe(), PHG4CrystalCalorimeterDetector::ConstructMe(), PHG4LFHcalDetector::ConstructMe(), PHG4InnerHcalDetector::ConstructMe(), PHG4GDMLDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructMe(), PHG4ForwardEcalDetector::ConstructMe(), PHG4OuterHcalDetector::ConstructOuterHcal(), PHG4ProjCrystalCalorimeterDetector::ConstructProjectiveCrystals(), PHG4HybridHomogeneousCalorimeterDetector::ConstructSupportFrame(), PHG4ForwardEcalDetector::ConstructTower(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), G4TwistedTubs::CreateSurfaces(), G4NeutronBetaDecayChannel::DecayIt(), export_G4RotationMatrix(), export_G4ThreeVector(), PHG4ProjCrystalCalorimeterDetector::Fill4x4Unit(), PHG4ProjCrystalCalorimeterDetector::FillSpecialUnit(), CylinderGeomIntt::find_strip_center(), G4VisCommandSceneAddLogo::G4Logo::G4Logo(), G4TwistBoxSide::G4TwistBoxSide(), G4TwistTrapAlphaSide::G4TwistTrapAlphaSide(), G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTrapParallelSide::G4TwistTrapParallelSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsSide::G4TwistTubsSide(), G4GDMLReadDefine::GetRotationMatrix(), G4GDMLReadParamvol::ParametersRead(), PHG4BarrelEcalDetector::PlaceTower(), DetectorConstruction::PlaceWithReflections(), CexmcSetup::RotateMatrix(), G4VScoringMesh::RotateZ(), G4LogicalCrystalVolume::SetMillerOrientation(), and G4PhysicalVolumeModel::VisitGeometryAndGetVisReps().
HepLorentzVector CLHEP::HepRotation::row1 () const inline
HepLorentzVector CLHEP::HepRotation::row2 () const inline
HepLorentzVector CLHEP::HepRotation::row3 () const inline
HepLorentzVector CLHEP::HepRotation::row4 () const inline
Hep3Vector CLHEP::HepRotation::rowX () const inline
Referenced by export_G4RotationMatrix().
Hep3Vector CLHEP::HepRotation::rowY () const inline
Referenced by export_G4RotationMatrix().
Hep3Vector CLHEP::HepRotation::rowZ () const inline
Referenced by export_G4RotationMatrix().
HepRotation & CLHEP::HepRotation::set (const Hep3Vector & axis, double delta)
Definition at line 27 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 27 of file RotationA.cc
References CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, rzz, Acts::UnitConstants::u, and CLHEP::Hep3Vector::unit().
Referenced by G4MuonDecayChannel::DecayIt(), CLHEP::HepLorentzRotation::decompose(), export_G4ThreeVector(), and export_G4TwoVector().
HepRotation & CLHEP::HepRotation::set (const HepAxisAngle & ax)
Definition at line 58 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 58 of file RotationA.cc
References CLHEP::HepAxisAngle::axis(), and CLHEP::HepAxisAngle::delta().
HepRotation & CLHEP::HepRotation::set (double phi, double theta, double psi)
Definition at line 35 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 35 of file RotationE.cc
References rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, and rzz.
HepRotation & CLHEP::HepRotation::set (const HepEulerAngles & e)
Definition at line 61 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 61 of file RotationE.cc
References CLHEP::HepEulerAngles::phi(), CLHEP::HepEulerAngles::psi(), and CLHEP::HepEulerAngles::theta().
HepRotation & CLHEP::HepRotation::set (const Hep3Vector & colX, const Hep3Vector & colY, const Hep3Vector & colZ)
Definition at line 73 of file RotationC.cc.
View newest version in sPHENIX GitHub at line 73 of file RotationC.cc
References CLHEP::Hep3Vector::dot(), rxx, rxy, rxz, ryx, ryy, ryz, rzx, rzy, rzz, setCols(), CLHEP::Hep4RotationInterface::tolerance, CLHEP::Hep3Vector::unit(), v1, v2, v3, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
HepRotation& CLHEP::HepRotation::set (const HepRotationX & r) inline
HepRotation& CLHEP::HepRotation::set (const HepRotationY & r) inline
HepRotation& CLHEP::HepRotation::set (const HepRotationZ & r) inline
HepRotation& CLHEP::HepRotation::set (const HepRep3x3 & m) inline
void CLHEP::HepRotation::setArbitrarily (const Hep3Vector & colX, Hep3Vector & v1, Hep3Vector & v2, Hep3Vector & v3) const private
Definition at line 48 of file RotationC.cc.
View newest version in sPHENIX GitHub at line 48 of file RotationC.cc
References CLHEP::Hep3Vector::cross(), CLHEP::Hep3Vector::mag2(), and CLHEP::Hep3Vector::unit().
void CLHEP::HepRotation::setAxis (const Hep3Vector & axis)
Definition at line 131 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 131 of file RotationA.cc
References delta().
Referenced by export_G4RotationMatrix().
bool CLHEP::HepRotation::setCols (const Hep3Vector & u1, const Hep3Vector & u2, const Hep3Vector & u3, double u1u2, Hep3Vector & v1, Hep3Vector & v2, Hep3Vector & v3) const private
Definition at line 25 of file RotationC.cc.
View newest version in sPHENIX GitHub at line 25 of file RotationC.cc
References CLHEP::Hep3Vector::cross(), CLHEP::Hep3Vector::dot(), CLHEP::Hep4RotationInterface::tolerance, and CLHEP::Hep3Vector::unit().
Referenced by set().
void CLHEP::HepRotation::setDelta (double delta)
Definition at line 135 of file RotationA.cc.
View newest version in sPHENIX GitHub at line 135 of file RotationA.cc
References axis().
Referenced by PHG4CylinderStripDetector::ConstructMe(), and export_G4RotationMatrix().
void CLHEP::HepRotation::setPhi (double phi)
Definition at line 262 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 262 of file RotationE.cc
References psi(), and theta().
Referenced by export_G4RotationMatrix(), export_G4ThreeVector(), export_G4TwoVector(), and G4GMocrenTouchable::GetRotation().
void CLHEP::HepRotation::setPsi (double psi)
Definition at line 270 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 270 of file RotationE.cc
References phi(), and theta().
Referenced by export_G4RotationMatrix().
HepRotation & CLHEP::HepRotation::setRows (const Hep3Vector & rowX, const Hep3Vector & rowY, const Hep3Vector & rowZ)
Definition at line 142 of file RotationC.cc.
View newest version in sPHENIX GitHub at line 142 of file RotationC.cc
References invert().
void CLHEP::HepRotation::setTheta (double theta)
Definition at line 266 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 266 of file RotationE.cc
References phi(), and psi().
Referenced by export_G4RotationMatrix(), and export_G4ThreeVector().
static double CLHEP::HepRotation::setTolerance (double tol) inline static
Referenced by export_G4ThreeVector().
double CLHEP::HepRotation::theta () const
Definition at line 104 of file RotationE.cc.
View newest version in sPHENIX GitHub at line 104 of file RotationE.cc
References rzz, and CLHEP::safe_acos().
Referenced by export_G4RotationMatrix(), setPhi(), and setPsi().
double CLHEP::HepRotation::thetaX () const
Definition at line 140 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 140 of file Rotation.cc
References CLHEP::safe_acos(), and zx().
Referenced by G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), and operator<<().
double CLHEP::HepRotation::thetaY () const
Definition at line 144 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 144 of file Rotation.cc
References CLHEP::safe_acos(), and zy().
Referenced by G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), and operator<<().
double CLHEP::HepRotation::thetaZ () const
Definition at line 148 of file Rotation.cc.
View newest version in sPHENIX GitHub at line 148 of file Rotation.cc
References CLHEP::safe_acos(), and zz().
Referenced by G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), and operator<<().
HepRotation& CLHEP::HepRotation::transform (const HepRotation & r) inline
Referenced by export_G4ThreeVector(), rotate(), and rotateAxes().
HepRotation& CLHEP::HepRotation::transform (const HepRotationX & r) inline
HepRotation& CLHEP::HepRotation::transform (const HepRotationY & r) inline
HepRotation& CLHEP::HepRotation::transform (const HepRotationZ & r) inline
double CLHEP::HepRotation::tt () const inline
Referenced by CLHEP::operator*().
double CLHEP::HepRotation::tx () const inline
Referenced by CLHEP::operator*().
double CLHEP::HepRotation::ty () const inline
Referenced by CLHEP::operator*().
double CLHEP::HepRotation::tz () const inline
Referenced by CLHEP::operator*().
double CLHEP::HepRotation::xt () const inline
Referenced by CLHEP::operator*().
double CLHEP::HepRotation::xx () const inline
Referenced by NeuronLoadDataFile::ComputeTransformation(), CLHEP::HepRotationY::distance2(), CLHEP::HepRotationZ::distance2(), CLHEP::HepRotationX::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4GDMLWriteDefine::GetAngles(), PHG4GDMLWriteDefine::GetAngles(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), phiX(), and print().
double CLHEP::HepRotation::xy () const inline
Referenced by CLHEP::HepRotationZ::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), phiY(), and print().
double CLHEP::HepRotation::xz () const inline
Referenced by CLHEP::HepRotationY::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), phiZ(), and print().
double CLHEP::HepRotation::yt () const inline
Referenced by CLHEP::operator*().
double CLHEP::HepRotation::yx () const inline
Referenced by NeuronLoadDataFile::ComputeTransformation(), CLHEP::HepRotationZ::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4GDMLWriteDefine::GetAngles(), PHG4GDMLWriteDefine::GetAngles(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), phiX(), and print().
double CLHEP::HepRotation::yy () const inline
Referenced by NeuronLoadDataFile::ComputeTransformation(), CLHEP::HepRotationY::distance2(), CLHEP::HepRotationZ::distance2(), CLHEP::HepRotationX::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4GDMLWriteDefine::GetAngles(), PHG4GDMLWriteDefine::GetAngles(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), phiY(), and print().
double CLHEP::HepRotation::yz () const inline
Referenced by NeuronLoadDataFile::ComputeTransformation(), CLHEP::HepRotationX::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4GDMLWriteDefine::GetAngles(), PHG4GDMLWriteDefine::GetAngles(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), phiZ(), and print().
double CLHEP::HepRotation::zt () const inline
Referenced by CLHEP::operator*().
double CLHEP::HepRotation::zx () const inline
Referenced by NeuronLoadDataFile::ComputeTransformation(), CLHEP::HepRotationY::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4GDMLWriteDefine::GetAngles(), PHG4GDMLWriteDefine::GetAngles(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), print(), and thetaX().
double CLHEP::HepRotation::zy () const inline
Referenced by NeuronLoadDataFile::ComputeTransformation(), CLHEP::HepRotationX::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4GDMLWriteDefine::GetAngles(), PHG4GDMLWriteDefine::GetAngles(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), print(), and thetaY().
double CLHEP::HepRotation::zz () const inline
Referenced by NeuronLoadDataFile::ComputeTransformation(), CLHEP::HepRotationY::distance2(), CLHEP::HepRotationZ::distance2(), CLHEP::HepRotationX::distance2(), G4tgrUtils::Dumprm(), G4tgbGeometryDumper::DumpRotationMatrix(), export_G4RotationMatrix(), export_G4Transform3D(), getAngleAxis(), G4GDMLWriteDefine::GetAngles(), PHG4GDMLWriteDefine::GetAngles(), G4VScoringMesh::List(), operator()(), CLHEP::operator*(), print(), and thetaZ().
Friends And Related Function Documentation
HepRotation operator* (const HepRotationX & rx, const HepRotation & r) friend
HepRotation operator* (const HepRotationY & ry, const HepRotation & r) friend
HepRotation operator* (const HepRotationZ & rz, const HepRotation & r) friend
Member Data Documentation
const HepRotation CLHEP::HepRotation::IDENTITY static
Definition at line 370 of file Rotation.h.
View newest version in sPHENIX GitHub at line 370 of file Rotation.h
Referenced by export_G4RotationMatrix(), G4VScoringMesh::GetRotationMatrix(), G4AssemblyVolume::MakeImprint(), G4LogicalCrystalVolume::SetMillerOrientation(), and G4LatticePhysical::SetPhysicalOrientation().
double CLHEP::HepRotation::rxx protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), delta(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), norm2(), rectify(), rotateY(), rotateZ(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), and G3toG4RotationMatrix::SetRotationMatrixByRow().
double CLHEP::HepRotation::rxy protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), rectify(), rotateY(), rotateZ(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), and G3toG4RotationMatrix::SetRotationMatrixByRow().
double CLHEP::HepRotation::rxz protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), psi(), rectify(), rotateY(), rotateZ(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), and G3toG4RotationMatrix::SetRotationMatrixByRow().
double CLHEP::HepRotation::ryx protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), rectify(), rotateX(), rotateZ(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), and G3toG4RotationMatrix::SetRotationMatrixByRow().
double CLHEP::HepRotation::ryy protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), delta(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), norm2(), rectify(), rotateX(), rotateZ(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), and G3toG4RotationMatrix::SetRotationMatrixByRow().
double CLHEP::HepRotation::ryz protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), psi(), rectify(), rotateX(), rotateZ(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), and G3toG4RotationMatrix::SetRotationMatrixByRow().
double CLHEP::HepRotation::rzx protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), phi(), rectify(), rotateX(), rotateY(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), and G3toG4RotationMatrix::SetRotationMatrixByRow().
double CLHEP::HepRotation::rzy protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), phi(), rectify(), rotateX(), rotateY(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), and G3toG4RotationMatrix::SetRotationMatrixByRow().
double CLHEP::HepRotation::rzz protected
Definition at line 389 of file Rotation.h.
View newest version in sPHENIX GitHub at line 389 of file Rotation.h
Referenced by axis(), compare(), delta(), distance2(), eulerAngles(), G3toG4RotationMatrix::G3toG4RotationMatrix(), isIdentity(), norm2(), phi(), psi(), rectify(), rotateX(), rotateY(), set(), G3toG4RotationMatrix::SetRotationMatrixByCol(), G3toG4RotationMatrix::SetRotationMatrixByRow(), and theta().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/Rotation.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/Rotation.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationA.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationC.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationE.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationIO.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationL.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationP.cc