ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4IT.hh File Reference
G4IT.hh File Reference
#include "globals.hh"
#include "G4ITType.hh"
#include "G4ThreeVector.hh"
#include "G4VUserTrackInformation.hh"
#include "G4KDNode.hh"
Classes
class G4FastListNode< OBJECT >
class G4IT
Typedefs
typedef G4FastListNode< G4Track > G4TrackListNode
Functions
G4IT * GetIT (const G4Track *track)
G4IT * GetIT (const G4Track &track)
Typedef Documentation
typedef G4FastListNode<G4Track> G4TrackListNode
Definition at line 75 of file G4IT.hh.
View newest version in sPHENIX GitHub at line 75 of file G4IT.hh
Function Documentation
G4IT* GetIT (const G4Track * track)
Definition at line 48 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 48 of file G4IT.cc
References G4Track::GetUserInformation().
Referenced by G4FastList< G4Track >::__GetNode(), G4ITTrackHolder::_PushTrack(), G4DNABrownianTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), ITTrackingInteractivity::AppendStep(), G4ITModelProcessor::CalculateMinTimeStep(), G4FastList< G4Track >::CheckFlag(), G4DNABrownianTransportation::ComputeGeomLimit(), G4ITStepProcessor::ComputeInteractionLength(), G4DNABrownianTransportation::ComputeStep(), G4ITModelProcessor::ComputeTrackReaction(), G4FastListNode< G4Track >::DetachYourSelf(), G4DNABrownianTransportation::Diffusion(), G4ITStepProcessor::DoStepping(), ITTrackingInteractivity::EndTracking(), G4FastList< G4Track >::Flag(), G4FastList< G4Track >::GetList(), GetMolecule(), G4Molecule::GetMolecule(), G4FastList< G4Track >::GetNode(), G4FastList< G4Track >::Holds(), G4ITTrackHolder::KillTracks(), G4ITSteppingVerbose::PostStepVerbose(), G4ITLeadingTracks::PrepareLeadingTracks(), G4ITSteppingVerbose::PreStepVerbose(), G4AllITFinder::Push(), G4ITTrackHolder::PushDelayed(), G4ITTrackHolder::PushTo(), G4ITLeadingTracks::Reset(), G4ITStepProcessor::SetTrack(), ITTrackingInteractivity::StartTracking(), G4ITTransportation::StartTracking(), G4VITProcess::StartTracking(), and G4ITSteppingVerbose::TrackingStarted().
G4IT* GetIT (const G4Track & track)
Definition at line 53 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 53 of file G4IT.cc
References G4Track::GetUserInformation().