ECCE @ EIC Software: G4PartonPair Class Reference
G4PartonPair Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4PartonPair.hh>
Public Types
enum { DIFFRACTIVE = 1, SOFT = 2, HARD = 3 }
enum { PROJECTILE = 1, TARGET = -1 }
Public Member Functions
G4PartonPair (G4Parton *P1, G4Parton *P2, G4int Type, G4int Direction)
~G4PartonPair ()
void SetPartons (G4Parton *P1, G4Parton *P2)
void SetCollisionType (G4int Type)
G4int GetCollisionType ()
G4Parton * GetParton1 (void)
G4Parton * GetParton2 (void)
G4int GetDirection ()
Private Member Functions
G4PartonPair (const G4PartonPair &right)
G4bool operator== (const G4PartonPair &right) const
G4bool operator!= (const G4PartonPair &right) const
Private Attributes
G4Parton * Parton1
G4Parton * Parton2
G4int CollisionType
G4int Direction
Detailed Description
Definition at line 35 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 35 of file G4PartonPair.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
DIFFRACTIVE
SOFT
HARD
Definition at line 38 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 38 of file G4PartonPair.hh
anonymous enum
Enumerator:
PROJECTILE
TARGET
Definition at line 43 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 43 of file G4PartonPair.hh
Constructor & Destructor Documentation
G4PartonPair::G4PartonPair (G4Parton * P1, G4Parton * P2, G4int Type, G4int Direction)
Definition at line 31 of file G4PartonPair.cc.
View newest version in sPHENIX GitHub at line 31 of file G4PartonPair.cc
References CollisionType, Direction, G4cout, G4endl, G4Parton::Get4Momentum(), G4Parton::GetColour(), G4Parton::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4Parton::GetSpinZ(), m, P1, P2, Parton1, Parton2, PROJECTILE, and SOFT.
G4PartonPair::~G4PartonPair ()
Definition at line 60 of file G4PartonPair.cc.
View newest version in sPHENIX GitHub at line 60 of file G4PartonPair.cc
G4PartonPair::G4PartonPair (const G4PartonPair & right) private
Member Function Documentation
G4int G4PartonPair::GetCollisionType () inline
Definition at line 86 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PartonPair.hh
References CollisionType.
G4int G4PartonPair::GetDirection () inline
Definition at line 91 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PartonPair.hh
References Direction.
Referenced by G4DiffractiveStringBuilder::BuildString(), and G4SoftStringBuilder::BuildString().
G4Parton * G4PartonPair::GetParton1 (void) inline
Definition at line 71 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 71 of file G4PartonPair.hh
References Parton1.
Referenced by G4DiffractiveStringBuilder::BuildString(), G4SoftStringBuilder::BuildString(), G4QGSParticipants::CreateStrings(), and G4QGSParticipants::PerformSoftCollisions().
G4Parton * G4PartonPair::GetParton2 (void) inline
Definition at line 76 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PartonPair.hh
References Parton2.
Referenced by G4DiffractiveStringBuilder::BuildString(), G4SoftStringBuilder::BuildString(), G4QGSParticipants::CreateStrings(), and G4QGSParticipants::PerformSoftCollisions().
G4bool G4PartonPair::operator!= (const G4PartonPair & right) const private
G4bool G4PartonPair::operator== (const G4PartonPair & right) const private
void G4PartonPair::SetCollisionType (G4int Type) inline
Definition at line 81 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 81 of file G4PartonPair.hh
References CollisionType.
void G4PartonPair::SetPartons (G4Parton * P1, G4Parton * P2)
Member Data Documentation
G4int G4PartonPair::CollisionType private
Definition at line 67 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PartonPair.hh
Referenced by G4PartonPair(), GetCollisionType(), and SetCollisionType().
G4int G4PartonPair::Direction private
Definition at line 68 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PartonPair.hh
Referenced by G4PartonPair(), and GetDirection().
G4Parton* G4PartonPair::Parton1 private
Definition at line 65 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 65 of file G4PartonPair.hh
Referenced by G4PartonPair(), and GetParton1().
G4Parton* G4PartonPair::Parton2 private
Definition at line 66 of file G4PartonPair.hh.
View newest version in sPHENIX GitHub at line 66 of file G4PartonPair.hh
Referenced by G4PartonPair(), and GetParton2().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4PartonPair.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4PartonPair.cc