ECCE @ EIC Software: G4LogicalVolumeModel Class Reference
G4LogicalVolumeModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4LogicalVolumeModel.hh>
Public Member Functions
G4LogicalVolumeModel (G4LogicalVolume *, G4int soughtDepth=1, G4bool booleans=true, G4bool voxels=true, G4bool readout=true, G4bool checkOverlaps=true, const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4LogicalVolumeModel ()
void DescribeYourselfTo (G4VGraphicsScene &)
G4bool Validate (G4bool)
Public Member Functions inherited from G4PhysicalVolumeModel
G4PhysicalVolumeModel (G4VPhysicalVolume *=0, G4int requestedDepth=UNLIMITED, const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0, G4bool useFullExtent=false, const std::vector< G4PhysicalVolumeNodeID > &baseFullPVPath=std::vector< G4PhysicalVolumeNodeID >())
virtual ~G4PhysicalVolumeModel ()
void DescribeYourselfTo (G4VGraphicsScene &)
G4String GetCurrentDescription () const
G4String GetCurrentTag () const
G4VPhysicalVolume * GetTopPhysicalVolume () const
G4int GetRequestedDepth () const
const G4VSolid * GetClippingSolid () const
G4int GetCurrentDepth () const
G4VPhysicalVolume * GetCurrentPV () const
G4int GetCurrentPVCopyNo () const
G4LogicalVolume * GetCurrentLV () const
G4Material * GetCurrentMaterial () const
G4Transform3D * GetCurrentTransform () const
const std::vector
< G4PhysicalVolumeNodeID > & GetBaseFullPVPath () const
const std::vector
< G4PhysicalVolumeNodeID > & GetFullPVPath () const
const std::vector
< G4PhysicalVolumeNodeID > & GetDrawnPVPath () const
const std::map< G4String,
G4AttDef > * GetAttDefs () const
std::vector< G4AttValue > * CreateCurrentAttValues () const
void SetRequestedDepth (G4int requestedDepth)
void SetClippingSolid (G4VSolid *pClippingSolid)
void SetClippingMode (ClippingMode mode)
G4bool Validate (G4bool warn)
void Abort () const
void CurtailDescent () const
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
Protected Member Functions
void DescribeSolid (const G4Transform3D &theAT, G4VSolid *pSol, const G4VisAttributes *pVisAttribs, G4VGraphicsScene &sceneHandler)
Protected Member Functions inherited from G4PhysicalVolumeModel
void VisitGeometryAndGetVisReps (G4VPhysicalVolume *, G4int requestedDepth, const G4Transform3D &, G4VGraphicsScene &)
void DescribeAndDescend (G4VPhysicalVolume *, G4int requestedDepth, G4LogicalVolume *, G4VSolid *, G4Material *, const G4Transform3D &, G4VGraphicsScene &)
void CalculateExtent ()
Protected Attributes
G4LogicalVolume * fpLV
G4bool fBooleans
G4bool fVoxels
G4bool fReadout
G4bool fCheckOverlaps
G4bool fOverlapsPrinted
Protected Attributes inherited from G4PhysicalVolumeModel
G4VPhysicalVolume * fpTopPV
G4String fTopPVName
G4int fTopPVCopyNo
G4int fRequestedDepth
G4bool fUseFullExtent
G4int fCurrentDepth
G4VPhysicalVolume * fpCurrentPV
G4int fCurrentPVCopyNo
G4LogicalVolume * fpCurrentLV
G4Material * fpCurrentMaterial
G4Transform3D * fpCurrentTransform
std::vector
< G4PhysicalVolumeNodeID > fBaseFullPVPath
std::vector
< G4PhysicalVolumeNodeID > fFullPVPath
std::vector
< G4PhysicalVolumeNodeID > fDrawnPVPath
G4bool fAbort
G4bool fCurtailDescent
G4VSolid * fpClippingSolid
ClippingMode fClippingMode
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Additional Inherited Members
Public Types inherited from G4PhysicalVolumeModel
enum { UNLIMITED = -1 }
enum ClippingMode { subtraction, intersection }
Static Public Member Functions inherited from G4PhysicalVolumeModel
static
G4ModelingParameters::PVNameCopyNoPath GetPVNameCopyNoPath (const std::vector< G4PhysicalVolumeNodeID > &)
Detailed Description
Definition at line 50 of file G4LogicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 50 of file G4LogicalVolumeModel.hh
Constructor & Destructor Documentation
G4LogicalVolumeModel::G4LogicalVolumeModel (G4LogicalVolume * pLV, G4int soughtDepth = 1, G4bool booleans = true, G4bool voxels = true, G4bool readout = true, G4bool checkOverlaps = true, const G4Transform3D & modelTransformation = G4Transform3D(), const G4ModelingParameters * pMP = 0)
Definition at line 50 of file G4LogicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 50 of file G4LogicalVolumeModel.cc
G4LogicalVolumeModel::~G4LogicalVolumeModel () virtual
Definition at line 88 of file G4LogicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 88 of file G4LogicalVolumeModel.cc
Member Function Documentation
void G4LogicalVolumeModel::DescribeSolid (const G4Transform3D & theAT, G4VSolid * pSol, const G4VisAttributes * pVisAttribs, G4VGraphicsScene & sceneHandler) protected virtual
Reimplemented from G4PhysicalVolumeModel.
Definition at line 293 of file G4LogicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 293 of file G4LogicalVolumeModel.cc
References FatalException, G4Exception(), G4VGraphicsScene::PostAddSolid(), G4VGraphicsScene::PreAddSolid(), and G4VisAttributes::SetForceWireframe().
void G4LogicalVolumeModel::DescribeYourselfTo (G4VGraphicsScene & sceneHandler) virtual
Implements G4VModel.
Definition at line 133 of file G4LogicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 133 of file G4LogicalVolumeModel.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives(), G4VPhysicalVolume::CheckOverlaps(), G4VSolid::ComputeDimensions(), G4DrawVoxels::CreatePlacedPolyhedra(), G4PhysicalVolumeModel::DescribeYourselfTo(), G4VGraphicsScene::EndPrimitives(), G4cout, G4endl, G4VPhysicalVolume::GetCopyNo(), G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4PVReplica::GetMultiplicity(), G4VReadOutGeometry::GetName(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), G4PVParameterised::GetParameterisation(), G4VSolid::GetPointOnSurface(), G4VSensitiveDetector::GetROgeometry(), G4VPhysicalVolume::GetRotation(), G4VReadOutGeometry::GetROWorld(), G4LogicalVolume::GetSolid(), G4VPhysicalVolume::GetTranslation(), G4VSolid::Inside(), kInside, kOutside, G4ModelingParameters::SetCulling(), G4VModel::SetModelingParameters(), and Acts::Test::transform.
G4bool G4LogicalVolumeModel::Validate (G4bool) inline virtual
Reimplemented from G4VModel.
Definition at line 68 of file G4LogicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4LogicalVolumeModel.hh
Member Data Documentation
G4bool G4LogicalVolumeModel::fBooleans protected
Definition at line 84 of file G4LogicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 84 of file G4LogicalVolumeModel.hh
G4bool G4LogicalVolumeModel::fCheckOverlaps protected
Definition at line 87 of file G4LogicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 87 of file G4LogicalVolumeModel.hh
G4bool G4LogicalVolumeModel::fOverlapsPrinted protected
Definition at line 88 of file G4LogicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4LogicalVolumeModel.hh
G4LogicalVolume* G4LogicalVolumeModel::fpLV protected
Definition at line 83 of file G4LogicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4LogicalVolumeModel.hh
G4bool G4LogicalVolumeModel::fReadout protected
Definition at line 86 of file G4LogicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4LogicalVolumeModel.hh
G4bool G4LogicalVolumeModel::fVoxels protected
Definition at line 85 of file G4LogicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4LogicalVolumeModel.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4LogicalVolumeModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4LogicalVolumeModel.cc