ECCE @ EIC Software: G4Fissioner Class Reference
G4Fissioner Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4Fissioner.hh>
Public Member Functions
G4Fissioner ()
virtual ~G4Fissioner ()
virtual void deExcite (const G4Fragment &target, G4CollisionOutput &output)
Public Member Functions inherited from G4CascadeDeexciteBase
G4CascadeDeexciteBase (const char *name)
virtual ~G4CascadeDeexciteBase ()
virtual void setVerboseLevel (G4int verbose=0)
Public Member Functions inherited from G4VCascadeDeexcitation
G4VCascadeDeexcitation (const G4String &name)
virtual ~G4VCascadeDeexcitation ()
virtual void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Private Member Functions
G4double getC2 (G4int A1, G4int A2, G4double X3, G4double X4, G4double R12) const
G4double getZopt (G4int A1, G4int A2, G4int ZT, G4double X3, G4double X4, G4double R12) const
void potentialMinimization (G4double &VP, G4double(&ED)[2], G4double &VC, G4int AF, G4int AS, G4int ZF, G4int ZS, G4double AL1[2], G4double BET1[2], G4double &R12) const
G4Fissioner (const G4Fissioner &)
G4Fissioner & operator= (const G4Fissioner &)
Private Attributes
G4FissionStore fissionStore
Additional Inherited Members
Protected Member Functions inherited from G4CascadeDeexciteBase
virtual G4bool explosion (const G4Fragment &target) const
virtual G4bool explosion (G4int A, G4int Z, G4double excitation) const
virtual G4bool validateOutput (const G4Fragment &target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclElementaryParticle > &particles)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclNuclei > &fragments)
void getTargetData (const G4Fragment &target)
const G4Fragment & makeFragment (G4LorentzVector mom, G4int A, G4int Z, G4double EX=0.)
const G4Fragment & makeFragment (G4int A, G4int Z, G4double EX=0.)
Protected Attributes inherited from G4CascadeDeexciteBase
G4CascadeCheckBalance * balance
G4int A
G4int Z
G4LorentzVector PEX
G4double EEXS
G4Fragment aFragment
Detailed Description
Definition at line 49 of file G4Fissioner.hh.
View newest version in sPHENIX GitHub at line 49 of file G4Fissioner.hh
Constructor & Destructor Documentation
G4Fissioner::G4Fissioner () inline
Definition at line 51 of file G4Fissioner.hh.
View newest version in sPHENIX GitHub at line 51 of file G4Fissioner.hh
virtual G4Fissioner::~G4Fissioner () inline virtual
Definition at line 52 of file G4Fissioner.hh.
View newest version in sPHENIX GitHub at line 52 of file G4Fissioner.hh
G4Fissioner::G4Fissioner (const G4Fissioner &) private
Member Function Documentation
void G4Fissioner::deExcite (const G4Fragment & target, G4CollisionOutput & output) virtual
Implements G4VCascadeDeexcitation.
Definition at line 65 of file G4Fissioner.cc.
View newest version in sPHENIX GitHub at line 65 of file G4Fissioner.cc
References A(), A13, G4CollisionOutput::addRecoilFragment(), G4FissionConfiguration::afirst, G4InuclSpecialFunctions::bindingEnergy(), G4InuclSpecialFunctions::bindingEnergyAsymptotic(), C1, CLHEP::HepLorentzVector::e(), G4FissionConfiguration::ekin, G4InuclSpecialFunctions::G4cbrt(), G4cout, G4endl, G4lrint(), G4InuclSpecialFunctions::generateWithRandomAngles(), G4InuclNuclei::getNucleiMass(), G4InuclSpecialFunctions::inuclRndm(), G4InuclSpecialFunctions::nucleiLevelDensity(), G4InuclSpecialFunctions::randomGauss(), CLHEP::HepLorentzVector::setVectM(), CLHEP::HepLorentzVector::vect(), Z, Z1, Z2, and G4FissionConfiguration::zfirst.
Referenced by G4EquilibriumEvaporator::deExcite().
G4double G4Fissioner::getC2 (G4int A1, G4int A2, G4double X3, G4double X4, G4double R12) const private
Definition at line 179 of file G4Fissioner.cc.
View newest version in sPHENIX GitHub at line 179 of file G4Fissioner.cc
References C2, G4cout, and G4endl.
G4double G4Fissioner::getZopt (G4int A1, G4int A2, G4int ZT, G4double X3, G4double X4, G4double R12) const private
Definition at line 195 of file G4Fissioner.cc.
View newest version in sPHENIX GitHub at line 195 of file G4Fissioner.cc
References G4cout, and G4endl.
G4Fissioner& G4Fissioner::operator= (const G4Fissioner &) private
void G4Fissioner::potentialMinimization (G4double & VP, G4double(&) ED[2], G4double & VC, G4int AF, G4int AS, G4int ZF, G4int ZS, G4double AL1[2], G4double BET1[2], G4double & R12) const private
Definition at line 213 of file G4Fissioner.cc.
View newest version in sPHENIX GitHub at line 213 of file G4Fissioner.cc
References B(), C(), D(), F, G4InuclSpecialFunctions::G4cbrt(), G4cout, G4endl, G4Exp(), Acts::IntegrationTest::R, S(), X, X1, X2, Y1, Y2, and Z1.
Member Data Documentation
G4FissionStore G4Fissioner::fissionStore private
Definition at line 57 of file G4Fissioner.hh.
View newest version in sPHENIX GitHub at line 57 of file G4Fissioner.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4Fissioner.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4Fissioner.cc