ECCE @ EIC Software: G4ChipsElasticModel Class Reference
G4ChipsElasticModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4ChipsElasticModel.hh>
Public Member Functions
G4ChipsElasticModel ()
virtual ~G4ChipsElasticModel ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual void ModelDescription (std::ostream &) const
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) override
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A) override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4ChipsProtonElasticXS * pxsManager
G4ChipsNeutronElasticXS * nxsManager
G4ChipsAntiBaryonElasticXS * PBARxsManager
G4ChipsPionPlusElasticXS * PIPxsManager
G4ChipsPionMinusElasticXS * PIMxsManager
G4ChipsKaonPlusElasticXS * KPxsManager
G4ChipsKaonMinusElasticXS * KMxsManager
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 52 of file G4ChipsElasticModel.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ChipsElasticModel.hh
Constructor & Destructor Documentation
G4ChipsElasticModel::G4ChipsElasticModel ()
Definition at line 46 of file G4ChipsElasticModel.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ChipsElasticModel.cc
References G4ChipsProtonElasticXS::Default_Name(), G4ChipsPionPlusElasticXS::Default_Name(), G4ChipsKaonPlusElasticXS::Default_Name(), G4ChipsKaonMinusElasticXS::Default_Name(), G4ChipsAntiBaryonElasticXS::Default_Name(), G4ChipsPionMinusElasticXS::Default_Name(), G4ChipsNeutronElasticXS::Default_Name(), G4CrossSectionDataSetRegistry::GetCrossSectionDataSet(), G4CrossSectionDataSetRegistry::Instance(), KMxsManager, KPxsManager, nxsManager, PBARxsManager, PIMxsManager, PIPxsManager, and pxsManager.
G4ChipsElasticModel::~G4ChipsElasticModel () virtual
Definition at line 58 of file G4ChipsElasticModel.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ChipsElasticModel.cc
Member Function Documentation
void G4ChipsElasticModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 61 of file G4ChipsElasticModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ChipsElasticModel.cc
G4double G4ChipsElasticModel::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 72 of file G4ChipsElasticModel.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ChipsElasticModel.cc
References G4ChipsProtonElasticXS::GetChipsCrossSection(), G4ChipsPionPlusElasticXS::GetChipsCrossSection(), G4ChipsKaonPlusElasticXS::GetChipsCrossSection(), G4ChipsKaonMinusElasticXS::GetChipsCrossSection(), G4ChipsAntiBaryonElasticXS::GetChipsCrossSection(), G4ChipsPionMinusElasticXS::GetChipsCrossSection(), G4ChipsNeutronElasticXS::GetChipsCrossSection(), G4ChipsProtonElasticXS::GetExchangeT(), G4ChipsPionPlusElasticXS::GetExchangeT(), G4ChipsKaonPlusElasticXS::GetExchangeT(), G4ChipsNeutronElasticXS::GetExchangeT(), G4ChipsPionMinusElasticXS::GetExchangeT(), G4ChipsAntiBaryonElasticXS::GetExchangeT(), G4ChipsKaonMinusElasticXS::GetExchangeT(), G4ParticleDefinition::GetPDGEncoding(), KMxsManager, KPxsManager, N, nxsManager, PBARxsManager, PIMxsManager, PIPxsManager, pxsManager, G4HadronElastic::SampleInvariantT(), t, and Z.
Member Data Documentation
G4ChipsKaonMinusElasticXS* G4ChipsElasticModel::KMxsManager private
Definition at line 74 of file G4ChipsElasticModel.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ChipsElasticModel.hh
Referenced by G4ChipsElasticModel(), and SampleInvariantT().
G4ChipsKaonPlusElasticXS* G4ChipsElasticModel::KPxsManager private
Definition at line 73 of file G4ChipsElasticModel.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ChipsElasticModel.hh
Referenced by G4ChipsElasticModel(), and SampleInvariantT().
G4ChipsNeutronElasticXS* G4ChipsElasticModel::nxsManager private
Definition at line 68 of file G4ChipsElasticModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ChipsElasticModel.hh
Referenced by G4ChipsElasticModel(), and SampleInvariantT().
G4ChipsAntiBaryonElasticXS* G4ChipsElasticModel::PBARxsManager private
Definition at line 70 of file G4ChipsElasticModel.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ChipsElasticModel.hh
Referenced by G4ChipsElasticModel(), and SampleInvariantT().
G4ChipsPionMinusElasticXS* G4ChipsElasticModel::PIMxsManager private
Definition at line 72 of file G4ChipsElasticModel.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ChipsElasticModel.hh
Referenced by G4ChipsElasticModel(), and SampleInvariantT().
G4ChipsPionPlusElasticXS* G4ChipsElasticModel::PIPxsManager private
Definition at line 71 of file G4ChipsElasticModel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ChipsElasticModel.hh
Referenced by G4ChipsElasticModel(), and SampleInvariantT().
G4ChipsProtonElasticXS* G4ChipsElasticModel::pxsManager private
Definition at line 67 of file G4ChipsElasticModel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ChipsElasticModel.hh
Referenced by G4ChipsElasticModel(), and SampleInvariantT().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4ChipsElasticModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4ChipsElasticModel.cc