ECCE @ EIC Software: G3MatTableEntry Class Reference
G3MatTableEntry Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3MatTableEntry.hh>
Public Member Functions
G3MatTableEntry (G4int id, G4Material *material)
G3MatTableEntry (const G3MatTableEntry &right)
virtual ~G3MatTableEntry ()
G3MatTableEntry & operator= (const G3MatTableEntry &right)
G4bool operator== (const G3MatTableEntry &right) const
G4bool operator!= (const G3MatTableEntry &right) const
G4int GetID () const
G4Material * GetMaterial () const
Private Attributes
G4int fID
G4Material * fMaterial
Detailed Description
Definition at line 45 of file G3MatTableEntry.hh.
View newest version in sPHENIX GitHub at line 45 of file G3MatTableEntry.hh
Constructor & Destructor Documentation
G3MatTableEntry::G3MatTableEntry (G4int id, G4Material * material)
Definition at line 34 of file G3MatTableEntry.cc.
View newest version in sPHENIX GitHub at line 34 of file G3MatTableEntry.cc
G3MatTableEntry::G3MatTableEntry (const G3MatTableEntry & right)
Definition at line 39 of file G3MatTableEntry.cc.
View newest version in sPHENIX GitHub at line 39 of file G3MatTableEntry.cc
G3MatTableEntry::~G3MatTableEntry () virtual
Definition at line 44 of file G3MatTableEntry.cc.
View newest version in sPHENIX GitHub at line 44 of file G3MatTableEntry.cc
Member Function Documentation
G4int G3MatTableEntry::GetID () const inline
Definition at line 71 of file G3MatTableEntry.hh.
View newest version in sPHENIX GitHub at line 71 of file G3MatTableEntry.hh
References fID.
Referenced by G3MatTable::get(), operator=(), and operator==().
G4Material * G3MatTableEntry::GetMaterial () const inline
Definition at line 74 of file G3MatTableEntry.hh.
View newest version in sPHENIX GitHub at line 74 of file G3MatTableEntry.hh
References fMaterial.
Referenced by G3MatTable::get(), and operator=().
G4bool G3MatTableEntry::operator!= (const G3MatTableEntry & right) const
Definition at line 63 of file G3MatTableEntry.cc.
View newest version in sPHENIX GitHub at line 63 of file G3MatTableEntry.cc
G3MatTableEntry & G3MatTableEntry::operator= (const G3MatTableEntry & right)
Definition at line 47 of file G3MatTableEntry.cc.
View newest version in sPHENIX GitHub at line 47 of file G3MatTableEntry.cc
References fID, fMaterial, GetID(), and GetMaterial().
G4bool G3MatTableEntry::operator== (const G3MatTableEntry & right) const
Definition at line 55 of file G3MatTableEntry.cc.
View newest version in sPHENIX GitHub at line 55 of file G3MatTableEntry.cc
References fID, and GetID().
Member Data Documentation
G4int G3MatTableEntry::fID private
Definition at line 65 of file G3MatTableEntry.hh.
View newest version in sPHENIX GitHub at line 65 of file G3MatTableEntry.hh
Referenced by GetID(), operator=(), and operator==().
G4Material* G3MatTableEntry::fMaterial private
Definition at line 66 of file G3MatTableEntry.hh.
View newest version in sPHENIX GitHub at line 66 of file G3MatTableEntry.hh
Referenced by GetMaterial(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3MatTableEntry.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3MatTableEntry.cc