ECCE @ EIC Software: G4DNAMolecularReactionTable Class Reference
G4DNAMolecularReactionTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAMolecularReactionTable.hh>
Public Types
using Reactant = const G4MolecularConfiguration
using Data = const G4DNAMolecularReactionData
using ReactantList = std::vector< Reactant * >
using DataList = std::vector< Data * >
using SpecificDataList = std::map< Reactant *, Data * >
using ReactionDataMap = std::map< Reactant *, SpecificDataList >
using ReactivesMV = std::map< Reactant *, ReactantList >
using ReactionDataMV = std::map< Reactant *, DataList >
Public Member Functions
virtual ~G4DNAMolecularReactionTable ()
void SetReaction (G4double observedReactionRate, Reactant *reactive1, Reactant *reactive2)
void SetReaction (G4DNAMolecularReactionData *)
Data * GetReactionData (Reactant *, Reactant *) const
Data * GetReactionData (const G4String &, const G4String &) const
Data * GetReaction (int reactionID) const
size_t GetNReactions () const
const ReactantList * CanReactWith (Reactant *) const
const SpecificDataList * GetReativesNData (const G4MolecularConfiguration *) const
const DataList * GetReactionData (const G4MolecularConfiguration *) const
const ReactionDataMap & GetAllReactionData ()
DataList GetVectorOfReactionData ()
void ScaleReactionRateForNewTemperature (double temp_K)
void PrintTable (G4VDNAReactionModel *=0)
Public Member Functions inherited from G4ITReactionTable
G4ITReactionTable ()
virtual ~G4ITReactionTable ()
G4ITReactionTable (const G4ITReactionTable &)
G4ITReactionTable & operator= (const G4ITReactionTable &)
Static Public Member Functions
static
G4DNAMolecularReactionTable * GetReactionTable ()
static
G4DNAMolecularReactionTable * Instance ()
static void DeleteInstance ()
Protected Member Functions
G4DNAMolecularReactionTable ()
Protected Attributes
G4bool fVerbose
ReactionDataMap fReactionData
ReactivesMV fReactantsMV
ReactionDataMV fReactionDataMV
std::vector< std::unique_ptr
< Data > > fVectorOfReactionData
std::unique_ptr
< G4ReactionTableMessenger > fpMessenger
Static Protected Attributes
static
G4DNAMolecularReactionTable * fpInstance
Detailed Description
G4DNAMolecularReactionTable sorts out the G4DNAMolecularReactionData for bimolecular reaction
Definition at line 152 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 152 of file G4DNAMolecularReactionTable.hh
Member Typedef Documentation
using G4DNAMolecularReactionTable::Data = const G4DNAMolecularReactionData
Definition at line 165 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 165 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionTable::DataList = std::vector<Data*>
Definition at line 167 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 167 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionTable::Reactant = const G4MolecularConfiguration
Definition at line 164 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 164 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionTable::ReactantList = std::vector<Reactant*>
Definition at line 166 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 166 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionTable::ReactionDataMap = std::map<Reactant*, SpecificDataList>
Definition at line 170 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 170 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionTable::ReactionDataMV = std::map<Reactant*, DataList>
Definition at line 172 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 172 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionTable::ReactivesMV = std::map<Reactant*, ReactantList>
Definition at line 171 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 171 of file G4DNAMolecularReactionTable.hh
using G4DNAMolecularReactionTable::SpecificDataList = std::map<Reactant*, Data*>
Definition at line 168 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 168 of file G4DNAMolecularReactionTable.hh
Constructor & Destructor Documentation
G4DNAMolecularReactionTable::G4DNAMolecularReactionTable () protected
Definition at line 282 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 282 of file G4DNAMolecularReactionTable.cc
Referenced by GetReactionTable(), and Instance().
G4DNAMolecularReactionTable::~G4DNAMolecularReactionTable () virtual default
Member Function Documentation
const G4DNAMolecularReactionTable::ReactantList * G4DNAMolecularReactionTable::CanReactWith (Reactant * pMolecule) const
Given a molecule's type, it returns with which a reaction is allowed
Definition at line 550 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 550 of file G4DNAMolecularReactionTable.cc
References FatalErrorInArgument, fReactantsMV, fVerbose, G4cout, G4endl, G4Exception(), and G4MolecularConfiguration::GetName().
Referenced by G4DNAMoleculeEncounterStepper::CalculateStep(), and PrintTable().
void G4DNAMolecularReactionTable::DeleteInstance () static
Definition at line 271 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 271 of file G4DNAMolecularReactionTable.cc
References fpInstance.
Referenced by G4DNAChemistryManager::Clear().
const G4DNAMolecularReactionTable::ReactionDataMap & G4DNAMolecularReactionTable::GetAllReactionData ()
Definition at line 530 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 530 of file G4DNAMolecularReactionTable.cc
References fReactionData.
size_t G4DNAMolecularReactionTable::GetNReactions () const
Definition at line 724 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 724 of file G4DNAMolecularReactionTable.cc
References fVectorOfReactionData.
G4DNAMolecularReactionTable::Data * G4DNAMolecularReactionTable::GetReaction (int reactionID) const
Definition at line 712 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 712 of file G4DNAMolecularReactionTable.cc
References fVectorOfReactionData.
G4DNAMolecularReactionTable::Data * G4DNAMolecularReactionTable::GetReactionData (Reactant * pReactant1, Reactant * pReactant2) const
Definition at line 496 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 496 of file G4DNAMolecularReactionTable.cc
References FatalErrorInArgument, fReactionData, G4cout, G4endl, G4Exception(), and G4MolecularConfiguration::GetName().
Referenced by GetReactionData(), G4DNASmoluchowskiReactionModel::GetReactionRadius(), G4DNASmoluchowskiReactionModel::Initialise(), G4DNASmoluchowskiReactionModel::InitialiseToPrint(), and G4DNAMolecularReaction::MakeReaction().
G4DNAMolecularReactionTable::Data * G4DNAMolecularReactionTable::GetReactionData (const G4String & mol1, const G4String & mol2) const
Definition at line 653 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 653 of file G4DNAMolecularReactionTable.cc
References G4MoleculeTable::GetConfiguration(), G4MoleculeTable::GetMoleculeTable(), and GetReactionData().
const G4DNAMolecularReactionTable::DataList * G4DNAMolecularReactionTable::GetReactionData (const G4MolecularConfiguration * molecule) const
Definition at line 631 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 631 of file G4DNAMolecularReactionTable.cc
References FatalErrorInArgument, fReactionDataMV, G4Exception(), G4MolecularConfiguration::GetName(), and it.
G4DNAMolecularReactionTable * G4DNAMolecularReactionTable::GetReactionTable () static
Definition at line 249 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 249 of file G4DNAMolecularReactionTable.cc
References fpInstance, and G4DNAMolecularReactionTable().
Referenced by G4DNAMolecularStepByStepModel::Initialize(), G4DNAChemistryManager::InitializeMaster(), and G4DNAChemistryManager::InitializeThread().
const G4DNAMolecularReactionTable::SpecificDataList * G4DNAMolecularReactionTable::GetReativesNData (const G4MolecularConfiguration * molecule) const
Definition at line 596 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 596 of file G4DNAMolecularReactionTable.cc
References FatalErrorInArgument, fReactionData, fVerbose, G4cout, G4endl, G4Exception(), and G4MolecularConfiguration::GetName().
G4DNAMolecularReactionTable::DataList G4DNAMolecularReactionTable::GetVectorOfReactionData ()
Definition at line 535 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 535 of file G4DNAMolecularReactionTable.cc
References fVectorOfReactionData.
G4DNAMolecularReactionTable * G4DNAMolecularReactionTable::Instance (void) static
Definition at line 260 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 260 of file G4DNAMolecularReactionTable.cc
References fpInstance, and G4DNAMolecularReactionTable().
Referenced by G4DNAChemistryManager::SetGlobalTemperature().
void G4DNAMolecularReactionTable::PrintTable (G4VDNAReactionModel * pReactionModel = 0)
Definition at line 323 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 323 of file G4DNAMolecularReactionTable.cc
References CanReactWith(), G4UIcommand::ConvertToString(), e, fReactantsMV, fReactionData, G4cout, G4endl, G4MolecularConfiguration::GetName(), G4DNAMolecularReactionData::GetNbProducts(), G4DNAMolecularReactionData::GetObservedReactionRateConstant(), G4DNAMolecularReactionData::GetProduct(), G4VDNAReactionModel::GetReactionRadius(), G4VDNAReactionModel::GetReactionTable(), G4VDNAReactionModel::InitialiseToPrint(), left, BTOF::length, m3, mole, n, nanometer, G4VDNAReactionModel::SetReactionTable(), title(), and TRUE.
Referenced by G4EmDNAChemistry::ConstructTimeStepModel(), G4EmDNAChemistry_option1::ConstructTimeStepModel(), G4EmDNAChemistry_option2::ConstructTimeStepModel(), and G4ReactionTableMessenger::SetNewValue().
void G4DNAMolecularReactionTable::ScaleReactionRateForNewTemperature (double temp_K)
Definition at line 691 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 691 of file G4DNAMolecularReactionTable.cc
References fVectorOfReactionData.
Referenced by G4DNAChemistryManager::SetGlobalTemperature().
void G4DNAMolecularReactionTable::SetReaction (G4double observedReactionRate, Reactant * reactive1, Reactant * reactive2)
Define a reaction : First argument : reaction rate Second argument : reactant 1 Third argument : reactant 2 Fourth argument : a std::vector holding the molecular products if this last argument is NULL then it will be interpreted as a reaction giving no products
Definition at line 313 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 313 of file G4DNAMolecularReactionTable.cc
Referenced by G4EmDNAChemistry::ConstructReactionTable(), G4EmDNAChemistry_option1::ConstructReactionTable(), G4EmDNAChemistry_option2::ConstructReactionTable(), and G4ReactionTableMessenger::SetNewValue().
void G4DNAMolecularReactionTable::SetReaction (G4DNAMolecularReactionData * pReactionData)
Definition at line 291 of file G4DNAMolecularReactionTable.cc.
View newest version in sPHENIX GitHub at line 291 of file G4DNAMolecularReactionTable.cc
References fReactantsMV, fReactionData, fReactionDataMV, fVectorOfReactionData, G4DNAMolecularReactionData::GetReactant1(), G4DNAMolecularReactionData::GetReactant2(), and G4DNAMolecularReactionData::SetReactionID().
Member Data Documentation
G4DNAMolecularReactionTable * G4DNAMolecularReactionTable::fpInstance static protected
Definition at line 156 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 156 of file G4DNAMolecularReactionTable.hh
Referenced by DeleteInstance(), GetReactionTable(), and Instance().
std::unique_ptr<G4ReactionTableMessenger> G4DNAMolecularReactionTable::fpMessenger protected
Definition at line 223 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 223 of file G4DNAMolecularReactionTable.hh
ReactivesMV G4DNAMolecularReactionTable::fReactantsMV protected
Definition at line 220 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 220 of file G4DNAMolecularReactionTable.hh
Referenced by CanReactWith(), PrintTable(), and SetReaction().
ReactionDataMap G4DNAMolecularReactionTable::fReactionData protected
Definition at line 219 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 219 of file G4DNAMolecularReactionTable.hh
Referenced by GetAllReactionData(), GetReactionData(), GetReativesNData(), PrintTable(), and SetReaction().
ReactionDataMV G4DNAMolecularReactionTable::fReactionDataMV protected
Definition at line 221 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 221 of file G4DNAMolecularReactionTable.hh
Referenced by GetReactionData(), and SetReaction().
std::vector<std::unique_ptr<Data> > G4DNAMolecularReactionTable::fVectorOfReactionData protected
Definition at line 222 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 222 of file G4DNAMolecularReactionTable.hh
Referenced by GetNReactions(), GetReaction(), GetVectorOfReactionData(), ScaleReactionRateForNewTemperature(), and SetReaction().
G4bool G4DNAMolecularReactionTable::fVerbose protected
Definition at line 217 of file G4DNAMolecularReactionTable.hh.
View newest version in sPHENIX GitHub at line 217 of file G4DNAMolecularReactionTable.hh
Referenced by CanReactWith(), and GetReativesNData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAMolecularReactionTable.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4DNAMolecularReactionTable.cc