ECCE @ EIC Software: Par01PionShowerModel Class Reference
Par01PionShowerModel Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01PionShowerModel.hh>
Public Member Functions
Par01PionShowerModel (G4String, G4Region *)
Par01PionShowerModel (G4String)
~Par01PionShowerModel ()
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4bool ModelTrigger (const G4FastTrack &)
virtual void DoIt (const G4FastTrack &, G4FastStep &)
Public Member Functions inherited from G4VFastSimulationModel
G4VFastSimulationModel (const G4String &aName)
G4VFastSimulationModel (const G4String &aName, G4Envelope *, G4bool IsUnique=FALSE)
virtual ~G4VFastSimulationModel ()
virtual G4bool AtRestModelTrigger (const G4FastTrack &)
virtual void AtRestDoIt (const G4FastTrack &, G4FastStep &)
const G4String GetName () const
G4bool operator== (const G4VFastSimulationModel &) const
Private Member Functions
void AssignSpotAndCallHit (const Par01EnergySpot &eSpot)
void FillFakeStep (const Par01EnergySpot &eSpot)
void Explode (const G4FastTrack &)
void BuildDetectorResponse ()
Private Attributes
G4Step * fFakeStep
G4StepPoint * fFakePreStepPoint
G4StepPoint * fFakePostStepPoint
G4TouchableHandle fTouchableHandle
G4Navigator * fpNavigator
G4bool fNaviSetup
std::vector< Par01EnergySpot > feSpotList
Detailed Description
Definition at line 45 of file Par01PionShowerModel.hh.
View newest version in sPHENIX GitHub at line 45 of file Par01PionShowerModel.hh
Constructor & Destructor Documentation
Par01PionShowerModel::Par01PionShowerModel (G4String modelName, G4Region * envelope)
Definition at line 48 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 48 of file Par01PionShowerModel.cc
References fFakePostStepPoint, fFakePreStepPoint, fFakeStep, fNaviSetup, fpNavigator, fTouchableHandle, G4Step::GetPostStepPoint(), and G4Step::GetPreStepPoint().
Par01PionShowerModel::Par01PionShowerModel (G4String modelName)
Definition at line 61 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 61 of file Par01PionShowerModel.cc
References fFakePostStepPoint, fFakePreStepPoint, fFakeStep, fNaviSetup, fpNavigator, fTouchableHandle, G4Step::GetPostStepPoint(), and G4Step::GetPreStepPoint().
Par01PionShowerModel::~Par01PionShowerModel ()
Definition at line 74 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 74 of file Par01PionShowerModel.cc
References fFakeStep, and fpNavigator.
Member Function Documentation
void Par01PionShowerModel::AssignSpotAndCallHit (const Par01EnergySpot & eSpot) private
Definition at line 189 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 189 of file Par01PionShowerModel.cc
References fFakeStep, FillFakeStep(), G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), and G4VSensitiveDetector::Hit().
Referenced by BuildDetectorResponse().
void Par01PionShowerModel::BuildDetectorResponse () private
Definition at line 171 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 171 of file Par01PionShowerModel.cc
References AssignSpotAndCallHit(), and feSpotList.
Referenced by DoIt().
void Par01PionShowerModel::DoIt (const G4FastTrack & fastTrack, G4FastStep & fastStep) virtual
Implements G4VFastSimulationModel.
Definition at line 100 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 100 of file Par01PionShowerModel.cc
References BuildDetectorResponse(), Explode(), G4Track::GetKineticEnergy(), G4FastTrack::GetPrimaryTrack(), G4FastStep::KillPrimaryTrack(), G4FastStep::ProposePrimaryTrackPathLength(), and G4FastStep::ProposeTotalEnergyDeposited().
void Par01PionShowerModel::Explode (const G4FastTrack & fastTrack) private
Definition at line 119 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 119 of file Par01PionShowerModel.cc
References cm, CLHEP::Hep3Vector::cross(), feSpotList, G4UniformRand, G4FastTrack::GetEnvelopeSolid(), G4FastTrack::GetInverseAffineTransformation(), G4Track::GetKineticEnergy(), G4Track::GetMomentumDirection(), G4FastTrack::GetPrimaryTrack(), G4FastTrack::GetPrimaryTrackLocalDirection(), G4FastTrack::GetPrimaryTrackLocalPosition(), CLHEP::Hep3Vector::orthogonal(), phi, r, Par01EnergySpot::SetEnergy(), Par01EnergySpot::SetPosition(), G4INCL::DeJongSpin::shoot(), twopi, and z.
Referenced by DoIt().
void Par01PionShowerModel::FillFakeStep (const Par01EnergySpot & eSpot) private
Definition at line 218 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 218 of file Par01PionShowerModel.cc
References fFakePreStepPoint, fFakeStep, fNaviSetup, fpNavigator, fTouchableHandle, Par01EnergySpot::GetEnergy(), Par01EnergySpot::GetPosition(), G4TransportationManager::GetTransportationManager(), G4Step::SetTotalEnergyDeposit(), and G4StepPoint::SetTouchableHandle().
Referenced by AssignSpotAndCallHit().
G4bool Par01PionShowerModel::IsApplicable (const G4ParticleDefinition & particleType) virtual
Implements G4VFastSimulationModel.
Definition at line 82 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 82 of file Par01PionShowerModel.cc
References G4PionMinus::PionMinusDefinition(), and G4PionPlus::PionPlusDefinition().
G4bool Par01PionShowerModel::ModelTrigger (const G4FastTrack &) virtual
Implements G4VFastSimulationModel.
Definition at line 91 of file Par01PionShowerModel.cc.
View newest version in sPHENIX GitHub at line 91 of file Par01PionShowerModel.cc
Member Data Documentation
std::vector<Par01EnergySpot> Par01PionShowerModel::feSpotList private
Definition at line 80 of file Par01PionShowerModel.hh.
View newest version in sPHENIX GitHub at line 80 of file Par01PionShowerModel.hh
Referenced by BuildDetectorResponse(), and Explode().
G4StepPoint * Par01PionShowerModel::fFakePostStepPoint private
Definition at line 75 of file Par01PionShowerModel.hh.
View newest version in sPHENIX GitHub at line 75 of file Par01PionShowerModel.hh
Referenced by Par01PionShowerModel().
G4StepPoint* Par01PionShowerModel::fFakePreStepPoint private
Definition at line 75 of file Par01PionShowerModel.hh.
View newest version in sPHENIX GitHub at line 75 of file Par01PionShowerModel.hh
Referenced by FillFakeStep(), and Par01PionShowerModel().
G4Step* Par01PionShowerModel::fFakeStep private
Definition at line 74 of file Par01PionShowerModel.hh.
View newest version in sPHENIX GitHub at line 74 of file Par01PionShowerModel.hh
Referenced by AssignSpotAndCallHit(), FillFakeStep(), Par01PionShowerModel(), and ~Par01PionShowerModel().
G4bool Par01PionShowerModel::fNaviSetup private
Definition at line 78 of file Par01PionShowerModel.hh.
View newest version in sPHENIX GitHub at line 78 of file Par01PionShowerModel.hh
Referenced by FillFakeStep(), and Par01PionShowerModel().
G4Navigator* Par01PionShowerModel::fpNavigator private
Definition at line 77 of file Par01PionShowerModel.hh.
View newest version in sPHENIX GitHub at line 77 of file Par01PionShowerModel.hh
Referenced by FillFakeStep(), Par01PionShowerModel(), and ~Par01PionShowerModel().
G4TouchableHandle Par01PionShowerModel::fTouchableHandle private
Definition at line 76 of file Par01PionShowerModel.hh.
View newest version in sPHENIX GitHub at line 76 of file Par01PionShowerModel.hh
Referenced by FillFakeStep(), and Par01PionShowerModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01PionShowerModel.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/src/Par01PionShowerModel.cc