ECCE @ EIC Software: RE02RunAction Class Reference
RE02RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/include/RE02RunAction.hh>
Public Member Functions
RE02RunAction ()
virtual ~RE02RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
G4int CopyNo (G4int ix, G4int iy, G4int iz)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
std::vector< G4String > fSDName
G4int fNx
G4int fNy
G4int fNz
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
User run action class
G4Run* GenerateRun() instanciates a run of RE02Run with a sensitive detector name
void BeginOfRunAction(const G4Run*) shows the run number
void EndOfRunAction(const G4Run*) shows accumulated information of primitive scorers and outputs total energy deposit into "totED.txt" file
G4int CopyNo(G4int ix, G4int iy, G4int iz) returns a copy number of the segment number of the water phantom indicated by three dimentional indexes
Definition at line 68 of file RE02RunAction.hh.
View newest version in sPHENIX GitHub at line 68 of file RE02RunAction.hh
Constructor & Destructor Documentation
RE02RunAction::RE02RunAction ()
Definition at line 52 of file RE02RunAction.cc.
View newest version in sPHENIX GitHub at line 52 of file RE02RunAction.cc
References fSDName.
RE02RunAction::~RE02RunAction () virtual
Definition at line 63 of file RE02RunAction.cc.
View newest version in sPHENIX GitHub at line 63 of file RE02RunAction.cc
References fSDName.
Member Function Documentation
void RE02RunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 80 of file RE02RunAction.cc.
View newest version in sPHENIX GitHub at line 80 of file RE02RunAction.cc
References G4cout, G4endl, and G4Run::GetRunID().
G4int RE02RunAction::CopyNo (G4int ix, G4int iy, G4int iz) inline
Definition at line 84 of file RE02RunAction.hh.
View newest version in sPHENIX GitHub at line 84 of file RE02RunAction.hh
References fNx, and fNz.
Referenced by EndOfRunAction().
void RE02RunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 87 of file RE02RunAction.cc.
View newest version in sPHENIX GitHub at line 87 of file RE02RunAction.cc
References cm, CopyNo(), RE02Run::DumpAllScorer(), file, fNx, fNy, fNz, G4BestUnit, G4cout, G4endl, RE02Run::GetHitsMap(), G4VHitsCollection::GetName(), G4Run::GetNumberOfEvent(), RE02DetectorConstruction::GetNumberOfSegmentsInPhantom(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), G4UserRunAction::IsMaster(), and MeV.
G4Run * RE02RunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 70 of file RE02RunAction.cc.
View newest version in sPHENIX GitHub at line 70 of file RE02RunAction.cc
References fSDName.
Member Data Documentation
G4int RE02RunAction::fNx private
Definition at line 93 of file RE02RunAction.hh.
View newest version in sPHENIX GitHub at line 93 of file RE02RunAction.hh
Referenced by CopyNo(), and EndOfRunAction().
G4int RE02RunAction::fNy private
Definition at line 93 of file RE02RunAction.hh.
View newest version in sPHENIX GitHub at line 93 of file RE02RunAction.hh
Referenced by EndOfRunAction().
G4int RE02RunAction::fNz private
Definition at line 93 of file RE02RunAction.hh.
View newest version in sPHENIX GitHub at line 93 of file RE02RunAction.hh
Referenced by CopyNo(), and EndOfRunAction().
std::vector<G4String> RE02RunAction::fSDName private
Definition at line 90 of file RE02RunAction.hh.
View newest version in sPHENIX GitHub at line 90 of file RE02RunAction.hh
Referenced by GenerateRun(), RE02RunAction(), and ~RE02RunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/include/RE02RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE02/src/RE02RunAction.cc