ECCE @ EIC Software: G4TransportationLogger Class Reference
G4TransportationLogger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/transportation/include/G4TransportationLogger.hh>
Public Member Functions
G4TransportationLogger (const G4String &className, G4int verbosity)
G4TransportationLogger (const char *className, G4int verbosity)
~G4TransportationLogger ()
void ReportLoopingTrack (const G4Track &track, const G4Step &stepInfo, G4int numTrials, G4long noCalls, const char *methodName) const
void ReportLooperThresholds (const char *className)
void SetThresholds (G4double newEnWarn, G4double importantEnergy, G4int newMaxTrials)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
G4double GetThresholdWarningEnergy () const
G4double GetThresholdImportantEnergy () const
G4double GetThresholdTrials () const
void SetThresholdWarningEnergy (G4double val)
void SetThresholdImportantEnergy (G4double val)
void SetThresholdTrials (G4int maxNoTrials)
Private Attributes
G4String fClassName
G4int fVerbose
G4double fThldWarningEnergy
G4double fThldImportantEnergy
G4int fThldTrials
Detailed Description
Definition at line 47 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 47 of file G4TransportationLogger.hh
Constructor & Destructor Documentation
G4TransportationLogger::G4TransportationLogger (const G4String & className, G4int verbosity)
Definition at line 42 of file G4TransportationLogger.cc.
View newest version in sPHENIX GitHub at line 42 of file G4TransportationLogger.cc
G4TransportationLogger::G4TransportationLogger (const char * className, G4int verbosity)
Definition at line 49 of file G4TransportationLogger.cc.
View newest version in sPHENIX GitHub at line 49 of file G4TransportationLogger.cc
G4TransportationLogger::~G4TransportationLogger ()
Definition at line 56 of file G4TransportationLogger.cc.
View newest version in sPHENIX GitHub at line 56 of file G4TransportationLogger.cc
Member Function Documentation
G4double G4TransportationLogger::GetThresholdImportantEnergy () const inline
Definition at line 77 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4TransportationLogger.hh
References fThldImportantEnergy.
Referenced by ReportLooperThresholds().
G4double G4TransportationLogger::GetThresholdTrials () const inline
Definition at line 78 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4TransportationLogger.hh
References fThldTrials.
Referenced by ReportLooperThresholds(), and ReportLoopingTrack().
G4double G4TransportationLogger::GetThresholdWarningEnergy () const inline
Definition at line 76 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4TransportationLogger.hh
References fThldWarningEnergy.
Referenced by ReportLooperThresholds(), and ReportLoopingTrack().
G4int G4TransportationLogger::GetVerboseLevel () const inline
Definition at line 71 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4TransportationLogger.hh
References fVerbose.
void G4TransportationLogger::ReportLooperThresholds (const char * className)
Definition at line 75 of file G4TransportationLogger.cc.
View newest version in sPHENIX GitHub at line 75 of file G4TransportationLogger.cc
References G4cout, G4endl, GetThresholdImportantEnergy(), GetThresholdTrials(), GetThresholdWarningEnergy(), and CLHEP::MeV.
Referenced by G4CoupledTransportation::ReportLooperThresholds(), and G4Transportation::ReportLooperThresholds().
void G4TransportationLogger::ReportLoopingTrack (const G4Track & track, const G4Step & stepInfo, G4int numTrials, G4long noCalls, const char * methodName) const
Definition at line 92 of file G4TransportationLogger.cc.
View newest version in sPHENIX GitHub at line 92 of file G4TransportationLogger.cc
References centimeter, fClassName, G4endl, G4Exception(), G4Track::GetCurrentStepNumber(), G4StepPoint::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4Track::GetMomentum(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), GetThresholdTrials(), GetThresholdWarningEnergy(), G4Track::GetVolume(), gram, JustWarning, CLHEP::Hep3Vector::mag(), material(), MeV, and mm.
Referenced by G4Transportation::AlongStepDoIt(), and G4CoupledTransportation::AlongStepDoIt().
void G4TransportationLogger::SetThresholdImportantEnergy (G4double val) inline
Definition at line 81 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4TransportationLogger.hh
References fThldImportantEnergy.
Referenced by SetThresholds().
void G4TransportationLogger::SetThresholds (G4double newEnWarn, G4double importantEnergy, G4int newMaxTrials)
Definition at line 64 of file G4TransportationLogger.cc.
View newest version in sPHENIX GitHub at line 64 of file G4TransportationLogger.cc
References SetThresholdImportantEnergy(), SetThresholdTrials(), and SetThresholdWarningEnergy().
void G4TransportationLogger::SetThresholdTrials (G4int maxNoTrials) inline
Definition at line 82 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4TransportationLogger.hh
References fThldTrials, and max.
Referenced by SetThresholds().
void G4TransportationLogger::SetThresholdWarningEnergy (G4double val) inline
Definition at line 80 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4TransportationLogger.hh
References fThldWarningEnergy.
Referenced by SetThresholds().
void G4TransportationLogger::SetVerboseLevel (G4int level) inline
Definition at line 72 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4TransportationLogger.hh
References fVerbose.
Member Data Documentation
G4String G4TransportationLogger::fClassName private
Definition at line 86 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4TransportationLogger.hh
Referenced by ReportLoopingTrack().
G4double G4TransportationLogger::fThldImportantEnergy private
Definition at line 93 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4TransportationLogger.hh
Referenced by GetThresholdImportantEnergy(), and SetThresholdImportantEnergy().
G4int G4TransportationLogger::fThldTrials private
Definition at line 94 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 94 of file G4TransportationLogger.hh
Referenced by GetThresholdTrials(), and SetThresholdTrials().
G4double G4TransportationLogger::fThldWarningEnergy private
Definition at line 92 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4TransportationLogger.hh
Referenced by GetThresholdWarningEnergy(), and SetThresholdWarningEnergy().
G4int G4TransportationLogger::fVerbose private
Definition at line 87 of file G4TransportationLogger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4TransportationLogger.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/transportation/include/G4TransportationLogger.hh
geant4/tree/geant4-10.6-release/source/processes/transportation/src/G4TransportationLogger.cc