ECCE @ EIC Software: G4ParticleHPMessenger Class Reference
G4ParticleHPMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPMessenger.hh>
Public Member Functions
G4ParticleHPMessenger (G4ParticleHPManager *)
~G4ParticleHPMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4ParticleHPManager * manager
G4UIdirectory * ParticleHPDir
G4UIcmdWithAString * PhotoEvaCmd
G4UIcmdWithAString * SkipMissingCmd
G4UIcmdWithAString * NeglectDopplerCmd
G4UIcmdWithAString * DoNotAdjustFSCmd
G4UIcmdWithAString * ProduceFissionFragementCmd
G4UIcmdWithAString * NRESP71Cmd
G4UIcmdWithAnInteger * VerboseCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 37 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 37 of file G4ParticleHPMessenger.hh
Constructor & Destructor Documentation
G4ParticleHPMessenger::G4ParticleHPMessenger (G4ParticleHPManager * man)
Definition at line 33 of file G4ParticleHPMessenger.cc.
View newest version in sPHENIX GitHub at line 33 of file G4ParticleHPMessenger.cc
References G4UIcommand::AvailableForStates(), DoNotAdjustFSCmd, G4State_Idle, G4State_PreInit, NeglectDopplerCmd, NRESP71Cmd, ParticleHPDir, PhotoEvaCmd, ProduceFissionFragementCmd, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcommand::SetRange(), SkipMissingCmd, and VerboseCmd.
G4ParticleHPMessenger::~G4ParticleHPMessenger ()
Definition at line 85 of file G4ParticleHPMessenger.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPMessenger.cc
References DoNotAdjustFSCmd, NeglectDopplerCmd, ParticleHPDir, PhotoEvaCmd, ProduceFissionFragementCmd, SkipMissingCmd, and VerboseCmd.
Member Function Documentation
void G4ParticleHPMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 96 of file G4ParticleHPMessenger.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ParticleHPMessenger.cc
References G4UIcommand::ConvertToInt(), DoNotAdjustFSCmd, manager, NeglectDopplerCmd, NRESP71Cmd, PhotoEvaCmd, ProduceFissionFragementCmd, G4ParticleHPManager::SetDoNotAdjustFinalState(), G4ParticleHPManager::SetNeglectDoppler(), G4ParticleHPManager::SetProduceFissionFragments(), G4ParticleHPManager::SetSkipMissingIsotopes(), G4ParticleHPManager::SetUseNRESP71Model(), G4ParticleHPManager::SetUseOnlyPhotoEvaporation(), G4ParticleHPManager::SetVerboseLevel(), SkipMissingCmd, and VerboseCmd.
Member Data Documentation
G4UIcmdWithAString* G4ParticleHPMessenger::DoNotAdjustFSCmd private
Definition at line 52 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPMessenger.hh
Referenced by G4ParticleHPMessenger(), SetNewValue(), and ~G4ParticleHPMessenger().
G4ParticleHPManager* G4ParticleHPMessenger::manager private
Definition at line 46 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* G4ParticleHPMessenger::NeglectDopplerCmd private
Definition at line 51 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPMessenger.hh
Referenced by G4ParticleHPMessenger(), SetNewValue(), and ~G4ParticleHPMessenger().
G4UIcmdWithAString* G4ParticleHPMessenger::NRESP71Cmd private
Definition at line 54 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPMessenger.hh
Referenced by G4ParticleHPMessenger(), and SetNewValue().
G4UIdirectory* G4ParticleHPMessenger::ParticleHPDir private
Definition at line 48 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPMessenger.hh
Referenced by G4ParticleHPMessenger(), and ~G4ParticleHPMessenger().
G4UIcmdWithAString* G4ParticleHPMessenger::PhotoEvaCmd private
Definition at line 49 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPMessenger.hh
Referenced by G4ParticleHPMessenger(), SetNewValue(), and ~G4ParticleHPMessenger().
G4UIcmdWithAString* G4ParticleHPMessenger::ProduceFissionFragementCmd private
Definition at line 53 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPMessenger.hh
Referenced by G4ParticleHPMessenger(), SetNewValue(), and ~G4ParticleHPMessenger().
G4UIcmdWithAString* G4ParticleHPMessenger::SkipMissingCmd private
Definition at line 50 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPMessenger.hh
Referenced by G4ParticleHPMessenger(), SetNewValue(), and ~G4ParticleHPMessenger().
G4UIcmdWithAnInteger* G4ParticleHPMessenger::VerboseCmd private
Definition at line 55 of file G4ParticleHPMessenger.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPMessenger.hh
Referenced by G4ParticleHPMessenger(), SetNewValue(), and ~G4ParticleHPMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPMessenger.cc