ECCE @ EIC Software: G4INCL::AvatarDumpAction Class Reference
G4INCL::AvatarDumpAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLAvatarDumpAction.hh>
Public Member Functions
AvatarDumpAction ()
virtual ~AvatarDumpAction ()
virtual void beforeCascadeUserAction (IPropagationModel *)
virtual void afterAvatarUserAction (IAvatar *avatar, Nucleus *nucleus, FinalState *)
virtual void afterCascadeUserAction (Nucleus *)
Public Member Functions inherited from G4INCL::CascadeAction
CascadeAction ()
virtual ~CascadeAction ()
virtual void beforeRunUserAction (Config const *)
virtual void beforePropagationUserAction (IPropagationModel *)
virtual void beforeAvatarUserAction (IAvatar *, Nucleus *)
virtual void afterPropagationUserAction (IPropagationModel *, IAvatar *)
virtual void afterRunUserAction ()
Private Attributes
std::ofstream * oFile
G4int eventCounter
Detailed Description
Definition at line 53 of file G4INCLAvatarDumpAction.hh.
View newest version in sPHENIX GitHub at line 53 of file G4INCLAvatarDumpAction.hh
Constructor & Destructor Documentation
G4INCL::AvatarDumpAction::AvatarDumpAction ()
Definition at line 44 of file G4INCLAvatarDumpAction.cc.
View newest version in sPHENIX GitHub at line 44 of file G4INCLAvatarDumpAction.cc
G4INCL::AvatarDumpAction::~AvatarDumpAction () virtual
Definition at line 50 of file G4INCLAvatarDumpAction.cc.
View newest version in sPHENIX GitHub at line 50 of file G4INCLAvatarDumpAction.cc
Member Function Documentation
void G4INCL::AvatarDumpAction::afterAvatarUserAction (IAvatar * avatar, Nucleus * nucleus, FinalState * finalState) virtual
Reimplemented from G4INCL::CascadeAction.
Definition at line 58 of file G4INCLAvatarDumpAction.cc.
View newest version in sPHENIX GitHub at line 58 of file G4INCLAvatarDumpAction.cc
References G4INCL::UnorderedVector< T >::contains(), e, G4INCL::FinalState::getCreatedParticles(), G4INCL::FinalState::getDestroyedParticles(), G4INCL::FinalState::getEnteringParticles(), G4INCL::FinalState::getModifiedParticles(), G4INCL::FinalState::getOutgoingParticles(), G4INCL::Store::getParticles(), G4INCL::Nucleus::getStore(), G4INCL::IAvatar::getTime(), G4INCL::IAvatar::getType(), G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), and pos().
void G4INCL::AvatarDumpAction::afterCascadeUserAction (Nucleus *) virtual
Reimplemented from G4INCL::CascadeAction.
Definition at line 97 of file G4INCLAvatarDumpAction.cc.
View newest version in sPHENIX GitHub at line 97 of file G4INCLAvatarDumpAction.cc
References eventCounter, and oFile.
void G4INCL::AvatarDumpAction::beforeCascadeUserAction (IPropagationModel *) virtual
Reimplemented from G4INCL::CascadeAction.
Definition at line 52 of file G4INCLAvatarDumpAction.cc.
View newest version in sPHENIX GitHub at line 52 of file G4INCLAvatarDumpAction.cc
References eventCounter, and oFile.
Member Data Documentation
G4int G4INCL::AvatarDumpAction::eventCounter private
Definition at line 65 of file G4INCLAvatarDumpAction.hh.
View newest version in sPHENIX GitHub at line 65 of file G4INCLAvatarDumpAction.hh
Referenced by afterCascadeUserAction(), and beforeCascadeUserAction().
std::ofstream* G4INCL::AvatarDumpAction::oFile private
Definition at line 64 of file G4INCLAvatarDumpAction.hh.
View newest version in sPHENIX GitHub at line 64 of file G4INCLAvatarDumpAction.hh
Referenced by afterCascadeUserAction(), and beforeCascadeUserAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLAvatarDumpAction.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLAvatarDumpAction.cc