ECCE @ EIC Software: G4Step Class Reference
G4Step Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4Step.hh>
Public Member Functions
G4Step ()
~G4Step ()
G4Step (const G4Step &)
G4Step & operator= (const G4Step &)
G4Track * GetTrack () const
void SetTrack (G4Track *value)
G4StepPoint * GetPreStepPoint () const
void SetPreStepPoint (G4StepPoint *value)
G4StepPoint * GetPostStepPoint () const
void SetPostStepPoint (G4StepPoint *value)
G4double GetStepLength () const
void SetStepLength (G4double value)
G4double GetTotalEnergyDeposit () const
void SetTotalEnergyDeposit (G4double value)
G4double GetNonIonizingEnergyDeposit () const
void SetNonIonizingEnergyDeposit (G4double value)
G4SteppingControl GetControlFlag () const
void SetControlFlag (G4SteppingControl StepControlFlag)
void AddTotalEnergyDeposit (G4double value)
void ResetTotalEnergyDeposit ()
void AddNonIonizingEnergyDeposit (G4double value)
void ResetNonIonizingEnergyDeposit ()
G4bool IsFirstStepInVolume () const
G4bool IsLastStepInVolume () const
void SetFirstStepFlag ()
void ClearFirstStepFlag ()
void SetLastStepFlag ()
void ClearLastStepFlag ()
G4ThreeVector GetDeltaPosition () const
G4double GetDeltaTime () const
G4ThreeVector GetDeltaMomentum () const
G4double GetDeltaEnergy () const
void InitializeStep (G4Track *aValue)
void UpdateTrack ()
void CopyPostToPreStepPoint ()
G4Polyline * CreatePolyline () const
size_t GetNumberOfSecondariesInCurrentStep () const
const std::vector< const
G4Track * > * GetSecondaryInCurrentStep () const
const G4TrackVector * GetSecondary () const
G4TrackVector * GetfSecondary ()
G4TrackVector * NewSecondaryVector ()
void DeleteSecondaryVector ()
void SetSecondary (G4TrackVector *value)
void SetPointerToVectorOfAuxiliaryPoints (std::vector< G4ThreeVector > *theNewVectorPointer)
std::vector< G4ThreeVector > * GetPointerToVectorOfAuxiliaryPoints () const
Protected Attributes
G4double fTotalEnergyDeposit
G4double fNonIonizingEnergyDeposit
Private Types
typedef const G4Track * CT
Private Attributes
G4StepPoint * fpPreStepPoint
G4StepPoint * fpPostStepPoint
G4double fStepLength
G4Track * fpTrack
G4SteppingControl fpSteppingControlFlag
G4bool fFirstStepInVolume
G4bool fLastStepInVolume
G4TrackVector * fSecondary
size_t nSecondaryByLastStep
std::vector< CT > * secondaryInCurrentStep
std::vector< G4ThreeVector > * fpVectorOfAuxiliaryPointsPointer
Detailed Description
Definition at line 68 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 68 of file G4Step.hh
Member Typedef Documentation
typedef const G4Track* G4Step::CT private
Definition at line 228 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 228 of file G4Step.hh
Constructor & Destructor Documentation
G4Step::G4Step ()
Definition at line 52 of file G4Step.cc.
View newest version in sPHENIX GitHub at line 52 of file G4Step.cc
References fpPostStepPoint, fpPreStepPoint, and secondaryInCurrentStep.
G4Step::~G4Step ()
Definition at line 70 of file G4Step.cc.
View newest version in sPHENIX GitHub at line 70 of file G4Step.cc
References fpPostStepPoint, fpPreStepPoint, fSecondary, and secondaryInCurrentStep.
G4Step::G4Step (const G4Step & right)
Definition at line 92 of file G4Step.cc.
View newest version in sPHENIX GitHub at line 92 of file G4Step.cc
References fpPostStepPoint, fpPreStepPoint, fSecondary, and secondaryInCurrentStep.
Member Function Documentation
void G4Step::AddNonIonizingEnergyDeposit (G4double value)
Referenced by G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
void G4Step::AddTotalEnergyDeposit (G4double value)
Referenced by G4SteppingManager::ApplyProductionCut(), G4UCNBoundaryProcess::InvokeSD(), G4OpBoundaryProcess::InvokeSD(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
void G4Step::ClearFirstStepFlag ()
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
void G4Step::ClearLastStepFlag ()
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
void G4Step::CopyPostToPreStepPoint ()
Referenced by G4ITStepProcessor::InitDefineStep(), and G4SteppingManager::Stepping().
G4Polyline* G4Step::CreatePolyline () const
void G4Step::DeleteSecondaryVector ()
Referenced by G4FastList< G4Track >::DeleteObject(), G4ITStepProcessor::~G4ITStepProcessor(), and G4SteppingManager::~G4SteppingManager().
G4SteppingControl G4Step::GetControlFlag () const
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), and G4SteppingManager::Stepping().
G4double G4Step::GetDeltaEnergy () const
Definition at line 193 of file G4Step.cc.
View newest version in sPHENIX GitHub at line 193 of file G4Step.cc
References fpPostStepPoint, fpPreStepPoint, G4Exception(), G4ThreadLocal, G4StepPoint::GetKineticEnergy(), and JustWarning.
Referenced by export_G4Step().
G4ThreeVector G4Step::GetDeltaMomentum () const
Definition at line 176 of file G4Step.cc.
View newest version in sPHENIX GitHub at line 176 of file G4Step.cc
References fpPostStepPoint, fpPreStepPoint, G4Exception(), G4ThreadLocal, G4StepPoint::GetMomentum(), and JustWarning.
Referenced by export_G4Step().
G4ThreeVector G4Step::GetDeltaPosition () const
Referenced by export_G4Step(), G4Cerenkov::PostStepDoIt(), and G4Scintillation::PostStepDoIt().
G4double G4Step::GetDeltaTime () const
Referenced by export_G4Step(), G4DNASmoluchowskiReactionModel::FindReaction(), and G4DNABrownianTransportation::PostStepDoIt().
G4TrackVector* G4Step::GetfSecondary ()
Referenced by G4FastList< G4Track >::DeleteObject(), G4SteppingManager::GetfSecondary(), and G4ITStepProcessor::SetupMembers().
G4double G4Step::GetNonIonizingEnergyDeposit () const
Referenced by G4ParallelWorldProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), G4ScoreSplittingProcess::PostStepDoIt(), XAluminumElectrodeSensitivity::ProcessHits(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
size_t G4Step::GetNumberOfSecondariesInCurrentStep () const
std::vector<G4ThreeVector>* G4Step::GetPointerToVectorOfAuxiliaryPoints () const inline
Definition at line 241 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 241 of file G4Step.hh
References fpVectorOfAuxiliaryPointsPointer.
Referenced by G4SmoothTrajectory::AppendStep().
G4StepPoint* G4Step::GetPostStepPoint () const
Referenced by HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4NuclearStopping::AlongStepDoIt(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), XrayFluoAnalysisManager::analyseStepping(), RE01Trajectory::AppendStep(), G4RichTrajectory::AppendStep(), G4SmoothTrajectory::AppendStep(), G4Trajectory::AppendStep(), RE04Trajectory::AppendStep(), G4BOptnForceFreeFlight::ApplyFinalStateBiasing(), G4DecayWithSpin::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4NIELCalculator::ComputeNIEL(), G4DNABrownianTransportation::ComputeStep(), G4VITSteppingVerbose::CopyState(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4AdjointCrossSurfChecker::CrossingAGivenRegisteredSurface(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4AdjointCrossSurfChecker::CrossingASphere(), G4SteppingManager::DefinePhysicalStepLength(), G4ITStepProcessor::DoDefinePhysicalStepLength(), G4ExceptionHandler::DumpTrackInfo(), export_G4Step(), F04TrajectoryPoint::F04TrajectoryPoint(), G4ImportanceProcess::G4ImportanceProcess(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4ScoreSplittingProcess::G4ScoreSplittingProcess(), G4SteppingManager::G4SteppingManager(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), G4Channeling::GetPost(), G4Scintillation::GetScintillationYieldByParticleType(), CCaloSD::getStepInfo(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePostStepDoItProcs(), G4SteppingManager::InvokePSDIP(), G4UCNBoundaryProcess::InvokeSD(), G4OpBoundaryProcess::InvokeSD(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellCurrent::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), PHG4RICHSteppingAction::MakeHit(), G4ErrorPropagator::MakeOneStep(), Par01EMShowerModel::Par01EMShowerModel(), Par01PionShowerModel::Par01PionShowerModel(), PrtOpBoundaryProcess::PostStepDoIt(), G4EicDircOpBoundaryProcess::PostStepDoIt(), G4PhononScattering::PostStepDoIt(), G4PhononReflection::PostStepDoIt(), G4Channeling::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4ITSteppingVerbose::PostStepVerbose(), eRositaTrackerSD::ProcessHits(), STCyclotronSensitiveTarget::ProcessHits(), LXeScintSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), ExN02TrackerSD::ProcessHits(), G4PSTrackCounter::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSNofCollision::ProcessHits(), ExP01TrackerSD::ProcessHits(), B2TrackerSD::ProcessHits(), DMXScintSD::ProcessHits(), PhantomSD::ProcessHits(), DMXPmtSD::ProcessHits(), TrackerSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), PrimaryKiller::ProcessHits(), LXePMTSD::ProcessHits_constStep(), WLSPhotonDetSD::ProcessHits_constStep(), G4ElectronIonPair::ResidualeChargePostStep(), G4ElectronIonPair::SampleIonsAlongStep(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4ITStepProcessor::SetupMembers(), G4SteppingVerbose::ShowStep(), G4ScoreSplittingProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), G4SteppingManager::Stepping(), PHG4SteppingAction::StoreLocalCoordinate(), G4ParallelWorldProcess::SwitchMaterial(), G4Channeling::UpdateParameters(), G4ParticleChangeForOccurenceBiasing::UpdateStepForAlongStep(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4VParticleChange::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), G4VParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForOccurenceBiasing::UpdateStepForPostStep(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChangeForMSC::UpdateStepForPostStep(), G4ParticleChangeForTransport::UpdateStepForPostStep(), G4ParticleChangeForDecay::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), G4VParticleChange::UpdateStepForPostStep(), G4FastStep::UpdateStepForPostStep(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), ExN04SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), CCalSteppingAction::UserSteppingAction(), RE04SteppingAction::UserSteppingAction(), PHG4RICHSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F05SteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), XrayFluoSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), G4AdjointSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and WLSTrajectoryPoint::WLSTrajectoryPoint().
G4StepPoint* G4Step::GetPreStepPoint () const
Referenced by G4SDChargedFilter::Accept(), G4SDNeutralFilter::Accept(), G4SDKineticEnergyFilter::Accept(), CML2ExpVoxels::add(), HistoManager::AddLeakingParticle(), HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4Transportation::AlongStepDoIt(), G4NuclearStopping::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), XrayFluoAnalysisManager::analyseStepping(), G4RichTrajectory::AppendStep(), RE04Trajectory::AppendStep(), Par01PionShowerModel::AssignSpotAndCallHit(), Par01EMShowerModel::AssignSpotAndCallHit(), G4VReadOutGeometry::CheckROVolume(), G4VMscModel::ComputeGeomLimit(), G4DNABrownianTransportation::ComputeGeomLimit(), G4NIELCalculator::ComputeNIEL(), G4DNABrownianTransportation::ComputeStep(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4VITSteppingVerbose::CopyState(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4AdjointCrossSurfChecker::CrossingASphere(), CCalVOrganization::DetectorLevel(), G4ExceptionHandler::DumpTrackInfo(), G4CellScoreComposer::EstimatorCalculation(), export_G4Step(), PHG4OuterHcalSteppingAction::FieldChecker(), G4DNASmoluchowskiReactionModel::FindReaction(), G4VReadOutGeometry::FindROTouchable(), G4ImportanceProcess::G4ImportanceProcess(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4ScoreSplittingProcess::G4ScoreSplittingProcess(), G4SteppingManager::G4SteppingManager(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), RE02PSEnergyDeposit::GetIndex(), G4PSNofSecondary3D::GetIndex(), RE02PSNofStep::GetIndex(), G4PSNofStep3D::GetIndex(), G4PSTermination3D::GetIndex(), G4PSPopulation3D::GetIndex(), G4PSStepChecker3D::GetIndex(), G4PSEnergyDeposit3D::GetIndex(), G4PSNofCollision3D::GetIndex(), G4PSPassageCellCurrent3D::GetIndex(), RE02PSPassageCellFlux::GetIndex(), G4PSDoseDeposit3D::GetIndex(), G4PSTrackCounter3D::GetIndex(), G4PSCellCharge3D::GetIndex(), G4PSMinKinEAtGeneration3D::GetIndex(), G4PSTrackLength3D::GetIndex(), G4PSPassageTrackLength3D::GetIndex(), G4PSPassageCellFlux3D::GetIndex(), RE02PSCellFlux::GetIndex(), G4VPrimitiveScorer::GetIndex(), CexmcEnergyDepositInCalorimeter::GetIndex(), CexmcTrackPointsInCalorimeter::GetIndex(), RE02PSFlatSurfaceCurrent::GetIndex(), G4PSCellFlux3D::GetIndex(), CexmcEnergyDepositInLeftRightSet::GetIndex(), CexmcTrackPointsInLeftRightSet::GetIndex(), RE02PSFlatSurfaceFlux::GetIndex(), G4PSCylinderSurfaceCurrent3D::GetIndex(), G4PSCylinderSurfaceFlux3D::GetIndex(), G4PSFlatSurfaceCurrent3D::GetIndex(), G4PSFlatSurfaceFlux3D::GetIndex(), G4PSSphereSurfaceCurrent3D::GetIndex(), G4PSSphereSurfaceFlux3D::GetIndex(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4Channeling::GetPre(), G4Scintillation::GetScintillationYieldByParticleType(), CCaloSD::getStepInfo(), CCalEcalOrganization::GetUnitID(), CCalHcalOrganization::GetUnitID(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), G4VGFlashSensitiveDetector::Hit(), G4ITStepProcessor::InitDefineStep(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellCurrent::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), CCalVOrganization::Levels(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), RE06SteppingVerbose::NewStep(), Par01EMShowerModel::Par01EMShowerModel(), Par01PionShowerModel::Par01PionShowerModel(), PrtOpBoundaryProcess::PostStepDoIt(), G4EicDircOpBoundaryProcess::PostStepDoIt(), SplitProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), GB05SD::ProcessHits(), GB06SD::ProcessHits(), GB07SD::ProcessHits(), G4HumanPhantomSD::ProcessHits(), ScreenSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), RE05TrackerSD::ProcessHits(), ExN04MuonSD::ProcessHits(), ExN04TrackerSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), RE05MuonSD::ProcessHits(), HadrontherapyDetectorSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), LXeScintSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), STCyclotronSensitiveTarget::ProcessHits(), B5HodoscopeSD::ProcessHits(), B5DriftChamberSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), B5HadCalorimeterSD::ProcessHits(), XAluminumElectrodeSensitivity::ProcessHits(), RE01TrackerSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), ExGflash2SensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), ExN02TrackerSD::ProcessHits(), G4PSDoseDeposit::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), ExGflash1SensitiveDetector::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSEnergyDeposit::ProcessHits(), G4PSNofCollision::ProcessHits(), G4PSTermination::ProcessHits(), G4PSTrackCounter::ProcessHits(), F02CalorimeterSD::ProcessHits(), ExP01TrackerSD::ProcessHits(), FCALHadModuleSD::ProcessHits(), G4PSPopulation::ProcessHits(), F01CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), G4PSMinKinEAtGeneration::ProcessHits(), FCALEMModuleSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), G4PSPassageCellCurrent::ProcessHits(), B2TrackerSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), DMXScintSD::ProcessHits(), PhantomSD::ProcessHits(), UltraPMTSD::ProcessHits(), G4PSPassageCellFlux::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), G4PSNofSecondary::ProcessHits(), G4PSTrackLength::ProcessHits(), G4PSCellFlux::ProcessHits(), RMC01SD::ProcessHits(), XrayFluoSD::ProcessHits(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CexmcTrackPoints::ProcessHits(), PrimaryKiller::ProcessHits(), ScoreSpecies::ProcessHits(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), G4TransportationLogger::ReportLoopingTrack(), G4ElectronIonPair::SampleIonsAlongStep(), G4VEnergyLossProcess::SampleSubCutSecondaries(), SteppingAction::SetupFlags(), G4ITStepProcessor::SetupMembers(), G4SteppingVerbose::ShowStep(), G4EnergySplitter::SplitEnergyInVolumes(), G4ScoreSplittingProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), G4SteppingManager::Stepping(), PHG4SteppingAction::StoreLocalCoordinate(), G4Channeling::UpdateParameters(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4VParticleChange::UpdateStepForAlongStep(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), ExN04SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), CCalSteppingAction::UserSteppingAction(), FW::Geant4::MMSteppingAction::UserSteppingAction(), RE04SteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), B1SteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), G4MSSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), and G4ParallelWorldScoringProcess::Verbose().
const G4TrackVector* G4Step::GetSecondary () const
Referenced by G4SteppingManager::GetSecondary(), G4ITSteppingVerbose::PostStepVerbose(), and G4ElectronIonPair::ResidualeChargePostStep().
const std::vector< const G4Track * > * G4Step::GetSecondaryInCurrentStep () const
Definition at line 210 of file G4Step.cc.
View newest version in sPHENIX GitHub at line 210 of file G4Step.cc
References fSecondary, nSecondaryByLastStep, and secondaryInCurrentStep.
Referenced by HadrontherapyDetectorSD::ProcessHits(), G4NIELCalculator::RecoilEnergy(), SteppingVerbose::StepInfo(), and OpNoviceSteppingAction::UserSteppingAction().
G4double G4Step::GetStepLength () const
Referenced by HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4ErrorEnergyLoss::AlongStepDoIt(), G4NuclearStopping::AlongStepDoIt(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), G4BiasingProcessInterface::AlongStepDoIt(), G4RayTrajectory::AppendStep(), SteppingAction::BirksAttenuation(), G4NIELCalculator::ComputeNIEL(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4ExceptionHandler::DumpTrackInfo(), G4CellScoreComposer::EstimatorCalculation(), export_G4Step(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4VTransitionRadiation::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4DNABrownianTransportation::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4BiasingProcessInterface::PostStepDoIt(), G4PSNofStep::ProcessHits(), F02CalorimeterSD::ProcessHits(), G4MultiFunctionalDetector::ProcessHits(), F01CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), DMXScintSD::ProcessHits(), G4PSCellFlux::ProcessHits(), G4PSTrackLength::ProcessHits(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4TransportationLogger::ReportLoopingTrack(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4EnergySplitter::SplitEnergyInVolumes(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), G4SteppingManager::Stepping(), F04SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), G4BOptnForceCommonTruncatedExp::UpdateForStep(), PHG4BbcSteppingAction::UserSteppingAction(), FW::Geant4::MMSteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), G4MSSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
G4double G4Step::GetTotalEnergyDeposit () const
Referenced by CML2ExpVoxels::add(), CML2Convergence::add(), HistoManager::AddTargetStep(), G4RichTrajectory::AppendStep(), SteppingAction::BirksAttenuation(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4ExceptionHandler::DumpTrackInfo(), export_G4Step(), G4Scintillation::GetScintillationYieldByParticleType(), CCaloSD::getStepInfo(), PHG4RICHSteppingAction::MakeHit(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), G4ScoreSplittingProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4HumanPhantomSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), RE05TrackerSD::ProcessHits(), ExN04MuonSD::ProcessHits(), ExN04TrackerSD::ProcessHits(), RE05MuonSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), STCyclotronSensitiveTarget::ProcessHits(), B5HodoscopeSD::ProcessHits(), LXeScintSD::ProcessHits(), RE01TrackerSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), B5HadCalorimeterSD::ProcessHits(), RE01CalorimeterSD::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), G4PSDoseDeposit::ProcessHits(), SensitiveDetector::ProcessHits(), ExN02TrackerSD::ProcessHits(), ExGflash1SensitiveDetector::ProcessHits(), ExGflash3SensitiveDetector::ProcessHits(), ExGflash2SensitiveDetector::ProcessHits(), ExGflashSensitiveDetector::ProcessHits(), G4PSEnergyDeposit::ProcessHits(), F02CalorimeterSD::ProcessHits(), ExP01TrackerSD::ProcessHits(), G4MultiFunctionalDetector::ProcessHits(), FCALHadModuleSD::ProcessHits(), F01CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), FCALEMModuleSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), B2TrackerSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), DMXScintSD::ProcessHits(), TargetSD::ProcessHits(), PhantomSD::ProcessHits(), TrackerSD::ProcessHits(), G4MultiSensitiveDetector::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), CCaloSD::ProcessHits(), RMC01SD::ProcessHits(), XrayFluoSD::ProcessHits(), CexmcSimpleEnergyDeposit::ProcessHits(), ScoreSpecies::ProcessHits(), G4SteppingVerbose::ShowStep(), G4EnergySplitter::SplitEnergyInVolumes(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F04SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), CCalSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), B1SteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
G4Track* G4Step::GetTrack () const
Referenced by CexmcTrackPointsFilter::Accept(), G4SDParticleFilter::Accept(), Run::AddEnergy(), HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), XrayFluoAnalysisManager::analyseStepping(), G4RichTrajectory::AppendStep(), G4DecayWithSpin::AtRestDoIt(), SteppingAction::BirksAttenuation(), G4NIELCalculator::ComputeNIEL(), G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), export_G4Step(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), PHG4SteppingAction::GetScintLightYield(), CCaloSD::getStepInfo(), CexmcTrackPoints::GetTrackId(), G4UCNBoundaryProcess::InvokeSD(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellCurrent::IsPassed(), G4PSPassageCellFlux::IsPassed(), PHG4RICHSteppingAction::MakeHit(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), SplitProcess::PostStepDoIt(), GB05SD::ProcessHits(), GB06SD::ProcessHits(), GB07SD::ProcessHits(), ScreenSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), STCyclotronSensitiveTarget::ProcessHits(), ExTGTrackerSD::ProcessHits(), B5DriftChamberSD::ProcessHits(), RE01TrackerSD::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExN02TrackerSD::ProcessHits(), G4PSDoseDeposit::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSTermination::ProcessHits(), ExP01TrackerSD::ProcessHits(), G4PSPopulation::ProcessHits(), G4PSMinKinEAtGeneration::ProcessHits(), B2TrackerSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), DMXScintSD::ProcessHits(), TrackerSD::ProcessHits(), UltraPMTSD::ProcessHits(), CheckVolumeSD::ProcessHits(), G4PSNofSecondary::ProcessHits(), RMC01SD::ProcessHits(), CexmcTrackPoints::ProcessHits(), PrimaryKiller::ProcessHits(), LXePMTSD::ProcessHits_constStep(), WLSPhotonDetSD::ProcessHits_constStep(), G4ElectronIonPair::ResidualeChargePostStep(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4SteppingVerbose::ShowStep(), G4DecayWithSpin::Spin_Precession(), G4EnergySplitter::SplitEnergyInVolumes(), G4ErrorGeomVolumeTarget::TargetReached(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChangeForDecay::UpdateStepForAtRest(), G4ParticleChange::UpdateStepForAtRest(), G4FastStep::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), G4ParticleChange::UpdateStepForPostStep(), G4FastStep::UpdateStepForPostStep(), G4ITReactionChange::UpdateStepInfo(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), ExN04SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), OpNoviceSteppingAction::UserSteppingAction(), RE04SteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), PHG4RICHSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), F05SteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), XrayFluoSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), CexmcSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), XrayTelSteppingAction::UserSteppingAction(), G4AdjointSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
void G4Step::InitializeStep (G4Track * aValue)
Referenced by G4SteppingManager::SetInitialStep(), and G4ITStepProcessor::SetInitialStep().
G4bool G4Step::IsFirstStepInVolume () const
G4bool G4Step::IsLastStepInVolume () const
G4TrackVector* G4Step::NewSecondaryVector ()
Referenced by G4SteppingManager::G4SteppingManager(), and G4ITStepProcessor::InitDefineStep().
G4Step & G4Step::operator= (const G4Step & right)
Definition at line 127 of file G4Step.cc.
View newest version in sPHENIX GitHub at line 127 of file G4Step.cc
References fFirstStepInVolume, fLastStepInVolume, fNonIonizingEnergyDeposit, fpPostStepPoint, fpPreStepPoint, fpSteppingControlFlag, fpTrack, fpVectorOfAuxiliaryPointsPointer, fSecondary, fStepLength, fTotalEnergyDeposit, nSecondaryByLastStep, and secondaryInCurrentStep.
void G4Step::ResetNonIonizingEnergyDeposit ()
void G4Step::ResetTotalEnergyDeposit ()
Referenced by G4ITStepProcessor::InitDefineStep(), and G4SteppingManager::Stepping().
void G4Step::SetControlFlag (G4SteppingControl StepControlFlag)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), and G4VParticleChange::UpdateStepInfo().
void G4Step::SetFirstStepFlag ()
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
void G4Step::SetLastStepFlag ()
Referenced by G4ParticleChangeForTransport::UpdateStepForPostStep(), and G4VParticleChange::UpdateStepInfo().
void G4Step::SetNonIonizingEnergyDeposit (G4double value)
Referenced by G4ParallelWorldProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), and G4ScoreSplittingProcess::PostStepDoIt().
void G4Step::SetPointerToVectorOfAuxiliaryPoints (std::vector< G4ThreeVector > * theNewVectorPointer) inline
Definition at line 237 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 237 of file G4Step.hh
References fpVectorOfAuxiliaryPointsPointer.
Referenced by G4ITStepProcessor::InitDefineStep(), G4SteppingManager::Stepping(), and G4ParticleChangeForTransport::UpdateStepForAlongStep().
void G4Step::SetPostStepPoint (G4StepPoint * value)
void G4Step::SetPreStepPoint (G4StepPoint * value)
void G4Step::SetSecondary (G4TrackVector * value)
Referenced by G4ParallelWorldProcess::CopyStep().
void G4Step::SetStepLength (G4double value)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), G4SteppingManager::InvokeAtRestDoItProcs(), G4ScoreSplittingProcess::PostStepDoIt(), G4SteppingManager::Stepping(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), G4ParticleChangeForGamma::UpdateStepForAtRest(), and G4VParticleChange::UpdateStepInfo().
void G4Step::SetTotalEnergyDeposit (G4double value)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), Par01PionShowerModel::FillFakeStep(), Par01EMShowerModel::FillFakeStep(), and G4ScoreSplittingProcess::PostStepDoIt().
void G4Step::SetTrack (G4Track * value)
Referenced by G4WeightCutOffProcess::CopyStep(), G4ParallelWorldProcess::CopyStep(), G4ImportanceProcess::CopyStep(), G4ParallelWorldScoringProcess::CopyStep(), G4WeightWindowProcess::CopyStep(), G4ScoreSplittingProcess::CopyStepStart(), and G4SteppingManager::Stepping().
void G4Step::UpdateTrack ()
Referenced by G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), and G4SteppingManager::Stepping().
Member Data Documentation
G4bool G4Step::fFirstStepInVolume private
Definition at line 192 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 192 of file G4Step.hh
Referenced by operator=().
G4bool G4Step::fLastStepInVolume private
Definition at line 193 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 193 of file G4Step.hh
Referenced by operator=().
G4double G4Step::fNonIonizingEnergyDeposit protected
Definition at line 172 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 172 of file G4Step.hh
Referenced by operator=().
G4StepPoint* G4Step::fpPostStepPoint private
Definition at line 182 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 182 of file G4Step.hh
Referenced by G4Step(), GetDeltaEnergy(), GetDeltaMomentum(), operator=(), and ~G4Step().
G4StepPoint* G4Step::fpPreStepPoint private
Definition at line 181 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 181 of file G4Step.hh
Referenced by G4Step(), GetDeltaEnergy(), GetDeltaMomentum(), operator=(), and ~G4Step().
G4SteppingControl G4Step::fpSteppingControlFlag private
Definition at line 188 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 188 of file G4Step.hh
Referenced by operator=().
G4Track* G4Step::fpTrack private
Definition at line 186 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 186 of file G4Step.hh
Referenced by operator=().
std::vector<G4ThreeVector>* G4Step::fpVectorOfAuxiliaryPointsPointer private
Definition at line 249 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 249 of file G4Step.hh
Referenced by GetPointerToVectorOfAuxiliaryPoints(), operator=(), and SetPointerToVectorOfAuxiliaryPoints().
G4TrackVector* G4Step::fSecondary private
Definition at line 223 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Step.hh
Referenced by G4Step(), GetSecondaryInCurrentStep(), operator=(), and ~G4Step().
G4double G4Step::fStepLength private
Definition at line 183 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 183 of file G4Step.hh
Referenced by operator=().
G4double G4Step::fTotalEnergyDeposit protected
Definition at line 169 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 169 of file G4Step.hh
Referenced by operator=().
size_t G4Step::nSecondaryByLastStep private
Definition at line 226 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 226 of file G4Step.hh
Referenced by GetSecondaryInCurrentStep(), and operator=().
std::vector<CT>* G4Step::secondaryInCurrentStep private
Definition at line 229 of file G4Step.hh.
View newest version in sPHENIX GitHub at line 229 of file G4Step.hh
Referenced by G4Step(), GetSecondaryInCurrentStep(), operator=(), and ~G4Step().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4Step.hh
geant4/tree/geant4-10.6-release/source/track/src/G4Step.cc