ECCE @ EIC Software: macros/blob/master/common/G4_mRwell_EIC.C File Reference
G4_mRwell_EIC.C File Reference
#include <GlobalVariables.C>
#include <fun4all/Fun4AllServer.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
Namespaces
namespace Enable
namespace RWELL
Macros
#define MACRO_G4mRWELL_C
Functions
void RWellInit (int verbosity=0)
double Build_G4_RWell_Bare (PHG4Reco *g4Reco, double rwellrad=80.0, double driftgap=1.83, double length=200.0, int index=0)
double Build_G4_RWell_Sup01 (PHG4Reco *g4Reco, double rwellrad=80.0, double driftgap=1.5, double length=200.0, int index=0)
double RWellSetup (PHG4Reco *g4Reco, int type=1)
type selects the RWell material
void RWell_Cells (int verbosity=0)
void RWell_Reco (int verbosity=0)
Variables
bool Enable::RWELL = false
bool Enable::RWELL_OVERLAPCHECK = false
const int RWELL::n_layer = 2
const double RWELL::nom_radius [RWELL::n_layer] = {51., 77.0175}
double RWELL::e_length_uRwell [RWELL::n_layer] = {106., 197}
double RWELL::h_length_uRwell [RWELL::n_layer] = { e_length_uRwell[0], 145}
const double RWELL::nom_driftgap [RWELL::n_layer] = {0.4, 0.4}
const double RWELL::nom_length [RWELL::n_layer] = {2*e_length_uRwell[0], 342.0}
int RWELL::subsysID = 0
Macro Definition Documentation
#define MACRO_G4mRWELL_C
Definition at line 2 of file G4_mRwell_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_mRwell_EIC.C
Function Documentation
double Build_G4_RWell_Bare (PHG4Reco * g4Reco, double rwellrad = 80.0, double driftgap = 1.83, double length = 200.0, int index = 0)
Definition at line 58 of file G4_mRwell_EIC.C.
View newest version in sPHENIX GitHub at line 58 of file G4_mRwell_EIC.C
References RWELL::e_length_uRwell, RWELL::h_length_uRwell, BTOF::length, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), Enable::RWELL_OVERLAPCHECK, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), RWELL::subsysID, and PHG4DetectorSubsystem::SuperDetector().
Referenced by RWellSetup().
double Build_G4_RWell_Sup01 (PHG4Reco * g4Reco, double rwellrad = 80.0, double driftgap = 1.5, double length = 200.0, int index = 0)
Definition at line 172 of file G4_mRwell_EIC.C.
View newest version in sPHENIX GitHub at line 172 of file G4_mRwell_EIC.C
References RWELL::e_length_uRwell, RWELL::h_length_uRwell, BTOF::length, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), Enable::RWELL_OVERLAPCHECK, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), RWELL::subsysID, and PHG4DetectorSubsystem::SuperDetector().
Referenced by RWellSetup().
void RWell_Cells (int verbosity = 0)
Definition at line 442 of file G4_mRwell_EIC.C.
View newest version in sPHENIX GitHub at line 442 of file G4_mRwell_EIC.C
References Fun4AllServer::instance().
void RWell_Reco (int verbosity = 0)
Definition at line 467 of file G4_mRwell_EIC.C.
View newest version in sPHENIX GitHub at line 467 of file G4_mRwell_EIC.C
References Fun4AllServer::instance().
void RWellInit (int verbosity = 0)
Definition at line 51 of file G4_mRwell_EIC.C.
View newest version in sPHENIX GitHub at line 51 of file G4_mRwell_EIC.C
References max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, RWELL::n_layer, RWELL::nom_length, and RWELL::nom_radius.
Referenced by G4Init().
double RWellSetup (PHG4Reco * g4Reco, int type = 1)
type selects the RWell material
Definition at line 379 of file G4_mRwell_EIC.C.
View newest version in sPHENIX GitHub at line 379 of file G4_mRwell_EIC.C
References PHG4TrackFastSim::add_cylinder_state(), PHG4TrackFastSim::add_phg4hits(), Build_G4_RWell_Bare(), Build_G4_RWell_Sup01(), PHG4TrackFastSim::Cylinder, e, TRACKING::FastKalmanFilter(), TRACKING::FastKalmanFilterInnerTrack(), TRACKING::FastKalmanFilterSiliconTrack(), RWELL::n_layer, RWELL::nom_driftgap, RWELL::nom_length, RWELL::nom_radius, TRACKING::ProjectionNames, and radius.
Referenced by G4Setup().