ECCE @ EIC Software: G4RDAtomicTransitionManager Class Reference
G4RDAtomicTransitionManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDAtomicTransitionManager.hh>
Public Member Functions
G4RDAtomicShell * Shell (G4int Z, size_t shellIndex) const
const G4RDFluoTransition * ReachableShell (G4int Z, size_t shellIndex) const
const G4RDAugerTransition * ReachableAugerShell (G4int Z, G4int shellIndex) const
G4int NumberOfShells (G4int Z) const
G4int NumberOfReachableShells (G4int Z) const
G4int NumberOfReachableAugerShells (G4int Z) const
G4double TotalRadiativeTransitionProbability (G4int Z, size_t shellIndex)
G4double TotalNonRadiativeTransitionProbability (G4int Z, size_t shellIndex)
Static Public Member Functions
static
G4RDAtomicTransitionManager * Instance ()
Protected Member Functions
G4RDAtomicTransitionManager (G4int minZ=1, G4int maxZ=100, G4int limitInfTable=6, G4int limitSupTable=100)
~G4RDAtomicTransitionManager ()
Private Member Functions
G4RDAtomicTransitionManager & operator= (const G4RDAtomicTransitionManager &right)
G4RDAtomicTransitionManager (const G4RDAtomicTransitionManager &)
Private Attributes
std::map< G4int, std::vector
< G4RDAtomicShell * >
, std::less< G4int > > shellTable
std::map< G4int, std::vector
< G4RDFluoTransition * >
, std::less< G4int > > transitionTable
G4RDAugerData * augerData
G4int zMin
G4int zMax
G4int infTableLimit
G4int supTableLimit
Static Private Attributes
static
G4RDAtomicTransitionManager * instance = 0
Detailed Description
Definition at line 59 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 59 of file G4RDAtomicTransitionManager.hh
Constructor & Destructor Documentation
G4RDAtomicTransitionManager::G4RDAtomicTransitionManager (G4int minZ = 1, G4int maxZ = 100, G4int limitInfTable = 6, G4int limitSupTable = 100) protected
Definition at line 39 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 39 of file G4RDAtomicTransitionManager.cc
References augerData, G4InuclSpecialFunctions::bindingEnergy(), G4RDShellData::BindingEnergy(), infTableLimit, G4RDShellData::LoadData(), G4RDFluoData::LoadData(), G4RDShellData::NumberOfShells(), G4RDFluoData::NumberOfTransitions(), G4RDShellData::ShellId(), shellTable, G4RDFluoData::StartShellEnergy(), G4RDFluoData::StartShellId(), G4RDFluoData::StartShellProb(), supTableLimit, transitionTable, G4RDFluoData::VacancyId(), Z, zMax, and zMin.
Referenced by Instance().
G4RDAtomicTransitionManager::~G4RDAtomicTransitionManager () protected
Definition at line 121 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 121 of file G4RDAtomicTransitionManager.cc
References augerData, pos(), shellTable, and transitionTable.
G4RDAtomicTransitionManager::G4RDAtomicTransitionManager (const G4RDAtomicTransitionManager &) private
Member Function Documentation
G4RDAtomicTransitionManager * G4RDAtomicTransitionManager::Instance (void) static
Definition at line 161 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 161 of file G4RDAtomicTransitionManager.cc
References G4RDAtomicTransitionManager(), and instance.
Referenced by G4RDeIonisationSpectrum::AverageEnergy(), G4LowEnergyIonisation::BuildLossTable(), G4LowEnergyIonisation::DeexciteAtom(), G4RDAtomicDeexcitation::GenerateAuger(), G4RDAtomicDeexcitation::GenerateFluorescence(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4RDeIonisationSpectrum::Probability(), G4RDeIonisationSpectrum::SampleEnergy(), and G4RDAtomicDeexcitation::SelectTypeOfTransition().
G4int G4RDAtomicTransitionManager::NumberOfReachableAugerShells (G4int Z) const
Definition at line 296 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 296 of file G4RDAtomicTransitionManager.cc
References augerData, n, and G4RDAugerData::NumberOfVacancies().
Referenced by G4RDAtomicDeexcitation::GenerateAuger().
G4int G4RDAtomicTransitionManager::NumberOfReachableShells (G4int Z) const
Definition at line 272 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 272 of file G4RDAtomicTransitionManager.cc
References G4cout, G4endl, pos(), transitionTable, and v.
Referenced by G4RDAtomicDeexcitation::GenerateFluorescence(), and G4RDAtomicDeexcitation::SelectTypeOfTransition().
G4int G4RDAtomicTransitionManager::NumberOfShells (G4int Z) const
Definition at line 246 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 246 of file G4RDAtomicTransitionManager.cc
References G4cout, G4endl, pos(), shellTable, and v.
Referenced by G4LowEnergyIonisation::BuildLossTable().
G4RDAtomicTransitionManager& G4RDAtomicTransitionManager::operator= (const G4RDAtomicTransitionManager & right) private
const G4RDAugerTransition * G4RDAtomicTransitionManager::ReachableAugerShell (G4int Z, G4int shellIndex) const
Definition at line 237 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 237 of file G4RDAtomicTransitionManager.cc
References augerData, and G4RDAugerData::GetAugerTransition().
Referenced by G4RDAtomicDeexcitation::GenerateAuger().
const G4RDFluoTransition * G4RDAtomicTransitionManager::ReachableShell (G4int Z, size_t shellIndex) const
Definition at line 213 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 213 of file G4RDAtomicTransitionManager.cc
References FatalException, G4cout, G4endl, G4Exception(), pos(), transitionTable, and v.
Referenced by G4RDAtomicDeexcitation::SelectTypeOfTransition().
G4RDAtomicShell * G4RDAtomicTransitionManager::Shell (G4int Z, size_t shellIndex) const
Definition at line 172 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 172 of file G4RDAtomicTransitionManager.cc
References FatalException, G4cout, G4endl, G4Exception(), pos(), shellTable, and v.
Referenced by G4LowEnergyIonisation::DeexciteAtom(), and G4LowEnergyPhotoElectric::PostStepDoIt().
G4double G4RDAtomicTransitionManager::TotalNonRadiativeTransitionProbability (G4int Z, size_t shellIndex)
Definition at line 346 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 346 of file G4RDAtomicTransitionManager.cc
References FatalException, G4cout, G4endl, G4Exception(), pos(), G4RDFluoTransition::TransitionProbabilities(), transitionTable, and v.
G4double G4RDAtomicTransitionManager::TotalRadiativeTransitionProbability (G4int Z, size_t shellIndex)
Definition at line 304 of file G4RDAtomicTransitionManager.cc.
View newest version in sPHENIX GitHub at line 304 of file G4RDAtomicTransitionManager.cc
References FatalException, G4cout, G4endl, G4Exception(), pos(), G4RDFluoTransition::TransitionProbabilities(), transitionTable, and v.
Member Data Documentation
G4RDAugerData* G4RDAtomicTransitionManager::augerData private
Definition at line 132 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 132 of file G4RDAtomicTransitionManager.hh
Referenced by G4RDAtomicTransitionManager(), NumberOfReachableAugerShells(), ReachableAugerShell(), and ~G4RDAtomicTransitionManager().
G4int G4RDAtomicTransitionManager::infTableLimit private
Definition at line 141 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 141 of file G4RDAtomicTransitionManager.hh
Referenced by G4RDAtomicTransitionManager().
G4RDAtomicTransitionManager * G4RDAtomicTransitionManager::instance = 0 static private
Definition at line 120 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4RDAtomicTransitionManager.hh
Referenced by Instance().
std::map<G4int,std::vector<G4RDAtomicShell*>,std::less<G4int> > G4RDAtomicTransitionManager::shellTable private
Definition at line 124 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4RDAtomicTransitionManager.hh
Referenced by G4RDAtomicTransitionManager(), NumberOfShells(), Shell(), and ~G4RDAtomicTransitionManager().
G4int G4RDAtomicTransitionManager::supTableLimit private
Definition at line 142 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 142 of file G4RDAtomicTransitionManager.hh
Referenced by G4RDAtomicTransitionManager().
std::map<G4int,std::vector<G4RDFluoTransition*>,std::less<G4int> > G4RDAtomicTransitionManager::transitionTable private
Definition at line 128 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 128 of file G4RDAtomicTransitionManager.hh
Referenced by G4RDAtomicTransitionManager(), NumberOfReachableShells(), ReachableShell(), TotalNonRadiativeTransitionProbability(), TotalRadiativeTransitionProbability(), and ~G4RDAtomicTransitionManager().
G4int G4RDAtomicTransitionManager::zMax private
Definition at line 137 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 137 of file G4RDAtomicTransitionManager.hh
Referenced by G4RDAtomicTransitionManager().
G4int G4RDAtomicTransitionManager::zMin private
Definition at line 136 of file G4RDAtomicTransitionManager.hh.
View newest version in sPHENIX GitHub at line 136 of file G4RDAtomicTransitionManager.hh
Referenced by G4RDAtomicTransitionManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDAtomicTransitionManager.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDAtomicTransitionManager.cc