ECCE @ EIC Software: GammaRayTelPrimaryGeneratorAction Class Reference
GammaRayTelPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelPrimaryGeneratorAction.hh>
Public Member Functions
GammaRayTelPrimaryGeneratorAction ()
~GammaRayTelPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *)
void SetRndmFlag (G4String val)
void SetSourceType (G4int val)
void SetSpectrumType (G4int val)
void SetVertexRadius (G4double val)
void SetSourceGen (G4bool val)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4ParticleGun * particleGun
G4GeneralParticleSource * particleSource
const
GammaRayTelDetectorConstruction * GammaRayTelDetector
GammaRayTelPrimaryGeneratorMessenger * gunMessenger
G4String rndmFlag
G4int nSourceType
G4double dVertexRadius
G4int nSpectrumType
G4bool sourceGun
Detailed Description
Definition at line 57 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file GammaRayTelPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
GammaRayTelPrimaryGeneratorAction::GammaRayTelPrimaryGeneratorAction ()
Definition at line 57 of file GammaRayTelPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 57 of file GammaRayTelPrimaryGeneratorAction.cc
References cm, dVertexRadius, G4ParticleTable::FindParticle(), GammaRayTelDetector, G4ParticleTable::GetParticleTable(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), GammaRayTelDetectorConstruction::GetWorldSizeZ(), gunMessenger, MeV, nSourceType, nSpectrumType, particle, particleGun, particleSource, rndmFlag, G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), and sourceGun.
GammaRayTelPrimaryGeneratorAction::~GammaRayTelPrimaryGeneratorAction ()
Definition at line 93 of file GammaRayTelPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 93 of file GammaRayTelPrimaryGeneratorAction.cc
References gunMessenger, particleGun, and particleSource.
Member Function Documentation
void GammaRayTelPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 103 of file GammaRayTelPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 103 of file GammaRayTelPrimaryGeneratorAction.cc
References cm, CLHEP::Hep3Vector::dot(), dVertexRadius, f, G4cout, G4endl, G4UniformRand, GammaRayTelDetector, G4ParticleGun::GeneratePrimaryVertex(), G4GeneralParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), G4ParticleGun::GetParticleMomentumDirection(), G4ParticleDefinition::GetParticleName(), GammaRayTelDetectorConstruction::GetWorldSizeXY(), GammaRayTelDetectorConstruction::GetWorldSizeZ(), GeV, halfpi, CLHEP::Hep3Vector::mag(), MeV, nSourceType, nSpectrumType, particleGun, particleSource, CLHEP::Hep3Vector::phi(), phi, pi, CLHEP::Hep3Vector::rotate(), CLHEP::Hep3Vector::setMag(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), CLHEP::Hep3Vector::setPhi(), CLHEP::Hep3Vector::setTheta(), sourceGun, CLHEP::Hep3Vector::theta(), theta(), twopi, y, z, and G4InuclParticleNames::z0.
void GammaRayTelPrimaryGeneratorAction::SetRndmFlag (G4String val) inline
Definition at line 66 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 66 of file GammaRayTelPrimaryGeneratorAction.hh
References rndmFlag.
Referenced by GammaRayTelPrimaryGeneratorMessenger::SetNewValue().
void GammaRayTelPrimaryGeneratorAction::SetSourceGen (G4bool val) inline
Definition at line 70 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 70 of file GammaRayTelPrimaryGeneratorAction.hh
References sourceGun.
Referenced by GammaRayTelPrimaryGeneratorMessenger::SetNewValue().
void GammaRayTelPrimaryGeneratorAction::SetSourceType (G4int val) inline
Definition at line 67 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 67 of file GammaRayTelPrimaryGeneratorAction.hh
References nSourceType.
Referenced by GammaRayTelPrimaryGeneratorMessenger::SetNewValue().
void GammaRayTelPrimaryGeneratorAction::SetSpectrumType (G4int val) inline
Definition at line 68 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 68 of file GammaRayTelPrimaryGeneratorAction.hh
References nSpectrumType.
Referenced by GammaRayTelPrimaryGeneratorMessenger::SetNewValue().
void GammaRayTelPrimaryGeneratorAction::SetVertexRadius (G4double val) inline
Definition at line 69 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 69 of file GammaRayTelPrimaryGeneratorAction.hh
References dVertexRadius.
Referenced by GammaRayTelPrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
G4double GammaRayTelPrimaryGeneratorAction::dVertexRadius private
Definition at line 79 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 79 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), GeneratePrimaries(), and SetVertexRadius().
const GammaRayTelDetectorConstruction* GammaRayTelPrimaryGeneratorAction::GammaRayTelDetector private
Definition at line 75 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 75 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), and GeneratePrimaries().
GammaRayTelPrimaryGeneratorMessenger* GammaRayTelPrimaryGeneratorAction::gunMessenger private
Definition at line 76 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 76 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), and ~GammaRayTelPrimaryGeneratorAction().
G4int GammaRayTelPrimaryGeneratorAction::nSourceType private
Definition at line 78 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 78 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), GeneratePrimaries(), and SetSourceType().
G4int GammaRayTelPrimaryGeneratorAction::nSpectrumType private
Definition at line 80 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 80 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), GeneratePrimaries(), and SetSpectrumType().
G4ParticleGun* GammaRayTelPrimaryGeneratorAction::particleGun private
Definition at line 73 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 73 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), GeneratePrimaries(), and ~GammaRayTelPrimaryGeneratorAction().
G4GeneralParticleSource* GammaRayTelPrimaryGeneratorAction::particleSource private
Definition at line 74 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 74 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), GeneratePrimaries(), and ~GammaRayTelPrimaryGeneratorAction().
G4String GammaRayTelPrimaryGeneratorAction::rndmFlag private
Definition at line 77 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 77 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), and SetRndmFlag().
G4bool GammaRayTelPrimaryGeneratorAction::sourceGun private
Definition at line 81 of file GammaRayTelPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 81 of file GammaRayTelPrimaryGeneratorAction.hh
Referenced by GammaRayTelPrimaryGeneratorAction(), GeneratePrimaries(), and SetSourceGen().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelPrimaryGeneratorAction.cc