ECCE @ EIC Software: G4UCNMicroRoughnessHelper Class Reference
G4UCNMicroRoughnessHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4UCNMicroRoughnessHelper.hh>
Public Member Functions
G4double S2 (G4double, G4double) const
G4double SS2 (G4double, G4double) const
G4double Fmu (G4double, G4double, G4double, G4double, G4double, G4double, G4double) const
G4double FmuS (G4double, G4double, G4double, G4double, G4double, G4double, G4double, G4double, G4double) const
G4double IntIplus (G4double, G4double, G4double, G4int, G4int, G4double, G4double, G4double *, G4double) const
G4double ProbIplus (G4double, G4double, G4double, G4double, G4double, G4double, G4double, G4double) const
G4double IntIminus (G4double, G4double, G4double, G4int, G4int, G4double, G4double, G4double *, G4double) const
G4double ProbIminus (G4double, G4double, G4double, G4double, G4double, G4double, G4double, G4double) const
Static Public Member Functions
static G4UCNMicroRoughnessHelper * GetInstance ()
Protected Member Functions
G4UCNMicroRoughnessHelper ()
~G4UCNMicroRoughnessHelper ()
Static Private Attributes
static G4UCNMicroRoughnessHelper * fpInstance = nullptr
Detailed Description
Definition at line 60 of file G4UCNMicroRoughnessHelper.hh.
View newest version in sPHENIX GitHub at line 60 of file G4UCNMicroRoughnessHelper.hh
Constructor & Destructor Documentation
G4UCNMicroRoughnessHelper::G4UCNMicroRoughnessHelper () protected
Definition at line 53 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 53 of file G4UCNMicroRoughnessHelper.cc
Referenced by GetInstance().
G4UCNMicroRoughnessHelper::~G4UCNMicroRoughnessHelper () protected
Definition at line 57 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 57 of file G4UCNMicroRoughnessHelper.cc
References fpInstance.
Member Function Documentation
G4double G4UCNMicroRoughnessHelper::Fmu (G4double k2, G4double thetai, G4double thetao, G4double phio, G4double b2, G4double w2, G4double AngCut) const
Definition at line 98 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 98 of file G4UCNMicroRoughnessHelper.cc
References twopi.
Referenced by IntIplus(), and ProbIplus().
G4double G4UCNMicroRoughnessHelper::FmuS (G4double k, G4double kS, G4double thetai, G4double thetaSo, G4double phiSo, G4double b2, G4double w2, G4double AngCut, G4double thetarefract) const
Definition at line 128 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 128 of file G4UCNMicroRoughnessHelper.cc
References twopi.
Referenced by IntIminus(), and ProbIminus().
G4UCNMicroRoughnessHelper * G4UCNMicroRoughnessHelper::GetInstance (void) static
Definition at line 65 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 65 of file G4UCNMicroRoughnessHelper.cc
References fpInstance, and G4UCNMicroRoughnessHelper().
Referenced by G4UCNMaterialPropertiesTable::ComputeMicroRoughnessTables(), G4UCNMaterialPropertiesTable::GetMRProbability(), and G4UCNMaterialPropertiesTable::GetMRTransProbability().
G4double G4UCNMicroRoughnessHelper::IntIminus (G4double E, G4double fermipot, G4double theta_i, G4int AngNoTheta, G4int AngNoPhi, G4double b2, G4double w2, G4double * max, G4double AngCut) const
Definition at line 283 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 283 of file G4UCNMicroRoughnessHelper.cc
References degree, E, e, eV, FmuS(), source.hepunit::hbarc_squared, k, ksdk(), source.hepunit::neutron_mass_c2, S2(), and SS2().
G4double G4UCNMicroRoughnessHelper::IntIplus (G4double E, G4double fermipot, G4double theta_i, G4int AngNoTheta, G4int AngNoPhi, G4double b2, G4double w2, G4double * max, G4double AngCut) const
Definition at line 159 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 159 of file G4UCNMicroRoughnessHelper.cc
References degree, E, e, eV, Fmu(), source.hepunit::hbarc_squared, k2, source.hepunit::neutron_mass_c2, and S2().
G4double G4UCNMicroRoughnessHelper::ProbIminus (G4double E, G4double fermipot, G4double theta_i, G4double thetas_o, G4double phis_o, G4double b, G4double w, G4double AngCut) const
Definition at line 431 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 431 of file G4UCNMicroRoughnessHelper.cc
References E, FmuS(), G4cout, G4endl, source.hepunit::hbarc_squared, k, ksdk(), source.hepunit::neutron_mass_c2, S2(), and SS2().
G4double G4UCNMicroRoughnessHelper::ProbIplus (G4double E, G4double fermipot, G4double theta_i, G4double theta_o, G4double phi_o, G4double b, G4double w, G4double AngCut) const
Definition at line 404 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 404 of file G4UCNMicroRoughnessHelper.cc
References E, Fmu(), source.hepunit::hbarc_squared, source.hepunit::neutron_mass_c2, and S2().
G4double G4UCNMicroRoughnessHelper::S2 (G4double costheta2, G4double klk2) const
Definition at line 74 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 74 of file G4UCNMicroRoughnessHelper.cc
References norm.
Referenced by IntIminus(), IntIplus(), ProbIminus(), and ProbIplus().
G4double G4UCNMicroRoughnessHelper::SS2 (G4double costhetas2, G4double klks2) const
Definition at line 88 of file G4UCNMicroRoughnessHelper.cc.
View newest version in sPHENIX GitHub at line 88 of file G4UCNMicroRoughnessHelper.cc
Referenced by IntIminus(), and ProbIminus().
Member Data Documentation
G4UCNMicroRoughnessHelper * G4UCNMicroRoughnessHelper::fpInstance = nullptr static private
Definition at line 184 of file G4UCNMicroRoughnessHelper.hh.
View newest version in sPHENIX GitHub at line 184 of file G4UCNMicroRoughnessHelper.hh
Referenced by GetInstance(), and ~G4UCNMicroRoughnessHelper().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4UCNMicroRoughnessHelper.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4UCNMicroRoughnessHelper.cc