ECCE @ EIC Software: G4PDefManager Class Reference
G4PDefManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4PDefManager.hh>
Public Member Functions
G4PDefManager ()
G4int CreateSubInstance ()
void NewSubInstances ()
void FreeSlave ()
G4PDefData * GetOffset ()
void UseWorkArea (G4PDefData *newOffset)
G4PDefData * FreeWorkArea ()
Static Public Member Functions
static G4PART_DLL G4int & slavetotalspace ()
static G4PART_DLL G4PDefData *& offset ()
Private Attributes
G4int totalobj
G4Mutex mutex
Detailed Description
Definition at line 86 of file G4PDefManager.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PDefManager.hh
Constructor & Destructor Documentation
G4PDefManager::G4PDefManager ()
Definition at line 67 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PDefManager.cc
References G4MUTEXINIT.
Member Function Documentation
G4int G4PDefManager::CreateSubInstance ()
Definition at line 72 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4PDefManager.cc
References G4TemplateAutoLock< _Mutex_t >::lock(), NewSubInstances(), slavetotalspace(), totalobj, and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by G4ParticleDefinition::SetParticleDefinitionID().
void G4PDefManager::FreeSlave ()
Definition at line 111 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 111 of file G4PDefManager.cc
References offset().
Referenced by G4ParticleDefinition::Clean(), and G4ParticlesWorkspace::DestroyWorkspace().
G4PDefData * G4PDefManager::FreeWorkArea ()
Definition at line 136 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 136 of file G4PDefManager.cc
References offset().
G4PDefData * G4PDefManager::GetOffset ()
Definition at line 119 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 119 of file G4PDefManager.cc
References offset().
Referenced by G4ParticlesWorkspace::G4ParticlesWorkspace().
void G4PDefManager::NewSubInstances ()
Definition at line 88 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 88 of file G4PDefManager.cc
References FatalException, G4Exception(), G4PDefData::initialize(), offset(), slavetotalspace(), and totalobj.
Referenced by CreateSubInstance(), and G4ParticlesWorkspace::InitialiseWorkspace().
G4PDefData *& G4PDefManager::offset () static
Definition at line 61 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 61 of file G4PDefManager.cc
References G4ThreadLocalStatic.
Referenced by FreeSlave(), FreeWorkArea(), GetOffset(), NewSubInstances(), and UseWorkArea().
G4int & G4PDefManager::slavetotalspace () static
Definition at line 55 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 55 of file G4PDefManager.cc
References G4ThreadLocalStatic.
Referenced by CreateSubInstance(), NewSubInstances(), and G4VUserPhysicsList::RemoveProcessManager().
void G4PDefManager::UseWorkArea (G4PDefData * newOffset)
Definition at line 124 of file G4PDefManager.cc.
View newest version in sPHENIX GitHub at line 124 of file G4PDefManager.cc
References FatalException, G4Exception(), and offset().
Referenced by G4ParticlesWorkspace::ReleaseWorkspace(), and G4ParticlesWorkspace::UseWorkspace().
Member Data Documentation
G4Mutex G4PDefManager::mutex private
Definition at line 119 of file G4PDefManager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4PDefManager.hh
G4int G4PDefManager::totalobj private
Definition at line 118 of file G4PDefManager.hh.
View newest version in sPHENIX GitHub at line 118 of file G4PDefManager.hh
Referenced by CreateSubInstance(), and NewSubInstances().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4PDefManager.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4PDefManager.cc