ECCE @ EIC Software: G4ParticlePropertyMessenger Class Reference
G4ParticlePropertyMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticlePropertyMessenger.hh>
Public Member Functions
G4ParticlePropertyMessenger (G4ParticleTable *pTable=0)
virtual ~G4ParticlePropertyMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
virtual G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4ParticlePropertyMessenger (const G4ParticlePropertyMessenger &)
G4ParticleDefinition * SetCurrentParticle ()
Private Attributes
G4ParticleTable * theParticleTable
G4ParticleDefinition * currentParticle
G4UIdirectory * thisDirectory
G4UIcmdWithoutParameter * dumpCmd
G4UIcmdWithABool * stableCmd
G4UIcmdWithAnInteger * verboseCmd
G4UIcmdWithADoubleAndUnit * lifetimeCmd
G4DecayTableMessenger * fDecayTableMessenger
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 68 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticlePropertyMessenger.hh
Constructor & Destructor Documentation
G4ParticlePropertyMessenger::G4ParticlePropertyMessenger (G4ParticleTable * pTable = 0)
Definition at line 58 of file G4ParticlePropertyMessenger.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ParticlePropertyMessenger.cc
References G4UIcommand::AvailableForStates(), dumpCmd, fDecayTableMessenger, G4State_GeomClosed, G4State_Idle, G4State_PreInit, G4ParticleTable::GetParticleTable(), lifetimeCmd, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), stableCmd, theParticleTable, thisDirectory, and verboseCmd.
G4ParticlePropertyMessenger::~G4ParticlePropertyMessenger () virtual
Definition at line 107 of file G4ParticlePropertyMessenger.cc.
View newest version in sPHENIX GitHub at line 107 of file G4ParticlePropertyMessenger.cc
References dumpCmd, fDecayTableMessenger, lifetimeCmd, stableCmd, thisDirectory, and verboseCmd.
G4ParticlePropertyMessenger::G4ParticlePropertyMessenger (const G4ParticlePropertyMessenger &) inline private
Definition at line 79 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticlePropertyMessenger.hh
Member Function Documentation
G4String G4ParticlePropertyMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 169 of file G4ParticlePropertyMessenger.cc.
View newest version in sPHENIX GitHub at line 169 of file G4ParticlePropertyMessenger.cc
References G4UIcommand::ConvertToString(), currentParticle, G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGStable(), lifetimeCmd, SetCurrentParticle(), stableCmd, and verboseCmd.
G4ParticleDefinition * G4ParticlePropertyMessenger::SetCurrentParticle () private
Definition at line 150 of file G4ParticlePropertyMessenger.cc.
View newest version in sPHENIX GitHub at line 150 of file G4ParticlePropertyMessenger.cc
References currentParticle, G4ParticleTable::FindParticle(), G4UImanager::GetCurrentStringValue(), G4ParticleDefinition::GetParticleName(), G4UImanager::GetUIpointer(), and theParticleTable.
Referenced by GetCurrentValue(), and SetNewValue().
void G4ParticlePropertyMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 119 of file G4ParticlePropertyMessenger.cc.
View newest version in sPHENIX GitHub at line 119 of file G4ParticlePropertyMessenger.cc
References currentParticle, dumpCmd, G4ParticleDefinition::DumpTable(), G4cout, G4endl, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMass(), lifetimeCmd, SetCurrentParticle(), G4ParticleDefinition::SetPDGLifeTime(), G4ParticleDefinition::SetPDGStable(), G4ParticleDefinition::SetVerboseLevel(), stableCmd, and verboseCmd.
Member Data Documentation
G4ParticleDefinition* G4ParticlePropertyMessenger::currentParticle private
Definition at line 84 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticlePropertyMessenger.hh
Referenced by GetCurrentValue(), SetCurrentParticle(), and SetNewValue().
G4UIcmdWithoutParameter* G4ParticlePropertyMessenger::dumpCmd private
Definition at line 87 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticlePropertyMessenger.hh
Referenced by G4ParticlePropertyMessenger(), SetNewValue(), and ~G4ParticlePropertyMessenger().
G4DecayTableMessenger* G4ParticlePropertyMessenger::fDecayTableMessenger private
Definition at line 92 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticlePropertyMessenger.hh
Referenced by G4ParticlePropertyMessenger(), and ~G4ParticlePropertyMessenger().
G4UIcmdWithADoubleAndUnit* G4ParticlePropertyMessenger::lifetimeCmd private
Definition at line 90 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ParticlePropertyMessenger.hh
Referenced by G4ParticlePropertyMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticlePropertyMessenger().
G4UIcmdWithABool* G4ParticlePropertyMessenger::stableCmd private
Definition at line 88 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticlePropertyMessenger.hh
Referenced by G4ParticlePropertyMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticlePropertyMessenger().
G4ParticleTable* G4ParticlePropertyMessenger::theParticleTable private
Definition at line 83 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticlePropertyMessenger.hh
Referenced by G4ParticlePropertyMessenger(), and SetCurrentParticle().
G4UIdirectory* G4ParticlePropertyMessenger::thisDirectory private
Definition at line 86 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticlePropertyMessenger.hh
Referenced by G4ParticlePropertyMessenger(), and ~G4ParticlePropertyMessenger().
G4UIcmdWithAnInteger* G4ParticlePropertyMessenger::verboseCmd private
Definition at line 89 of file G4ParticlePropertyMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticlePropertyMessenger.hh
Referenced by G4ParticlePropertyMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticlePropertyMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticlePropertyMessenger.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4ParticlePropertyMessenger.cc