ECCE @ EIC Software: G4tgrVolumeMgr Class Reference
G4tgrVolumeMgr Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrVolumeMgr.hh>
Public Member Functions
G4tgrSolid * CreateSolid (const std::vector< G4String > &wl, G4bool bVOLUtag)
void RegisterParentChild (const G4String &parentName, const G4tgrPlace *pl)
G4tgrSolid * FindSolid (const G4String &name, G4bool exists=false)
G4tgrVolume * FindVolume (const G4String &volname, G4bool exists=false)
std::vector< G4tgrVolume * > FindVolumes (const G4String &volname, G4bool exists)
const G4tgrVolume * GetTopVolume ()
std::pair< G4mmapspl::iterator,
G4mmapspl::iterator > GetChildren (const G4String &name)
void DumpSummary ()
void DumpVolumeTree ()
void DumpVolumeLeaf (const G4tgrVolume *vol, unsigned int copyNo, unsigned int leafDepth)
void RegisterMe (G4tgrSolid *vol)
void UnRegisterMe (G4tgrSolid *vol)
void RegisterMe (G4tgrVolume *vol)
void UnRegisterMe (G4tgrVolume *vol)
void RegisterMe (G4tgrPlace *pl)
void RegisterMe (G4tgrIsotope *iso)
void RegisterMe (G4tgrElement *ele)
void RegisterMe (G4tgrMaterial *mat)
void RegisterMe (G4tgrRotationMatrix *rm)
const G4mapssol & GetSolidMap ()
const G4mapsvol & GetVolumeMap ()
const G4mmapspl & GetVolumeTree ()
std::vector< G4tgrVolume * > GetVolumeList ()
std::vector< G4tgrPlace * > GetDetPlaceList ()
std::vector< G4tgrIsotope * > GetIsotopeList ()
std::vector< G4tgrElement * > GetElementList ()
std::vector< G4tgrMaterial * > GetMaterialList ()
std::vector
< G4tgrRotationMatrix * > GetRotMList ()
Static Public Member Functions
static G4tgrVolumeMgr * GetInstance ()
Private Member Functions
G4tgrVolumeMgr ()
~G4tgrVolumeMgr ()
Private Attributes
G4mapssol theG4tgrSolidMap
G4mapsvol theG4tgrVolumeMap
G4mmapspl theG4tgrVolumeTree
std::vector< G4tgrVolume * > theG4tgrVolumeList
std::vector< G4tgrPlace * > theG4tgrPlaceList
std::vector< G4tgrIsotope * > theHgIsotList
std::vector< G4tgrElement * > theHgElemList
std::vector< G4tgrMaterial * > theHgMateList
std::vector
< G4tgrRotationMatrix * > theHgRotMList
Static Private Attributes
static G4ThreadLocal
G4tgrVolumeMgr * theInstance = 0
Detailed Description
Definition at line 58 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 58 of file G4tgrVolumeMgr.hh
Constructor & Destructor Documentation
G4tgrVolumeMgr::G4tgrVolumeMgr () private
Definition at line 49 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgrVolumeMgr.cc
Referenced by GetInstance().
G4tgrVolumeMgr::~G4tgrVolumeMgr () private
Definition at line 55 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgrVolumeMgr.cc
References theInstance.
Member Function Documentation
G4tgrSolid * G4tgrVolumeMgr::CreateSolid (const std::vector< G4String > & wl, G4bool bVOLUtag)
Definition at line 74 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 74 of file G4tgrVolumeMgr.cc
References FatalException, FindSolid(), and G4Exception().
Referenced by G4tgrVolume::G4tgrVolume(), and G4tgrLineProcessor::ProcessLine().
void G4tgrVolumeMgr::DumpSummary ()
Definition at line 391 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 391 of file G4tgrVolumeMgr.cc
References G4tgrMaterialFactory::DumpElementList(), G4tgrMaterialFactory::DumpIsotopeList(), G4tgrMaterialFactory::DumpMaterialList(), G4tgrRotationMatrixFactory::DumpRotmList(), DumpVolumeTree(), G4cout, G4endl, G4tgrMaterialFactory::GetElementList(), G4tgrRotationMatrixFactory::GetInstance(), G4tgrMaterialFactory::GetInstance(), G4tgrMaterialFactory::GetIsotopeList(), G4tgrMaterialFactory::GetMaterialList(), G4tgrVolume::GetName(), G4tgrRotationMatrixFactory::GetRotMatList(), GetTopVolume(), and theG4tgrVolumeMap.
void G4tgrVolumeMgr::DumpVolumeLeaf (const G4tgrVolume * vol, unsigned int copyNo, unsigned int leafDepth)
Definition at line 361 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 361 of file G4tgrVolumeMgr.cc
References G4cout, G4endl, GetChildren(), G4tgrPlace::GetCopyNo(), G4tgrVolume::GetName(), and G4tgrPlace::GetVolume().
Referenced by DumpVolumeTree().
void G4tgrVolumeMgr::DumpVolumeTree ()
Definition at line 350 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 350 of file G4tgrVolumeMgr.cc
References DumpVolumeLeaf(), G4cout, G4endl, and GetTopVolume().
Referenced by DumpSummary().
G4tgrSolid * G4tgrVolumeMgr::FindSolid (const G4String & name, G4bool exists = false)
Definition at line 186 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 186 of file G4tgrVolumeMgr.cc
References FatalException, G4cerr, G4endl, G4Exception(), and theG4tgrSolidMap.
Referenced by CreateSolid(), G4tgrSolidBoolean::G4tgrSolidBoolean(), and G4tgrVolume::G4tgrVolume().
G4tgrVolume * G4tgrVolumeMgr::FindVolume (const G4String & volname, G4bool exists = false)
Definition at line 216 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 216 of file G4tgrVolumeMgr.cc
References FatalException, G4cerr, G4endl, G4Exception(), JustWarning, and theG4tgrVolumeMap.
Referenced by G4tgrLineProcessor::FindVolume(), G4tgrSolidBoolean::G4tgrSolidBoolean(), G4tgrVolumeDivision::G4tgrVolumeDivision(), and GetTopVolume().
std::vector< G4tgrVolume * > G4tgrVolumeMgr::FindVolumes (const G4String & volname, G4bool exists)
Definition at line 251 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 251 of file G4tgrVolumeMgr.cc
References G4tgrUtils::AreWordsEquivalent(), FatalException, G4cerr, G4endl, G4Exception(), JustWarning, and theG4tgrVolumeMap.
Referenced by G4tgrLineProcessor::ProcessLine().
std::pair< G4mmapspl::iterator, G4mmapspl::iterator > G4tgrVolumeMgr::GetChildren (const G4String & name)
Definition at line 341 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 341 of file G4tgrVolumeMgr.cc
References theG4tgrVolumeTree.
Referenced by G4tgbVolume::ConstructG4Volumes(), and DumpVolumeLeaf().
std::vector<G4tgrPlace*> G4tgrVolumeMgr::GetDetPlaceList () inline
Definition at line 117 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 117 of file G4tgrVolumeMgr.hh
References theG4tgrPlaceList.
std::vector<G4tgrElement*> G4tgrVolumeMgr::GetElementList () inline
Definition at line 119 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 119 of file G4tgrVolumeMgr.hh
References theHgElemList.
G4tgrVolumeMgr * G4tgrVolumeMgr::GetInstance (void) static
Definition at line 62 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 62 of file G4tgrVolumeMgr.cc
References G4tgrVolumeMgr(), and theInstance.
Referenced by G4tgrVolumeAssembly::AddPlace(), G4tgrVolume::AddPlace(), G4tgrVolume::AddPlaceParam(), G4tgrVolume::AddPlaceReplica(), G4tgbDetectorConstruction::Construct(), G4tgbVolume::ConstructG4Volumes(), G4tgbVolumeMgr::CopyVolumes(), G4tgrLineProcessor::G4tgrLineProcessor(), G4tgrSolid::G4tgrSolid(), G4tgrSolidBoolean::G4tgrSolidBoolean(), G4tgrVolume::G4tgrVolume(), G4tgrVolumeDivision::G4tgrVolumeDivision(), ExTGRCDetectorBuilder::ReadDetector(), and G4tgbDetectorBuilder::ReadDetector().
std::vector<G4tgrIsotope*> G4tgrVolumeMgr::GetIsotopeList () inline
Definition at line 118 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 118 of file G4tgrVolumeMgr.hh
References theHgIsotList.
std::vector<G4tgrMaterial*> G4tgrVolumeMgr::GetMaterialList () inline
Definition at line 120 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 120 of file G4tgrVolumeMgr.hh
References theHgMateList.
std::vector<G4tgrRotationMatrix*> G4tgrVolumeMgr::GetRotMList () inline
Definition at line 121 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 121 of file G4tgrVolumeMgr.hh
References theHgRotMList.
const G4mapssol& G4tgrVolumeMgr::GetSolidMap () inline
Definition at line 113 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 113 of file G4tgrVolumeMgr.hh
References theG4tgrSolidMap.
const G4tgrVolume * G4tgrVolumeMgr::GetTopVolume ()
Definition at line 291 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 291 of file G4tgrVolumeMgr.cc
References FindVolume(), G4cout, G4endl, G4Exception(), G4tgrVolume::GetName(), G4tgrVolume::GetPlacements(), G4tgrVolume::GetType(), G4tgrMessenger::GetVerboseLevel(), JustWarning, and theG4tgrVolumeMap.
Referenced by G4tgbDetectorConstruction::Construct(), DumpSummary(), DumpVolumeTree(), ExTGRCDetectorBuilder::ReadDetector(), and G4tgbDetectorBuilder::ReadDetector().
std::vector<G4tgrVolume*> G4tgrVolumeMgr::GetVolumeList () inline
Definition at line 116 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 116 of file G4tgrVolumeMgr.hh
References theG4tgrVolumeList.
const G4mapsvol& G4tgrVolumeMgr::GetVolumeMap () inline
Definition at line 114 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 114 of file G4tgrVolumeMgr.hh
References theG4tgrVolumeMap.
Referenced by G4tgbVolumeMgr::CopyVolumes().
const G4mmapspl& G4tgrVolumeMgr::GetVolumeTree () inline
Definition at line 115 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 115 of file G4tgrVolumeMgr.hh
References theG4tgrVolumeTree.
void G4tgrVolumeMgr::RegisterMe (G4tgrSolid * vol)
Definition at line 108 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 108 of file G4tgrVolumeMgr.cc
References FatalException, G4Exception(), G4tgrSolid::GetName(), and theG4tgrSolidMap.
Referenced by G4tgrSolid::G4tgrSolid(), G4tgrSolidBoolean::G4tgrSolidBoolean(), and G4tgrLineProcessor::ProcessLine().
void G4tgrVolumeMgr::RegisterMe (G4tgrVolume * vol)
Definition at line 139 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 139 of file G4tgrVolumeMgr.cc
References FatalException, G4Exception(), G4tgrVolume::GetName(), theG4tgrVolumeList, and theG4tgrVolumeMap.
void G4tgrVolumeMgr::RegisterMe (G4tgrPlace * pl) inline
Definition at line 105 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 105 of file G4tgrVolumeMgr.hh
References theG4tgrPlaceList.
void G4tgrVolumeMgr::RegisterMe (G4tgrIsotope * iso) inline
Definition at line 106 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 106 of file G4tgrVolumeMgr.hh
References theHgIsotList.
void G4tgrVolumeMgr::RegisterMe (G4tgrElement * ele) inline
Definition at line 107 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 107 of file G4tgrVolumeMgr.hh
References theHgElemList.
void G4tgrVolumeMgr::RegisterMe (G4tgrMaterial * mat) inline
Definition at line 108 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 108 of file G4tgrVolumeMgr.hh
References theHgMateList.
void G4tgrVolumeMgr::RegisterMe (G4tgrRotationMatrix * rm) inline
Definition at line 109 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 109 of file G4tgrVolumeMgr.hh
References theHgRotMList.
void G4tgrVolumeMgr::RegisterParentChild (const G4String & parentName, const G4tgrPlace * pl)
Definition at line 178 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 178 of file G4tgrVolumeMgr.cc
References theG4tgrVolumeTree.
Referenced by G4tgrVolumeAssembly::AddPlace(), G4tgrVolume::AddPlace(), G4tgrVolume::AddPlaceParam(), G4tgrVolume::AddPlaceReplica(), and G4tgrVolumeDivision::G4tgrVolumeDivision().
void G4tgrVolumeMgr::UnRegisterMe (G4tgrSolid * vol)
Definition at line 122 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 122 of file G4tgrVolumeMgr.cc
References FatalException, G4Exception(), G4tgrSolid::GetName(), and theG4tgrSolidMap.
void G4tgrVolumeMgr::UnRegisterMe (G4tgrVolume * vol)
Definition at line 154 of file G4tgrVolumeMgr.cc.
View newest version in sPHENIX GitHub at line 154 of file G4tgrVolumeMgr.cc
References FatalException, G4Exception(), G4tgrVolume::GetName(), theG4tgrVolumeList, and theG4tgrVolumeMap.
Member Data Documentation
std::vector<G4tgrPlace*> G4tgrVolumeMgr::theG4tgrPlaceList private
Definition at line 145 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 145 of file G4tgrVolumeMgr.hh
Referenced by GetDetPlaceList(), and RegisterMe().
G4mapssol G4tgrVolumeMgr::theG4tgrSolidMap private
Definition at line 130 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 130 of file G4tgrVolumeMgr.hh
Referenced by FindSolid(), GetSolidMap(), RegisterMe(), and UnRegisterMe().
std::vector<G4tgrVolume*> G4tgrVolumeMgr::theG4tgrVolumeList private
Definition at line 144 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 144 of file G4tgrVolumeMgr.hh
Referenced by GetVolumeList(), RegisterMe(), and UnRegisterMe().
G4mapsvol G4tgrVolumeMgr::theG4tgrVolumeMap private
Definition at line 134 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 134 of file G4tgrVolumeMgr.hh
Referenced by DumpSummary(), FindVolume(), FindVolumes(), GetTopVolume(), GetVolumeMap(), RegisterMe(), and UnRegisterMe().
G4mmapspl G4tgrVolumeMgr::theG4tgrVolumeTree private
Definition at line 138 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 138 of file G4tgrVolumeMgr.hh
Referenced by GetChildren(), GetVolumeTree(), and RegisterParentChild().
std::vector<G4tgrElement*> G4tgrVolumeMgr::theHgElemList private
Definition at line 147 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 147 of file G4tgrVolumeMgr.hh
Referenced by GetElementList(), and RegisterMe().
std::vector<G4tgrIsotope*> G4tgrVolumeMgr::theHgIsotList private
Definition at line 146 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 146 of file G4tgrVolumeMgr.hh
Referenced by GetIsotopeList(), and RegisterMe().
std::vector<G4tgrMaterial*> G4tgrVolumeMgr::theHgMateList private
Definition at line 148 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 148 of file G4tgrVolumeMgr.hh
Referenced by GetMaterialList(), and RegisterMe().
std::vector<G4tgrRotationMatrix*> G4tgrVolumeMgr::theHgRotMList private
Definition at line 149 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 149 of file G4tgrVolumeMgr.hh
Referenced by GetRotMList(), and RegisterMe().
G4ThreadLocal G4tgrVolumeMgr * G4tgrVolumeMgr::theInstance = 0 static private
Definition at line 142 of file G4tgrVolumeMgr.hh.
View newest version in sPHENIX GitHub at line 142 of file G4tgrVolumeMgr.hh
Referenced by GetInstance(), and ~G4tgrVolumeMgr().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrVolumeMgr.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrVolumeMgr.cc