ECCE @ EIC Software: G4ExcitedString Class Reference
G4ExcitedString Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4ExcitedString.hh>
Public Types
enum { PROJECTILE = 1, TARGET = -1 }
Public Member Functions
G4ExcitedString (G4Parton *Color, G4Parton *Gluon, G4Parton *AntiColor, G4int Direction=PROJECTILE)
G4ExcitedString (G4Parton *Color, G4Parton *AntiColor, G4int Direction=PROJECTILE)
G4ExcitedString (G4KineticTrack *atrack)
~G4ExcitedString ()
G4bool operator== (const G4ExcitedString &right) const
G4bool operator!= (const G4ExcitedString &right) const
G4double GetTimeOfCreation () const
void SetTimeOfCreation (G4double aTime)
const G4ThreeVector & GetPosition () const
void SetPosition (const G4ThreeVector &aPosition)
const G4PartonVector * GetPartonList () const
G4LorentzVector Get4Momentum () const
void LorentzRotate (const G4LorentzRotation &rotation)
void InsertParton (G4Parton *aParton, const G4Parton *addafter=NULL)
G4LorentzRotation TransformToCenterOfMass ()
G4LorentzRotation TransformToAlignedCms ()
void Boost (G4ThreeVector &Velocity)
G4Parton * GetColorParton (void) const
G4Parton * GetGluon (void) const
G4Parton * GetAntiColorParton (void) const
G4Parton * GetGluon (G4int GluonPos) const
G4KineticTrack * GetKineticTrack () const
G4Parton * GetLeftParton (void) const
G4Parton * GetRightParton (void) const
G4bool IsItKinkyString (void) const
G4int GetDirection (void) const
G4bool IsExcited () const
Private Member Functions
G4ExcitedString (const G4ExcitedString &right)
G4ExcitedString & operator= (const G4ExcitedString &right)
Private Attributes
G4int theDirection
G4double theTimeOfCreation
G4ThreeVector thePosition
G4PartonVector thePartons
G4KineticTrack * theTrack
Detailed Description
Definition at line 51 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ExcitedString.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
PROJECTILE
TARGET
Definition at line 56 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ExcitedString.hh
Constructor & Destructor Documentation
G4ExcitedString::G4ExcitedString (G4Parton * Color, G4Parton * Gluon, G4Parton * AntiColor, G4int Direction = PROJECTILE)
Definition at line 53 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ExcitedString.cc
References G4Parton::GetPosition(), theDirection, thePartons, thePosition, theTimeOfCreation, and theTrack.
G4ExcitedString::G4ExcitedString (G4Parton * Color, G4Parton * AntiColor, G4int Direction = PROJECTILE)
Definition at line 43 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ExcitedString.cc
References G4Parton::GetPosition(), theDirection, thePartons, thePosition, theTimeOfCreation, and theTrack.
G4ExcitedString::G4ExcitedString (G4KineticTrack * atrack)
Definition at line 64 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ExcitedString.cc
References G4KineticTrack::GetFormationTime(), G4KineticTrack::GetPosition(), theDirection, thePosition, theTimeOfCreation, theTrack, and track.
G4ExcitedString::~G4ExcitedString ()
Definition at line 72 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ExcitedString.cc
References thePartons, and theTrack.
G4ExcitedString::G4ExcitedString (const G4ExcitedString & right) private
Member Function Documentation
void G4ExcitedString::Boost (G4ThreeVector & Velocity)
Definition at line 97 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ExcitedString.cc
References CLHEP::HepLorentzVector::boost(), and thePartons.
G4LorentzVector G4ExcitedString::Get4Momentum () const inline
Definition at line 161 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 161 of file G4ExcitedString.hh
References G4KineticTrack::Get4Momentum(), IsExcited(), momentum, thePartons, and theTrack.
Referenced by G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4FragmentingString::G4FragmentingString(), LorentzRotate(), TransformToAlignedCms(), and TransformToCenterOfMass().
G4Parton * G4ExcitedString::GetAntiColorParton (void) const
Definition at line 135 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 135 of file G4ExcitedString.cc
References G4Parton::GetPDGcode(), start(), and thePartons.
G4Parton * G4ExcitedString::GetColorParton (void) const
Definition at line 109 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 109 of file G4ExcitedString.cc
References G4Parton::GetPDGcode(), start(), and thePartons.
G4int G4ExcitedString::GetDirection (void) const
Definition at line 154 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 154 of file G4ExcitedString.cc
References theDirection.
Referenced by G4VLongitudinalStringDecay::CopyExcited(), G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4FragmentingString::G4FragmentingString(), and G4LundStringFragmentation::Loop_toFragmentString().
G4Parton * G4ExcitedString::GetGluon (void) const
Definition at line 121 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ExcitedString.cc
References thePartons.
G4Parton * G4ExcitedString::GetGluon (G4int GluonPos) const
Definition at line 128 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 128 of file G4ExcitedString.cc
References thePartons.
G4KineticTrack * G4ExcitedString::GetKineticTrack () const inline
Definition at line 262 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 262 of file G4ExcitedString.hh
References theTrack.
G4Parton * G4ExcitedString::GetLeftParton (void) const
Definition at line 161 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 161 of file G4ExcitedString.cc
References thePartons.
Referenced by G4FTFModel::BuildStrings(), G4VLongitudinalStringDecay::CopyExcited(), G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4FragmentingString::G4FragmentingString(), and G4LundStringFragmentation::Loop_toFragmentString().
const G4PartonVector * G4ExcitedString::GetPartonList () const inline
Definition at line 256 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 256 of file G4ExcitedString.hh
References thePartons.
const G4ThreeVector & G4ExcitedString::GetPosition (void) const inline
Definition at line 149 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ExcitedString.hh
References thePosition.
Referenced by G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4LundStringFragmentation::Loop_toFragmentString(), and G4VLongitudinalStringDecay::ProduceOneHadron().
G4Parton * G4ExcitedString::GetRightParton (void) const
Definition at line 168 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 168 of file G4ExcitedString.cc
References thePartons.
Referenced by G4FTFModel::BuildStrings(), G4VLongitudinalStringDecay::CopyExcited(), G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4FragmentingString::G4FragmentingString(), and G4LundStringFragmentation::Loop_toFragmentString().
G4double G4ExcitedString::GetTimeOfCreation () const inline
Definition at line 137 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ExcitedString.hh
References theTimeOfCreation.
Referenced by G4LundStringFragmentation::FragmentString(), and G4LundStringFragmentation::Loop_toFragmentString().
void G4ExcitedString::InsertParton (G4Parton * aParton, const G4Parton * addafter = NULL) inline
Definition at line 196 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 196 of file G4ExcitedString.hh
References thePartons.
G4bool G4ExcitedString::IsExcited () const inline
Definition at line 268 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 268 of file G4ExcitedString.hh
References theTrack.
Referenced by G4FTFModel::BuildStrings(), Get4Momentum(), LorentzRotate(), and TransformToCenterOfMass().
G4bool G4ExcitedString::IsItKinkyString (void) const
Definition at line 147 of file G4ExcitedString.cc.
View newest version in sPHENIX GitHub at line 147 of file G4ExcitedString.cc
References thePartons.
void G4ExcitedString::LorentzRotate (const G4LorentzRotation & rotation) inline
Definition at line 180 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 180 of file G4ExcitedString.hh
References Get4Momentum(), G4KineticTrack::Get4Momentum(), IsExcited(), G4KineticTrack::Set4Momentum(), thePartons, and theTrack.
G4bool G4ExcitedString::operator!= (const G4ExcitedString & right) const inline
Definition at line 131 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ExcitedString.hh
References right.
G4ExcitedString& G4ExcitedString::operator= (const G4ExcitedString & right) private
G4bool G4ExcitedString::operator== (const G4ExcitedString & right) const inline
Definition at line 125 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ExcitedString.hh
References right.
void G4ExcitedString::SetPosition (const G4ThreeVector & aPosition) inline
Definition at line 155 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ExcitedString.hh
References thePosition.
Referenced by G4DiffractiveExcitation::CreateStrings().
void G4ExcitedString::SetTimeOfCreation (G4double aTime) inline
Definition at line 143 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 143 of file G4ExcitedString.hh
References theTimeOfCreation.
Referenced by G4DiffractiveExcitation::CreateStrings().
G4LorentzRotation G4ExcitedString::TransformToAlignedCms () inline
Definition at line 237 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 237 of file G4ExcitedString.hh
References CLHEP::HepLorentzVector::boostVector(), Get4Momentum(), momentum, and thePartons.
Referenced by G4QGSMFragmentation::FragmentString().
G4LorentzRotation G4ExcitedString::TransformToCenterOfMass () inline
Definition at line 215 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 215 of file G4ExcitedString.hh
References CLHEP::HepLorentzVector::boostVector(), Get4Momentum(), IsExcited(), momentum, G4KineticTrack::Set4Momentum(), thePartons, and theTrack.
Member Data Documentation
G4int G4ExcitedString::theDirection private
Definition at line 116 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ExcitedString.hh
Referenced by G4ExcitedString(), and GetDirection().
G4PartonVector G4ExcitedString::thePartons private
Definition at line 119 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ExcitedString.hh
Referenced by Boost(), G4ExcitedString(), Get4Momentum(), GetAntiColorParton(), GetColorParton(), GetGluon(), GetLeftParton(), GetPartonList(), GetRightParton(), InsertParton(), IsItKinkyString(), LorentzRotate(), TransformToAlignedCms(), TransformToCenterOfMass(), and ~G4ExcitedString().
G4ThreeVector G4ExcitedString::thePosition private
Definition at line 118 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ExcitedString.hh
Referenced by G4ExcitedString(), GetPosition(), and SetPosition().
G4double G4ExcitedString::theTimeOfCreation private
Definition at line 117 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ExcitedString.hh
Referenced by G4ExcitedString(), GetTimeOfCreation(), and SetTimeOfCreation().
G4KineticTrack* G4ExcitedString::theTrack private
Definition at line 120 of file G4ExcitedString.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ExcitedString.hh
Referenced by G4ExcitedString(), Get4Momentum(), GetKineticTrack(), IsExcited(), LorentzRotate(), TransformToCenterOfMass(), and ~G4ExcitedString().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4ExcitedString.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4ExcitedString.cc