ECCE @ EIC Software: G4QuasiElRatios Class Reference
G4QuasiElRatios Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/quasi_elastic/include/G4QuasiElRatios.hh>
Public Member Functions
G4QuasiElRatios ()
~G4QuasiElRatios ()
std::pair< G4double, G4double > GetRatios (G4double pIU, G4int prPDG, G4int tgZ, G4int tgN)
std::pair< G4double, G4double > GetChExFactor (G4double pIU, G4int pPDG, G4int Z, G4int N)
std::pair< G4LorentzVector,
G4LorentzVector > Scatter (G4int NPDG, G4LorentzVector N4M, G4int pPDG, G4LorentzVector p4M)
std::pair< G4LorentzVector,
G4LorentzVector > ChExer (G4int NPDG, G4LorentzVector N4M, G4int pPDG, G4LorentzVector p4M)
std::pair< G4double, G4double > GetElTot (G4double pIU, G4int hPDG, G4int Z, G4int N)
G4double ChExElCoef (G4double p, G4int Z, G4int N, G4int pPDG)
std::pair< G4double, G4double > GetElTotXS (G4double Mom, G4int PDG, G4bool F)
std::pair< G4double, G4double > FetchElTot (G4double pGeV, G4int PDG, G4bool F)
G4bool RelDecayIn2 (G4LorentzVector &theMomentum, G4LorentzVector &f4Mom, G4LorentzVector &s4Mom, G4LorentzVector &dir, G4double maxCost=1., G4double minCost=-1.)
Private Member Functions
G4double GetQF2IN_Ratio (G4double TotCS_mb, G4int A)
G4double CalcQF2IN_Ratio (G4double TCSmb, G4int A)
std::pair< G4double, G4double > CalcElTot (G4double pGeV, G4int Index)
Private Attributes
G4ChipsProtonElasticXS * PCSmanager
G4ChipsNeutronElasticXS * NCSmanager
std::vector< G4double * > * vT
std::vector< G4double * > * vL
std::vector< std::pair
< G4double, G4double > * > * vX
G4double lastSRatio
G4double lastRRatio
std::vector< G4int > vARatio
std::vector< G4double > vHRatio
std::vector< G4int > vNRatio
std::vector< G4double > vMRatio
std::vector< G4int > vKRatio
G4int lastARatio
G4double lastHRatio
G4int lastNRatio
G4double lastMRatio
G4int lastKRatio
G4double * lastTRatio
G4double * lastLRatio
G4double lastPtot
G4int lastHtot
G4bool lastFtot
std::pair< G4double, G4double > lastRtot
std::vector< G4int > vItot
std::vector< G4double > vMtot
std::vector< G4int > vKtot
G4int lastItot
G4double lastMtot
G4int lastKtot
std::pair< G4double, G4double > * lastXtot
Detailed Description
Definition at line 52 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 52 of file G4QuasiElRatios.hh
Constructor & Destructor Documentation
G4QuasiElRatios::G4QuasiElRatios ()
Definition at line 87 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 87 of file G4QuasiElRatios.cc
References G4ChipsProtonElasticXS::Default_Name(), G4ChipsNeutronElasticXS::Default_Name(), G4CrossSectionDataSetRegistry::GetCrossSectionDataSet(), G4CrossSectionDataSetRegistry::Instance(), lastARatio, lastFtot, lastHRatio, lastHtot, lastItot, lastKRatio, lastKtot, lastLRatio, lastMRatio, lastMtot, lastNRatio, lastPtot, lastRRatio, lastSRatio, lastTRatio, lastXtot, NCSmanager, PCSmanager, vL, vT, and vX.
G4QuasiElRatios::~G4QuasiElRatios ()
Definition at line 115 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 115 of file G4QuasiElRatios.cc
References pos(), vL, vT, and vX.
Member Function Documentation
std::pair< G4double, G4double > G4QuasiElRatios::CalcElTot (G4double pGeV, G4int Index) private
Definition at line 321 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 321 of file G4QuasiElRatios.cc
References FatalException, G4cout, G4endl, G4Exception(), G4Log(), G4Pow::GetInstance(), LE, G4Pow::powA(), and G4InuclParticleNames::sp.
Referenced by FetchElTot(), and GetElTotXS().
G4double G4QuasiElRatios::CalcQF2IN_Ratio (G4double TCSmb, G4int A) private
Definition at line 309 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 309 of file G4QuasiElRatios.cc
References C(), E, F, G4Exp(), G4Pow::GetInstance(), P, and G4Pow::powA().
Referenced by GetQF2IN_Ratio().
G4double G4QuasiElRatios::ChExElCoef (G4double p, G4int Z, G4int N, G4int pPDG)
Definition at line 995 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 995 of file G4QuasiElRatios.cc
References A(), G4cout, G4endl, G4Log(), MeV, N, Acts::IntegrationTest::R, G4InuclParticleNames::sp, T, and Z.
std::pair< G4LorentzVector, G4LorentzVector > G4QuasiElRatios::ChExer (G4int NPDG, G4LorentzVector N4M, G4int pPDG, G4LorentzVector p4M)
Definition at line 883 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 883 of file G4QuasiElRatios.cc
References E, CLHEP::HepLorentzVector::e(), FatalException, G4cerr, G4cout, G4endl, G4Exception(), G4UniformRand, G4ChipsProtonElasticXS::GetChipsCrossSection(), G4ChipsNeutronElasticXS::GetChipsCrossSection(), G4ChipsProtonElasticXS::GetExchangeT(), G4ChipsNeutronElasticXS::GetExchangeT(), G4ChipsProtonElasticXS::GetHMaxT(), G4ChipsNeutronElasticXS::GetHMaxT(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzVector::m(), CLHEP::HepLorentzVector::m2(), megaelectronvolt, N, NCSmanager, G4Neutron::Neutron(), P, PCSmanager, G4Proton::Proton(), RelDecayIn2(), and Z.
std::pair< G4double, G4double > G4QuasiElRatios::FetchElTot (G4double pGeV, G4int PDG, G4bool F)
Definition at line 600 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 600 of file G4QuasiElRatios.cc
References CalcElTot(), d, e, FatalException, G4cout, G4endl, G4Exception(), G4Exp(), G4Log(), G4UniformRand, lastFtot, lastHtot, lastItot, lastKtot, lastMtot, lastPtot, lastRtot, lastXtot, n, t, vItot, vKtot, vMtot, and vX.
Referenced by GetChExFactor(), and GetElTot().
std::pair< G4double, G4double > G4QuasiElRatios::GetChExFactor (G4double pIU, G4int pPDG, G4int Z, G4int N)
Definition at line 726 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 726 of file G4QuasiElRatios.cc
References A(), FetchElTot(), G4cout, G4endl, G4Log(), gigaelectronvolt, N, and Z.
std::pair< G4double, G4double > G4QuasiElRatios::GetElTot (G4double pIU, G4int hPDG, G4int Z, G4int N)
Definition at line 710 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 710 of file G4QuasiElRatios.cc
References A(), FetchElTot(), G4cout, G4endl, gigaelectronvolt, millibarn, and N.
Referenced by GetRatios().
std::pair< G4double, G4double > G4QuasiElRatios::GetElTotXS (G4double Mom, G4int PDG, G4bool F)
Definition at line 573 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 573 of file G4QuasiElRatios.cc
References CalcElTot(), FatalException, G4cout, G4endl, G4Exception(), and G4UniformRand.
G4double G4QuasiElRatios::GetQF2IN_Ratio (G4double TotCS_mb, G4int A) private
Definition at line 156 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 156 of file G4QuasiElRatios.cc
References A(), CalcQF2IN_Ratio(), d, G4Exp(), G4Log(), lastARatio, lastHRatio, lastKRatio, lastLRatio, lastMRatio, lastNRatio, lastRRatio, lastSRatio, lastTRatio, ls(), n, v, vARatio, vHRatio, vKRatio, vL, vMRatio, vNRatio, and vT.
Referenced by GetRatios().
std::pair< G4double, G4double > G4QuasiElRatios::GetRatios (G4double pIU, G4int prPDG, G4int tgZ, G4int tgN)
Definition at line 137 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 137 of file G4QuasiElRatios.cc
References GetElTot(), GetQF2IN_Ratio(), millibarn, and Acts::IntegrationTest::R.
Referenced by G4QuasiElasticChannel::GetFraction().
G4bool G4QuasiElRatios::RelDecayIn2 (G4LorentzVector & theMomentum, G4LorentzVector & f4Mom, G4LorentzVector & s4Mom, G4LorentzVector & dir, G4double maxCost = 1., G4double minCost = -1.)
Definition at line 1018 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 1018 of file G4QuasiElRatios.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), CLHEP::Hep3Vector::cross(), d2, dE, dir, CLHEP::HepLorentzVector::e(), G4cerr, G4endl, G4UniformRand, CLHEP::HepLorentzVector::m2(), CLHEP::Hep3Vector::mag2(), CLHEP::Hep3Vector::orthogonal(), phi, CLHEP::HepLorentzVector::rho(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setVect(), twopi, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Referenced by ChExer(), and Scatter().
std::pair< G4LorentzVector, G4LorentzVector > G4QuasiElRatios::Scatter (G4int NPDG, G4LorentzVector N4M, G4int pPDG, G4LorentzVector p4M)
Definition at line 769 of file G4QuasiElRatios.cc.
View newest version in sPHENIX GitHub at line 769 of file G4QuasiElRatios.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), E, CLHEP::HepLorentzVector::e(), FatalException, G4cerr, G4cout, G4endl, G4Exception(), G4ChipsProtonElasticXS::GetChipsCrossSection(), G4ChipsNeutronElasticXS::GetChipsCrossSection(), G4ChipsProtonElasticXS::GetExchangeT(), G4ChipsNeutronElasticXS::GetExchangeT(), G4ChipsProtonElasticXS::GetHMaxT(), G4ChipsNeutronElasticXS::GetHMaxT(), G4ParticleDefinition::GetPDGMass(), G4He3::He3(), CLHEP::HepLorentzVector::m(), CLHEP::HepLorentzVector::m2(), megaelectronvolt, N, NCSmanager, G4Neutron::Neutron(), P, PCSmanager, G4Proton::Proton(), RelDecayIn2(), G4InuclParticleNames::tm, G4Triton::Triton(), and Z.
Referenced by G4QuasiElasticChannel::Scatter().
Member Data Documentation
G4int G4QuasiElRatios::lastARatio private
Definition at line 113 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 113 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
G4bool G4QuasiElRatios::lastFtot private
Definition at line 123 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 123 of file G4QuasiElRatios.hh
Referenced by FetchElTot(), and G4QuasiElRatios().
G4double G4QuasiElRatios::lastHRatio private
Definition at line 114 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 114 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
G4int G4QuasiElRatios::lastHtot private
Definition at line 122 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 122 of file G4QuasiElRatios.hh
Referenced by FetchElTot(), and G4QuasiElRatios().
G4int G4QuasiElRatios::lastItot private
Definition at line 128 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 128 of file G4QuasiElRatios.hh
Referenced by FetchElTot(), and G4QuasiElRatios().
G4int G4QuasiElRatios::lastKRatio private
Definition at line 117 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 117 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
G4int G4QuasiElRatios::lastKtot private
Definition at line 130 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 130 of file G4QuasiElRatios.hh
Referenced by FetchElTot(), and G4QuasiElRatios().
G4double* G4QuasiElRatios::lastLRatio private
Definition at line 119 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 119 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
G4double G4QuasiElRatios::lastMRatio private
Definition at line 116 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 116 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
G4double G4QuasiElRatios::lastMtot private
Definition at line 129 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 129 of file G4QuasiElRatios.hh
Referenced by FetchElTot(), and G4QuasiElRatios().
G4int G4QuasiElRatios::lastNRatio private
Definition at line 115 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 115 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
G4double G4QuasiElRatios::lastPtot private
Definition at line 121 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 121 of file G4QuasiElRatios.hh
Referenced by FetchElTot(), and G4QuasiElRatios().
G4double G4QuasiElRatios::lastRRatio private
Definition at line 106 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 106 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
std::pair<G4double,G4double> G4QuasiElRatios::lastRtot private
Definition at line 124 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 124 of file G4QuasiElRatios.hh
Referenced by FetchElTot().
G4double G4QuasiElRatios::lastSRatio private
Definition at line 105 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 105 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
G4double* G4QuasiElRatios::lastTRatio private
Definition at line 118 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 118 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), and GetQF2IN_Ratio().
std::pair<G4double,G4double>* G4QuasiElRatios::lastXtot private
Definition at line 131 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 131 of file G4QuasiElRatios.hh
Referenced by FetchElTot(), and G4QuasiElRatios().
G4ChipsNeutronElasticXS* G4QuasiElRatios::NCSmanager private
Definition at line 92 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 92 of file G4QuasiElRatios.hh
Referenced by ChExer(), G4QuasiElRatios(), and Scatter().
G4ChipsProtonElasticXS* G4QuasiElRatios::PCSmanager private
Definition at line 91 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 91 of file G4QuasiElRatios.hh
Referenced by ChExer(), G4QuasiElRatios(), and Scatter().
std::vector<G4int> G4QuasiElRatios::vARatio private
Definition at line 107 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 107 of file G4QuasiElRatios.hh
Referenced by GetQF2IN_Ratio().
std::vector<G4double> G4QuasiElRatios::vHRatio private
Definition at line 108 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 108 of file G4QuasiElRatios.hh
Referenced by GetQF2IN_Ratio().
std::vector<G4int> G4QuasiElRatios::vItot private
Definition at line 125 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 125 of file G4QuasiElRatios.hh
Referenced by FetchElTot().
std::vector<G4int> G4QuasiElRatios::vKRatio private
Definition at line 111 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 111 of file G4QuasiElRatios.hh
Referenced by GetQF2IN_Ratio().
std::vector<G4int> G4QuasiElRatios::vKtot private
Definition at line 127 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 127 of file G4QuasiElRatios.hh
Referenced by FetchElTot().
std::vector<G4double*>* G4QuasiElRatios::vL private
Definition at line 102 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 102 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), GetQF2IN_Ratio(), and ~G4QuasiElRatios().
std::vector<G4double> G4QuasiElRatios::vMRatio private
Definition at line 110 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 110 of file G4QuasiElRatios.hh
Referenced by GetQF2IN_Ratio().
std::vector<G4double> G4QuasiElRatios::vMtot private
Definition at line 126 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 126 of file G4QuasiElRatios.hh
Referenced by FetchElTot().
std::vector<G4int> G4QuasiElRatios::vNRatio private
Definition at line 109 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 109 of file G4QuasiElRatios.hh
Referenced by GetQF2IN_Ratio().
std::vector<G4double*>* G4QuasiElRatios::vT private
Definition at line 101 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 101 of file G4QuasiElRatios.hh
Referenced by G4QuasiElRatios(), GetQF2IN_Ratio(), and ~G4QuasiElRatios().
std::vector<std::pair<G4double,G4double>*>* G4QuasiElRatios::vX private
Definition at line 103 of file G4QuasiElRatios.hh.
View newest version in sPHENIX GitHub at line 103 of file G4QuasiElRatios.hh
Referenced by FetchElTot(), G4QuasiElRatios(), and ~G4QuasiElRatios().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/quasi_elastic/include/G4QuasiElRatios.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/quasi_elastic/src/G4QuasiElRatios.cc