ECCE @ EIC Software: G4AtomicFormFactor Class Reference
G4AtomicFormFactor Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4AtomicFormFactor.hh>
Public Member Functions
G4double Get (G4double kScatteringVector, G4int Z, G4int charge=0)
Static Public Member Functions
static G4AtomicFormFactor * GetManager ()
Protected Member Functions
G4AtomicFormFactor ()
~G4AtomicFormFactor ()
Private Member Functions
void InsertCoefficients (G4int index, std::vector< G4double > aDoubleVec)
void LoadCoefficiencts (G4int index)
G4int GetIndex (G4int Z, G4int charge=0)
Private Attributes
std::map< G4int, std::vector
< G4double > > theCoefficientsMap
G4double theCoefficients [9]
G4int loadedIndex
Static Private Attributes
static G4AtomicFormFactor * s_G4AtomicFormFactorManager = 0
Detailed Description
Definition at line 57 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 57 of file G4AtomicFormFactor.hh
Constructor & Destructor Documentation
G4AtomicFormFactor::G4AtomicFormFactor () inline protected
Definition at line 132 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 132 of file G4AtomicFormFactor.hh
References InsertCoefficients(), and loadedIndex.
Referenced by GetManager().
G4AtomicFormFactor::~G4AtomicFormFactor () inline protected
Definition at line 348 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 348 of file G4AtomicFormFactor.hh
Member Function Documentation
G4double G4AtomicFormFactor::Get (G4double kScatteringVector, G4int Z, G4int charge = 0) inline
Definition at line 111 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 111 of file G4AtomicFormFactor.hh
References charge, G4Exp(), GetIndex(), LoadCoefficiencts(), loadedIndex, and theCoefficients.
Referenced by G4CrystalExtension::ComputeStructureFactor().
G4int G4AtomicFormFactor::GetIndex (G4int Z, G4int charge = 0) inline private
Definition at line 104 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AtomicFormFactor.hh
References charge.
Referenced by Get().
static G4AtomicFormFactor* G4AtomicFormFactor::GetManager () inline static
Definition at line 63 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 63 of file G4AtomicFormFactor.hh
References G4AtomicFormFactor(), and s_G4AtomicFormFactorManager.
Referenced by G4CrystalExtension::ComputeStructureFactor().
void G4AtomicFormFactor::InsertCoefficients (G4int index, std::vector< G4double > aDoubleVec) inline private
Definition at line 91 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 91 of file G4AtomicFormFactor.hh
References theCoefficientsMap.
Referenced by G4AtomicFormFactor().
void G4AtomicFormFactor::LoadCoefficiencts (G4int index) inline private
Definition at line 95 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 95 of file G4AtomicFormFactor.hh
References loadedIndex, theCoefficients, and theCoefficientsMap.
Referenced by Get().
Member Data Documentation
G4int G4AtomicFormFactor::loadedIndex private
Definition at line 78 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 78 of file G4AtomicFormFactor.hh
Referenced by G4AtomicFormFactor(), Get(), and LoadCoefficiencts().
G4AtomicFormFactor * G4AtomicFormFactor::s_G4AtomicFormFactorManager = 0 static private
Definition at line 60 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 60 of file G4AtomicFormFactor.hh
Referenced by GetManager().
G4double G4AtomicFormFactor::theCoefficients[9] private
Definition at line 77 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AtomicFormFactor.hh
Referenced by Get(), and LoadCoefficiencts().
std::map<G4int,std::vector<G4double> > G4AtomicFormFactor::theCoefficientsMap private
Definition at line 76 of file G4AtomicFormFactor.hh.
View newest version in sPHENIX GitHub at line 76 of file G4AtomicFormFactor.hh
Referenced by InsertCoefficients(), and LoadCoefficiencts().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4AtomicFormFactor.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4AtomicFormFactor.cc