ECCE @ EIC Software: LXeEventAction Class Reference
LXeEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeEventAction.hh>
Public Member Functions
LXeEventAction (const LXeDetectorConstruction *)
virtual ~LXeEventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
void SetEventVerbose (G4int v)
void SetPMTThreshold (G4int t)
void SetForceDrawPhotons (G4bool b)
void SetForceDrawNoPhotons (G4bool b)
void IncPhotonCount_Scint ()
void IncPhotonCount_Ceren ()
void IncEDep (G4double dep)
void IncAbsorption ()
void IncBoundaryAbsorption ()
void IncHitCount (G4int i=1)
void SetEWeightPos (const G4ThreeVector &p)
void SetReconPos (const G4ThreeVector &p)
void SetConvPos (const G4ThreeVector &p)
void SetPosMax (const G4ThreeVector &p, G4double edep)
G4int GetPhotonCount_Scint () const
G4int GetPhotonCount_Ceren () const
G4int GetHitCount () const
G4double GetEDep () const
G4int GetAbsorptionCount () const
G4int GetBoundaryAbsorptionCount () const
G4ThreeVector GetEWeightPos ()
G4ThreeVector GetReconPos ()
G4ThreeVector GetConvPos ()
G4ThreeVector GetPosMax ()
G4double GetEDepMax ()
G4double IsConvPosSet ()
G4int GetPhotonCount ()
void IncPMTSAboveThreshold ()
G4int GetPMTSAboveThreshold ()
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
LXeEventMessenger * fEventMessenger
const LXeDetectorConstruction * fDetector
G4int fScintCollID
G4int fPMTCollID
G4int fVerbose
G4int fPMTThreshold
G4bool fForcedrawphotons
G4bool fForcenophotons
G4int fHitCount
G4int fPhotonCount_Scint
G4int fPhotonCount_Ceren
G4int fAbsorptionCount
G4int fBoundaryAbsorptionCount
G4double fTotE
G4ThreeVector fEWeightPos
G4ThreeVector fReconPos
G4ThreeVector fConvPos
G4bool fConvPosSet
G4ThreeVector fPosMax
G4double fEdepMax
G4int fPMTsAboveThreshold
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 42 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 42 of file LXeEventAction.hh
Constructor & Destructor Documentation
LXeEventAction::LXeEventAction (const LXeDetectorConstruction * det)
Definition at line 53 of file LXeEventAction.cc.
View newest version in sPHENIX GitHub at line 53 of file LXeEventAction.cc
References fAbsorptionCount, fBoundaryAbsorptionCount, fConvPosSet, fEdepMax, fEventMessenger, fHitCount, fPhotonCount_Ceren, fPhotonCount_Scint, fPMTsAboveThreshold, and fTotE.
LXeEventAction::~LXeEventAction () virtual
Definition at line 74 of file LXeEventAction.cc.
View newest version in sPHENIX GitHub at line 74 of file LXeEventAction.cc
Member Function Documentation
void LXeEventAction::BeginOfEventAction (const G4Event *) virtual
Reimplemented from G4UserEventAction.
Definition at line 78 of file LXeEventAction.cc.
View newest version in sPHENIX GitHub at line 78 of file LXeEventAction.cc
References fAbsorptionCount, fBoundaryAbsorptionCount, fConvPosSet, fEdepMax, fHitCount, fPhotonCount_Ceren, fPhotonCount_Scint, fPMTCollID, fPMTsAboveThreshold, fScintCollID, fTotE, G4SDManager::GetCollectionID(), and G4SDManager::GetSDMpointer().
void LXeEventAction::EndOfEventAction (const G4Event * anEvent) virtual
Reimplemented from G4UserEventAction.
Definition at line 101 of file LXeEventAction.cc.
View newest version in sPHENIX GitHub at line 101 of file LXeEventAction.cc
References G4THitsCollection< T >::DrawAllHits(), LXeTrajectory::DrawTrajectory(), edep, edepMax, G4TrajectoryContainer::entries(), G4THitsCollection< T >::entries(), fAbsorptionCount, fBoundaryAbsorptionCount, fEdepMax, fEWeightPos, fForcedrawphotons, fForcenophotons, fHitCount, G4VAnalysisManager::FillH1(), fPhotonCount_Ceren, fPhotonCount_Scint, fPMTCollID, fPMTsAboveThreshold, fPMTThreshold, fPosMax, fReconPos, fScintCollID, fTotE, fVerbose, G4cout, G4endl, G4VVisManager::GetConcreteInstance(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4RunManager::GetNonConstCurrentRun(), G4Trajectory::GetParticleName(), GetPhotonCount(), G4RunManager::GetRunManager(), G4Event::GetTrajectoryContainer(), LXeRun::IncAbsorption(), LXeRun::IncBoundaryAbsorption(), LXeRun::IncEDep(), LXeRun::IncHitCount(), LXeRun::IncHitsAboveThreshold(), LXeRun::IncPhotonCount_Ceren(), LXeRun::IncPhotonCount_Scint(), G4ToolsAnalysisManager::Instance(), keV, mm, G4RunManager::rndmSaveThisEvent(), LXeTrajectory::SetForceDrawTrajectory(), and LXeTrajectory::SetForceNoDrawTrajectory().
G4int LXeEventAction::GetAbsorptionCount () const inline
Definition at line 80 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 80 of file LXeEventAction.hh
References fAbsorptionCount.
G4int LXeEventAction::GetBoundaryAbsorptionCount () const inline
Definition at line 81 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 81 of file LXeEventAction.hh
References fBoundaryAbsorptionCount.
G4ThreeVector LXeEventAction::GetConvPos () inline
Definition at line 85 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 85 of file LXeEventAction.hh
References fConvPos.
G4double LXeEventAction::GetEDep () const inline
Definition at line 79 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 79 of file LXeEventAction.hh
References fTotE.
G4double LXeEventAction::GetEDepMax () inline
Definition at line 87 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 87 of file LXeEventAction.hh
References fEdepMax.
G4ThreeVector LXeEventAction::GetEWeightPos () inline
Definition at line 83 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 83 of file LXeEventAction.hh
References fEWeightPos.
G4int LXeEventAction::GetHitCount () const inline
Definition at line 78 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 78 of file LXeEventAction.hh
References fHitCount.
G4int LXeEventAction::GetPhotonCount () inline
Definition at line 91 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 91 of file LXeEventAction.hh
References fPhotonCount_Ceren, and fPhotonCount_Scint.
Referenced by EndOfEventAction().
G4int LXeEventAction::GetPhotonCount_Ceren () const inline
Definition at line 77 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 77 of file LXeEventAction.hh
References fPhotonCount_Ceren.
G4int LXeEventAction::GetPhotonCount_Scint () const inline
Definition at line 76 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 76 of file LXeEventAction.hh
References fPhotonCount_Scint.
G4int LXeEventAction::GetPMTSAboveThreshold () inline
Definition at line 94 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 94 of file LXeEventAction.hh
References fPMTsAboveThreshold.
G4ThreeVector LXeEventAction::GetPosMax () inline
Definition at line 86 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 86 of file LXeEventAction.hh
References fPosMax.
G4ThreeVector LXeEventAction::GetReconPos () inline
Definition at line 84 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 84 of file LXeEventAction.hh
References fReconPos.
void LXeEventAction::IncAbsorption () inline
Definition at line 64 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 64 of file LXeEventAction.hh
References fAbsorptionCount.
Referenced by LXeSteppingAction::UserSteppingAction().
void LXeEventAction::IncBoundaryAbsorption () inline
Definition at line 65 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 65 of file LXeEventAction.hh
References fBoundaryAbsorptionCount.
Referenced by LXeSteppingAction::UserSteppingAction().
void LXeEventAction::IncEDep (G4double dep) inline
Definition at line 63 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 63 of file LXeEventAction.hh
References fTotE.
void LXeEventAction::IncHitCount (G4int i = 1) inline
Definition at line 66 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 66 of file LXeEventAction.hh
References fHitCount.
void LXeEventAction::IncPhotonCount_Ceren () inline
Definition at line 62 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 62 of file LXeEventAction.hh
References fPhotonCount_Ceren.
Referenced by LXeStackingAction::ClassifyNewTrack().
void LXeEventAction::IncPhotonCount_Scint () inline
Definition at line 61 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 61 of file LXeEventAction.hh
References fPhotonCount_Scint.
Referenced by LXeStackingAction::ClassifyNewTrack().
void LXeEventAction::IncPMTSAboveThreshold () inline
Definition at line 93 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 93 of file LXeEventAction.hh
References fPMTsAboveThreshold.
G4double LXeEventAction::IsConvPosSet () inline
Definition at line 88 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 88 of file LXeEventAction.hh
References fConvPosSet.
Referenced by LXeSteppingAction::UserSteppingAction().
void LXeEventAction::SetConvPos (const G4ThreeVector & p) inline
Definition at line 70 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 70 of file LXeEventAction.hh
References fConvPos, and fConvPosSet.
Referenced by LXeSteppingAction::UserSteppingAction().
void LXeEventAction::SetEventVerbose (G4int v) inline
Definition at line 54 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 54 of file LXeEventAction.hh
References fVerbose, and v.
Referenced by LXeEventMessenger::SetNewValue().
void LXeEventAction::SetEWeightPos (const G4ThreeVector & p) inline
Definition at line 68 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 68 of file LXeEventAction.hh
References fEWeightPos.
void LXeEventAction::SetForceDrawNoPhotons (G4bool b) inline
Definition at line 59 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 59 of file LXeEventAction.hh
References b, and fForcenophotons.
Referenced by LXeEventMessenger::SetNewValue().
void LXeEventAction::SetForceDrawPhotons (G4bool b) inline
Definition at line 58 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 58 of file LXeEventAction.hh
References b, and fForcedrawphotons.
Referenced by LXeEventMessenger::SetNewValue().
void LXeEventAction::SetPMTThreshold (G4int t) inline
Definition at line 56 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 56 of file LXeEventAction.hh
References fPMTThreshold, and t.
Referenced by LXeEventMessenger::SetNewValue().
void LXeEventAction::SetPosMax (const G4ThreeVector & p, G4double edep) inline
Definition at line 71 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 71 of file LXeEventAction.hh
References edep, fEdepMax, and fPosMax.
void LXeEventAction::SetReconPos (const G4ThreeVector & p) inline
Definition at line 69 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 69 of file LXeEventAction.hh
References fReconPos.
Member Data Documentation
G4int LXeEventAction::fAbsorptionCount private
Definition at line 114 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 114 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), GetAbsorptionCount(), IncAbsorption(), and LXeEventAction().
G4int LXeEventAction::fBoundaryAbsorptionCount private
Definition at line 115 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 115 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), GetBoundaryAbsorptionCount(), IncBoundaryAbsorption(), and LXeEventAction().
G4ThreeVector LXeEventAction::fConvPos private
Definition at line 123 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 123 of file LXeEventAction.hh
Referenced by GetConvPos(), and SetConvPos().
G4bool LXeEventAction::fConvPosSet private
Definition at line 124 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 124 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), IsConvPosSet(), LXeEventAction(), and SetConvPos().
const LXeDetectorConstruction* LXeEventAction::fDetector private
Definition at line 99 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 99 of file LXeEventAction.hh
G4double LXeEventAction::fEdepMax private
Definition at line 126 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 126 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), GetEDepMax(), LXeEventAction(), and SetPosMax().
LXeEventMessenger* LXeEventAction::fEventMessenger private
Definition at line 98 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 98 of file LXeEventAction.hh
Referenced by LXeEventAction().
G4ThreeVector LXeEventAction::fEWeightPos private
Definition at line 121 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 121 of file LXeEventAction.hh
Referenced by EndOfEventAction(), GetEWeightPos(), and SetEWeightPos().
G4bool LXeEventAction::fForcedrawphotons private
Definition at line 108 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 108 of file LXeEventAction.hh
Referenced by EndOfEventAction(), and SetForceDrawPhotons().
G4bool LXeEventAction::fForcenophotons private
Definition at line 109 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 109 of file LXeEventAction.hh
Referenced by EndOfEventAction(), and SetForceDrawNoPhotons().
G4int LXeEventAction::fHitCount private
Definition at line 111 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 111 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), GetHitCount(), IncHitCount(), and LXeEventAction().
G4int LXeEventAction::fPhotonCount_Ceren private
Definition at line 113 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 113 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), GetPhotonCount(), GetPhotonCount_Ceren(), IncPhotonCount_Ceren(), and LXeEventAction().
G4int LXeEventAction::fPhotonCount_Scint private
Definition at line 112 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 112 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), GetPhotonCount(), GetPhotonCount_Scint(), IncPhotonCount_Scint(), and LXeEventAction().
G4int LXeEventAction::fPMTCollID private
Definition at line 102 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 102 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
G4int LXeEventAction::fPMTsAboveThreshold private
Definition at line 128 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 128 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), GetPMTSAboveThreshold(), IncPMTSAboveThreshold(), and LXeEventAction().
G4int LXeEventAction::fPMTThreshold private
Definition at line 106 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 106 of file LXeEventAction.hh
Referenced by EndOfEventAction(), and SetPMTThreshold().
G4ThreeVector LXeEventAction::fPosMax private
Definition at line 125 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 125 of file LXeEventAction.hh
Referenced by EndOfEventAction(), GetPosMax(), and SetPosMax().
G4ThreeVector LXeEventAction::fReconPos private
Definition at line 122 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 122 of file LXeEventAction.hh
Referenced by EndOfEventAction(), GetReconPos(), and SetReconPos().
G4int LXeEventAction::fScintCollID private
Definition at line 101 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 101 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), and EndOfEventAction().
G4double LXeEventAction::fTotE private
Definition at line 117 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 117 of file LXeEventAction.hh
Referenced by BeginOfEventAction(), EndOfEventAction(), GetEDep(), IncEDep(), and LXeEventAction().
G4int LXeEventAction::fVerbose private
Definition at line 104 of file LXeEventAction.hh.
View newest version in sPHENIX GitHub at line 104 of file LXeEventAction.hh
Referenced by EndOfEventAction(), and SetEventVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/include/LXeEventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/LXe/src/LXeEventAction.cc