ECCE @ EIC Software: HadrontherapyLet Class Reference
HadrontherapyLet Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyLet.hh>
Public Member Functions
~HadrontherapyLet ()
void Initialize ()
void Clear ()
void Fill (G4int i, G4int j, G4int k, G4double DE, G4double DX)
void FillEnergySpectrum (G4int trackID, G4ParticleDefinition *particleDef, G4double ekinMean, G4Material *mat, G4double DE, G4double DEEletrons, G4double DX, G4int i, G4int j, G4int k)
void LetOutput ()
void StoreLetAscii ()
Static Public Member Functions
static HadrontherapyLet * GetInstance (HadrontherapyDetectorConstruction *)
static HadrontherapyLet * GetInstance ()
Static Public Attributes
static G4bool doCalculation = false
Private Member Functions
HadrontherapyLet (HadrontherapyDetectorConstruction *)
Private Attributes
HadrontherapyPrimaryGeneratorAction * pPGA
G4Material * detectorMat
G4double density
G4String filename
std::ofstream ofs
std::ofstream stopFile
HadrontherapyMatrix * matrix
G4int nVoxels
G4int numberOfVoxelAlongX
G4int numberOfVoxelAlongY
G4int numberOfVoxelAlongZ
G4double primaryEnergy
G4double energyLimit
G4double binWidth
G4int nBins
G4double nT
G4double dT
G4double nD
G4double dD
G4double nSecondaryT
G4double nSecondaryD
G4double dSecondaryT
G4double dSecondaryD
G4double nPrimaryT
G4double nPrimaryD
G4double dPrimaryT
G4double dPrimaryD
G4double * secondaryLetT
G4double * secondaryLetD
G4double * totalLetT
G4double * DtotalLetT
G4double * DtotalLetD
G4double * totalLetD
G4String nome_file
std::vector< ionLet > ionLetStore
Static Private Attributes
static HadrontherapyLet * instance = NULL
Detailed Description
Definition at line 61 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 61 of file HadrontherapyLet.hh
Constructor & Destructor Documentation
HadrontherapyLet::HadrontherapyLet (HadrontherapyDetectorConstruction * pDet) private
Definition at line 55 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 55 of file HadrontherapyLet.cc
References density, detectorMat, DtotalLetD, DtotalLetT, FatalException, G4Exception(), HadrontherapyMatrix::GetInstance(), G4RunManager::GetRunManager(), matrix, numberOfVoxelAlongX, numberOfVoxelAlongY, numberOfVoxelAlongZ, nVoxels, pPGA, totalLetD, and totalLetT.
Referenced by GetInstance().
HadrontherapyLet::~HadrontherapyLet ()
Definition at line 85 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 85 of file HadrontherapyLet.cc
References Clear(), DtotalLetD, DtotalLetT, totalLetD, and totalLetT.
Member Function Documentation
void HadrontherapyLet::Clear ()
Clear all stored data
Definition at line 103 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 103 of file HadrontherapyLet.cc
References ionLetStore.
Referenced by Initialize(), and ~HadrontherapyLet().
void HadrontherapyLet::Fill (G4int i, G4int j, G4int k, G4double DE, G4double DX)
void HadrontherapyLet::FillEnergySpectrum (G4int trackID, G4ParticleDefinition * particleDef, G4double ekinMean, G4Material * mat, G4double DE, G4double DEEletrons, G4double DX, G4int i, G4int j, G4int k)
Definition at line 114 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 114 of file HadrontherapyLet.cc
References A(), G4EmCalculator::ComputeElectronicDEDX(), doCalculation, DtotalLetD, DtotalLetT, ionLetStore, ionLet::letDD, ionLet::letDN, ionLet::letTD, ionLet::letTN, matrix, nVoxels, totalLetD, totalLetT, v, and Z.
HadrontherapyLet * HadrontherapyLet::GetInstance (HadrontherapyDetectorConstruction * pDet) static
Definition at line 43 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 43 of file HadrontherapyLet.cc
References HadrontherapyLet(), and instance.
HadrontherapyLet * HadrontherapyLet::GetInstance () static
Definition at line 50 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 50 of file HadrontherapyLet.cc
References instance.
Referenced by main(), HadrontherapyDetectorSD::ProcessHits(), HadrontherapyAnalysisFileMessenger::SetNewValue(), and HadrontherapyDetectorConstruction::UpdateGeometry().
void HadrontherapyLet::Initialize ()
Definition at line 95 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 95 of file HadrontherapyLet.cc
References Clear(), DtotalLetD, DtotalLetT, nVoxels, totalLetD, totalLetT, and v.
void HadrontherapyLet::LetOutput ()
Definition at line 201 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 201 of file HadrontherapyLet.cc
References DtotalLetD, DtotalLetT, ionLetStore, nVoxels, totalLetD, totalLetT, and v.
void HadrontherapyLet::StoreLetAscii ()
Definition at line 230 of file HadrontherapyLet.cc.
View newest version in sPHENIX GitHub at line 230 of file HadrontherapyLet.cc
References a, A(), G4VAnalysisManager::AddNtupleRow(), b, G4VAnalysisManager::CloseFile(), G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::CreateNtupleIColumn(), filename, G4VAnalysisManager::FillNtupleDColumn(), G4VAnalysisManager::FillNtupleIColumn(), G4VAnalysisManager::FinishNtuple(), G4endl, G4ToolsAnalysisManager::Instance(), ionLetStore, keV, left, matrix, numberOfVoxelAlongX, numberOfVoxelAlongY, numberOfVoxelAlongZ, ofs, G4VAnalysisManager::OpenFile(), G4VAnalysisManager::SetFirstHistoId(), G4VAnalysisManager::SetFirstNtupleId(), G4VAnalysisManager::SetVerboseLevel(), totalLetD, totalLetT, um, v, width, and G4VAnalysisManager::Write().
Member Data Documentation
G4double HadrontherapyLet::binWidth private
Definition at line 99 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 99 of file HadrontherapyLet.hh
G4double HadrontherapyLet::dD private
Definition at line 101 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 101 of file HadrontherapyLet.hh
G4double HadrontherapyLet::density private
Definition at line 92 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 92 of file HadrontherapyLet.hh
Referenced by HadrontherapyLet().
G4Material* HadrontherapyLet::detectorMat private
Definition at line 91 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 91 of file HadrontherapyLet.hh
Referenced by HadrontherapyLet().
G4bool HadrontherapyLet::doCalculation = false static
Definition at line 70 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 70 of file HadrontherapyLet.hh
Referenced by FillEnergySpectrum().
G4double HadrontherapyLet::dPrimaryD private
Definition at line 103 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 103 of file HadrontherapyLet.hh
G4double HadrontherapyLet::dPrimaryT private
Definition at line 103 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 103 of file HadrontherapyLet.hh
G4double HadrontherapyLet::dSecondaryD private
Definition at line 102 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 102 of file HadrontherapyLet.hh
G4double HadrontherapyLet::dSecondaryT private
Definition at line 102 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 102 of file HadrontherapyLet.hh
G4double HadrontherapyLet::dT private
Definition at line 101 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 101 of file HadrontherapyLet.hh
G4double * HadrontherapyLet::DtotalLetD private
Definition at line 104 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 104 of file HadrontherapyLet.hh
Referenced by FillEnergySpectrum(), HadrontherapyLet(), Initialize(), LetOutput(), and ~HadrontherapyLet().
G4double * HadrontherapyLet::DtotalLetT private
Definition at line 104 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 104 of file HadrontherapyLet.hh
Referenced by FillEnergySpectrum(), HadrontherapyLet(), Initialize(), LetOutput(), and ~HadrontherapyLet().
G4double HadrontherapyLet::energyLimit private
Definition at line 99 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 99 of file HadrontherapyLet.hh
G4String HadrontherapyLet::filename private
Definition at line 93 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 93 of file HadrontherapyLet.hh
Referenced by StoreLetAscii().
HadrontherapyLet * HadrontherapyLet::instance = NULL static private
Definition at line 88 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 88 of file HadrontherapyLet.hh
Referenced by GetInstance().
std::vector<ionLet> HadrontherapyLet::ionLetStore private
Definition at line 107 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 107 of file HadrontherapyLet.hh
Referenced by Clear(), FillEnergySpectrum(), LetOutput(), and StoreLetAscii().
HadrontherapyMatrix* HadrontherapyLet::matrix private
Definition at line 97 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 97 of file HadrontherapyLet.hh
Referenced by FillEnergySpectrum(), HadrontherapyLet(), and StoreLetAscii().
G4int HadrontherapyLet::nBins private
Definition at line 100 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 100 of file HadrontherapyLet.hh
G4double HadrontherapyLet::nD private
Definition at line 101 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 101 of file HadrontherapyLet.hh
G4String HadrontherapyLet::nome_file private
Definition at line 105 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 105 of file HadrontherapyLet.hh
G4double HadrontherapyLet::nPrimaryD private
Definition at line 103 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 103 of file HadrontherapyLet.hh
G4double HadrontherapyLet::nPrimaryT private
Definition at line 103 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 103 of file HadrontherapyLet.hh
G4double HadrontherapyLet::nSecondaryD private
Definition at line 102 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 102 of file HadrontherapyLet.hh
G4double HadrontherapyLet::nSecondaryT private
Definition at line 102 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 102 of file HadrontherapyLet.hh
G4double HadrontherapyLet::nT private
Definition at line 101 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 101 of file HadrontherapyLet.hh
G4int HadrontherapyLet::numberOfVoxelAlongX private
Definition at line 98 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 98 of file HadrontherapyLet.hh
Referenced by HadrontherapyLet(), and StoreLetAscii().
G4int HadrontherapyLet::numberOfVoxelAlongY private
Definition at line 98 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 98 of file HadrontherapyLet.hh
Referenced by HadrontherapyLet(), and StoreLetAscii().
G4int HadrontherapyLet::numberOfVoxelAlongZ private
Definition at line 98 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 98 of file HadrontherapyLet.hh
Referenced by HadrontherapyLet(), and StoreLetAscii().
G4int HadrontherapyLet::nVoxels private
Definition at line 98 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 98 of file HadrontherapyLet.hh
Referenced by FillEnergySpectrum(), HadrontherapyLet(), Initialize(), and LetOutput().
std::ofstream HadrontherapyLet::ofs private
Definition at line 95 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 95 of file HadrontherapyLet.hh
Referenced by StoreLetAscii().
HadrontherapyPrimaryGeneratorAction* HadrontherapyLet::pPGA private
Definition at line 89 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 89 of file HadrontherapyLet.hh
Referenced by HadrontherapyLet().
G4double HadrontherapyLet::primaryEnergy private
Definition at line 99 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 99 of file HadrontherapyLet.hh
G4double * HadrontherapyLet::secondaryLetD private
Definition at line 104 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 104 of file HadrontherapyLet.hh
G4double* HadrontherapyLet::secondaryLetT private
Definition at line 104 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 104 of file HadrontherapyLet.hh
std::ofstream HadrontherapyLet::stopFile private
Definition at line 96 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 96 of file HadrontherapyLet.hh
G4double * HadrontherapyLet::totalLetD private
Definition at line 104 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 104 of file HadrontherapyLet.hh
Referenced by FillEnergySpectrum(), HadrontherapyLet(), Initialize(), LetOutput(), StoreLetAscii(), and ~HadrontherapyLet().
G4double * HadrontherapyLet::totalLetT private
Definition at line 104 of file HadrontherapyLet.hh.
View newest version in sPHENIX GitHub at line 104 of file HadrontherapyLet.hh
Referenced by FillEnergySpectrum(), HadrontherapyLet(), Initialize(), LetOutput(), StoreLetAscii(), and ~HadrontherapyLet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/include/HadrontherapyLet.hh
geant4/tree/geant4-10.6-release/examples/advanced/hadrontherapy/src/HadrontherapyLet.cc