ECCE @ EIC Software: G4VelocityTable Class Reference
G4VelocityTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4VelocityTable.hh>
Public Member Functions
G4double Value (G4double theEnergy)
Static Public Member Functions
static G4VelocityTable * GetVelocityTable ()
static void SetVelocityTableProperties (G4double t_max, G4double t_min, G4int nbin)
static G4double GetMaxTOfVelocityTable ()
static G4double GetMinTOfVelocityTable ()
static G4int GetNbinOfVelocityTable ()
Private Types
typedef std::vector< G4double > G4VTDataVector
Private Member Functions
G4VelocityTable ()
~G4VelocityTable ()
size_t FindBinLocation (G4double theEnergy) const
G4double Interpolation () const
void PrepareVelocityTable ()
Private Attributes
G4double edgeMin
G4double edgeMax
size_t numberOfNodes
G4VTDataVector dataVector
G4VTDataVector binVector
G4VTDataVector secDerivative
G4double dBin
G4double baseBin
G4double lastEnergy
G4double lastValue
size_t lastBin
G4double maxT
G4double minT
G4int NbinT
Static Private Attributes
static G4ThreadLocal
G4VelocityTable * theInstance = nullptr
Friends
class G4ThreadLocalSingleton< G4VelocityTable >
Detailed Description
Definition at line 51 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VelocityTable.hh
Member Typedef Documentation
typedef std::vector<G4double> G4VelocityTable::G4VTDataVector private
Definition at line 58 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VelocityTable.hh
Constructor & Destructor Documentation
G4VelocityTable::G4VelocityTable () private
Definition at line 53 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VelocityTable.cc
References PrepareVelocityTable().
G4VelocityTable::~G4VelocityTable () private
Definition at line 64 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VelocityTable.cc
References binVector, and dataVector.
Member Function Documentation
size_t G4VelocityTable::FindBinLocation (G4double theEnergy) const private
Definition at line 108 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 108 of file G4VelocityTable.cc
References baseBin, dBin, and G4Log().
G4double G4VelocityTable::GetMaxTOfVelocityTable () static
Definition at line 198 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 198 of file G4VelocityTable.cc
References GetVelocityTable(), and maxT.
Referenced by G4Track::GetMaxTOfVelocityTable().
G4double G4VelocityTable::GetMinTOfVelocityTable () static
Definition at line 205 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 205 of file G4VelocityTable.cc
References GetVelocityTable(), and minT.
Referenced by G4Track::GetMinTOfVelocityTable().
G4int G4VelocityTable::GetNbinOfVelocityTable () static
Definition at line 212 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 212 of file G4VelocityTable.cc
References GetVelocityTable(), and NbinT.
Referenced by G4Track::GetNbinOfVelocityTable().
G4VelocityTable * G4VelocityTable::GetVelocityTable () static
Definition at line 162 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 162 of file G4VelocityTable.cc
References G4ThreadLocalSingleton< T >::Instance(), and theInstance.
Referenced by G4Track::G4Track(), GetMaxTOfVelocityTable(), GetMinTOfVelocityTable(), GetNbinOfVelocityTable(), SetVelocityTableProperties(), and G4Track::SetVelocityTableProperties().
G4double G4VelocityTable::Interpolation () const inline private
Definition at line 112 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VelocityTable.hh
References binVector, dataVector, lastBin, and lastEnergy.
Referenced by Value().
void G4VelocityTable::PrepareVelocityTable () private
Definition at line 73 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 73 of file G4VelocityTable.cc
References baseBin, binVector, source.hepunit::c_light, dataVector, dBin, edgeMax, edgeMin, G4Exp(), G4Log(), maxT, minT, NbinT, numberOfNodes, and T.
Referenced by G4VelocityTable(), and SetVelocityTableProperties().
void G4VelocityTable::SetVelocityTableProperties (G4double t_max, G4double t_min, G4int nbin) static
Definition at line 173 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 173 of file G4VelocityTable.cc
References G4Exception(), G4State_Idle, G4State_PreInit, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), GetVelocityTable(), JustWarning, maxT, minT, NbinT, PrepareVelocityTable(), and theInstance.
Referenced by G4Track::SetVelocityTableProperties().
G4double G4VelocityTable::Value (G4double theEnergy)
Definition at line 124 of file G4VelocityTable.cc.
View newest version in sPHENIX GitHub at line 124 of file G4VelocityTable.cc
References baseBin, binVector, dataVector, dBin, edgeMax, edgeMin, G4Log(), Interpolation(), lastBin, lastEnergy, lastValue, and numberOfNodes.
Referenced by G4Track::CalculateVelocity().
Friends And Related Function Documentation
friend class G4ThreadLocalSingleton< G4VelocityTable > friend
Definition at line 54 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VelocityTable.hh
Member Data Documentation
G4double G4VelocityTable::baseBin private
Definition at line 96 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 96 of file G4VelocityTable.hh
Referenced by FindBinLocation(), PrepareVelocityTable(), and Value().
G4VTDataVector G4VelocityTable::binVector private
Definition at line 92 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VelocityTable.hh
Referenced by Interpolation(), PrepareVelocityTable(), Value(), and ~G4VelocityTable().
G4VTDataVector G4VelocityTable::dataVector private
Definition at line 91 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VelocityTable.hh
Referenced by Interpolation(), PrepareVelocityTable(), Value(), and ~G4VelocityTable().
G4double G4VelocityTable::dBin private
Definition at line 95 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 95 of file G4VelocityTable.hh
Referenced by FindBinLocation(), PrepareVelocityTable(), and Value().
G4double G4VelocityTable::edgeMax private
Definition at line 87 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VelocityTable.hh
Referenced by PrepareVelocityTable(), and Value().
G4double G4VelocityTable::edgeMin private
Definition at line 86 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VelocityTable.hh
Referenced by PrepareVelocityTable(), and Value().
size_t G4VelocityTable::lastBin private
Definition at line 100 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 100 of file G4VelocityTable.hh
Referenced by Interpolation(), and Value().
G4double G4VelocityTable::lastEnergy private
Definition at line 98 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 98 of file G4VelocityTable.hh
Referenced by Interpolation(), and Value().
G4double G4VelocityTable::lastValue private
Definition at line 99 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 99 of file G4VelocityTable.hh
Referenced by Value().
G4double G4VelocityTable::maxT private
Definition at line 106 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 106 of file G4VelocityTable.hh
Referenced by GetMaxTOfVelocityTable(), PrepareVelocityTable(), and SetVelocityTableProperties().
G4double G4VelocityTable::minT private
Definition at line 107 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 107 of file G4VelocityTable.hh
Referenced by GetMinTOfVelocityTable(), PrepareVelocityTable(), and SetVelocityTableProperties().
G4int G4VelocityTable::NbinT private
Definition at line 108 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 108 of file G4VelocityTable.hh
Referenced by GetNbinOfVelocityTable(), PrepareVelocityTable(), and SetVelocityTableProperties().
size_t G4VelocityTable::numberOfNodes private
Definition at line 89 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VelocityTable.hh
Referenced by PrepareVelocityTable(), and Value().
G4VTDataVector G4VelocityTable::secDerivative private
Definition at line 93 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VelocityTable.hh
G4ThreadLocal G4VelocityTable * G4VelocityTable::theInstance = nullptr static private
Definition at line 105 of file G4VelocityTable.hh.
View newest version in sPHENIX GitHub at line 105 of file G4VelocityTable.hh
Referenced by GetVelocityTable(), and SetVelocityTableProperties().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4VelocityTable.hh
geant4/tree/geant4-10.6-release/source/track/src/G4VelocityTable.cc