ECCE @ EIC Software: G4VisCommandSceneAddArrow2D::Arrow2D Struct Reference
G4VisCommandSceneAddArrow2D::Arrow2D Struct Reference
Public Member Functions
Arrow2D (G4double x1, G4double y1, G4double x2, G4double y2, G4double width, const G4Colour &colour)
void operator() (G4VGraphicsScene &, const G4Transform3D &, const G4ModelingParameters *fpMp)
Public Attributes
G4Polyline fShaftPolyline
G4Polyline fHeadPolyline
G4double fWidth
G4Colour fColour
Detailed Description
Definition at line 67 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VisCommandsSceneAdd.hh
Constructor & Destructor Documentation
G4VisCommandSceneAddArrow2D::Arrow2D::Arrow2D (G4double x1, G4double y1, G4double x2, G4double y2, G4double width, const G4Colour & colour)
Definition at line 227 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 227 of file G4VisCommandsSceneAdd.cc
References deg, HepGeom::BasicVector3D< T >::rotateZ(), G4VisAttributes::SetColour(), G4VisAttributes::SetLineWidth(), and HepGeom::BasicVector3D< T >::unit().
Member Function Documentation
void G4VisCommandSceneAddArrow2D::Arrow2D::operator() (G4VGraphicsScene & sceneHandler, const G4Transform3D & , const G4ModelingParameters * fpMp)
Definition at line 250 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 250 of file G4VisCommandsSceneAdd.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives2D(), and G4VGraphicsScene::EndPrimitives2D().
Member Data Documentation
G4Colour G4VisCommandSceneAddArrow2D::Arrow2D::fColour
Definition at line 75 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VisCommandsSceneAdd.hh
G4Polyline G4VisCommandSceneAddArrow2D::Arrow2D::fHeadPolyline
Definition at line 73 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VisCommandsSceneAdd.hh
G4Polyline G4VisCommandSceneAddArrow2D::Arrow2D::fShaftPolyline
Definition at line 72 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 72 of file G4VisCommandsSceneAdd.hh
G4double G4VisCommandSceneAddArrow2D::Arrow2D::fWidth
Definition at line 74 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VisCommandsSceneAdd.hh
The documentation for this struct was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsSceneAdd.cc