ECCE @ EIC Software: G4UnitsCategory Class Reference
G4UnitsCategory Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4UnitsTable.hh>
Public Member Functions
G4UnitsCategory (const G4String &name)
~G4UnitsCategory ()
G4bool operator== (const G4UnitsCategory &) const
G4bool operator!= (const G4UnitsCategory &) const
const G4String & GetName () const
G4UnitsContainer & GetUnitsList ()
G4int GetNameMxLen () const
G4int GetSymbMxLen () const
void UpdateNameMxLen (G4int len)
void UpdateSymbMxLen (G4int len)
void PrintCategory ()
Private Member Functions
G4UnitsCategory (const G4UnitsCategory &)
G4UnitsCategory & operator= (const G4UnitsCategory &)
Private Attributes
G4String Name
G4UnitsContainer UnitsList
G4int NameMxLen
G4int SymbMxLen
Detailed Description
Definition at line 139 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 139 of file G4UnitsTable.hh
Constructor & Destructor Documentation
G4UnitsCategory::G4UnitsCategory (const G4String & name) explicit
Definition at line 421 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 421 of file G4UnitsTable.cc
G4UnitsCategory::~G4UnitsCategory ()
Definition at line 428 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 428 of file G4UnitsTable.cc
References UnitsList.
G4UnitsCategory::G4UnitsCategory (const G4UnitsCategory & right) private
Definition at line 439 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 439 of file G4UnitsTable.cc
References right.
Member Function Documentation
const G4String& G4UnitsCategory::GetName () const inline
Referenced by export_G4UnitsTable().
G4int G4UnitsCategory::GetNameMxLen () const inline
Referenced by export_G4UnitsTable().
G4int G4UnitsCategory::GetSymbMxLen () const inline
Referenced by export_G4UnitsTable().
G4UnitsContainer& G4UnitsCategory::GetUnitsList () inline
Referenced by export_G4UnitsTable().
G4bool G4UnitsCategory::operator!= (const G4UnitsCategory & right) const
Definition at line 467 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 467 of file G4UnitsTable.cc
G4UnitsCategory & G4UnitsCategory::operator= (const G4UnitsCategory & right) private
Definition at line 446 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 446 of file G4UnitsTable.cc
References Name, NameMxLen, SymbMxLen, and UnitsList.
G4bool G4UnitsCategory::operator== (const G4UnitsCategory & right) const
Definition at line 460 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 460 of file G4UnitsTable.cc
void G4UnitsCategory::PrintCategory ()
Definition at line 474 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 474 of file G4UnitsTable.cc
References G4cout, G4endl, Name, and UnitsList.
Referenced by export_G4UnitsTable().
void G4UnitsCategory::UpdateNameMxLen (G4int len) inline
Referenced by export_G4UnitsTable().
void G4UnitsCategory::UpdateSymbMxLen (G4int len) inline
Referenced by export_G4UnitsTable().
Member Data Documentation
G4String G4UnitsCategory::Name private
Definition at line 165 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 165 of file G4UnitsTable.hh
Referenced by operator=(), and PrintCategory().
G4int G4UnitsCategory::NameMxLen private
Definition at line 167 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 167 of file G4UnitsTable.hh
Referenced by operator=().
G4int G4UnitsCategory::SymbMxLen private
Definition at line 168 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 168 of file G4UnitsTable.hh
Referenced by operator=().
G4UnitsContainer G4UnitsCategory::UnitsList private
Definition at line 166 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 166 of file G4UnitsTable.hh
Referenced by operator=(), PrintCategory(), and ~G4UnitsCategory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4UnitsTable.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4UnitsTable.cc