ECCE @ EIC Software: CexmcRunAction Class Reference
CexmcRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcRunAction.hh>
Public Member Functions
CexmcRunAction (CexmcPhysicsManager *physicsManager)
G4Run * GenerateRun (void)
void EndOfRunAction (const G4Run *run)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void BeginOfRunAction (const G4Run *aRun)
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Static Public Member Functions
static void PrintResults (const CexmcNmbOfHitsInRanges &nmbOfHitsSampled, const CexmcNmbOfHitsInRanges &nmbOfHitsSampledFull, const CexmcNmbOfHitsInRanges &nmbOfHitsTriggeredRealRange, const CexmcNmbOfHitsInRanges &nmbOfHitsTriggeredRecRange, const CexmcNmbOfHitsInRanges &nmbOfOrphanHits, const CexmcAngularRangeList &angularRanges, G4int nmbOfFalseHitsTriggeredEDT, G4int nmbOfFalseHitsTriggeredRec)
Private Attributes
CexmcPhysicsManager * physicsManager
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 54 of file CexmcRunAction.hh.
View newest version in sPHENIX GitHub at line 54 of file CexmcRunAction.hh
Constructor & Destructor Documentation
CexmcRunAction::CexmcRunAction (CexmcPhysicsManager * physicsManager) explicit
Definition at line 56 of file CexmcRunAction.cc.
View newest version in sPHENIX GitHub at line 56 of file CexmcRunAction.cc
Member Function Documentation
void CexmcRunAction::EndOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
Definition at line 230 of file CexmcRunAction.cc.
View newest version in sPHENIX GitHub at line 230 of file CexmcRunAction.cc
References CexmcWeirdException, G4cout, G4endl, CexmcRun::GetNmbOfFalseHitsTriggeredEDT(), CexmcRun::GetNmbOfFalseHitsTriggeredRec(), CexmcRun::GetNmbOfHitsSampled(), CexmcRun::GetNmbOfHitsSampledFull(), CexmcRun::GetNmbOfHitsTriggeredRealRange(), CexmcRun::GetNmbOfHitsTriggeredRecRange(), CexmcRun::GetNmbOfOrphanHits(), CexmcPhysicsManager::GetProductionModel(), physicsManager, and PrintResults().
G4Run * CexmcRunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 62 of file CexmcRunAction.cc.
View newest version in sPHENIX GitHub at line 62 of file CexmcRunAction.cc
void CexmcRunAction::PrintResults (const CexmcNmbOfHitsInRanges & nmbOfHitsSampled, const CexmcNmbOfHitsInRanges & nmbOfHitsSampledFull, const CexmcNmbOfHitsInRanges & nmbOfHitsTriggeredRealRange, const CexmcNmbOfHitsInRanges & nmbOfHitsTriggeredRecRange, const CexmcNmbOfHitsInRanges & nmbOfOrphanHits, const CexmcAngularRangeList & angularRanges, G4int nmbOfFalseHitsTriggeredEDT, G4int nmbOfFalseHitsTriggeredRec) static
Definition at line 68 of file CexmcRunAction.cc.
View newest version in sPHENIX GitHub at line 68 of file CexmcRunAction.cc
References G4cout, G4endl, GetAngularGaps(), k, CLHEP::prec, and G4INCL::CrossSections::total().
Referenced by EndOfRunAction().
Member Data Documentation
CexmcPhysicsManager* CexmcRunAction::physicsManager private
Definition at line 76 of file CexmcRunAction.hh.
View newest version in sPHENIX GitHub at line 76 of file CexmcRunAction.hh
Referenced by EndOfRunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcRunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcRunAction.cc