ECCE @ EIC Software: G4NuclearRadii Class Reference
G4NuclearRadii Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4NuclearRadii.hh>
Static Public Member Functions
static G4double ExplicitRadius (G4int Z, G4int A)
static G4double Radius (G4int Z, G4int A)
static G4double RadiusRMS (G4int Z, G4int A)
static G4double RadiusNNGG (G4int Z, G4int A)
static G4double RadiusECS (G4int Z, G4int A)
static G4double RadiusHNGG (G4int A)
static G4double RadiusKNGG (G4int A)
static G4double RadiusND (G4int A)
static G4double RadiusCB (G4int Z, G4int A)
static G4double ParticleRadius (const G4ParticleDefinition *)
static G4double CoulombFactor (const G4ParticleDefinition *theParticle, const G4ParticleDefinition *nucleon, G4double ekin)
static G4double CoulombFactor (G4int Z, G4int A, const G4ParticleDefinition *theParticle, G4double ekin)
Static Public Attributes
static G4Pow * fG4pow = G4Pow::GetInstance()
static const G4double r0 [93]
Detailed Description
Definition at line 43 of file G4NuclearRadii.hh.
View newest version in sPHENIX GitHub at line 43 of file G4NuclearRadii.hh
Member Function Documentation
G4double G4NuclearRadii::CoulombFactor (const G4ParticleDefinition * theParticle, const G4ParticleDefinition * nucleon, G4double ekin) static
Definition at line 169 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 169 of file G4NuclearRadii.cc
References fAlpha, CLHEP::fermi, fInvep, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), and ParticleRadius().
Referenced by G4BGGNucleonElasticXS::CoulombFactor(), G4BGGNucleonInelasticXS::CoulombFactor(), G4BGGPionElasticXS::CoulombFactorPiPlus(), G4BGGPionInelasticXS::CoulombFactorPiPlus(), G4HadronNucleonXsc::HadronNucleonXscNS(), and G4HadronNucleonXsc::KaonNucleonXscVG().
G4double G4NuclearRadii::CoulombFactor (G4int Z, G4int A, const G4ParticleDefinition * theParticle, G4double ekin) static
Definition at line 190 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 190 of file G4NuclearRadii.cc
References fAlpha, fInvep, G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), ParticleRadius(), and RadiusCB().
G4double G4NuclearRadii::ExplicitRadius (G4int Z, G4int A) static
Definition at line 43 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 43 of file G4NuclearRadii.cc
References CLHEP::fermi, and Acts::IntegrationTest::R.
Referenced by Radius(), RadiusCB(), RadiusNNGG(), and RadiusRMS().
G4double G4NuclearRadii::ParticleRadius (const G4ParticleDefinition * p) static
Definition at line 158 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 158 of file G4NuclearRadii.cc
References kdfinder::abs(), CLHEP::fermi, G4ParticleDefinition::GetPDGEncoding(), pdg, and Acts::IntegrationTest::R.
Referenced by CoulombFactor().
G4double G4NuclearRadii::Radius (G4int Z, G4int A) static
Definition at line 59 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 59 of file G4NuclearRadii.cc
References ExplicitRadius(), CLHEP::fermi, fG4pow, G4Pow::powZ(), Acts::IntegrationTest::R, x, y, and G4Pow::Z13().
Referenced by G4ComponentGGNuclNuclXsc::ComputeCrossSections().
G4double G4NuclearRadii::RadiusCB (G4int Z, G4int A) static
Definition at line 148 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 148 of file G4NuclearRadii.cc
References ExplicitRadius(), CLHEP::fermi, fG4pow, min, Acts::IntegrationTest::R, r0, z, and G4Pow::Z13().
Referenced by CoulombFactor(), G4CoulombBarrier::G4CoulombBarrier(), and G4CoulombBarrier::GetCoulombBarrier().
G4double G4NuclearRadii::RadiusECS (G4int Z, G4int A) static
Definition at line 101 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 101 of file G4NuclearRadii.cc
References A(), c, c1, c2, CLHEP::fermi, fG4pow, G4Pow::powN(), Acts::IntegrationTest::R, x, y, Z, and G4Pow::Z13().
G4double G4NuclearRadii::RadiusHNGG (G4int A) static
Definition at line 122 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 122 of file G4NuclearRadii.cc
References CLHEP::fermi, fG4pow, G4Exp(), Acts::IntegrationTest::R, and G4Pow::Z13().
Referenced by G4ComponentGGHadronNucleusXsc::ComputeCrossSections().
G4double G4NuclearRadii::RadiusKNGG (G4int A) static
Definition at line 133 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 133 of file G4NuclearRadii.cc
References CLHEP::fermi, fG4pow, and G4Pow::Z13().
Referenced by G4ComponentGGHadronNucleusXsc::ComputeCrossSections().
G4double G4NuclearRadii::RadiusND (G4int A) static
Definition at line 138 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 138 of file G4NuclearRadii.cc
References CLHEP::fermi, fG4pow, Acts::IntegrationTest::R, x, and G4Pow::Z13().
G4double G4NuclearRadii::RadiusNNGG (G4int Z, G4int A) static
Definition at line 87 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 87 of file G4NuclearRadii.cc
References ExplicitRadius(), CLHEP::fermi, fG4pow, G4Exp(), Acts::IntegrationTest::R, and G4Pow::Z13().
G4double G4NuclearRadii::RadiusRMS (G4int Z, G4int A) static
Definition at line 78 of file G4NuclearRadii.cc.
View newest version in sPHENIX GitHub at line 78 of file G4NuclearRadii.cc
References ExplicitRadius(), CLHEP::fermi, fG4pow, G4Pow::powZ(), and Acts::IntegrationTest::R.
Member Data Documentation
G4Pow * G4NuclearRadii::fG4pow = G4Pow::GetInstance() static
Definition at line 90 of file G4NuclearRadii.hh.
View newest version in sPHENIX GitHub at line 90 of file G4NuclearRadii.hh
Referenced by Radius(), RadiusCB(), RadiusECS(), RadiusHNGG(), RadiusKNGG(), RadiusND(), RadiusNNGG(), and RadiusRMS().
const G4double G4NuclearRadii::r0 static
Initial value:
= {
 1.2,
 1.3, 1.3, 1.3, 1.3,1.17,1.54,1.65,1.71, 1.7,1.75,
 1.7,1.57,1.53, 1.4, 1.3,1.30,1.44, 1.4, 1.4, 1.4,
 1.4, 1.4,1.46, 1.4, 1.4,1.46,1.55, 1.5,1.38,1.48,
 1.4, 1.4, 1.4,1.46, 1.4, 1.4, 1.4, 1.4, 1.4,1.45,
 1.4, 1.4, 1.4, 1.4, 1.4, 1.4,1.45,1.48, 1.4,1.52,
1.46, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.5,
 1.4, 1.4, 1.4, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.4,
 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3,1.33,1.43,
 1.3,1.32,1.34, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3,
 1.3, 1.3}
Definition at line 91 of file G4NuclearRadii.hh.
View newest version in sPHENIX GitHub at line 91 of file G4NuclearRadii.hh
Referenced by RadiusCB().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4NuclearRadii.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4NuclearRadii.cc