ECCE @ EIC Software: HistoManager Class Reference
HistoManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/HistoManager.hh>
Public Member Functions
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
void Book ()
void Save ()
void FillHisto (G4int id, G4double e, G4double weight=1.0)
void Normalize (G4int id, G4double fac)
void FillNtuple (G4double EnergyAbs, G4double EnergyGap, G4double TrackLAbs, G4double TrackLGap)
void PrintStatistic ()
HistoManager ()
~HistoManager ()
void Book ()
void Save ()
void FillHisto (G4int id, G4double bin, G4double weight=1.0)
void Normalize (G4int id, G4double fac)
void FillNtuple (G4double energyAbs, G4double energyGap, G4double trackLAbs, G4double trackLGap)
void PrintStatistic ()
HistoManager ()
~HistoManager ()
void Book ()
void Save ()
void FillHisto (G4int id, G4double bin, G4double weight=1.0)
void Normalize (G4int id, G4double fac)
void FillNtuple (G4double EnergyAbs, G4double EnergyGap, G4double TrackLAbs, G4double TrackLGap)
void PrintStatistic ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
void Book ()
void Save ()
void SetHisto (G4int, G4int, G4double, G4double, const G4String &unit="none")
void FillHisto (G4int id, G4double e, G4double weight=1.0)
void Normalize (G4int id, G4double fac)
void PrintHisto (G4int)
void SetFileName (const G4String &name)
G4bool HistoExist (G4int id)
G4String GetTitle (G4int id)
G4int GetNbins (G4int id)
G4double GetVmin (G4int id)
G4double GetVmax (G4int id)
G4double GetHistoUnit (G4int id)
G4double GetBinWidth (G4int id)
G4int GetHistoID (G4int id)
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
~HistoManager ()
void BookHisto ()
void BeginOfRun ()
void EndOfRun (G4int runID)
void BeginOfEvent ()
void EndOfEvent ()
void ScoreNewTrack (const G4Track *aTrack)
void AddEnergy (G4double edep, G4int idx, G4int copyNo)
void AddDeltaElectron (const G4DynamicParticle *)
void AddPhoton (const G4DynamicParticle *)
void ResetTrackLength ()
void AddPositron (const G4DynamicParticle *)
void SetVerbose (G4int val)
G4int GetVerbose () const
void SetHistoNumber (G4int val)
void SetFirstEventToDebug (G4int val)
G4int FirstEventToDebug () const
void SetLastEventToDebug (G4int val)
G4int LastEventToDebug () const
void SetMaxEnergy (G4double val)
G4double GetMaxEnergy () const
void AddStep ()
void SetBeamEnergy (G4double val)
void SetEdepAndRMS (G4int, G4ThreeVector)
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
void BeginOfRun ()
void EndOfRun ()
void SetVerbose (G4int val)
void SetParticleName (const G4String &)
void SetElementName (const G4String &)
void SetNumberOfBinsE (G4int val)
void SetNumberOfBinsP (G4int val)
void SetMinKinEnergy (G4double val)
void SetMaxKinEnergy (G4double val)
void SetMinMomentum (G4double val)
void SetMaxMomentum (G4double val)
void SetHistoName (G4String &val)
void SetTargetMaterial (const G4Material *p)
~HistoManager ()
void BookHisto ()
void BeginOfRun ()
void EndOfRun ()
void BeginOfEvent ()
void EndOfEvent ()
void Fill (G4int id, G4double x, G4double w)
void ScoreNewTrack (const G4Track *)
void AddTargetStep (const G4Step *)
void AddLeakingParticle (const G4Track *)
void SetVerbose (G4int val)
void SetTargetLength (G4double val)
void SetNumberOfSlices (G4int val)
void SetNumberOfBinsE (G4int val)
void SetDefaultBeamPositionFlag (G4bool f)
void SetMaxEnergyDeposit (G4double val)
G4double Length () const
G4bool DefaultBeamPosition () const
G4int NumberOfSlices () const
G4int GetVerbose () const
~HistoManager ()
void BookHisto ()
void BeginOfRun ()
void EndOfRun ()
void BeginOfEvent ()
void EndOfEvent ()
void Fill (G4int id, G4double x, G4double w)
void ScoreNewTrack (const G4Track *)
void AddTargetStep (const G4Step *)
void SetVerbose (G4int val)
void SetIonPhysics (const G4String &)
void SetTargetMaterial (const G4Material *mat)
void SetTargetLength (G4double val)
void SetNumberOfSlices (G4int val)
void SetNumberOfBinsE (G4int val)
G4double Length () const
G4int NumberOfSlices () const
G4int GetVerbose () const
void SetDefaultBeamPositionFlag (G4bool f)
G4bool DefaultBeamPosition () const
void SetMaxEnergyDeposit (G4double val)
void SetPhysicsList (G4VModularPhysicsList *p)
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
void Update (DetectorConstruction *det, bool bForceActivation=false)
std::vector< G4int > GetHistoIdentifiers () const
void DumpHistoParameters ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
HistoManager ()
~HistoManager ()
Static Public Member Functions
static HistoManager * GetPointer ()
static HistoManager * GetPointer ()
static HistoManager * GetPointer ()
Private Member Functions
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void SaveAscii ()
void Book ()
void Book ()
void Book ()
HistoManager ()
void Book ()
void Book ()
HistoManager ()
HistoManager ()
void Initialise ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
void Book ()
Private Attributes
G4String fFileName
G4bool fFactoryOn
TFile * fRootFile
TH1D * fHisto [kMaxHisto]
TTree * fNtuple1
TTree * fNtuple2
G4double fEabs
G4double fEgap
G4double fLabs
G4double fLgap
AIDA::IAnalysisFactory * fAF
AIDA::ITree * fTree
AIDA::IHistogram1D * fHisto [kMaxHisto]
AIDA::ITuple * fNtuple1
AIDA::ITuple * fNtuple2
G4String fileName [2]
G4bool factoryOn
G4int fNbHist
G4int fHistId [kMaxHisto]
G4H1 * fHistPt [kMaxHisto]
G4bool fExist [kMaxHisto]
G4String fLabel [kMaxHisto]
G4String fTitle [kMaxHisto]
G4int fNbins [kMaxHisto]
G4double fVmin [kMaxHisto]
G4double fVmax [kMaxHisto]
G4double fUnit [kMaxHisto]
G4double fWidth [kMaxHisto]
G4bool fAscii [kMaxHisto]
HistoMessenger * fHistoMessenger
const G4ParticleDefinition * fGamma
const G4ParticleDefinition * fElectron
const G4ParticleDefinition * fPositron
G4int fNHisto
G4int fVerbose
G4int fEvt1
G4int fEvt2
G4double fBeamEnergy
G4double fMaxEnergy
G4double fMaxEnergyAbs
G4double fTrackLength
G4double fStep
G4bool fTrackAbs
G4int fEvt
G4int fElec
G4int fPosit
G4int fGam
G4int fLowe
G4int fBinsE
G4int fBinsEA
G4int fBinsED
G4double fEabs1
G4double fEabs2
G4double fEabs3
G4double fEabs4
G4double fE [25]
G4DataVector fEvertex
G4DataVector fNvertex
G4DataVector fBrem
G4DataVector fPhot
G4DataVector fComp
G4DataVector fConv
G4double fEdeptrue [3]
G4double fRmstrue [3]
G4double fLimittrue [3]
G4double fEdep [6]
G4double fErms [6]
G4double fEdeptr [6]
G4double fErmstr [6]
G4int fStat [6]
G4int fNmax
Histo * fHisto
HistoManagerMessenger * fMessenger
G4AnalysisManager * fAnalysisManager
const G4ParticleDefinition * fNeutron
const G4Material * fTargetMaterial
G4String fParticleName
G4String fElementName
G4double fMinKinEnergy
G4double fMaxKinEnergy
G4double fMinMomentum
G4double fMaxMomentum
G4int fBinsP
G4String fHistoName
const G4ParticleDefinition * fPrimaryDef
G4double fEdepMax
G4double fEdepEvt
G4double fEdepEM
G4double fEdepPI
G4double fEdepP
G4double fEdepSum
G4double fEdepSum2
G4double fLength
G4double fAbsZ0
G4double fPrimaryKineticEnergy
G4int fNBinsE
G4int fNSlices
G4int fNevt
G4int fNelec
G4int fNposit
G4int fNgam
G4int fNprot_leak
G4int fNpiofNleak
G4int fNcpions
G4int fNpi0
G4int fNkaons
G4int fNmuons
G4int fNions
G4int fNdeut
G4int fNalpha
G4int fNneutron
G4int fNproton
G4int fNaproton
G4int fNneu_forw
G4int fNneu_leak
G4int fNneu_back
G4int fNstep
G4bool fBeamFlag
G4bool fHistoBooked
G4VModularPhysicsList * fPhysList
G4VPhysicsConstructor * fIonPhysics
const G4Material * fMaterial
std::vector< G4int > fHisto
G4int fNBinsZ
G4int fNBinsR
G4double fAbsorberZ
G4double fAbsorberR
G4double fScoreZ
G4double fStepZ
G4double fStepR
G4double fStepE
Static Private Attributes
static HistoManager * fManager = 0
Detailed Description
Definition at line 43 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 43 of file HistoManager.hh
Constructor & Destructor Documentation
HistoManager::HistoManager ()
Definition at line 38 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 38 of file HistoManager.cc
References Book().
Referenced by GetPointer().
HistoManager::~HistoManager ()
Definition at line 46 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 46 of file HistoManager.cc
References G4ToolsAnalysisManager::Instance().
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager () private
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager () private
HistoManager::~HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager () private
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
HistoManager::HistoManager ()
HistoManager::~HistoManager ()
Member Function Documentation
void HistoManager::AddDeltaElectron (const G4DynamicParticle * elec)
Definition at line 525 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 525 of file HistoManager.cc
References e, fElec, fHisto, G4DynamicParticle::GetKineticEnergy(), and MeV.
Referenced by ScoreNewTrack().
void HistoManager::AddEnergy (G4double edep, G4int idx, G4int copyNo)
Definition at line 486 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 486 of file HistoManager.cc
References edep, fE, fEabs1, fEabs2, fEabs3, fEabs4, fEvertex, fNvertex, fVerbose, G4cout, G4endl, keV, and n.
void HistoManager::AddLeakingParticle (const G4Track * track)
Definition at line 468 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 468 of file HistoManager.cc
References kdfinder::abs(), fAbsZ0, fHisto, fNeutron, fNneu_back, fNneu_forw, fNneu_leak, fNpiofNleak, fNprot_leak, G4Track::GetDefinition(), G4StepPoint::GetKineticEnergy(), G4StepPoint::GetMomentumDirection(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4Track::GetStep(), MeV, G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), pos(), G4Proton::Proton(), G4InuclParticleNames::sp, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by CheckVolumeSD::ProcessHits().
void HistoManager::AddPhoton (const G4DynamicParticle * ph)
Definition at line 534 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 534 of file HistoManager.cc
References e, fGam, fHisto, G4DynamicParticle::GetKineticEnergy(), and MeV.
Referenced by ScoreNewTrack().
void HistoManager::AddPositron (const G4DynamicParticle *) inline
Definition at line 93 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 93 of file HistoManager.hh
References fPosit.
Referenced by ScoreNewTrack().
void HistoManager::AddStep () inline
Definition at line 105 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 105 of file HistoManager.hh
References fStep.
void HistoManager::AddTargetStep (const G4Step *)
void HistoManager::AddTargetStep (const G4Step * step)
Definition at line 419 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 419 of file HistoManager.cc
References G4AntiProton::AntiProton(), source.hepunit::c_light, DBL_MIN, G4Electron::Electron(), fAbsZ0, fEdep, fEdepEM, fEdepP, fEdepPI, fHisto, fNstep, fVerbose, G4cout, G4endl, G4Gamma::Gamma(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), G4StepPoint::GetVelocity(), G4Track::GetWeight(), keV, MeV, mm, G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), pos(), G4Positron::Positron(), G4Proton::Proton(), CLHEP::Hep3Vector::z(), and z.
void HistoManager::BeginOfEvent ()
void HistoManager::BeginOfEvent ()
void HistoManager::BeginOfEvent ()
Definition at line 308 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 308 of file HistoManager.cc
References fE, fEabs1, fEabs2, fEabs3, fEabs4, fEvertex, fEvt, and fNvertex.
void HistoManager::BeginOfRun ()
void HistoManager::BeginOfRun ()
void HistoManager::BeginOfRun ()
void HistoManager::BeginOfRun ()
Definition at line 128 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 128 of file HistoManager.cc
References fBrem, fComp, fConv, fEdep, fEdeptr, fEdeptrue, fElec, fErms, fErmstr, fEvt, fGam, fHisto, fLimittrue, fLowe, fNHisto, fNmax, fPhot, fPosit, fRmstrue, fStat, fStep, fVerbose, G4cout, and G4endl.
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
const G4int kMaxHisto1 = 24, kMaxHisto2 = 44;
Definition at line 53 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 53 of file HistoManager.cc
References G4VAnalysisManager::CreateH1(), fFileName, G4ToolsAnalysisManager::Instance(), k, kMaxHisto, G4VAnalysisManager::SetActivation(), G4VAnalysisManager::SetFileName(), G4VAnalysisManager::SetH1Activation(), G4VAnalysisManager::SetVerboseLevel(), and title().
Referenced by HistoManager().
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book ()
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book () private
void HistoManager::Book ()
void HistoManager::Book () private
void HistoManager::Book ()
void HistoManager::Book () private
void HistoManager::Book ()
void HistoManager::Book () private
void HistoManager::BookHisto ()
void HistoManager::BookHisto ()
void HistoManager::BookHisto ()
Definition at line 108 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 108 of file HistoManager.cc
References fBinsE, fBinsEA, fBinsED, fHisto, fMaxEnergy, fMaxEnergyAbs, and MeV.
G4bool HistoManager::DefaultBeamPosition () const inline
Definition at line 96 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 96 of file HistoManager.hh
References fBeamFlag.
G4bool HistoManager::DefaultBeamPosition () const inline
Definition at line 99 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 99 of file HistoManager.hh
References fBeamFlag.
void HistoManager::DumpHistoParameters ()
Definition at line 192 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 192 of file HistoManager.cc
References fHisto, G4cout, G4endl, G4VAnalysisManager::GetH1Nbins(), G4VAnalysisManager::GetH1Title(), G4VAnalysisManager::GetH1Width(), G4VAnalysisManager::GetH1Xmax(), G4VAnalysisManager::GetH1Xmin(), G4ToolsAnalysisManager::Instance(), int(), title(), width, xmax, and xmin.
void HistoManager::EndOfEvent ()
void HistoManager::EndOfEvent ()
void HistoManager::EndOfEvent ()
Definition at line 325 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 325 of file HistoManager.cc
References kdfinder::abs(), fBeamEnergy, fE, fEabs1, fEabs2, fEabs3, fEabs4, fEdep, fEdeptr, fEdeptrue, fErms, fErmstr, fEvt, fHisto, fLimittrue, fLowe, fNvertex, fRmstrue, fStat, fVerbose, G4cout, and G4endl.
void HistoManager::EndOfRun ()
Definition at line 144 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 144 of file HistoManager.cc
References barn, G4VAnalysisManager::CloseFile(), cm2, Acts::VectorHelpers::cross(), E, e, e1, fAnalysisManager, fBinsE, fBinsP, fElementName, G4VAnalysisManager::FillH1(), G4NistManager::FindOrBuildElement(), G4NistManager::FindOrBuildMaterial(), G4ParticleTable::FindParticle(), fMaxKinEnergy, fMaxMomentum, fMinKinEnergy, fMinMomentum, fNeutron, fParticleName, fTargetMaterial, fVerbose, Acts::UnitConstants::g, G4cout, G4endl, G4HadronicProcessStore::GetCaptureCrossSectionPerAtom(), G4HadronicProcessStore::GetChargeExchangeCrossSectionPerAtom(), G4Material::GetDensity(), G4HadronicProcessStore::GetElasticCrossSectionPerAtom(), G4HadronicProcessStore::GetElasticCrossSectionPerVolume(), G4HadronicProcessStore::GetFissionCrossSectionPerAtom(), G4HadronicProcessStore::GetInelasticCrossSectionPerAtom(), G4HadronicProcessStore::GetInelasticCrossSectionPerVolume(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4Material::GetRadlen(), GeV, G4HadronicProcessStore::Instance(), G4NistManager::Instance(), mass, mat, MeV, particle, CLHEP::prec, G4VAnalysisManager::Write(), and x.
void HistoManager::EndOfRun ()
void HistoManager::EndOfRun ()
void HistoManager::EndOfRun (G4int runID)
Definition at line 174 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 174 of file HistoManager.cc
References EmAcceptance::BeginOfAcceptance(), DBL_MAX, e, EmAcceptance::EmAcceptanceGauss(), EmAcceptance::EndOfAcceptance(), f, fBeamEnergy, fBrem, fComp, fConv, fEdep, fEdeptr, fEdeptrue, fElec, fErms, fErmstr, fEvt, fGam, fHisto, fLimittrue, fLowe, fNHisto, fNmax, fPhot, fPosit, fRmstrue, fStat, fStep, G4cout, G4endl, GeV, n1, r, x, xx, and y.
void HistoManager::Fill (G4int id, G4double x, G4double w)
void HistoManager::Fill (G4int id, G4double x, G4double w)
Definition at line 530 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 530 of file HistoManager.cc
References fHisto.
void HistoManager::FillHisto (G4int id, G4double e, G4double weight = 1.0)
Definition at line 130 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 130 of file HistoManager.cc
References G4VAnalysisManager::FillH1(), and G4ToolsAnalysisManager::Instance().
void HistoManager::FillHisto (G4int id, G4double bin, G4double weight = 1.0)
void HistoManager::FillHisto (G4int id, G4double e, G4double weight = 1.0)
void HistoManager::FillHisto (G4int id, G4double bin, G4double weight = 1.0)
void HistoManager::FillNtuple (G4double EnergyAbs, G4double EnergyGap, G4double TrackLAbs, G4double TrackLGap)
Definition at line 147 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 147 of file HistoManager.cc
References G4VAnalysisManager::AddNtupleRow(), G4VAnalysisManager::FillNtupleDColumn(), and G4ToolsAnalysisManager::Instance().
void HistoManager::FillNtuple (G4double energyAbs, G4double energyGap, G4double trackLAbs, G4double trackLGap)
void HistoManager::FillNtuple (G4double EnergyAbs, G4double EnergyGap, G4double TrackLAbs, G4double TrackLGap)
G4int HistoManager::FirstEventToDebug () const inline
Definition at line 99 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 99 of file HistoManager.hh
References fEvt1.
G4double HistoManager::GetBinWidth (G4int id) inline
Definition at line 69 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 69 of file HistoManager.hh
References fWidth.
Referenced by RunAction::ComputeTheory().
G4int HistoManager::GetHistoID (G4int id) inline
Definition at line 70 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 70 of file HistoManager.hh
References fHistId.
Referenced by RunAction::ComputeTheory().
std::vector<G4int> HistoManager::GetHistoIdentifiers () const inline
Definition at line 55 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 55 of file HistoManager.hh
References fHisto.
Referenced by Run::Run().
G4double HistoManager::GetHistoUnit (G4int id) inline
Definition at line 68 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 68 of file HistoManager.hh
References fUnit.
G4double HistoManager::GetMaxEnergy () const inline
Definition at line 104 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 104 of file HistoManager.hh
References fMaxEnergy.
G4int HistoManager::GetNbins (G4int id) inline
Definition at line 65 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 65 of file HistoManager.hh
References fNbins.
Referenced by RunAction::ComputeTheory().
static HistoManager* HistoManager::GetPointer () static
static HistoManager* HistoManager::GetPointer () static
HistoManager * HistoManager::GetPointer () static
Definition at line 63 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 63 of file HistoManager.cc
References fManager, and HistoManager().
Referenced by CheckVolumeSD::CheckVolumeSD(), and main().
G4String HistoManager::GetTitle (G4int id) inline
Definition at line 64 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 64 of file HistoManager.hh
References fTitle.
G4int HistoManager::GetVerbose () const inline
Definition at line 93 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 93 of file HistoManager.hh
References fVerbose.
G4int HistoManager::GetVerbose () const inline
Definition at line 95 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 95 of file HistoManager.hh
References fVerbose.
G4int HistoManager::GetVerbose () const inline
Definition at line 101 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 101 of file HistoManager.hh
References fVerbose.
G4double HistoManager::GetVmax (G4int id) inline
Definition at line 67 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 67 of file HistoManager.hh
References fVmax.
Referenced by RunAction::ComputeTheory().
G4double HistoManager::GetVmin (G4int id) inline
Definition at line 66 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 66 of file HistoManager.hh
References fVmin.
Referenced by RunAction::ComputeTheory().
G4bool HistoManager::HistoExist (G4int id) inline
Definition at line 63 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 63 of file HistoManager.hh
References fExist.
Referenced by RunAction::ComputeTheory().
void HistoManager::Initialise () private
Definition at line 124 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 124 of file HistoManager.cc
References fAbsZ0, fEdepEvt, fEdepSum, fEdepSum2, fLength, fNalpha, fNaproton, fNcpions, fNdeut, fNelec, fNevt, fNgam, fNions, fNkaons, fNmuons, fNneutron, fNpi0, fNposit, fNproton, and fNstep.
G4int HistoManager::LastEventToDebug () const inline
Definition at line 101 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 101 of file HistoManager.hh
References fEvt2.
G4double HistoManager::Length () const inline
Definition at line 90 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 90 of file HistoManager.hh
References fLength.
G4double HistoManager::Length () const inline
Definition at line 98 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 98 of file HistoManager.hh
References fLength.
void HistoManager::Normalize (G4int id, G4double fac)
Definition at line 138 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 138 of file HistoManager.cc
References G4ToolsAnalysisManager::GetH1(), h1, and G4ToolsAnalysisManager::Instance().
void HistoManager::Normalize (G4int id, G4double fac)
void HistoManager::Normalize (G4int id, G4double fac)
void HistoManager::Normalize (G4int id, G4double fac)
G4int HistoManager::NumberOfSlices () const inline
Definition at line 91 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 91 of file HistoManager.hh
References fNSlices.
G4int HistoManager::NumberOfSlices () const inline
Definition at line 100 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 100 of file HistoManager.hh
References fNSlices.
void HistoManager::PrintHisto (G4int ih)
Definition at line 209 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 209 of file HistoManager.cc
References fAscii, G4cout, and G4endl.
Referenced by HistoMessenger::SetNewValue().
void HistoManager::PrintStatistic ()
Definition at line 163 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 163 of file HistoManager.cc
References fFactoryOn, G4BestUnit, G4cout, G4endl, G4ToolsAnalysisManager::GetH1(), G4VAnalysisManager::GetH1Name(), G4VAnalysisManager::GetNofH1s(), h1, and G4ToolsAnalysisManager::Instance().
void HistoManager::PrintStatistic ()
void HistoManager::PrintStatistic ()
void HistoManager::ResetTrackLength () inline
Definition at line 92 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 92 of file HistoManager.hh
References fTrackAbs, and fTrackLength.
Referenced by ScoreNewTrack().
void HistoManager::Save ()
Definition at line 114 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 114 of file HistoManager.cc
References G4VAnalysisManager::CloseFile(), fFactoryOn, G4cout, G4endl, G4ToolsAnalysisManager::Instance(), and G4VAnalysisManager::Write().
void HistoManager::Save ()
void HistoManager::Save ()
void HistoManager::Save ()
void HistoManager::SaveAscii () private
Definition at line 221 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 221 of file HistoManager.cc
References fAscii, fHistPt, fileName, fNbins, fTitle, G4cout, G4endl, and kMaxHisto.
void HistoManager::ScoreNewTrack (const G4Track *)
void HistoManager::ScoreNewTrack (const G4Track * aTrack)
Definition at line 401 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 401 of file HistoManager.cc
References AddDeltaElectron(), AddPhoton(), AddPositron(), dir, fBrem, fBremsstrahlung, fComp, fComptonScattering, fConv, fElectron, fGamma, fGammaConversion, fPhot, fPhotoElectricEffect, fPositron, fVerbose, G4cout, G4endl, G4lrint(), G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetParentID(), G4ParticleDefinition::GetPDGMass(), G4VProcess::GetProcessSubType(), G4Track::GetVertexPosition(), G4Element::GetZ(), mass, MeV, particle, pid, pos(), ResetTrackLength(), and Z.
void HistoManager::ScoreNewTrack (const G4Track *)
void HistoManager::SetBeamEnergy (G4double val) inline
Definition at line 108 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 108 of file HistoManager.hh
References fBeamEnergy.
void HistoManager::SetDefaultBeamPositionFlag (G4bool f) inline
Definition at line 95 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 95 of file HistoManager.hh
References f, and fBeamFlag.
void HistoManager::SetDefaultBeamPositionFlag (G4bool f) inline
Definition at line 95 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 95 of file HistoManager.hh
References f, and fBeamFlag.
void HistoManager::SetEdepAndRMS (G4int i, G4ThreeVector val)
Definition at line 543 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 543 of file HistoManager.cc
References fEdeptrue, fLimittrue, and fRmstrue.
void HistoManager::SetElementName (const G4String & name) inline
Definition at line 119 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 119 of file HistoManager.hh
References fElementName.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetFileName (const G4String & name) inline
Definition at line 62 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 62 of file HistoManager.hh
References fileName.
Referenced by HistoMessenger::SetNewValue().
void HistoManager::SetFirstEventToDebug (G4int val) inline
Definition at line 98 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 98 of file HistoManager.hh
References fEvt1.
void HistoManager::SetHisto (G4int ih, G4int nbins, G4double vmin, G4double vmax, const G4String & unit = "none")
Definition at line 142 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 142 of file HistoManager.cc
References fExist, fLabel, fNbHist, fNbins, fTitle, fUnit, fVmax, fVmin, fWidth, G4cout, G4endl, G4UnitDefinition::GetValueOf(), and title().
Referenced by HistoMessenger::SetNewValue().
void HistoManager::SetHistoName (G4String & val) inline
Definition at line 154 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 154 of file HistoManager.hh
References fHistoName.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetHistoNumber (G4int val) inline
Definition at line 96 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 96 of file HistoManager.hh
References fNHisto.
void HistoManager::SetIonPhysics (const G4String & nam)
Definition at line 452 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 452 of file HistoManager.cc
References fIonPhysics, fPhysList, G4cout, G4endl, G4RunManager::GetRunManager(), G4RunManager::PhysicsHasBeenModified(), and G4VModularPhysicsList::ReplacePhysics().
void HistoManager::SetLastEventToDebug (G4int val) inline
Definition at line 100 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 100 of file HistoManager.hh
References fEvt2.
void HistoManager::SetMaxEnergy (G4double val) inline
Definition at line 103 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 103 of file HistoManager.hh
References fMaxEnergy.
void HistoManager::SetMaxEnergyDeposit (G4double val) inline
Definition at line 96 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 96 of file HistoManager.hh
References fEdepMax.
void HistoManager::SetMaxEnergyDeposit (G4double val) inline
Definition at line 98 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 98 of file HistoManager.hh
References fEdepMax.
void HistoManager::SetMaxKinEnergy (G4double val) inline
Definition at line 139 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 139 of file HistoManager.hh
References fMaxKinEnergy, and fMinKinEnergy.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetMaxMomentum (G4double val) inline
Definition at line 149 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 149 of file HistoManager.hh
References fMaxMomentum, and fMinMomentum.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetMinKinEnergy (G4double val) inline
Definition at line 134 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 134 of file HistoManager.hh
References fMaxKinEnergy, and fMinKinEnergy.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetMinMomentum (G4double val) inline
Definition at line 144 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 144 of file HistoManager.hh
References fMaxMomentum, and fMinMomentum.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetNumberOfBinsE (G4int val) inline
Definition at line 124 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 124 of file HistoManager.hh
References fBinsE.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetNumberOfBinsE (G4int val) inline
Definition at line 88 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 88 of file HistoManager.hh
References fNBinsE.
void HistoManager::SetNumberOfBinsE (G4int val) inline
Definition at line 94 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 94 of file HistoManager.hh
References fNBinsE.
void HistoManager::SetNumberOfBinsP (G4int val) inline
Definition at line 129 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 129 of file HistoManager.hh
References fBinsP.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetNumberOfSlices (G4int val) inline
Definition at line 87 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 87 of file HistoManager.hh
References fNSlices.
void HistoManager::SetNumberOfSlices (G4int val) inline
Definition at line 93 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 93 of file HistoManager.hh
References fNSlices.
void HistoManager::SetParticleName (const G4String & name) inline
Definition at line 114 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 114 of file HistoManager.hh
References fParticleName.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::SetPhysicsList (G4VModularPhysicsList * p) inline
Definition at line 100 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 100 of file HistoManager.hh
References fPhysList.
Referenced by main().
void HistoManager::SetTargetLength (G4double val) inline
Definition at line 86 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 86 of file HistoManager.hh
References fLength.
void HistoManager::SetTargetLength (G4double val) inline
Definition at line 92 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 92 of file HistoManager.hh
References fLength.
void HistoManager::SetTargetMaterial (const G4Material * mat) inline
Definition at line 85 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 85 of file HistoManager.hh
References fMaterial, and mat.
void HistoManager::SetTargetMaterial (const G4Material * p) inline
Definition at line 159 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 159 of file HistoManager.hh
References fTargetMaterial.
void HistoManager::SetVerbose (G4int val)
void HistoManager::SetVerbose (G4int val)
void HistoManager::SetVerbose (G4int val)
void HistoManager::SetVerbose (G4int val) inline
Definition at line 94 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 94 of file HistoManager.hh
References fVerbose.
Referenced by HistoManagerMessenger::SetNewValue().
void HistoManager::Update (DetectorConstruction * det, bool bForceActivation = false)
Definition at line 133 of file HistoManager.cc.
View newest version in sPHENIX GitHub at line 133 of file HistoManager.cc
References fAbsorberR, fAbsorberZ, fHisto, fMaxEnergy, fNBinsE, fNBinsR, fNBinsZ, DetectorConstruction::GetAbsorberR(), DetectorConstruction::GetAbsorberZ(), DetectorConstruction::GetMaxEnergy(), DetectorConstruction::GetNumberDivE(), DetectorConstruction::GetNumberDivR(), DetectorConstruction::GetNumberDivZ(), G4ToolsAnalysisManager::Instance(), int(), G4VAnalysisManager::IsActive(), MeV, mm, G4VAnalysisManager::SetActivation(), G4VAnalysisManager::SetH1(), G4VAnalysisManager::SetH1Activation(), and v.
Referenced by Run::Run().
Member Data Documentation
G4double HistoManager::fAbsorberR private
Definition at line 66 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 66 of file HistoManager.hh
Referenced by Update().
G4double HistoManager::fAbsorberZ private
Definition at line 65 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 65 of file HistoManager.hh
Referenced by Update().
G4double HistoManager::fAbsZ0 private
Definition at line 118 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 118 of file HistoManager.hh
Referenced by AddLeakingParticle(), AddTargetStep(), and Initialise().
G4bool HistoManager::factoryOn private
Definition at line 77 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 77 of file HistoManager.hh
AIDA::IAnalysisFactory* HistoManager::fAF private
Definition at line 69 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 69 of file HistoManager.hh
G4AnalysisManager* HistoManager::fAnalysisManager private
Definition at line 94 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 94 of file HistoManager.hh
Referenced by EndOfRun().
G4bool HistoManager::fAscii[kMaxHisto] private
Definition at line 90 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 90 of file HistoManager.hh
Referenced by PrintHisto(), and SaveAscii().
G4double HistoManager::fBeamEnergy private
Definition at line 126 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 126 of file HistoManager.hh
Referenced by EndOfEvent(), EndOfRun(), and SetBeamEnergy().
G4bool HistoManager::fBeamFlag private
Definition at line 147 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 147 of file HistoManager.hh
Referenced by DefaultBeamPosition(), and SetDefaultBeamPositionFlag().
G4int HistoManager::fBinsE private
Definition at line 141 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 141 of file HistoManager.hh
Referenced by BookHisto(), EndOfRun(), and SetNumberOfBinsE().
G4int HistoManager::fBinsEA private
Definition at line 141 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 141 of file HistoManager.hh
Referenced by BookHisto().
G4int HistoManager::fBinsED private
Definition at line 141 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 141 of file HistoManager.hh
Referenced by BookHisto().
G4int HistoManager::fBinsP private
Definition at line 109 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 109 of file HistoManager.hh
Referenced by EndOfRun(), and SetNumberOfBinsP().
G4DataVector HistoManager::fBrem private
Definition at line 147 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 147 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfRun(), and ScoreNewTrack().
G4DataVector HistoManager::fComp private
Definition at line 149 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 149 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfRun(), and ScoreNewTrack().
G4DataVector HistoManager::fConv private
Definition at line 150 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 150 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfRun(), and ScoreNewTrack().
G4double HistoManager::fE[25] private
Definition at line 144 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 144 of file HistoManager.hh
Referenced by AddEnergy(), BeginOfEvent(), and EndOfEvent().
G4double HistoManager::fEabs private
Definition at line 71 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 71 of file HistoManager.hh
G4double HistoManager::fEabs1 private
Definition at line 143 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 143 of file HistoManager.hh
Referenced by AddEnergy(), BeginOfEvent(), and EndOfEvent().
G4double HistoManager::fEabs2 private
Definition at line 143 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 143 of file HistoManager.hh
Referenced by AddEnergy(), BeginOfEvent(), and EndOfEvent().
G4double HistoManager::fEabs3 private
Definition at line 143 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 143 of file HistoManager.hh
Referenced by AddEnergy(), BeginOfEvent(), and EndOfEvent().
G4double HistoManager::fEabs4 private
Definition at line 143 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 143 of file HistoManager.hh
Referenced by AddEnergy(), BeginOfEvent(), and EndOfEvent().
G4double HistoManager::fEdep[6] private
Definition at line 155 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 155 of file HistoManager.hh
Referenced by AddTargetStep(), BeginOfRun(), EndOfEvent(), and EndOfRun().
G4double HistoManager::fEdepEM private
Definition at line 112 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 112 of file HistoManager.hh
Referenced by AddTargetStep().
G4double HistoManager::fEdepEvt private
Definition at line 111 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 111 of file HistoManager.hh
Referenced by Initialise().
G4double HistoManager::fEdepMax private
Definition at line 110 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 110 of file HistoManager.hh
Referenced by SetMaxEnergyDeposit().
G4double HistoManager::fEdepP private
Definition at line 114 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 114 of file HistoManager.hh
Referenced by AddTargetStep().
G4double HistoManager::fEdepPI private
Definition at line 113 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 113 of file HistoManager.hh
Referenced by AddTargetStep().
G4double HistoManager::fEdepSum private
Definition at line 115 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 115 of file HistoManager.hh
Referenced by Initialise().
G4double HistoManager::fEdepSum2 private
Definition at line 116 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 116 of file HistoManager.hh
Referenced by Initialise().
G4double HistoManager::fEdeptr[6] private
Definition at line 157 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 157 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
G4double HistoManager::fEdeptrue[3] private
Definition at line 152 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 152 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfEvent(), EndOfRun(), and SetEdepAndRMS().
G4double HistoManager::fEgap private
Definition at line 72 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 72 of file HistoManager.hh
G4int HistoManager::fElec private
Definition at line 135 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 135 of file HistoManager.hh
Referenced by AddDeltaElectron(), BeginOfRun(), and EndOfRun().
const G4ParticleDefinition* HistoManager::fElectron private
Definition at line 118 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 118 of file HistoManager.hh
Referenced by ScoreNewTrack().
G4String HistoManager::fElementName private
Definition at line 100 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 100 of file HistoManager.hh
Referenced by EndOfRun(), and SetElementName().
G4double HistoManager::fErms[6] private
Definition at line 156 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 156 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
G4double HistoManager::fErmstr[6] private
Definition at line 158 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 158 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
G4DataVector HistoManager::fEvertex private
Definition at line 145 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 145 of file HistoManager.hh
Referenced by AddEnergy(), and BeginOfEvent().
G4int HistoManager::fEvt private
Definition at line 134 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 134 of file HistoManager.hh
Referenced by BeginOfEvent(), BeginOfRun(), EndOfEvent(), and EndOfRun().
G4int HistoManager::fEvt1 private
Definition at line 123 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 123 of file HistoManager.hh
Referenced by FirstEventToDebug(), and SetFirstEventToDebug().
G4int HistoManager::fEvt2 private
Definition at line 124 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 124 of file HistoManager.hh
Referenced by LastEventToDebug(), and SetLastEventToDebug().
G4bool HistoManager::fExist[kMaxHisto] private
Definition at line 82 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 82 of file HistoManager.hh
Referenced by HistoExist(), and SetHisto().
G4bool HistoManager::fFactoryOn private
Definition at line 63 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 63 of file HistoManager.hh
Referenced by PrintStatistic(), and Save().
G4String HistoManager::fFileName private
Definition at line 52 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 52 of file HistoManager.hh
Referenced by Book().
G4int HistoManager::fGam private
Definition at line 137 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 137 of file HistoManager.hh
Referenced by AddPhoton(), BeginOfRun(), and EndOfRun().
const G4ParticleDefinition* HistoManager::fGamma private
Definition at line 117 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 117 of file HistoManager.hh
Referenced by ScoreNewTrack().
G4int HistoManager::fHistId[kMaxHisto] private
Definition at line 80 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 80 of file HistoManager.hh
Referenced by GetHistoID().
std::vector<G4int> HistoManager::fHisto private
Definition at line 60 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 60 of file HistoManager.hh
Histo * HistoManager::fHisto private
Definition at line 67 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 67 of file HistoManager.hh
Referenced by AddDeltaElectron(), AddLeakingParticle(), AddPhoton(), AddTargetStep(), BeginOfRun(), BookHisto(), DumpHistoParameters(), EndOfEvent(), EndOfRun(), Fill(), GetHistoIdentifiers(), and Update().
AIDA::IHistogram1D* HistoManager::fHisto[kMaxHisto] private
Definition at line 72 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 72 of file HistoManager.hh
Histo* HistoManager::fHisto private
Definition at line 162 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 162 of file HistoManager.hh
G4bool HistoManager::fHistoBooked private
Definition at line 148 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 148 of file HistoManager.hh
HistoMessenger* HistoManager::fHistoMessenger private
Definition at line 92 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 92 of file HistoManager.hh
G4String HistoManager::fHistoName private
Definition at line 111 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 111 of file HistoManager.hh
Referenced by SetHistoName().
G4H1* HistoManager::fHistPt[kMaxHisto] private
Definition at line 81 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 81 of file HistoManager.hh
Referenced by SaveAscii().
G4String HistoManager::fileName[2] private
Definition at line 76 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 76 of file HistoManager.hh
Referenced by SaveAscii(), and SetFileName().
G4VPhysicsConstructor* HistoManager::fIonPhysics private
Definition at line 110 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 110 of file HistoManager.hh
Referenced by SetIonPhysics().
G4String HistoManager::fLabel[kMaxHisto] private
Definition at line 83 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 83 of file HistoManager.hh
Referenced by SetHisto().
G4double HistoManager::fLabs private
Definition at line 73 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 73 of file HistoManager.hh
G4double HistoManager::fLength private
Definition at line 117 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 117 of file HistoManager.hh
Referenced by Initialise(), Length(), and SetTargetLength().
G4double HistoManager::fLgap private
Definition at line 74 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 74 of file HistoManager.hh
G4double HistoManager::fLimittrue[3] private
Definition at line 154 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 154 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfEvent(), EndOfRun(), and SetEdepAndRMS().
G4int HistoManager::fLowe private
Definition at line 140 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 140 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
HistoManager * HistoManager::fManager = 0 static private
Definition at line 115 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 115 of file HistoManager.hh
Referenced by GetPointer().
const G4Material* HistoManager::fMaterial private
Definition at line 113 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 113 of file HistoManager.hh
Referenced by SetTargetMaterial().
G4double HistoManager::fMaxEnergy private
Definition at line 127 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 127 of file HistoManager.hh
Referenced by BookHisto(), GetMaxEnergy(), SetMaxEnergy(), and Update().
G4double HistoManager::fMaxEnergyAbs private
Definition at line 128 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 128 of file HistoManager.hh
Referenced by BookHisto().
G4double HistoManager::fMaxKinEnergy private
Definition at line 103 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 103 of file HistoManager.hh
Referenced by EndOfRun(), SetMaxKinEnergy(), and SetMinKinEnergy().
G4double HistoManager::fMaxMomentum private
Definition at line 105 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 105 of file HistoManager.hh
Referenced by EndOfRun(), SetMaxMomentum(), and SetMinMomentum().
HistoManagerMessenger* HistoManager::fMessenger private
Definition at line 93 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 93 of file HistoManager.hh
G4double HistoManager::fMinKinEnergy private
Definition at line 102 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 102 of file HistoManager.hh
Referenced by EndOfRun(), SetMaxKinEnergy(), and SetMinKinEnergy().
G4double HistoManager::fMinMomentum private
Definition at line 104 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 104 of file HistoManager.hh
Referenced by EndOfRun(), SetMaxMomentum(), and SetMinMomentum().
G4int HistoManager::fNalpha private
Definition at line 137 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 137 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNaproton private
Definition at line 140 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 140 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNbHist private
Definition at line 79 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 79 of file HistoManager.hh
Referenced by SetHisto().
G4int HistoManager::fNbins[kMaxHisto] private
Definition at line 85 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 85 of file HistoManager.hh
Referenced by GetNbins(), SaveAscii(), and SetHisto().
G4int HistoManager::fNBinsE private
Definition at line 122 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 122 of file HistoManager.hh
Referenced by SetNumberOfBinsE(), and Update().
G4int HistoManager::fNBinsR private
Definition at line 63 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 63 of file HistoManager.hh
Referenced by Update().
G4int HistoManager::fNBinsZ private
Definition at line 63 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 63 of file HistoManager.hh
Referenced by Update().
G4int HistoManager::fNcpions private
Definition at line 131 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 131 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNdeut private
Definition at line 136 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 136 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNelec private
Definition at line 126 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 126 of file HistoManager.hh
Referenced by Initialise().
const G4ParticleDefinition * HistoManager::fNeutron private
Definition at line 96 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 96 of file HistoManager.hh
Referenced by AddLeakingParticle(), and EndOfRun().
G4int HistoManager::fNevt private
Definition at line 125 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 125 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNgam private
Definition at line 128 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 128 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNHisto private
Definition at line 121 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 121 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfRun(), and SetHistoNumber().
G4int HistoManager::fNions private
Definition at line 135 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 135 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNkaons private
Definition at line 133 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 133 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNmax private
Definition at line 160 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 160 of file HistoManager.hh
Referenced by BeginOfRun(), and EndOfRun().
G4int HistoManager::fNmuons private
Definition at line 134 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 134 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNneu_back private
Definition at line 143 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 143 of file HistoManager.hh
Referenced by AddLeakingParticle().
G4int HistoManager::fNneu_forw private
Definition at line 141 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 141 of file HistoManager.hh
Referenced by AddLeakingParticle().
G4int HistoManager::fNneu_leak private
Definition at line 142 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 142 of file HistoManager.hh
Referenced by AddLeakingParticle().
G4int HistoManager::fNneutron private
Definition at line 138 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 138 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNpi0 private
Definition at line 132 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 132 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNpiofNleak private
Definition at line 130 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 130 of file HistoManager.hh
Referenced by AddLeakingParticle().
G4int HistoManager::fNposit private
Definition at line 127 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 127 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNprot_leak private
Definition at line 129 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 129 of file HistoManager.hh
Referenced by AddLeakingParticle().
G4int HistoManager::fNproton private
Definition at line 139 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 139 of file HistoManager.hh
Referenced by Initialise().
G4int HistoManager::fNSlices private
Definition at line 123 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 123 of file HistoManager.hh
Referenced by NumberOfSlices(), and SetNumberOfSlices().
G4int HistoManager::fNstep private
Definition at line 144 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 144 of file HistoManager.hh
Referenced by AddTargetStep(), and Initialise().
TTree* HistoManager::fNtuple1 private
Definition at line 68 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 68 of file HistoManager.hh
AIDA::ITuple* HistoManager::fNtuple1 private
Definition at line 73 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 73 of file HistoManager.hh
TTree* HistoManager::fNtuple2 private
Definition at line 69 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 69 of file HistoManager.hh
AIDA::ITuple* HistoManager::fNtuple2 private
Definition at line 74 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 74 of file HistoManager.hh
G4DataVector HistoManager::fNvertex private
Definition at line 146 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 146 of file HistoManager.hh
Referenced by AddEnergy(), BeginOfEvent(), and EndOfEvent().
G4String HistoManager::fParticleName private
Definition at line 99 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 99 of file HistoManager.hh
Referenced by EndOfRun(), and SetParticleName().
G4DataVector HistoManager::fPhot private
Definition at line 148 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 148 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfRun(), and ScoreNewTrack().
G4VModularPhysicsList* HistoManager::fPhysList private
Definition at line 109 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 109 of file HistoManager.hh
Referenced by SetIonPhysics(), and SetPhysicsList().
G4int HistoManager::fPosit private
Definition at line 136 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 136 of file HistoManager.hh
Referenced by AddPositron(), BeginOfRun(), and EndOfRun().
const G4ParticleDefinition* HistoManager::fPositron private
Definition at line 119 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 119 of file HistoManager.hh
Referenced by ScoreNewTrack().
const G4ParticleDefinition * HistoManager::fPrimaryDef private
Definition at line 107 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 107 of file HistoManager.hh
G4double HistoManager::fPrimaryKineticEnergy private
Definition at line 119 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 119 of file HistoManager.hh
G4double HistoManager::fRmstrue[3] private
Definition at line 153 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 153 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfEvent(), EndOfRun(), and SetEdepAndRMS().
TFile* HistoManager::fRootFile private
Definition at line 66 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 66 of file HistoManager.hh
G4double HistoManager::fScoreZ private
Definition at line 67 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 67 of file HistoManager.hh
G4int HistoManager::fStat[6] private
Definition at line 159 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 159 of file HistoManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
G4double HistoManager::fStep private
Definition at line 131 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 131 of file HistoManager.hh
Referenced by AddStep(), BeginOfRun(), and EndOfRun().
G4double HistoManager::fStepE private
Definition at line 69 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 69 of file HistoManager.hh
G4double HistoManager::fStepR private
Definition at line 69 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 69 of file HistoManager.hh
G4double HistoManager::fStepZ private
Definition at line 69 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 69 of file HistoManager.hh
const G4Material* HistoManager::fTargetMaterial private
Definition at line 97 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 97 of file HistoManager.hh
Referenced by EndOfRun(), and SetTargetMaterial().
G4String HistoManager::fTitle[kMaxHisto] private
Definition at line 84 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 84 of file HistoManager.hh
Referenced by GetTitle(), SaveAscii(), and SetHisto().
G4bool HistoManager::fTrackAbs private
Definition at line 133 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 133 of file HistoManager.hh
Referenced by ResetTrackLength().
G4double HistoManager::fTrackLength private
Definition at line 130 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 130 of file HistoManager.hh
Referenced by ResetTrackLength().
AIDA::ITree* HistoManager::fTree private
Definition at line 70 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 70 of file HistoManager.hh
G4double HistoManager::fUnit[kMaxHisto] private
Definition at line 88 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 88 of file HistoManager.hh
Referenced by GetHistoUnit(), and SetHisto().
G4int HistoManager::fVerbose private
Definition at line 122 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 122 of file HistoManager.hh
Referenced by AddEnergy(), AddTargetStep(), BeginOfRun(), EndOfEvent(), EndOfRun(), GetVerbose(), ScoreNewTrack(), and SetVerbose().
G4double HistoManager::fVmax[kMaxHisto] private
Definition at line 87 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 87 of file HistoManager.hh
Referenced by GetVmax(), and SetHisto().
G4double HistoManager::fVmin[kMaxHisto] private
Definition at line 86 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 86 of file HistoManager.hh
Referenced by GetVmin(), and SetHisto().
G4double HistoManager::fWidth[kMaxHisto] private
Definition at line 89 of file HistoManager.hh.
View newest version in sPHENIX GitHub at line 89 of file HistoManager.hh
Referenced by GetBinWidth(), and SetHisto().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx01/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx02/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx03/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr00/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/include/HistoManager.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx01/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx02/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx03/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/particleGun/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr00/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr02/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay01/src/HistoManager.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/src/HistoManager.cc