ECCE @ EIC Software: G4Analysis Namespace Reference
G4Analysis Namespace Reference
Typedefs
using G4ToolsBaseHisto = tools::histo::base_histo< double, unsigned int, unsigned int, double, double >
Functions
G4ToolsAnalysisManager * ManagerInstance (const G4String &outputType)
G4int GetNbins (const G4ToolsBaseHisto &baseHisto, G4int dimension)
G4double GetMin (const G4ToolsBaseHisto &baseHisto, G4int dimension)
G4double GetMax (const G4ToolsBaseHisto &baseHisto, G4int dimension)
G4double GetWidth (const G4ToolsBaseHisto &baseHisto, G4int dimension, const G4String &hnType)
G4bool SetTitle (G4ToolsBaseHisto &baseHisto, const G4String &title)
G4bool SetAxisTitle (G4ToolsBaseHisto &baseHisto, G4int dimension, const G4String &title)
G4String GetTitle (const G4ToolsBaseHisto &baseHisto)
G4String GetAxisTitle (const G4ToolsBaseHisto &baseHisto, G4int dimension, const G4String &hnType)
G4bool CheckNbins (G4int nbins)
G4bool CheckMinMax (G4double xmin, G4double xmax, const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4bool CheckEdges (const std::vector< G4double > &edges)
G4bool CheckName (const G4String &name, const G4String &objectType)
G4double GetUnitValue (const G4String &unit)
void UpdateTitle (G4String &title, const G4String &unitName, const G4String &fcnName)
void Tokenize (const G4String &line, std::vector< G4String > &tokens)
template<typename T , typename... Args>
std::unique_ptr< T > make_unique (Args &&...args)
G4AnalysisOutput GetOutput (const G4String &outputName, G4bool warn=true)
G4String GetOutputName (G4AnalysisOutput outputType)
G4BinScheme GetBinScheme (const G4String &binSchemeName)
void ComputeEdges (G4int nbins, G4double xmin, G4double xmax, G4double unit, G4Fcn fcn, G4BinScheme, std::vector< G4double > &edges)
void ComputeEdges (const std::vector< G4double > &edges, G4double unit, G4Fcn fcn, std::vector< G4double > &newEdges)
G4Fcn GetFunction (const G4String &fcnName)
Variables
const G4int kX = 0
const G4int kY = 1
const G4int kZ = 2
const G4int kInvalidId = -1
Typedef Documentation
using G4Analysis::G4ToolsBaseHisto = typedef tools::histo::base_histo<double, unsigned int, unsigned int, double, double>
Definition at line 42 of file G4BaseHistoUtilities.hh.
View newest version in sPHENIX GitHub at line 42 of file G4BaseHistoUtilities.hh
Function Documentation
G4bool G4Analysis::CheckEdges (const std::vector< G4double > & edges)
Definition at line 119 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 119 of file G4AnalysisUtilities.cc
References G4endl, G4Exception(), and JustWarning.
Referenced by G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateH3(), G4VAnalysisManager::CreateP1(), G4VAnalysisManager::CreateP2(), G4VAnalysisManager::SetH1(), G4VAnalysisManager::SetH2(), G4VAnalysisManager::SetH3(), G4VAnalysisManager::SetP1(), and G4VAnalysisManager::SetP2().
G4bool G4Analysis::CheckMinMax (G4double xmin, G4double xmax, const G4String & fcnName = "none", const G4String & binSchemeName = "linear")
Definition at line 77 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 77 of file G4AnalysisUtilities.cc
References G4endl, G4Exception(), GetBinScheme(), and JustWarning.
Referenced by G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateH3(), G4VAnalysisManager::CreateP1(), G4VAnalysisManager::CreateP2(), G4VAnalysisManager::SetH1(), G4VAnalysisManager::SetH2(), G4VAnalysisManager::SetH3(), G4VAnalysisManager::SetP1(), and G4VAnalysisManager::SetP2().
G4bool G4Analysis::CheckName (const G4String & name, const G4String & objectType)
Definition at line 135 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 135 of file G4AnalysisUtilities.cc
References G4endl, G4Exception(), and JustWarning.
Referenced by G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateH3(), G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::CreateNtupleFColumn(), G4VAnalysisManager::CreateNtupleIColumn(), G4VAnalysisManager::CreateNtupleSColumn(), G4VAnalysisManager::CreateP1(), and G4VAnalysisManager::CreateP2().
G4bool G4Analysis::CheckNbins (G4int nbins)
Definition at line 61 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 61 of file G4AnalysisUtilities.cc
References G4endl, G4Exception(), and JustWarning.
Referenced by G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateH3(), G4VAnalysisManager::CreateP1(), G4VAnalysisManager::CreateP2(), G4VAnalysisManager::SetH1(), G4VAnalysisManager::SetH2(), G4VAnalysisManager::SetH3(), G4VAnalysisManager::SetP1(), and G4VAnalysisManager::SetP2().
void G4Analysis::ComputeEdges (G4int nbins, G4double xmin, G4double xmax, G4double unit, G4Fcn fcn, G4BinScheme binScheme, std::vector< G4double > & edges)
Definition at line 55 of file G4BinScheme.cc.
View newest version in sPHENIX GitHub at line 55 of file G4BinScheme.cc
References dx, G4endl, G4Exception(), and JustWarning.
void G4Analysis::ComputeEdges (const std::vector< G4double > & edges, G4double unit, G4Fcn fcn, std::vector< G4double > & newEdges)
Definition at line 97 of file G4BinScheme.cc.
View newest version in sPHENIX GitHub at line 97 of file G4BinScheme.cc
G4String G4Analysis::GetAxisTitle (const G4ToolsBaseHisto & baseHisto, G4int dimension, const G4String & hnType)
Definition at line 109 of file G4BaseHistoUtilities.cc.
View newest version in sPHENIX GitHub at line 109 of file G4BaseHistoUtilities.cc
References G4Exception(), JustWarning, kX, kY, kZ, and title().
Referenced by G4H1ToolsManager::GetH1XAxisTitle(), G4H1ToolsManager::GetH1YAxisTitle(), G4H2ToolsManager::GetH2XAxisTitle(), G4H2ToolsManager::GetH2YAxisTitle(), G4H2ToolsManager::GetH2ZAxisTitle(), G4H3ToolsManager::GetH3XAxisTitle(), G4H3ToolsManager::GetH3YAxisTitle(), G4H3ToolsManager::GetH3ZAxisTitle(), G4P1ToolsManager::GetP1XAxisTitle(), G4P1ToolsManager::GetP1YAxisTitle(), G4P2ToolsManager::GetP2XAxisTitle(), G4P2ToolsManager::GetP2YAxisTitle(), and G4P2ToolsManager::GetP2ZAxisTitle().
G4BinScheme G4Analysis::GetBinScheme (const G4String & binSchemeName)
Definition at line 35 of file G4BinScheme.cc.
View newest version in sPHENIX GitHub at line 35 of file G4BinScheme.cc
References G4endl, G4Exception(), and JustWarning.
Referenced by CheckMinMax(), G4H1ToolsManager::CreateH1(), G4H2ToolsManager::CreateH2(), G4H3ToolsManager::CreateH3(), G4P1ToolsManager::CreateP1(), G4P2ToolsManager::CreateP2(), G4H1ToolsManager::SetH1(), G4H2ToolsManager::SetH2(), G4H3ToolsManager::SetH3(), G4P1ToolsManager::SetP1(), and G4P2ToolsManager::SetP2().
G4Fcn G4Analysis::GetFunction (const G4String & fcnName)
Definition at line 35 of file G4Fcn.cc.
View newest version in sPHENIX GitHub at line 35 of file G4Fcn.cc
References G4endl, G4Exception(), G4FcnIdentity(), and JustWarning.
Referenced by G4HnInformation::AddDimension(), and G4HnInformation::SetDimension().
G4double G4Analysis::GetMax (const G4ToolsBaseHisto & baseHisto, G4int dimension)
Definition at line 52 of file G4BaseHistoUtilities.cc.
View newest version in sPHENIX GitHub at line 52 of file G4BaseHistoUtilities.cc
Referenced by G4H1ToolsManager::GetH1Xmax(), G4H2ToolsManager::GetH2Xmax(), G4H2ToolsManager::GetH2Ymax(), G4H3ToolsManager::GetH3Xmax(), G4H3ToolsManager::GetH3Ymax(), G4H3ToolsManager::GetH3Zmax(), G4P1ToolsManager::GetP1Xmax(), G4P2ToolsManager::GetP2Xmax(), G4P2ToolsManager::GetP2Ymax(), G4P2ToolsManager::GetP2Zmax(), and G4Channeling::UpdateIntegrationStep().
G4double G4Analysis::GetMin (const G4ToolsBaseHisto & baseHisto, G4int dimension)
Definition at line 44 of file G4BaseHistoUtilities.cc.
View newest version in sPHENIX GitHub at line 44 of file G4BaseHistoUtilities.cc
Referenced by G4H1ToolsManager::GetH1Xmin(), G4H2ToolsManager::GetH2Xmin(), G4H2ToolsManager::GetH2Ymin(), G4H3ToolsManager::GetH3Xmin(), G4H3ToolsManager::GetH3Ymin(), G4H3ToolsManager::GetH3Zmin(), G4P1ToolsManager::GetP1Xmin(), G4P2ToolsManager::GetP2Xmin(), G4P2ToolsManager::GetP2Ymin(), and G4P2ToolsManager::GetP2Zmin().
G4int G4Analysis::GetNbins (const G4ToolsBaseHisto & baseHisto, G4int dimension)
Definition at line 38 of file G4BaseHistoUtilities.cc.
View newest version in sPHENIX GitHub at line 38 of file G4BaseHistoUtilities.cc
Referenced by G4H1ToolsManager::GetH1Nbins(), G4H2ToolsManager::GetH2Nxbins(), G4H2ToolsManager::GetH2Nybins(), G4H3ToolsManager::GetH3Nxbins(), G4H3ToolsManager::GetH3Nybins(), G4H3ToolsManager::GetH3Nzbins(), G4P1ToolsManager::GetP1Nbins(), G4P2ToolsManager::GetP2Nxbins(), and G4P2ToolsManager::GetP2Nybins().
G4AnalysisOutput G4Analysis::GetOutput (const G4String & outputName, G4bool warn = true)
Definition at line 191 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 191 of file G4AnalysisUtilities.cc
References G4endl, G4Exception(), and JustWarning.
Referenced by ManagerInstance().
G4String G4Analysis::GetOutputName (G4AnalysisOutput outputType)
Definition at line 212 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 212 of file G4AnalysisUtilities.cc
References G4endl, G4Exception(), and JustWarning.
G4String G4Analysis::GetTitle (const G4ToolsBaseHisto & baseHisto)
Definition at line 102 of file G4BaseHistoUtilities.cc.
View newest version in sPHENIX GitHub at line 102 of file G4BaseHistoUtilities.cc
Referenced by G4H1ToolsManager::GetH1Title(), G4H2ToolsManager::GetH2Title(), G4H3ToolsManager::GetH3Title(), G4P1ToolsManager::GetP1Title(), and G4P2ToolsManager::GetP2Title().
G4double G4Analysis::GetUnitValue (const G4String & unit)
Definition at line 151 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 151 of file G4AnalysisUtilities.cc
References G4UnitDefinition::GetValueOf().
Referenced by G4HnInformation::AddDimension(), G4HnInformation::SetDimension(), G4P2Messenger::SetNewValue(), G4H3Messenger::SetNewValue(), G4H2Messenger::SetNewValue(), G4P1Messenger::SetNewValue(), and G4H1Messenger::SetNewValue().
G4double G4Analysis::GetWidth (const G4ToolsBaseHisto & baseHisto, G4int dimension, const G4String & hnType)
Definition at line 60 of file G4BaseHistoUtilities.cc.
View newest version in sPHENIX GitHub at line 60 of file G4BaseHistoUtilities.cc
References G4Exception(), and JustWarning.
Referenced by G4H1ToolsManager::GetH1Width(), G4H2ToolsManager::GetH2XWidth(), G4H2ToolsManager::GetH2YWidth(), G4H3ToolsManager::GetH3XWidth(), G4H3ToolsManager::GetH3YWidth(), G4H3ToolsManager::GetH3ZWidth(), G4P1ToolsManager::GetP1XWidth(), G4P2ToolsManager::GetP2XWidth(), and G4P2ToolsManager::GetP2YWidth().
template<typename T , typename... Args> std::unique_ptr<T> G4Analysis::make_unique (Args &&... args)
Definition at line 86 of file G4AnalysisUtilities.hh.
View newest version in sPHENIX GitHub at line 86 of file G4AnalysisUtilities.hh
References T.
Referenced by FW::WhiteBoard::add(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), Acts::SeedFilter< external_spacepoint_t >::filterSeeds_2SpFixed(), Acts::VolumeMaterialMapper::finalizeMaps(), and Acts::AdaptiveMultiVertexFinder< vfitter_t, sfinder_t >::find().
G4ToolsAnalysisManager * G4Analysis::ManagerInstance (const G4String & outputType)
Definition at line 56 of file g4analysis.cc.
View newest version in sPHENIX GitHub at line 56 of file g4analysis.cc
References GetOutput(), G4XmlAnalysisManager::Instance(), G4CsvAnalysisManager::Instance(), G4Hdf5AnalysisManager::Instance(), and G4RootAnalysisManager::Instance().
Referenced by B5RunAction::B5RunAction(), and ScoreSpecies::OutputAndClear().
G4bool G4Analysis::SetAxisTitle (G4ToolsBaseHisto & baseHisto, G4int dimension, const G4String & title)
Definition at line 85 of file G4BaseHistoUtilities.cc.
View newest version in sPHENIX GitHub at line 85 of file G4BaseHistoUtilities.cc
References kX, kY, and kZ.
Referenced by G4H1ToolsManager::SetH1XAxisTitle(), G4H1ToolsManager::SetH1YAxisTitle(), G4H2ToolsManager::SetH2XAxisTitle(), G4H2ToolsManager::SetH2YAxisTitle(), G4H2ToolsManager::SetH2ZAxisTitle(), G4H3ToolsManager::SetH3XAxisTitle(), G4H3ToolsManager::SetH3YAxisTitle(), G4H3ToolsManager::SetH3ZAxisTitle(), G4P1ToolsManager::SetP1XAxisTitle(), G4P1ToolsManager::SetP1YAxisTitle(), G4P2ToolsManager::SetP2XAxisTitle(), G4P2ToolsManager::SetP2YAxisTitle(), and G4P2ToolsManager::SetP2ZAxisTitle().
G4bool G4Analysis::SetTitle (G4ToolsBaseHisto & baseHisto, const G4String & title)
Definition at line 79 of file G4BaseHistoUtilities.cc.
View newest version in sPHENIX GitHub at line 79 of file G4BaseHistoUtilities.cc
void G4Analysis::Tokenize (const G4String & line, std::vector< G4String > & tokens)
Definition at line 172 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 172 of file G4AnalysisUtilities.cc
Referenced by G4NtupleMessenger::SetNewValue(), G4H2Messenger::SetNewValue(), G4P2Messenger::SetNewValue(), G4P1Messenger::SetNewValue(), G4H3Messenger::SetNewValue(), G4PlotMessenger::SetNewValue(), G4HnMessenger::SetNewValue(), and G4H1Messenger::SetNewValue().
void G4Analysis::UpdateTitle (G4String & title, const G4String & unitName, const G4String & fcnName)
Definition at line 162 of file G4AnalysisUtilities.cc.
View newest version in sPHENIX GitHub at line 162 of file G4AnalysisUtilities.cc
Variable Documentation
const G4int G4Analysis::kInvalidId = -1
Definition at line 64 of file G4AnalysisUtilities.hh.
View newest version in sPHENIX GitHub at line 64 of file G4AnalysisUtilities.hh
Referenced by G4VAnalysisManager::CreateH1(), G4VAnalysisManager::CreateH2(), G4VAnalysisManager::CreateH3(), G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::CreateNtupleFColumn(), G4VAnalysisManager::CreateNtupleIColumn(), G4VAnalysisManager::CreateNtupleSColumn(), G4RootMpiPNtupleManager::CreateNtupleTColumn(), G4RootPNtupleManager::CreateNtupleTColumn(), G4VAnalysisManager::CreateP1(), G4VAnalysisManager::CreateP2(), G4VAnalysisReader::GetNtuple(), G4Hdf5RFileManager::GetRDirectory(), G4Hdf5RFileManager::GetRFile(), G4Hdf5RFileManager::OpenDirectory(), G4VAnalysisReader::ReadH1(), G4CsvAnalysisReader::ReadH1Impl(), G4Hdf5AnalysisReader::ReadH1Impl(), G4RootAnalysisReader::ReadH1Impl(), G4XmlAnalysisReader::ReadH1Impl(), G4VAnalysisReader::ReadH2(), G4Hdf5AnalysisReader::ReadH2Impl(), G4RootAnalysisReader::ReadH2Impl(), G4XmlAnalysisReader::ReadH2Impl(), G4CsvAnalysisReader::ReadH2Impl(), G4VAnalysisReader::ReadH3(), G4CsvAnalysisReader::ReadH3Impl(), G4RootAnalysisReader::ReadH3Impl(), G4Hdf5AnalysisReader::ReadH3Impl(), G4XmlAnalysisReader::ReadH3Impl(), G4RootAnalysisReader::ReadNtupleImpl(), G4Hdf5AnalysisReader::ReadNtupleImpl(), G4XmlAnalysisReader::ReadNtupleImpl(), G4CsvAnalysisReader::ReadNtupleImpl(), G4VAnalysisReader::ReadP1(), G4CsvAnalysisReader::ReadP1Impl(), G4RootAnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP1Impl(), G4Hdf5AnalysisReader::ReadP1Impl(), G4VAnalysisReader::ReadP2(), G4RootAnalysisReader::ReadP2Impl(), G4XmlAnalysisReader::ReadP2Impl(), G4CsvAnalysisReader::ReadP2Impl(), G4Hdf5AnalysisReader::ReadP2Impl(), G4VAnalysisManager::SetH1(), G4VAnalysisManager::SetH2(), G4VAnalysisManager::SetH3(), G4VAnalysisManager::SetP1(), and G4VAnalysisManager::SetP2().
const G4int G4Analysis::kX = 0
Definition at line 57 of file G4AnalysisUtilities.hh.
View newest version in sPHENIX GitHub at line 57 of file G4AnalysisUtilities.hh
Referenced by G4H1ToolsManager::FillH1(), G4H2ToolsManager::FillH2(), G4H3ToolsManager::FillH3(), G4P1ToolsManager::FillP1(), G4P2ToolsManager::FillP2(), GetAxisTitle(), G4H1ToolsManager::GetH1Nbins(), G4H1ToolsManager::GetH1Width(), G4H1ToolsManager::GetH1XAxisTitle(), G4H1ToolsManager::GetH1Xmax(), G4H1ToolsManager::GetH1Xmin(), G4H2ToolsManager::GetH2Nxbins(), G4H2ToolsManager::GetH2XAxisTitle(), G4H2ToolsManager::GetH2Xmax(), G4H2ToolsManager::GetH2Xmin(), G4H2ToolsManager::GetH2XWidth(), G4H3ToolsManager::GetH3Nxbins(), G4H3ToolsManager::GetH3XAxisTitle(), G4H3ToolsManager::GetH3Xmax(), G4H3ToolsManager::GetH3Xmin(), G4H3ToolsManager::GetH3XWidth(), G4P1ToolsManager::GetP1Nbins(), G4P1ToolsManager::GetP1XAxisTitle(), G4P1ToolsManager::GetP1Xmax(), G4P1ToolsManager::GetP1Xmin(), G4P1ToolsManager::GetP1XWidth(), G4P2ToolsManager::GetP2Nxbins(), G4P2ToolsManager::GetP2XAxisTitle(), G4P2ToolsManager::GetP2Xmax(), G4P2ToolsManager::GetP2Xmin(), G4P2ToolsManager::GetP2XWidth(), G4HnManager::GetXAxisIsLog(), G4HnManager::GetXUnit(), G4PlotManager::PlotAndWrite(), SetAxisTitle(), G4H1ToolsManager::SetH1XAxisTitle(), G4H2ToolsManager::SetH2XAxisTitle(), G4H3ToolsManager::SetH3XAxisTitle(), G4P1ToolsManager::SetP1XAxisTitle(), G4P2ToolsManager::SetP2XAxisTitle(), and G4HnManager::SetXAxisIsLog().
const G4int G4Analysis::kY = 1
Definition at line 58 of file G4AnalysisUtilities.hh.
View newest version in sPHENIX GitHub at line 58 of file G4AnalysisUtilities.hh
Referenced by G4H2ToolsManager::FillH2(), G4H3ToolsManager::FillH3(), G4P1ToolsManager::FillP1(), G4P2ToolsManager::FillP2(), GetAxisTitle(), G4H1ToolsManager::GetH1YAxisTitle(), G4H2ToolsManager::GetH2Nybins(), G4H2ToolsManager::GetH2YAxisTitle(), G4H2ToolsManager::GetH2Ymax(), G4H2ToolsManager::GetH2Ymin(), G4H2ToolsManager::GetH2YWidth(), G4H3ToolsManager::GetH3Nybins(), G4H3ToolsManager::GetH3YAxisTitle(), G4H3ToolsManager::GetH3Ymax(), G4H3ToolsManager::GetH3Ymin(), G4H3ToolsManager::GetH3YWidth(), G4P1ToolsManager::GetP1YAxisTitle(), G4P2ToolsManager::GetP2Nybins(), G4P2ToolsManager::GetP2YAxisTitle(), G4P2ToolsManager::GetP2Ymax(), G4P2ToolsManager::GetP2Ymin(), G4P2ToolsManager::GetP2YWidth(), G4HnManager::GetYAxisIsLog(), G4HnManager::GetYUnit(), G4PlotManager::PlotAndWrite(), SetAxisTitle(), G4H1ToolsManager::SetH1YAxisTitle(), G4H2ToolsManager::SetH2YAxisTitle(), G4H3ToolsManager::SetH3YAxisTitle(), G4P1ToolsManager::SetP1YAxisTitle(), G4P2ToolsManager::SetP2YAxisTitle(), and G4HnManager::SetYAxisIsLog().
const G4int G4Analysis::kZ = 2
Definition at line 59 of file G4AnalysisUtilities.hh.
View newest version in sPHENIX GitHub at line 59 of file G4AnalysisUtilities.hh
Referenced by G4H3ToolsManager::FillH3(), G4P2ToolsManager::FillP2(), GetAxisTitle(), G4H2ToolsManager::GetH2ZAxisTitle(), G4H3ToolsManager::GetH3Nzbins(), G4H3ToolsManager::GetH3ZAxisTitle(), G4H3ToolsManager::GetH3Zmax(), G4H3ToolsManager::GetH3Zmin(), G4H3ToolsManager::GetH3ZWidth(), G4P2ToolsManager::GetP2ZAxisTitle(), G4P2ToolsManager::GetP2Zmax(), G4P2ToolsManager::GetP2Zmin(), G4HnManager::GetZAxisIsLog(), G4HnManager::GetZUnit(), G4PlotManager::PlotAndWrite(), SetAxisTitle(), G4H2ToolsManager::SetH2ZAxisTitle(), G4H3ToolsManager::SetH3ZAxisTitle(), G4P2ToolsManager::SetP2ZAxisTitle(), and G4HnManager::SetZAxisIsLog().