ECCE @ EIC Software: pyG4ThreeVector Namespace Reference
pyG4ThreeVector Namespace Reference
Variables
G4double(XXX::* f1_theta)() const = &XXX::theta
G4double(XXX::* f2_theta)(const XXX &) const = &XXX::theta
G4double(XXX::* f1_cosTheta)() const = &XXX::cosTheta
G4double(XXX::* f2_cosTheta)(const XXX &) const = &XXX::cosTheta
G4double(XXX::* f1_cos2Theta)() const = &XXX::cos2Theta
G4double(XXX::* f2_cos2Theta)(const XXX &) const = &XXX::cos2Theta
G4double(XXX::* f1_perp2)() const = &XXX::perp2
G4double(XXX::* f2_perp2)(const XXX &) const = &XXX::perp2
G4double(XXX::* f1_perp)() const = &XXX::perp
G4double(XXX::* f2_perp)(const XXX &) const = &XXX::perp
G4double(XXX::* f1_angle)() const = &XXX::angle
G4double(XXX::* f2_angle)(const XXX &) const = &XXX::angle
G4double(XXX::* f1_eta)() const = &XXX::eta
G4double(XXX::* f2_eta)(const XXX &) const = &XXX::eta
XXX(XXX::* f1_project)() const = &XXX::project
XXX(XXX::* f2_project)(const XXX &) const = &XXX::project
XXX(XXX::* f1_perpPart)() const = &XXX::perpPart
XXX(XXX::* f2_perpPart)(const XXX &) const = &XXX::perpPart
G4double(XXX::* f1_rapidity)() const = &XXX::rapidity
G4double(XXX::* f2_rapidity)(const XXX &) const = &XXX::rapidity
G4double(XXX::* f1_polarAngle)(const XXX &) const = &XXX::polarAngle
G4double(XXX::* f2_polarAngle)(const XXX &, const XXX &) const = &XXX::polarAngle
G4double(XXX::* f1_azimAngle)(const XXX &) const = &XXX::azimAngle
G4double(XXX::* f2_azimAngle)(const XXX &, const XXX &) const = &XXX::azimAngle
XXX &(XXX::* f1_rotate)(G4double, const XXX &) = &XXX::rotate
XXX &(XXX::* f2_rotate)(const XXX &, G4double) = &XXX::rotate
XXX &(XXX::* f3_rotate)(const HepAxisAngle &) = &XXX::rotate
XXX &(XXX::* f4_rotate)(const HepEulerAngles &) = &XXX::rotate
XXX &(XXX::* f5_rotate)(G4double, G4double, G4double) = &XXX::rotate
Variable Documentation
G4double(XXX::* pyG4ThreeVector::f1_angle)() const = &XXX::angle
Definition at line 60 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 60 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f1_azimAngle)(const XXX &) const = &XXX::azimAngle
Definition at line 78 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 78 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f1_cos2Theta)() const = &XXX::cos2Theta
Definition at line 51 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 51 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f1_cosTheta)() const = &XXX::cosTheta
Definition at line 48 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 48 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f1_eta)() const = &XXX::eta
Definition at line 63 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 63 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f1_perp)() const = &XXX::perp
Definition at line 57 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 57 of file pyG4ThreeVector.cc
G4double(XXX::* pyG4ThreeVector::f1_perp2)() const = &XXX::perp2
Definition at line 54 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 54 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
XXX(XXX::* pyG4ThreeVector::f1_perpPart)() const = &XXX::perpPart
Definition at line 69 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 69 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f1_polarAngle)(const XXX &) const = &XXX::polarAngle
Definition at line 75 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 75 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
XXX(XXX::* pyG4ThreeVector::f1_project)() const = &XXX::project
Definition at line 66 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 66 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f1_rapidity)() const = &XXX::rapidity
Definition at line 72 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 72 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
XXX&(XXX::* pyG4ThreeVector::f1_rotate)(G4double, const XXX &) = &XXX::rotate
Definition at line 81 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 81 of file pyG4ThreeVector.cc
G4double(XXX::* pyG4ThreeVector::f1_theta)() const = &XXX::theta
Definition at line 45 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 45 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f2_angle)(const XXX &) const = &XXX::angle
Definition at line 61 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 61 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f2_azimAngle)(const XXX &, const XXX &) const = &XXX::azimAngle
Definition at line 79 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 79 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f2_cos2Theta)(const XXX &) const = &XXX::cos2Theta
Definition at line 52 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 52 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f2_cosTheta)(const XXX &) const = &XXX::cosTheta
Definition at line 49 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 49 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f2_eta)(const XXX &) const = &XXX::eta
Definition at line 64 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 64 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f2_perp)(const XXX &) const = &XXX::perp
Definition at line 58 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 58 of file pyG4ThreeVector.cc
G4double(XXX::* pyG4ThreeVector::f2_perp2)(const XXX &) const = &XXX::perp2
Definition at line 55 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 55 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
XXX(XXX::* pyG4ThreeVector::f2_perpPart)(const XXX &) const = &XXX::perpPart
Definition at line 70 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 70 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f2_polarAngle)(const XXX &, const XXX &) const = &XXX::polarAngle
Definition at line 76 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 76 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
XXX(XXX::* pyG4ThreeVector::f2_project)(const XXX &) const = &XXX::project
Definition at line 67 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 67 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
G4double(XXX::* pyG4ThreeVector::f2_rapidity)(const XXX &) const = &XXX::rapidity
Definition at line 73 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 73 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
XXX&(XXX::* pyG4ThreeVector::f2_rotate)(const XXX &, G4double) = &XXX::rotate
Definition at line 82 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 82 of file pyG4ThreeVector.cc
G4double(XXX::* pyG4ThreeVector::f2_theta)(const XXX &) const = &XXX::theta
Definition at line 46 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 46 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().
XXX&(XXX::* pyG4ThreeVector::f3_rotate)(const HepAxisAngle &) = &XXX::rotate
Definition at line 83 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 83 of file pyG4ThreeVector.cc
XXX&(XXX::* pyG4ThreeVector::f4_rotate)(const HepEulerAngles &) = &XXX::rotate
Definition at line 84 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 84 of file pyG4ThreeVector.cc
XXX&(XXX::* pyG4ThreeVector::f5_rotate)(G4double, G4double, G4double) = &XXX::rotate
Definition at line 85 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 85 of file pyG4ThreeVector.cc
Referenced by export_G4ThreeVector().