ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_angularEnergy.cc File Reference
MCGIDI_angularEnergy.cc File Reference
#include <string.h>
#include "MCGIDI.h"
#include "MCGIDI_fromTOM.h"
#include "MCGIDI_misc.h"
#include "MCGIDI_private.h"
Functions
static int MCGIDI_angularEnergy_parsePointwiseFromTOM (statusMessageReporting *smr, xDataTOM_element *pointwise, MCGIDI_distribution *distribution)
MCGIDI_angularEnergy * MCGIDI_angularEnergy_new (statusMessageReporting *smr)
int MCGIDI_angularEnergy_initialize (statusMessageReporting *, MCGIDI_angularEnergy *angularEnergy)
MCGIDI_angularEnergy * MCGIDI_angularEnergy_free (statusMessageReporting *smr, MCGIDI_angularEnergy *angularEnergy)
int MCGIDI_angularEnergy_release (statusMessageReporting *smr, MCGIDI_angularEnergy *angularEnergy)
int MCGIDI_angularEnergy_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_distribution *distribution)
int MCGIDI_angularEnergy_sampleDistribution (statusMessageReporting *smr, MCGIDI_angularEnergy *angularEnergy, MCGIDI_quantitiesLookupModes &modes, MCGIDI_decaySamplingInfo *decaySamplingInfo)
Function Documentation
MCGIDI_angularEnergy* MCGIDI_angularEnergy_free (statusMessageReporting * smr, MCGIDI_angularEnergy * angularEnergy)
Definition at line 40 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 40 of file MCGIDI_angularEnergy.cc
References MCGIDI_angularEnergy_release(), and smr_freeMemory().
Referenced by MCGIDI_angularEnergy_new(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), and MCGIDI_distribution_release().
int MCGIDI_angularEnergy_initialize (statusMessageReporting * , MCGIDI_angularEnergy * angularEnergy)
Definition at line 32 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 32 of file MCGIDI_angularEnergy.cc
Referenced by MCGIDI_angularEnergy_new(), and MCGIDI_angularEnergy_release().
MCGIDI_angularEnergy* MCGIDI_angularEnergy_new (statusMessageReporting * smr)
Definition at line 21 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 21 of file MCGIDI_angularEnergy.cc
References MCGIDI_angularEnergy_free(), MCGIDI_angularEnergy_initialize(), and smr_malloc2.
Referenced by MCGIDI_angularEnergy_parsePointwiseFromTOM(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
int MCGIDI_angularEnergy_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_distribution * distribution)
Definition at line 65 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 65 of file MCGIDI_angularEnergy.cc
References check_license::err(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), smr_setReportError2, smr_unknownID, xDataTOM_getAttributesValueInElement(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_distribution_parseFromTOM().
static int MCGIDI_angularEnergy_parsePointwiseFromTOM (statusMessageReporting * smr, xDataTOM_element * pointwise, MCGIDI_distribution * distribution) static
Definition at line 91 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 91 of file MCGIDI_angularEnergy.cc
References MCGIDI_distribution_s::angularEnergy, MCGIDI_pdfsOfXGivenW_s::dist, e, check_license::err(), MCGIDI_angularEnergy_s::frame, MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, xDataTOM_W_XYs_s::length, xDataTOM_V_W_XYs_s::length, MCGIDI_angularEnergy_free(), MCGIDI_angularEnergy_new(), MCGIDI_distributionType_angularEnergy_e, MCGIDI_fromTOM_interpolation(), MCGIDI_fromTOM_pdfOfX(), MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf(), MCGIDI_misc_getProductFrame(), MCGIDI_misc_getUnitConversionFactor(), nfu_Okay, nfu_statusMessage(), norm, MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_angularEnergy_s::pdfOfEpGivenEAndMu, MCGIDI_angularEnergy_s::pdfOfMuGivenE, ptwXY_add_double(), ptwXY_free(), ptwXY_integrateDomain(), ptwXY_new(), ptwXY_setValueAtX(), smr_isOk(), smr_malloc2, smr_setReportError2, smr_unknownID, xDataTOM_V_W_XYs_s::subAxes, MCGIDI_distribution_s::type, xDataTOM_XYs_s::value, xDataTOM_W_XYs_s::value, xDataTOM_V_W_XYs_s::W_XYs, MCGIDI_pdfsOfXGivenW_s::Ws, xDataTOM_frame_invalid, xDataTOM_subAxes_getUnit(), xDataTOME_getXDataIfID(), xDataTOM_W_XYs_s::XYs, and y.
Referenced by MCGIDI_angularEnergy_parseFromTOM().
int MCGIDI_angularEnergy_release (statusMessageReporting * smr, MCGIDI_angularEnergy * angularEnergy)
Definition at line 49 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 49 of file MCGIDI_angularEnergy.cc
References MCGIDI_angularEnergy_initialize(), MCGIDI_sampling_pdfsOfXGivenW_release(), MCGIDI_pdfsOfXGivenW_s::numberOfWs, MCGIDI_angularEnergy_s::pdfOfEpGivenEAndMu, MCGIDI_angularEnergy_s::pdfOfMuGivenE, and smr_freeMemory().
Referenced by MCGIDI_angularEnergy_free().
int MCGIDI_angularEnergy_sampleDistribution (statusMessageReporting * smr, MCGIDI_angularEnergy * angularEnergy, MCGIDI_quantitiesLookupModes & modes, MCGIDI_decaySamplingInfo * decaySamplingInfo)
Definition at line 175 of file MCGIDI_angularEnergy.cc.
View newest version in sPHENIX GitHub at line 175 of file MCGIDI_angularEnergy.cc
References MCGIDI_decaySamplingInfo_s::frame, MCGIDI_angularEnergy_s::frame, MCGIDI_sampling_doubleDistribution(), MCGIDI_angularEnergy_s::pdfOfEpGivenEAndMu, and MCGIDI_angularEnergy_s::pdfOfMuGivenE.
Referenced by MCGIDI_outputChannel_sampleProductsAtE().