ECCE @ EIC Software: G4INCL::NNToNSKChannel Class Reference
G4INCL::NNToNSKChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNNToNSKChannel.hh>
Public Member Functions
NNToNSKChannel (Particle *, Particle *)
virtual ~NNToNSKChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
INCL_DECLARE_ALLOCATION_POOL (NNToNSKChannel)
Private Attributes
Particle * particle1
Particle * particle2
Static Private Attributes
static const G4double angularSlope = 2.
Detailed Description
Definition at line 47 of file G4INCLNNToNSKChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLNNToNSKChannel.hh
Constructor & Destructor Documentation
G4INCL::NNToNSKChannel::NNToNSKChannel (Particle * p1, Particle * p2)
Definition at line 51 of file G4INCLNNToNSKChannel.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLNNToNSKChannel.cc
G4INCL::NNToNSKChannel::~NNToNSKChannel () virtual
Definition at line 55 of file G4INCLNNToNSKChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNNToNSKChannel.cc
Member Function Documentation
void G4INCL::NNToNSKChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 57 of file G4INCLNNToNSKChannel.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNNToNSKChannel.cc
References G4INCL::FinalState::addCreatedParticle(), G4INCL::FinalState::addModifiedParticle(), angularSlope, G4INCL::PhaseSpaceGenerator::generateBiased(), G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getPosition(), G4INCL::Particle::getType(), G4INCL::KPlus, G4INCL::KZero, G4INCL::Neutron, particle1, particle2, G4INCL::Proton, G4INCL::Particle::setType(), G4INCL::Random::shoot(), G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, G4INCL::KinematicsUtils::totalEnergyInCM(), and zero.
G4INCL::NNToNSKChannel::INCL_DECLARE_ALLOCATION_POOL (NNToNSKChannel) private
Member Data Documentation
const G4double G4INCL::NNToNSKChannel::angularSlope = 2. static private
Definition at line 57 of file G4INCLNNToNSKChannel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNNToNSKChannel.hh
Referenced by fillFinalState().
Particle* G4INCL::NNToNSKChannel::particle1 private
Definition at line 55 of file G4INCLNNToNSKChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNNToNSKChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::NNToNSKChannel::particle2 private
Definition at line 55 of file G4INCLNNToNSKChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNNToNSKChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNNToNSKChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNNToNSKChannel.cc