ECCE @ EIC Software: G4MuBetheBlochModel Class Reference
G4MuBetheBlochModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/include/G4MuBetheBlochModel.hh>
Public Member Functions
G4MuBetheBlochModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="MuBetheBloch")
~G4MuBetheBlochModel ()=default
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *) override
virtual G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kinEnergy) override
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
void SetParticle (const G4ParticleDefinition *p)
G4MuBetheBlochModel & operator= (const G4MuBetheBlochModel &right)=delete
G4MuBetheBlochModel (const G4MuBetheBlochModel &)=delete
Private Attributes
const G4ParticleDefinition * particle
G4ParticleDefinition * theElectron
G4ParticleChangeForLoss * fParticleChange
G4EmCorrections * corr
G4double limitKinEnergy
G4double logLimitKinEnergy
G4double mass
G4double massSquare
G4double ratio
G4double twoln10
G4double alphaprime
Static Private Attributes
static G4double xgi [8]
static G4double wgi [8]
Additional Inherited Members
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 68 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4MuBetheBlochModel.hh
Constructor & Destructor Documentation
G4MuBetheBlochModel::G4MuBetheBlochModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "MuBetheBloch") explicit
Definition at line 78 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 78 of file G4MuBetheBlochModel.cc
References corr, G4Electron::Electron(), G4LossTableManager::EmCorrections(), fParticleChange, G4LossTableManager::Instance(), mass, massSquare, ratio, SetParticle(), and theElectron.
G4MuBetheBlochModel::~G4MuBetheBlochModel () default
G4MuBetheBlochModel::G4MuBetheBlochModel (const G4MuBetheBlochModel &) private delete
Member Function Documentation
G4double G4MuBetheBlochModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 179 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 179 of file G4MuBetheBlochModel.cc
References ComputeCrossSectionPerElectron(), and Acts::VectorHelpers::cross().
G4double G4MuBetheBlochModel::ComputeCrossSectionPerElectron (const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) virtual
Definition at line 130 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 130 of file G4MuBetheBlochModel.cc
References alphaprime, Acts::VectorHelpers::cross(), source.hepunit::electron_mass_c2, G4Exp(), G4Log(), limitKinEnergy, mass, massSquare, max, MaxSecondaryEnergy(), min, source.hepunit::twopi_mc2_rcl2, wgi, and xgi.
Referenced by ComputeCrossSectionPerAtom(), and CrossSectionPerVolume().
G4double G4MuBetheBlochModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 208 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 208 of file G4MuBetheBlochModel.cc
References alphaprime, corr, G4IonisParamMat::DensityCorrection(), source.hepunit::electron_mass_c2, G4Exp(), G4Log(), G4InuclParticleNames::gam, G4Material::GetElectronDensity(), G4Material::GetIonisation(), G4IonisParamMat::GetMeanExcitationEnergy(), G4EmCorrections::HighOrderCorrections(), limitKinEnergy, logLimitKinEnergy, mass, massSquare, MaxSecondaryEnergy(), min, G4EmCorrections::ShellCorrection(), twoln10, source.hepunit::twopi_mc2_rcl2, wgi, x, and xgi.
G4double G4MuBetheBlochModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 193 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 193 of file G4MuBetheBlochModel.cc
References ComputeCrossSectionPerElectron(), Acts::VectorHelpers::cross(), and G4Material::GetElectronDensity().
void G4MuBetheBlochModel::Initialise (const G4ParticleDefinition * p, const G4DataVector &) override virtual
Implements G4VEmModel.
Definition at line 121 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 121 of file G4MuBetheBlochModel.cc
References fParticleChange, G4VEmModel::GetParticleChangeForLoss(), and SetParticle().
G4double G4MuBetheBlochModel::MaxSecondaryEnergy (const G4ParticleDefinition * , G4double kinEnergy) override protected virtual
Reimplemented from G4VEmModel.
Definition at line 110 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 110 of file G4MuBetheBlochModel.cc
References source.hepunit::electron_mass_c2, mass, and ratio.
Referenced by ComputeCrossSectionPerElectron(), and ComputeDEDXPerVolume().
G4double G4MuBetheBlochModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple * couple) override virtual
Reimplemented from G4VEmModel.
Definition at line 102 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 102 of file G4MuBetheBlochModel.cc
References G4Material::GetIonisation(), G4MaterialCutsCouple::GetMaterial(), and G4IonisParamMat::GetMeanExcitationEnergy().
G4MuBetheBlochModel& G4MuBetheBlochModel::operator= (const G4MuBetheBlochModel & right) private delete
void G4MuBetheBlochModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * , const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) override virtual
Implements G4VEmModel.
Definition at line 271 of file G4MuBetheBlochModel.cc.
View newest version in sPHENIX GitHub at line 271 of file G4MuBetheBlochModel.cc
References a0, alphaprime, Acts::Test::delta, dir, source.hepunit::electron_mass_c2, f, fParticleChange, G4cout, G4endl, G4Log(), G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), limitKinEnergy, mass, massSquare, G4VEmModel::MaxSecondaryKinEnergy(), min, phi, CLHEP::Hep3Vector::rotateUz(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), theElectron, twopi, and CLHEP::Hep3Vector::unit().
void G4MuBetheBlochModel::SetParticle (const G4ParticleDefinition * p) inline private
Definition at line 144 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 144 of file G4MuBetheBlochModel.hh
References CLHEP::electron_mass_c2, G4ParticleDefinition::GetPDGMass(), mass, massSquare, particle, and ratio.
Referenced by G4MuBetheBlochModel(), and Initialise().
Member Data Documentation
G4double G4MuBetheBlochModel::alphaprime private
Definition at line 138 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 138 of file G4MuBetheBlochModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), and SampleSecondaries().
G4EmCorrections* G4MuBetheBlochModel::corr private
Definition at line 130 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 130 of file G4MuBetheBlochModel.hh
Referenced by ComputeDEDXPerVolume(), and G4MuBetheBlochModel().
G4ParticleChangeForLoss* G4MuBetheBlochModel::fParticleChange private
Definition at line 129 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4MuBetheBlochModel.hh
Referenced by G4MuBetheBlochModel(), Initialise(), and SampleSecondaries().
G4double G4MuBetheBlochModel::limitKinEnergy private
Definition at line 132 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 132 of file G4MuBetheBlochModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), and SampleSecondaries().
G4double G4MuBetheBlochModel::logLimitKinEnergy private
Definition at line 133 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 133 of file G4MuBetheBlochModel.hh
Referenced by ComputeDEDXPerVolume().
G4double G4MuBetheBlochModel::mass private
Definition at line 134 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 134 of file G4MuBetheBlochModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), G4MuBetheBlochModel(), MaxSecondaryEnergy(), SampleSecondaries(), and SetParticle().
G4double G4MuBetheBlochModel::massSquare private
Definition at line 135 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 135 of file G4MuBetheBlochModel.hh
Referenced by ComputeCrossSectionPerElectron(), ComputeDEDXPerVolume(), G4MuBetheBlochModel(), SampleSecondaries(), and SetParticle().
const G4ParticleDefinition* G4MuBetheBlochModel::particle private
Definition at line 127 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 127 of file G4MuBetheBlochModel.hh
Referenced by SetParticle().
G4double G4MuBetheBlochModel::ratio private
Definition at line 136 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 136 of file G4MuBetheBlochModel.hh
Referenced by G4MuBetheBlochModel(), MaxSecondaryEnergy(), and SetParticle().
G4ParticleDefinition* G4MuBetheBlochModel::theElectron private
Definition at line 128 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4MuBetheBlochModel.hh
Referenced by G4MuBetheBlochModel(), and SampleSecondaries().
G4double G4MuBetheBlochModel::twoln10 private
Definition at line 137 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 137 of file G4MuBetheBlochModel.hh
Referenced by ComputeDEDXPerVolume().
G4double G4MuBetheBlochModel::wgi static private
Initial value:
={ 0.0506, 0.1112, 0.1569, 0.1813, 0.1813,
                                      0.1569, 0.1112, 0.0506 }
Definition at line 139 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 139 of file G4MuBetheBlochModel.hh
Referenced by ComputeCrossSectionPerElectron(), and ComputeDEDXPerVolume().
G4double G4MuBetheBlochModel::xgi static private
Initial value:
={ 0.0199, 0.1017, 0.2372, 0.4083, 0.5917,
                                      0.7628, 0.8983, 0.9801 }
Definition at line 139 of file G4MuBetheBlochModel.hh.
View newest version in sPHENIX GitHub at line 139 of file G4MuBetheBlochModel.hh
Referenced by ComputeCrossSectionPerElectron(), and ComputeDEDXPerVolume().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/include/G4MuBetheBlochModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/src/G4MuBetheBlochModel.cc