ECCE @ EIC Software: G4NeutronTrackingCut Class Reference
G4NeutronTrackingCut Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4NeutronTrackingCut.hh>
Public Member Functions
G4NeutronTrackingCut (G4int ver=0)
G4NeutronTrackingCut (const G4String &name, G4int ver=0)
virtual ~G4NeutronTrackingCut ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
void SetTimeLimit (G4double)
void SetKineticEnergyLimit (G4double)
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Attributes
G4double timeLimit
G4double kineticEnergyLimit
G4int verbose
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 45 of file G4NeutronTrackingCut.hh.
View newest version in sPHENIX GitHub at line 45 of file G4NeutronTrackingCut.hh
Constructor & Destructor Documentation
G4NeutronTrackingCut::G4NeutronTrackingCut (G4int ver = 0)
Definition at line 56 of file G4NeutronTrackingCut.cc.
View newest version in sPHENIX GitHub at line 56 of file G4NeutronTrackingCut.cc
References bUnknown, kineticEnergyLimit, microsecond, G4VPhysicsConstructor::SetPhysicsType(), and timeLimit.
G4NeutronTrackingCut::G4NeutronTrackingCut (const G4String & name, G4int ver = 0)
Definition at line 64 of file G4NeutronTrackingCut.cc.
View newest version in sPHENIX GitHub at line 64 of file G4NeutronTrackingCut.cc
G4NeutronTrackingCut::~G4NeutronTrackingCut () virtual
Definition at line 68 of file G4NeutronTrackingCut.cc.
View newest version in sPHENIX GitHub at line 68 of file G4NeutronTrackingCut.cc
Member Function Documentation
void G4NeutronTrackingCut::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 71 of file G4NeutronTrackingCut.cc.
View newest version in sPHENIX GitHub at line 71 of file G4NeutronTrackingCut.cc
References G4Neutron::NeutronDefinition().
void G4NeutronTrackingCut::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 76 of file G4NeutronTrackingCut.cc.
View newest version in sPHENIX GitHub at line 76 of file G4NeutronTrackingCut.cc
References G4cout, G4endl, G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetProcessManager(), G4HadronicProcessStore::Instance(), G4Threading::IsMasterThread(), kineticEnergyLimit, MeV, G4Neutron::Neutron(), ns, particle, G4InuclParticleNames::pn, G4HadronicProcessStore::RegisterExtraProcess(), G4HadronicProcessStore::RegisterParticleForExtraProcess(), G4NeutronKiller::SetKinEnergyLimit(), G4NeutronKiller::SetTimeLimit(), timeLimit, and verbose.
void G4NeutronTrackingCut::SetKineticEnergyLimit (G4double val) inline
Definition at line 77 of file G4NeutronTrackingCut.hh.
View newest version in sPHENIX GitHub at line 77 of file G4NeutronTrackingCut.hh
References kineticEnergyLimit.
void G4NeutronTrackingCut::SetTimeLimit (G4double val) inline
Definition at line 72 of file G4NeutronTrackingCut.hh.
View newest version in sPHENIX GitHub at line 72 of file G4NeutronTrackingCut.hh
References timeLimit.
Member Data Documentation
G4double G4NeutronTrackingCut::kineticEnergyLimit private
Definition at line 67 of file G4NeutronTrackingCut.hh.
View newest version in sPHENIX GitHub at line 67 of file G4NeutronTrackingCut.hh
Referenced by ConstructProcess(), G4NeutronTrackingCut(), and SetKineticEnergyLimit().
G4double G4NeutronTrackingCut::timeLimit private
Definition at line 66 of file G4NeutronTrackingCut.hh.
View newest version in sPHENIX GitHub at line 66 of file G4NeutronTrackingCut.hh
Referenced by ConstructProcess(), G4NeutronTrackingCut(), and SetTimeLimit().
G4int G4NeutronTrackingCut::verbose private
Definition at line 69 of file G4NeutronTrackingCut.hh.
View newest version in sPHENIX GitHub at line 69 of file G4NeutronTrackingCut.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/include/G4NeutronTrackingCut.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/limiters/src/G4NeutronTrackingCut.cc