ECCE @ EIC Software: G4DeltaAngle Class Reference
G4DeltaAngle Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4DeltaAngle.hh>
Public Member Functions
G4DeltaAngle (const G4String &name="")
virtual ~G4DeltaAngle ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double kinEnergyFinal, G4int Z, const G4Material *mat=nullptr) final
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double kinEnergyFinal, G4int Z, G4int shellIdx, const G4Material *mat=nullptr) final
virtual void PrintGeneratorInformation () const final
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr)
const G4String & GetName () const
Private Member Functions
G4DeltaAngle & operator= (const G4DeltaAngle &right)=delete
G4DeltaAngle (const G4DeltaAngle &)=delete
Private Attributes
const G4ParticleDefinition * fElectron
std::vector< G4double > prob
G4int nprob
G4int fShellIdx
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 56 of file G4DeltaAngle.hh.
View newest version in sPHENIX GitHub at line 56 of file G4DeltaAngle.hh
Constructor & Destructor Documentation
G4DeltaAngle::G4DeltaAngle (const G4String & name = "") explicit
Definition at line 60 of file G4DeltaAngle.cc.
View newest version in sPHENIX GitHub at line 60 of file G4DeltaAngle.cc
References G4Electron::Electron(), fElectron, fShellIdx, nprob, and prob.
G4DeltaAngle::~G4DeltaAngle () virtual
Definition at line 69 of file G4DeltaAngle.cc.
View newest version in sPHENIX GitHub at line 69 of file G4DeltaAngle.cc
G4DeltaAngle::G4DeltaAngle (const G4DeltaAngle &) private delete
Member Function Documentation
G4DeltaAngle& G4DeltaAngle::operator= (const G4DeltaAngle & right) private delete
void G4DeltaAngle::PrintGeneratorInformation () const final virtual
Definition at line 195 of file G4DeltaAngle.cc.
View newest version in sPHENIX GitHub at line 195 of file G4DeltaAngle.cc
G4ThreeVector & G4DeltaAngle::SampleDirection (const G4DynamicParticle * dp, G4double kinEnergyFinal, G4int Z, const G4Material * mat = nullptr) final virtual
Implements G4VEmAngularDistribution.
Definition at line 82 of file G4DeltaAngle.cc.
View newest version in sPHENIX GitHub at line 82 of file G4DeltaAngle.cc
References kdfinder::abs(), G4InuclSpecialFunctions::bindingEnergy(), e, source.hepunit::electron_mass_c2, fElectron, G4VEmAngularDistribution::fLocalDirection, fShellIdx, G4Log(), G4UniformRand, G4AtomicShells::GetBindingEnergy(), G4DynamicParticle::GetMomentumDirection(), G4AtomicShells::GetNumberOfElectrons(), G4AtomicShells::GetNumberOfShells(), G4DynamicParticle::GetParticleDefinition(), G4DynamicParticle::GetTotalEnergy(), G4DynamicParticle::GetTotalMomentum(), incremental_prev_tag::idx, n, nmax, nprob, phi, prob, CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), sum, twopi, x, x1, x2, and y.
Referenced by SampleDirectionForShell().
G4ThreeVector & G4DeltaAngle::SampleDirectionForShell (const G4DynamicParticle * dp, G4double kinEnergyFinal, G4int Z, G4int shellIdx, const G4Material * mat = nullptr) final virtual
Reimplemented from G4VEmAngularDistribution.
Definition at line 73 of file G4DeltaAngle.cc.
View newest version in sPHENIX GitHub at line 73 of file G4DeltaAngle.cc
References fShellIdx, incremental_prev_tag::idx, and SampleDirection().
Member Data Documentation
const G4ParticleDefinition* G4DeltaAngle::fElectron private
Definition at line 83 of file G4DeltaAngle.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DeltaAngle.hh
Referenced by G4DeltaAngle(), and SampleDirection().
G4int G4DeltaAngle::fShellIdx private
Definition at line 86 of file G4DeltaAngle.hh.
View newest version in sPHENIX GitHub at line 86 of file G4DeltaAngle.hh
Referenced by G4DeltaAngle(), SampleDirection(), and SampleDirectionForShell().
G4int G4DeltaAngle::nprob private
Definition at line 85 of file G4DeltaAngle.hh.
View newest version in sPHENIX GitHub at line 85 of file G4DeltaAngle.hh
Referenced by G4DeltaAngle(), and SampleDirection().
std::vector<G4double> G4DeltaAngle::prob private
Definition at line 84 of file G4DeltaAngle.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DeltaAngle.hh
Referenced by G4DeltaAngle(), and SampleDirection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4DeltaAngle.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4DeltaAngle.cc