ECCE @ EIC Software: G4BiasingHelper Class Reference
G4BiasingHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BiasingHelper.hh>
Static Public Member Functions
static G4bool ActivatePhysicsBiasing (G4ProcessManager *pmanager, G4String physicsProcessToBias, G4String wrappedName="")
static void ActivateNonPhysicsBiasing (G4ProcessManager *pmanager, G4String nonPhysicsProcessName="")
static
G4ParallelGeometriesLimiterProcess * AddLimiterProcess (G4ProcessManager *pmanager, const G4String &processName="biasLimiter")
Detailed Description
Definition at line 52 of file G4BiasingHelper.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BiasingHelper.hh
Member Function Documentation
void G4BiasingHelper::ActivateNonPhysicsBiasing (G4ProcessManager * pmanager, G4String nonPhysicsProcessName = "") static
Definition at line 95 of file G4BiasingHelper.cc.
View newest version in sPHENIX GitHub at line 95 of file G4BiasingHelper.cc
References G4ProcessManager::AddProcess(), ordDefault, and ordInActive.
Referenced by G4GenericBiasingPhysics::ConstructProcess().
G4bool G4BiasingHelper::ActivatePhysicsBiasing (G4ProcessManager * pmanager, G4String physicsProcessToBias, G4String wrappedName = "") static
Definition at line 32 of file G4BiasingHelper.cc.
View newest version in sPHENIX GitHub at line 32 of file G4BiasingHelper.cc
References G4ProcessManager::AddProcess(), FatalException, G4endl, G4Exception(), G4ProcessManager::GetProcessList(), G4ProcessManager::GetProcessOrdering(), G4VProcess::GetProcessType(), idxAlongStep, idxAtRest, idxPostStep, ordDefault, ordInActive, G4ProcessManager::RemoveProcess(), and G4ProcessVector::size().
Referenced by G4GenericBiasingPhysics::ConstructProcess().
G4ParallelGeometriesLimiterProcess * G4BiasingHelper::AddLimiterProcess (G4ProcessManager * pmanager, const G4String & processName = "biasLimiter") static
Definition at line 107 of file G4BiasingHelper.cc.
View newest version in sPHENIX GitHub at line 107 of file G4BiasingHelper.cc
References G4ProcessManager::AddProcess(), G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), G4ParticleDefinition::GetPDGEncoding(), G4ProcessManager::GetProcessList(), idxAlongStep, idxPostStep, JustWarning, G4ProcessManager::SetProcessOrderingToLast(), G4ProcessManager::SetProcessOrderingToSecond(), and G4ProcessVector::size().
Referenced by G4GenericBiasingPhysics::AssociateParallelGeometries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BiasingHelper.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BiasingHelper.cc