ECCE @ EIC Software: G4LENDCombinedModel Class Reference
G4LENDCombinedModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDCombinedModel.hh>
Public Member Functions
G4LENDCombinedModel (G4ParticleDefinition *pd)
~G4LENDCombinedModel ()
void BuildPhysicsTable (const G4ParticleDefinition &)
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &aTargetNucleus)
G4bool HasData (const G4DynamicParticle *, G4int iZ, G4int iA, G4int iM, const G4Isotope *, const G4Element *, const G4Material *)
Public Member Functions inherited from G4LENDModel
G4LENDModel (G4String name="LENDModel")
~G4LENDModel ()
void ChangeDefaultEvaluation (G4String name)
void AllowNaturalAbundanceTarget ()
void AllowAnyCandidateTarget ()
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpLENDTargetInfo (G4bool force=false)
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void InitialiseModel ()
Private Attributes
G4LENDCombinedCrossSection * crossSection
G4LENDElastic * elastic
G4LENDInelastic * inelastic
G4LENDCapture * capture
G4LENDFission * fission
G4LENDModel * channels [4]
Additional Inherited Members
Protected Member Functions inherited from G4LENDModel
void create_used_target_map ()
void recreate_used_target_map ()
G4GIDI_target * get_target_from_map (G4int nuclear_code)
G4HadFinalState * returnUnchanged (const G4HadProjectile &aTrack, G4HadFinalState *theResult)
Protected Attributes inherited from G4LENDModel
G4ParticleDefinition * proj
G4LENDManager * lend_manager
std::map< G4int,
G4LENDUsedTarget * > usedTarget_map
Detailed Description
Definition at line 50 of file G4LENDCombinedModel.hh.
View newest version in sPHENIX GitHub at line 50 of file G4LENDCombinedModel.hh
Constructor & Destructor Documentation
G4LENDCombinedModel::G4LENDCombinedModel (G4ParticleDefinition * pd)
Definition at line 34 of file G4LENDCombinedModel.cc.
View newest version in sPHENIX GitHub at line 34 of file G4LENDCombinedModel.cc
References capture, channels, crossSection, elastic, fission, inelastic, and G4LENDModel::proj.
G4LENDCombinedModel::~G4LENDCombinedModel () inline
Definition at line 54 of file G4LENDCombinedModel.hh.
View newest version in sPHENIX GitHub at line 54 of file G4LENDCombinedModel.hh
Member Function Documentation
G4HadFinalState * G4LENDCombinedModel::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & aTargetNucleus) virtual
Reimplemented from G4LENDModel.
Definition at line 62 of file G4LENDCombinedModel.cc.
View newest version in sPHENIX GitHub at line 62 of file G4LENDCombinedModel.cc
References G4LENDModel::ApplyYourself(), channels, crossSection, G4Nucleus::GetA_asInt(), G4Nucleus::GetIsotope(), G4HadProjectile::GetKineticEnergy(), G4HadProjectile::GetMaterial(), G4Nucleus::GetZ_asInt(), G4LENDModel::proj, and G4LENDCombinedCrossSection::SelectChannel().
void G4LENDCombinedModel::BuildPhysicsTable (const G4ParticleDefinition & projectile) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 48 of file G4LENDCombinedModel.cc.
View newest version in sPHENIX GitHub at line 48 of file G4LENDCombinedModel.cc
References G4LENDCombinedCrossSection::BuildPhysicsTable(), G4LENDModel::create_used_target_map(), and crossSection.
Referenced by G4LENDorBERTModel::BuildPhysicsTable().
G4bool G4LENDCombinedModel::HasData (const G4DynamicParticle * , G4int iZ, G4int iA, G4int iM, const G4Isotope * , const G4Element * , const G4Material *)
Definition at line 53 of file G4LENDCombinedModel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4LENDCombinedModel.cc
References G4LENDModel::get_target_from_map(), G4LENDManager::GetNucleusEncoding(), and G4LENDModel::lend_manager.
Referenced by G4LENDorBERTModel::ApplyYourself().
Member Data Documentation
G4LENDCapture* G4LENDCombinedModel::capture private
Definition at line 67 of file G4LENDCombinedModel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4LENDCombinedModel.hh
Referenced by G4LENDCombinedModel().
G4LENDModel* G4LENDCombinedModel::channels[4] private
Definition at line 69 of file G4LENDCombinedModel.hh.
View newest version in sPHENIX GitHub at line 69 of file G4LENDCombinedModel.hh
Referenced by ApplyYourself(), and G4LENDCombinedModel().
G4LENDCombinedCrossSection* G4LENDCombinedModel::crossSection private
Definition at line 64 of file G4LENDCombinedModel.hh.
View newest version in sPHENIX GitHub at line 64 of file G4LENDCombinedModel.hh
Referenced by ApplyYourself(), BuildPhysicsTable(), and G4LENDCombinedModel().
G4LENDElastic* G4LENDCombinedModel::elastic private
Definition at line 65 of file G4LENDCombinedModel.hh.
View newest version in sPHENIX GitHub at line 65 of file G4LENDCombinedModel.hh
Referenced by G4LENDCombinedModel().
G4LENDFission* G4LENDCombinedModel::fission private
Definition at line 68 of file G4LENDCombinedModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4LENDCombinedModel.hh
Referenced by G4LENDCombinedModel().
G4LENDInelastic* G4LENDCombinedModel::inelastic private
Definition at line 66 of file G4LENDCombinedModel.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LENDCombinedModel.hh
Referenced by G4LENDCombinedModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDCombinedModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/G4LENDCombinedModel.cc