ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/particles/pymodG4particles.cc File Reference
pymodG4particles.cc File Reference
#include <boost/python.hpp>
Functions
void export_G4ParticleDefinition ()
void export_G4DynamicParticle ()
void export_G4ParticleTable ()
void export_G4DecayTable ()
void export_G4PrimaryParticle ()
void export_G4PrimaryVertex ()
void export_PyG4ParticleList ()
BOOST_PYTHON_MODULE (G4particles)
Function Documentation
BOOST_PYTHON_MODULE (G4particles)
Definition at line 47 of file pymodG4particles.cc.
View newest version in sPHENIX GitHub at line 47 of file pymodG4particles.cc
References export_G4DecayTable(), export_G4DynamicParticle(), export_G4ParticleDefinition(), export_G4ParticleTable(), export_G4PrimaryParticle(), export_G4PrimaryVertex(), and export_PyG4ParticleList().
void export_G4DecayTable ()
Definition at line 39 of file pyG4DecayTable.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4DecayTable.cc
References G4DecayTable::DumpInfo().
Referenced by BOOST_PYTHON_MODULE().
void export_G4DynamicParticle ()
Definition at line 41 of file pyG4DynamicParticle.cc.
View newest version in sPHENIX GitHub at line 41 of file pyG4DynamicParticle.cc
References G4DynamicParticle::DumpInfo(), G4DynamicParticle::GetCharge(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetOccupancy(), G4DynamicParticle::GetPDGcode(), G4DynamicParticle::GetPolarization(), G4DynamicParticle::GetPreAssignedDecayProperTime(), G4DynamicParticle::GetPrimaryParticle(), G4DynamicParticle::GetProperTime(), G4DynamicParticle::GetTotalEnergy(), G4DynamicParticle::GetTotalMomentum(), G4DynamicParticle::GetTotalOccupancy(), G4DynamicParticle::GetVerboseLevel(), and G4DynamicParticle::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4ParticleDefinition ()
Definition at line 43 of file pyG4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 43 of file pyG4ParticleDefinition.cc
References G4ParticleDefinition::DumpTable(), G4ParticleDefinition::GetAntiPDGEncoding(), G4ParticleDefinition::GetAntiQuarkContent(), G4ParticleDefinition::GetApplyCutsFlag(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetDecayTable(), G4ParticleDefinition::GetLeptonNumber(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGiConjugation(), G4ParticleDefinition::GetPDGiGParity(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiIsospin3(), G4ParticleDefinition::GetPDGiParity(), G4ParticleDefinition::GetPDGIsospin(), G4ParticleDefinition::GetPDGIsospin3(), G4ParticleDefinition::GetPDGiSpin(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), G4ParticleDefinition::GetPDGStable(), G4ParticleDefinition::GetPDGWidth(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::GetQuarkContent(), G4ParticleDefinition::GetVerboseLevel(), G4ParticleDefinition::IsShortLived(), G4ParticleDefinition::SetApplyCutsFlag(), G4ParticleDefinition::SetDecayTable(), G4ParticleDefinition::SetPDGLifeTime(), G4ParticleDefinition::SetPDGStable(), G4ParticleDefinition::SetProcessManager(), and G4ParticleDefinition::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().
void export_G4ParticleTable ()
Definition at line 97 of file pyG4ParticleTable.cc.
View newest version in sPHENIX GitHub at line 97 of file pyG4ParticleTable.cc
References G4ParticleTable::DumpTable(), G4ParticleTable::entries(), pyG4ParticleTable::f1_contains, pyG4ParticleTable::f1_FindAntiParticle, pyG4ParticleTable::f1_FindParticle, pyG4ParticleTable::f2_contains, pyG4ParticleTable::f2_FindAntiParticle, pyG4ParticleTable::f2_FindParticle, pyG4ParticleTable::f3_FindAntiParticle, pyG4ParticleTable::f3_FindParticle, G4ParticleTable::GetParticle(), pyG4ParticleTable::GetParticleList(), G4ParticleTable::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleTable::GetReadiness(), G4ParticleTable::GetVerboseLevel(), G4ParticleTable::SetReadiness(), G4ParticleTable::SetVerboseLevel(), and G4ParticleTable::size().
Referenced by BOOST_PYTHON_MODULE().
void export_G4PrimaryParticle ()
Definition at line 40 of file pyG4PrimaryParticle.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4PrimaryParticle.cc
References G4PrimaryParticle::GetCharge(), G4PrimaryParticle::GetG4code(), G4PrimaryParticle::GetMass(), G4PrimaryParticle::GetMomentum(), G4PrimaryParticle::GetNext(), G4PrimaryParticle::GetPDGcode(), G4PrimaryParticle::GetPolarization(), G4PrimaryParticle::GetPolX(), G4PrimaryParticle::GetPolY(), G4PrimaryParticle::GetPolZ(), G4PrimaryParticle::GetProperTime(), G4PrimaryParticle::GetPx(), G4PrimaryParticle::GetPy(), G4PrimaryParticle::GetPz(), G4PrimaryParticle::GetTrackID(), G4PrimaryParticle::GetWeight(), G4PrimaryParticle::Print(), G4PrimaryParticle::Set4Momentum(), G4PrimaryParticle::SetCharge(), G4PrimaryParticle::SetMass(), G4PrimaryParticle::SetMomentumDirection(), and G4PrimaryParticle::SetWeight().
Referenced by BOOST_PYTHON_MODULE().
void export_G4PrimaryVertex ()
Definition at line 50 of file pyG4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 50 of file pyG4PrimaryVertex.cc
References G4PrimaryVertex::GetNumberOfParticle(), G4PrimaryVertex::GetPosition(), G4PrimaryVertex::GetPrimary(), G4PrimaryVertex::GetT0(), G4PrimaryVertex::GetWeight(), G4PrimaryVertex::GetX0(), G4PrimaryVertex::GetY0(), G4PrimaryVertex::GetZ0(), G4PrimaryVertex::Print(), G4PrimaryVertex::SetPrimary(), and G4PrimaryVertex::SetWeight().
Referenced by BOOST_PYTHON_MODULE().
void export_PyG4ParticleList ()
Definition at line 82 of file pyG4ParticleList.cc.
View newest version in sPHENIX GitHub at line 82 of file pyG4ParticleList.cc
References PyG4ParticleList::p_begin(), and PyG4ParticleList::p_end().
Referenced by BOOST_PYTHON_MODULE().