ECCE @ EIC Software: G4INCL::NuclearPotential::NuclearPotentialConstant Class Reference
G4INCL::NuclearPotential::NuclearPotentialConstant Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNuclearPotentialConstant.hh>
Public Member Functions
NuclearPotentialConstant (const G4int A, const G4int Z, const G4bool pionPotential)
virtual ~NuclearPotentialConstant ()
G4double getNucleonPotential () const
G4double getDeltaPotential () const
virtual G4double computePotentialEnergy (const Particle *const p) const
Public Member Functions inherited from G4INCL::NuclearPotential::INuclearPotential
INuclearPotential (const G4int A, const G4int Z, const G4bool pionPot)
virtual ~INuclearPotential ()
G4bool hasPionPotential () const
Do we have a pion potential?
G4double getFermiEnergy (const Particle *const p) const
Return the Fermi energy for a particle.
G4double getFermiEnergy (const ParticleType t) const
Return the Fermi energy for a particle type.
G4double getSeparationEnergy (const Particle *const p) const
Return the separation energy for a particle.
G4double getSeparationEnergy (const ParticleType t) const
Return the separation energy for a particle type.
G4double getFermiMomentum (const Particle *const p) const
Return the Fermi momentum for a particle.
G4double getFermiMomentum (const ParticleType t) const
Return the Fermi momentum for a particle type.
Private Member Functions
void initialize ()
Private Attributes
G4double vNucleon
G4double vDelta
G4double vSigma
G4double vLambda
Additional Inherited Members
Protected Member Functions inherited from G4INCL::NuclearPotential::INuclearPotential
G4double computePionPotentialEnergy (const Particle *const p) const
Compute the potential energy for the given pion.
G4double computeKaonPotentialEnergy (const Particle *const p) const
Compute the potential energy for the given kaon.
G4double computePionResonancePotentialEnergy (const Particle *const p) const
Compute the potential energy for the given pion resonances (Eta, Omega and EtaPrime and Gamma also).
Protected Attributes inherited from G4INCL::NuclearPotential::INuclearPotential
const G4int theA
The mass number of the nucleus.
const G4int theZ
The charge number of the nucleus.
std::map< ParticleType, G4double > fermiEnergy
std::map< ParticleType, G4double > fermiMomentum
std::map< ParticleType, G4double > separationEnergy
Detailed Description
Definition at line 56 of file G4INCLNuclearPotentialConstant.hh.
View newest version in sPHENIX GitHub at line 56 of file G4INCLNuclearPotentialConstant.hh
Constructor & Destructor Documentation
G4INCL::NuclearPotential::NuclearPotentialConstant::NuclearPotentialConstant (const G4int A, const G4int Z, const G4bool pionPotential)
Definition at line 55 of file G4INCLNuclearPotentialConstant.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNuclearPotentialConstant.cc
References initialize().
G4INCL::NuclearPotential::NuclearPotentialConstant::~NuclearPotentialConstant () virtual
Definition at line 62 of file G4INCLNuclearPotentialConstant.cc.
View newest version in sPHENIX GitHub at line 62 of file G4INCLNuclearPotentialConstant.cc
Member Function Documentation
G4double G4INCL::NuclearPotential::NuclearPotentialConstant::computePotentialEnergy (const Particle *const p) const virtual
Implements G4INCL::NuclearPotential::INuclearPotential.
Definition at line 170 of file G4INCLNuclearPotentialConstant.cc.
View newest version in sPHENIX GitHub at line 170 of file G4INCLNuclearPotentialConstant.cc
References G4INCL::NuclearPotential::INuclearPotential::computeKaonPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionResonancePotentialEnergy(), G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::Particle::getType(), INCL_ERROR, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, G4INCL::UnknownParticle, vDelta, vLambda, vNucleon, and vSigma.
G4double G4INCL::NuclearPotential::NuclearPotentialConstant::getDeltaPotential () const inline
Definition at line 63 of file G4INCLNuclearPotentialConstant.hh.
View newest version in sPHENIX GitHub at line 63 of file G4INCLNuclearPotentialConstant.hh
References vDelta.
G4double G4INCL::NuclearPotential::NuclearPotentialConstant::getNucleonPotential () const inline
Definition at line 62 of file G4INCLNuclearPotentialConstant.hh.
View newest version in sPHENIX GitHub at line 62 of file G4INCLNuclearPotentialConstant.hh
References vNucleon.
void G4INCL::NuclearPotential::NuclearPotentialConstant::initialize () private
Definition at line 65 of file G4INCLNuclearPotentialConstant.cc.
View newest version in sPHENIX GitHub at line 65 of file G4INCLNuclearPotentialConstant.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::NuclearPotential::INuclearPotential::fermiEnergy, G4INCL::NuclearPotential::INuclearPotential::fermiMomentum, G4INCL::ParticleTable::getFermiMomentum, G4INCL::ParticleTable::getINCLMass(), G4INCL::ParticleTable::getSeparationEnergy, INCL_DEBUG, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::NuclearPotential::INuclearPotential::separationEnergy, G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, G4INCL::NuclearPotential::INuclearPotential::theA, G4INCL::NuclearPotential::INuclearPotential::theZ, vDelta, vLambda, vNucleon, and vSigma.
Referenced by NuclearPotentialConstant().
Member Data Documentation
G4double G4INCL::NuclearPotential::NuclearPotentialConstant::vDelta private
Definition at line 68 of file G4INCLNuclearPotentialConstant.hh.
View newest version in sPHENIX GitHub at line 68 of file G4INCLNuclearPotentialConstant.hh
Referenced by computePotentialEnergy(), getDeltaPotential(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialConstant::vLambda private
Definition at line 68 of file G4INCLNuclearPotentialConstant.hh.
View newest version in sPHENIX GitHub at line 68 of file G4INCLNuclearPotentialConstant.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialConstant::vNucleon private
Definition at line 68 of file G4INCLNuclearPotentialConstant.hh.
View newest version in sPHENIX GitHub at line 68 of file G4INCLNuclearPotentialConstant.hh
Referenced by computePotentialEnergy(), getNucleonPotential(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialConstant::vSigma private
Definition at line 68 of file G4INCLNuclearPotentialConstant.hh.
View newest version in sPHENIX GitHub at line 68 of file G4INCLNuclearPotentialConstant.hh
Referenced by computePotentialEnergy(), and initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNuclearPotentialConstant.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNuclearPotentialConstant.cc