ECCE @ EIC Software: G4FRofstream Class Reference
G4FRofstream Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/FukuiRenderer/include/G4FRofstream.hh>
Public Types
enum { SEND_BUFMAX = 1024 }
Public Member Functions
G4FRofstream ()
G4FRofstream (const char *filename)
virtual ~G4FRofstream ()
void Open (const char *filename)
void Close ()
G4bool IsOpen ()
void SendLine (const char *string)
Static Public Member Functions
static G4bool DoesFileExist (const char *filename)
Protected Attributes
G4bool flag_file_open
std::ofstream fout
Detailed Description
Definition at line 42 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 42 of file G4FRofstream.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
SEND_BUFMAX
Definition at line 45 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 45 of file G4FRofstream.hh
Constructor & Destructor Documentation
G4FRofstream::G4FRofstream () inline
Definition at line 50 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 50 of file G4FRofstream.hh
References false, and flag_file_open.
G4FRofstream::G4FRofstream (const char * filename) inline
Definition at line 111 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 111 of file G4FRofstream.hh
References false, flag_file_open, and Open().
G4FRofstream::~G4FRofstream () inline virtual
Definition at line 118 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 118 of file G4FRofstream.hh
References Close().
Member Function Documentation
void G4FRofstream::Close () inline
Definition at line 82 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 82 of file G4FRofstream.hh
References false, flag_file_open, fout, and IsOpen().
Referenced by G4DAWNFILEViewer::ClearView(), G4DAWNFILESceneHandler::EndSavingG4Prim(), and ~G4FRofstream().
G4bool G4FRofstream::DoesFileExist (const char * filename) inline static
Definition at line 98 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 98 of file G4FRofstream.hh
References false, and true.
Referenced by G4DAWNFILEViewer::ShowView().
G4bool G4FRofstream::IsOpen () inline
Definition at line 59 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 59 of file G4FRofstream.hh
References flag_file_open.
Referenced by G4DAWNFILEViewer::ClearView(), Close(), Open(), SendLine(), and G4DAWNFILESceneHandler::~G4DAWNFILESceneHandler().
void G4FRofstream::Open (const char * filename) inline
Definition at line 73 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FRofstream.hh
References flag_file_open, fout, IsOpen(), and true.
Referenced by G4DAWNFILESceneHandler::BeginSavingG4Prim(), G4DAWNFILEViewer::ClearView(), and G4FRofstream().
void G4FRofstream::SendLine (const char * string) inline
Definition at line 90 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 90 of file G4FRofstream.hh
References fout, G4endl, and IsOpen().
Member Data Documentation
G4bool G4FRofstream::flag_file_open protected
Definition at line 68 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 68 of file G4FRofstream.hh
Referenced by Close(), G4FRofstream(), IsOpen(), and Open().
std::ofstream G4FRofstream::fout protected
Definition at line 69 of file G4FRofstream.hh.
View newest version in sPHENIX GitHub at line 69 of file G4FRofstream.hh
Referenced by Close(), Open(), and SendLine().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/FukuiRenderer/include/G4FRofstream.hh