ECCE @ EIC Software: G4LatticeLogical Class Reference
G4LatticeLogical Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4LatticeLogical.hh>
Public Types
enum { MAXRES =322 }
Public Member Functions
G4LatticeLogical ()
virtual ~G4LatticeLogical ()
void SetVerboseLevel (G4int vb)
G4bool LoadMap (G4int, G4int, G4int, G4String)
G4bool Load_NMap (G4int, G4int, G4int, G4String)
virtual G4double MapKtoV (G4int, const G4ThreeVector &) const
virtual G4ThreeVector MapKtoVDir (G4int, const G4ThreeVector &) const
void Dump (std::ostream &os) const
void DumpMap (std::ostream &os, G4int pol, const G4String &name) const
void Dump_NMap (std::ostream &os, G4int pol, const G4String &name) const
void SetDynamicalConstants (G4double Beta, G4double Gamma, G4double Lambda, G4double Mu)
void SetScatteringConstant (G4double b)
void SetAnhDecConstant (G4double a)
void SetLDOS (G4double LDOS)
void SetSTDOS (G4double STDOS)
void SetFTDOS (G4double FTDOS)
G4double GetBeta () const
G4double GetGamma () const
G4double GetLambda () const
G4double GetMu () const
G4double GetScatteringConstant () const
G4double GetAnhDecConstant () const
G4double GetLDOS () const
G4double GetSTDOS () const
G4double GetFTDOS () const
Private Attributes
G4int verboseLevel
G4double fMap [3][MAXRES][MAXRES]
G4ThreeVector fN_map [3][MAXRES][MAXRES]
G4int fVresTheta
G4int fVresPhi
G4int fDresTheta
G4int fDresPhi
G4double fA
G4double fB
G4double fLDOS
G4double fSTDOS
G4double fFTDOS
G4double fBeta
G4double fGamma
G4double fLambda
G4double fMu
Detailed Description
Definition at line 41 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 41 of file G4LatticeLogical.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
MAXRES
Definition at line 85 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 85 of file G4LatticeLogical.hh
Constructor & Destructor Documentation
G4LatticeLogical::G4LatticeLogical ()
Definition at line 39 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 39 of file G4LatticeLogical.cc
References fMap, fN_map, k, MAXRES, and CLHEP::Hep3Vector::set().
G4LatticeLogical::~G4LatticeLogical () virtual
Definition at line 53 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 53 of file G4LatticeLogical.cc
Member Function Documentation
void G4LatticeLogical::Dump (std::ostream & os) const
Definition at line 201 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 201 of file G4LatticeLogical.cc
References Dump_NMap(), DumpMap(), fA, fB, fBeta, fFTDOS, fGamma, fLambda, fLDOS, fMu, and fSTDOS.
Referenced by operator<<().
void G4LatticeLogical::Dump_NMap (std::ostream & os, G4int pol, const G4String & name) const
Definition at line 228 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 228 of file G4LatticeLogical.cc
References fDresPhi, fDresTheta, fN_map, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by Dump().
void G4LatticeLogical::DumpMap (std::ostream & os, G4int pol, const G4String & name) const
Definition at line 216 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 216 of file G4LatticeLogical.cc
References fMap, fVresPhi, and fVresTheta.
Referenced by Dump().
G4double G4LatticeLogical::GetAnhDecConstant () const inline
Definition at line 79 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 79 of file G4LatticeLogical.hh
References fA.
Referenced by G4LatticePhysical::GetAnhDecConstant().
G4double G4LatticeLogical::GetBeta () const inline
Definition at line 74 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 74 of file G4LatticeLogical.hh
References fBeta.
Referenced by G4LatticePhysical::GetBeta().
G4double G4LatticeLogical::GetFTDOS () const inline
Definition at line 82 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 82 of file G4LatticeLogical.hh
References fFTDOS.
Referenced by G4LatticePhysical::GetFTDOS().
G4double G4LatticeLogical::GetGamma () const inline
Definition at line 75 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 75 of file G4LatticeLogical.hh
References fGamma.
Referenced by G4LatticePhysical::GetGamma().
G4double G4LatticeLogical::GetLambda () const inline
Definition at line 76 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 76 of file G4LatticeLogical.hh
References fLambda.
Referenced by G4LatticePhysical::GetLambda().
G4double G4LatticeLogical::GetLDOS () const inline
Definition at line 80 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 80 of file G4LatticeLogical.hh
References fLDOS.
Referenced by G4LatticePhysical::GetLDOS().
G4double G4LatticeLogical::GetMu () const inline
Definition at line 77 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 77 of file G4LatticeLogical.hh
References fMu.
Referenced by G4LatticePhysical::GetMu().
G4double G4LatticeLogical::GetScatteringConstant () const inline
Definition at line 78 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 78 of file G4LatticeLogical.hh
References fB.
Referenced by G4LatticePhysical::GetScatteringConstant().
G4double G4LatticeLogical::GetSTDOS () const inline
Definition at line 81 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 81 of file G4LatticeLogical.hh
References fSTDOS.
Referenced by G4LatticePhysical::GetSTDOS().
G4bool G4LatticeLogical::Load_NMap (G4int tRes, G4int pRes, G4int polarizationState, G4String map)
Definition at line 97 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 97 of file G4LatticeLogical.cc
References G4String::data(), dir, fDresPhi, fDresTheta, fN_map, G4cerr, G4cout, G4endl, MAXRES, phi, CLHEP::Hep3Vector::set(), theta(), CLHEP::Hep3Vector::unit(), verboseLevel, x, y, and z.
Referenced by G4LatticeReader::ProcessNMap().
G4bool G4LatticeLogical::LoadMap (G4int tRes, G4int pRes, G4int polarizationState, G4String map)
Definition at line 61 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 61 of file G4LatticeLogical.cc
References G4String::data(), fMap, fVresPhi, fVresTheta, G4cerr, G4cout, G4endl, m, MAXRES, phi, theta(), and verboseLevel.
Referenced by G4LatticeReader::ProcessMap().
G4double G4LatticeLogical::MapKtoV (G4int polarizationState, const G4ThreeVector & k) const virtual
Definition at line 135 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 135 of file G4LatticeLogical.cc
References fMap, fVresPhi, fVresTheta, G4cout, G4endl, CLHEP::Hep3Vector::getPhi(), CLHEP::Hep3Vector::getTheta(), int(), phi, pi, theta(), twopi, and verboseLevel.
Referenced by G4LatticePhysical::MapKtoV().
G4ThreeVector G4LatticeLogical::MapKtoVDir (G4int polarizationState, const G4ThreeVector & k) const virtual
Definition at line 171 of file G4LatticeLogical.cc.
View newest version in sPHENIX GitHub at line 171 of file G4LatticeLogical.cc
References fDresPhi, fDresTheta, fN_map, G4cout, G4endl, CLHEP::Hep3Vector::getPhi(), CLHEP::Hep3Vector::getTheta(), int(), phi, pi, theta(), and verboseLevel.
Referenced by G4LatticePhysical::MapKtoVDir().
void G4LatticeLogical::SetAnhDecConstant (G4double a) inline
Definition at line 69 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 69 of file G4LatticeLogical.hh
References a, and fA.
Referenced by G4LatticeReader::ProcessValue().
void G4LatticeLogical::SetDynamicalConstants (G4double Beta, G4double Gamma, G4double Lambda, G4double Mu) inline
Definition at line 63 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LatticeLogical.hh
References fBeta, fGamma, fLambda, fMu, and G4INCL::Lambda.
Referenced by G4LatticeReader::ProcessConstants().
void G4LatticeLogical::SetFTDOS (G4double FTDOS) inline
Definition at line 72 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 72 of file G4LatticeLogical.hh
References fFTDOS.
Referenced by G4LatticeReader::ProcessValue().
void G4LatticeLogical::SetLDOS (G4double LDOS) inline
Definition at line 70 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 70 of file G4LatticeLogical.hh
References fLDOS.
Referenced by G4LatticeReader::ProcessValue().
void G4LatticeLogical::SetScatteringConstant (G4double b) inline
Definition at line 68 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 68 of file G4LatticeLogical.hh
References b, and fB.
Referenced by G4LatticeReader::ProcessValue().
void G4LatticeLogical::SetSTDOS (G4double STDOS) inline
Definition at line 71 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 71 of file G4LatticeLogical.hh
References fSTDOS.
Referenced by G4LatticeReader::ProcessValue().
void G4LatticeLogical::SetVerboseLevel (G4int vb) inline
Definition at line 46 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 46 of file G4LatticeLogical.hh
References verboseLevel.
Member Data Documentation
G4double G4LatticeLogical::fA private
Definition at line 98 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 98 of file G4LatticeLogical.hh
Referenced by Dump(), GetAnhDecConstant(), and SetAnhDecConstant().
G4double G4LatticeLogical::fB private
Definition at line 99 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 99 of file G4LatticeLogical.hh
Referenced by Dump(), GetScatteringConstant(), and SetScatteringConstant().
G4double G4LatticeLogical::fBeta private
Definition at line 103 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 103 of file G4LatticeLogical.hh
Referenced by Dump(), GetBeta(), and SetDynamicalConstants().
G4int G4LatticeLogical::fDresPhi private
Definition at line 96 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 96 of file G4LatticeLogical.hh
Referenced by Dump_NMap(), Load_NMap(), and MapKtoVDir().
G4int G4LatticeLogical::fDresTheta private
Definition at line 95 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 95 of file G4LatticeLogical.hh
Referenced by Dump_NMap(), Load_NMap(), and MapKtoVDir().
G4double G4LatticeLogical::fFTDOS private
Definition at line 102 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 102 of file G4LatticeLogical.hh
Referenced by Dump(), GetFTDOS(), and SetFTDOS().
G4double G4LatticeLogical::fGamma private
Definition at line 103 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 103 of file G4LatticeLogical.hh
Referenced by Dump(), GetGamma(), and SetDynamicalConstants().
G4double G4LatticeLogical::fLambda private
Definition at line 103 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 103 of file G4LatticeLogical.hh
Referenced by Dump(), GetLambda(), and SetDynamicalConstants().
G4double G4LatticeLogical::fLDOS private
Definition at line 100 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 100 of file G4LatticeLogical.hh
Referenced by Dump(), GetLDOS(), and SetLDOS().
G4double G4LatticeLogical::fMap[3][MAXRES][MAXRES] private
Definition at line 90 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 90 of file G4LatticeLogical.hh
Referenced by DumpMap(), G4LatticeLogical(), LoadMap(), and MapKtoV().
G4double G4LatticeLogical::fMu private
Definition at line 103 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 103 of file G4LatticeLogical.hh
Referenced by Dump(), GetMu(), and SetDynamicalConstants().
G4ThreeVector G4LatticeLogical::fN_map[3][MAXRES][MAXRES] private
Definition at line 91 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 91 of file G4LatticeLogical.hh
Referenced by Dump_NMap(), G4LatticeLogical(), Load_NMap(), and MapKtoVDir().
G4double G4LatticeLogical::fSTDOS private
Definition at line 101 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 101 of file G4LatticeLogical.hh
Referenced by Dump(), GetSTDOS(), and SetSTDOS().
G4int G4LatticeLogical::fVresPhi private
Definition at line 94 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 94 of file G4LatticeLogical.hh
Referenced by DumpMap(), LoadMap(), and MapKtoV().
G4int G4LatticeLogical::fVresTheta private
Definition at line 93 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 93 of file G4LatticeLogical.hh
Referenced by DumpMap(), LoadMap(), and MapKtoV().
G4int G4LatticeLogical::verboseLevel private
Definition at line 88 of file G4LatticeLogical.hh.
View newest version in sPHENIX GitHub at line 88 of file G4LatticeLogical.hh
Referenced by Load_NMap(), LoadMap(), MapKtoV(), MapKtoVDir(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4LatticeLogical.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4LatticeLogical.cc