ECCE @ EIC Software: G4CrossSectionDataSet Class Reference
G4CrossSectionDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4CrossSectionDataSet.hh>
Public Member Functions
G4CrossSectionDataSet (G4VDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn)
virtual ~G4CrossSectionDataSet ()
virtual G4double FindValue (G4double e, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4VEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4VEMDataSet *dataSet)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual const G4DataVector & GetLogEnergies (G4int componentId) const
virtual const G4DataVector & GetLogData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *values, G4int componentId)
virtual void SetLogEnergiesData (G4DataVector *x, G4DataVector *values, G4DataVector *log_x, G4DataVector *log_values, G4int componentId)
virtual G4bool LoadData (const G4String &argFileName)
virtual G4bool LoadNonLogData (const G4String &argFileName)
virtual G4bool SaveData (const G4String &argFileName) const
virtual G4double RandomSelect (G4int) const
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Private Member Functions
G4String FullFileName (const G4String &argFileName) const
G4CrossSectionDataSet ()
G4CrossSectionDataSet (const G4CrossSectionDataSet &copy)
G4CrossSectionDataSet & operator= (const G4CrossSectionDataSet &right)
G4double GetUnitEnergies () const
G4double GetUnitData () const
const G4VDataSetAlgorithm * GetAlgorithm () const
void CleanUpComponents (void)
Private Attributes
std::vector< G4VEMDataSet * > components
G4int z
G4VDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
Detailed Description
Definition at line 54 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4CrossSectionDataSet.hh
Constructor & Destructor Documentation
G4CrossSectionDataSet::G4CrossSectionDataSet (G4VDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn)
Definition at line 64 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 64 of file G4CrossSectionDataSet.cc
References z.
G4CrossSectionDataSet::~G4CrossSectionDataSet () virtual
Definition at line 75 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 75 of file G4CrossSectionDataSet.cc
References algorithm, and CleanUpComponents().
G4CrossSectionDataSet::G4CrossSectionDataSet () private
G4CrossSectionDataSet::G4CrossSectionDataSet (const G4CrossSectionDataSet & copy) private
Member Function Documentation
virtual void G4CrossSectionDataSet::AddComponent (G4VEMDataSet * dataSet) inline virtual
Implements G4VEMDataSet.
Definition at line 71 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 71 of file G4CrossSectionDataSet.hh
References components.
Referenced by LoadData(), and LoadNonLogData().
void G4CrossSectionDataSet::CleanUpComponents (void) private
Definition at line 559 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 559 of file G4CrossSectionDataSet.cc
References components.
Referenced by LoadData(), LoadNonLogData(), and ~G4CrossSectionDataSet().
G4double G4CrossSectionDataSet::FindValue (G4double e, G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 481 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 481 of file G4CrossSectionDataSet.cc
References components.
Referenced by G4ecpssrBaseKxsModel::CalculateCrossSection().
G4String G4CrossSectionDataSet::FullFileName (const G4String & argFileName) const private
Definition at line 463 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 463 of file G4CrossSectionDataSet.cc
References FatalException, and G4Exception().
Referenced by LoadData(), LoadNonLogData(), and SaveData().
const G4VDataSetAlgorithm* G4CrossSectionDataSet::GetAlgorithm () const inline private
Definition at line 127 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 127 of file G4CrossSectionDataSet.hh
References algorithm.
Referenced by LoadData(), and LoadNonLogData().
virtual const G4VEMDataSet* G4CrossSectionDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 68 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 68 of file G4CrossSectionDataSet.hh
References components.
Referenced by GetData(), GetEnergies(), GetLogData(), GetLogEnergies(), PrintData(), and SaveData().
virtual const G4DataVector& G4CrossSectionDataSet::GetData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 80 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 80 of file G4CrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetData().
virtual const G4DataVector& G4CrossSectionDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 77 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 77 of file G4CrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetEnergies().
Referenced by SaveData().
virtual const G4DataVector& G4CrossSectionDataSet::GetLogData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 86 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 86 of file G4CrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogData().
virtual const G4DataVector& G4CrossSectionDataSet::GetLogEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 83 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 83 of file G4CrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogEnergies().
G4double G4CrossSectionDataSet::GetUnitData () const inline private
Definition at line 126 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 126 of file G4CrossSectionDataSet.hh
References unitData.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4double G4CrossSectionDataSet::GetUnitEnergies () const inline private
Definition at line 125 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 125 of file G4CrossSectionDataSet.hh
References unitEnergies.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4bool G4CrossSectionDataSet::LoadData (const G4String & argFileName) virtual
Implements G4VEMDataSet.
Definition at line 83 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 83 of file G4CrossSectionDataSet.cc
References AddComponent(), c, CleanUpComponents(), e, FatalException, FullFileName(), G4Exception(), GetAlgorithm(), GetUnitData(), GetUnitEnergies(), in, and message().
Referenced by G4ecpssrBaseKxsModel::G4ecpssrBaseKxsModel().
G4bool G4CrossSectionDataSet::LoadNonLogData (const G4String & argFileName) virtual
Implements G4VEMDataSet.
Definition at line 250 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 250 of file G4CrossSectionDataSet.cc
References AddComponent(), c, CleanUpComponents(), e, FatalException, FullFileName(), G4Exception(), GetAlgorithm(), GetUnitData(), GetUnitEnergies(), in, and message().
virtual size_t G4CrossSectionDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 74 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 74 of file G4CrossSectionDataSet.hh
References components.
Referenced by PrintData(), and SaveData().
G4CrossSectionDataSet& G4CrossSectionDataSet::operator= (const G4CrossSectionDataSet & right) private
void G4CrossSectionDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 499 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 499 of file G4CrossSectionDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4VEMDataSet::PrintData().
virtual G4double G4CrossSectionDataSet::RandomSelect (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 102 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 102 of file G4CrossSectionDataSet.hh
G4bool G4CrossSectionDataSet::SaveData (const G4String & argFileName) const virtual
Implements G4VEMDataSet.
Definition at line 395 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 395 of file G4CrossSectionDataSet.cc
References FatalException, FullFileName(), G4Exception(), GetComponent(), G4VEMDataSet::GetData(), GetEnergies(), GetUnitData(), GetUnitEnergies(), k, left, message(), n, and NumberOfComponents().
void G4CrossSectionDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * values, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 517 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 517 of file G4CrossSectionDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetEnergiesData().
void G4CrossSectionDataSet::SetLogEnergiesData (G4DataVector * x, G4DataVector * values, G4DataVector * log_x, G4DataVector * log_values, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 537 of file G4CrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 537 of file G4CrossSectionDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetLogEnergiesData().
Member Data Documentation
G4VDataSetAlgorithm* G4CrossSectionDataSet::algorithm private
Definition at line 120 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 120 of file G4CrossSectionDataSet.hh
Referenced by GetAlgorithm(), and ~G4CrossSectionDataSet().
std::vector<G4VEMDataSet*> G4CrossSectionDataSet::components private
Definition at line 116 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 116 of file G4CrossSectionDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), FindValue(), GetComponent(), NumberOfComponents(), SetEnergiesData(), and SetLogEnergiesData().
G4double G4CrossSectionDataSet::unitData private
Definition at line 123 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 123 of file G4CrossSectionDataSet.hh
Referenced by GetUnitData().
G4double G4CrossSectionDataSet::unitEnergies private
Definition at line 122 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 122 of file G4CrossSectionDataSet.hh
Referenced by GetUnitEnergies().
G4int G4CrossSectionDataSet::z private
Definition at line 118 of file G4CrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 118 of file G4CrossSectionDataSet.hh
Referenced by G4CrossSectionDataSet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4CrossSectionDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4CrossSectionDataSet.cc