ECCE @ EIC Software: G4Hdf5AnalysisManager Class Reference
G4Hdf5AnalysisManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/hdf5/include/G4Hdf5AnalysisManager.hh>
Public Member Functions
G4Hdf5AnalysisManager (G4bool isMaster=true)
~G4Hdf5AnalysisManager ()
tools::hdf5::ntuple * GetNtuple () const
tools::hdf5::ntuple * GetNtuple (G4int ntupleId) const
std::vector
< tools::hdf5::ntuple * >
::iterator BeginNtuple ()
std::vector
< tools::hdf5::ntuple * >
::iterator EndNtuple ()
std::vector
< tools::hdf5::ntuple * >
::const_iterator BeginConstNtuple () const
std::vector
< tools::hdf5::ntuple * >
::const_iterator EndConstNtuple () const
Public Member Functions inherited from G4ToolsAnalysisManager
G4ToolsAnalysisManager (const G4String &type, G4bool isMaster=true)
virtual ~G4ToolsAnalysisManager ()
tools::histo::h1d * GetH1 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
tools::histo::h2d * GetH2 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
tools::histo::h3d * GetH3 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
tools::histo::p1d * GetP1 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
tools::histo::p2d * GetP2 (G4int id, G4bool warn=true, G4bool onlyIfActive=true) const
std::vector< tools::histo::h1d * >
::iterator BeginH1 ()
std::vector< tools::histo::h1d * >
::iterator EndH1 ()
std::vector< tools::histo::h1d * >
::const_iterator BeginConstH1 () const
std::vector< tools::histo::h1d * >
::const_iterator EndConstH1 () const
std::vector< tools::histo::h2d * >
::iterator BeginH2 ()
std::vector< tools::histo::h2d * >
::iterator EndH2 ()
std::vector< tools::histo::h2d * >
::const_iterator BeginConstH2 () const
std::vector< tools::histo::h2d * >
::const_iterator EndConstH2 () const
std::vector< tools::histo::h3d * >
::iterator BeginH3 ()
std::vector< tools::histo::h3d * >
::iterator EndH3 ()
std::vector< tools::histo::h3d * >
::const_iterator BeginConstH3 () const
std::vector< tools::histo::h3d * >
::const_iterator EndConstH3 () const
std::vector< tools::histo::p1d * >
::iterator BeginP1 ()
std::vector< tools::histo::p1d * >
::iterator EndP1 ()
std::vector< tools::histo::p1d * >
::const_iterator BeginConstP1 () const
std::vector< tools::histo::p1d * >
::const_iterator EndConstP1 () const
std::vector< tools::histo::p2d * >
::iterator BeginP2 ()
std::vector< tools::histo::p2d * >
::iterator EndP2 ()
std::vector< tools::histo::p2d * >
::const_iterator BeginConstP2 () const
std::vector< tools::histo::p2d * >
::const_iterator EndConstP2 () const
std::vector
< tools::wroot::ntuple * >
::iterator BeginNtuple ()
std::vector
< tools::wroot::ntuple * >
::iterator EndNtuple ()
std::vector
< tools::wroot::ntuple * >
::const_iterator BeginConstNtuple () const
std::vector
< tools::wroot::ntuple * >
::const_iterator EndConstNtuple () const
Public Member Functions inherited from G4VAnalysisManager
G4VAnalysisManager (const G4String &type, G4bool isMaster)
virtual ~G4VAnalysisManager ()
G4bool OpenFile (const G4String &fileName="")
G4bool Write ()
G4bool CloseFile (G4bool reset=true)
G4bool Merge (tools::histo::hmpi *hmpi)
G4bool Plot ()
G4bool IsOpenFile () const
G4bool SetFileName (const G4String &fileName)
G4bool SetHistoDirectoryName (const G4String &dirName)
G4bool SetNtupleDirectoryName (const G4String &dirName)
void SetCompressionLevel (G4int level)
G4String GetFileName () const
G4String GetHistoDirectoryName () const
G4String GetNtupleDirectoryName () const
G4int GetCompressionLevel () const
G4int CreateH1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4int CreateH1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none")
G4int CreateH2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4int CreateH2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4int CreateH3 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear", const G4String &zbinSchemeName="linear")
G4int CreateH3 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool SetH1 (G4int id, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4bool SetH1 (G4int id, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none")
G4bool SetH2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4bool SetH2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4bool SetH3 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nzbins, G4double zmin, G4double zmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear", const G4String &zbinSchemeName="linear")
G4bool SetH3 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool ScaleH1 (G4int id, G4double factor)
G4bool ScaleH2 (G4int id, G4double factor)
G4bool ScaleH3 (G4int id, G4double factor)
G4int CreateP1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear")
G4int CreateP1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4int CreateP2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4int CreateP2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool SetP1 (G4int id, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear")
G4bool SetP1 (G4int id, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4bool SetP2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4bool SetP2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool ScaleP1 (G4int id, G4double factor)
G4bool ScaleP2 (G4int id, G4double factor)
G4int CreateNtuple (const G4String &name, const G4String &title)
G4int CreateNtupleIColumn (const G4String &name)
G4int CreateNtupleFColumn (const G4String &name)
G4int CreateNtupleDColumn (const G4String &name)
G4int CreateNtupleSColumn (const G4String &name)
G4int CreateNtupleIColumn (const G4String &name, std::vector< int > &vector)
G4int CreateNtupleFColumn (const G4String &name, std::vector< float > &vector)
G4int CreateNtupleDColumn (const G4String &name, std::vector< double > &vector)
void FinishNtuple ()
G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > &vector)
G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > &vector)
G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > &vector)
void FinishNtuple (G4int ntupleId)
virtual void SetNtupleMerging (G4bool mergeNtuples, G4int nofReducedNtupleFiles=0)
virtual void SetNtupleRowWise (G4bool rowWise, G4bool rowMode=true)
virtual void SetBasketSize (unsigned int basketSize)
virtual void SetBasketEntries (unsigned int basketEntries)
G4bool SetFirstHistoId (G4int firstId)
G4bool SetFirstH1Id (G4int firstId)
G4bool SetFirstH2Id (G4int firstId)
G4bool SetFirstH3Id (G4int firstId)
G4bool SetFirstProfileId (G4int firstId)
G4bool SetFirstP1Id (G4int firstId)
G4bool SetFirstP2Id (G4int firstId)
G4bool SetFirstNtupleId (G4int firstId)
G4bool SetFirstNtupleColumnId (G4int firstId)
G4bool FillH1 (G4int id, G4double value, G4double weight=1.0)
G4bool FillH2 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0)
G4bool FillH3 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0)
G4bool FillP1 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0)
G4bool FillP2 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0)
G4bool FillNtupleIColumn (G4int id, G4int value)
G4bool FillNtupleFColumn (G4int id, G4float value)
G4bool FillNtupleDColumn (G4int id, G4double value)
G4bool FillNtupleSColumn (G4int id, const G4String &value)
G4bool AddNtupleRow ()
G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)
G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)
G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)
G4bool FillNtupleSColumn (G4int ntupleId, G4int id, const G4String &value)
G4bool AddNtupleRow (G4int ntupleId)
void SetActivation (G4bool activation)
G4bool GetActivation () const
G4bool IsActive () const
G4bool IsAscii () const
G4bool IsPlotting () const
G4int GetFirstH1Id () const
G4int GetFirstH2Id () const
G4int GetFirstH3Id () const
G4int GetFirstP1Id () const
G4int GetFirstP2Id () const
G4int GetFirstNtupleId () const
G4int GetFirstNtupleColumnId () const
G4int GetNofH1s () const
G4int GetNofH2s () const
G4int GetNofH3s () const
G4int GetNofP1s () const
G4int GetNofP2s () const
G4int GetNofNtuples () const
G4int GetH1Id (const G4String &name, G4bool warn=true) const
G4int GetH2Id (const G4String &name, G4bool warn=true) const
G4int GetH3Id (const G4String &name, G4bool warn=true) const
G4int GetP1Id (const G4String &name, G4bool warn=true) const
G4int GetP2Id (const G4String &name, G4bool warn=true) const
void SetH1Activation (G4bool activation)
void SetH1Activation (G4int id, G4bool activation)
void SetH1Ascii (G4int id, G4bool ascii)
void SetH1Plotting (G4int id, G4bool plotting)
void SetH2Activation (G4bool activation)
void SetH2Activation (G4int id, G4bool activation)
void SetH2Ascii (G4int id, G4bool ascii)
void SetH2Plotting (G4int id, G4bool plotting)
void SetH3Activation (G4bool activation)
void SetH3Activation (G4int id, G4bool activation)
void SetH3Ascii (G4int id, G4bool ascii)
void SetH3Plotting (G4int id, G4bool plotting)
void SetP1Activation (G4bool activation)
void SetP1Activation (G4int id, G4bool activation)
void SetP1Ascii (G4int id, G4bool ascii)
void SetP1Plotting (G4int id, G4bool plotting)
void SetP2Activation (G4bool activation)
void SetP2Activation (G4int id, G4bool activation)
void SetP2Ascii (G4int id, G4bool ascii)
void SetP2Plotting (G4int id, G4bool plotting)
void SetNtupleActivation (G4bool activation)
void SetNtupleActivation (G4int id, G4bool activation)
G4int GetH1Nbins (G4int id) const
G4double GetH1Xmin (G4int id) const
G4double GetH1Xmax (G4int id) const
G4double GetH1Width (G4int id) const
G4int GetH2Nxbins (G4int id) const
G4double GetH2Xmin (G4int id) const
G4double GetH2Xmax (G4int id) const
G4double GetH2XWidth (G4int id) const
G4int GetH2Nybins (G4int id) const
G4double GetH2Ymin (G4int id) const
G4double GetH2Ymax (G4int id) const
G4double GetH2YWidth (G4int id) const
G4int GetH3Nxbins (G4int id) const
G4double GetH3Xmin (G4int id) const
G4double GetH3Xmax (G4int id) const
G4double GetH3XWidth (G4int id) const
G4int GetH3Nybins (G4int id) const
G4double GetH3Ymin (G4int id) const
G4double GetH3Ymax (G4int id) const
G4double GetH3YWidth (G4int id) const
G4int GetH3Nzbins (G4int id) const
G4double GetH3Zmin (G4int id) const
G4double GetH3Zmax (G4int id) const
G4double GetH3ZWidth (G4int id) const
G4int GetP1Nbins (G4int id) const
G4double GetP1Xmin (G4int id) const
G4double GetP1Xmax (G4int id) const
G4double GetP1XWidth (G4int id) const
G4double GetP1Ymin (G4int id) const
G4double GetP1Ymax (G4int id) const
G4int GetP2Nxbins (G4int id) const
G4double GetP2Xmin (G4int id) const
G4double GetP2Xmax (G4int id) const
G4double GetP2XWidth (G4int id) const
G4int GetP2Nybins (G4int id) const
G4double GetP2Ymin (G4int id) const
G4double GetP2Ymax (G4int id) const
G4double GetP2YWidth (G4int id) const
G4double GetP2Zmin (G4int id) const
G4double GetP2Zmax (G4int id) const
G4String GetH1Name (G4int id) const
G4double GetH1Unit (G4int id) const
G4bool GetH1Activation (G4int id) const
G4bool GetH1Ascii (G4int id) const
G4bool GetH1Plotting (G4int id) const
G4String GetH2Name (G4int id) const
G4double GetH2XUnit (G4int id) const
G4double GetH2YUnit (G4int id) const
G4bool GetH2Activation (G4int id) const
G4bool GetH2Ascii (G4int id) const
G4bool GetH2Plotting (G4int id) const
G4String GetH3Name (G4int id) const
G4double GetH3XUnit (G4int id) const
G4double GetH3YUnit (G4int id) const
G4double GetH3ZUnit (G4int id) const
G4bool GetH3Activation (G4int id) const
G4bool GetH3Ascii (G4int id) const
G4bool GetH3Plotting (G4int id) const
G4String GetP1Name (G4int id) const
G4double GetP1XUnit (G4int id) const
G4double GetP1YUnit (G4int id) const
G4bool GetP1Activation (G4int id) const
G4bool GetP1Ascii (G4int id) const
G4bool GetP1Plotting (G4int id) const
G4String GetP2Name (G4int id) const
G4double GetP2XUnit (G4int id) const
G4double GetP2YUnit (G4int id) const
G4double GetP2ZUnit (G4int id) const
G4bool GetP2Activation (G4int id) const
G4bool GetP2Ascii (G4int id) const
G4bool GetP2Plotting (G4int id) const
G4bool GetNtupleActivation (G4int id) const
G4bool SetH1Title (G4int id, const G4String &title)
G4bool SetH1XAxisTitle (G4int id, const G4String &title)
G4bool SetH1YAxisTitle (G4int id, const G4String &title)
G4bool SetH1XAxisIsLog (G4int id, G4bool isLog)
G4bool SetH1YAxisIsLog (G4int id, G4bool isLog)
G4bool SetH2Title (G4int id, const G4String &title)
G4bool SetH2XAxisTitle (G4int id, const G4String &title)
G4bool SetH2YAxisTitle (G4int id, const G4String &title)
G4bool SetH2ZAxisTitle (G4int id, const G4String &title)
G4bool SetH2XAxisIsLog (G4int id, G4bool isLog)
G4bool SetH2YAxisIsLog (G4int id, G4bool isLog)
G4bool SetH2ZAxisIsLog (G4int id, G4bool isLog)
G4bool SetH3Title (G4int id, const G4String &title)
G4bool SetH3XAxisTitle (G4int id, const G4String &title)
G4bool SetH3YAxisTitle (G4int id, const G4String &title)
G4bool SetH3ZAxisTitle (G4int id, const G4String &title)
G4bool SetH3XAxisIsLog (G4int id, G4bool isLog)
G4bool SetH3YAxisIsLog (G4int id, G4bool isLog)
G4bool SetH3ZAxisIsLog (G4int id, G4bool isLog)
G4bool SetP1Title (G4int id, const G4String &title)
G4bool SetP1XAxisTitle (G4int id, const G4String &title)
G4bool SetP1YAxisTitle (G4int id, const G4String &title)
G4bool SetP1XAxisIsLog (G4int id, G4bool isLog)
G4bool SetP1YAxisIsLog (G4int id, G4bool isLog)
G4bool SetP2Title (G4int id, const G4String &title)
G4bool SetP2XAxisTitle (G4int id, const G4String &title)
G4bool SetP2YAxisTitle (G4int id, const G4String &title)
G4bool SetP2ZAxisTitle (G4int id, const G4String &title)
G4bool SetP2XAxisIsLog (G4int id, G4bool isLog)
G4bool SetP2YAxisIsLog (G4int id, G4bool isLog)
G4bool SetP2ZAxisIsLog (G4int id, G4bool isLog)
G4String GetH1Title (G4int id) const
G4String GetH1XAxisTitle (G4int id) const
G4String GetH1YAxisTitle (G4int id) const
G4bool GetH1XAxisIsLog (G4int id) const
G4bool GetH1YAxisIsLog (G4int id) const
G4String GetH2Title (G4int id) const
G4String GetH2XAxisTitle (G4int id) const
G4String GetH2YAxisTitle (G4int id) const
G4String GetH2ZAxisTitle (G4int id) const
G4bool GetH2XAxisIsLog (G4int id) const
G4bool GetH2YAxisIsLog (G4int id) const
G4bool GetH2ZAxisIsLog (G4int id) const
G4String GetH3Title (G4int id) const
G4String GetH3XAxisTitle (G4int id) const
G4String GetH3YAxisTitle (G4int id) const
G4String GetH3ZAxisTitle (G4int id) const
G4bool GetH3XAxisIsLog (G4int id) const
G4bool GetH3YAxisIsLog (G4int id) const
G4bool GetH3ZAxisIsLog (G4int id) const
G4String GetP1Title (G4int id) const
G4String GetP1XAxisTitle (G4int id) const
G4String GetP1YAxisTitle (G4int id) const
G4bool GetP1XAxisIsLog (G4int id) const
G4bool GetP1YAxisIsLog (G4int id) const
G4String GetP2Title (G4int id) const
G4String GetP2XAxisTitle (G4int id) const
G4String GetP2YAxisTitle (G4int id) const
G4String GetP2ZAxisTitle (G4int id) const
G4bool GetP2XAxisIsLog (G4int id) const
G4bool GetP2YAxisIsLog (G4int id) const
G4bool GetP2ZAxisIsLog (G4int id) const
void SetVerboseLevel (G4int verboseLevel)
G4int GetVerboseLevel () const
G4String GetType () const
G4String GetFileType () const
Static Public Member Functions
static G4Hdf5AnalysisManager * Instance ()
static G4bool IsInstance ()
Static Public Member Functions inherited from G4ToolsAnalysisManager
static G4ToolsAnalysisManager * Instance ()
static G4bool IsInstance ()
Protected Member Functions
virtual G4bool OpenFileImpl (const G4String &fileName) final
virtual G4bool WriteImpl () final
virtual G4bool CloseFileImpl (G4bool reset) final
virtual G4bool IsOpenFileImpl () const final
Protected Member Functions inherited from G4ToolsAnalysisManager
virtual G4bool PlotImpl () final
virtual G4bool MergeImpl (tools::histo::hmpi *hmpi) final
G4bool Reset ()
Protected Member Functions inherited from G4VAnalysisManager
void SetH1Manager (G4VH1Manager *h1Manager)
void SetH2Manager (G4VH2Manager *h2Manager)
void SetH3Manager (G4VH3Manager *h3Manager)
void SetP1Manager (G4VP1Manager *p1Manager)
void SetP2Manager (G4VP2Manager *p2Manager)
void SetNtupleManager (G4VNtupleManager *ntupleManager)
void SetFileManager (std::shared_ptr< G4VFileManager > fileManager)
void SetPlotManager (std::shared_ptr< G4PlotManager > plotManager)
G4bool WriteAscii (const G4String &fileName)
Private Member Functions
template<typename T >
G4bool WriteHn (const std::vector< T * > &htVector, const std::vector< G4HnInformation * > &hnVector, const G4String &directoryName, const G4String &hnType)
template<typename T >
G4bool WritePn (const std::vector< T * > &htVector, const std::vector< G4HnInformation * > &hnVector, const G4String &directoryName, const G4String &hnType)
G4bool WriteDirectory ()
G4bool WriteH1 ()
G4bool WriteH2 ()
G4bool WriteH3 ()
G4bool WriteP1 ()
G4bool WriteP2 ()
G4bool Reset ()
Private Attributes
G4Hdf5NtupleManager * fNtupleManager
std::shared_ptr
< G4Hdf5FileManager > fFileManager
Static Private Attributes
static constexpr unsigned int fgkDefaultBasketSize = 32000
static G4Hdf5AnalysisManager * fgMasterInstance = nullptr
static G4ThreadLocal
G4Hdf5AnalysisManager * fgInstance = nullptr
Additional Inherited Members
Protected Attributes inherited from G4ToolsAnalysisManager
G4H1ToolsManager * fH1Manager
G4H2ToolsManager * fH2Manager
G4H3ToolsManager * fH3Manager
G4P1ToolsManager * fP1Manager
G4P2ToolsManager * fP2Manager
Static Protected Attributes inherited from G4ToolsAnalysisManager
static G4ThreadLocal
G4ToolsAnalysisManager * fgToolsInstance = nullptr
Detailed Description
Definition at line 45 of file G4Hdf5AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 45 of file G4Hdf5AnalysisManager.hh
Constructor & Destructor Documentation
G4Hdf5AnalysisManager::G4Hdf5AnalysisManager (G4bool isMaster = true) explicit
Definition at line 76 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 76 of file G4Hdf5AnalysisManager.cc
References FatalException, fFileManager, fgInstance, fgkDefaultBasketSize, fgMasterInstance, fNtupleManager, G4VAnalysisManager::fState, G4Exception(), message(), G4Hdf5NtupleManager::SetFileManager(), G4VAnalysisManager::SetFileManager(), and G4VAnalysisManager::SetNtupleManager().
Referenced by Instance().
G4Hdf5AnalysisManager::~G4Hdf5AnalysisManager ()
Definition at line 116 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 116 of file G4Hdf5AnalysisManager.cc
References fgInstance, fgMasterInstance, G4VAnalysisManager::fState, and G4AnalysisManagerState::GetIsMaster().
Member Function Documentation
std::vector<tools::hdf5::ntuple*>::const_iterator G4Hdf5AnalysisManager::BeginConstNtuple () const
std::vector<tools::hdf5::ntuple*>::iterator G4Hdf5AnalysisManager::BeginNtuple ()
G4bool G4Hdf5AnalysisManager::CloseFileImpl (G4bool reset) final protected virtual
Implements G4VAnalysisManager.
Definition at line 354 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 354 of file G4Hdf5AnalysisManager.cc
References fFileManager, fNtupleManager, G4Exception(), JustWarning, G4TNtupleManager< TNTUPLE >::Reset(), Reset(), and G4TemplateAutoLock< _Mutex_t >::unlock().
std::vector<tools::hdf5::ntuple*>::const_iterator G4Hdf5AnalysisManager::EndConstNtuple () const
std::vector<tools::hdf5::ntuple*>::iterator G4Hdf5AnalysisManager::EndNtuple ()
tools::hdf5::ntuple* G4Hdf5AnalysisManager::GetNtuple () const
tools::hdf5::ntuple* G4Hdf5AnalysisManager::GetNtuple (G4int ntupleId) const
G4Hdf5AnalysisManager * G4Hdf5AnalysisManager::Instance (void) static
Definition at line 59 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 59 of file G4Hdf5AnalysisManager.cc
References fgInstance, G4Hdf5AnalysisManager(), and G4Threading::IsWorkerThread().
Referenced by G4Analysis::ManagerInstance().
G4bool G4Hdf5AnalysisManager::IsInstance () static
Definition at line 70 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 70 of file G4Hdf5AnalysisManager.cc
References fgInstance.
virtual G4bool G4Hdf5AnalysisManager::IsOpenFileImpl () const final protected virtual
Implements G4VAnalysisManager.
G4bool G4Hdf5AnalysisManager::OpenFileImpl (const G4String & fileName) final protected virtual
Implements G4VAnalysisManager.
Definition at line 272 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 272 of file G4Hdf5AnalysisManager.cc
References G4TNtupleManager< TNTUPLE >::CreateNtuplesFromBooking(), fFileManager, fNtupleManager, G4VAnalysisManager::fState, G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), G4AnalysisVerbose::Message(), and G4TemplateAutoLock< _Mutex_t >::unlock().
G4bool G4Hdf5AnalysisManager::Reset () private
Definition at line 252 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 252 of file G4Hdf5AnalysisManager.cc
References fNtupleManager, G4TNtupleManager< TNTUPLE >::Reset(), and G4ToolsAnalysisManager::Reset().
Referenced by CloseFileImpl().
G4bool G4Hdf5AnalysisManager::WriteDirectory () private
G4bool G4Hdf5AnalysisManager::WriteH1 () private
Definition at line 127 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 127 of file G4Hdf5AnalysisManager.cc
References G4H1ToolsManager::AddH1Vector(), fFileManager, fgMasterInstance, G4ToolsAnalysisManager::fH1Manager, G4H1ToolsManager::GetH1Vector(), G4H1ToolsManager::GetHnVector(), G4Threading::IsWorkerThread(), G4TemplateAutoLock< _Mutex_t >::unlock(), and WriteHn().
Referenced by WriteImpl().
G4bool G4Hdf5AnalysisManager::WriteH2 () private
Definition at line 152 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 152 of file G4Hdf5AnalysisManager.cc
References G4H2ToolsManager::AddH2Vector(), fFileManager, fgMasterInstance, G4ToolsAnalysisManager::fH2Manager, G4H2ToolsManager::GetH2Vector(), G4H2ToolsManager::GetHnVector(), G4Threading::IsWorkerThread(), G4TemplateAutoLock< _Mutex_t >::unlock(), and WriteHn().
Referenced by WriteImpl().
G4bool G4Hdf5AnalysisManager::WriteH3 () private
Definition at line 177 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 177 of file G4Hdf5AnalysisManager.cc
References G4H3ToolsManager::AddH3Vector(), fFileManager, fgMasterInstance, G4ToolsAnalysisManager::fH3Manager, G4H3ToolsManager::GetH3Vector(), G4H3ToolsManager::GetHnVector(), G4Threading::IsWorkerThread(), G4TemplateAutoLock< _Mutex_t >::unlock(), and WriteHn().
Referenced by WriteImpl().
template<typename T > G4bool G4Hdf5AnalysisManager::WriteHn (const std::vector< T * > & htVector, const std::vector< G4HnInformation * > & hnVector, const G4String & directoryName, const G4String & hnType) private
Referenced by WriteH1(), WriteH2(), and WriteH3().
G4bool G4Hdf5AnalysisManager::WriteImpl () final protected virtual
Implements G4VAnalysisManager.
Definition at line 301 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 301 of file G4Hdf5AnalysisManager.cc
References fFileManager, G4VAnalysisManager::fState, G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), G4VAnalysisManager::IsAscii(), G4AnalysisVerbose::Message(), G4VAnalysisManager::WriteAscii(), WriteH1(), WriteH2(), WriteH3(), WriteP1(), and WriteP2().
G4bool G4Hdf5AnalysisManager::WriteP1 () private
Definition at line 202 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 202 of file G4Hdf5AnalysisManager.cc
References G4P1ToolsManager::AddP1Vector(), fFileManager, fgMasterInstance, G4ToolsAnalysisManager::fP1Manager, G4P1ToolsManager::GetHnVector(), G4P1ToolsManager::GetP1Vector(), G4Threading::IsWorkerThread(), G4TemplateAutoLock< _Mutex_t >::unlock(), and WritePn().
Referenced by WriteImpl().
G4bool G4Hdf5AnalysisManager::WriteP2 () private
Definition at line 227 of file G4Hdf5AnalysisManager.cc.
View newest version in sPHENIX GitHub at line 227 of file G4Hdf5AnalysisManager.cc
References G4P2ToolsManager::AddP2Vector(), fFileManager, fgMasterInstance, G4ToolsAnalysisManager::fP2Manager, G4P2ToolsManager::GetHnVector(), G4P2ToolsManager::GetP2Vector(), G4Threading::IsWorkerThread(), G4TemplateAutoLock< _Mutex_t >::unlock(), and WritePn().
Referenced by WriteImpl().
template<typename T > G4bool G4Hdf5AnalysisManager::WritePn (const std::vector< T * > & htVector, const std::vector< G4HnInformation * > & hnVector, const G4String & directoryName, const G4String & hnType) private
Referenced by WriteP1(), and WriteP2().
Member Data Documentation
std::shared_ptr<G4Hdf5FileManager> G4Hdf5AnalysisManager::fFileManager private
Definition at line 101 of file G4Hdf5AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 101 of file G4Hdf5AnalysisManager.hh
Referenced by CloseFileImpl(), G4Hdf5AnalysisManager(), OpenFileImpl(), WriteH1(), WriteH2(), WriteH3(), WriteImpl(), WriteP1(), and WriteP2().
G4ThreadLocal G4Hdf5AnalysisManager * G4Hdf5AnalysisManager::fgInstance = nullptr static private
Definition at line 78 of file G4Hdf5AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 78 of file G4Hdf5AnalysisManager.hh
Referenced by G4Hdf5AnalysisManager(), Instance(), IsInstance(), and ~G4Hdf5AnalysisManager().
constexpr unsigned int G4Hdf5AnalysisManager::fgkDefaultBasketSize = 32000 static private
Definition at line 74 of file G4Hdf5AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 74 of file G4Hdf5AnalysisManager.hh
Referenced by G4Hdf5AnalysisManager().
G4Hdf5AnalysisManager * G4Hdf5AnalysisManager::fgMasterInstance = nullptr static private
Definition at line 77 of file G4Hdf5AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 77 of file G4Hdf5AnalysisManager.hh
Referenced by G4Hdf5AnalysisManager(), WriteH1(), WriteH2(), WriteH3(), WriteP1(), WriteP2(), and ~G4Hdf5AnalysisManager().
G4Hdf5NtupleManager* G4Hdf5AnalysisManager::fNtupleManager private
Definition at line 100 of file G4Hdf5AnalysisManager.hh.
View newest version in sPHENIX GitHub at line 100 of file G4Hdf5AnalysisManager.hh
Referenced by CloseFileImpl(), G4Hdf5AnalysisManager(), OpenFileImpl(), and Reset().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/hdf5/include/G4Hdf5AnalysisManager.hh
geant4/tree/geant4-10.6-release/source/analysis/hdf5/src/G4Hdf5AnalysisManager.cc