ECCE @ EIC Software: G4ProcTblElement Class Reference
G4ProcTblElement Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcTblElement.hh>
Public Member Functions
G4ProcTblElement (const G4ProcTblElement &right)
G4ProcTblElement (G4VProcess *aProcess)
~G4ProcTblElement ()
G4ProcTblElement & operator= (const G4ProcTblElement &right)
G4bool operator== (const G4ProcTblElement &right) const
G4bool operator!= (const G4ProcTblElement &right) const
Protected Types
typedef std::vector
< G4ProcessManager * > G4ProcMgrVector
Protected Member Functions
G4ProcTblElement ()
G4int Length () const
void Insert (G4ProcessManager *aProcMgr)
void Remove (G4ProcessManager *aProcMgr)
G4VProcess * GetProcess () const
const G4String & GetProcessName () const
G4ProcessManager * GetProcessManager (G4int index) const
const G4ProcMgrVector * GetProcMgrVector () const
G4int GetIndex (const G4ProcessManager *pManager) const
G4bool Contains (const G4ProcessManager *pManager) const
Private Attributes
G4VProcess * pProcess
G4ProcMgrVector * pProcMgrVector
Friends
class G4ProcessTable
Detailed Description
Definition at line 52 of file G4ProcTblElement.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ProcTblElement.hh
Member Typedef Documentation
typedef std::vector<G4ProcessManager*> G4ProcTblElement::G4ProcMgrVector protected
Definition at line 76 of file G4ProcTblElement.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ProcTblElement.hh
Constructor & Destructor Documentation
G4ProcTblElement::G4ProcTblElement () protected
Definition at line 41 of file G4ProcTblElement.cc.
View newest version in sPHENIX GitHub at line 41 of file G4ProcTblElement.cc
G4ProcTblElement::G4ProcTblElement (const G4ProcTblElement & right)
Definition at line 54 of file G4ProcTblElement.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ProcTblElement.cc
References right.
G4ProcTblElement::G4ProcTblElement (G4VProcess * aProcess)
Definition at line 47 of file G4ProcTblElement.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ProcTblElement.cc
References pProcMgrVector.
G4ProcTblElement::~G4ProcTblElement ()
Definition at line 62 of file G4ProcTblElement.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ProcTblElement.cc
References pProcMgrVector.
Member Function Documentation
G4bool G4ProcTblElement::Contains (const G4ProcessManager * pManager) const protected
Referenced by G4ProcessTable::FindProcess(), G4ProcessTable::Insert(), and G4ProcessTable::Remove().
G4int G4ProcTblElement::GetIndex (const G4ProcessManager * pManager) const protected
G4VProcess* G4ProcTblElement::GetProcess () const protected
Referenced by G4ProcessTable::DumpInfo(), G4ProcessTable::ExtractProcesses(), G4ProcessTable::Find(), G4ProcessTable::FindProcess(), G4ProcessTable::Insert(), G4ProcessTable::Remove(), and G4ProcessTable::SetProcessActivation().
G4ProcessManager* G4ProcTblElement::GetProcessManager (G4int index) const protected
Referenced by G4ProcessTable::DumpInfo(), and G4ProcessTable::SetProcessActivation().
const G4String& G4ProcTblElement::GetProcessName () const protected
Referenced by G4ProcessTable::Find(), G4ProcessTable::FindProcess(), and G4ProcessTable::Remove().
const G4ProcMgrVector* G4ProcTblElement::GetProcMgrVector () const inline protected
Definition at line 88 of file G4ProcTblElement.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ProcTblElement.hh
References pProcMgrVector.
void G4ProcTblElement::Insert (G4ProcessManager * aProcMgr) protected
Referenced by G4ProcessTable::Insert().
G4int G4ProcTblElement::Length () const protected
Referenced by G4ProcessTable::DumpInfo(), G4ProcessTable::Remove(), and G4ProcessTable::SetProcessActivation().
G4bool G4ProcTblElement::operator!= (const G4ProcTblElement & right) const
Definition at line 99 of file G4ProcTblElement.cc.
View newest version in sPHENIX GitHub at line 99 of file G4ProcTblElement.cc
G4ProcTblElement & G4ProcTblElement::operator= (const G4ProcTblElement & right)
Definition at line 72 of file G4ProcTblElement.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ProcTblElement.cc
References pProcess, and pProcMgrVector.
G4bool G4ProcTblElement::operator== (const G4ProcTblElement & right) const
Definition at line 92 of file G4ProcTblElement.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ProcTblElement.cc
void G4ProcTblElement::Remove (G4ProcessManager * aProcMgr) protected
Referenced by G4ProcessTable::Remove().
Friends And Related Function Documentation
friend class G4ProcessTable friend
Definition at line 55 of file G4ProcTblElement.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ProcTblElement.hh
Member Data Documentation
G4VProcess* G4ProcTblElement::pProcess private
Definition at line 95 of file G4ProcTblElement.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ProcTblElement.hh
Referenced by operator=().
G4ProcMgrVector* G4ProcTblElement::pProcMgrVector private
Definition at line 98 of file G4ProcTblElement.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ProcTblElement.hh
Referenced by G4ProcTblElement(), GetProcMgrVector(), operator=(), and ~G4ProcTblElement().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4ProcTblElement.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4ProcTblElement.cc