ECCE @ EIC Software: G4GeometryWorkspace Class Reference
G4GeometryWorkspace Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4GeometryWorkspace.hh>
Public Types
using pool_type = G4TWorkspacePool< G4GeometryWorkspace >
Public Member Functions
G4GeometryWorkspace ()
~G4GeometryWorkspace ()
void UseWorkspace ()
void ReleaseWorkspace ()
void DestroyWorkspace ()
void InitialiseWorkspace ()
void SetVerbose (G4bool v)
G4bool GetVerbose ()
Static Public Member Functions
static pool_type * GetPool ()
Protected Member Functions
void InitialisePhysicalVolumes ()
G4bool CloneParameterisedSolids (G4PVParameterised *paramVol)
G4bool CloneReplicaSolid (G4PVReplica *)
Private Attributes
G4LVManager * fpLogicalVolumeSIM
G4PVManager * fpPhysicalVolumeSIM
G4PVRManager * fpReplicaSIM
G4RegionManager * fpRegionSIM
G4LVData * fLogicalVolumeOffset
G4PVData * fPhysicalVolumeOffset
G4ReplicaData * fReplicaOffset
G4RegionData * fRegionOffset
G4bool fVerbose = false
Detailed Description
Definition at line 58 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 58 of file G4GeometryWorkspace.hh
Member Typedef Documentation
using G4GeometryWorkspace::pool_type = G4TWorkspacePool<G4GeometryWorkspace>
Definition at line 62 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 62 of file G4GeometryWorkspace.hh
Constructor & Destructor Documentation
G4GeometryWorkspace::G4GeometryWorkspace ()
Definition at line 60 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 60 of file G4GeometryWorkspace.cc
References fLogicalVolumeOffset, fPhysicalVolumeOffset, fpLogicalVolumeSIM, fpPhysicalVolumeSIM, fpRegionSIM, fpReplicaSIM, fRegionOffset, fReplicaOffset, G4GeomSplitter< T >::GetOffset(), G4PVReplica::GetSubInstanceManager(), G4VPhysicalVolume::GetSubInstanceManager(), G4Region::GetSubInstanceManager(), G4LogicalVolume::GetSubInstanceManager(), and InitialiseWorkspace().
G4GeometryWorkspace::~G4GeometryWorkspace ()
Definition at line 86 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 86 of file G4GeometryWorkspace.cc
Member Function Documentation
G4bool G4GeometryWorkspace::CloneParameterisedSolids (G4PVParameterised * paramVol) protected
Definition at line 232 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 232 of file G4GeometryWorkspace.cc
References G4VSolid::Clone(), FatalException, G4Exception(), G4VSolid::GetEntityType(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetSolid(), G4LogicalVolume::InitialiseWorker(), and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by InitialisePhysicalVolumes().
G4bool G4GeometryWorkspace::CloneReplicaSolid (G4PVReplica * replicaPV) protected
Definition at line 189 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 189 of file G4GeometryWorkspace.cc
References G4VSolid::Clone(), FatalException, G4Exception(), G4VSolid::GetEntityType(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetSolid(), G4LogicalVolume::InitialiseWorker(), and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by InitialisePhysicalVolumes().
void G4GeometryWorkspace::DestroyWorkspace ()
Definition at line 323 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 323 of file G4GeometryWorkspace.cc
References fpLogicalVolumeSIM, fpPhysicalVolumeSIM, fpRegionSIM, fpReplicaSIM, G4GeomSplitter< T >::FreeSlave(), G4PhysicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4PVReplica::TerminateWorker(), and G4LogicalVolume::TerminateWorker().
Referenced by G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
G4GeometryWorkspace::pool_type * G4GeometryWorkspace::GetPool () static
Definition at line 53 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 53 of file G4GeometryWorkspace.cc
Referenced by G4WorkerThread::BuildGeometryAndPhysicsVector(), G4WorkerThread::DestroyGeometryAndPhysicsVector(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
G4bool G4GeometryWorkspace::GetVerbose () inline
Definition at line 75 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 75 of file G4GeometryWorkspace.hh
References fVerbose.
void G4GeometryWorkspace::InitialisePhysicalVolumes () protected
Definition at line 136 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 136 of file G4GeometryWorkspace.cc
References CloneParameterisedSolids(), CloneReplicaSolid(), FatalException, fVerbose, G4cout, G4endl, G4Exception(), G4PhysicalVolumeStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMasterSolid(), G4PVReplica::InitialiseWorker(), G4LogicalVolume::InitialiseWorker(), and G4PVReplica::IsParameterised().
Referenced by InitialiseWorkspace().
void G4GeometryWorkspace::InitialiseWorkspace ()
Definition at line 292 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 292 of file G4GeometryWorkspace.cc
References fpLogicalVolumeSIM, fpPhysicalVolumeSIM, fpRegionSIM, fpReplicaSIM, fVerbose, G4cout, G4endl, InitialisePhysicalVolumes(), G4GeomSplitter< T >::SlaveCopySubInstanceArray(), and G4GeomSplitter< T >::SlaveInitializeSubInstance().
Referenced by G4GeometryWorkspace(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
void G4GeometryWorkspace::ReleaseWorkspace ()
Definition at line 125 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 125 of file G4GeometryWorkspace.cc
References fpLogicalVolumeSIM, fpPhysicalVolumeSIM, fpRegionSIM, fpReplicaSIM, and G4GeomSplitter< T >::UseWorkArea().
void G4GeometryWorkspace::SetVerbose (G4bool v) inline
Definition at line 74 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 74 of file G4GeometryWorkspace.hh
References fVerbose, and v.
void G4GeometryWorkspace::UseWorkspace ()
Definition at line 93 of file G4GeometryWorkspace.cc.
View newest version in sPHENIX GitHub at line 93 of file G4GeometryWorkspace.cc
References fLogicalVolumeOffset, fPhysicalVolumeOffset, fpLogicalVolumeSIM, fpPhysicalVolumeSIM, fpRegionSIM, fpReplicaSIM, fRegionOffset, fReplicaOffset, fVerbose, G4cout, G4endl, and G4GeomSplitter< T >::UseWorkArea().
Member Data Documentation
G4LVData* G4GeometryWorkspace::fLogicalVolumeOffset private
Definition at line 96 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 96 of file G4GeometryWorkspace.hh
Referenced by G4GeometryWorkspace(), and UseWorkspace().
G4PVData* G4GeometryWorkspace::fPhysicalVolumeOffset private
Definition at line 97 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 97 of file G4GeometryWorkspace.hh
Referenced by G4GeometryWorkspace(), and UseWorkspace().
G4LVManager* G4GeometryWorkspace::fpLogicalVolumeSIM private
Definition at line 87 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 87 of file G4GeometryWorkspace.hh
Referenced by DestroyWorkspace(), G4GeometryWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4PVManager* G4GeometryWorkspace::fpPhysicalVolumeSIM private
Definition at line 88 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 88 of file G4GeometryWorkspace.hh
Referenced by DestroyWorkspace(), G4GeometryWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4RegionManager* G4GeometryWorkspace::fpRegionSIM private
Definition at line 90 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 90 of file G4GeometryWorkspace.hh
Referenced by DestroyWorkspace(), G4GeometryWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4PVRManager* G4GeometryWorkspace::fpReplicaSIM private
Definition at line 89 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 89 of file G4GeometryWorkspace.hh
Referenced by DestroyWorkspace(), G4GeometryWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4RegionData* G4GeometryWorkspace::fRegionOffset private
Definition at line 99 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 99 of file G4GeometryWorkspace.hh
Referenced by G4GeometryWorkspace(), and UseWorkspace().
G4ReplicaData* G4GeometryWorkspace::fReplicaOffset private
Definition at line 98 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 98 of file G4GeometryWorkspace.hh
Referenced by G4GeometryWorkspace(), and UseWorkspace().
G4bool G4GeometryWorkspace::fVerbose = false private
Definition at line 101 of file G4GeometryWorkspace.hh.
View newest version in sPHENIX GitHub at line 101 of file G4GeometryWorkspace.hh
Referenced by GetVerbose(), InitialisePhysicalVolumes(), InitialiseWorkspace(), SetVerbose(), and UseWorkspace().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4GeometryWorkspace.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4GeometryWorkspace.cc