ECCE @ EIC Software: PriorityList Class Reference
PriorityList Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTrackHolder.hh>
Public Types
enum Type { MainList = 0, SecondariesList = 1, WaitingList = 2, Undefined = -1 }
Public Types inherited from G4FastList< OBJECT >::Watcher
enum Priority {
eExtreme, eHigh, eNormal, eLow,
eVeryLow
}
typedef G4FastList< OBJECT > list
Public Member Functions
PriorityList ()
PriorityList (G4TrackManyList &allMainList)
PriorityList (const PriorityList &right)
virtual ~PriorityList ()
virtual void NotifyDeletingList (G4TrackList *__list)
void NewMainList (G4TrackList *__list, G4TrackManyList &allMainList)
G4TrackList * NewMainList (G4TrackManyList &allMainList)
void PushToMainList (G4Track *__track, G4TrackManyList &allMainList)
void TransferToMainList (G4TrackList *&__list, G4TrackManyList &allMainList)
void PushToListOfSecondaries (G4Track *__track, G4TrackManyList &listOfAllSecondaries)
void PushToWaitingList (G4Track *__track)
void TransferSecondariesToMainList ()
void PushToMainList (G4Track *track)
void MergeWithMainList (G4TrackList *trackList)
G4TrackList * GetMainList ()
G4TrackList * GetSecondariesList ()
void SetWaitingList (G4TrackList *__list)
G4TrackList * Get (Type type)
int GetNTracks ()
Public Member Functions inherited from G4FastList< OBJECT >::Watcher
Watcher ()
virtual ~Watcher ()
virtual G4String GetWatcherName ()
Priority GetPriority () const
void NotifyDeletingList (G4FastList< OBJECT > *)
virtual void NotifyAddObject (OBJECT *, G4FastList< OBJECT > *)
virtual void NotifyRemoveObject (OBJECT *, G4FastList< OBJECT > *)
void Watch (G4FastList< OBJECT > *fastList)
void StopWatching (G4FastList< OBJECT > *fastList, bool removeWatcher=true)
Private Attributes
G4TrackList * fpMainList
G4TrackList fSecondaries
G4TrackList * fpWaitingList
Additional Inherited Members
Protected Attributes inherited from G4FastList< OBJECT >::Watcher
Priority fPriority
Detailed Description
Definition at line 40 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ITTrackHolder.hh
Member Enumeration Documentation
enum PriorityList::Type
Enumerator:
MainList
SecondariesList
WaitingList
Undefined
Definition at line 43 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ITTrackHolder.hh
Constructor & Destructor Documentation
PriorityList::PriorityList ()
Definition at line 44 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ITTrackHolder.cc
PriorityList::PriorityList (G4TrackManyList & allMainList)
Definition at line 49 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ITTrackHolder.cc
References NewMainList().
PriorityList::PriorityList (const PriorityList & right)
Definition at line 55 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ITTrackHolder.cc
PriorityList::~PriorityList () virtual
Definition at line 62 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ITTrackHolder.cc
References fpMainList, and fpWaitingList.
Member Function Documentation
G4TrackList* PriorityList::Get (Type type) inline
Definition at line 92 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ITTrackHolder.hh
References fpMainList, fpWaitingList, fSecondaries, MainList, SecondariesList, Undefined, and WaitingList.
G4TrackList* PriorityList::GetMainList () inline
Definition at line 77 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ITTrackHolder.hh
References fpMainList.
Referenced by G4ITTrackHolder::GetMainList(), and G4ITTrackHolder::MergeNextTimeToMainList().
int PriorityList::GetNTracks ()
Definition at line 167 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 167 of file G4ITTrackHolder.cc
References fpMainList, fpWaitingList, fSecondaries, and G4FastList< OBJECT >::size().
G4TrackList* PriorityList::GetSecondariesList () inline
Definition at line 82 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ITTrackHolder.hh
References fSecondaries.
void PriorityList::MergeWithMainList (G4TrackList * trackList)
Definition at line 161 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 161 of file G4ITTrackHolder.cc
References fpMainList, and G4FastList< OBJECT >::transferTo().
void PriorityList::NewMainList (G4TrackList * __list, G4TrackManyList & allMainList)
Definition at line 90 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 90 of file G4ITTrackHolder.cc
References G4ManyFastLists< OBJECT >::Add(), fpMainList, and G4FastList< OBJECT >::Watcher::Watch().
Referenced by NewMainList(), PriorityList(), PushToMainList(), and TransferToMainList().
G4TrackList * PriorityList::NewMainList (G4TrackManyList & allMainList)
Definition at line 98 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ITTrackHolder.cc
References fpMainList, and NewMainList().
void PriorityList::NotifyDeletingList (G4TrackList * __list) virtual
Definition at line 76 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ITTrackHolder.cc
References fpMainList, and fpWaitingList.
void PriorityList::PushToListOfSecondaries (G4Track * __track, G4TrackManyList & listOfAllSecondaries)
Definition at line 130 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 130 of file G4ITTrackHolder.cc
References G4ManyFastLists< OBJECT >::Add(), fSecondaries, G4FastList< OBJECT >::GetListNode(), and G4FastList< OBJECT >::push_back().
Referenced by G4ITTrackHolder::PushTo().
void PriorityList::PushToMainList (G4Track * __track, G4TrackManyList & allMainList)
Definition at line 105 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 105 of file G4ITTrackHolder.cc
References fpMainList, NewMainList(), and G4FastList< OBJECT >::push_back().
Referenced by G4ITTrackHolder::PushTo().
void PriorityList::PushToMainList (G4Track * track)
Definition at line 155 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 155 of file G4ITTrackHolder.cc
References fpMainList, and G4FastList< OBJECT >::push_back().
void PriorityList::PushToWaitingList (G4Track * __track)
Definition at line 141 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 141 of file G4ITTrackHolder.cc
References fpWaitingList, and G4FastList< OBJECT >::push_back().
Referenced by G4ITTrackHolder::PushTo().
void PriorityList::SetWaitingList (G4TrackList * __list) inline
Definition at line 87 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ITTrackHolder.hh
References fpWaitingList.
void PriorityList::TransferSecondariesToMainList ()
Definition at line 150 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 150 of file G4ITTrackHolder.cc
References fpMainList, fSecondaries, and G4FastList< OBJECT >::transferTo().
void PriorityList::TransferToMainList (G4TrackList *& __list, G4TrackManyList & allMainList)
Definition at line 115 of file G4ITTrackHolder.cc.
View newest version in sPHENIX GitHub at line 115 of file G4ITTrackHolder.cc
References fpMainList, NewMainList(), and G4FastList< OBJECT >::transferTo().
Referenced by G4ITTrackHolder::MergeNextTimeToMainList().
Member Data Documentation
G4TrackList* PriorityList::fpMainList private
Definition at line 114 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ITTrackHolder.hh
Referenced by Get(), GetMainList(), GetNTracks(), MergeWithMainList(), NewMainList(), NotifyDeletingList(), PushToMainList(), TransferSecondariesToMainList(), TransferToMainList(), and ~PriorityList().
G4TrackList* PriorityList::fpWaitingList private
Definition at line 117 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ITTrackHolder.hh
Referenced by Get(), GetNTracks(), NotifyDeletingList(), PushToWaitingList(), SetWaitingList(), and ~PriorityList().
G4TrackList PriorityList::fSecondaries private
Definition at line 115 of file G4ITTrackHolder.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ITTrackHolder.hh
Referenced by Get(), GetNTracks(), GetSecondariesList(), PushToListOfSecondaries(), and TransferSecondariesToMainList().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTrackHolder.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITTrackHolder.cc