ECCE @ EIC Software: G4Scheduler Class Reference
G4Scheduler Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4Scheduler.hh>
Public Member Functions
virtual G4bool Notify (G4ApplicationState requestedState)
virtual void RegisterModel (G4VITStepModel *, double)
void Initialize ()
void ForceReinitialization ()
bool IsInitialized ()
bool IsRunning ()
void Reset ()
void Process ()
void ClearList ()
void SetGun (G4ITGun *)
G4ITGun * GetGun ()
void Stop ()
void Clear ()
void EndTracking ()
void SetEndTime (const double)
void SetTimeTolerance (double)
double GetTimeTolerance () const
void SetMaxZeroTimeAllowed (int)
int GetMaxZeroTimeAllowed () const
G4ITModelHandler * GetModelHandler ()
void SetTimeSteps (std::map< double, double > *)
void AddTimeStep (double, double)
void SetDefaultTimeStep (double)
double GetLimitingTimeStep () const
G4int GetNbSteps () const
void SetMaxNbSteps (G4int)
G4int GetMaxNbSteps () const
G4double GetStartTime () const
G4double GetEndTime () const
virtual G4double GetTimeStep () const
G4double GetPreviousTimeStep () const
G4double GetGlobalTime () const
void SetUserAction (G4UserTimeStepAction *)
G4UserTimeStepAction * GetUserTimeStepAction () const
void UseDefaultTimeSteps (G4bool)
G4bool AreDefaultTimeStepsUsed ()
G4ITStepStatus GetStatus () const
void SetVerbose (int)
int GetVerbose () const
void WhyDoYouStop ()
void SetInteractivity (G4ITTrackingInteractivity *)
G4ITTrackingInteractivity * GetInteractivity ()
virtual size_t GetNTracks ()
void GetCollisionType (G4String &interactionType)
void AddWatchedTime (double time)
double GetNextWatchedTime () const
void SetMaxTimeStep (double maxTimeStep)
double GetMaxTimeStep () const
Public Member Functions inherited from G4VStateDependent
G4VStateDependent (G4bool bottom=false)
virtual ~G4VStateDependent ()
G4bool operator== (const G4VStateDependent &right) const
G4bool operator!= (const G4VStateDependent &right) const
Static Public Member Functions
static G4Scheduler * Instance ()
static void DeleteInstance ()
Static Public Member Functions inherited from G4VScheduler
static G4VScheduler * Instance ()
Protected Member Functions
virtual ~G4Scheduler ()
void DoProcess ()
void SynchronizeTracks ()
void Stepping ()
void FindUserPreDefinedTimeStep ()
bool CanICarryOn ()
void PrintWhyDoYouStop ()
Protected Member Functions inherited from G4VScheduler
G4VScheduler ()
virtual ~G4VScheduler ()
Private Member Functions
G4Scheduler ()
void Create ()
G4Scheduler (const G4Scheduler &)
G4Scheduler & operator= (const G4Scheduler &)
Private Attributes
G4SchedulerMessenger * fpMessenger
int fVerbose
bool fWhyDoYouStop
bool fInitialized
bool fRunning
G4bool fContinue
int fNbSteps
int fMaxSteps
G4ITStepStatus fITStepStatus
G4bool fUseDefaultTimeSteps
double fTimeTolerance
double fGlobalTime
double fTmpGlobalTime
double fStartTime
double fStopTime
double fEndTime
double fPreviousTimeStep
int fZeroTimeCount
int fMaxNZeroTimeStepsAllowed
double fTimeStep
double fMaxTimeStep
bool fUsePreDefinedTimeSteps
double fDefaultMinTimeStep
std::map< double, double > * fpUserTimeSteps
double fUserUpperTimeLimit
double fDefinedMinTimeStep
bool fReachedUserTimeLimit
std::set< double > fWatchedTimes
G4UserTimeStepAction * fpUserTimeStepAction
G4ITStepProcessor * fpStepProcessor
G4ITModelProcessor * fpModelProcessor
G4ITTrackingManager * fpTrackingManager
G4ITTrackingInteractivity * fpTrackingInteractivity
G4ITReactionSet * fReactionSet
G4ITTrackHolder & fTrackContainer
G4ITModelHandler * fpModelHandler
double fTSTimeStep
double fILTimeStep
bool fInteractionStep
G4ITGun * fpGun
Static Private Attributes
static G4ThreadLocal G4Scheduler * fgScheduler
Detailed Description
G4Scheduler synchronizes (in time) track stepping
Definition at line 87 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 87 of file G4Scheduler.hh
Constructor & Destructor Documentation
G4Scheduler::~G4Scheduler () protected virtual
Definition at line 200 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 200 of file G4Scheduler.cc
References Clear(), fgScheduler, and fpMessenger.
G4Scheduler::G4Scheduler () private
Definition at line 132 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 132 of file G4Scheduler.cc
References Create().
G4Scheduler::G4Scheduler (const G4Scheduler &) private
Definition at line 1122 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 1122 of file G4Scheduler.cc
References Create().
Member Function Documentation
void G4Scheduler::AddTimeStep (double startingTime, double timeStep) inline virtual
Reimplemented from G4VScheduler.
Definition at line 304 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 304 of file G4Scheduler.hh
References fpUserTimeSteps, and fUsePreDefinedTimeSteps.
void G4Scheduler::AddWatchedTime (double time) inline
Definition at line 176 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 176 of file G4Scheduler.hh
References fWatchedTimes.
G4bool G4Scheduler::AreDefaultTimeStepsUsed () inline
Definition at line 437 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 437 of file G4Scheduler.hh
References fUseDefaultTimeSteps, and fUsePreDefinedTimeSteps.
Referenced by G4SchedulerMessenger::GetCurrentValue().
bool G4Scheduler::CanICarryOn () protected
Definition at line 550 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 550 of file G4Scheduler.cc
References fContinue, fEndTime, fGlobalTime, fMaxSteps, and fNbSteps.
Referenced by SynchronizeTracks().
void G4Scheduler::Clear ()
Definition at line 216 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 216 of file G4Scheduler.cc
References ClearList(), fpMessenger, fpModelHandler, fpModelProcessor, fpStepProcessor, fpTrackingManager, fReactionSet, G4ITTypeManager::Instance(), and G4ITTypeManager::ReleaseRessource().
Referenced by ~G4Scheduler().
void G4Scheduler::ClearList ()
Definition at line 264 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 264 of file G4Scheduler.cc
References G4ITTrackHolder::Clear(), G4AllITFinder::DeleteInstance(), and fTrackContainer.
Referenced by Clear(), and Process().
void G4Scheduler::Create () private
Definition at line 139 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 139 of file G4Scheduler.cc
References DBL_MAX, eUndefined, fContinue, fDefaultMinTimeStep, fDefinedMinTimeStep, fEndTime, fGlobalTime, fILTimeStep, fInitialized, fInteractionStep, fITStepStatus, fMaxNZeroTimeStepsAllowed, fMaxSteps, fMaxTimeStep, fNbSteps, fpGun, fpMessenger, fpModelHandler, fpModelProcessor, fPreviousTimeStep, fpStepProcessor, fpTrackingInteractivity, fpTrackingManager, fpUserTimeStepAction, fpUserTimeSteps, fReachedUserTimeLimit, fReactionSet, fRunning, fStartTime, fStopTime, fTimeStep, fTimeTolerance, fTmpGlobalTime, fTSTimeStep, fUseDefaultTimeSteps, fUsePreDefinedTimeSteps, fUserUpperTimeLimit, fVerbose, fWhyDoYouStop, fZeroTimeCount, G4ITTypeManager::Instance(), G4ITReactionSet::Instance(), microsecond, picosecond, and G4ITTypeManager::ReserveRessource().
Referenced by G4Scheduler(), and operator=().
void G4Scheduler::DeleteInstance () static
DeleteInstance should be used instead of the destructor
Definition at line 123 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 123 of file G4Scheduler.cc
void G4Scheduler::DoProcess () protected
Definition at line 602 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 602 of file G4Scheduler.cc
References fContinue, fGlobalTime, fMaxSteps, fNbSteps, fpUserTimeStepAction, fStopTime, fTrackContainer, fVerbose, G4BestUnit, G4cout, G4endl, G4ITTrackHolder::MainListsNOTEmpty(), G4MemStat::MemoryUsage(), G4UserTimeStepAction::NewStage(), PrintWhyDoYouStop(), and Stepping().
Referenced by SynchronizeTracks().
void G4Scheduler::EndTracking ()
Definition at line 1061 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 1061 of file G4Scheduler.cc
References G4ManyFastLists< OBJECT >::begin(), G4ManyFastLists< OBJECT >::end(), G4ITTrackingManager::EndTrackingWOKill(), FatalErrorInArgument, fpTrackingManager, fRunning, fTrackContainer, G4endl, G4Exception(), G4ITTrackHolder::GetMainList(), G4ITTrackHolder::GetSecondariesList(), it, G4ITTrackHolder::MainListsNOTEmpty(), G4ITTrackHolder::MergeSecondariesWithMainList(), and G4ITTrackHolder::SecondaryListsNOTEmpty().
Referenced by Process().
void G4Scheduler::FindUserPreDefinedTimeStep () protected
Definition at line 1006 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 1006 of file G4Scheduler.cc
References FatalErrorInArgument, fDefinedMinTimeStep, fGlobalTime, fpUserTimeSteps, fTimeTolerance, and G4Exception().
void G4Scheduler::ForceReinitialization ()
Definition at line 1115 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 1115 of file G4Scheduler.cc
References fInitialized, and Initialize().
void G4Scheduler::GetCollisionType (G4String & interactionType)
Definition at line 1146 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 1146 of file G4Scheduler.cc
References eCollisionBetweenTracks, eInteractionWithMedium, and fITStepStatus.
Referenced by Stepping().
G4double G4Scheduler::GetEndTime () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 335 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 335 of file G4Scheduler.hh
References fEndTime.
Referenced by G4SchedulerMessenger::GetCurrentValue().
G4double G4Scheduler::GetGlobalTime () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 350 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 350 of file G4Scheduler.hh
References fGlobalTime.
Referenced by G4ITTrackHolder::_PushTrack().
G4ITGun * G4Scheduler::GetGun () inline
Definition at line 422 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 422 of file G4Scheduler.hh
References fpGun.
G4ITTrackingInteractivity * G4Scheduler::GetInteractivity () inline virtual
Reimplemented from G4VScheduler.
Definition at line 412 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 412 of file G4Scheduler.hh
References fpTrackingInteractivity.
double G4Scheduler::GetLimitingTimeStep () const virtual
Reimplemented from G4VScheduler.
Definition at line 940 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 940 of file G4Scheduler.cc
References fDefaultMinTimeStep, fDefinedMinTimeStep, fGlobalTime, fpUserTimeSteps, fStopTime, fTimeTolerance, and fUserUpperTimeLimit.
Referenced by Stepping().
G4int G4Scheduler::GetMaxNbSteps () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 325 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 325 of file G4Scheduler.hh
References fMaxSteps.
Referenced by G4SchedulerMessenger::GetCurrentValue().
double G4Scheduler::GetMaxTimeStep () const inline
Definition at line 188 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 188 of file G4Scheduler.hh
References fMaxTimeStep.
int G4Scheduler::GetMaxZeroTimeAllowed () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 382 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 382 of file G4Scheduler.hh
References fMaxNZeroTimeStepsAllowed.
Referenced by G4SchedulerMessenger::GetCurrentValue().
G4ITModelHandler * G4Scheduler::GetModelHandler () inline virtual
Reimplemented from G4VScheduler.
Definition at line 287 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 287 of file G4Scheduler.hh
References fpModelHandler.
G4int G4Scheduler::GetNbSteps () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 315 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 315 of file G4Scheduler.hh
References fNbSteps.
double G4Scheduler::GetNextWatchedTime () const
Definition at line 488 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 488 of file G4Scheduler.cc
References DBL_MAX, fGlobalTime, and fWatchedTimes.
Referenced by SynchronizeTracks().
size_t G4Scheduler::GetNTracks () virtual
Definition at line 1140 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 1140 of file G4Scheduler.cc
References fTrackContainer, and G4ITTrackHolder::GetNTracks().
G4double G4Scheduler::GetPreviousTimeStep () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 397 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 397 of file G4Scheduler.hh
References fPreviousTimeStep.
G4double G4Scheduler::GetStartTime () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 330 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 330 of file G4Scheduler.hh
References fStartTime.
G4ITStepStatus G4Scheduler::GetStatus () const inline
Definition at line 402 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 402 of file G4Scheduler.hh
References fITStepStatus.
G4double G4Scheduler::GetTimeStep () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 340 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 340 of file G4Scheduler.hh
References fTimeStep.
double G4Scheduler::GetTimeTolerance () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 392 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 392 of file G4Scheduler.hh
References fTimeTolerance.
Referenced by G4ITTrackHolder::_PushTrack(), and G4SchedulerMessenger::GetCurrentValue().
G4UserTimeStepAction * G4Scheduler::GetUserTimeStepAction () const inline virtual
Reimplemented from G4VScheduler.
Definition at line 361 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 361 of file G4Scheduler.hh
References fpUserTimeStepAction.
int G4Scheduler::GetVerbose () const inline
Definition at line 371 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 371 of file G4Scheduler.hh
References fVerbose.
Referenced by G4SchedulerMessenger::GetCurrentValue().
void G4Scheduler::Initialize () virtual
Reimplemented from G4VScheduler.
Definition at line 281 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 281 of file G4Scheduler.cc
References FatalErrorInArgument, fInitialized, fpModelHandler, fpModelProcessor, fpStepProcessor, fpTrackingInteractivity, fpTrackingManager, fpUserTimeSteps, fUsePreDefinedTimeSteps, G4Exception(), G4ITTrackingManager::SetInteractivity(), G4ITModelProcessor::SetModelHandler(), G4ITModelProcessor::SetTrackingManager(), and G4ITStepProcessor::SetTrackingManager().
Referenced by ForceReinitialization(), G4DNAChemistryManager::InitializeThread(), Process(), and G4SchedulerMessenger::SetNewValue().
G4Scheduler * G4Scheduler::Instance (void) static
Definition at line 101 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 101 of file G4Scheduler.cc
Referenced by G4ITTrackHolder::_PushTrack(), G4MoleculeCounter::AddAMoleculeAtTime(), G4DNAChemistryManager::InitializeMaster(), G4DNAChemistryManager::InitializeThread(), G4VScheduler::Instance(), G4MoleculeCounter::RemoveAMoleculeAtTime(), G4DNAChemistryManager::Run(), and G4DNAChemistryManager::SetGun().
bool G4Scheduler::IsInitialized () inline
Definition at line 282 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 282 of file G4Scheduler.hh
References fInitialized.
Referenced by G4SchedulerMessenger::GetCurrentValue().
bool G4Scheduler::IsRunning () inline virtual
Reimplemented from G4VScheduler.
Definition at line 107 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 107 of file G4Scheduler.hh
References fRunning.
Referenced by G4ITTrackHolder::_PushTrack().
G4bool G4Scheduler::Notify (G4ApplicationState requestedState) virtual
Implements G4VStateDependent.
Definition at line 108 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 108 of file G4Scheduler.cc
References JA::Clear(), G4cout, G4endl, and G4State_Quit.
G4Scheduler & G4Scheduler::operator= (const G4Scheduler & right) private
Definition at line 1131 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 1131 of file G4Scheduler.cc
References Create().
void G4Scheduler::PrintWhyDoYouStop () protected
Definition at line 558 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 558 of file G4Scheduler.cc
References fContinue, fGlobalTime, fMaxSteps, fNbSteps, fStopTime, fTrackContainer, fWhyDoYouStop, G4BestUnit, G4cout, G4endl, and G4ITTrackHolder::MainListsNOTEmpty().
Referenced by DoProcess().
void G4Scheduler::Process () virtual
Reimplemented from G4VScheduler.
Definition at line 376 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 376 of file G4Scheduler.cc
References ClearList(), G4ITGun::DefineTracks(), G4ITTrackHolder::DelayListsNOTEmpty(), G4UserTimeStepAction::EndProcessing(), EndTracking(), fGlobalTime, G4ITTrackingInteractivity::Finalize(), fInitialized, fpGun, fpModelProcessor, fpStepProcessor, fpTrackingInteractivity, fpUserTimeStepAction, fRunning, fStartTime, fTrackContainer, fVerbose, G4BestUnit, G4cout, G4endl, G4ITTrackHolder::GetNextTime(), G4ITTrackingInteractivity::Initialize(), G4ITModelProcessor::Initialize(), Initialize(), G4ITStepProcessor::Initialize(), Reset(), G4Timer::Start(), G4UserTimeStepAction::StartProcessing(), G4Timer::Stop(), and SynchronizeTracks().
Referenced by G4DNAChemistryManager::Run(), and G4SchedulerMessenger::SetNewValue().
void G4Scheduler::RegisterModel (G4VITStepModel * model, double time) virtual
Reimplemented from G4VScheduler.
Definition at line 274 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 274 of file G4Scheduler.cc
References fpModelHandler, and G4ITModelHandler::RegisterModel().
void G4Scheduler::Reset () virtual
Reimplemented from G4VScheduler.
Definition at line 356 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 356 of file G4Scheduler.cc
References G4ITReactionSet::CleanAllReaction(), DBL_MAX, eUndefined, fContinue, fGlobalTime, fILTimeStep, fInteractionStep, fITStepStatus, fNbSteps, fPreviousTimeStep, fReactionSet, fStartTime, fTimeStep, fTSTimeStep, fUserUpperTimeLimit, and fZeroTimeCount.
Referenced by Process().
void G4Scheduler::SetDefaultTimeStep (double timeStep) inline virtual
Reimplemented from G4VScheduler.
Definition at line 345 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 345 of file G4Scheduler.hh
References fDefaultMinTimeStep.
void G4Scheduler::SetEndTime (const double __endtime) inline virtual
Reimplemented from G4VScheduler.
Definition at line 292 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 292 of file G4Scheduler.hh
References fEndTime.
Referenced by G4SchedulerMessenger::SetNewValue().
void G4Scheduler::SetGun (G4ITGun * gun) inline virtual
Reimplemented from G4VScheduler.
Definition at line 417 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 417 of file G4Scheduler.hh
References fpGun.
Referenced by G4DNAChemistryManager::SetGun().
void G4Scheduler::SetInteractivity (G4ITTrackingInteractivity * interactivity) virtual
Reimplemented from G4VScheduler.
Definition at line 1103 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 1103 of file G4Scheduler.cc
References fpTrackingInteractivity, fpTrackingManager, and G4ITTrackingManager::SetInteractivity().
void G4Scheduler::SetMaxNbSteps (G4int maxSteps) inline virtual
Reimplemented from G4VScheduler.
Definition at line 320 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 320 of file G4Scheduler.hh
References fMaxSteps.
Referenced by G4SchedulerMessenger::SetNewValue().
void G4Scheduler::SetMaxTimeStep (double maxTimeStep) inline
Definition at line 183 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 183 of file G4Scheduler.hh
References fMaxTimeStep.
void G4Scheduler::SetMaxZeroTimeAllowed (int maxTimeStepAllowed) inline virtual
Reimplemented from G4VScheduler.
Definition at line 377 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 377 of file G4Scheduler.hh
References fMaxNZeroTimeStepsAllowed.
Referenced by G4SchedulerMessenger::SetNewValue().
void G4Scheduler::SetTimeSteps (std::map< double, double > * steps) inline virtual
Reimplemented from G4VScheduler.
Definition at line 298 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 298 of file G4Scheduler.hh
References fpUserTimeSteps, fUsePreDefinedTimeSteps, and propagation_timing::steps.
void G4Scheduler::SetTimeTolerance (double time) inline virtual
Reimplemented from G4VScheduler.
Definition at line 387 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 387 of file G4Scheduler.hh
References fTimeTolerance, and Acts::VectorHelpers::time().
Referenced by G4SchedulerMessenger::SetNewValue().
void G4Scheduler::SetUserAction (G4UserTimeStepAction * userITAction) inline virtual
Reimplemented from G4VScheduler.
Definition at line 356 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 356 of file G4Scheduler.hh
References fpUserTimeStepAction.
void G4Scheduler::SetVerbose (int verbose) inline virtual
Reimplemented from G4VScheduler.
Definition at line 366 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 366 of file G4Scheduler.hh
References fVerbose.
Referenced by G4SchedulerMessenger::SetNewValue().
void G4Scheduler::Stepping () protected
Definition at line 649 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 649 of file G4Scheduler.cc
References G4ITModelProcessor::CalculateMinTimeStep(), G4ITReactionSet::CleanAllReaction(), G4ITStepProcessor::ComputeInteractionLength(), G4ITModelProcessor::ComputeTrackReaction(), DBL_MAX, G4ITStepProcessor::DoIt(), eCollisionBetweenTracks, eInteractionWithMedium, eUndefined, FatalErrorInArgument, fDefinedMinTimeStep, fGlobalTime, fILTimeStep, fInteractionStep, fITStepStatus, fMaxNZeroTimeStepsAllowed, fMaxTimeStep, fNbSteps, fpModelProcessor, fPreviousTimeStep, fpStepProcessor, fpUserTimeStepAction, fReachedUserTimeLimit, fReactionSet, fStopTime, fTimeStep, fTimeTolerance, fTSTimeStep, fUseDefaultTimeSteps, fUsePreDefinedTimeSteps, fVerbose, fZeroTimeCount, G4BestUnit, G4cout, G4endl, G4Exception(), GetCollisionType(), G4ITModelProcessor::GetComputeTimeStep(), GetLimitingTimeStep(), LIGHT_RED, G4MemStat::MemoryUsage(), G4ITStepProcessor::PrepareLeadingTracks(), RESET_COLOR, G4ITStepProcessor::ResetLeadingTracks(), G4UserTimeStepAction::UserPostTimeStepAction(), and G4UserTimeStepAction::UserPreTimeStepAction().
Referenced by DoProcess().
void G4Scheduler::Stop () inline
Definition at line 407 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 407 of file G4Scheduler.hh
References fContinue.
void G4Scheduler::SynchronizeTracks () protected
Definition at line 497 of file G4Scheduler.cc.
View newest version in sPHENIX GitHub at line 497 of file G4Scheduler.cc
References CanICarryOn(), DoProcess(), fEndTime, fGlobalTime, fStopTime, fTmpGlobalTime, fTrackContainer, G4ITTrackHolder::GetNextTime(), GetNextWatchedTime(), G4ITTrackHolder::MergeNextTimeToMainList(), and min.
Referenced by Process().
void G4Scheduler::UseDefaultTimeSteps (G4bool flag) inline
Definition at line 432 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 432 of file G4Scheduler.hh
References fUseDefaultTimeSteps.
Referenced by G4SchedulerMessenger::SetNewValue().
void G4Scheduler::WhyDoYouStop () inline
Definition at line 427 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 427 of file G4Scheduler.hh
References fWhyDoYouStop.
Referenced by G4SchedulerMessenger::SetNewValue().
Member Data Documentation
G4bool G4Scheduler::fContinue private
Definition at line 218 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 218 of file G4Scheduler.hh
Referenced by CanICarryOn(), Create(), DoProcess(), PrintWhyDoYouStop(), Reset(), and Stop().
double G4Scheduler::fDefaultMinTimeStep private
Definition at line 242 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 242 of file G4Scheduler.hh
Referenced by Create(), GetLimitingTimeStep(), and SetDefaultTimeStep().
double G4Scheduler::fDefinedMinTimeStep private
Definition at line 246 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 246 of file G4Scheduler.hh
Referenced by Create(), FindUserPreDefinedTimeStep(), GetLimitingTimeStep(), and Stepping().
double G4Scheduler::fEndTime private
Definition at line 232 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 232 of file G4Scheduler.hh
Referenced by CanICarryOn(), Create(), GetEndTime(), SetEndTime(), and SynchronizeTracks().
double G4Scheduler::fGlobalTime private
Definition at line 228 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 228 of file G4Scheduler.hh
Referenced by CanICarryOn(), Create(), DoProcess(), FindUserPreDefinedTimeStep(), GetGlobalTime(), GetLimitingTimeStep(), GetNextWatchedTime(), PrintWhyDoYouStop(), Process(), Reset(), Stepping(), and SynchronizeTracks().
G4ThreadLocal G4Scheduler * G4Scheduler::fgScheduler static private
Definition at line 213 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 213 of file G4Scheduler.hh
Referenced by ~G4Scheduler().
double G4Scheduler::fILTimeStep private
Definition at line 267 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 267 of file G4Scheduler.hh
Referenced by Create(), Reset(), and Stepping().
bool G4Scheduler::fInitialized private
Definition at line 216 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 216 of file G4Scheduler.hh
Referenced by Create(), ForceReinitialization(), Initialize(), IsInitialized(), and Process().
bool G4Scheduler::fInteractionStep private
Definition at line 271 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 271 of file G4Scheduler.hh
Referenced by Create(), Reset(), and Stepping().
G4ITStepStatus G4Scheduler::fITStepStatus private
Definition at line 223 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 223 of file G4Scheduler.hh
Referenced by Create(), GetCollisionType(), GetStatus(), Reset(), and Stepping().
int G4Scheduler::fMaxNZeroTimeStepsAllowed private
Definition at line 235 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 235 of file G4Scheduler.hh
Referenced by Create(), GetMaxZeroTimeAllowed(), SetMaxZeroTimeAllowed(), and Stepping().
int G4Scheduler::fMaxSteps private
Definition at line 221 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Scheduler.hh
Referenced by CanICarryOn(), Create(), DoProcess(), GetMaxNbSteps(), PrintWhyDoYouStop(), and SetMaxNbSteps().
double G4Scheduler::fMaxTimeStep private
Definition at line 238 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 238 of file G4Scheduler.hh
Referenced by Create(), GetMaxTimeStep(), SetMaxTimeStep(), and Stepping().
int G4Scheduler::fNbSteps private
Definition at line 220 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 220 of file G4Scheduler.hh
Referenced by CanICarryOn(), Create(), DoProcess(), GetNbSteps(), PrintWhyDoYouStop(), Reset(), and Stepping().
G4ITGun* G4Scheduler::fpGun private
Definition at line 275 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 275 of file G4Scheduler.hh
Referenced by Create(), GetGun(), Process(), and SetGun().
G4SchedulerMessenger* G4Scheduler::fpMessenger private
Definition at line 211 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 211 of file G4Scheduler.hh
Referenced by Clear(), Create(), and ~G4Scheduler().
G4ITModelHandler* G4Scheduler::fpModelHandler private
Definition at line 262 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 262 of file G4Scheduler.hh
Referenced by Clear(), Create(), GetModelHandler(), Initialize(), and RegisterModel().
G4ITModelProcessor* G4Scheduler::fpModelProcessor private
Definition at line 257 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 257 of file G4Scheduler.hh
Referenced by Clear(), Create(), Initialize(), Process(), and Stepping().
double G4Scheduler::fPreviousTimeStep private
Definition at line 233 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 233 of file G4Scheduler.hh
Referenced by Create(), GetPreviousTimeStep(), Reset(), and Stepping().
G4ITStepProcessor* G4Scheduler::fpStepProcessor private
Definition at line 256 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 256 of file G4Scheduler.hh
Referenced by Clear(), Create(), Initialize(), Process(), and Stepping().
G4ITTrackingInteractivity* G4Scheduler::fpTrackingInteractivity private
Definition at line 259 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 259 of file G4Scheduler.hh
Referenced by Create(), GetInteractivity(), Initialize(), Process(), and SetInteractivity().
G4ITTrackingManager* G4Scheduler::fpTrackingManager private
Definition at line 258 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 258 of file G4Scheduler.hh
Referenced by Clear(), Create(), EndTracking(), Initialize(), and SetInteractivity().
G4UserTimeStepAction* G4Scheduler::fpUserTimeStepAction private
Definition at line 252 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 252 of file G4Scheduler.hh
Referenced by Create(), DoProcess(), GetUserTimeStepAction(), Process(), SetUserAction(), and Stepping().
std::map<double, double>* G4Scheduler::fpUserTimeSteps private
Definition at line 243 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 243 of file G4Scheduler.hh
Referenced by AddTimeStep(), Create(), FindUserPreDefinedTimeStep(), GetLimitingTimeStep(), Initialize(), and SetTimeSteps().
bool G4Scheduler::fReachedUserTimeLimit private
Definition at line 248 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 248 of file G4Scheduler.hh
Referenced by Create(), and Stepping().
G4ITReactionSet* G4Scheduler::fReactionSet private
Definition at line 260 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 260 of file G4Scheduler.hh
Referenced by Clear(), Create(), Reset(), and Stepping().
bool G4Scheduler::fRunning private
Definition at line 217 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 217 of file G4Scheduler.hh
Referenced by Create(), EndTracking(), IsRunning(), and Process().
double G4Scheduler::fStartTime private
Definition at line 230 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 230 of file G4Scheduler.hh
Referenced by Create(), GetStartTime(), Process(), and Reset().
double G4Scheduler::fStopTime private
Definition at line 231 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 231 of file G4Scheduler.hh
Referenced by Create(), DoProcess(), GetLimitingTimeStep(), PrintWhyDoYouStop(), Stepping(), and SynchronizeTracks().
double G4Scheduler::fTimeStep private
Definition at line 237 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 237 of file G4Scheduler.hh
Referenced by Create(), GetTimeStep(), Reset(), and Stepping().
double G4Scheduler::fTimeTolerance private
Definition at line 227 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 227 of file G4Scheduler.hh
Referenced by Create(), FindUserPreDefinedTimeStep(), GetLimitingTimeStep(), GetTimeTolerance(), SetTimeTolerance(), and Stepping().
double G4Scheduler::fTmpGlobalTime private
Definition at line 229 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 229 of file G4Scheduler.hh
Referenced by Create(), and SynchronizeTracks().
G4ITTrackHolder& G4Scheduler::fTrackContainer private
Definition at line 261 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 261 of file G4Scheduler.hh
Referenced by ClearList(), DoProcess(), EndTracking(), GetNTracks(), PrintWhyDoYouStop(), Process(), and SynchronizeTracks().
double G4Scheduler::fTSTimeStep private
Definition at line 265 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 265 of file G4Scheduler.hh
Referenced by Create(), Reset(), and Stepping().
G4bool G4Scheduler::fUseDefaultTimeSteps private
Definition at line 226 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 226 of file G4Scheduler.hh
Referenced by AreDefaultTimeStepsUsed(), Create(), Stepping(), and UseDefaultTimeSteps().
bool G4Scheduler::fUsePreDefinedTimeSteps private
Definition at line 241 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 241 of file G4Scheduler.hh
Referenced by AddTimeStep(), AreDefaultTimeStepsUsed(), Create(), Initialize(), SetTimeSteps(), and Stepping().
double G4Scheduler::fUserUpperTimeLimit mutable private
Definition at line 245 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 245 of file G4Scheduler.hh
Referenced by Create(), GetLimitingTimeStep(), and Reset().
int G4Scheduler::fVerbose private
Definition at line 214 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 214 of file G4Scheduler.hh
Referenced by Create(), DoProcess(), GetVerbose(), Process(), SetVerbose(), and Stepping().
std::set<double> G4Scheduler::fWatchedTimes private
Definition at line 250 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 250 of file G4Scheduler.hh
Referenced by AddWatchedTime(), and GetNextWatchedTime().
bool G4Scheduler::fWhyDoYouStop private
Definition at line 215 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 215 of file G4Scheduler.hh
Referenced by Create(), PrintWhyDoYouStop(), and WhyDoYouStop().
int G4Scheduler::fZeroTimeCount private
Definition at line 234 of file G4Scheduler.hh.
View newest version in sPHENIX GitHub at line 234 of file G4Scheduler.hh
Referenced by Create(), Reset(), and Stepping().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4Scheduler.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4Scheduler.cc