ECCE @ EIC Software: G4INCL::Pauli Namespace Reference
G4INCL::Pauli Namespace Reference
Pauli blocking.
Functions
G4bool isBlocked (ParticleList const &p, Nucleus const *const n)
Check Pauli blocking.
G4bool isCDPPBlocked (ParticleList const &p, Nucleus const *const n)
Check CDPP blocking.
IPauli * getBlocker ()
Get the Pauli blocker algorithm.
IPauli * getCDPP ()
Get the CDPP blocker algorithm.
void setBlocker (IPauli *const)
Set the Pauli blocker algorithm.
void setCDPP (IPauli *const)
Set the CDPP blocker algorithm.
void deleteBlockers ()
Delete blockers.
void initialize (Config const *const aConfig)
Initialise blockers according to a Config object.
Detailed Description
Pauli blocking.
Function Documentation
void G4INCL::Pauli::deleteBlockers ()
Delete blockers.
Definition at line 87 of file G4INCLPauliBlocking.cc.
View newest version in sPHENIX GitHub at line 87 of file G4INCLPauliBlocking.cc
Referenced by G4INCL::INCL::~INCL().
IPauli * G4INCL::Pauli::getBlocker ()
Get the Pauli blocker algorithm.
Definition at line 57 of file G4INCLPauliBlocking.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLPauliBlocking.cc
IPauli * G4INCL::Pauli::getCDPP ()
Get the CDPP blocker algorithm.
Definition at line 59 of file G4INCLPauliBlocking.cc.
View newest version in sPHENIX GitHub at line 59 of file G4INCLPauliBlocking.cc
void G4INCL::Pauli::initialize (Config const *const aConfig)
Initialise blockers according to a Config object.
Definition at line 94 of file G4INCLPauliBlocking.cc.
View newest version in sPHENIX GitHub at line 94 of file G4INCLPauliBlocking.cc
References G4INCL::Config::getCDPP(), G4INCL::Config::getPauliType(), G4INCL::GlobalPauli, G4INCL::NoPauli, setBlocker(), setCDPP(), G4INCL::StatisticalPauli, G4INCL::StrictPauli, and G4INCL::StrictStatisticalPauli.
Referenced by G4INCL::INCL::INCL().
G4bool G4INCL::Pauli::isBlocked (ParticleList const & p, Nucleus const *const n)
Check Pauli blocking.
Note: This is a "pure" function: it doesn't retain or modify any state at all and thus only depends on its arguments.
Parameters
p list of modified and created particles
n the nucleus
Definition at line 69 of file G4INCLPauliBlocking.cc.
View newest version in sPHENIX GitHub at line 69 of file G4INCLPauliBlocking.cc
Referenced by G4INCL::InteractionAvatar::postInteraction().
G4bool G4INCL::Pauli::isCDPPBlocked (ParticleList const & p, Nucleus const *const n)
Check CDPP blocking.
Note: This is a "pure" function: it doesn't retain or modify any state at all and thus only depends on its arguments.
Parameters
p list of created particles
n the nucleus
Definition at line 78 of file G4INCLPauliBlocking.cc.
View newest version in sPHENIX GitHub at line 78 of file G4INCLPauliBlocking.cc
Referenced by G4INCL::DecayAvatar::postInteraction(), and G4INCL::InteractionAvatar::postInteraction().
void G4INCL::Pauli::setBlocker (IPauli * const pauliBlocker)
Set the Pauli blocker algorithm.
Definition at line 61 of file G4INCLPauliBlocking.cc.
View newest version in sPHENIX GitHub at line 61 of file G4INCLPauliBlocking.cc
Referenced by initialize().
void G4INCL::Pauli::setCDPP (IPauli * const cdpp)
Set the CDPP blocker algorithm.
Definition at line 65 of file G4INCLPauliBlocking.cc.
View newest version in sPHENIX GitHub at line 65 of file G4INCLPauliBlocking.cc
Referenced by initialize().