ECCE @ EIC Software: InteractionInformation Class Reference
InteractionInformation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/doiPET/include/doiPETRun.hh>
Public Member Functions
InteractionInformation ()
~InteractionInformation ()
void SetEdep (G4double e)
void SetBlockNo (G4int n)
void SetCrystalNo (G4int n)
void SetGlobalTime (G4double t)
void SetInteractionPositionInCrystal (G4ThreeVector pos)
G4double GetEdep ()
G4int GetBlockNo ()
G4int GetCrystalNo ()
G4double GetGlobalTime ()
G4ThreeVector GetInteractionPositionInCrystal ()
Private Attributes
G4double edep
G4double globalTime
G4int blockNo
G4int crystalNo
G4ThreeVector crystalPosition
Detailed Description
Definition at line 105 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 105 of file doiPETRun.hh
Constructor & Destructor Documentation
InteractionInformation::InteractionInformation () inline
Definition at line 109 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 109 of file doiPETRun.hh
InteractionInformation::~InteractionInformation () inline
Definition at line 110 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 110 of file doiPETRun.hh
Member Function Documentation
G4int InteractionInformation::GetBlockNo () inline
Definition at line 129 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 129 of file doiPETRun.hh
References blockNo.
Referenced by doiPETRun::GetIntractionInfomation().
G4int InteractionInformation::GetCrystalNo () inline
Definition at line 130 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 130 of file doiPETRun.hh
References crystalNo.
G4double InteractionInformation::GetEdep () inline
Definition at line 128 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 128 of file doiPETRun.hh
References edep.
G4double InteractionInformation::GetGlobalTime () inline
Definition at line 131 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 131 of file doiPETRun.hh
References globalTime.
G4ThreeVector InteractionInformation::GetInteractionPositionInCrystal () inline
Definition at line 134 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 134 of file doiPETRun.hh
References crystalPosition.
void InteractionInformation::SetBlockNo (G4int n) inline
Definition at line 116 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 116 of file doiPETRun.hh
References blockNo, and n.
Referenced by doiPETSteppingAction::UserSteppingAction().
void InteractionInformation::SetCrystalNo (G4int n) inline
Definition at line 119 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 119 of file doiPETRun.hh
References crystalNo, and n.
Referenced by doiPETSteppingAction::UserSteppingAction().
void InteractionInformation::SetEdep (G4double e) inline
Definition at line 113 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 113 of file doiPETRun.hh
References e, and edep.
Referenced by doiPETSteppingAction::UserSteppingAction().
void InteractionInformation::SetGlobalTime (G4double t) inline
Definition at line 122 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 122 of file doiPETRun.hh
References globalTime, and t.
Referenced by doiPETSteppingAction::UserSteppingAction().
void InteractionInformation::SetInteractionPositionInCrystal (G4ThreeVector pos) inline
Definition at line 125 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 125 of file doiPETRun.hh
References crystalPosition, and pos().
Referenced by doiPETSteppingAction::UserSteppingAction().
Member Data Documentation
G4int InteractionInformation::blockNo private
Definition at line 140 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 140 of file doiPETRun.hh
Referenced by GetBlockNo(), and SetBlockNo().
G4int InteractionInformation::crystalNo private
Definition at line 141 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 141 of file doiPETRun.hh
Referenced by GetCrystalNo(), and SetCrystalNo().
G4ThreeVector InteractionInformation::crystalPosition private
Definition at line 142 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 142 of file doiPETRun.hh
Referenced by GetInteractionPositionInCrystal(), and SetInteractionPositionInCrystal().
G4double InteractionInformation::edep private
Definition at line 134 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 134 of file doiPETRun.hh
Referenced by GetEdep(), and SetEdep().
G4double InteractionInformation::globalTime private
Definition at line 139 of file doiPETRun.hh.
View newest version in sPHENIX GitHub at line 139 of file doiPETRun.hh
Referenced by GetGlobalTime(), and SetGlobalTime().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/advanced/doiPET/include/doiPETRun.hh