ECCE @ EIC Software: G4LowEnergyPolarizedCompton Class Reference
G4LowEnergyPolarizedCompton Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4LowEnergyPolarizedCompton.hh>
Public Member Functions
G4LowEnergyPolarizedCompton (const G4String &processName="polarLowEnCompt")
~G4LowEnergyPolarizedCompton ()
G4bool IsApplicable (const G4ParticleDefinition &definition)
void BuildPhysicsTable (const G4ParticleDefinition &photon)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep)
G4double DumpMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
Private Member Functions
G4LowEnergyPolarizedCompton & operator= (const G4LowEnergyPolarizedCompton &right)
G4LowEnergyPolarizedCompton (const G4LowEnergyPolarizedCompton &)
G4ThreeVector GetRandomPolarization (G4ThreeVector &direction0)
G4ThreeVector GetPerpendicularPolarization (const G4ThreeVector &direction0, const G4ThreeVector &polarization0) const
G4ThreeVector SetPerpendicularVector (G4ThreeVector &a)
G4ThreeVector SetNewPolarization (G4double epsilon, G4double sinSqrTheta, G4double phi, G4double cosTheta)
G4double SetPhi (G4double, G4double)
void SystemOfRefChange (G4ThreeVector &direction0, G4ThreeVector &direction1, G4ThreeVector &polarization0, G4ThreeVector &polarization1)
Private Attributes
G4double lowEnergyLimit
G4double highEnergyLimit
G4RDVEMDataSet * meanFreePathTable
G4RDVEMDataSet * scatterFunctionData
G4RDVCrossSectionHandler * crossSectionHandler
G4RDVRangeTest * rangeTest
const G4double intrinsicLowEnergyLimit
const G4double intrinsicHighEnergyLimit
G4RDShellData shellData
G4RDDopplerProfile profileData
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 72 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 72 of file G4LowEnergyPolarizedCompton.hh
Constructor & Destructor Documentation
G4LowEnergyPolarizedCompton::G4LowEnergyPolarizedCompton (const G4String & processName = "polarLowEnCompt")
Definition at line 87 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 87 of file G4LowEnergyPolarizedCompton.cc
References crossSectionHandler, FatalException, G4cout, G4endl, G4Exception(), G4VProcess::GetProcessName(), GeV, highEnergyLimit, intrinsicHighEnergyLimit, intrinsicLowEnergyLimit, keV, G4RDVEMDataSet::LoadData(), lowEnergyLimit, meanFreePathTable, rangeTest, scatterFunctionData, G4RDShellData::SetOccupancyData(), shellData, and G4VProcess::verboseLevel.
G4LowEnergyPolarizedCompton::~G4LowEnergyPolarizedCompton ()
Definition at line 130 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 130 of file G4LowEnergyPolarizedCompton.cc
References crossSectionHandler, meanFreePathTable, rangeTest, and scatterFunctionData.
G4LowEnergyPolarizedCompton::G4LowEnergyPolarizedCompton (const G4LowEnergyPolarizedCompton &) private
Member Function Documentation
void G4LowEnergyPolarizedCompton::BuildPhysicsTable (const G4ParticleDefinition & photon) virtual
Reimplemented from G4VProcess.
Definition at line 139 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 139 of file G4LowEnergyPolarizedCompton.cc
References G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4RDVCrossSectionHandler::Clear(), crossSectionHandler, file, G4RDShellData::LoadData(), G4RDVCrossSectionHandler::LoadData(), meanFreePathTable, and shellData.
G4double G4LowEnergyPolarizedCompton::DumpMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) inline
Definition at line 87 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 87 of file G4LowEnergyPolarizedCompton.hh
References GetMeanFreePath().
G4double G4LowEnergyPolarizedCompton::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) protected virtual
Implements G4VDiscreteProcess.
Definition at line 688 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 688 of file G4LowEnergyPolarizedCompton.cc
References DBL_MAX, energy, G4RDVEMDataSet::FindValue(), G4Track::GetDynamicParticle(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), highEnergyLimit, lowEnergyLimit, meanFreePathTable, and G4InuclParticleNames::photon.
Referenced by DumpMeanFreePath().
G4ThreeVector G4LowEnergyPolarizedCompton::GetPerpendicularPolarization (const G4ThreeVector & direction0, const G4ThreeVector & polarization0) const private
Definition at line 548 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 548 of file G4LowEnergyPolarizedCompton.cc
References CLHEP::Hep3Vector::dot().
Referenced by PostStepDoIt().
G4ThreeVector G4LowEnergyPolarizedCompton::GetRandomPolarization (G4ThreeVector & direction0) private
Definition at line 523 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 523 of file G4LowEnergyPolarizedCompton.cc
References a0, angle, c, CLHEP::Hep3Vector::cross(), G4UniformRand, ds::rand1, SetPerpendicularVector(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by PostStepDoIt().
G4bool G4LowEnergyPolarizedCompton::IsApplicable (const G4ParticleDefinition & definition) virtual
Reimplemented from G4VProcess.
Definition at line 682 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 682 of file G4LowEnergyPolarizedCompton.cc
References G4Gamma::Gamma().
G4LowEnergyPolarizedCompton& G4LowEnergyPolarizedCompton::operator= (const G4LowEnergyPolarizedCompton & right) private
G4VParticleChange * G4LowEnergyPolarizedCompton::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
Doppler Broadeing
Reimplemented from G4VDiscreteProcess.
Definition at line 154 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 154 of file G4LowEnergyPolarizedCompton.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, G4RDShellData::BindingEnergy(), source.hepunit::c_light, cm, crossSectionHandler, e, G4InuclParticleNames::electron, G4Electron::Electron(), source.hepunit::electron_mass_c2, epsilon(), source.hepunit::epsilon0, G4RDVRangeTest::Escape(), G4RDVEMDataSet::FindValue(), source.hepunit::fine_structure_const, fStopAndKill, G4cout, G4endl, G4UniformRand, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), GetPerpendicularPolarization(), G4DynamicParticle::GetPolarization(), G4Step::GetPostStepPoint(), GetRandomPolarization(), G4StepPoint::GetSafety(), source.hepunit::h_Planck, CLHEP::Hep3Vector::howOrthogonal(), G4ParticleChange::Initialize(), CLHEP::Hep3Vector::isOrthogonal(), lowEnergyLimit, CLHEP::Hep3Vector::mag(), phi, G4VDiscreteProcess::PostStepDoIt(), profileData, G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4ParticleChange::ProposePolarization(), G4VParticleChange::ProposeTrackStatus(), G4RDDopplerProfile::RandomSelectMomentum(), rangeTest, scale, scatterFunctionData, G4RDVCrossSectionHandler::SelectRandomAtom(), G4RDShellData::SelectRandomShell(), SetNewPolarization(), G4VParticleChange::SetNumberOfSecondaries(), SetPhi(), shellData, SystemOfRefChange(), CLHEP::Hep3Vector::unit(), G4VProcess::verboseLevel, x, and Z.
G4ThreeVector G4LowEnergyPolarizedCompton::SetNewPolarization (G4double epsilon, G4double sinSqrTheta, G4double phi, G4double cosTheta) private
Definition at line 565 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 565 of file G4LowEnergyPolarizedCompton.cc
References G4UniformRand, pi, ds::rand1, ds::rand2, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and theta().
Referenced by PostStepDoIt().
G4ThreeVector G4LowEnergyPolarizedCompton::SetPerpendicularVector (G4ThreeVector & a) private
Definition at line 508 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 508 of file G4LowEnergyPolarizedCompton.cc
References dx, dy, dz, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Referenced by GetRandomPolarization().
G4double G4LowEnergyPolarizedCompton::SetPhi (G4double energyRate, G4double sinSqrTh) private
Definition at line 479 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 479 of file G4LowEnergyPolarizedCompton.cc
References a, b, G4UniformRand, phi, ds::rand1, ds::rand2, and twopi.
Referenced by PostStepDoIt().
void G4LowEnergyPolarizedCompton::SystemOfRefChange (G4ThreeVector & direction0, G4ThreeVector & direction1, G4ThreeVector & polarization0, G4ThreeVector & polarization1) private
Definition at line 656 of file G4LowEnergyPolarizedCompton.cc.
View newest version in sPHENIX GitHub at line 656 of file G4LowEnergyPolarizedCompton.cc
References CLHEP::Hep3Vector::cross(), CLHEP::Hep3Vector::getX(), CLHEP::Hep3Vector::getY(), CLHEP::Hep3Vector::getZ(), and CLHEP::Hep3Vector::unit().
Referenced by PostStepDoIt().
Member Data Documentation
G4RDVCrossSectionHandler* G4LowEnergyPolarizedCompton::crossSectionHandler private
Definition at line 112 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 112 of file G4LowEnergyPolarizedCompton.hh
Referenced by BuildPhysicsTable(), G4LowEnergyPolarizedCompton(), PostStepDoIt(), and ~G4LowEnergyPolarizedCompton().
G4double G4LowEnergyPolarizedCompton::highEnergyLimit private
Definition at line 107 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 107 of file G4LowEnergyPolarizedCompton.hh
Referenced by G4LowEnergyPolarizedCompton(), and GetMeanFreePath().
const G4double G4LowEnergyPolarizedCompton::intrinsicHighEnergyLimit private
Definition at line 116 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 116 of file G4LowEnergyPolarizedCompton.hh
Referenced by G4LowEnergyPolarizedCompton().
const G4double G4LowEnergyPolarizedCompton::intrinsicLowEnergyLimit private
Definition at line 115 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 115 of file G4LowEnergyPolarizedCompton.hh
Referenced by G4LowEnergyPolarizedCompton().
G4double G4LowEnergyPolarizedCompton::lowEnergyLimit private
Definition at line 106 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 106 of file G4LowEnergyPolarizedCompton.hh
Referenced by G4LowEnergyPolarizedCompton(), GetMeanFreePath(), and PostStepDoIt().
G4RDVEMDataSet* G4LowEnergyPolarizedCompton::meanFreePathTable private
Definition at line 109 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 109 of file G4LowEnergyPolarizedCompton.hh
Referenced by BuildPhysicsTable(), G4LowEnergyPolarizedCompton(), GetMeanFreePath(), and ~G4LowEnergyPolarizedCompton().
G4RDDopplerProfile G4LowEnergyPolarizedCompton::profileData private
Definition at line 134 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 134 of file G4LowEnergyPolarizedCompton.hh
Referenced by PostStepDoIt().
G4RDVRangeTest* G4LowEnergyPolarizedCompton::rangeTest private
Definition at line 113 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 113 of file G4LowEnergyPolarizedCompton.hh
Referenced by G4LowEnergyPolarizedCompton(), PostStepDoIt(), and ~G4LowEnergyPolarizedCompton().
G4RDVEMDataSet* G4LowEnergyPolarizedCompton::scatterFunctionData private
Definition at line 110 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 110 of file G4LowEnergyPolarizedCompton.hh
Referenced by G4LowEnergyPolarizedCompton(), PostStepDoIt(), and ~G4LowEnergyPolarizedCompton().
G4RDShellData G4LowEnergyPolarizedCompton::shellData private
Definition at line 133 of file G4LowEnergyPolarizedCompton.hh.
View newest version in sPHENIX GitHub at line 133 of file G4LowEnergyPolarizedCompton.hh
Referenced by BuildPhysicsTable(), G4LowEnergyPolarizedCompton(), and PostStepDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4LowEnergyPolarizedCompton.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4LowEnergyPolarizedCompton.cc