ECCE @ EIC Software: G4AntiDeuteron Class Reference
G4AntiDeuteron Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/include/G4AntiDeuteron.hh>
Static Public Member Functions
static G4AntiDeuteron * Definition ()
static G4AntiDeuteron * AntiDeuteronDefinition ()
static G4AntiDeuteron * AntiDeuteron ()
Static Public Member Functions inherited from G4Ions
static G4Ions::G4FloatLevelBase FloatLevelBase (char flbChar)
static G4Ions::G4FloatLevelBase FloatLevelBase (G4int flbIdx)
static char FloatLevelBaseChar (G4Ions::G4FloatLevelBase flb)
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4AntiDeuteron ()
~G4AntiDeuteron ()
Static Private Attributes
static G4AntiDeuteron * theInstance = 0
Additional Inherited Members
Public Types inherited from G4Ions
enum G4FloatLevelBase
Public Member Functions inherited from G4Ions
G4Ions (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0, G4int isomer=0)
virtual ~G4Ions ()
G4Ions * IonsDefinition ()
G4Ions * Ions ()
G4double GetExcitationEnergy () const
G4int GetIsomerLevel () const
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
G4int GetFloatLevelBaseIndex () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (char flbChar)
void SetFloatLevelBase (G4int flbIdx)
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4Ions
G4Ions ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 50 of file G4AntiDeuteron.hh.
View newest version in sPHENIX GitHub at line 50 of file G4AntiDeuteron.hh
Constructor & Destructor Documentation
G4AntiDeuteron::G4AntiDeuteron () inline private
Definition at line 54 of file G4AntiDeuteron.hh.
View newest version in sPHENIX GitHub at line 54 of file G4AntiDeuteron.hh
G4AntiDeuteron::~G4AntiDeuteron () inline private
Definition at line 55 of file G4AntiDeuteron.hh.
View newest version in sPHENIX GitHub at line 55 of file G4AntiDeuteron.hh
Member Function Documentation
G4AntiDeuteron * G4AntiDeuteron::AntiDeuteron () static
Definition at line 93 of file G4AntiDeuteron.cc.
View newest version in sPHENIX GitHub at line 93 of file G4AntiDeuteron.cc
References Definition().
Referenced by G4AntiBarionBuilder::Build(), AntiBaryonPhysics::ConstructProcess(), G4HadronPhysicsFTFQGSP_BERT::ConstructProcess(), G4AntiNuclElastic::G4AntiNuclElastic(), G4ComponentAntiNuclNuclearXS::G4ComponentAntiNuclNuclearXS(), and G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface().
G4AntiDeuteron * G4AntiDeuteron::AntiDeuteronDefinition () static
Definition at line 88 of file G4AntiDeuteron.cc.
View newest version in sPHENIX GitHub at line 88 of file G4AntiDeuteron.cc
References Definition().
Referenced by G4IonConstructor::ConstructLightIons(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
G4AntiDeuteron * G4AntiDeuteron::Definition () static
Definition at line 49 of file G4AntiDeuteron.cc.
View newest version in sPHENIX GitHub at line 49 of file G4AntiDeuteron.cc
References source.hepunit::c_squared, eplus, G4ParticleTable::FindParticle(), G4Ions::G4Ions(), G4ParticleTable::GetParticleTable(), GeV, source.hepunit::hbar_Planck, MeV, source.hepunit::proton_mass_c2, G4ParticleDefinition::SetPDGMagneticMoment(), and theInstance.
Referenced by AntiDeuteron(), AntiDeuteronDefinition(), G4InuclElementaryParticle::makeDefinition(), and G4InuclElementaryParticle::type().
Member Data Documentation
G4AntiDeuteron * G4AntiDeuteron::theInstance = 0 static private
Definition at line 53 of file G4AntiDeuteron.hh.
View newest version in sPHENIX GitHub at line 53 of file G4AntiDeuteron.hh
Referenced by Definition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/include/G4AntiDeuteron.hh
geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/src/G4AntiDeuteron.cc