ECCE @ EIC Software: G4WorkerRunManager Class Reference
G4WorkerRunManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4WorkerRunManager.hh>
Public Member Functions
G4WorkerRunManager ()
~G4WorkerRunManager ()
virtual void InitializeGeometry ()
virtual void RunInitialization ()
virtual void DoEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void ProcessOneEvent (G4int i_event)
virtual G4Event * GenerateEvent (G4int i_event)
virtual void RunTermination ()
virtual void TerminateEventLoop ()
virtual void DoWork ()
void SetWorkerThread (G4WorkerThread *wc)
Sets the worker context.
virtual void SetUserInitialization (G4VUserPhysicsList *userInit)
virtual void SetUserInitialization (G4VUserDetectorConstruction *userInit)
virtual void SetUserInitialization (G4VUserActionInitialization *userInit)
virtual void SetUserInitialization (G4UserWorkerInitialization *userInit)
virtual void SetUserInitialization (G4UserWorkerThreadInitialization *userInit)
virtual void SetUserAction (G4UserRunAction *userAction)
virtual void SetUserAction (G4VUserPrimaryGeneratorAction *userAction)
virtual void SetUserAction (G4UserEventAction *userAction)
virtual void SetUserAction (G4UserStackingAction *userAction)
virtual void SetUserAction (G4UserTrackingAction *userAction)
virtual void SetUserAction (G4UserSteppingAction *userAction)
virtual void RestoreRndmEachEvent (G4bool flag)
Public Member Functions inherited from G4RunManager
G4RunManager ()
virtual ~G4RunManager ()
virtual void BeamOn (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void Initialize ()
virtual void DefineWorldVolume (G4VPhysicalVolume *worldVol, G4bool topologyIsChanged=true)
virtual void AbortRun (G4bool softAbort=false)
virtual void AbortEvent ()
virtual void InitializePhysics ()
virtual G4bool ConfirmBeamOnCondition ()
virtual void InitializeEventLoop (G4int n_event, const char *macroFile=0, G4int n_select=-1)
virtual void TerminateOneEvent ()
virtual void AnalyzeEvent (G4Event *anEvent)
void DumpRegion (const G4String &rname) const
void DumpRegion (G4Region *region=0) const
virtual void RestoreRandomNumberStatus (const G4String &fileN)
const G4VUserDetectorConstruction * GetUserDetectorConstruction () const
const G4VUserPhysicsList * GetUserPhysicsList () const
const G4VUserActionInitialization * GetUserActionInitialization () const
G4VUserActionInitialization * GetNonConstUserActionInitialization () const
const G4UserWorkerInitialization * GetUserWorkerInitialization () const
const
G4UserWorkerThreadInitialization * GetUserWorkerThreadInitialization () const
const G4UserRunAction * GetUserRunAction () const
const
G4VUserPrimaryGeneratorAction * GetUserPrimaryGeneratorAction () const
const G4UserEventAction * GetUserEventAction () const
const G4UserStackingAction * GetUserStackingAction () const
const G4UserTrackingAction * GetUserTrackingAction () const
const G4UserSteppingAction * GetUserSteppingAction () const
void SetNumberOfAdditionalWaitingStacks (G4int iAdd)
const G4String & GetVersionString () const
void SetPrimaryTransformer (G4PrimaryTransformer *pt)
void StoreRandomNumberStatusToG4Event (G4int vl)
G4int GetFlagRandomNumberStatusToG4Event () const
void SetRandomNumberStore (G4bool flag)
G4bool GetRandomNumberStore () const
void SetRandomNumberStoreDir (const G4String &dir)
const G4String & GetRandomNumberStoreDir () const
const G4String & GetRandomNumberStatusForThisRun () const
const G4String & GetRandomNumberStatusForThisEvent () const
void SetRandomNumberStorePerEvent (G4bool flag)
G4bool GetRandomNumberStorePerEvent () const
void GeometryHasBeenModified (G4bool prop=true)
void ReinitializeGeometry (G4bool destroyFirst=false, G4bool prop=true)
void PhysicsHasBeenModified ()
void CutOffHasBeenModified ()
void ReOptimizeMotherOf (G4VPhysicalVolume *)
void ReOptimize (G4LogicalVolume *)
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
G4int GetPrintProgress ()
void SetPrintProgress (G4int i)
void SetGeometryToBeOptimized (G4bool vl)
G4bool GetGeometryToBeOptimized ()
void SetNumberOfEventsToBeStored (G4int val)
const G4Run * GetCurrentRun () const
G4Run * GetNonConstCurrentRun () const
const G4Event * GetCurrentEvent () const
const G4Event * GetPreviousEvent (G4int i) const
void SetRunIDCounter (G4int i)
G4int GetNumberOfParallelWorld () const
void SetNumberOfEventsToBeProcessed (G4int val)
G4int GetNumberOfEventsToBeProcessed () const
G4int GetNumberOfSelectEvents () const
G4String GetSelectMacro () const
void SetDCtable (G4DCtable *DCtbl)
RMType GetRunManagerType () const
void GeometryDirectlyUpdated (G4bool val=true)
Static Public Member Functions
static G4WorkerRunManager * GetWorkerRunManager ()
static G4WorkerRunManagerKernel * GetWorkerRunManagerKernel ()
Static Public Member Functions inherited from G4RunManager
static G4RunManager * GetRunManager ()
static G4bool IfGeometryHasBeenDestroyed ()
Protected Member Functions
virtual void ConstructScoringWorlds ()
virtual void StoreRNGStatus (const G4String &filenamePrefix)
virtual void rndmSaveThisRun ()
virtual void rndmSaveThisEvent ()
virtual void MergePartialResults ()
Protected Member Functions inherited from G4RunManager
void CleanUpPreviousEvents ()
void CleanUpUnnecessaryEvents (G4int keepNEvents)
void StackPreviousEvent (G4Event *anEvent)
G4RunManager (RMType rmType)
void UpdateScoring ()
virtual void DeleteUserInitializations ()
Protected Attributes
G4bool eventLoopOnGoing
G4bool runIsSeeded
G4int nevModulo
G4int currEvID
G4int luxury
G4SeedsQueue seedsQueue
G4bool readStatusFromFile
Protected Attributes inherited from G4RunManager
G4RunManagerKernel * kernel
G4EventManager * eventManager
G4VUserDetectorConstruction * userDetector
G4VUserPhysicsList * physicsList
G4VUserActionInitialization * userActionInitialization
G4UserWorkerInitialization * userWorkerInitialization
G4UserWorkerThreadInitialization * userWorkerThreadInitialization
G4UserRunAction * userRunAction
G4VUserPrimaryGeneratorAction * userPrimaryGeneratorAction
G4UserEventAction * userEventAction
G4UserStackingAction * userStackingAction
G4UserTrackingAction * userTrackingAction
G4UserSteppingAction * userSteppingAction
G4bool geometryInitialized
G4bool physicsInitialized
G4bool runAborted
G4bool initializedAtLeastOnce
G4bool geometryToBeOptimized
G4int runIDCounter
G4int verboseLevel
G4int printModulo
G4Timer * timer
G4DCtable * DCtable
G4Run * currentRun
G4Event * currentEvent
std::list< G4Event * > * previousEvents
G4int n_perviousEventsToBeStored
G4int numberOfEventToBeProcessed
G4bool storeRandomNumberStatus
G4int storeRandomNumberStatusToG4Event
G4String randomNumberStatusDir
G4String randomNumberStatusForThisRun
G4String randomNumberStatusForThisEvent
G4bool rngStatusEventsFlag
G4VPhysicalVolume * currentWorld
G4int nParallelWorlds
G4String msgText
G4int n_select_msg
G4int numberOfEventProcessed
G4String selectMacro
G4bool fakeRun
G4bool isScoreNtupleWriter
RMType runManagerType
G4bool geometryDirectlyUpdated
Private Member Functions
void SetupDefaultRNGEngine ()
Private Attributes
G4WorkerThread * workerContext
Additional Inherited Members
Public Types inherited from G4RunManager
enum RMType { sequentialRM, masterRM, workerRM }
Static Protected Attributes inherited from G4RunManager
static G4bool fGeometryHasBeenDestroyed = false
Detailed Description
Definition at line 47 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 47 of file G4WorkerRunManager.hh
Constructor & Destructor Documentation
G4WorkerRunManager::G4WorkerRunManager ()
Definition at line 60 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 60 of file G4WorkerRunManager.cc
References currEvID, eventLoopOnGoing, FatalException, G4Exception(), G4VVisManager::GetConcreteInstance(), CLHEP::Ranlux64Engine::getLuxury(), CLHEP::RanluxEngine::getLuxury(), G4MTRunManager::GetMasterScoringManager(), G4ParticleTable::GetParticleTable(), G4ScoringManager::GetScoringManager(), G4UImanager::GetUIpointer(), luxury, nevModulo, readStatusFromFile, runIsSeeded, G4UImanager::SetIgnoreCmdNotFound(), theEngine, workerContext, and G4ParticleTable::WorkerG4ParticleTable().
G4WorkerRunManager::~G4WorkerRunManager ()
Definition at line 114 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 114 of file G4WorkerRunManager.cc
References G4cout, G4endl, G4RunManager::physicsList, G4VUserPhysicsList::TerminateWorker(), G4RunManager::userActionInitialization, G4RunManager::userDetector, G4RunManager::userWorkerInitialization, G4RunManager::userWorkerThreadInitialization, and G4RunManager::verboseLevel.
Member Function Documentation
void G4WorkerRunManager::ConstructScoringWorlds () protected virtual
Reimplemented from G4RunManager.
Reimplemented in tbbWorkerRunManager.
Definition at line 481 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 481 of file G4WorkerRunManager.cc
References G4ProcessManager::AddProcess(), FatalException, G4RunManager::fGeometryHasBeenDestroyed, G4Exception(), G4VScoringMesh::GeometryHasBeenDestroyed(), G4ParticleTable::GetIterator(), G4MTRunManager::GetMasterScoringManager(), G4ScoringManager::GetMesh(), G4VScoringMesh::GetMeshElementLogical(), G4ScoringManager::GetNumberOfMesh(), G4VScoringMesh::GetParallelWorldProcess(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), G4ScoringManager::GetScoringManagerIfExist(), G4VScoringMesh::GetShape(), G4TransportationManager::GetTransportationManager(), G4ScoringManager::GetWorldName(), idxAlongStep, idxAtRest, idxPostStep, G4ParallelWorldProcess::IsAtRestRequired(), G4TransportationManager::IsWorldExisting(), G4RunManager::kernel, particle, G4ParticleTableIterator< K, V >::reset(), G4VScoringMesh::SetMeshElementLogical(), G4ParallelWorldProcess::SetParallelWorld(), G4VScoringMesh::SetParallelWorldProcess(), G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToSecond(), G4TemplateAutoLock< _Mutex_t >::unlock(), G4ParticleTableIterator< K, V >::value(), G4VScoringMesh::WorkerConstruct(), and G4RunManagerKernel::WorkerUpdateWorldVolume().
Referenced by tbbWorkerRunManager::ConstructScoringWorlds().
void G4WorkerRunManager::DoEventLoop (G4int n_event, const char * macroFile = 0, G4int n_select = -1) virtual
Reimplemented from G4RunManager.
Definition at line 239 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 239 of file G4WorkerRunManager.cc
References currEvID, eventLoopOnGoing, FatalException, G4Exception(), G4RunManager::InitializeEventLoop(), nevModulo, ProcessOneEvent(), G4RunManager::runAborted, runIsSeeded, seedsQueue, TerminateEventLoop(), G4RunManager::TerminateOneEvent(), TIMEMORY_AUTO_TIMER, and G4RunManager::userPrimaryGeneratorAction.
void G4WorkerRunManager::DoWork () virtual
Definition at line 704 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 704 of file G4WorkerRunManager.cc
References G4UImanager::ApplyCommand(), G4RunManager::BeamOn(), d, FatalException, G4Exception(), G4ThreadLocal, G4MTRunManager::GetCommandStack(), G4MTRunManager::GetMasterRunManager(), G4RunManager::GetNumberOfEventsToBeProcessed(), G4RunManager::GetNumberOfSelectEvents(), G4RunManager::GetSelectMacro(), G4UImanager::GetUIpointer(), it, G4MTRunManager::ThisWorkerProcessCommandsStackDone(), G4MTRunManager::ThisWorkerWaitForNextAction(), TIMEMORY_AUTO_TIMER, G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster(), and workerContext.
Referenced by G4MTRunManagerKernel::StartThread().
G4Event * G4WorkerRunManager::GenerateEvent (G4int i_event) virtual
Reimplemented from G4RunManager.
Definition at line 297 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 297 of file G4WorkerRunManager.cc
References G4RunManager::currentRun, currEvID, eventLoopOnGoing, INPUTHEPMC::filename, G4cout, G4endl, G4VUserPrimaryGeneratorAction::GeneratePrimaries(), G4Event::GetEventID(), G4MTRunManager::GetEventModulo(), G4TemplateRNGHelper< T >::GetInstance(), G4MTRunManager::GetMasterRunManager(), G4Run::GetRunID(), G4TemplateRNGHelper< T >::GetSeed(), luxury, nevModulo, G4RunManager::printModulo, G4RunManager::randomNumberStatusForThisEvent, readStatusFromFile, G4RunManager::rngStatusEventsFlag, runIsSeeded, s1, G4MTRunManager::SeedOncePerCommunication(), seedsQueue, G4Event::SetEventID(), G4Event::SetRandomNumberStatus(), G4MTRunManager::SetUpAnEvent(), G4MTRunManager::SetUpNEvents(), G4RunManager::storeRandomNumberStatus, G4RunManager::storeRandomNumberStatusToG4Event, StoreRNGStatus(), TIMEMORY_AUTO_TIMER, and G4RunManager::userPrimaryGeneratorAction.
Referenced by ProcessOneEvent().
G4WorkerRunManager * G4WorkerRunManager::GetWorkerRunManager () static
Definition at line 54 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 54 of file G4WorkerRunManager.cc
References G4RunManager::GetRunManager().
Referenced by GetWorkerRunManagerKernel(), G4RTWorkerInitialization::WorkerRunEnd(), and G4RTWorkerInitialization::WorkerRunStart().
G4WorkerRunManagerKernel * G4WorkerRunManager::GetWorkerRunManagerKernel () static
Definition at line 57 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 57 of file G4WorkerRunManager.cc
References GetWorkerRunManager(), and G4RunManager::kernel.
void G4WorkerRunManager::InitializeGeometry () virtual
Reimplemented from G4RunManager.
Definition at line 132 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 132 of file G4WorkerRunManager.cc
References G4TransportationManager::ClearParallelWorlds(), G4VUserDetectorConstruction::ConstructParallelSD(), G4VUserDetectorConstruction::ConstructSDandField(), FatalException, G4RunManager::fGeometryHasBeenDestroyed, G4Exception(), G4RunManager::geometryInitialized, G4RunManagerKernel::GetCurrentWorld(), G4MTRunManager::GetMasterRunManagerKernel(), G4RunManagerKernel::GetNumberOfParallelWorld(), G4TransportationManager::GetTransportationManager(), G4RunManager::kernel, G4RunManagerKernel::SetNumberOfParallelWorld(), G4RunManager::userDetector, and G4RunManagerKernel::WorkerDefineWorldVolume().
void G4WorkerRunManager::MergePartialResults () protected virtual
Reimplemented in tbbWorkerRunManager.
Definition at line 420 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 420 of file G4WorkerRunManager.cc
References G4RunManager::currentRun, G4MTRunManager::GetMasterRunManager(), G4ScoringManager::GetScoringManagerIfExist(), G4MTRunManager::MergeRun(), and G4MTRunManager::MergeScores().
Referenced by RunTermination().
void G4WorkerRunManager::ProcessOneEvent (G4int i_event) virtual
Reimplemented from G4RunManager.
Definition at line 284 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 284 of file G4WorkerRunManager.cc
References G4RunManager::AnalyzeEvent(), G4UImanager::ApplyCommand(), G4RunManager::currentEvent, eventLoopOnGoing, G4RunManager::eventManager, GenerateEvent(), G4Event::GetEventID(), G4UImanager::GetUIpointer(), G4RunManager::msgText, G4RunManager::n_select_msg, G4EventManager::ProcessOneEvent(), TIMEMORY_AUTO_TIMER, and G4RunManager::UpdateScoring().
Referenced by DoEventLoop().
virtual void G4WorkerRunManager::RestoreRndmEachEvent (G4bool flag) inline virtual
Reimplemented from G4RunManager.
Definition at line 109 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 109 of file G4WorkerRunManager.hh
References readStatusFromFile.
void G4WorkerRunManager::rndmSaveThisEvent () protected virtual
Reimplemented from G4RunManager.
Definition at line 664 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 664 of file G4WorkerRunManager.cc
References G4UImanager::ApplyCommand(), G4RunManager::currentEvent, G4RunManager::currentRun, G4cerr, G4cout, G4endl, G4Event::GetEventID(), G4Run::GetRunID(), G4WorkerThread::GetThreadId(), G4UImanager::GetUIpointer(), G4RunManager::randomNumberStatusDir, G4RunManager::storeRandomNumberStatus, G4RunManager::verboseLevel, and workerContext.
void G4WorkerRunManager::rndmSaveThisRun () protected virtual
Reimplemented from G4RunManager.
Definition at line 632 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 632 of file G4WorkerRunManager.cc
References G4UImanager::ApplyCommand(), G4RunManager::currentRun, G4cerr, G4cout, G4endl, G4Run::GetRunID(), G4WorkerThread::GetThreadId(), G4UImanager::GetUIpointer(), G4RunManager::randomNumberStatusDir, G4RunManager::storeRandomNumberStatus, G4RunManager::verboseLevel, and workerContext.
void G4WorkerRunManager::RunInitialization () virtual
Reimplemented from G4RunManager.
Definition at line 156 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 156 of file G4WorkerRunManager.cc
References G4UserRunAction::BeginOfRunAction(), G4VScoreNtupleWriter::Book(), G4RunManager::CleanUpPreviousEvents(), G4RunManager::currentRun, G4RunManager::DCtable, G4RunManager::fakeRun, G4RunManager::fGeometryHasBeenDestroyed, G4cout, G4endl, G4Threading::G4GetThreadId(), G4UserRunAction::GenerateRun(), G4VVisManager::GetConcreteInstance(), G4SDManager::GetHCtable(), G4ParallelWorldProcessStore::GetInstance(), G4MTRunManager::GetMasterRunManager(), G4Run::GetRunID(), G4SDManager::GetSDMpointerIfExist(), G4RunManager::GetUserWorkerInitialization(), G4VScoreNtupleWriter::Instance(), G4RunManager::isScoreNtupleWriter, G4RunManager::kernel, G4RunManager::n_perviousEventsToBeStored, G4RunManager::numberOfEventProcessed, G4RunManager::numberOfEventToBeProcessed, G4VScoreNtupleWriter::OpenFile(), G4SDManager::PrepareNewEvent(), G4RunManager::previousEvents, G4RunManager::printModulo, G4RunManager::randomNumberStatusForThisRun, G4RunManager::rngStatusEventsFlag, G4RunManager::runAborted, G4RunManager::runIDCounter, G4RunManagerKernel::RunInitialization(), G4Run::SetDCtable(), G4Run::SetHCtable(), G4Run::SetNumberOfEventToBeProcessed(), G4Run::SetRandomNumberStatus(), G4Run::SetRunID(), G4RunManager::storeRandomNumberStatus, StoreRNGStatus(), G4MTRunManager::ThisWorkerReady(), TIMEMORY_AUTO_TIMER, G4ParallelWorldProcessStore::UpdateWorlds(), G4RunManager::userRunAction, G4RunManager::verboseLevel, and G4UserWorkerInitialization::WorkerRunStart().
void G4WorkerRunManager::RunTermination () virtual
Reimplemented from G4RunManager.
Definition at line 429 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 429 of file G4WorkerRunManager.cc
References G4RunManager::fakeRun, G4MTRunManager::GetMasterRunManager(), G4RunManager::GetUserWorkerInitialization(), MergePartialResults(), G4RunManager::RunTermination(), G4MTRunManager::ThisWorkerEndEventLoop(), and G4UserWorkerInitialization::WorkerRunEnd().
void G4WorkerRunManager::SetupDefaultRNGEngine () private
Definition at line 589 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 589 of file G4WorkerRunManager.cc
References G4MTRunManager::getMasterRandomEngine(), G4MTRunManager::GetMasterRunManager(), G4RunManager::GetUserWorkerThreadInitialization(), and G4UserWorkerThreadInitialization::SetupRNGEngine().
void G4WorkerRunManager::SetUserAction (G4UserRunAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 583 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 583 of file G4WorkerRunManager.cc
References G4UserRunAction::SetMaster(), and G4RunManager::SetUserAction().
Referenced by G4RTWorkerInitialization::WorkerRunEnd(), and G4RTWorkerInitialization::WorkerRunStart().
void G4WorkerRunManager::SetUserAction (G4VUserPrimaryGeneratorAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 605 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 605 of file G4WorkerRunManager.cc
References G4RunManager::SetUserAction().
void G4WorkerRunManager::SetUserAction (G4UserEventAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 600 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 600 of file G4WorkerRunManager.cc
References G4RunManager::SetUserAction().
void G4WorkerRunManager::SetUserAction (G4UserStackingAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 610 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 610 of file G4WorkerRunManager.cc
References G4RunManager::SetUserAction().
void G4WorkerRunManager::SetUserAction (G4UserTrackingAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 615 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 615 of file G4WorkerRunManager.cc
References G4RunManager::SetUserAction().
void G4WorkerRunManager::SetUserAction (G4UserSteppingAction * userAction) virtual
Reimplemented from G4RunManager.
Definition at line 620 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 620 of file G4WorkerRunManager.cc
References G4RunManager::SetUserAction().
void G4WorkerRunManager::SetUserInitialization (G4VUserPhysicsList * userInit) virtual
Reimplemented from G4RunManager.
Definition at line 577 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 577 of file G4WorkerRunManager.cc
References G4VUserPhysicsList::InitializeWorker(), and G4RunManager::SetUserInitialization().
Referenced by G4MTRunManagerKernel::StartThread().
void G4WorkerRunManager::SetUserInitialization (G4VUserDetectorConstruction * userInit) virtual
Reimplemented from G4RunManager.
Definition at line 571 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 571 of file G4WorkerRunManager.cc
References FatalException, and G4Exception().
void G4WorkerRunManager::SetUserInitialization (G4VUserActionInitialization * userInit) virtual
Reimplemented from G4RunManager.
Definition at line 565 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 565 of file G4WorkerRunManager.cc
References FatalException, and G4Exception().
void G4WorkerRunManager::SetUserInitialization (G4UserWorkerInitialization * userInit) virtual
Reimplemented from G4RunManager.
Definition at line 553 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 553 of file G4WorkerRunManager.cc
References FatalException, and G4Exception().
void G4WorkerRunManager::SetUserInitialization (G4UserWorkerThreadInitialization * userInit) virtual
Reimplemented from G4RunManager.
Definition at line 559 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 559 of file G4WorkerRunManager.cc
References FatalException, and G4Exception().
void G4WorkerRunManager::SetWorkerThread (G4WorkerThread * wc) inline
Sets the worker context.
Definition at line 81 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 81 of file G4WorkerRunManager.hh
References workerContext.
Referenced by G4MTRunManagerKernel::StartThread().
void G4WorkerRunManager::StoreRNGStatus (const G4String & filenamePrefix) protected virtual
Reimplemented from G4RunManager.
Definition at line 625 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 625 of file G4WorkerRunManager.cc
References G4WorkerThread::GetThreadId(), G4RunManager::randomNumberStatusDir, and workerContext.
Referenced by GenerateEvent(), and RunInitialization().
void G4WorkerRunManager::TerminateEventLoop () virtual
Reimplemented from G4RunManager.
Definition at line 450 of file G4WorkerRunManager.cc.
View newest version in sPHENIX GitHub at line 450 of file G4WorkerRunManager.cc
References G4RunManager::fakeRun, G4cout, G4endl, G4RunManager::numberOfEventProcessed, G4RunManager::runAborted, G4Timer::Stop(), G4RunManager::timer, and G4RunManager::verboseLevel.
Referenced by DoEventLoop().
Member Data Documentation
G4int G4WorkerRunManager::currEvID protected
Definition at line 103 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 103 of file G4WorkerRunManager.hh
Referenced by DoEventLoop(), G4WorkerRunManager(), and GenerateEvent().
G4bool G4WorkerRunManager::eventLoopOnGoing protected
Definition at line 100 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 100 of file G4WorkerRunManager.hh
Referenced by DoEventLoop(), G4WorkerRunManager(), GenerateEvent(), and ProcessOneEvent().
G4int G4WorkerRunManager::luxury protected
Definition at line 104 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4WorkerRunManager.hh
Referenced by G4WorkerRunManager(), and GenerateEvent().
G4int G4WorkerRunManager::nevModulo protected
Definition at line 102 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 102 of file G4WorkerRunManager.hh
Referenced by DoEventLoop(), G4WorkerRunManager(), and GenerateEvent().
G4bool G4WorkerRunManager::readStatusFromFile protected
Definition at line 106 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 106 of file G4WorkerRunManager.hh
Referenced by G4WorkerRunManager(), GenerateEvent(), and RestoreRndmEachEvent().
G4bool G4WorkerRunManager::runIsSeeded protected
Definition at line 101 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 101 of file G4WorkerRunManager.hh
Referenced by DoEventLoop(), G4WorkerRunManager(), and GenerateEvent().
G4SeedsQueue G4WorkerRunManager::seedsQueue protected
Definition at line 105 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 105 of file G4WorkerRunManager.hh
Referenced by DoEventLoop(), and GenerateEvent().
G4WorkerThread* G4WorkerRunManager::workerContext private
Definition at line 83 of file G4WorkerRunManager.hh.
View newest version in sPHENIX GitHub at line 83 of file G4WorkerRunManager.hh
Referenced by DoWork(), G4WorkerRunManager(), rndmSaveThisEvent(), rndmSaveThisRun(), SetWorkerThread(), and StoreRNGStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4WorkerRunManager.hh
geant4/tree/geant4-10.6-release/source/run/src/G4WorkerRunManager.cc