ECCE @ EIC Software: G4HadronPhysicsQGSP_BIC_AllHP Class Reference
G4HadronPhysicsQGSP_BIC_AllHP Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsQGSP_BIC_AllHP.hh>
Classes
struct ThreadPrivate
Public Member Functions
G4HadronPhysicsQGSP_BIC_AllHP (G4int verbose=1)
G4HadronPhysicsQGSP_BIC_AllHP (const G4String &name, G4bool quasiElastic=true)
virtual ~G4HadronPhysicsQGSP_BIC_AllHP ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
void CreateModels ()
Private Attributes
const G4double maxFTFP = G4HadronicParameters::Instance()->GetMaxEnergyTransitionQGS_FTF()
const G4double minFTFP = G4HadronicParameters::Instance()->GetMinEnergyTransitionFTF_Cascade()
const G4double maxBIC = G4HadronicParameters::Instance()->GetMaxEnergyTransitionFTF_Cascade()
const G4double maxBERT = G4HadronicParameters::Instance()->GetMaxEnergyTransitionFTF_Cascade()
const G4double minBIC_neutron = 19.9*CLHEP::MeV
const G4double maxHP_neutron = 20.0*CLHEP::MeV
const G4double minBIC_proton = 199.0*CLHEP::MeV
const G4double maxHP_proton = 200.0*CLHEP::MeV
Static Private Attributes
static G4ThreadLocal
ThreadPrivate * tpdata = nullptr
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 64 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 64 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Constructor & Destructor Documentation
G4HadronPhysicsQGSP_BIC_AllHP::G4HadronPhysicsQGSP_BIC_AllHP (G4int verbose = 1)
Definition at line 62 of file G4HadronPhysicsQGSP_BIC_AllHP.cc.
View newest version in sPHENIX GitHub at line 62 of file G4HadronPhysicsQGSP_BIC_AllHP.cc
G4HadronPhysicsQGSP_BIC_AllHP::G4HadronPhysicsQGSP_BIC_AllHP (const G4String & name, G4bool quasiElastic = true)
Definition at line 66 of file G4HadronPhysicsQGSP_BIC_AllHP.cc.
View newest version in sPHENIX GitHub at line 66 of file G4HadronPhysicsQGSP_BIC_AllHP.cc
G4HadronPhysicsQGSP_BIC_AllHP::~G4HadronPhysicsQGSP_BIC_AllHP () virtual
Definition at line 110 of file G4HadronPhysicsQGSP_BIC_AllHP.cc.
View newest version in sPHENIX GitHub at line 110 of file G4HadronPhysicsQGSP_BIC_AllHP.cc
References G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theAntiBaryon, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theBertiniPiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theBinaryNeutron, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theBinaryPro, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theFTFPAntiBaryon, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theFTFPNeutron, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theFTFPPiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theFTFPPro, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theHyperon, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePHPNeutron, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePHPProton, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePro, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theQGSPNeutron, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theQGSPPiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theQGSPPro, and tpdata.
Member Function Documentation
void G4HadronPhysicsQGSP_BIC_AllHP::ConstructParticle (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 134 of file G4HadronPhysicsQGSP_BIC_AllHP.cc.
View newest version in sPHENIX GitHub at line 134 of file G4HadronPhysicsQGSP_BIC_AllHP.cc
References G4MesonConstructor::ConstructParticle(), G4IonConstructor::ConstructParticle(), G4BaryonConstructor::ConstructParticle(), and G4ShortLivedConstructor::ConstructParticle().
void G4HadronPhysicsQGSP_BIC_AllHP::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 150 of file G4HadronPhysicsQGSP_BIC_AllHP.cc.
View newest version in sPHENIX GitHub at line 150 of file G4HadronPhysicsQGSP_BIC_AllHP.cc
References G4AntiBarionBuilder::Build(), G4PiKBuilder::Build(), G4ProtonBuilder::Build(), G4NeutronBuilder::Build(), G4HyperonFTFPBuilder::Build(), CreateModels(), G4PhysListUtil::FindCaptureProcess(), G4PhysListUtil::FindFissionProcess(), G4HadronicParameters::Instance(), minBIC_neutron, G4InuclParticleNames::neutron, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theAntiBaryon, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theHyperon, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theNeutrons, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePro, and tpdata.
void G4HadronPhysicsQGSP_BIC_AllHP::CreateModels () private
Definition at line 70 of file G4HadronPhysicsQGSP_BIC_AllHP.cc.
View newest version in sPHENIX GitHub at line 70 of file G4HadronPhysicsQGSP_BIC_AllHP.cc
References maxBERT, maxBIC, maxFTFP, maxHP_neutron, maxHP_proton, minBIC_neutron, minBIC_proton, minFTFP, G4AntiBarionBuilder::RegisterMe(), G4PiKBuilder::RegisterMe(), G4ProtonBuilder::RegisterMe(), G4NeutronBuilder::RegisterMe(), G4ProtonPHPBuilder::SetMaxEnergy(), G4BinaryProtonBuilder::SetMaxEnergy(), G4BinaryNeutronBuilder::SetMaxEnergy(), G4BertiniPiKBuilder::SetMaxEnergy(), G4FTFPProtonBuilder::SetMaxEnergy(), G4NeutronPHPBuilder::SetMaxEnergy(), G4FTFPNeutronBuilder::SetMaxEnergy(), G4FTFPPiKBuilder::SetMaxEnergy(), G4BinaryProtonBuilder::SetMinEnergy(), G4BinaryNeutronBuilder::SetMinEnergy(), G4FTFPProtonBuilder::SetMinEnergy(), G4FTFPNeutronBuilder::SetMinEnergy(), G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theAntiBaryon, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theBertiniPiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theBinaryNeutron, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theBinaryPro, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theFTFPAntiBaryon, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theFTFPNeutron, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theFTFPPiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theFTFPPro, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theHyperon, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theNeutrons, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePHPNeutron, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePHPProton, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::thePro, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theQGSPNeutron, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theQGSPPiK, G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate::theQGSPPro, and tpdata.
Referenced by ConstructProcess().
Member Data Documentation
const G4double G4HadronPhysicsQGSP_BIC_AllHP::maxBERT = G4HadronicParameters::Instance()->GetMaxEnergyTransitionFTF_Cascade() private
Definition at line 80 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 80 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by CreateModels().
const G4double G4HadronPhysicsQGSP_BIC_AllHP::maxBIC = G4HadronicParameters::Instance()->GetMaxEnergyTransitionFTF_Cascade() private
Definition at line 79 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 79 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by CreateModels().
const G4double G4HadronPhysicsQGSP_BIC_AllHP::maxFTFP = G4HadronicParameters::Instance()->GetMaxEnergyTransitionQGS_FTF() private
Definition at line 77 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by CreateModels().
const G4double G4HadronPhysicsQGSP_BIC_AllHP::maxHP_neutron = 20.0*CLHEP::MeV private
Definition at line 82 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 82 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by CreateModels().
const G4double G4HadronPhysicsQGSP_BIC_AllHP::maxHP_proton = 200.0*CLHEP::MeV private
Definition at line 84 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by CreateModels().
const G4double G4HadronPhysicsQGSP_BIC_AllHP::minBIC_neutron = 19.9*CLHEP::MeV private
Definition at line 81 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by ConstructProcess(), and CreateModels().
const G4double G4HadronPhysicsQGSP_BIC_AllHP::minBIC_proton = 199.0*CLHEP::MeV private
Definition at line 83 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 83 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by CreateModels().
const G4double G4HadronPhysicsQGSP_BIC_AllHP::minFTFP = G4HadronicParameters::Instance()->GetMinEnergyTransitionFTF_Cascade() private
Definition at line 78 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by CreateModels().
G4ThreadLocal G4HadronPhysicsQGSP_BIC_AllHP::ThreadPrivate * G4HadronPhysicsQGSP_BIC_AllHP::tpdata = nullptr static private
Definition at line 109 of file G4HadronPhysicsQGSP_BIC_AllHP.hh.
View newest version in sPHENIX GitHub at line 109 of file G4HadronPhysicsQGSP_BIC_AllHP.hh
Referenced by ConstructProcess(), CreateModels(), and ~G4HadronPhysicsQGSP_BIC_AllHP().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsQGSP_BIC_AllHP.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsQGSP_BIC_AllHP.cc