ECCE @ EIC Software: OpNoviceStackingAction Class Reference
OpNoviceStackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/include/OpNoviceStackingAction.hh>
Public Member Functions
OpNoviceStackingAction ()
virtual ~OpNoviceStackingAction ()
virtual G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
virtual void NewStage ()
virtual void PrepareNewEvent ()
Public Member Functions inherited from G4UserStackingAction
G4UserStackingAction ()
virtual ~G4UserStackingAction ()
void SetStackManager (G4StackManager *value)
Private Attributes
G4int fScintillationCounter
G4int fCerenkovCounter
Additional Inherited Members
Protected Attributes inherited from G4UserStackingAction
G4StackManager * stackManager
Detailed Description
Definition at line 41 of file OpNoviceStackingAction.hh.
View newest version in sPHENIX GitHub at line 41 of file OpNoviceStackingAction.hh
Constructor & Destructor Documentation
OpNoviceStackingAction::OpNoviceStackingAction ()
Definition at line 44 of file OpNoviceStackingAction.cc.
View newest version in sPHENIX GitHub at line 44 of file OpNoviceStackingAction.cc
OpNoviceStackingAction::~OpNoviceStackingAction () virtual
Definition at line 51 of file OpNoviceStackingAction.cc.
View newest version in sPHENIX GitHub at line 51 of file OpNoviceStackingAction.cc
Member Function Documentation
G4ClassificationOfNewTrack OpNoviceStackingAction::ClassifyNewTrack (const G4Track * aTrack) virtual
Reimplemented from G4UserStackingAction.
Definition at line 57 of file OpNoviceStackingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file OpNoviceStackingAction.cc
References fCerenkovCounter, fScintillationCounter, fUrgent, G4Track::GetCreatorProcess(), G4Track::GetDefinition(), G4Track::GetParentID(), G4VProcess::GetProcessName(), and G4OpticalPhoton::OpticalPhotonDefinition().
void OpNoviceStackingAction::NewStage () virtual
Reimplemented from G4UserStackingAction.
Definition at line 74 of file OpNoviceStackingAction.cc.
View newest version in sPHENIX GitHub at line 74 of file OpNoviceStackingAction.cc
References fCerenkovCounter, fScintillationCounter, G4cout, and G4endl.
void OpNoviceStackingAction::PrepareNewEvent () virtual
Reimplemented from G4UserStackingAction.
Definition at line 84 of file OpNoviceStackingAction.cc.
View newest version in sPHENIX GitHub at line 84 of file OpNoviceStackingAction.cc
References fCerenkovCounter, and fScintillationCounter.
Member Data Documentation
G4int OpNoviceStackingAction::fCerenkovCounter private
Definition at line 54 of file OpNoviceStackingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file OpNoviceStackingAction.hh
Referenced by ClassifyNewTrack(), NewStage(), and PrepareNewEvent().
G4int OpNoviceStackingAction::fScintillationCounter private
Definition at line 53 of file OpNoviceStackingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file OpNoviceStackingAction.hh
Referenced by ClassifyNewTrack(), NewStage(), and PrepareNewEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/include/OpNoviceStackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice/src/OpNoviceStackingAction.cc