ECCE @ EIC Software: pyglobals Namespace Reference
pyglobals Namespace Reference
Typedefs
typedef std::vector< G4int > G4intVector
typedef std::vector< G4double > G4doubleVector
typedef std::vector< G4String > G4StringVector
typedef std::vector
< G4ThreeVector > G4ThreeVectorVector
typedef std::vector< G4TwoVector > G4TwoVectorVector
Functions
void SetG4PyCoutDestination ()
void ResetG4PyCoutDestination ()
Typedef Documentation
typedef std::vector<G4double> pyglobals::G4doubleVector
Definition at line 64 of file pyglobals.cc.
View newest version in sPHENIX GitHub at line 64 of file pyglobals.cc
typedef std::vector<G4int> pyglobals::G4intVector
Definition at line 63 of file pyglobals.cc.
View newest version in sPHENIX GitHub at line 63 of file pyglobals.cc
typedef std::vector<G4String> pyglobals::G4StringVector
Definition at line 65 of file pyglobals.cc.
View newest version in sPHENIX GitHub at line 65 of file pyglobals.cc
typedef std::vector<G4ThreeVector> pyglobals::G4ThreeVectorVector
Definition at line 66 of file pyglobals.cc.
View newest version in sPHENIX GitHub at line 66 of file pyglobals.cc
typedef std::vector<G4TwoVector> pyglobals::G4TwoVectorVector
Definition at line 67 of file pyglobals.cc.
View newest version in sPHENIX GitHub at line 67 of file pyglobals.cc
Function Documentation
void pyglobals::ResetG4PyCoutDestination ()
Definition at line 57 of file pyglobals.cc.
View newest version in sPHENIX GitHub at line 57 of file pyglobals.cc
References G4UImanager::GetUIpointer().
Referenced by export_globals().
void pyglobals::SetG4PyCoutDestination ()
Definition at line 49 of file pyglobals.cc.
View newest version in sPHENIX GitHub at line 49 of file pyglobals.cc
References G4cerrbuf, G4coutbuf, G4UImanager::GetUIpointer(), and G4strstreambuf::SetDestination().
Referenced by export_globals(), emcalc_gui::main(), and source::print_version().