ECCE @ EIC Software: B5DetectorConstruction Class Reference
B5DetectorConstruction Class Reference
Detector construction.
#include <geant4/tree/geant4-10.6-release/examples/basic/B5/include/B5DetectorConstruction.hh>
Public Member Functions
B5DetectorConstruction ()
virtual ~B5DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
void SetArmAngle (G4double val)
G4double GetArmAngle ()
void ConstructMaterials ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineCommands ()
Private Attributes
G4GenericMessenger * fMessenger
G4LogicalVolume * fHodoscope1Logical
G4LogicalVolume * fHodoscope2Logical
G4LogicalVolume * fWirePlane1Logical
G4LogicalVolume * fWirePlane2Logical
G4LogicalVolume * fCellLogical
G4LogicalVolume * fHadCalScintiLogical
G4LogicalVolume * fMagneticLogical
std::vector< G4VisAttributes * > fVisAttributes
G4double fArmAngle
G4RotationMatrix * fArmRotation
G4VPhysicalVolume * fSecondArmPhys
Static Private Attributes
static G4ThreadLocal
B5MagneticField * fMagneticField = 0
static G4ThreadLocal
G4FieldManager * fFieldMgr = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Detector construction.
Definition at line 50 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 50 of file B5DetectorConstruction.hh
Constructor & Destructor Documentation
B5DetectorConstruction::B5DetectorConstruction ()
Definition at line 75 of file B5DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 75 of file B5DetectorConstruction.cc
References DefineCommands(), fArmAngle, fArmRotation, and CLHEP::HepRotation::rotateY().
B5DetectorConstruction::~B5DetectorConstruction () virtual
Definition at line 95 of file B5DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 95 of file B5DetectorConstruction.cc
References fArmRotation, fMessenger, and fVisAttributes.
Member Function Documentation
G4VPhysicalVolume * B5DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 107 of file B5DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 107 of file B5DetectorConstruction.cc
References cm, ConstructMaterials(), deg, fArmAngle, fArmRotation, fCellLogical, fHadCalScintiLogical, fHodoscope1Logical, fHodoscope2Logical, fMagneticLogical, fSecondArmPhys, fVisAttributes, fWirePlane1Logical, fWirePlane2Logical, G4Material::GetMaterial(), kNofChambers, kNofEmCells, kNofHadCells, kNofHadColumns, kNofHadRows, kNofHodoscopes1, kNofHodoscopes2, kXAxis, kYAxis, kZAxis, m, mm, CLHEP::HepRotation::rotateX(), G4LogicalVolume::SetUserLimits(), G4LogicalVolume::SetVisAttributes(), x, x1, x2, z, z1, and z2.
void B5DetectorConstruction::ConstructMaterials ()
Definition at line 406 of file B5DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 406 of file B5DetectorConstruction.cc
References G4cout, G4endl, G4Material::GetMaterialTable(), and G4NistManager::Instance().
Referenced by Construct().
void B5DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 365 of file B5DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 365 of file B5DetectorConstruction.cc
References G4FieldManager::CreateChordFinder(), fCellLogical, fFieldMgr, fHadCalScintiLogical, fHodoscope1Logical, fHodoscope2Logical, fMagneticField, fMagneticLogical, fWirePlane1Logical, fWirePlane2Logical, G4SDManager::GetSDMpointer(), G4FieldManager::SetDetectorField(), G4LogicalVolume::SetFieldManager(), and G4LogicalVolume::SetSensitiveDetector().
void B5DetectorConstruction::DefineCommands () private
Definition at line 465 of file B5DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 465 of file B5DetectorConstruction.cc
References G4GenericMessenger::DeclareMethodWithUnit(), fMessenger, SetArmAngle(), G4GenericMessenger::Command::SetDefaultValue(), G4GenericMessenger::Command::SetParameterName(), and G4GenericMessenger::Command::SetRange().
Referenced by B5DetectorConstruction().
G4double B5DetectorConstruction::GetArmAngle () inline
Definition at line 60 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 60 of file B5DetectorConstruction.hh
References fArmAngle.
void B5DetectorConstruction::SetArmAngle (G4double val)
Definition at line 445 of file B5DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 445 of file B5DetectorConstruction.cc
References fArmAngle, fArmRotation, fSecondArmPhys, G4cerr, G4endl, G4RunManager::GeometryHasBeenModified(), G4RunManager::GetRunManager(), m, CLHEP::HepRotation::rotateY(), G4VPhysicalVolume::SetTranslation(), x, and z.
Referenced by DefineCommands().
Member Data Documentation
G4double B5DetectorConstruction::fArmAngle private
Definition at line 82 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file B5DetectorConstruction.hh
Referenced by B5DetectorConstruction(), Construct(), GetArmAngle(), and SetArmAngle().
G4RotationMatrix* B5DetectorConstruction::fArmRotation private
Definition at line 83 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 83 of file B5DetectorConstruction.hh
Referenced by B5DetectorConstruction(), Construct(), SetArmAngle(), and ~B5DetectorConstruction().
G4LogicalVolume* B5DetectorConstruction::fCellLogical private
Definition at line 76 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file B5DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4ThreadLocal G4FieldManager * B5DetectorConstruction::fFieldMgr = 0 static private
Definition at line 70 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 70 of file B5DetectorConstruction.hh
Referenced by ConstructSDandField().
G4LogicalVolume* B5DetectorConstruction::fHadCalScintiLogical private
Definition at line 77 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 77 of file B5DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4LogicalVolume* B5DetectorConstruction::fHodoscope1Logical private
Definition at line 72 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 72 of file B5DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4LogicalVolume* B5DetectorConstruction::fHodoscope2Logical private
Definition at line 73 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file B5DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4ThreadLocal B5MagneticField * B5DetectorConstruction::fMagneticField = 0 static private
Definition at line 69 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 69 of file B5DetectorConstruction.hh
Referenced by ConstructSDandField().
G4LogicalVolume* B5DetectorConstruction::fMagneticLogical private
Definition at line 78 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 78 of file B5DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4GenericMessenger* B5DetectorConstruction::fMessenger private
Definition at line 67 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 67 of file B5DetectorConstruction.hh
Referenced by DefineCommands(), and ~B5DetectorConstruction().
G4VPhysicalVolume* B5DetectorConstruction::fSecondArmPhys private
Definition at line 84 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file B5DetectorConstruction.hh
Referenced by Construct(), and SetArmAngle().
std::vector<G4VisAttributes*> B5DetectorConstruction::fVisAttributes private
Definition at line 80 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file B5DetectorConstruction.hh
Referenced by Construct(), and ~B5DetectorConstruction().
G4LogicalVolume* B5DetectorConstruction::fWirePlane1Logical private
Definition at line 74 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 74 of file B5DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4LogicalVolume* B5DetectorConstruction::fWirePlane2Logical private
Definition at line 75 of file B5DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 75 of file B5DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B5/include/B5DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/basic/B5/src/B5DetectorConstruction.cc