ECCE @ EIC Software: G4SmartVoxelStat Class Reference
G4SmartVoxelStat Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4SmartVoxelStat.hh>
Public Member Functions
G4SmartVoxelStat (const G4LogicalVolume *theVolume, const G4SmartVoxelHeader *theVoxel, G4double theSysTime, G4double theUserTime)
const G4LogicalVolume * GetVolume () const
const G4SmartVoxelHeader * GetVoxel () const
G4double GetSysTime () const
G4double GetUserTime () const
G4double GetTotalTime () const
G4long GetNumberHeads () const
G4long GetNumberNodes () const
G4long GetNumberPointers () const
G4long GetMemoryUse () const
Protected Member Functions
void CountHeadsAndNodes (const G4SmartVoxelHeader *head)
Protected Attributes
const G4LogicalVolume * volume
const G4SmartVoxelHeader * voxel
G4double sysTime
G4double userTime
G4long heads = 1
G4long nodes = 0
G4long pointers = 0
Detailed Description
Definition at line 43 of file G4SmartVoxelStat.hh.
View newest version in sPHENIX GitHub at line 43 of file G4SmartVoxelStat.hh
Constructor & Destructor Documentation
G4SmartVoxelStat::G4SmartVoxelStat (const G4LogicalVolume * theVolume, const G4SmartVoxelHeader * theVoxel, G4double theSysTime, G4double theUserTime)
Definition at line 42 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 42 of file G4SmartVoxelStat.cc
References CountHeadsAndNodes(), and voxel.
Member Function Documentation
void G4SmartVoxelStat::CountHeadsAndNodes (const G4SmartVoxelHeader * head) protected
Definition at line 119 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 119 of file G4SmartVoxelStat.cc
References G4SmartVoxelProxy::GetHeader(), G4SmartVoxelHeader::GetNoSlices(), G4SmartVoxelHeader::GetSlice(), heads, G4SmartVoxelProxy::IsNode(), nodes, and pointers.
Referenced by G4SmartVoxelStat().
G4long G4SmartVoxelStat::GetMemoryUse () const
Definition at line 100 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 100 of file G4SmartVoxelStat.cc
References heads, nodes, and pointers.
Referenced by G4GeometryManager::ReportVoxelStats().
G4long G4SmartVoxelStat::GetNumberHeads () const
Definition at line 82 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 82 of file G4SmartVoxelStat.cc
References heads.
G4long G4SmartVoxelStat::GetNumberNodes () const
Definition at line 87 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 87 of file G4SmartVoxelStat.cc
References nodes.
G4long G4SmartVoxelStat::GetNumberPointers () const
Definition at line 92 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 92 of file G4SmartVoxelStat.cc
References pointers.
G4double G4SmartVoxelStat::GetSysTime () const
Definition at line 67 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 67 of file G4SmartVoxelStat.cc
References sysTime.
G4double G4SmartVoxelStat::GetTotalTime () const
Definition at line 77 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 77 of file G4SmartVoxelStat.cc
References sysTime, and userTime.
Referenced by G4GeometryManager::ReportVoxelStats().
G4double G4SmartVoxelStat::GetUserTime () const
Definition at line 72 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 72 of file G4SmartVoxelStat.cc
References userTime.
const G4LogicalVolume * G4SmartVoxelStat::GetVolume () const
Definition at line 57 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 57 of file G4SmartVoxelStat.cc
References volume.
const G4SmartVoxelHeader * G4SmartVoxelStat::GetVoxel () const
Definition at line 62 of file G4SmartVoxelStat.cc.
View newest version in sPHENIX GitHub at line 62 of file G4SmartVoxelStat.cc
References voxel.
Member Data Documentation
G4long G4SmartVoxelStat::heads = 1 protected
Definition at line 91 of file G4SmartVoxelStat.hh.
View newest version in sPHENIX GitHub at line 91 of file G4SmartVoxelStat.hh
Referenced by CountHeadsAndNodes(), GetMemoryUse(), and GetNumberHeads().
G4long G4SmartVoxelStat::nodes = 0 protected
Definition at line 92 of file G4SmartVoxelStat.hh.
View newest version in sPHENIX GitHub at line 92 of file G4SmartVoxelStat.hh
Referenced by CountHeadsAndNodes(), GetMemoryUse(), and GetNumberNodes().
G4long G4SmartVoxelStat::pointers = 0 protected
Definition at line 93 of file G4SmartVoxelStat.hh.
View newest version in sPHENIX GitHub at line 93 of file G4SmartVoxelStat.hh
Referenced by CountHeadsAndNodes(), GetMemoryUse(), and GetNumberPointers().
G4double G4SmartVoxelStat::sysTime protected
Definition at line 88 of file G4SmartVoxelStat.hh.
View newest version in sPHENIX GitHub at line 88 of file G4SmartVoxelStat.hh
Referenced by GetSysTime(), and GetTotalTime().
G4double G4SmartVoxelStat::userTime protected
Definition at line 89 of file G4SmartVoxelStat.hh.
View newest version in sPHENIX GitHub at line 89 of file G4SmartVoxelStat.hh
Referenced by GetTotalTime(), and GetUserTime().
const G4LogicalVolume* G4SmartVoxelStat::volume protected
Definition at line 85 of file G4SmartVoxelStat.hh.
View newest version in sPHENIX GitHub at line 85 of file G4SmartVoxelStat.hh
Referenced by GetVolume().
const G4SmartVoxelHeader* G4SmartVoxelStat::voxel protected
Definition at line 86 of file G4SmartVoxelStat.hh.
View newest version in sPHENIX GitHub at line 86 of file G4SmartVoxelStat.hh
Referenced by G4SmartVoxelStat(), and GetVoxel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4SmartVoxelStat.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4SmartVoxelStat.cc