ECCE @ EIC Software: G4ShellCorrection Class Reference
G4ShellCorrection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/include/G4ShellCorrection.hh>
Public Member Functions
G4ShellCorrection ()
~G4ShellCorrection ()
const
G4CameronTruranHilfShellCorrections * GetCameronTruranHilfShellCorrections () const
const
G4CameronShellPlusPairingCorrections * GetCameronShellPlusPairingCorrections () const
G4double GetShellCorrection (G4int A, G4int Z) const
Private Attributes
G4CookShellCorrections theCookShellCorrections
G4CameronGilbertShellCorrections theCameronGilbertShellCorrections
G4CameronTruranHilfShellCorrections theCameronTruranHilfShellCorrections
G4CameronShellPlusPairingCorrections theCameronShellPlusPairingCorrections
Detailed Description
Definition at line 42 of file G4ShellCorrection.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ShellCorrection.hh
Constructor & Destructor Documentation
G4ShellCorrection::G4ShellCorrection () explicit
Definition at line 35 of file G4ShellCorrection.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ShellCorrection.cc
G4ShellCorrection::~G4ShellCorrection ()
Definition at line 38 of file G4ShellCorrection.cc.
View newest version in sPHENIX GitHub at line 38 of file G4ShellCorrection.cc
Member Function Documentation
const G4CameronShellPlusPairingCorrections * G4ShellCorrection::GetCameronShellPlusPairingCorrections () const
Definition at line 48 of file G4ShellCorrection.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ShellCorrection.cc
References theCameronShellPlusPairingCorrections.
Referenced by G4FissionBarrier::G4FissionBarrier().
const G4CameronTruranHilfShellCorrections * G4ShellCorrection::GetCameronTruranHilfShellCorrections () const
Definition at line 42 of file G4ShellCorrection.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ShellCorrection.cc
References theCameronTruranHilfShellCorrections.
G4double G4ShellCorrection::GetShellCorrection (G4int A, G4int Z) const
Definition at line 53 of file G4ShellCorrection.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ShellCorrection.cc
References G4CookShellCorrections::GetShellCorrection(), G4CameronGilbertShellCorrections::GetShellCorrection(), N, theCameronGilbertShellCorrections, theCookShellCorrections, and Z.
Member Data Documentation
G4CameronGilbertShellCorrections G4ShellCorrection::theCameronGilbertShellCorrections private
Definition at line 61 of file G4ShellCorrection.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ShellCorrection.hh
Referenced by GetShellCorrection().
G4CameronShellPlusPairingCorrections G4ShellCorrection::theCameronShellPlusPairingCorrections private
Definition at line 63 of file G4ShellCorrection.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ShellCorrection.hh
Referenced by GetCameronShellPlusPairingCorrections().
G4CameronTruranHilfShellCorrections G4ShellCorrection::theCameronTruranHilfShellCorrections private
Definition at line 62 of file G4ShellCorrection.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ShellCorrection.hh
Referenced by GetCameronTruranHilfShellCorrections().
G4CookShellCorrections G4ShellCorrection::theCookShellCorrections private
Definition at line 60 of file G4ShellCorrection.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ShellCorrection.hh
Referenced by GetShellCorrection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/include/G4ShellCorrection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/src/G4ShellCorrection.cc