ECCE @ EIC Software: CCalSensAssign Class Reference
CCalSensAssign Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSensAssign.hh>
Public Member Functions
~CCalSensAssign ()
G4bool assign ()
G4bool stackingAction ()
G4bool addCaloSD (G4String name, CCalVOrganization *numberingScheme)
Static Public Member Functions
static CCalSensAssign * getInstance ()
Private Member Functions
CCalSensAssign ()
Private Attributes
std::map< G4String,
G4VSensitiveDetector * > sens_
Static Private Attributes
static CCalSensAssign * theInstance = 0
Detailed Description
Definition at line 40 of file CCalSensAssign.hh.
View newest version in sPHENIX GitHub at line 40 of file CCalSensAssign.hh
Constructor & Destructor Documentation
CCalSensAssign::~CCalSensAssign () inline
Definition at line 43 of file CCalSensAssign.hh.
View newest version in sPHENIX GitHub at line 43 of file CCalSensAssign.hh
CCalSensAssign::CCalSensAssign () private
Definition at line 49 of file CCalSensAssign.cc.
View newest version in sPHENIX GitHub at line 49 of file CCalSensAssign.cc
Referenced by getInstance().
Member Function Documentation
G4bool CCalSensAssign::addCaloSD (G4String name, CCalVOrganization * numberingScheme)
Definition at line 88 of file CCalSensAssign.cc.
View newest version in sPHENIX GitHub at line 88 of file CCalSensAssign.cc
References sens_.
G4bool CCalSensAssign::assign ()
Definition at line 52 of file CCalSensAssign.cc.
View newest version in sPHENIX GitHub at line 52 of file CCalSensAssign.cc
References G4SDManager::AddNewDetector(), G4String::first(), G4cout, G4endl, CCalSensitiveDetectors::getInstance(), G4VSensitiveDetector::GetName(), G4SDManager::GetSDMpointer(), sens_, and CCalSensitiveDetectors::setSensitive().
Referenced by CCalDetectorConstruction::Construct().
CCalSensAssign * CCalSensAssign::getInstance () static
Definition at line 43 of file CCalSensAssign.cc.
View newest version in sPHENIX GitHub at line 43 of file CCalSensAssign.cc
References CCalSensAssign(), and theInstance.
Referenced by CCalDetectorConstruction::Construct().
G4bool CCalSensAssign::stackingAction ()
Definition at line 72 of file CCalSensAssign.cc.
View newest version in sPHENIX GitHub at line 72 of file CCalSensAssign.cc
References G4cout, G4endl, G4RunManager::GetRunManager(), and G4RunManager::SetUserAction().
Referenced by CCalDetectorConstruction::Construct().
Member Data Documentation
std::map<G4String,G4VSensitiveDetector*> CCalSensAssign::sens_ private
Definition at line 53 of file CCalSensAssign.hh.
View newest version in sPHENIX GitHub at line 53 of file CCalSensAssign.hh
Referenced by addCaloSD(), and assign().
CCalSensAssign * CCalSensAssign::theInstance = 0 static private
Definition at line 52 of file CCalSensAssign.hh.
View newest version in sPHENIX GitHub at line 52 of file CCalSensAssign.hh
Referenced by getInstance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSensAssign.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalSensAssign.cc