ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/extended/errorpropagation/errprop.cc File Reference
errprop.cc File Reference
Main program of the errorpropagation example.
#include "ExErrorDetectorConstruction.hh"
#include "G4SteppingVerbose.hh"
#include "G4ErrorPropagator.hh"
#include "G4ErrorPropagatorData.hh"
#include "G4ErrorPropagatorManager.hh"
#include "G4ErrorPlaneSurfaceTarget.hh"
#include "G4ErrorCylSurfaceTarget.hh"
#include "G4ErrorGeomVolumeTarget.hh"
#include "G4ErrorTrackLengthTarget.hh"
#include "G4ErrorFreeTrajState.hh"
#include "G4UImanager.hh"
#include "G4SystemOfUnits.hh"
Functions
void Initialize ()
G4ErrorTarget * BuildTarget (G4int iTarget)
void ProcessEvent (G4int iProp, size_t nEv)
void Finalize ()
int main ()
Variables
G4ErrorTarget * theTarget
G4ErrorMode theG4ErrorMode
Detailed Description
Main program of the errorpropagation example.
Definition in file errprop.cc.
Function Documentation
G4ErrorTarget * BuildTarget (G4int iTarget)
Definition at line 232 of file errprop.cc.
View newest version in sPHENIX GitHub at line 232 of file errprop.cc
References cm, FatalErrorInArgument, G4Exception(), and radius.
Referenced by Initialize().
void Finalize ()
Definition at line 256 of file errprop.cc.
View newest version in sPHENIX GitHub at line 256 of file errprop.cc
References G4ErrorPropagatorManager::CloseGeometry(), and G4ErrorPropagatorManager::GetErrorPropagatorManager().
Referenced by main(), G4MPImanager::ParseArguments(), and G4MPImanager::~G4MPImanager().
void Initialize ()
Definition at line 100 of file errprop.cc.
View newest version in sPHENIX GitHub at line 100 of file errprop.cc
References G4UImanager::ApplyCommand(), BuildTarget(), FatalErrorInArgument, G4ErrorMode_PropBackwards, G4ErrorMode_PropForwards, G4Exception(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4ErrorPropagatorManager::GetErrorPropagatorManager(), G4UImanager::GetUIpointer(), G4ErrorPropagatorManager::InitGeant4e(), JustWarning, G4VSteppingVerbose::SetInstance(), G4ErrorPropagatorData::SetTarget(), G4ErrorPropagatorManager::SetUserInitialization(), and theG4ErrorMode.
Referenced by PHG4GDMLUtility::Dump_G4_GDML(), PHG4GDMLUtility::Dump_GDML(), G4GDMLParser::G4GDMLParser(), main(), HepMCG4AsciiReaderMessenger::SetNewValue(), HadrontherapyDetectorConstruction::UpdateGeometry(), and visio().
int main ()
Definition at line 62 of file errprop.cc.
View newest version in sPHENIX GitHub at line 62 of file errprop.cc
References FatalErrorInArgument, Finalize(), G4Exception(), Initialize(), JustWarning, nEvents, and ProcessEvent().
void ProcessEvent (G4int iProp, size_t nEv)
Definition at line 171 of file errprop.cc.
View newest version in sPHENIX GitHub at line 171 of file errprop.cc
References G4ErrorPropagator::CheckIfLastStep(), cm, error, G4cout, G4endl, G4ErrorTrajState::GetError(), G4ErrorPropagatorManager::GetErrorPropagatorManager(), G4ErrorTrajState::GetG4Track(), G4ErrorTrajState::GetMomentum(), G4ErrorTrajState::GetPosition(), G4ErrorPropagatorManager::GetPropagator(), GeV, G4ErrorPropagatorManager::InitTrackPropagation(), G4ErrorPropagator::InvokePostUserTrackingAction(), G4ErrorPropagatorManager::Propagate(), G4ErrorPropagatorManager::PropagateOneStep(), theG4ErrorMode, and TRUE.
Referenced by main().
Variable Documentation
G4ErrorMode theG4ErrorMode
Definition at line 59 of file errprop.cc.
View newest version in sPHENIX GitHub at line 59 of file errprop.cc
Referenced by Initialize(), and ProcessEvent().
G4ErrorTarget* theTarget
Definition at line 58 of file errprop.cc.
View newest version in sPHENIX GitHub at line 58 of file errprop.cc
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::CompositeApply(), and G4Nucleus::GetThermalNucleus().