ECCE @ EIC Software: G4Fragment Class Reference
G4Fragment Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4Fragment.hh>
Public Member Functions
G4Fragment ()
~G4Fragment ()
G4Fragment (const G4Fragment &right)
G4Fragment (G4int A, G4int Z, const G4LorentzVector &aMomentum)
G4Fragment (const G4LorentzVector &aMomentum, const G4ParticleDefinition *aParticleDefinition)
G4Fragment & operator= (const G4Fragment &right)
G4bool operator== (const G4Fragment &right) const
G4bool operator!= (const G4Fragment &right) const
void * operator new (size_t)
void operator delete (void *aFragment)
G4int GetZ_asInt () const
G4int GetA_asInt () const
void SetZandA_asInt (G4int Znew, G4int Anew)
G4double GetExcitationEnergy () const
void SetExcEnergyAndMomentum (G4double eexc, const G4LorentzVector &)
G4double GetGroundStateMass () const
G4double GetBindingEnergy () const
const G4LorentzVector & GetMomentum () const
void SetMomentum (const G4LorentzVector &value)
G4double ComputeGroundStateMass (G4int Z, G4int A) const
G4double GetSpin () const
void SetSpin (G4double value)
G4int GetCreatorModelType () const
void SetCreatorModelType (G4int value)
G4double GetZ () const
G4double GetA () const
void SetZ (G4double value)
void SetA (G4double value)
G4int GetNumberOfExcitons () const
G4int GetNumberOfParticles () const
G4int GetNumberOfCharged () const
void SetNumberOfExcitedParticle (G4int valueTot, G4int valueP)
G4int GetNumberOfHoles () const
G4int GetNumberOfChargedHoles () const
void SetNumberOfHoles (G4int valueTot, G4int valueP=0)
void SetNumberOfParticles (G4int value)
void SetNumberOfCharged (G4int value)
G4int GetNumberOfElectrons () const
void SetNumberOfElectrons (G4int value)
G4int GetFloatingLevelNumber () const
void SetFloatingLevelNumber (G4int value)
const G4ParticleDefinition * GetParticleDefinition () const
void SetParticleDefinition (const G4ParticleDefinition *p)
G4double GetCreationTime () const
void SetCreationTime (G4double time)
G4NuclearPolarization * NuclearPolarization ()
G4NuclearPolarization * GetNuclearPolarization () const
void SetNuclearPolarization (G4NuclearPolarization *)
void SetAngularMomentum (const G4ThreeVector &)
G4ThreeVector GetAngularMomentum () const
Private Member Functions
void ExcitationEnergyWarning ()
void NumberOfExitationWarning (const G4String &)
void CalculateExcitationEnergy ()
void CalculateGroundStateMass ()
Private Attributes
G4int theA
G4int theZ
G4double theExcitationEnergy
G4double theGroundStateMass
G4LorentzVector theMomentum
G4NuclearPolarization * thePolarization
G4int creatorModel
G4int numberOfParticles
G4int numberOfCharged
G4int numberOfHoles
G4int numberOfChargedHoles
G4int numberOfShellElectrons
G4int xLevel
const G4ParticleDefinition * theParticleDefinition
G4double spin
G4double theCreationTime
Static Private Attributes
static const G4double minFragExcitation = 10.*CLHEP::eV
Friends
std::ostream & operator<< (std::ostream &, const G4Fragment &)
Detailed Description
Definition at line 65 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 65 of file G4Fragment.hh
Constructor & Destructor Documentation
G4Fragment::G4Fragment ()
Definition at line 54 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 54 of file G4Fragment.cc
G4Fragment::~G4Fragment ()
Definition at line 93 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 93 of file G4Fragment.cc
G4Fragment::G4Fragment (const G4Fragment & right)
Definition at line 74 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 74 of file G4Fragment.cc
G4Fragment::G4Fragment (G4int A, G4int Z, const G4LorentzVector & aMomentum)
Definition at line 96 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 96 of file G4Fragment.cc
References CalculateExcitationEnergy(), CalculateGroundStateMass(), and theA.
G4Fragment::G4Fragment (const G4LorentzVector & aMomentum, const G4ParticleDefinition * aParticleDefinition)
Definition at line 121 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 121 of file G4Fragment.cc
References G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), and theGroundStateMass.
Member Function Documentation
void G4Fragment::CalculateExcitationEnergy () inline private
Definition at line 238 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 238 of file G4Fragment.hh
References ExcitationEnergyWarning(), CLHEP::HepLorentzVector::mag(), minFragExcitation, theExcitationEnergy, theGroundStateMass, and theMomentum.
Referenced by G4Fragment(), and SetMomentum().
void G4Fragment::CalculateGroundStateMass () inline private
Definition at line 253 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 253 of file G4Fragment.hh
References G4NucleiProperties::GetNuclearMass(), theA, theGroundStateMass, and theZ.
Referenced by G4Fragment(), SetA(), SetZ(), and SetZandA_asInt().
G4double G4Fragment::ComputeGroundStateMass (G4int Z, G4int A) const inline
Definition at line 248 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 248 of file G4Fragment.hh
References G4NucleiProperties::GetNuclearMass().
Referenced by G4GEMProbability::CalcProbability(), and G4PhotonEvaporation::GetEmissionProbability().
void G4Fragment::ExcitationEnergyWarning () private
Definition at line 232 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 232 of file G4Fragment.cc
References G4cout, and G4endl.
Referenced by CalculateExcitationEnergy().
G4double G4Fragment::GetA (void) const inline
Definition at line 315 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 315 of file G4Fragment.hh
References theA.
G4int G4Fragment::GetA_asInt () const inline
Definition at line 258 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 258 of file G4Fragment.hh
References theA.
Referenced by G4PreCompoundEmission::AngularDistribution(), G4NeutronRadCapture::ApplyYourself(), G4FermiBreakUpVI::BreakFragment(), G4Evaporation::BreakFragment(), G4InuclEvaporation::BreakItUp(), G4StatMF::BreakItUp(), G4ExcitationHandler::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4PhotonEvaporation::BreakUpChain(), G4NeutronEvaporationProbability::CalcAlphaParam(), G4GEMProbability::CalcAlphaParam(), G4NeutronEvaporationProbability::CalcBetaParam(), G4GEMProbability::CalcBetaParam(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4GEMProbability::CalcProbability(), G4GNASHTransitions::CalculateProbability(), G4PreCompoundTransitions::CalculateProbability(), G4StatMFMacroCanonical::CalculateTemperature(), G4StatMFMicroCanonical::ChooseAandZ(), G4StatMFMacroCanonical::ChooseAandZ(), G4CascadeCheckBalance::collide(), G4GEMProbabilityVI::ComputeTotalProbability(), G4InuclNuclei::copy(), G4AblaInterface::DeExcite(), G4PreCompoundModel::DeExcite(), G4InuclCollider::deexcite(), G4BinaryCascade::DeExcite(), G4FissionProbability::EmissionProbability(), G4CompetitiveFission::EmittedFragment(), G4PhotonEvaporation::EmittedFragment(), G4CascadeDeexciteBase::explosion(), G4StatMF::FindTemperatureOfBreakingChannel(), G4StatMFMacroCanonical::G4StatMFMacroCanonical(), G4PhotonEvaporation::GenerateGamma(), G4GEMProbability::GetCoulombBarrier(), G4GEMChannelVI::GetEmissionProbability(), G4CompetitiveFission::GetEmissionProbability(), G4EvaporationChannel::GetEmissionProbability(), G4GEMChannel::GetEmissionProbability(), G4PhotonEvaporation::GetEmissionProbability(), G4CascadeDeexciteBase::getTargetData(), G4VPreCompoundFragment::Initialize(), G4StatMFMicroCanonical::Initialize(), G4StatMFMacroCanonical::Initialize(), G4StatMFMicroManager::Initialize(), G4GNASHTransitions::PerformTransition(), G4PreCompoundTransitions::PerformTransition(), G4GEMChannel::SampleKineticEnergy(), G4ExcitationHandler::SortSecondaryFragment(), and G4EvaporationProbability::TotalProbability().
G4ThreeVector G4Fragment::GetAngularMomentum () const
Definition at line 254 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 254 of file G4Fragment.cc
References spin, and v.
Referenced by G4AblaInterface::DeExcite().
G4double G4Fragment::GetBindingEnergy () const inline
Definition at line 293 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 293 of file G4Fragment.hh
References CLHEP::neutron_mass_c2, CLHEP::proton_mass_c2, theA, theGroundStateMass, and theZ.
G4double G4Fragment::GetCreationTime () const inline
Definition at line 440 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 440 of file G4Fragment.hh
References theCreationTime.
Referenced by G4NeutronRadCapture::ApplyYourself(), G4FermiBreakUpVI::BreakFragment(), G4UnstableFragmentBreakUp::BreakUpChain(), G4ITDecay::DecayIt(), G4PhotonEvaporation::GenerateGamma(), and operator<<().
G4int G4Fragment::GetCreatorModelType () const inline
Definition at line 399 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 399 of file G4Fragment.hh
References creatorModel.
Referenced by operator<<().
G4double G4Fragment::GetExcitationEnergy (void) const inline
Definition at line 275 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 275 of file G4Fragment.hh
References theExcitationEnergy.
Referenced by G4PreCompoundEmission::AngularDistribution(), G4ParaFissionModel::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4FermiBreakUpVI::BreakFragment(), G4Evaporation::BreakFragment(), G4InuclEvaporation::BreakItUp(), G4StatMF::BreakItUp(), G4ExcitationHandler::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4PhotonEvaporation::BreakUpChain(), G4StatMFMicroCanonical::CalcEntropyOfCompoundNucleus(), G4GEMProbability::CalcProbability(), G4GNASHTransitions::CalculateProbability(), G4PreCompoundTransitions::CalculateProbability(), G4StatMFMacroCanonical::CalculateTemperature(), G4GEMProbabilityVI::ComputeTotalProbability(), G4InuclNuclei::copy(), G4ITDecay::DecayIt(), G4AblaInterface::DeExcite(), G4PreCompoundModel::DeExcite(), G4FissionProbability::EmissionProbability(), G4GEMProbability::EmissionProbability(), G4CompetitiveFission::EmittedFragment(), G4PhotonEvaporation::EmittedFragment(), G4CascadeDeexciteBase::explosion(), G4StatMF::FindTemperatureOfBreakingChannel(), G4PhotonEvaporation::GenerateGamma(), G4GEMProbability::GetCoulombBarrier(), G4GEMChannelVI::GetEmissionProbability(), G4CompetitiveFission::GetEmissionProbability(), G4EvaporationChannel::GetEmissionProbability(), G4GEMChannel::GetEmissionProbability(), G4PhotonEvaporation::GetEmissionProbability(), G4CascadeDeexciteBase::getTargetData(), G4VPreCompoundFragment::Initialize(), G4StatMFMicroCanonical::Initialize(), G4StatMFMicroManager::Initialize(), G4HETCFragment::IntegrateEmissionProbability(), operator<<(), G4PreCompoundNucleon::ProbabilityDistributionFunction(), G4PreCompoundIon::ProbabilityDistributionFunction(), G4HETCChargedFragment::SampleKineticEnergy(), G4HETCNeutron::SampleKineticEnergy(), G4GEMChannel::SampleKineticEnergy(), G4GammaTransition::SampleTransition(), G4ExcitationHandler::SortSecondaryFragment(), and G4EvaporationProbability::TotalProbability().
G4int G4Fragment::GetFloatingLevelNumber () const inline
Definition at line 419 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 419 of file G4Fragment.hh
References xLevel.
Referenced by G4ITDecay::DecayIt(), and operator<<().
G4double G4Fragment::GetGroundStateMass () const inline
Definition at line 280 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 280 of file G4Fragment.hh
References theGroundStateMass.
Referenced by G4WilsonAbrasionModel::ApplyYourself(), G4FermiBreakUpVI::BreakFragment(), G4WilsonAblationModel::BreakItUp(), G4CompetitiveFission::EmittedFragment(), G4GEMChannelVI::GetEmissionProbability(), G4EvaporationChannel::GetEmissionProbability(), G4GEMChannel::GetEmissionProbability(), G4PhotonEvaporation::GetEmissionProbability(), G4VPreCompoundFragment::Initialize(), and G4GammaTransition::SampleTransition().
const G4LorentzVector & G4Fragment::GetMomentum (void) const inline
Definition at line 299 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 299 of file G4Fragment.hh
References theMomentum.
Referenced by G4PreCompoundEmission::AngularDistribution(), G4ParaFissionModel::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4FermiBreakUpVI::BreakFragment(), G4InuclEvaporation::BreakItUp(), G4StatMF::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4CascadeCheckBalance::collide(), G4InuclNuclei::copy(), G4ITDecay::DecayIt(), G4AblaInterface::DeExcite(), G4BinaryCascade::DeExcite(), G4GEMChannelVI::EmittedFragment(), G4CompetitiveFission::EmittedFragment(), G4EvaporationChannel::EmittedFragment(), G4GEMChannel::EmittedFragment(), G4CascadeDeexciteBase::getTargetData(), G4VPreCompoundFragment::Initialize(), operator<<(), G4PreCompoundEmission::PerformEmission(), and G4GammaTransition::SampleTransition().
G4NuclearPolarization * G4Fragment::GetNuclearPolarization () const inline
Definition at line 455 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 455 of file G4Fragment.hh
References thePolarization.
Referenced by G4PhotonEvaporation::EmittedFragment(), operator<<(), and G4GammaTransition::SampleDirection().
G4int G4Fragment::GetNumberOfCharged () const inline
Definition at line 342 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 342 of file G4Fragment.hh
References numberOfCharged.
Referenced by G4PreCompoundTransitions::CalculateProbability(), G4InuclNuclei::copy(), G4ExitonConfiguration::fill(), operator<<(), G4PreCompoundEmission::PerformEmission(), G4GNASHTransitions::PerformTransition(), G4PreCompoundTransitions::PerformTransition(), G4PreCompoundNucleon::ProbabilityDistributionFunction(), and G4PreCompoundIon::ProbabilityDistributionFunction().
G4int G4Fragment::GetNumberOfChargedHoles () const inline
Definition at line 362 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 362 of file G4Fragment.hh
References numberOfChargedHoles.
Referenced by G4InuclNuclei::copy(), G4ExitonConfiguration::fill(), and operator<<().
G4int G4Fragment::GetNumberOfElectrons () const inline
Definition at line 389 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 389 of file G4Fragment.hh
References numberOfShellElectrons.
Referenced by G4GammaTransition::SampleTransition().
G4int G4Fragment::GetNumberOfExcitons () const inline
Definition at line 332 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 332 of file G4Fragment.hh
References numberOfHoles, and numberOfParticles.
Referenced by G4PreCompoundEmission::AngularDistribution(), G4PreCompoundModel::DeExcite(), and operator<<().
G4int G4Fragment::GetNumberOfHoles () const inline
Definition at line 357 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 357 of file G4Fragment.hh
References numberOfHoles.
Referenced by G4PreCompoundEmission::AngularDistribution(), G4GNASHTransitions::CalculateProbability(), G4PreCompoundTransitions::CalculateProbability(), G4InuclNuclei::copy(), G4ExitonConfiguration::fill(), G4HETCFragment::IntegrateEmissionProbability(), G4HETCHe3::K(), G4HETCAlpha::K(), G4HETCProton::K(), G4HETCTriton::K(), G4HETCDeuteron::K(), G4HETCNeutron::K(), operator<<(), G4GNASHTransitions::PerformTransition(), G4PreCompoundTransitions::PerformTransition(), G4PreCompoundNucleon::ProbabilityDistributionFunction(), G4PreCompoundIon::ProbabilityDistributionFunction(), G4HETCChargedFragment::SampleKineticEnergy(), and G4HETCNeutron::SampleKineticEnergy().
G4int G4Fragment::GetNumberOfParticles () const inline
Definition at line 337 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 337 of file G4Fragment.hh
References numberOfParticles.
Referenced by G4PreCompoundEmission::AngularDistribution(), G4GNASHTransitions::CalculateProbability(), G4PreCompoundTransitions::CalculateProbability(), G4InuclNuclei::copy(), G4ExitonConfiguration::fill(), G4HETCFragment::IntegrateEmissionProbability(), G4HETCHe3::K(), G4HETCAlpha::K(), G4HETCProton::K(), G4HETCTriton::K(), G4HETCDeuteron::K(), G4HETCNeutron::K(), operator<<(), G4PreCompoundEmission::PerformEmission(), G4GNASHTransitions::PerformTransition(), G4PreCompoundTransitions::PerformTransition(), G4PreCompoundNucleon::ProbabilityDistributionFunction(), G4PreCompoundIon::ProbabilityDistributionFunction(), G4HETCChargedFragment::SampleKineticEnergy(), and G4HETCNeutron::SampleKineticEnergy().
const G4ParticleDefinition * G4Fragment::GetParticleDefinition (void) const inline
Definition at line 430 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 430 of file G4Fragment.hh
References theParticleDefinition.
Referenced by G4ParaFissionModel::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), and G4ITDecay::DecayIt().
G4double G4Fragment::GetSpin (void) const inline
Definition at line 409 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 409 of file G4Fragment.hh
References spin.
Referenced by operator<<().
G4double G4Fragment::GetZ (void) const inline
Definition at line 310 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 310 of file G4Fragment.hh
References theZ.
G4int G4Fragment::GetZ_asInt () const inline
Definition at line 263 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 263 of file G4Fragment.hh
References theZ.
Referenced by G4PreCompoundEmission::AngularDistribution(), G4NeutronRadCapture::ApplyYourself(), G4FermiBreakUpVI::BreakFragment(), G4Evaporation::BreakFragment(), G4InuclEvaporation::BreakItUp(), G4StatMF::BreakItUp(), G4ExcitationHandler::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4PhotonEvaporation::BreakUpChain(), G4He3EvaporationProbability::CalcAlphaParam(), G4AlphaEvaporationProbability::CalcAlphaParam(), G4ProtonEvaporationProbability::CalcAlphaParam(), G4DeuteronEvaporationProbability::CalcAlphaParam(), G4TritonEvaporationProbability::CalcAlphaParam(), G4GEMProbability::CalcAlphaParam(), G4StatMFMicroCanonical::CalcFreeInternalEnergy(), G4GEMProbability::CalcProbability(), G4GNASHTransitions::CalculateProbability(), G4PreCompoundTransitions::CalculateProbability(), G4StatMFMacroCanonical::CalculateTemperature(), G4StatMFMicroCanonical::ChooseAandZ(), G4StatMFMacroCanonical::ChooseAandZ(), G4CascadeCheckBalance::collide(), G4GEMProbabilityVI::ComputeTotalProbability(), G4InuclNuclei::copy(), G4AblaInterface::DeExcite(), G4PreCompoundModel::DeExcite(), G4FissionProbability::EmissionProbability(), G4CompetitiveFission::EmittedFragment(), G4PhotonEvaporation::EmittedFragment(), G4CascadeDeexciteBase::explosion(), G4StatMF::FindTemperatureOfBreakingChannel(), G4PhotonEvaporation::GenerateGamma(), G4GEMProbability::GetCoulombBarrier(), G4GEMChannelVI::GetEmissionProbability(), G4CompetitiveFission::GetEmissionProbability(), G4EvaporationChannel::GetEmissionProbability(), G4GEMChannel::GetEmissionProbability(), G4PhotonEvaporation::GetEmissionProbability(), G4CascadeDeexciteBase::getTargetData(), G4VPreCompoundFragment::Initialize(), G4StatMFMicroCanonical::Initialize(), G4StatMFMacroCanonical::Initialize(), G4StatMFMicroManager::Initialize(), G4GNASHTransitions::PerformTransition(), G4PreCompoundTransitions::PerformTransition(), G4GEMChannel::SampleKineticEnergy(), G4GammaTransition::SampleTransition(), G4ExcitationHandler::SortSecondaryFragment(), and G4EvaporationProbability::TotalProbability().
G4NuclearPolarization * G4Fragment::NuclearPolarization () inline
Definition at line 450 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 450 of file G4Fragment.hh
References thePolarization.
void G4Fragment::NumberOfExitationWarning (const G4String & value) private
Definition at line 240 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 240 of file G4Fragment.cc
References G4cout, and G4endl.
Referenced by SetNumberOfCharged(), SetNumberOfExcitedParticle(), and SetNumberOfHoles().
void G4Fragment::operator delete (void * aFragment) inline
Definition at line 233 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 233 of file G4Fragment.hh
References pFragmentAllocator().
void * G4Fragment::operator new (size_t) inline
Definition at line 227 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 227 of file G4Fragment.hh
References pFragmentAllocator().
G4bool G4Fragment::operator!= (const G4Fragment & right) const
Definition at line 176 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 176 of file G4Fragment.cc
G4Fragment & G4Fragment::operator= (const G4Fragment & right)
Definition at line 148 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 148 of file G4Fragment.cc
References creatorModel, numberOfCharged, numberOfChargedHoles, numberOfHoles, numberOfParticles, numberOfShellElectrons, spin, theA, theCreationTime, theExcitationEnergy, theGroundStateMass, theMomentum, theParticleDefinition, thePolarization, theZ, and xLevel.
G4bool G4Fragment::operator== (const G4Fragment & right) const
Definition at line 171 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 171 of file G4Fragment.cc
void G4Fragment::SetA (G4double value) inline
Definition at line 326 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 326 of file G4Fragment.hh
References CalculateGroundStateMass(), G4lrint(), and theA.
void G4Fragment::SetAngularMomentum (const G4ThreeVector & v)
Definition at line 249 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 249 of file G4Fragment.cc
References CLHEP::Hep3Vector::mag(), and spin.
Referenced by G4INCLXXInterface::ApplyYourself().
void G4Fragment::SetCreationTime (G4double time) inline
Definition at line 445 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 445 of file G4Fragment.hh
References theCreationTime, and Acts::VectorHelpers::time().
Referenced by G4LowEIonFragmentation::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4FermiBreakUpVI::BreakFragment(), G4UnstableFragmentBreakUp::BreakUpChain(), and G4PhotonEvaporation::GenerateGamma().
void G4Fragment::SetCreatorModelType (G4int value) inline
Definition at line 404 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 404 of file G4Fragment.hh
References creatorModel.
void G4Fragment::SetExcEnergyAndMomentum (G4double eexc, const G4LorentzVector & v) inline
Definition at line 285 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 285 of file G4Fragment.hh
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), CLHEP::HepLorentzVector::set(), theExcitationEnergy, theGroundStateMass, and theMomentum.
Referenced by G4NeutrinoNucleusModel::CoherentPion(), G4NeutrinoNucleusModel::FinalBarion(), and G4GammaTransition::SampleTransition().
void G4Fragment::SetFloatingLevelNumber (G4int value) inline
Definition at line 424 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 424 of file G4Fragment.hh
References xLevel.
Referenced by G4PhotonEvaporation::GenerateGamma().
void G4Fragment::SetMomentum (const G4LorentzVector & value) inline
Definition at line 304 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 304 of file G4Fragment.hh
References CalculateExcitationEnergy(), and theMomentum.
Referenced by G4WilsonAbrasionModel::ApplyYourself(), G4UnstableFragmentBreakUp::BreakUpChain(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4GEMChannelVI::EmittedFragment(), G4CompetitiveFission::EmittedFragment(), G4EvaporationChannel::EmittedFragment(), G4GEMChannel::EmittedFragment(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4CascadeDeexciteBase::makeFragment(), G4CascadeRecoilMaker::makeRecoilFragment(), and G4PreCompoundEmission::PerformEmission().
void G4Fragment::SetNuclearPolarization (G4NuclearPolarization * p) inline
Definition at line 460 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 460 of file G4Fragment.hh
References thePolarization.
Referenced by G4PhotonEvaporation::BreakUpChain(), and G4PhotonEvaporation::EmittedFragment().
void G4Fragment::SetNumberOfCharged (G4int value) inline
Definition at line 381 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 381 of file G4Fragment.hh
References numberOfCharged, NumberOfExitationWarning(), and numberOfParticles.
Referenced by G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4BinaryCascade::FindFragments(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4PreCompoundEmission::PerformEmission(), G4GNASHTransitions::PerformTransition(), G4PreCompoundTransitions::PerformTransition(), G4GeneratorPrecompoundInterface::Propagate(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
void G4Fragment::SetNumberOfElectrons (G4int value) inline
Definition at line 394 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 394 of file G4Fragment.hh
References numberOfShellElectrons.
Referenced by G4GammaTransition::SampleTransition().
void G4Fragment::SetNumberOfExcitedParticle (G4int valueTot, G4int valueP) inline
Definition at line 348 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 348 of file G4Fragment.hh
References numberOfCharged, NumberOfExitationWarning(), and numberOfParticles.
Referenced by G4ParaFissionModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4CascadeDeexciteBase::makeFragment(), G4InuclNuclei::makeG4Fragment(), and G4CascadeRecoilMaker::makeRecoilFragment().
void G4Fragment::SetNumberOfHoles (G4int valueTot, G4int valueP = 0) inline
Definition at line 367 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 367 of file G4Fragment.hh
References numberOfChargedHoles, NumberOfExitationWarning(), and numberOfHoles.
Referenced by G4ParaFissionModel::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4NeutrinoNucleusModel::CoherentPion(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4NeutrinoNucleusModel::FinalBarion(), G4BinaryCascade::FindFragments(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4CascadeDeexciteBase::makeFragment(), G4InuclNuclei::makeG4Fragment(), G4CascadeRecoilMaker::makeRecoilFragment(), G4GNASHTransitions::PerformTransition(), G4PreCompoundTransitions::PerformTransition(), G4GeneratorPrecompoundInterface::Propagate(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
void G4Fragment::SetNumberOfParticles (G4int value) inline
Definition at line 376 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 376 of file G4Fragment.hh
References numberOfParticles.
Referenced by G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4BinaryCascade::FindFragments(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4PreCompoundEmission::PerformEmission(), G4GNASHTransitions::PerformTransition(), G4PreCompoundTransitions::PerformTransition(), G4GeneratorPrecompoundInterface::Propagate(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
void G4Fragment::SetParticleDefinition (const G4ParticleDefinition * p) inline
Definition at line 435 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 435 of file G4Fragment.hh
References theParticleDefinition.
void G4Fragment::SetSpin (G4double value) inline
Definition at line 414 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 414 of file G4Fragment.hh
References spin.
Referenced by G4FermiBreakUpVI::BreakFragment(), and G4PhotonEvaporation::GenerateGamma().
void G4Fragment::SetZ (G4double value) inline
Definition at line 320 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 320 of file G4Fragment.hh
References CalculateGroundStateMass(), G4lrint(), and theZ.
void G4Fragment::SetZandA_asInt (G4int Znew, G4int Anew) inline
Definition at line 268 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 268 of file G4Fragment.hh
References CalculateGroundStateMass(), theA, and theZ.
Referenced by G4UnstableFragmentBreakUp::BreakUpChain(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4GEMChannelVI::EmittedFragment(), G4CompetitiveFission::EmittedFragment(), G4EvaporationChannel::EmittedFragment(), G4GEMChannel::EmittedFragment(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4CascadeDeexciteBase::makeFragment(), G4CascadeRecoilMaker::makeRecoilFragment(), and G4PreCompoundEmission::PerformEmission().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4Fragment & theFragment) friend
Definition at line 181 of file G4Fragment.cc.
View newest version in sPHENIX GitHub at line 181 of file G4Fragment.cc
Member Data Documentation
G4int G4Fragment::creatorModel private
Definition at line 199 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 199 of file G4Fragment.hh
Referenced by GetCreatorModelType(), operator=(), and SetCreatorModelType().
const G4double G4Fragment::minFragExcitation = 10.*CLHEP::eV static private
Definition at line 216 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 216 of file G4Fragment.hh
Referenced by CalculateExcitationEnergy().
G4int G4Fragment::numberOfCharged private
Definition at line 203 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 203 of file G4Fragment.hh
Referenced by GetNumberOfCharged(), operator=(), SetNumberOfCharged(), and SetNumberOfExcitedParticle().
G4int G4Fragment::numberOfChargedHoles private
Definition at line 205 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 205 of file G4Fragment.hh
Referenced by GetNumberOfChargedHoles(), operator=(), and SetNumberOfHoles().
G4int G4Fragment::numberOfHoles private
Definition at line 204 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 204 of file G4Fragment.hh
Referenced by GetNumberOfExcitons(), GetNumberOfHoles(), operator=(), and SetNumberOfHoles().
G4int G4Fragment::numberOfParticles private
Definition at line 202 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 202 of file G4Fragment.hh
Referenced by GetNumberOfExcitons(), GetNumberOfParticles(), operator=(), SetNumberOfCharged(), SetNumberOfExcitedParticle(), and SetNumberOfParticles().
G4int G4Fragment::numberOfShellElectrons private
Definition at line 208 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 208 of file G4Fragment.hh
Referenced by GetNumberOfElectrons(), operator=(), and SetNumberOfElectrons().
G4double G4Fragment::spin private
Definition at line 213 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 213 of file G4Fragment.hh
Referenced by GetAngularMomentum(), GetSpin(), operator=(), SetAngularMomentum(), and SetSpin().
G4int G4Fragment::theA private
Definition at line 185 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 185 of file G4Fragment.hh
Referenced by CalculateGroundStateMass(), G4Fragment(), GetA(), GetA_asInt(), GetBindingEnergy(), operator<<(), operator=(), SetA(), and SetZandA_asInt().
G4double G4Fragment::theCreationTime private
Definition at line 214 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 214 of file G4Fragment.hh
Referenced by GetCreationTime(), operator=(), and SetCreationTime().
G4double G4Fragment::theExcitationEnergy private
Definition at line 189 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 189 of file G4Fragment.hh
Referenced by CalculateExcitationEnergy(), GetExcitationEnergy(), operator=(), and SetExcEnergyAndMomentum().
G4double G4Fragment::theGroundStateMass private
Definition at line 191 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 191 of file G4Fragment.hh
Referenced by CalculateExcitationEnergy(), CalculateGroundStateMass(), G4Fragment(), GetBindingEnergy(), GetGroundStateMass(), operator=(), and SetExcEnergyAndMomentum().
G4LorentzVector G4Fragment::theMomentum private
Definition at line 193 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 193 of file G4Fragment.hh
Referenced by CalculateExcitationEnergy(), GetMomentum(), operator=(), SetExcEnergyAndMomentum(), and SetMomentum().
const G4ParticleDefinition* G4Fragment::theParticleDefinition private
Definition at line 211 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 211 of file G4Fragment.hh
Referenced by GetParticleDefinition(), operator=(), and SetParticleDefinition().
G4NuclearPolarization* G4Fragment::thePolarization private
Definition at line 196 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 196 of file G4Fragment.hh
Referenced by GetNuclearPolarization(), NuclearPolarization(), operator=(), and SetNuclearPolarization().
G4int G4Fragment::theZ private
Definition at line 187 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 187 of file G4Fragment.hh
Referenced by CalculateGroundStateMass(), GetBindingEnergy(), GetZ(), GetZ_asInt(), operator<<(), operator=(), SetZ(), and SetZandA_asInt().
G4int G4Fragment::xLevel private
Definition at line 209 of file G4Fragment.hh.
View newest version in sPHENIX GitHub at line 209 of file G4Fragment.hh
Referenced by GetFloatingLevelNumber(), operator=(), and SetFloatingLevelNumber().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4Fragment.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4Fragment.cc