ECCE @ EIC Software: G4TablesForExtrapolator Class Reference
G4TablesForExtrapolator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/include/G4TablesForExtrapolator.hh>
Public Member Functions
G4TablesForExtrapolator (G4int verb, G4int bins, G4double e1, G4double e2)
~G4TablesForExtrapolator ()
const G4PhysicsTable * GetPhysicsTable (ExtTableType type) const
void Initialisation ()
Private Member Functions
G4PhysicsTable * PrepareTable (G4PhysicsTable *)
void ComputeElectronDEDX (const G4ParticleDefinition *part, G4PhysicsTable *table)
void ComputeMuonDEDX (const G4ParticleDefinition *part, G4PhysicsTable *table)
void ComputeProtonDEDX (const G4ParticleDefinition *part, G4PhysicsTable *table)
void ComputeTrasportXS (const G4ParticleDefinition *part, G4PhysicsTable *table)
G4TablesForExtrapolator & operator= (const G4TablesForExtrapolator &right)
G4TablesForExtrapolator (const G4TablesForExtrapolator &)
Private Attributes
const G4ParticleDefinition * currentParticle
const G4ParticleDefinition * electron
const G4ParticleDefinition * positron
const G4ParticleDefinition * muonPlus
const G4ParticleDefinition * muonMinus
const G4ParticleDefinition * proton
G4DataVector cuts
G4LossTableBuilder * builder
G4ProductionCuts * pcuts
std::vector< const
G4MaterialCutsCouple * > couples
G4PhysicsTable * dedxElectron
G4PhysicsTable * dedxPositron
G4PhysicsTable * dedxMuon
G4PhysicsTable * dedxProton
G4PhysicsTable * rangeElectron
G4PhysicsTable * rangePositron
G4PhysicsTable * rangeMuon
G4PhysicsTable * rangeProton
G4PhysicsTable * invRangeElectron
G4PhysicsTable * invRangePositron
G4PhysicsTable * invRangeMuon
G4PhysicsTable * invRangeProton
G4PhysicsTable * mscElectron
G4int verbose
G4int nbins
G4int nmat
G4double emin
G4double emax
G4double mass
G4double charge2
G4bool splineFlag
Detailed Description
Definition at line 74 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 74 of file G4TablesForExtrapolator.hh
Constructor & Destructor Documentation
G4TablesForExtrapolator::G4TablesForExtrapolator (G4int verb, G4int bins, G4double e1, G4double e2) explicit
Definition at line 72 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 72 of file G4TablesForExtrapolator.cc
References dedxElectron, dedxMuon, dedxPositron, dedxProton, G4Electron::Electron(), electron, Initialisation(), invRangeElectron, invRangeMuon, invRangePositron, invRangeProton, mscElectron, G4MuonMinus::MuonMinus(), muonMinus, G4MuonPlus::MuonPlus(), muonPlus, pcuts, G4Positron::Positron(), positron, G4Proton::Proton(), proton, rangeElectron, rangeMuon, rangePositron, and rangeProton.
G4TablesForExtrapolator::~G4TablesForExtrapolator ()
Definition at line 90 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 90 of file G4TablesForExtrapolator.cc
References builder, G4PhysicsTable::clearAndDestroy(), couples, dedxElectron, dedxMuon, dedxPositron, dedxProton, invRangeElectron, invRangeMuon, invRangePositron, invRangeProton, mscElectron, nmat, pcuts, rangeElectron, rangeMuon, rangePositron, and rangeProton.
G4TablesForExtrapolator::G4TablesForExtrapolator (const G4TablesForExtrapolator &) private
Member Function Documentation
void G4TablesForExtrapolator::ComputeElectronDEDX (const G4ParticleDefinition * part, G4PhysicsTable * table) private
Definition at line 281 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 281 of file G4TablesForExtrapolator.cc
References charge2, cm, cm2, G4VEmModel::ComputeDEDX(), couples, currentParticle, cuts, e, source.hepunit::electron_mass_c2, G4PhysicsVector::Energy(), G4PhysicsVector::FillSecondDerivatives(), Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetDensity(), G4Material::GetMaterialTable(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4eBremsstrahlungRelModel::Initialise(), G4MollerBhabhaModel::Initialise(), mass, mat, MeV, nbins, nmat, part, G4PhysicsVector::PutValue(), G4VEmModel::SetUseBaseMaterials(), splineFlag, and verbose.
Referenced by Initialisation().
void G4TablesForExtrapolator::ComputeMuonDEDX (const G4ParticleDefinition * part, G4PhysicsTable * table) private
Definition at line 335 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 335 of file G4TablesForExtrapolator.cc
References charge2, cm, cm2, G4VEmModel::ComputeDEDX(), couples, currentParticle, cuts, e, G4PhysicsVector::Energy(), G4PhysicsVector::FillSecondDerivatives(), Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetDensity(), G4Material::GetMaterialTable(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4BetheBlochModel::Initialise(), G4MuBremsstrahlungModel::Initialise(), G4MuPairProductionModel::Initialise(), mass, mat, MeV, nbins, nmat, part, G4PhysicsVector::PutValue(), G4VEmModel::SetUseBaseMaterials(), splineFlag, and verbose.
Referenced by Initialisation().
void G4TablesForExtrapolator::ComputeProtonDEDX (const G4ParticleDefinition * part, G4PhysicsTable * table) private
Definition at line 392 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 392 of file G4TablesForExtrapolator.cc
References charge2, cm, cm2, G4VEmModel::ComputeDEDX(), couples, currentParticle, cuts, e, G4PhysicsVector::Energy(), G4PhysicsVector::FillSecondDerivatives(), Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetDensity(), G4Material::GetMaterialTable(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4BetheBlochModel::Initialise(), mass, mat, MeV, nbins, nmat, part, G4PhysicsVector::PutValue(), G4VEmModel::SetUseBaseMaterials(), splineFlag, and verbose.
Referenced by Initialisation().
void G4TablesForExtrapolator::ComputeTrasportXS (const G4ParticleDefinition * part, G4PhysicsTable * table) private
Definition at line 439 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 439 of file G4TablesForExtrapolator.cc
References charge2, couples, G4VEmModel::CrossSectionPerVolume(), currentParticle, cuts, e, G4PhysicsVector::Energy(), G4PhysicsVector::FillSecondDerivatives(), G4cout, G4endl, G4Material::GetMaterialTable(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4WentzelVIModel::Initialise(), mass, mat, MeV, mm, nbins, nmat, part, CLHEP::pi, G4PhysicsVector::PutValue(), G4VEmModel::SetCurrentCouple(), G4VEmModel::SetPolarAngleLimit(), G4VEmModel::SetUseBaseMaterials(), splineFlag, and verbose.
Referenced by Initialisation().
const G4PhysicsTable * G4TablesForExtrapolator::GetPhysicsTable (ExtTableType type) const
Definition at line 128 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 128 of file G4TablesForExtrapolator.cc
References dedxElectron, dedxMuon, dedxPositron, dedxProton, fDedxElectron, fDedxMuon, fDedxPositron, fDedxProton, fInvRangeElectron, fInvRangeMuon, fInvRangePositron, fInvRangeProton, fMscElectron, fRangeElectron, fRangeMuon, fRangePositron, fRangeProton, invRangeElectron, invRangeMuon, invRangePositron, invRangeProton, mscElectron, rangeElectron, rangeMuon, rangePositron, and rangeProton.
Referenced by G4EnergyLossForExtrapolator::GetPhysicsTable().
void G4TablesForExtrapolator::Initialisation ()
Definition at line 177 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 177 of file G4TablesForExtrapolator.cc
References builder, G4LossTableBuilder::BuildInverseRangeTable(), G4LossTableBuilder::BuildRangeTable(), charge2, ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), couples, currentParticle, cuts, DBL_MAX, dedxElectron, dedxMuon, dedxPositron, dedxProton, electron, G4cout, G4endl, G4Material::GetMaterialTable(), G4Material::GetNumberOfMaterials(), G4LossTableBuilder::InitialiseBaseMaterials(), G4EmParameters::Instance(), invRangeElectron, invRangeMuon, invRangePositron, invRangeProton, mass, mscElectron, muonPlus, nmat, pcuts, positron, PrepareTable(), proton, rangeElectron, rangeMuon, rangePositron, rangeProton, G4EmParameters::Spline(), splineFlag, and verbose.
Referenced by G4EnergyLossForExtrapolator::BuildTables(), and G4TablesForExtrapolator().
G4TablesForExtrapolator& G4TablesForExtrapolator::operator= (const G4TablesForExtrapolator & right) private
G4PhysicsTable * G4TablesForExtrapolator::PrepareTable (G4PhysicsTable * ptr) private
Definition at line 261 of file G4TablesForExtrapolator.cc.
View newest version in sPHENIX GitHub at line 261 of file G4TablesForExtrapolator.cc
References emax, emin, nbins, nmat, G4PhysicsTable::push_back(), G4PhysicsVector::SetSpline(), splineFlag, and v.
Referenced by Initialisation().
Member Data Documentation
G4LossTableBuilder* G4TablesForExtrapolator::builder private
Definition at line 115 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 115 of file G4TablesForExtrapolator.hh
Referenced by Initialisation(), and ~G4TablesForExtrapolator().
G4double G4TablesForExtrapolator::charge2 private
Definition at line 140 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 140 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), and Initialisation().
std::vector<const G4MaterialCutsCouple*> G4TablesForExtrapolator::couples private
Definition at line 117 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 117 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), Initialisation(), and ~G4TablesForExtrapolator().
const G4ParticleDefinition* G4TablesForExtrapolator::currentParticle private
Definition at line 106 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 106 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), and Initialisation().
G4DataVector G4TablesForExtrapolator::cuts private
Definition at line 113 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 113 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), and Initialisation().
G4PhysicsTable* G4TablesForExtrapolator::dedxElectron private
Definition at line 119 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 119 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::dedxMuon private
Definition at line 121 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 121 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::dedxPositron private
Definition at line 120 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 120 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::dedxProton private
Definition at line 122 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 122 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
const G4ParticleDefinition* G4TablesForExtrapolator::electron private
Definition at line 107 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 107 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), and Initialisation().
G4double G4TablesForExtrapolator::emax private
Definition at line 138 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 138 of file G4TablesForExtrapolator.hh
Referenced by PrepareTable().
G4double G4TablesForExtrapolator::emin private
Definition at line 137 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 137 of file G4TablesForExtrapolator.hh
Referenced by PrepareTable().
G4PhysicsTable* G4TablesForExtrapolator::invRangeElectron private
Definition at line 127 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 127 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::invRangeMuon private
Definition at line 129 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 129 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::invRangePositron private
Definition at line 128 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 128 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::invRangeProton private
Definition at line 130 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 130 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4double G4TablesForExtrapolator::mass private
Definition at line 139 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 139 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), and Initialisation().
G4PhysicsTable* G4TablesForExtrapolator::mscElectron private
Definition at line 131 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 131 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
const G4ParticleDefinition* G4TablesForExtrapolator::muonMinus private
Definition at line 110 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 110 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator().
const G4ParticleDefinition* G4TablesForExtrapolator::muonPlus private
Definition at line 109 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 109 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), and Initialisation().
G4int G4TablesForExtrapolator::nbins private
Definition at line 134 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 134 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), and PrepareTable().
G4int G4TablesForExtrapolator::nmat private
Definition at line 135 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 135 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), Initialisation(), PrepareTable(), and ~G4TablesForExtrapolator().
G4ProductionCuts* G4TablesForExtrapolator::pcuts private
Definition at line 116 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 116 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), Initialisation(), and ~G4TablesForExtrapolator().
const G4ParticleDefinition* G4TablesForExtrapolator::positron private
Definition at line 108 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 108 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), and Initialisation().
const G4ParticleDefinition* G4TablesForExtrapolator::proton private
Definition at line 111 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 111 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), and Initialisation().
G4PhysicsTable* G4TablesForExtrapolator::rangeElectron private
Definition at line 123 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 123 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::rangeMuon private
Definition at line 125 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 125 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::rangePositron private
Definition at line 124 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 124 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4PhysicsTable* G4TablesForExtrapolator::rangeProton private
Definition at line 126 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 126 of file G4TablesForExtrapolator.hh
Referenced by G4TablesForExtrapolator(), GetPhysicsTable(), Initialisation(), and ~G4TablesForExtrapolator().
G4bool G4TablesForExtrapolator::splineFlag private
Definition at line 142 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 142 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), Initialisation(), and PrepareTable().
G4int G4TablesForExtrapolator::verbose private
Definition at line 133 of file G4TablesForExtrapolator.hh.
View newest version in sPHENIX GitHub at line 133 of file G4TablesForExtrapolator.hh
Referenced by ComputeElectronDEDX(), ComputeMuonDEDX(), ComputeProtonDEDX(), ComputeTrasportXS(), and Initialisation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/include/G4TablesForExtrapolator.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/muons/src/G4TablesForExtrapolator.cc