ECCE @ EIC Software: G4INCL::Nucleus Class Reference
G4INCL::Nucleus Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNucleus.hh>
Classes
struct ConservationBalance
Struct for conservation laws.
Public Member Functions
Nucleus (G4int mass, G4int charge, G4int strangess, Config const *const conf, const G4double universeRadius=-1.)
virtual ~Nucleus ()
Nucleus (const Nucleus &rhs)
Dummy copy constructor to silence Coverity warning.
Nucleus & operator= (const Nucleus &rhs)
Dummy assignment operator to silence Coverity warning.
void initializeParticles ()
void insertParticle (Particle *p)
Insert a new particle (e.g. a projectile) in the nucleus.
void applyFinalState (FinalState *)
G4int getInitialA () const
G4int getInitialZ () const
G4int getInitialS () const
void propagateParticles (G4double step)
G4int getNumberOfEnteringProtons () const
G4int getNumberOfEnteringNeutrons () const
G4int getNumberOfEnteringPions () const
G4int getNumberOfEnteringKaons () const
G4double computeSeparationEnergyBalance () const
Outgoing - incoming separation energies.
G4bool decayOutgoingDeltas ()
Force the decay of outgoing deltas.
G4bool decayInsideDeltas ()
Force the decay of deltas inside the nucleus.
G4bool decayInsideStrangeParticles ()
Force the transformation of strange particles into a Lambda;.
G4bool decayOutgoingPionResonances (G4double timeThreshold)
Force the decay of outgoing PionResonances (eta/omega).
G4bool decayOutgoingSigmaZero (G4double timeThreshold)
Force the decay of outgoing Neutral Sigma.
G4bool decayOutgoingNeutralKaon ()
Force the transformation of outgoing Neutral Kaon into propation eigenstate.
G4bool decayOutgoingClusters ()
Force the decay of unstable outgoing clusters.
G4bool decayMe ()
Force the phase-space decay of the Nucleus.
void emitInsidePions ()
Force emission of all pions inside the nucleus.
void emitInsideStrangeParticles ()
Force emission of all strange particles inside the nucleus.
G4int emitInsideLambda ()
Force emission of all Lambda (desexitation code with strangeness not implanted yet)
G4bool emitInsideKaon ()
Force emission of all Kaon inside the nucleus.
void computeRecoilKinematics ()
Compute the recoil momentum and spin of the nucleus.
ThreeVector computeCenterOfMass () const
Compute the current center-of-mass position.
G4double computeTotalEnergy () const
Compute the current total energy.
G4double computeExcitationEnergy () const
Compute the current excitation energy.
void setIncomingAngularMomentum (const ThreeVector &j)
Set the incoming angular-momentum vector.
const ThreeVector & getIncomingAngularMomentum () const
Get the incoming angular-momentum vector.
void setIncomingMomentum (const ThreeVector &p)
Set the incoming momentum vector.
const ThreeVector & getIncomingMomentum () const
Get the incoming momentum vector.
void setInitialEnergy (const G4double e)
Set the initial energy.
G4double getInitialEnergy () const
Get the initial energy.
G4double getExcitationEnergy () const
Get the excitation energy of the nucleus.
G4bool containsDeltas ()
Returns true if the nucleus contains any deltas.
G4bool containsAntiKaon ()
Returns true if the nucleus contains any anti Kaons.
G4bool containsLambda ()
Returns true if the nucleus contains any Lambda.
G4bool containsSigma ()
Returns true if the nucleus contains any Sigma.
G4bool containsKaon ()
Returns true if the nucleus contains any Kaons.
G4bool containsEtas ()
Returns true if the nucleus contains any etas.
G4bool containsOmegas ()
Returns true if the nucleus contains any omegas.
std::string print ()
Store * getStore () const
void setStore (Store *s)
G4double getInitialInternalEnergy () const
G4bool isEventTransparent () const
Is the event transparent?
G4bool hasRemnant () const
Does the nucleus give a cascade remnant?
void fillEventInfo (EventInfo *eventInfo)
G4bool getTryCompoundNucleus ()
G4double getTransmissionBarrier (Particle const *const p)
Get the transmission barrier.
ConservationBalance getConservationBalance (EventInfo const &theEventInfo, const G4bool afterRecoil) const
Compute charge, mass, energy and momentum balance.
void useFusionKinematics ()
Adjust the kinematics for complete-fusion events.
G4double getSurfaceRadius (Particle const *const particle) const
Get the maximum allowed radius for a given particle.
G4double getUniverseRadius () const
Getter for theUniverseRadius.
void setUniverseRadius (const G4double universeRadius)
Setter for theUniverseRadius.
G4bool isNucleusNucleusCollision () const
Is it a nucleus-nucleus collision?
void setNucleusNucleusCollision ()
Set a nucleus-nucleus collision.
void setParticleNucleusCollision ()
Set a particle-nucleus collision.
void setProjectileRemnant (ProjectileRemnant *const c)
Set the projectile remnant.
ProjectileRemnant * getProjectileRemnant () const
Get the projectile remnant.
void deleteProjectileRemnant ()
Delete the projectile remnant.
void finalizeProjectileRemnant (const G4double emissionTime)
Finalise the projectile remnant.
void updatePotentialEnergy (Particle *p) const
Update the particle potential energy.
void setDensity (NuclearDensity const *const d)
Setter for theDensity.
NuclearDensity const * getDensity () const
Getter for theDensity.
NuclearPotential::INuclearPotential
const * getPotential () const
Getter for thePotential.
Public Member Functions inherited from G4INCL::Cluster
Cluster (const G4int Z, const G4int A, const G4int S, const G4bool createParticleSampler=true)
Standard Cluster constructor.
template<class Iterator >
Cluster (Iterator begin, Iterator end)
virtual ~Cluster ()
Cluster (const Cluster &rhs)
Copy constructor.
Cluster & operator= (const Cluster &rhs)
Assignment operator.
void swap (Cluster &rhs)
Helper method for the assignment operator.
ParticleSpecies getSpecies () const
Get the particle species.
void deleteParticles ()
void clearParticles ()
void setZ (const G4int Z)
Set the charge number of the cluster.
void setA (const G4int A)
Set the mass number of the cluster.
void setS (const G4int S)
Set the strangess number of the cluster.
G4double getExcitationEnergy () const
Get the excitation energy of the cluster.
void setExcitationEnergy (const G4double e)
Set the excitation energy of the cluster.
virtual G4double getTableMass () const
Get the real particle mass.
ParticleList const & getParticles () const
void removeParticle (Particle *const p)
Remove a particle from the cluster components.
void addParticle (Particle *const p)
void updateClusterParameters ()
Set total cluster mass, energy, size, etc. from the particles.
void addParticles (ParticleList const &pL)
Add a list of particles to the cluster.
ParticleList getParticleList () const
Returns the list of particles that make up the cluster.
std::string print () const
void internalBoostToCM ()
Boost to the CM of the component particles.
void putParticlesOffShell ()
Put the cluster components off shell.
void setPosition (const ThreeVector &position)
Set the position of the cluster.
void boost (const ThreeVector &aBoostVector)
Boost the cluster with the indicated velocity.
void freezeInternalMotion ()
Freeze the internal motion of the particles.
virtual void rotatePosition (const G4double angle, const ThreeVector &axis)
Rotate position of all the particles.
virtual void rotateMomentum (const G4double angle, const ThreeVector &axis)
Rotate momentum of all the particles.
virtual void makeProjectileSpectator ()
Make all the components projectile spectators, too.
virtual void makeTargetSpectator ()
Make all the components target spectators, too.
virtual void makeParticipant ()
Make all the components participants, too.
ThreeVector const & getSpin () const
Get the spin of the nucleus.
void setSpin (const ThreeVector &j)
Set the spin of the nucleus.
G4INCL::ThreeVector getAngularMomentum () const
Get the total angular momentum (orbital + spin)
Public Member Functions inherited from G4INCL::Particle
Particle ()
Particle (ParticleType t, G4double energy, ThreeVector const &momentum, ThreeVector const &position)
Particle (ParticleType t, ThreeVector const &momentum, ThreeVector const &position)
virtual ~Particle ()
Particle (const Particle &rhs)
Copy constructor.
Particle & operator= (const Particle &rhs)
Assignment operator.
G4INCL::ParticleType getType () const
void setType (ParticleType t)
G4bool isNucleon () const
ParticipantType getParticipantType () const
void setParticipantType (ParticipantType const p)
G4bool isParticipant () const
G4bool isTargetSpectator () const
G4bool isProjectileSpectator () const
G4bool isPion () const
Is this a pion?
G4bool isEta () const
Is this an eta?
G4bool isOmega () const
Is this an omega?
G4bool isEtaPrime () const
Is this an etaprime?
G4bool isPhoton () const
Is this a photon?
G4bool isResonance () const
Is it a resonance?
G4bool isDelta () const
Is it a Delta?
G4bool isSigma () const
Is this a Sigma?
G4bool isKaon () const
Is this a Kaon?
G4bool isAntiKaon () const
Is this an antiKaon?
G4bool isLambda () const
Is this a Lambda?
G4bool isNucleonorLambda () const
Is this a Nucleon or a Lambda?
G4bool isHyperon () const
Is this an Hyperon?
G4bool isMeson () const
Is this a Meson?
G4bool isBaryon () const
Is this a Baryon?
G4bool isStrange () const
Is this an Strange?
G4int getA () const
Returns the baryon number.
G4int getZ () const
Returns the charge number.
G4int getS () const
Returns the strangeness number.
G4double getBeta () const
ThreeVector boostVector () const
void boost (const ThreeVector &aBoostVector)
void lorentzContract (const ThreeVector &aBoostVector, const ThreeVector &refPos)
Lorentz-contract the particle position around some center.
G4double getMass () const
Get the cached particle mass.
G4double getINCLMass () const
Get the INCL particle mass.
G4double getRealMass () const
Get the real particle mass.
void setRealMass ()
Set the mass of the Particle to its real mass.
void setTableMass ()
Set the mass of the Particle to its table mass.
void setINCLMass ()
Set the mass of the Particle to its table mass.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent) const
Computes correction on the emission Q-value.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int ATo, const G4int ZTo) const
Computes correction on the transfer Q-value.
G4double getEmissionQValueCorrection (const G4int AParent, const G4int ZParent, const G4int SParent) const
Computes correction on the emission Q-value for hypernuclei.
G4double getTransferQValueCorrection (const G4int AFrom, const G4int ZFrom, const G4int SFrom, const G4int ATo, const G4int ZTo, const G4int STo) const
Computes correction on the transfer Q-value for hypernuclei.
G4double getInvariantMass () const
Get the the particle invariant mass.
G4double getKineticEnergy () const
Get the particle kinetic energy.
G4double getPotentialEnergy () const
Get the particle potential energy.
void setPotentialEnergy (G4double v)
Set the particle potential energy.
G4double getEnergy () const
void setMass (G4double mass)
void setEnergy (G4double energy)
const G4INCL::ThreeVector & getMomentum () const
virtual void setMomentum (const G4INCL::ThreeVector &momentum)
const G4INCL::ThreeVector & getPosition () const
G4double getHelicity ()
void setHelicity (G4double h)
void propagate (G4double step)
G4int getNumberOfCollisions () const
Return the number of collisions undergone by the particle.
void setNumberOfCollisions (G4int n)
Set the number of collisions undergone by the particle.
void incrementNumberOfCollisions ()
Increment the number of collisions undergone by the particle.
G4int getNumberOfDecays () const
Return the number of decays undergone by the particle.
void setNumberOfDecays (G4int n)
Set the number of decays undergone by the particle.
void incrementNumberOfDecays ()
Increment the number of decays undergone by the particle.
void setOutOfWell ()
Mark the particle as out of its potential well.
G4bool isOutOfWell () const
Check if the particle is out of its potential well.
void setEmissionTime (G4double t)
G4double getEmissionTime ()
ThreeVector getTransversePosition () const
Transverse component of the position w.r.t. the momentum.
ThreeVector getLongitudinalPosition () const
Longitudinal component of the position w.r.t. the momentum.
const ThreeVector & adjustMomentumFromEnergy ()
Rescale the momentum to match the total energy.
G4double adjustEnergyFromMomentum ()
Recompute the energy to match the momentum.
G4bool isCluster () const
void setFrozenMomentum (const ThreeVector &momentum)
Set the frozen particle momentum.
void setFrozenEnergy (const G4double energy)
Set the frozen particle momentum.
ThreeVector getFrozenMomentum () const
Get the frozen particle momentum.
G4double getFrozenEnergy () const
Get the frozen particle momentum.
ThreeVector getPropagationVelocity () const
Get the propagation velocity of the particle.
void freezePropagation ()
Freeze particle propagation.
void thawPropagation ()
Unfreeze particle propagation.
virtual void rotatePositionAndMomentum (const G4double angle, const ThreeVector &axis)
Rotate the particle position and momentum.
std::string print () const
std::string dump () const
long getID () const
ParticleList const * getParticles () const
G4double getReflectionMomentum () const
Return the reflection momentum.
void setUncorrelatedMomentum (const G4double p)
Set the uncorrelated momentum.
void rpCorrelate ()
Make the particle follow a strict r-p correlation.
void rpDecorrelate ()
Make the particle not follow a strict r-p correlation.
G4double getCosRPAngle () const
Get the cosine of the angle between position and momentum.
G4double getParticleBias () const
Get the particle bias.
void setParticleBias (G4double ParticleBias)
Set the particle bias.
std::vector< G4int > getBiasCollisionVector () const
Get the vector list of biased vertices on the particle path.
void setBiasCollisionVector (std::vector< G4int > BiasCollisionVector)
Set the vector list of biased vertices on the particle path.
G4int getNumberOfKaon () const
Number of Kaon inside de nucleus.
void setNumberOfKaon (const G4int NK)
Private Member Functions
void computeOneNucleonRecoilKinematics ()
Compute the recoil kinematics for a 1-nucleon remnant.
Private Attributes
G4int theInitialZ
G4int theInitialA
G4int theInitialS
G4int theNpInitial
The number of entering protons.
G4int theNnInitial
The number of entering neutrons.
G4int theNpionplusInitial
The number of entering pions.
G4int theNpionminusInitial
G4int theNkaonplusInitial
The number of entering kaons.
G4int theNkaonminusInitial
G4double initialInternalEnergy
ThreeVector incomingAngularMomentum
ThreeVector incomingMomentum
ThreeVector initialCenterOfMass
G4bool remnant
G4double initialEnergy
Store * theStore
G4bool tryCN
G4int projectileZ
The charge number of the projectile.
G4int projectileA
The mass number of the projectile.
G4int projectileS
The strangeness number of the projectile.
G4double theUniverseRadius
The radius of the universe.
G4bool isNucleusNucleus
true if running a nucleus-nucleus collision
ProjectileRemnant * theProjectileRemnant
Pointer to the quasi-projectile.
NuclearDensity const * theDensity
Pointer to the NuclearDensity object.
NuclearPotential::INuclearPotential
const * thePotential
Pointer to the NuclearPotential object.
Additional Inherited Members
Static Public Member Functions inherited from G4INCL::Particle
static G4double getTotalBias ()
General bias vector function.
static void setINCLBiasVector (std::vector< G4double > NewVector)
static void FillINCLBiasVector (G4double newBias)
static G4double getBiasFromVector (std::vector< G4int > VectorBias)
static std::vector< G4int > MergeVectorBias (Particle const *const p1, Particle const *const p2)
static std::vector< G4int > MergeVectorBias (std::vector< G4int > p1, Particle const *const p2)
Static Public Attributes inherited from G4INCL::Particle
static std::vector< G4double > INCLBiasVector
Time ordered vector of all bias applied.
static G4ThreadLocal G4int nextBiasedCollisionID = 0
Protected Member Functions inherited from G4INCL::Particle
void swap (Particle &rhs)
Helper method for the assignment operator.
Protected Attributes inherited from G4INCL::Cluster
ParticleList particles
G4double theExcitationEnergy
ThreeVector theSpin
ParticleSampler * theParticleSampler
Detailed Description
Definition at line 65 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 65 of file G4INCLNucleus.hh
Constructor & Destructor Documentation
G4INCL::Nucleus::Nucleus (G4int mass, G4int charge, G4int strangess, Config const *const conf, const G4double universeRadius = -1.)
Definition at line 68 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 68 of file G4INCLNucleus.cc
References G4INCL::NuclearDensityFactory::createDensity(), G4INCL::NuclearPotential::createPotential(), G4INCL::Config::getPionPotential(), G4INCL::Config::getPotentialType(), G4INCL::NuclearPotential::INuclearPotential::getSeparationEnergy(), G4INCL::IsospinPotential, G4INCL::Neutron, G4INCL::Proton, G4INCL::ParticleSampler::setDensity(), G4INCL::ParticleTable::setNeutronSeparationEnergy(), G4INCL::ParticleSampler::setPotential(), G4INCL::ParticleTable::setProtonSeparationEnergy(), G4INCL::Particle::theA, theDensity, G4INCL::Cluster::theParticleSampler, thePotential, G4INCL::Particle::theS, theStore, theUniverseRadius, and G4INCL::Particle::theZ.
G4INCL::Nucleus::~Nucleus () virtual
Definition at line 112 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 112 of file G4INCLNucleus.cc
References deleteProjectileRemnant(), and theStore.
G4INCL::Nucleus::Nucleus (const Nucleus & rhs)
Dummy copy constructor to silence Coverity warning.
Member Function Documentation
void G4INCL::Nucleus::applyFinalState (FinalState * finalstate)
Apply reaction final state information to the nucleus.
Definition at line 136 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 136 of file G4INCLNucleus.cc
References kdfinder::abs(), G4INCL::Store::add(), G4INCL::Store::addToOutgoing(), components, deleted, e, G4INCL::Store::getBook(), G4INCL::FinalState::getCreatedParticles(), G4INCL::Book::getCurrentTime(), G4INCL::FinalState::getDestroyedParticles(), G4INCL::FinalState::getEnteringParticles(), G4INCL::FinalState::getModifiedParticles(), G4INCL::FinalState::getOutgoingParticles(), G4INCL::Cluster::getParticles(), G4INCL::FinalState::getTotalEnergyBeforeInteraction(), G4INCL::FinalState::getValidity(), in, INCL_DEBUG, INCL_ERROR, insertParticle(), G4INCL::ParticleBelowFermiFS, G4INCL::ParticleBelowZeroFS, G4INCL::Store::particleHasBeenDestroyed(), G4INCL::Store::particleHasBeenEjected(), G4INCL::Store::particleHasBeenUpdated(), G4INCL::FinalState::print(), G4INCL::Store::removeScheduledAvatars(), G4INCL::Particle::theA, G4INCL::Particle::theS, theStore, G4INCL::Particle::theZ, tryCN, and G4INCL::ValidFS.
Referenced by G4INCL::INCL::cascade(), decayInsideDeltas(), decayInsideStrangeParticles(), and G4INCL::INCL::makeCompoundNucleus().
ThreeVector G4INCL::Nucleus::computeCenterOfMass () const
Compute the current center-of-mass position.
Returns
the center-of-mass position vector [fm].
Definition at line 268 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 268 of file G4INCLNucleus.cc
References cm, e, G4INCL::Store::getParticles(), mass, and theStore.
Referenced by computeRecoilKinematics().
G4double G4INCL::Nucleus::computeExcitationEnergy () const
Compute the current excitation energy.
Returns
the excitation energy [MeV]
Definition at line 281 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 281 of file G4INCLNucleus.cc
References computeSeparationEnergyBalance(), computeTotalEnergy(), and initialInternalEnergy.
Referenced by G4INCL::INCL::postCascade().
void G4INCL::Nucleus::computeOneNucleonRecoilKinematics () private
Compute the recoil kinematics for a 1-nucleon remnant.
Puts the remnant nucleon on mass shell and tries to enforce approximate energy conservation by modifying the masses of the outgoing particles.
Definition at line 853 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 853 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::Particle::adjustEnergyFromMomentum(), G4INCL::Particle::boost(), G4INCL::ClusterDecay::decay(), e, Acts::UnitConstants::fs, G4INCL::Particle::getA(), G4INCL::Store::getBook(), G4INCL::FinalState::getCreatedParticles(), G4INCL::Book::getCurrentTime(), G4INCL::IAvatar::getFinalState(), G4INCL::Particle::getMass(), G4INCL::Particle::getMomentum(), G4INCL::Store::getOutgoingParticles(), G4INCL::Store::getParticles(), G4INCL::Particle::getS(), G4INCL::Particle::getZ(), INCL_DATABLOCK, INCL_DEBUG, incomingMomentum, initialEnergy, G4INCL::Particle::isDelta(), G4INCL::ThreeVector::mag(), G4INCL::ThreeVector::mag2(), mom, G4INCL::KinematicsUtils::momentumInCM(), G4INCL::Store::particleHasBeenEjected(), scale, G4INCL::Particle::setEmissionTime(), G4INCL::Particle::setMomentum(), G4INCL::ThreeVector::setX(), G4INCL::ThreeVector::setY(), G4INCL::ThreeVector::setZ(), G4INCL::Particle::theA, G4INCL::Cluster::theExcitationEnergy, G4INCL::Particle::theS, theStore, G4INCL::Particle::theZ, and v.
Referenced by computeRecoilKinematics().
void G4INCL::Nucleus::computeRecoilKinematics ()
Compute the recoil momentum and spin of the nucleus.
Definition at line 235 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 235 of file G4INCLNucleus.cc
References G4INCL::Particle::adjustEnergyFromMomentum(), computeCenterOfMass(), computeOneNucleonRecoilKinematics(), e, emitInsidePions(), G4INCL::Cluster::getAngularMomentum(), G4INCL::Particle::getMomentum(), G4INCL::Store::getOutgoingParticles(), G4INCL::ParticleTable::getTableMass, incomingAngularMomentum, incomingMomentum, initialCenterOfMass, remnant, G4INCL::Particle::setMass(), G4INCL::Particle::theA, G4INCL::Cluster::theExcitationEnergy, G4INCL::Particle::theMomentum, G4INCL::Particle::thePosition, theProjectileRemnant, G4INCL::Particle::theS, G4INCL::Cluster::theSpin, theStore, and G4INCL::Particle::theZ.
Referenced by G4INCL::INCL::postCascade().
G4double G4INCL::Nucleus::computeSeparationEnergyBalance () const inline
Outgoing - incoming separation energies.
Used by CDPP.
Definition at line 128 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 128 of file G4INCLNucleus.hh
References G4INCL::Composite, G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, e, G4INCL::Store::getOutgoingParticles(), G4INCL::NuclearPotential::INuclearPotential::getSeparationEnergy(), G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::Proton, S(), G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, t, theNkaonminusInitial, theNkaonplusInitial, theNnInitial, theNpInitial, theNpionminusInitial, theNpionplusInitial, thePotential, and theStore.
Referenced by computeExcitationEnergy(), and G4INCL::CDPP::isBlocked().
G4double G4INCL::Nucleus::computeTotalEnergy () const
Compute the current total energy.
Returns
the total energy [MeV]
Definition at line 218 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 218 of file G4INCLNucleus.cc
References e, G4INCL::ParticleTable::effectiveNucleonMass, G4INCL::Store::getParticles(), G4INCL::ParticleTable::getRealMass(), and theStore.
Referenced by computeExcitationEnergy(), and initializeParticles().
G4bool G4INCL::Nucleus::containsAntiKaon () inline
Returns true if the nucleus contains any anti Kaons.
Definition at line 295 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 295 of file G4INCLNucleus.hh
References e, G4INCL::Store::getParticles(), and theStore.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::containsDeltas () inline
Returns true if the nucleus contains any deltas.
Definition at line 287 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 287 of file G4INCLNucleus.hh
References e, G4INCL::Store::getParticles(), and theStore.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::containsEtas () inline
Returns true if the nucleus contains any etas.
Definition at line 327 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 327 of file G4INCLNucleus.hh
References e, G4INCL::Store::getParticles(), and theStore.
G4bool G4INCL::Nucleus::containsKaon () inline
Returns true if the nucleus contains any Kaons.
Definition at line 319 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 319 of file G4INCLNucleus.hh
References e, G4INCL::Store::getParticles(), and theStore.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::containsLambda () inline
Returns true if the nucleus contains any Lambda.
Definition at line 303 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 303 of file G4INCLNucleus.hh
References e, G4INCL::Store::getParticles(), and theStore.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::containsOmegas () inline
Returns true if the nucleus contains any omegas.
Definition at line 335 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 335 of file G4INCLNucleus.hh
References e, G4INCL::Store::getParticles(), and theStore.
G4bool G4INCL::Nucleus::containsSigma () inline
Returns true if the nucleus contains any Sigma.
Definition at line 311 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 311 of file G4INCLNucleus.hh
References e, G4INCL::Store::getParticles(), and theStore.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::decayInsideDeltas ()
Force the decay of deltas inside the nucleus.
Returns
true if any delta was forced to decay.
Definition at line 361 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 361 of file G4INCLNucleus.cc
References applyFinalState(), G4INCL::ClusterDecay::decay(), e, emitInsidePions(), Acts::UnitConstants::fs, G4INCL::Store::getParticles(), G4INCL::FinalState::getValidity(), G4INCL::NuclearPotential::INuclearPotential::hasPionPotential(), INCL_DEBUG, INCL_WARN, G4INCL::Particle::theA, thePotential, theStore, G4INCL::Particle::theZ, and G4INCL::ValidFS.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::decayInsideStrangeParticles ()
Force the transformation of strange particles into a Lambda;.
Returns
true if any strange particles was forced to absorb.
Definition at line 417 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 417 of file G4INCLNucleus.cc
References applyFinalState(), G4INCL::ClusterDecay::decay(), e, emitInsideStrangeParticles(), Acts::UnitConstants::fs, G4INCL::Store::getParticles(), INCL_DEBUG, INCL_WARN, G4INCL::Random::shoot(), G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::Particle::theA, theStore, and G4INCL::Particle::theZ.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::decayMe ()
Force the phase-space decay of the Nucleus.
Only applied if Z==0 or N==0.
Returns
true if the nucleus was forced to decay.
Definition at line 656 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 656 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::ClusterDecay::decay(), e, G4INCL::Particle::getBiasCollisionVector(), G4INCL::Particle::theA, G4INCL::Particle::theS, theStore, and G4INCL::Particle::theZ.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::decayOutgoingClusters ()
Force the decay of unstable outgoing clusters.
Returns
true if any cluster was forced to decay.
Definition at line 631 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 631 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::ClusterDecay::decay(), G4INCL::Cluster::deleteParticles(), e, G4INCL::Particle::getBiasCollisionVector(), G4INCL::Store::getOutgoingParticles(), and theStore.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::decayOutgoingDeltas ()
Force the decay of outgoing deltas.
Returns
true if any delta was forced to decay.
Definition at line 308 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 308 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::Particle::adjustEnergyFromMomentum(), G4INCL::Particle::boost(), G4INCL::ClusterDecay::decay(), e, Acts::UnitConstants::fs, G4INCL::Particle::getBiasCollisionVector(), G4INCL::FinalState::getCreatedParticles(), G4INCL::Particle::getEmissionTime(), G4INCL::IAvatar::getFinalState(), G4INCL::FinalState::getModifiedParticles(), G4INCL::Particle::getMomentum(), G4INCL::Store::getOutgoingParticles(), G4INCL::Particle::getTableMass(), INCL_DEBUG, G4INCL::ThreeVector::mag(), G4INCL::KinematicsUtils::momentumInCM(), G4InuclParticleNames::nucleon(), G4InuclParticleNames::pion(), G4INCL::Particle::setBiasCollisionVector(), G4INCL::Particle::setEmissionTime(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setTableMass(), and theStore.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::decayOutgoingNeutralKaon ()
Force the transformation of outgoing Neutral Kaon into propation eigenstate.
Returns
true if any kaon was forced to decay.
Definition at line 608 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 608 of file G4INCLNucleus.cc
References G4INCL::ClusterDecay::decay(), e, Acts::UnitConstants::fs, G4INCL::Store::getOutgoingParticles(), INCL_DEBUG, G4INCL::KZero, G4INCL::KZeroBar, and theStore.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::decayOutgoingPionResonances (G4double timeThreshold)
Force the decay of outgoing PionResonances (eta/omega).
Returns
true if any eta was forced to decay.
Definition at line 480 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 480 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::Particle::adjustEnergyFromMomentum(), G4INCL::Particle::boost(), G4INCL::ClusterDecay::decay(), e, G4INCL::Eta, Acts::UnitConstants::fs, G4INCL::Particle::getBiasCollisionVector(), G4INCL::FinalState::getCreatedParticles(), G4INCL::IAvatar::getFinalState(), G4INCL::FinalState::getModifiedParticles(), G4INCL::Particle::getMomentum(), G4INCL::Store::getOutgoingParticles(), G4INCL::Particle::getTableMass(), G4INCL::ParticleTable::getWidth(), INCL_DEBUG, INCL_ERROR, G4INCL::ThreeVector::mag(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::Omega, G4INCL::Particle::setBiasCollisionVector(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setTableMass(), and theStore.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::decayOutgoingSigmaZero (G4double timeThreshold)
Force the decay of outgoing Neutral Sigma.
Returns
true if any Sigma was forced to decay.
Definition at line 551 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 551 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::Particle::adjustEnergyFromMomentum(), G4INCL::Particle::boost(), G4INCL::ClusterDecay::decay(), e, Acts::UnitConstants::fs, G4INCL::Particle::getBiasCollisionVector(), G4INCL::FinalState::getCreatedParticles(), G4INCL::IAvatar::getFinalState(), G4INCL::FinalState::getModifiedParticles(), G4INCL::Particle::getMomentum(), G4INCL::Store::getOutgoingParticles(), G4INCL::Particle::getTableMass(), G4INCL::ParticleTable::getWidth(), INCL_DEBUG, INCL_ERROR, G4INCL::ThreeVector::mag(), G4INCL::KinematicsUtils::momentumInCM(), G4INCL::Particle::setBiasCollisionVector(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setTableMass(), G4INCL::SigmaZero, and theStore.
Referenced by G4INCL::INCL::postCascade().
void G4INCL::Nucleus::deleteProjectileRemnant () inline
Delete the projectile remnant.
Definition at line 442 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 442 of file G4INCLNucleus.hh
References theProjectileRemnant.
Referenced by ~Nucleus().
G4bool G4INCL::Nucleus::emitInsideKaon ()
Force emission of all Kaon inside the nucleus.
Definition at line 796 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 796 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::Particle::adjustMomentumFromEnergy(), e, G4INCL::Store::getBook(), G4INCL::Book::getCurrentTime(), G4INCL::Particle::getEmissionQValueCorrection(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMass(), G4INCL::Store::getParticles(), G4INCL::Particle::getPotentialEnergy(), G4INCL::Particle::getS(), G4INCL::Particle::getTotalBias(), G4INCL::Particle::getZ(), INCL_DEBUG, G4INCL::Store::particleHasBeenEjected(), G4INCL::Particle::print(), G4INCL::Particle::setEmissionTime(), G4INCL::Particle::setEnergy(), G4INCL::Particle::setPotentialEnergy(), G4INCL::Particle::setTableMass(), G4INCL::Particle::theA, G4INCL::Particle::theNKaon, G4INCL::Particle::theS, theStore, and G4INCL::Particle::theZ.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
G4int G4INCL::Nucleus::emitInsideLambda ()
Force emission of all Lambda (desexitation code with strangeness not implanted yet)
Definition at line 753 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 753 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::Particle::adjustMomentumFromEnergy(), e, G4INCL::Particle::getA(), G4INCL::Store::getBook(), G4INCL::Book::getCurrentTime(), G4INCL::Particle::getEmissionQValueCorrection(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMass(), G4INCL::Store::getParticles(), G4INCL::Particle::getPotentialEnergy(), G4INCL::Particle::getS(), G4INCL::Particle::getTotalBias(), INCL_DEBUG, G4INCL::Store::particleHasBeenEjected(), G4INCL::Particle::print(), G4INCL::Particle::setEmissionTime(), G4INCL::Particle::setEnergy(), G4INCL::Particle::setPotentialEnergy(), G4INCL::Particle::setTableMass(), G4INCL::Particle::theA, G4INCL::Particle::theS, theStore, and G4INCL::Particle::theZ.
Referenced by G4INCL::INCL::postCascade().
void G4INCL::Nucleus::emitInsidePions ()
Force emission of all pions inside the nucleus.
Definition at line 670 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 670 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::Particle::adjustMomentumFromEnergy(), e, G4INCL::Store::getBook(), G4INCL::Book::getCurrentTime(), G4INCL::Particle::getEmissionQValueCorrection(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMass(), G4INCL::Store::getParticles(), G4INCL::Particle::getPotentialEnergy(), G4INCL::Particle::getTotalBias(), G4INCL::Particle::getZ(), INCL_DEBUG, INCL_WARN, G4INCL::Store::particleHasBeenEjected(), G4INCL::Particle::print(), G4INCL::Particle::setEmissionTime(), G4INCL::Particle::setEnergy(), G4INCL::Particle::setPotentialEnergy(), G4INCL::Particle::setTableMass(), G4INCL::Particle::theA, G4INCL::Particle::theS, theStore, and G4INCL::Particle::theZ.
Referenced by computeRecoilKinematics(), and decayInsideDeltas().
void G4INCL::Nucleus::emitInsideStrangeParticles ()
Force emission of all strange particles inside the nucleus.
Definition at line 710 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 710 of file G4INCLNucleus.cc
References G4INCL::Store::addToOutgoing(), G4INCL::Particle::adjustMomentumFromEnergy(), e, G4INCL::Particle::getA(), G4INCL::Store::getBook(), G4INCL::Book::getCurrentTime(), G4INCL::Particle::getEmissionQValueCorrection(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMass(), G4INCL::Store::getParticles(), G4INCL::Particle::getPotentialEnergy(), G4INCL::Particle::getS(), G4INCL::Particle::getTotalBias(), G4INCL::Particle::getZ(), INCL_DEBUG, G4INCL::Store::particleHasBeenEjected(), G4INCL::Particle::print(), G4INCL::Particle::setEmissionTime(), G4INCL::Particle::setEnergy(), G4INCL::Particle::setPotentialEnergy(), G4INCL::Particle::setTableMass(), G4INCL::Particle::theA, G4INCL::Particle::theS, theStore, and G4INCL::Particle::theZ.
Referenced by decayInsideStrangeParticles(), and G4INCL::INCL::postCascade().
void G4INCL::Nucleus::fillEventInfo (EventInfo * eventInfo)
Fill the event info which contains INCL output data
Definition at line 1010 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 1010 of file G4INCLNucleus.cc
References G4INCL::EventInfo::A, kdfinder::abs(), G4INCL::EventInfo::ARem, G4INCL::CollisionAvatarType, G4INCL::Composite, G4INCL::DecayAvatarType, E, e, G4INCL::EventInfo::EKin, G4INCL::EventInfo::EKinRem, G4INCL::EventInfo::emissionTime, G4INCL::EventInfo::EStarRem, G4INCL::EventInfo::eventNumber, G4INCL::EventInfo::firstCollisionIsElastic, G4INCL::EventInfo::firstCollisionSpectatorMomentum, G4INCL::EventInfo::firstCollisionSpectatorPosition, G4INCL::EventInfo::firstCollisionTime, G4INCL::EventInfo::firstCollisionXSec, G4INCL::EventInfo::forcedCompoundNucleus, G4INCL::Particle::getA(), G4INCL::Book::getAcceptedCollisions(), G4INCL::Book::getAcceptedDecays(), G4INCL::Book::getAvatars(), G4INCL::Book::getBlockedCollisions(), G4INCL::Book::getBlockedDecays(), G4INCL::Store::getBook(), G4INCL::Book::getEnergyViolationInteraction(), G4INCL::Cluster::getExcitationEnergy(), getExcitationEnergy(), G4INCL::Book::getFirstCollisionIsElastic(), G4INCL::Book::getFirstCollisionSpectatorMomentum(), G4INCL::Book::getFirstCollisionSpectatorPosition(), G4INCL::Book::getFirstCollisionTime(), G4INCL::Book::getFirstCollisionXSec(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMomentum(), G4INCL::Store::getOutgoingParticles(), G4INCL::Particle::getS(), G4INCL::Cluster::getSpin(), getStore(), G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), G4INCL::Particle::getZ(), hasRemnant(), G4INCL::PhysicalConstants::hc, G4INCL::EventInfo::history, INCL_WARN, G4INCL::EventInfo::JRem, G4INCL::EventInfo::jxRem, G4INCL::EventInfo::jyRem, G4INCL::EventInfo::jzRem, G4INCL::ThreeVector::mag(), mom, G4INCL::EventInfo::nBlockedCollisions, G4INCL::EventInfo::nBlockedDecays, G4INCL::EventInfo::nCascadeParticles, G4INCL::EventInfo::nCollisionAvatars, G4INCL::EventInfo::nCollisions, G4INCL::EventInfo::nDecayAvatars, G4INCL::EventInfo::nDecays, G4INCL::EventInfo::nEnergyViolationInteraction, G4INCL::Neutron, G4INCL::EventInfo::nParticles, G4INCL::EventInfo::nReflectionAvatars, G4INCL::EventInfo::nRemnants, G4INCL::EventInfo::nucleonAbsorption, G4INCL::EventInfo::origin, G4INCL::EventInfo::ParticleBias, G4INCL::EventInfo::PDGCode, G4INCL::ThreeVector::phi(), G4INCL::EventInfo::phi, G4INCL::EventInfo::phiRem, G4INCL::PiMinus, G4INCL::EventInfo::pionAbsorption, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::EventInfo::projectileType, G4INCL::Proton, pt, G4INCL::EventInfo::px, G4INCL::EventInfo::pxRem, G4INCL::EventInfo::py, G4INCL::EventInfo::pyRem, G4INCL::EventInfo::pz, G4INCL::EventInfo::pzRem, G4INCL::EventInfo::S, G4INCL::EventInfo::SRem, G4INCL::SurfaceAvatarType, theProjectileRemnant, theStore, G4INCL::ThreeVector::theta(), G4INCL::EventInfo::theta, G4INCL::EventInfo::thetaRem, G4INCL::Math::toDegrees(), tryCN, G4INCL::EventInfo::Z, and G4INCL::EventInfo::ZRem.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::postCascade().
void G4INCL::Nucleus::finalizeProjectileRemnant (const G4double emissionTime)
Finalise the projectile remnant.
Complete the treatment of the projectile remnant. If it contains nucleons, assign its excitation energy and spin. Move stuff to the outgoing list, if appropriate.
Parameters
emissionTime the emission time of the projectile remnant
Definition at line 1211 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 1211 of file G4INCLNucleus.cc
References G4INCL::Particle::getA(), G4INCL::Particle::getInvariantMass(), G4INCL::Particle::getS(), G4INCL::ParticleTable::getTableMass, G4INCL::Particle::getZ(), G4INCL::Particle::setEmissionTime(), G4INCL::Cluster::setExcitationEnergy(), G4INCL::Particle::setMass(), G4INCL::Cluster::setSpin(), and theProjectileRemnant.
Referenced by G4INCL::INCL::makeCompoundNucleus(), and G4INCL::INCL::makeProjectileRemnant().
Nucleus::ConservationBalance G4INCL::Nucleus::getConservationBalance (EventInfo const & theEventInfo, const G4bool afterRecoil) const
Compute charge, mass, energy and momentum balance.
Definition at line 1155 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 1155 of file G4INCLNucleus.cc
References G4INCL::Nucleus::ConservationBalance::A, G4INCL::EventInfo::Ap, G4INCL::EventInfo::At, e, G4INCL::Nucleus::ConservationBalance::energy, G4INCL::Particle::getA(), G4INCL::Cluster::getExcitationEnergy(), getExcitationEnergy(), getIncomingMomentum(), getInitialEnergy(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMomentum(), G4INCL::Store::getOutgoingParticles(), G4INCL::Particle::getS(), G4INCL::ParticleTable::getTableMass, G4INCL::Particle::getZ(), hasRemnant(), G4INCL::Nucleus::ConservationBalance::momentum, G4INCL::Nucleus::ConservationBalance::S, G4INCL::EventInfo::Sp, G4INCL::EventInfo::St, theProjectileRemnant, theStore, G4INCL::Nucleus::ConservationBalance::Z, G4INCL::EventInfo::Zp, and G4INCL::EventInfo::Zt.
Referenced by G4INCL::INCL::RecoilFunctor::operator()(), and G4INCL::INCL::RecoilCMFunctor::operator()().
NuclearDensity const* G4INCL::Nucleus::getDensity () const inline
Getter for theDensity.
Definition at line 470 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 470 of file G4INCLNucleus.hh
References theDensity.
Referenced by G4INCL::CoulombNonRelativistic::distortOut(), G4INCL::ClusteringModelIntercomparison::findClusterStartingFrom(), G4INCL::ClusteringModelIntercomparison::getCluster(), and G4INCL::KinematicsUtils::getLocalEnergy().
G4double G4INCL::Nucleus::getExcitationEnergy () const inline
Get the excitation energy of the nucleus.
Method computeRecoilKinematics() should be called first.
Definition at line 284 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 284 of file G4INCLNucleus.hh
References G4INCL::Cluster::theExcitationEnergy.
Referenced by fillEventInfo(), getConservationBalance(), G4INCL::INCL::postCascade(), G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta(), and G4INCL::INCL::RecoilFunctor::scaleParticleEnergies().
const ThreeVector& G4INCL::Nucleus::getIncomingAngularMomentum () const inline
Get the incoming angular-momentum vector.
Definition at line 262 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 262 of file G4INCLNucleus.hh
References incomingAngularMomentum.
Referenced by G4INCL::INCL::makeCompoundNucleus().
const ThreeVector& G4INCL::Nucleus::getIncomingMomentum () const inline
Get the incoming momentum vector.
Definition at line 270 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 270 of file G4INCLNucleus.hh
References incomingMomentum.
Referenced by getConservationBalance(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor(), and G4INCL::INCL::RecoilFunctor::scaleParticleEnergies().
G4int G4INCL::Nucleus::getInitialA () const inline
Definition at line 108 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 108 of file G4INCLNucleus.hh
References theInitialA.
Referenced by G4INCL::PauliGlobal::isBlocked().
G4double G4INCL::Nucleus::getInitialEnergy () const inline
Get the initial energy.
Definition at line 278 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 278 of file G4INCLNucleus.hh
References initialEnergy.
Referenced by getConservationBalance(), and G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor().
G4double G4INCL::Nucleus::getInitialInternalEnergy () const inline
Definition at line 353 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 353 of file G4INCLNucleus.hh
References initialInternalEnergy.
Referenced by G4INCL::CDPP::isBlocked().
G4int G4INCL::Nucleus::getInitialS () const inline
Definition at line 110 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 110 of file G4INCLNucleus.hh
References theInitialS.
G4int G4INCL::Nucleus::getInitialZ () const inline
Definition at line 109 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 109 of file G4INCLNucleus.hh
References theInitialZ.
Referenced by G4INCL::PauliGlobal::isBlocked().
G4int G4INCL::Nucleus::getNumberOfEnteringKaons () const inline
Definition at line 122 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 122 of file G4INCLNucleus.hh
References theNkaonminusInitial, and theNkaonplusInitial.
G4int G4INCL::Nucleus::getNumberOfEnteringNeutrons () const inline
Definition at line 120 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 120 of file G4INCLNucleus.hh
References theNnInitial.
G4int G4INCL::Nucleus::getNumberOfEnteringPions () const inline
Definition at line 121 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 121 of file G4INCLNucleus.hh
References theNpionminusInitial, and theNpionplusInitial.
G4int G4INCL::Nucleus::getNumberOfEnteringProtons () const inline
Definition at line 119 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 119 of file G4INCLNucleus.hh
References theNpInitial.
NuclearPotential::INuclearPotential const* G4INCL::Nucleus::getPotential () const inline
Getter for thePotential.
Definition at line 473 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 473 of file G4INCLNucleus.hh
References thePotential.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::KinematicsUtils::getLocalEnergy(), G4INCL::PauliStrict::isBlocked(), G4INCL::PauliGlobal::isBlocked(), G4INCL::CDPP::isBlocked(), and G4INCL::ParticleEntryChannel::particleEnters().
ProjectileRemnant* G4INCL::Nucleus::getProjectileRemnant () const inline
Get the projectile remnant.
Definition at line 439 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 439 of file G4INCLNucleus.hh
References theProjectileRemnant.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::makeProjectileRemnant(), G4INCL::INCL::postCascade(), G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor(), and G4INCL::INCL::RecoilFunctor::RecoilFunctor().
Store* G4INCL::Nucleus::getStore () const inline
Definition at line 347 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 347 of file G4INCLNucleus.hh
References theStore.
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::CascadeAction::beforeAvatarDefaultAction(), G4INCL::INCL::continueCascade(), G4INCL::InteractionAvatar::enforceEnergyConservation(), fillEventInfo(), G4INCL::StandardPropagationModel::generateAllAvatars(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::BinaryCollisionAvatar::getChannel(), G4INCL::SurfaceAvatar::getChannel(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::SurfaceAvatar::getTransmissionProbability(), G4INCL::INCL::initializeTarget(), G4INCL::PauliGlobal::isBlocked(), G4INCL::CDPP::isBlocked(), G4INCL::PauliStrictStandard::isBlocked(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::INCL::makeProjectileRemnant(), G4INCL::ParticleEntryChannel::particleEnters(), G4INCL::INCL::postCascade(), G4INCL::DecayAvatar::postInteraction(), G4INCL::BinaryCollisionAvatar::postInteraction(), G4INCL::SurfaceAvatar::postInteraction(), G4INCL::InteractionAvatar::postInteraction(), G4INCL::StandardPropagationModel::propagate(), G4INCL::StandardPropagationModel::registerAvatar(), G4INCL::StandardPropagationModel::shootComposite(), G4INCL::StandardPropagationModel::shootParticle(), G4INCL::InteractionAvatar::shouldUseLocalEnergy(), and G4INCL::StandardPropagationModel::updateAvatars().
G4double G4INCL::Nucleus::getSurfaceRadius (Particle const *const particle) const inline
Get the maximum allowed radius for a given particle.
Calls the NuclearDensity::getMaxRFromP() method for nucleons and deltas, and the NuclearDensity::getTrasmissionRadius() method for pions.
Parameters
particle pointer to a particle
Returns
surface radius
Definition at line 402 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 402 of file G4INCLNucleus.hh
References G4INCL::NuclearPotential::INuclearPotential::getFermiMomentum(), G4INCL::NuclearDensity::getMaxRFromP(), G4INCL::Particle::getReflectionMomentum(), G4INCL::Particle::getType(), getUniverseRadius(), G4INCL::Particle::isLambda(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isResonance(), gammaraytel::pr, theDensity, and thePotential.
Referenced by G4INCL::InteractionAvatar::bringParticleInside(), G4INCL::StandardPropagationModel::generateBinaryCollisionAvatar(), G4INCL::StandardPropagationModel::getReflectionTime(), and G4INCL::InteractionAvatar::postInteraction().
G4double G4INCL::Nucleus::getTransmissionBarrier (Particle const *const p) inline
Get the transmission barrier.
Definition at line 375 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 375 of file G4INCLNucleus.hh
References G4INCL::PhysicalConstants::eSquared, G4INCL::NuclearDensity::getTransmissionRadius(), G4INCL::Particle::getZ(), theDensity, and G4INCL::Particle::theZ.
Referenced by G4INCL::SurfaceAvatar::getTransmissionProbability(), and G4INCL::InteractionAvatar::postInteraction().
G4bool G4INCL::Nucleus::getTryCompoundNucleus () inline
Definition at line 372 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 372 of file G4INCLNucleus.hh
References tryCN.
Referenced by G4INCL::INCL::continueCascade(), G4INCL::INCL::postCascade(), and G4INCL::INCL::updateGlobalInfo().
G4double G4INCL::Nucleus::getUniverseRadius () const inline
Getter for theUniverseRadius.
Definition at line 418 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 418 of file G4INCLNucleus.hh
References theUniverseRadius.
Referenced by G4INCL::CoulombNone::bringToSurface(), G4INCL::PauliStandard::getBlockingProbability(), G4INCL::ClusteringModelIntercomparison::getCluster(), G4INCL::CoulombNonRelativistic::getCoulombRadius(), G4INCL::KinematicsUtils::getLocalEnergy(), getSurfaceRadius(), G4INCL::CoulombNone::maxImpactParameter(), G4INCL::CoulombNonRelativistic::maxImpactParameter(), G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
G4bool G4INCL::Nucleus::hasRemnant () const inline
Does the nucleus give a cascade remnant?
To be called after computeRecoilKinematics().
Definition at line 365 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 365 of file G4INCLNucleus.hh
References remnant.
Referenced by fillEventInfo(), getConservationBalance(), and G4INCL::INCL::postCascade().
void G4INCL::Nucleus::initializeParticles () virtual
Call the Cluster method to generate the initial distribution of particles. At the beginning all particles are assigned as spectators.
Reimplemented from G4INCL::Cluster.
Definition at line 121 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 121 of file G4INCLNucleus.cc
References G4INCL::Store::add(), computeTotalEnergy(), e, initialCenterOfMass, initialInternalEnergy, G4INCL::Cluster::initializeParticles(), G4INCL::Cluster::particles, G4INCL::Particle::thePosition, theProjectileRemnant, theStore, and updatePotentialEnergy().
Referenced by G4INCL::INCL::initializeTarget().
void G4INCL::Nucleus::insertParticle (Particle * p) inline
Insert a new particle (e.g. a projectile) in the nucleus.
Definition at line 83 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 83 of file G4INCLNucleus.hh
References G4INCL::Particle::getA(), G4INCL::Store::getBook(), G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getS(), G4INCL::Particle::getType(), G4INCL::Particle::getZ(), G4INCL::Math::heaviside(), G4INCL::Book::incrementCascading(), G4INCL::Particle::isAntiKaon(), G4INCL::Particle::isKaon(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isPion(), G4INCL::Particle::isTargetSpectator(), G4INCL::Store::particleHasEntered(), G4INCL::Particle::theA, theNkaonminusInitial, theNkaonplusInitial, theNnInitial, theNpInitial, theNpionminusInitial, theNpionplusInitial, G4INCL::Particle::theS, theStore, and G4INCL::Particle::theZ.
Referenced by applyFinalState().
G4bool G4INCL::Nucleus::isEventTransparent () const
Is the event transparent?
To be called at the end of the cascade.
Definition at line 840 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 840 of file G4INCLNucleus.cc
References G4INCL::Book::getAcceptedCollisions(), G4INCL::Book::getAcceptedDecays(), G4INCL::Store::getBook(), G4INCL::Book::getEmittedClusters(), and theStore.
Referenced by G4INCL::INCL::postCascade().
G4bool G4INCL::Nucleus::isNucleusNucleusCollision () const inline
Is it a nucleus-nucleus collision?
Definition at line 424 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 424 of file G4INCLNucleus.hh
References isNucleusNucleus.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::SurfaceAvatar::getChannel(), and G4INCL::INCL::makeCompoundNucleus().
Nucleus& G4INCL::Nucleus::operator= (const Nucleus & rhs)
Dummy assignment operator to silence Coverity warning.
std::string G4INCL::Nucleus::print ()
Print the nucleus info
Definition at line 288 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 288 of file G4INCLNucleus.cc
References e, G4INCL::Store::getOutgoingParticles(), G4INCL::Store::getParticles(), and theStore.
void G4INCL::Nucleus::propagateParticles (G4double step)
Propagate the particles one time step.
Parameters
step length of the time step
Definition at line 214 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 214 of file G4INCLNucleus.cc
References INCL_WARN.
void G4INCL::Nucleus::setDensity (NuclearDensity const *const d) inline
Setter for theDensity.
Definition at line 463 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 463 of file G4INCLNucleus.hh
References d, G4INCL::ParticleSampler::setDensity(), theDensity, and G4INCL::Cluster::theParticleSampler.
void G4INCL::Nucleus::setIncomingAngularMomentum (const ThreeVector & j) inline
Set the incoming angular-momentum vector.
Definition at line 257 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 257 of file G4INCLNucleus.hh
References incomingAngularMomentum.
Referenced by G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
void G4INCL::Nucleus::setIncomingMomentum (const ThreeVector & p) inline
Set the incoming momentum vector.
Definition at line 265 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 265 of file G4INCLNucleus.hh
References incomingMomentum.
Referenced by G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
void G4INCL::Nucleus::setInitialEnergy (const G4double e) inline
Set the initial energy.
Definition at line 275 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 275 of file G4INCLNucleus.hh
References e, and initialEnergy.
Referenced by G4INCL::StandardPropagationModel::shootComposite(), and G4INCL::StandardPropagationModel::shootParticle().
void G4INCL::Nucleus::setNucleusNucleusCollision () inline
Set a nucleus-nucleus collision.
Definition at line 427 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 427 of file G4INCLNucleus.hh
References isNucleusNucleus.
Referenced by G4INCL::StandardPropagationModel::shootComposite().
void G4INCL::Nucleus::setParticleNucleusCollision () inline
Set a particle-nucleus collision.
Definition at line 430 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 430 of file G4INCLNucleus.hh
References isNucleusNucleus.
Referenced by G4INCL::StandardPropagationModel::shootParticle().
void G4INCL::Nucleus::setProjectileRemnant (ProjectileRemnant *const c) inline
Set the projectile remnant.
Definition at line 433 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 433 of file G4INCLNucleus.hh
References c, and theProjectileRemnant.
Referenced by G4INCL::StandardPropagationModel::shootComposite().
void G4INCL::Nucleus::setStore (Store * s) inline
Definition at line 348 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 348 of file G4INCLNucleus.hh
References theStore.
void G4INCL::Nucleus::setUniverseRadius (const G4double universeRadius) inline
Setter for theUniverseRadius.
Definition at line 421 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 421 of file G4INCLNucleus.hh
References theUniverseRadius.
void G4INCL::Nucleus::updatePotentialEnergy (Particle * p) const inline
Update the particle potential energy.
Definition at line 458 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 458 of file G4INCLNucleus.hh
References G4INCL::NuclearPotential::INuclearPotential::computePotentialEnergy(), G4INCL::Particle::setPotentialEnergy(), and thePotential.
Referenced by G4INCL::ReflectionChannel::fillFinalState(), initializeParticles(), G4INCL::InteractionAvatar::ViolationEMomentumFunctor::scaleParticleMomenta(), and G4INCL::InteractionAvatar::ViolationEEnergyFunctor::setParticleEnergy().
void G4INCL::Nucleus::useFusionKinematics ()
Adjust the kinematics for complete-fusion events.
Definition at line 1203 of file G4INCLNucleus.cc.
View newest version in sPHENIX GitHub at line 1203 of file G4INCLNucleus.cc
References G4INCL::Cluster::getTableMass(), incomingAngularMomentum, incomingMomentum, initialEnergy, G4INCL::ThreeVector::mag2(), G4INCL::Particle::setEnergy(), G4INCL::Particle::setMass(), G4INCL::Particle::setMomentum(), G4INCL::Cluster::setSpin(), G4INCL::Particle::theEnergy, G4INCL::Cluster::theExcitationEnergy, and G4INCL::Particle::theMomentum.
Referenced by G4INCL::INCL::postCascade().
Member Data Documentation
ThreeVector G4INCL::Nucleus::incomingAngularMomentum private
Definition at line 497 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 497 of file G4INCLNucleus.hh
Referenced by computeRecoilKinematics(), getIncomingAngularMomentum(), setIncomingAngularMomentum(), and useFusionKinematics().
ThreeVector G4INCL::Nucleus::incomingMomentum private
Definition at line 497 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 497 of file G4INCLNucleus.hh
Referenced by computeOneNucleonRecoilKinematics(), computeRecoilKinematics(), getIncomingMomentum(), setIncomingMomentum(), and useFusionKinematics().
ThreeVector G4INCL::Nucleus::initialCenterOfMass private
Definition at line 498 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 498 of file G4INCLNucleus.hh
Referenced by computeRecoilKinematics(), and initializeParticles().
G4double G4INCL::Nucleus::initialEnergy private
Definition at line 501 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 501 of file G4INCLNucleus.hh
Referenced by computeOneNucleonRecoilKinematics(), getInitialEnergy(), setInitialEnergy(), and useFusionKinematics().
G4double G4INCL::Nucleus::initialInternalEnergy private
Definition at line 496 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 496 of file G4INCLNucleus.hh
Referenced by computeExcitationEnergy(), getInitialInternalEnergy(), and initializeParticles().
G4bool G4INCL::Nucleus::isNucleusNucleus private
true if running a nucleus-nucleus collision
Tells INCL whether to make a projectile-like pre-fragment or not.
Definition at line 519 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 519 of file G4INCLNucleus.hh
Referenced by isNucleusNucleusCollision(), setNucleusNucleusCollision(), and setParticleNucleusCollision().
G4int G4INCL::Nucleus::projectileA private
The mass number of the projectile.
Definition at line 508 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 508 of file G4INCLNucleus.hh
G4int G4INCL::Nucleus::projectileS private
The strangeness number of the projectile.
Definition at line 510 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 510 of file G4INCLNucleus.hh
G4int G4INCL::Nucleus::projectileZ private
The charge number of the projectile.
Definition at line 506 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 506 of file G4INCLNucleus.hh
G4bool G4INCL::Nucleus::remnant private
Definition at line 499 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 499 of file G4INCLNucleus.hh
Referenced by computeRecoilKinematics(), and hasRemnant().
NuclearDensity const* G4INCL::Nucleus::theDensity private
Pointer to the NuclearDensity object.
Definition at line 528 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 528 of file G4INCLNucleus.hh
Referenced by getDensity(), getSurfaceRadius(), getTransmissionBarrier(), Nucleus(), and setDensity().
G4int G4INCL::Nucleus::theInitialA private
Definition at line 484 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 484 of file G4INCLNucleus.hh
Referenced by getInitialA().
G4int G4INCL::Nucleus::theInitialS private
Definition at line 484 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 484 of file G4INCLNucleus.hh
Referenced by getInitialS().
G4int G4INCL::Nucleus::theInitialZ private
Definition at line 484 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 484 of file G4INCLNucleus.hh
Referenced by getInitialZ().
G4int G4INCL::Nucleus::theNkaonminusInitial private
Definition at line 494 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 494 of file G4INCLNucleus.hh
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringKaons(), and insertParticle().
G4int G4INCL::Nucleus::theNkaonplusInitial private
The number of entering kaons.
Definition at line 493 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 493 of file G4INCLNucleus.hh
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringKaons(), and insertParticle().
G4int G4INCL::Nucleus::theNnInitial private
The number of entering neutrons.
Definition at line 488 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 488 of file G4INCLNucleus.hh
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringNeutrons(), and insertParticle().
G4int G4INCL::Nucleus::theNpInitial private
The number of entering protons.
Definition at line 486 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 486 of file G4INCLNucleus.hh
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringProtons(), and insertParticle().
G4int G4INCL::Nucleus::theNpionminusInitial private
Definition at line 491 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 491 of file G4INCLNucleus.hh
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringPions(), and insertParticle().
G4int G4INCL::Nucleus::theNpionplusInitial private
The number of entering pions.
Definition at line 490 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 490 of file G4INCLNucleus.hh
Referenced by computeSeparationEnergyBalance(), getNumberOfEnteringPions(), and insertParticle().
NuclearPotential::INuclearPotential const* G4INCL::Nucleus::thePotential private
Pointer to the NuclearPotential object.
Definition at line 531 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 531 of file G4INCLNucleus.hh
Referenced by computeSeparationEnergyBalance(), decayInsideDeltas(), getPotential(), getSurfaceRadius(), Nucleus(), and updatePotentialEnergy().
ProjectileRemnant* G4INCL::Nucleus::theProjectileRemnant private
Pointer to the quasi-projectile.
Owned by the Nucleus object.
Definition at line 525 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 525 of file G4INCLNucleus.hh
Referenced by computeRecoilKinematics(), deleteProjectileRemnant(), fillEventInfo(), finalizeProjectileRemnant(), getConservationBalance(), getProjectileRemnant(), initializeParticles(), and setProjectileRemnant().
Store* G4INCL::Nucleus::theStore private
Definition at line 502 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 502 of file G4INCLNucleus.hh
Referenced by applyFinalState(), computeCenterOfMass(), computeOneNucleonRecoilKinematics(), computeRecoilKinematics(), computeSeparationEnergyBalance(), computeTotalEnergy(), containsAntiKaon(), containsDeltas(), containsEtas(), containsKaon(), containsLambda(), containsOmegas(), containsSigma(), decayInsideDeltas(), decayInsideStrangeParticles(), decayMe(), decayOutgoingClusters(), decayOutgoingDeltas(), decayOutgoingNeutralKaon(), decayOutgoingPionResonances(), decayOutgoingSigmaZero(), emitInsideKaon(), emitInsideLambda(), emitInsidePions(), emitInsideStrangeParticles(), fillEventInfo(), getConservationBalance(), getStore(), initializeParticles(), insertParticle(), isEventTransparent(), Nucleus(), print(), setStore(), and ~Nucleus().
G4double G4INCL::Nucleus::theUniverseRadius private
The radius of the universe.
Definition at line 513 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 513 of file G4INCLNucleus.hh
Referenced by getUniverseRadius(), Nucleus(), and setUniverseRadius().
G4bool G4INCL::Nucleus::tryCN private
Definition at line 503 of file G4INCLNucleus.hh.
View newest version in sPHENIX GitHub at line 503 of file G4INCLNucleus.hh
Referenced by applyFinalState(), fillEventInfo(), and getTryCompoundNucleus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNucleus.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNucleus.cc