ECCE @ EIC Software: G4VPEventIO Class Reference
G4VPEventIO Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VPEventIO.hh>
Public Member Functions
G4VPEventIO ()
virtual ~G4VPEventIO ()
void SetVerboseLevel (int v)
G4int CurrentEventID ()
virtual G4bool Store (const G4Event *anEvent)=0
virtual G4bool Retrieve (G4Pevent *&anEvent)=0
virtual G4bool Retrieve (G4Event *&anEvent)=0
Protected Attributes
G4int m_verbose
G4int m_currentEvtID
Detailed Description
Definition at line 40 of file G4VPEventIO.hh.
View newest version in sPHENIX GitHub at line 40 of file G4VPEventIO.hh
Constructor & Destructor Documentation
G4VPEventIO::G4VPEventIO ()
Definition at line 34 of file G4VPEventIO.cc.
View newest version in sPHENIX GitHub at line 34 of file G4VPEventIO.cc
virtual G4VPEventIO::~G4VPEventIO () inline virtual
Definition at line 46 of file G4VPEventIO.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VPEventIO.hh
Member Function Documentation
G4int G4VPEventIO::CurrentEventID () inline
Definition at line 53 of file G4VPEventIO.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VPEventIO.hh
References m_currentEvtID.
virtual G4bool G4VPEventIO::Retrieve (G4Pevent *& anEvent) pure virtual
Referenced by G4PersistencyManager::Retrieve().
virtual G4bool G4VPEventIO::Retrieve (G4Event *& anEvent) pure virtual
void G4VPEventIO::SetVerboseLevel (int v) inline
Definition at line 50 of file G4VPEventIO.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VPEventIO.hh
References m_verbose, and v.
Referenced by G4PersistencyManager::SetVerboseLevel().
virtual G4bool G4VPEventIO::Store (const G4Event * anEvent) pure virtual
Referenced by G4PersistencyManager::Store().
Member Data Documentation
G4int G4VPEventIO::m_currentEvtID protected
Definition at line 67 of file G4VPEventIO.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VPEventIO.hh
Referenced by CurrentEventID().
G4int G4VPEventIO::m_verbose protected
Definition at line 66 of file G4VPEventIO.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VPEventIO.hh
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VPEventIO.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4VPEventIO.cc