ECCE @ EIC Software: G4VPHitIO Class Reference
G4VPHitIO Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VPHitIO.hh>
Public Member Functions
G4VPHitIO ()
virtual ~G4VPHitIO ()
G4VPHitIO * GetVPHitIO ()
virtual G4bool Store (const G4HCofThisEvent *)=0
virtual G4bool Retrieve (G4HCofThisEvent *&)=0
void SetVerboseLevel (int v)
Protected Member Functions
void SetG4VPHitIO (G4VPHitIO *hitMan)
Protected Attributes
G4int m_verbose
G4HCIOcatalog * f_catalog
Static Protected Attributes
static G4ThreadLocal G4VPHitIO * f_G4VPHitIO = 0
Detailed Description
Definition at line 41 of file G4VPHitIO.hh.
View newest version in sPHENIX GitHub at line 41 of file G4VPHitIO.hh
Constructor & Destructor Documentation
G4VPHitIO::G4VPHitIO ()
Definition at line 36 of file G4VPHitIO.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VPHitIO.cc
References f_catalog, and G4HCIOcatalog::GetHCIOcatalog().
virtual G4VPHitIO::~G4VPHitIO () inline virtual
Definition at line 47 of file G4VPHitIO.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VPHitIO.hh
Member Function Documentation
G4VPHitIO* G4VPHitIO::GetVPHitIO () inline
Definition at line 51 of file G4VPHitIO.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VPHitIO.hh
References f_G4VPHitIO.
virtual G4bool G4VPHitIO::Retrieve (G4HCofThisEvent *&) pure virtual
void G4VPHitIO::SetG4VPHitIO (G4VPHitIO * hitMan) inline protected
Definition at line 68 of file G4VPHitIO.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPHitIO.hh
References f_G4VPHitIO.
void G4VPHitIO::SetVerboseLevel (int v)
Definition at line 43 of file G4VPHitIO.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VPHitIO.cc
References f_catalog, G4HCIOcatalog::GetHCIOmanager(), m_verbose, G4HCIOcatalog::NumberOfHCIOmanager(), G4VPHitsCollectionIO::SetVerboseLevel(), and v.
Referenced by G4PersistencyManager::SetVerboseLevel().
virtual G4bool G4VPHitIO::Store (const G4HCofThisEvent *) pure virtual
Referenced by G4PersistencyManager::Store().
Member Data Documentation
G4HCIOcatalog* G4VPHitIO::f_catalog protected
Definition at line 74 of file G4VPHitIO.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VPHitIO.hh
Referenced by G4VPHitIO(), and SetVerboseLevel().
G4ThreadLocal G4VPHitIO * G4VPHitIO::f_G4VPHitIO = 0 static protected
Definition at line 73 of file G4VPHitIO.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VPHitIO.hh
Referenced by GetVPHitIO(), and SetG4VPHitIO().
G4int G4VPHitIO::m_verbose protected
Definition at line 68 of file G4VPHitIO.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPHitIO.hh
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VPHitIO.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4VPHitIO.cc