ECCE @ EIC Software: G4VisCommandGeometrySetDaughtersInvisible Class Reference
G4VisCommandGeometrySetDaughtersInvisible Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometrySet.hh>
Public Member Functions
G4VisCommandGeometrySetDaughtersInvisible ()
virtual ~G4VisCommandGeometrySetDaughtersInvisible ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Private Member Functions
G4VisCommandGeometrySetDaughtersInvisible (const G4VisCommandGeometrySetDaughtersInvisible &)
G4VisCommandGeometrySetDaughtersInvisible & operator= (const G4VisCommandGeometrySetDaughtersInvisible &)
Private Attributes
G4UIcommand * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Types inherited from G4VVisCommandGeometry
typedef std::map
< G4LogicalVolume *, const
G4VisAttributes * >
::const_iterator VisAttsMapIterator
Protected Member Functions inherited from G4VVisCommandGeometrySet
void Set (G4String logVolName, const G4VVisCommandGeometrySetFunction &, G4int requestedDepth)
void SetLVVisAtts (G4LogicalVolume *, const G4VVisCommandGeometrySetFunction &, G4int depth, G4int requestedDepth)
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommandGeometry
static std::map
< G4LogicalVolume *, const
G4VisAttributes * > fVisAttsMap
Detailed Description
Definition at line 190 of file G4VisCommandsGeometrySet.hh.
View newest version in sPHENIX GitHub at line 190 of file G4VisCommandsGeometrySet.hh
Constructor & Destructor Documentation
G4VisCommandGeometrySetDaughtersInvisible::G4VisCommandGeometrySetDaughtersInvisible ()
Definition at line 163 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 163 of file G4VisCommandsGeometrySet.cc
References fpCommand, G4UIparameter::SetDefaultValue(), G4UIparameter::SetGuidance(), G4UIcommand::SetGuidance(), and G4UIcommand::SetParameter().
G4VisCommandGeometrySetDaughtersInvisible::~G4VisCommandGeometrySetDaughtersInvisible () virtual
Definition at line 185 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 185 of file G4VisCommandsGeometrySet.cc
References fpCommand.
G4VisCommandGeometrySetDaughtersInvisible::G4VisCommandGeometrySetDaughtersInvisible (const G4VisCommandGeometrySetDaughtersInvisible &) private
Member Function Documentation
G4String G4VisCommandGeometrySetDaughtersInvisible::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 191 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 191 of file G4VisCommandsGeometrySet.cc
G4VisCommandGeometrySetDaughtersInvisible& G4VisCommandGeometrySetDaughtersInvisible::operator= (const G4VisCommandGeometrySetDaughtersInvisible &) private
void G4VisCommandGeometrySetDaughtersInvisible::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 197 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 197 of file G4VisCommandsGeometrySet.cc
References G4UIcommand::ConvertToBool(), G4cout, G4endl, G4VViewer::GetViewParameters(), G4ViewParameters::IsCulling(), G4ArrayOps::Set(), and G4VisManager::warnings.
Member Data Documentation
G4UIcommand* G4VisCommandGeometrySetDaughtersInvisible::fpCommand private
Definition at line 202 of file G4VisCommandsGeometrySet.hh.
View newest version in sPHENIX GitHub at line 202 of file G4VisCommandsGeometrySet.hh
Referenced by G4VisCommandGeometrySetDaughtersInvisible(), and ~G4VisCommandGeometrySetDaughtersInvisible().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometrySet.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsGeometrySet.cc