ECCE @ EIC Software: G4ShiftedGaussian Class Reference
G4ShiftedGaussian Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ShiftedGaussian.hh>
Public Member Functions
G4ShiftedGaussian (void)
G4ShiftedGaussian (G4int Verbosity)
G4double G4FindShiftedMean (G4double RequestedMean, G4double RequestedStdDev)
void G4InsertShiftedMean (G4double ShiftedMean, G4double RequestedMean, G4double RequestedStdDev)
void G4SetVerbosity (G4int WhatVerbosity)
~G4ShiftedGaussian (void)
Protected Member Functions
void Initialize (void)
Protected Attributes
std::vector< std::pair
< std::pair< G4double,
G4double >, G4double > > ShiftedMean_
G4int Verbosity_
Detailed Description
G4ShiftedGaussian is a class for storing the shifted values used for sampling a Gaussian distribution and returning only positive values; it is integrated into G4FPYSamplingOps
Definition at line 45 of file G4ShiftedGaussian.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ShiftedGaussian.hh
Constructor & Destructor Documentation
G4ShiftedGaussian::G4ShiftedGaussian (void)
Default constructor
Usage: No arguments required
Notes:
Definition at line 42 of file G4ShiftedGaussian.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ShiftedGaussian.cc
References Initialize(), G4FFGDefaultValues::Verbosity, and Verbosity_.
G4ShiftedGaussian::G4ShiftedGaussian (G4int Verbosity)
Overloaded constructor
Usage:
Verbosity: Verbosity level
Notes:
Definition at line 52 of file G4ShiftedGaussian.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ShiftedGaussian.cc
References Initialize(), and Verbosity_.
G4ShiftedGaussian::~G4ShiftedGaussian (void)
Default deconstructor.
Definition at line 126 of file G4ShiftedGaussian.cc.
View newest version in sPHENIX GitHub at line 126 of file G4ShiftedGaussian.cc
References G4FFG_FUNCTIONENTER__, and G4FFG_FUNCTIONLEAVE__.
Member Function Documentation
G4double G4ShiftedGaussian::G4FindShiftedMean (G4double RequestedMean, G4double RequestedStdDev)
Returns the shifted mean that correlates to a RequestedMean and RequestedStdDev pair. 0 is returned if there is no associated value.
Definition at line 72 of file G4ShiftedGaussian.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ShiftedGaussian.cc
References G4FFG_SAMPLING_FUNCTIONENTER__, G4FFG_SAMPLING_FUNCTIONLEAVE__, and ShiftedMean_.
Referenced by G4FPYSamplingOps::CheckAndSetParameters().
void G4ShiftedGaussian::G4InsertShiftedMean (G4double ShiftedMean, G4double RequestedMean, G4double RequestedStdDev)
Inserts a ShiftedMean indexed by the RequestedMean and RequestedStdDev
Definition at line 96 of file G4ShiftedGaussian.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ShiftedGaussian.cc
References G4FFG_SAMPLING_FUNCTIONENTER__, G4FFG_SAMPLING_FUNCTIONLEAVE__, and ShiftedMean_.
Referenced by G4FPYSamplingOps::ShiftParameters().
void G4ShiftedGaussian::G4SetVerbosity (G4int WhatVerbosity)
Sets the verbosity levels
Usage:
WhichVerbosity: Combination of levels
Notes:
SILENT: All verbose output is repressed
UPDATES: Only high-level internal changes are reported
DAUGHTER_INFO: Displays information about daughter product sampling
NEUTRON_INFO: Displays information about neutron sampling
GAMMA_INFO: Displays information about gamma sampling
ALPHA_INFO: Displays information about alpha sampling
MOMENTUM_INFO: Displays information about momentum balancing
EXTRAPOLATION_INTERPOLATION_INFO: Displays information about any data extrapolation or interpolation that occurs
DEBUG: Reports program flow as it steps through functions
PRINT_ALL: Displays any and all output
Definition at line 116 of file G4ShiftedGaussian.cc.
View newest version in sPHENIX GitHub at line 116 of file G4ShiftedGaussian.cc
References G4FFG_SAMPLING_FUNCTIONENTER__, G4FFG_SAMPLING_FUNCTIONLEAVE__, and Verbosity_.
Referenced by G4FPYSamplingOps::G4SetVerbosity().
void G4ShiftedGaussian::Initialize (void) protected
Initialize is a common function called by all constructors.
Definition at line 62 of file G4ShiftedGaussian.cc.
View newest version in sPHENIX GitHub at line 62 of file G4ShiftedGaussian.cc
References G4FFG_FUNCTIONENTER__, and G4FFG_FUNCTIONLEAVE__.
Referenced by G4ShiftedGaussian().
Member Data Documentation
std::vector< std::pair< std::pair< G4double, G4double >, G4double > > G4ShiftedGaussian::ShiftedMean_ protected
Contains the adjusted mean of the POSITIVE only Gaussian distribution associated with a RequestedMean and RequestedStdDev pair.
Definition at line 107 of file G4ShiftedGaussian.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ShiftedGaussian.hh
Referenced by G4FindShiftedMean(), and G4InsertShiftedMean().
G4int G4ShiftedGaussian::Verbosity_ protected
Verbosity level
Definition at line 109 of file G4ShiftedGaussian.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ShiftedGaussian.hh
Referenced by G4SetVerbosity(), and G4ShiftedGaussian().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ShiftedGaussian.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ShiftedGaussian.cc