ECCE @ EIC Software: G4VGFlashSensitiveDetector Class Reference
G4VGFlashSensitiveDetector Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/G4VGFlashSensitiveDetector.hh>
Public Member Functions
G4VGFlashSensitiveDetector ()
G4VGFlashSensitiveDetector (const G4VGFlashSensitiveDetector &)
virtual ~G4VGFlashSensitiveDetector ()
G4bool operator== (const G4VGFlashSensitiveDetector &right) const
G4bool operator!= (const G4VGFlashSensitiveDetector &right) const
G4bool Hit (G4GFlashSpot *aSpot)
Protected Member Functions
virtual G4bool ProcessHits (G4GFlashSpot *aSpot, G4TouchableHistory *ROhist)=0
Detailed Description
Definition at line 52 of file G4VGFlashSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VGFlashSensitiveDetector.hh
Constructor & Destructor Documentation
G4VGFlashSensitiveDetector::G4VGFlashSensitiveDetector () inline
Definition at line 57 of file G4VGFlashSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VGFlashSensitiveDetector.hh
G4VGFlashSensitiveDetector::G4VGFlashSensitiveDetector (const G4VGFlashSensitiveDetector &) inline
Definition at line 58 of file G4VGFlashSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VGFlashSensitiveDetector.hh
virtual G4VGFlashSensitiveDetector::~G4VGFlashSensitiveDetector () inline virtual
Definition at line 66 of file G4VGFlashSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VGFlashSensitiveDetector.hh
Member Function Documentation
G4bool G4VGFlashSensitiveDetector::Hit (G4GFlashSpot * aSpot) inline
Definition at line 75 of file G4VGFlashSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VGFlashSensitiveDetector.hh
References G4VReadOutGeometry::CheckROVolume(), FatalException, G4Exception(), G4Track::GetMomentumDirection(), G4GFlashSpot::GetOriginatorTrack(), G4GFlashSpot::GetPosition(), G4Step::GetPreStepPoint(), G4FastTrack::GetPrimaryTrack(), G4VSensitiveDetector::GetROgeometry(), G4GFlashSpot::GetTouchableHandle(), G4VSensitiveDetector::isActive(), ProcessHits(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPosition(), and G4StepPoint::SetTouchableHandle().
Referenced by GFlashHitMaker::make().
G4bool G4VGFlashSensitiveDetector::operator!= (const G4VGFlashSensitiveDetector & right) const inline
Definition at line 70 of file G4VGFlashSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 70 of file G4VGFlashSensitiveDetector.hh
References right.
G4bool G4VGFlashSensitiveDetector::operator== (const G4VGFlashSensitiveDetector & right) const inline
Definition at line 68 of file G4VGFlashSensitiveDetector.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VGFlashSensitiveDetector.hh
References right.
virtual G4bool G4VGFlashSensitiveDetector::ProcessHits (G4GFlashSpot * aSpot, G4TouchableHistory * ROhist) protected pure virtual
Implemented in ExGflash1SensitiveDetector, ExGflash2SensitiveDetector, ExGflash3SensitiveDetector, and ExGflashSensitiveDetector.
Referenced by Hit().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/G4VGFlashSensitiveDetector.hh