ECCE @ EIC Software: mcscorerootio Namespace Reference
mcscorerootio Namespace Reference
Classes
class MCScoreROOTIO
Functions
def loop_tree
def test_t2root
def test_loop
Variables
list __all__ [ 'MCScoreROOTIO', 'loop_tree' ]
Detailed Description
Python module
This module provides ROOT IO interface for MCScore data
  [C] MCScoreROOTIO
  [f] loop_tree(tfile, analyze_vertex):
                                        Q, 2006
Function Documentation
def mcscorerootio.loop_tree (tfile, analyze_vertex)
loop ROOT tree in a ROOT file.
  * analyze_vertex: user function : analyze_vertex(MCVertex)
Definition at line 112 of file mcscorerootio.py.
View newest version in sPHENIX GitHub at line 112 of file mcscorerootio.py
Referenced by test_loop().
def mcscorerootio.test_loop ()
Definition at line 174 of file mcscorerootio.py.
View newest version in sPHENIX GitHub at line 174 of file mcscorerootio.py
References loop_tree(), and test_t2root().
def mcscorerootio.test_t2root ()
Definition at line 147 of file mcscorerootio.py.
View newest version in sPHENIX GitHub at line 147 of file mcscorerootio.py
References Acts.open, and while().
Referenced by test_loop().
Variable Documentation
list mcscorerootio.__all__ [ 'MCScoreROOTIO', 'loop_tree' ]
Definition at line 20 of file mcscorerootio.py.
View newest version in sPHENIX GitHub at line 20 of file mcscorerootio.py