ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/global/management/include/G4EnvironmentUtils.hh File Reference
G4EnvironmentUtils.hh File Reference
#include <cstdlib>
#include <string>
#include <sstream>
#include <map>
#include <iostream>
#include <iomanip>
#include <mutex>
#include "G4ios.hh"
#include "G4String.hh"
#include "G4Exception.hh"
#include "G4ExceptionSeverity.hh"
Classes
class G4EnvSettings
Functions
template<typename _Tp >
_Tp G4GetEnv (const std::string &env_id, _Tp _default=_Tp())
template<>
G4bool G4GetEnv (const std::string &env_id, bool _default)
template<typename _Tp >
_Tp G4GetEnv (const std::string &env_id, _Tp _default, const std::string &msg)
G4String G4GetDataEnv (const std::string &env_id, const char *originOfException, const char *exceptionCode, G4ExceptionSeverity severity, const char *description)
void G4PrintEnv (std::ostream &os=G4cout)
Function Documentation
G4String G4GetDataEnv (const std::string & env_id, const char * originOfException, const char * exceptionCode, G4ExceptionSeverity severity, const char * description) inline
Definition at line 203 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 203 of file G4EnvironmentUtils.hh
References G4Exception(), G4EnvSettings::GetInstance(), and G4EnvSettings::insert().
template<typename _Tp > _Tp G4GetEnv (const std::string & env_id, _Tp _default = _Tp())
Definition at line 120 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 120 of file G4EnvironmentUtils.hh
References G4EnvSettings::GetInstance(), and G4EnvSettings::insert().
template<> G4bool G4GetEnv (const std::string & env_id, bool _default) inline
Definition at line 147 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 147 of file G4EnvironmentUtils.hh
References G4EnvSettings::GetInstance(), and G4EnvSettings::insert().
template<typename _Tp > _Tp G4GetEnv (const std::string & env_id, _Tp _default, const std::string & msg)
Definition at line 171 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 171 of file G4EnvironmentUtils.hh
References G4cout, G4endl, G4EnvSettings::GetInstance(), and G4EnvSettings::insert().
void G4PrintEnv (std::ostream & os = G4cout) inline
Definition at line 231 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 231 of file G4EnvironmentUtils.hh
References G4EnvSettings::GetInstance().
Referenced by TSRunAction::BeginOfRunAction().