ECCE @ EIC Software: G4DNABrownianTransportation Class Reference
G4DNABrownianTransportation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNABrownianTransportation.hh>
Classes
struct G4ITBrownianState
Public Member Functions
G4DNABrownianTransportation (const G4String &aName="DNABrownianTransportation", G4int verbosityLevel=0)
virtual ~G4DNABrownianTransportation ()
G4DNABrownianTransportation (const G4DNABrownianTransportation &)
G4DNABrownianTransportation & operator= (const G4DNABrownianTransportation &)
void SetBrownianAction (G4BrownianAction *)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void StartTracking (G4Track *aTrack)
virtual void ComputeStep (const G4Track &, const G4Step &, const double, double &)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &)
void UseMaximumTimeBeforeReachingBoundary (bool flag=true)
void UseCumulativeDensitFunction (bool flag=true)
void UseLimitingTimeSteps (bool flag=true)
void SpeedLevel (int level)
Public Member Functions inherited from G4ITTransportation
G4ITTransportation (const G4String &aName="ITTransportation", G4int verbosityLevel=0)
virtual ~G4ITTransportation ()
G4ITTransportation (const G4ITTransportation &)
G4bool IsStepLimitedByGeometry ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double, G4ForceCondition *pForceCond)
G4PropagatorInField * GetPropagatorInField ()
void SetPropagatorInField (G4PropagatorInField *pFieldPropagator)
void SetVerboseLevel (G4int verboseLevel)
G4int GetVerboseLevel () const
G4double GetThresholdWarningEnergy () const
G4double GetThresholdImportantEnergy () const
G4int GetThresholdTrials () const
void SetThresholdWarningEnergy (G4double newEnWarn)
void SetThresholdImportantEnergy (G4double newEnImp)
void SetThresholdTrials (G4int newMaxTrials)
G4double GetMaxEnergyKilled () const
G4double GetSumEnergyKilled () const
void ResetKilledStatistics (G4int report=1)
void EnableShortStepOptimisation (G4bool optimise=true)
Public Member Functions inherited from G4VITProcess
G4VITProcess (const G4String &name, G4ProcessType type=fNotDefined)
virtual ~G4VITProcess ()
G4VITProcess (const G4VITProcess &other)
G4VITProcess & operator= (const G4VITProcess &other)
G4bool operator== (const G4VITProcess &right) const
G4bool operator!= (const G4VITProcess &right) const
size_t GetProcessID () const
G4shared_ptr< G4ProcessState_Lock > GetProcessState ()
void SetProcessState (G4shared_ptr< G4ProcessState_Lock > aProcInfo)
void ResetProcessState ()
G4double GetInteractionTimeLeft ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4bool ProposesTimeStep () const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4double ComputeGeomLimit (const G4Track &track, G4double &presafety, G4double limit)
void Diffusion (const G4Track &track)
Protected Member Functions inherited from G4ITTransportation
G4bool DoesGlobalFieldExist ()
void SetInstantiateProcessState (G4bool flag)
G4bool InstantiateProcessState ()
Protected Member Functions inherited from G4VITProcess
void RetrieveProcessInfo ()
void CreateInfo ()
template<typename T >
T * GetState ()
virtual void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
virtual void ClearInteractionTimeLeft ()
virtual void ClearNumberOfInteractionLengthLeft ()
void SetInstantiateProcessState (G4bool flag)
G4bool InstantiateProcessState ()
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4bool fUseMaximumTimeBeforeReachingBoundary
G4Material * fNistWater
G4bool fUseSchedulerMinTimeSteps
G4double fInternalMinTimeStep
G4bool fSpeedMeUp
const std::vector< G4double > * fpWaterDensity
G4BrownianAction * fpBrownianAction
Protected Attributes inherited from G4ITTransportation
G4ITNavigator * fLinearNavigator
G4PropagatorInField * fFieldPropagator
G4ParticleChangeForTransport fParticleChange
G4double fThreshold_Warning_Energy
G4double fThreshold_Important_Energy
G4int fThresholdTrials
G4double fUnimportant_Energy
G4double fSumEnergyKilled
G4double fMaxEnergyKilled
G4bool fShortStepOptimisation
G4ITSafetyHelper * fpSafetyHelper
G4int fVerboseLevel
Protected Attributes inherited from G4VITProcess
G4shared_ptr< G4ProcessState > fpState
G4bool fProposesTimeStep
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Additional Inherited Members
Static Public Member Functions inherited from G4VITProcess
static const size_t & GetMaxProcessIndex ()
Detailed Description
Definition at line 108 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 108 of file G4DNABrownianTransportation.hh
Constructor & Destructor Documentation
G4DNABrownianTransportation::G4DNABrownianTransportation (const G4String & aName = "DNABrownianTransportation", G4int verbosityLevel = 0)
Definition at line 119 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 119 of file G4DNABrownianTransportation.cc
References G4NistManager::FindOrBuildMaterial(), fInternalMinTimeStep, fNistWater, fpBrownianAction, G4VITProcess::fpState, fpWaterDensity, fSpeedMeUp, fUseMaximumTimeBeforeReachingBoundary, fUseSchedulerMinTimeSteps, G4ITTransportation::fVerboseLevel, G4NistManager::Instance(), picosecond, and G4VProcess::SetProcessSubType().
G4DNABrownianTransportation::~G4DNABrownianTransportation () virtual
Definition at line 142 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 142 of file G4DNABrownianTransportation.cc
References fpBrownianAction.
G4DNABrownianTransportation::G4DNABrownianTransportation (const G4DNABrownianTransportation & right)
Definition at line 147 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 147 of file G4DNABrownianTransportation.cc
References fInternalMinTimeStep, fNistWater, fpBrownianAction, fpWaterDensity, fSpeedMeUp, fUseMaximumTimeBeforeReachingBoundary, fUseSchedulerMinTimeSteps, and G4VProcess::SetProcessSubType().
Member Function Documentation
G4VParticleChange * G4DNABrownianTransportation::AlongStepDoIt (const G4Track & track, const G4Step & step) virtual
Reimplemented from G4ITTransportation.
Definition at line 802 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 802 of file G4DNABrownianTransportation.cc
References G4ITTransportation::AlongStepDoIt(), DBL_MAX, Diffusion(), fInternalMinTimeStep, G4ITTransportation::fParticleChange, fUseSchedulerMinTimeSteps, G4ITTransportation::fVerboseLevel, G4cout, G4endl, GetIT(), GetMolecule(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4Track::GetStepLength(), G4Track::GetTrackID(), GREEN_ON_BLUE, G4MemStat::MemoryUsage(), RESET_COLOR, G4INCL::DeJongSpin::shoot(), State, G4VITProcess::theInteractionTimeLeft, x, y, and z.
G4double G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & currentSafety, G4GPILSelection * selection) virtual
Reimplemented from G4ITTransportation.
Definition at line 581 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 581 of file G4DNABrownianTransportation.cc
References G4ITTransportation::AlongStepGetPhysicalInteractionLength(), DBL_MAX, fInternalMinTimeStep, G4ITTransportation::fLinearNavigator, fSpeedMeUp, fUseMaximumTimeBeforeReachingBoundary, fUseSchedulerMinTimeSteps, G4ITTransportation::fVerboseLevel, G4BestUnit, G4cout, G4endl, G4UniformRand, G4Molecule::GetDiffusionCoefficient(), G4Track::GetGlobalTime(), G4VScheduler::GetLimitingTimeStep(), GetMolecule(), G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4Track::GetPosition(), G4Track::GetTrackID(), G4VTouchable::GetVolume(), G4Track::GetVolume(), GREEN_ON_BLUE, G4VScheduler::Instance(), InvErf(), InvErfc(), RESET_COLOR, State, G4VITProcess::theInteractionTimeLeft, and G4VTouchable::UpdateYourself().
void G4DNABrownianTransportation::BuildPhysicsTable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4ITTransportation.
Definition at line 187 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 187 of file G4DNABrownianTransportation.cc
References G4ITTransportation::BuildPhysicsTable(), G4ITTransportation::fpSafetyHelper, fpWaterDensity, G4cout, G4endl, G4Material::GetMaterial(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), G4ITSafetyHelper::InitialiseHelper(), G4DNAMolecularMaterial::Instance(), and G4VProcess::verboseLevel.
G4double G4DNABrownianTransportation::ComputeGeomLimit (const G4Track & track, G4double & presafety, G4double limit) protected
Definition at line 562 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 562 of file G4DNABrownianTransportation.cc
References G4ITSafetyHelper::CheckNextStep(), DBL_MAX, G4ITTransportation::fpSafetyHelper, GetIT(), G4Track::GetMomentumDirection(), G4StepPoint::GetPosition(), G4Step::GetPreStepPoint(), G4Track::GetStep(), G4IT::GetTrackingInfo(), G4TrackingInformation::GetTrackStateManager(), G4Track::GetVolume(), G4ITSafetyHelper::GetWorldVolume(), G4TrackStateDependent< T >::LoadTrackState(), and G4TrackStateDependent< T >::ResetTrackState().
void G4DNABrownianTransportation::ComputeStep (const G4Track & track, const G4Step & step, const double timeStep, double & spaceStep) virtual
Reimplemented from G4ITTransportation.
Definition at line 203 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 203 of file G4DNABrownianTransportation.cc
References DBL_MAX, Erfc(), FatalErrorInArgument, fUseMaximumTimeBeforeReachingBoundary, fUseSchedulerMinTimeSteps, G4ITTransportation::fVerboseLevel, G4BestUnit, G4cout, G4endl, G4Exception(), G4UniformRand, G4Molecule::GetDiffusionCoefficient(), G4StepPoint::GetGlobalTime(), GetIT(), G4Track::GetMaterial(), GetMolecule(), G4Track::GetMomentumDirection(), G4Molecule::GetName(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4Material::GetTemperature(), G4Track::GetTrackID(), GREEN_ON_BLUE, InvErfc(), CLHEP::Hep3Vector::mag(), molecule(), G4VITProcess::ProposesTimeStep(), RESET_COLOR, G4INCL::DeJongSpin::shoot(), State, x, y, and z.
void G4DNABrownianTransportation::Diffusion (const G4Track & track) protected
Definition at line 474 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 474 of file G4DNABrownianTransportation.cc
References G4ITTransportation::fParticleChange, fpBrownianAction, fStopAndKill, G4ITTransportation::fVerboseLevel, G4BestUnit, G4cout, G4endl, G4RandomDirection(), G4Track::GetCurrentStepNumber(), G4Track::GetGlobalTime(), G4Material::GetIndex(), GetIT(), G4Track::GetMaterial(), GetMolecule(), G4IT::GetName(), G4Molecule::GetName(), G4Track::GetTrackID(), GREEN_ON_BLUE, material(), G4MemStat::MemoryUsage(), G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), RESET_COLOR, G4ParticleChangeForTransport::SetMomentumChanged(), State, and G4BrownianAction::Transport().
Referenced by AlongStepDoIt().
G4DNABrownianTransportation & G4DNABrownianTransportation::operator= (const G4DNABrownianTransportation & rhs)
Definition at line 162 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 162 of file G4DNABrownianTransportation.cc
G4VParticleChange * G4DNABrownianTransportation::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Reimplemented from G4ITTransportation.
Definition at line 450 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 450 of file G4DNABrownianTransportation.cc
References G4ITTransportation::fParticleChange, G4ITTransportation::fVerboseLevel, G4BestUnit, G4cout, G4endl, G4Step::GetDeltaTime(), G4Track::GetGlobalTime(), GetMolecule(), G4Molecule::GetName(), G4Step::GetStepLength(), G4Track::GetTrackID(), GREEN_ON_BLUE, G4ITTransportation::PostStepDoIt(), and RESET_COLOR.
void G4DNABrownianTransportation::SetBrownianAction (G4BrownianAction * brownianAction) inline
Definition at line 242 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 242 of file G4DNABrownianTransportation.hh
References fpBrownianAction.
void G4DNABrownianTransportation::SpeedLevel (int level) inline
Definition at line 171 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 171 of file G4DNABrownianTransportation.hh
References fSpeedMeUp, and fUseSchedulerMinTimeSteps.
void G4DNABrownianTransportation::StartTracking (G4Track * aTrack) virtual
Reimplemented from G4ITTransportation.
Definition at line 178 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 178 of file G4DNABrownianTransportation.cc
References G4VITProcess::fpState, G4ITTransportation::SetInstantiateProcessState(), and G4ITTransportation::StartTracking().
void G4DNABrownianTransportation::UseCumulativeDensitFunction (bool flag = true) inline
Definition at line 155 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 155 of file G4DNABrownianTransportation.hh
References fUseMaximumTimeBeforeReachingBoundary.
void G4DNABrownianTransportation::UseLimitingTimeSteps (bool flag = true) inline
Definition at line 166 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 166 of file G4DNABrownianTransportation.hh
References fUseSchedulerMinTimeSteps.
void G4DNABrownianTransportation::UseMaximumTimeBeforeReachingBoundary (bool flag = true) inline
Definition at line 146 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 146 of file G4DNABrownianTransportation.hh
References fUseMaximumTimeBeforeReachingBoundary.
Member Data Documentation
G4double G4DNABrownianTransportation::fInternalMinTimeStep protected
Definition at line 232 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 232 of file G4DNABrownianTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and G4DNABrownianTransportation().
G4Material* G4DNABrownianTransportation::fNistWater protected
Definition at line 229 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 229 of file G4DNABrownianTransportation.hh
Referenced by G4DNABrownianTransportation().
G4BrownianAction* G4DNABrownianTransportation::fpBrownianAction protected
Definition at line 238 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 238 of file G4DNABrownianTransportation.hh
Referenced by Diffusion(), G4DNABrownianTransportation(), SetBrownianAction(), and ~G4DNABrownianTransportation().
const std::vector<G4double>* G4DNABrownianTransportation::fpWaterDensity protected
Definition at line 236 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 236 of file G4DNABrownianTransportation.hh
Referenced by BuildPhysicsTable(), and G4DNABrownianTransportation().
G4bool G4DNABrownianTransportation::fSpeedMeUp protected
Definition at line 233 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 233 of file G4DNABrownianTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation(), and SpeedLevel().
G4bool G4DNABrownianTransportation::fUseMaximumTimeBeforeReachingBoundary protected
Definition at line 228 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 228 of file G4DNABrownianTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), ComputeStep(), G4DNABrownianTransportation(), UseCumulativeDensitFunction(), and UseMaximumTimeBeforeReachingBoundary().
G4bool G4DNABrownianTransportation::fUseSchedulerMinTimeSteps protected
Definition at line 231 of file G4DNABrownianTransportation.hh.
View newest version in sPHENIX GitHub at line 231 of file G4DNABrownianTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), ComputeStep(), G4DNABrownianTransportation(), SpeedLevel(), and UseLimitingTimeSteps().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNABrownianTransportation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/src/G4DNABrownianTransportation.cc