ECCE @ EIC Software: MarshaledG4String Class Reference
MarshaledG4String Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/MarshaledG4String.h>
Public Member Functions
MarshaledG4String (G4String *objptr)
MarshaledG4String (void *buf, char isUnmarshaling= 'u')
~MarshaledG4String ()
G4String * unmarshal ()
void unmarshalTo (G4String *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4String (G4String *objptr)
MarshaledG4String (void *buf, char chIsUnmarshaling= 'u')
~MarshaledG4String ()
G4String * unmarshal ()
void unmarshalTo (G4String *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4String (G4String *objptr)
MarshaledG4String (void *buf, char isUnmarshaling= 'u')
~MarshaledG4String ()
G4String * unmarshal ()
void unmarshalTo (G4String *obj)
void marshal1 ()
void unmarshal1 ()
MarshaledG4String (G4String *objptr)
MarshaledG4String (void *buf, char chIsUnmarshaling= 'u')
~MarshaledG4String ()
G4String * unmarshal ()
void unmarshalTo (G4String *obj)
void marshal1 ()
void unmarshal1 ()
Public Member Functions inherited from MarshaledObj
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
MarshaledObj ()
MarshaledObj (void *buf, char chIsUnmarshaling)
~MarshaledObj ()
bool isUnmarshaling ()
void EXTEND_BUFFER (int size)
void resizeBuffer (size_t new_size)
int getBufferSize ()
char * getBuffer ()
void marshalPrimitive (void *p, int size)
void unmarshalPrimitive (void *p, int size)
Public Attributes
G4String * param
ShadowedMarshaledG4String * Shadowed_param
Additional Inherited Members
Static Public Member Functions inherited from MarshaledObj
static int ROUND_UP (int x)
static int ROUND_UP (int x)
Protected Attributes inherited from MarshaledObj
int msh_typechoice
char * msh_buffer
char * msh_field_begin
size_t msh_size
char * msh_cursor
size_t msh_extent
bool msh_isUnmarshalDone
Detailed Description
Definition at line 23 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 23 of file MarshaledG4String.h
Constructor & Destructor Documentation
MarshaledG4String::MarshaledG4String (G4String * objptr) inline
Definition at line 32 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 32 of file MarshaledG4String.h
References marshal1(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledG4String::MarshaledG4String (void * buf, char isUnmarshaling = 'u') inline
Definition at line 42 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 42 of file MarshaledG4String.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledG4String::~MarshaledG4String () inline
Definition at line 47 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 47 of file MarshaledG4String.h
MarshaledG4String::MarshaledG4String (G4String * objptr) inline
Definition at line 30 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 30 of file MarshaledG4String.h
References marshal1(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledG4String::MarshaledG4String (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 40 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 40 of file MarshaledG4String.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledG4String::~MarshaledG4String () inline
Definition at line 45 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 45 of file MarshaledG4String.h
MarshaledG4String::MarshaledG4String (G4String * objptr) inline
Definition at line 32 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 32 of file MarshaledG4String.h
References marshal1(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledG4String::MarshaledG4String (void * buf, char isUnmarshaling = 'u') inline
Definition at line 42 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 42 of file MarshaledG4String.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledG4String::~MarshaledG4String () inline
Definition at line 47 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 47 of file MarshaledG4String.h
MarshaledG4String::MarshaledG4String (G4String * objptr) inline
Definition at line 29 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 29 of file MarshaledG4String.h
References marshal1(), MarshaledObj::msh_isUnmarshalDone, param, and Shadowed_param.
MarshaledG4String::MarshaledG4String (void * buf, char chIsUnmarshaling = 'u') inline
Definition at line 39 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 39 of file MarshaledG4String.h
References MarshaledObj::msh_isUnmarshalDone.
MarshaledG4String::~MarshaledG4String () inline
Definition at line 44 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 44 of file MarshaledG4String.h
Member Function Documentation
void MarshaledG4String::marshal1 () inline
Definition at line 81 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 81 of file MarshaledG4String.h
References MarshaledObj::EXTEND_BUFFER(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
void MarshaledG4String::marshal1 () inline
Definition at line 82 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 82 of file MarshaledG4String.h
References MarshaledObj::EXTEND_BUFFER(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
void MarshaledG4String::marshal1 () inline
Definition at line 84 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 84 of file MarshaledG4String.h
References MarshaledObj::EXTEND_BUFFER(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
void MarshaledG4String::marshal1 () inline
Definition at line 84 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 84 of file MarshaledG4String.h
References MarshaledObj::EXTEND_BUFFER(), int(), MarshaledObj::isUnmarshaling(), MarshaledObj::msh_buffer, MarshaledObj::msh_cursor, MarshaledObj::msh_field_begin, MSH_SET_TOTALSIZE, MSH_SET_TYPECHOICE, MarshaledObj::msh_size, MarshaledObj::msh_typechoice, param, and tmp.
Referenced by MarshaledG4String().
G4String* MarshaledG4String::unmarshal () inline
Definition at line 50 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 50 of file MarshaledG4String.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
G4String* MarshaledG4String::unmarshal () inline
Definition at line 51 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 51 of file MarshaledG4String.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
G4String* MarshaledG4String::unmarshal () inline
Definition at line 53 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 53 of file MarshaledG4String.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
G4String* MarshaledG4String::unmarshal () inline
Definition at line 53 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 53 of file MarshaledG4String.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
void MarshaledG4String::unmarshal1 () inline
Definition at line 123 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 123 of file MarshaledG4String.h
References int(), MarshaledObj::msh_cursor, param, and sc.
void MarshaledG4String::unmarshal1 () inline
Definition at line 123 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 123 of file MarshaledG4String.h
References int(), MarshaledObj::msh_cursor, and param.
Referenced by unmarshal(), and unmarshalTo().
void MarshaledG4String::unmarshal1 () inline
Definition at line 123 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 123 of file MarshaledG4String.h
References int(), MarshaledObj::msh_cursor, and param.
void MarshaledG4String::unmarshal1 () inline
Definition at line 124 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 124 of file MarshaledG4String.h
References int(), MarshaledObj::msh_cursor, and param.
void MarshaledG4String::unmarshalTo (G4String * obj) inline
Definition at line 67 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 67 of file MarshaledG4String.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
void MarshaledG4String::unmarshalTo (G4String * obj) inline
Definition at line 68 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 68 of file MarshaledG4String.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
void MarshaledG4String::unmarshalTo (G4String * obj) inline
Definition at line 70 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 70 of file MarshaledG4String.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
Referenced by MarshaledG4VHitsCollection::unmarshal1(), and MarshaledG4VHitsCollection::unmarshal2().
void MarshaledG4String::unmarshalTo (G4String * obj) inline
Definition at line 70 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 70 of file MarshaledG4String.h
References MSH_HEADER_SIZE, MarshaledObj::msh_isUnmarshalDone, MarshaledObj::msh_size, param, Shadowed_param, and unmarshal1().
Member Data Documentation
G4String * MarshaledG4String::param
Definition at line 25 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 25 of file MarshaledG4String.h
Referenced by marshal1(), MarshaledG4String(), unmarshal(), unmarshal1(), and unmarshalTo().
ShadowedMarshaledG4String * MarshaledG4String::Shadowed_param
Definition at line 26 of file MarshaledG4String.h.
View newest version in sPHENIX GitHub at line 26 of file MarshaledG4String.h
Referenced by MarshaledG4String(), unmarshal(), and unmarshalTo().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/MarshaledG4String.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/MarshaledG4String.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/AnnotatedFiles/MarshaledG4String.h
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/MarshaledG4String.h