ECCE @ EIC Software: G4DCIOcatalog Class Reference
G4DCIOcatalog Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4DCIOcatalog.hh>
Public Member Functions
G4DCIOcatalog ()
virtual ~G4DCIOcatalog ()
void SetVerboseLevel (int v)
void RegisterEntry (G4VDCIOentry *d)
void RegisterDCIOmanager (G4VPDigitsCollectionIO *d)
G4VDCIOentry * GetEntry (std::string name)
G4VPDigitsCollectionIO * GetDCIOmanager (std::string name)
void PrintEntries ()
std::string CurrentDCIOmanager ()
void PrintDCIOmanager ()
size_t NumberOfDCIOmanager ()
G4VPDigitsCollectionIO * GetDCIOmanager (int n)
Static Public Member Functions
static G4DCIOcatalog * GetDCIOcatalog ()
Private Attributes
int m_verbose
DCIOmap theCatalog
DCIOstore theStore
Static Private Attributes
static G4ThreadLocal
G4DCIOcatalog * f_thePointer = 0
Detailed Description
Definition at line 47 of file G4DCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 47 of file G4DCIOcatalog.hh
Constructor & Destructor Documentation
G4DCIOcatalog::G4DCIOcatalog ()
Definition at line 39 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 39 of file G4DCIOcatalog.cc
Referenced by GetDCIOcatalog().
virtual G4DCIOcatalog::~G4DCIOcatalog () inline virtual
Definition at line 53 of file G4DCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 53 of file G4DCIOcatalog.hh
Member Function Documentation
std::string G4DCIOcatalog::CurrentDCIOmanager ()
Definition at line 116 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 116 of file G4DCIOcatalog.cc
References it, and theStore.
Referenced by G4PersistencyCenter::CurrentDCIOmanager().
G4DCIOcatalog * G4DCIOcatalog::GetDCIOcatalog () static
Definition at line 44 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 44 of file G4DCIOcatalog.cc
References f_thePointer, and G4DCIOcatalog().
Referenced by G4PersistencyCenter::AddDCIOmanager(), G4DCIOentryT< T >::CreateDCIOmanager(), G4PersistencyCenter::CurrentDCIOmanager(), G4VDCIOentry::G4VDCIOentry(), G4VPDigitIO::G4VPDigitIO(), G4PersistencyCenter::PrintAll(), and G4PersistencyManager::SetVerboseLevel().
G4VPDigitsCollectionIO * G4DCIOcatalog::GetDCIOmanager (std::string name)
Definition at line 92 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 92 of file G4DCIOcatalog.cc
References G4cout, G4endl, and theStore.
Referenced by G4VPDigitIO::SetVerboseLevel(), and G4PersistencyManager::SetVerboseLevel().
G4VPDigitsCollectionIO * G4DCIOcatalog::GetDCIOmanager (int n)
Definition at line 139 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 139 of file G4DCIOcatalog.cc
References it, and theStore.
G4VDCIOentry * G4DCIOcatalog::GetEntry (std::string name)
Definition at line 79 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 79 of file G4DCIOcatalog.cc
References G4cout, G4endl, and theCatalog.
Referenced by G4PersistencyCenter::AddDCIOmanager().
size_t G4DCIOcatalog::NumberOfDCIOmanager () inline
Definition at line 84 of file G4DCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DCIOcatalog.hh
References theStore.
Referenced by G4VPDigitIO::SetVerboseLevel(), and G4PersistencyManager::SetVerboseLevel().
void G4DCIOcatalog::PrintDCIOmanager ()
Definition at line 127 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 127 of file G4DCIOcatalog.cc
References G4cout, G4endl, it, and theStore.
Referenced by G4DCIOentryT< T >::CreateDCIOmanager(), and G4PersistencyCenter::PrintAll().
void G4DCIOcatalog::PrintEntries ()
Definition at line 105 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 105 of file G4DCIOcatalog.cc
References G4cout, G4endl, it, and theCatalog.
Referenced by G4PersistencyCenter::PrintAll().
void G4DCIOcatalog::RegisterDCIOmanager (G4VPDigitsCollectionIO * d)
Definition at line 65 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 65 of file G4DCIOcatalog.cc
References d, G4VPDigitsCollectionIO::DMname(), G4cout, G4endl, m_verbose, and theStore.
Referenced by G4DCIOentryT< T >::CreateDCIOmanager().
void G4DCIOcatalog::RegisterEntry (G4VDCIOentry * d)
Definition at line 51 of file G4DCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 51 of file G4DCIOcatalog.cc
References d, G4cout, G4endl, G4VDCIOentry::GetName(), m_verbose, and theCatalog.
Referenced by G4VDCIOentry::G4VDCIOentry().
void G4DCIOcatalog::SetVerboseLevel (int v) inline
Definition at line 60 of file G4DCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 60 of file G4DCIOcatalog.hh
References m_verbose, and v.
Referenced by G4PersistencyManager::SetVerboseLevel().
Member Data Documentation
G4ThreadLocal G4DCIOcatalog * G4DCIOcatalog::f_thePointer = 0 static private
Definition at line 92 of file G4DCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 92 of file G4DCIOcatalog.hh
Referenced by GetDCIOcatalog().
int G4DCIOcatalog::m_verbose private
Definition at line 91 of file G4DCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 91 of file G4DCIOcatalog.hh
Referenced by RegisterDCIOmanager(), RegisterEntry(), and SetVerboseLevel().
DCIOmap G4DCIOcatalog::theCatalog private
Definition at line 93 of file G4DCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 93 of file G4DCIOcatalog.hh
Referenced by GetEntry(), PrintEntries(), and RegisterEntry().
DCIOstore G4DCIOcatalog::theStore private
Definition at line 94 of file G4DCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 94 of file G4DCIOcatalog.hh
Referenced by CurrentDCIOmanager(), GetDCIOmanager(), NumberOfDCIOmanager(), PrintDCIOmanager(), and RegisterDCIOmanager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4DCIOcatalog.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4DCIOcatalog.cc