ECCE @ EIC Software: G4ParticleHPElasticFS Class Reference
G4ParticleHPElasticFS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPElasticFS.hh>
Public Member Functions
G4ParticleHPElasticFS ()
~G4ParticleHPElasticFS ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &aFSType, G4ParticleDefinition *)
G4HadFinalState * ApplyYourself (const G4HadProjectile &theTrack)
G4ParticleHPFinalState * New ()
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
virtual G4double GetXsec (G4double)
virtual G4ParticleHPVector * GetXsec ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Private Attributes
G4int repFlag
G4double tE_of_repFlag3
G4double targetMass
G4int frameFlag
G4ParticleHPLegendreStore * theCoefficients
G4ParticleHPPartial * theProbArray
G4ParticleHPInterpolator theInt
G4ParticleHPFastLegendre theLegend
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Detailed Description
Definition at line 46 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPElasticFS.hh
Constructor & Destructor Documentation
G4ParticleHPElasticFS::G4ParticleHPElasticFS () inline
Definition at line 50 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPElasticFS.hh
References frameFlag, G4ParticleHPFinalState::hasXsec, repFlag, targetMass, tE_of_repFlag3, theCoefficients, and theProbArray.
Referenced by New().
G4ParticleHPElasticFS::~G4ParticleHPElasticFS () inline
Definition at line 61 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPElasticFS.hh
References theCoefficients, and theProbArray.
Member Function Documentation
G4HadFinalState * G4ParticleHPElasticFS::ApplyYourself (const G4HadProjectile & theTrack) virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 194 of file G4ParticleHPElasticFS.cc.
View newest version in sPHENIX GitHub at line 194 of file G4ParticleHPElasticFS.cc
References G4HadFinalState::AddSecondary(), CLHEP::HepLorentzVector::boost(), G4HadFinalState::Clear(), denom, CLHEP::HepLorentzVector::e(), Acts::eT, CLHEP::HepLorentzVector::findBoostToCM(), frameFlag, G4cout, G4endl, G4UniformRand, G4Cache< VALTYPE >::Get(), G4HadProjectile::Get4Momentum(), G4Nucleus::GetBiasedThermalNucleus(), G4HadProjectile::GetDefinition(), G4Pow::GetInstance(), G4IonTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4ReactionProduct::GetKineticEnergy(), G4ReactionProduct::GetMass(), G4HadProjectile::GetMaterial(), G4ReactionProduct::GetMomentum(), G4ParticleDefinition::GetPDGMass(), G4Material::GetTemperature(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), G4ReactionProduct::Lorentz(), phi, G4Pow::powA(), proj, G4Cache< VALTYPE >::Put(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), ratio, repFlag, G4ParticleHPPartial::Sample(), G4ParticleHPLegendreStore::SampleElastic(), G4DynamicParticle::SetDefinition(), G4HadFinalState::SetEnergyChange(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4DynamicParticle::SetMomentum(), G4HadFinalState::SetMomentumChange(), G4HadFinalState::SetStatusChange(), G4ReactionProduct::SetTotalEnergy(), CLHEP::HepLorentzVector::setVect(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), suspend, targ, targetMass, tE_of_repFlag3, G4ParticleHPFinalState::theBaseA, G4ParticleHPFinalState::theBaseZ, theCoefficients, theProbArray, G4ParticleHPFinalState::theResult, theta(), theTarget, twopi, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and CLHEP::Hep3Vector::x().
void G4ParticleHPElasticFS::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & aFSType, G4ParticleDefinition *) virtual
Implements G4ParticleHPFinalState.
Definition at line 54 of file G4ParticleHPElasticFS.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPElasticFS.cc
References kdfinder::abs(), G4ParticleHPPartial::DoneSetXY(), e, energy, eV, INPUTHEPMC::filename, frameFlag, G4cout, G4endl, G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPFinalState::hasAnyData, G4ParticleHPFinalState::hasFSData, G4ParticleHPFinalState::hasXsec, in, G4ParticleHPLegendreStore::Init(), G4ParticleHPPartial::InitInterpolation(), G4ParticleHPLegendreStore::InitInterpolation(), repFlag, G4ParticleHPFinalState::SetAZMs(), G4ParticleHPLegendreStore::SetCoeff(), G4ParticleHPPartial::SetT(), G4ParticleHPLegendreStore::SetTemperature(), G4ParticleHPPartial::SetX(), G4ParticleHPPartial::SetY(), targetMass, tE_of_repFlag3, theCoefficients, G4ParticleHPFinalState::theNames, G4ParticleHPFinalState::theNDLDataA, G4ParticleHPFinalState::theNDLDataM, G4ParticleHPFinalState::theNDLDataZ, and theProbArray.
G4ParticleHPFinalState* G4ParticleHPElasticFS::New () inline virtual
Implements G4ParticleHPFinalState.
Definition at line 68 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPElasticFS.hh
References G4ParticleHPElasticFS().
Member Data Documentation
G4int G4ParticleHPElasticFS::frameFlag private
Definition at line 79 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPElasticFS.hh
Referenced by ApplyYourself(), G4ParticleHPElasticFS(), and Init().
G4int G4ParticleHPElasticFS::repFlag private
Definition at line 75 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ParticleHPElasticFS.hh
Referenced by ApplyYourself(), G4ParticleHPElasticFS(), and Init().
G4double G4ParticleHPElasticFS::targetMass private
Definition at line 78 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleHPElasticFS.hh
Referenced by ApplyYourself(), G4ParticleHPElasticFS(), and Init().
G4double G4ParticleHPElasticFS::tE_of_repFlag3 private
Definition at line 77 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPElasticFS.hh
Referenced by ApplyYourself(), G4ParticleHPElasticFS(), and Init().
G4ParticleHPLegendreStore* G4ParticleHPElasticFS::theCoefficients private
Definition at line 81 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleHPElasticFS.hh
Referenced by ApplyYourself(), G4ParticleHPElasticFS(), Init(), and ~G4ParticleHPElasticFS().
G4ParticleHPInterpolator G4ParticleHPElasticFS::theInt private
Definition at line 83 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPElasticFS.hh
G4ParticleHPFastLegendre G4ParticleHPElasticFS::theLegend private
Definition at line 85 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPElasticFS.hh
G4ParticleHPPartial* G4ParticleHPElasticFS::theProbArray private
Definition at line 82 of file G4ParticleHPElasticFS.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPElasticFS.hh
Referenced by ApplyYourself(), G4ParticleHPElasticFS(), Init(), and ~G4ParticleHPElasticFS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPElasticFS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPElasticFS.cc