ECCE @ EIC Software: G4AntiNeutronAnnihilationAtRest Class Reference
G4AntiNeutronAnnihilationAtRest Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4AntiNeutronAnnihilationAtRest.hh>
Public Member Functions
G4AntiNeutronAnnihilationAtRest (const G4String &processName="AntiNeutronAnnihilationAtRest", G4ProcessType aType=fHadronic)
~G4AntiNeutronAnnihilationAtRest ()
G4bool IsApplicable (const G4ParticleDefinition &)
void PreparePhysicsTable (const G4ParticleDefinition &)
void BuildPhysicsTable (const G4ParticleDefinition &)
G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
G4double GetMeanLifeTime (const G4Track &, G4ForceCondition *)
G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
G4int GetNumberOfSecondaries ()
G4GHEKinematicsVector * GetSecondaryKinematics ()
Public Member Functions inherited from G4VRestProcess
G4VRestProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestProcess (G4VRestProcess &)
virtual ~G4VRestProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double, G4ForceCondition *)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4AntiNeutronAnnihilationAtRest & operator= (const G4AntiNeutronAnnihilationAtRest &right)
G4AntiNeutronAnnihilationAtRest (const G4AntiNeutronAnnihilationAtRest &)
void GenerateSecondaries ()
void Poisso (G4float, G4int *)
void Normal (G4float *)
void AntiNeutronAnnihilation (G4int *)
G4double ExNu (G4float)
G4int NFac (G4int)
Private Attributes
G4float globalTime
G4float targetAtomicMass
G4float targetCharge
G4GHEKinematicsVector * pv
G4GHEKinematicsVector * eve
G4GHEKinematicsVector * gkin
G4float evapEnergy1
G4float evapEnergy3
G4int ngkine
G4int ntot
G4GHEKinematicsVector result
G4float massPionMinus
G4float massPionZero
G4float massPionPlus
G4float massGamma
G4float massAntiNeutron
G4float massNeutron
G4ParticleDefinition * pdefGamma
G4ParticleDefinition * pdefPionPlus
G4ParticleDefinition * pdefPionZero
G4ParticleDefinition * pdefPionMinus
G4ParticleDefinition * pdefProton
G4ParticleDefinition * pdefNeutron
G4ParticleDefinition * pdefAntiNeutron
G4ParticleDefinition * pdefDeuteron
G4ParticleDefinition * pdefTriton
G4ParticleDefinition * pdefAlpha
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 46 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 46 of file G4AntiNeutronAnnihilationAtRest.hh
Constructor & Destructor Documentation
G4AntiNeutronAnnihilationAtRest::G4AntiNeutronAnnihilationAtRest (const G4AntiNeutronAnnihilationAtRest &) private
G4AntiNeutronAnnihilationAtRest::G4AntiNeutronAnnihilationAtRest (const G4String & processName = "AntiNeutronAnnihilationAtRest", G4ProcessType aType = fHadronic)
Definition at line 45 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 45 of file G4AntiNeutronAnnihilationAtRest.cc
References evapEnergy1, evapEnergy3, eve, fHadronAtRest, G4cout, G4endl, G4HadronicDeprecate, G4VProcess::GetProcessName(), gkin, globalTime, G4HadronicProcessStore::Instance(), MAX_SECONDARIES, ngkine, ntot, pv, G4HadronicProcessStore::RegisterExtraProcess(), G4VProcess::SetProcessSubType(), targetAtomicMass, targetCharge, and G4VProcess::verboseLevel.
G4AntiNeutronAnnihilationAtRest::~G4AntiNeutronAnnihilationAtRest ()
Definition at line 82 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 82 of file G4AntiNeutronAnnihilationAtRest.cc
References G4HadronicProcessStore::DeRegisterExtraProcess(), eve, gkin, G4HadronicProcessStore::Instance(), and pv.
Member Function Documentation
void G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation (G4int * nopt) private
Definition at line 414 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 414 of file G4AntiNeutronAnnihilationAtRest.cc
References e, evapEnergy1, evapEnergy3, eve, ExNu(), f, G4Exp(), G4Log(), G4UniformRand, G4GHEKinematicsVector::GetParticleDef(), G4ParticleDefinition::GetPDGMass(), G4GHEKinematicsVector::GetTOF(), GeV, inve, massAntiNeutron, massGamma, massNeutron, massPionMinus, massPionPlus, massPionZero, MAX_SECONDARIES, Normal(), ntot, pdefAlpha, pdefDeuteron, pdefGamma, pdefNeutron, pdefPionMinus, pdefPionPlus, pdefPionZero, pdefProton, pdefTriton, Poisso(), pv, ran(), result, G4GHEKinematicsVector::SetEnergy(), G4GHEKinematicsVector::SetEnergyAndUpdate(), G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), G4GHEKinematicsVector::SetMass(), G4GHEKinematicsVector::SetMomentumAndUpdate(), G4GHEKinematicsVector::SetParticleDef(), G4GHEKinematicsVector::SetTOF(), G4GHEKinematicsVector::SetZero(), targ, targetAtomicMass, targetCharge, x, y, and z.
Referenced by GenerateSecondaries().
G4VParticleChange * G4AntiNeutronAnnihilationAtRest::AtRestDoIt (const G4Track & track, const G4Step &) virtual
Reimplemented from G4VRestProcess.
Definition at line 150 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 150 of file G4AntiNeutronAnnihilationAtRest.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, fStopAndKill, G4cout, G4endl, G4UniformRand, GenerateSecondaries(), G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Track::GetGlobalTime(), G4Track::GetMaterial(), G4Material::GetNumberOfElements(), G4Track::GetPosition(), G4GHEKinematicsVector::GetTOF(), G4Track::GetTouchableHandle(), GeV, gkin, globalTime, G4ParticleChange::Initialize(), momentum, ngkine, G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4VProcess::ResetNumberOfInteractionLengthLeft(), G4DynamicParticle::SetDefinition(), G4DynamicParticle::SetMomentum(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), targetAtomicMass, targetCharge, and G4VProcess::verboseLevel.
G4double G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) virtual
Reimplemented from G4VRestProcess.
Definition at line 124 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 124 of file G4AntiNeutronAnnihilationAtRest.cc
References G4VProcess::currentInteractionLength, G4DynamicParticle::DumpInfo(), G4cout, G4endl, G4Track::GetDynamicParticle(), G4Track::GetMaterial(), GetMeanLifeTime(), G4Material::GetName(), G4VProcess::GetProcessName(), NotForced, ns, G4VProcess::ResetNumberOfInteractionLengthLeft(), G4VProcess::theNumberOfInteractionLengthLeft, and G4VProcess::verboseLevel.
void G4AntiNeutronAnnihilationAtRest::BuildPhysicsTable (const G4ParticleDefinition & p) virtual
Reimplemented from G4VProcess.
Definition at line 95 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 95 of file G4AntiNeutronAnnihilationAtRest.cc
References G4HadronicProcessStore::Instance(), and G4HadronicProcessStore::PrintInfo().
G4double G4AntiNeutronAnnihilationAtRest::ExNu (G4float ek1) private
Definition at line 668 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 668 of file G4AntiNeutronAnnihilationAtRest.cc
References evapEnergy1, evapEnergy3, f, G4Exp(), G4Log(), G4UniformRand, Normal(), targetAtomicMass, and targetCharge.
Referenced by AntiNeutronAnnihilation().
void G4AntiNeutronAnnihilationAtRest::GenerateSecondaries () private
Definition at line 238 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 238 of file G4AntiNeutronAnnihilationAtRest.cc
References AntiNeutronAnnihilation(), e, eve, G4GHEKinematicsVector::GetParticleDef(), G4GHEKinematicsVector::GetTOF(), gkin, globalTime, massAntiNeutron, MAX_SECONDARIES, min, ngkine, ntot, pdefAntiNeutron, pv, result, G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), G4GHEKinematicsVector::SetMass(), G4GHEKinematicsVector::SetParticleDef(), G4GHEKinematicsVector::SetTOF(), and G4GHEKinematicsVector::SetZero().
Referenced by AtRestDoIt().
G4double G4AntiNeutronAnnihilationAtRest::GetMeanLifeTime (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VRestProcess.
Definition at line 71 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 71 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AtRestGetPhysicalInteractionLength().
G4int G4AntiNeutronAnnihilationAtRest::GetNumberOfSecondaries ()
Definition at line 111 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 111 of file G4AntiNeutronAnnihilationAtRest.cc
References ngkine.
G4GHEKinematicsVector * G4AntiNeutronAnnihilationAtRest::GetSecondaryKinematics ()
Definition at line 118 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 118 of file G4AntiNeutronAnnihilationAtRest.cc
References gkin.
G4bool G4AntiNeutronAnnihilationAtRest::IsApplicable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 102 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 102 of file G4AntiNeutronAnnihilationAtRest.cc
References pdefAntiNeutron.
G4int G4AntiNeutronAnnihilationAtRest::NFac (G4int n) private
Definition at line 381 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 381 of file G4AntiNeutronAnnihilationAtRest.cc
References n.
Referenced by Poisso().
void G4AntiNeutronAnnihilationAtRest::Normal (G4float * ran) private
Definition at line 405 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 405 of file G4AntiNeutronAnnihilationAtRest.cc
References G4UniformRand.
Referenced by AntiNeutronAnnihilation(), ExNu(), and Poisso().
G4AntiNeutronAnnihilationAtRest& G4AntiNeutronAnnihilationAtRest::operator= (const G4AntiNeutronAnnihilationAtRest & right) private
void G4AntiNeutronAnnihilationAtRest::Poisso (G4float xav, G4int * iran) private
Definition at line 306 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 306 of file G4AntiNeutronAnnihilationAtRest.cc
References G4Exp(), G4Log(), G4UniformRand, G4Pow::GetInstance(), NFac(), Normal(), G4Pow::powN(), r, and ran().
Referenced by AntiNeutronAnnihilation().
void G4AntiNeutronAnnihilationAtRest::PreparePhysicsTable (const G4ParticleDefinition & p) virtual
Reimplemented from G4VProcess.
Definition at line 90 of file G4AntiNeutronAnnihilationAtRest.cc.
View newest version in sPHENIX GitHub at line 90 of file G4AntiNeutronAnnihilationAtRest.cc
References G4HadronicProcessStore::Instance(), and G4HadronicProcessStore::RegisterParticleForExtraProcess().
Member Data Documentation
G4float G4AntiNeutronAnnihilationAtRest::evapEnergy1 private
Definition at line 106 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), ExNu(), and G4AntiNeutronAnnihilationAtRest().
G4float G4AntiNeutronAnnihilationAtRest::evapEnergy3 private
Definition at line 107 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), ExNu(), and G4AntiNeutronAnnihilationAtRest().
G4GHEKinematicsVector* G4AntiNeutronAnnihilationAtRest::eve private
Definition at line 103 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), G4AntiNeutronAnnihilationAtRest(), GenerateSecondaries(), and ~G4AntiNeutronAnnihilationAtRest().
G4GHEKinematicsVector* G4AntiNeutronAnnihilationAtRest::gkin private
Definition at line 104 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AtRestDoIt(), G4AntiNeutronAnnihilationAtRest(), GenerateSecondaries(), GetSecondaryKinematics(), and ~G4AntiNeutronAnnihilationAtRest().
G4float G4AntiNeutronAnnihilationAtRest::globalTime private
Definition at line 94 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 94 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AtRestDoIt(), G4AntiNeutronAnnihilationAtRest(), and GenerateSecondaries().
G4float G4AntiNeutronAnnihilationAtRest::massAntiNeutron private
Definition at line 118 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 118 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), and GenerateSecondaries().
G4float G4AntiNeutronAnnihilationAtRest::massGamma private
Definition at line 117 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 117 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4float G4AntiNeutronAnnihilationAtRest::massNeutron private
Definition at line 119 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 119 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4float G4AntiNeutronAnnihilationAtRest::massPionMinus private
Definition at line 114 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4float G4AntiNeutronAnnihilationAtRest::massPionPlus private
Definition at line 116 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 116 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4float G4AntiNeutronAnnihilationAtRest::massPionZero private
Definition at line 115 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 115 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4int G4AntiNeutronAnnihilationAtRest::ngkine private
Definition at line 109 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AtRestDoIt(), G4AntiNeutronAnnihilationAtRest(), GenerateSecondaries(), and GetNumberOfSecondaries().
G4int G4AntiNeutronAnnihilationAtRest::ntot private
Definition at line 111 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 111 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), G4AntiNeutronAnnihilationAtRest(), and GenerateSecondaries().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefAlpha private
Definition at line 130 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 130 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefAntiNeutron private
Definition at line 127 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 127 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by GenerateSecondaries(), and IsApplicable().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefDeuteron private
Definition at line 128 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 128 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefGamma private
Definition at line 121 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 121 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefNeutron private
Definition at line 126 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 126 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefPionMinus private
Definition at line 124 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 124 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefPionPlus private
Definition at line 122 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 122 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefPionZero private
Definition at line 123 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 123 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefProton private
Definition at line 125 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 125 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4ParticleDefinition* G4AntiNeutronAnnihilationAtRest::pdefTriton private
Definition at line 129 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 129 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation().
G4GHEKinematicsVector* G4AntiNeutronAnnihilationAtRest::pv private
Definition at line 102 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), G4AntiNeutronAnnihilationAtRest(), GenerateSecondaries(), and ~G4AntiNeutronAnnihilationAtRest().
G4GHEKinematicsVector G4AntiNeutronAnnihilationAtRest::result private
Definition at line 112 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 112 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), and GenerateSecondaries().
G4float G4AntiNeutronAnnihilationAtRest::targetAtomicMass private
Definition at line 97 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), AtRestDoIt(), ExNu(), and G4AntiNeutronAnnihilationAtRest().
G4float G4AntiNeutronAnnihilationAtRest::targetCharge private
Definition at line 100 of file G4AntiNeutronAnnihilationAtRest.hh.
View newest version in sPHENIX GitHub at line 100 of file G4AntiNeutronAnnihilationAtRest.hh
Referenced by AntiNeutronAnnihilation(), AtRestDoIt(), ExNu(), and G4AntiNeutronAnnihilationAtRest().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4AntiNeutronAnnihilationAtRest.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/src/G4AntiNeutronAnnihilationAtRest.cc