ECCE @ EIC Software: PHG4EtaPhiParameterization Class Reference
PHG4EtaPhiParameterization Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4EtaPhiParameterization.h>
Public Member Functions
PHG4EtaPhiParameterization (unsigned int neta, double minEta, double maxEta, unsigned int nphi, double startPhi, double deltaPhi, double radiusIn, double radiusOut, double centerZ)
~PHG4EtaPhiParameterization () override
virtual void Print (std::ostream &os=std::cout) const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const override
void ComputeDimensions (G4Tubs &ring, const G4int copyNo, const G4VPhysicalVolume *physVol) const override
int GetIEta (int copyNo) const
int GetIPhi (int copyNo) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
unsigned int _neta
double _minEta
double _maxEta
unsigned int _nphi
double _startPhi
double _deltaPhi
double _radiusIn
double _radiusOut
double _centerZ
std::vector< double > _zpos
std::vector< double > _zhalf
std::vector< double > _phi0
std::vector< double > _phi1
std::vector< int > _ieta
std::vector< int > _iphi
Detailed Description
Definition at line 18 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 18 of file PHG4EtaPhiParameterization.h
Constructor & Destructor Documentation
PHG4EtaPhiParameterization::PHG4EtaPhiParameterization (unsigned int neta, double minEta, double maxEta, unsigned int nphi, double startPhi, double deltaPhi, double radiusIn, double radiusOut, double centerZ)
Definition at line 14 of file PHG4EtaPhiParameterization.cc.
View newest version in sPHENIX GitHub at line 14 of file PHG4EtaPhiParameterization.cc
References _centerZ, _deltaPhi, _ieta, _iphi, _maxEta, _minEta, _neta, _nphi, _phi0, _phi1, _radiusIn, _radiusOut, _startPhi, _zhalf, _zpos, g4zmq::exit(), and BTOF::zpos.
PHG4EtaPhiParameterization::~PHG4EtaPhiParameterization () override
Definition at line 89 of file PHG4EtaPhiParameterization.cc.
View newest version in sPHENIX GitHub at line 89 of file PHG4EtaPhiParameterization.cc
Member Function Documentation
void PHG4EtaPhiParameterization::ComputeDimensions (G4Tubs & ring, const G4int copyNo, const G4VPhysicalVolume * physVol) const override virtual
Reimplemented from G4VPVParameterisation.
Definition at line 117 of file PHG4EtaPhiParameterization.cc.
View newest version in sPHENIX GitHub at line 117 of file PHG4EtaPhiParameterization.cc
References _phi0, _phi1, _radiusIn, _radiusOut, _zhalf, GetIEta(), GetIPhi(), phi, G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), and G4Tubs::SetZHalfLength().
void PHG4EtaPhiParameterization::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const override virtual
Implements G4VPVParameterisation.
Definition at line 109 of file PHG4EtaPhiParameterization.cc.
View newest version in sPHENIX GitHub at line 109 of file PHG4EtaPhiParameterization.cc
References _nphi, _zpos, Acts::Test::origin(), G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
int PHG4EtaPhiParameterization::GetIEta (int copyNo) const inline
Definition at line 44 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 44 of file PHG4EtaPhiParameterization.h
References _ieta.
Referenced by ComputeDimensions().
int PHG4EtaPhiParameterization::GetIPhi (int copyNo) const inline
Definition at line 45 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 45 of file PHG4EtaPhiParameterization.h
References _iphi.
Referenced by ComputeDimensions().
void PHG4EtaPhiParameterization::Print (std::ostream & os = std::cout) const virtual
Definition at line 95 of file PHG4EtaPhiParameterization.cc.
View newest version in sPHENIX GitHub at line 95 of file PHG4EtaPhiParameterization.cc
References _neta, _nphi, _phi0, _zpos, and field_utils::copy().
Member Data Documentation
double PHG4EtaPhiParameterization::_centerZ private
Definition at line 71 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 71 of file PHG4EtaPhiParameterization.h
Referenced by PHG4EtaPhiParameterization().
double PHG4EtaPhiParameterization::_deltaPhi private
Definition at line 68 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 68 of file PHG4EtaPhiParameterization.h
Referenced by PHG4EtaPhiParameterization().
std::vector<int> PHG4EtaPhiParameterization::_ieta private
Definition at line 76 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 76 of file PHG4EtaPhiParameterization.h
Referenced by GetIEta(), and PHG4EtaPhiParameterization().
std::vector<int> PHG4EtaPhiParameterization::_iphi private
Definition at line 77 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 77 of file PHG4EtaPhiParameterization.h
Referenced by GetIPhi(), and PHG4EtaPhiParameterization().
double PHG4EtaPhiParameterization::_maxEta private
Definition at line 65 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 65 of file PHG4EtaPhiParameterization.h
Referenced by PHG4EtaPhiParameterization().
double PHG4EtaPhiParameterization::_minEta private
Definition at line 64 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 64 of file PHG4EtaPhiParameterization.h
Referenced by PHG4EtaPhiParameterization().
unsigned int PHG4EtaPhiParameterization::_neta private
Definition at line 63 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 63 of file PHG4EtaPhiParameterization.h
Referenced by PHG4EtaPhiParameterization(), and Print().
unsigned int PHG4EtaPhiParameterization::_nphi private
Definition at line 66 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 66 of file PHG4EtaPhiParameterization.h
Referenced by ComputeTransformation(), PHG4EtaPhiParameterization(), and Print().
std::vector<double> PHG4EtaPhiParameterization::_phi0 private
Definition at line 74 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 74 of file PHG4EtaPhiParameterization.h
Referenced by ComputeDimensions(), PHG4EtaPhiParameterization(), and Print().
std::vector<double> PHG4EtaPhiParameterization::_phi1 private
Definition at line 75 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 75 of file PHG4EtaPhiParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaPhiParameterization().
double PHG4EtaPhiParameterization::_radiusIn private
Definition at line 69 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 69 of file PHG4EtaPhiParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaPhiParameterization().
double PHG4EtaPhiParameterization::_radiusOut private
Definition at line 70 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 70 of file PHG4EtaPhiParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaPhiParameterization().
double PHG4EtaPhiParameterization::_startPhi private
Definition at line 67 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 67 of file PHG4EtaPhiParameterization.h
Referenced by PHG4EtaPhiParameterization().
std::vector<double> PHG4EtaPhiParameterization::_zhalf private
Definition at line 73 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 73 of file PHG4EtaPhiParameterization.h
Referenced by ComputeDimensions(), and PHG4EtaPhiParameterization().
std::vector<double> PHG4EtaPhiParameterization::_zpos private
Definition at line 72 of file PHG4EtaPhiParameterization.h.
View newest version in sPHENIX GitHub at line 72 of file PHG4EtaPhiParameterization.h
Referenced by ComputeTransformation(), PHG4EtaPhiParameterization(), and Print().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4EtaPhiParameterization.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4EtaPhiParameterization.cc