ECCE @ EIC Software: G4ITSteppingVerbose Class Reference
G4ITSteppingVerbose Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITSteppingVerbose.hh>
Public Member Functions
G4ITSteppingVerbose ()
~G4ITSteppingVerbose ()
void NewStep ()
void StepInfoForLeadingTrack ()
void AtRestDoItInvoked ()
void AtRestDoItOneByOne ()
void AlongStepDoItAllDone ()
void AlongStepDoItOneByOne ()
void PostStepDoItAllDone ()
void PostStepDoItOneByOne ()
void StepInfo ()
void TrackingStarted (G4Track *)
void TrackingEnded (G4Track *)
void DoItStarted ()
void PreStepVerbose (G4Track *track)
void PostStepVerbose (G4Track *track)
void DPSLStarted ()
void DPSLUserLimit ()
void DPSLPostStep ()
void DPSLAlongStep ()
void VerboseTrack ()
void VerboseParticleChange ()
void ShowStep () const
Public Member Functions inherited from G4VITSteppingVerbose
G4VITSteppingVerbose ()
virtual ~G4VITSteppingVerbose ()
void CopyState ()
void SetVerbose (int flag)
G4int GetVerbose ()
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
virtual G4String GetCurrentValue (G4UIcommand *command)
void SetStepProcessor (const G4ITStepProcessor *stepProcessor)
void TrackBanner (G4Track *track, const G4String &message)
Additional Inherited Members
Protected Types inherited from G4VITSteppingVerbose
typedef std::vector< G4int > G4SelectedAtRestDoItVector
typedef std::vector< G4int > G4SelectedAlongStepDoItVector
typedef std::vector< G4int > G4SelectedPostStepDoItVector
Protected Attributes inherited from G4VITSteppingVerbose
const G4ITStepProcessor * fpStepProcessor
G4UIcmdWithAnInteger * fpVerboseUI
G4ITStepProcessorState * fpState
const ProcessGeneralInfo * fpProcessGeneralInfo
G4double PhysicalStep
G4StepStatus fStepStatus
const G4VParticleChange * fParticleChange
const G4Track * fTrack
const G4TrackVector * fSecondary
const G4Step * fStep
G4StepPoint * fPreStepPoint
G4StepPoint * fPostStepPoint
const G4VPhysicalVolume * fCurrentVolume
const G4VITProcess * fCurrentProcess
G4ProcessVector * fAtRestDoItVector
G4ProcessVector * fAlongStepDoItVector
G4ProcessVector * fPostStepDoItVector
G4ProcessVector * fAtRestGetPhysIntVector
G4ProcessVector * fAlongStepGetPhysIntVector
G4ProcessVector * fPostStepGetPhysIntVector
size_t MAXofAtRestLoops
size_t MAXofAlongStepLoops
size_t MAXofPostStepLoops
size_t fAtRestDoItProcTriggered
size_t fPostStepDoItProcTriggered
G4int fN2ndariesAtRestDoIt
G4int fN2ndariesAlongStepDoIt
G4int fN2ndariesPostStepDoIt
G4int fVerboseLevel
G4SelectedAtRestDoItVector * fSelectedAtRestDoItVector
G4SelectedPostStepDoItVector * fSelectedPostStepDoItVector
G4double fPreviousStepSize
G4TouchableHandle fTouchableHandle
G4double physIntLength
G4ForceCondition fCondition
G4GPILSelection fGPILSelection
Detailed Description
Definition at line 44 of file G4ITSteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ITSteppingVerbose.hh
Constructor & Destructor Documentation
G4ITSteppingVerbose::G4ITSteppingVerbose ()
Definition at line 57 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ITSteppingVerbose.cc
References G4cout, and G4endl.
G4ITSteppingVerbose::~G4ITSteppingVerbose ()
Definition at line 66 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ITSteppingVerbose.cc
Member Function Documentation
void G4ITSteppingVerbose::AlongStepDoItAllDone () virtual
Implements G4VITSteppingVerbose.
Definition at line 145 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 145 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, G4VProcess::GetProcessName(), x, y, and z.
void G4ITSteppingVerbose::AlongStepDoItOneByOne () virtual
Implements G4VITSteppingVerbose.
Definition at line 675 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 675 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, x, y, and z.
void G4ITSteppingVerbose::AtRestDoItInvoked () virtual
Implements G4VITSteppingVerbose.
Definition at line 78 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, G4VProcess::GetProcessName(), x, y, and z.
void G4ITSteppingVerbose::AtRestDoItOneByOne () virtual
Implements G4VITSteppingVerbose.
Definition at line 1237 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 1237 of file G4ITSteppingVerbose.cc
References G4cout, and G4endl.
void G4ITSteppingVerbose::DoItStarted () virtual
Implements G4VITSteppingVerbose.
Definition at line 1103 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 1103 of file G4ITSteppingVerbose.cc
References G4cout, G4endl, left, LIGHT_RED, and RESET_COLOR.
void G4ITSteppingVerbose::DPSLAlongStep () virtual
Implements G4VITSteppingVerbose.
Definition at line 557 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 557 of file G4ITSteppingVerbose.cc
References CandidateForSelection, G4BestUnit, G4cout, G4endl, and NotCandidateForSelection.
void G4ITSteppingVerbose::DPSLPostStep () virtual
Implements G4VITSteppingVerbose.
Definition at line 519 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 519 of file G4ITSteppingVerbose.cc
References Conditionally, ExclusivelyForced, Forced, G4cout, G4endl, and StronglyForced.
void G4ITSteppingVerbose::DPSLStarted () virtual
Implements G4VITSteppingVerbose.
Definition at line 486 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 486 of file G4ITSteppingVerbose.cc
References G4cout, and G4endl.
void G4ITSteppingVerbose::DPSLUserLimit () virtual
Implements G4VITSteppingVerbose.
Definition at line 501 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 501 of file G4ITSteppingVerbose.cc
References G4cout, and G4endl.
void G4ITSteppingVerbose::NewStep () virtual
Implements G4VITSteppingVerbose.
Definition at line 72 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ITSteppingVerbose.cc
void G4ITSteppingVerbose::PostStepDoItAllDone () virtual
Implements G4VITSteppingVerbose.
Definition at line 202 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 202 of file G4ITSteppingVerbose.cc
References Conditionally, ExclusivelyForced, Forced, fPostStepDoItProc, G4BestUnit, G4cout, G4endl, G4VProcess::GetProcessName(), StronglyForced, x, y, and z.
void G4ITSteppingVerbose::PostStepDoItOneByOne () virtual
Implements G4VITSteppingVerbose.
Definition at line 720 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 720 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, x, y, and z.
void G4ITSteppingVerbose::PostStepVerbose (G4Track * track) virtual
Implements G4VITSteppingVerbose.
Definition at line 1170 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 1170 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, GetIT(), G4IT::GetName(), G4VPhysicalVolume::GetName(), G4Track::GetNextTouchableHandle(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4VProcess::GetProcessName(), G4VTouchable::GetReplicaNumber(), G4Step::GetSecondary(), G4Track::GetStep(), G4Track::GetTrackID(), G4VTouchable::GetVolume(), G4VPhysicalVolume::IsParameterised(), G4VPhysicalVolume::IsReplicated(), left, and Acts::Test::volume.
void G4ITSteppingVerbose::PreStepVerbose (G4Track * track) virtual
Implements G4VITSteppingVerbose.
Definition at line 1121 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 1121 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, G4Track::GetGlobalTime(), GetIT(), G4IT::GetName(), G4VPhysicalVolume::GetName(), G4Track::GetNextTouchableHandle(), G4Track::GetPosition(), G4VTouchable::GetReplicaNumber(), G4Track::GetTrackID(), G4VTouchable::GetVolume(), G4VPhysicalVolume::IsParameterised(), G4VPhysicalVolume::IsReplicated(), left, LIGHT_RED, RESET_COLOR, and Acts::Test::volume.
void G4ITSteppingVerbose::ShowStep () const
Definition at line 925 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 925 of file G4ITSteppingVerbose.cc
References fAlongStepDoItProc, fAtRestDoItProc, fGeomBoundary, fPostStepDoItProc, fUndefined, G4cout, and G4endl.
void G4ITSteppingVerbose::StepInfo () virtual
Implements G4VITSteppingVerbose.
Definition at line 382 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 382 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, CLHEP::prec, x, y, and z.
void G4ITSteppingVerbose::StepInfoForLeadingTrack () virtual
Implements G4VITSteppingVerbose.
Definition at line 276 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 276 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, CLHEP::prec, x, y, and z.
void G4ITSteppingVerbose::TrackingEnded (G4Track * track) virtual
Reimplemented from G4VITSteppingVerbose.
Definition at line 657 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 657 of file G4ITSteppingVerbose.cc
References G4cout, G4endl, G4Track::GetDefinition(), G4VPhysicalVolume::GetName(), G4Track::GetNextVolume(), G4ParticleDefinition::GetParticleName(), and G4Track::GetTrackID().
void G4ITSteppingVerbose::TrackingStarted (G4Track * track) virtual
Reimplemented from G4VITSteppingVerbose.
Definition at line 588 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 588 of file G4ITSteppingVerbose.cc
References G4BestUnit, G4cout, G4endl, GetIT(), G4IT::GetName(), G4Track::GetStep(), CLHEP::prec, and track.
void G4ITSteppingVerbose::VerboseParticleChange () virtual
Implements G4VITSteppingVerbose.
Definition at line 912 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 912 of file G4ITSteppingVerbose.cc
References G4cout, and G4endl.
void G4ITSteppingVerbose::VerboseTrack () virtual
Implements G4VITSteppingVerbose.
Definition at line 763 of file G4ITSteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 763 of file G4ITSteppingVerbose.cc
References fAlive, fKillTrackAndSecondaries, fPostponeToNextEvent, fStopAndKill, fStopButAlive, fSuspend, G4BestUnit, G4cout, G4endl, mm, ns, and CLHEP::prec.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITSteppingVerbose.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITSteppingVerbose.cc