ECCE @ EIC Software: G4VTrajectory Class Reference
G4VTrajectory Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4VTrajectory.hh>
Public Member Functions
G4VTrajectory ()
virtual ~G4VTrajectory ()
G4bool operator== (const G4VTrajectory &right) const
virtual G4int GetTrackID () const =0
virtual G4int GetParentID () const =0
virtual G4String GetParticleName () const =0
virtual G4double GetCharge () const =0
virtual G4int GetPDGEncoding () const =0
virtual G4ThreeVector GetInitialMomentum () const =0
virtual int GetPointEntries () const =0
virtual G4VTrajectoryPoint * GetPoint (G4int i) const =0
virtual void ShowTrajectory (std::ostream &os=G4cout) const
virtual void DrawTrajectory () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
virtual void AppendStep (const G4Step *aStep)=0
virtual void MergeTrajectory (G4VTrajectory *secondTrajectory)=0
Detailed Description
Definition at line 56 of file G4VTrajectory.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VTrajectory.hh
Constructor & Destructor Documentation
G4VTrajectory::G4VTrajectory ()
Definition at line 52 of file G4VTrajectory.cc.
View newest version in sPHENIX GitHub at line 52 of file G4VTrajectory.cc
G4VTrajectory::~G4VTrajectory () virtual
Definition at line 53 of file G4VTrajectory.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VTrajectory.cc
Member Function Documentation
virtual void G4VTrajectory::AppendStep (const G4Step * aStep) pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, F04Trajectory, G4RichTrajectory, G4RayTrajectory, and RE01Trajectory.
Referenced by ITTrackingInteractivity::AppendStep().
virtual std::vector<G4AttValue>* G4VTrajectory::CreateAttValues () const inline virtual
Reimplemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, F04Trajectory, G4RichTrajectory, and RE01Trajectory.
Definition at line 99 of file G4VTrajectory.hh.
View newest version in sPHENIX GitHub at line 99 of file G4VTrajectory.hh
Referenced by G4HepRepSceneHandler::addAttributes(), G4HepRepFileSceneHandler::AddCompound(), G4TrajectoriesModelDebugG4AttValues(), G4VSceneHandler::LoadAtts(), and ShowTrajectory().
void G4VTrajectory::DrawTrajectory () const virtual
Reimplemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RichTrajectory, G4RayTrajectory, RE01Trajectory, and LXeTrajectory.
Definition at line 114 of file G4VTrajectory.cc.
View newest version in sPHENIX GitHub at line 114 of file G4VTrajectory.cc
References G4VVisManager::DispatchToModel(), and G4VVisManager::GetConcreteInstance().
Referenced by G4GMocrenFileSceneHandler::AddCompound(), G4VSceneHandler::AddCompound(), CexmcEventAction::DrawTrajectories(), G4RichTrajectory::DrawTrajectory(), G4SmoothTrajectory::DrawTrajectory(), G4Trajectory::DrawTrajectory(), and RE04Trajectory::DrawTrajectory().
virtual const std::map<G4String,G4AttDef>* G4VTrajectory::GetAttDefs () const inline virtual
Reimplemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, F04Trajectory, G4RichTrajectory, and RE01Trajectory.
Definition at line 93 of file G4VTrajectory.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VTrajectory.hh
Referenced by G4HepRepSceneHandler::addAttributes(), G4HepRepFileSceneHandler::AddCompound(), G4TrajectoriesModelDebugG4AttValues(), G4VSceneHandler::LoadAtts(), and ShowTrajectory().
virtual G4double G4VTrajectory::GetCharge () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoryDrawByCharge::Draw(), and G4TrajectoryChargeFilter::Evaluate().
virtual G4ThreeVector G4VTrajectory::GetInitialMomentum () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound().
virtual G4int G4VTrajectory::GetParentID () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
virtual G4String G4VTrajectory::GetParticleName () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoryDrawByParticleID::Draw(), and G4TrajectoryParticleFilter::Evaluate().
virtual G4int G4VTrajectory::GetPDGEncoding () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, G4RayTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
virtual G4VTrajectoryPoint* G4VTrajectory::GetPoint (G4int i) const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, F04Trajectory, G4RichTrajectory, RE01Trajectory, and G4RayTrajectory.
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryOriginVolumeFilter::Evaluate(), G4TrajectoriesModelDebugG4AttValues(), G4TrajectoryDrawerUtils::GetPointsAndTimes(), G4VSceneHandler::LoadAtts(), and ShowTrajectory().
virtual int G4VTrajectory::GetPointEntries () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, F04Trajectory, G4RichTrajectory, RE01Trajectory, and G4RayTrajectory.
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoriesModelDebugG4AttValues(), G4TrajectoryDrawerUtils::GetPointsAndTimes(), G4VSceneHandler::LoadAtts(), and ShowTrajectory().
virtual G4int G4VTrajectory::GetTrackID () const pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4RayTrajectory, G4SmoothTrajectory, WLSTrajectory, F04Trajectory, and RE01Trajectory.
Referenced by G4GMocrenFileSceneHandler::AddCompound().
virtual void G4VTrajectory::MergeTrajectory (G4VTrajectory * secondTrajectory) pure virtual
Implemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, F04Trajectory, G4RayTrajectory, G4RichTrajectory, and RE01Trajectory.
Referenced by G4EventManager::DoProcessing().
G4bool G4VTrajectory::operator== (const G4VTrajectory & right) const
Definition at line 55 of file G4VTrajectory.cc.
View newest version in sPHENIX GitHub at line 55 of file G4VTrajectory.cc
void G4VTrajectory::ShowTrajectory (std::ostream & os = G4cout) const virtual
Reimplemented in RE04Trajectory, G4Trajectory, G4SmoothTrajectory, WLSTrajectory, F04Trajectory, G4RichTrajectory, G4RayTrajectory, and RE01Trajectory.
Definition at line 60 of file G4VTrajectory.cc.
View newest version in sPHENIX GitHub at line 60 of file G4VTrajectory.cc
References G4VTrajectoryPoint::CreateAttValues(), CreateAttValues(), G4VTrajectoryPoint::GetAttDefs(), GetAttDefs(), GetPoint(), and GetPointEntries().
Referenced by ITTrackingInteractivity::EndTracking(), G4TrackingManager::ProcessOneTrack(), G4RichTrajectory::ShowTrajectory(), F04Trajectory::ShowTrajectory(), WLSTrajectory::ShowTrajectory(), G4SmoothTrajectory::ShowTrajectory(), G4Trajectory::ShowTrajectory(), and RE04Trajectory::ShowTrajectory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4VTrajectory.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4VTrajectory.cc