ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/global/HEPRandom/src/G4UniformRandPool.cc File Reference
G4UniformRandPool.cc File Reference
#include "G4UniformRandPool.hh"
#include "globals.hh"
#include "G4Threading.hh"
#include "G4AutoDelete.hh"
#include <climits>
#include <stdlib.h>
#include <algorithm>
#include <cstring>
Functions
void create_pool (G4double *&buffer, G4int ps)
void destroy_pool (G4double *&buffer)
void create_pool_align (G4double *&buffer, G4int ps)
void destroy_pool_align (G4double *&buffer)
Function Documentation
void create_pool (G4double *& buffer, G4int ps)
Definition at line 45 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 45 of file G4UniformRandPool.cc
References ps.
Referenced by G4UniformRandPool::G4UniformRandPool(), and G4UniformRandPool::Resize().
void create_pool_align (G4double *& buffer, G4int ps)
Definition at line 71 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 71 of file G4UniformRandPool.cc
References FatalException, and G4Exception().
Referenced by G4UniformRandPool::G4UniformRandPool().
void destroy_pool (G4double *& buffer)
Definition at line 50 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 50 of file G4UniformRandPool.cc
References buffer.
Referenced by G4UniformRandPool::Resize(), and G4UniformRandPool::~G4UniformRandPool().
void destroy_pool_align (G4double *& buffer)
Definition at line 87 of file G4UniformRandPool.cc.
View newest version in sPHENIX GitHub at line 87 of file G4UniformRandPool.cc
Referenced by G4UniformRandPool::~G4UniformRandPool().