ECCE @ EIC Software: CLHEP::HepLorentzVector Class Reference
CLHEP::HepLorentzVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/LorentzVector.h>
Public Types
enum {
X =0, Y =1, Z =2, T =3,
NUM_COORDINATES =4, SIZE =NUM_COORDINATES
}
Public Member Functions
HepLorentzVector (double x, double y, double z, double t)
HepLorentzVector (double x, double y, double z)
HepLorentzVector (double t)
HepLorentzVector ()
HepLorentzVector (const Hep3Vector &p, double e)
HepLorentzVector (double e, const Hep3Vector &p)
HepLorentzVector (const HepLorentzVector &)
HepLorentzVector (HepLorentzVector &&)=default
~HepLorentzVector ()
operator const Hep3Vector & () const
operator Hep3Vector & ()
double x () const
double y () const
double z () const
double t () const
void setX (double)
void setY (double)
void setZ (double)
void setT (double)
double px () const
double py () const
double pz () const
double e () const
void setPx (double)
void setPy (double)
void setPz (double)
void setE (double)
Hep3Vector vect () const
void setVect (const Hep3Vector &)
double theta () const
double cosTheta () const
double phi () const
double rho () const
void setTheta (double)
void setPhi (double)
void setRho (double)
double operator() (int) const
double operator[] (int) const
double & operator() (int)
double & operator[] (int)
HepLorentzVector & operator= (const HepLorentzVector &)
HepLorentzVector & operator= (HepLorentzVector &&)=default
HepLorentzVector operator+ (const HepLorentzVector &) const
HepLorentzVector & operator+= (const HepLorentzVector &)
HepLorentzVector operator- (const HepLorentzVector &) const
HepLorentzVector & operator-= (const HepLorentzVector &)
HepLorentzVector operator- () const
HepLorentzVector & operator*= (double)
HepLorentzVector & operator/= (double)
bool operator== (const HepLorentzVector &) const
bool operator!= (const HepLorentzVector &) const
double perp2 () const
double perp () const
void setPerp (double)
double perp2 (const Hep3Vector &) const
double perp (const Hep3Vector &) const
double angle (const Hep3Vector &) const
double mag2 () const
double m2 () const
double mag () const
double m () const
double mt2 () const
double mt () const
double et2 () const
double et () const
double dot (const HepLorentzVector &) const
double operator* (const HepLorentzVector &) const
double invariantMass2 (const HepLorentzVector &w) const
double invariantMass (const HepLorentzVector &w) const
void setVectMag (const Hep3Vector &spatial, double magnitude)
void setVectM (const Hep3Vector &spatial, double mass)
double plus () const
double minus () const
Hep3Vector boostVector () const
HepLorentzVector & boost (double, double, double)
HepLorentzVector & boost (const Hep3Vector &)
HepLorentzVector & boostX (double beta)
HepLorentzVector & boostY (double beta)
HepLorentzVector & boostZ (double beta)
double rapidity () const
double pseudoRapidity () const
bool isTimelike () const
bool isSpacelike () const
bool isLightlike (double epsilon=tolerance) const
HepLorentzVector & rotateX (double)
HepLorentzVector & rotateY (double)
HepLorentzVector & rotateZ (double)
HepLorentzVector & rotateUz (const Hep3Vector &)
HepLorentzVector & rotate (double, const Hep3Vector &)
HepLorentzVector & operator*= (const HepRotation &)
HepLorentzVector & transform (const HepRotation &)
HepLorentzVector & operator*= (const HepLorentzRotation &)
HepLorentzVector & transform (const HepLorentzRotation &)
void set (double x, double y, double z, double t)
void set (double x, double y, double z, Tcomponent t)
HepLorentzVector (double x, double y, double z, Tcomponent t)
void set (Tcomponent t, double x, double y, double z)
HepLorentzVector (Tcomponent t, double x, double y, double z)
void set (double t)
void set (Tcomponent t)
HepLorentzVector (Tcomponent t)
void set (const Hep3Vector &v)
HepLorentzVector (const Hep3Vector &v)
HepLorentzVector & operator= (const Hep3Vector &v)
void set (const Hep3Vector &v, double t)
void set (double t, const Hep3Vector &v)
double getX () const
double getY () const
double getZ () const
double getT () const
Hep3Vector v () const
Hep3Vector getV () const
void setV (const Hep3Vector &)
void setV (double x, double y, double z)
void setRThetaPhi (double r, double theta, double phi)
void setREtaPhi (double r, double eta, double phi)
void setRhoPhiZ (double rho, double phi, double z)
int compare (const HepLorentzVector &w) const
bool operator> (const HepLorentzVector &w) const
bool operator< (const HepLorentzVector &w) const
bool operator>= (const HepLorentzVector &w) const
bool operator<= (const HepLorentzVector &w) const
bool isNear (const HepLorentzVector &w, double epsilon=tolerance) const
double howNear (const HepLorentzVector &w) const
bool isNearCM (const HepLorentzVector &w, double epsilon=tolerance) const
double howNearCM (const HepLorentzVector &w) const
bool isParallel (const HepLorentzVector &w, double epsilon=tolerance) const
double howParallel (const HepLorentzVector &w) const
double deltaR (const HepLorentzVector &v) const
double howLightlike () const
double euclideanNorm2 () const
double euclideanNorm () const
double restMass2 () const
double invariantMass2 () const
double restMass () const
double invariantMass () const
HepLorentzVector rest4Vector () const
double beta () const
double gamma () const
double eta () const
double eta (const Hep3Vector &ref) const
double rapidity (const Hep3Vector &ref) const
double coLinearRapidity () const
Hep3Vector findBoostToCM () const
Hep3Vector findBoostToCM (const HepLorentzVector &w) const
double et2 (const Hep3Vector &) const
double et (const Hep3Vector &) const
double diff2 (const HepLorentzVector &w) const
double delta2Euclidean (const HepLorentzVector &w) const
double plus (const Hep3Vector &ref) const
double minus (const Hep3Vector &ref) const
HepLorentzVector & rotate (const Hep3Vector &axis, double delta)
HepLorentzVector & rotate (const HepAxisAngle &ax)
HepLorentzVector & rotate (const HepEulerAngles &e)
HepLorentzVector & rotate (double phi, double theta, double psi)
HepLorentzVector & boost (const Hep3Vector &axis, double beta)
Static Public Member Functions
static ZMpvMetric_t setMetric (ZMpvMetric_t met)
static ZMpvMetric_t getMetric ()
static double getTolerance ()
static double setTolerance (double tol)
Private Attributes
Hep3Vector pp
double ee
Static Private Attributes
static DLL_API double tolerance
static DLL_API double metric = 1.0
Friends
HepLorentzVector rotationXOf (const HepLorentzVector &vec, double delta)
HepLorentzVector rotationYOf (const HepLorentzVector &vec, double delta)
HepLorentzVector rotationZOf (const HepLorentzVector &vec, double delta)
HepLorentzVector rotationOf (const HepLorentzVector &vec, const Hep3Vector &axis, double delta)
HepLorentzVector rotationOf (const HepLorentzVector &vec, const HepAxisAngle &ax)
HepLorentzVector rotationOf (const HepLorentzVector &vec, const HepEulerAngles &e)
HepLorentzVector rotationOf (const HepLorentzVector &vec, double phi, double theta, double psi)
HepLorentzVector boostXOf (const HepLorentzVector &vec, double beta)
HepLorentzVector boostYOf (const HepLorentzVector &vec, double beta)
HepLorentzVector boostZOf (const HepLorentzVector &vec, double beta)
HepLorentzVector boostOf (const HepLorentzVector &vec, const Hep3Vector &betaVector)
HepLorentzVector boostOf (const HepLorentzVector &vec, const Hep3Vector &axis, double beta)
Detailed Description
Author
Definition at line 71 of file LorentzVector.h.
View newest version in sPHENIX GitHub at line 71 of file LorentzVector.h
Member Enumeration Documentation
anonymous enum
Enumerator:
X
Y
Z
T
NUM_COORDINATES
SIZE
Definition at line 75 of file LorentzVector.h.
View newest version in sPHENIX GitHub at line 75 of file LorentzVector.h
Constructor & Destructor Documentation
CLHEP::HepLorentzVector::HepLorentzVector (double x, double y, double z, double t) inline
CLHEP::HepLorentzVector::HepLorentzVector (double x, double y, double z) inline
CLHEP::HepLorentzVector::HepLorentzVector (double t) explicit
CLHEP::HepLorentzVector::HepLorentzVector () inline
Referenced by rest4Vector().
CLHEP::HepLorentzVector::HepLorentzVector (const Hep3Vector & p, double e) inline
CLHEP::HepLorentzVector::HepLorentzVector (double e, const Hep3Vector & p) inline
CLHEP::HepLorentzVector::HepLorentzVector (const HepLorentzVector &) inline
CLHEP::HepLorentzVector::HepLorentzVector (HepLorentzVector &&) inline default
CLHEP::HepLorentzVector::~HepLorentzVector () inline
CLHEP::HepLorentzVector::HepLorentzVector (double x, double y, double z, Tcomponent t) inline
CLHEP::HepLorentzVector::HepLorentzVector (Tcomponent t, double x, double y, double z) inline
CLHEP::HepLorentzVector::HepLorentzVector (Tcomponent t) inline explicit
CLHEP::HepLorentzVector::HepLorentzVector (const Hep3Vector & v) inline explicit
Member Function Documentation
double CLHEP::HepLorentzVector::angle (const Hep3Vector &) const inline
double CLHEP::HepLorentzVector::beta () const
Definition at line 75 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 75 of file LorentzVectorK.cc
References ee, CLHEP::Hep3Vector::mag2(), and pp.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4EMDissociation::ApplyYourself(), G4RKPropagation::FieldTransport(), G4EMDissociationCrossSection::GetElementCrossSection(), and G4BetheHeitler5DModel::SampleSecondaries().
HepLorentzVector & CLHEP::HepLorentzVector::boost (double bx, double by, double bz)
Definition at line 58 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 58 of file LorentzVector.cc
References bp, t, x, y, and z.
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4HadronElastic::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4LorentzConvertor::backToTheLab(), G4KineticTrackVector::Boost(), G4DecayProducts::Boost(), G4Nucleon::Boost(), G4ExcitedString::Boost(), G4KineticTrackVector::BoostBeam(), G4InuclEvaporation::BreakItUp(), G4StatMF::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4NeutrinoNucleusModel::ClusterDecay(), G4NeutrinoNucleusModel::CoherentPion(), G4LightTargetCollider::collide(), G4FermiPhaseSpaceDecay::Decay(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonDecayChannelWithSpin::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4BigBanger::deExcite(), G4GEMChannelVI::EmittedFragment(), G4CompetitiveFission::EmittedFragment(), G4EvaporationChannel::EmittedFragment(), G4GEMChannel::EmittedFragment(), G4CascadeFinalStateAlgorithm::FillUsingKopylov(), G4NeutrinoNucleusModel::FinalBarion(), G4HadPhaseSpaceKopylov::GenerateMultiBody(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4LorentzConvertor::getKinEnergyInTheTRS(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4LorentzConvertor::getTRSMomentum(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4CascadeCoalescence::maxDeltaP(), G4NeutrinoNucleusModel::MesonDecay(), G4PreCompoundEmission::PerformEmission(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), CexmcChargeExchangeReconstructor::Reconstruct(), G4QuasiElRatios::RelDecayIn2(), G4FermiBreakUpVI::SampleDecay(), G4AntiNuclElastic::SampleInvariantT(), G4NuclNuclDiffuseElastic::SampleInvariantT(), G4DiffuseElasticV2::SampleInvariantT(), G4DiffuseElastic::SampleInvariantT(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4eeTo3PiModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4eeToHadronsModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4GammaTransition::SampleTransition(), G4WilsonAblationModel::SelectSecondariesByDefault(), G4Fragment::SetExcEnergyAndMomentum(), G4QGSMFragmentation::SplitLast(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), G4DiffuseElastic::ThetaLabToThetaCMS(), G4LorentzConvertor::toTheCenterOfMass(), and G4LorentzConvertor::toTheTargetRestFrame().
HepLorentzVector& CLHEP::HepLorentzVector::boost (const Hep3Vector &) inline
HepLorentzVector & CLHEP::HepLorentzVector::boost (const Hep3Vector & axis, double beta)
Definition at line 49 of file LorentzVectorB.cc.
View newest version in sPHENIX GitHub at line 49 of file LorentzVectorB.cc
References CLHEP::Hep3Vector::dot(), CLHEP::Hep3Vector::mag2(), G4InuclParticleNames::pp, r2, Acts::UnitConstants::u, and CLHEP::Hep3Vector::unit().
Hep3Vector CLHEP::HepLorentzVector::boostVector () const
Definition at line 176 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 176 of file LorentzVector.cc
References ee, CLHEP::Hep3Vector::mag2(), pp, and restMass2().
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Annihilate(), G4HadronElastic::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4StatMF::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4NeutrinoNucleusModel::ClusterDecay(), G4NeutrinoNucleusModel::CoherentPion(), G4LightTargetCollider::collide(), G4BinaryCascade::CorrectFinalPandE(), G4DiffractiveExcitation::CreateStrings(), G4FermiPhaseSpaceDecay::Decay(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), G4BinaryCascade::DecayVoidNucleus(), G4BigBanger::deExcite(), G4BinaryLightIonReaction::DeExciteSpectatorNucleus(), G4QGSParticipants::DeterminePartonMomenta(), G4ElasticHNScattering::ElasticScattering(), G4GEMChannelVI::EmittedFragment(), G4CompetitiveFission::EmittedFragment(), G4EvaporationChannel::EmittedFragment(), G4GEMChannel::EmittedFragment(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4CascadeFinalStateAlgorithm::FillUsingKopylov(), G4NeutrinoNucleusModel::FinalBarion(), G4VElasticCollision::FinalState(), G4VAnnihilationCollision::FinalState(), G4VScatteringCollision::FinalState(), findBoostToCM(), G4Absorber::FindProducts(), G4ExcitedStringDecay::FragmentStrings(), G4FragmentingString::G4FragmentingString(), G4HadDecayGenerator::Generate(), G4HadPhaseSpaceKopylov::GenerateMultiBody(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4LorentzConvertor::getKinEnergyInTheTRS(), G4LorentzConvertor::getTRSMomentum(), G4RKFieldIntegrator::Integrate(), G4CascadeCoalescence::maxDeltaP(), G4NeutrinoNucleusModel::MesonDecay(), G4PreCompoundEmission::PerformEmission(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), CexmcChargeExchangeReconstructor::Reconstruct(), G4QuasiElRatios::RelDecayIn2(), G4FermiBreakUpVI::SampleDecay(), G4AntiNuclElastic::SampleInvariantT(), G4NuclNuclDiffuseElastic::SampleInvariantT(), G4DiffuseElasticV2::SampleInvariantT(), G4DiffuseElastic::SampleInvariantT(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4eeTo3PiModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eeToHadronsModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4GammaTransition::SampleTransition(), G4Fragment::SetExcEnergyAndMomentum(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), G4DiffuseElastic::ThetaLabToThetaCMS(), G4LorentzConvertor::toTheTargetRestFrame(), G4ExcitedString::TransformToAlignedCms(), G4FragmentingString::TransformToAlignedCms(), G4ExcitedString::TransformToCenterOfMass(), and G4FragmentingString::TransformToCenterOfMass().
HepLorentzVector & CLHEP::HepLorentzVector::boostX (double beta)
Definition at line 196 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 196 of file LorentzVector.cc
References ee, CLHEP::Hep3Vector::getX(), pp, and CLHEP::Hep3Vector::setX().
HepLorentzVector & CLHEP::HepLorentzVector::boostY (double beta)
Definition at line 211 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 211 of file LorentzVector.cc
References ee, CLHEP::Hep3Vector::getY(), pp, and CLHEP::Hep3Vector::setY().
HepLorentzVector & CLHEP::HepLorentzVector::boostZ (double beta)
Definition at line 226 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 226 of file LorentzVector.cc
References ee, CLHEP::Hep3Vector::getZ(), pp, and CLHEP::Hep3Vector::setZ().
Referenced by G4BetheHeitler5DModel::SampleSecondaries().
double CLHEP::HepLorentzVector::coLinearRapidity () const
Definition at line 171 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 171 of file LorentzVectorK.cc
References ee, CLHEP::Hep3Vector::mag(), pp, and v1.
int CLHEP::HepLorentzVector::compare (const HepLorentzVector & w) const
Definition at line 28 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 28 of file LorentzVectorC.cc
References CLHEP::Hep3Vector::compare(), ee, and pp.
Referenced by operator<(), operator<=(), operator>(), and operator>=().
double CLHEP::HepLorentzVector::cosTheta () const inline
Referenced by CexmcEventAction::EndOfEventAction().
double CLHEP::HepLorentzVector::delta2Euclidean (const HepLorentzVector & w) const inline
double CLHEP::HepLorentzVector::deltaR (const HepLorentzVector & v) const
Definition at line 194 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 194 of file LorentzVectorC.cc
References a, b, CLHEP::Hep3Vector::deltaPhi(), eta(), getV(), and pp.
double CLHEP::HepLorentzVector::diff2 (const HepLorentzVector & w) const inline
double CLHEP::HepLorentzVector::dot (const HepLorentzVector &) const inline
Referenced by G4Nucleon::Boost(), and CLHEP::HepLorentzRotation::set().
double CLHEP::HepLorentzVector::e () const inline
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4BinaryLightIonReaction::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4LorentzConvertor::backToTheLab(), G4Nucleon::Boost(), G4NucleiModel::boundaryTransition(), G4StatMF::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4BinaryCascade::BuildLateParticleCollisions(), G4BinaryCascade::BuildTargetList(), G4QMDMeanField::Cal2BodyQuantities(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDCollision::CalFinalStateOfTheBinaryCollision(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDMeanField::CalGraduate(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4BinaryCascade::Capture(), G4RPGAntiKZeroInelastic::Cascade(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4BinaryCascade::CheckPauliPrinciple(), G4HadronicProcess::CheckResult(), G4QuasiElRatios::ChExer(), G4NeutrinoNucleusModel::CoherentPion(), G4CascadeCheckBalance::collide(), G4BinaryCascade::CorrectFinalPandE(), G4BinaryCascade::CorrectShortlivedFinalsForFermi(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4CascadeInterface::createBullet(), G4DiffractiveExcitation::CreateStrings(), G4CollisionNN::CrossSection(), G4BinaryCascade::DebugApplyCollision(), G4BinaryCascade::DebugFinalEpConservation(), G4Pythia6Decayer::Decay(), G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4Fissioner::deExcite(), G4EquilibriumEvaporator::deExcite(), G4BinaryCascade::DeExcite(), G4CascadeCheckBalance::deltaE(), G4QGSParticipants::DeterminePartonMomenta(), G4Fancy3DNucleus::DoLorentzContraction(), G4CascadeCheckBalance::ekin(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4RKPropagation::FieldTransport(), G4CascadeRecoilMaker::fillRecoil(), G4MuonicAtomDecay::FillResult(), G4BinaryCascade::FillVoidNucleusProducts(), G4NeutrinoNucleusModel::FinalBarion(), G4NeutrinoNucleusModel::FinalMomentum(), G4ExcitedStringDecay::FragmentStrings(), G4RKPropagation::FreeTransport(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4FragmentingString::G4FragmentingString(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4BinaryCascade::GetFinal4Momentum(), G4BinaryCascade::GetFinalNucleusMomentum(), G4LorentzConvertor::getKinEnergyInTheTRS(), G4QMDParticipant::GetKineticEnergy(), G4RKPropagation::GetSphereIntersectionTimes(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4HadProjectile::GetTotalEnergy(), G4IntraNucleiCascader::initialize(), operator()(), operator<<(), G4ReactionProduct::operator=(), G4InuclParticle::print(), G4LorentzConvertor::printBullet(), G4LorentzConvertor::printTarget(), G4BinaryCascade::ProductsAddFinalState(), G4BinaryCascade::Propagate1H1(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4CascadeCheckBalance::relativeE(), G4QuasiElRatios::RelDecayIn2(), G4FermiBreakUpVI::SampleDecay(), G4AntiNuclElastic::SampleInvariantT(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4eeTo3PiModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4eeToHadronsModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), G4QuasiElasticChannel::Scatter(), G4QuasiElRatios::Scatter(), G4CollisionOutput::setOnShell(), MCTruthTrackingAction::TrackToBeStored(), G4RKPropagation::Transport(), G4CollisionOutput::tuneSelectedPair(), G4CascadeRecoilMaker::wholeEvent(), and G4Absorber::WillBeAbsorbed().
double CLHEP::HepLorentzVector::et () const inline
Referenced by pywidt().
double CLHEP::HepLorentzVector::et (const Hep3Vector &) const inline
double CLHEP::HepLorentzVector::et2 () const inline
double CLHEP::HepLorentzVector::et2 (const Hep3Vector &) const inline
double CLHEP::HepLorentzVector::eta () const inline
Referenced by deltaR().
double CLHEP::HepLorentzVector::eta (const Hep3Vector & ref) const inline
double CLHEP::HepLorentzVector::euclideanNorm () const inline
Referenced by howParallel(), and isParallel().
double CLHEP::HepLorentzVector::euclideanNorm2 () const inline
Referenced by isParallel().
Hep3Vector CLHEP::HepLorentzVector::findBoostToCM () const
Definition at line 223 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 223 of file LorentzVectorK.cc
References boostVector().
Referenced by G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4WilsonAblationModel::BreakItUp(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4LightTargetCollider::collide(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), and G4GeneratorPrecompoundInterface::PropagateNuclNucl().
Hep3Vector CLHEP::HepLorentzVector::findBoostToCM (const HepLorentzVector & w) const
Definition at line 227 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 227 of file LorentzVectorK.cc
References ee, CLHEP::Hep3Vector::mag2(), pp, t1, and v1.
double CLHEP::HepLorentzVector::gamma () const
Definition at line 94 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 94 of file LorentzVectorK.cc
References ee, CLHEP::Hep3Vector::mag2(), pp, t2, and v2.
Referenced by G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), and G4KineticTrack::SampleResidualLifetime().
ZMpvMetric_t CLHEP::HepLorentzVector::getMetric () static
Definition at line 35 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 35 of file LorentzVectorK.cc
References metric, CLHEP::TimeNegative, and CLHEP::TimePositive.
double CLHEP::HepLorentzVector::getT () const inline
Referenced by G4BinaryLightIonReaction::ApplyYourself(), CLHEP::operator/(), G4LundStringFragmentation::Sample4Momentum(), and CLHEP::HepLorentzRotation::set().
double CLHEP::HepLorentzVector::getTolerance () static
Definition at line 248 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 248 of file LorentzVector.cc
References tolerance.
Hep3Vector CLHEP::HepLorentzVector::getV () const inline
Referenced by G4INCLXXInterface::ApplyYourself(), deltaR(), CLHEP::operator/(), and G4LENDModel::returnUnchanged().
double CLHEP::HepLorentzVector::getX () const inline
Referenced by G4LundStringFragmentation::Sample4Momentum().
double CLHEP::HepLorentzVector::getY () const inline
Referenced by G4LundStringFragmentation::Sample4Momentum().
double CLHEP::HepLorentzVector::getZ () const inline
Referenced by G4InuclEvaporation::BreakItUp(), G4DiffractiveExcitation::CreateStrings(), and G4LundStringFragmentation::Sample4Momentum().
double CLHEP::HepLorentzVector::howLightlike () const
Definition at line 248 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 248 of file LorentzVectorC.cc
References ee, and restMass2().
double CLHEP::HepLorentzVector::howNear (const HepLorentzVector & w) const
Definition at line 66 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 66 of file LorentzVectorC.cc
References Acts::Test::delta, CLHEP::Hep3Vector::dot(), ee, mag2(), and pp.
Referenced by howNearCM().
double CLHEP::HepLorentzVector::howNearCM (const HepLorentzVector & w) const
Definition at line 132 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 132 of file LorentzVectorC.cc
References CLHEP::Hep3Vector::dot(), ee, howNear(), CLHEP::Hep3Vector::mag2(), and pp.
double CLHEP::HepLorentzVector::howParallel (const HepLorentzVector & w) const
Definition at line 226 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 226 of file LorentzVectorC.cc
References euclideanNorm(), norm, and x1.
double CLHEP::HepLorentzVector::invariantMass (const HepLorentzVector & w) const
Definition at line 192 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 192 of file LorentzVectorK.cc
References ee, invariantMass2(), isLightlike(), and isSpacelike().
double CLHEP::HepLorentzVector::invariantMass () const inline
double CLHEP::HepLorentzVector::invariantMass2 (const HepLorentzVector & w) const inline
double CLHEP::HepLorentzVector::invariantMass2 () const inline
Referenced by invariantMass().
bool CLHEP::HepLorentzVector::isLightlike (double epsilon = tolerance) const inline
Referenced by invariantMass().
bool CLHEP::HepLorentzVector::isNear (const HepLorentzVector & w, double epsilon = tolerance) const
Definition at line 56 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 56 of file LorentzVectorC.cc
References Acts::Test::delta, CLHEP::Hep3Vector::dot(), ee, epsilon(), mag2(), and pp.
Referenced by isNearCM().
bool CLHEP::HepLorentzVector::isNearCM (const HepLorentzVector & w, double epsilon = tolerance) const
Definition at line 84 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 84 of file LorentzVectorC.cc
References CLHEP::Hep3Vector::dot(), ee, isNear(), CLHEP::Hep3Vector::mag2(), G4InuclParticleNames::pp, and pp.
bool CLHEP::HepLorentzVector::isParallel (const HepLorentzVector & w, double epsilon = tolerance) const
Definition at line 207 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 207 of file LorentzVectorC.cc
References euclideanNorm(), euclideanNorm2(), and norm.
bool CLHEP::HepLorentzVector::isSpacelike () const inline
Referenced by invariantMass().
bool CLHEP::HepLorentzVector::isTimelike () const inline
double CLHEP::HepLorentzVector::m () const inline
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4QMDMeanField::CalGraduate(), G4QuasiElRatios::ChExer(), G4NeutrinoNucleusModel::ClusterDecay(), G4NeutrinoNucleusModel::CoherentPion(), G4CascadeRecoilMaker::deltaM(), G4CascadeCheckBalance::ekin(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4CascadeRecoilMaker::fillRecoil(), G4NeutrinoNucleusModel::FinalBarion(), G4VAnnihilationCollision::FinalState(), G4VScatteringCollision::FinalState(), G4IntraNucleiCascader::finishCascade(), G4HadDecayGenerator::Generate(), G4BinaryCascade::GetFinal4Momentum(), G4LorentzConvertor::getKinEnergyInTheTRS(), G4VPreCompoundFragment::Initialize(), G4NeutrinoNucleusModel::MesonDecay(), G4LorentzConvertor::printBullet(), G4LorentzConvertor::printTarget(), QAG4SimulationUpsilon::process_event(), QAG4SimulationKFParticle::process_event(), rest4Vector(), G4NuMuNucleusCcModel::SampleLVkr(), G4eeToHadronsModel::SampleSecondaries(), G4QuasiElRatios::Scatter(), G4InuclParticle::setMomentum(), and G4CollisionOutput::setOnShell().
double CLHEP::HepLorentzVector::m2 () const inline
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4QMDMeanField::Cal2BodyQuantities(), G4QuasiElRatios::ChExer(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4QuasiElRatios::RelDecayIn2(), G4eeTo3PiModel::SampleSecondaries(), and G4QuasiElRatios::Scatter().
double CLHEP::HepLorentzVector::mag () const inline
Referenced by G4MesonAbsorption::AbsorptionCrossSection(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Annihilate(), G4BinaryLightIonReaction::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4Nucleon::Boost(), G4UnstableFragmentBreakUp::BreakUpChain(), G4Fragment::CalculateExcitationEnergy(), G4BinaryCascade::CheckPauliPrinciple(), G4BinaryCascade::CorrectFinalPandE(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::CreateStrings(), G4BinaryCascade::DecayVoidNucleus(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4ElasticHNScattering::ElasticScattering(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4FragmentingString::G4FragmentingString(), G4BinaryCascade::GetExcitationEnergy(), G4BinaryLightIonReaction::GetProjectileExcitation(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4FragmentingString::Mass(), G4QGSParticipants::PerformDiffractiveCollisions(), G4BinaryCascade::PrintKTVector(), G4VLongitudinalStringDecay::ProduceOneHadron(), G4GeneratorPrecompoundInterface::Propagate(), G4BinaryCascade::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4GammaTransition::SampleTransition(), G4Scatterer::Scatter(), G4VPartonStringModel::Scatter(), G4LightTargetCollider::SingleNucleonScattering(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitLast(), G4QGSDiffractiveExcitation::String(), and G4RKPropagation::Transport().
double CLHEP::HepLorentzVector::mag2 () const inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Annihilate(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::CorrectFinalPandE(), G4BinaryCascade::CorrectShortlivedFinalsForFermi(), G4QGSParticipants::DeterminePartonMomenta(), G4ElasticHNScattering::ElasticScattering(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4VElasticCollision::FinalState(), G4KineticTrack::GetActualMass(), G4MesonAbsorption::GetTimeToAbsorption(), howNear(), isNear(), G4FragmentingString::Mass2(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4AntiNuclElastic::SampleInvariantT(), G4KineticTrack::SetTrackingMomentum(), G4KineticTrack::Update4Momentum(), and G4KineticTrack::UpdateTrackingMomentum().
double CLHEP::HepLorentzVector::minus () const inline
Referenced by G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), G4FragmentingString::G4FragmentingString(), G4FragmentingString::LorentzRotate(), G4QGSDiffractiveExcitation::String(), G4FragmentingString::TransformToAlignedCms(), and G4FragmentingString::TransformToCenterOfMass().
double CLHEP::HepLorentzVector::minus (const Hep3Vector & ref) const
Definition at line 55 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 55 of file LorentzVectorK.cc
References CLHEP::Hep3Vector::dot(), ee, CLHEP::Hep3Vector::mag(), pp, and r.
double CLHEP::HepLorentzVector::mt () const inline
Referenced by pysugi(), pytbhb(), pytbhg(), pytbhq(), and quench().
double CLHEP::HepLorentzVector::mt2 () const inline
CLHEP::HepLorentzVector::operator const Hep3Vector & () const inline
CLHEP::HepLorentzVector::operator Hep3Vector & () inline
bool CLHEP::HepLorentzVector::operator!= (const HepLorentzVector &) const inline
double CLHEP::HepLorentzVector::operator() (int i) const
Definition at line 25 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 25 of file LorentzVector.cc
References e(), pp, T, X, Y, and Z.
double & CLHEP::HepLorentzVector::operator() (int i)
Definition at line 40 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 40 of file LorentzVector.cc
References ee, pp, T, X, Y, and Z.
double CLHEP::HepLorentzVector::operator* (const HepLorentzVector &) const inline
HepLorentzVector& CLHEP::HepLorentzVector::operator*= (double) inline
HepLorentzVector& CLHEP::HepLorentzVector::operator*= (const HepRotation &) inline
HepLorentzVector & CLHEP::HepLorentzVector::operator*= (const HepLorentzRotation & m1)
Definition at line 21 of file LorentzVectorL.cc.
View newest version in sPHENIX GitHub at line 21 of file LorentzVectorL.cc
References CLHEP::HepLorentzRotation::vectorMultiplication().
HepLorentzVector CLHEP::HepLorentzVector::operator+ (const HepLorentzVector &) const inline
HepLorentzVector& CLHEP::HepLorentzVector::operator+= (const HepLorentzVector &) inline
HepLorentzVector CLHEP::HepLorentzVector::operator- (const HepLorentzVector &) const inline
HepLorentzVector CLHEP::HepLorentzVector::operator- () const inline
HepLorentzVector& CLHEP::HepLorentzVector::operator-= (const HepLorentzVector &) inline
HepLorentzVector & CLHEP::HepLorentzVector::operator/= (double c)
Definition at line 151 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 151 of file LorentzVector.cc
References c, ee, and pp.
bool CLHEP::HepLorentzVector::operator< (const HepLorentzVector & w) const
Definition at line 41 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 41 of file LorentzVectorC.cc
References compare().
bool CLHEP::HepLorentzVector::operator<= (const HepLorentzVector & w) const
Definition at line 47 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 47 of file LorentzVectorC.cc
References compare().
HepLorentzVector& CLHEP::HepLorentzVector::operator= (const HepLorentzVector &) inline
HepLorentzVector& CLHEP::HepLorentzVector::operator= (HepLorentzVector &&) inline default
HepLorentzVector& CLHEP::HepLorentzVector::operator= (const Hep3Vector & v) inline
bool CLHEP::HepLorentzVector::operator== (const HepLorentzVector &) const inline
bool CLHEP::HepLorentzVector::operator> (const HepLorentzVector & w) const
Definition at line 38 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 38 of file LorentzVectorC.cc
References compare().
bool CLHEP::HepLorentzVector::operator>= (const HepLorentzVector & w) const
Definition at line 44 of file LorentzVectorC.cc.
View newest version in sPHENIX GitHub at line 44 of file LorentzVectorC.cc
References compare().
double CLHEP::HepLorentzVector::operator[] (int) const inline
double& CLHEP::HepLorentzVector::operator[] (int) inline
double CLHEP::HepLorentzVector::perp () const inline
double CLHEP::HepLorentzVector::perp (const Hep3Vector &) const inline
double CLHEP::HepLorentzVector::perp2 () const inline
Referenced by G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4QGSDiffractiveExcitation::String().
double CLHEP::HepLorentzVector::perp2 (const Hep3Vector &) const inline
double CLHEP::HepLorentzVector::phi () const inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4INCLXXInterface::ApplyYourself(), G4Pythia6Decayer::Decay(), G4MesonAbsorption::GetFinalState(), G4HadProjectile::InitialiseLocal(), and G4VPartonStringModel::Scatter().
double CLHEP::HepLorentzVector::plus () const inline
Referenced by G4QGSMSplitableHadron::DiffractiveSplitUp(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), G4FragmentingString::G4FragmentingString(), G4FragmentingString::LorentzRotate(), G4QGSDiffractiveExcitation::String(), G4FragmentingString::TransformToAlignedCms(), and G4FragmentingString::TransformToCenterOfMass().
double CLHEP::HepLorentzVector::plus (const Hep3Vector & ref) const
Definition at line 44 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 44 of file LorentzVectorK.cc
References CLHEP::Hep3Vector::dot(), ee, CLHEP::Hep3Vector::mag(), pp, and r.
double CLHEP::HepLorentzVector::pseudoRapidity () const inline
double CLHEP::HepLorentzVector::px () const inline
Referenced by G4ParticleHPElasticFS::ApplyYourself(), avscatcen(), G4CascadeCheckBalance::collide(), G4DiffractiveExcitation::CreateStrings(), G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4EquilibriumEvaporator::deExcite(), G4Parton::DefineMomentumInZ(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4CascadeRecoilMaker::fillRecoil(), CexmcReimplementedGenbod::Generate(), getscatterer(), getsscat(), hijsrt(), luptdi(), lustrf(), maxscatcen(), G4InuclParticle::print(), G4LorentzConvertor::printBullet(), G4LorentzConvertor::printTarget(), pwithpF(), pyhiscat(), pyptdi(), pyscat(), pystrf(), G4eeTo3PiModel::SampleSecondaries(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4QGSDiffractiveExcitation::String().
double CLHEP::HepLorentzVector::py () const inline
Referenced by G4ParticleHPElasticFS::ApplyYourself(), avscatcen(), G4CascadeCheckBalance::collide(), G4DiffractiveExcitation::CreateStrings(), G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4EquilibriumEvaporator::deExcite(), G4Parton::DefineMomentumInZ(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4CascadeRecoilMaker::fillRecoil(), CexmcReimplementedGenbod::Generate(), getscatterer(), getsscat(), hijsrt(), luptdi(), lustrf(), maxscatcen(), G4InuclParticle::print(), G4LorentzConvertor::printBullet(), G4LorentzConvertor::printTarget(), pwithpF(), pyhiscat(), pyptdi(), pyscat(), pystrf(), G4eeTo3PiModel::SampleSecondaries(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4QGSDiffractiveExcitation::String().
double CLHEP::HepLorentzVector::pz () const inline
Referenced by __example_6.f__(), __example_7.f__(), __example_8.f__(), G4ParticleHPElasticFS::ApplyYourself(), avscatcen(), G4CascadeCheckBalance::collide(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::CreateStrings(), G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4EquilibriumEvaporator::deExcite(), G4QGSParticipants::DeterminePartonMomenta(), G4CascadeRecoilMaker::fillRecoil(), G4QGSMFragmentation::FragmentString(), G4FragmentingString::G4FragmentingString(), CexmcReimplementedGenbod::Generate(), getqvec(), getscatterer(), getsscat(), G4HadProjectile::GetTotalMomentum(), hijsrt(), makeinsplit(), makesplitting(), maxscatcen(), G4InuclParticle::print(), G4LorentzConvertor::printBullet(), G4LorentzConvertor::printTarget(), pwithpF(), pybesq(), pydiff(), pyhidiff(), pyhiremn(), pyhiscat(), pyremn(), pyscat(), G4eeTo3PiModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4QGSParticipants::SamplingNucleonKinematics(), and G4FTFModel::SamplingNucleonKinematics().
double CLHEP::HepLorentzVector::rapidity () const
Definition at line 128 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 128 of file LorentzVectorK.cc
References ee, CLHEP::Hep3Vector::getZ(), pp, and z1.
Referenced by G4FTFModel::AdjustNucleons(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::ExciteParticipants(), G4QGSParticipants::PutOnMassShell(), and G4FTFModel::PutOnMassShell().
double CLHEP::HepLorentzVector::rapidity (const Hep3Vector & ref) const
Definition at line 147 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 147 of file LorentzVectorK.cc
References CLHEP::Hep3Vector::dot(), ee, CLHEP::Hep3Vector::mag2(), pp, and r.
HepLorentzVector CLHEP::HepLorentzVector::rest4Vector () const
Definition at line 66 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 66 of file LorentzVectorK.cc
References HepLorentzVector(), m(), and t().
double CLHEP::HepLorentzVector::restMass () const inline
double CLHEP::HepLorentzVector::restMass2 () const inline
Referenced by boostVector(), and howLightlike().
double CLHEP::HepLorentzVector::rho () const inline
Referenced by G4INCLXXInterface::ApplyYourself(), G4CascadeInterface::createBullet(), G4CascadeCheckBalance::deltaP(), G4CascadeFinalStateAlgorithm::FillDirManyBody(), G4BigBanger::generateBangInSCM(), G4ElementaryParticleCollider::generateSCMpionNAbsorption(), G4LorentzConvertor::getSCMMomentum(), G4LorentzConvertor::getTRSMomentum(), G4NucleiModel::initializeCascad(), G4CascadeCoalescence::maxDeltaP(), G4InuclParticle::print(), G4CascadeCheckBalance::relativeP(), G4QuasiElRatios::RelDecayIn2(), G4CollisionOutput::setOnShell(), and G4CascadeRecoilMaker::wholeEvent().
HepLorentzVector & CLHEP::HepLorentzVector::rotate (double a, const Hep3Vector & v1)
Definition at line 19 of file LorentzVectorR.cc.
View newest version in sPHENIX GitHub at line 19 of file LorentzVectorR.cc
References pp, and CLHEP::Hep3Vector::rotate().
Referenced by G4MuonicAtomDecay::FillResult(), and CLHEP::rotationOf().
HepLorentzVector & CLHEP::HepLorentzVector::rotate (const Hep3Vector & axis, double delta)
Definition at line 24 of file LorentzVectorR.cc.
View newest version in sPHENIX GitHub at line 24 of file LorentzVectorR.cc
References pp, and CLHEP::Hep3Vector::rotate().
HepLorentzVector & CLHEP::HepLorentzVector::rotate (const HepAxisAngle & ax)
Definition at line 30 of file LorentzVectorR.cc.
View newest version in sPHENIX GitHub at line 30 of file LorentzVectorR.cc
References pp, and CLHEP::Hep3Vector::rotate().
HepLorentzVector & CLHEP::HepLorentzVector::rotate (const HepEulerAngles & e)
Definition at line 35 of file LorentzVectorR.cc.
View newest version in sPHENIX GitHub at line 35 of file LorentzVectorR.cc
References pp, and CLHEP::Hep3Vector::rotate().
HepLorentzVector & CLHEP::HepLorentzVector::rotate (double phi, double theta, double psi)
Definition at line 40 of file LorentzVectorR.cc.
View newest version in sPHENIX GitHub at line 40 of file LorentzVectorR.cc
References pp, and CLHEP::Hep3Vector::rotate().
HepLorentzVector & CLHEP::HepLorentzVector::rotateUz (const Hep3Vector & v1)
Definition at line 84 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 84 of file LorentzVector.cc
References pp, and CLHEP::Hep3Vector::rotateUz().
Referenced by G4eeTo3PiModel::SampleSecondaries().
HepLorentzVector & CLHEP::HepLorentzVector::rotateX (double a)
Definition at line 71 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 71 of file LorentzVector.cc
References pp, and CLHEP::Hep3Vector::rotateX().
Referenced by CLHEP::rotationXOf().
HepLorentzVector & CLHEP::HepLorentzVector::rotateY (double a)
Definition at line 75 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 75 of file LorentzVector.cc
References pp, and CLHEP::Hep3Vector::rotateY().
Referenced by G4QGSParticipants::DeterminePartonMomenta(), G4ElasticHNScattering::ElasticScattering(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4MesonAbsorption::GetFinalState(), CLHEP::rotationYOf(), and G4FragmentingString::TransformToAlignedCms().
HepLorentzVector & CLHEP::HepLorentzVector::rotateZ (double a)
Definition at line 79 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 79 of file LorentzVector.cc
References pp, and CLHEP::Hep3Vector::rotateZ().
Referenced by G4QGSParticipants::DeterminePartonMomenta(), G4ElasticHNScattering::ElasticScattering(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4MesonAbsorption::GetFinalState(), CLHEP::rotationZOf(), and G4FragmentingString::TransformToAlignedCms().
void CLHEP::HepLorentzVector::set (double x, double y, double z, double t) inline
Referenced by G4LowEGammaNuclearModel::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4UnstableFragmentBreakUp::BreakUpChain(), G4HadProjectile::G4HadProjectile(), G4CascadeCoalescence::getClusterMomentum(), G4HadProjectile::InitialiseLocal(), G4FermiBreakUpVI::SampleDecay(), G4eeTo3PiModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4GammaTransition::SampleTransition(), and G4Fragment::SetExcEnergyAndMomentum().
void CLHEP::HepLorentzVector::set (double x, double y, double z, Tcomponent t) inline
void CLHEP::HepLorentzVector::set (Tcomponent t, double x, double y, double z) inline
void CLHEP::HepLorentzVector::set (double t) inline
void CLHEP::HepLorentzVector::set (Tcomponent t) inline
void CLHEP::HepLorentzVector::set (const Hep3Vector & v) inline
void CLHEP::HepLorentzVector::set (const Hep3Vector & v, double t) inline
void CLHEP::HepLorentzVector::set (double t, const Hep3Vector & v) inline
void CLHEP::HepLorentzVector::setE (double) inline
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4WilsonAbrasionModel::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4Nucleon::Boost(), G4StatMF::BreakItUp(), G4WilsonAblationModel::BreakItUp(), G4QGSParticipants::BuildInteractions(), G4BinaryCascade::BuildTargetList(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4DiffractiveExcitation::CreateStrings(), G4CollisionNN::CrossSection(), G4FermiPhaseSpaceDecay::Decay(), G4BinaryCascade::DecayVoidNucleus(), G4Parton::DefineMomentumInZ(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4ExcitedStringDecay::FragmentStrings(), G4KineticTrack::G4KineticTrack(), G4VSplitableHadron::G4VSplitableHadron(), G4FragmentingString::Get4Momentum(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4FTFModel::Init(), G4NucleiModel::initializeCascad(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QuasiElRatios::RelDecayIn2(), G4QGSMFragmentation::Sample4Momentum(), G4LundStringFragmentation::Sample4Momentum(), G4AntiNuclElastic::SampleInvariantT(), G4QuasiElasticChannel::Scatter(), G4KineticTrack::SetTrackingMomentum(), and G4QGSDiffractiveExcitation::String().
ZMpvMetric_t CLHEP::HepLorentzVector::setMetric (ZMpvMetric_t met) static
Definition at line 25 of file LorentzVectorK.cc.
View newest version in sPHENIX GitHub at line 25 of file LorentzVectorK.cc
References metric, CLHEP::TimeNegative, and CLHEP::TimePositive.
Referenced by CLHEP::HepLorentzRotation::set().
void CLHEP::HepLorentzVector::setPerp (double) inline
void CLHEP::HepLorentzVector::setPhi (double) inline
void CLHEP::HepLorentzVector::setPx (double) inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), CexmcReimplementedGenbod::Generate(), G4QGSMFragmentation::Sample4Momentum(), G4LundStringFragmentation::Sample4Momentum(), G4AntiNuclElastic::SampleInvariantT(), and G4QGSDiffractiveExcitation::String().
void CLHEP::HepLorentzVector::setPy (double) inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), CexmcReimplementedGenbod::Generate(), G4QGSMFragmentation::Sample4Momentum(), G4LundStringFragmentation::Sample4Momentum(), G4AntiNuclElastic::SampleInvariantT(), and G4QGSDiffractiveExcitation::String().
void CLHEP::HepLorentzVector::setPz (double) inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4DiffractiveExcitation::CreateStrings(), G4Parton::DefineMomentumInZ(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), CexmcReimplementedGenbod::Generate(), G4FragmentingString::Get4Momentum(), G4QGSMFragmentation::Sample4Momentum(), G4LundStringFragmentation::Sample4Momentum(), G4AntiNuclElastic::SampleInvariantT(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), and G4QGSDiffractiveExcitation::String().
void CLHEP::HepLorentzVector::setREtaPhi (double r, double eta, double phi) inline
void CLHEP::HepLorentzVector::setRho (double) inline
void CLHEP::HepLorentzVector::setRhoPhiZ (double rho, double phi, double z) inline
void CLHEP::HepLorentzVector::setRThetaPhi (double r, double theta, double phi) inline
void CLHEP::HepLorentzVector::setT (double) inline
Referenced by G4BinaryLightIonReaction::ApplyYourself(), G4DiffractiveExcitation::CreateStrings(), and CLHEP::operator>>().
void CLHEP::HepLorentzVector::setTheta (double) inline
double CLHEP::HepLorentzVector::setTolerance (double tol) static
Definition at line 241 of file LorentzVector.cc.
View newest version in sPHENIX GitHub at line 241 of file LorentzVector.cc
References tolerance.
void CLHEP::HepLorentzVector::setV (const Hep3Vector &) inline
void CLHEP::HepLorentzVector::setV (double x, double y, double z) inline
void CLHEP::HepLorentzVector::setVect (const Hep3Vector &) inline
Referenced by G4LightTargetCollider::AbsorptionOnDeuteron(), G4ParticleHPElasticFS::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4Nucleon::Boost(), G4NucleiModel::boundaryTransition(), G4StatMF::BreakItUp(), G4QGSParticipants::BuildInteractions(), G4FermiPhaseSpaceDecay::Decay(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4VSplitableHadron::G4VSplitableHadron(), G4FTFModel::Init(), G4NucleiModel::initializeCascad(), G4QuasiElRatios::RelDecayIn2(), G4LorentzConvertor::rotate(), and G4LorentzConvertor::toTheCenterOfMass().
void CLHEP::HepLorentzVector::setVectM (const Hep3Vector & spatial, double mass) inline
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4Fissioner::deExcite(), G4CascadeFinalStateAlgorithm::FillUsingKopylov(), G4HadPhaseSpaceKopylov::GenerateMultiBody(), G4ElementaryParticleCollider::generateSCMpionAbsorption(), G4InuclSpecialFunctions::generateWithFixedTheta(), G4InuclSpecialFunctions::generateWithRandomAngles(), G4CascadeDeexciteBase::makeFragment(), QAG4SimulationKFParticle::makeHepLV(), G4CascadeRecoilMaker::makeRecoilFragment(), QAG4SimulationUpsilon::process_event(), G4LorentzConvertor::setBullet(), G4CollisionOutput::setOnShell(), and G4LorentzConvertor::setTarget().
void CLHEP::HepLorentzVector::setVectMag (const Hep3Vector & spatial, double magnitude) inline
void CLHEP::HepLorentzVector::setX (double) inline
Referenced by G4BinaryLightIonReaction::Interact(), CLHEP::operator>>(), HepMCNodeReader::process_event(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), and G4IonCoulombScatteringModel::SampleSecondaries().
void CLHEP::HepLorentzVector::setY (double) inline
Referenced by G4BinaryLightIonReaction::Interact(), CLHEP::operator>>(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), and G4IonCoulombScatteringModel::SampleSecondaries().
void CLHEP::HepLorentzVector::setZ (double) inline
Referenced by G4CollisionOutput::boostToLabFrame(), G4InuclCollider::collide(), G4BinaryLightIonReaction::Interact(), CLHEP::operator>>(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), and G4IonCoulombScatteringModel::SampleSecondaries().
double CLHEP::HepLorentzVector::t () const inline
Referenced by G4MesonAbsorption::AbsorptionCrossSection(), MCTruthManager::AddParticle(), CLHEP::HepLorentzRotation::boostX(), CLHEP::HepLorentzRotation::boostY(), CLHEP::HepLorentzRotation::boostZ(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4MesonAbsorption::GetFinalState(), G4BinaryLightIonReaction::GetProjectileExcitation(), operator<<(), CLHEP::operator<<(), G4DecayStrongResonances::Propagate(), rest4Vector(), CLHEP::HepLorentzRotation::rotateX(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4Scatterer::Scatter(), CLHEP::HepLorentzRotation::set(), and G4DynamicParticle::Set4Momentum().
double CLHEP::HepLorentzVector::theta () const inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4INCLXXInterface::ApplyYourself(), G4Pythia6Decayer::Decay(), G4MesonAbsorption::GetFinalState(), G4HadProjectile::InitialiseLocal(), and G4VPartonStringModel::Scatter().
HepLorentzVector& CLHEP::HepLorentzVector::transform (const HepRotation &) inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::DeterminePartonMomenta(), G4ElasticHNScattering::ElasticScattering(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4QGSParticipants::PutOnMassShell(), G4FTFModel::PutOnMassShell(), and G4BetheHeitler5DModel::SampleSecondaries().
HepLorentzVector & CLHEP::HepLorentzVector::transform (const HepLorentzRotation & m1)
Definition at line 26 of file LorentzVectorL.cc.
View newest version in sPHENIX GitHub at line 26 of file LorentzVectorL.cc
References CLHEP::HepLorentzRotation::vectorMultiplication().
Hep3Vector CLHEP::HepLorentzVector::v () const inline
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDCollision::CalFinalStateOfTheBinaryCollision(), and G4QMDMeanField::CalGraduate().
Hep3Vector CLHEP::HepLorentzVector::vect () const inline
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4PreCompoundEmission::AngularDistribution(), G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4LEnp::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LENDModel::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), G4LENDInelastic::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4LFission::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4Nucleon::Boost(), G4NucleiModel::boundaryTransition(), G4InuclEvaporation::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4BinaryCascade::BuildTargetList(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4MuonVDNuclearModel::CalculateEMVertex(), G4RPGInelastic::CalculateMomenta(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4RPGAntiKZeroInelastic::Cascade(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4NucleiModel::choosePointAlongTraj(), G4Fancy3DNucleus::ChoosePositions(), G4NeutrinoNucleusModel::CoherentPion(), G4ParticleHPInelasticCompFS::CompositeApply(), G4BinaryCascade::CorrectShortlivedFinalsForFermi(), G4DiffractiveExcitation::CreateStrings(), G4IntraNucleiCascader::decayTrappedParticle(), G4BinaryCascade::DecayVoidNucleus(), G4NonEquilibriumEvaporator::deExcite(), G4Fissioner::deExcite(), G4Fancy3DNucleus::DoLorentzContraction(), G4ElasticHNScattering::ElasticScattering(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4QuarkExchange::ExciteParticipants(), G4SingleDiffractiveExcitation::ExciteParticipants(), G4QGSDiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doDiffraction(), G4DiffractiveExcitation::ExciteParticipants_doNonDiffraction(), G4RKPropagation::FieldTransport(), G4LorentzConvertor::fillKinematics(), G4MuonicAtomDecay::FillResult(), G4BinaryCascade::FillVoidNucleusProducts(), G4NeutrinoNucleusModel::FinalBarion(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4NeutrinoNucleusModel::FinalMomentum(), G4ExcitedStringDecay::FragmentStrings(), G4RKPropagation::FreeTransport(), G4BinaryLightIonReaction::FuseNucleiAndPrompound(), G4FragmentingString::G4FragmentingString(), G4NucleiModel::generateInteractionPartners(), G4ElementaryParticleCollider::generateSCMpionAbsorption(), G4BinaryCascade::GetFinal4Momentum(), G4BinaryCascade::GetFinalNucleusMomentum(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4CascadParticle::getPathToTheNextZone(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4RKPropagation::GetSphereIntersectionTimes(), G4BinaryCascade::GetSpherePoint(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), gustep(), G4NucleiModel::initializeCascad(), G4BinaryLightIonReaction::Interact(), G4CascadeInterface::makeDynamicParticle(), G4CascadeDeexciteBase::makeFragment(), G4CascadeRecoilMaker::makeRecoilFragment(), G4ReactionProduct::operator=(), G4CascadeHistory::PrintEntry(), G4BinaryCascade::PrintKTVector(), G4BinaryCascade::ProductsAddFinalState(), G4DecayStrongResonances::Propagate(), G4GeneratorPrecompoundInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4CascadParticle::propagateAlongThePath(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), pyptfs(), pyshow(), G4QuasiElRatios::RelDecayIn2(), G4LorentzConvertor::rotate(), G4AntiNuclElastic::SampleInvariantT(), G4NuclNuclDiffuseElastic::SampleInvariantT(), G4DiffuseElasticV2::SampleInvariantT(), G4DiffuseElastic::SampleInvariantT(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4Scatterer::Scatter(), G4QuasiElasticChannel::Scatter(), G4DynamicParticle::Set4Momentum(), G4LorentzConvertor::setBullet(), G4InuclParticle::setMomentum(), G4CollisionOutput::setOnShell(), G4LorentzConvertor::setTarget(), G4KineticTrack::SetTrackingMomentum(), G4RPGNeutronInelastic::SlowNeutron(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4LorentzConvertor::toTheCenterOfMass(), G4LorentzConvertor::toTheTargetRestFrame(), G4FragmentingString::TransformToCenterOfMass(), G4RKPropagation::Transport(), G4KineticTrack::Update4Momentum(), and G4KineticTrack::UpdateTrackingMomentum().
double CLHEP::HepLorentzVector::x () const inline
Referenced by MCTruthManager::AddParticle(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LorentzConvertor::backToTheLab(), CLHEP::HepLorentzRotation::boostX(), CLHEP::HepLorentzRotation::boostY(), CLHEP::HepLorentzRotation::boostZ(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4BigBanger::deExcite(), G4AblaInterface::DeExcite(), G4DiffractiveExcitation::ExciteParticipants(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4BigBanger::generateBangInSCM(), G4IntraNucleiCascader::initialize(), operator<<(), CLHEP::operator<<(), G4LorentzConvertor::rotate(), CLHEP::HepLorentzRotation::rotateX(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4eeTo3PiModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), CLHEP::HepLorentzRotation::set(), G4CollisionOutput::setOnShell(), and G4RPGNeutronInelastic::SlowNeutron().
double CLHEP::HepLorentzVector::y () const inline
Referenced by MCTruthManager::AddParticle(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LorentzConvertor::backToTheLab(), CLHEP::HepLorentzRotation::boostX(), CLHEP::HepLorentzRotation::boostY(), CLHEP::HepLorentzRotation::boostZ(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4BigBanger::deExcite(), G4AblaInterface::DeExcite(), G4DiffractiveExcitation::ExciteParticipants(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4BigBanger::generateBangInSCM(), G4IntraNucleiCascader::initialize(), operator<<(), CLHEP::operator<<(), G4LorentzConvertor::rotate(), CLHEP::HepLorentzRotation::rotateX(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4eeTo3PiModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), CLHEP::HepLorentzRotation::set(), G4CollisionOutput::setOnShell(), and G4RPGNeutronInelastic::SlowNeutron().
double CLHEP::HepLorentzVector::z () const inline
Referenced by MCTruthManager::AddParticle(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4LEnp::ApplyYourself(), G4LEpp::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4LorentzConvertor::backToTheLab(), G4CollisionOutput::boostToLabFrame(), CLHEP::HepLorentzRotation::boostX(), CLHEP::HepLorentzRotation::boostY(), CLHEP::HepLorentzRotation::boostZ(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4BigBanger::deExcite(), G4AblaInterface::DeExcite(), G4QGSParticipants::DeterminePartonMomenta(), G4ElasticHNScattering::ElasticScattering(), G4DiffractiveExcitation::ExciteParticipants(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4BigBanger::generateBangInSCM(), G4Scatterer::GetTimeToInteraction(), G4IntraNucleiCascader::initialize(), G4NucleiModel::initializeCascad(), operator<<(), CLHEP::operator<<(), G4LorentzConvertor::reflectionNeeded(), G4LorentzConvertor::rotate(), CLHEP::HepLorentzRotation::rotateX(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4eeTo3PiModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), CLHEP::HepLorentzRotation::set(), G4CollisionOutput::setOnShell(), G4RPGNeutronInelastic::SlowNeutron(), and G4LundStringFragmentation::SplitLast().
Friends And Related Function Documentation
HepLorentzVector boostOf (const HepLorentzVector & vec, const Hep3Vector & betaVector) friend
HepLorentzVector boostOf (const HepLorentzVector & vec, const Hep3Vector & axis, double beta) friend
HepLorentzVector boostXOf (const HepLorentzVector & vec, double beta) friend
HepLorentzVector boostYOf (const HepLorentzVector & vec, double beta) friend
HepLorentzVector boostZOf (const HepLorentzVector & vec, double beta) friend
HepLorentzVector rotationOf (const HepLorentzVector & vec, const Hep3Vector & axis, double delta) friend
HepLorentzVector rotationOf (const HepLorentzVector & vec, const HepAxisAngle & ax) friend
HepLorentzVector rotationOf (const HepLorentzVector & vec, const HepEulerAngles & e) friend
HepLorentzVector rotationOf (const HepLorentzVector & vec, double phi, double theta, double psi) friend
HepLorentzVector rotationXOf (const HepLorentzVector & vec, double delta) friend
HepLorentzVector rotationYOf (const HepLorentzVector & vec, double delta) friend
HepLorentzVector rotationZOf (const HepLorentzVector & vec, double delta) friend
Member Data Documentation
double CLHEP::HepLorentzVector::ee private
Definition at line 529 of file LorentzVector.h.
View newest version in sPHENIX GitHub at line 529 of file LorentzVector.h
Referenced by beta(), boostVector(), boostX(), boostY(), boostZ(), coLinearRapidity(), compare(), findBoostToCM(), gamma(), howLightlike(), howNear(), howNearCM(), invariantMass(), isNear(), isNearCM(), minus(), operator()(), operator/=(), plus(), and rapidity().
double CLHEP::HepLorentzVector::metric = 1.0 static private
Definition at line 532 of file LorentzVector.h.
View newest version in sPHENIX GitHub at line 532 of file LorentzVector.h
Referenced by getMetric(), and setMetric().
Hep3Vector CLHEP::HepLorentzVector::pp private
Definition at line 528 of file LorentzVector.h.
View newest version in sPHENIX GitHub at line 528 of file LorentzVector.h
Referenced by beta(), boostVector(), boostX(), boostY(), boostZ(), coLinearRapidity(), compare(), deltaR(), findBoostToCM(), gamma(), howNear(), howNearCM(), isNear(), isNearCM(), minus(), operator()(), operator/=(), plus(), rapidity(), rotate(), rotateUz(), rotateX(), rotateY(), and rotateZ().
double CLHEP::HepLorentzVector::tolerance static private
Initial value:
=
        Hep3Vector::ToleranceTicks * 2.22045e-16
Definition at line 531 of file LorentzVector.h.
View newest version in sPHENIX GitHub at line 531 of file LorentzVector.h
Referenced by getTolerance(), and setTolerance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/LorentzVector.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzVector.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzVectorB.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzVectorC.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzVectorK.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzVectorL.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/LorentzVectorR.cc