ECCE @ EIC Software: G4RDCrossSectionHandler Class Reference
G4RDCrossSectionHandler Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDCrossSectionHandler.hh>
Public Member Functions
G4RDCrossSectionHandler ()
~G4RDCrossSectionHandler ()
Public Member Functions inherited from G4RDVCrossSectionHandler
G4RDVCrossSectionHandler ()
G4RDVCrossSectionHandler (G4RDVDataSetAlgorithm *interpolation, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int nBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
virtual ~G4RDVCrossSectionHandler ()
void Initialise (G4RDVDataSetAlgorithm *interpolation=0, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int numberOfBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
G4int SelectRandomAtom (const G4MaterialCutsCouple *couple, G4double e) const
const G4Element * SelectRandomElement (const G4MaterialCutsCouple *material, G4double e) const
G4int SelectRandomShell (G4int Z, G4double e) const
G4RDVEMDataSet * BuildMeanFreePathForMaterials (const G4DataVector *energyCuts=0)
G4double FindValue (G4int Z, G4double e) const
G4double FindValue (G4int Z, G4double e, G4int shellIndex) const
G4double ValueForMaterial (const G4Material *material, G4double e) const
void LoadData (const G4String &dataFile)
void LoadShellData (const G4String &dataFile)
void PrintData () const
void Clear ()
Protected Member Functions
virtual std::vector
< G4RDVEMDataSet * > * BuildCrossSectionsForMaterials (const G4DataVector &energyVector, const G4DataVector *energyCuts=0)
Protected Member Functions inherited from G4RDVCrossSectionHandler
G4int NumberOfComponents (G4int Z) const
void ActiveElements ()
virtual G4RDVDataSetAlgorithm * CreateInterpolation ()
const G4RDVDataSetAlgorithm * GetInterpolation () const
Private Member Functions
G4RDCrossSectionHandler (const G4RDCrossSectionHandler &)
G4RDCrossSectionHandler & operator= (const G4RDCrossSectionHandler &right)
Detailed Description
Definition at line 57 of file G4RDCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 57 of file G4RDCrossSectionHandler.hh
Constructor & Destructor Documentation
G4RDCrossSectionHandler::G4RDCrossSectionHandler ()
Definition at line 53 of file G4RDCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 53 of file G4RDCrossSectionHandler.cc
G4RDCrossSectionHandler::~G4RDCrossSectionHandler ()
Definition at line 56 of file G4RDCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 56 of file G4RDCrossSectionHandler.cc
G4RDCrossSectionHandler::G4RDCrossSectionHandler (const G4RDCrossSectionHandler &) private
Member Function Documentation
std::vector< G4RDVEMDataSet * > * G4RDCrossSectionHandler::BuildCrossSectionsForMaterials (const G4DataVector & energyVector, const G4DataVector * energyCuts = 0) protected virtual
Implements G4RDVCrossSectionHandler.
Definition at line 60 of file G4RDCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 60 of file G4RDCrossSectionHandler.cc
References G4RDVEMDataSet::AddComponent(), bin, G4RDVDataSetAlgorithm::Clone(), G4RDVCrossSectionHandler::CreateInterpolation(), Acts::VectorHelpers::cross(), e, G4RDVCrossSectionHandler::FindValue(), G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetNumberOfElements(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), m, material(), and Z.
G4RDCrossSectionHandler& G4RDCrossSectionHandler::operator= (const G4RDCrossSectionHandler & right) private
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDCrossSectionHandler.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDCrossSectionHandler.cc