ECCE @ EIC Software: XPhysicsList Class Reference
XPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/phonon/include/XPhysicsList.hh>
Public Member Functions
XPhysicsList (G4int verbose=0)
~XPhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
virtual void TerminateWorker ()
Additional Inherited Members
Static Public Member Functions inherited from G4VUserPhysicsList
static const G4VUPLManager & GetSubInstanceManager ()
Protected Member Functions inherited from G4VUserPhysicsList
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Protected Attributes inherited from G4VUserPhysicsList
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Static Protected Attributes inherited from G4VUserPhysicsList
static G4RUN_DLL G4VUPLManager subInstanceManager
Detailed Description
Definition at line 38 of file XPhysicsList.hh.
View newest version in sPHENIX GitHub at line 38 of file XPhysicsList.hh
Constructor & Destructor Documentation
XPhysicsList::XPhysicsList (G4int verbose = 0)
Definition at line 47 of file XPhysicsList.cc.
View newest version in sPHENIX GitHub at line 47 of file XPhysicsList.cc
References G4cout, G4endl, mm, G4VUserPhysicsList::SetDefaultCutValue(), and G4VUserPhysicsList::SetVerboseLevel().
XPhysicsList::~XPhysicsList ()
Definition at line 56 of file XPhysicsList.cc.
View newest version in sPHENIX GitHub at line 56 of file XPhysicsList.cc
Member Function Documentation
void XPhysicsList::ConstructParticle (void) virtual
Implements G4VUserPhysicsList.
Definition at line 60 of file XPhysicsList.cc.
View newest version in sPHENIX GitHub at line 60 of file XPhysicsList.cc
References G4PhononLong::PhononDefinition(), G4PhononTransSlow::PhononDefinition(), and G4PhononTransFast::PhononDefinition().
void XPhysicsList::ConstructProcess (void) virtual
Implements G4VUserPhysicsList.
Definition at line 68 of file XPhysicsList.cc.
View newest version in sPHENIX GitHub at line 68 of file XPhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), G4VUserPhysicsList::AddTransportation(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), G4VProcess::IsApplicable(), particle, G4VProcess::SetVerboseLevel(), and G4VUserPhysicsList::verboseLevel.
void XPhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 96 of file XPhysicsList.cc.
View newest version in sPHENIX GitHub at line 96 of file XPhysicsList.cc
References G4VUserPhysicsList::SetCutsWithDefault().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/phonon/include/XPhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/phonon/src/XPhysicsList.cc