ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/xDataTOM_importXML_XYs.cc File Reference
xDataTOM_importXML_XYs.cc File Reference
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <ctype.h>
#include "xDataTOM_importXML_private.h"
Functions
static int xDataXML_XYsDataToTOM2 (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_xDataInfo *xDI, int index, int length, double value, double accuracy)
int xDataXML_XYsToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE)
int xDataXML_XYsDataToTOM (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_XYs *XYs, int index, int length, double value, double accuracy, enum xDataTOM_subAxesType subAxesType, int axesOffest, xDataTOM_axes *axes, xDataTOM_interpolation *interpolation)
int xDataXML_stringToDoubles (statusMessageReporting *smr, xDataXML_element *XE, char const *s1, int length, double *d1)
Function Documentation
int xDataXML_stringToDoubles (statusMessageReporting * smr, xDataXML_element * XE, char const * s1, int length, double * d1)
Definition at line 96 of file xDataTOM_importXML_XYs.cc.
View newest version in sPHENIX GitHub at line 96 of file xDataTOM_importXML_XYs.cc
References e1, BTOF::length, smr_setReportError3, xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), and xDataXML_stringTo_double().
Referenced by xDataXML_KalbachMannCoefficientsToTOM(), xDataXML_LegendreSeriesDataToTOM(), xDataXML_polynomialToTOM(), and xDataXML_XYsDataToTOM().
int xDataXML_XYsDataToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_XYs * XYs, int index, int length, double value, double accuracy, enum xDataTOM_subAxesType subAxesType, int axesOffest, xDataTOM_axes * axes, xDataTOM_interpolation * interpolation)
Definition at line 76 of file xDataTOM_importXML_XYs.cc.
View newest version in sPHENIX GitHub at line 76 of file xDataTOM_importXML_XYs.cc
References xDataTOM_XYs_s::accuracy, xDataTOM_XYs_s::data, check_license::err(), xDataTOM_XYs_s::index, BTOF::length, xDataTOM_XYs_s::length, smr_freeMemory(), smr_malloc2, xDataTOM_XYs_s::subAxes, xDataXML_text_s::text, xDataXML_element_s::text, xDataTOM_XYs_s::value, xDataTOM_subAxes_initialize(), and xDataXML_stringToDoubles().
Referenced by xDataXML_regionsXYs_XYsToTOM(), xDataXML_W_XYs_XYsToTOM(), and xDataXML_XYsDataToTOM2().
static int xDataXML_XYsDataToTOM2 (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_xDataInfo * xDI, int index, int length, double value, double accuracy) static
Definition at line 57 of file xDataTOM_importXML_XYs.cc.
View newest version in sPHENIX GitHub at line 57 of file xDataTOM_importXML_XYs.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, check_license::err(), xDataTOM_xDataInfo_s::ID, smr_freeMemory(), smr_malloc2, xDataTOM_subAxesType_proxy, xDataTOM_XYs_ID, and xDataXML_XYsDataToTOM().
Referenced by xDataXML_XYsToTOM().
int xDataXML_XYsToTOM (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE)
Definition at line 22 of file xDataTOM_importXML_XYs.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_importXML_XYs.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::element, check_license::err(), BTOF::length, xDataXML_element_s::name, smr_setReportError3p, xDataTOM_element_s::xDataInfo, xDataTOM_smrLibraryID, xDataXML_axesElememtToTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), and xDataXML_XYsDataToTOM2().
Referenced by xDataXML_constructTOM().