ECCE @ EIC Software: B03Run Class Reference
B03Run Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/include/B03Run.hh>
Public Member Functions
B03Run (const std::vector< G4String > mfdName)
virtual ~B03Run ()
virtual void RecordEvent (const G4Event *)
G4int GetNumberOfHitsMap () const
G4THitsMap< G4double > * GetHitsMap (G4int i)
G4THitsMap< G4double > * GetHitsMap (const G4String &detName, const G4String &colName)
G4THitsMap< G4double > * GetHitsMap (const G4String &fullName)
void DumpAllScorer ()
virtual void Merge (const G4Run *)
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
std::vector< G4String > fCollName
std::vector< G4int > fCollID
std::vector< G4THitsMap
< G4double > * > fRunMap
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Definition at line 49 of file B03Run.hh.
View newest version in sPHENIX GitHub at line 49 of file B03Run.hh
Constructor & Destructor Documentation
B03Run::B03Run (const std::vector< G4String > mfdName)
Definition at line 69 of file B03Run.cc.
View newest version in sPHENIX GitHub at line 69 of file B03Run.cc
References fCollID, fCollName, G4SDManager::FindSensitiveDetector(), fRunMap, G4cout, G4endl, G4SDManager::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4MultiFunctionalDetector::GetNumberOfPrimitives(), G4MultiFunctionalDetector::GetPrimitive(), and G4SDManager::GetSDMpointer().
B03Run::~B03Run () virtual
Definition at line 117 of file B03Run.cc.
View newest version in sPHENIX GitHub at line 117 of file B03Run.cc
References fCollID, fCollName, and fRunMap.
Member Function Documentation
void B03Run::DumpAllScorer ()
Definition at line 197 of file B03Run.cc.
View newest version in sPHENIX GitHub at line 197 of file B03Run.cc
References G4VTHitsMap< T, Map_t >::entries(), G4cout, G4endl, GetHitsMap(), G4VTHitsMap< T, Map_t >::GetMap(), G4VHitsCollection::GetName(), GetNumberOfHitsMap(), G4VHitsCollection::GetSDname(), and n.
G4THitsMap<G4double>* B03Run::GetHitsMap (G4int i) inline
Definition at line 69 of file B03Run.hh.
View newest version in sPHENIX GitHub at line 69 of file B03Run.hh
References fRunMap.
Referenced by DumpAllScorer(), B03RunAction::EndOfRunAction(), and GetHitsMap().
G4THitsMap< G4double > * B03Run::GetHitsMap (const G4String & detName, const G4String & colName)
Definition at line 170 of file B03Run.cc.
View newest version in sPHENIX GitHub at line 170 of file B03Run.cc
References G4cout, G4endl, and GetHitsMap().
G4THitsMap< G4double > * B03Run::GetHitsMap (const G4String & fullName)
Definition at line 182 of file B03Run.cc.
View newest version in sPHENIX GitHub at line 182 of file B03Run.cc
References fCollName, fRunMap, G4cout, and G4endl.
G4int B03Run::GetNumberOfHitsMap () const inline
Definition at line 65 of file B03Run.hh.
View newest version in sPHENIX GitHub at line 65 of file B03Run.hh
References fRunMap.
Referenced by DumpAllScorer().
void B03Run::Merge (const G4Run * aRun) virtual
Reimplemented from G4Run.
Definition at line 220 of file B03Run.cc.
View newest version in sPHENIX GitHub at line 220 of file B03Run.cc
References fCollID, fRunMap, and G4Run::Merge().
void B03Run::RecordEvent (const G4Event * aEvent) virtual
Reimplemented from G4Run.
Definition at line 134 of file B03Run.cc.
View newest version in sPHENIX GitHub at line 134 of file B03Run.cc
References fCollID, fRunMap, G4cout, G4endl, G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), and G4Run::numberOfEvent.
Member Data Documentation
std::vector<G4int> B03Run::fCollID private
Definition at line 81 of file B03Run.hh.
View newest version in sPHENIX GitHub at line 81 of file B03Run.hh
Referenced by B03Run(), Merge(), RecordEvent(), and ~B03Run().
std::vector<G4String> B03Run::fCollName private
Definition at line 80 of file B03Run.hh.
View newest version in sPHENIX GitHub at line 80 of file B03Run.hh
Referenced by B03Run(), GetHitsMap(), and ~B03Run().
std::vector<G4THitsMap<G4double>*> B03Run::fRunMap private
Definition at line 82 of file B03Run.hh.
View newest version in sPHENIX GitHub at line 82 of file B03Run.hh
Referenced by B03Run(), GetHitsMap(), GetNumberOfHitsMap(), Merge(), RecordEvent(), and ~B03Run().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/include/B03Run.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/B03/src/B03Run.cc