ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/processes/pyG4EmCalculator.cc File Reference
pyG4EmCalculator.cc File Reference
#include <boost/python.hpp>
#include "G4Version.hh"
#include "G4EmCalculator.hh"
#include "G4Region.hh"
#include "G4Material.hh"
#include "G4Element.hh"
#include "G4ParticleDefinition.hh"
#include "G4MaterialCutsCouple.hh"
Namespaces
namespace pyG4EmCalculator
Functions
pyG4EmCalculator::BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS (f_ComputeCrossSectionPerAtom, ComputeCrossSectionPerAtom, 5, 6) BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(g_ComputeCrossSectionPerAtom
void export_G4EmCalculator ()
Variables
G4double(G4EmCalculator::* pyG4EmCalculator::f1_GetDEDX)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetDEDX
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetDEDX)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetDEDX
G4double(G4EmCalculator::* pyG4EmCalculator::f1_GetRange)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetRange
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetRange)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetRange
G4double(G4EmCalculator::* pyG4EmCalculator::f1_GetKinEnergy)(G4double, const G4ParticleDefinition *, const G4Material *, const G4Region *) = &G4EmCalculator::GetKinEnergy
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetKinEnergy)(G4double, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetKinEnergy
G4double(G4EmCalculator::* pyG4EmCalculator::f1_GetCrossSectionPerVolume)(G4double, const G4ParticleDefinition *, const G4String &, const G4Material *, const G4Region *) = &G4EmCalculator::GetCrossSectionPerVolume
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetCrossSectionPerVolume)(G4double, const G4String &, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetCrossSectionPerVolume
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_GetCrossSectionPerVolume,
GetCrossSectionPerVolume,
4, 5) G4double(G4EmCalculator
G4double(G4EmCalculator::* pyG4EmCalculator::f2_GetMeanFreePath)(G4double, const G4String &, const G4String &, const G4String &, const G4String &) = &G4EmCalculator::GetMeanFreePath
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_GetMeanFreePath,
GetMeanFreePath,
4, 5) G4double(G4EmCalculator
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeDEDX)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeDEDX
G4double(G4EmCalculator::* pyG4EmCalculator::f1_ComputeNuclearDEDX)(G4double, const G4ParticleDefinition *, const G4Material *) = &G4EmCalculator::ComputeNuclearDEDX
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeNuclearDEDX)(G4double, const G4String &, const G4String &) = &G4EmCalculator::ComputeNuclearDEDX
G4double(G4EmCalculator::* pyG4EmCalculator::f1_ComputeElectronicDEDX)(G4double, const G4ParticleDefinition *, const G4Material *, G4double) = &G4EmCalculator::ComputeElectronicDEDX
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeElectronicDEDX)(G4double, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeElectronicDEDX
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_ComputeElectronicDEDX,
ComputeElectronicDEDX,
3, 4) G4double(G4EmCalculator
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeTotalDEDX)(G4double, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeTotalDEDX
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_ComputeTotalDEDX,
ComputeTotalDEDX,
3, 4) G4double(G4EmCalculator
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeCrossSectionPerVolume)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeCrossSectionPerVolume
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(f_ComputeCrossSectionPerVolume,
ComputeCrossSectionPerVolume,
4, 5) G4double(G4EmCalculator
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeCrossSectionPerAtom)(G4double, const G4String &, const G4String &, const G4Element *, G4double) = &G4EmCalculator::ComputeCrossSectionPerAtom
pyG4EmCalculator::ComputeCrossSectionPerAtom
G4double(G4EmCalculator::* pyG4EmCalculator::f1_ComputeEnergyCutFromRangeCut)(G4double, const G4ParticleDefinition *, const G4Material *) = &G4EmCalculator::ComputeEnergyCutFromRangeCut
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeEnergyCutFromRangeCut)(G4double range, const G4String &, const G4String &) = &G4EmCalculator::ComputeEnergyCutFromRangeCut
G4double(G4EmCalculator::* pyG4EmCalculator::f1_ComputeMeanFreePath)(G4double, const G4ParticleDefinition *, const G4String &, const G4Material *, G4double) = &G4EmCalculator::ComputeMeanFreePath
G4double(G4EmCalculator::* pyG4EmCalculator::f2_ComputeMeanFreePath)(G4double, const G4String &, const G4String &, const G4String &, G4double) = &G4EmCalculator::ComputeMeanFreePath
Function Documentation
void export_G4EmCalculator ()
Definition at line 213 of file pyG4EmCalculator.cc.
View newest version in sPHENIX GitHub at line 213 of file pyG4EmCalculator.cc
References pyG4EmCalculator::f1_ComputeElectronicDEDX, pyG4EmCalculator::f1_ComputeEnergyCutFromRangeCut, pyG4EmCalculator::f1_ComputeMeanFreePath, pyG4EmCalculator::f1_ComputeNuclearDEDX, pyG4EmCalculator::f1_GetCrossSectionPerVolume, pyG4EmCalculator::f1_GetDEDX, pyG4EmCalculator::f1_GetKinEnergy, pyG4EmCalculator::f1_GetRange, pyG4EmCalculator::f2_ComputeCrossSectionPerAtom, pyG4EmCalculator::f2_ComputeCrossSectionPerVolume, pyG4EmCalculator::f2_ComputeDEDX, pyG4EmCalculator::f2_ComputeElectronicDEDX, pyG4EmCalculator::f2_ComputeEnergyCutFromRangeCut, pyG4EmCalculator::f2_ComputeMeanFreePath, pyG4EmCalculator::f2_ComputeNuclearDEDX, pyG4EmCalculator::f2_ComputeTotalDEDX, pyG4EmCalculator::f2_GetCrossSectionPerVolume, pyG4EmCalculator::f2_GetDEDX, pyG4EmCalculator::f2_GetKinEnergy, pyG4EmCalculator::f2_GetMeanFreePath, G4EmCalculator::FindCouple(), G4EmCalculator::FindMaterial(), G4EmCalculator::FindParticle(), G4EmCalculator::FindRegion(), G4EmCalculator::PrintDEDXTable(), G4EmCalculator::PrintInverseRangeTable(), G4EmCalculator::PrintRangeTable(), and G4EmCalculator::SetVerbose().
Referenced by BOOST_PYTHON_MODULE().