ECCE @ EIC Software: G4UserWorkerThreadInitialization Class Reference
G4UserWorkerThreadInitialization Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4UserWorkerThreadInitialization.hh>
Public Member Functions
G4UserWorkerThreadInitialization ()
virtual ~G4UserWorkerThreadInitialization ()
virtual G4Thread * CreateAndStartWorker (G4WorkerThread *workerThreadContext)
virtual void SetupRNGEngine (const CLHEP::HepRandomEngine *aRNGEngine) const
virtual void JoinWorker (G4Thread *aThread)
virtual G4WorkerRunManager * CreateWorkerRunManager () const
Detailed Description
Definition at line 47 of file G4UserWorkerThreadInitialization.hh.
View newest version in sPHENIX GitHub at line 47 of file G4UserWorkerThreadInitialization.hh
Constructor & Destructor Documentation
G4UserWorkerThreadInitialization::G4UserWorkerThreadInitialization ()
Definition at line 70 of file G4UserWorkerThreadInitialization.cc.
View newest version in sPHENIX GitHub at line 70 of file G4UserWorkerThreadInitialization.cc
G4UserWorkerThreadInitialization::~G4UserWorkerThreadInitialization () virtual
Definition at line 73 of file G4UserWorkerThreadInitialization.cc.
View newest version in sPHENIX GitHub at line 73 of file G4UserWorkerThreadInitialization.cc
Member Function Documentation
G4Thread * G4UserWorkerThreadInitialization::CreateAndStartWorker (G4WorkerThread * workerThreadContext) virtual
Reimplemented in tbbUserWorkerInitialization.
Definition at line 52 of file G4UserWorkerThreadInitialization.cc.
View newest version in sPHENIX GitHub at line 52 of file G4UserWorkerThreadInitialization.cc
Referenced by G4MTRunManager::CreateAndStartWorkers().
G4WorkerRunManager * G4UserWorkerThreadInitialization::CreateWorkerRunManager () const virtual
Reimplemented in tbbUserWorkerInitialization.
Definition at line 136 of file G4UserWorkerThreadInitialization.cc.
View newest version in sPHENIX GitHub at line 136 of file G4UserWorkerThreadInitialization.cc
Referenced by tbbTask::execute(), and G4MTRunManagerKernel::StartThread().
void G4UserWorkerThreadInitialization::JoinWorker (G4Thread * aThread) virtual
Reimplemented in tbbUserWorkerInitialization.
Definition at line 65 of file G4UserWorkerThreadInitialization.cc.
View newest version in sPHENIX GitHub at line 65 of file G4UserWorkerThreadInitialization.cc
Referenced by G4MTRunManager::TerminateWorkers().
void G4UserWorkerThreadInitialization::SetupRNGEngine (const CLHEP::HepRandomEngine * aRNGEngine) const virtual
Definition at line 81 of file G4UserWorkerThreadInitialization.cc.
View newest version in sPHENIX GitHub at line 81 of file G4UserWorkerThreadInitialization.cc
References FatalException, G4endl, G4Exception(), CLHEP::Ranlux64Engine::getLuxury(), and CLHEP::RanluxEngine::getLuxury().
Referenced by tbbTask::execute(), G4WorkerRunManager::SetupDefaultRNGEngine(), and G4MTRunManagerKernel::StartThread().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4UserWorkerThreadInitialization.hh
geant4/tree/geant4-10.6-release/source/run/src/G4UserWorkerThreadInitialization.cc