ECCE @ EIC Software: G4SauterGavrilaAngularDistribution Class Reference
G4SauterGavrilaAngularDistribution Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4SauterGavrilaAngularDistribution.hh>
Public Member Functions
G4SauterGavrilaAngularDistribution ()
virtual ~G4SauterGavrilaAngularDistribution ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double e=0.0, G4int shellId=0, const G4Material *mat=0) final
virtual void PrintGeneratorInformation () const final
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material *)
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr)
const G4String & GetName () const
Private Member Functions
G4SauterGavrilaAngularDistribution & operator= (const G4SauterGavrilaAngularDistribution &right)=delete
G4SauterGavrilaAngularDistribution (const G4SauterGavrilaAngularDistribution &)=delete
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 54 of file G4SauterGavrilaAngularDistribution.hh.
View newest version in sPHENIX GitHub at line 54 of file G4SauterGavrilaAngularDistribution.hh
Constructor & Destructor Documentation
G4SauterGavrilaAngularDistribution::G4SauterGavrilaAngularDistribution () explicit
Definition at line 48 of file G4SauterGavrilaAngularDistribution.cc.
View newest version in sPHENIX GitHub at line 48 of file G4SauterGavrilaAngularDistribution.cc
G4SauterGavrilaAngularDistribution::~G4SauterGavrilaAngularDistribution () virtual
Definition at line 52 of file G4SauterGavrilaAngularDistribution.cc.
View newest version in sPHENIX GitHub at line 52 of file G4SauterGavrilaAngularDistribution.cc
G4SauterGavrilaAngularDistribution::G4SauterGavrilaAngularDistribution (const G4SauterGavrilaAngularDistribution &) private delete
Member Function Documentation
G4SauterGavrilaAngularDistribution& G4SauterGavrilaAngularDistribution::operator= (const G4SauterGavrilaAngularDistribution & right) private delete
void G4SauterGavrilaAngularDistribution::PrintGeneratorInformation () const final virtual
Definition at line 110 of file G4SauterGavrilaAngularDistribution.cc.
View newest version in sPHENIX GitHub at line 110 of file G4SauterGavrilaAngularDistribution.cc
References G4cout, and G4endl.
G4ThreeVector & G4SauterGavrilaAngularDistribution::SampleDirection (const G4DynamicParticle * dp, G4double e = 0.0, G4int shellId = 0, const G4Material * mat = 0) final virtual
Implements G4VEmAngularDistribution.
Definition at line 55 of file G4SauterGavrilaAngularDistribution.cc.
View newest version in sPHENIX GitHub at line 55 of file G4SauterGavrilaAngularDistribution.cc
References source.hepunit::electron_mass_c2, emax, CEMC_TOWER::emin, energy, CLHEP::eV, G4VEmAngularDistribution::fLocalDirection, G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), max, CLHEP::MeV, phi, CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), and CLHEP::twopi.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4SauterGavrilaAngularDistribution.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4SauterGavrilaAngularDistribution.cc