ECCE @ EIC Software: cheprep::DefaultHepRepPoint Class Reference
cheprep::DefaultHepRepPoint Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepPoint.h>
Public Member Functions
DefaultHepRepPoint (HEPREP::HepRepInstance *instance, double x, double y, double z)
~DefaultHepRepPoint ()
HEPREP::HepRepInstance * getInstance ()
HEPREP::HepRepAttValue * getAttValue (std::string lowerCaseName)
HEPREP::HepRepPoint * copy (HEPREP::HepRepInstance *parent)
double getX ()
double getY ()
double getZ ()
std::vector< double > * getXYZ (std::vector< double > *xyz)
double getRho ()
double getPhi ()
double getTheta ()
double getR ()
double getEta ()
double getX (double xVertex, double yVertex, double zVertex)
double getY (double xVertex, double yVertex, double zVertex)
double getZ (double xVertex, double yVertex, double zVertex)
double getRho (double xVertex, double yVertex, double zVertex)
double getPhi (double xVertex, double yVertex, double zVertex)
double getTheta (double xVertex, double yVertex, double zVertex)
double getR (double xVertex, double yVertex, double zVertex)
double getEta (double xVertex, double yVertex, double zVertex)
Public Member Functions inherited from cheprep::DefaultHepRepAttribute
DefaultHepRepAttribute ()
~DefaultHepRepAttribute ()
std::set
< HEPREP::HepRepAttValue * > getAttValuesFromNode ()
void addAttValue (HEPREP::HepRepAttValue *hepRepAttValue)
void addAttValue (std::string key, char *value, int showLabel)
void addAttValue (std::string key, std::string value, int showLabel)
void addAttValue (std::string key, int value, int showLabel)
void addAttValue (std::string key, int64 value, int showLabel)
void addAttValue (std::string key, double value, int showLabel)
void addAttValue (std::string key, bool value, int showLabel)
void addAttValue (std::string key, std::vector< double > value, int showLabel)
void addAttValue (std::string key, double red, double green, double blue, double alpha, int showLabel)
HEPREP::HepRepAttValue * getAttValueFromNode (std::string lowerCaseName)
HEPREP::HepRepAttValue * removeAttValue (std::string key)
Public Member Functions inherited from HEPREP::HepRepAttribute
virtual ~HepRepAttribute ()
Destructor.
Public Member Functions inherited from HEPREP::HepRepPoint
virtual ~HepRepPoint ()
Destructor.
Protected Attributes
double x
double y
double z
Private Attributes
HEPREP::HepRepInstance * instance
Detailed Description
Definition at line 22 of file DefaultHepRepPoint.h.
View newest version in sPHENIX GitHub at line 22 of file DefaultHepRepPoint.h
Constructor & Destructor Documentation
cheprep::DefaultHepRepPoint::DefaultHepRepPoint (HEPREP::HepRepInstance * instance, double x, double y, double z)
Definition at line 17 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 17 of file DefaultHepRepPoint.cc
References HEPREP::HepRepInstance::addPoint(), and instance.
Referenced by copy().
cheprep::DefaultHepRepPoint::~DefaultHepRepPoint ()
Definition at line 27 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 27 of file DefaultHepRepPoint.cc
Member Function Documentation
HepRepPoint * cheprep::DefaultHepRepPoint::copy (HEPREP::HepRepInstance * parent) virtual
Returns a deep copy of this point.
Parameters
parent to add the copy to.
Returns
copy of this point.
Implements HEPREP::HepRepPoint.
Definition at line 39 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 39 of file DefaultHepRepPoint.cc
References DefaultHepRepPoint(), x, y, and z.
HepRepAttValue * cheprep::DefaultHepRepPoint::getAttValue (std::string name) virtual
Returns the attValue specified by name. This attValue is normally searched on the node itself and then on its type, moving up the typetree.
Parameters
name of attribute value.
Returns
attribute value.
Implements cheprep::DefaultHepRepAttribute.
Definition at line 34 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 34 of file DefaultHepRepPoint.cc
References HEPREP::HepRepAttribute::getAttValue(), cheprep::DefaultHepRepAttribute::getAttValueFromNode(), and instance.
double cheprep::DefaultHepRepPoint::getEta () virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
eta = -0.5*clog((1.-ct)/(1.+ct)), where ct = .cos(getTheta(dx, dy, dz));
Implements HEPREP::HepRepPoint.
Definition at line 79 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 79 of file DefaultHepRepPoint.cc
References getTheta().
double cheprep::DefaultHepRepPoint::getEta (double xVertex, double yVertex, double zVertex) virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
eta = -0.5*clog((1.-ct)/(1.+ct)), where ct = .cos(getTheta(dx, dy, dz));
Implements HEPREP::HepRepPoint.
Definition at line 116 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 116 of file DefaultHepRepPoint.cc
References getTheta().
HepRepInstance * cheprep::DefaultHepRepPoint::getInstance () virtual
Returns associated instance (parent).
Returns
HepRepInstance.
Implements HEPREP::HepRepPoint.
Definition at line 30 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 30 of file DefaultHepRepPoint.cc
References instance.
double cheprep::DefaultHepRepPoint::getPhi () virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
phi = std::atan2(dy, dx);
Implements HEPREP::HepRepPoint.
Definition at line 66 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 66 of file DefaultHepRepPoint.cc
References x, and y.
double cheprep::DefaultHepRepPoint::getPhi (double xVertex, double yVertex, double zVertex) virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
phi = std::atan2(dy, dx);
Implements HEPREP::HepRepPoint.
Definition at line 102 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 102 of file DefaultHepRepPoint.cc
References getX(), and getY().
double cheprep::DefaultHepRepPoint::getR () virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
r = std::sqrt(dx2+dy2+dz2);
Implements HEPREP::HepRepPoint.
Definition at line 74 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 74 of file DefaultHepRepPoint.cc
References getRho(), r, and z.
double cheprep::DefaultHepRepPoint::getR (double xVertex, double yVertex, double zVertex) virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
r = std::sqrt(dx2+dy2+dz2);
Implements HEPREP::HepRepPoint.
Definition at line 110 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 110 of file DefaultHepRepPoint.cc
References dz, getRho(), and getZ().
double cheprep::DefaultHepRepPoint::getRho () virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
rho = std::sqrt(dx2+dy2);
Implements HEPREP::HepRepPoint.
Definition at line 62 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 62 of file DefaultHepRepPoint.cc
References x, and y.
Referenced by getR(), and getTheta().
double cheprep::DefaultHepRepPoint::getRho (double xVertex, double yVertex, double zVertex) virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
rho = std::sqrt(dx2+dy2);
Implements HEPREP::HepRepPoint.
Definition at line 96 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 96 of file DefaultHepRepPoint.cc
References dx, dy, getX(), and getY().
double cheprep::DefaultHepRepPoint::getTheta () virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
theta = std::atan2(rho, dx);
Implements HEPREP::HepRepPoint.
Definition at line 70 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 70 of file DefaultHepRepPoint.cc
References getRho(), and z.
Referenced by getEta().
double cheprep::DefaultHepRepPoint::getTheta (double xVertex, double yVertex, double zVertex) virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
theta = std::atan2(rho, dx);
Implements HEPREP::HepRepPoint.
Definition at line 106 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 106 of file DefaultHepRepPoint.cc
References getRho(), and getZ().
double cheprep::DefaultHepRepPoint::getX () virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
dx-coordinate
Implements HEPREP::HepRepPoint.
Definition at line 43 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 43 of file DefaultHepRepPoint.cc
References x.
Referenced by getPhi(), and getRho().
double cheprep::DefaultHepRepPoint::getX (double xVertex, double yVertex, double zVertex) virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
dx-coordinate
Implements HEPREP::HepRepPoint.
Definition at line 84 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 84 of file DefaultHepRepPoint.cc
References x.
vector< double > * cheprep::DefaultHepRepPoint::getXYZ (std::vector< double > * xyz) virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Parameters
xyz list of three coordinates which are filled and returned. If null, a new list of three coordinates is allocated.
Returns
list of 3 coordinates.
Implements HEPREP::HepRepPoint.
Definition at line 55 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 55 of file DefaultHepRepPoint.cc
References x, y, and z.
double cheprep::DefaultHepRepPoint::getY () virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
dy-coordinate
Implements HEPREP::HepRepPoint.
Definition at line 47 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 47 of file DefaultHepRepPoint.cc
References y.
Referenced by getPhi(), and getRho().
double cheprep::DefaultHepRepPoint::getY (double xVertex, double yVertex, double zVertex) virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
dy-coordinate
Implements HEPREP::HepRepPoint.
Definition at line 88 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 88 of file DefaultHepRepPoint.cc
References y.
double cheprep::DefaultHepRepPoint::getZ () virtual
Returns coordinate with respect to vertex at (0, 0, 0).
Returns
dz-coordinate
Implements HEPREP::HepRepPoint.
Definition at line 51 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 51 of file DefaultHepRepPoint.cc
References z.
Referenced by getR(), and getTheta().
double cheprep::DefaultHepRepPoint::getZ (double xVertex, double yVertex, double zVertex) virtual
Returns coordinate with respect to vertex at (xVertex, yVertex, zVertex).
Returns
dz-coordinate
Implements HEPREP::HepRepPoint.
Definition at line 92 of file DefaultHepRepPoint.cc.
View newest version in sPHENIX GitHub at line 92 of file DefaultHepRepPoint.cc
References z.
Member Data Documentation
HEPREP::HepRepInstance* cheprep::DefaultHepRepPoint::instance private
Definition at line 25 of file DefaultHepRepPoint.h.
View newest version in sPHENIX GitHub at line 25 of file DefaultHepRepPoint.h
Referenced by DefaultHepRepPoint(), getAttValue(), and getInstance().
double cheprep::DefaultHepRepPoint::x protected
Definition at line 28 of file DefaultHepRepPoint.h.
View newest version in sPHENIX GitHub at line 28 of file DefaultHepRepPoint.h
Referenced by copy(), getPhi(), getRho(), getX(), and getXYZ().
double cheprep::DefaultHepRepPoint::y protected
Definition at line 28 of file DefaultHepRepPoint.h.
View newest version in sPHENIX GitHub at line 28 of file DefaultHepRepPoint.h
Referenced by copy(), getPhi(), getRho(), getXYZ(), and getY().
double cheprep::DefaultHepRepPoint::z protected
Definition at line 28 of file DefaultHepRepPoint.h.
View newest version in sPHENIX GitHub at line 28 of file DefaultHepRepPoint.h
Referenced by copy(), getR(), getTheta(), getXYZ(), and getZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepPoint.h
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/DefaultHepRepPoint.cc