ECCE @ EIC Software: G4AdjointPhysicsMessenger Class Reference
G4AdjointPhysicsMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/G4AdjointPhysicsMessenger.hh>
Public Member Functions
G4AdjointPhysicsMessenger (G4AdjointPhysicsList *)
virtual ~G4AdjointPhysicsMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4AdjointPhysicsList * fPhysicsList
G4UIdirectory * fPhysicsDir
G4UIcmdWithABool * fUsepIonisationCmd
G4UIcmdWithABool * fUseBremCmd
G4UIcmdWithABool * fUseComptonCmd
G4UIcmdWithABool * fUseMSCmd
G4UIcmdWithABool * fUsePEEffectCmd
G4UIcmdWithABool * fUseGammaConversionCmd
G4UIcmdWithABool * fUseEgainFluctuationCmd
G4UIcmdWithADoubleAndUnit * fSetEminAdjModelsCmd
G4UIcmdWithADoubleAndUnit * fSetEmaxAdjModelsCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 63 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file G4AdjointPhysicsMessenger.hh
Constructor & Destructor Documentation
G4AdjointPhysicsMessenger::G4AdjointPhysicsMessenger (G4AdjointPhysicsList * pPhysicsList)
Definition at line 55 of file G4AdjointPhysicsMessenger.cc.
View newest version in sPHENIX GitHub at line 55 of file G4AdjointPhysicsMessenger.cc
References G4UIcommand::AvailableForStates(), fPhysicsDir, fSetEmaxAdjModelsCmd, fSetEminAdjModelsCmd, fUseBremCmd, fUseComptonCmd, fUseEgainFluctuationCmd, fUseGammaConversionCmd, fUseMSCmd, fUsePEEffectCmd, fUsepIonisationCmd, G4State_PreInit, G4UIcommand::SetGuidance(), G4UIcmdWithADoubleAndUnit::SetParameterName(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
G4AdjointPhysicsMessenger::~G4AdjointPhysicsMessenger () virtual
Definition at line 132 of file G4AdjointPhysicsMessenger.cc.
View newest version in sPHENIX GitHub at line 132 of file G4AdjointPhysicsMessenger.cc
References fSetEmaxAdjModelsCmd, fSetEminAdjModelsCmd, fUseBremCmd, fUseComptonCmd, fUseEgainFluctuationCmd, fUseGammaConversionCmd, fUseMSCmd, fUsePEEffectCmd, and fUsepIonisationCmd.
Member Function Documentation
void G4AdjointPhysicsMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 147 of file G4AdjointPhysicsMessenger.cc.
View newest version in sPHENIX GitHub at line 147 of file G4AdjointPhysicsMessenger.cc
References fPhysicsList, fSetEmaxAdjModelsCmd, fSetEminAdjModelsCmd, fUseBremCmd, fUseComptonCmd, fUseEgainFluctuationCmd, fUseGammaConversionCmd, fUseMSCmd, fUsePEEffectCmd, fUsepIonisationCmd, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4AdjointPhysicsList::SetEmaxAdjModels(), G4AdjointPhysicsList::SetEminAdjModels(), G4AdjointPhysicsList::SetUseBrem(), G4AdjointPhysicsList::SetUseCompton(), G4AdjointPhysicsList::SetUseEgainFluctuation(), G4AdjointPhysicsList::SetUseGammaConversion(), G4AdjointPhysicsList::SetUseMS(), G4AdjointPhysicsList::SetUsePEEffect(), and G4AdjointPhysicsList::SetUseProtonIonisation().
Member Data Documentation
G4UIdirectory* G4AdjointPhysicsMessenger::fPhysicsDir private
Definition at line 72 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger().
G4AdjointPhysicsList* G4AdjointPhysicsMessenger::fPhysicsList private
Definition at line 71 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4AdjointPhysicsMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADoubleAndUnit* G4AdjointPhysicsMessenger::fSetEmaxAdjModelsCmd private
Definition at line 83 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
G4UIcmdWithADoubleAndUnit* G4AdjointPhysicsMessenger::fSetEminAdjModelsCmd private
Definition at line 82 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
G4UIcmdWithABool* G4AdjointPhysicsMessenger::fUseBremCmd private
Definition at line 76 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
G4UIcmdWithABool* G4AdjointPhysicsMessenger::fUseComptonCmd private
Definition at line 77 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
G4UIcmdWithABool* G4AdjointPhysicsMessenger::fUseEgainFluctuationCmd private
Definition at line 81 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
G4UIcmdWithABool* G4AdjointPhysicsMessenger::fUseGammaConversionCmd private
Definition at line 80 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
G4UIcmdWithABool* G4AdjointPhysicsMessenger::fUseMSCmd private
Definition at line 78 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
G4UIcmdWithABool* G4AdjointPhysicsMessenger::fUsePEEffectCmd private
Definition at line 79 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
G4UIcmdWithABool* G4AdjointPhysicsMessenger::fUsepIonisationCmd private
Definition at line 75 of file G4AdjointPhysicsMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4AdjointPhysicsMessenger.hh
Referenced by G4AdjointPhysicsMessenger(), SetNewValue(), and ~G4AdjointPhysicsMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/G4AdjointPhysicsMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/src/G4AdjointPhysicsMessenger.cc