ECCE @ EIC Software: G4Nucleon Class Reference
G4Nucleon Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4Nucleon.hh>
Public Member Functions
G4Nucleon ()
~G4Nucleon ()
G4bool operator== (const G4Nucleon &right) const
G4bool operator!= (const G4Nucleon &right) const
G4Nucleon & operator= (const G4Nucleon &right)
void SetPosition (const G4ThreeVector aPosition)
const G4ThreeVector & GetPosition () const
void SetMomentum (G4LorentzVector &aMomentum)
const G4LorentzVector & GetMomentum () const
virtual const G4LorentzVector & Get4Momentum () const
void SetBindingEnergy (G4double anEnergy)
G4double GetBindingEnergy () const
void SetParticleType (G4Proton *aProton)
void SetParticleType (G4Neutron *aNeutron)
void SetParticleType (G4AntiProton *aAntiProton)
void SetParticleType (G4AntiNeutron *aAntiNeutron)
const G4ParticleDefinition * GetParticleType () const
virtual const
G4ParticleDefinition * GetDefinition () const
void Boost (const G4ThreeVector &beta)
void Boost (const G4LorentzVector &aMomentum)
void Hit (G4VSplitableHadron *aHit)
void Hit (G4int)
G4VSplitableHadron * GetSplitableHadron () const
G4bool AreYouHit () const
Public Member Functions inherited from G4VKineticNucleon
G4VKineticNucleon ()
G4VKineticNucleon (const G4VKineticNucleon &right)
virtual ~G4VKineticNucleon ()
const G4VKineticNucleon & operator= (const G4VKineticNucleon &right)
G4bool operator== (const G4VKineticNucleon &right) const
G4bool operator!= (const G4VKineticNucleon &right) const
virtual G4KineticTrackVector * Decay ()
Private Attributes
G4ThreeVector thePosition
G4LorentzVector theMomentum
G4double theBindingE
const G4ParticleDefinition * theParticleType
G4VSplitableHadron * theSplitableHadron
Detailed Description
Definition at line 54 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 54 of file G4Nucleon.hh
Constructor & Destructor Documentation
G4Nucleon::G4Nucleon ()
Definition at line 38 of file G4Nucleon.cc.
View newest version in sPHENIX GitHub at line 38 of file G4Nucleon.cc
G4Nucleon::~G4Nucleon ()
Definition at line 42 of file G4Nucleon.cc.
View newest version in sPHENIX GitHub at line 42 of file G4Nucleon.cc
Member Function Documentation
G4bool G4Nucleon::AreYouHit () const inline
Definition at line 96 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Nucleon.hh
References theSplitableHadron.
Referenced by G4BinaryCascade::BuildTargetList(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4InuclNuclei::copy(), G4IntraNucleiCascader::copyWoundedNucleus(), G4FTFParticipants::GetList(), G4BinaryLightIonReaction::GetProjectileExcitation(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4KineticTrack::IsParticipant(), G4QGSParticipants::PrepareInitialState(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4VPartonStringModel::Scatter(), G4QGSParticipants::StoreInvolvedNucleon(), and G4FTFModel::StoreInvolvedNucleon().
void G4Nucleon::Boost (const G4ThreeVector & beta) inline
Definition at line 86 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 86 of file G4Nucleon.hh
References CLHEP::HepLorentzVector::boost(), and theMomentum.
void G4Nucleon::Boost (const G4LorentzVector & aMomentum)
Definition at line 46 of file G4Nucleon.cc.
View newest version in sPHENIX GitHub at line 46 of file G4Nucleon.cc
References CLHEP::HepLorentzVector::dot(), CLHEP::HepLorentzVector::e(), CLHEP::HepLorentzVector::mag(), mass, CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setVect(), theMomentum, and CLHEP::HepLorentzVector::vect().
virtual const G4LorentzVector& G4Nucleon::Get4Momentum () const inline virtual
Implements G4VKineticNucleon.
Definition at line 72 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 72 of file G4Nucleon.hh
References theMomentum.
Referenced by G4QGSParticipants::BuildInteractions(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), operator<<(), operator=(), G4QGSParticipants::PrepareInitialState(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4VPartonStringModel::Scatter().
G4double G4Nucleon::GetBindingEnergy () const inline
Definition at line 75 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 75 of file G4Nucleon.hh
References theBindingE.
Referenced by G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), operator=(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), and G4VPartonStringModel::Scatter().
virtual const G4ParticleDefinition* G4Nucleon::GetDefinition () const inline virtual
Implements G4VKineticNucleon.
Definition at line 84 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 84 of file G4Nucleon.hh
References theParticleType.
Referenced by G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4BinaryCascade::BuildTargetList(), G4QGSParticipants::ComputeNucleusProperties(), G4FTFModel::ComputeNucleusProperties(), G4QGSParticipants::FinalizeKinematics(), G4QGSParticipants::GetList(), G4BinaryLightIonReaction::GetProjectileExcitation(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4FTFModel::Init(), G4BinaryLightIonReaction::Interact(), operator=(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4QGSParticipants::ReggeonCascade(), and G4VPartonStringModel::Scatter().
const G4LorentzVector& G4Nucleon::GetMomentum (void) const inline
Definition at line 71 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Nucleon.hh
References theMomentum.
Referenced by G4BinaryCascade::BuildTargetList(), G4VSplitableHadron::G4VSplitableHadron(), G4BinaryLightIonReaction::GetProjectileExcitation(), and G4BinaryLightIonReaction::Interact().
const G4ParticleDefinition* G4Nucleon::GetParticleType () const inline
Definition at line 83 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 83 of file G4Nucleon.hh
References theParticleType.
Referenced by G4LowEIonFragmentation::ApplyYourself(), G4InuclNuclei::copy(), G4IntraNucleiCascader::copyWoundedNucleus(), and G4VSplitableHadron::G4VSplitableHadron().
const G4ThreeVector & G4Nucleon::GetPosition (void) const inline virtual
Implements G4VKineticNucleon.
Definition at line 138 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 138 of file G4Nucleon.hh
References thePosition.
Referenced by G4LowEIonFragmentation::ApplyYourself(), G4BinaryCascade::BuildTargetList(), G4IntraNucleiCascader::copyWoundedNucleus(), G4Fancy3DNucleusHelperForSortInZ(), G4VSplitableHadron::G4VSplitableHadron(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4BinaryLightIonReaction::GetProjectileExcitation(), G4BinaryLightIonReaction::Interact(), operator<<(), operator=(), G4QGSParticipants::ReggeonCascade(), and G4FTFModel::ReggeonCascade().
G4VSplitableHadron* G4Nucleon::GetSplitableHadron () const inline
Definition at line 95 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 95 of file G4Nucleon.hh
References theSplitableHadron.
Referenced by G4QGSParticipants::BuildInteractions(), G4FTFModel::BuildStrings(), G4QGSParticipants::CheckKinematics(), G4FTFModel::CheckKinematics(), G4QGSParticipants::CreateStrings(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4QGSParticipants::GenerateDeltaIsobar(), G4FTFModel::GenerateDeltaIsobar(), G4FTFParticipants::GetList(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4FTFModel::GetStrings(), operator=(), G4QGSParticipants::PrepareInitialState(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4FTFModel::~G4FTFModel().
void G4Nucleon::Hit (G4VSplitableHadron * aHit) inline
Definition at line 89 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 89 of file G4Nucleon.hh
References theSplitableHadron.
Referenced by G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4FTFModel::GetResiduals(), G4KineticTrack::Hit(), G4QGSParticipants::PrepareInitialState(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4VPartonStringModel::Scatter(), G4GammaParticipants::SelectInteractions(), and G4QGSParticipants::SelectInteractions().
void G4Nucleon::Hit (G4int) inline
Definition at line 91 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 91 of file G4Nucleon.hh
References theSplitableHadron.
G4bool G4Nucleon::operator!= (const G4Nucleon & right) const inline
Definition at line 115 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 115 of file G4Nucleon.hh
References right.
G4Nucleon & G4Nucleon::operator= (const G4Nucleon & right) inline
Definition at line 120 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 120 of file G4Nucleon.hh
References Get4Momentum(), GetBindingEnergy(), GetDefinition(), GetPosition(), GetSplitableHadron(), theBindingE, theMomentum, theParticleType, thePosition, and theSplitableHadron.
G4bool G4Nucleon::operator== (const G4Nucleon & right) const inline
Definition at line 111 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 111 of file G4Nucleon.hh
References right.
void G4Nucleon::SetBindingEnergy (G4double anEnergy) inline
Definition at line 74 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 74 of file G4Nucleon.hh
References theBindingE.
Referenced by G4QGSParticipants::GetResiduals(), and G4FTFModel::GetResiduals().
void G4Nucleon::SetMomentum (G4LorentzVector & aMomentum) inline
Definition at line 70 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 70 of file G4Nucleon.hh
References theMomentum.
Referenced by G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), and G4VPartonStringModel::Scatter().
void G4Nucleon::SetParticleType (G4Proton * aProton) inline
Definition at line 77 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 77 of file G4Nucleon.hh
References theParticleType.
Referenced by G4FTFModel::Init().
void G4Nucleon::SetParticleType (G4Neutron * aNeutron) inline
Definition at line 78 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 78 of file G4Nucleon.hh
References theParticleType.
void G4Nucleon::SetParticleType (G4AntiProton * aAntiProton) inline
Definition at line 80 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 80 of file G4Nucleon.hh
References theParticleType.
void G4Nucleon::SetParticleType (G4AntiNeutron * aAntiNeutron) inline
Definition at line 81 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 81 of file G4Nucleon.hh
References theParticleType.
void G4Nucleon::SetPosition (const G4ThreeVector aPosition) inline
Definition at line 133 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 133 of file G4Nucleon.hh
References thePosition.
Referenced by G4QGSParticipants::GetList(), and G4QGSParticipants::PrepareInitialState().
Member Data Documentation
G4double G4Nucleon::theBindingE private
Definition at line 102 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 102 of file G4Nucleon.hh
Referenced by GetBindingEnergy(), operator=(), and SetBindingEnergy().
G4LorentzVector G4Nucleon::theMomentum private
Definition at line 101 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 101 of file G4Nucleon.hh
Referenced by Boost(), Get4Momentum(), GetMomentum(), operator=(), and SetMomentum().
const G4ParticleDefinition* G4Nucleon::theParticleType private
Definition at line 103 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 103 of file G4Nucleon.hh
Referenced by GetDefinition(), GetParticleType(), operator=(), and SetParticleType().
G4ThreeVector G4Nucleon::thePosition private
Definition at line 100 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 100 of file G4Nucleon.hh
Referenced by GetPosition(), operator=(), and SetPosition().
G4VSplitableHadron* G4Nucleon::theSplitableHadron private
Definition at line 104 of file G4Nucleon.hh.
View newest version in sPHENIX GitHub at line 104 of file G4Nucleon.hh
Referenced by AreYouHit(), GetSplitableHadron(), Hit(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4Nucleon.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4Nucleon.cc