ECCE @ EIC Software: G4ParticleHPLabAngularEnergy Class Reference
G4ParticleHPLabAngularEnergy Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPLabAngularEnergy.hh>
Public Member Functions
G4ParticleHPLabAngularEnergy ()
~G4ParticleHPLabAngularEnergy ()
void Init (std::istream &aDataFile)
G4ReactionProduct * Sample (G4double anEnergy, G4double massCode, G4double mass)
G4double MeanEnergyOfThisInteraction ()
Public Member Functions inherited from G4VParticleHPEnergyAngular
G4VParticleHPEnergyAngular ()
virtual ~G4VParticleHPEnergyAngular ()
void SetProjectileRP (G4ReactionProduct *aIncidentParticleRP)
void SetTarget (G4ReactionProduct *aTarget)
G4ReactionProduct * GetTarget ()
G4ReactionProduct * GetProjectileRP ()
G4ReactionProduct * GetCMS ()
void SetQValue (G4double aValue)
virtual void ClearHistories ()
Private Attributes
G4int nEnergies
G4InterpolationManager theManager
G4double * theEnergies
G4int * nCosTh
G4InterpolationManager * theSecondManager
G4ParticleHPVector ** theData
G4ParticleHPInterpolator theInt
G4double currentMeanEnergy
Additional Inherited Members
Protected Member Functions inherited from G4VParticleHPEnergyAngular
G4double GetQValue ()
Detailed Description
Definition at line 42 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPLabAngularEnergy.hh
Constructor & Destructor Documentation
G4ParticleHPLabAngularEnergy::G4ParticleHPLabAngularEnergy () inline
Definition at line 46 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPLabAngularEnergy.hh
References currentMeanEnergy, nCosTh, nEnergies, theData, theEnergies, and theSecondManager.
G4ParticleHPLabAngularEnergy::~G4ParticleHPLabAngularEnergy () inline
Definition at line 55 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPLabAngularEnergy.hh
References nCosTh, nEnergies, theData, theEnergies, and theSecondManager.
Member Function Documentation
void G4ParticleHPLabAngularEnergy::Init (std::istream & aDataFile) virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 48 of file G4ParticleHPLabAngularEnergy.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPLabAngularEnergy.cc
References eV, G4InterpolationManager::Init(), G4ParticleHPVector::Init(), nCosTh, nEnergies, G4ParticleHPVector::SetLabel(), theData, theEnergies, theManager, and theSecondManager.
G4double G4ParticleHPLabAngularEnergy::MeanEnergyOfThisInteraction () inline virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 72 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleHPLabAngularEnergy.hh
References currentMeanEnergy.
G4ReactionProduct * G4ParticleHPLabAngularEnergy::Sample (G4double anEnergy, G4double massCode, G4double mass) virtual
Implements G4VParticleHPEnergyAngular.
Definition at line 73 of file G4ParticleHPLabAngularEnergy.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleHPLabAngularEnergy.cc
References A(), G4Alpha::Alpha(), currentMeanEnergy, G4Deuteron::Deuteron(), E, G4Electron::Electron(), G4cout, G4endl, G4UniformRand, G4Gamma::Gamma(), G4ParticleHPVector::GetIntegral(), G4ParticleHPVector::GetInterpolationManager(), G4ParticleHPVector::GetLabel(), G4ParticleHPVector::GetMeanX(), G4InterpolationManager::GetScheme(), G4ReactionProduct::GetTotalMomentum(), G4ParticleHPVector::GetVectorLength(), G4ParticleHPVector::GetX(), G4ParticleHPVector::GetY(), G4He3::He3(), G4ParticleHPInterpolator::Interpolate(), it, G4ParticleHPInterpolator::Lin(), G4ParticleHPVector::Merge(), nCosTh, nEnergies, G4Neutron::Neutron(), phi, G4Positron::Positron(), G4Proton::Proton(), G4ParticleHPVector::Sample(), G4ParticleHPVector::SetData(), G4ReactionProduct::SetDefinition(), G4ParticleHPVector::SetInterpolationManager(), G4ReactionProduct::SetKineticEnergy(), G4ReactionProduct::SetMomentum(), G4ParticleHPVector::SetX(), G4ParticleHPVector::SetY(), theData, theEnergies, theInt, theManager, theSecondManager, theta(), tmp, G4Triton::Triton(), twopi, x, x1, x2, xx, y, y1, y2, and Z.
Member Data Documentation
G4double G4ParticleHPLabAngularEnergy::currentMeanEnergy private
Definition at line 97 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPLabAngularEnergy.hh
Referenced by G4ParticleHPLabAngularEnergy(), MeanEnergyOfThisInteraction(), and Sample().
G4int* G4ParticleHPLabAngularEnergy::nCosTh private
Definition at line 87 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPLabAngularEnergy.hh
Referenced by G4ParticleHPLabAngularEnergy(), Init(), Sample(), and ~G4ParticleHPLabAngularEnergy().
G4int G4ParticleHPLabAngularEnergy::nEnergies private
Definition at line 81 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleHPLabAngularEnergy.hh
Referenced by G4ParticleHPLabAngularEnergy(), Init(), Sample(), and ~G4ParticleHPLabAngularEnergy().
G4ParticleHPVector** G4ParticleHPLabAngularEnergy::theData private
Definition at line 91 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPLabAngularEnergy.hh
Referenced by G4ParticleHPLabAngularEnergy(), Init(), Sample(), and ~G4ParticleHPLabAngularEnergy().
G4double* G4ParticleHPLabAngularEnergy::theEnergies private
Definition at line 85 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPLabAngularEnergy.hh
Referenced by G4ParticleHPLabAngularEnergy(), Init(), Sample(), and ~G4ParticleHPLabAngularEnergy().
G4ParticleHPInterpolator G4ParticleHPLabAngularEnergy::theInt private
Definition at line 94 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPLabAngularEnergy.hh
Referenced by Sample().
G4InterpolationManager G4ParticleHPLabAngularEnergy::theManager private
Definition at line 83 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPLabAngularEnergy.hh
Referenced by Init(), and Sample().
G4InterpolationManager* G4ParticleHPLabAngularEnergy::theSecondManager private
Definition at line 89 of file G4ParticleHPLabAngularEnergy.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPLabAngularEnergy.hh
Referenced by G4ParticleHPLabAngularEnergy(), Init(), Sample(), and ~G4ParticleHPLabAngularEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPLabAngularEnergy.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPLabAngularEnergy.cc