ECCE @ EIC Software: GeometryConstruction Class Reference
GeometryConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/include/GeometryConstruction.hh>
Public Member Functions
GeometryConstruction ()
~GeometryConstruction ()
virtual G4VPhysicalVolume * Construct ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4VPhysicalVolume * fUniverse_phys
G4VPhysicalVolume * fAl_phys
G4VPhysicalVolume * fSphere_phys
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 43 of file GeometryConstruction.hh.
View newest version in sPHENIX GitHub at line 43 of file GeometryConstruction.hh
Constructor & Destructor Documentation
GeometryConstruction::GeometryConstruction ()
Definition at line 50 of file GeometryConstruction.cc.
View newest version in sPHENIX GitHub at line 50 of file GeometryConstruction.cc
GeometryConstruction::~GeometryConstruction ()
Definition at line 59 of file GeometryConstruction.cc.
View newest version in sPHENIX GitHub at line 59 of file GeometryConstruction.cc
Member Function Documentation
G4VPhysicalVolume * GeometryConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 64 of file GeometryConstruction.cc.
View newest version in sPHENIX GitHub at line 64 of file GeometryConstruction.cc
References a, G4Material::AddElement(), cm, cm3, fAl_phys, fSphere_phys, fUniverse_phys, Acts::UnitConstants::g, G4VisAttributes::GetInvisible(), kelvin, kStateGas, mole, pascal, pi, G4LogicalVolume::SetVisAttributes(), twopi, source.hepunit::universe_mean_density, and z.
Member Data Documentation
G4VPhysicalVolume* GeometryConstruction::fAl_phys private
Definition at line 53 of file GeometryConstruction.hh.
View newest version in sPHENIX GitHub at line 53 of file GeometryConstruction.hh
Referenced by Construct().
G4VPhysicalVolume* GeometryConstruction::fSphere_phys private
Definition at line 54 of file GeometryConstruction.hh.
View newest version in sPHENIX GitHub at line 54 of file GeometryConstruction.hh
Referenced by Construct().
G4VPhysicalVolume* GeometryConstruction::fUniverse_phys private
Definition at line 52 of file GeometryConstruction.hh.
View newest version in sPHENIX GitHub at line 52 of file GeometryConstruction.hh
Referenced by Construct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/include/GeometryConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/exgps/src/GeometryConstruction.cc