ECCE @ EIC Software: G4RDFluoTransition Class Reference
G4RDFluoTransition Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDFluoTransition.hh>
Public Member Functions
G4RDFluoTransition (G4int, const std::vector< G4int > &, const G4DataVector &, const G4DataVector &)
~G4RDFluoTransition ()
const std::vector< G4int > & OriginatingShellIds () const
const G4DataVector & TransitionEnergies () const
const G4DataVector & TransitionProbabilities () const
G4int FinalShellId () const
G4int OriginatingShellId (G4int index) const
G4double TransitionEnergy (G4int index) const
G4double TransitionProbability (G4int index) const
Private Attributes
G4int finalShellId
std::vector< G4int > originatingShellIds
G4DataVector transitionEnergies
G4DataVector transitionProbabilities
Detailed Description
Definition at line 51 of file G4RDFluoTransition.hh.
View newest version in sPHENIX GitHub at line 51 of file G4RDFluoTransition.hh
Constructor & Destructor Documentation
G4RDFluoTransition::G4RDFluoTransition (G4int finalShell, const std::vector< G4int > & ids, const G4DataVector & energies, const G4DataVector & prob)
Definition at line 39 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 39 of file G4RDFluoTransition.cc
G4RDFluoTransition::~G4RDFluoTransition ()
Definition at line 49 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 49 of file G4RDFluoTransition.cc
Member Function Documentation
G4int G4RDFluoTransition::FinalShellId () const
Definition at line 67 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 67 of file G4RDFluoTransition.cc
References finalShellId.
Referenced by G4RDAtomicDeexcitation::SelectTypeOfTransition().
G4int G4RDFluoTransition::OriginatingShellId (G4int index) const
Definition at line 72 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 72 of file G4RDFluoTransition.cc
References originatingShellIds.
Referenced by G4RDAtomicDeexcitation::SelectTypeOfTransition().
const std::vector< G4int > & G4RDFluoTransition::OriginatingShellIds () const
Definition at line 52 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 52 of file G4RDFluoTransition.cc
References originatingShellIds.
const G4DataVector & G4RDFluoTransition::TransitionEnergies () const
Definition at line 57 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 57 of file G4RDFluoTransition.cc
References transitionEnergies.
G4double G4RDFluoTransition::TransitionEnergy (G4int index) const
Definition at line 76 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 76 of file G4RDFluoTransition.cc
References transitionEnergies.
const G4DataVector & G4RDFluoTransition::TransitionProbabilities () const
Definition at line 62 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 62 of file G4RDFluoTransition.cc
References transitionProbabilities.
Referenced by G4RDAtomicDeexcitation::SelectTypeOfTransition(), G4RDAtomicTransitionManager::TotalNonRadiativeTransitionProbability(), and G4RDAtomicTransitionManager::TotalRadiativeTransitionProbability().
G4double G4RDFluoTransition::TransitionProbability (G4int index) const
Definition at line 80 of file G4RDFluoTransition.cc.
View newest version in sPHENIX GitHub at line 80 of file G4RDFluoTransition.cc
References transitionProbabilities.
Referenced by G4RDAtomicDeexcitation::SelectTypeOfTransition().
Member Data Documentation
G4int G4RDFluoTransition::finalShellId private
Definition at line 89 of file G4RDFluoTransition.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RDFluoTransition.hh
Referenced by FinalShellId().
std::vector<G4int> G4RDFluoTransition::originatingShellIds private
Definition at line 90 of file G4RDFluoTransition.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RDFluoTransition.hh
Referenced by OriginatingShellId(), and OriginatingShellIds().
G4DataVector G4RDFluoTransition::transitionEnergies private
Definition at line 91 of file G4RDFluoTransition.hh.
View newest version in sPHENIX GitHub at line 91 of file G4RDFluoTransition.hh
Referenced by TransitionEnergies(), and TransitionEnergy().
G4DataVector G4RDFluoTransition::transitionProbabilities private
Definition at line 92 of file G4RDFluoTransition.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RDFluoTransition.hh
Referenced by TransitionProbabilities(), and TransitionProbability().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDFluoTransition.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDFluoTransition.cc