ECCE @ EIC Software: B01RunAction Class Reference
B01RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/B01/include/B01RunAction.hh>
Public Member Functions
B01RunAction ()
virtual ~B01RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void PrintHeader (std::ostream *out)
std::string FillString (const std::string &name, char c, G4int n, G4bool back=true)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
std::vector< G4String > fSDName
G4int fFieldValue
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 48 of file B01RunAction.hh.
View newest version in sPHENIX GitHub at line 48 of file B01RunAction.hh
Constructor & Destructor Documentation
B01RunAction::B01RunAction ()
Definition at line 50 of file B01RunAction.cc.
View newest version in sPHENIX GitHub at line 50 of file B01RunAction.cc
References fSDName.
B01RunAction::~B01RunAction () virtual
Definition at line 63 of file B01RunAction.cc.
View newest version in sPHENIX GitHub at line 63 of file B01RunAction.cc
References fSDName.
Member Function Documentation
void B01RunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 80 of file B01RunAction.cc.
View newest version in sPHENIX GitHub at line 80 of file B01RunAction.cc
References G4cout, G4endl, and G4Run::GetRunID().
void B01RunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 87 of file B01RunAction.cc.
View newest version in sPHENIX GitHub at line 87 of file B01RunAction.cc
References fFieldValue, fSDName, G4cout, G4endl, B01DetectorConstruction::GetCellName(), B01Run::GetHitsMap(), G4Run::GetNumberOfEvent(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), G4UserRunAction::IsMaster(), PrintHeader(), and SL.
std::string B01RunAction::FillString (const std::string & name, char c, G4int n, G4bool back = true)
Definition at line 239 of file B01RunAction.cc.
View newest version in sPHENIX GitHub at line 239 of file B01RunAction.cc
References test::fname, and k.
G4Run * B01RunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 70 of file B01RunAction.cc.
View newest version in sPHENIX GitHub at line 70 of file B01RunAction.cc
References fSDName.
void B01RunAction::PrintHeader (std::ostream * out)
Definition at line 204 of file B01RunAction.cc.
View newest version in sPHENIX GitHub at line 204 of file B01RunAction.cc
References fFieldValue, G4endl, and it.
Referenced by EndOfRunAction().
Member Data Documentation
G4int B01RunAction::fFieldValue private
Definition at line 71 of file B01RunAction.hh.
View newest version in sPHENIX GitHub at line 71 of file B01RunAction.hh
Referenced by EndOfRunAction(), and PrintHeader().
std::vector<G4String> B01RunAction::fSDName private
Definition at line 69 of file B01RunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file B01RunAction.hh
Referenced by B01RunAction(), EndOfRunAction(), GenerateRun(), and ~B01RunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/B01/include/B01RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/B01/src/B01RunAction.cc