ECCE @ EIC Software: G4SynchrotronRadiationInMat Class Reference
G4SynchrotronRadiationInMat Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4SynchrotronRadiationInMat.hh>
Public Member Functions
G4SynchrotronRadiationInMat (const G4String &processName="SynchrotronRadiation", G4ProcessType type=fElectromagnetic)
virtual ~G4SynchrotronRadiationInMat ()
G4double GetMeanFreePath (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &Step) override
G4double GetPhotonEnergy (const G4Track &trackData, const G4Step &stepData)
G4double GetRandomEnergySR (G4double, G4double)
G4double GetProbSpectrumSRforInt (G4double)
G4double GetIntProbSR (G4double)
G4double GetProbSpectrumSRforEnergy (G4double)
G4double GetEnergyProbSR (G4double)
G4double GetIntegrandForAngleK (G4double)
G4double GetAngleK (G4double)
G4double GetAngleNumberAtGammaKsi (G4double)
G4bool IsApplicable (const G4ParticleDefinition &) override
void SetRootNumber (G4int rn)
void SetVerboseLevel (G4int v)
void SetKsi (G4double ksi)
void SetEta (G4double eta)
void SetPsiGamma (G4double psg)
void SetOrderAngleK (G4double ord)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static G4double GetLambdaConst ()
static G4double GetEnergyConst ()
Private Member Functions
G4SynchrotronRadiationInMat & operator= (const G4SynchrotronRadiationInMat &right)=delete
G4SynchrotronRadiationInMat (const G4SynchrotronRadiationInMat &)=delete
Private Attributes
const G4double LowestKineticEnergy
G4double CutInRange
const G4ParticleDefinition * theGamma
const G4ParticleDefinition * theElectron
const G4ParticleDefinition * thePositron
G4double GammaCutInKineticEnergyNow
G4double ElectronCutInKineticEnergyNow
G4double PositronCutInKineticEnergyNow
G4double ParticleCutInKineticEnergyNow
G4double fAlpha
G4int fRootNumber
G4double fKsi
G4double fPsiGamma
G4double fEta
G4double fOrderAngleK
G4int fVerboseLevel
G4PropagatorInField * fFieldPropagator
Static Private Attributes
static const G4double fLambdaConst
static const G4double fEnergyConst
static const G4double fIntegralProbabilityOfSR [200]
Additional Inherited Members
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 67 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 67 of file G4SynchrotronRadiationInMat.hh
Constructor & Destructor Documentation
G4SynchrotronRadiationInMat::G4SynchrotronRadiationInMat (const G4String & processName = "SynchrotronRadiation", G4ProcessType type = fElectromagnetic) explicit
Definition at line 122 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 122 of file G4SynchrotronRadiationInMat.cc
References CutInRange, ElectronCutInKineticEnergyNow, fEta, fFieldPropagator, fKsi, fOrderAngleK, fPsiGamma, fSynchrotronRadiation, GammaCutInKineticEnergyNow, G4TransportationManager::GetPropagatorInField(), G4TransportationManager::GetTransportationManager(), ParticleCutInKineticEnergyNow, PositronCutInKineticEnergyNow, and G4VProcess::SetProcessSubType().
G4SynchrotronRadiationInMat::~G4SynchrotronRadiationInMat () virtual
Definition at line 145 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 145 of file G4SynchrotronRadiationInMat.cc
G4SynchrotronRadiationInMat::G4SynchrotronRadiationInMat (const G4SynchrotronRadiationInMat &) private delete
Member Function Documentation
G4double G4SynchrotronRadiationInMat::GetAngleK (G4double eta)
Definition at line 638 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 638 of file G4SynchrotronRadiationInMat.cc
References a, Acts::VectorHelpers::eta(), fAlpha, fEta, fRootNumber, GetIntegrandForAngleK(), G4Integrator< T, F >::Laguerre(), and n.
Referenced by GetAngleNumberAtGammaKsi().
G4double G4SynchrotronRadiationInMat::GetAngleNumberAtGammaKsi (G4double gpsi)
Definition at line 659 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 659 of file G4SynchrotronRadiationInMat.cc
References fEta, fKsi, fOrderAngleK, fPsiGamma, and GetAngleK().
G4double G4SynchrotronRadiationInMat::GetEnergyConst () static
Definition at line 161 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 161 of file G4SynchrotronRadiationInMat.cc
References fEnergyConst.
G4double G4SynchrotronRadiationInMat::GetEnergyProbSR (G4double ksi)
Definition at line 601 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 601 of file G4SynchrotronRadiationInMat.cc
References a, fAlpha, fKsi, fRootNumber, GetProbSpectrumSRforEnergy(), G4Integrator< T, F >::Laguerre(), n, and pi.
G4double G4SynchrotronRadiationInMat::GetIntegrandForAngleK (G4double t)
Definition at line 625 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 625 of file G4SynchrotronRadiationInMat.cc
References fEta, and fOrderAngleK.
Referenced by GetAngleK().
G4double G4SynchrotronRadiationInMat::GetIntProbSR (G4double ksi)
Definition at line 562 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 562 of file G4SynchrotronRadiationInMat.cc
References a, fAlpha, fKsi, fRootNumber, GetProbSpectrumSRforInt(), G4Integrator< T, F >::Laguerre(), n, and pi.
G4double G4SynchrotronRadiationInMat::GetLambdaConst () static
Definition at line 156 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 156 of file G4SynchrotronRadiationInMat.cc
References fLambdaConst.
G4double G4SynchrotronRadiationInMat::GetMeanFreePath (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) override virtual
Implements G4VDiscreteProcess.
Definition at line 175 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 175 of file G4SynchrotronRadiationInMat.cc
References CLHEP::Hep3Vector::cross(), DBL_MAX, e3, fFieldPropagator, G4PropagatorInField::FindAndSetFieldManager(), fLambdaConst, fVerboseLevel, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Field::GetFieldValue(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGCharge(), G4Track::GetPosition(), G4DynamicParticle::GetTotalEnergy(), G4DynamicParticle::GetTotalMomentum(), G4Track::GetVolume(), LowestKineticEnergy, m, CLHEP::Hep3Vector::mag(), NotForced, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4SynchrotronRadiationInMat::GetPhotonEnergy (const G4Track & trackData, const G4Step & stepData)
Definition at line 423 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 423 of file G4SynchrotronRadiationInMat.cc
References CLHEP::Hep3Vector::cross(), fEnergyConst, fFieldPropagator, G4PropagatorInField::FindAndSetFieldManager(), fIntegralProbabilityOfSR, G4UniformRand, G4DynamicParticle::GetDefinition(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Field::GetFieldValue(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGCharge(), G4Track::GetPosition(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetVolume(), CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4SynchrotronRadiationInMat::GetProbSpectrumSRforEnergy (G4double t)
Definition at line 586 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 586 of file G4SynchrotronRadiationInMat.cc
References fKsi.
Referenced by GetEnergyProbSR().
G4double G4SynchrotronRadiationInMat::GetProbSpectrumSRforInt (G4double t)
Definition at line 546 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 546 of file G4SynchrotronRadiationInMat.cc
References fKsi.
Referenced by GetIntProbSR().
G4double G4SynchrotronRadiationInMat::GetRandomEnergySR (G4double gamma, G4double perpB)
Definition at line 516 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 516 of file G4SynchrotronRadiationInMat.cc
References fEnergyConst, fIntegralProbabilityOfSR, G4UniformRand, and position.
Referenced by PostStepDoIt().
G4bool G4SynchrotronRadiationInMat::IsApplicable (const G4ParticleDefinition & particle) override virtual
Reimplemented from G4VProcess.
Definition at line 150 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 150 of file G4SynchrotronRadiationInMat.cc
References theElectron, and thePositron.
G4SynchrotronRadiationInMat& G4SynchrotronRadiationInMat::operator= (const G4SynchrotronRadiationInMat & right) private delete
G4VParticleChange * G4SynchrotronRadiationInMat::PostStepDoIt (const G4Track & track, const G4Step & Step) override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 260 of file G4SynchrotronRadiationInMat.cc.
View newest version in sPHENIX GitHub at line 260 of file G4SynchrotronRadiationInMat.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, charge, CLHEP::Hep3Vector::cross(), e3, fcos(), fFieldPropagator, G4PropagatorInField::FindAndSetFieldManager(), fStopAndKill, fStopButAlive, fVerboseLevel, G4cout, G4endl, G4UniformRand, G4Gamma::Gamma(), G4DynamicParticle::GetDefinition(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Field::GetFieldValue(), G4Track::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetPDGCharge(), G4Track::GetPosition(), GetRandomEnergySR(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetVolume(), G4ParticleChange::Initialize(), keV, CLHEP::Hep3Vector::mag(), G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), CLHEP::Hep3Vector::rotateUz(), G4VParticleChange::SetNumberOfSecondaries(), G4DynamicParticle::SetPolarization(), twopi, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4SynchrotronRadiationInMat::SetEta (G4double eta) inline
Definition at line 115 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 115 of file G4SynchrotronRadiationInMat.hh
References Acts::VectorHelpers::eta(), and fEta.
void G4SynchrotronRadiationInMat::SetKsi (G4double ksi) inline
Definition at line 114 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 114 of file G4SynchrotronRadiationInMat.hh
References fKsi.
void G4SynchrotronRadiationInMat::SetOrderAngleK (G4double ord) inline
Definition at line 117 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 117 of file G4SynchrotronRadiationInMat.hh
References fOrderAngleK.
void G4SynchrotronRadiationInMat::SetPsiGamma (G4double psg) inline
Definition at line 116 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 116 of file G4SynchrotronRadiationInMat.hh
References fPsiGamma.
void G4SynchrotronRadiationInMat::SetRootNumber (G4int rn) inline
Definition at line 112 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 112 of file G4SynchrotronRadiationInMat.hh
References fRootNumber.
void G4SynchrotronRadiationInMat::SetVerboseLevel (G4int v) inline
Definition at line 113 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 113 of file G4SynchrotronRadiationInMat.hh
References fVerboseLevel, and v.
Member Data Documentation
G4double G4SynchrotronRadiationInMat::CutInRange private
Definition at line 130 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 130 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat().
G4double G4SynchrotronRadiationInMat::ElectronCutInKineticEnergyNow private
Definition at line 137 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 137 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat().
G4double G4SynchrotronRadiationInMat::fAlpha private
Definition at line 141 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 141 of file G4SynchrotronRadiationInMat.hh
Referenced by GetAngleK(), GetEnergyProbSR(), and GetIntProbSR().
const G4double G4SynchrotronRadiationInMat::fEnergyConst static private
Initial value:
= 1.5*c_light*c_light*eplus*hbar_Planck/
                                       electron_mass_c2
Definition at line 123 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 123 of file G4SynchrotronRadiationInMat.hh
Referenced by GetEnergyConst(), GetPhotonEnergy(), and GetRandomEnergySR().
G4double G4SynchrotronRadiationInMat::fEta private
Definition at line 145 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 145 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat(), GetAngleK(), GetAngleNumberAtGammaKsi(), GetIntegrandForAngleK(), and SetEta().
G4PropagatorInField* G4SynchrotronRadiationInMat::fFieldPropagator private
Definition at line 150 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 150 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat(), GetMeanFreePath(), GetPhotonEnergy(), and PostStepDoIt().
const G4double G4SynchrotronRadiationInMat::fIntegralProbabilityOfSR static private
Definition at line 125 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 125 of file G4SynchrotronRadiationInMat.hh
Referenced by GetPhotonEnergy(), and GetRandomEnergySR().
G4double G4SynchrotronRadiationInMat::fKsi private
Definition at line 143 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 143 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat(), GetAngleNumberAtGammaKsi(), GetEnergyProbSR(), GetIntProbSR(), GetProbSpectrumSRforEnergy(), GetProbSpectrumSRforInt(), and SetKsi().
const G4double G4SynchrotronRadiationInMat::fLambdaConst static private
Initial value:
= std::sqrt(3.0)*electron_mass_c2/
                                       (2.5*fine_structure_const*eplus*c_light)
Definition at line 117 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 117 of file G4SynchrotronRadiationInMat.hh
Referenced by GetLambdaConst(), and GetMeanFreePath().
G4double G4SynchrotronRadiationInMat::fOrderAngleK private
Definition at line 146 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 146 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat(), GetAngleNumberAtGammaKsi(), GetIntegrandForAngleK(), and SetOrderAngleK().
G4double G4SynchrotronRadiationInMat::fPsiGamma private
Definition at line 144 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 144 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat(), GetAngleNumberAtGammaKsi(), and SetPsiGamma().
G4int G4SynchrotronRadiationInMat::fRootNumber private
Definition at line 142 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 142 of file G4SynchrotronRadiationInMat.hh
Referenced by GetAngleK(), GetEnergyProbSR(), GetIntProbSR(), and SetRootNumber().
G4int G4SynchrotronRadiationInMat::fVerboseLevel private
Definition at line 149 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 149 of file G4SynchrotronRadiationInMat.hh
Referenced by GetMeanFreePath(), PostStepDoIt(), and SetVerboseLevel().
G4double G4SynchrotronRadiationInMat::GammaCutInKineticEnergyNow private
Definition at line 136 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 136 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat().
const G4double G4SynchrotronRadiationInMat::LowestKineticEnergy private
Definition at line 128 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 128 of file G4SynchrotronRadiationInMat.hh
Referenced by GetMeanFreePath().
G4double G4SynchrotronRadiationInMat::ParticleCutInKineticEnergyNow private
Definition at line 139 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 139 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat().
G4double G4SynchrotronRadiationInMat::PositronCutInKineticEnergyNow private
Definition at line 138 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 138 of file G4SynchrotronRadiationInMat.hh
Referenced by G4SynchrotronRadiationInMat().
const G4ParticleDefinition* G4SynchrotronRadiationInMat::theElectron private
Definition at line 133 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 133 of file G4SynchrotronRadiationInMat.hh
Referenced by IsApplicable().
const G4ParticleDefinition* G4SynchrotronRadiationInMat::theGamma private
Definition at line 132 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 132 of file G4SynchrotronRadiationInMat.hh
const G4ParticleDefinition* G4SynchrotronRadiationInMat::thePositron private
Definition at line 134 of file G4SynchrotronRadiationInMat.hh.
View newest version in sPHENIX GitHub at line 134 of file G4SynchrotronRadiationInMat.hh
Referenced by IsApplicable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4SynchrotronRadiationInMat.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/src/G4SynchrotronRadiationInMat.cc