ECCE @ EIC Software: G4RTMessenger Class Reference
G4RTMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTMessenger.hh>
Public Member Functions
virtual ~G4RTMessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
virtual void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Static Public Member Functions
static G4RTMessenger * GetInstance (G4TheRayTracer *p1)
Private Member Functions
G4RTMessenger (G4TheRayTracer *p1)
Private Attributes
G4TheRayTracer * theDefaultTracer
G4TheRayTracer * theTracer
G4UIdirectory * rayDirectory
G4UIcmdWithAnInteger * columnCmd
G4UIcmdWithAnInteger * rowCmd
G4UIcmdWith3VectorAndUnit * targetCmd
G4UIcmdWith3VectorAndUnit * eyePosCmd
G4UIcmdWith3Vector * lightCmd
G4UIcmdWithADoubleAndUnit * spanXCmd
G4UIcmdWithADoubleAndUnit * headCmd
G4UIcmdWithADoubleAndUnit * attCmd
G4UIcmdWithABool * distCmd
G4UIcmdWithABool * transCmd
G4UIcmdWithAString * fileCmd
G4UIcmdWith3Vector * bkgColCmd
Static Private Attributes
static G4RTMessenger * fpInstance = 0
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 50 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RTMessenger.hh
Constructor & Destructor Documentation
G4RTMessenger::~G4RTMessenger () virtual
Definition at line 139 of file G4RTMessenger.cc.
View newest version in sPHENIX GitHub at line 139 of file G4RTMessenger.cc
References attCmd, bkgColCmd, columnCmd, distCmd, eyePosCmd, fileCmd, headCmd, lightCmd, rayDirectory, rowCmd, spanXCmd, targetCmd, and transCmd.
G4RTMessenger::G4RTMessenger (G4TheRayTracer * p1) private
Definition at line 56 of file G4RTMessenger.cc.
View newest version in sPHENIX GitHub at line 56 of file G4RTMessenger.cc
References attCmd, G4UIcommand::AvailableForStates(), bkgColCmd, columnCmd, distCmd, eyePosCmd, fileCmd, G4State_Idle, headCmd, lightCmd, rayDirectory, rowCmd, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWith3Vector::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4UIcommand::SetRange(), spanXCmd, targetCmd, theDefaultTracer, theTracer, and transCmd.
Member Function Documentation
G4String G4RTMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 156 of file G4RTMessenger.cc.
View newest version in sPHENIX GitHub at line 156 of file G4RTMessenger.cc
References attCmd, bkgColCmd, columnCmd, G4UIcommand::ConvertToString(), distCmd, eyePosCmd, G4TheRayTracer::GetAttenuationLength(), G4TheRayTracer::GetBackgroundColour(), G4TheRayTracer::GetDistortion(), G4TheRayTracer::GetEyePosition(), G4TheRayTracer::GetHeadAngle(), G4RTSteppingAction::GetIgnoreTransparency(), G4TheRayTracer::GetLightDirection(), G4TheRayTracer::GetNColumn(), G4TheRayTracer::GetNRow(), G4TheRayTracer::GetTargetPosition(), G4TheRayTracer::GetViewSpan(), headCmd, lightCmd, rowCmd, spanXCmd, targetCmd, theTracer, and transCmd.
G4RTMessenger * G4RTMessenger::GetInstance (G4TheRayTracer * p1) static
Definition at line 50 of file G4RTMessenger.cc.
View newest version in sPHENIX GitHub at line 50 of file G4RTMessenger.cc
Referenced by G4TheRayTracer::G4TheRayTracer().
void G4RTMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 184 of file G4RTMessenger.cc.
View newest version in sPHENIX GitHub at line 184 of file G4RTMessenger.cc
References attCmd, bkgColCmd, columnCmd, distCmd, eyePosCmd, fileCmd, G4cout, G4endl, G4VisManager::GetCurrentViewer(), G4VisManager::GetInstance(), G4UIcmdWith3Vector::GetNew3VectorValue(), G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4RayTracerViewer::GetTracer(), headCmd, lightCmd, rowCmd, G4TheRayTracer::SetAttenuationLength(), G4TheRayTracer::SetDistortion(), G4TheRayTracer::SetEyePosition(), G4TheRayTracer::SetHeadAngle(), G4RTSteppingAction::SetIgnoreTransparency(), G4TheRayTracer::SetLightDirection(), G4TheRayTracer::SetNColumn(), G4TheRayTracer::SetNRow(), G4TheRayTracer::SetTargetPosition(), G4TheRayTracer::SetViewSpan(), spanXCmd, targetCmd, theDefaultTracer, theTracer, G4TheRayTracer::Trace(), and transCmd.
Member Data Documentation
G4UIcmdWithADoubleAndUnit* G4RTMessenger::attCmd private
Definition at line 74 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIcmdWith3Vector* G4RTMessenger::bkgColCmd private
Definition at line 78 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIcmdWithAnInteger* G4RTMessenger::columnCmd private
Definition at line 67 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIcmdWithABool* G4RTMessenger::distCmd private
Definition at line 75 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIcmdWith3VectorAndUnit* G4RTMessenger::eyePosCmd private
Definition at line 70 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIcmdWithAString* G4RTMessenger::fileCmd private
Definition at line 77 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), SetNewValue(), and ~G4RTMessenger().
G4RTMessenger * G4RTMessenger::fpInstance = 0 static private
Definition at line 61 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file G4RTMessenger.hh
G4UIcmdWithADoubleAndUnit* G4RTMessenger::headCmd private
Definition at line 73 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIcmdWith3Vector* G4RTMessenger::lightCmd private
Definition at line 71 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIdirectory* G4RTMessenger::rayDirectory private
Definition at line 66 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), and ~G4RTMessenger().
G4UIcmdWithAnInteger* G4RTMessenger::rowCmd private
Definition at line 68 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIcmdWithADoubleAndUnit* G4RTMessenger::spanXCmd private
Definition at line 72 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4UIcmdWith3VectorAndUnit* G4RTMessenger::targetCmd private
Definition at line 69 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
G4TheRayTracer* G4RTMessenger::theDefaultTracer private
Definition at line 62 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), and SetNewValue().
G4TheRayTracer* G4RTMessenger::theTracer private
Definition at line 64 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), and SetNewValue().
G4UIcmdWithABool* G4RTMessenger::transCmd private
Definition at line 76 of file G4RTMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4RTMessenger.hh
Referenced by G4RTMessenger(), GetCurrentValue(), SetNewValue(), and ~G4RTMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTMessenger.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4RTMessenger.cc