ECCE @ EIC Software: B1SteppingAction Class Reference
B1SteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B1/include/B1SteppingAction.hh>
Public Member Functions
B1SteppingAction (B1EventAction *eventAction)
virtual ~B1SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
B1SteppingAction (B1EventAction *eventAction)
virtual ~B1SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
B1SteppingAction (B1EventAction *eventAction)
virtual ~B1SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
B1EventAction * fEventAction
G4LogicalVolume * fScoringVolume
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Stepping action class
Definition at line 43 of file B1SteppingAction.hh.
View newest version in sPHENIX GitHub at line 43 of file B1SteppingAction.hh
Constructor & Destructor Documentation
B1SteppingAction::B1SteppingAction (B1EventAction * eventAction)
Definition at line 41 of file B1SteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file B1SteppingAction.cc
B1SteppingAction::~B1SteppingAction () virtual
Definition at line 49 of file B1SteppingAction.cc.
View newest version in sPHENIX GitHub at line 49 of file B1SteppingAction.cc
B1SteppingAction::B1SteppingAction (B1EventAction * eventAction)
virtual B1SteppingAction::~B1SteppingAction () virtual
B1SteppingAction::B1SteppingAction (B1EventAction * eventAction)
virtual B1SteppingAction::~B1SteppingAction () virtual
Member Function Documentation
void B1SteppingAction::UserSteppingAction (const G4Step * step) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 54 of file B1SteppingAction.cc.
View newest version in sPHENIX GitHub at line 54 of file B1SteppingAction.cc
References B1EventAction::AddEdep(), fEventAction, fScoringVolume, G4VPhysicalVolume::GetLogicalVolume(), G4Step::GetPreStepPoint(), G4RunManager::GetRunManager(), B1DetectorConstruction::GetScoringVolume(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchableHandle(), G4RunManager::GetUserDetectorConstruction(), G4VTouchable::GetVolume(), and Acts::Test::volume.
virtual void B1SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void B1SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
Member Data Documentation
B1EventAction * B1SteppingAction::fEventAction private
Definition at line 53 of file B1SteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file B1SteppingAction.hh
Referenced by UserSteppingAction().
G4LogicalVolume * B1SteppingAction::fScoringVolume private
Definition at line 54 of file B1SteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file B1SteppingAction.hh
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B1/include/B1SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/include/B1SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/include/B1SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B1/src/B1SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/B1Con/src/B1SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/src/B1SteppingAction.cc