ECCE @ EIC Software: G4GeneratorPrecompoundInterface Class Reference
G4GeneratorPrecompoundInterface Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4GeneratorPrecompoundInterface.hh>
Public Member Functions
G4GeneratorPrecompoundInterface (G4VPreCompoundModel *p=0)
virtual ~G4GeneratorPrecompoundInterface ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
virtual G4ReactionProductVector * Propagate (G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus)
virtual G4ReactionProductVector * PropagateNuclNucl (G4KineticTrackVector *theSecondaries, G4V3DNucleus *theNucleus, G4V3DNucleus *theProjectileNucleus)
void SetCaptureThreshold (G4double)
void SetDeltaM (G4double)
void SetDeltaR (G4double)
void MakeCoalescence (G4KineticTrackVector *theSecondaries)
virtual void PropagateModelDescription (std::ostream &) const
Public Member Functions inherited from G4VIntraNuclearTransportModel
G4VIntraNuclearTransportModel (const G4String &mName="CascadeModel", G4VPreCompoundModel *ptr=nullptr)
virtual ~G4VIntraNuclearTransportModel ()
void SetDeExcitation (G4VPreCompoundModel *ptr)
void Set3DNucleus (G4V3DNucleus *const value)
void SetPrimaryProjectile (const G4HadProjectile &aPrimary)
const G4String & GetModelName () const
virtual void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
G4GeneratorPrecompoundInterface (const G4GeneratorPrecompoundInterface &right)
const
G4GeneratorPrecompoundInterface & operator= (const G4GeneratorPrecompoundInterface &right)
G4bool operator== (G4GeneratorPrecompoundInterface &right)
G4bool operator!= (G4GeneratorPrecompoundInterface &right)
Private Attributes
G4double CaptureThreshold
G4double DeltaM
G4double DeltaR
const G4ParticleDefinition * proton
const G4ParticleDefinition * neutron
const G4ParticleDefinition * deuteron
const G4ParticleDefinition * triton
const G4ParticleDefinition * He3
const G4ParticleDefinition * He4
const G4ParticleDefinition * ANTIproton
const G4ParticleDefinition * ANTIneutron
const G4ParticleDefinition * ANTIdeuteron
const G4ParticleDefinition * ANTItriton
const G4ParticleDefinition * ANTIHe3
const G4ParticleDefinition * ANTIHe4
Additional Inherited Members
Protected Member Functions inherited from G4VIntraNuclearTransportModel
G4V3DNucleus * Get3DNucleus () const
G4VPreCompoundModel * GetDeExcitation () const
const G4HadProjectile * GetPrimaryProjectile () const
Protected Attributes inherited from G4VIntraNuclearTransportModel
G4String theTransportModelName
G4V3DNucleus * the3DNucleus
G4VPreCompoundModel * theDeExcitation
const G4HadProjectile * thePrimaryProjectile
Detailed Description
Definition at line 59 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 59 of file G4GeneratorPrecompoundInterface.hh
Constructor & Destructor Documentation
G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface (G4VPreCompoundModel * p = 0)
Definition at line 78 of file G4GeneratorPrecompoundInterface.cc.
View newest version in sPHENIX GitHub at line 78 of file G4GeneratorPrecompoundInterface.cc
References G4Alpha::Alpha(), G4AntiAlpha::AntiAlpha(), G4AntiDeuteron::AntiDeuteron(), ANTIdeuteron, G4AntiHe3::AntiHe3(), ANTIHe3, ANTIHe4, G4AntiNeutron::AntiNeutron(), ANTIneutron, G4AntiProton::AntiProton(), ANTIproton, G4AntiTriton::AntiTriton(), ANTItriton, G4Deuteron::Deuteron(), deuteron, G4HadronicInteractionRegistry::FindModel(), G4He3::He3(), He3, He4, G4HadronicInteractionRegistry::Instance(), G4Neutron::Neutron(), neutron, G4Proton::Proton(), proton, G4VIntraNuclearTransportModel::SetDeExcitation(), G4Triton::Triton(), and triton.
G4GeneratorPrecompoundInterface::~G4GeneratorPrecompoundInterface () virtual
Definition at line 107 of file G4GeneratorPrecompoundInterface.cc.
View newest version in sPHENIX GitHub at line 107 of file G4GeneratorPrecompoundInterface.cc
G4GeneratorPrecompoundInterface::G4GeneratorPrecompoundInterface (const G4GeneratorPrecompoundInterface & right) private
Member Function Documentation
G4HadFinalState * G4GeneratorPrecompoundInterface::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 324 of file G4GeneratorPrecompoundInterface.cc.
View newest version in sPHENIX GitHub at line 324 of file G4GeneratorPrecompoundInterface.cc
References G4cout, and G4endl.
void G4GeneratorPrecompoundInterface::MakeCoalescence (G4KineticTrackVector * theSecondaries)
Definition at line 720 of file G4GeneratorPrecompoundInterface.cc.
View newest version in sPHENIX GitHub at line 720 of file G4GeneratorPrecompoundInterface.cc
References DeltaM, deuteron, fermi, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4KineticTrack::GetFormationTime(), G4ParticleDefinition::GetPDGMass(), G4KineticTrack::GetPosition(), source.hepunit::hbarc, neutron, and proton.
Referenced by PropagateNuclNucl().
G4bool G4GeneratorPrecompoundInterface::operator!= (G4GeneratorPrecompoundInterface & right) inline private
Definition at line 90 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 90 of file G4GeneratorPrecompoundInterface.hh
const G4GeneratorPrecompoundInterface& G4GeneratorPrecompoundInterface::operator= (const G4GeneratorPrecompoundInterface & right) private
G4bool G4GeneratorPrecompoundInterface::operator== (G4GeneratorPrecompoundInterface & right) inline private
Definition at line 89 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 89 of file G4GeneratorPrecompoundInterface.hh
G4ReactionProductVector * G4GeneratorPrecompoundInterface::Propagate (G4KineticTrackVector * theSecondaries, G4V3DNucleus * theNucleus) virtual
Implements G4VIntraNuclearTransportModel.
Definition at line 112 of file G4GeneratorPrecompoundInterface.cc.
View newest version in sPHENIX GitHub at line 112 of file G4GeneratorPrecompoundInterface.cc
References G4Nucleon::AreYouHit(), CaptureThreshold, G4INCL::ClusterDecay::decay(), G4VPreCompoundModel::DeExcite(), e, eplus, G4cin, G4cout, G4endl, G4Log(), G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleon::Get4Momentum(), G4V3DNucleus::GetCharge(), G4Nucleon::GetDefinition(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNextNucleon(), G4NucleiProperties::GetNuclearMass(), G4V3DNucleus::GetNuclearRadius(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4VIntraNuclearTransportModel::GetPrimaryProjectile(), CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), mass, MeV, mom, neutron, part, proton, Acts::IntegrationTest::R, CLHEP::HepLorentzVector::setE(), G4ReactionProduct::SetMomentum(), G4Fragment::SetNumberOfCharged(), G4Fragment::SetNumberOfHoles(), G4Fragment::SetNumberOfParticles(), G4ReactionProduct::SetTotalEnergy(), sqr(), G4V3DNucleus::StartLoop(), G4VIntraNuclearTransportModel::theDeExcitation, CLHEP::HepLorentzVector::vect(), and Z.
void G4GeneratorPrecompoundInterface::PropagateModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4VIntraNuclearTransportModel.
Definition at line 333 of file G4GeneratorPrecompoundInterface.cc.
View newest version in sPHENIX GitHub at line 333 of file G4GeneratorPrecompoundInterface.cc
G4ReactionProductVector * G4GeneratorPrecompoundInterface::PropagateNuclNucl (G4KineticTrackVector * theSecondaries, G4V3DNucleus * theNucleus, G4V3DNucleus * theProjectileNucleus) virtual
Reimplemented from G4VIntraNuclearTransportModel.
Definition at line 348 of file G4GeneratorPrecompoundInterface.cc.
View newest version in sPHENIX GitHub at line 348 of file G4GeneratorPrecompoundInterface.cc
References G4AntiAlpha::AntiAlphaDefinition(), G4AntiDeuteron::AntiDeuteronDefinition(), G4AntiHe3::AntiHe3Definition(), ANTIneutron, G4AntiNeutron::AntiNeutronDefinition(), ANTIproton, G4AntiProton::AntiProtonDefinition(), G4AntiTriton::AntiTritonDefinition(), G4Nucleon::AreYouHit(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), CaptureThreshold, G4INCL::ClusterDecay::decay(), G4VPreCompoundModel::DeExcite(), deuteron, CLHEP::HepLorentzVector::e(), eplus, CLHEP::HepLorentzVector::findBoostToCM(), G4cout, G4endl, G4Log(), G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleon::Get4Momentum(), G4ParticleDefinition::GetBaryonNumber(), G4Nucleon::GetBindingEnergy(), G4V3DNucleus::GetCharge(), G4HadProjectile::GetDefinition(), G4Nucleon::GetDefinition(), G4ReactionProduct::GetDefinition(), G4V3DNucleus::GetMassNumber(), G4ReactionProduct::GetMomentum(), G4V3DNucleus::GetNextNucleon(), G4NucleiProperties::GetNuclearMass(), G4V3DNucleus::GetNuclearRadius(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4VIntraNuclearTransportModel::GetPrimaryProjectile(), G4ReactionProduct::GetTotalEnergy(), He3, He4, CLHEP::HepLorentzVector::mag(), CLHEP::Hep3Vector::mag2(), CLHEP::HepLorentzVector::mag2(), MakeCoalescence(), neutron, part, proton, Acts::IntegrationTest::R, CLHEP::HepLorentzVector::setE(), G4ReactionProduct::SetMomentum(), G4Fragment::SetNumberOfCharged(), G4Fragment::SetNumberOfHoles(), G4Fragment::SetNumberOfParticles(), G4ReactionProduct::SetTotalEnergy(), G4V3DNucleus::StartLoop(), G4VIntraNuclearTransportModel::theDeExcitation, tmp, triton, CLHEP::HepLorentzVector::vect(), and Z.
void G4GeneratorPrecompoundInterface::SetCaptureThreshold (G4double value) inline
Definition at line 114 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 114 of file G4GeneratorPrecompoundInterface.hh
References CaptureThreshold.
void G4GeneratorPrecompoundInterface::SetDeltaM (G4double value) inline
Definition at line 120 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 120 of file G4GeneratorPrecompoundInterface.hh
References DeltaM.
void G4GeneratorPrecompoundInterface::SetDeltaR (G4double value) inline
Definition at line 126 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 126 of file G4GeneratorPrecompoundInterface.hh
References DeltaR.
Member Data Documentation
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::ANTIdeuteron private
Definition at line 107 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 107 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::ANTIHe3 private
Definition at line 109 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 109 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::ANTIHe4 private
Definition at line 110 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 110 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::ANTIneutron private
Definition at line 105 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 105 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface(), and PropagateNuclNucl().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::ANTIproton private
Definition at line 104 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 104 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface(), and PropagateNuclNucl().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::ANTItriton private
Definition at line 108 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 108 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface().
G4double G4GeneratorPrecompoundInterface::CaptureThreshold private
Definition at line 92 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 92 of file G4GeneratorPrecompoundInterface.hh
Referenced by Propagate(), PropagateNuclNucl(), and SetCaptureThreshold().
G4double G4GeneratorPrecompoundInterface::DeltaM private
Definition at line 93 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 93 of file G4GeneratorPrecompoundInterface.hh
Referenced by MakeCoalescence(), and SetDeltaM().
G4double G4GeneratorPrecompoundInterface::DeltaR private
Definition at line 94 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 94 of file G4GeneratorPrecompoundInterface.hh
Referenced by SetDeltaR().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::deuteron private
Definition at line 99 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 99 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface(), MakeCoalescence(), and PropagateNuclNucl().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::He3 private
Definition at line 101 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 101 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface(), and PropagateNuclNucl().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::He4 private
Definition at line 102 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 102 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface(), and PropagateNuclNucl().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::neutron private
Definition at line 97 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 97 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface(), MakeCoalescence(), Propagate(), and PropagateNuclNucl().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::proton private
Definition at line 96 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 96 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface(), MakeCoalescence(), Propagate(), and PropagateNuclNucl().
const G4ParticleDefinition* G4GeneratorPrecompoundInterface::triton private
Definition at line 100 of file G4GeneratorPrecompoundInterface.hh.
View newest version in sPHENIX GitHub at line 100 of file G4GeneratorPrecompoundInterface.hh
Referenced by G4GeneratorPrecompoundInterface(), and PropagateNuclNucl().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4GeneratorPrecompoundInterface.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4GeneratorPrecompoundInterface.cc