ECCE @ EIC Software: G4ModelingParameters::PVPointerCopyNo Class Reference
G4ModelingParameters::PVPointerCopyNo Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ModelingParameters.hh>
Public Member Functions
PVPointerCopyNo (G4VPhysicalVolume *pPV, G4int copyNo)
const G4String & GetName () const
const G4VPhysicalVolume * GetPVPointer () const
G4int GetCopyNo () const
G4bool operator!= (const PVPointerCopyNo &) const
G4bool operator== (const PVPointerCopyNo &rhs) const
Private Attributes
G4VPhysicalVolume * fpPV
G4int fCopyNo
Detailed Description
Definition at line 97 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ModelingParameters.hh
Constructor & Destructor Documentation
G4ModelingParameters::PVPointerCopyNo::PVPointerCopyNo (G4VPhysicalVolume * pPV, G4int copyNo) inline
Definition at line 100 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ModelingParameters.hh
Member Function Documentation
G4int G4ModelingParameters::PVPointerCopyNo::GetCopyNo () const inline
Definition at line 104 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ModelingParameters.hh
References fCopyNo.
const G4String & G4ModelingParameters::PVPointerCopyNo::GetName (void) const
Definition at line 361 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 361 of file G4ModelingParameters.cc
References fpPV, and G4VPhysicalVolume::GetName().
const G4VPhysicalVolume* G4ModelingParameters::PVPointerCopyNo::GetPVPointer () const inline
Definition at line 103 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ModelingParameters.hh
References fpPV.
G4bool G4ModelingParameters::PVPointerCopyNo::operator!= (const PVPointerCopyNo & rhs) const
Definition at line 367 of file G4ModelingParameters.cc.
View newest version in sPHENIX GitHub at line 367 of file G4ModelingParameters.cc
Referenced by operator==().
G4bool G4ModelingParameters::PVPointerCopyNo::operator== (const PVPointerCopyNo & rhs) const inline
Definition at line 106 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ModelingParameters.hh
References operator!=().
Member Data Documentation
G4int G4ModelingParameters::PVPointerCopyNo::fCopyNo private
Definition at line 109 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ModelingParameters.hh
Referenced by GetCopyNo().
G4VPhysicalVolume* G4ModelingParameters::PVPointerCopyNo::fpPV private
Definition at line 108 of file G4ModelingParameters.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ModelingParameters.hh
Referenced by GetName(), and GetPVPointer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ModelingParameters.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4ModelingParameters.cc