ECCE @ EIC Software: G4ChipsHyperonInelasticXS Class Reference
G4ChipsHyperonInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsHyperonInelasticXS.hh>
Public Member Functions
G4ChipsHyperonInelasticXS ()
~G4ChipsHyperonInelasticXS ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsIsoApplicable (const G4DynamicParticle *Pt, G4int Z, G4int A, const G4Element *elm, const G4Material *mat)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int tgZ, G4int A, const G4Isotope *iso=0, const G4Element *elm=0, const G4Material *mat=0)
virtual G4double GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
G4double CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum)
G4double CrossSectionLin (G4int targZ, G4int targN, G4double P)
G4double CrossSectionLog (G4int targZ, G4int targN, G4double lP)
G4double CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP)
G4double EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double *Y)
Private Attributes
G4double * lastLEN
G4double * lastHEN
G4int lastN
G4int lastZ
G4double lastP
G4double lastTH
G4double lastCS
G4int lastI
std::vector< G4double * > * LEN
std::vector< G4double * > * HEN
G4int j
std::vector< G4int > colN
std::vector< G4int > colZ
std::vector< G4double > colP
std::vector< G4double > colTH
std::vector< G4double > colCS
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 45 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ChipsHyperonInelasticXS.hh
Constructor & Destructor Documentation
G4ChipsHyperonInelasticXS::G4ChipsHyperonInelasticXS ()
Definition at line 54 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ChipsHyperonInelasticXS.cc
References HEN, lastCS, lastHEN, lastI, lastLEN, lastN, lastP, lastTH, lastZ, and LEN.
G4ChipsHyperonInelasticXS::~G4ChipsHyperonInelasticXS ()
Definition at line 69 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 69 of file G4ChipsHyperonInelasticXS.cc
References HEN, and LEN.
Member Function Documentation
G4double G4ChipsHyperonInelasticXS::CalculateCrossSection (G4int F, G4int I, G4int PDG, G4int Z, G4int N, G4double Momentum) private
Definition at line 214 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 214 of file G4ChipsHyperonInelasticXS.cc
References CrossSectionFormula(), CrossSectionLin(), CrossSectionLog(), EquLinearFit(), G4cerr, G4endl, G4Log(), HEN, k, lastHEN, lastLEN, lastTH, LEN, n, nH, nL, P, and THmin.
Referenced by GetChipsCrossSection().
void G4ChipsHyperonInelasticXS::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 80 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 80 of file G4ChipsHyperonInelasticXS.cc
G4double G4ChipsHyperonInelasticXS::CrossSectionFormula (G4int targZ, G4int targN, G4double P, G4double lP) private
Definition at line 305 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 305 of file G4ChipsHyperonInelasticXS.cc
References a, c, d, e, G4cerr, G4cout, G4endl, G4Exp(), G4Log(), Acts::UnitConstants::h, P, r, G4InuclParticleNames::sp, and t.
Referenced by CalculateCrossSection(), CrossSectionLin(), and CrossSectionLog().
G4double G4ChipsHyperonInelasticXS::CrossSectionLin (G4int targZ, G4int targN, G4double P) private
Definition at line 292 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 292 of file G4ChipsHyperonInelasticXS.cc
References CrossSectionFormula(), and G4Log().
Referenced by CalculateCrossSection().
G4double G4ChipsHyperonInelasticXS::CrossSectionLog (G4int targZ, G4int targN, G4double lP) private
Definition at line 299 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 299 of file G4ChipsHyperonInelasticXS.cc
References CrossSectionFormula(), G4Exp(), and P.
Referenced by CalculateCrossSection().
static const char* G4ChipsHyperonInelasticXS::Default_Name () inline static
Definition at line 54 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ChipsHyperonInelasticXS.hh
Referenced by G4ChipsComponentXS::G4ChipsComponentXS().
G4double G4ChipsHyperonInelasticXS::EquLinearFit (G4double X, G4int N, G4double X0, G4double DX, G4double * Y) private
Definition at line 366 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 366 of file G4ChipsHyperonInelasticXS.cc
References d, G4cerr, and G4endl.
Referenced by CalculateCrossSection().
G4double G4ChipsHyperonInelasticXS::GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg) virtual
!The slave functions must provide cross-sections in millibarns (mb) !! (not in IU)
Definition at line 140 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 140 of file G4ChipsHyperonInelasticXS.cc
References CalculateCrossSection(), colCS, colN, colP, colTH, colZ, in, j, lastCS, lastI, lastN, lastP, lastTH, lastZ, and millibarn.
Referenced by GetIsoCrossSection().
G4double G4ChipsHyperonInelasticXS::GetIsoCrossSection (const G4DynamicParticle * Pt, G4int tgZ, G4int A, const G4Isotope * iso = 0, const G4Element * elm = 0, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 128 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 128 of file G4ChipsHyperonInelasticXS.cc
References GetChipsCrossSection(), G4DynamicParticle::GetDefinition(), G4ParticleDefinition::GetPDGEncoding(), G4DynamicParticle::GetTotalMomentum(), and pdg.
G4bool G4ChipsHyperonInelasticXS::IsIsoApplicable (const G4DynamicParticle * Pt, G4int Z, G4int A, const G4Element * elm, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 88 of file G4ChipsHyperonInelasticXS.cc.
View newest version in sPHENIX GitHub at line 88 of file G4ChipsHyperonInelasticXS.cc
Member Data Documentation
std::vector<G4double> G4ChipsHyperonInelasticXS::colCS private
Definition at line 96 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ChipsHyperonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsHyperonInelasticXS::colN private
Definition at line 92 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ChipsHyperonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsHyperonInelasticXS::colP private
Definition at line 94 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ChipsHyperonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double> G4ChipsHyperonInelasticXS::colTH private
Definition at line 95 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ChipsHyperonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4int> G4ChipsHyperonInelasticXS::colZ private
Definition at line 93 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ChipsHyperonInelasticXS.hh
Referenced by GetChipsCrossSection().
std::vector<G4double*>* G4ChipsHyperonInelasticXS::HEN private
Definition at line 89 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ChipsHyperonInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsHyperonInelasticXS(), and ~G4ChipsHyperonInelasticXS().
G4int G4ChipsHyperonInelasticXS::j private
Definition at line 91 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ChipsHyperonInelasticXS.hh
Referenced by GetChipsCrossSection().
G4double G4ChipsHyperonInelasticXS::lastCS private
Definition at line 86 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChipsHyperonInelasticXS.hh
Referenced by G4ChipsHyperonInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsHyperonInelasticXS::lastHEN private
Definition at line 81 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ChipsHyperonInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsHyperonInelasticXS().
G4int G4ChipsHyperonInelasticXS::lastI private
Definition at line 87 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChipsHyperonInelasticXS.hh
Referenced by G4ChipsHyperonInelasticXS(), and GetChipsCrossSection().
G4double* G4ChipsHyperonInelasticXS::lastLEN private
Definition at line 80 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ChipsHyperonInelasticXS.hh
Referenced by CalculateCrossSection(), and G4ChipsHyperonInelasticXS().
G4int G4ChipsHyperonInelasticXS::lastN private
Definition at line 82 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ChipsHyperonInelasticXS.hh
Referenced by G4ChipsHyperonInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsHyperonInelasticXS::lastP private
Definition at line 84 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChipsHyperonInelasticXS.hh
Referenced by G4ChipsHyperonInelasticXS(), and GetChipsCrossSection().
G4double G4ChipsHyperonInelasticXS::lastTH private
Definition at line 85 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChipsHyperonInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsHyperonInelasticXS(), and GetChipsCrossSection().
G4int G4ChipsHyperonInelasticXS::lastZ private
Definition at line 83 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ChipsHyperonInelasticXS.hh
Referenced by G4ChipsHyperonInelasticXS(), and GetChipsCrossSection().
std::vector<G4double*>* G4ChipsHyperonInelasticXS::LEN private
Definition at line 88 of file G4ChipsHyperonInelasticXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ChipsHyperonInelasticXS.hh
Referenced by CalculateCrossSection(), G4ChipsHyperonInelasticXS(), and ~G4ChipsHyperonInelasticXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsHyperonInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ChipsHyperonInelasticXS.cc