ECCE @ EIC Software: G4VisCommandSceneAddScale Class Reference
G4VisCommandSceneAddScale Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh>
Public Member Functions
G4VisCommandSceneAddScale ()
virtual ~G4VisCommandSceneAddScale ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VVisCommandScene
G4VVisCommandScene ()
virtual ~G4VVisCommandScene ()
Public Member Functions inherited from G4VVisCommand
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4VisCommandSceneAddScale (const G4VisCommandSceneAddScale &)
G4VisCommandSceneAddScale & operator= (const G4VisCommandSceneAddScale &)
Private Attributes
G4UIcommand * fpCommand
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Member Functions inherited from G4VVisCommandScene
G4String CurrentSceneName ()
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommand
static G4VisManager * fpVisManager = 0
static G4int fErrorCode = 0
static G4int fCurrentArrow3DLineSegmentsPerCircle = 6
static G4Colour fCurrentColour = G4Colour::White()
static G4double fCurrentLineWidth = 1.
static G4Colour fCurrentTextColour = G4Colour::Blue()
static G4Text::Layout fCurrentTextLayout = G4Text::left
static G4double fCurrentTextSize = 12.
static
G4PhysicalVolumeModel::TouchableProperties fCurrentTouchableProperties
static G4VisExtent fCurrentExtentForField
static std::vector
< G4PhysicalVolumesSearchScene::Findings > fCurrrentPVFindingsForField
Detailed Description
Definition at line 369 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 369 of file G4VisCommandsSceneAdd.hh
Constructor & Destructor Documentation
G4VisCommandSceneAddScale::G4VisCommandSceneAddScale ()
Definition at line 2040 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2040 of file G4VisCommandsSceneAdd.cc
References G4VisCommandSceneAddLogo::fpCommand, G4Scale::GetGuidanceString(), G4UIparameter::SetDefaultValue(), G4UIparameter::SetGuidance(), and G4UIcommand::SetParameter().
G4VisCommandSceneAddScale::~G4VisCommandSceneAddScale () virtual
Definition at line 2091 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2091 of file G4VisCommandsSceneAdd.cc
References G4VisCommandSceneAddLogo::fpCommand.
G4VisCommandSceneAddScale::G4VisCommandSceneAddScale (const G4VisCommandSceneAddScale &) private
Member Function Documentation
G4String G4VisCommandSceneAddScale::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 2095 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2095 of file G4VisCommandsSceneAdd.cc
G4VisCommandSceneAddScale& G4VisCommandSceneAddScale::operator= (const G4VisCommandSceneAddScale &) private
void G4VisCommandSceneAddScale::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 2099 of file G4VisCommandsSceneAdd.cc.
View newest version in sPHENIX GitHub at line 2099 of file G4VisCommandsSceneAdd.cc
References kdfinder::abs(), G4VVisCommand::CheckSceneAndNotifyHandlers(), G4VisManager::confirmations, G4VisManager::errors, G4VVisCommand::fCurrentTextSize, G4VVisCommand::fpVisManager, G4BestUnit, G4cerr, G4cout, G4endl, G4VVisCommand::G4VisCommandsSceneAddUnsuccessful(), G4VisManager::GetCurrentScene(), G4VisManager::GetCurrentViewer(), G4Scene::GetExtent(), G4VisExtent::GetExtentRadius(), G4VModel::GetGlobalDescription(), HepGeom::Transform3D::getRotation(), HepGeom::Transform3D::getTranslation(), G4ViewParameters::GetUpVector(), G4VisManager::GetVerbosity(), G4VViewer::GetViewParameters(), G4ViewParameters::GetViewpointDirection(), G4VisExtent::GetXmax(), G4VisExtent::GetXmin(), G4VisExtent::GetYmax(), G4VisExtent::GetYmin(), G4VisExtent::GetZmax(), G4VisExtent::GetZmin(), halfpi, BTOF::length, G4VisManager::parameters, scale, G4VModel::SetExtent(), G4VModel::SetGlobalDescription(), G4VModel::SetTransformation(), G4Visible::SetVisAttributes(), Acts::Test::transform, G4UIcommand::ValueOf(), G4VisManager::warnings, G4Scale::x, HepGeom::BasicVector3D< T >::x(), xmin, G4Scale::y, HepGeom::BasicVector3D< T >::y(), ymin, G4Scale::z, and HepGeom::BasicVector3D< T >::z().
Member Data Documentation
G4UIcommand* G4VisCommandSceneAddScale::fpCommand private
Definition at line 378 of file G4VisCommandsSceneAdd.hh.
View newest version in sPHENIX GitHub at line 378 of file G4VisCommandsSceneAdd.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsSceneAdd.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsSceneAdd.cc