ECCE @ EIC Software: G4RPGKPlusInelastic Class Reference
G4RPGKPlusInelastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGKPlusInelastic.hh>
Public Member Functions
G4RPGKPlusInelastic ()
~G4RPGKPlusInelastic ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
Public Member Functions inherited from G4RPGInelastic
G4RPGInelastic (const G4String &modelName="RPGInelastic")
virtual ~G4RPGInelastic ()
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void ModelDescription (std::ostream &outFile) const
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
void Cascade (G4FastVector< G4ReactionProduct, GHADLISTSIZE > &vec, G4int &vecLen, const G4HadProjectile *originalIncident, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4bool &incidentHasChanged, G4bool &targetHasChanged, G4bool &quasiElastic)
Additional Inherited Members
Protected Types inherited from G4RPGInelastic
enum {
pi0, pip, pim, kp,
km, k0, k0b, pro,
neu, lam, sp, s0,
sm, xi0, xim, om,
ap, an
}
Protected Member Functions inherited from G4RPGInelastic
G4double Pmltpc (G4int np, G4int nm, G4int nz, G4int n, G4double b, G4double c)
G4int Factorial (G4int n)
G4bool MarkLeadingStrangeParticle (const G4ReactionProduct &currentParticle, const G4ReactionProduct &targetParticle, G4ReactionProduct &leadParticle)
void SetUpPions (const G4int np, const G4int nm, const G4int nz, G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen)
void GetNormalizationConstant (const G4double availableEnergy, G4double &n, G4double &anpn)
void CalculateMomenta (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, const G4HadProjectile *originalIncident, const G4DynamicParticle *originalTarget, G4ReactionProduct &modifiedOriginal, G4Nucleus &targetNucleus, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4bool &incidentHasChanged, G4bool &targetHasChanged, G4bool quasiElastic)
void SetUpChange (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4bool &incidentHasChanged)
std::pair< G4int, G4double > interpolateEnergy (G4double ke) const
G4int sampleFlat (std::vector< G4double > sigma) const
void CheckQnums (G4FastVector< G4ReactionProduct, 256 > &vec, G4int &vecLen, G4ReactionProduct &currentParticle, G4ReactionProduct &targetParticle, G4double Q, G4double B, G4double S)
Protected Attributes inherited from G4RPGInelastic
G4RPGFragmentation fragmentation
G4RPGTwoCluster twoCluster
G4RPGPionSuppression pionSuppression
G4RPGStrangeProduction strangeProduction
G4RPGTwoBody twoBody
G4ParticleDefinition * particleDef [18]
Detailed Description
Definition at line 42 of file G4RPGKPlusInelastic.hh.
View newest version in sPHENIX GitHub at line 42 of file G4RPGKPlusInelastic.hh
Constructor & Destructor Documentation
G4RPGKPlusInelastic::G4RPGKPlusInelastic () inline
Definition at line 46 of file G4RPGKPlusInelastic.hh.
View newest version in sPHENIX GitHub at line 46 of file G4RPGKPlusInelastic.hh
References CLHEP::GeV, G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
G4RPGKPlusInelastic::~G4RPGKPlusInelastic () inline
Definition at line 52 of file G4RPGKPlusInelastic.hh.
View newest version in sPHENIX GitHub at line 52 of file G4RPGKPlusInelastic.hh
Member Function Documentation
G4HadFinalState * G4RPGKPlusInelastic::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 36 of file G4RPGKPlusInelastic.cc.
View newest version in sPHENIX GitHub at line 36 of file G4RPGKPlusInelastic.cc
References kdfinder::abs(), G4RPGInelastic::CalculateMomenta(), Cascade(), G4Nucleus::Cinema(), G4Nucleus::EvaporationEffects(), G4cout, G4endl, G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4DynamicParticle::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4HadProjectile::GetMaterial(), G4Material::GetName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4FastVector< Type, N >::Initialize(), isAlive, MeV, momentum, G4InuclParticleNames::pp, G4Nucleus::ReturnTargetParticle(), G4HadFinalState::SetEnergyChange(), G4ReactionProduct::SetMomentum(), G4HadFinalState::SetMomentumChange(), G4ReactionProduct::SetSide(), G4HadFinalState::SetStatusChange(), G4RPGInelastic::SetUpChange(), G4HadronicInteraction::theParticleChange, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and G4HadronicInteraction::verboseLevel.
void G4RPGKPlusInelastic::Cascade (G4FastVector< G4ReactionProduct, GHADLISTSIZE > & vec, G4int & vecLen, const G4HadProjectile * originalIncident, G4ReactionProduct & currentParticle, G4ReactionProduct & targetParticle, G4bool & incidentHasChanged, G4bool & targetHasChanged, G4bool & quasiElastic) private
Definition at line 131 of file G4RPGKPlusInelastic.cc.
View newest version in sPHENIX GitHub at line 131 of file G4RPGKPlusInelastic.cc
References b, c, e, G4Exp(), G4ThreadLocal, G4UniformRand, G4HadProjectile::GetDefinition(), G4ReactionProduct::GetDefinition(), G4ReactionProduct::GetMass(), G4RPGInelastic::GetNormalizationConstant(), G4ParticleDefinition::GetPDGMass(), G4HadProjectile::GetTotalEnergy(), GeV, G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), max, min, n, G4Neutron::Neutron(), pi, G4PionPlus::PionPlus(), G4RPGInelastic::Pmltpc(), G4Proton::Proton(), ran(), G4ReactionProduct::SetDefinitionAndUpdateE(), G4RPGInelastic::SetUpPions(), sqr(), test(), G4InuclParticleNames::wm, and wp.
Referenced by ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/include/G4RPGKPlusInelastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/rpg/src/G4RPGKPlusInelastic.cc