ECCE @ EIC Software: PHG4GDMLWriteParamvol Class Reference
PHG4GDMLWriteParamvol Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteParamvol.hh>
Public Member Functions
virtual void ParamvolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const)
virtual void ParamvolAlgorithmWrite (xercesc::DOMElement *paramvolElement, const G4VPhysicalVolume *const paramvol)
Public Member Functions inherited from PHG4GDMLWriteSetup
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)
Public Member Functions inherited from PHG4GDMLWriteSolids
virtual void AddSolid (const G4VSolid *const)
virtual void SolidsWrite (xercesc::DOMElement *)
Public Member Functions inherited from PHG4GDMLWriteMaterials
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from PHG4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from PHG4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (PHG4GDMLAuxStructType myaux)
virtual void StructureWrite (xercesc::DOMElement *)=0
virtual G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const, const G4int)=0
virtual void SurfacesWrite ()=0
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
PHG4GDMLWriteParamvol ()
virtual ~PHG4GDMLWriteParamvol ()
void Box_dimensionsWrite (xercesc::DOMElement *, const G4Box *const)
void Trd_dimensionsWrite (xercesc::DOMElement *, const G4Trd *const)
void Trap_dimensionsWrite (xercesc::DOMElement *, const G4Trap *const)
void Tube_dimensionsWrite (xercesc::DOMElement *, const G4Tubs *const)
void Cone_dimensionsWrite (xercesc::DOMElement *, const G4Cons *const)
void Sphere_dimensionsWrite (xercesc::DOMElement *, const G4Sphere *const)
void Orb_dimensionsWrite (xercesc::DOMElement *, const G4Orb *const)
void Torus_dimensionsWrite (xercesc::DOMElement *, const G4Torus *const)
void Ellipsoid_dimensionsWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void Para_dimensionsWrite (xercesc::DOMElement *, const G4Para *const)
void Hype_dimensionsWrite (xercesc::DOMElement *, const G4Hype *const)
void Polycone_dimensionsWrite (xercesc::DOMElement *, const G4Polycone *const)
void Polyhedra_dimensionsWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void ParametersWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const, const G4int &)
Protected Member Functions inherited from PHG4GDMLWriteSetup
PHG4GDMLWriteSetup ()
virtual ~PHG4GDMLWriteSetup ()
Protected Member Functions inherited from PHG4GDMLWriteSolids
PHG4GDMLWriteSolids ()
virtual ~PHG4GDMLWriteSolids ()
void MultiUnionWrite (xercesc::DOMElement *solElement, const G4MultiUnion *const)
void BooleanWrite (xercesc::DOMElement *, const G4BooleanSolid *const)
void BoxWrite (xercesc::DOMElement *, const G4Box *const)
void ConeWrite (xercesc::DOMElement *, const G4Cons *const)
void ElconeWrite (xercesc::DOMElement *, const G4EllipticalCone *const)
void EllipsoidWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void EltubeWrite (xercesc::DOMElement *, const G4EllipticalTube *const)
void XtruWrite (xercesc::DOMElement *, const G4ExtrudedSolid *const)
void HypeWrite (xercesc::DOMElement *, const G4Hype *const)
void OrbWrite (xercesc::DOMElement *, const G4Orb *const)
void ParaWrite (xercesc::DOMElement *, const G4Para *const)
void ParaboloidWrite (xercesc::DOMElement *, const G4Paraboloid *const)
void PolyconeWrite (xercesc::DOMElement *, const G4Polycone *const)
void GenericPolyconeWrite (xercesc::DOMElement *, const G4GenericPolycone *const)
void PolyhedraWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void SphereWrite (xercesc::DOMElement *, const G4Sphere *const)
void TessellatedWrite (xercesc::DOMElement *, const G4TessellatedSolid *const)
void TetWrite (xercesc::DOMElement *, const G4Tet *const)
void TorusWrite (xercesc::DOMElement *, const G4Torus *const)
void GenTrapWrite (xercesc::DOMElement *, const G4GenericTrap *const)
void TrapWrite (xercesc::DOMElement *, const G4Trap *const)
void TrdWrite (xercesc::DOMElement *, const G4Trd *const)
void TubeWrite (xercesc::DOMElement *, const G4Tubs *const)
void CutTubeWrite (xercesc::DOMElement *, const G4CutTubs *const)
void TwistedboxWrite (xercesc::DOMElement *, const G4TwistedBox *const)
void TwistedtrapWrite (xercesc::DOMElement *, const G4TwistedTrap *const)
void TwistedtrdWrite (xercesc::DOMElement *, const G4TwistedTrd *const)
void TwistedtubsWrite (xercesc::DOMElement *, const G4TwistedTubs *const)
void ZplaneWrite (xercesc::DOMElement *, const G4double &, const G4double &, const G4double &)
void RZPointWrite (xercesc::DOMElement *, const G4double &, const G4double &)
void OpticalSurfaceWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
Protected Member Functions inherited from PHG4GDMLWriteMaterials
PHG4GDMLWriteMaterials ()
virtual ~PHG4GDMLWriteMaterials ()
void AtomWrite (xercesc::DOMElement *, const G4double &)
void DWrite (xercesc::DOMElement *, const G4double &)
void PWrite (xercesc::DOMElement *, const G4double &)
void TWrite (xercesc::DOMElement *, const G4double &)
void MEEWrite (xercesc::DOMElement *, const G4double &)
void IsotopeWrite (const G4Isotope *const)
void ElementWrite (const G4Element *const)
void MaterialWrite (const G4Material *const)
void PropertyWrite (xercesc::DOMElement *, const G4Material *const)
void PropertyVectorWrite (const G4String &, const G4PhysicsOrderedFreeVector *const)
Protected Member Functions inherited from PHG4GDMLWriteDefine
PHG4GDMLWriteDefine ()
virtual ~PHG4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from PHG4GDMLWrite
PHG4GDMLWrite ()
virtual ~PHG4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (PHG4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Additional Inherited Members
Static Public Member Functions inherited from PHG4GDMLWrite
static void SetAddPointerToName (G4bool)
Protected Attributes inherited from PHG4GDMLWriteSolids
std::vector< const G4VSolid * > solidList
xercesc::DOMElement * solidsElement
Static Protected Attributes inherited from PHG4GDMLWriteSolids
static const G4int maxTransforms = 8
Detailed Description
Definition at line 60 of file PHG4GDMLWriteParamvol.hh.
View newest version in sPHENIX GitHub at line 60 of file PHG4GDMLWriteParamvol.hh
Constructor & Destructor Documentation
PHG4GDMLWriteParamvol::PHG4GDMLWriteParamvol () protected
Definition at line 58 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 58 of file PHG4GDMLWriteParamvol.cc
PHG4GDMLWriteParamvol::~PHG4GDMLWriteParamvol () protected virtual
Definition at line 63 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 63 of file PHG4GDMLWriteParamvol.cc
Member Function Documentation
void PHG4GDMLWriteParamvol::Box_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Box * const box) protected
Definition at line 68 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 68 of file PHG4GDMLWriteParamvol.cc
References G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), G4Box::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Cone_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Cons * const cone) protected
Definition at line 168 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 168 of file PHG4GDMLWriteParamvol.cc
References degree, G4Cons::GetDeltaPhiAngle(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4Cons::GetStartPhiAngle(), G4Cons::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Ellipsoid_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Ellipsoid * const ellipsoid) protected
Definition at line 251 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 251 of file PHG4GDMLWriteParamvol.cc
References G4Ellipsoid::GetSemiAxisMax(), G4Ellipsoid::GetZBottomCut(), G4Ellipsoid::GetZTopCut(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Hype_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Hype * const hype) protected
Definition at line 303 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 303 of file PHG4GDMLWriteParamvol.cc
References degree, G4Hype::GetInnerRadius(), G4Hype::GetInnerStereo(), G4Hype::GetOuterRadius(), G4Hype::GetOuterStereo(), G4Hype::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Orb_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Orb * const orb) protected
Definition at line 217 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 217 of file PHG4GDMLWriteParamvol.cc
References G4Orb::GetRadius(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Para_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Para * const para) protected
Definition at line 272 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 272 of file PHG4GDMLWriteParamvol.cc
References alpha, degree, G4Para::GetSymAxis(), G4Para::GetTanAlpha(), G4Para::GetXHalfLength(), G4Para::GetYHalfLength(), G4Para::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), phi, theta(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::ParametersWrite (xercesc::DOMElement * paramvolElement, const G4VPhysicalVolume * const paramvol, const G4int & index) protected
Definition at line 385 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 385 of file PHG4GDMLWriteParamvol.cc
References Box_dimensionsWrite(), G4VPVParameterisation::ComputeDimensions(), G4VPVParameterisation::ComputeTransformation(), Cone_dimensionsWrite(), DBL_EPSILON, Ellipsoid_dimensionsWrite(), FatalException, G4Exception(), PHG4GDMLWrite::GenerateName(), PHG4GDMLWriteDefine::GetAngles(), G4VPhysicalVolume::GetLogicalVolume(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), G4VPhysicalVolume::GetObjectRotationValue(), G4VPhysicalVolume::GetObjectTranslation(), G4VPhysicalVolume::GetParameterisation(), G4LogicalVolume::GetSolid(), Hype_dimensionsWrite(), PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), Orb_dimensionsWrite(), Para_dimensionsWrite(), Polycone_dimensionsWrite(), Polyhedra_dimensionsWrite(), PHG4GDMLWriteDefine::PositionWrite(), PHG4GDMLWriteDefine::RotationWrite(), Sphere_dimensionsWrite(), Torus_dimensionsWrite(), Trap_dimensionsWrite(), Trd_dimensionsWrite(), and Tube_dimensionsWrite().
Referenced by ParamvolAlgorithmWrite().
void PHG4GDMLWriteParamvol::ParamvolAlgorithmWrite (xercesc::DOMElement * paramvolElement, const G4VPhysicalVolume *const paramvol) virtual
Definition at line 521 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 521 of file PHG4GDMLWriteParamvol.cc
References PHG4GDMLWrite::GenerateName(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMultiplicity(), G4LogicalVolume::GetName(), and ParametersWrite().
Referenced by ParamvolWrite().
void PHG4GDMLWriteParamvol::ParamvolWrite (xercesc::DOMElement * volumeElement, const G4VPhysicalVolume * const paramvol) virtual
Definition at line 500 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 500 of file PHG4GDMLWriteParamvol.cc
References PHG4GDMLWrite::GenerateName(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMultiplicity(), G4LogicalVolume::GetName(), PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), and ParamvolAlgorithmWrite().
Referenced by PHG4GDMLWriteStructure::TraverseVolumeTree().
void PHG4GDMLWriteParamvol::Polycone_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Polycone * const pcone) protected
Definition at line 325 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 325 of file PHG4GDMLWriteParamvol.cc
References degree, G4Polycone::GetOriginalParameters(), PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), G4PolyconeHistorical::Num_z_planes, G4PolyconeHistorical::Opening_angle, G4PolyconeHistorical::Rmax, G4PolyconeHistorical::Rmin, G4PolyconeHistorical::Start_angle, G4PolyconeHistorical::Z_values, and PHG4GDMLWriteSolids::ZplaneWrite().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Polyhedra_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Polyhedra * const polyhedra) protected
Definition at line 354 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 354 of file PHG4GDMLWriteParamvol.cc
References degree, G4Polyhedra::GetOriginalParameters(), PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), G4PolyhedraHistorical::Num_z_planes, G4PolyhedraHistorical::numSide, G4PolyhedraHistorical::Opening_angle, G4PolyhedraHistorical::Rmax, G4PolyhedraHistorical::Rmin, G4PolyhedraHistorical::Start_angle, G4PolyhedraHistorical::Z_values, and PHG4GDMLWriteSolids::ZplaneWrite().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Sphere_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Sphere * const sphere) protected
Definition at line 194 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 194 of file PHG4GDMLWriteParamvol.cc
References degree, G4Sphere::GetDeltaPhiAngle(), G4Sphere::GetDeltaThetaAngle(), G4Sphere::GetInnerRadius(), G4Sphere::GetOuterRadius(), G4Sphere::GetStartPhiAngle(), G4Sphere::GetStartThetaAngle(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Torus_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Torus * const torus) protected
Definition at line 228 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 228 of file PHG4GDMLWriteParamvol.cc
References degree, G4Torus::GetDPhi(), G4Torus::GetRmax(), G4Torus::GetRmin(), G4Torus::GetRtor(), G4Torus::GetSPhi(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Trap_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Trap * const trap) protected
Definition at line 104 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 104 of file PHG4GDMLWriteParamvol.cc
References degree, G4Trap::GetSymAxis(), G4Trap::GetTanAlpha1(), G4Trap::GetTanAlpha2(), G4Trap::GetXHalfLength1(), G4Trap::GetXHalfLength2(), G4Trap::GetXHalfLength3(), G4Trap::GetXHalfLength4(), G4Trap::GetYHalfLength1(), G4Trap::GetYHalfLength2(), G4Trap::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), phi, theta(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Trd_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Trd * const trd) protected
Definition at line 84 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 84 of file PHG4GDMLWriteParamvol.cc
References G4Trd::GetXHalfLength1(), G4Trd::GetXHalfLength2(), G4Trd::GetYHalfLength1(), G4Trd::GetYHalfLength2(), G4Trd::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
void PHG4GDMLWriteParamvol::Tube_dimensionsWrite (xercesc::DOMElement * parametersElement, const G4Tubs * const tube) protected
Definition at line 145 of file PHG4GDMLWriteParamvol.cc.
View newest version in sPHENIX GitHub at line 145 of file PHG4GDMLWriteParamvol.cc
References degree, G4Tubs::GetDeltaPhiAngle(), G4Tubs::GetInnerRadius(), G4Tubs::GetOuterRadius(), G4Tubs::GetStartPhiAngle(), G4Tubs::GetZHalfLength(), mm, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ParametersWrite().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteParamvol.hh
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteParamvol.cc