ECCE @ EIC Software: G4ParticleHPArbitaryTab Class Reference
G4ParticleHPArbitaryTab Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPArbitaryTab.hh>
Public Member Functions
G4ParticleHPArbitaryTab ()
~G4ParticleHPArbitaryTab ()
void Init (std::istream &theData)
G4double GetFractionalProbability (G4double anEnergy)
G4double Sample (G4double anEnergy)
Public Member Functions inherited from G4VParticleHPEDis
G4VParticleHPEDis ()
virtual ~G4VParticleHPEDis ()
Private Attributes
G4ParticleHPVector theFractionalProb
G4int nDistFunc
G4InterpolationManager theManager
G4ParticleHPVector * theDistFunc
G4ParticleHPVector theBuffer
G4double theLowThreshold [1000]
G4double theHighThreshold [1000]
Detailed Description
Definition at line 45 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPArbitaryTab.hh
Constructor & Destructor Documentation
G4ParticleHPArbitaryTab::G4ParticleHPArbitaryTab () inline
Definition at line 48 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPArbitaryTab.hh
References nDistFunc, and theDistFunc.
G4ParticleHPArbitaryTab::~G4ParticleHPArbitaryTab () inline
Definition at line 53 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPArbitaryTab.hh
References theDistFunc.
Member Function Documentation
G4double G4ParticleHPArbitaryTab::GetFractionalProbability (G4double anEnergy) inline virtual
Implements G4VParticleHPEDis.
Definition at line 101 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPArbitaryTab.hh
References G4ParticleHPVector::GetY(), and theFractionalProb.
void G4ParticleHPArbitaryTab::Init (std::istream & theData) inline virtual
Implements G4VParticleHPEDis.
Definition at line 58 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPArbitaryTab.hh
References e, CLHEP::eV, G4ParticleHPVector::GetEnergy(), G4ParticleHPVector::GetVectorLength(), G4InterpolationManager::Init(), G4ParticleHPVector::Init(), G4ParticleHPVector::IntegrateAndNormalise(), nDistFunc, G4ParticleHPVector::SetLabel(), theDistFunc, theFractionalProb, theHighThreshold, theLowThreshold, and theManager.
G4double G4ParticleHPArbitaryTab::Sample (G4double anEnergy) virtual
Implements G4VParticleHPEDis.
Definition at line 35 of file G4ParticleHPArbitaryTab.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleHPArbitaryTab.cc
References G4cerr, G4endl, G4UniformRand, G4ParticleHPVector::GetLabel(), nDistFunc, G4ParticleHPVector::Sample(), theDistFunc, theHighThreshold, and theLowThreshold.
Member Data Documentation
G4int G4ParticleHPArbitaryTab::nDistFunc private
Definition at line 111 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPArbitaryTab.hh
Referenced by G4ParticleHPArbitaryTab(), Init(), and Sample().
G4ParticleHPVector G4ParticleHPArbitaryTab::theBuffer private
Definition at line 114 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleHPArbitaryTab.hh
G4ParticleHPVector* G4ParticleHPArbitaryTab::theDistFunc private
Definition at line 113 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleHPArbitaryTab.hh
Referenced by G4ParticleHPArbitaryTab(), Init(), Sample(), and ~G4ParticleHPArbitaryTab().
G4ParticleHPVector G4ParticleHPArbitaryTab::theFractionalProb private
Definition at line 110 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPArbitaryTab.hh
Referenced by GetFractionalProbability(), and Init().
G4double G4ParticleHPArbitaryTab::theHighThreshold[1000] private
Definition at line 118 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ParticleHPArbitaryTab.hh
Referenced by Init(), and Sample().
G4double G4ParticleHPArbitaryTab::theLowThreshold[1000] private
Definition at line 117 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ParticleHPArbitaryTab.hh
Referenced by Init(), and Sample().
G4InterpolationManager G4ParticleHPArbitaryTab::theManager private
Definition at line 112 of file G4ParticleHPArbitaryTab.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPArbitaryTab.hh
Referenced by Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPArbitaryTab.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPArbitaryTab.cc