ECCE @ EIC Software: F02SteppingVerbose Class Reference
F02SteppingVerbose Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02SteppingVerbose.hh>
Public Member Functions
F02SteppingVerbose ()
virtual ~F02SteppingVerbose ()
virtual void StepInfo ()
virtual void TrackingStarted ()
Public Member Functions inherited from G4SteppingVerbose
G4SteppingVerbose ()
~G4SteppingVerbose ()
void NewStep ()
void AtRestDoItInvoked ()
void AlongStepDoItAllDone ()
void PostStepDoItAllDone ()
void AlongStepDoItOneByOne ()
void PostStepDoItOneByOne ()
void StepInfo ()
void TrackingStarted ()
void DPSLStarted ()
void DPSLUserLimit ()
void DPSLPostStep ()
void DPSLAlongStep ()
void VerboseTrack ()
void VerboseParticleChange ()
void ShowStep () const
Public Member Functions inherited from G4VSteppingVerbose
virtual ~G4VSteppingVerbose ()
void CopyState ()
void SetManager (G4SteppingManager *const)
Additional Inherited Members
Static Public Member Functions inherited from G4VSteppingVerbose
static void SetInstance (G4VSteppingVerbose *Instance)
static G4VSteppingVerbose * GetInstance ()
static G4int GetSilent ()
static void SetSilent (G4int fSilent)
static G4int GetSilentStepInfo ()
static void SetSilentStepInfo (G4int fSilent)
Protected Types inherited from G4VSteppingVerbose
typedef std::vector< G4int > G4SelectedAtRestDoItVector
typedef std::vector< G4int > G4SelectedAlongStepDoItVector
typedef std::vector< G4int > G4SelectedPostStepDoItVector
Protected Member Functions inherited from G4VSteppingVerbose
G4VSteppingVerbose ()
Protected Attributes inherited from G4VSteppingVerbose
G4SteppingManager * fManager
G4UserSteppingAction * fUserSteppingAction
G4double PhysicalStep
G4double GeometricalStep
G4double CorrectedStep
G4bool PreStepPointIsGeom
G4bool FirstStep
G4StepStatus fStepStatus
G4double TempInitVelocity
G4double TempVelocity
G4double Mass
G4double sumEnergyChange
G4VParticleChange * fParticleChange
G4Track * fTrack
G4TrackVector * fSecondary
G4Step * fStep
G4StepPoint * fPreStepPoint
G4StepPoint * fPostStepPoint
G4VPhysicalVolume * fCurrentVolume
G4VSensitiveDetector * fSensitive
G4VProcess * fCurrentProcess
G4ProcessVector * fAtRestDoItVector
G4ProcessVector * fAlongStepDoItVector
G4ProcessVector * fPostStepDoItVector
G4ProcessVector * fAtRestGetPhysIntVector
G4ProcessVector * fAlongStepGetPhysIntVector
G4ProcessVector * fPostStepGetPhysIntVector
size_t MAXofAtRestLoops
size_t MAXofAlongStepLoops
size_t MAXofPostStepLoops
G4double currentMinimumStep
G4double numberOfInteractionLengthLeft
size_t fAtRestDoItProcTriggered
size_t fAlongStepDoItProcTriggered
size_t fPostStepDoItProcTriggered
G4int fN2ndariesAtRestDoIt
G4int fN2ndariesAlongStepDoIt
G4int fN2ndariesPostStepDoIt
G4Navigator * fNavigator
G4int verboseLevel
G4SelectedAtRestDoItVector * fSelectedAtRestDoItVector
G4SelectedAlongStepDoItVector * fSelectedAlongStepDoItVector
G4SelectedPostStepDoItVector * fSelectedPostStepDoItVector
G4double fPreviousStepSize
G4TouchableHandle fTouchableHandle
G4SteppingControl StepControlFlag
G4double physIntLength
G4ForceCondition fCondition
G4GPILSelection fGPILSelection
Static Protected Attributes inherited from G4VSteppingVerbose
static G4ThreadLocal
G4VSteppingVerbose * fInstance = 0
static G4ThreadLocal G4int Silent = 0
static G4ThreadLocal G4int SilentStepInfo = 0
Detailed Description
Definition at line 58 of file F02SteppingVerbose.hh.
View newest version in sPHENIX GitHub at line 58 of file F02SteppingVerbose.hh
Constructor & Destructor Documentation
F02SteppingVerbose::F02SteppingVerbose ()
Definition at line 42 of file F02SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 42 of file F02SteppingVerbose.cc
F02SteppingVerbose::~F02SteppingVerbose () virtual
Definition at line 48 of file F02SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 48 of file F02SteppingVerbose.cc
Member Function Documentation
void F02SteppingVerbose::StepInfo () virtual
Implements G4VSteppingVerbose.
Definition at line 53 of file F02SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 53 of file F02SteppingVerbose.cc
References G4VSteppingVerbose::CopyState(), G4VSteppingVerbose::fN2ndariesAlongStepDoIt, G4VSteppingVerbose::fN2ndariesAtRestDoIt, G4VSteppingVerbose::fN2ndariesPostStepDoIt, G4VSteppingVerbose::fStep, G4VSteppingVerbose::fTrack, G4BestUnit, G4cout, G4endl, G4Track::GetCurrentStepNumber(), G4Track::GetKineticEnergy(), G4VPhysicalVolume::GetName(), G4Track::GetNextVolume(), G4Track::GetPosition(), G4Step::GetPostStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4VProcess::GetProcessName(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), G4Track::GetTrackLength(), CLHEP::prec, G4VSteppingVerbose::verboseLevel, G4SteppingVerbose::VerboseTrack(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void F02SteppingVerbose::TrackingStarted () virtual
Implements G4VSteppingVerbose.
Definition at line 126 of file F02SteppingVerbose.cc.
View newest version in sPHENIX GitHub at line 126 of file F02SteppingVerbose.cc
References G4VSteppingVerbose::CopyState(), G4VSteppingVerbose::fStep, G4VSteppingVerbose::fTrack, G4BestUnit, G4cout, G4endl, G4Track::GetCurrentStepNumber(), G4Track::GetKineticEnergy(), G4VPhysicalVolume::GetName(), G4Track::GetNextVolume(), G4Track::GetPosition(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), G4Track::GetTrackLength(), CLHEP::prec, G4VSteppingVerbose::verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02SteppingVerbose.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field02/src/F02SteppingVerbose.cc