ECCE @ EIC Software: G4SeltzerBergerModel Class Reference
G4SeltzerBergerModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4SeltzerBergerModel.hh>
Public Member Functions
G4SeltzerBergerModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="eBremSB")
~G4SeltzerBergerModel () override
void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
void InitialiseForElement (const G4ParticleDefinition *, G4int Z) override
void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double cutEnergy, G4double maxEnergy) override
void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double) override
void SetBicubicInterpolationFlag (G4bool val)
Public Member Functions inherited from G4eBremsstrahlungRelModel
G4eBremsstrahlungRelModel (const G4ParticleDefinition *p=0, const G4String &nam="eBremLPM")
virtual ~G4eBremsstrahlungRelModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double ekin, G4double cutEnergy) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double ekin, G4double zet, G4double, G4double cutEnergy, G4double maxEnergy=DBL_MAX) override
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cutEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
G4double ComputeDXSectionPerAtom (G4double gammaEnergy) override
Protected Member Functions inherited from G4eBremsstrahlungRelModel
void SetParticle (const G4ParticleDefinition *p)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
void ReadData (G4int Z)
const G4String & FindDirectoryPath ()
G4double SampleEnergyTransfer (const G4double kineticEnergy, const G4double logKineticEnergy, const G4double cut, const G4double emax)
G4SeltzerBergerModel & operator= (const G4SeltzerBergerModel &right)
G4SeltzerBergerModel (const G4SeltzerBergerModel &)
Private Attributes
G4bool fIsUseBicubicInterpolation
G4bool fIsUseSamplingTables
G4int fNumWarnings
size_t fIndx
size_t fIndy
Static Private Attributes
static constexpr G4int gMaxZet = 101
static constexpr G4double gExpNumLimit = -12.
static G4double gYLimitData [gMaxZet] = { 0.0 }
static G4Physics2DVector * gSBDCSData [gMaxZet] = { nullptr }
static G4SBBremTable * gSBSamplingTable = nullptr
static G4String gDataDirectory = ""
Additional Inherited Members
Protected Attributes inherited from G4eBremsstrahlungRelModel
G4bool fIsElectron
G4bool fIsScatOffElectron
G4bool fIsLPMActive
G4int fCurrentIZ
G4double fPrimaryParticleMass
G4double fPrimaryKinEnergy
G4double fPrimaryTotalEnergy
G4double fDensityFactor
G4double fDensityCorr
G4double fLowestKinEnergy
G4double fNucTerm
G4double fSumTerm
const G4ParticleDefinition * fPrimaryParticle
G4ParticleDefinition * fGammaParticle
G4ParticleChangeForLoss * fParticleChange
Static Protected Attributes inherited from G4eBremsstrahlungRelModel
static const G4double gBremFactor
static const G4double gMigdalConstant
Detailed Description
Definition at line 69 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 69 of file G4SeltzerBergerModel.hh
Constructor & Destructor Documentation
G4SeltzerBergerModel::G4SeltzerBergerModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "eBremSB") explicit
Definition at line 88 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 88 of file G4SeltzerBergerModel.cc
References G4eBremsstrahlungRelModel::fLowestKinEnergy, keV, G4VEmModel::SetAngularDistribution(), G4VEmModel::SetLowEnergyLimit(), and G4VEmModel::SetLPMFlag().
G4SeltzerBergerModel::~G4SeltzerBergerModel () override
Definition at line 99 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 99 of file G4SeltzerBergerModel.cc
References gMaxZet, gSBDCSData, gSBSamplingTable, and G4VEmModel::IsMaster().
G4SeltzerBergerModel::G4SeltzerBergerModel (const G4SeltzerBergerModel &) private
Member Function Documentation
G4double G4SeltzerBergerModel::ComputeDXSectionPerAtom (G4double gammaEnergy) override protected virtual
Reimplemented from G4eBremsstrahlungRelModel.
Definition at line 212 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 212 of file G4SeltzerBergerModel.cc
References e2, G4eBremsstrahlungRelModel::fCurrentIZ, fIndx, fIndy, G4eBremsstrahlungRelModel::fIsElectron, G4eBremsstrahlungRelModel::fPrimaryKinEnergy, G4eBremsstrahlungRelModel::fPrimaryTotalEnergy, G4Exp(), G4Log(), G4eBremsstrahlungRelModel::gBremFactor, gExpNumLimit, gMaxZet, gSBDCSData, InitialiseForElement(), kAlpha, kMC2, max, CLHEP::MeV, CLHEP::millibarn, min, pt2, G4Physics2DVector::Value(), x, and y.
const G4String & G4SeltzerBergerModel::FindDirectoryPath () private
Definition at line 159 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 159 of file G4SeltzerBergerModel.cc
References FatalException, G4Exception(), and gDataDirectory.
Referenced by ReadData().
void G4SeltzerBergerModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) override virtual
Reimplemented from G4eBremsstrahlungRelModel.
Definition at line 116 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 116 of file G4SeltzerBergerModel.cc
References G4EmParameters::EnableSamplingTable(), G4eBremsstrahlungRelModel::fIsScatOffElectron, fIsUseSamplingTables, G4eBremsstrahlungRelModel::fLowestKinEnergy, G4eBremsstrahlungRelModel::fParticleChange, G4VEmModel::GetParticleChangeForLoss(), G4ProductionCutsTable::GetProductionCutsTable(), G4VEmModel::GetTripletModel(), gMaxZet, gSBSamplingTable, G4VEmModel::HighEnergyLimit(), G4VEmModel::Initialise(), G4VEmModel::InitialiseElementSelectors(), InitialiseForElement(), G4SBBremTable::Initialize(), G4EmParameters::Instance(), G4VEmModel::IsMaster(), G4VEmModel::LowEnergyLimit(), mat, max, min, G4eBremsstrahlungRelModel::SetParticle(), and Z.
Referenced by G4ePolarizedBremsstrahlungModel::Initialise().
void G4SeltzerBergerModel::InitialiseForElement (const G4ParticleDefinition * , G4int Z) override virtual
Reimplemented from G4VEmModel.
Definition at line 403 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 403 of file G4SeltzerBergerModel.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, gSBDCSData, and ReadData().
Referenced by ComputeDXSectionPerAtom(), Initialise(), and SampleEnergyTransfer().
G4SeltzerBergerModel& G4SeltzerBergerModel::operator= (const G4SeltzerBergerModel & right) private
void G4SeltzerBergerModel::ReadData (G4int Z) private
Definition at line 178 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 178 of file G4SeltzerBergerModel.cc
References emaxlog, FatalException, fin, FindDirectoryPath(), fIndx, fIndy, fIsUseBicubicInterpolation, G4Exception(), G4Log(), gSBDCSData, gYLimitData, G4Physics2DVector::Retrieve(), G4Physics2DVector::SetBicubicInterpolation(), v, G4Physics2DVector::Value(), and Z.
Referenced by InitialiseForElement().
G4double G4SeltzerBergerModel::SampleEnergyTransfer (const G4double kineticEnergy, const G4double logKineticEnergy, const G4double cut, const G4double emax) private
Definition at line 326 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 326 of file G4SeltzerBergerModel.cc
References e1, e2, G4eBremsstrahlungRelModel::fCurrentIZ, G4eBremsstrahlungRelModel::fDensityCorr, fIndx, fIndy, G4eBremsstrahlungRelModel::fIsElectron, CLHEP::HepRandomEngine::flatArray(), fNumWarnings, G4eBremsstrahlungRelModel::fPrimaryParticle, G4Exception(), G4Exp(), G4Log(), G4ParticleDefinition::GetParticleName(), gExpNumLimit, gSBDCSData, gYLimitData, InitialiseForElement(), JustWarning, kAlpha, CLHEP::keV, kMC2, max, CLHEP::MeV, min, G4InuclParticleNames::nn, v, G4Physics2DVector::Value(), G4VEmModel::Value(), xmin, and y.
Referenced by SampleSecondaries().
void G4SeltzerBergerModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4eBremsstrahlungRelModel.
Definition at line 253 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 253 of file G4SeltzerBergerModel.cc
References dir, G4eBremsstrahlungRelModel::fCurrentIZ, G4eBremsstrahlungRelModel::fDensityCorr, G4eBremsstrahlungRelModel::fGammaParticle, G4eBremsstrahlungRelModel::fIsElectron, fIsUseSamplingTables, G4eBremsstrahlungRelModel::fParticleChange, G4eBremsstrahlungRelModel::fPrimaryParticle, G4eBremsstrahlungRelModel::fPrimaryTotalEnergy, fStopAndKill, G4VEmModel::GetAngularDistribution(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), gMaxZet, gSBSamplingTable, kMC2, max, min, G4VParticleChange::ProposeTrackStatus(), G4VEmAngularDistribution::SampleDirection(), G4SBBremTable::SampleEnergyTransfer(), SampleEnergyTransfer(), G4VEmModel::SecondaryThreshold(), G4VEmModel::SelectTargetAtom(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), and SetupForMaterial().
Referenced by G4ePolarizedBremsstrahlungModel::SampleSecondaries().
void G4SeltzerBergerModel::SetBicubicInterpolationFlag (G4bool val) inline
Definition at line 92 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 92 of file G4SeltzerBergerModel.hh
References fIsUseBicubicInterpolation.
void G4SeltzerBergerModel::SetupForMaterial (const G4ParticleDefinition * , const G4Material * mat, G4double kineticEnergy) override virtual
Reimplemented from G4eBremsstrahlungRelModel.
Definition at line 419 of file G4SeltzerBergerModel.cc.
View newest version in sPHENIX GitHub at line 419 of file G4SeltzerBergerModel.cc
References CLHEP::electron_mass_c2, G4eBremsstrahlungRelModel::fDensityCorr, G4eBremsstrahlungRelModel::fDensityFactor, G4eBremsstrahlungRelModel::fIsLPMActive, G4eBremsstrahlungRelModel::fPrimaryKinEnergy, G4eBremsstrahlungRelModel::fPrimaryTotalEnergy, G4Material::GetElectronDensity(), G4eBremsstrahlungRelModel::gMigdalConstant, and G4VEmModel::LPMFlag().
Referenced by SampleSecondaries().
Member Data Documentation
size_t G4SeltzerBergerModel::fIndx private
Definition at line 127 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 127 of file G4SeltzerBergerModel.hh
Referenced by ComputeDXSectionPerAtom(), ReadData(), and SampleEnergyTransfer().
size_t G4SeltzerBergerModel::fIndy private
Definition at line 128 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4SeltzerBergerModel.hh
Referenced by ComputeDXSectionPerAtom(), ReadData(), and SampleEnergyTransfer().
G4bool G4SeltzerBergerModel::fIsUseBicubicInterpolation private
Definition at line 122 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 122 of file G4SeltzerBergerModel.hh
Referenced by ReadData(), and SetBicubicInterpolationFlag().
G4bool G4SeltzerBergerModel::fIsUseSamplingTables private
Definition at line 123 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 123 of file G4SeltzerBergerModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4int G4SeltzerBergerModel::fNumWarnings private
Definition at line 125 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 125 of file G4SeltzerBergerModel.hh
Referenced by SampleEnergyTransfer().
G4String G4SeltzerBergerModel::gDataDirectory = "" static private
Definition at line 120 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4SeltzerBergerModel.hh
Referenced by FindDirectoryPath().
constexpr G4double G4SeltzerBergerModel::gExpNumLimit = -12. static private
Definition at line 116 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4SeltzerBergerModel.hh
Referenced by ComputeDXSectionPerAtom(), and SampleEnergyTransfer().
constexpr G4int G4SeltzerBergerModel::gMaxZet = 101 static private
Definition at line 115 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4SeltzerBergerModel.hh
Referenced by ComputeDXSectionPerAtom(), Initialise(), SampleSecondaries(), and ~G4SeltzerBergerModel().
G4Physics2DVector * G4SeltzerBergerModel::gSBDCSData = { nullptr } static private
Definition at line 118 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4SeltzerBergerModel.hh
Referenced by ComputeDXSectionPerAtom(), InitialiseForElement(), ReadData(), SampleEnergyTransfer(), and ~G4SeltzerBergerModel().
G4SBBremTable * G4SeltzerBergerModel::gSBSamplingTable = nullptr static private
Definition at line 119 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4SeltzerBergerModel.hh
Referenced by Initialise(), SampleSecondaries(), and ~G4SeltzerBergerModel().
G4double G4SeltzerBergerModel::gYLimitData = { 0.0 } static private
Definition at line 117 of file G4SeltzerBergerModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4SeltzerBergerModel.hh
Referenced by ReadData(), and SampleEnergyTransfer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4SeltzerBergerModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4SeltzerBergerModel.cc