ECCE @ EIC Software: G4VHadDecayAlgorithm Class Reference
G4VHadDecayAlgorithm Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4VHadDecayAlgorithm.hh>
Public Member Functions
G4VHadDecayAlgorithm (const G4String &algName, G4int verbose=0)
virtual ~G4VHadDecayAlgorithm ()
void Generate (G4double initialMass, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)
virtual void SetVerboseLevel (G4int verbose)
G4int GetVerboseLevel () const
const G4String & GetName () const
Protected Member Functions
virtual void GenerateTwoBody (G4double initialMass, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)=0
virtual void GenerateMultiBody (G4double initialMass, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)=0
virtual G4bool IsDecayAllowed (G4double initialMass, const std::vector< G4double > &masses) const
G4double TwoBodyMomentum (G4double M0, G4double M1, G4double M2) const
G4double UniformTheta () const
G4double UniformPhi () const
void PrintVector (const std::vector< G4double > &v, const G4String &name, std::ostream &os) const
Private Attributes
G4String name
G4int verboseLevel
Detailed Description
Definition at line 42 of file G4VHadDecayAlgorithm.hh.
View newest version in sPHENIX GitHub at line 42 of file G4VHadDecayAlgorithm.hh
Constructor & Destructor Documentation
G4VHadDecayAlgorithm::G4VHadDecayAlgorithm (const G4String & algName, G4int verbose = 0) inline
Definition at line 44 of file G4VHadDecayAlgorithm.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VHadDecayAlgorithm.hh
virtual G4VHadDecayAlgorithm::~G4VHadDecayAlgorithm () inline virtual
Definition at line 46 of file G4VHadDecayAlgorithm.hh.
View newest version in sPHENIX GitHub at line 46 of file G4VHadDecayAlgorithm.hh
Member Function Documentation
void G4VHadDecayAlgorithm::Generate (G4double initialMass, const std::vector< G4double > & masses, std::vector< G4LorentzVector > & finalState)
Definition at line 48 of file G4VHadDecayAlgorithm.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VHadDecayAlgorithm.cc
References G4cout, G4endl, GenerateMultiBody(), GenerateTwoBody(), GetName(), IsDecayAllowed(), and verboseLevel.
Referenced by G4HadDecayGenerator::Generate().
virtual void G4VHadDecayAlgorithm::GenerateMultiBody (G4double initialMass, const std::vector< G4double > & masses, std::vector< G4LorentzVector > & finalState) protected pure virtual
Implemented in G4CascadeFinalStateAlgorithm, G4HadPhaseSpaceKopylov, G4HadPhaseSpaceNBodyAsai, and G4HadPhaseSpaceGenbod.
Referenced by Generate().
virtual void G4VHadDecayAlgorithm::GenerateTwoBody (G4double initialMass, const std::vector< G4double > & masses, std::vector< G4LorentzVector > & finalState) protected pure virtual
Implemented in G4CascadeFinalStateAlgorithm, and G4VHadPhaseSpaceAlgorithm.
Referenced by Generate().
const G4String& G4VHadDecayAlgorithm::GetName (void) const inline
Definition at line 56 of file G4VHadDecayAlgorithm.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VHadDecayAlgorithm.hh
References name.
Referenced by G4HadPhaseSpaceGenbod::AcceptEvent(), G4HadPhaseSpaceGenbod::AccumulateFinalState(), G4CascadeFinalStateAlgorithm::ChooseGenerators(), G4HadPhaseSpaceGenbod::ComputeWeight(), G4HadPhaseSpaceGenbod::ComputeWeightScale(), G4CascadeFinalStateAlgorithm::Configure(), G4CascadeFinalStateAlgorithm::FillDirections(), G4CascadeFinalStateAlgorithm::FillDirManyBody(), G4CascadeFinalStateAlgorithm::FillDirThreeBody(), G4HadPhaseSpaceGenbod::FillEnergySteps(), G4CascadeFinalStateAlgorithm::FillMagnitudes(), G4HadPhaseSpaceGenbod::FillRandomBuffer(), G4CascadeFinalStateAlgorithm::FillUsingKopylov(), G4HadDecayGenerator::G4HadDecayGenerator(), Generate(), G4CascadeFinalStateAlgorithm::GenerateCosTheta(), G4HadPhaseSpaceGenbod::GenerateMomenta(), G4HadPhaseSpaceGenbod::GenerateMultiBody(), G4HadPhaseSpaceNBodyAsai::GenerateMultiBody(), G4HadPhaseSpaceKopylov::GenerateMultiBody(), G4CascadeFinalStateAlgorithm::GenerateMultiBody(), G4CascadeFinalStateAlgorithm::GenerateTwoBody(), G4HadDecayGenerator::GetAlgorithmName(), G4HadPhaseSpaceGenbod::Initialize(), IsDecayAllowed(), G4CascadeFinalStateAlgorithm::satisfyTriangle(), G4CascadeFinalStateAlgorithm::SaveKinematics(), and TwoBodyMomentum().
G4int G4VHadDecayAlgorithm::GetVerboseLevel () const inline
Definition at line 55 of file G4VHadDecayAlgorithm.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VHadDecayAlgorithm.hh
References verboseLevel.
Referenced by G4HadPhaseSpaceGenbod::AcceptEvent(), G4HadPhaseSpaceGenbod::AccumulateFinalState(), G4CascadeFinalStateAlgorithm::ChooseGenerators(), G4HadPhaseSpaceGenbod::ComputeWeight(), G4HadPhaseSpaceGenbod::ComputeWeightScale(), G4CascadeFinalStateAlgorithm::Configure(), G4CascadeFinalStateAlgorithm::FillDirections(), G4CascadeFinalStateAlgorithm::FillDirManyBody(), G4CascadeFinalStateAlgorithm::FillDirThreeBody(), G4HadPhaseSpaceGenbod::FillEnergySteps(), G4CascadeFinalStateAlgorithm::FillMagnitudes(), G4HadPhaseSpaceGenbod::FillRandomBuffer(), G4CascadeFinalStateAlgorithm::FillUsingKopylov(), G4CascadeFinalStateAlgorithm::GenerateCosTheta(), G4HadPhaseSpaceGenbod::GenerateMomenta(), G4HadPhaseSpaceGenbod::GenerateMultiBody(), G4HadPhaseSpaceKopylov::GenerateMultiBody(), G4HadPhaseSpaceNBodyAsai::GenerateMultiBody(), G4CascadeFinalStateAlgorithm::GenerateMultiBody(), G4VHadPhaseSpaceAlgorithm::GenerateTwoBody(), G4CascadeFinalStateAlgorithm::GenerateTwoBody(), G4HadPhaseSpaceGenbod::Initialize(), G4CascadeFinalStateAlgorithm::satisfyTriangle(), and G4CascadeFinalStateAlgorithm::SaveKinematics().
G4bool G4VHadDecayAlgorithm::IsDecayAllowed (G4double initialMass, const std::vector< G4double > & masses) const protected virtual
Definition at line 68 of file G4VHadDecayAlgorithm.cc.
View newest version in sPHENIX GitHub at line 68 of file G4VHadDecayAlgorithm.cc
References G4cout, G4endl, GetName(), PrintVector(), and verboseLevel.
Referenced by Generate().
void G4VHadDecayAlgorithm::PrintVector (const std::vector< G4double > & v, const G4String & name, std::ostream & os) const protected
Definition at line 122 of file G4VHadDecayAlgorithm.cc.
View newest version in sPHENIX GitHub at line 122 of file G4VHadDecayAlgorithm.cc
References field_utils::copy().
Referenced by G4HadPhaseSpaceGenbod::FillEnergySteps(), G4HadPhaseSpaceGenbod::FillRandomBuffer(), G4HadPhaseSpaceNBodyAsai::GenerateMultiBody(), G4HadPhaseSpaceGenbod::Initialize(), and IsDecayAllowed().
virtual void G4VHadDecayAlgorithm::SetVerboseLevel (G4int verbose) inline virtual
Reimplemented in G4CascadeFinalStateAlgorithm.
Definition at line 54 of file G4VHadDecayAlgorithm.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VHadDecayAlgorithm.hh
References verboseLevel.
Referenced by G4CascadeFinalStateAlgorithm::SetVerboseLevel(), and G4HadDecayGenerator::SetVerboseLevel().
G4double G4VHadDecayAlgorithm::TwoBodyMomentum (G4double M0, G4double M1, G4double M2) const protected
Definition at line 90 of file G4VHadDecayAlgorithm.cc.
View newest version in sPHENIX GitHub at line 90 of file G4VHadDecayAlgorithm.cc
References CLHEP::eV, G4cout, G4endl, GetName(), GeV, and MeV.
Referenced by G4HadPhaseSpaceGenbod::ComputeWeightScale(), G4HadPhaseSpaceGenbod::FillEnergySteps(), G4CascadeFinalStateAlgorithm::FillUsingKopylov(), G4HadPhaseSpaceKopylov::GenerateMultiBody(), G4HadPhaseSpaceNBodyAsai::GenerateMultiBody(), G4VHadPhaseSpaceAlgorithm::GenerateTwoBody(), and G4CascadeFinalStateAlgorithm::GenerateTwoBody().
G4double G4VHadDecayAlgorithm::UniformPhi () const protected
Definition at line 114 of file G4VHadDecayAlgorithm.cc.
View newest version in sPHENIX GitHub at line 114 of file G4VHadDecayAlgorithm.cc
References G4UniformRand, and twopi.
Referenced by G4CascadeFinalStateAlgorithm::FillUsingKopylov(), G4CascadeFinalStateAlgorithm::GenerateTwoBody(), and G4VHadPhaseSpaceAlgorithm::UniformVector().
G4double G4VHadDecayAlgorithm::UniformTheta () const protected
Definition at line 110 of file G4VHadDecayAlgorithm.cc.
View newest version in sPHENIX GitHub at line 110 of file G4VHadDecayAlgorithm.cc
References G4UniformRand.
Referenced by G4CascadeFinalStateAlgorithm::FillUsingKopylov(), and G4VHadPhaseSpaceAlgorithm::UniformVector().
Member Data Documentation
G4String G4VHadDecayAlgorithm::name private
Definition at line 85 of file G4VHadDecayAlgorithm.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VHadDecayAlgorithm.hh
Referenced by GetName().
G4int G4VHadDecayAlgorithm::verboseLevel private
Definition at line 86 of file G4VHadDecayAlgorithm.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VHadDecayAlgorithm.hh
Referenced by Generate(), GetVerboseLevel(), IsDecayAllowed(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4VHadDecayAlgorithm.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4VHadDecayAlgorithm.cc