ECCE @ EIC Software: G4PSMinKinEAtGeneration Class Reference
G4PSMinKinEAtGeneration Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSMinKinEAtGeneration.hh>
Public Member Functions
G4PSMinKinEAtGeneration (G4String name, G4int depth=0)
G4PSMinKinEAtGeneration (G4String name, const G4String &unit, G4int depth=0)
virtual ~G4PSMinKinEAtGeneration ()
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4THitsMap< G4double > * EvtMap
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 47 of file G4PSMinKinEAtGeneration.hh.
View newest version in sPHENIX GitHub at line 47 of file G4PSMinKinEAtGeneration.hh
Constructor & Destructor Documentation
G4PSMinKinEAtGeneration::G4PSMinKinEAtGeneration (G4String name, G4int depth = 0)
Definition at line 41 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 41 of file G4PSMinKinEAtGeneration.cc
References SetUnit().
G4PSMinKinEAtGeneration::G4PSMinKinEAtGeneration (G4String name, const G4String & unit, G4int depth = 0)
Definition at line 47 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 47 of file G4PSMinKinEAtGeneration.cc
References SetUnit().
G4PSMinKinEAtGeneration::~G4PSMinKinEAtGeneration () virtual
Definition at line 55 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 55 of file G4PSMinKinEAtGeneration.cc
Member Function Documentation
void G4PSMinKinEAtGeneration::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 108 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 108 of file G4PSMinKinEAtGeneration.cc
References G4VTHitsMap< T, Map_t >::clear(), and EvtMap.
void G4PSMinKinEAtGeneration::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 112 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 112 of file G4PSMinKinEAtGeneration.cc
void G4PSMinKinEAtGeneration::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 105 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 105 of file G4PSMinKinEAtGeneration.cc
void G4PSMinKinEAtGeneration::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 98 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 98 of file G4PSMinKinEAtGeneration.cc
References G4HCofThisEvent::AddHitsCollection(), G4VPrimitiveScorer::detector, EvtMap, G4VPrimitiveScorer::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), and HCID.
void G4PSMinKinEAtGeneration::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 115 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 115 of file G4PSMinKinEAtGeneration.cc
References G4VTHitsMap< T, Map_t >::entries(), EvtMap, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), G4VPrimitiveScorer::GetName(), G4VPrimitiveScorer::GetUnit(), and G4VPrimitiveScorer::GetUnitValue().
G4bool G4PSMinKinEAtGeneration::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 58 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PSMinKinEAtGeneration.cc
References EvtMap, FALSE, G4Track::GetCurrentStepNumber(), G4VPrimitiveScorer::GetIndex(), G4StepPoint::GetKineticEnergy(), G4Track::GetParentID(), G4Step::GetPreStepPoint(), G4Step::GetTrack(), G4VTHitsMap< T, Map_t >::set(), and TRUE.
void G4PSMinKinEAtGeneration::SetUnit (const G4String & unit) virtual
Definition at line 128 of file G4PSMinKinEAtGeneration.cc.
View newest version in sPHENIX GitHub at line 128 of file G4PSMinKinEAtGeneration.cc
References G4VPrimitiveScorer::CheckAndSetUnit().
Referenced by G4PSMinKinEAtGeneration(), G4PSMinKinEAtGeneration3D::G4PSMinKinEAtGeneration3D(), and G4ScoreQuantityMessenger::SetNewValue().
Member Data Documentation
G4THitsMap<G4double>* G4PSMinKinEAtGeneration::EvtMap private
Definition at line 74 of file G4PSMinKinEAtGeneration.hh.
View newest version in sPHENIX GitHub at line 74 of file G4PSMinKinEAtGeneration.hh
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
G4int G4PSMinKinEAtGeneration::HCID private
Definition at line 73 of file G4PSMinKinEAtGeneration.hh.
View newest version in sPHENIX GitHub at line 73 of file G4PSMinKinEAtGeneration.hh
Referenced by Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSMinKinEAtGeneration.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSMinKinEAtGeneration.cc