ECCE @ EIC Software: PhysListEmStandard Class Reference
PhysListEmStandard Class Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysListEmStandard.hh>
Public Member Functions
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
void ConstructParticle ()
void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
void ConstructParticle ()
void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
virtual ~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
PhysListEmStandard (const G4String &name="standard")
~PhysListEmStandard ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 39 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 39 of file PhysListEmStandard.hh
Constructor & Destructor Documentation
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
Definition at line 59 of file PhysListEmStandard.cc.
View newest version in sPHENIX GitHub at line 59 of file PhysListEmStandard.cc
PhysListEmStandard::~PhysListEmStandard ()
Definition at line 65 of file PhysListEmStandard.cc.
View newest version in sPHENIX GitHub at line 65 of file PhysListEmStandard.cc
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
virtual PhysListEmStandard::~PhysListEmStandard () virtual
PhysListEmStandard::PhysListEmStandard (const G4String & name = "standard")
PhysListEmStandard::~PhysListEmStandard ()
Member Function Documentation
void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 46 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 46 of file PhysListEmStandard.hh
void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 47 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 47 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 49 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 49 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 50 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 50 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 50 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 50 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 50 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 50 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 50 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 50 of file PhysListEmStandard.hh
virtual void PhysListEmStandard::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 50 of file PhysListEmStandard.hh.
View newest version in sPHENIX GitHub at line 50 of file PhysListEmStandard.hh
void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
void PhysListEmStandard::ConstructProcess (void) virtual
G4PhotoElectricEffect* phot = new G4PhotoElectricEffect(); phot->SetEmModel(new G4LivermorePhotoElectricModel(), 1); ph->RegisterProcess(phot, particle);
Implements G4VPhysicsConstructor.
Definition at line 70 of file PhysListEmStandard.cc.
View newest version in sPHENIX GitHub at line 70 of file PhysListEmStandard.cc
References G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::IsShortLived(), particle, G4ParticleTableIterator< K, V >::reset(), theParticleIterator, G4VPhysicsConstructor::theParticleTable, and G4ParticleTableIterator< K, V >::value().
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
virtual void PhysListEmStandard::ConstructProcess () virtual
Implements G4VPhysicsConstructor.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/include/PhysListEmStandard.hh
geant4/tree/geant4-10.6-release/environments/g4py/examples/demos/TestEm0/module/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm0/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/PhysListEmStandard.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/electronScattering/src/PhysListEmStandard.cc