ECCE @ EIC Software: G4ParameterisationParaZ Class Reference
G4ParameterisationParaZ Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPara.hh>
Public Member Functions
G4ParameterisationParaZ (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
~G4ParameterisationParaZ ()
G4double GetMaxParameter () const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Para &para, const G4int copyNo, const G4VPhysicalVolume *pv) const
Public Member Functions inherited from G4VParameterisationPara
G4VParameterisationPara (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid *msolid, DivisionType divType)
virtual ~G4VParameterisationPara ()
Public Member Functions inherited from G4VDivisionParameterisation
G4VDivisionParameterisation (EAxis axis, G4int nDiv, G4double width, G4double offset, DivisionType divType, G4VSolid *motherSolid=nullptr)
virtual ~G4VDivisionParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
const G4String & GetType () const
EAxis GetAxis () const
G4int GetNoDiv () const
G4double GetWidth () const
G4double GetOffset () const
G4VSolid * GetMotherSolid () const
void SetType (const G4String &type)
G4int VolumeFirstCopyNo () const
void SetHalfGap (G4double hg)
G4double GetHalfGap () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Additional Inherited Members
Protected Member Functions inherited from G4VDivisionParameterisation
void ChangeRotMatrix (G4VPhysicalVolume *physVol, G4double rotZ=0.0) const
G4int CalculateNDiv (G4double motherDim, G4double width, G4double offset) const
G4double CalculateWidth (G4double motherDim, G4int nDiv, G4double offset) const
virtual void CheckParametersValidity ()
void CheckOffset (G4double maxPar)
void CheckNDivAndWidth (G4double maxPar)
G4double OffsetZ () const
Protected Attributes inherited from G4VDivisionParameterisation
G4String ftype
EAxis faxis
G4int fnDiv = 0
G4double fwidth = 0.0
G4double foffset = 0.0
DivisionType fDivisionType
G4VSolid * fmotherSolid = nullptr
G4bool fReflectedSolid = false
G4bool fDeleteSolid = false
G4int theVoluFirstCopyNo = 1
G4double kCarTolerance
G4double fhgap = 0.0
Static Protected Attributes inherited from G4VDivisionParameterisation
static G4ThreadLocal
G4RotationMatrix * fRot = nullptr
static const G4int verbose = 5
Detailed Description
Definition at line 161 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 161 of file G4ParameterisationPara.hh
Constructor & Destructor Documentation
G4ParameterisationParaZ::G4ParameterisationParaZ (EAxis axis, G4int nCopies, G4double offset, G4double step, G4VSolid * msolid, DivisionType divType)
Definition at line 287 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 287 of file G4ParameterisationPara.cc
References G4VDivisionParameterisation::CalculateNDiv(), G4VDivisionParameterisation::CalculateWidth(), G4VDivisionParameterisation::CheckParametersValidity(), DivNDIV, DivWIDTH, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fnDiv, G4VDivisionParameterisation::foffset, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Para::GetZHalfLength(), offset, G4VDivisionParameterisation::SetType(), and G4VDivisionParameterisation::verbose.
G4ParameterisationParaZ::~G4ParameterisationParaZ ()
Definition at line 317 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 317 of file G4ParameterisationPara.cc
Member Function Documentation
void G4ParameterisationParaZ::ComputeDimensions (G4Para & para, const G4int copyNo, const G4VPhysicalVolume * pv) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 357 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 357 of file G4ParameterisationPara.cc
References G4VSolid::DumpInfo(), G4VDivisionParameterisation::fhgap, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Para::GetSymAxis(), G4Para::GetTanAlpha(), G4Para::GetXHalfLength(), G4Para::GetYHalfLength(), CLHEP::Hep3Vector::phi(), G4Para::SetAllParameters(), CLHEP::Hep3Vector::theta(), and G4VDivisionParameterisation::verbose.
void G4ParameterisationParaZ::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 180 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 180 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 182 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 182 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 184 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 186 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 186 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 188 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 188 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 190 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 190 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 192 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 192 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 194 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 194 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 196 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 196 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 198 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 198 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 200 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 200 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 202 of file G4ParameterisationPara.hh.
View newest version in sPHENIX GitHub at line 202 of file G4ParameterisationPara.hh
void G4ParameterisationParaZ::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VDivisionParameterisation.
Definition at line 331 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 331 of file G4ParameterisationPara.cc
References G4VDivisionParameterisation::faxis, G4VDivisionParameterisation::fmotherSolid, G4VDivisionParameterisation::fwidth, G4cout, G4endl, G4Para::GetSymAxis(), G4Para::GetZHalfLength(), G4VDivisionParameterisation::OffsetZ(), Acts::Test::origin(), G4VPhysicalVolume::SetTranslation(), G4VDivisionParameterisation::verbose, and CLHEP::Hep3Vector::z().
G4double G4ParameterisationParaZ::GetMaxParameter () const virtual
Implements G4VDivisionParameterisation.
Definition at line 322 of file G4ParameterisationPara.cc.
View newest version in sPHENIX GitHub at line 322 of file G4ParameterisationPara.cc
References G4VDivisionParameterisation::fmotherSolid, and G4Para::GetZHalfLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/divisions/include/G4ParameterisationPara.hh
geant4/tree/geant4-10.6-release/source/geometry/divisions/src/G4ParameterisationPara.cc