ECCE @ EIC Software: G4RDeIonisationParameters Class Reference
G4RDeIonisationParameters Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDeIonisationParameters.hh>
Public Member Functions
G4RDeIonisationParameters (G4int minZ=1, G4int maxZ=99)
~G4RDeIonisationParameters ()
G4double Parameter (G4int Z, G4int shellIndex, G4int parameterIndex, G4double e) const
G4double Excitation (G4int Z, G4double e) const
void PrintData () const
Private Member Functions
G4RDeIonisationParameters (const G4RDeIonisationParameters &)
G4RDeIonisationParameters & operator= (const G4RDeIonisationParameters &right)
void LoadData ()
Private Attributes
G4int zMin
G4int zMax
G4DataVector activeZ
std::map< G4int,
G4RDVEMDataSet *, std::less
< G4int > > param
std::map< G4int,
G4RDVEMDataSet *, std::less
< G4int > > excit
size_t length
Detailed Description
Definition at line 60 of file G4RDeIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 60 of file G4RDeIonisationParameters.hh
Constructor & Destructor Documentation
G4RDeIonisationParameters::G4RDeIonisationParameters (G4int minZ = 1, G4int maxZ = 99)
Definition at line 60 of file G4RDeIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 60 of file G4RDeIonisationParameters.cc
References LoadData().
G4RDeIonisationParameters::~G4RDeIonisationParameters ()
Definition at line 68 of file G4RDeIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 68 of file G4RDeIonisationParameters.cc
References activeZ, excit, param, and pos().
G4RDeIonisationParameters::G4RDeIonisationParameters (const G4RDeIonisationParameters &) private
Member Function Documentation
G4double G4RDeIonisationParameters::Excitation (G4int Z, G4double e) const
Definition at line 122 of file G4RDeIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 122 of file G4RDeIonisationParameters.cc
References e, excit, G4RDVEMDataSet::FindValue(), G4cout, G4endl, G4RDVEMDataSet::GetEnergies(), max, min, and pos().
Referenced by G4RDeIonisationSpectrum::Excitation().
void G4RDeIonisationParameters::LoadData () private
Definition at line 144 of file G4RDeIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 144 of file G4RDeIonisationParameters.cc
References a, activeZ, barn, G4DataVector::contains(), d, e, energy, excit, FatalException, file, G4cout, G4endl, G4Exception(), G4Material::GetElementVector(), G4Material::GetMaterialTable(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), G4Element::GetZ(), k, length, m, material(), MeV, G4TrackingService::nMaterials, param, sum, Z, and z.
Referenced by G4RDeIonisationParameters().
G4RDeIonisationParameters& G4RDeIonisationParameters::operator= (const G4RDeIonisationParameters & right) private
G4double G4RDeIonisationParameters::Parameter (G4int Z, G4int shellIndex, G4int parameterIndex, G4double e) const
Definition at line 89 of file G4RDeIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 89 of file G4RDeIonisationParameters.cc
References e, G4RDVEMDataSet::FindValue(), G4cout, G4endl, G4RDVEMDataSet::GetComponent(), G4RDVEMDataSet::GetEnergies(), max, min, G4RDVEMDataSet::NumberOfComponents(), param, and pos().
Referenced by G4RDeIonisationSpectrum::AverageEnergy(), G4RDeIonisationSpectrum::Probability(), and G4RDeIonisationSpectrum::SampleEnergy().
void G4RDeIonisationParameters::PrintData (void) const
Definition at line 371 of file G4RDeIonisationParameters.cc.
View newest version in sPHENIX GitHub at line 371 of file G4RDeIonisationParameters.cc
References activeZ, G4cout, G4endl, G4RDVEMDataSet::GetComponent(), k, length, G4RDVEMDataSet::NumberOfComponents(), param, pos(), G4RDVEMDataSet::PrintData(), and Z.
Referenced by G4RDeIonisationSpectrum::PrintData().
Member Data Documentation
G4DataVector G4RDeIonisationParameters::activeZ private
Definition at line 86 of file G4RDeIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RDeIonisationParameters.hh
Referenced by LoadData(), PrintData(), and ~G4RDeIonisationParameters().
std::map<G4int,G4RDVEMDataSet*,std::less<G4int> > G4RDeIonisationParameters::excit private
Definition at line 90 of file G4RDeIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 90 of file G4RDeIonisationParameters.hh
Referenced by Excitation(), LoadData(), and ~G4RDeIonisationParameters().
size_t G4RDeIonisationParameters::length private
Definition at line 92 of file G4RDeIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 92 of file G4RDeIonisationParameters.hh
Referenced by LoadData(), and PrintData().
std::map<G4int,G4RDVEMDataSet*,std::less<G4int> > G4RDeIonisationParameters::param private
Definition at line 89 of file G4RDeIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RDeIonisationParameters.hh
Referenced by LoadData(), Parameter(), PrintData(), and ~G4RDeIonisationParameters().
G4int G4RDeIonisationParameters::zMax private
Definition at line 84 of file G4RDeIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 84 of file G4RDeIonisationParameters.hh
G4int G4RDeIonisationParameters::zMin private
Definition at line 83 of file G4RDeIonisationParameters.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RDeIonisationParameters.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDeIonisationParameters.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDeIonisationParameters.cc