ECCE @ EIC Software: G4XmlFileManager Class Reference
G4XmlFileManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/xml/include/G4XmlFileManager.hh>
Public Types
using NtupleType = tools::waxml::ntuple
using NtupleDescriptionType = G4TNtupleDescription< NtupleType >
Public Member Functions
G4XmlFileManager (const G4AnalysisManagerState &state)
~G4XmlFileManager ()
virtual G4bool OpenFile (const G4String &fileName) final
virtual G4bool WriteFile () final
virtual G4bool CloseFile () final
G4bool CreateHnFile ()
G4bool CloseHnFile ()
G4bool CreateNtupleFile (NtupleDescriptionType *ntupleDescription)
G4bool CloseNtupleFile (NtupleDescriptionType *ntupleDescription)
std::shared_ptr< std::ofstream > GetHnFile () const
Public Member Functions inherited from G4VFileManager
G4VFileManager (const G4AnalysisManagerState &state)
virtual ~G4VFileManager ()
virtual G4bool SetFileName (const G4String &fileName) final
void LockHistoDirectoryName ()
void LockNtupleDirectoryName ()
G4bool SetHistoDirectoryName (const G4String &dirName)
G4bool SetNtupleDirectoryName (const G4String &dirName)
G4bool IsOpenFile () const
G4String GetHistoDirectoryName () const
G4String GetNtupleDirectoryName () const
Public Member Functions inherited from G4BaseFileManager
G4BaseFileManager (const G4AnalysisManagerState &state)
virtual ~G4BaseFileManager ()
G4String GetFileName () const
G4String GetFullFileName (const G4String &baseFileName="", G4bool isPerThread=true) const
G4String GetHnFileName (const G4String &hnType, const G4String &hnName) const
G4String GetNtupleFileName (const G4String &ntupleName) const
G4String GetNtupleFileName (G4int ntupleFileNumber) const
G4String GetPlotFileName () const
G4String GetFileType () const
Private Attributes
std::shared_ptr< std::ofstream > fHnFile
Additional Inherited Members
Protected Member Functions inherited from G4BaseFileManager
G4String TakeOffExtension (G4String &name) const
Protected Attributes inherited from G4VFileManager
G4bool fIsOpenFile
G4String fHistoDirectoryName
G4String fNtupleDirectoryName
G4bool fLockFileName
G4bool fLockHistoDirectoryName
G4bool fLockNtupleDirectoryName
Detailed Description
Definition at line 45 of file G4XmlFileManager.hh.
View newest version in sPHENIX GitHub at line 45 of file G4XmlFileManager.hh
Member Typedef Documentation
using G4XmlFileManager::NtupleDescriptionType = G4TNtupleDescription<NtupleType>
Definition at line 53 of file G4XmlFileManager.hh.
View newest version in sPHENIX GitHub at line 53 of file G4XmlFileManager.hh
using G4XmlFileManager::NtupleType = tools::waxml::ntuple
Definition at line 52 of file G4XmlFileManager.hh.
View newest version in sPHENIX GitHub at line 52 of file G4XmlFileManager.hh
Constructor & Destructor Documentation
G4XmlFileManager::G4XmlFileManager (const G4AnalysisManagerState & state) explicit
Definition at line 38 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 38 of file G4XmlFileManager.cc
G4XmlFileManager::~G4XmlFileManager ()
Definition at line 45 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 45 of file G4XmlFileManager.cc
Member Function Documentation
G4bool G4XmlFileManager::CloseFile () final virtual
Implements G4VFileManager.
Definition at line 71 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 71 of file G4XmlFileManager.cc
References G4VFileManager::fIsOpenFile, and G4VFileManager::fLockFileName.
G4bool G4XmlFileManager::CloseHnFile ()
Definition at line 111 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 111 of file G4XmlFileManager.cc
References fHnFile, G4BaseFileManager::fState, G4BaseFileManager::GetFullFileName(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4XmlFileManager::CloseNtupleFile (NtupleDescriptionType * ntupleDescription)
Definition at line 171 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 171 of file G4XmlFileManager.cc
References G4TNtupleDescription< TNTUPLE >::fFile, G4TNtupleDescription< TNTUPLE >::fNtupleBooking, G4BaseFileManager::fState, G4BaseFileManager::GetNtupleFileName(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), and G4AnalysisVerbose::Message().
G4bool G4XmlFileManager::CreateHnFile ()
Definition at line 81 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 81 of file G4XmlFileManager.cc
References fHnFile, G4BaseFileManager::fState, G4Exception(), G4BaseFileManager::GetFullFileName(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, and G4AnalysisVerbose::Message().
G4bool G4XmlFileManager::CreateNtupleFile (NtupleDescriptionType * ntupleDescription)
Definition at line 136 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 136 of file G4XmlFileManager.cc
References G4TNtupleDescription< TNTUPLE >::fFile, G4TNtupleDescription< TNTUPLE >::fNtupleBooking, G4BaseFileManager::fState, G4Exception(), G4BaseFileManager::GetNtupleFileName(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, and G4AnalysisVerbose::Message().
std::shared_ptr< std::ofstream > G4XmlFileManager::GetHnFile () const inline
Definition at line 76 of file G4XmlFileManager.hh.
View newest version in sPHENIX GitHub at line 76 of file G4XmlFileManager.hh
References fHnFile.
G4bool G4XmlFileManager::OpenFile (const G4String & fileName) final virtual
Implements G4VFileManager.
Definition at line 53 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 53 of file G4XmlFileManager.cc
References G4BaseFileManager::fFileName, G4VFileManager::fIsOpenFile, and G4VFileManager::fLockFileName.
G4bool G4XmlFileManager::WriteFile () final virtual
Implements G4VFileManager.
Definition at line 64 of file G4XmlFileManager.cc.
View newest version in sPHENIX GitHub at line 64 of file G4XmlFileManager.cc
Member Data Documentation
std::shared_ptr<std::ofstream> G4XmlFileManager::fHnFile private
Definition at line 71 of file G4XmlFileManager.hh.
View newest version in sPHENIX GitHub at line 71 of file G4XmlFileManager.hh
Referenced by CloseHnFile(), CreateHnFile(), and GetHnFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/xml/include/G4XmlFileManager.hh
geant4/tree/geant4-10.6-release/source/analysis/xml/src/G4XmlFileManager.cc