ECCE @ EIC Software: G4VUserParallelWorld Class Reference
G4VUserParallelWorld Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VUserParallelWorld.hh>
Public Member Functions
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
virtual void Construct ()=0
virtual void ConstructSD ()
G4String GetName ()
Protected Member Functions
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes
G4String fWorldName
Detailed Description
Definition at line 47 of file G4VUserParallelWorld.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VUserParallelWorld.hh
Constructor & Destructor Documentation
G4VUserParallelWorld::G4VUserParallelWorld (G4String worldName)
Definition at line 38 of file G4VUserParallelWorld.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VUserParallelWorld.cc
References fWorldName.
G4VUserParallelWorld::~G4VUserParallelWorld () virtual
Definition at line 41 of file G4VUserParallelWorld.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VUserParallelWorld.cc
Member Function Documentation
virtual void G4VUserParallelWorld::Construct () pure virtual
Implemented in B03ImportanceDetectorConstruction, B02ImportanceDetectorConstruction, HadrontherapyDetectorROGeometry, RE04ParallelWorldConstruction, ExGflash2ParallelWorld, RE06ParallelWorld, ExGflash3ParallelWorld, RE01CalorimeterROGeometry, RE05CalorimeterParallelWorld, GB06ParallelWorldForSlices, Par01ParallelWorldForPion, and ParallelWorld.
void G4VUserParallelWorld::ConstructSD () virtual
Reimplemented in B02ImportanceDetectorConstruction, B03ImportanceDetectorConstruction, HadrontherapyDetectorROGeometry, ExGflash2ParallelWorld, RE06ParallelWorld, ExGflash3ParallelWorld, RE01CalorimeterROGeometry, RE05CalorimeterParallelWorld, GB06ParallelWorldForSlices, and Par01ParallelWorldForPion.
Definition at line 44 of file G4VUserParallelWorld.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VUserParallelWorld.cc
G4String G4VUserParallelWorld::GetName (void) inline
Definition at line 64 of file G4VUserParallelWorld.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VUserParallelWorld.hh
References fWorldName.
Referenced by B02ImportanceDetectorConstruction::CreateImportanceStore(), B02ImportanceDetectorConstruction::CreateWeightWindowStore(), main(), and G4VUserDetectorConstruction::RegisterParallelWorld().
G4VPhysicalVolume * G4VUserParallelWorld::GetWorld () protected
Definition at line 47 of file G4VUserParallelWorld.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VUserParallelWorld.cc
References fWorldName, G4TransportationManager::GetParallelWorld(), G4TransportationManager::GetTransportationManager(), and G4VPhysicalVolume::SetName().
Referenced by GB06ParallelWorldForSlices::Construct(), Par01ParallelWorldForPion::Construct(), ExGflash3ParallelWorld::Construct(), RE01CalorimeterROGeometry::Construct(), RE05CalorimeterParallelWorld::Construct(), ExGflash2ParallelWorld::Construct(), RE04ParallelWorldConstruction::Construct(), HadrontherapyDetectorROGeometry::Construct(), B02ImportanceDetectorConstruction::Construct(), B03ImportanceDetectorConstruction::Construct(), GB06ParallelWorldForSlices::ConstructSD(), ParallelWorld::SetupChemistryGeometry(), and RE06ParallelWorld::SetupGeometry().
void G4VUserParallelWorld::SetSensitiveDetector (const G4String & logVolName, G4VSensitiveDetector * aSD, G4bool multi = false) protected
Definition at line 57 of file G4VUserParallelWorld.cc.
View newest version in sPHENIX GitHub at line 57 of file G4VUserParallelWorld.cc
References FatalErrorInArgument, G4Exception(), G4LogicalVolumeStore::GetInstance(), G4VSensitiveDetector::GetName(), and pos().
Referenced by RE01CalorimeterROGeometry::ConstructSD(), RE05CalorimeterParallelWorld::ConstructSD(), B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), and RE06ParallelWorld::SetupDetectors().
void G4VUserParallelWorld::SetSensitiveDetector (G4LogicalVolume * logVol, G4VSensitiveDetector * aSD) protected
Definition at line 92 of file G4VUserParallelWorld.cc.
View newest version in sPHENIX GitHub at line 92 of file G4VUserParallelWorld.cc
References G4SDManager::AddNewDetector(), G4SDManager::GetSDMpointer(), and G4LogicalVolume::SetSensitiveDetector().
Member Data Documentation
G4String G4VUserParallelWorld::fWorldName protected
Definition at line 58 of file G4VUserParallelWorld.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VUserParallelWorld.hh
Referenced by GB06ParallelWorldForSlices::Construct(), G4VUserParallelWorld(), GetName(), and GetWorld().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VUserParallelWorld.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VUserParallelWorld.cc