ECCE @ EIC Software: G4INCL::DecayAvatar Class Reference
G4INCL::DecayAvatar Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLDecayAvatar.hh>
Public Member Functions
DecayAvatar (G4INCL::Particle *aParticle, G4double time, G4INCL::Nucleus *aNucleus, G4bool force=false)
DecayAvatar (G4INCL::Particle *aParticle, G4INCL::Particle *bParticle, G4double time, G4INCL::Nucleus *aNucleus, G4bool force=false)
virtual ~DecayAvatar ()
IChannel * getChannel ()
void fillFinalState (FinalState *fs)
virtual void preInteraction ()
virtual void postInteraction (FinalState *fs)
ParticleList getParticles () const
std::string dump () const
Public Member Functions inherited from G4INCL::InteractionAvatar
InteractionAvatar (G4double, G4INCL::Nucleus *, G4INCL::Particle *)
InteractionAvatar (G4double, G4INCL::Nucleus *, G4INCL::Particle *, G4INCL::Particle *)
virtual ~InteractionAvatar ()
Public Member Functions inherited from G4INCL::IAvatar
IAvatar ()
IAvatar (G4double time)
virtual ~IAvatar ()
FinalState * getFinalState ()
void fillFinalState (FinalState *fs)
G4double getTime () const
AvatarType getType () const
G4bool isACollision () const
G4bool isADecay () const
void setType (AvatarType t)
long getID () const
std::string toString ()
Private Attributes
G4bool forced
ThreeVector const incidentDirection
Additional Inherited Members
Static Public Member Functions inherited from G4INCL::InteractionAvatar
static void deleteBackupParticles ()
Release the memory allocated for the backup particles.
Static Public Attributes inherited from G4INCL::InteractionAvatar
static const G4double locEAccuracy = 1.E-4
Target accuracy in the determination of the local-energy Q-value.
static const G4int maxIterLocE = 50
Max number of iterations for the determination of the local-energy Q-value.
Protected Member Functions inherited from G4INCL::InteractionAvatar
G4bool bringParticleInside (Particle *const p)
void preInteractionLocalEnergy (Particle *const p)
Apply local-energy transformation, if appropriate.
void preInteractionBlocking ()
Store the state of the particles before the interaction.
void preInteraction ()
void postInteraction (FinalState *)
void restoreParticles () const
Restore the state of both particles.
G4bool shouldUseLocalEnergy () const
true if the given avatar should use local energy
G4bool enforceEnergyConservation (FinalState *const fs)
Enforce energy conservation.
Protected Attributes inherited from G4INCL::InteractionAvatar
Nucleus * theNucleus
Particle * particle1
Particle * particle2
ThreeVector boostVector
G4double oldTotalEnergy
G4double oldXSec
G4bool isPiN
G4double weight
ParticleList modified
ParticleList created
ParticleList modifiedAndCreated
ParticleList Destroyed
ParticleList ModifiedAndDestroyed
Static Protected Attributes inherited from G4INCL::InteractionAvatar
static G4ThreadLocal Particle * backupParticle1 = NULL
static G4ThreadLocal Particle * backupParticle2 = NULL
Detailed Description
Decay avatar
The reflection avatar is created when a particle reaches the boundary of the nucleus. At this point it can either be reflected from the boundary or exit the nucleus.
Definition at line 55 of file G4INCLDecayAvatar.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLDecayAvatar.hh
Constructor & Destructor Documentation
G4INCL::DecayAvatar::DecayAvatar (G4INCL::Particle * aParticle, G4double time, G4INCL::Nucleus * aNucleus, G4bool force = false)
Definition at line 52 of file G4INCLDecayAvatar.cc.
View newest version in sPHENIX GitHub at line 52 of file G4INCLDecayAvatar.cc
References G4INCL::DecayAvatarType, and G4INCL::IAvatar::setType().
G4INCL::DecayAvatar::DecayAvatar (G4INCL::Particle * aParticle, G4INCL::Particle * bParticle, G4double time, G4INCL::Nucleus * aNucleus, G4bool force = false)
Definition at line 59 of file G4INCLDecayAvatar.cc.
View newest version in sPHENIX GitHub at line 59 of file G4INCLDecayAvatar.cc
References G4INCL::DecayAvatarType, and G4INCL::IAvatar::setType().
G4INCL::DecayAvatar::~DecayAvatar () virtual
Definition at line 66 of file G4INCLDecayAvatar.cc.
View newest version in sPHENIX GitHub at line 66 of file G4INCLDecayAvatar.cc
Member Function Documentation
std::string G4INCL::DecayAvatar::dump () const virtual
Implements G4INCL::IAvatar.
Definition at line 207 of file G4INCLDecayAvatar.cc.
View newest version in sPHENIX GitHub at line 207 of file G4INCLDecayAvatar.cc
References G4INCL::Particle::dump(), G4INCL::InteractionAvatar::particle1, and G4INCL::IAvatar::theTime.
void G4INCL::DecayAvatar::fillFinalState (FinalState * fs)
G4INCL::IChannel * G4INCL::DecayAvatar::getChannel () virtual
Implements G4INCL::InteractionAvatar.
Definition at line 70 of file G4INCLDecayAvatar.cc.
View newest version in sPHENIX GitHub at line 70 of file G4INCLDecayAvatar.cc
References G4INCL::Particle::getType(), incidentDirection, INCL_DEBUG, G4INCL::Particle::isAntiKaon(), G4INCL::Particle::isDelta(), G4INCL::Particle::isEta(), G4INCL::Particle::isNucleon(), G4INCL::Particle::isOmega(), G4INCL::Particle::isSigma(), G4INCL::KZero, G4INCL::KZeroBar, G4INCL::InteractionAvatar::particle1, G4INCL::InteractionAvatar::particle2, and G4INCL::SigmaZero.
ParticleList G4INCL::DecayAvatar::getParticles () const inline virtual
Implements G4INCL::IAvatar.
Definition at line 67 of file G4INCLDecayAvatar.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLDecayAvatar.hh
References G4INCL::InteractionAvatar::particle1.
void G4INCL::DecayAvatar::postInteraction (FinalState * fs) virtual
Implements G4INCL::IAvatar.
Definition at line 100 of file G4INCLDecayAvatar.cc.
View newest version in sPHENIX GitHub at line 100 of file G4INCLDecayAvatar.cc
References G4INCL::FinalState::addModifiedParticle(), G4INCL::InteractionAvatar::created, G4INCL::InteractionAvatar::Destroyed, e, G4INCL::InteractionAvatar::enforceEnergyConservation(), forced, G4INCL::Store::getBook(), G4INCL::FinalState::getCreatedParticles(), G4INCL::FinalState::getDestroyedParticles(), G4INCL::FinalState::getModifiedParticles(), G4INCL::ParticleList::getParticleListBiasVector(), G4INCL::Nucleus::getStore(), G4INCL::FinalState::getValidity(), INCL_DEBUG, G4INCL::Book::incrementAcceptedDecays(), G4INCL::Book::incrementBlockedDecays(), G4INCL::Pauli::isCDPPBlocked(), G4INCL::FinalState::makeNoEnergyConservation(), G4INCL::FinalState::makePauliBlocked(), G4INCL::InteractionAvatar::modified, G4INCL::InteractionAvatar::modifiedAndCreated, G4INCL::InteractionAvatar::ModifiedAndDestroyed, G4INCL::NoEnergyConservationFS, G4INCL::InteractionAvatar::oldTotalEnergy, G4INCL::InteractionAvatar::particle1, G4INCL::ParticleBelowFermiFS, G4INCL::ParticleBelowZeroFS, G4INCL::PauliBlockedFS, G4INCL::InteractionAvatar::postInteraction(), G4INCL::FinalState::reset(), G4INCL::InteractionAvatar::restoreParticles(), G4INCL::FinalState::setTotalEnergyBeforeInteraction(), G4INCL::InteractionAvatar::theNucleus, and G4INCL::ValidFS.
void G4INCL::DecayAvatar::preInteraction () virtual
Implements G4INCL::IAvatar.
Definition at line 96 of file G4INCLDecayAvatar.cc.
View newest version in sPHENIX GitHub at line 96 of file G4INCLDecayAvatar.cc
References G4INCL::InteractionAvatar::preInteraction().
Member Data Documentation
G4bool G4INCL::DecayAvatar::forced private
Definition at line 75 of file G4INCLDecayAvatar.hh.
View newest version in sPHENIX GitHub at line 75 of file G4INCLDecayAvatar.hh
Referenced by postInteraction().
ThreeVector const G4INCL::DecayAvatar::incidentDirection private
Definition at line 76 of file G4INCLDecayAvatar.hh.
View newest version in sPHENIX GitHub at line 76 of file G4INCLDecayAvatar.hh
Referenced by getChannel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLDecayAvatar.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLDecayAvatar.cc