ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/track/pymodG4track.cc File Reference
pymodG4track.cc File Reference
#include <boost/python.hpp>
Functions
void export_G4Track ()
void export_G4TrackStatus ()
void export_G4Step ()
void export_G4StepPoint ()
void export_G4StepStatus ()
BOOST_PYTHON_MODULE (G4track)
Function Documentation
BOOST_PYTHON_MODULE (G4track)
Definition at line 44 of file pymodG4track.cc.
View newest version in sPHENIX GitHub at line 44 of file pymodG4track.cc
References export_G4Step(), export_G4StepPoint(), export_G4StepStatus(), export_G4Track(), and export_G4TrackStatus().
void export_G4Step ()
Definition at line 40 of file pyG4Step.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4Step.cc
References G4Step::GetDeltaEnergy(), G4Step::GetDeltaMomentum(), G4Step::GetDeltaPosition(), G4Step::GetDeltaTime(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), and G4Step::GetTrack().
Referenced by BOOST_PYTHON_MODULE().
void export_G4StepPoint ()
Definition at line 40 of file pyG4StepPoint.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4StepPoint.cc
References G4StepPoint::GetBeta(), G4StepPoint::GetCharge(), G4StepPoint::GetGamma(), G4StepPoint::GetGlobalTime(), G4StepPoint::GetKineticEnergy(), G4StepPoint::GetLocalTime(), G4StepPoint::GetMass(), G4StepPoint::GetMaterial(), G4StepPoint::GetMomentum(), G4StepPoint::GetMomentumDirection(), G4StepPoint::GetPolarization(), G4StepPoint::GetPosition(), G4StepPoint::GetProcessDefinedStep(), G4StepPoint::GetProperTime(), G4StepPoint::GetStepStatus(), G4StepPoint::GetTotalEnergy(), G4StepPoint::GetTouchable(), G4StepPoint::GetVelocity(), and G4StepPoint::GetWeight().
Referenced by BOOST_PYTHON_MODULE().
void export_G4StepStatus ()
Definition at line 39 of file pyG4StepStatus.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4StepStatus.cc
References fAlongStepDoItProc, fAtRestDoItProc, fExclusivelyForcedProc, fGeomBoundary, fPostStepDoItProc, fUndefined, fUserDefinedLimit, and fWorldBoundary.
Referenced by BOOST_PYTHON_MODULE().
void export_G4Track ()
Definition at line 40 of file pyG4Track.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4Track.cc
References G4Track::GetCreatorProcess(), G4Track::GetCurrentStepNumber(), G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4Track::GetLocalTime(), G4Track::GetLogicalVolumeAtVertex(), G4Track::GetMaterial(), G4Track::GetMomentum(), G4Track::GetMomentumDirection(), G4Track::GetParentID(), G4Track::GetPolarization(), G4Track::GetPosition(), G4Track::GetProperTime(), G4Track::GetStep(), G4Track::GetStepLength(), G4Track::GetTotalEnergy(), G4Track::GetTouchable(), G4Track::GetTrackID(), G4Track::GetTrackLength(), G4Track::GetTrackStatus(), G4Track::GetVelocity(), G4Track::GetVertexKineticEnergy(), G4Track::GetVertexMomentumDirection(), G4Track::GetVertexPosition(), G4Track::GetVolume(), G4Track::GetWeight(), and G4Track::SetWeight().
Referenced by BOOST_PYTHON_MODULE().
void export_G4TrackStatus ()
Definition at line 39 of file pyG4TrackStatus.cc.
View newest version in sPHENIX GitHub at line 39 of file pyG4TrackStatus.cc
References fAlive, fKillTrackAndSecondaries, fPostponeToNextEvent, fStopAndKill, fStopButAlive, and fSuspend.
Referenced by BOOST_PYTHON_MODULE().