ECCE @ EIC Software: G4PSFlatSurfaceCurrent Class Reference
G4PSFlatSurfaceCurrent Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSFlatSurfaceCurrent.hh>
Public Member Functions
G4PSFlatSurfaceCurrent (G4String name, G4int direction, G4int depth=0)
G4PSFlatSurfaceCurrent (G4String name, G4int direction, const G4String &unit, G4int depth=0)
virtual ~G4PSFlatSurfaceCurrent ()
void Weighted (G4bool flg=true)
void DivideByArea (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
G4int IsSelectedSurface (G4Step *, G4Box *)
virtual void DefineUnitAndCategory ()
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4int fDirection
G4THitsMap< G4double > * EvtMap
G4bool weighted
G4bool divideByArea
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 59 of file G4PSFlatSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PSFlatSurfaceCurrent.hh
Constructor & Destructor Documentation
G4PSFlatSurfaceCurrent::G4PSFlatSurfaceCurrent (G4String name, G4int direction, G4int depth = 0)
Definition at line 58 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PSFlatSurfaceCurrent.cc
References DefineUnitAndCategory(), and SetUnit().
G4PSFlatSurfaceCurrent::G4PSFlatSurfaceCurrent (G4String name, G4int direction, const G4String & unit, G4int depth = 0)
Definition at line 67 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 67 of file G4PSFlatSurfaceCurrent.cc
References DefineUnitAndCategory(), and SetUnit().
G4PSFlatSurfaceCurrent::~G4PSFlatSurfaceCurrent () virtual
Definition at line 78 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 78 of file G4PSFlatSurfaceCurrent.cc
Member Function Documentation
void G4PSFlatSurfaceCurrent::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 158 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 158 of file G4PSFlatSurfaceCurrent.cc
References G4VTHitsMap< T, Map_t >::clear(), and EvtMap.
void G4PSFlatSurfaceCurrent::DefineUnitAndCategory () protected virtual
Definition at line 198 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 198 of file G4PSFlatSurfaceCurrent.cc
References cm2, m2, and mm2.
Referenced by G4PSFlatSurfaceCurrent().
void G4PSFlatSurfaceCurrent::DivideByArea (G4bool flg = true) inline
Definition at line 71 of file G4PSFlatSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 71 of file G4PSFlatSurfaceCurrent.hh
References divideByArea.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
void G4PSFlatSurfaceCurrent::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 162 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 162 of file G4PSFlatSurfaceCurrent.cc
void G4PSFlatSurfaceCurrent::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 155 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 155 of file G4PSFlatSurfaceCurrent.cc
void G4PSFlatSurfaceCurrent::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 148 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 148 of file G4PSFlatSurfaceCurrent.cc
References G4HCofThisEvent::AddHitsCollection(), G4VPrimitiveScorer::detector, EvtMap, G4VPrimitiveScorer::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), and HCID.
G4int G4PSFlatSurfaceCurrent::IsSelectedSurface (G4Step * aStep, G4Box * boxSolid) protected
Definition at line 119 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 119 of file G4PSFlatSurfaceCurrent.cc
References fCurrent_In, fCurrent_Out, fGeomBoundary, G4VTouchable::GetHistory(), G4GeometryTolerance::GetInstance(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetStepStatus(), G4GeometryTolerance::GetSurfaceTolerance(), G4NavigationHistory::GetTopTransform(), G4StepPoint::GetTouchableHandle(), G4Box::GetZHalfLength(), kCarTolerance, G4AffineTransform::TransformPoint(), and CLHEP::Hep3Vector::z().
Referenced by ProcessHits().
void G4PSFlatSurfaceCurrent::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 165 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 165 of file G4PSFlatSurfaceCurrent.cc
References G4VPrimitiveScorer::detector, divideByArea, G4VTHitsMap< T, Map_t >::entries(), EvtMap, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), G4VPrimitiveScorer::GetUnit(), and G4VPrimitiveScorer::GetUnitValue().
G4bool G4PSFlatSurfaceCurrent::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 81 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 81 of file G4PSFlatSurfaceCurrent.cc
References G4VTHitsMap< T, Map_t >::add(), G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), divideByArea, EvtMap, fCurrent_InOut, fDirection, G4VPrimitiveScorer::GetIndex(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetParameterisation(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), G4LogicalVolume::GetSolid(), G4StepPoint::GetTouchable(), G4StepPoint::GetTouchableHandle(), G4StepPoint::GetWeight(), G4Box::GetXHalfLength(), G4Box::GetYHalfLength(), incremental_prev_tag::idx, G4VPrimitiveScorer::indexDepth, IsSelectedSurface(), square(), TRUE, and weighted.
void G4PSFlatSurfaceCurrent::SetUnit (const G4String & unit) virtual
Definition at line 183 of file G4PSFlatSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 183 of file G4PSFlatSurfaceCurrent.cc
References G4VPrimitiveScorer::CheckAndSetUnit(), divideByArea, G4Exception(), G4VPrimitiveScorer::GetName(), G4VPrimitiveScorer::GetUnit(), JustWarning, G4VPrimitiveScorer::unitName, and G4VPrimitiveScorer::unitValue.
Referenced by G4PSFlatSurfaceCurrent(), G4PSFlatSurfaceCurrent3D::G4PSFlatSurfaceCurrent3D(), and G4ScoreQuantityMessenger::SetNewValue().
void G4PSFlatSurfaceCurrent::Weighted (G4bool flg = true) inline
Definition at line 69 of file G4PSFlatSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PSFlatSurfaceCurrent.hh
References weighted.
Referenced by G4ScoreQuantityMessenger::SetNewValue().
Member Data Documentation
G4bool G4PSFlatSurfaceCurrent::divideByArea private
Definition at line 95 of file G4PSFlatSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PSFlatSurfaceCurrent.hh
Referenced by DivideByArea(), PrintAll(), ProcessHits(), and SetUnit().
G4THitsMap<G4double>* G4PSFlatSurfaceCurrent::EvtMap private
Definition at line 93 of file G4PSFlatSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PSFlatSurfaceCurrent.hh
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
G4int G4PSFlatSurfaceCurrent::fDirection private
Definition at line 92 of file G4PSFlatSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PSFlatSurfaceCurrent.hh
Referenced by ProcessHits().
G4int G4PSFlatSurfaceCurrent::HCID private
Definition at line 91 of file G4PSFlatSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PSFlatSurfaceCurrent.hh
Referenced by Initialize().
G4bool G4PSFlatSurfaceCurrent::weighted private
Definition at line 94 of file G4PSFlatSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PSFlatSurfaceCurrent.hh
Referenced by ProcessHits(), and Weighted().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSFlatSurfaceCurrent.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSFlatSurfaceCurrent.cc