ECCE @ EIC Software: G4LogicalVolume Class Reference
G4LogicalVolume Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4LogicalVolume.hh>
Public Member Functions
G4LogicalVolume (G4VSolid *pSolid, G4Material *pMaterial, const G4String &name, G4FieldManager *pFieldMgr=nullptr, G4VSensitiveDetector *pSDetector=nullptr, G4UserLimits *pULimits=nullptr, G4bool optimise=true)
virtual ~G4LogicalVolume ()
G4LogicalVolume (const G4LogicalVolume &)=delete
G4LogicalVolume & operator= (const G4LogicalVolume &)=delete
const G4String & GetName () const
void SetName (const G4String &pName)
size_t GetNoDaughters () const
G4VPhysicalVolume * GetDaughter (const G4int i) const
void AddDaughter (G4VPhysicalVolume *p)
G4bool IsDaughter (const G4VPhysicalVolume *p) const
G4bool IsAncestor (const G4VPhysicalVolume *p) const
void RemoveDaughter (const G4VPhysicalVolume *p)
void ClearDaughters ()
G4int TotalVolumeEntities () const
EVolume CharacteriseDaughters () const
EVolume DeduceDaughtersType () const
G4VSolid * GetSolid () const
void SetSolid (G4VSolid *pSolid)
G4Material * GetMaterial () const
void SetMaterial (G4Material *pMaterial)
void UpdateMaterial (G4Material *pMaterial)
G4double GetMass (G4bool forced=false, G4bool propagate=true, G4Material *parMaterial=nullptr)
void ResetMass ()
G4FieldManager * GetFieldManager () const
void SetFieldManager (G4FieldManager *pFieldMgr, G4bool forceToAllDaughters)
G4VSensitiveDetector * GetSensitiveDetector () const
void SetSensitiveDetector (G4VSensitiveDetector *pSDetector)
G4UserLimits * GetUserLimits () const
void SetUserLimits (G4UserLimits *pULimits)
G4SmartVoxelHeader * GetVoxelHeader () const
void SetVoxelHeader (G4SmartVoxelHeader *pVoxel)
G4double GetSmartless () const
void SetSmartless (G4double s)
G4bool IsToOptimise () const
void SetOptimisation (G4bool optim)
G4bool IsRootRegion () const
void SetRegionRootFlag (G4bool rreg)
G4bool IsRegion () const
void SetRegion (G4Region *reg)
G4Region * GetRegion () const
void PropagateRegion ()
const G4MaterialCutsCouple * GetMaterialCutsCouple () const
void SetMaterialCutsCouple (G4MaterialCutsCouple *cuts)
G4bool operator== (const G4LogicalVolume &lv) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *pVA)
void SetVisAttributes (const G4VisAttributes &VA)
G4FastSimulationManager * GetFastSimulationManager () const
void SetBiasWeight (G4double w)
G4double GetBiasWeight () const
G4LogicalVolume (__void__ &)
virtual G4bool IsExtended () const
G4FieldManager * GetMasterFieldManager () const
G4VSensitiveDetector * GetMasterSensitiveDetector () const
G4VSolid * GetMasterSolid () const
G4int GetInstanceID () const
void Lock ()
void InitialiseWorker (G4LogicalVolume *ptrMasterObject, G4VSolid *pSolid, G4VSensitiveDetector *pSDetector)
void TerminateWorker (G4LogicalVolume *ptrMasterObject)
void AssignFieldManager (G4FieldManager *fldMgr)
G4bool ChangeDaughtersType (EVolume atype)
Static Public Member Functions
static const G4LVManager & GetSubInstanceManager ()
static void Clean ()
static G4VSolid * GetSolid (G4LVData &instLVdata)
static void SetSolid (G4LVData &instLVdata, G4VSolid *pSolid)
Private Types
typedef std::vector
< G4VPhysicalVolume * > G4PhysicalVolumeList
Private Attributes
G4PhysicalVolumeList fDaughters
G4String fName
EVolume fDaughtersVolumeType
G4UserLimits * fUserLimits = nullptr
G4SmartVoxelHeader * fVoxel = nullptr
G4bool fOptimise = true
G4bool fRootRegion = false
G4bool fLock = false
G4double fSmartless = 2.0
const G4VisAttributes * fVisAttributes = nullptr
G4Region * fRegion = nullptr
G4double fBiasWeight = 1.0
G4int instanceID
G4VSolid * fSolid = nullptr
G4VSensitiveDetector * fSensitiveDetector = nullptr
G4FieldManager * fFieldManager = nullptr
G4LVData * lvdata = nullptr
Static Private Attributes
static G4GEOM_DLL G4LVManager subInstanceManager
Detailed Description
Definition at line 182 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 182 of file G4LogicalVolume.hh
Member Typedef Documentation
typedef std::vector<G4VPhysicalVolume*> G4LogicalVolume::G4PhysicalVolumeList private
Definition at line 184 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 184 of file G4LogicalVolume.hh
Constructor & Destructor Documentation
G4LogicalVolume::G4LogicalVolume (G4VSolid * pSolid, G4Material * pMaterial, const G4String & name, G4FieldManager * pFieldMgr = nullptr, G4VSensitiveDetector * pSDetector = nullptr, G4UserLimits * pULimits = nullptr, G4bool optimise = true)
Definition at line 68 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 68 of file G4LogicalVolume.cc
References AssignFieldManager(), G4GeomSplitter< T >::CreateSubInstance(), fFieldManager, G4LVData::fMaterial, fSensitiveDetector, G4LVData::fSolid, fSolid, G4MT_ccouple, G4MT_mass, instanceID, lvdata, G4LogicalVolumeStore::Register(), SetMaterial(), SetName(), SetSensitiveDetector(), SetSolid(), SetUserLimits(), and subInstanceManager.
G4LogicalVolume::~G4LogicalVolume () virtual
Definition at line 134 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 134 of file G4LogicalVolume.cc
References G4LogicalVolumeStore::DeRegister(), fLock, fRegion, fRootRegion, lvdata, and G4Region::RemoveRootLogicalVolume().
G4LogicalVolume::G4LogicalVolume (const G4LogicalVolume &) delete
G4LogicalVolume::G4LogicalVolume (__void__ &)
Definition at line 113 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 113 of file G4LogicalVolume.cc
References G4GeomSplitter< T >::CreateSubInstance(), G4MT_ccouple, G4MT_mass, instanceID, G4LogicalVolumeStore::Register(), SetFieldManager(), SetSensitiveDetector(), and subInstanceManager.
Member Function Documentation
void G4LogicalVolume::AddDaughter (G4VPhysicalVolume * p)
Definition at line 271 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 271 of file G4LogicalVolume.cc
References FatalException, fDaughters, fDaughtersVolumeType, fRegion, G4endl, G4Exception(), G4MT_fmanager, G4MT_mass, GetFieldManager(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), GetName(), message(), PropagateRegion(), G4Region::RegionModified(), SetFieldManager(), and G4VPhysicalVolume::VolumeType().
Referenced by G4ReplicatedSlice::CheckAndSetParameters(), EICG4dRICHDetector::ConstructMe(), export_G4LogicalVolume(), G4PVDivision::G4PVDivision(), G4PVParameterised::G4PVParameterised(), G4PVPlacement::G4PVPlacement(), G4PVReplica::G4PVReplica(), and G4VExternalPhysicalVolume::G4VExternalPhysicalVolume().
void G4LogicalVolume::AssignFieldManager (G4FieldManager * fldMgr)
Definition at line 230 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 230 of file G4LogicalVolume.cc
References fFieldManager, G4MT_fmanager, and G4Threading::IsMasterThread().
Referenced by G4LogicalVolume(), InitialiseWorker(), and SetFieldManager().
G4bool G4LogicalVolume::ChangeDaughtersType (EVolume atype)
Definition at line 649 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 649 of file G4LogicalVolume.cc
References DeduceDaughtersType(), fDaughtersVolumeType, and kExternal.
EVolume G4LogicalVolume::CharacteriseDaughters () const inline
Referenced by G4Navigator::RecheckDistanceToCurrentBoundary(), and G4ITNavigator2::RecheckDistanceToCurrentBoundary().
void G4LogicalVolume::Clean () static
Definition at line 188 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 188 of file G4LogicalVolume.cc
References G4GeomSplitter< T >::FreeSlave(), and subInstanceManager.
Referenced by G4LogicalVolumeStore::~G4LogicalVolumeStore().
void G4LogicalVolume::ClearDaughters ()
Definition at line 375 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 375 of file G4LogicalVolume.cc
References fDaughters, fRegion, G4MT_mass, and G4Region::RegionModified().
Referenced by export_G4LogicalVolume().
EVolume G4LogicalVolume::DeduceDaughtersType () const inline
Referenced by ChangeDaughtersType().
G4double G4LogicalVolume::GetBiasWeight () const inline
Referenced by G4ReflectionFactory::CreateReflectedLV(), and export_G4LogicalVolume().
G4VPhysicalVolume* G4LogicalVolume::GetDaughter (const G4int i) const inline
Referenced by EICG4dRICHDetector::ActivateVolumeTree(), G4GMocrenFileSceneHandler::AddSolid(), G4Region::BelongsTo(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4PVReplica::CheckOnlyDaughter(), G4PVPlacement::CheckOverlaps(), CML2WorldConstruction::checkVolumeOverlap(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4RegularNavigation::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4GeometryManager::DeleteOptimisations(), G4LogicalVolumeModel::DescribeYourselfTo(), export_G4LogicalVolume(), PHG4EICMvtxDetector::FindSensor(), PHG4MvtxDetector::FindSensor(), PHG4DisplayAction::FindVolumes(), G4SmartVoxelHeader::G4SmartVoxelHeader(), BeastMagnetDetector::InsertVolumes(), AllSiliconTrackerDetector::InsertVolumes(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), CexmcSetup::ReadCalorimeterGeometryData(), G4ReflectionFactory::ReflectDaughters(), G4VoxelSafety::SafetyForVoxelNode(), G4ProductionCutsTable::ScanAndSetCouple(), G4Region::ScanVolumeTree(), G4LBLVtxDetector::SetActiveVolumes(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), PHG4MvtxDetector::SetDisplayProperty(), SetFieldManager(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4GeomTestVolume::TestRecursiveOverlap(), PHG4GDMLWriteStructure::TraverseVolumeTree(), and G4GDMLWriteStructure::TraverseVolumeTree().
G4FastSimulationManager* G4LogicalVolume::GetFastSimulationManager () const inline
Referenced by G4FastSimulationManagerProcess::AtRestGetPhysicalInteractionLength(), export_G4LogicalVolume(), GFlashHitMaker::make(), and G4FastSimulationManagerProcess::PostStepGetPhysicalInteractionLength().
G4FieldManager * G4LogicalVolume::GetFieldManager () const
Definition at line 221 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 221 of file G4LogicalVolume.cc
References G4MT_fmanager.
Referenced by AddDaughter(), G4ReflectionFactory::CreateReflectedLV(), G4VFieldModel::DescribeYourselfTo(), export_G4LogicalVolume(), G4PropagatorInField::FindAndSetFieldManager(), InitialiseWorker(), SetFieldManager(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
G4int G4LogicalVolume::GetInstanceID () const inline
G4double G4LogicalVolume::GetMass (G4bool forced = false, G4bool propagate = true, G4Material * parMaterial = nullptr)
Definition at line 552 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 552 of file G4LogicalVolume.cc
References G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeMaterial(), G4VPVParameterisation::ComputeSolid(), FatalException, fDaughters, fName, G4endl, G4Exception(), G4MT_mass, G4VSolid::GetCubicVolume(), G4Material::GetDensity(), G4VPhysicalVolume::GetLogicalVolume(), GetMass(), GetMaterial(), G4VPhysicalVolume::GetMultiplicity(), G4VPhysicalVolume::GetParameterisation(), GetSolid(), and message().
Referenced by PHG4FullProjTiltedSpacalDetector::Construct_Tower(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), export_G4LogicalVolume(), DetectorConstruction::GetAbsorMass(), DetectorConstruction::GetCytoMass(), GetMass(), DetectorConstruction::GetNuclMass(), and G4ASCIITreeSceneHandler::RequestPrimitives().
G4FieldManager* G4LogicalVolume::GetMasterFieldManager () const inline
Referenced by G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
G4VSensitiveDetector* G4LogicalVolume::GetMasterSensitiveDetector () const inline
Referenced by G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
G4VSolid* G4LogicalVolume::GetMasterSolid () const inline
Referenced by G4GeometryWorkspace::InitialisePhysicalVolumes().
G4Material * G4LogicalVolume::GetMaterial () const
Definition at line 429 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 429 of file G4LogicalVolume.cc
References G4MT_material.
Referenced by CML2ExpVoxels::add(), UltraFresnelLens::BuildLens(), G4Track::CalculateVelocityForOpticalPhoton(), G4AdjointPrimaryGenerator::ComputeAccumulatedDepthVectorAlongBackRay(), G4VPVParameterisation::ComputeMaterial(), CellParameterisation::ComputeMaterial(), PHG4PhenixDetector::Construct(), G4MIRDLeftLegBone::Construct(), G4MIRDRightKidney::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLiver::Construct(), G4MIRDPelvis::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDRightLeg::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDSkull::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDThyroid::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDBrain::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDPancreas::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDTrunk::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDHead::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDRightArmBone::Construct(), G4MIRDUrinaryBladder::Construct(), PHG4MvtxDetector::ConstructMe(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4ReflectionFactory::CreateReflectedLV(), G4tgbGeometryDumper::DumpLogVol(), export_G4LogicalVolume(), PHG4GDMLWriteStructure::ExportEnergyCuts(), G4GDMLWriteStructure::ExportEnergyCuts(), DetectorConstruction::GetAbsorberMaterial(), G4LogicalCrystalVolume::GetCrystal(), GetMass(), G4Channeling::GetMatData(), PHG4MvtxDetector::GetMvtxOuterShell(), PhysicsList::GetRange(), G4LatticeManager::LoadLattice(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), XrayFluoMercuryDetectorConstruction::PrintApparateParameters(), XrayFluoPlaneDetectorConstruction::PrintApparateParameters(), XrayFluoDetectorConstruction::PrintApparateParameters(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4LatticeManager::RegisterLattice(), G4PropagatorInField::ReportLoopingParticle(), G4ProductionCutsTable::ScanAndSetCouple(), G4Region::ScanVolumeTree(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), PHG4MvtxDetector::SetDisplayProperty(), G4ParallelWorldProcess::SwitchMaterial(), PHG4GDMLWriteStructure::TraverseVolumeTree(), G4GDMLWriteStructure::TraverseVolumeTree(), and EICG4LumiSteppingAction::UserSteppingAction().
const G4MaterialCutsCouple * G4LogicalVolume::GetMaterialCutsCouple () const
Definition at line 478 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 478 of file G4LogicalVolume.cc
References G4MT_ccouple.
Referenced by export_G4LogicalVolume(), PhysicsList::GetRange(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), and G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength().
const G4String& G4LogicalVolume::GetName () const inline
Referenced by G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), EICG4LumiDetector::AddCAL(), AddDaughter(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepSceneHandler::AddSolid(), G4VBiasingOperator::AttachTo(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4SmartVoxelHeader::BuildVoxelsWithinLimits(), G4PVReplica::CheckOnlyDaughter(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), checkVol(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G3toG4DetectorConstruction::Construct(), FFDetectorConstruction::Construct(), Par02DetectorConstruction::Construct(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), G4tgbVolume::ConstructG4LogVol(), G4tgbVolume::ConstructG4PhysVol(), G4tgbVolume::ConstructG4Volumes(), CCalG4Ecal::constructGlobal(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Ecal::constructIn(), PHG4EPDDetector::ConstructMe(), CCalG4Hcal::constructScintillatorLayer(), GB07DetectorConstruction::ConstructSDandField(), GB01DetectorConstruction::ConstructSDandField(), GB02DetectorConstruction::ConstructSDandField(), GB04DetectorConstruction::ConstructSDandField(), RE01CalorimeterHit::CreateAttValues(), B5HodoscopeHit::CreateAttValues(), B5EmCalorimeterHit::CreateAttValues(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G3Division::CreatePVReplica(), G4ReflectionFactory::CreateReflectedLV(), G4AdjointCrossSurfChecker::CrossingAnInterfaceBetweenTwoVolumes(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4RunManagerKernel::DefineWorldVolume(), G4RadioactiveDecayBase::DeselectAVolume(), G4RadioactiveDecay::DeselectAVolume(), G4ReflectionFactory::Divide(), G4GDMLReadStructure::DivisionvolRead(), PHG4GDMLWriteStructure::DivisionvolWrite(), G4GDMLWriteStructure::DivisionvolWrite(), G4TrajectoryDrawByOriginVolume::Draw(), G4tgbVolumeMgr::DumpG4LogVolLeaf(), G4tgbGeometryDumper::DumpLogVol(), G4tgbGeometryDumper::DumpPhysVol(), G4tgbGeometryDumper::DumpPVParameterised(), G4tgbGeometryDumper::DumpPVPlacement(), G4tgbGeometryDumper::DumpPVReplica(), G4TrajectoryOriginVolumeFilter::Evaluate(), export_G4LogicalVolume(), G4GDMLParser::ExportRegions(), PHG4EICMvtxDetector::FillPVArray(), PHG4MvtxDetector::FillPVArray(), PHG4EICMvtxDetector::FindSensor(), PHG4MvtxDetector::FindSensor(), G4BuildGeom(), G4PVReplica::G4PVReplica(), G4GDMLRead::GeneratePhysvolName(), PHG4InttDetector::get_PassiveVolumeTuple(), G4HepRepSceneHandler::getGeometryInstance(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4tgbGeometryDumper::GetPVChildren(), G4tgbVolumeMgr::GetTopLogVol(), G4tgbVolumeMgr::GetTopPhysVol(), G4GDMLReadStructure::GetWorldVolume(), G4AdjointCrossSurfChecker::GoingInOrOutOfaVolumeByExtSurface(), G4GDMLWriteParamvol::ParamvolAlgorithmWrite(), PHG4GDMLWriteParamvol::ParamvolAlgorithmWrite(), G4GDMLReadParamvol::ParamvolRead(), G4GDMLWriteParamvol::ParamvolWrite(), PHG4GDMLWriteParamvol::ParamvolWrite(), G4GDMLReadStructure::PhysvolRead(), PHG4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteStructure::PhysvolWrite(), G4ReflectionFactory::Place(), BeamLineMagnetDetector::PostConstruction(), G4HumanPhantomSD::ProcessHits(), G4ReflectionFactory::ReflectDaughters(), G4ReflectionFactory::ReflectPVDivision(), G4ReflectionFactory::ReflectPVPlacement(), G4ReflectionFactory::ReflectPVReplica(), PHG4TTLDetector::RegisterLogicalVolume(), PHG4Sector::PHG4SectorConstructor::RegisterLogicalVolume(), ePHENIXRICH::ePHENIXRICHConstruction::RegisterLogicalVolume(), G4tgbVolumeMgr::RegisterMe(), CCalSensitiveDetectors::registerVolume(), G4RunManager::ReOptimize(), G4GDMLReadStructure::ReplicaRead(), G4ReflectionFactory::Replicate(), PHG4GDMLWriteStructure::ReplicavolWrite(), G4GDMLWriteStructure::ReplicavolWrite(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VoxelSafety::SafetyForVoxelHeader(), G4PolarizedComptonModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4Region::ScanVolumeTree(), G4RadioactiveDecayBase::SelectAllVolumes(), G4RadioactiveDecay::SelectAllVolumes(), G4RadioactiveDecayBase::SelectAVolume(), G4RadioactiveDecay::SelectAVolume(), G4VVisCommandGeometrySet::Set(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), PHG4MvtxDetector::SetDisplayProperty(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4VisCommandGeometryList::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), DicomDetectorConstruction::SetScorer(), CCalSensitiveDetectors::setSensitive(), G4VUserDetectorConstruction::SetSensitiveDetector(), G4GDMLWriteSetup::SetupWrite(), PHG4GDMLWriteSetup::SetupWrite(), CCalG4Able::setVisType(), G4PolarizationManager::SetVolumePolarization(), PHG4GDMLWriteStructure::SkinSurfaceCache(), G4GDMLWriteStructure::SkinSurfaceCache(), G4GDMLRead::StripNames(), PHG4GDMLWriteStructure::TraverseVolumeTree(), and G4GDMLWriteStructure::TraverseVolumeTree().
size_t G4LogicalVolume::GetNoDaughters () const inline
Referenced by EICG4dRICHDetector::ActivateVolumeTree(), G4GMocrenFileSceneHandler::AddSolid(), G4Region::BelongsTo(), G4SmartVoxelHeader::BuildNodes(), G4GeometryManager::BuildOptimisations(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4SmartVoxelHeader::BuildVoxels(), G4PVReplica::CheckOnlyDaughter(), G4PVPlacement::CheckOverlaps(), CML2WorldConstruction::checkVolumeOverlap(), G4VoxelSafety::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4DrawVoxels::ComputeVoxelPolyhedra(), CML2PhantomConstruction::createPhysicalVolumeNamesList(), G4GeometryManager::DeleteOptimisations(), G4PhysicalVolumeModel::DescribeAndDescend(), G4LogicalVolumeModel::DescribeYourselfTo(), G4DrawVoxels::DrawVoxels(), export_G4LogicalVolume(), PHG4EICMvtxDetector::FindSensor(), PHG4MvtxDetector::FindSensor(), PHG4DisplayAction::FindVolumes(), G4PVReplica::G4PVReplica(), G4SmartVoxelHeader::G4SmartVoxelHeader(), BeastMagnetDetector::InsertVolumes(), AllSiliconTrackerDetector::InsertVolumes(), G4AssemblyVolume::MakeImprint(), BeamLineMagnetDetector::PostConstruction(), CexmcSetup::ReadCalorimeterGeometryData(), G4ReflectionFactory::ReflectDaughters(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4ProductionCutsTable::ScanAndSetCouple(), G4Region::ScanVolumeTree(), G4LBLVtxDetector::SetActiveVolumes(), PHG4GDMLDetector::SetDisplayProperty(), PHG4EICMvtxDetector::SetDisplayProperty(), PHG4MvtxDetector::SetDisplayProperty(), SetFieldManager(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4GeomTestVolume::TestRecursiveOverlap(), PHG4GDMLWriteStructure::TraverseVolumeTree(), and G4GDMLWriteStructure::TraverseVolumeTree().
G4Region* G4LogicalVolume::GetRegion () const inline
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4Region::BelongsTo(), G4RunManagerKernel::CheckRegions(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4ReflectionFactory::CreateReflectedLV(), G4RunManagerKernel::DefineWorldVolume(), G4VFieldModel::DescribeYourselfTo(), G4GlobalFastSimulationManager::DisplayRegion(), export_G4LogicalVolume(), PHG4GDMLWriteStructure::ExportEnergyCuts(), G4GDMLWriteStructure::ExportEnergyCuts(), G4PropagatorInField::FindAndSetFieldManager(), G4FastTrack::FRecordsAffineTransformation(), G4HepRepSceneHandler::getGeometryInstance(), G4VTransitionRadiation::GetMeanFreePath(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), RE06SteppingVerbose::NewStep(), SplitProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4ElectronCapture::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4ReflectionFactory::ReflectLV(), G4ProductionCutsTable::ScanAndSetCouple(), G4GlobalFastSimulationManager::ShowSetup(), G4SteppingManager::Stepping(), G4ParallelWorldProcess::SwitchMaterial(), RE01SteppingAction::UserSteppingAction(), and G4MSSteppingAction::UserSteppingAction().
G4VSensitiveDetector * G4LogicalVolume::GetSensitiveDetector () const
Definition at line 459 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 459 of file G4LogicalVolume.cc
References G4MT_sdetector.
Referenced by G4ParallelWorldProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4ReflectionFactory::CreateReflectedLV(), export_G4LogicalVolume(), G4GDMLWriteStructure::ExportSD(), GFlashHitMaker::make(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VUserDetectorConstruction::SetSensitiveDetector(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
G4double G4LogicalVolume::GetSmartless () const inline
Referenced by G4SmartVoxelHeader::BuildNodes(), and export_G4LogicalVolume().
G4VSolid * G4LogicalVolume::GetSolid () const
Definition at line 403 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 403 of file G4LogicalVolume.cc
References instanceID, G4GeomSplitter< T >::offset, and subInstanceManager.
Referenced by PHG4MicromegasDetector::add_geometry_node(), G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddSolid(), XrayFluoAnalysisManager::analyseStepping(), G4ReplicaNavigation::BackLocate(), G4PhantomParameterisation::BuildContainerSolid(), G4SmartVoxelHeader::BuildNodes(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4SmartVoxelHeader::BuildVoxelsWithinLimits(), G4PVDivision::CheckAndSetParameters(), G4ReplicatedSlice::CheckAndSetParameters(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4GeometryWorkspace::CloneParameterisedSolids(), G4GeometryWorkspace::CloneReplicaSolid(), G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4PhantomParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeSolid(), G4VNestedParameterisation::ComputeSolid(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4Navigator::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4DrawVoxels::ComputeVoxelPolyhedra(), GB06ParallelWorldForSlices::Construct(), G4MIRDLiver::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLeftLegBone::Construct(), G4MIRDRightKidney::Construct(), G4MIRDLeftLung::Construct(), G4MIRDRightLeg::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDSkull::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDHeart::Construct(), G4MIRDThyroid::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDPelvis::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDBrain::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDTrunk::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDPancreas::Construct(), G4MIRDRibCage::Construct(), G4MIRDHead::Construct(), G4MIRDRightBreast::Construct(), G4MIRDUrinaryBladder::Construct(), G4MIRDRightArmBone::Construct(), G4tgbVolume::ConstructG4PhysVol(), G4TheRayTracer::CreateBitMap(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G3Division::CreatePVReplica(), G4ReflectionFactory::CreateReflectedLV(), G4AdjointPosOnPhysVolGenerator::DefinePhysicalVolume(), G4VFieldModel::DescribeYourselfTo(), G4LogicalVolumeModel::DescribeYourselfTo(), G4VisManager::Draw(), G4tgbGeometryDumper::DumpLogVol(), F04SimpleSolenoid::F04SimpleSolenoid(), G4FastTrack::FRecordsAffineTransformation(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), B2PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4HepRepSceneHandler::getGeometryInstance(), G4Navigator::GetGlobalExitNormal(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), GetMass(), FFPrimaryGeneratorAction::GetNeutronSourceCenter(), G4ITTransportationManager::GetParallelWorld(), G4TransportationManager::GetParallelWorld(), G4BOptnForceCommonTruncatedExp::Initialize(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4NavigationLogger::PreComputeStepLog(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), CexmcSetup::ReadCalorimeterGeometryData(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4NavigationLogger::ReportOutsideMother(), G4NavigationLogger::ReportVolumeAndIntersection(), G4VoxelSafety::SafetyForVoxelHeader(), G4VoxelSafety::SafetyForVoxelNode(), G4VisCommandsTouchable::SetNewValue(), G4PVDivision::SetParameterisation(), G4ReplicatedSlice::SetParameterisation(), G4RTPrimaryGeneratorAction::SetUp(), CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::SetupConstructionHook(), PHG4GDMLWriteStructure::TraverseVolumeTree(), and G4GDMLWriteStructure::TraverseVolumeTree().
G4VSolid * G4LogicalVolume::GetSolid (G4LVData & instLVdata) static
Definition at line 398 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 398 of file G4LogicalVolume.cc
References G4LVData::fSolid.
const G4LVManager & G4LogicalVolume::GetSubInstanceManager () static
Definition at line 212 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 212 of file G4LogicalVolume.cc
References subInstanceManager.
Referenced by G4GeometryWorkspace::G4GeometryWorkspace().
G4UserLimits* G4LogicalVolume::GetUserLimits () const inline
Referenced by G4ReflectionFactory::CreateReflectedLV(), export_G4LogicalVolume(), G4StepLimiter::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), and DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength().
const G4VisAttributes* G4LogicalVolume::GetVisAttributes () const inline
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G03ColorWriter::AddExtension(), PHG4BbcDisplayAction::ApplyDisplayAction(), PHG4SectorDisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDisplayAction::ApplyDisplayAction(), PHG4CrystalCalorimeterDisplayAction::ApplyDisplayAction(), PHG4ForwardDualReadoutDisplayAction::ApplyDisplayAction(), PHG4ConeDisplayAction::ApplyDisplayAction(), PHG4BarrelEcalDisplayAction::ApplyDisplayAction(), BeamLineMagnetDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), PHG4ZDCDisplayAction::ApplyDisplayAction(), PHG4EPDDisplayAction::ApplyDisplayAction(), PHG4HybridHomogeneousCalorimeterDisplayAction::ApplyDisplayAction(), PHG4BlockDisplayAction::ApplyDisplayAction(), PHG4InnerHcalDisplayAction::ApplyDisplayAction(), PHG4InttDisplayAction::ApplyDisplayAction(), PHG4RICHDisplayAction::ApplyDisplayAction(), G4JLeicVTXDisplayAction::ApplyDisplayAction(), PHG4PhenixDisplayAction::ApplyDisplayAction(), G4JLeicBeamLineMagnetDisplayAction::ApplyDisplayAction(), G4JLeicDIRCDisplayAction::ApplyDisplayAction(), PHG4OuterHcalDisplayAction::ApplyDisplayAction(), PHG4MvtxDisplayAction::ApplyDisplayAction(), PHG4TpcDisplayAction::ApplyDisplayAction(), PHG4BackwardHcalDisplayAction::ApplyDisplayAction(), PHG4SpacalDisplayAction::ApplyDisplayAction(), PHG4ForwardEcalDisplayAction::ApplyDisplayAction(), PHG4ForwardHcalDisplayAction::ApplyDisplayAction(), PHG4LFHcalDisplayAction::ApplyDisplayAction(), G4EicDircDisplayAction::ApplyDisplayAction(), PHG4TTLDisplayAction::ApplyDisplayAction(), G4ReflectionFactory::CreateReflectedLV(), G4PhysicalVolumeModel::DescribeAndDescend(), RE01CalorimeterHit::Draw(), ExGflashHit::Draw(), RE05CalorimeterHit::Draw(), Par01CalorimeterHit::Draw(), B5HodoscopeHit::Draw(), B5EmCalorimeterHit::Draw(), export_G4LogicalVolume(), G4BuildGeom(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4VisCommandGeometryList::SetNewValue(), and G4VisCommandGeometryRestore::SetNewValue().
G4SmartVoxelHeader* G4LogicalVolume::GetVoxelHeader () const inline
Referenced by G4GeometryManager::BuildOptimisations(), G4VoxelSafety::ComputeSafety(), G4Navigator::ComputeSafety(), G4ITNavigator1::ComputeSafety(), G4ITNavigator2::ComputeSafety(), G4Navigator::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4DrawVoxels::CreatePlacedPolyhedra(), G4GeometryManager::DeleteOptimisations(), export_G4LogicalVolume(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4Navigator::LocateGlobalPointWithinVolume(), G4ITNavigator1::LocateGlobalPointWithinVolume(), G4ITNavigator2::LocateGlobalPointWithinVolume(), and G4RunManager::ReOptimize().
void G4LogicalVolume::InitialiseWorker (G4LogicalVolume * ptrMasterObject, G4VSolid * pSolid, G4VSensitiveDetector * pSDetector)
Definition at line 155 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 155 of file G4LogicalVolume.cc
References AssignFieldManager(), fFieldManager, GetFieldManager(), SetFieldManager(), SetSensitiveDetector(), SetSolid(), G4GeomSplitter< T >::SlaveCopySubInstanceArray(), and subInstanceManager.
Referenced by G4GeometryWorkspace::CloneParameterisedSolids(), G4GeometryWorkspace::CloneReplicaSolid(), and G4GeometryWorkspace::InitialisePhysicalVolumes().
G4bool G4LogicalVolume::IsAncestor (const G4VPhysicalVolume * p) const
Definition at line 500 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 500 of file G4LogicalVolume.cc
References fDaughters, and IsDaughter().
Referenced by export_G4LogicalVolume(), G4WeightWindowStore::IsInWorld(), and G4IStore::IsInWorld().
G4bool G4LogicalVolume::IsDaughter (const G4VPhysicalVolume * p) const inline
Referenced by export_G4LogicalVolume(), and IsAncestor().
G4bool G4LogicalVolume::IsExtended () const virtual
Reimplemented in G4LogicalCrystalVolume.
Definition at line 240 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 240 of file G4LogicalVolume.cc
Referenced by G4Channeling::GetMatData().
G4bool G4LogicalVolume::IsRegion () const inline
Referenced by G4ReflectionFactory::CreateReflectedLV(), and export_G4LogicalVolume().
G4bool G4LogicalVolume::IsRootRegion () const inline
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4GlobalFastSimulationManager::DisplayRegion(), export_G4LogicalVolume(), G4FastTrack::FRecordsAffineTransformation(), G4HepRepSceneHandler::getGeometryInstance(), G4ReflectionFactory::ReflectLV(), and G4Region::ScanVolumeTree().
G4bool G4LogicalVolume::IsToOptimise () const inline
Referenced by G4GeometryManager::BuildOptimisations(), and export_G4LogicalVolume().
void G4LogicalVolume::Lock () inline
G4LogicalVolume& G4LogicalVolume::operator= (const G4LogicalVolume &) delete
G4bool G4LogicalVolume::operator== (const G4LogicalVolume & lv) const
void G4LogicalVolume::PropagateRegion () inline
Referenced by AddDaughter(), and export_G4LogicalVolume().
void G4LogicalVolume::RemoveDaughter (const G4VPhysicalVolume * p)
Definition at line 354 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 354 of file G4LogicalVolume.cc
References fDaughters, fRegion, G4MT_mass, and G4Region::RegionModified().
Referenced by G4PhysicalVolumeStore::DeRegister(), export_G4LogicalVolume(), GB03DetectorConstruction::SetNumberOfLayers(), and RE06DetectorConstruction::SetNumberOfLayers().
void G4LogicalVolume::ResetMass ()
Definition at line 389 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 389 of file G4LogicalVolume.cc
References G4MT_mass.
Referenced by SetSolid().
void G4LogicalVolume::SetBiasWeight (G4double w) inline
Referenced by export_G4LogicalVolume().
void G4LogicalVolume::SetFieldManager (G4FieldManager * pFieldMgr, G4bool forceToAllDaughters)
Definition at line 250 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 250 of file G4LogicalVolume.cc
References AssignFieldManager(), GetDaughter(), GetFieldManager(), G4VPhysicalVolume::GetLogicalVolume(), GetNoDaughters(), and SetFieldManager().
Referenced by AddDaughter(), G4VUserDetectorConstruction::CloneF(), PHG4OuterHcalDetector::ConstructHcalScintillatorAssembly(), PHG4OuterHcalDetector::ConstructOuterHcal(), B5DetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), export_G4LogicalVolume(), G4LogicalVolume(), InitialiseWorker(), BeamLineMagnetDetector::PostConstruction(), SetFieldManager(), and G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster().
void G4LogicalVolume::SetMaterial (G4Material * pMaterial)
Definition at line 438 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 438 of file G4LogicalVolume.cc
References G4MT_mass, and G4MT_material.
Referenced by Par01ParallelWorldForPion::Construct(), export_G4LogicalVolume(), G4LogicalVolume(), G4ScoreSplittingProcess::PostStepDoIt(), DetectorConstruction::SetAbsMaterial(), GB03DetectorConstruction::SetAbsorberMaterial(), RE06DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetAbsorberMaterial(), F03DetectorConstruction::SetAbsorberMaterial(), F02DetectorConstruction::SetAbsorberMaterial(), F01DetectorConstruction::SetAbsorberMaterial(), DetectorConstruction::SetAbsorMaterial(), B2bDetectorConstruction::SetChamberMaterial(), ExN02DetectorConstruction::setChamberMaterial(), ExP01DetectorConstruction::SetChamberMaterial(), DetectorConstruction::SetContainerMaterial(), DetectorConstruction::SetContainMaterial(), GammaRayTelDetectorConstruction::SetConverterMaterial(), DetectorConstruction::SetDetectorMaterial(), DetectorConstruction::SetEcalMaterial(), STCyclotronDetectorConstruction::SetFoilMaterial(), GB03DetectorConstruction::SetGapMaterial(), RE06DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGapMaterial(), DetectorConstruction::SetGasMaterial(), DetectorConstruction0::SetMaterial(), DetectorConstruction::SetMaterial(), ExGflashDetectorConstruction::SetMaterial(), XrayFluoMercuryDetectorConstruction::SetMercuryMaterial(), XrayFluoPlaneDetectorConstruction::SetPlaneMaterial(), ElectronBenchmarkDetector::SetPrimFoilMaterial(), XrayFluoDetectorConstruction::SetSampleMaterial(), DetectorConstruction::SetTankMaterial(), DetectorConstruction::SetTarget1Material(), DetectorConstruction::SetTarget2Material(), B2bDetectorConstruction::SetTargetMaterial(), B2aDetectorConstruction::SetTargetMaterial(), DetectorConstruction::SetTargetMaterial(), ExN02DetectorConstruction::setTargetMaterial(), ExP01DetectorConstruction::SetTargetMaterial(), STCyclotronDetectorConstruction::SetTargetMaterial(), F03DetectorConstruction::SetWorldMaterial(), F01DetectorConstruction::SetWorldMaterial(), F02DetectorConstruction::SetWorldMaterial(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), and STCyclotronDetectorConstruction::UpdateMaterial().
void G4LogicalVolume::SetMaterialCutsCouple (G4MaterialCutsCouple * cuts)
Definition at line 487 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 487 of file G4LogicalVolume.cc
References G4MT_ccouple.
Referenced by export_G4LogicalVolume(), and G4ProductionCutsTable::ScanAndSetCouple().
void G4LogicalVolume::SetName (const G4String & pName) inline
Referenced by export_G4LogicalVolume(), G4LogicalVolume(), and G4GDMLRead::StripNames().
void G4LogicalVolume::SetOptimisation (G4bool optim) inline
Referenced by export_G4LogicalVolume().
void G4LogicalVolume::SetRegion (G4Region * reg) inline
Referenced by G4RunManagerKernel::CheckRegions(), RE01DetectorConstruction::Construct(), ExGflash2ParallelWorld::Construct(), ExGflash1DetectorConstruction::Construct(), ExGflash3DetectorConstruction::Construct(), ExGflashDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), G4RunManagerKernel::DefineWorldVolume(), export_G4LogicalVolume(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2AccSaturn::Jaw1X(), CML2AccSaturn::Jaw1Y(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), G4Region::ScanVolumeTree(), RE06DetectorConstruction::SetupGeometry(), CML2Acc2::target(), and CML2Acc2::vacuumWindow().
void G4LogicalVolume::SetRegionRootFlag (G4bool rreg) inline
Referenced by G4Region::AddRootLogicalVolume(), export_G4LogicalVolume(), and G4Region::RemoveRootLogicalVolume().
void G4LogicalVolume::SetSensitiveDetector (G4VSensitiveDetector * pSDetector)
Definition at line 468 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 468 of file G4LogicalVolume.cc
References fSensitiveDetector, G4MT_sdetector, and G4Threading::IsMasterThread().
Referenced by ExN04CalorimeterROGeometry::Build(), G4VUserDetectorConstruction::CloneSD(), ExN04DetectorConstruction::Construct(), DetectorHarris73::Construct(), DetectorWatase86::Construct(), DetectorBarr90::Construct(), DetectorSimpleALICE::Construct(), DetectorALICE06::Construct(), DetectorBari05::Construct(), FCALHadModule::Construct(), FCALEMModule::Construct(), eRositaDetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), CML2Ph_FullWater::Construct(), ExGflash3ParallelWorld::ConstructSD(), HadrontherapyDetectorROGeometry::ConstructSD(), Par01DetectorConstruction::ConstructSDandField(), G04DetectorConstruction::ConstructSDandField(), GB05DetectorConstruction::ConstructSDandField(), GB07DetectorConstruction::ConstructSDandField(), ExGflash2DetectorConstruction::ConstructSDandField(), ExGflash1DetectorConstruction::ConstructSDandField(), GB06DetectorConstruction::ConstructSDandField(), ExGflashDetectorConstruction::ConstructSDandField(), B5DetectorConstruction::ConstructSDandField(), ElectronBenchmarkDetector::ConstructSDandField(), RE02DetectorConstruction::ConstructSDandField(), RMC01DetectorConstruction::ConstructSimpleGeometry(), export_G4LogicalVolume(), G4LogicalVolume(), InitialiseWorker(), CCalSensitiveDetectors::setSensitive(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), G4ScoringRealWorld::SetupGeometry(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), G4WorkerThread::UpdateGeometryAndPhysicsVectorFromMaster(), and G4VScoringMesh::WorkerConstruct().
void G4LogicalVolume::SetSmartless (G4double s) inline
Referenced by FCALEMModule::Construct(), FCALHadModule::Construct(), DicomPartialDetectorConstruction::ConstructPhantom(), and export_G4LogicalVolume().
void G4LogicalVolume::SetSolid (G4VSolid * pSolid)
Definition at line 412 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 412 of file G4LogicalVolume.cc
References G4MT_solid, and ResetMass().
Referenced by G4LogicalVolume(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), InitialiseWorker(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
void G4LogicalVolume::SetSolid (G4LVData & instLVdata, G4VSolid * pSolid) static
Definition at line 419 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 419 of file G4LogicalVolume.cc
References G4LVData::fMass, and G4LVData::fSolid.
void G4LogicalVolume::SetUserLimits (G4UserLimits * pULimits) inline
Referenced by ExUCNDetectorConstruction::Construct(), B5DetectorConstruction::Construct(), F05DetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), F06DetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), DMXDetectorConstruction::Construct(), WLSDetectorConstruction::ConstructFiber(), TSDetectorConstruction::ConstructWorld(), DetectorConstruction::DefineVolumes(), B2bDetectorConstruction::DefineVolumes(), B2aDetectorConstruction::DefineVolumes(), export_G4LogicalVolume(), F04ElementField::F04ElementField(), G4LogicalVolume(), F04ElementField::SetMaxStep(), and XDetectorConstruction::SetupGeometry().
void G4LogicalVolume::SetVisAttributes (const G4VisAttributes * pVA) inline
Referenced by EICG4LumiDetector::AddCAL(), EICG4LumiDetector::AddCuboid(), AllSi_Al_support_Detector::addDetectorSection(), EicFRichDetector::addDetectorSection(), EICG4LumiDetector::AddExitWindowForV2(), EICG4LumiDetector::AddExitWindowForV3(), EICG4LumiDetector::AddLumiTracker(), EICG4LumiDetector::AddRecCone(), EICG4LumiDetector::AddTriangularTrapezoid(), PHG4EPDDisplayAction::ApplyDisplayAction(), PHG4InttDisplayAction::ApplyDisplayAction(), PHG4HybridHomogeneousCalorimeterDisplayAction::ApplyDisplayAction(), PHG4PhenixDisplayAction::ApplyDisplayAction(), G4JLeicBeamLineMagnetDisplayAction::ApplyDisplayAction(), PHG4InnerHcalDisplayAction::ApplyDisplayAction(), PHG4MvtxDisplayAction::ApplyDisplayAction(), G4JLeicDIRCDisplayAction::ApplyDisplayAction(), PHG4TpcDisplayAction::ApplyDisplayAction(), G4JLeicVTXDisplayAction::ApplyDisplayAction(), PHG4ConeDisplayAction::ApplyDisplayAction(), PHG4TpcEndCapDisplayAction::ApplyDisplayAction(), PHG4OuterHcalDisplayAction::ApplyDisplayAction(), BeamLineMagnetDisplayAction::ApplyDisplayAction(), PHG4BbcDisplayAction::ApplyDisplayAction(), PHG4CylinderDisplayAction::ApplyDisplayAction(), PHG4BlockDisplayAction::ApplyDisplayAction(), PHG4SectorDisplayAction::ApplyDisplayAction(), PHG4ForwardDualReadoutDisplayAction::ApplyDisplayAction(), PHG4RICHDisplayAction::ApplyDisplayAction(), PHG4ZDCDisplayAction::ApplyDisplayAction(), PHG4BarrelEcalDisplayAction::ApplyDisplayAction(), PHG4CrystalCalorimeterDisplayAction::ApplyDisplayAction(), PHG4ForwardEcalDisplayAction::ApplyDisplayAction(), PHG4ForwardHcalDisplayAction::ApplyDisplayAction(), PHG4LFHcalDisplayAction::ApplyDisplayAction(), G4EicDircDisplayAction::ApplyDisplayAction(), PHG4BackwardHcalDisplayAction::ApplyDisplayAction(), PHG4TTLDisplayAction::ApplyDisplayAction(), PHG4SpacalDisplayAction::ApplyDisplayAction(), DetectorConstruction::AtomisticView(), DetectorConstruction::BarycenterView(), UltraFresnelLens::BuildLens(), HadrontherapyModulator::BuildSteps(), DicomPhantomParameterisationColour::ComputeMaterial(), DicomNestedPhantomParameterisation::ComputeMaterial(), CellParameterisation::ComputeMaterial(), ExGflash3ParallelWorld::Construct(), ExN04DetectorConstruction::Construct(), G4MIRDLeftLegBone::Construct(), G4MIRDLiver::Construct(), G4MIRDRightKidney::Construct(), G4MIRDRightScapula::Construct(), G4MIRDBrain::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDPelvis::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDRightLeg::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDSkull::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDThyroid::Construct(), G4MIRDUpperLargeIntestine::Construct(), B03DetectorConstruction::Construct(), G4MIRDHead::Construct(), Par01DetectorConstruction::Construct(), G4MIRDLeftBreast::Construct(), RE01DetectorConstruction::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDPancreas::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightTeste::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDThymus::Construct(), G4MIRDTrunk::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUterus::Construct(), RE05DetectorConstruction::Construct(), G4MIRDRightArmBone::Construct(), G4MIRDUrinaryBladder::Construct(), B01DetectorConstruction::Construct(), B02DetectorConstruction::Construct(), GeometryConstruction::Construct(), ExGflash2ParallelWorld::Construct(), ExGflash2DetectorConstruction::Construct(), B3DetectorConstruction::Construct(), ExGflash3DetectorConstruction::Construct(), ExGflash1DetectorConstruction::Construct(), FCALCryostatVolumes::Construct(), FCALEMModule::Construct(), FCALHadModule::Construct(), eRositaDetectorConstruction::Construct(), ExUCNDetectorConstruction::Construct(), ExGflashDetectorConstruction::Construct(), B5DetectorConstruction::Construct(), LXeDetectorConstruction::Construct(), ExP01DetectorConstruction::Construct(), ExN02DetectorConstruction::Construct(), FCALTestbeamSetup::Construct(), G02DetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), ExErrorDetectorConstruction::Construct(), doiPETDetectorConstruction::Construct(), DMXDetectorConstruction::Construct(), UltraDetectorConstruction::Construct(), RE02DetectorConstruction::Construct(), XrayFluoMercuryDetectorConstruction::ConstructApparate(), XrayFluoPlaneDetectorConstruction::ConstructApparate(), XrayFluoDetectorConstruction::ConstructApparate(), DetectorConstruction::ConstructCalorimeter(), ExN03DetectorConstruction::ConstructCalorimeter(), PurgMagDetectorConstruction::ConstructCalorimeter(), EICG4ZDCStructure::ConstructCrystalTowers(), DetectorConstruction::ConstructDetector(), EICG4ZDCStructure::ConstructEMLayers(), G4tgbVolume::ConstructG4LogVol(), EICG4ZDCStructure::ConstructHCSciLayers(), EICG4ZDCStructure::ConstructHCSiliconLayers(), DetectorConstruction::ConstructLine(), PHG4PSTOFDetector::ConstructMe(), G4JLeicDIRCDetector::ConstructMe(), PHG4ECAPToFDetector::ConstructMe(), EICG4RPDetector::ConstructMe(), PHG4TRDDetector::ConstructMe(), G4JLeicVTXDetector::ConstructMe(), EICG4B0Detector::ConstructMe(), EICG4dRICHDetector::ConstructMe(), EICG4ZDCDetector::ConstructMe(), PHG4EnvelopeDetector::ConstructMe(), PHG4CylinderStripDetector::ConstructMe(), PHG4HcalDetector::ConstructMe(), GammaRayTelDetectorConstruction::ConstructPayload(), DicomNestedParamDetectorConstruction::ConstructPhantom(), DicomRegularDetectorConstruction::ConstructPhantom(), DicomPartialDetectorConstruction::ConstructPhantom(), doiPETDetectorConstruction::ConstructPhantom(), UltraDetectorConstruction::ConstructReflector(), XrayTelDetectorConstruction::ConstructTelescope(), EICG4BwdDetector::ConstructTower(), EICG4B0ECALDetector::ConstructTower(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), UltraDetectorConstruction::ConstructUVscope(), G4HumanPhantomConstruction::ConstructWorld(), DetectorConstruction::ConstructWorld(), TSDetectorConstruction::ConstructWorld(), ElectronBenchmarkDetector::CreateExitWindow(), ElectronBenchmarkDetector::CreateHeliumBag(), ElectronBenchmarkDetector::CreateMonitor(), ElectronBenchmarkDetector::CreatePrimaryFoil(), G4ReflectionFactory::CreateReflectedLV(), ElectronBenchmarkDetector::CreateScorer(), ElectronBenchmarkDetector::CreateWorld(), B2bDetectorConstruction::DefineVolumes(), B2aDetectorConstruction::DefineVolumes(), PHG4Detector::DisplayVolume(), DetectorConstruction::DrawBoundingVolume(), F04ElementField::F04ElementField(), LaserDrivenBeamLine::FaradayCup(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), CML2AccSaturn::flatteningFilter(), G4BuildGeom(), G4GDMLReadStructure::GetWorldVolume(), TrentoPassiveProtonBeamLine::HadrontherapyRidgeFilter(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2AccSaturn::Jaw1Y(), EICG4LumiDetector::MakeTower(), CML2Acc2::MLC(), CML2Acc1::primaryCollimator(), CML2Acc2::primaryCollimator(), DetectorConstruction::ResiduesView(), F04ElementField::SetColor(), PHG4GDMLDetector::SetDisplayProperty(), G4VVisCommandGeometrySet::SetLVVisAtts(), G4VisCommandGeometryRestore::SetNewValue(), G4ScoringCylinder::SetupGeometry(), G4ScoringBox::SetupGeometry(), XDetectorConstruction::SetupGeometry(), RE03DetectorConstruction::SetupGeometry(), RE04DetectorConstruction::SetupGeometry(), GB03DetectorConstruction::SetupGeometry(), RE06DetectorConstruction::SetupGeometry(), CCalG4Able::setVisType(), G4EicDircDetector::SetVisualization(), G3toG4DetectorConstruction::SimpleConstruct(), CML2Acc2::target(), CML2Acc2::vacuumWindow(), LXeMainVolume::VisAttributes(), and G03ColorReader::VolumeRead().
void G4LogicalVolume::SetVisAttributes (const G4VisAttributes & VA)
Definition at line 634 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 634 of file G4LogicalVolume.cc
References fVisAttributes.
void G4LogicalVolume::SetVoxelHeader (G4SmartVoxelHeader * pVoxel) inline
Referenced by G4GeometryManager::BuildOptimisations(), G4GeometryManager::DeleteOptimisations(), export_G4LogicalVolume(), and G4RunManager::ReOptimize().
void G4LogicalVolume::TerminateWorker (G4LogicalVolume * ptrMasterObject)
Definition at line 202 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 202 of file G4LogicalVolume.cc
Referenced by G4GeometryWorkspace::DestroyWorkspace().
G4int G4LogicalVolume::TotalVolumeEntities () const
Definition at line 521 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 521 of file G4LogicalVolume.cc
References fDaughters, G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetMultiplicity(), and TotalVolumeEntities().
Referenced by export_G4LogicalVolume(), and TotalVolumeEntities().
void G4LogicalVolume::UpdateMaterial (G4Material * pMaterial)
Definition at line 448 of file G4LogicalVolume.cc.
View newest version in sPHENIX GitHub at line 448 of file G4LogicalVolume.cc
References G4Region::FindCouple(), fRegion, G4MT_ccouple, G4MT_mass, and G4MT_material.
Referenced by export_G4LogicalVolume(), G4RegularNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
Member Data Documentation
G4double G4LogicalVolume::fBiasWeight = 1.0 private
Definition at line 421 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 421 of file G4LogicalVolume.hh
G4PhysicalVolumeList G4LogicalVolume::fDaughters private
Definition at line 397 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 397 of file G4LogicalVolume.hh
Referenced by AddDaughter(), ClearDaughters(), GetMass(), IsAncestor(), RemoveDaughter(), and TotalVolumeEntities().
EVolume G4LogicalVolume::fDaughtersVolumeType private
Definition at line 401 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 401 of file G4LogicalVolume.hh
Referenced by AddDaughter(), and ChangeDaughtersType().
G4FieldManager* G4LogicalVolume::fFieldManager = nullptr private
Definition at line 435 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 435 of file G4LogicalVolume.hh
Referenced by AssignFieldManager(), G4LogicalVolume(), and InitialiseWorker().
G4bool G4LogicalVolume::fLock = false private
Definition at line 412 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 412 of file G4LogicalVolume.hh
Referenced by ~G4LogicalVolume().
G4String G4LogicalVolume::fName private
Definition at line 399 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 399 of file G4LogicalVolume.hh
Referenced by GetMass().
G4bool G4LogicalVolume::fOptimise = true private
Definition at line 408 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 408 of file G4LogicalVolume.hh
G4Region* G4LogicalVolume::fRegion = nullptr private
Definition at line 419 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 419 of file G4LogicalVolume.hh
Referenced by AddDaughter(), ClearDaughters(), RemoveDaughter(), UpdateMaterial(), and ~G4LogicalVolume().
G4bool G4LogicalVolume::fRootRegion = false private
Definition at line 410 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 410 of file G4LogicalVolume.hh
Referenced by ~G4LogicalVolume().
G4VSensitiveDetector* G4LogicalVolume::fSensitiveDetector = nullptr private
Definition at line 434 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 434 of file G4LogicalVolume.hh
Referenced by G4LogicalVolume(), and SetSensitiveDetector().
G4double G4LogicalVolume::fSmartless = 2.0 private
Definition at line 414 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 414 of file G4LogicalVolume.hh
G4VSolid* G4LogicalVolume::fSolid = nullptr private
Definition at line 433 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 433 of file G4LogicalVolume.hh
Referenced by G4LogicalVolume().
G4UserLimits* G4LogicalVolume::fUserLimits = nullptr private
Definition at line 404 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 404 of file G4LogicalVolume.hh
const G4VisAttributes* G4LogicalVolume::fVisAttributes = nullptr private
Definition at line 417 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 417 of file G4LogicalVolume.hh
Referenced by SetVisAttributes().
G4SmartVoxelHeader* G4LogicalVolume::fVoxel = nullptr private
Definition at line 406 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 406 of file G4LogicalVolume.hh
G4int G4LogicalVolume::instanceID private
Definition at line 424 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 424 of file G4LogicalVolume.hh
Referenced by G4LogicalVolume(), and GetSolid().
G4LVData* G4LogicalVolume::lvdata = nullptr private
Definition at line 436 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 436 of file G4LogicalVolume.hh
Referenced by G4LogicalVolume(), and ~G4LogicalVolume().
G4LVManager G4LogicalVolume::subInstanceManager static private
Definition at line 426 of file G4LogicalVolume.hh.
View newest version in sPHENIX GitHub at line 426 of file G4LogicalVolume.hh
Referenced by Clean(), G4LogicalVolume(), GetSolid(), GetSubInstanceManager(), and InitialiseWorker().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4LogicalVolume.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4LogicalVolume.cc