ECCE @ EIC Software: G4UCNBoundaryProcess Class Reference
G4UCNBoundaryProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/include/G4UCNBoundaryProcess.hh>
Public Member Functions
G4UCNBoundaryProcess (const G4String &processName="UCNBoundaryProcess", G4ProcessType type=fUCN)
virtual ~G4UCNBoundaryProcess ()
G4bool IsApplicable (const G4ParticleDefinition &aParticleType)
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *condition)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep)
G4ThreeVector MRreflect (G4double, G4ThreeVector, G4ThreeVector, G4double, G4double)
G4ThreeVector MRreflectHigh (G4double, G4double, G4double, G4ThreeVector, G4ThreeVector, G4double, G4double, G4double &)
void SetMicroRoughness (G4bool)
G4bool GetMicroRoughness ()
G4UCNBoundaryProcessStatus GetStatus () const
void BoundaryProcessSummary () const
void SetMaterialPropertiesTable1 (G4UCNMaterialPropertiesTable *MPT)
void SetMaterialPropertiesTable2 (G4UCNMaterialPropertiesTable *MPT)
G4double GetTheta_o ()
G4double GetPhi_o ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4UCNBoundaryProcess (const G4UCNBoundaryProcess &right)
G4UCNBoundaryProcess & operator= (const G4UCNBoundaryProcess &right)
G4bool High (G4double, G4double)
G4bool Loss (G4double, G4double, G4double)
G4bool SpinFlip (G4double)
G4double Reflectivity (G4double, G4double)
G4ThreeVector Reflect (G4double, G4ThreeVector, G4ThreeVector)
G4double Transmit (G4double, G4double)
G4ThreeVector LDiffRefl (G4ThreeVector)
G4ThreeVector MRDiffRefl (G4ThreeVector, G4double, G4double, G4ThreeVector, G4double)
G4ThreeVector MRDiffTrans (G4ThreeVector, G4double, G4double, G4ThreeVector, G4double)
G4RotationMatrix GetCoordinateTransformMatrix (G4ThreeVector, G4ThreeVector)
void BoundaryProcessVerbose () const
G4bool InvokeSD (const G4Step *step)
Private Attributes
G4UCNBoundaryProcessMessenger * fMessenger
G4double neV
G4double kCarTolerance
G4UCNBoundaryProcessStatus theStatus
G4Material * Material1
G4Material * Material2
G4UCNMaterialPropertiesTable * aMaterialPropertiesTable1
G4UCNMaterialPropertiesTable * aMaterialPropertiesTable2
G4bool UseMicroRoughnessReflection
G4bool DoMicroRoughnessReflection
G4int nNoMPT
G4int nNoMRT
G4int nNoMRCondition
G4int nAbsorption
G4int nEzero
G4int nFlip
G4int aSpecularReflection
G4int bSpecularReflection
G4int bLambertianReflection
G4int aMRDiffuseReflection
G4int bMRDiffuseReflection
G4int nSnellTransmit
G4int mSnellTransmit
G4int aMRDiffuseTransmit
G4double ftheta_o
G4double fphi_o
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 82 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 82 of file G4UCNBoundaryProcess.hh
Constructor & Destructor Documentation
G4UCNBoundaryProcess::G4UCNBoundaryProcess (const G4String & processName = "UCNBoundaryProcess", G4ProcessType type = fUCN)
Definition at line 67 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 67 of file G4UCNBoundaryProcess.cc
References aMaterialPropertiesTable1, aMaterialPropertiesTable2, aMRDiffuseReflection, aMRDiffuseTransmit, aSpecularReflection, bLambertianReflection, bMRDiffuseReflection, bSpecularReflection, DoMicroRoughnessReflection, eV, fMessenger, fphi_o, ftheta_o, fUCNBoundary, G4cout, G4endl, G4GeometryTolerance::GetInstance(), G4VProcess::GetProcessName(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, Material1, Material2, mSnellTransmit, nAbsorption, neV, nEzero, nFlip, nNoMPT, nNoMRCondition, nNoMRT, nSnellTransmit, G4VProcess::SetProcessSubType(), theStatus, Acts::Undefined, UseMicroRoughnessReflection, and G4VProcess::verboseLevel.
G4UCNBoundaryProcess::~G4UCNBoundaryProcess () virtual
Definition at line 104 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 104 of file G4UCNBoundaryProcess.cc
References fMessenger.
G4UCNBoundaryProcess::G4UCNBoundaryProcess (const G4UCNBoundaryProcess & right) private
Member Function Documentation
void G4UCNBoundaryProcess::BoundaryProcessSummary (void) const
Definition at line 943 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 943 of file G4UCNBoundaryProcess.cc
References aMRDiffuseReflection, aMRDiffuseTransmit, aSpecularReflection, bLambertianReflection, bMRDiffuseReflection, bSpecularReflection, G4cout, G4endl, mSnellTransmit, nAbsorption, nEzero, nFlip, nNoMPT, nNoMRCondition, nNoMRT, and nSnellTransmit.
Referenced by ExUCNRunAction::EndOfRunAction().
void G4UCNBoundaryProcess::BoundaryProcessVerbose () const private
Definition at line 909 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 909 of file G4UCNBoundaryProcess.cc
References Absorption, Ezero, Flip, G4cout, G4endl, LambertianReflection, MRDiffuseReflection, MRDiffuseTransmit, NoMPT, NoMRCondition, NoMRT, NotAtBoundary, SameMaterial, SnellTransmit, SpecularReflection, StepTooSmall, theStatus, and Acts::Undefined.
Referenced by MRreflect(), MRreflectHigh(), PostStepDoIt(), and Reflect().
G4RotationMatrix G4UCNBoundaryProcess::GetCoordinateTransformMatrix (G4ThreeVector Normal, G4ThreeVector direction) private
Definition at line 878 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 878 of file G4UCNBoundaryProcess.cc
References degree, CLHEP::Hep3Vector::perpPart(), CLHEP::Hep3Vector::rotate(), and CLHEP::Hep3Vector::setMag().
Referenced by MRDiffRefl(), and MRDiffTrans().
G4double G4UCNBoundaryProcess::GetMeanFreePath (const G4Track & aTrack, G4double , G4ForceCondition * condition) virtual
Implements G4VDiscreteProcess.
Definition at line 456 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 456 of file G4UCNBoundaryProcess.cc
References DBL_MAX, and Forced.
G4bool G4UCNBoundaryProcess::GetMicroRoughness () inline
Definition at line 247 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 247 of file G4UCNBoundaryProcess.hh
References UseMicroRoughnessReflection.
G4double G4UCNBoundaryProcess::GetPhi_o () inline
Definition at line 212 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 212 of file G4UCNBoundaryProcess.hh
References fphi_o.
G4UCNBoundaryProcessStatus G4UCNBoundaryProcess::GetStatus () const inline
Definition at line 227 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 227 of file G4UCNBoundaryProcess.hh
References theStatus.
G4double G4UCNBoundaryProcess::GetTheta_o () inline
Definition at line 211 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 211 of file G4UCNBoundaryProcess.hh
References ftheta_o.
G4bool G4UCNBoundaryProcess::High (G4double Energy, G4double FermiPotDiff) inline private
Definition at line 233 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 233 of file G4UCNBoundaryProcess.hh
Referenced by PostStepDoIt().
G4bool G4UCNBoundaryProcess::InvokeSD (const G4Step * step) private
Definition at line 976 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 976 of file G4UCNBoundaryProcess.cc
References G4Step::AddTotalEnergyDeposit(), G4Track::GetKineticEnergy(), G4Step::GetPostStepPoint(), G4StepPoint::GetSensitiveDetector(), G4Step::GetTrack(), and G4VSensitiveDetector::Hit().
G4bool G4UCNBoundaryProcess::IsApplicable (const G4ParticleDefinition & aParticleType) inline virtual
Reimplemented from G4VProcess.
Definition at line 221 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 221 of file G4UCNBoundaryProcess.hh
References G4Neutron::NeutronDefinition().
G4ThreeVector G4UCNBoundaryProcess::LDiffRefl (G4ThreeVector Normal) private
Definition at line 860 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 860 of file G4UCNBoundaryProcess.cc
References G4cout, G4endl, G4UniformRand, momentum, pi, CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::setRThetaPhi(), and CLHEP::Hep3Vector::unit().
Referenced by Reflect().
G4bool G4UCNBoundaryProcess::Loss (G4double pUpScatter, G4double theVelocityNormal, G4double FermiPot) private
Definition at line 465 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 465 of file G4UCNBoundaryProcess.cc
References aMaterialPropertiesTable2, b, source.hepunit::c_squared, DoMicroRoughnessReflection, G4UniformRand, G4UCNMaterialPropertiesTable::GetCorrLen(), G4UCNMaterialPropertiesTable::GetRMS(), source.hepunit::hbar_Planck, source.hepunit::neutron_mass_c2, and w.
Referenced by PostStepDoIt().
G4ThreeVector G4UCNBoundaryProcess::MRDiffRefl (G4ThreeVector Normal, G4double Energy, G4double FermiPot, G4ThreeVector OldMomentum, G4double pDiffuse) private
Definition at line 695 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 695 of file G4UCNBoundaryProcess.cc
References aMaterialPropertiesTable2, fphi_o, ftheta_o, G4cout, G4endl, G4UniformRand, GetCoordinateTransformMatrix(), momentum, pi, CLHEP::Hep3Vector::polarAngle(), CLHEP::Hep3Vector::setRThetaPhi(), and CLHEP::Hep3Vector::unit().
Referenced by MRreflect(), and MRreflectHigh().
G4ThreeVector G4UCNBoundaryProcess::MRDiffTrans (G4ThreeVector Normal, G4double Energy, G4double FermiPot, G4ThreeVector OldMomentum, G4double pDiffuseTrans) private
Definition at line 777 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 777 of file G4UCNBoundaryProcess.cc
References aMaterialPropertiesTable2, G4cout, G4endl, G4UniformRand, GetCoordinateTransformMatrix(), momentum, pi, CLHEP::Hep3Vector::polarAngle(), CLHEP::Hep3Vector::setRThetaPhi(), and CLHEP::Hep3Vector::unit().
Referenced by MRreflectHigh().
G4ThreeVector G4UCNBoundaryProcess::MRreflect (G4double pDiffuse, G4ThreeVector OldMomentum, G4ThreeVector Normal, G4double Energy, G4double FermiPot)
Definition at line 542 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 542 of file G4UCNBoundaryProcess.cc
References bMRDiffuseReflection, BoundaryProcessVerbose(), bSpecularReflection, G4UniformRand, MRDiffRefl(), MRDiffuseReflection, SpecularReflection, theStatus, CLHEP::Hep3Vector::unit(), and G4VProcess::verboseLevel.
Referenced by PostStepDoIt().
G4ThreeVector G4UCNBoundaryProcess::MRreflectHigh (G4double pDiffuse, G4double pDiffuseTrans, G4double pLoss, G4ThreeVector OldMomentum, G4ThreeVector Normal, G4double Energy, G4double FermiPot, G4double & Enew)
Definition at line 586 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 586 of file G4UCNBoundaryProcess.cc
References aMRDiffuseReflection, aMRDiffuseTransmit, aSpecularReflection, BoundaryProcessVerbose(), source.hepunit::c_squared, Ezero, G4cout, G4endl, G4UniformRand, MRDiffRefl(), MRDiffTrans(), MRDiffuseReflection, MRDiffuseTransmit, mSnellTransmit, source.hepunit::neutron_mass_c2, nEzero, Reflectivity(), SnellTransmit, SpecularReflection, theStatus, CLHEP::Hep3Vector::unit(), and G4VProcess::verboseLevel.
Referenced by PostStepDoIt().
G4UCNBoundaryProcess& G4UCNBoundaryProcess::operator= (const G4UCNBoundaryProcess & right) private
G4VParticleChange * G4UCNBoundaryProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 110 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 110 of file G4UCNBoundaryProcess.cc
References Absorption, aMaterialPropertiesTable1, aMaterialPropertiesTable2, CLHEP::Hep3Vector::angle(), G4VProcess::aParticleChange, BoundaryProcessVerbose(), source.hepunit::c_light, degree, DoMicroRoughnessReflection, EventMustBeAborted, fGeomBoundary, Flip, fStopAndKill, G4cout, G4endl, G4Exception(), G4UniformRand, G4MaterialPropertiesTable::GetConstProperty(), G4Track::GetDynamicParticle(), G4ParticleChange::GetEnergy(), G4ParallelWorldProcess::GetHyperStep(), G4ParallelWorldProcess::GetHypNavigatorID(), G4Track::GetKineticEnergy(), G4StepPoint::GetMaterial(), G4UCNMaterialPropertiesTable::GetMicroRoughnessTable(), G4Track::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4StepPoint::GetPhysicalVolume(), G4DynamicParticle::GetPolarization(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Track::GetStepLength(), G4StepPoint::GetStepStatus(), G4TransportationManager::GetTransportationManager(), G4Track::GetVelocity(), High(), G4ParticleChange::Initialize(), kCarTolerance, Loss(), mass, Material1, Material2, MRreflect(), MRreflectHigh(), nAbsorption, source.hepunit::neutron_mass_c2, neV, nFlip, nNoMPT, nNoMRCondition, nNoMRT, NoMPT, NoMRCondition, NoMRT, NotAtBoundary, nSnellTransmit, G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4ParticleChange::ProposePolarization(), G4VParticleChange::ProposeTrackStatus(), G4ParticleChange::ProposeVelocity(), Reflect(), Reflectivity(), SameMaterial, SnellTransmit, SpinFlip(), StepTooSmall, theStatus, Transmit(), CLHEP::Hep3Vector::unit(), UseMicroRoughnessReflection, Acts::IntegrationTest::valid(), and G4VProcess::verboseLevel.
G4ThreeVector G4UCNBoundaryProcess::Reflect (G4double pDiffuse, G4ThreeVector OldMomentum, G4ThreeVector Normal) private
Definition at line 511 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 511 of file G4UCNBoundaryProcess.cc
References bLambertianReflection, BoundaryProcessVerbose(), bSpecularReflection, G4UniformRand, LambertianReflection, LDiffRefl(), SpecularReflection, theStatus, CLHEP::Hep3Vector::unit(), and G4VProcess::verboseLevel.
Referenced by PostStepDoIt().
G4double G4UCNBoundaryProcess::Reflectivity (G4double FermiPot, G4double Enormal) private
Definition at line 503 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 503 of file G4UCNBoundaryProcess.cc
References r.
Referenced by MRreflectHigh(), and PostStepDoIt().
void G4UCNBoundaryProcess::SetMaterialPropertiesTable1 (G4UCNMaterialPropertiesTable * MPT) inline
Definition at line 205 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 205 of file G4UCNBoundaryProcess.hh
References aMaterialPropertiesTable1.
void G4UCNBoundaryProcess::SetMaterialPropertiesTable2 (G4UCNMaterialPropertiesTable * MPT) inline
Definition at line 208 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 208 of file G4UCNBoundaryProcess.hh
References aMaterialPropertiesTable2.
void G4UCNBoundaryProcess::SetMicroRoughness (G4bool active) inline
Definition at line 241 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 241 of file G4UCNBoundaryProcess.hh
References active, and UseMicroRoughnessReflection.
Referenced by ExUCNExtraPhysics::ConstructUCN().
G4bool G4UCNBoundaryProcess::SpinFlip (G4double pSpinFlip) private
Definition at line 498 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 498 of file G4UCNBoundaryProcess.cc
References G4UniformRand.
Referenced by PostStepDoIt().
G4double G4UCNBoundaryProcess::Transmit (G4double FermiPot, G4double Energy) private
Definition at line 855 of file G4UCNBoundaryProcess.cc.
View newest version in sPHENIX GitHub at line 855 of file G4UCNBoundaryProcess.cc
Referenced by PostStepDoIt().
Member Data Documentation
G4UCNMaterialPropertiesTable* G4UCNBoundaryProcess::aMaterialPropertiesTable1 private
Definition at line 135 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 135 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), PostStepDoIt(), and SetMaterialPropertiesTable1().
G4UCNMaterialPropertiesTable* G4UCNBoundaryProcess::aMaterialPropertiesTable2 private
Definition at line 137 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 137 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), Loss(), MRDiffRefl(), MRDiffTrans(), PostStepDoIt(), and SetMaterialPropertiesTable2().
G4int G4UCNBoundaryProcess::aMRDiffuseReflection private
Definition at line 190 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 190 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and MRreflectHigh().
G4int G4UCNBoundaryProcess::aMRDiffuseTransmit private
Definition at line 192 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 192 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and MRreflectHigh().
G4int G4UCNBoundaryProcess::aSpecularReflection private
Definition at line 188 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 188 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and MRreflectHigh().
G4int G4UCNBoundaryProcess::bLambertianReflection private
Definition at line 189 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 189 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and Reflect().
G4int G4UCNBoundaryProcess::bMRDiffuseReflection private
Definition at line 190 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 190 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and MRreflect().
G4int G4UCNBoundaryProcess::bSpecularReflection private
Definition at line 188 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 188 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), MRreflect(), and Reflect().
G4bool G4UCNBoundaryProcess::DoMicroRoughnessReflection private
Definition at line 140 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 140 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), Loss(), and PostStepDoIt().
G4UCNBoundaryProcessMessenger* G4UCNBoundaryProcess::fMessenger private
Definition at line 123 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 123 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), and ~G4UCNBoundaryProcess().
G4double G4UCNBoundaryProcess::fphi_o private
Definition at line 194 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 194 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), GetPhi_o(), and MRDiffRefl().
G4double G4UCNBoundaryProcess::ftheta_o private
Definition at line 194 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 194 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), GetTheta_o(), and MRDiffRefl().
G4double G4UCNBoundaryProcess::kCarTolerance private
Definition at line 127 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 127 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), and PostStepDoIt().
G4Material* G4UCNBoundaryProcess::Material1 private
Definition at line 131 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 131 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), and PostStepDoIt().
G4Material* G4UCNBoundaryProcess::Material2 private
Definition at line 132 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 132 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), and PostStepDoIt().
G4int G4UCNBoundaryProcess::mSnellTransmit private
Definition at line 191 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 191 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and MRreflectHigh().
G4int G4UCNBoundaryProcess::nAbsorption private
Definition at line 187 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 187 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and PostStepDoIt().
G4double G4UCNBoundaryProcess::neV private
Definition at line 125 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 125 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), and PostStepDoIt().
G4int G4UCNBoundaryProcess::nEzero private
Definition at line 187 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 187 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and MRreflectHigh().
G4int G4UCNBoundaryProcess::nFlip private
Definition at line 187 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 187 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and PostStepDoIt().
G4int G4UCNBoundaryProcess::nNoMPT private
Definition at line 186 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 186 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and PostStepDoIt().
G4int G4UCNBoundaryProcess::nNoMRCondition private
Definition at line 186 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 186 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and PostStepDoIt().
G4int G4UCNBoundaryProcess::nNoMRT private
Definition at line 186 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 186 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and PostStepDoIt().
G4int G4UCNBoundaryProcess::nSnellTransmit private
Definition at line 191 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 191 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessSummary(), G4UCNBoundaryProcess(), and PostStepDoIt().
G4UCNBoundaryProcessStatus G4UCNBoundaryProcess::theStatus private
Definition at line 129 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 129 of file G4UCNBoundaryProcess.hh
Referenced by BoundaryProcessVerbose(), G4UCNBoundaryProcess(), GetStatus(), MRreflect(), MRreflectHigh(), PostStepDoIt(), and Reflect().
G4bool G4UCNBoundaryProcess::UseMicroRoughnessReflection private
Definition at line 139 of file G4UCNBoundaryProcess.hh.
View newest version in sPHENIX GitHub at line 139 of file G4UCNBoundaryProcess.hh
Referenced by G4UCNBoundaryProcess(), GetMicroRoughness(), PostStepDoIt(), and SetMicroRoughness().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/include/G4UCNBoundaryProcess.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/src/G4UCNBoundaryProcess.cc