ECCE @ EIC Software: B3bRun Class Reference
B3bRun Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/include/B3bRun.hh>
Public Member Functions
B3bRun ()
virtual ~B3bRun ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
G4int GetNbGoodEvents () const
G4double GetSumDose () const
G4StatAnalysis GetStatDose () const
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Attributes
G4int fCollID_cryst
G4int fCollID_patient
G4int fPrintModulo
G4int fGoodEvents
G4double fSumDose
G4StatAnalysis fStatDose
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Run class
In RecordEvent() there is collected information event per event from Hits Collections, and accumulated statistic for the run
Definition at line 42 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 42 of file B3bRun.hh
Constructor & Destructor Documentation
B3bRun::B3bRun ()
Definition at line 42 of file B3bRun.cc.
View newest version in sPHENIX GitHub at line 42 of file B3bRun.cc
B3bRun::~B3bRun () virtual
Definition at line 54 of file B3bRun.cc.
View newest version in sPHENIX GitHub at line 54 of file B3bRun.cc
Member Function Documentation
G4int B3bRun::GetNbGoodEvents () const inline
Definition at line 52 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 52 of file B3bRun.hh
References fGoodEvents.
Referenced by B3bRunAction::EndOfRunAction().
G4StatAnalysis B3bRun::GetStatDose () const inline
Definition at line 54 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 54 of file B3bRun.hh
References fStatDose.
Referenced by B3bRunAction::EndOfRunAction().
G4double B3bRun::GetSumDose () const inline
Definition at line 53 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 53 of file B3bRun.hh
References fSumDose.
Referenced by B3bRunAction::EndOfRunAction().
void B3bRun::Merge (const G4Run * aRun) virtual
Reimplemented from G4Run.
Definition at line 119 of file B3bRun.cc.
View newest version in sPHENIX GitHub at line 119 of file B3bRun.cc
References fGoodEvents, fStatDose, fSumDose, and G4Run::Merge().
void B3bRun::RecordEvent (const G4Event * event) virtual
G4int copyNb = (itr->first); G4cout << G4endl << " cryst" << copyNb << ": " << edep/keV << " keV ";
G4int copyNb = (itr->first);
Reimplemented from G4Run.
Definition at line 59 of file B3bRun.cc.
View newest version in sPHENIX GitHub at line 59 of file B3bRun.cc
References dose, edep, fCollID_cryst, fCollID_patient, fGoodEvents, fPrintModulo, fStatDose, fSumDose, G4cout, G4endl, G4SDManager::GetCollectionID(), G4HCofThisEvent::GetHC(), G4VTHitsMap< T, Map_t >::GetMap(), G4SDManager::GetSDMpointer(), keV, and G4Run::RecordEvent().
Member Data Documentation
G4int B3bRun::fCollID_cryst private
Definition at line 57 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 57 of file B3bRun.hh
Referenced by RecordEvent().
G4int B3bRun::fCollID_patient private
Definition at line 58 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 58 of file B3bRun.hh
Referenced by RecordEvent().
G4int B3bRun::fGoodEvents private
Definition at line 60 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 60 of file B3bRun.hh
Referenced by GetNbGoodEvents(), Merge(), and RecordEvent().
G4int B3bRun::fPrintModulo private
Definition at line 59 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 59 of file B3bRun.hh
Referenced by RecordEvent().
G4StatAnalysis B3bRun::fStatDose private
Definition at line 62 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 62 of file B3bRun.hh
Referenced by GetStatDose(), Merge(), and RecordEvent().
G4double B3bRun::fSumDose private
Definition at line 61 of file B3bRun.hh.
View newest version in sPHENIX GitHub at line 61 of file B3bRun.hh
Referenced by GetSumDose(), Merge(), and RecordEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/include/B3bRun.hh
geant4/tree/geant4-10.6-release/examples/basic/B3/B3b/src/B3bRun.cc