ECCE @ EIC Software: G4ComponentAntiNuclNuclearXS Class Reference
G4ComponentAntiNuclNuclearXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ComponentAntiNuclNuclearXS.hh>
Public Member Functions
G4ComponentAntiNuclNuclearXS ()
virtual ~G4ComponentAntiNuclNuclearXS ()
virtual G4double GetTotalIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A)
virtual G4double GetTotalElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double A)
virtual G4double GetInelasticIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A)
virtual G4double GetInelasticElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double A)
virtual G4double GetElasticElementCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4double A)
virtual G4double GetElasticIsotopeCrossSection (const G4ParticleDefinition *aParticle, G4double kinEnergy, G4int Z, G4int A)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void CrossSectionDescription (std::ostream &) const
G4double GetAntiHadronNucleonTotCrSc (const G4ParticleDefinition *aParticle, G4double kinEnergy)
G4double GetAntiHadronNucleonElCrSc (const G4ParticleDefinition *aParticle, G4double kinEnergy)
Public Member Functions inherited from G4VComponentCrossSection
G4VComponentCrossSection (const G4String &nam="")
virtual ~G4VComponentCrossSection ()
G4double GetTotalElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
G4double GetInelasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
G4double GetElasticElementCrossSection (const G4ParticleDefinition *, G4double kinEnergy, const G4Element *)
virtual G4double ComputeQuasiElasticRatio (const G4ParticleDefinition *, G4double kinEnergy, G4int, G4int)
virtual void Description (std::ostream &) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
const G4String & GetName () const
Private Attributes
G4double fRadiusEff
G4double fRadiusNN2
G4double fTotalXsc
G4double fElasticXsc
G4double fInelasticXsc
G4double fAntiHadronNucleonTotXsc
G4double fAntiHadronNucleonElXsc
G4double Elab
G4double S
G4double SqrtS
G4double Mn
G4double b0
G4double b2
G4double SqrtS0
G4double S0
G4double R0
G4ParticleDefinition * theAProton
G4ParticleDefinition * theANeutron
G4ParticleDefinition * theADeuteron
G4ParticleDefinition * theATriton
G4ParticleDefinition * theAAlpha
G4ParticleDefinition * theAHe3
Detailed Description
Definition at line 59 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ComponentAntiNuclNuclearXS.hh
Constructor & Destructor Documentation
G4ComponentAntiNuclNuclearXS::G4ComponentAntiNuclNuclearXS ()
Definition at line 49 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ComponentAntiNuclNuclearXS.cc
References G4AntiAlpha::AntiAlpha(), G4AntiDeuteron::AntiDeuteron(), G4AntiHe3::AntiHe3(), G4AntiNeutron::AntiNeutron(), G4AntiProton::AntiProton(), G4AntiTriton::AntiTriton(), b0, b2, Mn, R0, S0, SqrtS0, theAAlpha, theADeuteron, theAHe3, theANeutron, theAProton, and theATriton.
G4ComponentAntiNuclNuclearXS::~G4ComponentAntiNuclNuclearXS () virtual
Definition at line 73 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ComponentAntiNuclNuclearXS.cc
Member Function Documentation
virtual void G4ComponentAntiNuclNuclearXS::BuildPhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 76 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ComponentAntiNuclNuclearXS.hh
void G4ComponentAntiNuclNuclearXS::CrossSectionDescription (std::ostream & outFile) const virtual
Definition at line 326 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 326 of file G4ComponentAntiNuclNuclearXS.cc
virtual void G4ComponentAntiNuclNuclearXS::DumpPhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented from G4VComponentCrossSection.
Definition at line 77 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ComponentAntiNuclNuclearXS.hh
G4double G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonElCrSc (const G4ParticleDefinition * aParticle, G4double kinEnergy)
Definition at line 301 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 301 of file G4ComponentAntiNuclNuclearXS.cc
References C(), d1, d2, fAntiHadronNucleonElXsc, G4Log(), GetAntiHadronNucleonTotCrSc(), G4Pow::GetInstance(), Mn, G4Pow::powA(), R0, S, S0, and SqrtS.
G4double G4ComponentAntiNuclNuclearXS::GetAntiHadronNucleonTotCrSc (const G4ParticleDefinition * aParticle, G4double kinEnergy)
Definition at line 264 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 264 of file G4ComponentAntiNuclNuclearXS.cc
References kdfinder::abs(), B(), C(), d1, d2, G4Log(), G4ParticleDefinition::GetBaryonNumber(), G4Pow::GetInstance(), G4ParticleDefinition::GetPDGMass(), GeV, momentum, G4Pow::powA(), and S().
Referenced by GetAntiHadronNucleonElCrSc(), and G4AntiNuclElastic::SampleInvariantT().
G4double G4ComponentAntiNuclNuclearXS::GetElasticElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double A) virtual
Implements G4VComponentCrossSection.
Definition at line 240 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 240 of file G4ComponentAntiNuclNuclearXS.cc
Referenced by G4AntiNuclElastic::SampleInvariantT().
G4double G4ComponentAntiNuclNuclearXS::GetElasticIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A) virtual
Implements G4VComponentCrossSection.
Definition at line 254 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 254 of file G4ComponentAntiNuclNuclearXS.cc
G4double G4ComponentAntiNuclNuclearXS::GetInelasticElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double A) virtual
Implements G4VComponentCrossSection.
Definition at line 161 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 161 of file G4ComponentAntiNuclNuclearXS.cc
References kdfinder::abs(), G4Log(), G4ParticleDefinition::GetBaryonNumber(), G4Pow::GetInstance(), millibarn, pi, and G4Pow::powA().
G4double G4ComponentAntiNuclNuclearXS::GetInelasticIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A) virtual
Implements G4VComponentCrossSection.
Definition at line 229 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 229 of file G4ComponentAntiNuclNuclearXS.cc
G4double G4ComponentAntiNuclNuclearXS::GetTotalElementCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4double A) virtual
Implements G4VComponentCrossSection.
Definition at line 83 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ComponentAntiNuclNuclearXS.cc
References kdfinder::abs(), G4Log(), G4ParticleDefinition::GetBaryonNumber(), G4Pow::GetInstance(), millibarn, pi, and G4Pow::powA().
Referenced by G4AntiNuclElastic::SampleInvariantT().
G4double G4ComponentAntiNuclNuclearXS::GetTotalIsotopeCrossSection (const G4ParticleDefinition * aParticle, G4double kinEnergy, G4int Z, G4int A) virtual
Implements G4VComponentCrossSection.
Definition at line 151 of file G4ComponentAntiNuclNuclearXS.cc.
View newest version in sPHENIX GitHub at line 151 of file G4ComponentAntiNuclNuclearXS.cc
Member Data Documentation
G4double G4ComponentAntiNuclNuclearXS::b0 private
Definition at line 90 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
G4double G4ComponentAntiNuclNuclearXS::b2 private
Definition at line 90 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
G4double G4ComponentAntiNuclNuclearXS::Elab private
Definition at line 89 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ComponentAntiNuclNuclearXS.hh
G4double G4ComponentAntiNuclNuclearXS::fAntiHadronNucleonElXsc private
Definition at line 88 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by GetAntiHadronNucleonElCrSc().
G4double G4ComponentAntiNuclNuclearXS::fAntiHadronNucleonTotXsc private
Definition at line 88 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ComponentAntiNuclNuclearXS.hh
G4double G4ComponentAntiNuclNuclearXS::fElasticXsc private
Definition at line 87 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ComponentAntiNuclNuclearXS.hh
G4double G4ComponentAntiNuclNuclearXS::fInelasticXsc private
Definition at line 87 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ComponentAntiNuclNuclearXS.hh
G4double G4ComponentAntiNuclNuclearXS::fRadiusEff private
Definition at line 85 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ComponentAntiNuclNuclearXS.hh
G4double G4ComponentAntiNuclNuclearXS::fRadiusNN2 private
Definition at line 86 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ComponentAntiNuclNuclearXS.hh
G4double G4ComponentAntiNuclNuclearXS::fTotalXsc private
Definition at line 87 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ComponentAntiNuclNuclearXS.hh
G4double G4ComponentAntiNuclNuclearXS::Mn private
Definition at line 90 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS(), and GetAntiHadronNucleonElCrSc().
G4double G4ComponentAntiNuclNuclearXS::R0 private
Definition at line 90 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS(), and GetAntiHadronNucleonElCrSc().
G4double G4ComponentAntiNuclNuclearXS::S private
Definition at line 89 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by GetAntiHadronNucleonElCrSc().
G4double G4ComponentAntiNuclNuclearXS::S0 private
Definition at line 90 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS(), and GetAntiHadronNucleonElCrSc().
G4double G4ComponentAntiNuclNuclearXS::SqrtS private
Definition at line 89 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by GetAntiHadronNucleonElCrSc().
G4double G4ComponentAntiNuclNuclearXS::SqrtS0 private
Definition at line 90 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
G4ParticleDefinition* G4ComponentAntiNuclNuclearXS::theAAlpha private
Definition at line 95 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
G4ParticleDefinition* G4ComponentAntiNuclNuclearXS::theADeuteron private
Definition at line 93 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
G4ParticleDefinition* G4ComponentAntiNuclNuclearXS::theAHe3 private
Definition at line 96 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
G4ParticleDefinition* G4ComponentAntiNuclNuclearXS::theANeutron private
Definition at line 92 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
G4ParticleDefinition* G4ComponentAntiNuclNuclearXS::theAProton private
Definition at line 91 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
G4ParticleDefinition* G4ComponentAntiNuclNuclearXS::theATriton private
Definition at line 94 of file G4ComponentAntiNuclNuclearXS.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ComponentAntiNuclNuclearXS.hh
Referenced by G4ComponentAntiNuclNuclearXS().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ComponentAntiNuclNuclearXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ComponentAntiNuclNuclearXS.cc