ECCE @ EIC Software: G4VMultipleScattering Class Reference
G4VMultipleScattering Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VMultipleScattering.hh>
Public Member Functions
G4VMultipleScattering (const G4String &name="msc", G4ProcessType type=fElectromagnetic)
virtual ~G4VMultipleScattering ()
virtual G4bool IsApplicable (const G4ParticleDefinition &p) override=0
virtual void PrintInfo ()
virtual void ProcessDescription (std::ostream &outFile) const override
void PreparePhysicsTable (const G4ParticleDefinition &) override
void BuildPhysicsTable (const G4ParticleDefinition &) override
G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii=false) override
G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &directory, G4bool ascii) override
void StartTracking (G4Track *) override
G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4double currentMinimalStep, G4double &currentSafety, G4GPILSelection *selection) override
G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double previousStepSize, G4ForceCondition *condition) override
G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &) override
G4double ContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimalStep, G4double &currentSafety)
G4VEmModel * SelectModel (G4double kinEnergy, size_t idx)
void AddEmModel (G4int order, G4VEmModel *, const G4Region *region=nullptr)
void SetEmModel (G4VMscModel *, size_t index=0)
G4VMscModel * EmModel (size_t index=0) const
G4VEmModel * GetModelByIndex (G4int idx=0, G4bool ver=false) const
void SetIonisation (G4VEnergyLossProcess *)
G4bool LateralDisplasmentFlag () const
void SetLateralDisplasmentFlag (G4bool val)
G4double Skin () const
void SetSkin (G4double val)
G4double RangeFactor () const
void SetRangeFactor (G4double val)
G4double GeomFactor () const
G4double PolarAngleLimit () const
G4MscStepLimitType StepLimitType () const
void SetStepLimitType (G4MscStepLimitType val)
G4double LowestKinEnergy () const
void SetLowestKinEnergy (G4double val)
const G4ParticleDefinition * FirstParticle () const
Public Member Functions inherited from G4VContinuousDiscreteProcess
G4VContinuousDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VContinuousDiscreteProcess (G4VContinuousDiscreteProcess &)
virtual ~G4VContinuousDiscreteProcess ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual void InitialiseProcess (const G4ParticleDefinition *)=0
virtual void StreamProcessInfo (std::ostream &) const
G4double GetMeanFreePath (const G4Track &track, G4double, G4ForceCondition *condition) override
G4double GetContinuousStepLimit (const G4Track &track, G4double previousStepSize, G4double currentMinimalStep, G4double &currentSafety) override
G4int NumberOfModels () const
Protected Member Functions inherited from G4VContinuousDiscreteProcess
void SetGPILSelection (G4GPILSelection selection)
G4GPILSelection GetGPILSelection () const
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4ParticleChangeForMSC fParticleChange
Private Member Functions
G4VMultipleScattering (G4VMultipleScattering &)=delete
G4VMultipleScattering & operator= (const G4VMultipleScattering &right)=delete
void StreamInfo (std::ostream &outFile, const G4ParticleDefinition &, G4bool rst=false) const
Private Attributes
G4EmModelManager * modelManager
G4LossTableManager * emManager
G4EmParameters * theParameters
G4SafetyHelper * safetyHelper
std::vector< G4VMscModel * > mscModels
G4int numberOfModels
const G4ParticleDefinition * firstParticle
const G4ParticleDefinition * currParticle
G4MscStepLimitType stepLimit
G4double facrange
G4double lowestKinEnergy
G4bool latDisplacement
G4bool isIon
G4bool fDispBeyondSafety
G4VMscModel * currentModel
G4VEnergyLossProcess * fIonisation
G4double geomMin
G4double minDisplacement2
G4double physStepLimit
G4double tPathLength
G4double gPathLength
G4ThreeVector fNewPosition
G4ThreeVector fNewDirection
G4bool fPositionChanged
G4bool isActive
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Detailed Description
Definition at line 91 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VMultipleScattering.hh
Constructor & Destructor Documentation
G4VMultipleScattering::G4VMultipleScattering (const G4String & name = "msc", G4ProcessType type = fElectromagnetic)
Definition at line 90 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 90 of file G4VMultipleScattering.cc
References currentModel, emManager, CLHEP::eV, fIonisation, firstParticle, fMultipleScattering, fParticleChange, fPositionChanged, G4GenericIon::GenericIon(), geomMin, gPathLength, G4EmParameters::Instance(), G4LossTableManager::Instance(), isActive, lowestKinEnergy, minDisplacement2, modelManager, mscModels, CLHEP::nm, physStepLimit, G4VProcess::pParticleChange, G4LossTableManager::Register(), safetyHelper, G4VProcess::SetProcessSubType(), G4VProcess::SetVerboseLevel(), theParameters, and tPathLength.
G4VMultipleScattering::~G4VMultipleScattering () virtual
Definition at line 130 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 130 of file G4VMultipleScattering.cc
References G4LossTableManager::DeRegister(), emManager, and modelManager.
G4VMultipleScattering::G4VMultipleScattering (G4VMultipleScattering &) private delete
Member Function Documentation
void G4VMultipleScattering::AddEmModel (G4int order, G4VEmModel * p, const G4Region * region = nullptr)
Definition at line 144 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 144 of file G4VMultipleScattering.cc
References G4EmModelManager::AddEmModel(), Acts::UnitConstants::fm, modelManager, G4VProcess::pParticleChange, and G4VEmModel::SetParticleChange().
Referenced by PhysicsList::ConstructEM(), PhysListEmStandardGS::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4eAdjointMultipleScattering::InitialiseProcess(), G4MuMultipleScattering::InitialiseProcess(), G4eMultipleScattering::InitialiseProcess(), G4hMultipleScattering::InitialiseProcess(), G4AdjointhMultipleScattering::InitialiseProcess(), G4EmConfigurator::PrepareModels(), and G4EmConfigurator::SetModelForRegion().
G4VParticleChange * G4VMultipleScattering::AlongStepDoIt (const G4Track & track, const G4Step & step) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 461 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 461 of file G4VMultipleScattering.cc
References kdfinder::abs(), G4SafetyHelper::ComputeSafety(), G4VMscModel::ComputeTrueStepLength(), currentModel, currParticle, fDispBeyondSafety, fNewDirection, fNewPosition, fParticleChange, fPositionChanged, geomMin, G4Track::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4ParticleChangeForMSC::GetMomentumDirection(), G4StepPoint::GetMomentumDirection(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4VMscModel::GetRange(), G4Step::GetStepLength(), isActive, CLHEP::Hep3Vector::mag2(), min, minDisplacement2, CLHEP::nm, physStepLimit, G4ParticleChangeForMSC::ProposeMomentumDirection(), G4ParticleChangeForMSC::ProposePosition(), G4VParticleChange::ProposeTrueStepLength(), r2, G4SafetyHelper::RecheckDistanceToCurrentBoundary(), G4SafetyHelper::ReLocateWithinVolume(), safetyHelper, G4VMscModel::SampleScattering(), and tPathLength.
G4double G4VMultipleScattering::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimalStep, G4double & currentSafety, G4GPILSelection * selection) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 395 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 395 of file G4VMultipleScattering.cc
References CandidateForSelection, G4VMscModel::ComputeTruePathLengthLimit(), currentModel, geomMin, G4MaterialCutsCouple::GetIndex(), G4Track::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetPDGMass(), gPathLength, isActive, G4VEmModel::IsActive(), isIon, lowestKinEnergy, NotCandidateForSelection, numberOfModels, physStepLimit, source.hepunit::proton_mass_c2, SelectModel(), and tPathLength.
Referenced by GetContinuousStepLimit().
void G4VMultipleScattering::BuildPhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Definition at line 280 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 280 of file G4VMultipleScattering.cc
References G4LossTableManager::BuildPhysicsTable(), emManager, firstParticle, G4cout, G4endl, G4VEmModel::GetCrossSectionTable(), G4VProcess::GetMasterProcess(), GetModelByIndex(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4VEmModel::InitialiseLocal(), isIon, G4LossTableManager::IsMaster(), num, numberOfModels, G4VEmModel::SetCrossSectionTable(), StreamInfo(), and G4VProcess::verboseLevel.
G4double G4VMultipleScattering::ContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimalStep, G4double & currentSafety)
Definition at line 644 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 644 of file G4VMultipleScattering.cc
References GetContinuousStepLimit().
G4VMscModel * G4VMultipleScattering::EmModel (size_t index = 0) const
Definition at line 163 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 163 of file G4VMultipleScattering.cc
References mscModels.
Referenced by G4eAdjointMultipleScattering::InitialiseProcess(), G4MuMultipleScattering::InitialiseProcess(), G4eMultipleScattering::InitialiseProcess(), and G4hMultipleScattering::InitialiseProcess().
const G4ParticleDefinition * G4VMultipleScattering::FirstParticle () const inline
Definition at line 407 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 407 of file G4VMultipleScattering.hh
References firstParticle.
G4double G4VMultipleScattering::GeomFactor () const inline
Definition at line 363 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 363 of file G4VMultipleScattering.hh
References G4EmParameters::MscGeomFactor(), and theParameters.
Referenced by G4eAdjointMultipleScattering::PrintInfo(), G4eMultipleScattering::StreamProcessInfo(), and G4hMultipleScattering::StreamProcessInfo().
G4double G4VMultipleScattering::GetContinuousStepLimit (const G4Track & track, G4double previousStepSize, G4double currentMinimalStep, G4double & currentSafety) override protected virtual
Implements G4VContinuousDiscreteProcess.
Definition at line 628 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 628 of file G4VMultipleScattering.cc
References AlongStepGetPhysicalInteractionLength(), NotCandidateForSelection, and x.
Referenced by ContinuousStepLimit().
G4double G4VMultipleScattering::GetMeanFreePath (const G4Track & track, G4double , G4ForceCondition * condition) override protected virtual
Implements G4VContinuousDiscreteProcess.
Definition at line 656 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 656 of file G4VMultipleScattering.cc
References DBL_MAX, and Forced.
G4VEmModel * G4VMultipleScattering::GetModelByIndex (G4int idx = 0, G4bool ver = false) const inline
Definition at line 422 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 422 of file G4VMultipleScattering.hh
References G4EmModelManager::GetModel(), and modelManager.
Referenced by BuildPhysicsTable(), PreparePhysicsTable(), SetIonisation(), and StartTracking().
virtual void G4VMultipleScattering::InitialiseProcess (const G4ParticleDefinition *) protected pure virtual
Implemented in G4AdjointhMultipleScattering, G4hMultipleScattering, G4eAdjointMultipleScattering, G4MuMultipleScattering, and G4eMultipleScattering.
Referenced by PreparePhysicsTable().
virtual G4bool G4VMultipleScattering::IsApplicable (const G4ParticleDefinition & p) override pure virtual
Reimplemented from G4VProcess.
Implemented in G4AdjointhMultipleScattering, G4eAdjointMultipleScattering, G4hMultipleScattering, G4MuMultipleScattering, and G4eMultipleScattering.
G4bool G4VMultipleScattering::LateralDisplasmentFlag () const inline
Definition at line 318 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 318 of file G4VMultipleScattering.hh
References latDisplacement.
Referenced by G4eAdjointMultipleScattering::PrintInfo(), G4AdjointhMultipleScattering::PrintInfo(), G4eMultipleScattering::StreamProcessInfo(), G4MuMultipleScattering::StreamProcessInfo(), and G4hMultipleScattering::StreamProcessInfo().
G4double G4VMultipleScattering::LowestKinEnergy () const inline
Definition at line 393 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 393 of file G4VMultipleScattering.hh
References lowestKinEnergy.
G4int G4VMultipleScattering::NumberOfModels () const inline protected
Definition at line 414 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 414 of file G4VMultipleScattering.hh
References modelManager, and G4EmModelManager::NumberOfModels().
G4VMultipleScattering& G4VMultipleScattering::operator= (const G4VMultipleScattering & right) private delete
G4double G4VMultipleScattering::PolarAngleLimit () const inline
Definition at line 370 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 370 of file G4VMultipleScattering.hh
References G4EmParameters::MscThetaLimit(), and theParameters.
Referenced by G4MuMultipleScattering::StreamProcessInfo().
G4VParticleChange * G4VMultipleScattering::PostStepDoIt (const G4Track & track, const G4Step &) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 620 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 620 of file G4VMultipleScattering.cc
References fParticleChange, and G4ParticleChangeForMSC::Initialize().
G4double G4VMultipleScattering::PostStepGetPhysicalInteractionLength (const G4Track & , G4double previousStepSize, G4ForceCondition * condition) override virtual
Reimplemented from G4VContinuousDiscreteProcess.
Definition at line 451 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 451 of file G4VMultipleScattering.cc
References DBL_MAX, and NotForced.
void G4VMultipleScattering::PreparePhysicsTable (const G4ParticleDefinition & part) override virtual
Reimplemented from G4VProcess.
Definition at line 171 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 171 of file G4VMultipleScattering.cc
References currentModel, currParticle, G4Electron::Electron(), emax, emManager, facrange, fDispBeyondSafety, G4ParticleTable::FindParticle(), firstParticle, fMinimal, G4cout, G4endl, G4ProcessManager::GetAlongStepProcessVector(), GetModelByIndex(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4TransportationManager::GetSafetyHelper(), G4TransportationManager::GetTransportationManager(), G4VEmModel::HighEnergyLimit(), G4EmModelManager::Initialise(), G4SafetyHelper::InitialiseHelper(), InitialiseProcess(), isIon, G4LossTableManager::IsMaster(), latDisplacement, G4EmParameters::LatDisplacementBeyondSafety(), G4EmParameters::LateralDisplacement(), G4EmParameters::MaxKinEnergy(), MeV, min, modelManager, G4EmParameters::MscMuHadRangeFactor(), G4EmParameters::MscMuHadStepLimitType(), G4EmParameters::MscRangeFactor(), G4EmParameters::MscStepLimitType(), G4EmParameters::MscThetaLimit(), G4EmParameters::MuHadLateralDisplacement(), n, G4EmModelManager::NumberOfModels(), numberOfModels, part, Acts::UnitConstants::pm, pname(), G4LossTableManager::PreparePhysicsTable(), safetyHelper, G4VEmModel::SetHighEnergyLimit(), G4VMscModel::SetIonisation(), G4VEmModel::SetMasterThread(), G4VEmModel::SetPolarAngleLimit(), G4VProcess::SetVerboseLevel(), G4ProcessVector::size(), stepLimit, theParameters, v, G4EmParameters::Verbose(), G4VProcess::verboseLevel, and G4EmParameters::WorkerVerbose().
virtual void G4VMultipleScattering::PrintInfo () inline virtual
Reimplemented in G4AdjointhMultipleScattering, and G4eAdjointMultipleScattering.
Definition at line 107 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 107 of file G4VMultipleScattering.hh
void G4VMultipleScattering::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VProcess.
Reimplemented in G4hMultipleScattering, G4MuMultipleScattering, and G4eMultipleScattering.
Definition at line 729 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 729 of file G4VMultipleScattering.cc
References firstParticle, and StreamInfo().
Referenced by G4MuMultipleScattering::ProcessDescription(), G4eMultipleScattering::ProcessDescription(), and G4hMultipleScattering::ProcessDescription().
G4double G4VMultipleScattering::RangeFactor () const inline
Definition at line 346 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 346 of file G4VMultipleScattering.hh
References facrange.
Referenced by G4eAdjointMultipleScattering::PrintInfo(), G4AdjointhMultipleScattering::PrintInfo(), G4eMultipleScattering::StreamProcessInfo(), G4MuMultipleScattering::StreamProcessInfo(), and G4hMultipleScattering::StreamProcessInfo().
G4bool G4VMultipleScattering::RetrievePhysicsTable (const G4ParticleDefinition * , const G4String & directory, G4bool ascii) override virtual
Reimplemented from G4VProcess.
Definition at line 710 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 710 of file G4VMultipleScattering.cc
G4VEmModel * G4VMultipleScattering::SelectModel (G4double kinEnergy, size_t idx) inline
Definition at line 311 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 311 of file G4VMultipleScattering.hh
References modelManager, and G4EmModelManager::SelectModel().
Referenced by AlongStepGetPhysicalInteractionLength(), G4EmCalculator::FindEmModel(), and G4EmCalculator::FindLambdaTable().
void G4VMultipleScattering::SetEmModel (G4VMscModel * p, size_t index = 0)
Definition at line 155 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 155 of file G4VMultipleScattering.cc
References mscModels.
Referenced by G4AdjointPhysicsList::ConstructEM(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), G4eAdjointMultipleScattering::InitialiseProcess(), G4eMultipleScattering::InitialiseProcess(), G4MuMultipleScattering::InitialiseProcess(), and G4hMultipleScattering::InitialiseProcess().
void G4VMultipleScattering::SetIonisation (G4VEnergyLossProcess * p)
Definition at line 719 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 719 of file G4VMultipleScattering.cc
References firstParticle, GetModelByIndex(), numberOfModels, and G4VMscModel::SetIonisation().
void G4VMultipleScattering::SetLateralDisplasmentFlag (G4bool val) inline
Definition at line 325 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 325 of file G4VMultipleScattering.hh
References latDisplacement.
void G4VMultipleScattering::SetLowestKinEnergy (G4double val) inline
Definition at line 400 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 400 of file G4VMultipleScattering.hh
References lowestKinEnergy.
void G4VMultipleScattering::SetRangeFactor (G4double val) inline
Definition at line 353 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 353 of file G4VMultipleScattering.hh
References facrange, G4EmParameters::SetMscRangeFactor(), and theParameters.
Referenced by SetStepLimitType().
void G4VMultipleScattering::SetSkin (G4double val) inline
Definition at line 339 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 339 of file G4VMultipleScattering.hh
References G4EmParameters::SetMscSkin(), and theParameters.
void G4VMultipleScattering::SetStepLimitType (G4MscStepLimitType val) inline
Definition at line 384 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 384 of file G4VMultipleScattering.hh
References fMinimal, G4EmParameters::SetMscStepLimitType(), SetRangeFactor(), stepLimit, and theParameters.
Referenced by DMXPhysicsList::ConstructEM(), LBE::ConstructEM(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), and G4EmDNAPhysics_option6::ConstructProcess().
G4double G4VMultipleScattering::Skin () const inline
Definition at line 332 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 332 of file G4VMultipleScattering.hh
References G4EmParameters::MscSkin(), and theParameters.
Referenced by G4eAdjointMultipleScattering::PrintInfo(), G4AdjointhMultipleScattering::PrintInfo(), G4eMultipleScattering::StreamProcessInfo(), and G4hMultipleScattering::StreamProcessInfo().
void G4VMultipleScattering::StartTracking (G4Track * track) override virtual
Reimplemented from G4VProcess.
Definition at line 361 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 361 of file G4VMultipleScattering.cc
References currParticle, emManager, fIonisation, G4LossTableManager::GetEnergyLossProcess(), GetModelByIndex(), G4Track::GetParticleDefinition(), numberOfModels, G4VMscModel::SetIonisation(), and G4VEmModel::StartTracking().
Referenced by G4eAdjointMultipleScattering::StartTracking().
G4MscStepLimitType G4VMultipleScattering::StepLimitType () const inline
Definition at line 377 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 377 of file G4VMultipleScattering.hh
References stepLimit.
Referenced by G4eAdjointMultipleScattering::PrintInfo(), G4AdjointhMultipleScattering::PrintInfo(), G4eMultipleScattering::StreamProcessInfo(), G4MuMultipleScattering::StreamProcessInfo(), and G4hMultipleScattering::StreamProcessInfo().
G4bool G4VMultipleScattering::StorePhysicsTable (const G4ParticleDefinition * part, const G4String & directory, G4bool ascii = false) override virtual
Reimplemented from G4VProcess.
Definition at line 666 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 666 of file G4VMultipleScattering.cc
References firstParticle, G4cout, G4endl, G4VEmModel::GetCrossSectionTable(), G4VProcess::GetMasterProcess(), G4EmModelManager::GetModel(), G4ParticleDefinition::GetParticleName(), G4VProcess::GetPhysicsTableFileName(), G4VProcess::GetProcessName(), min, modelManager, G4EmModelManager::NumberOfModels(), G4PhysicsTable::StorePhysicsTable(), and G4VProcess::verboseLevel.
void G4VMultipleScattering::StreamInfo (std::ostream & outFile, const G4ParticleDefinition & part, G4bool rst = false) const private
Definition at line 348 of file G4VMultipleScattering.cc.
View newest version in sPHENIX GitHub at line 348 of file G4VMultipleScattering.cc
References G4EmModelManager::DumpModelList(), G4endl, G4ParticleDefinition::GetParticleName(), G4VProcess::GetProcessName(), G4VProcess::GetProcessSubType(), modelManager, StreamProcessInfo(), and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable(), and ProcessDescription().
virtual void G4VMultipleScattering::StreamProcessInfo (std::ostream &) const inline protected virtual
Reimplemented in G4hMultipleScattering, G4MuMultipleScattering, and G4eMultipleScattering.
Definition at line 115 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 115 of file G4VMultipleScattering.hh
Referenced by StreamInfo().
Member Data Documentation
G4VMscModel* G4VMultipleScattering::currentModel private
Definition at line 291 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 291 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4VMultipleScattering(), and PreparePhysicsTable().
const G4ParticleDefinition* G4VMultipleScattering::currParticle private
Definition at line 271 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 271 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), PreparePhysicsTable(), and StartTracking().
G4LossTableManager* G4VMultipleScattering::emManager private
Definition at line 260 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 260 of file G4VMultipleScattering.hh
Referenced by BuildPhysicsTable(), G4VMultipleScattering(), PreparePhysicsTable(), StartTracking(), and ~G4VMultipleScattering().
G4double G4VMultipleScattering::facrange private
Definition at line 275 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 275 of file G4VMultipleScattering.hh
Referenced by PreparePhysicsTable(), RangeFactor(), and SetRangeFactor().
G4bool G4VMultipleScattering::fDispBeyondSafety private
Definition at line 280 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 280 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), and PreparePhysicsTable().
G4VEnergyLossProcess* G4VMultipleScattering::fIonisation private
Definition at line 292 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 292 of file G4VMultipleScattering.hh
Referenced by G4VMultipleScattering(), and StartTracking().
const G4ParticleDefinition* G4VMultipleScattering::firstParticle private
Definition at line 270 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 270 of file G4VMultipleScattering.hh
Referenced by BuildPhysicsTable(), FirstParticle(), G4VMultipleScattering(), PreparePhysicsTable(), ProcessDescription(), SetIonisation(), and StorePhysicsTable().
G4ThreeVector G4VMultipleScattering::fNewDirection private
Definition at line 301 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 301 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt().
G4ThreeVector G4VMultipleScattering::fNewPosition private
Definition at line 300 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 300 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt().
G4ParticleChangeForMSC G4VMultipleScattering::fParticleChange protected
Definition at line 286 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 286 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), G4VMultipleScattering(), and PostStepDoIt().
G4bool G4VMultipleScattering::fPositionChanged private
Definition at line 302 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 302 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), and G4VMultipleScattering().
G4double G4VMultipleScattering::geomMin private
Definition at line 294 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 294 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and G4VMultipleScattering().
G4double G4VMultipleScattering::gPathLength private
Definition at line 298 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 298 of file G4VMultipleScattering.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and G4VMultipleScattering().
G4bool G4VMultipleScattering::isActive private
Definition at line 303 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 303 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and G4VMultipleScattering().
G4bool G4VMultipleScattering::isIon private
Definition at line 279 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 279 of file G4VMultipleScattering.hh
Referenced by AlongStepGetPhysicalInteractionLength(), BuildPhysicsTable(), and PreparePhysicsTable().
G4bool G4VMultipleScattering::latDisplacement private
Definition at line 278 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 278 of file G4VMultipleScattering.hh
Referenced by LateralDisplasmentFlag(), PreparePhysicsTable(), and SetLateralDisplasmentFlag().
G4double G4VMultipleScattering::lowestKinEnergy private
Definition at line 276 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 276 of file G4VMultipleScattering.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4VMultipleScattering(), LowestKinEnergy(), and SetLowestKinEnergy().
G4double G4VMultipleScattering::minDisplacement2 private
Definition at line 295 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 295 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), and G4VMultipleScattering().
G4EmModelManager* G4VMultipleScattering::modelManager private
Definition at line 259 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 259 of file G4VMultipleScattering.hh
Referenced by AddEmModel(), G4VMultipleScattering(), GetModelByIndex(), NumberOfModels(), PreparePhysicsTable(), SelectModel(), StorePhysicsTable(), StreamInfo(), and ~G4VMultipleScattering().
std::vector<G4VMscModel*> G4VMultipleScattering::mscModels private
Definition at line 267 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 267 of file G4VMultipleScattering.hh
Referenced by EmModel(), G4VMultipleScattering(), and SetEmModel().
G4int G4VMultipleScattering::numberOfModels private
Definition at line 268 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 268 of file G4VMultipleScattering.hh
Referenced by AlongStepGetPhysicalInteractionLength(), BuildPhysicsTable(), PreparePhysicsTable(), SetIonisation(), and StartTracking().
G4double G4VMultipleScattering::physStepLimit private
Definition at line 296 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 296 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and G4VMultipleScattering().
G4SafetyHelper* G4VMultipleScattering::safetyHelper private
Definition at line 265 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 265 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), G4VMultipleScattering(), and PreparePhysicsTable().
G4MscStepLimitType G4VMultipleScattering::stepLimit private
Definition at line 273 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 273 of file G4VMultipleScattering.hh
Referenced by PreparePhysicsTable(), SetStepLimitType(), and StepLimitType().
G4EmParameters* G4VMultipleScattering::theParameters private
Definition at line 261 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 261 of file G4VMultipleScattering.hh
Referenced by G4VMultipleScattering(), GeomFactor(), PolarAngleLimit(), PreparePhysicsTable(), SetRangeFactor(), SetSkin(), SetStepLimitType(), and Skin().
G4double G4VMultipleScattering::tPathLength private
Definition at line 297 of file G4VMultipleScattering.hh.
View newest version in sPHENIX GitHub at line 297 of file G4VMultipleScattering.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), and G4VMultipleScattering().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4VMultipleScattering.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4VMultipleScattering.cc