ECCE @ EIC Software: G4UIGAG Class Reference
G4UIGAG Class Reference
#include <geant4/tree/geant4-10.6-release/source/interfaces/GAG/include/G4UIGAG.hh>
Public Member Functions
G4UIGAG ()
~G4UIGAG ()
G4UIsession * SessionStart ()
void PauseSessionStart (const G4String &)
G4int ReceiveG4cout (const G4String &)
G4int ReceiveG4cerr (const G4String &)
void SessionTerminate ()
void Prompt (const G4String &)
G4String GetCommand ()
Public Member Functions inherited from G4UIsession
G4UIsession ()
G4UIsession (G4int iBatch)
virtual ~G4UIsession ()
G4int GetLastReturnCode () const
Public Member Functions inherited from G4coutDestination
G4coutDestination ()=default
virtual ~G4coutDestination ()
void AddCoutTransformer (const Transformer &t)
void AddCoutTransformer (Transformer &&t)
void AddCerrTransformer (const Transformer &t)
void AddCerrTransformer (Transformer &&t)
virtual void ResetTransformers ()
G4int ReceiveG4cout_ (const G4String &msg)
G4int ReceiveG4cerr_ (const G4String &msg)
Private Member Functions
void ExecuteCommand (const G4String &)
void ChangeDirectory (const G4String &)
void ListDirectory (const G4String &)
void TerminalHelp (const G4String &)
G4String ModifyPrefix (G4String)
G4UIcommandTree * FindDirPath (const G4String &)
void ShowCurrent (const G4String &)
G4String GetFullPath (const G4String &)
void SendCommandProperties (G4UIcommandTree *)
void SendParameterProperties (G4UIcommandTree *)
void SendAParamProperty (G4UIcommand *)
void SendATclParamProperty (G4UIcommand *)
void CodeGenJavaTree (G4UIcommandTree *, int recursiveLevel)
void CodeGenJavaParams (G4UIcommandTree *, int recursiveLevel)
void CodeGenTclTree (G4UIcommandTree *, int recursiveLevel)
void CodeGenTclParams (G4UIcommandTree *, int recursiveLevel)
void SendDisableList (G4UIcommandTree *, int recursiveLevel)
void NotifyStateChange (void)
void NotifyCommandUpdate (void)
void NotifyParameterUpdate (G4UIcommand *)
int CommandUpdated (void)
void UpdateState (void)
void UpdateParamVal (void)
void GetNewTreeStructure (G4UIcommandTree *, int recursiveLevel)
void GetNewTreeValues (G4UIcommandTree *, int recursiveLevel)
Private Attributes
G4String prefix
G4UImanager * UI
G4String promptCharacter
G4bool iExit
G4bool iCont
UImode uiMode
G4String JVersion
G4String TVersion
std::vector< G4String > previousTreeCommands
std::vector< G4String > newTreeCommands
std::vector< G4String > previousTreeParams
std::vector< G4String > newTreeParams
std::vector< G4UIcommand * > previousTreePCP
std::vector< G4UIcommand * > newTreePCP
Additional Inherited Members
Public Types inherited from G4coutDestination
using Transformer = std::function< G4bool(G4String &)>
Static Public Member Functions inherited from G4UIsession
static G4int InSession ()
Protected Attributes inherited from G4UIsession
G4int ifBatch
G4int lastRC
Static Protected Attributes inherited from G4UIsession
static G4ICOMS_DLL G4int inSession = 0
Detailed Description
Definition at line 52 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 52 of file G4UIGAG.hh
Constructor & Destructor Documentation
G4UIGAG::G4UIGAG ()
Definition at line 38 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 38 of file G4UIGAG.cc
References G4StateManager::GetCurrentState(), GetNewTreeStructure(), GetNewTreeValues(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), G4UImanager::GetTree(), G4UImanager::GetUIpointer(), iCont, iExit, JVersion, newTreeCommands, newTreeParams, newTreePCP, previousTreeCommands, previousTreeParams, previousTreePCP, promptCharacter, G4UImanager::SetCoutDestination(), G4UImanager::SetSession(), terminal_mode, gammaraytel::tree, TVersion, UI, and uiMode.
G4UIGAG::~G4UIGAG ()
Definition at line 61 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 61 of file G4UIGAG.cc
References G4UImanager::GetUIpointer(), G4UImanager::SetCoutDestination(), G4UImanager::SetSession(), and UI.
Member Function Documentation
void G4UIGAG::ChangeDirectory (const G4String & newCommand) private
Definition at line 358 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 358 of file G4UIGAG.cc
References G4String::both, FindDirPath(), G4cout, G4endl, ModifyPrefix(), prefix, and G4String::strip().
Referenced by GetCommand().
void G4UIGAG::CodeGenJavaParams (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 580 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 580 of file G4UIGAG.cc
References G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommandTree::GetPathName(), G4UIcommandTree::GetTitle(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), and SendAParamProperty().
Referenced by SendCommandProperties(), and SendParameterProperties().
void G4UIGAG::CodeGenJavaTree (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 562 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 562 of file G4UIGAG.cc
References G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIcommandTree::GetTree(), and G4UIcommandTree::GetTreeEntry().
Referenced by SendCommandProperties().
void G4UIGAG::CodeGenTclParams (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 729 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 729 of file G4UIGAG.cc
References G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), and SendATclParamProperty().
Referenced by SendCommandProperties(), and SendParameterProperties().
void G4UIGAG::CodeGenTclTree (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 667 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 667 of file G4UIGAG.cc
References G4String::append(), c, G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIcommand::GetGuidanceEntries(), G4UIcommand::GetGuidanceLine(), G4UIcommandTree::GetPathName(), G4UIcommandTree::GetTitle(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), int(), k, and t.
Referenced by SendCommandProperties().
int G4UIGAG::CommandUpdated (void) private
Definition at line 825 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 825 of file G4UIGAG.cc
References added, addedAndDeleted, deleted, G4cout, G4endl, newTreeCommands, notChanged, and previousTreeCommands.
Referenced by ExecuteCommand().
void G4UIGAG::ExecuteCommand (const G4String & aCommand) private
Definition at line 99 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 99 of file G4UIGAG.cc
References G4UImanager::ApplyCommand(), CommandUpdated(), fAliasNotFound, fCommandNotFound, fCommandSucceeded, fIllegalApplicationState, fParameterOutOfCandidates, fParameterOutOfRange, fParameterUnreadable, G4cerr, G4cout, G4endl, GetNewTreeStructure(), GetNewTreeValues(), G4UImanager::GetTree(), newTreeCommands, newTreeParams, newTreePCP, NotifyCommandUpdate(), previousTreeCommands, previousTreeParams, previousTreePCP, G4UImanager::SolveAlias(), terminal_mode, gammaraytel::tree, UI, uiMode, UpdateParamVal(), and UpdateState().
Referenced by PauseSessionStart(), and SessionStart().
G4UIcommandTree * G4UIGAG::FindDirPath (const G4String & newCommand) private
Definition at line 514 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 514 of file G4UIGAG.cc
References G4UIcommandTree::GetTree(), G4UImanager::GetTree(), incremental_prev_tag::idx, G4String::index(), and UI.
Referenced by ChangeDirectory(), and ListDirectory().
G4String G4UIGAG::GetCommand ()
Definition at line 188 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 188 of file G4UIGAG.cc
References G4String::append(), ChangeDirectory(), FALSE, G4cerr, G4cin, G4cout, G4endl, GetFullPath(), G4UImanager::GetNumberOfHistory(), G4UImanager::GetPreviousCommand(), G4UImanager::GetTree(), iCont, iExit, java_mode, JVersion, G4String::leading, ListDirectory(), NotifyStateChange(), promptCharacter, G4String::readLine(), G4String::remove(), SendCommandProperties(), ShowCurrent(), G4String::strip(), tcl_mode, terminal_mode, TerminalHelp(), gammaraytel::tree, TVersion, UI, and uiMode.
Referenced by PauseSessionStart(), and SessionStart().
G4String G4UIGAG::GetFullPath (const G4String & aNewCommand) private
Definition at line 302 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 302 of file G4UIGAG.cc
References G4String::append(), G4String::both, ModifyPrefix(), prefix, and G4String::strip().
Referenced by GetCommand(), and ShowCurrent().
void G4UIGAG::GetNewTreeStructure (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 855 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 855 of file G4UIGAG.cc
References G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIcommandTree::GetPathName(), G4UIcommandTree::GetTitle(), G4UIcommand::GetTitle(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), newTreeCommands, t, and title().
Referenced by ExecuteCommand(), and G4UIGAG().
void G4UIGAG::GetNewTreeValues (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 934 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 934 of file G4UIGAG.cc
References G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIparameter::GetDefaultValue(), G4UIcommand::GetParameter(), G4UIparameter::GetParameterCandidates(), G4UIcommand::GetParameterEntries(), G4UIparameter::GetParameterName(), G4UIparameter::GetParameterRange(), G4UIparameter::GetParameterType(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), newTreeParams, newTreePCP, and t.
Referenced by ExecuteCommand(), and G4UIGAG().
void G4UIGAG::ListDirectory (const G4String & newCommand) private
Definition at line 385 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 385 of file G4UIGAG.cc
References G4String::both, FindDirPath(), G4cout, G4endl, G4UIcommandTree::ListCurrent(), ModifyPrefix(), prefix, and G4String::strip().
Referenced by GetCommand().
G4String G4UIGAG::ModifyPrefix (G4String newCommand) private
Definition at line 489 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 489 of file G4UIGAG.cc
References G4String::last(), and prefix.
Referenced by ChangeDirectory(), GetFullPath(), and ListDirectory().
void G4UIGAG::NotifyCommandUpdate (void) private
Definition at line 797 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 797 of file G4UIGAG.cc
References G4UImanager::GetTree(), SendCommandProperties(), gammaraytel::tree, and UI.
Referenced by ExecuteCommand().
void G4UIGAG::NotifyParameterUpdate (G4UIcommand * com) private
Definition at line 803 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 803 of file G4UIGAG.cc
References java_mode, SendAParamProperty(), SendATclParamProperty(), and uiMode.
Referenced by UpdateParamVal().
void G4UIGAG::NotifyStateChange (void) private
Definition at line 783 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 783 of file G4UIGAG.cc
References G4cout, G4endl, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), G4UImanager::GetTree(), SendDisableList(), terminal_mode, gammaraytel::tree, UI, and uiMode.
Referenced by GetCommand(), and UpdateState().
void G4UIGAG::PauseSessionStart (const G4String & msg) virtual
Reimplemented from G4UIsession.
Definition at line 86 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 86 of file G4UIGAG.cc
References ExecuteCommand(), G4cout, G4endl, GetCommand(), iCont, and promptCharacter.
void G4UIGAG::Prompt (const G4String & aPrompt)
Definition at line 183 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 183 of file G4UIGAG.cc
References promptCharacter.
G4int G4UIGAG::ReceiveG4cerr (const G4String & cerrString) virtual
Reimplemented from G4UIsession.
Definition at line 177 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 177 of file G4UIGAG.cc
G4int G4UIGAG::ReceiveG4cout (const G4String & coutString) virtual
Reimplemented from G4UIsession.
Definition at line 171 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 171 of file G4UIGAG.cc
void G4UIGAG::SendAParamProperty (G4UIcommand * Comp) private
Definition at line 603 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 603 of file G4UIGAG.cc
References G4String::append(), c, G4cout, G4endl, G4UIcommand::GetCommandPath(), G4UIparameter::GetDefaultValue(), G4UIcommand::GetGuidanceEntries(), G4UIcommand::GetGuidanceLine(), G4UIcommand::GetParameter(), G4UIparameter::GetParameterCandidates(), G4UIcommand::GetParameterEntries(), G4UIparameter::GetParameterGuidance(), G4UIparameter::GetParameterName(), G4UIparameter::GetParameterRange(), G4UIparameter::GetParameterType(), G4UIcommand::GetRange(), int(), G4UIparameter::IsOmittable(), and title().
Referenced by CodeGenJavaParams(), and NotifyParameterUpdate().
void G4UIGAG::SendATclParamProperty (G4UIcommand * Comp) private
Definition at line 748 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 748 of file G4UIGAG.cc
References G4String::append(), c, G4cout, G4endl, G4UIcommand::GetCommandPath(), G4UIparameter::GetDefaultValue(), G4UIcommand::GetParameter(), G4UIparameter::GetParameterCandidates(), G4UIcommand::GetParameterEntries(), G4UIparameter::GetParameterGuidance(), G4UIparameter::GetParameterName(), G4UIparameter::GetParameterRange(), G4UIparameter::GetParameterType(), G4UIcommand::GetRange(), int(), and G4UIparameter::IsOmittable().
Referenced by CodeGenTclParams(), and NotifyParameterUpdate().
void G4UIGAG::SendCommandProperties (G4UIcommandTree * tree) private
Definition at line 531 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 531 of file G4UIGAG.cc
References CodeGenJavaParams(), CodeGenJavaTree(), CodeGenTclParams(), CodeGenTclTree(), G4cerr, G4cout, G4endl, java_mode, and uiMode.
Referenced by GetCommand(), and NotifyCommandUpdate().
void G4UIGAG::SendDisableList (G4UIcommandTree * tree, int recursiveLevel) private
Definition at line 644 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 644 of file G4UIGAG.cc
References false, G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetCommandEntry(), G4UIcommand::GetCommandPath(), G4UIcommandTree::GetTree(), G4UIcommandTree::GetTreeEntry(), and G4UIcommand::IsAvailable().
Referenced by NotifyStateChange().
void G4UIGAG::SendParameterProperties (G4UIcommandTree * tree) private
Definition at line 549 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 549 of file G4UIGAG.cc
References CodeGenJavaParams(), CodeGenTclParams(), G4cerr, G4endl, java_mode, and uiMode.
G4UIsession * G4UIGAG::SessionStart () virtual
Reimplemented from G4UIsession.
Definition at line 71 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 71 of file G4UIGAG.cc
References ExecuteCommand(), GetCommand(), G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), G4StateManager::GetStateString(), iExit, and promptCharacter.
void G4UIGAG::SessionTerminate ()
Definition at line 336 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 336 of file G4UIGAG.cc
References G4cout, and G4endl.
void G4UIGAG::ShowCurrent (const G4String & newCommand) private
Definition at line 341 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 341 of file G4UIGAG.cc
References G4cout, G4endl, G4UImanager::GetCurrentValues(), GetFullPath(), G4String::isNull(), terminal_mode, UI, and uiMode.
Referenced by GetCommand().
void G4UIGAG::TerminalHelp (const G4String & newCommand) private
Definition at line 413 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 413 of file G4UIGAG.cc
References G4String::both, G4UIcommandTree::FindPath(), G4cin, G4cout, G4endl, G4UIcommandTree::GetCommand(), G4UIcommandTree::GetTree(), G4UImanager::GetTree(), G4UIcommandTree::GetTreeEntry(), G4String::index(), G4UIcommand::List(), G4UIcommandTree::ListCurrentWithNum(), prefix, G4String::prepend(), G4String::strip(), and UI.
Referenced by GetCommand().
void G4UIGAG::UpdateParamVal (void) private
Definition at line 882 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 882 of file G4UIGAG.cc
References G4cout, G4endl, G4UIcommand::GetCommandPath(), newTreeParams, newTreePCP, NotifyParameterUpdate(), and previousTreeParams.
Referenced by ExecuteCommand().
void G4UIGAG::UpdateState (void) private
Definition at line 812 of file G4UIGAG.cc.
View newest version in sPHENIX GitHub at line 812 of file G4UIGAG.cc
References G4State_PreInit, G4ThreadLocal, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), and NotifyStateChange().
Referenced by ExecuteCommand().
Member Data Documentation
G4bool G4UIGAG::iCont private
Definition at line 83 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 83 of file G4UIGAG.hh
Referenced by G4UIGAG(), GetCommand(), and PauseSessionStart().
G4bool G4UIGAG::iExit private
Definition at line 82 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 82 of file G4UIGAG.hh
Referenced by G4UIGAG(), GetCommand(), and SessionStart().
G4String G4UIGAG::JVersion private
Definition at line 87 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 87 of file G4UIGAG.hh
Referenced by G4UIGAG(), and GetCommand().
std::vector<G4String> G4UIGAG::newTreeCommands private
Definition at line 122 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 122 of file G4UIGAG.hh
Referenced by CommandUpdated(), ExecuteCommand(), G4UIGAG(), and GetNewTreeStructure().
std::vector<G4String> G4UIGAG::newTreeParams private
Definition at line 124 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 124 of file G4UIGAG.hh
Referenced by ExecuteCommand(), G4UIGAG(), GetNewTreeValues(), and UpdateParamVal().
std::vector<G4UIcommand*> G4UIGAG::newTreePCP private
Definition at line 126 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 126 of file G4UIGAG.hh
Referenced by ExecuteCommand(), G4UIGAG(), GetNewTreeValues(), and UpdateParamVal().
G4String G4UIGAG::prefix private
Definition at line 79 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 79 of file G4UIGAG.hh
Referenced by ChangeDirectory(), GetFullPath(), ListDirectory(), ModifyPrefix(), and TerminalHelp().
std::vector<G4String> G4UIGAG::previousTreeCommands private
Definition at line 121 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 121 of file G4UIGAG.hh
Referenced by CommandUpdated(), ExecuteCommand(), and G4UIGAG().
std::vector<G4String> G4UIGAG::previousTreeParams private
Definition at line 123 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 123 of file G4UIGAG.hh
Referenced by ExecuteCommand(), G4UIGAG(), and UpdateParamVal().
std::vector<G4UIcommand*> G4UIGAG::previousTreePCP private
Definition at line 125 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 125 of file G4UIGAG.hh
Referenced by ExecuteCommand(), and G4UIGAG().
G4String G4UIGAG::promptCharacter private
Definition at line 81 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 81 of file G4UIGAG.hh
Referenced by G4UIGAG(), GetCommand(), PauseSessionStart(), Prompt(), and SessionStart().
G4String G4UIGAG::TVersion private
Definition at line 88 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 88 of file G4UIGAG.hh
Referenced by G4UIGAG(), and GetCommand().
G4UImanager* G4UIGAG::UI private
Definition at line 80 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 80 of file G4UIGAG.hh
Referenced by ExecuteCommand(), FindDirPath(), G4UIGAG(), GetCommand(), NotifyCommandUpdate(), NotifyStateChange(), ShowCurrent(), TerminalHelp(), and ~G4UIGAG().
UImode G4UIGAG::uiMode private
Definition at line 84 of file G4UIGAG.hh.
View newest version in sPHENIX GitHub at line 84 of file G4UIGAG.hh
Referenced by ExecuteCommand(), G4UIGAG(), GetCommand(), NotifyParameterUpdate(), NotifyStateChange(), SendCommandProperties(), SendParameterProperties(), and ShowCurrent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/interfaces/GAG/include/G4UIGAG.hh
geant4/tree/geant4-10.6-release/source/interfaces/GAG/src/G4UIGAG.cc