ECCE @ EIC Software: G4FissionLevelDensityParameterINCLXX Class Reference
G4FissionLevelDensityParameterINCLXX Class Reference
Revised level-density parameter for fission after INCL++.
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4FissionLevelDensityParameterINCLXX.hh>
Public Member Functions
G4FissionLevelDensityParameterINCLXX ()
virtual ~G4FissionLevelDensityParameterINCLXX ()
G4double LevelDensityParameter (G4int A, G4int Z, G4double U) const final
void setAfanLow (const double a)
void setAfanHigh (const double a)
void setZLow (const int z)
void setZHigh (const int z)
double getAfanLow () const
double getAfanHigh () const
int getZLow () const
int getZHigh () const
Public Member Functions inherited from G4VLevelDensityParameter
G4VLevelDensityParameter ()
virtual ~G4VLevelDensityParameter ()
Private Member Functions
G4FissionLevelDensityParameterINCLXX (const G4FissionLevelDensityParameterINCLXX &right)
const
G4FissionLevelDensityParameterINCLXX & operator= (const G4FissionLevelDensityParameterINCLXX &right)
G4bool operator== (const G4FissionLevelDensityParameterINCLXX &right) const
G4bool operator!= (const G4FissionLevelDensityParameterINCLXX &right) const
void UpdateAfanSlope ()
Private Attributes
G4NuclearLevelData * fNucData
double afanLow
double afanHigh
int ZLow
int ZHigh
double afanSlope
Detailed Description
Revised level-density parameter for fission after INCL++.
Author
Davide Mancusi
Date
6th October 2014
This class contains a revised level-density parameter that works better than the standard one with the Li`ege Intranuclear Cascade model (INCL++). The fit parameter is the ratio of the level-density parameters in the fission channel and in the neutron-evaporation channel. This is commonly known as af/an and is usually very close to 1.0. Variations of a few percent are likely to induce large factors in the fission probability, because of the exponential growth of the Fermi level density. The best values of af/an were empirically found to be about 1.02 for 1-GeV p+208Pb and 1.04 for 1-GeV p+U238. A linear interpolation was adopted between the two extreme values.
Definition at line 57 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 57 of file G4FissionLevelDensityParameterINCLXX.hh
Constructor & Destructor Documentation
G4FissionLevelDensityParameterINCLXX::G4FissionLevelDensityParameterINCLXX () explicit
Definition at line 35 of file G4FissionLevelDensityParameterINCLXX.cc.
View newest version in sPHENIX GitHub at line 35 of file G4FissionLevelDensityParameterINCLXX.cc
References fNucData, G4NuclearLevelData::GetInstance(), and UpdateAfanSlope().
G4FissionLevelDensityParameterINCLXX::~G4FissionLevelDensityParameterINCLXX () virtual
Definition at line 45 of file G4FissionLevelDensityParameterINCLXX.cc.
View newest version in sPHENIX GitHub at line 45 of file G4FissionLevelDensityParameterINCLXX.cc
G4FissionLevelDensityParameterINCLXX::G4FissionLevelDensityParameterINCLXX (const G4FissionLevelDensityParameterINCLXX & right) private
Member Function Documentation
double G4FissionLevelDensityParameterINCLXX::getAfanHigh () const inline
Definition at line 78 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FissionLevelDensityParameterINCLXX.hh
References afanHigh.
double G4FissionLevelDensityParameterINCLXX::getAfanLow () const inline
Definition at line 77 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FissionLevelDensityParameterINCLXX.hh
References afanLow.
int G4FissionLevelDensityParameterINCLXX::getZHigh () const inline
Definition at line 80 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 80 of file G4FissionLevelDensityParameterINCLXX.hh
References ZHigh.
int G4FissionLevelDensityParameterINCLXX::getZLow () const inline
Definition at line 79 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 79 of file G4FissionLevelDensityParameterINCLXX.hh
References ZLow.
G4double G4FissionLevelDensityParameterINCLXX::LevelDensityParameter (G4int A, G4int Z, G4double U) const final virtual
Implements G4VLevelDensityParameter.
Definition at line 49 of file G4FissionLevelDensityParameterINCLXX.cc.
View newest version in sPHENIX GitHub at line 49 of file G4FissionLevelDensityParameterINCLXX.cc
References afanHigh, afanLow, afanSlope, fNucData, G4NuclearLevelData::GetLevelDensity(), ZHigh, and ZLow.
G4bool G4FissionLevelDensityParameterINCLXX::operator!= (const G4FissionLevelDensityParameterINCLXX & right) const private
const G4FissionLevelDensityParameterINCLXX& G4FissionLevelDensityParameterINCLXX::operator= (const G4FissionLevelDensityParameterINCLXX & right) private
G4bool G4FissionLevelDensityParameterINCLXX::operator== (const G4FissionLevelDensityParameterINCLXX & right) const private
void G4FissionLevelDensityParameterINCLXX::setAfanHigh (const double a) inline
Definition at line 74 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FissionLevelDensityParameterINCLXX.hh
References a, afanHigh, and UpdateAfanSlope().
void G4FissionLevelDensityParameterINCLXX::setAfanLow (const double a) inline
Definition at line 73 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FissionLevelDensityParameterINCLXX.hh
References a, afanLow, and UpdateAfanSlope().
void G4FissionLevelDensityParameterINCLXX::setZHigh (const int z) inline
Definition at line 76 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FissionLevelDensityParameterINCLXX.hh
References UpdateAfanSlope(), z, and ZHigh.
void G4FissionLevelDensityParameterINCLXX::setZLow (const int z) inline
Definition at line 75 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 75 of file G4FissionLevelDensityParameterINCLXX.hh
References UpdateAfanSlope(), z, and ZLow.
void G4FissionLevelDensityParameterINCLXX::UpdateAfanSlope () private
Definition at line 61 of file G4FissionLevelDensityParameterINCLXX.cc.
View newest version in sPHENIX GitHub at line 61 of file G4FissionLevelDensityParameterINCLXX.cc
References afanHigh, afanLow, afanSlope, ZHigh, and ZLow.
Referenced by G4FissionLevelDensityParameterINCLXX(), setAfanHigh(), setAfanLow(), setZHigh(), and setZLow().
Member Data Documentation
double G4FissionLevelDensityParameterINCLXX::afanHigh private
Definition at line 88 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 88 of file G4FissionLevelDensityParameterINCLXX.hh
Referenced by getAfanHigh(), LevelDensityParameter(), setAfanHigh(), and UpdateAfanSlope().
double G4FissionLevelDensityParameterINCLXX::afanLow private
Definition at line 88 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 88 of file G4FissionLevelDensityParameterINCLXX.hh
Referenced by getAfanLow(), LevelDensityParameter(), setAfanLow(), and UpdateAfanSlope().
double G4FissionLevelDensityParameterINCLXX::afanSlope private
Definition at line 90 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 90 of file G4FissionLevelDensityParameterINCLXX.hh
Referenced by LevelDensityParameter(), and UpdateAfanSlope().
G4NuclearLevelData* G4FissionLevelDensityParameterINCLXX::fNucData private
Definition at line 86 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 86 of file G4FissionLevelDensityParameterINCLXX.hh
Referenced by G4FissionLevelDensityParameterINCLXX(), and LevelDensityParameter().
int G4FissionLevelDensityParameterINCLXX::ZHigh private
Definition at line 89 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 89 of file G4FissionLevelDensityParameterINCLXX.hh
Referenced by getZHigh(), LevelDensityParameter(), setZHigh(), and UpdateAfanSlope().
int G4FissionLevelDensityParameterINCLXX::ZLow private
Definition at line 89 of file G4FissionLevelDensityParameterINCLXX.hh.
View newest version in sPHENIX GitHub at line 89 of file G4FissionLevelDensityParameterINCLXX.hh
Referenced by getZLow(), LevelDensityParameter(), setZLow(), and UpdateAfanSlope().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/include/G4FissionLevelDensityParameterINCLXX.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fission/src/G4FissionLevelDensityParameterINCLXX.cc