ECCE @ EIC Software: G4BaseFileManager Class Reference
G4BaseFileManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4BaseFileManager.hh>
Public Member Functions
G4BaseFileManager (const G4AnalysisManagerState &state)
virtual ~G4BaseFileManager ()
virtual G4bool SetFileName (const G4String &fileName)
G4String GetFileName () const
G4String GetFullFileName (const G4String &baseFileName="", G4bool isPerThread=true) const
G4String GetHnFileName (const G4String &hnType, const G4String &hnName) const
G4String GetNtupleFileName (const G4String &ntupleName) const
G4String GetNtupleFileName (G4int ntupleFileNumber) const
G4String GetPlotFileName () const
G4String GetFileType () const
Protected Member Functions
G4String TakeOffExtension (G4String &name) const
Protected Attributes
const G4AnalysisManagerState & fState
G4String fFileName
Detailed Description
Definition at line 37 of file G4BaseFileManager.hh.
View newest version in sPHENIX GitHub at line 37 of file G4BaseFileManager.hh
Constructor & Destructor Documentation
G4BaseFileManager::G4BaseFileManager (const G4AnalysisManagerState & state) explicit
Definition at line 34 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 34 of file G4BaseFileManager.cc
G4BaseFileManager::~G4BaseFileManager () virtual
Definition at line 41 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 41 of file G4BaseFileManager.cc
Member Function Documentation
G4String G4BaseFileManager::GetFileName () const inline
Definition at line 94 of file G4BaseFileManager.hh.
View newest version in sPHENIX GitHub at line 94 of file G4BaseFileManager.hh
References fFileName.
G4String G4BaseFileManager::GetFileType () const
Definition at line 174 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 174 of file G4BaseFileManager.cc
References fState, G4AnalysisManagerState::GetType(), and G4String::toLower().
Referenced by TakeOffExtension().
G4String G4BaseFileManager::GetFullFileName (const G4String & baseFileName = "", G4bool isPerThread = true) const
Definition at line 69 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 69 of file G4BaseFileManager.cc
References G4String::append(), fFileName, fState, G4Threading::G4GetThreadId(), G4AnalysisManagerState::GetIsMaster(), and TakeOffExtension().
Referenced by G4RootFileManager::CloseFile(), G4Hdf5FileManager::CloseFile(), G4XmlFileManager::CloseHnFile(), G4XmlFileManager::CreateHnFile(), G4CsvAnalysisReader::GetHnFileName(), G4Hdf5RFileManager::GetRFile(), G4XmlRFileManager::GetRFile(), G4RootRFileManager::GetRFile(), G4RootFileManager::OpenFile(), G4Hdf5FileManager::OpenFile(), G4XmlRFileManager::OpenRFile(), G4RootRFileManager::OpenRFile(), G4Hdf5RFileManager::OpenRFile(), G4Hdf5AnalysisReader::ReadNtupleImpl(), and G4RootFileManager::WriteFile().
G4String G4BaseFileManager::GetHnFileName (const G4String & hnType, const G4String & hnName) const
Definition at line 139 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 139 of file G4BaseFileManager.cc
References G4String::append(), fFileName, and TakeOffExtension().
Referenced by G4CsvAnalysisReader::GetHnFileName().
G4String G4BaseFileManager::GetNtupleFileName (const G4String & ntupleName) const
Definition at line 93 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 93 of file G4BaseFileManager.cc
References G4String::append(), fFileName, fState, G4Threading::G4GetThreadId(), G4AnalysisManagerState::GetIsMaster(), and TakeOffExtension().
Referenced by G4RootFileManager::CloseFile(), G4CsvFileManager::CloseNtupleFile(), G4XmlFileManager::CloseNtupleFile(), G4CsvFileManager::CreateNtupleFile(), G4XmlFileManager::CreateNtupleFile(), G4RootFileManager::OpenNtupleFiles(), G4CsvAnalysisReader::ReadNtupleImpl(), G4XmlAnalysisReader::ReadNtupleImpl(), and G4RootFileManager::WriteFile().
G4String G4BaseFileManager::GetNtupleFileName (G4int ntupleFileNumber) const
Definition at line 119 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 119 of file G4BaseFileManager.cc
References G4String::append(), fFileName, and TakeOffExtension().
G4String G4BaseFileManager::GetPlotFileName () const
Definition at line 160 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 160 of file G4BaseFileManager.cc
References G4String::append(), fFileName, and TakeOffExtension().
G4bool G4BaseFileManager::SetFileName (const G4String & fileName) inline virtual
Reimplemented in G4VFileManager.
Definition at line 89 of file G4BaseFileManager.hh.
View newest version in sPHENIX GitHub at line 89 of file G4BaseFileManager.hh
References fFileName.
Referenced by G4VFileManager::SetFileName().
G4String G4BaseFileManager::TakeOffExtension (G4String & name) const protected
Definition at line 50 of file G4BaseFileManager.cc.
View newest version in sPHENIX GitHub at line 50 of file G4BaseFileManager.cc
References G4String::append(), and GetFileType().
Referenced by GetFullFileName(), GetHnFileName(), GetNtupleFileName(), and GetPlotFileName().
Member Data Documentation
G4String G4BaseFileManager::fFileName protected
Definition at line 86 of file G4BaseFileManager.hh.
View newest version in sPHENIX GitHub at line 86 of file G4BaseFileManager.hh
Referenced by GetFileName(), GetFullFileName(), GetHnFileName(), GetNtupleFileName(), GetPlotFileName(), G4CsvFileManager::OpenFile(), G4RootFileManager::OpenFile(), G4XmlFileManager::OpenFile(), G4Hdf5FileManager::OpenFile(), and SetFileName().
const G4AnalysisManagerState& G4BaseFileManager::fState protected
Definition at line 85 of file G4BaseFileManager.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BaseFileManager.hh
Referenced by G4Hdf5FileManager::CloseFile(), G4XmlFileManager::CloseHnFile(), G4CsvFileManager::CloseNtupleFile(), G4XmlFileManager::CloseNtupleFile(), G4Hdf5FileManager::CreateDirectory(), G4RootFileManager::CreateHistoDirectory(), G4XmlFileManager::CreateHnFile(), G4RootFileManager::CreateNtupleDirectory(), G4CsvFileManager::CreateNtupleFile(), G4XmlFileManager::CreateNtupleFile(), GetFileType(), GetFullFileName(), GetNtupleFileName(), G4Hdf5RFileManager::OpenDirectory(), G4RootFileManager::OpenFile(), G4RootFileManager::OpenNtupleFiles(), G4CsvRFileManager::OpenRFile(), G4XmlRFileManager::OpenRFile(), G4RootRFileManager::OpenRFile(), and G4Hdf5RFileManager::OpenRFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4BaseFileManager.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4BaseFileManager.cc