ECCE @ EIC Software: G4BestUnit Class Reference
G4BestUnit Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4UnitsTable.hh>
Public Member Functions
G4BestUnit (G4double internalValue, const G4String &category)
G4BestUnit (const G4ThreeVector &internalValue, const G4String &category)
~G4BestUnit ()
G4double * GetValue ()
const G4String & GetCategory () const
size_t GetIndexOfCategory () const
operator G4String () const
Private Attributes
G4double Value [3]
G4int nbOfVals
G4String Category
size_t IndexOfCategory
Friends
std::ostream & operator<< (std::ostream &, G4BestUnit VU)
Detailed Description
Definition at line 173 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 173 of file G4UnitsTable.hh
Constructor & Destructor Documentation
G4BestUnit::G4BestUnit (G4double internalValue, const G4String & category)
Definition at line 483 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 483 of file G4UnitsTable.cc
References FatalException, G4cout, G4endl, G4Exception(), G4UnitDefinition::GetUnitsTable(), IndexOfCategory, and Value.
G4BestUnit::G4BestUnit (const G4ThreeVector & internalValue, const G4String & category)
Definition at line 507 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 507 of file G4UnitsTable.cc
References FatalException, G4cerr, G4endl, G4Exception(), G4UnitDefinition::GetUnitsTable(), IndexOfCategory, Value, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4BestUnit::~G4BestUnit ()
Definition at line 530 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 530 of file G4UnitsTable.cc
Member Function Documentation
const G4String& G4BestUnit::GetCategory () const inline
Referenced by export_G4UnitsTable().
size_t G4BestUnit::GetIndexOfCategory () const inline
Referenced by export_G4UnitsTable().
G4double* G4BestUnit::GetValue () inline
G4BestUnit::operator G4String () const
Definition at line 535 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 535 of file G4UnitsTable.cc
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & flux, G4BestUnit VU) friend
Definition at line 544 of file G4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 544 of file G4UnitsTable.cc
Member Data Documentation
G4String G4BestUnit::Category private
Definition at line 201 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 201 of file G4UnitsTable.hh
size_t G4BestUnit::IndexOfCategory private
Definition at line 202 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 202 of file G4UnitsTable.hh
Referenced by G4BestUnit(), and operator<<().
G4int G4BestUnit::nbOfVals private
Definition at line 200 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 200 of file G4UnitsTable.hh
Referenced by operator<<().
G4double G4BestUnit::Value[3] private
Definition at line 199 of file G4UnitsTable.hh.
View newest version in sPHENIX GitHub at line 199 of file G4UnitsTable.hh
Referenced by G4BestUnit(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4UnitsTable.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4UnitsTable.cc