ECCE @ EIC Software: G4HadronElasticProcess Class Reference
G4HadronElasticProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/include/G4HadronElasticProcess.hh>
Public Member Functions
G4HadronElasticProcess (const G4String &procName="hadElastic")
~G4HadronElasticProcess () override
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual void SetLowestEnergy (G4double)
virtual void SetLowestEnergyNeutron (G4double)
void ProcessDescription (std::ostream &outFile) const override
void SetDiffraction (G4HadronicInteraction *, G4VCrossSectionRatio *)
Public Member Functions inherited from G4HadronicProcess
G4HadronicProcess (const G4String &processName="Hadronic", G4ProcessType procType=fHadronic)
G4HadronicProcess (const G4String &processName, G4HadronicProcessType subType)
~G4HadronicProcess () override
void RegisterMe (G4HadronicInteraction *a)
G4double GetElementCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
G4double GetMicroscopicCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
void PreparePhysicsTable (const G4ParticleDefinition &) override
void BuildPhysicsTable (const G4ParticleDefinition &) override
void DumpPhysicsTable (const G4ParticleDefinition &p)
void AddDataSet (G4VCrossSectionDataSet *aDataSet)
std::vector
< G4HadronicInteraction * > & GetHadronicInteractionList ()
G4HadronicInteraction * GetHadronicModel (const G4String &)
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *) override
const G4Nucleus * GetTargetNucleus () const
const G4Isotope * GetTargetIsotope ()
void BiasCrossSectionByFactor (G4double aScale)
void MultiplyCrossSectionBy (G4double factor)
G4double CrossSectionFactor () const
void SetIntegral (G4bool val)
void SetEpReportLevel (G4int level)
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
std::pair< G4double, G4double > GetEnergyMomentumCheckLevels () const
G4CrossSectionDataStore * GetCrossSectionDataStore ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4HadronElasticProcess & operator= (const G4HadronElasticProcess &right)
G4HadronElasticProcess (const G4HadronElasticProcess &)
void PrintWarning (const G4String &) const
Private Attributes
G4HadronicInteraction * fDiffraction
G4VCrossSectionRatio * fDiffractionRatio
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4HadronicProcess
G4HadronicInteraction * ChooseHadronicInteraction (const G4HadProjectile &aHadProjectile, G4Nucleus &aTargetNucleus, const G4Material *aMaterial, const G4Element *anElement)
G4Nucleus * GetTargetNucleusPointer ()
void DumpState (const G4Track &, const G4String &, G4ExceptionDescription &)
G4HadronicInteraction * GetHadronicInteraction () const
G4double GetLastCrossSection ()
void FillResult (G4HadFinalState *aR, const G4Track &aT)
G4HadFinalState * CheckResult (const G4HadProjectile &thePro, const G4Nucleus &targetNucleus, G4HadFinalState *result)
void CheckEnergyMomentumConservation (const G4Track &, const G4Nucleus &)
Protected Attributes inherited from G4HadronicProcess
G4HadProjectile thePro
G4ParticleChange * theTotalResult
G4double fWeight
G4int epReportLevel
Detailed Description
Definition at line 49 of file G4HadronElasticProcess.hh.
View newest version in sPHENIX GitHub at line 49 of file G4HadronElasticProcess.hh
Constructor & Destructor Documentation
G4HadronElasticProcess::G4HadronElasticProcess (const G4String & procName = "hadElastic") explicit
Definition at line 46 of file G4HadronElasticProcess.cc.
View newest version in sPHENIX GitHub at line 46 of file G4HadronElasticProcess.cc
G4HadronElasticProcess::~G4HadronElasticProcess () override
Definition at line 51 of file G4HadronElasticProcess.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HadronElasticProcess.cc
G4HadronElasticProcess::G4HadronElasticProcess (const G4HadronElasticProcess &) private
Member Function Documentation
G4HadronElasticProcess& G4HadronElasticProcess::operator= (const G4HadronElasticProcess & right) private
G4VParticleChange * G4HadronElasticProcess::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4HadronicProcess.
Definition at line 62 of file G4HadronElasticProcess.cc.
View newest version in sPHENIX GitHub at line 62 of file G4HadronElasticProcess.cc
References G4ParticleChange::AddSecondary(), G4HadronicInteraction::ApplyYourself(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4HadronicProcess::CheckResult(), G4HadronicProcess::ChooseHadronicInteraction(), G4HadFinalState::Clear(), G4VParticleChange::Clear(), G4VProcess::ClearNumberOfInteractionLengthLeft(), G4VCrossSectionRatio::ComputeRatio(), G4HadronicProcess::DumpState(), edep, G4HadronicProcess::epReportLevel, fAlive, FatalException, fDiffraction, fDiffractionRatio, G4HadronicProcess::FillResult(), fStopAndKill, fStopButAlive, G4cout, G4endl, G4Exception(), G4UniformRand, G4Nucleus::GetA_asInt(), G4ProcessManager::GetAtRestProcessVector(), G4HadronicProcess::GetCrossSectionDataStore(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4HadFinalState::GetEnergyChange(), G4ProductionCutsTable::GetEnergyCutsVector(), G4Track::GetGlobalTime(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetKineticEnergy(), G4HadFinalState::GetLocalEnergyDeposit(), G4Track::GetMaterial(), G4Track::GetMaterialCutsCouple(), G4HadronicInteraction::GetModelName(), G4HadFinalState::GetMomentumChange(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4Element::GetName(), G4Material::GetName(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), G4ParticleDefinition::GetProcessManager(), G4ProductionCutsTable::GetProductionCutsTable(), G4HadFinalState::GetSecondary(), G4HadronicProcess::GetTargetNucleusPointer(), G4Track::GetTouchableHandle(), G4Track::GetTrackStatus(), G4HadProjectile::GetTrafoToLab(), G4Track::GetWeight(), G4Nucleus::GetZ_asInt(), incremental_prev_tag::idx, G4ParticleChange::Initialize(), material(), max, part, G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeNonIonizingEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeWeight(), ratio, G4HadronicException::Report(), CLHEP::Hep3Vector::rotateUz(), G4CrossSectionDataStore::SampleZandA(), G4DynamicParticle::SetMomentumDirection(), G4VParticleChange::SetNumberOfSecondaries(), G4HadronicInteraction::SetRecoilEnergyThreshold(), G4Track::SetTouchableHandle(), G4HadFinalState::SetTrafoToLab(), G4Track::SetWeight(), G4ProcessVector::size(), t, G4HadronicProcess::theTotalResult, G4VProcess::verboseLevel, and weight.
void G4HadronElasticProcess::PrintWarning (const G4String & tit) const private
Definition at line 272 of file G4HadronElasticProcess.cc.
View newest version in sPHENIX GitHub at line 272 of file G4HadronElasticProcess.cc
References G4Exception(), and JustWarning.
Referenced by SetLowestEnergy(), and SetLowestEnergyNeutron().
void G4HadronElasticProcess::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4HadronicProcess.
Definition at line 54 of file G4HadronElasticProcess.cc.
View newest version in sPHENIX GitHub at line 54 of file G4HadronElasticProcess.cc
void G4HadronElasticProcess::SetDiffraction (G4HadronicInteraction * hi, G4VCrossSectionRatio * xsr)
Definition at line 263 of file G4HadronElasticProcess.cc.
View newest version in sPHENIX GitHub at line 263 of file G4HadronElasticProcess.cc
References fDiffraction, and fDiffractionRatio.
Referenced by G4HadronHElasticPhysics::ConstructProcess().
void G4HadronElasticProcess::SetLowestEnergy (G4double) virtual
Definition at line 252 of file G4HadronElasticProcess.cc.
View newest version in sPHENIX GitHub at line 252 of file G4HadronElasticProcess.cc
References PrintWarning().
void G4HadronElasticProcess::SetLowestEnergyNeutron (G4double) virtual
Definition at line 258 of file G4HadronElasticProcess.cc.
View newest version in sPHENIX GitHub at line 258 of file G4HadronElasticProcess.cc
References PrintWarning().
Member Data Documentation
G4HadronicInteraction* G4HadronElasticProcess::fDiffraction private
Definition at line 79 of file G4HadronElasticProcess.hh.
View newest version in sPHENIX GitHub at line 79 of file G4HadronElasticProcess.hh
Referenced by PostStepDoIt(), and SetDiffraction().
G4VCrossSectionRatio* G4HadronElasticProcess::fDiffractionRatio private
Definition at line 80 of file G4HadronElasticProcess.hh.
View newest version in sPHENIX GitHub at line 80 of file G4HadronElasticProcess.hh
Referenced by PostStepDoIt(), and SetDiffraction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/include/G4HadronElasticProcess.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/processes/src/G4HadronElasticProcess.cc