ECCE @ EIC Software: G4SampleResonance Class Reference
G4SampleResonance Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4SampleResonance.hh>
Public Types
typedef std::map< const
G4ParticleDefinition
*, G4double, std::less< const
G4ParticleDefinition * >
>::const_iterator minMassMapIterator
typedef std::map< const
G4ParticleDefinition
*, G4double, std::less< const
G4ParticleDefinition * > > minMassMapType
Public Member Functions
G4double GetMinimumMass (const G4ParticleDefinition *p) const
G4double SampleMass (const G4double poleMass, const G4double gamma, const G4double minMass, const G4double maxMass) const
G4double SampleMass (const G4ParticleDefinition *p, const G4double maxMass) const
Private Member Functions
G4double BrWigInt0 (const G4double x, const G4double gamma, const G4double m0) const
G4double BrWigInt1 (const G4double x, const G4double gamma, const G4double m0) const
G4double BrWigInv (const G4double x, const G4double gamma, const G4double m0) const
Static Private Attributes
static G4ThreadLocal
minMassMapType * minMassCache_G4MT_TLS_ = 0
Detailed Description
Definition at line 43 of file G4SampleResonance.hh.
View newest version in sPHENIX GitHub at line 43 of file G4SampleResonance.hh
Member Typedef Documentation
typedef std::map<const G4ParticleDefinition*, G4double, std::less<const G4ParticleDefinition*> >::const_iterator G4SampleResonance::minMassMapIterator
Definition at line 67 of file G4SampleResonance.hh.
View newest version in sPHENIX GitHub at line 67 of file G4SampleResonance.hh
typedef std::map<const G4ParticleDefinition*, G4double, std::less<const G4ParticleDefinition*> > G4SampleResonance::minMassMapType
Definition at line 68 of file G4SampleResonance.hh.
View newest version in sPHENIX GitHub at line 68 of file G4SampleResonance.hh
Member Function Documentation
G4double G4SampleResonance::BrWigInt0 (const G4double x, const G4double gamma, const G4double m0) const inline private
Definition at line 56 of file G4SampleResonance.hh.
View newest version in sPHENIX GitHub at line 56 of file G4SampleResonance.hh
Referenced by BrWigInt1(), and SampleMass().
G4double G4SampleResonance::BrWigInt1 (const G4double x, const G4double gamma, const G4double m0) const inline private
Definition at line 59 of file G4SampleResonance.hh.
View newest version in sPHENIX GitHub at line 59 of file G4SampleResonance.hh
References BrWigInt0(), and G4Log().
G4double G4SampleResonance::BrWigInv (const G4double x, const G4double gamma, const G4double m0) const inline private
Definition at line 62 of file G4SampleResonance.hh.
View newest version in sPHENIX GitHub at line 62 of file G4SampleResonance.hh
Referenced by SampleMass().
G4double G4SampleResonance::GetMinimumMass (const G4ParticleDefinition * p) const
Definition at line 46 of file G4SampleResonance.cc.
View newest version in sPHENIX GitHub at line 46 of file G4SampleResonance.cc
References DBL_MAX, G4DecayTable::entries(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4VDecayChannel::GetNumberOfDaughters(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::IsShortLived(), and minMassCache_G4MT_TLS_.
Referenced by G4KineticTrack::Decay(), G4DiffractiveExcitation::ExciteParticipants(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4ExcitedStringDecay::FragmentStrings(), G4KineticTrack::G4KineticTrack(), and SampleMass().
G4double G4SampleResonance::SampleMass (const G4double poleMass, const G4double gamma, const G4double minMass, const G4double maxMass) const
Definition at line 110 of file G4SampleResonance.cc.
View newest version in sPHENIX GitHub at line 110 of file G4SampleResonance.cc
References BrWigInt0(), BrWigInv(), DBL_EPSILON, f, G4UniformRand, max, min, and minMassCache_G4MT_TLS_.
Referenced by G4KineticTrack::Decay(), G4DiffractiveExcitation::ExciteParticipants_doChargeExchange(), G4ExcitedStringDecay::FragmentStrings(), and SampleMass().
G4double G4SampleResonance::SampleMass (const G4ParticleDefinition * p, const G4double maxMass) const
Definition at line 104 of file G4SampleResonance.cc.
View newest version in sPHENIX GitHub at line 104 of file G4SampleResonance.cc
References GetMinimumMass(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGWidth(), minMassCache_G4MT_TLS_, and SampleMass().
Member Data Documentation
G4ThreadLocal G4SampleResonance::minMassMapType * G4SampleResonance::minMassCache_G4MT_TLS_ = 0 static private
Definition at line 72 of file G4SampleResonance.hh.
View newest version in sPHENIX GitHub at line 72 of file G4SampleResonance.hh
Referenced by GetMinimumMass(), and SampleMass().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4SampleResonance.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4SampleResonance.cc