ECCE @ EIC Software: fun4all_eicdetectors/blob/master/simulation/g4simulation/g4mrich/PHG4mRICHDetector.cc File Reference
PHG4mRICHDetector.cc File Reference
#include "PHG4mRICHDetector.h"
#include <phparameter/PHParameters.h>
#include <fun4all/Fun4AllBase.h>
#include <g4main/PHG4Detector.h>
#include <Geant4/G4AssemblyVolume.hh>
#include <Geant4/G4Box.hh>
#include <Geant4/G4LogicalBorderSurface.hh>
#include <Geant4/G4LogicalVolume.hh>
#include <Geant4/G4Material.hh>
#include <Geant4/G4MaterialPropertiesTable.hh>
#include <Geant4/G4OpticalSurface.hh>
#include <Geant4/G4PVPlacement.hh>
#include <Geant4/G4PhysicalConstants.hh>
#include <Geant4/G4Polycone.hh>
#include <Geant4/G4Polyhedra.hh>
#include <Geant4/G4RotationMatrix.hh>
#include <Geant4/G4SurfaceProperty.hh>
#include <Geant4/G4SystemOfUnits.hh>
#include <Geant4/G4ThreeVector.hh>
#include <Geant4/G4Types.hh>
#include <Geant4/G4VPhysicalVolume.hh>
#include <Geant4/G4VisAttributes.hh>
#include <Geant4/G4ios.hh>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <iostream>
#include <iterator>
#include <string>
Functions
pos (G4ThreeVector(0 *mm, 0 *mm, 0 *mm))
start (0.)
theta (0.)
numSide (0)
num_zLayer (0)
material (GetDetectorMaterial("G4_AIR"))
sensitivity (0)
color (G4Colour(0, 0, 0, 0))
visibility (false)
wireframe (false)
surface (false)
Function Documentation
color (G4Colour(0, 0, 0, 0))
Referenced by cheprep::DefaultHepRepAttribute::addAttValue(), G4GMocrenFileSceneHandler::AddDetector(), G4GMocrenFileSceneHandler::AddPrimitive(), PHG4TpcDisplayAction::ApplyDisplayAction(), Acts::Test::BOOST_AUTO_TEST_CASE(), G4GMocrenFileSceneHandler::Detector::clear(), G03ColorReader::ColorRead(), G03ColorWriter::ColorWrite(), PHG4MicromegasDetector::construct_micromegas(), PHG4CylinderStripDetector::ConstructMe(), Par01EnergySpot::Draw(), H02MuonHit::Draw(), G4ScoreLogColorMap::DrawColorChartText(), G4VScoreColorMap::DrawColorChartText(), kdfinder::export_candidates_json(), kdfinder::export_candidates_json_old(), PHTpcEventExporter::exportEvent(), Acts::ObjVisualization< T >::face(), Acts::ObjVisualization< T >::faces(), G4GMocrenIO::getDetector(), G4GMocrenIO::getTrack(), Acts::ObjVisualization< T >::line(), Plot(), ProcessSingleFile(), G4HepRepSceneHandler::setAttribute(), setHistStyle(), Acts::Frustum< value_t, DIM, SIDES >::svg(), Acts::AxisAlignedBoundingBox< entity_t, value_t, DIM >::svg(), and Acts::ObjVisualization< T >::vertex().
material (GetDetectorMaterial("G4_AIR"))
Referenced by G4RDVCrossSectionHandler::ActiveElements(), G4VCrossSectionHandler::ActiveElements(), G4PixeCrossSectionHandler::ActiveElements(), CCalMaterialFactory::addCCalMaterial(), G4HepRepFileSceneHandler::AddHepRepInstance(), PHG4TpcEndCapDetector::AddLayer(), G4Material::AddMaterial(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4hImpactIonisation::AlongStepDoIt(), G4hImpactIonisation::AntiProtonParametrisedDEDX(), G4hImpactIonisation::BarkasTerm(), RunAction::BeginOfRunAction(), SteppingAction::BirksAttenuation(), G4hImpactIonisation::BlochTerm(), Acts::Test::BOOST_AUTO_TEST_CASE(), G4AugerData::BuildAugerTransitionTable(), G4RDAugerData::BuildAugerTransitionTable(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), G4hImpactIonisation::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4ScreenedCoulombCrossSection::BuildMFPTables(), G4OpRayleigh::BuildPhysicsTable(), G4hImpactIonisation::BuildPhysicsTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4IonParametrisedLossModel::BuildRangeVector(), Acts::PassiveLayerBuilder::centralLayers(), G4hImpactIonisation::ComputeDEDX(), G4BetheBlochModel::ComputeDEDXPerVolume(), G4MIRDRightKidney::Construct(), G4MIRDRightScapula::Construct(), G4VoxelLeftBreast::Construct(), G4VoxelRightBreast::Construct(), G4MIRDLeftLegBone::Construct(), G4MIRDLiver::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDRightLeg::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDSkull::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDThyroid::Construct(), G4MIRDBrain::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDLeftLung::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDPelvis::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDRightOvary::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightTeste::Construct(), G4MIRDSpleen::Construct(), G4MIRDStomach::Construct(), G4MIRDTrunk::Construct(), G4MIRDThymus::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDHead::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDPancreas::Construct(), G4MIRDRightArmBone::Construct(), G4MIRDUrinaryBladder::Construct(), DetectorConstruction0::Construct(), PHG4MicromegasDetector::construct_micromegas(), PHG4TpcEndCapDetector::ConstructElectronics(), PHG4TpcEndCapDetector::ConstructEndCapAssembly(), PHG4EPDDetector::ConstructMe(), PHG4TpcDetector::ConstructTpcCageVolume(), PHG4TpcDetector::ConstructTpcGasVolume(), PHG4TpcEndCapDetector::ConstructWagonWheel(), G4IonParametrisedLossModel::CorrectionsAlongStep(), RunAction::CriticalEnergy(), G4BraggModel::DEDX(), G4BraggIonModel::DEDX(), G4LowEnergyIonisation::DeexciteAtom(), G4hImpactIonisation::DeltaRaysEnergy(), Acts::Test::DetectorElementStub::DetectorElementStub(), G4DNABrownianTransportation::Diffusion(), G4ionEffectiveCharge::EffectiveCharge(), G4hImpactIonisation::ElectronicLossFluctuation(), Acts::PassiveLayerBuilder::endcapLayers(), Run::EndOfRun(), WLSDetectorConstruction::FindMaterial(), G3toG4BuildLVTree(), G4gsmate(), G4gsmixt(), G4gstmed(), G4RDShellVacancy::GenerateNumberOfIonisations(), G4ShellVacancy::GenerateNumberOfIonisations(), G4hImpactIonisation::GetConstraints(), G4DNAModelInterface::GetDNAModel(), RunAction::GetEnergyCut(), G4VDNAModel::GetHighELimit(), G4ParticleHPFissionData::GetIsoCrossSection(), G4ParticleHPCaptureData::GetIsoCrossSection(), G4ParticleHPElasticData::GetIsoCrossSection(), G4ParticleHPInelasticData::GetIsoCrossSection(), G4ParticleHPThermalScatteringData::GetIsoCrossSection(), G4VDNAModel::GetLowELimit(), CML2AccSaturn::getMaterial(), G4OpRayleigh::GetMeanFreePath(), G4hImpactIonisation::GetMeanFreePath(), G4LowEnergyPhotoElectric::GetMeanFreePath(), G4LivermoreRayleighModel::Initialise(), G4LivermoreGammaConversionModelRC::Initialise(), G4LivermoreNuclearGammaConversionModel::Initialise(), G4BoldyshevTripletModel::Initialise(), G4LivermorePolarizedPhotoElectricGDModel::Initialise(), G4LivermorePolarizedGammaConversionModel::Initialise(), G4LivermoreComptonModel::Initialise(), G4LivermorePolarizedPhotoElectricModel::Initialise(), G4LivermorePhotoElectricModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4JAEAElasticScatteringModel::Initialise(), G4LivermorePolarizedComptonModel::Initialise(), G4PenelopeGammaConversionModel::Initialise(), G4PenelopeRayleighModel::Initialise(), G4PenelopePhotoElectricModel::Initialise(), G4mplIonisationModel::Initialise(), G4mplIonisationWithDeltaModel::Initialise(), G4LowEPComptonModel::Initialise(), G4IonParametrisedLossModel::Initialise(), G4LowEPPolarizedComptonModel::Initialise(), G4EmModelManager::Initialise(), G4VEmModel::InitialiseElementSelectors(), CML2Acc1::ionizationChamber(), G4RDBremsstrahlungParameters::LoadData(), G4BremsstrahlungParameters::LoadData(), G4RDeIonisationParameters::LoadData(), G4eIonisationParameters::LoadData(), G4NativeScreenedCoulombCrossSection::LoadData(), main(), make_barrel_layer_basic(), make_barrel_layer_LYSO_basic(), FCALMaterialConsultant::Material(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), G4GDMLReadMaterials::MaterialRead(), DetectorConstruction::MaterialWithSingleIsotope(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), molecule(), operator<<(), DetectorConstruction::OtherMaterial(), DNAParser::ParseFile(), PlugDoor(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4hImpactIonisation::PrintInfoDefinition(), G4hImpactIonisation::ProtonParametrisedDEDX(), G4PropagatorInField::ReportLoopingParticle(), G4TransportationLogger::ReportLoopingTrack(), G4BohrFluctuations::SampleFluctuations(), G4UniversalFluctuation::SampleFluctuations(), G4AtimaFluctuations::SampleFluctuations(), G4IonFluctuations::SampleFluctuations(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VCrossSectionHandler::SelectRandomAtom(), G4RDVCrossSectionHandler::SelectRandomElement(), G4VCrossSectionHandler::SelectRandomElement(), G4ScreenedCoulombCrossSection::SelectRandomUnweightedTarget(), F03DetectorConstruction::SetAbsorberMaterial(), F01DetectorConstruction::SetAbsorberMaterial(), F02DetectorConstruction::SetAbsorberMaterial(), G4VDNAModel::SetHighELimit(), G4VDNAModel::SetLowELimit(), G3MedTableEntry::SetMaterial(), G4MaterialCutsCouple::SetMaterial(), PHG4EICForwardEcalDetector::SetMaterialAbsorber(), PHG4ForwardDualReadoutDetector::SetMaterialAbsorber(), PHG4EICForwardEcalDetector::SetMaterialScintillator(), PHG4ForwardDualReadoutDetector::SetMaterialScintillator(), G4DNAMolecularMaterial::SetMolecularConfiguration(), DetectorConstruction::SetTargetMaterial(), F03DetectorConstruction::SetWorldMaterial(), F02DetectorConstruction::SetWorldMaterial(), F01DetectorConstruction::SetWorldMaterial(), G4IonDEDXScalingICRU73::UpdateCacheMaterial(), G4IonParametrisedLossModel::UpdateDEDXCache(), STCyclotronDetectorConstruction::UpdateFoilMaterial(), STCyclotronDetectorConstruction::UpdateMaterial(), G4IonParametrisedLossModel::UpdateRangeCache(), FW::Geant4::MMSteppingAction::UserSteppingAction(), and G4MSSteppingAction::UserSteppingAction().
num_zLayer (0)
numSide (0)
Referenced by STCyclotronDetectorConstruction::Construct(), and G4GenericPolycone::CreatePolyhedron().
pos (G4ThreeVector(0 *mm, 0 *mm, 0 *mm))
Referenced by CML2ExpVoxels::add(), G4AdjointCrossSurfChecker::AddaSphericalSurface(), G4HepRepSceneHandler::addAttVals(), EICG4LumiDetector::AddExitWindowForV3(), G4TessellatedSolid::AddFacet(), HistoManager::AddLeakingParticle(), G4ITReactionSet::AddReaction(), G4Region::AddRootLogicalVolume(), HistoManager::AddTargetStep(), G4GDMLWriteStructure::AddVolumeAuxiliary(), PHG4GDMLWriteStructure::AddVolumeAuxiliary(), G4INCL::AvatarDumpAction::afterAvatarUserAction(), XrayTelAnalysis::analyseStepping(), PHG4TpcDirectLaser::AppendLaserTrack(), G4EmBiasingManager::ApplyDirectionalSplitting(), G4GDMLWriteStructure::AssemblyWrite(), dfe::FlatSet< T, Compare, Container >::at(), G4RDAugerTransition::AugerOriginatingShellId(), G4AugerTransition::AugerOriginatingShellId(), G4RDAugerTransition::AugerTransitionEnergy(), G4AugerTransition::AugerTransitionEnergy(), G4RDAugerTransition::AugerTransitionProbability(), G4AugerTransition::AugerTransitionProbability(), G4ShellData::BindingEnergy(), G4RDShellData::BindingEnergy(), G03ColorWriter::BookAttribute(), G4GDMLWriteSolids::BooleanWrite(), PHG4GDMLWriteSolids::BooleanWrite(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), G4NucleiModel::boundaryTransition(), G4INCL::InteractionAvatar::bringParticleInside(), PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_sector2(), PHG4mRICHDetector::build_mRICH_wall_eside(), PHG4mRICHDetector::build_mRICH_wall_eside_proj(), PHG4mRICHDetector::build_mRICH_wall_hside(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4Voxelizer::BuildReduceVoxels(), G4BinaryCascade::BuildTargetList(), ActsTransformations::calculateDCA(), ActsEvaluator::calculateDCA(), G4EmBiasingManager::CheckDirection(), G4PVParameterised::CheckOverlaps(), G4BinaryCascade::CheckPauliPrinciple(), G4RunManagerKernel::CheckRegularGeometry(), G4NucleiModel::choosePointAlongTraj(), PHActsSiliconSeeding::circleFitByTaubin(), DMXStackingAction::ClassifyNewTrack(), G4FieldManagerStore::Clean(), G4LogicalVolumeStore::Clean(), G4PhysicalVolumeStore::Clean(), G4RegionStore::Clean(), G4SolidStore::Clean(), G4AssemblyStore::Clean(), G4SurfaceProperty::CleanSurfacePropertyTable(), G4LogicalSkinSurface::CleanSurfaceTable(), G4LogicalBorderSurface::CleanSurfaceTable(), G4RDVCrossSectionHandler::Clear(), G4VCrossSectionHandler::Clear(), G4PixeCrossSectionHandler::Clear(), G4INCL::ClusteringModelIntercomparison::clusterCanEscape(), Acts::IntegrationTest::constant_field_propagation(), Acts::IntegrationTest::covariance_bound(), Acts::IntegrationTest::covariance_curvilinear(), DNAParser::CreateCutSolid(), DecayFinder::createDecayNode(), G3Division::CreateEnvelope(), Acts::createGrid2D(), Acts::createGrid3D(), KFParticle_DST::createParticleNode(), G4TessellatedSolid::CreateVertexList(), G4ChipsProtonInelasticXS::CrossSectionLin(), G4ChipsNeutronInelasticXS::CrossSectionLin(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::CrossSectionPerVolume(), G4DNABornIonisationModel1::CrossSectionPerVolume(), G4MicroElecElasticModel::CrossSectionPerVolume(), G4MuElecElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNACPA100ElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4MicroElecInelasticModel::CrossSectionPerVolume(), G4MuElecInelasticModel::CrossSectionPerVolume(), oncsSub_idcaenv1742::decode(), oncsSub_idfnalmwpc::decode(), oncsSub_idfnalmwpcv2::decode(), Packet_hbd_fpgashort::decode(), Packet_hbd_fpga::decode(), oncsSub_idmvtxv2::decode(), G4VFieldModel::DescribeYourselfTo(), G4MultiUnion::DistanceToIn(), G4ScoringBox::Draw(), G4ScoringBox::DrawColumn(), LXeTrajectory::DrawTrajectory(), RE01Trajectory::DrawTrajectory(), G4tgbGeometryDumper::DumpBooleanVolume(), Fun4AllHistoManager::dumpHistos(), G4LogicalSkinSurface::DumpInfo(), G4LogicalBorderSurface::DumpInfo(), G4tgbGeometryDumper::DumpPVPlacement(), EEMCH_Eval(), GFlashShowerModel::ElectronDoIt(), dfe::SmallVector< T, N, Allocator >::emplace(), CCalEventAction::EndOfEventAction(), G4BlineEventAction::EndOfEventAction(), G4KM_OpticalEqRhs::EvaluateRhsGivenB(), G4KM_NucleonEqRhs::EvaluateRhsGivenB(), G4RDeIonisationParameters::Excitation(), G4eIonisationParameters::Excitation(), FW::HitSmearing::execute(), FW::ParticleSmearing::execute(), PHTpcEventExporter::exportEvent(), Acts::fieldMapperRZ(), Acts::fieldMapperXYZ(), G4GDMLReadStructure::FileRead(), G4CascadParticle::fill(), Fill(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::fill(), G4CrystalUnitCell::FillAtomicUnitPos(), HelixHough::fillBins(), SvtxEvaluator::fillOutputNtuples(), KFParticle_DST::fillParticleNode_Particle(), KFParticle_DST::fillParticleNode_Track(), dfe::FlatSet< T, Compare, Container >::find(), kdfinder::find_vertex_seeds(), G4Absorber::FindAbsorbers(), findByPdg(), sPHENIXTracker::findHelicesParallelOneHelicity(), sPHENIXSeedFinder::findHelicesParallelOneHelicity(), PHG4GDMLWriteStructure::FindOpticalSurface(), G4GDMLWriteStructure::FindOpticalSurface(), G4MCTSimEvent::FindParticle(), G4RDVCrossSectionHandler::FindValue(), G4PixeCrossSectionHandler::FindValue(), G4VCrossSectionHandler::FindValue(), CML2AccSaturn::flatteningFilter(), PHTpcTrackFollower::followTrack(), Acts::IntegrationTest::foward_backward(), Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), Fun4All_runEvaluators(), G4AugerData::G4AugerData(), G4GenericMessenger::G4GenericMessenger(), G4RDAugerData::G4RDAugerData(), G4SmoothTrajectoryPoint::G4SmoothTrajectoryPoint(), G4TrajectoryPoint::G4TrajectoryPoint(), generate_distortion_map(), G4AdjointPrimaryGenerator::GenerateAdjointPrimaryVertex(), G4RDAtomicDeexcitation::GenerateAuger(), G4AtomicDeexcitation::GenerateAuger(), G4UAtomicDeexcitation::GenerateAuger(), AnnularFieldSim::GenerateDistortionMaps(), G4AdjointPrimaryGenerator::GenerateFwdPrimaryVertex(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), TSPrimaryGeneratorAction::GeneratePrimaries(), AnnularFieldSim::GenerateSeparateDistortionMaps(), PHTpcTrackFollower::get_projected_coordinate(), PHTpcTrackFollower::get_track_layer(), G4GDMLReadStructure::GetAssembly(), G4CrystalExtension::GetAtomPos(), RE01TrackerHit::GetAttDefs(), RE01CalorimeterHit::GetAttDefs(), RE04TrajectoryPoint::GetAttDefs(), Acts::SurfaceArray::SurfaceGridLookup< Axes >::getBinCenterImpl(), PHG4GDMLWriteStructure::GetBorderSurface(), G4GDMLWriteStructure::GetBorderSurface(), PHActsSiliconSeeding::getCharge(), G4LossTableManager::GetEnergyLossProcess(), pyG4MagneticField::CB_PyG4MagneticField::GetFieldValue(), G4BFieldIntegrationDriver::GetFieldValue(), G4MCTEvent::GetGenParticle(), XrayFluoSiLiDetectorType::GetInfData(), XrayFluoHPGeDetectorType::GetInfData(), MakeActsGeometry::getInttKeyFromNode(), MakeActsGeometry::getMvtxKeyFromNode(), GetNameAndPathOfExecutable(), G4DNABornIonisationModel1::GetPartialCrossSection(), AnnularFieldSim::GetPhiIndex(), AnnularFieldSim::GetPhiIndexAndCheckBounds(), G4ScoringBox::GetReplicaPosition(), G4MCTEvent::GetSimParticle(), PHG4GDMLWriteStructure::GetSkinSurface(), G4GDMLWriteStructure::GetSkinSurface(), XrayFluoHPGeDetectorType::GetSupData(), XrayFluoSiLiDetectorType::GetSupData(), G4LogicalSkinSurface::GetSurface(), G4LogicalBorderSurface::GetSurface(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G03ColorReader::GetVisAttribute(), G4GDMLReadStructure::GetVolumeAuxiliaryInformation(), Acts::globalToLocalFromBin(), gridBoxFactory(), PHTpcTrackFollower::hit_to_measurement(), Initialise_info(), HadrontherapyDetectorROGeometry::Initialize(), KFParticle_nTuple::initializeBranches(), G4NucleiModel::initializeCascad(), __1DSortOut::Insert(), G4KDMap::Insert(), dfe::FlatSet< T, Compare, Container >::insert_or_assign(), PHPointerList< T >::insertAt(), AllSiliconTrackerDetector::InsertVolumes(), G4BinaryLightIonReaction::Interact(), PHActsSiliconSeeding::lineFit(), AnnularFieldSim::load_analytic_spacecharge(), CML2ExpVoxels::loadData(), HadrontherapyRBE::LoadLEMTable(), main(), PHGenFitTrkFitter::MakeSvtxTrack(), PHG4TrackFastSim::MakeSvtxTrack(), B0TrackFastSim::MakeSvtxTrack(), Acts::materialMapperRZ(), Acts::materialMapperXYZ(), G4GDMLWriteSolids::MultiUnionWrite(), oncsSub_idmvtxv0::mvtx_decode(), oncsSub_idmvtxv1::mvtx_decode(), G4RDVCrossSectionHandler::NumberOfComponents(), G4VCrossSectionHandler::NumberOfComponents(), G4PixeCrossSectionHandler::NumberOfComponents(), G4RDAtomicTransitionManager::NumberOfReachableShells(), G4AtomicTransitionManager::NumberOfReachableShells(), G4RDAtomicTransitionManager::NumberOfShells(), G4AtomicTransitionManager::NumberOfShells(), operand(), FW::Options::operator>>(), PHGenFitTrkProp::OutputPHGenFitTrack(), G4RDBremsstrahlungParameters::Parameter(), G4RDeIonisationParameters::Parameter(), G4BremsstrahlungParameters::Parameter(), G4eIonisationParameters::Parameter(), DecayFinder::parseDecayDescriptor(), KFParticle_sPHENIX::parseDecayDescriptor(), G4DNARuddIonisationModel::PartialCrossSection(), G4DNARuddIonisationExtendedModel::PartialCrossSection(), PHG4TrackFastSim::PHG4HitToMeasurementCylinder(), B0TrackFastSim::PHG4HitToMeasurementCylinder(), PHG4TrackFastSim::PHG4HitToMeasurementVerticalPlane(), B0TrackFastSim::PHG4HitToMeasurementVerticalPlane(), G4STRead::PhysvolRead(), PHG4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteStructure::PhysvolWrite(), Piston(), __1DSortOut::PopOutMiddle(), PosFlip(), FW::HepMC3Vertex::position(), Fun4AllServer::Print(), G4RDeIonisationParameters::PrintData(), G4BremsstrahlungParameters::PrintData(), G4eIonisationParameters::PrintData(), G4RDBremsstrahlungParameters::PrintData(), G4RDVCrossSectionHandler::PrintData(), G4VCrossSectionHandler::PrintData(), G4PixeCrossSectionHandler::PrintData(), G4BinaryCascade::PrintKTVector(), KFParticle_DST::printNode(), PHTpcTracker::Process(), PHTruthVertexing::Process(), PHSimpleVertexFinder::process_event(), PHGenFitTrackProjection::process_event(), PHTpcCentralMembraneClusterizer::process_event(), PHG4TrackFastSim::process_event(), B0TrackFastSim::process_event(), ExN04MuonSD::ProcessHits(), RE05MuonSD::ProcessHits(), LXeScintSD::ProcessHits(), G4DopplerProfile::Profiles(), G4RDDopplerProfile::Profiles(), G4BinaryCascade::Propagate1H1(), G4DNAEmfietzoglouExcitationModel::RandomSelect(), G4DNACPA100ExcitationModel::RandomSelect(), G4MuElecInelasticModel::RandomSelect(), G4DNARuddIonisationModel::RandomSelect(), G4DNARuddIonisationExtendedModel::RandomSelect(), G4DNABornIonisationModel1::RandomSelect(), G4MicroElecInelasticModel::RandomSelect(), G4DNACPA100IonisationModel::RandomSelect(), G4DNAEmfietzoglouIonisationModel::RandomSelect(), G4VDNAModel::RandomSelectShell(), G4RDAtomicTransitionManager::ReachableShell(), G4AtomicTransitionManager::ReachableShell(), FW::CsvPlanarClusterReader::read(), dfe::io_dsv_impl::DsvReader< Delimiter >::read(), PHGenFitTrkProp::ReFitTrack(), PHGenFitTrkFitter::ReFitTrack(), Fun4AllHistoManager::registerHisto(), G4CollisionOutput::removeOutgoingNucleus(), G4CollisionOutput::removeOutgoingParticle(), G4Region::RemoveRootLogicalVolume(), nlohmann::json_pointer< BasicJsonType >::replace_substring(), G4ExtDEDXTable::RetrievePhysicsTable(), Acts::Test::runTest(), Run::ScoreNewTrack(), HistoManager::ScoreNewTrack(), G4RDVCrossSectionHandler::SelectRandomShell(), G4PixeCrossSectionHandler::SelectRandomShell(), G4VCrossSectionHandler::SelectRandomShell(), G4TessellatedSolid::SetAllUsingStack(), G4SafetyHelper::SetCurrentSafety(), G4ITSafetyHelper::SetCurrentSafety(), G4ErrorTrajState::SetData(), WLSUserTrackInformation::SetExitPosition(), ExN04PrimaryGeneratorAction::SetGenerator(), H02PrimaryGeneratorAction::SetGenerator(), InteractionInformation::SetInteractionPositionInCrystal(), DicomIntersectVolume::SetNewValue(), G4ErrorSurfaceTrajState::SetParameters(), G4ErrorFreeTrajState::SetParameters(), IORTDetectorConstruction::SetPhantomPosition(), HadrontherapyDetectorConstruction::SetPhantomPosition(), G4ErrorTrajState::SetPosition(), G4VUserParallelWorld::SetSensitiveDetector(), G4VUserDetectorConstruction::SetSensitiveDetector(), MedicalBeam::SetSourcePosition(), G4RDAtomicTransitionManager::Shell(), G4AtomicTransitionManager::Shell(), G4ShellData::ShellId(), G4RDShellData::ShellId(), G4RDShellData::ShellIdVector(), G4ShellData::ShellIdVector(), G4RDShellData::ShellOccupancyProbability(), G4ShellData::ShellOccupancyProbability(), G4ShellData::ShellVector(), G4RDShellData::ShellVector(), FW::HepMC3Event::shiftPositionTo(), G4TrajectoryDrawerUtils::SliceLine(), Acts::solenoidFieldMapper(), split(), nlohmann::json_pointer< BasicJsonType >::split(), G4RDFluoData::StartShellEnergy(), G4FluoData::StartShellEnergy(), G4RDFluoData::StartShellId(), G4FluoData::StartShellId(), G4RDFluoData::StartShellProb(), G4FluoData::StartShellProb(), Acts::AtlasStepper< bfield_t >::State::State(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::State::State(), Acts::AtlasStepper< ConstantBField >::step(), G4GDMLWriteStructure::StructureWrite(), AnnularFieldSim::sum_phislice_field_at(), Acts::SurfaceArrayCreator::surfaceArrayOnCylinder(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), Acts::SurfaceArrayCreator::surfaceArrayOnPlane(), PHG4GDMLWriteStructure::SurfacesWrite(), G4GDMLWriteStructure::SurfacesWrite(), PHGenFitTrkProp::SvtxTrackToPHGenFitTracks(), remote_msg_buffer::sync(), Acts::IntegrationTest::to_cylinder(), Acts::IntegrationTest::to_surface(), Tokenize(), G4RDAtomicTransitionManager::TotalNonRadiativeTransitionProbability(), G4RDAtomicTransitionManager::TotalRadiativeTransitionProbability(), G4AtomicTransitionManager::TotalRadiativeTransitionProbability(), PHGenFitTrkProp::TrackPropPatRec(), PHRaveVertexing::TranslateSvtxToGenFitTrack(), G4GDMLWriteStructure::TraverseVolumeTree(), sPHENIXTrackerTpc::tripletRejection(), sPHENIXTracker::tripletRejection(), sPHENIXSeedFinder::tripletRejection(), PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement(), Acts::AtlasStepper< ConstantBField >::update(), G4Channeling::UpdateParameters(), G4CascadParticle::updatePosition(), G4ErrorTrajState::UpdatePosMom(), PHActsVertexPropagator::updateTrackDCA(), PHActsVertexFinder::updateTrackDCA(), doiPETSteppingAction::UserSteppingAction(), G4RDFluoData::VacancyId(), G4FluoData::VacancyId(), PHG4TrackFastSim::VertexMeasurement(), B0TrackFastSim::VertexMeasurement(), FW::RootPlanarClusterWriter::writeT(), G03ColorReader::~G03ColorReader(), G4AtomicTransitionManager::~G4AtomicTransitionManager(), G4BremsstrahlungParameters::~G4BremsstrahlungParameters(), G4ChipsAntiBaryonElasticXS::~G4ChipsAntiBaryonElasticXS(), G4ChipsHyperonElasticXS::~G4ChipsHyperonElasticXS(), G4ChipsKaonMinusElasticXS::~G4ChipsKaonMinusElasticXS(), G4ChipsKaonPlusElasticXS::~G4ChipsKaonPlusElasticXS(), G4ChipsNeutronElasticXS::~G4ChipsNeutronElasticXS(), G4ChipsPionMinusElasticXS::~G4ChipsPionMinusElasticXS(), G4ChipsPionPlusElasticXS::~G4ChipsPionPlusElasticXS(), G4ChipsProtonElasticXS::~G4ChipsProtonElasticXS(), G4DNABornIonisationModel1::~G4DNABornIonisationModel1(), G4DNACPA100ElasticModel::~G4DNACPA100ElasticModel(), G4DNACPA100ExcitationModel::~G4DNACPA100ExcitationModel(), G4DNACPA100IonisationModel::~G4DNACPA100IonisationModel(), G4DNAEmfietzoglouExcitationModel::~G4DNAEmfietzoglouExcitationModel(), G4DNAEmfietzoglouIonisationModel::~G4DNAEmfietzoglouIonisationModel(), G4DNARuddIonisationExtendedModel::~G4DNARuddIonisationExtendedModel(), G4DNARuddIonisationModel::~G4DNARuddIonisationModel(), G4DopplerProfile::~G4DopplerProfile(), G4eIonisationParameters::~G4eIonisationParameters(), G4FluoData::~G4FluoData(), G4MicroElecElasticModel::~G4MicroElecElasticModel(), G4MicroElecInelasticModel::~G4MicroElecInelasticModel(), G4MuElecElasticModel::~G4MuElecElasticModel(), G4MuElecInelasticModel::~G4MuElecInelasticModel(), G4PixeCrossSectionHandler::~G4PixeCrossSectionHandler(), G4QuasiElRatios::~G4QuasiElRatios(), G4RDAtomicTransitionManager::~G4RDAtomicTransitionManager(), G4RDBremsstrahlungParameters::~G4RDBremsstrahlungParameters(), G4RDDopplerProfile::~G4RDDopplerProfile(), G4RDeIonisationParameters::~G4RDeIonisationParameters(), G4RDFluoData::~G4RDFluoData(), G4RDShellData::~G4RDShellData(), G4RDVCrossSectionHandler::~G4RDVCrossSectionHandler(), G4ShellData::~G4ShellData(), G4VCrossSectionHandler::~G4VCrossSectionHandler(), XrayFluoHPGeDetectorType::~XrayFluoHPGeDetectorType(), and XrayFluoSiLiDetectorType::~XrayFluoSiLiDetectorType().
sensitivity (0)
Referenced by G4HumanPhantomMessenger::AddBodyPart().
start (0.)
Referenced by AnnularFieldSim::analyticFieldIntegral(), PHG4TpcDirectLaser::AppendLaserTrack(), PHField3DCylindrical::bin_search(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), FitNewton::ChiSquareGradHessian::calcValGradHessianThread1(), FitNewton::ChiSquareGradHessian::calcValGradThread1(), FW::Obj::constructVerticalFaces(), Acts::IntegrationTest::covariance_bound(), Acts::IntegrationTest::covariance_curvilinear(), G4DiffractiveExcitation::CreateStrings(), Packet_idcdevdescr::decode(), doCompression(), G4BrentLocator::EstimateIntersectionPoint(), FW::TruthVerticesToTracksAlgorithm::execute(), externalEntityInitProcessor2(), externalEntityInitProcessor3(), AnnularFieldSim::fieldIntegral(), kdfinder::find_vertex_seeds(), FW::GroupBy< Iterator, KeyGetter >::findEndOfGroup(), KFParticle_Tools::findUniqueDaughterCombinations(), Acts::IntegrationTest::foward_backward(), G4PolyPhiFace::G4PolyPhiFace(), G4RPGNucleonInelastic::G4RPGNucleonInelastic(), G4RPGPionInelastic::G4RPGPionInelastic(), G4ExcitedString::GetAntiColorParton(), G4ExcitedString::GetColorParton(), G4RPGNucleonInelastic::GetFSPartTypesForT0(), G4RPGNucleonInelastic::GetFSPartTypesForT1(), G4RPGPionInelastic::GetFSPartTypesForT12(), G4RPGPionInelastic::GetFSPartTypesForT32(), AnnularFieldSim::GetStepDistortion(), AnnularFieldSim::GetTotalDistortion(), G4AllocatorPool::Grow(), g4vrmlview::main(), main(), Acts::VolumeMaterialMapper::mapMaterialTrack(), Acts::SurfaceMaterialMapper::mapMaterialTrack(), MCGIDI_map_toXMLString(), kdfinder::merge_track_candidates(), Acts::Test::benchmark_tools_internal::microBenchmarkImpl(), PgPostCalBankIterator::next(), Acts::RiddersPropagator< propagator_t >::propagate(), Acts::Propagator< stepper_t, navigator_t >::propagate(), Acts::Test::runTest(), FitNewton::GaussianRegGradHessian::setDataThread1(), FitNewton::GaussianRegGradHessian::setErrorsThread1(), FitNewton::GaussianRegGradHessian::setPointsThread1(), sPHENIXTrackerTpc::setStartLayer(), ActsFatras::ParticleSimulator< propagator_t, physics_list_t, hit_surface_selector_t >::simulate(), nlohmann::json_pointer< BasicJsonType >::split(), G4QGSDiffractiveExcitation::String(), AnnularFieldSim::swimToInAnalyticSteps(), Acts::PrimitivesVisualization::test(), G4ParticleHPVector::ThinOut(), Acts::IntegrationTest::to_cylinder(), Acts::IntegrationTest::to_surface(), DMXSteppingAction::UserSteppingAction(), Acts::detail::wrap_periodic(), XML_ParseBuffer(), XML_SetCdataSectionHandler(), XML_SetDoctypeDeclHandler(), XML_SetElementHandler(), XML_SetNamespaceDeclHandler(), XML_SetStartCdataSectionHandler(), XML_SetStartDoctypeDeclHandler(), XML_SetStartElementHandler(), and XML_SetStartNamespaceDeclHandler().
surface (false)
Definition at line 176 of file PHG4mRICHDetector.cc.
View newest version in sPHENIX GitHub at line 176 of file PHG4mRICHDetector.cc
References mm, and z.
Referenced by Acts::addLayerProtoMaterial(), Acts::TrackingVolume::assignBoundaryMaterial(), Acts::LayerCreator::associateSurfacesToLayer(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::boundState(), Acts::TGeoLayerBuilder::buildLayers(), Acts::CuboidVolumeBuilder::buildSurface(), PHActsTrkFitter::checkSurfaceVec(), Acts::TGeoDetectorElement::construct(), PHSiliconTpcTrackMatching::correctTpcClusterZ(), Acts::SurfaceArrayCreator::createVariableAxis(), FW::CsvPlanarClusterReader::CsvPlanarClusterReader(), Acts::MaterialWiper::decorate(), Acts::JsonMaterialDecorator::decorate(), FW::RootMaterialDecorator::decorate(), FW::DigitizationAlgorithm::DigitizationAlgorithm(), G4EllipticalCone::DistanceToOut(), DSTEmulator::evaluate_tracks(), FW::HitSmearing::execute(), Acts::CombinatorialKalmanFilter< propagator_t, updater_t, smoother_t, source_link_selector_t, branch_stopper_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::filter(), ActsTransformations::getGlobalPosition(), PHActsSiliconSeeding::getMvtxSpacePoints(), FW::HitSmearing::HitSmearing(), MakeActsGeometry::InitRun(), G4MultiUnion::InsideWithExclusion(), PHActsTrkFitter::loopTracks(), MakeActsGeometry::makeMmMapPairs(), Acts::Test::StepWiseActor::operator()(), Acts::Test::SurfaceObserver< Surface >::operator()(), Acts::MaterialInteractor::operator()(), ActsFatras::Interactor< generator_t, physics_list_t, hit_surface_selector_t >::operator()(), Acts::CKFSourceLinkSelector::operator()(), Acts::Test::MeasurementCreator::operator()(), Acts::KalmanFitter< propagator_t, updater_t, smoother_t, outlier_finder_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()(), Acts::CombinatorialKalmanFilter< propagator_t, updater_t, smoother_t, source_link_selector_t, branch_stopper_t, calibrator_t, input_converter_t, output_converter_t >::Actor< source_link_t, parameters_t >::operator()(), FW::Contextual::PayloadDecorator::parseGeometry(), plot(), plot_ratio(), PHTpcClusterMover::process_event(), Acts::RiddersPropagator< propagator_t >::propagate(), FW::CsvPlanarClusterReader::read(), Acts::StraightLineStepper::State::State(), Acts::AtlasStepper< bfield_t >::State::State(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::State::State(), Acts::Navigator::status(), PHG4LFHcalDetector::SurfaceTable(), PHG4HybridHomogeneousCalorimeterDetector::SurfaceTable(), PHG4ForwardEcalDetector::SurfaceTable(), Acts::Navigator::targetSurfaces(), Acts::AtlasStepper< ConstantBField >::update(), Acts::TrackingVolume::updateBoundarySurface(), Acts::Test::PropagatorState::Stepper::updateSurfaceStatus(), Acts::StraightLineStepper::updateSurfaceStatus(), Acts::EigenStepper< ConstantBField >::updateSurfaceStatus(), Acts::AtlasStepper< ConstantBField >::updateSurfaceStatus(), FW::Obj::ObjTrackingGeometryWriter::write(), and FW::RootMaterialTrackWriter::writeT().
theta (0.)
Referenced by accessStepWise(), G4HadPhaseSpaceGenbod::AccumulateFinalState(), Run::AddMscProjTheta(), G4VarNtp::addParticle(), PHG4TpcDirectLaser::AimToPatternStep(), G4LEnp::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LEHadronProtonElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), attrad(), G4EnergyLossForExtrapolator::AverageScatteringAngle(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), PHG4mRICHDetector::build_mRICH_sector(), PHG4mRICHDetector::build_mRICH_wall_hside(), PHGenFitTrkProp::BuildLayerZPhiHitMap(), G4Molecule::BuildTrack(), G4QMDReaction::calcOffSetOfCollision(), G4MuonVDNuclearModel::CalculateEMVertex(), G4RDGenerator2BN::CalculateFkt(), G4Generator2BN::CalculateFkt(), PHG4TpcCentralMembrane::CalculateVertices(), genericRICH::cherenkovAngleSigma(), ECCEdRICHFastPIDMap::cherenkovAngleSigma(), PHTruthTrackSeeding::circleFitSeed(), PHActsSiliconSeeding::circleFitSeed(), G4EnergyLossForExtrapolator::ComputeTrueStep(), Acts::IntegrationTest::constant_field_propagation(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), G4RDGenerator2BN::ConstructMajorantSurface(), G4Generator2BN::ConstructMajorantSurface(), PHG4PSTOFDetector::ConstructMe(), G4AngularDistributionNP::CosTheta(), G4AngularDistributionPP::CosTheta(), DNAParser::CreateCutSolid(), G4Para::CreatePolyhedron(), G4Trap::CreatePolyhedron(), G4PhotoElectricAngularGeneratorPolarized::CrossSectionMajorantFunction(), G4RDPhotoElectricAngularGeneratorPolarized::CrossSectionMajorantFunction(), G4NeutronBetaDecayChannel::DecayIt(), Acts::Visualization::decomposeCovariance(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4NRESP71M03::DKINMA(), dokinematics(), G4MaterialScanner::DoScan(), CexmcScenePrimitives::DrawRadialLine(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::estimateImpactParameters(), FW::ParticleSmearing::execute(), FW::ResPlotTool::fill(), SvtxEvaluator::fillOutputNtuples(), Acts::FullBilloirVertexFitter< input_track_t, linearizer_t >::fit(), fullMaterial(), Fun4All_G4_EICDetector(), G4ArrowModel::G4ArrowModel(), G4fissionEvent::G4SmpTerrell(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASphereBoundary(), G4SPSAngDistribution::GenerateBeamFlux(), G4SPSPosDistribution::GeneratePointsOnSurface(), FW::Geant4::MMPrimaryGeneratorAction::GeneratePrimaries(), ExUCNPrimaryGeneratorAction::GeneratePrimaries(), F06PrimaryGeneratorAction::GeneratePrimaries(), XrayFluoMercuryPrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPlanePrimaryGeneratorAction::GeneratePrimaries(), XrayFluoPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), CCalPrimaryGeneratorAction::GeneratePrimaries(), PHG4Utils::get_eta(), PHG4InputFilter::get_eta(), RawTowerGeomv1::get_eta(), RawTowerGeomv4::get_eta(), RawTowerGeomv2::get_eta(), RawTowerZDCGeomv1::get_eta(), RawTowerGeomv3::get_eta(), PHG4Utils::get_etaphi(), PHG4Utils::get_theta(), RawTowerGeomv1::get_theta(), RawTowerGeomv4::get_theta(), RawTowerZDCGeomv1::get_theta(), RawTowerGeomv3::get_theta(), mRICH::getAng(), ECCEmRICHFastPIDMap::getAng(), G4VXTRenergyLoss::GetAngleVector(), mRICH::getdAng(), ECCEmRICHFastPIDMap::getdAng(), ECCEmRICHFastPIDMap::getdAngTrk(), G4ParticleHPDeExGammas::GetDecayGammas(), G4NuclNuclDiffuseElastic::GetDiffElasticProb(), G4DiffuseElastic::GetDiffElasticProb(), G4NuclNuclDiffuseElastic::GetDiffElasticSumProb(), G4DiffuseElastic::GetDiffElasticSumProb(), G4DiffuseElasticV2::GetDiffElasticSumProbA(), G4NuclNuclDiffuseElastic::GetDiffElasticSumProbA(), G4DiffuseElastic::GetDiffElasticSumProbA(), G4NuclNuclDiffuseElastic::GetDiffuseElasticSumXsc(), G4DiffuseElastic::GetDiffuseElasticSumXsc(), Acts::ImpactPointEstimator< input_track_t, propagator_t, propagator_options_t >::getDistanceAndMomentum(), ECCEhpDIRCFastPIDMap::getFastSmearLogLikelihood(), G4NuclNuclDiffuseElastic::GetFresnelIntegrandXsc(), DrcPidFast::GetInfo(), PHG4Utils::GetLengthForRapidityCoverage(), getmass(), G4RDPhotoElectricAngularGeneratorPolarized::GetPhotoElectronDirection(), G4ParticleHPPhotonDist::GetPhotons(), G4Torus::GetPointOnSurface(), BEmcRec::GetProb(), getqvec(), G4Absorber::GetRandomDirection(), getscatterer(), ClusterIso::getTowerEta(), PassiveCarbonBeamLine::HadrontherapyRippleFilter(), G4CoulombScattering::InitialiseProcess(), G4LatticeLogical::Load_NMap(), G4NativeScreenedCoulombCrossSection::LoadData(), G4LatticeLogical::LoadMap(), lutest(), makebranch(), PHActsTrackProjection::makeCaloSurfacePtrs(), makeinsplit(), makesplitting(), G4LatticeLogical::MapKtoV(), G4LatticeLogical::MapKtoVDir(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_sampleEnergy(), G4CoulombScattering::MinPrimaryEnergy(), momentumDistributions(), ActsFatras::detail::Scattering< scattering_model_t >::operator()(), ActsFatras::detail::GeneralMixture::operator()(), Acts::Test::MaterialScattering::operator()(), PHHepMCGenHelper::pair2Hep3Vector(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), G4GDMLReadSolids::ParaRead(), PHG4GDMLWriteSolids::ParaWrite(), G4GDMLWriteSolids::ParaWrite(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronGeneratePhiAndTheta(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronGeneratePhiAndTheta(), PHG4BarrelEcalDetector::PlaceTower(), DetectorConstruction::PlaceWithAxialRotations(), plot_matscan(), plot_matscan_tdr(), G4RDGenerator2BS::PolarAngle(), G4RDModifiedTsai::PolarAngle(), G4RDGenerator2BN::PolarAngle(), G4DipBustGenerator::PolarAngle(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), BEmcRec::PredictEnergyProb(), PrimaryGeneratorAction3::PrimaryGeneratorAction3(), printHits(), G4SnglNtuple::process_event(), G4SnglTree::process_event(), PHG4SimpleEventGenerator::process_event(), G4DIRCTree::process_event(), G4NuclNuclDiffuseElastic::Profile(), G4NuclNuclDiffuseElastic::ProfileFar(), G4NuclNuclDiffuseElastic::ProfileNear(), pygaga(), pyptfs(), pyptis(), pytest(), G4MuElecElasticModel::RandomizeCosTheta(), G4MicroElecElasticModel::RandomizeCosTheta(), G4DNAChampionElasticModel::RandomizeCosTheta(), G4DNAELSEPAElasticModel::RandomizeCosTheta(), G4DNAPTBElasticModel::RandomizeCosTheta(), GammaKnifeController::ReadFile(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPEvapSpectrum::Sample(), G4ParticleHPFissionSpectrum::Sample(), G4ParticleHPSimpleEvapSpectrum::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4PhotoElectricAngularGeneratorPolarized::SampleDirection(), G4LEpp::SampleInvariantT(), G4LEnp::SampleInvariantT(), G4DNAIonElasticModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4NuclNuclDiffuseElastic::SampleT(), G4DiffuseElastic::SampleT(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4UCNMultiScattering::Scatter(), CML2Acc1::SetJawAperture(), CML2Acc2::SetJawAperture(), CML2AccSaturn::SetJawAperture(), G4LivermorePolarizedComptonModel::SetNewPolarization(), G4LowEnergyPolarizedCompton::SetNewPolarization(), G4LowEPPolarizedComptonModel::SetNewPolarization(), G4VisCommandsViewerSet::SetNewValue(), G4MatScanMessenger::SetNewValue(), WLSDetectorConstruction::SetPhotonDetAlignment(), G4Torus::SolveNumericJT(), G4Para::StreamInfo(), G4Trap::StreamInfo(), G4PolarizationHelper::TestInteractionFrame(), G4PolarizationHelper::TestPolarizationTransformations(), G4MuElecElasticModel::Theta(), G4MicroElecElasticModel::Theta(), G4DNAIonElasticModel::Theta(), G4DNAChampionElasticModel::Theta(), G4DNAELSEPAElasticModel::Theta(), G4DNACPA100ElasticModel::Theta(), G4DNAPTBElasticModel::Theta(), genericDetector::trackLength(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), G4GDMLReadSolids::TrapRead(), PHG4GDMLWriteSolids::TrapWrite(), G4GDMLWriteSolids::TrapWrite(), G4ParticleHPInelasticCompFS::two_body_reaction(), ActsEvaluator::visitTrackStates(), and FW::RootTrajectoryWriter::writeT().
visibility (false)
Referenced by G4GMocrenFileSceneHandler::IsVisible(), G4VisAttributes::SetForceAuxEdgeVisible(), and G4VisCommandGeometrySetVisibility::SetNewValue().
wireframe (false)
Referenced by CCalVisualisable::readFile().