ECCE @ EIC Software: G4XResonance Class Reference
G4XResonance Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XResonance.hh>
Public Member Functions
G4XResonance (const G4ParticleDefinition *in1, const G4ParticleDefinition *in2, G4int iIsospinOut1, G4double iSpinOut1, G4double massOut1, G4int iIsospinOut2, G4double iSpinOut2, G4double massOut2, G4String subType1, G4String subType2, const G4VXResonanceTable &sigmaTable)
virtual ~G4XResonance ()
G4bool operator== (const G4XResonance &right) const
G4bool operator!= (const G4XResonance &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4String Name () const
Public Member Functions inherited from G4VXResonance
G4VXResonance ()
virtual ~G4VXResonance ()
G4bool operator== (const G4VXResonance &right) const
G4bool operator!= (const G4VXResonance &right) const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4bool IsValid (G4double e) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Private Member Functions
G4XResonance (const G4XResonance &right)
G4XResonance & operator= (const G4XResonance &right)
Private Attributes
G4int isoOut1
G4double iSpinOut1
G4double mOut1
G4int isoOut2
G4double iSpinOut2
G4double mOut2
G4PhysicsVector * table
G4String name
Additional Inherited Members
Protected Member Functions inherited from G4VXResonance
G4VXResonance (const G4VXResonance &right)
G4VXResonance & operator= (const G4VXResonance &right)
G4double DegeneracyFactor (const G4KineticTrack &trk1, const G4KineticTrack &trk2, G4double iSpinOut1, G4double iSpinOut2) const
G4double DetailedBalance (const G4KineticTrack &trk1, const G4KineticTrack &trk2, G4int isoOut1, G4int isoOut2, G4double iSpinOut1, G4double iSpinOut2, G4double mOut1, G4double mOut2) const
G4double IsospinCorrection (const G4KineticTrack &trk1, const G4KineticTrack &trk2, G4int isoOut1, G4int isoOut2, G4double iSpinOut1, G4double iSpinOut2) const
Detailed Description
Definition at line 39 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 39 of file G4XResonance.hh
Constructor & Destructor Documentation
G4XResonance::G4XResonance (const G4ParticleDefinition * in1, const G4ParticleDefinition * in2, G4int iIsospinOut1, G4double iSpinOut1, G4double massOut1, G4int iIsospinOut2, G4double iSpinOut2, G4double massOut2, G4String subType1, G4String subType2, const G4VXResonanceTable & sigmaTable)
Definition at line 35 of file G4XResonance.cc.
View newest version in sPHENIX GitHub at line 35 of file G4XResonance.cc
References G4VXResonanceTable::CrossSectionTable(), G4ParticleDefinition::GetParticleName(), and table.
G4XResonance::~G4XResonance () virtual
Definition at line 54 of file G4XResonance.cc.
View newest version in sPHENIX GitHub at line 54 of file G4XResonance.cc
References table.
G4XResonance::G4XResonance (const G4XResonance & right) private
Member Function Documentation
G4double G4XResonance::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 78 of file G4XResonance.cc.
View newest version in sPHENIX GitHub at line 78 of file G4XResonance.cc
References G4VXResonance::DetailedBalance(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4PhysicsVector::GetValue(), isoOut1, isoOut2, G4VXResonance::IsospinCorrection(), iSpinOut1, iSpinOut2, G4ParticleDefinition::IsShortLived(), mOut1, mOut2, and table.
virtual const G4CrossSectionVector* G4XResonance::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 59 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 59 of file G4XResonance.hh
G4String G4XResonance::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 73 of file G4XResonance.cc.
View newest version in sPHENIX GitHub at line 73 of file G4XResonance.cc
References name.
G4bool G4XResonance::operator!= (const G4XResonance & right) const
Definition at line 67 of file G4XResonance.cc.
View newest version in sPHENIX GitHub at line 67 of file G4XResonance.cc
G4XResonance& G4XResonance::operator= (const G4XResonance & right) private
G4bool G4XResonance::operator== (const G4XResonance & right) const
Definition at line 61 of file G4XResonance.cc.
View newest version in sPHENIX GitHub at line 61 of file G4XResonance.cc
Member Data Documentation
G4int G4XResonance::isoOut1 private
Definition at line 72 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 72 of file G4XResonance.hh
Referenced by CrossSection().
G4int G4XResonance::isoOut2 private
Definition at line 76 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 76 of file G4XResonance.hh
Referenced by CrossSection().
G4double G4XResonance::iSpinOut1 private
Definition at line 73 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 73 of file G4XResonance.hh
Referenced by CrossSection().
G4double G4XResonance::iSpinOut2 private
Definition at line 77 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 77 of file G4XResonance.hh
Referenced by CrossSection().
G4double G4XResonance::mOut1 private
Definition at line 74 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 74 of file G4XResonance.hh
Referenced by CrossSection().
G4double G4XResonance::mOut2 private
Definition at line 78 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 78 of file G4XResonance.hh
Referenced by CrossSection().
G4String G4XResonance::name private
Definition at line 83 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 83 of file G4XResonance.hh
Referenced by Name().
G4PhysicsVector* G4XResonance::table private
Definition at line 81 of file G4XResonance.hh.
View newest version in sPHENIX GitHub at line 81 of file G4XResonance.hh
Referenced by CrossSection(), G4XResonance(), and ~G4XResonance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XResonance.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XResonance.cc