ECCE @ EIC Software: G4ParticleHPThermalScatteringNames Class Reference
G4ParticleHPThermalScatteringNames Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPThermalScatteringNames.hh>
Public Member Functions
G4ParticleHPThermalScatteringNames ()
~G4ParticleHPThermalScatteringNames ()
G4bool IsThisThermalElement (G4String)
G4bool IsThisThermalElement (G4String, G4String)
size_t GetSize ()
G4String GetTS_NDL_Name (G4String nameG4Element)
G4String GetTS_NDL_Name (G4String material, G4String element)
void AddThermalElement (G4String, G4String)
Private Attributes
std::map< G4String, G4String > names
std::map< std::pair< G4String,
G4String >, G4String > nist_names
Detailed Description
Definition at line 47 of file G4ParticleHPThermalScatteringNames.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPThermalScatteringNames.hh
Constructor & Destructor Documentation
G4ParticleHPThermalScatteringNames::G4ParticleHPThermalScatteringNames ()
Definition at line 45 of file G4ParticleHPThermalScatteringNames.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPThermalScatteringNames.cc
References names, and nist_names.
G4ParticleHPThermalScatteringNames::~G4ParticleHPThermalScatteringNames ()
Definition at line 86 of file G4ParticleHPThermalScatteringNames.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPThermalScatteringNames.cc
Member Function Documentation
void G4ParticleHPThermalScatteringNames::AddThermalElement (G4String nameG4Element, G4String filename)
Definition at line 106 of file G4ParticleHPThermalScatteringNames.cc.
View newest version in sPHENIX GitHub at line 106 of file G4ParticleHPThermalScatteringNames.cc
References names.
Referenced by G4ParticleHPThermalScattering::AddUserThermalScatteringFile(), and G4ParticleHPThermalScatteringData::AddUserThermalScatteringFile().
size_t G4ParticleHPThermalScatteringNames::GetSize (void) inline
Definition at line 57 of file G4ParticleHPThermalScatteringNames.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ParticleHPThermalScatteringNames.hh
References names.
G4String G4ParticleHPThermalScatteringNames::GetTS_NDL_Name (G4String nameG4Element) inline
Definition at line 58 of file G4ParticleHPThermalScatteringNames.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPThermalScatteringNames.hh
References names.
Referenced by G4ParticleHPThermalScatteringData::BuildPhysicsTable(), and G4ParticleHPThermalScattering::buildPhysicsTable().
G4String G4ParticleHPThermalScatteringNames::GetTS_NDL_Name (G4String material, G4String element) inline
Definition at line 59 of file G4ParticleHPThermalScatteringNames.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ParticleHPThermalScatteringNames.hh
References nist_names.
G4bool G4ParticleHPThermalScatteringNames::IsThisThermalElement (G4String aname)
Definition at line 91 of file G4ParticleHPThermalScatteringNames.cc.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPThermalScatteringNames.cc
References names.
Referenced by G4ParticleHPThermalScatteringData::BuildPhysicsTable(), and G4ParticleHPThermalScattering::buildPhysicsTable().
G4bool G4ParticleHPThermalScatteringNames::IsThisThermalElement (G4String material, G4String element)
Definition at line 98 of file G4ParticleHPThermalScatteringNames.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPThermalScatteringNames.cc
References nist_names.
Member Data Documentation
std::map< G4String , G4String > G4ParticleHPThermalScatteringNames::names private
Definition at line 69 of file G4ParticleHPThermalScatteringNames.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleHPThermalScatteringNames.hh
Referenced by AddThermalElement(), G4ParticleHPThermalScatteringNames(), GetSize(), GetTS_NDL_Name(), and IsThisThermalElement().
std::map< std::pair < G4String , G4String > , G4String > G4ParticleHPThermalScatteringNames::nist_names private
Definition at line 72 of file G4ParticleHPThermalScatteringNames.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleHPThermalScatteringNames.hh
Referenced by G4ParticleHPThermalScatteringNames(), GetTS_NDL_Name(), and IsThisThermalElement().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPThermalScatteringNames.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPThermalScatteringNames.cc