ECCE @ EIC Software: HepGeom Namespace Reference
HepGeom Namespace Reference
Classes
class BasicVector3D
class Normal3D
class Normal3D< float >
class Normal3D< double >
class Plane3D
class Point3D
class Point3D< float >
class Point3D< double >
class Transform3D
class Rotate3D
class RotateX3D
class RotateY3D
class RotateZ3D
class Translate3D
class TranslateX3D
class TranslateY3D
class TranslateZ3D
class Reflect3D
class ReflectX3D
class ReflectY3D
class ReflectZ3D
class Scale3D
class ScaleX3D
class ScaleY3D
class ScaleZ3D
class Vector3D
class Vector3D< float >
class Vector3D< double >
Functions
std::ostream & operator<< (std::ostream &os, const BasicVector3D< float > &a)
std::istream & operator>> (std::istream &is, BasicVector3D< float > &a)
std::ostream & operator<< (std::ostream &os, const BasicVector3D< double > &a)
std::istream & operator>> (std::istream &is, BasicVector3D< double > &a)
Normal3D< float > operator* (const Transform3D &m, const Normal3D< float > &v)
Normal3D< double > operator* (const Transform3D &m, const Normal3D< double > &v)
std::ostream & operator<< (std::ostream &os, const Plane3D< float > &p)
std::ostream & operator<< (std::ostream &os, const Plane3D< double > &p)
Point3D< float > operator* (const Transform3D &m, const Point3D< float > &v)
Point3D< double > operator* (const Transform3D &m, const Point3D< double > &v)
Vector3D< float > operator* (const Transform3D &m, const Vector3D< float > &v)
Vector3D< double > operator* (const Transform3D &m, const Vector3D< double > &v)
Function Documentation
Point3D<float> HepGeom::operator* (const Transform3D & m, const Point3D< float > & v) related
Definition at line 20 of file Point3D.cc.
View newest version in sPHENIX GitHub at line 20 of file Point3D.cc
References HepGeom::Transform3D::dx(), HepGeom::Transform3D::dy(), HepGeom::Transform3D::dz(), HepGeom::BasicVector3D< T >::x(), HepGeom::Transform3D::xx(), HepGeom::Transform3D::xy(), HepGeom::Transform3D::xz(), HepGeom::BasicVector3D< T >::y(), HepGeom::Transform3D::yx(), HepGeom::Transform3D::yy(), HepGeom::Transform3D::yz(), HepGeom::BasicVector3D< T >::z(), HepGeom::Transform3D::zx(), HepGeom::Transform3D::zy(), and HepGeom::Transform3D::zz().
Vector3D<float> HepGeom::operator* (const Transform3D & m, const Vector3D< float > & v)
Definition at line 20 of file Vector3D.cc.
View newest version in sPHENIX GitHub at line 20 of file Vector3D.cc
References HepGeom::BasicVector3D< T >::x(), HepGeom::Transform3D::xx(), HepGeom::Transform3D::xy(), HepGeom::Transform3D::xz(), HepGeom::BasicVector3D< T >::y(), HepGeom::Transform3D::yx(), HepGeom::Transform3D::yy(), HepGeom::Transform3D::yz(), HepGeom::BasicVector3D< T >::z(), HepGeom::Transform3D::zx(), HepGeom::Transform3D::zy(), and HepGeom::Transform3D::zz().
Normal3D<float> HepGeom::operator* (const Transform3D & m, const Normal3D< float > & v) related
Definition at line 23 of file Normal3D.cc.
View newest version in sPHENIX GitHub at line 23 of file Normal3D.cc
References HepGeom::BasicVector3D< T >::x(), xx, HepGeom::Transform3D::xx(), HepGeom::Transform3D::xy(), HepGeom::Transform3D::xz(), HepGeom::BasicVector3D< T >::y(), HepGeom::Transform3D::yx(), HepGeom::Transform3D::yy(), HepGeom::Transform3D::yz(), HepGeom::BasicVector3D< T >::z(), HepGeom::Transform3D::zx(), HepGeom::Transform3D::zy(), zz, and HepGeom::Transform3D::zz().
Point3D<double> HepGeom::operator* (const Transform3D & m, const Point3D< double > & v) related
Definition at line 40 of file Point3D.cc.
View newest version in sPHENIX GitHub at line 40 of file Point3D.cc
References HepGeom::Transform3D::dx(), HepGeom::Transform3D::dy(), HepGeom::Transform3D::dz(), HepGeom::BasicVector3D< T >::x(), HepGeom::Transform3D::xx(), HepGeom::Transform3D::xy(), HepGeom::Transform3D::xz(), HepGeom::BasicVector3D< T >::y(), HepGeom::Transform3D::yx(), HepGeom::Transform3D::yy(), HepGeom::Transform3D::yz(), HepGeom::BasicVector3D< T >::z(), HepGeom::Transform3D::zx(), HepGeom::Transform3D::zy(), and HepGeom::Transform3D::zz().
Vector3D<double> HepGeom::operator* (const Transform3D & m, const Vector3D< double > & v)
Definition at line 40 of file Vector3D.cc.
View newest version in sPHENIX GitHub at line 40 of file Vector3D.cc
References HepGeom::BasicVector3D< T >::x(), HepGeom::Transform3D::xx(), HepGeom::Transform3D::xy(), HepGeom::Transform3D::xz(), HepGeom::BasicVector3D< T >::y(), HepGeom::Transform3D::yx(), HepGeom::Transform3D::yy(), HepGeom::Transform3D::yz(), HepGeom::BasicVector3D< T >::z(), HepGeom::Transform3D::zx(), HepGeom::Transform3D::zy(), and HepGeom::Transform3D::zz().
Normal3D<double> HepGeom::operator* (const Transform3D & m, const Normal3D< double > & v) related
Definition at line 49 of file Normal3D.cc.
View newest version in sPHENIX GitHub at line 49 of file Normal3D.cc
References HepGeom::BasicVector3D< T >::x(), xx, HepGeom::Transform3D::xx(), HepGeom::Transform3D::xy(), HepGeom::Transform3D::xz(), HepGeom::BasicVector3D< T >::y(), HepGeom::Transform3D::yx(), HepGeom::Transform3D::yy(), HepGeom::Transform3D::yz(), HepGeom::BasicVector3D< T >::z(), HepGeom::Transform3D::zx(), HepGeom::Transform3D::zy(), zz, and HepGeom::Transform3D::zz().
std::ostream& HepGeom::operator<< (std::ostream & os, const Plane3D< float > & p) related
Definition at line 21 of file Plane3D.cc.
View newest version in sPHENIX GitHub at line 21 of file Plane3D.cc
std::ostream& HepGeom::operator<< (std::ostream & os, const Plane3D< double > & p) related
Definition at line 28 of file Plane3D.cc.
View newest version in sPHENIX GitHub at line 28 of file Plane3D.cc
std::ostream& HepGeom::operator<< (std::ostream & os, const BasicVector3D< float > & a) related
Definition at line 106 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 106 of file BasicVector3D.cc
References a.
std::ostream& HepGeom::operator<< (std::ostream & os, const BasicVector3D< double > & a) related
Definition at line 262 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 262 of file BasicVector3D.cc
References a.
std::istream& HepGeom::operator>> (std::istream & is, BasicVector3D< float > & a) related
Definition at line 113 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 113 of file BasicVector3D.cc
References c, HepGeom::BasicVector3D< T >::setX(), HepGeom::BasicVector3D< T >::setY(), HepGeom::BasicVector3D< T >::setZ(), x, y, and z.
std::istream& HepGeom::operator>> (std::istream & is, BasicVector3D< double > & a) related
Definition at line 269 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 269 of file BasicVector3D.cc
References c, HepGeom::BasicVector3D< T >::setX(), HepGeom::BasicVector3D< T >::setY(), HepGeom::BasicVector3D< T >::setZ(), x, y, and z.