ECCE @ EIC Software: G4DrawVoxels Class Reference
G4DrawVoxels Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4DrawVoxels.hh>
Public Member Functions
G4DrawVoxels ()
~G4DrawVoxels ()
void DrawVoxels (const G4LogicalVolume *lv) const
G4PlacedPolyhedronList * CreatePlacedPolyhedra (const G4LogicalVolume *) const
void SetVoxelsVisAttributes (G4VisAttributes &, G4VisAttributes &, G4VisAttributes &)
void SetBoundingBoxVisAttributes (G4VisAttributes &)
Private Member Functions
void ComputeVoxelPolyhedra (const G4LogicalVolume *, const G4SmartVoxelHeader *, G4VoxelLimits &, G4PlacedPolyhedronList *) const
G4DrawVoxels (const G4DrawVoxels &)=delete
G4DrawVoxels operator= (const G4DrawVoxels &)=delete
Private Attributes
G4VisAttributes fVoxelsVisAttributes [3]
G4VisAttributes fBoundingBoxVisAttributes
Detailed Description
Definition at line 48 of file G4DrawVoxels.hh.
View newest version in sPHENIX GitHub at line 48 of file G4DrawVoxels.hh
Constructor & Destructor Documentation
G4DrawVoxels::G4DrawVoxels ()
Definition at line 47 of file G4DrawVoxels.cc.
View newest version in sPHENIX GitHub at line 47 of file G4DrawVoxels.cc
References fBoundingBoxVisAttributes, fVoxelsVisAttributes, and G4VisAttributes::SetColour().
G4DrawVoxels::~G4DrawVoxels ()
Definition at line 57 of file G4DrawVoxels.cc.
View newest version in sPHENIX GitHub at line 57 of file G4DrawVoxels.cc
G4DrawVoxels::G4DrawVoxels (const G4DrawVoxels &) private delete
Member Function Documentation
void G4DrawVoxels::ComputeVoxelPolyhedra (const G4LogicalVolume * lv, const G4SmartVoxelHeader * header, G4VoxelLimits & limit, G4PlacedPolyhedronList * ppl) const private
Definition at line 80 of file G4DrawVoxels.cc.
View newest version in sPHENIX GitHub at line 80 of file G4DrawVoxels.cc
References G4VoxelLimits::AddLimit(), G4VSolid::CalculateExtent(), dx, dy, dz, fBoundingBoxVisAttributes, fVoxelsVisAttributes, G4SmartVoxelHeader::GetAxis(), G4SmartVoxelProxy::GetHeader(), G4SmartVoxelHeader::GetMaxEquivalentSliceNo(), G4SmartVoxelNode::GetMaxEquivalentSliceNo(), G4SmartVoxelHeader::GetMaxExtent(), G4SmartVoxelHeader::GetMinExtent(), G4LogicalVolume::GetNoDaughters(), G4SmartVoxelProxy::GetNode(), G4SmartVoxelHeader::GetNoSlices(), G4SmartVoxelHeader::GetSlice(), G4LogicalVolume::GetSolid(), G4SmartVoxelProxy::IsHeader(), kInfinity, kXAxis, kYAxis, kZAxis, G4Visible::SetVisAttributes(), Acts::Test::step(), voxel_width, xmax, xmin, ymax, and ymin.
Referenced by CreatePlacedPolyhedra().
G4PlacedPolyhedronList * G4DrawVoxels::CreatePlacedPolyhedra (const G4LogicalVolume * lv) const
Definition at line 185 of file G4DrawVoxels.cc.
View newest version in sPHENIX GitHub at line 185 of file G4DrawVoxels.cc
References ComputeVoxelPolyhedra(), and G4LogicalVolume::GetVoxelHeader().
Referenced by G4LogicalVolumeModel::DescribeYourselfTo(), and DrawVoxels().
void G4DrawVoxels::DrawVoxels (const G4LogicalVolume * lv) const
Definition at line 195 of file G4DrawVoxels.cc.
View newest version in sPHENIX GitHub at line 195 of file G4DrawVoxels.cc
References CreatePlacedPolyhedra(), G4VVisManager::Draw(), G4Exception(), G4VVisManager::GetConcreteInstance(), G4TouchableHistory::GetHistory(), G4LogicalVolume::GetNoDaughters(), G4NavigationHistory::GetTopTransform(), G4TransportationManager::GetTransportationManager(), G4AffineTransform::Inverse(), JustWarning, G4AffineTransform::NetRotation(), and G4AffineTransform::NetTranslation().
G4DrawVoxels G4DrawVoxels::operator= (const G4DrawVoxels &) private delete
void G4DrawVoxels::SetBoundingBoxVisAttributes (G4VisAttributes & VA_boundingbox)
Definition at line 72 of file G4DrawVoxels.cc.
View newest version in sPHENIX GitHub at line 72 of file G4DrawVoxels.cc
References fBoundingBoxVisAttributes.
void G4DrawVoxels::SetVoxelsVisAttributes (G4VisAttributes & VA_voxelX, G4VisAttributes & VA_voxelY, G4VisAttributes & VA_voxelZ)
Definition at line 63 of file G4DrawVoxels.cc.
View newest version in sPHENIX GitHub at line 63 of file G4DrawVoxels.cc
References fVoxelsVisAttributes.
Member Data Documentation
G4VisAttributes G4DrawVoxels::fBoundingBoxVisAttributes private
Definition at line 84 of file G4DrawVoxels.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DrawVoxels.hh
Referenced by ComputeVoxelPolyhedra(), G4DrawVoxels(), and SetBoundingBoxVisAttributes().
G4VisAttributes G4DrawVoxels::fVoxelsVisAttributes[3] private
Definition at line 83 of file G4DrawVoxels.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DrawVoxels.hh
Referenced by ComputeVoxelPolyhedra(), G4DrawVoxels(), and SetVoxelsVisAttributes().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4DrawVoxels.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4DrawVoxels.cc