ECCE @ EIC Software: G4IonCoulombScatteringModel Class Reference
G4IonCoulombScatteringModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4IonCoulombScatteringModel.hh>
Public Member Functions
G4IonCoulombScatteringModel (const G4String &nam="IonCoulombScattering")
virtual ~G4IonCoulombScatteringModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) final
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A, G4double cut, G4double emax) final
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) final
void SetRecoilThreshold (G4double eth)
void SetHeavyIonCorr (G4int b)
G4int GetHeavyIonCorr ()
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
void DefineMaterial (const G4MaterialCutsCouple *)
void SetupParticle (const G4ParticleDefinition *)
G4IonCoulombScatteringModel & operator= (const G4IonCoulombScatteringModel &right)=delete
G4IonCoulombScatteringModel (const G4IonCoulombScatteringModel &)=delete
Private Attributes
G4IonTable * theIonTable
G4ParticleChangeForGamma * fParticleChange
G4NistManager * fNistManager
G4IonCoulombCrossSection * ioncross
const std::vector< G4double > * pCuts
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
const G4Element * currentElement
G4int currentMaterialIndex
G4int heavycorr
G4double cosThetaMin
G4double recoilThreshold
const G4ParticleDefinition * particle
const G4ParticleDefinition * theProton
G4double mass
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 71 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 71 of file G4IonCoulombScatteringModel.hh
Constructor & Destructor Documentation
G4IonCoulombScatteringModel::G4IonCoulombScatteringModel (const G4String & nam = "IonCoulombScattering") explicit
Definition at line 75 of file G4IonCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 75 of file G4IonCoulombScatteringModel.cc
References currentCouple, currentElement, currentMaterial, currentMaterialIndex, eV, fNistManager, fParticleChange, G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), heavycorr, G4NistManager::Instance(), ioncross, mass, particle, pCuts, G4Proton::Proton(), recoilThreshold, theIonTable, and theProton.
G4IonCoulombScatteringModel::~G4IonCoulombScatteringModel () virtual
Definition at line 101 of file G4IonCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 101 of file G4IonCoulombScatteringModel.cc
References ioncross.
G4IonCoulombScatteringModel::G4IonCoulombScatteringModel (const G4IonCoulombScatteringModel &) private delete
Member Function Documentation
G4double G4IonCoulombScatteringModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kinEnergy, G4double Z, G4double A, G4double cut, G4double emax) final virtual
Reimplemented from G4VEmModel.
Definition at line 125 of file G4IonCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 125 of file G4IonCoulombScatteringModel.cc
References source.hepunit::amu_c2, Acts::VectorHelpers::cross(), G4VEmModel::CurrentCouple(), DefineMaterial(), fNistManager, G4lrint(), G4NistManager::GetAtomicMassAmu(), heavycorr, ioncross, G4IonCoulombCrossSection::NuclearCrossSection(), source.hepunit::proton_mass_c2, G4IonCoulombCrossSection::SetupKinematic(), SetupParticle(), and G4IonCoulombCrossSection::SetupTarget().
void G4IonCoulombScatteringModel::DefineMaterial (const G4MaterialCutsCouple * cup) inline private
Definition at line 146 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 146 of file G4IonCoulombScatteringModel.hh
References currentCouple, currentMaterial, currentMaterialIndex, G4MaterialCutsCouple::GetIndex(), and G4MaterialCutsCouple::GetMaterial().
Referenced by ComputeCrossSectionPerAtom(), and SampleSecondaries().
G4int G4IonCoulombScatteringModel::GetHeavyIonCorr () inline
Definition at line 183 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 183 of file G4IonCoulombScatteringModel.hh
References heavycorr.
void G4IonCoulombScatteringModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) final virtual
Implements G4VEmModel.
Definition at line 108 of file G4IonCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 108 of file G4IonCoulombScatteringModel.cc
References cosThetaMin, currentCouple, currentMaterialIndex, fParticleChange, G4VEmModel::GetParticleChangeForGamma(), G4IonCoulombCrossSection::Initialise(), ioncross, pCuts, and SetupParticle().
G4IonCoulombScatteringModel& G4IonCoulombScatteringModel::operator= (const G4IonCoulombScatteringModel & right) private delete
void G4IonCoulombScatteringModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) final virtual
Implements G4VEmModel.
Definition at line 152 of file G4IonCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 152 of file G4IonCoulombScatteringModel.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), currentElement, currentMaterialIndex, DefineMaterial(), dir, CLHEP::HepLorentzVector::e(), e1, edep, fParticleChange, G4UniformRand, G4DynamicParticle::GetDefinition(), G4IonTable::GetIon(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4NucleiProperties::GetNuclearMass(), G4Element::GetZasInt(), heavycorr, ioncross, mass, max, particle, pCuts, phi, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4VParticleChange::ProposeNonIonizingEnergyDeposit(), CLHEP::HepLorentzVector::pz(), recoilThreshold, CLHEP::Hep3Vector::rotateUz(), G4IonCoulombCrossSection::SampleCosineTheta(), G4VEmModel::SelectIsotopeNumber(), G4VEmModel::SelectTargetAtom(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), G4IonCoulombCrossSection::SetupKinematic(), SetupParticle(), G4IonCoulombCrossSection::SetupTarget(), CLHEP::HepLorentzVector::setX(), CLHEP::HepLorentzVector::setY(), CLHEP::HepLorentzVector::setZ(), theIonTable, twopi, CLHEP::Hep3Vector::unit(), v1, CLHEP::HepLorentzVector::vect(), and z1.
void G4IonCoulombScatteringModel::SetHeavyIonCorr (G4int b) inline
Definition at line 176 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4IonCoulombScatteringModel.hh
References b, and heavycorr.
void G4IonCoulombScatteringModel::SetRecoilThreshold (G4double eth) inline
Definition at line 169 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4IonCoulombScatteringModel.hh
References recoilThreshold.
void G4IonCoulombScatteringModel::SetupParticle (const G4ParticleDefinition * p) inline private
Definition at line 158 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4IonCoulombScatteringModel.hh
References G4ParticleDefinition::GetPDGMass(), ioncross, mass, particle, and G4IonCoulombCrossSection::SetupParticle().
Referenced by ComputeCrossSectionPerAtom(), Initialise(), and SampleSecondaries().
Member Data Documentation
G4double G4IonCoulombScatteringModel::cosThetaMin private
Definition at line 133 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 133 of file G4IonCoulombScatteringModel.hh
Referenced by Initialise().
const G4MaterialCutsCouple* G4IonCoulombScatteringModel::currentCouple private
Definition at line 126 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 126 of file G4IonCoulombScatteringModel.hh
Referenced by DefineMaterial(), G4IonCoulombScatteringModel(), and Initialise().
const G4Element* G4IonCoulombScatteringModel::currentElement private
Definition at line 128 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 128 of file G4IonCoulombScatteringModel.hh
Referenced by G4IonCoulombScatteringModel(), and SampleSecondaries().
const G4Material* G4IonCoulombScatteringModel::currentMaterial private
Definition at line 127 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 127 of file G4IonCoulombScatteringModel.hh
Referenced by DefineMaterial(), and G4IonCoulombScatteringModel().
G4int G4IonCoulombScatteringModel::currentMaterialIndex private
Definition at line 129 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4IonCoulombScatteringModel.hh
Referenced by DefineMaterial(), G4IonCoulombScatteringModel(), Initialise(), and SampleSecondaries().
G4NistManager* G4IonCoulombScatteringModel::fNistManager private
Definition at line 122 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 122 of file G4IonCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), and G4IonCoulombScatteringModel().
G4ParticleChangeForGamma* G4IonCoulombScatteringModel::fParticleChange private
Definition at line 121 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4IonCoulombScatteringModel.hh
Referenced by G4IonCoulombScatteringModel(), Initialise(), and SampleSecondaries().
G4int G4IonCoulombScatteringModel::heavycorr private
Definition at line 131 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 131 of file G4IonCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4IonCoulombScatteringModel(), GetHeavyIonCorr(), SampleSecondaries(), and SetHeavyIonCorr().
G4IonCoulombCrossSection* G4IonCoulombScatteringModel::ioncross private
Definition at line 123 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 123 of file G4IonCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4IonCoulombScatteringModel(), Initialise(), SampleSecondaries(), SetupParticle(), and ~G4IonCoulombScatteringModel().
G4double G4IonCoulombScatteringModel::mass private
Definition at line 139 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 139 of file G4IonCoulombScatteringModel.hh
Referenced by G4IonCoulombScatteringModel(), SampleSecondaries(), and SetupParticle().
const G4ParticleDefinition* G4IonCoulombScatteringModel::particle private
Definition at line 137 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 137 of file G4IonCoulombScatteringModel.hh
Referenced by G4IonCoulombScatteringModel(), SampleSecondaries(), and SetupParticle().
const std::vector<G4double>* G4IonCoulombScatteringModel::pCuts private
Definition at line 125 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 125 of file G4IonCoulombScatteringModel.hh
Referenced by G4IonCoulombScatteringModel(), Initialise(), and SampleSecondaries().
G4double G4IonCoulombScatteringModel::recoilThreshold private
Definition at line 134 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 134 of file G4IonCoulombScatteringModel.hh
Referenced by G4IonCoulombScatteringModel(), SampleSecondaries(), and SetRecoilThreshold().
G4IonTable* G4IonCoulombScatteringModel::theIonTable private
Definition at line 120 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4IonCoulombScatteringModel.hh
Referenced by G4IonCoulombScatteringModel(), and SampleSecondaries().
const G4ParticleDefinition* G4IonCoulombScatteringModel::theProton private
Definition at line 138 of file G4IonCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 138 of file G4IonCoulombScatteringModel.hh
Referenced by G4IonCoulombScatteringModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4IonCoulombScatteringModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4IonCoulombScatteringModel.cc