ECCE @ EIC Software: G4XPDGTotal Class Reference
G4XPDGTotal Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XPDGTotal.hh>
Public Member Functions
G4XPDGTotal ()
virtual ~G4XPDGTotal ()
G4bool operator== (const G4XPDGTotal &right) const
G4bool operator!= (const G4XPDGTotal &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4String Name () const
virtual G4bool IsValid (G4double e) const
virtual G4double LowLimit () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double HighLimit () const
Private Types
typedef std::map< G4pDefPair,
std::vector< G4double >
, std::less< G4pDefPair > > PairDoubleMap
Private Member Functions
G4double PDGTotal (G4double coeff, G4double ecm) const
G4XPDGTotal (const G4XPDGTotal &right)
const G4XPDGTotal & operator= (const G4XPDGTotal &right)
Private Attributes
std::map< G4pDefPair,
std::vector< G4double >
, std::less< G4pDefPair > > xMap
Static Private Attributes
static const G4double _lowLimit = 3. * GeV
static const G4double _highLimit = DBL_MAX
static const G4int nFit = 5
static const G4double ppPDGFit [5] = { 3., 40000., 18.256, 60.19, 33.43 }
static const G4double npPDGFit [5] = { 3., 40., 18.256, 61.14, 29.80 }
static const G4double pipPDGFit [5] = { 3., 40., 11.568, 27.55, 5.62 }
static const G4double KpPDGFit [5] = { 3., 40., 10.376, 15.57, 13.19 }
static const G4double KnPDGFit [5] = { 3., 40., 10.376, 14.29, 7.38 }
static const G4double gammapPDGFit [5] = { 3., 300., 0.0577, 0.1171, 0. }
static const G4double gammagammaPDGFit [5] = { 3., 300., 0.000156, 0.00032, 0. }
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 55 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 55 of file G4XPDGTotal.hh
Member Typedef Documentation
typedef std::map<G4pDefPair, std::vector<G4double>, std::less<G4pDefPair> > G4XPDGTotal::PairDoubleMap private
Definition at line 100 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 100 of file G4XPDGTotal.hh
Constructor & Destructor Documentation
G4XPDGTotal::G4XPDGTotal ()
Definition at line 70 of file G4XPDGTotal.cc.
View newest version in sPHENIX GitHub at line 70 of file G4XPDGTotal.cc
References G4Gamma::GammaDefinition(), gammagammaPDGFit, gammapPDGFit, GeV, G4KaonMinus::KaonMinusDefinition(), G4KaonPlus::KaonPlusDefinition(), KnPDGFit, KpPDGFit, G4Neutron::NeutronDefinition(), nFit, G4InuclParticleNames::nn, npPDGFit, G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), pipPDGFit, G4InuclParticleNames::pn, G4InuclParticleNames::pp, ppPDGFit, G4Proton::ProtonDefinition(), and xMap.
G4XPDGTotal::~G4XPDGTotal () virtual
Definition at line 142 of file G4XPDGTotal.cc.
View newest version in sPHENIX GitHub at line 142 of file G4XPDGTotal.cc
G4XPDGTotal::G4XPDGTotal (const G4XPDGTotal & right) private
Member Function Documentation
G4double G4XPDGTotal::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 158 of file G4XPDGTotal.cc.
View newest version in sPHENIX GitHub at line 158 of file G4XPDGTotal.cc
References epsilon(), G4cout, G4endl, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4Pow::GetInstance(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), GeV, millibarn, G4Pow::powA(), S(), and xMap.
Referenced by G4XpimNTotal::CrossSection(), and G4XpipNTotal::CrossSection().
virtual const G4CrossSectionVector* G4XPDGTotal::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 69 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 69 of file G4XPDGTotal.hh
G4bool G4XPDGTotal::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 244 of file G4XPDGTotal.cc.
View newest version in sPHENIX GitHub at line 244 of file G4XPDGTotal.cc
References _highLimit, _lowLimit, and G4VCrossSectionSource::InLimits().
virtual G4double G4XPDGTotal::LowLimit () const inline virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 75 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 75 of file G4XPDGTotal.hh
References _lowLimit.
G4String G4XPDGTotal::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 237 of file G4XPDGTotal.cc.
View newest version in sPHENIX GitHub at line 237 of file G4XPDGTotal.cc
G4bool G4XPDGTotal::operator!= (const G4XPDGTotal & right) const
Definition at line 152 of file G4XPDGTotal.cc.
View newest version in sPHENIX GitHub at line 152 of file G4XPDGTotal.cc
const G4XPDGTotal& G4XPDGTotal::operator= (const G4XPDGTotal & right) private
G4bool G4XPDGTotal::operator== (const G4XPDGTotal & right) const
Definition at line 146 of file G4XPDGTotal.cc.
View newest version in sPHENIX GitHub at line 146 of file G4XPDGTotal.cc
G4double G4XPDGTotal::PDGTotal (G4double coeff, G4double ecm) const private
Definition at line 252 of file G4XPDGTotal.cc.
View newest version in sPHENIX GitHub at line 252 of file G4XPDGTotal.cc
Member Data Documentation
const G4double G4XPDGTotal::_highLimit = DBL_MAX static private
Definition at line 88 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 88 of file G4XPDGTotal.hh
Referenced by IsValid().
const G4double G4XPDGTotal::_lowLimit = 3. * GeV static private
Definition at line 87 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 87 of file G4XPDGTotal.hh
Referenced by IsValid(), and LowLimit().
const G4double G4XPDGTotal::gammagammaPDGFit = { 3., 300., 0.000156, 0.00032, 0. } static private
Definition at line 97 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 97 of file G4XPDGTotal.hh
Referenced by G4XPDGTotal().
const G4double G4XPDGTotal::gammapPDGFit = { 3., 300., 0.0577, 0.1171, 0. } static private
Definition at line 96 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 96 of file G4XPDGTotal.hh
Referenced by G4XPDGTotal().
const G4double G4XPDGTotal::KnPDGFit = { 3., 40., 10.376, 14.29, 7.38 } static private
Definition at line 95 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 95 of file G4XPDGTotal.hh
Referenced by G4XPDGTotal().
const G4double G4XPDGTotal::KpPDGFit = { 3., 40., 10.376, 15.57, 13.19 } static private
Definition at line 94 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 94 of file G4XPDGTotal.hh
Referenced by G4XPDGTotal().
const G4int G4XPDGTotal::nFit = 5 static private
Definition at line 90 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 90 of file G4XPDGTotal.hh
Referenced by G4XPDGTotal().
const G4double G4XPDGTotal::npPDGFit = { 3., 40., 18.256, 61.14, 29.80 } static private
Definition at line 92 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 92 of file G4XPDGTotal.hh
Referenced by G4XPDGTotal().
const G4double G4XPDGTotal::pipPDGFit = { 3., 40., 11.568, 27.55, 5.62 } static private
Definition at line 93 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 93 of file G4XPDGTotal.hh
Referenced by G4XPDGTotal().
const G4double G4XPDGTotal::ppPDGFit = { 3., 40000., 18.256, 60.19, 33.43 } static private
Definition at line 91 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 91 of file G4XPDGTotal.hh
Referenced by G4XPDGTotal().
std::map<G4pDefPair, std::vector<G4double>, std::less<G4pDefPair> > G4XPDGTotal::xMap private
Definition at line 99 of file G4XPDGTotal.hh.
View newest version in sPHENIX GitHub at line 99 of file G4XPDGTotal.hh
Referenced by CrossSection(), and G4XPDGTotal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XPDGTotal.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XPDGTotal.cc