ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4Hype.cc File Reference
pyG4Hype.cc File Reference
#include <boost/python.hpp>
#include "G4Hype.hh"
Namespaces
namespace pyG4Hype
Functions
G4Hype * pyG4Hype::CreateHype (const G4String &name, G4double newInnerRadius, G4double newOuterRadius, G4double newInnerStereo, G4double newOuterStereo, G4double newHalfLenZ)
void export_G4Hype ()
Function Documentation
void export_G4Hype ()
Definition at line 61 of file pyG4Hype.cc.
View newest version in sPHENIX GitHub at line 61 of file pyG4Hype.cc
References pyG4Hype::CreateHype(), G4Hype::GetInnerRadius(), G4Hype::GetInnerStereo(), G4Hype::GetOuterRadius(), G4Hype::GetOuterStereo(), G4Hype::GetZHalfLength(), init(), G4Hype::SetInnerRadius(), G4Hype::SetInnerStereo(), G4Hype::SetOuterRadius(), G4Hype::SetOuterStereo(), and G4Hype::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().