ECCE @ EIC Software: G4XPDGElastic Class Reference
G4XPDGElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XPDGElastic.hh>
Public Member Functions
G4XPDGElastic ()
virtual ~G4XPDGElastic ()
G4bool operator== (const G4XPDGElastic &right) const
G4bool operator!= (const G4XPDGElastic &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4String Name () const
virtual G4bool IsValid (G4double e) const
virtual G4double LowLimit () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double HighLimit () const
Private Types
typedef std::map< G4pDefPair,
std::vector< G4double >
, std::less< G4pDefPair > > PairDoubleMap
Private Member Functions
G4XPDGElastic (const G4XPDGElastic &right)
const G4XPDGElastic & operator= (const G4XPDGElastic &right)
Private Attributes
std::map< G4pDefPair,
std::vector< G4double >
, std::less< G4pDefPair > > xMap
Static Private Attributes
static const G4double _lowLimit = 5. * GeV
static const G4double _highLimit = DBL_MAX
static const G4int nPar = 7
static const G4double pPiPlusPDGFit [7] = { 2., 200., 0., 11.4, -0.4, 0.079, 0. }
static const G4double pPiMinusPDGFit [7] = { 2., 360., 1.76, 11.2, -0.64, 0.043, 0. }
static const G4double pKPlusPDGFit [7] = { 2., 175., 5.0, 8.1, -1.8, 0.16, -1.3 }
static const G4double pKMinusPDGFit [7] = { 2., 175., 7.3, 0., 0., 0.29, -2.40 }
static const G4double ppPDGFit [7] = { 2., 2100., 11.9, 26.9, -1.21, 0.169, -1.85 }
static const G4double ppbarPDGFit [7] = { 5., 1730000., 10.2, 52.7, -1.16, 0.125, -1.28 }
static const G4double npbarPDGFit [7] = { 1.1, 5.55, 36.5, 0., 0., 0., -11.9 }
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 54 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 54 of file G4XPDGElastic.hh
Member Typedef Documentation
typedef std::map<G4pDefPair, std::vector<G4double>, std::less<G4pDefPair> > G4XPDGElastic::PairDoubleMap private
Definition at line 99 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 99 of file G4XPDGElastic.hh
Constructor & Destructor Documentation
G4XPDGElastic::G4XPDGElastic ()
Definition at line 76 of file G4XPDGElastic.cc.
View newest version in sPHENIX GitHub at line 76 of file G4XPDGElastic.cc
References G4AntiProton::AntiProtonDefinition(), GeV, G4KaonMinus::KaonMinusDefinition(), G4KaonPlus::KaonPlusDefinition(), G4INCL::KMinus, G4INCL::KPlus, G4InuclParticleNames::neutron, G4Neutron::NeutronDefinition(), G4InuclParticleNames::nn, nPar, npbarPDGFit, G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), pKMinusPDGFit, pKPlusPDGFit, G4InuclParticleNames::pn, G4InuclParticleNames::pp, ppbarPDGFit, pPiMinusPDGFit, pPiPlusPDGFit, ppPDGFit, G4InuclParticleNames::proton, G4Proton::ProtonDefinition(), and xMap.
G4XPDGElastic::~G4XPDGElastic () virtual
Definition at line 139 of file G4XPDGElastic.cc.
View newest version in sPHENIX GitHub at line 139 of file G4XPDGElastic.cc
G4XPDGElastic::G4XPDGElastic (const G4XPDGElastic & right) private
Member Function Documentation
G4double G4XPDGElastic::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 155 of file G4XPDGElastic.cc.
View newest version in sPHENIX GitHub at line 155 of file G4XPDGElastic.cc
References G4cout, G4endl, G4Log(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4Pow::GetInstance(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), GeV, max, millibarn, G4Pow::powA(), and xMap.
Referenced by G4XMesonBaryonElastic::CrossSection().
virtual const G4CrossSectionVector* G4XPDGElastic::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 68 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 68 of file G4XPDGElastic.hh
G4bool G4XPDGElastic::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 260 of file G4XPDGElastic.cc.
View newest version in sPHENIX GitHub at line 260 of file G4XPDGElastic.cc
References _highLimit, _lowLimit, and G4VCrossSectionSource::InLimits().
virtual G4double G4XPDGElastic::LowLimit () const inline virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 74 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 74 of file G4XPDGElastic.hh
References _lowLimit.
G4String G4XPDGElastic::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 253 of file G4XPDGElastic.cc.
View newest version in sPHENIX GitHub at line 253 of file G4XPDGElastic.cc
G4bool G4XPDGElastic::operator!= (const G4XPDGElastic & right) const
Definition at line 149 of file G4XPDGElastic.cc.
View newest version in sPHENIX GitHub at line 149 of file G4XPDGElastic.cc
const G4XPDGElastic& G4XPDGElastic::operator= (const G4XPDGElastic & right) private
G4bool G4XPDGElastic::operator== (const G4XPDGElastic & right) const
Definition at line 143 of file G4XPDGElastic.cc.
View newest version in sPHENIX GitHub at line 143 of file G4XPDGElastic.cc
Member Data Documentation
const G4double G4XPDGElastic::_highLimit = DBL_MAX static private
Definition at line 86 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 86 of file G4XPDGElastic.hh
Referenced by IsValid().
const G4double G4XPDGElastic::_lowLimit = 5. * GeV static private
Definition at line 85 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 85 of file G4XPDGElastic.hh
Referenced by IsValid(), and LowLimit().
const G4int G4XPDGElastic::nPar = 7 static private
Definition at line 88 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 88 of file G4XPDGElastic.hh
Referenced by G4XPDGElastic().
const G4double G4XPDGElastic::npbarPDGFit = { 1.1, 5.55, 36.5, 0., 0., 0., -11.9 } static private
Definition at line 95 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 95 of file G4XPDGElastic.hh
Referenced by G4XPDGElastic().
const G4double G4XPDGElastic::pKMinusPDGFit = { 2., 175., 7.3, 0., 0., 0.29, -2.40 } static private
Definition at line 92 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 92 of file G4XPDGElastic.hh
Referenced by G4XPDGElastic().
const G4double G4XPDGElastic::pKPlusPDGFit = { 2., 175., 5.0, 8.1, -1.8, 0.16, -1.3 } static private
Definition at line 91 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 91 of file G4XPDGElastic.hh
Referenced by G4XPDGElastic().
const G4double G4XPDGElastic::ppbarPDGFit = { 5., 1730000., 10.2, 52.7, -1.16, 0.125, -1.28 } static private
Definition at line 94 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 94 of file G4XPDGElastic.hh
Referenced by G4XPDGElastic().
const G4double G4XPDGElastic::pPiMinusPDGFit = { 2., 360., 1.76, 11.2, -0.64, 0.043, 0. } static private
Definition at line 90 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 90 of file G4XPDGElastic.hh
Referenced by G4XPDGElastic().
const G4double G4XPDGElastic::pPiPlusPDGFit = { 2., 200., 0., 11.4, -0.4, 0.079, 0. } static private
Definition at line 89 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 89 of file G4XPDGElastic.hh
Referenced by G4XPDGElastic().
const G4double G4XPDGElastic::ppPDGFit = { 2., 2100., 11.9, 26.9, -1.21, 0.169, -1.85 } static private
Definition at line 93 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 93 of file G4XPDGElastic.hh
Referenced by G4XPDGElastic().
std::map<G4pDefPair, std::vector<G4double>, std::less<G4pDefPair> > G4XPDGElastic::xMap private
Definition at line 97 of file G4XPDGElastic.hh.
View newest version in sPHENIX GitHub at line 97 of file G4XPDGElastic.hh
Referenced by CrossSection(), and G4XPDGElastic().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XPDGElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XPDGElastic.cc