ECCE @ EIC Software: coresoftware/blob/master/offline/packages/HelixHough/helix_hough/Kalman/CylinderKalman.cpp File Reference
CylinderKalman.cpp File Reference
#include "CylinderKalman.h"
#include "HelixKalmanState.h"
#include "SimpleHit3D.h"
#include <Eigen/Core>
#include <Eigen/LU>
#include <algorithm>
#include <cmath>
Functions
static float sign (float x)
Function Documentation
static float sign (float x) inline static
Definition at line 15 of file CylinderKalman.cpp.
View newest version in sPHENIX GitHub at line 15 of file CylinderKalman.cpp
Referenced by CylinderKalman::calculate_dxda(), G4Clebsch::ClebschGordanCoeff(), doinstatescat(), dokinematics(), kdfinder::export_candidates_json(), kdfinder::export_candidates_json_old(), PHTpcEventExporter::exportEvent(), CLHEP::HepStat::flatToGaussian(), HelixHoughBin_v1::get_neighbors_global_bin(), Acts::LineSurface::globalToLocal(), G4INCL::IFunction1D::integrate(), PrimaryGeneratorAction2::InverseCumul(), lucell(), luedit(), lustrf(), lutabu(), luthru(), lux3jt(), luxdif(), luxkfl(), luxtot(), nf_floatToShortestString(), odeint(), plu(), PHInitZVertexing::prune_xy(), PHPatternReco::prune_xy(), PHInitZVertexing::prune_z(), PHPatternReco::prune_z(), ptwXY_dullEdges(), ptwXY_integrateWithFunction(), pyangl(), pyapps(), pycell(), pycjdc(), pydocu(), pyedit(), pygaga(), pyglui(), pyhiklim(), pyhiremn(), pyhiresd(), pyhisigh(), pyhispen(), pyhitest(), pyhithia(), pyhiwidt(), pyinbm(), pyinki(), pyinom(), pyklim(), pymsin(), pynjdc(), pyp(), pyplot(), pyptfs(), pyrand(), pyremn(), pyresd(), pyscat(), pysfdc(), pysgex(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pyshow(), pysigh(), pyslha(), pyspen(), pystrf(), pytabu(), pytbdy(), pytest(), pythia(), pythrg(), pythru(), pywidt(), pywidx(), pyx3jt(), pyxdif(), pyxkfl(), pyxtee(), PHG4HcalSubsystem::SetTiltViaNcross(), CLHEP::RandGaussQ::transformQuick(), ulangl(), CylinderKalman::updateIntersection(), G4Clebsch::Wigner6J(), G4Clebsch::Wigner9J(), and G4Clebsch::WignerLittleD().