ECCE @ EIC Software: G4DNAGenericIonsManager Class Reference
G4DNAGenericIonsManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAGenericIonsManager.hh>
Public Member Functions
G4ParticleDefinition * GetIon (const G4String &name)
Static Public Member Functions
static G4DNAGenericIonsManager * Instance (void)
Private Types
typedef std::map< G4String,
G4ParticleDefinition * > IonsMap
Private Member Functions
G4DNAGenericIonsManager ()
~G4DNAGenericIonsManager ()
G4DNAGenericIonsManager (const G4DNAGenericIonsManager &)
const G4DNAGenericIonsManager & operator= (const G4DNAGenericIonsManager &)
Private Attributes
IonsMap map
Static Private Attributes
static G4DNAGenericIonsManager * theInstance
Detailed Description
Definition at line 38 of file G4DNAGenericIonsManager.hh.
View newest version in sPHENIX GitHub at line 38 of file G4DNAGenericIonsManager.hh
Member Typedef Documentation
typedef std::map<G4String, G4ParticleDefinition *> G4DNAGenericIonsManager::IonsMap private
Definition at line 53 of file G4DNAGenericIonsManager.hh.
View newest version in sPHENIX GitHub at line 53 of file G4DNAGenericIonsManager.hh
Constructor & Destructor Documentation
G4DNAGenericIonsManager::G4DNAGenericIonsManager () private
Definition at line 57 of file G4DNAGenericIonsManager.cc.
View newest version in sPHENIX GitHub at line 57 of file G4DNAGenericIonsManager.cc
References G4Alpha::Alpha(), source.hepunit::electron_mass_c2, eplus, GeV, map, and MeV.
Referenced by Instance().
G4DNAGenericIonsManager::~G4DNAGenericIonsManager () private
G4DNAGenericIonsManager::G4DNAGenericIonsManager (const G4DNAGenericIonsManager &) private
Member Function Documentation
G4ParticleDefinition * G4DNAGenericIonsManager::GetIon (const G4String & name)
Definition at line 45 of file G4DNAGenericIonsManager.cc.
View newest version in sPHENIX GitHub at line 45 of file G4DNAGenericIonsManager.cc
References map.
Referenced by G4EmDNAPhysics_option3::ConstructParticle(), G4EmDNAPhysics_stationary::ConstructParticle(), G4EmDNAPhysics_stationary_option2::ConstructParticle(), G4EmDNAPhysics_stationary_option4::ConstructParticle(), G4EmDNAPhysics_stationary_option6::ConstructParticle(), G4EmDNAPhysics_option1::ConstructParticle(), G4EmDNAPhysics::ConstructParticle(), G4EmDNAPhysics_option2::ConstructParticle(), G4EmDNAPhysics_option7::ConstructParticle(), G4EmDNAPhysics_option8::ConstructParticle(), G4EmDNAPhysics_option4::ConstructParticle(), G4EmDNAPhysics_option5::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructParticle(), G4EmLEPTSPhysics::ConstructParticle(), G4EmDNAPhysics_option6::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructProcess(), G4DNARuddIonisationModel::CorrectionFactor(), G4DNARuddIonisationExtendedModel::CorrectionFactor(), G4DNADingfelderChargeDecreaseModel::CrossSectionPerVolume(), G4DNADingfelderChargeIncreaseModel::CrossSectionPerVolume(), G4DNAMillerGreenExcitationModel::CrossSectionPerVolume(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::DifferentialCrossSection(), G4DNADingfelderChargeIncreaseModel::IncomingParticleBindingEnergyConstant(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNAIonElasticModel::Initialise(), G4DNAChargeIncrease::IsApplicable(), G4DNAChargeDecrease::IsApplicable(), G4DNAElastic::IsApplicable(), G4DNAExcitation::IsApplicable(), G4DNAIonisation::IsApplicable(), G4DNADingfelderChargeIncreaseModel::NumberOfFinalStates(), G4DNADingfelderChargeDecreaseModel::NumberOfFinalStates(), G4DNADingfelderChargeDecreaseModel::OutgoingParticleBindingEnergyConstant(), G4DNADingfelderChargeIncreaseModel::OutgoingParticleDefinition(), G4DNADingfelderChargeDecreaseModel::OutgoingParticleDefinition(), G4DNADingfelderChargeIncreaseModel::PartialCrossSection(), G4DNADingfelderChargeDecreaseModel::PartialCrossSection(), G4DNAMillerGreenExcitationModel::PartialCrossSection(), G4DNARuddIonisationModel::RandomizeEjectedElectronEnergy(), G4DNADingfelderChargeIncreaseModel::RandomSelect(), G4DNADingfelderChargeDecreaseModel::RandomSelect(), G4DNAMillerGreenExcitationModel::RandomSelect(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::Sum(), G4DNADingfelderChargeDecreaseModel::Sum(), and G4DNADingfelderChargeDecreaseModel::WaterBindingEnergyConstant().
G4DNAGenericIonsManager * G4DNAGenericIonsManager::Instance (void) static
Definition at line 35 of file G4DNAGenericIonsManager.cc.
View newest version in sPHENIX GitHub at line 35 of file G4DNAGenericIonsManager.cc
References G4DNAGenericIonsManager(), and theInstance.
Referenced by G4EmDNAPhysics_option3::ConstructParticle(), G4EmDNAPhysics_stationary::ConstructParticle(), G4EmDNAPhysics_stationary_option2::ConstructParticle(), G4EmDNAPhysics_stationary_option4::ConstructParticle(), G4EmDNAPhysics_stationary_option6::ConstructParticle(), G4EmDNAPhysics_option1::ConstructParticle(), G4EmDNAPhysics::ConstructParticle(), G4EmDNAPhysics_option2::ConstructParticle(), G4EmDNAPhysics_option7::ConstructParticle(), G4EmDNAPhysics_option8::ConstructParticle(), G4EmDNAPhysics_option4::ConstructParticle(), G4EmDNAPhysics_option5::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructParticle(), G4EmLEPTSPhysics::ConstructParticle(), G4EmDNAPhysics_option6::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructProcess(), G4DNARuddIonisationModel::CorrectionFactor(), G4DNARuddIonisationExtendedModel::CorrectionFactor(), G4DNADingfelderChargeDecreaseModel::CrossSectionPerVolume(), G4DNADingfelderChargeIncreaseModel::CrossSectionPerVolume(), G4DNAMillerGreenExcitationModel::CrossSectionPerVolume(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::DifferentialCrossSection(), G4DNADingfelderChargeIncreaseModel::IncomingParticleBindingEnergyConstant(), G4DNADingfelderChargeDecreaseModel::Initialise(), G4DNADingfelderChargeIncreaseModel::Initialise(), G4DNAMillerGreenExcitationModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNAIonElasticModel::Initialise(), G4DNAChargeIncrease::IsApplicable(), G4DNAChargeDecrease::IsApplicable(), G4DNAElastic::IsApplicable(), G4DNAExcitation::IsApplicable(), G4DNAIonisation::IsApplicable(), G4DNADingfelderChargeIncreaseModel::NumberOfFinalStates(), G4DNADingfelderChargeDecreaseModel::NumberOfFinalStates(), G4DNADingfelderChargeDecreaseModel::OutgoingParticleBindingEnergyConstant(), G4DNADingfelderChargeIncreaseModel::OutgoingParticleDefinition(), G4DNADingfelderChargeDecreaseModel::OutgoingParticleDefinition(), G4DNADingfelderChargeIncreaseModel::PartialCrossSection(), G4DNADingfelderChargeDecreaseModel::PartialCrossSection(), G4DNAMillerGreenExcitationModel::PartialCrossSection(), G4DNARuddIonisationModel::RandomizeEjectedElectronEnergy(), G4DNADingfelderChargeIncreaseModel::RandomSelect(), G4DNADingfelderChargeDecreaseModel::RandomSelect(), G4DNAMillerGreenExcitationModel::RandomSelect(), G4DNARuddIonisationExtendedModel::RejectionFunction(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::Sum(), G4DNADingfelderChargeDecreaseModel::Sum(), and G4DNADingfelderChargeDecreaseModel::WaterBindingEnergyConstant().
const G4DNAGenericIonsManager& G4DNAGenericIonsManager::operator= (const G4DNAGenericIonsManager &) private
Member Data Documentation
IonsMap G4DNAGenericIonsManager::map private
Definition at line 55 of file G4DNAGenericIonsManager.hh.
View newest version in sPHENIX GitHub at line 55 of file G4DNAGenericIonsManager.hh
Referenced by G4DNAGenericIonsManager(), and GetIon().
G4DNAGenericIonsManager * G4DNAGenericIonsManager::theInstance static private
Definition at line 51 of file G4DNAGenericIonsManager.hh.
View newest version in sPHENIX GitHub at line 51 of file G4DNAGenericIonsManager.hh
Referenced by Instance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNAGenericIonsManager.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4DNAGenericIonsManager.cc