ECCE @ EIC Software: G4BOptrForceCollision Class Reference
G4BOptrForceCollision Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptrForceCollision.hh>
Public Member Functions
G4BOptrForceCollision (G4String particleToForce, G4String name="ForceCollision")
G4BOptrForceCollision (const G4ParticleDefinition *particleToForce, G4String name="ForceCollision")
~G4BOptrForceCollision ()
virtual void Configure () final
virtual void ConfigureForWorker () final
virtual void StartRun () final
virtual void StartTracking (const G4Track *track) final
virtual void ExitBiasing (const G4Track *, const G4BiasingProcessInterface *) final
virtual void EndTracking () final
void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced) final
void OperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced) final
Public Member Functions inherited from G4VBiasingOperator
G4VBiasingOperator (G4String name)
virtual ~G4VBiasingOperator ()
const G4String GetName () const
void AttachTo (const G4LogicalVolume *)
G4BiasingAppliedCase GetPreviousBiasingAppliedCase () const
G4VBiasingOperation * GetProposedOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
G4VBiasingOperation * GetProposedNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ExitingBiasing (const G4Track *track, const G4BiasingProcessInterface *callingProcess)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *operationApplied, const G4VParticleChange *particleChangeProduced)
void ReportOperationApplied (const G4BiasingProcessInterface *callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation *occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation *finalStateOperationApplied, const G4VParticleChange *particleChangeProduced)
const G4VBiasingOperation * GetPreviousNonPhysicsAppliedOperation ()
Private Member Functions
virtual G4VBiasingOperation * ProposeNonPhysicsBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final
virtual G4VBiasingOperation * ProposeOccurenceBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final
virtual G4VBiasingOperation * ProposeFinalStateBiasingOperation (const G4Track *track, const G4BiasingProcessInterface *callingProcess) final
Private Attributes
G4int fForceCollisionModelID
const G4Track * fCurrentTrack
G4BOptrForceCollisionTrackData * fCurrentTrackData
std::map< const
G4BiasingProcessInterface
*, G4BOptnForceFreeFlight * > fFreeFlightOperations
G4BOptnForceCommonTruncatedExp * fSharedForceInteractionOperation
G4BOptnCloning * fCloningOperation
G4double fInitialTrackWeight
G4bool fSetup
const G4ParticleDefinition * fParticleToBias
Additional Inherited Members
Static Public Member Functions inherited from G4VBiasingOperator
static const std::vector
< G4VBiasingOperator * > & GetBiasingOperators ()
static G4VBiasingOperator * GetBiasingOperator (const G4LogicalVolume *)
Detailed Description
Definition at line 58 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BOptrForceCollision.hh
Constructor & Destructor Documentation
G4BOptrForceCollision::G4BOptrForceCollision (G4String particleToForce, G4String name = "ForceCollision")
Definition at line 46 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 46 of file G4BOptrForceCollision.cc
References fCloningOperation, G4ParticleTable::FindParticle(), fParticleToBias, fSharedForceInteractionOperation, G4endl, G4Exception(), G4ParticleTable::GetParticleTable(), and JustWarning.
G4BOptrForceCollision::G4BOptrForceCollision (const G4ParticleDefinition * particleToForce, G4String name = "ForceCollision")
Definition at line 70 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 70 of file G4BOptrForceCollision.cc
References fCloningOperation, fParticleToBias, fSharedForceInteractionOperation, and particle.
G4BOptrForceCollision::~G4BOptrForceCollision ()
Definition at line 84 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 84 of file G4BOptrForceCollision.cc
References fCloningOperation, fFreeFlightOperations, fSharedForceInteractionOperation, and it.
Member Function Documentation
void G4BOptrForceCollision::Configure () final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 94 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 94 of file G4BOptrForceCollision.cc
References ConfigureForWorker(), fForceCollisionModelID, and G4PhysicsModelCatalog::Register().
void G4BOptrForceCollision::ConfigureForWorker () final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 104 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 104 of file G4BOptrForceCollision.cc
References fForceCollisionModelID, fFreeFlightOperations, fParticleToBias, fSetup, G4BiasingProcessSharedData::GetPhysicsBiasingProcessInterfaces(), G4ParticleDefinition::GetProcessManager(), G4VProcess::GetProcessName(), G4BiasingProcessInterface::GetSharedData(), G4BiasingProcessInterface::GetWrappedProcess(), and G4PhysicsModelCatalog::Register().
Referenced by Configure().
void G4BOptrForceCollision::EndTracking () final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 316 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 316 of file G4BOptrForceCollision.cc
References fCurrentTrack, fCurrentTrackData, fKillTrackAndSecondaries, fStopAndKill, G4Exception(), G4VBiasingOperator::GetName(), G4Track::GetTrackStatus(), G4BOptrForceCollisionTrackData::IsFreeFromBiasing(), and JustWarning.
virtual void G4BOptrForceCollision::ExitBiasing (const G4Track * , const G4BiasingProcessInterface *) inline final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 75 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 75 of file G4BOptrForceCollision.hh
void G4BOptrForceCollision::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * operationApplied, const G4VParticleChange * particleChangeProduced) final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 337 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 337 of file G4BOptrForceCollision.cc
References BAC_None, fCloningOperation, fCurrentTrackData, fForceCollisionModelID, G4BOptrForceCollisionTrackData::fForceCollisionState, fFreeFlightOperations, fSharedForceInteractionOperation, G4endl, G4Exception(), G4BOptnCloning::GetCloneTrack(), G4BOptnForceCommonTruncatedExp::GetInteractionOccured(), JustWarning, G4BOptrForceCollisionTrackData::Reset(), and G4Track::SetAuxiliaryTrackInformation().
void G4BOptrForceCollision::OperationApplied (const G4BiasingProcessInterface * callingProcess, G4BiasingAppliedCase biasingCase, G4VBiasingOperation * occurenceOperationApplied, G4double weightForOccurenceInteraction, G4VBiasingOperation * finalStateOperationApplied, const G4VParticleChange * particleChangeProduced) final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 407 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 407 of file G4BOptrForceCollision.cc
References fCurrentTrackData, G4BOptrForceCollisionTrackData::fForceCollisionState, fSharedForceInteractionOperation, G4endl, G4Exception(), G4BOptnForceCommonTruncatedExp::GetInteractionOccured(), JustWarning, and G4BOptrForceCollisionTrackData::Reset().
G4VBiasingOperation * G4BOptrForceCollision::ProposeFinalStateBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final private virtual
Implements G4VBiasingOperator.
Definition at line 300 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 300 of file G4BOptrForceCollision.cc
References G4BiasingProcessInterface::GetCurrentOccurenceBiasingOperation().
G4VBiasingOperation * G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final private virtual
Implements G4VBiasingOperator.
Definition at line 257 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 257 of file G4BOptrForceCollision.cc
References fCloningOperation, fCurrentTrackData, fForceCollisionModelID, G4BOptrForceCollisionTrackData::fForceCollisionOperator, G4BOptrForceCollisionTrackData::fForceCollisionState, fGeomBoundary, fInitialTrackWeight, fParticleToBias, G4Track::GetAuxiliaryTrackInformation(), G4Track::GetDefinition(), G4Step::GetPreStepPoint(), G4Track::GetStep(), G4StepPoint::GetStepStatus(), G4Track::GetWeight(), G4BOptrForceCollisionTrackData::IsFreeFromBiasing(), G4Track::SetAuxiliaryTrackInformation(), and G4BOptnCloning::SetCloneWeights().
G4VBiasingOperation * G4BOptrForceCollision::ProposeOccurenceBiasingOperation (const G4Track * track, const G4BiasingProcessInterface * callingProcess) final private virtual
Implements G4VBiasingOperator.
Definition at line 135 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 135 of file G4BOptrForceCollision.cc
References G4BOptnForceCommonTruncatedExp::AddCrossSection(), DBL_MAX, DBL_MIN, fCurrentTrackData, fForceCollisionModelID, G4BOptrForceCollisionTrackData::fForceCollisionState, fFreeFlightOperations, fInitialTrackWeight, fParticleToBias, fSharedForceInteractionOperation, G4Track::GetAuxiliaryTrackInformation(), G4VProcess::GetCurrentInteractionLength(), G4Track::GetCurrentStepNumber(), G4Track::GetDefinition(), G4BOptnForceCommonTruncatedExp::GetInitialMomentum(), G4BOptnForceCommonTruncatedExp::GetMaximumDistance(), G4Track::GetMomentum(), G4BOptnForceCommonTruncatedExp::GetNumberOfSharing(), G4BiasingProcessSharedData::GetPhysicsBiasingProcessInterfaces(), G4BiasingProcessInterface::GetSharedData(), G4Track::GetStep(), G4BiasingProcessInterface::GetWrappedProcess(), G4BOptnForceCommonTruncatedExp::Initialize(), G4BOptrForceCollisionTrackData::Reset(), G4BOptnForceFreeFlight::ResetInitialTrackWeight(), G4BOptnForceCommonTruncatedExp::Sample(), and G4BOptnForceCommonTruncatedExp::UpdateForStep().
void G4BOptrForceCollision::StartRun () final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 130 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 130 of file G4BOptrForceCollision.cc
void G4BOptrForceCollision::StartTracking (const G4Track * track) final virtual
Reimplemented from G4VBiasingOperator.
Definition at line 309 of file G4BOptrForceCollision.cc.
View newest version in sPHENIX GitHub at line 309 of file G4BOptrForceCollision.cc
References fCurrentTrack, fCurrentTrackData, and track.
Member Data Documentation
G4BOptnCloning* G4BOptrForceCollision::fCloningOperation private
Definition at line 92 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 92 of file G4BOptrForceCollision.hh
Referenced by G4BOptrForceCollision(), OperationApplied(), ProposeNonPhysicsBiasingOperation(), and ~G4BOptrForceCollision().
const G4Track* G4BOptrForceCollision::fCurrentTrack private
Definition at line 88 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 88 of file G4BOptrForceCollision.hh
Referenced by EndTracking(), and StartTracking().
G4BOptrForceCollisionTrackData* G4BOptrForceCollision::fCurrentTrackData private
Definition at line 89 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 89 of file G4BOptrForceCollision.hh
Referenced by EndTracking(), OperationApplied(), ProposeNonPhysicsBiasingOperation(), ProposeOccurenceBiasingOperation(), and StartTracking().
G4int G4BOptrForceCollision::fForceCollisionModelID private
Definition at line 87 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 87 of file G4BOptrForceCollision.hh
Referenced by Configure(), ConfigureForWorker(), OperationApplied(), ProposeNonPhysicsBiasingOperation(), and ProposeOccurenceBiasingOperation().
std::map< const G4BiasingProcessInterface*, G4BOptnForceFreeFlight* > G4BOptrForceCollision::fFreeFlightOperations private
Definition at line 90 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 90 of file G4BOptrForceCollision.hh
Referenced by ConfigureForWorker(), OperationApplied(), ProposeOccurenceBiasingOperation(), and ~G4BOptrForceCollision().
G4double G4BOptrForceCollision::fInitialTrackWeight private
Definition at line 93 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 93 of file G4BOptrForceCollision.hh
Referenced by ProposeNonPhysicsBiasingOperation(), and ProposeOccurenceBiasingOperation().
const G4ParticleDefinition* G4BOptrForceCollision::fParticleToBias private
Definition at line 95 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 95 of file G4BOptrForceCollision.hh
Referenced by ConfigureForWorker(), G4BOptrForceCollision(), ProposeNonPhysicsBiasingOperation(), and ProposeOccurenceBiasingOperation().
G4bool G4BOptrForceCollision::fSetup private
Definition at line 94 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 94 of file G4BOptrForceCollision.hh
Referenced by ConfigureForWorker().
G4BOptnForceCommonTruncatedExp* G4BOptrForceCollision::fSharedForceInteractionOperation private
Definition at line 91 of file G4BOptrForceCollision.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BOptrForceCollision.hh
Referenced by G4BOptrForceCollision(), OperationApplied(), ProposeOccurenceBiasingOperation(), and ~G4BOptrForceCollision().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptrForceCollision.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BOptrForceCollision.cc