ECCE @ EIC Software: G4INCL::CascadeAction Class Reference
G4INCL::CascadeAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCascadeAction.hh>
Public Member Functions
CascadeAction ()
virtual ~CascadeAction ()
virtual void beforeRunUserAction (Config const *)
virtual void beforeCascadeUserAction (IPropagationModel *)
virtual void beforePropagationUserAction (IPropagationModel *)
virtual void beforeAvatarUserAction (IAvatar *, Nucleus *)
virtual void afterAvatarUserAction (IAvatar *, Nucleus *, FinalState *)
virtual void afterPropagationUserAction (IPropagationModel *, IAvatar *)
virtual void afterCascadeUserAction (Nucleus *)
virtual void afterRunUserAction ()
Private Member Functions
void beforeRunAction (Config const *config)
void beforeCascadeAction (IPropagationModel *)
void beforePropagationAction (IPropagationModel *pm)
void beforeAvatarAction (IAvatar *a, Nucleus *n)
void afterAvatarAction (IAvatar *a, Nucleus *n, FinalState *fs)
void afterPropagationAction (IPropagationModel *pm, IAvatar *avatar)
void afterCascadeAction (Nucleus *)
void afterRunAction ()
void beforeRunDefaultAction (Config const *config)
void beforeCascadeDefaultAction (IPropagationModel *pm)
void beforePropagationDefaultAction (IPropagationModel *pm)
void beforeAvatarDefaultAction (IAvatar *a, Nucleus *n)
void afterAvatarDefaultAction (IAvatar *a, Nucleus *n, FinalState *fs)
void afterPropagationDefaultAction (IPropagationModel *pm, IAvatar *avatar)
void afterCascadeDefaultAction (Nucleus *)
void afterRunDefaultAction ()
Private Attributes
long stepCounter
Friends
class INCL
Detailed Description
Definition at line 57 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 57 of file G4INCLCascadeAction.hh
Constructor & Destructor Documentation
G4INCL::CascadeAction::CascadeAction ()
Definition at line 44 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 44 of file G4INCLCascadeAction.cc
G4INCL::CascadeAction::~CascadeAction () virtual
Definition at line 48 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 48 of file G4INCLCascadeAction.cc
Member Function Documentation
void G4INCL::CascadeAction::afterAvatarAction (IAvatar * a, Nucleus * n, FinalState * fs) private
Definition at line 71 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 71 of file G4INCLCascadeAction.cc
References afterAvatarDefaultAction(), and afterAvatarUserAction().
Referenced by G4INCL::INCL::cascade().
void G4INCL::CascadeAction::afterAvatarDefaultAction (IAvatar * a, Nucleus * n, FinalState * fs) private
Definition at line 108 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 108 of file G4INCLCascadeAction.cc
References e, G4INCL::FinalState::getCreatedParticles(), G4INCL::IAvatar::getID(), G4INCL::FinalState::getModifiedParticles(), G4INCL::Random::getSeeds(), INCL_DEBUG, G4INCL::IAvatar::isACollision(), and G4INCL::IAvatar::isADecay().
Referenced by afterAvatarAction().
virtual void G4INCL::CascadeAction::afterAvatarUserAction (IAvatar * , Nucleus * , FinalState *) inline virtual
Reimplemented in G4INCL::AvatarDumpAction.
Definition at line 69 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 69 of file G4INCLCascadeAction.hh
Referenced by afterAvatarAction().
void G4INCL::CascadeAction::afterCascadeAction (Nucleus * n) private
Definition at line 81 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 81 of file G4INCLCascadeAction.cc
References afterCascadeDefaultAction(), and afterCascadeUserAction().
Referenced by G4INCL::INCL::processEvent().
void G4INCL::CascadeAction::afterCascadeDefaultAction (Nucleus *) private
Definition at line 141 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 141 of file G4INCLCascadeAction.cc
Referenced by afterCascadeAction().
virtual void G4INCL::CascadeAction::afterCascadeUserAction (Nucleus *) inline virtual
Reimplemented in G4INCL::AvatarDumpAction.
Definition at line 71 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 71 of file G4INCLCascadeAction.hh
Referenced by afterCascadeAction().
void G4INCL::CascadeAction::afterPropagationAction (IPropagationModel * pm, IAvatar * avatar) private
Definition at line 76 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 76 of file G4INCLCascadeAction.cc
References afterPropagationDefaultAction(), and afterPropagationUserAction().
Referenced by G4INCL::INCL::cascade().
void G4INCL::CascadeAction::afterPropagationDefaultAction (IPropagationModel * pm, IAvatar * avatar) private
Definition at line 132 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 132 of file G4INCLCascadeAction.cc
References stepCounter.
Referenced by afterPropagationAction().
virtual void G4INCL::CascadeAction::afterPropagationUserAction (IPropagationModel * , IAvatar *) inline virtual
Definition at line 70 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 70 of file G4INCLCascadeAction.hh
Referenced by afterPropagationAction().
void G4INCL::CascadeAction::afterRunAction () private
Definition at line 86 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 86 of file G4INCLCascadeAction.cc
References afterRunDefaultAction(), and afterRunUserAction().
Referenced by G4INCL::INCL::~INCL().
void G4INCL::CascadeAction::afterRunDefaultAction () private
Definition at line 143 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 143 of file G4INCLCascadeAction.cc
Referenced by afterRunAction().
virtual void G4INCL::CascadeAction::afterRunUserAction () inline virtual
Definition at line 72 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 72 of file G4INCLCascadeAction.hh
Referenced by afterRunAction().
void G4INCL::CascadeAction::beforeAvatarAction (IAvatar * a, Nucleus * n) private
Definition at line 66 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 66 of file G4INCLCascadeAction.cc
References beforeAvatarDefaultAction(), and beforeAvatarUserAction().
Referenced by G4INCL::INCL::cascade().
void G4INCL::CascadeAction::beforeAvatarDefaultAction (IAvatar * a, Nucleus * n) private
Definition at line 101 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 101 of file G4INCLCascadeAction.cc
References G4INCL::IAvatar::dump(), G4INCL::Store::getBook(), G4INCL::IAvatar::getID(), G4INCL::Random::getSeeds(), G4INCL::Nucleus::getStore(), G4INCL::IAvatar::getType(), INCL_DEBUG, and G4INCL::Book::incrementAvatars().
Referenced by beforeAvatarAction().
virtual void G4INCL::CascadeAction::beforeAvatarUserAction (IAvatar * , Nucleus *) inline virtual
Definition at line 68 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 68 of file G4INCLCascadeAction.hh
Referenced by beforeAvatarAction().
void G4INCL::CascadeAction::beforeCascadeAction (IPropagationModel * pm) private
Definition at line 56 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 56 of file G4INCLCascadeAction.cc
References beforeCascadeDefaultAction(), and beforeCascadeUserAction().
Referenced by G4INCL::INCL::processEvent().
void G4INCL::CascadeAction::beforeCascadeDefaultAction (IPropagationModel * pm) private
Definition at line 95 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 95 of file G4INCLCascadeAction.cc
Referenced by beforeCascadeAction().
virtual void G4INCL::CascadeAction::beforeCascadeUserAction (IPropagationModel *) inline virtual
Reimplemented in G4INCL::AvatarDumpAction.
Definition at line 66 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLCascadeAction.hh
Referenced by beforeCascadeAction().
void G4INCL::CascadeAction::beforePropagationAction (IPropagationModel * pm) private
Definition at line 61 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 61 of file G4INCLCascadeAction.cc
References beforePropagationDefaultAction(), and beforePropagationUserAction().
Referenced by G4INCL::INCL::cascade().
void G4INCL::CascadeAction::beforePropagationDefaultAction (IPropagationModel * pm) private
Definition at line 97 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 97 of file G4INCLCascadeAction.cc
Referenced by beforePropagationAction().
virtual void G4INCL::CascadeAction::beforePropagationUserAction (IPropagationModel *) inline virtual
Definition at line 67 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLCascadeAction.hh
Referenced by beforePropagationAction().
void G4INCL::CascadeAction::beforeRunAction (Config const * config) private
Definition at line 51 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 51 of file G4INCLCascadeAction.cc
References beforeRunDefaultAction(), and beforeRunUserAction().
Referenced by G4INCL::INCL::INCL().
void G4INCL::CascadeAction::beforeRunDefaultAction (Config const * config) private
Definition at line 93 of file G4INCLCascadeAction.cc.
View newest version in sPHENIX GitHub at line 93 of file G4INCLCascadeAction.cc
Referenced by beforeRunAction().
virtual void G4INCL::CascadeAction::beforeRunUserAction (Config const *) inline virtual
Definition at line 65 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 65 of file G4INCLCascadeAction.hh
Referenced by beforeRunAction().
Friends And Related Function Documentation
friend class INCL friend
Definition at line 59 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 59 of file G4INCLCascadeAction.hh
Member Data Documentation
long G4INCL::CascadeAction::stepCounter private
Definition at line 96 of file G4INCLCascadeAction.hh.
View newest version in sPHENIX GitHub at line 96 of file G4INCLCascadeAction.hh
Referenced by afterPropagationDefaultAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCascadeAction.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLCascadeAction.cc