ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/showers/plotHisto.C File Reference
plotHisto.C File Reference
Functions
hist1 Draw ("HIST")
Variables
TFile f = TFile("run2.root")
TCanvas * c1 = new TCanvas("c1", " ")
TH1D * hist1 = (TH1D*)f.Get("1")
TH1D * hist2 = (TH1D*)f.Get("2")
TH1D * hist3 = (TH1D*)f.Get("3")
TH1D * hist4 = (TH1D*)f.Get("4")
TH1D * hist5 = (TH1D*)f.Get("5")
Function Documentation
hist26 Draw ("HIST")
Referenced by G4VSceneHandler::AddCompound().
Variable Documentation
TCanvas* c1 = new TCanvas("c1", " ")
Definition at line 7 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 7 of file plotHisto.C
Referenced by __example_6.f__(), __example_7.f__(), __example_8.f__(), G4ExtrudedSolid::AddGeneralPolygonFacets(), airy1(), airy1d(), airy2(), airy2d(), aiz(), kdfinder::angle_between_vectors(), biz(), G4KineticTrackVector::Boost(), G4KineticTrackVector::BoostBeam(), boundParamResolution(), G4DNAScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4DNAUeharaScreenedRutherfordElasticModel::BrennerZaiderRandomizeCosTheta(), G4VLongitudinalStringDecay::CalculateHadronTimePosition(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), CMDistortionAnalysis(), CMDistortionAnalysisCart(), CMDistortionAnalysisPhiR(), G4KleinNishinaCompton::ComputeCrossSectionPerAtom(), G4KleinNishinaModel::ComputeCrossSectionPerAtom(), G4BetheHeitlerModel::ComputeCrossSectionPerAtom(), G4UrbanMscModel::ComputeCrossSectionPerAtom(), G4UrbanAdjointMscModel::ComputeCrossSectionPerAtom(), G4SandiaTable::ComputeMatSandiaMatrixPAI(), G4SandiaTable::ComputeMatTable(), G4JTPolynomialSolver::ComputeNewEstimate(), G4PairProductionRelModel::ComputeParametrizedXSectionPerAtom(), G4INCL::CoulombNonRelativistic::distortOut(), G4Abla::eflmac(), G4Abla::eflmac_profi(), G4RKFieldIntegrator::Erf(), errorOf1DHistograms(), errorOf2DHistograms(), CLHEP::HepRotation::eulerAngles(), expai(), expaid(), G4INCL::PiNToEtaChannel::fillFinalState(), FitNewton::NewtonMinimizerGradHessian::findSaddlePoint(), G4UImanager::ForeachS(), G4PolyhedraSide::G4PolyhedraSide(), gauss1(), gauss2(), gauss3(), gauss4(), CLHEP::RandGauss::get(), G4VXTRenergyLoss::GetComptonPerAtom(), G4NuclNuclDiffuseElastic::GetCoulombIntegralXsc(), G4DiffuseElastic::GetCoulombIntegralXsc(), G4RKFieldIntegrator::GetExcitationEnergy(), TabulatedField3D::GetFieldValue(), EMField::GetFieldValue(), AnnularFieldSim::GetStepDistortion(), G4Abla::guet(), G4UImanager::LoopS(), CCalMagneticField::MagneticField(), FitNewton::NewtonMinimizerGradHessian::minimize(), perigeeParamResolution(), plot(), plot_ratio(), pycjdc(), pyeig4(), pygau2(), pygaus(), pyglui(), pyh2xx(), pyhext(), pyhiscat(), pynjdc(), pyrvg1(), pyrvg2(), pyrvg3(), pyrvne(), pyscat(), pysfdc(), pysghf(), pyx2xg(), pyx2xh(), G4NuclearRadii::RadiusECS(), G4InitXscPAI::RePartDielectricConst(), G4PAIySection::RePartDielectricConst(), G4PAIxSection::RePartDielectricConst(), CLHEP::RandGauss::restoreDistState(), CLHEP::RandFlat::restoreDistState(), CLHEP::HepLorentzRotation::rotateX(), CLHEP::HepRotation::rotateX(), CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), CLHEP::HepRotation::rotateZ(), RUNME(), G4InitXscPAI::RutherfordIntegral(), G4PAIySection::RutherfordIntegral(), G4PAIxSection::RutherfordIntegral(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4BoldyshevTripletModel::SampleSecondaries(), G4SandiaTable::SandiaIntervals(), G4UIcontrolMessenger::SetNewValue(), G4LivermorePolarizedGammaConversionModel::SetPhi(), G4hRDEnergyLoss::SetStepFunction(), G4RDVeLowEnergyLoss::SetStepFunction(), G4BetaDecayCorrections::ShapeFactor(), G4KineticTrackVector::Shift(), G4RKG3_Stepper::StepNoErr(), G4DormandPrinceRK56::Stepper(), G4CashKarpRKF45::Stepper(), G4DormandPrinceRK78::Stepper(), and streqci().
TFile f = TFile("run2.root")
Definition at line 6 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 6 of file plotHisto.C
Referenced by MultiArray< TVector3 >::Add(), PHG4ScintillatorSlatv1::add_edep(), G4MTcoutDestination::AddMasterOutput(), G4GMocrenFileSceneHandler::AddPrimitive(), G4ForwardXrayTR::AngleDensity(), G4AntiNeutronAnnihilationAtRest::AntiNeutronAnnihilation(), G4ErrorMatrix::apply(), G4ErrorSymMatrix::apply(), G4NeutronRadCapture::ApplyYourself(), GPUTPCTrackParam::ApproximateBetheBloch(), CB_G4UserEventAction::BeginOfEventAction(), CB_G4UserRunAction::BeginOfRunAction(), BEmcProfile::BEmcProfile(), GPUTPCTrackParam::BetheBlochGas(), GPUTPCTrackParam::BetheBlochGeant(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_AUTO_TEST_CASE(), G4FermiBreakUpVI::BreakFragment(), G4PenelopeRayleighModel::BuildFormFactorTable(), Acts::Legacy::AtlasSeedfinder< SpacePoint >::buildFrameWork(), G4StatMFMicroPartition::CalcPartitionProbability(), GPUTPCTrackParam::CalculateFitParameters(), VertexFitFunc::calcValGradHessian(), Call< g, f, A >::call(), GPUTPCTrackParam::CheckNumericalQuality(), ChromosomeParameterisation::ChromosomeParameterisation(), pyG4UserStackingAction::CB_G4UserStackingAction::ClassifyNewTrack(), doiPETAnalysis::Close(), Acts::AnnulusBounds::closestOnSegment(), cm_energy(), cmpL(), cmpR(), PgPostBankBackupManager::commitAllBankfromTFile(), compare_sign(), Acts::BoundaryCheck::computeClosestPointOnPolygon(), G4RToEConvForElectron::ComputeLoss(), G4RToEConvForPositron::ComputeLoss(), c2_factory< float_type >::const_plugin_function(), GPUTPCTrackParam::CorrectForMeanMaterial(), G4ChipsKaonMinusInelasticXS::CrossSectionFormula(), G4ChipsPionMinusInelasticXS::CrossSectionFormula(), G4ChipsKaonPlusInelasticXS::CrossSectionFormula(), G4ChipsPionPlusInelasticXS::CrossSectionFormula(), crsjet(), csz__huft_build(), Packet_fvtx_dcm0::decode(), G4SDManager::DeRegisterSDFilter(), Acts::deriveEnergyLossBetheQOverP(), G4VFieldModel::DescribeYourselfTo(), G4SDManager::DestroyFilters(), SegmentationAlpide::detectorToLocalUnchecked(), FW::determineEventFilesRange(), G4AdjointIonIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4AdjointhIonisationModel::DiffCrossSectionPerAtomPrimToSecond(), G4AtimaFluctuations::Dispersion(), G4TriangularFacet::Distance(), doCompression(), oncsSub_idcaenv1742::dump(), G4FermiFragmentsPoolVI::Dump(), kdfinder::CircleFit< T >::eigen2x2(), G4BraggModel::ElectronicStoppingPower(), dfe::SmallVector< T, N, Allocator >::emplace(), LiteCaloEval::End(), CB_G4UserEventAction::EndOfEventAction(), HistoManager::EndOfRun(), CB_G4UserRunAction::EndOfRunAction(), G4PolynomialPDF::Evaluate(), G4AntiNeutronAnnihilationAtRest::ExNu(), Acts::Polyhedron::extent(), SvtxClusterEval::fast_approx_atan2(), PgPostBankBackupManager::fetchAllBank2TFile(), PgPostBankBackupManager::fetchBank2TFile(), Acts::Legacy::AtlasSeedfinder< SpacePoint >::fillLists(), GPUTPCTrackParam::Filter(), G4ASTARStopping::FindData(), G4PSTARStopping::FindData(), ActsFatras::findMass(), G4eIonisationSpectrum::Function(), G4RDeIonisationSpectrum::Function(), G4eBremsstrahlungSpectrum::Function(), G4RDeBremsstrahlungSpectrum::Function(), g(), G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AnyMethod::G4AnyMethod(), G4ElasticHadrNucleusHE::G4ElasticHadrNucleusHE(), G4Expf(), G4LevelReader::G4LevelReader(), G4Logf(), G4PhotonEvaporation::G4PhotonEvaporation(), G4Pow::G4Pow(), G4QuickRand(), GammaFit(), gauss1(), gauss2(), gauss3(), gauss4(), gen_bitlen(), CLHEP::RandBinomial::genBinomial(), G4eeToHadronsModel::GenerateCMPhoton(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), MultiArray< TVector3 >::Get(), nlohmann::detail::dtoa_impl::get_cached_power_for_binary_exponent(), CylinderGeom_Mvtx::get_pixel_from_local_coords(), mRICH::getdAng(), GPUTPCTrackParam::GetDCAPoint(), G4TripathiLightCrossSection::GetElementCrossSection(), G4ElectroNuclearCrossSection::GetEquivalentPhotonEnergy(), MultiArray< TVector3 >::GetPtr(), GPUTPCTrackParam::GetS(), PHG4mRICHDetector::LensPar::GetSagita(), G4PolynomialPDF::GetX(), ghvq(), gphoton(), half::half(), halfFunction< T >::halfFunction(), PHG4OuterHcalSteppingAction::Init(), G4FermiFragmentsPoolVI::Initialise(), G4PhotonEvaporation::InitialiseGRData(), G4PolarizedMollerCrossSection::Initialize(), GPUTPCTrackParam::InitParam(), G4TessellatedSolid::InsideNoVoxels(), G4INCL::IFunction1D::inverseCDFTable(), HepPolyhedron::InvertFacets(), G4INCL::InvFInterpolationTable::InvFInterpolationTable(), G4EmCorrections::KShellCorrection(), G4LevelReader::LevelManager(), AnnularFieldSim::load_and_resample_spacecharge(), AnnularFieldSim::load_spacecharge(), Rossegger::LoadZeroes(), CaloCalibEmc_Pi0::Loop(), G4EmCorrections::LShellCorrection(), main(), G4NuclearLevelData::MaxLevelEnergy(), Acts::Material::meanExcitationEnergy(), mRICH::mRICH(), MultiArray< TVector3 >::MultiArray(), MyTClonesArray::MyEventFloat(), MySimpleTree::MyFloat(), pyG4UserStackingAction::CB_G4UserStackingAction::NewStage(), G4TessellatedSolid::Normal(), G4LevelReader::NormalizedICCProbability(), Acts::MaterialProperties::operator bool(), Acts::Logging::OutStream::operator<<(), c2_const_ptr< G4double >::operator=(), c2_ptr< G4double >::operator=(), parton(), kdfinder::Helix< T >::pathLength(), pfileopen(), plot(), Plot(), plot_matscan(), plot_matscan_tdr(), c2_factory< float_type >::plugin_function(), CB_G4UserTrackingAction::PostUserTrackingAction(), pyG4UserStackingAction::CB_G4UserStackingAction::PrepareNewEvent(), CB_G4UserTrackingAction::PreUserTrackingAction(), G4INCL::IFunction1D::primitive(), MakeSimpleTree::process_event(), PHG4TpcElectronDrift::process_event(), CCaloSD::ProcessHits(), Acts::Legacy::AtlasSeedfinder< SpacePoint >::production3Sp(), prt_set_style(), ptwXY_createFromFunctionBisect(), ptwXY_f_integrate(), ptwXY_groupOneFunction(), ptwXY_groupThreeFunctions(), ptwXY_groupTwoFunctions(), ptwXY_unitbaseInterpolate(), pycbal(), pycrth(), pyfact(), pygau2(), pygaus(), ActsFatras::LandauDistribution::quantile(), Acts::ProtoLayer::radialDistance(), Read(), ReadASCII(), PHParameters::ReadFromFile(), G4IonFluctuations::RelativisticFactor(), kdfinder::LinearFit< T >::RobustFit(), GPUTPCTrackParam::Rotate(), G4SampleResonance::SampleMass(), G4VScatteringCollision::SampleResonanceMass(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4eBremParametrizedModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), MultiArray< TVector3 >::Set(), PHG4Hitv1::set_edep(), EICG4dRICHHit::set_edep(), PHG4HitEval::set_eion(), c2_const_ptr< G4double >::set_function(), G4RootHitContainer::set_leakage(), G4RootScintillatorSlatContainer::set_leakage(), G4RootScintillatorTowerContainer::set_leakage(), set_phimin(), set_phispan(), PHG4Hitv1::set_t(), EICG4dRICHHit::set_t(), set_thetamin(), set_thetaspan(), PHG4Hitv1::set_x(), PHG4Hitv1::set_y(), PHG4Hitv1::set_z(), G4INCL::Config::setAutosaveFrequency(), G4hhElastic::SetCofF2(), G4hhElastic::SetCofF3(), G4VEmProcess::SetCrossSectionBiasingFactor(), G4VEnergyLossProcess::SetCrossSectionBiasingFactor(), HistoManager::SetDefaultBeamPositionFlag(), G4MTcoutDestination::SetDefaultOutput(), G4INCL::Config::setFermiMomentumType(), PHNodeIOManager::setFile(), G4VPrimitiveScorer::SetFilter(), G4GHEKinematicsVector::setFlag(), FitNewton::ChiSquareGradHessian::setFunction(), FitNewton::GaussianRegGradHessian::setFunction(), RE01PrimaryGeneratorAction::SetHEPEvtGenerator(), ExN04PrimaryGeneratorAction::SetHEPEvtGenerator(), HepMCFlowAfterBurner::setMaxEta(), HepMCFlowAfterBurner::setMaxPt(), G4ReactionProduct::SetMayBeKilled(), HepMCFlowAfterBurner::setMinEta(), HepMCFlowAfterBurner::setMinPt(), G4ReactionProduct::SetNewlyAdded(), G4VEmModel::SetParticleChange(), G4BetaMinusDecay::SetUpBetaSpectrumSampler(), G4BetaPlusDecay::SetUpBetaSpectrumSampler(), G4EmCorrections::ShellCorrection(), Acts::AtlasStepper< ConstantBField >::step(), G4BraggModel::StoppingPower(), Acts::Frustum< value_t, DIM, SIDES >::svg(), GPUTPCTrackParam::TransportToX(), GPUTPCTrackParam::TransportToXWithMaterial(), A_Event::updateFramelist(), CB_G4UserSteppingAction::UserSteppingAction(), vegas(), G4eeCrossSections::Width2p(), G4eeCrossSections::WidthPg(), cheprep::BHepRepWriter::writeReal(), PHParametersContainer::WriteToFile(), PdbParameterMapContainer::WriteToFile(), PHParameters::WriteToFile(), and xDataXML_importFile2().
TH1D* hist1 = (TH1D*)f.Get("1")
Definition at line 9 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 9 of file plotHisto.C
Referenced by plot().
TH1D* hist2 = (TH1D*)f.Get("2")
Definition at line 12 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 12 of file plotHisto.C
TH1D* hist3 = (TH1D*)f.Get("3")
Definition at line 15 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 15 of file plotHisto.C
TH1D* hist4 = (TH1D*)f.Get("4")
Definition at line 18 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 18 of file plotHisto.C
TH1D* hist5 = (TH1D*)f.Get("5")
Definition at line 21 of file plotHisto.C.
View newest version in sPHENIX GitHub at line 21 of file plotHisto.C