ECCE @ EIC Software: G4ResonanceNames Class Reference
G4ResonanceNames Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4ResonanceNames.hh>
Public Member Functions
G4ResonanceNames ()
~G4ResonanceNames ()
G4bool operator== (const G4ResonanceNames &right) const
G4bool operator!= (const G4ResonanceNames &right) const
const std::vector< G4String > NstarNames () const
const std::vector< G4String > DeltastarNames () const
const std::vector< G4String > DeltaNames () const
const std::vector< G4String > LambdaNames () const
const std::vector< G4String > SigmaNames () const
const std::vector< G4String > XiNames () const
const G4String ShortName (const G4String &name)
G4double MinMass (const G4String &name)
Private Member Functions
G4ResonanceNames (const G4ResonanceNames &right)
G4ResonanceNames & operator= (const G4ResonanceNames &right)
Private Attributes
std::vector< G4String > nameNstar
std::vector< G4String > nameDeltastar
std::vector< G4String > nameDelta
std::vector< G4String > nameLambda
std::vector< G4String > nameSigma
std::vector< G4String > nameXi
std::map< G4String,
G4ParticleDefinition
*, std::less< G4String > > lowResMap
std::map< G4String, G4String,
std::less< G4String > > shortMap
Detailed Description
Definition at line 50 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ResonanceNames.hh
Constructor & Destructor Documentation
G4ResonanceNames::G4ResonanceNames ()
Definition at line 36 of file G4ResonanceNames.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ResonanceNames.cc
References G4ShortLivedConstructor::ConstructParticle(), G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), lowResMap, nameDelta, nameDeltastar, nameLambda, nameNstar, nameSigma, nameXi, and shortMap.
G4ResonanceNames::~G4ResonanceNames ()
Definition at line 318 of file G4ResonanceNames.cc.
View newest version in sPHENIX GitHub at line 318 of file G4ResonanceNames.cc
G4ResonanceNames::G4ResonanceNames (const G4ResonanceNames & right) private
Member Function Documentation
const std::vector<G4String> G4ResonanceNames::DeltaNames () const inline
Definition at line 66 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ResonanceNames.hh
References nameDelta.
const std::vector<G4String> G4ResonanceNames::DeltastarNames () const inline
Definition at line 64 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ResonanceNames.hh
References nameDeltastar.
const std::vector<G4String> G4ResonanceNames::LambdaNames () const inline
Definition at line 68 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ResonanceNames.hh
References nameLambda.
G4double G4ResonanceNames::MinMass (const G4String & name)
Definition at line 334 of file G4ResonanceNames.cc.
View newest version in sPHENIX GitHub at line 334 of file G4ResonanceNames.cc
References G4ParticleTable::FindParticle(), G4cout, G4endl, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), lowResMap, G4InuclParticleNames::pion(), and G4PionPlus::PionPlusDefinition().
const std::vector<G4String> G4ResonanceNames::NstarNames () const inline
Definition at line 62 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ResonanceNames.hh
References nameNstar.
G4bool G4ResonanceNames::operator!= (const G4ResonanceNames & right) const
Definition at line 328 of file G4ResonanceNames.cc.
View newest version in sPHENIX GitHub at line 328 of file G4ResonanceNames.cc
G4ResonanceNames& G4ResonanceNames::operator= (const G4ResonanceNames & right) private
G4bool G4ResonanceNames::operator== (const G4ResonanceNames & right) const
Definition at line 322 of file G4ResonanceNames.cc.
View newest version in sPHENIX GitHub at line 322 of file G4ResonanceNames.cc
const G4String G4ResonanceNames::ShortName (const G4String & name)
Definition at line 366 of file G4ResonanceNames.cc.
View newest version in sPHENIX GitHub at line 366 of file G4ResonanceNames.cc
References shortMap.
Referenced by G4XAnnihilationChannel::G4XAnnihilationChannel().
const std::vector<G4String> G4ResonanceNames::SigmaNames () const inline
Definition at line 70 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ResonanceNames.hh
References nameSigma.
const std::vector<G4String> G4ResonanceNames::XiNames () const inline
Definition at line 72 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ResonanceNames.hh
References nameSigma.
Member Data Documentation
std::map<G4String, G4ParticleDefinition*, std::less<G4String> > G4ResonanceNames::lowResMap private
Definition at line 94 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ResonanceNames.hh
Referenced by G4ResonanceNames(), and MinMass().
std::vector<G4String> G4ResonanceNames::nameDelta private
Definition at line 88 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ResonanceNames.hh
Referenced by DeltaNames(), and G4ResonanceNames().
std::vector<G4String> G4ResonanceNames::nameDeltastar private
Definition at line 87 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ResonanceNames.hh
Referenced by DeltastarNames(), and G4ResonanceNames().
std::vector<G4String> G4ResonanceNames::nameLambda private
Definition at line 89 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ResonanceNames.hh
Referenced by G4ResonanceNames(), and LambdaNames().
std::vector<G4String> G4ResonanceNames::nameNstar private
Definition at line 86 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ResonanceNames.hh
Referenced by G4ResonanceNames(), and NstarNames().
std::vector<G4String> G4ResonanceNames::nameSigma private
Definition at line 90 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ResonanceNames.hh
Referenced by G4ResonanceNames(), SigmaNames(), and XiNames().
std::vector<G4String> G4ResonanceNames::nameXi private
Definition at line 91 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ResonanceNames.hh
Referenced by G4ResonanceNames().
std::map<G4String, G4String, std::less<G4String> > G4ResonanceNames::shortMap private
Definition at line 97 of file G4ResonanceNames.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ResonanceNames.hh
Referenced by G4ResonanceNames(), and ShortName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4ResonanceNames.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4ResonanceNames.cc