ECCE @ EIC Software: G4SmartVoxelNode Class Reference
G4SmartVoxelNode Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4SmartVoxelNode.hh>
Public Member Functions
G4SmartVoxelNode (G4int pSlice=0)
~G4SmartVoxelNode ()
G4int GetVolume (G4int pVolumeNo) const
void Insert (G4int pVolumeNo)
size_t GetNoContained () const
size_t GetCapacity () const
void Reserve (G4int noSlices)
void Shrink ()
G4int GetMaxEquivalentSliceNo () const
void SetMaxEquivalentSliceNo (G4int pMax)
G4int GetMinEquivalentSliceNo () const
void SetMinEquivalentSliceNo (G4int pMin)
G4bool operator== (const G4SmartVoxelNode &v) const
Private Attributes
G4int fminEquivalent
G4int fmaxEquivalent
G4SliceVector fcontents
Detailed Description
Definition at line 55 of file G4SmartVoxelNode.hh.
View newest version in sPHENIX GitHub at line 55 of file G4SmartVoxelNode.hh
Constructor & Destructor Documentation
G4SmartVoxelNode::G4SmartVoxelNode (G4int pSlice = 0) inline
Definition at line 59 of file G4SmartVoxelNode.hh.
View newest version in sPHENIX GitHub at line 59 of file G4SmartVoxelNode.hh
G4SmartVoxelNode::~G4SmartVoxelNode ()
Definition at line 36 of file G4SmartVoxelNode.cc.
View newest version in sPHENIX GitHub at line 36 of file G4SmartVoxelNode.cc
Member Function Documentation
size_t G4SmartVoxelNode::GetCapacity () const inline
G4int G4SmartVoxelNode::GetMaxEquivalentSliceNo () const inline
Referenced by G4SmartVoxelHeader::CollectEquivalentNodes(), G4DrawVoxels::ComputeVoxelPolyhedra(), G4ParameterisedNavigation::ComputeVoxelSafety(), G4VoxelNavigation::ComputeVoxelSafety(), G4ParameterisedNavigation::LocateNextVoxel(), G4VoxelNavigation::LocateNextVoxel(), G4SmartVoxelHeader::RefineNodes(), and G4VoxelSafety::SafetyForVoxelHeader().
G4int G4SmartVoxelNode::GetMinEquivalentSliceNo () const inline
Referenced by G4ParameterisedNavigation::ComputeVoxelSafety(), G4VoxelNavigation::ComputeVoxelSafety(), G4ParameterisedNavigation::LocateNextVoxel(), G4VoxelNavigation::LocateNextVoxel(), G4SmartVoxelHeader::RefineNodes(), and G4VoxelSafety::SafetyForVoxelHeader().
size_t G4SmartVoxelNode::GetNoContained () const inline
Referenced by G4SmartVoxelHeader::CalculateQuality(), G4ParameterisedNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ParameterisedNavigation::LevelLocate(), operator==(), G4SmartVoxelHeader::RefineNodes(), and G4VoxelSafety::SafetyForVoxelNode().
G4int G4SmartVoxelNode::GetVolume (G4int pVolumeNo) const inline
Referenced by G4ParameterisedNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ParameterisedNavigation::LevelLocate(), operator==(), G4SmartVoxelHeader::RefineNodes(), and G4VoxelSafety::SafetyForVoxelNode().
void G4SmartVoxelNode::Insert (G4int pVolumeNo) inline
G4bool G4SmartVoxelNode::operator== (const G4SmartVoxelNode & v) const
Definition at line 45 of file G4SmartVoxelNode.cc.
View newest version in sPHENIX GitHub at line 45 of file G4SmartVoxelNode.cc
References GetNoContained(), and GetVolume().
void G4SmartVoxelNode::Reserve (G4int noSlices) inline
void G4SmartVoxelNode::SetMaxEquivalentSliceNo (G4int pMax) inline
Referenced by G4SmartVoxelHeader::BuildEquivalentSliceNos().
void G4SmartVoxelNode::SetMinEquivalentSliceNo (G4int pMin) inline
Referenced by G4SmartVoxelHeader::BuildEquivalentSliceNos().
void G4SmartVoxelNode::Shrink () inline
Member Data Documentation
G4SliceVector G4SmartVoxelNode::fcontents private
Definition at line 106 of file G4SmartVoxelNode.hh.
View newest version in sPHENIX GitHub at line 106 of file G4SmartVoxelNode.hh
G4int G4SmartVoxelNode::fmaxEquivalent private
Definition at line 105 of file G4SmartVoxelNode.hh.
View newest version in sPHENIX GitHub at line 105 of file G4SmartVoxelNode.hh
G4int G4SmartVoxelNode::fminEquivalent private
Definition at line 104 of file G4SmartVoxelNode.hh.
View newest version in sPHENIX GitHub at line 104 of file G4SmartVoxelNode.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4SmartVoxelNode.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4SmartVoxelNode.cc