ECCE @ EIC Software: G4KDNode< PointT > Class Template Reference
G4KDNode< PointT > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4KDNode.hh>
Public Member Functions
G4KDNode (G4KDTree *, PointT *, G4KDNode_Base *)
virtual ~G4KDNode ()
void * operator new (size_t)
void operator delete (void *)
PointT * GetPoint ()
virtual double operator[] (size_t i) const
virtual void InactiveNode ()
virtual bool IsValid () const
template<>
~G4KDNode ()
template<>
~G4KDNode ()
template<>
~G4KDNode ()
template<>
~G4KDNode ()
Public Member Functions inherited from G4KDNode_Base
G4KDNode_Base (G4KDTree *, G4KDNode_Base *)
virtual ~G4KDNode_Base ()
G4KDTree * GetTree () const
void SetTree (G4KDTree *tree)
int GetDim () const
int GetAxis () const
G4KDNode_Base * GetParent ()
G4KDNode_Base * GetLeft ()
G4KDNode_Base * GetRight ()
template<typename Position >
G4KDNode_Base * FindParent (const Position &x0)
template<typename PointT >
G4KDNode_Base * Insert (PointT *point)
template<typename PointT >
G4KDNode_Base * Insert (const PointT &point)
int Insert (G4KDNode_Base *newNode)
void PullSubTree ()
void RetrieveNodeList (std::list< G4KDNode_Base * > &node_list)
void Print (std::ostream &out, int level=0) const
Protected Attributes
PointT * fPoint
bool fValid
Protected Attributes inherited from G4KDNode_Base
size_t fAxis
int fSide
G4KDTree * fTree
G4KDNode_Base * fLeft
G4KDNode_Base * fRight
G4KDNode_Base * fParent
Private Member Functions
G4KDNode (const G4KDNode< PointT > &right)
G4KDNode & operator= (const G4KDNode< PointT > &right)
Static Private Attributes
static G4ThreadLocal
G4Allocator< G4KDNode< PointT > > * fgAllocator = 0
Detailed Description
template<typename PointT>
class G4KDNode< PointT >
G4KDNode stores one entity in G4KDTree This class is for internal use only
Definition at line 132 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 132 of file G4KDNode.hh
Constructor & Destructor Documentation
template<typename PointT> G4KDNode< PointT >::G4KDNode (G4KDTree * , PointT * , G4KDNode_Base *)
template<typename PointT> virtual G4KDNode< PointT >::~G4KDNode () virtual
template<typename PointT> G4KDNode< PointT >::G4KDNode (const G4KDNode< PointT > & right) private
template<> G4KDNode< G4IT >::~G4KDNode ()
template<> G4KDNode< G4IT >::~G4KDNode ()
Definition at line 59 of file G4IT.cc.
View newest version in sPHENIX GitHub at line 59 of file G4IT.cc
template<> G4KDNode< G4Molecule >::~G4KDNode ()
template<> G4KDNode< G4Molecule >::~G4KDNode ()
Definition at line 70 of file G4Molecule.cc.
View newest version in sPHENIX GitHub at line 70 of file G4Molecule.cc
Member Function Documentation
template<typename PointT> PointT* G4KDNode< PointT >::GetPoint () inline
Definition at line 144 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 144 of file G4KDNode.hh
References G4KDNode< PointT >::fPoint.
Referenced by G4KDTreeResult::GetItem().
template<typename PointT> virtual void G4KDNode< PointT >::InactiveNode () inline virtual
Reimplemented from G4KDNode_Base.
Definition at line 155 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 155 of file G4KDNode.hh
References G4KDNode< PointT >::fValid, and G4KDNode_Base::InactiveNode().
template<typename PointT> virtual bool G4KDNode< PointT >::IsValid (void) const inline virtual
Reimplemented from G4KDNode_Base.
Definition at line 161 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 161 of file G4KDNode.hh
References G4KDNode< PointT >::fValid.
template<typename PointT > void G4KDNode< PointT >::operator delete (void * aNode)
Definition at line 189 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 189 of file G4KDNode.hh
template<typename PointT > void * G4KDNode< PointT >::operator new (size_t)
Definition at line 182 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 182 of file G4KDNode.hh
References G4Allocator< Type >::MallocSingle().
template<typename PointT> G4KDNode& G4KDNode< PointT >::operator= (const G4KDNode< PointT > & right) private
template<typename PointT> virtual double G4KDNode< PointT >::operator[] (size_t i) const inline virtual
Implements G4KDNode_Base.
Definition at line 149 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 149 of file G4KDNode.hh
References G4KDNode< PointT >::fPoint.
Member Data Documentation
template<typename PointT> G4ThreadLocal G4Allocator< G4KDNode< PointT > > * G4KDNode< PointT >::fgAllocator = 0 static private
Definition at line 174 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 174 of file G4KDNode.hh
template<typename PointT> PointT* G4KDNode< PointT >::fPoint protected
Definition at line 167 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 167 of file G4KDNode.hh
Referenced by G4KDNode< PointT >::GetPoint(), and G4KDNode< PointT >::operator[]().
template<typename PointT> bool G4KDNode< PointT >::fValid protected
Definition at line 168 of file G4KDNode.hh.
View newest version in sPHENIX GitHub at line 168 of file G4KDNode.hh
Referenced by G4KDNode< PointT >::InactiveNode(), and G4KDNode< PointT >::IsValid().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4KDNode.hh