ECCE @ EIC Software: G4Cache< VALTYPE > Class Template Reference
G4Cache< VALTYPE > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4Cache.hh>
Public Types
typedef VALTYPE value_type
Public Member Functions
G4Cache ()
G4Cache (const value_type &v)
virtual ~G4Cache ()
value_type & Get () const
void Put (const value_type &val) const
value_type Pop ()
G4Cache (const G4Cache &rhs)
G4Cache & operator= (const G4Cache &rhs)
Protected Member Functions
const G4int & GetId () const
Private Member Functions
value_type & GetCache () const
Private Attributes
G4int id
G4CacheReference< value_type > theCache
Static Private Attributes
static std::atomic< unsigned int > instancesctr
static std::atomic< unsigned int > dstrctr
Detailed Description
template<class VALTYPE>
class G4Cache< VALTYPE >
Definition at line 91 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 91 of file G4Cache.hh
Member Typedef Documentation
template<class VALTYPE> typedef VALTYPE G4Cache< VALTYPE >::value_type
Definition at line 95 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 95 of file G4Cache.hh
Constructor & Destructor Documentation
template<class V > G4Cache< V >::G4Cache ()
Definition at line 221 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 221 of file G4Cache.hh
References G4TypeMutex().
template<class VALTYPE> G4Cache< VALTYPE >::G4Cache (const value_type & v)
template<class V > G4Cache< V >::~G4Cache () virtual
Definition at line 279 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 279 of file G4Cache.hh
References e, G4cout, G4endl, G4TypeMutex(), and G4TemplateAutoLock< _Mutex_t >::lock().
template<class VALTYPE> G4Cache< VALTYPE >::G4Cache (const G4Cache< VALTYPE > & rhs)
Member Function Documentation
template<class V > V & G4Cache< V >::Get () const inline
Definition at line 325 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 325 of file G4Cache.hh
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPD2AInelasticFS::ApplyYourself(), G4ParticleHPT2AInelasticFS::ApplyYourself(), G4ParticleHP2N2AInelasticFS::ApplyYourself(), G4ParticleHP2NInelasticFS::ApplyYourself(), G4ParticleHP2NPInelasticFS::ApplyYourself(), G4ParticleHP2PInelasticFS::ApplyYourself(), G4ParticleHP3AInelasticFS::ApplyYourself(), G4ParticleHP2NAInelasticFS::ApplyYourself(), G4ParticleHP2NDInelasticFS::ApplyYourself(), G4ParticleHPDAInelasticFS::ApplyYourself(), G4ParticleHPDInelasticFS::ApplyYourself(), G4ParticleHPN2AInelasticFS::ApplyYourself(), G4ParticleHPN2PInelasticFS::ApplyYourself(), G4ParticleHPN3AInelasticFS::ApplyYourself(), G4ParticleHPNAInelasticFS::ApplyYourself(), G4ParticleHPND2AInelasticFS::ApplyYourself(), G4ParticleHPNDInelasticFS::ApplyYourself(), G4ParticleHPNHe3InelasticFS::ApplyYourself(), G4ParticleHPNInelasticFS::ApplyYourself(), G4ParticleHPHe3InelasticFS::ApplyYourself(), G4ParticleHPNPInelasticFS::ApplyYourself(), G4ParticleHPNT2AInelasticFS::ApplyYourself(), G4ParticleHPNTInelasticFS::ApplyYourself(), G4ParticleHPNXInelasticFS::ApplyYourself(), G4ParticleHPPAInelasticFS::ApplyYourself(), G4ParticleHPPDInelasticFS::ApplyYourself(), G4ParticleHPNPAInelasticFS::ApplyYourself(), G4ParticleHPPTInelasticFS::ApplyYourself(), G4ParticleHPPInelasticFS::ApplyYourself(), G4ParticleHPTInelasticFS::ApplyYourself(), G4ParticleHP2AInelasticFS::ApplyYourself(), G4ParticleHP3NAInelasticFS::ApplyYourself(), G4ParticleHP3NPInelasticFS::ApplyYourself(), G4ParticleHP4NInelasticFS::ApplyYourself(), G4ParticleHPAInelasticFS::ApplyYourself(), G4ParticleHP3NInelasticFS::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPFSFissionFS::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4VectorCache< VALTYPE >::Begin(), G4MapCache< KEYTYPE, VALTYPE >::Begin(), G4BiasingProcessInterface::BuildPhysicsTable(), G4BiasingProcessInterface::BuildWorkerPhysicsTable(), G4SPSEneDistribution::CalculateBbodySpectrum(), G4SPSEneDistribution::CalculateCdgSpectrum(), G4SPSEneDistribution::CalculateCPowSpectrum(), G4VectorCache< VALTYPE >::Clear(), G4ParticleHPContAngularPar::ClearHistories(), G4ParticleHPInelasticCompFS::CompositeApply(), DetectorConstruction::ConstructSDandField(), ElectronBenchmarkDetector::ConstructSDandField(), LXeDetectorConstruction::ConstructSDandField(), F04DetectorConstruction::ConstructSDandField(), PurgMagDetectorConstruction::ConstructSDandField(), WLSDetectorConstruction::ConstructSDandField(), XrayFluoPlaneDetectorConstruction::ConstructSDandField(), DMXDetectorConstruction::ConstructSDandField(), XrayFluoMercuryDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), XrayFluoDetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), G4SPSEneDistribution::ConvertEPNToEnergy(), G4VectorCache< VALTYPE >::End(), G4MapCache< KEYTYPE, VALTYPE >::End(), G4BiasingProcessInterface::EndTracking(), G4SPSEneDistribution::EpnEnergyHisto(), G4MapCache< KEYTYPE, VALTYPE >::Erase(), G4SPSEneDistribution::ExpInterpolation(), G4MapCache< KEYTYPE, VALTYPE >::Find(), G4ParticleHPContAngularPar::G4ParticleHPContAngularPar(), G4ParticleHPEnAngCorrelation::G4ParticleHPEnAngCorrelation(), G4SPSEneDistribution::G4SPSEneDistribution(), G4VBiasingOperator::G4VBiasingOperator(), G4VectorCache< VALTYPE >::G4VectorCache(), G4SPSEneDistribution::GenArbPointEnergies(), G4SPSEneDistribution::GenEpnHistEnergies(), G4SPSEneDistribution::GenerateBbodyEnergies(), G4SPSEneDistribution::GenerateBiasPowEnergies(), G4SPSEneDistribution::GenerateBremEnergies(), G4SPSEneDistribution::GenerateCdgEnergies(), G4SPSEneDistribution::GenerateCPowEnergies(), G4SPSEneDistribution::GenerateExpEnergies(), G4SPSEneDistribution::GenerateGaussEnergies(), G4SPSEneDistribution::GenerateLinearEnergies(), G4SPSEneDistribution::GenerateMonoEnergetic(), G4SPSPosDistribution::GenerateOne(), G4SPSEneDistribution::GenerateOne(), G4SPSPosDistribution::GeneratePointsInPlane(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), G4SPSEneDistribution::GeneratePowEnergies(), G4SingleParticleSource::GeneratePrimaryVertex(), G4SPSRandomGenerator::GenRandEnergy(), G4SPSRandomGenerator::GenRandPhi(), G4SPSRandomGenerator::GenRandPosPhi(), G4SPSRandomGenerator::GenRandPosTheta(), G4SPSRandomGenerator::GenRandTheta(), G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), G4SPSRandomGenerator::GenRandZ(), G4SPSEneDistribution::GenUserHistEnergies(), G4SPSEneDistribution::Getalpha(), G4BiasingOperationManager::GetBiasingOperations(), G4VBiasingOperator::GetBiasingOperators(), G4SPSRandomGenerator::GetBiasWeight(), G4SPSEneDistribution::Getcept(), G4VParticleHPEnergyAngular::GetCMS(), G4SPSEneDistribution::GetEmax(), G4SPSEneDistribution::GetEmin(), G4SPSEneDistribution::GetEzero(), G4SPSEneDistribution::Getgrad(), DetectorConstruction::GetMonopoleFieldSetup(), G4ParticleHPProduct::GetMultiplicity(), G4SingleParticleSource::GetParticleEnergy(), G4SingleParticleSource::GetParticleMomentumDirection(), G4SPSPosDistribution::GetParticlePos(), G4SingleParticleSource::GetParticlePosition(), G4ParticleHPFSFissionFS::GetPhotons(), G4ParticleHPPhotonDist::GetPhotons(), G4SPSEneDistribution::GetProbability(), G4VParticleHPEnergyAngular::GetProjectileRP(), G4ParticleHPProduct::GetProjectileRP(), G4SPSPosDistribution::GetSideRefVec1(), G4SPSPosDistribution::GetSideRefVec2(), G4SPSPosDistribution::GetSideRefVec3(), G4VParticleHPEnergyAngular::GetTarget(), G4ParticleHPProduct::GetTarget(), G4ParticleHPEnAngCorrelation::GetTotalMeanEnergy(), G4SPSEneDistribution::GetWeight(), G4MapCache< KEYTYPE, VALTYPE >::Insert(), G4ThreadLocalSingleton< T >::Instance(), G4SPSEneDistribution::LinearInterpolation(), G4SPSEneDistribution::LogInterpolation(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4ParticleHPContEnergyAngular::MeanEnergyOfThisInteraction(), G4ParticleHPContAngularPar::MeanEnergyOfThisInteraction(), G4ParticleHPProduct::MeanEnergyOfThisInteraction(), G4PhaseSpaceDecayChannel::OneBodyDecayIt(), G4VectorCache< VALTYPE >::operator[](), G4VectorCache< VALTYPE >::Pop_back(), G4VectorCache< VALTYPE >::Push_back(), G4SPSRandomGenerator::ReSetHist(), G4ParticleHPContEnergyAngular::Sample(), G4ParticleHPContAngularPar::Sample(), G4ParticleHPEnAngCorrelation::Sample(), G4ParticleHPProduct::Sample(), G4ParticleHPAngular::SampleAndUpdate(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4SPSEneDistribution::SetAlpha(), G4SPSEneDistribution::SetEmax(), G4SPSEneDistribution::SetEmin(), G4SPSEneDistribution::SetEzero(), G4SPSEneDistribution::SetGradient(), G4SPSRandomGenerator::SetIntensityWeight(), G4SPSEneDistribution::SetInterCept(), G4ParticleHPFissionBaseFS::SetNeutronRP(), G4ParticleHPFSFissionFS::SetNeutronRP(), G4ParticleHPContAngularPar::SetPrimary(), G4VParticleHPEnergyAngular::SetProjectileRP(), G4ParticleHPAngular::SetProjectileRP(), G4ParticleHPEnAngCorrelation::SetProjectileRP(), G4ParticleHPProduct::SetProjectileRP(), G4VParticleHPEnergyAngular::SetTarget(), G4ParticleHPAngular::SetTarget(), G4ParticleHPFissionBaseFS::SetTarget(), G4ParticleHPFSFissionFS::SetTarget(), G4ParticleHPContAngularPar::SetTarget(), G4ParticleHPEnAngCorrelation::SetTarget(), G4ParticleHPProduct::SetTarget(), G4ParticleHPContAngularPar::SetTargetCode(), G4VectorCache< G4VCrossSectionDataSet * >::Size(), G4MapCache< const G4ProcessManager *, G4BiasingProcessSharedData * >::Size(), G4SPSEneDistribution::SplineInterpolation(), G4BiasingProcessInterface::StartTracking(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4PhaseSpaceDecayChannel::TwoBodyDecayIt(), G4ParticleHPInelasticCompFS::use_nresp71_model(), G4SPSEneDistribution::UserEnergyHisto(), G4ParticleHPContAngularPar::~G4ParticleHPContAngularPar(), G4ParticleHPContEnergyAngular::~G4ParticleHPContEnergyAngular(), G4ParticleHPFinalState::~G4ParticleHPFinalState(), and G4ParticleHPPhotonDist::~G4ParticleHPPhotonDist().
template<class VALTYPE> value_type& G4Cache< VALTYPE >::GetCache () const inline private
Definition at line 130 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 130 of file G4Cache.hh
Referenced by G4Cache< VALTYPE >::operator=().
template<class VALTYPE> const G4int& G4Cache< VALTYPE >::GetId () const inline protected
Definition at line 121 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 121 of file G4Cache.hh
Referenced by G4MapCache< KEYTYPE, VALTYPE >::~G4MapCache().
template<class VALTYPE> G4Cache< V > & G4Cache< V >::operator= (const G4Cache< VALTYPE > & rhs)
Definition at line 251 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 251 of file G4Cache.hh
References G4Cache< VALTYPE >::GetCache().
template<class V > V G4Cache< V >::Pop () inline
Definition at line 334 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 334 of file G4Cache.hh
template<class VALTYPE> void G4Cache< V >::Put (const value_type & val) const inline
Definition at line 329 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 329 of file G4Cache.hh
Referenced by G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4FissionLibrary::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4BiasingProcessInterface::BuildPhysicsTable(), G4BiasingProcessInterface::BuildWorkerPhysicsTable(), G4ParticleHPContAngularPar::cacheInit(), G4ParticleHPInelasticCompFS::CompositeApply(), DetectorConstruction::ConstructSDandField(), LXeDetectorConstruction::ConstructSDandField(), F04DetectorConstruction::ConstructSDandField(), PurgMagDetectorConstruction::ConstructSDandField(), WLSDetectorConstruction::ConstructSDandField(), XrayFluoPlaneDetectorConstruction::ConstructSDandField(), DMXDetectorConstruction::ConstructSDandField(), XrayFluoMercuryDetectorConstruction::ConstructSDandField(), F03DetectorConstruction::ConstructSDandField(), F01DetectorConstruction::ConstructSDandField(), F02DetectorConstruction::ConstructSDandField(), XrayFluoDetectorConstruction::ConstructSDandField(), GammaRayTelDetectorConstruction::ConstructSDandField(), G4PhaseSpaceDecayChannel::DecayIt(), DMXDetectorConstruction::DMXDetectorConstruction(), G4BiasingProcessInterface::EndTracking(), G4BiasingProcessInterface::G4BiasingProcessInterface(), G4ParticleHPAngular::G4ParticleHPAngular(), G4ParticleHPContAngularPar::G4ParticleHPContAngularPar(), G4ParticleHPContEnergyAngular::G4ParticleHPContEnergyAngular(), G4ParticleHPEnAngCorrelation::G4ParticleHPEnAngCorrelation(), G4ParticleHPFinalState::G4ParticleHPFinalState(), G4ParticleHPPhotonDist::G4ParticleHPPhotonDist(), G4ParticleHPProduct::G4ParticleHPProduct(), G4PenelopeBremsstrahlungFS::G4PenelopeBremsstrahlungFS(), G4ThreadLocalSingleton< T >::G4ThreadLocalSingleton(), G4VBiasingOperator::G4VBiasingOperator(), G4VParticleHPEnergyAngular::G4VParticleHPEnergyAngular(), GammaRayTelDetectorConstruction::GammaRayTelDetectorConstruction(), G4ThreadLocalSingleton< T >::Instance(), G4ParticleHPContEnergyAngular::MeanEnergyOfThisInteraction(), PurgMagDetectorConstruction::PurgMagDetectorConstruction(), G4ParticleHPContEnergyAngular::Sample(), G4PenelopeBremsstrahlungFS::SampleGammaEnergy(), G4BiasingProcessInterface::StartTracking(), and XrayFluoDetectorConstruction::XrayFluoDetectorConstruction().
Member Data Documentation
template<class VALTYPE> std::atomic< unsigned int > G4Cache< V >::dstrctr static private
Definition at line 128 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 128 of file G4Cache.hh
template<class VALTYPE> G4int G4Cache< VALTYPE >::id private
Definition at line 125 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 125 of file G4Cache.hh
Referenced by G4Cache< F02ElectricFieldSetup * >::GetId().
template<class VALTYPE> std::atomic< unsigned int > G4Cache< V >::instancesctr static private
Definition at line 127 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 127 of file G4Cache.hh
template<class VALTYPE> G4CacheReference<value_type> G4Cache< VALTYPE >::theCache mutable private
Definition at line 126 of file G4Cache.hh.
View newest version in sPHENIX GitHub at line 126 of file G4Cache.hh
Referenced by G4Cache< F02ElectricFieldSetup * >::GetCache().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/management/include/G4Cache.hh