ECCE @ EIC Software: G4CascadeCheckBalance Class Reference
G4CascadeCheckBalance Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeCheckBalance.hh>
Public Member Functions
G4CascadeCheckBalance (const G4String &owner="G4CascadeCheckBalance")
G4CascadeCheckBalance (G4double relative, G4double absolute, const G4String &owner="G4CascadeCheckBalance")
virtual ~G4CascadeCheckBalance ()
void setOwner (const G4String &owner)
void setLimits (G4double relative, G4double absolute)
void setRelativeLimit (G4double limit)
void setAbsoluteLimit (G4double limit)
void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output)
void collide (const G4Fragment &fragment, G4CollisionOutput &output)
void collide (G4InuclParticle *bullet, G4InuclParticle *target, const std::vector< G4InuclElementaryParticle > &particles)
void collide (G4InuclParticle *bullet, G4InuclParticle *target, const std::vector< G4CascadParticle > &particles)
void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &output, const std::vector< G4CascadParticle > &cparticles)
void collide (const G4Fragment &target, const std::vector< G4InuclElementaryParticle > &particles)
void collide (const G4Fragment &target, const std::vector< G4InuclNuclei > &fragments)
G4bool energyOkay () const
G4bool ekinOkay () const
G4bool momentumOkay () const
G4bool baryonOkay () const
G4bool chargeOkay () const
G4bool strangeOkay () const
G4bool okay () const
G4double deltaE () const
G4double relativeE () const
G4double deltaKE () const
G4double relativeKE () const
G4double deltaP () const
G4double relativeP () const
G4LorentzVector deltaLV () const
G4int deltaB () const
G4int deltaQ () const
G4int deltaS () const
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
virtual void setVerboseLevel (G4int verbose=0)
Static Public Attributes
static const G4double tolerance = 1e-6
Protected Member Functions
G4double ekin (const G4LorentzVector &p) const
Protected Member Functions inherited from G4VCascadeCollider
virtual void setName (const G4String &name)
Private Member Functions
G4CascadeCheckBalance (const G4CascadeCheckBalance &)
G4CascadeCheckBalance & operator= (const G4CascadeCheckBalance &)
Private Attributes
G4double relativeLimit
G4double absoluteLimit
G4LorentzVector initial
G4LorentzVector final
G4int initialBaryon
G4int finalBaryon
G4int initialCharge
G4int finalCharge
G4int initialStrange
G4int finalStrange
G4CollisionOutput tempOutput
Additional Inherited Members
Protected Attributes inherited from G4VCascadeCollider
G4String theName
G4int verboseLevel
Detailed Description
Definition at line 64 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 64 of file G4CascadeCheckBalance.hh
Constructor & Destructor Documentation
G4CascadeCheckBalance::G4CascadeCheckBalance (const G4String & owner = "G4CascadeCheckBalance") explicit
Definition at line 71 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 71 of file G4CascadeCheckBalance.cc
G4CascadeCheckBalance::G4CascadeCheckBalance (G4double relative, G4double absolute, const G4String & owner = "G4CascadeCheckBalance")
Definition at line 77 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 77 of file G4CascadeCheckBalance.cc
virtual G4CascadeCheckBalance::~G4CascadeCheckBalance () inline virtual
Definition at line 72 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 72 of file G4CascadeCheckBalance.hh
G4CascadeCheckBalance::G4CascadeCheckBalance (const G4CascadeCheckBalance &) private
Member Function Documentation
G4bool G4CascadeCheckBalance::baryonOkay () const
Definition at line 330 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 330 of file G4CascadeCheckBalance.cc
References deltaB(), G4cerr, G4endl, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::checkFinalResult(), okay(), and G4CascadeInterface::throwNonConservationFailure().
G4bool G4CascadeCheckBalance::chargeOkay () const
Definition at line 338 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 338 of file G4CascadeCheckBalance.cc
References deltaQ(), G4cerr, G4endl, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::checkFinalResult(), okay(), and G4CascadeInterface::throwNonConservationFailure().
void G4CascadeCheckBalance::collide (G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & output) virtual
Implements G4VCascadeCollider.
Definition at line 88 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 88 of file G4CascadeCheckBalance.cc
References G4InuclElementaryParticle::baryon(), CLHEP::HepLorentzVector::e(), G4Electron::Electron(), finalBaryon, finalCharge, finalStrange, G4cout, G4endl, G4InuclNuclei::getA(), G4InuclParticle::getCharge(), G4InuclParticle::getMomentum(), G4CollisionOutput::getOutgoingParticles(), G4InuclElementaryParticle::getStrangeness(), G4CollisionOutput::getTotalBaryonNumber(), G4CollisionOutput::getTotalCharge(), G4CollisionOutput::getTotalOutputMomentum(), G4CollisionOutput::getTotalStrangeness(), GeV, initial, initialBaryon, initialCharge, initialStrange, G4CollisionOutput::numberOfOutgoingParticles(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Referenced by G4CascadeInterface::ApplyYourself(), G4CascadeInterface::checkFinalResult(), G4CascadeRecoilMaker::collide(), collide(), G4NucleiModel::generateParticleFate(), G4CascadeInterface::Propagate(), G4CascadeDeexciteBase::validateOutput(), and G4CascadeColliderBase::validateOutput().
void G4CascadeCheckBalance::collide (const G4Fragment & fragment, G4CollisionOutput & output)
Definition at line 156 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 156 of file G4CascadeCheckBalance.cc
References CLHEP::HepLorentzVector::e(), G4Electron::Electron(), finalBaryon, finalCharge, finalStrange, G4cout, G4endl, G4Fragment::GetA_asInt(), G4Fragment::GetMomentum(), G4CollisionOutput::getOutgoingParticles(), G4CollisionOutput::getTotalBaryonNumber(), G4CollisionOutput::getTotalCharge(), G4CollisionOutput::getTotalOutputMomentum(), G4CollisionOutput::getTotalStrangeness(), G4Fragment::GetZ_asInt(), GeV, initial, initialBaryon, initialCharge, initialStrange, G4CollisionOutput::numberOfOutgoingParticles(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
void G4CascadeCheckBalance::collide (G4InuclParticle * bullet, G4InuclParticle * target, const std::vector< G4InuclElementaryParticle > & particles)
Definition at line 207 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 207 of file G4CascadeCheckBalance.cc
References G4CollisionOutput::addOutgoingParticles(), collide(), G4cout, G4endl, G4CollisionOutput::reset(), tempOutput, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
void G4CascadeCheckBalance::collide (G4InuclParticle * bullet, G4InuclParticle * target, const std::vector< G4CascadParticle > & particles)
Definition at line 245 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 245 of file G4CascadeCheckBalance.cc
References G4CollisionOutput::addOutgoingParticles(), collide(), G4cout, G4endl, G4CollisionOutput::reset(), tempOutput, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
void G4CascadeCheckBalance::collide (G4InuclParticle * bullet, G4InuclParticle * target, G4CollisionOutput & output, const std::vector< G4CascadParticle > & cparticles)
Definition at line 259 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 259 of file G4CascadeCheckBalance.cc
References G4CollisionOutput::add(), G4CollisionOutput::addOutgoingParticles(), collide(), G4cout, G4endl, G4CollisionOutput::reset(), tempOutput, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
void G4CascadeCheckBalance::collide (const G4Fragment & target, const std::vector< G4InuclElementaryParticle > & particles)
Definition at line 219 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 219 of file G4CascadeCheckBalance.cc
References G4CollisionOutput::addOutgoingParticles(), collide(), G4cout, G4endl, G4CollisionOutput::reset(), tempOutput, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
void G4CascadeCheckBalance::collide (const G4Fragment & target, const std::vector< G4InuclNuclei > & fragments)
Definition at line 232 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 232 of file G4CascadeCheckBalance.cc
References G4CollisionOutput::addOutgoingNuclei(), collide(), G4cout, G4endl, G4CollisionOutput::reset(), tempOutput, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
G4int G4CascadeCheckBalance::deltaB () const inline
Definition at line 147 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 147 of file G4CascadeCheckBalance.hh
References finalBaryon, and initialBaryon.
Referenced by baryonOkay(), G4CascadeInterface::checkFinalResult(), G4CascadeRecoilMaker::fillRecoil(), and G4CascadeInterface::throwNonConservationFailure().
G4double G4CascadeCheckBalance::deltaE () const inline
Definition at line 126 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 126 of file G4CascadeCheckBalance.hh
References e, CLHEP::HepLorentzVector::e(), and initial.
Referenced by G4CascadeInterface::checkFinalResult(), energyOkay(), relativeE(), and G4CascadeInterface::throwNonConservationFailure().
G4double G4CascadeCheckBalance::deltaKE () const inline
Definition at line 132 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 132 of file G4CascadeCheckBalance.hh
References ekin(), and initial.
Referenced by G4CascadeInterface::checkFinalResult(), ekinOkay(), and relativeKE().
G4LorentzVector G4CascadeCheckBalance::deltaLV () const inline
Definition at line 144 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 144 of file G4CascadeCheckBalance.hh
References initial.
Referenced by deltaP(), and G4CascadeRecoilMaker::fillRecoil().
G4double G4CascadeCheckBalance::deltaP () const inline
Definition at line 138 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 138 of file G4CascadeCheckBalance.hh
References deltaLV(), and CLHEP::HepLorentzVector::rho().
Referenced by momentumOkay(), relativeP(), and G4CascadeInterface::throwNonConservationFailure().
G4int G4CascadeCheckBalance::deltaQ () const inline
Definition at line 148 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 148 of file G4CascadeCheckBalance.hh
References finalCharge, and initialCharge.
Referenced by chargeOkay(), G4CascadeInterface::checkFinalResult(), G4CascadeRecoilMaker::fillRecoil(), and G4CascadeInterface::throwNonConservationFailure().
G4int G4CascadeCheckBalance::deltaS () const inline
Definition at line 149 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 149 of file G4CascadeCheckBalance.hh
References finalStrange, and initialStrange.
Referenced by strangeOkay().
G4double G4CascadeCheckBalance::ekin (const G4LorentzVector & p) const inline protected
Definition at line 153 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 153 of file G4CascadeCheckBalance.hh
References CLHEP::HepLorentzVector::e(), and CLHEP::HepLorentzVector::m().
Referenced by deltaKE(), and relativeKE().
G4bool G4CascadeCheckBalance::ekinOkay () const
Definition at line 293 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 293 of file G4CascadeCheckBalance.cc
References kdfinder::abs(), absoluteLimit, deltaKE(), G4cerr, G4cout, G4endl, relativeKE(), relativeLimit, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
G4bool G4CascadeCheckBalance::energyOkay () const
Definition at line 275 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 275 of file G4CascadeCheckBalance.cc
References kdfinder::abs(), absoluteLimit, deltaE(), G4cerr, G4cout, G4endl, relativeE(), relativeLimit, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Referenced by okay(), and G4CascadeInterface::throwNonConservationFailure().
G4bool G4CascadeCheckBalance::momentumOkay () const
Definition at line 312 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 312 of file G4CascadeCheckBalance.cc
References kdfinder::abs(), absoluteLimit, deltaP(), G4cerr, G4cout, G4endl, relativeLimit, relativeP(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Referenced by okay(), and G4CascadeInterface::throwNonConservationFailure().
G4bool G4CascadeCheckBalance::okay () const inline
Definition at line 121 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 121 of file G4CascadeCheckBalance.hh
References baryonOkay(), chargeOkay(), energyOkay(), and momentumOkay().
Referenced by G4CascadeInterface::ApplyYourself(), G4NucleiModel::generateParticleFate(), G4CascadeInterface::Propagate(), G4CascadeInterface::retryInelasticNucleus(), G4CascadeDeexciteBase::validateOutput(), and G4CascadeColliderBase::validateOutput().
G4CascadeCheckBalance& G4CascadeCheckBalance::operator= (const G4CascadeCheckBalance &) private
G4double G4CascadeCheckBalance::relativeE () const inline
Definition at line 127 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 127 of file G4CascadeCheckBalance.hh
References kdfinder::abs(), deltaE(), CLHEP::HepLorentzVector::e(), initial, and tolerance.
Referenced by energyOkay(), and G4CascadeInterface::throwNonConservationFailure().
G4double G4CascadeCheckBalance::relativeKE () const inline
Definition at line 133 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 133 of file G4CascadeCheckBalance.hh
References kdfinder::abs(), deltaKE(), ekin(), initial, and tolerance.
Referenced by ekinOkay().
G4double G4CascadeCheckBalance::relativeP () const inline
Definition at line 139 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 139 of file G4CascadeCheckBalance.hh
References kdfinder::abs(), deltaP(), initial, CLHEP::HepLorentzVector::rho(), and tolerance.
Referenced by momentumOkay(), and G4CascadeInterface::throwNonConservationFailure().
void G4CascadeCheckBalance::setAbsoluteLimit (G4double limit) inline
Definition at line 82 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 82 of file G4CascadeCheckBalance.hh
References absoluteLimit.
Referenced by setLimits().
void G4CascadeCheckBalance::setLimits (G4double relative, G4double absolute) inline
Definition at line 76 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CascadeCheckBalance.hh
References setAbsoluteLimit(), and setRelativeLimit().
Referenced by G4CascadeInterface::G4CascadeInterface().
void G4CascadeCheckBalance::setOwner (const G4String & owner) inline
Definition at line 74 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 74 of file G4CascadeCheckBalance.hh
References G4VCascadeCollider::setName().
void G4CascadeCheckBalance::setRelativeLimit (G4double limit) inline
Definition at line 81 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 81 of file G4CascadeCheckBalance.hh
References relativeLimit.
Referenced by setLimits().
G4bool G4CascadeCheckBalance::strangeOkay () const
Definition at line 347 of file G4CascadeCheckBalance.cc.
View newest version in sPHENIX GitHub at line 347 of file G4CascadeCheckBalance.cc
References deltaS(), G4cerr, G4endl, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Member Data Documentation
G4double G4CascadeCheckBalance::absoluteLimit private
Definition at line 157 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 157 of file G4CascadeCheckBalance.hh
Referenced by ekinOkay(), energyOkay(), momentumOkay(), and setAbsoluteLimit().
G4LorentzVector G4CascadeCheckBalance::final private
Definition at line 160 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 160 of file G4CascadeCheckBalance.hh
G4int G4CascadeCheckBalance::finalBaryon private
Definition at line 163 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 163 of file G4CascadeCheckBalance.hh
Referenced by collide(), and deltaB().
G4int G4CascadeCheckBalance::finalCharge private
Definition at line 166 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 166 of file G4CascadeCheckBalance.hh
Referenced by collide(), and deltaQ().
G4int G4CascadeCheckBalance::finalStrange private
Definition at line 169 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 169 of file G4CascadeCheckBalance.hh
Referenced by collide(), and deltaS().
G4LorentzVector G4CascadeCheckBalance::initial private
Definition at line 159 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 159 of file G4CascadeCheckBalance.hh
Referenced by collide(), deltaE(), deltaKE(), deltaLV(), relativeE(), relativeKE(), and relativeP().
G4int G4CascadeCheckBalance::initialBaryon private
Definition at line 162 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 162 of file G4CascadeCheckBalance.hh
Referenced by collide(), and deltaB().
G4int G4CascadeCheckBalance::initialCharge private
Definition at line 165 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 165 of file G4CascadeCheckBalance.hh
Referenced by collide(), and deltaQ().
G4int G4CascadeCheckBalance::initialStrange private
Definition at line 168 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 168 of file G4CascadeCheckBalance.hh
Referenced by collide(), and deltaS().
G4double G4CascadeCheckBalance::relativeLimit private
Definition at line 156 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 156 of file G4CascadeCheckBalance.hh
Referenced by ekinOkay(), energyOkay(), momentumOkay(), and setRelativeLimit().
G4CollisionOutput G4CascadeCheckBalance::tempOutput private
Definition at line 171 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 171 of file G4CascadeCheckBalance.hh
Referenced by collide().
const G4double G4CascadeCheckBalance::tolerance = 1e-6 static
Definition at line 66 of file G4CascadeCheckBalance.hh.
View newest version in sPHENIX GitHub at line 66 of file G4CascadeCheckBalance.hh
Referenced by relativeE(), relativeKE(), and relativeP().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeCheckBalance.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeCheckBalance.cc