ECCE @ EIC Software: G4LivermoreComptonModifiedModel Class Reference
G4LivermoreComptonModifiedModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermoreComptonModifiedModel.hh>
Public Member Functions
G4LivermoreComptonModifiedModel (const G4ParticleDefinition *p=0, const G4String &nam="LivermoreModifiedCompton")
virtual ~G4LivermoreComptonModifiedModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0, G4double cut=0, G4double emax=DBL_MAX)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChange
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Member Functions
G4LivermoreComptonModifiedModel & operator= (const G4LivermoreComptonModifiedModel &right)
G4LivermoreComptonModifiedModel (const G4LivermoreComptonModifiedModel &)
Private Attributes
G4bool isInitialised
G4int verboseLevel
G4VEMDataSet * scatterFunctionData
G4VCrossSectionHandler * crossSectionHandler
G4VAtomDeexcitation * fAtomDeexcitation
G4ShellData shellData
G4DopplerProfile profileData
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 47 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4LivermoreComptonModifiedModel.hh
Constructor & Destructor Documentation
G4LivermoreComptonModifiedModel::G4LivermoreComptonModifiedModel (const G4ParticleDefinition * p = 0, const G4String & nam = "LivermoreModifiedCompton")
Definition at line 63 of file G4LivermoreComptonModifiedModel.cc.
View newest version in sPHENIX GitHub at line 63 of file G4LivermoreComptonModifiedModel.cc
References G4cout, G4endl, G4VEmModel::SetDeexcitationFlag(), and verboseLevel.
G4LivermoreComptonModifiedModel::~G4LivermoreComptonModifiedModel () virtual
Definition at line 87 of file G4LivermoreComptonModifiedModel.cc.
View newest version in sPHENIX GitHub at line 87 of file G4LivermoreComptonModifiedModel.cc
References crossSectionHandler, and scatterFunctionData.
G4LivermoreComptonModifiedModel::G4LivermoreComptonModifiedModel (const G4LivermoreComptonModifiedModel &) private
Member Function Documentation
G4double G4LivermoreComptonModifiedModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kinEnergy, G4double Z, G4double A = 0, G4double cut = 0, G4double emax = DBL_MAX) virtual
Reimplemented from G4VEmModel.
Definition at line 148 of file G4LivermoreComptonModifiedModel.cc.
View newest version in sPHENIX GitHub at line 148 of file G4LivermoreComptonModifiedModel.cc
References crossSectionHandler, G4VCrossSectionHandler::FindValue(), G4cout, G4endl, G4VEmModel::LowEnergyLimit(), and verboseLevel.
void G4LivermoreComptonModifiedModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector & cuts) virtual
Implements G4VEmModel.
Definition at line 95 of file G4LivermoreComptonModifiedModel.cc.
View newest version in sPHENIX GitHub at line 95 of file G4LivermoreComptonModifiedModel.cc
References G4LossTableManager::AtomDeexcitation(), G4VCrossSectionHandler::Clear(), crossSectionHandler, eV, fAtomDeexcitation, file, fParticleChange, G4cout, G4endl, G4VEmModel::GetParticleChangeForGamma(), GeV, G4VEmModel::HighEnergyLimit(), G4VEmModel::InitialiseElementSelectors(), G4LossTableManager::Instance(), isInitialised, G4ShellData::LoadData(), G4VEMDataSet::LoadData(), G4VCrossSectionHandler::LoadData(), G4VEmModel::LowEnergyLimit(), scatterFunctionData, G4ShellData::SetOccupancyData(), shellData, and verboseLevel.
G4LivermoreComptonModifiedModel& G4LivermoreComptonModifiedModel::operator= (const G4LivermoreComptonModifiedModel & right) private
void G4LivermoreComptonModifiedModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicGamma, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 166 of file G4LivermoreComptonModifiedModel.cc.
View newest version in sPHENIX GitHub at line 166 of file G4LivermoreComptonModifiedModel.cc
References Alpha, G4ShellData::BindingEnergy(), source.hepunit::c_light, G4VAtomDeexcitation::CheckDeexcitationActiveRegion(), cm, G4Electron::Electron(), source.hepunit::electron_mass_c2, epsilon(), fAtomDeexcitation, G4VEMDataSet::FindValue(), source.hepunit::fine_structure_const, fParticleChange, fStopAndKill, G4cout, G4endl, G4Exp(), G4UniformRand, G4VAtomDeexcitation::GenerateParticles(), G4VAtomDeexcitation::GetAtomicShell(), G4DynamicParticle::GetDefinition(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4Material::GetName(), G4Element::GetZ(), source.hepunit::h_Planck, G4VEmModel::LowEnergyLimit(), MeV, particle, phi, pi, profileData, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), G4DopplerProfile::RandomSelectMomentum(), return(), CLHEP::Hep3Vector::rotateUz(), scale, scatterFunctionData, G4VEmModel::SelectRandomAtom(), G4ShellData::SelectRandomShell(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), shellData, twopi, verboseLevel, x, and Z.
Member Data Documentation
G4VCrossSectionHandler* G4LivermoreComptonModifiedModel::crossSectionHandler private
Definition at line 81 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4LivermoreComptonModifiedModel.hh
Referenced by ComputeCrossSectionPerAtom(), Initialise(), and ~G4LivermoreComptonModifiedModel().
G4VAtomDeexcitation* G4LivermoreComptonModifiedModel::fAtomDeexcitation private
Definition at line 83 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 83 of file G4LivermoreComptonModifiedModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4ParticleChangeForGamma* G4LivermoreComptonModifiedModel::fParticleChange protected
Definition at line 74 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 74 of file G4LivermoreComptonModifiedModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4bool G4LivermoreComptonModifiedModel::isInitialised private
Definition at line 77 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4LivermoreComptonModifiedModel.hh
Referenced by Initialise().
G4DopplerProfile G4LivermoreComptonModifiedModel::profileData private
Definition at line 86 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4LivermoreComptonModifiedModel.hh
Referenced by SampleSecondaries().
G4VEMDataSet* G4LivermoreComptonModifiedModel::scatterFunctionData private
Definition at line 80 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4LivermoreComptonModifiedModel.hh
Referenced by Initialise(), SampleSecondaries(), and ~G4LivermoreComptonModifiedModel().
G4ShellData G4LivermoreComptonModifiedModel::shellData private
Definition at line 85 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 85 of file G4LivermoreComptonModifiedModel.hh
Referenced by Initialise(), and SampleSecondaries().
G4int G4LivermoreComptonModifiedModel::verboseLevel private
Definition at line 78 of file G4LivermoreComptonModifiedModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4LivermoreComptonModifiedModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4LivermoreComptonModifiedModel(), Initialise(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermoreComptonModifiedModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4LivermoreComptonModifiedModel.cc