ECCE @ EIC Software: CheckVolumeSD Class Reference
CheckVolumeSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/include/CheckVolumeSD.hh>
Public Member Functions
CheckVolumeSD (const G4String &)
virtual ~CheckVolumeSD ()
virtual void Initialize (G4HCofThisEvent *)
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void PrintAll ()
CheckVolumeSD (const G4String &)
virtual ~CheckVolumeSD ()
void Initialize (G4HCofThisEvent *)
G4bool ProcessHits (G4Step *, G4TouchableHistory *)
void EndOfEvent (G4HCofThisEvent *)
void clear ()
void PrintAll ()
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
virtual void DrawAll ()
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Member Functions
CheckVolumeSD & operator= (const CheckVolumeSD &right)
CheckVolumeSD (const CheckVolumeSD &)
Private Attributes
HistoManager * fHisto
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 56 of file CheckVolumeSD.hh.
View newest version in sPHENIX GitHub at line 56 of file CheckVolumeSD.hh
Constructor & Destructor Documentation
CheckVolumeSD::CheckVolumeSD (const G4String & name)
Definition at line 51 of file CheckVolumeSD.cc.
View newest version in sPHENIX GitHub at line 51 of file CheckVolumeSD.cc
References fHisto, and HistoManager::GetPointer().
CheckVolumeSD::~CheckVolumeSD () virtual
Definition at line 59 of file CheckVolumeSD.cc.
View newest version in sPHENIX GitHub at line 59 of file CheckVolumeSD.cc
CheckVolumeSD::CheckVolumeSD (const G4String &)
virtual CheckVolumeSD::~CheckVolumeSD () virtual
CheckVolumeSD::CheckVolumeSD (const CheckVolumeSD &) private
Member Function Documentation
void CheckVolumeSD::clear () virtual
Reimplemented from G4VSensitiveDetector.
void CheckVolumeSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 83 of file CheckVolumeSD.cc.
View newest version in sPHENIX GitHub at line 83 of file CheckVolumeSD.cc
void CheckVolumeSD::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
void CheckVolumeSD::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 78 of file CheckVolumeSD.cc.
View newest version in sPHENIX GitHub at line 78 of file CheckVolumeSD.cc
void CheckVolumeSD::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
void CheckVolumeSD::Initialize (G4HCofThisEvent *) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 64 of file CheckVolumeSD.cc.
View newest version in sPHENIX GitHub at line 64 of file CheckVolumeSD.cc
CheckVolumeSD& CheckVolumeSD::operator= (const CheckVolumeSD & right) private
void CheckVolumeSD::PrintAll () virtual
Reimplemented from G4VSensitiveDetector.
void CheckVolumeSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 88 of file CheckVolumeSD.cc.
View newest version in sPHENIX GitHub at line 88 of file CheckVolumeSD.cc
G4bool CheckVolumeSD::ProcessHits (G4Step * , G4TouchableHistory *) virtual
Implements G4VSensitiveDetector.
G4bool CheckVolumeSD::ProcessHits (G4Step * aStep, G4TouchableHistory *) virtual
Implements G4VSensitiveDetector.
Definition at line 69 of file CheckVolumeSD.cc.
View newest version in sPHENIX GitHub at line 69 of file CheckVolumeSD.cc
References HistoManager::AddLeakingParticle(), fHisto, G4Step::GetTrack(), G4Track::GetTrackID(), and track.
Member Data Documentation
HistoManager* CheckVolumeSD::fHisto private
Definition at line 71 of file CheckVolumeSD.hh.
View newest version in sPHENIX GitHub at line 71 of file CheckVolumeSD.hh
Referenced by CheckVolumeSD(), and ProcessHits().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/include/CheckVolumeSD.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/include/CheckVolumeSD.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr01/src/CheckVolumeSD.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/GammaTherapy/src/CheckVolumeSD.cc