ECCE @ EIC Software: G4MultiFunctionalDetector Class Reference
G4MultiFunctionalDetector Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4MultiFunctionalDetector.hh>
Public Member Functions
G4MultiFunctionalDetector (G4String)
G4bool RegisterPrimitive (G4VPrimitiveScorer *)
G4bool RemovePrimitive (G4VPrimitiveScorer *)
G4int GetNumberOfPrimitives () const
G4VPrimitiveScorer * GetPrimitive (G4int id) const
virtual ~G4MultiFunctionalDetector ()
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes
std::vector< G4VPrimitiveScorer * > primitives
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 47 of file G4MultiFunctionalDetector.hh.
View newest version in sPHENIX GitHub at line 47 of file G4MultiFunctionalDetector.hh
Constructor & Destructor Documentation
G4MultiFunctionalDetector::G4MultiFunctionalDetector (G4String name)
Definition at line 37 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 37 of file G4MultiFunctionalDetector.cc
G4MultiFunctionalDetector::~G4MultiFunctionalDetector () virtual
Definition at line 41 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 41 of file G4MultiFunctionalDetector.cc
References gammaraytel::pr, and primitives.
Member Function Documentation
void G4MultiFunctionalDetector::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 108 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 108 of file G4MultiFunctionalDetector.cc
References gammaraytel::pr, and primitives.
void G4MultiFunctionalDetector::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 114 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 114 of file G4MultiFunctionalDetector.cc
References gammaraytel::pr, and primitives.
void G4MultiFunctionalDetector::EndOfEvent (G4HCofThisEvent * HC) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 102 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 102 of file G4MultiFunctionalDetector.cc
References gammaraytel::pr, and primitives.
G4int G4MultiFunctionalDetector::GetNumberOfPrimitives () const inline
Definition at line 61 of file G4MultiFunctionalDetector.hh.
View newest version in sPHENIX GitHub at line 61 of file G4MultiFunctionalDetector.hh
References primitives.
Referenced by B01Run::B01Run(), B02Run::B02Run(), B03Run::B03Run(), DicomRun::ConstructMFD(), Dicom2Run::ConstructMFD(), TSRun::ConstructMFD(), G4VScoringMesh::GetPrimitiveScorer(), G4VScoringMesh::List(), ML2Run::ML2Run(), and RE02Run::RE02Run().
G4VPrimitiveScorer* G4MultiFunctionalDetector::GetPrimitive (G4int id) const inline
Definition at line 63 of file G4MultiFunctionalDetector.hh.
View newest version in sPHENIX GitHub at line 63 of file G4MultiFunctionalDetector.hh
References primitives.
Referenced by B01Run::B01Run(), B02Run::B02Run(), B03Run::B03Run(), DicomRun::ConstructMFD(), Dicom2Run::ConstructMFD(), TSRun::ConstructMFD(), G4VScoringMesh::GetPrimitiveScorer(), G4VScoringMesh::List(), ML2Run::ML2Run(), and RE02Run::RE02Run().
void G4MultiFunctionalDetector::Initialize (G4HCofThisEvent * HC) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 96 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 96 of file G4MultiFunctionalDetector.cc
References gammaraytel::pr, and primitives.
void G4MultiFunctionalDetector::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 120 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 120 of file G4MultiFunctionalDetector.cc
References gammaraytel::pr, and primitives.
G4bool G4MultiFunctionalDetector::ProcessHits (G4Step * aStep, G4TouchableHistory * aTH) protected virtual
Implements G4VSensitiveDetector.
Definition at line 47 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 47 of file G4MultiFunctionalDetector.cc
References G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), gammaraytel::pr, and primitives.
G4bool G4MultiFunctionalDetector::RegisterPrimitive (G4VPrimitiveScorer * aPS)
Definition at line 56 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 56 of file G4MultiFunctionalDetector.cc
References G4SDManager::AddNewCollection(), G4VSensitiveDetector::collectionName, G4SDManager::FindSensitiveDetector(), G4endl, G4Exception(), G4VPrimitiveScorer::GetName(), G4SDManager::GetSDMpointer(), G4CollectionNameVector::insert(), JustWarning, gammaraytel::pr, primitives, G4VSensitiveDetector::SensitiveDetectorName, and G4VPrimitiveScorer::SetMultiFunctionalDetector().
Referenced by CML2Ph_FullWater::Construct(), B03ImportanceDetectorConstruction::ConstructSD(), B02ImportanceDetectorConstruction::ConstructSD(), B3DetectorConstruction::ConstructSDandField(), ElectronBenchmarkDetector::ConstructSDandField(), B01DetectorConstruction::ConstructSDandField(), TSDetectorConstruction::ConstructSDandField(), DicomDetectorConstruction::ConstructSDandField(), RE02DetectorConstruction::ConstructSDandField(), G4VScoringMesh::SetPrimitiveScorer(), RE06ParallelWorld::SetupDetectors(), GB03DetectorConstruction::SetupDetectors(), RE06DetectorConstruction::SetupDetectors(), and CexmcSetup::SetupSpecialVolumes().
G4bool G4MultiFunctionalDetector::RemovePrimitive (G4VPrimitiveScorer * aPS)
Definition at line 82 of file G4MultiFunctionalDetector.cc.
View newest version in sPHENIX GitHub at line 82 of file G4MultiFunctionalDetector.cc
References G4cerr, G4endl, G4VPrimitiveScorer::GetName(), gammaraytel::pr, primitives, G4VSensitiveDetector::SensitiveDetectorName, and G4VPrimitiveScorer::SetMultiFunctionalDetector().
Member Data Documentation
std::vector<G4VPrimitiveScorer*> G4MultiFunctionalDetector::primitives protected
Definition at line 56 of file G4MultiFunctionalDetector.hh.
View newest version in sPHENIX GitHub at line 56 of file G4MultiFunctionalDetector.hh
Referenced by clear(), DrawAll(), EndOfEvent(), GetNumberOfPrimitives(), GetPrimitive(), Initialize(), PrintAll(), ProcessHits(), RegisterPrimitive(), RemovePrimitive(), and ~G4MultiFunctionalDetector().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4MultiFunctionalDetector.hh
geant4/tree/geant4-10.6-release/source/digits_hits/detector/src/G4MultiFunctionalDetector.cc