ECCE @ EIC Software: G4ParticleHPParticleYield Class Reference
G4ParticleHPParticleYield Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPParticleYield.hh>
Public Member Functions
G4ParticleHPParticleYield ()
~G4ParticleHPParticleYield ()
G4double GetTargetMass ()
void InitMean (std::istream &aDataFile)
void InitPrompt (std::istream &aDataFile)
void InitDelayed (std::istream &aDataFile)
G4double GetMean (G4double anEnergy)
G4double GetPrompt (G4double anEnergy)
G4double GetDelayed (G4double anEnergy)
G4double GetDecayConstant (G4int i)
Private Attributes
G4double targetMass
G4bool simpleMean
G4ParticleHPPolynomExpansion theMean
G4ParticleHPVector theSimpleMean
G4bool hasPromptData
G4bool spontPrompt
G4ParticleHPVector thePrompt
G4double theSpontPrompt
G4bool hasDelayedData
G4bool spontDelayed
G4ParticleHPList thePrecursorDecayConstants
G4ParticleHPVector theDelayed
G4double theSpontDelayed
Detailed Description
Definition at line 39 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleHPParticleYield.hh
Constructor & Destructor Documentation
G4ParticleHPParticleYield::G4ParticleHPParticleYield () inline
Definition at line 42 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPParticleYield.hh
References hasDelayedData, hasPromptData, simpleMean, spontDelayed, spontPrompt, targetMass, theSpontDelayed, and theSpontPrompt.
G4ParticleHPParticleYield::~G4ParticleHPParticleYield () inline
Definition at line 54 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPParticleYield.hh
Member Function Documentation
G4double G4ParticleHPParticleYield::GetDecayConstant (G4int i) inline
Definition at line 135 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ParticleHPParticleYield.hh
References G4ParticleHPList::GetValue(), and thePrecursorDecayConstants.
Referenced by G4ParticleHPFSFissionFS::ApplyYourself().
G4double G4ParticleHPParticleYield::GetDelayed (G4double anEnergy) inline
Definition at line 125 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ParticleHPParticleYield.hh
References G4ParticleHPVector::GetY(), hasDelayedData, spontDelayed, theDelayed, and theSpontDelayed.
Referenced by G4FissionLibrary::SampleMult(), and G4ParticleHPFSFissionFS::SampleNeutronMult().
G4double G4ParticleHPParticleYield::GetMean (G4double anEnergy) inline
Definition at line 106 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParticleHPParticleYield.hh
References G4ParticleHPPolynomExpansion::GetValue(), G4ParticleHPVector::GetY(), simpleMean, theMean, and theSimpleMean.
Referenced by G4FissionLibrary::SampleMult(), and G4ParticleHPFSFissionFS::SampleNeutronMult().
G4double G4ParticleHPParticleYield::GetPrompt (G4double anEnergy) inline
Definition at line 115 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ParticleHPParticleYield.hh
References G4ParticleHPVector::GetY(), hasPromptData, spontPrompt, thePrompt, and theSpontPrompt.
Referenced by G4FissionLibrary::SampleMult(), and G4ParticleHPFSFissionFS::SampleNeutronMult().
G4double G4ParticleHPParticleYield::GetTargetMass () inline
Definition at line 56 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPParticleYield.hh
References targetMass.
Referenced by G4ParticleHPFSFissionFS::GetMass(), and G4FissionLibrary::Init().
void G4ParticleHPParticleYield::InitDelayed (std::istream & aDataFile) inline
Definition at line 89 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPParticleYield.hh
References CLHEP::eV, hasDelayedData, G4ParticleHPList::Init(), G4ParticleHPVector::Init(), CLHEP::s, spontDelayed, targetMass, theDelayed, thePrecursorDecayConstants, and theSpontDelayed.
Referenced by G4ParticleHPFSFissionFS::Init(), and G4FissionLibrary::Init().
void G4ParticleHPParticleYield::InitMean (std::istream & aDataFile) inline
Definition at line 58 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPParticleYield.hh
References CLHEP::eV, G4ParticleHPPolynomExpansion::Init(), G4ParticleHPVector::Init(), simpleMean, targetMass, theMean, and theSimpleMean.
Referenced by G4ParticleHPFSFissionFS::Init(), and G4FissionLibrary::Init().
void G4ParticleHPParticleYield::InitPrompt (std::istream & aDataFile) inline
Definition at line 73 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleHPParticleYield.hh
References CLHEP::eV, hasPromptData, G4ParticleHPVector::Init(), spontPrompt, targetMass, thePrompt, and theSpontPrompt.
Referenced by G4ParticleHPFSFissionFS::Init(), and G4FissionLibrary::Init().
Member Data Documentation
G4bool G4ParticleHPParticleYield::hasDelayedData private
Definition at line 155 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ParticleHPParticleYield.hh
Referenced by G4ParticleHPParticleYield(), GetDelayed(), and InitDelayed().
G4bool G4ParticleHPParticleYield::hasPromptData private
Definition at line 149 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ParticleHPParticleYield.hh
Referenced by G4ParticleHPParticleYield(), GetPrompt(), and InitPrompt().
G4bool G4ParticleHPParticleYield::simpleMean private
Definition at line 144 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ParticleHPParticleYield.hh
Referenced by G4ParticleHPParticleYield(), GetMean(), and InitMean().
G4bool G4ParticleHPParticleYield::spontDelayed private
Definition at line 156 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ParticleHPParticleYield.hh
Referenced by G4ParticleHPParticleYield(), GetDelayed(), and InitDelayed().
G4bool G4ParticleHPParticleYield::spontPrompt private
Definition at line 150 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ParticleHPParticleYield.hh
Referenced by G4ParticleHPParticleYield(), GetPrompt(), and InitPrompt().
G4double G4ParticleHPParticleYield::targetMass private
Definition at line 142 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ParticleHPParticleYield.hh
Referenced by G4ParticleHPParticleYield(), GetTargetMass(), InitDelayed(), InitMean(), and InitPrompt().
G4ParticleHPVector G4ParticleHPParticleYield::theDelayed private
Definition at line 158 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ParticleHPParticleYield.hh
Referenced by GetDelayed(), and InitDelayed().
G4ParticleHPPolynomExpansion G4ParticleHPParticleYield::theMean private
Definition at line 145 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ParticleHPParticleYield.hh
Referenced by GetMean(), and InitMean().
G4ParticleHPList G4ParticleHPParticleYield::thePrecursorDecayConstants private
Definition at line 157 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParticleHPParticleYield.hh
Referenced by GetDecayConstant(), and InitDelayed().
G4ParticleHPVector G4ParticleHPParticleYield::thePrompt private
Definition at line 151 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ParticleHPParticleYield.hh
Referenced by GetPrompt(), and InitPrompt().
G4ParticleHPVector G4ParticleHPParticleYield::theSimpleMean private
Definition at line 146 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ParticleHPParticleYield.hh
Referenced by GetMean(), and InitMean().
G4double G4ParticleHPParticleYield::theSpontDelayed private
Definition at line 159 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ParticleHPParticleYield.hh
Referenced by G4ParticleHPParticleYield(), GetDelayed(), and InitDelayed().
G4double G4ParticleHPParticleYield::theSpontPrompt private
Definition at line 152 of file G4ParticleHPParticleYield.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ParticleHPParticleYield.hh
Referenced by G4ParticleHPParticleYield(), GetPrompt(), and InitPrompt().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPParticleYield.hh