ECCE @ EIC Software: G3RotTableEntry Class Reference
G3RotTableEntry Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3RotTableEntry.hh>
Public Member Functions
G3RotTableEntry (G4int id, G4RotationMatrix *matrix)
G3RotTableEntry (const G3RotTableEntry &right)
virtual ~G3RotTableEntry ()
G3RotTableEntry & operator= (const G3RotTableEntry &right)
G4bool operator== (const G3RotTableEntry &right) const
G4bool operator!= (const G3RotTableEntry &right) const
G4int GetID () const
G4RotationMatrix * GetMatrix () const
Private Attributes
G4int fID
G4RotationMatrix * fMatrix
Detailed Description
Definition at line 46 of file G3RotTableEntry.hh.
View newest version in sPHENIX GitHub at line 46 of file G3RotTableEntry.hh
Constructor & Destructor Documentation
G3RotTableEntry::G3RotTableEntry (G4int id, G4RotationMatrix * matrix)
Definition at line 34 of file G3RotTableEntry.cc.
View newest version in sPHENIX GitHub at line 34 of file G3RotTableEntry.cc
G3RotTableEntry::G3RotTableEntry (const G3RotTableEntry & right)
Definition at line 39 of file G3RotTableEntry.cc.
View newest version in sPHENIX GitHub at line 39 of file G3RotTableEntry.cc
G3RotTableEntry::~G3RotTableEntry () virtual
Definition at line 44 of file G3RotTableEntry.cc.
View newest version in sPHENIX GitHub at line 44 of file G3RotTableEntry.cc
Member Function Documentation
G4int G3RotTableEntry::GetID () const inline
Definition at line 72 of file G3RotTableEntry.hh.
View newest version in sPHENIX GitHub at line 72 of file G3RotTableEntry.hh
References fID.
Referenced by G3RotTable::Get(), operator=(), and operator==().
G4RotationMatrix * G3RotTableEntry::GetMatrix () const inline
Definition at line 75 of file G3RotTableEntry.hh.
View newest version in sPHENIX GitHub at line 75 of file G3RotTableEntry.hh
References fMatrix.
Referenced by G3RotTable::Get(), and operator=().
G4bool G3RotTableEntry::operator!= (const G3RotTableEntry & right) const
Definition at line 63 of file G3RotTableEntry.cc.
View newest version in sPHENIX GitHub at line 63 of file G3RotTableEntry.cc
G3RotTableEntry & G3RotTableEntry::operator= (const G3RotTableEntry & right)
Definition at line 47 of file G3RotTableEntry.cc.
View newest version in sPHENIX GitHub at line 47 of file G3RotTableEntry.cc
References fID, fMatrix, GetID(), and GetMatrix().
G4bool G3RotTableEntry::operator== (const G3RotTableEntry & right) const
Definition at line 55 of file G3RotTableEntry.cc.
View newest version in sPHENIX GitHub at line 55 of file G3RotTableEntry.cc
References fID, and GetID().
Member Data Documentation
G4int G3RotTableEntry::fID private
Definition at line 66 of file G3RotTableEntry.hh.
View newest version in sPHENIX GitHub at line 66 of file G3RotTableEntry.hh
Referenced by GetID(), operator=(), and operator==().
G4RotationMatrix* G3RotTableEntry::fMatrix private
Definition at line 67 of file G3RotTableEntry.hh.
View newest version in sPHENIX GitHub at line 67 of file G3RotTableEntry.hh
Referenced by GetMatrix(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3RotTableEntry.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3RotTableEntry.cc