ECCE @ EIC Software: pyG4ProcessManager Namespace Reference
pyG4ProcessManager Namespace Reference
Functions
list f_GetProcessList (const G4ProcessManager *procMgr)
list f_GetProcessVector (const G4ProcessManager *procMgr, G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ=typeGPIL)
BOOST_PYTHON_FUNCTION_OVERLOADS (g_GetProcessVector, f_GetProcessVector, 2, 3) list f_GetAtRestProcessVector(const G4ProcessManager *procMgr
Variables
G4ProcessVectorTypeIndex typ
G4VProcess *(G4ProcessManager::* f2_RemoveProcess)(G4int) = &G4ProcessManager::RemoveProcess
G4VProcess *(G4ProcessManager::* f1_SetProcessActivation)(G4VProcess *, G4bool) = &G4ProcessManager::SetProcessActivation
G4VProcess *(G4ProcessManager::* f2_SetProcessActivation)(G4int, G4bool) = &G4ProcessManager::SetProcessActivation
G4bool(G4ProcessManager::* f1_GetProcessActivation)(G4VProcess *) const = &G4ProcessManager::GetProcessActivation
G4bool(G4ProcessManager::* f2_GetProcessActivation)(G4int) const = &G4ProcessManager::GetProcessActivation
Function Documentation
pyG4ProcessManager::BOOST_PYTHON_FUNCTION_OVERLOADS (g_GetProcessVector , f_GetProcessVector , 2 , 3) const
list pyG4ProcessManager::f_GetProcessList (const G4ProcessManager * procMgr)
Definition at line 43 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 43 of file pyG4ProcessManager.cc
Referenced by export_G4ProcessManager().
list pyG4ProcessManager::f_GetProcessVector (const G4ProcessManager * procMgr, G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ = typeGPIL)
Definition at line 55 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 55 of file pyG4ProcessManager.cc
References typ.
Referenced by export_G4ProcessManager().
Variable Documentation
G4bool(G4ProcessManager::* pyG4ProcessManager::f1_GetProcessActivation)(G4VProcess *) const = &G4ProcessManager::GetProcessActivation
Definition at line 157 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 157 of file pyG4ProcessManager.cc
Referenced by export_G4ProcessManager().
G4VProcess*(G4ProcessManager::* pyG4ProcessManager::f1_SetProcessActivation)(G4VProcess *, G4bool) = &G4ProcessManager::SetProcessActivation
Definition at line 151 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 151 of file pyG4ProcessManager.cc
Referenced by export_G4ProcessManager(), and export_G4ProcessTable().
G4bool(G4ProcessManager::* pyG4ProcessManager::f2_GetProcessActivation)(G4int) const = &G4ProcessManager::GetProcessActivation
Definition at line 160 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 160 of file pyG4ProcessManager.cc
Referenced by export_G4ProcessManager().
G4VProcess*(G4ProcessManager::* pyG4ProcessManager::f2_RemoveProcess)(G4int) = &G4ProcessManager::RemoveProcess
Definition at line 147 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 147 of file pyG4ProcessManager.cc
Referenced by export_G4ProcessManager().
G4VProcess*(G4ProcessManager::* pyG4ProcessManager::f2_SetProcessActivation)(G4int, G4bool) = &G4ProcessManager::SetProcessActivation
Definition at line 154 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 154 of file pyG4ProcessManager.cc
Referenced by export_G4ProcessManager(), and export_G4ProcessTable().
G4ProcessVectorTypeIndex pyG4ProcessManager::typ
Definition at line 73 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 73 of file pyG4ProcessManager.cc
Referenced by f_GetProcessVector(), PHG4HcalDetector::SetDetectorType(), PHG4SpacalDetector::SetDetectorType(), G4tgrPlaceDivRep::SetDivType(), and G4tgrPlace::SetType().