ECCE @ EIC Software: BeamLineMagnetSteppingAction Class Reference
BeamLineMagnetSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.h>
Public Member Functions
BeamLineMagnetSteppingAction (BeamLineMagnetDetector *, const PHParameters *parameters)
constructor
~BeamLineMagnetSteppingAction () override
destructor
bool UserSteppingAction (const G4Step *, bool) override
stepping action
void SetInterfacePointers (PHCompositeNode *) override
reimplemented from base class
void SetHitNodeName (const std::string &type, const std::string &name) override
Set the G4HIT node names from Subsystem rather than constructing your own.
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
BeamLineMagnetDetector * m_Detector = nullptr
pointer to the detector
const PHParameters * m_Params = nullptr
PHG4HitContainer * m_HitContainer = nullptr
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer = nullptr
PHG4Hit * m_Hit = nullptr
PHG4HitContainer * m_SaveHitContainer = nullptr
G4VPhysicalVolume * m_SaveVolPre = nullptr
G4VPhysicalVolume * m_SaveVolPost = nullptr
int m_SaveTrackId = -1
int m_SavePreStepStatus = -1
int m_SavePostStepStatus = -1
double m_EdepSum = 0.
int m_ActiveFlag = 0
int m_AbsorberActiveFlag = 0
int m_BlackHoleFlag = 0
std::string m_HitNodeName
std::string m_AbsorberNodeName
Detailed Description
Definition at line 18 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 18 of file BeamLineMagnetSteppingAction.h
Constructor & Destructor Documentation
BeamLineMagnetSteppingAction::BeamLineMagnetSteppingAction (BeamLineMagnetDetector * detector, const PHParameters * parameters)
constructor
Definition at line 42 of file BeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 42 of file BeamLineMagnetSteppingAction.cc
BeamLineMagnetSteppingAction::~BeamLineMagnetSteppingAction () override
destructor
Definition at line 52 of file BeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 52 of file BeamLineMagnetSteppingAction.cc
References m_Hit.
Member Function Documentation
void BeamLineMagnetSteppingAction::SetHitNodeName (const std::string & , const std::string &) override virtual
Set the G4HIT node names from Subsystem rather than constructing your own.
Reimplemented from PHG4SteppingAction.
Definition at line 310 of file BeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 310 of file BeamLineMagnetSteppingAction.cc
References m_AbsorberNodeName, and m_HitNodeName.
void BeamLineMagnetSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) override virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 287 of file BeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 287 of file BeamLineMagnetSteppingAction.cc
References m_AbsorberHitContainer, m_AbsorberNodeName, m_BlackHoleFlag, m_HitContainer, m_HitNodeName, and PHG4SteppingAction::Verbosity().
bool BeamLineMagnetSteppingAction::UserSteppingAction (const G4Step * aStep, bool) override virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 62 of file BeamLineMagnetSteppingAction.cc.
View newest version in sPHENIX GitHub at line 62 of file BeamLineMagnetSteppingAction.cc
References PHG4HitContainer::AddHit(), cm, edep, fAtRestDoItProc, fGeomBoundary, fPostStepDoItProc, fStopAndKill, fUndefined, fWorldBoundary, PHG4Hit::get_hit_id(), PHG4Hit::get_x(), G4VPhysicalVolume::GetCopyNo(), G4StepPoint::GetGlobalTime(), PHG4HitContainer::GetID(), G4Track::GetKineticEnergy(), PHG4SteppingAction::GetName(), G4VPhysicalVolume::GetName(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), PHG4StepStatusDecode::GetStepStatus(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchableHandle(), G4Step::GetTrack(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), G4Track::GetUserInformation(), G4VTouchable::GetVolume(), GeV, isfinite, BeamLineMagnetDetector::IsInBeamLineMagnet(), m_AbsorberActiveFlag, m_AbsorberHitContainer, m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_EdepSum, m_Hit, m_HitContainer, m_SaveHitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, nanosecond, G4InuclParticleNames::pp, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_layer(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), G4Track::SetTrackStatus(), Acts::Test::volume, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
int BeamLineMagnetSteppingAction::m_AbsorberActiveFlag = 0 private
Definition at line 52 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 52 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
PHG4HitContainer* BeamLineMagnetSteppingAction::m_AbsorberHitContainer = nullptr private
Definition at line 41 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 41 of file BeamLineMagnetSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string BeamLineMagnetSteppingAction::m_AbsorberNodeName private
Definition at line 56 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 56 of file BeamLineMagnetSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
int BeamLineMagnetSteppingAction::m_ActiveFlag = 0 private
Definition at line 51 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 51 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
int BeamLineMagnetSteppingAction::m_BlackHoleFlag = 0 private
Definition at line 53 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 53 of file BeamLineMagnetSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
BeamLineMagnetDetector* BeamLineMagnetSteppingAction::m_Detector = nullptr private
pointer to the detector
Definition at line 37 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 37 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
double BeamLineMagnetSteppingAction::m_EdepSum = 0. private
Definition at line 50 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 50 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
PHG4Hit* BeamLineMagnetSteppingAction::m_Hit = nullptr private
Definition at line 42 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 42 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction(), and ~BeamLineMagnetSteppingAction().
PHG4HitContainer* BeamLineMagnetSteppingAction::m_HitContainer = nullptr private
pointer to hit container
Definition at line 40 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 40 of file BeamLineMagnetSteppingAction.h
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::string BeamLineMagnetSteppingAction::m_HitNodeName private
Definition at line 55 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 55 of file BeamLineMagnetSteppingAction.h
Referenced by SetHitNodeName(), and SetInterfacePointers().
const PHParameters* BeamLineMagnetSteppingAction::m_Params = nullptr private
Definition at line 38 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 38 of file BeamLineMagnetSteppingAction.h
PHG4HitContainer* BeamLineMagnetSteppingAction::m_SaveHitContainer = nullptr private
Definition at line 43 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 43 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
int BeamLineMagnetSteppingAction::m_SavePostStepStatus = -1 private
Definition at line 49 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 49 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
int BeamLineMagnetSteppingAction::m_SavePreStepStatus = -1 private
Definition at line 48 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 48 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
int BeamLineMagnetSteppingAction::m_SaveTrackId = -1 private
Definition at line 47 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 47 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* BeamLineMagnetSteppingAction::m_SaveVolPost = nullptr private
Definition at line 46 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 46 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
G4VPhysicalVolume* BeamLineMagnetSteppingAction::m_SaveVolPre = nullptr private
Definition at line 45 of file BeamLineMagnetSteppingAction.h.
View newest version in sPHENIX GitHub at line 45 of file BeamLineMagnetSteppingAction.h
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.cc