ECCE @ EIC Software: G4ScoreQuantityMessenger Class Reference
G4ScoreQuantityMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoreQuantityMessenger.hh>
Public Member Functions
G4ScoreQuantityMessenger (G4ScoringManager *SManager)
~G4ScoreQuantityMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Protected Member Functions
void FillTokenVec (G4String newValues, G4TokenVec &token)
void FParticleCommand (G4VScoringMesh *mesh, G4TokenVec &token)
void FParticleWithEnergyCommand (G4VScoringMesh *mesh, G4TokenVec &token)
G4bool CheckMeshPS (G4VScoringMesh *mesh, G4String &psname, G4UIcommand *command)
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Private Member Functions
void QuantityCommands ()
void FilterCommands ()
Private Attributes
G4ScoringManager * fSMan
G4UIdirectory * quantityDir
G4UIcmdWithAString * qTouchCmd
G4UIcmdWithoutParameter * qGetUnitCmd
G4UIcmdWithAString * qSetUnitCmd
G4UIcommand * qCellChgCmd
G4UIcommand * qCellFluxCmd
G4UIcommand * qPassCellFluxCmd
G4UIcommand * qeDepCmd
G4UIcommand * qdoseDepCmd
G4UIcommand * qnOfStepCmd
G4UIcommand * qnOfSecondaryCmd
G4UIcommand * qTrackLengthCmd
G4UIcommand * qPassCellCurrCmd
G4UIcommand * qPassTrackLengthCmd
G4UIcommand * qFlatSurfCurrCmd
G4UIcommand * qFlatSurfFluxCmd
G4UIcommand * qNofCollisionCmd
G4UIcommand * qPopulationCmd
G4UIcommand * qTrackCountCmd
G4UIcommand * qTerminationCmd
G4UIcommand * qMinKinEAtGeneCmd
G4UIcommand * qStepCheckerCmd
G4UIdirectory * filterDir
G4UIcmdWithAString * fchargedCmd
G4UIcmdWithAString * fneutralCmd
G4UIcommand * fkinECmd
G4UIcommand * fparticleCmd
G4UIcommand * fparticleKinECmd
Additional Inherited Members
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 58 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ScoreQuantityMessenger.hh
Constructor & Destructor Documentation
G4ScoreQuantityMessenger::G4ScoreQuantityMessenger (G4ScoringManager * SManager)
Definition at line 116 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 116 of file G4ScoreQuantityMessenger.cc
References FilterCommands(), and QuantityCommands().
G4ScoreQuantityMessenger::~G4ScoreQuantityMessenger ()
Definition at line 199 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 199 of file G4ScoreQuantityMessenger.cc
References fchargedCmd, filterDir, fkinECmd, fneutralCmd, fparticleCmd, fparticleKinECmd, qCellChgCmd, qCellFluxCmd, qdoseDepCmd, qeDepCmd, qFlatSurfCurrCmd, qFlatSurfFluxCmd, qGetUnitCmd, qMinKinEAtGeneCmd, qNofCollisionCmd, qnOfSecondaryCmd, qnOfStepCmd, qPassCellCurrCmd, qPassCellFluxCmd, qPassTrackLengthCmd, qPopulationCmd, qSetUnitCmd, qStepCheckerCmd, qTerminationCmd, qTouchCmd, qTrackCountCmd, qTrackLengthCmd, and quantityDir.
Member Function Documentation
G4bool G4ScoreQuantityMessenger::CheckMeshPS (G4VScoringMesh * mesh, G4String & psname, G4UIcommand * command) protected
Definition at line 643 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 643 of file G4ScoreQuantityMessenger.cc
References G4UIcommand::CommandFailed(), G4VScoringMesh::FindPrimitiveScorer(), G4UIcommand::GetCommandPath(), qTouchCmd, and G4VScoringMesh::SetNullToCurrentPrimitiveScorer().
Referenced by SetNewValue().
void G4ScoreQuantityMessenger::FillTokenVec (G4String newValues, G4TokenVec & token) protected
Definition at line 605 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 605 of file G4ScoreQuantityMessenger.cc
Referenced by SetNewValue().
void G4ScoreQuantityMessenger::FilterCommands () private
Definition at line 123 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 123 of file G4ScoreQuantityMessenger.cc
References DBL_MAX, G4UImessenger::DtoS(), fchargedCmd, filterDir, fkinECmd, fneutralCmd, fparticleCmd, fparticleKinECmd, G4UIparameter::SetDefaultUnit(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIcmdWithAString::SetParameterName(), and smax.
Referenced by G4ScoreQuantityMessenger().
void G4ScoreQuantityMessenger::FParticleCommand (G4VScoringMesh * mesh, G4TokenVec & token) protected
Definition at line 615 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 615 of file G4ScoreQuantityMessenger.cc
References G4VScoringMesh::SetFilter().
Referenced by SetNewValue().
void G4ScoreQuantityMessenger::FParticleWithEnergyCommand (G4VScoringMesh * mesh, G4TokenVec & token) protected
Definition at line 630 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 630 of file G4ScoreQuantityMessenger.cc
References G4SDParticleWithEnergyFilter::add(), filter, G4UnitDefinition::GetValueOf(), G4VScoringMesh::SetFilter(), and G4UImessenger::StoD().
Referenced by SetNewValue().
G4String G4ScoreQuantityMessenger::GetCurrentValue (G4UIcommand *) virtual
Reimplemented from G4UImessenger.
Definition at line 598 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 598 of file G4ScoreQuantityMessenger.cc
void G4ScoreQuantityMessenger::QuantityCommands () private
Definition at line 84 of file G4ScoreQuantityMessengerQCmd.cc.
View newest version in sPHENIX GitHub at line 84 of file G4ScoreQuantityMessengerQCmd.cc
References qCellChgCmd, qCellFluxCmd, qdoseDepCmd, qeDepCmd, qFlatSurfCurrCmd, qFlatSurfFluxCmd, qGetUnitCmd, qMinKinEAtGeneCmd, qNofCollisionCmd, qnOfSecondaryCmd, qnOfStepCmd, qPassCellCurrCmd, qPassCellFluxCmd, qPassTrackLengthCmd, qPopulationCmd, qSetUnitCmd, qStepCheckerCmd, qTerminationCmd, qTouchCmd, qTrackCountCmd, qTrackLengthCmd, quantityDir, G4UIparameter::SetDefaultUnit(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), and G4UIcmdWithAString::SetParameterName().
Referenced by G4ScoreQuantityMessenger().
void G4ScoreQuantityMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 240 of file G4ScoreQuantityMessenger.cc.
View newest version in sPHENIX GitHub at line 240 of file G4ScoreQuantityMessenger.cc
References CheckMeshPS(), G4UIcommand::CommandFailed(), G4PSFlatSurfaceCurrent::DivideByArea(), G4PSFlatSurfaceFlux::DivideByArea(), G4PSTrackLength::DivideByVelocity(), fchargedCmd, FillTokenVec(), fkinECmd, fneutralCmd, fparticleCmd, FParticleCommand(), fparticleKinECmd, FParticleWithEnergyCommand(), fSMan, G4cout, G4endl, G4UIcommand::GetCommandPath(), G4VScoringMesh::GetCopyNumberLevel(), G4ScoringManager::GetCurrentMesh(), G4VScoringMesh::GetCurrentPSUnit(), G4VScoringMesh::GetNumberOfSegments(), G4VScoringMesh::GetShape(), G4VScoringMesh::GetSize(), G4UnitDefinition::GetValueOf(), G4VScoringMesh::IsCurrentPrimitiveScorerNull(), G4PSTrackLength::MultiplyKineticEnergy(), ps, qCellChgCmd, qCellFluxCmd, qdoseDepCmd, qeDepCmd, qFlatSurfCurrCmd, qFlatSurfFluxCmd, qGetUnitCmd, qMinKinEAtGeneCmd, qNofCollisionCmd, qnOfSecondaryCmd, qnOfStepCmd, qPassCellCurrCmd, qPassCellFluxCmd, qPassTrackLengthCmd, qPopulationCmd, qSetUnitCmd, qStepCheckerCmd, qTerminationCmd, qTouchCmd, qTrackCountCmd, qTrackLengthCmd, G4PSNofStep::SetBoundaryFlag(), G4VScoringMesh::SetCurrentPrimitiveScorer(), G4VScoringMesh::SetCurrentPSUnit(), G4PSDoseDepositForCylinder3D::SetCylinderSize(), G4PSPassageCellFluxForCylinder3D::SetCylinderSize(), G4PSCellFluxForCylinder3D::SetCylinderSize(), G4VScoringMesh::SetFilter(), G4PSDoseDepositForCylinder3D::SetNumberOfSegments(), G4PSPassageCellFluxForCylinder3D::SetNumberOfSegments(), G4PSCellFluxForCylinder3D::SetNumberOfSegments(), G4VScoringMesh::SetPrimitiveScorer(), G4PSEnergyDeposit::SetUnit(), G4PSCellCharge::SetUnit(), G4PSDoseDeposit::SetUnit(), G4PSPassageTrackLength::SetUnit(), G4PSMinKinEAtGeneration::SetUnit(), G4PSPassageCellFlux::SetUnit(), G4PSTrackLength::SetUnit(), G4PSCellFlux::SetUnit(), G4PSFlatSurfaceCurrent::SetUnit(), G4PSFlatSurfaceFlux::SetUnit(), G4UImessenger::StoB(), G4UImessenger::StoD(), G4UImessenger::StoI(), G4PSPassageCellCurrent::Weighted(), G4PSPassageTrackLength::Weighted(), G4PSTrackLength::Weighted(), G4PSNofCollision::Weighted(), G4PSTrackCounter::Weighted(), G4PSTermination::Weighted(), G4PSPopulation::Weighted(), G4PSFlatSurfaceFlux::Weighted(), and G4PSFlatSurfaceCurrent::Weighted().
Member Data Documentation
G4UIcmdWithAString* G4ScoreQuantityMessenger::fchargedCmd private
Definition at line 121 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ScoreQuantityMessenger.hh
Referenced by FilterCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIdirectory* G4ScoreQuantityMessenger::filterDir private
Definition at line 120 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ScoreQuantityMessenger.hh
Referenced by FilterCommands(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::fkinECmd private
Definition at line 123 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ScoreQuantityMessenger.hh
Referenced by FilterCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcmdWithAString* G4ScoreQuantityMessenger::fneutralCmd private
Definition at line 122 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 122 of file G4ScoreQuantityMessenger.hh
Referenced by FilterCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::fparticleCmd private
Definition at line 124 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 124 of file G4ScoreQuantityMessenger.hh
Referenced by FilterCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::fparticleKinECmd private
Definition at line 125 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ScoreQuantityMessenger.hh
Referenced by FilterCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4ScoringManager* G4ScoreQuantityMessenger::fSMan private
Definition at line 85 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ScoreQuantityMessenger.hh
Referenced by SetNewValue().
G4UIcommand* G4ScoreQuantityMessenger::qCellChgCmd private
Definition at line 93 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qCellFluxCmd private
Definition at line 94 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qdoseDepCmd private
Definition at line 97 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qeDepCmd private
Definition at line 96 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qFlatSurfCurrCmd private
Definition at line 104 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qFlatSurfFluxCmd private
Definition at line 105 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcmdWithoutParameter* G4ScoreQuantityMessenger::qGetUnitCmd private
Definition at line 90 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qMinKinEAtGeneCmd private
Definition at line 114 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qNofCollisionCmd private
Definition at line 110 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qnOfSecondaryCmd private
Definition at line 99 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qnOfStepCmd private
Definition at line 98 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qPassCellCurrCmd private
Definition at line 102 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qPassCellFluxCmd private
Definition at line 95 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qPassTrackLengthCmd private
Definition at line 103 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qPopulationCmd private
Definition at line 111 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcmdWithAString* G4ScoreQuantityMessenger::qSetUnitCmd private
Definition at line 91 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qStepCheckerCmd private
Definition at line 116 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qTerminationCmd private
Definition at line 113 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcmdWithAString* G4ScoreQuantityMessenger::qTouchCmd private
Definition at line 89 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ScoreQuantityMessenger.hh
Referenced by CheckMeshPS(), QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qTrackCountCmd private
Definition at line 112 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIcommand* G4ScoreQuantityMessenger::qTrackLengthCmd private
Definition at line 101 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), SetNewValue(), and ~G4ScoreQuantityMessenger().
G4UIdirectory* G4ScoreQuantityMessenger::quantityDir private
Definition at line 88 of file G4ScoreQuantityMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ScoreQuantityMessenger.hh
Referenced by QuantityCommands(), and ~G4ScoreQuantityMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoreQuantityMessenger.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4ScoreQuantityMessenger.cc
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4ScoreQuantityMessengerQCmd.cc