ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/geometry/pyG4Cons.cc File Reference
pyG4Cons.cc File Reference
#include <boost/python.hpp>
#include "G4Cons.hh"
Namespaces
namespace pyG4Cons
Functions
G4Cons * pyG4Cons::CreateCons (const G4String &name, G4double pRmin1, G4double pRmax1, G4double pRmin2, G4double pRmax2, G4double pDz, G4double pSPhi, G4double pDPhi)
void export_G4Cons ()
Function Documentation
void export_G4Cons ()
Definition at line 55 of file pyG4Cons.cc.
View newest version in sPHENIX GitHub at line 55 of file pyG4Cons.cc
References pyG4Cons::CreateCons(), G4Cons::GetDeltaPhiAngle(), G4Cons::GetInnerRadiusMinusZ(), G4Cons::GetInnerRadiusPlusZ(), G4Cons::GetOuterRadiusMinusZ(), G4Cons::GetOuterRadiusPlusZ(), G4Cons::GetStartPhiAngle(), G4Cons::GetZHalfLength(), init(), G4Cons::SetDeltaPhiAngle(), G4Cons::SetInnerRadiusMinusZ(), G4Cons::SetInnerRadiusPlusZ(), G4Cons::SetOuterRadiusMinusZ(), G4Cons::SetOuterRadiusPlusZ(), G4Cons::SetStartPhiAngle(), and G4Cons::SetZHalfLength().
Referenced by BOOST_PYTHON_MODULE().