ECCE @ EIC Software: G4CollisionnpElastic Class Reference
G4CollisionnpElastic Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionnpElastic.hh>
Public Member Functions
G4CollisionnpElastic ()
virtual ~G4CollisionnpElastic ()
G4bool operator== (const G4CollisionnpElastic &right) const
G4bool operator!= (const G4CollisionnpElastic &right) const
virtual G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4String GetName () const
Public Member Functions inherited from G4VElasticCollision
G4VElasticCollision ()
virtual ~G4VElasticCollision ()
G4bool operator== (const G4VElasticCollision &right) const
G4bool operator!= (const G4VElasticCollision &right) const
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const
virtual const
G4VAngularDistribution * GetAngularDistribution () const
virtual const std::vector
< G4String > & GetListOfColliders (G4int whichOne) const
Private Member Functions
G4CollisionnpElastic (const G4CollisionnpElastic &)
G4CollisionnpElastic & operator= (const G4CollisionnpElastic &)
Private Attributes
G4VCrossSectionSource * crossSectionSource
G4VAngularDistribution * angularDistribution
std::vector< G4String > colliders1
std::vector< G4String > colliders2
Detailed Description
Definition at line 41 of file G4CollisionnpElastic.hh.
View newest version in sPHENIX GitHub at line 41 of file G4CollisionnpElastic.hh
Constructor & Destructor Documentation
G4CollisionnpElastic::G4CollisionnpElastic ()
Definition at line 42 of file G4CollisionnpElastic.cc.
View newest version in sPHENIX GitHub at line 42 of file G4CollisionnpElastic.cc
References angularDistribution, colliders1, colliders2, crossSectionSource, G4ParticleDefinition::GetParticleSubType(), G4Neutron::NeutronDefinition(), and G4Proton::ProtonDefinition().
G4CollisionnpElastic::~G4CollisionnpElastic () virtual
Definition at line 57 of file G4CollisionnpElastic.cc.
View newest version in sPHENIX GitHub at line 57 of file G4CollisionnpElastic.cc
References angularDistribution, and crossSectionSource.
G4CollisionnpElastic::G4CollisionnpElastic (const G4CollisionnpElastic &) private
Member Function Documentation
virtual const G4VAngularDistribution* G4CollisionnpElastic::GetAngularDistribution () const inline protected virtual
Implements G4VCollision.
Definition at line 65 of file G4CollisionnpElastic.hh.
View newest version in sPHENIX GitHub at line 65 of file G4CollisionnpElastic.hh
References angularDistribution.
virtual const G4VCrossSectionSource* G4CollisionnpElastic::GetCrossSectionSource () const inline protected virtual
Implements G4VCollision.
Definition at line 64 of file G4CollisionnpElastic.hh.
View newest version in sPHENIX GitHub at line 64 of file G4CollisionnpElastic.hh
References crossSectionSource.
const std::vector< G4String > & G4CollisionnpElastic::GetListOfColliders (G4int whichOne) const protected virtual
Implements G4VCollision.
Definition at line 84 of file G4CollisionnpElastic.cc.
View newest version in sPHENIX GitHub at line 84 of file G4CollisionnpElastic.cc
References colliders1, and colliders2.
virtual G4String G4CollisionnpElastic::GetName (void) const inline virtual
Implements G4VCollision.
Definition at line 56 of file G4CollisionnpElastic.hh.
View newest version in sPHENIX GitHub at line 56 of file G4CollisionnpElastic.hh
G4bool G4CollisionnpElastic::IsInCharge (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCollision.
Definition at line 64 of file G4CollisionnpElastic.cc.
View newest version in sPHENIX GitHub at line 64 of file G4CollisionnpElastic.cc
References G4KineticTrack::GetDefinition(), G4Neutron::NeutronDefinition(), and G4Proton::ProtonDefinition().
G4bool G4CollisionnpElastic::operator!= (const G4CollisionnpElastic & right) const
G4CollisionnpElastic& G4CollisionnpElastic::operator= (const G4CollisionnpElastic &) private
G4bool G4CollisionnpElastic::operator== (const G4CollisionnpElastic & right) const
Member Data Documentation
G4VAngularDistribution* G4CollisionnpElastic::angularDistribution private
Definition at line 73 of file G4CollisionnpElastic.hh.
View newest version in sPHENIX GitHub at line 73 of file G4CollisionnpElastic.hh
Referenced by G4CollisionnpElastic(), GetAngularDistribution(), and ~G4CollisionnpElastic().
std::vector<G4String> G4CollisionnpElastic::colliders1 private
Definition at line 75 of file G4CollisionnpElastic.hh.
View newest version in sPHENIX GitHub at line 75 of file G4CollisionnpElastic.hh
Referenced by G4CollisionnpElastic(), and GetListOfColliders().
std::vector<G4String> G4CollisionnpElastic::colliders2 private
Definition at line 76 of file G4CollisionnpElastic.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CollisionnpElastic.hh
Referenced by G4CollisionnpElastic(), and GetListOfColliders().
G4VCrossSectionSource* G4CollisionnpElastic::crossSectionSource private
Definition at line 72 of file G4CollisionnpElastic.hh.
View newest version in sPHENIX GitHub at line 72 of file G4CollisionnpElastic.hh
Referenced by G4CollisionnpElastic(), GetCrossSectionSource(), and ~G4CollisionnpElastic().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionnpElastic.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4CollisionnpElastic.cc