ECCE @ EIC Software: G02ChamberParameterisation Class Reference
G02ChamberParameterisation Class Reference
Chamber parametrisation used in the GDML read/write example.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/include/G02ChamberParameterisation.hh>
Public Member Functions
G02ChamberParameterisation (G4int NoChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
~G02ChamberParameterisation ()
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Box &trackerLayer, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4int fNoChambers
G4double fStartZ
G4double fHalfWidth
G4double fSpacing
G4double fHalfLengthFirst
G4double fHalfLengthIncr
Detailed Description
Chamber parametrisation used in the GDML read/write example.
Definition at line 67 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 67 of file G02ChamberParameterisation.hh
Constructor & Destructor Documentation
G02ChamberParameterisation::G02ChamberParameterisation (G4int NoChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
Definition at line 44 of file G02ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 44 of file G02ChamberParameterisation.cc
References FatalException, fHalfLengthFirst, fHalfLengthIncr, fHalfWidth, fNoChambers, fSpacing, fStartZ, and G4Exception().
G02ChamberParameterisation::~G02ChamberParameterisation ()
Definition at line 72 of file G02ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 72 of file G02ChamberParameterisation.cc
Member Function Documentation
void G02ChamberParameterisation::ComputeDimensions (G4Box & trackerLayer, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file G02ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 89 of file G02ChamberParameterisation.cc
References fHalfLengthFirst, fHalfLengthIncr, fHalfWidth, G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), and G4Box::SetZHalfLength().
void G02ChamberParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 88 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 88 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 89 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 90 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 90 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 91 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 92 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 92 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 93 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 93 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 94 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 94 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 95 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 95 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 96 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 96 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 97 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 97 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 98 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 98 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 99 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 99 of file G02ChamberParameterisation.hh
void G02ChamberParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Definition at line 78 of file G02ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 78 of file G02ChamberParameterisation.cc
References fSpacing, fStartZ, Acts::Test::origin(), G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
Member Data Documentation
G4double G02ChamberParameterisation::fHalfLengthFirst private
Definition at line 107 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 107 of file G02ChamberParameterisation.hh
Referenced by ComputeDimensions(), and G02ChamberParameterisation().
G4double G02ChamberParameterisation::fHalfLengthIncr private
Definition at line 108 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 108 of file G02ChamberParameterisation.hh
Referenced by ComputeDimensions(), and G02ChamberParameterisation().
G4double G02ChamberParameterisation::fHalfWidth private
Definition at line 105 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 105 of file G02ChamberParameterisation.hh
Referenced by ComputeDimensions(), and G02ChamberParameterisation().
G4int G02ChamberParameterisation::fNoChambers private
Definition at line 103 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 103 of file G02ChamberParameterisation.hh
Referenced by G02ChamberParameterisation().
G4double G02ChamberParameterisation::fSpacing private
Definition at line 106 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 106 of file G02ChamberParameterisation.hh
Referenced by ComputeTransformation(), and G02ChamberParameterisation().
G4double G02ChamberParameterisation::fStartZ private
Definition at line 104 of file G02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 104 of file G02ChamberParameterisation.hh
Referenced by ComputeTransformation(), and G02ChamberParameterisation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/include/G02ChamberParameterisation.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G02/src/G02ChamberParameterisation.cc