ECCE @ EIC Software: G4NucleiProperties Class Reference
G4NucleiProperties Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4NucleiProperties.hh>
Public Member Functions
~G4NucleiProperties ()
G4NucleiProperties ()
Static Public Member Functions
static G4double GetNuclearMass (const G4double A, const G4double Z)
static G4double GetNuclearMass (const G4int A, const G4int Z)
static bool IsInStableTable (const G4double A, const G4double Z)
static bool IsInStableTable (const G4int A, const G4int Z)
static G4double GetBindingEnergy (const G4int A, const G4int Z)
static G4double GetBindingEnergy (const G4double A, const G4double Z)
static G4double GetMassExcess (const G4int A, const G4int Z)
static G4double GetMassExcess (const G4double A, const G4double Z)
Private Types
enum { MaxZ = 120 }
Static Private Member Functions
static G4double GetAtomicMass (const G4double A, const G4double Z)
static G4double AtomicMass (G4double A, G4double Z)
static G4double NuclearMass (G4double A, G4double Z)
static G4double BindingEnergy (G4double A, G4double Z)
static G4double MassExcess (G4double A, G4double Z)
Static Private Attributes
static G4ThreadLocal G4double electronMass [MaxZ]
static G4ThreadLocal G4bool isIntialized
static G4ThreadLocal G4double mass_proton = -1.
static G4ThreadLocal G4double mass_neutron = -1.
static G4ThreadLocal G4double mass_deuteron = -1.
static G4ThreadLocal G4double mass_triton = -1.
static G4ThreadLocal G4double mass_alpha = -1.
static G4ThreadLocal G4double mass_He3 = -1.
Detailed Description
Definition at line 46 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 46 of file G4NucleiProperties.hh
Member Enumeration Documentation
anonymous enum private
Enumerator:
MaxZ
Definition at line 97 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 97 of file G4NucleiProperties.hh
Constructor & Destructor Documentation
G4NucleiProperties::~G4NucleiProperties () inline
Definition at line 55 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 55 of file G4NucleiProperties.hh
G4NucleiProperties::G4NucleiProperties () inline
Definition at line 58 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 58 of file G4NucleiProperties.hh
Member Function Documentation
G4double G4NucleiProperties::AtomicMass (G4double A, G4double Z) static private
Definition at line 262 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 262 of file G4NucleiProperties.cc
References source.hepunit::amu_c2, BindingEnergy(), G4NucleiPropertiesTableAME12::GetMassExcess(), mass, and Z.
Referenced by GetAtomicMass(), and NuclearMass().
G4double G4NucleiProperties::BindingEnergy (G4double A, G4double Z) static private
Definition at line 294 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 294 of file G4NucleiProperties.cc
References MeV, and Z.
Referenced by AtomicMass(), and GetBindingEnergy().
G4double G4NucleiProperties::GetAtomicMass (const G4double A, const G4double Z) static private
Definition at line 200 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 200 of file G4NucleiProperties.cc
References AtomicMass(), e, G4cout, G4endl, G4NucleiPropertiesTheoreticalTable::GetAtomicMass(), G4NucleiPropertiesTableAME12::GetAtomicMass(), G4ParticleTable::GetParticleTable(), G4NucleiPropertiesTheoreticalTable::IsInTable(), and G4NucleiPropertiesTableAME12::IsInTable().
Referenced by MassExcess().
G4double G4NucleiProperties::GetBindingEnergy (const G4int A, const G4int Z) static
Definition at line 234 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 234 of file G4NucleiProperties.cc
References BindingEnergy(), G4cout, G4endl, G4NucleiPropertiesTheoreticalTable::GetBindingEnergy(), G4NucleiPropertiesTableAME12::GetBindingEnergy(), G4ParticleTable::GetParticleTable(), G4NucleiPropertiesTheoreticalTable::IsInTable(), and G4NucleiPropertiesTableAME12::IsInTable().
Referenced by G4ParticleHPInelasticBaseFS::BaseApply(), G4InuclSpecialFunctions::bindingEnergy(), G4Fancy3DNucleus::BindingEnergy(), G4StatMFMacroTriNucleon::CalcEnergy(), G4StatMFMacroTetraNucleon::CalcEnergy(), G4StatMFMacroBiNucleon::CalcEnergy(), G4StatMFMacroTetraNucleon::CalcMeanMultiplicity(), G4StatMFMacroTriNucleon::CalcMeanMultiplicity(), G4StatMFMacroBiNucleon::CalcMeanMultiplicity(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), GetBindingEnergy(), G4SigmaPlusField::GetField(), G4KaonZeroField::GetField(), G4SigmaMinusField::GetField(), G4SigmaZeroField::GetField(), G4KaonMinusField::GetField(), G4PionPlusField::GetField(), G4AntiProtonField::GetField(), G4PionZeroField::GetField(), G4KaonPlusField::GetField(), G4PionMinusField::GetField(), G4ParticleHPInelasticBaseFS::InitGammas(), G4QMDGroundStateNucleus::packNucleons(), and G4KM_OpticalEqRhs::SetFactor().
G4double G4NucleiProperties::GetBindingEnergy (const G4double A, const G4double Z) static
Definition at line 227 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 227 of file G4NucleiProperties.cc
References GetBindingEnergy().
G4double G4NucleiProperties::GetMassExcess (const G4int A, const G4int Z) static
Definition at line 174 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 174 of file G4NucleiProperties.cc
References G4cout, G4endl, G4NucleiPropertiesTheoreticalTable::GetMassExcess(), G4NucleiPropertiesTableAME12::GetMassExcess(), G4ParticleTable::GetParticleTable(), G4NucleiPropertiesTheoreticalTable::IsInTable(), G4NucleiPropertiesTableAME12::IsInTable(), and MassExcess().
Referenced by G4StatMF::CalcEnergy(), G4StatMFFragment::GetEnergy(), and GetMassExcess().
G4double G4NucleiProperties::GetMassExcess (const G4double A, const G4double Z) static
Definition at line 167 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 167 of file G4NucleiProperties.cc
References GetMassExcess().
G4double G4NucleiProperties::GetNuclearMass (const G4double A, const G4double Z) static
Definition at line 57 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 57 of file G4NucleiProperties.cc
References e, mass, and NuclearMass().
Referenced by G4LowEGammaNuclearModel::ApplyYourself(), G4ParaFissionModel::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ChargeExchange::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4EmCaptureCascade::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4EMDissociation::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4Nucleus::AtomicMass(), G4ParticleHPInelasticBaseFS::BaseApply(), G4InuclEvaporation::BreakItUp(), G4UnstableFragmentBreakUp::BreakUpChain(), G4Fragment::CalculateGroundStateMass(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4HadronicProcess::CheckResult(), G4NeutrinoNucleusModel::CoherentPion(), G4ParticleHPInelasticCompFS::CompositeApply(), G4ComponentGGNuclNuclXsc::ComputeCoulombBarier(), G4Fragment::ComputeGroundStateMass(), G4HadronElastic::ComputeMomentumCMS(), G4NuclearRadii::CoulombFactor(), G4GEMProbability::Dump(), G4CompetitiveFission::EmittedFragment(), G4NeutrinoNucleusModel::FinalBarion(), G4ElasticData::G4ElasticData(), G4EvaporationChannel::G4EvaporationChannel(), G4FermiFragment::G4FermiFragment(), G4FermiPair::G4FermiPair(), G4GEMChannel::G4GEMChannel(), G4GEMChannelVI::G4GEMChannelVI(), G4UnstableFragmentBreakUp::G4UnstableFragmentBreakUp(), G4VEmissionProbability::G4VEmissionProbability(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4IonsKoxCrossSection::GetElementCrossSection(), G4TripathiLightCrossSection::GetElementCrossSection(), G4GEMChannelVI::GetEmissionProbability(), G4EvaporationChannel::GetEmissionProbability(), G4GEMChannel::GetEmissionProbability(), G4IonsShenCrossSection::GetIsoCrossSection(), G4MuonMinusBoundDecay::GetMuonDecayRate(), G4QMDNucleus::GetNuclearMass(), G4HyperNucleiProperties::GetNuclearMass(), G4InuclNuclei::getNucleiMass(), G4IonTable::GetNucleusMass(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4FermiFragmentsPoolVI::Initialise(), G4VPreCompoundFragment::Initialize(), G4hCoulombScatteringModel::MinPrimaryEnergy(), G4eCoulombScatteringModel::MinPrimaryEnergy(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4ParticleHPContAngularPar::Sample(), G4AntiNuclElastic::SampleInvariantT(), G4NuclNuclDiffuseElastic::SampleInvariantT(), G4DiffuseElasticV2::SampleInvariantT(), G4DiffuseElastic::SampleInvariantT(), G4BetheHeitler5DModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4ScreeningMottCrossSection::SetupKinematic(), G4PhotoNuclearCrossSection::ThresholdEnergy(), and G4ElectroNuclearCrossSection::ThresholdEnergy().
G4double G4NucleiProperties::GetNuclearMass (const G4int A, const G4int Z) static
Definition at line 74 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 74 of file G4NucleiProperties.cc
References G4ParticleTable::FindParticle(), G4cout, G4endl, G4NucleiPropertiesTheoreticalTable::GetNuclearMass(), G4NucleiPropertiesTableAME12::GetNuclearMass(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4NucleiPropertiesTheoreticalTable::IsInTable(), G4NucleiPropertiesTableAME12::IsInTable(), mass, mass_alpha, mass_deuteron, mass_He3, mass_neutron, mass_proton, mass_triton, and NuclearMass().
G4bool G4NucleiProperties::IsInStableTable (const G4double A, const G4double Z) static
Definition at line 145 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 145 of file G4NucleiProperties.cc
Referenced by G4PhotoNuclearCrossSection::ThresholdEnergy(), and G4ElectroNuclearCrossSection::ThresholdEnergy().
G4bool G4NucleiProperties::IsInStableTable (const G4int A, const G4int Z) static
Definition at line 152 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 152 of file G4NucleiProperties.cc
References G4cout, G4endl, G4ParticleTable::GetParticleTable(), and G4NucleiPropertiesTableAME12::IsInTable().
G4double G4NucleiProperties::MassExcess (G4double A, G4double Z) static private
Definition at line 257 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 257 of file G4NucleiProperties.cc
References source.hepunit::amu_c2, and GetAtomicMass().
Referenced by GetMassExcess().
G4double G4NucleiProperties::NuclearMass (G4double A, G4double Z) static private
Definition at line 274 of file G4NucleiProperties.cc.
View newest version in sPHENIX GitHub at line 274 of file G4NucleiProperties.cc
References AtomicMass(), e, source.hepunit::electron_mass_c2, eV, G4cout, G4endl, G4ParticleTable::GetParticleTable(), and mass.
Referenced by GetNuclearMass().
Member Data Documentation
G4ThreadLocal G4double G4NucleiProperties::electronMass[MaxZ] static private
Definition at line 98 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 98 of file G4NucleiProperties.hh
G4ThreadLocal G4bool G4NucleiProperties::isIntialized static private
Definition at line 101 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 101 of file G4NucleiProperties.hh
G4ThreadLocal G4double G4NucleiProperties::mass_alpha = -1. static private
Definition at line 106 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 106 of file G4NucleiProperties.hh
Referenced by GetNuclearMass().
G4ThreadLocal G4double G4NucleiProperties::mass_deuteron = -1. static private
Definition at line 104 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 104 of file G4NucleiProperties.hh
Referenced by GetNuclearMass().
G4ThreadLocal G4double G4NucleiProperties::mass_He3 = -1. static private
Definition at line 107 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 107 of file G4NucleiProperties.hh
Referenced by GetNuclearMass().
G4ThreadLocal G4double G4NucleiProperties::mass_neutron = -1. static private
Definition at line 103 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 103 of file G4NucleiProperties.hh
Referenced by GetNuclearMass().
G4ThreadLocal G4double G4NucleiProperties::mass_proton = -1. static private
Definition at line 102 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 102 of file G4NucleiProperties.hh
Referenced by GetNuclearMass().
G4ThreadLocal G4double G4NucleiProperties::mass_triton = -1. static private
Definition at line 105 of file G4NucleiProperties.hh.
View newest version in sPHENIX GitHub at line 105 of file G4NucleiProperties.hh
Referenced by GetNuclearMass().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4NucleiProperties.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4NucleiProperties.cc