ECCE @ EIC Software: G4HadDecayGenerator Class Reference
G4HadDecayGenerator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4HadDecayGenerator.hh>
Public Types
enum Algorithm { NONE =0, Kopylov =1, GENBOD =2, NBody =3 }
Public Member Functions
G4HadDecayGenerator (Algorithm alg=Kopylov, G4int verbose=0)
G4HadDecayGenerator (G4VHadDecayAlgorithm *alg, G4int verbose=0)
virtual ~G4HadDecayGenerator ()
void SetVerboseLevel (G4int verbose)
const G4String & GetAlgorithmName () const
G4bool Generate (G4double initialMass, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)
G4bool Generate (const G4ParticleDefinition *initialPD, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)
G4bool Generate (const G4LorentzVector &initialState, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState)
Protected Member Functions
G4bool GenerateOneBody (G4double initialMass, const std::vector< G4double > &masses, std::vector< G4LorentzVector > &finalState) const
void ReportInvalidAlgorithm (Algorithm alg) const
void ReportMissingAlgorithm () const
void UseAlgorithm (G4VHadDecayAlgorithm *alg)
Protected Attributes
G4int verboseLevel
G4VHadDecayAlgorithm * theAlgorithm
Detailed Description
Definition at line 49 of file G4HadDecayGenerator.hh.
View newest version in sPHENIX GitHub at line 49 of file G4HadDecayGenerator.hh
Member Enumeration Documentation
enum G4HadDecayGenerator::Algorithm
Enumerator:
NONE
Kopylov
GENBOD
NBody
Definition at line 52 of file G4HadDecayGenerator.hh.
View newest version in sPHENIX GitHub at line 52 of file G4HadDecayGenerator.hh
Constructor & Destructor Documentation
G4HadDecayGenerator::G4HadDecayGenerator (Algorithm alg = Kopylov, G4int verbose = 0)
Definition at line 55 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 55 of file G4HadDecayGenerator.cc
References G4cout, G4endl, GENBOD, G4VHadDecayAlgorithm::GetName(), Kopylov, NBody, NONE, ReportInvalidAlgorithm(), theAlgorithm, and verboseLevel.
G4HadDecayGenerator::G4HadDecayGenerator (G4VHadDecayAlgorithm * alg, G4int verbose = 0)
Definition at line 72 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 72 of file G4HadDecayGenerator.cc
References G4cout, G4endl, G4VHadDecayAlgorithm::GetName(), theAlgorithm, and verboseLevel.
G4HadDecayGenerator::~G4HadDecayGenerator () virtual
Definition at line 82 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 82 of file G4HadDecayGenerator.cc
References theAlgorithm.
Member Function Documentation
G4bool G4HadDecayGenerator::Generate (G4double initialMass, const std::vector< G4double > & masses, std::vector< G4LorentzVector > & finalState)
Definition at line 120 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 120 of file G4HadDecayGenerator.cc
References G4cout, G4endl, G4VHadDecayAlgorithm::Generate(), GenerateOneBody(), ReportMissingAlgorithm(), theAlgorithm, and verboseLevel.
Referenced by Generate(), G4ElementaryParticleCollider::generateSCMfinalState(), and G4LightTargetCollider::SingleNucleonScattering().
G4bool G4HadDecayGenerator::Generate (const G4ParticleDefinition * initialPD, const std::vector< G4double > & masses, std::vector< G4LorentzVector > & finalState)
Definition at line 138 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 138 of file G4HadDecayGenerator.cc
References G4cout, G4endl, Generate(), G4ParticleDefinition::GetPDGMass(), and verboseLevel.
G4bool G4HadDecayGenerator::Generate (const G4LorentzVector & initialState, const std::vector< G4double > & masses, std::vector< G4LorentzVector > & finalState)
Definition at line 150 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 150 of file G4HadDecayGenerator.cc
References CLHEP::HepLorentzVector::boostVector(), G4cout, G4endl, Generate(), CLHEP::HepLorentzVector::m(), and verboseLevel.
G4bool G4HadDecayGenerator::GenerateOneBody (G4double initialMass, const std::vector< G4double > & masses, std::vector< G4LorentzVector > & finalState) const protected
Definition at line 171 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 171 of file G4HadDecayGenerator.cc
References eV, G4cout, G4endl, and verboseLevel.
Referenced by Generate().
const G4String & G4HadDecayGenerator::GetAlgorithmName () const
Definition at line 111 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 111 of file G4HadDecayGenerator.cc
References G4VHadDecayAlgorithm::GetName(), and theAlgorithm.
void G4HadDecayGenerator::ReportInvalidAlgorithm (Algorithm alg) const protected
Definition at line 90 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 90 of file G4HadDecayGenerator.cc
References G4cerr, G4endl, and verboseLevel.
Referenced by G4HadDecayGenerator().
void G4HadDecayGenerator::ReportMissingAlgorithm () const protected
Definition at line 97 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 97 of file G4HadDecayGenerator.cc
References G4cerr, G4endl, and verboseLevel.
Referenced by Generate().
void G4HadDecayGenerator::SetVerboseLevel (G4int verbose)
Definition at line 106 of file G4HadDecayGenerator.cc.
View newest version in sPHENIX GitHub at line 106 of file G4HadDecayGenerator.cc
References G4VHadDecayAlgorithm::SetVerboseLevel(), theAlgorithm, and verboseLevel.
Referenced by G4ElementaryParticleCollider::generateSCMfinalState().
void G4HadDecayGenerator::UseAlgorithm (G4VHadDecayAlgorithm * alg) inline protected
Definition at line 100 of file G4HadDecayGenerator.hh.
View newest version in sPHENIX GitHub at line 100 of file G4HadDecayGenerator.hh
References theAlgorithm.
Member Data Documentation
G4VHadDecayAlgorithm* G4HadDecayGenerator::theAlgorithm protected
Definition at line 103 of file G4HadDecayGenerator.hh.
View newest version in sPHENIX GitHub at line 103 of file G4HadDecayGenerator.hh
Referenced by G4CascadeFinalStateGenerator::Configure(), G4HadDecayGenerator(), Generate(), GetAlgorithmName(), SetVerboseLevel(), UseAlgorithm(), and ~G4HadDecayGenerator().
G4int G4HadDecayGenerator::verboseLevel protected
Definition at line 102 of file G4HadDecayGenerator.hh.
View newest version in sPHENIX GitHub at line 102 of file G4HadDecayGenerator.hh
Referenced by G4CascadeFinalStateGenerator::Configure(), G4HadDecayGenerator(), Generate(), GenerateOneBody(), ReportInvalidAlgorithm(), ReportMissingAlgorithm(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4HadDecayGenerator.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4HadDecayGenerator.cc