ECCE @ EIC Software: G4HEPEvtInterface Class Reference
G4HEPEvtInterface Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4HEPEvtInterface.hh>
Public Member Functions
G4HEPEvtInterface (const char *evfile, G4int vl=0)
~G4HEPEvtInterface ()
void GeneratePrimaryVertex (G4Event *evt)
Public Member Functions inherited from G4VPrimaryGenerator
G4VPrimaryGenerator ()
virtual ~G4VPrimaryGenerator ()
G4ThreeVector GetParticlePosition ()
G4double GetParticleTime ()
void SetParticlePosition (G4ThreeVector aPosition)
void SetParticleTime (G4double aTime)
Private Attributes
G4int vLevel
G4String fileName
std::ifstream inputFile
std::vector< G4HEPEvtParticle * > HPlist
Additional Inherited Members
Static Public Member Functions inherited from G4VPrimaryGenerator
static G4bool CheckVertexInsideWorld (const G4ThreeVector &pos)
Protected Attributes inherited from G4VPrimaryGenerator
G4ThreeVector particle_position
G4double particle_time
Detailed Description
Definition at line 77 of file G4HEPEvtInterface.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HEPEvtInterface.hh
Constructor & Destructor Documentation
G4HEPEvtInterface::G4HEPEvtInterface (const char * evfile, G4int vl = 0)
Definition at line 42 of file G4HEPEvtInterface.cc.
View newest version in sPHENIX GitHub at line 42 of file G4HEPEvtInterface.cc
References FatalException, fileName, G4cout, G4endl, G4Exception(), inputFile, G4VPrimaryGenerator::particle_position, G4VPrimaryGenerator::particle_time, and zero.
G4HEPEvtInterface::~G4HEPEvtInterface ()
Definition at line 60 of file G4HEPEvtInterface.cc.
View newest version in sPHENIX GitHub at line 60 of file G4HEPEvtInterface.cc
Member Function Documentation
void G4HEPEvtInterface::GeneratePrimaryVertex (G4Event * evt) virtual
Implements G4VPrimaryGenerator.
Definition at line 63 of file G4HEPEvtInterface.cc.
View newest version in sPHENIX GitHub at line 63 of file G4HEPEvtInterface.cc
References G4Event::AddPrimaryVertex(), FatalException, fileName, G4cout, G4endl, G4Exception(), GeV, HPlist, inputFile, particle, G4VPrimaryGenerator::particle_position, G4VPrimaryGenerator::particle_time, RunMustBeAborted, G4PrimaryParticle::SetDaughter(), G4PrimaryParticle::SetMass(), G4PrimaryParticle::SetMomentum(), G4PrimaryVertex::SetPrimary(), and vLevel.
Member Data Documentation
G4String G4HEPEvtInterface::fileName private
Definition at line 91 of file G4HEPEvtInterface.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HEPEvtInterface.hh
Referenced by G4HEPEvtInterface(), and GeneratePrimaryVertex().
std::vector<G4HEPEvtParticle*> G4HEPEvtInterface::HPlist private
Definition at line 93 of file G4HEPEvtInterface.hh.
View newest version in sPHENIX GitHub at line 93 of file G4HEPEvtInterface.hh
Referenced by GeneratePrimaryVertex().
std::ifstream G4HEPEvtInterface::inputFile private
Definition at line 92 of file G4HEPEvtInterface.hh.
View newest version in sPHENIX GitHub at line 92 of file G4HEPEvtInterface.hh
Referenced by G4HEPEvtInterface(), and GeneratePrimaryVertex().
G4int G4HEPEvtInterface::vLevel private
Definition at line 90 of file G4HEPEvtInterface.hh.
View newest version in sPHENIX GitHub at line 90 of file G4HEPEvtInterface.hh
Referenced by GeneratePrimaryVertex().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4HEPEvtInterface.hh
geant4/tree/geant4-10.6-release/source/event/src/G4HEPEvtInterface.cc