ECCE @ EIC Software: G4eBremsstrahlungSpectrum Class Reference
G4eBremsstrahlungSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4eBremsstrahlungSpectrum.hh>
Public Member Functions
G4eBremsstrahlungSpectrum (const G4DataVector &bins, const G4String &name)
~G4eBremsstrahlungSpectrum ()
G4double Probability (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const
G4double AverageEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const
G4double SampleEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell=0, const G4ParticleDefinition *pd=0) const
G4double MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z=0, const G4ParticleDefinition *pd=0) const
G4double Excitation (G4int Z, G4double kineticEnergy) const
void PrintData () const
Public Member Functions inherited from G4VEnergySpectrum
G4VEnergySpectrum ()
virtual ~G4VEnergySpectrum ()
Private Member Functions
G4double IntSpectrum (G4double xMin, G4double xMax, const G4DataVector &p) const
G4double AverageValue (G4double xMin, G4double xMax, const G4DataVector &p) const
G4double Function (G4double x, const G4DataVector &p) const
G4eBremsstrahlungSpectrum (const G4eBremsstrahlungSpectrum &)
G4eBremsstrahlungSpectrum & operator= (const G4eBremsstrahlungSpectrum &right)
Private Attributes
G4BremsstrahlungParameters * theBRparam
G4double lowestE
size_t length
G4int verbose
const G4DataVector xp
Detailed Description
Definition at line 64 of file G4eBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 64 of file G4eBremsstrahlungSpectrum.hh
Constructor & Destructor Documentation
G4eBremsstrahlungSpectrum::G4eBremsstrahlungSpectrum (const G4DataVector & bins, const G4String & name)
Definition at line 54 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 54 of file G4eBremsstrahlungSpectrum.cc
References length, theBRparam, verbose, and xp.
G4eBremsstrahlungSpectrum::~G4eBremsstrahlungSpectrum ()
Definition at line 66 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 66 of file G4eBremsstrahlungSpectrum.cc
References theBRparam.
G4eBremsstrahlungSpectrum::G4eBremsstrahlungSpectrum (const G4eBremsstrahlungSpectrum &) private
Member Function Documentation
G4double G4eBremsstrahlungSpectrum::AverageEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4VEnergySpectrum.
Definition at line 119 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 119 of file G4eBremsstrahlungSpectrum.cc
References AverageValue(), c, e, G4cout, G4endl, IntSpectrum(), length, lowestE, max, MeV, min, G4BremsstrahlungParameters::Parameter(), G4BremsstrahlungParameters::ParameterC(), theBRparam, G4InuclParticleNames::tm, verbose, x, y, and G4InuclParticleNames::z0.
G4double G4eBremsstrahlungSpectrum::AverageValue (G4double xMin, G4double xMax, const G4DataVector & p) const private
Definition at line 246 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 246 of file G4eBremsstrahlungSpectrum.cc
References k, length, max, min, sum, x1, x2, xp, z1, and z2.
Referenced by AverageEnergy().
G4double G4eBremsstrahlungSpectrum::Excitation (G4int Z, G4double kineticEnergy) const virtual
Implements G4VEnergySpectrum.
Definition at line 301 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 301 of file G4eBremsstrahlungSpectrum.cc
G4double G4eBremsstrahlungSpectrum::Function (G4double x, const G4DataVector & p) const private
Definition at line 277 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 277 of file G4eBremsstrahlungSpectrum.cc
References f, length, and xp.
Referenced by SampleEnergy().
G4double G4eBremsstrahlungSpectrum::IntSpectrum (G4double xMin, G4double xMax, const G4DataVector & p) const private
Definition at line 220 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 220 of file G4eBremsstrahlungSpectrum.cc
References k, length, max, min, sum, x1, x2, xp, z1, and z2.
Referenced by AverageEnergy(), and Probability().
G4double G4eBremsstrahlungSpectrum::MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4VEnergySpectrum.
Definition at line 306 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 306 of file G4eBremsstrahlungSpectrum.cc
G4eBremsstrahlungSpectrum& G4eBremsstrahlungSpectrum::operator= (const G4eBremsstrahlungSpectrum & right) private
void G4eBremsstrahlungSpectrum::PrintData (void) const virtual
Implements G4VEnergySpectrum.
Definition at line 298 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 298 of file G4eBremsstrahlungSpectrum.cc
References G4BremsstrahlungParameters::PrintData(), and theBRparam.
G4double G4eBremsstrahlungSpectrum::Probability (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4VEnergySpectrum.
Definition at line 72 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 72 of file G4eBremsstrahlungSpectrum.cc
References e, G4cout, G4endl, IntSpectrum(), length, lowestE, max, MeV, min, G4BremsstrahlungParameters::Parameter(), theBRparam, G4InuclParticleNames::tm, verbose, x, xp, y, and G4InuclParticleNames::z0.
G4double G4eBremsstrahlungSpectrum::SampleEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4VEnergySpectrum.
Definition at line 173 of file G4eBremsstrahlungSpectrum.cc.
View newest version in sPHENIX GitHub at line 173 of file G4eBremsstrahlungSpectrum.cc
References e, Function(), G4cout, G4endl, G4Exp(), G4UniformRand, length, lowestE, max, min, G4BremsstrahlungParameters::Parameter(), theBRparam, G4InuclParticleNames::tm, x, and xp.
Member Data Documentation
size_t G4eBremsstrahlungSpectrum::length private
Definition at line 118 of file G4eBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 118 of file G4eBremsstrahlungSpectrum.hh
Referenced by AverageEnergy(), AverageValue(), Function(), G4eBremsstrahlungSpectrum(), IntSpectrum(), Probability(), and SampleEnergy().
G4double G4eBremsstrahlungSpectrum::lowestE private
Definition at line 117 of file G4eBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 117 of file G4eBremsstrahlungSpectrum.hh
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4BremsstrahlungParameters* G4eBremsstrahlungSpectrum::theBRparam private
Definition at line 116 of file G4eBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 116 of file G4eBremsstrahlungSpectrum.hh
Referenced by AverageEnergy(), G4eBremsstrahlungSpectrum(), PrintData(), Probability(), SampleEnergy(), and ~G4eBremsstrahlungSpectrum().
G4int G4eBremsstrahlungSpectrum::verbose private
Definition at line 119 of file G4eBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 119 of file G4eBremsstrahlungSpectrum.hh
Referenced by AverageEnergy(), G4eBremsstrahlungSpectrum(), and Probability().
const G4DataVector G4eBremsstrahlungSpectrum::xp private
Definition at line 121 of file G4eBremsstrahlungSpectrum.hh.
View newest version in sPHENIX GitHub at line 121 of file G4eBremsstrahlungSpectrum.hh
Referenced by AverageValue(), Function(), G4eBremsstrahlungSpectrum(), IntSpectrum(), Probability(), and SampleEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4eBremsstrahlungSpectrum.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4eBremsstrahlungSpectrum.cc