ECCE @ EIC Software: macros/blob/master/common/G4_Tracking_EIC.C File Reference
G4_Tracking_EIC.C File Reference
#include <GlobalVariables.C>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <trackreco/PHRaveVertexing.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include <fun4all/Fun4AllServer.h>
#include <vector>
Namespaces
namespace Enable
namespace G4TRACKING
Macros
#define MACRO_G4TRACKINGEIC_C
Functions
void TrackingInit ()
void InitFastKalmanFilter (PHG4TrackFastSim *kalman_filter)
void Tracking_Reco ()
void Tracking_Eval (const std::string &outputfile)
Variables
bool Enable::TRACKING = false
bool Enable::TRACKING_EVAL = false
int Enable::TRACKING_VERBOSITY = 0
bool G4TRACKING::DISPLACED_VERTEX = false
bool G4TRACKING::PROJECTION_EEMC = false
bool G4TRACKING::PROJECTION_EHCAL = false
bool G4TRACKING::PROJECTION_CEMC = false
bool G4TRACKING::PROJECTION_BECAL = false
bool G4TRACKING::PROJECTION_HCALIN = false
bool G4TRACKING::PROJECTION_HCALOUT = false
bool G4TRACKING::PROJECTION_FEMC = false
bool G4TRACKING::PROJECTION_FHCAL = false
bool G4TRACKING::PROJECTION_LFHCAL = false
Macro Definition Documentation
#define MACRO_G4TRACKINGEIC_C
Definition at line 2 of file G4_Tracking_EIC.C.
View newest version in sPHENIX GitHub at line 2 of file G4_Tracking_EIC.C
Function Documentation
void InitFastKalmanFilter (PHG4TrackFastSim * kalman_filter)
Definition at line 48 of file G4_Tracking_EIC.C.
View newest version in sPHENIX GitHub at line 48 of file G4_Tracking_EIC.C
References G4TRACKING::DISPLACED_VERTEX, e, PHG4TrackFastSim::enable_vertexing(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_xy_resolution(), and PHG4TrackFastSim::set_vertex_z_resolution().
void Tracking_Eval (const std::string & outputfile)
Definition at line 196 of file G4_Tracking_EIC.C.
View newest version in sPHENIX GitHub at line 196 of file G4_Tracking_EIC.C
References PHG4TrackFastSimEval::AddProjection(), Fun4AllServer::instance(), max, proj, TRACKING::ProjectionNames, Fun4AllServer::registerSubsystem(), PHG4TrackFastSimEval::set_filename(), PHG4TrackFastSimEval::set_trackmapname(), Enable::TRACKING_VERBOSITY, TRACKING::TrackNodeName, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), Fun4All_G4_sPHENIX(), and Fun4All_runEvaluators().
void Tracking_Reco ()
Definition at line 73 of file G4_Tracking_EIC.C.
View newest version in sPHENIX GitHub at line 73 of file G4_Tracking_EIC.C
References PHG4TrackFastSim::add_state_name(), Enable::BECAL, Enable::CEMC, Enable::EEMC, Enable::EEMCH, Enable::EHCAL, PHG4TrackFastSim::enable_vertexing(), g4zmq::exit(), TRACKING::FastKalmanFilter(), TRACKING::FastKalmanFilterInnerTrack(), TRACKING::FastKalmanFilterSiliconTrack(), Enable::FEMC, Enable::FHCAL, Enable::HCALIN, Enable::HCALOUT, InitFastKalmanFilter(), Fun4AllServer::instance(), Enable::LFHCAL, max, G4TRACKING::PROJECTION_BECAL, G4TRACKING::PROJECTION_CEMC, G4TRACKING::PROJECTION_EEMC, G4TRACKING::PROJECTION_EHCAL, G4TRACKING::PROJECTION_FEMC, G4TRACKING::PROJECTION_FHCAL, G4TRACKING::PROJECTION_HCALIN, G4TRACKING::PROJECTION_HCALOUT, G4TRACKING::PROJECTION_LFHCAL, TRACKING::ProjectionNames, Fun4AllServer::registerSubsystem(), PHG4TrackFastSim::set_trackmap_out_name(), Enable::TRACKING_VERBOSITY, TRACKING::TrackNodeName, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_AnaTutorial(), and Fun4All_G4_sPHENIX().
void TrackingInit ()
Definition at line 41 of file G4_Tracking_EIC.C.
View newest version in sPHENIX GitHub at line 41 of file G4_Tracking_EIC.C
References TRACKING::FastKalmanFilter(), TRACKING::FastKalmanFilterInnerTrack(), and TRACKING::FastKalmanFilterSiliconTrack().
Referenced by Fun4All_AnaTutorial_sPHENIX(), Fun4All_AnaTutorial_sPHENIX_Jets(), Fun4All_G4_sPHENIX(), and G4Init().