ECCE @ EIC Software: G4SchedulerMessenger Class Reference
G4SchedulerMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4SchedulerMessenger.hh>
Public Member Functions
G4SchedulerMessenger (G4Scheduler *runMgr)
~G4SchedulerMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4Scheduler * fScheduler
G4UIdirectory * fITDirectory
G4UIcmdWithADoubleAndUnit * fEndTime
G4UIcmdWithADoubleAndUnit * fTimeTolerance
G4UIcmdWithAnInteger * fVerboseCmd
G4UIcmdWithAnInteger * fMaxStepNumber
G4UIcmdWithoutParameter * fInitCmd
G4UIcmdWithoutParameter * fProcessCmd
G4UIcmdWithAnInteger * fMaxNULLTimeSteps
G4UIcmdWithoutParameter * fWhyDoYouStop
G4UIcmdWithABool * fUseDefaultTimeSteps
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 65 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file G4SchedulerMessenger.hh
Constructor & Destructor Documentation
G4SchedulerMessenger::G4SchedulerMessenger (G4Scheduler * runMgr)
Definition at line 46 of file G4SchedulerMessenger.cc.
View newest version in sPHENIX GitHub at line 46 of file G4SchedulerMessenger.cc
References G4UIcommand::AvailableForStates(), fEndTime, fInitCmd, fITDirectory, fMaxNULLTimeSteps, fMaxStepNumber, fProcessCmd, fTimeTolerance, fUseDefaultTimeSteps, fVerboseCmd, fWhyDoYouStop, G4State_Idle, G4State_PreInit, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcommand::SetRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
G4SchedulerMessenger::~G4SchedulerMessenger ()
Definition at line 121 of file G4SchedulerMessenger.cc.
View newest version in sPHENIX GitHub at line 121 of file G4SchedulerMessenger.cc
References fEndTime, fInitCmd, fITDirectory, fMaxNULLTimeSteps, fMaxStepNumber, fProcessCmd, fTimeTolerance, fUseDefaultTimeSteps, fVerboseCmd, and fWhyDoYouStop.
Member Function Documentation
G4String G4SchedulerMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 178 of file G4SchedulerMessenger.cc.
View newest version in sPHENIX GitHub at line 178 of file G4SchedulerMessenger.cc
References G4Scheduler::AreDefaultTimeStepsUsed(), G4UIcommand::ConvertToString(), fEndTime, fInitCmd, fMaxNULLTimeSteps, fMaxStepNumber, fScheduler, fTimeTolerance, fUseDefaultTimeSteps, fVerboseCmd, G4Scheduler::GetEndTime(), G4Scheduler::GetMaxNbSteps(), G4Scheduler::GetMaxZeroTimeAllowed(), G4Scheduler::GetTimeTolerance(), G4Scheduler::GetVerbose(), and G4Scheduler::IsInitialized().
void G4SchedulerMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 135 of file G4SchedulerMessenger.cc.
View newest version in sPHENIX GitHub at line 135 of file G4SchedulerMessenger.cc
References fEndTime, fInitCmd, fMaxNULLTimeSteps, fMaxStepNumber, fProcessCmd, fScheduler, fTimeTolerance, fUseDefaultTimeSteps, fVerboseCmd, fWhyDoYouStop, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4Scheduler::Initialize(), G4Scheduler::Process(), G4Scheduler::SetEndTime(), G4Scheduler::SetMaxNbSteps(), G4Scheduler::SetMaxZeroTimeAllowed(), G4Scheduler::SetTimeTolerance(), G4Scheduler::SetVerbose(), G4Scheduler::UseDefaultTimeSteps(), and G4Scheduler::WhyDoYouStop().
Member Data Documentation
G4UIcmdWithADoubleAndUnit* G4SchedulerMessenger::fEndTime private
Definition at line 81 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), GetCurrentValue(), SetNewValue(), and ~G4SchedulerMessenger().
G4UIcmdWithoutParameter* G4SchedulerMessenger::fInitCmd private
Definition at line 85 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), GetCurrentValue(), SetNewValue(), and ~G4SchedulerMessenger().
G4UIdirectory* G4SchedulerMessenger::fITDirectory private
Definition at line 79 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), and ~G4SchedulerMessenger().
G4UIcmdWithAnInteger* G4SchedulerMessenger::fMaxNULLTimeSteps private
Definition at line 87 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), GetCurrentValue(), SetNewValue(), and ~G4SchedulerMessenger().
G4UIcmdWithAnInteger* G4SchedulerMessenger::fMaxStepNumber private
Definition at line 84 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), GetCurrentValue(), SetNewValue(), and ~G4SchedulerMessenger().
G4UIcmdWithoutParameter* G4SchedulerMessenger::fProcessCmd private
Definition at line 86 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 86 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), SetNewValue(), and ~G4SchedulerMessenger().
G4Scheduler* G4SchedulerMessenger::fScheduler private
Definition at line 76 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4SchedulerMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIcmdWithADoubleAndUnit* G4SchedulerMessenger::fTimeTolerance private
Definition at line 82 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), GetCurrentValue(), SetNewValue(), and ~G4SchedulerMessenger().
G4UIcmdWithABool* G4SchedulerMessenger::fUseDefaultTimeSteps private
Definition at line 89 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), GetCurrentValue(), SetNewValue(), and ~G4SchedulerMessenger().
G4UIcmdWithAnInteger* G4SchedulerMessenger::fVerboseCmd private
Definition at line 83 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), GetCurrentValue(), SetNewValue(), and ~G4SchedulerMessenger().
G4UIcmdWithoutParameter* G4SchedulerMessenger::fWhyDoYouStop private
Definition at line 88 of file G4SchedulerMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4SchedulerMessenger.hh
Referenced by G4SchedulerMessenger(), SetNewValue(), and ~G4SchedulerMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4SchedulerMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4SchedulerMessenger.cc