ECCE @ EIC Software: G4AntiProtonField Class Reference
G4AntiProtonField Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4AntiProtonField.hh>
Public Member Functions
G4AntiProtonField (G4V3DNucleus *nucleus, G4double coeff=1.53 *CLHEP::fermi)
virtual ~G4AntiProtonField ()
virtual G4double GetField (const G4ThreeVector &aPosition)
virtual G4double GetBarrier ()
virtual G4double GetCoeff ()
Public Member Functions inherited from G4VNuclearField
G4VNuclearField (G4V3DNucleus *aNucleus=0)
virtual ~G4VNuclearField ()
void SetNucleus (G4V3DNucleus *aNucleus)
Private Member Functions
G4AntiProtonField (const G4AntiProtonField &right)
const G4AntiProtonField & operator= (const G4AntiProtonField &right)
G4bool operator== (const G4AntiProtonField &right) const
G4bool operator!= (const G4AntiProtonField &right) const
Private Attributes
G4double theCoeff
Additional Inherited Members
Protected Attributes inherited from G4VNuclearField
G4V3DNucleus * theNucleus
const G4double radius
Detailed Description
Definition at line 47 of file G4AntiProtonField.hh.
View newest version in sPHENIX GitHub at line 47 of file G4AntiProtonField.hh
Constructor & Destructor Documentation
G4AntiProtonField::G4AntiProtonField (G4V3DNucleus * nucleus, G4double coeff = 1.53*CLHEP::fermi)
Definition at line 50 of file G4AntiProtonField.cc.
View newest version in sPHENIX GitHub at line 50 of file G4AntiProtonField.cc
References theCoeff.
G4AntiProtonField::~G4AntiProtonField () virtual
Definition at line 57 of file G4AntiProtonField.cc.
View newest version in sPHENIX GitHub at line 57 of file G4AntiProtonField.cc
G4AntiProtonField::G4AntiProtonField (const G4AntiProtonField & right) private
Member Function Documentation
G4double G4AntiProtonField::GetBarrier () virtual
Implements G4VNuclearField.
Definition at line 83 of file G4AntiProtonField.cc.
View newest version in sPHENIX GitHub at line 83 of file G4AntiProtonField.cc
References A(), G4V3DNucleus::GetCharge(), G4Pow::GetInstance(), G4V3DNucleus::GetMassNumber(), MeV, G4VNuclearField::theNucleus, Z, and G4Pow::Z13().
Referenced by GetField().
virtual G4double G4AntiProtonField::GetCoeff () inline virtual
Reimplemented from G4VNuclearField.
Definition at line 62 of file G4AntiProtonField.hh.
View newest version in sPHENIX GitHub at line 62 of file G4AntiProtonField.hh
References theCoeff.
G4double G4AntiProtonField::GetField (const G4ThreeVector & aPosition) virtual
Implements G4VNuclearField.
Definition at line 63 of file G4AntiProtonField.cc.
View newest version in sPHENIX GitHub at line 63 of file G4AntiProtonField.cc
References A(), G4AntiProton::AntiProtonDefinition(), G4InuclSpecialFunctions::bindingEnergy(), GetBarrier(), G4NucleiProperties::GetBindingEnergy(), G4V3DNucleus::GetCharge(), G4VNuclearDensity::GetDensity(), G4V3DNucleus::GetMassNumber(), G4V3DNucleus::GetNuclearDensity(), G4ParticleDefinition::GetPDGMass(), source.hepunit::hbarc, CLHEP::Hep3Vector::mag(), source.hepunit::neutron_mass_c2, pi, source.hepunit::proton_mass_c2, G4VNuclearField::radius, theCoeff, G4VNuclearField::theNucleus, and Z.
G4bool G4AntiProtonField::operator!= (const G4AntiProtonField & right) const private
const G4AntiProtonField& G4AntiProtonField::operator= (const G4AntiProtonField & right) private
G4bool G4AntiProtonField::operator== (const G4AntiProtonField & right) const private
Member Data Documentation
G4double G4AntiProtonField::theCoeff private
Definition at line 65 of file G4AntiProtonField.hh.
View newest version in sPHENIX GitHub at line 65 of file G4AntiProtonField.hh
Referenced by G4AntiProtonField(), GetCoeff(), and GetField().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/include/G4AntiProtonField.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/binary_cascade/src/G4AntiProtonField.cc