ECCE @ EIC Software: G4EnvSettings Class Reference
G4EnvSettings Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4EnvironmentUtils.hh>
Public Types
typedef std::string string_t
typedef std::map< string_t,
string_t > env_map_t
typedef std::pair< string_t,
string_t > env_pair_t
Public Member Functions
template<typename _Tp >
void insert (const std::string &env_id, _Tp val)
const env_map_t & get () const
Static Public Member Functions
static G4EnvSettings * GetInstance ()
Private Attributes
env_map_t m_env
Friends
std::ostream & operator<< (std::ostream &os, const G4EnvSettings &env)
Detailed Description
Definition at line 59 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 59 of file G4EnvironmentUtils.hh
Member Typedef Documentation
typedef std::map<string_t, string_t> G4EnvSettings::env_map_t
Definition at line 66 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 66 of file G4EnvironmentUtils.hh
typedef std::pair<string_t, string_t> G4EnvSettings::env_pair_t
Definition at line 67 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 67 of file G4EnvironmentUtils.hh
typedef std::string G4EnvSettings::string_t
Definition at line 65 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 65 of file G4EnvironmentUtils.hh
Member Function Documentation
const env_map_t& G4EnvSettings::get (void) const inline
Definition at line 90 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 90 of file G4EnvironmentUtils.hh
References m_env.
static G4EnvSettings* G4EnvSettings::GetInstance (void) inline static
Definition at line 70 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 70 of file G4EnvironmentUtils.hh
Referenced by G4GetDataEnv(), G4GetEnv(), and G4PrintEnv().
template<typename _Tp > void G4EnvSettings::insert (const std::string & env_id, _Tp val) inline
Definition at line 78 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 78 of file G4EnvironmentUtils.hh
References m_env, and G4AttDefStore::mutex.
Referenced by G4GetDataEnv(), and G4GetEnv().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4EnvSettings & env) friend
Definition at line 92 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 92 of file G4EnvironmentUtils.hh
Member Data Documentation
env_map_t G4EnvSettings::m_env private
Definition at line 110 of file G4EnvironmentUtils.hh.
View newest version in sPHENIX GitHub at line 110 of file G4EnvironmentUtils.hh
Referenced by get(), and insert().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/management/include/G4EnvironmentUtils.hh