ECCE @ EIC Software: CLHEP::HepRotationX Class Reference
CLHEP::HepRotationX Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/RotationX.h>
Public Member Functions
HepRotationX ()
HepRotationX (double delta)
HepRotationX (const HepRotationX &orig)
HepRotationX (HepRotationX &&orig)=default
HepRotationX & operator= (const HepRotationX &r)
HepRotationX & operator= (HepRotationX &&r)=default
HepRotationX & set (double delta)
~HepRotationX ()
Hep3Vector colX () const
Hep3Vector colY () const
Hep3Vector colZ () const
Hep3Vector rowX () const
Hep3Vector rowY () const
Hep3Vector rowZ () const
double xx () const
double xy () const
double xz () const
double yx () const
double yy () const
double yz () const
double zx () const
double zy () const
double zz () const
HepRep3x3 rep3x3 () const
double getPhi () const
double getTheta () const
double getPsi () const
double phi () const
double theta () const
double psi () const
HepEulerAngles eulerAngles () const
double getDelta () const
Hep3Vector getAxis () const
double delta () const
Hep3Vector axis () const
HepAxisAngle axisAngle () const
void getAngleAxis (double &delta, Hep3Vector &axis) const
double phiX () const
double phiY () const
double phiZ () const
double thetaX () const
double thetaY () const
double thetaZ () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
double xt () const
double yt () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepRep4x4 rep4x4 () const
void setDelta (double delta)
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
void decompose (HepRotation &rotation, HepBoost &boost) const
void decompose (HepBoost &boost, HepRotation &rotation) const
bool isIdentity () const
int compare (const HepRotationX &r) const
bool operator== (const HepRotationX &r) const
bool operator!= (const HepRotationX &r) const
bool operator< (const HepRotationX &r) const
bool operator> (const HepRotationX &r) const
bool operator<= (const HepRotationX &r) const
bool operator>= (const HepRotationX &r) const
double distance2 (const HepRotationX &r) const
double distance2 (const HepRotation &r) const
double howNear (const HepRotationX &r) const
double howNear (const HepRotation &r) const
bool isNear (const HepRotationX &r, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
double distance2 (const HepBoost &lt) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoost &lt) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoost &lt, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
Hep3Vector operator() (const Hep3Vector &p) const
Hep3Vector operator* (const Hep3Vector &p) const
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &w) const
HepRotationX operator* (const HepRotationX &rx) const
HepRotationX & operator*= (const HepRotationX &r)
HepRotationX & transform (const HepRotationX &r)
HepRotationX inverse () const
HepRotationX & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Protected Member Functions
HepRotationX (double dd, double ss, double cc)
Static Protected Member Functions
static double proper (double delta)
Protected Attributes
double its_d
double its_s
double its_c
Friends
HepRotationX inverseOf (const HepRotationX &r)
Detailed Description
Author
Definition at line 43 of file RotationX.h.
View newest version in sPHENIX GitHub at line 43 of file RotationX.h
Constructor & Destructor Documentation
CLHEP::HepRotationX::HepRotationX () inline
CLHEP::HepRotationX::HepRotationX (double delta)
Definition at line 31 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 31 of file RotationX.cc
CLHEP::HepRotationX::HepRotationX (const HepRotationX & orig) inline
CLHEP::HepRotationX::HepRotationX (HepRotationX && orig) inline default
CLHEP::HepRotationX::~HepRotationX () inline
CLHEP::HepRotationX::HepRotationX (double dd, double ss, double cc) inline protected
Member Function Documentation
Hep3Vector CLHEP::HepRotationX::axis () const inline
HepAxisAngle CLHEP::HepRotationX::axisAngle () const inline
HepLorentzVector CLHEP::HepRotationX::col1 () const inline
HepLorentzVector CLHEP::HepRotationX::col2 () const inline
HepLorentzVector CLHEP::HepRotationX::col3 () const inline
HepLorentzVector CLHEP::HepRotationX::col4 () const inline
Hep3Vector CLHEP::HepRotationX::colX () const inline
Hep3Vector CLHEP::HepRotationX::colY () const inline
Hep3Vector CLHEP::HepRotationX::colZ () const inline
int CLHEP::HepRotationX::compare (const HepRotationX & r) const inline
void CLHEP::HepRotationX::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 108 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 108 of file RotationX.cc
References CLHEP::Hep3Vector::set().
void CLHEP::HepRotationX::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 114 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 114 of file RotationX.cc
References CLHEP::Hep3Vector::set().
void CLHEP::HepRotationX::decompose (HepRotation & rotation, HepBoost & boost) const
Definition at line 120 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 120 of file RotationX.cc
References CLHEP::HepBoost::set().
void CLHEP::HepRotationX::decompose (HepBoost & boost, HepRotation & rotation) const
Definition at line 126 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 126 of file RotationX.cc
References CLHEP::HepBoost::set().
double CLHEP::HepRotationX::delta () const inline
double CLHEP::HepRotationX::distance2 (const HepRotationX & r) const
Definition at line 131 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 131 of file RotationX.cc
References its_c, and its_s.
Referenced by distance2(), howNear(), and isNear().
double CLHEP::HepRotationX::distance2 (const HepRotation & r) const
Definition at line 136 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 136 of file RotationX.cc
References sum, CLHEP::HepRotation::xx(), yy(), CLHEP::HepRotation::yy(), yz(), CLHEP::HepRotation::yz(), zy(), CLHEP::HepRotation::zy(), zz(), and CLHEP::HepRotation::zz().
double CLHEP::HepRotationX::distance2 (const HepBoost & lt) const
Definition at line 154 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 154 of file RotationX.cc
References distance2().
double CLHEP::HepRotationX::distance2 (const HepLorentzRotation & lt) const
Definition at line 144 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 144 of file RotationX.cc
References a, b, CLHEP::Hep3Vector::beta(), CLHEP::HepLorentzRotation::decompose(), distance2(), and r.
HepEulerAngles CLHEP::HepRotationX::eulerAngles () const
Definition at line 62 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 62 of file RotationX.cc
References phi(), psi(), and theta().
void CLHEP::HepRotationX::getAngleAxis (double & delta, Hep3Vector & axis) const inline
Hep3Vector CLHEP::HepRotationX::getAxis () const inline
double CLHEP::HepRotationX::getDelta () const inline
double CLHEP::HepRotationX::getPhi () const inline
double CLHEP::HepRotationX::getPsi () const inline
double CLHEP::HepRotationX::getTheta () const inline
static double CLHEP::HepRotationX::getTolerance () inline static
double CLHEP::HepRotationX::howNear (const HepRotationX & r) const
Definition at line 158 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 158 of file RotationX.cc
References distance2().
double CLHEP::HepRotationX::howNear (const HepRotation & r) const
Definition at line 161 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 161 of file RotationX.cc
References distance2().
double CLHEP::HepRotationX::howNear (const HepBoost & lt) const
Definition at line 164 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 164 of file RotationX.cc
References distance2().
double CLHEP::HepRotationX::howNear (const HepLorentzRotation & lt) const
Definition at line 167 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 167 of file RotationX.cc
References distance2().
HepRotationX CLHEP::HepRotationX::inverse () const inline
HepRotationX& CLHEP::HepRotationX::invert () inline
bool CLHEP::HepRotationX::isIdentity () const inline
bool CLHEP::HepRotationX::isNear (const HepRotationX & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 170 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 170 of file RotationX.cc
References distance2().
bool CLHEP::HepRotationX::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 173 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 173 of file RotationX.cc
References distance2().
bool CLHEP::HepRotationX::isNear (const HepBoost & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 176 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 176 of file RotationX.cc
References distance2().
bool CLHEP::HepRotationX::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 180 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 180 of file RotationX.cc
References distance2().
double CLHEP::HepRotationX::norm2 () const
Definition at line 185 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 185 of file RotationX.cc
References its_c.
bool CLHEP::HepRotationX::operator!= (const HepRotationX & r) const inline
Hep3Vector CLHEP::HepRotationX::operator() (const Hep3Vector & p) const inline
HepLorentzVector CLHEP::HepRotationX::operator() (const HepLorentzVector & w) const inline
Hep3Vector CLHEP::HepRotationX::operator* (const Hep3Vector & p) const inline
HepLorentzVector CLHEP::HepRotationX::operator* (const HepLorentzVector & w) const inline
HepRotationX CLHEP::HepRotationX::operator* (const HepRotationX & rx) const inline
HepRotationX& CLHEP::HepRotationX::operator*= (const HepRotationX & r) inline
bool CLHEP::HepRotationX::operator< (const HepRotationX & r) const inline
bool CLHEP::HepRotationX::operator<= (const HepRotationX & r) const inline
HepRotationX& CLHEP::HepRotationX::operator= (const HepRotationX & r) inline
HepRotationX& CLHEP::HepRotationX::operator= (HepRotationX && r) inline default
bool CLHEP::HepRotationX::operator== (const HepRotationX & r) const inline
bool CLHEP::HepRotationX::operator> (const HepRotationX & r) const inline
bool CLHEP::HepRotationX::operator>= (const HepRotationX & r) const inline
double CLHEP::HepRotationX::phi () const
Definition at line 42 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 42 of file RotationX.cc
References its_d, and CLHEP::pi.
Referenced by eulerAngles().
double CLHEP::HepRotationX::phiX () const
Definition at line 74 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 74 of file RotationX.cc
References xx(), and yx().
double CLHEP::HepRotationX::phiY () const
Definition at line 79 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 79 of file RotationX.cc
References xy(), and yy().
double CLHEP::HepRotationX::phiZ () const
Definition at line 84 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 84 of file RotationX.cc
References xz(), and yz().
std::ostream & CLHEP::HepRotationX::print (std::ostream & os) const
Definition at line 189 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 189 of file RotationX.cc
References its_c, its_d, and its_s.
static double CLHEP::HepRotationX::proper (double delta) inline static protected
Referenced by set().
double CLHEP::HepRotationX::psi () const
Definition at line 54 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 54 of file RotationX.cc
References its_d, and CLHEP::pi.
Referenced by eulerAngles().
void CLHEP::HepRotationX::rectify () inline
HepRep3x3 CLHEP::HepRotationX::rep3x3 () const inline
HepRep4x4 CLHEP::HepRotationX::rep4x4 () const inline
HepLorentzVector CLHEP::HepRotationX::row1 () const inline
HepLorentzVector CLHEP::HepRotationX::row2 () const inline
HepLorentzVector CLHEP::HepRotationX::row3 () const inline
HepLorentzVector CLHEP::HepRotationX::row4 () const inline
Hep3Vector CLHEP::HepRotationX::rowX () const inline
Hep3Vector CLHEP::HepRotationX::rowY () const inline
Hep3Vector CLHEP::HepRotationX::rowZ () const inline
HepRotationX & CLHEP::HepRotationX::set (double delta)
Definition at line 35 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 35 of file RotationX.cc
References its_c, its_d, its_s, and proper().
void CLHEP::HepRotationX::setDelta (double delta)
Definition at line 103 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 103 of file RotationX.cc
static double CLHEP::HepRotationX::setTolerance (double tol) inline static
double CLHEP::HepRotationX::theta () const
Definition at line 50 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 50 of file RotationX.cc
References its_d.
Referenced by eulerAngles().
double CLHEP::HepRotationX::thetaX () const
Definition at line 89 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 89 of file RotationX.cc
References CLHEP::safe_acos(), and zx().
double CLHEP::HepRotationX::thetaY () const
Definition at line 94 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 94 of file RotationX.cc
References CLHEP::safe_acos(), and zy().
double CLHEP::HepRotationX::thetaZ () const
Definition at line 98 of file RotationX.cc.
View newest version in sPHENIX GitHub at line 98 of file RotationX.cc
References CLHEP::safe_acos(), and zz().
HepRotationX& CLHEP::HepRotationX::transform (const HepRotationX & r) inline
double CLHEP::HepRotationX::tt () const inline
double CLHEP::HepRotationX::tx () const inline
double CLHEP::HepRotationX::ty () const inline
double CLHEP::HepRotationX::tz () const inline
double CLHEP::HepRotationX::xt () const inline
double CLHEP::HepRotationX::xx () const inline
Referenced by phiX().
double CLHEP::HepRotationX::xy () const inline
Referenced by phiY().
double CLHEP::HepRotationX::xz () const inline
Referenced by phiZ().
double CLHEP::HepRotationX::yt () const inline
double CLHEP::HepRotationX::yx () const inline
Referenced by phiX().
double CLHEP::HepRotationX::yy () const inline
Referenced by distance2(), and phiY().
double CLHEP::HepRotationX::yz () const inline
Referenced by distance2(), and phiZ().
double CLHEP::HepRotationX::zt () const inline
double CLHEP::HepRotationX::zx () const inline
Referenced by thetaX().
double CLHEP::HepRotationX::zy () const inline
Referenced by distance2(), and thetaY().
double CLHEP::HepRotationX::zz () const inline
Referenced by distance2(), and thetaZ().
Friends And Related Function Documentation
HepRotationX inverseOf (const HepRotationX & r) friend
Member Data Documentation
double CLHEP::HepRotationX::its_c protected
Definition at line 266 of file RotationX.h.
View newest version in sPHENIX GitHub at line 266 of file RotationX.h
Referenced by distance2(), norm2(), print(), and set().
double CLHEP::HepRotationX::its_d protected
Definition at line 262 of file RotationX.h.
View newest version in sPHENIX GitHub at line 262 of file RotationX.h
Referenced by phi(), print(), psi(), set(), and theta().
double CLHEP::HepRotationX::its_s protected
Definition at line 265 of file RotationX.h.
View newest version in sPHENIX GitHub at line 265 of file RotationX.h
Referenced by distance2(), print(), and set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/RotationX.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationX.cc