ECCE @ EIC Software: G4AnalyticalPolSolver Class Reference
G4AnalyticalPolSolver Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4AnalyticalPolSolver.hh>
Public Member Functions
G4AnalyticalPolSolver ()
~G4AnalyticalPolSolver ()
G4int QuadRoots (G4double p[5], G4double r[3][5])
G4int CubicRoots (G4double p[5], G4double r[3][5])
G4int BiquadRoots (G4double p[5], G4double r[3][5])
G4int QuarticRoots (G4double p[5], G4double r[3][5])
Detailed Description
Definition at line 63 of file G4AnalyticalPolSolver.hh.
View newest version in sPHENIX GitHub at line 63 of file G4AnalyticalPolSolver.hh
Constructor & Destructor Documentation
G4AnalyticalPolSolver::G4AnalyticalPolSolver ()
Definition at line 36 of file G4AnalyticalPolSolver.cc.
View newest version in sPHENIX GitHub at line 36 of file G4AnalyticalPolSolver.cc
G4AnalyticalPolSolver::~G4AnalyticalPolSolver ()
Definition at line 40 of file G4AnalyticalPolSolver.cc.
View newest version in sPHENIX GitHub at line 40 of file G4AnalyticalPolSolver.cc
Member Function Documentation
G4int G4AnalyticalPolSolver::BiquadRoots (G4double p[5], G4double r[3][5])
Definition at line 171 of file G4AnalyticalPolSolver.cc.
View newest version in sPHENIX GitHub at line 171 of file G4AnalyticalPolSolver.cc
References a, b, c, CubicRoots(), d, e, k, and QuadRoots().
G4int G4AnalyticalPolSolver::CubicRoots (G4double p[5], G4double r[3][5])
Definition at line 84 of file G4AnalyticalPolSolver.cc.
View newest version in sPHENIX GitHub at line 84 of file G4AnalyticalPolSolver.cc
References b, c, d, k, t, and x.
Referenced by BiquadRoots(), and QuarticRoots().
G4int G4AnalyticalPolSolver::QuadRoots (G4double p[5], G4double r[3][5])
Definition at line 49 of file G4AnalyticalPolSolver.cc.
View newest version in sPHENIX GitHub at line 49 of file G4AnalyticalPolSolver.cc
References b, c, d, and d2.
Referenced by BiquadRoots().
G4int G4AnalyticalPolSolver::QuarticRoots (G4double p[5], G4double r[3][5])
Definition at line 271 of file G4AnalyticalPolSolver.cc.
View newest version in sPHENIX GitHub at line 271 of file G4AnalyticalPolSolver.cc
References a, a0, b, c, CubicRoots(), D(), d, DBL_MAX, E, k, Acts::IntegrationTest::R, and y1.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/HEPNumerics/include/G4AnalyticalPolSolver.hh
geant4/tree/geant4-10.6-release/source/global/HEPNumerics/src/G4AnalyticalPolSolver.cc