ECCE @ EIC Software: G4NavigationHistoryPool Class Reference
G4NavigationHistoryPool Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4NavigationHistoryPool.hh>
Public Member Functions
std::vector< G4NavigationLevel > * GetNewLevels ()
std::vector< G4NavigationLevel > * GetLevels ()
void DeRegister (std::vector< G4NavigationLevel > *pLevels)
void Clean ()
void Print () const
~G4NavigationHistoryPool ()
Static Public Member Functions
static G4NavigationHistoryPool * GetInstance ()
Private Member Functions
G4NavigationHistoryPool ()
void Register (std::vector< G4NavigationLevel > *pLevels)
void Reset ()
Private Attributes
std::vector< std::vector
< G4NavigationLevel > * > fPool
std::vector< std::vector
< G4NavigationLevel > * > fFree
Static Private Attributes
static G4ThreadLocal
G4NavigationHistoryPool * fgInstance = nullptr
Detailed Description
Definition at line 43 of file G4NavigationHistoryPool.hh.
View newest version in sPHENIX GitHub at line 43 of file G4NavigationHistoryPool.hh
Constructor & Destructor Documentation
G4NavigationHistoryPool::~G4NavigationHistoryPool ()
Definition at line 57 of file G4NavigationHistoryPool.cc.
View newest version in sPHENIX GitHub at line 57 of file G4NavigationHistoryPool.cc
References Clean(), and fgInstance.
G4NavigationHistoryPool::G4NavigationHistoryPool () private
Definition at line 47 of file G4NavigationHistoryPool.cc.
View newest version in sPHENIX GitHub at line 47 of file G4NavigationHistoryPool.cc
References fFree, and fPool.
Referenced by GetInstance().
Member Function Documentation
void G4NavigationHistoryPool::Clean ()
Definition at line 66 of file G4NavigationHistoryPool.cc.
View newest version in sPHENIX GitHub at line 66 of file G4NavigationHistoryPool.cc
References fFree, and fPool.
Referenced by ~G4NavigationHistoryPool().
void G4NavigationHistoryPool::DeRegister (std::vector< G4NavigationLevel > * pLevels) inline
Definition at line 103 of file G4NavigationHistoryPool.hh.
View newest version in sPHENIX GitHub at line 103 of file G4NavigationHistoryPool.hh
References fFree.
Referenced by G4NavigationHistory::~G4NavigationHistory().
G4NavigationHistoryPool * G4NavigationHistoryPool::GetInstance (void) static
Definition at line 108 of file G4NavigationHistoryPool.cc.
View newest version in sPHENIX GitHub at line 108 of file G4NavigationHistoryPool.cc
References fgInstance, and G4NavigationHistoryPool().
Referenced by G4NavigationHistory::G4NavigationHistory(), G4NavigationHistory::~G4NavigationHistory(), and G4RunManagerKernel::~G4RunManagerKernel().
std::vector< G4NavigationLevel > * G4NavigationHistoryPool::GetLevels () inline
Definition at line 126 of file G4NavigationHistoryPool.hh.
View newest version in sPHENIX GitHub at line 126 of file G4NavigationHistoryPool.hh
References fFree, and GetNewLevels().
Referenced by G4NavigationHistory::G4NavigationHistory().
std::vector< G4NavigationLevel > * G4NavigationHistoryPool::GetNewLevels () inline
Definition at line 112 of file G4NavigationHistoryPool.hh.
View newest version in sPHENIX GitHub at line 112 of file G4NavigationHistoryPool.hh
References kHistoryMax, and Register().
Referenced by GetLevels().
void G4NavigationHistoryPool::Print (void) const
Definition at line 80 of file G4NavigationHistoryPool.cc.
View newest version in sPHENIX GitHub at line 80 of file G4NavigationHistoryPool.cc
References fPool, G4cout, and G4endl.
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
void G4NavigationHistoryPool::Register (std::vector< G4NavigationLevel > * pLevels) inline private
Definition at line 93 of file G4NavigationHistoryPool.hh.
View newest version in sPHENIX GitHub at line 93 of file G4NavigationHistoryPool.hh
References fPool.
Referenced by GetNewLevels().
void G4NavigationHistoryPool::Reset () private
Definition at line 92 of file G4NavigationHistoryPool.cc.
View newest version in sPHENIX GitHub at line 92 of file G4NavigationHistoryPool.cc
References fFree, and fPool.
Member Data Documentation
std::vector<std::vector<G4NavigationLevel> *> G4NavigationHistoryPool::fFree private
Definition at line 85 of file G4NavigationHistoryPool.hh.
View newest version in sPHENIX GitHub at line 85 of file G4NavigationHistoryPool.hh
Referenced by Clean(), DeRegister(), G4NavigationHistoryPool(), GetLevels(), and Reset().
G4ThreadLocal G4NavigationHistoryPool * G4NavigationHistoryPool::fgInstance = nullptr static private
Definition at line 82 of file G4NavigationHistoryPool.hh.
View newest version in sPHENIX GitHub at line 82 of file G4NavigationHistoryPool.hh
Referenced by GetInstance(), and ~G4NavigationHistoryPool().
std::vector<std::vector<G4NavigationLevel> *> G4NavigationHistoryPool::fPool private
Definition at line 84 of file G4NavigationHistoryPool.hh.
View newest version in sPHENIX GitHub at line 84 of file G4NavigationHistoryPool.hh
Referenced by Clean(), G4NavigationHistoryPool(), Print(), Register(), and Reset().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4NavigationHistoryPool.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4NavigationHistoryPool.cc