ECCE @ EIC Software: G4NeutrinoElectronNcModel Class Reference
G4NeutrinoElectronNcModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4NeutrinoElectronNcModel.hh>
Public Member Functions
G4NeutrinoElectronNcModel (const G4String &name="nu-e-elastic")
virtual ~G4NeutrinoElectronNcModel ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double SampleElectronTkin (const G4HadProjectile *aParticle)
void SetCutEnergy (G4double ec)
G4double GetCutEnergy ()
virtual void ModelDescription (std::ostream &) const
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A) override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Attributes
G4ParticleDefinition * theElectron
G4double fSin2tW
G4double fCutEnergy
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 49 of file G4NeutrinoElectronNcModel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4NeutrinoElectronNcModel.hh
Constructor & Destructor Documentation
G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel (const G4String & name = "nu-e-elastic")
Definition at line 44 of file G4NeutrinoElectronNcModel.cc.
View newest version in sPHENIX GitHub at line 44 of file G4NeutrinoElectronNcModel.cc
References e, G4Electron::Electron(), eV, fCutEnergy, fSin2tW, G4HadronicInteraction::GetMaxEnergy(), GeV, G4HadronicParameters::Instance(), G4HadronElastic::SetLowestEnergyLimit(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), and theElectron.
G4NeutrinoElectronNcModel::~G4NeutrinoElectronNcModel () virtual
Definition at line 61 of file G4NeutrinoElectronNcModel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4NeutrinoElectronNcModel.cc
Member Function Documentation
G4HadFinalState * G4NeutrinoElectronNcModel::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Reimplemented from G4HadronElastic.
Definition at line 104 of file G4NeutrinoElectronNcModel.cc.
View newest version in sPHENIX GitHub at line 104 of file G4NeutrinoElectronNcModel.cc
References G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), CLHEP::HepLorentzVector::e(), source.hepunit::electron_mass_c2, fCutEnergy, G4UniformRand, G4HadProjectile::Get4Momentum(), G4HadProjectile::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetZ_asInt(), G4HadronElastic::LowestEnergyLimit(), phi, SampleElectronTkin(), G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetLocalEnergyDeposit(), G4HadFinalState::SetMomentumChange(), theElectron, G4HadronicInteraction::theParticleChange, CLHEP::twopi, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), and Z.
G4double G4NeutrinoElectronNcModel::GetCutEnergy () inline
Definition at line 68 of file G4NeutrinoElectronNcModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4NeutrinoElectronNcModel.hh
References fCutEnergy.
G4bool G4NeutrinoElectronNcModel::IsApplicable (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 76 of file G4NeutrinoElectronNcModel.cc.
View newest version in sPHENIX GitHub at line 76 of file G4NeutrinoElectronNcModel.cc
References source.hepunit::electron_mass_c2, energy, fCutEnergy, G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4HadProjectile::GetTotalEnergy(), G4Nucleus::GetZ_asInt(), and Z.
void G4NeutrinoElectronNcModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronElastic.
Definition at line 65 of file G4NeutrinoElectronNcModel.cc.
View newest version in sPHENIX GitHub at line 65 of file G4NeutrinoElectronNcModel.cc
G4double G4NeutrinoElectronNcModel::SampleElectronTkin (const G4HadProjectile * aParticle)
Definition at line 177 of file G4NeutrinoElectronNcModel.cc.
View newest version in sPHENIX GitHub at line 177 of file G4NeutrinoElectronNcModel.cc
References a, A(), b, B(), c, D(), d, source.hepunit::electron_mass_c2, energy, fSin2tW, G4UniformRand, G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4HadProjectile::GetTotalEnergy(), x1, and y1.
Referenced by ApplyYourself().
void G4NeutrinoElectronNcModel::SetCutEnergy (G4double ec) inline
Definition at line 67 of file G4NeutrinoElectronNcModel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4NeutrinoElectronNcModel.hh
References fCutEnergy.
Member Data Documentation
G4double G4NeutrinoElectronNcModel::fCutEnergy private
Definition at line 78 of file G4NeutrinoElectronNcModel.hh.
View newest version in sPHENIX GitHub at line 78 of file G4NeutrinoElectronNcModel.hh
Referenced by ApplyYourself(), G4NeutrinoElectronNcModel(), GetCutEnergy(), IsApplicable(), and SetCutEnergy().
G4double G4NeutrinoElectronNcModel::fSin2tW private
Definition at line 77 of file G4NeutrinoElectronNcModel.hh.
View newest version in sPHENIX GitHub at line 77 of file G4NeutrinoElectronNcModel.hh
Referenced by G4NeutrinoElectronNcModel(), and SampleElectronTkin().
G4ParticleDefinition* G4NeutrinoElectronNcModel::theElectron private
Definition at line 76 of file G4NeutrinoElectronNcModel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4NeutrinoElectronNcModel.hh
Referenced by ApplyYourself(), and G4NeutrinoElectronNcModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4NeutrinoElectronNcModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4NeutrinoElectronNcModel.cc