ECCE @ EIC Software: G4HadronElasticPhysicsHP Class Reference
G4HadronElasticPhysicsHP Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_elastic/include/G4HadronElasticPhysicsHP.hh>
Public Member Functions
G4HadronElasticPhysicsHP (G4int ver=1)
virtual ~G4HadronElasticPhysicsHP ()
void ConstructProcess () final
Public Member Functions inherited from G4HadronElasticPhysics
G4HadronElasticPhysics (G4int ver=0, const G4String &nam="hElasticWEL_CHIPS_XS")
virtual ~G4HadronElasticPhysics ()
void ConstructParticle () override
G4HadronicProcess * GetElasticProcess (const G4ParticleDefinition *part) const
G4HadronElastic * GetElasticModel (const G4ParticleDefinition *part) const
G4HadronicProcess * GetNeutronProcess () const
G4HadronElastic * GetNeutronModel () const
void AddXSection (const G4ParticleDefinition *, G4VCrossSectionDataSet *) const
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
G4HadronElasticPhysicsHP (G4HadronElasticPhysicsHP &)=delete
G4HadronElasticPhysicsHP & operator= (const G4HadronElasticPhysicsHP &right)=delete
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4HadronElasticPhysics
G4int verbose
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 43 of file G4HadronElasticPhysicsHP.hh.
View newest version in sPHENIX GitHub at line 43 of file G4HadronElasticPhysicsHP.hh
Constructor & Destructor Documentation
G4HadronElasticPhysicsHP::G4HadronElasticPhysicsHP (G4int ver = 1) explicit
Definition at line 54 of file G4HadronElasticPhysicsHP.cc.
View newest version in sPHENIX GitHub at line 54 of file G4HadronElasticPhysicsHP.cc
References G4cout, G4endl, G4VPhysicsConstructor::GetPhysicsName(), and G4HadronElasticPhysics::verbose.
G4HadronElasticPhysicsHP::~G4HadronElasticPhysicsHP () virtual
Definition at line 63 of file G4HadronElasticPhysicsHP.cc.
View newest version in sPHENIX GitHub at line 63 of file G4HadronElasticPhysicsHP.cc
G4HadronElasticPhysicsHP::G4HadronElasticPhysicsHP (G4HadronElasticPhysicsHP &) private delete
Member Function Documentation
void G4HadronElasticPhysicsHP::ConstructProcess (void) final virtual
Reimplemented from G4HadronElasticPhysics.
Definition at line 66 of file G4HadronElasticPhysicsHP.cc.
View newest version in sPHENIX GitHub at line 66 of file G4HadronElasticPhysicsHP.cc
References G4HadronicProcess::AddDataSet(), G4HadronElasticPhysics::ConstructProcess(), G4cout, G4endl, G4HadronElasticPhysics::GetElasticModel(), G4HadronElasticPhysics::GetElasticProcess(), MeV, G4InuclParticleNames::neutron, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMinEnergy(), and G4HadronElasticPhysics::verbose.
G4HadronElasticPhysicsHP& G4HadronElasticPhysicsHP::operator= (const G4HadronElasticPhysicsHP & right) private delete
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_elastic/include/G4HadronElasticPhysicsHP.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_elastic/src/G4HadronElasticPhysicsHP.cc