ECCE @ EIC Software: G4HadronPhysicsQGS_BIC Class Reference
G4HadronPhysicsQGS_BIC Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsQGS_BIC.hh>
Public Member Functions
G4HadronPhysicsQGS_BIC (G4int verbose=1)
G4HadronPhysicsQGS_BIC (const G4String &name, G4bool quasiElastic=true)
virtual ~G4HadronPhysicsQGS_BIC ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Member Functions
void CreateModels ()
virtual void Neutron ()
virtual void Proton ()
virtual void Pion ()
virtual void Kaon ()
virtual void Others ()
virtual void DumpBanner ()
virtual void ExtraConfiguration ()
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes
G4double maxFTF_neutron
G4double maxFTF_proton
G4double minFTF_neutron
G4double minFTF_proton
G4double maxBIC_neutron
G4double maxBIC_proton
G4double maxFTF_pion
G4double maxBERT_pion
G4double minBERT_pion
G4double maxBIC_pion
G4double maxFTF_kaon
G4double maxBERT_kaon
G4bool QuasiElasticQGS
G4bool QuasiElasticFTF
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 49 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 49 of file G4HadronPhysicsQGS_BIC.hh
Constructor & Destructor Documentation
G4HadronPhysicsQGS_BIC::G4HadronPhysicsQGS_BIC (G4int verbose = 1)
Definition at line 91 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 91 of file G4HadronPhysicsQGS_BIC.cc
G4HadronPhysicsQGS_BIC::G4HadronPhysicsQGS_BIC (const G4String & name, G4bool quasiElastic = true)
Definition at line 94 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 94 of file G4HadronPhysicsQGS_BIC.cc
References G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::GetMaxEnergyTransitionQGS_FTF(), G4HadronicParameters::GetMinEnergyTransitionFTF_Cascade(), GeV, G4HadronicParameters::Instance(), maxBERT_kaon, maxBERT_pion, maxBIC_neutron, maxBIC_pion, maxBIC_proton, maxFTF_kaon, maxFTF_neutron, maxFTF_pion, maxFTF_proton, minBERT_pion, minFTF_neutron, minFTF_proton, QuasiElasticFTF, and QuasiElasticQGS.
G4HadronPhysicsQGS_BIC::~G4HadronPhysicsQGS_BIC () virtual
Definition at line 113 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 113 of file G4HadronPhysicsQGS_BIC.cc
Member Function Documentation
void G4HadronPhysicsQGS_BIC::ConstructParticle (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 222 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 222 of file G4HadronPhysicsQGS_BIC.cc
References G4MesonConstructor::ConstructParticle(), G4IonConstructor::ConstructParticle(), G4BaryonConstructor::ConstructParticle(), and G4ShortLivedConstructor::ConstructParticle().
void G4HadronPhysicsQGS_BIC::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 238 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 238 of file G4HadronPhysicsQGS_BIC.cc
References CreateModels(), DumpBanner(), ExtraConfiguration(), and G4Threading::IsMasterThread().
void G4HadronPhysicsQGS_BIC::CreateModels () protected
Definition at line 116 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 116 of file G4HadronPhysicsQGS_BIC.cc
References Kaon(), Neutron(), Others(), Pion(), and Proton().
Referenced by ConstructProcess().
virtual void G4HadronPhysicsQGS_BIC::DumpBanner () inline protected virtual
Definition at line 66 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 66 of file G4HadronPhysicsQGS_BIC.hh
Referenced by ConstructProcess().
void G4HadronPhysicsQGS_BIC::ExtraConfiguration () protected virtual
Definition at line 247 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 247 of file G4HadronPhysicsQGS_BIC.cc
References G4HadronicProcess::AddDataSet(), G4PhysListUtil::FindCaptureProcess(), G4PhysListUtil::FindInelasticProcess(), G4InuclParticleNames::neutron, G4Neutron::Neutron(), and G4HadronicProcess::RegisterMe().
Referenced by ConstructProcess().
void G4HadronPhysicsQGS_BIC::Kaon () protected virtual
Definition at line 191 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 191 of file G4HadronPhysicsQGS_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), k, maxBERT_kaon, maxFTF_kaon, QuasiElasticFTF, and QuasiElasticQGS.
Referenced by CreateModels().
void G4HadronPhysicsQGS_BIC::Neutron () protected virtual
Definition at line 125 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 125 of file G4HadronPhysicsQGS_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), maxBIC_neutron, maxFTF_neutron, minFTF_neutron, G4InuclParticleNames::neu, QuasiElasticFTF, and QuasiElasticQGS.
Referenced by CreateModels().
void G4HadronPhysicsQGS_BIC::Others () protected virtual
Definition at line 209 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 209 of file G4HadronPhysicsQGS_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), and QuasiElasticFTF.
Referenced by CreateModels().
void G4HadronPhysicsQGS_BIC::Pion () protected virtual
Definition at line 168 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 168 of file G4HadronPhysicsQGS_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), maxBERT_pion, maxBIC_pion, maxFTF_pion, minBERT_pion, pi, QuasiElasticFTF, and QuasiElasticQGS.
Referenced by CreateModels().
void G4HadronPhysicsQGS_BIC::Proton () protected virtual
Definition at line 149 of file G4HadronPhysicsQGS_BIC.cc.
View newest version in sPHENIX GitHub at line 149 of file G4HadronPhysicsQGS_BIC.cc
References G4VPhysicsConstructor::AddBuilder(), maxBIC_proton, maxFTF_proton, minFTF_proton, G4InuclParticleNames::pro, QuasiElasticFTF, and QuasiElasticQGS.
Referenced by CreateModels().
Member Data Documentation
G4double G4HadronPhysicsQGS_BIC::maxBERT_kaon protected
Definition at line 84 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Kaon().
G4double G4HadronPhysicsQGS_BIC::maxBERT_pion protected
Definition at line 79 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 79 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Pion().
G4double G4HadronPhysicsQGS_BIC::maxBIC_neutron protected
Definition at line 75 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 75 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Neutron().
G4double G4HadronPhysicsQGS_BIC::maxBIC_pion protected
Definition at line 81 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 81 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Pion().
G4double G4HadronPhysicsQGS_BIC::maxBIC_proton protected
Definition at line 76 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 76 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Proton().
G4double G4HadronPhysicsQGS_BIC::maxFTF_kaon protected
Definition at line 83 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 83 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Kaon().
G4double G4HadronPhysicsQGS_BIC::maxFTF_neutron protected
Definition at line 71 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 71 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Neutron().
G4double G4HadronPhysicsQGS_BIC::maxFTF_pion protected
Definition at line 78 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Pion().
G4double G4HadronPhysicsQGS_BIC::maxFTF_proton protected
Definition at line 72 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Proton().
G4double G4HadronPhysicsQGS_BIC::minBERT_pion protected
Definition at line 80 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 80 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Pion().
G4double G4HadronPhysicsQGS_BIC::minFTF_neutron protected
Definition at line 73 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 73 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Neutron().
G4double G4HadronPhysicsQGS_BIC::minFTF_proton protected
Definition at line 74 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 74 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), and Proton().
G4bool G4HadronPhysicsQGS_BIC::QuasiElasticFTF protected
Definition at line 87 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 87 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), Kaon(), Neutron(), Others(), Pion(), and Proton().
G4bool G4HadronPhysicsQGS_BIC::QuasiElasticQGS protected
Definition at line 86 of file G4HadronPhysicsQGS_BIC.hh.
View newest version in sPHENIX GitHub at line 86 of file G4HadronPhysicsQGS_BIC.hh
Referenced by G4HadronPhysicsQGS_BIC(), Kaon(), Neutron(), Pion(), and Proton().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsQGS_BIC.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsQGS_BIC.cc