ECCE @ EIC Software: G4SDParticleWithEnergyFilter Class Reference
G4SDParticleWithEnergyFilter Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4SDParticleWithEnergyFilter.hh>
Public Member Functions
G4SDParticleWithEnergyFilter (G4String name, G4double elow=0.0, G4double ehigh=DBL_MAX)
virtual ~G4SDParticleWithEnergyFilter ()
virtual G4bool Accept (const G4Step *) const
void add (const G4String &particleName)
void SetKineticEnergy (G4double elow, G4double ehigh)
void show ()
G4SDParticleWithEnergyFilter (const G4SDParticleWithEnergyFilter &)
G4SDParticleWithEnergyFilter & operator= (const G4SDParticleWithEnergyFilter &)
Public Member Functions inherited from G4VSDFilter
G4VSDFilter (G4String name)
virtual ~G4VSDFilter ()
G4String GetName () const
Private Attributes
G4SDParticleFilter * fParticleFilter
G4SDKineticEnergyFilter * fKineticFilter
Additional Inherited Members
Protected Attributes inherited from G4VSDFilter
G4String filterName
Detailed Description
Definition at line 50 of file G4SDParticleWithEnergyFilter.hh.
View newest version in sPHENIX GitHub at line 50 of file G4SDParticleWithEnergyFilter.hh
Constructor & Destructor Documentation
G4SDParticleWithEnergyFilter::G4SDParticleWithEnergyFilter (G4String name, G4double elow = 0.0, G4double ehigh = DBL_MAX)
Definition at line 45 of file G4SDParticleWithEnergyFilter.cc.
View newest version in sPHENIX GitHub at line 45 of file G4SDParticleWithEnergyFilter.cc
References fKineticFilter, and fParticleFilter.
G4SDParticleWithEnergyFilter::~G4SDParticleWithEnergyFilter () virtual
Definition at line 54 of file G4SDParticleWithEnergyFilter.cc.
View newest version in sPHENIX GitHub at line 54 of file G4SDParticleWithEnergyFilter.cc
References fKineticFilter, and fParticleFilter.
G4SDParticleWithEnergyFilter::G4SDParticleWithEnergyFilter (const G4SDParticleWithEnergyFilter & rhs)
Definition at line 83 of file G4SDParticleWithEnergyFilter.cc.
View newest version in sPHENIX GitHub at line 83 of file G4SDParticleWithEnergyFilter.cc
References fKineticFilter, and fParticleFilter.
Member Function Documentation
G4bool G4SDParticleWithEnergyFilter::Accept (const G4Step * aStep) const virtual
Implements G4VSDFilter.
Definition at line 60 of file G4SDParticleWithEnergyFilter.cc.
View newest version in sPHENIX GitHub at line 60 of file G4SDParticleWithEnergyFilter.cc
References G4SDKineticEnergyFilter::Accept(), G4SDParticleFilter::Accept(), FALSE, fKineticFilter, fParticleFilter, and TRUE.
void G4SDParticleWithEnergyFilter::add (const G4String & particleName)
Definition at line 67 of file G4SDParticleWithEnergyFilter.cc.
View newest version in sPHENIX GitHub at line 67 of file G4SDParticleWithEnergyFilter.cc
References G4SDParticleFilter::add(), and fParticleFilter.
Referenced by RE02DetectorConstruction::ConstructSDandField(), and G4ScoreQuantityMessenger::FParticleWithEnergyCommand().
G4SDParticleWithEnergyFilter & G4SDParticleWithEnergyFilter::operator= (const G4SDParticleWithEnergyFilter & rhs)
Definition at line 91 of file G4SDParticleWithEnergyFilter.cc.
View newest version in sPHENIX GitHub at line 91 of file G4SDParticleWithEnergyFilter.cc
References fKineticFilter, and fParticleFilter.
void G4SDParticleWithEnergyFilter::SetKineticEnergy (G4double elow, G4double ehigh)
Definition at line 72 of file G4SDParticleWithEnergyFilter.cc.
View newest version in sPHENIX GitHub at line 72 of file G4SDParticleWithEnergyFilter.cc
References fKineticFilter, and G4SDKineticEnergyFilter::SetKineticEnergy().
void G4SDParticleWithEnergyFilter::show ()
Definition at line 78 of file G4SDParticleWithEnergyFilter.cc.
View newest version in sPHENIX GitHub at line 78 of file G4SDParticleWithEnergyFilter.cc
References fKineticFilter, fParticleFilter, G4SDKineticEnergyFilter::show(), and G4SDParticleFilter::show().
Referenced by RE02DetectorConstruction::ConstructSDandField().
Member Data Documentation
G4SDKineticEnergyFilter* G4SDParticleWithEnergyFilter::fKineticFilter private
Definition at line 70 of file G4SDParticleWithEnergyFilter.hh.
View newest version in sPHENIX GitHub at line 70 of file G4SDParticleWithEnergyFilter.hh
Referenced by Accept(), G4SDParticleWithEnergyFilter(), operator=(), SetKineticEnergy(), show(), and ~G4SDParticleWithEnergyFilter().
G4SDParticleFilter* G4SDParticleWithEnergyFilter::fParticleFilter private
Definition at line 69 of file G4SDParticleWithEnergyFilter.hh.
View newest version in sPHENIX GitHub at line 69 of file G4SDParticleWithEnergyFilter.hh
Referenced by Accept(), add(), G4SDParticleWithEnergyFilter(), operator=(), show(), and ~G4SDParticleWithEnergyFilter().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4SDParticleWithEnergyFilter.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4SDParticleWithEnergyFilter.cc