ECCE @ EIC Software: GVFlashShowerParameterisation Class Reference
GVFlashShowerParameterisation Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GVFlashShowerParameterisation.hh>
Public Member Functions
GVFlashShowerParameterisation ()
virtual ~GVFlashShowerParameterisation ()
virtual void ComputeRadialParameters (G4double y, G4double Tau)=0
virtual void GenerateLongitudinalProfile (G4double Energy)=0
virtual G4double IntegrateEneLongitudinal (G4double LongitudinalStep)=0
virtual G4double IntegrateNspLongitudinal (G4double LongitudinalStep)=0
virtual G4double ComputeTau (G4double LongitudinalPosition)=0
virtual G4double GenerateRadius (G4int ispot, G4double Energy, G4double LongitudinalPosition)=0
virtual void ComputeLongitudinalParameters (G4double y)=0
virtual void GenerateEnergyProfile (G4double y)=0
virtual void GenerateNSpotProfile (G4double y)=0
virtual G4double GenerateExponential (G4double Energy)=0
virtual G4double GetAveR99 ()=0
virtual G4double GetAveR90 ()=0
virtual G4double GetAveTmx ()=0
virtual G4double GetAveT99 ()=0
virtual G4double GetAveT90 ()=0
virtual G4double GetNspot ()=0
virtual G4double GetX0 ()=0
virtual G4double GetEc ()=0
virtual G4double GetRm ()=0
G4double GeneratePhi ()
G4double GetEffZ (const G4Material *material)
G4double GetEffA (const G4Material *material)
G4double gam (G4double x, G4double a) const
void PrintMaterial (const G4Material *mat)
Protected Attributes
GVFlashHomoShowerTuning * thePar
G4double density
G4double A
G4double Z
G4double X0
G4double Ec
G4double Rm
G4double NSpot
Private Attributes
MyGamma * fGamma
Detailed Description
Definition at line 50 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 50 of file GVFlashShowerParameterisation.hh
Constructor & Destructor Documentation
GVFlashShowerParameterisation::GVFlashShowerParameterisation ()
Definition at line 48 of file GVFlashShowerParameterisation.cc.
View newest version in sPHENIX GitHub at line 48 of file GVFlashShowerParameterisation.cc
References fGamma.
GVFlashShowerParameterisation::~GVFlashShowerParameterisation () virtual
Definition at line 54 of file GVFlashShowerParameterisation.cc.
View newest version in sPHENIX GitHub at line 54 of file GVFlashShowerParameterisation.cc
References fGamma.
Member Function Documentation
virtual void GVFlashShowerParameterisation::ComputeLongitudinalParameters (G4double y) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
virtual void GVFlashShowerParameterisation::ComputeRadialParameters (G4double y, G4double Tau) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
virtual G4double GVFlashShowerParameterisation::ComputeTau (G4double LongitudinalPosition) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
G4double GVFlashShowerParameterisation::gam (G4double x, G4double a) const
Definition at line 121 of file GVFlashShowerParameterisation.cc.
View newest version in sPHENIX GitHub at line 121 of file GVFlashShowerParameterisation.cc
References fGamma, and MyGamma::Gamma().
Referenced by GFlashHomoShowerParameterisation::IntegrateEneLongitudinal(), GFlashSamplingShowerParameterisation::IntegrateEneLongitudinal(), GFlashHomoShowerParameterisation::IntegrateNspLongitudinal(), and GFlashSamplingShowerParameterisation::IntegrateNspLongitudinal().
virtual void GVFlashShowerParameterisation::GenerateEnergyProfile (G4double y) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
virtual G4double GVFlashShowerParameterisation::GenerateExponential (G4double Energy) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
virtual void GVFlashShowerParameterisation::GenerateLongitudinalProfile (G4double Energy) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
Referenced by GFlashShowerModel::ElectronDoIt(), and GFlashShowerModel::ModelTrigger().
virtual void GVFlashShowerParameterisation::GenerateNSpotProfile (G4double y) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
G4double GVFlashShowerParameterisation::GeneratePhi ()
Definition at line 115 of file GVFlashShowerParameterisation.cc.
View newest version in sPHENIX GitHub at line 115 of file GVFlashShowerParameterisation.cc
References G4UniformRand, and twopi.
Referenced by GFlashShowerModel::ElectronDoIt().
virtual G4double GVFlashShowerParameterisation::GenerateRadius (G4int ispot, G4double Energy, G4double LongitudinalPosition) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
Referenced by GFlashShowerModel::ElectronDoIt().
virtual G4double GVFlashShowerParameterisation::GetAveR90 () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
Referenced by GFlashShowerModel::CheckContainment().
virtual G4double GVFlashShowerParameterisation::GetAveR99 () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
virtual G4double GVFlashShowerParameterisation::GetAveT90 () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
Referenced by GFlashShowerModel::CheckContainment().
virtual G4double GVFlashShowerParameterisation::GetAveT99 () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
virtual G4double GVFlashShowerParameterisation::GetAveTmx () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
virtual G4double GVFlashShowerParameterisation::GetEc () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
G4double GVFlashShowerParameterisation::GetEffA (const G4Material * material)
Definition at line 82 of file GVFlashShowerParameterisation.cc.
View newest version in sPHENIX GitHub at line 82 of file GVFlashShowerParameterisation.cc
References a, Acts::UnitConstants::g, G4Element::GetA(), G4Material::GetA(), G4Material::GetElement(), G4Material::GetFractionVector(), G4Material::GetNumberOfElements(), and mole.
Referenced by GFlashSamplingShowerParameterisation::SetMaterial(), and GFlashHomoShowerParameterisation::SetMaterial().
G4double GVFlashShowerParameterisation::GetEffZ (const G4Material * material)
Definition at line 59 of file GVFlashShowerParameterisation.cc.
View newest version in sPHENIX GitHub at line 59 of file GVFlashShowerParameterisation.cc
References G4Material::GetElement(), G4Material::GetFractionVector(), G4Material::GetNumberOfElements(), G4Element::GetZ(), G4Material::GetZ(), and z.
Referenced by GFlashSamplingShowerParameterisation::SetMaterial(), and GFlashHomoShowerParameterisation::SetMaterial().
virtual G4double GVFlashShowerParameterisation::GetNspot () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
Referenced by GFlashShowerModel::ElectronDoIt().
virtual G4double GVFlashShowerParameterisation::GetRm () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
virtual G4double GVFlashShowerParameterisation::GetX0 () pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
Referenced by GFlashShowerModel::ElectronDoIt().
virtual G4double GVFlashShowerParameterisation::IntegrateEneLongitudinal (G4double LongitudinalStep) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
Referenced by GFlashShowerModel::ElectronDoIt().
virtual G4double GVFlashShowerParameterisation::IntegrateNspLongitudinal (G4double LongitudinalStep) pure virtual
Implemented in GFlashSamplingShowerParameterisation, and GFlashHomoShowerParameterisation.
Referenced by GFlashShowerModel::ElectronDoIt().
void GVFlashShowerParameterisation::PrintMaterial (const G4Material * mat)
Definition at line 102 of file GVFlashShowerParameterisation.cc.
View newest version in sPHENIX GitHub at line 102 of file GVFlashShowerParameterisation.cc
References A, cm, Ec, G4cout, G4endl, G4Material::GetName(), MeV, Rm, X0, and Z.
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and ExGflashDetectorConstruction::SetMaterial().
Member Data Documentation
G4double GVFlashShowerParameterisation::A protected
Definition at line 91 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file GVFlashShowerParameterisation.hh
Referenced by PrintMaterial(), and GFlashHomoShowerParameterisation::SetMaterial().
G4double GVFlashShowerParameterisation::density protected
Definition at line 91 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file GVFlashShowerParameterisation.hh
Referenced by GFlashHomoShowerParameterisation::SetMaterial().
G4double GVFlashShowerParameterisation::Ec protected
Definition at line 91 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file GVFlashShowerParameterisation.hh
Referenced by GFlashHomoShowerParameterisation::GenerateLongitudinalProfile(), GFlashHomoShowerParameterisation::GenerateNSpotProfile(), GFlashHomoShowerParameterisation::GetEc(), PrintMaterial(), and GFlashHomoShowerParameterisation::SetMaterial().
MyGamma* GVFlashShowerParameterisation::fGamma private
Definition at line 96 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 96 of file GVFlashShowerParameterisation.hh
Referenced by gam(), GVFlashShowerParameterisation(), and ~GVFlashShowerParameterisation().
G4double GVFlashShowerParameterisation::NSpot protected
Definition at line 93 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 93 of file GVFlashShowerParameterisation.hh
G4double GVFlashShowerParameterisation::Rm protected
Definition at line 91 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file GVFlashShowerParameterisation.hh
Referenced by GFlashHomoShowerParameterisation::GenerateRadius(), GFlashHomoShowerParameterisation::GetAveR90(), GFlashHomoShowerParameterisation::GetAveR99(), GFlashHomoShowerParameterisation::GetRm(), PrintMaterial(), and GFlashHomoShowerParameterisation::SetMaterial().
GVFlashHomoShowerTuning* GVFlashShowerParameterisation::thePar protected
Definition at line 89 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 89 of file GVFlashShowerParameterisation.hh
G4double GVFlashShowerParameterisation::X0 protected
Definition at line 91 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file GVFlashShowerParameterisation.hh
Referenced by GFlashHomoShowerParameterisation::ComputeTau(), GFlashHomoShowerParameterisation::GenerateExponential(), GFlashHomoShowerParameterisation::GetAveT90(), GFlashHomoShowerParameterisation::GetAveT99(), GFlashHomoShowerParameterisation::GetAveTmx(), GFlashHomoShowerParameterisation::GetX0(), GFlashHomoShowerParameterisation::IntegrateEneLongitudinal(), GFlashHomoShowerParameterisation::IntegrateNspLongitudinal(), PrintMaterial(), and GFlashHomoShowerParameterisation::SetMaterial().
G4double GVFlashShowerParameterisation::Z protected
Definition at line 91 of file GVFlashShowerParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file GVFlashShowerParameterisation.hh
Referenced by GFlashHomoShowerParameterisation::ComputeLongitudinalParameters(), GFlashHomoShowerParameterisation::ComputeRadialParameters(), GFlashHomoShowerParameterisation::GenerateNSpotProfile(), PrintMaterial(), and GFlashHomoShowerParameterisation::SetMaterial().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GVFlashShowerParameterisation.hh
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/src/GVFlashShowerParameterisation.cc