ECCE @ EIC Software: G4FastSimulationManager Class Reference
G4FastSimulationManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4FastSimulationManager.hh>
Public Member Functions
G4FastSimulationManager (G4Envelope *anEnvelope, G4bool IsUnique=FALSE)
~G4FastSimulationManager ()
void AddFastSimulationModel (G4VFastSimulationModel *)
void RemoveFastSimulationModel (G4VFastSimulationModel *)
G4bool ActivateFastSimulationModel (const G4String &)
G4bool InActivateFastSimulationModel (const G4String &)
void ListTitle () const
void ListModels () const
void ListModels (const G4ParticleDefinition *) const
void ListModels (const G4String &aName) const
const G4Envelope * GetEnvelope () const
G4VFastSimulationModel * GetFastSimulationModel (const G4String &modelName, const G4VFastSimulationModel *previousFound, bool &foundPrevious) const
const std::vector
< G4VFastSimulationModel * > & GetFastSimulationModelList () const
G4bool PostStepGetFastSimulationManagerTrigger (const G4Track &, const G4Navigator *a=0)
G4VParticleChange * InvokePostStepDoIt ()
G4bool AtRestGetFastSimulationManagerTrigger (const G4Track &, const G4Navigator *a=0)
G4VParticleChange * InvokeAtRestDoIt ()
G4bool operator== (const G4FastSimulationManager &) const
Private Attributes
G4FastTrack fFastTrack
G4FastStep fFastStep
G4VFastSimulationModel * fTriggedFastSimulationModel
G4FastSimulationVector
< G4VFastSimulationModel > ModelList
G4FastSimulationVector
< G4VFastSimulationModel > fInactivatedModels
G4ParticleDefinition * fLastCrossedParticle
G4FastSimulationVector
< G4VFastSimulationModel > fApplicableModelList
G4FastSimulationVector
< G4Transform3D > GhostPlacements
Detailed Description
Definition at line 82 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 82 of file G4FastSimulationManager.hh
Constructor & Destructor Documentation
G4FastSimulationManager::G4FastSimulationManager (G4Envelope * anEnvelope, G4bool IsUnique = FALSE)
Definition at line 52 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 52 of file G4FastSimulationManager.cc
References G4GlobalFastSimulationManager::GetGlobalFastSimulationManager(), and G4Region::SetFastSimulationManager().
G4FastSimulationManager::~G4FastSimulationManager ()
Definition at line 69 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 69 of file G4FastSimulationManager.cc
References G4Region::ClearFastSimulationManager(), fFastTrack, G4FastTrack::GetEnvelope(), G4Region::GetFastSimulationManager(), and G4GlobalFastSimulationManager::GetGlobalFastSimulationManager().
Member Function Documentation
G4bool G4FastSimulationManager::ActivateFastSimulationModel (const G4String & aName)
Definition at line 87 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 87 of file G4FastSimulationManager.cc
References fInactivatedModels, fLastCrossedParticle, ModelList, and G4FastSimulationVector< T >::removeAt().
void G4FastSimulationManager::AddFastSimulationModel (G4VFastSimulationModel * fsm) inline
Definition at line 183 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 183 of file G4FastSimulationManager.hh
References fLastCrossedParticle, and ModelList.
Referenced by G4VFastSimulationModel::G4VFastSimulationModel().
G4bool G4FastSimulationManager::AtRestGetFastSimulationManagerTrigger (const G4Track & track, const G4Navigator * a = 0)
Definition at line 248 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 248 of file G4FastSimulationManager.cc
References fApplicableModelList, fFastStep, fFastTrack, fLastCrossedParticle, fTriggedFastSimulationModel, G4Track::GetDefinition(), G4FastStep::Initialize(), ModelList, and G4FastTrack::SetCurrentTrack().
Referenced by G4FastSimulationManagerProcess::AtRestGetPhysicalInteractionLength().
const G4Envelope * G4FastSimulationManager::GetEnvelope () const inline
Definition at line 205 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 205 of file G4FastSimulationManager.hh
References fFastTrack, and G4FastTrack::GetEnvelope().
G4VFastSimulationModel * G4FastSimulationManager::GetFastSimulationModel (const G4String & modelName, const G4VFastSimulationModel * previousFound, bool & foundPrevious) const
Definition at line 126 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 126 of file G4FastSimulationManager.cc
References ModelList.
const std::vector<G4VFastSimulationModel*>& G4FastSimulationManager::GetFastSimulationModelList () const inline
Definition at line 145 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 145 of file G4FastSimulationManager.hh
References ModelList.
Referenced by G4GlobalFastSimulationManager::DisplayRegion().
G4bool G4FastSimulationManager::InActivateFastSimulationModel (const G4String & aName)
Definition at line 110 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 110 of file G4FastSimulationManager.cc
References fInactivatedModels, fLastCrossedParticle, ModelList, and G4FastSimulationVector< T >::removeAt().
G4VParticleChange * G4FastSimulationManager::InvokeAtRestDoIt ()
Definition at line 289 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 289 of file G4FastSimulationManager.cc
References G4VFastSimulationModel::AtRestDoIt(), fFastStep, fFastTrack, and fTriggedFastSimulationModel.
Referenced by G4FastSimulationManagerProcess::AtRestDoIt().
G4VParticleChange * G4FastSimulationManager::InvokePostStepDoIt ()
Definition at line 237 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 237 of file G4FastSimulationManager.cc
References G4VFastSimulationModel::DoIt(), fFastStep, fFastTrack, and fTriggedFastSimulationModel.
Referenced by G4FastSimulationManagerProcess::PostStepDoIt().
void G4FastSimulationManager::ListModels () const
Definition at line 306 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 306 of file G4FastSimulationManager.cc
References fInactivatedModels, G4cout, ListTitle(), and ModelList.
void G4FastSimulationManager::ListModels (const G4ParticleDefinition * particleDefinition) const
Definition at line 377 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 377 of file G4FastSimulationManager.cc
References fInactivatedModels, G4cout, G4endl, G4Exception(), JustWarning, ListTitle(), and ModelList.
void G4FastSimulationManager::ListModels (const G4String & aName) const
Definition at line 322 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 322 of file G4FastSimulationManager.cc
References G4ParticleTable::entries(), fInactivatedModels, G4cout, G4endl, G4ParticleTable::GetParticle(), G4ParticleTable::GetParticleName(), G4ParticleTable::GetParticleTable(), ListTitle(), and ModelList.
void G4FastSimulationManager::ListTitle () const
Definition at line 296 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 296 of file G4FastSimulationManager.cc
References fFastTrack, G4cout, G4FastTrack::GetEnvelope(), G4Region::GetName(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetTransportationManager(), G4Region::GetWorldPhysical(), and G4Navigator::GetWorldVolume().
Referenced by ListModels().
G4bool G4FastSimulationManager::operator== (const G4FastSimulationManager & fsm) const inline
Definition at line 199 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 199 of file G4FastSimulationManager.hh
G4bool G4FastSimulationManager::PostStepGetFastSimulationManagerTrigger (const G4Track & track, const G4Navigator * a = 0)
Definition at line 183 of file G4FastSimulationManager.cc.
View newest version in sPHENIX GitHub at line 183 of file G4FastSimulationManager.cc
References fApplicableModelList, fFastStep, fFastTrack, fLastCrossedParticle, fTriggedFastSimulationModel, G4Track::GetDefinition(), G4FastStep::Initialize(), ModelList, G4FastTrack::OnTheBoundaryButExiting(), and G4FastTrack::SetCurrentTrack().
Referenced by G4FastSimulationManagerProcess::PostStepGetPhysicalInteractionLength().
void G4FastSimulationManager::RemoveFastSimulationModel (G4VFastSimulationModel * fsm) inline
Definition at line 191 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 191 of file G4FastSimulationManager.hh
References fInactivatedModels, fLastCrossedParticle, ModelList, and G4FastSimulationVector< T >::remove().
Member Data Documentation
G4FastSimulationVector<G4VFastSimulationModel> G4FastSimulationManager::fApplicableModelList private
Definition at line 176 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 176 of file G4FastSimulationManager.hh
Referenced by AtRestGetFastSimulationManagerTrigger(), and PostStepGetFastSimulationManagerTrigger().
G4FastStep G4FastSimulationManager::fFastStep private
Definition at line 170 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 170 of file G4FastSimulationManager.hh
Referenced by AtRestGetFastSimulationManagerTrigger(), InvokeAtRestDoIt(), InvokePostStepDoIt(), and PostStepGetFastSimulationManagerTrigger().
G4FastTrack G4FastSimulationManager::fFastTrack private
Definition at line 169 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 169 of file G4FastSimulationManager.hh
Referenced by AtRestGetFastSimulationManagerTrigger(), GetEnvelope(), InvokeAtRestDoIt(), InvokePostStepDoIt(), ListTitle(), PostStepGetFastSimulationManagerTrigger(), and ~G4FastSimulationManager().
G4FastSimulationVector<G4VFastSimulationModel> G4FastSimulationManager::fInactivatedModels private
Definition at line 173 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 173 of file G4FastSimulationManager.hh
Referenced by ActivateFastSimulationModel(), InActivateFastSimulationModel(), ListModels(), and RemoveFastSimulationModel().
G4ParticleDefinition* G4FastSimulationManager::fLastCrossedParticle private
Definition at line 175 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 175 of file G4FastSimulationManager.hh
Referenced by ActivateFastSimulationModel(), AddFastSimulationModel(), AtRestGetFastSimulationManagerTrigger(), InActivateFastSimulationModel(), PostStepGetFastSimulationManagerTrigger(), and RemoveFastSimulationModel().
G4VFastSimulationModel* G4FastSimulationManager::fTriggedFastSimulationModel private
Definition at line 171 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 171 of file G4FastSimulationManager.hh
Referenced by AtRestGetFastSimulationManagerTrigger(), InvokeAtRestDoIt(), InvokePostStepDoIt(), and PostStepGetFastSimulationManagerTrigger().
G4FastSimulationVector<G4Transform3D> G4FastSimulationManager::GhostPlacements private
Definition at line 179 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 179 of file G4FastSimulationManager.hh
G4FastSimulationVector<G4VFastSimulationModel> G4FastSimulationManager::ModelList private
Definition at line 172 of file G4FastSimulationManager.hh.
View newest version in sPHENIX GitHub at line 172 of file G4FastSimulationManager.hh
Referenced by ActivateFastSimulationModel(), AddFastSimulationModel(), AtRestGetFastSimulationManagerTrigger(), GetFastSimulationModel(), GetFastSimulationModelList(), InActivateFastSimulationModel(), ListModels(), PostStepGetFastSimulationManagerTrigger(), and RemoveFastSimulationModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/parameterisation/include/G4FastSimulationManager.hh
geant4/tree/geant4-10.6-release/source/processes/parameterisation/src/G4FastSimulationManager.cc