ECCE @ EIC Software: G4MuonDecayChannel Class Reference
G4MuonDecayChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4MuonDecayChannel.hh>
Public Member Functions
G4MuonDecayChannel (const G4String &theParentName, G4double theBR)
virtual ~G4MuonDecayChannel ()
virtual G4DecayProducts * DecayIt (G4double)
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Protected Member Functions
G4MuonDecayChannel (const G4MuonDecayChannel &)
G4MuonDecayChannel & operator= (const G4MuonDecayChannel &)
G4MuonDecayChannel ()
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Additional Inherited Members
Protected Attributes inherited from G4VDecayChannel
G4String kinematics_name
G4double rbranch
G4int numberOfDaughters
G4String * parent_name
G4String ** daughters_name
G4double rangeMass
G4ThreeVector parent_polarization
G4ParticleTable * particletable
G4int verboseLevel
G4ParticleDefinition * G4MT_parent
G4ParticleDefinition ** G4MT_daughters
G4double G4MT_parent_mass
G4double * G4MT_daughters_mass
G4double * G4MT_daughters_width
G4Mutex daughtersMutex
G4Mutex parentMutex
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 42 of file G4MuonDecayChannel.hh.
View newest version in sPHENIX GitHub at line 42 of file G4MuonDecayChannel.hh
Constructor & Destructor Documentation
G4MuonDecayChannel::G4MuonDecayChannel (const G4String & theParentName, G4double theBR)
Definition at line 58 of file G4MuonDecayChannel.cc.
View newest version in sPHENIX GitHub at line 58 of file G4MuonDecayChannel.cc
References G4cout, G4endl, G4VDecayChannel::GetVerboseLevel(), G4VDecayChannel::SetBR(), G4VDecayChannel::SetDaughter(), G4VDecayChannel::SetNumberOfDaughters(), and G4VDecayChannel::SetParent().
G4MuonDecayChannel::~G4MuonDecayChannel () virtual
Definition at line 93 of file G4MuonDecayChannel.cc.
View newest version in sPHENIX GitHub at line 93 of file G4MuonDecayChannel.cc
G4MuonDecayChannel::G4MuonDecayChannel (const G4MuonDecayChannel & right) protected
Definition at line 88 of file G4MuonDecayChannel.cc.
View newest version in sPHENIX GitHub at line 88 of file G4MuonDecayChannel.cc
G4MuonDecayChannel::G4MuonDecayChannel () protected
Definition at line 53 of file G4MuonDecayChannel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4MuonDecayChannel.cc
Member Function Documentation
G4DecayProducts * G4MuonDecayChannel::DecayIt (G4double) virtual
Implements G4VDecayChannel.
Reimplemented in G4MuonDecayChannelWithSpin.
Definition at line 124 of file G4MuonDecayChannel.cc.
View newest version in sPHENIX GitHub at line 124 of file G4MuonDecayChannel.cc
References G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), G4DecayProducts::DumpInfo(), G4cout, G4endl, G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4InuclParticleNames::gam, G4ParticleDefinition::GetPDGMass(), G4VDecayChannel::GetVerboseLevel(), G4DecayProducts::PushProducts(), rad, CLHEP::HepRotation::set(), twopi, x, and xmax.
G4MuonDecayChannel & G4MuonDecayChannel::operator= (const G4MuonDecayChannel & right) protected
Definition at line 97 of file G4MuonDecayChannel.cc.
View newest version in sPHENIX GitHub at line 97 of file G4MuonDecayChannel.cc
References G4VDecayChannel::ClearDaughtersName(), G4VDecayChannel::daughters_name, G4VDecayChannel::kinematics_name, G4VDecayChannel::numberOfDaughters, G4VDecayChannel::parent_name, G4VDecayChannel::rbranch, and G4VDecayChannel::verboseLevel.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4MuonDecayChannel.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4MuonDecayChannel.cc