ECCE @ EIC Software: ExN02DetectorConstruction Class Reference
ExN02DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/ExN02DetectorConstruction.hh>
Public Member Functions
ExN02DetectorConstruction ()
~ExN02DetectorConstruction ()
G4VPhysicalVolume * Construct ()
const G4VPhysicalVolume * GetTracker ()
G4double GetTrackerFullLength ()
G4double GetTargetFullLength ()
G4double GetWorldFullLength ()
void setTargetMaterial (G4String)
void setChamberMaterial (G4String)
void SetMagField (G4double)
void SetMaxStep (G4double)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void ConstructSDandField ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4Box * solidWorld
G4LogicalVolume * logicWorld
G4VPhysicalVolume * physiWorld
G4Box * solidTarget
G4LogicalVolume * logicTarget
G4VPhysicalVolume * physiTarget
G4Box * solidTracker
G4LogicalVolume * logicTracker
G4VPhysicalVolume * physiTracker
G4Box * solidChamber
G4LogicalVolume * logicChamber
G4VPhysicalVolume * physiChamber
G4Material * TargetMater
G4Material * ChamberMater
G4VPVParameterisation * chamberParam
G4UserLimits * stepLimit
ExN02MagneticField * fpMagField
ExN02DetectorMessenger * detectorMessenger
G4double fWorldLength
G4double fTargetLength
G4double fTrackerLength
G4int NbOfChambers
G4double ChamberWidth
G4double ChamberSpacing
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 51 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 51 of file ExN02DetectorConstruction.hh
Constructor & Destructor Documentation
ExN02DetectorConstruction::ExN02DetectorConstruction ()
Definition at line 59 of file ExN02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 59 of file ExN02DetectorConstruction.cc
References detectorMessenger, and fpMagField.
ExN02DetectorConstruction::~ExN02DetectorConstruction ()
Definition at line 75 of file ExN02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 75 of file ExN02DetectorConstruction.cc
References chamberParam, detectorMessenger, fpMagField, and stepLimit.
Member Function Documentation
G4VPhysicalVolume * ExN02DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 85 of file ExN02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 85 of file ExN02DetectorConstruction.cc
References a, G4Material::AddElement(), G4SDManager::AddNewDetector(), atmosphere, ChamberMater, chamberParam, ChamberSpacing, ChamberWidth, cm, cm3, fTargetLength, fTrackerLength, fWorldLength, Acts::UnitConstants::g, G4cout, G4endl, G4GeometryTolerance::GetInstance(), G4GeometryManager::GetInstance(), G4Material::GetMaterialTable(), G4Material::GetName(), G4SDManager::GetSDMpointer(), G4GeometryTolerance::GetSurfaceTolerance(), kelvin, kStateGas, kZAxis, logicChamber, logicTarget, logicTracker, logicWorld, mg, mm, mole, N, NbOfChambers, perCent, physiChamber, physiTarget, physiTracker, physiWorld, G4LogicalVolume::SetSensitiveDetector(), G4LogicalVolume::SetUserLimits(), G4LogicalVolume::SetVisAttributes(), G4GeometryManager::SetWorldMaximumExtent(), solidChamber, solidTarget, solidTracker, solidWorld, stepLimit, TargetMater, and z.
G4double ExN02DetectorConstruction::GetTargetFullLength () inline
Definition at line 65 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 65 of file ExN02DetectorConstruction.hh
References fTargetLength.
const G4VPhysicalVolume* ExN02DetectorConstruction::GetTracker () inline
Definition at line 63 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 63 of file ExN02DetectorConstruction.hh
References physiTracker.
G4double ExN02DetectorConstruction::GetTrackerFullLength () inline
Definition at line 64 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 64 of file ExN02DetectorConstruction.hh
References fTrackerLength.
G4double ExN02DetectorConstruction::GetWorldFullLength () inline
Definition at line 66 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 66 of file ExN02DetectorConstruction.hh
References fWorldLength.
Referenced by ExN02PrimaryGeneratorAction::GeneratePrimaries().
void ExN02DetectorConstruction::setChamberMaterial (G4String materialName)
Definition at line 288 of file ExN02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 288 of file ExN02DetectorConstruction.cc
References ChamberMater, ChamberWidth, cm, G4cout, G4endl, G4Material::GetMaterial(), logicChamber, and G4LogicalVolume::SetMaterial().
Referenced by ExN02DetectorMessenger::SetNewValue().
void ExN02DetectorConstruction::SetMagField (G4double fieldValue)
Definition at line 302 of file ExN02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 302 of file ExN02DetectorConstruction.cc
References fpMagField, and ExN02MagneticField::SetMagFieldValue().
Referenced by ExN02DetectorMessenger::SetNewValue().
void ExN02DetectorConstruction::SetMaxStep (G4double maxStep)
Definition at line 309 of file ExN02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 309 of file ExN02DetectorConstruction.cc
References G4UserLimits::SetMaxAllowedStep(), and stepLimit.
Referenced by ExN02DetectorMessenger::SetNewValue().
void ExN02DetectorConstruction::setTargetMaterial (G4String materialName)
Definition at line 274 of file ExN02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 274 of file ExN02DetectorConstruction.cc
References cm, fTargetLength, G4cout, G4endl, G4Material::GetMaterial(), logicTarget, G4LogicalVolume::SetMaterial(), and TargetMater.
Referenced by ExN02DetectorMessenger::SetNewValue().
Member Data Documentation
G4Material* ExN02DetectorConstruction::ChamberMater private
Definition at line 92 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 92 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and setChamberMaterial().
G4VPVParameterisation* ExN02DetectorConstruction::chamberParam private
Definition at line 94 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and ~ExN02DetectorConstruction().
G4double ExN02DetectorConstruction::ChamberSpacing private
Definition at line 106 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4double ExN02DetectorConstruction::ChamberWidth private
Definition at line 105 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and setChamberMaterial().
ExN02DetectorMessenger* ExN02DetectorConstruction::detectorMessenger private
Definition at line 99 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 99 of file ExN02DetectorConstruction.hh
Referenced by ExN02DetectorConstruction(), and ~ExN02DetectorConstruction().
ExN02MagneticField* ExN02DetectorConstruction::fpMagField private
Definition at line 97 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 97 of file ExN02DetectorConstruction.hh
Referenced by ExN02DetectorConstruction(), SetMagField(), and ~ExN02DetectorConstruction().
G4double ExN02DetectorConstruction::fTargetLength private
Definition at line 102 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 102 of file ExN02DetectorConstruction.hh
Referenced by Construct(), GetTargetFullLength(), and setTargetMaterial().
G4double ExN02DetectorConstruction::fTrackerLength private
Definition at line 103 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 103 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and GetTrackerFullLength().
G4double ExN02DetectorConstruction::fWorldLength private
Definition at line 101 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 101 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and GetWorldFullLength().
G4LogicalVolume* ExN02DetectorConstruction::logicChamber private
Definition at line 88 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 88 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and setChamberMaterial().
G4LogicalVolume* ExN02DetectorConstruction::logicTarget private
Definition at line 80 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and setTargetMaterial().
G4LogicalVolume* ExN02DetectorConstruction::logicTracker private
Definition at line 84 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4LogicalVolume* ExN02DetectorConstruction::logicWorld private
Definition at line 76 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4int ExN02DetectorConstruction::NbOfChambers private
Definition at line 104 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4VPhysicalVolume* ExN02DetectorConstruction::physiChamber private
Definition at line 89 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 89 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4VPhysicalVolume* ExN02DetectorConstruction::physiTarget private
Definition at line 81 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 81 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4VPhysicalVolume* ExN02DetectorConstruction::physiTracker private
Definition at line 85 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and GetTracker().
G4VPhysicalVolume* ExN02DetectorConstruction::physiWorld private
Definition at line 77 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 77 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4Box* ExN02DetectorConstruction::solidChamber private
Definition at line 87 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4Box* ExN02DetectorConstruction::solidTarget private
Definition at line 79 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 79 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4Box* ExN02DetectorConstruction::solidTracker private
Definition at line 83 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 83 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4Box* ExN02DetectorConstruction::solidWorld private
Definition at line 75 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 75 of file ExN02DetectorConstruction.hh
Referenced by Construct().
G4UserLimits* ExN02DetectorConstruction::stepLimit private
Definition at line 95 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 95 of file ExN02DetectorConstruction.hh
Referenced by Construct(), SetMaxStep(), and ~ExN02DetectorConstruction().
G4Material* ExN02DetectorConstruction::TargetMater private
Definition at line 91 of file ExN02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file ExN02DetectorConstruction.hh
Referenced by Construct(), and setTargetMaterial().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/ExN02DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/src/ExN02DetectorConstruction.cc