ECCE @ EIC Software: G4ParticleHPIsoData Class Reference
G4ParticleHPIsoData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPIsoData.hh>
Public Member Functions
G4ParticleHPIsoData ()
~G4ParticleHPIsoData ()
G4double GetXsec (G4double energy)
G4bool Init (G4int A, G4int Z, G4double abun, G4String dirName, G4String aFSType)
G4bool Init (G4int A, G4int Z, G4int M, G4double abun, G4String dirName, G4String aFSType)
void Init (G4int A, G4int Z, G4double abun, G4ParticleDefinition *projectile, const char *dataDirVariable)
void Init (G4int A, G4int Z, G4int M, G4double abun, G4ParticleDefinition *projectile, const char *dataDirVariable)
G4ParticleHPVector * MakeElasticData ()
G4ParticleHPVector * MakeFissionData ()
G4ParticleHPVector * MakeCaptureData ()
G4ParticleHPVector * MakeInelasticData ()
G4ParticleHPVector * MakeChannelData ()
G4String GetName (G4int A, G4int Z, G4String base, G4String rest)
void FillChannelData (G4ParticleHPVector *aBuffer)
void ThinOut (G4double precision)
Private Attributes
G4ParticleHPVector * theFissionData
G4ParticleHPVector * theCaptureData
G4ParticleHPVector * theElasticData
G4ParticleHPVector * theInelasticData
G4ParticleHPVector * theChannelData
G4String theFileName
G4ParticleHPNames theNames
Detailed Description
Definition at line 45 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPIsoData.hh
Constructor & Destructor Documentation
G4ParticleHPIsoData::G4ParticleHPIsoData () inline
Definition at line 49 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPIsoData.hh
References theCaptureData, theChannelData, theElasticData, theFissionData, and theInelasticData.
G4ParticleHPIsoData::~G4ParticleHPIsoData () inline
Definition at line 58 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPIsoData.hh
References theChannelData.
Member Function Documentation
void G4ParticleHPIsoData::FillChannelData (G4ParticleHPVector * aBuffer) inline
Definition at line 87 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPIsoData.hh
References G4ParticleHPVector::GetPoint(), G4ParticleHPVector::GetVectorLength(), G4ParticleHPVector::Hash(), G4ParticleHPVector::SetPoint(), and theChannelData.
Referenced by G4ParticleHPChannel::UpdateData().
G4String G4ParticleHPIsoData::GetName (G4int A, G4int Z, G4String base, G4String rest)
Definition at line 170 of file G4ParticleHPIsoData.cc.
View newest version in sPHENIX GitHub at line 170 of file G4ParticleHPIsoData.cc
References G4ParticleHPNames::GetName(), and theNames.
G4double G4ParticleHPIsoData::GetXsec (G4double energy) inline
Definition at line 60 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPIsoData.hh
References G4ParticleHPVector::GetXsec(), max, and theChannelData.
Referenced by G4ParticleHPChannel::ApplyYourself(), and G4ParticleHPChannel::GetWeightedXsec().
G4bool G4ParticleHPIsoData::Init (G4int A, G4int Z, G4double abun, G4String dirName, G4String aFSType) inline
Definition at line 66 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPIsoData.hh
References Init().
Referenced by Init(), G4ParticleHPElementData::UpdateData(), and G4ParticleHPChannel::UpdateData().
G4bool G4ParticleHPIsoData::Init (G4int A, G4int Z, G4int M, G4double abun, G4String dirName, G4String aFSType)
Definition at line 39 of file G4ParticleHPIsoData.cc.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleHPIsoData.cc
References A(), kdfinder::abs(), CLHEP::barn, CLHEP::eV, INPUTHEPMC::filename, G4cout, G4endl, G4ParticleHPDataUsed::GetA(), G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPDataUsed::GetZ(), in, G4ParticleHPVector::Init(), theChannelData, and theNames.
void G4ParticleHPIsoData::Init (G4int A, G4int Z, G4double abun, G4ParticleDefinition * projectile, const char * dataDirVariable) inline
Definition at line 70 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPIsoData.hh
References Init().
void G4ParticleHPIsoData::Init (G4int A, G4int Z, G4int M, G4double abun, G4ParticleDefinition * projectile, const char * dataDirVariable)
Definition at line 90 of file G4ParticleHPIsoData.cc.
View newest version in sPHENIX GitHub at line 90 of file G4ParticleHPIsoData.cc
References G4Alpha::Alpha(), G4Deuteron::Deuteron(), G4ParticleDefinition::GetParticleName(), G4He3::He3(), Init(), message(), G4Neutron::Neutron(), G4Proton::Proton(), theCaptureData, theChannelData, theElasticData, theFissionData, theInelasticData, and G4Triton::Triton().
G4ParticleHPVector* G4ParticleHPIsoData::MakeCaptureData () inline
Definition at line 78 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleHPIsoData.hh
References theCaptureData.
Referenced by G4ParticleHPElementData::UpdateData().
G4ParticleHPVector* G4ParticleHPIsoData::MakeChannelData () inline
Definition at line 82 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPIsoData.hh
References theChannelData.
Referenced by G4ParticleHPChannel::UpdateData().
G4ParticleHPVector* G4ParticleHPIsoData::MakeElasticData () inline
Definition at line 74 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleHPIsoData.hh
References theElasticData.
Referenced by G4ParticleHPElementData::UpdateData().
G4ParticleHPVector* G4ParticleHPIsoData::MakeFissionData () inline
Definition at line 76 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleHPIsoData.hh
References theFissionData.
Referenced by G4ParticleHPElementData::UpdateData().
G4ParticleHPVector* G4ParticleHPIsoData::MakeInelasticData () inline
Definition at line 80 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleHPIsoData.hh
References theInelasticData.
Referenced by G4ParticleHPElementData::UpdateData().
void G4ParticleHPIsoData::ThinOut (G4double precision) inline
Definition at line 98 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPIsoData.hh
References theCaptureData, theElasticData, theFissionData, theInelasticData, and G4ParticleHPVector::ThinOut().
Member Data Documentation
G4ParticleHPVector* G4ParticleHPIsoData::theCaptureData private
Definition at line 109 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPIsoData.hh
Referenced by G4ParticleHPIsoData(), Init(), MakeCaptureData(), and ThinOut().
G4ParticleHPVector* G4ParticleHPIsoData::theChannelData private
Definition at line 112 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPIsoData.hh
Referenced by FillChannelData(), G4ParticleHPIsoData(), GetXsec(), Init(), MakeChannelData(), and ~G4ParticleHPIsoData().
G4ParticleHPVector* G4ParticleHPIsoData::theElasticData private
Definition at line 110 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPIsoData.hh
Referenced by G4ParticleHPIsoData(), Init(), MakeElasticData(), and ThinOut().
G4String G4ParticleHPIsoData::theFileName private
Definition at line 114 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleHPIsoData.hh
G4ParticleHPVector* G4ParticleHPIsoData::theFissionData private
Definition at line 108 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPIsoData.hh
Referenced by G4ParticleHPIsoData(), Init(), MakeFissionData(), and ThinOut().
G4ParticleHPVector* G4ParticleHPIsoData::theInelasticData private
Definition at line 111 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPIsoData.hh
Referenced by G4ParticleHPIsoData(), Init(), MakeInelasticData(), and ThinOut().
G4ParticleHPNames G4ParticleHPIsoData::theNames private
Definition at line 115 of file G4ParticleHPIsoData.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ParticleHPIsoData.hh
Referenced by GetName(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPIsoData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPIsoData.cc