ECCE @ EIC Software: G4InuclEvaporation Class Reference
G4InuclEvaporation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclEvaporation.hh>
Public Member Functions
G4InuclEvaporation ()
~G4InuclEvaporation ()
G4FragmentVector * BreakItUp (const G4Fragment &theNucleus)
void setVerboseLevel (const G4int verbose)
Public Member Functions inherited from G4VEvaporation
G4VEvaporation ()
virtual ~G4VEvaporation ()
virtual void BreakFragment (G4FragmentVector *, G4Fragment *theNucleus)
virtual void InitialiseChannels ()
virtual void SetPhotonEvaporation (G4VEvaporationChannel *ptr)
void SetFermiBreakUp (G4VFermiBreakUp *ptr)
G4VFermiBreakUp * GetFermiBreakUp () const
G4VEvaporationChannel * GetPhotonEvaporation ()
G4VEvaporationChannel * GetFissionChannel ()
void SetOPTxs (G4int opt)
void UseSICB (G4bool use)
size_t GetNumberOfChannels () const
Private Member Functions
G4InuclEvaporation (const G4InuclEvaporation &right)
const G4InuclEvaporation & operator= (const G4InuclEvaporation &right)
G4bool operator== (const G4InuclEvaporation &right) const
G4bool operator!= (const G4InuclEvaporation &right) const
Private Attributes
G4int verboseLevel
G4EvaporationInuclCollider * evaporator
Additional Inherited Members
Protected Member Functions inherited from G4VEvaporation
void CleanChannels ()
Protected Attributes inherited from G4VEvaporation
G4VEvaporationChannel * thePhotonEvaporation
G4VFermiBreakUp * theFBU
G4int OPTxs
G4bool useSICB
std::vector
< G4VEvaporationChannel * > * theChannels
G4VEvaporationFactory * theChannelFactory
Detailed Description
Definition at line 43 of file G4InuclEvaporation.hh.
View newest version in sPHENIX GitHub at line 43 of file G4InuclEvaporation.hh
Constructor & Destructor Documentation
G4InuclEvaporation::G4InuclEvaporation ()
Definition at line 72 of file G4InuclEvaporation.cc.
View newest version in sPHENIX GitHub at line 72 of file G4InuclEvaporation.cc
G4InuclEvaporation::~G4InuclEvaporation ()
Definition at line 79 of file G4InuclEvaporation.cc.
View newest version in sPHENIX GitHub at line 79 of file G4InuclEvaporation.cc
References evaporator.
G4InuclEvaporation::G4InuclEvaporation (const G4InuclEvaporation & right) private
Definition at line 75 of file G4InuclEvaporation.cc.
View newest version in sPHENIX GitHub at line 75 of file G4InuclEvaporation.cc
Member Function Documentation
G4FragmentVector * G4InuclEvaporation::BreakItUp (const G4Fragment & theNucleus)
Definition at line 100 of file G4InuclEvaporation.cc.
View newest version in sPHENIX GitHub at line 100 of file G4InuclEvaporation.cc
References A(), CLHEP::HepLorentzVector::boost(), G4VCascadeDeexcitation::collide(), evaporator, G4cout, G4endl, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetMomentum(), G4NucleiProperties::GetNuclearMass(), G4CollisionOutput::getOutgoingNuclei(), G4CollisionOutput::getOutgoingParticles(), CLHEP::HepLorentzVector::getZ(), G4Fragment::GetZ_asInt(), GeV, ipart, mass, momentum, G4InuclNuclei::setExitationEnergy(), CLHEP::HepLorentzVector::vect(), verboseLevel, and Z.
G4bool G4InuclEvaporation::operator!= (const G4InuclEvaporation & right) const private
Definition at line 92 of file G4InuclEvaporation.cc.
View newest version in sPHENIX GitHub at line 92 of file G4InuclEvaporation.cc
const G4InuclEvaporation & G4InuclEvaporation::operator= (const G4InuclEvaporation & right) private
Definition at line 83 of file G4InuclEvaporation.cc.
View newest version in sPHENIX GitHub at line 83 of file G4InuclEvaporation.cc
G4bool G4InuclEvaporation::operator== (const G4InuclEvaporation & right) const private
Definition at line 88 of file G4InuclEvaporation.cc.
View newest version in sPHENIX GitHub at line 88 of file G4InuclEvaporation.cc
void G4InuclEvaporation::setVerboseLevel (const G4int verbose)
Definition at line 96 of file G4InuclEvaporation.cc.
View newest version in sPHENIX GitHub at line 96 of file G4InuclEvaporation.cc
References verboseLevel.
Member Data Documentation
G4EvaporationInuclCollider* G4InuclEvaporation::evaporator private
Definition at line 62 of file G4InuclEvaporation.hh.
View newest version in sPHENIX GitHub at line 62 of file G4InuclEvaporation.hh
Referenced by BreakItUp(), and ~G4InuclEvaporation().
G4int G4InuclEvaporation::verboseLevel private
Definition at line 61 of file G4InuclEvaporation.hh.
View newest version in sPHENIX GitHub at line 61 of file G4InuclEvaporation.hh
Referenced by BreakItUp(), and setVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4InuclEvaporation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4InuclEvaporation.cc