ECCE @ EIC Software: G4GDMLWriteStructure Class Reference
G4GDMLWriteStructure Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteStructure.hh>
Public Member Functions
G4GDMLWriteStructure ()
virtual ~G4GDMLWriteStructure ()
virtual void StructureWrite (xercesc::DOMElement *)
void AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume *const)
void SetEnergyCutsExport (G4bool)
void SetSDExport (G4bool)
G4int GetMaxExportLevel () const
void SetMaxExportLevel (G4int)
Public Member Functions inherited from G4GDMLWriteParamvol
virtual void ParamvolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const)
virtual void ParamvolAlgorithmWrite (xercesc::DOMElement *paramvolElement, const G4VPhysicalVolume *const paramvol)
Public Member Functions inherited from G4GDMLWriteSetup
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)
Public Member Functions inherited from G4GDMLWriteSolids
virtual void AddSolid (const G4VSolid *const)
virtual void SolidsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteMaterials
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from G4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (G4GDMLAuxStructType myaux)
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
void DivisionvolWrite (xercesc::DOMElement *, const G4PVDivision *const)
void PhysvolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const topVol, const G4Transform3D &transform, const G4String &moduleName)
void ReplicavolWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const)
void AssemblyWrite (xercesc::DOMElement *, const int assemblyID)
G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const topVol, const G4int depth)
void SurfacesWrite ()
void BorderSurfaceCache (const G4LogicalBorderSurface *const)
void SkinSurfaceCache (const G4LogicalSkinSurface *const)
const G4LogicalBorderSurface * GetBorderSurface (const G4VPhysicalVolume *const)
const G4LogicalSkinSurface * GetSkinSurface (const G4LogicalVolume *const)
G4bool FindOpticalSurface (const G4SurfaceProperty *)
void ExportEnergyCuts (const G4LogicalVolume *const)
void ExportSD (const G4LogicalVolume *const)
Protected Member Functions inherited from G4GDMLWriteParamvol
G4GDMLWriteParamvol ()
virtual ~G4GDMLWriteParamvol ()
void Box_dimensionsWrite (xercesc::DOMElement *, const G4Box *const)
void Trd_dimensionsWrite (xercesc::DOMElement *, const G4Trd *const)
void Trap_dimensionsWrite (xercesc::DOMElement *, const G4Trap *const)
void Tube_dimensionsWrite (xercesc::DOMElement *, const G4Tubs *const)
void Cone_dimensionsWrite (xercesc::DOMElement *, const G4Cons *const)
void Sphere_dimensionsWrite (xercesc::DOMElement *, const G4Sphere *const)
void Orb_dimensionsWrite (xercesc::DOMElement *, const G4Orb *const)
void Torus_dimensionsWrite (xercesc::DOMElement *, const G4Torus *const)
void Ellipsoid_dimensionsWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void Para_dimensionsWrite (xercesc::DOMElement *, const G4Para *const)
void Hype_dimensionsWrite (xercesc::DOMElement *, const G4Hype *const)
void Polycone_dimensionsWrite (xercesc::DOMElement *, const G4Polycone *const)
void Polyhedra_dimensionsWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void ParametersWrite (xercesc::DOMElement *, const G4VPhysicalVolume *const, const G4int &)
Protected Member Functions inherited from G4GDMLWriteSetup
G4GDMLWriteSetup ()
virtual ~G4GDMLWriteSetup ()
Protected Member Functions inherited from G4GDMLWriteSolids
G4GDMLWriteSolids ()
virtual ~G4GDMLWriteSolids ()
void MultiUnionWrite (xercesc::DOMElement *solElement, const G4MultiUnion *const)
void BooleanWrite (xercesc::DOMElement *, const G4BooleanSolid *const)
void ScaledWrite (xercesc::DOMElement *, const G4ScaledSolid *const)
void BoxWrite (xercesc::DOMElement *, const G4Box *const)
void ConeWrite (xercesc::DOMElement *, const G4Cons *const)
void ElconeWrite (xercesc::DOMElement *, const G4EllipticalCone *const)
void EllipsoidWrite (xercesc::DOMElement *, const G4Ellipsoid *const)
void EltubeWrite (xercesc::DOMElement *, const G4EllipticalTube *const)
void XtruWrite (xercesc::DOMElement *, const G4ExtrudedSolid *const)
void HypeWrite (xercesc::DOMElement *, const G4Hype *const)
void OrbWrite (xercesc::DOMElement *, const G4Orb *const)
void ParaWrite (xercesc::DOMElement *, const G4Para *const)
void ParaboloidWrite (xercesc::DOMElement *, const G4Paraboloid *const)
void PolyconeWrite (xercesc::DOMElement *, const G4Polycone *const)
void GenericPolyconeWrite (xercesc::DOMElement *, const G4GenericPolycone *const)
void PolyhedraWrite (xercesc::DOMElement *, const G4Polyhedra *const)
void SphereWrite (xercesc::DOMElement *, const G4Sphere *const)
void TessellatedWrite (xercesc::DOMElement *, const G4TessellatedSolid *const)
void TetWrite (xercesc::DOMElement *, const G4Tet *const)
void TorusWrite (xercesc::DOMElement *, const G4Torus *const)
void GenTrapWrite (xercesc::DOMElement *, const G4GenericTrap *const)
void TrapWrite (xercesc::DOMElement *, const G4Trap *const)
void TrdWrite (xercesc::DOMElement *, const G4Trd *const)
void TubeWrite (xercesc::DOMElement *, const G4Tubs *const)
void CutTubeWrite (xercesc::DOMElement *, const G4CutTubs *const)
void TwistedboxWrite (xercesc::DOMElement *, const G4TwistedBox *const)
void TwistedtrapWrite (xercesc::DOMElement *, const G4TwistedTrap *const)
void TwistedtrdWrite (xercesc::DOMElement *, const G4TwistedTrd *const)
void TwistedtubsWrite (xercesc::DOMElement *, const G4TwistedTubs *const)
void ZplaneWrite (xercesc::DOMElement *, const G4double &, const G4double &, const G4double &)
void RZPointWrite (xercesc::DOMElement *, const G4double &, const G4double &)
void OpticalSurfaceWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
void PropertyWrite (xercesc::DOMElement *, const G4OpticalSurface *const)
Protected Member Functions inherited from G4GDMLWriteMaterials
G4GDMLWriteMaterials ()
virtual ~G4GDMLWriteMaterials ()
void AtomWrite (xercesc::DOMElement *, const G4double &)
void DWrite (xercesc::DOMElement *, const G4double &)
void PWrite (xercesc::DOMElement *, const G4double &)
void TWrite (xercesc::DOMElement *, const G4double &)
void MEEWrite (xercesc::DOMElement *, const G4double &)
void IsotopeWrite (const G4Isotope *const)
void ElementWrite (const G4Element *const)
void MaterialWrite (const G4Material *const)
void PropertyWrite (xercesc::DOMElement *, const G4Material *const)
void PropertyVectorWrite (const G4String &, const G4PhysicsOrderedFreeVector *const)
Protected Member Functions inherited from G4GDMLWriteDefine
G4GDMLWriteDefine ()
virtual ~G4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from G4GDMLWrite
G4GDMLWrite ()
virtual ~G4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (G4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Protected Attributes
xercesc::DOMElement * structureElement
std::vector
< xercesc::DOMElement * > borderElementVec
std::vector
< xercesc::DOMElement * > skinElementVec
std::map< const
G4LogicalVolume
*, G4GDMLAuxListType > auxmap
Private Attributes
std::vector< const
G4OpticalSurface * > opt_vec
G4ReflectionFactory * reflFactory
G4bool cexport
G4bool sdexport
G4int maxLevel
std::map< const
G4VPhysicalVolume *, G4int > assemblyVolMap
std::map< const
G4VPhysicalVolume *, G4int > imprintsMap
std::vector< int > addedAssemblies
Static Private Attributes
static G4int levelNo = 0
Additional Inherited Members
Static Public Member Functions inherited from G4GDMLWrite
static void SetAddPointerToName (G4bool)
Static Protected Attributes inherited from G4GDMLWriteSolids
static const G4int maxTransforms = 8
Detailed Description
Definition at line 56 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 56 of file G4GDMLWriteStructure.hh
Constructor & Destructor Documentation
G4GDMLWriteStructure::G4GDMLWriteStructure ()
Definition at line 63 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 63 of file G4GDMLWriteStructure.cc
References G4ReflectionFactory::Instance(), and reflFactory.
G4GDMLWriteStructure::~G4GDMLWriteStructure () virtual
Definition at line 69 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 69 of file G4GDMLWriteStructure.cc
Member Function Documentation
void G4GDMLWriteStructure::AddVolumeAuxiliary (G4GDMLAuxStructType myaux, const G4LogicalVolume * const lvol)
Definition at line 754 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 754 of file G4GDMLWriteStructure.cc
References auxmap, and pos().
Referenced by ExportEnergyCuts(), and ExportSD().
void G4GDMLWriteStructure::AssemblyWrite (xercesc::DOMElement * volumeElement, const int assemblyID) protected
Definition at line 235 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 235 of file G4GDMLWriteStructure.cc
References G4GDMLWrite::GenerateName(), G4GDMLWriteDefine::GetAngles(), G4AssemblyStore::GetAssembly(), G4AssemblyStore::GetInstance(), G4AssemblyVolume::GetTripletsIterator(), G4GDMLWriteDefine::kAngularPrecision, G4GDMLWriteDefine::kLinearPrecision, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), pname(), pos(), G4GDMLWriteDefine::PositionWrite(), G4GDMLWriteDefine::RotationWrite(), nlohmann::to_string(), G4AssemblyVolume::TotalTriplets(), and TraverseVolumeTree().
Referenced by TraverseVolumeTree().
void G4GDMLWriteStructure::BorderSurfaceCache (const G4LogicalBorderSurface * const bsurf) protected
Definition at line 292 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 292 of file G4GDMLWriteStructure.cc
References borderElementVec, FatalException, FindOpticalSurface(), G4Exception(), G4GDMLWrite::GenerateName(), G4LogicalSurface::GetName(), G4SurfaceProperty::GetName(), G4VPhysicalVolume::GetName(), G4LogicalSurface::GetSurfaceProperty(), G4LogicalBorderSurface::GetVolume1(), G4LogicalBorderSurface::GetVolume2(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), G4GDMLWriteSolids::OpticalSurfaceWrite(), and G4GDMLWriteSolids::solidsElement.
Referenced by GetBorderSurface().
void G4GDMLWriteStructure::DivisionvolWrite (xercesc::DOMElement * volumeElement, const G4PVDivision * const divisionvol) protected
Definition at line 74 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 74 of file G4GDMLWriteStructure.cc
References G4GDMLWrite::GenerateName(), G4PVDivision::GetDivisionAxis(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4PVDivision::GetReplicationData(), kPhi, kRho, kUndefined, kXAxis, kYAxis, kZAxis, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), offset, and width.
Referenced by TraverseVolumeTree().
void G4GDMLWriteStructure::ExportEnergyCuts (const G4LogicalVolume * const lvol) protected
Definition at line 772 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 772 of file G4GDMLWriteStructure.cc
References AddVolumeAuxiliary(), G4ProductionCutsTable::ConvertRangeToEnergy(), G4GDMLEvaluator::ConvertToString(), G4Electron::Electron(), eplus, G4Gamma::Gamma(), G4LogicalVolume::GetMaterial(), G4ProductionCuts::GetProductionCut(), G4Region::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4LogicalVolume::GetRegion(), G4Positron::Positron(), G4InuclParticleNames::proton, and G4Proton::Proton().
Referenced by TraverseVolumeTree().
void G4GDMLWriteStructure::ExportSD (const G4LogicalVolume * const lvol) protected
Definition at line 814 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 814 of file G4GDMLWriteStructure.cc
References AddVolumeAuxiliary(), G4VSensitiveDetector::GetName(), and G4LogicalVolume::GetSensitiveDetector().
Referenced by TraverseVolumeTree().
G4bool G4GDMLWriteStructure::FindOpticalSurface (const G4SurfaceProperty * psurf) protected
Definition at line 370 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 370 of file G4GDMLWriteStructure.cc
References opt_vec, and pos().
Referenced by BorderSurfaceCache(), and SkinSurfaceCache().
const G4LogicalBorderSurface * G4GDMLWriteStructure::GetBorderSurface (const G4VPhysicalVolume * const pvol) protected
Definition at line 403 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 403 of file G4GDMLWriteStructure.cc
References BorderSurfaceCache(), G4LogicalBorderSurface::GetNumberOfBorderSurfaces(), G4LogicalBorderSurface::GetSurfaceTable(), and pos().
Referenced by TraverseVolumeTree().
G4int G4GDMLWriteStructure::GetMaxExportLevel () const
Definition at line 828 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 828 of file G4GDMLWriteStructure.cc
References maxLevel.
const G4LogicalSkinSurface * G4GDMLWriteStructure::GetSkinSurface (const G4LogicalVolume * const lvol) protected
Definition at line 382 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 382 of file G4GDMLWriteStructure.cc
References G4LogicalSkinSurface::GetNumberOfSkinSurfaces(), G4LogicalSkinSurface::GetSurfaceTable(), and pos().
Referenced by TraverseVolumeTree().
void G4GDMLWriteStructure::PhysvolWrite (xercesc::DOMElement * volumeElement, const G4VPhysicalVolume *const topVol, const G4Transform3D & transform, const G4String & moduleName) protected
Definition at line 112 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 112 of file G4GDMLWriteStructure.cc
References G4GDMLWrite::GenerateName(), G4GDMLWriteDefine::GetAngles(), G4ReflectionFactory::GetConstituentLV(), G4VPhysicalVolume::GetCopyNo(), HepGeom::Transform3D::getDecomposition(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), HepGeom::Transform3D::getRotation(), HepGeom::Transform3D::getTranslation(), G4ReflectionFactory::IsReflected(), G4GDMLWriteDefine::kAngularPrecision, G4GDMLWriteDefine::kLinearPrecision, G4GDMLWriteDefine::kRelativePrecision, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), pos(), G4GDMLWriteDefine::PositionWrite(), reflFactory, G4GDMLWriteDefine::RotationWrite(), scale, G4GDMLWriteDefine::ScaleWrite(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by TraverseVolumeTree().
void G4GDMLWriteStructure::ReplicavolWrite (xercesc::DOMElement * volumeElement, const G4VPhysicalVolume * const replicavol) protected
Definition at line 183 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 183 of file G4GDMLWriteStructure.cc
References G4GDMLWrite::GenerateName(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetName(), G4VPhysicalVolume::GetReplicationData(), kPhi, kRho, kUndefined, kXAxis, kYAxis, kZAxis, G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), offset, and width.
Referenced by TraverseVolumeTree().
void G4GDMLWriteStructure::SetEnergyCutsExport (G4bool fcuts)
Definition at line 766 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 766 of file G4GDMLWriteStructure.cc
References cexport.
void G4GDMLWriteStructure::SetMaxExportLevel (G4int level)
Definition at line 834 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 834 of file G4GDMLWriteStructure.cc
References FatalException, G4Exception(), levelNo, and maxLevel.
void G4GDMLWriteStructure::SetSDExport (G4bool fsd)
Definition at line 807 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 807 of file G4GDMLWriteStructure.cc
References sdexport.
void G4GDMLWriteStructure::SkinSurfaceCache (const G4LogicalSkinSurface * const ssurf) protected
Definition at line 334 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 334 of file G4GDMLWriteStructure.cc
References FatalException, FindOpticalSurface(), G4Exception(), G4GDMLWrite::GenerateName(), G4LogicalSkinSurface::GetLogicalVolume(), G4LogicalSurface::GetName(), G4SurfaceProperty::GetName(), G4LogicalVolume::GetName(), G4LogicalSurface::GetSurfaceProperty(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), G4GDMLWriteSolids::OpticalSurfaceWrite(), skinElementVec, and G4GDMLWriteSolids::solidsElement.
Referenced by TraverseVolumeTree().
void G4GDMLWriteStructure::StructureWrite (xercesc::DOMElement * gdmlElement) virtual
Implements G4GDMLWrite.
Definition at line 440 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 440 of file G4GDMLWriteStructure.cc
References assemblyVolMap, G4cout, G4endl, G4AssemblyStore::GetInstance(), imprintsMap, it, G4GDMLWrite::NewElement(), pos(), and structureElement.
void G4GDMLWriteStructure::SurfacesWrite () protected virtual
Implements G4GDMLWrite.
Definition at line 424 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 424 of file G4GDMLWriteStructure.cc
References borderElementVec, G4cout, G4endl, pos(), skinElementVec, and structureElement.
G4Transform3D G4GDMLWriteStructure::TraverseVolumeTree (const G4LogicalVolume *const topVol, const G4int depth) protected virtual
Implements G4GDMLWrite.
Definition at line 475 of file G4GDMLWriteStructure.cc.
View newest version in sPHENIX GitHub at line 475 of file G4GDMLWriteStructure.cc
References G4GDMLWrite::AddAuxInfo(), addedAssemblies, G4GDMLWrite::AddExtension(), G4GDMLWriteMaterials::AddMaterial(), G4GDMLWriteSolids::AddSolid(), assemblyVolMap, AssemblyWrite(), auxmap, cexport, DivisionvolWrite(), ExportEnergyCuts(), ExportSD(), FatalException, G4Exception(), G4GDMLWrite::GenerateName(), G4GDMLWriteDefine::GetAngles(), G4AssemblyStore::GetAssembly(), GetBorderSurface(), G4ReflectionFactory::GetConstituentLV(), G4LogicalVolume::GetDaughter(), HepGeom::Transform3D::getDecomposition(), G4VPhysicalVolume::GetFrameRotation(), G4AssemblyVolume::GetImprintTransformation(), G4AssemblyStore::GetInstance(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), G4VSolid::GetName(), G4Material::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), G4VPhysicalVolume::GetObjectTranslation(), HepGeom::Transform3D::getRotation(), GetSkinSurface(), G4LogicalVolume::GetSolid(), HepGeom::Transform3D::getTranslation(), HepGeom::Transform3D::Identity, imprintsMap, HepGeom::Transform3D::inverse(), CLHEP::HepRotation::inverse(), G4VPhysicalVolume::IsParameterised(), G4ReflectionFactory::IsReflected(), G4VPhysicalVolume::IsReplicated(), G4GDMLWriteDefine::kAngularPrecision, G4GDMLWriteDefine::kLinearPrecision, G4GDMLWriteDefine::kRelativePrecision, levelNo, maxLevel, G4GDMLWriteSolids::maxTransforms, G4GDMLWrite::Modularize(), G4GDMLWrite::NewAttribute(), G4GDMLWrite::NewElement(), P, G4GDMLWriteParamvol::ParamvolWrite(), PhysvolWrite(), pos(), G4GDMLWriteDefine::PositionWrite(), Acts::IntegrationTest::R, reflFactory, ReplicavolWrite(), G4GDMLWriteDefine::RotationWrite(), scale, G4GDMLWriteDefine::ScaleWrite(), G4GDMLWrite::SchemaLocation, sdexport, SkinSurfaceCache(), structureElement, nlohmann::to_string(), G4GDMLWrite::VolumeMap(), G4GDMLWrite::Write(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by AssemblyWrite().
Member Data Documentation
std::vector<int> G4GDMLWriteStructure::addedAssemblies private
Definition at line 108 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 108 of file G4GDMLWriteStructure.hh
Referenced by TraverseVolumeTree().
std::map<const G4VPhysicalVolume*, G4int> G4GDMLWriteStructure::assemblyVolMap private
Definition at line 106 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 106 of file G4GDMLWriteStructure.hh
Referenced by StructureWrite(), and TraverseVolumeTree().
std::map<const G4LogicalVolume*, G4GDMLAuxListType> G4GDMLWriteStructure::auxmap protected
Definition at line 96 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 96 of file G4GDMLWriteStructure.hh
Referenced by AddVolumeAuxiliary(), and TraverseVolumeTree().
std::vector<xercesc::DOMElement*> G4GDMLWriteStructure::borderElementVec protected
Definition at line 94 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 94 of file G4GDMLWriteStructure.hh
Referenced by BorderSurfaceCache(), and SurfacesWrite().
G4bool G4GDMLWriteStructure::cexport private
Definition at line 102 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 102 of file G4GDMLWriteStructure.hh
Referenced by SetEnergyCutsExport(), and TraverseVolumeTree().
std::map<const G4VPhysicalVolume*, G4int> G4GDMLWriteStructure::imprintsMap private
Definition at line 107 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 107 of file G4GDMLWriteStructure.hh
Referenced by StructureWrite(), and TraverseVolumeTree().
G4int G4GDMLWriteStructure::levelNo = 0 static private
Definition at line 105 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 105 of file G4GDMLWriteStructure.hh
Referenced by SetMaxExportLevel(), and TraverseVolumeTree().
G4int G4GDMLWriteStructure::maxLevel private
Definition at line 104 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 104 of file G4GDMLWriteStructure.hh
Referenced by GetMaxExportLevel(), SetMaxExportLevel(), and TraverseVolumeTree().
std::vector<const G4OpticalSurface*> G4GDMLWriteStructure::opt_vec private
Definition at line 100 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 100 of file G4GDMLWriteStructure.hh
Referenced by FindOpticalSurface().
G4ReflectionFactory* G4GDMLWriteStructure::reflFactory private
Definition at line 101 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 101 of file G4GDMLWriteStructure.hh
Referenced by G4GDMLWriteStructure(), PhysvolWrite(), and TraverseVolumeTree().
G4bool G4GDMLWriteStructure::sdexport private
Definition at line 103 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 103 of file G4GDMLWriteStructure.hh
Referenced by SetSDExport(), and TraverseVolumeTree().
std::vector<xercesc::DOMElement*> G4GDMLWriteStructure::skinElementVec protected
Definition at line 95 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 95 of file G4GDMLWriteStructure.hh
Referenced by SkinSurfaceCache(), and SurfacesWrite().
xercesc::DOMElement* G4GDMLWriteStructure::structureElement protected
Definition at line 93 of file G4GDMLWriteStructure.hh.
View newest version in sPHENIX GitHub at line 93 of file G4GDMLWriteStructure.hh
Referenced by StructureWrite(), SurfacesWrite(), and TraverseVolumeTree().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLWriteStructure.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLWriteStructure.cc