ECCE @ EIC Software: G4VSolid Class Reference
G4VSolid Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VSolid.hh>
Public Member Functions
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
virtual void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
virtual G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const =0
virtual EInside Inside (const G4ThreeVector &p) const =0
virtual G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const =0
virtual G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const =0
virtual G4double DistanceToIn (const G4ThreeVector &p) const =0
virtual G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const =0
virtual G4double DistanceToOut (const G4ThreeVector &p) const =0
virtual void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
virtual G4double GetCubicVolume ()
virtual G4double GetSurfaceArea ()
virtual G4GeometryType GetEntityType () const =0
virtual G4ThreeVector GetPointOnSurface () const
virtual G4VSolid * Clone () const
virtual std::ostream & StreamInfo (std::ostream &os) const =0
void DumpInfo () const
virtual void DescribeYourselfTo (G4VGraphicsScene &scene) const =0
virtual G4VisExtent GetExtent () const
virtual G4Polyhedron * CreatePolyhedron () const
virtual G4Polyhedron * GetPolyhedron () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Member Functions
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Protected Attributes
G4double kCarTolerance
Private Member Functions
void ClipPolygonToSimpleLimits (G4ThreeVectorList &pPolygon, G4ThreeVectorList &outputPolygon, const G4VoxelLimits &pVoxelLimit) const
Private Attributes
G4String fshapeName
Friends
std::ostream & operator<< (std::ostream &os, const G4VSolid &e)
Detailed Description
Definition at line 82 of file G4VSolid.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VSolid.hh
Constructor & Destructor Documentation
G4VSolid::G4VSolid (const G4String & name)
Definition at line 48 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VSolid.cc
References G4GeometryTolerance::GetInstance(), G4SolidStore::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, and G4SolidStore::Register().
G4VSolid::~G4VSolid () virtual
Definition at line 89 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 89 of file G4VSolid.cc
References G4SolidStore::DeRegister(), and G4SolidStore::GetInstance().
G4VSolid::G4VSolid (__void__ &)
Definition at line 76 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 76 of file G4VSolid.cc
References G4SolidStore::GetInstance(), and G4SolidStore::Register().
G4VSolid::G4VSolid (const G4VSolid & rhs)
Definition at line 63 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 63 of file G4VSolid.cc
References G4SolidStore::GetInstance(), and G4SolidStore::Register().
Member Function Documentation
void G4VSolid::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4ExtrudedSolid, G4Torus, G4Para, G4Tubs, G4EllipticalCone, G4GenericTrap, G4MultiUnion, G4Trd, G4CutTubs, G4Polyhedra, G4Polycone, G4Tet, G4Paraboloid, G4TwistedTubs, G4Ellipsoid, G4GenericPolycone, G4Hype, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Orb, G4EllipticalTube, G4DisplacedSolid, G4VTwistedFaceted, G4Box, G4ReflectedSolid, and G4ScaledSolid.
Definition at line 653 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 653 of file G4VSolid.cc
References G4Exception(), GetEntityType(), JustWarning, kInfinity, message(), and CLHEP::Hep3Vector::set().
Referenced by G4ScaledSolid::BoundingLimits(), G4ReflectedSolid::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4UnionSolid::BoundingLimits(), G4SubtractionSolid::BoundingLimits(), G4Voxelizer::BuildVoxelLimits(), G4ScaledSolid::CalculateExtent(), G4PVPlacement::CheckOverlaps(), EstimateSurfaceArea(), and G4MultiUnion::Extent().
void G4VSolid::CalculateClippedPolygonExtent (G4ThreeVectorList & pPolygon, const G4VoxelLimits & pVoxelLimit, const EAxis pAxis, G4double & pMin, G4double & pMax) const protected
Definition at line 477 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 477 of file G4VSolid.cc
References ClipPolygon().
Referenced by ClipBetweenSections(), and ClipCrossSection().
virtual G4bool G4VSolid::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4ExtrudedSolid, G4Torus, G4Para, G4Tubs, G4EllipticalCone, G4GenericTrap, G4MultiUnion, G4Trd, G4CutTubs, G4Polyhedra, G4Polycone, G4Tet, G4TwistedTubs, G4Paraboloid, G4Ellipsoid, G4Hype, G4GenericPolycone, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Orb, G4EllipticalTube, G4VTwistedFaceted, G4DisplacedSolid, G4Box, G4ReflectedSolid, G4ScaledSolid, and G4VCSGfaceted.
Referenced by G4ReflectedSolid::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4SmartVoxelHeader::BuildNodes(), G4SmartVoxelHeader::BuildReplicaVoxels(), G4SmartVoxelHeader::BuildVoxelsWithinLimits(), G4ReflectedSolid::CalculateExtent(), G4DisplacedSolid::CalculateExtent(), G4IntersectionSolid::CalculateExtent(), G4UnionSolid::CalculateExtent(), G4SubtractionSolid::CalculateExtent(), G4DrawVoxels::ComputeVoxelPolyhedra(), EstimateCubicVolume(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnABoxBoundary(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASphereBoundary(), GetExtent(), and G4ITNavigator2::GetRandomInCurrentVolume().
void G4VSolid::ClipBetweenSections (G4ThreeVectorList * pVertices, const G4int pSectionIndex, const G4VoxelLimits & pVoxelLimit, const EAxis pAxis, G4double & pMin, G4double & pMax) const protected
Definition at line 432 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 432 of file G4VSolid.cc
References CalculateClippedPolygonExtent().
void G4VSolid::ClipCrossSection (G4ThreeVectorList * pVertices, const G4int pSectionIndex, const G4VoxelLimits & pVoxelLimit, const EAxis pAxis, G4double & pMin, G4double & pMax) const protected
Definition at line 402 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 402 of file G4VSolid.cc
References CalculateClippedPolygonExtent().
void G4VSolid::ClipPolygon (G4ThreeVectorList & pPolygon, const G4VoxelLimits & pVoxelLimit, const EAxis pAxis) const protected
Definition at line 527 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 527 of file G4VSolid.cc
References G4VoxelLimits::AddLimit(), ClipPolygonToSimpleLimits(), G4VoxelLimits::GetMaxXExtent(), G4VoxelLimits::GetMaxYExtent(), G4VoxelLimits::GetMaxZExtent(), G4VoxelLimits::GetMinXExtent(), G4VoxelLimits::GetMinYExtent(), G4VoxelLimits::GetMinZExtent(), G4VoxelLimits::IsLimited(), G4VoxelLimits::IsXLimited(), G4VoxelLimits::IsYLimited(), G4VoxelLimits::IsZLimited(), kInfinity, kXAxis, kYAxis, and kZAxis.
Referenced by CalculateClippedPolygonExtent().
void G4VSolid::ClipPolygonToSimpleLimits (G4ThreeVectorList & pPolygon, G4ThreeVectorList & outputPolygon, const G4VoxelLimits & pVoxelLimit) const private
Definition at line 600 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 600 of file G4VSolid.cc
References G4VoxelLimits::ClipToLimits(), and G4VoxelLimits::Inside().
Referenced by ClipPolygon().
G4VSolid * G4VSolid::Clone () const virtual
Reimplemented in G4Trap, G4TessellatedSolid, G4Sphere, G4TwistedTubs, G4Cons, G4Para, G4Torus, G4Tubs, G4EllipticalCone, G4Trd, G4ExtrudedSolid, G4CutTubs, G4GenericTrap, G4MultiUnion, G4Hype, G4Tet, G4Polycone, G4Polyhedra, G4Ellipsoid, G4Paraboloid, G4Orb, G4DisplacedSolid, G4TwistedTrap, G4Box, G4EllipticalTube, G4ScaledSolid, G4GenericPolycone, G4ReflectedSolid, G4TwistedTrd, G4SubtractionSolid, G4TwistedBox, G4IntersectionSolid, and G4UnionSolid.
Definition at line 379 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 379 of file G4VSolid.cc
References G4endl, G4Exception(), GetEntityType(), JustWarning, and message().
Referenced by G4GeometryWorkspace::CloneParameterisedSolids(), and G4GeometryWorkspace::CloneReplicaSolid().
void G4VSolid::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented in G4Trap, G4Torus, G4Sphere, G4Cons, G4Para, G4Tubs, G4Polycone, G4Polyhedra, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Trd, G4DisplacedSolid, G4Tet, G4TwistedTubs, G4Ellipsoid, G4ReflectedSolid, G4Hype, G4ScaledSolid, G4Orb, G4VTwistedFaceted, and G4Box.
Definition at line 125 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 125 of file G4VSolid.cc
References FatalException, G4endl, G4Exception(), and message().
Referenced by G4SmartVoxelHeader::BuildNodes(), G4PVParameterised::CheckOverlaps(), G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4ScoreSplittingProcess::CreateTouchableForSubStep(), G4VFieldModel::DescribeYourselfTo(), G4LogicalVolumeModel::DescribeYourselfTo(), G4LogicalVolume::GetMass(), G4Navigator::GetMotherToDaughterTransform(), G4ITNavigator1::GetMotherToDaughterTransform(), G4ITNavigator2::GetMotherToDaughterTransform(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4ITNavigator1::SetupHierarchy(), G4Navigator::SetupHierarchy(), and G4ITNavigator2::SetupHierarchy().
G4Polyhedron * G4VSolid::CreatePolyhedron () const virtual
Reimplemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Para, G4EllipticalCone, G4Torus, G4Tubs, G4DisplacedSolid, G4Trd, G4GenericTrap, G4CutTubs, G4MultiUnion, G4Tet, G4Hype, G4Ellipsoid, G4Paraboloid, G4Polyhedra, G4TwistedTubs, G4Polycone, G4ReflectedSolid, G4Orb, G4ScaledSolid, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Box, G4EllipticalTube, G4VTwistedFaceted, G4GenericPolycone, and G4VCSGfaceted.
Definition at line 688 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 688 of file G4VSolid.cc
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G4ScaledSolid::CreatePolyhedron(), G4ReflectedSolid::CreatePolyhedron(), G4DisplacedSolid::CreatePolyhedron(), G4CSGSolid::GetPolyhedron(), and G4BooleanSolid::GetPolyhedron().
virtual void G4VSolid::DescribeYourselfTo (G4VGraphicsScene & scene) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Para, G4Torus, G4EllipticalCone, G4Tubs, G4DisplacedSolid, G4Trd, G4CutTubs, G4GenericTrap, G4MultiUnion, G4Tet, G4Hype, G4Ellipsoid, G4Paraboloid, G4TwistedTubs, G4ReflectedSolid, G4Orb, G4EllipticalTube, G4ScaledSolid, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Box, G4VTwistedFaceted, and G4VCSGfaceted.
Referenced by G4VisManager::Draw().
virtual G4double G4VSolid::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Para, G4Torus, G4Tubs, G4EllipticalCone, G4Trd, G4ExtrudedSolid, G4CutTubs, G4Hype, G4Tet, G4GenericTrap, G4TwistedTubs, G4Ellipsoid, G4Paraboloid, G4Polyhedra, G4Polycone, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Box, G4Orb, G4MultiUnion, G4EllipticalTube, G4GenericPolycone, G4DisplacedSolid, G4VTwistedFaceted, G4ReflectedSolid, G4ScaledSolid, and G4VCSGfaceted.
Referenced by G4NavigationLogger::AlongComputeStepLog(), G4NavigationLogger::CheckDaughterEntryPoint(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurfaceStartingFromBox(), G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurfaceStartingFromSphere(), G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ScaledSolid::DistanceToIn(), G4ReflectedSolid::DistanceToIn(), G4MultiUnion::DistanceToIn(), G4DisplacedSolid::DistanceToIn(), G4UnionSolid::DistanceToIn(), G4IntersectionSolid::DistanceToIn(), G4SubtractionSolid::DistanceToIn(), G4MultiUnion::DistanceToInCandidates(), G4MultiUnion::DistanceToInNoVoxels(), G4SubtractionSolid::DistanceToOut(), EstimateSurfaceArea(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASolidBoundary(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), G4NavigationLogger::PreComputeStepLog(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4NavigationLogger::ReportOutsideMother(), G4NavigationLogger::ReportVolumeAndIntersection(), G4VoxelSafety::SafetyForVoxelNode(), G4MultiUnion::SafetyFromOutsideNumberNode(), G4SubtractionSolid::SurfaceNormal(), and G4MultiUnion::SurfaceNormal().
virtual G4double G4VSolid::DistanceToIn (const G4ThreeVector & p) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Para, G4Torus, G4Tubs, G4EllipticalCone, G4Trd, G4ExtrudedSolid, G4CutTubs, G4Hype, G4Tet, G4GenericTrap, G4TwistedTubs, G4Ellipsoid, G4Paraboloid, G4Polyhedra, G4Polycone, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Box, G4Orb, G4EllipticalTube, G4DisplacedSolid, G4GenericPolycone, G4VTwistedFaceted, G4MultiUnion, G4ReflectedSolid, G4ScaledSolid, and G4VCSGfaceted.
virtual G4double G4VSolid::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Para, G4Torus, G4Tubs, G4EllipticalCone, G4Trd, G4ExtrudedSolid, G4CutTubs, G4Hype, G4Tet, G4TwistedTubs, G4GenericTrap, G4Ellipsoid, G4Paraboloid, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Orb, G4Box, G4EllipticalTube, G4MultiUnion, G4DisplacedSolid, G4VTwistedFaceted, G4ReflectedSolid, G4ScaledSolid, and G4VCSGfaceted.
Referenced by G4NavigationLogger::AlongComputeStepLog(), XrayFluoAnalysisManager::analyseStepping(), G4NavigationLogger::CheckDaughterEntryPoint(), G4PVPlacement::CheckOverlaps(), G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4IntersectionSolid::DistanceToIn(), G4SubtractionSolid::DistanceToIn(), G4ScaledSolid::DistanceToOut(), G4ReflectedSolid::DistanceToOut(), G4MultiUnion::DistanceToOut(), G4DisplacedSolid::DistanceToOut(), G4UnionSolid::DistanceToOut(), G4IntersectionSolid::DistanceToOut(), G4SubtractionSolid::DistanceToOut(), G4MultiUnion::DistanceToOutNoVoxels(), G4MultiUnion::DistanceToOutVoxels(), GFlashShowerModel::ElectronDoIt(), EstimateSurfaceArea(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4BOptnForceCommonTruncatedExp::Initialize(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4NavigationLogger::ReportOutsideMother(), G4NavigationLogger::ReportVolumeAndIntersection(), G4IntersectionSolid::SurfaceNormal(), G4SubtractionSolid::SurfaceNormal(), and G4MultiUnion::SurfaceNormal().
virtual G4double G4VSolid::DistanceToOut (const G4ThreeVector & p) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Para, G4Torus, G4Tubs, G4EllipticalCone, G4Trd, G4ExtrudedSolid, G4CutTubs, G4TwistedTubs, G4Hype, G4Tet, G4GenericTrap, G4Ellipsoid, G4Paraboloid, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Orb, G4Box, G4EllipticalTube, G4DisplacedSolid, G4VTwistedFaceted, G4MultiUnion, G4ReflectedSolid, G4ScaledSolid, and G4VCSGfaceted.
void G4VSolid::DumpInfo () const inline
Referenced by G4CutTubs::ApproxSurfaceNormal(), G4Torus::ApproxSurfaceNormal(), G4Tubs::ApproxSurfaceNormal(), G4Cons::ApproxSurfaceNormal(), G4Sphere::ApproxSurfaceNormal(), G4ScaledSolid::BoundingLimits(), G4ReflectedSolid::BoundingLimits(), G4Box::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4Orb::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4UnionSolid::BoundingLimits(), G4SubtractionSolid::BoundingLimits(), G4GenericPolycone::BoundingLimits(), G4Hype::BoundingLimits(), G4Paraboloid::BoundingLimits(), G4TwistedTubs::BoundingLimits(), G4Polycone::BoundingLimits(), G4Polyhedra::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Trd::BoundingLimits(), G4GenericTrap::BoundingLimits(), G4EllipticalCone::BoundingLimits(), G4Tubs::BoundingLimits(), G4Para::BoundingLimits(), G4Torus::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Cons::BoundingLimits(), G4Sphere::BoundingLimits(), G4TessellatedSolid::BoundingLimits(), G4Trap::BoundingLimits(), G4ScaledSolid::ComputeDimensions(), G4ParameterisationTubsRho::ComputeDimensions(), G4ParameterisationBoxX::ComputeDimensions(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationConsRho::ComputeDimensions(), G4ReflectedSolid::ComputeDimensions(), G4ParameterisationPolyconeRho::ComputeDimensions(), G4ParameterisationTrdX::ComputeDimensions(), G4ParameterisationPolyhedraRho::ComputeDimensions(), G4DisplacedSolid::ComputeDimensions(), G4ParameterisationTubsPhi::ComputeDimensions(), G4ParameterisationConsPhi::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationPolyconePhi::ComputeDimensions(), G4ParameterisationTrdY::ComputeDimensions(), G4ParameterisationPolyhedraPhi::ComputeDimensions(), G4ParameterisationTubsZ::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), G4ParameterisationConsZ::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4ParameterisationPolyconeZ::ComputeDimensions(), G4ParameterisationTrdZ::ComputeDimensions(), G4ParameterisationPolyhedraZ::ComputeDimensions(), G4ParameterisedNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ScaledSolid::CreatePolyhedron(), G4DisplacedSolid::CreatePolyhedron(), G4SubtractionSolid::DistanceToIn(), G4VTwistedFaceted::DistanceToOut(), G4EllipticalTube::DistanceToOut(), G4Box::DistanceToOut(), G4Orb::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4GenericTrap::DistanceToOut(), G4CutTubs::DistanceToOut(), G4Trd::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4Tubs::DistanceToOut(), G4Torus::DistanceToOut(), G4Para::DistanceToOut(), G4Cons::DistanceToOut(), G4Sphere::DistanceToOut(), G4Trap::DistanceToOut(), export_G4VSolid(), G4Polycone::G4Polycone(), G4Polyhedra::G4Polyhedra(), G4BooleanSolid::GetConstituentSolid(), G4NavigationLogger::PostComputeStepLog(), G4EllipticalTube::SurfaceNormal(), G4Box::SurfaceNormal(), G4Ellipsoid::SurfaceNormal(), G4Tet::SurfaceNormal(), G4Trd::SurfaceNormal(), G4ExtrudedSolid::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4Para::SurfaceNormal(), and G4Trap::SurfaceNormal().
G4double G4VSolid::EstimateCubicVolume (G4int nStat, G4double epsilon) const
Definition at line 191 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 191 of file G4VSolid.cc
References CalculateExtent(), epsilon(), G4QuickRand(), in, Inside(), kOutside, kXAxis, kYAxis, kZAxis, maxY, maxZ, minY, Acts::Test::origin(), and Acts::Test::volume.
Referenced by G4VCSGfaceted::GetCubicVolume(), and GetCubicVolume().
G4double G4VSolid::EstimateSurfaceArea (G4int nStat, G4double ell) const
Definition at line 253 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 253 of file G4VSolid.cc
References BoundingLimits(), DistanceToIn(), DistanceToOut(), CLHEP::Hep3Vector::dot(), Acts::Test::dX, Acts::Test::dY, eps, G4QuickRand(), in, Inside(), kInfinity, kInside, kOutside, min, minY, n, SurfaceNormal(), v, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4VCSGfaceted::GetSurfaceArea(), G4MultiUnion::GetSurfaceArea(), and GetSurfaceArea().
const G4VSolid * G4VSolid::GetConstituentSolid (G4int no) const virtual
Reimplemented in G4BooleanSolid.
Definition at line 155 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 155 of file G4VSolid.cc
Referenced by G4BooleanSolid::StackPolyhedron().
G4VSolid * G4VSolid::GetConstituentSolid (G4int no) virtual
Reimplemented in G4BooleanSolid.
Definition at line 158 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 158 of file G4VSolid.cc
G4double G4VSolid::GetCubicVolume () virtual
Reimplemented in G4Trap, G4TessellatedSolid, G4TwistedTubs, G4GenericTrap, G4Sphere, G4Hype, G4Tet, G4Cons, G4Torus, G4Ellipsoid, G4MultiUnion, G4Para, G4Tubs, G4EllipticalCone, G4EllipticalTube, G4CutTubs, G4Trd, G4VTwistedFaceted, G4VCSGfaceted, G4Box, G4Paraboloid, G4ScaledSolid, G4BooleanSolid, and G4Orb.
Definition at line 176 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 176 of file G4VSolid.cc
References EstimateCubicVolume().
Referenced by G4PSDoseDeposit::ComputeVolume(), G4PSPassageCellFlux::ComputeVolume(), G4PSCellFlux::ComputeVolume(), G4MIRDLiver::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLeftLegBone::Construct(), G4MIRDRightKidney::Construct(), G4MIRDLeftLung::Construct(), G4MIRDRightLeg::Construct(), G4MIRDRightLegBone::Construct(), G4MIRDLeftOvary::Construct(), G4MIRDLeftAdrenal::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDThyroid::Construct(), G4MIRDLeftTeste::Construct(), G4MIRDSkull::Construct(), G4MIRDSmallIntestine::Construct(), G4MIRDHeart::Construct(), G4MIRDLeftArmBone::Construct(), G4MIRDLowerLargeIntestine::Construct(), G4MIRDMaleGenitalia::Construct(), G4MIRDUpperLargeIntestine::Construct(), G4MIRDPelvis::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDRightAdrenal::Construct(), G4MIRDLeftLeg::Construct(), G4MIRDBrain::Construct(), G4MIRDLeftClavicle::Construct(), G4MIRDRightClavicle::Construct(), G4MIRDHead::Construct(), G4MIRDStomach::Construct(), G4MIRDRightLung::Construct(), G4MIRDRightOvary::Construct(), G4MIRDMiddleLowerSpine::Construct(), G4MIRDThymus::Construct(), G4MIRDRightTeste::Construct(), G4MIRDTrunk::Construct(), G4MIRDLeftBreast::Construct(), G4MIRDSpleen::Construct(), G4MIRDUpperSpine::Construct(), G4MIRDUterus::Construct(), G4MIRDPancreas::Construct(), G4MIRDRibCage::Construct(), G4MIRDRightBreast::Construct(), G4MIRDUrinaryBladder::Construct(), G4MIRDRightArmBone::Construct(), PHG4InnerHcalDetector::ConstructScintillatorBox(), PHG4OuterHcalDetector::ConstructScintillatorBox(), PHG4InnerHcalDetector::ConstructSteelPlate(), PHG4OuterHcalDetector::ConstructSteelPlate(), export_G4VSolid(), G4ScaledSolid::GetCubicVolume(), G4Hype::GetCubicVolume(), G4GenericTrap::GetCubicVolume(), and G4LogicalVolume::GetMass().
const G4DisplacedSolid * G4VSolid::GetDisplacedSolidPtr () const virtual
Reimplemented in G4DisplacedSolid.
Definition at line 161 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 161 of file G4VSolid.cc
G4DisplacedSolid * G4VSolid::GetDisplacedSolidPtr () virtual
Reimplemented in G4DisplacedSolid.
Definition at line 164 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 164 of file G4VSolid.cc
virtual G4GeometryType G4VSolid::GetEntityType () const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4TwistedTubs, G4Sphere, G4Cons, G4Para, G4Torus, G4Tubs, G4EllipticalCone, G4ExtrudedSolid, G4VTwistedFaceted, G4Trd, G4CutTubs, G4MultiUnion, G4GenericTrap, G4Hype, G4Tet, G4Polycone, G4Polyhedra, G4Ellipsoid, G4Paraboloid, G4DisplacedSolid, G4Orb, G4TwistedTrap, G4Box, G4EllipticalTube, G4ScaledSolid, G4GenericPolycone, G4ReflectedSolid, G4BooleanSolid, G4TwistedTrd, G4VCSGfaceted, G4SubtractionSolid, G4TwistedBox, G4IntersectionSolid, and G4UnionSolid.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), PHG4GDMLWriteSolids::AddSolid(), G4GDMLWriteSolids::AddSolid(), BoundingLimits(), G4tgbVolume::BuildSolidForDivision(), G4Voxelizer::BuildVoxelLimits(), G4PVDivision::CheckAndSetParameters(), G4ReplicatedSlice::CheckAndSetParameters(), G4PVPlacement::CheckOverlaps(), Clone(), G4GeometryWorkspace::CloneParameterisedSolids(), G4GeometryWorkspace::CloneReplicaSolid(), G4VoxelNavigation::ComputeSafety(), G4NavigationLogger::ComputeSafetyLog(), G4VDivisionParameterisation::ComputeSolid(), PHG4PhenixDetector::Construct(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4SubtractionSolid::DistanceToIn(), G4tgbGeometryDumper::DumpPVParameterised(), G4tgbGeometryDumper::DumpSolid(), G4PVDivision::ErrorInAxis(), G4ReplicatedSlice::ErrorInAxis(), G4tgbVolume::FindOrConstructG4Solid(), G4DisplacedSolid::G4DisplacedSolid(), G4VParameterisationBox::G4VParameterisationBox(), G4VParameterisationCons::G4VParameterisationCons(), G4VParameterisationPara::G4VParameterisationPara(), G4VParameterisationPolycone::G4VParameterisationPolycone(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), G4VParameterisationTrd::G4VParameterisationTrd(), G4VParameterisationTubs::G4VParameterisationTubs(), G4HepRepSceneHandler::getGeometryInstance(), G4Navigator::GetGlobalExitNormal(), G4BooleanSolid::GetListOfPrimitives(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), GetPointOnSurface(), G4tgbGeometryDumper::GetSolidParams(), G4NavigationLogger::PostComputeStepLog(), G4NavigationLogger::PreComputeStepLog(), G4NavigationLogger::PrintDaughterLog(), G4NavigationLogger::ReportOutsideMother(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VoxelSafety::SafetyForVoxelHeader(), G4PVDivision::SetParameterisation(), G4ReplicatedSlice::SetParameterisation(), G4BooleanSolid::StackPolyhedron(), G4CSGSolid::StreamInfo(), and G4PhysicalVolumeModel::VisitGeometryAndGetVisReps().
G4VisExtent G4VSolid::GetExtent () const virtual
Reimplemented in G4TessellatedSolid, G4Sphere, G4TwistedTubs, G4EllipticalCone, G4GenericTrap, G4VTwistedFaceted, G4Tet, G4Hype, G4Ellipsoid, G4Orb, G4EllipticalTube, G4Box, and G4VCSGfaceted.
Definition at line 670 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 670 of file G4VSolid.cc
References CalculateExtent(), kXAxis, kYAxis, kZAxis, G4VisExtent::SetXmax(), G4VisExtent::SetXmin(), G4VisExtent::SetYmax(), G4VisExtent::SetYmin(), G4VisExtent::SetZmax(), and G4VisExtent::SetZmin().
Referenced by G4tgbVolume::BuildSolidForDivision(), G4BoundingExtentScene::ProcessVolume(), G4BoundingSphereScene::ProcessVolume(), and G4VisCommandsTouchable::SetNewValue().
G4String G4VSolid::GetName () const inline
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), G4XXXFileSceneHandler::AddSolid(), G4XXXStoredSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4XXXSGSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), PHG4GDMLWriteSolids::AddSolid(), G4GDMLWriteSolids::AddSolid(), G4NavigationLogger::AlongComputeStepLog(), PHG4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::BooleanWrite(), G4ScaledSolid::BoundingLimits(), G4ReflectedSolid::BoundingLimits(), G4Box::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4Orb::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4UnionSolid::BoundingLimits(), G4SubtractionSolid::BoundingLimits(), G4GenericPolycone::BoundingLimits(), G4Hype::BoundingLimits(), G4Paraboloid::BoundingLimits(), G4TwistedTubs::BoundingLimits(), G4Polycone::BoundingLimits(), G4Polyhedra::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Trd::BoundingLimits(), G4GenericTrap::BoundingLimits(), G4EllipticalCone::BoundingLimits(), G4Para::BoundingLimits(), G4Tubs::BoundingLimits(), G4Torus::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Cons::BoundingLimits(), G4Sphere::BoundingLimits(), G4TessellatedSolid::BoundingLimits(), G4Trap::BoundingLimits(), PHG4GDMLWriteSolids::BoxWrite(), G4GDMLWriteSolids::BoxWrite(), G4GenericPolycone::CalculateExtent(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4ExtrudedSolid::CalculateExtent(), G4NavigationLogger::CheckDaughterEntryPoint(), G4VDivisionParameterisation::CheckNDivAndWidth(), G4VDivisionParameterisation::CheckOffset(), G4GenericTrap::CheckOrder(), G4EllipticalTube::CheckParameters(), G4Ellipsoid::CheckParameters(), G4Trd::CheckParameters(), G4Para::CheckParameters(), G4Trap::CheckParameters(), G4ParameterisationPolyconeRho::CheckParametersValidity(), G4ParameterisationPolyhedraRho::CheckParametersValidity(), G4ParameterisationPolyhedraPhi::CheckParametersValidity(), G4ParameterisationPolyconeZ::CheckParametersValidity(), G4ParameterisationPolyhedraZ::CheckParametersValidity(), G4PhantomParameterisation::CheckVoxelsFillContainer(), G4GenericTrap::ComputeIsTwisted(), G4VoxelSafety::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4NavigationLogger::ComputeSafetyLog(), G4ParameterisedNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), PHG4GDMLWriteSolids::ConeWrite(), G4GDMLWriteSolids::ConeWrite(), FFDetectorConstruction::Construct(), CCalG4Hall::constructIn(), G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), G4PhysicalVolumeModel::CreateCurrentAttValues(), G4GenericPolycone::CreatePolyhedron(), G4ReflectedSolid::CreatePolyhedron(), G4Polyhedra::CreatePolyhedron(), G4ReflectionFactory::CreateReflectedLV(), G4GenericTrap::CreateTessellatedSolid(), PHG4GDMLWriteSolids::CutTubeWrite(), G4GDMLWriteSolids::CutTubeWrite(), G4PhysicalVolumeModel::DescribeSolid(), G4SubtractionSolid::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4TessellatedSolid::DistanceToIn(), G4EllipticalTube::DistanceToOut(), G4Box::DistanceToOut(), G4Orb::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Trd::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4Para::DistanceToOut(), G4TessellatedSolid::DistanceToOut(), G4Trap::DistanceToOut(), G4tgbGeometryDumper::DumpSolid(), PHG4GDMLWriteSolids::ElconeWrite(), G4GDMLWriteSolids::ElconeWrite(), PHG4GDMLWriteSolids::EllipsoidWrite(), G4GDMLWriteSolids::EllipsoidWrite(), PHG4GDMLWriteSolids::EltubeWrite(), G4GDMLWriteSolids::EltubeWrite(), G4PVDivision::ErrorInAxis(), G4ReplicatedSlice::ErrorInAxis(), export_G4VSolid(), G4Box::G4Box(), G4Cons::G4Cons(), G4CutTubs::G4CutTubs(), G4EllipticalCone::G4EllipticalCone(), G4Hype::G4Hype(), G4Para::G4Para(), G4Paraboloid::G4Paraboloid(), G4Polycone::G4Polycone(), G4Polyhedra::G4Polyhedra(), G4Sphere::G4Sphere(), G4Tet::G4Tet(), G4Trap::G4Trap(), G4Tubs::G4Tubs(), G4VParameterisationCons::G4VParameterisationCons(), G4VParameterisationPara::G4VParameterisationPara(), G4VParameterisationPolycone::G4VParameterisationPolycone(), G4VParameterisationPolyhedra::G4VParameterisationPolyhedra(), G4VParameterisationTrd::G4VParameterisationTrd(), G4VTwistedFaceted::G4VTwistedFaceted(), PHG4GDMLWriteSolids::GenericPolyconeWrite(), G4GDMLWriteSolids::GenericPolyconeWrite(), PHG4GDMLWriteSolids::GenTrapWrite(), G4GDMLWriteSolids::GenTrapWrite(), G4HepRepSceneHandler::getGeometryInstance(), G4Navigator::GetGlobalExitNormal(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4BooleanSolid::GetPointOnSurface(), G4PhantomParameterisation::GetReplicaNo(), PHG4GDMLWriteSolids::HypeWrite(), G4GDMLWriteSolids::HypeWrite(), G4TessellatedSolid::InsideNoVoxels(), G4TessellatedSolid::InsideVoxels(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4GenericTrap::MakeDownFacet(), G4Trap::MakePlanes(), G4GenericTrap::MakeUpFacet(), G4GDMLWriteSolids::MultiUnionWrite(), PHG4GDMLWriteSolids::OrbWrite(), G4GDMLWriteSolids::OrbWrite(), PHG4GDMLWriteSolids::ParaboloidWrite(), G4GDMLWriteSolids::ParaboloidWrite(), G4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteParamvol::ParametersWrite(), PHG4GDMLWriteSolids::ParaWrite(), G4GDMLWriteSolids::ParaWrite(), PHG4GDMLWriteSolids::PolyconeWrite(), G4GDMLWriteSolids::PolyconeWrite(), PHG4GDMLWriteSolids::PolyhedraWrite(), G4GDMLWriteSolids::PolyhedraWrite(), G4NavigationLogger::PostComputeStepLog(), G4NavigationLogger::PreComputeStepLog(), G4NavigationLogger::PrintDaughterLog(), G4tgbVolumeMgr::RegisterMe(), G4NavigationLogger::ReportOutsideMother(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VSceneHandler::RequestPrimitives(), G4GenericPolycone::Reset(), G4Polyhedra::Reset(), G4VoxelSafety::SafetyForVoxelNode(), G4GDMLWriteSolids::ScaledWrite(), G4Torus::SetAllParameters(), G4Polycone::SetOriginalParameters(), G4Polyhedra::SetOriginalParameters(), G4Tet::SetVertices(), G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), G4Box::SetZHalfLength(), PHG4GDMLWriteSolids::SphereWrite(), G4GDMLWriteSolids::SphereWrite(), G4BooleanSolid::StackPolyhedron(), G4CSGSolid::StreamInfo(), G4TwistedBox::StreamInfo(), G4VCSGfaceted::StreamInfo(), G4TwistedTrd::StreamInfo(), G4BooleanSolid::StreamInfo(), G4GenericPolycone::StreamInfo(), G4ScaledSolid::StreamInfo(), G4EllipticalTube::StreamInfo(), G4Box::StreamInfo(), G4TwistedTrap::StreamInfo(), G4VTwistedFaceted::StreamInfo(), G4ReflectedSolid::StreamInfo(), G4Orb::StreamInfo(), G4Ellipsoid::StreamInfo(), G4Paraboloid::StreamInfo(), G4Polycone::StreamInfo(), G4Hype::StreamInfo(), G4Polyhedra::StreamInfo(), G4Tet::StreamInfo(), G4GenericTrap::StreamInfo(), G4TwistedTubs::StreamInfo(), G4MultiUnion::StreamInfo(), G4CutTubs::StreamInfo(), G4ExtrudedSolid::StreamInfo(), G4DisplacedSolid::StreamInfo(), G4Trd::StreamInfo(), G4EllipticalCone::StreamInfo(), G4Tubs::StreamInfo(), G4Torus::StreamInfo(), G4Para::StreamInfo(), G4Cons::StreamInfo(), G4Sphere::StreamInfo(), G4TessellatedSolid::StreamInfo(), G4Trap::StreamInfo(), G4GDMLRead::StripNames(), SubstractSolids(), G4EllipticalTube::SurfaceNormal(), G4UnionSolid::SurfaceNormal(), G4Box::SurfaceNormal(), G4Ellipsoid::SurfaceNormal(), G4Tet::SurfaceNormal(), G4Trd::SurfaceNormal(), G4ExtrudedSolid::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4Para::SurfaceNormal(), G4Trap::SurfaceNormal(), PHG4GDMLWriteSolids::TessellatedWrite(), G4GDMLWriteSolids::TessellatedWrite(), PHG4GDMLWriteSolids::TetWrite(), G4GDMLWriteSolids::TetWrite(), PHG4GDMLWriteSolids::TorusWrite(), G4GDMLWriteSolids::TorusWrite(), PHG4GDMLWriteSolids::TrapWrite(), G4GDMLWriteSolids::TrapWrite(), PHG4GDMLWriteStructure::TraverseVolumeTree(), G4GDMLWriteStructure::TraverseVolumeTree(), PHG4GDMLWriteSolids::TrdWrite(), G4GDMLWriteSolids::TrdWrite(), PHG4GDMLWriteSolids::TubeWrite(), G4GDMLWriteSolids::TubeWrite(), PHG4GDMLWriteSolids::TwistedboxWrite(), G4GDMLWriteSolids::TwistedboxWrite(), PHG4GDMLWriteSolids::TwistedtrapWrite(), G4GDMLWriteSolids::TwistedtrapWrite(), PHG4GDMLWriteSolids::TwistedtrdWrite(), G4GDMLWriteSolids::TwistedtrdWrite(), PHG4GDMLWriteSolids::TwistedtubsWrite(), G4GDMLWriteSolids::TwistedtubsWrite(), G4PhysicalVolumeModel::VisitGeometryAndGetVisReps(), PHG4GDMLWriteSolids::XtruWrite(), and G4GDMLWriteSolids::XtruWrite().
G4ThreeVector G4VSolid::GetPointOnSurface () const virtual
Reimplemented in G4Trap, G4TessellatedSolid, G4TwistedTubs, G4Sphere, G4Cons, G4Para, G4EllipticalCone, G4Torus, G4Tubs, G4Trd, G4MultiUnion, G4CutTubs, G4GenericTrap, G4Hype, G4Tet, G4Ellipsoid, G4Paraboloid, G4Polyhedra, G4Polycone, G4EllipticalTube, G4Orb, G4Box, G4DisplacedSolid, G4VTwistedFaceted, G4BooleanSolid, G4GenericPolycone, G4ScaledSolid, and G4ReflectedSolid.
Definition at line 140 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 140 of file G4VSolid.cc
References G4endl, G4Exception(), GetEntityType(), JustWarning, and message().
Referenced by G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4LogicalVolumeModel::DescribeYourselfTo(), export_G4VSolid(), G4ReflectedSolid::GetPointOnSurface(), G4ScaledSolid::GetPointOnSurface(), G4DisplacedSolid::GetPointOnSurface(), G4MultiUnion::GetPointOnSurface(), and G4VSceneHandler::RequestPrimitives().
G4Polyhedron * G4VSolid::GetPolyhedron () const virtual
Reimplemented in G4TessellatedSolid, G4DisplacedSolid, G4EllipticalCone, G4MultiUnion, G4GenericTrap, G4Tet, G4Hype, G4Ellipsoid, G4Paraboloid, G4TwistedTubs, G4ReflectedSolid, G4ScaledSolid, G4EllipticalTube, G4VTwistedFaceted, G4VCSGfaceted, G4BooleanSolid, and G4CSGSolid.
Definition at line 693 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 693 of file G4VSolid.cc
Referenced by G4PhysicalVolumeModel::DescribeSolid(), PerspectiveVisAction::ExtendedDraw(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VSceneHandler::RequestPrimitives(), G4VisCommandsTouchable::SetNewValue(), and G4BooleanSolid::StackPolyhedron().
G4double G4VSolid::GetSurfaceArea () virtual
Reimplemented in G4Trap, G4TessellatedSolid, G4TwistedTubs, G4GenericTrap, G4Sphere, G4Hype, G4Tet, G4Cons, G4Torus, G4Ellipsoid, G4MultiUnion, G4Para, G4Tubs, G4EllipticalCone, G4EllipticalTube, G4CutTubs, G4Trd, G4VTwistedFaceted, G4VCSGfaceted, G4Box, G4Paraboloid, G4ScaledSolid, G4BooleanSolid, and G4Orb.
Definition at line 238 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 238 of file G4VSolid.cc
References EstimateSurfaceArea().
Referenced by G4AdjointCrossSurfChecker::AddanExtSurfaceOfAvolume(), export_G4VSolid(), G4ScaledSolid::GetSurfaceArea(), G4VTwistedFaceted::GetSurfaceArea(), G4Hype::GetSurfaceArea(), G4GenericTrap::GetSurfaceArea(), and G4TwistedTubs::GetSurfaceArea().
G4double G4VSolid::GetTolerance () const inline
Referenced by G4NavigationLogger::CheckDaughterEntryPoint(), G4ParameterisedNavigation::ComputeStep(), G4NavigationLogger::PreComputeStepLog(), G4NavigationLogger::ReportOutsideMother(), and G4NavigationLogger::ReportVolumeAndIntersection().
virtual EInside G4VSolid::Inside (const G4ThreeVector & p) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Para, G4Tubs, G4Torus, G4EllipticalCone, G4TwistedTubs, G4ExtrudedSolid, G4Trd, G4CutTubs, G4Hype, G4Tet, G4GenericTrap, G4Ellipsoid, G4Paraboloid, G4Polycone, G4Polyhedra, G4VTwistedFaceted, G4Box, G4SubtractionSolid, G4IntersectionSolid, G4UnionSolid, G4Orb, G4GenericPolycone, G4EllipticalTube, G4MultiUnion, G4DisplacedSolid, G4ReflectedSolid, G4VCSGfaceted, and G4ScaledSolid.
Referenced by G4NavigationLogger::AlongComputeStepLog(), G4ReplicaNavigation::BackLocate(), GFlashShowerModel::CheckContainment(), G4NavigationLogger::CheckDaughterEntryPoint(), G4PVParameterised::CheckOverlaps(), G4PVPlacement::CheckOverlaps(), G4VoxelSafety::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4RegularNavigation::ComputeStepSkippingEqualMaterials(), G4TheRayTracer::CreateBitMap(), G4DNAMolecularDissociation::DecayIt(), G4VFieldModel::DescribeYourselfTo(), G4LogicalVolumeModel::DescribeYourselfTo(), G4PolyPhiFace::Diagnose(), G4IntersectionSolid::DistanceToIn(), G4SubtractionSolid::DistanceToIn(), G4MultiUnion::DistanceToOut(), G4UnionSolid::DistanceToOut(), G4MultiUnion::DistanceToOutNoVoxels(), G4MultiUnion::DistanceToOutVoxels(), EstimateCubicVolume(), EstimateSurfaceArea(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4BooleanSolid::GetPointOnSurface(), G4ITNavigator2::GetRandomInCurrentVolume(), G4PhantomParameterisation::GetReplicaNo(), G4ScaledSolid::Inside(), G4ReflectedSolid::Inside(), G4DisplacedSolid::Inside(), G4UnionSolid::Inside(), G4IntersectionSolid::Inside(), G4SubtractionSolid::Inside(), G4VExternalNavigation::Inside(), G4MultiUnion::InsideNoVoxels(), G4MultiUnion::InsideWithExclusion(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4VIntersectionLocator::LocateGlobalPointWithinVolumeAndCheck(), G4NavigationLogger::PreComputeStepLog(), G4Navigator::RecheckDistanceToCurrentBoundary(), G4ITNavigator2::RecheckDistanceToCurrentBoundary(), G4NavigationLogger::ReportOutsideMother(), G4NavigationLogger::ReportVolumeAndIntersection(), DicomIntersectVolume::SetNewValue(), G4RTPrimaryGeneratorAction::SetUp(), G4IntersectionSolid::SurfaceNormal(), G4UnionSolid::SurfaceNormal(), G4SubtractionSolid::SurfaceNormal(), and G4MultiUnion::SurfaceNormal().
G4VSolid & G4VSolid::operator= (const G4VSolid & rhs)
Definition at line 98 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 98 of file G4VSolid.cc
References fshapeName, and kCarTolerance.
Referenced by G4VCSGfaceted::operator=(), G4CSGSolid::operator=(), G4MultiUnion::operator=(), G4BooleanSolid::operator=(), G4ScaledSolid::operator=(), G4ReflectedSolid::operator=(), G4EllipticalTube::operator=(), G4Paraboloid::operator=(), G4Hype::operator=(), G4VTwistedFaceted::operator=(), G4Ellipsoid::operator=(), G4TessellatedSolid::operator=(), G4Tet::operator=(), G4DisplacedSolid::operator=(), G4GenericTrap::operator=(), G4EllipticalCone::operator=(), and G4TwistedTubs::operator=().
G4bool G4VSolid::operator== (const G4VSolid & s) const inline
void G4VSolid::SetName (const G4String & name) inline
Referenced by export_G4VSolid(), G4MultiUnion::G4MultiUnion(), and G4GDMLRead::StripNames().
virtual std::ostream& G4VSolid::StreamInfo (std::ostream & os) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Para, G4Torus, G4Tubs, G4EllipticalCone, G4Trd, G4DisplacedSolid, G4ExtrudedSolid, G4CutTubs, G4MultiUnion, G4TwistedTubs, G4GenericTrap, G4Hype, G4Polyhedra, G4Tet, G4Polycone, G4Ellipsoid, G4Paraboloid, G4Orb, G4ReflectedSolid, G4TwistedTrap, G4VTwistedFaceted, G4Box, G4EllipticalTube, G4ScaledSolid, G4GenericPolycone, G4BooleanSolid, G4TwistedTrd, G4VCSGfaceted, G4TwistedBox, and G4CSGSolid.
Referenced by operator<<(), G4BooleanSolid::StreamInfo(), G4ScaledSolid::StreamInfo(), G4ReflectedSolid::StreamInfo(), G4MultiUnion::StreamInfo(), and G4DisplacedSolid::StreamInfo().
virtual G4ThreeVector G4VSolid::SurfaceNormal (const G4ThreeVector & p) const pure virtual
Implemented in G4Trap, G4TessellatedSolid, G4Sphere, G4Cons, G4Torus, G4Para, G4Tubs, G4EllipticalCone, G4TwistedTubs, G4ExtrudedSolid, G4Trd, G4CutTubs, G4MultiUnion, G4Hype, G4Tet, G4GenericTrap, G4Ellipsoid, G4Paraboloid, G4VTwistedFaceted, G4SubtractionSolid, G4Box, G4IntersectionSolid, G4UnionSolid, G4Orb, G4EllipticalTube, G4DisplacedSolid, G4ReflectedSolid, G4ScaledSolid, and G4VCSGfaceted.
Referenced by G4Navigator::ComputeStep(), G4ReplicaNavigation::ComputeStep(), G4ITNavigator1::ComputeStep(), G4ITNavigator2::ComputeStep(), G4SubtractionSolid::DistanceToOut(), EstimateSurfaceArea(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4UnionSolid::Inside(), G4SubtractionSolid::Inside(), G4MultiUnion::InsideWithExclusion(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4NavigationLogger::ReportVolumeAndIntersection(), G4ScaledSolid::SurfaceNormal(), G4ReflectedSolid::SurfaceNormal(), G4DisplacedSolid::SurfaceNormal(), G4IntersectionSolid::SurfaceNormal(), G4UnionSolid::SurfaceNormal(), G4SubtractionSolid::SurfaceNormal(), and G4MultiUnion::SurfaceNormal().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4VSolid & e) friend
Definition at line 116 of file G4VSolid.cc.
View newest version in sPHENIX GitHub at line 116 of file G4VSolid.cc
Member Data Documentation
G4String G4VSolid::fshapeName private
Definition at line 315 of file G4VSolid.hh.
View newest version in sPHENIX GitHub at line 315 of file G4VSolid.hh
Referenced by operator=().
G4double G4VSolid::kCarTolerance protected
Definition at line 302 of file G4VSolid.hh.
View newest version in sPHENIX GitHub at line 302 of file G4VSolid.hh
Referenced by G4TessellatedSolid::AddFacet(), G4Polycone::CalculateExtent(), G4Polyhedra::CalculateExtent(), G4Tet::CheckDegeneracy(), G4EllipticalTube::CheckParameters(), G4Ellipsoid::CheckParameters(), G4Trd::CheckParameters(), G4Para::CheckParameters(), G4GenericTrap::ComputeIsTwisted(), G4GenericPolycone::Create(), G4Polycone::Create(), G4Polyhedra::Create(), G4GenericPolycone::CreatePolyhedron(), G4Polyhedra::CreatePolyhedron(), G4CutTubs::CreatePolyhedron(), G4TessellatedSolid::CreateVertexList(), G4VCSGfaceted::DistanceTo(), G4VCSGfaceted::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4Hype::DistanceToIn(), G4Sphere::DistanceToIn(), G4TessellatedSolid::DistanceToInCore(), G4VCSGfaceted::DistanceToOut(), G4UnionSolid::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4GenericTrap::DistanceToOut(), G4Hype::DistanceToOut(), G4CutTubs::DistanceToOut(), G4Tubs::DistanceToOut(), G4Torus::DistanceToOut(), G4Cons::DistanceToOut(), G4Sphere::DistanceToOut(), G4TessellatedSolid::DistanceToOutCandidates(), G4TessellatedSolid::DistanceToOutCore(), G4TessellatedSolid::DistanceToOutNoVoxels(), G4GenericTrap::DistToPlane(), G4GenericTrap::DistToTriangle(), G4Box::G4Box(), G4Cons::G4Cons(), G4CutTubs::G4CutTubs(), G4EllipticalCone::G4EllipticalCone(), G4ExtrudedSolid::G4ExtrudedSolid(), G4GenericTrap::G4GenericTrap(), G4Hype::G4Hype(), G4Para::G4Para(), G4Sphere::G4Sphere(), G4Tet::G4Tet(), G4Trap::G4Trap(), G4Tubs::G4Tubs(), G4UnionSolid::G4UnionSolid(), G4VSolid(), G4VTwistedFaceted::G4VTwistedFaceted(), G4Orb::Initialize(), G4TessellatedSolid::Initialize(), G4VCSGfaceted::Inside(), G4SubtractionSolid::Inside(), G4VTwistedFaceted::Inside(), G4Paraboloid::Inside(), G4Hype::Inside(), G4TessellatedSolid::InsideNoVoxels(), G4GenericTrap::InsidePolygone(), G4TessellatedSolid::InsideVoxels(), G4GenericTrap::IsSegCrossingZ(), G4Trap::MakePlane(), G4GenericTrap::NormalToPlane(), operator=(), G4TessellatedSolid::SafetyFromInside(), G4TessellatedSolid::SafetyFromOutside(), G4Torus::SetAllParameters(), G4Polycone::SetOriginalParameters(), G4Polyhedra::SetOriginalParameters(), G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), G4Box::SetZHalfLength(), G4Paraboloid::SurfaceNormal(), G4GenericTrap::SurfaceNormal(), and G4Torus::SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VSolid.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4VSolid.cc