ECCE @ EIC Software: G4ionEffectiveCharge Class Reference
G4ionEffectiveCharge Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4ionEffectiveCharge.hh>
Public Member Functions
G4ionEffectiveCharge ()
virtual ~G4ionEffectiveCharge ()
G4double EffectiveChargeSquareRatio (const G4ParticleDefinition *p, const G4Material *material, G4double kineticEnergy)
G4double EffectiveCharge (const G4ParticleDefinition *p, const G4Material *material, G4double kineticEnergy)
Private Member Functions
G4ionEffectiveCharge & operator= (const G4ionEffectiveCharge &right)=delete
G4ionEffectiveCharge (const G4ionEffectiveCharge &)=delete
Private Attributes
G4double inveplus
G4Pow * g4calc
const G4ParticleDefinition * lastPart
const G4Material * lastMat
G4double lastKinEnergy
G4double chargeCorrection
G4double effCharge
G4double energyHighLimit
G4double energyLowLimit
G4double energyBohr
G4double massFactor
G4double minCharge
Detailed Description
Definition at line 61 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ionEffectiveCharge.hh
Constructor & Destructor Documentation
G4ionEffectiveCharge::G4ionEffectiveCharge () explicit
Definition at line 64 of file G4ionEffectiveCharge.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ionEffectiveCharge.cc
References source.hepunit::amu_c2, chargeCorrection, effCharge, energyBohr, energyHighLimit, energyLowLimit, CLHEP::eplus, eplus, g4calc, G4Pow::GetInstance(), inveplus, keV, lastKinEnergy, lastMat, lastPart, massFactor, MeV, minCharge, and source.hepunit::proton_mass_c2.
G4ionEffectiveCharge::~G4ionEffectiveCharge () virtual
Definition at line 82 of file G4ionEffectiveCharge.cc.
View newest version in sPHENIX GitHub at line 82 of file G4ionEffectiveCharge.cc
G4ionEffectiveCharge::G4ionEffectiveCharge (const G4ionEffectiveCharge &) private delete
Member Function Documentation
G4double G4ionEffectiveCharge::EffectiveCharge (const G4ParticleDefinition * p, const G4Material * material, G4double kineticEnergy)
Definition at line 87 of file G4ionEffectiveCharge.cc.
View newest version in sPHENIX GitHub at line 87 of file G4ionEffectiveCharge.cc
References G4Pow::A13(), G4Pow::A23(), c, charge, chargeCorrection, effCharge, energyBohr, energyHighLimit, energyLowLimit, g4calc, G4Exp(), G4Log(), G4IonisParamMat::GetFermiEnergy(), G4Material::GetIonisation(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4IonisParamMat::GetZeffective(), inveplus, keV, G4InuclParticleNames::lambda, lastKinEnergy, lastMat, lastPart, mass, massFactor, material(), max, minCharge, source.hepunit::proton_mass_c2, Q, x, xx, y, y3, and z.
Referenced by G4MicroElecInelasticModel::CrossSectionPerVolume(), G4MuElecInelasticModel::CrossSectionPerVolume(), EffectiveChargeSquareRatio(), G4EmCorrections::GetParticleCharge(), and G4EmCorrections::SetupKinematics().
G4double G4ionEffectiveCharge::EffectiveChargeSquareRatio (const G4ParticleDefinition * p, const G4Material * material, G4double kineticEnergy) inline
Definition at line 105 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ionEffectiveCharge.hh
References charge, chargeCorrection, effCharge, EffectiveCharge(), inveplus, lastKinEnergy, lastMat, and lastPart.
Referenced by G4EmCorrections::BuildCorrectionVector(), and G4EmCorrections::EffectiveChargeSquareRatio().
G4ionEffectiveCharge& G4ionEffectiveCharge::operator= (const G4ionEffectiveCharge & right) private delete
Member Data Documentation
G4double G4ionEffectiveCharge::chargeCorrection private
Definition at line 92 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), EffectiveChargeSquareRatio(), and G4ionEffectiveCharge().
G4double G4ionEffectiveCharge::effCharge private
Definition at line 93 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), EffectiveChargeSquareRatio(), and G4ionEffectiveCharge().
G4double G4ionEffectiveCharge::energyBohr private
Definition at line 97 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), and G4ionEffectiveCharge().
G4double G4ionEffectiveCharge::energyHighLimit private
Definition at line 95 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 95 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), and G4ionEffectiveCharge().
G4double G4ionEffectiveCharge::energyLowLimit private
Definition at line 96 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 96 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), and G4ionEffectiveCharge().
G4Pow* G4ionEffectiveCharge::g4calc private
Definition at line 86 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), and G4ionEffectiveCharge().
G4double G4ionEffectiveCharge::inveplus private
Definition at line 85 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), EffectiveChargeSquareRatio(), and G4ionEffectiveCharge().
G4double G4ionEffectiveCharge::lastKinEnergy private
Definition at line 90 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), EffectiveChargeSquareRatio(), and G4ionEffectiveCharge().
const G4Material* G4ionEffectiveCharge::lastMat private
Definition at line 89 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), EffectiveChargeSquareRatio(), and G4ionEffectiveCharge().
const G4ParticleDefinition* G4ionEffectiveCharge::lastPart private
Definition at line 88 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), EffectiveChargeSquareRatio(), and G4ionEffectiveCharge().
G4double G4ionEffectiveCharge::massFactor private
Definition at line 98 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), and G4ionEffectiveCharge().
G4double G4ionEffectiveCharge::minCharge private
Definition at line 99 of file G4ionEffectiveCharge.hh.
View newest version in sPHENIX GitHub at line 99 of file G4ionEffectiveCharge.hh
Referenced by EffectiveCharge(), and G4ionEffectiveCharge().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4ionEffectiveCharge.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4ionEffectiveCharge.cc