ECCE @ EIC Software: G4LevelManager Class Reference
G4LevelManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4LevelManager.hh>
Public Member Functions
G4LevelManager (G4int Z, G4int A, size_t nlev, const std::vector< G4double > &energies, const std::vector< G4int > &spin, const std::vector< const G4NucLevel * > &levels)
~G4LevelManager ()
size_t NumberOfTransitions () const
const G4NucLevel * GetLevel (size_t i) const
G4double LevelEnergy (size_t i) const
G4double MaxLevelEnergy () const
size_t NearestLevelIndex (G4double energy, size_t index=0) const
size_t NearestLowEdgeLevelIndex (G4double energy) const
const G4NucLevel * NearestLevel (G4double energy, size_t index=0) const
G4double NearestLevelEnergy (G4double energy, size_t index=0) const
G4double NearestLowEdgeLevelEnergy (G4double energy) const
G4double LifeTime (size_t i) const
G4int SpinTwo (size_t i) const
G4int Parity (size_t i) const
G4int FloatingLevel (size_t i) const
G4double ShellCorrection () const
G4double LevelDensity (G4double U) const
const G4String & FloatingType (size_t i) const
void StreamInfo (std::ostream &os) const
Private Member Functions
G4LevelManager (const G4LevelManager &right)=delete
const G4LevelManager & operator= (const G4LevelManager &right)=delete
G4bool operator== (const G4LevelManager &right) const =delete
G4bool operator!= (const G4LevelManager &right) const =delete
Private Attributes
std::vector< G4double > fLevelEnergy
std::vector< G4int > fSpin
std::vector< const G4NucLevel * > fLevels
G4double fShellCorrection
G4double fLevelDensity
size_t nTransitions
Static Private Attributes
static const G4int nfloting = 13
static G4String fFloatingLevels [nfloting]
Detailed Description
Definition at line 53 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 53 of file G4LevelManager.hh
Constructor & Destructor Documentation
G4LevelManager::G4LevelManager (G4int Z, G4int A, size_t nlev, const std::vector< G4double > & energies, const std::vector< G4int > & spin, const std::vector< const G4NucLevel * > & levels) explicit
Definition at line 52 of file G4LevelManager.cc.
View newest version in sPHENIX GitHub at line 52 of file G4LevelManager.cc
References fLevelDensity, fLevelEnergy, fLevels, fShellCorrection, fSpin, G4Pow::GetInstance(), G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetShellCorrection(), N, nTransitions, Z, and G4Pow::Z13().
G4LevelManager::~G4LevelManager ()
Definition at line 89 of file G4LevelManager.cc.
View newest version in sPHENIX GitHub at line 89 of file G4LevelManager.cc
References fLevels, and nTransitions.
G4LevelManager::G4LevelManager (const G4LevelManager & right) private delete
Member Function Documentation
G4int G4LevelManager::FloatingLevel (size_t i) const inline
Definition at line 210 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 210 of file G4LevelManager.hh
References fSpin, and nTransitions.
Referenced by G4PhotonEvaporation::GenerateGamma(), and StreamInfo().
const G4String & G4LevelManager::FloatingType (size_t i) const
Definition at line 122 of file G4LevelManager.cc.
View newest version in sPHENIX GitHub at line 122 of file G4LevelManager.cc
References fFloatingLevels, fSpin, and nTransitions.
const G4NucLevel * G4LevelManager::GetLevel (size_t i) const inline
Definition at line 138 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 138 of file G4LevelManager.hh
References fLevels, and nTransitions.
Referenced by G4PhotonEvaporation::GenerateGamma(), and NearestLevel().
G4double G4LevelManager::LevelDensity (G4double U) const inline
Definition at line 223 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 223 of file G4LevelManager.hh
References fLevelDensity.
Referenced by G4NuclearLevelData::GetLevelDensity().
G4double G4LevelManager::LevelEnergy (size_t i) const inline
Definition at line 146 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 146 of file G4LevelManager.hh
References fLevelEnergy, and nTransitions.
Referenced by G4NuclearLevelData::FindLevel(), G4PhotonEvaporation::GenerateGamma(), G4FermiFragmentsPoolVI::Initialise(), NearestLevelEnergy(), and NearestLowEdgeLevelEnergy().
G4double G4LevelManager::LifeTime (size_t i) const inline
Definition at line 186 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 186 of file G4LevelManager.hh
References fLevels, and nTransitions.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4PhotonEvaporation::GenerateGamma(), and G4FermiFragmentsPoolVI::Initialise().
G4double G4LevelManager::MaxLevelEnergy () const inline
Definition at line 154 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 154 of file G4LevelManager.hh
References fLevelEnergy, and nTransitions.
Referenced by G4GEMProbabilityVI::G4GEMProbabilityVI(), and G4PhotonEvaporation::InitialiseLevelManager().
const G4NucLevel * G4LevelManager::NearestLevel (G4double energy, size_t index = 0) const inline
Definition at line 170 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 170 of file G4LevelManager.hh
References GetLevel(), and NearestLevelIndex().
G4double G4LevelManager::NearestLevelEnergy (G4double energy, size_t index = 0) const inline
Definition at line 176 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 176 of file G4LevelManager.hh
References LevelEnergy(), and NearestLevelIndex().
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4PhotonEvaporation::GetFinalLevelEnergy(), and G4NuclearLevelData::GetLevelEnergy().
size_t G4LevelManager::NearestLevelIndex (G4double energy, size_t index = 0) const
Definition at line 95 of file G4LevelManager.cc.
View newest version in sPHENIX GitHub at line 95 of file G4LevelManager.cc
References kdfinder::abs(), energy, fLevelEnergy, incremental_prev_tag::idx, min, and nTransitions.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4NuclearLevelData::FindLevel(), G4PhotonEvaporation::GenerateGamma(), NearestLevel(), and NearestLevelEnergy().
G4double G4LevelManager::NearestLowEdgeLevelEnergy (G4double energy) const inline
Definition at line 181 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 181 of file G4LevelManager.hh
References LevelEnergy(), and NearestLowEdgeLevelIndex().
Referenced by G4NuclearLevelData::GetLowEdgeLevelEnergy().
size_t G4LevelManager::NearestLowEdgeLevelIndex (G4double energy) const inline
Definition at line 159 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 159 of file G4LevelManager.hh
References energy, fLevelEnergy, incremental_prev_tag::idx, and nTransitions.
Referenced by NearestLowEdgeLevelEnergy().
size_t G4LevelManager::NumberOfTransitions () const inline
Definition at line 133 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 133 of file G4LevelManager.hh
References nTransitions.
Referenced by G4Radioactivation::CalculateChainsFromParent(), G4RadioactiveDecay::CalculateChainsFromParent(), G4NuclearLevelData::FindLevel(), G4PhotonEvaporation::GenerateGamma(), G4NuclearLevelData::GetLevelEnergy(), G4FermiFragmentsPoolVI::Initialise(), and G4NuclearLevelData::StreamLevels().
G4bool G4LevelManager::operator!= (const G4LevelManager & right) const private delete
const G4LevelManager& G4LevelManager::operator= (const G4LevelManager & right) private delete
G4bool G4LevelManager::operator== (const G4LevelManager & right) const private delete
G4int G4LevelManager::Parity (size_t i) const inline
Definition at line 202 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 202 of file G4LevelManager.hh
References fSpin, and nTransitions.
Referenced by StreamInfo().
G4double G4LevelManager::ShellCorrection () const inline
Definition at line 218 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 218 of file G4LevelManager.hh
References fShellCorrection.
G4int G4LevelManager::SpinTwo (size_t i) const inline
Definition at line 194 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 194 of file G4LevelManager.hh
References kdfinder::abs(), fSpin, and nTransitions.
Referenced by G4PhotonEvaporation::GenerateGamma(), G4FermiFragmentsPoolVI::Initialise(), and StreamInfo().
void G4LevelManager::StreamInfo (std::ostream & os) const
Definition at line 141 of file G4LevelManager.cc.
View newest version in sPHENIX GitHub at line 141 of file G4LevelManager.cc
References fLevelEnergy, fLevels, FloatingLevel(), nTransitions, Parity(), CLHEP::prec, and SpinTwo().
Referenced by G4NuclearLevelData::StreamLevels().
Member Data Documentation
G4String G4LevelManager::fFloatingLevels static private
Initial value:
= {
  "-", "+X", "+Y", "+Z", "+U", "+V", "+W", "+R", "+S", "+T", "+A", "+B", "+C"}
Definition at line 129 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 129 of file G4LevelManager.hh
Referenced by FloatingType().
G4double G4LevelManager::fLevelDensity private
Definition at line 124 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 124 of file G4LevelManager.hh
Referenced by G4LevelManager(), and LevelDensity().
std::vector<G4double> G4LevelManager::fLevelEnergy private
Definition at line 119 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4LevelManager.hh
Referenced by G4LevelManager(), LevelEnergy(), MaxLevelEnergy(), NearestLevelIndex(), NearestLowEdgeLevelIndex(), and StreamInfo().
std::vector<const G4NucLevel*> G4LevelManager::fLevels private
Definition at line 121 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 121 of file G4LevelManager.hh
Referenced by G4LevelManager(), GetLevel(), LifeTime(), StreamInfo(), and ~G4LevelManager().
G4double G4LevelManager::fShellCorrection private
Definition at line 123 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 123 of file G4LevelManager.hh
Referenced by G4LevelManager(), and ShellCorrection().
std::vector<G4int> G4LevelManager::fSpin private
Definition at line 120 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4LevelManager.hh
Referenced by FloatingLevel(), FloatingType(), G4LevelManager(), Parity(), and SpinTwo().
const G4int G4LevelManager::nfloting = 13 static private
Definition at line 128 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 128 of file G4LevelManager.hh
size_t G4LevelManager::nTransitions private
Definition at line 126 of file G4LevelManager.hh.
View newest version in sPHENIX GitHub at line 126 of file G4LevelManager.hh
Referenced by FloatingLevel(), FloatingType(), G4LevelManager(), GetLevel(), LevelEnergy(), LifeTime(), MaxLevelEnergy(), NearestLevelIndex(), NearestLowEdgeLevelIndex(), NumberOfTransitions(), Parity(), SpinTwo(), StreamInfo(), and ~G4LevelManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/include/G4LevelManager.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/management/src/G4LevelManager.cc