ECCE @ EIC Software: G4DNASecondOrderReaction Class Reference
G4DNASecondOrderReaction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNASecondOrderReaction.hh>
Classes
struct SecondOrderReactionState
Public Member Functions
G4DNASecondOrderReaction (const G4String &aName="DNASecondOrderReaction", G4ProcessType type=fDecay)
virtual ~G4DNASecondOrderReaction ()
G4DNASecondOrderReaction (const G4DNASecondOrderReaction &)
G4DNASecondOrderReaction & operator= (const G4DNASecondOrderReaction &)
void StartTracking (G4Track *)
void SetReaction (const G4MolecularConfiguration *, const G4Material *, double)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VITProcess
G4VITProcess (const G4String &name, G4ProcessType type=fNotDefined)
virtual ~G4VITProcess ()
G4VITProcess (const G4VITProcess &other)
G4VITProcess & operator= (const G4VITProcess &other)
G4bool operator== (const G4VITProcess &right) const
G4bool operator!= (const G4VITProcess &right) const
size_t GetProcessID () const
G4shared_ptr< G4ProcessState_Lock > GetProcessState ()
void SetProcessState (G4shared_ptr< G4ProcessState_Lock > aProcInfo)
void ResetProcessState ()
G4double GetInteractionTimeLeft ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4bool ProposesTimeStep () const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Attributes
G4bool fIsInitialized
G4double fReturnedValue
const std::vector< double > * fpMoleculeDensity
G4double fReactionRate
G4double fConcentration
G4double fMolarMassOfMaterial
G4ParticleChange fParticleChange
const G4MolecularConfiguration * fpMolecularConfiguration
const G4Material * fpMaterial
Protected Attributes inherited from G4VITProcess
G4shared_ptr< G4ProcessState > fpState
G4bool fProposesTimeStep
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Private Member Functions
void Create ()
Additional Inherited Members
Static Public Member Functions inherited from G4VITProcess
static const size_t & GetMaxProcessIndex ()
Protected Member Functions inherited from G4VITProcess
void RetrieveProcessInfo ()
void CreateInfo ()
template<typename T >
T * GetState ()
virtual void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
virtual void ClearInteractionTimeLeft ()
virtual void ClearNumberOfInteractionLengthLeft ()
void SetInstantiateProcessState (G4bool flag)
G4bool InstantiateProcessState ()
Detailed Description
Definition at line 54 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 54 of file G4DNASecondOrderReaction.hh
Constructor & Destructor Documentation
G4DNASecondOrderReaction::G4DNASecondOrderReaction (const G4String & aName = "DNASecondOrderReaction", G4ProcessType type = fDecay)
Definition at line 67 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 67 of file G4DNASecondOrderReaction.cc
References Create().
G4DNASecondOrderReaction::~G4DNASecondOrderReaction () virtual
Definition at line 79 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 79 of file G4DNASecondOrderReaction.cc
G4DNASecondOrderReaction::G4DNASecondOrderReaction (const G4DNASecondOrderReaction & rhs)
Definition at line 73 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 73 of file G4DNASecondOrderReaction.cc
References Create().
Member Function Documentation
virtual G4VParticleChange* G4DNASecondOrderReaction::AlongStepDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 102 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 102 of file G4DNASecondOrderReaction.hh
virtual G4double G4DNASecondOrderReaction::AlongStepGetPhysicalInteractionLength (const G4Track & , G4double , G4double , G4double & , G4GPILSelection *) inline virtual
Implements G4VProcess.
Definition at line 93 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 93 of file G4DNASecondOrderReaction.hh
virtual G4VParticleChange* G4DNASecondOrderReaction::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 87 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 87 of file G4DNASecondOrderReaction.hh
virtual G4double G4DNASecondOrderReaction::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VProcess.
Definition at line 82 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DNASecondOrderReaction.hh
void G4DNASecondOrderReaction::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VITProcess.
Definition at line 97 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 97 of file G4DNASecondOrderReaction.cc
References CLHEP::Avogadro, e3, fIsInitialized, fMolarMassOfMaterial, fpMaterial, fpMoleculeDensity, G4Material::GetMassOfMolecule(), G4DNAMolecularMaterial::GetNumMolPerVolTableFor(), and G4DNAMolecularMaterial::Instance().
void G4DNASecondOrderReaction::Create () private
Definition at line 42 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 42 of file G4DNASecondOrderReaction.cc
References DBL_MAX, G4VProcess::enableAlongStepDoIt, G4VProcess::enableAtRestDoIt, G4VProcess::enablePostStepDoIt, fConcentration, fIsInitialized, fMolarMassOfMaterial, fParticleChange, fpMaterial, fpMolecularConfiguration, fpMoleculeDensity, G4VITProcess::fProposesTimeStep, fReactionRate, fReturnedValue, G4VProcess::pParticleChange, G4VITProcess::SetInstantiateProcessState(), G4VProcess::SetProcessSubType(), and G4VProcess::verboseLevel.
Referenced by G4DNASecondOrderReaction().
G4DNASecondOrderReaction & G4DNASecondOrderReaction::operator= (const G4DNASecondOrderReaction & rhs)
Definition at line 83 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 83 of file G4DNASecondOrderReaction.cc
G4VParticleChange * G4DNASecondOrderReaction::PostStepDoIt (const G4Track & track, const G4Step &) virtual
Implements G4VProcess.
Definition at line 244 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 244 of file G4DNASecondOrderReaction.cc
References G4DNADamage::AddIndirectDamage(), DBL_MAX, fParticleChange, fpMaterial, fReturnedValue, fStopAndKill, G4BestUnit, G4cout, G4endl, G4Track::GetGlobalTime(), GetMolecule(), G4Molecule::GetName(), G4Material::GetName(), G4Track::GetPosition(), G4ParticleChange::Initialize(), G4VScheduler::Instance(), G4DNADamage::Instance(), molecule(), G4VParticleChange::ProposeTrackStatus(), State, and G4VProcess::verboseLevel.
G4double G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 129 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 129 of file G4DNASecondOrderReaction.cc
References CLHEP::Avogadro, cm, DBL_MAX, G4DynamicParticle::DumpInfo(), fConcentration, fpMolecularConfiguration, G4VITProcess::fpState, fReactionRate, fReturnedValue, G4cout, G4endl, G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Material::GetIndex(), G4Track::GetMaterial(), G4Molecule::GetMolecularConfiguration(), GetMolecule(), G4Material::GetName(), G4VProcess::GetProcessName(), material(), NotForced, G4VITProcess::ResetNumberOfInteractionLengthLeft(), State, G4VITProcess::SubtractNumberOfInteractionLengthLeft(), and G4VProcess::verboseLevel.
void G4DNASecondOrderReaction::SetReaction (const G4MolecularConfiguration * molConf, const G4Material * mat, double reactionRate)
Definition at line 113 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 113 of file G4DNASecondOrderReaction.cc
References FatalErrorInArgument, fIsInitialized, fpMaterial, fpMolecularConfiguration, fReactionRate, G4Exception(), and mat.
void G4DNASecondOrderReaction::StartTracking (G4Track * track) virtual
Reimplemented from G4VITProcess.
Definition at line 105 of file G4DNASecondOrderReaction.cc.
View newest version in sPHENIX GitHub at line 105 of file G4DNASecondOrderReaction.cc
References G4VITProcess::fpState, G4VITProcess::StartTracking(), and G4VProcess::StartTracking().
Member Data Documentation
G4double G4DNASecondOrderReaction::fConcentration protected
Definition at line 126 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 126 of file G4DNASecondOrderReaction.hh
Referenced by Create(), and PostStepGetPhysicalInteractionLength().
G4bool G4DNASecondOrderReaction::fIsInitialized protected
Definition at line 120 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 120 of file G4DNASecondOrderReaction.hh
Referenced by BuildPhysicsTable(), Create(), and SetReaction().
G4double G4DNASecondOrderReaction::fMolarMassOfMaterial protected
Definition at line 127 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 127 of file G4DNASecondOrderReaction.hh
Referenced by BuildPhysicsTable(), and Create().
G4ParticleChange G4DNASecondOrderReaction::fParticleChange protected
Definition at line 128 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 128 of file G4DNASecondOrderReaction.hh
Referenced by Create(), and PostStepDoIt().
const G4Material* G4DNASecondOrderReaction::fpMaterial protected
Definition at line 131 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 131 of file G4DNASecondOrderReaction.hh
Referenced by BuildPhysicsTable(), Create(), PostStepDoIt(), and SetReaction().
const G4MolecularConfiguration* G4DNASecondOrderReaction::fpMolecularConfiguration protected
Definition at line 130 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 130 of file G4DNASecondOrderReaction.hh
Referenced by Create(), PostStepGetPhysicalInteractionLength(), and SetReaction().
const std::vector<double>* G4DNASecondOrderReaction::fpMoleculeDensity protected
Definition at line 124 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 124 of file G4DNASecondOrderReaction.hh
Referenced by BuildPhysicsTable(), and Create().
G4double G4DNASecondOrderReaction::fReactionRate protected
Definition at line 125 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 125 of file G4DNASecondOrderReaction.hh
Referenced by Create(), PostStepGetPhysicalInteractionLength(), and SetReaction().
G4double G4DNASecondOrderReaction::fReturnedValue protected
Definition at line 122 of file G4DNASecondOrderReaction.hh.
View newest version in sPHENIX GitHub at line 122 of file G4DNASecondOrderReaction.hh
Referenced by Create(), PostStepDoIt(), and PostStepGetPhysicalInteractionLength().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNASecondOrderReaction.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/src/G4DNASecondOrderReaction.cc