ECCE @ EIC Software: G4ParticleHPChannelList Class Reference
G4ParticleHPChannelList Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPChannelList.hh>
Public Member Functions
G4ParticleHPChannelList (G4int n, G4ParticleDefinition *projectile)
G4ParticleHPChannelList ()
void Init (G4int n)
~G4ParticleHPChannelList ()
G4HadFinalState * ApplyYourself (const G4Element *theElement, const G4HadProjectile &aTrack)
void Init (G4Element *anElement, const G4String &dirName, G4ParticleDefinition *projectile)
void Register (G4ParticleHPFinalState *theFS, const G4String &aName)
G4double GetXsec (G4double anEnergy)
G4int GetNumberOfChannels ()
G4bool HasDataInAnyFinalState ()
void RestartRegistration ()
void DumpInfo ()
Private Attributes
G4ParticleHPChannel ** theChannels
G4int nChannels
G4String theDir
G4Element * theElement
G4bool allChannelsCreated
G4int theInitCount
G4StableIsotopes theStableOnes
G4ParticleDefinition * theProjectile
G4HadFinalState unChanged
Static Private Attributes
static G4ThreadLocal G4int trycounter = 0
Detailed Description
Definition at line 47 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPChannelList.hh
Constructor & Destructor Documentation
G4ParticleHPChannelList::G4ParticleHPChannelList (G4int n, G4ParticleDefinition * projectile)
Definition at line 42 of file G4ParticleHPChannelList.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPChannelList.cc
References allChannelsCreated, n, nChannels, theChannels, theElement, and theInitCount.
G4ParticleHPChannelList::G4ParticleHPChannelList ()
Definition at line 53 of file G4ParticleHPChannelList.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPChannelList.cc
References allChannelsCreated, nChannels, G4Neutron::Neutron(), theChannels, theElement, theInitCount, and theProjectile.
G4ParticleHPChannelList::~G4ParticleHPChannelList ()
Definition at line 63 of file G4ParticleHPChannelList.cc.
View newest version in sPHENIX GitHub at line 63 of file G4ParticleHPChannelList.cc
References nChannels, and theChannels.
Member Function Documentation
G4HadFinalState * G4ParticleHPChannelList::ApplyYourself (const G4Element * theElement, const G4HadProjectile & aTrack)
Definition at line 77 of file G4ParticleHPChannelList.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPChannelList.cc
References G4HadFinalState::AddSecondary(), G4ParticleHPChannel::ApplyYourself(), G4HadFinalState::Clear(), G4cout, G4endl, G4UniformRand, G4HadProjectile::Get4Momentum(), G4ParticleHPChannel::GetFSCrossSection(), G4ParticleHPManager::GetInstance(), G4IonTable::GetIon(), G4IonTable::GetIonTable(), G4HadProjectile::GetKineticEnergy(), G4HadProjectile::GetMaterial(), G4ParticleHPChannel::GetN(), G4ParticleHPChannel::GetNiso(), G4ParticleHPManager::GetReactionWhiteBoard(), G4Material::GetTemperature(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4ParticleHPChannel::GetWeightedXsec(), G4ParticleHPChannel::GetZ(), nChannels, G4HadFinalState::SetEnergyChange(), G4HadFinalState::SetMomentumChange(), G4ParticleHPReactionWhiteBoard::SetTargA(), G4ParticleHPReactionWhiteBoard::SetTargZ(), theChannels, unChanged, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
void G4ParticleHPChannelList::DumpInfo ()
Definition at line 223 of file G4ParticleHPChannelList.cc.
View newest version in sPHENIX GitHub at line 223 of file G4ParticleHPChannelList.cc
References G4ParticleHPChannel::DumpInfo(), G4cout, G4endl, G4Element::GetName(), G4ParticleDefinition::GetParticleName(), HasDataInAnyFinalState(), nChannels, theChannels, theDir, theElement, and theProjectile.
G4int G4ParticleHPChannelList::GetNumberOfChannels () inline
Definition at line 77 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPChannelList.hh
References nChannels.
G4double G4ParticleHPChannelList::GetXsec (G4double anEnergy) inline
Definition at line 66 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPChannelList.hh
References max, nChannels, and theChannels.
G4bool G4ParticleHPChannelList::HasDataInAnyFinalState () inline
Definition at line 79 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPChannelList.hh
References nChannels, and theChannels.
Referenced by DumpInfo().
void G4ParticleHPChannelList::Init (G4int n)
void G4ParticleHPChannelList::Init (G4Element * anElement, const G4String & dirName, G4ParticleDefinition * projectile)
Definition at line 179 of file G4ParticleHPChannelList.cc.
View newest version in sPHENIX GitHub at line 179 of file G4ParticleHPChannelList.cc
References theDir, theElement, and theProjectile.
void G4ParticleHPChannelList::Register (G4ParticleHPFinalState * theFS, const G4String & aName)
Definition at line 188 of file G4ParticleHPChannelList.cc.
View newest version in sPHENIX GitHub at line 188 of file G4ParticleHPChannelList.cc
References allChannelsCreated, G4ParticleHPChannel::Init(), nChannels, G4ParticleHPChannel::Register(), theChannels, theDir, theElement, theInitCount, and theProjectile.
void G4ParticleHPChannelList::RestartRegistration () inline
Definition at line 89 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPChannelList.hh
References allChannelsCreated, and theInitCount.
Member Data Documentation
G4bool G4ParticleHPChannelList::allChannelsCreated private
Definition at line 106 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParticleHPChannelList.hh
Referenced by G4ParticleHPChannelList(), Register(), and RestartRegistration().
G4int G4ParticleHPChannelList::nChannels private
Definition at line 102 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ParticleHPChannelList.hh
Referenced by ApplyYourself(), DumpInfo(), G4ParticleHPChannelList(), GetNumberOfChannels(), GetXsec(), HasDataInAnyFinalState(), Register(), and ~G4ParticleHPChannelList().
G4ParticleHPChannel** G4ParticleHPChannelList::theChannels private
Definition at line 101 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPChannelList.hh
Referenced by ApplyYourself(), DumpInfo(), G4ParticleHPChannelList(), GetXsec(), HasDataInAnyFinalState(), Register(), and ~G4ParticleHPChannelList().
G4String G4ParticleHPChannelList::theDir private
Definition at line 103 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleHPChannelList.hh
Referenced by DumpInfo(), Init(), and Register().
G4Element* G4ParticleHPChannelList::theElement private
Definition at line 104 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParticleHPChannelList.hh
Referenced by DumpInfo(), G4ParticleHPChannelList(), Init(), and Register().
G4int G4ParticleHPChannelList::theInitCount private
Definition at line 107 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPChannelList.hh
Referenced by G4ParticleHPChannelList(), Register(), and RestartRegistration().
G4ParticleDefinition* G4ParticleHPChannelList::theProjectile private
Definition at line 111 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPChannelList.hh
Referenced by DumpInfo(), G4ParticleHPChannelList(), Init(), and Register().
G4StableIsotopes G4ParticleHPChannelList::theStableOnes private
Definition at line 109 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPChannelList.hh
G4ThreadLocal G4int G4ParticleHPChannelList::trycounter = 0 static private
Definition at line 100 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ParticleHPChannelList.hh
G4HadFinalState G4ParticleHPChannelList::unChanged private
Definition at line 113 of file G4ParticleHPChannelList.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleHPChannelList.hh
Referenced by ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPChannelList.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPChannelList.cc