ECCE @ EIC Software: G4INCL::INCL::RecoilCMFunctor Class Reference
G4INCL::INCL::RecoilCMFunctor Class Reference
Class to adjust remnant recoil in the reaction CM system.
Public Member Functions
RecoilCMFunctor (Nucleus *const n, const EventInfo &ei)
Prepare for calling the () operator and scaleParticleEnergies.
virtual ~RecoilCMFunctor ()
G4double operator() (const G4double x) const
Compute the energy-conservation violation.
void cleanUp (const G4bool success) const
Clean up after root finding.
Public Member Functions inherited from G4INCL::RootFunctor
virtual ~RootFunctor ()
Public Member Functions inherited from G4INCL::IFunction1D
IFunction1D ()
IFunction1D (const G4double x0, const G4double x1)
virtual ~IFunction1D ()
virtual G4double getXMinimum () const
Return the minimum allowed value of the independent variable.
virtual G4double getXMaximum () const
Return the maximum allowed value of the independent variable.
virtual G4double integrate (const G4double x0, const G4double x1, const G4double step=-1.) const
Integrate the function between two values.
IFunction1D * primitive () const
Return a pointer to the (numerical) primitive to this function.
InterpolationTable * inverseCDFTable (ManipulatorFunc fWrap=0, const G4int nNodes=60) const
Return a pointer to the inverse of the CDF of this function.
Private Member Functions
void scaleParticleCMMomenta (const G4double rescale) const
Scale the kinetic energies of the outgoing particles.
Private Attributes
Nucleus * nucleus
Pointer to the nucleus.
ThreeVector thePTBoostVector
Projectile-target CM boost vector.
ThreeVector theIncomingMomentum
Incoming momentum.
ParticleList outgoingParticles
List of final-state particles.
EventInfo const & theEventInfo
Reference to the EventInfo object.
std::list< ThreeVector > particleCMMomenta
Initial CM momenta of the outgoing particles.
Additional Inherited Members
Public Types inherited from G4INCL::IFunction1D
typedef G4double(*const ManipulatorFunc)(const G4double)
Typedef to simplify the syntax of inverseCDFTable.
Protected Member Functions inherited from G4INCL::RootFunctor
RootFunctor (const G4double x0, const G4double x1)
Protected Attributes inherited from G4INCL::IFunction1D
G4double xMin
Minimum value of the independent variable.
G4double xMax
Maximum value of the independent variable.
Detailed Description
Class to adjust remnant recoil in the reaction CM system.
Definition at line 190 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 190 of file G4INCLCascade.hh
Constructor & Destructor Documentation
G4INCL::INCL::RecoilCMFunctor::RecoilCMFunctor (Nucleus *const n, const EventInfo & ei) inline
Prepare for calling the () operator and scaleParticleEnergies.
The constructor sets the private class members.
Definition at line 196 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 196 of file G4INCLCascade.hh
References G4INCL::Cluster::boost(), e, G4INCL::Particle::getA(), G4INCL::Nucleus::getIncomingMomentum(), G4INCL::Nucleus::getInitialEnergy(), G4INCL::Particle::getMomentum(), G4INCL::Nucleus::getProjectileRemnant(), nucleus, outgoingParticles, particleCMMomenta, and thePTBoostVector.
virtual G4INCL::INCL::RecoilCMFunctor::~RecoilCMFunctor () inline virtual
Definition at line 214 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 214 of file G4INCLCascade.hh
Member Function Documentation
void G4INCL::INCL::RecoilCMFunctor::cleanUp (const G4bool success) const inline virtual
Clean up after root finding.
Implements G4INCL::RootFunctor.
Definition at line 227 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 227 of file G4INCLCascade.hh
References scaleParticleCMMomenta().
G4double G4INCL::INCL::RecoilCMFunctor::operator() (const G4double x) const inline virtual
Compute the energy-conservation violation.
Parameters
x scale factor for the particle energies
Returns
the energy-conservation violation
Implements G4INCL::IFunction1D.
Definition at line 221 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 221 of file G4INCLCascade.hh
References G4INCL::Nucleus::ConservationBalance::energy, G4INCL::Nucleus::getConservationBalance(), nucleus, scaleParticleCMMomenta(), and theEventInfo.
void G4INCL::INCL::RecoilCMFunctor::scaleParticleCMMomenta (const G4double rescale) const inline private
Scale the kinetic energies of the outgoing particles.
Parameters
rescale scale factor
Definition at line 250 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 250 of file G4INCLCascade.hh
References e, G4INCL::Particle::getA(), G4INCL::Nucleus::getExcitationEnergy(), G4INCL::Particle::getS(), G4INCL::ParticleTable::getTableMass, G4INCL::Particle::getZ(), G4INCL::ThreeVector::mag2(), nucleus, outgoingParticles, particleCMMomenta, G4INCL::Particle::setEnergy(), G4INCL::Particle::setMomentum(), theIncomingMomentum, and thePTBoostVector.
Referenced by cleanUp(), and operator()().
Member Data Documentation
Nucleus* G4INCL::INCL::RecoilCMFunctor::nucleus private
Pointer to the nucleus.
Definition at line 234 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 234 of file G4INCLCascade.hh
Referenced by operator()(), RecoilCMFunctor(), and scaleParticleCMMomenta().
ParticleList G4INCL::INCL::RecoilCMFunctor::outgoingParticles private
List of final-state particles.
Definition at line 240 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 240 of file G4INCLCascade.hh
Referenced by RecoilCMFunctor(), and scaleParticleCMMomenta().
std::list<ThreeVector> G4INCL::INCL::RecoilCMFunctor::particleCMMomenta private
Initial CM momenta of the outgoing particles.
Definition at line 244 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 244 of file G4INCLCascade.hh
Referenced by RecoilCMFunctor(), and scaleParticleCMMomenta().
EventInfo const& G4INCL::INCL::RecoilCMFunctor::theEventInfo private
Reference to the EventInfo object.
Definition at line 242 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 242 of file G4INCLCascade.hh
Referenced by operator()().
ThreeVector G4INCL::INCL::RecoilCMFunctor::theIncomingMomentum private
Incoming momentum.
Definition at line 238 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 238 of file G4INCLCascade.hh
Referenced by scaleParticleCMMomenta().
ThreeVector G4INCL::INCL::RecoilCMFunctor::thePTBoostVector private
Projectile-target CM boost vector.
Definition at line 236 of file G4INCLCascade.hh.
View newest version in sPHENIX GitHub at line 236 of file G4INCLCascade.hh
Referenced by RecoilCMFunctor(), and scaleParticleCMMomenta().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLCascade.hh