ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/G4gsdvn.cc File Reference
G4gsdvn.cc File Reference
#include "G3G4Interface.hh"
#include "G3Division.hh"
#include "G3VolTableEntry.hh"
#include "G3VolTable.hh"
#include "globals.hh"
#include "G3toG4.hh"
Functions
void PG4gsdvn (G4String *tokens)
void G4CreateCloneVTEWithDivision (G4String vname, G3VolTableEntry *mvte, G3DivType divType, G4int nofDivisions, G4int iaxis, G4int, G4double c0, G4double step)
void G4gsdvn (G4String vname, G4String vmoth, G4int ndiv, G4int iaxis)
Function Documentation
void G4CreateCloneVTEWithDivision (G4String vname, G3VolTableEntry * mvte, G3DivType divType, G4int nofDivisions, G4int iaxis, G4int , G4double c0, G4double step)
Definition at line 51 of file G4gsdvn.cc.
View newest version in sPHENIX GitHub at line 51 of file G4gsdvn.cc
References G3VolTableEntry::AddClone(), G3VolTableEntry::AddDaughter(), G3VolTableEntry::AddMother(), G4String::append(), G3Vol, G3VolTableEntry::GetClone(), G3VolTableEntry::GetName(), G3VolTableEntry::GetNmed(), G3VolTableEntry::GetNoClones(), G3VolTableEntry::GetShape(), gSeparator, G3VolTable::PutVTE(), G3VolTableEntry::SetDivision(), and G3Division::UpdateVTE().
Referenced by G4gsdvn(), G4gsdvn2(), G4gsdvt(), and G4gsdvt2().
void G4gsdvn (G4String vname, G4String vmoth, G4int ndiv, G4int iaxis)
Definition at line 102 of file G4gsdvn.cc.
View newest version in sPHENIX GitHub at line 102 of file G4gsdvn.cc
References FatalException, G3Vol, G4CreateCloneVTEWithDivision(), G4Exception(), G3VolTable::GetVTE(), and kDvn.
Referenced by PG4gsdvn().
void PG4gsdvn (G4String * tokens)
Definition at line 37 of file G4gsdvn.cc.
View newest version in sPHENIX GitHub at line 37 of file G4gsdvn.cc
References G3fillParams(), G4gsdvn(), Ipar, PTgsdvn, and Spar.
Referenced by G3CLEval().