ECCE @ EIC Software: ecce-detectors/blob/master/FastPID/hpDIRC/prttools.C File Reference
prttools.C File Reference
#include "TROOT.h"
#include "TSystem.h"
#include "TStyle.h"
#include "TCanvas.h"
#include "TPad.h"
#include "TH1.h"
#include "TH2.h"
#include "TGraph.h"
#include "TMultiGraph.h"
#include "TSpline.h"
#include "TF1.h"
#include "TFile.h"
#include "TTree.h"
#include "TClonesArray.h"
#include "TVector3.h"
#include "TMath.h"
#include "TChain.h"
#include "TGaxis.h"
#include "TColor.h"
#include "TString.h"
#include "TArrayD.h"
#include "TSpectrum.h"
#include "TSpectrum2.h"
#include "Math/Minimizer.h"
#include "Math/Factory.h"
#include "Math/Functor.h"
#include "TRandom2.h"
#include "TError.h"
#include "TPaveStats.h"
#include "TObjString.h"
#include "TApplication.h"
#include <TLegend.h>
#include <TAxis.h>
#include <TPaletteAxis.h>
#include <TRandom.h>
#include <TCutG.h>
#include <TKey.h>
#include "TPRegexp.h"
#include "TFitResult.h"
#include <iostream>
#include <fstream>
#include <sstream>
Macros
#define prttools_h 1
Functions
int prt_entries (0)
int prt_particle (0)
int prt_geometry (2023)
int prt_beamx (0)
int prt_beamz (0)
double prt_theta (0)
double prt_test1 (0)
double prt_test2 (0)
double prt_mom (0)
double prt_phi (0)
TString prt_savepath ("")
TString prt_info ("")
int prt_pid (0)
TVector3 prt_fit (TH1 *h, double range=3, double threshold=20, double limit=2, int peakSearch=1, int bkg=0, TString opt="MQ")
TGraph * prt_fitslices (TH2F *hh, double minrange=0, double maxrange=0, double fitrange=1, int rebin=1, int ret=0)
void prt_createMap (int setupid=2019)
int prt_getChannelNumber (int tdc, int tdcChannel)
int prt_getTdcId (int ch)
TString prt_getTdcName (int ch)
int prt_getTdcChannel (int ch)
int prt_removeRefChannels (int ch, int tdcSeqId)
int prt_addRefChannels (int ch, int tdcSeqId)
Bool_t prt_isBadChannel (int ch)
TString prt_randstr (int len=10)
TCanvas * prt_drawDigi (int layoutId=0, double maxz=0, double minz=0, TCanvas *cdigi=NULL)
TString prt_getPixData (TString s="m,p,v\n", int layoutId=1)
void prt_initDigi (int type=1)
void prt_resetDigi ()
void prt_axisHits800x500 (TH2 *hist)
void prt_axisAngle800x500 (TH2 *hist)
void prt_axisAngle800x500 (TH1 *hist)
void prt_axisTime800x500 (TH2 *hist)
void prt_axisTime800x500 (TH1 *hist, TString xtitle="time [ns]")
void prt_setPrettyStyle ()
void prt_setGStyle (TGraph *g, int id)
void prt_setRootPalette (int pal=0)
int prt_getColorId (int ind, int style=0)
int prt_shiftHist (TH1 *hist, double double_shift)
void prt_addInfo (TString str)
void prt_writeInfo (TString filename)
void prt_writeString (TString filename, TString str)
TString prt_createDir (TString inpath="")
void prt_canvasPrint (TPad *c, TString name="", TString path="", int what=0)
void prt_set_style (TCanvas *c)
void prt_save (TPad *c=NULL, TString path="", int what=0, int style=0)
TString prt_createSubDir (TString dir="dir")
TCanvas * prt_canvasGet (TString name="c")
void prt_canvasAdd (TString name="c", int w=800, int h=400)
void prt_canvasAdd (TCanvas *c)
void prt_canvasCd ()
void prt_canvasDel (TString name="c")
void prt_canvasSave (int what=1, int style=0, Bool_t rm=false)
void prt_canvasSave (TString path, int what=1, int style=0, Bool_t rm=false)
void prt_set_style ()
void prt_waitPrimitive (TString name, TString prim="")
double prt_integral (TH1F *h, double xmin, double xmax)
void prt_normalize (TH1F *hists[], int size)
void prt_normalizeto (TH1F *hists[], int size, double max=1)
void prt_normalize (TH1F *h1, TH1F *h2)
TGraph * prt_smooth (TGraph *g, int smoothness=1)
int prt_get_pid (int pdg)
double prt_get_momentum_from_tof (double dist, double dtof)
double prt_get_tof_diff (int pid1=211, int pid2=321, double p=1, double l=2)
bool prt_ispath (TString path)
int prt_get3digit (TString str)
Variables
const int prt_nmcp = 24
const int prt_npix = 16 * 16
const int prt_ntdc_may2015 =41
TString prt_tdcsid_may2015 []
const int prt_ntdc_jun2015 =30
TString prt_tdcsid_jun2015 []
const int prt_ntdc_oct2016 =20
TString prt_tdcsid_oct2016 []
const int prt_ntdc_jul2018 = 32
TString prt_tdcsid_jul2018 []
const int prt_ntdc_jul2019 = 21
TString prt_tdcsid_jul2019 []
const int prt_maxdircch = prt_nmcp*prt_npix
const int prt_maxnametdc =10000
TRandom prt_rand
TChain * prt_ch = 0
int prt_last_layoutId
int prt_last_max
int prt_last_maxz
int prt_last_minz
TH2F * prt_hdigi [prt_nmcp]
TSpectrum * prt_spect = new TSpectrum(2)
const int prt_ntdcm = 80
int prt_ntdc = prt_ntdcm
int prt_maxch = prt_ntdc*48
TString prt_tdcsid [prt_ntdcm]
const int prt_maxchm = prt_ntdcm*48
int map_tdc [prt_maxnametdc]
int map_mpc [prt_maxchm/prt_npix][prt_npix]
int map_mcp [prt_maxchm]
int map_pix [prt_maxchm]
int map_row [prt_maxchm]
int map_col [prt_maxchm]
int prt_pdg [] ={11,13,211,321,2212}
double prt_mass [] ={0.000511,0.1056584,0.139570,0.49368,0.9382723}
TString prt_name [] ={"e","muon","pion","kaon","proton"}
TString prt_lname [] ={"e","#mu","#pi","K","p"}
int prt_color [] ={kOrange+6,kCyan+1,kBlue+1,kRed+1,kRed+1}
double prt_particleArray [3000]
TF1 * prt_gaust
TH1 * prt_cdigi_th
TList * prt_canvaslist
Macro Definition Documentation
#define prttools_h 1
Definition at line 5 of file prttools.C.
View newest version in sPHENIX GitHub at line 5 of file prttools.C
Function Documentation
void prt_addInfo (TString str)
Definition at line 1023 of file prttools.C.
View newest version in sPHENIX GitHub at line 1023 of file prttools.C
References prt_info().
int prt_addRefChannels (int ch, int tdcSeqId)
Definition at line 371 of file prttools.C.
View newest version in sPHENIX GitHub at line 371 of file prttools.C
void prt_axisAngle800x500 (TH2 * hist)
Definition at line 703 of file prttools.C.
View newest version in sPHENIX GitHub at line 703 of file prttools.C
void prt_axisAngle800x500 (TH1 * hist)
Definition at line 714 of file prttools.C.
View newest version in sPHENIX GitHub at line 714 of file prttools.C
void prt_axisHits800x500 (TH2 * hist)
Definition at line 692 of file prttools.C.
View newest version in sPHENIX GitHub at line 692 of file prttools.C
void prt_axisTime800x500 (TH2 * hist)
Definition at line 725 of file prttools.C.
View newest version in sPHENIX GitHub at line 725 of file prttools.C
void prt_axisTime800x500 (TH1 * hist, TString xtitle = "time [ns]")
Definition at line 735 of file prttools.C.
View newest version in sPHENIX GitHub at line 735 of file prttools.C
int prt_beamx (0)
int prt_beamz (0)
void prt_canvasAdd (TString name = "c", int w = 800, int h = 400)
Definition at line 1218 of file prttools.C.
View newest version in sPHENIX GitHub at line 1218 of file prttools.C
References c, Acts::UnitConstants::h, prt_canvasGet(), and w.
Referenced by plot_map(), and scan_mom().
void prt_canvasAdd (TCanvas * c)
Definition at line 1226 of file prttools.C.
View newest version in sPHENIX GitHub at line 1226 of file prttools.C
void prt_canvasCd ()
Definition at line 1232 of file prttools.C.
View newest version in sPHENIX GitHub at line 1232 of file prttools.C
void prt_canvasDel (TString name = "c")
Definition at line 1236 of file prttools.C.
View newest version in sPHENIX GitHub at line 1236 of file prttools.C
References c.
TCanvas* prt_canvasGet (TString name = "c")
Definition at line 1209 of file prttools.C.
View newest version in sPHENIX GitHub at line 1209 of file prttools.C
References c.
Referenced by prt_canvasAdd().
void prt_canvasPrint (TPad * c, TString name = "", TString path = "", int what = 0)
Definition at line 1070 of file prttools.C.
View newest version in sPHENIX GitHub at line 1070 of file prttools.C
Referenced by prt_save().
void prt_canvasSave (int what = 1, int style = 0, Bool_t rm = false)
Definition at line 1251 of file prttools.C.
View newest version in sPHENIX GitHub at line 1251 of file prttools.C
References c, prt_createDir(), prt_save(), and prt_set_style().
Referenced by plot_map(), prt_canvasSave(), and scan_mom().
void prt_canvasSave (TString path, int what = 1, int style = 0, Bool_t rm = false)
Definition at line 1266 of file prttools.C.
View newest version in sPHENIX GitHub at line 1266 of file prttools.C
References prt_canvasSave(), and prt_savepath().
TString prt_createDir (TString inpath = "")
Definition at line 1042 of file prttools.C.
View newest version in sPHENIX GitHub at line 1042 of file prttools.C
References dir, prt_savepath(), prt_writeInfo(), and Acts::VectorHelpers::time().
Referenced by prt_canvasSave(), and prt_set_style().
void prt_createMap (int setupid = 2019)
Definition at line 264 of file prttools.C.
View newest version in sPHENIX GitHub at line 264 of file prttools.C
References col, map_col, map_mcp, map_mpc, map_pix, map_row, map_tdc, prt_geometry(), prt_maxch, prt_maxnametdc, prt_npix, prt_ntdc, prt_ntdc_jul2018, prt_ntdc_jul2019, prt_ntdc_jun2015, prt_ntdc_oct2016, prt_particleArray, prt_pdg, prt_tdcsid, prt_tdcsid_jul2018, prt_tdcsid_jul2019, prt_tdcsid_jun2015, and prt_tdcsid_oct2016.
TString prt_createSubDir (TString dir = "dir")
Definition at line 1202 of file prttools.C.
View newest version in sPHENIX GitHub at line 1202 of file prttools.C
References dir.
TCanvas* prt_drawDigi (int layoutId = 0, double maxz = 0, double minz = 0, TCanvas * cdigi = NULL)
Definition at line 416 of file prttools.C.
View newest version in sPHENIX GitHub at line 416 of file prttools.C
References GetEntries(), Acts::UnitConstants::h, max, G4B0ECAL::maxz, G4B0ECAL::minz, prt_geometry(), prt_hdigi, prt_last_layoutId, prt_last_max, prt_last_maxz, prt_last_minz, prt_nmcp, and prt_randstr().
Referenced by prt_save().
int prt_entries (0)
TVector3 prt_fit (TH1 * h, double range = 3, double threshold = 20, double limit = 2, int peakSearch = 1, int bkg = 0, TString opt = "MQ")
Definition at line 147 of file prttools.C.
View newest version in sPHENIX GitHub at line 147 of file prttools.C
References prt_gaust, prt_spect, and xmax.
Referenced by prt_fitslices().
TGraph* prt_fitslices (TH2F * hh, double minrange = 0, double maxrange = 0, double fitrange = 1, int rebin = 1, int ret = 0)
Definition at line 225 of file prttools.C.
View newest version in sPHENIX GitHub at line 225 of file prttools.C
References Acts::UnitConstants::h, prt_fit(), x, and y.
int prt_geometry (2023)
Referenced by prt_createMap(), prt_drawDigi(), prt_getChannelNumber(), prt_getTdcChannel(), and prt_getTdcId().
int prt_get3digit (TString str)
Definition at line 1394 of file prttools.C.
View newest version in sPHENIX GitHub at line 1394 of file prttools.C
References e.
double prt_get_momentum_from_tof (double dist, double dtof)
Definition at line 1366 of file prttools.C.
View newest version in sPHENIX GitHub at line 1366 of file prttools.C
References a, b, prt_mass, and x.
int prt_get_pid (int pdg)
Definition at line 1356 of file prttools.C.
View newest version in sPHENIX GitHub at line 1356 of file prttools.C
References pid.
Referenced by prt_get_tof_diff().
double prt_get_tof_diff (int pid1 = 211, int pid2 = 321, double p = 1, double l = 2)
Definition at line 1377 of file prttools.C.
View newest version in sPHENIX GitHub at line 1377 of file prttools.C
References c, m2, prt_get_pid(), and prt_mass.
int prt_getChannelNumber (int tdc, int tdcChannel)
Definition at line 308 of file prttools.C.
View newest version in sPHENIX GitHub at line 308 of file prttools.C
References prt_geometry().
int prt_getColorId (int ind, int style = 0)
Definition at line 986 of file prttools.C.
View newest version in sPHENIX GitHub at line 986 of file prttools.C
TString prt_getPixData (TString s = "m,p,v\n", int layoutId = 1)
Definition at line 616 of file prttools.C.
View newest version in sPHENIX GitHub at line 616 of file prttools.C
References GetEntries(), nmax, prt_hdigi, prt_last_max, prt_last_maxz, prt_last_minz, and weight.
int prt_getTdcChannel (int ch)
Definition at line 348 of file prttools.C.
View newest version in sPHENIX GitHub at line 348 of file prttools.C
References prt_geometry(), and prt_ntdc.
int prt_getTdcId (int ch)
Definition at line 326 of file prttools.C.
View newest version in sPHENIX GitHub at line 326 of file prttools.C
References prt_geometry(), and prt_ntdc.
Referenced by prt_getTdcName().
TString prt_getTdcName (int ch)
Definition at line 344 of file prttools.C.
View newest version in sPHENIX GitHub at line 344 of file prttools.C
References prt_getTdcId(), and prt_tdcsid.
TString prt_info ("")
Referenced by prt_addInfo(), and prt_writeInfo().
void prt_initDigi (int type = 1)
Definition at line 647 of file prttools.C.
View newest version in sPHENIX GitHub at line 647 of file prttools.C
References m, prt_hdigi, and prt_nmcp.
double prt_integral (TH1F * h, double xmin, double xmax)
Definition at line 1292 of file prttools.C.
View newest version in sPHENIX GitHub at line 1292 of file prttools.C
References xmax.
Bool_t prt_isBadChannel (int ch)
Definition at line 375 of file prttools.C.
View newest version in sPHENIX GitHub at line 375 of file prttools.C
References prt_maxdircch.
bool prt_ispath (TString path)
Definition at line 1389 of file prttools.C.
View newest version in sPHENIX GitHub at line 1389 of file prttools.C
double prt_mom (0)
void prt_normalize (TH1F * hists[], int size)
Definition at line 1302 of file prttools.C.
View newest version in sPHENIX GitHub at line 1302 of file prttools.C
References max, and min.
void prt_normalize (TH1F * h1, TH1F * h2)
Definition at line 1328 of file prttools.C.
View newest version in sPHENIX GitHub at line 1328 of file prttools.C
References max.
void prt_normalizeto (TH1F * hists[], int size, double max = 1)
Definition at line 1321 of file prttools.C.
View newest version in sPHENIX GitHub at line 1321 of file prttools.C
References max.
int prt_particle (0)
double prt_phi (0)
int prt_pid (0)
TString prt_randstr (int len = 10)
Definition at line 392 of file prttools.C.
View newest version in sPHENIX GitHub at line 392 of file prttools.C
Referenced by prt_drawDigi().
int prt_removeRefChannels (int ch, int tdcSeqId)
Definition at line 367 of file prttools.C.
View newest version in sPHENIX GitHub at line 367 of file prttools.C
void prt_resetDigi ()
Definition at line 686 of file prttools.C.
View newest version in sPHENIX GitHub at line 686 of file prttools.C
References m, prt_hdigi, and prt_nmcp.
void prt_save (TPad * c = NULL, TString path = "", int what = 0, int style = 0)
Definition at line 1162 of file prttools.C.
View newest version in sPHENIX GitHub at line 1162 of file prttools.C
References c, Acts::UnitConstants::h, prt_canvasPrint(), prt_drawDigi(), prt_last_layoutId, prt_last_maxz, prt_last_minz, prt_set_style(), and w.
Referenced by prt_canvasSave().
TString prt_savepath ("")
Referenced by plot_map(), prt_canvasSave(), prt_createDir(), and scan_mom().
void prt_set_style (TCanvas * c)
Definition at line 1079 of file prttools.C.
View newest version in sPHENIX GitHub at line 1079 of file prttools.C
References f, and hh.
Referenced by prt_canvasSave(), prt_save(), and prt_set_style().
void prt_set_style ()
Definition at line 1271 of file prttools.C.
View newest version in sPHENIX GitHub at line 1271 of file prttools.C
References c, prt_createDir(), and prt_set_style().
void prt_setGStyle (TGraph * g, int id)
Definition at line 781 of file prttools.C.
View newest version in sPHENIX GitHub at line 781 of file prttools.C
References cm.
void prt_setPrettyStyle ()
Definition at line 748 of file prttools.C.
View newest version in sPHENIX GitHub at line 748 of file prttools.C
void prt_setRootPalette (int pal = 0)
Definition at line 794 of file prttools.C.
View newest version in sPHENIX GitHub at line 794 of file prttools.C
Referenced by plot_map().
int prt_shiftHist (TH1 * hist, double double_shift)
Definition at line 997 of file prttools.C.
View newest version in sPHENIX GitHub at line 997 of file prttools.C
References xmax, and xmin.
TGraph* prt_smooth (TGraph * g, int smoothness = 1)
Definition at line 1336 of file prttools.C.
View newest version in sPHENIX GitHub at line 1336 of file prttools.C
References Acts::UnitConstants::h, n, x, and y.
double prt_test1 (0)
double prt_test2 (0)
double prt_theta (0)
void prt_waitPrimitive (TString name, TString prim = "")
Definition at line 1280 of file prttools.C.
View newest version in sPHENIX GitHub at line 1280 of file prttools.C
References c.
void prt_writeInfo (TString filename)
Definition at line 1027 of file prttools.C.
View newest version in sPHENIX GitHub at line 1027 of file prttools.C
References prt_info().
Referenced by prt_createDir().
void prt_writeString (TString filename, TString str)
Definition at line 1034 of file prttools.C.
View newest version in sPHENIX GitHub at line 1034 of file prttools.C
Variable Documentation
int map_col[prt_maxchm]
Definition at line 137 of file prttools.C.
View newest version in sPHENIX GitHub at line 137 of file prttools.C
Referenced by prt_createMap().
int map_mcp[prt_maxchm]
Definition at line 134 of file prttools.C.
View newest version in sPHENIX GitHub at line 134 of file prttools.C
Referenced by prt_createMap().
int map_mpc[prt_maxchm/prt_npix][prt_npix]
Definition at line 133 of file prttools.C.
View newest version in sPHENIX GitHub at line 133 of file prttools.C
Referenced by prt_createMap().
int map_pix[prt_maxchm]
Definition at line 135 of file prttools.C.
View newest version in sPHENIX GitHub at line 135 of file prttools.C
Referenced by prt_createMap().
int map_row[prt_maxchm]
Definition at line 136 of file prttools.C.
View newest version in sPHENIX GitHub at line 136 of file prttools.C
Referenced by prt_createMap().
int map_tdc[prt_maxnametdc]
Definition at line 132 of file prttools.C.
View newest version in sPHENIX GitHub at line 132 of file prttools.C
Referenced by prt_createMap().
TList* prt_canvaslist
Definition at line 1207 of file prttools.C.
View newest version in sPHENIX GitHub at line 1207 of file prttools.C
TH1* prt_cdigi_th
Definition at line 415 of file prttools.C.
View newest version in sPHENIX GitHub at line 415 of file prttools.C
TChain* prt_ch = 0
Definition at line 119 of file prttools.C.
View newest version in sPHENIX GitHub at line 119 of file prttools.C
int prt_color[] ={kOrange+6,kCyan+1,kBlue+1,kRed+1,kRed+1}
Definition at line 143 of file prttools.C.
View newest version in sPHENIX GitHub at line 143 of file prttools.C
TF1* prt_gaust
Definition at line 146 of file prttools.C.
View newest version in sPHENIX GitHub at line 146 of file prttools.C
Referenced by prt_fit().
TH2F* prt_hdigi[prt_nmcp]
Definition at line 124 of file prttools.C.
View newest version in sPHENIX GitHub at line 124 of file prttools.C
Referenced by prt_drawDigi(), prt_getPixData(), prt_initDigi(), and prt_resetDigi().
int prt_last_layoutId
Definition at line 121 of file prttools.C.
View newest version in sPHENIX GitHub at line 121 of file prttools.C
Referenced by prt_drawDigi(), and prt_save().
int prt_last_max
Definition at line 121 of file prttools.C.
View newest version in sPHENIX GitHub at line 121 of file prttools.C
Referenced by prt_drawDigi(), and prt_getPixData().
int prt_last_maxz
Definition at line 121 of file prttools.C.
View newest version in sPHENIX GitHub at line 121 of file prttools.C
Referenced by prt_drawDigi(), prt_getPixData(), and prt_save().
int prt_last_minz
Definition at line 121 of file prttools.C.
View newest version in sPHENIX GitHub at line 121 of file prttools.C
Referenced by prt_drawDigi(), prt_getPixData(), and prt_save().
TString prt_lname[] ={"e","#mu","#pi","K","p"}
Definition at line 142 of file prttools.C.
View newest version in sPHENIX GitHub at line 142 of file prttools.C
double prt_mass[] ={0.000511,0.1056584,0.139570,0.49368,0.9382723}
Definition at line 140 of file prttools.C.
View newest version in sPHENIX GitHub at line 140 of file prttools.C
Referenced by prt_get_momentum_from_tof(), and prt_get_tof_diff().
int prt_maxch = prt_ntdc*48
Definition at line 129 of file prttools.C.
View newest version in sPHENIX GitHub at line 129 of file prttools.C
Referenced by prt_createMap().
const int prt_maxchm = prt_ntdcm*48
Definition at line 131 of file prttools.C.
View newest version in sPHENIX GitHub at line 131 of file prttools.C
const int prt_maxdircch = prt_nmcp*prt_npix
Definition at line 115 of file prttools.C.
View newest version in sPHENIX GitHub at line 115 of file prttools.C
Referenced by prt_isBadChannel().
const int prt_maxnametdc =10000
Definition at line 116 of file prttools.C.
View newest version in sPHENIX GitHub at line 116 of file prttools.C
Referenced by prt_createMap().
TString prt_name[] ={"e","muon","pion","kaon","proton"}
Definition at line 141 of file prttools.C.
View newest version in sPHENIX GitHub at line 141 of file prttools.C
const int prt_nmcp = 24
Definition at line 69 of file prttools.C.
View newest version in sPHENIX GitHub at line 69 of file prttools.C
Referenced by prt_drawDigi(), prt_initDigi(), and prt_resetDigi().
const int prt_npix = 16 * 16
Definition at line 70 of file prttools.C.
View newest version in sPHENIX GitHub at line 70 of file prttools.C
Referenced by prt_createMap().
int prt_ntdc = prt_ntdcm
Definition at line 128 of file prttools.C.
View newest version in sPHENIX GitHub at line 128 of file prttools.C
Referenced by prt_createMap(), prt_getTdcChannel(), and prt_getTdcId().
const int prt_ntdc_jul2018 = 32
Definition at line 103 of file prttools.C.
View newest version in sPHENIX GitHub at line 103 of file prttools.C
Referenced by prt_createMap().
const int prt_ntdc_jul2019 = 21
Definition at line 110 of file prttools.C.
View newest version in sPHENIX GitHub at line 110 of file prttools.C
Referenced by prt_createMap().
const int prt_ntdc_jun2015 =30
Definition at line 89 of file prttools.C.
View newest version in sPHENIX GitHub at line 89 of file prttools.C
Referenced by prt_createMap().
const int prt_ntdc_may2015 =41
Definition at line 81 of file prttools.C.
View newest version in sPHENIX GitHub at line 81 of file prttools.C
const int prt_ntdc_oct2016 =20
Definition at line 96 of file prttools.C.
View newest version in sPHENIX GitHub at line 96 of file prttools.C
Referenced by prt_createMap().
const int prt_ntdcm = 80
Definition at line 127 of file prttools.C.
View newest version in sPHENIX GitHub at line 127 of file prttools.C
double prt_particleArray[3000]
Definition at line 144 of file prttools.C.
View newest version in sPHENIX GitHub at line 144 of file prttools.C
Referenced by prt_createMap().
int prt_pdg[] ={11,13,211,321,2212}
Definition at line 139 of file prttools.C.
View newest version in sPHENIX GitHub at line 139 of file prttools.C
Referenced by prt_createMap().
TRandom prt_rand
Definition at line 118 of file prttools.C.
View newest version in sPHENIX GitHub at line 118 of file prttools.C
TSpectrum* prt_spect = new TSpectrum(2)
Definition at line 125 of file prttools.C.
View newest version in sPHENIX GitHub at line 125 of file prttools.C
Referenced by prt_fit().
TString prt_tdcsid[prt_ntdcm]
Definition at line 130 of file prttools.C.
View newest version in sPHENIX GitHub at line 130 of file prttools.C
Referenced by prt_createMap(), and prt_getTdcName().
TString prt_tdcsid_jul2018[]
Initial value:
={"2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","200a","200b","200c","200d","200e","200f","2010","2011","2012","2013",
             "2014","2015","2016","2017","2018","2019","201a","201b",
             "201c","201d","201e","201f"
}
Definition at line 104 of file prttools.C.
View newest version in sPHENIX GitHub at line 104 of file prttools.C
Referenced by prt_createMap().
TString prt_tdcsid_jul2019[]
Initial value:
={"2014","2015","2016","2017","2000","2001","2002","2003","2004","2005",
             "2006","2007","2008","2009","200a","200b","200c","200d","200e","200f",
             "2010"}
Definition at line 111 of file prttools.C.
View newest version in sPHENIX GitHub at line 111 of file prttools.C
Referenced by prt_createMap().
TString prt_tdcsid_jun2015[]
Initial value:
={"2000","2001","2002","2003","2004","2005","2006","2007","2008","2009",
       "200a","200b","200c","200d","200e","200f","2010","2011","2012","2013",
       "2014","2015","2016","2018","2019","201a","201c","201d","202c","202d"
}
Definition at line 90 of file prttools.C.
View newest version in sPHENIX GitHub at line 90 of file prttools.C
Referenced by prt_createMap().
TString prt_tdcsid_may2015[]
Initial value:
={"2000","2001","2002","2003","2004","2005","2006","2007","2008","2009",
       "200a","200b","200c","200d","200e","200f","2010","2011","2012","2013",
       "2014","2015","2016","2018","2019","201a","201c","2020","2023","2024",
       "2025","2026","2027","2028","2029","202a","202b","202c","202d","202e","202f"
}
Definition at line 82 of file prttools.C.
View newest version in sPHENIX GitHub at line 82 of file prttools.C
TString prt_tdcsid_oct2016[]
Initial value:
={"2000","2001","2002","2003","2004","2005","2006","2007","2008","2009",
             "200a","200b","200c",
             "2018","201b","201c","201f","202c","202d","202d"
}
Definition at line 97 of file prttools.C.
View newest version in sPHENIX GitHub at line 97 of file prttools.C
Referenced by prt_createMap().