ECCE @ EIC Software: CCalPrimaryGeneratorAction Class Reference
CCalPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalPrimaryGeneratorAction.hh>
Public Member Functions
CCalPrimaryGeneratorAction ()
~CCalPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *anEvent)
void SetVerboseLevel (G4int val)
void SetRandom (G4String val)
void SetScan (G4String val)
void SetMinimumEnergy (G4double p)
void SetMaximumEnergy (G4double p)
void SetMinimumPhi (G4double p)
void SetMaximumPhi (G4double p)
void SetStepsPhi (G4int val)
void SetMinimumEta (G4double p)
void SetMaximumEta (G4double p)
void SetStepsEta (G4int val)
void SetGunPosition (const G4ThreeVector &pos) const
void SetRunNo (G4int val)
G4ThreeVector GetParticlePosition ()
G4double GetParticleEnergy ()
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Member Functions
void initialize ()
void print (G4int val)
Private Attributes
CCalPrimaryGeneratorMessenger * gunMessenger
G4ParticleGun * particleGun
generatorInputType generatorInput
G4int verboseLevel
G4int n_particle
G4String particleName
G4double particleEnergy
G4ThreeVector particlePosition
G4ThreeVector particleDir
G4double energyMin
G4double energyMax
G4double etaMin
G4double etaMax
G4double phiMin
G4double phiMax
G4int etaSteps
G4int phiSteps
G4int isInitialized
G4double etaValue
G4double phiValue
G4int scanSteps
Detailed Description
Definition at line 65 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 65 of file CCalPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
CCalPrimaryGeneratorAction::CCalPrimaryGeneratorAction ()
Definition at line 49 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 49 of file CCalPrimaryGeneratorAction.cc
References degree, G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), GeV, gunMessenger, n_particle, particle, particleDir, particleEnergy, particleGun, particleName, particlePosition, print(), SetMaximumEnergy(), SetMaximumEta(), SetMaximumPhi(), SetMinimumEnergy(), SetMinimumEta(), SetMinimumPhi(), G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), SetStepsEta(), SetStepsPhi(), and TeV.
CCalPrimaryGeneratorAction::~CCalPrimaryGeneratorAction ()
Definition at line 82 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 82 of file CCalPrimaryGeneratorAction.cc
References gunMessenger, and particleGun.
Member Function Documentation
void CCalPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 89 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 89 of file CCalPrimaryGeneratorAction.cc
References deg, E, energyMax, energyMin, Acts::VectorHelpers::eta(), etaMax, etaMin, etaSteps, etaValue, G4cout, G4endl, G4Exp(), G4ParticleGun::GeneratePrimaryVertex(), generatorInput, GeV, initialize(), isInitialized, particleDir, particleEnergy, particleGun, phi, phiMax, phiMin, phiSteps, phiValue, scanSteps, G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), CLHEP::RandFlat::shoot(), singleRandom, singleScan, theta(), and verboseLevel.
G4double CCalPrimaryGeneratorAction::GetParticleEnergy () inline
Definition at line 90 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 90 of file CCalPrimaryGeneratorAction.hh
References G4ParticleGun::GetParticleEnergy(), and particleGun.
Referenced by CCalEventAction::EndOfEventAction().
G4ThreeVector CCalPrimaryGeneratorAction::GetParticlePosition () inline
Definition at line 89 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 89 of file CCalPrimaryGeneratorAction.hh
References G4VPrimaryGenerator::GetParticlePosition(), and particleGun.
Referenced by CCalEventAction::EndOfEventAction().
void CCalPrimaryGeneratorAction::initialize () private
Definition at line 335 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 335 of file CCalPrimaryGeneratorAction.cc
References isInitialized, and print().
Referenced by GeneratePrimaries().
void CCalPrimaryGeneratorAction::print (G4int val) private
Definition at line 343 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 343 of file CCalPrimaryGeneratorAction.cc
References degree, energyMax, energyMin, etaMax, etaMin, etaSteps, G4cout, G4endl, generatorInput, G4ParticleGun::GetNumberOfParticles(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), G4ParticleGun::GetParticleMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4VPrimaryGenerator::GetParticlePosition(), GeV, particleGun, phiMax, phiMin, phiSteps, singleFixed, singleRandom, singleScan, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), initialize(), SetRandom(), and SetScan().
void CCalPrimaryGeneratorAction::SetGunPosition (const G4ThreeVector & pos) const
Definition at line 326 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 326 of file CCalPrimaryGeneratorAction.cc
References particleGun, and G4VPrimaryGenerator::SetParticlePosition().
void CCalPrimaryGeneratorAction::SetMaximumEnergy (G4double p)
Definition at line 214 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 214 of file CCalPrimaryGeneratorAction.cc
References energyMax, G4cerr, G4cout, G4endl, GeV, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), and CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetMaximumEta (G4double p)
Definition at line 298 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 298 of file CCalPrimaryGeneratorAction.cc
References etaMax, G4cout, G4endl, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), and CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetMaximumPhi (G4double p)
Definition at line 250 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 250 of file CCalPrimaryGeneratorAction.cc
References G4cerr, G4cout, G4endl, phiMax, pi, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), and CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetMinimumEnergy (G4double p)
Definition at line 196 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 196 of file CCalPrimaryGeneratorAction.cc
References energyMin, G4cerr, G4cout, G4endl, GeV, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), and CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetMinimumEta (G4double p)
Definition at line 286 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 286 of file CCalPrimaryGeneratorAction.cc
References etaMin, G4cout, G4endl, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), and CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetMinimumPhi (G4double p)
Definition at line 232 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 232 of file CCalPrimaryGeneratorAction.cc
References G4cerr, G4cout, G4endl, phiMin, pi, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), and CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetRandom (G4String val)
Definition at line 171 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 171 of file CCalPrimaryGeneratorAction.cc
References generatorInput, print(), singleFixed, and singleRandom.
Referenced by CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetRunNo (G4int val)
Definition at line 331 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 331 of file CCalPrimaryGeneratorAction.cc
References G4RunManager::GetRunManager(), and G4RunManager::SetRunIDCounter().
Referenced by CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetScan (G4String val)
Definition at line 183 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 183 of file CCalPrimaryGeneratorAction.cc
References generatorInput, print(), scanSteps, singleFixed, and singleScan.
Referenced by CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetStepsEta (G4int val)
Definition at line 310 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 310 of file CCalPrimaryGeneratorAction.cc
References etaSteps, G4cerr, G4cout, G4endl, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), and CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetStepsPhi (G4int val)
Definition at line 268 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 268 of file CCalPrimaryGeneratorAction.cc
References G4cerr, G4cout, G4endl, phiSteps, and verboseLevel.
Referenced by CCalPrimaryGeneratorAction(), and CCalPrimaryGeneratorMessenger::SetNewValue().
void CCalPrimaryGeneratorAction::SetVerboseLevel (G4int val)
Definition at line 166 of file CCalPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 166 of file CCalPrimaryGeneratorAction.cc
References verboseLevel.
Referenced by CCalPrimaryGeneratorMessenger::SetNewValue().
Member Data Documentation
G4double CCalPrimaryGeneratorAction::energyMax private
Definition at line 104 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 104 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), and SetMaximumEnergy().
G4double CCalPrimaryGeneratorAction::energyMin private
Definition at line 104 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 104 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), and SetMinimumEnergy().
G4double CCalPrimaryGeneratorAction::etaMax private
Definition at line 105 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 105 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), and SetMaximumEta().
G4double CCalPrimaryGeneratorAction::etaMin private
Definition at line 105 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 105 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), and SetMinimumEta().
G4int CCalPrimaryGeneratorAction::etaSteps private
Definition at line 107 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 107 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), and SetStepsEta().
G4double CCalPrimaryGeneratorAction::etaValue private
Definition at line 110 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 110 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
generatorInputType CCalPrimaryGeneratorAction::generatorInput private
Definition at line 95 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 95 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), SetRandom(), and SetScan().
CCalPrimaryGeneratorMessenger* CCalPrimaryGeneratorAction::gunMessenger private
Definition at line 93 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 93 of file CCalPrimaryGeneratorAction.hh
Referenced by CCalPrimaryGeneratorAction(), and ~CCalPrimaryGeneratorAction().
G4int CCalPrimaryGeneratorAction::isInitialized private
Definition at line 109 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 109 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and initialize().
G4int CCalPrimaryGeneratorAction::n_particle private
Definition at line 98 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 98 of file CCalPrimaryGeneratorAction.hh
Referenced by CCalPrimaryGeneratorAction().
G4ThreeVector CCalPrimaryGeneratorAction::particleDir private
Definition at line 102 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 102 of file CCalPrimaryGeneratorAction.hh
Referenced by CCalPrimaryGeneratorAction(), and GeneratePrimaries().
G4double CCalPrimaryGeneratorAction::particleEnergy private
Definition at line 100 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 100 of file CCalPrimaryGeneratorAction.hh
Referenced by CCalPrimaryGeneratorAction(), and GeneratePrimaries().
G4ParticleGun* CCalPrimaryGeneratorAction::particleGun private
Definition at line 94 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 94 of file CCalPrimaryGeneratorAction.hh
Referenced by CCalPrimaryGeneratorAction(), GeneratePrimaries(), GetParticleEnergy(), GetParticlePosition(), print(), SetGunPosition(), and ~CCalPrimaryGeneratorAction().
G4String CCalPrimaryGeneratorAction::particleName private
Definition at line 99 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 99 of file CCalPrimaryGeneratorAction.hh
Referenced by CCalPrimaryGeneratorAction().
G4ThreeVector CCalPrimaryGeneratorAction::particlePosition private
Definition at line 101 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 101 of file CCalPrimaryGeneratorAction.hh
Referenced by CCalPrimaryGeneratorAction().
G4double CCalPrimaryGeneratorAction::phiMax private
Definition at line 106 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 106 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), and SetMaximumPhi().
G4double CCalPrimaryGeneratorAction::phiMin private
Definition at line 106 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 106 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), and SetMinimumPhi().
G4int CCalPrimaryGeneratorAction::phiSteps private
Definition at line 107 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 107 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), and SetStepsPhi().
G4double CCalPrimaryGeneratorAction::phiValue private
Definition at line 110 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 110 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries().
G4int CCalPrimaryGeneratorAction::scanSteps private
Definition at line 111 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 111 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), and SetScan().
G4int CCalPrimaryGeneratorAction::verboseLevel private
Definition at line 97 of file CCalPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 97 of file CCalPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), print(), SetMaximumEnergy(), SetMaximumEta(), SetMaximumPhi(), SetMinimumEnergy(), SetMinimumEta(), SetMinimumPhi(), SetStepsEta(), SetStepsPhi(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalPrimaryGeneratorAction.cc