ECCE @ EIC Software: G4HadronXSDataTable Class Reference
G4HadronXSDataTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4HadronXSDataTable.hh>
Public Member Functions
G4HadronXSDataTable ()
~G4HadronXSDataTable ()
void Initialise (G4DynamicParticle *, G4CrossSectionDataStore *, G4int bins, G4double emin, G4double emax, G4bool spline)
const G4PhysicsVector * HasData (size_t idx) const
G4double GetCrossSection (G4double e, size_t idx) const
const G4Element * SelectRandomAtom (G4double e, size_t idx) const
void Dump ()
Private Member Functions
G4HadronXSDataTable & operator= (const G4HadronXSDataTable &right)=delete
G4HadronXSDataTable (const G4HadronXSDataTable &)=delete
Private Attributes
std::vector< G4PhysicsVector * > xsData
std::vector
< G4HadElementSelector * > elmSelectors
size_t nMaterials
Detailed Description
Definition at line 95 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 95 of file G4HadronXSDataTable.hh
Constructor & Destructor Documentation
G4HadronXSDataTable::G4HadronXSDataTable () explicit
Definition at line 104 of file G4HadronXSDataTable.cc.
View newest version in sPHENIX GitHub at line 104 of file G4HadronXSDataTable.cc
G4HadronXSDataTable::~G4HadronXSDataTable ()
Definition at line 149 of file G4HadronXSDataTable.cc.
View newest version in sPHENIX GitHub at line 149 of file G4HadronXSDataTable.cc
References elmSelectors, nMaterials, and xsData.
G4HadronXSDataTable::G4HadronXSDataTable (const G4HadronXSDataTable &) private delete
Member Function Documentation
void G4HadronXSDataTable::Dump ()
Definition at line 159 of file G4HadronXSDataTable.cc.
View newest version in sPHENIX GitHub at line 159 of file G4HadronXSDataTable.cc
G4double G4HadronXSDataTable::GetCrossSection (G4double e, size_t idx) const inline
Definition at line 113 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 113 of file G4HadronXSDataTable.hh
References incremental_prev_tag::idx, and xsData.
const G4PhysicsVector* G4HadronXSDataTable::HasData (size_t idx) const inline
Definition at line 108 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 108 of file G4HadronXSDataTable.hh
References incremental_prev_tag::idx, and xsData.
void G4HadronXSDataTable::Initialise (G4DynamicParticle * dp, G4CrossSectionDataStore * xs, G4int bins, G4double emin, G4double emax, G4bool spline)
Definition at line 109 of file G4HadronXSDataTable.cc.
View newest version in sPHENIX GitHub at line 109 of file G4HadronXSDataTable.cc
References G4CrossSectionDataStore::ComputeCrossSection(), e, elmSelectors, G4PhysicsVector::Energy(), G4Material::GetMaterialTable(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), mat, max, nMaterials, G4InuclParticleNames::nn, G4PhysicsVector::PutValue(), G4DynamicParticle::SetKineticEnergy(), G4PhysicsVector::SetSpline(), v, and xsData.
G4HadronXSDataTable& G4HadronXSDataTable::operator= (const G4HadronXSDataTable & right) private delete
const G4Element* G4HadronXSDataTable::SelectRandomAtom (G4double e, size_t idx) const inline
Definition at line 118 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 118 of file G4HadronXSDataTable.hh
References elmSelectors, and incremental_prev_tag::idx.
Member Data Documentation
std::vector<G4HadElementSelector*> G4HadronXSDataTable::elmSelectors private
Definition at line 133 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 133 of file G4HadronXSDataTable.hh
Referenced by Initialise(), SelectRandomAtom(), and ~G4HadronXSDataTable().
size_t G4HadronXSDataTable::nMaterials private
Definition at line 135 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 135 of file G4HadronXSDataTable.hh
Referenced by Initialise(), and ~G4HadronXSDataTable().
std::vector<G4PhysicsVector*> G4HadronXSDataTable::xsData private
Definition at line 132 of file G4HadronXSDataTable.hh.
View newest version in sPHENIX GitHub at line 132 of file G4HadronXSDataTable.hh
Referenced by GetCrossSection(), HasData(), Initialise(), and ~G4HadronXSDataTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4HadronXSDataTable.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4HadronXSDataTable.cc