ECCE @ EIC Software: G4ArrowModel Class Reference
G4ArrowModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ArrowModel.hh>
Public Member Functions
G4ArrowModel (G4double x1, G4double y1, G4double z1, G4double x2, G4double y2, G4double z2, G4double width, const G4Colour &colour, const G4String &description="", G4int lineSegmentsPerCircle=6)
virtual ~G4ArrowModel ()
virtual void DescribeYourselfTo (G4VGraphicsScene &)
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
virtual G4String GetCurrentDescription () const
virtual G4String GetCurrentTag () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
virtual G4bool Validate (G4bool warn=true)
Private Member Functions
G4ArrowModel (const G4ArrowModel &)
G4ArrowModel & operator= (const G4ArrowModel &)
Private Attributes
G4Polyhedron * fpShaftPolyhedron
G4Polyhedron * fpHeadPolyhedron
Additional Inherited Members
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Detailed Description
Definition at line 47 of file G4ArrowModel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ArrowModel.hh
Constructor & Destructor Documentation
G4ArrowModel::G4ArrowModel (G4double x1, G4double y1, G4double z1, G4double x2, G4double y2, G4double z2, G4double width, const G4Colour & colour, const G4String & description = "", G4int lineSegmentsPerCircle = 6)
Definition at line 52 of file G4ArrowModel.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ArrowModel.cc
References G4Tet::CreatePolyhedron(), G4Tubs::CreatePolyhedron(), G4GeometryTolerance::GetInstance(), HepPolyhedron::GetNumberOfRotationSteps(), G4GeometryTolerance::GetRadialTolerance(), max, min, phi, HepGeom::BasicVector3D< T >::phi(), G4VisAttributes::SetColour(), G4VisAttributes::SetForceSolid(), HepPolyhedron::SetNumberOfRotationSteps(), theta(), HepGeom::BasicVector3D< T >::theta(), HepPolyhedron::Transform(), twopi, and HepGeom::BasicVector3D< T >::unit().
G4ArrowModel::~G4ArrowModel () virtual
Definition at line 45 of file G4ArrowModel.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ArrowModel.cc
References fpHeadPolyhedron, and fpShaftPolyhedron.
G4ArrowModel::G4ArrowModel (const G4ArrowModel &) private
Member Function Documentation
void G4ArrowModel::DescribeYourselfTo (G4VGraphicsScene & sceneHandler) virtual
Implements G4VModel.
Definition at line 126 of file G4ArrowModel.cc.
View newest version in sPHENIX GitHub at line 126 of file G4ArrowModel.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives(), G4VGraphicsScene::EndPrimitives(), fpHeadPolyhedron, and fpShaftPolyhedron.
Referenced by G4VFieldModel::DescribeYourselfTo().
G4ArrowModel& G4ArrowModel::operator= (const G4ArrowModel &) private
Member Data Documentation
G4Polyhedron* G4ArrowModel::fpHeadPolyhedron private
Definition at line 68 of file G4ArrowModel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ArrowModel.hh
Referenced by DescribeYourselfTo(), and ~G4ArrowModel().
G4Polyhedron* G4ArrowModel::fpShaftPolyhedron private
Definition at line 67 of file G4ArrowModel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4ArrowModel.hh
Referenced by DescribeYourselfTo(), and ~G4ArrowModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4ArrowModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4ArrowModel.cc