ECCE @ EIC Software: PurgMagPhysicsList Class Reference
PurgMagPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/purging_magnet/include/PurgMagPhysicsList.hh>
Public Member Functions
PurgMagPhysicsList ()
~PurgMagPhysicsList ()
void SetGammaCut (G4double)
void SetElectronCut (G4double)
void SetPositronCut (G4double)
void SetProtonCut (G4double)
void SetGammaLowLimit (G4double)
void SetElectronLowLimit (G4double)
void SetPositronLowLimit (G4double)
void SetProtonLowLimit (G4double)
void SetGEPLowLimit (G4double)
void SetGELowLimit (G4double)
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
virtual void TerminateWorker ()
Protected Member Functions
void ConstructParticle ()
void ConstructProcess ()
void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructBarions ()
void ConstructGeneral ()
void ConstructEM ()
Protected Member Functions inherited from G4VUserPhysicsList
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Private Attributes
G4double cutForGamma
G4double cutForElectron
G4double cutForPositron
G4double cutForProton
Additional Inherited Members
Static Public Member Functions inherited from G4VUserPhysicsList
static const G4VUPLManager & GetSubInstanceManager ()
Protected Attributes inherited from G4VUserPhysicsList
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Static Protected Attributes inherited from G4VUserPhysicsList
static G4RUN_DLL G4VUPLManager subInstanceManager
Detailed Description
Definition at line 55 of file PurgMagPhysicsList.hh.
View newest version in sPHENIX GitHub at line 55 of file PurgMagPhysicsList.hh
Constructor & Destructor Documentation
PurgMagPhysicsList::PurgMagPhysicsList ()
Definition at line 53 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 53 of file PurgMagPhysicsList.cc
References cutForElectron, cutForGamma, cutForPositron, cutForProton, G4VUserPhysicsList::defaultCutValue, micrometer, and G4VUserPhysicsList::SetVerboseLevel().
PurgMagPhysicsList::~PurgMagPhysicsList ()
Definition at line 66 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 66 of file PurgMagPhysicsList.cc
Member Function Documentation
void PurgMagPhysicsList::ConstructBarions () protected
Definition at line 105 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 105 of file PurgMagPhysicsList.cc
References G4AntiProton::AntiProtonDefinition(), and G4Proton::ProtonDefinition().
Referenced by ConstructParticle().
void PurgMagPhysicsList::ConstructBosons () protected
Definition at line 85 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 85 of file PurgMagPhysicsList.cc
References G4Gamma::GammaDefinition(), and G4OpticalPhoton::OpticalPhotonDefinition().
Referenced by ConstructParticle().
void PurgMagPhysicsList::ConstructEM () protected
Definition at line 136 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 136 of file PurgMagPhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetProcessManager(), and particle.
Referenced by ConstructProcess().
void PurgMagPhysicsList::ConstructGeneral () protected
Definition at line 179 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 179 of file PurgMagPhysicsList.cc
Referenced by ConstructProcess().
void PurgMagPhysicsList::ConstructLeptons () protected
Definition at line 96 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 96 of file PurgMagPhysicsList.cc
References G4Electron::ElectronDefinition(), and G4Positron::PositronDefinition().
Referenced by ConstructParticle().
void PurgMagPhysicsList::ConstructParticle (void) protected virtual
Implements G4VUserPhysicsList.
Definition at line 71 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 71 of file PurgMagPhysicsList.cc
References ConstructBarions(), ConstructBosons(), and ConstructLeptons().
void PurgMagPhysicsList::ConstructProcess (void) protected virtual
Implements G4VUserPhysicsList.
Definition at line 114 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 114 of file PurgMagPhysicsList.cc
References G4VUserPhysicsList::AddTransportation(), ConstructEM(), and ConstructGeneral().
void PurgMagPhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 184 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 184 of file PurgMagPhysicsList.cc
References cutForElectron, cutForGamma, cutForPositron, cutForProton, G4VUserPhysicsList::defaultCutValue, G4VUserPhysicsList::DumpCutValuesTable(), G4BestUnit, G4cout, G4endl, G4VUserPhysicsList::SetCutValue(), and G4VUserPhysicsList::verboseLevel.
void PurgMagPhysicsList::SetElectronCut (G4double val)
Definition at line 305 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 305 of file PurgMagPhysicsList.cc
References cutForElectron.
void PurgMagPhysicsList::SetElectronLowLimit (G4double lowcut)
Definition at line 222 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 222 of file PurgMagPhysicsList.cc
References G4cout, G4endl, MeV, SetGELowLimit(), and G4VUserPhysicsList::verboseLevel.
void PurgMagPhysicsList::SetGammaCut (G4double val)
Definition at line 297 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 297 of file PurgMagPhysicsList.cc
References cutForGamma, and G4VUserPhysicsList::ResetCuts().
void PurgMagPhysicsList::SetGammaLowLimit (G4double lowcut)
Definition at line 209 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 209 of file PurgMagPhysicsList.cc
References G4cout, G4endl, MeV, SetGELowLimit(), and G4VUserPhysicsList::verboseLevel.
void PurgMagPhysicsList::SetGELowLimit (G4double lowcut)
Definition at line 288 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 288 of file PurgMagPhysicsList.cc
References e5, G4cout, G4endl, G4ProductionCutsTable::GetProductionCutsTable(), MeV, G4ProductionCutsTable::SetEnergyRange(), and G4VUserPhysicsList::verboseLevel.
Referenced by SetElectronLowLimit(), SetGammaLowLimit(), and SetGEPLowLimit().
void PurgMagPhysicsList::SetGEPLowLimit (G4double lowcut)
Definition at line 271 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 271 of file PurgMagPhysicsList.cc
References G4cerr, G4cout, G4endl, MeV, SetGELowLimit(), and G4VUserPhysicsList::verboseLevel.
void PurgMagPhysicsList::SetPositronCut (G4double val)
Definition at line 313 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 313 of file PurgMagPhysicsList.cc
References cutForPositron.
void PurgMagPhysicsList::SetPositronLowLimit (G4double lowcut)
Definition at line 236 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 236 of file PurgMagPhysicsList.cc
References FatalException, G4cerr, G4cout, G4endl, G4Exception(), MeV, and G4VUserPhysicsList::verboseLevel.
void PurgMagPhysicsList::SetProtonCut (G4double val)
Definition at line 321 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 321 of file PurgMagPhysicsList.cc
References cutForProton.
void PurgMagPhysicsList::SetProtonLowLimit (G4double lowcut)
Definition at line 253 of file PurgMagPhysicsList.cc.
View newest version in sPHENIX GitHub at line 253 of file PurgMagPhysicsList.cc
References FatalException, G4cerr, G4cout, G4endl, G4Exception(), MeV, and G4VUserPhysicsList::verboseLevel.
Member Data Documentation
G4double PurgMagPhysicsList::cutForElectron private
Definition at line 86 of file PurgMagPhysicsList.hh.
View newest version in sPHENIX GitHub at line 86 of file PurgMagPhysicsList.hh
Referenced by PurgMagPhysicsList(), SetCuts(), and SetElectronCut().
G4double PurgMagPhysicsList::cutForGamma private
Definition at line 85 of file PurgMagPhysicsList.hh.
View newest version in sPHENIX GitHub at line 85 of file PurgMagPhysicsList.hh
Referenced by PurgMagPhysicsList(), SetCuts(), and SetGammaCut().
G4double PurgMagPhysicsList::cutForPositron private
Definition at line 87 of file PurgMagPhysicsList.hh.
View newest version in sPHENIX GitHub at line 87 of file PurgMagPhysicsList.hh
Referenced by PurgMagPhysicsList(), SetCuts(), and SetPositronCut().
G4double PurgMagPhysicsList::cutForProton private
Definition at line 88 of file PurgMagPhysicsList.hh.
View newest version in sPHENIX GitHub at line 88 of file PurgMagPhysicsList.hh
Referenced by PurgMagPhysicsList(), SetCuts(), and SetProtonCut().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/purging_magnet/include/PurgMagPhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/purging_magnet/src/PurgMagPhysicsList.cc