ECCE @ EIC Software: G4AdjointHe3 Class Reference
G4AdjointHe3 Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/adjoint/include/G4AdjointHe3.hh>
Static Public Member Functions
static G4AdjointHe3 * Definition ()
static G4AdjointHe3 * He3Definition ()
static G4AdjointHe3 * He3 ()
Private Member Functions
G4AdjointHe3 ()
~G4AdjointHe3 ()
Static Private Attributes
static G4AdjointHe3 * theInstance = 0
Additional Inherited Members
Public Member Functions inherited from G4AdjointIons
G4AdjointIons (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived, const G4String &subType="", G4int anti_encoding=0, G4double excitation=0.0)
virtual ~G4AdjointIons ()
G4AdjointIons * IonsDefinition ()
G4AdjointIons * Ions ()
G4double GetExcitationEnergy () const
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4AdjointIons
G4AdjointIons ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 52 of file G4AdjointHe3.hh.
View newest version in sPHENIX GitHub at line 52 of file G4AdjointHe3.hh
Constructor & Destructor Documentation
G4AdjointHe3::G4AdjointHe3 () inline private
Definition at line 56 of file G4AdjointHe3.hh.
View newest version in sPHENIX GitHub at line 56 of file G4AdjointHe3.hh
G4AdjointHe3::~G4AdjointHe3 () inline private
Definition at line 57 of file G4AdjointHe3.hh.
View newest version in sPHENIX GitHub at line 57 of file G4AdjointHe3.hh
Member Function Documentation
G4AdjointHe3 * G4AdjointHe3::Definition () static
Definition at line 38 of file G4AdjointHe3.cc.
View newest version in sPHENIX GitHub at line 38 of file G4AdjointHe3.cc
References source.hepunit::c_squared, eplus, G4ParticleTable::FindParticle(), G4AdjointIons::G4AdjointIons(), G4ParticleTable::GetParticleTable(), GeV, source.hepunit::hbar_Planck, MeV, source.hepunit::proton_mass_c2, G4ParticleDefinition::SetAntiPDGEncoding(), G4ParticleDefinition::SetPDGMagneticMoment(), and theInstance.
Referenced by He3(), and He3Definition().
G4AdjointHe3 * G4AdjointHe3::He3 () static
Definition at line 85 of file G4AdjointHe3.cc.
View newest version in sPHENIX GitHub at line 85 of file G4AdjointHe3.cc
References Definition().
G4AdjointHe3 * G4AdjointHe3::He3Definition () static
Definition at line 80 of file G4AdjointHe3.cc.
View newest version in sPHENIX GitHub at line 80 of file G4AdjointHe3.cc
References Definition().
Member Data Documentation
G4AdjointHe3 * G4AdjointHe3::theInstance = 0 static private
Definition at line 55 of file G4AdjointHe3.hh.
View newest version in sPHENIX GitHub at line 55 of file G4AdjointHe3.hh
Referenced by Definition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/adjoint/include/G4AdjointHe3.hh
geant4/tree/geant4-10.6-release/source/particles/adjoint/src/G4AdjointHe3.cc