ECCE @ EIC Software: macros/blob/master/common/G4_DIRC.C File Reference
G4_DIRC.C File Reference
Setup the gas DIRC detector full sim.
#include <GlobalVariables.C>
#include <g4eicdirc/G4EicDircSubsystem.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <eccefastpidreco/ECCEFastPIDReco.h>
#include <eccefastpidreco/ECCEhpDIRCFastPIDMap.h>
#include <g4main/PHG4Reco.h>
Namespaces
namespace Enable
Macros
#define MACRO_G4DIRC_C
Functions
void DIRCInit ()
void DIRCSetup (PHG4Reco *g4Reco)
void DIRCReco ()
Variables
bool Enable::DIRC = false
bool Enable::DIRC_RECO = false
bool Enable::DIRC_OVERLAPCHECK = false
int Enable::DIRC_VERBOSITY = 0
double Enable::DIRC_SCALE = 10
bool Enable::DIRC_DISABLE_PHOTON_SIMULATION = true
Detailed Description
Setup the gas DIRC detector full sim.
Author
Cameron Dean cdean.nosp@m.@bnl.nosp@m..gov
Version
Revision:
0.1
Date
Date:
2021/08/17
Definition in file G4_DIRC.C.
Macro Definition Documentation
#define MACRO_G4DIRC_C
Definition at line 9 of file G4_DIRC.C.
View newest version in sPHENIX GitHub at line 9 of file G4_DIRC.C
Function Documentation
void DIRCInit ()
Definition at line 36 of file G4_DIRC.C.
View newest version in sPHENIX GitHub at line 36 of file G4_DIRC.C
References max, BlackHoleGeometry::max_radius, and BlackHoleGeometry::max_z.
Referenced by G4Init().
void DIRCReco ()
Definition at line 87 of file G4_DIRC.C.
View newest version in sPHENIX GitHub at line 87 of file G4_DIRC.C
References EICPIDDefs::DIRC, Enable::DIRC_VERBOSITY, Fun4AllServer::instance(), max, ECCEhpDIRCFastPIDMap::ReadMap(), Fun4AllServer::registerSubsystem(), ECCEFastPIDReco::setMatchG4Hit(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_ECCEModular(), Fun4All_G4_EICDetector(), and Fun4All_G4_EICDetector_AnaTutorial().
void DIRCSetup (PHG4Reco * g4Reco)
Definition at line 42 of file G4_DIRC.C.
View newest version in sPHENIX GitHub at line 42 of file G4_DIRC.C
References Enable::DIRC_DISABLE_PHOTON_SIMULATION, Enable::DIRC_OVERLAPCHECK, Enable::DIRC_SCALE, Enable::DIRC_VERBOSITY, TRACKING::FastKalmanFilter(), max, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), TRACKING::ProjectionNames, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by G4Setup().