ECCE @ EIC Software: boost::python::detail::proxy_group< Proxy > Class Template Reference
boost::python::detail::proxy_group< Proxy > Class Template Reference
#include <geant4/tree/geant4-10.6-release/environments/g4py/source/boost/detail/indexing_suite_detail.hpp>
Public Types
typedef std::vector< PyObject * >
::const_iterator const_iterator
typedef std::vector< PyObject * >
::iterator iterator
typedef Proxy::index_type index_type
typedef Proxy::policies_type policies_type
Public Member Functions
iterator first_proxy (index_type i)
void remove (Proxy &proxy)
void add (PyObject *prox)
void erase (index_type i, mpl::false_)
void erase (index_type i, mpl::true_)
void erase (index_type from, index_type to)
void replace (index_type from, index_type to, typename std::vector< PyObject * >::size_type len)
PyObject * find (index_type i)
std::vector< PyObject * >
::size_type size () const
Private Member Functions
void check_invariant () const
Private Attributes
std::vector< PyObject * > proxies
Detailed Description
template<class Proxy>
class boost::python::detail::proxy_group< Proxy >
Definition at line 54 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 54 of file indexing_suite_detail.hpp
Member Typedef Documentation
template<class Proxy > typedef std::vector<PyObject*>::const_iterator boost::python::detail::proxy_group< Proxy >::const_iterator
Definition at line 58 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 58 of file indexing_suite_detail.hpp
template<class Proxy > typedef Proxy::index_type boost::python::detail::proxy_group< Proxy >::index_type
Definition at line 60 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 60 of file indexing_suite_detail.hpp
template<class Proxy > typedef std::vector<PyObject*>::iterator boost::python::detail::proxy_group< Proxy >::iterator
Definition at line 59 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 59 of file indexing_suite_detail.hpp
template<class Proxy > typedef Proxy::policies_type boost::python::detail::proxy_group< Proxy >::policies_type
Definition at line 61 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 61 of file indexing_suite_detail.hpp
Member Function Documentation
template<class Proxy > void boost::python::detail::proxy_group< Proxy >::add (PyObject * prox) inline
Definition at line 89 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 89 of file indexing_suite_detail.hpp
References BOOST_PYTHON_INDEXING_CHECK_INVARIANT, boost::python::detail::proxy_group< Proxy >::first_proxy(), PHG4CellDefs::MVTXBinning::get_index(), and boost::python::detail::proxy_group< Proxy >::proxies.
template<class Proxy > void boost::python::detail::proxy_group< Proxy >::check_invariant () const inline private
Definition at line 215 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 215 of file indexing_suite_detail.hpp
References PHG4CellDefs::MVTXBinning::get_index(), and boost::python::detail::proxy_group< Proxy >::proxies.
template<class Proxy > void boost::python::detail::proxy_group< Proxy >::erase (index_type i, mpl::false_) inline
Definition at line 99 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 99 of file indexing_suite_detail.hpp
References BOOST_PYTHON_INDEXING_CHECK_INVARIANT, and boost::python::detail::proxy_group< Proxy >::replace().
template<class Proxy > void boost::python::detail::proxy_group< Proxy >::erase (index_type i, mpl::true_) inline
Definition at line 108 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 108 of file indexing_suite_detail.hpp
References BOOST_PYTHON_INDEXING_CHECK_INVARIANT, boost::python::detail::proxy_group< Proxy >::first_proxy(), and boost::python::detail::proxy_group< Proxy >::proxies.
template<class Proxy > void boost::python::detail::proxy_group< Proxy >::erase (index_type from, index_type to) inline
Definition at line 126 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 126 of file indexing_suite_detail.hpp
References BOOST_PYTHON_INDEXING_CHECK_INVARIANT, and boost::python::detail::proxy_group< Proxy >::replace().
template<class Proxy > PyObject* boost::python::detail::proxy_group< Proxy >::find (index_type i) inline
Definition at line 186 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 186 of file indexing_suite_detail.hpp
References BOOST_PYTHON_INDEXING_CHECK_INVARIANT, boost::python::detail::proxy_group< Proxy >::first_proxy(), PHG4CellDefs::MVTXBinning::get_index(), and boost::python::detail::proxy_group< Proxy >::proxies.
template<class Proxy > iterator boost::python::detail::proxy_group< Proxy >::first_proxy (index_type i) inline
Definition at line 64 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 64 of file indexing_suite_detail.hpp
References boost::python::detail::proxy_group< Proxy >::proxies.
Referenced by boost::python::detail::proxy_group< Proxy >::add(), boost::python::detail::proxy_group< Proxy >::erase(), boost::python::detail::proxy_group< Proxy >::find(), boost::python::detail::proxy_group< Proxy >::remove(), and boost::python::detail::proxy_group< Proxy >::replace().
template<class Proxy > void boost::python::detail::proxy_group< Proxy >::remove (Proxy & proxy) inline
Definition at line 73 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 73 of file indexing_suite_detail.hpp
References BOOST_PYTHON_INDEXING_CHECK_INVARIANT, boost::python::detail::proxy_group< Proxy >::first_proxy(), and boost::python::detail::proxy_group< Proxy >::proxies.
template<class Proxy > void boost::python::detail::proxy_group< Proxy >::replace (index_type from, index_type to, typename std::vector< PyObject * >::size_type len) inline
Definition at line 137 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 137 of file indexing_suite_detail.hpp
References BOOST_PYTHON_INDEXING_CHECK_INVARIANT, boost::python::detail::proxy_group< Proxy >::first_proxy(), PHG4CellDefs::MVTXBinning::get_index(), left, offset, boost::python::detail::proxy_group< Proxy >::proxies, and right.
Referenced by boost::python::detail::proxy_group< Proxy >::erase().
template<class Proxy > std::vector<PyObject*>::size_type boost::python::detail::proxy_group< Proxy >::size (void) const inline
Definition at line 204 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 204 of file indexing_suite_detail.hpp
References BOOST_PYTHON_INDEXING_CHECK_INVARIANT, and boost::python::detail::proxy_group< Proxy >::proxies.
Member Data Documentation
template<class Proxy > std::vector<PyObject*> boost::python::detail::proxy_group< Proxy >::proxies private
Definition at line 240 of file indexing_suite_detail.hpp.
View newest version in sPHENIX GitHub at line 240 of file indexing_suite_detail.hpp
Referenced by boost::python::detail::proxy_group< Proxy >::add(), boost::python::detail::proxy_group< Proxy >::check_invariant(), boost::python::detail::proxy_group< Proxy >::erase(), boost::python::detail::proxy_group< Proxy >::find(), boost::python::detail::proxy_group< Proxy >::first_proxy(), boost::python::detail::proxy_group< Proxy >::remove(), boost::python::detail::proxy_group< Proxy >::replace(), and boost::python::detail::proxy_group< Proxy >::size().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/environments/g4py/source/boost/detail/indexing_suite_detail.hpp