ECCE @ EIC Software: Par01CalorimeterSD Class Reference
Par01CalorimeterSD Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01CalorimeterSD.hh>
Public Member Functions
Par01CalorimeterSD (G4String name, G4int nCells, G4String colName)
~Par01CalorimeterSD ()
virtual void Initialize (G4HCofThisEvent *HCE)
virtual G4bool ProcessHits (G4Step *aStep, G4TouchableHistory *ROhist)
virtual void EndOfEvent (G4HCofThisEvent *HCE)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
Public Member Functions inherited from G4VSensitiveDetector
G4VSensitiveDetector (G4String name)
G4VSensitiveDetector (const G4VSensitiveDetector &right)
virtual ~G4VSensitiveDetector ()
G4VSensitiveDetector & operator= (const G4VSensitiveDetector &right)
G4bool operator== (const G4VSensitiveDetector &right) const
G4bool operator!= (const G4VSensitiveDetector &right) const
G4bool Hit (G4Step *aStep)
void SetROgeometry (G4VReadOutGeometry *value)
void SetFilter (G4VSDFilter *value)
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int id) const
void SetVerboseLevel (G4int vl)
void Activate (G4bool activeFlag)
G4bool isActive () const
G4String GetName () const
G4String GetPathName () const
G4String GetFullPathName () const
G4VReadOutGeometry * GetROgeometry () const
G4VSDFilter * GetFilter () const
virtual G4VSensitiveDetector * Clone () const
Private Attributes
Par01CalorimeterHitsCollection * fCalCollection
int * fCellID
int fNumberOfCells
int fHCID
Additional Inherited Members
Protected Member Functions inherited from G4VSensitiveDetector
virtual G4int GetCollectionID (G4int i)
Protected Attributes inherited from G4VSensitiveDetector
G4CollectionNameVector collectionName
G4String SensitiveDetectorName
G4String thePathName
G4String fullPathName
G4int verboseLevel
G4bool active
G4VReadOutGeometry * ROgeometry
G4VSDFilter * filter
Detailed Description
Definition at line 40 of file Par01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 40 of file Par01CalorimeterSD.hh
Constructor & Destructor Documentation
Par01CalorimeterSD::Par01CalorimeterSD (G4String name, G4int nCells, G4String colName)
Definition at line 44 of file Par01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 44 of file Par01CalorimeterSD.cc
References G4VSensitiveDetector::collectionName, fCellID, fNumberOfCells, and G4CollectionNameVector::insert().
Par01CalorimeterSD::~Par01CalorimeterSD ()
Definition at line 58 of file Par01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 58 of file Par01CalorimeterSD.cc
References fCellID.
Member Function Documentation
void Par01CalorimeterSD::clear (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 121 of file Par01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 121 of file Par01CalorimeterSD.cc
void Par01CalorimeterSD::DrawAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 127 of file Par01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 127 of file Par01CalorimeterSD.cc
void Par01CalorimeterSD::EndOfEvent (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 112 of file Par01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 112 of file Par01CalorimeterSD.cc
References G4HCofThisEvent::AddHitsCollection(), G4VSensitiveDetector::collectionName, fCalCollection, fHCID, G4SDManager::GetCollectionID(), and G4SDManager::GetSDMpointer().
void Par01CalorimeterSD::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 65 of file Par01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 65 of file Par01CalorimeterSD.cc
References G4VSensitiveDetector::collectionName, fCalCollection, fCellID, fNumberOfCells, and G4VSensitiveDetector::SensitiveDetectorName.
void Par01CalorimeterSD::PrintAll (void) virtual
Reimplemented from G4VSensitiveDetector.
Definition at line 133 of file Par01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 133 of file Par01CalorimeterSD.cc
G4bool Par01CalorimeterSD::ProcessHits (G4Step * aStep, G4TouchableHistory * ROhist) virtual
Implements G4VSensitiveDetector.
Definition at line 77 of file Par01CalorimeterSD.cc.
View newest version in sPHENIX GitHub at line 77 of file Par01CalorimeterSD.cc
References edep, fCalCollection, fCellID, G4cout, G4endl, G4TouchableHistory::GetHistory(), G4VPhysicalVolume::GetLogicalVolume(), G4Step::GetPreStepPoint(), G4TouchableHistory::GetReplicaNumber(), G4NavigationHistory::GetTopTransform(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchable(), G4TouchableHistory::GetVolume(), hist, G4THitsCollection< T >::insert(), G4AffineTransform::Invert(), G4AffineTransform::NetRotation(), G4AffineTransform::NetTranslation(), Par01CalorimeterHit::SetEdep(), Par01CalorimeterHit::SetPos(), Par01CalorimeterHit::SetRot(), and G4VSensitiveDetector::verboseLevel.
Member Data Documentation
Par01CalorimeterHitsCollection* Par01CalorimeterSD::fCalCollection private
Definition at line 55 of file Par01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 55 of file Par01CalorimeterSD.hh
Referenced by EndOfEvent(), Initialize(), and ProcessHits().
int* Par01CalorimeterSD::fCellID private
Definition at line 57 of file Par01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 57 of file Par01CalorimeterSD.hh
Referenced by Initialize(), Par01CalorimeterSD(), ProcessHits(), and ~Par01CalorimeterSD().
int Par01CalorimeterSD::fHCID private
Definition at line 59 of file Par01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 59 of file Par01CalorimeterSD.hh
Referenced by EndOfEvent().
int Par01CalorimeterSD::fNumberOfCells private
Definition at line 58 of file Par01CalorimeterSD.hh.
View newest version in sPHENIX GitHub at line 58 of file Par01CalorimeterSD.hh
Referenced by Initialize(), and Par01CalorimeterSD().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01CalorimeterSD.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/src/Par01CalorimeterSD.cc