ECCE @ EIC Software: G4ParticleGunMessenger Class Reference
G4ParticleGunMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4ParticleGunMessenger.hh>
Public Member Functions
G4ParticleGunMessenger (G4ParticleGun *fPtclGun)
~G4ParticleGunMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void IonCommand (G4String newValues)
void IonLevelCommand (G4String newValues)
Private Attributes
G4ParticleGun * fParticleGun
G4ParticleTable * particleTable
G4UIdirectory * gunDirectory
G4UIcmdWithoutParameter * listCmd
G4UIcmdWithAString * particleCmd
G4UIcmdWith3Vector * directionCmd
G4UIcmdWithADoubleAndUnit * energyCmd
G4UIcmdWithADoubleAndUnit * momAmpCmd
G4UIcmdWith3VectorAndUnit * momCmd
G4UIcmdWith3VectorAndUnit * positionCmd
G4UIcmdWithADoubleAndUnit * timeCmd
G4UIcmdWith3Vector * polCmd
G4UIcmdWithAnInteger * numberCmd
G4UIcommand * ionCmd
G4UIcommand * ionLvlCmd
G4bool fShootIon
G4int fAtomicNumber
G4int fAtomicMass
G4int fIonCharge
G4double fIonExciteEnergy
char fIonFloatingLevelBase
G4int fIonEnergyLevel
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 53 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleGunMessenger.hh
Constructor & Destructor Documentation
G4ParticleGunMessenger::G4ParticleGunMessenger (G4ParticleGun * fPtclGun)
Definition at line 46 of file G4ParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleGunMessenger.cc
References cm, directionCmd, energyCmd, fParticleGun, G4Geantino::Geantino(), G4ParticleDefinition::GetDecayTable(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), GeV, gunDirectory, ionCmd, ionLvlCmd, G4ParticleDefinition::IsShortLived(), listCmd, momAmpCmd, momCmd, ns, numberCmd, particleCmd, particleTable, polCmd, positionCmd, G4ParticleTableIterator< K, V >::reset(), G4UIcmdWithAString::SetCandidates(), G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWith3VectorAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIparameter::SetParameterCandidates(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWith3Vector::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), G4VPrimaryGenerator::SetParticleTime(), G4UIcommand::SetRange(), timeCmd, and G4ParticleTableIterator< K, V >::value().
G4ParticleGunMessenger::~G4ParticleGunMessenger ()
Definition at line 186 of file G4ParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 186 of file G4ParticleGunMessenger.cc
References directionCmd, energyCmd, gunDirectory, ionCmd, ionLvlCmd, listCmd, momAmpCmd, momCmd, numberCmd, particleCmd, polCmd, positionCmd, and timeCmd.
Member Function Documentation
G4String G4ParticleGunMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 263 of file G4ParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 263 of file G4ParticleGunMessenger.cc
References G4UIcommand::ConvertToString(), directionCmd, energyCmd, fAtomicMass, fAtomicNumber, fIonCharge, fParticleGun, fShootIon, G4cerr, G4endl, G4ParticleGun::GetNumberOfParticles(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), G4ParticleGun::GetParticleMomentum(), G4ParticleGun::GetParticleMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4ParticleGun::GetParticlePolarization(), G4VPrimaryGenerator::GetParticlePosition(), G4VPrimaryGenerator::GetParticleTime(), ionCmd, G4UImessenger::ItoS(), mom, momAmpCmd, momCmd, numberCmd, particleCmd, polCmd, positionCmd, and timeCmd.
void G4ParticleGunMessenger::IonCommand (G4String newValues) private
Definition at line 345 of file G4ParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 345 of file G4ParticleGunMessenger.cc
References G4UIcommand::CommandFailed(), eplus, fAtomicMass, fAtomicNumber, fIonCharge, fIonExciteEnergy, fIonFloatingLevelBase, fParticleGun, G4IonTable::GetIon(), G4IonTable::GetIonTable(), ionCmd, G4String::isNull(), keV, G4ParticleGun::SetParticleCharge(), G4ParticleGun::SetParticleDefinition(), G4UImessenger::StoD(), and G4UImessenger::StoI().
Referenced by SetNewValue().
void G4ParticleGunMessenger::IonLevelCommand (G4String newValues) private
Definition at line 314 of file G4ParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 314 of file G4ParticleGunMessenger.cc
References G4UIcommand::CommandFailed(), eplus, fAtomicMass, fAtomicNumber, fIonCharge, fIonEnergyLevel, fParticleGun, G4IonTable::GetIon(), G4IonTable::GetIonTable(), ionLvlCmd, G4String::isNull(), G4ParticleGun::SetParticleCharge(), G4ParticleGun::SetParticleDefinition(), and G4UImessenger::StoI().
Referenced by SetNewValue().
void G4ParticleGunMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 203 of file G4ParticleGunMessenger.cc.
View newest version in sPHENIX GitHub at line 203 of file G4ParticleGunMessenger.cc
References G4UIcommand::CommandFailed(), directionCmd, G4ParticleTable::DumpTable(), energyCmd, G4ParticleTable::FindParticle(), fParticleGun, fShootIon, G4Exception(), G4UIcmdWith3Vector::GetNew3VectorValue(), G4UIcmdWith3VectorAndUnit::GetNew3VectorValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), ionCmd, IonCommand(), IonLevelCommand(), ionLvlCmd, JustWarning, listCmd, momAmpCmd, momCmd, numberCmd, particleCmd, particleTable, polCmd, positionCmd, G4ParticleGun::SetNumberOfParticles(), G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentum(), G4ParticleGun::SetParticleMomentumDirection(), G4ParticleGun::SetParticlePolarization(), G4VPrimaryGenerator::SetParticlePosition(), G4VPrimaryGenerator::SetParticleTime(), and timeCmd.
Member Data Documentation
G4UIcmdWith3Vector* G4ParticleGunMessenger::directionCmd private
Definition at line 75 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcmdWithADoubleAndUnit* G4ParticleGunMessenger::energyCmd private
Definition at line 76 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
G4int G4ParticleGunMessenger::fAtomicMass private
Definition at line 90 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ParticleGunMessenger.hh
Referenced by GetCurrentValue(), IonCommand(), and IonLevelCommand().
G4int G4ParticleGunMessenger::fAtomicNumber private
Definition at line 89 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleGunMessenger.hh
Referenced by GetCurrentValue(), IonCommand(), and IonLevelCommand().
G4int G4ParticleGunMessenger::fIonCharge private
Definition at line 91 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleGunMessenger.hh
Referenced by GetCurrentValue(), IonCommand(), and IonLevelCommand().
G4int G4ParticleGunMessenger::fIonEnergyLevel private
Definition at line 94 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleGunMessenger.hh
Referenced by IonLevelCommand().
G4double G4ParticleGunMessenger::fIonExciteEnergy private
Definition at line 92 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleGunMessenger.hh
Referenced by IonCommand().
char G4ParticleGunMessenger::fIonFloatingLevelBase private
Definition at line 93 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleGunMessenger.hh
Referenced by IonCommand().
G4ParticleGun* G4ParticleGunMessenger::fParticleGun private
Definition at line 68 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), IonCommand(), IonLevelCommand(), and SetNewValue().
G4bool G4ParticleGunMessenger::fShootIon private
Definition at line 88 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleGunMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIdirectory* G4ParticleGunMessenger::gunDirectory private
Definition at line 72 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), and ~G4ParticleGunMessenger().
G4UIcommand* G4ParticleGunMessenger::ionCmd private
Definition at line 84 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), IonCommand(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcommand* G4ParticleGunMessenger::ionLvlCmd private
Definition at line 85 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), IonLevelCommand(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcmdWithoutParameter* G4ParticleGunMessenger::listCmd private
Definition at line 73 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcmdWithADoubleAndUnit* G4ParticleGunMessenger::momAmpCmd private
Definition at line 77 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcmdWith3VectorAndUnit* G4ParticleGunMessenger::momCmd private
Definition at line 78 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcmdWithAnInteger* G4ParticleGunMessenger::numberCmd private
Definition at line 82 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcmdWithAString* G4ParticleGunMessenger::particleCmd private
Definition at line 74 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
G4ParticleTable* G4ParticleGunMessenger::particleTable private
Definition at line 69 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), and SetNewValue().
G4UIcmdWith3Vector* G4ParticleGunMessenger::polCmd private
Definition at line 81 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcmdWith3VectorAndUnit* G4ParticleGunMessenger::positionCmd private
Definition at line 79 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
G4UIcmdWithADoubleAndUnit* G4ParticleGunMessenger::timeCmd private
Definition at line 80 of file G4ParticleGunMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleGunMessenger.hh
Referenced by G4ParticleGunMessenger(), GetCurrentValue(), SetNewValue(), and ~G4ParticleGunMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4ParticleGunMessenger.hh
geant4/tree/geant4-10.6-release/source/event/src/G4ParticleGunMessenger.cc