ECCE @ EIC Software: G4VLevelDensityParameter Class Reference
G4VLevelDensityParameter Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/include/G4VLevelDensityParameter.hh>
Public Member Functions
G4VLevelDensityParameter ()
virtual ~G4VLevelDensityParameter ()
virtual G4double LevelDensityParameter (G4int A, G4int Z, G4double U) const =0
Private Member Functions
G4VLevelDensityParameter (const G4VLevelDensityParameter &right)=delete
const G4VLevelDensityParameter & operator= (const G4VLevelDensityParameter &right)=delete
G4bool operator== (const G4VLevelDensityParameter &right) const =delete
G4bool operator!= (const G4VLevelDensityParameter &right) const =delete
Detailed Description
Definition at line 36 of file G4VLevelDensityParameter.hh.
View newest version in sPHENIX GitHub at line 36 of file G4VLevelDensityParameter.hh
Constructor & Destructor Documentation
G4VLevelDensityParameter::G4VLevelDensityParameter () inline explicit
Definition at line 40 of file G4VLevelDensityParameter.hh.
View newest version in sPHENIX GitHub at line 40 of file G4VLevelDensityParameter.hh
virtual G4VLevelDensityParameter::~G4VLevelDensityParameter () inline virtual
Definition at line 41 of file G4VLevelDensityParameter.hh.
View newest version in sPHENIX GitHub at line 41 of file G4VLevelDensityParameter.hh
G4VLevelDensityParameter::G4VLevelDensityParameter (const G4VLevelDensityParameter & right) private delete
Member Function Documentation
virtual G4double G4VLevelDensityParameter::LevelDensityParameter (G4int A, G4int Z, G4double U) const pure virtual
Implemented in G4FissionLevelDensityParameterINCLXX, G4EvaporationLevelDensityParameter, G4FissionLevelDensityParameter, and G4ConstantLevelDensityParameter.
Referenced by G4GEMProbability::CalcProbability(), G4FissionProbability::EmissionProbability(), and G4GEMChannel::SampleKineticEnergy().
G4bool G4VLevelDensityParameter::operator!= (const G4VLevelDensityParameter & right) const private delete
const G4VLevelDensityParameter& G4VLevelDensityParameter::operator= (const G4VLevelDensityParameter & right) private delete
G4bool G4VLevelDensityParameter::operator== (const G4VLevelDensityParameter & right) const private delete
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/util/include/G4VLevelDensityParameter.hh