ECCE @ EIC Software: G4FermiChannels Class Reference
G4FermiChannels Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiChannels.hh>
Public Member Functions
G4FermiChannels (size_t nmax, G4double ex, G4double gmass)
size_t GetNumberOfChannels () const
const std::vector< const
G4FermiPair * > & GetChannels () const
const G4FermiPair * GetPair (size_t idx) const
const G4FermiPair * SamplePair (G4double rand) const
void AddChannel (const G4FermiPair *)
std::vector< G4double > & GetProbabilities ()
G4double GetExcitation () const
G4double GetMass () const
Private Member Functions
const G4FermiChannels & operator= (const G4FermiChannels &)
G4FermiChannels (const G4FermiChannels &)
G4bool operator== (const G4FermiChannels &)
G4bool operator!= (const G4FermiChannels &)
Private Attributes
size_t nch
G4double excitation
G4double ground_mass
std::vector< const G4FermiPair * > fvect
std::vector< G4double > cum_prob
Detailed Description
Definition at line 39 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 39 of file G4FermiChannels.hh
Constructor & Destructor Documentation
G4FermiChannels::G4FermiChannels (size_t nmax, G4double ex, G4double gmass) inline explicit
Definition at line 43 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 43 of file G4FermiChannels.hh
References cum_prob, and fvect.
G4FermiChannels::G4FermiChannels (const G4FermiChannels &) inline private
Member Function Documentation
void G4FermiChannels::AddChannel (const G4FermiPair * ptr) inline
Definition at line 97 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 97 of file G4FermiChannels.hh
References cum_prob, fvect, and nch.
const std::vector< const G4FermiPair * > & G4FermiChannels::GetChannels () const inline
Definition at line 78 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FermiChannels.hh
References fvect.
Referenced by G4FermiFragmentsPoolVI::Initialise(), and G4FermiBreakUpVI::SampleDecay().
G4double G4FermiChannels::GetExcitation () const inline
Definition at line 109 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 109 of file G4FermiChannels.hh
References excitation.
Referenced by G4FermiBreakUpVI::SampleDecay().
G4double G4FermiChannels::GetMass () const inline
Definition at line 114 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 114 of file G4FermiChannels.hh
References excitation, and ground_mass.
size_t G4FermiChannels::GetNumberOfChannels () const inline
Definition at line 73 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 73 of file G4FermiChannels.hh
References nch.
Referenced by G4FermiFragmentsPoolVI::Initialise(), and G4FermiBreakUpVI::SampleDecay().
const G4FermiPair * G4FermiChannels::GetPair (size_t idx) const inline
Definition at line 83 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 83 of file G4FermiChannels.hh
References fvect, incremental_prev_tag::idx, and nch.
Referenced by G4FermiBreakUpVI::SampleDecay().
std::vector< G4double > & G4FermiChannels::GetProbabilities () inline
Definition at line 104 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 104 of file G4FermiChannels.hh
References cum_prob.
Referenced by G4FermiFragmentsPoolVI::Initialise().
G4bool G4FermiChannels::operator!= (const G4FermiChannels &) inline private
const G4FermiChannels& G4FermiChannels::operator= (const G4FermiChannels &) inline private
G4bool G4FermiChannels::operator== (const G4FermiChannels &) inline private
const G4FermiPair * G4FermiChannels::SamplePair (G4double rand) const inline
Definition at line 88 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 88 of file G4FermiChannels.hh
References cum_prob, fvect, and nch.
Referenced by G4FermiBreakUpVI::SampleDecay().
Member Data Documentation
std::vector<G4double> G4FermiChannels::cum_prob private
Definition at line 69 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 69 of file G4FermiChannels.hh
Referenced by AddChannel(), G4FermiChannels(), GetProbabilities(), and SamplePair().
G4double G4FermiChannels::excitation private
Definition at line 66 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 66 of file G4FermiChannels.hh
Referenced by GetExcitation(), and GetMass().
std::vector<const G4FermiPair*> G4FermiChannels::fvect private
Definition at line 68 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 68 of file G4FermiChannels.hh
Referenced by AddChannel(), G4FermiChannels(), GetChannels(), GetPair(), and SamplePair().
G4double G4FermiChannels::ground_mass private
Definition at line 67 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 67 of file G4FermiChannels.hh
Referenced by GetMass().
size_t G4FermiChannels::nch private
Definition at line 65 of file G4FermiChannels.hh.
View newest version in sPHENIX GitHub at line 65 of file G4FermiChannels.hh
Referenced by AddChannel(), GetNumberOfChannels(), GetPair(), and SamplePair().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiChannels.hh