ECCE @ EIC Software: G4MicroElecCrossSectionDataSet Class Reference
G4MicroElecCrossSectionDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4MicroElecCrossSectionDataSet.hh>
Public Member Functions
G4MicroElecCrossSectionDataSet (G4VDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn)
virtual ~G4MicroElecCrossSectionDataSet ()
virtual G4double FindValue (G4double e, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4VEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4VEMDataSet *dataSet)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual const G4DataVector & GetLogEnergies (G4int componentId) const
virtual const G4DataVector & GetLogData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *values, G4int componentId)
virtual void SetLogEnergiesData (G4DataVector *x, G4DataVector *values, G4DataVector *log_x, G4DataVector *log_values, G4int componentId)
virtual G4bool LoadData (const G4String &argFileName)
virtual G4bool LoadNonLogData (const G4String &argFileName)
virtual G4bool SaveData (const G4String &argFileName) const
virtual G4double RandomSelect (G4int) const
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Private Member Functions
G4String FullFileName (const G4String &argFileName) const
G4MicroElecCrossSectionDataSet ()
G4MicroElecCrossSectionDataSet (const G4MicroElecCrossSectionDataSet &copy)
G4MicroElecCrossSectionDataSet & operator= (const G4MicroElecCrossSectionDataSet &right)
G4double GetUnitEnergies () const
G4double GetUnitData () const
const G4VDataSetAlgorithm * GetAlgorithm () const
void CleanUpComponents (void)
Private Attributes
std::vector< G4VEMDataSet * > components
G4int z
G4VDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
Detailed Description
Definition at line 37 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 37 of file G4MicroElecCrossSectionDataSet.hh
Constructor & Destructor Documentation
G4MicroElecCrossSectionDataSet::G4MicroElecCrossSectionDataSet (G4VDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn)
Definition at line 39 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 39 of file G4MicroElecCrossSectionDataSet.cc
References z.
G4MicroElecCrossSectionDataSet::~G4MicroElecCrossSectionDataSet () virtual
Definition at line 50 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 50 of file G4MicroElecCrossSectionDataSet.cc
References algorithm, and CleanUpComponents().
G4MicroElecCrossSectionDataSet::G4MicroElecCrossSectionDataSet () private
G4MicroElecCrossSectionDataSet::G4MicroElecCrossSectionDataSet (const G4MicroElecCrossSectionDataSet & copy) private
Member Function Documentation
virtual void G4MicroElecCrossSectionDataSet::AddComponent (G4VEMDataSet * dataSet) inline virtual
Implements G4VEMDataSet.
Definition at line 54 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4MicroElecCrossSectionDataSet.hh
References components.
Referenced by LoadData(), and LoadNonLogData().
void G4MicroElecCrossSectionDataSet::CleanUpComponents (void) private
Definition at line 538 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 538 of file G4MicroElecCrossSectionDataSet.cc
References components.
Referenced by LoadData(), LoadNonLogData(), and ~G4MicroElecCrossSectionDataSet().
G4double G4MicroElecCrossSectionDataSet::FindValue (G4double e, G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 458 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 458 of file G4MicroElecCrossSectionDataSet.cc
References components.
Referenced by G4MicroElecElasticModel::CrossSectionPerVolume(), and G4MicroElecInelasticModel::CrossSectionPerVolume().
G4String G4MicroElecCrossSectionDataSet::FullFileName (const G4String & argFileName) const private
Definition at line 439 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 439 of file G4MicroElecCrossSectionDataSet.cc
References FatalException, and G4Exception().
Referenced by LoadData(), LoadNonLogData(), and SaveData().
const G4VDataSetAlgorithm* G4MicroElecCrossSectionDataSet::GetAlgorithm () const inline private
Definition at line 110 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 110 of file G4MicroElecCrossSectionDataSet.hh
References algorithm.
Referenced by LoadData(), and LoadNonLogData().
virtual const G4VEMDataSet* G4MicroElecCrossSectionDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 51 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 51 of file G4MicroElecCrossSectionDataSet.hh
References components.
Referenced by GetData(), GetEnergies(), GetLogData(), GetLogEnergies(), PrintData(), G4MicroElecInelasticModel::RandomSelect(), and SaveData().
virtual const G4DataVector& G4MicroElecCrossSectionDataSet::GetData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 63 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 63 of file G4MicroElecCrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetData().
virtual const G4DataVector& G4MicroElecCrossSectionDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 60 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 60 of file G4MicroElecCrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetEnergies().
Referenced by SaveData().
virtual const G4DataVector& G4MicroElecCrossSectionDataSet::GetLogData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 69 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 69 of file G4MicroElecCrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogData().
virtual const G4DataVector& G4MicroElecCrossSectionDataSet::GetLogEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 66 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 66 of file G4MicroElecCrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogEnergies().
G4double G4MicroElecCrossSectionDataSet::GetUnitData () const inline private
Definition at line 109 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 109 of file G4MicroElecCrossSectionDataSet.hh
References unitData.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4double G4MicroElecCrossSectionDataSet::GetUnitEnergies () const inline private
Definition at line 108 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 108 of file G4MicroElecCrossSectionDataSet.hh
References unitEnergies.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4bool G4MicroElecCrossSectionDataSet::LoadData (const G4String & argFileName) virtual
Implements G4VEMDataSet.
Definition at line 58 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 58 of file G4MicroElecCrossSectionDataSet.cc
References AddComponent(), c, CleanUpComponents(), e, FatalException, FullFileName(), G4Exception(), GetAlgorithm(), GetUnitData(), GetUnitEnergies(), in, and message().
Referenced by G4MicroElecElasticModel::Initialise(), and G4MicroElecInelasticModel::Initialise().
G4bool G4MicroElecCrossSectionDataSet::LoadNonLogData (const G4String & argFileName) virtual
Implements G4VEMDataSet.
Definition at line 225 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 225 of file G4MicroElecCrossSectionDataSet.cc
References AddComponent(), c, CleanUpComponents(), e, FatalException, FullFileName(), G4Exception(), GetAlgorithm(), GetUnitData(), GetUnitEnergies(), in, and message().
virtual size_t G4MicroElecCrossSectionDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 57 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 57 of file G4MicroElecCrossSectionDataSet.hh
References components.
Referenced by PrintData(), G4MicroElecInelasticModel::RandomSelect(), and SaveData().
G4MicroElecCrossSectionDataSet& G4MicroElecCrossSectionDataSet::operator= (const G4MicroElecCrossSectionDataSet & right) private
void G4MicroElecCrossSectionDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 476 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 476 of file G4MicroElecCrossSectionDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4VEMDataSet::PrintData().
virtual G4double G4MicroElecCrossSectionDataSet::RandomSelect (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 85 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 85 of file G4MicroElecCrossSectionDataSet.hh
G4bool G4MicroElecCrossSectionDataSet::SaveData (const G4String & argFileName) const virtual
Implements G4VEMDataSet.
Definition at line 370 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 370 of file G4MicroElecCrossSectionDataSet.cc
References FatalException, FullFileName(), G4Exception(), GetComponent(), G4VEMDataSet::GetData(), GetEnergies(), GetUnitData(), GetUnitEnergies(), k, left, message(), n, and NumberOfComponents().
void G4MicroElecCrossSectionDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * values, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 494 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 494 of file G4MicroElecCrossSectionDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetEnergiesData().
void G4MicroElecCrossSectionDataSet::SetLogEnergiesData (G4DataVector * x, G4DataVector * values, G4DataVector * log_x, G4DataVector * log_values, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 515 of file G4MicroElecCrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 515 of file G4MicroElecCrossSectionDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetLogEnergiesData().
Member Data Documentation
G4VDataSetAlgorithm* G4MicroElecCrossSectionDataSet::algorithm private
Definition at line 103 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 103 of file G4MicroElecCrossSectionDataSet.hh
Referenced by GetAlgorithm(), and ~G4MicroElecCrossSectionDataSet().
std::vector<G4VEMDataSet*> G4MicroElecCrossSectionDataSet::components private
Definition at line 99 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 99 of file G4MicroElecCrossSectionDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), FindValue(), GetComponent(), NumberOfComponents(), SetEnergiesData(), and SetLogEnergiesData().
G4double G4MicroElecCrossSectionDataSet::unitData private
Definition at line 106 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 106 of file G4MicroElecCrossSectionDataSet.hh
Referenced by GetUnitData().
G4double G4MicroElecCrossSectionDataSet::unitEnergies private
Definition at line 105 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 105 of file G4MicroElecCrossSectionDataSet.hh
Referenced by GetUnitEnergies().
G4int G4MicroElecCrossSectionDataSet::z private
Definition at line 101 of file G4MicroElecCrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 101 of file G4MicroElecCrossSectionDataSet.hh
Referenced by G4MicroElecCrossSectionDataSet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4MicroElecCrossSectionDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4MicroElecCrossSectionDataSet.cc