ECCE @ EIC Software: eRositaRunAction Class Reference
eRositaRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/include/eRositaRunAction.hh>
Public Member Functions
eRositaRunAction ()
~eRositaRunAction ()
void BeginOfRunAction (const G4Run *)
void EndOfRunAction (const G4Run *)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4Timer timerRun
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 40 of file eRositaRunAction.hh.
View newest version in sPHENIX GitHub at line 40 of file eRositaRunAction.hh
Constructor & Destructor Documentation
eRositaRunAction::eRositaRunAction ()
Definition at line 35 of file eRositaRunAction.cc.
View newest version in sPHENIX GitHub at line 35 of file eRositaRunAction.cc
eRositaRunAction::~eRositaRunAction ()
Definition at line 39 of file eRositaRunAction.cc.
View newest version in sPHENIX GitHub at line 39 of file eRositaRunAction.cc
Member Function Documentation
void eRositaRunAction::BeginOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
Definition at line 44 of file eRositaRunAction.cc.
View newest version in sPHENIX GitHub at line 44 of file eRositaRunAction.cc
References G4cout, G4endl, G4Run::GetRunID(), AnalysisManager::Instance(), G4Timer::Start(), and timerRun.
void eRositaRunAction::EndOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
Definition at line 55 of file eRositaRunAction.cc.
View newest version in sPHENIX GitHub at line 55 of file eRositaRunAction.cc
References AnalysisManager::Destroy(), G4cout, G4endl, G4Run::GetRunID(), AnalysisManager::Instance(), G4Timer::Stop(), and timerRun.
Member Data Documentation
G4Timer eRositaRunAction::timerRun private
Definition at line 51 of file eRositaRunAction.hh.
View newest version in sPHENIX GitHub at line 51 of file eRositaRunAction.hh
Referenced by BeginOfRunAction(), and EndOfRunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/include/eRositaRunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/src/eRositaRunAction.cc