ECCE @ EIC Software: G4RootPNtupleManager Class Reference
G4RootPNtupleManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootPNtupleManager.hh>
Public Member Functions
G4RootPNtupleManager (G4RootMainNtupleManager *main, const G4AnalysisManagerState &state, G4bool rowWise, G4bool rowMode)
~G4RootPNtupleManager ()
template<>
G4bool FillNtupleTColumn (G4int ntupleId, G4int columnId, const std::string &value)
Public Member Functions inherited from G4BaseNtupleManager
G4BaseNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4BaseNtupleManager ()
G4BaseNtupleManager (const G4BaseNtupleManager &rhs)=delete
G4BaseNtupleManager & operator= (const G4BaseNtupleManager &rhs)=delete
Public Member Functions inherited from G4VNtupleManager
G4VNtupleManager (const G4AnalysisManagerState &state)
virtual ~G4VNtupleManager ()
G4VNtupleManager (const G4VNtupleManager &rhs)=delete
G4VNtupleManager & operator= (const G4VNtupleManager &rhs)=delete
Public Member Functions inherited from G4BaseAnalysisManager
G4BaseAnalysisManager (const G4AnalysisManagerState &state)
virtual ~G4BaseAnalysisManager ()
G4bool SetFirstId (G4int firstId)
void SetLockFirstId (G4bool lockFirstId)
G4int GetFirstId () const
Private Types
enum G4PNtupleCreateMode
Private Member Functions
void CreateNtuple (G4RootPNtupleDescription *ntupleDescription, tools::wroot::ntuple *mainNtuple)
void CreateNtuplesFromMain ()
virtual G4int CreateNtuple (const G4String &name, const G4String &title) final
virtual G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > *vector) override
virtual G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > *vector) override
virtual G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > *vector) override
virtual G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name) override
virtual void FinishNtuple (G4int ntupleId) override
virtual G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final
virtual G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final
virtual G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final
virtual G4bool FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String &value) final
virtual G4bool AddNtupleRow (G4int ntupleId) final
virtual G4bool Merge () final
virtual G4bool Reset (G4bool deleteNtuple) final
virtual void SetActivation (G4bool activation) final
virtual void SetActivation (G4int ntupleId, G4bool activation) final
virtual G4bool GetActivation (G4int ntupleId) const final
virtual G4bool IsEmpty () const final
virtual G4int GetNofNtuples () const final
virtual G4int GetNofNtupleBookings () const final
void SetNtupleRowWise (G4bool rowWise, G4bool rowMode)
G4RootPNtupleDescription * GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn=true) const
tools::wroot::base_pntuple * GetNtupleInFunction (G4int id, G4String function, G4bool warn=true) const
tools::wroot::ntuple * GetMainNtupleInFunction (G4int id, G4String function, G4bool warn=true) const
template<typename T >
G4int CreateNtupleTColumn (G4int ntupleId, const G4String &name, std::vector< T > *vector)
template<typename T >
G4int CreateNtupleTColumn (const G4String &name, std::vector< T > *vector)
template<typename T >
G4bool FillNtupleTColumn (G4int ntupleId, G4int columnId, const T &value)
template<typename T >
G4bool FillNtupleTColumn (G4int columnId, const T &value)
Private Attributes
G4PNtupleCreateMode fCreateMode
G4RootMainNtupleManager * fMainNtupleManager
std::vector
< G4RootPNtupleDescription * > fNtupleDescriptionVector
std::vector
< tools::wroot::imt_ntuple * > fNtupleVector
G4bool fRowWise
G4bool fRowMode
Friends
class G4RootAnalysisManager
Additional Inherited Members
Protected Member Functions inherited from G4BaseNtupleManager
virtual G4int CreateNtupleIColumn (const G4String &name, std::vector< int > *vector) final
virtual G4int CreateNtupleFColumn (const G4String &name, std::vector< float > *vector) final
virtual G4int CreateNtupleDColumn (const G4String &name, std::vector< double > *vector) final
virtual G4int CreateNtupleSColumn (const G4String &name)
virtual void FinishNtuple () final
virtual G4bool SetFirstNtupleColumnId (G4int firstId) final
G4int GetFirstNtupleColumnId () const final
virtual G4bool FillNtupleIColumn (G4int id, G4int value) final
virtual G4bool FillNtupleFColumn (G4int id, G4float value) final
virtual G4bool FillNtupleDColumn (G4int id, G4double value) final
virtual G4bool FillNtupleSColumn (G4int id, const G4String &value) final
virtual G4bool AddNtupleRow () final
Protected Attributes inherited from G4BaseNtupleManager
G4int fFirstNtupleColumnId
G4bool fLockFirstNtupleColumnId
Detailed Description
Definition at line 78 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 78 of file G4RootPNtupleManager.hh
Member Enumeration Documentation
enum G4RootPNtupleManager::G4PNtupleCreateMode private
Definition at line 89 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RootPNtupleManager.hh
Constructor & Destructor Documentation
G4RootPNtupleManager::G4RootPNtupleManager (G4RootMainNtupleManager * main, const G4AnalysisManagerState & state, G4bool rowWise, G4bool rowMode) explicit
Definition at line 43 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 43 of file G4RootPNtupleManager.cc
G4RootPNtupleManager::~G4RootPNtupleManager ()
Definition at line 55 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 55 of file G4RootPNtupleManager.cc
References fNtupleDescriptionVector.
Member Function Documentation
G4bool G4RootPNtupleManager::AddNtupleRow (G4int ntupleId) final private virtual
Implements G4BaseNtupleManager.
Definition at line 352 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 352 of file G4RootPNtupleManager.cc
References G4BaseAnalysisManager::fState, G4Exception(), GetActivation(), G4AnalysisManagerState::GetIsActivation(), GetNtupleDescriptionInFunction(), G4AnalysisManagerState::GetVerboseL3(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, G4AnalysisVerbose::Message(), and G4TemplateAutoLock< _Mutex_t >::unlock().
void G4RootPNtupleManager::CreateNtuple (G4RootPNtupleDescription * ntupleDescription, tools::wroot::ntuple * mainNtuple) private
Definition at line 136 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 136 of file G4RootPNtupleManager.cc
References G4RootPNtupleDescription::fBasePNtuple, G4RootPNtupleDescription::fFile, G4RootPNtupleDescription::fIsNtupleOwner, G4RootPNtupleDescription::fMainBranches, fMainNtupleManager, G4RootPNtupleDescription::fNtuple, G4RootPNtupleDescription::fNtupleBooking, fNtupleVector, fRowMode, fRowWise, G4BaseAnalysisManager::fState, G4cout, G4RootMainNtupleManager::GetBasketEntries(), G4RootMainNtupleManager::GetNtupleFile(), G4AnalysisManagerState::GetVerboseL3(), G4AnalysisManagerState::GetVerboseL4(), it, G4AnalysisVerbose::Message(), and propagation_timing::rfile.
Referenced by CreateNtuplesFromMain(), and FinishNtuple().
G4int G4RootPNtupleManager::CreateNtuple (const G4String & name, const G4String & title) final private virtual
Implements G4BaseNtupleManager.
Definition at line 235 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 235 of file G4RootPNtupleManager.cc
References fCreateMode, G4BaseAnalysisManager::fFirstId, G4BaseAnalysisManager::fLockFirstId, fMainNtupleManager, fNtupleDescriptionVector, G4BaseAnalysisManager::fState, G4RootMainNtupleManager::GetNtupleFile(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), kUndefined, and G4AnalysisVerbose::Message().
G4int G4RootPNtupleManager::CreateNtupleDColumn (G4int ntupleId, const G4String & name, std::vector< double > * vector) override private virtual
Implements G4BaseNtupleManager.
Definition at line 292 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 292 of file G4RootPNtupleManager.cc
G4int G4RootPNtupleManager::CreateNtupleFColumn (G4int ntupleId, const G4String & name, std::vector< float > * vector) override private virtual
Implements G4BaseNtupleManager.
Definition at line 284 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 284 of file G4RootPNtupleManager.cc
G4int G4RootPNtupleManager::CreateNtupleIColumn (G4int ntupleId, const G4String & name, std::vector< int > * vector) override private virtual
Implements G4BaseNtupleManager.
Definition at line 277 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 277 of file G4RootPNtupleManager.cc
G4int G4RootPNtupleManager::CreateNtupleSColumn (G4int ntupleId, const G4String & name) override private virtual
Implements G4BaseNtupleManager.
Definition at line 299 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 299 of file G4RootPNtupleManager.cc
void G4RootPNtupleManager::CreateNtuplesFromMain () private
Definition at line 201 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 201 of file G4RootPNtupleManager.cc
References CreateNtuple(), fCreateMode, fMainNtupleManager, fNtupleDescriptionVector, G4RootMainNtupleManager::GetNtupleVector(), and kUndefined.
Referenced by G4RootAnalysisManager::OpenFileImpl().
template<typename T > G4int G4RootPNtupleManager::CreateNtupleTColumn (G4int ntupleId, const G4String & name, std::vector< T > * vector) private
Definition at line 189 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 189 of file G4RootPNtupleManager.hh
References G4BaseNtupleManager::fFirstNtupleColumnId, G4BaseNtupleManager::fLockFirstNtupleColumnId, G4BaseAnalysisManager::fState, GetNtupleDescriptionInFunction(), G4AnalysisManagerState::GetVerboseL2(), G4AnalysisManagerState::GetVerboseL4(), G4Analysis::kInvalidId, and G4AnalysisVerbose::Message().
template<typename T > G4int G4RootPNtupleManager::CreateNtupleTColumn (const G4String & name, std::vector< T > * vector) private
Definition at line 227 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 227 of file G4RootPNtupleManager.hh
References G4BaseAnalysisManager::fFirstId, and fNtupleDescriptionVector.
G4bool G4RootPNtupleManager::FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value) final private virtual
Implements G4BaseNtupleManager.
Definition at line 338 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 338 of file G4RootPNtupleManager.cc
G4bool G4RootPNtupleManager::FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value) final private virtual
Implements G4BaseNtupleManager.
Definition at line 331 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 331 of file G4RootPNtupleManager.cc
G4bool G4RootPNtupleManager::FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value) final private virtual
Implements G4BaseNtupleManager.
Definition at line 324 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 324 of file G4RootPNtupleManager.cc
G4bool G4RootPNtupleManager::FillNtupleSColumn (G4int ntupleId, G4int columnId, const G4String & value) final private virtual
Implements G4BaseNtupleManager.
Definition at line 345 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 345 of file G4RootPNtupleManager.cc
template<typename T > G4bool G4RootPNtupleManager::FillNtupleTColumn (G4int ntupleId, G4int columnId, const T & value) private
Definition at line 293 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 293 of file G4RootPNtupleManager.hh
References G4BaseNtupleManager::fFirstNtupleColumnId, G4BaseAnalysisManager::fState, G4cout, G4endl, G4Exception(), GetActivation(), G4AnalysisManagerState::GetIsActivation(), GetNtupleInFunction(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, G4AnalysisVerbose::Message(), and ntuple.
Referenced by FillNtupleTColumn().
template<typename T > G4bool G4RootPNtupleManager::FillNtupleTColumn (G4int columnId, const T & value) private
Definition at line 353 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 353 of file G4RootPNtupleManager.hh
References FillNtupleTColumn().
template<> G4bool G4RootPNtupleManager::FillNtupleTColumn (G4int ntupleId, G4int columnId, const std::string & value) inline
Definition at line 236 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 236 of file G4RootPNtupleManager.hh
References G4BaseNtupleManager::fFirstNtupleColumnId, G4BaseAnalysisManager::fState, G4cout, G4endl, G4Exception(), GetActivation(), G4AnalysisManagerState::GetIsActivation(), GetNtupleInFunction(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, G4AnalysisVerbose::Message(), and ntuple.
void G4RootPNtupleManager::FinishNtuple (G4int ntupleId) override private virtual
Implements G4BaseNtupleManager.
Definition at line 306 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 306 of file G4RootPNtupleManager.cc
References CreateNtuple(), fCreateMode, GetMainNtupleInFunction(), and GetNtupleDescriptionInFunction().
G4bool G4RootPNtupleManager::GetActivation (G4int ntupleId) const final private virtual
Implements G4VNtupleManager.
Definition at line 477 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 477 of file G4RootPNtupleManager.cc
References GetNtupleDescriptionInFunction().
Referenced by AddNtupleRow(), and FillNtupleTColumn().
tools::wroot::ntuple * G4RootPNtupleManager::GetMainNtupleInFunction (G4int id, G4String function, G4bool warn = true) const private
Definition at line 109 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 109 of file G4RootPNtupleManager.cc
References G4BaseAnalysisManager::fFirstId, fMainNtupleManager, G4Exception(), G4RootMainNtupleManager::GetNtupleVector(), and JustWarning.
Referenced by FinishNtuple().
G4int G4RootPNtupleManager::GetNofNtupleBookings () const final private virtual
Implements G4VNtupleManager.
Definition at line 493 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 493 of file G4RootPNtupleManager.cc
References fNtupleDescriptionVector.
G4int G4RootPNtupleManager::GetNofNtuples () const final private virtual
Implements G4VNtupleManager.
Definition at line 487 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 487 of file G4RootPNtupleManager.cc
References fNtupleVector.
G4RootPNtupleDescription * G4RootPNtupleManager::GetNtupleDescriptionInFunction (G4int id, G4String function, G4bool warn = true) const private
Definition at line 68 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 68 of file G4RootPNtupleManager.cc
References G4BaseAnalysisManager::fFirstId, fNtupleDescriptionVector, G4Exception(), and JustWarning.
Referenced by AddNtupleRow(), CreateNtupleTColumn(), FinishNtuple(), GetActivation(), GetNtupleInFunction(), and SetActivation().
tools::wroot::base_pntuple * G4RootPNtupleManager::GetNtupleInFunction (G4int id, G4String function, G4bool warn = true) const private
Definition at line 88 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 88 of file G4RootPNtupleManager.cc
References G4Exception(), GetNtupleDescriptionInFunction(), and JustWarning.
Referenced by FillNtupleTColumn().
G4bool G4RootPNtupleManager::IsEmpty () const final private virtual
Definition at line 499 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 499 of file G4RootPNtupleManager.cc
References fNtupleDescriptionVector.
G4bool G4RootPNtupleManager::Merge () final private virtual
Definition at line 397 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 397 of file G4RootPNtupleManager.cc
References fNtupleDescriptionVector, G4BaseAnalysisManager::fState, G4Exception(), G4AnalysisManagerState::GetVerboseL3(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, G4AnalysisVerbose::Message(), and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by G4RootAnalysisManager::WriteNtuple().
G4bool G4RootPNtupleManager::Reset (G4bool deleteNtuple) final private virtual
Definition at line 441 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 441 of file G4RootPNtupleManager.cc
References fNtupleDescriptionVector, and fNtupleVector.
void G4RootPNtupleManager::SetActivation (G4bool activation) final private virtual
Implements G4VNtupleManager.
Definition at line 457 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 457 of file G4RootPNtupleManager.cc
References fNtupleDescriptionVector.
void G4RootPNtupleManager::SetActivation (G4int ntupleId, G4bool activation) final private virtual
Implements G4VNtupleManager.
Definition at line 467 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 467 of file G4RootPNtupleManager.cc
References GetNtupleDescriptionInFunction().
void G4RootPNtupleManager::SetNtupleRowWise (G4bool rowWise, G4bool rowMode) private
Definition at line 505 of file G4RootPNtupleManager.cc.
View newest version in sPHENIX GitHub at line 505 of file G4RootPNtupleManager.cc
References fRowMode, and fRowWise.
Referenced by G4RootAnalysisManager::SetNtupleRowWise().
Friends And Related Function Documentation
friend class G4RootAnalysisManager friend
Definition at line 80 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 80 of file G4RootPNtupleManager.hh
Member Data Documentation
G4PNtupleCreateMode G4RootPNtupleManager::fCreateMode private
Definition at line 177 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 177 of file G4RootPNtupleManager.hh
Referenced by CreateNtuple(), CreateNtuplesFromMain(), and FinishNtuple().
G4RootMainNtupleManager* G4RootPNtupleManager::fMainNtupleManager private
Definition at line 178 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 178 of file G4RootPNtupleManager.hh
Referenced by CreateNtuple(), CreateNtuplesFromMain(), and GetMainNtupleInFunction().
std::vector<G4RootPNtupleDescription*> G4RootPNtupleManager::fNtupleDescriptionVector private
Definition at line 179 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 179 of file G4RootPNtupleManager.hh
Referenced by CreateNtuple(), CreateNtuplesFromMain(), CreateNtupleTColumn(), GetNofNtupleBookings(), GetNtupleDescriptionInFunction(), IsEmpty(), Merge(), Reset(), SetActivation(), and ~G4RootPNtupleManager().
std::vector<tools::wroot::imt_ntuple*> G4RootPNtupleManager::fNtupleVector private
Definition at line 180 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 180 of file G4RootPNtupleManager.hh
Referenced by CreateNtuple(), GetNofNtuples(), and Reset().
G4bool G4RootPNtupleManager::fRowMode private
Definition at line 182 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 182 of file G4RootPNtupleManager.hh
Referenced by CreateNtuple(), and SetNtupleRowWise().
G4bool G4RootPNtupleManager::fRowWise private
Definition at line 181 of file G4RootPNtupleManager.hh.
View newest version in sPHENIX GitHub at line 181 of file G4RootPNtupleManager.hh
Referenced by CreateNtuple(), and SetNtupleRowWise().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/root/include/G4RootPNtupleManager.hh
geant4/tree/geant4-10.6-release/source/analysis/root/src/G4RootPNtupleManager.cc