ECCE @ EIC Software: G4LightMedia Class Reference
G4LightMedia Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4LightMedia.hh>
Public Member Functions
G4LightMedia ()
G4LightMedia (const G4LightMedia &right)
~G4LightMedia ()
G4LightMedia & operator= (const G4LightMedia &)
G4bool operator== (const G4LightMedia &right) const
G4bool operator!= (const G4LightMedia &right) const
G4DynamicParticle * PionPlusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * PionMinusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * KaonPlusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * KaonZeroShortExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * KaonZeroLongExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * KaonMinusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * ProtonExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * AntiProtonExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * NeutronExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * AntiNeutronExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * LambdaExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * AntiLambdaExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * SigmaPlusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * SigmaMinusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * AntiSigmaPlusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * AntiSigmaMinusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * XiZeroExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * XiMinusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * AntiXiZeroExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * AntiXiMinusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * OmegaMinusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
G4DynamicParticle * AntiOmegaMinusExchange (const G4HadProjectile *incidentParticle, const G4Nucleus &aNucleus)
Detailed Description
Definition at line 40 of file G4LightMedia.hh.
View newest version in sPHENIX GitHub at line 40 of file G4LightMedia.hh
Constructor & Destructor Documentation
G4LightMedia::G4LightMedia () inline
Definition at line 44 of file G4LightMedia.hh.
View newest version in sPHENIX GitHub at line 44 of file G4LightMedia.hh
G4LightMedia::G4LightMedia (const G4LightMedia & right) inline
Definition at line 46 of file G4LightMedia.hh.
View newest version in sPHENIX GitHub at line 46 of file G4LightMedia.hh
References right.
G4LightMedia::~G4LightMedia () inline
Definition at line 49 of file G4LightMedia.hh.
View newest version in sPHENIX GitHub at line 49 of file G4LightMedia.hh
Member Function Documentation
G4DynamicParticle * G4LightMedia::AntiLambdaExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 362 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 362 of file G4LightMedia.cc
References G4AntiSigmaMinus::AntiSigmaMinus(), G4AntiSigmaPlus::AntiSigmaPlus(), G4AntiSigmaZero::AntiSigmaZero(), G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::AntiNeutronExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 257 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 257 of file G4LightMedia.cc
References G4AntiProton::AntiProton(), G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Neutron::Neutron(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::AntiOmegaMinusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 1128 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 1128 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Lambda::Lambda(), min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), G4XiMinus::XiMinus(), and G4XiZero::XiZero().
G4DynamicParticle * G4LightMedia::AntiProtonExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 204 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 204 of file G4LightMedia.cc
References G4AntiNeutron::AntiNeutron(), G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::AntiSigmaMinusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 625 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 625 of file G4LightMedia.cc
References G4AntiLambda::AntiLambda(), G4AntiSigmaZero::AntiSigmaZero(), G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::AntiSigmaPlusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 566 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 566 of file G4LightMedia.cc
References G4AntiLambda::AntiLambda(), G4AntiSigmaZero::AntiSigmaZero(), G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::AntiXiMinusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 943 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 943 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Lambda::Lambda(), min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), G4SigmaMinus::SigmaMinus(), G4SigmaZero::SigmaZero(), and G4XiZero::XiZero().
G4DynamicParticle * G4LightMedia::AntiXiZeroExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 854 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 854 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Lambda::Lambda(), min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), and G4XiMinus::XiMinus().
G4DynamicParticle * G4LightMedia::KaonMinusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 170 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 170 of file G4LightMedia.cc
G4DynamicParticle * G4LightMedia::KaonPlusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 83 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 83 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), min, G4Neutron::Neutron(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::KaonZeroLongExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 155 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 155 of file G4LightMedia.cc
References G4UniformRand, G4KaonZeroShort::KaonZeroShort(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::KaonZeroShortExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 117 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 117 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4KaonPlus::KaonPlus(), G4KaonZeroLong::KaonZeroLong(), min, G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::LambdaExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 284 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 284 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), and G4SigmaZero::SigmaZero().
G4DynamicParticle * G4LightMedia::NeutronExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 231 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 231 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::OmegaMinusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 1031 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 1031 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Lambda::Lambda(), min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), G4XiMinus::XiMinus(), and G4XiZero::XiZero().
G4bool G4LightMedia::operator!= (const G4LightMedia & right) const inline
Definition at line 57 of file G4LightMedia.hh.
View newest version in sPHENIX GitHub at line 57 of file G4LightMedia.hh
G4LightMedia& G4LightMedia::operator= (const G4LightMedia &) inline
Definition at line 51 of file G4LightMedia.hh.
View newest version in sPHENIX GitHub at line 51 of file G4LightMedia.hh
G4bool G4LightMedia::operator== (const G4LightMedia & right) const inline
Definition at line 54 of file G4LightMedia.hh.
View newest version in sPHENIX GitHub at line 54 of file G4LightMedia.hh
G4DynamicParticle * G4LightMedia::PionMinusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 75 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 75 of file G4LightMedia.cc
G4DynamicParticle * G4LightMedia::PionPlusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 45 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 45 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Neutron::Neutron(), G4PionZero::PionZero(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::ProtonExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 178 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 178 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, min, G4Neutron::Neutron(), G4Nucleus::ReturnTargetParticle(), and G4DynamicParticle::SetDefinition().
G4DynamicParticle * G4LightMedia::SigmaMinusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 504 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 504 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Lambda::Lambda(), min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), and G4SigmaZero::SigmaZero().
G4DynamicParticle * G4LightMedia::SigmaPlusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 442 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 442 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Lambda::Lambda(), min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), and G4SigmaZero::SigmaZero().
G4DynamicParticle * G4LightMedia::XiMinusExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 770 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 770 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Lambda::Lambda(), min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), G4SigmaMinus::SigmaMinus(), G4SigmaZero::SigmaZero(), and G4XiZero::XiZero().
G4DynamicParticle * G4LightMedia::XiZeroExchange (const G4HadProjectile * incidentParticle, const G4Nucleus & aNucleus)
Definition at line 685 of file G4LightMedia.cc.
View newest version in sPHENIX GitHub at line 685 of file G4LightMedia.cc
References G4UniformRand, G4Pow::GetInstance(), G4HadProjectile::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, G4Lambda::Lambda(), min, G4Neutron::Neutron(), G4Proton::Proton(), G4Nucleus::ReturnTargetParticle(), G4DynamicParticle::SetDefinition(), G4SigmaMinus::SigmaMinus(), G4SigmaPlus::SigmaPlus(), G4SigmaZero::SigmaZero(), and G4XiMinus::XiMinus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/include/G4LightMedia.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/util/src/G4LightMedia.cc