ECCE @ EIC Software: G4INCL::NuclearPotential::NuclearPotentialIsospin Class Reference
G4INCL::NuclearPotential::NuclearPotentialIsospin Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNuclearPotentialIsospin.hh>
Public Member Functions
NuclearPotentialIsospin (const G4int A, const G4int Z, const G4bool pionPotential)
virtual ~NuclearPotentialIsospin ()
virtual G4double computePotentialEnergy (const Particle *const p) const
Public Member Functions inherited from G4INCL::NuclearPotential::INuclearPotential
INuclearPotential (const G4int A, const G4int Z, const G4bool pionPot)
virtual ~INuclearPotential ()
G4bool hasPionPotential () const
Do we have a pion potential?
G4double getFermiEnergy (const Particle *const p) const
Return the Fermi energy for a particle.
G4double getFermiEnergy (const ParticleType t) const
Return the Fermi energy for a particle type.
G4double getSeparationEnergy (const Particle *const p) const
Return the separation energy for a particle.
G4double getSeparationEnergy (const ParticleType t) const
Return the separation energy for a particle type.
G4double getFermiMomentum (const Particle *const p) const
Return the Fermi momentum for a particle.
G4double getFermiMomentum (const ParticleType t) const
Return the Fermi momentum for a particle type.
Private Member Functions
void initialize ()
Private Attributes
G4double vProton
G4double vNeutron
G4double vDeltaPlusPlus
G4double vDeltaPlus
G4double vDeltaZero
G4double vDeltaMinus
G4double vSigmaPlus
G4double vSigmaZero
G4double vSigmaMinus
G4double vLambda
Additional Inherited Members
Protected Member Functions inherited from G4INCL::NuclearPotential::INuclearPotential
G4double computePionPotentialEnergy (const Particle *const p) const
Compute the potential energy for the given pion.
G4double computeKaonPotentialEnergy (const Particle *const p) const
Compute the potential energy for the given kaon.
G4double computePionResonancePotentialEnergy (const Particle *const p) const
Compute the potential energy for the given pion resonances (Eta, Omega and EtaPrime and Gamma also).
Protected Attributes inherited from G4INCL::NuclearPotential::INuclearPotential
const G4int theA
The mass number of the nucleus.
const G4int theZ
The charge number of the nucleus.
std::map< ParticleType, G4double > fermiEnergy
std::map< ParticleType, G4double > fermiMomentum
std::map< ParticleType, G4double > separationEnergy
Detailed Description
Definition at line 56 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 56 of file G4INCLNuclearPotentialIsospin.hh
Constructor & Destructor Documentation
G4INCL::NuclearPotential::NuclearPotentialIsospin::NuclearPotentialIsospin (const G4int A, const G4int Z, const G4bool pionPotential)
Definition at line 57 of file G4INCLNuclearPotentialIsospin.cc.
View newest version in sPHENIX GitHub at line 57 of file G4INCLNuclearPotentialIsospin.cc
References initialize().
G4INCL::NuclearPotential::NuclearPotentialIsospin::~NuclearPotentialIsospin () virtual
Definition at line 64 of file G4INCLNuclearPotentialIsospin.cc.
View newest version in sPHENIX GitHub at line 64 of file G4INCLNuclearPotentialIsospin.cc
Member Function Documentation
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::computePotentialEnergy (const Particle *const p) const virtual
Implements G4INCL::NuclearPotential::INuclearPotential.
Reimplemented in G4INCL::NuclearPotential::NuclearPotentialEnergyIsospinSmooth, and G4INCL::NuclearPotential::NuclearPotentialEnergyIsospin.
Definition at line 196 of file G4INCLNuclearPotentialIsospin.cc.
View newest version in sPHENIX GitHub at line 196 of file G4INCLNuclearPotentialIsospin.cc
References G4INCL::Composite, G4INCL::NuclearPotential::INuclearPotential::computeKaonPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionPotentialEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePionResonancePotentialEnergy(), G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::Particle::getType(), INCL_ERROR, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Proton, G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, G4INCL::UnknownParticle, vDeltaMinus, vDeltaPlus, vDeltaPlusPlus, vDeltaZero, vLambda, vNeutron, vProton, vSigmaMinus, vSigmaPlus, and vSigmaZero.
Referenced by G4INCL::NuclearPotential::NuclearPotentialEnergyIsospin::computePotentialEnergy(), and G4INCL::NuclearPotential::NuclearPotentialEnergyIsospinSmooth::computePotentialEnergy().
void G4INCL::NuclearPotential::NuclearPotentialIsospin::initialize () private
Definition at line 66 of file G4INCLNuclearPotentialIsospin.cc.
View newest version in sPHENIX GitHub at line 66 of file G4INCLNuclearPotentialIsospin.cc
References G4INCL::DeltaMinus, G4INCL::DeltaPlus, G4INCL::DeltaPlusPlus, G4INCL::DeltaZero, E, G4INCL::Eta, G4INCL::EtaPrime, G4INCL::NuclearPotential::INuclearPotential::fermiEnergy, G4INCL::NuclearPotential::INuclearPotential::fermiMomentum, G4INCL::ParticleTable::getFermiMomentum, G4INCL::ParticleTable::getINCLMass(), G4INCL::ParticleTable::getSeparationEnergy, INCL_DEBUG, G4INCL::KLong, G4INCL::KMinus, G4INCL::KPlus, G4INCL::KShort, G4INCL::KZero, G4INCL::KZeroBar, G4INCL::Lambda, max, G4INCL::Neutron, G4INCL::Omega, G4INCL::Photon, G4INCL::PiMinus, G4INCL::PiPlus, G4INCL::PiZero, G4INCL::Math::pow13(), G4INCL::Proton, G4INCL::NuclearPotential::INuclearPotential::separationEnergy, G4INCL::SigmaMinus, G4INCL::SigmaPlus, G4INCL::SigmaZero, G4INCL::NuclearPotential::INuclearPotential::theA, G4INCL::NuclearPotential::INuclearPotential::theZ, vDeltaMinus, vDeltaPlus, vDeltaPlusPlus, vDeltaZero, vLambda, vNeutron, vProton, vSigmaMinus, vSigmaPlus, and vSigmaZero.
Referenced by NuclearPotentialIsospin().
Member Data Documentation
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vDeltaMinus private
Definition at line 66 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vDeltaPlus private
Definition at line 66 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vDeltaPlusPlus private
Definition at line 66 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vDeltaZero private
Definition at line 66 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vLambda private
Definition at line 67 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vNeutron private
Definition at line 65 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 65 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vProton private
Definition at line 65 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 65 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vSigmaMinus private
Definition at line 67 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vSigmaPlus private
Definition at line 67 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
G4double G4INCL::NuclearPotential::NuclearPotentialIsospin::vSigmaZero private
Definition at line 67 of file G4INCLNuclearPotentialIsospin.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLNuclearPotentialIsospin.hh
Referenced by computePotentialEnergy(), and initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNuclearPotentialIsospin.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNuclearPotentialIsospin.cc