ECCE @ EIC Software: VoxelParam Class Reference
VoxelParam Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/include/VoxelParam.hh>
Public Member Functions
VoxelParam ()
~VoxelParam ()
virtual void ComputeTransformation (const G4int id, G4VPhysicalVolume *vol) const
virtual void ComputeDimensions (G4Box &box, const G4int id, const G4VPhysicalVolume *vol) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
VoxelParam ()
~VoxelParam ()
virtual void ComputeTransformation (const G4int id, G4VPhysicalVolume *vol) const
virtual void ComputeDimensions (G4Box &box, const G4int id, const G4VPhysicalVolume *vol) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
VoxelParam ()
~VoxelParam ()
virtual void ComputeTransformation (const G4int id, G4VPhysicalVolume *vol) const
virtual void ComputeDimensions (G4Box &box, const G4int id, const G4VPhysicalVolume *vol) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Detailed Description
Definition at line 35 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 35 of file VoxelParam.hh
Constructor & Destructor Documentation
VoxelParam::VoxelParam ()
Definition at line 36 of file VoxelParam.cc.
View newest version in sPHENIX GitHub at line 36 of file VoxelParam.cc
VoxelParam::~VoxelParam ()
Definition at line 41 of file VoxelParam.cc.
View newest version in sPHENIX GitHub at line 41 of file VoxelParam.cc
VoxelParam::VoxelParam ()
VoxelParam::~VoxelParam ()
VoxelParam::VoxelParam ()
VoxelParam::~VoxelParam ()
Member Function Documentation
void VoxelParam::ComputeDimensions (G4Box & box, const G4int id, const G4VPhysicalVolume * vol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 65 of file VoxelParam.cc.
View newest version in sPHENIX GitHub at line 65 of file VoxelParam.cc
References mm, G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), and G4Box::SetZHalfLength().
virtual void VoxelParam::ComputeDimensions (G4Box & box, const G4int id, const G4VPhysicalVolume * vol) const virtual
Reimplemented from G4VPVParameterisation.
virtual void VoxelParam::ComputeDimensions (G4Box & box, const G4int id, const G4VPhysicalVolume * vol) const virtual
Reimplemented from G4VPVParameterisation.
virtual void VoxelParam::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 47 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 47 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 47 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 47 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 47 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 47 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 50 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 50 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 50 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 50 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 50 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 50 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 53 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 53 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 53 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 53 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 53 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 53 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 56 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 56 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 56 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 56 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 56 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 56 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 59 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 59 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 59 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 59 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 59 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 59 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 62 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 62 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 62 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 62 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 62 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 62 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 65 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 65 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 65 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 65 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 65 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 65 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 68 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 68 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 68 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 68 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 68 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 68 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 71 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 71 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 71 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 71 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 71 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 71 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 74 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 74 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 74 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 74 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 74 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 74 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 77 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 77 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 77 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 77 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 77 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 77 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 80 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 80 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 80 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 80 of file VoxelParam.hh
virtual void VoxelParam::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Definition at line 80 of file VoxelParam.hh.
View newest version in sPHENIX GitHub at line 80 of file VoxelParam.hh
virtual void VoxelParam::ComputeTransformation (const G4int id, G4VPhysicalVolume * vol) const virtual
Implements G4VPVParameterisation.
void VoxelParam::ComputeTransformation (const G4int id, G4VPhysicalVolume * vol) const virtual
Implements G4VPVParameterisation.
Definition at line 46 of file VoxelParam.cc.
View newest version in sPHENIX GitHub at line 46 of file VoxelParam.cc
References cm, and mm.
virtual void VoxelParam::ComputeTransformation (const G4int id, G4VPhysicalVolume * vol) const virtual
Implements G4VPVParameterisation.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/include/VoxelParam.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/include/VoxelParam.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/include/VoxelParam.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI02/src/VoxelParam.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI03/src/VoxelParam.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/examples/exMPI04/src/VoxelParam.cc