ECCE @ EIC Software: CLHEP::RandPoisson Class Reference
CLHEP::RandPoisson Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandPoisson.h>
Public Member Functions
RandPoisson (HepRandomEngine &anEngine, double a1=1.0)
RandPoisson (HepRandomEngine *anEngine, double a1=1.0)
virtual ~RandPoisson ()
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
long fire ()
long fire (double m)
void fireArray (const int size, long *vect)
void fireArray (const int size, long *vect, double m)
double operator() ()
double operator() (double m)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static long shoot (double m=1.0)
static void shootArray (const int size, long *vect, double m=1.0)
static long shoot (HepRandomEngine *anEngine, double m=1.0)
static void shootArray (HepRandomEngine *anEngine, const int size, long *vect, double m=1.0)
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Protected Member Functions
HepRandomEngine * getLocalEngine ()
Static Protected Member Functions
static double getOldMean ()
static double getMaxMean ()
static void setOldMean (double val)
static double * getPStatus ()
static void setPStatus (double sq, double alxm, double g1)
Protected Attributes
double meanMax
double defaultMean
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
double status [3]
double oldm
Static Private Attributes
static CLHEP_THREAD_LOCAL double status_st [3] = {0., 0., 0.}
static CLHEP_THREAD_LOCAL double oldm_st = -1.0
static const double meanMax_st = 2.0E9
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 41 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 41 of file RandPoisson.h
Constructor & Destructor Documentation
CLHEP::RandPoisson::RandPoisson (HepRandomEngine & anEngine, double a1 = 1.0) inline
CLHEP::RandPoisson::RandPoisson (HepRandomEngine * anEngine, double a1 = 1.0) inline
CLHEP::RandPoisson::~RandPoisson () virtual
Definition at line 42 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 42 of file RandPoisson.cc
Member Function Documentation
static std::string CLHEP::RandPoisson::distributionName () inline static
Definition at line 93 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 93 of file RandPoisson.h
HepRandomEngine & CLHEP::RandPoisson::engine () virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandPoissonQ.
Definition at line 35 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 35 of file RandPoisson.cc
References localEngine.
Referenced by CLHEP::RandPoissonQ::engine().
long CLHEP::RandPoisson::fire ()
Definition at line 212 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 212 of file RandPoisson.cc
References defaultMean.
Referenced by fireArray(), and operator()().
long CLHEP::RandPoisson::fire (double m)
Definition at line 216 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 216 of file RandPoisson.cc
References CLHEP::gammln(), getMaxMean(), localEngine, meanMax, CLHEP::normal(), oldm, CLHEP::pi, status, t, and y.
void CLHEP::RandPoisson::fireArray (const int size, long * vect)
Definition at line 268 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 268 of file RandPoisson.cc
References defaultMean, fire(), and v.
void CLHEP::RandPoisson::fireArray (const int size, long * vect, double m)
Definition at line 274 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 274 of file RandPoisson.cc
References fire(), and v.
std::istream & CLHEP::RandPoisson::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandPoissonQ.
Definition at line 301 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 301 of file RandPoisson.cc
References defaultMean, CLHEP::DoubConv::longs2double(), meanMax, name(), oldm, CLHEP::possibleKeywordInput(), status, and t.
Referenced by CLHEP::RandPoissonQ::get().
HepRandomEngine* CLHEP::RandPoisson::getLocalEngine () inline protected
Referenced by CLHEP::RandPoissonQ::fire().
static double CLHEP::RandPoisson::getMaxMean () inline static protected
Definition at line 103 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 103 of file RandPoisson.h
References meanMax_st.
Referenced by fire(), and shoot().
static double CLHEP::RandPoisson::getOldMean () inline static protected
Definition at line 101 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 101 of file RandPoisson.h
References oldm_st.
Referenced by shoot().
static double* CLHEP::RandPoisson::getPStatus () inline static protected
Definition at line 107 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 107 of file RandPoisson.h
References status_st.
Referenced by shoot().
std::string CLHEP::RandPoisson::name () const virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandPoissonQ.
Definition at line 34 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 34 of file RandPoisson.cc
Referenced by get(), and put().
double CLHEP::RandPoisson::operator() () virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandPoissonQ.
Definition at line 45 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 45 of file RandPoisson.cc
References defaultMean, and fire().
double CLHEP::RandPoisson::operator() (double m)
Definition at line 49 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 49 of file RandPoisson.cc
References fire().
std::ostream & CLHEP::RandPoisson::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Reimplemented in CLHEP::RandPoissonQ.
Definition at line 280 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 280 of file RandPoisson.cc
References defaultMean, CLHEP::DoubConv::dto2longs(), meanMax, name(), oldm, gammaraytel::pr, status, and t.
Referenced by CLHEP::RandPoissonQ::put().
static void CLHEP::RandPoisson::setOldMean (double val) inline static protected
Definition at line 105 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 105 of file RandPoisson.h
References oldm_st.
Referenced by shoot().
static void CLHEP::RandPoisson::setPStatus (double sq, double alxm, double g1) inline static protected
Definition at line 109 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 109 of file RandPoisson.h
References status_st.
Referenced by shoot().
long CLHEP::RandPoisson::shoot (double m = 1.0) static
Definition at line 90 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 90 of file RandPoisson.cc
References CLHEP::HepRandomEngine::flat(), CLHEP::gammln(), getMaxMean(), getOldMean(), getPStatus(), CLHEP::HepRandom::getTheEngine(), CLHEP::normal(), G4InuclParticleNames::om, CLHEP::pi, setOldMean(), setPStatus(), status, t, and y.
Referenced by CLHEP::RandPoissonQ::poissonDeviateSmall(), and shootArray().
long CLHEP::RandPoisson::shoot (HepRandomEngine * anEngine, double m = 1.0) static
Definition at line 151 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 151 of file RandPoisson.cc
References CLHEP::HepRandomEngine::flat(), CLHEP::gammln(), getMaxMean(), getOldMean(), getPStatus(), CLHEP::normal(), G4InuclParticleNames::om, CLHEP::pi, setOldMean(), setPStatus(), status, t, and y.
void CLHEP::RandPoisson::shootArray (const int size, long * vect, double m = 1.0) static
Definition at line 145 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 145 of file RandPoisson.cc
References shoot(), and v.
void CLHEP::RandPoisson::shootArray (HepRandomEngine * anEngine, const int size, long * vect, double m = 1.0) static
Definition at line 205 of file RandPoisson.cc.
View newest version in sPHENIX GitHub at line 205 of file RandPoisson.cc
References shoot(), and v.
Member Data Documentation
double CLHEP::RandPoisson::defaultMean protected
Definition at line 99 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 99 of file RandPoisson.h
Referenced by fire(), CLHEP::RandPoissonQ::fire(), fireArray(), CLHEP::RandPoissonQ::fireArray(), get(), operator()(), put(), and CLHEP::RandPoissonQ::setupForDefaultMu().
std::shared_ptr<HepRandomEngine> CLHEP::RandPoisson::localEngine private
Definition at line 117 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 117 of file RandPoisson.h
Referenced by engine(), and fire().
double CLHEP::RandPoisson::meanMax protected
Definition at line 98 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 98 of file RandPoisson.h
Referenced by fire(), get(), and put().
const double CLHEP::RandPoisson::meanMax_st = 2.0E9 static private
Definition at line 123 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 123 of file RandPoisson.h
Referenced by getMaxMean().
double CLHEP::RandPoisson::oldm private
Definition at line 118 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 118 of file RandPoisson.h
Referenced by fire(), get(), and put().
CLHEP_THREAD_LOCAL double CLHEP::RandPoisson::oldm_st = -1.0 static private
Definition at line 122 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 122 of file RandPoisson.h
Referenced by getOldMean(), and setOldMean().
double CLHEP::RandPoisson::status[3] private
Definition at line 118 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 118 of file RandPoisson.h
Referenced by fire(), get(), put(), and shoot().
CLHEP_THREAD_LOCAL double CLHEP::RandPoisson::status_st = {0., 0., 0.} static private
Definition at line 121 of file RandPoisson.h.
View newest version in sPHENIX GitHub at line 121 of file RandPoisson.h
Referenced by getPStatus(), and setPStatus().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandPoisson.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandPoisson.cc