ECCE @ EIC Software: eRositaTrackerHit Class Reference
eRositaTrackerHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/include/eRositaTrackerHit.hh>
Public Member Functions
eRositaTrackerHit ()
~eRositaTrackerHit ()
eRositaTrackerHit (const eRositaTrackerHit &)
const eRositaTrackerHit & operator= (const eRositaTrackerHit &)
G4bool operator== (const eRositaTrackerHit &) const
void * operator new (size_t)
void operator delete (void *)
void Draw ()
void Print ()
void PrintToFile ()
void SetTrackID (G4int track)
void SetChamberNb (G4int chamb)
void SetEdep (G4double de)
void SetPos (G4ThreeVector xyz)
G4int GetTrackID ()
G4int GetChamberNb ()
G4double GetEdep ()
G4ThreeVector GetPos ()
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Private Attributes
G4int trackID
G4int chamberNb
G4double edep
G4ThreeVector pos
Detailed Description
Definition at line 40 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 40 of file eRositaTrackerHit.hh
Constructor & Destructor Documentation
eRositaTrackerHit::eRositaTrackerHit ()
Definition at line 41 of file eRositaTrackerHit.cc.
View newest version in sPHENIX GitHub at line 41 of file eRositaTrackerHit.cc
eRositaTrackerHit::~eRositaTrackerHit ()
Definition at line 44 of file eRositaTrackerHit.cc.
View newest version in sPHENIX GitHub at line 44 of file eRositaTrackerHit.cc
eRositaTrackerHit::eRositaTrackerHit (const eRositaTrackerHit & right)
Definition at line 47 of file eRositaTrackerHit.cc.
View newest version in sPHENIX GitHub at line 47 of file eRositaTrackerHit.cc
References chamberNb, edep, pos, and trackID.
Member Function Documentation
void eRositaTrackerHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 73 of file eRositaTrackerHit.cc.
View newest version in sPHENIX GitHub at line 73 of file eRositaTrackerHit.cc
References G4VVisManager::Draw(), G4VMarker::filled, G4VVisManager::GetConcreteInstance(), pos, G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
G4int eRositaTrackerHit::GetChamberNb () inline
Definition at line 65 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 65 of file eRositaTrackerHit.hh
References chamberNb.
G4double eRositaTrackerHit::GetEdep () inline
Definition at line 66 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 66 of file eRositaTrackerHit.hh
References edep.
G4ThreeVector eRositaTrackerHit::GetPos () inline
Definition at line 67 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 67 of file eRositaTrackerHit.hh
G4int eRositaTrackerHit::GetTrackID () inline
Definition at line 64 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 64 of file eRositaTrackerHit.hh
References trackID.
void eRositaTrackerHit::operator delete (void * aHit) inline
Definition at line 91 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 91 of file eRositaTrackerHit.hh
References G4Allocator< Type >::FreeSingle().
void * eRositaTrackerHit::operator new (size_t) inline
Definition at line 83 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 83 of file eRositaTrackerHit.hh
References G4Allocator< Type >::MallocSingle().
const eRositaTrackerHit & eRositaTrackerHit::operator= (const eRositaTrackerHit & right)
Definition at line 57 of file eRositaTrackerHit.cc.
View newest version in sPHENIX GitHub at line 57 of file eRositaTrackerHit.cc
References chamberNb, edep, pos, and trackID.
G4bool eRositaTrackerHit::operator== (const eRositaTrackerHit & right) const
Definition at line 67 of file eRositaTrackerHit.cc.
View newest version in sPHENIX GitHub at line 67 of file eRositaTrackerHit.cc
void eRositaTrackerHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 89 of file eRositaTrackerHit.cc.
View newest version in sPHENIX GitHub at line 89 of file eRositaTrackerHit.cc
References edep, G4BestUnit, G4cout, G4endl, pos, and trackID.
void eRositaTrackerHit::PrintToFile ()
Definition at line 97 of file eRositaTrackerHit.cc.
View newest version in sPHENIX GitHub at line 97 of file eRositaTrackerHit.cc
References edep, AnalysisManager::Instance(), and AnalysisManager::Score().
void eRositaTrackerHit::SetChamberNb (G4int chamb) inline
Definition at line 60 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 60 of file eRositaTrackerHit.hh
References chamberNb.
void eRositaTrackerHit::SetEdep (G4double de) inline
Definition at line 61 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 61 of file eRositaTrackerHit.hh
References edep.
Referenced by eRositaTrackerSD::ProcessHits().
void eRositaTrackerHit::SetPos (G4ThreeVector xyz) inline
Definition at line 62 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 62 of file eRositaTrackerHit.hh
References pos.
Referenced by eRositaTrackerSD::ProcessHits().
void eRositaTrackerHit::SetTrackID (G4int track) inline
Definition at line 59 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 59 of file eRositaTrackerHit.hh
References track, and trackID.
Referenced by eRositaTrackerSD::ProcessHits().
Member Data Documentation
G4int eRositaTrackerHit::chamberNb private
Definition at line 72 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 72 of file eRositaTrackerHit.hh
Referenced by eRositaTrackerHit(), GetChamberNb(), operator=(), and SetChamberNb().
G4double eRositaTrackerHit::edep private
Definition at line 73 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 73 of file eRositaTrackerHit.hh
Referenced by eRositaTrackerHit(), GetEdep(), operator=(), Print(), PrintToFile(), and SetEdep().
G4ThreeVector eRositaTrackerHit::pos private
Definition at line 74 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 74 of file eRositaTrackerHit.hh
Referenced by Draw(), eRositaTrackerHit(), operator=(), Print(), and SetPos().
G4int eRositaTrackerHit::trackID private
Definition at line 67 of file eRositaTrackerHit.hh.
View newest version in sPHENIX GitHub at line 67 of file eRositaTrackerHit.hh
Referenced by eRositaTrackerHit(), GetTrackID(), operator=(), Print(), and SetTrackID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/include/eRositaTrackerHit.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/application/src/eRositaTrackerHit.cc