ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/src/G4DNABrownianTransportation.cc File Reference
G4DNABrownianTransportation.cc File Reference
#include <CLHEP/Random/Stat.h>
#include "G4DNABrownianTransportation.hh"
#include <G4Scheduler.hh>
#include "G4PhysicalConstants.hh"
#include "G4SystemOfUnits.hh"
#include "Randomize.hh"
#include "G4Molecule.hh"
#include "G4RandomDirection.hh"
#include "G4ParticleTable.hh"
#include "G4SafetyHelper.hh"
#include "G4TransportationManager.hh"
#include "G4UnitsTable.hh"
#include "G4NistManager.hh"
#include "G4DNAMolecularMaterial.hh"
#include "G4ITNavigator.hh"
#include "G4ITSafetyHelper.hh"
#include "G4TrackingInformation.hh"
Macros
#define State(theXInfo) (GetState<G4ITBrownianState>()->theXInfo)
#define RED ""
#define LIGHT_RED ""
#define GREEN ""
#define GREEN_ON_BLUE ""
#define RESET_COLOR ""
Functions
static double InvErf (double x)
static double InvErfc (double x)
static double Erfc (double x)
Macro Definition Documentation
#define GREEN ""
Definition at line 82 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 82 of file G4DNABrownianTransportation.cc
#define GREEN_ON_BLUE ""
Definition at line 83 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 83 of file G4DNABrownianTransportation.cc
Referenced by G4DNABrownianTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::ComputeStep(), G4DNABrownianTransportation::Diffusion(), and G4DNABrownianTransportation::PostStepDoIt().
#define LIGHT_RED ""
Definition at line 81 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 81 of file G4DNABrownianTransportation.cc
#define RED ""
Definition at line 80 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 80 of file G4DNABrownianTransportation.cc
#define RESET_COLOR ""
Definition at line 84 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 84 of file G4DNABrownianTransportation.cc
Referenced by G4DNABrownianTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::ComputeStep(), G4DNABrownianTransportation::Diffusion(), and G4DNABrownianTransportation::PostStepDoIt().
#define State (theXInfo) (GetState<G4ITBrownianState>()->theXInfo)
Definition at line 64 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 64 of file G4DNABrownianTransportation.cc
Referenced by G4DNABrownianTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::ComputeStep(), and G4DNABrownianTransportation::Diffusion().
Function Documentation
static double Erfc (double x) static
Definition at line 110 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 110 of file G4DNABrownianTransportation.cc
References CLHEP::HepStat::erf().
Referenced by G4DNABrownianTransportation::ComputeStep().
static double InvErf (double x) static
Definition at line 95 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 95 of file G4DNABrownianTransportation.cc
References CLHEP::HepStat::inverseErf().
Referenced by G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength().
static double InvErfc (double x) static
Definition at line 100 of file G4DNABrownianTransportation.cc.
View newest version in sPHENIX GitHub at line 100 of file G4DNABrownianTransportation.cc
References CLHEP::HepStat::inverseErf().
Referenced by G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), and G4DNABrownianTransportation::ComputeStep().