ECCE @ EIC Software: DicomROIContour Class Reference
DicomROIContour Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomROIContour.hh>
Public Member Functions
DicomROIContour ()
~DicomROIContour ()
void AddImageIUID (OFString ima)
OFString GetGeomType () const
void SetGeomType (OFString gt)
std::vector< G4ThreeVector > GetPoints () const
std::vector< G4ThreeVector > GetDirections ()
G4double GetZ ()
void SetData (std::vector< G4ThreeVector > data)
void AddPoints (std::vector< G4ThreeVector > points)
void Print (std::ostream &out)
Private Attributes
std::vector< OFString > theImageIUIDs
OFString theGeomType
std::vector< G4ThreeVector > thePoints
std::vector< G4ThreeVector > theDirections
Detailed Description
Definition at line 34 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 34 of file DicomROIContour.hh
Constructor & Destructor Documentation
DicomROIContour::DicomROIContour ()
Definition at line 29 of file DicomROIContour.cc.
View newest version in sPHENIX GitHub at line 29 of file DicomROIContour.cc
DicomROIContour::~DicomROIContour () inline
Definition at line 38 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 38 of file DicomROIContour.hh
Member Function Documentation
void DicomROIContour::AddImageIUID (OFString ima) inline
Definition at line 41 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 41 of file DicomROIContour.hh
References theImageIUIDs.
Referenced by DicomFileStructure::ReadData().
void DicomROIContour::AddPoints (std::vector< G4ThreeVector > points)
Definition at line 62 of file DicomROIContour.cc.
View newest version in sPHENIX GitHub at line 62 of file DicomROIContour.cc
References theDirections, and thePoints.
std::vector<G4ThreeVector> DicomROIContour::GetDirections () inline
Definition at line 53 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 53 of file DicomROIContour.hh
References theDirections.
Referenced by DicomFileCT::BuildStructureIDs().
OFString DicomROIContour::GetGeomType () const inline
Definition at line 44 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 44 of file DicomROIContour.hh
References theGeomType.
Referenced by DicomFileCT::BuildStructureIDs().
std::vector<G4ThreeVector> DicomROIContour::GetPoints () const inline
Definition at line 50 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 50 of file DicomROIContour.hh
References thePoints.
Referenced by DicomROI::AddContour(), and DicomFileCT::BuildStructureIDs().
G4double DicomROIContour::GetZ ()
Definition at line 48 of file DicomROIContour.cc.
View newest version in sPHENIX GitHub at line 48 of file DicomROIContour.cc
References DBL_MAX, FatalException, G4cout, G4Exception(), Print(), and thePoints.
Referenced by DicomROI::AddContour(), and DicomFileCT::BuildStructureIDs().
void DicomROIContour::Print (std::ostream & out)
Definition at line 78 of file DicomROIContour.cc.
View newest version in sPHENIX GitHub at line 78 of file DicomROIContour.cc
References G4endl, theGeomType, theImageIUIDs, and thePoints.
Referenced by GetZ().
void DicomROIContour::SetData (std::vector< G4ThreeVector > data)
Definition at line 34 of file DicomROIContour.cc.
View newest version in sPHENIX GitHub at line 34 of file DicomROIContour.cc
References theDirections, theGeomType, and thePoints.
Referenced by DicomFileStructure::ReadData().
void DicomROIContour::SetGeomType (OFString gt) inline
Definition at line 47 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 47 of file DicomROIContour.hh
References theGeomType.
Referenced by DicomFileStructure::ReadData().
Member Data Documentation
std::vector<G4ThreeVector> DicomROIContour::theDirections private
Definition at line 68 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 68 of file DicomROIContour.hh
Referenced by AddPoints(), GetDirections(), and SetData().
OFString DicomROIContour::theGeomType private
Definition at line 66 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 66 of file DicomROIContour.hh
Referenced by GetGeomType(), Print(), SetData(), and SetGeomType().
std::vector<OFString> DicomROIContour::theImageIUIDs private
Definition at line 64 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 64 of file DicomROIContour.hh
Referenced by AddImageIUID(), and Print().
std::vector<G4ThreeVector> DicomROIContour::thePoints private
Definition at line 67 of file DicomROIContour.hh.
View newest version in sPHENIX GitHub at line 67 of file DicomROIContour.hh
Referenced by AddPoints(), GetPoints(), GetZ(), Print(), and SetData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomROIContour.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/src/DicomROIContour.cc