ECCE @ EIC Software: G4LEpp Class Reference
G4LEpp Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4LEpp.hh>
Public Member Functions
G4LEpp ()
~G4LEpp () override
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus) override
G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A) override
Public Member Functions inherited from G4HadronElastic
G4HadronElastic (const G4String &name="hElasticLHEP")
~G4HadronElastic () override
G4double GetSlopeCof (const G4int pdg)
void SetLowestEnergyLimit (G4double value)
G4double LowestEnergyLimit () const
G4double ComputeMomentumCMS (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
void ModelDescription (std::ostream &) const override
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Types
enum { NENERGY =40, NANGLE =180 }
Static Private Attributes
static const G4float Sig [NENERGY][NANGLE]
static const G4float elab [NENERGY]
static const G4float dSigmax [NENERGY]
static const G4float Sigtot [NENERGY]
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronElastic
G4double pLocalTmax
Detailed Description
Definition at line 41 of file G4LEpp.hh.
View newest version in sPHENIX GitHub at line 41 of file G4LEpp.hh
Member Enumeration Documentation
anonymous enum private
Enumerator:
NENERGY
NANGLE
Definition at line 45 of file G4LEpp.hh.
View newest version in sPHENIX GitHub at line 45 of file G4LEpp.hh
Constructor & Destructor Documentation
G4LEpp::G4LEpp () explicit
Definition at line 41 of file G4LEpp.cc.
View newest version in sPHENIX GitHub at line 41 of file G4LEpp.cc
References GeV, G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
G4LEpp::~G4LEpp () override
Definition at line 47 of file G4LEpp.cc.
View newest version in sPHENIX GitHub at line 47 of file G4LEpp.cc
Member Function Documentation
G4HadFinalState * G4LEpp::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) override virtual
Reimplemented from G4HadronElastic.
Definition at line 51 of file G4LEpp.cc.
View newest version in sPHENIX GitHub at line 51 of file G4LEpp.cc
References A(), G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), E, G4cout, G4endl, G4UniformRand, G4HadProjectile::Get4Momentum(), G4Nucleus::GetA_asInt(), G4HadProjectile::GetDefinition(), G4DynamicParticle::GetDefinition(), G4HadProjectile::GetKineticEnergy(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4HadProjectile::GetTotalEnergy(), G4DynamicParticle::GetTotalEnergy(), G4HadProjectile::GetTotalMomentum(), G4DynamicParticle::GetTotalMomentum(), G4Nucleus::GetZ_asInt(), GeV, halfpi, P, phi, G4Proton::Proton(), source.hepunit::proton_mass_c2, Q, G4Nucleus::ReturnTargetParticle(), SampleInvariantT(), G4DynamicParticle::SetDefinition(), G4HadFinalState::SetEnergyChange(), G4DynamicParticle::SetMomentum(), G4HadFinalState::SetMomentumChange(), t, G4HadronicInteraction::theParticleChange, twopi, CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, CLHEP::HepLorentzVector::x(), CLHEP::HepLorentzVector::y(), Z, and CLHEP::HepLorentzVector::z().
G4double G4LEpp::SampleInvariantT (const G4ParticleDefinition * p, G4double plab, G4int Z, G4int A) override virtual
Reimplemented from G4HadronElastic.
Definition at line 245 of file G4LEpp.cc.
View newest version in sPHENIX GitHub at line 245 of file G4LEpp.cc
References b, elab, G4UniformRand, G4ParticleDefinition::GetPDGMass(), GeV, NANGLE, NENERGY, pi, Sig, t, and theta().
Referenced by ApplyYourself().
Member Data Documentation
const G4float G4LEpp::dSigmax static private
Initial value:
= {
     63.9f, 29.9f, 14.5f, 8.97f, 7.23f, 6.66f, 6.30f,
     5.89f, 5.68f, 5.57f, 5.56f, 5.57f, 5.74f, 6.38f,
     7.66f, 9.65f, 12.4f, 15.6f, 18.0f, 20.1f, 22.0f, 23.8f,
     26.710f, 28.910f, 31.000f, 32.990f, 34.900f, 36.730f, 38.520f,
     40.270f, 43.680f, 46.950f, 50.100f, 53.160f, 55.880f, 58.820f,
     57.420f, 57.820f, 58.590f, 57.800f
 }
Definition at line 67 of file G4LEpp.hh.
View newest version in sPHENIX GitHub at line 67 of file G4LEpp.hh
const G4float G4LEpp::elab static private
Initial value:
= {
     0.100E-01f, 0.200E-01f, 0.400E-01f, 0.700E-01f, 0.100f, 0.120f, 0.140f,
     0.180f, 0.220f, 0.260f, 0.280f, 0.300f, 0.340f, 0.420f,
     0.520f, 0.620f, 0.700f, 0.800f, 0.900f, 1.00f, 1.10f, 1.20f,
     1.30f, 1.40f, 1.50f, 1.60f, 1.70f, 1.80f, 1.90f,
     2.00f, 2.20f, 2.40f, 2.60f, 2.80f, 3.00f, 3.40f,
     3.80f, 4.20f, 4.60f, 5.00f
 }
Definition at line 66 of file G4LEpp.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LEpp.hh
Referenced by SampleInvariantT().
const G4float G4LEpp::Sig static private
Definition at line 65 of file G4LEpp.hh.
View newest version in sPHENIX GitHub at line 65 of file G4LEpp.hh
Referenced by SampleInvariantT().
const G4float G4LEpp::Sigtot static private
Initial value:
= {
     396.f, 179.f, 80.7f, 44.5f, 32.8f, 29.0f, 26.9f,
     24.9f, 24.4f, 24.3f, 24.4f, 24.4f, 24.7f, 25.5f,
     26.4f, 26.1f, 25.6f, 25.1f, 24.4f, 23.4f, 22.4f, 21.5f,
     22.765f, 23.275f, 23.744f, 24.188f, 24.620f, 25.058f, 25.509f,
     25.981f, 26.984f, 28.055f, 29.242f, 30.608f, 32.026f, 34.457f,
     34.394f, 33.885f, 34.122f, 33.603f
 }
Definition at line 68 of file G4LEpp.hh.
View newest version in sPHENIX GitHub at line 68 of file G4LEpp.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4LEpp.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/include/G4LEppData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/coherent_elastic/src/G4LEpp.cc