ECCE @ EIC Software: G3Division Class Reference
G3Division Class Reference
#include <geant4/tree/geant4-10.6-release/source/g3tog4/include/G3Division.hh>
Public Member Functions
G3Division (G3DivType type, G3VolTableEntry *vte, G3VolTableEntry *mvte, G4int nofDivision, G4int iaxis, G4int nmed, G4double c0, G4double step)
G3Division (G3VolTableEntry *vte, G3VolTableEntry *mvte, const G3Division &division)
virtual ~G3Division ()
void UpdateVTE ()
void CreatePVReplica ()
Private Member Functions
void SetRangeAndAxis ()
void CreateSolid (G4String shape, G4double par[], G4int npar)
G3VolTableEntry * CreateEnvelope (G4String shape, G4double hi, G4double lo, G4double par[], G4int npar)
G3VolTableEntry * Dvn ()
G3VolTableEntry * Dvn2 ()
G3VolTableEntry * Dvt ()
G3VolTableEntry * Dvt2 ()
void Exception (G4String where, G4String what)
Private Attributes
G3DivType fType
G3VolTableEntry * fVTE
G3VolTableEntry * fMVTE
G4int fNofDivisions
G4int fIAxis
G4int fNmed
G4double fC0
G4double fStep
G4double fLowRange
G4double fHighRange
G4double fWidth
G4double fOffset
EAxis fAxis
Detailed Description
Definition at line 54 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 54 of file G3Division.hh
Constructor & Destructor Documentation
G3Division::G3Division (G3DivType type, G3VolTableEntry * vte, G3VolTableEntry * mvte, G4int nofDivision, G4int iaxis, G4int nmed, G4double c0, G4double step)
Definition at line 49 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 49 of file G3Division.cc
References fVTE, and G3VolTableEntry::SetHasNegPars().
G3Division::G3Division (G3VolTableEntry * vte, G3VolTableEntry * mvte, const G3Division & division)
Definition at line 69 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 69 of file G3Division.cc
References fAxis, fC0, fHighRange, fIAxis, fLowRange, fNmed, fNofDivisions, fOffset, fStep, fType, fVTE, fWidth, kXAxis, and G3VolTableEntry::SetHasNegPars().
G3Division::~G3Division () virtual
Definition at line 91 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 91 of file G3Division.cc
Member Function Documentation
G3VolTableEntry * G3Division::CreateEnvelope (G4String shape, G4double hi, G4double lo, G4double par[], G4int npar) private
Definition at line 437 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 437 of file G3Division.cc
References G3VolTableEntry::AddG3Pos(), cm, deg, Exception(), fIAxis, fMVTE, fNmed, fVTE, G4CreateVTE(), G3VolTableEntry::GetMasterClone(), G3VolTableEntry::GetName(), offset, pos(), rmax(), Rpar, x1, y1, and z1.
Referenced by Dvn2(), Dvt(), and Dvt2().
void G3Division::CreatePVReplica ()
Definition at line 127 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 127 of file G3Division.cc
References fAxis, fIAxis, fLowRange, fMVTE, fNofDivisions, fOffset, fVTE, fWidth, G4cout, G4endl, G3VolTableEntry::GetLV(), G3VolTableEntry::GetName(), G4LogicalVolume::GetName(), G3VolTableEntry::GetShape(), G4LogicalVolume::GetSolid(), G4ReflectionFactory::Instance(), G4ReflectionFactory::Place(), G4ReflectionFactory::Replicate(), CLHEP::Hep3Vector::setX(), and CLHEP::Hep3Vector::y().
Referenced by G3toG4BuildPVTree().
void G3Division::CreateSolid (G4String shape, G4double par[], G4int npar) private
Definition at line 614 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 614 of file G3Division.cc
References cm, deg, Exception(), FatalException, fIAxis, fOffset, fVTE, fWidth, G3toG4MakeSolid(), G4Exception(), G3VolTableEntry::GetName(), Rpar, G3VolTableEntry::SetHasNegPars(), G3VolTableEntry::SetNRpar(), and G3VolTableEntry::SetSolid().
Referenced by Dvn(), Dvn2(), Dvt(), and Dvt2().
G3VolTableEntry * G3Division::Dvn () private
Definition at line 786 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 786 of file G3Division.cc
References CreateSolid(), fHighRange, fLowRange, fMVTE, fNofDivisions, fWidth, G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), and Rpar.
Referenced by UpdateVTE().
G3VolTableEntry * G3Division::Dvn2 () private
Definition at line 802 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 802 of file G3Division.cc
References kdfinder::abs(), cm, CreateEnvelope(), CreateSolid(), deg, fAxis, fC0, fHighRange, fLowRange, fMVTE, fNofDivisions, fWidth, G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), kPhi, and Rpar.
Referenced by UpdateVTE().
G3VolTableEntry * G3Division::Dvt () private
Definition at line 830 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 830 of file G3Division.cc
References kdfinder::abs(), cm, CreateEnvelope(), CreateSolid(), deg, Acts::Test::delta, fAxis, fHighRange, fLowRange, fMVTE, fNofDivisions, fStep, fWidth, G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), kPhi, Rpar, and Acts::Test::step().
Referenced by UpdateVTE().
G3VolTableEntry * G3Division::Dvt2 () private
Definition at line 871 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 871 of file G3Division.cc
References kdfinder::abs(), cm, CreateEnvelope(), CreateSolid(), deg, Acts::Test::delta, fAxis, fC0, fHighRange, fLowRange, fMVTE, fNofDivisions, fStep, fWidth, G3VolTableEntry::GetNpar(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), kPhi, Rpar, and Acts::Test::step().
Referenced by UpdateVTE().
void G3Division::Exception (G4String where, G4String what) private
Definition at line 180 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 180 of file G3Division.cc
References FatalException, and G4Exception().
Referenced by CreateEnvelope(), CreateSolid(), and SetRangeAndAxis().
void G3Division::SetRangeAndAxis () private
Definition at line 189 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 189 of file G3Division.cc
References cm, deg, Exception(), FatalException, fAxis, fHighRange, fIAxis, fLowRange, fMVTE, G4cout, G4endl, G4Exception(), G3VolTableEntry::GetRpar(), G3VolTableEntry::GetShape(), kInfinity, kPhi, kRho, kXAxis, kYAxis, kZAxis, max, min, and Rpar.
Referenced by UpdateVTE().
void G3Division::UpdateVTE ()
Definition at line 96 of file G3Division.cc.
View newest version in sPHENIX GitHub at line 96 of file G3Division.cc
References G3VolTableEntry::AddDaughter(), G3VolTableEntry::AddMother(), Dvn(), Dvn2(), Dvt(), Dvt2(), fMVTE, fNmed, fType, fVTE, G3VolTableEntry::GetNmed(), G3VolTableEntry::HasNegPars(), kDvn, kDvn2, kDvt, kDvt2, G3VolTableEntry::ReplaceDaughter(), G3VolTableEntry::ReplaceMother(), G3VolTableEntry::SetNmed(), and SetRangeAndAxis().
Referenced by G4CloneDaughters(), G4CreateCloneVTEWithDivision(), and G4ProcessDaughters().
Member Data Documentation
EAxis G3Division::fAxis private
Definition at line 95 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 95 of file G3Division.hh
Referenced by CreatePVReplica(), Dvn2(), Dvt(), Dvt2(), G3Division(), and SetRangeAndAxis().
G4double G3Division::fC0 private
Definition at line 89 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 89 of file G3Division.hh
Referenced by Dvn2(), Dvt2(), and G3Division().
G4double G3Division::fHighRange private
Definition at line 92 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 92 of file G3Division.hh
Referenced by Dvn(), Dvn2(), Dvt(), Dvt2(), G3Division(), and SetRangeAndAxis().
G4int G3Division::fIAxis private
Definition at line 87 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 87 of file G3Division.hh
Referenced by CreateEnvelope(), CreatePVReplica(), CreateSolid(), G3Division(), and SetRangeAndAxis().
G4double G3Division::fLowRange private
Definition at line 91 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 91 of file G3Division.hh
Referenced by CreatePVReplica(), Dvn(), Dvn2(), Dvt(), Dvt2(), G3Division(), and SetRangeAndAxis().
G3VolTableEntry* G3Division::fMVTE private
Definition at line 85 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 85 of file G3Division.hh
Referenced by CreateEnvelope(), CreatePVReplica(), Dvn(), Dvn2(), Dvt(), Dvt2(), SetRangeAndAxis(), and UpdateVTE().
G4int G3Division::fNmed private
Definition at line 88 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 88 of file G3Division.hh
Referenced by CreateEnvelope(), G3Division(), and UpdateVTE().
G4int G3Division::fNofDivisions private
Definition at line 86 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 86 of file G3Division.hh
Referenced by CreatePVReplica(), Dvn(), Dvn2(), Dvt(), Dvt2(), and G3Division().
G4double G3Division::fOffset private
Definition at line 94 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 94 of file G3Division.hh
Referenced by CreatePVReplica(), CreateSolid(), and G3Division().
G4double G3Division::fStep private
Definition at line 90 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 90 of file G3Division.hh
Referenced by Dvt(), Dvt2(), and G3Division().
G3DivType G3Division::fType private
Definition at line 83 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 83 of file G3Division.hh
Referenced by G3Division(), and UpdateVTE().
G3VolTableEntry* G3Division::fVTE private
Definition at line 84 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 84 of file G3Division.hh
Referenced by CreateEnvelope(), CreatePVReplica(), CreateSolid(), G3Division(), and UpdateVTE().
G4double G3Division::fWidth private
Definition at line 93 of file G3Division.hh.
View newest version in sPHENIX GitHub at line 93 of file G3Division.hh
Referenced by CreatePVReplica(), CreateSolid(), Dvn(), Dvn2(), Dvt(), Dvt2(), and G3Division().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/g3tog4/include/G3Division.hh
geant4/tree/geant4-10.6-release/source/g3tog4/src/G3Division.cc