ECCE @ EIC Software: G4ParticleChangeForDecay Class Reference
G4ParticleChangeForDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForDecay.hh>
Public Member Functions
G4ParticleChangeForDecay ()
virtual ~G4ParticleChangeForDecay ()
G4bool operator== (const G4ParticleChangeForDecay &right) const
G4bool operator!= (const G4ParticleChangeForDecay &right) const
virtual G4Step * UpdateStepForAtRest (G4Step *Step)
virtual G4Step * UpdateStepForPostStep (G4Step *Step)
virtual void Initialize (const G4Track &)
void ProposeGlobalTime (G4double t)
void ProposeLocalTime (G4double t)
G4double GetGlobalTime (G4double timeDelay=0.0) const
G4double GetLocalTime (G4double timeDelay=0.0) const
const G4ThreeVector * GetPolarization () const
void ProposePolarization (G4double Px, G4double Py, G4double Pz)
void ProposePolarization (const G4ThreeVector &finalPoralization)
virtual void DumpInfo () const
virtual G4bool CheckIt (const G4Track &)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
virtual G4Step * UpdateStepForAlongStep (G4Step *Step)
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4ParticleChangeForDecay (const G4ParticleChangeForDecay &right)
G4ParticleChangeForDecay & operator= (const G4ParticleChangeForDecay &right)
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Protected Attributes
G4double theGlobalTime0
G4double theLocalTime0
G4double theTimeChange
G4ThreeVector thePolarizationChange
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Additional Inherited Members
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 53 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleChangeForDecay.hh
Constructor & Destructor Documentation
G4ParticleChangeForDecay::G4ParticleChangeForDecay ()
Definition at line 47 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleChangeForDecay.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChangeForDecay::~G4ParticleChangeForDecay () virtual
Definition at line 58 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleChangeForDecay.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChangeForDecay::G4ParticleChangeForDecay (const G4ParticleChangeForDecay & right) protected
Definition at line 67 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ParticleChangeForDecay.cc
References theGlobalTime0, theLocalTime0, thePolarizationChange, and theTimeChange.
Member Function Documentation
G4bool G4ParticleChangeForDecay::CheckIt (const G4Track & aTrack) virtual
Reimplemented from G4VParticleChange.
Definition at line 200 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 200 of file G4ParticleChangeForDecay.cc
References G4VParticleChange::accuracyForException, G4VParticleChange::accuracyForWarning, G4VParticleChange::CheckIt(), DumpInfo(), EventMustBeAborted, G4cout, G4endl, G4Exception(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4Track::GetLocalTime(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), m, MeV, ns, theGlobalTime0, theLocalTime0, theTimeChange, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by UpdateStepForAtRest().
void G4ParticleChangeForDecay::DumpInfo () const virtual
Reimplemented from G4VParticleChange.
Definition at line 185 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 185 of file G4ParticleChangeForDecay.cc
References G4VParticleChange::DumpInfo(), G4cout, G4endl, ns, theGlobalTime0, theLocalTime0, and theTimeChange.
Referenced by CheckIt().
G4double G4ParticleChangeForDecay::GetGlobalTime (G4double timeDelay = 0.0) const inline
Definition at line 131 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ParticleChangeForDecay.hh
References theGlobalTime0, theLocalTime0, and theTimeChange.
Referenced by UpdateStepForAtRest().
G4double G4ParticleChangeForDecay::GetLocalTime (G4double timeDelay = 0.0) const inline
Definition at line 144 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ParticleChangeForDecay.hh
References theTimeChange.
const G4ThreeVector * G4ParticleChangeForDecay::GetPolarization () const inline
Definition at line 151 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ParticleChangeForDecay.hh
References thePolarizationChange.
void G4ParticleChangeForDecay::Initialize (const G4Track & track) virtual
Reimplemented from G4VParticleChange.
Definition at line 123 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 123 of file G4ParticleChangeForDecay.cc
References G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4Track::GetLocalTime(), G4DynamicParticle::GetPolarization(), G4VParticleChange::Initialize(), theGlobalTime0, theLocalTime0, thePolarizationChange, and theTimeChange.
Referenced by G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4DecayWithSpin::PostStepDoIt(), and G4Decay::PostStepDoIt().
G4bool G4ParticleChangeForDecay::operator!= (const G4ParticleChangeForDecay & right) const
Definition at line 115 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 115 of file G4ParticleChangeForDecay.cc
G4ParticleChangeForDecay & G4ParticleChangeForDecay::operator= (const G4ParticleChangeForDecay & right) protected
Definition at line 76 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleChangeForDecay.cc
References G4cout, G4FastVector< Type, N >::SetElement(), theGlobalTime0, G4VParticleChange::theListOfSecondaries, G4VParticleChange::theLocalEnergyDeposit, theLocalTime0, G4VParticleChange::theNumberOfSecondaries, thePolarizationChange, G4VParticleChange::theStatusChange, G4VParticleChange::theSteppingControlFlag, theTimeChange, G4VParticleChange::theTrueStepLength, and G4VParticleChange::verboseLevel.
G4bool G4ParticleChangeForDecay::operator== (const G4ParticleChangeForDecay & right) const
Definition at line 110 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleChangeForDecay.cc
void G4ParticleChangeForDecay::ProposeGlobalTime (G4double t) inline
Definition at line 125 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ParticleChangeForDecay.hh
References theGlobalTime0, theLocalTime0, and theTimeChange.
Referenced by G4UnknownDecay::DecayIt().
void G4ParticleChangeForDecay::ProposeLocalTime (G4double t) inline
Definition at line 138 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 138 of file G4ParticleChangeForDecay.hh
References t, and theTimeChange.
Referenced by G4RadioactiveDecayBase::DecayAnalog(), G4Decay::DecayIt(), G4Radioactivation::DecayIt(), and G4RadioactiveDecay::DecayIt().
void G4ParticleChangeForDecay::ProposePolarization (G4double Px, G4double Py, G4double Pz) inline
Definition at line 163 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 163 of file G4ParticleChangeForDecay.hh
References CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and thePolarizationChange.
Referenced by G4DecayWithSpin::AtRestDoIt(), and G4DecayWithSpin::PostStepDoIt().
void G4ParticleChangeForDecay::ProposePolarization (const G4ThreeVector & finalPoralization) inline
Definition at line 157 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParticleChangeForDecay.hh
References thePolarizationChange.
G4Step * G4ParticleChangeForDecay::UpdateStepForAtRest (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 160 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 160 of file G4ParticleChangeForDecay.cc
References G4StepPoint::AddProperTime(), CheckIt(), G4VParticleChange::debugFlag, GetGlobalTime(), G4Step::GetPostStepPoint(), G4Step::GetTrack(), G4VParticleChange::isParentWeightProposed, G4StepPoint::SetGlobalTime(), G4StepPoint::SetLocalTime(), G4StepPoint::SetPolarization(), G4StepPoint::SetWeight(), theLocalTime0, G4VParticleChange::theParentWeight, thePolarizationChange, theTimeChange, and G4VParticleChange::UpdateStepInfo().
G4Step * G4ParticleChangeForDecay::UpdateStepForPostStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 145 of file G4ParticleChangeForDecay.cc.
View newest version in sPHENIX GitHub at line 145 of file G4ParticleChangeForDecay.cc
References G4Step::GetPostStepPoint(), G4VParticleChange::isParentWeightProposed, G4StepPoint::SetPolarization(), G4StepPoint::SetWeight(), G4VParticleChange::theParentWeight, thePolarizationChange, and G4VParticleChange::UpdateStepInfo().
Member Data Documentation
G4double G4ParticleChangeForDecay::theGlobalTime0 protected
Definition at line 108 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleChangeForDecay.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChangeForDecay(), GetGlobalTime(), Initialize(), operator=(), and ProposeGlobalTime().
G4double G4ParticleChangeForDecay::theLocalTime0 protected
Definition at line 110 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleChangeForDecay.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChangeForDecay(), GetGlobalTime(), Initialize(), operator=(), ProposeGlobalTime(), and UpdateStepForAtRest().
G4ThreeVector G4ParticleChangeForDecay::thePolarizationChange protected
Definition at line 116 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ParticleChangeForDecay.hh
Referenced by G4ParticleChangeForDecay(), GetPolarization(), Initialize(), operator=(), ProposePolarization(), UpdateStepForAtRest(), and UpdateStepForPostStep().
G4double G4ParticleChangeForDecay::theTimeChange protected
Definition at line 113 of file G4ParticleChangeForDecay.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleChangeForDecay.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChangeForDecay(), GetGlobalTime(), GetLocalTime(), Initialize(), operator=(), ProposeGlobalTime(), ProposeLocalTime(), and UpdateStepForAtRest().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForDecay.hh
geant4/tree/geant4-10.6-release/source/track/src/G4ParticleChangeForDecay.cc