ECCE @ EIC Software: G4ErrorCylSurfaceTarget Class Reference
G4ErrorCylSurfaceTarget Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4ErrorCylSurfaceTarget.hh>
Public Member Functions
G4ErrorCylSurfaceTarget (const G4double &radius, const G4ThreeVector &trans=G4ThreeVector(), const G4RotationMatrix &rotm=G4RotationMatrix())
G4ErrorCylSurfaceTarget (const G4double &radius, const G4AffineTransform &trans)
~G4ErrorCylSurfaceTarget ()
virtual G4ThreeVector IntersectLocal (const G4ThreeVector &point, const G4ThreeVector &direc) const
virtual G4double GetDistanceFromPoint (const G4ThreeVector &point, const G4ThreeVector &direc) const
virtual G4double GetDistanceFromPoint (const G4ThreeVector &point) const
virtual G4Plane3D GetTangentPlane (const G4ThreeVector &point) const
virtual void Dump (const G4String &msg) const
Public Member Functions inherited from G4ErrorSurfaceTarget
G4ErrorSurfaceTarget ()
virtual ~G4ErrorSurfaceTarget ()
Public Member Functions inherited from G4ErrorTanPlaneTarget
G4ErrorTanPlaneTarget ()
virtual ~G4ErrorTanPlaneTarget ()
Public Member Functions inherited from G4ErrorTarget
G4ErrorTarget ()
virtual ~G4ErrorTarget ()
virtual G4bool TargetReached (const G4Step *)
G4ErrorTargetType GetType () const
Private Attributes
G4double fradius
G4AffineTransform ftransform
Additional Inherited Members
Protected Attributes inherited from G4ErrorTarget
G4ErrorTargetType theType
Detailed Description
Definition at line 44 of file G4ErrorCylSurfaceTarget.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ErrorCylSurfaceTarget.hh
Constructor & Destructor Documentation
G4ErrorCylSurfaceTarget::G4ErrorCylSurfaceTarget (const G4double & radius, const G4ThreeVector & trans = G4ThreeVector(), const G4RotationMatrix & rotm = G4RotationMatrix())
Definition at line 44 of file G4ErrorCylSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ErrorCylSurfaceTarget.cc
References Dump(), ftransform, G4ErrorTarget_CylindricalSurface, CLHEP::HepRotation::inverse(), G4ErrorTarget::theType, and G4ErrorPropagatorData::verbose().
G4ErrorCylSurfaceTarget::G4ErrorCylSurfaceTarget (const G4double & radius, const G4AffineTransform & trans)
Definition at line 63 of file G4ErrorCylSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 63 of file G4ErrorCylSurfaceTarget.cc
References Dump(), G4ErrorTarget_CylindricalSurface, G4ErrorTarget::theType, and G4ErrorPropagatorData::verbose().
G4ErrorCylSurfaceTarget::~G4ErrorCylSurfaceTarget ()
Definition at line 79 of file G4ErrorCylSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ErrorCylSurfaceTarget.cc
Member Function Documentation
void G4ErrorCylSurfaceTarget::Dump (const G4String & msg) const virtual
Implements G4ErrorSurfaceTarget.
Definition at line 220 of file G4ErrorCylSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 220 of file G4ErrorCylSurfaceTarget.cc
References fradius, ftransform, G4cout, G4endl, G4AffineTransform::NetRotation(), and G4AffineTransform::NetTranslation().
Referenced by G4ErrorCylSurfaceTarget(), GetDistanceFromPoint(), and IntersectLocal().
G4double G4ErrorCylSurfaceTarget::GetDistanceFromPoint (const G4ThreeVector & point, const G4ThreeVector & direc) const virtual
Implements G4ErrorSurfaceTarget.
Definition at line 86 of file G4ErrorCylSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 86 of file G4ErrorCylSurfaceTarget.cc
References Dump(), FatalException, ftransform, G4cout, G4endl, G4Exception(), IntersectLocal(), CLHEP::Hep3Vector::mag(), G4AffineTransform::TransformAxis(), G4AffineTransform::TransformPoint(), and G4ErrorPropagatorData::verbose().
G4double G4ErrorCylSurfaceTarget::GetDistanceFromPoint (const G4ThreeVector & point) const virtual
Implements G4ErrorSurfaceTarget.
Definition at line 120 of file G4ErrorCylSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 120 of file G4ErrorCylSurfaceTarget.cc
References Dump(), fradius, ftransform, G4cout, G4endl, CLHEP::Hep3Vector::perp(), G4AffineTransform::TransformPoint(), and G4ErrorPropagatorData::verbose().
G4Plane3D G4ErrorCylSurfaceTarget::GetTangentPlane (const G4ThreeVector & point) const virtual
Implements G4ErrorSurfaceTarget.
Definition at line 193 of file G4ErrorCylSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 193 of file G4ErrorCylSurfaceTarget.cc
References fradius, ftransform, G4endl, G4Exception(), G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), JustWarning, message(), G4AffineTransform::NetTranslation(), CLHEP::normal(), CLHEP::Hep3Vector::perp(), and G4AffineTransform::TransformPoint().
G4ThreeVector G4ErrorCylSurfaceTarget::IntersectLocal (const G4ThreeVector & point, const G4ThreeVector & direc) const virtual
Definition at line 140 of file G4ErrorCylSurfaceTarget.cc.
View newest version in sPHENIX GitHub at line 140 of file G4ErrorCylSurfaceTarget.cc
References Dump(), fradius, G4cout, G4endl, G4Exception(), JustWarning, kInfinity, G4InuclParticleNames::lambda, CLHEP::Hep3Vector::mag(), message(), CLHEP::Hep3Vector::perp(), G4ErrorPropagatorData::verbose(), CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by GetDistanceFromPoint().
Member Data Documentation
G4double G4ErrorCylSurfaceTarget::fradius private
Definition at line 80 of file G4ErrorCylSurfaceTarget.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ErrorCylSurfaceTarget.hh
Referenced by Dump(), GetDistanceFromPoint(), GetTangentPlane(), and IntersectLocal().
G4AffineTransform G4ErrorCylSurfaceTarget::ftransform private
Definition at line 81 of file G4ErrorCylSurfaceTarget.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ErrorCylSurfaceTarget.hh
Referenced by Dump(), G4ErrorCylSurfaceTarget(), GetDistanceFromPoint(), and GetTangentPlane().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4ErrorCylSurfaceTarget.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4ErrorCylSurfaceTarget.cc