ECCE @ EIC Software: G4MuonicAtomHelper Class Reference
G4MuonicAtomHelper Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4MuonicAtomHelper.hh>
Static Public Member Functions
static G4MuonicAtom * ConstructMuonicAtom (G4String name, G4int encoding, G4Ions const *baseion)
static G4double GetMuonCaptureRate (G4int Z, G4int A)
static G4double GetMuonDecayRate (G4int Z)
static G4double GetMuonZeff (G4int Z)
static G4double GetKShellEnergy (G4double A)
static G4double GetLinApprox (G4int N, const G4double *const X, const G4double *const Y, G4double Xuser)
Detailed Description
Definition at line 44 of file G4MuonicAtomHelper.hh.
View newest version in sPHENIX GitHub at line 44 of file G4MuonicAtomHelper.hh
Member Function Documentation
G4MuonicAtom * G4MuonicAtomHelper::ConstructMuonicAtom (G4String name, G4int encoding, G4Ions const * baseion) static
Definition at line 48 of file G4MuonicAtomHelper.cc.
View newest version in sPHENIX GitHub at line 48 of file G4MuonicAtomHelper.cc
References A(), charge, G4ParticleTable::FindParticle(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetBaryonNumber(), GetKShellEnergy(), G4ParticleDefinition::GetLeptonNumber(), GetMuonCaptureRate(), GetMuonDecayRate(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGiConjugation(), G4ParticleDefinition::GetPDGiGParity(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiIsospin3(), G4ParticleDefinition::GetPDGiParity(), G4ParticleDefinition::GetPDGiSpin(), G4ParticleDefinition::GetPDGMagneticMoment(), G4ParticleDefinition::GetPDGMass(), mass, G4ParticleDefinition::SetPDGMagneticMoment(), and Z.
Referenced by G4IonTable::GetMuonicAtom().
G4double G4MuonicAtomHelper::GetKShellEnergy (G4double A) static
Definition at line 347 of file G4MuonicAtomHelper.cc.
View newest version in sPHENIX GitHub at line 347 of file G4MuonicAtomHelper.cc
References GetLinApprox().
Referenced by ConstructMuonicAtom(), and G4MuonicAtomDecay::DecayIt().
G4double G4MuonicAtomHelper::GetLinApprox (G4int N, const G4double *const X, const G4double *const Y, G4double Xuser) static
Definition at line 371 of file G4MuonicAtomHelper.cc.
View newest version in sPHENIX GitHub at line 371 of file G4MuonicAtomHelper.cc
References N.
Referenced by GetKShellEnergy().
G4double G4MuonicAtomHelper::GetMuonCaptureRate (G4int Z, G4int A) static
Definition at line 105 of file G4MuonicAtomHelper.cc.
View newest version in sPHENIX GitHub at line 105 of file G4MuonicAtomHelper.cc
References A(), kdfinder::abs(), GetMuonZeff(), G4InuclParticleNames::lambda, microsecond, r1, r2, t1, and Z.
Referenced by ConstructMuonicAtom().
G4double G4MuonicAtomHelper::GetMuonDecayRate (G4int Z) static
Definition at line 293 of file G4MuonicAtomHelper.cc.
View newest version in sPHENIX GitHub at line 293 of file G4MuonicAtomHelper.cc
References source.hepunit::fine_structure_const, GetMuonZeff(), G4InuclParticleNames::lambda, microsecond, x, and Z.
Referenced by ConstructMuonicAtom().
G4double G4MuonicAtomHelper::GetMuonZeff (G4int Z) static
Definition at line 261 of file G4MuonicAtomHelper.cc.
View newest version in sPHENIX GitHub at line 261 of file G4MuonicAtomHelper.cc
References maxZ, and Z.
Referenced by GetMuonCaptureRate(), and GetMuonDecayRate().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4MuonicAtomHelper.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4MuonicAtomHelper.cc