ECCE @ EIC Software: G4VTwistSurface Class Reference
G4VTwistSurface Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistSurface.hh>
Classes
class Boundary
class CurrentStatus
class G4SurfCurNormal
class G4SurfSideQuery
Public Types
enum EValidate { kDontValidate = 0, kValidateWithTol = 1, kValidateWithoutTol = 2, kUninitialized = 3 }
Public Member Functions
G4VTwistSurface (const G4String &name)
G4VTwistSurface (const G4String &name, const G4RotationMatrix &rot, const G4ThreeVector &tlate, G4int handedness, const EAxis axis1, const EAxis axis2, G4double axis0min=-kInfinity, G4double axis1min=-kInfinity, G4double axis0max=kInfinity, G4double axis1max=kInfinity)
virtual ~G4VTwistSurface ()
virtual G4int AmIOnLeftSide (const G4ThreeVector &me, const G4ThreeVector &vec, G4bool withTol=true)
virtual G4double DistanceToBoundary (G4int areacode, G4ThreeVector &xx, const G4ThreeVector &p)
virtual G4double DistanceToIn (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector &gxxbest)
virtual G4double DistanceToOut (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector &gxxbest)
virtual G4double DistanceTo (const G4ThreeVector &gp, G4ThreeVector &gxx)
virtual G4int DistanceToSurface (const G4ThreeVector &gp, const G4ThreeVector &gv, G4ThreeVector gxx[], G4double distance[], G4int areacode[], G4bool isvalid[], EValidate validate=kValidateWithTol)=0
virtual G4int DistanceToSurface (const G4ThreeVector &gp, G4ThreeVector gxx[], G4double distance[], G4int areacode[])=0
void DebugPrint () const
virtual G4ThreeVector GetNormal (const G4ThreeVector &xx, G4bool isGlobal)=0
virtual G4String GetName () const
virtual void GetBoundaryParameters (const G4int &areacode, G4ThreeVector &d, G4ThreeVector &x0, G4int &boundarytype) const
virtual G4ThreeVector GetBoundaryAtPZ (G4int areacode, const G4ThreeVector &p) const
G4double DistanceToPlaneWithV (const G4ThreeVector &p, const G4ThreeVector &v, const G4ThreeVector &x0, const G4ThreeVector &n0, G4ThreeVector &xx)
G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &n0, G4ThreeVector &xx)
G4double DistanceToPlane (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &t1, const G4ThreeVector &t2, G4ThreeVector &xx, G4ThreeVector &n)
G4double DistanceToLine (const G4ThreeVector &p, const G4ThreeVector &x0, const G4ThreeVector &d, G4ThreeVector &xx)
G4bool IsAxis0 (G4int areacode) const
G4bool IsAxis1 (G4int areacode) const
G4bool IsOutside (G4int areacode) const
G4bool IsInside (G4int areacode, G4bool testbitmode=false) const
G4bool IsBoundary (G4int areacode, G4bool testbitmode=false) const
G4bool IsCorner (G4int areacode, G4bool testbitmode=false) const
G4bool IsValidNorm () const
G4bool IsSameBoundary (G4VTwistSurface *surface1, G4int areacode1, G4VTwistSurface *surface2, G4int areacode2) const
G4int GetAxisType (G4int areacode, G4int whichaxis) const
G4ThreeVector ComputeGlobalPoint (const G4ThreeVector &lp) const
G4ThreeVector ComputeLocalPoint (const G4ThreeVector &gp) const
G4ThreeVector ComputeGlobalDirection (const G4ThreeVector &lp) const
G4ThreeVector ComputeLocalDirection (const G4ThreeVector &gp) const
void SetAxis (G4int i, const EAxis axis)
void SetNeighbours (G4VTwistSurface *ax0min, G4VTwistSurface *ax1min, G4VTwistSurface *ax0max, G4VTwistSurface *ax1max)
virtual G4ThreeVector SurfacePoint (G4double, G4double, G4bool isGlobal=false)=0
virtual G4double GetBoundaryMin (G4double)=0
virtual G4double GetBoundaryMax (G4double)=0
virtual G4double GetSurfaceArea ()=0
virtual void GetFacets (G4int m, G4int n, G4double xyz[][3], G4int faces[][4], G4int iside)=0
G4int GetNode (G4int i, G4int j, G4int m, G4int n, G4int iside)
G4int GetFace (G4int i, G4int j, G4int m, G4int n, G4int iside)
G4int GetEdgeVisibility (G4int i, G4int j, G4int m, G4int n, G4int number, G4int orientation)
G4VTwistSurface (__void__ &)
Static Public Attributes
static const G4int sOutside = 0x00000000
static const G4int sInside = 0x10000000
static const G4int sBoundary = 0x20000000
static const G4int sCorner = 0x40000000
static const G4int sC0Min1Min = 0x40000101
static const G4int sC0Max1Min = 0x40000201
static const G4int sC0Max1Max = 0x40000202
static const G4int sC0Min1Max = 0x40000102
static const G4int sAxisMin = 0x00000101
static const G4int sAxisMax = 0x00000202
static const G4int sAxisX = 0x00000404
static const G4int sAxisY = 0x00000808
static const G4int sAxisZ = 0x00000C0C
static const G4int sAxisRho = 0x00001010
static const G4int sAxisPhi = 0x00001414
static const G4int sAxis0 = 0x0000FF00
static const G4int sAxis1 = 0x000000FF
static const G4int sSizeMask = 0x00000303
static const G4int sAxisMask = 0x0000FCFC
static const G4int sAreaMask = 0XF0000000
Protected Member Functions
G4VTwistSurface ** GetNeighbours ()
G4int GetNeighbours (G4int areacode, G4VTwistSurface *surfaces[])
G4ThreeVector GetCorner (G4int areacode) const
void GetBoundaryAxis (G4int areacode, EAxis axis[]) const
void GetBoundaryLimit (G4int areacode, G4double limit[]) const
virtual G4int GetAreaCode (const G4ThreeVector &xx, G4bool withtol=true)=0
virtual void SetBoundary (const G4int &axiscode, const G4ThreeVector &direction, const G4ThreeVector &x0, const G4int &boundarytype)
void SetCorner (G4int areacode, G4double x, G4double y, G4double z)
Protected Attributes
EAxis fAxis [2]
G4double fAxisMin [2]
G4double fAxisMax [2]
CurrentStatus fCurStatWithV
CurrentStatus fCurStat
G4RotationMatrix fRot
G4ThreeVector fTrans
G4int fHandedness
G4SurfCurNormal fCurrentNormal
G4bool fIsValidNorm
G4double kCarTolerance
Private Member Functions
virtual void SetBoundaries ()=0
virtual void SetCorners ()=0
Private Attributes
G4VTwistSurface * fNeighbours [4]
G4ThreeVector fCorners [4]
Boundary fBoundaries [4]
G4String fName
G4SurfSideQuery fAmIOnLeftSide
Detailed Description
Definition at line 48 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VTwistSurface.hh
Member Enumeration Documentation
enum G4VTwistSurface::EValidate
Enumerator:
kDontValidate
kValidateWithTol
kValidateWithoutTol
kUninitialized
Definition at line 52 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 52 of file G4VTwistSurface.hh
Constructor & Destructor Documentation
G4VTwistSurface::G4VTwistSurface (const G4String & name)
Definition at line 64 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VTwistSurface.cc
References fAmIOnLeftSide, fAxis, fAxisMax, fAxisMin, fCorners, fCurrentNormal, fHandedness, fNeighbours, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, kInfinity, kUndefined, G4VTwistSurface::G4SurfSideQuery::me, G4VTwistSurface::G4SurfCurNormal::p, CLHEP::Hep3Vector::set(), and G4VTwistSurface::G4SurfSideQuery::vec.
G4VTwistSurface::G4VTwistSurface (const G4String & name, const G4RotationMatrix & rot, const G4ThreeVector & tlate, G4int handedness, const EAxis axis1, const EAxis axis2, G4double axis0min = -kInfinity, G4double axis1min = -kInfinity, G4double axis0max = kInfinity, G4double axis1max = kInfinity)
Definition at line 89 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 89 of file G4VTwistSurface.cc
References fAmIOnLeftSide, fAxis, fAxisMax, fAxisMin, fCorners, fCurrentNormal, fHandedness, fNeighbours, fRot, fTrans, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, kInfinity, G4VTwistSurface::G4SurfSideQuery::me, G4VTwistSurface::G4SurfCurNormal::p, CLHEP::Hep3Vector::set(), and G4VTwistSurface::G4SurfSideQuery::vec.
G4VTwistSurface::~G4VTwistSurface () virtual
Definition at line 140 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 140 of file G4VTwistSurface.cc
G4VTwistSurface::G4VTwistSurface (__void__ &)
Definition at line 127 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 127 of file G4VTwistSurface.cc
References fAxis, fAxisMax, fAxisMin, fNeighbours, and kXAxis.
Member Function Documentation
G4int G4VTwistSurface::AmIOnLeftSide (const G4ThreeVector & me, const G4ThreeVector & vec, G4bool withTol = true) virtual
Definition at line 147 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 147 of file G4VTwistSurface.cc
References G4VTwistSurface::G4SurfSideQuery::amIOnLeftSide, CLHEP::Hep3Vector::cross(), fAmIOnLeftSide, fName, G4cout, G4endl, G4GeometryTolerance::GetAngularTolerance(), G4GeometryTolerance::GetInstance(), G4VTwistSurface::G4SurfSideQuery::me, CLHEP::HepRotation::rotateZ(), G4VTwistSurface::G4SurfSideQuery::vec, G4VTwistSurface::G4SurfSideQuery::withTol, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by G4TwistTubsSide::DistanceToSurface(), G4TwistTubsFlatSide::GetAreaCode(), and G4TwistTubsHypeSide::GetAreaCodeInPhi().
G4ThreeVector G4VTwistSurface::ComputeGlobalDirection (const G4ThreeVector & lp) const inline
Referenced by G4TwistTrapFlatSide::GetNormal(), G4TwistTrapAlphaSide::GetNormal(), G4TwistTrapParallelSide::GetNormal(), G4TwistBoxSide::GetNormal(), G4TwistTubsFlatSide::GetNormal(), G4TwistTubsSide::GetNormal(), G4TwistTubsHypeSide::GetNormal(), and IsSameBoundary().
G4ThreeVector G4VTwistSurface::ComputeGlobalPoint (const G4ThreeVector & lp) const inline
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), and IsSameBoundary().
G4ThreeVector G4VTwistSurface::ComputeLocalDirection (const G4ThreeVector & gp) const inline
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), and G4TwistTubsHypeSide::GetNormal().
G4ThreeVector G4VTwistSurface::ComputeLocalPoint (const G4ThreeVector & gp) const inline
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), G4TwistTrapAlphaSide::GetNormal(), G4TwistBoxSide::GetNormal(), G4TwistTrapParallelSide::GetNormal(), G4TwistTubsSide::GetNormal(), G4TwistTubsHypeSide::GetNormal(), and G4TwistTubsHypeSide::Inside().
void G4VTwistSurface::DebugPrint () const
Definition at line 1139 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1139 of file G4VTwistSurface.cc
References A(), B(), C(), D(), fAxis, fAxisMax, fAxisMin, fName, fRot, fTrans, G4cout, G4endl, GetCorner(), sC0Max1Max, sC0Max1Min, sC0Min1Max, and sC0Min1Min.
G4double G4VTwistSurface::DistanceTo (const G4ThreeVector & gp, G4ThreeVector & gxx) virtual
Definition at line 577 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 577 of file G4VTwistSurface.cc
References DistanceToSurface(), fName, G4cout, G4endl, G4VSURFACENXX, kInfinity, and sOutside.
Referenced by G4VTwistedFaceted::DistanceToIn(), G4TwistedTubs::DistanceToIn(), G4VTwistedFaceted::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4VTwistedFaceted::SurfaceNormal(), and G4TwistedTubs::SurfaceNormal().
G4double G4VTwistSurface::DistanceToBoundary (G4int areacode, G4ThreeVector & xx, const G4ThreeVector & p) virtual
Definition at line 231 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 231 of file G4VTwistSurface.cc
References d, DistanceToLine(), FatalException, G4endl, G4Exception(), GetBoundaryParameters(), CLHEP::Hep3Vector::getRho(), IsAxis0(), IsAxis1(), kInfinity, message(), sAxisPhi, CLHEP::Hep3Vector::set(), t, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4TwistTubsSide::DistanceToSurface().
G4double G4VTwistSurface::DistanceToIn (const G4ThreeVector & gp, const G4ThreeVector & gv, G4ThreeVector & gxxbest) virtual
Definition at line 290 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 290 of file G4VTwistSurface.cc
References DistanceToSurface(), false, fName, G4cout, G4endl, G4VSURFACENXX, GetNeighbours(), GetNormal(), IsInside(), IsSameBoundary(), k, kInfinity, kValidateWithTol, CLHEP::normal(), and sOutside.
Referenced by G4VTwistedFaceted::DistanceToIn(), and G4TwistedTubs::DistanceToIn().
G4double G4VTwistSurface::DistanceToLine (const G4ThreeVector & p, const G4ThreeVector & x0, const G4ThreeVector & d, G4ThreeVector & xx) inline
Referenced by DistanceToBoundary(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
G4double G4VTwistSurface::DistanceToOut (const G4ThreeVector & gp, const G4ThreeVector & gv, G4ThreeVector & gxxbest) virtual
Definition at line 494 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 494 of file G4VTwistSurface.cc
References DistanceToSurface(), false, fName, G4cout, G4endl, G4VSURFACENXX, GetNormal(), kInfinity, kValidateWithTol, CLHEP::normal(), and sOutside.
Referenced by G4VTwistedFaceted::DistanceToOut(), and G4TwistedTubs::DistanceToOut().
G4double G4VTwistSurface::DistanceToPlane (const G4ThreeVector & p, const G4ThreeVector & x0, const G4ThreeVector & n0, G4ThreeVector & xx) inline
Referenced by G4TwistTubsSide::DistanceToPlane(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), and G4TwistTubsSide::DistanceToSurface().
G4double G4VTwistSurface::DistanceToPlane (const G4ThreeVector & p, const G4ThreeVector & x0, const G4ThreeVector & t1, const G4ThreeVector & t2, G4ThreeVector & xx, G4ThreeVector & n) inline
G4double G4VTwistSurface::DistanceToPlaneWithV (const G4ThreeVector & p, const G4ThreeVector & v, const G4ThreeVector & x0, const G4ThreeVector & n0, G4ThreeVector & xx) inline
Referenced by G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), and G4TwistTubsSide::DistanceToSurface().
virtual G4int G4VTwistSurface::DistanceToSurface (const G4ThreeVector & gp, const G4ThreeVector & gv, G4ThreeVector gxx[], G4double distance[], G4int areacode[], G4bool isvalid[], EValidate validate = kValidateWithTol) pure virtual
Implemented in G4TwistTubsHypeSide, G4TwistTubsSide, G4TwistTubsFlatSide, G4TwistBoxSide, G4TwistTrapAlphaSide, G4TwistTrapParallelSide, and G4TwistTrapFlatSide.
Referenced by DistanceTo(), DistanceToIn(), and DistanceToOut().
virtual G4int G4VTwistSurface::DistanceToSurface (const G4ThreeVector & gp, G4ThreeVector gxx[], G4double distance[], G4int areacode[]) pure virtual
Implemented in G4TwistTubsHypeSide, G4TwistTubsSide, G4TwistTubsFlatSide, G4TwistBoxSide, G4TwistTrapAlphaSide, G4TwistTrapParallelSide, and G4TwistTrapFlatSide.
virtual G4int G4VTwistSurface::GetAreaCode (const G4ThreeVector & xx, G4bool withtol = true) protected pure virtual
Implemented in G4TwistTubsSide, G4TwistTubsHypeSide, G4TwistTubsFlatSide, G4TwistTrapAlphaSide, G4TwistTrapFlatSide, G4TwistBoxSide, and G4TwistTrapParallelSide.
G4int G4VTwistSurface::GetAxisType (G4int areacode, G4int whichaxis) const inline
G4ThreeVector G4VTwistSurface::GetBoundaryAtPZ (G4int areacode, const G4ThreeVector & p) const virtual
Definition at line 698 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 698 of file G4VTwistSurface.cc
References d, FatalException, fBoundaries, G4endl, G4Exception(), GetBoundaryParameters(), message(), sAxis0, sAxis1, sAxisPhi, sAxisRho, and CLHEP::Hep3Vector::z().
Referenced by G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::GetAreaCodeInPhi(), G4TwistTubsHypeSide::GetBoundaryMax(), and G4TwistTubsHypeSide::GetBoundaryMin().
void G4VTwistSurface::GetBoundaryAxis (G4int areacode, EAxis axis[]) const protected
Definition at line 783 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 783 of file G4VTwistSurface.cc
References FatalException, G4endl, G4Exception(), kPhi, kRho, kXAxis, kYAxis, kZAxis, message(), sAxis0, sAxis1, sAxisMask, sAxisPhi, sAxisRho, sAxisX, sAxisY, sAxisZ, and sBoundary.
void G4VTwistSurface::GetBoundaryLimit (G4int areacode, G4double limit[]) const protected
Definition at line 825 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 825 of file G4VTwistSurface.cc
References fAxisMax, fAxisMin, G4endl, G4Exception(), JustWarning, message(), sAxis0, sAxis1, sAxisMax, sAxisMin, sBoundary, sC0Max1Max, sC0Max1Min, sC0Min1Max, sC0Min1Min, and sCorner.
virtual G4double G4VTwistSurface::GetBoundaryMax (G4double) pure virtual
Implemented in G4TwistTrapAlphaSide, G4TwistBoxSide, G4TwistTrapParallelSide, G4TwistTubsHypeSide, G4TwistTubsSide, G4TwistTubsFlatSide, and G4TwistTrapFlatSide.
Referenced by G4VTwistedFaceted::GetPointOnSurface(), and G4TwistedTubs::GetPointOnSurface().
virtual G4double G4VTwistSurface::GetBoundaryMin (G4double) pure virtual
Implemented in G4TwistTrapAlphaSide, G4TwistBoxSide, G4TwistTrapParallelSide, G4TwistTubsHypeSide, G4TwistTubsSide, G4TwistTubsFlatSide, and G4TwistTrapFlatSide.
Referenced by G4VTwistedFaceted::GetPointOnSurface(), and G4TwistedTubs::GetPointOnSurface().
void G4VTwistSurface::GetBoundaryParameters (const G4int & areacode, G4ThreeVector & d, G4ThreeVector & x0, G4int & boundarytype) const virtual
Definition at line 668 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 668 of file G4VTwistSurface.cc
References FatalException, fBoundaries, G4endl, G4Exception(), and message().
Referenced by DistanceToBoundary(), G4TwistTubsSide::DistanceToSurface(), GetBoundaryAtPZ(), and IsSameBoundary().
G4ThreeVector G4VTwistSurface::GetCorner (G4int areacode) const inline protected
Referenced by DebugPrint(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsFlatSide::GetBoundaryMax(), G4TwistTubsFlatSide::GetBoundaryMin(), IsSameBoundary(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), and G4TwistTubsSide::SetBoundaries().
G4int G4VTwistSurface::GetEdgeVisibility (G4int i, G4int j, G4int m, G4int n, G4int number, G4int orientation)
Definition at line 1031 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 1031 of file G4VTwistSurface.cc
References FatalException, G4Exception(), GetName(), and message().
Referenced by G4TwistTrapFlatSide::GetFacets(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistTrapParallelSide::GetFacets(), G4TwistBoxSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), and G4TwistTrapAlphaSide::GetFacets().
G4int G4VTwistSurface::GetFace (G4int i, G4int j, G4int m, G4int n, G4int iside)
Definition at line 906 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 906 of file G4VTwistSurface.cc
References FatalException, G4endl, G4Exception(), GetName(), and message().
Referenced by G4TwistTrapFlatSide::GetFacets(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistTrapParallelSide::GetFacets(), G4TwistBoxSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), and G4TwistTrapAlphaSide::GetFacets().
virtual void G4VTwistSurface::GetFacets (G4int m, G4int n, G4double xyz[][3], G4int faces[][4], G4int iside) pure virtual
Implemented in G4TwistTrapAlphaSide, G4TwistBoxSide, G4TwistTrapParallelSide, G4TwistTubsHypeSide, G4TwistTubsSide, G4TwistTubsFlatSide, and G4TwistTrapFlatSide.
Referenced by G4VTwistedFaceted::CreatePolyhedron(), and G4TwistedTubs::CreatePolyhedron().
virtual G4String G4VTwistSurface::GetName (void) const inline virtual
Definition at line 107 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 107 of file G4VTwistSurface.hh
References fName.
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistBoxSide::G4TwistBoxSide(), GetEdgeVisibility(), GetFace(), GetNode(), and G4TwistTubsHypeSide::Inside().
G4VTwistSurface** G4VTwistSurface::GetNeighbours () inline protected
Definition at line 183 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 183 of file G4VTwistSurface.hh
References fNeighbours.
Referenced by DistanceToIn().
G4int G4VTwistSurface::GetNeighbours (G4int areacode, G4VTwistSurface * surfaces[]) inline protected
G4int G4VTwistSurface::GetNode (G4int i, G4int j, G4int m, G4int n, G4int iside)
Definition at line 952 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 952 of file G4VTwistSurface.cc
References FatalException, G4endl, G4Exception(), GetName(), and message().
Referenced by G4TwistTrapFlatSide::GetFacets(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistTrapParallelSide::GetFacets(), G4TwistBoxSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), and G4TwistTrapAlphaSide::GetFacets().
virtual G4ThreeVector G4VTwistSurface::GetNormal (const G4ThreeVector & xx, G4bool isGlobal) pure virtual
Implemented in G4TwistTubsHypeSide, G4TwistTubsSide, G4TwistTubsFlatSide, G4TwistBoxSide, G4TwistTrapAlphaSide, G4TwistTrapParallelSide, and G4TwistTrapFlatSide.
Referenced by DistanceToIn(), DistanceToOut(), G4VTwistedFaceted::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4VTwistedFaceted::SurfaceNormal(), and G4TwistedTubs::SurfaceNormal().
virtual G4double G4VTwistSurface::GetSurfaceArea () pure virtual
Implemented in G4TwistTrapAlphaSide, G4TwistBoxSide, G4TwistTrapParallelSide, G4TwistTubsHypeSide, G4TwistTubsSide, G4TwistTubsFlatSide, and G4TwistTrapFlatSide.
Referenced by G4VTwistedFaceted::GetPointOnSurface(), and G4TwistedTubs::GetPointOnSurface().
G4bool G4VTwistSurface::IsAxis0 (G4int areacode) const inline
Referenced by DistanceToBoundary().
G4bool G4VTwistSurface::IsAxis1 (G4int areacode) const inline
Referenced by DistanceToBoundary().
G4bool G4VTwistSurface::IsBoundary (G4int areacode, G4bool testbitmode = false) const inline
Referenced by G4TwistTubsHypeSide::Inside(), and IsSameBoundary().
G4bool G4VTwistSurface::IsCorner (G4int areacode, G4bool testbitmode = false) const inline
Referenced by IsSameBoundary().
G4bool G4VTwistSurface::IsInside (G4int areacode, G4bool testbitmode = false) const inline
Referenced by DistanceToIn(), G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), and G4TwistTubsHypeSide::Inside().
G4bool G4VTwistSurface::IsOutside (G4int areacode) const inline
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), G4TwistTubsHypeSide::GetAreaCode(), and G4TwistTubsHypeSide::Inside().
G4bool G4VTwistSurface::IsSameBoundary (G4VTwistSurface * surface1, G4int areacode1, G4VTwistSurface * surface2, G4int areacode2) const
Definition at line 616 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 616 of file G4VTwistSurface.cc
References ComputeGlobalDirection(), ComputeGlobalPoint(), d1, d2, GetBoundaryParameters(), GetCorner(), IsBoundary(), IsCorner(), and kCarTolerance.
Referenced by DistanceToIn().
G4bool G4VTwistSurface::IsValidNorm () const inline
Definition at line 144 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 144 of file G4VTwistSurface.hh
References fIsValidNorm.
Referenced by G4VTwistedFaceted::DistanceToOut(), and G4TwistedTubs::DistanceToOut().
void G4VTwistSurface::SetAxis (G4int i, const EAxis axis) inline
Definition at line 156 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 156 of file G4VTwistSurface.hh
References fAxis.
virtual void G4VTwistSurface::SetBoundaries () private pure virtual
Implemented in G4TwistTubsSide, G4TwistTubsHypeSide, G4TwistTubsFlatSide, G4TwistTrapFlatSide, G4TwistTrapAlphaSide, G4TwistBoxSide, and G4TwistTrapParallelSide.
void G4VTwistSurface::SetBoundary (const G4int & axiscode, const G4ThreeVector & direction, const G4ThreeVector & x0, const G4int & boundarytype) protected virtual
Definition at line 863 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 863 of file G4VTwistSurface.cc
References FatalException, fBoundaries, G4endl, G4Exception(), message(), sAxis0, sAxis1, sAxisMask, sAxisMax, sAxisMin, and G4VTwistSurface::Boundary::SetFields().
Referenced by G4TwistBoxSide::SetBoundaries(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), and G4TwistTubsSide::SetBoundaries().
void G4VTwistSurface::SetCorner (G4int areacode, G4double x, G4double y, G4double z) protected
Definition at line 757 of file G4VTwistSurface.cc.
View newest version in sPHENIX GitHub at line 757 of file G4VTwistSurface.cc
References FatalException, fCorners, G4endl, G4Exception(), message(), sC0Max1Max, sC0Max1Min, sC0Min1Max, sC0Min1Min, sCorner, and CLHEP::Hep3Vector::set().
Referenced by G4TwistBoxSide::SetCorners(), G4TwistTrapParallelSide::SetCorners(), G4TwistTrapAlphaSide::SetCorners(), G4TwistTrapFlatSide::SetCorners(), G4TwistTubsFlatSide::SetCorners(), G4TwistTubsHypeSide::SetCorners(), and G4TwistTubsSide::SetCorners().
virtual void G4VTwistSurface::SetCorners () private pure virtual
Implemented in G4TwistTubsSide, G4TwistTubsHypeSide, G4TwistTubsFlatSide, G4TwistTrapFlatSide, G4TwistTrapAlphaSide, G4TwistBoxSide, and G4TwistTrapParallelSide.
void G4VTwistSurface::SetNeighbours (G4VTwistSurface * ax0min, G4VTwistSurface * ax1min, G4VTwistSurface * ax0max, G4VTwistSurface * ax1max) inline
Referenced by G4VTwistedFaceted::CreateSurfaces(), and G4TwistedTubs::CreateSurfaces().
virtual G4ThreeVector G4VTwistSurface::SurfacePoint (G4double , G4double , G4bool isGlobal = false) pure virtual
Implemented in G4TwistTrapAlphaSide, G4TwistBoxSide, G4TwistTrapParallelSide, G4TwistTubsHypeSide, G4TwistTubsSide, G4TwistTubsFlatSide, and G4TwistTrapFlatSide.
Referenced by G4VTwistedFaceted::GetPointOnSurface(), and G4TwistedTubs::GetPointOnSurface().
Member Data Documentation
G4SurfSideQuery G4VTwistSurface::fAmIOnLeftSide private
Definition at line 342 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 342 of file G4VTwistSurface.hh
Referenced by AmIOnLeftSide(), and G4VTwistSurface().
EAxis G4VTwistSurface::fAxis[2] protected
Definition at line 308 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 308 of file G4VTwistSurface.hh
Referenced by DebugPrint(), G4TwistTubsSide::DistanceToSurface(), G4TwistBoxSide::G4TwistBoxSide(), G4TwistTrapAlphaSide::G4TwistTrapAlphaSide(), G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTrapParallelSide::G4TwistTrapParallelSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsHypeSide::G4TwistTubsHypeSide(), G4TwistTubsSide::G4TwistTubsSide(), G4VTwistSurface(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), SetAxis(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), G4TwistTrapParallelSide::SetCorners(), G4TwistBoxSide::SetCorners(), G4TwistTrapAlphaSide::SetCorners(), G4TwistTrapFlatSide::SetCorners(), G4TwistTubsFlatSide::SetCorners(), G4TwistTubsSide::SetCorners(), and G4TwistTubsHypeSide::SetCorners().
G4double G4VTwistSurface::fAxisMax[2] protected
Definition at line 310 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 310 of file G4VTwistSurface.hh
Referenced by DebugPrint(), G4TwistBoxSide::G4TwistBoxSide(), G4TwistTrapAlphaSide::G4TwistTrapAlphaSide(), G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTrapParallelSide::G4TwistTrapParallelSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsHypeSide::G4TwistTubsHypeSide(), G4TwistTubsSide::G4TwistTubsSide(), G4VTwistSurface(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), GetBoundaryLimit(), G4TwistTubsSide::GetBoundaryMax(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), G4TwistTubsSide::GetSurfaceArea(), G4TwistTubsHypeSide::GetSurfaceArea(), and G4TwistTubsFlatSide::SetCorners().
G4double G4VTwistSurface::fAxisMin[2] protected
Definition at line 309 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 309 of file G4VTwistSurface.hh
Referenced by DebugPrint(), G4TwistBoxSide::G4TwistBoxSide(), G4TwistTrapAlphaSide::G4TwistTrapAlphaSide(), G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTrapParallelSide::G4TwistTrapParallelSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsHypeSide::G4TwistTubsHypeSide(), G4TwistTubsSide::G4TwistTubsSide(), G4VTwistSurface(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), GetBoundaryLimit(), G4TwistTubsSide::GetBoundaryMin(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), G4TwistTubsSide::GetSurfaceArea(), G4TwistTubsHypeSide::GetSurfaceArea(), and G4TwistTubsFlatSide::SetCorners().
Boundary G4VTwistSurface::fBoundaries[4] private
Definition at line 331 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 331 of file G4VTwistSurface.hh
Referenced by GetBoundaryAtPZ(), GetBoundaryParameters(), and SetBoundary().
G4ThreeVector G4VTwistSurface::fCorners[4] private
Definition at line 330 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 330 of file G4VTwistSurface.hh
Referenced by G4VTwistSurface(), and SetCorner().
G4SurfCurNormal G4VTwistSurface::fCurrentNormal protected
Definition at line 322 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 322 of file G4VTwistSurface.hh
Referenced by G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4VTwistSurface(), G4TwistTrapFlatSide::GetNormal(), G4TwistTrapAlphaSide::GetNormal(), G4TwistBoxSide::GetNormal(), G4TwistTrapParallelSide::GetNormal(), G4TwistTubsFlatSide::GetNormal(), G4TwistTubsSide::GetNormal(), and G4TwistTubsHypeSide::GetNormal().
CurrentStatus G4VTwistSurface::fCurStat protected
Definition at line 312 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 312 of file G4VTwistSurface.hh
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
CurrentStatus G4VTwistSurface::fCurStatWithV protected
Definition at line 311 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 311 of file G4VTwistSurface.hh
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), and G4TwistTubsHypeSide::DistanceToSurface().
G4int G4VTwistSurface::fHandedness protected
Definition at line 315 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 315 of file G4VTwistSurface.hh
Referenced by G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsHypeSide::G4TwistTubsHypeSide(), G4TwistTubsSide::G4TwistTubsSide(), G4VTwistSurface(), G4TwistTrapFlatSide::GetFacets(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), G4TwistTubsSide::GetNormal(), G4TwistTubsHypeSide::GetNormal(), G4TwistTubsHypeSide::Inside(), and G4TwistTubsHypeSide::SetCorners().
G4bool G4VTwistSurface::fIsValidNorm protected
Definition at line 323 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 323 of file G4VTwistSurface.hh
Referenced by G4TwistBoxSide::G4TwistBoxSide(), G4TwistTrapAlphaSide::G4TwistTrapAlphaSide(), G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTrapParallelSide::G4TwistTrapParallelSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsHypeSide::G4TwistTubsHypeSide(), G4TwistTubsSide::G4TwistTubsSide(), and IsValidNorm().
G4String G4VTwistSurface::fName private
Definition at line 332 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 332 of file G4VTwistSurface.hh
Referenced by AmIOnLeftSide(), DebugPrint(), DistanceTo(), DistanceToIn(), DistanceToOut(), and GetName().
G4VTwistSurface* G4VTwistSurface::fNeighbours[4] private
Definition at line 328 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 328 of file G4VTwistSurface.hh
Referenced by G4VTwistSurface(), and GetNeighbours().
G4RotationMatrix G4VTwistSurface::fRot protected
Definition at line 313 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 313 of file G4VTwistSurface.hh
Referenced by DebugPrint(), G4TwistBoxSide::G4TwistBoxSide(), G4TwistTrapAlphaSide::G4TwistTrapAlphaSide(), G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTrapParallelSide::G4TwistTrapParallelSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsSide::G4TwistTubsSide(), G4VTwistSurface(), G4TwistTubsHypeSide::GetRhoAtPZ(), G4TwistTubsSide::ProjectAtPXPZ(), G4TwistTrapParallelSide::ProjectPoint(), G4TwistBoxSide::ProjectPoint(), G4TwistTrapAlphaSide::ProjectPoint(), G4TwistTrapFlatSide::SurfacePoint(), G4TwistTubsFlatSide::SurfacePoint(), G4TwistTubsSide::SurfacePoint(), G4TwistTubsHypeSide::SurfacePoint(), G4TwistTrapParallelSide::SurfacePoint(), G4TwistBoxSide::SurfacePoint(), and G4TwistTrapAlphaSide::SurfacePoint().
G4ThreeVector G4VTwistSurface::fTrans protected
Definition at line 314 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 314 of file G4VTwistSurface.hh
Referenced by DebugPrint(), G4TwistBoxSide::G4TwistBoxSide(), G4TwistTrapAlphaSide::G4TwistTrapAlphaSide(), G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTrapParallelSide::G4TwistTrapParallelSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsHypeSide::G4TwistTubsHypeSide(), G4TwistTubsSide::G4TwistTubsSide(), G4VTwistSurface(), G4TwistTubsHypeSide::GetRhoAtPZ(), G4TwistTubsSide::ProjectAtPXPZ(), G4TwistTrapParallelSide::ProjectPoint(), G4TwistBoxSide::ProjectPoint(), G4TwistTrapAlphaSide::ProjectPoint(), G4TwistTrapFlatSide::SurfacePoint(), G4TwistTubsFlatSide::SurfacePoint(), G4TwistTubsSide::SurfacePoint(), G4TwistTubsHypeSide::SurfacePoint(), G4TwistTrapParallelSide::SurfacePoint(), G4TwistBoxSide::SurfacePoint(), and G4TwistTrapAlphaSide::SurfacePoint().
G4double G4VTwistSurface::kCarTolerance protected
Definition at line 324 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 324 of file G4VTwistSurface.hh
Referenced by G4TwistTubsSide::DistanceToPlane(), G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4VTwistSurface(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), G4TwistTrapParallelSide::GetNormal(), G4TwistTrapAlphaSide::GetNormal(), G4TwistBoxSide::GetNormal(), G4TwistTubsSide::GetNormal(), G4TwistTubsHypeSide::GetNormal(), and IsSameBoundary().
const G4int G4VTwistSurface::sAreaMask = 0XF0000000 static
Definition at line 235 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 235 of file G4VTwistSurface.hh
const G4int G4VTwistSurface::sAxis0 = 0x0000FF00 static
Definition at line 231 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 231 of file G4VTwistSurface.hh
Referenced by G4TwistTubsSide::DistanceToSurface(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCodeInPhi(), GetBoundaryAtPZ(), GetBoundaryAxis(), GetBoundaryLimit(), G4TwistTubsHypeSide::GetBoundaryMax(), G4TwistTubsHypeSide::GetBoundaryMin(), G4VTwistSurface::Boundary::GetBoundaryParameters(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), and SetBoundary().
const G4int G4VTwistSurface::sAxis1 = 0x000000FF static
Definition at line 232 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 232 of file G4VTwistSurface.hh
Referenced by G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), GetBoundaryAtPZ(), GetBoundaryAxis(), GetBoundaryLimit(), G4VTwistSurface::Boundary::GetBoundaryParameters(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), and SetBoundary().
const G4int G4VTwistSurface::sAxisMask = 0x0000FCFC static
Definition at line 234 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 234 of file G4VTwistSurface.hh
Referenced by GetBoundaryAxis(), and SetBoundary().
const G4int G4VTwistSurface::sAxisMax = 0x00000202 static
Definition at line 225 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 225 of file G4VTwistSurface.hh
Referenced by G4TwistTubsSide::DistanceToSurface(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCodeInPhi(), GetBoundaryLimit(), G4TwistTubsHypeSide::GetBoundaryMax(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), and SetBoundary().
const G4int G4VTwistSurface::sAxisMin = 0x00000101 static
Definition at line 224 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 224 of file G4VTwistSurface.hh
Referenced by G4TwistTubsSide::DistanceToSurface(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCodeInPhi(), GetBoundaryLimit(), G4TwistTubsHypeSide::GetBoundaryMin(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), and SetBoundary().
const G4int G4VTwistSurface::sAxisPhi = 0x00001414 static
Definition at line 230 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 230 of file G4VTwistSurface.hh
Referenced by DistanceToBoundary(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), GetBoundaryAtPZ(), GetBoundaryAxis(), G4TwistTubsFlatSide::SetBoundaries(), and G4TwistTubsHypeSide::SetBoundaries().
const G4int G4VTwistSurface::sAxisRho = 0x00001010 static
Definition at line 229 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 229 of file G4VTwistSurface.hh
Referenced by G4TwistTubsFlatSide::GetAreaCode(), GetBoundaryAtPZ(), GetBoundaryAxis(), and G4TwistTubsFlatSide::SetBoundaries().
const G4int G4VTwistSurface::sAxisX = 0x00000404 static
Definition at line 226 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 226 of file G4VTwistSurface.hh
Referenced by G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), GetBoundaryAxis(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), and G4TwistTubsSide::SetBoundaries().
const G4int G4VTwistSurface::sAxisY = 0x00000808 static
Definition at line 227 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 227 of file G4VTwistSurface.hh
Referenced by G4TwistBoxSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), GetBoundaryAxis(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), and G4TwistTrapFlatSide::SetBoundaries().
const G4int G4VTwistSurface::sAxisZ = 0x00000C0C static
Definition at line 228 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 228 of file G4VTwistSurface.hh
Referenced by G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), GetBoundaryAxis(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), and G4TwistTubsSide::SetBoundaries().
const G4int G4VTwistSurface::sBoundary = 0x20000000 static
Definition at line 218 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 218 of file G4VTwistSurface.hh
Referenced by G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCodeInPhi(), GetBoundaryAxis(), and GetBoundaryLimit().
const G4int G4VTwistSurface::sC0Max1Max = 0x40000202 static
Definition at line 222 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 222 of file G4VTwistSurface.hh
Referenced by DebugPrint(), G4TwistTubsFlatSide::GetAreaCode(), GetBoundaryLimit(), G4TwistTubsFlatSide::GetBoundaryMax(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), SetCorner(), G4TwistTrapParallelSide::SetCorners(), G4TwistBoxSide::SetCorners(), G4TwistTrapAlphaSide::SetCorners(), G4TwistTrapFlatSide::SetCorners(), G4TwistTubsFlatSide::SetCorners(), G4TwistTubsSide::SetCorners(), and G4TwistTubsHypeSide::SetCorners().
const G4int G4VTwistSurface::sC0Max1Min = 0x40000201 static
Definition at line 221 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 221 of file G4VTwistSurface.hh
Referenced by DebugPrint(), G4TwistTubsFlatSide::GetAreaCode(), GetBoundaryLimit(), G4TwistTubsFlatSide::GetBoundaryMin(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), SetCorner(), G4TwistTrapParallelSide::SetCorners(), G4TwistBoxSide::SetCorners(), G4TwistTrapAlphaSide::SetCorners(), G4TwistTrapFlatSide::SetCorners(), G4TwistTubsFlatSide::SetCorners(), G4TwistTubsSide::SetCorners(), and G4TwistTubsHypeSide::SetCorners().
const G4int G4VTwistSurface::sC0Min1Max = 0x40000102 static
Definition at line 223 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 223 of file G4VTwistSurface.hh
Referenced by DebugPrint(), GetBoundaryLimit(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), SetCorner(), G4TwistBoxSide::SetCorners(), G4TwistTrapParallelSide::SetCorners(), G4TwistTrapAlphaSide::SetCorners(), G4TwistTrapFlatSide::SetCorners(), G4TwistTubsFlatSide::SetCorners(), G4TwistTubsSide::SetCorners(), and G4TwistTubsHypeSide::SetCorners().
const G4int G4VTwistSurface::sC0Min1Min = 0x40000101 static
Definition at line 220 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 220 of file G4VTwistSurface.hh
Referenced by DebugPrint(), GetBoundaryLimit(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), SetCorner(), G4TwistBoxSide::SetCorners(), G4TwistTrapParallelSide::SetCorners(), G4TwistTrapAlphaSide::SetCorners(), G4TwistTrapFlatSide::SetCorners(), G4TwistTubsFlatSide::SetCorners(), G4TwistTubsSide::SetCorners(), and G4TwistTubsHypeSide::SetCorners().
const G4int G4VTwistSurface::sCorner = 0x40000000 static
Definition at line 219 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 219 of file G4VTwistSurface.hh
Referenced by G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), GetBoundaryLimit(), and SetCorner().
const G4int G4VTwistSurface::sInside = 0x10000000 static
Definition at line 217 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 217 of file G4VTwistSurface.hh
Referenced by G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), and G4TwistTubsHypeSide::GetAreaCodeInPhi().
const G4int G4VTwistSurface::sOutside = 0x00000000 static
Definition at line 216 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 216 of file G4VTwistSurface.hh
Referenced by G4VTwistSurface::CurrentStatus::CurrentStatus(), DistanceTo(), DistanceToIn(), DistanceToOut(), G4TwistTrapFlatSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), and G4VTwistSurface::CurrentStatus::ResetfDone().
const G4int G4VTwistSurface::sSizeMask = 0x00000303 static
Definition at line 233 of file G4VTwistSurface.hh.
View newest version in sPHENIX GitHub at line 233 of file G4VTwistSurface.hh
Referenced by G4VTwistSurface::Boundary::GetBoundaryParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4VTwistSurface.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4VTwistSurface.cc