ECCE @ EIC Software: ExGflash2ParallelWorld Class Reference
ExGflash2ParallelWorld Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/include/ExGflash2ParallelWorld.hh>
Public Member Functions
ExGflash2ParallelWorld (G4String aWorldName)
~ExGflash2ParallelWorld ()
virtual void Construct () final
virtual void ConstructSD () final
Public Member Functions inherited from G4VUserParallelWorld
G4VUserParallelWorld (G4String worldName)
virtual ~G4VUserParallelWorld ()
G4String GetName ()
Private Attributes
G4Region * fRegion
Static Private Attributes
static G4ThreadLocal
GFlashShowerModel * fFastShowerModel = 0
static G4ThreadLocal
GFlashHomoShowerParameterisation * fParameterisation = 0
static G4ThreadLocal
GFlashParticleBounds * fParticleBounds = 0
static G4ThreadLocal
GFlashHitMaker * fHitMaker = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserParallelWorld
G4VPhysicalVolume * GetWorld ()
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Protected Attributes inherited from G4VUserParallelWorld
G4String fWorldName
Detailed Description
Definition at line 43 of file ExGflash2ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 43 of file ExGflash2ParallelWorld.hh
Constructor & Destructor Documentation
ExGflash2ParallelWorld::ExGflash2ParallelWorld (G4String aWorldName)
Definition at line 64 of file ExGflash2ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 64 of file ExGflash2ParallelWorld.cc
References G4cout, and G4endl.
ExGflash2ParallelWorld::~ExGflash2ParallelWorld ()
Definition at line 72 of file ExGflash2ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 72 of file ExGflash2ParallelWorld.cc
References fFastShowerModel, fHitMaker, fParameterisation, and fParticleBounds.
Member Function Documentation
void ExGflash2ParallelWorld::Construct (void) final virtual
Implements G4VUserParallelWorld.
Definition at line 82 of file ExGflash2ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 82 of file ExGflash2ParallelWorld.cc
References G4Region::AddRootLogicalVolume(), cm, fRegion, G4VPhysicalVolume::GetLogicalVolume(), G4VUserParallelWorld::GetWorld(), G4LogicalVolume::SetRegion(), G4LogicalVolume::SetVisAttributes(), and BTOF::zpos.
void ExGflash2ParallelWorld::ConstructSD () final virtual
Reimplemented from G4VUserParallelWorld.
Definition at line 144 of file ExGflash2ParallelWorld.cc.
View newest version in sPHENIX GitHub at line 144 of file ExGflash2ParallelWorld.cc
References fFastShowerModel, fHitMaker, G4NistManager::FindOrBuildMaterial(), fParameterisation, fParticleBounds, fRegion, G4cout, G4endl, G4NistManager::Instance(), GFlashShowerModel::SetHitMaker(), GFlashShowerModel::SetParameterisation(), and GFlashShowerModel::SetParticleBounds().
Member Data Documentation
G4ThreadLocal GFlashShowerModel * ExGflash2ParallelWorld::fFastShowerModel = 0 static private
Definition at line 56 of file ExGflash2ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 56 of file ExGflash2ParallelWorld.hh
Referenced by ConstructSD(), and ~ExGflash2ParallelWorld().
G4ThreadLocal GFlashHitMaker * ExGflash2ParallelWorld::fHitMaker = 0 static private
Definition at line 59 of file ExGflash2ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 59 of file ExGflash2ParallelWorld.hh
Referenced by ConstructSD(), and ~ExGflash2ParallelWorld().
G4ThreadLocal GFlashHomoShowerParameterisation * ExGflash2ParallelWorld::fParameterisation = 0 static private
Definition at line 57 of file ExGflash2ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 57 of file ExGflash2ParallelWorld.hh
Referenced by ConstructSD(), and ~ExGflash2ParallelWorld().
G4ThreadLocal GFlashParticleBounds * ExGflash2ParallelWorld::fParticleBounds = 0 static private
Definition at line 58 of file ExGflash2ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 58 of file ExGflash2ParallelWorld.hh
Referenced by ConstructSD(), and ~ExGflash2ParallelWorld().
G4Region* ExGflash2ParallelWorld::fRegion private
Definition at line 54 of file ExGflash2ParallelWorld.hh.
View newest version in sPHENIX GitHub at line 54 of file ExGflash2ParallelWorld.hh
Referenced by Construct(), and ConstructSD().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/include/ExGflash2ParallelWorld.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/src/ExGflash2ParallelWorld.cc