ECCE @ EIC Software: G4MaterialScanner Class Reference
G4MaterialScanner Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4MaterialScanner.hh>
Public Member Functions
G4MaterialScanner ()
~G4MaterialScanner ()
void Scan ()
void SetEyePosition (const G4ThreeVector &val)
G4ThreeVector GetEyePosition () const
void SetNTheta (G4int val)
G4int GetNTheta () const
void SetThetaMin (G4double val)
G4double GetThetaMin () const
void SetThetaSpan (G4double val)
G4double GetThetaSpan () const
void SetNPhi (G4int val)
G4int GetNPhi () const
void SetPhiMin (G4double val)
G4double GetPhiMin () const
void SetPhiSpan (G4double val)
G4double GetPhiSpan () const
void SetRegionSensitive (G4bool val=true)
G4bool GetRegionSensitive () const
G4bool SetRegionName (const G4String &val)
G4String GetRegionName () const
Private Member Functions
void DoScan ()
void StoreUserActions ()
void RestoreUserActions ()
Private Attributes
G4RayShooter * theRayShooter
G4MatScanMessenger * theMessenger
G4EventManager * theEventManager
G4UserEventAction * theUserEventAction
G4UserStackingAction * theUserStackingAction
G4UserTrackingAction * theUserTrackingAction
G4UserSteppingAction * theUserSteppingAction
G4UserEventAction * theMatScannerEventAction
G4UserStackingAction * theMatScannerStackingAction
G4UserTrackingAction * theMatScannerTrackingAction
G4MSSteppingAction * theMatScannerSteppingAction
G4ThreeVector eyePosition
G4int nTheta
G4double thetaMin
G4double thetaSpan
G4int nPhi
G4double phiMin
G4double phiSpan
G4ThreeVector eyeDirection
G4bool regionSensitive
G4String regionName
G4Region * theRegion
Detailed Description
Definition at line 53 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 53 of file G4MaterialScanner.hh
Constructor & Destructor Documentation
G4MaterialScanner::G4MaterialScanner ()
Definition at line 50 of file G4MaterialScanner.cc.
View newest version in sPHENIX GitHub at line 50 of file G4MaterialScanner.cc
References deg, eyePosition, G4EventManager::GetEventManager(), nPhi, nTheta, phiMin, phiSpan, regionName, regionSensitive, theEventManager, theMatScannerEventAction, theMatScannerStackingAction, theMatScannerSteppingAction, theMatScannerTrackingAction, theMessenger, theRayShooter, theRegion, thetaMin, thetaSpan, theUserEventAction, theUserStackingAction, theUserSteppingAction, and theUserTrackingAction.
G4MaterialScanner::~G4MaterialScanner ()
Definition at line 79 of file G4MaterialScanner.cc.
View newest version in sPHENIX GitHub at line 79 of file G4MaterialScanner.cc
References theMatScannerSteppingAction, theMessenger, and theRayShooter.
Member Function Documentation
void G4MaterialScanner::DoScan () private
Definition at line 136 of file G4MaterialScanner.cc.
View newest version in sPHENIX GitHub at line 136 of file G4MaterialScanner.cc
References G4GeometryManager::CloseGeometry(), deg, eyeDirection, eyePosition, G4cout, G4endl, G4State_GeomClosed, G4State_Idle, G4GeometryManager::GetInstance(), G4MSSteppingAction::GetLambda0(), G4TransportationManager::GetNavigatorForTracking(), G4RunManagerKernel::GetRunManagerKernel(), G4StateManager::GetStateManager(), G4MSSteppingAction::GetTotalStepLength(), G4TransportationManager::GetTransportationManager(), G4MSSteppingAction::GetX0(), G4MSSteppingAction::Initialize(), G4InuclParticleNames::lambda, BTOF::length, G4Navigator::LocateGlobalPointAndSetup(), mm, Acts::Test::navigator, nPhi, nTheta, G4GeometryManager::OpenGeometry(), phi, phiMin, phiSpan, G4EventManager::ProcessOneEvent(), regionSensitive, G4StateManager::SetNewState(), G4RayShooter::Shoot(), theEventManager, theMatScannerSteppingAction, theRayShooter, theRegion, theta(), thetaMin, thetaSpan, and G4RunManagerKernel::UpdateRegion().
Referenced by Scan().
G4ThreeVector G4MaterialScanner::GetEyePosition () const inline
Definition at line 105 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 105 of file G4MaterialScanner.hh
References eyePosition.
Referenced by G4MatScanMessenger::GetCurrentValue().
G4int G4MaterialScanner::GetNPhi () const inline
Definition at line 113 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 113 of file G4MaterialScanner.hh
References nPhi.
Referenced by G4MatScanMessenger::GetCurrentValue(), and G4MatScanMessenger::SetNewValue().
G4int G4MaterialScanner::GetNTheta () const inline
Definition at line 107 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 107 of file G4MaterialScanner.hh
References nTheta.
Referenced by G4MatScanMessenger::GetCurrentValue(), and G4MatScanMessenger::SetNewValue().
G4double G4MaterialScanner::GetPhiMin () const inline
Definition at line 115 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 115 of file G4MaterialScanner.hh
References phiMin.
Referenced by G4MatScanMessenger::GetCurrentValue(), and G4MatScanMessenger::SetNewValue().
G4double G4MaterialScanner::GetPhiSpan () const inline
Definition at line 117 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 117 of file G4MaterialScanner.hh
References phiSpan.
Referenced by G4MatScanMessenger::GetCurrentValue(), and G4MatScanMessenger::SetNewValue().
G4String G4MaterialScanner::GetRegionName () const inline
Definition at line 121 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 121 of file G4MaterialScanner.hh
References regionName.
Referenced by G4MatScanMessenger::GetCurrentValue().
G4bool G4MaterialScanner::GetRegionSensitive () const inline
Definition at line 119 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 119 of file G4MaterialScanner.hh
References regionSensitive.
Referenced by G4MatScanMessenger::GetCurrentValue().
G4double G4MaterialScanner::GetThetaMin () const inline
Definition at line 109 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 109 of file G4MaterialScanner.hh
References thetaMin.
Referenced by G4MatScanMessenger::GetCurrentValue(), and G4MatScanMessenger::SetNewValue().
G4double G4MaterialScanner::GetThetaSpan () const inline
Definition at line 111 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 111 of file G4MaterialScanner.hh
References thetaSpan.
Referenced by G4MatScanMessenger::GetCurrentValue(), and G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::RestoreUserActions () private
Definition at line 124 of file G4MaterialScanner.cc.
View newest version in sPHENIX GitHub at line 124 of file G4MaterialScanner.cc
References G4SDManager::Activate(), G4SDManager::GetSDMpointerIfExist(), G4EventManager::SetUserAction(), theEventManager, theUserEventAction, theUserStackingAction, theUserSteppingAction, and theUserTrackingAction.
Referenced by Scan().
void G4MaterialScanner::Scan ()
Definition at line 86 of file G4MaterialScanner.cc.
View newest version in sPHENIX GitHub at line 86 of file G4MaterialScanner.cc
References DoScan(), G4cerr, G4endl, G4State_Idle, G4StateManager::GetCurrentState(), G4StateManager::GetStateManager(), RestoreUserActions(), StoreUserActions(), and theMatScannerSteppingAction.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::SetEyePosition (const G4ThreeVector & val) inline
Definition at line 104 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 104 of file G4MaterialScanner.hh
References eyePosition.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::SetNPhi (G4int val) inline
Definition at line 112 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 112 of file G4MaterialScanner.hh
References nPhi.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::SetNTheta (G4int val) inline
Definition at line 106 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 106 of file G4MaterialScanner.hh
References nTheta.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::SetPhiMin (G4double val) inline
Definition at line 114 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 114 of file G4MaterialScanner.hh
References phiMin.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::SetPhiSpan (G4double val) inline
Definition at line 116 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 116 of file G4MaterialScanner.hh
References phiSpan.
Referenced by G4MatScanMessenger::SetNewValue().
G4bool G4MaterialScanner::SetRegionName (const G4String & val)
Definition at line 212 of file G4MaterialScanner.cc.
View newest version in sPHENIX GitHub at line 212 of file G4MaterialScanner.cc
References G4cerr, G4endl, G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), regionName, and theRegion.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::SetRegionSensitive (G4bool val = true) inline
Definition at line 118 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 118 of file G4MaterialScanner.hh
References regionSensitive.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::SetThetaMin (G4double val) inline
Definition at line 108 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 108 of file G4MaterialScanner.hh
References thetaMin.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::SetThetaSpan (G4double val) inline
Definition at line 110 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 110 of file G4MaterialScanner.hh
References thetaSpan.
Referenced by G4MatScanMessenger::SetNewValue().
void G4MaterialScanner::StoreUserActions () private
Definition at line 103 of file G4MaterialScanner.cc.
View newest version in sPHENIX GitHub at line 103 of file G4MaterialScanner.cc
References G4SDManager::Activate(), G4GeometryManager::CloseGeometry(), G4GeometryManager::GetInstance(), G4SDManager::GetSDMpointerIfExist(), G4EventManager::GetUserEventAction(), G4EventManager::GetUserStackingAction(), G4EventManager::GetUserSteppingAction(), G4EventManager::GetUserTrackingAction(), G4GeometryManager::OpenGeometry(), G4EventManager::SetUserAction(), theEventManager, theMatScannerEventAction, theMatScannerStackingAction, theMatScannerSteppingAction, theMatScannerTrackingAction, theUserEventAction, theUserStackingAction, theUserSteppingAction, and theUserTrackingAction.
Referenced by Scan().
Member Data Documentation
G4ThreeVector G4MaterialScanner::eyeDirection private
Definition at line 97 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 97 of file G4MaterialScanner.hh
Referenced by DoScan().
G4ThreeVector G4MaterialScanner::eyePosition private
Definition at line 89 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 89 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), GetEyePosition(), and SetEyePosition().
G4int G4MaterialScanner::nPhi private
Definition at line 93 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 93 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), GetNPhi(), and SetNPhi().
G4int G4MaterialScanner::nTheta private
Definition at line 90 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 90 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), GetNTheta(), and SetNTheta().
G4double G4MaterialScanner::phiMin private
Definition at line 94 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 94 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), GetPhiMin(), and SetPhiMin().
G4double G4MaterialScanner::phiSpan private
Definition at line 95 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 95 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), GetPhiSpan(), and SetPhiSpan().
G4String G4MaterialScanner::regionName private
Definition at line 100 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 100 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), GetRegionName(), and SetRegionName().
G4bool G4MaterialScanner::regionSensitive private
Definition at line 99 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 99 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), GetRegionSensitive(), and SetRegionSensitive().
G4EventManager* G4MaterialScanner::theEventManager private
Definition at line 77 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 77 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), RestoreUserActions(), and StoreUserActions().
G4UserEventAction* G4MaterialScanner::theMatScannerEventAction private
Definition at line 84 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 84 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), and StoreUserActions().
G4UserStackingAction* G4MaterialScanner::theMatScannerStackingAction private
Definition at line 85 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 85 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), and StoreUserActions().
G4MSSteppingAction* G4MaterialScanner::theMatScannerSteppingAction private
Definition at line 87 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 87 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), Scan(), StoreUserActions(), and ~G4MaterialScanner().
G4UserTrackingAction* G4MaterialScanner::theMatScannerTrackingAction private
Definition at line 86 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 86 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), and StoreUserActions().
G4MatScanMessenger* G4MaterialScanner::theMessenger private
Definition at line 75 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 75 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), and ~G4MaterialScanner().
G4RayShooter* G4MaterialScanner::theRayShooter private
Definition at line 74 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 74 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), and ~G4MaterialScanner().
G4Region* G4MaterialScanner::theRegion private
Definition at line 101 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 101 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), and SetRegionName().
G4double G4MaterialScanner::thetaMin private
Definition at line 91 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 91 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), GetThetaMin(), and SetThetaMin().
G4double G4MaterialScanner::thetaSpan private
Definition at line 92 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 92 of file G4MaterialScanner.hh
Referenced by DoScan(), G4MaterialScanner(), GetThetaSpan(), and SetThetaSpan().
G4UserEventAction* G4MaterialScanner::theUserEventAction private
Definition at line 79 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 79 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), RestoreUserActions(), and StoreUserActions().
G4UserStackingAction* G4MaterialScanner::theUserStackingAction private
Definition at line 80 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 80 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), RestoreUserActions(), and StoreUserActions().
G4UserSteppingAction* G4MaterialScanner::theUserSteppingAction private
Definition at line 82 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 82 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), RestoreUserActions(), and StoreUserActions().
G4UserTrackingAction* G4MaterialScanner::theUserTrackingAction private
Definition at line 81 of file G4MaterialScanner.hh.
View newest version in sPHENIX GitHub at line 81 of file G4MaterialScanner.hh
Referenced by G4MaterialScanner(), RestoreUserActions(), and StoreUserActions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4MaterialScanner.hh
geant4/tree/geant4-10.6-release/source/run/src/G4MaterialScanner.cc