ECCE @ EIC Software: G4DNACrossSectionDataSet Class Reference
G4DNACrossSectionDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNACrossSectionDataSet.hh>
Public Member Functions
G4DNACrossSectionDataSet (G4VDataSetAlgorithm *algo, G4double xUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn)
virtual ~G4DNACrossSectionDataSet ()
virtual G4double FindValue (G4double e, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4VEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4VEMDataSet *dataSet)
virtual size_t NumberOfComponents (void) const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual const G4DataVector & GetLogEnergies (G4int componentId) const
virtual const G4DataVector & GetLogData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *values, G4int componentId)
virtual void SetLogEnergiesData (G4DataVector *x, G4DataVector *values, G4DataVector *log_x, G4DataVector *log_values, G4int componentId)
virtual G4bool LoadData (const G4String &argFileName)
virtual G4bool LoadNonLogData (const G4String &argFileName)
virtual G4bool SaveData (const G4String &argFileName) const
virtual G4double RandomSelect (G4int) const
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Private Member Functions
G4String FullFileName (const G4String &argFileName) const
G4DNACrossSectionDataSet ()
G4DNACrossSectionDataSet (const G4DNACrossSectionDataSet &copy)
G4DNACrossSectionDataSet & operator= (const G4DNACrossSectionDataSet &right)
G4double GetUnitEnergies () const
G4double GetUnitData () const
const G4VDataSetAlgorithm * GetAlgorithm () const
void CleanUpComponents (void)
Private Attributes
std::vector< G4VEMDataSet * > components
G4int z
G4VDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
Detailed Description
Definition at line 54 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4DNACrossSectionDataSet.hh
Constructor & Destructor Documentation
G4DNACrossSectionDataSet::G4DNACrossSectionDataSet (G4VDataSetAlgorithm * algo, G4double xUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn)
Definition at line 64 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 64 of file G4DNACrossSectionDataSet.cc
References z.
G4DNACrossSectionDataSet::~G4DNACrossSectionDataSet () virtual
Definition at line 75 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 75 of file G4DNACrossSectionDataSet.cc
References algorithm, and CleanUpComponents().
G4DNACrossSectionDataSet::G4DNACrossSectionDataSet () private
G4DNACrossSectionDataSet::G4DNACrossSectionDataSet (const G4DNACrossSectionDataSet & copy) private
Member Function Documentation
virtual void G4DNACrossSectionDataSet::AddComponent (G4VEMDataSet * dataSet) inline virtual
Implements G4VEMDataSet.
Definition at line 71 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 71 of file G4DNACrossSectionDataSet.hh
References components.
Referenced by LoadData(), and LoadNonLogData().
void G4DNACrossSectionDataSet::CleanUpComponents (void) private
Definition at line 563 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 563 of file G4DNACrossSectionDataSet.cc
References components.
Referenced by LoadData(), LoadNonLogData(), and ~G4DNACrossSectionDataSet().
G4double G4DNACrossSectionDataSet::FindValue (G4double e, G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 483 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 483 of file G4DNACrossSectionDataSet.cc
References components.
Referenced by G4DNABornExcitationModel1::CrossSectionPerVolume(), G4DNAChampionElasticModel::CrossSectionPerVolume(), G4DNAMeltonAttachmentModel::CrossSectionPerVolume(), G4DNAELSEPAElasticModel::CrossSectionPerVolume(), G4DNARuddIonisationExtendedModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::CrossSectionPerVolume(), G4DNABornIonisationModel1::CrossSectionPerVolume(), G4DNABornIonisationModel2::CrossSectionPerVolume(), G4DNAIonElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNACPA100ElasticModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4DNARuddIonisationModel::PartialCrossSection(), and G4DNARuddIonisationExtendedModel::PartialCrossSection().
G4String G4DNACrossSectionDataSet::FullFileName (const G4String & argFileName) const private
Definition at line 464 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 464 of file G4DNACrossSectionDataSet.cc
References FatalException, and G4Exception().
Referenced by LoadData(), LoadNonLogData(), and SaveData().
const G4VDataSetAlgorithm* G4DNACrossSectionDataSet::GetAlgorithm () const inline private
Definition at line 127 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 127 of file G4DNACrossSectionDataSet.hh
References algorithm.
Referenced by LoadData(), and LoadNonLogData().
virtual const G4VEMDataSet* G4DNACrossSectionDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 68 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 68 of file G4DNACrossSectionDataSet.hh
References components.
Referenced by GetData(), GetEnergies(), GetLogData(), GetLogEnergies(), G4DNABornExcitationModel1::GetPartialCrossSection(), G4DNABornIonisationModel2::GetPartialCrossSection(), G4DNABornIonisationModel1::GetPartialCrossSection(), PrintData(), G4DNABornExcitationModel1::RandomSelect(), G4DNAEmfietzoglouExcitationModel::RandomSelect(), G4DNACPA100ExcitationModel::RandomSelect(), G4DNARuddIonisationModel::RandomSelect(), G4DNABornIonisationModel2::RandomSelect(), G4DNARuddIonisationExtendedModel::RandomSelect(), G4DNABornIonisationModel1::RandomSelect(), G4DNACPA100IonisationModel::RandomSelect(), G4DNAEmfietzoglouIonisationModel::RandomSelect(), G4VDNAModel::RandomSelectShell(), and SaveData().
virtual const G4DataVector& G4DNACrossSectionDataSet::GetData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 80 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 80 of file G4DNACrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetData().
virtual const G4DataVector& G4DNACrossSectionDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 77 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 77 of file G4DNACrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetEnergies().
Referenced by SaveData().
virtual const G4DataVector& G4DNACrossSectionDataSet::GetLogData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 86 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 86 of file G4DNACrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogData().
virtual const G4DataVector& G4DNACrossSectionDataSet::GetLogEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 83 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DNACrossSectionDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogEnergies().
G4double G4DNACrossSectionDataSet::GetUnitData () const inline private
Definition at line 126 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 126 of file G4DNACrossSectionDataSet.hh
References unitData.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4double G4DNACrossSectionDataSet::GetUnitEnergies () const inline private
Definition at line 125 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 125 of file G4DNACrossSectionDataSet.hh
References unitEnergies.
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4bool G4DNACrossSectionDataSet::LoadData (const G4String & argFileName) virtual
Implements G4VEMDataSet.
Definition at line 83 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 83 of file G4DNACrossSectionDataSet.cc
References AddComponent(), c, CleanUpComponents(), e, FatalException, FullFileName(), G4Exception(), GetAlgorithm(), GetUnitData(), GetUnitEnergies(), in, and message().
Referenced by G4DNABornExcitationModel1::Initialise(), G4DNAChampionElasticModel::Initialise(), G4DNAMeltonAttachmentModel::Initialise(), G4DNAELSEPAElasticModel::Initialise(), G4DNARuddIonisationExtendedModel::Initialise(), G4DNARuddIonisationModel::Initialise(), G4DNABornIonisationModel1::Initialise(), G4DNABornIonisationModel2::Initialise(), G4DNAIonElasticModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), and G4DNACPA100IonisationModel::Initialise().
G4bool G4DNACrossSectionDataSet::LoadNonLogData (const G4String & argFileName) virtual
Implements G4VEMDataSet.
Definition at line 250 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 250 of file G4DNACrossSectionDataSet.cc
References AddComponent(), c, CleanUpComponents(), e, FatalException, FullFileName(), G4Exception(), GetAlgorithm(), GetUnitData(), GetUnitEnergies(), in, and message().
virtual size_t G4DNACrossSectionDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 74 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 74 of file G4DNACrossSectionDataSet.hh
References components.
Referenced by PrintData(), G4DNABornExcitationModel1::RandomSelect(), G4DNAEmfietzoglouExcitationModel::RandomSelect(), G4DNACPA100ExcitationModel::RandomSelect(), G4DNARuddIonisationModel::RandomSelect(), G4DNABornIonisationModel2::RandomSelect(), G4DNARuddIonisationExtendedModel::RandomSelect(), G4DNABornIonisationModel1::RandomSelect(), G4DNACPA100IonisationModel::RandomSelect(), G4DNAEmfietzoglouIonisationModel::RandomSelect(), G4VDNAModel::RandomSelectShell(), and SaveData().
G4DNACrossSectionDataSet& G4DNACrossSectionDataSet::operator= (const G4DNACrossSectionDataSet & right) private
void G4DNACrossSectionDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 501 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 501 of file G4DNACrossSectionDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4VEMDataSet::PrintData().
virtual G4double G4DNACrossSectionDataSet::RandomSelect (G4int) const inline virtual
Implements G4VEMDataSet.
Definition at line 102 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 102 of file G4DNACrossSectionDataSet.hh
G4bool G4DNACrossSectionDataSet::SaveData (const G4String & argFileName) const virtual
Implements G4VEMDataSet.
Definition at line 395 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 395 of file G4DNACrossSectionDataSet.cc
References FatalException, FullFileName(), G4Exception(), GetComponent(), G4VEMDataSet::GetData(), GetEnergies(), GetUnitData(), GetUnitEnergies(), k, left, message(), n, and NumberOfComponents().
void G4DNACrossSectionDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * values, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 519 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 519 of file G4DNACrossSectionDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetEnergiesData().
void G4DNACrossSectionDataSet::SetLogEnergiesData (G4DataVector * x, G4DataVector * values, G4DataVector * log_x, G4DataVector * log_values, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 540 of file G4DNACrossSectionDataSet.cc.
View newest version in sPHENIX GitHub at line 540 of file G4DNACrossSectionDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetLogEnergiesData().
Member Data Documentation
G4VDataSetAlgorithm* G4DNACrossSectionDataSet::algorithm private
Definition at line 120 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 120 of file G4DNACrossSectionDataSet.hh
Referenced by GetAlgorithm(), and ~G4DNACrossSectionDataSet().
std::vector<G4VEMDataSet*> G4DNACrossSectionDataSet::components private
Definition at line 116 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 116 of file G4DNACrossSectionDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), FindValue(), GetComponent(), NumberOfComponents(), SetEnergiesData(), and SetLogEnergiesData().
G4double G4DNACrossSectionDataSet::unitData private
Definition at line 123 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 123 of file G4DNACrossSectionDataSet.hh
Referenced by GetUnitData().
G4double G4DNACrossSectionDataSet::unitEnergies private
Definition at line 122 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 122 of file G4DNACrossSectionDataSet.hh
Referenced by GetUnitEnergies().
G4int G4DNACrossSectionDataSet::z private
Definition at line 118 of file G4DNACrossSectionDataSet.hh.
View newest version in sPHENIX GitHub at line 118 of file G4DNACrossSectionDataSet.hh
Referenced by G4DNACrossSectionDataSet().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4DNACrossSectionDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4DNACrossSectionDataSet.cc