ECCE @ EIC Software: B02RunAction Class Reference
B02RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/include/B02RunAction.hh>
Public Member Functions
B02RunAction ()
virtual ~B02RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void PrintHeader (std::ostream *out)
std::string FillString (const std::string &name, char c, G4int n, G4bool back=true)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
std::vector< G4String > fSDName
G4int fFieldValue
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 48 of file B02RunAction.hh.
View newest version in sPHENIX GitHub at line 48 of file B02RunAction.hh
Constructor & Destructor Documentation
B02RunAction::B02RunAction ()
Definition at line 51 of file B02RunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file B02RunAction.cc
References fSDName.
B02RunAction::~B02RunAction () virtual
Definition at line 64 of file B02RunAction.cc.
View newest version in sPHENIX GitHub at line 64 of file B02RunAction.cc
References fSDName.
Member Function Documentation
void B02RunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 81 of file B02RunAction.cc.
View newest version in sPHENIX GitHub at line 81 of file B02RunAction.cc
References G4cout, G4endl, and G4Run::GetRunID().
void B02RunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 88 of file B02RunAction.cc.
View newest version in sPHENIX GitHub at line 88 of file B02RunAction.cc
References fFieldValue, fSDName, G4cout, G4endl, B02ImportanceDetectorConstruction::GetCellName(), B02Run::GetHitsMap(), G4Run::GetNumberOfEvent(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), G4UserRunAction::IsMaster(), PrintHeader(), and SL.
std::string B02RunAction::FillString (const std::string & name, char c, G4int n, G4bool back = true)
Definition at line 241 of file B02RunAction.cc.
View newest version in sPHENIX GitHub at line 241 of file B02RunAction.cc
References test::fname, and k.
G4Run * B02RunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 71 of file B02RunAction.cc.
View newest version in sPHENIX GitHub at line 71 of file B02RunAction.cc
References fSDName.
void B02RunAction::PrintHeader (std::ostream * out)
Definition at line 206 of file B02RunAction.cc.
View newest version in sPHENIX GitHub at line 206 of file B02RunAction.cc
References fFieldValue, G4endl, and it.
Referenced by EndOfRunAction().
Member Data Documentation
G4int B02RunAction::fFieldValue private
Definition at line 71 of file B02RunAction.hh.
View newest version in sPHENIX GitHub at line 71 of file B02RunAction.hh
Referenced by EndOfRunAction(), and PrintHeader().
std::vector<G4String> B02RunAction::fSDName private
Definition at line 69 of file B02RunAction.hh.
View newest version in sPHENIX GitHub at line 69 of file B02RunAction.hh
Referenced by B02RunAction(), EndOfRunAction(), GenerateRun(), and ~B02RunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/include/B02RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/B02/src/B02RunAction.cc