ECCE @ EIC Software: F04DetectorConstruction Class Reference
F04DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04DetectorConstruction.hh>
Public Member Functions
F04DetectorConstruction ()
virtual ~F04DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
G4VPhysicalVolume * ConstructDetector ()
virtual void ConstructSDandField ()
void SetWorldMaterial (G4String)
void SetWorldSizeZ (G4double)
void SetWorldSizeR (G4double)
void SetCaptureMgntRadius (G4double)
void SetCaptureMgntLength (G4double)
void SetCaptureMgntB1 (G4double)
void SetCaptureMgntB2 (G4double)
void SetTransferMgntRadius (G4double)
void SetTransferMgntLength (G4double)
void SetTransferMgntB (G4double)
void SetTransferMgntPos (G4double)
void SetTargetMaterial (G4String)
void SetTargetThickness (G4double)
void SetTargetRadius (G4double)
void SetTargetPos (G4double)
void SetTargetAngle (G4int)
void SetDegraderMaterial (G4String)
void SetDegraderThickness (G4double)
void SetDegraderRadius (G4double)
void SetDegraderPos (G4double)
G4Material * GetWorldMaterial ()
G4double GetWorldSizeZ ()
G4double GetWorldSizeR ()
G4LogicalVolume * GetCaptureMgnt ()
G4double GetCaptureMgntRadius ()
G4double GetCaptureMgntLength ()
G4double GetCaptureMgntB1 ()
G4double GetCaptureMgntB2 ()
G4ThreeVector GetCaptureMgntCenter ()
G4LogicalVolume * GetTransferMgnt ()
G4double GetTransferMgntRadius ()
G4double GetTransferMgntLength ()
G4double GetTransferMgntB ()
G4double GetTransferMgntPos ()
G4ThreeVector GetTransferMgntCenter ()
G4Material * GetTargetMaterial ()
G4double GetTargetRadius ()
G4double GetTargetThickness ()
G4double GetTargetPos ()
G4int GetTargetAngle ()
G4Material * GetDegraderMaterial ()
G4double GetDegraderRadius ()
G4double GetDegraderThickness ()
G4double GetDegraderPos ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Static Public Member Functions
static G4RotationMatrix StringToRotationMatrix (G4String rotation)
Private Member Functions
void DefineMaterials ()
Private Attributes
F04DetectorMessenger * fDetectorMessenger
G4Cache< F04GlobalField * > fFieldSetUp
F04Materials * fMaterials
G4Material * fVacuum
G4Tubs * fSolidWorld
G4LogicalVolume * fLogicWorld
G4VPhysicalVolume * fPhysiWorld
G4Tubs * fSolidTarget
G4LogicalVolume * fLogicTarget
G4VPhysicalVolume * fPhysiTarget
G4Tubs * fSolidDegrader
G4LogicalVolume * fLogicDegrader
G4VPhysicalVolume * fPhysiDegrader
G4Tubs * fSolidCaptureMgnt
G4LogicalVolume * fLogicCaptureMgnt
G4VPhysicalVolume * fPhysiCaptureMgnt
G4Tubs * fSolidTransferMgnt
G4LogicalVolume * fLogicTransferMgnt
G4VPhysicalVolume * fPhysiTransferMgnt
G4Material * fWorldMaterial
G4double fWorldSizeR
G4double fWorldSizeZ
G4double fCaptureMgntLength
G4double fCaptureMgntRadius
G4double fCaptureMgntB1
G4double fCaptureMgntB2
G4double fTransferMgntLength
G4double fTransferMgntRadius
G4double fTransferMgntB
G4double fTransferMgntPos
G4Material * fTargetMaterial
G4double fTargetThickness
G4double fTargetRadius
G4double fTargetPos
G4int fTargetAngle
G4Material * fDegraderMaterial
G4double fDegraderThickness
G4double fDegraderRadius
G4double fDegraderPos
G4ThreeVector fCaptureMgntCenter
G4ThreeVector fTransferMgntCenter
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 53 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 53 of file F04DetectorConstruction.hh
Constructor & Destructor Documentation
F04DetectorConstruction::F04DetectorConstruction ()
Definition at line 69 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 69 of file F04DetectorConstruction.cc
References cm, fCaptureMgntLength, fCaptureMgntRadius, fDegraderPos, fDegraderRadius, fDegraderThickness, fDetectorMessenger, fTargetRadius, fTargetThickness, fTransferMgntLength, fTransferMgntRadius, fWorldSizeR, fWorldSizeZ, m, SetCaptureMgntB1(), SetCaptureMgntB2(), SetTargetAngle(), SetTransferMgntB(), and tesla.
F04DetectorConstruction::~F04DetectorConstruction () virtual
Definition at line 108 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 108 of file F04DetectorConstruction.cc
References fDetectorMessenger.
Member Function Documentation
G4VPhysicalVolume * F04DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 115 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 115 of file F04DetectorConstruction.cc
References G4PhysicalVolumeStore::Clean(), G4LogicalVolumeStore::Clean(), G4SolidStore::Clean(), ConstructDetector(), DefineMaterials(), fMaterials, fPhysiWorld, F04Materials::GetInstance(), G4LogicalVolumeStore::GetInstance(), G4PhysicalVolumeStore::GetInstance(), G4SolidStore::GetInstance(), G4GeometryManager::GetInstance(), and G4GeometryManager::OpenGeometry().
G4VPhysicalVolume * F04DetectorConstruction::ConstructDetector ()
Definition at line 147 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 147 of file F04DetectorConstruction.cc
References angle, G4String::both, c, fCaptureMgntCenter, fLogicCaptureMgnt, fLogicDegrader, fLogicTarget, fLogicTransferMgnt, fLogicWorld, fPhysiCaptureMgnt, fPhysiDegrader, fPhysiTarget, fPhysiTransferMgnt, fPhysiWorld, fSolidCaptureMgnt, fSolidDegrader, fSolidTarget, fSolidTransferMgnt, fSolidWorld, fTransferMgntCenter, fVacuum, GetCaptureMgntLength(), GetCaptureMgntRadius(), GetDegraderMaterial(), GetDegraderPos(), GetDegraderRadius(), GetDegraderThickness(), GetTargetAngle(), GetTargetMaterial(), GetTargetPos(), GetTargetRadius(), GetTargetThickness(), GetTransferMgntLength(), GetTransferMgntPos(), GetTransferMgntRadius(), GetWorldMaterial(), GetWorldSizeR(), GetWorldSizeZ(), CLHEP::HepRotation::inverse(), mm, StringToRotationMatrix(), G4String::strip(), twopi, x, and z.
Referenced by Construct().
void F04DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 525 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 525 of file F04DetectorConstruction.cc
References fFieldSetUp, G4Cache< VALTYPE >::Get(), F04GlobalField::GetObject(), G4Cache< VALTYPE >::Put(), and G4AutoDelete::Register().
void F04DetectorConstruction::DefineMaterials () private
Definition at line 134 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 134 of file F04DetectorConstruction.cc
References fDegraderMaterial, fMaterials, fTargetMaterial, fVacuum, fWorldMaterial, and F04Materials::GetMaterial().
Referenced by Construct().
G4LogicalVolume* F04DetectorConstruction::GetCaptureMgnt () inline
Definition at line 109 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 109 of file F04DetectorConstruction.hh
References fLogicCaptureMgnt.
Referenced by F04GlobalField::ConstructField().
G4double F04DetectorConstruction::GetCaptureMgntB1 () inline
Definition at line 112 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 112 of file F04DetectorConstruction.hh
References fCaptureMgntB1.
Referenced by F04GlobalField::ConstructField().
G4double F04DetectorConstruction::GetCaptureMgntB2 () inline
Definition at line 113 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 113 of file F04DetectorConstruction.hh
References fCaptureMgntB2.
Referenced by F04GlobalField::ConstructField().
G4ThreeVector F04DetectorConstruction::GetCaptureMgntCenter () inline
Definition at line 114 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 114 of file F04DetectorConstruction.hh
References fCaptureMgntCenter.
Referenced by F04GlobalField::ConstructField().
G4double F04DetectorConstruction::GetCaptureMgntLength () inline
Definition at line 111 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 111 of file F04DetectorConstruction.hh
References fCaptureMgntLength.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetCaptureMgntRadius () inline
Definition at line 110 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 110 of file F04DetectorConstruction.hh
References fCaptureMgntRadius.
Referenced by ConstructDetector().
G4Material* F04DetectorConstruction::GetDegraderMaterial () inline
Definition at line 129 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 129 of file F04DetectorConstruction.hh
References fDegraderMaterial.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetDegraderPos () inline
Definition at line 132 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 132 of file F04DetectorConstruction.hh
References fDegraderPos.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetDegraderRadius () inline
Definition at line 130 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 130 of file F04DetectorConstruction.hh
References fDegraderRadius.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetDegraderThickness () inline
Definition at line 131 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 131 of file F04DetectorConstruction.hh
References fDegraderThickness.
Referenced by ConstructDetector().
G4int F04DetectorConstruction::GetTargetAngle () inline
Definition at line 127 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 127 of file F04DetectorConstruction.hh
References fTargetAngle.
Referenced by ConstructDetector().
G4Material* F04DetectorConstruction::GetTargetMaterial () inline
Definition at line 123 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 123 of file F04DetectorConstruction.hh
References fTargetMaterial.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetTargetPos () inline
Definition at line 126 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 126 of file F04DetectorConstruction.hh
References fTargetPos.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetTargetRadius () inline
Definition at line 124 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 124 of file F04DetectorConstruction.hh
References fTargetRadius.
Referenced by ConstructDetector(), and F04PrimaryGeneratorAction::GeneratePrimaries().
G4double F04DetectorConstruction::GetTargetThickness () inline
Definition at line 125 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 125 of file F04DetectorConstruction.hh
References fTargetThickness.
Referenced by ConstructDetector(), F04PrimaryGeneratorAction::F04PrimaryGeneratorAction(), and F04PrimaryGeneratorAction::GeneratePrimaries().
G4LogicalVolume* F04DetectorConstruction::GetTransferMgnt () inline
Definition at line 116 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 116 of file F04DetectorConstruction.hh
References fLogicTransferMgnt.
Referenced by F04GlobalField::ConstructField().
G4double F04DetectorConstruction::GetTransferMgntB () inline
Definition at line 119 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 119 of file F04DetectorConstruction.hh
References fTransferMgntB.
Referenced by F04GlobalField::ConstructField().
G4ThreeVector F04DetectorConstruction::GetTransferMgntCenter () inline
Definition at line 121 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 121 of file F04DetectorConstruction.hh
References fTransferMgntCenter.
Referenced by F04GlobalField::ConstructField().
G4double F04DetectorConstruction::GetTransferMgntLength () inline
Definition at line 118 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 118 of file F04DetectorConstruction.hh
References fTransferMgntLength.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetTransferMgntPos () inline
Definition at line 120 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 120 of file F04DetectorConstruction.hh
References fTransferMgntPos.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetTransferMgntRadius () inline
Definition at line 117 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 117 of file F04DetectorConstruction.hh
References fTransferMgntRadius.
Referenced by ConstructDetector().
G4Material* F04DetectorConstruction::GetWorldMaterial () inline
Definition at line 105 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file F04DetectorConstruction.hh
References fWorldMaterial.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetWorldSizeR () inline
Definition at line 107 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 107 of file F04DetectorConstruction.hh
References fWorldSizeR.
Referenced by ConstructDetector().
G4double F04DetectorConstruction::GetWorldSizeZ () inline
Definition at line 106 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file F04DetectorConstruction.hh
References fWorldSizeZ.
Referenced by ConstructDetector().
void F04DetectorConstruction::SetCaptureMgntB1 (G4double val)
Definition at line 395 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 395 of file F04DetectorConstruction.cc
References fCaptureMgntB1, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorConstruction(), and F04FieldMessenger::SetNewValue().
void F04DetectorConstruction::SetCaptureMgntB2 (G4double val)
Definition at line 405 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 405 of file F04DetectorConstruction.cc
References fCaptureMgntB2, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorConstruction(), and F04FieldMessenger::SetNewValue().
void F04DetectorConstruction::SetCaptureMgntLength (G4double val)
Definition at line 385 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 385 of file F04DetectorConstruction.cc
References fCaptureMgntLength, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetCaptureMgntRadius (G4double val)
Definition at line 375 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 375 of file F04DetectorConstruction.cc
References fCaptureMgntRadius, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetDegraderMaterial (G4String materialChoice)
Definition at line 335 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 335 of file F04DetectorConstruction.cc
References fDegraderMaterial, G4NistManager::FindOrBuildMaterial(), G4cout, G4endl, G4RunManager::GetRunManager(), G4NistManager::Instance(), and G4RunManager::PhysicsHasBeenModified().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetDegraderPos (G4double val)
Definition at line 515 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 515 of file F04DetectorConstruction.cc
References fDegraderPos, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetDegraderRadius (G4double val)
Definition at line 495 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 495 of file F04DetectorConstruction.cc
References fDegraderRadius, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetDegraderThickness (G4double val)
Definition at line 505 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 505 of file F04DetectorConstruction.cc
References fDegraderThickness, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetTargetAngle (G4int val)
Definition at line 485 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 485 of file F04DetectorConstruction.cc
References fTargetAngle, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorConstruction(), and F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetTargetMaterial (G4String materialChoice)
Definition at line 317 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 317 of file F04DetectorConstruction.cc
References G4NistManager::FindOrBuildMaterial(), fTargetMaterial, G4cout, G4endl, G4RunManager::GetRunManager(), G4NistManager::Instance(), and G4RunManager::PhysicsHasBeenModified().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetTargetPos (G4double val)
Definition at line 475 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 475 of file F04DetectorConstruction.cc
References fTargetPos, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetTargetRadius (G4double val)
Definition at line 455 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 455 of file F04DetectorConstruction.cc
References fTargetRadius, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetTargetThickness (G4double val)
Definition at line 465 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 465 of file F04DetectorConstruction.cc
References fTargetThickness, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetTransferMgntB (G4double val)
Definition at line 435 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 435 of file F04DetectorConstruction.cc
References fTransferMgntB, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorConstruction(), and F04FieldMessenger::SetNewValue().
void F04DetectorConstruction::SetTransferMgntLength (G4double val)
Definition at line 425 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 425 of file F04DetectorConstruction.cc
References fTransferMgntLength, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetTransferMgntPos (G4double val)
Definition at line 445 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 445 of file F04DetectorConstruction.cc
References fTransferMgntPos, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetTransferMgntRadius (G4double val)
Definition at line 415 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 415 of file F04DetectorConstruction.cc
References fTransferMgntRadius, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetWorldMaterial (G4String materialChoice)
Definition at line 299 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 299 of file F04DetectorConstruction.cc
References G4NistManager::FindOrBuildMaterial(), fWorldMaterial, G4cout, G4endl, G4RunManager::GetRunManager(), G4NistManager::Instance(), and G4RunManager::PhysicsHasBeenModified().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetWorldSizeR (G4double val)
Definition at line 365 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 365 of file F04DetectorConstruction.cc
References fWorldSizeR, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
void F04DetectorConstruction::SetWorldSizeZ (G4double val)
Definition at line 354 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 354 of file F04DetectorConstruction.cc
References fWorldSizeZ, G4State_PreInit, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F04DetectorMessenger::SetNewValue().
G4RotationMatrix F04DetectorConstruction::StringToRotationMatrix (G4String rotation) static
Definition at line 537 of file F04DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 537 of file F04DetectorConstruction.cc
References angle, deg, G4cerr, and G4endl.
Referenced by ConstructDetector().
Member Data Documentation
G4double F04DetectorConstruction::fCaptureMgntB1 private
Definition at line 169 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 169 of file F04DetectorConstruction.hh
Referenced by GetCaptureMgntB1(), and SetCaptureMgntB1().
G4double F04DetectorConstruction::fCaptureMgntB2 private
Definition at line 170 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 170 of file F04DetectorConstruction.hh
Referenced by GetCaptureMgntB2(), and SetCaptureMgntB2().
G4ThreeVector F04DetectorConstruction::fCaptureMgntCenter private
Definition at line 188 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 188 of file F04DetectorConstruction.hh
Referenced by ConstructDetector(), and GetCaptureMgntCenter().
G4double F04DetectorConstruction::fCaptureMgntLength private
Definition at line 167 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 167 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetCaptureMgntLength(), and SetCaptureMgntLength().
G4double F04DetectorConstruction::fCaptureMgntRadius private
Definition at line 168 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 168 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetCaptureMgntRadius(), and SetCaptureMgntRadius().
G4Material* F04DetectorConstruction::fDegraderMaterial private
Definition at line 183 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 183 of file F04DetectorConstruction.hh
Referenced by DefineMaterials(), GetDegraderMaterial(), and SetDegraderMaterial().
G4double F04DetectorConstruction::fDegraderPos private
Definition at line 186 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 186 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetDegraderPos(), and SetDegraderPos().
G4double F04DetectorConstruction::fDegraderRadius private
Definition at line 185 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 185 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetDegraderRadius(), and SetDegraderRadius().
G4double F04DetectorConstruction::fDegraderThickness private
Definition at line 184 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 184 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetDegraderThickness(), and SetDegraderThickness().
F04DetectorMessenger* F04DetectorConstruction::fDetectorMessenger private
Definition at line 136 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 136 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), and ~F04DetectorConstruction().
G4Cache<F04GlobalField*> F04DetectorConstruction::fFieldSetUp private
Definition at line 137 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 137 of file F04DetectorConstruction.hh
Referenced by ConstructSDandField().
G4LogicalVolume* F04DetectorConstruction::fLogicCaptureMgnt private
Definition at line 156 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 156 of file F04DetectorConstruction.hh
Referenced by ConstructDetector(), and GetCaptureMgnt().
G4LogicalVolume* F04DetectorConstruction::fLogicDegrader private
Definition at line 152 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 152 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4LogicalVolume* F04DetectorConstruction::fLogicTarget private
Definition at line 148 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 148 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4LogicalVolume* F04DetectorConstruction::fLogicTransferMgnt private
Definition at line 160 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 160 of file F04DetectorConstruction.hh
Referenced by ConstructDetector(), and GetTransferMgnt().
G4LogicalVolume* F04DetectorConstruction::fLogicWorld private
Definition at line 144 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 144 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
F04Materials* F04DetectorConstruction::fMaterials private
Definition at line 139 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 139 of file F04DetectorConstruction.hh
Referenced by Construct(), and DefineMaterials().
G4VPhysicalVolume* F04DetectorConstruction::fPhysiCaptureMgnt private
Definition at line 157 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 157 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4VPhysicalVolume* F04DetectorConstruction::fPhysiDegrader private
Definition at line 153 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 153 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4VPhysicalVolume* F04DetectorConstruction::fPhysiTarget private
Definition at line 149 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 149 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4VPhysicalVolume* F04DetectorConstruction::fPhysiTransferMgnt private
Definition at line 161 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 161 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4VPhysicalVolume* F04DetectorConstruction::fPhysiWorld private
Definition at line 145 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 145 of file F04DetectorConstruction.hh
Referenced by Construct(), and ConstructDetector().
G4Tubs* F04DetectorConstruction::fSolidCaptureMgnt private
Definition at line 155 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 155 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4Tubs* F04DetectorConstruction::fSolidDegrader private
Definition at line 151 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 151 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4Tubs* F04DetectorConstruction::fSolidTarget private
Definition at line 147 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 147 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4Tubs* F04DetectorConstruction::fSolidTransferMgnt private
Definition at line 159 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 159 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4Tubs* F04DetectorConstruction::fSolidWorld private
Definition at line 143 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 143 of file F04DetectorConstruction.hh
Referenced by ConstructDetector().
G4int F04DetectorConstruction::fTargetAngle private
Definition at line 181 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 181 of file F04DetectorConstruction.hh
Referenced by GetTargetAngle(), and SetTargetAngle().
G4Material* F04DetectorConstruction::fTargetMaterial private
Definition at line 177 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 177 of file F04DetectorConstruction.hh
Referenced by DefineMaterials(), GetTargetMaterial(), and SetTargetMaterial().
G4double F04DetectorConstruction::fTargetPos private
Definition at line 180 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 180 of file F04DetectorConstruction.hh
Referenced by GetTargetPos(), and SetTargetPos().
G4double F04DetectorConstruction::fTargetRadius private
Definition at line 179 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 179 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetTargetRadius(), and SetTargetRadius().
G4double F04DetectorConstruction::fTargetThickness private
Definition at line 178 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 178 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetTargetThickness(), and SetTargetThickness().
G4double F04DetectorConstruction::fTransferMgntB private
Definition at line 174 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 174 of file F04DetectorConstruction.hh
Referenced by GetTransferMgntB(), and SetTransferMgntB().
G4ThreeVector F04DetectorConstruction::fTransferMgntCenter private
Definition at line 188 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 188 of file F04DetectorConstruction.hh
Referenced by ConstructDetector(), and GetTransferMgntCenter().
G4double F04DetectorConstruction::fTransferMgntLength private
Definition at line 172 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 172 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetTransferMgntLength(), and SetTransferMgntLength().
G4double F04DetectorConstruction::fTransferMgntPos private
Definition at line 175 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 175 of file F04DetectorConstruction.hh
Referenced by GetTransferMgntPos(), and SetTransferMgntPos().
G4double F04DetectorConstruction::fTransferMgntRadius private
Definition at line 173 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 173 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetTransferMgntRadius(), and SetTransferMgntRadius().
G4Material* F04DetectorConstruction::fVacuum private
Definition at line 141 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 141 of file F04DetectorConstruction.hh
Referenced by ConstructDetector(), and DefineMaterials().
G4Material* F04DetectorConstruction::fWorldMaterial private
Definition at line 163 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 163 of file F04DetectorConstruction.hh
Referenced by DefineMaterials(), GetWorldMaterial(), and SetWorldMaterial().
G4double F04DetectorConstruction::fWorldSizeR private
Definition at line 164 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 164 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetWorldSizeR(), and SetWorldSizeR().
G4double F04DetectorConstruction::fWorldSizeZ private
Definition at line 165 of file F04DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 165 of file F04DetectorConstruction.hh
Referenced by F04DetectorConstruction(), GetWorldSizeZ(), and SetWorldSizeZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04DetectorConstruction.cc