ECCE @ EIC Software: BiasingOperation Class Reference
BiasingOperation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr08/include/BiasingOperation.hh>
Public Member Functions
BiasingOperation (G4String name)
virtual ~BiasingOperation ()
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &)
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *)
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4ProtonInelasticProcess * fProtonInelasticProcess
G4NeutronInelasticProcess * fNeutronInelasticProcess
G4PionPlusInelasticProcess * fPionPlusInelasticProcess
G4PionMinusInelasticProcess * fPionMinusInelasticProcess
Detailed Description
Definition at line 46 of file BiasingOperation.hh.
View newest version in sPHENIX GitHub at line 46 of file BiasingOperation.hh
Constructor & Destructor Documentation
BiasingOperation::BiasingOperation (G4String name)
Definition at line 54 of file BiasingOperation.cc.
View newest version in sPHENIX GitHub at line 54 of file BiasingOperation.cc
References G4HadronicProcess::AddDataSet(), fNeutronInelasticProcess, fPionMinusInelasticProcess, fPionPlusInelasticProcess, fProtonInelasticProcess, G4HadronicParameters::GetMaxEnergy(), CLHEP::GeV, G4HadronicParameters::Instance(), CLHEP::MeV, G4HadronicProcess::RegisterMe(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), and G4TheoFSGenerator::SetTransport().
BiasingOperation::~BiasingOperation () virtual
Definition at line 125 of file BiasingOperation.cc.
View newest version in sPHENIX GitHub at line 125 of file BiasingOperation.cc
Member Function Documentation
G4VParticleChange * BiasingOperation::ApplyFinalStateBiasing (const G4BiasingProcessInterface * , const G4Track * track, const G4Step * step, G4bool &) virtual
Implements G4VBiasingOperation.
Definition at line 130 of file BiasingOperation.cc.
View newest version in sPHENIX GitHub at line 130 of file BiasingOperation.cc
References G4PionPlus::Definition(), G4PionMinus::Definition(), G4Neutron::Definition(), G4Proton::Definition(), fNeutronInelasticProcess, fPionMinusInelasticProcess, fPionPlusInelasticProcess, fProtonInelasticProcess, G4cerr, G4endl, G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), and G4HadronicProcess::PostStepDoIt().
virtual G4double BiasingOperation::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition *) inline virtual
Implements G4VBiasingOperation.
Definition at line 61 of file BiasingOperation.hh.
View newest version in sPHENIX GitHub at line 61 of file BiasingOperation.hh
References DBL_MAX.
virtual G4VParticleChange* BiasingOperation::GenerateBiasingFinalState (const G4Track * , const G4Step *) inline virtual
Implements G4VBiasingOperation.
Definition at line 63 of file BiasingOperation.hh.
View newest version in sPHENIX GitHub at line 63 of file BiasingOperation.hh
virtual const G4VBiasingInteractionLaw* BiasingOperation::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition &) inline virtual
Implements G4VBiasingOperation.
Definition at line 58 of file BiasingOperation.hh.
View newest version in sPHENIX GitHub at line 58 of file BiasingOperation.hh
Member Data Documentation
G4NeutronInelasticProcess* BiasingOperation::fNeutronInelasticProcess private
Definition at line 67 of file BiasingOperation.hh.
View newest version in sPHENIX GitHub at line 67 of file BiasingOperation.hh
Referenced by ApplyFinalStateBiasing(), and BiasingOperation().
G4PionMinusInelasticProcess* BiasingOperation::fPionMinusInelasticProcess private
Definition at line 69 of file BiasingOperation.hh.
View newest version in sPHENIX GitHub at line 69 of file BiasingOperation.hh
Referenced by ApplyFinalStateBiasing(), and BiasingOperation().
G4PionPlusInelasticProcess* BiasingOperation::fPionPlusInelasticProcess private
Definition at line 68 of file BiasingOperation.hh.
View newest version in sPHENIX GitHub at line 68 of file BiasingOperation.hh
Referenced by ApplyFinalStateBiasing(), and BiasingOperation().
G4ProtonInelasticProcess* BiasingOperation::fProtonInelasticProcess private
Definition at line 66 of file BiasingOperation.hh.
View newest version in sPHENIX GitHub at line 66 of file BiasingOperation.hh
Referenced by ApplyFinalStateBiasing(), and BiasingOperation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr08/include/BiasingOperation.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr08/src/BiasingOperation.cc