ECCE @ EIC Software: Par02EventAction Class Reference
Par02EventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02EventAction.hh>
Public Member Functions
Par02EventAction ()
Par02EventAction (G4bool aSmear)
virtual ~Par02EventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void EndOfEventAction (const G4Event *)
Defines the actions at the end of the event.
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Attributes
G4bool fSmear
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Event action (before/after event processing).
Defines the action at the beginning and at the end of each event. It is invoked by a G4EventManager when a G4Event object is sent (which contains primary vertices and particles created by the Par02PrimaryGeneratorAction).
Author
Anna Zaborowska
Definition at line 44 of file Par02EventAction.hh.
View newest version in sPHENIX GitHub at line 44 of file Par02EventAction.hh
Constructor & Destructor Documentation
Par02EventAction::Par02EventAction ()
A default constructor. Sets the flag fSmear to true indicating that smearing will be performed.
Definition at line 42 of file Par02EventAction.cc.
View newest version in sPHENIX GitHub at line 42 of file Par02EventAction.cc
Par02EventAction::Par02EventAction (G4bool aSmear)
A constructor.
Parameters
aSmear The flag indicating if smearing has to be done.
Definition at line 46 of file Par02EventAction.cc.
View newest version in sPHENIX GitHub at line 46 of file Par02EventAction.cc
Par02EventAction::~Par02EventAction () virtual
Definition at line 51 of file Par02EventAction.cc.
View newest version in sPHENIX GitHub at line 51 of file Par02EventAction.cc
Member Function Documentation
void Par02EventAction::BeginOfEventAction (const G4Event *) virtual
Defines the actions at the beginning of the event. It sets the Par02EventInformation with fSmear flag. It creates all the ntuples defined in Par02Output singleton class.
Reimplemented from G4UserEventAction.
Definition at line 55 of file Par02EventAction.cc.
View newest version in sPHENIX GitHub at line 55 of file Par02EventAction.cc
References Par02Output::CreateNtuples(), fSmear, G4EventManager::GetEventManager(), Par02Output::Instance(), and G4EventManager::SetUserInformation().
void Par02EventAction::EndOfEventAction (const G4Event *) virtual
Defines the actions at the end of the event.
Reimplemented from G4UserEventAction.
Definition at line 63 of file Par02EventAction.cc.
View newest version in sPHENIX GitHub at line 63 of file Par02EventAction.cc
Member Data Documentation
G4bool Par02EventAction::fSmear private
A flag indicating if smearing should be performed. Passed to Par02EventInformation in BeginOfEventAction(const G4Event*).
Definition at line 69 of file Par02EventAction.hh.
View newest version in sPHENIX GitHub at line 69 of file Par02EventAction.hh
Referenced by BeginOfEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02EventAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/src/Par02EventAction.cc