ECCE @ EIC Software: G4FPYBiasedLightFragmentDist Class Reference
G4FPYBiasedLightFragmentDist Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4FPYBiasedLightFragmentDist.hh>
Public Member Functions
G4FPYBiasedLightFragmentDist (G4int WhichIsotope, G4FFGEnumerations::MetaState WhichMetaState, G4FFGEnumerations::FissionCause WhichCause, G4FFGEnumerations::YieldType WhichYieldType, std::istringstream &dataStream)
G4FPYBiasedLightFragmentDist (G4int WhichIsotope, G4FFGEnumerations::MetaState WhichMetaState, G4FFGEnumerations::FissionCause WhichCause, G4FFGEnumerations::YieldType WhichYieldType, G4int Verbosity, std::istringstream &dataStream)
virtual ~G4FPYBiasedLightFragmentDist (void)
Public Member Functions inherited from G4FissionProductYieldDist
G4FissionProductYieldDist (G4int WhichIsotope, G4FFGEnumerations::MetaState WhichMetaState, G4FFGEnumerations::FissionCause WhichCause, G4FFGEnumerations::YieldType WhichYieldType, std::istringstream &dataStream)
G4FissionProductYieldDist (G4int WhichIsotope, G4FFGEnumerations::MetaState WhichMetaState, G4FFGEnumerations::FissionCause WhichCause, G4FFGEnumerations::YieldType WhichYieldType, G4int Verbosity, std::istringstream &dataStream)
G4DynamicParticleVector * G4GetFission (void)
G4Ions * G4GetFissionProduct (void)
void G4SetAlphaProduction (G4double WhatAlphaProduction)
void G4SetEnergy (G4double WhatIncidentEnergy)
void G4SetTernaryProbability (G4double TernaryProbability)
void G4SetVerbosity (G4int WhatVerbosity)
virtual ~G4FissionProductYieldDist (void)
Protected Member Functions
void Initialize (void)
virtual G4Ions * GetFissionProduct (void)
Protected Member Functions inherited from G4FissionProductYieldDist
void CheckAlphaSanity (void)
G4Ions * FindParticle (G4double RandomParticle)
G4Ions * FindParticleExtrapolation (G4double RandomParticle, G4bool LowerEnergyGroupExists)
G4Ions * FindParticleInterpolation (G4double RandomParticle, G4int LowerEnergyGroup)
G4Ions * FindParticleBranchSearch (ProbabilityBranch *Branch, G4double RandomParticle, G4int EnergyGroup1, G4int EnergyGroup2)
virtual void GenerateAlphas (std::vector< G4ReactionProduct * > *Alphas)
virtual void GenerateNeutrons (std::vector< G4ReactionProduct * > *Neutrons)
G4Ions * GetParticleDefinition (G4int Product, G4FFGEnumerations::MetaState MetaState)
G4String MakeDirectoryName (void)
G4String MakeFileName (G4int Isotope, G4FFGEnumerations::MetaState MetaState)
G4DynamicParticle * MakeG4DynamicParticle (G4ReactionProduct *)
G4String MakeIsotopeName (G4int Isotope, G4FFGEnumerations::MetaState MetaState)
virtual void MakeTrees (void)
virtual void ReadProbabilities (void)
void Renormalize (ProbabilityBranch *Branch)
void SampleAlphaEnergies (std::vector< G4ReactionProduct * > *Alphas)
void SampleGammaEnergies (std::vector< G4ReactionProduct * > *Gammas)
void SampleNeutronEnergies (std::vector< G4ReactionProduct * > *Neutrons)
void SetNubar (void)
virtual void SortProbability (G4ENDFYieldDataContainer *YieldData)
void BurnTree (ProbabilityBranch *Branch)
Protected Attributes
G4int HalfWeight_
Protected Attributes inherited from G4FissionProductYieldDist
const G4int Isotope_
const G4FFGEnumerations::MetaState MetaState_
const
G4FFGEnumerations::FissionCause Cause_
const G4FFGEnumerations::YieldType YieldType_
G4ENDFTapeRead * ENDFData_
G4Ions * AlphaDefinition_
G4double AlphaProduction_
G4double TernaryProbability_
G4Gamma * GammaDefinition_
G4double IncidentEnergy_
G4double MeanGammaEnergy_
G4Ions * NeutronDefinition_
G4double Nubar_
G4double NubarWidth_
G4int RemainingZ_
G4int RemainingA_
G4double RemainingEnergy_
G4int Verbosity_
ProbabilityTree * Trees_
G4Ions * SmallestZ_
G4Ions * SmallestA_
G4Ions * LargestZ_
G4Ions * LargestA_
G4int YieldEnergyGroups_
G4double * YieldEnergies_
G4double * MaintainNormalizedData_
G4double * DataTotal_
G4int TreeCount_
G4int BranchCount_
G4IonTable * IonTable_
G4ParticleHPNames * ElementNames_
G4FPYSamplingOps * RandomEngine_
Detailed Description
G4FPYBiasedLightFragmentDist is an inherited class of G4FissionProductYield that only samples the 'light' fission fragments, defined by A < 115
This inherited class of G4FissionProductYield samples only the lighter fission fragments, defined by A < 115
This biasing was implemented because of an artifact that is introduced due to random sampling of fission fragments. Typically small fission fragments (neutrons, alphas, gammas) are sampled after the first fragment is sampled. If a heavy fragment (A >= 115) is sampled first then the resulting lighter fission fragment, after all the other particles have been removed from the available mass, will most likely land far off the neutron drip line.
This implementation reduces the probability that such an improbable nucleus will be created by first sampling the lighter fission fragment and allowing the heavy fission fragment, which has a lot more flexibility for varying neutron populations, to make up the slack.
Definition at line 58 of file G4FPYBiasedLightFragmentDist.hh.
View newest version in sPHENIX GitHub at line 58 of file G4FPYBiasedLightFragmentDist.hh
Constructor & Destructor Documentation
G4FPYBiasedLightFragmentDist::G4FPYBiasedLightFragmentDist (G4int WhichIsotope, G4FFGEnumerations::MetaState WhichMetaState, G4FFGEnumerations::FissionCause WhichCause, G4FFGEnumerations::YieldType WhichYieldType, std::istringstream & dataStream)
Default constructor
Usage:
WhichIsotope: Isotope number of the element in ZZZAAA form
WhichMetaState: GROUND_STATE, META_1, or META_2
WhichCause: SPONTANEOUS or N_INDUCED
WhichYieldType: INDEPENDENT or CUMULATIVE
Notes:
Definition at line 43 of file G4FPYBiasedLightFragmentDist.cc.
View newest version in sPHENIX GitHub at line 43 of file G4FPYBiasedLightFragmentDist.cc
References Initialize().
G4FPYBiasedLightFragmentDist::G4FPYBiasedLightFragmentDist (G4int WhichIsotope, G4FFGEnumerations::MetaState WhichMetaState, G4FFGEnumerations::FissionCause WhichCause, G4FFGEnumerations::YieldType WhichYieldType, G4int Verbosity, std::istringstream & dataStream)
Overloaded constructor
Usage:
WhichIsotope: Isotope number of the element in ZZZAAA form
WhichMetaState: GROUND_STATE, META_1, or META_2
WhichCause: SPONTANEOUS or N_INDUCED
WhichYieldType: INDEPENDENT or CUMULATIVE
Verbosity: Verbosity level
Notes:
Definition at line 59 of file G4FPYBiasedLightFragmentDist.cc.
View newest version in sPHENIX GitHub at line 59 of file G4FPYBiasedLightFragmentDist.cc
References Initialize().
G4FPYBiasedLightFragmentDist::~G4FPYBiasedLightFragmentDist (void) virtual
Default deconstructor. It is a virtual function since G4FPYBiasedLightFragmentDist inherits from G4FissionProductYieldDist
Definition at line 130 of file G4FPYBiasedLightFragmentDist.cc.
View newest version in sPHENIX GitHub at line 130 of file G4FPYBiasedLightFragmentDist.cc
References G4FFG_FUNCTIONENTER__, and G4FFG_FUNCTIONLEAVE__.
Member Function Documentation
G4Ions * G4FPYBiasedLightFragmentDist::GetFissionProduct (void) protected virtual
Selects a fission product from the probability tree, limited by the number of nucleons available to the system
Implements G4FissionProductYieldDist.
Definition at line 88 of file G4FPYBiasedLightFragmentDist.cc.
View newest version in sPHENIX GitHub at line 88 of file G4FPYBiasedLightFragmentDist.cc
References G4FissionProductYieldDist::FindParticle(), G4FFG_FUNCTIONENTER__, G4FFG_FUNCTIONLEAVE__, G4FPYSamplingOps::G4SampleUniform(), HalfWeight_, G4FissionProductYieldDist::RandomEngine_, G4FissionProductYieldDist::RemainingA_, and G4FissionProductYieldDist::RemainingZ_.
void G4FPYBiasedLightFragmentDist::Initialize (void) protected
Initialize is a common function called by all constructors.
Definition at line 77 of file G4FPYBiasedLightFragmentDist.cc.
View newest version in sPHENIX GitHub at line 77 of file G4FPYBiasedLightFragmentDist.cc
References G4FFG_FUNCTIONENTER__, G4FFG_FUNCTIONLEAVE__, HalfWeight_, and G4FissionProductYieldDist::Isotope_.
Referenced by G4FPYBiasedLightFragmentDist().
Member Data Documentation
G4int G4FPYBiasedLightFragmentDist::HalfWeight_ protected
Defines the half-weight of the fission isotope
Definition at line 100 of file G4FPYBiasedLightFragmentDist.hh.
View newest version in sPHENIX GitHub at line 100 of file G4FPYBiasedLightFragmentDist.hh
Referenced by GetFissionProduct(), and Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4FPYBiasedLightFragmentDist.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4FPYBiasedLightFragmentDist.cc