ECCE @ EIC Software: H02SteppingAction Class Reference
H02SteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx02/include/H02SteppingAction.hh>
Public Member Functions
H02SteppingAction ()
virtual ~H02SteppingAction ()
virtual void UserSteppingAction (const G4Step *astep)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 35 of file H02SteppingAction.hh.
View newest version in sPHENIX GitHub at line 35 of file H02SteppingAction.hh
Constructor & Destructor Documentation
H02SteppingAction::H02SteppingAction ()
Definition at line 41 of file H02SteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file H02SteppingAction.cc
H02SteppingAction::~H02SteppingAction () virtual
Definition at line 48 of file H02SteppingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file H02SteppingAction.cc
Member Function Documentation
void H02SteppingAction::UserSteppingAction (const G4Step * astep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 53 of file H02SteppingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file H02SteppingAction.cc
References fAlive, fKillTrackAndSecondaries, PHG4TrackStatusDecode::GetTrackStatus(), G4MuonMinus::MuonMinusDefinition(), and G4MuonPlus::MuonPlusDefinition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx02/include/H02SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx02/src/H02SteppingAction.cc