ECCE @ EIC Software: G4SliceTimer Class Reference
G4SliceTimer Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4SliceTimer.hh>
Public Member Functions
G4SliceTimer ()
void Start ()
void Stop ()
void Clear ()
G4bool IsValid () const
G4double GetRealElapsed () const
G4double GetSystemElapsed () const
G4double GetUserElapsed () const
Private Attributes
G4bool fValidTimes
clock_t fStartRealTime
clock_t fEndRealTime
tms fStartTimes
tms fEndTimes
G4double fRealElapsed
G4double fSystemElapsed
G4double fUserElapsed
Detailed Description
Definition at line 110 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 110 of file G4SliceTimer.hh
Constructor & Destructor Documentation
G4SliceTimer::G4SliceTimer ()
Definition at line 60 of file G4SliceTimer.cc.
View newest version in sPHENIX GitHub at line 60 of file G4SliceTimer.cc
References Clear().
Member Function Documentation
void G4SliceTimer::Clear () inline
Referenced by G4SliceTimer().
G4double G4SliceTimer::GetRealElapsed () const
Definition at line 66 of file G4SliceTimer.cc.
View newest version in sPHENIX GitHub at line 66 of file G4SliceTimer.cc
References fRealElapsed.
Referenced by operator<<().
G4double G4SliceTimer::GetSystemElapsed () const
Definition at line 71 of file G4SliceTimer.cc.
View newest version in sPHENIX GitHub at line 71 of file G4SliceTimer.cc
References fSystemElapsed.
Referenced by operator<<().
G4double G4SliceTimer::GetUserElapsed () const
Definition at line 76 of file G4SliceTimer.cc.
View newest version in sPHENIX GitHub at line 76 of file G4SliceTimer.cc
References fUserElapsed.
Referenced by operator<<().
G4bool G4SliceTimer::IsValid () const inline
Referenced by operator<<().
void G4SliceTimer::Start () inline
void G4SliceTimer::Stop () inline
Member Data Documentation
clock_t G4SliceTimer::fEndRealTime private
Definition at line 127 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 127 of file G4SliceTimer.hh
tms G4SliceTimer::fEndTimes private
Definition at line 128 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 128 of file G4SliceTimer.hh
G4double G4SliceTimer::fRealElapsed private
Definition at line 129 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 129 of file G4SliceTimer.hh
Referenced by GetRealElapsed().
clock_t G4SliceTimer::fStartRealTime private
Definition at line 127 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 127 of file G4SliceTimer.hh
tms G4SliceTimer::fStartTimes private
Definition at line 128 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 128 of file G4SliceTimer.hh
G4double G4SliceTimer::fSystemElapsed private
Definition at line 129 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 129 of file G4SliceTimer.hh
Referenced by GetSystemElapsed().
G4double G4SliceTimer::fUserElapsed private
Definition at line 129 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 129 of file G4SliceTimer.hh
Referenced by GetUserElapsed().
G4bool G4SliceTimer::fValidTimes private
Definition at line 126 of file G4SliceTimer.hh.
View newest version in sPHENIX GitHub at line 126 of file G4SliceTimer.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4SliceTimer.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4SliceTimer.cc