ECCE @ EIC Software: B4dEventAction Class Reference
B4dEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B4/B4d/include/B4dEventAction.hh>
Public Member Functions
B4dEventAction ()
virtual ~B4dEventAction ()
virtual void BeginOfEventAction (const G4Event *event)
virtual void EndOfEventAction (const G4Event *event)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Member Functions
G4THitsMap< G4double > * GetHitsCollection (G4int hcID, const G4Event *event) const
G4double GetSum (G4THitsMap< G4double > *hitsMap) const
void PrintEventStatistics (G4double absoEdep, G4double absoTrackLength, G4double gapEdep, G4double gapTrackLength) const
Private Attributes
G4int fAbsoEdepHCID
G4int fGapEdepHCID
G4int fAbsoTrackLengthHCID
G4int fGapTrackLengthHCID
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Event action class
In EndOfEventAction(), it prints the accumulated quantities of the energy deposit and track lengths of charged particles in Absober and Gap layers stored in the hits collections.
Definition at line 44 of file B4dEventAction.hh.
View newest version in sPHENIX GitHub at line 44 of file B4dEventAction.hh
Constructor & Destructor Documentation
B4dEventAction::B4dEventAction ()
Definition at line 44 of file B4dEventAction.cc.
View newest version in sPHENIX GitHub at line 44 of file B4dEventAction.cc
B4dEventAction::~B4dEventAction () virtual
Definition at line 54 of file B4dEventAction.cc.
View newest version in sPHENIX GitHub at line 54 of file B4dEventAction.cc
Member Function Documentation
void B4dEventAction::BeginOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
Definition at line 112 of file B4dEventAction.cc.
View newest version in sPHENIX GitHub at line 112 of file B4dEventAction.cc
void B4dEventAction::EndOfEventAction (const G4Event * event) virtual
Reimplemented from G4UserEventAction.
Definition at line 117 of file B4dEventAction.cc.
View newest version in sPHENIX GitHub at line 117 of file B4dEventAction.cc
References fAbsoEdepHCID, fAbsoTrackLengthHCID, fGapEdepHCID, fGapTrackLengthHCID, G4cout, G4endl, G4SDManager::GetCollectionID(), GetHitsCollection(), G4RunManager::GetPrintProgress(), G4RunManager::GetRunManager(), G4SDManager::GetSDMpointer(), GetSum(), G4ToolsAnalysisManager::Instance(), and PrintEventStatistics().
G4THitsMap< G4double > * B4dEventAction::GetHitsCollection (G4int hcID, const G4Event * event) const private
Definition at line 60 of file B4dEventAction.cc.
View newest version in sPHENIX GitHub at line 60 of file B4dEventAction.cc
References FatalException, and G4Exception().
Referenced by EndOfEventAction().
G4double B4dEventAction::GetSum (G4THitsMap< G4double > * hitsMap) const private
Definition at line 79 of file B4dEventAction.cc.
View newest version in sPHENIX GitHub at line 79 of file B4dEventAction.cc
References G4VTHitsMap< T, Map_t >::GetMap(), and it.
Referenced by EndOfEventAction().
void B4dEventAction::PrintEventStatistics (G4double absoEdep, G4double absoTrackLength, G4double gapEdep, G4double gapTrackLength) const private
Definition at line 91 of file B4dEventAction.cc.
View newest version in sPHENIX GitHub at line 91 of file B4dEventAction.cc
References G4BestUnit, G4cout, and G4endl.
Referenced by EndOfEventAction().
Member Data Documentation
G4int B4dEventAction::fAbsoEdepHCID private
Definition at line 62 of file B4dEventAction.hh.
View newest version in sPHENIX GitHub at line 62 of file B4dEventAction.hh
Referenced by EndOfEventAction().
G4int B4dEventAction::fAbsoTrackLengthHCID private
Definition at line 64 of file B4dEventAction.hh.
View newest version in sPHENIX GitHub at line 64 of file B4dEventAction.hh
Referenced by EndOfEventAction().
G4int B4dEventAction::fGapEdepHCID private
Definition at line 63 of file B4dEventAction.hh.
View newest version in sPHENIX GitHub at line 63 of file B4dEventAction.hh
Referenced by EndOfEventAction().
G4int B4dEventAction::fGapTrackLengthHCID private
Definition at line 65 of file B4dEventAction.hh.
View newest version in sPHENIX GitHub at line 65 of file B4dEventAction.hh
Referenced by EndOfEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B4/B4d/include/B4dEventAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B4/B4d/src/B4dEventAction.cc