ECCE @ EIC Software: G4FieldManagerStore Class Reference
G4FieldManagerStore Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4FieldManagerStore.hh>
Public Member Functions
void ClearAllChordFindersState ()
~G4FieldManagerStore ()
Static Public Member Functions
static void Register (G4FieldManager *pVolume)
static void DeRegister (G4FieldManager *pVolume)
static G4FieldManagerStore * GetInstance ()
static G4FieldManagerStore * GetInstanceIfExist ()
static void Clean ()
Protected Member Functions
G4FieldManagerStore ()
Static Private Attributes
static G4ThreadLocal
G4FieldManagerStore * fgInstance = nullptr
static G4ThreadLocal G4bool locked = false
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 49 of file G4FieldManagerStore.hh.
View newest version in sPHENIX GitHub at line 49 of file G4FieldManagerStore.hh
Constructor & Destructor Documentation
G4FieldManagerStore::~G4FieldManagerStore ()
Definition at line 57 of file G4FieldManagerStore.cc.
View newest version in sPHENIX GitHub at line 57 of file G4FieldManagerStore.cc
References Clean(), and fgInstance.
G4FieldManagerStore::G4FieldManagerStore () protected
Definition at line 47 of file G4FieldManagerStore.cc.
View newest version in sPHENIX GitHub at line 47 of file G4FieldManagerStore.cc
Referenced by GetInstance().
Member Function Documentation
void G4FieldManagerStore::Clean () static
Definition at line 67 of file G4FieldManagerStore.cc.
View newest version in sPHENIX GitHub at line 67 of file G4FieldManagerStore.cc
References G4cout, G4endl, GetInstance(), locked, and pos().
Referenced by ~G4FieldManagerStore().
void G4FieldManagerStore::ClearAllChordFindersState ()
Definition at line 153 of file G4FieldManagerStore.cc.
View newest version in sPHENIX GitHub at line 153 of file G4FieldManagerStore.cc
References GetInstance(), and G4ChordFinder::ResetStepEstimate().
Referenced by G4MonopoleTransportation::StartTracking(), G4Transportation::StartTracking(), and G4CoupledTransportation::StartTracking().
void G4FieldManagerStore::DeRegister (G4FieldManager * pVolume) static
Definition at line 111 of file G4FieldManagerStore.cc.
View newest version in sPHENIX GitHub at line 111 of file G4FieldManagerStore.cc
References GetInstance(), and locked.
Referenced by G4FieldManager::~G4FieldManager().
G4FieldManagerStore * G4FieldManagerStore::GetInstance (void) static
Definition at line 130 of file G4FieldManagerStore.cc.
View newest version in sPHENIX GitHub at line 130 of file G4FieldManagerStore.cc
References fgInstance, and G4FieldManagerStore().
Referenced by Clean(), ClearAllChordFindersState(), DeRegister(), Register(), G4ITTransportation::StartTracking(), G4MonopoleTransportation::StartTracking(), G4Transportation::StartTracking(), and G4CoupledTransportation::StartTracking().
G4FieldManagerStore * G4FieldManagerStore::GetInstanceIfExist () static
Definition at line 143 of file G4FieldManagerStore.cc.
View newest version in sPHENIX GitHub at line 143 of file G4FieldManagerStore.cc
References fgInstance.
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
void G4FieldManagerStore::Register (G4FieldManager * pVolume) static
Definition at line 102 of file G4FieldManagerStore.cc.
View newest version in sPHENIX GitHub at line 102 of file G4FieldManagerStore.cc
References GetInstance().
Referenced by G4FieldManager::G4FieldManager().
Member Data Documentation
G4ThreadLocal G4FieldManagerStore * G4FieldManagerStore::fgInstance = nullptr static private
Definition at line 76 of file G4FieldManagerStore.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FieldManagerStore.hh
Referenced by GetInstance(), GetInstanceIfExist(), and ~G4FieldManagerStore().
G4ThreadLocal G4bool G4FieldManagerStore::locked = false static private
Definition at line 77 of file G4FieldManagerStore.hh.
View newest version in sPHENIX GitHub at line 77 of file G4FieldManagerStore.hh
Referenced by Clean(), and DeRegister().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4FieldManagerStore.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4FieldManagerStore.cc