ECCE @ EIC Software: ExGflash2DetectorConstruction Class Reference
ExGflash2DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/include/ExGflash2DetectorConstruction.hh>
Public Member Functions
ExGflash2DetectorConstruction ()
~ExGflash2DetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
const G4VPhysicalVolume * GetCristal (int aNumCrystal)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
G4LogicalVolume * fCrystalLog
G4VPhysicalVolume * fCrystalPhys [100]
Static Private Attributes
static G4ThreadLocal
GFlashShowerModel * fFastShowerModel
static G4ThreadLocal
GFlashHomoShowerParameterisation * fParameterisation
static G4ThreadLocal
GFlashParticleBounds * fParticleBounds
static G4ThreadLocal
GFlashHitMaker * fHitMaker
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 44 of file ExGflash2DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 44 of file ExGflash2DetectorConstruction.hh
Constructor & Destructor Documentation
ExGflash2DetectorConstruction::ExGflash2DetectorConstruction ()
Definition at line 58 of file ExGflash2DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 58 of file ExGflash2DetectorConstruction.cc
ExGflash2DetectorConstruction::~ExGflash2DetectorConstruction ()
Initial value:
{
  G4cout<<"ExGflash2DetectorConstruction::Detector constructor"<<G4endl
Definition at line 66 of file ExGflash2DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 66 of file ExGflash2DetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * ExGflash2DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 70 of file ExGflash2DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 70 of file ExGflash2DetectorConstruction.cc
References cm, fCrystalLog, fCrystalPhys, G4NistManager::FindOrBuildMaterial(), G4cout, G4endl, G4VisAttributes::GetInvisible(), G4NistManager::Instance(), n, G4LogicalVolume::SetVisAttributes(), and BTOF::zpos.
void ExGflash2DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 208 of file ExGflash2DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 208 of file ExGflash2DetectorConstruction.cc
References G4SDManager::AddNewDetector(), fCrystalLog, G4SDManager::GetSDMpointer(), and G4LogicalVolume::SetSensitiveDetector().
const G4VPhysicalVolume* ExGflash2DetectorConstruction::GetCristal (int aNumCrystal) inline
Definition at line 54 of file ExGflash2DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 54 of file ExGflash2DetectorConstruction.hh
Referenced by ExGflash2SensitiveDetector::ProcessHits().
Member Data Documentation
G4LogicalVolume* ExGflash2DetectorConstruction::fCrystalLog private
Definition at line 55 of file ExGflash2DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file ExGflash2DetectorConstruction.hh
Referenced by Construct(), and ConstructSDandField().
G4VPhysicalVolume* ExGflash2DetectorConstruction::fCrystalPhys[100] private
Definition at line 60 of file ExGflash2DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 60 of file ExGflash2DetectorConstruction.hh
Referenced by Construct().
G4ThreadLocal GFlashShowerModel* ExGflash2DetectorConstruction::fFastShowerModel static private
Definition at line 62 of file ExGflash2DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 62 of file ExGflash2DetectorConstruction.hh
G4ThreadLocal GFlashHitMaker* ExGflash2DetectorConstruction::fHitMaker static private
Definition at line 65 of file ExGflash2DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 65 of file ExGflash2DetectorConstruction.hh
G4ThreadLocal GFlashHomoShowerParameterisation* ExGflash2DetectorConstruction::fParameterisation static private
Definition at line 63 of file ExGflash2DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 63 of file ExGflash2DetectorConstruction.hh
G4ThreadLocal GFlashParticleBounds* ExGflash2DetectorConstruction::fParticleBounds static private
Definition at line 64 of file ExGflash2DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 64 of file ExGflash2DetectorConstruction.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/include/ExGflash2DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/gflash/gflash2/src/ExGflash2DetectorConstruction.cc