ECCE @ EIC Software: G4ecpssrBaseLixsModel Class Reference
G4ecpssrBaseLixsModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ecpssrBaseLixsModel.hh>
Public Member Functions
G4ecpssrBaseLixsModel ()
~G4ecpssrBaseLixsModel ()
G4double CalculateL1CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)
G4double CalculateL2CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)
G4double CalculateL3CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident)
G4double CalculateVelocity (G4int subShell, G4int zTarget, G4double massIncident, G4double energyIncident)
G4double ExpIntFunction (G4int n, G4double x)
Public Member Functions inherited from G4VecpssrLiModel
G4VecpssrLiModel ()
virtual ~G4VecpssrLiModel ()
Private Types
typedef std::map< double,
std::map< double, double > > TriDimensionMap
typedef std::map< double,
std::vector< double > > VecMap
Private Member Functions
G4ecpssrBaseLixsModel (const G4ecpssrBaseLixsModel &)
G4ecpssrBaseLixsModel & operator= (const G4ecpssrBaseLixsModel &right)
G4double FunctionFL1 (G4double k, G4double theta)
G4double FunctionFL2 (G4double k, G4double theta)
G4double LogLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double LinLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double LinLinInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e)
Private Attributes
TriDimensionMap FL1Data
TriDimensionMap FL2Data
std::vector< double > dummyVec1
std::vector< double > dummyVec2
VecMap aVecMap1
VecMap aVecMap2
G4int verboseLevel
Detailed Description
Definition at line 55 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ecpssrBaseLixsModel.hh
Member Typedef Documentation
typedef std::map<double, std::map<double, double> > G4ecpssrBaseLixsModel::TriDimensionMap private
Definition at line 106 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ecpssrBaseLixsModel.hh
typedef std::map<double, std::vector<double> > G4ecpssrBaseLixsModel::VecMap private
Definition at line 116 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ecpssrBaseLixsModel.hh
Constructor & Destructor Documentation
G4ecpssrBaseLixsModel::G4ecpssrBaseLixsModel ()
Definition at line 43 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ecpssrBaseLixsModel.cc
References aVecMap1, aVecMap2, dummyVec1, dummyVec2, FatalException, FL1Data, FL2Data, G4Exception(), verboseLevel, x1, x2, y1, and y2.
G4ecpssrBaseLixsModel::~G4ecpssrBaseLixsModel ()
Definition at line 116 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 116 of file G4ecpssrBaseLixsModel.cc
G4ecpssrBaseLixsModel::G4ecpssrBaseLixsModel (const G4ecpssrBaseLixsModel &) private
Member Function Documentation
G4double G4ecpssrBaseLixsModel::CalculateL1CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrLiModel.
Definition at line 191 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 191 of file G4ecpssrBaseLixsModel.cc
References G4Alpha::Alpha(), source.hepunit::amu_c2, barn, G4AtomicShell::BindingEnergy(), source.hepunit::Bohr_radius, CalculateVelocity(), e2, source.hepunit::electron_mass_c2, eplus, ExpIntFunction(), FunctionFL1(), G4cout, G4endl, G4Exp(), G4NistManager::GetAtomicMassAmu(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4AtomicTransitionManager::Instance(), G4NistManager::Instance(), pi, G4Proton::Proton(), G4AtomicTransitionManager::Shell(), verboseLevel, and x1.
G4double G4ecpssrBaseLixsModel::CalculateL2CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrLiModel.
Definition at line 394 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 394 of file G4ecpssrBaseLixsModel.cc
References G4Alpha::Alpha(), source.hepunit::amu_c2, barn, G4AtomicShell::BindingEnergy(), source.hepunit::Bohr_radius, CalculateVelocity(), e2, source.hepunit::electron_mass_c2, eplus, ExpIntFunction(), FunctionFL2(), G4cout, G4endl, G4Exp(), G4NistManager::GetAtomicMassAmu(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4AtomicTransitionManager::Instance(), G4NistManager::Instance(), pi, G4Proton::Proton(), G4AtomicTransitionManager::Shell(), verboseLevel, and x2.
G4double G4ecpssrBaseLixsModel::CalculateL3CrossSection (G4int zTarget, G4double massIncident, G4double energyIncident) virtual
Implements G4VecpssrLiModel.
Definition at line 557 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 557 of file G4ecpssrBaseLixsModel.cc
References G4Alpha::Alpha(), source.hepunit::amu_c2, barn, G4AtomicShell::BindingEnergy(), source.hepunit::Bohr_radius, CalculateVelocity(), e2, source.hepunit::electron_mass_c2, eplus, ExpIntFunction(), FunctionFL2(), G4cout, G4endl, G4Exp(), G4NistManager::GetAtomicMassAmu(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4AtomicTransitionManager::Instance(), G4NistManager::Instance(), pi, G4Proton::Proton(), G4AtomicTransitionManager::Shell(), verboseLevel, and x3.
G4double G4ecpssrBaseLixsModel::CalculateVelocity (G4int subShell, G4int zTarget, G4double massIncident, G4double energyIncident)
Definition at line 727 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 727 of file G4ecpssrBaseLixsModel.cc
References G4Alpha::Alpha(), G4AtomicShell::BindingEnergy(), source.hepunit::electron_mass_c2, G4cout, G4endl, G4ParticleDefinition::GetPDGMass(), G4AtomicTransitionManager::Instance(), G4Proton::Proton(), and G4AtomicTransitionManager::Shell().
Referenced by CalculateL1CrossSection(), CalculateL2CrossSection(), and CalculateL3CrossSection().
G4double G4ecpssrBaseLixsModel::ExpIntFunction (G4int n, G4double x)
Definition at line 121 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 121 of file G4ecpssrBaseLixsModel.cc
References a, b, c, d, eps, G4cout, G4endl, G4Exp(), Acts::UnitConstants::h, n, and x.
Referenced by CalculateL1CrossSection(), CalculateL2CrossSection(), and CalculateL3CrossSection().
G4double G4ecpssrBaseLixsModel::FunctionFL1 (G4double k, G4double theta) private
Definition at line 765 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 765 of file G4ecpssrBaseLixsModel.cc
References aVecMap1, dummyVec1, e, FL1Data, G4cout, G4endl, k, QuadInterpolator(), t1, t2, and verboseLevel.
Referenced by CalculateL1CrossSection().
G4double G4ecpssrBaseLixsModel::FunctionFL2 (G4double k, G4double theta) private
Definition at line 856 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 856 of file G4ecpssrBaseLixsModel.cc
References aVecMap2, dummyVec2, e, FL2Data, G4cout, G4endl, k, QuadInterpolator(), t1, t2, and verboseLevel.
Referenced by CalculateL2CrossSection(), and CalculateL3CrossSection().
G4double G4ecpssrBaseLixsModel::LinLinInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 947 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 947 of file G4ecpssrBaseLixsModel.cc
References e1.
G4double G4ecpssrBaseLixsModel::LinLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 959 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 959 of file G4ecpssrBaseLixsModel.cc
References d1, d2, and G4Exp().
G4double G4ecpssrBaseLixsModel::LogLogInterpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 973 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 973 of file G4ecpssrBaseLixsModel.cc
References a, and b.
Referenced by QuadInterpolator().
G4ecpssrBaseLixsModel& G4ecpssrBaseLixsModel::operator= (const G4ecpssrBaseLixsModel & right) private
G4double G4ecpssrBaseLixsModel::QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e) private
Definition at line 988 of file G4ecpssrBaseLixsModel.cc.
View newest version in sPHENIX GitHub at line 988 of file G4ecpssrBaseLixsModel.cc
References LogLogInterpolate().
Referenced by FunctionFL1(), and FunctionFL2().
Member Data Documentation
VecMap G4ecpssrBaseLixsModel::aVecMap1 private
Definition at line 117 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ecpssrBaseLixsModel.hh
Referenced by FunctionFL1(), and G4ecpssrBaseLixsModel().
VecMap G4ecpssrBaseLixsModel::aVecMap2 private
Definition at line 118 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ecpssrBaseLixsModel.hh
Referenced by FunctionFL2(), and G4ecpssrBaseLixsModel().
std::vector<double> G4ecpssrBaseLixsModel::dummyVec1 private
Definition at line 111 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ecpssrBaseLixsModel.hh
Referenced by FunctionFL1(), and G4ecpssrBaseLixsModel().
std::vector<double> G4ecpssrBaseLixsModel::dummyVec2 private
Definition at line 112 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ecpssrBaseLixsModel.hh
Referenced by FunctionFL2(), and G4ecpssrBaseLixsModel().
TriDimensionMap G4ecpssrBaseLixsModel::FL1Data private
Definition at line 108 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ecpssrBaseLixsModel.hh
Referenced by FunctionFL1(), and G4ecpssrBaseLixsModel().
TriDimensionMap G4ecpssrBaseLixsModel::FL2Data private
Definition at line 110 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ecpssrBaseLixsModel.hh
Referenced by FunctionFL2(), and G4ecpssrBaseLixsModel().
G4int G4ecpssrBaseLixsModel::verboseLevel private
Definition at line 120 of file G4ecpssrBaseLixsModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ecpssrBaseLixsModel.hh
Referenced by CalculateL1CrossSection(), CalculateL2CrossSection(), CalculateL3CrossSection(), FunctionFL1(), FunctionFL2(), and G4ecpssrBaseLixsModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4ecpssrBaseLixsModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4ecpssrBaseLixsModel.cc