ECCE @ EIC Software: G4ParticleTableIterator< K, V > Class Template Reference
G4ParticleTableIterator< K, V > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticleTableIterator.hh>
Public Types
typedef std::map< K, V,
std::less< K > > Map
Public Member Functions
G4ParticleTableIterator (Map &adict)
G4bool operator++ ()
G4bool operator() ()
void reset (G4bool ifSkipIon=true)
K * key () const
V value () const
Private Attributes
Map::iterator it
Map * mydict
G4bool defined
G4bool skipIons
Detailed Description
template<class K, class V>
class G4ParticleTableIterator< K, V >
Definition at line 42 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleTableIterator.hh
Member Typedef Documentation
template<class K, class V> typedef std::map<K, V, std::less<K> > G4ParticleTableIterator< K, V >::Map
Definition at line 45 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleTableIterator.hh
Constructor & Destructor Documentation
template<class K, class V> G4ParticleTableIterator< K, V >::G4ParticleTableIterator (Map & adict) inline
Definition at line 46 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleTableIterator.hh
Member Function Documentation
template<class K, class V> K* G4ParticleTableIterator< K, V >::key () const inline
Definition at line 79 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleTableIterator.hh
template<class K, class V> G4bool G4ParticleTableIterator< K, V >::operator() () inline
Definition at line 60 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleTableIterator.hh
References G4ParticleTableIterator< K, V >::defined, G4ParticleTableIterator< K, V >::it, G4ParticleTableIterator< K, V >::mydict, and G4ParticleTableIterator< K, V >::skipIons.
template<class K, class V> G4bool G4ParticleTableIterator< K, V >::operator++ () inline
Definition at line 53 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleTableIterator.hh
References G4ParticleTableIterator< K, V >::defined, G4ParticleTableIterator< K, V >::it, and G4ParticleTableIterator< K, V >::mydict.
template<class K, class V> void G4ParticleTableIterator< K, V >::reset (G4bool ifSkipIon = true) inline
Definition at line 78 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleTableIterator.hh
References G4ParticleTableIterator< K, V >::defined, and G4ParticleTableIterator< K, V >::skipIons.
Referenced by G4ITStepProcessor::ActiveOnlyITProcess(), G4ChannelingOptrMultiParticleChangeCrossSection::AddChargedParticles(), G4PhysicsListHelper::AddTransportation(), LBE::AddTransportation(), G4PhysicsListHelper::CheckParticleList(), G4RunManagerKernel::ConfirmCoupledTransportation(), LBE::ConstructEM(), LBE::ConstructGeneral(), LBE::ConstructHad(), LBE::ConstructOp(), G4ChannelingPhysics::ConstructProcess(), PhysListEmStandard::ConstructProcess(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), G4VParticlePropertyReporter::FillList(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4ProcessPlacer::GetProcessManager(), PHG4Reco::InitRun(), G4RunManagerKernel::PropagateGenericIonID(), G4TextPPRetriever::Retrieve(), G4EmConfigurator::SetModelForRegion(), G4RunManagerKernel::SetScoreSplitter(), G4MTRunManagerKernel::SetUpDecayChannels(), G4RunManagerKernel::SetupPhysics(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4RunManagerKernel::SetupShadowProcess(), and G4ParticleTable::WorkerG4ParticleTable().
template<class K, class V> V G4ParticleTableIterator< K, V >::value () const inline
Definition at line 80 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleTableIterator.hh
Referenced by G4ITStepProcessor::ActiveOnlyITProcess(), G4ChannelingOptrMultiParticleChangeCrossSection::AddChargedParticles(), G4PhysicsListHelper::AddTransportation(), G4PhysicsListHelper::CheckParticleList(), G4RunManagerKernel::ConfirmCoupledTransportation(), G4ChannelingPhysics::ConstructProcess(), PhysListEmStandard::ConstructProcess(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), G4ParticleTable::DeleteAllParticles(), G4ParticleTable::DumpTable(), G4VParticlePropertyReporter::FillList(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4ParticleGunMessenger::G4ParticleGunMessenger(), G4UserPhysicsListMessenger::GetCurrentValue(), G4ParticleMessenger::GetCurrentValue(), G4ParticleTable::GetParticle(), G4ProcessPlacer::GetProcessManager(), PHG4Reco::InitRun(), G4RunManagerKernel::PropagateGenericIonID(), G4TextPPRetriever::Retrieve(), G4ParticleMessenger::SetNewValue(), G4RunManagerKernel::SetScoreSplitter(), G4MTRunManagerKernel::SetUpDecayChannels(), G4RunManagerKernel::SetupPhysics(), G4WorkerRunManagerKernel::SetupShadowProcess(), G4RunManagerKernel::SetupShadowProcess(), and G4ParticleTable::WorkerG4ParticleTable().
Member Data Documentation
template<class K, class V> G4bool G4ParticleTableIterator< K, V >::defined private
Definition at line 85 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleTableIterator.hh
Referenced by G4ParticleTableIterator< K, V >::operator()(), G4ParticleTableIterator< K, V >::operator++(), and G4ParticleTableIterator< K, V >::reset().
template<class K, class V> Map::iterator G4ParticleTableIterator< K, V >::it private
Definition at line 83 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleTableIterator.hh
Referenced by G4ParticleTableIterator< K, V >::operator()(), and G4ParticleTableIterator< K, V >::operator++().
template<class K, class V> Map* G4ParticleTableIterator< K, V >::mydict private
Definition at line 84 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ParticleTableIterator.hh
Referenced by G4ParticleTableIterator< K, V >::operator()(), and G4ParticleTableIterator< K, V >::operator++().
template<class K, class V> G4bool G4ParticleTableIterator< K, V >::skipIons private
Definition at line 86 of file G4ParticleTableIterator.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleTableIterator.hh
Referenced by G4ParticleTableIterator< K, V >::operator()(), and G4ParticleTableIterator< K, V >::reset().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticleTableIterator.hh