ECCE @ EIC Software: G4AnyType::Placeholder Class Reference
G4AnyType::Placeholder Class Reference abstract
Public Member Functions
Placeholder ()
virtual ~Placeholder ()
virtual const std::type_info & TypeInfo () const =0
virtual Placeholder * Clone () const =0
virtual void * Address () const =0
virtual std::string ToString () const =0
virtual void FromString (const std::string &val)=0
Detailed Description
Definition at line 124 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 124 of file G4AnyType.hh
Constructor & Destructor Documentation
G4AnyType::Placeholder::Placeholder () inline
Constructor
Definition at line 127 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 127 of file G4AnyType.hh
virtual G4AnyType::Placeholder::~Placeholder () inline virtual
Destructor
Definition at line 129 of file G4AnyType.hh.
View newest version in sPHENIX GitHub at line 129 of file G4AnyType.hh
Member Function Documentation
virtual void* G4AnyType::Placeholder::Address () const pure virtual
Query
Implemented in G4AnyType::Ref< ValueType >.
Referenced by G4AnyType::Address().
virtual Placeholder* G4AnyType::Placeholder::Clone () const pure virtual
Query
Implemented in G4AnyType::Ref< ValueType >.
virtual void G4AnyType::Placeholder::FromString (const std::string & val) pure virtual
FromString
Implemented in G4AnyType::Ref< ValueType >, G4AnyType::Ref< ValueType >, G4AnyType::Ref< ValueType >, and G4AnyType::Ref< ValueType >.
Referenced by G4AnyType::FromString().
virtual std::string G4AnyType::Placeholder::ToString () const pure virtual
ToString
Implemented in G4AnyType::Ref< ValueType >.
Referenced by G4AnyType::ToString().
virtual const std::type_info& G4AnyType::Placeholder::TypeInfo () const pure virtual
Query
Implemented in G4AnyType::Ref< ValueType >.
Referenced by G4AnyType::TypeInfo().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4AnyType.hh