ECCE @ EIC Software: G4HitsModel Class Reference
G4HitsModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4HitsModel.hh>
Public Member Functions
G4HitsModel ()
virtual ~G4HitsModel ()
virtual void DescribeYourselfTo (G4VGraphicsScene &)
const G4VHit * GetCurrentHit () const
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
virtual G4String GetCurrentDescription () const
virtual G4String GetCurrentTag () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
virtual G4bool Validate (G4bool warn=true)
Private Attributes
const G4VHit * fpCurrentHit
Additional Inherited Members
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Detailed Description
Definition at line 46 of file G4HitsModel.hh.
View newest version in sPHENIX GitHub at line 46 of file G4HitsModel.hh
Constructor & Destructor Documentation
G4HitsModel::G4HitsModel ()
Definition at line 40 of file G4HitsModel.cc.
View newest version in sPHENIX GitHub at line 40 of file G4HitsModel.cc
References G4VModel::fGlobalDescription, G4VModel::fGlobalTag, and G4VModel::fType.
G4HitsModel::~G4HitsModel () virtual
Definition at line 38 of file G4HitsModel.cc.
View newest version in sPHENIX GitHub at line 38 of file G4HitsModel.cc
Member Function Documentation
void G4HitsModel::DescribeYourselfTo (G4VGraphicsScene & sceneHandler) virtual
Implements G4VModel.
Definition at line 48 of file G4HitsModel.cc.
View newest version in sPHENIX GitHub at line 48 of file G4HitsModel.cc
References G4VGraphicsScene::AddCompound(), fpCurrentHit, G4VModel::fpMP, G4ModelingParameters::GetEvent(), and G4VHitsCollection::GetSize().
const G4VHit* G4HitsModel::GetCurrentHit () const inline
Definition at line 57 of file G4HitsModel.hh.
View newest version in sPHENIX GitHub at line 57 of file G4HitsModel.hh
References fpCurrentHit.
Referenced by G4VSceneHandler::LoadAtts().
Member Data Documentation
const G4VHit* G4HitsModel::fpCurrentHit private
Definition at line 62 of file G4HitsModel.hh.
View newest version in sPHENIX GitHub at line 62 of file G4HitsModel.hh
Referenced by DescribeYourselfTo(), and GetCurrentHit().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4HitsModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4HitsModel.cc