ECCE @ EIC Software: CexmcPrimaryGeneratorAction Class Reference
CexmcPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcPrimaryGeneratorAction.hh>
Public Member Functions
CexmcPrimaryGeneratorAction (CexmcPhysicsManager *physicsManager)
~CexmcPrimaryGeneratorAction ()
void GeneratePrimaries (G4Event *event)
void SetFwhmPosX (G4double value, G4bool fromMessenger=true)
void SetFwhmPosY (G4double value, G4bool fromMessenger=true)
void SetFwhmDirX (G4double value, G4bool fromMessenger=true)
void SetFwhmDirY (G4double value, G4bool fromMessenger=true)
void SetFwhmMomentumAmp (G4double value, G4bool fromMessenger=true)
G4double GetFwhmPosX (void) const
G4double GetFwhmPosY (void) const
G4double GetFwhmDirX (void) const
G4double GetFwhmDirY (void) const
G4double GetFwhmMomentumAmp (void) const
CexmcParticleGun * GetParticleGun (void)
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
CexmcParticleGun * particleGun
G4double fwhmPosX
G4double fwhmPosY
G4double fwhmDirX
G4double fwhmDirY
G4double fwhmMomentumAmp
CexmcPrimaryGeneratorActionMessenger * messenger
Detailed Description
Definition at line 56 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 56 of file CexmcPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
CexmcPrimaryGeneratorAction::CexmcPrimaryGeneratorAction (CexmcPhysicsManager * physicsManager) explicit
Definition at line 54 of file CexmcPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 54 of file CexmcPrimaryGeneratorAction.cc
References messenger, and particleGun.
CexmcPrimaryGeneratorAction::~CexmcPrimaryGeneratorAction ()
Definition at line 64 of file CexmcPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 64 of file CexmcPrimaryGeneratorAction.cc
References messenger, and particleGun.
Member Function Documentation
void CexmcPrimaryGeneratorAction::GeneratePrimaries (G4Event * event) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 71 of file CexmcPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 71 of file CexmcPrimaryGeneratorAction.cc
References CexmcFwhmToStddev(), fwhmDirX, fwhmDirY, fwhmMomentumAmp, fwhmPosX, fwhmPosY, G4ParticleGun::GeneratePrimaryVertex(), CexmcParticleGun::GetOrigDirection(), CexmcParticleGun::GetOrigMomentumAmp(), CexmcParticleGun::GetOrigPosition(), particleGun, CexmcParticleGun::PrepareForNewEvent(), G4ParticleGun::SetParticleMomentum(), G4ParticleGun::SetParticleMomentumDirection(), G4VPrimaryGenerator::SetParticlePosition(), and G4INCL::DeJongSpin::shoot().
G4double CexmcPrimaryGeneratorAction::GetFwhmDirX (void) const inline
Definition at line 172 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 172 of file CexmcPrimaryGeneratorAction.hh
References fwhmDirX.
G4double CexmcPrimaryGeneratorAction::GetFwhmDirY (void) const inline
Definition at line 178 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 178 of file CexmcPrimaryGeneratorAction.hh
References fwhmDirY.
G4double CexmcPrimaryGeneratorAction::GetFwhmMomentumAmp (void) const inline
Definition at line 184 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 184 of file CexmcPrimaryGeneratorAction.hh
References fwhmMomentumAmp.
G4double CexmcPrimaryGeneratorAction::GetFwhmPosX (void) const inline
Definition at line 160 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 160 of file CexmcPrimaryGeneratorAction.hh
References fwhmPosX.
G4double CexmcPrimaryGeneratorAction::GetFwhmPosY (void) const inline
Definition at line 166 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 166 of file CexmcPrimaryGeneratorAction.hh
References fwhmPosY.
CexmcParticleGun * CexmcPrimaryGeneratorAction::GetParticleGun (void)
Definition at line 103 of file CexmcPrimaryGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 103 of file CexmcPrimaryGeneratorAction.cc
References particleGun.
Referenced by CexmcChargeExchangeReconstructor::CexmcChargeExchangeReconstructor().
void CexmcPrimaryGeneratorAction::SetFwhmDirX (G4double value, G4bool fromMessenger = true) inline
Definition at line 130 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 130 of file CexmcPrimaryGeneratorAction.hh
References CexmcCmdIsNotAllowed, fwhmDirX, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcPrimaryGeneratorActionMessenger::SetNewValue().
void CexmcPrimaryGeneratorAction::SetFwhmDirY (G4double value, G4bool fromMessenger = true) inline
Definition at line 140 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 140 of file CexmcPrimaryGeneratorAction.hh
References CexmcCmdIsNotAllowed, fwhmDirY, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcPrimaryGeneratorActionMessenger::SetNewValue().
void CexmcPrimaryGeneratorAction::SetFwhmMomentumAmp (G4double value, G4bool fromMessenger = true) inline
Definition at line 150 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 150 of file CexmcPrimaryGeneratorAction.hh
References CexmcCmdIsNotAllowed, fwhmMomentumAmp, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcPrimaryGeneratorActionMessenger::SetNewValue().
void CexmcPrimaryGeneratorAction::SetFwhmPosX (G4double value, G4bool fromMessenger = true) inline
Definition at line 110 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 110 of file CexmcPrimaryGeneratorAction.hh
References CexmcCmdIsNotAllowed, fwhmPosX, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcPrimaryGeneratorActionMessenger::SetNewValue().
void CexmcPrimaryGeneratorAction::SetFwhmPosY (G4double value, G4bool fromMessenger = true) inline
Definition at line 120 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 120 of file CexmcPrimaryGeneratorAction.hh
References CexmcCmdIsNotAllowed, fwhmPosY, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcPrimaryGeneratorActionMessenger::SetNewValue().
Member Data Documentation
G4double CexmcPrimaryGeneratorAction::fwhmDirX private
Definition at line 99 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 99 of file CexmcPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetFwhmDirX(), and SetFwhmDirX().
G4double CexmcPrimaryGeneratorAction::fwhmDirY private
Definition at line 101 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 101 of file CexmcPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetFwhmDirY(), and SetFwhmDirY().
G4double CexmcPrimaryGeneratorAction::fwhmMomentumAmp private
Definition at line 103 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 103 of file CexmcPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetFwhmMomentumAmp(), and SetFwhmMomentumAmp().
G4double CexmcPrimaryGeneratorAction::fwhmPosX private
Definition at line 95 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 95 of file CexmcPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetFwhmPosX(), and SetFwhmPosX().
G4double CexmcPrimaryGeneratorAction::fwhmPosY private
Definition at line 97 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 97 of file CexmcPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetFwhmPosY(), and SetFwhmPosY().
CexmcPrimaryGeneratorActionMessenger* CexmcPrimaryGeneratorAction::messenger private
Definition at line 106 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 106 of file CexmcPrimaryGeneratorAction.hh
Referenced by CexmcPrimaryGeneratorAction(), and ~CexmcPrimaryGeneratorAction().
CexmcParticleGun* CexmcPrimaryGeneratorAction::particleGun private
Definition at line 93 of file CexmcPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 93 of file CexmcPrimaryGeneratorAction.hh
Referenced by CexmcPrimaryGeneratorAction(), GeneratePrimaries(), GetParticleGun(), and ~CexmcPrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcPrimaryGeneratorAction.cc