ECCE @ EIC Software: G4eeToHadronsModel Class Reference
G4eeToHadronsModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeToHadronsModel.hh>
Public Member Functions
G4eeToHadronsModel (G4Vee2hadrons *, G4int ver=0, const G4String &nam="eeToHadrons")
virtual ~G4eeToHadronsModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX) override
virtual G4double ComputeCrossSectionPerElectron (const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin=0.0, G4double maxEnergy=DBL_MAX) override
G4DynamicParticle * GenerateCMPhoton (G4double)
G4double PeakEnergy () const
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Private Member Functions
void ComputeCMCrossSectionPerElectron ()
G4eeToHadronsModel & operator= (const G4eeToHadronsModel &right)=delete
G4eeToHadronsModel (const G4eeToHadronsModel &)=delete
Private Attributes
G4Vee2hadrons * model
G4ParticleDefinition * theGamma
G4PhysicsVector * crossPerElectron
G4PhysicsVector * crossBornPerElectron
G4bool isInitialised
G4int nbins
G4int verbose
G4double lowKinEnergy
G4double peakKinEnergy
G4double highKinEnergy
G4double emin
G4double epeak
G4double emax
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 58 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4eeToHadronsModel.hh
Constructor & Destructor Documentation
G4eeToHadronsModel::G4eeToHadronsModel (G4Vee2hadrons * mod, G4int ver = 0, const G4String & nam = "eeToHadrons") explicit
Definition at line 69 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 69 of file G4eeToHadronsModel.cc
References emax, emin, epeak, G4Gamma::Gamma(), G4VEmModel::HighEnergyLimit(), highKinEnergy, G4VEmModel::LowEnergyLimit(), lowKinEnergy, peakKinEnergy, and theGamma.
G4eeToHadronsModel::~G4eeToHadronsModel () virtual
Definition at line 91 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 91 of file G4eeToHadronsModel.cc
References model.
G4eeToHadronsModel::G4eeToHadronsModel (const G4eeToHadronsModel &) private delete
Member Function Documentation
void G4eeToHadronsModel::ComputeCMCrossSectionPerElectron () private
Definition at line 234 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 234 of file G4eeToHadronsModel.cc
References crossBornPerElectron, crossPerElectron, e, e1, e2, source.hepunit::electron_mass_c2, G4PhysicsVector::Energy(), source.hepunit::fine_structure_const, G4Exp(), G4Log(), LL, nbins, pi, G4PhysicsVector::PutValue(), s1, G4PhysicsVector::Value(), x1, and x2.
Referenced by Initialise().
G4double G4eeToHadronsModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kineticEnergy, G4double Z, G4double A, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) override virtual
Reimplemented from G4VEmModel.
Definition at line 161 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 161 of file G4eeToHadronsModel.cc
References ComputeCrossSectionPerElectron().
G4double G4eeToHadronsModel::ComputeCrossSectionPerElectron (const G4ParticleDefinition * , G4double kineticEnergy, G4double cutEnergy = 0.0, G4double maxEnergy = DBL_MAX) virtual
Definition at line 172 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 172 of file G4eeToHadronsModel.cc
References crossPerElectron, and G4PhysicsVector::Value().
Referenced by ComputeCrossSectionPerAtom(), and CrossSectionPerVolume().
G4double G4eeToHadronsModel::CrossSectionPerVolume (const G4Material * mat, const G4ParticleDefinition * p, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) override virtual
Reimplemented from G4VEmModel.
Definition at line 149 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 149 of file G4eeToHadronsModel.cc
References ComputeCrossSectionPerElectron(), and G4Material::GetElectronDensity().
G4DynamicParticle * G4eeToHadronsModel::GenerateCMPhoton (G4double e)
Definition at line 274 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 274 of file G4eeToHadronsModel.cc
References crossBornPerElectron, dir, e1, source.hepunit::electron_mass_c2, emax, emin, epeak, f, source.hepunit::fine_structure_const, G4cout, G4endl, G4Exp(), G4Log(), G4UniformRand, LL, max, min, nbins, pi, G4InuclParticleNames::s0, s1, CLHEP::Hep3Vector::set(), theGamma, G4PhysicsVector::Value(), x, xmax, and xmin.
Referenced by SampleSecondaries().
void G4eeToHadronsModel::Initialise (const G4ParticleDefinition * , const G4DataVector &) override virtual
Implements G4VEmModel.
Definition at line 98 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 98 of file G4eeToHadronsModel.cc
References ComputeCMCrossSectionPerElectron(), crossBornPerElectron, crossPerElectron, e, emax, emin, G4PhysicsVector::Energy(), epeak, G4cout, G4endl, G4PhysicsVector::GetVectorLength(), isInitialised, MeV, min, nanobarn, nbins, G4PhysicsVector::PutValue(), s1, G4PhysicsVector::Value(), and verbose.
Referenced by G4eeToHadronsMultiModel::AddEEModel().
G4eeToHadronsModel& G4eeToHadronsModel::operator= (const G4eeToHadronsModel & right) private delete
G4double G4eeToHadronsModel::PeakEnergy () const inline
Definition at line 127 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 127 of file G4eeToHadronsModel.hh
References peakKinEnergy.
void G4eeToHadronsModel::SampleSecondaries (std::vector< G4DynamicParticle * > * newp, const G4MaterialCutsCouple * , const G4DynamicParticle * dParticle, G4double tmin = 0.0, G4double maxEnergy = DBL_MAX) override virtual
Implements G4VEmModel.
Definition at line 182 of file G4eeToHadronsModel.cc.
View newest version in sPHENIX GitHub at line 182 of file G4eeToHadronsModel.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), crossPerElectron, dir, e, CLHEP::HepLorentzVector::e(), source.hepunit::electron_mass_c2, emin, G4cout, G4endl, GenerateCMPhoton(), G4DynamicParticle::Get4Momentum(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), CLHEP::HepLorentzVector::m(), mass, MeV, G4DynamicParticle::Set4Momentum(), t, and v.
Member Data Documentation
G4PhysicsVector* G4eeToHadronsModel::crossBornPerElectron private
Definition at line 111 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4eeToHadronsModel.hh
Referenced by ComputeCMCrossSectionPerElectron(), GenerateCMPhoton(), and Initialise().
G4PhysicsVector* G4eeToHadronsModel::crossPerElectron private
Definition at line 110 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4eeToHadronsModel.hh
Referenced by ComputeCMCrossSectionPerElectron(), ComputeCrossSectionPerElectron(), Initialise(), and SampleSecondaries().
G4double G4eeToHadronsModel::emax private
Definition at line 122 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 122 of file G4eeToHadronsModel.hh
Referenced by G4eeToHadronsModel(), GenerateCMPhoton(), and Initialise().
G4double G4eeToHadronsModel::emin private
Definition at line 120 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4eeToHadronsModel.hh
Referenced by G4eeToHadronsModel(), GenerateCMPhoton(), Initialise(), and SampleSecondaries().
G4double G4eeToHadronsModel::epeak private
Definition at line 121 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 121 of file G4eeToHadronsModel.hh
Referenced by G4eeToHadronsModel(), GenerateCMPhoton(), and Initialise().
G4double G4eeToHadronsModel::highKinEnergy private
Definition at line 118 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4eeToHadronsModel.hh
Referenced by G4eeToHadronsModel().
G4bool G4eeToHadronsModel::isInitialised private
Definition at line 112 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4eeToHadronsModel.hh
Referenced by Initialise().
G4double G4eeToHadronsModel::lowKinEnergy private
Definition at line 116 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4eeToHadronsModel.hh
Referenced by G4eeToHadronsModel().
G4Vee2hadrons* G4eeToHadronsModel::model private
Definition at line 108 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4eeToHadronsModel.hh
Referenced by ~G4eeToHadronsModel().
G4int G4eeToHadronsModel::nbins private
Definition at line 113 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4eeToHadronsModel.hh
Referenced by ComputeCMCrossSectionPerElectron(), GenerateCMPhoton(), and Initialise().
G4double G4eeToHadronsModel::peakKinEnergy private
Definition at line 117 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4eeToHadronsModel.hh
Referenced by G4eeToHadronsModel(), and PeakEnergy().
G4ParticleDefinition* G4eeToHadronsModel::theGamma private
Definition at line 109 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4eeToHadronsModel.hh
Referenced by G4eeToHadronsModel(), and GenerateCMPhoton().
G4int G4eeToHadronsModel::verbose private
Definition at line 114 of file G4eeToHadronsModel.hh.
View newest version in sPHENIX GitHub at line 114 of file G4eeToHadronsModel.hh
Referenced by Initialise().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4eeToHadronsModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/src/G4eeToHadronsModel.cc