ECCE @ EIC Software: GIDI_settings_flux_order Class Reference
GIDI_settings_flux_order Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh>
Public Member Functions
GIDI_settings_flux_order (int order)
GIDI_settings_flux_order (int order, int length, double const *energies, double const *fluxes)
GIDI_settings_flux_order (int order, std::vector< double > const &energies, std::vector< double > const &fluxes)
GIDI_settings_flux_order (GIDI_settings_flux_order const &fluxOrder)
GIDI_settings_flux_order & operator= (const GIDI_settings_flux_order &fluxOrder)
~GIDI_settings_flux_order ()
int getOrder (void) const
int size (void) const
double const * getEnergies (void) const
double const * getFluxes (void) const
void print (int valuesPerLine=10) const
Private Member Functions
void initialize (int order, int length, double const *energies, double const *fluxes)
Private Attributes
int mOrder
std::vector< double > mEnergies
std::vector< double > mFluxes
Detailed Description
This class stores the flux for one Legendre order (see class GIDI_settings_flux).
Definition at line 92 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 92 of file GIDI_settings.hh
Constructor & Destructor Documentation
GIDI_settings_flux_order::GIDI_settings_flux_order (int order)
Parameters
order The Legendre order for this flux data.
Definition at line 15 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 15 of file GIDI_settings_flux.cc
References mOrder.
GIDI_settings_flux_order::GIDI_settings_flux_order (int order, int length, double const * energies, double const * fluxes)
Parameters
order The Legendre order for this flux data.
length The number or values in energies and fluxes.
energies List of energies where flux is given.
fluxes List of flux value for each energies value.
Definition at line 23 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 23 of file GIDI_settings_flux.cc
References initialize().
GIDI_settings_flux_order::GIDI_settings_flux_order (int order, std::vector< double > const & energies, std::vector< double > const & fluxes)
Parameters
order The Legendre order for this flux data.
energies List of energies where flux is given.
fluxes List of flux value for each energies value.
Definition at line 30 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 30 of file GIDI_settings_flux.cc
References initialize(), int(), and BTOF::length.
GIDI_settings_flux_order::GIDI_settings_flux_order (GIDI_settings_flux_order const & fluxOrder)
Parameters
fluxOrder Legendre flux order to copy.
Definition at line 40 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 40 of file GIDI_settings_flux.cc
References initialize(), mEnergies, mFluxes, mOrder, and size().
GIDI_settings_flux_order::~GIDI_settings_flux_order ()
Definition at line 68 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 68 of file GIDI_settings_flux.cc
Member Function Documentation
double const* GIDI_settings_flux_order::getEnergies (void) const inline
Definition at line 114 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 114 of file GIDI_settings.hh
References mEnergies.
double const* GIDI_settings_flux_order::getFluxes (void) const inline
Definition at line 115 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 115 of file GIDI_settings.hh
References mFluxes.
int GIDI_settings_flux_order::getOrder (void) const inline
Definition at line 112 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 112 of file GIDI_settings.hh
References mOrder.
Referenced by GIDI_settings_flux::addFluxOrder().
void GIDI_settings_flux_order::initialize (int order, int length, double const * energies, double const * fluxes) private
Definition at line 47 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 47 of file GIDI_settings_flux.cc
References BTOF::length, mEnergies, mFluxes, and mOrder.
Referenced by GIDI_settings_flux_order(), and operator=().
GIDI_settings_flux_order & GIDI_settings_flux_order::operator= (const GIDI_settings_flux_order & fluxOrder)
Definition at line 59 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 59 of file GIDI_settings_flux.cc
References initialize(), mEnergies, mFluxes, mOrder, and size().
void GIDI_settings_flux_order::print (int valuesPerLine = 10) const
Definition at line 74 of file GIDI_settings_flux.cc.
View newest version in sPHENIX GitHub at line 74 of file GIDI_settings_flux.cc
References buffer, int(), mEnergies, mFluxes, mOrder, and nE.
int GIDI_settings_flux_order::size (void) const inline
Definition at line 113 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 113 of file GIDI_settings.hh
References mEnergies.
Referenced by GIDI_settings_flux_order(), and operator=().
Member Data Documentation
std::vector<double> GIDI_settings_flux_order::mEnergies private
List of flux energies.
Definition at line 96 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 96 of file GIDI_settings.hh
Referenced by getEnergies(), GIDI_settings_flux_order(), initialize(), operator=(), print(), and size().
std::vector<double> GIDI_settings_flux_order::mFluxes private
List of flux values - one for each element of mEnergies.
Definition at line 97 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 97 of file GIDI_settings.hh
Referenced by getFluxes(), GIDI_settings_flux_order(), initialize(), operator=(), and print().
int GIDI_settings_flux_order::mOrder private
The Legendre order of the flux.
Definition at line 95 of file GIDI_settings.hh.
View newest version in sPHENIX GitHub at line 95 of file GIDI_settings.hh
Referenced by getOrder(), GIDI_settings_flux_order(), initialize(), operator=(), and print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/GIDI_settings.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/GIDI_settings_flux.cc