ECCE @ EIC Software: G4ChipsKaonZeroInelasticXS Class Reference
G4ChipsKaonZeroInelasticXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsKaonZeroInelasticXS.hh>
Public Member Functions
G4ChipsKaonZeroInelasticXS ()
~G4ChipsKaonZeroInelasticXS ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsIsoApplicable (const G4DynamicParticle *Pt, G4int Z, G4int A, const G4Element *elm, const G4Material *mat)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int tgZ, G4int A, const G4Isotope *iso=0, const G4Element *elm=0, const G4Material *mat=0)
G4double GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Attributes
G4ChipsKaonMinusInelasticXS * theKMinusCS
G4ChipsKaonPlusInelasticXS * theKPlusCS
G4double * lastLEN
G4double * lastHEN
G4int lastN
G4int lastZ
G4double lastP
G4double lastTH
G4double lastCS
G4int lastI
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 49 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ChipsKaonZeroInelasticXS.hh
Constructor & Destructor Documentation
G4ChipsKaonZeroInelasticXS::G4ChipsKaonZeroInelasticXS ()
Definition at line 54 of file G4ChipsKaonZeroInelasticXS.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ChipsKaonZeroInelasticXS.cc
References G4ChipsKaonMinusInelasticXS::Default_Name(), G4ChipsKaonPlusInelasticXS::Default_Name(), G4CrossSectionDataSetRegistry::GetCrossSectionDataSet(), G4CrossSectionDataSetRegistry::Instance(), lastCS, lastHEN, lastI, lastLEN, lastN, lastP, lastTH, lastZ, theKMinusCS, and theKPlusCS.
G4ChipsKaonZeroInelasticXS::~G4ChipsKaonZeroInelasticXS ()
Definition at line 70 of file G4ChipsKaonZeroInelasticXS.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ChipsKaonZeroInelasticXS.cc
Member Function Documentation
void G4ChipsKaonZeroInelasticXS::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 75 of file G4ChipsKaonZeroInelasticXS.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ChipsKaonZeroInelasticXS.cc
static const char* G4ChipsKaonZeroInelasticXS::Default_Name () inline static
Definition at line 59 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by LBE::ConstructHad(), GammaRayTelHadronPhysics::ConstructProcess(), and G4ChipsComponentXS::G4ChipsComponentXS().
G4double G4ChipsKaonZeroInelasticXS::GetChipsCrossSection (G4double momentum, G4int Z, G4int N, G4int pdg)
Definition at line 106 of file G4ChipsKaonZeroInelasticXS.cc.
View newest version in sPHENIX GitHub at line 106 of file G4ChipsKaonZeroInelasticXS.cc
References G4ChipsKaonMinusInelasticXS::GetChipsCrossSection(), G4ChipsKaonPlusInelasticXS::GetChipsCrossSection(), theKMinusCS, and theKPlusCS.
Referenced by GetIsoCrossSection().
G4double G4ChipsKaonZeroInelasticXS::GetIsoCrossSection (const G4DynamicParticle * Pt, G4int tgZ, G4int A, const G4Isotope * iso = 0, const G4Element * elm = 0, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 95 of file G4ChipsKaonZeroInelasticXS.cc.
View newest version in sPHENIX GitHub at line 95 of file G4ChipsKaonZeroInelasticXS.cc
References GetChipsCrossSection(), G4DynamicParticle::GetTotalMomentum(), and N.
G4bool G4ChipsKaonZeroInelasticXS::IsIsoApplicable (const G4DynamicParticle * Pt, G4int Z, G4int A, const G4Element * elm, const G4Material * mat) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 83 of file G4ChipsKaonZeroInelasticXS.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ChipsKaonZeroInelasticXS.cc
Member Data Documentation
G4double G4ChipsKaonZeroInelasticXS::lastCS private
Definition at line 87 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS().
G4double* G4ChipsKaonZeroInelasticXS::lastHEN private
Definition at line 82 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS().
G4int G4ChipsKaonZeroInelasticXS::lastI private
Definition at line 88 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS().
G4double* G4ChipsKaonZeroInelasticXS::lastLEN private
Definition at line 81 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS().
G4int G4ChipsKaonZeroInelasticXS::lastN private
Definition at line 83 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS().
G4double G4ChipsKaonZeroInelasticXS::lastP private
Definition at line 85 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS().
G4double G4ChipsKaonZeroInelasticXS::lastTH private
Definition at line 86 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS().
G4int G4ChipsKaonZeroInelasticXS::lastZ private
Definition at line 84 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS().
G4ChipsKaonMinusInelasticXS* G4ChipsKaonZeroInelasticXS::theKMinusCS private
Definition at line 78 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS(), and GetChipsCrossSection().
G4ChipsKaonPlusInelasticXS* G4ChipsKaonZeroInelasticXS::theKPlusCS private
Definition at line 79 of file G4ChipsKaonZeroInelasticXS.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ChipsKaonZeroInelasticXS.hh
Referenced by G4ChipsKaonZeroInelasticXS(), and GetChipsCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ChipsKaonZeroInelasticXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ChipsKaonZeroInelasticXS.cc