ECCE @ EIC Software: XrayFluoPhysicsListMessenger Class Reference
XrayFluoPhysicsListMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoPhysicsListMessenger.hh>
Public Member Functions
XrayFluoPhysicsListMessenger (XrayFluoPhysicsList *)
virtual ~XrayFluoPhysicsListMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
XrayFluoPhysicsList * pPhysicsList
G4UIdirectory * physDir
G4UIcmdWithAString * pListCmd
G4UIcmdWithADoubleAndUnit * gammaCutCmd
G4UIcmdWithADoubleAndUnit * electCutCmd
G4UIcmdWithADoubleAndUnit * protoCutCmd
G4UIcmdWithADoubleAndUnit * allCutCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 46 of file XrayFluoPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 46 of file XrayFluoPhysicsListMessenger.hh
Constructor & Destructor Documentation
XrayFluoPhysicsListMessenger::XrayFluoPhysicsListMessenger (XrayFluoPhysicsList * pPhys)
Definition at line 43 of file XrayFluoPhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 43 of file XrayFluoPhysicsListMessenger.cc
References allCutCmd, G4UIcommand::AvailableForStates(), electCutCmd, G4State_Idle, G4State_PreInit, gammaCutCmd, physDir, pListCmd, protoCutCmd, G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
XrayFluoPhysicsListMessenger::~XrayFluoPhysicsListMessenger () virtual
Definition at line 96 of file XrayFluoPhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 96 of file XrayFluoPhysicsListMessenger.cc
References allCutCmd, electCutCmd, gammaCutCmd, physDir, pListCmd, and protoCutCmd.
Member Function Documentation
void XrayFluoPhysicsListMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 110 of file XrayFluoPhysicsListMessenger.cc.
View newest version in sPHENIX GitHub at line 110 of file XrayFluoPhysicsListMessenger.cc
References XrayFluoPhysicsList::AddPhysicsList(), allCutCmd, electCutCmd, gammaCutCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4RunManager::GetRunManager(), G4RunManager::PhysicsHasBeenModified(), pListCmd, pPhysicsList, protoCutCmd, XrayFluoPhysicsList::SetCutForElectron(), XrayFluoPhysicsList::SetCutForGamma(), XrayFluoPhysicsList::SetCutForPositron(), and XrayFluoPhysicsList::SetCutForProton().
Member Data Documentation
G4UIcmdWithADoubleAndUnit* XrayFluoPhysicsListMessenger::allCutCmd private
Definition at line 64 of file XrayFluoPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file XrayFluoPhysicsListMessenger.hh
Referenced by SetNewValue(), XrayFluoPhysicsListMessenger(), and ~XrayFluoPhysicsListMessenger().
G4UIcmdWithADoubleAndUnit* XrayFluoPhysicsListMessenger::electCutCmd private
Definition at line 62 of file XrayFluoPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file XrayFluoPhysicsListMessenger.hh
Referenced by SetNewValue(), XrayFluoPhysicsListMessenger(), and ~XrayFluoPhysicsListMessenger().
G4UIcmdWithADoubleAndUnit* XrayFluoPhysicsListMessenger::gammaCutCmd private
Definition at line 61 of file XrayFluoPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file XrayFluoPhysicsListMessenger.hh
Referenced by SetNewValue(), XrayFluoPhysicsListMessenger(), and ~XrayFluoPhysicsListMessenger().
G4UIdirectory* XrayFluoPhysicsListMessenger::physDir private
Definition at line 59 of file XrayFluoPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 59 of file XrayFluoPhysicsListMessenger.hh
Referenced by XrayFluoPhysicsListMessenger(), and ~XrayFluoPhysicsListMessenger().
G4UIcmdWithAString* XrayFluoPhysicsListMessenger::pListCmd private
Definition at line 60 of file XrayFluoPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file XrayFluoPhysicsListMessenger.hh
Referenced by SetNewValue(), XrayFluoPhysicsListMessenger(), and ~XrayFluoPhysicsListMessenger().
XrayFluoPhysicsList* XrayFluoPhysicsListMessenger::pPhysicsList private
Definition at line 57 of file XrayFluoPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 57 of file XrayFluoPhysicsListMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithADoubleAndUnit* XrayFluoPhysicsListMessenger::protoCutCmd private
Definition at line 63 of file XrayFluoPhysicsListMessenger.hh.
View newest version in sPHENIX GitHub at line 63 of file XrayFluoPhysicsListMessenger.hh
Referenced by SetNewValue(), XrayFluoPhysicsListMessenger(), and ~XrayFluoPhysicsListMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoPhysicsListMessenger.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoPhysicsListMessenger.cc