ECCE @ EIC Software: MCGIDI_quantitiesLookupModes Class Reference
MCGIDI_quantitiesLookupModes Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/MCGIDI.h>
Public Member Functions
MCGIDI_quantitiesLookupModes (int projectilesPOPID)
~MCGIDI_quantitiesLookupModes ()
double getProjectileEnergy (void) const
void setProjectileEnergy (double e_in)
int getGroupIndex (void) const
int setGroupIndex (GIDI_settings const &settings, bool encloseOutOfRange)
double getTemperature (void) const
void setTemperature (double temperature)
enum MCGIDI_quantityLookupMode getMode (std::string const &quantity) const
enum MCGIDI_quantityLookupMode getCrossSectionMode (void) const
std::vector< std::string > getListOfLookupQuanities () const
void setMode (std::string const &quantity, enum MCGIDI_quantityLookupMode mode)
void setCrossSectionMode (enum MCGIDI_quantityLookupMode mode)
void setModeAll (enum MCGIDI_quantityLookupMode mode)
Private Attributes
int mProjectilesPOPID
double mProjectileEnergy
int mGroupIndex
double mProjectileEnergyForGroupIndex
double mTemperature
enum MCGIDI_quantityLookupMode mCrossSectionMode
enum MCGIDI_quantityLookupMode mMultiplicityMode
Detailed Description
Definition at line 82 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 82 of file MCGIDI.h
Constructor & Destructor Documentation
MCGIDI_quantitiesLookupModes::MCGIDI_quantitiesLookupModes (int projectilesPOPID)
Definition at line 12 of file MCGIDI_quantitiesLookupMode.cc.
View newest version in sPHENIX GitHub at line 12 of file MCGIDI_quantitiesLookupMode.cc
References MCGIDI_quantityLookupMode_pointwise, mCrossSectionMode, mGroupIndex, mMultiplicityMode, mProjectileEnergy, mProjectileEnergyForGroupIndex, mProjectilesPOPID, and mTemperature.
MCGIDI_quantitiesLookupModes::~MCGIDI_quantitiesLookupModes ()
Definition at line 25 of file MCGIDI_quantitiesLookupMode.cc.
View newest version in sPHENIX GitHub at line 25 of file MCGIDI_quantitiesLookupMode.cc
Member Function Documentation
enum MCGIDI_quantityLookupMode MCGIDI_quantitiesLookupModes::getCrossSectionMode (void) const inline
Definition at line 107 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 107 of file MCGIDI.h
References mCrossSectionMode.
Referenced by MCGIDI_reaction_getCrossSectionAtE(), MCGIDI_target_heated_getTotalCrossSectionAtE(), and MCGIDI_target_sampleReaction().
int MCGIDI_quantitiesLookupModes::getGroupIndex (void) const inline
Definition at line 100 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 100 of file MCGIDI.h
References mGroupIndex.
Referenced by MCGIDI_reaction_getCrossSectionAtE(), MCGIDI_target_heated_getTotalCrossSectionAtE(), and MCGIDI_target_sampleReaction().
std::vector< std::string > MCGIDI_quantitiesLookupModes::getListOfLookupQuanities () const
Definition at line 59 of file MCGIDI_quantitiesLookupMode.cc.
View newest version in sPHENIX GitHub at line 59 of file MCGIDI_quantitiesLookupMode.cc
enum MCGIDI_quantityLookupMode MCGIDI_quantitiesLookupModes::getMode (std::string const & quantity) const
Definition at line 46 of file MCGIDI_quantitiesLookupMode.cc.
View newest version in sPHENIX GitHub at line 46 of file MCGIDI_quantitiesLookupMode.cc
References mCrossSectionMode, and mMultiplicityMode.
double MCGIDI_quantitiesLookupModes::getProjectileEnergy (void) const inline
Definition at line 97 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 97 of file MCGIDI.h
References mProjectileEnergy.
Referenced by MCGIDI_angular_sampleMu(), MCGIDI_energy_sampleEnergy(), MCGIDI_energy_sampleWeightedFunctional(), MCGIDI_KalbachMann_sampleEp(), MCGIDI_kinetics_COM2Lab(), MCGIDI_outputChannel_sampleProductsAtE(), MCGIDI_reaction_getCrossSectionAtE(), MCGIDI_sampling_doubleDistribution(), MCGIDI_target_heated_getTotalCrossSectionAtE(), MCGIDI_target_sampleNullReactionProductsAtE(), and MCGIDI_target_sampleReaction().
double MCGIDI_quantitiesLookupModes::getTemperature (void) const inline
Definition at line 103 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 103 of file MCGIDI.h
References mTemperature.
Referenced by MCGIDI_target_getIndexReactionCrossSectionAtE(), MCGIDI_target_getTotalCrossSectionAtTAndE(), and MCGIDI_target_sampleReaction().
void MCGIDI_quantitiesLookupModes::setCrossSectionMode (enum MCGIDI_quantityLookupMode mode) inline
Definition at line 110 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 110 of file MCGIDI.h
References mCrossSectionMode.
Referenced by G4GIDI_target::getElasticFinalState(), G4GIDI_target::getFinalState(), G4GIDI_target::getTotalCrossSectionAtE(), G4GIDI_target::sampleChannelCrossSectionAtE(), and G4GIDI_target::sumChannelCrossSectionAtE().
int MCGIDI_quantitiesLookupModes::setGroupIndex (GIDI_settings const & settings, bool encloseOutOfRange)
Definition at line 31 of file MCGIDI_quantitiesLookupMode.cc.
View newest version in sPHENIX GitHub at line 31 of file MCGIDI_quantitiesLookupMode.cc
References GIDI_settings_particle::getGroupIndexFromEnergy(), GIDI_settings::getParticle(), mGroupIndex, mProjectileEnergy, mProjectileEnergyForGroupIndex, mProjectilesPOPID, and particle.
void MCGIDI_quantitiesLookupModes::setMode (std::string const & quantity, enum MCGIDI_quantityLookupMode mode)
Definition at line 71 of file MCGIDI_quantitiesLookupMode.cc.
View newest version in sPHENIX GitHub at line 71 of file MCGIDI_quantitiesLookupMode.cc
References mCrossSectionMode, and mMultiplicityMode.
void MCGIDI_quantitiesLookupModes::setModeAll (enum MCGIDI_quantityLookupMode mode)
Definition at line 84 of file MCGIDI_quantitiesLookupMode.cc.
View newest version in sPHENIX GitHub at line 84 of file MCGIDI_quantitiesLookupMode.cc
References mCrossSectionMode, and mMultiplicityMode.
void MCGIDI_quantitiesLookupModes::setProjectileEnergy (double e_in) inline
Definition at line 98 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 98 of file MCGIDI.h
References mProjectileEnergy.
Referenced by G4GIDI_target::getElasticFinalState(), G4GIDI_target::getFinalState(), G4GIDI_target::getTotalCrossSectionAtE(), G4GIDI_target::sampleChannelCrossSectionAtE(), and G4GIDI_target::sumChannelCrossSectionAtE().
void MCGIDI_quantitiesLookupModes::setTemperature (double temperature) inline
Definition at line 104 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 104 of file MCGIDI.h
References mTemperature.
Referenced by G4GIDI_target::getElasticFinalState(), G4GIDI_target::getFinalState(), G4GIDI_target::getTotalCrossSectionAtE(), G4GIDI_target::sampleChannelCrossSectionAtE(), and G4GIDI_target::sumChannelCrossSectionAtE().
Member Data Documentation
enum MCGIDI_quantityLookupMode MCGIDI_quantitiesLookupModes::mCrossSectionMode private
Definition at line 90 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 90 of file MCGIDI.h
Referenced by getCrossSectionMode(), getMode(), MCGIDI_quantitiesLookupModes(), setCrossSectionMode(), setMode(), and setModeAll().
int MCGIDI_quantitiesLookupModes::mGroupIndex private
Definition at line 87 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 87 of file MCGIDI.h
Referenced by getGroupIndex(), MCGIDI_quantitiesLookupModes(), and setGroupIndex().
enum MCGIDI_quantityLookupMode MCGIDI_quantitiesLookupModes::mMultiplicityMode private
Definition at line 91 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 91 of file MCGIDI.h
Referenced by getMode(), MCGIDI_quantitiesLookupModes(), setMode(), and setModeAll().
double MCGIDI_quantitiesLookupModes::mProjectileEnergy private
Definition at line 86 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 86 of file MCGIDI.h
Referenced by getProjectileEnergy(), MCGIDI_quantitiesLookupModes(), setGroupIndex(), and setProjectileEnergy().
double MCGIDI_quantitiesLookupModes::mProjectileEnergyForGroupIndex private
Definition at line 88 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 88 of file MCGIDI.h
Referenced by MCGIDI_quantitiesLookupModes(), and setGroupIndex().
int MCGIDI_quantitiesLookupModes::mProjectilesPOPID private
Definition at line 85 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 85 of file MCGIDI.h
Referenced by MCGIDI_quantitiesLookupModes(), and setGroupIndex().
double MCGIDI_quantitiesLookupModes::mTemperature private
Definition at line 89 of file MCGIDI.h.
View newest version in sPHENIX GitHub at line 89 of file MCGIDI.h
Referenced by getTemperature(), MCGIDI_quantitiesLookupModes(), and setTemperature().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/MCGIDI.h
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_quantitiesLookupMode.cc