ECCE @ EIC Software: G4ILawTruncatedExp Class Reference
G4ILawTruncatedExp Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4ILawTruncatedExp.hh>
Public Member Functions
G4ILawTruncatedExp (G4String name="expForceInteractionLaw")
virtual ~G4ILawTruncatedExp ()
virtual G4double ComputeEffectiveCrossSectionAt (G4double length) const
virtual G4double ComputeNonInteractionProbabilityAt (G4double length) const
virtual G4double SampleInteractionLength ()
virtual G4double UpdateInteractionLengthForStep (G4double truePathLength)
virtual G4bool IsSingular () const
void SetForceCrossSection (G4double xs)
void SetMaximumDistance (G4double d)
G4double GetMaximumDistance () const
G4double GetInteractionDistance () const
Public Member Functions inherited from G4VBiasingInteractionLaw
G4VBiasingInteractionLaw (G4String name)
virtual ~G4VBiasingInteractionLaw ()
const G4String & GetName () const
virtual G4bool IsEffectiveCrossSectionInfinite () const
G4double Sample ()
G4double UpdateForStep (G4double truePathLength)
G4double GetSampledInteractionLength () const
Private Attributes
G4double fMaximumDistance
G4double fCrossSection
G4double fCrossSectionDefined
G4bool fIsSingular
G4double fInteractionDistance
Detailed Description
Definition at line 45 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ILawTruncatedExp.hh
Constructor & Destructor Documentation
G4ILawTruncatedExp::G4ILawTruncatedExp (G4String name = "expForceInteractionLaw")
Definition at line 31 of file G4ILawTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 31 of file G4ILawTruncatedExp.cc
G4ILawTruncatedExp::~G4ILawTruncatedExp () virtual
Definition at line 39 of file G4ILawTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 39 of file G4ILawTruncatedExp.cc
Member Function Documentation
G4double G4ILawTruncatedExp::ComputeEffectiveCrossSectionAt (G4double length) const virtual
Implements G4VBiasingInteractionLaw.
Definition at line 58 of file G4ILawTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 58 of file G4ILawTruncatedExp.cc
References fCrossSection, fCrossSectionDefined, fMaximumDistance, G4Exception(), and JustWarning.
Referenced by G4ILawCommonTruncatedExp::ComputeEffectiveCrossSectionAt().
G4double G4ILawTruncatedExp::ComputeNonInteractionProbabilityAt (G4double length) const virtual
Implements G4VBiasingInteractionLaw.
Definition at line 73 of file G4ILawTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ILawTruncatedExp.cc
References fCrossSection, fCrossSectionDefined, fMaximumDistance, G4Exception(), JustWarning, and num.
Referenced by G4ILawCommonTruncatedExp::ComputeNonInteractionProbabilityAt().
G4double G4ILawTruncatedExp::GetInteractionDistance () const inline
Definition at line 66 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 66 of file G4ILawTruncatedExp.hh
References fInteractionDistance.
Referenced by G4ILawCommonTruncatedExp::GetInteractionDistance().
G4double G4ILawTruncatedExp::GetMaximumDistance () const inline
Definition at line 65 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ILawTruncatedExp.hh
References fMaximumDistance.
Referenced by G4ILawCommonTruncatedExp::GetMaximumDistance().
virtual G4bool G4ILawTruncatedExp::IsSingular () const inline virtual
Reimplemented from G4VBiasingInteractionLaw.
Definition at line 58 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ILawTruncatedExp.hh
References fIsSingular.
Referenced by G4ILawCommonTruncatedExp::IsSingular().
G4double G4ILawTruncatedExp::SampleInteractionLength () virtual
Implements G4VBiasingInteractionLaw.
Definition at line 89 of file G4ILawTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 89 of file G4ILawTruncatedExp.cc
References fCrossSection, fCrossSectionDefined, fInteractionDistance, fMaximumDistance, G4Exception(), G4UniformRand, and JustWarning.
Referenced by G4ILawCommonTruncatedExp::SampleInteractionLength().
void G4ILawTruncatedExp::SetForceCrossSection (G4double xs)
Definition at line 42 of file G4ILawTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ILawTruncatedExp.cc
References fCrossSection, fCrossSectionDefined, fIsSingular, G4Exception(), and JustWarning.
Referenced by G4ILawCommonTruncatedExp::SetForceCrossSection().
void G4ILawTruncatedExp::SetMaximumDistance (G4double d) inline
Definition at line 64 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ILawTruncatedExp.hh
References d, and fMaximumDistance.
Referenced by G4ILawCommonTruncatedExp::SetMaximumDistance().
G4double G4ILawTruncatedExp::UpdateInteractionLengthForStep (G4double truePathLength) virtual
Reimplemented from G4VBiasingInteractionLaw.
Definition at line 105 of file G4ILawTruncatedExp.cc.
View newest version in sPHENIX GitHub at line 105 of file G4ILawTruncatedExp.cc
References fInteractionDistance, fMaximumDistance, G4endl, G4Exception(), G4VBiasingInteractionLaw::GetName(), and JustWarning.
Referenced by G4ILawCommonTruncatedExp::UpdateInteractionLengthForStep().
Member Data Documentation
G4double G4ILawTruncatedExp::fCrossSection private
Definition at line 70 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ILawTruncatedExp.hh
Referenced by ComputeEffectiveCrossSectionAt(), ComputeNonInteractionProbabilityAt(), SampleInteractionLength(), and SetForceCrossSection().
G4double G4ILawTruncatedExp::fCrossSectionDefined private
Definition at line 71 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ILawTruncatedExp.hh
Referenced by ComputeEffectiveCrossSectionAt(), ComputeNonInteractionProbabilityAt(), SampleInteractionLength(), and SetForceCrossSection().
G4double G4ILawTruncatedExp::fInteractionDistance private
Definition at line 73 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ILawTruncatedExp.hh
Referenced by GetInteractionDistance(), SampleInteractionLength(), and UpdateInteractionLengthForStep().
G4bool G4ILawTruncatedExp::fIsSingular private
Definition at line 72 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ILawTruncatedExp.hh
Referenced by IsSingular(), and SetForceCrossSection().
G4double G4ILawTruncatedExp::fMaximumDistance private
Definition at line 69 of file G4ILawTruncatedExp.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ILawTruncatedExp.hh
Referenced by ComputeEffectiveCrossSectionAt(), ComputeNonInteractionProbabilityAt(), GetMaximumDistance(), SampleInteractionLength(), SetMaximumDistance(), and UpdateInteractionLengthForStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4ILawTruncatedExp.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4ILawTruncatedExp.cc