ECCE @ EIC Software: WLSRunAction Class Reference
WLSRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSRunAction.hh>
Public Member Functions
WLSRunAction ()
virtual ~WLSRunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void SetRndmFreq (G4int val)
G4int GetRndmFreq ()
void SetAutoSeed (const G4bool val)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
WLSRunActionMessenger * fRunMessenger
G4int fSaveRndm
G4bool fAutoSeed
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 45 of file WLSRunAction.hh.
View newest version in sPHENIX GitHub at line 45 of file WLSRunAction.hh
Constructor & Destructor Documentation
WLSRunAction::WLSRunAction ()
Definition at line 46 of file WLSRunAction.cc.
View newest version in sPHENIX GitHub at line 46 of file WLSRunAction.cc
References fRunMessenger.
WLSRunAction::~WLSRunAction () virtual
Definition at line 54 of file WLSRunAction.cc.
View newest version in sPHENIX GitHub at line 54 of file WLSRunAction.cc
References fRunMessenger.
Member Function Documentation
void WLSRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented from G4UserRunAction.
Definition at line 61 of file WLSRunAction.cc.
View newest version in sPHENIX GitHub at line 61 of file WLSRunAction.cc
References fAutoSeed, fSaveRndm, G4cout, G4endl, G4UniformRand, G4Run::GetRunID(), G4RunManager::GetRunManager(), G4RunManager::SetRandomNumberStore(), and Acts::VectorHelpers::time().
void WLSRunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 88 of file WLSRunAction.cc.
View newest version in sPHENIX GitHub at line 88 of file WLSRunAction.cc
References fSaveRndm.
G4int WLSRunAction::GetRndmFreq () inline
Definition at line 58 of file WLSRunAction.hh.
View newest version in sPHENIX GitHub at line 58 of file WLSRunAction.hh
References fSaveRndm.
Referenced by WLSEventAction::EndOfEventAction().
void WLSRunAction::SetAutoSeed (const G4bool val) inline
Definition at line 60 of file WLSRunAction.hh.
View newest version in sPHENIX GitHub at line 60 of file WLSRunAction.hh
References fAutoSeed.
Referenced by WLSRunActionMessenger::SetNewValue().
void WLSRunAction::SetRndmFreq (G4int val) inline
Definition at line 57 of file WLSRunAction.hh.
View newest version in sPHENIX GitHub at line 57 of file WLSRunAction.hh
References fSaveRndm.
Referenced by WLSRunActionMessenger::SetNewValue().
Member Data Documentation
G4bool WLSRunAction::fAutoSeed private
Definition at line 67 of file WLSRunAction.hh.
View newest version in sPHENIX GitHub at line 67 of file WLSRunAction.hh
Referenced by BeginOfRunAction(), and SetAutoSeed().
WLSRunActionMessenger* WLSRunAction::fRunMessenger private
Definition at line 64 of file WLSRunAction.hh.
View newest version in sPHENIX GitHub at line 64 of file WLSRunAction.hh
Referenced by WLSRunAction(), and ~WLSRunAction().
G4int WLSRunAction::fSaveRndm private
Definition at line 66 of file WLSRunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file WLSRunAction.hh
Referenced by BeginOfRunAction(), EndOfRunAction(), GetRndmFreq(), and SetRndmFreq().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSRunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSRunAction.cc