ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/G4LENDModel.hh File Reference
G4LENDModel.hh File Reference
#include "G4LENDHeader.hh"
#include "G4LENDManager.hh"
#include "G4LENDUsedTarget.hh"
#include "G4HadronicInteraction.hh"
#include "globals.hh"
Classes
class G4LENDModel
Functions
double MyRNG (void *)
Function Documentation
double MyRNG (void *)
Definition at line 45 of file G4LENDModel.cc.
View newest version in sPHENIX GitHub at line 45 of file G4LENDModel.cc
Referenced by G4LENDCapture::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4LENDFission::ApplyYourself(), and G4LENDInelastic::ApplyYourself().