ECCE @ EIC Software: G4HepRepFileXMLWriter Class Reference
G4HepRepFileXMLWriter Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/G4HepRepFileXMLWriter.hh>
Public Member Functions
G4HepRepFileXMLWriter ()
void addType (const char *name, int newTypeDepth)
void addInstance ()
void addPrimitive ()
void addPoint (double x, double y, double z)
void addAttDef (const char *name, const char *desc, const char *type, const char *extra)
void addAttValue (const char *name, const char *value)
void addAttValue (const char *name, double value)
void addAttValue (const char *name, int value)
void addAttValue (const char *name, bool value)
void addAttValue (const char *name, double value1, double value2, double value3)
void open (const char *filespec)
void close ()
void endTypes ()
Public Attributes
bool isOpen
int typeDepth
bool inType [50]
bool inInstance [50]
char * prevTypeName [50]
Private Member Functions
void init ()
void endType ()
void endInstance ()
void endPrimitive ()
void endPoint ()
void indent ()
Private Attributes
std::ofstream fout
bool inPrimitive
bool inPoint
Detailed Description
Definition at line 50 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 50 of file G4HepRepFileXMLWriter.hh
Constructor & Destructor Documentation
G4HepRepFileXMLWriter::G4HepRepFileXMLWriter ()
Definition at line 47 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 47 of file G4HepRepFileXMLWriter.cc
References init(), and isOpen.
Member Function Documentation
void G4HepRepFileXMLWriter::addAttDef (const char * name, const char * desc, const char * type, const char * extra)
Definition at line 194 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 194 of file G4HepRepFileXMLWriter.cc
References fout, G4cout, G4endl, and indent().
Referenced by G4HepRepFileSceneHandler::AddCompound(), and G4HepRepFileSceneHandler::CheckFileOpen().
void G4HepRepFileXMLWriter::addAttValue (const char * name, const char * value)
Definition at line 213 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 213 of file G4HepRepFileXMLWriter.cc
References fout, G4cout, G4endl, and indent().
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepFileSceneHandler::CheckFileOpen(), G4HepRepFileSceneHandler::InitHit(), and G4HepRepFileSceneHandler::InitTrajectory().
void G4HepRepFileXMLWriter::addAttValue (const char * name, double value)
Definition at line 229 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 229 of file G4HepRepFileXMLWriter.cc
References fout, G4cout, G4endl, and indent().
void G4HepRepFileXMLWriter::addAttValue (const char * name, int value)
Definition at line 245 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 245 of file G4HepRepFileXMLWriter.cc
References fout, G4cout, G4endl, and indent().
void G4HepRepFileXMLWriter::addAttValue (const char * name, bool value)
Definition at line 261 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 261 of file G4HepRepFileXMLWriter.cc
References fout, G4cout, G4endl, and indent().
void G4HepRepFileXMLWriter::addAttValue (const char * name, double value1, double value2, double value3)
Definition at line 280 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 280 of file G4HepRepFileXMLWriter.cc
References fout, G4cout, G4endl, indent(), and int().
void G4HepRepFileXMLWriter::addInstance ()
Definition at line 119 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 119 of file G4HepRepFileXMLWriter.cc
References endInstance(), fout, G4cout, G4endl, indent(), inInstance, inType, and typeDepth.
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4HepRepFileSceneHandler::AddHepRepInstance(), addType(), G4HepRepFileSceneHandler::InitHit(), and G4HepRepFileSceneHandler::InitTrajectory().
void G4HepRepFileXMLWriter::addPoint (double x, double y, double z)
Definition at line 163 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 163 of file G4HepRepFileXMLWriter.cc
References endPoint(), fout, G4cout, G4endl, G4HepRepMessenger::getCenter(), G4HepRepMessenger::GetInstance(), G4HepRepMessenger::getScale(), indent(), inPoint, inPrimitive, scale, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4HepRepFileSceneHandler::AddPrimitive(), and G4HepRepFileSceneHandler::AddSolid().
void G4HepRepFileXMLWriter::addPrimitive ()
Definition at line 141 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 141 of file G4HepRepFileXMLWriter.cc
References endPrimitive(), fout, G4cout, G4endl, indent(), inInstance, inPrimitive, and typeDepth.
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4HepRepFileSceneHandler::AddPrimitive(), and G4HepRepFileSceneHandler::AddSolid().
void G4HepRepFileXMLWriter::addType (const char * name, int newTypeDepth)
Definition at line 70 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 70 of file G4HepRepFileXMLWriter.cc
References addInstance(), endPrimitive(), endType(), fout, G4cout, G4endl, indent(), inType, prevTypeName, and typeDepth.
Referenced by G4HepRepFileSceneHandler::AddCompound(), and G4HepRepFileSceneHandler::AddHepRepInstance().
void G4HepRepFileXMLWriter::close (void)
Definition at line 320 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 320 of file G4HepRepFileXMLWriter.cc
References endTypes(), fout, G4cout, G4endl, and isOpen.
Referenced by open(), and G4HepRepFileViewer::ShowView().
void G4HepRepFileXMLWriter::endInstance () private
Definition at line 353 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 353 of file G4HepRepFileXMLWriter.cc
References endPrimitive(), fout, G4endl, indent(), inInstance, and typeDepth.
Referenced by addInstance(), and endType().
void G4HepRepFileXMLWriter::endPoint () private
Definition at line 375 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 375 of file G4HepRepFileXMLWriter.cc
References fout, G4endl, indent(), and inPoint.
Referenced by addPoint(), and endPrimitive().
void G4HepRepFileXMLWriter::endPrimitive () private
Definition at line 364 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 364 of file G4HepRepFileXMLWriter.cc
References endPoint(), fout, G4endl, indent(), and inPrimitive.
Referenced by addPrimitive(), addType(), and endInstance().
void G4HepRepFileXMLWriter::endType () private
Definition at line 341 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 341 of file G4HepRepFileXMLWriter.cc
References endInstance(), fout, G4endl, indent(), inType, prevTypeName, and typeDepth.
Referenced by addType(), and endTypes().
void G4HepRepFileXMLWriter::endTypes ()
Definition at line 334 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 334 of file G4HepRepFileXMLWriter.cc
References endType(), and typeDepth.
Referenced by close().
void G4HepRepFileXMLWriter::indent () private
Definition at line 385 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 385 of file G4HepRepFileXMLWriter.cc
References fout, inInstance, inPoint, inPrimitive, and inType.
Referenced by addAttDef(), addAttValue(), addInstance(), addPoint(), addPrimitive(), addType(), endInstance(), endPoint(), endPrimitive(), and endType().
void G4HepRepFileXMLWriter::init (void) private
Definition at line 53 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 53 of file G4HepRepFileXMLWriter.cc
References inInstance, inPoint, inPrimitive, inType, prevTypeName, and typeDepth.
Referenced by G4HepRepFileXMLWriter(), and open().
void G4HepRepFileXMLWriter::open (const char * filespec)
Definition at line 301 of file G4HepRepFileXMLWriter.cc.
View newest version in sPHENIX GitHub at line 301 of file G4HepRepFileXMLWriter.cc
References close(), fout, G4cout, G4endl, init(), and isOpen.
Referenced by G4HepRepFileSceneHandler::CheckFileOpen().
Member Data Documentation
std::ofstream G4HepRepFileXMLWriter::fout private
Definition at line 94 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 94 of file G4HepRepFileXMLWriter.hh
Referenced by addAttDef(), addAttValue(), addInstance(), addPoint(), addPrimitive(), addType(), close(), endInstance(), endPoint(), endPrimitive(), endType(), indent(), and open().
bool G4HepRepFileXMLWriter::inInstance[50]
Definition at line 90 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 90 of file G4HepRepFileXMLWriter.hh
Referenced by addInstance(), addPrimitive(), endInstance(), indent(), and init().
bool G4HepRepFileXMLWriter::inPoint private
Definition at line 99 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 99 of file G4HepRepFileXMLWriter.hh
Referenced by addPoint(), endPoint(), indent(), and init().
bool G4HepRepFileXMLWriter::inPrimitive private
Definition at line 98 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 98 of file G4HepRepFileXMLWriter.hh
Referenced by addPoint(), addPrimitive(), endPrimitive(), indent(), and init().
bool G4HepRepFileXMLWriter::inType[50]
Definition at line 89 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 89 of file G4HepRepFileXMLWriter.hh
Referenced by addInstance(), addType(), endType(), indent(), and init().
bool G4HepRepFileXMLWriter::isOpen
Definition at line 87 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 87 of file G4HepRepFileXMLWriter.hh
Referenced by G4HepRepFileSceneHandler::CheckFileOpen(), close(), G4HepRepFileXMLWriter(), open(), and G4HepRepFileViewer::ShowView().
char* G4HepRepFileXMLWriter::prevTypeName[50]
Definition at line 91 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HepRepFileXMLWriter.hh
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4HepRepFileSceneHandler::AddHepRepInstance(), addType(), endType(), and init().
int G4HepRepFileXMLWriter::typeDepth
Definition at line 88 of file G4HepRepFileXMLWriter.hh.
View newest version in sPHENIX GitHub at line 88 of file G4HepRepFileXMLWriter.hh
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), addInstance(), addPrimitive(), addType(), endInstance(), endType(), endTypes(), and init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/G4HepRepFileXMLWriter.hh
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/G4HepRepFileXMLWriter.cc