ECCE @ EIC Software: G4ImportanceConfigurator Class Reference
G4ImportanceConfigurator Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4ImportanceConfigurator.hh>
Public Member Functions
G4ImportanceConfigurator (const G4VPhysicalVolume *worldvolume, const G4String &particlename, G4VIStore &istore, const G4VImportanceAlgorithm *ialg, G4bool paraflag)
G4ImportanceConfigurator (const G4String &worldvolumeName, const G4String &particlename, G4VIStore &istore, const G4VImportanceAlgorithm *ialg, G4bool paraflag)
virtual ~G4ImportanceConfigurator ()
virtual void Configure (G4VSamplerConfigurator *preConf)
virtual const G4VTrackTerminator * GetTrackTerminator () const
void SetWorldName (const G4String &Name)
Public Member Functions inherited from G4VSamplerConfigurator
G4VSamplerConfigurator ()
virtual ~G4VSamplerConfigurator ()
Private Member Functions
G4ImportanceConfigurator (const G4ImportanceConfigurator &)
G4ImportanceConfigurator & operator= (const G4ImportanceConfigurator &)
Private Attributes
const G4VPhysicalVolume * fWorld
G4String fWorldName
G4ProcessPlacer fPlacer
G4VIStore & fIStore
G4bool fDeleteIalg
const G4VImportanceAlgorithm * fIalgorithm
G4ImportanceProcess * fImportanceProcess
G4bool paraflag
Detailed Description
Definition at line 51 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ImportanceConfigurator.hh
Constructor & Destructor Documentation
G4ImportanceConfigurator::G4ImportanceConfigurator (const G4VPhysicalVolume * worldvolume, const G4String & particlename, G4VIStore & istore, const G4VImportanceAlgorithm * ialg, G4bool paraflag)
Definition at line 50 of file G4ImportanceConfigurator.cc.
View newest version in sPHENIX GitHub at line 50 of file G4ImportanceConfigurator.cc
G4ImportanceConfigurator::G4ImportanceConfigurator (const G4String & worldvolumeName, const G4String & particlename, G4VIStore & istore, const G4VImportanceAlgorithm * ialg, G4bool paraflag)
Definition at line 66 of file G4ImportanceConfigurator.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ImportanceConfigurator.cc
References fWorld, fWorldName, G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetParallelWorld(), G4TransportationManager::GetTransportationManager(), G4Navigator::GetWorldVolume(), and paraflag.
G4ImportanceConfigurator::~G4ImportanceConfigurator () virtual
Definition at line 83 of file G4ImportanceConfigurator.cc.
View newest version in sPHENIX GitHub at line 83 of file G4ImportanceConfigurator.cc
References fDeleteIalg, fIalgorithm, fImportanceProcess, fPlacer, and G4ProcessPlacer::RemoveProcess().
G4ImportanceConfigurator::G4ImportanceConfigurator (const G4ImportanceConfigurator &) private
Member Function Documentation
void G4ImportanceConfigurator::Configure (G4VSamplerConfigurator * preConf) virtual
Implements G4VSamplerConfigurator.
Definition at line 97 of file G4ImportanceConfigurator.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ImportanceConfigurator.cc
References G4ProcessPlacer::AddProcessAsSecondDoIt(), FatalException, fIalgorithm, fImportanceProcess, fIStore, fPlacer, fWorld, G4cout, G4endl, G4Exception(), G4VPhysicalVolume::GetName(), G4VSamplerConfigurator::GetTrackTerminator(), paraflag, G4ImportanceProcess::SetParallelWorld(), and G4TemplateAutoLock< _Mutex_t >::unlock().
const G4VTrackTerminator * G4ImportanceConfigurator::GetTrackTerminator () const virtual
Implements G4VSamplerConfigurator.
Definition at line 135 of file G4ImportanceConfigurator.cc.
View newest version in sPHENIX GitHub at line 135 of file G4ImportanceConfigurator.cc
References fImportanceProcess.
G4ImportanceConfigurator& G4ImportanceConfigurator::operator= (const G4ImportanceConfigurator &) private
void G4ImportanceConfigurator::SetWorldName (const G4String & Name)
Definition at line 140 of file G4ImportanceConfigurator.cc.
View newest version in sPHENIX GitHub at line 140 of file G4ImportanceConfigurator.cc
References fWorldName, G4cout, and G4endl.
Referenced by G4GeometrySampler::PrepareImportanceSampling().
Member Data Documentation
G4bool G4ImportanceConfigurator::fDeleteIalg private
Definition at line 84 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 84 of file G4ImportanceConfigurator.hh
Referenced by ~G4ImportanceConfigurator().
const G4VImportanceAlgorithm* G4ImportanceConfigurator::fIalgorithm private
Definition at line 85 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ImportanceConfigurator.hh
Referenced by Configure(), and ~G4ImportanceConfigurator().
G4ImportanceProcess* G4ImportanceConfigurator::fImportanceProcess private
Definition at line 86 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ImportanceConfigurator.hh
Referenced by Configure(), GetTrackTerminator(), and ~G4ImportanceConfigurator().
G4VIStore& G4ImportanceConfigurator::fIStore private
Definition at line 83 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ImportanceConfigurator.hh
Referenced by Configure().
G4ProcessPlacer G4ImportanceConfigurator::fPlacer private
Definition at line 82 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ImportanceConfigurator.hh
Referenced by Configure(), and ~G4ImportanceConfigurator().
const G4VPhysicalVolume* G4ImportanceConfigurator::fWorld private
Definition at line 80 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ImportanceConfigurator.hh
Referenced by Configure(), and G4ImportanceConfigurator().
G4String G4ImportanceConfigurator::fWorldName private
Definition at line 81 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ImportanceConfigurator.hh
Referenced by G4ImportanceConfigurator(), and SetWorldName().
G4bool G4ImportanceConfigurator::paraflag private
Definition at line 89 of file G4ImportanceConfigurator.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ImportanceConfigurator.hh
Referenced by Configure(), and G4ImportanceConfigurator().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/include/G4ImportanceConfigurator.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/importance/src/G4ImportanceConfigurator.cc