ECCE @ EIC Software: G4DNASolvationModelFactory Class Reference
G4DNASolvationModelFactory Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAOneStepThermalizationModel.hh>
Static Public Member Functions
static G4VEmModel * Create (const G4String &penetrationModel)
static G4VEmModel * GetMacroDefinedModel ()
One step thermalization model can be chosen via macro using /process/dna/e-SolvationSubType Ritchie1994.
Detailed Description
Definition at line 192 of file G4DNAOneStepThermalizationModel.hh.
View newest version in sPHENIX GitHub at line 192 of file G4DNAOneStepThermalizationModel.hh
Member Function Documentation
G4VEmModel * G4DNASolvationModelFactory::Create (const G4String & penetrationModel) static
Parameters
penetrationType Available options: Meesungnoen2002, Terrisol1990, Ritchie1994
Definition at line 256 of file G4DNAOneStepThermalizationModel.cc.
View newest version in sPHENIX GitHub at line 256 of file G4DNAOneStepThermalizationModel.cc
References G4Electron::Definition(), FatalErrorInArgument, and G4Exception().
Referenced by GetMacroDefinedModel().
G4VEmModel * G4DNASolvationModelFactory::GetMacroDefinedModel () static
One step thermalization model can be chosen via macro using /process/dna/e-SolvationSubType Ritchie1994.
Returns
Create the model defined via the command macro /process/dna/e-SolvationSubType In case the command is unused, it returns the default model set in G4EmParameters.
Definition at line 294 of file G4DNAOneStepThermalizationModel.cc.
View newest version in sPHENIX GitHub at line 294 of file G4DNAOneStepThermalizationModel.cc
References Create(), G4EmParameters::DNAeSolvationSubType(), FatalErrorInArgument, fDNAUnknownModel, fKreipl2009eSolvation, fMeesungnoen2002eSolvation, fMeesungnoensolid2002eSolvation, fRitchie1994eSolvation, fTerrisol1990eSolvation, G4Exception(), and G4EmParameters::Instance().
Referenced by G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), and G4DNAElectronSolvation::InitialiseProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/include/G4DNAOneStepThermalizationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/models/src/G4DNAOneStepThermalizationModel.cc