ECCE @ EIC Software: G4ScoringManager Class Reference
G4ScoringManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoringManager.hh>
Public Member Functions
~G4ScoringManager ()
void RegisterScoreColorMap (G4VScoreColorMap *colorMap)
void Accumulate (G4VHitsCollection *map)
void Merge (const G4ScoringManager *scMan)
G4VScoringMesh * FindMesh (G4VHitsCollection *map)
G4VScoringMesh * FindMesh (const G4String &)
void List () const
void Dump () const
void DrawMesh (const G4String &meshName, const G4String &psName, const G4String &colorMapName, G4int axflg=111)
void DrawMesh (const G4String &meshName, const G4String &psName, G4int idxPlane, G4int iColumn, const G4String &colorMapName)
void DumpQuantityToFile (const G4String &meshName, const G4String &psName, const G4String &fileName, const G4String &option="")
void DumpAllQuantitiesToFile (const G4String &meshName, const G4String &fileName, const G4String &option="")
G4VScoreColorMap * GetScoreColorMap (const G4String &mapName)
void ListScoreColorMaps ()
void SetCurrentMesh (G4VScoringMesh *scm)
G4VScoringMesh * GetCurrentMesh () const
void CloseCurrentMesh ()
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
size_t GetNumberOfMesh () const
void RegisterScoringMesh (G4VScoringMesh *scm)
G4VScoringMesh * GetMesh (G4int i) const
G4String GetWorldName (G4int i) const
void SetScoreWriter (G4VScoreWriter *sw)
void SetFactor (G4double val=1.0)
G4double GetFactor () const
Static Public Member Functions
static G4ScoringManager * GetScoringManager ()
static G4ScoringManager * GetScoringManagerIfExist ()
static void SetReplicaLevel (G4int)
static G4int GetReplicaLevel ()
Protected Member Functions
G4ScoringManager ()
Private Member Functions
G4ScoringManager (const G4ScoringManager &)
G4ScoringManager & operator= (const G4ScoringManager &)
Private Attributes
G4int verboseLevel
G4ScoringMessenger * fMessenger
G4ScoreQuantityMessenger * fQuantityMessenger
MeshVec fMeshVec
G4VScoringMesh * fCurrentMesh
G4VScoreWriter * writer
G4VScoreColorMap * fDefaultLinearColorMap
ColorMapDict * fColorMapDict
MeshMap fMeshMap
Static Private Attributes
static G4ThreadLocal
G4ScoringManager * fSManager = nullptr
static G4ThreadLocal G4int replicaLevel = 3
Detailed Description
Definition at line 61 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ScoringManager.hh
Constructor & Destructor Documentation
G4ScoringManager::G4ScoringManager () protected
Definition at line 54 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ScoringManager.cc
References fColorMapDict, fDefaultLinearColorMap, fMessenger, fQuantityMessenger, G4VScoreColorMap::GetName(), and writer.
Referenced by GetScoringManager().
G4ScoringManager::~G4ScoringManager ()
Definition at line 67 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ScoringManager.cc
References fColorMapDict, fDefaultLinearColorMap, fMessenger, fQuantityMessenger, fSManager, and writer.
G4ScoringManager::G4ScoringManager (const G4ScoringManager &) private
Member Function Documentation
void G4ScoringManager::Accumulate (G4VHitsCollection * map)
Definition at line 82 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 82 of file G4ScoringManager.cc
References FindMesh(), G4cout, G4endl, G4VHitsCollection::GetName(), G4VHitsCollection::GetSDname(), G4InuclParticleNames::sm, and verboseLevel.
Referenced by G4RunManager::UpdateScoring().
void G4ScoringManager::CloseCurrentMesh () inline
Definition at line 123 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 123 of file G4ScoringManager.hh
References fCurrentMesh.
Referenced by G4ScoringMessenger::SetNewValue().
void G4ScoringManager::DrawMesh (const G4String & meshName, const G4String & psName, const G4String & colorMapName, G4int axflg = 111)
Definition at line 129 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 129 of file G4ScoringManager.cc
References G4VScoringMesh::DrawMesh(), fDefaultLinearColorMap, FindMesh(), G4cerr, G4endl, and GetScoreColorMap().
Referenced by G4ScoringMessenger::SetNewValue().
void G4ScoringManager::DrawMesh (const G4String & meshName, const G4String & psName, G4int idxPlane, G4int iColumn, const G4String & colorMapName)
Definition at line 149 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 149 of file G4ScoringManager.cc
References G4VScoringMesh::DrawMesh(), fDefaultLinearColorMap, FindMesh(), G4cerr, G4endl, and GetScoreColorMap().
void G4ScoringManager::Dump () const
Definition at line 124 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 124 of file G4ScoringManager.cc
References fMeshVec.
Referenced by G4ScoringMessenger::SetNewValue().
void G4ScoringManager::DumpAllQuantitiesToFile (const G4String & meshName, const G4String & fileName, const G4String & option = "")
Definition at line 185 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 185 of file G4ScoringManager.cc
References G4VScoreWriter::DumpAllQuantitiesToFile(), FindMesh(), G4cerr, G4endl, G4VScoreWriter::SetScoringMesh(), and writer.
Referenced by G4ScoringMessenger::SetNewValue().
void G4ScoringManager::DumpQuantityToFile (const G4String & meshName, const G4String & psName, const G4String & fileName, const G4String & option = "")
Definition at line 170 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 170 of file G4ScoringManager.cc
References G4VScoreWriter::DumpQuantityToFile(), FindMesh(), G4cerr, G4endl, G4VScoreWriter::SetScoringMesh(), and writer.
Referenced by G4ScoringMessenger::SetNewValue().
G4VScoringMesh * G4ScoringManager::FindMesh (G4VHitsCollection * map)
Definition at line 92 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ScoringManager.cc
References fMeshMap, G4VHitsCollection::GetColID(), G4VHitsCollection::GetSDname(), and G4InuclParticleNames::sm.
Referenced by Accumulate(), G4GMocrenFileSceneHandler::AddSolid(), DrawMesh(), DumpAllQuantitiesToFile(), DumpQuantityToFile(), and G4ScoringMessenger::SetNewValue().
G4VScoringMesh * G4ScoringManager::FindMesh (const G4String & wName)
Definition at line 108 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 108 of file G4ScoringManager.cc
References fMeshVec, G4cout, G4endl, G4InuclParticleNames::sm, and verboseLevel.
G4VScoringMesh* G4ScoringManager::GetCurrentMesh () const inline
Definition at line 121 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ScoringManager.hh
References fCurrentMesh.
Referenced by G4ScoreQuantityMessenger::SetNewValue(), and G4ScoringMessenger::SetNewValue().
G4double G4ScoringManager::GetFactor () const inline
Definition at line 160 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ScoringManager.hh
References G4VScoreWriter::GetFactor(), and writer.
G4VScoringMesh* G4ScoringManager::GetMesh (G4int i) const inline
Definition at line 143 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 143 of file G4ScoringManager.hh
References fMeshVec.
Referenced by GammaKnifeController::AccumulateAllHits(), G4VSceneHandler::AddCompound(), G4MPIscorerMerger::CalculatePackSize(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), G4PSHitsModel::DescribeYourselfTo(), PHG4ScoringManager::makeScoringHistograms(), Merge(), G4MPIscorerMerger::Pack(), GammaKnifeController::PrepareHitsAccumulation(), GammaKnifeController::RotateBack(), GammaKnifeController::RotateForward(), GammaKnifeController::StoreHits(), and G4MPIscorerMerger::UnPackAndMerge().
size_t G4ScoringManager::GetNumberOfMesh () const inline
Definition at line 135 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ScoringManager.hh
References fMeshVec.
Referenced by GammaKnifeController::AccumulateAllHits(), G4VSceneHandler::AddCompound(), G4MPIscorerMerger::CalculatePackSize(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), G4PSHitsModel::DescribeYourselfTo(), List(), PHG4ScoringManager::makeScoringHistograms(), Merge(), G4MPIscorerMerger::Pack(), GammaKnifeController::PrepareHitsAccumulation(), GammaKnifeController::RotateBack(), GammaKnifeController::RotateForward(), GammaKnifeController::StoreHits(), G4MPIscorerMerger::UnPackAndMerge(), and G4RunManager::UpdateScoring().
G4int G4ScoringManager::GetReplicaLevel () static
Definition at line 79 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ScoringManager.cc
References replicaLevel.
Referenced by G4ScoringCylinder::SetupGeometry(), and G4ScoringBox::SetupGeometry().
G4VScoreColorMap * G4ScoringManager::GetScoreColorMap (const G4String & mapName)
Definition at line 212 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 212 of file G4ScoringManager.cc
References fColorMapDict.
Referenced by DrawMesh(), and G4ScoringMessenger::SetNewValue().
G4ScoringManager * G4ScoringManager::GetScoringManager () static
Definition at line 42 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ScoringManager.cc
References fSManager, and G4ScoringManager().
Referenced by G4GMocrenFileSceneHandler::AddSolid(), RunActionMaster::EndOfRunAction(), G4WorkerRunManager::G4WorkerRunManager(), PHG4ScoringManager::InitRun(), main(), and PHG4ScoringManager::makeScoringHistograms().
G4ScoringManager * G4ScoringManager::GetScoringManagerIfExist () static
Definition at line 51 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ScoringManager.cc
References fSManager.
Referenced by GammaKnifeController::AccumulateAllHits(), G4VSceneHandler::AddCompound(), G4PhysicsListHelper::AddTransportation(), G4MTRunManager::ConstructScoringWorlds(), G4WorkerRunManager::ConstructScoringWorlds(), G4RunManager::ConstructScoringWorlds(), G4PSHitsModel::DescribeYourselfTo(), RunActionMaster::EndOfRunAction(), G4MTRunManager::G4MTRunManager(), G4WorkerRunManager::MergePartialResults(), GammaKnifeController::PrepareHitsAccumulation(), GammaKnifeController::RotateBack(), GammaKnifeController::RotateForward(), GammaKnifeController::StoreHits(), and G4RunManager::UpdateScoring().
G4int G4ScoringManager::GetVerboseLevel () const inline
Definition at line 133 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ScoringManager.hh
References verboseLevel.
Referenced by G4ScoringMessenger::GetCurrentValue().
G4String G4ScoringManager::GetWorldName (G4int i) const inline
Definition at line 145 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ScoringManager.hh
References fMeshVec.
Referenced by G4WorkerRunManager::ConstructScoringWorlds(), and G4RunManager::ConstructScoringWorlds().
void G4ScoringManager::List () const
Definition at line 118 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 118 of file G4ScoringManager.cc
References fMeshVec, G4cout, G4endl, and GetNumberOfMesh().
Referenced by G4ScoringMessenger::SetNewValue().
void G4ScoringManager::ListScoreColorMaps ()
Definition at line 219 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 219 of file G4ScoringManager.cc
References fColorMapDict, G4cout, and G4endl.
Referenced by G4ScoringMessenger::SetNewValue().
void G4ScoringManager::Merge (const G4ScoringManager * scMan)
Definition at line 228 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 228 of file G4ScoringManager.cc
References GetMesh(), GetNumberOfMesh(), and G4VScoringMesh::Merge().
Referenced by G4MTRunManager::MergeScores().
G4ScoringManager& G4ScoringManager::operator= (const G4ScoringManager &) private
void G4ScoringManager::RegisterScoreColorMap (G4VScoreColorMap * colorMap)
Definition at line 199 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 199 of file G4ScoringManager.cc
References fColorMapDict, G4cerr, G4endl, and G4VScoreColorMap::GetName().
void G4ScoringManager::RegisterScoringMesh (G4VScoringMesh * scm) inline
Definition at line 137 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ScoringManager.hh
References fMeshVec, SetCurrentMesh(), G4VScoringMesh::SetVerboseLevel(), and verboseLevel.
Referenced by G4ScoringMessenger::SetNewValue().
void G4ScoringManager::SetCurrentMesh (G4VScoringMesh * scm) inline
Definition at line 119 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ScoringManager.hh
References fCurrentMesh.
Referenced by RegisterScoringMesh(), and G4ScoringMessenger::SetNewValue().
void G4ScoringManager::SetFactor (G4double val = 1.0) inline
Definition at line 158 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ScoringManager.hh
References G4VScoreWriter::SetFactor(), and writer.
Referenced by G4ScoringMessenger::SetNewValue().
void G4ScoringManager::SetReplicaLevel (G4int lvl) static
Definition at line 77 of file G4ScoringManager.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ScoringManager.cc
References replicaLevel.
void G4ScoringManager::SetScoreWriter (G4VScoreWriter * sw) inline
Definition at line 149 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ScoringManager.hh
References G4VScoreWriter::SetVerboseLevel(), sw, verboseLevel, and writer.
Referenced by main().
void G4ScoringManager::SetVerboseLevel (G4int vl) inline
Definition at line 125 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ScoringManager.hh
References fMeshVec, G4VScoreWriter::SetVerboseLevel(), verboseLevel, and writer.
Referenced by main(), and G4ScoringMessenger::SetNewValue().
Member Data Documentation
ColorMapDict* G4ScoringManager::fColorMapDict private
Definition at line 115 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ScoringManager.hh
Referenced by G4ScoringManager(), GetScoreColorMap(), ListScoreColorMaps(), RegisterScoreColorMap(), and ~G4ScoringManager().
G4VScoringMesh* G4ScoringManager::fCurrentMesh private
Definition at line 111 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ScoringManager.hh
Referenced by CloseCurrentMesh(), GetCurrentMesh(), and SetCurrentMesh().
G4VScoreColorMap* G4ScoringManager::fDefaultLinearColorMap private
Definition at line 114 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ScoringManager.hh
Referenced by DrawMesh(), G4ScoringManager(), and ~G4ScoringManager().
MeshMap G4ScoringManager::fMeshMap private
Definition at line 117 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ScoringManager.hh
Referenced by FindMesh().
MeshVec G4ScoringManager::fMeshVec private
Definition at line 110 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ScoringManager.hh
Referenced by Dump(), FindMesh(), GetMesh(), GetNumberOfMesh(), GetWorldName(), List(), RegisterScoringMesh(), and SetVerboseLevel().
G4ScoringMessenger* G4ScoringManager::fMessenger private
Definition at line 107 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ScoringManager.hh
Referenced by G4ScoringManager(), and ~G4ScoringManager().
G4ScoreQuantityMessenger* G4ScoringManager::fQuantityMessenger private
Definition at line 108 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ScoringManager.hh
Referenced by G4ScoringManager(), and ~G4ScoringManager().
G4ThreadLocal G4ScoringManager * G4ScoringManager::fSManager = nullptr static private
Definition at line 104 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ScoringManager.hh
Referenced by GetScoringManager(), GetScoringManagerIfExist(), and ~G4ScoringManager().
G4ThreadLocal G4int G4ScoringManager::replicaLevel = 3 static private
Definition at line 105 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ScoringManager.hh
Referenced by GetReplicaLevel(), and SetReplicaLevel().
G4int G4ScoringManager::verboseLevel private
Definition at line 106 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ScoringManager.hh
Referenced by Accumulate(), FindMesh(), GetVerboseLevel(), RegisterScoringMesh(), SetScoreWriter(), and SetVerboseLevel().
G4VScoreWriter* G4ScoringManager::writer private
Definition at line 113 of file G4ScoringManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ScoringManager.hh
Referenced by DumpAllQuantitiesToFile(), DumpQuantityToFile(), G4ScoringManager(), GetFactor(), SetFactor(), SetScoreWriter(), SetVerboseLevel(), and ~G4ScoringManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4ScoringManager.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4ScoringManager.cc