ECCE @ EIC Software: G4MIRDRibCage Class Reference
G4MIRDRibCage Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4MIRDRibCage.hh>
Public Member Functions
G4MIRDRibCage ()
~G4MIRDRibCage ()
G4VPhysicalVolume * Construct (const G4String &, G4VPhysicalVolume *, const G4String &, G4bool, G4bool)
Public Member Functions inherited from G4VOrgan
G4VOrgan ()
virtual ~G4VOrgan ()
Private Attributes
G4VPhysicalVolume * physRib1
G4VPhysicalVolume * physRib2
G4VPhysicalVolume * physRib3
G4VPhysicalVolume * physRib4
G4VPhysicalVolume * physRib5
G4VPhysicalVolume * physRib6
G4VPhysicalVolume * physRib7
G4VPhysicalVolume * physRib8
G4VPhysicalVolume * physRib9
G4VPhysicalVolume * physRib10
G4VPhysicalVolume * physRib11
G4VPhysicalVolume * physRib12
Detailed Description
Definition at line 40 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 40 of file G4MIRDRibCage.hh
Constructor & Destructor Documentation
G4MIRDRibCage::G4MIRDRibCage ()
Definition at line 45 of file G4MIRDRibCage.cc.
View newest version in sPHENIX GitHub at line 45 of file G4MIRDRibCage.cc
G4MIRDRibCage::~G4MIRDRibCage ()
Definition at line 49 of file G4MIRDRibCage.cc.
View newest version in sPHENIX GitHub at line 49 of file G4MIRDRibCage.cc
Member Function Documentation
G4VPhysicalVolume * G4MIRDRibCage::Construct (const G4String & volumeName, G4VPhysicalVolume * mother, const G4String & colourName, G4bool wireFrame, G4bool) virtual
Implements G4VOrgan.
Definition at line 54 of file G4MIRDRibCage.cc.
View newest version in sPHENIX GitHub at line 54 of file G4MIRDRibCage.cc
References cm, cm3, dx, dy, dz, Acts::UnitConstants::g, G4cout, G4endl, G4VSolid::GetCubicVolume(), G4Material::GetDensity(), G4VisAttributes::GetInvisible(), G4LogicalVolume::GetMaterial(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4LogicalVolume::GetSolid(), gram, material(), physRib1, physRib10, physRib11, physRib12, physRib2, physRib3, physRib4, physRib5, physRib6, physRib7, physRib8, physRib9, G4VisAttributes::SetForceSolid(), G4LogicalVolume::SetVisAttributes(), thickness, xx, and zz.
Member Data Documentation
G4VPhysicalVolume* G4MIRDRibCage::physRib1 private
Definition at line 50 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 50 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib10 private
Definition at line 59 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 59 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib11 private
Definition at line 60 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 60 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib12 private
Definition at line 61 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 61 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib2 private
Definition at line 51 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 51 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib3 private
Definition at line 52 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 52 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib4 private
Definition at line 53 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 53 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib5 private
Definition at line 54 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 54 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib6 private
Definition at line 55 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 55 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib7 private
Definition at line 56 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 56 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib8 private
Definition at line 57 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 57 of file G4MIRDRibCage.hh
Referenced by Construct().
G4VPhysicalVolume* G4MIRDRibCage::physRib9 private
Definition at line 58 of file G4MIRDRibCage.hh.
View newest version in sPHENIX GitHub at line 58 of file G4MIRDRibCage.hh
Referenced by Construct().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4MIRDRibCage.hh
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/src/G4MIRDRibCage.cc