ECCE @ EIC Software: G4DNAPARSER::Command Class Reference
G4DNAPARSER::Command Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/include/CommandLineParser.hh>
Public Types
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
enum Type {
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory, WithOption, WithoutOption,
OptionNotCompulsory, WithOption, WithoutOption, OptionNotCompulsory,
WithOption, WithoutOption, OptionNotCompulsory, WithOption,
WithoutOption, OptionNotCompulsory
}
Public Member Functions
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
virtual const G4String & GetOption ()
Command::Type GetType ()
G4bool IsActive ()
const G4String & GetDescription ()
virtual const G4String & GetOptionName ()
virtual const G4String & GetDefaultOption ()
virtual void SetOption (const G4String &)
virtual void SetOptionName (const G4String &)
virtual void SetDefaultOption (const G4String &)
Protected Member Functions
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Command (Type, const G4String &description="")
virtual ~Command ()
Protected Attributes
Type fType
G4bool fActive
G4String fDescription
Static Protected Attributes
static G4String fNoOption = "NoOption"
Friends
class CommandLineParser
Detailed Description
Definition at line 47 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 47 of file CommandLineParser.hh
Member Enumeration Documentation
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 49 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 49 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
enum G4DNAPARSER::Command::Type
Enumerator:
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
WithOption
WithoutOption
OptionNotCompulsory
Definition at line 50 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 50 of file CommandLineParser.hh
Constructor & Destructor Documentation
Command::Command (Command::Type commandType, const G4String & description = "") protected
Definition at line 104 of file CommandLineParser.cc.
View newest version in sPHENIX GitHub at line 104 of file CommandLineParser.cc
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 76 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 76 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
G4DNAPARSER::Command::Command (Type , const G4String & description = "") protected
virtual G4DNAPARSER::Command::~Command () inline protected virtual
Definition at line 77 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 77 of file CommandLineParser.hh
Member Function Documentation
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
Referenced by main(), and G4DNAPARSER::CommandLineParser::PrintHelp().
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetDefaultOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 62 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 62 of file CommandLineParser.hh
References fNoOption.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fDescription.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
Referenced by G4DNAPARSER::CommandLineParser::PrintHelp().
const G4String& G4DNAPARSER::Command::GetDescription () inline
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fDescription.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 56 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 56 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
Referenced by RunAction::CreateNtuple(), main(), NeuronLoadDataFile::NeuronLoadDataFile(), and SetSeed().
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOption () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 60 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 60 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
virtual const G4String& G4DNAPARSER::Command::GetOptionName () inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 61 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 61 of file CommandLineParser.hh
References fNoOption.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 57 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 57 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
Command::Type G4DNAPARSER::Command::GetType () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fType.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 58 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 58 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
G4bool G4DNAPARSER::Command::IsActive () inline
Definition at line 59 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 59 of file CommandLineParser.hh
References fActive.
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetDefaultOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 66 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 66 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 63 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 63 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
Referenced by G4DNAPARSER::CommandLineParser::Parse().
virtual void G4DNAPARSER::Command::SetOption (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 64 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 64 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
virtual void G4DNAPARSER::Command::SetOptionName (const G4String &) inline virtual
Reimplemented in G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, G4DNAPARSER::CommandWithOption, and G4DNAPARSER::CommandWithOption.
Definition at line 65 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 65 of file CommandLineParser.hh
Friends And Related Function Documentation
CommandLineParser friend
Definition at line 69 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 69 of file CommandLineParser.hh
Member Data Documentation
G4bool G4DNAPARSER::Command::fActive protected
Definition at line 71 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 71 of file CommandLineParser.hh
Referenced by G4DNAPARSER::CommandLineParser::GetCommandIfActive(), IsActive(), and G4DNAPARSER::CommandLineParser::Parse().
G4String G4DNAPARSER::Command::fDescription protected
Definition at line 72 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 72 of file CommandLineParser.hh
Referenced by GetDescription().
G4String Command::fNoOption = "NoOption" static protected
Definition at line 73 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 73 of file CommandLineParser.hh
Referenced by GetDefaultOption(), GetOption(), and GetOptionName().
Type G4DNAPARSER::Command::fType protected
Definition at line 70 of file CommandLineParser.hh.
View newest version in sPHENIX GitHub at line 70 of file CommandLineParser.hh
Referenced by GetType(), and G4DNAPARSER::CommandLineParser::Parse().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/include/CommandLineParser.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem1/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem2/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem4/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem5/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/src/CommandLineParser.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/src/CommandLineParser.cc