ECCE @ EIC Software: CexmcTrackInfo Class Reference
CexmcTrackInfo Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackInfo.hh>
Public Member Functions
CexmcTrackInfo (CexmcTrackType trackType=CexmcInsipidTrack, G4int copyNumber=0)
void Print (void) const
virtual G4int GetTypeInfo (void) const
CexmcTrackType GetTrackType (void) const
void SetTrackType (CexmcTrackType value)
G4int GetCopyNumber (void) const
Public Member Functions inherited from G4VUserTrackInformation
G4VUserTrackInformation ()
G4VUserTrackInformation (const G4String &infoType)
G4VUserTrackInformation (const G4VUserTrackInformation &)
G4VUserTrackInformation & operator= (const G4VUserTrackInformation &)
virtual ~G4VUserTrackInformation ()
const G4String & GetType () const
Private Attributes
CexmcTrackType trackType
G4int copyNumber
Additional Inherited Members
Protected Attributes inherited from G4VUserTrackInformation
G4String * pType
Detailed Description
Definition at line 51 of file CexmcTrackInfo.hh.
View newest version in sPHENIX GitHub at line 51 of file CexmcTrackInfo.hh
Constructor & Destructor Documentation
CexmcTrackInfo::CexmcTrackInfo (CexmcTrackType trackType = CexmcInsipidTrack, G4int copyNumber = 0) explicit
Definition at line 47 of file CexmcTrackInfo.cc.
View newest version in sPHENIX GitHub at line 47 of file CexmcTrackInfo.cc
Member Function Documentation
G4int CexmcTrackInfo::GetCopyNumber (void) const inline
Definition at line 89 of file CexmcTrackInfo.hh.
View newest version in sPHENIX GitHub at line 89 of file CexmcTrackInfo.hh
References copyNumber.
Referenced by CexmcTrackPoints::GetTrackId().
CexmcTrackType CexmcTrackInfo::GetTrackType (void) const inline
Definition at line 77 of file CexmcTrackInfo.hh.
View newest version in sPHENIX GitHub at line 77 of file CexmcTrackInfo.hh
References trackType.
Referenced by CexmcTrackPoints::GetTrackId().
G4int CexmcTrackInfo::GetTypeInfo (void) const virtual
Reimplemented in CexmcIncidentParticleTrackInfo.
Definition at line 59 of file CexmcTrackInfo.cc.
View newest version in sPHENIX GitHub at line 59 of file CexmcTrackInfo.cc
References CexmcBasicTrackType.
Referenced by CexmcHadronicProcess::PostStepDoIt(), and CexmcStudiedProcess::PostStepGetPhysicalInteractionLength().
void CexmcTrackInfo::Print (void) const virtual
Reimplemented from G4VUserTrackInformation.
Definition at line 54 of file CexmcTrackInfo.cc.
View newest version in sPHENIX GitHub at line 54 of file CexmcTrackInfo.cc
void CexmcTrackInfo::SetTrackType (CexmcTrackType value) inline
Definition at line 83 of file CexmcTrackInfo.hh.
View newest version in sPHENIX GitHub at line 83 of file CexmcTrackInfo.hh
References trackType.
Member Data Documentation
G4int CexmcTrackInfo::copyNumber private
Definition at line 73 of file CexmcTrackInfo.hh.
View newest version in sPHENIX GitHub at line 73 of file CexmcTrackInfo.hh
Referenced by GetCopyNumber().
CexmcTrackType CexmcTrackInfo::trackType private
Definition at line 71 of file CexmcTrackInfo.hh.
View newest version in sPHENIX GitHub at line 71 of file CexmcTrackInfo.hh
Referenced by GetTrackType(), and SetTrackType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcTrackInfo.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcTrackInfo.cc