ECCE @ EIC Software: G4VVisCommandGeometrySet Class Reference
G4VVisCommandGeometrySet Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometrySet.hh>
Protected Member Functions
void Set (G4String logVolName, const G4VVisCommandGeometrySetFunction &, G4int requestedDepth)
void SetLVVisAtts (G4LogicalVolume *, const G4VVisCommandGeometrySetFunction &, G4int depth, G4int requestedDepth)
Additional Inherited Members
Public Member Functions inherited from G4VVisCommandGeometry
virtual ~G4VVisCommandGeometry ()
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Types inherited from G4VVisCommandGeometry
typedef std::map
< G4LogicalVolume *, const
G4VisAttributes * >
::const_iterator VisAttsMapIterator
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommandGeometry
static std::map
< G4LogicalVolume *, const
G4VisAttributes * > fVisAttsMap
Detailed Description
Definition at line 170 of file G4VisCommandsGeometrySet.hh.
View newest version in sPHENIX GitHub at line 170 of file G4VisCommandsGeometrySet.hh
Member Function Documentation
void G4VVisCommandGeometrySet::Set (G4String logVolName, const G4VVisCommandGeometrySetFunction & setFunction, G4int requestedDepth) protected
Definition at line 40 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 40 of file G4VisCommandsGeometrySet.cc
References G4UImanager::ApplyCommand(), G4VisManager::errors, G4cerr, G4endl, G4LogicalVolumeStore::GetInstance(), G4LogicalVolume::GetName(), and G4UImanager::GetUIpointer().
void G4VVisCommandGeometrySet::SetLVVisAtts (G4LogicalVolume * pLV, const G4VVisCommandGeometrySetFunction & setFunction, G4int depth, G4int requestedDepth) protected
Definition at line 68 of file G4VisCommandsGeometrySet.cc.
View newest version in sPHENIX GitHub at line 68 of file G4VisCommandsGeometrySet.cc
References G4VisManager::confirmations, G4cout, G4endl, G4LogicalVolume::GetDaughter(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetName(), G4LogicalVolume::GetNoDaughters(), G4LogicalVolume::GetVisAttributes(), and G4LogicalVolume::SetVisAttributes().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsGeometrySet.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsGeometrySet.cc