ECCE @ EIC Software: G4hCoulombScatteringModel Class Reference
G4hCoulombScatteringModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4hCoulombScatteringModel.hh>
Public Member Functions
G4hCoulombScatteringModel (G4bool combined=true)
virtual ~G4hCoulombScatteringModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A, G4double cut, G4double emax) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double) final
void SetLowEnergyThreshold (G4double val)
void SetRecoilThreshold (G4double eth)
void SetFixedCut (G4double)
G4double GetFixedCut () const
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
void DefineMaterial (const G4MaterialCutsCouple *)
void SetupParticle (const G4ParticleDefinition *)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
G4hCoulombScatteringModel & operator= (const G4hCoulombScatteringModel &right)=delete
G4hCoulombScatteringModel (const G4hCoulombScatteringModel &)=delete
Private Attributes
G4IonTable * theIonTable
G4ParticleChangeForGamma * fParticleChange
G4WentzelVIRelXSection * wokvi
G4NistManager * fNistManager
const std::vector< G4double > * pCuts
const G4MaterialCutsCouple * currentCouple
const G4Material * currentMaterial
G4int currentMaterialIndex
G4double cosThetaMin
G4double cosThetaMax
G4double recoilThreshold
G4double elecRatio
G4double mass
G4double fixedCut
const G4ParticleDefinition * particle
const G4ParticleDefinition * theProton
G4bool isCombined
Additional Inherited Members
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 66 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 66 of file G4hCoulombScatteringModel.hh
Constructor & Destructor Documentation
G4hCoulombScatteringModel::G4hCoulombScatteringModel (G4bool combined = true) explicit
Definition at line 66 of file G4hCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4hCoulombScatteringModel.cc
References currentCouple, currentMaterial, currentMaterialIndex, elecRatio, fixedCut, fNistManager, fParticleChange, G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4NistManager::Instance(), mass, particle, pCuts, G4Proton::Proton(), CLHEP::proton_mass_c2, recoilThreshold, theIonTable, theProton, and wokvi.
G4hCoulombScatteringModel::~G4hCoulombScatteringModel () virtual
Definition at line 94 of file G4hCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 94 of file G4hCoulombScatteringModel.cc
References wokvi.
G4hCoulombScatteringModel::G4hCoulombScatteringModel (const G4hCoulombScatteringModel &) private delete
Member Function Documentation
G4double G4hCoulombScatteringModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * p, G4double kinEnergy, G4double Z, G4double A, G4double cut, G4double emax) override virtual
Reimplemented from G4VEmModel.
Definition at line 182 of file G4hCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 182 of file G4hCoulombScatteringModel.cc
References source.hepunit::amu_c2, G4WentzelOKandVIxSection::ComputeElectronCrossSection(), G4WentzelOKandVIxSection::ComputeNuclearCrossSection(), cosThetaMax, Acts::VectorHelpers::cross(), G4VEmModel::CurrentCouple(), currentMaterial, DefineMaterial(), elecRatio, fixedCut, fNistManager, G4lrint(), G4NistManager::GetAtomicMassAmu(), particle, source.hepunit::proton_mass_c2, G4WentzelOKandVIxSection::SetTargetMass(), G4WentzelVIRelXSection::SetupKinematic(), SetupParticle(), G4WentzelOKandVIxSection::SetupTarget(), theProton, and wokvi.
void G4hCoulombScatteringModel::DefineMaterial (const G4MaterialCutsCouple * cup) inline protected
Definition at line 153 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4hCoulombScatteringModel.hh
References currentCouple, currentMaterial, currentMaterialIndex, G4MaterialCutsCouple::GetIndex(), and G4MaterialCutsCouple::GetMaterial().
Referenced by ComputeCrossSectionPerAtom(), and SampleSecondaries().
G4double G4hCoulombScatteringModel::GetFixedCut () const inline
Definition at line 191 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 191 of file G4hCoulombScatteringModel.hh
References fixedCut.
void G4hCoulombScatteringModel::Initialise (const G4ParticleDefinition * part, const G4DataVector & cuts) override virtual
Implements G4VEmModel.
Definition at line 101 of file G4hCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 101 of file G4hCoulombScatteringModel.cc
References cosThetaMin, currentCouple, fParticleChange, G4VEmModel::GetParticleChangeForGamma(), G4WentzelOKandVIxSection::Initialise(), G4VEmModel::InitialiseElementSelectors(), isCombined, G4VEmModel::IsMaster(), pCuts, CLHEP::pi, G4VEmModel::PolarAngleLimit(), SetupParticle(), and wokvi.
void G4hCoulombScatteringModel::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) override virtual
Reimplemented from G4VEmModel.
Definition at line 145 of file G4hCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 145 of file G4hCoulombScatteringModel.cc
References G4VEmModel::GetElementSelectors(), and G4VEmModel::SetElementSelectors().
G4double G4hCoulombScatteringModel::MinPrimaryEnergy (const G4Material * material, const G4ParticleDefinition * part, G4double) final virtual
Reimplemented from G4VEmModel.
Definition at line 154 of file G4hCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 154 of file G4hCoulombScatteringModel.cc
References A(), G4VEmModel::CurrentCouple(), fNistManager, G4lrint(), G4NistManager::GetAtomicMassAmu(), G4Material::GetElementVector(), G4NucleiProperties::GetNuclearMass(), G4Material::GetNumberOfElements(), max, min, pCuts, recoilThreshold, SetupParticle(), t, and Z.
G4hCoulombScatteringModel& G4hCoulombScatteringModel::operator= (const G4hCoulombScatteringModel & right) private delete
void G4hCoulombScatteringModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double tmin, G4double maxEnergy) override virtual
Implements G4VEmModel.
Definition at line 230 of file G4hCoulombScatteringModel.cc.
View newest version in sPHENIX GitHub at line 230 of file G4hCoulombScatteringModel.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4WentzelOKandVIxSection::ComputeElectronCrossSection(), G4WentzelOKandVIxSection::ComputeNuclearCrossSection(), cosThetaMax, Acts::VectorHelpers::cross(), currentMaterial, currentMaterialIndex, DefineMaterial(), dir, CLHEP::HepLorentzVector::e(), e1, edep, fixedCut, fParticleChange, G4DynamicParticle::GetDefinition(), G4IonTable::GetIon(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4NucleiProperties::GetNuclearMass(), G4Element::GetZasInt(), mass, max, particle, pCuts, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4VParticleChange::ProposeNonIonizingEnergyDeposit(), CLHEP::HepLorentzVector::pz(), ratio, recoilThreshold, CLHEP::Hep3Vector::rotateUz(), G4WentzelOKandVIxSection::SampleSingleScattering(), G4VEmModel::SelectIsotopeNumber(), G4VEmModel::SelectRandomAtom(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), G4WentzelOKandVIxSection::SetTargetMass(), G4WentzelVIRelXSection::SetupKinematic(), SetupParticle(), G4WentzelOKandVIxSection::SetupTarget(), CLHEP::HepLorentzVector::setX(), CLHEP::HepLorentzVector::setY(), CLHEP::HepLorentzVector::setZ(), theIonTable, theProton, CLHEP::Hep3Vector::unit(), v1, CLHEP::HepLorentzVector::vect(), wokvi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4hCoulombScatteringModel::SetFixedCut (G4double val) inline
Definition at line 184 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 184 of file G4hCoulombScatteringModel.hh
References fixedCut.
void G4hCoulombScatteringModel::SetLowEnergyThreshold (G4double val) inline
void G4hCoulombScatteringModel::SetRecoilThreshold (G4double eth) inline
Definition at line 177 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4hCoulombScatteringModel.hh
References recoilThreshold.
void G4hCoulombScatteringModel::SetupParticle (const G4ParticleDefinition * p) inline protected
Definition at line 165 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4hCoulombScatteringModel.hh
References G4ParticleDefinition::GetPDGMass(), mass, particle, G4WentzelOKandVIxSection::SetupParticle(), and wokvi.
Referenced by ComputeCrossSectionPerAtom(), Initialise(), MinPrimaryEnergy(), and SampleSecondaries().
Member Data Documentation
G4double G4hCoulombScatteringModel::cosThetaMax private
Definition at line 136 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 136 of file G4hCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), and SampleSecondaries().
G4double G4hCoulombScatteringModel::cosThetaMin private
Definition at line 135 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 135 of file G4hCoulombScatteringModel.hh
Referenced by Initialise().
const G4MaterialCutsCouple* G4hCoulombScatteringModel::currentCouple private
Definition at line 131 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 131 of file G4hCoulombScatteringModel.hh
Referenced by DefineMaterial(), G4hCoulombScatteringModel(), and Initialise().
const G4Material* G4hCoulombScatteringModel::currentMaterial private
Definition at line 132 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 132 of file G4hCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), DefineMaterial(), G4hCoulombScatteringModel(), and SampleSecondaries().
G4int G4hCoulombScatteringModel::currentMaterialIndex private
Definition at line 133 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 133 of file G4hCoulombScatteringModel.hh
Referenced by DefineMaterial(), G4hCoulombScatteringModel(), and SampleSecondaries().
G4double G4hCoulombScatteringModel::elecRatio private
Definition at line 138 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 138 of file G4hCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), and G4hCoulombScatteringModel().
G4double G4hCoulombScatteringModel::fixedCut private
Definition at line 141 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 141 of file G4hCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel(), GetFixedCut(), SampleSecondaries(), and SetFixedCut().
G4NistManager* G4hCoulombScatteringModel::fNistManager private
Definition at line 127 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 127 of file G4hCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel(), and MinPrimaryEnergy().
G4ParticleChangeForGamma* G4hCoulombScatteringModel::fParticleChange private
Definition at line 125 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 125 of file G4hCoulombScatteringModel.hh
Referenced by G4hCoulombScatteringModel(), Initialise(), and SampleSecondaries().
G4bool G4hCoulombScatteringModel::isCombined private
Definition at line 147 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4hCoulombScatteringModel.hh
Referenced by Initialise().
G4double G4hCoulombScatteringModel::mass private
Definition at line 139 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 139 of file G4hCoulombScatteringModel.hh
Referenced by G4hCoulombScatteringModel(), SampleSecondaries(), and SetupParticle().
const G4ParticleDefinition* G4hCoulombScatteringModel::particle private
Definition at line 144 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 144 of file G4hCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel(), SampleSecondaries(), and SetupParticle().
const std::vector<G4double>* G4hCoulombScatteringModel::pCuts private
Definition at line 129 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 129 of file G4hCoulombScatteringModel.hh
Referenced by G4hCoulombScatteringModel(), Initialise(), MinPrimaryEnergy(), and SampleSecondaries().
G4double G4hCoulombScatteringModel::recoilThreshold private
Definition at line 137 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 137 of file G4hCoulombScatteringModel.hh
Referenced by G4hCoulombScatteringModel(), MinPrimaryEnergy(), SampleSecondaries(), and SetRecoilThreshold().
G4IonTable* G4hCoulombScatteringModel::theIonTable private
Definition at line 124 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 124 of file G4hCoulombScatteringModel.hh
Referenced by G4hCoulombScatteringModel(), and SampleSecondaries().
const G4ParticleDefinition* G4hCoulombScatteringModel::theProton private
Definition at line 145 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 145 of file G4hCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel(), and SampleSecondaries().
G4WentzelVIRelXSection* G4hCoulombScatteringModel::wokvi private
Definition at line 126 of file G4hCoulombScatteringModel.hh.
View newest version in sPHENIX GitHub at line 126 of file G4hCoulombScatteringModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel(), Initialise(), SampleSecondaries(), SetupParticle(), and ~G4hCoulombScatteringModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4hCoulombScatteringModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4hCoulombScatteringModel.cc