ECCE @ EIC Software: GB05BOptnSplitAndKillByCrossSection Class Reference
GB05BOptnSplitAndKillByCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/include/GB05BOptnSplitAndKillByCrossSection.hh>
Public Member Functions
GB05BOptnSplitAndKillByCrossSection (G4String name)
virtual ~GB05BOptnSplitAndKillByCrossSection ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &) final
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &) final
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *condition) final
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *) final
void SetInteractionLength (G4double interactionLength)
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4ParticleChange fParticleChange
G4double fInteractionLength
Detailed Description
Definition at line 38 of file GB05BOptnSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 38 of file GB05BOptnSplitAndKillByCrossSection.hh
Constructor & Destructor Documentation
GB05BOptnSplitAndKillByCrossSection::GB05BOptnSplitAndKillByCrossSection (G4String name)
Definition at line 35 of file GB05BOptnSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 35 of file GB05BOptnSplitAndKillByCrossSection.cc
GB05BOptnSplitAndKillByCrossSection::~GB05BOptnSplitAndKillByCrossSection () virtual
Definition at line 43 of file GB05BOptnSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 43 of file GB05BOptnSplitAndKillByCrossSection.cc
Member Function Documentation
virtual G4VParticleChange* GB05BOptnSplitAndKillByCrossSection::ApplyFinalStateBiasing (const G4BiasingProcessInterface * , const G4Track * , const G4Step * , G4bool &) inline final virtual
Implements G4VBiasingOperation.
Definition at line 55 of file GB05BOptnSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 55 of file GB05BOptnSplitAndKillByCrossSection.hh
G4double GB05BOptnSplitAndKillByCrossSection::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition * condition) final virtual
Implements G4VBiasingOperation.
Definition at line 49 of file GB05BOptnSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 49 of file GB05BOptnSplitAndKillByCrossSection.cc
References fInteractionLength, G4UniformRand, and NotForced.
G4VParticleChange * GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState (const G4Track * track, const G4Step *) final virtual
Implements G4VBiasingOperation.
Definition at line 65 of file GB05BOptnSplitAndKillByCrossSection.cc.
View newest version in sPHENIX GitHub at line 65 of file GB05BOptnSplitAndKillByCrossSection.cc
References G4ParticleChange::AddSecondary(), fParticleChange, fStopAndKill, G4UniformRand, G4Track::GetMomentumDirection(), G4Track::GetWeight(), G4ParticleChange::Initialize(), G4VParticleChange::ProposeParentWeight(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::SetSecondaryWeightByProcess(), G4Track::SetWeight(), and CLHEP::Hep3Vector::z().
virtual const G4VBiasingInteractionLaw* GB05BOptnSplitAndKillByCrossSection::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition &) inline final virtual
Implements G4VBiasingOperation.
Definition at line 51 of file GB05BOptnSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 51 of file GB05BOptnSplitAndKillByCrossSection.hh
void GB05BOptnSplitAndKillByCrossSection::SetInteractionLength (G4double interactionLength) inline
Definition at line 80 of file GB05BOptnSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 80 of file GB05BOptnSplitAndKillByCrossSection.hh
References fInteractionLength.
Referenced by GB05BOptrSplitAndKillByCrossSection::ProposeNonPhysicsBiasingOperation().
Member Data Documentation
G4double GB05BOptnSplitAndKillByCrossSection::fInteractionLength private
Definition at line 88 of file GB05BOptnSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 88 of file GB05BOptnSplitAndKillByCrossSection.hh
Referenced by DistanceToApplyOperation(), and SetInteractionLength().
G4ParticleChange GB05BOptnSplitAndKillByCrossSection::fParticleChange private
Definition at line 87 of file GB05BOptnSplitAndKillByCrossSection.hh.
View newest version in sPHENIX GitHub at line 87 of file GB05BOptnSplitAndKillByCrossSection.hh
Referenced by GenerateBiasingFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/include/GB05BOptnSplitAndKillByCrossSection.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/GB05/src/GB05BOptnSplitAndKillByCrossSection.cc