ECCE @ EIC Software: G4ParticleHPFission Class Reference
G4ParticleHPFission Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFission.hh>
Public Member Functions
G4ParticleHPFission ()
~G4ParticleHPFission ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &aTargetNucleus)
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int)
void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void InitialiseModel ()
Private Attributes
std::vector
< G4ParticleHPChannel * > * theFission
G4String dirName
G4int numEle
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 52 of file G4ParticleHPFission.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ParticleHPFission.hh
Constructor & Destructor Documentation
G4ParticleHPFission::G4ParticleHPFission ()
Definition at line 41 of file G4ParticleHPFission.cc.
View newest version in sPHENIX GitHub at line 41 of file G4ParticleHPFission.cc
References MeV, G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
G4ParticleHPFission::~G4ParticleHPFission ()
Definition at line 79 of file G4ParticleHPFission.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPFission.cc
References G4Threading::IsMasterThread(), it, and theFission.
Member Function Documentation
G4HadFinalState * G4ParticleHPFission::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & aTargetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 95 of file G4ParticleHPFission.cc.
View newest version in sPHENIX GitHub at line 95 of file G4ParticleHPFission.cc
References G4ParticleHPManager::CloseReactionWhiteBoard(), G4UniformRand, G4Material::GetElement(), G4Element::GetElementTable(), G4Element::GetIndex(), G4ParticleHPManager::GetInstance(), G4Element::GetIsotope(), G4HadProjectile::GetMaterial(), G4Isotope::GetN(), G4Material::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4ParticleHPManager::GetReactionWhiteBoard(), G4ParticleHPReactionWhiteBoard::GetTargA(), G4Material::GetTemperature(), G4ParticleHPThermalBoost::GetThermalEnergy(), G4Material::GetVecNbOfAtomsPerVolume(), n, G4ParticleHPManager::OpenReactionWhiteBoard(), G4Nucleus::SetIsotope(), G4Nucleus::SetParameters(), and sum.
void G4ParticleHPFission::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4HadronicInteraction.
Definition at line 183 of file G4ParticleHPFission.cc.
View newest version in sPHENIX GitHub at line 183 of file G4ParticleHPFission.cc
References dirName, G4Element::GetElementTable(), G4ParticleHPManager::GetFissionFinalStates(), G4ParticleHPManager::GetInstance(), G4Element::GetNumberOfElements(), lightions::Init(), G4Threading::IsMasterThread(), numEle, G4AutoDelete::Register(), G4ParticleHPManager::RegisterFissionFinalStates(), and theFission.
const std::pair< G4double, G4double > G4ParticleHPFission::GetFatalEnergyCheckLevels () const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 152 of file G4ParticleHPFission.cc.
View newest version in sPHENIX GitHub at line 152 of file G4ParticleHPFission.cc
References DBL_MAX, and perCent.
G4int G4ParticleHPFission::GetVerboseLevel () const
Definition at line 175 of file G4ParticleHPFission.cc.
View newest version in sPHENIX GitHub at line 175 of file G4ParticleHPFission.cc
References G4ParticleHPManager::GetInstance(), and G4ParticleHPManager::GetVerboseLevel().
void G4ParticleHPFission::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 222 of file G4ParticleHPFission.cc.
View newest version in sPHENIX GitHub at line 222 of file G4ParticleHPFission.cc
void G4ParticleHPFission::SetVerboseLevel (G4int newValue)
Definition at line 179 of file G4ParticleHPFission.cc.
View newest version in sPHENIX GitHub at line 179 of file G4ParticleHPFission.cc
References G4ParticleHPManager::GetInstance(), and G4ParticleHPManager::SetVerboseLevel().
Member Data Documentation
G4String G4ParticleHPFission::dirName private
Definition at line 74 of file G4ParticleHPFission.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleHPFission.hh
Referenced by BuildPhysicsTable().
G4int G4ParticleHPFission::numEle private
Definition at line 75 of file G4ParticleHPFission.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ParticleHPFission.hh
Referenced by BuildPhysicsTable().
std::vector<G4ParticleHPChannel*>* G4ParticleHPFission::theFission private
Definition at line 73 of file G4ParticleHPFission.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleHPFission.hh
Referenced by BuildPhysicsTable(), and ~G4ParticleHPFission().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFission.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPFission.cc