ECCE @ EIC Software: CCalEventAction Class Reference
CCalEventAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalEventAction.hh>
Public Member Functions
CCalEventAction (CCalPrimaryGeneratorAction *, CCalSteppingAction *)
~CCalEventAction ()
virtual void BeginOfEventAction (const G4Event *evt)
virtual void EndOfEventAction (const G4Event *evt)
Public Member Functions inherited from G4UserEventAction
G4UserEventAction ()
virtual ~G4UserEventAction ()
virtual void SetEventManager (G4EventManager *value)
Private Member Functions
void initialize ()
Private Attributes
G4bool isInitialized
CCalPrimaryGeneratorAction * fPrimaryGenerator
CCalSteppingAction * fSteppingAction
nameType * SDnames
G4int numberOfSD
CCaloOrganization * theOrg
Additional Inherited Members
Protected Attributes inherited from G4UserEventAction
G4EventManager * fpEventManager
Detailed Description
Definition at line 44 of file CCalEventAction.hh.
View newest version in sPHENIX GitHub at line 44 of file CCalEventAction.hh
Constructor & Destructor Documentation
CCalEventAction::CCalEventAction (CCalPrimaryGeneratorAction * pg, CCalSteppingAction * sa)
Definition at line 60 of file CCalEventAction.cc.
View newest version in sPHENIX GitHub at line 60 of file CCalEventAction.cc
References G4cout, G4endl, and theOrg.
CCalEventAction::~CCalEventAction ()
Definition at line 73 of file CCalEventAction.cc.
View newest version in sPHENIX GitHub at line 73 of file CCalEventAction.cc
References SDnames, and theOrg.
Member Function Documentation
void CCalEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 100 of file CCalEventAction.cc.
View newest version in sPHENIX GitHub at line 100 of file CCalEventAction.cc
References G4cout, G4endl, G4Event::GetEventID(), initialize(), and isInitialized.
void CCalEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from G4UserEventAction.
Definition at line 112 of file CCalEventAction.cc.
View newest version in sPHENIX GitHub at line 112 of file CCalEventAction.cc
References G4VAnalysisManager::AddNtupleRow(), edep, CCalSteppingAction::endOfEvent(), G4THitsCollection< T >::entries(), G4VAnalysisManager::FillH1(), G4VAnalysisManager::FillNtupleFColumn(), fPrimaryGenerator, fSteppingAction, G4cout, G4endl, G4SDManager::GetCollectionID(), CCalHit::getEnergyDeposit(), G4VAnalysisManager::GetH1Id(), G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), CCalPrimaryGeneratorAction::GetParticleEnergy(), CCalPrimaryGeneratorAction::GetParticlePosition(), G4SDManager::GetSDMpointer(), CCalHit::getTimeSlice(), CCalHit::getUnitID(), GeV, G4ToolsAnalysisManager::Instance(), k, MeV, mm, nentries, numberOfSD, pos(), SDnames, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
void CCalEventAction::initialize () private
Definition at line 78 of file CCalEventAction.cc.
View newest version in sPHENIX GitHub at line 78 of file CCalEventAction.cc
References G4cout, G4endl, CCalSDList::getInstance(), CCalSDList::getNumberOfCaloSD(), isInitialized, min, n, numberOfSD, and SDnames.
Referenced by BeginOfEventAction().
Member Data Documentation
CCalPrimaryGeneratorAction* CCalEventAction::fPrimaryGenerator private
Definition at line 58 of file CCalEventAction.hh.
View newest version in sPHENIX GitHub at line 58 of file CCalEventAction.hh
Referenced by EndOfEventAction().
CCalSteppingAction* CCalEventAction::fSteppingAction private
Definition at line 59 of file CCalEventAction.hh.
View newest version in sPHENIX GitHub at line 59 of file CCalEventAction.hh
Referenced by EndOfEventAction().
G4bool CCalEventAction::isInitialized private
Definition at line 56 of file CCalEventAction.hh.
View newest version in sPHENIX GitHub at line 56 of file CCalEventAction.hh
Referenced by BeginOfEventAction(), and initialize().
G4int CCalEventAction::numberOfSD private
Definition at line 61 of file CCalEventAction.hh.
View newest version in sPHENIX GitHub at line 61 of file CCalEventAction.hh
Referenced by EndOfEventAction(), and initialize().
nameType* CCalEventAction::SDnames private
Definition at line 60 of file CCalEventAction.hh.
View newest version in sPHENIX GitHub at line 60 of file CCalEventAction.hh
Referenced by EndOfEventAction(), initialize(), and ~CCalEventAction().
CCaloOrganization* CCalEventAction::theOrg private
Definition at line 62 of file CCalEventAction.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalEventAction.hh
Referenced by CCalEventAction(), and ~CCalEventAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalEventAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalEventAction.cc