ECCE @ EIC Software: CCalDetector Class Reference
CCalDetector Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalDetector.hh>
Public Member Functions
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (G4int i) const
G4int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Protected Member Functions
virtual G4int readFile ()=0
virtual void constructDaughters ()=0
G4int buildFromFile ()
Protected Attributes
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
G4int constructFlag
Friends
std::ostream & operator<< (std::ostream &, const CCalDetector &)
Detailed Description
Definition at line 49 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 49 of file CCalDetector.hh
Constructor & Destructor Documentation
CCalDetector::CCalDetector (const G4String & name)
Definition at line 42 of file CCalDetector.cc.
View newest version in sPHENIX GitHub at line 42 of file CCalDetector.cc
References constructFlag, FatalException, fileName, G4cout, G4endl, G4Exception(), CCalGeometryConfiguration::getConstructFlag(), CCalGeometryConfiguration::getFileName(), CCalGeometryConfiguration::getInstance(), and pathName.
CCalDetector::~CCalDetector () virtual
Definition at line 60 of file CCalDetector.cc.
View newest version in sPHENIX GitHub at line 60 of file CCalDetector.cc
References theDetectorsInside.
Member Function Documentation
void CCalDetector::addDetector (CCalDetector * det)
Definition at line 91 of file CCalDetector.cc.
View newest version in sPHENIX GitHub at line 91 of file CCalDetector.cc
References theDetectorsInside.
Referenced by CCalG4Hall::constructDaughters(), and CCalHall::constructDaughters().
G4String CCalDetector::baseFileName () const inline
Definition at line 78 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 78 of file CCalDetector.hh
References fileName.
G4int CCalDetector::buildFromFile () protected
Definition at line 97 of file CCalDetector.cc.
View newest version in sPHENIX GitHub at line 97 of file CCalDetector.cc
References readFile().
Referenced by construct().
void CCalDetector::construct ()
Definition at line 67 of file CCalDetector.cc.
View newest version in sPHENIX GitHub at line 67 of file CCalDetector.cc
References buildFromFile(), constructDaughters(), constructFlag, G4cout, G4endl, Name(), and theDetectorsInside.
Referenced by constructHierarchy().
virtual void CCalDetector::constructDaughters () protected pure virtual
Implemented in CCalHcal, CCalEcal, CCalG4Hcal, CCalHall, and CCalG4Hall.
Referenced by construct().
void CCalDetector::constructHierarchy () inline
Definition at line 66 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 66 of file CCalDetector.hh
References construct().
Referenced by CCalDetectorConstruction::Construct().
G4String CCalDetector::File () const inline
Definition at line 79 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 79 of file CCalDetector.hh
References fileName.
Referenced by CCalHall::readFile(), CCalEcal::readFile(), and CCalHcal::readFile().
CCalDetector* CCalDetector::getDaughter (G4int i) const inline
Definition at line 80 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 80 of file CCalDetector.hh
References theDetectorsInside.
G4int CCalDetector::getNDaughters () const inline
Definition at line 81 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 81 of file CCalDetector.hh
References theDetectorsInside.
G4String CCalDetector::Name () const inline
Definition at line 77 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 77 of file CCalDetector.hh
References detectorName.
Referenced by construct(), CCalG4Hcal::constructAbsorberLayer(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), CCalG4Hcal::constructScintillatorLayer(), and CCalG4Hcal::constructSensitive().
G4bool CCalDetector::operator!= (const CCalDetector & left) const inline
Definition at line 90 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 90 of file CCalDetector.hh
References detectorName.
G4bool CCalDetector::operator== (const CCalDetector & left) const inline
Definition at line 87 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 87 of file CCalDetector.hh
References detectorName.
virtual G4int CCalDetector::readFile () protected pure virtual
Implemented in CCalHcal, CCalEcal, and CCalHall.
Referenced by buildFromFile().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCalDetector & det) friend
Definition at line 103 of file CCalDetector.cc.
View newest version in sPHENIX GitHub at line 103 of file CCalDetector.cc
Member Data Documentation
G4int CCalDetector::constructFlag protected
Definition at line 122 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 122 of file CCalDetector.hh
Referenced by CCalDetector(), and construct().
G4String CCalDetector::detectorName protected
Definition at line 116 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 116 of file CCalDetector.hh
Referenced by Name(), operator!=(), operator<<(), and operator==().
G4String CCalDetector::fileName protected
Definition at line 117 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 117 of file CCalDetector.hh
Referenced by baseFileName(), CCalDetector(), File(), and operator<<().
G4String CCalDetector::pathName protected
Definition at line 118 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 118 of file CCalDetector.hh
Referenced by CCalDetector(), CCalHall::readFile(), CCalEcal::readFile(), and CCalHcal::readFile().
CCalDetectorTable CCalDetector::theDetectorsInside protected
Definition at line 120 of file CCalDetector.hh.
View newest version in sPHENIX GitHub at line 120 of file CCalDetector.hh
Referenced by addDetector(), construct(), getDaughter(), getNDaughters(), operator<<(), and ~CCalDetector().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalDetector.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalDetector.cc