ECCE @ EIC Software: G4Box Class Reference
G4Box Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Box.hh>
Public Member Functions
G4Box (const G4String &pName, G4double pX, G4double pY, G4double pZ)
virtual ~G4Box ()
void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
G4double GetXHalfLength () const
G4double GetYHalfLength () const
G4double GetZHalfLength () const
void SetXHalfLength (G4double dx)
void SetYHalfLength (G4double dy)
void SetZHalfLength (G4double dz)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4ThreeVector GetPointOnSurface () const
G4VSolid * Clone () const
std::ostream & StreamInfo (std::ostream &os) const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4VisExtent GetExtent () const
G4Polyhedron * CreatePolyhedron () const
G4Box (__void__ &)
G4Box (const G4Box &rhs)
G4Box & operator= (const G4Box &rhs)
Public Member Functions inherited from G4CSGSolid
G4CSGSolid (const G4String &pName)
virtual ~G4CSGSolid ()
virtual G4Polyhedron * GetPolyhedron () const
G4CSGSolid (__void__ &)
G4CSGSolid (const G4CSGSolid &rhs)
G4CSGSolid & operator= (const G4CSGSolid &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Private Member Functions
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double fDx = 0.0
G4double fDy = 0.0
G4double fDz = 0.0
G4double delta
Additional Inherited Members
Protected Member Functions inherited from G4CSGSolid
G4double GetRadiusInRing (G4double rmin, G4double rmax) const
Protected Attributes inherited from G4CSGSolid
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Detailed Description
Definition at line 55 of file G4Box.hh.
View newest version in sPHENIX GitHub at line 55 of file G4Box.hh
Constructor & Destructor Documentation
G4Box::G4Box (const G4String & pName, G4double pX, G4double pY, G4double pZ)
Definition at line 52 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 52 of file G4Box.cc
References delta, FatalException, G4endl, G4Exception(), G4VSolid::GetName(), G4VSolid::kCarTolerance, and message().
Referenced by Clone().
G4Box::~G4Box () virtual
Definition at line 84 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 84 of file G4Box.cc
G4Box::G4Box (__void__ & a)
Definition at line 75 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 75 of file G4Box.cc
G4Box::G4Box (const G4Box & rhs)
Definition at line 92 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 92 of file G4Box.cc
Member Function Documentation
G4ThreeVector G4Box::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 305 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 305 of file G4Box.cc
References kdfinder::abs(), fDx, fDy, fDz, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by SurfaceNormal().
void G4Box::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 207 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 207 of file G4Box.cc
References G4VSolid::DumpInfo(), fDx, fDy, fDz, G4Exception(), G4VSolid::GetName(), JustWarning, message(), pMax, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent().
G4bool G4Box::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 230 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 230 of file G4Box.cc
References BoundingLimits(), and G4BoundingEnvelope::CalculateExtent().
G4VSolid * G4Box::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 525 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 525 of file G4Box.cc
References G4Box().
Referenced by EICG4RPDetector::ConstructMe().
void G4Box::ComputeDimensions (G4VPVParameterisation * p, const G4int n, const G4VPhysicalVolume * pRep) virtual
Reimplemented from G4VSolid.
Definition at line 196 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 196 of file G4Box.cc
References G4VPVParameterisation::ComputeDimensions().
G4Polyhedron * G4Box::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 544 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 544 of file G4Box.cc
References fDx, fDy, and fDz.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and StandaloneVisAction::Draw().
void G4Box::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 534 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 534 of file G4Box.cc
References G4VGraphicsScene::AddSolid().
G4double G4Box::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 325 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 325 of file G4Box.cc
References kdfinder::abs(), DBL_MAX, delta, dx, dy, dz, fDx, fDy, fDz, kInfinity, max, min, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4Voxelizer::DistanceToFirst().
G4double G4Box::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 362 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 362 of file G4Box.cc
References kdfinder::abs(), fDx, fDy, fDz, max, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Box::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 376 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 376 of file G4Box.cc
References kdfinder::abs(), DBL_MAX, delta, fDx, fDy, fDz, min, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Box::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 441 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 441 of file G4Box.cc
References kdfinder::abs(), G4VSolid::DumpInfo(), fDx, fDy, fDz, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), Inside(), JustWarning, kOutside, message(), min, mm, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Box::GetCubicVolume () inline virtual
Reimplemented from G4VSolid.
G4GeometryType G4Box::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 469 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 469 of file G4Box.cc
G4VisExtent G4Box::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 539 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 539 of file G4Box.cc
References fDx, fDy, and fDz.
G4ThreeVector G4Box::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 501 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 501 of file G4Box.cc
References fDx, fDy, fDz, and G4UniformRand.
G4double G4Box::GetSurfaceArea () inline virtual
Reimplemented from G4VSolid.
G4double G4Box::GetXHalfLength () const inline
Referenced by G4XXXFileSceneHandler::AddSolid(), G4XXXStoredSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4XXXSGSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4GDMLWriteParamvol::Box_dimensionsWrite(), PHG4GDMLWriteParamvol::Box_dimensionsWrite(), PHG4GDMLWriteSolids::BoxWrite(), G4GDMLWriteSolids::BoxWrite(), G4tgbVolume::BuildSolidForDivision(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), G4ParameterisationBoxX::ComputeTransformation(), GB06ParallelWorldForSlices::Construct(), DicomRegularDetectorConstruction::ConstructPhantom(), export_G4Box(), G4ParameterisationBoxX::G4ParameterisationBoxX(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationBoxX::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4STRead::Read(), and CexmcSetup::ReadCalorimeterGeometryData().
G4double G4Box::GetYHalfLength () const inline
Referenced by G4XXXFileSceneHandler::AddSolid(), G4XXXStoredSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4XXXSGSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4GDMLWriteParamvol::Box_dimensionsWrite(), PHG4GDMLWriteParamvol::Box_dimensionsWrite(), PHG4GDMLWriteSolids::BoxWrite(), G4GDMLWriteSolids::BoxWrite(), G4ParameterisationBoxX::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), G4ParameterisationBoxY::ComputeTransformation(), GB06ParallelWorldForSlices::Construct(), DicomRegularDetectorConstruction::ConstructPhantom(), export_G4Box(), G4ParameterisationBoxY::G4ParameterisationBoxY(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationBoxY::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4STRead::Read(), and CexmcSetup::ReadCalorimeterGeometryData().
G4double G4Box::GetZHalfLength () const inline
Referenced by G4XXXFileSceneHandler::AddSolid(), G4XXXStoredSceneHandler::AddSolid(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4XXXSGSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4GDMLWriteParamvol::Box_dimensionsWrite(), PHG4GDMLWriteParamvol::Box_dimensionsWrite(), PHG4GDMLWriteSolids::BoxWrite(), G4GDMLWriteSolids::BoxWrite(), G4tgbVolume::BuildSolidForDivision(), G4ParameterisationBoxX::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeTransformation(), GB06ParallelWorldForSlices::Construct(), DicomRegularDetectorConstruction::ConstructPhantom(), DNAParser::CreateCutSolid(), export_G4Box(), G4ParameterisationBoxZ::G4ParameterisationBoxZ(), B4PrimaryGeneratorAction::GeneratePrimaries(), B2PrimaryGeneratorAction::GeneratePrimaries(), B1PrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), G4ParameterisationBoxZ::GetMaxParameter(), G4tgbGeometryDumper::GetSolidParams(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), G4STRead::Read(), CexmcSetup::ReadCalorimeterGeometryData(), and CML2Acc2::target().
EInside G4Box::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 249 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 249 of file G4Box.cc
References kdfinder::abs(), delta, fDx, fDy, fDz, kInside, kOutside, kSurface, max, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by DistanceToOut().
G4Box & G4Box::operator= (const G4Box & rhs)
Definition at line 101 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 101 of file G4Box.cc
References delta, fDx, fDy, fDz, and G4CSGSolid::operator=().
void G4Box::SetXHalfLength (G4double dx)
Definition at line 125 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 125 of file G4Box.cc
References dx, FatalException, G4CSGSolid::fCubicVolume, fDx, G4CSGSolid::fRebuildPolyhedron, G4CSGSolid::fSurfaceArea, G4endl, G4Exception(), G4VSolid::GetName(), G4VSolid::kCarTolerance, and message().
Referenced by G4Voxelizer::BuildBoundingBox(), DetectorConstruction::ChangeGeometry(), VoxelParam::ComputeDimensions(), ExN02ChamberParameterisation::ComputeDimensions(), ExP01ChamberParameterisation::ComputeDimensions(), G4ParameterisationBoxX::ComputeDimensions(), G02ChamberParameterisation::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), DicomNestedPhantomParameterisation::ComputeDimensions(), RE02NestedPhantomParameterisation::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), export_G4Box(), G4STRead::Read(), and HadrontherapyDetectorROGeometry::UpdateROGeometry().
void G4Box::SetYHalfLength (G4double dy)
Definition at line 149 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 149 of file G4Box.cc
References dy, FatalException, G4CSGSolid::fCubicVolume, fDy, G4CSGSolid::fRebuildPolyhedron, G4CSGSolid::fSurfaceArea, G4Exception(), G4VSolid::GetName(), G4VSolid::kCarTolerance, and message().
Referenced by G4Voxelizer::BuildBoundingBox(), DetectorConstruction::ChangeGeometry(), VoxelParam::ComputeDimensions(), ExN02ChamberParameterisation::ComputeDimensions(), ExP01ChamberParameterisation::ComputeDimensions(), G4ParameterisationBoxX::ComputeDimensions(), G02ChamberParameterisation::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), DicomNestedPhantomParameterisation::ComputeDimensions(), RE02NestedPhantomParameterisation::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), export_G4Box(), G4STRead::Read(), and HadrontherapyDetectorROGeometry::UpdateROGeometry().
void G4Box::SetZHalfLength (G4double dz)
Definition at line 172 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 172 of file G4Box.cc
References dz, FatalException, G4CSGSolid::fCubicVolume, fDz, G4CSGSolid::fRebuildPolyhedron, G4CSGSolid::fSurfaceArea, G4Exception(), G4VSolid::GetName(), G4VSolid::kCarTolerance, and message().
Referenced by G4Voxelizer::BuildBoundingBox(), DetectorConstruction::ChangeGeometry(), VoxelParam::ComputeDimensions(), ExN02ChamberParameterisation::ComputeDimensions(), ExP01ChamberParameterisation::ComputeDimensions(), G4ParameterisationBoxX::ComputeDimensions(), G02ChamberParameterisation::ComputeDimensions(), G4GDMLParameterisation::ComputeDimensions(), DicomNestedPhantomParameterisation::ComputeDimensions(), RE02NestedPhantomParameterisation::ComputeDimensions(), G4ParameterisationBoxY::ComputeDimensions(), G4ParameterisationBoxZ::ComputeDimensions(), EICG4RPDetector::ConstructMe(), export_G4Box(), G4STRead::Read(), GB03DetectorConstruction::SetNumberOfLayers(), RE06DetectorConstruction::SetNumberOfLayers(), and HadrontherapyDetectorROGeometry::UpdateROGeometry().
std::ostream & G4Box::StreamInfo (std::ostream & os) const virtual
Reimplemented from G4CSGSolid.
Definition at line 478 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 478 of file G4Box.cc
References fDx, fDy, fDz, G4VSolid::GetName(), and mm.
G4ThreeVector G4Box::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 263 of file G4Box.cc.
View newest version in sPHENIX GitHub at line 263 of file G4Box.cc
References kdfinder::abs(), ApproxSurfaceNormal(), delta, G4VSolid::DumpInfo(), fDx, fDy, fDz, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), JustWarning, CLHEP::Hep3Vector::mag2(), message(), mm, norm, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4double G4Box::delta private
Definition at line 133 of file G4Box.hh.
View newest version in sPHENIX GitHub at line 133 of file G4Box.hh
Referenced by DistanceToIn(), DistanceToOut(), G4Box(), Inside(), operator=(), and SurfaceNormal().
G4double G4Box::fDx = 0.0 private
Definition at line 132 of file G4Box.hh.
View newest version in sPHENIX GitHub at line 132 of file G4Box.hh
Referenced by ApproxSurfaceNormal(), BoundingLimits(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetExtent(), GetPointOnSurface(), Inside(), operator=(), SetXHalfLength(), StreamInfo(), and SurfaceNormal().
G4double G4Box::fDy = 0.0 private
Definition at line 132 of file G4Box.hh.
View newest version in sPHENIX GitHub at line 132 of file G4Box.hh
Referenced by ApproxSurfaceNormal(), BoundingLimits(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetExtent(), GetPointOnSurface(), Inside(), operator=(), SetYHalfLength(), StreamInfo(), and SurfaceNormal().
G4double G4Box::fDz = 0.0 private
Definition at line 132 of file G4Box.hh.
View newest version in sPHENIX GitHub at line 132 of file G4Box.hh
Referenced by ApproxSurfaceNormal(), BoundingLimits(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetExtent(), GetPointOnSurface(), Inside(), operator=(), SetZHalfLength(), StreamInfo(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/include/G4Box.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/CSG/src/G4Box.cc