ECCE @ EIC Software: GFlashSamplingShowerTuning Class Reference
GFlashSamplingShowerTuning Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashSamplingShowerTuning.hh>
Public Member Functions
GFlashSamplingShowerTuning ()
virtual ~GFlashSamplingShowerTuning ()
G4double ParsAveT1 ()
G4double ParsAveT2 ()
G4double ParsAveA1 ()
G4double ParsSigLogT1 ()
G4double ParsSigLogT2 ()
G4double ParsSigLogA1 ()
G4double ParsSigLogA2 ()
G4double ParsRho1 ()
G4double ParsRho2 ()
G4double ParsRC1 ()
G4double ParsRC2 ()
G4double ParsRT1 ()
G4double ParsRT2 ()
G4double ParsWC1 ()
G4double ParsWC2 ()
G4double ParsSpotN1 ()
G4double ParsSpotN2 ()
G4double ParsSpotT1 ()
G4double ParsSpotT2 ()
G4double ParsSpotA1 ()
G4double ParsSpotA2 ()
G4double ConstantResolution ()
G4double NoiseResolution ()
G4double SamplingResolution ()
Public Member Functions inherited from GVFlashHomoShowerTuning
GVFlashHomoShowerTuning ()
virtual ~GVFlashHomoShowerTuning ()
virtual G4double ParAveT1 ()
virtual G4double ParAveA1 ()
virtual G4double ParAveA2 ()
virtual G4double ParAveA3 ()
virtual G4double ParSigLogT1 ()
virtual G4double ParSigLogT2 ()
virtual G4double ParSigLogA1 ()
virtual G4double ParSigLogA2 ()
virtual G4double ParRho1 ()
virtual G4double ParRho2 ()
virtual G4double ParRC1 ()
virtual G4double ParRC2 ()
virtual G4double ParRC3 ()
virtual G4double ParRC4 ()
virtual G4double ParRT1 ()
virtual G4double ParRT2 ()
virtual G4double ParRT3 ()
virtual G4double ParRT4 ()
virtual G4double ParRT5 ()
virtual G4double ParRT6 ()
virtual G4double ParWC1 ()
virtual G4double ParWC2 ()
virtual G4double ParWC3 ()
virtual G4double ParWC4 ()
virtual G4double ParWC5 ()
virtual G4double ParWC6 ()
virtual G4double ParSpotN1 ()
virtual G4double ParSpotN2 ()
virtual G4double ParSpotT1 ()
virtual G4double ParSpotT2 ()
virtual G4double ParSpotA1 ()
virtual G4double ParSpotA2 ()
Detailed Description
Definition at line 53 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 53 of file GFlashSamplingShowerTuning.hh
Constructor & Destructor Documentation
GFlashSamplingShowerTuning::GFlashSamplingShowerTuning () inline
Definition at line 57 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 57 of file GFlashSamplingShowerTuning.hh
virtual GFlashSamplingShowerTuning::~GFlashSamplingShowerTuning () inline virtual
Definition at line 58 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 58 of file GFlashSamplingShowerTuning.hh
Member Function Documentation
G4double GFlashSamplingShowerTuning::ConstantResolution () inline
Definition at line 124 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 124 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::NoiseResolution () inline
Definition at line 125 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 125 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsAveA1 () inline
Definition at line 67 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 67 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsAveT1 () inline
Definition at line 63 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 63 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsAveT2 () inline
Definition at line 64 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 64 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsRC1 () inline
Definition at line 88 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 88 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsRC2 () inline
Definition at line 89 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 89 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsRho1 () inline
Definition at line 78 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 78 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsRho2 () inline
Definition at line 79 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 79 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsRT1 () inline
Definition at line 92 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 92 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsRT2 () inline
Definition at line 93 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 93 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsSigLogA1 () inline
Definition at line 74 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 74 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSigLogA2 () inline
Definition at line 75 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 75 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSigLogT1 () inline
Definition at line 70 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 70 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSigLogT2 () inline
Definition at line 71 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 71 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSpotA1 () inline
Definition at line 119 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 119 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSpotA2 () inline
Definition at line 120 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 120 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSpotN1 () inline
Definition at line 103 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 103 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSpotN2 () inline
Definition at line 104 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 104 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSpotT1 () inline
Definition at line 116 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 116 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsSpotT2 () inline
Definition at line 117 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 117 of file GFlashSamplingShowerTuning.hh
G4double GFlashSamplingShowerTuning::ParsWC1 () inline
Definition at line 96 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 96 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::ParsWC2 () inline
Definition at line 97 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 97 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
G4double GFlashSamplingShowerTuning::SamplingResolution () inline
Definition at line 126 of file GFlashSamplingShowerTuning.hh.
View newest version in sPHENIX GitHub at line 126 of file GFlashSamplingShowerTuning.hh
Referenced by GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GFlashSamplingShowerTuning.hh