ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/analysis/g4tools/include/tools/mpi/dummy_mpi.h File Reference
dummy_mpi.h File Reference
Classes
struct _MPI_Status
Macros
#define MPI_UNSIGNED 0
#define MPI_FLOAT 0
#define MPI_DOUBLE 0
#define MPI_UNSIGNED_CHAR 0
#define MPI_CHAR 0
#define MPI_LONG 0
#define MPI_SHORT 0
#define MPI_INT 0
#define MPI_UNSIGNED_LONG 0
#define MPI_LONG_LONG 0
#define MPI_UNSIGNED_LONG_LONG 0
#define MPI_ANY_SOURCE 0
#define MPI_SUCCESS 1
#define MPI_COMM_WORLD 0
#define MPI_MAX_PROCESSOR_NAME 100
Typedefs
typedef void * MPI_Comm
typedef void * MPI_Datatype
typedef _MPI_Status MPI_Status
Functions
int MPI_Pack (const void *, int, MPI_Datatype, void *, int, int *, MPI_Comm)
int MPI_Unpack (const void *, int, int *, void *, int, MPI_Datatype, MPI_Comm)
int MPI_Probe (int, int, MPI_Comm, MPI_Status *)
int MPI_Get_count (const MPI_Status *, MPI_Datatype, int *)
int MPI_Send (const void *, int, MPI_Datatype, int, int, MPI_Comm)
int MPI_Recv (void *, int, MPI_Datatype, int, int, MPI_Comm, MPI_Status *)
int MPI_Init (int *, char ***)
int MPI_Finalize (void)
int MPI_Comm_size (MPI_Comm, int *)
int MPI_Comm_rank (MPI_Comm, int *)
int MPI_Get_processor_name (char *, int *)
Macro Definition Documentation
#define MPI_ANY_SOURCE 0
Definition at line 28 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 28 of file dummy_mpi.h
#define MPI_CHAR 0
Definition at line 20 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 20 of file dummy_mpi.h
#define MPI_COMM_WORLD 0
to pass examples/cpp/mpi.cpp //////////////////////////////
Definition at line 59 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 59 of file dummy_mpi.h
Referenced by G4MPImanager::Initialize().
#define MPI_DOUBLE 0
Definition at line 18 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 18 of file dummy_mpi.h
#define MPI_FLOAT 0
Definition at line 17 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 17 of file dummy_mpi.h
#define MPI_INT 0
Definition at line 23 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 23 of file dummy_mpi.h
#define MPI_LONG 0
Definition at line 21 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 21 of file dummy_mpi.h
#define MPI_LONG_LONG 0
Definition at line 25 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 25 of file dummy_mpi.h
#define MPI_MAX_PROCESSOR_NAME 100
Definition at line 60 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 60 of file dummy_mpi.h
#define MPI_SHORT 0
Definition at line 22 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 22 of file dummy_mpi.h
#define MPI_SUCCESS 1
Definition at line 30 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 30 of file dummy_mpi.h
#define MPI_UNSIGNED 0
Definition at line 16 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 16 of file dummy_mpi.h
#define MPI_UNSIGNED_CHAR 0
Definition at line 19 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 19 of file dummy_mpi.h
#define MPI_UNSIGNED_LONG 0
Definition at line 24 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 24 of file dummy_mpi.h
#define MPI_UNSIGNED_LONG_LONG 0
Definition at line 26 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 26 of file dummy_mpi.h
Typedef Documentation
typedef void* MPI_Comm
to pass hd2mpi ////////////////////////////////////////////
Definition at line 13 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 13 of file dummy_mpi.h
typedef void* MPI_Datatype
Definition at line 14 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 14 of file dummy_mpi.h
typedef _MPI_Status MPI_Status
Definition at line 48 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 48 of file dummy_mpi.h
Function Documentation
int MPI_Comm_rank (MPI_Comm , int *) inline
Definition at line 65 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 65 of file dummy_mpi.h
int MPI_Comm_size (MPI_Comm , int *) inline
Definition at line 64 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 64 of file dummy_mpi.h
int MPI_Finalize (void) inline
Definition at line 63 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 63 of file dummy_mpi.h
int MPI_Get_count (const MPI_Status * , MPI_Datatype , int *) inline
Definition at line 51 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 51 of file dummy_mpi.h
int MPI_Get_processor_name (char * , int *) inline
Definition at line 66 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 66 of file dummy_mpi.h
int MPI_Init (int * , char ***) inline
Definition at line 62 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 62 of file dummy_mpi.h
int MPI_Pack (const void * , int , MPI_Datatype , void * , int , int * , MPI_Comm) inline
Definition at line 36 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 36 of file dummy_mpi.h
Referenced by G4MPIscorerMerger::Pack(), and G4VUserMPIrunMerger::Send().
int MPI_Probe (int , int , MPI_Comm , MPI_Status *) inline
Definition at line 50 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 50 of file dummy_mpi.h
int MPI_Recv (void * , int , MPI_Datatype , int , int , MPI_Comm , MPI_Status *) inline
Definition at line 53 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 53 of file dummy_mpi.h
int MPI_Send (const void * , int , MPI_Datatype , int , int , MPI_Comm) inline
Definition at line 52 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 52 of file dummy_mpi.h
Referenced by _testMe().
int MPI_Unpack (const void * , int , int * , void * , int , MPI_Datatype , MPI_Comm) inline
Definition at line 37 of file dummy_mpi.h.
View newest version in sPHENIX GitHub at line 37 of file dummy_mpi.h
Referenced by G4VUserMPIrunMerger::Receive(), G4MPIscorerMerger::UnPackAndMerge(), and G4MPIscorerMerger::UnPackHitStatDoubleMap().