ECCE @ EIC Software: G4BlockingList Class Reference
G4BlockingList Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4BlockingList.hh>
Public Member Functions
G4BlockingList (G4int maxDefault=kBlockingListMaxDefault, G4int stride=kBlockingListStride)
~G4BlockingList ()
void Reset ()
void FullyReset ()
void Enlarge (const G4int nv)
size_t Length () const
void BlockVolume (const G4int v)
G4bool IsBlocked (const G4int v) const
Private Attributes
G4int fBlockTagNo = 1
G4int fStride
std::vector< G4int > fBlockingList
Detailed Description
Definition at line 53 of file G4BlockingList.hh.
View newest version in sPHENIX GitHub at line 53 of file G4BlockingList.hh
Constructor & Destructor Documentation
G4BlockingList::G4BlockingList (G4int maxDefault = kBlockingListMaxDefault, G4int stride = kBlockingListStride)
Definition at line 32 of file G4BlockingList.cc.
View newest version in sPHENIX GitHub at line 32 of file G4BlockingList.cc
G4BlockingList::~G4BlockingList ()
Definition at line 39 of file G4BlockingList.cc.
View newest version in sPHENIX GitHub at line 39 of file G4BlockingList.cc
Member Function Documentation
void G4BlockingList::BlockVolume (const G4int v)
Referenced by G4ParameterisedNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), and G4VoxelSafety::SafetyForVoxelNode().
void G4BlockingList::Enlarge (const G4int nv)
Referenced by G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
void G4BlockingList::FullyReset ()
Definition at line 45 of file G4BlockingList.cc.
View newest version in sPHENIX GitHub at line 45 of file G4BlockingList.cc
References fBlockingList, and fBlockTagNo.
G4bool G4BlockingList::IsBlocked (const G4int v) const
Referenced by G4ParameterisedNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), and G4VoxelSafety::SafetyForVoxelNode().
size_t G4BlockingList::Length () const
void G4BlockingList::Reset ()
Referenced by G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeStep(), and G4VoxelNavigation::ComputeStep().
Member Data Documentation
std::vector<G4int> G4BlockingList::fBlockingList private
Definition at line 93 of file G4BlockingList.hh.
View newest version in sPHENIX GitHub at line 93 of file G4BlockingList.hh
Referenced by FullyReset().
G4int G4BlockingList::fBlockTagNo = 1 private
Definition at line 90 of file G4BlockingList.hh.
View newest version in sPHENIX GitHub at line 90 of file G4BlockingList.hh
Referenced by FullyReset().
G4int G4BlockingList::fStride private
Definition at line 90 of file G4BlockingList.hh.
View newest version in sPHENIX GitHub at line 90 of file G4BlockingList.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4BlockingList.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4BlockingList.cc