ECCE @ EIC Software: CCalHcalOrganization Class Reference
CCalHcalOrganization Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalHcalOrganization.hh>
Public Member Functions
CCalHcalOrganization ()
~CCalHcalOrganization ()
virtual unsigned int GetUnitID (const G4Step *aStep) const
Public Member Functions inherited from CCalVOrganization
CCalVOrganization ()
virtual ~CCalVOrganization ()
virtual G4int Levels (const G4Step *) const
virtual void DetectorLevel (const G4Step *, G4int &, G4int *, G4String *) const
Additional Inherited Members
Protected Attributes inherited from CCalVOrganization
CCaloOrganization theOrg
Detailed Description
Definition at line 35 of file CCalHcalOrganization.hh.
View newest version in sPHENIX GitHub at line 35 of file CCalHcalOrganization.hh
Constructor & Destructor Documentation
CCalHcalOrganization::CCalHcalOrganization () inline
Definition at line 39 of file CCalHcalOrganization.hh.
View newest version in sPHENIX GitHub at line 39 of file CCalHcalOrganization.hh
CCalHcalOrganization::~CCalHcalOrganization ()
Definition at line 37 of file CCalHcalOrganization.cc.
View newest version in sPHENIX GitHub at line 37 of file CCalHcalOrganization.cc
Member Function Documentation
unsigned int CCalHcalOrganization::GetUnitID (const G4Step * aStep) const virtual
Implements CCalVOrganization.
Definition at line 40 of file CCalHcalOrganization.cc.
View newest version in sPHENIX GitHub at line 40 of file CCalHcalOrganization.cc
References G4TouchableHistory::GetHistoryDepth(), G4Step::GetPreStepPoint(), G4TouchableHistory::GetReplicaNumber(), and G4StepPoint::GetTouchable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalHcalOrganization.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalHcalOrganization.cc