ECCE @ EIC Software: G4ExtendedMaterial Class Reference
G4ExtendedMaterial Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4ExtendedMaterial.hh>
Public Member Functions
G4ExtendedMaterial (const G4String &name, const G4Material *baseMaterial)
G4ExtendedMaterial (const G4String &name, G4double z, G4double a, G4double density, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4ExtendedMaterial (const G4String &name, G4double density, G4int nComponents, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4ExtendedMaterial (const G4String &name, G4double density, const G4ExtendedMaterial *baseMaterial, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
virtual ~G4ExtendedMaterial ()
void RegisterExtension (std::unique_ptr< G4VMaterialExtension > extension)
G4VMaterialExtension * RetrieveExtension (const G4String &name)
G4int GetNumberOfExtensions () const
G4MaterialExtensionMap::const_iterator begin () const
G4MaterialExtensionMap::const_iterator cbegin () const
G4MaterialExtensionMap::const_iterator end () const
G4MaterialExtensionMap::const_iterator cend () const
virtual G4bool IsExtended () const
void Print (std::ostream &flux) const
Public Member Functions inherited from G4Material
G4Material (const G4String &name, G4double z, G4double a, G4double density, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material (const G4String &name, G4double density, G4int nComponents, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
G4Material (const G4String &name, G4double density, const G4Material *baseMaterial, G4State state=kStateUndefined, G4double temp=NTP_Temperature, G4double pressure=CLHEP::STP_Pressure)
void AddElement (G4Element *element, G4int nAtoms)
void AddElement (G4Element *element, G4double fraction)
void AddMaterial (G4Material *material, G4double fraction)
virtual ~G4Material ()
const G4String & GetName () const
const G4String & GetChemicalFormula () const
G4double GetFreeElectronDensity () const
G4double GetDensity () const
G4State GetState () const
G4double GetTemperature () const
G4double GetPressure () const
size_t GetNumberOfElements () const
const G4ElementVector * GetElementVector () const
const G4double * GetFractionVector () const
const G4int * GetAtomsVector () const
const G4Element * GetElement (G4int iel) const
const G4double * GetVecNbOfAtomsPerVolume () const
G4double GetTotNbOfAtomsPerVolume () const
G4double GetTotNbOfElectPerVolume () const
const G4double * GetAtomicNumDensityVector () const
G4double GetElectronDensity () const
G4double GetRadlen () const
G4double GetNuclearInterLength () const
G4IonisParamMat * GetIonisation () const
G4SandiaTable * GetSandiaTable () const
const G4Material * GetBaseMaterial () const
const std::map< G4Material
*, G4double > & GetMatComponents () const
G4double GetMassOfMolecule () const
void SetChemicalFormula (const G4String &chF)
void SetFreeElectronDensity (G4double)
void ComputeDensityEffectOnFly (G4bool)
G4double GetZ () const
G4double GetA () const
void SetMaterialPropertiesTable (G4MaterialPropertiesTable *anMPT)
G4MaterialPropertiesTable * GetMaterialPropertiesTable () const
size_t GetIndex () const
G4Material (__void__ &)
void SetName (const G4String &name)
Private Attributes
G4MaterialExtensionMap fExtensionMap
Additional Inherited Members
Static Public Member Functions inherited from G4Material
static G4MaterialTable * GetMaterialTable ()
static size_t GetNumberOfMaterials ()
static G4Material * GetMaterial (const G4String &name, G4bool warning=true)
static G4Material * GetMaterial (G4double z, G4double a, G4double dens)
static G4Material * GetMaterial (size_t nComp, G4double dens)
Detailed Description
Definition at line 62 of file G4ExtendedMaterial.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ExtendedMaterial.hh
Constructor & Destructor Documentation
G4ExtendedMaterial::G4ExtendedMaterial (const G4String & name, const G4Material * baseMaterial)
Definition at line 44 of file G4ExtendedMaterial.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ExtendedMaterial.cc
G4ExtendedMaterial::G4ExtendedMaterial (const G4String & name, G4double z, G4double a, G4double density, G4State state = kStateUndefined, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 53 of file G4ExtendedMaterial.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ExtendedMaterial.cc
G4ExtendedMaterial::G4ExtendedMaterial (const G4String & name, G4double density, G4int nComponents, G4State state = kStateUndefined, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 64 of file G4ExtendedMaterial.cc.
View newest version in sPHENIX GitHub at line 64 of file G4ExtendedMaterial.cc
G4ExtendedMaterial::G4ExtendedMaterial (const G4String & name, G4double density, const G4ExtendedMaterial * baseMaterial, G4State state = kStateUndefined, G4double temp = NTP_Temperature, G4double pressure = CLHEP::STP_Pressure)
Definition at line 74 of file G4ExtendedMaterial.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ExtendedMaterial.cc
virtual G4ExtendedMaterial::~G4ExtendedMaterial () inline virtual
Definition at line 104 of file G4ExtendedMaterial.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ExtendedMaterial.hh
Member Function Documentation
G4MaterialExtensionMap::const_iterator G4ExtendedMaterial::begin () const inline
Definition at line 125 of file G4ExtendedMaterial.hh.
View newest version in sPHENIX GitHub at line 125 of file G4ExtendedMaterial.hh
References fExtensionMap.
G4MaterialExtensionMap::const_iterator G4ExtendedMaterial::cbegin () const inline
Definition at line 126 of file G4ExtendedMaterial.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ExtendedMaterial.hh
References fExtensionMap.
G4MaterialExtensionMap::const_iterator G4ExtendedMaterial::cend () const inline
Definition at line 128 of file G4ExtendedMaterial.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ExtendedMaterial.hh
References fExtensionMap.
G4MaterialExtensionMap::const_iterator G4ExtendedMaterial::end () const inline
Definition at line 127 of file G4ExtendedMaterial.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ExtendedMaterial.hh
References fExtensionMap.
G4int G4ExtendedMaterial::GetNumberOfExtensions () const inline
Definition at line 120 of file G4ExtendedMaterial.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ExtendedMaterial.hh
References fExtensionMap.
G4bool G4ExtendedMaterial::IsExtended () const virtual
Reimplemented from G4Material.
Definition at line 120 of file G4ExtendedMaterial.cc.
View newest version in sPHENIX GitHub at line 120 of file G4ExtendedMaterial.cc
void G4ExtendedMaterial::Print (std::ostream & flux) const
Definition at line 125 of file G4ExtendedMaterial.cc.
View newest version in sPHENIX GitHub at line 125 of file G4ExtendedMaterial.cc
References fExtensionMap.
void G4ExtendedMaterial::RegisterExtension (std::unique_ptr< G4VMaterialExtension > extension)
Definition at line 85 of file G4ExtendedMaterial.cc.
View newest version in sPHENIX GitHub at line 85 of file G4ExtendedMaterial.cc
References fExtensionMap, G4Exception(), G4VMaterialExtension::GetName(), G4Material::GetName(), and JustWarning.
G4VMaterialExtension * G4ExtendedMaterial::RetrieveExtension (const G4String & name)
Definition at line 103 of file G4ExtendedMaterial.cc.
View newest version in sPHENIX GitHub at line 103 of file G4ExtendedMaterial.cc
References fExtensionMap, G4Exception(), G4Material::GetName(), and JustWarning.
Referenced by G4Channeling::GetMatData().
Member Data Documentation
G4MaterialExtensionMap G4ExtendedMaterial::fExtensionMap private
Definition at line 104 of file G4ExtendedMaterial.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ExtendedMaterial.hh
Referenced by begin(), cbegin(), cend(), end(), GetNumberOfExtensions(), Print(), RegisterExtension(), and RetrieveExtension().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4ExtendedMaterial.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4ExtendedMaterial.cc