ECCE @ EIC Software: G4GDMLReadMaterials Class Reference
G4GDMLReadMaterials Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadMaterials.hh>
Public Member Functions
G4Element * GetElement (const G4String &, G4bool verbose=true) const
G4Isotope * GetIsotope (const G4String &, G4bool verbose=true) const
G4Material * GetMaterial (const G4String &, G4bool verbose=true) const
virtual void MaterialsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadDefine
G4bool IsValidID (const G4String &) const
G4double GetConstant (const G4String &)
G4double GetVariable (const G4String &)
G4double GetQuantity (const G4String &)
G4ThreeVector GetPosition (const G4String &)
G4ThreeVector GetRotation (const G4String &)
G4ThreeVector GetScale (const G4String &)
G4GDMLMatrix GetMatrix (const G4String &)
virtual void DefineRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLRead
virtual void SetupRead (const xercesc::DOMElement *const)=0
virtual void SolidsRead (const xercesc::DOMElement *const)=0
virtual void Paramvol_contentRead (const xercesc::DOMElement *const)=0
virtual void Volume_contentRead (const xercesc::DOMElement *const)=0
virtual void StructureRead (const xercesc::DOMElement *const)=0
virtual void ExtensionRead (const xercesc::DOMElement *const)
virtual void UserinfoRead (const xercesc::DOMElement *const)
virtual G4LogicalVolume * GetVolume (const G4String &) const =0
virtual G4String GetSetup (const G4String &)=0
void Read (const G4String &, G4bool validation, G4bool isModule, G4bool strip=true)
void StripNames () const
void StripName (G4String &) const
void OverlapCheck (G4bool)
const G4GDMLAuxListType * GetAuxList () const
Protected Member Functions
G4GDMLReadMaterials ()
virtual ~G4GDMLReadMaterials ()
G4double AtomRead (const xercesc::DOMElement *const)
G4int CompositeRead (const xercesc::DOMElement *const, G4String &)
G4double DRead (const xercesc::DOMElement *const)
G4double PRead (const xercesc::DOMElement *const)
G4double TRead (const xercesc::DOMElement *const)
G4double MEERead (const xercesc::DOMElement *const)
void ElementRead (const xercesc::DOMElement *const)
G4double FractionRead (const xercesc::DOMElement *const, G4String &)
void IsotopeRead (const xercesc::DOMElement *const)
void MaterialRead (const xercesc::DOMElement *const)
void MixtureRead (const xercesc::DOMElement *const, G4Element *)
void MixtureRead (const xercesc::DOMElement *const, G4Material *)
void PropertyRead (const xercesc::DOMElement *const, G4Material *)
Protected Member Functions inherited from G4GDMLReadDefine
G4GDMLReadDefine ()
virtual ~G4GDMLReadDefine ()
G4RotationMatrix GetRotationMatrix (const G4ThreeVector &)
void VectorRead (const xercesc::DOMElement *const, G4ThreeVector &)
G4String RefRead (const xercesc::DOMElement *const)
void ConstantRead (const xercesc::DOMElement *const)
void MatrixRead (const xercesc::DOMElement *const)
void PositionRead (const xercesc::DOMElement *const)
void RotationRead (const xercesc::DOMElement *const)
void ScaleRead (const xercesc::DOMElement *const)
void VariableRead (const xercesc::DOMElement *const)
void QuantityRead (const xercesc::DOMElement *const)
void ExpressionRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLRead
G4GDMLRead ()
virtual ~G4GDMLRead ()
G4String Transcode (const XMLCh *const)
G4String GenerateName (const G4String &name, G4bool strip=false)
G4String Strip (const G4String &) const
void GeneratePhysvolName (const G4String &, G4VPhysicalVolume *)
void LoopRead (const xercesc::DOMElement *const, void(G4GDMLRead::*)(const xercesc::DOMElement *const))
G4GDMLAuxStructType AuxiliaryRead (const xercesc::DOMElement *const auxElem)
Additional Inherited Members
Protected Attributes inherited from G4GDMLReadDefine
std::map< G4String, G4double > quantityMap
std::map< G4String, G4ThreeVector > positionMap
std::map< G4String, G4ThreeVector > rotationMap
std::map< G4String, G4ThreeVector > scaleMap
std::map< G4String, G4GDMLMatrix > matrixMap
Detailed Description
Definition at line 50 of file G4GDMLReadMaterials.hh.
View newest version in sPHENIX GitHub at line 50 of file G4GDMLReadMaterials.hh
Constructor & Destructor Documentation
G4GDMLReadMaterials::G4GDMLReadMaterials () protected
Definition at line 45 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 45 of file G4GDMLReadMaterials.cc
G4GDMLReadMaterials::~G4GDMLReadMaterials () protected virtual
Definition at line 49 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 49 of file G4GDMLReadMaterials.cc
Member Function Documentation
G4double G4GDMLReadMaterials::AtomRead (const xercesc::DOMElement * const atomElement) protected
Definition at line 54 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 54 of file G4GDMLReadMaterials.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, Acts::UnitConstants::g, G4Exception(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), mole, and G4GDMLRead::Transcode().
Referenced by ElementRead(), IsotopeRead(), and MaterialRead().
G4int G4GDMLReadMaterials::CompositeRead (const xercesc::DOMElement * const compositeElement, G4String & ref) protected
Definition at line 94 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 94 of file G4GDMLReadMaterials.cc
References G4GDMLRead::eval, G4GDMLEvaluator::EvaluateInteger(), FatalException, G4Exception(), n, and G4GDMLRead::Transcode().
Referenced by MixtureRead().
G4double G4GDMLReadMaterials::DRead (const xercesc::DOMElement * const DElement) protected
Definition at line 128 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 128 of file G4GDMLReadMaterials.cc
References cm3, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, Acts::UnitConstants::g, G4Exception(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by MaterialRead().
void G4GDMLReadMaterials::ElementRead (const xercesc::DOMElement * const elementElement) protected
Definition at line 283 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 283 of file G4GDMLReadMaterials.cc
References a, AtomRead(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), MixtureRead(), G4GDMLRead::Strip(), G4GDMLRead::Transcode(), and Z.
Referenced by MaterialsRead().
G4double G4GDMLReadMaterials::FractionRead (const xercesc::DOMElement * const fractionElement, G4String & ref) protected
Definition at line 351 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 351 of file G4GDMLReadMaterials.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), n, and G4GDMLRead::Transcode().
Referenced by MixtureRead().
G4Element * G4GDMLReadMaterials::GetElement (const G4String & ref, G4bool verbose = true) const
Definition at line 731 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 731 of file G4GDMLReadMaterials.cc
References FatalException, G4NistManager::FindOrBuildElement(), G4Exception(), G4Element::GetElement(), and G4NistManager::Instance().
Referenced by MixtureRead().
G4Isotope * G4GDMLReadMaterials::GetIsotope (const G4String & ref, G4bool verbose = true) const
Definition at line 750 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 750 of file G4GDMLReadMaterials.cc
References FatalException, G4Exception(), and G4Isotope::GetIsotope().
Referenced by MixtureRead().
G4Material * G4GDMLReadMaterials::GetMaterial (const G4String & ref, G4bool verbose = true) const
Definition at line 765 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 765 of file G4GDMLReadMaterials.cc
References FatalException, G4NistManager::FindOrBuildMaterial(), G4Exception(), G4Material::GetMaterial(), and G4NistManager::Instance().
Referenced by MixtureRead(), G03ColorReader::VolumeRead(), and G4GDMLReadStructure::VolumeRead().
void G4GDMLReadMaterials::IsotopeRead (const xercesc::DOMElement * const isotopeElement) protected
Definition at line 386 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 386 of file G4GDMLReadMaterials.cc
References a, AtomRead(), G4GDMLRead::eval, G4GDMLEvaluator::EvaluateInteger(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), N, G4GDMLRead::Strip(), G4GDMLRead::Transcode(), and Z.
Referenced by MaterialsRead().
void G4GDMLReadMaterials::MaterialRead (const xercesc::DOMElement * const materialElement) protected
Definition at line 443 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 443 of file G4GDMLReadMaterials.cc
References a, AtomRead(), D(), DRead(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4Material::GetIonisation(), G4GDMLReadDefine::GetQuantity(), kStateGas, kStateLiquid, kStateSolid, kStateUndefined, material(), MEERead(), MixtureRead(), P, PRead(), PropertyRead(), G4GDMLReadDefine::RefRead(), G4IonisParamMat::SetMeanExcitationEnergy(), source.hepunit::STP_Pressure, source.hepunit::STP_Temperature, G4GDMLRead::Strip(), T, G4GDMLRead::Transcode(), TRead(), and Z.
Referenced by MaterialsRead().
void G4GDMLReadMaterials::MaterialsRead (const xercesc::DOMElement * const materialsElement) virtual
Implements G4GDMLRead.
Definition at line 697 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 697 of file G4GDMLReadMaterials.cc
References G4GDMLReadDefine::DefineRead(), ElementRead(), FatalException, G4cout, G4endl, G4Exception(), IsotopeRead(), MaterialRead(), and G4GDMLRead::Transcode().
G4double G4GDMLReadMaterials::MEERead (const xercesc::DOMElement * const PElement) protected
Definition at line 244 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 244 of file G4GDMLReadMaterials.cc
References eV, G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), and G4GDMLRead::Transcode().
Referenced by MaterialRead().
void G4GDMLReadMaterials::MixtureRead (const xercesc::DOMElement * const mixtureElement, G4Element * element) protected
Definition at line 552 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 552 of file G4GDMLReadMaterials.cc
References G4Element::AddIsotope(), FatalException, FractionRead(), G4Exception(), G4GDMLRead::GenerateName(), GetIsotope(), n, and G4GDMLRead::Transcode().
Referenced by ElementRead(), and MaterialRead().
void G4GDMLReadMaterials::MixtureRead (const xercesc::DOMElement * const mixtureElement, G4Material * material) protected
Definition at line 579 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 579 of file G4GDMLReadMaterials.cc
References G4Material::AddElement(), G4Material::AddMaterial(), CompositeRead(), FatalException, FractionRead(), G4Exception(), G4GDMLRead::GenerateName(), GetElement(), GetMaterial(), n, and G4GDMLRead::Transcode().
G4double G4GDMLReadMaterials::PRead (const xercesc::DOMElement * const PElement) protected
Definition at line 168 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 168 of file G4GDMLReadMaterials.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), hep_pascal, source.hepunit::STP_Pressure, and G4GDMLRead::Transcode().
Referenced by MaterialRead().
void G4GDMLReadMaterials::PropertyRead (const xercesc::DOMElement * const propertyElement, G4Material * material) protected
Definition at line 628 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 628 of file G4GDMLReadMaterials.cc
References G4MaterialPropertiesTable::AddConstProperty(), G4MaterialPropertiesTable::AddProperty(), FatalException, G4Exception(), G4GDMLRead::GenerateName(), G4GDMLMatrix::Get(), G4GDMLMatrix::GetCols(), G4Material::GetMaterialPropertiesTable(), G4GDMLReadDefine::GetMatrix(), G4GDMLMatrix::GetRows(), G4PhysicsOrderedFreeVector::InsertValues(), G4Material::SetMaterialPropertiesTable(), G4GDMLRead::Strip(), and G4GDMLRead::Transcode().
Referenced by MaterialRead().
G4double G4GDMLReadMaterials::TRead (const xercesc::DOMElement * const TElement) protected
Definition at line 206 of file G4GDMLReadMaterials.cc.
View newest version in sPHENIX GitHub at line 206 of file G4GDMLReadMaterials.cc
References G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), FatalException, G4Exception(), G4UnitDefinition::GetCategory(), G4UnitDefinition::GetValueOf(), kelvin, source.hepunit::STP_Temperature, and G4GDMLRead::Transcode().
Referenced by MaterialRead().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/gdml/include/G4GDMLReadMaterials.hh
geant4/tree/geant4-10.6-release/source/persistency/gdml/src/G4GDMLReadMaterials.cc