ECCE @ EIC Software: G4VPhysicsConstructor Class Reference
G4VPhysicsConstructor Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VPhysicsConstructor.hh>
Inherited by AntiBaryonPhysics, BiasedRDPhysics, CexmcStudiedPhysics< Process >, CexmcStudiedPhysics< CexmcHadronicProcess >, Decay, ElectromagneticPhysics, ElectromagneticPhysics, ElectromagneticPhysics, ElectromagneticPhysics, ExN04EMPhysics, ExUCNExtraPhysics, G4ChannelingPhysics, G4ChargeExchangePhysics, G4DecayPhysics, G4EmDNAChemistry, G4EmDNAChemistry_option1, G4EmDNAChemistry_option2, G4EmDNAPhysics, G4EmDNAPhysics_option1, G4EmDNAPhysics_option2, G4EmDNAPhysics_option3, G4EmDNAPhysics_option4, G4EmDNAPhysics_option5, G4EmDNAPhysics_option6, G4EmDNAPhysics_option7, G4EmDNAPhysics_option8, G4EmDNAPhysics_stationary, G4EmDNAPhysics_stationary_option2, G4EmDNAPhysics_stationary_option4, G4EmDNAPhysics_stationary_option6, G4EmDNAPhysicsActivator, G4EmExtraPhysics, G4EmLEPTSPhysics, G4EmLivermorePhysics, G4EmLivermorePolarizedPhysics, G4EmLowEPPhysics, G4EmPenelopePhysics, G4EmStandardPhysics, G4EmStandardPhysics_option1, G4EmStandardPhysics_option2, G4EmStandardPhysics_option3, G4EmStandardPhysics_option4, G4EmStandardPhysics_option4_channeling, G4EmStandardPhysicsGS, G4EmStandardPhysicsSS, G4EmStandardPhysicsWVI, G4FastSimulationPhysics, G4GenericBiasingPhysics, G4HadronDElasticPhysics, G4HadronElasticPhysics, G4HadronHElasticPhysics, G4HadronPhysicsFTF_BIC, G4HadronPhysicsFTFP_BERT, G4HadronPhysicsFTFQGSP_BERT, G4HadronPhysicsINCLXX, G4HadronPhysicsQGS_BIC, G4HadronPhysicsQGSP_BERT, G4HadronPhysicsQGSP_BIC, G4HadronPhysicsQGSP_BIC_AllHP, G4HadronPhysicsQGSP_BIC_HP, G4HadronPhysicsShielding, G4HadronPhysicsShieldingLEND, G4ImportanceBiasing, G4IonElasticPhysics, G4IonINCLXXPhysics, G4IonPhysics, G4IonPhysicsPHP, G4IonQMDPhysics, G4MonopolePhysics, G4MuonicAtomDecayPhysics, G4NeutronCrossSectionXS, G4NeutronTrackingCut, G4OpticalPhysics, G4ParallelWorldPhysics, G4RadioactiveDecayPhysics, G4SpinDecayPhysics, G4StepLimiterPhysics, G4StoppingPhysics, G4StoppingPhysicsFritiofWithBinaryCascade, G4UnknownDecayPhysics, G4VHadronPhysics, G4WeightWindowBiasing, GammaKnifeParticles, GammaLeptoNuclearPhysics, GammaNuclearPhysics, GammaNuclearPhysics, GammaNuclearPhysics, GammaNuclearPhysics, GammaNuclearPhysics, GammaRayTelEMlowePhysics, GammaRayTelEMstdPhysics, GammaRayTelGeneralPhysics, GammaRayTelHadronPhysics, GammaRayTelIonPhysics, GammaRayTelMuonPhysics, GammaRayTelParticles, HadronPhysicsCRMC_FTFP_BERT, HadronPhysicsHIJING, HadronPhysicsUrQMD, HadrontherapyParticles, HyperonPhysics, IonCRMCPhysics, IonPhysics, KaonPhysics, MuNuclearBuilder, NeutronHPphysics, NeutronPhysics, P6DExtDecayerPhysics, P6DExtDecayerPhysics, Particles, PhysicsListEMstd, PhysListEm19DStandard, PhysListEm5DStandard, PhysListEm5DStandard, PhysListEm5DStandard, PhysListEmLivermore, PhysListEmLivermore, PhysListEmLivermore, PhysListEmPenelope, PhysListEmPenelope, PhysListEmPenelope, PhysListEmPolarized, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard_GS, PhysListEmStandard_GS, PhysListEmStandard_option0, PhysListEmStandard_option0, PhysListEmStandard_option3, PhysListEmStandard_option3, PhysListEmStandard_option4, PhysListEmStandard_option4, PhysListEmStandard_SS, PhysListEmStandard_SS, PhysListEmStandard_WVI, PhysListEmStandard_WVI, PhysListEmStandardGS, PhysListEmStandardNR, PhysListEmStandardSS, PhysListEmStandardSSM, PhysListEmStandardWVI, PionPhysics, ProtonPhysics, pyG4VPhysicsConstructor::CB_G4VPhysicsConstructor, StepLimiterBuilder, StepMaxBuilder, and TransitionRadiationPhysics.
Public Member Functions
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
virtual void ConstructParticle ()=0
virtual void ConstructProcess ()=0
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Static Public Member Functions
static const G4VPCManager & GetSubInstanceManager ()
Protected Types
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 125 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 125 of file G4VPhysicsConstructor.hh
Member Typedef Documentation
using G4VPhysicsConstructor::PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V protected
Definition at line 173 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 173 of file G4VPhysicsConstructor.hh
Constructor & Destructor Documentation
G4VPhysicsConstructor::G4VPhysicsConstructor (const G4String & name = "")
Definition at line 48 of file G4VPhysicsConstructor.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VPhysicsConstructor.cc
References G4VUPLSplitter< T >::CreateSubInstance(), g4vpcInstanceID, G4ParticleTable::GetParticleTable(), subInstanceManager, and theParticleTable.
G4VPhysicsConstructor::G4VPhysicsConstructor (const G4String & name, G4int physics_type)
Definition at line 60 of file G4VPhysicsConstructor.cc.
View newest version in sPHENIX GitHub at line 60 of file G4VPhysicsConstructor.cc
References G4VUPLSplitter< T >::CreateSubInstance(), g4vpcInstanceID, G4ParticleTable::GetParticleTable(), subInstanceManager, theParticleTable, and typePhysics.
G4VPhysicsConstructor::~G4VPhysicsConstructor () virtual
Definition at line 74 of file G4VPhysicsConstructor.cc.
View newest version in sPHENIX GitHub at line 74 of file G4VPhysicsConstructor.cc
References TerminateWorker().
Member Function Documentation
void G4VPhysicsConstructor::AddBuilder (G4PhysicsBuilderInterface * bld) protected
Definition at line 94 of file G4VPhysicsConstructor.cc.
View newest version in sPHENIX GitHub at line 94 of file G4VPhysicsConstructor.cc
References g4vpcInstanceID, G4VUPLSplitter< T >::offset, and subInstanceManager.
Referenced by G4HadronPhysicsQGS_BIC::Kaon(), G4HadronPhysicsShieldingLEND::Kaon(), G4HadronPhysicsFTF_BIC::Kaon(), G4HadronPhysicsShielding::Kaon(), G4HadronPhysicsFTFP_BERT::Kaon(), G4HadronPhysicsINCLXX::Kaon(), G4HadronPhysicsFTFP_BERT_HP::Neutron(), G4HadronPhysicsFTFP_BERT_ATL::Neutron(), G4HadronPhysicsQGS_BIC::Neutron(), G4HadronPhysicsFTF_BIC::Neutron(), G4HadronPhysicsShieldingLEND::Neutron(), G4HadronPhysicsQGSP_BIC::Neutron(), G4HadronPhysicsQGSP_BERT::Neutron(), G4HadronPhysicsShielding::Neutron(), G4HadronPhysicsFTFP_BERT::Neutron(), G4HadronPhysicsINCLXX::Neutron(), G4HadronPhysicsQGSP_BERT_HP::Neutron(), G4HadronPhysicsQGS_BIC::Others(), G4HadronPhysicsShieldingLEND::Others(), G4HadronPhysicsFTF_BIC::Others(), G4HadronPhysicsQGSP_BIC::Others(), G4HadronPhysicsQGSP_BERT::Others(), G4HadronPhysicsShielding::Others(), G4HadronPhysicsFTFP_BERT::Others(), G4HadronPhysicsINCLXX::Others(), G4HadronPhysicsFTFP_BERT_TRV::Pion(), G4HadronPhysicsFTFP_BERT_ATL::Pion(), G4HadronPhysicsQGS_BIC::Pion(), G4HadronPhysicsShieldingLEND::Pion(), G4HadronPhysicsFTF_BIC::Pion(), G4HadronPhysicsQGSP_BIC::Pion(), G4HadronPhysicsQGSP_BERT::Pion(), G4HadronPhysicsShielding::Pion(), G4HadronPhysicsFTFP_BERT::Pion(), G4HadronPhysicsNuBeam::Pion(), G4HadronPhysicsINCLXX::Pion(), G4HadronPhysicsFTFP_BERT_ATL::Proton(), G4HadronPhysicsQGS_BIC::Proton(), G4HadronPhysicsShieldingLEND::Proton(), G4HadronPhysicsFTF_BIC::Proton(), G4HadronPhysicsQGSP_BIC::Proton(), G4HadronPhysicsQGSP_BERT::Proton(), G4HadronPhysicsShielding::Proton(), G4HadronPhysicsFTFP_BERT::Proton(), G4HadronPhysicsNuBeam::Proton(), and G4HadronPhysicsINCLXX::Proton().
virtual void G4VPhysicsConstructor::ConstructParticle () pure virtual
Implemented in G4GenericBiasingPhysics, GammaRayTelHadronPhysics, G4HadronPhysicsFTFQGSP_BERT, G4HadronPhysicsQGSP_BIC_HP, GammaRayTelIonPhysics, G4StoppingPhysics, G4OpticalPhysics, G4HadronPhysicsINCLXX, G4HadronPhysicsQGSP_BIC_AllHP, HadronPhysicsHIJING, CexmcStudiedPhysics< Process >, HadronPhysicsUrQMD, CexmcStudiedPhysics< CexmcHadronicProcess >, ExN04EMPhysics, G4HadronElasticPhysics, P6DExtDecayerPhysics, G4EmExtraPhysics, G4HadronPhysicsShielding, G4FastSimulationPhysics, GammaRayTelMuonPhysics, G4EmStandardPhysics_option2, G4HadronPhysicsQGSP_BERT, G4IonPhysicsPHP, G4IonQMDPhysics, G4StoppingPhysicsFritiofWithBinaryCascade, IonCRMCPhysics, G4EmStandardPhysics_option1, G4HadronPhysicsFTFP_BERT, G4HadronPhysicsQGSP_BIC, HadronPhysicsCRMC_FTFP_BERT, G4EmStandardPhysics_option4, G4EmStandardPhysicsWVI, G4IonINCLXXPhysics, G4EmStandardPhysics_option4_channeling, G4EmStandardPhysics, G4EmStandardPhysics_option3, G4EmStandardPhysicsGS, G4VHadronPhysics, G4IonPhysics, GammaRayTelGeneralPhysics, PhysListEm5DStandard, PhysListEm19DStandard, PhysListEm5DStandard, G4DecayPhysics, G4SpinDecayPhysics, G4EmStandardPhysicsSS, G4HadronPhysicsFTF_BIC, G4HadronPhysicsShieldingLEND, GammaRayTelEMlowePhysics, GammaRayTelEMstdPhysics, PhysListEm5DStandard, P6DExtDecayerPhysics, G4HadronHElasticPhysics, G4HadronPhysicsQGS_BIC, G4EmDNAPhysics_option6, Decay, G4UnknownDecayPhysics, G4HadronDElasticPhysics, G4IonElasticPhysics, G4NeutronTrackingCut, G4MonopolePhysics, G4EmLEPTSPhysics, G4ChargeExchangePhysics, PhysListEmStandard_option0, PhysListEmStandard_option3, PhysListEmStandard_option4, PhysListEmStandard_SS, G4StepLimiterPhysics, G4WeightWindowBiasing, TransitionRadiationPhysics, PhysListEmStandard_GS, PhysListEmStandard_WVI, G4NeutronCrossSectionXS, G4ImportanceBiasing, pyG4VPhysicsConstructor::CB_G4VPhysicsConstructor, PhysicsListEMstd, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, NeutronHPphysics, PhysListEmStandardWVI, PhysListEmStandard_SS, PhysListEmPolarized, PhysListEmStandard, PhysListEmStandardSSM, PhysListEmLivermore, PhysListEmPenelope, PhysListEmStandard, PhysListEmLivermore, PhysListEmPenelope, PhysListEmStandard, MuNuclearBuilder, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandardNR, PhysListEmStandard, ElectromagneticPhysics, ElectromagneticPhysics, ElectromagneticPhysics, PhysListEmStandard, PhysListEmStandardGS, PhysListEmStandardSS, PhysListEmStandard_GS, PhysListEmStandard_option0, PhysListEmStandard_option3, PhysListEmStandard_option4, PhysListEmStandard_WVI, StepLimiterBuilder, ElectromagneticPhysics, G4ParallelWorldPhysics, Particles, PhysicsListEMstd, GammaRayTelParticles, GammaNuclearPhysics, GammaNuclearPhysics, GammaNuclearPhysics, StepMaxBuilder, GammaNuclearPhysics, GammaNuclearPhysics, G4EmDNAPhysicsActivator, PhysListEmStandard, G4RadioactiveDecayPhysics, PhysListEmStandard, ExUCNExtraPhysics, G4EmDNAChemistry_option2, PhysListEmLivermore, PhysListEmPenelope, G4ChannelingPhysics, G4MuonicAtomDecayPhysics, G4EmDNAChemistry, G4EmDNAChemistry_option1, G4EmDNAPhysics_option4, G4EmDNAPhysics_option5, G4EmDNAPhysics_option7, G4EmDNAPhysics_option8, G4EmDNAPhysics, G4EmDNAPhysics_option1, G4EmDNAPhysics_option2, G4EmLivermorePhysics, G4EmLivermorePolarizedPhysics, G4EmLowEPPhysics, G4EmPenelopePhysics, BiasedRDPhysics, G4EmDNAPhysics_stationary, G4EmDNAPhysics_stationary_option2, G4EmDNAPhysics_stationary_option4, G4EmDNAPhysics_stationary_option6, HadrontherapyParticles, G4EmDNAPhysics_option3, GammaKnifeParticles, GammaLeptoNuclearPhysics, IonPhysics, ProtonPhysics, AntiBaryonPhysics, HyperonPhysics, KaonPhysics, NeutronPhysics, and PionPhysics.
Referenced by GammaKnifePhysicsList::ConstructParticle(), GammaRayTelPhysicsList::ConstructParticle(), STCyclotronPhysicsList::ConstructParticle(), UltraPhysicsList::ConstructParticle(), IORTPhysicsList::ConstructParticle(), ML2PhysicsList::ConstructParticle(), and export_G4VPhysicsConstructor().
virtual void G4VPhysicsConstructor::ConstructProcess () pure virtual
Implemented in G4GenericBiasingPhysics, GammaRayTelHadronPhysics, G4HadronPhysicsFTFQGSP_BERT, GammaRayTelIonPhysics, G4StoppingPhysics, G4HadronPhysicsQGSP_BIC_HP, G4OpticalPhysics, G4HadronPhysicsINCLXX, G4HadronPhysicsQGSP_BIC_AllHP, HadronPhysicsHIJING, ExN04EMPhysics, G4HadronElasticPhysics, CexmcStudiedPhysics< Process >, G4FastSimulationPhysics, CexmcStudiedPhysics< CexmcHadronicProcess >, GammaRayTelMuonPhysics, HadronPhysicsUrQMD, G4IonQMDPhysics, G4StoppingPhysicsFritiofWithBinaryCascade, G4HadronPhysicsFTFP_BERT, IonHIJINGPhysics, G4IonINCLXXPhysics, P6DExtDecayerPhysics, G4EmExtraPhysics, G4HadronPhysicsShielding, IonUrQMDPhysics, G4SpinDecayPhysics, G4EmStandardPhysics_option2, G4HadronInelasticQBBC, G4HadronPhysicsQGSP_BERT, G4IonPhysicsPHP, GammaRayTelGeneralPhysics, IonCRMCPhysics, G4DecayPhysics, G4EmStandardPhysics_option1, G4HadronPhysicsQGSP_BIC, HadronPhysicsCRMC_FTFP_BERT, G4EmStandardPhysics_option4, G4EmStandardPhysicsWVI, GammaRayTelEMlowePhysics, GammaRayTelEMstdPhysics, G4EmStandardPhysics_option4_channeling, G4EmStandardPhysics, G4EmStandardPhysics_option3, G4EmStandardPhysicsGS, G4HadronHElasticPhysics, G4IonPhysics, PhysListEm5DStandard, PhysListEm19DStandard, PhysListEm5DStandard, G4UnknownDecayPhysics, G4EmStandardPhysicsSS, G4HadronDElasticPhysics, G4IonElasticPhysics, G4HadronPhysicsFTF_BIC, G4HadronPhysicsShieldingLEND, G4NeutronTrackingCut, G4MonopolePhysics, G4ChargeExchangePhysics, PhysListEm5DStandard, P6DExtDecayerPhysics, PhysListEmStandard_option0, PhysListEmStandard_option3, PhysListEmStandard_option4, PhysListEmStandard_SS, G4HadronPhysicsQGS_BIC, G4StepLimiterPhysics, G4WeightWindowBiasing, TransitionRadiationPhysics, PhysListEmStandard_GS, PhysListEmStandard_WVI, G4EmDNAPhysics_option6, G4ImportanceBiasing, Decay, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandardWVI, PhysListEmStandard_SS, PhysListEmPolarized, G4HadronElasticPhysicsLEND, pyG4VPhysicsConstructor::CB_G4VPhysicsConstructor, PhysListEmStandard, PhysListEmStandardSSM, PhysListEmLivermore, PhysListEmPenelope, PhysListEmStandard, PhysListEmLivermore, PhysListEmPenelope, PhysListEmStandard, MuNuclearBuilder, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandard, PhysListEmStandardNR, PhysListEmStandard, ElectromagneticPhysics, ElectromagneticPhysics, ElectromagneticPhysics, PhysListEmStandard, PhysListEmStandardGS, PhysListEmStandardSS, PhysListEmStandard_GS, PhysListEmStandard_option0, PhysListEmStandard_option3, PhysListEmStandard_option4, PhysListEmStandard_WVI, StepLimiterBuilder, ElectromagneticPhysics, G4EmLEPTSPhysics, G4HadronElasticPhysicsHP, G4HadronElasticPhysicsXS, G4ParallelWorldPhysics, G4HadronElasticPhysicsPHP, PhysListEmStandard, G4NeutronCrossSectionXS, G4RadioactiveDecayPhysics, PhysicsListEMstd, PhysListEmStandard, GammaRayTelParticles, NeutronHPphysics, G4ThermalNeutrons, HadronElasticPhysicsHP, HadronElasticPhysicsHP, HadronElasticPhysicsHP, HadronElasticPhysicsHP, G4MuonicAtomDecayPhysics, G4EmDNAChemistry_option2, Particles, PhysicsListEMstd, GammaNuclearPhysics, GammaNuclearPhysics, GammaNuclearPhysics, StepMaxBuilder, GammaNuclearPhysics, GammaNuclearPhysics, G4EmDNAChemistry, G4EmDNAChemistry_option1, G4EmDNAPhysicsActivator, BiasedRDPhysics, ExUCNExtraPhysics, PhysListEmLivermore, PhysListEmPenelope, G4ChannelingPhysics, G4EmDNAPhysics_option4, G4EmDNAPhysics_option5, G4EmDNAPhysics_option7, G4EmDNAPhysics_option8, HadrontherapyParticles, G4EmDNAPhysics, G4EmDNAPhysics_option1, G4EmDNAPhysics_option2, G4EmLivermorePhysics, G4EmLivermorePolarizedPhysics, G4EmLowEPPhysics, G4EmPenelopePhysics, G4EmDNAPhysics_stationary, G4EmDNAPhysics_stationary_option2, G4EmDNAPhysics_stationary_option4, G4EmDNAPhysics_stationary_option6, GammaKnifeParticles, G4EmDNAPhysics_option3, IonPhysics, GammaLeptoNuclearPhysics, AntiBaryonPhysics, HyperonPhysics, KaonPhysics, NeutronPhysics, PionPhysics, and ProtonPhysics.
Referenced by STCyclotronPhysicsList::ConstructProcess(), GammaKnifePhysicsList::ConstructProcess(), PhysicsList::ConstructProcess(), XrayFluoPhysicsList::ConstructProcess(), doiPETPhysicsList::ConstructProcess(), GammaRayTelPhysicsList::ConstructProcess(), UltraPhysicsList::ConstructProcess(), ML2PhysicsList::ConstructProcess(), IORTPhysicsList::ConstructProcess(), and export_G4VPhysicsConstructor().
G4VPhysicsConstructor::PhysicsBuilder_V G4VPhysicsConstructor::GetBuilders () const protected
Definition at line 85 of file G4VPhysicsConstructor.cc.
View newest version in sPHENIX GitHub at line 85 of file G4VPhysicsConstructor.cc
References field_utils::copy(), g4vpcInstanceID, G4VUPLSplitter< T >::offset, and subInstanceManager.
G4int G4VPhysicsConstructor::GetInstanceID () const inline
G4ParticleTable::G4PTblDicIterator * G4VPhysicsConstructor::GetParticleIterator () const protected
Definition at line 80 of file G4VPhysicsConstructor.cc.
View newest version in sPHENIX GitHub at line 80 of file G4VPhysicsConstructor.cc
References g4vpcInstanceID, G4VUPLSplitter< T >::offset, and subInstanceManager.
Referenced by G4GenericBiasingPhysics::AssociateParallelGeometries(), G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), ExUCNExtraPhysics::ConstructProcess(), StepMaxBuilder::ConstructProcess(), PhysListEmStandardSSM::ConstructProcess(), PhysListEmPenelope::ConstructProcess(), G4EmLEPTSPhysics::ConstructProcess(), ElectromagneticPhysics::ConstructProcess(), StepLimiterBuilder::ConstructProcess(), G4ParallelWorldPhysics::ConstructProcess(), PhysListEmStandardGS::ConstructProcess(), PhysListEmLivermore::ConstructProcess(), PhysListEmStandardSS::ConstructProcess(), PhysListEmStandardNR::ConstructProcess(), PhysListEmPolarized::ConstructProcess(), PhysListEmStandardWVI::ConstructProcess(), PhysListEmStandard_GS::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), PhysListEmStandard_WVI::ConstructProcess(), PhysListEmStandard_option0::ConstructProcess(), PhysListEmStandard_option3::ConstructProcess(), PhysListEmStandard_option4::ConstructProcess(), PhysListEmStandard_SS::ConstructProcess(), G4StepLimiterPhysics::ConstructProcess(), G4ChargeExchangePhysics::ConstructProcess(), G4UnknownDecayPhysics::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), G4HadronDElasticPhysics::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), G4DecayPhysics::ConstructProcess(), GammaRayTelGeneralPhysics::ConstructProcess(), G4HadronInelasticQBBC::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), G4StoppingPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), and ExUCNExtraPhysics::ConstructUCN().
const G4String & G4VPhysicsConstructor::GetPhysicsName () const inline
Definition at line 205 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 205 of file G4VPhysicsConstructor.hh
References namePhysics.
Referenced by G4EmDNAPhysics_option3::ConstructProcess(), G4EmDNAPhysics_stationary_option2::ConstructProcess(), G4EmDNAPhysics_stationary_option4::ConstructProcess(), G4EmDNAPhysics_stationary_option6::ConstructProcess(), G4EmDNAPhysics_stationary::ConstructProcess(), G4EmDNAPhysics::ConstructProcess(), G4EmDNAPhysics_option2::ConstructProcess(), G4EmLivermorePhysics::ConstructProcess(), G4EmLivermorePolarizedPhysics::ConstructProcess(), G4EmLowEPPhysics::ConstructProcess(), G4EmPenelopePhysics::ConstructProcess(), G4EmDNAPhysics_option1::ConstructProcess(), G4EmDNAPhysics_option4::ConstructProcess(), G4EmDNAPhysics_option5::ConstructProcess(), G4EmDNAPhysics_option7::ConstructProcess(), G4EmDNAPhysics_option8::ConstructProcess(), G4ThermalNeutrons::ConstructProcess(), G4EmDNAPhysics_option6::ConstructProcess(), G4EmStandardPhysicsSS::ConstructProcess(), PhysListEm19DStandard::ConstructProcess(), PhysListEm5DStandard::ConstructProcess(), G4EmStandardPhysics_option4_channeling::ConstructProcess(), G4EmStandardPhysics::ConstructProcess(), G4EmStandardPhysics_option3::ConstructProcess(), G4EmStandardPhysicsGS::ConstructProcess(), G4EmStandardPhysics_option4::ConstructProcess(), G4EmStandardPhysicsWVI::ConstructProcess(), G4EmStandardPhysics_option1::ConstructProcess(), G4EmStandardPhysics_option2::ConstructProcess(), export_G4VPhysicsConstructor(), F04PhysicsList::F04PhysicsList(), G4HadronDElasticPhysics::G4HadronDElasticPhysics(), G4HadronElasticPhysics::G4HadronElasticPhysics(), G4HadronElasticPhysicsHP::G4HadronElasticPhysicsHP(), G4HadronElasticPhysicsLEND::G4HadronElasticPhysicsLEND(), G4HadronElasticPhysicsPHP::G4HadronElasticPhysicsPHP(), G4HadronElasticPhysicsXS::G4HadronElasticPhysicsXS(), G4HadronHElasticPhysics::G4HadronHElasticPhysics(), G4IonElasticPhysics::G4IonElasticPhysics(), G4VModularPhysicsList::RegisterPhysics(), and G4VModularPhysicsList::ReplacePhysics().
G4int G4VPhysicsConstructor::GetPhysicsType () const inline
Definition at line 215 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 215 of file G4VPhysicsConstructor.hh
References typePhysics.
Referenced by G4VModularPhysicsList::RegisterPhysics(), and G4VModularPhysicsList::ReplacePhysics().
const G4VPCManager & G4VPhysicsConstructor::GetSubInstanceManager () inline static
Definition at line 229 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 229 of file G4VPhysicsConstructor.hh
References subInstanceManager.
Referenced by G4PhysicsListWorkspace::G4PhysicsListWorkspace().
G4int G4VPhysicsConstructor::GetVerboseLevel () const inline
Definition at line 195 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 195 of file G4VPhysicsConstructor.hh
References verboseLevel.
Referenced by G4MuonicAtomDecayPhysics::ConstructParticle(), G4MuonicAtomDecayPhysics::ConstructProcess(), export_G4VPhysicsConstructor(), and G4MuonicAtomDecayPhysics::G4MuonicAtomDecayPhysics().
G4bool G4VPhysicsConstructor::RegisterProcess (G4VProcess * process, G4ParticleDefinition * particle) inline protected
Definition at line 221 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 221 of file G4VPhysicsConstructor.hh
References G4PhysicsListHelper::GetPhysicsListHelper(), and G4PhysicsListHelper::RegisterProcess().
Referenced by BiasedRDPhysics::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), G4MuonicAtomDecayPhysics::ConstructProcess(), and G4RadioactiveDecayPhysics::ConstructProcess().
void G4VPhysicsConstructor::SetPhysicsName (const G4String & name = "") inline
Definition at line 200 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 200 of file G4VPhysicsConstructor.hh
References namePhysics.
Referenced by export_G4VPhysicsConstructor().
void G4VPhysicsConstructor::SetPhysicsType (G4int val) inline
Definition at line 210 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 210 of file G4VPhysicsConstructor.hh
References typePhysics.
Referenced by ElectromagneticPhysics::ElectromagneticPhysics(), G4EmDNAPhysics::G4EmDNAPhysics(), G4EmDNAPhysics_option1::G4EmDNAPhysics_option1(), G4EmDNAPhysics_option2::G4EmDNAPhysics_option2(), G4EmDNAPhysics_option3::G4EmDNAPhysics_option3(), G4EmDNAPhysics_option4::G4EmDNAPhysics_option4(), G4EmDNAPhysics_option5::G4EmDNAPhysics_option5(), G4EmDNAPhysics_option6::G4EmDNAPhysics_option6(), G4EmDNAPhysics_option7::G4EmDNAPhysics_option7(), G4EmDNAPhysics_option8::G4EmDNAPhysics_option8(), G4EmDNAPhysics_stationary::G4EmDNAPhysics_stationary(), G4EmDNAPhysics_stationary_option2::G4EmDNAPhysics_stationary_option2(), G4EmDNAPhysics_stationary_option4::G4EmDNAPhysics_stationary_option4(), G4EmDNAPhysics_stationary_option6::G4EmDNAPhysics_stationary_option6(), G4EmExtraPhysics::G4EmExtraPhysics(), G4EmLEPTSPhysics::G4EmLEPTSPhysics(), G4EmLivermorePhysics::G4EmLivermorePhysics(), G4EmLivermorePolarizedPhysics::G4EmLivermorePolarizedPhysics(), G4EmLowEPPhysics::G4EmLowEPPhysics(), G4EmPenelopePhysics::G4EmPenelopePhysics(), G4EmStandardPhysics::G4EmStandardPhysics(), G4EmStandardPhysics_option1::G4EmStandardPhysics_option1(), G4EmStandardPhysics_option2::G4EmStandardPhysics_option2(), G4EmStandardPhysics_option3::G4EmStandardPhysics_option3(), G4EmStandardPhysics_option4::G4EmStandardPhysics_option4(), G4EmStandardPhysics_option4_channeling::G4EmStandardPhysics_option4_channeling(), G4EmStandardPhysicsGS::G4EmStandardPhysicsGS(), G4EmStandardPhysicsSS::G4EmStandardPhysicsSS(), G4EmStandardPhysicsWVI::G4EmStandardPhysicsWVI(), G4IonINCLXXPhysics::G4IonINCLXXPhysics(), G4IonPhysics::G4IonPhysics(), G4IonPhysicsPHP::G4IonPhysicsPHP(), G4IonQMDPhysics::G4IonQMDPhysics(), G4MonopolePhysics::G4MonopolePhysics(), G4NeutronTrackingCut::G4NeutronTrackingCut(), G4StepLimiterPhysics::G4StepLimiterPhysics(), PhysListEm19DStandard::PhysListEm19DStandard(), PhysListEm5DStandard::PhysListEm5DStandard(), PhysListEmStandard_GS::PhysListEmStandard_GS(), PhysListEmStandard_option0::PhysListEmStandard_option0(), PhysListEmStandard_option3::PhysListEmStandard_option3(), PhysListEmStandard_option4::PhysListEmStandard_option4(), PhysListEmStandard_SS::PhysListEmStandard_SS(), PhysListEmStandard_WVI::PhysListEmStandard_WVI(), PhysListEmStandardNR::PhysListEmStandardNR(), PhysListEmStandardSS::PhysListEmStandardSS(), and PhysListEmStandardWVI::PhysListEmStandardWVI().
void G4VPhysicsConstructor::SetVerboseLevel (G4int value) inline
Definition at line 190 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 190 of file G4VPhysicsConstructor.hh
References verboseLevel.
Referenced by export_G4VPhysicsConstructor(), G4MuonicAtomDecayPhysics::G4MuonicAtomDecayPhysics(), G4VHadronPhysics::G4VHadronPhysics(), PhysicsListEMstd::PhysicsListEMstd(), PhysicsList::RegisterConstructor(), and G4OpticalPhysicsMessenger::SetNewValue().
void G4VPhysicsConstructor::TerminateWorker () virtual
Definition at line 99 of file G4VPhysicsConstructor.cc.
View newest version in sPHENIX GitHub at line 99 of file G4VPhysicsConstructor.cc
References g4vpcInstanceID, G4VUPLSplitter< T >::offset, and subInstanceManager.
Referenced by ~G4VPhysicsConstructor().
Member Data Documentation
G4int G4VPhysicsConstructor::g4vpcInstanceID protected
Definition at line 170 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 170 of file G4VPhysicsConstructor.hh
Referenced by AddBuilder(), G4VPhysicsConstructor(), GetBuilders(), GetParticleIterator(), and TerminateWorker().
G4String G4VPhysicsConstructor::namePhysics protected
Definition at line 166 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 166 of file G4VPhysicsConstructor.hh
Referenced by G4ParallelWorldPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), GetPhysicsName(), and SetPhysicsName().
G4VPCManager G4VPhysicsConstructor::subInstanceManager static protected
Definition at line 171 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 171 of file G4VPhysicsConstructor.hh
Referenced by AddBuilder(), G4VPhysicsConstructor(), GetBuilders(), GetParticleIterator(), GetSubInstanceManager(), and TerminateWorker().
G4ParticleTable* G4VPhysicsConstructor::theParticleTable protected
Definition at line 169 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 169 of file G4VPhysicsConstructor.hh
Referenced by PhysListEmStandard::ConstructProcess(), and G4VPhysicsConstructor().
G4int G4VPhysicsConstructor::typePhysics protected
Definition at line 167 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 167 of file G4VPhysicsConstructor.hh
Referenced by G4VPhysicsConstructor(), GetPhysicsType(), and SetPhysicsType().
G4int G4VPhysicsConstructor::verboseLevel protected
Definition at line 165 of file G4VPhysicsConstructor.hh.
View newest version in sPHENIX GitHub at line 165 of file G4VPhysicsConstructor.hh
Referenced by G4VHadronPhysics::AddCaptureCrossSection(), G4VHadronPhysics::AddElasticCrossSection(), G4VHadronPhysics::AddFissionCrossSection(), G4VHadronPhysics::AddInelasticCrossSection(), G4VHadronPhysics::BuildModel(), G4MonopolePhysics::ConstructProcess(), P6DExtDecayerPhysics::ConstructProcess(), G4OpticalPhysics::ConstructProcess(), G4MuonicAtomDecayPhysics::G4MuonicAtomDecayPhysics(), G4OpticalPhysics::G4OpticalPhysics(), G4VHadronPhysics::G4VHadronPhysics(), GetVerboseLevel(), G4VHadronPhysics::NewModel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4VPhysicsConstructor.hh
geant4/tree/geant4-10.6-release/source/run/src/G4VPhysicsConstructor.cc