ECCE @ EIC Software: G4IonConstructor Class Reference
G4IonConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/include/G4IonConstructor.hh>
Public Member Functions
G4IonConstructor ()
~G4IonConstructor ()
Static Public Member Functions
static void ConstructParticle ()
Static Protected Member Functions
static void ConstructLightIons ()
Detailed Description
Definition at line 38 of file G4IonConstructor.hh.
View newest version in sPHENIX GitHub at line 38 of file G4IonConstructor.hh
Constructor & Destructor Documentation
G4IonConstructor::G4IonConstructor ()
Definition at line 49 of file G4IonConstructor.cc.
View newest version in sPHENIX GitHub at line 49 of file G4IonConstructor.cc
G4IonConstructor::~G4IonConstructor ()
Definition at line 53 of file G4IonConstructor.cc.
View newest version in sPHENIX GitHub at line 53 of file G4IonConstructor.cc
Member Function Documentation
void G4IonConstructor::ConstructLightIons () static protected
Definition at line 63 of file G4IonConstructor.cc.
View newest version in sPHENIX GitHub at line 63 of file G4IonConstructor.cc
References G4Alpha::AlphaDefinition(), G4AntiAlpha::AntiAlphaDefinition(), G4AntiDeuteron::AntiDeuteronDefinition(), G4AntiHe3::AntiHe3Definition(), G4AntiTriton::AntiTritonDefinition(), G4Deuteron::DeuteronDefinition(), G4GenericIon::GenericIonDefinition(), G4He3::He3Definition(), and G4Triton::TritonDefinition().
Referenced by ConstructParticle().
void G4IonConstructor::ConstructParticle (void) static
Definition at line 58 of file G4IonConstructor.cc.
View newest version in sPHENIX GitHub at line 58 of file G4IonConstructor.cc
References ConstructLightIons().
Referenced by B03PhysicsList::ConstructAllIons(), Par02PhysicsList::ConstructIons(), XrayTelPhysicsList::ConstructIons(), DMXPhysicsList::ConstructMyHadrons(), LBE::ConstructMyIons(), EICPhysicsList::ConstructParticle(), GammaKnifeParticles::ConstructParticle(), HadrontherapyParticles::ConstructParticle(), G4ChannelingPhysics::ConstructParticle(), Particles::ConstructParticle(), XrayFluoPhysicsList::ConstructParticle(), G4HadronDElasticPhysics::ConstructParticle(), G4HadronPhysicsQGS_BIC::ConstructParticle(), G4HadronHElasticPhysics::ConstructParticle(), G4DecayPhysics::ConstructParticle(), G4HadronPhysicsShieldingLEND::ConstructParticle(), G4IonPhysics::ConstructParticle(), G4VHadronPhysics::ConstructParticle(), G4IonINCLXXPhysics::ConstructParticle(), G4HadronPhysicsQGSP_BIC::ConstructParticle(), G4HadronPhysicsQGSP_BERT::ConstructParticle(), G4IonPhysicsPHP::ConstructParticle(), G4IonQMDPhysics::ConstructParticle(), G4HadronPhysicsShielding::ConstructParticle(), G4HadronElasticPhysics::ConstructParticle(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructParticle(), G4HadronPhysicsINCLXX::ConstructParticle(), G4HadronPhysicsQGSP_BIC_HP::ConstructParticle(), and G4RunManagerKernel::SetupPhysics().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/include/G4IonConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/hadrons/ions/src/G4IonConstructor.cc