ECCE @ EIC Software: G4LogicalSurface Class Reference
G4LogicalSurface Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4LogicalSurface.hh>
Public Member Functions
G4SurfaceProperty * GetSurfaceProperty () const
void SetSurfaceProperty (G4SurfaceProperty *ptrSurfaceProperty)
const G4String & GetName () const
void SetName (const G4String &name)
G4TransitionRadiationSurface * GetTransitionRadiationSurface () const
void SetTransitionRadiationSurface (G4TransitionRadiationSurface *trs)
virtual ~G4LogicalSurface ()
G4LogicalSurface (const G4LogicalSurface &)=delete
G4LogicalSurface & operator= (const G4LogicalSurface &)=delete
G4bool operator== (const G4LogicalSurface &right) const
G4bool operator!= (const G4LogicalSurface &right) const
Protected Member Functions
G4LogicalSurface (const G4String &name, G4SurfaceProperty *prop)
Private Attributes
G4String theName
G4SurfaceProperty * theSurfaceProperty = nullptr
G4TransitionRadiationSurface * theTransRadSurface = nullptr
Detailed Description
Definition at line 64 of file G4LogicalSurface.hh.
View newest version in sPHENIX GitHub at line 64 of file G4LogicalSurface.hh
Constructor & Destructor Documentation
G4LogicalSurface::~G4LogicalSurface () virtual
Definition at line 39 of file G4LogicalSurface.cc.
View newest version in sPHENIX GitHub at line 39 of file G4LogicalSurface.cc
G4LogicalSurface::G4LogicalSurface (const G4LogicalSurface &) delete
G4LogicalSurface::G4LogicalSurface (const G4String & name, G4SurfaceProperty * prop) protected
Definition at line 33 of file G4LogicalSurface.cc.
View newest version in sPHENIX GitHub at line 33 of file G4LogicalSurface.cc
Member Function Documentation
const G4String& G4LogicalSurface::GetName () const inline
Referenced by PHG4GDMLWriteStructure::BorderSurfaceCache(), G4GDMLWriteStructure::BorderSurfaceCache(), ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD(), ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH(), PHG4GDMLWriteStructure::SkinSurfaceCache(), and G4GDMLWriteStructure::SkinSurfaceCache().
G4SurfaceProperty* G4LogicalSurface::GetSurfaceProperty () const inline
Referenced by PHG4GDMLWriteStructure::BorderSurfaceCache(), G4GDMLWriteStructure::BorderSurfaceCache(), OpNoviceDetectorConstruction::Construct(), G4OpBoundaryProcess::PostStepDoIt(), PHG4GDMLWriteStructure::SkinSurfaceCache(), and G4GDMLWriteStructure::SkinSurfaceCache().
G4TransitionRadiationSurface* G4LogicalSurface::GetTransitionRadiationSurface () const inline
G4bool G4LogicalSurface::operator!= (const G4LogicalSurface & right) const inline
G4LogicalSurface& G4LogicalSurface::operator= (const G4LogicalSurface &) delete
G4bool G4LogicalSurface::operator== (const G4LogicalSurface & right) const inline
void G4LogicalSurface::SetName (const G4String & name) inline
void G4LogicalSurface::SetSurfaceProperty (G4SurfaceProperty * ptrSurfaceProperty) inline
void G4LogicalSurface::SetTransitionRadiationSurface (G4TransitionRadiationSurface * trs) inline
Member Data Documentation
G4String G4LogicalSurface::theName private
Definition at line 97 of file G4LogicalSurface.hh.
View newest version in sPHENIX GitHub at line 97 of file G4LogicalSurface.hh
G4SurfaceProperty* G4LogicalSurface::theSurfaceProperty = nullptr private
Definition at line 99 of file G4LogicalSurface.hh.
View newest version in sPHENIX GitHub at line 99 of file G4LogicalSurface.hh
G4TransitionRadiationSurface* G4LogicalSurface::theTransRadSurface = nullptr private
Definition at line 100 of file G4LogicalSurface.hh.
View newest version in sPHENIX GitHub at line 100 of file G4LogicalSurface.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4LogicalSurface.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4LogicalSurface.cc