ECCE @ EIC Software: G4CollisionNN Class Reference
G4CollisionNN Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionNN.hh>
Public Member Functions
G4CollisionNN ()
virtual ~G4CollisionNN ()
G4bool operator== (const G4CollisionNN &right) const
G4bool operator!= (const G4CollisionNN &right) const
virtual G4String GetName () const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Public Member Functions inherited from G4GeneralNNCollision
G4bool IsInCharge (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Public Member Functions inherited from G4CollisionComposite
G4CollisionComposite ()
virtual ~G4CollisionComposite ()
virtual G4KineticTrackVector * FinalState (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
void AddComponent (G4VCollision *aC)
Public Member Functions inherited from G4VCollision
G4VCollision ()
void establish_G4MT_TLS_G4VCollision ()
G4VCollision (void *s1, void *s2, void *s3, void *s4, void *s5, void *s6, void *s7)
virtual ~G4VCollision ()
G4bool operator== (const G4VCollision &right) const
G4bool operator!= (const G4VCollision &right) const
virtual void Print () const
virtual void Print (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Protected Member Functions
virtual const
G4VCrossSectionSource * GetCrossSectionSource () const
virtual const
G4VAngularDistribution * GetAngularDistribution () const
virtual const G4CollisionVector * GetComponents () const
virtual const std::vector
< G4String > & GetListOfColliders (G4int whichOne) const
Private Member Functions
G4CollisionNN (const G4CollisionNN &)
G4CollisionNN & operator= (const G4CollisionNN &)
Private Attributes
G4CollisionVector * components
G4VCrossSectionSource * crossSectionSource
std::vector< G4String > colliders1
std::vector< G4String > colliders2
Detailed Description
Definition at line 39 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 39 of file G4CollisionNN.hh
Constructor & Destructor Documentation
G4CollisionNN::G4CollisionNN ()
Definition at line 54 of file G4CollisionNN.cc.
View newest version in sPHENIX GitHub at line 54 of file G4CollisionNN.cc
References G4ForEach< group >::Apply(), and components.
G4CollisionNN::~G4CollisionNN () virtual
Definition at line 63 of file G4CollisionNN.cc.
View newest version in sPHENIX GitHub at line 63 of file G4CollisionNN.cc
References components, and crossSectionSource.
G4CollisionNN::G4CollisionNN (const G4CollisionNN &) private
Member Function Documentation
G4double G4CollisionNN::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Reimplemented from G4CollisionComposite.
Definition at line 81 of file G4CollisionNN.cc.
View newest version in sPHENIX GitHub at line 81 of file G4CollisionNN.cc
References G4VCrossSectionSource::CrossSection(), CLHEP::HepLorentzVector::e(), G4KineticTrack::Get4Momentum(), G4KineticTrack::GetActualMass(), GetCrossSectionSource(), G4KineticTrack::GetDefinition(), G4ParticleDefinition::GetPDGMass(), G4KineticTrack::Set4Momentum(), CLHEP::HepLorentzVector::setE(), t1, and t2.
virtual const G4VAngularDistribution* G4CollisionNN::GetAngularDistribution () const inline protected virtual
Reimplemented from G4CollisionComposite.
Definition at line 64 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 64 of file G4CollisionNN.hh
virtual const G4CollisionVector* G4CollisionNN::GetComponents () const inline protected virtual
Reimplemented from G4CollisionComposite.
Definition at line 66 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 66 of file G4CollisionNN.hh
References components.
virtual const G4VCrossSectionSource* G4CollisionNN::GetCrossSectionSource () const inline protected virtual
Reimplemented from G4CollisionComposite.
Definition at line 63 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 63 of file G4CollisionNN.hh
References crossSectionSource.
Referenced by CrossSection().
const std::vector< G4String > & G4CollisionNN::GetListOfColliders (G4int whichOne) const protected virtual
Implements G4VCollision.
Definition at line 74 of file G4CollisionNN.cc.
View newest version in sPHENIX GitHub at line 74 of file G4CollisionNN.cc
References colliders1.
virtual G4String G4CollisionNN::GetName (void) const inline virtual
Implements G4VCollision.
Definition at line 51 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 51 of file G4CollisionNN.hh
G4bool G4CollisionNN::operator!= (const G4CollisionNN & right) const
G4CollisionNN& G4CollisionNN::operator= (const G4CollisionNN &) private
G4bool G4CollisionNN::operator== (const G4CollisionNN & right) const
Member Data Documentation
std::vector<G4String> G4CollisionNN::colliders1 private
Definition at line 76 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CollisionNN.hh
Referenced by GetListOfColliders().
std::vector<G4String> G4CollisionNN::colliders2 private
Definition at line 77 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 77 of file G4CollisionNN.hh
G4CollisionVector* G4CollisionNN::components private
Definition at line 72 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 72 of file G4CollisionNN.hh
Referenced by GetComponents(), and ~G4CollisionNN().
G4VCrossSectionSource* G4CollisionNN::crossSectionSource private
Definition at line 74 of file G4CollisionNN.hh.
View newest version in sPHENIX GitHub at line 74 of file G4CollisionNN.hh
Referenced by GetCrossSectionSource(), and ~G4CollisionNN().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CollisionNN.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4CollisionNN.cc