ECCE @ EIC Software: G4VisManager Class Reference
G4VisManager Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisManager.hh>
Classes
struct UserVisAction
Public Types
enum Verbosity {
quiet, startup, errors, warnings,
confirmations, parameters, all
}
Public Member Functions
virtual ~G4VisManager ()
void Initialise ()
void Initialize ()
void RegisterRunDurationUserVisAction (const G4String &name, G4VUserVisAction *, const G4VisExtent &=G4VisExtent())
void RegisterEndOfEventUserVisAction (const G4String &name, G4VUserVisAction *, const G4VisExtent &=G4VisExtent())
void RegisterEndOfRunUserVisAction (const G4String &name, G4VUserVisAction *, const G4VisExtent &=G4VisExtent())
void SetUserAction (G4VUserVisAction *pVisAction, const G4VisExtent &=G4VisExtent())
void SetUserActionExtent (const G4VisExtent &)
G4bool RegisterGraphicsSystem (G4VGraphicsSystem *)
void RegisterModelFactory (G4TrajDrawModelFactory *factory)
void RegisterModel (G4VTrajectoryModel *model)
void RegisterModelFactory (G4TrajFilterFactory *factory)
void RegisterModel (G4VFilter< G4VTrajectory > *filter)
void RegisterModelFactory (G4HitFilterFactory *factory)
void RegisterModel (G4VFilter< G4VHit > *filter)
void RegisterModelFactory (G4DigiFilterFactory *factory)
void RegisterModel (G4VFilter< G4VDigi > *filter)
void SelectTrajectoryModel (const G4String &model)
void RegisterMessenger (G4UImessenger *messenger)
void Draw (const G4Circle &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4Polyhedron &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4Polyline &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4Polymarker &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4Scale &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4Square &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4Text &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw2D (const G4Circle &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw2D (const G4Polyhedron &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw2D (const G4Polyline &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw2D (const G4Polymarker &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw2D (const G4Square &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw2D (const G4Text &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4VTrajectory &)
void Draw (const G4VHit &)
void Draw (const G4VDigi &)
void Draw (const G4LogicalVolume &, const G4VisAttributes &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4VPhysicalVolume &, const G4VisAttributes &, const G4Transform3D &objectTransformation=G4Transform3D())
void Draw (const G4VSolid &, const G4VisAttributes &, const G4Transform3D &objectTransformation=G4Transform3D())
void BeginDraw (const G4Transform3D &objectTransformation=G4Transform3D())
void EndDraw ()
void BeginDraw2D (const G4Transform3D &objectTransformation=G4Transform3D())
void EndDraw2D ()
void GeometryHasChanged ()
void IgnoreStateChanges (G4bool)
void NotifyHandlers ()
void DispatchToModel (const G4VTrajectory &)
G4bool FilterTrajectory (const G4VTrajectory &)
G4bool FilterHit (const G4VHit &)
G4bool FilterDigi (const G4VDigi &)
void CreateSceneHandler (const G4String &name="")
void CreateViewer (const G4String &name="", const G4String &XGeometry="")
void Enable ()
void Disable ()
const G4VTrajectoryModel * CurrentTrajDrawModel () const
const std::vector
< UserVisAction > & GetRunDurationUserVisActions () const
const std::vector
< UserVisAction > & GetEndOfEventUserVisActions () const
const std::vector
< UserVisAction > & GetEndOfRunUserVisActions () const
const std::map
< G4VUserVisAction
*, G4VisExtent > & GetUserVisActionExtents () const
G4VGraphicsSystem * GetCurrentGraphicsSystem () const
G4Scene * GetCurrentScene () const
G4VSceneHandler * GetCurrentSceneHandler () const
G4VViewer * GetCurrentViewer () const
const G4GraphicsSystemList & GetAvailableGraphicsSystems ()
const G4SceneHandlerList & GetAvailableSceneHandlers () const
const G4SceneList & GetSceneList () const
G4bool GetTransientsDrawnThisRun () const
G4bool GetTransientsDrawnThisEvent () const
G4bool GetDrawEventOnlyIfToBeKept () const
const G4Event * GetRequestedEvent () const
G4int GetNKeepRequests () const
G4bool GetReviewingKeptEvents () const
G4bool GetAbortReviewKeptEvents () const
const G4ViewParameters & GetDefaultViewParameters () const
void SetCurrentGraphicsSystem (G4VGraphicsSystem *)
void SetCurrentScene (G4Scene *)
void SetCurrentSceneHandler (G4VSceneHandler *)
void SetCurrentViewer (G4VViewer *)
G4SceneHandlerList & SetAvailableSceneHandlers ()
G4SceneList & SetSceneList ()
void SetVerboseLevel (G4int)
void SetVerboseLevel (const G4String &)
void SetVerboseLevel (Verbosity)
void SetEventRefreshing (G4bool)
void ResetTransientsDrawnFlags ()
void SetTransientsDrawnThisRun (G4bool)
void SetTransientsDrawnThisEvent (G4bool)
void SetDrawEventOnlyIfToBeKept (G4bool)
void SetRequestedEvent (const G4Event *)
void SetReviewingKeptEvents (G4bool)
void SetAbortReviewKeptEvents (G4bool)
void SetDefaultViewParameters (const G4ViewParameters &)
G4String ViewerShortName (const G4String &viewerName) const
G4VViewer * GetViewer (const G4String &viewerName) const
Public Member Functions inherited from G4VVisManager
G4VVisManager ()
virtual ~G4VVisManager ()
Static Public Member Functions
static G4VisManager * GetInstance ()
static Verbosity GetVerbosity ()
static Verbosity GetVerbosityValue (const G4String &)
static Verbosity GetVerbosityValue (G4int)
static G4String VerbosityString (Verbosity)
Static Public Member Functions inherited from G4VVisManager
static G4VVisManager * GetConcreteInstance ()
Static Public Attributes
static std::vector< G4String > VerbosityGuidanceStrings
Protected Member Functions
G4VisManager (const G4String &verbosityString="warnings")
virtual void RegisterGraphicsSystems ()=0
virtual void RegisterModelFactories ()
void RegisterMessengers ()
void PrintAvailableGraphicsSystems (Verbosity) const
Protected Attributes
const G4int fVerbose
Private Member Functions
G4VisManager (const G4VisManager &)
G4VisManager & operator= (const G4VisManager &)
void BeginOfRun ()
void BeginOfEvent ()
void EndOfEvent ()
void EndOfRun ()
template<class T >
void DrawT (const T &graphics_primitive, const G4Transform3D &objectTransform)
template<class T >
void DrawT2D (const T &graphics_primitive, const G4Transform3D &objectTransform)
void PrintAvailableModels (Verbosity) const
void InitialiseG4ColourMap () const
void PrintAvailableColours (Verbosity) const
void PrintAvailableUserVisActions (Verbosity) const
void PrintInvalidPointers () const
G4bool IsValidView ()
void ClearTransientStoreIfMarked ()
Private Attributes
G4bool fInitialised
std::vector< UserVisAction > fRunDurationUserVisActions
std::vector< UserVisAction > fEndOfEventUserVisActions
std::vector< UserVisAction > fEndOfRunUserVisActions
std::map< G4VUserVisAction
*, G4VisExtent > fUserVisActionExtents
G4VGraphicsSystem * fpGraphicsSystem
G4Scene * fpScene
G4VSceneHandler * fpSceneHandler
G4VViewer * fpViewer
G4GraphicsSystemList fAvailableGraphicsSystems
G4SceneList fSceneList
G4SceneHandlerList fAvailableSceneHandlers
std::vector< G4UImessenger * > fMessengerList
std::vector< G4UIcommand * > fDirectoryList
G4VisStateDependent * fpStateDependent
G4bool fEventRefreshing
G4bool fTransientsDrawnThisRun
G4bool fTransientsDrawnThisEvent
G4int fNoOfEventsDrawnThisRun
G4int fNKeepRequests
G4bool fEventKeepingSuspended
G4bool fKeptLastEvent
G4bool fDrawEventOnlyIfToBeKept
const G4Event * fpRequestedEvent
G4bool fReviewingKeptEvents
G4bool fAbortReviewKeptEvents
G4ViewParameters fDefaultViewParameters
G4bool fIsDrawGroup
G4int fDrawGroupNestingDepth
G4bool fIgnoreStateChanges
G4VisModelManager
< G4VTrajectoryModel > * fpTrajDrawModelMgr
G4VisFilterManager
< G4VTrajectory > * fpTrajFilterMgr
G4VisFilterManager< G4VHit > * fpHitFilterMgr
G4VisFilterManager< G4VDigi > * fpDigiFilterMgr
Static Private Attributes
static G4VisManager * fpInstance = 0
static Verbosity fVerbosity = G4VisManager::warnings
Friends
class G4VSceneHandler
class G4VViewer
class G4VisStateDependent
class G4VisCommandList
std::ostream & operator<< (std::ostream &, const G4VGraphicsSystem &)
std::ostream & operator<< (std::ostream &, const G4VSceneHandler &)
Additional Inherited Members
Static Protected Member Functions inherited from G4VVisManager
static void SetConcreteInstance (G4VVisManager *)
Static Protected Attributes inherited from G4VVisManager
static G4VVisManager * fpConcreteInstance = 0
Detailed Description
Definition at line 123 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 123 of file G4VisManager.hh
Member Enumeration Documentation
enum G4VisManager::Verbosity
Enumerator:
quiet
startup
errors
warnings
confirmations
parameters
all
Definition at line 137 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 137 of file G4VisManager.hh
Constructor & Destructor Documentation
G4VisManager::G4VisManager (const G4String & verbosityString = "warnings") protected
Definition at line 99 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 99 of file G4VisManager.cc
References FatalException, fDirectoryList, fpDigiFilterMgr, fpHitFilterMgr, fpInstance, fpStateDependent, fpTrajDrawModelMgr, fpTrajFilterMgr, fVerbosity, G4cout, G4endl, G4Exception(), G4VisStateDependent, GetVerbosityValue(), RegisterMessenger(), G4VVisManager::SetConcreteInstance(), G4VVisCommand::SetVisManager(), startup, VerbosityGuidanceStrings, and VerbosityString().
G4VisManager::~G4VisManager () virtual
Definition at line 210 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 210 of file G4VisManager.cc
References fAvailableGraphicsSystems, fAvailableSceneHandlers, fDirectoryList, fMessengerList, fpDigiFilterMgr, fpHitFilterMgr, fpInstance, fpTrajDrawModelMgr, fpTrajFilterMgr, fSceneList, fVerbosity, G4cout, G4endl, and startup.
G4VisManager::G4VisManager (const G4VisManager &) private
Member Function Documentation
void G4VisManager::BeginDraw (const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 815 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 815 of file G4VisManager.cc
References ClearTransientStoreIfMarked(), fDrawGroupNestingDepth, fIsDrawGroup, fpSceneHandler, G4Exception(), IsValidView(), G4Threading::IsWorkerThread(), and JustWarning.
void G4VisManager::BeginDraw2D (const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 852 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 852 of file G4VisManager.cc
References ClearTransientStoreIfMarked(), fDrawGroupNestingDepth, fIsDrawGroup, fpSceneHandler, G4Exception(), IsValidView(), G4Threading::IsWorkerThread(), and JustWarning.
void G4VisManager::BeginOfEvent () private
Definition at line 1959 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1959 of file G4VisManager.cc
References fIgnoreStateChanges, fpSceneHandler, fTransientsDrawnThisEvent, G4VVisManager::GetConcreteInstance(), and G4VSceneHandler::SetTransientsDrawnThisEvent().
void G4VisManager::BeginOfRun () private
Definition at line 1895 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1895 of file G4VisManager.cc
References CurrentTrajDrawModel(), fEventKeepingSuspended, fIgnoreStateChanges, fKeptLastEvent, fNKeepRequests, fNoOfEventsDrawnThisRun, fpSceneHandler, fpViewer, fTransientsDrawnThisRun, G4MUTEXLOCK, G4MUTEXUNLOCK, G4THREADCREATE(), G4MTRunManager::GetMasterRunManager(), G4RunManager::GetNumberOfEventsToBeProcessed(), G4RunManager::GetRunManager(), G4Threading::IsMultithreadedApplication(), G4Threading::IsWorkerThread(), and G4VSceneHandler::SetTransientsDrawnThisRun().
void G4VisManager::ClearTransientStoreIfMarked () private
Definition at line 2337 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2337 of file G4VisManager.cc
References G4VSceneHandler::ClearTransientStore(), fpSceneHandler, fTransientsDrawnThisEvent, fTransientsDrawnThisRun, G4VSceneHandler::GetMarkForClearingTransientStore(), G4VSceneHandler::GetTransientsDrawnThisEvent(), G4VSceneHandler::GetTransientsDrawnThisRun(), and G4VSceneHandler::SetMarkForClearingTransientStore().
Referenced by BeginDraw(), BeginDraw2D(), Draw(), and EndOfEvent().
void G4VisManager::CreateSceneHandler (const G4String & name = "")
Definition at line 1131 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1131 of file G4VisManager.cc
References errors, fAvailableSceneHandlers, fInitialised, fpGraphicsSystem, fpSceneHandler, fVerbosity, G4cout, G4endl, Initialise(), and PrintInvalidPointers().
void G4VisManager::CreateViewer (const G4String & name = "", const G4String & XGeometry = "")
Definition at line 1153 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1153 of file G4VisManager.cc
References G4cerr, G4cout, G4endl, G4ViewParameters::IsCulling(), G4ViewParameters::IsCullingCovered(), G4ViewParameters::IsCullingInvisible(), Dataset::parameters, and G4ViewParameters::SetXGeometryString().
const G4VTrajectoryModel * G4VisManager::CurrentTrajDrawModel () const
Definition at line 744 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 744 of file G4VisManager.cc
References G4VisModelManager< typename >::Current(), fpTrajDrawModelMgr, fVerbosity, G4cout, G4endl, G4VisModelManager< typename >::Register(), and warnings.
Referenced by G4HepRepFileSceneHandler::BeginModeling(), BeginOfRun(), and DispatchToModel().
void G4VisManager::Disable ()
Definition at line 676 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 676 of file G4VisManager.cc
References confirmations, fVerbosity, G4cout, G4endl, G4RunManagerKernel::GetRunManagerKernel(), G4TrackingManager::GetStoreTrajectory(), G4RunManagerKernel::GetTrackingManager(), G4VVisManager::SetConcreteInstance(), and warnings.
Referenced by G4VisCommandEnable::SetNewValue(), and G4VisCommandReviewKeptEvents::SetNewValue().
void G4VisManager::DispatchToModel (const G4VTrajectory & trajectory) virtual
Implements G4VVisManager.
Definition at line 1377 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1377 of file G4VisManager.cc
References CurrentTrajDrawModel(), G4VTrajectoryModel::Draw(), FilterTrajectory(), fpTrajDrawModelMgr, fpTrajFilterMgr, G4VisFilterManager< T >::GetMode(), IsValidView(), FilterMode::Soft, and BlackHoleGeometry::visible.
void G4VisManager::Draw (const G4Circle & circle, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 935 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 935 of file G4VisManager.cc
References DrawT().
Referenced by Draw(), G4VVisCommand::DrawExtent(), CexmcEventAction::DrawReconstructionData(), and CexmcEventAction::DrawTrackPoints().
void G4VisManager::Draw (const G4Polyhedron & polyhedron, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 941 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 941 of file G4VisManager.cc
References DrawT().
void G4VisManager::Draw (const G4Polyline & line, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 947 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 947 of file G4VisManager.cc
References DrawT().
void G4VisManager::Draw (const G4Polymarker & polymarker, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 953 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 953 of file G4VisManager.cc
References DrawT().
void G4VisManager::Draw (const G4Scale & scale, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 959 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 959 of file G4VisManager.cc
References DrawT().
void G4VisManager::Draw (const G4Square & square, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 965 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 965 of file G4VisManager.cc
References DrawT().
void G4VisManager::Draw (const G4Text & text, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 971 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 971 of file G4VisManager.cc
References DrawT().
void G4VisManager::Draw (const G4VTrajectory & traj) virtual
Implements G4VVisManager.
Definition at line 1041 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1041 of file G4VisManager.cc
References ClearTransientStoreIfMarked(), fIsDrawGroup, fpSceneHandler, G4EventManager::GetConstCurrentEvent(), G4RunManager::GetCurrentRun(), G4Event::GetEventID(), G4EventManager::GetEventManager(), G4MTRunManager::GetMasterRunManager(), G4Run::GetRunID(), G4RunManager::GetRunManager(), G4Threading::IsMultithreadedApplication(), IsValidView(), G4Threading::IsWorkerThread(), G4TrajectoriesModel::SetCurrentTrajectory(), G4TrajectoriesModel::SetEventID(), and G4TrajectoriesModel::SetRunID().
void G4VisManager::Draw (const G4VHit & hit) virtual
Implements G4VVisManager.
Definition at line 1013 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1013 of file G4VisManager.cc
References ClearTransientStoreIfMarked(), fIsDrawGroup, fpSceneHandler, IsValidView(), and G4Threading::IsWorkerThread().
void G4VisManager::Draw (const G4VDigi & digi) virtual
Implements G4VVisManager.
Definition at line 1027 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1027 of file G4VisManager.cc
References ClearTransientStoreIfMarked(), fIsDrawGroup, fpSceneHandler, IsValidView(), and G4Threading::IsWorkerThread().
void G4VisManager::Draw (const G4LogicalVolume & logicalVol, const G4VisAttributes & attribs, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 1077 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1077 of file G4VisManager.cc
References Draw(), G4LogicalVolume::GetSolid(), and G4Threading::IsWorkerThread().
void G4VisManager::Draw (const G4VPhysicalVolume & physicalVol, const G4VisAttributes & attribs, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 1108 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1108 of file G4VisManager.cc
References Draw(), G4VPhysicalVolume::GetLogicalVolume(), and G4Threading::IsWorkerThread().
void G4VisManager::Draw (const G4VSolid & solid, const G4VisAttributes & attribs, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 1088 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1088 of file G4VisManager.cc
References ClearTransientStoreIfMarked(), G4VSolid::DescribeYourselfTo(), fIsDrawGroup, fpSceneHandler, IsValidView(), and G4Threading::IsWorkerThread().
void G4VisManager::Draw2D (const G4Circle & circle, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 977 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 977 of file G4VisManager.cc
References DrawT2D().
void G4VisManager::Draw2D (const G4Polyhedron & polyhedron, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 983 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 983 of file G4VisManager.cc
References DrawT2D().
void G4VisManager::Draw2D (const G4Polyline & line, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 989 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 989 of file G4VisManager.cc
References DrawT2D().
void G4VisManager::Draw2D (const G4Polymarker & polymarker, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 995 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 995 of file G4VisManager.cc
References DrawT2D().
void G4VisManager::Draw2D (const G4Square & square, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 1001 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1001 of file G4VisManager.cc
References DrawT2D().
void G4VisManager::Draw2D (const G4Text & text, const G4Transform3D & objectTransformation = G4Transform3D()) virtual
Implements G4VVisManager.
Definition at line 1007 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1007 of file G4VisManager.cc
References DrawT2D().
template<class T > void G4VisManager::DrawT (const T & graphics_primitive, const G4Transform3D & objectTransform) private
Definition at line 890 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 890 of file G4VisManager.cc
References FatalException, G4Exception(), and G4Threading::IsWorkerThread().
Referenced by Draw().
template<class T > void G4VisManager::DrawT2D (const T & graphics_primitive, const G4Transform3D & objectTransform) private
Definition at line 913 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 913 of file G4VisManager.cc
References FatalException, G4Exception(), and G4Threading::IsWorkerThread().
Referenced by Draw2D().
void G4VisManager::Enable ()
Definition at line 648 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 648 of file G4VisManager.cc
References confirmations, fVerbosity, G4cout, G4endl, G4RunManager::GetCurrentRun(), G4Run::GetEventVector(), G4RunManager::GetRunManager(), IsValidView(), G4VVisManager::SetConcreteInstance(), and warnings.
Referenced by G4VisCommandEnable::SetNewValue(), and G4VisCommandReviewKeptEvents::SetNewValue().
void G4VisManager::EndDraw () virtual
Implements G4VVisManager.
Definition at line 836 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 836 of file G4VisManager.cc
References fDrawGroupNestingDepth, fIsDrawGroup, fpSceneHandler, IsValidView(), and G4Threading::IsWorkerThread().
void G4VisManager::EndDraw2D () virtual
Implements G4VVisManager.
Definition at line 873 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 873 of file G4VisManager.cc
References fDrawGroupNestingDepth, fIsDrawGroup, fpSceneHandler, IsValidView(), and G4Threading::IsWorkerThread().
void G4VisManager::EndOfEvent () private
Definition at line 1976 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1976 of file G4VisManager.cc
References ClearTransientStoreIfMarked(), G4VSceneHandler::DrawEvent(), fDrawEventOnlyIfToBeKept, fEventKeepingSuspended, fIgnoreStateChanges, fKeptLastEvent, fNKeepRequests, fNoOfEventsDrawnThisRun, fpScene, fpSceneHandler, fpViewer, fVerbosity, G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, G4THREADSLEEP, G4VVisManager::GetConcreteInstance(), G4EventManager::GetConstCurrentEvent(), G4RunManager::GetCurrentRun(), G4Event::GetEventID(), G4EventManager::GetEventManager(), G4Run::GetEventVector(), G4MTRunManager::GetMasterRunManager(), G4Scene::GetMaxNumberOfKeptEvents(), G4RunManager::GetNumberOfEventsToBeProcessed(), G4Scene::GetRefreshAtEndOfEvent(), G4RunManager::GetRunManager(), G4Threading::IsMultithreadedApplication(), IsValidView(), G4Event::KeepForPostProcessing(), G4EventManager::KeepTheCurrentEvent(), G4VSceneHandler::SetMarkForClearingTransientStore(), G4VViewer::ShowView(), G4Event::ToBeKept(), Acts::IntegrationTest::valid(), and warnings.
void G4VisManager::EndOfRun () private
Definition at line 2187 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2187 of file G4VisManager.cc
References G4VSceneHandler::DrawEndOfRunModels(), fEventKeepingSuspended, fEventRefreshing, fIgnoreStateChanges, G4VGraphicsSystem::fileWriter, fKeptLastEvent, fNKeepRequests, fNoOfEventsDrawnThisRun, fpGraphicsSystem, fpScene, fpSceneHandler, fpViewer, fVerbosity, G4cout, G4endl, G4MUTEXLOCK, G4MUTEXUNLOCK, G4THREADJOIN, G4VVisManager::GetConcreteInstance(), G4RunManager::GetCurrentRun(), G4Run::GetEventVector(), G4VGraphicsSystem::GetFunctionality(), G4MTRunManager::GetMasterRunManager(), G4Scene::GetMaxNumberOfKeptEvents(), G4RunManager::GetNumberOfEventsToBeProcessed(), G4Scene::GetRefreshAtEndOfRun(), G4RunManager::GetRunManager(), G4VViewer::GetViewParameters(), G4ViewParameters::IsAutoRefresh(), G4Threading::IsMultithreadedApplication(), IsValidView(), G4Threading::IsWorkerThread(), G4VViewer::RefreshView(), G4VSceneHandler::SetMarkForClearingTransientStore(), G4VViewer::ShowView(), Acts::IntegrationTest::valid(), and warnings.
G4bool G4VisManager::FilterDigi (const G4VDigi & digi) virtual
Implements G4VVisManager.
Definition at line 1372 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1372 of file G4VisManager.cc
References G4VisFilterManager< T >::Accept(), and fpDigiFilterMgr.
G4bool G4VisManager::FilterHit (const G4VHit & hit) virtual
Implements G4VVisManager.
Definition at line 1367 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1367 of file G4VisManager.cc
References G4VisFilterManager< T >::Accept(), and fpHitFilterMgr.
G4bool G4VisManager::FilterTrajectory (const G4VTrajectory & trajectory) virtual
Implements G4VVisManager.
Definition at line 1362 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1362 of file G4VisManager.cc
References G4VisFilterManager< T >::Accept(), and fpTrajFilterMgr.
Referenced by DispatchToModel().
void G4VisManager::GeometryHasChanged () virtual
Implements G4VVisManager.
Definition at line 1244 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1244 of file G4VisManager.cc
References G4Scene::CalculateExtent(), G4VSceneHandler::ClearStore(), G4VSceneHandler::ClearTransientStore(), G4VViewer::ClearView(), confirmations, G4VViewer::FinishView(), fpScene, fpSceneHandler, fpViewer, fSceneList, fVerbosity, G4cout, G4endl, G4Scene::GetName(), G4TransportationManager::GetTransportationManager(), G4UImanager::GetUIpointer(), G4VViewer::NeedKernelVisit(), G4VViewer::SetView(), and warnings.
G4bool G4VisManager::GetAbortReviewKeptEvents () const
Referenced by G4VisCommandReviewKeptEvents::SetNewValue().
const G4GraphicsSystemList & G4VisManager::GetAvailableGraphicsSystems ()
Definition at line 700 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 700 of file G4VisManager.cc
References fAvailableGraphicsSystems, fVerbosity, G4cout, G4endl, and warnings.
const G4SceneHandlerList& G4VisManager::GetAvailableSceneHandlers () const
G4VGraphicsSystem* G4VisManager::GetCurrentGraphicsSystem () const
Referenced by CexmcEventAction::DrawReconstructionData(), CexmcEventAction::DrawTrackPoints(), CexmcEventAction::DrawTrajectories(), and G4VisCommandDrawTree::SetNewValue().
G4Scene* G4VisManager::GetCurrentScene () const
Referenced by G4RayTracerSceneHandler::G4RayTracerSceneHandler(), CexmcRunManager::RegisterScenePrimitives(), G4VisCommandDrawTree::SetNewValue(), G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandSceneActivateModel::SetNewValue(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandSceneEndOfRunAction::SetNewValue(), G4VisCommandSceneAddDate::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4VisCommandSceneAddDigis::SetNewValue(), G4VisCommandSceneAddEventID::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandSceneAddGPS::SetNewValue(), G4VisCommandSceneAddHits::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandSceneAddLine2D::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddLogo2D::SetNewValue(), G4VisCommandSceneAddMagneticField::SetNewValue(), G4VisCommandSceneAddPSHits::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), G4VisCommandSceneAddText2D::SetNewValue(), G4VisCommandSceneAddTrajectories::SetNewValue(), G4VisCommandSceneAddUserAction::SetNewValue(), and G4VisCommandSceneAddVolume::SetNewValue().
G4VSceneHandler* G4VisManager::GetCurrentSceneHandler () const
Referenced by G4RayTrajectory::AppendStep(), G4VisCommandDrawTree::SetNewValue(), G4VisCommandSceneActivateModel::SetNewValue(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandSceneEndOfRunAction::SetNewValue(), and G4RTSteppingAction::UserSteppingAction().
G4VViewer* G4VisManager::GetCurrentViewer () const
Referenced by G4VisCommandDrawTree::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4RTMessenger::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), G4VisCommandViewerDolly::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), G4VisCommandViewerPan::SetNewValue(), G4VisCommandViewerSave::SetNewValue(), G4VisCommandViewerScale::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandViewerZoom::SetNewValue(), and G4VisCommandSceneAddScale::SetNewValue().
const G4ViewParameters& G4VisManager::GetDefaultViewParameters () const
Referenced by G4VViewer::G4VViewer(), G4VisCommandViewerDefaultHiddenEdge::SetNewValue(), and G4VisCommandViewerDefaultStyle::SetNewValue().
G4bool G4VisManager::GetDrawEventOnlyIfToBeKept () const
Referenced by G4VisCommandDrawOnlyToBeKeptEvents::SetNewValue().
const std::vector<UserVisAction>& G4VisManager::GetEndOfEventUserVisActions () const
Referenced by G4VisCommandSceneAddUserAction::SetNewValue().
const std::vector<UserVisAction>& G4VisManager::GetEndOfRunUserVisActions () const
Referenced by G4VisCommandSceneAddUserAction::SetNewValue().
G4VisManager * G4VisManager::GetInstance (void) static
Definition at line 243 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 243 of file G4VisManager.cc
References FatalException, fpInstance, and G4Exception().
Referenced by G4RayTrajectory::AppendStep(), G4HepRepFileSceneHandler::BeginModeling(), G4RayTracerSceneHandler::BuildVisAttsMap(), G4RayTracerSceneHandler::G4RayTracerSceneHandler(), G4VSceneHandler::G4VSceneHandler(), G4VViewer::G4VViewer(), operator<<(), G4VSceneHandler::ProcessScene(), G4RTMessenger::SetNewValue(), and G4RTSteppingAction::UserSteppingAction().
G4int G4VisManager::GetNKeepRequests () const
const G4Event* G4VisManager::GetRequestedEvent () const
Referenced by G4VSceneHandler::ProcessScene().
G4bool G4VisManager::GetReviewingKeptEvents () const
Referenced by G4VisCommandReviewKeptEvents::SetNewValue().
const std::vector<UserVisAction>& G4VisManager::GetRunDurationUserVisActions () const
Referenced by G4VisCommandSceneAddUserAction::SetNewValue().
const G4SceneList& G4VisManager::GetSceneList () const
G4bool G4VisManager::GetTransientsDrawnThisEvent () const
Referenced by G4VSceneHandler::G4VSceneHandler().
G4bool G4VisManager::GetTransientsDrawnThisRun () const
Referenced by G4VSceneHandler::G4VSceneHandler().
const std::map<G4VUserVisAction*,G4VisExtent>& G4VisManager::GetUserVisActionExtents () const
Referenced by G4VisCommandSceneAddUserAction::AddVisAction().
G4VisManager::Verbosity G4VisManager::GetVerbosity () static
Definition at line 2447 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2447 of file G4VisManager.cc
References fVerbosity.
Referenced by G4GMocrenFileSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::BeginPrimitives(), G4DAWNFILESceneHandler::BeginSavingG4Prim(), G4GMocrenFileSceneHandler::BeginSavingGdd(), G4RayTracerSceneHandler::BuildVisAttsMap(), G4VVisCommand::CheckSceneAndNotifyHandlers(), G4VRML1FileViewer::ClearView(), G4VRML2FileViewer::ClearView(), G4DAWNFILEViewer::ClearView(), G4GMocrenFileViewer::ClearView(), G4VRML2FileSceneHandler::closePort(), G4VRML1FileSceneHandler::closePort(), G4VRML2FileSceneHandler::connectPort(), G4VRML1FileSceneHandler::connectPort(), G4VVisCommand::ConvertToDoublePair(), G4VSceneHandler::CreateModelingParameters(), G4VRML1FileViewer::DrawView(), G4VRML2FileViewer::DrawView(), G4DAWNFILEViewer::DrawView(), G4GMocrenFileViewer::DrawView(), G4GMocrenFileSceneHandler::EndPrimitives(), G4DAWNFILESceneHandler::EndSavingG4Prim(), G4GMocrenFileSceneHandler::EndSavingGdd(), export_G4VisManager(), G4VRML1FileViewer::FinishView(), G4VRML2FileViewer::FinishView(), G4DAWNFILESceneHandler::FRBeginModeling(), G4GMocrenIO::getDetector(), GMocrenDetector::getEdge(), G4GMocrenIO::getShortDoseDist(), GMocrenTrack::getStep(), G4GMocrenIO::getTrack(), G4GMocrenFileSceneHandler::GFBeginModeling(), G4GMocrenFileSceneHandler::GFEndModeling(), G4GMocrenIO::mergeDoseDist(), GMocrenDataPrimitive< T >::operator+(), GMocrenDataPrimitive< T >::operator+=(), G4VSceneHandler::ProcessScene(), G4VVisCommand::RefreshIfRequired(), G4VSceneHandler::RequestPrimitives(), G4GMocrenIO::retrieveData(), G4GMocrenIO::retrieveData2(), G4GMocrenIO::retrieveData3(), G4GMocrenIO::retrieveData4(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4DAWNFILESceneHandler::SetG4PrimFileName(), G4GMocrenFileSceneHandler::SetGddFileName(), G4VisCommandDrawTree::SetNewValue(), G4VisCommandViewerDefaultHiddenEdge::SetNewValue(), G4VisCommandSceneHandlerAttach::SetNewValue(), G4VisCommandSetArrow3DLineSegmentsPerCircle::SetNewValue(), G4VisCommandViewerAddCutawayPlane::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4VisCommandSceneAddArrow::SetNewValue(), G4VisCommandViewerDefaultStyle::SetNewValue(), G4VisCommandSceneHandlerCreate::SetNewValue(), G4VisCommandSceneActivateModel::SetNewValue(), G4VisCommandDrawOnlyToBeKeptEvents::SetNewValue(), G4VisCommandGeometryList::SetNewValue(), G4VisCommandSetColour::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSceneAddArrow2D::SetNewValue(), G4VisCommandGeometryRestore::SetNewValue(), G4VisCommandSceneCreate::SetNewValue(), G4VisCommandSetExtentForField::SetNewValue(), G4VisCommandDrawVolume::SetNewValue(), G4VisCommandViewerChangeCutawayPlane::SetNewValue(), G4VisCommandSceneHandlerSelect::SetNewValue(), G4VisCommandSetLineWidth::SetNewValue(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandOpen::SetNewValue(), G4VisCommandSceneAddAxes::SetNewValue(), G4VisCommandViewerClear::SetNewValue(), G4VisCommandSetTextColour::SetNewValue(), G4VisCommandSpecify::SetNewValue(), G4VisCommandSceneEndOfRunAction::SetNewValue(), G4VisCommandSceneAddDate::SetNewValue(), G4VisCommandViewerClearCutawayPlanes::SetNewValue(), G4VisCommandReviewKeptEvents::SetNewValue(), G4VisCommandSetTextLayout::SetNewValue(), G4VisCommandViewerClearTransients::SetNewValue(), G4VisCommandSetTextSize::SetNewValue(), G4VisCommandSceneNotifyHandlers::SetNewValue(), G4VisCommandViewerClearVisAttributesModifiers::SetNewValue(), G4VisCommandSceneAddDigis::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandSceneSelect::SetNewValue(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandSceneAddEventID::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), G4VisCommandSceneShowExtents::SetNewValue(), G4VisCommandViewerColourByDensity::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), G4VisCommandSceneAddExtent::SetNewValue(), G4VisCommandViewerCreate::SetNewValue(), G4VisCommandViewerDolly::SetNewValue(), G4VisCommandSceneAddFrame::SetNewValue(), G4VisCommandViewerFlush::SetNewValue(), G4VisCommandSceneAddGPS::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), G4VisCommandSceneAddHits::SetNewValue(), G4VisCommandViewerPan::SetNewValue(), G4VisCommandSceneAddLine::SetNewValue(), G4VisCommandViewerReset::SetNewValue(), G4VisCommandViewerRefresh::SetNewValue(), G4VisCommandSceneAddLine2D::SetNewValue(), G4VisCommandViewerRebuild::SetNewValue(), G4VisCommandViewerSave::SetNewValue(), G4VisCommandSceneAddLogicalVolume::SetNewValue(), G4VisCommandViewerScale::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandViewerSelect::SetNewValue(), G4VisCommandSceneAddLogo2D::SetNewValue(), G4VisCommandViewerUpdate::SetNewValue(), G4VisCommandViewerZoom::SetNewValue(), G4VisCommandSceneAddMagneticField::SetNewValue(), G4VisCommandSceneAddPSHits::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), G4VisCommandSceneAddText::SetNewValue(), G4VisCommandSceneAddText2D::SetNewValue(), G4VisCommandSceneAddTrajectories::SetNewValue(), G4VisCommandSceneAddUserAction::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), G4VRML1FileViewer::SetView(), G4DAWNFILEViewer::SetView(), G4VRML2FileViewer::SetView(), G4GMocrenFileViewer::SetView(), G4VRML1FileViewer::ShowView(), G4VRML2FileViewer::ShowView(), G4DAWNFILEViewer::ShowView(), G4GMocrenFileViewer::ShowView(), G4GMocrenIO::storeData3(), G4DAWNFILESceneHandler::~G4DAWNFILESceneHandler(), G4GMocrenFileSceneHandler::~G4GMocrenFileSceneHandler(), G4VRML1FileSceneHandler::~G4VRML1FileSceneHandler(), and G4VRML2FileSceneHandler::~G4VRML2FileSceneHandler().
G4VisManager::Verbosity G4VisManager::GetVerbosityValue (const G4String & verbosityString) static
Definition at line 2408 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2408 of file G4VisManager.cc
References all, confirmations, errors, G4cerr, G4endl, parameters, quiet, startup, G4String::toLower(), VerbosityGuidanceStrings, VerbosityString(), and warnings.
Referenced by G4VisManager(), G4VisCommandSceneHandlerList::SetNewValue(), G4VisCommandList::SetNewValue(), G4VisCommandSceneList::SetNewValue(), G4VisCommandVerbose::SetNewValue(), G4VisCommandViewerList::SetNewValue(), and SetVerboseLevel().
G4VisManager::Verbosity G4VisManager::GetVerbosityValue (G4int intVerbosity) static
Definition at line 2439 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2439 of file G4VisManager.cc
References all, and quiet.
G4VViewer * G4VisManager::GetViewer (const G4String & viewerName) const
Definition at line 2369 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2369 of file G4VisManager.cc
References fAvailableSceneHandlers, and ViewerShortName().
void G4VisManager::IgnoreStateChanges (G4bool val) virtual
Reimplemented from G4VVisManager.
Definition at line 2585 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2585 of file G4VisManager.cc
References fIgnoreStateChanges.
void G4VisManager::Initialise ()
Definition at line 252 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 252 of file G4VisManager.cc
References fDirectoryList, fInitialised, fVerbosity, G4cout, G4endl, InitialiseG4ColourMap(), parameters, PrintAvailableGraphicsSystems(), PrintAvailableModels(), PrintAvailableUserVisActions(), RegisterGraphicsSystems(), RegisterMessengers(), RegisterModelFactories(), startup, and warnings.
Referenced by CreateSceneHandler(), IsValidView(), and main().
void G4VisManager::InitialiseG4ColourMap () const private
Definition at line 367 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 367 of file G4VisManager.cc
References F, G4Colour::InitialiseColourMap(), and TOOLS_COLORS_STAT.
Referenced by Initialise().
void G4VisManager::Initialize ()
Referenced by export_G4VisManager(), PHG4Reco::InitUImanager(), main(), XrayFluoSimulation::RunSimulation(), and G4VisCommandInitialize::SetNewValue().
G4bool G4VisManager::IsValidView () private
Definition at line 2459 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2459 of file G4VisManager.cc
References G4UImanager::ApplyCommand(), errors, fInitialised, fpGraphicsSystem, fpScene, fpSceneHandler, fpViewer, fVerbosity, G4cerr, G4cout, G4endl, G4UImanager::GetUIpointer(), Initialise(), PrintInvalidPointers(), and warnings.
Referenced by BeginDraw(), BeginDraw2D(), DispatchToModel(), Draw(), Enable(), EndDraw(), EndDraw2D(), EndOfEvent(), EndOfRun(), SetCurrentSceneHandler(), and SetCurrentViewer().
void G4VisManager::NotifyHandlers () virtual
Reimplemented from G4VVisManager.
Definition at line 1324 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1324 of file G4VisManager.cc
References G4Scene::CalculateExtent(), G4VSceneHandler::ClearStore(), G4VSceneHandler::ClearTransientStore(), G4VViewer::ClearView(), confirmations, G4VViewer::FinishView(), fpScene, fpSceneHandler, fpViewer, fSceneList, fVerbosity, G4cout, G4endl, G4Scene::GetName(), G4UImanager::GetUIpointer(), G4VViewer::NeedKernelVisit(), G4VViewer::SetView(), and warnings.
G4VisManager& G4VisManager::operator= (const G4VisManager &) private
void G4VisManager::PrintAvailableColours (Verbosity) const private
Definition at line 1733 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1733 of file G4VisManager.cc
References G4cout, G4endl, and G4Colour::GetMap().
Referenced by G4VisCommandList::SetNewValue().
void G4VisManager::PrintAvailableGraphicsSystems (Verbosity verbosity) const protected
Definition at line 1614 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1614 of file G4VisManager.cc
References fAvailableGraphicsSystems, G4cout, G4endl, and warnings.
Referenced by Initialise(), and G4VisCommandList::SetNewValue().
void G4VisManager::PrintAvailableModels (Verbosity verbosity) const private
Definition at line 1642 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1642 of file G4VisManager.cc
References G4VisListManager< T >::Current(), G4VisModelManager< typename >::FactoryList(), G4VisFilterManager< T >::FactoryList(), G4VisFilterManager< T >::FilterList(), fpTrajDrawModelMgr, fpTrajFilterMgr, G4cout, G4endl, G4VisModelManager< typename >::ListManager(), G4VisListManager< T >::Map(), and parameters.
Referenced by Initialise(), and G4VisCommandList::SetNewValue().
void G4VisManager::PrintAvailableUserVisActions (Verbosity) const private
Definition at line 1697 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1697 of file G4VisManager.cc
References fEndOfEventUserVisActions, fEndOfRunUserVisActions, fRunDurationUserVisActions, G4cout, and G4endl.
Referenced by Initialise(), and G4VisCommandList::SetNewValue().
void G4VisManager::PrintInvalidPointers () const private
Definition at line 1746 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1746 of file G4VisManager.cc
References errors, fpGraphicsSystem, fpScene, fpSceneHandler, fpViewer, fVerbosity, G4cerr, and G4endl.
Referenced by CreateSceneHandler(), and IsValidView().
void G4VisManager::RegisterEndOfEventUserVisAction (const G4String & name, G4VUserVisAction * pVisAction, const G4VisExtent & extent = G4VisExtent())
Definition at line 1436 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1436 of file G4VisManager.cc
References G4cout, G4endl, and G4VisExtent::GetExtentRadius().
void G4VisManager::RegisterEndOfRunUserVisAction (const G4String & name, G4VUserVisAction * pVisAction, const G4VisExtent & extent = G4VisExtent())
Definition at line 1457 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1457 of file G4VisManager.cc
References G4cout, G4endl, and G4VisExtent::GetExtentRadius().
G4bool G4VisManager::RegisterGraphicsSystem (G4VGraphicsSystem * pSystem)
Definition at line 720 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 720 of file G4VisManager.cc
References confirmations, errors, fAvailableGraphicsSystems, fVerbosity, G4cout, and G4endl.
Referenced by export_G4VisManager().
virtual void G4VisManager::RegisterGraphicsSystems () protected pure virtual
Implemented in G4VisExecutive, and PyG4VisManager.
Referenced by Initialise().
void G4VisManager::RegisterMessenger (G4UImessenger * messenger)
Referenced by G4VisManager(), and RegisterMessengers().
void G4VisManager::RegisterMessengers () protected
Definition at line 461 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 461 of file G4VisManager.cc
References fDirectoryList, fpDigiFilterMgr, fpHitFilterMgr, fpTrajDrawModelMgr, fpTrajFilterMgr, G4VisModelManager< typename >::Placement(), G4VisFilterManager< T >::Placement(), and RegisterMessenger().
Referenced by Initialise().
void G4VisManager::RegisterModel (G4VTrajectoryModel * model)
Definition at line 766 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 766 of file G4VisManager.cc
References fpTrajDrawModelMgr, and G4VisModelManager< typename >::Register().
void G4VisManager::RegisterModel (G4VFilter< G4VTrajectory > * filter)
Definition at line 777 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 777 of file G4VisManager.cc
References fpTrajFilterMgr, and G4VisFilterManager< T >::Register().
void G4VisManager::RegisterModel (G4VFilter< G4VHit > * filter)
Definition at line 788 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 788 of file G4VisManager.cc
References fpHitFilterMgr, and G4VisFilterManager< T >::Register().
void G4VisManager::RegisterModel (G4VFilter< G4VDigi > * filter)
Definition at line 799 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 799 of file G4VisManager.cc
References fpDigiFilterMgr, and G4VisFilterManager< T >::Register().
void G4VisManager::RegisterModelFactories () protected virtual
Reimplemented in G4VisExecutive, and PyG4VisManager.
Definition at line 2569 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2569 of file G4VisManager.cc
References fVerbosity, G4cout, G4endl, and warnings.
Referenced by Initialise().
void G4VisManager::RegisterModelFactory (G4TrajDrawModelFactory * factory)
Definition at line 772 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 772 of file G4VisManager.cc
References fpTrajDrawModelMgr, and G4VisModelManager< typename >::Register().
void G4VisManager::RegisterModelFactory (G4TrajFilterFactory * factory)
Definition at line 783 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 783 of file G4VisManager.cc
References fpTrajFilterMgr, and G4VisFilterManager< T >::Register().
void G4VisManager::RegisterModelFactory (G4HitFilterFactory * factory)
Definition at line 794 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 794 of file G4VisManager.cc
References fpHitFilterMgr, and G4VisFilterManager< T >::Register().
void G4VisManager::RegisterModelFactory (G4DigiFilterFactory * factory)
Definition at line 805 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 805 of file G4VisManager.cc
References fpDigiFilterMgr, and G4VisFilterManager< T >::Register().
void G4VisManager::RegisterRunDurationUserVisAction (const G4String & name, G4VUserVisAction * pVisAction, const G4VisExtent & extent = G4VisExtent())
Definition at line 1415 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1415 of file G4VisManager.cc
References G4cout, G4endl, and G4VisExtent::GetExtentRadius().
Referenced by main().
void G4VisManager::ResetTransientsDrawnFlags ()
Definition at line 2351 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2351 of file G4VisManager.cc
References fAvailableSceneHandlers, fTransientsDrawnThisEvent, and fTransientsDrawnThisRun.
Referenced by SetCurrentScene(), G4VisCommandSceneEndOfEventAction::SetNewValue(), G4VisCommandSceneEndOfRunAction::SetNewValue(), and G4VisCommandViewerClearTransients::SetNewValue().
void G4VisManager::SelectTrajectoryModel (const G4String & model)
Definition at line 810 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 810 of file G4VisManager.cc
References fpTrajDrawModelMgr, and G4VisModelManager< typename >::SetCurrent().
void G4VisManager::SetAbortReviewKeptEvents (G4bool)
Referenced by G4VisCommandAbortReviewKeptEvents::SetNewValue(), and G4VisCommandReviewKeptEvents::SetNewValue().
G4SceneHandlerList& G4VisManager::SetAvailableSceneHandlers ()
void G4VisManager::SetCurrentGraphicsSystem (G4VGraphicsSystem * pSystem)
Definition at line 1486 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1486 of file G4VisManager.cc
References confirmations, fAvailableSceneHandlers, fpGraphicsSystem, fpScene, fpSceneHandler, fpViewer, fVerbosity, G4cout, and G4endl.
Referenced by G4VisCommandDrawTree::SetNewValue().
void G4VisManager::SetCurrentScene (G4Scene * pScene)
Definition at line 1477 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1477 of file G4VisManager.cc
References fpScene, and ResetTransientsDrawnFlags().
Referenced by G4RayTracerSceneHandler::G4RayTracerSceneHandler(), and G4VisCommandDrawTree::SetNewValue().
void G4VisManager::SetCurrentSceneHandler (G4VSceneHandler * pSceneHandler)
Definition at line 1533 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1533 of file G4VisManager.cc
References confirmations, fpGraphicsSystem, fpScene, fpSceneHandler, fpViewer, fVerbosity, G4cout, G4endl, IsValidView(), and warnings.
Referenced by G4VisCommandDrawTree::SetNewValue().
void G4VisManager::SetCurrentViewer (G4VViewer * pViewer)
Definition at line 1585 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1585 of file G4VisManager.cc
References confirmations, fpGraphicsSystem, fpScene, fpSceneHandler, fpViewer, fVerbosity, G4cout, G4endl, IsValidView(), G4VViewer::SetView(), and warnings.
Referenced by G4VisCommandDrawTree::SetNewValue().
void G4VisManager::SetDefaultViewParameters (const G4ViewParameters &)
Referenced by G4VisCommandViewerDefaultHiddenEdge::SetNewValue(), and G4VisCommandViewerDefaultStyle::SetNewValue().
void G4VisManager::SetDrawEventOnlyIfToBeKept (G4bool)
Referenced by G4VisCommandDrawOnlyToBeKeptEvents::SetNewValue().
void G4VisManager::SetEventRefreshing (G4bool)
Referenced by G4VSceneHandler::ProcessScene().
void G4VisManager::SetRequestedEvent (const G4Event *)
Referenced by G4VisCommandReviewKeptEvents::SetNewValue().
void G4VisManager::SetReviewingKeptEvents (G4bool)
Referenced by G4VisCommandReviewKeptEvents::SetNewValue().
G4SceneList& G4VisManager::SetSceneList ()
Referenced by G4RayTracerSceneHandler::G4RayTracerSceneHandler().
void G4VisManager::SetTransientsDrawnThisEvent (G4bool)
void G4VisManager::SetTransientsDrawnThisRun (G4bool)
void G4VisManager::SetUserAction (G4VUserVisAction * pVisAction, const G4VisExtent & extent = G4VisExtent())
Definition at line 1404 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 1404 of file G4VisManager.cc
References G4cout, and G4endl.
void G4VisManager::SetUserActionExtent (const G4VisExtent &)
void G4VisManager::SetVerboseLevel (G4int intVerbosity)
Definition at line 2451 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2451 of file G4VisManager.cc
References fVerbosity, and GetVerbosityValue().
Referenced by main(), G4VisCommandDrawTree::SetNewValue(), G4VisCommandVerbose::SetNewValue(), and G4VisCommandViewerInterpolate::SetNewValue().
void G4VisManager::SetVerboseLevel (const G4String & verbosityString)
Definition at line 2455 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2455 of file G4VisManager.cc
References fVerbosity, and GetVerbosityValue().
void G4VisManager::SetVerboseLevel (Verbosity)
G4String G4VisManager::VerbosityString (Verbosity verbosity) static
Definition at line 2393 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2393 of file G4VisManager.cc
References all, confirmations, errors, parameters, quiet, startup, and warnings.
Referenced by G4VisManager(), GetVerbosityValue(), and G4VisCommandVerbose::SetNewValue().
G4String G4VisManager::ViewerShortName (const G4String & viewerName) const
Definition at line 2363 of file G4VisManager.cc.
View newest version in sPHENIX GitHub at line 2363 of file G4VisManager.cc
References G4String::strip().
Referenced by GetViewer().
Friends And Related Function Documentation
friend class G4VisCommandList friend
Definition at line 129 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 129 of file G4VisManager.hh
friend class G4VisStateDependent friend
Definition at line 128 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 128 of file G4VisManager.hh
Referenced by G4VisManager().
friend class G4VSceneHandler friend
Definition at line 126 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 126 of file G4VisManager.hh
friend class G4VViewer friend
Definition at line 127 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 127 of file G4VisManager.hh
std::ostream& operator<< (std::ostream & os, const G4VGraphicsSystem & gs) friend
Definition at line 73 of file G4VGraphicsSystem.cc.
View newest version in sPHENIX GitHub at line 73 of file G4VGraphicsSystem.cc
std::ostream& operator<< (std::ostream & os, const G4VSceneHandler & sh) friend
Definition at line 1157 of file G4VSceneHandler.cc.
View newest version in sPHENIX GitHub at line 1157 of file G4VSceneHandler.cc
Member Data Documentation
G4bool G4VisManager::fAbortReviewKeptEvents private
Definition at line 532 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 532 of file G4VisManager.hh
G4GraphicsSystemList G4VisManager::fAvailableGraphicsSystems private
Definition at line 515 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 515 of file G4VisManager.hh
Referenced by GetAvailableGraphicsSystems(), PrintAvailableGraphicsSystems(), RegisterGraphicsSystem(), and ~G4VisManager().
G4SceneHandlerList G4VisManager::fAvailableSceneHandlers private
Definition at line 517 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 517 of file G4VisManager.hh
Referenced by CreateSceneHandler(), GetViewer(), ResetTransientsDrawnFlags(), SetCurrentGraphicsSystem(), and ~G4VisManager().
G4ViewParameters G4VisManager::fDefaultViewParameters private
Definition at line 533 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 533 of file G4VisManager.hh
std::vector<G4UIcommand*> G4VisManager::fDirectoryList private
Definition at line 520 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 520 of file G4VisManager.hh
Referenced by G4VisManager(), Initialise(), RegisterMessengers(), and ~G4VisManager().
G4bool G4VisManager::fDrawEventOnlyIfToBeKept private
Definition at line 529 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 529 of file G4VisManager.hh
Referenced by EndOfEvent().
G4int G4VisManager::fDrawGroupNestingDepth private
Definition at line 535 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 535 of file G4VisManager.hh
Referenced by BeginDraw(), BeginDraw2D(), EndDraw(), and EndDraw2D().
std::vector<UserVisAction> G4VisManager::fEndOfEventUserVisActions private
Definition at line 508 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 508 of file G4VisManager.hh
Referenced by PrintAvailableUserVisActions().
std::vector<UserVisAction> G4VisManager::fEndOfRunUserVisActions private
Definition at line 509 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 509 of file G4VisManager.hh
Referenced by PrintAvailableUserVisActions().
G4bool G4VisManager::fEventKeepingSuspended private
Definition at line 527 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 527 of file G4VisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
G4bool G4VisManager::fEventRefreshing private
Definition at line 522 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 522 of file G4VisManager.hh
Referenced by EndOfRun().
G4bool G4VisManager::fIgnoreStateChanges private
Definition at line 536 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 536 of file G4VisManager.hh
Referenced by BeginOfEvent(), BeginOfRun(), EndOfEvent(), EndOfRun(), and IgnoreStateChanges().
G4bool G4VisManager::fInitialised private
Definition at line 506 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 506 of file G4VisManager.hh
Referenced by CreateSceneHandler(), Initialise(), and IsValidView().
G4bool G4VisManager::fIsDrawGroup private
Definition at line 534 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 534 of file G4VisManager.hh
Referenced by BeginDraw(), BeginDraw2D(), Draw(), EndDraw(), and EndDraw2D().
G4bool G4VisManager::fKeptLastEvent private
Definition at line 528 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 528 of file G4VisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
std::vector<G4UImessenger*> G4VisManager::fMessengerList private
Definition at line 519 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 519 of file G4VisManager.hh
Referenced by ~G4VisManager().
G4int G4VisManager::fNKeepRequests private
Definition at line 526 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 526 of file G4VisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
G4int G4VisManager::fNoOfEventsDrawnThisRun private
Definition at line 525 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 525 of file G4VisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), and EndOfRun().
G4VisFilterManager<G4VDigi>* G4VisManager::fpDigiFilterMgr private
Definition at line 552 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 552 of file G4VisManager.hh
Referenced by FilterDigi(), G4VisManager(), RegisterMessengers(), RegisterModel(), RegisterModelFactory(), and ~G4VisManager().
G4VGraphicsSystem* G4VisManager::fpGraphicsSystem private
Definition at line 511 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 511 of file G4VisManager.hh
Referenced by CreateSceneHandler(), EndOfRun(), IsValidView(), PrintInvalidPointers(), SetCurrentGraphicsSystem(), SetCurrentSceneHandler(), and SetCurrentViewer().
G4VisFilterManager<G4VHit>* G4VisManager::fpHitFilterMgr private
Definition at line 549 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 549 of file G4VisManager.hh
Referenced by FilterHit(), G4VisManager(), RegisterMessengers(), RegisterModel(), RegisterModelFactory(), and ~G4VisManager().
G4VisManager * G4VisManager::fpInstance = 0 static private
Definition at line 505 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 505 of file G4VisManager.hh
Referenced by G4VisManager(), GetInstance(), and ~G4VisManager().
const G4Event* G4VisManager::fpRequestedEvent private
Definition at line 530 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 530 of file G4VisManager.hh
G4Scene* G4VisManager::fpScene private
Definition at line 512 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 512 of file G4VisManager.hh
Referenced by EndOfEvent(), EndOfRun(), GeometryHasChanged(), IsValidView(), NotifyHandlers(), PrintInvalidPointers(), SetCurrentGraphicsSystem(), SetCurrentScene(), SetCurrentSceneHandler(), and SetCurrentViewer().
G4VSceneHandler* G4VisManager::fpSceneHandler private
Definition at line 513 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 513 of file G4VisManager.hh
Referenced by BeginDraw(), BeginDraw2D(), BeginOfEvent(), BeginOfRun(), ClearTransientStoreIfMarked(), CreateSceneHandler(), Draw(), EndDraw(), EndDraw2D(), EndOfEvent(), EndOfRun(), GeometryHasChanged(), IsValidView(), NotifyHandlers(), PrintInvalidPointers(), SetCurrentGraphicsSystem(), SetCurrentSceneHandler(), and SetCurrentViewer().
G4VisStateDependent* G4VisManager::fpStateDependent private
Definition at line 521 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 521 of file G4VisManager.hh
Referenced by G4VisManager().
G4VisModelManager<G4VTrajectoryModel>* G4VisManager::fpTrajDrawModelMgr private
Definition at line 543 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 543 of file G4VisManager.hh
Referenced by CurrentTrajDrawModel(), DispatchToModel(), G4VisManager(), PrintAvailableModels(), RegisterMessengers(), RegisterModel(), RegisterModelFactory(), SelectTrajectoryModel(), and ~G4VisManager().
G4VisFilterManager<G4VTrajectory>* G4VisManager::fpTrajFilterMgr private
Definition at line 546 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 546 of file G4VisManager.hh
Referenced by DispatchToModel(), FilterTrajectory(), G4VisManager(), PrintAvailableModels(), RegisterMessengers(), RegisterModel(), RegisterModelFactory(), and ~G4VisManager().
G4VViewer* G4VisManager::fpViewer private
Definition at line 514 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 514 of file G4VisManager.hh
Referenced by BeginOfRun(), EndOfEvent(), EndOfRun(), GeometryHasChanged(), IsValidView(), NotifyHandlers(), PrintInvalidPointers(), SetCurrentGraphicsSystem(), SetCurrentSceneHandler(), and SetCurrentViewer().
G4bool G4VisManager::fReviewingKeptEvents private
Definition at line 531 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 531 of file G4VisManager.hh
std::vector<UserVisAction> G4VisManager::fRunDurationUserVisActions private
Definition at line 507 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 507 of file G4VisManager.hh
Referenced by PrintAvailableUserVisActions().
G4SceneList G4VisManager::fSceneList private
Definition at line 516 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 516 of file G4VisManager.hh
Referenced by GeometryHasChanged(), NotifyHandlers(), and ~G4VisManager().
G4bool G4VisManager::fTransientsDrawnThisEvent private
Definition at line 524 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 524 of file G4VisManager.hh
Referenced by BeginOfEvent(), ClearTransientStoreIfMarked(), and ResetTransientsDrawnFlags().
G4bool G4VisManager::fTransientsDrawnThisRun private
Definition at line 523 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 523 of file G4VisManager.hh
Referenced by BeginOfRun(), ClearTransientStoreIfMarked(), and ResetTransientsDrawnFlags().
std::map<G4VUserVisAction*,G4VisExtent> G4VisManager::fUserVisActionExtents private
Definition at line 510 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 510 of file G4VisManager.hh
const G4int G4VisManager::fVerbose protected
Definition at line 477 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 477 of file G4VisManager.hh
G4VisManager::Verbosity G4VisManager::fVerbosity = G4VisManager::warnings static private
Definition at line 518 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 518 of file G4VisManager.hh
Referenced by CreateSceneHandler(), CurrentTrajDrawModel(), Disable(), Enable(), EndOfEvent(), EndOfRun(), G4VisManager(), GeometryHasChanged(), GetAvailableGraphicsSystems(), GetVerbosity(), Initialise(), IsValidView(), NotifyHandlers(), PrintInvalidPointers(), RegisterGraphicsSystem(), RegisterModelFactories(), SetCurrentGraphicsSystem(), SetCurrentSceneHandler(), SetCurrentViewer(), SetVerboseLevel(), and ~G4VisManager().
std::vector< G4String > G4VisManager::VerbosityGuidanceStrings static
Definition at line 463 of file G4VisManager.hh.
View newest version in sPHENIX GitHub at line 463 of file G4VisManager.hh
Referenced by G4VisCommandVerbose::G4VisCommandVerbose(), G4VisManager(), and GetVerbosityValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisManager.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisManager.cc