ECCE @ EIC Software: G4MSSteppingAction Class Reference
G4MSSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4MSSteppingAction.hh>
Public Member Functions
G4MSSteppingAction ()
virtual ~G4MSSteppingAction ()
void Initialize (G4bool rSens, G4Region *reg)
virtual void UserSteppingAction (const G4Step *)
G4double GetTotalStepLength () const
G4double GetX0 () const
G4double GetLambda0 () const
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
G4bool regionSensitive
G4Region * theRegion
G4double length
G4double x0
G4double lambda
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 46 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file G4MSSteppingAction.hh
Constructor & Destructor Documentation
G4MSSteppingAction::G4MSSteppingAction ()
Definition at line 40 of file G4MSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 40 of file G4MSSteppingAction.cc
References Initialize().
G4MSSteppingAction::~G4MSSteppingAction () virtual
Definition at line 45 of file G4MSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 45 of file G4MSSteppingAction.cc
Member Function Documentation
G4double G4MSSteppingAction::GetLambda0 () const inline
Definition at line 65 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file G4MSSteppingAction.hh
References lambda.
Referenced by G4MaterialScanner::DoScan().
G4double G4MSSteppingAction::GetTotalStepLength () const inline
Definition at line 63 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file G4MSSteppingAction.hh
References length.
Referenced by G4MaterialScanner::DoScan().
G4double G4MSSteppingAction::GetX0 () const inline
Definition at line 64 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file G4MSSteppingAction.hh
References x0.
Referenced by G4MaterialScanner::DoScan().
void G4MSSteppingAction::Initialize (G4bool rSens, G4Region * reg)
Definition at line 48 of file G4MSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file G4MSSteppingAction.cc
References lambda, length, reg, regionSensitive, theRegion, and x0.
Referenced by G4MaterialScanner::DoScan(), and G4MSSteppingAction().
void G4MSSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 57 of file G4MSSteppingAction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4MSSteppingAction.cc
References G4VPhysicalVolume::GetLogicalVolume(), G4StepPoint::GetMaterial(), G4Material::GetNuclearInterLength(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), G4Material::GetRadlen(), G4LogicalVolume::GetRegion(), G4Step::GetStepLength(), lambda, length, material(), regionSensitive, theRegion, and x0.
Member Data Documentation
G4double G4MSSteppingAction::lambda private
Definition at line 60 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file G4MSSteppingAction.hh
Referenced by GetLambda0(), Initialize(), and UserSteppingAction().
G4double G4MSSteppingAction::length private
Definition at line 58 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file G4MSSteppingAction.hh
Referenced by GetTotalStepLength(), Initialize(), and UserSteppingAction().
G4bool G4MSSteppingAction::regionSensitive private
Definition at line 56 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file G4MSSteppingAction.hh
Referenced by Initialize(), and UserSteppingAction().
G4Region* G4MSSteppingAction::theRegion private
Definition at line 57 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file G4MSSteppingAction.hh
Referenced by Initialize(), and UserSteppingAction().
G4double G4MSSteppingAction::x0 private
Definition at line 59 of file G4MSSteppingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file G4MSSteppingAction.hh
Referenced by GetX0(), Initialize(), and UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4MSSteppingAction.hh
geant4/tree/geant4-10.6-release/source/run/src/G4MSSteppingAction.cc