ECCE @ EIC Software: CexmcEnergyDepositDigitizer Class Reference
CexmcEnergyDepositDigitizer Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcEnergyDepositDigitizer.hh>
Public Member Functions
CexmcEnergyDepositDigitizer (const G4String &name)
~CexmcEnergyDepositDigitizer ()
void Digitize (void)
G4double GetMonitorED (void) const
G4double GetVetoCounterEDLeft (void) const
G4double GetVetoCounterEDRight (void) const
G4double GetCalorimeterEDLeft (void) const
G4double GetCalorimeterEDRight (void) const
G4int GetCalorimeterEDLeftMaxX (void) const
G4int GetCalorimeterEDLeftMaxY (void) const
G4int GetCalorimeterEDRightMaxX (void) const
G4int GetCalorimeterEDRightMaxY (void) const
const
CexmcEnergyDepositCalorimeterCollection & GetCalorimeterEDLeftCollection (void) const
const
CexmcEnergyDepositCalorimeterCollection & GetCalorimeterEDRightCollection (void) const
G4bool MonitorHasTriggered (void) const
G4bool HasTriggered (void) const
void SetMonitorThreshold (G4double value, G4bool fromMessenger=true)
void SetVetoCounterLeftThreshold (G4double value, G4bool fromMessenger=true)
void SetVetoCounterRightThreshold (G4double value, G4bool fromMessenger=true)
void SetVetoCountersThreshold (G4double value)
void SetCalorimeterLeftThreshold (G4double value, G4bool fromMessenger=true)
void SetCalorimeterRightThreshold (G4double value, G4bool fromMessenger=true)
void SetCalorimetersThreshold (G4double value)
void SetCalorimeterTriggerAlgorithm (CexmcCalorimeterTriggerAlgorithm value, G4bool fromMessenger=true)
void SetOuterCrystalsVetoAlgorithm (CexmcOuterCrystalsVetoAlgorithm value, G4bool fromMessenger=true)
void SetOuterCrystalsVetoFraction (G4double value, G4bool fromMessenger=true)
void ApplyFiniteCrystalResolution (G4bool value, G4bool fromMessenger=true)
void AddCrystalResolutionRange (G4double bottom, G4double top, G4double value, G4bool fromMessenger=true)
void ClearCrystalResolutionData (G4bool fromMessenger=true)
void SetCrystalResolutionData (const CexmcEnergyRangeWithDoubleValueList &data)
G4double GetMonitorThreshold (void) const
G4double GetVetoCounterLeftThreshold (void) const
G4double GetVetoCounterRightThreshold (void) const
G4double GetCalorimeterLeftThreshold (void) const
G4double GetCalorimeterRightThreshold (void) const
CexmcCalorimeterTriggerAlgorithm GetCalorimeterTriggerAlgorithm (void) const
CexmcOuterCrystalsVetoAlgorithm GetOuterCrystalsVetoAlgorithm (void) const
G4double GetOuterCrystalsVetoFraction (void) const
G4bool IsFiniteCrystalResolutionApplied (void) const
const
CexmcEnergyRangeWithDoubleValueList & GetCrystalResolutionData (void) const
G4bool IsOuterCrystal (G4int column, G4int row) const
Public Member Functions inherited from G4VDigitizerModule
G4VDigitizerModule (const G4String &modName)
virtual ~G4VDigitizerModule ()
G4bool operator== (const G4VDigitizerModule &right) const
G4bool operator!= (const G4VDigitizerModule &right) const
G4int GetNumberOfCollections () const
G4String GetCollectionName (G4int i) const
G4String GetName () const
void SetVerboseLevel (G4int val)
Private Member Functions
void InitializeData (void)
Private Attributes
G4double monitorED
G4double vetoCounterEDLeft
G4double vetoCounterEDRight
CexmcEnergyDepositCalorimeterCollection calorimeterEDLeftCollection
CexmcEnergyDepositCalorimeterCollection calorimeterEDRightCollection
G4double calorimeterEDLeft
G4double calorimeterEDRight
G4int calorimeterEDLeftMaxX
G4int calorimeterEDLeftMaxY
G4int calorimeterEDRightMaxX
G4int calorimeterEDRightMaxY
G4bool monitorHasTriggered
G4bool hasTriggered
G4double monitorEDThreshold
G4double vetoCounterEDLeftThreshold
G4double vetoCounterEDRightThreshold
G4double calorimeterEDLeftThreshold
G4double calorimeterEDRightThreshold
CexmcCalorimeterTriggerAlgorithm calorimeterTriggerAlgorithm
CexmcOuterCrystalsVetoAlgorithm outerCrystalsVetoAlgorithm
G4double outerCrystalsVetoFraction
G4double monitorEDThresholdRef
G4double vetoCounterEDLeftThresholdRef
G4double vetoCounterEDRightThresholdRef
G4double calorimeterEDLeftThresholdRef
G4double calorimeterEDRightThresholdRef
CexmcCalorimeterTriggerAlgorithm calorimeterTriggerAlgorithmRef
CexmcOuterCrystalsVetoAlgorithm outerCrystalsVetoAlgorithmRef
G4double outerCrystalsVetoFractionRef
G4int nCrystalsInColumn
G4int nCrystalsInRow
G4bool applyFiniteCrystalResolution
CexmcEnergyRangeWithDoubleValueList crystalResolutionData
CexmcEnergyDepositDigitizerMessenger * messenger
Additional Inherited Members
Protected Member Functions inherited from G4VDigitizerModule
void StoreDigiCollection (G4VDigiCollection *aDC)
void StoreDigiCollection (G4int DCID, G4VDigiCollection *aDC)
Protected Attributes inherited from G4VDigitizerModule
G4DigiManager * DigiManager
G4String moduleName
std::vector< G4String > collectionName
G4int verboseLevel
Detailed Description
Definition at line 59 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 59 of file CexmcEnergyDepositDigitizer.hh
Constructor & Destructor Documentation
CexmcEnergyDepositDigitizer::CexmcEnergyDepositDigitizer (const G4String & name) explicit
Definition at line 59 of file CexmcEnergyDepositDigitizer.cc.
View newest version in sPHENIX GitHub at line 59 of file CexmcEnergyDepositDigitizer.cc
References calorimeterEDLeftCollection, calorimeterEDRightCollection, CexmcSetup::GetCalorimeterGeometry(), G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), k, messenger, nCrystalsInColumn, and nCrystalsInRow.
CexmcEnergyDepositDigitizer::~CexmcEnergyDepositDigitizer ()
Definition at line 116 of file CexmcEnergyDepositDigitizer.cc.
View newest version in sPHENIX GitHub at line 116 of file CexmcEnergyDepositDigitizer.cc
References messenger.
Member Function Documentation
void CexmcEnergyDepositDigitizer::AddCrystalResolutionRange (G4double bottom, G4double top, G4double value, G4bool fromMessenger = true) inline
Definition at line 473 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 473 of file CexmcEnergyDepositDigitizer.hh
References CexmcCmdIsNotAllowed, crystalResolutionData, GeV, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::ApplyFiniteCrystalResolution (G4bool value, G4bool fromMessenger = true) inline
Definition at line 463 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 463 of file CexmcEnergyDepositDigitizer.hh
References applyFiniteCrystalResolution, CexmcCmdIsNotAllowed, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::ClearCrystalResolutionData (G4bool fromMessenger = true) inline
Definition at line 486 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 486 of file CexmcEnergyDepositDigitizer.hh
References CexmcCmdIsNotAllowed, crystalResolutionData, and ThrowExceptionIfProjectIsRead().
Referenced by SetCrystalResolutionData(), and CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::Digitize (void) virtual
Implements G4VDigitizerModule.
Definition at line 159 of file CexmcEnergyDepositDigitizer.cc.
View newest version in sPHENIX GitHub at line 159 of file CexmcEnergyDepositDigitizer.cc
References applyFiniteCrystalResolution, calorimeterEDLeft, calorimeterEDLeftCollection, calorimeterEDLeftMaxX, calorimeterEDLeftMaxY, calorimeterEDLeftThreshold, calorimeterEDRight, calorimeterEDRightCollection, calorimeterEDRightMaxX, calorimeterEDRightMaxY, calorimeterEDRightThreshold, calorimeterTriggerAlgorithm, CexmcCalorimeterDetectorRole, CexmcDetectorRoleName, CexmcDetectorTypeName, CexmcEDDetector, CexmcFractionOfEDInOuterCrystalsVeto, CexmcFwhmToStddev(), CexmcInnerCrystalsMakeEDTriggerThreshold, CexmcLeft, CexmcMaximumEDInASingleOuterCrystalVeto, CexmcMonitorDetectorRole, CexmcNoOuterCrystalsVeto, CexmcRight, CexmcVetoCounterDetectorRole, crystalResolutionData, CexmcEnergyDepositInCalorimeter::GetColumn(), G4DigiManager::GetDMpointer(), G4DigiManager::GetHitsCollection(), G4DigiManager::GetHitsCollectionID(), CexmcEnergyDepositInCalorimeter::GetRow(), G4RunManager::GetRunManager(), CexmcEnergyDepositInLeftRightSet::GetSide(), hasTriggered, InitializeData(), IsOuterCrystal(), k, monitorED, monitorEDThreshold, monitorHasTriggered, outerCrystalsVetoAlgorithm, outerCrystalsVetoFraction, CexmcRunManager::ProjectIsRead(), G4INCL::DeJongSpin::shoot(), vetoCounterEDLeft, vetoCounterEDLeftThreshold, vetoCounterEDRight, and vetoCounterEDRightThreshold.
Referenced by CexmcEventAction::EndOfEventAction().
G4double CexmcEnergyDepositDigitizer::GetCalorimeterEDLeft (void) const inline
Definition at line 265 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 265 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDLeft.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
const CexmcEnergyDepositCalorimeterCollection & CexmcEnergyDepositDigitizer::GetCalorimeterEDLeftCollection (void) const inline
Definition at line 307 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 307 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDLeftCollection.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4int CexmcEnergyDepositDigitizer::GetCalorimeterEDLeftMaxX (void) const inline
Definition at line 278 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 278 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDLeftMaxX.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4int CexmcEnergyDepositDigitizer::GetCalorimeterEDLeftMaxY (void) const inline
Definition at line 285 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 285 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDLeftMaxY.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4double CexmcEnergyDepositDigitizer::GetCalorimeterEDRight (void) const inline
Definition at line 271 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 271 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDRight.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
const CexmcEnergyDepositCalorimeterCollection & CexmcEnergyDepositDigitizer::GetCalorimeterEDRightCollection (void) const inline
Definition at line 314 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 314 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDRightCollection.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4int CexmcEnergyDepositDigitizer::GetCalorimeterEDRightMaxX (void) const inline
Definition at line 292 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 292 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDRightMaxX.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4int CexmcEnergyDepositDigitizer::GetCalorimeterEDRightMaxY (void) const inline
Definition at line 299 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 299 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDRightMaxY.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4double CexmcEnergyDepositDigitizer::GetCalorimeterLeftThreshold (void) const inline
Definition at line 532 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 532 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDLeftThreshold.
G4double CexmcEnergyDepositDigitizer::GetCalorimeterRightThreshold (void) const inline
Definition at line 539 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 539 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDRightThreshold.
CexmcCalorimeterTriggerAlgorithm CexmcEnergyDepositDigitizer::GetCalorimeterTriggerAlgorithm (void) const inline
Definition at line 547 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 547 of file CexmcEnergyDepositDigitizer.hh
References calorimeterTriggerAlgorithm.
const CexmcEnergyRangeWithDoubleValueList & CexmcEnergyDepositDigitizer::GetCrystalResolutionData (void) const inline
Definition at line 577 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 577 of file CexmcEnergyDepositDigitizer.hh
References crystalResolutionData.
G4double CexmcEnergyDepositDigitizer::GetMonitorED (void) const inline
Definition at line 246 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 246 of file CexmcEnergyDepositDigitizer.hh
References monitorED.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4double CexmcEnergyDepositDigitizer::GetMonitorThreshold (void) const inline
Definition at line 512 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 512 of file CexmcEnergyDepositDigitizer.hh
References monitorEDThreshold.
CexmcOuterCrystalsVetoAlgorithm CexmcEnergyDepositDigitizer::GetOuterCrystalsVetoAlgorithm (void) const inline
Definition at line 555 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 555 of file CexmcEnergyDepositDigitizer.hh
References outerCrystalsVetoAlgorithm.
G4double CexmcEnergyDepositDigitizer::GetOuterCrystalsVetoFraction (void) const inline
Definition at line 562 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 562 of file CexmcEnergyDepositDigitizer.hh
References outerCrystalsVetoFraction.
G4double CexmcEnergyDepositDigitizer::GetVetoCounterEDLeft (void) const inline
Definition at line 252 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 252 of file CexmcEnergyDepositDigitizer.hh
References vetoCounterEDLeft.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4double CexmcEnergyDepositDigitizer::GetVetoCounterEDRight (void) const inline
Definition at line 258 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 258 of file CexmcEnergyDepositDigitizer.hh
References vetoCounterEDRight.
Referenced by CexmcEventAction::MakeEnergyDepositStore().
G4double CexmcEnergyDepositDigitizer::GetVetoCounterLeftThreshold (void) const inline
Definition at line 518 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 518 of file CexmcEnergyDepositDigitizer.hh
References vetoCounterEDLeftThreshold.
G4double CexmcEnergyDepositDigitizer::GetVetoCounterRightThreshold (void) const inline
Definition at line 525 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 525 of file CexmcEnergyDepositDigitizer.hh
References vetoCounterEDRightThreshold.
G4bool CexmcEnergyDepositDigitizer::HasTriggered (void) const inline
Definition at line 326 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 326 of file CexmcEnergyDepositDigitizer.hh
References hasTriggered.
Referenced by CexmcEventAction::EndOfEventAction().
void CexmcEnergyDepositDigitizer::InitializeData (void) private
Definition at line 122 of file CexmcEnergyDepositDigitizer.cc.
View newest version in sPHENIX GitHub at line 122 of file CexmcEnergyDepositDigitizer.cc
References calorimeterEDLeft, calorimeterEDLeftCollection, calorimeterEDLeftMaxX, calorimeterEDLeftMaxY, calorimeterEDRight, calorimeterEDRightCollection, calorimeterEDRightMaxX, calorimeterEDRightMaxY, hasTriggered, k, monitorED, monitorHasTriggered, vetoCounterEDLeft, and vetoCounterEDRight.
Referenced by Digitize().
G4bool CexmcEnergyDepositDigitizer::IsFiniteCrystalResolutionApplied (void) const inline
Definition at line 569 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 569 of file CexmcEnergyDepositDigitizer.hh
References applyFiniteCrystalResolution.
G4bool CexmcEnergyDepositDigitizer::IsOuterCrystal (G4int column, G4int row) const inline
Definition at line 504 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 504 of file CexmcEnergyDepositDigitizer.hh
References nCrystalsInColumn, and nCrystalsInRow.
Referenced by Digitize().
G4bool CexmcEnergyDepositDigitizer::MonitorHasTriggered (void) const inline
Definition at line 320 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 320 of file CexmcEnergyDepositDigitizer.hh
References monitorHasTriggered.
Referenced by CexmcEventAction::EndOfEventAction().
void CexmcEnergyDepositDigitizer::SetCalorimeterLeftThreshold (G4double value, G4bool fromMessenger = true) inline
Definition at line 383 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 383 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDLeftThreshold, calorimeterEDLeftThresholdRef, CexmcBadThreshold, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetCalorimeterRightThreshold (G4double value, G4bool fromMessenger = true) inline
Definition at line 396 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 396 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDRightThreshold, calorimeterEDRightThresholdRef, CexmcBadThreshold, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetCalorimetersThreshold (G4double value) inline
Definition at line 409 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 409 of file CexmcEnergyDepositDigitizer.hh
References calorimeterEDLeftThreshold, calorimeterEDLeftThresholdRef, calorimeterEDRightThreshold, calorimeterEDRightThresholdRef, CexmcBadThreshold, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetCalorimeterTriggerAlgorithm (CexmcCalorimeterTriggerAlgorithm value, G4bool fromMessenger = true) inline
Definition at line 421 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 421 of file CexmcEnergyDepositDigitizer.hh
References calorimeterTriggerAlgorithm, calorimeterTriggerAlgorithmRef, CexmcAllCrystalsMakeEDTriggerThreshold, CexmcBadCalorimeterTriggerAlgorithm, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetCrystalResolutionData (const CexmcEnergyRangeWithDoubleValueList & data) inline
Definition at line 496 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 496 of file CexmcEnergyDepositDigitizer.hh
References ClearCrystalResolutionData(), and crystalResolutionData.
void CexmcEnergyDepositDigitizer::SetMonitorThreshold (G4double value, G4bool fromMessenger = true) inline
Definition at line 332 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 332 of file CexmcEnergyDepositDigitizer.hh
References CexmcBadThreshold, monitorEDThreshold, monitorEDThresholdRef, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetOuterCrystalsVetoAlgorithm (CexmcOuterCrystalsVetoAlgorithm value, G4bool fromMessenger = true) inline
Definition at line 436 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 436 of file CexmcEnergyDepositDigitizer.hh
References CexmcBadOCVetoAlgorithm, CexmcNoOuterCrystalsVeto, outerCrystalsVetoAlgorithm, outerCrystalsVetoAlgorithmRef, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetOuterCrystalsVetoFraction (G4double value, G4bool fromMessenger = true) inline
Definition at line 450 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 450 of file CexmcEnergyDepositDigitizer.hh
References CexmcBadOCVetoFraction, outerCrystalsVetoFraction, outerCrystalsVetoFractionRef, and ThrowExceptionIfProjectIsRead().
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetVetoCounterLeftThreshold (G4double value, G4bool fromMessenger = true) inline
Definition at line 345 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 345 of file CexmcEnergyDepositDigitizer.hh
References CexmcBadThreshold, ThrowExceptionIfProjectIsRead(), vetoCounterEDLeftThreshold, and vetoCounterEDLeftThresholdRef.
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetVetoCounterRightThreshold (G4double value, G4bool fromMessenger = true) inline
Definition at line 358 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 358 of file CexmcEnergyDepositDigitizer.hh
References CexmcBadThreshold, ThrowExceptionIfProjectIsRead(), vetoCounterEDRightThreshold, and vetoCounterEDRightThresholdRef.
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
void CexmcEnergyDepositDigitizer::SetVetoCountersThreshold (G4double value) inline
Definition at line 371 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 371 of file CexmcEnergyDepositDigitizer.hh
References CexmcBadThreshold, ThrowExceptionIfProjectIsRead(), vetoCounterEDLeftThreshold, vetoCounterEDLeftThresholdRef, vetoCounterEDRightThreshold, and vetoCounterEDRightThresholdRef.
Referenced by CexmcEnergyDepositDigitizerMessenger::SetNewValue().
Member Data Documentation
G4bool CexmcEnergyDepositDigitizer::applyFiniteCrystalResolution private
Definition at line 237 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 237 of file CexmcEnergyDepositDigitizer.hh
Referenced by ApplyFiniteCrystalResolution(), Digitize(), and IsFiniteCrystalResolutionApplied().
G4double CexmcEnergyDepositDigitizer::calorimeterEDLeft private
Definition at line 182 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 182 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterEDLeft(), and InitializeData().
CexmcEnergyDepositCalorimeterCollection CexmcEnergyDepositDigitizer::calorimeterEDLeftCollection private
Definition at line 178 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 178 of file CexmcEnergyDepositDigitizer.hh
Referenced by CexmcEnergyDepositDigitizer(), Digitize(), GetCalorimeterEDLeftCollection(), and InitializeData().
G4int CexmcEnergyDepositDigitizer::calorimeterEDLeftMaxX private
Definition at line 186 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 186 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterEDLeftMaxX(), and InitializeData().
G4int CexmcEnergyDepositDigitizer::calorimeterEDLeftMaxY private
Definition at line 188 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 188 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterEDLeftMaxY(), and InitializeData().
G4double CexmcEnergyDepositDigitizer::calorimeterEDLeftThreshold private
Definition at line 205 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 205 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterLeftThreshold(), SetCalorimeterLeftThreshold(), and SetCalorimetersThreshold().
G4double CexmcEnergyDepositDigitizer::calorimeterEDLeftThresholdRef private
Definition at line 221 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 221 of file CexmcEnergyDepositDigitizer.hh
Referenced by SetCalorimeterLeftThreshold(), and SetCalorimetersThreshold().
G4double CexmcEnergyDepositDigitizer::calorimeterEDRight private
Definition at line 184 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 184 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterEDRight(), and InitializeData().
CexmcEnergyDepositCalorimeterCollection CexmcEnergyDepositDigitizer::calorimeterEDRightCollection private
Definition at line 180 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 180 of file CexmcEnergyDepositDigitizer.hh
Referenced by CexmcEnergyDepositDigitizer(), Digitize(), GetCalorimeterEDRightCollection(), and InitializeData().
G4int CexmcEnergyDepositDigitizer::calorimeterEDRightMaxX private
Definition at line 190 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 190 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterEDRightMaxX(), and InitializeData().
G4int CexmcEnergyDepositDigitizer::calorimeterEDRightMaxY private
Definition at line 192 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 192 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterEDRightMaxY(), and InitializeData().
G4double CexmcEnergyDepositDigitizer::calorimeterEDRightThreshold private
Definition at line 207 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 207 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterRightThreshold(), SetCalorimeterRightThreshold(), and SetCalorimetersThreshold().
G4double CexmcEnergyDepositDigitizer::calorimeterEDRightThresholdRef private
Definition at line 223 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 223 of file CexmcEnergyDepositDigitizer.hh
Referenced by SetCalorimeterRightThreshold(), and SetCalorimetersThreshold().
CexmcCalorimeterTriggerAlgorithm CexmcEnergyDepositDigitizer::calorimeterTriggerAlgorithm private
Definition at line 209 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 209 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetCalorimeterTriggerAlgorithm(), and SetCalorimeterTriggerAlgorithm().
CexmcCalorimeterTriggerAlgorithm CexmcEnergyDepositDigitizer::calorimeterTriggerAlgorithmRef private
Definition at line 225 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 225 of file CexmcEnergyDepositDigitizer.hh
Referenced by SetCalorimeterTriggerAlgorithm().
CexmcEnergyRangeWithDoubleValueList CexmcEnergyDepositDigitizer::crystalResolutionData private
Definition at line 239 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 239 of file CexmcEnergyDepositDigitizer.hh
Referenced by AddCrystalResolutionRange(), ClearCrystalResolutionData(), Digitize(), GetCrystalResolutionData(), and SetCrystalResolutionData().
G4bool CexmcEnergyDepositDigitizer::hasTriggered private
Definition at line 196 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 196 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), HasTriggered(), and InitializeData().
CexmcEnergyDepositDigitizerMessenger* CexmcEnergyDepositDigitizer::messenger private
Definition at line 242 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 242 of file CexmcEnergyDepositDigitizer.hh
Referenced by CexmcEnergyDepositDigitizer(), and ~CexmcEnergyDepositDigitizer().
G4double CexmcEnergyDepositDigitizer::monitorED private
Definition at line 172 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 172 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetMonitorED(), and InitializeData().
G4double CexmcEnergyDepositDigitizer::monitorEDThreshold private
Definition at line 199 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 199 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetMonitorThreshold(), and SetMonitorThreshold().
G4double CexmcEnergyDepositDigitizer::monitorEDThresholdRef private
Definition at line 215 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 215 of file CexmcEnergyDepositDigitizer.hh
Referenced by SetMonitorThreshold().
G4bool CexmcEnergyDepositDigitizer::monitorHasTriggered private
Definition at line 194 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 194 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), InitializeData(), and MonitorHasTriggered().
G4int CexmcEnergyDepositDigitizer::nCrystalsInColumn private
Definition at line 232 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 232 of file CexmcEnergyDepositDigitizer.hh
Referenced by CexmcEnergyDepositDigitizer(), and IsOuterCrystal().
G4int CexmcEnergyDepositDigitizer::nCrystalsInRow private
Definition at line 234 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 234 of file CexmcEnergyDepositDigitizer.hh
Referenced by CexmcEnergyDepositDigitizer(), and IsOuterCrystal().
CexmcOuterCrystalsVetoAlgorithm CexmcEnergyDepositDigitizer::outerCrystalsVetoAlgorithm private
Definition at line 211 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 211 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetOuterCrystalsVetoAlgorithm(), and SetOuterCrystalsVetoAlgorithm().
CexmcOuterCrystalsVetoAlgorithm CexmcEnergyDepositDigitizer::outerCrystalsVetoAlgorithmRef private
Definition at line 227 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 227 of file CexmcEnergyDepositDigitizer.hh
Referenced by SetOuterCrystalsVetoAlgorithm().
G4double CexmcEnergyDepositDigitizer::outerCrystalsVetoFraction private
Definition at line 213 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 213 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetOuterCrystalsVetoFraction(), and SetOuterCrystalsVetoFraction().
G4double CexmcEnergyDepositDigitizer::outerCrystalsVetoFractionRef private
Definition at line 229 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 229 of file CexmcEnergyDepositDigitizer.hh
Referenced by SetOuterCrystalsVetoFraction().
G4double CexmcEnergyDepositDigitizer::vetoCounterEDLeft private
Definition at line 174 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 174 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetVetoCounterEDLeft(), and InitializeData().
G4double CexmcEnergyDepositDigitizer::vetoCounterEDLeftThreshold private
Definition at line 201 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 201 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetVetoCounterLeftThreshold(), SetVetoCounterLeftThreshold(), and SetVetoCountersThreshold().
G4double CexmcEnergyDepositDigitizer::vetoCounterEDLeftThresholdRef private
Definition at line 217 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 217 of file CexmcEnergyDepositDigitizer.hh
Referenced by SetVetoCounterLeftThreshold(), and SetVetoCountersThreshold().
G4double CexmcEnergyDepositDigitizer::vetoCounterEDRight private
Definition at line 176 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 176 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetVetoCounterEDRight(), and InitializeData().
G4double CexmcEnergyDepositDigitizer::vetoCounterEDRightThreshold private
Definition at line 203 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 203 of file CexmcEnergyDepositDigitizer.hh
Referenced by Digitize(), GetVetoCounterRightThreshold(), SetVetoCounterRightThreshold(), and SetVetoCountersThreshold().
G4double CexmcEnergyDepositDigitizer::vetoCounterEDRightThresholdRef private
Definition at line 219 of file CexmcEnergyDepositDigitizer.hh.
View newest version in sPHENIX GitHub at line 219 of file CexmcEnergyDepositDigitizer.hh
Referenced by SetVetoCounterRightThreshold(), and SetVetoCountersThreshold().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcEnergyDepositDigitizer.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcEnergyDepositDigitizer.cc