ECCE @ EIC Software: G4LogicalBorderSurface Class Reference
G4LogicalBorderSurface Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4LogicalBorderSurface.hh>
Public Member Functions
G4LogicalBorderSurface (const G4String &name, G4VPhysicalVolume *vol1, G4VPhysicalVolume *vol2, G4SurfaceProperty *surfaceProperty)
~G4LogicalBorderSurface ()
G4LogicalBorderSurface (const G4LogicalBorderSurface &)=delete
G4LogicalBorderSurface & operator= (const G4LogicalBorderSurface &)=delete
G4bool operator== (const G4LogicalBorderSurface &right) const
G4bool operator!= (const G4LogicalBorderSurface &right) const
void SetPhysicalVolumes (G4VPhysicalVolume *vol1, G4VPhysicalVolume *vol2)
const G4VPhysicalVolume * GetVolume1 () const
const G4VPhysicalVolume * GetVolume2 () const
void SetVolume1 (G4VPhysicalVolume *vol1)
void SetVolume2 (G4VPhysicalVolume *vol2)
Public Member Functions inherited from G4LogicalSurface
G4SurfaceProperty * GetSurfaceProperty () const
void SetSurfaceProperty (G4SurfaceProperty *ptrSurfaceProperty)
const G4String & GetName () const
void SetName (const G4String &name)
G4TransitionRadiationSurface * GetTransitionRadiationSurface () const
void SetTransitionRadiationSurface (G4TransitionRadiationSurface *trs)
virtual ~G4LogicalSurface ()
G4LogicalSurface (const G4LogicalSurface &)=delete
G4LogicalSurface & operator= (const G4LogicalSurface &)=delete
G4bool operator== (const G4LogicalSurface &right) const
G4bool operator!= (const G4LogicalSurface &right) const
Static Public Member Functions
static G4LogicalBorderSurface * GetSurface (const G4VPhysicalVolume *vol1, const G4VPhysicalVolume *vol2)
static void CleanSurfaceTable ()
static const
G4LogicalBorderSurfaceTable * GetSurfaceTable ()
static size_t GetNumberOfBorderSurfaces ()
static void DumpInfo ()
Private Attributes
G4VPhysicalVolume * Volume1
G4VPhysicalVolume * Volume2
Static Private Attributes
static
G4LogicalBorderSurfaceTable * theBorderSurfaceTable = nullptr
Additional Inherited Members
Protected Member Functions inherited from G4LogicalSurface
G4LogicalSurface (const G4String &name, G4SurfaceProperty *prop)
Detailed Description
Definition at line 49 of file G4LogicalBorderSurface.hh.
View newest version in sPHENIX GitHub at line 49 of file G4LogicalBorderSurface.hh
Constructor & Destructor Documentation
G4LogicalBorderSurface::G4LogicalBorderSurface (const G4String & name, G4VPhysicalVolume * vol1, G4VPhysicalVolume * vol2, G4SurfaceProperty * surfaceProperty)
Definition at line 45 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 45 of file G4LogicalBorderSurface.cc
References theBorderSurfaceTable.
G4LogicalBorderSurface::~G4LogicalBorderSurface ()
Definition at line 62 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 62 of file G4LogicalBorderSurface.cc
G4LogicalBorderSurface::G4LogicalBorderSurface (const G4LogicalBorderSurface &) delete
Member Function Documentation
void G4LogicalBorderSurface::CleanSurfaceTable () static
Definition at line 142 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 142 of file G4LogicalBorderSurface.cc
References pos(), and theBorderSurfaceTable.
Referenced by WLSDetectorConstruction::Construct().
void G4LogicalBorderSurface::DumpInfo () static
Definition at line 122 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 122 of file G4LogicalBorderSurface.cc
References G4cout, G4endl, GetNumberOfBorderSurfaces(), pos(), and theBorderSurfaceTable.
size_t G4LogicalBorderSurface::GetNumberOfBorderSurfaces () static
Definition at line 95 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 95 of file G4LogicalBorderSurface.cc
References theBorderSurfaceTable.
Referenced by DumpInfo(), PHG4GDMLWriteStructure::GetBorderSurface(), and G4GDMLWriteStructure::GetBorderSurface().
G4LogicalBorderSurface * G4LogicalBorderSurface::GetSurface (const G4VPhysicalVolume * vol1, const G4VPhysicalVolume * vol2) static
Definition at line 105 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 105 of file G4LogicalBorderSurface.cc
References pos(), and theBorderSurfaceTable.
Referenced by OpNoviceDetectorConstruction::Construct(), and G4OpBoundaryProcess::PostStepDoIt().
const G4LogicalBorderSurfaceTable * G4LogicalBorderSurface::GetSurfaceTable () static
Definition at line 86 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 86 of file G4LogicalBorderSurface.cc
References theBorderSurfaceTable.
Referenced by PHG4GDMLWriteStructure::GetBorderSurface(), and G4GDMLWriteStructure::GetBorderSurface().
const G4VPhysicalVolume* G4LogicalBorderSurface::GetVolume1 () const inline
Referenced by PHG4GDMLWriteStructure::BorderSurfaceCache(), and G4GDMLWriteStructure::BorderSurfaceCache().
const G4VPhysicalVolume* G4LogicalBorderSurface::GetVolume2 () const inline
Referenced by PHG4GDMLWriteStructure::BorderSurfaceCache(), and G4GDMLWriteStructure::BorderSurfaceCache().
G4bool G4LogicalBorderSurface::operator!= (const G4LogicalBorderSurface & right) const
Definition at line 77 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 77 of file G4LogicalBorderSurface.cc
G4LogicalBorderSurface& G4LogicalBorderSurface::operator= (const G4LogicalBorderSurface &) delete
G4bool G4LogicalBorderSurface::operator== (const G4LogicalBorderSurface & right) const
Definition at line 71 of file G4LogicalBorderSurface.cc.
View newest version in sPHENIX GitHub at line 71 of file G4LogicalBorderSurface.cc
void G4LogicalBorderSurface::SetPhysicalVolumes (G4VPhysicalVolume * vol1, G4VPhysicalVolume * vol2) inline
void G4LogicalBorderSurface::SetVolume1 (G4VPhysicalVolume * vol1) inline
void G4LogicalBorderSurface::SetVolume2 (G4VPhysicalVolume * vol2) inline
Member Data Documentation
G4LogicalBorderSurfaceTable * G4LogicalBorderSurface::theBorderSurfaceTable = nullptr static private
Definition at line 92 of file G4LogicalBorderSurface.hh.
View newest version in sPHENIX GitHub at line 92 of file G4LogicalBorderSurface.hh
Referenced by CleanSurfaceTable(), DumpInfo(), G4LogicalBorderSurface(), GetNumberOfBorderSurfaces(), GetSurface(), and GetSurfaceTable().
G4VPhysicalVolume* G4LogicalBorderSurface::Volume1 private
Definition at line 89 of file G4LogicalBorderSurface.hh.
View newest version in sPHENIX GitHub at line 89 of file G4LogicalBorderSurface.hh
G4VPhysicalVolume* G4LogicalBorderSurface::Volume2 private
Definition at line 90 of file G4LogicalBorderSurface.hh.
View newest version in sPHENIX GitHub at line 90 of file G4LogicalBorderSurface.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4LogicalBorderSurface.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4LogicalBorderSurface.cc