ECCE @ EIC Software: CCalSDList Class Reference
CCalSDList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSDList.hh>
Public Member Functions
void addCalo (nameType name)
void addTracker (nameType name)
nameType getCaloSDName (G4int i)
nameType getTrackerSDName (G4int i)
G4int getNumberOfCaloSD ()
G4int getNumberOfTrackerSD ()
Static Public Member Functions
static CCalSDList * getInstance ()
Private Member Functions
CCalSDList ()
~CCalSDList ()
CCalSDList & operator= (CCalSDList &)
Private Attributes
std::vector< nameType > caloSD
std::vector< nameType > trackerSD
Static Private Attributes
static CCalSDList * theList = 0
Detailed Description
Definition at line 40 of file CCalSDList.hh.
View newest version in sPHENIX GitHub at line 40 of file CCalSDList.hh
Constructor & Destructor Documentation
CCalSDList::CCalSDList () private
Definition at line 34 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 34 of file CCalSDList.cc
Referenced by getInstance().
CCalSDList::~CCalSDList () private
Definition at line 35 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 35 of file CCalSDList.cc
References theList.
Member Function Documentation
void CCalSDList::addCalo (nameType name)
Definition at line 44 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 44 of file CCalSDList.cc
References caloSD, and theList.
Referenced by CCaloSD::CCaloSD().
void CCalSDList::addTracker (nameType name)
Definition at line 49 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 49 of file CCalSDList.cc
References theList, and trackerSD.
nameType CCalSDList::getCaloSDName (G4int i)
Definition at line 54 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 54 of file CCalSDList.cc
References caloSD, G4cout, G4endl, getNumberOfCaloSD(), and theList.
CCalSDList * CCalSDList::getInstance () static
Definition at line 37 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 37 of file CCalSDList.cc
References CCalSDList(), and theList.
Referenced by CCaloSD::CCaloSD(), CCalEventAction::initialize(), and CCalStackingAction::initialize().
G4int CCalSDList::getNumberOfCaloSD ()
Definition at line 76 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 76 of file CCalSDList.cc
References caloSD, and theList.
Referenced by getCaloSDName(), CCalEventAction::initialize(), and CCalStackingAction::initialize().
G4int CCalSDList::getNumberOfTrackerSD ()
Definition at line 81 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 81 of file CCalSDList.cc
References theList, and trackerSD.
Referenced by getTrackerSDName().
nameType CCalSDList::getTrackerSDName (G4int i)
Definition at line 64 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 64 of file CCalSDList.cc
References G4cout, G4endl, getNumberOfTrackerSD(), theList, and trackerSD.
CCalSDList & CCalSDList::operator= (CCalSDList &) private
Definition at line 87 of file CCalSDList.cc.
View newest version in sPHENIX GitHub at line 87 of file CCalSDList.cc
Member Data Documentation
std::vector<nameType> CCalSDList::caloSD private
Definition at line 62 of file CCalSDList.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalSDList.hh
Referenced by addCalo(), getCaloSDName(), and getNumberOfCaloSD().
CCalSDList * CCalSDList::theList = 0 static private
Definition at line 61 of file CCalSDList.hh.
View newest version in sPHENIX GitHub at line 61 of file CCalSDList.hh
Referenced by addCalo(), addTracker(), getCaloSDName(), getInstance(), getNumberOfCaloSD(), getNumberOfTrackerSD(), getTrackerSDName(), and ~CCalSDList().
std::vector<nameType> CCalSDList::trackerSD private
Definition at line 63 of file CCalSDList.hh.
View newest version in sPHENIX GitHub at line 63 of file CCalSDList.hh
Referenced by addTracker(), getNumberOfTrackerSD(), and getTrackerSDName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSDList.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalSDList.cc