ECCE @ EIC Software: G4ParticleHPEnAngCorrelation Class Reference
G4ParticleHPEnAngCorrelation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPEnAngCorrelation.hh>
Classes
struct toBeCached
Public Member Functions
G4ParticleHPEnAngCorrelation ()
G4ParticleHPEnAngCorrelation (G4ParticleDefinition *proj)
~G4ParticleHPEnAngCorrelation ()
void Init (std::istream &aDataFile)
G4ReactionProduct * SampleOne (G4double anEnergy)
G4ReactionProductVector * Sample (G4double anEnergy)
void SetTarget (G4ReactionProduct &aTarget)
void SetProjectileRP (G4ReactionProduct &aIncidentPart)
G4bool InCharge ()
G4double GetTargetMass ()
G4double GetTotalMeanEnergy ()
Private Attributes
G4double targetMass
G4int frameFlag
G4int nProducts
G4ParticleHPProduct * theProducts
G4bool inCharge
G4Cache< toBeCached > fCache
G4ParticleDefinition * theProjectile
G4bool bAdjustFinalState
Detailed Description
Definition at line 45 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPEnAngCorrelation.hh
Constructor & Destructor Documentation
G4ParticleHPEnAngCorrelation::G4ParticleHPEnAngCorrelation () inline
Definition at line 58 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticleHPEnAngCorrelation.hh
References bAdjustFinalState, fCache, frameFlag, G4Cache< VALTYPE >::Get(), inCharge, G4Neutron::Neutron(), nProducts, G4Cache< VALTYPE >::Put(), targetMass, theProducts, and theProjectile.
G4ParticleHPEnAngCorrelation::G4ParticleHPEnAngCorrelation (G4ParticleDefinition * proj) inline
Definition at line 73 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleHPEnAngCorrelation.hh
References bAdjustFinalState, fCache, frameFlag, G4Cache< VALTYPE >::Get(), inCharge, nProducts, G4Cache< VALTYPE >::Put(), targetMass, and theProducts.
G4ParticleHPEnAngCorrelation::~G4ParticleHPEnAngCorrelation () inline
Definition at line 88 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleHPEnAngCorrelation.hh
References theProducts.
Member Function Documentation
G4double G4ParticleHPEnAngCorrelation::GetTargetMass () inline
Definition at line 140 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ParticleHPEnAngCorrelation.hh
References targetMass.
Referenced by G4ParticleHPInelasticBaseFS::BaseApply().
G4double G4ParticleHPEnAngCorrelation::GetTotalMeanEnergy () inline
Definition at line 145 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ParticleHPEnAngCorrelation.hh
References fCache, and G4Cache< VALTYPE >::Get().
Referenced by G4ParticleHPInelasticBaseFS::BaseApply().
G4bool G4ParticleHPEnAngCorrelation::InCharge () inline
Definition at line 135 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ParticleHPEnAngCorrelation.hh
References inCharge.
void G4ParticleHPEnAngCorrelation::Init (std::istream & aDataFile) inline
Definition at line 93 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPEnAngCorrelation.hh
References bAdjustFinalState, frameFlag, inCharge, G4ParticleHPProduct::Init(), nProducts, targetMass, theProducts, and theProjectile.
Referenced by G4ParticleHPCaptureFS::Init(), G4ParticleHPInelasticBaseFS::Init(), and G4ParticleHPInelasticCompFS::Init().
G4ReactionProductVector * G4ParticleHPEnAngCorrelation::Sample (G4double anEnergy)
Definition at line 77 of file G4ParticleHPEnAngCorrelation.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPEnAngCorrelation.cc
References fCache, frameFlag, G4cout, G4endl, G4Cache< VALTYPE >::Get(), G4ReactionProduct::GetMomentum(), G4ParticleHPProduct::GetMultiplicity(), G4ParticleHPProduct::GetQValue(), G4ReactionProduct::GetTotalEnergy(), CLHEP::HepLorentzRotation::inverse(), it, G4ReactionProduct::Lorentz(), G4ParticleHPProduct::MeanEnergyOfThisInteraction(), nProducts, CLHEP::HepLorentzRotation::rotateY(), CLHEP::HepLorentzRotation::rotateZ(), G4ParticleHPProduct::Sample(), G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), and theProducts.
Referenced by G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::CompositeApply().
G4ReactionProduct * G4ParticleHPEnAngCorrelation::SampleOne (G4double anEnergy)
Definition at line 42 of file G4ParticleHPEnAngCorrelation.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPEnAngCorrelation.cc
References G4cout, G4endl, nProducts, G4ParticleHPProduct::Sample(), and theProducts.
void G4ParticleHPEnAngCorrelation::SetProjectileRP (G4ReactionProduct & aIncidentPart) inline
Definition at line 128 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 128 of file G4ParticleHPEnAngCorrelation.hh
References fCache, G4Cache< VALTYPE >::Get(), nProducts, and theProducts.
Referenced by G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::InitDistributionInitialState().
void G4ParticleHPEnAngCorrelation::SetTarget (G4ReactionProduct & aTarget) inline
Definition at line 121 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ParticleHPEnAngCorrelation.hh
References fCache, G4Cache< VALTYPE >::Get(), nProducts, and theProducts.
Referenced by G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::InitDistributionInitialState().
Member Data Documentation
G4bool G4ParticleHPEnAngCorrelation::bAdjustFinalState private
Definition at line 166 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ParticleHPEnAngCorrelation.hh
Referenced by G4ParticleHPEnAngCorrelation(), and Init().
G4Cache<toBeCached> G4ParticleHPEnAngCorrelation::fCache private
Definition at line 162 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ParticleHPEnAngCorrelation.hh
Referenced by G4ParticleHPEnAngCorrelation(), GetTotalMeanEnergy(), Sample(), SetProjectileRP(), and SetTarget().
G4int G4ParticleHPEnAngCorrelation::frameFlag private
Definition at line 155 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ParticleHPEnAngCorrelation.hh
Referenced by G4ParticleHPEnAngCorrelation(), Init(), and Sample().
G4bool G4ParticleHPEnAngCorrelation::inCharge private
Definition at line 158 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ParticleHPEnAngCorrelation.hh
Referenced by G4ParticleHPEnAngCorrelation(), InCharge(), and Init().
G4int G4ParticleHPEnAngCorrelation::nProducts private
Definition at line 156 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ParticleHPEnAngCorrelation.hh
Referenced by G4ParticleHPEnAngCorrelation(), Init(), Sample(), SampleOne(), SetProjectileRP(), and SetTarget().
G4double G4ParticleHPEnAngCorrelation::targetMass private
Definition at line 154 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParticleHPEnAngCorrelation.hh
Referenced by G4ParticleHPEnAngCorrelation(), GetTargetMass(), and Init().
G4ParticleHPProduct* G4ParticleHPEnAngCorrelation::theProducts private
Definition at line 157 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParticleHPEnAngCorrelation.hh
Referenced by G4ParticleHPEnAngCorrelation(), Init(), Sample(), SampleOne(), SetProjectileRP(), SetTarget(), and ~G4ParticleHPEnAngCorrelation().
G4ParticleDefinition* G4ParticleHPEnAngCorrelation::theProjectile private
Definition at line 164 of file G4ParticleHPEnAngCorrelation.hh.
View newest version in sPHENIX GitHub at line 164 of file G4ParticleHPEnAngCorrelation.hh
Referenced by G4ParticleHPEnAngCorrelation(), and Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPEnAngCorrelation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPEnAngCorrelation.cc