ECCE @ EIC Software: G4AdjointSimMessenger Class Reference
G4AdjointSimMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4AdjointSimMessenger.hh>
Public Member Functions
G4AdjointSimMessenger (G4AdjointSimManager *)
~G4AdjointSimMessenger ()
void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4AdjointSimManager * theAdjointRunManager
G4UIdirectory * AdjointSimDir
G4UIcommand * beamOnCmd
G4UIcommand * DefineSpherExtSourceCmd
G4UIcommand * DefineSpherExtSourceCenteredOnAVolumeCmd
G4UIcmdWithAString * DefineExtSourceOnAVolumeExtSurfaceCmd
G4UIcmdWithADoubleAndUnit * setExtSourceEMaxCmd
G4UIcommand * DefineSpherAdjSourceCmd
G4UIcommand * DefineSpherAdjSourceCenteredOnAVolumeCmd
G4UIcmdWithAString * DefineAdjSourceOnAVolumeExtSurfaceCmd
G4UIcmdWithADoubleAndUnit * setAdjSourceEminCmd
G4UIcmdWithADoubleAndUnit * setAdjSourceEmaxCmd
G4UIcmdWithAString * ConsiderParticleAsPrimaryCmd
G4UIcmdWithAString * NeglectParticleAsPrimaryCmd
G4UIcmdWithAnInteger * setNbOfPrimaryFwdGammasPerEventCmd
G4UIcmdWithAnInteger * setNbOfPrimaryAdjGammasPerEventCmd
G4UIcmdWithAnInteger * setNbOfPrimaryAdjElectronsPerEventCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 127 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 127 of file G4AdjointSimMessenger.hh
Constructor & Destructor Documentation
G4AdjointSimMessenger::G4AdjointSimMessenger (G4AdjointSimManager * pAdjointRunManager)
Definition at line 56 of file G4AdjointSimMessenger.cc.
View newest version in sPHENIX GitHub at line 56 of file G4AdjointSimMessenger.cc
References AdjointSimDir, G4UIcommand::AvailableForStates(), beamOnCmd, ConsiderParticleAsPrimaryCmd, DefineAdjSourceOnAVolumeExtSurfaceCmd, DefineExtSourceOnAVolumeExtSurfaceCmd, DefineSpherAdjSourceCenteredOnAVolumeCmd, DefineSpherAdjSourceCmd, DefineSpherExtSourceCenteredOnAVolumeCmd, DefineSpherExtSourceCmd, G4State_Idle, G4State_PreInit, NeglectParticleAsPrimaryCmd, setAdjSourceEmaxCmd, setAdjSourceEminCmd, G4UIcmdWithAString::SetCandidates(), G4UIparameter::SetDefaultValue(), setExtSourceEMaxCmd, G4UIcommand::SetGuidance(), setNbOfPrimaryAdjElectronsPerEventCmd, setNbOfPrimaryAdjGammasPerEventCmd, setNbOfPrimaryFwdGammasPerEventCmd, G4UIcommand::SetParameter(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIparameter::SetParameterRange(), and G4UIcmdWithADoubleAndUnit::SetUnitCategory().
G4AdjointSimMessenger::~G4AdjointSimMessenger ()
Definition at line 234 of file G4AdjointSimMessenger.cc.
View newest version in sPHENIX GitHub at line 234 of file G4AdjointSimMessenger.cc
References beamOnCmd.
Member Function Documentation
void G4AdjointSimMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 242 of file G4AdjointSimMessenger.cc.
View newest version in sPHENIX GitHub at line 242 of file G4AdjointSimMessenger.cc
References beamOnCmd, G4AdjointSimManager::ConsiderParticleAsPrimary(), ConsiderParticleAsPrimaryCmd, G4AdjointSimManager::DefineAdjointSourceOnTheExtSurfaceOfAVolume(), DefineAdjSourceOnAVolumeExtSurfaceCmd, DefineExtSourceOnAVolumeExtSurfaceCmd, G4AdjointSimManager::DefineExtSourceOnTheExtSurfaceOfAVolume(), DefineSpherAdjSourceCenteredOnAVolumeCmd, DefineSpherAdjSourceCmd, DefineSpherExtSourceCenteredOnAVolumeCmd, DefineSpherExtSourceCmd, G4AdjointSimManager::DefineSphericalAdjointSource(), G4AdjointSimManager::DefineSphericalAdjointSourceWithCentreAtTheCentreOfAVolume(), G4AdjointSimManager::DefineSphericalExtSource(), G4AdjointSimManager::DefineSphericalExtSourceWithCentreAtTheCentreOfAVolume(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4RunManager::GetRunManager(), G4UnitDefinition::GetValueOf(), G4AdjointSimManager::NeglectParticleAsPrimary(), NeglectParticleAsPrimaryCmd, r, G4AdjointSimManager::RunAdjointSimulation(), G4RunManager::sequentialRM, G4AdjointSimManager::SetAdjointSourceEmax(), G4AdjointSimManager::SetAdjointSourceEmin(), setAdjSourceEmaxCmd, setAdjSourceEminCmd, G4AdjointSimManager::SetExtSourceEmax(), setExtSourceEMaxCmd, G4AdjointSimManager::SetNbAdjointPrimaryElectronsPerEvent(), G4AdjointSimManager::SetNbAdjointPrimaryGammasPerEvent(), setNbOfPrimaryAdjElectronsPerEventCmd, setNbOfPrimaryAdjGammasPerEventCmd, G4AdjointSimManager::SetNbOfPrimaryFwdGammasPerEvent(), setNbOfPrimaryFwdGammasPerEventCmd, theAdjointRunManager, x, y, and z.
Member Data Documentation
G4UIdirectory* G4AdjointSimMessenger::AdjointSimDir private
Definition at line 149 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 149 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger().
G4UIcommand* G4AdjointSimMessenger::beamOnCmd private
Definition at line 150 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 150 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), SetNewValue(), and ~G4AdjointSimMessenger().
G4UIcmdWithAString* G4AdjointSimMessenger::ConsiderParticleAsPrimaryCmd private
Definition at line 165 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 165 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithAString* G4AdjointSimMessenger::DefineAdjSourceOnAVolumeExtSurfaceCmd private
Definition at line 159 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 159 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithAString* G4AdjointSimMessenger::DefineExtSourceOnAVolumeExtSurfaceCmd private
Definition at line 154 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 154 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcommand* G4AdjointSimMessenger::DefineSpherAdjSourceCenteredOnAVolumeCmd private
Definition at line 158 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 158 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcommand* G4AdjointSimMessenger::DefineSpherAdjSourceCmd private
Definition at line 157 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 157 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcommand* G4AdjointSimMessenger::DefineSpherExtSourceCenteredOnAVolumeCmd private
Definition at line 153 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 153 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcommand* G4AdjointSimMessenger::DefineSpherExtSourceCmd private
Definition at line 152 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 152 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithAString* G4AdjointSimMessenger::NeglectParticleAsPrimaryCmd private
Definition at line 166 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 166 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithADoubleAndUnit* G4AdjointSimMessenger::setAdjSourceEmaxCmd private
Definition at line 162 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 162 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithADoubleAndUnit* G4AdjointSimMessenger::setAdjSourceEminCmd private
Definition at line 161 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 161 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithADoubleAndUnit* G4AdjointSimMessenger::setExtSourceEMaxCmd private
Definition at line 155 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 155 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithAnInteger* G4AdjointSimMessenger::setNbOfPrimaryAdjElectronsPerEventCmd private
Definition at line 170 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 170 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithAnInteger* G4AdjointSimMessenger::setNbOfPrimaryAdjGammasPerEventCmd private
Definition at line 169 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 169 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4UIcmdWithAnInteger* G4AdjointSimMessenger::setNbOfPrimaryFwdGammasPerEventCmd private
Definition at line 168 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 168 of file G4AdjointSimMessenger.hh
Referenced by G4AdjointSimMessenger(), and SetNewValue().
G4AdjointSimManager* G4AdjointSimMessenger::theAdjointRunManager private
Definition at line 142 of file G4AdjointSimMessenger.hh.
View newest version in sPHENIX GitHub at line 142 of file G4AdjointSimMessenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4AdjointSimMessenger.hh
geant4/tree/geant4-10.6-release/source/run/src/G4AdjointSimMessenger.cc