ECCE @ EIC Software: G4CascadeParameters Class Reference
G4CascadeParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeParameters.hh>
Public Member Functions
~G4CascadeParameters ()
Static Public Member Functions
static const G4CascadeParameters * Instance ()
static G4int verbose ()
static G4bool checkConservation ()
static G4bool usePreCompound ()
static G4bool doCoalescence ()
static G4bool showHistory ()
static G4bool use3BodyMom ()
static G4bool usePhaseSpace ()
static G4double piNAbsorption ()
static const G4String & randomFile ()
static G4bool useTwoParam ()
static G4double radiusScale ()
static G4double radiusSmall ()
static G4double radiusAlpha ()
static G4double radiusTrailing ()
static G4double fermiScale ()
static G4double xsecScale ()
static G4double gammaQDScale ()
static G4double dpMaxDoublet ()
static G4double dpMaxTriplet ()
static G4double dpMaxAlpha ()
static void DumpConfiguration (std::ostream &os)
Private Member Functions
void Initialize ()
G4CascadeParameters ()
void DumpConfig (std::ostream &os) const
Private Attributes
const char * G4CASCADE_VERBOSE
const char * G4CASCADE_CHECK_ECONS
const char * G4CASCADE_USE_PRECOMPOUND
const char * G4CASCADE_DO_COALESCENCE
const char * G4CASCADE_SHOW_HISTORY
const char * G4CASCADE_USE_3BODYMOM
const char * G4CASCADE_USE_PHASESPACE
const char * G4CASCADE_PIN_ABSORPTION
const char * G4CASCADE_RANDOM_FILE
const char * G4NUCMODEL_USE_BEST
const char * G4NUCMODEL_RAD_2PAR
const char * G4NUCMODEL_RAD_SCALE
const char * G4NUCMODEL_RAD_SMALL
const char * G4NUCMODEL_RAD_ALPHA
const char * G4NUCMODEL_RAD_TRAILING
const char * G4NUCMODEL_FERMI_SCALE
const char * G4NUCMODEL_XSEC_SCALE
const char * G4NUCMODEL_GAMMAQD
const char * DPMAX_2CLUSTER
const char * DPMAX_3CLUSTER
const char * DPMAX_4CLUSTER
G4int VERBOSE_LEVEL
G4bool CHECK_ECONS
G4bool USE_PRECOMPOUND
G4bool DO_COALESCENCE
G4bool SHOW_HISTORY
G4bool USE_3BODYMOM
G4bool USE_PHASESPACE
G4double PIN_ABSORPTION
G4String RANDOM_FILE
G4bool BEST_PAR
G4bool TWOPARAM_RADIUS
G4double RADIUS_SCALE
G4double RADIUS_SMALL
G4double RADIUS_ALPHA
G4double RADIUS_TRAILING
G4double FERMI_SCALE
G4double XSEC_SCALE
G4double GAMMAQD_SCALE
G4double DPMAX_DOUBLET
G4double DPMAX_TRIPLET
G4double DPMAX_ALPHA
G4CascadeParamMessenger * messenger
Static Private Attributes
static G4CascadeParameters * fpInstance = 0
Friends
class G4CascadeParamMessenger
Detailed Description
Definition at line 46 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 46 of file G4CascadeParameters.hh
Constructor & Destructor Documentation
G4CascadeParameters::~G4CascadeParameters ()
Definition at line 151 of file G4CascadeParameters.cc.
View newest version in sPHENIX GitHub at line 151 of file G4CascadeParameters.cc
References messenger.
G4CascadeParameters::G4CascadeParameters () private
Definition at line 86 of file G4CascadeParameters.cc.
View newest version in sPHENIX GitHub at line 86 of file G4CascadeParameters.cc
References G4CascadeParamMessenger, Initialize(), and messenger.
Referenced by Instance().
Member Function Documentation
static G4bool G4CascadeParameters::checkConservation () inline static
Definition at line 53 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 53 of file G4CascadeParameters.hh
References CHECK_ECONS, and Instance().
Referenced by G4CascadeColliderBase::G4CascadeColliderBase(), and G4CascadeDeexciteBase::G4CascadeDeexciteBase().
static G4bool G4CascadeParameters::doCoalescence () inline static
Definition at line 55 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 55 of file G4CascadeParameters.hh
References DO_COALESCENCE, and Instance().
Referenced by G4IntraNucleiCascader::G4IntraNucleiCascader().
static G4double G4CascadeParameters::dpMaxAlpha () inline static
Definition at line 75 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 75 of file G4CascadeParameters.hh
References DPMAX_ALPHA, and Instance().
static G4double G4CascadeParameters::dpMaxDoublet () inline static
Definition at line 73 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 73 of file G4CascadeParameters.hh
References DPMAX_DOUBLET, and Instance().
static G4double G4CascadeParameters::dpMaxTriplet () inline static
Definition at line 74 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 74 of file G4CascadeParameters.hh
References DPMAX_TRIPLET, and Instance().
void G4CascadeParameters::DumpConfig (std::ostream & os) const private
Definition at line 158 of file G4CascadeParameters.cc.
View newest version in sPHENIX GitHub at line 158 of file G4CascadeParameters.cc
References DPMAX_2CLUSTER, DPMAX_3CLUSTER, DPMAX_4CLUSTER, G4CASCADE_CHECK_ECONS, G4CASCADE_DO_COALESCENCE, G4CASCADE_PIN_ABSORPTION, G4CASCADE_RANDOM_FILE, G4CASCADE_SHOW_HISTORY, G4CASCADE_USE_3BODYMOM, G4CASCADE_USE_PHASESPACE, G4CASCADE_USE_PRECOMPOUND, G4CASCADE_VERBOSE, G4NUCMODEL_FERMI_SCALE, G4NUCMODEL_GAMMAQD, G4NUCMODEL_RAD_2PAR, G4NUCMODEL_RAD_ALPHA, G4NUCMODEL_RAD_SCALE, G4NUCMODEL_RAD_SMALL, G4NUCMODEL_RAD_TRAILING, G4NUCMODEL_USE_BEST, and G4NUCMODEL_XSEC_SCALE.
Referenced by DumpConfiguration(), and G4CascadeParamMessenger::SetNewValue().
static void G4CascadeParameters::DumpConfiguration (std::ostream & os) inline static
Definition at line 77 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 77 of file G4CascadeParameters.hh
References DumpConfig(), and Instance().
Referenced by G4CascadeInterface::DumpConfiguration().
static G4double G4CascadeParameters::fermiScale () inline static
Definition at line 68 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 68 of file G4CascadeParameters.hh
References FERMI_SCALE, and Instance().
static G4double G4CascadeParameters::gammaQDScale () inline static
Definition at line 70 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 70 of file G4CascadeParameters.hh
References GAMMAQD_SCALE, and Instance().
void G4CascadeParameters::Initialize () private
Definition at line 113 of file G4CascadeParameters.cc.
View newest version in sPHENIX GitHub at line 113 of file G4CascadeParameters.cc
References BEST_PAR, CHECK_ECONS, G4HadronicDeveloperParameters::DeveloperGet(), DO_COALESCENCE, DPMAX_2CLUSTER, DPMAX_3CLUSTER, DPMAX_4CLUSTER, DPMAX_ALPHA, DPMAX_DOUBLET, DPMAX_TRIPLET, FERMI_SCALE, G4CASCADE_CHECK_ECONS, G4CASCADE_DO_COALESCENCE, G4CASCADE_PIN_ABSORPTION, G4CASCADE_RANDOM_FILE, G4CASCADE_SHOW_HISTORY, G4CASCADE_USE_3BODYMOM, G4CASCADE_USE_PHASESPACE, G4CASCADE_USE_PRECOMPOUND, G4CASCADE_VERBOSE, G4NUCMODEL_FERMI_SCALE, G4NUCMODEL_GAMMAQD, G4NUCMODEL_RAD_2PAR, G4NUCMODEL_RAD_ALPHA, G4NUCMODEL_RAD_SCALE, G4NUCMODEL_RAD_SMALL, G4NUCMODEL_RAD_TRAILING, G4NUCMODEL_USE_BEST, G4NUCMODEL_XSEC_SCALE, GAMMAQD_SCALE, HDP, OLD_RADIUS_UNITS, PIN_ABSORPTION, RADIUS_ALPHA, RADIUS_SCALE, RADIUS_SMALL, RADIUS_TRAILING, RANDOM_FILE, SHOW_HISTORY, TWOPARAM_RADIUS, USE_3BODYMOM, USE_PHASESPACE, USE_PRECOMPOUND, VERBOSE_LEVEL, and XSEC_SCALE.
Referenced by G4CascadeParameters(), and G4CascadeParamMessenger::SetNewValue().
const G4CascadeParameters * G4CascadeParameters::Instance (void) static
Definition at line 72 of file G4CascadeParameters.cc.
View newest version in sPHENIX GitHub at line 72 of file G4CascadeParameters.cc
References fpInstance, G4CascadeParameters(), and G4AutoDelete::Register().
Referenced by checkConservation(), doCoalescence(), dpMaxAlpha(), dpMaxDoublet(), dpMaxTriplet(), DumpConfiguration(), fermiScale(), gammaQDScale(), piNAbsorption(), radiusAlpha(), radiusScale(), radiusSmall(), radiusTrailing(), randomFile(), showHistory(), use3BodyMom(), usePhaseSpace(), usePreCompound(), useTwoParam(), verbose(), and xsecScale().
static G4double G4CascadeParameters::piNAbsorption () inline static
Definition at line 59 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 59 of file G4CascadeParameters.hh
References Instance(), and PIN_ABSORPTION.
Referenced by G4ElementaryParticleCollider::pionNucleonAbsorption().
static G4double G4CascadeParameters::radiusAlpha () inline static
Definition at line 66 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 66 of file G4CascadeParameters.hh
References Instance(), and RADIUS_ALPHA.
static G4double G4CascadeParameters::radiusScale () inline static
Definition at line 64 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 64 of file G4CascadeParameters.hh
References Instance(), and RADIUS_SCALE.
static G4double G4CascadeParameters::radiusSmall () inline static
Definition at line 65 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 65 of file G4CascadeParameters.hh
References Instance(), and RADIUS_SMALL.
static G4double G4CascadeParameters::radiusTrailing () inline static
Definition at line 67 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 67 of file G4CascadeParameters.hh
References Instance(), and RADIUS_TRAILING.
static const G4String& G4CascadeParameters::randomFile () inline static
Definition at line 60 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 60 of file G4CascadeParameters.hh
References Instance(), and RANDOM_FILE.
static G4bool G4CascadeParameters::showHistory () inline static
Definition at line 56 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 56 of file G4CascadeParameters.hh
References Instance(), and SHOW_HISTORY.
Referenced by G4IntraNucleiCascader::G4IntraNucleiCascader().
static G4bool G4CascadeParameters::use3BodyMom () inline static
Definition at line 57 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 57 of file G4CascadeParameters.hh
References Instance(), and USE_3BODYMOM.
Referenced by G4MultiBodyMomentumDist::ChooseDist().
static G4bool G4CascadeParameters::usePhaseSpace () inline static
Definition at line 58 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 58 of file G4CascadeParameters.hh
References Instance(), and USE_PHASESPACE.
Referenced by G4CascadeFinalStateAlgorithm::ChooseGenerators(), and G4CascadeFinalStateAlgorithm::GenerateMultiBody().
static G4bool G4CascadeParameters::usePreCompound () inline static
Definition at line 54 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 54 of file G4CascadeParameters.hh
References Instance(), and USE_PRECOMPOUND.
Referenced by G4CascadeInterface::G4CascadeInterface().
static G4bool G4CascadeParameters::useTwoParam () inline static
Definition at line 63 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 63 of file G4CascadeParameters.hh
References Instance(), and TWOPARAM_RADIUS.
static G4int G4CascadeParameters::verbose () inline static
Definition at line 52 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 52 of file G4CascadeParameters.hh
References Instance(), and VERBOSE_LEVEL.
Referenced by G4CascadeInterface::G4CascadeInterface().
static G4double G4CascadeParameters::xsecScale () inline static
Definition at line 69 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 69 of file G4CascadeParameters.hh
References Instance(), and XSEC_SCALE.
Friends And Related Function Documentation
friend class G4CascadeParamMessenger friend
Definition at line 137 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 137 of file G4CascadeParameters.hh
Referenced by G4CascadeParameters().
Member Data Documentation
G4bool G4CascadeParameters::BEST_PAR private
Definition at line 114 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 114 of file G4CascadeParameters.hh
Referenced by Initialize().
G4bool G4CascadeParameters::CHECK_ECONS private
Definition at line 105 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 105 of file G4CascadeParameters.hh
Referenced by checkConservation(), and Initialize().
G4bool G4CascadeParameters::DO_COALESCENCE private
Definition at line 107 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 107 of file G4CascadeParameters.hh
Referenced by doCoalescence(), and Initialize().
const char* G4CascadeParameters::DPMAX_2CLUSTER private
Definition at line 98 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 98 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::DPMAX_3CLUSTER private
Definition at line 99 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 99 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::DPMAX_4CLUSTER private
Definition at line 100 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 100 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
G4double G4CascadeParameters::DPMAX_ALPHA private
Definition at line 130 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 130 of file G4CascadeParameters.hh
Referenced by dpMaxAlpha(), and Initialize().
G4double G4CascadeParameters::DPMAX_DOUBLET private
Definition at line 128 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 128 of file G4CascadeParameters.hh
Referenced by dpMaxDoublet(), and Initialize().
G4double G4CascadeParameters::DPMAX_TRIPLET private
Definition at line 129 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 129 of file G4CascadeParameters.hh
Referenced by dpMaxTriplet(), and Initialize().
G4double G4CascadeParameters::FERMI_SCALE private
Definition at line 124 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 124 of file G4CascadeParameters.hh
Referenced by fermiScale(), and Initialize().
G4CascadeParameters * G4CascadeParameters::fpInstance = 0 static private
Definition at line 139 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 139 of file G4CascadeParameters.hh
Referenced by Instance().
const char* G4CascadeParameters::G4CASCADE_CHECK_ECONS private
Definition at line 81 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 81 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4CASCADE_DO_COALESCENCE private
Definition at line 83 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 83 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4CASCADE_PIN_ABSORPTION private
Definition at line 87 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 87 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4CASCADE_RANDOM_FILE private
Definition at line 88 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 88 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4CASCADE_SHOW_HISTORY private
Definition at line 84 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 84 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4CASCADE_USE_3BODYMOM private
Definition at line 85 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 85 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4CASCADE_USE_PHASESPACE private
Definition at line 86 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 86 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4CASCADE_USE_PRECOMPOUND private
Definition at line 82 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 82 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4CASCADE_VERBOSE private
Definition at line 80 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 80 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_FERMI_SCALE private
Definition at line 95 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 95 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_GAMMAQD private
Definition at line 97 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 97 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_RAD_2PAR private
Definition at line 90 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 90 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_RAD_ALPHA private
Definition at line 93 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 93 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_RAD_SCALE private
Definition at line 91 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 91 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_RAD_SMALL private
Definition at line 92 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 92 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_RAD_TRAILING private
Definition at line 94 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 94 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_USE_BEST private
Definition at line 89 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 89 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
const char* G4CascadeParameters::G4NUCMODEL_XSEC_SCALE private
Definition at line 96 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 96 of file G4CascadeParameters.hh
Referenced by DumpConfig(), Initialize(), and G4CascadeParamMessenger::SetNewValue().
G4double G4CascadeParameters::GAMMAQD_SCALE private
Definition at line 126 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 126 of file G4CascadeParameters.hh
Referenced by gammaQDScale(), and Initialize().
G4CascadeParamMessenger* G4CascadeParameters::messenger private
Definition at line 136 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 136 of file G4CascadeParameters.hh
Referenced by G4CascadeParameters(), and ~G4CascadeParameters().
G4double G4CascadeParameters::PIN_ABSORPTION private
Definition at line 111 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 111 of file G4CascadeParameters.hh
Referenced by Initialize(), and piNAbsorption().
G4double G4CascadeParameters::RADIUS_ALPHA private
Definition at line 122 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 122 of file G4CascadeParameters.hh
Referenced by Initialize(), and radiusAlpha().
G4double G4CascadeParameters::RADIUS_SCALE private
Definition at line 120 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 120 of file G4CascadeParameters.hh
Referenced by Initialize(), and radiusScale().
G4double G4CascadeParameters::RADIUS_SMALL private
Definition at line 121 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 121 of file G4CascadeParameters.hh
Referenced by Initialize(), and radiusSmall().
G4double G4CascadeParameters::RADIUS_TRAILING private
Definition at line 123 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 123 of file G4CascadeParameters.hh
Referenced by Initialize(), and radiusTrailing().
G4String G4CascadeParameters::RANDOM_FILE private
Definition at line 112 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 112 of file G4CascadeParameters.hh
Referenced by Initialize(), and randomFile().
G4bool G4CascadeParameters::SHOW_HISTORY private
Definition at line 108 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 108 of file G4CascadeParameters.hh
Referenced by Initialize(), and showHistory().
G4bool G4CascadeParameters::TWOPARAM_RADIUS private
Definition at line 119 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 119 of file G4CascadeParameters.hh
Referenced by Initialize(), and useTwoParam().
G4bool G4CascadeParameters::USE_3BODYMOM private
Definition at line 109 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 109 of file G4CascadeParameters.hh
Referenced by Initialize(), and use3BodyMom().
G4bool G4CascadeParameters::USE_PHASESPACE private
Definition at line 110 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 110 of file G4CascadeParameters.hh
Referenced by Initialize(), and usePhaseSpace().
G4bool G4CascadeParameters::USE_PRECOMPOUND private
Definition at line 106 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 106 of file G4CascadeParameters.hh
Referenced by Initialize(), and usePreCompound().
G4int G4CascadeParameters::VERBOSE_LEVEL private
Definition at line 104 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 104 of file G4CascadeParameters.hh
Referenced by Initialize(), and verbose().
G4double G4CascadeParameters::XSEC_SCALE private
Definition at line 125 of file G4CascadeParameters.hh.
View newest version in sPHENIX GitHub at line 125 of file G4CascadeParameters.hh
Referenced by Initialize(), and xsecScale().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeParameters.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeParameters.cc