ECCE @ EIC Software: G4SurfBits Class Reference
G4SurfBits Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4SurfBits.hh>
Public Member Functions
G4SurfBits (unsigned int nbits=0)
G4SurfBits (const G4SurfBits &)
G4SurfBits & operator= (const G4SurfBits &)
~G4SurfBits ()
void ResetAllBits (G4bool value=false)
void ResetBitNumber (unsigned int bitnumber)
void SetBitNumber (unsigned int bitnumber, G4bool value=true)
G4bool TestBitNumber (unsigned int bitnumber) const
G4bool operator[] (unsigned int bitnumber) const
void set (unsigned int nbits, const char *array)
void set (unsigned int nbits, const G4int *array)
void Get (char *array) const
void Get (G4int *array) const
void Clear ()
void Compact ()
unsigned int GetNbits () const
unsigned int GetNbytes () const
void Print () const
void Output (std::ostream &) const
Public Attributes
unsigned char * fAllBits = nullptr
Protected Member Functions
void ReserveBytes (unsigned int nbytes)
Protected Attributes
unsigned int fNBits
unsigned int fNBytes
Detailed Description
Definition at line 50 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 50 of file G4SurfBits.hh
Constructor & Destructor Documentation
G4SurfBits::G4SurfBits (unsigned int nbits = 0)
Definition at line 36 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 36 of file G4SurfBits.cc
References fAllBits, fNBits, and fNBytes.
G4SurfBits::G4SurfBits (const G4SurfBits & original)
Definition at line 48 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 48 of file G4SurfBits.cc
References fAllBits, and fNBytes.
G4SurfBits::~G4SurfBits ()
Definition at line 81 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 81 of file G4SurfBits.cc
References fAllBits.
Member Function Documentation
void G4SurfBits::Clear ()
Definition at line 89 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 89 of file G4SurfBits.cc
References fAllBits, fNBits, and fNBytes.
Referenced by G4Voxelizer::BuildBitmasks(), G4Voxelizer::BuildEmpty(), G4TessellatedSolid::PrecalculateInsides(), and G4Voxelizer::Voxelize().
void G4SurfBits::Compact ()
Definition at line 100 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 100 of file G4SurfBits.cc
References fAllBits, fNBits, and fNBytes.
void G4SurfBits::Get (char * array) const
Definition at line 188 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 188 of file G4SurfBits.cc
References fAllBits, and fNBits.
Referenced by Get().
void G4SurfBits::Get (G4int * array) const
Definition at line 206 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 206 of file G4SurfBits.cc
References Get().
unsigned int G4SurfBits::GetNbits () const inline
Definition at line 92 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 92 of file G4SurfBits.hh
References fNBits.
Referenced by G4TessellatedSolid::InsideVoxels(), G4TessellatedSolid::SafetyFromOutside(), and G4TessellatedSolid::Voxelize().
unsigned int G4SurfBits::GetNbytes () const inline
Definition at line 93 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 93 of file G4SurfBits.hh
References fNBytes.
Referenced by G4Voxelizer::AllocatedMemory(), and G4TessellatedSolid::AllocatedMemory().
G4SurfBits & G4SurfBits::operator= (const G4SurfBits & rhs)
Definition at line 58 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 58 of file G4SurfBits.cc
References fAllBits, fNBits, and fNBytes.
G4bool G4SurfBits::operator[] (unsigned int bitnumber) const inline
Definition at line 159 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 159 of file G4SurfBits.hh
References TestBitNumber().
void G4SurfBits::Output (std::ostream & os) const
Definition at line 123 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 123 of file G4SurfBits.cc
References fAllBits, and fNBytes.
void G4SurfBits::Print (void) const
Definition at line 138 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 138 of file G4SurfBits.cc
References fAllBits, fNBytes, G4cout, and G4endl.
void G4SurfBits::ReserveBytes (unsigned int nbytes) protected
Definition at line 161 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 161 of file G4SurfBits.cc
References fAllBits, and fNBytes.
Referenced by set().
void G4SurfBits::ResetAllBits (G4bool value = false)
Definition at line 155 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 155 of file G4SurfBits.cc
References fAllBits, and fNBytes.
Referenced by G4Voxelizer::BuildEmpty().
void G4SurfBits::ResetBitNumber (unsigned int bitnumber) inline
Definition at line 154 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 154 of file G4SurfBits.hh
References SetBitNumber().
Referenced by G4Voxelizer::BuildEmpty(), and G4TessellatedSolid::PrecalculateInsides().
void G4SurfBits::set (unsigned int nbits, const char * array)
Definition at line 176 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 176 of file G4SurfBits.cc
References fAllBits, fNBits, and ReserveBytes().
Referenced by G4Voxelizer::DisplayListNodes().
void G4SurfBits::set (unsigned int nbits, const G4int * array)
Definition at line 198 of file G4SurfBits.cc.
View newest version in sPHENIX GitHub at line 198 of file G4SurfBits.cc
void G4SurfBits::SetBitNumber (unsigned int bitnumber, G4bool value = true) inline
Definition at line 114 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 114 of file G4SurfBits.hh
References fAllBits, fNBits, and fNBytes.
Referenced by G4Voxelizer::BuildBitmasks(), G4Voxelizer::BuildEmpty(), G4MultiUnion::DistanceToInCandidates(), G4TessellatedSolid::PrecalculateInsides(), ResetBitNumber(), and G4TessellatedSolid::SetAllUsingStack().
G4bool G4SurfBits::TestBitNumber (unsigned int bitnumber) const inline
Definition at line 141 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 141 of file G4SurfBits.hh
References fAllBits, and fNBits.
Referenced by G4Voxelizer::GetCandidatesAsString(), and operator[]().
Member Data Documentation
unsigned char* G4SurfBits::fAllBits = nullptr
Definition at line 104 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 104 of file G4SurfBits.hh
Referenced by Clear(), Compact(), G4SurfBits(), Get(), G4Voxelizer::GetCandidatesVoxelArray(), operator=(), Output(), Print(), ReserveBytes(), ResetAllBits(), set(), SetBitNumber(), TestBitNumber(), and ~G4SurfBits().
unsigned int G4SurfBits::fNBits protected
Definition at line 108 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 108 of file G4SurfBits.hh
Referenced by Clear(), Compact(), G4SurfBits(), Get(), GetNbits(), operator=(), set(), SetBitNumber(), and TestBitNumber().
unsigned int G4SurfBits::fNBytes protected
Definition at line 109 of file G4SurfBits.hh.
View newest version in sPHENIX GitHub at line 109 of file G4SurfBits.hh
Referenced by Clear(), Compact(), G4SurfBits(), GetNbytes(), operator=(), Output(), Print(), ReserveBytes(), ResetAllBits(), and SetBitNumber().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4SurfBits.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4SurfBits.cc