ECCE @ EIC Software: G4PhysicsTable Class Reference
G4PhysicsTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4PhysicsTable.hh>
Public Member Functions
G4PhysicsTable ()
G4PhysicsTable (size_t cap)
virtual ~G4PhysicsTable ()
G4PhysicsVector *& operator() (size_t)
G4PhysicsVector *const & operator() (size_t) const
void clearAndDestroy ()
void push_back (G4PhysicsVector *)
void insert (G4PhysicsVector *)
void insertAt (size_t, G4PhysicsVector *)
void resize (size_t, G4PhysicsVector *vec=(G4PhysicsVector *)(0))
size_t entries () const
size_t length () const
G4bool isEmpty () const
G4bool ExistPhysicsTable (const G4String &fileName) const
G4bool StorePhysicsTable (const G4String &filename, G4bool ascii=false)
G4bool RetrievePhysicsTable (const G4String &filename, G4bool ascii=false)
void ResetFlagArray ()
G4bool GetFlag (size_t i) const
void ClearFlag (size_t i)
Protected Member Functions
G4PhysicsVector * CreatePhysicsVector (G4int type)
Protected Attributes
G4FlagCollection vecFlag
Private Types
typedef std::vector
< G4PhysicsVector * > G4PhysCollection
typedef std::vector< G4bool > G4FlagCollection
Private Member Functions
G4PhysicsTable (const G4PhysicsTable &)=delete
G4PhysicsTable & operator= (const G4PhysicsTable &)=delete
Friends
std::ostream & operator<< (std::ostream &out, G4PhysicsTable &table)
Additional Inherited Members
Public Attributes inherited from std::vector< T >
T elements
STL member.
Detailed Description
Definition at line 65 of file G4PhysicsTable.hh.
View newest version in sPHENIX GitHub at line 65 of file G4PhysicsTable.hh
Member Typedef Documentation
typedef std::vector<G4bool> G4PhysicsTable::G4FlagCollection private
Definition at line 69 of file G4PhysicsTable.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PhysicsTable.hh
typedef std::vector<G4PhysicsVector*> G4PhysicsTable::G4PhysCollection private
Definition at line 68 of file G4PhysicsTable.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PhysicsTable.hh
Constructor & Destructor Documentation
G4PhysicsTable::G4PhysicsTable ()
Definition at line 50 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 50 of file G4PhysicsTable.cc
G4PhysicsTable::G4PhysicsTable (size_t cap) explicit
Definition at line 55 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 55 of file G4PhysicsTable.cc
References vecFlag.
G4PhysicsTable::~G4PhysicsTable () virtual
Definition at line 85 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 85 of file G4PhysicsTable.cc
References clear(), and vecFlag.
G4PhysicsTable::G4PhysicsTable (const G4PhysicsTable &) private delete
Member Function Documentation
void G4PhysicsTable::clearAndDestroy ()
Referenced by G4eLowEnergyLoss::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildLabTimeTable(), G4hImpactIonisation::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4VLEPTSModel::BuildPhysicsTable(), G4ParticleHPFissionData::BuildPhysicsTable(), G4ParticleHPCaptureData::BuildPhysicsTable(), G4ParticleHPElasticData::BuildPhysicsTable(), G4ParticleHPInelasticData::BuildPhysicsTable(), G4OpRayleigh::BuildPhysicsTable(), G4OpWLS::BuildPhysicsTable(), G4Scintillation::BuildPhysicsTable(), G4RDVeLowEnergyLoss::BuildProperTimeTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffATable(), G4hRDEnergyLoss::BuildRangeCoeffATable(), G4RDVeLowEnergyLoss::BuildRangeCoeffBTable(), G4hRDEnergyLoss::BuildRangeCoeffBTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffCTable(), G4hRDEnergyLoss::BuildRangeCoeffCTable(), G4RDVeLowEnergyLoss::BuildRangeTable(), G4hRDEnergyLoss::BuildRangeTable(), G4LossTableBuilder::BuildTableForModel(), G4hRDEnergyLoss::BuildTimeTables(), G4PolarizedCompton::CleanTable(), G4eplusPolarizedAnnihilation::CleanTables(), G4ePolarizedIonisation::CleanTables(), G4VRangeToEnergyConverter::G4VRangeToEnergyConverter(), G4VMscModel::GetParticleChangeForMSC(), G4VRangeToEnergyConverter::operator=(), G4VEnergyLossProcess::PreparePhysicsTable(), G4VRangeToEnergyConverter::Reset(), RetrievePhysicsTable(), G4VEmModel::SetCrossSectionTable(), G4Cerenkov::~G4Cerenkov(), G4eLowEnergyLoss::~G4eLowEnergyLoss(), G4hImpactIonisation::~G4hImpactIonisation(), G4hRDEnergyLoss::~G4hRDEnergyLoss(), G4NeutronElectronElModel::~G4NeutronElectronElModel(), G4OpRayleigh::~G4OpRayleigh(), G4OpWLS::~G4OpWLS(), G4ParticleHPCaptureData::~G4ParticleHPCaptureData(), G4ParticleHPElasticData::~G4ParticleHPElasticData(), G4ParticleHPFissionData::~G4ParticleHPFissionData(), G4ParticleHPInelasticData::~G4ParticleHPInelasticData(), G4Scintillation::~G4Scintillation(), G4TablesForExtrapolator::~G4TablesForExtrapolator(), G4UPiNuclearCrossSection::~G4UPiNuclearCrossSection(), G4VEmModel::~G4VEmModel(), G4VEnergyLossProcess::~G4VEnergyLossProcess(), G4VLEPTSModel::~G4VLEPTSModel(), G4VXTRenergyLoss::~G4VXTRenergyLoss(), and WLSPrimaryGeneratorAction::~WLSPrimaryGeneratorAction().
void G4PhysicsTable::ClearFlag (size_t i)
Referenced by G4PhysicsTableHelper::PreparePhysicsTable(), G4PhysicsTableHelper::RetrievePhysicsTable(), and G4PhysicsTableHelper::SetPhysicsVector().
G4PhysicsVector * G4PhysicsTable::CreatePhysicsVector (G4int type) protected
Definition at line 283 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 283 of file G4PhysicsTable.cc
References T_G4LPhysicsFreeVector, T_G4PhysicsFreeVector, T_G4PhysicsLinearVector, T_G4PhysicsLnVector, T_G4PhysicsLogVector, and T_G4PhysicsOrderedFreeVector.
Referenced by RetrievePhysicsTable().
size_t G4PhysicsTable::entries () const
Referenced by G4OpRayleigh::DumpPhysicsTable(), G4OpWLS::DumpPhysicsTable(), G4Cerenkov::DumpPhysicsTable(), G4Scintillation::DumpPhysicsTable(), and G4PenelopePhotoElectricModel::SelectRandomShell().
G4bool G4PhysicsTable::ExistPhysicsTable (const G4String & fileName) const
Definition at line 149 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 149 of file G4PhysicsTable.cc
References in.
Referenced by G4VEnergyLossProcess::RetrieveTable().
G4bool G4PhysicsTable::GetFlag (size_t i) const
Referenced by G4PolarizedCompton::BuildAsymmetryTable(), G4eplusPolarizedAnnihilation::BuildAsymmetryTables(), G4VEnergyLossProcess::BuildDEDXTable(), G4LossTableBuilder::BuildTableForModel(), G4WentzelVIModel::Initialise(), G4LossTableBuilder::InitialiseBaseMaterials(), and operator<<().
void G4PhysicsTable::insert (G4PhysicsVector *)
Referenced by G4eLowEnergyLoss::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildLabTimeTable(), G4hImpactIonisation::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4VRangeToEnergyConverter::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4RDVeLowEnergyLoss::BuildProperTimeTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffATable(), G4hRDEnergyLoss::BuildRangeCoeffATable(), G4RDVeLowEnergyLoss::BuildRangeCoeffBTable(), G4hRDEnergyLoss::BuildRangeCoeffBTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffCTable(), G4hRDEnergyLoss::BuildRangeCoeffCTable(), G4RDVeLowEnergyLoss::BuildRangeTable(), G4hRDEnergyLoss::BuildRangeTable(), G4hRDEnergyLoss::BuildTimeTables(), and G4VRangeToEnergyConverter::operator=().
void G4PhysicsTable::insertAt (size_t , G4PhysicsVector *)
Referenced by G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4NuclNuclDiffuseElastic::BuildAngleTable(), G4DiffuseElastic::BuildAngleTable(), G4VXTRenergyLoss::BuildAngleTable(), G4ePolarizedIonisation::BuildAsymmetryTables(), WLSPrimaryGeneratorAction::BuildEmissionSpectrum(), G4VXTRenergyLoss::BuildEnergyTable(), G4VXTRenergyLoss::BuildGlobalAngleTable(), G4VLEPTSModel::BuildMeanFreePathTable(), G4VLEPTSModel::BuildPhysicsTable(), G4OpRayleigh::BuildPhysicsTable(), G4OpWLS::BuildPhysicsTable(), G4hhElastic::BuildTableT(), G4hhElastic::BuildTableTest(), G4Cerenkov::BuildThePhysicsTable(), G4Scintillation::BuildThePhysicsTable(), G4ForwardXrayTR::BuildXrayTRtables(), G4NeutronElectronElModel::Initialise(), G4PAIPhotData::Initialise(), G4PAIModelData::Initialise(), G4NuclNuclDiffuseElastic::TestAngleTable(), and G4DiffuseElastic::TestAngleTable().
G4bool G4PhysicsTable::isEmpty () const
size_t G4PhysicsTable::length () const
Referenced by G4RDVeLowEnergyLoss::BuildRangeTable(), G4VEmProcess::FindLambdaMax(), G4EmDataHandler::RetrievePhysicsTable(), G4VEmProcess::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrieveTable(), G4VEnergyLossProcess::SetCSDARangeTable(), G4VEnergyLossProcess::SetDEDXTable(), G4VEnergyLossProcess::SetLambdaTable(), and G4VEmProcess::StreamInfo().
G4PhysicsVector*& G4PhysicsTable::operator() (size_t)
G4PhysicsVector* const& G4PhysicsTable::operator() (size_t) const
G4PhysicsTable& G4PhysicsTable::operator= (const G4PhysicsTable &) private delete
void G4PhysicsTable::push_back (G4PhysicsVector *)
Referenced by G4UPiNuclearCrossSection::AddDataSet(), G4ParticleHPFissionData::BuildPhysicsTable(), G4ParticleHPCaptureData::BuildPhysicsTable(), G4ParticleHPElasticData::BuildPhysicsTable(), G4ParticleHPInelasticData::BuildPhysicsTable(), G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), G4PenelopeCrossSection::G4PenelopeCrossSection(), G4PenelopeBremsstrahlungFS::InitializeEnergySampling(), G4TablesForExtrapolator::PrepareTable(), G4PenelopeBremsstrahlungAngular::PrepareTables(), and G4PenelopePhotoElectricModel::ReadDataFile().
void G4PhysicsTable::ResetFlagArray ()
Definition at line 273 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 273 of file G4PhysicsTable.cc
References incremental_prev_tag::idx, and vecFlag.
Referenced by G4PhysicsTableHelper::PreparePhysicsTable().
void G4PhysicsTable::resize (size_t siz, G4PhysicsVector * vec = (G4PhysicsVector*)(0))
Definition at line 91 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 91 of file G4PhysicsTable.cc
References vecFlag.
Referenced by G4PhysicsTableHelper::PreparePhysicsTable().
G4bool G4PhysicsTable::RetrievePhysicsTable (const G4String & filename, G4bool ascii = false)
Definition at line 165 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 165 of file G4PhysicsTable.cc
References clearAndDestroy(), CreatePhysicsVector(), G4cerr, G4endl, incremental_prev_tag::idx, in, G4PhysicsVector::Retrieve(), and vecFlag.
Referenced by G4DNABornExcitationModel2::Initialise(), and G4PhysicsTableHelper::RetrievePhysicsTable().
G4bool G4PhysicsTable::StorePhysicsTable (const G4String & filename, G4bool ascii = false)
Definition at line 97 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 97 of file G4PhysicsTable.cc
References G4cerr, and G4endl.
Referenced by G4VMultipleScattering::StorePhysicsTable(), G4VEmProcess::StorePhysicsTable(), and G4VEnergyLossProcess::StoreTable().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, G4PhysicsTable & table) friend
Definition at line 247 of file G4PhysicsTable.cc.
View newest version in sPHENIX GitHub at line 247 of file G4PhysicsTable.cc
Member Data Documentation
G4FlagCollection G4PhysicsTable::vecFlag protected
Definition at line 131 of file G4PhysicsTable.hh.
View newest version in sPHENIX GitHub at line 131 of file G4PhysicsTable.hh
Referenced by G4PhysicsTable(), ResetFlagArray(), resize(), RetrievePhysicsTable(), and ~G4PhysicsTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4PhysicsTable.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4PhysicsTable.cc