ECCE @ EIC Software: G4CompositeEMDataSet Class Reference
G4CompositeEMDataSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4CompositeEMDataSet.hh>
Public Member Functions
G4CompositeEMDataSet (G4VDataSetAlgorithm *argAlgorithm, G4double eUnit=CLHEP::MeV, G4double dataUnit=CLHEP::barn, G4int zMin=1, G4int zMax=99)
virtual ~G4CompositeEMDataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const
virtual void PrintData (void) const
virtual const G4VEMDataSet * GetComponent (G4int componentId) const
virtual void AddComponent (G4VEMDataSet *dataSet)
virtual size_t NumberOfComponents () const
virtual const G4DataVector & GetEnergies (G4int componentId) const
virtual const G4DataVector & GetData (G4int componentId) const
virtual const G4DataVector & GetLogEnergies (G4int componentId) const
virtual const G4DataVector & GetLogData (G4int componentId) const
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *data, G4int componentId)
virtual void SetLogEnergiesData (G4DataVector *xData, G4DataVector *data, G4DataVector *xLogData, G4DataVector *Logdata, G4int componentId)
virtual G4bool LoadData (const G4String &fileName)
virtual G4bool LoadNonLogData (const G4String &fileName)
virtual G4bool SaveData (const G4String &fileName) const
virtual G4double RandomSelect (G4int componentId) const
Public Member Functions inherited from G4VEMDataSet
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
Private Member Functions
void CleanUpComponents (void)
G4CompositeEMDataSet ()
G4CompositeEMDataSet (const G4CompositeEMDataSet &copy)
G4CompositeEMDataSet & operator= (const G4CompositeEMDataSet &right)
Private Attributes
std::vector< G4VEMDataSet * > components
G4VDataSetAlgorithm * algorithm
G4double unitEnergies
G4double unitData
G4int minZ
G4int maxZ
Detailed Description
Definition at line 58 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 58 of file G4CompositeEMDataSet.hh
Constructor & Destructor Documentation
G4CompositeEMDataSet::G4CompositeEMDataSet (G4VDataSetAlgorithm * argAlgorithm, G4double eUnit = CLHEP::MeV, G4double dataUnit = CLHEP::barn, G4int zMin = 1, G4int zMax = 99)
Definition at line 56 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 56 of file G4CompositeEMDataSet.cc
References algorithm, FatalException, and G4Exception().
G4CompositeEMDataSet::~G4CompositeEMDataSet () virtual
Definition at line 76 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 76 of file G4CompositeEMDataSet.cc
References algorithm, and CleanUpComponents().
G4CompositeEMDataSet::G4CompositeEMDataSet () private
G4CompositeEMDataSet::G4CompositeEMDataSet (const G4CompositeEMDataSet & copy) private
Member Function Documentation
virtual void G4CompositeEMDataSet::AddComponent (G4VEMDataSet * dataSet) inline virtual
Implements G4VEMDataSet.
Definition at line 74 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 74 of file G4CompositeEMDataSet.hh
References components.
Referenced by LoadData(), and LoadNonLogData().
void G4CompositeEMDataSet::CleanUpComponents (void) private
Definition at line 212 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 212 of file G4CompositeEMDataSet.cc
References components.
Referenced by LoadData(), LoadNonLogData(), and ~G4CompositeEMDataSet().
G4double G4CompositeEMDataSet::FindValue (G4double x, G4int componentId = 0) const virtual
Implements G4VEMDataSet.
Definition at line 83 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 83 of file G4CompositeEMDataSet.cc
References FatalException, G4VEMDataSet::FindValue(), G4Exception(), GetComponent(), and message().
Referenced by G4LivermorePolarizedComptonModel::SampleSecondaries().
virtual const G4VEMDataSet* G4CompositeEMDataSet::GetComponent (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 73 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 73 of file G4CompositeEMDataSet.hh
References components.
Referenced by FindValue(), GetData(), GetEnergies(), GetLogData(), GetLogEnergies(), PrintData(), RandomSelect(), and SaveData().
virtual const G4DataVector& G4CompositeEMDataSet::GetData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 78 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 78 of file G4CompositeEMDataSet.hh
References GetComponent(), and G4VEMDataSet::GetData().
virtual const G4DataVector& G4CompositeEMDataSet::GetEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 77 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 77 of file G4CompositeEMDataSet.hh
References GetComponent(), and G4VEMDataSet::GetEnergies().
virtual const G4DataVector& G4CompositeEMDataSet::GetLogData (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 80 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 80 of file G4CompositeEMDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogData().
virtual const G4DataVector& G4CompositeEMDataSet::GetLogEnergies (G4int componentId) const inline virtual
Implements G4VEMDataSet.
Definition at line 79 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 79 of file G4CompositeEMDataSet.hh
References GetComponent(), and G4VEMDataSet::GetLogEnergies().
G4bool G4CompositeEMDataSet::LoadData (const G4String & fileName) virtual
Implements G4VEMDataSet.
Definition at line 154 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 154 of file G4CompositeEMDataSet.cc
References AddComponent(), algorithm, CleanUpComponents(), G4VDataSetAlgorithm::Clone(), G4VEMDataSet::LoadData(), maxZ, minZ, unitData, unitEnergies, and z.
Referenced by G4LivermorePolarizedComptonModel::Initialise().
G4bool G4CompositeEMDataSet::LoadNonLogData (const G4String & fileName) virtual
Implements G4VEMDataSet.
Definition at line 172 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 172 of file G4CompositeEMDataSet.cc
References AddComponent(), algorithm, CleanUpComponents(), G4VDataSetAlgorithm::Clone(), G4VEMDataSet::LoadNonLogData(), maxZ, minZ, unitData, unitEnergies, and z.
virtual size_t G4CompositeEMDataSet::NumberOfComponents (void) const inline virtual
Implements G4VEMDataSet.
Definition at line 75 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 75 of file G4CompositeEMDataSet.hh
References components.
Referenced by PrintData().
G4CompositeEMDataSet& G4CompositeEMDataSet::operator= (const G4CompositeEMDataSet & right) private
void G4CompositeEMDataSet::PrintData (void) const virtual
Implements G4VEMDataSet.
Definition at line 98 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 98 of file G4CompositeEMDataSet.cc
References G4cout, G4endl, GetComponent(), n, NumberOfComponents(), and G4VEMDataSet::PrintData().
G4double G4CompositeEMDataSet::RandomSelect (G4int componentId) const virtual
Implements G4VEMDataSet.
Definition at line 223 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 223 of file G4CompositeEMDataSet.cc
References components, GetComponent(), and G4VEMDataSet::RandomSelect().
G4bool G4CompositeEMDataSet::SaveData (const G4String & fileName) const virtual
Implements G4VEMDataSet.
Definition at line 190 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 190 of file G4CompositeEMDataSet.cc
References FatalException, G4Exception(), GetComponent(), maxZ, message(), minZ, G4VEMDataSet::SaveData(), and z.
void G4CompositeEMDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * data, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 115 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 115 of file G4CompositeEMDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetEnergiesData().
void G4CompositeEMDataSet::SetLogEnergiesData (G4DataVector * xData, G4DataVector * data, G4DataVector * xLogData, G4DataVector * Logdata, G4int componentId) virtual
Implements G4VEMDataSet.
Definition at line 132 of file G4CompositeEMDataSet.cc.
View newest version in sPHENIX GitHub at line 132 of file G4CompositeEMDataSet.cc
References components, FatalException, G4Exception(), message(), and G4VEMDataSet::SetLogEnergiesData().
Member Data Documentation
G4VDataSetAlgorithm* G4CompositeEMDataSet::algorithm private
Definition at line 108 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 108 of file G4CompositeEMDataSet.hh
Referenced by G4CompositeEMDataSet(), LoadData(), LoadNonLogData(), and ~G4CompositeEMDataSet().
std::vector<G4VEMDataSet*> G4CompositeEMDataSet::components private
Definition at line 106 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 106 of file G4CompositeEMDataSet.hh
Referenced by AddComponent(), CleanUpComponents(), GetComponent(), NumberOfComponents(), RandomSelect(), SetEnergiesData(), and SetLogEnergiesData().
G4int G4CompositeEMDataSet::maxZ private
Definition at line 114 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 114 of file G4CompositeEMDataSet.hh
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4int G4CompositeEMDataSet::minZ private
Definition at line 113 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 113 of file G4CompositeEMDataSet.hh
Referenced by LoadData(), LoadNonLogData(), and SaveData().
G4double G4CompositeEMDataSet::unitData private
Definition at line 111 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 111 of file G4CompositeEMDataSet.hh
Referenced by LoadData(), and LoadNonLogData().
G4double G4CompositeEMDataSet::unitEnergies private
Definition at line 110 of file G4CompositeEMDataSet.hh.
View newest version in sPHENIX GitHub at line 110 of file G4CompositeEMDataSet.hh
Referenced by LoadData(), and LoadNonLogData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4CompositeEMDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4CompositeEMDataSet.cc