ECCE @ EIC Software: CLHEP::RandGeneral Class Reference
CLHEP::RandGeneral Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGeneral.h>
Public Member Functions
RandGeneral (const double *aProbFunc, int theProbSize, int IntType=0)
RandGeneral (HepRandomEngine &anEngine, const double *aProbFunc, int theProbSize, int IntType=0)
RandGeneral (HepRandomEngine *anEngine, const double *aProbFunc, int theProbSize, int IntType=0)
virtual ~RandGeneral ()
double shoot ()
void shootArray (const int size, double *vect)
double shoot (HepRandomEngine *anEngine)
void shootArray (HepRandomEngine *anEngine, const int size, double *vect)
double fire ()
void fireArray (const int size, double *vect)
double operator() ()
std::ostream & put (std::ostream &os) const
std::istream & get (std::istream &is)
std::string name () const
HepRandomEngine & engine ()
Public Member Functions inherited from CLHEP::HepRandom
HepRandom ()
HepRandom (long seed)
HepRandom (HepRandomEngine &algorithm)
HepRandom (HepRandomEngine *algorithm)
virtual ~HepRandom ()
double flat ()
void flatArray (const int size, double *vect)
double flat (HepRandomEngine *theNewEngine)
void flatArray (HepRandomEngine *theNewEngine, const int size, double *vect)
Static Public Member Functions
static std::string distributionName ()
Static Public Member Functions inherited from CLHEP::HepRandom
static void setTheSeed (long seed, int lux=3)
static long getTheSeed ()
static void setTheSeeds (const long *seeds, int aux=-1)
static const long * getTheSeeds ()
static void getTheTableSeeds (long *seeds, int index)
static HepRandom * getTheGenerator ()
static void setTheEngine (HepRandomEngine *theNewEngine)
static HepRandomEngine * getTheEngine ()
static void saveEngineStatus (const char filename[]="Config.conf")
static void restoreEngineStatus (const char filename[]="Config.conf")
static std::ostream & saveFullState (std::ostream &os)
static std::istream & restoreFullState (std::istream &is)
static std::ostream & saveDistState (std::ostream &os)
static std::istream & restoreDistState (std::istream &is)
static std::ostream & saveStaticRandomStates (std::ostream &os)
static std::istream & restoreStaticRandomStates (std::istream &is)
static void showEngineStatus ()
static int createInstance ()
static std::string distributionName ()
Private Member Functions
void prepareTable (const double *aProbFunc)
void useFlatDistribution ()
double mapRandom (double rand) const
Private Attributes
std::shared_ptr< HepRandomEngine > localEngine
std::vector< double > theIntegralPdf
int nBins
double oneOverNbins
int InterpolationType
Additional Inherited Members
Static Protected Attributes inherited from CLHEP::HepRandom
static const long seedTable [215][2]
Detailed Description
Author
Definition at line 38 of file RandGeneral.h.
View newest version in sPHENIX GitHub at line 38 of file RandGeneral.h
Constructor & Destructor Documentation
CLHEP::RandGeneral::RandGeneral (const double * aProbFunc, int theProbSize, int IntType = 0)
Definition at line 63 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 63 of file RandGeneral.cc
References prepareTable().
CLHEP::RandGeneral::RandGeneral (HepRandomEngine & anEngine, const double * aProbFunc, int theProbSize, int IntType = 0)
Definition at line 74 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 74 of file RandGeneral.cc
References prepareTable().
CLHEP::RandGeneral::RandGeneral (HepRandomEngine * anEngine, const double * aProbFunc, int theProbSize, int IntType = 0)
Definition at line 86 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 86 of file RandGeneral.cc
References prepareTable().
CLHEP::RandGeneral::~RandGeneral () virtual
Definition at line 171 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 171 of file RandGeneral.cc
Member Function Documentation
static std::string CLHEP::RandGeneral::distributionName () inline static
Definition at line 124 of file RandGeneral.h.
View newest version in sPHENIX GitHub at line 124 of file RandGeneral.h
HepRandomEngine & CLHEP::RandGeneral::engine () virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 56 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 56 of file RandGeneral.cc
References localEngine.
double CLHEP::RandGeneral::fire ()
Referenced by fireArray().
void CLHEP::RandGeneral::fireArray (const int size, double * vect)
Definition at line 237 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 237 of file RandGeneral.cc
References fire().
std::istream & CLHEP::RandGeneral::get (std::istream & is) virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 263 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 263 of file RandGeneral.cc
References InterpolationType, CLHEP::DoubConv::longs2double(), name(), nBins, oneOverNbins, CLHEP::possibleKeywordInput(), t, and theIntegralPdf.
double CLHEP::RandGeneral::mapRandom (double rand) const private
Definition at line 179 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 179 of file RandGeneral.cc
References InterpolationType, nBins, oneOverNbins, and theIntegralPdf.
std::string CLHEP::RandGeneral::name () const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 55 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 55 of file RandGeneral.cc
Referenced by get(), and put().
double CLHEP::RandGeneral::operator() () virtual
Reimplemented from CLHEP::HepRandom.
void CLHEP::RandGeneral::prepareTable (const double * aProbFunc) private
Definition at line 98 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 98 of file RandGeneral.cc
References InterpolationType, nBins, oneOverNbins, theIntegralPdf, useFlatDistribution(), and weight.
Referenced by RandGeneral().
std::ostream & CLHEP::RandGeneral::put (std::ostream & os) const virtual
Reimplemented from CLHEP::HepRandom.
Definition at line 246 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 246 of file RandGeneral.cc
References CLHEP::DoubConv::dto2longs(), InterpolationType, name(), nBins, oneOverNbins, gammaraytel::pr, t, and theIntegralPdf.
double CLHEP::RandGeneral::shoot () inline
Referenced by shootArray().
double CLHEP::RandGeneral::shoot (HepRandomEngine * anEngine)
void CLHEP::RandGeneral::shootArray (const int size, double * vect) inline
void CLHEP::RandGeneral::shootArray (HepRandomEngine * anEngine, const int size, double * vect)
Definition at line 227 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 227 of file RandGeneral.cc
References shoot().
void CLHEP::RandGeneral::useFlatDistribution () private
Definition at line 154 of file RandGeneral.cc.
View newest version in sPHENIX GitHub at line 154 of file RandGeneral.cc
References nBins, oneOverNbins, and theIntegralPdf.
Referenced by prepareTable().
Member Data Documentation
int CLHEP::RandGeneral::InterpolationType private
Definition at line 134 of file RandGeneral.h.
View newest version in sPHENIX GitHub at line 134 of file RandGeneral.h
Referenced by get(), mapRandom(), prepareTable(), and put().
std::shared_ptr<HepRandomEngine> CLHEP::RandGeneral::localEngine private
Definition at line 130 of file RandGeneral.h.
View newest version in sPHENIX GitHub at line 130 of file RandGeneral.h
Referenced by engine().
int CLHEP::RandGeneral::nBins private
Definition at line 132 of file RandGeneral.h.
View newest version in sPHENIX GitHub at line 132 of file RandGeneral.h
Referenced by get(), mapRandom(), prepareTable(), put(), and useFlatDistribution().
double CLHEP::RandGeneral::oneOverNbins private
Definition at line 133 of file RandGeneral.h.
View newest version in sPHENIX GitHub at line 133 of file RandGeneral.h
Referenced by get(), mapRandom(), prepareTable(), put(), and useFlatDistribution().
std::vector<double> CLHEP::RandGeneral::theIntegralPdf private
Definition at line 131 of file RandGeneral.h.
View newest version in sPHENIX GitHub at line 131 of file RandGeneral.h
Referenced by get(), mapRandom(), prepareTable(), put(), and useFlatDistribution().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/RandGeneral.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RandGeneral.cc