ECCE @ EIC Software: CCalG4Hcal Class Reference
CCalG4Hcal Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Hcal.hh>
Public Member Functions
CCalG4Hcal (const G4String &name)
virtual ~CCalG4Hcal ()
Public Member Functions inherited from CCalHcal
CCalHcal (const G4String &name)
virtual ~CCalHcal ()
G4String getGenMat () const
G4double getDy_2Cal () const
G4double getDx_2Cal () const
G4double getXposCal () const
G4String getBoxMat () const
G4int getNBox () const
G4double getDy_2Box () const
G4double getDx_2Box () const
G4double getWallThickBox () const
G4double getXposBox (unsigned int i) const
G4int getNLayerScnt () const
G4int getTypeScnt (unsigned int i) const
G4int getMotherScnt (unsigned int i) const
G4double getXposScnt (unsigned int i) const
G4int getNLayerAbs () const
G4int getTypeAbs (unsigned int i) const
G4int getMotherAbs (unsigned int i) const
G4double getXposAbs (unsigned int i) const
G4String getAbsMat () const
G4int getNAbsorber () const
G4double getDy_2Abs () const
G4double getDx_2Abs (unsigned int i) const
G4String getScntMat () const
G4String getWrapMat () const
G4String getPlasMat () const
G4int getNScintillator () const
G4double getDy_2ScntLay (unsigned int i) const
G4double getDx_2ScntLay (unsigned int i) const
G4double getDx_2Wrap (unsigned int i) const
G4double getDx_2FrontP (unsigned int i) const
G4double getDx_2BackP (unsigned int i) const
G4double getDx_2Scnt (unsigned int i) const
Public Member Functions inherited from CCalDetector
CCalDetector (const G4String &name)
virtual ~CCalDetector ()
void constructHierarchy ()
void construct ()
void addDetector (CCalDetector *)
G4String Name () const
G4String baseFileName () const
G4String File () const
CCalDetector * getDaughter (G4int i) const
G4int getNDaughters () const
G4bool operator== (const CCalDetector &left) const
G4bool operator!= (const CCalDetector &left) const
Public Member Functions inherited from CCalG4Able
CCalG4Able (G4String name)
virtual ~CCalG4Able ()
G4VPhysicalVolume * PhysicalVolume (G4VPhysicalVolume *)
void setVisType (CCalVisualisable::visType, G4LogicalVolume *)
void setSensitivity (G4bool sens=true)
G4bool isSensitive () const
G4String G4Name () const
void setName (const G4String &name)
G4bool operator== (const CCalG4Able &right) const
Protected Member Functions
virtual G4VPhysicalVolume * constructIn (G4VPhysicalVolume *)
virtual void constructDaughters ()
G4LogicalVolume * constructScintillatorLayer (G4int)
G4LogicalVolume * constructAbsorberLayer (G4int)
virtual void constructSensitive ()
Protected Member Functions inherited from CCalHcal
virtual G4int readFile ()
Protected Member Functions inherited from CCalDetector
G4int buildFromFile ()
Protected Member Functions inherited from CCalG4Able
void AddCCalG4Able (CCalG4Able *)
Private Attributes
ptrG4Log * sclLog
ptrG4Log * absLog
std::vector< ptrG4Log > allSensitiveLogs
Additional Inherited Members
Protected Attributes inherited from CCalDetector
G4String detectorName
G4String fileName
G4String pathName
CCalDetectorTable theDetectorsInside
G4int constructFlag
Protected Attributes inherited from CCalG4Able
G4VPhysicalVolume * detPhysicalVolume
CCalG4AbleTable theG4DetectorsInside
G4String g4ableName
G4bool sensitivity
CCalVisualisable visProperties
G4VisAttributes * g4VisAtt [CCalVisualisable::TotalVisTypes]
Detailed Description
Definition at line 40 of file CCalG4Hcal.hh.
View newest version in sPHENIX GitHub at line 40 of file CCalG4Hcal.hh
Constructor & Destructor Documentation
CCalG4Hcal::CCalG4Hcal (const G4String & name)
Definition at line 57 of file CCalG4Hcal.cc.
View newest version in sPHENIX GitHub at line 57 of file CCalG4Hcal.cc
CCalG4Hcal::~CCalG4Hcal () virtual
Definition at line 60 of file CCalG4Hcal.cc.
View newest version in sPHENIX GitHub at line 60 of file CCalG4Hcal.cc
References absLog, and sclLog.
Member Function Documentation
G4LogicalVolume * CCalG4Hcal::constructAbsorberLayer (G4int lay) protected
Definition at line 320 of file CCalG4Hcal.cc.
View newest version in sPHENIX GitHub at line 320 of file CCalG4Hcal.cc
References CCalVisualisable::Absorber, CCalMaterialFactory::findMaterial(), G4cout, G4endl, CCalHcal::getAbsMat(), CCalHcal::getDx_2Abs(), CCalHcal::getDy_2Abs(), CCalMaterialFactory::getInstance(), mm, CCalDetector::Name(), CCalG4Able::setVisType(), and tab().
Referenced by constructIn().
void CCalG4Hcal::constructDaughters () protected virtual
Reimplemented from CCalHcal.
Definition at line 361 of file CCalG4Hcal.cc.
View newest version in sPHENIX GitHub at line 361 of file CCalG4Hcal.cc
G4VPhysicalVolume * CCalG4Hcal::constructIn (G4VPhysicalVolume * mother) protected virtual
Implements CCalG4Able.
Definition at line 71 of file CCalG4Hcal.cc.
View newest version in sPHENIX GitHub at line 71 of file CCalG4Hcal.cc
References absLog, constructAbsorberLayer(), constructScintillatorLayer(), CCalMaterialFactory::findMaterial(), G4cout, G4endl, CCalHcal::getBoxMat(), CCalHcal::getDx_2Box(), CCalHcal::getDx_2Cal(), CCalHcal::getDy_2Box(), CCalHcal::getDy_2Cal(), CCalHcal::getGenMat(), CCalMaterialFactory::getInstance(), CCalHcal::getMotherAbs(), CCalHcal::getMotherScnt(), CCalHcal::getNAbsorber(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), CCalHcal::getNBox(), CCalHcal::getNLayerAbs(), CCalHcal::getNLayerScnt(), CCalHcal::getNScintillator(), CCalHcal::getTypeAbs(), CCalHcal::getTypeScnt(), CCalHcal::getWallThickBox(), CCalHcal::getXposAbs(), CCalHcal::getXposBox(), CCalHcal::getXposCal(), CCalHcal::getXposScnt(), mm, CCalDetector::Name(), CCalVisualisable::PseudoVolumes, sclLog, CCalG4Able::setVisType(), CCalVisualisable::Support, and tab().
G4LogicalVolume * CCalG4Hcal::constructScintillatorLayer (G4int lay) protected
Definition at line 211 of file CCalG4Hcal.cc.
View newest version in sPHENIX GitHub at line 211 of file CCalG4Hcal.cc
References allSensitiveLogs, CCalVisualisable::Cable, CCalMaterialFactory::findMaterial(), G4cout, G4endl, CCalHcal::getDx_2BackP(), CCalHcal::getDx_2FrontP(), CCalHcal::getDx_2Scnt(), CCalHcal::getDx_2ScntLay(), CCalHcal::getDx_2Wrap(), CCalHcal::getDy_2ScntLay(), CCalHcal::getGenMat(), CCalMaterialFactory::getInstance(), G4LogicalVolume::GetName(), CCalHcal::getPlasMat(), CCalHcal::getScntMat(), CCalHcal::getWrapMat(), mm, CCalDetector::Name(), CCalVisualisable::PseudoVolumes, CCalVisualisable::Sensitive, CCalG4Able::setVisType(), CCalVisualisable::Support, and tab().
Referenced by constructIn().
void CCalG4Hcal::constructSensitive () protected virtual
Reimplemented from CCalG4Able.
Definition at line 342 of file CCalG4Hcal.cc.
View newest version in sPHENIX GitHub at line 342 of file CCalG4Hcal.cc
References allSensitiveLogs, G4cerr, G4cout, G4endl, CCalSensitiveDetectors::getInstance(), CCalDetector::Name(), and CCalSensitiveDetectors::registerVolume().
Member Data Documentation
ptrG4Log* CCalG4Hcal::absLog private
Definition at line 62 of file CCalG4Hcal.hh.
View newest version in sPHENIX GitHub at line 62 of file CCalG4Hcal.hh
Referenced by constructIn(), and ~CCalG4Hcal().
std::vector<ptrG4Log> CCalG4Hcal::allSensitiveLogs private
Definition at line 65 of file CCalG4Hcal.hh.
View newest version in sPHENIX GitHub at line 65 of file CCalG4Hcal.hh
Referenced by constructScintillatorLayer(), and constructSensitive().
ptrG4Log* CCalG4Hcal::sclLog private
Definition at line 61 of file CCalG4Hcal.hh.
View newest version in sPHENIX GitHub at line 61 of file CCalG4Hcal.hh
Referenced by constructIn(), and ~CCalG4Hcal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Hcal.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalG4Hcal.cc