ECCE @ EIC Software: G4KineticTrack Class Reference
G4KineticTrack Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4KineticTrack.hh>
Public Types
enum CascadeState {
undefined, outside, going_in, inside,
going_out, gone_out, captured, miss_nucleus
}
Public Member Functions
G4KineticTrack ()
G4KineticTrack (const G4KineticTrack &right)
G4KineticTrack (const G4ParticleDefinition *aDefinition, G4double aFormationTime, const G4ThreeVector &aPosition, const G4LorentzVector &a4Momentum)
G4KineticTrack (G4Nucleon *nucleon, const G4ThreeVector &aPosition, const G4LorentzVector &a4Momentum)
~G4KineticTrack ()
G4KineticTrack & operator= (const G4KineticTrack &right)
G4bool operator== (const G4KineticTrack &right) const
G4bool operator!= (const G4KineticTrack &right) const
const G4ParticleDefinition * GetDefinition () const
void SetDefinition (const G4ParticleDefinition *aDefinition)
G4double GetFormationTime () const
void SetFormationTime (G4double aFormationTime)
const G4ThreeVector & GetPosition () const
void SetPosition (const G4ThreeVector aPosition)
const G4LorentzVector & Get4Momentum () const
void Set4Momentum (const G4LorentzVector &a4Momentum)
void Update4Momentum (G4double aEnergy)
void Update4Momentum (const G4ThreeVector &aMomentum)
void SetTrackingMomentum (const G4LorentzVector &a4Momentum)
void UpdateTrackingMomentum (G4double aEnergy)
void UpdateTrackingMomentum (const G4ThreeVector &aMomentum)
const G4LorentzVector & GetTrackingMomentum () const
G4double SampleResidualLifetime ()
void Hit ()
void SetNucleon (G4Nucleon *aN)
G4bool IsParticipant () const
G4KineticTrackVector * Decay ()
G4double * GetActualWidth () const
G4double GetActualMass () const
G4int GetnChannels () const
CascadeState SetState (const CascadeState new_state)
CascadeState GetState () const
void SetProjectilePotential (const G4double aPotential)
G4double GetProjectilePotential () const
G4double BrWig (const G4double Gamma, const G4double rmass, const G4double mass) const
Public Member Functions inherited from G4VKineticNucleon
G4VKineticNucleon ()
G4VKineticNucleon (const G4VKineticNucleon &right)
virtual ~G4VKineticNucleon ()
const G4VKineticNucleon & operator= (const G4VKineticNucleon &right)
G4bool operator== (const G4VKineticNucleon &right) const
G4bool operator!= (const G4VKineticNucleon &right) const
Private Member Functions
void SetnChannels (const G4int aChannel)
void SetActualWidth (G4double *anActualWidth)
G4double EvaluateTotalActualWidth ()
G4double EvaluateCMMomentum (const G4double mass, const G4double *m_ij) const
G4double IntegrateCMMomentum (const G4double lowerLimit) const
G4double IntegrateCMMomentum (const G4double lowerLimit, const G4double polemass) const
G4double IntegrateCMMomentum2 () const
G4double IntegrandFunction1 (G4double xmass) const
G4double IntegrandFunction2 (G4double xmass) const
G4double IntegrandFunction3 (G4double xmass) const
G4double IntegrandFunction4 (G4double xmass) const
Private Attributes
const G4ParticleDefinition * theDefinition
G4double theFormationTime
G4ThreeVector thePosition
G4LorentzVector the4Momentum
G4LorentzVector theFermi3Momentum
G4LorentzVector theTotal4Momentum
G4Nucleon * theNucleon
G4int nChannels
G4double theActualMass
G4double * theActualWidth
G4double * theDaughterMass
G4double * theDaughterWidth
CascadeState theStateToNucleus
G4double theProjectilePotential
Detailed Description
Definition at line 56 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 56 of file G4KineticTrack.hh
Member Enumeration Documentation
enum G4KineticTrack::CascadeState
Enumerator:
undefined
outside
going_in
inside
going_out
gone_out
captured
miss_nucleus
Definition at line 118 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 118 of file G4KineticTrack.hh
Constructor & Destructor Documentation
G4KineticTrack::G4KineticTrack ()
Definition at line 67 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 67 of file G4KineticTrack.cc
G4KineticTrack::G4KineticTrack (const G4KineticTrack & right)
Definition at line 100 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 100 of file G4KineticTrack.cc
References GetActualMass(), GetDefinition(), GetFormationTime(), GetnChannels(), GetPosition(), GetTrackingMomentum(), nChannels, the4Momentum, theActualMass, theActualWidth, theDaughterMass, theDaughterWidth, theDefinition, theFermi3Momentum, theFormationTime, theNucleon, thePosition, theProjectilePotential, theStateToNucleus, and theTotal4Momentum.
G4KineticTrack::G4KineticTrack (const G4ParticleDefinition * aDefinition, G4double aFormationTime, const G4ThreeVector & aPosition, const G4LorentzVector & a4Momentum)
Definition at line 138 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 138 of file G4KineticTrack.cc
References G4AntiKaonZero::AntiKaonZero(), G4DecayTable::entries(), EvaluateCMMomentum(), G4KineticTrack_Gmass, G4SwapObj(), G4UniformRand, GetActualMass(), G4VDecayChannel::GetBR(), G4VDecayChannel::GetDaughter(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4SampleResonance::GetMinimumMass(), G4VDecayChannel::GetNumberOfDaughters(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGWidth(), IntegrateCMMomentum(), IntegrateCMMomentum2(), G4ParticleDefinition::IsShortLived(), G4KaonZero::KaonZero(), G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), n, nChannels, theActualMass, theActualWidth, theDaughterMass, theDaughterWidth, and theDefinition.
G4KineticTrack::G4KineticTrack (G4Nucleon * nucleon, const G4ThreeVector & aPosition, const G4LorentzVector & a4Momentum)
Definition at line 416 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 416 of file G4KineticTrack.cc
References Set4Momentum(), CLHEP::HepLorentzVector::setE(), and theFermi3Momentum.
G4KineticTrack::~G4KineticTrack ()
Definition at line 438 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 438 of file G4KineticTrack.cc
References theActualWidth, theDaughterMass, and theDaughterWidth.
Member Function Documentation
G4double G4KineticTrack::BrWig (const G4double Gamma, const G4double rmass, const G4double mass) const inline
Definition at line 378 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 378 of file G4KineticTrack.hh
References CLHEP::twopi.
Referenced by IntegrandFunction1(), IntegrandFunction2(), IntegrandFunction3(), and IntegrandFunction4().
G4KineticTrackVector * G4KineticTrack::Decay () virtual
Reimplemented from G4VKineticNucleon.
Definition at line 486 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 486 of file G4KineticTrack.cc
References G4GeneralPhaseSpaceDecay::DecayIt(), G4DecayProducts::entries(), EvaluateTotalActualWidth(), G4cerr, G4endl, G4Exception(), G4lrint(), G4UniformRand, Get4Momentum(), G4DynamicParticle::Get4Momentum(), GetActualMass(), G4ParticleDefinition::GetBaryonNumber(), G4VDecayChannel::GetDaughter(), G4VDecayChannel::GetDaughterName(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), GetDefinition(), G4DynamicParticle::GetDefinition(), G4SampleResonance::GetMinimumMass(), G4VDecayChannel::GetNumberOfDaughters(), G4VDecayChannel::GetParentName(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), GetPosition(), G4ParticleDefinition::IsShortLived(), JustWarning, momentum, nChannels, one, G4DecayProducts::PopProducts(), r, G4SampleResonance::SampleMass(), theActualWidth, theDefinition, and zero.
Referenced by G4LMsdGenerator::ApplyYourself(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4DecayKineticTracks::Decay(), G4NeutrinoNucleusModel::FinalBarion(), G4NeutrinoNucleusModel::FinalMeson(), and G4BCDecay::GetFinalState().
G4double G4KineticTrack::EvaluateCMMomentum (const G4double mass, const G4double * m_ij) const inline private
Definition at line 364 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 364 of file G4KineticTrack.hh
References mass.
Referenced by G4KineticTrack().
G4double G4KineticTrack::EvaluateTotalActualWidth () inline private
Definition at line 345 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 345 of file G4KineticTrack.hh
References nChannels, and theActualWidth.
Referenced by Decay(), and SampleResidualLifetime().
const G4LorentzVector & G4KineticTrack::Get4Momentum () const inline virtual
Implements G4VKineticNucleon.
Definition at line 239 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 239 of file G4KineticTrack.hh
References theTotal4Momentum.
Referenced by G4MesonAbsorption::AbsorptionCrossSection(), G4CollisionManager::AddCollision(), G4BinaryCascade::ApplyCollision(), G4KineticTrackVector::Boost(), G4KineticTrackVector::BoostBeam(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4BinaryCascade::Capture(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4XpimNTotal::CrossSection(), G4XpipNTotal::CrossSection(), G4XNNTotalLowE::CrossSection(), G4XNNElasticLowE::CrossSection(), G4CollisionNN::CrossSection(), G4XResonance::CrossSection(), G4XAnnihilationChannel::CrossSection(), G4XMesonBaryonElastic::CrossSection(), G4CrossSectionPatch::CrossSection(), G4XnpElasticLowE::CrossSection(), G4XnpTotalLowE::CrossSection(), G4CrossSectionComposite::CrossSection(), G4XPDGElastic::CrossSection(), G4CrossSectionBuffer::CrossSection(), G4XPDGTotal::CrossSection(), G4BinaryCascade::DebugApplyCollision(), Decay(), G4VXResonance::DetailedBalance(), G4BinaryCascade::FillVoidNucleusProducts(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4VAnnihilationCollision::FinalState(), G4BinaryCascade::FindLateParticleCollision(), G4Absorber::FindProducts(), G4QGSMFragmentation::FragmentString(), G4ExcitedString::Get4Momentum(), G4MesonAbsorption::GetFinalState(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4RKFieldIntegrator::Integrate(), G4BinaryLightIonReaction::Interact(), G4LundStringFragmentation::Loop_toFragmentString(), G4ExcitedString::LorentzRotate(), G4GeneratorPrecompoundInterface::MakeCoalescence(), G4VCrossSectionSource::PrintAll(), G4BinaryCascade::PrintKTVector(), G4IntraNucleiCascader::processSecondary(), G4BinaryCascade::ProductsAddFinalState(), G4DecayStrongResonances::Propagate(), G4CascadeInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4IntraNucleiCascader::releaseSecondary(), G4Scatterer::Scatter(), G4CrossSectionPatch::Transition(), G4XAnnihilationChannel::VariablePartialWidth(), G4XAnnihilationChannel::VariableWidth(), and G4Absorber::WillBeAbsorbed().
G4double G4KineticTrack::GetActualMass () const inline
Definition at line 318 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 318 of file G4KineticTrack.hh
References kdfinder::abs(), CLHEP::HepLorentzVector::mag2(), and the4Momentum.
Referenced by G4BinaryCascade::Capture(), G4CollisionNN::CrossSection(), Decay(), G4RKPropagation::FieldTransport(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4KineticTrack(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4RKPropagation::Transport(), and G4Absorber::WillBeAbsorbed().
G4double * G4KineticTrack::GetActualWidth () const inline
Definition at line 333 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 333 of file G4KineticTrack.hh
References theActualWidth.
const G4ParticleDefinition * G4KineticTrack::GetDefinition () const inline virtual
Implements G4VKineticNucleon.
Definition at line 209 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 209 of file G4KineticTrack.hh
References theDefinition.
Referenced by G4MesonAbsorption::AbsorptionCrossSection(), G4CollisionManager::AddCollision(), G4BinaryCascade::ApplyCollision(), G4KineticTrackVector::BoostBeam(), G4CollisionComposite::BufferedCrossSection(), G4RKFieldIntegrator::CalculateTotalEnergy(), G4BinaryCascade::Capture(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4XAqmTotal::CrossSection(), G4CollisionNN::CrossSection(), G4XResonance::CrossSection(), G4XAnnihilationChannel::CrossSection(), G4XnpElasticLowE::CrossSection(), G4XnpTotalLowE::CrossSection(), G4CollisionComposite::CrossSection(), G4XPDGElastic::CrossSection(), G4XPDGTotal::CrossSection(), G4BinaryCascade::DebugApplyCollision(), G4BinaryCascade::DebugApplyCollisionFail(), G4DecayKineticTracks::Decay(), Decay(), G4VXResonance::DegeneracyFactor(), G4VXResonance::DetailedBalance(), G4RKPropagation::FieldTransport(), G4BinaryCascade::FillVoidNucleusProducts(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), G4Absorber::FindAbsorbers(), G4MesonAbsorption::FindAndFillCluster(), G4VCrossSectionSource::FindKeyParticle(), G4BinaryCascade::FindLateParticleCollision(), G4VCrossSectionSource::FindLightParticle(), G4Absorber::FindProducts(), G4QGSMFragmentation::FragmentString(), G4ExcitedStringDecay::FragmentStrings(), G4KineticTrack(), G4BCDecay::GetCollisions(), G4MesonAbsorption::GetFinalState(), G4ParticleTypeConverter::GetGenericType(), G4ConcreteMesonBaryonToResonance::GetOutgoingParticle(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4GeneralNNCollision::IsInCharge(), G4CollisionnpElastic::IsInCharge(), G4CollisionMesonBaryonElastic::IsInCharge(), G4CollisionNNElastic::IsInCharge(), G4ConcreteNNTwoBodyResonance::IsInCharge(), G4VXResonance::IsospinCorrection(), G4LundStringFragmentation::Loop_toFragmentString(), G4GeneratorPrecompoundInterface::MakeCoalescence(), G4XAnnihilationChannel::NormalizedClebsch(), operator=(), G4CollisionManager::Print(), G4CollisionInitialState::Print(), G4BinaryCascade::PrintKTVector(), G4IntraNucleiCascader::processSecondary(), G4BinaryCascade::ProductsAddFinalState(), G4DecayStrongResonances::Propagate(), G4CascadeInterface::Propagate(), G4BinaryCascade::Propagate1H1(), G4IntraNucleiCascader::releaseSecondary(), G4Scatterer::Scatter(), G4BinaryCascade::StepParticlesOut(), G4RKPropagation::Transport(), and G4Absorber::WillBeAbsorbed().
G4double G4KineticTrack::GetFormationTime () const inline
Definition at line 219 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 219 of file G4KineticTrack.hh
References theFormationTime.
Referenced by G4XMesonBaryonElastic::CrossSection(), G4QGSMFragmentation::FragmentString(), G4ExcitedString::G4ExcitedString(), G4KineticTrack(), G4BCLateParticle::GetCollisions(), G4LundStringFragmentation::Loop_toFragmentString(), G4GeneratorPrecompoundInterface::MakeCoalescence(), operator=(), and G4CascadeInterface::Propagate().
G4int G4KineticTrack::GetnChannels () const inline
Definition at line 323 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 323 of file G4KineticTrack.hh
References nChannels.
Referenced by G4KineticTrack(), and operator=().
const G4ThreeVector & G4KineticTrack::GetPosition (void) const inline virtual
Implements G4VKineticNucleon.
Definition at line 229 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 229 of file G4KineticTrack.hh
References thePosition.
Referenced by G4RKFieldIntegrator::CalculateTotalEnergy(), G4BinaryCascade::Capture(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4XMesonBaryonElastic::CrossSection(), G4BinaryCascade::DebugApplyCollision(), Decay(), G4RKPropagation::FieldTransport(), G4VAnnihilationCollision::FinalState(), G4VScatteringCollision::FinalState(), G4Absorber::FindAbsorbers(), G4MesonAbsorption::FindAndFillCluster(), G4Absorber::FindProducts(), G4QGSMFragmentation::FragmentString(), G4RKPropagation::FreeTransport(), G4ExcitedString::G4ExcitedString(), G4KineticTrack(), G4RKPropagation::GetSphereIntersectionTimes(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), G4RKFieldIntegrator::Integrate(), G4LundStringFragmentation::Loop_toFragmentString(), G4GeneratorPrecompoundInterface::MakeCoalescence(), G4BinaryCascade::PrintKTVector(), G4IntraNucleiCascader::processSecondary(), G4CascadeInterface::Propagate(), G4KineticTrackVector::Shift(), and G4RKPropagation::Transport().
G4double G4KineticTrack::GetProjectilePotential () const inline
Definition at line 420 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 420 of file G4KineticTrack.hh
References theProjectilePotential.
Referenced by G4RKPropagation::Transport().
G4KineticTrack::CascadeState G4KineticTrack::GetState () const inline
Definition at line 401 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 401 of file G4KineticTrack.hh
References theStateToNucleus.
Referenced by G4BinaryCascade::Absorb(), G4BinaryCascade::ApplyCollision(), G4BinaryCascade::Capture(), G4BinaryCascade::CorrectShortlivedPrimaryForFermi(), G4BinaryCascade::FindLateParticleCollision(), G4BinaryCascade::PrintKTVector(), G4BinaryCascade::StepParticlesOut(), and G4RKPropagation::Transport().
const G4LorentzVector & G4KineticTrack::GetTrackingMomentum () const inline
Definition at line 244 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 244 of file G4KineticTrack.hh
References the4Momentum.
Referenced by G4BinaryCascade::ApplyCollision(), G4RKPropagation::FieldTransport(), G4RKPropagation::FreeTransport(), G4KineticTrack(), G4RKPropagation::GetSphereIntersectionTimes(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), operator=(), G4BinaryCascade::PrintKTVector(), G4BinaryCascade::StepParticlesOut(), and G4RKPropagation::Transport().
void G4KineticTrack::Hit () inline
Definition at line 385 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 385 of file G4KineticTrack.hh
References G4Nucleon::Hit(), and theNucleon.
Referenced by G4BinaryCascade::ApplyCollision(), and G4BinaryCascade::Capture().
G4double G4KineticTrack::IntegrandFunction1 (G4double xmass) const private
Definition at line 744 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 744 of file G4KineticTrack.cc
References BrWig(), mass, max, theActualMass, theDaughterMass, and theDaughterWidth.
Referenced by IntegrateCMMomentum().
G4double G4KineticTrack::IntegrandFunction2 (G4double xmass) const private
Definition at line 758 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 758 of file G4KineticTrack.cc
References BrWig(), G4ParticleDefinition::GetPDGMass(), mass, max, theDaughterMass, theDaughterWidth, and theDefinition.
Referenced by IntegrateCMMomentum().
G4double G4KineticTrack::IntegrandFunction3 (G4double xmass) const private
Definition at line 771 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 771 of file G4KineticTrack.cc
References BrWig(), G4KineticTrack_Gmass, G4KineticTrack_xmass1, mass, theDaughterMass, and theDaughterWidth.
Referenced by IntegrandFunction4().
G4double G4KineticTrack::IntegrandFunction4 (G4double xmass) const private
Definition at line 785 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 785 of file G4KineticTrack.cc
References BrWig(), G4KineticTrack_Gmass, G4KineticTrack_xmass1, IntegrandFunction3(), mass, G4Integrator< T, F >::Simpson(), theDaughterMass, and theDaughterWidth.
Referenced by IntegrateCMMomentum2().
G4double G4KineticTrack::IntegrateCMMomentum (const G4double lowerLimit) const private
Definition at line 805 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 805 of file G4KineticTrack.cc
References IntegrandFunction1(), G4Integrator< T, F >::Simpson(), theActualMass, and theDaughterMass.
Referenced by G4KineticTrack().
G4double G4KineticTrack::IntegrateCMMomentum (const G4double lowerLimit, const G4double polemass) const private
Definition at line 818 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 818 of file G4KineticTrack.cc
References IntegrandFunction2(), G4Integrator< T, F >::Simpson(), and theDaughterMass.
G4double G4KineticTrack::IntegrateCMMomentum2 () const private
Definition at line 832 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 832 of file G4KineticTrack.cc
References IntegrandFunction4(), G4Integrator< T, F >::Simpson(), and theActualMass.
Referenced by G4KineticTrack().
G4bool G4KineticTrack::IsParticipant () const inline
Definition at line 394 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 394 of file G4KineticTrack.hh
References G4Nucleon::AreYouHit(), and theNucleon.
Referenced by G4BinaryCascade::PrintKTVector(), and G4BinaryCascade::ProductsAddFinalState().
G4bool G4KineticTrack::operator!= (const G4KineticTrack & right) const
Definition at line 479 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 479 of file G4KineticTrack.cc
G4KineticTrack & G4KineticTrack::operator= (const G4KineticTrack & right)
Definition at line 447 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 447 of file G4KineticTrack.cc
References GetDefinition(), GetFormationTime(), GetnChannels(), GetTrackingMomentum(), nChannels, the4Momentum, theActualWidth, theDefinition, theFermi3Momentum, theFormationTime, theNucleon, theStateToNucleus, and theTotal4Momentum.
G4bool G4KineticTrack::operator== (const G4KineticTrack & right) const
Definition at line 472 of file G4KineticTrack.cc.
View newest version in sPHENIX GitHub at line 472 of file G4KineticTrack.cc
G4double G4KineticTrack::SampleResidualLifetime () inline
Definition at line 356 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 356 of file G4KineticTrack.hh
References EvaluateTotalActualWidth(), G4Log(), G4UniformRand, CLHEP::HepLorentzVector::gamma(), CLHEP::hbar_Planck, and the4Momentum.
Referenced by G4BCDecay::GetCollisions().
void G4KineticTrack::Set4Momentum (const G4LorentzVector & a4Momentum) inline
Definition at line 249 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 249 of file G4KineticTrack.hh
References the4Momentum, theFermi3Momentum, and theTotal4Momentum.
Referenced by G4BinaryCascade::ApplyCollision(), G4KineticTrackVector::Boost(), G4KineticTrackVector::BoostBeam(), G4CollisionNN::CrossSection(), G4VElasticCollision::FinalState(), G4QGSMFragmentation::FragmentString(), G4KineticTrack(), G4LundStringFragmentation::Loop_toFragmentString(), G4ExcitedString::LorentzRotate(), G4ExcitedString::TransformToCenterOfMass(), and Update4Momentum().
void G4KineticTrack::SetActualWidth (G4double * anActualWidth) inline private
Definition at line 338 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 338 of file G4KineticTrack.hh
References theActualWidth.
void G4KineticTrack::SetDefinition (const G4ParticleDefinition * aDefinition) inline
Definition at line 214 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 214 of file G4KineticTrack.hh
References theDefinition.
void G4KineticTrack::SetFormationTime (G4double aFormationTime) inline
Definition at line 224 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 224 of file G4KineticTrack.hh
References theFormationTime.
Referenced by G4QGSMFragmentation::FragmentString(), and G4LundStringFragmentation::Loop_toFragmentString().
void G4KineticTrack::SetnChannels (const G4int aChannel) inline private
Definition at line 328 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 328 of file G4KineticTrack.hh
References nChannels.
void G4KineticTrack::SetNucleon (G4Nucleon * aN) inline
Definition at line 105 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 105 of file G4KineticTrack.hh
References theNucleon.
Referenced by G4BinaryCascade::BuildTargetList().
void G4KineticTrack::SetPosition (const G4ThreeVector aPosition) inline
Definition at line 234 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 234 of file G4KineticTrack.hh
References thePosition.
Referenced by G4RKPropagation::FieldTransport(), G4QGSMFragmentation::FragmentString(), G4ExcitedStringDecay::FragmentStrings(), G4RKPropagation::FreeTransport(), G4RKFieldIntegrator::Integrate(), G4LundStringFragmentation::Loop_toFragmentString(), and G4KineticTrackVector::Shift().
void G4KineticTrack::SetProjectilePotential (const G4double aPotential) inline
Definition at line 415 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 415 of file G4KineticTrack.hh
References theProjectilePotential.
Referenced by G4BinaryLightIonReaction::Interact().
G4KineticTrack::CascadeState G4KineticTrack::SetState (const CascadeState new_state) inline
Definition at line 407 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 407 of file G4KineticTrack.hh
References theStateToNucleus.
Referenced by G4BinaryCascade::ApplyYourself(), G4BinaryCascade::BuildTargetList(), G4BinaryCascade::FindLateParticleCollision(), G4BinaryLightIonReaction::Interact(), and G4RKPropagation::Transport().
void G4KineticTrack::SetTrackingMomentum (const G4LorentzVector & a4Momentum) inline
Definition at line 282 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 282 of file G4KineticTrack.hh
References CLHEP::Hep3Vector::mag2(), CLHEP::HepLorentzVector::mag2(), CLHEP::HepLorentzVector::setE(), the4Momentum, theFermi3Momentum, theTotal4Momentum, and CLHEP::HepLorentzVector::vect().
Referenced by G4RKPropagation::FieldTransport(), G4RKPropagation::Transport(), and UpdateTrackingMomentum().
void G4KineticTrack::Update4Momentum (G4double aEnergy) inline
Definition at line 258 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 258 of file G4KineticTrack.hh
References CLHEP::HepLorentzVector::mag2(), Set4Momentum(), sqr(), the4Momentum, theTotal4Momentum, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
Referenced by G4BinaryCascade::CorrectShortlivedPrimaryForFermi().
void G4KineticTrack::Update4Momentum (const G4ThreeVector & aMomentum) inline
Definition at line 274 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 274 of file G4KineticTrack.hh
References CLHEP::Hep3Vector::mag2(), CLHEP::HepLorentzVector::mag2(), Set4Momentum(), and theTotal4Momentum.
void G4KineticTrack::UpdateTrackingMomentum (G4double aEnergy) inline
Definition at line 294 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 294 of file G4KineticTrack.hh
References CLHEP::HepLorentzVector::mag2(), SetTrackingMomentum(), sqr(), the4Momentum, theTotal4Momentum, CLHEP::Hep3Vector::unit(), and CLHEP::HepLorentzVector::vect().
void G4KineticTrack::UpdateTrackingMomentum (const G4ThreeVector & aMomentum) inline
Definition at line 310 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 310 of file G4KineticTrack.hh
References CLHEP::Hep3Vector::mag2(), CLHEP::HepLorentzVector::mag2(), SetTrackingMomentum(), and theTotal4Momentum.
Member Data Documentation
G4int G4KineticTrack::nChannels private
Definition at line 175 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 175 of file G4KineticTrack.hh
Referenced by Decay(), EvaluateTotalActualWidth(), G4KineticTrack(), GetnChannels(), operator=(), and SetnChannels().
G4LorentzVector G4KineticTrack::the4Momentum private
Definition at line 169 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 169 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), GetActualMass(), GetTrackingMomentum(), operator=(), SampleResidualLifetime(), Set4Momentum(), SetTrackingMomentum(), Update4Momentum(), and UpdateTrackingMomentum().
G4double G4KineticTrack::theActualMass private
Definition at line 177 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 177 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), IntegrandFunction1(), IntegrateCMMomentum(), and IntegrateCMMomentum2().
G4double* G4KineticTrack::theActualWidth private
Definition at line 179 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 179 of file G4KineticTrack.hh
Referenced by Decay(), EvaluateTotalActualWidth(), G4KineticTrack(), GetActualWidth(), operator=(), SetActualWidth(), and ~G4KineticTrack().
G4double* G4KineticTrack::theDaughterMass private
Definition at line 183 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 183 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), IntegrandFunction1(), IntegrandFunction2(), IntegrandFunction3(), IntegrandFunction4(), IntegrateCMMomentum(), and ~G4KineticTrack().
G4double* G4KineticTrack::theDaughterWidth private
Definition at line 184 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 184 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), IntegrandFunction1(), IntegrandFunction2(), IntegrandFunction3(), IntegrandFunction4(), and ~G4KineticTrack().
const G4ParticleDefinition* G4KineticTrack::theDefinition private
Definition at line 163 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 163 of file G4KineticTrack.hh
Referenced by Decay(), G4KineticTrack(), GetDefinition(), IntegrandFunction2(), operator=(), and SetDefinition().
G4LorentzVector G4KineticTrack::theFermi3Momentum private
Definition at line 170 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 170 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), operator=(), Set4Momentum(), and SetTrackingMomentum().
G4double G4KineticTrack::theFormationTime private
Definition at line 165 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 165 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), GetFormationTime(), operator=(), and SetFormationTime().
G4Nucleon* G4KineticTrack::theNucleon private
Definition at line 173 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 173 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), Hit(), IsParticipant(), operator=(), and SetNucleon().
G4ThreeVector G4KineticTrack::thePosition private
Definition at line 167 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 167 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), GetPosition(), and SetPosition().
G4double G4KineticTrack::theProjectilePotential private
Definition at line 188 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 188 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), GetProjectilePotential(), and SetProjectilePotential().
CascadeState G4KineticTrack::theStateToNucleus private
Definition at line 186 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 186 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), GetState(), operator=(), and SetState().
G4LorentzVector G4KineticTrack::theTotal4Momentum private
Definition at line 171 of file G4KineticTrack.hh.
View newest version in sPHENIX GitHub at line 171 of file G4KineticTrack.hh
Referenced by G4KineticTrack(), Get4Momentum(), operator=(), Set4Momentum(), SetTrackingMomentum(), Update4Momentum(), and UpdateTrackingMomentum().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4KineticTrack.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4KineticTrack.cc