ECCE @ EIC Software: B2bChamberParameterisation Class Reference
B2bChamberParameterisation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/include/B2bChamberParameterisation.hh>
Public Member Functions
B2bChamberParameterisation (G4int noChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
virtual ~B2bChamberParameterisation ()
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Tubs &trackerLayer, const G4int copyNo, const G4VPhysicalVolume *physVol) const
B2bChamberParameterisation (G4int noChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
virtual ~B2bChamberParameterisation ()
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Tubs &trackerLayer, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4int fNoChambers
G4double fStartZ
G4double fHalfWidth
G4double fSpacing
G4double fRmaxFirst
G4double fRmaxIncr
Detailed Description
A parameterisation that describes a series of boxes along Z.
The boxes have equal width, & their lengths are a linear equation. They are spaced an equal distance apart, starting from given location.
Definition at line 58 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 58 of file B2bChamberParameterisation.hh
Constructor & Destructor Documentation
B2bChamberParameterisation::B2bChamberParameterisation (G4int noChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
Definition at line 39 of file B2bChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 39 of file B2bChamberParameterisation.cc
References FatalException, fHalfWidth, fNoChambers, fRmaxFirst, fRmaxIncr, fSpacing, fStartZ, and G4Exception().
B2bChamberParameterisation::~B2bChamberParameterisation () virtual
Definition at line 65 of file B2bChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 65 of file B2bChamberParameterisation.cc
B2bChamberParameterisation::B2bChamberParameterisation (G4int noChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
virtual B2bChamberParameterisation::~B2bChamberParameterisation () virtual
Member Function Documentation
void B2bChamberParameterisation::ComputeDimensions (G4Tubs & trackerLayer, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 83 of file B2bChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 83 of file B2bChamberParameterisation.cc
References deg, rmax(), G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), and G4Tubs::SetZHalfLength().
void B2bChamberParameterisation::ComputeDimensions (G4Tubs & trackerLayer, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
void B2bChamberParameterisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 79 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 79 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 79 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 79 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 81 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 81 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 81 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 81 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 83 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 83 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 83 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 83 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 85 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 85 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 85 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 85 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 87 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 87 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 87 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 87 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 89 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 89 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 91 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 91 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 93 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 93 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 93 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 93 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 95 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 95 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 95 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 95 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 97 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 97 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 97 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 97 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 99 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 99 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 99 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 99 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 101 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 101 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 101 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 101 of file B2bChamberParameterisation.hh
void B2bChamberParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Definition at line 71 of file B2bChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 71 of file B2bChamberParameterisation.cc
References Acts::Test::origin(), G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
void B2bChamberParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Member Data Documentation
G4double B2bChamberParameterisation::fHalfWidth private
Definition at line 108 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 108 of file B2bChamberParameterisation.hh
Referenced by B2bChamberParameterisation().
G4int B2bChamberParameterisation::fNoChambers private
Definition at line 106 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 106 of file B2bChamberParameterisation.hh
Referenced by B2bChamberParameterisation().
G4double B2bChamberParameterisation::fRmaxFirst private
Definition at line 110 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 110 of file B2bChamberParameterisation.hh
Referenced by B2bChamberParameterisation().
G4double B2bChamberParameterisation::fRmaxIncr private
Definition at line 111 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 111 of file B2bChamberParameterisation.hh
Referenced by B2bChamberParameterisation().
G4double B2bChamberParameterisation::fSpacing private
Definition at line 109 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 109 of file B2bChamberParameterisation.hh
Referenced by B2bChamberParameterisation().
G4double B2bChamberParameterisation::fStartZ private
Definition at line 107 of file B2bChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 107 of file B2bChamberParameterisation.hh
Referenced by B2bChamberParameterisation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/include/B2bChamberParameterisation.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/include/B2bChamberParameterisation.hh
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/src/B2bChamberParameterisation.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/src/B2bChamberParameterisation.cc