ECCE @ EIC Software: G4ErrorSymMatrix Class Reference
G4ErrorSymMatrix Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorSymMatrix.hh>
Classes
class G4ErrorSymMatrix_row
class G4ErrorSymMatrix_row_const
Public Member Functions
G4ErrorSymMatrix ()
G4ErrorSymMatrix (G4int p)
G4ErrorSymMatrix (G4int p, G4int)
G4ErrorSymMatrix (const G4ErrorSymMatrix &m1)
virtual ~G4ErrorSymMatrix ()
G4int num_row () const
G4int num_col () const
const G4double & operator() (G4int row, G4int col) const
G4double & operator() (G4int row, G4int col)
const G4double & fast (G4int row, G4int col) const
G4double & fast (G4int row, G4int col)
void assign (const G4ErrorMatrix &m2)
void assign (const G4ErrorSymMatrix &m2)
G4ErrorSymMatrix & operator*= (G4double t)
G4ErrorSymMatrix & operator/= (G4double t)
G4ErrorSymMatrix & operator+= (const G4ErrorSymMatrix &m2)
G4ErrorSymMatrix & operator-= (const G4ErrorSymMatrix &m2)
G4ErrorSymMatrix & operator= (const G4ErrorSymMatrix &m2)
G4ErrorSymMatrix operator- () const
G4ErrorSymMatrix T () const
G4ErrorSymMatrix apply (G4double(*f)(G4double, G4int, G4int)) const
G4ErrorSymMatrix similarity (const G4ErrorMatrix &m1) const
G4ErrorSymMatrix similarity (const G4ErrorSymMatrix &m1) const
G4ErrorSymMatrix similarityT (const G4ErrorMatrix &m1) const
G4ErrorSymMatrix sub (G4int min_row, G4int max_row) const
void sub (G4int row, const G4ErrorSymMatrix &m1)
G4ErrorSymMatrix sub (G4int min_row, G4int max_row)
G4ErrorSymMatrix inverse (G4int &ifail) const
void invert (G4int &ifail)
G4double determinant () const
G4double trace () const
G4ErrorSymMatrix_row operator[] (G4int)
G4ErrorSymMatrix_row_const operator[] (G4int) const
void invertCholesky5 (G4int &ifail)
void invertCholesky6 (G4int &ifail)
void invertHaywood4 (G4int &ifail)
void invertHaywood5 (G4int &ifail)
void invertHaywood6 (G4int &ifail)
void invertBunchKaufman (G4int &ifail)
Protected Member Functions
G4int num_size () const
Private Member Functions
void invert4 (G4int &ifail)
void invert5 (G4int &ifail)
void invert6 (G4int &ifail)
Private Attributes
std::vector< G4double > m
G4int nrow
G4int size
Static Private Attributes
static G4ThreadLocal G4double posDefFraction5x5 = 1.0
static G4ThreadLocal G4double adjustment5x5 = 0.0
static const G4double CHOLESKY_THRESHOLD_5x5 = .5
static const G4double CHOLESKY_CREEP_5x5 = .005
static G4ThreadLocal G4double posDefFraction6x6 = 1.0
static G4ThreadLocal G4double adjustment6x6 = 0.0
static const G4double CHOLESKY_THRESHOLD_6x6 = .2
static const G4double CHOLESKY_CREEP_6x6 = .002
Friends
class G4ErrorSymMatrix_row
class G4ErrorSymMatrix_row_const
class G4ErrorMatrix
void tridiagonal (G4ErrorSymMatrix *a, G4ErrorMatrix *hsm)
G4double condition (const G4ErrorSymMatrix &m)
void diag_step (G4ErrorSymMatrix *t, G4int begin, G4int end)
void diag_step (G4ErrorSymMatrix *t, G4ErrorMatrix *u, G4int begin, G4int end)
G4ErrorMatrix diagonalize (G4ErrorSymMatrix *s)
void house_with_update2 (G4ErrorSymMatrix *a, G4ErrorMatrix *v, G4int row, G4int col)
G4ErrorSymMatrix operator+ (const G4ErrorSymMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorSymMatrix operator- (const G4ErrorSymMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorSymMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorSymMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorMatrix &m1, const G4ErrorSymMatrix &m2)
Detailed Description
Definition at line 43 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ErrorSymMatrix.hh
Constructor & Destructor Documentation
G4ErrorSymMatrix::G4ErrorSymMatrix () inline
G4ErrorSymMatrix::G4ErrorSymMatrix (G4int p) explicit
Definition at line 70 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ErrorSymMatrix.cc
References m, nrow, and size.
G4ErrorSymMatrix::G4ErrorSymMatrix (G4int p, G4int init)
Definition at line 77 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ErrorSymMatrix.cc
References a, G4ErrorMatrix::error(), m, nrow, and size.
G4ErrorSymMatrix::G4ErrorSymMatrix (const G4ErrorSymMatrix & m1)
Definition at line 111 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 111 of file G4ErrorSymMatrix.cc
References m.
G4ErrorSymMatrix::~G4ErrorSymMatrix () virtual
Definition at line 107 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 107 of file G4ErrorSymMatrix.cc
Member Function Documentation
G4ErrorSymMatrix G4ErrorSymMatrix::apply (G4double(*)(G4double, G4int, G4int) f) const
Definition at line 552 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 552 of file G4ErrorSymMatrix.cc
References a, b, f, m, and num_row().
void G4ErrorSymMatrix::assign (const G4ErrorMatrix & m2)
Definition at line 567 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 567 of file G4ErrorSymMatrix.cc
References a, b, c, d, m, G4ErrorMatrix::m, nrow, G4ErrorMatrix::nrow, r, and size.
void G4ErrorSymMatrix::assign (const G4ErrorSymMatrix & m2)
G4double G4ErrorSymMatrix::determinant () const
Definition at line 798 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 798 of file G4ErrorSymMatrix.cc
References G4ErrorMatrix::dfact_matrix(), and nrow.
const G4double& G4ErrorSymMatrix::fast (G4int row, G4int col) const
G4double& G4ErrorSymMatrix::fast (G4int row, G4int col)
G4ErrorSymMatrix G4ErrorSymMatrix::inverse (G4int & ifail) const inline
void G4ErrorSymMatrix::invert (G4int & ifail)
Definition at line 682 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 682 of file G4ErrorSymMatrix.cc
References invert4(), invert5(), invert6(), invertBunchKaufman(), m, nrow, t1, and t2.
void G4ErrorSymMatrix::invert4 (G4int & ifail) private
Definition at line 2188 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 2188 of file G4ErrorSymMatrix.cc
References A00, A01, A02, A03, A10, A11, A12, A13, A20, A21, A22, A23, A30, A31, A32, A33, and m.
Referenced by invert(), and invertHaywood4().
void G4ErrorSymMatrix::invert5 (G4int & ifail) private
Definition at line 1300 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 1300 of file G4ErrorSymMatrix.cc
References adjustment5x5, CHOLESKY_CREEP_5x5, CHOLESKY_THRESHOLD_5x5, invertCholesky5(), invertHaywood5(), and posDefFraction5x5.
Referenced by invert().
void G4ErrorSymMatrix::invert6 (G4int & ifail) private
Definition at line 1332 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 1332 of file G4ErrorSymMatrix.cc
References adjustment6x6, CHOLESKY_CREEP_6x6, CHOLESKY_THRESHOLD_6x6, invertCholesky6(), invertHaywood6(), and posDefFraction6x6.
Referenced by invert().
void G4ErrorSymMatrix::invertBunchKaufman (G4int & ifail)
Definition at line 826 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 826 of file G4ErrorSymMatrix.cc
References alpha, DBL_EPSILON, epsilon(), G4Exception(), G4ThreadLocal, JustWarning, k, G4InuclParticleNames::lambda, m, message(), nrow, temp1, temp2, and x.
Referenced by invert().
void G4ErrorSymMatrix::invertCholesky5 (G4int & ifail)
Definition at line 1917 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 1917 of file G4ErrorSymMatrix.cc
References A00, A01, A02, A03, A04, A10, A11, A12, A13, A14, A20, A21, A22, A23, A24, A30, A31, A32, A33, A34, A40, A41, A42, A43, A44, h10, h11, h20, and m.
Referenced by invert5().
void G4ErrorSymMatrix::invertCholesky6 (G4int & ifail)
Definition at line 2039 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 2039 of file G4ErrorSymMatrix.cc
References A00, A01, A02, A03, A04, A05, A10, A11, A12, A13, A14, A15, A20, A21, A22, A23, A24, A25, A30, A31, A32, A33, A34, A35, A40, A41, A42, A43, A44, A45, A50, A51, A52, A53, A54, A55, h10, h11, h20, and m.
Referenced by invert6().
void G4ErrorSymMatrix::invertHaywood4 (G4int & ifail)
Definition at line 2266 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 2266 of file G4ErrorSymMatrix.cc
References invert4().
void G4ErrorSymMatrix::invertHaywood5 (G4int & ifail)
Definition at line 1364 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 1364 of file G4ErrorSymMatrix.cc
References A00, A01, A02, A03, A04, A10, A11, A12, A13, A14, A20, A21, A22, A23, A24, A30, A31, A32, A33, A34, A40, A41, A42, A43, A44, and m.
Referenced by invert5().
void G4ErrorSymMatrix::invertHaywood6 (G4int & ifail)
Definition at line 1532 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 1532 of file G4ErrorSymMatrix.cc
References A00, A01, A02, A03, A04, A05, A10, A11, A12, A13, A14, A15, A20, A21, A22, A23, A24, A25, A30, A31, A32, A33, A34, A35, A40, A41, A42, A43, A44, A45, A50, A51, A52, A53, A54, A55, and m.
Referenced by invert6().
G4int G4ErrorSymMatrix::num_col () const inline
Referenced by operator*(), operator+(), G4ErrorMatrix::operator+=(), operator+=(), operator-(), G4ErrorMatrix::operator-=(), operator-=(), operator<<(), and similarity().
G4int G4ErrorSymMatrix::num_row () const inline
Referenced by apply(), dsum(), operator*(), operator+(), G4ErrorMatrix::operator+=(), operator+=(), operator-(), G4ErrorMatrix::operator-=(), operator-=(), operator<<(), similarity(), and sub().
G4int G4ErrorSymMatrix::num_size () const inline protected
Referenced by operator-().
const G4double& G4ErrorSymMatrix::operator() (G4int row, G4int col) const
G4double& G4ErrorSymMatrix::operator() (G4int row, G4int col)
G4ErrorSymMatrix & G4ErrorSymMatrix::operator*= (G4double t)
Definition at line 471 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 471 of file G4ErrorSymMatrix.cc
References SIMPLE_UOP.
G4ErrorSymMatrix & G4ErrorSymMatrix::operator+= (const G4ErrorSymMatrix & m2)
Definition at line 426 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 426 of file G4ErrorSymMatrix.cc
References CHK_DIM_2, num_col(), num_row(), and SIMPLE_BOP.
G4ErrorSymMatrix G4ErrorSymMatrix::operator- () const
Definition at line 196 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 196 of file G4ErrorSymMatrix.cc
References a, b, e, m, nrow, and num_size().
G4ErrorSymMatrix & G4ErrorSymMatrix::operator-= (const G4ErrorSymMatrix & m2)
Definition at line 458 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 458 of file G4ErrorSymMatrix.cc
References CHK_DIM_2, num_col(), num_row(), and SIMPLE_BOP.
G4ErrorSymMatrix & G4ErrorSymMatrix::operator/= (G4double t)
Definition at line 465 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 465 of file G4ErrorSymMatrix.cc
References SIMPLE_UOP.
G4ErrorSymMatrix & G4ErrorSymMatrix::operator= (const G4ErrorSymMatrix & m2)
Definition at line 508 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 508 of file G4ErrorSymMatrix.cc
References m, nrow, and size.
G4ErrorSymMatrix_row G4ErrorSymMatrix::operator[] (G4int) inline
G4ErrorSymMatrix_row_const G4ErrorSymMatrix::operator[] (G4int) const inline
G4ErrorSymMatrix G4ErrorSymMatrix::similarity (const G4ErrorMatrix & m1) const
Definition at line 588 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 588 of file G4ErrorSymMatrix.cc
References c, G4ErrorMatrix::m, n, G4ErrorMatrix::num_col(), G4ErrorMatrix::num_row(), r, and tmp.
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), and G4ErrorFreeTrajState::PropagateError().
G4ErrorSymMatrix G4ErrorSymMatrix::similarity (const G4ErrorSymMatrix & m1) const
Definition at line 619 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 619 of file G4ErrorSymMatrix.cc
References c, m, n, num_col(), num_row(), r, and tmp.
G4ErrorSymMatrix G4ErrorSymMatrix::similarityT (const G4ErrorMatrix & m1) const
Definition at line 653 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 653 of file G4ErrorSymMatrix.cc
References c, n, G4ErrorMatrix::num_col(), r, and tmp.
G4ErrorSymMatrix G4ErrorSymMatrix::sub (G4int min_row, G4int max_row) const
Definition at line 123 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 123 of file G4ErrorSymMatrix.cc
References a, b, G4ErrorMatrix::error(), m, and num_row().
Referenced by dsum().
void G4ErrorSymMatrix::sub (G4int row, const G4ErrorSymMatrix & m1)
Definition at line 161 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 161 of file G4ErrorSymMatrix.cc
References a, b, G4ErrorMatrix::error(), m, and num_row().
G4ErrorSymMatrix G4ErrorSymMatrix::sub (G4int min_row, G4int max_row)
Definition at line 142 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 142 of file G4ErrorSymMatrix.cc
References a, b, G4ErrorMatrix::error(), m, and num_row().
G4ErrorSymMatrix G4ErrorSymMatrix::T () const
Referenced by G4ErrorFreeTrajState::PropagateError().
G4double G4ErrorSymMatrix::trace () const
Definition at line 818 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 818 of file G4ErrorSymMatrix.cc
References m, nrow, and t.
Friends And Related Function Documentation
G4double condition (const G4ErrorSymMatrix & m) friend
void diag_step (G4ErrorSymMatrix * t, G4int begin, G4int end) friend
void diag_step (G4ErrorSymMatrix * t, G4ErrorMatrix * u, G4int begin, G4int end) friend
G4ErrorMatrix diagonalize (G4ErrorSymMatrix * s) friend
friend class G4ErrorMatrix friend
Definition at line 192 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 192 of file G4ErrorSymMatrix.hh
friend class G4ErrorSymMatrix_row friend
Definition at line 190 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 190 of file G4ErrorSymMatrix.hh
friend class G4ErrorSymMatrix_row_const friend
Definition at line 191 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 191 of file G4ErrorSymMatrix.hh
void house_with_update2 (G4ErrorSymMatrix * a, G4ErrorMatrix * v, G4int row, G4int col) friend
G4ErrorMatrix operator* (const G4ErrorSymMatrix & m1, const G4ErrorSymMatrix & m2) friend
Definition at line 353 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 353 of file G4ErrorSymMatrix.cc
G4ErrorMatrix operator* (const G4ErrorSymMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 320 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 320 of file G4ErrorSymMatrix.cc
G4ErrorMatrix operator* (const G4ErrorMatrix & m1, const G4ErrorSymMatrix & m2) friend
Definition at line 286 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 286 of file G4ErrorSymMatrix.cc
G4ErrorSymMatrix operator+ (const G4ErrorSymMatrix & m1, const G4ErrorSymMatrix & m2) friend
Definition at line 222 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 222 of file G4ErrorSymMatrix.cc
G4ErrorSymMatrix operator- (const G4ErrorSymMatrix & m1, const G4ErrorSymMatrix & m2) friend
Definition at line 251 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 251 of file G4ErrorSymMatrix.cc
void tridiagonal (G4ErrorSymMatrix * a, G4ErrorMatrix * hsm) friend
Member Data Documentation
G4ThreadLocal G4double G4ErrorSymMatrix::adjustment5x5 = 0.0 static private
Definition at line 223 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 223 of file G4ErrorSymMatrix.hh
Referenced by invert5().
G4ThreadLocal G4double G4ErrorSymMatrix::adjustment6x6 = 0.0 static private
Definition at line 228 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 228 of file G4ErrorSymMatrix.hh
Referenced by invert6().
const G4double G4ErrorSymMatrix::CHOLESKY_CREEP_5x5 = .005 static private
Definition at line 225 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 225 of file G4ErrorSymMatrix.hh
Referenced by invert5().
const G4double G4ErrorSymMatrix::CHOLESKY_CREEP_6x6 = .002 static private
Definition at line 230 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 230 of file G4ErrorSymMatrix.hh
Referenced by invert6().
const G4double G4ErrorSymMatrix::CHOLESKY_THRESHOLD_5x5 = .5 static private
Definition at line 224 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 224 of file G4ErrorSymMatrix.hh
Referenced by invert5().
const G4double G4ErrorSymMatrix::CHOLESKY_THRESHOLD_6x6 = .2 static private
Definition at line 229 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 229 of file G4ErrorSymMatrix.hh
Referenced by invert6().
std::vector<G4double > G4ErrorSymMatrix::m private
Definition at line 217 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 217 of file G4ErrorSymMatrix.hh
Referenced by apply(), assign(), G4ErrorMatrix::G4ErrorMatrix(), G4ErrorSymMatrix(), invert(), invert4(), invertBunchKaufman(), invertCholesky5(), invertCholesky6(), invertHaywood5(), invertHaywood6(), operator*(), G4ErrorMatrix::operator+=(), operator-(), G4ErrorMatrix::operator-=(), operator=(), G4ErrorMatrix::operator=(), similarity(), sub(), and trace().
G4int G4ErrorSymMatrix::nrow private
Definition at line 219 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 219 of file G4ErrorSymMatrix.hh
Referenced by assign(), determinant(), G4ErrorSymMatrix(), invert(), invertBunchKaufman(), operator+(), operator-(), operator=(), G4ErrorMatrix::operator=(), and trace().
G4ThreadLocal G4double G4ErrorSymMatrix::posDefFraction5x5 = 1.0 static private
Definition at line 222 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 222 of file G4ErrorSymMatrix.hh
Referenced by invert5().
G4ThreadLocal G4double G4ErrorSymMatrix::posDefFraction6x6 = 1.0 static private
Definition at line 227 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 227 of file G4ErrorSymMatrix.hh
Referenced by invert6().
G4int G4ErrorSymMatrix::size private
Definition at line 220 of file G4ErrorSymMatrix.hh.
View newest version in sPHENIX GitHub at line 220 of file G4ErrorSymMatrix.hh
Referenced by assign(), G4ErrorSymMatrix(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorSymMatrix.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorSymMatrix.cc