ECCE @ EIC Software: G4PrimaryVertex Class Reference
G4PrimaryVertex Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4PrimaryVertex.hh>
Public Member Functions
void * operator new (size_t)
void operator delete (void *aStackedTrack)
G4PrimaryVertex ()
G4PrimaryVertex (G4double x0, G4double y0, G4double z0, G4double t0)
G4PrimaryVertex (G4ThreeVector xyz0, G4double t0)
virtual ~G4PrimaryVertex ()
G4PrimaryVertex (const G4PrimaryVertex &right)
G4PrimaryVertex & operator= (const G4PrimaryVertex &right)
G4bool operator== (const G4PrimaryVertex &right) const
G4bool operator!= (const G4PrimaryVertex &right) const
G4ThreeVector GetPosition () const
void SetPosition (G4double x0, G4double y0, G4double z0)
G4double GetX0 () const
G4double GetY0 () const
G4double GetZ0 () const
G4double GetT0 () const
void SetT0 (G4double t0)
G4int GetNumberOfParticle () const
void SetPrimary (G4PrimaryParticle *pp)
G4PrimaryParticle * GetPrimary (G4int i=0) const
void SetNext (G4PrimaryVertex *nv)
void ClearNext ()
G4PrimaryVertex * GetNext () const
G4double GetWeight () const
void SetWeight (G4double w)
void SetUserInformation (G4VUserPrimaryVertexInformation *anInfo)
G4VUserPrimaryVertexInformation * GetUserInformation () const
void Print () const
Private Attributes
G4double X0
G4double Y0
G4double Z0
G4double T0
G4PrimaryParticle * theParticle
G4PrimaryParticle * theTail
G4PrimaryVertex * nextVertex
G4PrimaryVertex * tailVertex
G4int numberOfParticle
G4double Weight0
G4VUserPrimaryVertexInformation * userInfo
Detailed Description
Definition at line 47 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 47 of file G4PrimaryVertex.hh
Constructor & Destructor Documentation
G4PrimaryVertex::G4PrimaryVertex ()
Definition at line 40 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 40 of file G4PrimaryVertex.cc
Referenced by operator=().
G4PrimaryVertex::G4PrimaryVertex (G4double x0, G4double y0, G4double z0, G4double t0)
Definition at line 47 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 47 of file G4PrimaryVertex.cc
G4PrimaryVertex::G4PrimaryVertex (G4ThreeVector xyz0, G4double t0)
Definition at line 55 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 55 of file G4PrimaryVertex.cc
G4PrimaryVertex::~G4PrimaryVertex () virtual
Definition at line 69 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 69 of file G4PrimaryVertex.cc
References G4PrimaryParticle::ClearNext(), G4PrimaryParticle::GetNext(), nextVertex, tailVertex, theParticle, theTail, and userInfo.
G4PrimaryVertex::G4PrimaryVertex (const G4PrimaryVertex & right)
Definition at line 62 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PrimaryVertex.cc
References right.
Member Function Documentation
void G4PrimaryVertex::ClearNext () inline
Definition at line 157 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 157 of file G4PrimaryVertex.hh
References nextVertex, and tailVertex.
Referenced by G4Event::~G4Event().
G4PrimaryVertex * G4PrimaryVertex::GetNext () const inline
Definition at line 163 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 163 of file G4PrimaryVertex.hh
References nextVertex.
Referenced by PHG4TruthEventAction::EndOfEventAction(), PrimaryGeneratorAction1::GeneratePrimaries(), G4Event::GetPrimaryVertex(), G4PrimaryTransformer::GimmePrimaries(), operator=(), and G4Event::~G4Event().
G4int G4PrimaryVertex::GetNumberOfParticle () const inline
Definition at line 139 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 139 of file G4PrimaryVertex.hh
References numberOfParticle.
Referenced by export_G4PrimaryVertex(), and Par02PrimaryGeneratorAction::GeneratePrimaries().
G4ThreeVector G4PrimaryVertex::GetPosition () const inline
Definition at line 118 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 118 of file G4PrimaryVertex.hh
References X0, Y0, and Z0.
Referenced by ExGflashEventAction::EndOfEventAction(), export_G4PrimaryVertex(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), and G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
G4PrimaryParticle * G4PrimaryVertex::GetPrimary (G4int i = 0) const
Definition at line 144 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 144 of file G4PrimaryVertex.cc
References G4PrimaryParticle::GetNext(), numberOfParticle, particle, and theParticle.
Referenced by PHG4TruthEventAction::EndOfEventAction(), ExGflashEventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), export_G4PrimaryVertex(), Par02PrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), and G4PrimaryTransformer::GenerateTracks().
G4double G4PrimaryVertex::GetT0 () const inline
Definition at line 133 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 133 of file G4PrimaryVertex.hh
References T0.
Referenced by RE01EventAction::EndOfEventAction(), export_G4PrimaryVertex(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), and G4PrimaryTransformer::GenerateTracks().
G4VUserPrimaryVertexInformation * G4PrimaryVertex::GetUserInformation () const inline
Definition at line 175 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 175 of file G4PrimaryVertex.hh
References userInfo.
G4double G4PrimaryVertex::GetWeight () const inline
Definition at line 166 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 166 of file G4PrimaryVertex.hh
References Weight0.
Referenced by export_G4PrimaryVertex(), and G4PrimaryTransformer::GenerateTracks().
G4double G4PrimaryVertex::GetX0 () const inline
Definition at line 124 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 124 of file G4PrimaryVertex.hh
References X0.
Referenced by RE01EventAction::EndOfEventAction(), export_G4PrimaryVertex(), and G4PrimaryTransformer::GenerateTracks().
G4double G4PrimaryVertex::GetY0 () const inline
Definition at line 127 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 127 of file G4PrimaryVertex.hh
References Y0.
Referenced by RE01EventAction::EndOfEventAction(), export_G4PrimaryVertex(), and G4PrimaryTransformer::GenerateTracks().
G4double G4PrimaryVertex::GetZ0 () const inline
Definition at line 130 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 130 of file G4PrimaryVertex.hh
References Z0.
Referenced by RE01EventAction::EndOfEventAction(), export_G4PrimaryVertex(), and G4PrimaryTransformer::GenerateTracks().
void G4PrimaryVertex::operator delete (void * aStackedTrack) inline
Definition at line 113 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 113 of file G4PrimaryVertex.hh
References aPrimaryVertexAllocator().
void * G4PrimaryVertex::operator new (size_t) inline
Definition at line 104 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 104 of file G4PrimaryVertex.hh
References aPrimaryVertexAllocator().
G4bool G4PrimaryVertex::operator!= (const G4PrimaryVertex & right) const
Definition at line 141 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 141 of file G4PrimaryVertex.cc
G4PrimaryVertex & G4PrimaryVertex::operator= (const G4PrimaryVertex & right)
Definition at line 94 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 94 of file G4PrimaryVertex.cc
References G4PrimaryVertex(), GetNext(), G4PrimaryParticle::GetNext(), nextVertex, numberOfParticle, T0, tailVertex, theParticle, theTail, userInfo, Weight0, X0, Y0, and Z0.
G4bool G4PrimaryVertex::operator== (const G4PrimaryVertex & right) const
Definition at line 138 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 138 of file G4PrimaryVertex.cc
void G4PrimaryVertex::Print (void) const
Definition at line 158 of file G4PrimaryVertex.cc.
View newest version in sPHENIX GitHub at line 158 of file G4PrimaryVertex.cc
References G4cout, G4endl, mm, nextVertex, ns, numberOfParticle, G4VUserPrimaryVertexInformation::Print(), Print(), G4PrimaryParticle::Print(), T0, theParticle, userInfo, Weight0, X0, Y0, and Z0.
Referenced by export_G4PrimaryVertex(), G4PrimaryTransformer::GenerateTracks(), and Print().
void G4PrimaryVertex::SetNext (G4PrimaryVertex * nv) inline
Definition at line 150 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 150 of file G4PrimaryVertex.hh
References nextVertex, SetNext(), and tailVertex.
Referenced by G4Event::AddPrimaryVertex(), and SetNext().
void G4PrimaryVertex::SetPosition (G4double x0, G4double y0, G4double z0) inline
Definition at line 121 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 121 of file G4PrimaryVertex.hh
References X0, Y0, G4InuclParticleNames::z0, and Z0.
Referenced by G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
void G4PrimaryVertex::SetPrimary (G4PrimaryParticle * pp) inline
Definition at line 142 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 142 of file G4PrimaryVertex.hh
References numberOfParticle, G4InuclParticleNames::pp, G4PrimaryParticle::SetNext(), theParticle, and theTail.
Referenced by export_G4PrimaryVertex(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), G4BlinePrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGenerator::GeneratePrimaryVertex(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4HEPEvtInterface::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), and G4RayShooter::Shoot().
void G4PrimaryVertex::SetT0 (G4double t0) inline
Definition at line 136 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 136 of file G4PrimaryVertex.hh
References T0.
Referenced by PrimaryGeneratorAction1::GeneratePrimaries(), and G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
void G4PrimaryVertex::SetUserInformation (G4VUserPrimaryVertexInformation * anInfo) inline
Definition at line 172 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 172 of file G4PrimaryVertex.hh
References userInfo.
void G4PrimaryVertex::SetWeight (G4double w) inline
Definition at line 169 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 169 of file G4PrimaryVertex.hh
References w, and Weight0.
Referenced by export_G4PrimaryVertex(), and G4AdjointPrimaryGeneratorAction::GeneratePrimaries().
Member Data Documentation
G4PrimaryVertex* G4PrimaryVertex::nextVertex private
Definition at line 94 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PrimaryVertex.hh
Referenced by ClearNext(), GetNext(), operator=(), Print(), SetNext(), and ~G4PrimaryVertex().
G4int G4PrimaryVertex::numberOfParticle private
Definition at line 96 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 96 of file G4PrimaryVertex.hh
Referenced by GetNumberOfParticle(), GetPrimary(), operator=(), Print(), and SetPrimary().
G4double G4PrimaryVertex::T0 private
Definition at line 91 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PrimaryVertex.hh
Referenced by GetT0(), operator=(), Print(), and SetT0().
G4PrimaryVertex* G4PrimaryVertex::tailVertex private
Definition at line 95 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PrimaryVertex.hh
Referenced by ClearNext(), operator=(), SetNext(), and ~G4PrimaryVertex().
G4PrimaryParticle* G4PrimaryVertex::theParticle private
Definition at line 92 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PrimaryVertex.hh
Referenced by GetPrimary(), operator=(), Print(), SetPrimary(), and ~G4PrimaryVertex().
G4PrimaryParticle* G4PrimaryVertex::theTail private
Definition at line 93 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PrimaryVertex.hh
Referenced by operator=(), SetPrimary(), and ~G4PrimaryVertex().
G4VUserPrimaryVertexInformation* G4PrimaryVertex::userInfo private
Definition at line 98 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 98 of file G4PrimaryVertex.hh
Referenced by GetUserInformation(), operator=(), Print(), SetUserInformation(), and ~G4PrimaryVertex().
G4double G4PrimaryVertex::Weight0 private
Definition at line 97 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 97 of file G4PrimaryVertex.hh
Referenced by GetWeight(), operator=(), Print(), and SetWeight().
G4double G4PrimaryVertex::X0 private
Definition at line 88 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PrimaryVertex.hh
Referenced by GetPosition(), GetX0(), operator=(), Print(), and SetPosition().
G4double G4PrimaryVertex::Y0 private
Definition at line 89 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 89 of file G4PrimaryVertex.hh
Referenced by GetPosition(), GetY0(), operator=(), Print(), and SetPosition().
G4double G4PrimaryVertex::Z0 private
Definition at line 90 of file G4PrimaryVertex.hh.
View newest version in sPHENIX GitHub at line 90 of file G4PrimaryVertex.hh
Referenced by GetPosition(), GetZ0(), operator=(), Print(), and SetPosition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4PrimaryVertex.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4PrimaryVertex.cc