ECCE @ EIC Software: G4tgrMaterialMixture Class Reference
G4tgrMaterialMixture Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrMaterialMixture.hh>
Public Member Functions
G4tgrMaterialMixture (const G4String &matType, const std::vector< G4String > &wl)
G4double GetA () const
G4double GetZ () const
const G4String & GetComponent (G4int i) const
G4double GetFraction (G4int i)
G4tgrMaterialMixture operator= (const G4tgrMaterialMixture &)
G4tgrMaterialMixture ()
~G4tgrMaterialMixture ()
Public Member Functions inherited from G4tgrMaterial
G4tgrMaterial ()
virtual ~G4tgrMaterial ()
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfComponents () const
const G4String & GetType () const
G4double GetIonisationMeanExcitationEnergy () const
void SetIonisationMeanExcitationEnergy (G4double mee)
G4State GetState () const
void SetState (G4String val)
G4double GetTemperature () const
void SetTemperature (G4double val)
G4double GetPressure () const
void SetPressure (G4double val)
Protected Member Functions
void TransformToFractionsByWeight ()
Protected Attributes
std::vector< G4String > theComponents
std::vector< G4double > theFractions
Protected Attributes inherited from G4tgrMaterial
G4String theName
G4double theDensity
G4int theNoComponents
G4String theMateType
G4double theIonisationMeanExcitationEnergy
G4State theState
G4double theTemperature
G4double thePressure
Friends
std::ostream & operator<< (std::ostream &, const G4tgrMaterialMixture &)
Detailed Description
Definition at line 49 of file G4tgrMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 49 of file G4tgrMaterialMixture.hh
Constructor & Destructor Documentation
G4tgrMaterialMixture::G4tgrMaterialMixture (const G4String & matType, const std::vector< G4String > & wl)
Definition at line 54 of file G4tgrMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 54 of file G4tgrMaterialMixture.cc
References G4tgrUtils::CheckWLsize(), cm3, Acts::UnitConstants::g, G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), theComponents, G4tgrMaterial::theDensity, theFractions, G4tgrMaterial::theMateType, G4tgrMaterial::theName, G4tgrMaterial::theNoComponents, and WLSIZE_GE.
G4tgrMaterialMixture::G4tgrMaterialMixture ()
Definition at line 42 of file G4tgrMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 42 of file G4tgrMaterialMixture.cc
G4tgrMaterialMixture::~G4tgrMaterialMixture ()
Definition at line 48 of file G4tgrMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 48 of file G4tgrMaterialMixture.cc
Member Function Documentation
G4double G4tgrMaterialMixture::GetA () const inline virtual
Implements G4tgrMaterial.
Definition at line 61 of file G4tgrMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgrMaterialMixture.hh
const G4String& G4tgrMaterialMixture::GetComponent (G4int i) const inline virtual
Implements G4tgrMaterial.
Definition at line 63 of file G4tgrMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 63 of file G4tgrMaterialMixture.hh
References theComponents.
G4double G4tgrMaterialMixture::GetFraction (G4int i) inline virtual
Implements G4tgrMaterial.
Definition at line 64 of file G4tgrMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 64 of file G4tgrMaterialMixture.hh
References theFractions.
G4double G4tgrMaterialMixture::GetZ () const inline virtual
Implements G4tgrMaterial.
Definition at line 62 of file G4tgrMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 62 of file G4tgrMaterialMixture.hh
G4tgrMaterialMixture G4tgrMaterialMixture::operator= (const G4tgrMaterialMixture &)
void G4tgrMaterialMixture::TransformToFractionsByWeight () inline protected
Definition at line 75 of file G4tgrMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 75 of file G4tgrMaterialMixture.hh
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrMaterialMixture & mate) friend
Definition at line 94 of file G4tgrMaterialMixture.cc.
View newest version in sPHENIX GitHub at line 94 of file G4tgrMaterialMixture.cc
Member Data Documentation
std::vector<G4String> G4tgrMaterialMixture::theComponents protected
Definition at line 75 of file G4tgrMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 75 of file G4tgrMaterialMixture.hh
Referenced by G4tgrMaterialMixture(), GetComponent(), and operator<<().
std::vector<G4double> G4tgrMaterialMixture::theFractions protected
Definition at line 80 of file G4tgrMaterialMixture.hh.
View newest version in sPHENIX GitHub at line 80 of file G4tgrMaterialMixture.hh
Referenced by G4tgrMaterialMixture(), GetFraction(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrMaterialMixture.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrMaterialMixture.cc