ECCE @ EIC Software: G4RDBremsstrahlungCrossSectionHandler Class Reference
G4RDBremsstrahlungCrossSectionHandler Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDBremsstrahlungCrossSectionHandler.hh>
Public Member Functions
G4RDBremsstrahlungCrossSectionHandler (const G4RDVEnergySpectrum *spectrum, G4RDVDataSetAlgorithm *interpolation)
~G4RDBremsstrahlungCrossSectionHandler ()
Public Member Functions inherited from G4RDVCrossSectionHandler
G4RDVCrossSectionHandler ()
G4RDVCrossSectionHandler (G4RDVDataSetAlgorithm *interpolation, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int nBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
virtual ~G4RDVCrossSectionHandler ()
void Initialise (G4RDVDataSetAlgorithm *interpolation=0, G4double minE=250 *CLHEP::eV, G4double maxE=100 *CLHEP::GeV, G4int numberOfBins=200, G4double unitE=CLHEP::MeV, G4double unitData=CLHEP::barn, G4int minZ=1, G4int maxZ=99)
G4int SelectRandomAtom (const G4MaterialCutsCouple *couple, G4double e) const
const G4Element * SelectRandomElement (const G4MaterialCutsCouple *material, G4double e) const
G4int SelectRandomShell (G4int Z, G4double e) const
G4RDVEMDataSet * BuildMeanFreePathForMaterials (const G4DataVector *energyCuts=0)
G4double FindValue (G4int Z, G4double e) const
G4double FindValue (G4int Z, G4double e, G4int shellIndex) const
G4double ValueForMaterial (const G4Material *material, G4double e) const
void LoadData (const G4String &dataFile)
void LoadShellData (const G4String &dataFile)
void PrintData () const
void Clear ()
Protected Member Functions
std::vector< G4RDVEMDataSet * > * BuildCrossSectionsForMaterials (const G4DataVector &energyVector, const G4DataVector *energyCuts)
Protected Member Functions inherited from G4RDVCrossSectionHandler
G4int NumberOfComponents (G4int Z) const
void ActiveElements ()
virtual G4RDVDataSetAlgorithm * CreateInterpolation ()
const G4RDVDataSetAlgorithm * GetInterpolation () const
Private Member Functions
G4RDBremsstrahlungCrossSectionHandler & operator= (const G4RDBremsstrahlungCrossSectionHandler &right)
G4RDBremsstrahlungCrossSectionHandler (const G4RDBremsstrahlungCrossSectionHandler &)
Private Attributes
const G4RDVEnergySpectrum * theBR
G4RDVDataSetAlgorithm * interp
Detailed Description
Definition at line 62 of file G4RDBremsstrahlungCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 62 of file G4RDBremsstrahlungCrossSectionHandler.hh
Constructor & Destructor Documentation
G4RDBremsstrahlungCrossSectionHandler::G4RDBremsstrahlungCrossSectionHandler (const G4RDVEnergySpectrum * spectrum, G4RDVDataSetAlgorithm * interpolation)
Definition at line 55 of file G4RDBremsstrahlungCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 55 of file G4RDBremsstrahlungCrossSectionHandler.cc
References interp.
G4RDBremsstrahlungCrossSectionHandler::~G4RDBremsstrahlungCrossSectionHandler ()
Definition at line 63 of file G4RDBremsstrahlungCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 63 of file G4RDBremsstrahlungCrossSectionHandler.cc
References interp.
G4RDBremsstrahlungCrossSectionHandler::G4RDBremsstrahlungCrossSectionHandler (const G4RDBremsstrahlungCrossSectionHandler &) private
Member Function Documentation
std::vector< G4RDVEMDataSet * > * G4RDBremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials (const G4DataVector & energyVector, const G4DataVector * energyCuts) protected virtual
Implements G4RDVCrossSectionHandler.
Definition at line 70 of file G4RDBremsstrahlungCrossSectionHandler.cc.
View newest version in sPHENIX GitHub at line 70 of file G4RDBremsstrahlungCrossSectionHandler.cc
References G4RDVEMDataSet::AddComponent(), bin, G4RDVDataSetAlgorithm::Clone(), e, G4RDVCrossSectionHandler::FindValue(), G4Material::GetElementVector(), G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4Material::GetNumberOfElements(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4Material::GetVecNbOfAtomsPerVolume(), interp, m, material(), G4RDVEnergySpectrum::Probability(), theBR, and Z.
G4RDBremsstrahlungCrossSectionHandler& G4RDBremsstrahlungCrossSectionHandler::operator= (const G4RDBremsstrahlungCrossSectionHandler & right) private
Member Data Documentation
G4RDVDataSetAlgorithm* G4RDBremsstrahlungCrossSectionHandler::interp private
Definition at line 85 of file G4RDBremsstrahlungCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RDBremsstrahlungCrossSectionHandler.hh
Referenced by BuildCrossSectionsForMaterials(), G4RDBremsstrahlungCrossSectionHandler(), and ~G4RDBremsstrahlungCrossSectionHandler().
const G4RDVEnergySpectrum* G4RDBremsstrahlungCrossSectionHandler::theBR private
Definition at line 83 of file G4RDBremsstrahlungCrossSectionHandler.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RDBremsstrahlungCrossSectionHandler.hh
Referenced by BuildCrossSectionsForMaterials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDBremsstrahlungCrossSectionHandler.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDBremsstrahlungCrossSectionHandler.cc