ECCE @ EIC Software: G4CascadeDeexciteBase Class Reference
G4CascadeDeexciteBase Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeDeexciteBase.hh>
Public Member Functions
G4CascadeDeexciteBase (const char *name)
virtual ~G4CascadeDeexciteBase ()
virtual void setVerboseLevel (G4int verbose=0)
Public Member Functions inherited from G4VCascadeDeexcitation
G4VCascadeDeexcitation (const G4String &name)
virtual ~G4VCascadeDeexcitation ()
virtual void collide (G4InuclParticle *bullet, G4InuclParticle *target, G4CollisionOutput &globalOutput)
virtual void deExcite (const G4Fragment &fragment, G4CollisionOutput &output)=0
Public Member Functions inherited from G4VCascadeCollider
G4VCascadeCollider (const G4String &name, G4int verbose=0)
virtual ~G4VCascadeCollider ()
Protected Member Functions
virtual G4bool explosion (const G4Fragment &target) const
virtual G4bool explosion (G4int A, G4int Z, G4double excitation) const
virtual G4bool validateOutput (const G4Fragment &target, G4CollisionOutput &output)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclElementaryParticle > &particles)
virtual G4bool validateOutput (const G4Fragment &target, const std::vector< G4InuclNuclei > &fragments)
void getTargetData (const G4Fragment &target)
const G4Fragment & makeFragment (G4LorentzVector mom, G4int A, G4int Z, G4double EX=0.)
const G4Fragment & makeFragment (G4int A, G4int Z, G4double EX=0.)
Protected Attributes
G4CascadeCheckBalance * balance
G4int A
G4int Z
G4LorentzVector PEX
G4double EEXS
G4Fragment aFragment
Private Member Functions
G4CascadeDeexciteBase (const G4CascadeDeexciteBase &)
G4CascadeDeexciteBase & operator= (const G4CascadeDeexciteBase &)
Detailed Description
Definition at line 44 of file G4CascadeDeexciteBase.hh.
View newest version in sPHENIX GitHub at line 44 of file G4CascadeDeexciteBase.hh
Constructor & Destructor Documentation
G4CascadeDeexciteBase::G4CascadeDeexciteBase (const char * name)
Definition at line 48 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 48 of file G4CascadeDeexciteBase.cc
References balance, and G4CascadeParameters::checkConservation().
G4CascadeDeexciteBase::~G4CascadeDeexciteBase () virtual
Definition at line 54 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 54 of file G4CascadeDeexciteBase.cc
References balance.
G4CascadeDeexciteBase::G4CascadeDeexciteBase (const G4CascadeDeexciteBase &) private
Member Function Documentation
G4bool G4CascadeDeexciteBase::explosion (const G4Fragment & target) const protected virtual
Reimplemented in G4EquilibriumEvaporator.
Definition at line 109 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 109 of file G4CascadeDeexciteBase.cc
References G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), and G4Fragment::GetZ_asInt().
Referenced by G4CascadeDeexcitation::deExcite(), G4PreCompoundDeexcitation::deExcite(), and G4EquilibriumEvaporator::explosion().
G4bool G4CascadeDeexciteBase::explosion (G4int A, G4int Z, G4double excitation) const protected virtual
Reimplemented in G4EquilibriumEvaporator.
Definition at line 114 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 114 of file G4CascadeDeexciteBase.cc
References G4InuclSpecialFunctions::bindingEnergy(), G4cout, G4endl, G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
void G4CascadeDeexciteBase::getTargetData (const G4Fragment & target) protected
Definition at line 66 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 66 of file G4CascadeDeexciteBase.cc
References A, EEXS, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetMomentum(), G4Fragment::GetZ_asInt(), GeV, PEX, and Z.
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), and G4EquilibriumEvaporator::deExcite().
const G4Fragment & G4CascadeDeexciteBase::makeFragment (G4LorentzVector mom, G4int A, G4int Z, G4double EX = 0.) protected
Definition at line 86 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 86 of file G4CascadeDeexciteBase.cc
References aFragment, G4cout, G4endl, G4InuclNuclei::getNucleiMass(), GeV, mass, G4Fragment::SetMomentum(), G4Fragment::SetNumberOfExcitedParticle(), G4Fragment::SetNumberOfHoles(), CLHEP::HepLorentzVector::setVectM(), G4Fragment::SetZandA_asInt(), G4VCascadeCollider::theName, CLHEP::HepLorentzVector::vect(), and G4VCascadeCollider::verboseLevel.
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4EquilibriumEvaporator::deExcite(), and makeFragment().
const G4Fragment & G4CascadeDeexciteBase::makeFragment (G4int A, G4int Z, G4double EX = 0.) protected
Definition at line 81 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 81 of file G4CascadeDeexciteBase.cc
References makeFragment(), and zero.
G4CascadeDeexciteBase& G4CascadeDeexciteBase::operator= (const G4CascadeDeexciteBase &) private
void G4CascadeDeexciteBase::setVerboseLevel (G4int verbose = 0) virtual
Reimplemented from G4VCascadeCollider.
Reimplemented in G4EquilibriumEvaporator, G4PreCompoundDeexcitation, and G4CascadeDeexcitation.
Definition at line 58 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 58 of file G4CascadeDeexciteBase.cc
References balance, and G4VCascadeCollider::setVerboseLevel().
Referenced by G4CascadeDeexcitation::setVerboseLevel(), G4PreCompoundDeexcitation::setVerboseLevel(), and G4EquilibriumEvaporator::setVerboseLevel().
G4bool G4CascadeDeexciteBase::validateOutput (const G4Fragment & target, G4CollisionOutput & output) protected virtual
Definition at line 130 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 130 of file G4CascadeDeexciteBase.cc
References balance, G4CascadeCheckBalance::collide(), G4cout, G4endl, G4CascadeCheckBalance::okay(), G4VCascadeCollider::setVerboseLevel(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), and G4EquilibriumEvaporator::deExcite().
G4bool G4CascadeDeexciteBase::validateOutput (const G4Fragment & target, const std::vector< G4InuclElementaryParticle > & particles) protected virtual
Definition at line 142 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 142 of file G4CascadeDeexciteBase.cc
References balance, G4CascadeCheckBalance::collide(), G4cout, G4endl, G4CascadeCheckBalance::okay(), G4VCascadeCollider::setVerboseLevel(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
G4bool G4CascadeDeexciteBase::validateOutput (const G4Fragment & target, const std::vector< G4InuclNuclei > & fragments) protected virtual
Definition at line 154 of file G4CascadeDeexciteBase.cc.
View newest version in sPHENIX GitHub at line 154 of file G4CascadeDeexciteBase.cc
References balance, G4CascadeCheckBalance::collide(), G4cout, G4endl, G4CascadeCheckBalance::okay(), G4VCascadeCollider::setVerboseLevel(), G4VCascadeCollider::theName, and G4VCascadeCollider::verboseLevel.
Member Data Documentation
G4int G4CascadeDeexciteBase::A protected
Definition at line 73 of file G4CascadeDeexciteBase.hh.
View newest version in sPHENIX GitHub at line 73 of file G4CascadeDeexciteBase.hh
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4EquilibriumEvaporator::deExcite(), and getTargetData().
G4Fragment G4CascadeDeexciteBase::aFragment protected
Definition at line 82 of file G4CascadeDeexciteBase.hh.
View newest version in sPHENIX GitHub at line 82 of file G4CascadeDeexciteBase.hh
Referenced by makeFragment().
G4CascadeCheckBalance* G4CascadeDeexciteBase::balance protected
Definition at line 57 of file G4CascadeDeexciteBase.hh.
View newest version in sPHENIX GitHub at line 57 of file G4CascadeDeexciteBase.hh
Referenced by G4CascadeDeexciteBase(), setVerboseLevel(), validateOutput(), and ~G4CascadeDeexciteBase().
G4double G4CascadeDeexciteBase::EEXS protected
Definition at line 76 of file G4CascadeDeexciteBase.hh.
View newest version in sPHENIX GitHub at line 76 of file G4CascadeDeexciteBase.hh
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4EquilibriumEvaporator::deExcite(), and getTargetData().
G4LorentzVector G4CascadeDeexciteBase::PEX protected
Definition at line 75 of file G4CascadeDeexciteBase.hh.
View newest version in sPHENIX GitHub at line 75 of file G4CascadeDeexciteBase.hh
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4EquilibriumEvaporator::deExcite(), and getTargetData().
G4int G4CascadeDeexciteBase::Z protected
Definition at line 74 of file G4CascadeDeexciteBase.hh.
View newest version in sPHENIX GitHub at line 74 of file G4CascadeDeexciteBase.hh
Referenced by G4NonEquilibriumEvaporator::deExcite(), G4BigBanger::deExcite(), G4EquilibriumEvaporator::deExcite(), and getTargetData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/include/G4CascadeDeexciteBase.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/cascade/cascade/src/G4CascadeDeexciteBase.cc