ECCE @ EIC Software: STCyclotronPrimaryGeneratorAction Class Reference
STCyclotronPrimaryGeneratorAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/include/STCyclotronPrimaryGeneratorAction.hh>
Public Member Functions
STCyclotronPrimaryGeneratorAction ()
virtual ~STCyclotronPrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *)
virtual void SetBeamCurrent (G4double)
G4GeneralParticleSource * GetParticleGun ()
G4double GetBeamCurrent ()
Public Member Functions inherited from G4VUserPrimaryGeneratorAction
G4VUserPrimaryGeneratorAction ()
virtual ~G4VUserPrimaryGeneratorAction ()
Private Attributes
G4GeneralParticleSource * fParticleBeam
G4double fBeamCurrent
STCyclotronPrimaryGeneratorActionMessenger * fMessenger
Detailed Description
Definition at line 42 of file STCyclotronPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 42 of file STCyclotronPrimaryGeneratorAction.hh
Constructor & Destructor Documentation
STCyclotronPrimaryGeneratorAction::STCyclotronPrimaryGeneratorAction ()
Definition at line 41 of file STCyclotronGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 41 of file STCyclotronGeneratorAction.cc
References fBeamCurrent, fMessenger, and fParticleBeam.
STCyclotronPrimaryGeneratorAction::~STCyclotronPrimaryGeneratorAction () virtual
Definition at line 50 of file STCyclotronGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 50 of file STCyclotronGeneratorAction.cc
References fMessenger, and fParticleBeam.
Member Function Documentation
void STCyclotronPrimaryGeneratorAction::GeneratePrimaries (G4Event * anEvent) virtual
Implements G4VUserPrimaryGeneratorAction.
Definition at line 56 of file STCyclotronGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 56 of file STCyclotronGeneratorAction.cc
References kdfinder::abs(), energy, fBeamCurrent, fParticleBeam, G4cout, G4endl, G4GeneralParticleSource::GeneratePrimaryVertex(), G4RunManager::GetNonConstCurrentRun(), G4GeneralParticleSource::GetParticleDefinition(), G4GeneralParticleSource::GetParticleEnergy(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4RunManager::GetRunManager(), STCyclotronRun::SetBeamCurrent(), STCyclotronRun::SetBeamEnergy(), STCyclotronRun::SetBeamName(), G4GeneralParticleSource::SetNumberOfParticles(), STCyclotronRun::SetPrimariesPerEvent(), and STCyclotronRun::SetTimePerEvent().
G4double STCyclotronPrimaryGeneratorAction::GetBeamCurrent () inline
Definition at line 52 of file STCyclotronPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file STCyclotronPrimaryGeneratorAction.hh
References fBeamCurrent.
G4GeneralParticleSource* STCyclotronPrimaryGeneratorAction::GetParticleGun (void) inline
Definition at line 51 of file STCyclotronPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 51 of file STCyclotronPrimaryGeneratorAction.hh
References fParticleBeam.
void STCyclotronPrimaryGeneratorAction::SetBeamCurrent (G4double current) virtual
Definition at line 88 of file STCyclotronGeneratorAction.cc.
View newest version in sPHENIX GitHub at line 88 of file STCyclotronGeneratorAction.cc
References fBeamCurrent, G4cout, and G4endl.
Member Data Documentation
G4double STCyclotronPrimaryGeneratorAction::fBeamCurrent private
Definition at line 57 of file STCyclotronPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 57 of file STCyclotronPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetBeamCurrent(), SetBeamCurrent(), and STCyclotronPrimaryGeneratorAction().
STCyclotronPrimaryGeneratorActionMessenger* STCyclotronPrimaryGeneratorAction::fMessenger private
Definition at line 58 of file STCyclotronPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 58 of file STCyclotronPrimaryGeneratorAction.hh
Referenced by STCyclotronPrimaryGeneratorAction(), and ~STCyclotronPrimaryGeneratorAction().
G4GeneralParticleSource* STCyclotronPrimaryGeneratorAction::fParticleBeam private
Definition at line 52 of file STCyclotronPrimaryGeneratorAction.hh.
View newest version in sPHENIX GitHub at line 52 of file STCyclotronPrimaryGeneratorAction.hh
Referenced by GeneratePrimaries(), GetParticleGun(), STCyclotronPrimaryGeneratorAction(), and ~STCyclotronPrimaryGeneratorAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/include/STCyclotronPrimaryGeneratorAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/src/STCyclotronGeneratorAction.cc