ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/event/pyG4ParticleGun.cc File Reference
pyG4ParticleGun.cc File Reference
#include <boost/python.hpp>
#include "G4Version.hh"
#include "G4ParticleGun.hh"
#include "G4ParticleTable.hh"
#include "G4Event.hh"
Namespaces
namespace pyG4ParticleGun
Functions
void pyG4ParticleGun::SetParticleByName (G4ParticleGun *gun, const std::string &pname)
std::string pyG4ParticleGun::GetParticleByName (G4ParticleGun *gun)
void export_G4ParticleGun ()
Function Documentation
void export_G4ParticleGun ()
Definition at line 126 of file pyG4ParticleGun.cc.
View newest version in sPHENIX GitHub at line 126 of file pyG4ParticleGun.cc
References G4ParticleGun::GeneratePrimaryVertex(), G4ParticleGun::GetNumberOfParticles(), pyG4ParticleGun::GetParticleByName(), G4ParticleGun::GetParticleCharge(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), G4ParticleGun::GetParticleMomentumDirection(), G4ParticleGun::GetParticlePolarization(), G4VPrimaryGenerator::GetParticlePosition(), G4VPrimaryGenerator::GetParticleTime(), G4ParticleGun::SetNumberOfParticles(), pyG4ParticleGun::SetParticleByName(), G4ParticleGun::SetParticleCharge(), G4ParticleGun::SetParticleDefinition(), G4ParticleGun::SetParticleEnergy(), G4ParticleGun::SetParticleMomentum(), G4ParticleGun::SetParticleMomentumDirection(), G4ParticleGun::SetParticlePolarization(), G4VPrimaryGenerator::SetParticlePosition(), and G4VPrimaryGenerator::SetParticleTime().
Referenced by BOOST_PYTHON_MODULE().