ECCE @ EIC Software: G4AttValueFilterT< T, ConversionErrorPolicy > Class Template Reference
G4AttValueFilterT< T, ConversionErrorPolicy > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4AttValueFilterT.hh>
Public Member Functions
G4AttValueFilterT ()
virtual ~G4AttValueFilterT ()
G4bool Accept (const G4AttValue &attVal) const
G4bool GetValidElement (const G4AttValue &input, G4String &interval) const
virtual void PrintAll (std::ostream &ostr) const
virtual void Reset ()
void LoadIntervalElement (const G4String &input)
void LoadSingleValueElement (const G4String &input)
Public Member Functions inherited from G4VAttValueFilter
G4VAttValueFilter (const G4String &name="G4AttValueFilter")
virtual ~G4VAttValueFilter ()
Public Member Functions inherited from G4VFilter< G4AttValue >
G4VFilter (const G4String &name)
virtual ~G4VFilter ()
G4String Name () const
G4String GetName () const
Private Types
typedef std::pair< T, T > Pair
typedef std::map< G4String, Pair > IntervalMap
typedef std::map< G4String, T > SingleValueMap
Private Attributes
IntervalMap fIntervalMap
SingleValueMap fSingleValueMap
Additional Inherited Members
Public Types inherited from G4VFilter< G4AttValue >
typedef G4AttValue Type
Detailed Description
template<typename T, typename ConversionErrorPolicy = G4ConversionFatalError>
class G4AttValueFilterT< T, ConversionErrorPolicy >
Definition at line 71 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 71 of file G4AttValueFilterT.hh
Member Typedef Documentation
template<typename T , typename ConversionErrorPolicy = G4ConversionFatalError> typedef std::map<G4String, Pair> G4AttValueFilterT< T, ConversionErrorPolicy >::IntervalMap private
Definition at line 96 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AttValueFilterT.hh
template<typename T , typename ConversionErrorPolicy = G4ConversionFatalError> typedef std::pair<T, T> G4AttValueFilterT< T, ConversionErrorPolicy >::Pair private
Definition at line 95 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 95 of file G4AttValueFilterT.hh
template<typename T , typename ConversionErrorPolicy = G4ConversionFatalError> typedef std::map<G4String, T> G4AttValueFilterT< T, ConversionErrorPolicy >::SingleValueMap private
Definition at line 97 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AttValueFilterT.hh
Constructor & Destructor Documentation
template<typename T , typename ConversionErrorPolicy > G4AttValueFilterT< T, ConversionErrorPolicy >::G4AttValueFilterT ()
Definition at line 107 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AttValueFilterT.hh
template<typename T , typename ConversionErrorPolicy > G4AttValueFilterT< T, ConversionErrorPolicy >::~G4AttValueFilterT () virtual
Definition at line 110 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 110 of file G4AttValueFilterT.hh
Member Function Documentation
template<typename T , typename ConversionErrorPolicy > G4bool G4AttValueFilterT< T, ConversionErrorPolicy >::Accept (const G4AttValue & attVal) const virtual
Implements G4VAttValueFilter.
Definition at line 142 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 142 of file G4AttValueFilterT.hh
References G4ConversionUtils::Convert(), G4AttValue::GetValue(), and T.
template<typename T , typename ConversionErrorPolicy > G4bool G4AttValueFilterT< T, ConversionErrorPolicy >::GetValidElement (const G4AttValue & input, G4String & interval) const virtual
Implements G4VAttValueFilter.
Definition at line 114 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AttValueFilterT.hh
References G4ConversionUtils::Convert(), G4String::first(), G4AttValue::GetValue(), and T.
template<typename T , typename ConversionErrorPolicy > void G4AttValueFilterT< T, ConversionErrorPolicy >::LoadIntervalElement (const G4String & input) virtual
Implements G4VAttValueFilter.
Definition at line 164 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 164 of file G4AttValueFilterT.hh
References G4ConversionUtils::Convert(), max, min, and T.
template<typename T , typename ConversionErrorPolicy > void G4AttValueFilterT< T, ConversionErrorPolicy >::LoadSingleValueElement (const G4String & input) virtual
Implements G4VAttValueFilter.
Definition at line 177 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 177 of file G4AttValueFilterT.hh
References G4ConversionUtils::Convert(), and T.
template<typename T , typename ConversionErrorPolicy > void G4AttValueFilterT< T, ConversionErrorPolicy >::PrintAll (std::ostream & ostr) const virtual
Implements G4VAttValueFilter.
Definition at line 188 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 188 of file G4AttValueFilterT.hh
References configureMap::Name.
template<typename T , typename ConversionErrorPolicy > void G4AttValueFilterT< T, ConversionErrorPolicy >::Reset () virtual
Implements G4VAttValueFilter.
Definition at line 213 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 213 of file G4AttValueFilterT.hh
Member Data Documentation
template<typename T , typename ConversionErrorPolicy = G4ConversionFatalError> IntervalMap G4AttValueFilterT< T, ConversionErrorPolicy >::fIntervalMap private
Definition at line 101 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AttValueFilterT.hh
template<typename T , typename ConversionErrorPolicy = G4ConversionFatalError> SingleValueMap G4AttValueFilterT< T, ConversionErrorPolicy >::fSingleValueMap private
Definition at line 102 of file G4AttValueFilterT.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AttValueFilterT.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4AttValueFilterT.hh