ECCE @ EIC Software: G4NRESP71M03 Class Reference
G4NRESP71M03 Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4NRESP71M03.hh>
Public Member Functions
G4NRESP71M03 ()
~G4NRESP71M03 ()
void DKINMA (G4ReactionProduct *p1, G4ReactionProduct *p2, G4ReactionProduct *p3, G4ReactionProduct *p4, const G4double Q, const G4double costhcm3)
G4int ApplyMechanismI_NBeA2A (G4ReactionProduct &neut, G4ReactionProduct &carb, G4ReactionProduct *theProds, const G4double QI)
G4int ApplyMechanismII_ACN2A (G4ReactionProduct &neut, G4ReactionProduct &carb, G4ReactionProduct *theProds, const G4double QI)
G4int ApplyMechanismABE (G4ReactionProduct &neut, G4ReactionProduct &carb, G4ReactionProduct *theProds)
Static Private Attributes
static const G4int ndist = 32
static const G4int nrhos = 51
static const G4double BEN2 [ndist] = { 5700., 8000., 8640., 8990., 9220., 9410., 9830., 10400., 10800., 11250., 11460., 11870., 12140., 12320., 12570., 12940., 13420., 13760., 14020., 14200., 14440., 14620., 14820., 15050., 15660., 15980., 16470., 16940., 17970., 18000., 19000., 20000. }
static const G4double B2 [ndist][nrhos]
Detailed Description
Definition at line 36 of file G4NRESP71M03.hh.
View newest version in sPHENIX GitHub at line 36 of file G4NRESP71M03.hh
Constructor & Destructor Documentation
G4NRESP71M03::G4NRESP71M03 () inline
Definition at line 40 of file G4NRESP71M03.hh.
View newest version in sPHENIX GitHub at line 40 of file G4NRESP71M03.hh
G4NRESP71M03::~G4NRESP71M03 () inline
Definition at line 41 of file G4NRESP71M03.hh.
View newest version in sPHENIX GitHub at line 41 of file G4NRESP71M03.hh
Member Function Documentation
G4int G4NRESP71M03::ApplyMechanismABE (G4ReactionProduct & neut, G4ReactionProduct & carb, G4ReactionProduct * theProds)
Definition at line 202 of file G4NRESP71M03.cc.
View newest version in sPHENIX GitHub at line 202 of file G4NRESP71M03.cc
References G4Alpha::Alpha(), B2, BEN2, DKINMA(), G4UniformRand, G4IonTable::GetIonTable(), G4ReactionProduct::GetKineticEnergy(), keV, MeV, ndist, and G4ReactionProduct::SetDefinition().
Referenced by G4ParticleHPInelasticCompFS::use_nresp71_model().
G4int G4NRESP71M03::ApplyMechanismI_NBeA2A (G4ReactionProduct & neut, G4ReactionProduct & carb, G4ReactionProduct * theProds, const G4double QI)
Definition at line 147 of file G4NRESP71M03.cc.
View newest version in sPHENIX GitHub at line 147 of file G4NRESP71M03.cc
References G4Alpha::Alpha(), DKINMA(), G4UniformRand, G4Neutron::Neutron(), and G4ReactionProduct::SetDefinition().
Referenced by G4ParticleHPInelasticCompFS::use_nresp71_model().
G4int G4NRESP71M03::ApplyMechanismII_ACN2A (G4ReactionProduct & neut, G4ReactionProduct & carb, G4ReactionProduct * theProds, const G4double QI)
Definition at line 175 of file G4NRESP71M03.cc.
View newest version in sPHENIX GitHub at line 175 of file G4NRESP71M03.cc
References G4Alpha::Alpha(), DKINMA(), G4UniformRand, G4Neutron::Neutron(), and G4ReactionProduct::SetDefinition().
Referenced by G4ParticleHPInelasticCompFS::use_nresp71_model().
void G4NRESP71M03::DKINMA (G4ReactionProduct * p1, G4ReactionProduct * p2, G4ReactionProduct * p3, G4ReactionProduct * p4, const G4double Q, const G4double costhcm3)
Definition at line 76 of file G4NRESP71M03.cc.
View newest version in sPHENIX GitHub at line 76 of file G4NRESP71M03.cc
References G4UniformRand, G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4ReactionProduct::GetTotalEnergy(), CLHEP::HepRotation::inverse(), G4ReactionProduct::Lorentz(), phi, Q, G4ReactionProduct::SetMass(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), theta(), twopi, and CLHEP::Hep3Vector::unit().
Referenced by ApplyMechanismABE(), ApplyMechanismI_NBeA2A(), and ApplyMechanismII_ACN2A().
Member Data Documentation
const G4double G4NRESP71M03::B2 static private
Definition at line 57 of file G4NRESP71M03.hh.
View newest version in sPHENIX GitHub at line 57 of file G4NRESP71M03.hh
Referenced by ApplyMechanismABE().
const G4double G4NRESP71M03::BEN2 = { 5700., 8000., 8640., 8990., 9220., 9410., 9830., 10400., 10800., 11250., 11460., 11870., 12140., 12320., 12570., 12940., 13420., 13760., 14020., 14200., 14440., 14620., 14820., 15050., 15660., 15980., 16470., 16940., 17970., 18000., 19000., 20000. } static private
Definition at line 55 of file G4NRESP71M03.hh.
View newest version in sPHENIX GitHub at line 55 of file G4NRESP71M03.hh
Referenced by ApplyMechanismABE().
const G4int G4NRESP71M03::ndist = 32 static private
Definition at line 52 of file G4NRESP71M03.hh.
View newest version in sPHENIX GitHub at line 52 of file G4NRESP71M03.hh
Referenced by ApplyMechanismABE().
const G4int G4NRESP71M03::nrhos = 51 static private
Definition at line 53 of file G4NRESP71M03.hh.
View newest version in sPHENIX GitHub at line 53 of file G4NRESP71M03.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4NRESP71M03.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4NRESP71M03.cc