ECCE @ EIC Software: G4StatMFMicroManager Class Reference
G4StatMFMicroManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMicroManager.hh>
Classes
struct DeleteFragment
Public Member Functions
G4StatMFMicroManager (const G4Fragment &theFragment, G4int multiplicity, G4double FreeIntE, G4double SCompNuc)
~G4StatMFMicroManager ()
G4bool operator== (const G4StatMFMicroManager &right) const
G4bool operator!= (const G4StatMFMicroManager &right) const
G4StatMFChannel * ChooseChannel (G4int A0, G4int Z0, G4double MeanT)
G4double GetProbability (void) const
void Normalize (G4double Norm)
G4double GetMeanMultiplicity (void) const
G4double GetMeanTemperature (void) const
G4double GetMeanEntropy (void) const
Private Member Functions
G4StatMFMicroManager ()
G4StatMFMicroManager (const G4StatMFMicroManager &right)
G4StatMFMicroManager & operator= (const G4StatMFMicroManager &right)
void Initialize (const G4Fragment &theFragment, G4int m, G4double FreeIntE, G4double SCompNuc)
G4bool MakePartition (G4int k, G4int *ANumbers)
Private Attributes
std::vector
< G4StatMFMicroPartition * > _Partition
G4double _WW
G4double _Normalization
G4double _MeanMultiplicity
G4double _MeanTemperature
G4double _MeanEntropy
Detailed Description
Definition at line 43 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 43 of file G4StatMFMicroManager.hh
Constructor & Destructor Documentation
G4StatMFMicroManager::G4StatMFMicroManager (const G4Fragment & theFragment, G4int multiplicity, G4double FreeIntE, G4double SCompNuc)
Definition at line 62 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 62 of file G4StatMFMicroManager.cc
References Initialize().
G4StatMFMicroManager::~G4StatMFMicroManager ()
Definition at line 72 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4StatMFMicroManager.cc
References _Partition.
G4StatMFMicroManager::G4StatMFMicroManager () inline private
Definition at line 57 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 57 of file G4StatMFMicroManager.hh
G4StatMFMicroManager::G4StatMFMicroManager (const G4StatMFMicroManager & right) private
Definition at line 35 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 35 of file G4StatMFMicroManager.cc
Member Function Documentation
G4StatMFChannel * G4StatMFMicroManager::ChooseChannel (G4int A0, G4int Z0, G4double MeanT)
Definition at line 170 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 170 of file G4StatMFMicroManager.cc
References _Normalization, _Partition, _WW, and G4UniformRand.
G4double G4StatMFMicroManager::GetMeanEntropy (void) const inline
Definition at line 85 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 85 of file G4StatMFMicroManager.hh
References _MeanEntropy.
G4double G4StatMFMicroManager::GetMeanMultiplicity (void) const inline
Definition at line 81 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 81 of file G4StatMFMicroManager.hh
References _MeanMultiplicity.
G4double G4StatMFMicroManager::GetMeanTemperature (void) const inline
Definition at line 83 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 83 of file G4StatMFMicroManager.hh
References _MeanTemperature.
G4double G4StatMFMicroManager::GetProbability (void) const inline
Definition at line 77 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 77 of file G4StatMFMicroManager.hh
References _WW.
void G4StatMFMicroManager::Initialize (const G4Fragment & theFragment, G4int m, G4double FreeIntE, G4double SCompNuc) private
Definition at line 81 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 81 of file G4StatMFMicroManager.cc
References _MeanEntropy, _MeanMultiplicity, _MeanTemperature, _Partition, _WW, A(), G4StatMFMicroPartition::CalcPartitionProbability(), G4Fragment::GetA_asInt(), G4StatMFMicroPartition::GetEntropy(), G4Fragment::GetExcitationEnergy(), G4StatMFMicroPartition::GetTemperature(), G4Fragment::GetZ_asInt(), MakePartition(), G4StatMFMicroPartition::SetPartitionFragment(), and Z.
Referenced by G4StatMFMicroManager().
G4bool G4StatMFMicroManager::MakePartition (G4int k, G4int * ANumbers) private
Definition at line 138 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 138 of file G4StatMFMicroManager.cc
References tmp.
Referenced by Initialize().
void G4StatMFMicroManager::Normalize (G4double Norm)
Definition at line 158 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 158 of file G4StatMFMicroManager.cc
References _MeanEntropy, _MeanMultiplicity, _MeanTemperature, _Normalization, and _WW.
G4bool G4StatMFMicroManager::operator!= (const G4StatMFMicroManager & right) const
Definition at line 56 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 56 of file G4StatMFMicroManager.cc
G4StatMFMicroManager & G4StatMFMicroManager::operator= (const G4StatMFMicroManager & right) private
Definition at line 43 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 43 of file G4StatMFMicroManager.cc
G4bool G4StatMFMicroManager::operator== (const G4StatMFMicroManager & right) const
Definition at line 50 of file G4StatMFMicroManager.cc.
View newest version in sPHENIX GitHub at line 50 of file G4StatMFMicroManager.cc
Member Data Documentation
G4double G4StatMFMicroManager::_MeanEntropy private
Definition at line 115 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 115 of file G4StatMFMicroManager.hh
Referenced by GetMeanEntropy(), Initialize(), and Normalize().
G4double G4StatMFMicroManager::_MeanMultiplicity private
Definition at line 111 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 111 of file G4StatMFMicroManager.hh
Referenced by GetMeanMultiplicity(), Initialize(), and Normalize().
G4double G4StatMFMicroManager::_MeanTemperature private
Definition at line 113 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4StatMFMicroManager.hh
Referenced by GetMeanTemperature(), Initialize(), and Normalize().
G4double G4StatMFMicroManager::_Normalization private
Definition at line 109 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 109 of file G4StatMFMicroManager.hh
Referenced by ChooseChannel(), and Normalize().
std::vector<G4StatMFMicroPartition*> G4StatMFMicroManager::_Partition private
Definition at line 103 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 103 of file G4StatMFMicroManager.hh
Referenced by ChooseChannel(), Initialize(), and ~G4StatMFMicroManager().
G4double G4StatMFMicroManager::_WW private
Definition at line 107 of file G4StatMFMicroManager.hh.
View newest version in sPHENIX GitHub at line 107 of file G4StatMFMicroManager.hh
Referenced by ChooseChannel(), GetProbability(), Initialize(), and Normalize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMicroManager.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMicroManager.cc