ECCE @ EIC Software: G4ParticleHPDeExGammas Class Reference
G4ParticleHPDeExGammas Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPDeExGammas.hh>
Public Member Functions
G4ParticleHPDeExGammas ()
~G4ParticleHPDeExGammas ()
void Init (std::istream &aDataFile)
G4ReactionProductVector * GetDecayGammas (G4int aLevel)
G4ParticleHPLevel * GetLevel (G4int i)
G4int GetNumberOfLevels ()
G4double GetLevelEnergy (G4int aLevel)
Private Attributes
G4int * levelStart
G4int * levelSize
G4int nLevels
G4ParticleHPLevel * theLevels
Detailed Description
Definition at line 43 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ParticleHPDeExGammas.hh
Constructor & Destructor Documentation
G4ParticleHPDeExGammas::G4ParticleHPDeExGammas () inline
Definition at line 47 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPDeExGammas.hh
References levelSize, levelStart, nLevels, and theLevels.
G4ParticleHPDeExGammas::~G4ParticleHPDeExGammas () inline
Definition at line 54 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPDeExGammas.hh
References levelSize, levelStart, and theLevels.
Member Function Documentation
G4ReactionProductVector* G4ParticleHPDeExGammas::GetDecayGammas (G4int aLevel) inline
Definition at line 63 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 63 of file G4ParticleHPDeExGammas.hh
References G4UniformRand, G4ReactionProduct::GetTotalMomentum(), nLevels, phi, G4ReactionProduct::SetMomentum(), theLevels, theta(), and CLHEP::twopi.
Referenced by G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::CompositeApply().
G4ParticleHPLevel* G4ParticleHPDeExGammas::GetLevel (G4int i) inline
Definition at line 91 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPDeExGammas.hh
References G4cout, G4endl, nLevels, and theLevels.
Referenced by G4ParticleHPInelasticCompFS::CompositeApply().
G4double G4ParticleHPDeExGammas::GetLevelEnergy (G4int aLevel) inline
Definition at line 100 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ParticleHPDeExGammas.hh
References G4ParticleHPLevel::GetLevelEnergy(), nLevels, and theLevels.
Referenced by G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::CompositeApply(), and Init().
G4int G4ParticleHPDeExGammas::GetNumberOfLevels () inline
Definition at line 98 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPDeExGammas.hh
References nLevels.
Referenced by G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::CompositeApply().
void G4ParticleHPDeExGammas::Init (std::istream & aDataFile)
Definition at line 37 of file G4ParticleHPDeExGammas.cc.
View newest version in sPHENIX GitHub at line 37 of file G4ParticleHPDeExGammas.cc
References kdfinder::abs(), buffer, epsilon(), G4ParticleHPGamma::GetGammaEnergy(), G4ParticleHPLevel::GetLevelEnergy(), G4ParticleHPGamma::GetLevelEnergy(), GetLevelEnergy(), G4ParticleHPGamma::Init(), it, keV, levelSize, levelStart, min, nLevels, G4ParticleHPLevel::SetGamma(), G4ParticleHPGamma::SetNext(), G4ParticleHPLevel::SetNumberOfGammas(), and theLevels.
Referenced by G4ParticleHPInelasticBaseFS::InitGammas(), and G4ParticleHPInelasticCompFS::InitGammas().
Member Data Documentation
G4int* G4ParticleHPDeExGammas::levelSize private
Definition at line 109 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPDeExGammas.hh
Referenced by G4ParticleHPDeExGammas(), Init(), and ~G4ParticleHPDeExGammas().
G4int* G4ParticleHPDeExGammas::levelStart private
Definition at line 108 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPDeExGammas.hh
Referenced by G4ParticleHPDeExGammas(), Init(), and ~G4ParticleHPDeExGammas().
G4int G4ParticleHPDeExGammas::nLevels private
Definition at line 110 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPDeExGammas.hh
Referenced by G4ParticleHPDeExGammas(), GetDecayGammas(), GetLevel(), GetLevelEnergy(), GetNumberOfLevels(), and Init().
G4ParticleHPLevel* G4ParticleHPDeExGammas::theLevels private
Definition at line 111 of file G4ParticleHPDeExGammas.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPDeExGammas.hh
Referenced by G4ParticleHPDeExGammas(), GetDecayGammas(), GetLevel(), GetLevelEnergy(), Init(), and ~G4ParticleHPDeExGammas().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPDeExGammas.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPDeExGammas.cc