ECCE @ EIC Software: G4ParticleChangeForMSC Class Reference
G4ParticleChangeForMSC Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForMSC.hh>
Public Member Functions
G4ParticleChangeForMSC ()
virtual ~G4ParticleChangeForMSC ()
virtual G4Step * UpdateStepForAlongStep (G4Step *Step)
virtual G4Step * UpdateStepForPostStep (G4Step *Step)
virtual void Initialize (const G4Track &)
void ProposeMomentumDirection (const G4ThreeVector &Pfinal)
void ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz)
const G4ThreeVector * GetMomentumDirection () const
const G4ThreeVector * GetProposedMomentumDirection () const
void SetProposedMomentumDirection (const G4ThreeVector &Pfinal)
const G4ThreeVector * GetPosition () const
void ProposePosition (const G4ThreeVector &finalPosition)
const G4ThreeVector * GetProposedPosition () const
void SetProposedPosition (const G4ThreeVector &finalPosition)
virtual void DumpInfo () const
virtual G4bool CheckIt (const G4Track &)
Public Member Functions inherited from G4VParticleChange
G4VParticleChange ()
virtual ~G4VParticleChange ()
G4bool operator== (const G4VParticleChange &right) const
G4bool operator!= (const G4VParticleChange &right) const
virtual G4Step * UpdateStepForAtRest (G4Step *Step)
G4double GetTrueStepLength () const
void ProposeTrueStepLength (G4double truePathLength)
G4double GetLocalEnergyDeposit () const
void ProposeLocalEnergyDeposit (G4double anEnergyPart)
G4double GetNonIonizingEnergyDeposit () const
void ProposeNonIonizingEnergyDeposit (G4double anEnergyPart)
G4TrackStatus GetTrackStatus () const
void ProposeTrackStatus (G4TrackStatus status)
G4SteppingControl GetSteppingControl () const
void ProposeSteppingControl (G4SteppingControl StepControlFlag)
G4bool GetFirstStepInVolume () const
G4bool GetLastStepInVolume () const
void ProposeFirstStepInVolume (G4bool flag)
void ProposeLastStepInVolume (G4bool flag)
void Clear ()
void SetNumberOfSecondaries (G4int totSecondaries)
G4int GetNumberOfSecondaries () const
G4Track * GetSecondary (G4int anIndex) const
void AddSecondary (G4Track *aSecondary)
G4double GetWeight () const
G4double GetParentWeight () const
void ProposeWeight (G4double finalWeight)
void ProposeParentWeight (G4double finalWeight)
void SetSecondaryWeightByProcess (G4bool)
G4bool IsSecondaryWeightSetByProcess () const
void SetParentWeightByProcess (G4bool)
G4bool IsParentWeightSetByProcess () const
void SetVerboseLevel (G4int vLevel)
G4int GetVerboseLevel () const
void ClearDebugFlag ()
void SetDebugFlag ()
G4bool GetDebugFlag () const
Protected Member Functions
G4ParticleChangeForMSC (const G4ParticleChangeForMSC &right)
G4ParticleChangeForMSC & operator= (const G4ParticleChangeForMSC &right)
Protected Member Functions inherited from G4VParticleChange
G4VParticleChange (const G4VParticleChange &right)
G4VParticleChange & operator= (const G4VParticleChange &right)
G4Step * UpdateStepInfo (G4Step *Step)
void InitializeTrueStepLength (const G4Track &)
void InitializeLocalEnergyDeposit (const G4Track &)
void InitializeSteppingControl (const G4Track &)
void InitializeParentWeight (const G4Track &)
void InitializeParentGlobalTime (const G4Track &)
void InitializeStatusChange (const G4Track &)
void InitializeSecondaries (const G4Track &)
void InitializeStepInVolumeFlags (const G4Track &)
G4bool CheckSecondary (G4Track &)
G4double GetAccuracyForWarning () const
G4double GetAccuracyForException () const
Private Attributes
G4ThreeVector theMomentumDirection
G4ThreeVector thePosition
Additional Inherited Members
Protected Attributes inherited from G4VParticleChange
G4TrackFastVector * theListOfSecondaries
G4int theNumberOfSecondaries
G4int theSizeOftheListOfSecondaries
G4TrackStatus theStatusChange
G4SteppingControl theSteppingControlFlag
G4double theLocalEnergyDeposit
G4double theNonIonizingEnergyDeposit
G4double theTrueStepLength
G4bool theFirstStepInVolume
G4bool theLastStepInVolume
G4double theParentWeight
G4bool isParentWeightProposed
G4bool fSetSecondaryWeightByProcess
G4double theParentGlobalTime
G4int verboseLevel
G4bool debugFlag
Static Protected Attributes inherited from G4VParticleChange
static const G4double accuracyForWarning = 1.0e-9
static const G4double accuracyForException = 0.001
Detailed Description
Definition at line 53 of file G4ParticleChangeForMSC.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleChangeForMSC.hh
Constructor & Destructor Documentation
G4ParticleChangeForMSC::G4ParticleChangeForMSC ()
Definition at line 46 of file G4ParticleChangeForMSC.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleChangeForMSC.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChangeForMSC::~G4ParticleChangeForMSC () virtual
Definition at line 56 of file G4ParticleChangeForMSC.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleChangeForMSC.cc
References G4cout, G4endl, and G4VParticleChange::verboseLevel.
G4ParticleChangeForMSC::G4ParticleChangeForMSC (const G4ParticleChangeForMSC & right) protected
Definition at line 66 of file G4ParticleChangeForMSC.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleChangeForMSC.cc
References G4cout, G4endl, theMomentumDirection, thePosition, and G4VParticleChange::verboseLevel.
Member Function Documentation
G4bool G4ParticleChangeForMSC::CheckIt (const G4Track & aTrack) virtual
Reimplemented from G4VParticleChange.
Definition at line 168 of file G4ParticleChangeForMSC.cc.
View newest version in sPHENIX GitHub at line 168 of file G4ParticleChangeForMSC.cc
References G4VParticleChange::accuracyForException, G4VParticleChange::accuracyForWarning, G4VParticleChange::CheckIt(), DumpInfo(), EventMustBeAborted, G4cout, G4endl, G4Exception(), G4Track::GetDefinition(), G4Track::GetKineticEnergy(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), m, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), MeV, theMomentumDirection, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4ParticleChangeForMSC::DumpInfo () const virtual
Reimplemented from G4VParticleChange.
Definition at line 140 of file G4ParticleChangeForMSC.cc.
View newest version in sPHENIX GitHub at line 140 of file G4ParticleChangeForMSC.cc
References G4VParticleChange::DumpInfo(), G4cout, G4endl, mm, theMomentumDirection, thePosition, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by CheckIt().
const G4ThreeVector* G4ParticleChangeForMSC::GetMomentumDirection () const
Referenced by G4VMultipleScattering::AlongStepDoIt().
const G4ThreeVector* G4ParticleChangeForMSC::GetPosition () const
const G4ThreeVector* G4ParticleChangeForMSC::GetProposedMomentumDirection () const
const G4ThreeVector* G4ParticleChangeForMSC::GetProposedPosition () const
virtual void G4ParticleChangeForMSC::Initialize (const G4Track &) virtual
Reimplemented from G4VParticleChange.
Referenced by G4VMultipleScattering::PostStepDoIt().
G4ParticleChangeForMSC & G4ParticleChangeForMSC::operator= (const G4ParticleChangeForMSC & right) protected
Definition at line 77 of file G4ParticleChangeForMSC.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleChangeForMSC.cc
References G4cout, G4endl, G4VParticleChange::theListOfSecondaries, G4VParticleChange::theLocalEnergyDeposit, theMomentumDirection, G4VParticleChange::theNumberOfSecondaries, thePosition, G4VParticleChange::theSizeOftheListOfSecondaries, G4VParticleChange::theStatusChange, G4VParticleChange::theSteppingControlFlag, G4VParticleChange::theTrueStepLength, and G4VParticleChange::verboseLevel.
void G4ParticleChangeForMSC::ProposeMomentumDirection (const G4ThreeVector & Pfinal)
Referenced by G4VMultipleScattering::AlongStepDoIt(), G4WentzelVIModel::SampleScattering(), G4UrbanMscModel::SampleScattering(), G4UrbanAdjointMscModel::SampleScattering(), and G4GoudsmitSaundersonMscModel::SampleScattering().
void G4ParticleChangeForMSC::ProposeMomentumDirection (G4double Px, G4double Py, G4double Pz)
void G4ParticleChangeForMSC::ProposePosition (const G4ThreeVector & finalPosition)
Referenced by G4VMultipleScattering::AlongStepDoIt().
void G4ParticleChangeForMSC::SetProposedMomentumDirection (const G4ThreeVector & Pfinal)
void G4ParticleChangeForMSC::SetProposedPosition (const G4ThreeVector & finalPosition)
G4Step * G4ParticleChangeForMSC::UpdateStepForAlongStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 103 of file G4ParticleChangeForMSC.cc.
View newest version in sPHENIX GitHub at line 103 of file G4ParticleChangeForMSC.cc
References G4Step::GetPostStepPoint(), G4Step::GetTrack(), G4Track::GetTrackStatus(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPosition(), G4Step::SetStepLength(), theMomentumDirection, thePosition, G4VParticleChange::theStatusChange, and G4VParticleChange::theTrueStepLength.
G4Step * G4ParticleChangeForMSC::UpdateStepForPostStep (G4Step * Step) virtual
Reimplemented from G4VParticleChange.
Definition at line 120 of file G4ParticleChangeForMSC.cc.
View newest version in sPHENIX GitHub at line 120 of file G4ParticleChangeForMSC.cc
References G4Step::GetPostStepPoint(), G4StepPoint::SetMomentumDirection(), G4StepPoint::SetPosition(), theMomentumDirection, and thePosition.
Member Data Documentation
G4ThreeVector G4ParticleChangeForMSC::theMomentumDirection private
Definition at line 107 of file G4ParticleChangeForMSC.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleChangeForMSC.hh
Referenced by CheckIt(), DumpInfo(), G4ParticleChangeForMSC(), operator=(), UpdateStepForAlongStep(), and UpdateStepForPostStep().
G4ThreeVector G4ParticleChangeForMSC::thePosition private
Definition at line 114 of file G4ParticleChangeForMSC.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleChangeForMSC.hh
Referenced by DumpInfo(), G4ParticleChangeForMSC(), operator=(), UpdateStepForAlongStep(), and UpdateStepForPostStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4ParticleChangeForMSC.hh
geant4/tree/geant4-10.6-release/source/track/src/G4ParticleChangeForMSC.cc