ECCE @ EIC Software: G4PhysicsVector Class Reference
G4PhysicsVector Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4PhysicsVector.hh>
Public Member Functions
G4PhysicsVector (G4bool spline=false)
G4PhysicsVector (const G4PhysicsVector &)
G4PhysicsVector & operator= (const G4PhysicsVector &)
virtual ~G4PhysicsVector ()
G4double Value (G4double theEnergy, size_t &lastidx) const
G4double LogVectorValue (const G4double theEnergy, const G4double theLogEnergy) const
G4double Value (G4double theEnergy) const
G4double GetValue (G4double theEnergy, G4bool &isOutRange) const
G4bool operator== (const G4PhysicsVector &right) const
G4bool operator!= (const G4PhysicsVector &right) const
G4double operator[] (const size_t index) const
G4double operator() (const size_t index) const
void PutValue (size_t index, G4double theValue)
virtual void ScaleVector (G4double factorE, G4double factorV)
G4double Energy (size_t index) const
G4double GetMaxEnergy () const
G4double GetLowEdgeEnergy (size_t binNumber) const
size_t GetVectorLength () const
size_t FindBin (G4double energy, size_t idx) const
size_t ComputeLogVectorBin (const G4double logenergy) const
void FillSecondDerivatives ()
void ComputeSecDerivatives ()
void ComputeSecondDerivatives (G4double firstPointDerivative, G4double endPointDerivative)
G4double FindLinearEnergy (G4double rand) const
G4bool IsFilledVectorExist () const
G4PhysicsVectorType GetType () const
void SetSpline (G4bool)
G4bool Store (std::ofstream &fOut, G4bool ascii=false) const
virtual G4bool Retrieve (std::ifstream &fIn, G4bool ascii=false)
void DumpValues (G4double unitE=1.0, G4double unitV=1.0) const
void SetVerboseLevel (G4int value)
G4double Interpolation (size_t idx, G4double energy) const
Protected Member Functions
void DeleteData ()
void CopyData (const G4PhysicsVector &vec)
void PrintPutValueError (size_t index)
Protected Attributes
G4PhysicsVectorType type
G4double edgeMin
G4double edgeMax
size_t numberOfNodes
G4PVDataVector dataVector
G4PVDataVector binVector
G4PVDataVector secDerivative
G4double invdBin
G4double baseBin
G4int verboseLevel
Private Member Functions
G4bool SplinePossible ()
G4double LinearInterpolation (size_t idx, G4double energy) const
G4double SplineInterpolation (size_t idx, G4double energy) const
size_t FindBinLocation (G4double theEnergy) const
Private Attributes
G4bool useSpline
Friends
std::ostream & operator<< (std::ostream &, const G4PhysicsVector &)
Detailed Description
Definition at line 78 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PhysicsVector.hh
Constructor & Destructor Documentation
G4PhysicsVector::G4PhysicsVector (G4bool spline = false) explicit
Definition at line 60 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 60 of file G4PhysicsVector.cc
G4PhysicsVector::G4PhysicsVector (const G4PhysicsVector & right)
Definition at line 75 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 75 of file G4PhysicsVector.cc
References baseBin, CopyData(), DeleteData(), invdBin, and verboseLevel.
G4PhysicsVector::~G4PhysicsVector () virtual
Definition at line 70 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 70 of file G4PhysicsVector.cc
Member Function Documentation
size_t G4PhysicsVector::ComputeLogVectorBin (const G4double logenergy) const inline
void G4PhysicsVector::ComputeSecDerivatives ()
Definition at line 430 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 430 of file G4PhysicsVector.cc
References binVector, dataVector, n, numberOfNodes, secDerivative, SplinePossible(), and useSpline.
Referenced by ComputeSecondDerivatives(), and FillSecondDerivatives().
void G4PhysicsVector::ComputeSecondDerivatives (G4double firstPointDerivative, G4double endPointDerivative)
Definition at line 293 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 293 of file G4PhysicsVector.cc
References binVector, ComputeSecDerivatives(), dataVector, k, n, numberOfNodes, secDerivative, SplinePossible(), Acts::UnitConstants::u, and useSpline.
void G4PhysicsVector::CopyData (const G4PhysicsVector & vec) protected
Definition at line 123 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 123 of file G4PhysicsVector.cc
References binVector, dataVector, edgeMax, edgeMin, numberOfNodes, secDerivative, type, and useSpline.
Referenced by G4PhysicsVector(), and operator=().
void G4PhysicsVector::DeleteData () protected
Definition at line 115 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 115 of file G4PhysicsVector.cc
References secDerivative, and useSpline.
Referenced by G4PhysicsVector(), and operator=().
void G4PhysicsVector::DumpValues (G4double unitE = 1.0, G4double unitV = 1.0) const
Definition at line 265 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 265 of file G4PhysicsVector.cc
References binVector, dataVector, G4cout, G4endl, and numberOfNodes.
Referenced by G4OpRayleigh::DumpPhysicsTable(), G4OpWLS::DumpPhysicsTable(), G4Cerenkov::DumpPhysicsTable(), G4Scintillation::DumpPhysicsTable(), G4SPSEneDistribution::GenUserHistEnergies(), and G4SPSEneDistribution::LinearInterpolation().
G4double G4PhysicsVector::Energy (size_t index) const inline
Referenced by G4EmCorrections::BarkasCorrection(), G4DiffuseElasticV2::BuildAngleTable(), G4PolarizedCompton::BuildAsymmetryTable(), G4ePolarizedIonisation::BuildAsymmetryTables(), G4EmCorrections::BuildCorrectionVector(), G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), WLSPrimaryGeneratorAction::BuildEmissionSpectrum(), G4LossTableBuilder::BuildInverseRangeTable(), G4VRangeToEnergyConverter::BuildLossTable(), G4OpWLS::BuildPhysicsTable(), G4LossTableBuilder::BuildRangeTable(), G4PenelopeBremsstrahlungFS::BuildScaledXSTable(), G4LossTableBuilder::BuildTableForModel(), G4Cerenkov::BuildThePhysicsTable(), G4Scintillation::BuildThePhysicsTable(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4eeToHadronsModel::ComputeCMCrossSectionPerElectron(), G4LivermoreRayleighModel::ComputeCrossSectionPerAtom(), G4LivermoreComptonModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedRayleighModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedComptonModel::ComputeCrossSectionPerAtom(), G4JAEAElasticScatteringModel::ComputeCrossSectionPerAtom(), G4LowEPComptonModel::ComputeCrossSectionPerAtom(), G4LowEPPolarizedComptonModel::ComputeCrossSectionPerAtom(), G4TablesForExtrapolator::ComputeElectronDEDX(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), G4EmModelManager::DumpModelList(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4VEmProcess::FindLambdaMax(), G4HadElementSelector::G4HadElementSelector(), G4LivermorePhotoElectricModel::GetBindingEnergy(), G4ICRU90StoppingData::GetDEDX(), G4PAIPhotData::GetEnergyPhotonTransfer(), G4PAIPhotData::GetEnergyPlasmonTransfer(), G4PAIModelData::GetEnergyTransfer(), G4PAIPhotData::GetEnergyTransfer(), G4DNABornExcitationModel2::Initialise(), G4eplusTo2GammaOKVIModel::Initialise(), G4eeToHadronsModel::Initialise(), G4WentzelVIModel::Initialise(), G4HadronXSDataTable::Initialise(), G4NeutronCaptureXS::IsoCrossSection(), G4GDMLWriteMaterials::PropertyVectorWrite(), PHG4GDMLWriteMaterials::PropertyVectorWrite(), G4PAIPhotData::SampleAlongStepPhotonTransfer(), G4PAIPhotData::SampleAlongStepPlasmonTransfer(), G4PAIPhotData::SampleAlongStepTransfer(), G4PAIModelData::SampleAlongStepTransfer(), G4PAIModelData::SamplePostStepTransfer(), G4DiffuseElasticV2::SampleTableThetaCMS(), G4VEnergyLossProcess::ScaledKinEnergyForLoss(), G4VEnergyLossProcess::SetLambdaTable(), and G4VEmProcess::StreamInfo().
void G4PhysicsVector::FillSecondDerivatives ()
Definition at line 358 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 358 of file G4PhysicsVector.cc
References binVector, ComputeSecDerivatives(), dataVector, k, n, numberOfNodes, secDerivative, SplinePossible(), Acts::UnitConstants::u, and useSpline.
Referenced by G4ASTARStopping::AddData(), G4PSTARStopping::AddData(), G4ICRU90StoppingData::AddData(), G4LossTableBuilder::BuildDEDXTable(), G4VEnergyLossProcess::BuildDEDXTable(), G4LossTableBuilder::BuildInverseRangeTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4LossTableBuilder::BuildRangeTable(), G4LossTableBuilder::BuildTableForModel(), G4TablesForExtrapolator::ComputeElectronDEDX(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), and G4WentzelVIModel::Initialise().
size_t G4PhysicsVector::FindBin (G4double energy, size_t idx) const inline
Referenced by G4DiffuseElasticV2::SampleTableThetaCMS(), and Value().
size_t G4PhysicsVector::FindBinLocation (G4double theEnergy) const inline private
G4double G4PhysicsVector::FindLinearEnergy (G4double rand) const
Definition at line 515 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 515 of file G4PhysicsVector.cc
References bin, binVector, dataVector, min, numberOfNodes, and y.
Referenced by G4AdjointPrimaryGenerator::SampleDistanceAlongBackRayAndComputeWeightCorrection().
G4double G4PhysicsVector::GetLowEdgeEnergy (size_t binNumber) const
Definition at line 150 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 150 of file G4PhysicsVector.cc
References binVector.
Referenced by G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4NuclNuclDiffuseElastic::BuildAngleTable(), G4DiffuseElastic::BuildAngleTable(), G4VXTRenergyLoss::BuildAngleTable(), G4eplusPolarizedAnnihilation::BuildAsymmetryTables(), G4eLowEnergyLoss::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), G4PenelopeIonisationXSHandler::BuildDeltaTable(), G4VXTRenergyLoss::BuildEnergyTable(), G4VXTRenergyLoss::BuildGlobalAngleTable(), G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildLabTimeVector(), G4hRDEnergyLoss::BuildLabTimeVector(), G4hImpactIonisation::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4VLEPTSModel::BuildMeanFreePathTable(), G4RDVeLowEnergyLoss::BuildProperTimeVector(), G4hRDEnergyLoss::BuildProperTimeVector(), G4VRangeToEnergyConverter::BuildRangeVector(), G4RDVeLowEnergyLoss::BuildRangeVector(), G4hRDEnergyLoss::BuildRangeVector(), G4hhElastic::BuildTableT(), G4AdjointCSManager::BuildTotalSigmaTables(), G4ForwardXrayTR::BuildXrayTRtables(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4PenelopeBremsstrahlungModel::BuildXSTable(), G4VRangeToEnergyConverter::ConvertCutToKineticEnergy(), G4SPSEneDistribution::ConvertEPNToEnergy(), G4PenelopeRayleighModel::DumpFormFactorTable(), G4SPSEneDistribution::ExpInterpolation(), G4SPSEneDistribution::GenArbPointEnergies(), G4SPSEneDistribution::GenEpnHistEnergies(), G4SPSAngDistribution::GenerateUserDefPhi(), G4SPSAngDistribution::GenerateUserDefTheta(), G4SPSRandomGenerator::GenRandEnergy(), G4SPSRandomGenerator::GenRandPhi(), G4SPSRandomGenerator::GenRandPosPhi(), G4SPSRandomGenerator::GenRandPosTheta(), G4SPSRandomGenerator::GenRandTheta(), G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), G4SPSRandomGenerator::GenRandZ(), G4SPSEneDistribution::GenUserHistEnergies(), G4ForwardXrayTR::GetEnergyTR(), G4VXTRenergyLoss::GetMeanFreePath(), G4VXTRenergyLoss::GetXTRrandomEnergy(), G4NeutronElectronElXsc::Initialise(), G4NeutronElectronElModel::Initialise(), G4InitXscPAI::IntegralCherenkov(), G4InitXscPAI::IntegralPAIdEdx(), G4InitXscPAI::IntegralPAIxSection(), G4InitXscPAI::IntegralPlasmon(), G4RDVeLowEnergyLoss::InvertRangeVector(), G4hRDEnergyLoss::InvertRangeVector(), G4SPSEneDistribution::LinearInterpolation(), G4SPSEneDistribution::LogInterpolation(), G4PenelopeCrossSection::NormalizeShellCrossSections(), G4ForwardXrayTR::PostStepDoIt(), G4XNNElasticLowE::Print(), G4XnpTotalLowE::Print(), G4XnpElasticLowE::Print(), G4NuclNuclDiffuseElastic::SampleTableThetaCMS(), G4DiffuseElastic::SampleTableThetaCMS(), and G4SPSEneDistribution::SplineInterpolation().
G4double G4PhysicsVector::GetMaxEnergy () const inline
Referenced by G4EmModelManager::FillLambdaVector(), G4PAIModelData::GetEnergyTransfer(), G4Scintillation::GetScintillationYieldByParticleType(), G4NeutronInelasticXS::Initialise(), G4ParticleInelasticXS::Initialise(), G4PAIModelData::SampleAlongStepTransfer(), G4PAIModelData::SamplePostStepTransfer(), and G4VEmProcess::StreamInfo().
G4PhysicsVectorType G4PhysicsVector::GetType () const inline
G4double G4PhysicsVector::GetValue (G4double theEnergy, G4bool & isOutRange) const inline
Referenced by G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildLabTimeVector(), G4hRDEnergyLoss::BuildLabTimeVector(), G4RDVeLowEnergyLoss::BuildProperTimeVector(), G4hRDEnergyLoss::BuildProperTimeVector(), G4RDVeLowEnergyLoss::BuildRangeCoeffATable(), G4hRDEnergyLoss::BuildRangeCoeffATable(), G4RDVeLowEnergyLoss::BuildRangeCoeffBTable(), G4hRDEnergyLoss::BuildRangeCoeffBTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffCTable(), G4hRDEnergyLoss::BuildRangeCoeffCTable(), G4RDVeLowEnergyLoss::BuildRangeVector(), G4hRDEnergyLoss::BuildRangeVector(), G4XNNElasticLowE::CrossSection(), G4XResonance::CrossSection(), G4XnpTotalLowE::CrossSection(), G4XnpElasticLowE::CrossSection(), G4PartialWidthTable::Dump(), G4Cerenkov::GetAverageNumberOfPhotons(), G4ChargeExchangeProcess::GetElementCrossSection(), G4ParticleHPJENDLHEData::getXSfromThisIsotope(), G4RDVeLowEnergyLoss::LabTimeIntLog(), G4hRDEnergyLoss::LabTimeIntLog(), G4XNNElasticLowE::Print(), G4XnpTotalLowE::Print(), G4XnpElasticLowE::Print(), G4RDVeLowEnergyLoss::ProperTimeIntLog(), G4hRDEnergyLoss::ProperTimeIntLog(), G4RDVeLowEnergyLoss::RangeIntLin(), G4hRDEnergyLoss::RangeIntLin(), G4RDVeLowEnergyLoss::RangeIntLog(), G4hRDEnergyLoss::RangeIntLog(), G4XAnnihilationChannel::VariablePartialWidth(), and G4XAnnihilationChannel::VariableWidth().
size_t G4PhysicsVector::GetVectorLength () const inline
Referenced by G4ePolarizedIonisation::BuildAsymmetryTables(), G4LossTableBuilder::BuildDEDXTable(), G4PenelopeIonisationXSHandler::BuildDeltaTable(), WLSPrimaryGeneratorAction::BuildEmissionSpectrum(), G4LossTableBuilder::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4OpWLS::BuildPhysicsTable(), G4LossTableBuilder::BuildRangeTable(), G4Cerenkov::BuildThePhysicsTable(), G4Scintillation::BuildThePhysicsTable(), G4AdjointCSManager::BuildTotalSigmaTables(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4PenelopeBremsstrahlungModel::BuildXSTable(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4LivermoreRayleighModel::ComputeCrossSectionPerAtom(), G4LivermoreGammaConversionModelRC::ComputeCrossSectionPerAtom(), G4LivermoreNuclearGammaConversionModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedGammaConversionModel::ComputeCrossSectionPerAtom(), G4LivermoreComptonModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedRayleighModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedComptonModel::ComputeCrossSectionPerAtom(), G4JAEAElasticScatteringModel::ComputeCrossSectionPerAtom(), G4LowEPComptonModel::ComputeCrossSectionPerAtom(), G4LowEPPolarizedComptonModel::ComputeCrossSectionPerAtom(), G4SPSEneDistribution::ConvertEPNToEnergy(), G4PenelopeRayleighModel::DumpFormFactorTable(), G4EmModelManager::DumpModelList(), G4SPSEneDistribution::ExpInterpolation(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4VEmProcess::FindLambdaMax(), G4SPSEneDistribution::GenArbPointEnergies(), G4SPSEneDistribution::GenEpnHistEnergies(), G4SPSAngDistribution::GenerateUserDefPhi(), G4SPSAngDistribution::GenerateUserDefTheta(), G4SPSRandomGenerator::GenRandEnergy(), G4SPSRandomGenerator::GenRandPhi(), G4SPSRandomGenerator::GenRandPosPhi(), G4SPSRandomGenerator::GenRandPosTheta(), G4SPSRandomGenerator::GenRandTheta(), G4SPSRandomGenerator::GenRandX(), G4SPSRandomGenerator::GenRandY(), G4SPSRandomGenerator::GenRandZ(), G4SPSEneDistribution::GenUserHistEnergies(), G4PAIPhotData::GetEnergyPhotonTransfer(), G4PAIPhotData::GetEnergyPlasmonTransfer(), G4PAIModelData::GetEnergyTransfer(), G4PAIPhotData::GetEnergyTransfer(), G4PenelopeCrossSection::GetHardCrossSection(), G4PenelopeCrossSection::GetNormalizedShellCrossSection(), G4PenelopeCrossSection::GetShellCrossSection(), G4PenelopeCrossSection::GetSoftStoppingPower(), G4PenelopeCrossSection::GetTotalCrossSection(), G4eeToHadronsModel::Initialise(), G4NeutronInelasticXS::Initialise(), G4ParticleInelasticXS::Initialise(), G4SPSEneDistribution::LinearInterpolation(), G4SPSEneDistribution::LogInterpolation(), G4GDMLWriteMaterials::PropertyVectorWrite(), PHG4GDMLWriteMaterials::PropertyVectorWrite(), G4VEnergyLossProcess::SetLambdaTable(), G4SPSEneDistribution::SplineInterpolation(), and G4VEmProcess::StreamInfo().
G4double G4PhysicsVector::Interpolation (size_t idx, G4double energy) const inline
Referenced by Value().
G4bool G4PhysicsVector::IsFilledVectorExist () const inline
Referenced by G4Cerenkov::GetAverageNumberOfPhotons().
G4double G4PhysicsVector::LinearInterpolation (size_t idx, G4double energy) const inline private
G4double G4PhysicsVector::LogVectorValue (const G4double theEnergy, const G4double theLogEnergy) const inline
Referenced by G4GammaGeneralProcess::ComputeGeneralLambda(), G4GammaGeneralProcess::GetProbability(), and G4NeutronCaptureXS::IsoCrossSection().
G4bool G4PhysicsVector::operator!= (const G4PhysicsVector & right) const
Definition at line 108 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 108 of file G4PhysicsVector.cc
G4double G4PhysicsVector::operator() (const size_t index) const inline
G4PhysicsVector & G4PhysicsVector::operator= (const G4PhysicsVector & right)
Definition at line 87 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 87 of file G4PhysicsVector.cc
References baseBin, CopyData(), DeleteData(), invdBin, and verboseLevel.
G4bool G4PhysicsVector::operator== (const G4PhysicsVector & right) const
Definition at line 101 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 101 of file G4PhysicsVector.cc
G4double G4PhysicsVector::operator[] (const size_t index) const inline
void G4PhysicsVector::PrintPutValueError (size_t index) protected
Definition at line 532 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 532 of file G4PhysicsVector.cc
References FatalException, G4Exception(), numberOfNodes, and type.
Referenced by G4PhysicsFreeVector::PutValue().
void G4PhysicsVector::PutValue (size_t index, G4double theValue) inline
Referenced by G4RToEConvForGamma::BuildAbsorptionLengthVector(), G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4PolarizedCompton::BuildAsymmetryTable(), G4eplusPolarizedAnnihilation::BuildAsymmetryTables(), G4ePolarizedIonisation::BuildAsymmetryTables(), G4EmCorrections::BuildCorrectionVector(), G4KokoulinMuonNuclearXS::BuildCrossSectionTable(), G4LossTableBuilder::BuildDEDXTable(), G4eLowEnergyLoss::BuildDEDXTable(), G4hRDEnergyLoss::BuildDEDXTable(), G4VXTRenergyLoss::BuildEnergyTable(), G4VXTRenergyLoss::BuildGlobalAngleTable(), G4RDVeLowEnergyLoss::BuildInverseRangeTable(), G4hRDEnergyLoss::BuildInverseRangeTable(), G4RDVeLowEnergyLoss::BuildLabTimeVector(), G4hRDEnergyLoss::BuildLabTimeVector(), G4hImpactIonisation::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4VRangeToEnergyConverter::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4VLEPTSModel::BuildMeanFreePathTable(), G4ChargeExchangeProcess::BuildPhysicsTable(), G4VLEPTSModel::BuildPhysicsTable(), G4RDVeLowEnergyLoss::BuildProperTimeVector(), G4hRDEnergyLoss::BuildProperTimeVector(), G4RDVeLowEnergyLoss::BuildRangeCoeffATable(), G4hRDEnergyLoss::BuildRangeCoeffATable(), G4RDVeLowEnergyLoss::BuildRangeCoeffBTable(), G4hRDEnergyLoss::BuildRangeCoeffBTable(), G4RDVeLowEnergyLoss::BuildRangeCoeffCTable(), G4hRDEnergyLoss::BuildRangeCoeffCTable(), G4LossTableBuilder::BuildRangeTable(), G4VRangeToEnergyConverter::BuildRangeVector(), G4RDVeLowEnergyLoss::BuildRangeVector(), G4hRDEnergyLoss::BuildRangeVector(), G4LossTableBuilder::BuildTableForModel(), G4AdjointCSManager::BuildTotalSigmaTables(), G4ForwardXrayTR::BuildXrayTRtables(), G4eeToHadronsModel::ComputeCMCrossSectionPerElectron(), G4TablesForExtrapolator::ComputeElectronDEDX(), G4TablesForExtrapolator::ComputeMuonDEDX(), G4TablesForExtrapolator::ComputeProtonDEDX(), G4TablesForExtrapolator::ComputeTrasportXS(), G4EmModelManager::FillDEDXVector(), G4EmModelManager::FillLambdaVector(), G4NeutronElectronElXsc::G4NeutronElectronElXsc(), G4XNNElasticLowE::G4XNNElasticLowE(), G4XnpElasticLowE::G4XnpElasticLowE(), G4XnpTotalLowE::G4XnpTotalLowE(), G4NeutronElectronElXsc::Initialise(), G4DNABornExcitationModel2::Initialise(), G4eplusTo2GammaOKVIModel::Initialise(), G4eeToHadronsModel::Initialise(), G4PAIPhotData::Initialise(), G4WentzelVIModel::Initialise(), G4PAIModelData::Initialise(), G4HadronXSDataTable::Initialise(), G4InitXscPAI::IntegralCherenkov(), G4InitXscPAI::IntegralPAIdEdx(), G4InitXscPAI::IntegralPAIxSection(), G4InitXscPAI::IntegralPlasmon(), G4RDVeLowEnergyLoss::InvertRangeVector(), G4hRDEnergyLoss::InvertRangeVector(), G4VRangeToEnergyConverter::operator=(), G4ChannelingECHARM::ReadFromECHARM(), and G4ChannelingMaterialData::SetBR().
G4bool G4PhysicsVector::Retrieve (std::ifstream & fIn, G4bool ascii = false) virtual
Reimplemented in G4PhysicsLogVector, and G4PhysicsLinearVector.
Definition at line 190 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 190 of file G4PhysicsVector.cc
References binVector, dataVector, edgeMax, edgeMin, numberOfNodes, secDerivative, and true.
Referenced by G4LivermoreRayleighModel::ReadData(), G4LivermorePolarizedPhotoElectricGDModel::ReadData(), G4LivermorePolarizedPhotoElectricModel::ReadData(), G4LivermorePolarizedRayleighModel::ReadData(), G4LivermorePhotoElectricModel::ReadData(), G4ComponentSAIDTotalXS::ReadData(), G4PhysicsLinearVector::Retrieve(), G4PhysicsLogVector::Retrieve(), and G4PhysicsTable::RetrievePhysicsTable().
void G4PhysicsVector::ScaleVector (G4double factorE, G4double factorV) virtual
Reimplemented in G4PhysicsLogVector, and G4PhysicsLinearVector.
Definition at line 276 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 276 of file G4PhysicsVector.cc
References binVector, dataVector, edgeMax, edgeMin, n, and secDerivative.
Referenced by G4SPSEneDistribution::ExpInterpolation(), G4SPSEneDistribution::LinearInterpolation(), G4SPSEneDistribution::LogInterpolation(), G4LivermorePolarizedPhotoElectricGDModel::ReadData(), G4LivermorePolarizedPhotoElectricModel::ReadData(), G4LivermorePhotoElectricModel::ReadData(), G4ComponentSAIDTotalXS::ReadData(), G4PhysicsLinearVector::ScaleVector(), G4PhysicsLogVector::ScaleVector(), and G4SPSEneDistribution::SplineInterpolation().
void G4PhysicsVector::SetSpline (G4bool) inline
Referenced by G4WaterStopping::AddData(), G4ASTARStopping::AddData(), G4PSTARStopping::AddData(), G4ICRU90StoppingData::AddData(), G4UPiNuclearCrossSection::AddDataSet(), G4PolarizedCompton::BuildAsymmetryTable(), G4EmCorrections::BuildCorrectionVector(), G4LossTableBuilder::BuildDEDXTable(), G4VEnergyLossProcess::BuildDEDXTable(), G4PenelopeRayleighModel::BuildFormFactorTable(), G4LossTableBuilder::BuildInverseRangeTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4LossTableBuilder::BuildRangeTable(), G4LossTableBuilder::BuildTableForModel(), OpNoviceDetectorConstruction::Construct(), PHG4Reco::DefineMaterials(), G4EmElementSelector::G4EmElementSelector(), G4HadElementSelector::G4HadElementSelector(), G4DNABornExcitationModel2::Initialise(), G4eplusTo2GammaOKVIModel::Initialise(), G4HadronXSDataTable::Initialise(), G4EmCorrections::Initialise(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4GammaGeneralProcess::InitialiseProcess(), G4VEnergyLossProcess::LambdaPhysicsVector(), G4VEmProcess::LambdaPhysicsVector(), G4TablesForExtrapolator::PrepareTable(), G4PenelopeBremsstrahlungAngular::PrepareTables(), G4LivermorePolarizedPhotoElectricGDModel::ReadData(), G4JAEAElasticScatteringModel::ReadData(), G4LivermorePolarizedPhotoElectricModel::ReadData(), G4LivermorePhotoElectricModel::ReadData(), G4ComponentSAIDTotalXS::ReadData(), and EICG4dRICHOptics::setMatPropTable().
void G4PhysicsVector::SetVerboseLevel (G4int value) inline
G4double G4PhysicsVector::SplineInterpolation (size_t idx, G4double energy) const inline private
G4bool G4PhysicsVector::SplinePossible () private
Definition at line 458 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 458 of file G4PhysicsVector.cc
References binVector, numberOfNodes, secDerivative, and useSpline.
Referenced by ComputeSecDerivatives(), ComputeSecondDerivatives(), and FillSecondDerivatives().
G4bool G4PhysicsVector::Store (std::ofstream & fOut, G4bool ascii = false) const
Definition at line 157 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 157 of file G4PhysicsVector.cc
References binVector, dataVector, edgeMax, edgeMin, and numberOfNodes.
G4double G4PhysicsVector::Value (G4double theEnergy, size_t & lastidx) const
Definition at line 497 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 497 of file G4PhysicsVector.cc
References dataVector, edgeMax, edgeMin, FindBin(), Interpolation(), numberOfNodes, and y.
Referenced by G4EmCorrections::BarkasCorrection(), G4LossTableBuilder::BuildRangeTable(), G4OpBoundaryProcess::CalculateReflectivity(), G4Track::CalculateVelocityForOpticalPhoton(), G4eeToHadronsModel::ComputeCMCrossSectionPerElectron(), G4BoldyshevTripletModel::ComputeCrossSectionPerAtom(), G4LivermoreRayleighModel::ComputeCrossSectionPerAtom(), G4LivermoreGammaConversionModelRC::ComputeCrossSectionPerAtom(), G4LivermoreNuclearGammaConversionModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedGammaConversionModel::ComputeCrossSectionPerAtom(), G4LivermoreGammaConversionModel::ComputeCrossSectionPerAtom(), G4LivermoreComptonModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedRayleighModel::ComputeCrossSectionPerAtom(), G4LivermorePolarizedComptonModel::ComputeCrossSectionPerAtom(), G4PenelopeGammaConversionModel::ComputeCrossSectionPerAtom(), G4PenelopeRayleighModel::ComputeCrossSectionPerAtom(), G4JAEAElasticScatteringModel::ComputeCrossSectionPerAtom(), G4eplusTo2GammaOKVIModel::ComputeCrossSectionPerAtom(), G4PenelopePhotoElectricModel::ComputeCrossSectionPerAtom(), G4LowEPComptonModel::ComputeCrossSectionPerAtom(), G4LowEPPolarizedComptonModel::ComputeCrossSectionPerAtom(), G4eeToHadronsModel::ComputeCrossSectionPerElectron(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4VRangeToEnergyConverter::ConvertCutToKineticEnergy(), G4DNABornExcitationModel2::CrossSectionPerVolume(), G4eplusTo2GammaOKVIModel::CrossSectionPerVolume(), G4EmCorrections::EffectiveChargeCorrection(), G4eeToHadronsModel::GenerateCMPhoton(), G4ChannelingMaterialData::GetBR(), G4FastPathHadronicCrossSection::fastPathEntry::GetCrossSection(), G4ICRU90StoppingData::GetDEDX(), G4PenelopeIonisationXSHandler::GetDensityCorrection(), G4ChannelingECHARM::GetEC(), G4NeutronElectronElXsc::GetElementCrossSection(), G4KokoulinMuonNuclearXS::GetElementCrossSection(), G4PAIPhotData::GetEnergyPhotonTransfer(), G4PAIPhotData::GetEnergyPlasmonTransfer(), G4PAIModelData::GetEnergyTransfer(), G4PAIPhotData::GetEnergyTransfer(), G4PenelopeRayleighModel::GetFSquared(), G4PenelopeCrossSection::GetHardCrossSection(), G4OpMieHG::GetMeanFreePath(), G4OpAbsorption::GetMeanFreePath(), G4OpRayleigh::GetMeanFreePath(), G4PenelopeCrossSection::GetNormalizedShellCrossSection(), G4SPSEneDistribution::GetProbability(), G4OpBoundaryProcess::GetReflectivity(), G4Scintillation::GetScintillationYieldByParticleType(), G4PenelopeCrossSection::GetShellCrossSection(), G4PenelopePhotoElectricModel::GetShellCrossSection(), G4PenelopeCrossSection::GetSoftStoppingPower(), G4PenelopeCrossSection::GetTotalCrossSection(), G4ElementData::GetValueForElement(), G4NeutronElectronElXsc::Initialise(), G4eeToHadronsModel::Initialise(), G4PAIPhotData::Initialise(), G4EmCorrections::KShellCorrection(), G4EmCorrections::LShellCorrection(), G4Cerenkov::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4PenelopeBremsstrahlungAngular::PrepareTables(), G4DNABornExcitationModel2::RandomSelect(), G4PAIModelData::SampleAlongStepTransfer(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4PAIModelData::SamplePostStepTransfer(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4VEnergyLossProcess::ScaledKinEnergyForLoss(), G4PenelopePhotoElectricModel::SelectRandomShell(), G4VEnergyLossProcess::SetCSDARangeTable(), G4VEnergyLossProcess::SetDEDXTable(), and G4EmCorrections::ShellCorrection().
G4double G4PhysicsVector::Value (G4double theEnergy) const inline
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4PhysicsVector & pv) friend
Definition at line 478 of file G4PhysicsVector.cc.
View newest version in sPHENIX GitHub at line 478 of file G4PhysicsVector.cc
Member Data Documentation
G4double G4PhysicsVector::baseBin protected
Definition at line 250 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 250 of file G4PhysicsVector.hh
Referenced by G4PhysicsLinearVector::G4PhysicsLinearVector(), G4PhysicsLogVector::G4PhysicsLogVector(), G4PhysicsVector(), operator=(), G4PhysicsLinearVector::Retrieve(), G4PhysicsLogVector::Retrieve(), G4PhysicsLinearVector::ScaleVector(), and G4PhysicsLogVector::ScaleVector().
G4PVDataVector G4PhysicsVector::binVector protected
Definition at line 229 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 229 of file G4PhysicsVector.hh
Referenced by ComputeSecDerivatives(), ComputeSecondDerivatives(), CopyData(), DumpValues(), FillSecondDerivatives(), FindLinearEnergy(), G4PhysicsFreeVector::G4PhysicsFreeVector(), G4PhysicsLinearVector::G4PhysicsLinearVector(), G4PhysicsLogVector::G4PhysicsLogVector(), G4PhysicsOrderedFreeVector::G4PhysicsOrderedFreeVector(), GetLowEdgeEnergy(), G4PhysicsOrderedFreeVector::GetMaxLowEdgeEnergy(), G4PhysicsOrderedFreeVector::GetMinLowEdgeEnergy(), G4PhysicsOrderedFreeVector::InsertValues(), G4PhysicsOrderedFreeVector::LinearInterpolationOfEnergy(), operator<<(), G4PhysicsFreeVector::PutValue(), G4PhysicsLinearVector::Retrieve(), G4PhysicsLogVector::Retrieve(), Retrieve(), G4PhysicsLinearVector::ScaleVector(), G4PhysicsLogVector::ScaleVector(), ScaleVector(), SplinePossible(), and Store().
G4PVDataVector G4PhysicsVector::dataVector protected
Definition at line 228 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 228 of file G4PhysicsVector.hh
Referenced by ComputeSecDerivatives(), ComputeSecondDerivatives(), CopyData(), DumpValues(), FillSecondDerivatives(), FindLinearEnergy(), G4PhysicsOrderedFreeVector::FindValueBinLocation(), G4PhysicsFreeVector::G4PhysicsFreeVector(), G4PhysicsLinearVector::G4PhysicsLinearVector(), G4PhysicsLogVector::G4PhysicsLogVector(), G4PhysicsOrderedFreeVector::G4PhysicsOrderedFreeVector(), G4PhysicsOrderedFreeVector::GetMaxValue(), G4PhysicsOrderedFreeVector::GetMinValue(), G4PhysicsOrderedFreeVector::InsertValues(), G4PhysicsOrderedFreeVector::LinearInterpolationOfEnergy(), operator<<(), G4PhysicsFreeVector::PutValue(), Retrieve(), ScaleVector(), Store(), and Value().
G4double G4PhysicsVector::edgeMax protected
Definition at line 224 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 224 of file G4PhysicsVector.hh
Referenced by CopyData(), G4PhysicsFreeVector::G4PhysicsFreeVector(), G4PhysicsLinearVector::G4PhysicsLinearVector(), G4PhysicsLogVector::G4PhysicsLogVector(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsOrderedFreeVector::InsertValues(), operator<<(), G4PhysicsFreeVector::PutValue(), Retrieve(), ScaleVector(), Store(), and Value().
G4double G4PhysicsVector::edgeMin protected
Definition at line 223 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 223 of file G4PhysicsVector.hh
Referenced by CopyData(), G4PhysicsFreeVector::G4PhysicsFreeVector(), G4PhysicsLinearVector::G4PhysicsLinearVector(), G4PhysicsLogVector::G4PhysicsLogVector(), G4PhysicsOrderedFreeVector::GetEnergy(), G4PhysicsOrderedFreeVector::InsertValues(), operator<<(), G4PhysicsFreeVector::PutValue(), G4PhysicsLinearVector::Retrieve(), G4PhysicsLogVector::Retrieve(), Retrieve(), G4PhysicsLinearVector::ScaleVector(), G4PhysicsLogVector::ScaleVector(), ScaleVector(), Store(), and Value().
G4double G4PhysicsVector::invdBin protected
Definition at line 249 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 249 of file G4PhysicsVector.hh
Referenced by G4PhysicsLinearVector::G4PhysicsLinearVector(), G4PhysicsLogVector::G4PhysicsLogVector(), G4PhysicsVector(), operator=(), G4PhysicsLinearVector::Retrieve(), G4PhysicsLogVector::Retrieve(), G4PhysicsLinearVector::ScaleVector(), and G4PhysicsLogVector::ScaleVector().
size_t G4PhysicsVector::numberOfNodes protected
Definition at line 226 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 226 of file G4PhysicsVector.hh
Referenced by ComputeSecDerivatives(), ComputeSecondDerivatives(), CopyData(), DumpValues(), FillSecondDerivatives(), FindLinearEnergy(), G4PhysicsOrderedFreeVector::FindValueBinLocation(), G4PhysicsFreeVector::G4PhysicsFreeVector(), G4PhysicsLinearVector::G4PhysicsLinearVector(), G4PhysicsLogVector::G4PhysicsLogVector(), G4PhysicsOrderedFreeVector::InsertValues(), operator<<(), PrintPutValueError(), G4PhysicsFreeVector::PutValue(), Retrieve(), SplinePossible(), Store(), and Value().
G4PVDataVector G4PhysicsVector::secDerivative protected
Definition at line 230 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 230 of file G4PhysicsVector.hh
Referenced by ComputeSecDerivatives(), ComputeSecondDerivatives(), CopyData(), DeleteData(), FillSecondDerivatives(), Retrieve(), ScaleVector(), and SplinePossible().
G4PhysicsVectorType G4PhysicsVector::type protected
Definition at line 221 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 221 of file G4PhysicsVector.hh
Referenced by CopyData(), G4PhysicsFreeVector::G4PhysicsFreeVector(), G4PhysicsLinearVector::G4PhysicsLinearVector(), G4PhysicsLogVector::G4PhysicsLogVector(), G4PhysicsOrderedFreeVector::G4PhysicsOrderedFreeVector(), and PrintPutValueError().
G4bool G4PhysicsVector::useSpline private
Definition at line 245 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 245 of file G4PhysicsVector.hh
Referenced by ComputeSecDerivatives(), ComputeSecondDerivatives(), CopyData(), DeleteData(), FillSecondDerivatives(), and SplinePossible().
G4int G4PhysicsVector::verboseLevel protected
Definition at line 252 of file G4PhysicsVector.hh.
View newest version in sPHENIX GitHub at line 252 of file G4PhysicsVector.hh
Referenced by G4PhysicsVector(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4PhysicsVector.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4PhysicsVector.cc