ECCE @ EIC Software: CexmcHadronicProcess Class Reference
CexmcHadronicProcess Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcHadronicProcess.hh>
Public Member Functions
CexmcHadronicProcess (const G4String &name=CexmcStudiedProcessLastName)
~CexmcHadronicProcess ()
G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step)
G4bool IsApplicable (const G4ParticleDefinition &particle)
void RegisterProductionModel (CexmcProductionModel *model)
Public Member Functions inherited from G4HadronicProcess
G4HadronicProcess (const G4String &processName="Hadronic", G4ProcessType procType=fHadronic)
G4HadronicProcess (const G4String &processName, G4HadronicProcessType subType)
~G4HadronicProcess () override
void RegisterMe (G4HadronicInteraction *a)
G4double GetElementCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
G4double GetMicroscopicCrossSection (const G4DynamicParticle *part, const G4Element *elm, const G4Material *mat=nullptr)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
void PreparePhysicsTable (const G4ParticleDefinition &) override
void BuildPhysicsTable (const G4ParticleDefinition &) override
void DumpPhysicsTable (const G4ParticleDefinition &p)
void AddDataSet (G4VCrossSectionDataSet *aDataSet)
std::vector
< G4HadronicInteraction * > & GetHadronicInteractionList ()
G4HadronicInteraction * GetHadronicModel (const G4String &)
G4double GetMeanFreePath (const G4Track &aTrack, G4double, G4ForceCondition *) override
const G4Nucleus * GetTargetNucleus () const
const G4Isotope * GetTargetIsotope ()
void ProcessDescription (std::ostream &outFile) const override
void BiasCrossSectionByFactor (G4double aScale)
void MultiplyCrossSectionBy (G4double factor)
G4double CrossSectionFactor () const
void SetIntegral (G4bool val)
void SetEpReportLevel (G4int level)
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
std::pair< G4double, G4double > GetEnergyMomentumCheckLevels () const
G4CrossSectionDataStore * GetCrossSectionDataStore ()
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
void CalculateTargetNucleus (const G4Material *material)
void FillTotalResult (G4HadFinalState *hadFinalState, const G4Track &track)
Private Attributes
CexmcProductionModel * productionModel
G4HadronicInteraction * interaction
G4ParticleChange * theTotalResult
G4Nucleus targetNucleus
G4bool isInitialized
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4HadronicProcess
G4HadronicInteraction * ChooseHadronicInteraction (const G4HadProjectile &aHadProjectile, G4Nucleus &aTargetNucleus, const G4Material *aMaterial, const G4Element *anElement)
G4Nucleus * GetTargetNucleusPointer ()
void DumpState (const G4Track &, const G4String &, G4ExceptionDescription &)
G4HadronicInteraction * GetHadronicInteraction () const
G4double GetLastCrossSection ()
void FillResult (G4HadFinalState *aR, const G4Track &aT)
G4HadFinalState * CheckResult (const G4HadProjectile &thePro, const G4Nucleus &targetNucleus, G4HadFinalState *result)
void CheckEnergyMomentumConservation (const G4Track &, const G4Nucleus &)
Protected Attributes inherited from G4HadronicProcess
G4HadProjectile thePro
G4ParticleChange * theTotalResult
G4double fWeight
G4int epReportLevel
Detailed Description
Definition at line 60 of file CexmcHadronicProcess.hh.
View newest version in sPHENIX GitHub at line 60 of file CexmcHadronicProcess.hh
Constructor & Destructor Documentation
CexmcHadronicProcess::CexmcHadronicProcess (const G4String & name = CexmcStudiedProcessLastName) explicit
Definition at line 58 of file CexmcHadronicProcess.cc.
View newest version in sPHENIX GitHub at line 58 of file CexmcHadronicProcess.cc
References theTotalResult.
CexmcHadronicProcess::~CexmcHadronicProcess ()
Definition at line 66 of file CexmcHadronicProcess.cc.
View newest version in sPHENIX GitHub at line 66 of file CexmcHadronicProcess.cc
References theTotalResult.
Member Function Documentation
void CexmcHadronicProcess::CalculateTargetNucleus (const G4Material * material) private
Definition at line 86 of file CexmcHadronicProcess.cc.
View newest version in sPHENIX GitHub at line 86 of file CexmcHadronicProcess.cc
References CEXMC_LINE_START, G4cout, G4endl, G4Material::GetElement(), G4StableIsotopes::GetFirstIsotope(), G4StableIsotopes::GetIsotopeNucleonCount(), G4Material::GetNumberOfElements(), G4Nucleus::SetParameters(), targetNucleus, and Z.
Referenced by PostStepDoIt().
void CexmcHadronicProcess::FillTotalResult (G4HadFinalState * hadFinalState, const G4Track & track) private
Definition at line 109 of file CexmcHadronicProcess.cc.
View newest version in sPHENIX GitHub at line 109 of file CexmcHadronicProcess.cc
References G4ParticleChange::AddSecondary(), G4HadFinalState::Clear(), G4VParticleChange::Clear(), fAlive, fStopAndKill, G4HadFinalState::GetEnergyChange(), G4Track::GetGlobalTime(), G4HadFinalState::GetLocalEnergyDeposit(), G4HadFinalState::GetNumberOfSecondaries(), G4HadSecondary::GetParticle(), G4Track::GetPosition(), G4HadFinalState::GetSecondary(), G4HadFinalState::GetStatusChange(), G4HadSecondary::GetTime(), G4Track::GetTouchableHandle(), G4HadSecondary::GetWeight(), G4Track::GetWeight(), G4ParticleChange::Initialize(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::SetNumberOfSecondaries(), G4VParticleChange::SetSecondaryWeightByProcess(), G4Track::SetTouchableHandle(), G4Track::SetWeight(), stopAndKill, theTotalResult, and Acts::VectorHelpers::time().
Referenced by PostStepDoIt().
G4bool CexmcHadronicProcess::IsApplicable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 195 of file CexmcHadronicProcess.cc.
View newest version in sPHENIX GitHub at line 195 of file CexmcHadronicProcess.cc
References CexmcProductionModel::GetIncidentParticle(), and productionModel.
G4VParticleChange * CexmcHadronicProcess::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 146 of file CexmcHadronicProcess.cc.
View newest version in sPHENIX GitHub at line 146 of file CexmcHadronicProcess.cc
References G4HadronicInteraction::ApplyYourself(), CalculateTargetNucleus(), CexmcIncidentParticleTrackType, G4VParticleChange::Clear(), fAlive, FillTotalResult(), fStopAndKill, fSuspend, G4Track::GetMaterial(), G4VParticleChange::GetTrackStatus(), G4Track::GetTrackStatus(), CexmcTrackInfo::GetTypeInfo(), G4Track::GetUserInformation(), G4ParticleChange::Initialize(), interaction, isInitialized, CexmcIncidentParticleTrackInfo::SetNeedsTrackLengthResampling(), targetNucleus, and theTotalResult.
void CexmcHadronicProcess::RegisterProductionModel (CexmcProductionModel * model)
Definition at line 72 of file CexmcHadronicProcess.cc.
View newest version in sPHENIX GitHub at line 72 of file CexmcHadronicProcess.cc
References CexmcIncompatibleProductionModel, interaction, productionModel, and G4HadronicProcess::RegisterMe().
Referenced by CexmcHadronicPhysics< ProductionModel >::ApplyInteractionModel().
Member Data Documentation
G4HadronicInteraction* CexmcHadronicProcess::interaction private
Definition at line 86 of file CexmcHadronicProcess.hh.
View newest version in sPHENIX GitHub at line 86 of file CexmcHadronicProcess.hh
Referenced by PostStepDoIt(), and RegisterProductionModel().
G4bool CexmcHadronicProcess::isInitialized private
Definition at line 93 of file CexmcHadronicProcess.hh.
View newest version in sPHENIX GitHub at line 93 of file CexmcHadronicProcess.hh
Referenced by PostStepDoIt().
CexmcProductionModel* CexmcHadronicProcess::productionModel private
Definition at line 84 of file CexmcHadronicProcess.hh.
View newest version in sPHENIX GitHub at line 84 of file CexmcHadronicProcess.hh
Referenced by IsApplicable(), and RegisterProductionModel().
G4Nucleus CexmcHadronicProcess::targetNucleus private
Definition at line 91 of file CexmcHadronicProcess.hh.
View newest version in sPHENIX GitHub at line 91 of file CexmcHadronicProcess.hh
Referenced by CalculateTargetNucleus(), and PostStepDoIt().
G4ParticleChange* CexmcHadronicProcess::theTotalResult private
Definition at line 89 of file CexmcHadronicProcess.hh.
View newest version in sPHENIX GitHub at line 89 of file CexmcHadronicProcess.hh
Referenced by CexmcHadronicProcess(), FillTotalResult(), PostStepDoIt(), and ~CexmcHadronicProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcHadronicProcess.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcHadronicProcess.cc