ECCE @ EIC Software: PDBlib Class Reference
PDBlib Class Reference
PDBlib Class.
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/PDBlib.hh>
Public Member Functions
PDBlib ()
First constructor.
~PDBlib ()
Destructor.
Molecule * Load (const std::string &filename, unsigned short int &isDNA, unsigned short int verbose)
Load PDB file into memory.
Barycenter * ComputeNucleotideBarycenters (Molecule *moleculeListTemp)
Compute nucleotide barycenter from memory.
void ComputeBoundingVolumeParams (Molecule *moleculeListTemp, double &dX, double &dY, double &dZ, double &tX, double &tY, double &tZ)
Compute the corresponding bounding volume parameters.
void ComputeNbNucleotidsPerStrand (Molecule *moleculeListTemp)
Compute number of nucleotide per strand.
unsigned short int ComputeMatchEdepDNA (Barycenter *, Molecule *, double x, double y, double z, int &numStrand, int &numNucleotid, int &codeResidue)
Compute if energy is deposited in per atom.
Private Member Functions
double DistanceTwo3Dpoints (double xA, double xB, double yA, double yB, double zA, double zB)
return distance between two 3D points
Private Attributes
int fNbNucleotidsPerStrand
Number of nucleotid per strand.
Detailed Description
PDBlib Class.
This Class define Molecule model ...
Definition at line 56 of file PDBlib.hh.
View newest version in sPHENIX GitHub at line 56 of file PDBlib.hh
Constructor & Destructor Documentation
PDBlib::PDBlib ()
First constructor.
Definition at line 65 of file PDBlib.cc.
View newest version in sPHENIX GitHub at line 65 of file PDBlib.cc
PDBlib::~PDBlib () inline
Destructor.
Definition at line 62 of file PDBlib.hh.
View newest version in sPHENIX GitHub at line 62 of file PDBlib.hh
Member Function Documentation
void PDBlib::ComputeBoundingVolumeParams (Molecule * moleculeListTemp, double & dX, double & dY, double & dZ, double & tX, double & tY, double & tZ)
Compute the corresponding bounding volume parameters.
the corresponding bounding volume parameters
the corresponding bounding volume parameters to build a box from atoms coordinates
Definition at line 661 of file PDBlib.cc.
View newest version in sPHENIX GitHub at line 661 of file PDBlib.cc
References DBL_MAX, Molecule::fMaxGlobX, Molecule::fMaxGlobY, Molecule::fMaxGlobZ, Molecule::fMinGlobX, Molecule::fMinGlobY, Molecule::fMinGlobZ, and Molecule::GetNext().
Referenced by DetectorConstruction::DrawBoundingVolume().
unsigned short int PDBlib::ComputeMatchEdepDNA (Barycenter * BarycenterList, Molecule * moleculeListTemp, double x, double y, double z, int & numStrand, int & numNucleotid, int & codeResidue)
Compute if energy is deposited in per atom.
Compute barycenters.
Compute barycenters and its coordinate for nucleotides
Definition at line 759 of file PDBlib.cc.
View newest version in sPHENIX GitHub at line 759 of file PDBlib.cc
References DistanceTwo3Dpoints(), Barycenter::fCenterX, Barycenter::fCenterY, Barycenter::fCenterZ, Residue::fNbAtom, fNbNucleotidsPerStrand, Residue::fResName, Residue::fResSeq, Residue::GetFirst(), Molecule::GetFirst(), Barycenter::GetNext(), Molecule::GetNext(), Residue::GetNext(), Atom::GetNext(), Atom::GetX(), Atom::GetY(), Atom::GetZ(), INT_MAX, k, y, and z.
void PDBlib::ComputeNbNucleotidsPerStrand (Molecule * moleculeListTemp)
Compute number of nucleotide per strand.
Compute number of nucleotide per strand for DNA
Definition at line 725 of file PDBlib.cc.
View newest version in sPHENIX GitHub at line 725 of file PDBlib.cc
References fNbNucleotidsPerStrand, Molecule::GetFirst(), Molecule::GetNext(), Residue::GetNext(), and k.
Referenced by DetectorConstruction::DefineVolumes().
Barycenter * PDBlib::ComputeNucleotideBarycenters (Molecule * moleculeListTemp)
Compute nucleotide barycenter from memory.
Compute barycenters.
Compute barycenters and its coordinate for nucleotides
Parameters
moleculeListTemp * moleculeList
Returns
Barycenter *
molecs->push_back(*moleculeListTemp);
Definition at line 451 of file PDBlib.cc.
View newest version in sPHENIX GitHub at line 451 of file PDBlib.cc
References DistanceTwo3Dpoints(), Barycenter::fCenterX, Barycenter::fCenterY, Barycenter::fCenterZ, Atom::fElement, Residue::fNbAtom, Residue::fResSeq, Atom::fX, Atom::fY, Atom::fZ, Residue::GetFirst(), Molecule::GetFirst(), Molecule::GetNext(), Residue::GetNext(), Atom::GetNext(), k, max, Barycenter::SetDistance(), Barycenter::SetNext(), and Barycenter::SetRadius().
Referenced by DetectorConstruction::DefineVolumes().
double PDBlib::DistanceTwo3Dpoints (double xA, double xB, double yA, double yB, double zA, double zB) private
return distance between two 3D points
Definition at line 883 of file PDBlib.cc.
View newest version in sPHENIX GitHub at line 883 of file PDBlib.cc
Referenced by ComputeMatchEdepDNA(), and ComputeNucleotideBarycenters().
Molecule * PDBlib::Load (const std::string & filename, unsigned short int & isDNA, unsigned short int verbose = 0)
Load PDB file into memory.
Load a PDB file into memory.
molecule (polymer,?), read line, key words
Parameters
filename G4String for filename
isDNA
verbose
Returns
List of molecules
Definition at line 82 of file PDBlib.cc.
View newest version in sPHENIX GitHub at line 82 of file PDBlib.cc
References compare(), DBL_MAX, g4zmq::exit(), FatalException, Molecule::fCenterX, Molecule::fCenterY, Molecule::fCenterZ, INPUTHEPMC::filename, Molecule::fMaxGlobX, Molecule::fMaxGlobY, Molecule::fMaxGlobZ, Molecule::fMinGlobX, Molecule::fMinGlobY, Molecule::fMinGlobZ, Residue::fNbAtom, Molecule::fNbResidue, Atom::fNumInRes, G4cerr, G4cout, G4endl, G4Exception(), int(), INT_MAX, maxY, maxZ, minY, Residue::SetFirst(), Molecule::SetFirst(), Molecule::SetNext(), Residue::SetNext(), Atom::SetNext(), x, y, and z.
Referenced by DetectorConstruction::DefineVolumes().
Member Data Documentation
int PDBlib::fNbNucleotidsPerStrand private
Number of nucleotid per strand.
Definition at line 95 of file PDBlib.hh.
View newest version in sPHENIX GitHub at line 95 of file PDBlib.hh
Referenced by ComputeMatchEdepDNA(), and ComputeNbNucleotidsPerStrand().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/PDBlib.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/src/PDBlib.cc