ECCE @ EIC Software: WLSTrackingAction Class Reference
WLSTrackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSTrackingAction.hh>
Public Member Functions
WLSTrackingAction ()
virtual ~WLSTrackingAction ()
virtual void PreUserTrackingAction (const G4Track *)
Public Member Functions inherited from G4UserTrackingAction
G4UserTrackingAction ()
virtual ~G4UserTrackingAction ()
virtual void SetTrackingManagerPointer (G4TrackingManager *pValue)
virtual void PostUserTrackingAction (const G4Track *)
Additional Inherited Members
Protected Attributes inherited from G4UserTrackingAction
G4TrackingManager * fpTrackingManager
Detailed Description
Definition at line 39 of file WLSTrackingAction.hh.
View newest version in sPHENIX GitHub at line 39 of file WLSTrackingAction.hh
Constructor & Destructor Documentation
WLSTrackingAction::WLSTrackingAction () inline
Definition at line 43 of file WLSTrackingAction.hh.
View newest version in sPHENIX GitHub at line 43 of file WLSTrackingAction.hh
virtual WLSTrackingAction::~WLSTrackingAction () inline virtual
Definition at line 44 of file WLSTrackingAction.hh.
View newest version in sPHENIX GitHub at line 44 of file WLSTrackingAction.hh
Member Function Documentation
void WLSTrackingAction::PreUserTrackingAction (const G4Track * aTrack) virtual
Reimplemented from G4UserTrackingAction.
Definition at line 46 of file WLSTrackingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file WLSTrackingAction.cc
References WLSUserTrackInformation::AddStatusFlag(), G4UserTrackingAction::fpTrackingManager, G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4Track::GetVolume(), InsideOfFiber, left, right, G4TrackingManager::SetTrajectory(), G4TrackingManager::SetUserTrackInformation(), and CLHEP::Hep3Vector::z().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/include/WLSTrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/wls/src/WLSTrackingAction.cc