ECCE @ EIC Software: G4VXTRenergyLoss Class Reference
G4VXTRenergyLoss Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4VXTRenergyLoss.hh>
Public Member Functions
G4VXTRenergyLoss (G4LogicalVolume *anEnvelope, G4Material *, G4Material *, G4double, G4double, G4int, const G4String &processName="XTRenergyLoss", G4ProcessType type=fElectromagnetic)
virtual ~G4VXTRenergyLoss ()
virtual G4double GetStackFactor (G4double energy, G4double gamma, G4double varAngle)
virtual G4bool IsApplicable (const G4ParticleDefinition &) override
virtual G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
void BuildEnergyTable ()
void BuildAngleForEnergyBank ()
void BuildTable ()
void BuildAngleTable ()
void BuildGlobalAngleTable ()
G4complex OneInterfaceXTRdEdx (G4double energy, G4double gamma, G4double varAngle)
G4double SpectralAngleXTRdEdx (G4double varAngle)
virtual G4double SpectralXTRdEdx (G4double energy)
G4double AngleSpectralXTRdEdx (G4double energy)
G4double AngleXTRdEdx (G4double varAngle)
G4double OneBoundaryXTRNdensity (G4double energy, G4double gamma, G4double varAngle) const
G4double XTRNSpectralAngleDensity (G4double varAngle)
G4double XTRNSpectralDensity (G4double energy)
G4double XTRNAngleSpectralDensity (G4double energy)
G4double XTRNAngleDensity (G4double varAngle)
void GetNumberOfPhotons ()
G4double GetPlateFormationZone (G4double, G4double, G4double)
G4complex GetPlateComplexFZ (G4double, G4double, G4double)
void ComputePlatePhotoAbsCof ()
G4double GetPlateLinearPhotoAbs (G4double)
void GetPlateZmuProduct ()
G4double GetPlateZmuProduct (G4double, G4double, G4double)
G4double GetGasFormationZone (G4double, G4double, G4double)
G4complex GetGasComplexFZ (G4double, G4double, G4double)
void ComputeGasPhotoAbsCof ()
G4double GetGasLinearPhotoAbs (G4double)
void GetGasZmuProduct ()
G4double GetGasZmuProduct (G4double, G4double, G4double)
G4double GetPlateCompton (G4double)
G4double GetGasCompton (G4double)
G4double GetComptonPerAtom (G4double, G4double)
G4double GetXTRrandomEnergy (G4double scaledTkin, G4int iTkin)
G4double GetXTRenergy (G4int iPlace, G4double position, G4int iTransfer)
G4double GetRandomAngle (G4double energyXTR, G4int iTkin)
G4double GetAngleXTR (G4int iTR, G4double position, G4int iAngle)
G4double GetGamma ()
G4double GetEnergy ()
G4double GetVarAngle ()
void SetGamma (G4double gamma)
void SetEnergy (G4double energy)
void SetVarAngle (G4double varAngle)
void SetAngleRadDistr (G4bool pAngleRadDistr)
void SetCompton (G4bool pC)
G4PhysicsLogVector * GetProtonVector ()
G4int GetTotBin ()
G4PhysicsFreeVector * GetAngleVector (G4double energy, G4int n)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Attributes
G4ParticleDefinition * fPtrGamma
G4double * fGammaCutInKineticEnergy
G4double fGammaTkinCut
G4LogicalVolume * fEnvelope
G4PhysicsTable * fAngleDistrTable
G4PhysicsTable * fEnergyDistrTable
G4PhysicsLogVector * fProtonEnergyVector
G4PhysicsLogVector * fXTREnergyVector
G4double fTheMinEnergyTR
G4double fTheMaxEnergyTR
G4double fMinEnergyTR
G4double fMaxEnergyTR
G4double fTheMaxAngle
G4double fTheMinAngle
G4double fMaxThetaTR
G4int fBinTR
G4double fMinProtonTkin
G4double fMaxProtonTkin
G4int fTotBin
G4double fGamma
G4double fEnergy
G4double fVarAngle
G4double fLambda
G4double fPlasmaCof
G4double fCofTR
G4bool fExitFlux
G4bool fAngleRadDistr
G4bool fCompton
G4double fSigma1
G4double fSigma2
G4int fMatIndex1
G4int fMatIndex2
G4int fPlateNumber
G4double fTotalDist
G4double fPlateThick
G4double fGasThick
G4double fAlphaPlate
G4double fAlphaGas
G4SandiaTable * fPlatePhotoAbsCof
G4SandiaTable * fGasPhotoAbsCof
G4ParticleChange fParticleChange
G4PhysicsTable * fAngleForEnergyTable
std::vector< G4PhysicsTable * > fAngleBank
Private Member Functions
G4VXTRenergyLoss (G4VXTRenergyLoss &)=delete
G4VXTRenergyLoss & operator= (const G4VXTRenergyLoss &right)=delete
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Detailed Description
Definition at line 73 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VXTRenergyLoss.hh
Constructor & Destructor Documentation
G4VXTRenergyLoss::G4VXTRenergyLoss (G4LogicalVolume * anEnvelope, G4Material * foilMat, G4Material * gasMat, G4double a, G4double b, G4int n, const G4String & processName = "XTRenergyLoss", G4ProcessType type = fElectromagnetic) explicit
Definition at line 63 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 63 of file G4VXTRenergyLoss.cc
References a, b, cm, ComputeGasPhotoAbsCof(), ComputePlatePhotoAbsCof(), DBL_MAX, source.hepunit::electron_mass_c2, eV, fAlphaGas, fAlphaPlate, fAngleRadDistr, FatalException, fBinTR, fCofTR, fCompton, fEnergy, fEnvelope, fExitFlux, fGamma, fGasThick, source.hepunit::fine_structure_const, fLambda, fMatIndex1, fMatIndex2, fMaxEnergyTR, fMaxProtonTkin, fMaxThetaTR, fMinEnergyTR, fMinProtonTkin, fParticleChange, fPlasmaCof, fPlateNumber, fPlateThick, fProtonEnergyVector, fPtrGamma, fSigma1, fSigma2, fTheMaxAngle, fTheMaxEnergyTR, fTheMinAngle, fTheMinEnergyTR, fTotalDist, fTotBin, fTransitionRadiation, fVarAngle, fXTREnergyVector, G4cout, G4endl, G4Exception(), G4Material::GetElectronDensity(), G4Material::GetIndex(), G4Material::GetName(), GeV, source.hepunit::hbarc, keV, n, pi, G4VProcess::pParticleChange, G4VProcess::SetProcessSubType(), TeV, and G4VProcess::verboseLevel.
G4VXTRenergyLoss::~G4VXTRenergyLoss () virtual
Definition at line 170 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 170 of file G4VXTRenergyLoss.cc
References G4PhysicsTable::clearAndDestroy(), fAngleDistrTable, fAngleForEnergyTable, fAngleRadDistr, fEnergyDistrTable, fEnvelope, fProtonEnergyVector, and fXTREnergyVector.
G4VXTRenergyLoss::G4VXTRenergyLoss (G4VXTRenergyLoss &) private delete
Member Function Documentation
G4double G4VXTRenergyLoss::AngleSpectralXTRdEdx (G4double energy)
Definition at line 949 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 949 of file G4VXTRenergyLoss.cc
References fGamma, fVarAngle, and GetStackFactor().
G4double G4VXTRenergyLoss::AngleXTRdEdx (G4double varAngle)
Definition at line 960 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 960 of file G4VXTRenergyLoss.cc
References kdfinder::abs(), fGamma, fGasThick, fPlateNumber, fPlateThick, fSigma1, fSigma2, fTheMaxEnergyTR, fTheMinEnergyTR, source.hepunit::hbarc, k, BoundingBox::kMax, BoundingBox::kMin, pi, sum, tmp, tmp1, tmp2, and twopi.
Referenced by BuildGlobalAngleTable().
void G4VXTRenergyLoss::BuildAngleForEnergyBank ()
Definition at line 393 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 393 of file G4VXTRenergyLoss.cc
References BuildAngleTable(), fAngleBank, fAngleForEnergyTable, fBinTR, fEnergy, fGamma, fGammaTkinCut, fMaxEnergyTR, fMaxThetaTR, fMinEnergyTR, fProtonEnergyVector, fTheMaxAngle, fTheMaxEnergyTR, fTheMinAngle, fTheMinEnergyTR, fTotBin, G4cout, G4endl, G4PhysicsVector::GetLowEdgeEnergy(), G4VProcess::GetProcessName(), G4Timer::GetUserElapsed(), G4PhysicsTable::insertAt(), G4Integrator< T, F >::Legendre10(), source.hepunit::proton_mass_c2, G4PhysicsVector::PutValue(), SpectralAngleXTRdEdx(), G4Timer::Start(), G4Timer::Stop(), and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable().
void G4VXTRenergyLoss::BuildAngleTable ()
Definition at line 484 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 484 of file G4VXTRenergyLoss.cc
References energy, fAngleBank, fAngleForEnergyTable, fBinTR, fGamma, fGammaTkinCut, fMaxEnergyTR, fMaxThetaTR, fMinEnergyTR, fProtonEnergyVector, fTheMaxAngle, fTheMaxEnergyTR, fTheMinAngle, fTheMinEnergyTR, fTotBin, fXTREnergyVector, G4cout, G4endl, GetAngleVector(), G4PhysicsVector::GetLowEdgeEnergy(), G4Timer::GetUserElapsed(), G4PhysicsTable::insertAt(), source.hepunit::proton_mass_c2, G4Timer::Start(), G4Timer::Stop(), and G4VProcess::verboseLevel.
Referenced by BuildAngleForEnergyBank().
void G4VXTRenergyLoss::BuildEnergyTable ()
Definition at line 301 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 301 of file G4VXTRenergyLoss.cc
References fAngleDistrTable, fAngleRadDistr, fBinTR, fCofTR, fEnergyDistrTable, fGamma, fGammaTkinCut, fMaxEnergyTR, fMaxThetaTR, fMinEnergyTR, fProtonEnergyVector, fTheMaxAngle, fTheMaxEnergyTR, fTheMinAngle, fTheMinEnergyTR, fTotalDist, fTotBin, G4cout, G4endl, G4PhysicsVector::GetLowEdgeEnergy(), G4Timer::GetUserElapsed(), G4PhysicsTable::insertAt(), G4Integrator< T, F >::Legendre10(), source.hepunit::proton_mass_c2, G4PhysicsVector::PutValue(), SpectralXTRdEdx(), G4Timer::Start(), G4Timer::Stop(), and G4VProcess::verboseLevel.
Referenced by BuildPhysicsTable().
void G4VXTRenergyLoss::BuildGlobalAngleTable ()
Definition at line 639 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 639 of file G4VXTRenergyLoss.cc
References AngleXTRdEdx(), fAngleDistrTable, fBinTR, fCofTR, fGamma, fGammaTkinCut, fMaxEnergyTR, fMaxThetaTR, fMinEnergyTR, fProtonEnergyVector, fTheMaxAngle, fTheMaxEnergyTR, fTheMinAngle, fTheMinEnergyTR, fTotBin, G4cout, G4endl, G4PhysicsVector::GetLowEdgeEnergy(), G4Timer::GetUserElapsed(), G4PhysicsTable::insertAt(), G4Integrator< T, F >::Legendre96(), source.hepunit::proton_mass_c2, G4PhysicsVector::PutValue(), G4Timer::Start(), G4Timer::Stop(), and G4VProcess::verboseLevel.
void G4VXTRenergyLoss::BuildPhysicsTable (const G4ParticleDefinition & pd) override virtual
Reimplemented from G4VProcess.
Definition at line 276 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 276 of file G4VXTRenergyLoss.cc
References BuildAngleForEnergyBank(), BuildEnergyTable(), fAngleRadDistr, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetPDGCharge(), JustWarning, and G4VProcess::verboseLevel.
void G4VXTRenergyLoss::BuildTable () inline
Definition at line 101 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 101 of file G4VXTRenergyLoss.hh
void G4VXTRenergyLoss::ComputeGasPhotoAbsCof ()
Definition at line 1162 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1162 of file G4VXTRenergyLoss.cc
References fGasPhotoAbsCof, fMatIndex2, G4Material::GetMaterialTable(), G4Material::GetSandiaTable(), and mat.
Referenced by G4VXTRenergyLoss().
void G4VXTRenergyLoss::ComputePlatePhotoAbsCof ()
Definition at line 1087 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1087 of file G4VXTRenergyLoss.cc
References fMatIndex1, fPlatePhotoAbsCof, G4Material::GetMaterialTable(), G4Material::GetSandiaTable(), and mat.
Referenced by G4VXTRenergyLoss().
G4PhysicsFreeVector * G4VXTRenergyLoss::GetAngleVector (G4double energy, G4int n)
Definition at line 557 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 557 of file G4VXTRenergyLoss.cc
References kdfinder::abs(), fGamma, fGasThick, fMaxThetaTR, fPlateThick, fSigma1, fSigma2, G4cout, G4endl, source.hepunit::hbarc, k, BoundingBox::kMin, pi, G4PhysicsFreeVector::PutValue(), theta(), tmp, and G4VProcess::verboseLevel.
Referenced by BuildAngleTable().
G4double G4VXTRenergyLoss::GetAngleXTR (G4int iTR, G4double position, G4int iAngle)
Definition at line 1598 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1598 of file G4VXTRenergyLoss.cc
References G4UniformRand, x1, x2, y1, and y2.
Referenced by GetRandomAngle().
G4double G4VXTRenergyLoss::GetComptonPerAtom (G4double GammaEnergy, G4double Z)
Definition at line 1318 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1318 of file G4VXTRenergyLoss.cc
References a, b, barn, c, c1, c2, d1, d2, e1, e2, e3, e4, source.hepunit::electron_mass_c2, f1, f2, f3, f4, GeV, keV, max, T0, X, y, and Z.
Referenced by GetGasCompton(), and GetPlateCompton().
G4double G4VXTRenergyLoss::GetEnergy () inline
Definition at line 164 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 164 of file G4VXTRenergyLoss.hh
References fEnergy.
G4double G4VXTRenergyLoss::GetGamma () inline
Definition at line 163 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 163 of file G4VXTRenergyLoss.hh
References fGamma.
G4complex G4VXTRenergyLoss::GetGasComplexFZ (G4double omega, G4double gamma, G4double varAngle)
Definition at line 1138 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1138 of file G4VXTRenergyLoss.cc
References Acts::Test::delta, GetGasFormationZone(), GetGasLinearPhotoAbs(), and BTOF::length.
Referenced by G4StrawTubeXTRadiator::GetStackFactor(), and OneInterfaceXTRdEdx().
G4double G4VXTRenergyLoss::GetGasCompton (G4double omega)
Definition at line 1294 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1294 of file G4VXTRenergyLoss.cc
References fMatIndex2, GetComptonPerAtom(), and G4Material::GetMaterialTable().
Referenced by G4XTRTransparentRegRadModel::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
G4double G4VXTRenergyLoss::GetGasFormationZone (G4double omega, G4double gamma, G4double varAngle)
Definition at line 1123 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1123 of file G4VXTRenergyLoss.cc
References fSigma2, source.hepunit::hbarc, and G4InuclParticleNames::lambda.
Referenced by GetGasComplexFZ(), GetGasZmuProduct(), G4XTRRegularRadModel::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), and G4GammaXTRadiator::GetStackFactor().
G4double G4VXTRenergyLoss::GetGasLinearPhotoAbs (G4double omega)
Definition at line 1175 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1175 of file G4VXTRenergyLoss.cc
References Acts::VectorHelpers::cross(), fGasPhotoAbsCof, and G4SandiaTable::GetSandiaCofForMaterial().
Referenced by GetGasComplexFZ(), GetGasZmuProduct(), G4XTRRegularRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
void G4VXTRenergyLoss::GetGasZmuProduct ()
Definition at line 1245 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1245 of file G4VXTRenergyLoss.cc
References G4cout, G4endl, keV, and G4VProcess::verboseLevel.
G4double G4VXTRenergyLoss::GetGasZmuProduct (G4double omega, G4double gamma, G4double varAngle)
Definition at line 1234 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1234 of file G4VXTRenergyLoss.cc
References GetGasFormationZone(), and GetGasLinearPhotoAbs().
G4double G4VXTRenergyLoss::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) override virtual
Implements G4VDiscreteProcess.
Definition at line 203 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 203 of file G4VXTRenergyLoss.cc
References charge, DBL_MAX, DBL_MIN, fEnergyDistrTable, fEnvelope, fGamma, fLambda, fProtonEnergyVector, fTotBin, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4PhysicsVector::GetLowEdgeEnergy(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4Track::GetVolume(), G4InuclParticleNames::lambda, mass, mm, NotForced, source.hepunit::proton_mass_c2, and G4VProcess::verboseLevel.
void G4VXTRenergyLoss::GetNumberOfPhotons ()
Definition at line 1450 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1450 of file G4VXTRenergyLoss.cc
References fProtonEnergyVector, fTotBin, G4cout, G4endl, source.hepunit::proton_mass_c2, and G4VProcess::verboseLevel.
G4complex G4VXTRenergyLoss::GetPlateComplexFZ (G4double omega, G4double gamma, G4double varAngle)
Definition at line 1065 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1065 of file G4VXTRenergyLoss.cc
References Acts::Test::delta, GetPlateFormationZone(), GetPlateLinearPhotoAbs(), and BTOF::length.
Referenced by G4StrawTubeXTRadiator::GetStackFactor(), and OneInterfaceXTRdEdx().
G4double G4VXTRenergyLoss::GetPlateCompton (G4double omega)
Definition at line 1270 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1270 of file G4VXTRenergyLoss.cc
References fMatIndex1, GetComptonPerAtom(), and G4Material::GetMaterialTable().
Referenced by G4XTRTransparentRegRadModel::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
G4double G4VXTRenergyLoss::GetPlateFormationZone (G4double omega, G4double gamma, G4double varAngle)
Definition at line 1051 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1051 of file G4VXTRenergyLoss.cc
References fSigma1, source.hepunit::hbarc, and G4InuclParticleNames::lambda.
Referenced by GetPlateComplexFZ(), GetPlateZmuProduct(), G4XTRRegularRadModel::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), and G4GammaXTRadiator::GetStackFactor().
G4double G4VXTRenergyLoss::GetPlateLinearPhotoAbs (G4double omega)
Definition at line 1103 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1103 of file G4VXTRenergyLoss.cc
References Acts::VectorHelpers::cross(), fPlatePhotoAbsCof, and G4SandiaTable::GetSandiaCofForMaterial().
Referenced by GetPlateComplexFZ(), GetPlateZmuProduct(), G4XTRRegularRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
void G4VXTRenergyLoss::GetPlateZmuProduct ()
Definition at line 1207 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1207 of file G4VXTRenergyLoss.cc
References G4cout, G4endl, keV, and G4VProcess::verboseLevel.
G4double G4VXTRenergyLoss::GetPlateZmuProduct (G4double omega, G4double gamma, G4double varAngle)
Definition at line 1195 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1195 of file G4VXTRenergyLoss.cc
References GetPlateFormationZone(), and GetPlateLinearPhotoAbs().
G4PhysicsLogVector* G4VXTRenergyLoss::GetProtonVector () inline
Definition at line 173 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 173 of file G4VXTRenergyLoss.hh
References fProtonEnergyVector.
G4double G4VXTRenergyLoss::GetRandomAngle (G4double energyXTR, G4int iTkin)
Definition at line 1568 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1568 of file G4VXTRenergyLoss.cc
References angle, fAngleBank, fAngleForEnergyTable, fBinTR, fTotBin, G4UniformRand, GetAngleXTR(), and position.
Referenced by PostStepDoIt().
G4double G4VXTRenergyLoss::GetStackFactor (G4double energy, G4double gamma, G4double varAngle) virtual
Reimplemented in G4GammaXTRadiator, G4StrawTubeXTRadiator, G4XTRGammaRadModel, XTRTransparentRegRadModel, G4TransparentRegXTRadiator, G4RegularXTRadiator, G4XTRTransparentRegRadModel, and G4XTRRegularRadModel.
Definition at line 1389 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1389 of file G4VXTRenergyLoss.cc
References OneInterfaceXTRdEdx().
Referenced by AngleSpectralXTRdEdx(), SpectralAngleXTRdEdx(), XTRNAngleSpectralDensity(), and XTRNSpectralAngleDensity().
G4int G4VXTRenergyLoss::GetTotBin () inline
Definition at line 174 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 174 of file G4VXTRenergyLoss.hh
References fTotBin.
G4double G4VXTRenergyLoss::GetVarAngle () inline
Definition at line 165 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 165 of file G4VXTRenergyLoss.hh
References fVarAngle.
G4double G4VXTRenergyLoss::GetXTRenergy (G4int iPlace, G4double position, G4int iTransfer)
Definition at line 1532 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1532 of file G4VXTRenergyLoss.cc
References G4UniformRand, x1, x2, y1, and y2.
Referenced by GetXTRrandomEnergy().
G4double G4VXTRenergyLoss::GetXTRrandomEnergy (G4double scaledTkin, G4int iTkin)
Definition at line 1481 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1481 of file G4VXTRenergyLoss.cc
References fEnergyDistrTable, fProtonEnergyVector, fTotBin, G4UniformRand, G4PhysicsVector::GetLowEdgeEnergy(), GetXTRenergy(), and position.
Referenced by PostStepDoIt().
G4bool G4VXTRenergyLoss::IsApplicable (const G4ParticleDefinition & particle) override virtual
Reimplemented from G4VProcess.
Definition at line 194 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 194 of file G4VXTRenergyLoss.cc
References G4ParticleDefinition::GetPDGCharge().
G4double G4VXTRenergyLoss::OneBoundaryXTRNdensity (G4double energy, G4double gamma, G4double varAngle) const
Definition at line 1372 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1372 of file G4VXTRenergyLoss.cc
References fSigma1, and fSigma2.
Referenced by XTRNAngleSpectralDensity(), and XTRNSpectralAngleDensity().
G4complex G4VXTRenergyLoss::OneInterfaceXTRdEdx (G4double energy, G4double gamma, G4double varAngle)
Definition at line 872 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 872 of file G4VXTRenergyLoss.cc
References GetGasComplexFZ(), GetPlateComplexFZ(), source.hepunit::hbarc, Z1, and Z2.
Referenced by G4XTRRegularRadModel::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), and GetStackFactor().
G4VXTRenergyLoss& G4VXTRenergyLoss::operator= (const G4VXTRenergyLoss & right) private delete
G4VParticleChange * G4VXTRenergyLoss::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 730 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 730 of file G4VXTRenergyLoss.cc
References G4ParticleChange::AddSecondary(), source.hepunit::c_light, G4VSolid::DistanceToOut(), fAngleRadDistr, fEnvelope, fExitFlux, fParticleChange, fTotBin, G4cout, G4endl, G4UniformRand, G4Gamma::Gamma(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4StepPoint::GetGlobalTime(), G4DynamicParticle::GetKineticEnergy(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4Material::GetName(), G4ParticleDefinition::GetPDGMass(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), GetRandomAngle(), G4VTouchable::GetRotation(), G4LogicalVolume::GetSolid(), G4StepPoint::GetTouchable(), G4StepPoint::GetTouchableHandle(), G4Track::GetTrackID(), G4VTouchable::GetTranslation(), G4Track::GetVolume(), GetXTRrandomEnergy(), G4ParticleChange::Initialize(), G4AffineTransform::Invert(), keV, mass, mm, phi, pi, G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), source.hepunit::proton_mass_c2, CLHEP::Hep3Vector::rotateUz(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetParentID(), G4Track::SetTouchableHandle(), G4INCL::DeJongSpin::shoot(), theta(), Acts::Test::transform, G4AffineTransform::TransformAxis(), G4AffineTransform::TransformPoint(), twopi, CLHEP::Hep3Vector::unit(), and G4VProcess::verboseLevel.
void G4VXTRenergyLoss::SetAngleRadDistr (G4bool pAngleRadDistr) inline
Definition at line 170 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 170 of file G4VXTRenergyLoss.hh
References fAngleRadDistr.
void G4VXTRenergyLoss::SetCompton (G4bool pC) inline
Definition at line 171 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 171 of file G4VXTRenergyLoss.hh
References fCompton.
void G4VXTRenergyLoss::SetEnergy (G4double energy) inline
Definition at line 168 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 168 of file G4VXTRenergyLoss.hh
References energy, and fEnergy.
void G4VXTRenergyLoss::SetGamma (G4double gamma) inline
Definition at line 167 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 167 of file G4VXTRenergyLoss.hh
References fGamma.
void G4VXTRenergyLoss::SetVarAngle (G4double varAngle) inline
Definition at line 169 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 169 of file G4VXTRenergyLoss.hh
References fVarAngle.
G4double G4VXTRenergyLoss::SpectralAngleXTRdEdx (G4double varAngle)
Definition at line 891 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 891 of file G4VXTRenergyLoss.cc
References fEnergy, fGamma, and GetStackFactor().
Referenced by BuildAngleForEnergyBank(), and SpectralXTRdEdx().
G4double G4VXTRenergyLoss::SpectralXTRdEdx (G4double energy) virtual
Reimplemented in XTRTransparentRegRadModel, G4TransparentRegXTRadiator, G4RegularXTRadiator, G4XTRTransparentRegRadModel, and G4XTRRegularRadModel.
Definition at line 902 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 902 of file G4VXTRenergyLoss.cc
References energy, fEnergy, fMaxThetaTR, G4Integrator< T, F >::Legendre96(), and SpectralAngleXTRdEdx().
Referenced by BuildEnergyTable().
G4double G4VXTRenergyLoss::XTRNAngleDensity (G4double varAngle)
Definition at line 1437 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1437 of file G4VXTRenergyLoss.cc
References fMaxEnergyTR, fMinEnergyTR, fVarAngle, G4Integrator< T, F >::Legendre96(), and XTRNAngleSpectralDensity().
G4double G4VXTRenergyLoss::XTRNAngleSpectralDensity (G4double energy)
Definition at line 1427 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1427 of file G4VXTRenergyLoss.cc
References fGamma, fVarAngle, GetStackFactor(), and OneBoundaryXTRNdensity().
Referenced by XTRNAngleDensity().
G4double G4VXTRenergyLoss::XTRNSpectralAngleDensity (G4double varAngle)
Definition at line 1402 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1402 of file G4VXTRenergyLoss.cc
References fEnergy, fGamma, GetStackFactor(), and OneBoundaryXTRNdensity().
Referenced by XTRNSpectralDensity().
G4double G4VXTRenergyLoss::XTRNSpectralDensity (G4double energy)
Definition at line 1412 of file G4VXTRenergyLoss.cc.
View newest version in sPHENIX GitHub at line 1412 of file G4VXTRenergyLoss.cc
References energy, fEnergy, fMaxThetaTR, G4Integrator< T, F >::Legendre10(), G4Integrator< T, F >::Legendre96(), and XTRNSpectralAngleDensity().
Member Data Documentation
G4double G4VXTRenergyLoss::fAlphaGas protected
Definition at line 225 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 225 of file G4VXTRenergyLoss.hh
Referenced by G4GammaXTRadiator::G4GammaXTRadiator(), G4RegularXTRadiator::G4RegularXTRadiator(), G4StrawTubeXTRadiator::G4StrawTubeXTRadiator(), G4TransparentRegXTRadiator::G4TransparentRegXTRadiator(), G4VXTRenergyLoss(), G4XTRGammaRadModel::G4XTRGammaRadModel(), G4XTRTransparentRegRadModel::G4XTRTransparentRegRadModel(), G4RegularXTRadiator::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), and XTRTransparentRegRadModel::XTRTransparentRegRadModel().
G4double G4VXTRenergyLoss::fAlphaPlate protected
Definition at line 224 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 224 of file G4VXTRenergyLoss.hh
Referenced by G4GammaXTRadiator::G4GammaXTRadiator(), G4RegularXTRadiator::G4RegularXTRadiator(), G4StrawTubeXTRadiator::G4StrawTubeXTRadiator(), G4TransparentRegXTRadiator::G4TransparentRegXTRadiator(), G4VXTRenergyLoss(), G4XTRGammaRadModel::G4XTRGammaRadModel(), G4XTRTransparentRegRadModel::G4XTRTransparentRegRadModel(), G4RegularXTRadiator::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), and XTRTransparentRegRadModel::XTRTransparentRegRadModel().
std::vector<G4PhysicsTable*> G4VXTRenergyLoss::fAngleBank protected
Definition at line 234 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 234 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), and GetRandomAngle().
G4PhysicsTable* G4VXTRenergyLoss::fAngleDistrTable protected
Definition at line 185 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 185 of file G4VXTRenergyLoss.hh
Referenced by BuildEnergyTable(), BuildGlobalAngleTable(), and ~G4VXTRenergyLoss().
G4PhysicsTable* G4VXTRenergyLoss::fAngleForEnergyTable protected
Definition at line 233 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 233 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), GetRandomAngle(), and ~G4VXTRenergyLoss().
G4bool G4VXTRenergyLoss::fAngleRadDistr protected
Definition at line 212 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 212 of file G4VXTRenergyLoss.hh
Referenced by BuildEnergyTable(), BuildPhysicsTable(), G4VXTRenergyLoss(), PostStepDoIt(), SetAngleRadDistr(), and ~G4VXTRenergyLoss().
G4int G4VXTRenergyLoss::fBinTR protected
Definition at line 198 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 198 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), G4VXTRenergyLoss(), and GetRandomAngle().
G4double G4VXTRenergyLoss::fCofTR protected
Definition at line 209 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 209 of file G4VXTRenergyLoss.hh
Referenced by BuildEnergyTable(), BuildGlobalAngleTable(), and G4VXTRenergyLoss().
G4bool G4VXTRenergyLoss::fCompton protected
Definition at line 213 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 213 of file G4VXTRenergyLoss.hh
Referenced by G4VXTRenergyLoss(), SetCompton(), and G4XTRTransparentRegRadModel::SpectralXTRdEdx().
G4double G4VXTRenergyLoss::fEnergy protected
Definition at line 204 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 204 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), G4VXTRenergyLoss(), GetEnergy(), SetEnergy(), SpectralAngleXTRdEdx(), SpectralXTRdEdx(), XTRNSpectralAngleDensity(), and XTRNSpectralDensity().
G4PhysicsTable* G4VXTRenergyLoss::fEnergyDistrTable protected
Definition at line 186 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 186 of file G4VXTRenergyLoss.hh
Referenced by BuildEnergyTable(), GetMeanFreePath(), GetXTRrandomEnergy(), and ~G4VXTRenergyLoss().
G4LogicalVolume* G4VXTRenergyLoss::fEnvelope protected
Definition at line 184 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 184 of file G4VXTRenergyLoss.hh
Referenced by G4VXTRenergyLoss(), GetMeanFreePath(), PostStepDoIt(), and ~G4VXTRenergyLoss().
G4bool G4VXTRenergyLoss::fExitFlux protected
Definition at line 211 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 211 of file G4VXTRenergyLoss.hh
Referenced by G4VXTRenergyLoss(), G4XTRGammaRadModel::G4XTRGammaRadModel(), G4XTRRegularRadModel::G4XTRRegularRadModel(), G4XTRTransparentRegRadModel::G4XTRTransparentRegRadModel(), PostStepDoIt(), and XTRTransparentRegRadModel::XTRTransparentRegRadModel().
G4double G4VXTRenergyLoss::fGamma protected
Definition at line 203 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 203 of file G4VXTRenergyLoss.hh
Referenced by AngleSpectralXTRdEdx(), AngleXTRdEdx(), BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), G4VXTRenergyLoss(), GetAngleVector(), GetGamma(), GetMeanFreePath(), SetGamma(), SpectralAngleXTRdEdx(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), XTRTransparentRegRadModel::SpectralXTRdEdx(), XTRNAngleSpectralDensity(), and XTRNSpectralAngleDensity().
G4double* G4VXTRenergyLoss::fGammaCutInKineticEnergy protected
Definition at line 181 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 181 of file G4VXTRenergyLoss.hh
G4double G4VXTRenergyLoss::fGammaTkinCut protected
Definition at line 183 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 183 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), and BuildGlobalAngleTable().
G4SandiaTable* G4VXTRenergyLoss::fGasPhotoAbsCof protected
Definition at line 229 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 229 of file G4VXTRenergyLoss.hh
Referenced by ComputeGasPhotoAbsCof(), and GetGasLinearPhotoAbs().
G4double G4VXTRenergyLoss::fGasThick protected
Definition at line 223 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 223 of file G4VXTRenergyLoss.hh
Referenced by AngleXTRdEdx(), G4VXTRenergyLoss(), GetAngleVector(), G4XTRRegularRadModel::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
G4double G4VXTRenergyLoss::fLambda protected
Definition at line 206 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 206 of file G4VXTRenergyLoss.hh
Referenced by G4VXTRenergyLoss(), and GetMeanFreePath().
G4int G4VXTRenergyLoss::fMatIndex1 protected
Definition at line 217 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 217 of file G4VXTRenergyLoss.hh
Referenced by ComputePlatePhotoAbsCof(), G4VXTRenergyLoss(), and GetPlateCompton().
G4int G4VXTRenergyLoss::fMatIndex2 protected
Definition at line 218 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 218 of file G4VXTRenergyLoss.hh
Referenced by ComputeGasPhotoAbsCof(), G4VXTRenergyLoss(), and GetGasCompton().
G4double G4VXTRenergyLoss::fMaxEnergyTR protected
Definition at line 194 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 194 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), G4VXTRenergyLoss(), and XTRNAngleDensity().
G4double G4VXTRenergyLoss::fMaxProtonTkin protected
Definition at line 201 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 201 of file G4VXTRenergyLoss.hh
Referenced by G4VXTRenergyLoss().
G4double G4VXTRenergyLoss::fMaxThetaTR protected
Definition at line 197 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 197 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), G4VXTRenergyLoss(), GetAngleVector(), SpectralXTRdEdx(), and XTRNSpectralDensity().
G4double G4VXTRenergyLoss::fMinEnergyTR protected
Definition at line 193 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 193 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), G4VXTRenergyLoss(), and XTRNAngleDensity().
G4double G4VXTRenergyLoss::fMinProtonTkin protected
Definition at line 200 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 200 of file G4VXTRenergyLoss.hh
Referenced by G4VXTRenergyLoss().
G4ParticleChange G4VXTRenergyLoss::fParticleChange protected
Definition at line 231 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 231 of file G4VXTRenergyLoss.hh
Referenced by G4VXTRenergyLoss(), and PostStepDoIt().
G4double G4VXTRenergyLoss::fPlasmaCof protected
Definition at line 208 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 208 of file G4VXTRenergyLoss.hh
Referenced by G4StrawTubeXTRadiator::G4StrawTubeXTRadiator(), and G4VXTRenergyLoss().
G4int G4VXTRenergyLoss::fPlateNumber protected
Definition at line 219 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 219 of file G4VXTRenergyLoss.hh
Referenced by AngleXTRdEdx(), G4VXTRenergyLoss(), G4XTRRegularRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
G4SandiaTable* G4VXTRenergyLoss::fPlatePhotoAbsCof protected
Definition at line 227 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 227 of file G4VXTRenergyLoss.hh
Referenced by ComputePlatePhotoAbsCof(), and GetPlateLinearPhotoAbs().
G4double G4VXTRenergyLoss::fPlateThick protected
Definition at line 222 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 222 of file G4VXTRenergyLoss.hh
Referenced by AngleXTRdEdx(), G4VXTRenergyLoss(), GetAngleVector(), G4XTRRegularRadModel::GetStackFactor(), G4XTRTransparentRegRadModel::GetStackFactor(), G4RegularXTRadiator::GetStackFactor(), G4TransparentRegXTRadiator::GetStackFactor(), XTRTransparentRegRadModel::GetStackFactor(), G4StrawTubeXTRadiator::GetStackFactor(), G4XTRGammaRadModel::GetStackFactor(), G4GammaXTRadiator::GetStackFactor(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
G4PhysicsLogVector* G4VXTRenergyLoss::fProtonEnergyVector protected
Definition at line 188 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 188 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), G4VXTRenergyLoss(), GetMeanFreePath(), GetNumberOfPhotons(), GetProtonVector(), GetXTRrandomEnergy(), and ~G4VXTRenergyLoss().
G4ParticleDefinition* G4VXTRenergyLoss::fPtrGamma protected
Definition at line 179 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 179 of file G4VXTRenergyLoss.hh
Referenced by G4VXTRenergyLoss().
G4double G4VXTRenergyLoss::fSigma1 protected
Definition at line 214 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 214 of file G4VXTRenergyLoss.hh
Referenced by AngleXTRdEdx(), G4VXTRenergyLoss(), GetAngleVector(), GetPlateFormationZone(), OneBoundaryXTRNdensity(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
G4double G4VXTRenergyLoss::fSigma2 protected
Definition at line 215 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 215 of file G4VXTRenergyLoss.hh
Referenced by AngleXTRdEdx(), G4VXTRenergyLoss(), GetAngleVector(), GetGasFormationZone(), OneBoundaryXTRNdensity(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4XTRTransparentRegRadModel::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), and XTRTransparentRegRadModel::SpectralXTRdEdx().
G4double G4VXTRenergyLoss::fTheMaxAngle protected
Definition at line 195 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 195 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), and G4VXTRenergyLoss().
G4double G4VXTRenergyLoss::fTheMaxEnergyTR protected
Definition at line 192 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 192 of file G4VXTRenergyLoss.hh
Referenced by AngleXTRdEdx(), BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), and G4VXTRenergyLoss().
G4double G4VXTRenergyLoss::fTheMinAngle protected
Definition at line 196 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 196 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), and G4VXTRenergyLoss().
G4double G4VXTRenergyLoss::fTheMinEnergyTR protected
Definition at line 191 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 191 of file G4VXTRenergyLoss.hh
Referenced by AngleXTRdEdx(), BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), and G4VXTRenergyLoss().
G4double G4VXTRenergyLoss::fTotalDist protected
Definition at line 221 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 221 of file G4VXTRenergyLoss.hh
Referenced by BuildEnergyTable(), and G4VXTRenergyLoss().
G4int G4VXTRenergyLoss::fTotBin protected
Definition at line 202 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 202 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleForEnergyBank(), BuildAngleTable(), BuildEnergyTable(), BuildGlobalAngleTable(), G4VXTRenergyLoss(), GetMeanFreePath(), GetNumberOfPhotons(), GetRandomAngle(), GetTotBin(), GetXTRrandomEnergy(), and PostStepDoIt().
G4double G4VXTRenergyLoss::fVarAngle protected
Definition at line 205 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 205 of file G4VXTRenergyLoss.hh
Referenced by AngleSpectralXTRdEdx(), G4VXTRenergyLoss(), GetVarAngle(), SetVarAngle(), XTRNAngleDensity(), and XTRNAngleSpectralDensity().
G4PhysicsLogVector* G4VXTRenergyLoss::fXTREnergyVector protected
Definition at line 189 of file G4VXTRenergyLoss.hh.
View newest version in sPHENIX GitHub at line 189 of file G4VXTRenergyLoss.hh
Referenced by BuildAngleTable(), G4VXTRenergyLoss(), and ~G4VXTRenergyLoss().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/include/G4VXTRenergyLoss.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/xrays/src/G4VXTRenergyLoss.cc