ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrEvaluator.cc File Reference
G4tgrEvaluator.cc File Reference
#include "G4tgrEvaluator.hh"
#include <cmath>
Functions
G4double fsin (G4double arg)
G4double fcos (G4double arg)
G4double ftan (G4double arg)
G4double fasin (G4double arg)
G4double facos (G4double arg)
G4double fatan (G4double arg)
G4double fatan2 (G4double arg1, G4double arg2)
G4double fsinh (G4double arg)
G4double fcosh (G4double arg)
G4double ftanh (G4double arg)
G4double fsqrt (G4double arg)
G4double fexp (G4double arg)
G4double flog (G4double arg)
G4double flog10 (G4double arg)
G4double fpow (G4double arg1, G4double arg2)
Function Documentation
G4double facos (G4double arg)
Definition at line 70 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 70 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fasin (G4double arg)
Definition at line 69 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 69 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fatan (G4double arg)
Definition at line 71 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 71 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fatan2 (G4double arg1, G4double arg2)
Definition at line 72 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 72 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fcos (G4double arg)
Definition at line 67 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 67 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions(), and G4SynchrotronRadiationInMat::PostStepDoIt().
G4double fcosh (G4double arg)
Definition at line 74 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 74 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fexp (G4double arg)
Definition at line 80 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 80 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions(), and pyzdis().
G4double flog (G4double arg)
Definition at line 81 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 81 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions(), and PgPostBankBackupManager::CleanTable().
G4double flog10 (G4double arg)
Definition at line 82 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 82 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fpow (G4double arg1, G4double arg2)
Definition at line 83 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 83 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fsin (G4double arg)
Definition at line 66 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 66 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fsinh (G4double arg)
Definition at line 73 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 73 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double fsqrt (G4double arg)
Definition at line 79 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 79 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double ftan (G4double arg)
Definition at line 68 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 68 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().
G4double ftanh (G4double arg)
Definition at line 75 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 75 of file G4tgrEvaluator.cc
Referenced by G4tgrEvaluator::AddCommonFunctions().