ECCE @ EIC Software: G4AnalysisVerbose Class Reference
G4AnalysisVerbose Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4AnalysisVerbose.hh>
Public Member Functions
G4AnalysisVerbose (const G4String &type, G4int verboseLevel)
~G4AnalysisVerbose ()
void Message (const G4String &action, const G4String &object, const G4String &objectName, G4bool success=true) const
void Message (const G4String &action, const G4String &object, G4ExceptionDescription &description, G4bool success=true) const
Private Attributes
G4String fType
G4String fToBeDoneText
G4String fDoneText
G4String fFailureText
Detailed Description
Definition at line 36 of file G4AnalysisVerbose.hh.
View newest version in sPHENIX GitHub at line 36 of file G4AnalysisVerbose.hh
Constructor & Destructor Documentation
G4AnalysisVerbose::G4AnalysisVerbose (const G4String & type, G4int verboseLevel)
Definition at line 35 of file G4AnalysisVerbose.cc.
View newest version in sPHENIX GitHub at line 35 of file G4AnalysisVerbose.cc
References fDoneText, fFailureText, and fToBeDoneText.
G4AnalysisVerbose::~G4AnalysisVerbose ()
Definition at line 49 of file G4AnalysisVerbose.cc.
View newest version in sPHENIX GitHub at line 49 of file G4AnalysisVerbose.cc
Member Function Documentation
void G4AnalysisVerbose::Message (const G4String & action, const G4String & object, const G4String & objectName, G4bool success = true) const
Definition at line 58 of file G4AnalysisVerbose.cc.
View newest version in sPHENIX GitHub at line 58 of file G4AnalysisVerbose.cc
References fDoneText, fFailureText, fToBeDoneText, fType, G4cout, and G4endl.
Referenced by G4H1ToolsManager::AddH1(), G4H2ToolsManager::AddH2(), G4H3ToolsManager::AddH3(), G4RootMpiPNtupleManager::AddNtupleRow(), G4RootPNtupleManager::AddNtupleRow(), G4P1ToolsManager::AddP1(), G4P2ToolsManager::AddP2(), G4RootAnalysisManager::ClearNtupleManagers(), G4Hdf5FileManager::CloseFile(), G4PlotManager::CloseFile(), G4XmlAnalysisManager::CloseFileImpl(), G4RootAnalysisManager::CloseFileImpl(), G4XmlFileManager::CloseHnFile(), G4CsvFileManager::CloseNtupleFile(), G4XmlFileManager::CloseNtupleFile(), G4Hdf5FileManager::CreateDirectory(), G4H1ToolsManager::CreateH1(), G4H2ToolsManager::CreateH2(), G4H3ToolsManager::CreateH3(), G4RootFileManager::CreateHistoDirectory(), G4XmlFileManager::CreateHnFile(), G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), G4RootMainNtupleManager::CreateNtuple(), G4RootMpiPNtupleManager::CreateNtuple(), G4RootPNtupleManager::CreateNtuple(), G4RootFileManager::CreateNtupleDirectory(), G4CsvFileManager::CreateNtupleFile(), G4XmlFileManager::CreateNtupleFile(), G4RootAnalysisManager::CreateNtupleManagers(), G4RootMpiPNtupleManager::CreateNtuplesFromBooking(), G4RootMpiPNtupleManager::CreateNtupleTColumn(), G4RootPNtupleManager::CreateNtupleTColumn(), G4P1ToolsManager::CreateP1(), G4P2ToolsManager::CreateP2(), G4H1ToolsManager::FillH1(), G4H2ToolsManager::FillH2(), G4H3ToolsManager::FillH3(), G4TNtupleManager< tools::hdf5::ntuple >::FillNtupleTColumn(), G4TNtupleManager< tools::wroot::ntuple >::FillNtupleTColumn(), G4RootMpiPNtupleManager::FillNtupleTColumn(), G4RootPNtupleManager::FillNtupleTColumn(), G4P1ToolsManager::FillP1(), G4P2ToolsManager::FillP2(), G4MPIToolsManager::Merge(), G4RootMpiPNtupleManager::Merge(), G4RootPNtupleManager::Merge(), G4Hdf5RFileManager::OpenDirectory(), G4PlotManager::OpenFile(), G4RootMpiAnalysisManager::OpenFileImpl(), G4Hdf5AnalysisManager::OpenFileImpl(), G4XmlAnalysisManager::OpenFileImpl(), G4RootAnalysisManager::OpenFileImpl(), G4RootFileManager::OpenNtupleFiles(), G4CsvRFileManager::OpenRFile(), G4XmlRFileManager::OpenRFile(), G4RootRFileManager::OpenRFile(), G4Hdf5RFileManager::OpenRFile(), G4PlotManager::PlotAndWrite(), G4RootAnalysisReader::ReadH1Impl(), G4XmlAnalysisReader::ReadH1Impl(), G4Hdf5AnalysisReader::ReadH1Impl(), G4CsvAnalysisReader::ReadH1Impl(), G4RootAnalysisReader::ReadH2Impl(), G4XmlAnalysisReader::ReadH2Impl(), G4Hdf5AnalysisReader::ReadH2Impl(), G4CsvAnalysisReader::ReadH2Impl(), G4RootAnalysisReader::ReadH3Impl(), G4XmlAnalysisReader::ReadH3Impl(), G4Hdf5AnalysisReader::ReadH3Impl(), G4CsvAnalysisReader::ReadH3Impl(), G4XmlAnalysisReader::ReadNtupleImpl(), G4CsvAnalysisReader::ReadNtupleImpl(), G4RootAnalysisReader::ReadNtupleImpl(), G4Hdf5AnalysisReader::ReadNtupleImpl(), G4RootAnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP1Impl(), G4Hdf5AnalysisReader::ReadP1Impl(), G4CsvAnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP2Impl(), G4CsvAnalysisReader::ReadP2Impl(), G4Hdf5AnalysisReader::ReadP2Impl(), G4RootAnalysisReader::ReadP2Impl(), G4RootNtupleManager::SetCreateMode(), G4H1ToolsManager::SetH1(), G4H2ToolsManager::SetH2(), G4H3ToolsManager::SetH3(), G4RootMpiAnalysisManager::SetMpiNtupleMergingMode(), G4XmlRNtupleManager::SetNtupleDColumn(), G4XmlRNtupleManager::SetNtupleFColumn(), G4XmlRNtupleManager::SetNtupleIColumn(), G4RootAnalysisManager::SetNtupleMergingMode(), G4RootAnalysisManager::SetNtupleRowWise(), G4P1ToolsManager::SetP1(), G4P2ToolsManager::SetP2(), G4VAnalysisManager::WriteAscii(), G4XmlAnalysisManager::WriteImpl(), G4Hdf5AnalysisManager::WriteImpl(), G4CsvAnalysisManager::WriteImpl(), G4RootMpiAnalysisManager::WriteNtuple(), G4RootAnalysisManager::WriteNtuple(), G4H1ToolsManager::WriteOnAscii(), and G4PlotManager::WritePage().
void G4AnalysisVerbose::Message (const G4String & action, const G4String & object, G4ExceptionDescription & description, G4bool success = true) const
Definition at line 83 of file G4AnalysisVerbose.cc.
View newest version in sPHENIX GitHub at line 83 of file G4AnalysisVerbose.cc
References fDoneText, fFailureText, fToBeDoneText, fType, G4cout, and G4endl.
Member Data Documentation
G4String G4AnalysisVerbose::fDoneText private
Definition at line 57 of file G4AnalysisVerbose.hh.
View newest version in sPHENIX GitHub at line 57 of file G4AnalysisVerbose.hh
Referenced by G4AnalysisVerbose(), and Message().
G4String G4AnalysisVerbose::fFailureText private
Definition at line 58 of file G4AnalysisVerbose.hh.
View newest version in sPHENIX GitHub at line 58 of file G4AnalysisVerbose.hh
Referenced by G4AnalysisVerbose(), and Message().
G4String G4AnalysisVerbose::fToBeDoneText private
Definition at line 56 of file G4AnalysisVerbose.hh.
View newest version in sPHENIX GitHub at line 56 of file G4AnalysisVerbose.hh
Referenced by G4AnalysisVerbose(), and Message().
G4String G4AnalysisVerbose::fType private
Definition at line 55 of file G4AnalysisVerbose.hh.
View newest version in sPHENIX GitHub at line 55 of file G4AnalysisVerbose.hh
Referenced by Message().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4AnalysisVerbose.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4AnalysisVerbose.cc