ECCE @ EIC Software: NeuronLoadDataFile Class Reference
NeuronLoadDataFile Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/NeuronLoadDataFile.hh>
Public Member Functions
NeuronLoadDataFile ()
virtual ~NeuronLoadDataFile ()
void SingleNeuronSWCfile (const G4String &filename)
void NeuralNetworkDATAfile (const G4String &filename)
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Tubs &cylinderComp, const G4int copyNo, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
G4double GetwidthB ()
G4double GetheightB ()
G4double GetdepthB ()
G4double GetdiagnlLength ()
G4double GetshiftX ()
G4double GetshiftY ()
G4double GetshiftZ ()
G4double GetTypeN (G4int i)
G4int GetnbSomacomp ()
G4double GetMassSomacomp (G4int i)
G4double GetMassSomaTot ()
G4ThreeVector GetPosSomacomp (G4int i)
G4double GetRadSomacomp (G4int i)
G4int GetnbDendritecomp ()
G4double GetMassDendcomp (G4int i)
G4double GetMassDendTot ()
G4ThreeVector GetPosDendcomp (G4int i)
G4double GetRadDendcomp (G4int i)
G4double GetHeightDendcomp (G4int i)
G4double GetDistADendSoma (G4int i)
G4double GetDistBDendSoma (G4int i)
G4RotationMatrix GetRotDendcomp (G4int i)
G4int GetnbAxoncomp ()
G4double GetMassAxoncomp (G4int i)
G4double GetMassAxonTot ()
G4ThreeVector GetPosAxoncomp (G4int i)
G4double GetRadAxoncomp (G4int i)
G4double GetHeightAxoncomp (G4int i)
G4double GetDistAxonsoma (G4int i)
G4RotationMatrix GetRotAxoncomp (G4int i)
G4int GetnbSpinecomp ()
G4double GetMassSpinecomp (G4int i)
G4double GetMassSpineTot ()
G4ThreeVector GetPosSpinecomp (G4int i)
G4double GetRadSpinecomp (G4int i)
G4double GetHeightSpinecomp (G4int i)
G4double GetDistSpinesoma (G4int i)
G4RotationMatrix GetRotSpinecomp (G4int i)
G4int GetnbNeuroncomp ()
G4double GetTotVolNeuron ()
G4double GetTotSurfNeuron ()
G4double GetTotMassNeuron ()
G4double GetTotVolSlice ()
G4double GetTotSurfSlice ()
G4double GetTotMassSlice ()
G4double GetTotVolMedium ()
G4double GetTotSurfMedium ()
G4double GetTotMassMedium ()
G4VisAttributes GetSomaColour ()
G4VisAttributes GetDendColour ()
G4VisAttributes GetAxonColour ()
G4VisAttributes GetSpineColour ()
G4VisAttributes GetNeuronColour ()
Private Attributes
G4String fNeuronFileNameSWC
NEURON filename.
G4String fNeuronFileNameDATA
G4int fnbSomacomp
G4int fnbDendritecomp
G4int fnbAxoncomp
G4int fnbSpinecomp
G4int fnbNeuroncomp
G4int * fnNn
G4int * fpNn
G4int * fnNd
G4int * fpNd
G4int * fnNa
G4int * fpNa
G4int * fTypeN
G4double fshiftX
G4double fshiftY
G4double fshiftZ
G4double fwidthB
G4double fheightB
G4double fdepthB
G4double fdiagnlLength
G4ThreeVector * fPosSomacomp
G4double * fRadSomacomp
G4double * fMassSomacomp
G4double fMassSomaTot
G4double * fRadDendcomp
G4double * fDistADendSoma
G4double * fDistBDendSoma
G4double * fHeightDendcomp
G4double * fMassDendcomp
G4double fMassDendTot
G4ThreeVector * fPosDendcomp
G4RotationMatrix * fRotDendcomp
G4double * fRadAxoncomp
G4double * fHeightAxoncomp
G4double * fDistAxonsoma
G4double * fMassAxoncomp
G4double fMassAxonTot
G4ThreeVector * fPosAxoncomp
G4RotationMatrix * fRotAxoncomp
G4double * fRadSpinecomp
G4double * fHeightSpinecomp
G4double * fDistSpinesoma
G4double * fMassSpinecomp
G4double fMassSpineTot
G4ThreeVector * fPosSpinecomp
G4RotationMatrix * fRotSpinecomp
G4double * fRadNeuroncomp
G4double * fHeightNeuroncomp
G4double * fDistNeuronsoma
G4double * fMassNeuroncomp
G4ThreeVector * fPosNeuroncomp
G4RotationMatrix * fRotNeuroncomp
G4double fTotVolNeuron
G4double fTotSurfNeuron
G4double fTotMassNeuron
G4double fTotVolSlice
G4double fTotSurfSlice
G4double fTotMassSlice
G4double fTotVolMedium
G4double fTotSurfMedium
G4double fTotMassMedium
G4VisAttributes * fSomaColour
G4VisAttributes * fDendColour
G4VisAttributes * fAxonColour
G4VisAttributes * fSpineColour
G4VisAttributes * fNeuronColour
Detailed Description
Definition at line 79 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 79 of file NeuronLoadDataFile.hh
Constructor & Destructor Documentation
NeuronLoadDataFile::NeuronLoadDataFile ()
Definition at line 76 of file NeuronLoadDataFile.cc.
View newest version in sPHENIX GitHub at line 76 of file NeuronLoadDataFile.cc
References G4DNAPARSER::Command::GetOption().
NeuronLoadDataFile::~NeuronLoadDataFile () virtual
Definition at line 851 of file NeuronLoadDataFile.cc.
View newest version in sPHENIX GitHub at line 851 of file NeuronLoadDataFile.cc
Member Function Documentation
void NeuronLoadDataFile::ComputeDimensions (G4Tubs & cylinderComp, const G4int copyNo, const G4VPhysicalVolume *) const
Definition at line 952 of file NeuronLoadDataFile.cc.
View newest version in sPHENIX GitHub at line 952 of file NeuronLoadDataFile.cc
References deg, G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), G4Tubs::SetZHalfLength(), and um.
void NeuronLoadDataFile::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 104 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 104 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 106 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 106 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 108 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 108 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 110 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 110 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 112 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 112 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 115 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 115 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 118 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 118 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 121 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 121 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 124 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 124 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 127 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 127 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 130 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 130 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline
Definition at line 133 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 133 of file NeuronLoadDataFile.hh
void NeuronLoadDataFile::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const
Definition at line 880 of file NeuronLoadDataFile.cc.
View newest version in sPHENIX GitHub at line 880 of file NeuronLoadDataFile.cc
References FLT_EPSILON, CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::HepRotation::rotateZ(), G4VPhysicalVolume::SetRotation(), G4VPhysicalVolume::SetTranslation(), um, x, CLHEP::HepRotation::xx(), y, CLHEP::HepRotation::yx(), CLHEP::HepRotation::yy(), CLHEP::HepRotation::yz(), z, CLHEP::HepRotation::zx(), CLHEP::HepRotation::zy(), and CLHEP::HepRotation::zz().
G4VisAttributes NeuronLoadDataFile::GetAxonColour () inline
Definition at line 194 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 194 of file NeuronLoadDataFile.hh
References fAxonColour.
G4VisAttributes NeuronLoadDataFile::GetDendColour () inline
Definition at line 193 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 193 of file NeuronLoadDataFile.hh
References fDendColour.
G4double NeuronLoadDataFile::GetdepthB () inline
Definition at line 139 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 139 of file NeuronLoadDataFile.hh
References fdepthB.
G4double NeuronLoadDataFile::GetdiagnlLength () inline
Definition at line 140 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 140 of file NeuronLoadDataFile.hh
References fdiagnlLength.
G4double NeuronLoadDataFile::GetDistADendSoma (G4int i) inline
Definition at line 158 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 158 of file NeuronLoadDataFile.hh
References fDistADendSoma.
G4double NeuronLoadDataFile::GetDistAxonsoma (G4int i) inline
Definition at line 168 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 168 of file NeuronLoadDataFile.hh
References fDistAxonsoma.
G4double NeuronLoadDataFile::GetDistBDendSoma (G4int i) inline
Definition at line 159 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 159 of file NeuronLoadDataFile.hh
References fDistBDendSoma.
G4double NeuronLoadDataFile::GetDistSpinesoma (G4int i) inline
Definition at line 177 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 177 of file NeuronLoadDataFile.hh
References fDistSpinesoma.
G4double NeuronLoadDataFile::GetHeightAxoncomp (G4int i) inline
Definition at line 167 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 167 of file NeuronLoadDataFile.hh
References fHeightAxoncomp.
G4double NeuronLoadDataFile::GetheightB () inline
Definition at line 138 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 138 of file NeuronLoadDataFile.hh
References fheightB.
G4double NeuronLoadDataFile::GetHeightDendcomp (G4int i) inline
Definition at line 157 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 157 of file NeuronLoadDataFile.hh
References fHeightDendcomp.
G4double NeuronLoadDataFile::GetHeightSpinecomp (G4int i) inline
Definition at line 176 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 176 of file NeuronLoadDataFile.hh
References fHeightSpinecomp.
G4double NeuronLoadDataFile::GetMassAxoncomp (G4int i) inline
Definition at line 163 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 163 of file NeuronLoadDataFile.hh
References fMassAxoncomp.
G4double NeuronLoadDataFile::GetMassAxonTot () inline
Definition at line 164 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 164 of file NeuronLoadDataFile.hh
References fMassAxonTot.
G4double NeuronLoadDataFile::GetMassDendcomp (G4int i) inline
Definition at line 153 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 153 of file NeuronLoadDataFile.hh
References fMassDendcomp.
G4double NeuronLoadDataFile::GetMassDendTot () inline
Definition at line 154 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 154 of file NeuronLoadDataFile.hh
References fMassDendTot.
G4double NeuronLoadDataFile::GetMassSomacomp (G4int i) inline
Definition at line 147 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 147 of file NeuronLoadDataFile.hh
References fMassSomacomp.
G4double NeuronLoadDataFile::GetMassSomaTot () inline
Definition at line 148 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 148 of file NeuronLoadDataFile.hh
References fMassSomaTot.
G4double NeuronLoadDataFile::GetMassSpinecomp (G4int i) inline
Definition at line 172 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 172 of file NeuronLoadDataFile.hh
References fMassSpinecomp.
G4double NeuronLoadDataFile::GetMassSpineTot () inline
Definition at line 173 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 173 of file NeuronLoadDataFile.hh
References fMassSpineTot.
G4int NeuronLoadDataFile::GetnbAxoncomp () inline
Definition at line 162 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 162 of file NeuronLoadDataFile.hh
References fnbAxoncomp.
G4int NeuronLoadDataFile::GetnbDendritecomp () inline
Definition at line 152 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 152 of file NeuronLoadDataFile.hh
References fnbDendritecomp.
G4int NeuronLoadDataFile::GetnbNeuroncomp () inline
Definition at line 180 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 180 of file NeuronLoadDataFile.hh
References fnbNeuroncomp.
G4int NeuronLoadDataFile::GetnbSomacomp () inline
Definition at line 146 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 146 of file NeuronLoadDataFile.hh
References fnbSomacomp.
G4int NeuronLoadDataFile::GetnbSpinecomp () inline
Definition at line 171 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 171 of file NeuronLoadDataFile.hh
References fnbSpinecomp.
G4VisAttributes NeuronLoadDataFile::GetNeuronColour () inline
Definition at line 196 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 196 of file NeuronLoadDataFile.hh
References fNeuronColour.
G4ThreeVector NeuronLoadDataFile::GetPosAxoncomp (G4int i) inline
Definition at line 165 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 165 of file NeuronLoadDataFile.hh
References fPosAxoncomp.
G4ThreeVector NeuronLoadDataFile::GetPosDendcomp (G4int i) inline
Definition at line 155 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 155 of file NeuronLoadDataFile.hh
References fPosDendcomp.
G4ThreeVector NeuronLoadDataFile::GetPosSomacomp (G4int i) inline
Definition at line 149 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 149 of file NeuronLoadDataFile.hh
References fPosSomacomp.
G4ThreeVector NeuronLoadDataFile::GetPosSpinecomp (G4int i) inline
Definition at line 174 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 174 of file NeuronLoadDataFile.hh
References fPosSpinecomp.
G4double NeuronLoadDataFile::GetRadAxoncomp (G4int i) inline
Definition at line 166 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 166 of file NeuronLoadDataFile.hh
References fRadAxoncomp.
G4double NeuronLoadDataFile::GetRadDendcomp (G4int i) inline
Definition at line 156 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 156 of file NeuronLoadDataFile.hh
References fRadDendcomp.
G4double NeuronLoadDataFile::GetRadSomacomp (G4int i) inline
Definition at line 150 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 150 of file NeuronLoadDataFile.hh
References fRadSomacomp.
G4double NeuronLoadDataFile::GetRadSpinecomp (G4int i) inline
Definition at line 175 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 175 of file NeuronLoadDataFile.hh
References fRadSpinecomp.
G4RotationMatrix NeuronLoadDataFile::GetRotAxoncomp (G4int i) inline
Definition at line 169 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 169 of file NeuronLoadDataFile.hh
References fRotAxoncomp.
G4RotationMatrix NeuronLoadDataFile::GetRotDendcomp (G4int i) inline
Definition at line 160 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 160 of file NeuronLoadDataFile.hh
References fRotDendcomp.
G4RotationMatrix NeuronLoadDataFile::GetRotSpinecomp (G4int i) inline
Definition at line 178 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 178 of file NeuronLoadDataFile.hh
References fRotSpinecomp.
G4double NeuronLoadDataFile::GetshiftX () inline
Definition at line 141 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 141 of file NeuronLoadDataFile.hh
References fshiftX.
G4double NeuronLoadDataFile::GetshiftY () inline
Definition at line 142 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 142 of file NeuronLoadDataFile.hh
References fshiftY.
G4double NeuronLoadDataFile::GetshiftZ () inline
Definition at line 143 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 143 of file NeuronLoadDataFile.hh
References fshiftZ.
G4VisAttributes NeuronLoadDataFile::GetSomaColour () inline
Definition at line 192 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 192 of file NeuronLoadDataFile.hh
References fSomaColour.
G4VisAttributes NeuronLoadDataFile::GetSpineColour () inline
Definition at line 195 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 195 of file NeuronLoadDataFile.hh
References fSpineColour.
G4double NeuronLoadDataFile::GetTotMassMedium () inline
Definition at line 190 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 190 of file NeuronLoadDataFile.hh
References fTotMassMedium.
G4double NeuronLoadDataFile::GetTotMassNeuron () inline
Definition at line 184 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 184 of file NeuronLoadDataFile.hh
References fTotMassNeuron.
G4double NeuronLoadDataFile::GetTotMassSlice () inline
Definition at line 187 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 187 of file NeuronLoadDataFile.hh
References fTotMassSlice.
G4double NeuronLoadDataFile::GetTotSurfMedium () inline
Definition at line 189 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 189 of file NeuronLoadDataFile.hh
References fTotSurfMedium.
G4double NeuronLoadDataFile::GetTotSurfNeuron () inline
Definition at line 183 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 183 of file NeuronLoadDataFile.hh
References fTotSurfNeuron.
G4double NeuronLoadDataFile::GetTotSurfSlice () inline
Definition at line 186 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 186 of file NeuronLoadDataFile.hh
References fTotSurfSlice.
G4double NeuronLoadDataFile::GetTotVolMedium () inline
Definition at line 188 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 188 of file NeuronLoadDataFile.hh
References fTotVolMedium.
G4double NeuronLoadDataFile::GetTotVolNeuron () inline
Definition at line 182 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 182 of file NeuronLoadDataFile.hh
References fTotVolNeuron.
G4double NeuronLoadDataFile::GetTotVolSlice () inline
Definition at line 185 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 185 of file NeuronLoadDataFile.hh
References fTotVolSlice.
G4double NeuronLoadDataFile::GetTypeN (G4int i) inline
Definition at line 144 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 144 of file NeuronLoadDataFile.hh
References fTypeN.
G4double NeuronLoadDataFile::GetwidthB () inline
Definition at line 137 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 137 of file NeuronLoadDataFile.hh
References fwidthB.
void NeuronLoadDataFile::NeuralNetworkDATAfile (const G4String & filename)
Definition at line 659 of file NeuronLoadDataFile.cc.
View newest version in sPHENIX GitHub at line 659 of file NeuronLoadDataFile.cc
References cm3, e, g4zmq::exit(), Acts::UnitConstants::g, G4cout, G4endl, CLHEP::HepRotation::inverse(), nlines, CLHEP::Hep3Vector::phi(), pi, radius, CLHEP::Hep3Vector::theta(), um, x1, x2, y1, y2, z1, and z2.
void NeuronLoadDataFile::SingleNeuronSWCfile (const G4String & filename)
Definition at line 115 of file NeuronLoadDataFile.cc.
View newest version in sPHENIX GitHub at line 115 of file NeuronLoadDataFile.cc
References cm3, e, g4zmq::exit(), Acts::UnitConstants::g, G4cout, G4endl, CLHEP::HepRotation::inverse(), maxY, maxZ, minY, nlines, CLHEP::Hep3Vector::phi(), pi, radius, G4VisAttributes::SetColour(), CLHEP::Hep3Vector::theta(), um, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Member Data Documentation
G4VisAttributes* NeuronLoadDataFile::fAxonColour private
Definition at line 275 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 275 of file NeuronLoadDataFile.hh
Referenced by GetAxonColour().
G4VisAttributes* NeuronLoadDataFile::fDendColour private
Definition at line 274 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 274 of file NeuronLoadDataFile.hh
Referenced by GetDendColour().
G4double NeuronLoadDataFile::fdepthB private
Definition at line 222 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 222 of file NeuronLoadDataFile.hh
Referenced by GetdepthB().
G4double NeuronLoadDataFile::fdiagnlLength private
Definition at line 223 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 223 of file NeuronLoadDataFile.hh
Referenced by GetdiagnlLength().
G4double* NeuronLoadDataFile::fDistADendSoma private
Definition at line 231 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 231 of file NeuronLoadDataFile.hh
Referenced by GetDistADendSoma().
G4double* NeuronLoadDataFile::fDistAxonsoma private
Definition at line 241 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 241 of file NeuronLoadDataFile.hh
Referenced by GetDistAxonsoma().
G4double* NeuronLoadDataFile::fDistBDendSoma private
Definition at line 232 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 232 of file NeuronLoadDataFile.hh
Referenced by GetDistBDendSoma().
G4double* NeuronLoadDataFile::fDistNeuronsoma private
Definition at line 257 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 257 of file NeuronLoadDataFile.hh
G4double* NeuronLoadDataFile::fDistSpinesoma private
Definition at line 249 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 249 of file NeuronLoadDataFile.hh
Referenced by GetDistSpinesoma().
G4double* NeuronLoadDataFile::fHeightAxoncomp private
Definition at line 240 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 240 of file NeuronLoadDataFile.hh
Referenced by GetHeightAxoncomp().
G4double NeuronLoadDataFile::fheightB private
Definition at line 221 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 221 of file NeuronLoadDataFile.hh
Referenced by GetheightB().
G4double* NeuronLoadDataFile::fHeightDendcomp private
Definition at line 233 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 233 of file NeuronLoadDataFile.hh
Referenced by GetHeightDendcomp().
G4double* NeuronLoadDataFile::fHeightNeuroncomp private
Definition at line 256 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 256 of file NeuronLoadDataFile.hh
G4double* NeuronLoadDataFile::fHeightSpinecomp private
Definition at line 248 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 248 of file NeuronLoadDataFile.hh
Referenced by GetHeightSpinecomp().
G4double* NeuronLoadDataFile::fMassAxoncomp private
Definition at line 242 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 242 of file NeuronLoadDataFile.hh
Referenced by GetMassAxoncomp().
G4double NeuronLoadDataFile::fMassAxonTot private
Definition at line 243 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 243 of file NeuronLoadDataFile.hh
Referenced by GetMassAxonTot().
G4double* NeuronLoadDataFile::fMassDendcomp private
Definition at line 234 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 234 of file NeuronLoadDataFile.hh
Referenced by GetMassDendcomp().
G4double NeuronLoadDataFile::fMassDendTot private
Definition at line 235 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 235 of file NeuronLoadDataFile.hh
Referenced by GetMassDendTot().
G4double* NeuronLoadDataFile::fMassNeuroncomp private
Definition at line 258 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 258 of file NeuronLoadDataFile.hh
G4double* NeuronLoadDataFile::fMassSomacomp private
Definition at line 227 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 227 of file NeuronLoadDataFile.hh
Referenced by GetMassSomacomp().
G4double NeuronLoadDataFile::fMassSomaTot private
Definition at line 228 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 228 of file NeuronLoadDataFile.hh
Referenced by GetMassSomaTot().
G4double* NeuronLoadDataFile::fMassSpinecomp private
Definition at line 250 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 250 of file NeuronLoadDataFile.hh
Referenced by GetMassSpinecomp().
G4double NeuronLoadDataFile::fMassSpineTot private
Definition at line 251 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 251 of file NeuronLoadDataFile.hh
Referenced by GetMassSpineTot().
G4int NeuronLoadDataFile::fnbAxoncomp private
Definition at line 206 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 206 of file NeuronLoadDataFile.hh
Referenced by GetnbAxoncomp().
G4int NeuronLoadDataFile::fnbDendritecomp private
Definition at line 205 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 205 of file NeuronLoadDataFile.hh
Referenced by GetnbDendritecomp().
G4int NeuronLoadDataFile::fnbNeuroncomp private
Definition at line 208 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 208 of file NeuronLoadDataFile.hh
Referenced by GetnbNeuroncomp().
G4int NeuronLoadDataFile::fnbSomacomp private
Definition at line 204 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 204 of file NeuronLoadDataFile.hh
Referenced by GetnbSomacomp().
G4int NeuronLoadDataFile::fnbSpinecomp private
Definition at line 207 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 207 of file NeuronLoadDataFile.hh
Referenced by GetnbSpinecomp().
G4VisAttributes* NeuronLoadDataFile::fNeuronColour private
Definition at line 277 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 277 of file NeuronLoadDataFile.hh
Referenced by GetNeuronColour().
G4String NeuronLoadDataFile::fNeuronFileNameDATA private
Definition at line 202 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 202 of file NeuronLoadDataFile.hh
G4String NeuronLoadDataFile::fNeuronFileNameSWC private
NEURON filename.
Definition at line 201 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 201 of file NeuronLoadDataFile.hh
G4int* NeuronLoadDataFile::fnNa private
Definition at line 215 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 215 of file NeuronLoadDataFile.hh
G4int* NeuronLoadDataFile::fnNd private
Definition at line 213 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 213 of file NeuronLoadDataFile.hh
G4int* NeuronLoadDataFile::fnNn private
Definition at line 210 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 210 of file NeuronLoadDataFile.hh
G4int* NeuronLoadDataFile::fpNa private
Definition at line 216 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 216 of file NeuronLoadDataFile.hh
G4int* NeuronLoadDataFile::fpNd private
Definition at line 214 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 214 of file NeuronLoadDataFile.hh
G4int* NeuronLoadDataFile::fpNn private
Definition at line 211 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 211 of file NeuronLoadDataFile.hh
G4ThreeVector* NeuronLoadDataFile::fPosAxoncomp private
Definition at line 244 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 244 of file NeuronLoadDataFile.hh
Referenced by GetPosAxoncomp().
G4ThreeVector* NeuronLoadDataFile::fPosDendcomp private
Definition at line 236 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 236 of file NeuronLoadDataFile.hh
Referenced by GetPosDendcomp().
G4ThreeVector* NeuronLoadDataFile::fPosNeuroncomp private
Definition at line 260 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 260 of file NeuronLoadDataFile.hh
G4ThreeVector* NeuronLoadDataFile::fPosSomacomp private
Definition at line 225 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 225 of file NeuronLoadDataFile.hh
Referenced by GetPosSomacomp().
G4ThreeVector* NeuronLoadDataFile::fPosSpinecomp private
Definition at line 252 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 252 of file NeuronLoadDataFile.hh
Referenced by GetPosSpinecomp().
G4double* NeuronLoadDataFile::fRadAxoncomp private
Definition at line 239 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 239 of file NeuronLoadDataFile.hh
Referenced by GetRadAxoncomp().
G4double* NeuronLoadDataFile::fRadDendcomp private
Definition at line 230 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 230 of file NeuronLoadDataFile.hh
Referenced by GetRadDendcomp().
G4double* NeuronLoadDataFile::fRadNeuroncomp private
Definition at line 255 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 255 of file NeuronLoadDataFile.hh
G4double* NeuronLoadDataFile::fRadSomacomp private
Definition at line 226 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 226 of file NeuronLoadDataFile.hh
Referenced by GetRadSomacomp().
G4double* NeuronLoadDataFile::fRadSpinecomp private
Definition at line 247 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 247 of file NeuronLoadDataFile.hh
Referenced by GetRadSpinecomp().
G4RotationMatrix* NeuronLoadDataFile::fRotAxoncomp private
Definition at line 245 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 245 of file NeuronLoadDataFile.hh
Referenced by GetRotAxoncomp().
G4RotationMatrix* NeuronLoadDataFile::fRotDendcomp private
Definition at line 237 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 237 of file NeuronLoadDataFile.hh
Referenced by GetRotDendcomp().
G4RotationMatrix* NeuronLoadDataFile::fRotNeuroncomp private
Definition at line 261 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 261 of file NeuronLoadDataFile.hh
G4RotationMatrix* NeuronLoadDataFile::fRotSpinecomp private
Definition at line 253 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 253 of file NeuronLoadDataFile.hh
Referenced by GetRotSpinecomp().
G4double NeuronLoadDataFile::fshiftX private
Definition at line 219 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 219 of file NeuronLoadDataFile.hh
Referenced by GetshiftX().
G4double NeuronLoadDataFile::fshiftY private
Definition at line 219 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 219 of file NeuronLoadDataFile.hh
Referenced by GetshiftY().
G4double NeuronLoadDataFile::fshiftZ private
Definition at line 219 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 219 of file NeuronLoadDataFile.hh
Referenced by GetshiftZ().
G4VisAttributes* NeuronLoadDataFile::fSomaColour private
Definition at line 273 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 273 of file NeuronLoadDataFile.hh
Referenced by GetSomaColour().
G4VisAttributes* NeuronLoadDataFile::fSpineColour private
Definition at line 276 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 276 of file NeuronLoadDataFile.hh
Referenced by GetSpineColour().
G4double NeuronLoadDataFile::fTotMassMedium private
Definition at line 271 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 271 of file NeuronLoadDataFile.hh
Referenced by GetTotMassMedium().
G4double NeuronLoadDataFile::fTotMassNeuron private
Definition at line 265 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 265 of file NeuronLoadDataFile.hh
Referenced by GetTotMassNeuron().
G4double NeuronLoadDataFile::fTotMassSlice private
Definition at line 268 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 268 of file NeuronLoadDataFile.hh
Referenced by GetTotMassSlice().
G4double NeuronLoadDataFile::fTotSurfMedium private
Definition at line 270 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 270 of file NeuronLoadDataFile.hh
Referenced by GetTotSurfMedium().
G4double NeuronLoadDataFile::fTotSurfNeuron private
Definition at line 264 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 264 of file NeuronLoadDataFile.hh
Referenced by GetTotSurfNeuron().
G4double NeuronLoadDataFile::fTotSurfSlice private
Definition at line 267 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 267 of file NeuronLoadDataFile.hh
Referenced by GetTotSurfSlice().
G4double NeuronLoadDataFile::fTotVolMedium private
Definition at line 269 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 269 of file NeuronLoadDataFile.hh
Referenced by GetTotVolMedium().
G4double NeuronLoadDataFile::fTotVolNeuron private
Definition at line 263 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 263 of file NeuronLoadDataFile.hh
Referenced by GetTotVolNeuron().
G4double NeuronLoadDataFile::fTotVolSlice private
Definition at line 266 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 266 of file NeuronLoadDataFile.hh
Referenced by GetTotVolSlice().
G4int* NeuronLoadDataFile::fTypeN private
Definition at line 217 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 217 of file NeuronLoadDataFile.hh
Referenced by GetTypeN().
G4double NeuronLoadDataFile::fwidthB private
Definition at line 220 of file NeuronLoadDataFile.hh.
View newest version in sPHENIX GitHub at line 220 of file NeuronLoadDataFile.hh
Referenced by GetwidthB().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/NeuronLoadDataFile.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/NeuronLoadDataFile.cc