ECCE @ EIC Software: G4InteractionLawPhysical Class Reference
G4InteractionLawPhysical Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4InteractionLawPhysical.hh>
Public Member Functions
G4InteractionLawPhysical (G4String name="exponentialLaw")
virtual ~G4InteractionLawPhysical ()
void SetPhysicalCrossSection (G4double crossSection)
G4double GetPhysicalCrossSection () const
virtual G4double ComputeEffectiveCrossSectionAt (G4double length) const
virtual G4double ComputeNonInteractionProbabilityAt (G4double length) const
virtual G4double SampleInteractionLength ()
virtual G4double UpdateInteractionLengthForStep (G4double truePathLength)
Public Member Functions inherited from G4VBiasingInteractionLaw
G4VBiasingInteractionLaw (G4String name)
virtual ~G4VBiasingInteractionLaw ()
const G4String & GetName () const
virtual G4bool IsSingular () const
virtual G4bool IsEffectiveCrossSectionInfinite () const
G4double Sample ()
G4double UpdateForStep (G4double truePathLength)
G4double GetSampledInteractionLength () const
Private Attributes
G4double fCrossSection
G4bool fCrossSectionDefined
G4double fNumberOfInteractionLength
Detailed Description
Definition at line 44 of file G4InteractionLawPhysical.hh.
View newest version in sPHENIX GitHub at line 44 of file G4InteractionLawPhysical.hh
Constructor & Destructor Documentation
G4InteractionLawPhysical::G4InteractionLawPhysical (G4String name = "exponentialLaw")
Definition at line 29 of file G4InteractionLawPhysical.cc.
View newest version in sPHENIX GitHub at line 29 of file G4InteractionLawPhysical.cc
G4InteractionLawPhysical::~G4InteractionLawPhysical () virtual
Definition at line 36 of file G4InteractionLawPhysical.cc.
View newest version in sPHENIX GitHub at line 36 of file G4InteractionLawPhysical.cc
Member Function Documentation
G4double G4InteractionLawPhysical::ComputeEffectiveCrossSectionAt (G4double length) const virtual
Implements G4VBiasingInteractionLaw.
Definition at line 53 of file G4InteractionLawPhysical.cc.
View newest version in sPHENIX GitHub at line 53 of file G4InteractionLawPhysical.cc
References fCrossSection, fCrossSectionDefined, G4Exception(), and JustWarning.
Referenced by G4BiasingProcessInterface::PostStepDoIt().
G4double G4InteractionLawPhysical::ComputeNonInteractionProbabilityAt (G4double length) const virtual
Implements G4VBiasingInteractionLaw.
Definition at line 62 of file G4InteractionLawPhysical.cc.
View newest version in sPHENIX GitHub at line 62 of file G4InteractionLawPhysical.cc
References fCrossSection, fCrossSectionDefined, G4Exception(), and JustWarning.
Referenced by G4BiasingProcessInterface::AlongStepDoIt().
G4double G4InteractionLawPhysical::GetPhysicalCrossSection () const inline
Definition at line 52 of file G4InteractionLawPhysical.hh.
View newest version in sPHENIX GitHub at line 52 of file G4InteractionLawPhysical.hh
References fCrossSection.
Referenced by G4BOptnChangeCrossSection::GetBiasedCrossSection().
G4double G4InteractionLawPhysical::SampleInteractionLength () virtual
Implements G4VBiasingInteractionLaw.
Definition at line 73 of file G4InteractionLawPhysical.cc.
View newest version in sPHENIX GitHub at line 73 of file G4InteractionLawPhysical.cc
References DBL_MAX, FatalException, fCrossSection, fCrossSectionDefined, fNumberOfInteractionLength, G4Exception(), and G4UniformRand.
void G4InteractionLawPhysical::SetPhysicalCrossSection (G4double crossSection)
Definition at line 39 of file G4InteractionLawPhysical.cc.
View newest version in sPHENIX GitHub at line 39 of file G4InteractionLawPhysical.cc
References fCrossSection, fCrossSectionDefined, G4Exception(), and JustWarning.
Referenced by G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), and G4BOptnChangeCrossSection::SetBiasedCrossSection().
G4double G4InteractionLawPhysical::UpdateInteractionLengthForStep (G4double truePathLength) virtual
Reimplemented from G4VBiasingInteractionLaw.
Definition at line 86 of file G4InteractionLawPhysical.cc.
View newest version in sPHENIX GitHub at line 86 of file G4InteractionLawPhysical.cc
References fCrossSection, fNumberOfInteractionLength, G4endl, G4Exception(), G4VBiasingInteractionLaw::GetName(), and JustWarning.
Member Data Documentation
G4double G4InteractionLawPhysical::fCrossSection private
Definition at line 64 of file G4InteractionLawPhysical.hh.
View newest version in sPHENIX GitHub at line 64 of file G4InteractionLawPhysical.hh
Referenced by ComputeEffectiveCrossSectionAt(), ComputeNonInteractionProbabilityAt(), GetPhysicalCrossSection(), SampleInteractionLength(), SetPhysicalCrossSection(), and UpdateInteractionLengthForStep().
G4bool G4InteractionLawPhysical::fCrossSectionDefined private
Definition at line 65 of file G4InteractionLawPhysical.hh.
View newest version in sPHENIX GitHub at line 65 of file G4InteractionLawPhysical.hh
Referenced by ComputeEffectiveCrossSectionAt(), ComputeNonInteractionProbabilityAt(), SampleInteractionLength(), and SetPhysicalCrossSection().
G4double G4InteractionLawPhysical::fNumberOfInteractionLength private
Definition at line 66 of file G4InteractionLawPhysical.hh.
View newest version in sPHENIX GitHub at line 66 of file G4InteractionLawPhysical.hh
Referenced by SampleInteractionLength(), and UpdateInteractionLengthForStep().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4InteractionLawPhysical.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4InteractionLawPhysical.cc