ECCE @ EIC Software: G4AblaDataFile Class Reference
G4AblaDataFile Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/include/G4AblaDataFile.hh>
Public Member Functions
G4AblaDataFile ()
~G4AblaDataFile ()
bool readData ()
Public Member Functions inherited from G4AblaVirtualData
G4bool setAlpha (G4int A, G4int Z, G4double value)
G4bool setEcnz (G4int A, G4int Z, G4double value)
G4bool setVgsld (G4int A, G4int Z, G4double value)
G4bool setPace2 (G4int A, G4int Z, G4double value)
G4bool setRms (G4int A, G4int Z, G4double value)
G4bool setMexp (G4int A, G4int Z, G4double value)
G4bool setMexpID (G4int A, G4int Z, G4int value)
G4bool setBeta2 (G4int A, G4int Z, G4double value)
G4bool setBeta4 (G4int A, G4int Z, G4double value)
G4double getAlpha (G4int A, G4int Z)
G4double getEcnz (G4int A, G4int Z)
G4double getVgsld (G4int A, G4int Z)
G4double getPace2 (G4int A, G4int Z)
G4double getRms (G4int A, G4int Z)
G4double getMexp (G4int A, G4int Z)
G4int getMexpID (G4int A, G4int Z)
G4double getBeta2 (G4int A, G4int Z)
G4double getBeta4 (G4int A, G4int Z)
G4int getAlphaRows ()
G4int getAlphaCols ()
G4int getPaceRows ()
G4int getPaceCols ()
Private Attributes
G4int verboseLevel
Additional Inherited Members
Protected Member Functions inherited from G4AblaVirtualData
G4AblaVirtualData ()
virtual ~G4AblaVirtualData ()
Detailed Description
Read ABLA data from files.
Definition at line 45 of file G4AblaDataFile.hh.
View newest version in sPHENIX GitHub at line 45 of file G4AblaDataFile.hh
Constructor & Destructor Documentation
G4AblaDataFile::G4AblaDataFile ()
Definition at line 52 of file G4AblaDataFile.cc.
View newest version in sPHENIX GitHub at line 52 of file G4AblaDataFile.cc
References G4AblaVirtualData::G4AblaVirtualData(), and verboseLevel.
G4AblaDataFile::~G4AblaDataFile ()
Definition at line 61 of file G4AblaDataFile.cc.
View newest version in sPHENIX GitHub at line 61 of file G4AblaDataFile.cc
Member Function Documentation
bool G4AblaDataFile::readData () virtual
Read all data from files.
Implements G4AblaVirtualData.
Definition at line 68 of file G4AblaDataFile.cc.
View newest version in sPHENIX GitHub at line 68 of file G4AblaDataFile.cc
References A(), kdfinder::abs(), e, FatalException, G4endl, G4Exception(), G4AblaVirtualData::getPace2(), G4AblaVirtualData::getPaceCols(), G4AblaVirtualData::getPaceRows(), G4AblaVirtualData::setAlpha(), G4AblaVirtualData::setBeta2(), G4AblaVirtualData::setBeta4(), G4AblaVirtualData::setEcnz(), G4AblaVirtualData::setMexp(), G4AblaVirtualData::setMexpID(), G4AblaVirtualData::setPace2(), G4AblaVirtualData::setRms(), G4AblaVirtualData::setVgsld(), and verboseLevel.
Referenced by G4Abla::initEvapora().
Member Data Documentation
G4int G4AblaDataFile::verboseLevel private
Definition at line 61 of file G4AblaDataFile.hh.
View newest version in sPHENIX GitHub at line 61 of file G4AblaDataFile.hh
Referenced by G4AblaDataFile(), and readData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/include/G4AblaDataFile.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/src/G4AblaDataFile.cc