ECCE @ EIC Software: G4IonStoppingData Class Reference
G4IonStoppingData Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4IonStoppingData.hh>
Public Member Functions
G4IonStoppingData (const G4String &dir, G4bool icru)
virtual ~G4IonStoppingData ()
G4bool IsApplicable (G4int atomicNumberIon, G4int atomicNumberElem)
G4bool IsApplicable (G4int atomicNumberIon, const G4String &matIdentifier)
G4bool BuildPhysicsVector (G4int ionZ, const G4String &matName)
G4bool BuildPhysicsVector (G4int ionZ, G4int matZ)
G4PhysicsVector * GetPhysicsVector (G4int atomicNumberIon, G4int atomicNumberElem)
G4PhysicsVector * GetPhysicsVector (G4int atomicNumberIon, const G4String &matIdenfier)
G4double GetDEDX (G4double kinEnergyPerNucleon, G4int atomicNumberIon, G4int atomicNumberElem)
G4double GetDEDX (G4double kinEnergyPerNucleon, G4int atomicNumberIon, const G4String &matIdentifier)
G4bool AddPhysicsVector (G4PhysicsVector *physicsVector, G4int atomicNumberIon, const G4String &matIdentifier)
G4bool AddPhysicsVector (G4PhysicsVector *physicsVector, G4int atomicNumberIon, G4int atomicNumberElem)
G4bool RemovePhysicsVector (G4int atomicNumberIon, const G4String &matIdentifier)
G4bool RemovePhysicsVector (G4int atomicNumberIon, G4int atomicNumberElem)
void ClearTable ()
void DumpMap ()
Public Member Functions inherited from G4VIonDEDXTable
G4VIonDEDXTable ()
virtual ~G4VIonDEDXTable ()
Private Types
typedef std::pair< G4int, G4int > G4IonDEDXKeyElem
typedef std::pair< G4int,
G4String > G4IonDEDXKeyMat
typedef std::map
< G4IonDEDXKeyElem,
G4PhysicsVector * > G4IonDEDXMapElem
typedef std::map
< G4IonDEDXKeyMat,
G4PhysicsVector * > G4IonDEDXMapMat
Private Member Functions
G4IonStoppingData (G4IonStoppingData &)=delete
const G4IonStoppingData & operator= (const G4IonStoppingData &)=delete
Private Attributes
G4String subDir
G4IonDEDXMapElem dedxMapElements
G4IonDEDXMapMat dedxMapMaterials
G4bool fICRU90
Detailed Description
Definition at line 59 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 59 of file G4IonStoppingData.hh
Member Typedef Documentation
typedef std::pair<G4int, G4int> G4IonStoppingData::G4IonDEDXKeyElem private
Definition at line 161 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 161 of file G4IonStoppingData.hh
typedef std::pair<G4int, G4String> G4IonStoppingData::G4IonDEDXKeyMat private
Definition at line 162 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 162 of file G4IonStoppingData.hh
typedef std::map<G4IonDEDXKeyElem, G4PhysicsVector*> G4IonStoppingData::G4IonDEDXMapElem private
Definition at line 164 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 164 of file G4IonStoppingData.hh
typedef std::map<G4IonDEDXKeyMat, G4PhysicsVector*> G4IonStoppingData::G4IonDEDXMapMat private
Definition at line 165 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 165 of file G4IonStoppingData.hh
Constructor & Destructor Documentation
G4IonStoppingData::G4IonStoppingData (const G4String & dir, G4bool icru)
Definition at line 63 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 63 of file G4IonStoppingData.cc
G4IonStoppingData::~G4IonStoppingData () virtual
Definition at line 69 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 69 of file G4IonStoppingData.cc
References ClearTable().
G4IonStoppingData::G4IonStoppingData (G4IonStoppingData &) private delete
Member Function Documentation
G4bool G4IonStoppingData::AddPhysicsVector (G4PhysicsVector * physicsVector, G4int atomicNumberIon, const G4String & matIdentifier)
Definition at line 163 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 163 of file G4IonStoppingData.cc
References dedxMapMaterials, FatalException, and G4Exception().
Referenced by BuildPhysicsVector().
G4bool G4IonStoppingData::AddPhysicsVector (G4PhysicsVector * physicsVector, G4int atomicNumberIon, G4int atomicNumberElem)
Definition at line 207 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 207 of file G4IonStoppingData.cc
References dedxMapElements, FatalException, and G4Exception().
G4bool G4IonStoppingData::BuildPhysicsVector (G4int ionZ, const G4String & matName) virtual
Implements G4VIonDEDXTable.
Definition at line 305 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 305 of file G4IonStoppingData.cc
References AddPhysicsVector(), cm2, FatalException, fICRU90, file, Acts::UnitConstants::g, G4Exception(), IsApplicable(), MeV, and subDir.
G4bool G4IonStoppingData::BuildPhysicsVector (G4int ionZ, G4int matZ) virtual
Implements G4VIonDEDXTable.
Definition at line 357 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 357 of file G4IonStoppingData.cc
References AddPhysicsVector(), cm2, FatalException, fICRU90, file, Acts::UnitConstants::g, G4Exception(), IsApplicable(), MeV, and subDir.
void G4IonStoppingData::ClearTable ()
Definition at line 406 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 406 of file G4IonStoppingData.cc
References dedxMapElements, dedxMapMaterials, and second.
Referenced by ~G4IonStoppingData().
void G4IonStoppingData::DumpMap ()
Definition at line 435 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 435 of file G4IonStoppingData.cc
References dedxMapElements, dedxMapMaterials, G4cout, G4endl, right, and second.
G4double G4IonStoppingData::GetDEDX (G4double kinEnergyPerNucleon, G4int atomicNumberIon, G4int atomicNumberElem)
Definition at line 131 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 131 of file G4IonStoppingData.cc
References dedxMapElements.
G4double G4IonStoppingData::GetDEDX (G4double kinEnergyPerNucleon, G4int atomicNumberIon, const G4String & matIdentifier)
Definition at line 147 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 147 of file G4IonStoppingData.cc
References dedxMapMaterials.
G4PhysicsVector * G4IonStoppingData::GetPhysicsVector (G4int atomicNumberIon, G4int atomicNumberElem) virtual
Implements G4VIonDEDXTable.
Definition at line 103 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 103 of file G4IonStoppingData.cc
References dedxMapElements.
G4PhysicsVector * G4IonStoppingData::GetPhysicsVector (G4int atomicNumberIon, const G4String & matIdenfier) virtual
Implements G4VIonDEDXTable.
Definition at line 117 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 117 of file G4IonStoppingData.cc
References dedxMapMaterials.
G4bool G4IonStoppingData::IsApplicable (G4int atomicNumberIon, G4int atomicNumberElem) virtual
Implements G4VIonDEDXTable.
Definition at line 75 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 75 of file G4IonStoppingData.cc
References dedxMapElements.
Referenced by BuildPhysicsVector().
G4bool G4IonStoppingData::IsApplicable (G4int atomicNumberIon, const G4String & matIdentifier) virtual
Implements G4VIonDEDXTable.
Definition at line 89 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 89 of file G4IonStoppingData.cc
References dedxMapMaterials.
const G4IonStoppingData& G4IonStoppingData::operator= (const G4IonStoppingData &) private delete
G4bool G4IonStoppingData::RemovePhysicsVector (G4int atomicNumberIon, const G4String & matIdentifier)
Definition at line 250 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 250 of file G4IonStoppingData.cc
References dedxMapMaterials, FatalException, and G4Exception().
G4bool G4IonStoppingData::RemovePhysicsVector (G4int atomicNumberIon, G4int atomicNumberElem)
Definition at line 278 of file G4IonStoppingData.cc.
View newest version in sPHENIX GitHub at line 278 of file G4IonStoppingData.cc
References dedxMapElements, FatalException, and G4Exception().
Member Data Documentation
G4IonDEDXMapElem G4IonStoppingData::dedxMapElements private
Definition at line 167 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 167 of file G4IonStoppingData.hh
Referenced by AddPhysicsVector(), ClearTable(), DumpMap(), GetDEDX(), GetPhysicsVector(), IsApplicable(), and RemovePhysicsVector().
G4IonDEDXMapMat G4IonStoppingData::dedxMapMaterials private
Definition at line 168 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 168 of file G4IonStoppingData.hh
Referenced by AddPhysicsVector(), ClearTable(), DumpMap(), GetDEDX(), GetPhysicsVector(), IsApplicable(), and RemovePhysicsVector().
G4bool G4IonStoppingData::fICRU90 private
Definition at line 170 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 170 of file G4IonStoppingData.hh
Referenced by BuildPhysicsVector().
G4String G4IonStoppingData::subDir private
Definition at line 159 of file G4IonStoppingData.hh.
View newest version in sPHENIX GitHub at line 159 of file G4IonStoppingData.hh
Referenced by BuildPhysicsVector().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4IonStoppingData.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4IonStoppingData.cc