ECCE @ EIC Software: G4QGSDiffractiveExcitation Class Reference
G4QGSDiffractiveExcitation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4QGSDiffractiveExcitation.hh>
Public Member Functions
G4QGSDiffractiveExcitation ()
virtual ~G4QGSDiffractiveExcitation ()
virtual G4bool ExciteParticipants (G4VSplitableHadron *aPartner, G4VSplitableHadron *bPartner, G4bool ProjectileDiffraction=TRUE) const
virtual G4ExcitedString * String (G4VSplitableHadron *aHadron, G4bool isProjectile) const
Private Member Functions
G4QGSDiffractiveExcitation (const G4QGSDiffractiveExcitation &right)
G4double ChooseP (G4double Pmin, G4double Pmax) const
G4ThreeVector GaussianPt (G4double AveragePt2, G4double maxPtSquare) const
const G4QGSDiffractiveExcitation & operator= (const G4QGSDiffractiveExcitation &right)
G4bool operator== (const G4QGSDiffractiveExcitation &right) const
G4bool operator!= (const G4QGSDiffractiveExcitation &right) const
Detailed Description
Definition at line 50 of file G4QGSDiffractiveExcitation.hh.
View newest version in sPHENIX GitHub at line 50 of file G4QGSDiffractiveExcitation.hh
Constructor & Destructor Documentation
G4QGSDiffractiveExcitation::G4QGSDiffractiveExcitation ()
Definition at line 68 of file G4QGSDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 68 of file G4QGSDiffractiveExcitation.cc
G4QGSDiffractiveExcitation::~G4QGSDiffractiveExcitation () virtual
Definition at line 72 of file G4QGSDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 72 of file G4QGSDiffractiveExcitation.cc
G4QGSDiffractiveExcitation::G4QGSDiffractiveExcitation (const G4QGSDiffractiveExcitation & right) private
Member Function Documentation
G4double G4QGSDiffractiveExcitation::ChooseP (G4double Pmin, G4double Pmax) const private
Definition at line 362 of file G4QGSDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 362 of file G4QGSDiffractiveExcitation.cc
References G4cout, G4endl, G4UniformRand, G4Pow::GetInstance(), P, and G4Pow::powA().
Referenced by ExciteParticipants().
G4bool G4QGSDiffractiveExcitation::ExciteParticipants (G4VSplitableHadron * aPartner, G4VSplitableHadron * bPartner, G4bool ProjectileDiffraction = TRUE) const virtual
Reimplemented in G4SingleDiffractiveExcitation.
Definition at line 78 of file G4QGSDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 78 of file G4QGSDiffractiveExcitation.cc
References kdfinder::abs(), CLHEP::HepLorentzVector::boostVector(), ChooseP(), G4cout, G4endl, GaussianPt(), G4VSplitableHadron::Get4Momentum(), G4VSplitableHadron::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGMass(), GeV, CLHEP::HepLorentzVector::mag(), CLHEP::HepLorentzVector::mag2(), MeV, CLHEP::HepLorentzVector::rotateY(), CLHEP::HepLorentzVector::rotateZ(), S(), G4VSplitableHadron::Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), sqr(), CLHEP::HepLorentzRotation::transform(), CLHEP::HepLorentzVector::transform(), and CLHEP::HepLorentzVector::vect().
Referenced by G4QGSParticipants::PerformDiffractiveCollisions().
G4ThreeVector G4QGSDiffractiveExcitation::GaussianPt (G4double AveragePt2, G4double maxPtSquare) const private
Definition at line 382 of file G4QGSDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 382 of file G4QGSDiffractiveExcitation.cc
References G4Exp(), G4Log(), G4UniformRand, phi, and twopi.
Referenced by ExciteParticipants(), and String().
G4bool G4QGSDiffractiveExcitation::operator!= (const G4QGSDiffractiveExcitation & right) const private
const G4QGSDiffractiveExcitation& G4QGSDiffractiveExcitation::operator= (const G4QGSDiffractiveExcitation & right) private
G4bool G4QGSDiffractiveExcitation::operator== (const G4QGSDiffractiveExcitation & right) const private
G4ExcitedString * G4QGSDiffractiveExcitation::String (G4VSplitableHadron * aHadron, G4bool isProjectile) const virtual
Definition at line 288 of file G4QGSDiffractiveExcitation.cc.
View newest version in sPHENIX GitHub at line 288 of file G4QGSDiffractiveExcitation.cc
References G4cout, G4endl, GaussianPt(), G4VSplitableHadron::Get4Momentum(), G4Parton::Get4Momentum(), G4VSplitableHadron::GetNextParton(), G4Parton::GetPDGcode(), G4VSplitableHadron::GetPosition(), GeV, CLHEP::HepLorentzVector::mag(), max, CLHEP::HepLorentzVector::minus(), CLHEP::HepLorentzVector::perp2(), CLHEP::HepLorentzVector::plus(), pt, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), G4Parton::Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), G4VSplitableHadron::SplitUp(), sqr(), start(), CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/include/G4QGSDiffractiveExcitation.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/qgsm/src/G4QGSDiffractiveExcitation.cc