ECCE @ EIC Software: G4ParticlesWorkspace Class Reference
G4ParticlesWorkspace Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticlesWorkspace.hh>
Public Types
typedef G4TWorkspacePool
< G4ParticlesWorkspace > pool_type
Public Member Functions
G4ParticlesWorkspace (G4bool verbose=false)
~G4ParticlesWorkspace ()
void UseWorkspace ()
void ReleaseWorkspace ()
void DestroyWorkspace ()
void InitialiseWorkspace ()
void SetVerbose (G4bool v)
G4bool GetVerbose ()
Static Public Member Functions
static pool_type * GetPool ()
Protected Member Functions
void InitialiseParticles ()
Private Attributes
G4PDefManager * fpPDefSIM
G4PDefData * fpPDefOffset
G4bool fVerbose
Detailed Description
Definition at line 54 of file G4ParticlesWorkspace.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticlesWorkspace.hh
Member Typedef Documentation
typedef G4TWorkspacePool<G4ParticlesWorkspace> G4ParticlesWorkspace::pool_type
Definition at line 58 of file G4ParticlesWorkspace.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ParticlesWorkspace.hh
Constructor & Destructor Documentation
G4ParticlesWorkspace::G4ParticlesWorkspace (G4bool verbose = false)
Definition at line 36 of file G4ParticlesWorkspace.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ParticlesWorkspace.cc
References fpPDefOffset, fpPDefSIM, G4PDefManager::GetOffset(), G4ParticleDefinition::GetSubInstanceManager(), and InitialiseWorkspace().
G4ParticlesWorkspace::~G4ParticlesWorkspace ()
Definition at line 49 of file G4ParticlesWorkspace.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ParticlesWorkspace.cc
Member Function Documentation
void G4ParticlesWorkspace::DestroyWorkspace ()
Definition at line 96 of file G4ParticlesWorkspace.cc.
View newest version in sPHENIX GitHub at line 96 of file G4ParticlesWorkspace.cc
References fpPDefSIM, and G4PDefManager::FreeSlave().
G4ParticlesWorkspace::pool_type * G4ParticlesWorkspace::GetPool () static
Definition at line 34 of file G4ParticlesWorkspace.cc.
View newest version in sPHENIX GitHub at line 34 of file G4ParticlesWorkspace.cc
Referenced by G4WorkerThread::BuildGeometryAndPhysicsVector(), and G4WorkerThread::DestroyGeometryAndPhysicsVector().
G4bool G4ParticlesWorkspace::GetVerbose () inline
Definition at line 70 of file G4ParticlesWorkspace.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParticlesWorkspace.hh
References fVerbose.
void G4ParticlesWorkspace::InitialiseParticles () protected
Definition at line 72 of file G4ParticlesWorkspace.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ParticlesWorkspace.cc
Referenced by InitialiseWorkspace().
void G4ParticlesWorkspace::InitialiseWorkspace ()
Definition at line 77 of file G4ParticlesWorkspace.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticlesWorkspace.cc
References fpPDefSIM, fVerbose, G4cout, G4endl, InitialiseParticles(), and G4PDefManager::NewSubInstances().
Referenced by G4ParticlesWorkspace().
void G4ParticlesWorkspace::ReleaseWorkspace ()
Definition at line 67 of file G4ParticlesWorkspace.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ParticlesWorkspace.cc
References fpPDefSIM, and G4PDefManager::UseWorkArea().
void G4ParticlesWorkspace::SetVerbose (G4bool v) inline
Definition at line 69 of file G4ParticlesWorkspace.hh.
View newest version in sPHENIX GitHub at line 69 of file G4ParticlesWorkspace.hh
References fVerbose, and v.
void G4ParticlesWorkspace::UseWorkspace ()
Definition at line 54 of file G4ParticlesWorkspace.cc.
View newest version in sPHENIX GitHub at line 54 of file G4ParticlesWorkspace.cc
References fpPDefOffset, fpPDefSIM, fVerbose, G4cout, G4endl, and G4PDefManager::UseWorkArea().
Member Data Documentation
G4PDefData* G4ParticlesWorkspace::fpPDefOffset private
Definition at line 87 of file G4ParticlesWorkspace.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticlesWorkspace.hh
Referenced by G4ParticlesWorkspace(), and UseWorkspace().
G4PDefManager* G4ParticlesWorkspace::fpPDefSIM private
Definition at line 81 of file G4ParticlesWorkspace.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ParticlesWorkspace.hh
Referenced by DestroyWorkspace(), G4ParticlesWorkspace(), InitialiseWorkspace(), ReleaseWorkspace(), and UseWorkspace().
G4bool G4ParticlesWorkspace::fVerbose private
Definition at line 88 of file G4ParticlesWorkspace.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticlesWorkspace.hh
Referenced by GetVerbose(), InitialiseWorkspace(), SetVerbose(), and UseWorkspace().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4ParticlesWorkspace.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4ParticlesWorkspace.cc