ECCE @ EIC Software: G4ParticleHPPhotonDist Class Reference
G4ParticleHPPhotonDist Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPPhotonDist.hh>
Public Member Functions
G4ParticleHPPhotonDist ()
~G4ParticleHPPhotonDist ()
G4bool InitMean (std::istream &aDataFile)
void InitAngular (std::istream &aDataFile)
void InitEnergies (std::istream &aDataFile)
void InitPartials (std::istream &aDataFile, G4ParticleHPVector *theXsec=0)
G4ReactionProductVector * GetPhotons (G4double anEnergy)
G4double GetTargetMass ()
G4bool NeedsCascade ()
G4double GetLevelEnergy ()
Private Attributes
G4int repFlag
G4double targetMass
G4int nDiscrete
G4int * disType
G4double * energy
G4ParticleHPVector * theYield
G4ParticleHPVector theTotalXsec
G4ParticleHPVector * thePartialXsec
G4ParticleHPVector * theReactionXsec
G4int * isPrimary
G4int isoFlag
G4int tabulationType
G4int nDiscrete2
G4int nIso
G4double * theShells
G4double * theGammas
G4int * nNeu
G4InterpolationManager theLegendreManager
G4ParticleHPLegendreTable ** theLegendre
G4ParticleHPAngularP ** theAngular
G4int * distribution
G4int nPartials
G4ParticleHPVector * probs
G4ParticleHPPartial ** partials
G4Cache< std::vector< G4int > * > actualMult
G4int theInternalConversionFlag
G4int nGammaEnergies
G4double theBaseEnergy
G4double * theLevelEnergies
G4double * theTransitionProbabilities
G4double * thePhotonTransitionFraction
G4ParticleHPFastLegendre theLegend
G4ParticleHPInterpolator theInt
Detailed Description
Definition at line 57 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ParticleHPPhotonDist.hh
Constructor & Destructor Documentation
G4ParticleHPPhotonDist::G4ParticleHPPhotonDist () inline
Definition at line 61 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPPhotonDist.hh
References actualMult, distribution, disType, energy, isPrimary, nNeu, partials, probs, G4Cache< VALTYPE >::Put(), theAngular, theGammas, theLegendre, theLevelEnergies, thePartialXsec, thePhotonTransitionFraction, theReactionXsec, theShells, theTransitionProbabilities, and theYield.
G4ParticleHPPhotonDist::~G4ParticleHPPhotonDist () inline
Definition at line 97 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPPhotonDist.hh
References actualMult, distribution, disType, energy, G4Cache< VALTYPE >::Get(), isPrimary, nDiscrete2, nIso, nNeu, nPartials, partials, probs, theAngular, theGammas, theLegendre, theLevelEnergies, thePartialXsec, thePhotonTransitionFraction, theShells, theTransitionProbabilities, and theYield.
Member Function Documentation
G4double G4ParticleHPPhotonDist::GetLevelEnergy () inline
Definition at line 149 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ParticleHPPhotonDist.hh
References theBaseEnergy.
Referenced by G4ParticleHPInelasticCompFS::CompositeApply().
G4ReactionProductVector * G4ParticleHPPhotonDist::GetPhotons (G4double anEnergy)
Definition at line 285 of file G4ParticleHPPhotonDist.cc.
View newest version in sPHENIX GitHub at line 285 of file G4ParticleHPPhotonDist.cc
References kdfinder::abs(), actualMult, DBL_MAX, disType, G4Electron::Electron(), energy, G4Poisson(), G4UniformRand, G4Gamma::Gamma(), G4Cache< VALTYPE >::Get(), G4ParticleHPAngularP::GetCosTh(), G4ParticleDefinition::GetPDGMass(), G4ReactionProduct::GetTotalEnergy(), G4ReactionProduct::GetTotalMomentum(), G4ParticleHPVector::GetVectorLength(), G4ParticleHPVector::GetX(), G4ParticleHPVector::GetXsec(), G4ParticleHPPartial::GetY(), G4ParticleHPVector::GetY(), isoFlag, it, keV, nDiscrete, nDiscrete2, nGammaEnergies, nIso, nNeu, nPartials, partials, phi, probs, repFlag, G4ParticleHPVector::Sample(), G4ParticleHPLegendreStore::SampleMax(), G4ParticleHPLegendreStore::SetCoeff(), G4ReactionProduct::SetDefinition(), G4ReactionProduct::SetMomentum(), G4ReactionProduct::SetTotalEnergy(), sum, tabulationType, theAngular, theBaseEnergy, theGammas, theInternalConversionFlag, theLegendre, theLevelEnergies, thePartialXsec, thePhotonTransitionFraction, theReactionXsec, theta(), theTransitionProbabilities, theYield, twopi, x, and y.
Referenced by G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4ParticleHPInelasticCompFS::CompositeApply(), and G4ParticleHPFSFissionFS::GetPhotons().
G4double G4ParticleHPPhotonDist::GetTargetMass () inline
Definition at line 145 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ParticleHPPhotonDist.hh
References targetMass.
Referenced by G4ParticleHPCaptureFS::Init().
void G4ParticleHPPhotonDist::InitAngular (std::istream & aDataFile)
Definition at line 122 of file G4ParticleHPPhotonDist.cc.
View newest version in sPHENIX GitHub at line 122 of file G4ParticleHPPhotonDist.cc
References disType, eV, G4cout, G4endl, G4ParticleHPAngularP::Init(), G4ParticleHPLegendreTable::Init(), G4InterpolationManager::Init(), isoFlag, isPrimary, it, nDiscrete, nDiscrete2, nIso, nNeu, repFlag, tabulationType, theAngular, theGammas, theLegendre, theLegendreManager, thePartialXsec, and theShells.
Referenced by G4ParticleHPCaptureFS::Init(), G4ParticleHPFSFissionFS::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), and G4FissionLibrary::Init().
void G4ParticleHPPhotonDist::InitEnergies (std::istream & aDataFile)
Definition at line 230 of file G4ParticleHPPhotonDist.cc.
View newest version in sPHENIX GitHub at line 230 of file G4ParticleHPPhotonDist.cc
References distribution, disType, eV, G4ParticleHPPartial::Init(), G4ParticleHPVector::Init(), G4ParticleHPPartial::InitInterpolation(), nDiscrete, nPartials, partials, and probs.
Referenced by G4ParticleHPCaptureFS::Init(), G4ParticleHPFSFissionFS::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), and G4FissionLibrary::Init().
G4bool G4ParticleHPPhotonDist::InitMean (std::istream & aDataFile)
Definition at line 55 of file G4ParticleHPPhotonDist.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPPhotonDist.cc
References disType, energy, eV, G4cout, G4endl, G4ParticleHPVector::Init(), nDiscrete, nGammaEnergies, repFlag, targetMass, theBaseEnergy, theInternalConversionFlag, theLevelEnergies, thePhotonTransitionFraction, theTransitionProbabilities, and theYield.
Referenced by G4ParticleHPCaptureFS::Init(), G4ParticleHPFSFissionFS::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), and G4FissionLibrary::Init().
void G4ParticleHPPhotonDist::InitPartials (std::istream & aDataFile, G4ParticleHPVector * theXsec = 0)
Definition at line 255 of file G4ParticleHPPhotonDist.cc.
View newest version in sPHENIX GitHub at line 255 of file G4ParticleHPPhotonDist.cc
References disType, eV, G4ParticleHPVector::Init(), isPrimary, nDiscrete, targetMass, theGammas, thePartialXsec, theReactionXsec, theShells, and theTotalXsec.
Referenced by G4ParticleHPInelasticBaseFS::Init(), and G4ParticleHPInelasticCompFS::Init().
G4bool G4ParticleHPPhotonDist::NeedsCascade () inline
Definition at line 147 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ParticleHPPhotonDist.hh
References repFlag.
Member Data Documentation
G4Cache< std::vector<G4int>* > G4ParticleHPPhotonDist::actualMult private
Definition at line 181 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 181 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), and ~G4ParticleHPPhotonDist().
G4int* G4ParticleHPPhotonDist::distribution private
Definition at line 176 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 176 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), InitEnergies(), and ~G4ParticleHPPhotonDist().
G4int* G4ParticleHPPhotonDist::disType private
Definition at line 157 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitAngular(), InitEnergies(), InitMean(), InitPartials(), and ~G4ParticleHPPhotonDist().
G4double* G4ParticleHPPhotonDist::energy private
Definition at line 158 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 158 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitMean(), and ~G4ParticleHPPhotonDist().
G4int G4ParticleHPPhotonDist::isoFlag private
Definition at line 165 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 165 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), and InitAngular().
G4int* G4ParticleHPPhotonDist::isPrimary private
Definition at line 163 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 163 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), InitAngular(), InitPartials(), and ~G4ParticleHPPhotonDist().
G4int G4ParticleHPPhotonDist::nDiscrete private
Definition at line 156 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), InitAngular(), InitEnergies(), InitMean(), and InitPartials().
G4int G4ParticleHPPhotonDist::nDiscrete2 private
Definition at line 167 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), InitAngular(), and ~G4ParticleHPPhotonDist().
G4int G4ParticleHPPhotonDist::nGammaEnergies private
Definition at line 185 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 185 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), and InitMean().
G4int G4ParticleHPPhotonDist::nIso private
Definition at line 168 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), InitAngular(), and ~G4ParticleHPPhotonDist().
G4int* G4ParticleHPPhotonDist::nNeu private
Definition at line 171 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 171 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitAngular(), and ~G4ParticleHPPhotonDist().
G4int G4ParticleHPPhotonDist::nPartials private
Definition at line 177 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 177 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), InitEnergies(), and ~G4ParticleHPPhotonDist().
G4ParticleHPPartial** G4ParticleHPPhotonDist::partials private
Definition at line 179 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 179 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitEnergies(), and ~G4ParticleHPPhotonDist().
G4ParticleHPVector* G4ParticleHPPhotonDist::probs private
Definition at line 178 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 178 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitEnergies(), and ~G4ParticleHPPhotonDist().
G4int G4ParticleHPPhotonDist::repFlag private
Definition at line 153 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), InitAngular(), InitMean(), and NeedsCascade().
G4int G4ParticleHPPhotonDist::tabulationType private
Definition at line 166 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), and InitAngular().
G4double G4ParticleHPPhotonDist::targetMass private
Definition at line 154 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParticleHPPhotonDist.hh
Referenced by GetTargetMass(), InitMean(), and InitPartials().
G4ParticleHPAngularP** G4ParticleHPPhotonDist::theAngular private
Definition at line 174 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitAngular(), and ~G4ParticleHPPhotonDist().
G4double G4ParticleHPPhotonDist::theBaseEnergy private
Definition at line 186 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 186 of file G4ParticleHPPhotonDist.hh
Referenced by GetLevelEnergy(), GetPhotons(), and InitMean().
G4double* G4ParticleHPPhotonDist::theGammas private
Definition at line 170 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 170 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitAngular(), InitPartials(), and ~G4ParticleHPPhotonDist().
G4ParticleHPInterpolator G4ParticleHPPhotonDist::theInt private
Definition at line 193 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 193 of file G4ParticleHPPhotonDist.hh
G4int G4ParticleHPPhotonDist::theInternalConversionFlag private
Definition at line 184 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 184 of file G4ParticleHPPhotonDist.hh
Referenced by GetPhotons(), and InitMean().
G4ParticleHPFastLegendre G4ParticleHPPhotonDist::theLegend private
Definition at line 192 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 192 of file G4ParticleHPPhotonDist.hh
G4ParticleHPLegendreTable** G4ParticleHPPhotonDist::theLegendre private
Definition at line 173 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitAngular(), and ~G4ParticleHPPhotonDist().
G4InterpolationManager G4ParticleHPPhotonDist::theLegendreManager private
Definition at line 172 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ParticleHPPhotonDist.hh
Referenced by InitAngular().
G4double* G4ParticleHPPhotonDist::theLevelEnergies private
Definition at line 187 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 187 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitMean(), and ~G4ParticleHPPhotonDist().
G4ParticleHPVector* G4ParticleHPPhotonDist::thePartialXsec private
Definition at line 161 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 161 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitAngular(), InitPartials(), and ~G4ParticleHPPhotonDist().
G4double* G4ParticleHPPhotonDist::thePhotonTransitionFraction private
Definition at line 189 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 189 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitMean(), and ~G4ParticleHPPhotonDist().
G4ParticleHPVector* G4ParticleHPPhotonDist::theReactionXsec private
Definition at line 162 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 162 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), and InitPartials().
G4double* G4ParticleHPPhotonDist::theShells private
Definition at line 169 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 169 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), InitAngular(), InitPartials(), and ~G4ParticleHPPhotonDist().
G4ParticleHPVector G4ParticleHPPhotonDist::theTotalXsec private
Definition at line 160 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 160 of file G4ParticleHPPhotonDist.hh
Referenced by InitPartials().
G4double* G4ParticleHPPhotonDist::theTransitionProbabilities private
Definition at line 188 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 188 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitMean(), and ~G4ParticleHPPhotonDist().
G4ParticleHPVector* G4ParticleHPPhotonDist::theYield private
Definition at line 159 of file G4ParticleHPPhotonDist.hh.
View newest version in sPHENIX GitHub at line 159 of file G4ParticleHPPhotonDist.hh
Referenced by G4ParticleHPPhotonDist(), GetPhotons(), InitMean(), and ~G4ParticleHPPhotonDist().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPPhotonDist.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPPhotonDist.cc