ECCE @ EIC Software: G4RDRangeTest Class Reference
G4RDRangeTest Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDRangeTest.hh>
Public Member Functions
G4RDRangeTest ()
virtual ~G4RDRangeTest ()
virtual G4bool Escape (const G4ParticleDefinition *particle, const G4MaterialCutsCouple *couple, G4double energy, G4double safety) const
Public Member Functions inherited from G4RDVRangeTest
G4RDVRangeTest ()
virtual ~G4RDVRangeTest ()
Detailed Description
Definition at line 52 of file G4RDRangeTest.hh.
View newest version in sPHENIX GitHub at line 52 of file G4RDRangeTest.hh
Constructor & Destructor Documentation
G4RDRangeTest::G4RDRangeTest () inline
Definition at line 56 of file G4RDRangeTest.hh.
View newest version in sPHENIX GitHub at line 56 of file G4RDRangeTest.hh
G4RDRangeTest::~G4RDRangeTest () virtual
Definition at line 44 of file G4RDRangeTest.cc.
View newest version in sPHENIX GitHub at line 44 of file G4RDRangeTest.cc
Member Function Documentation
G4bool G4RDRangeTest::Escape (const G4ParticleDefinition * particle, const G4MaterialCutsCouple * couple, G4double energy, G4double safety) const virtual
Implements G4RDVRangeTest.
Definition at line 47 of file G4RDRangeTest.cc.
View newest version in sPHENIX GitHub at line 47 of file G4RDRangeTest.cc
References G4Electron::Electron(), G4ProductionCuts::GetProductionCut(), G4MaterialCutsCouple::GetProductionCuts(), G4EnergyLossTables::GetRange(), incremental_prev_tag::idx, min, and G4Positron::Positron().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDRangeTest.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDRangeTest.cc