ECCE @ EIC Software: G4VEMDataSet Class Reference
G4VEMDataSet Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VEMDataSet.hh>
Public Member Functions
G4VEMDataSet ()
virtual ~G4VEMDataSet ()
virtual G4double FindValue (G4double x, G4int componentId=0) const =0
virtual void PrintData (void) const =0
virtual const G4VEMDataSet * GetComponent (G4int componentId) const =0
virtual void AddComponent (G4VEMDataSet *dataSet)=0
virtual size_t NumberOfComponents (void) const =0
virtual const G4DataVector & GetEnergies (G4int componentId) const =0
virtual const G4DataVector & GetData (G4int componentId) const =0
virtual const G4DataVector & GetLogEnergies (G4int componentId) const =0
virtual const G4DataVector & GetLogData (G4int componentId) const =0
virtual void SetEnergiesData (G4DataVector *x, G4DataVector *data, G4int component=0)=0
virtual void SetLogEnergiesData (G4DataVector *x, G4DataVector *data, G4DataVector *Log_x, G4DataVector *Log_data, G4int component=0)=0
virtual G4bool LoadData (const G4String &fileName)=0
virtual G4bool LoadNonLogData (const G4String &fileName)=0
virtual G4bool SaveData (const G4String &fileName) const =0
virtual G4double RandomSelect (G4int componentId=0) const =0
Private Member Functions
G4VEMDataSet (const G4VEMDataSet &copy)
G4VEMDataSet & operator= (const G4VEMDataSet &right)
Detailed Description
Definition at line 55 of file G4VEMDataSet.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VEMDataSet.hh
Constructor & Destructor Documentation
G4VEMDataSet::G4VEMDataSet ()
Definition at line 38 of file G4VEMDataSet.cc.
View newest version in sPHENIX GitHub at line 38 of file G4VEMDataSet.cc
G4VEMDataSet::~G4VEMDataSet () virtual
Definition at line 39 of file G4VEMDataSet.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VEMDataSet.cc
G4VEMDataSet::G4VEMDataSet (const G4VEMDataSet & copy) private
Member Function Documentation
virtual void G4VEMDataSet::AddComponent (G4VEMDataSet * dataSet) pure virtual
Implemented in G4EMDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4BremsstrahlungCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), and G4DopplerProfile::LoadProfile().
virtual G4double G4VEMDataSet::FindValue (G4double x, G4int componentId = 0) const pure virtual
Implemented in G4EMDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4ShellVacancy::AverageNOfIonisations(), G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), G4eIonisationParameters::Excitation(), G4CompositeEMDataSet::FindValue(), G4VCrossSectionHandler::FindValue(), G4LivermorePolarizedRayleighModel::GenerateCosTheta(), G4DNABornExcitationModel1::GetPartialCrossSection(), G4DNABornIonisationModel2::GetPartialCrossSection(), G4DNABornIonisationModel1::GetPartialCrossSection(), G4eIonisationParameters::Parameter(), G4BremsstrahlungParameters::Parameter(), G4DNABornExcitationModel1::RandomSelect(), G4DNAEmfietzoglouExcitationModel::RandomSelect(), G4DNACPA100ExcitationModel::RandomSelect(), G4MuElecInelasticModel::RandomSelect(), G4DNABornIonisationModel2::RandomSelect(), G4DNARuddIonisationModel::RandomSelect(), G4DNARuddIonisationExtendedModel::RandomSelect(), G4DNABornIonisationModel1::RandomSelect(), G4MicroElecInelasticModel::RandomSelect(), G4DNACPA100IonisationModel::RandomSelect(), G4DNAEmfietzoglouIonisationModel::RandomSelect(), G4VDNAModel::RandomSelectShell(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4VCrossSectionHandler::SelectRandomAtom(), and G4VCrossSectionHandler::SelectRandomElement().
virtual const G4VEMDataSet* G4VEMDataSet::GetComponent (G4int componentId) const pure virtual
Implemented in G4EMDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), G4VCrossSectionHandler::FindValue(), G4eIonisationParameters::Parameter(), G4eIonisationParameters::PrintData(), G4DopplerProfile::Profile(), G4VCrossSectionHandler::SelectRandomAtom(), and G4VCrossSectionHandler::SelectRandomElement().
virtual const G4DataVector& G4VEMDataSet::GetData (G4int componentId) const pure virtual
Implemented in G4EMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4MicroElecCrossSectionDataSet::GetData(), G4MuElecCrossSectionDataSet::GetData(), G4CompositeEMDataSet::GetData(), G4ShellEMDataSet::GetData(), G4CrossSectionDataSet::GetData(), G4DNACrossSectionDataSet::GetData(), G4MicroElecCrossSectionDataSet::SaveData(), G4MuElecCrossSectionDataSet::SaveData(), G4ShellEMDataSet::SaveData(), G4CrossSectionDataSet::SaveData(), and G4DNACrossSectionDataSet::SaveData().
virtual const G4DataVector& G4VEMDataSet::GetEnergies (G4int componentId) const pure virtual
Implemented in G4EMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4eIonisationParameters::Excitation(), G4MicroElecCrossSectionDataSet::GetEnergies(), G4MuElecCrossSectionDataSet::GetEnergies(), G4CompositeEMDataSet::GetEnergies(), G4ShellEMDataSet::GetEnergies(), G4DNACrossSectionDataSet::GetEnergies(), G4CrossSectionDataSet::GetEnergies(), G4eIonisationParameters::Parameter(), G4BremsstrahlungParameters::Parameter(), and G4ShellEMDataSet::SaveData().
virtual const G4DataVector& G4VEMDataSet::GetLogData (G4int componentId) const pure virtual
Implemented in G4EMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4MicroElecCrossSectionDataSet::GetLogData(), G4MuElecCrossSectionDataSet::GetLogData(), G4CompositeEMDataSet::GetLogData(), G4ShellEMDataSet::GetLogData(), G4DNACrossSectionDataSet::GetLogData(), and G4CrossSectionDataSet::GetLogData().
virtual const G4DataVector& G4VEMDataSet::GetLogEnergies (G4int componentId) const pure virtual
Implemented in G4EMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4MicroElecCrossSectionDataSet::GetLogEnergies(), G4MuElecCrossSectionDataSet::GetLogEnergies(), G4CompositeEMDataSet::GetLogEnergies(), G4ShellEMDataSet::GetLogEnergies(), G4DNACrossSectionDataSet::GetLogEnergies(), and G4CrossSectionDataSet::GetLogEnergies().
virtual G4bool G4VEMDataSet::LoadData (const G4String & fileName) pure virtual
Implemented in G4EMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4LivermoreComptonModifiedModel::Initialise(), G4LivermorePolarizedRayleighModel::Initialise(), G4CompositeEMDataSet::LoadData(), and G4VCrossSectionHandler::LoadShellData().
virtual G4bool G4VEMDataSet::LoadNonLogData (const G4String & fileName) pure virtual
Implemented in G4EMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4CompositeEMDataSet::LoadNonLogData().
virtual size_t G4VEMDataSet::NumberOfComponents (void) const pure virtual
Implemented in G4EMDataSet, G4DNACrossSectionDataSet, G4CompositeEMDataSet, G4CrossSectionDataSet, G4ShellEMDataSet, XrayFluoDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4VCrossSectionHandler::BuildMeanFreePathForMaterials(), G4VCrossSectionHandler::FindValue(), G4VCrossSectionHandler::NumberOfComponents(), G4eIonisationParameters::Parameter(), and G4eIonisationParameters::PrintData().
G4VEMDataSet& G4VEMDataSet::operator= (const G4VEMDataSet & right) private
virtual void G4VEMDataSet::PrintData (void) const pure virtual
Implemented in G4EMDataSet, XrayFluoDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4MicroElecCrossSectionDataSet::PrintData(), G4MuElecCrossSectionDataSet::PrintData(), G4DopplerProfile::PrintData(), G4DNACrossSectionDataSet::PrintData(), G4CrossSectionDataSet::PrintData(), G4ShellEMDataSet::PrintData(), G4CompositeEMDataSet::PrintData(), G4eIonisationParameters::PrintData(), G4BremsstrahlungParameters::PrintData(), and G4VCrossSectionHandler::PrintData().
virtual G4double G4VEMDataSet::RandomSelect (G4int componentId = 0) const pure virtual
Implemented in G4EMDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, G4MuElecCrossSectionDataSet, and XrayFluoDataSet.
Referenced by G4CompositeEMDataSet::RandomSelect(), and G4DopplerProfile::RandomSelectMomentum().
virtual G4bool G4VEMDataSet::SaveData (const G4String & fileName) const pure virtual
Implemented in G4EMDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, G4MuElecCrossSectionDataSet, and XrayFluoDataSet.
Referenced by G4CompositeEMDataSet::SaveData().
virtual void G4VEMDataSet::SetEnergiesData (G4DataVector * x, G4DataVector * data, G4int component = 0) pure virtual
Implemented in G4EMDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, XrayFluoDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4MicroElecCrossSectionDataSet::SetEnergiesData(), G4MuElecCrossSectionDataSet::SetEnergiesData(), G4CompositeEMDataSet::SetEnergiesData(), G4ShellEMDataSet::SetEnergiesData(), G4DNACrossSectionDataSet::SetEnergiesData(), and G4CrossSectionDataSet::SetEnergiesData().
virtual void G4VEMDataSet::SetLogEnergiesData (G4DataVector * x, G4DataVector * data, G4DataVector * Log_x, G4DataVector * Log_data, G4int component = 0) pure virtual
Implemented in G4EMDataSet, XrayFluoDataSet, G4DNACrossSectionDataSet, G4CrossSectionDataSet, G4CompositeEMDataSet, G4ShellEMDataSet, G4MicroElecCrossSectionDataSet, and G4MuElecCrossSectionDataSet.
Referenced by G4MicroElecCrossSectionDataSet::SetLogEnergiesData(), G4MuElecCrossSectionDataSet::SetLogEnergiesData(), G4CompositeEMDataSet::SetLogEnergiesData(), G4ShellEMDataSet::SetLogEnergiesData(), G4DNACrossSectionDataSet::SetLogEnergiesData(), and G4CrossSectionDataSet::SetLogEnergiesData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VEMDataSet.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4VEMDataSet.cc