ECCE @ EIC Software: G4DiffractiveSplitableHadron Class Reference
G4DiffractiveSplitableHadron Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4DiffractiveSplitableHadron.hh>
Public Member Functions
G4DiffractiveSplitableHadron ()
G4DiffractiveSplitableHadron (const G4ReactionProduct &aPrimary)
G4DiffractiveSplitableHadron (const G4Nucleon &aNucleon)
G4DiffractiveSplitableHadron (const G4VKineticNucleon *aNucleon)
~G4DiffractiveSplitableHadron ()
void SplitUp ()
G4Parton * GetNextParton ()
G4Parton * GetNextAntiParton ()
void SetFirstParton (G4int PDGcode)
void SetSecondParton (G4int PDGcode)
Public Member Functions inherited from G4VSplitableHadron
G4VSplitableHadron ()
G4VSplitableHadron (const G4ReactionProduct &aPrimary)
G4VSplitableHadron (const G4Nucleon &aNucleon)
G4VSplitableHadron (const G4VKineticNucleon *aNucleon)
virtual ~G4VSplitableHadron ()
G4bool operator== (const G4VSplitableHadron &right) const
G4bool operator!= (const G4VSplitableHadron &right) const
void Set4Momentum (const G4LorentzVector &a4Momentum)
const G4LorentzVector & Get4Momentum () const
void SetDefinition (const G4ParticleDefinition *aDefinition)
const G4ParticleDefinition * GetDefinition () const
void IncrementCollisionCount (G4int aCount)
void SetCollisionCount (G4int aCount)
void SetTimeOfCreation (G4double aTime)
G4double GetTimeOfCreation ()
void SetPosition (const G4ThreeVector &aPosition)
const G4ThreeVector & GetPosition () const
void SetStatus (const G4int aStatus)
G4int GetStatus ()
G4bool IsSplit ()
G4int GetSoftCollisionCount ()
Private Member Functions
G4DiffractiveSplitableHadron (const G4DiffractiveSplitableHadron &)
G4DiffractiveSplitableHadron & operator= (const G4DiffractiveSplitableHadron &)
G4bool operator== (const G4DiffractiveSplitableHadron &right) const
G4bool operator!= (const G4DiffractiveSplitableHadron &right) const
G4int Diquark (G4int aquark, G4int bquark, G4int Spin) const
void ChooseStringEnds (G4int PDGcode, G4int *aEnd, G4int *bEnd) const
Private Attributes
G4Parton * Parton [2]
G4int PartonIndex
Additional Inherited Members
Protected Member Functions inherited from G4VSplitableHadron
void Splitting ()
Detailed Description
Definition at line 45 of file G4DiffractiveSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 45 of file G4DiffractiveSplitableHadron.hh
Constructor & Destructor Documentation
G4DiffractiveSplitableHadron::G4DiffractiveSplitableHadron ()
Definition at line 45 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 45 of file G4DiffractiveSplitableHadron.cc
References Parton, PartonIndex, G4Parton::Set4Momentum(), and tmp.
G4DiffractiveSplitableHadron::G4DiffractiveSplitableHadron (const G4ReactionProduct & aPrimary)
Definition at line 58 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 58 of file G4DiffractiveSplitableHadron.cc
References Parton, and PartonIndex.
G4DiffractiveSplitableHadron::G4DiffractiveSplitableHadron (const G4Nucleon & aNucleon)
Definition at line 68 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 68 of file G4DiffractiveSplitableHadron.cc
References Parton, and PartonIndex.
G4DiffractiveSplitableHadron::G4DiffractiveSplitableHadron (const G4VKineticNucleon * aNucleon)
Definition at line 78 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 78 of file G4DiffractiveSplitableHadron.cc
References Parton, and PartonIndex.
G4DiffractiveSplitableHadron::~G4DiffractiveSplitableHadron ()
Definition at line 88 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 88 of file G4DiffractiveSplitableHadron.cc
G4DiffractiveSplitableHadron::G4DiffractiveSplitableHadron (const G4DiffractiveSplitableHadron &) private
Member Function Documentation
void G4DiffractiveSplitableHadron::ChooseStringEnds (G4int PDGcode, G4int * aEnd, G4int * bEnd) const private
Definition at line 169 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 169 of file G4DiffractiveSplitableHadron.cc
References kdfinder::abs(), Diquark(), G4UniformRand, and max.
Referenced by SplitUp().
G4int G4DiffractiveSplitableHadron::Diquark (G4int aquark, G4int bquark, G4int Spin) const private
Definition at line 253 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 253 of file G4DiffractiveSplitableHadron.cc
References kdfinder::abs(), max, and min.
Referenced by ChooseStringEnds().
G4Parton * G4DiffractiveSplitableHadron::GetNextAntiParton () virtual
Implements G4VSplitableHadron.
Definition at line 138 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 138 of file G4DiffractiveSplitableHadron.cc
References Parton, and PartonIndex.
G4Parton * G4DiffractiveSplitableHadron::GetNextParton () virtual
Implements G4VSplitableHadron.
Definition at line 127 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 127 of file G4DiffractiveSplitableHadron.cc
References Parton, and PartonIndex.
G4bool G4DiffractiveSplitableHadron::operator!= (const G4DiffractiveSplitableHadron & right) const private
G4DiffractiveSplitableHadron& G4DiffractiveSplitableHadron::operator= (const G4DiffractiveSplitableHadron &) private
G4bool G4DiffractiveSplitableHadron::operator== (const G4DiffractiveSplitableHadron & right) const private
void G4DiffractiveSplitableHadron::SetFirstParton (G4int PDGcode) virtual
Implements G4VSplitableHadron.
Definition at line 149 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 149 of file G4DiffractiveSplitableHadron.cc
References Parton, G4Parton::Set4Momentum(), and tmp.
void G4DiffractiveSplitableHadron::SetSecondParton (G4int PDGcode) virtual
Implements G4VSplitableHadron.
Definition at line 159 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 159 of file G4DiffractiveSplitableHadron.cc
References Parton, G4Parton::Set4Momentum(), and tmp.
void G4DiffractiveSplitableHadron::SplitUp () virtual
Implements G4VSplitableHadron.
Definition at line 93 of file G4DiffractiveSplitableHadron.cc.
View newest version in sPHENIX GitHub at line 93 of file G4DiffractiveSplitableHadron.cc
References ChooseStringEnds(), G4VSplitableHadron::GetDefinition(), G4ParticleDefinition::GetPDGEncoding(), G4VSplitableHadron::IsSplit(), Parton, PartonIndex, G4Parton::Set4Momentum(), G4VSplitableHadron::Splitting(), and tmp.
Member Data Documentation
G4Parton* G4DiffractiveSplitableHadron::Parton[2] private
Definition at line 69 of file G4DiffractiveSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 69 of file G4DiffractiveSplitableHadron.hh
Referenced by G4DiffractiveSplitableHadron(), GetNextAntiParton(), GetNextParton(), SetFirstParton(), SetSecondParton(), and SplitUp().
G4int G4DiffractiveSplitableHadron::PartonIndex private
Definition at line 70 of file G4DiffractiveSplitableHadron.hh.
View newest version in sPHENIX GitHub at line 70 of file G4DiffractiveSplitableHadron.hh
Referenced by G4DiffractiveSplitableHadron(), GetNextAntiParton(), GetNextParton(), and SplitUp().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/include/G4DiffractiveSplitableHadron.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/diffraction/src/G4DiffractiveSplitableHadron.cc