ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/global/pyG4ThreeVector.cc File Reference
pyG4ThreeVector.cc File Reference
#include <boost/python.hpp>
#include "G4ThreeVector.hh"
#include "G4RotationMatrix.hh"
Namespaces
namespace pyG4ThreeVector
Typedefs
typedef G4ThreeVector XXX
Functions
void export_G4ThreeVector ()
Variables
G4double(XXX::* pyG4ThreeVector::f1_theta)() const = &XXX::theta
G4double(XXX::* pyG4ThreeVector::f2_theta)(const XXX &) const = &XXX::theta
G4double(XXX::* pyG4ThreeVector::f1_cosTheta)() const = &XXX::cosTheta
G4double(XXX::* pyG4ThreeVector::f2_cosTheta)(const XXX &) const = &XXX::cosTheta
G4double(XXX::* pyG4ThreeVector::f1_cos2Theta)() const = &XXX::cos2Theta
G4double(XXX::* pyG4ThreeVector::f2_cos2Theta)(const XXX &) const = &XXX::cos2Theta
G4double(XXX::* pyG4ThreeVector::f1_perp2)() const = &XXX::perp2
G4double(XXX::* pyG4ThreeVector::f2_perp2)(const XXX &) const = &XXX::perp2
G4double(XXX::* pyG4ThreeVector::f1_perp)() const = &XXX::perp
G4double(XXX::* pyG4ThreeVector::f2_perp)(const XXX &) const = &XXX::perp
G4double(XXX::* pyG4ThreeVector::f1_angle)() const = &XXX::angle
G4double(XXX::* pyG4ThreeVector::f2_angle)(const XXX &) const = &XXX::angle
G4double(XXX::* pyG4ThreeVector::f1_eta)() const = &XXX::eta
G4double(XXX::* pyG4ThreeVector::f2_eta)(const XXX &) const = &XXX::eta
XXX(XXX::* pyG4ThreeVector::f1_project)() const = &XXX::project
XXX(XXX::* pyG4ThreeVector::f2_project)(const XXX &) const = &XXX::project
XXX(XXX::* pyG4ThreeVector::f1_perpPart)() const = &XXX::perpPart
XXX(XXX::* pyG4ThreeVector::f2_perpPart)(const XXX &) const = &XXX::perpPart
G4double(XXX::* pyG4ThreeVector::f1_rapidity)() const = &XXX::rapidity
G4double(XXX::* pyG4ThreeVector::f2_rapidity)(const XXX &) const = &XXX::rapidity
G4double(XXX::* pyG4ThreeVector::f1_polarAngle)(const XXX &) const = &XXX::polarAngle
G4double(XXX::* pyG4ThreeVector::f2_polarAngle)(const XXX &, const XXX &) const = &XXX::polarAngle
G4double(XXX::* pyG4ThreeVector::f1_azimAngle)(const XXX &) const = &XXX::azimAngle
G4double(XXX::* pyG4ThreeVector::f2_azimAngle)(const XXX &, const XXX &) const = &XXX::azimAngle
XXX &(XXX::* pyG4ThreeVector::f1_rotate)(G4double, const XXX &) = &XXX::rotate
XXX &(XXX::* pyG4ThreeVector::f2_rotate)(const XXX &, G4double) = &XXX::rotate
XXX &(XXX::* pyG4ThreeVector::f3_rotate)(const HepAxisAngle &) = &XXX::rotate
XXX &(XXX::* pyG4ThreeVector::f4_rotate)(const HepEulerAngles &) = &XXX::rotate
XXX &(XXX::* pyG4ThreeVector::f5_rotate)(G4double, G4double, G4double) = &XXX::rotate
Typedef Documentation
typedef G4ThreeVector XXX
Definition at line 38 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 38 of file pyG4ThreeVector.cc
Function Documentation
void export_G4ThreeVector ()
Definition at line 98 of file pyG4ThreeVector.cc.
View newest version in sPHENIX GitHub at line 98 of file pyG4ThreeVector.cc
References CLHEP::HepRotation::compare(), Acts::VectorHelpers::cross(), deltaR(), pyG4ThreeVector::f1_angle, pyG4ThreeVector::f1_azimAngle, pyG4ThreeVector::f1_cos2Theta, pyG4ThreeVector::f1_cosTheta, pyG4ThreeVector::f1_eta, pyG4ThreeVector::f1_perp2, pyG4ThreeVector::f1_perpPart, pyG4ThreeVector::f1_polarAngle, pyG4ThreeVector::f1_project, pyG4ThreeVector::f1_rapidity, pyG4RotationMatrix::f1_rotate, pyG4ThreeVector::f1_theta, pyG4ThreeVector::f2_angle, pyG4ThreeVector::f2_azimAngle, pyG4ThreeVector::f2_cos2Theta, pyG4ThreeVector::f2_cosTheta, pyG4ThreeVector::f2_eta, pyG4ThreeVector::f2_perp2, pyG4ThreeVector::f2_perpPart, pyG4ThreeVector::f2_polarAngle, pyG4ThreeVector::f2_project, pyG4ThreeVector::f2_rapidity, pyG4RotationMatrix::f2_rotate, pyG4ThreeVector::f2_theta, pyG4ThreeVector::f5_rotate, CLHEP::HepRotation::getPhi(), CLHEP::HepRotation::getTheta(), CLHEP::HepRotation::getTolerance(), CLHEP::HepRotation::howNear(), CLHEP::HepRotation::isNear(), CLHEP::HepRotation::phi(), r, CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::HepRotation::rotateZ(), CLHEP::HepRotation::set(), CLHEP::HepRotation::setPhi(), CLHEP::HepRotation::setTheta(), CLHEP::HepRotation::setTolerance(), CLHEP::HepRotation::transform(), x, y, and z.
Referenced by BOOST_PYTHON_MODULE().