ECCE @ EIC Software: CexmcReconstructor Class Reference
CexmcReconstructor Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcReconstructor.hh>
Public Member Functions
CexmcReconstructor ()
virtual ~CexmcReconstructor ()
virtual void Reconstruct (const CexmcEnergyDepositStore *edStore)
void SetCalorimeterEntryPointDefinitionAlgorithm (CexmcCalorimeterEntryPointDefinitionAlgorithm algo)
void SetCalorimeterEntryPointDepthDefinitionAlgorithm (CexmcCalorimeterEntryPointDepthDefinitionAlgorithm algo)
void SetCrystalSelectionAlgorithm (CexmcCrystalSelectionAlgorithm algo)
void UseInnerRefCrystal (G4bool on=true)
void SetCalorimeterEntryPointDepth (G4double depth)
CexmcCalorimeterEntryPointDefinitionAlgorithm GetCalorimeterEntryPointDefinitionAlgorithm (void) const
CexmcCalorimeterEntryPointDepthDefinitionAlgorithm GetCalorimeterEntryPointDepthDefinitionAlgorithm (void) const
CexmcCrystalSelectionAlgorithm GetCrystalSelectionAlgorithm (void) const
G4bool IsInnerRefCrystalUsed (void) const
G4double GetCalorimeterEntryPointDepth (void) const
const G4ThreeVector & GetCalorimeterEPLeftPosition (void) const
const G4ThreeVector & GetCalorimeterEPRightPosition (void) const
const G4ThreeVector & GetCalorimeterEPLeftDirection (void) const
const G4ThreeVector & GetCalorimeterEPRightDirection (void) const
const G4ThreeVector & GetTargetEPPosition (void) const
const G4ThreeVector & GetTargetEPDirection (void) const
const G4ThreeVector & GetCalorimeterEPLeftWorldPosition (void) const
const G4ThreeVector & GetCalorimeterEPRightWorldPosition (void) const
const G4ThreeVector & GetCalorimeterEPLeftWorldDirection (void) const
const G4ThreeVector & GetCalorimeterEPRightWorldDirection (void) const
const G4ThreeVector & GetTargetEPWorldPosition (void) const
const G4ThreeVector & GetTargetEPWorldDirection (void) const
G4double GetTheAngle (void) const
G4bool HasBasicTrigger (void) const
virtual G4bool HasFullTrigger (void) const
Protected Member Functions
void ReconstructEntryPoints (const CexmcEnergyDepositStore *edStore)
void ReconstructTargetPoint (void)
void ReconstructAngle (void)
Protected Attributes
G4bool hasBasicTrigger
CexmcCalorimeterEntryPointDefinitionAlgorithm epDefinitionAlgorithm
CexmcCalorimeterEntryPointDepthDefinitionAlgorithm epDepthDefinitionAlgorithm
CexmcCrystalSelectionAlgorithm csAlgorithm
G4bool useInnerRefCrystal
G4double epDepth
G4ThreeVector calorimeterEPLeftPosition
G4ThreeVector calorimeterEPRightPosition
G4ThreeVector calorimeterEPLeftDirection
G4ThreeVector calorimeterEPRightDirection
G4ThreeVector targetEPPosition
G4ThreeVector targetEPDirection
G4ThreeVector calorimeterEPLeftWorldPosition
G4ThreeVector calorimeterEPRightWorldPosition
G4ThreeVector calorimeterEPLeftWorldDirection
G4ThreeVector calorimeterEPRightWorldDirection
G4ThreeVector targetEPWorldPosition
G4ThreeVector targetEPWorldDirection
G4double theAngle
G4double calorimeterEDLeftAdjacent
G4double calorimeterEDRightAdjacent
G4bool collectEDInAdjacentCrystals
Private Member Functions
void CollectEDInAdjacentCrystals (const CexmcEnergyDepositCalorimeterCollection &edHits, G4int row, G4int column, G4double &ed)
void CalculateWeightedEPPosition (const CexmcEnergyDepositCalorimeterCollection &edHits, G4int row, G4int column, G4double &x, G4double &y, G4double &ed)
void TransformToAdjacentInnerCrystal (G4int &column, G4int &row) const
Private Attributes
CexmcSetup::CalorimeterGeometryData calorimeterGeometry
G4AffineTransform calorimeterLeftTransform
G4AffineTransform calorimeterRightTransform
G4AffineTransform targetTransform
G4bool targetEPInitialized
CexmcReconstructorMessenger * messenger
Detailed Description
Definition at line 56 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 56 of file CexmcReconstructor.hh
Constructor & Destructor Documentation
CexmcReconstructor::CexmcReconstructor () explicit
Definition at line 50 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 50 of file CexmcReconstructor.cc
References calorimeterGeometry, calorimeterLeftTransform, calorimeterRightTransform, CexmcSetup::GetCalorimeterGeometry(), CexmcSetup::GetCalorimeterLeftTransform(), CexmcSetup::GetCalorimeterRightTransform(), G4RunManager::GetRunManager(), CexmcSetup::GetTargetTransform(), G4RunManager::GetUserDetectorConstruction(), messenger, and targetTransform.
CexmcReconstructor::~CexmcReconstructor () virtual
Definition at line 70 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 70 of file CexmcReconstructor.cc
References messenger.
Member Function Documentation
void CexmcReconstructor::CalculateWeightedEPPosition (const CexmcEnergyDepositCalorimeterCollection & edHits, G4int row, G4int column, G4double & x, G4double & y, G4double & ed) private
Definition at line 312 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 312 of file CexmcReconstructor.cc
References calorimeterGeometry, CexmcEntryPointBySqrtEDWeights, CexmcSelectAdjacentCrystals, CexmcSetup::CalorimeterGeometryData::crystalHeight, CexmcSetup::CalorimeterGeometryData::crystalWidth, csAlgorithm, epDefinitionAlgorithm, k, CexmcSetup::CalorimeterGeometryData::nCrystalsInColumn, and CexmcSetup::CalorimeterGeometryData::nCrystalsInRow.
Referenced by ReconstructEntryPoints().
void CexmcReconstructor::CollectEDInAdjacentCrystals (const CexmcEnergyDepositCalorimeterCollection & edHits, G4int row, G4int column, G4double & ed) private
Definition at line 280 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 280 of file CexmcReconstructor.cc
References k.
Referenced by ReconstructEntryPoints().
CexmcCalorimeterEntryPointDefinitionAlgorithm CexmcReconstructor::GetCalorimeterEntryPointDefinitionAlgorithm (void) const inline
Definition at line 248 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 248 of file CexmcReconstructor.hh
References epDefinitionAlgorithm.
G4double CexmcReconstructor::GetCalorimeterEntryPointDepth (void) const inline
Definition at line 276 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 276 of file CexmcReconstructor.hh
References epDepth.
CexmcCalorimeterEntryPointDepthDefinitionAlgorithm CexmcReconstructor::GetCalorimeterEntryPointDepthDefinitionAlgorithm (void) const inline
Definition at line 256 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 256 of file CexmcReconstructor.hh
References epDepthDefinitionAlgorithm.
const G4ThreeVector & CexmcReconstructor::GetCalorimeterEPLeftDirection (void) const inline
Definition at line 297 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 297 of file CexmcReconstructor.hh
References calorimeterEPLeftDirection.
const G4ThreeVector & CexmcReconstructor::GetCalorimeterEPLeftPosition (void) const inline
Definition at line 283 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 283 of file CexmcReconstructor.hh
References calorimeterEPLeftPosition.
Referenced by CexmcEventAction::PrintReconstructedData().
const G4ThreeVector & CexmcReconstructor::GetCalorimeterEPLeftWorldDirection (void) const inline
Definition at line 339 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 339 of file CexmcReconstructor.hh
References calorimeterEPLeftWorldDirection.
const G4ThreeVector & CexmcReconstructor::GetCalorimeterEPLeftWorldPosition (void) const inline
Definition at line 325 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 325 of file CexmcReconstructor.hh
References calorimeterEPLeftWorldPosition.
Referenced by CexmcEventAction::DrawReconstructionData().
const G4ThreeVector & CexmcReconstructor::GetCalorimeterEPRightDirection (void) const inline
Definition at line 304 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 304 of file CexmcReconstructor.hh
References calorimeterEPRightDirection.
const G4ThreeVector & CexmcReconstructor::GetCalorimeterEPRightPosition (void) const inline
Definition at line 290 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 290 of file CexmcReconstructor.hh
References calorimeterEPRightPosition.
Referenced by CexmcEventAction::PrintReconstructedData().
const G4ThreeVector & CexmcReconstructor::GetCalorimeterEPRightWorldDirection (void) const inline
Definition at line 346 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 346 of file CexmcReconstructor.hh
References calorimeterEPRightWorldDirection.
const G4ThreeVector & CexmcReconstructor::GetCalorimeterEPRightWorldPosition (void) const inline
Definition at line 332 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 332 of file CexmcReconstructor.hh
References calorimeterEPRightWorldPosition.
Referenced by CexmcEventAction::DrawReconstructionData().
CexmcCrystalSelectionAlgorithm CexmcReconstructor::GetCrystalSelectionAlgorithm (void) const inline
Definition at line 264 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 264 of file CexmcReconstructor.hh
References csAlgorithm.
const G4ThreeVector & CexmcReconstructor::GetTargetEPDirection (void) const inline
Definition at line 318 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 318 of file CexmcReconstructor.hh
References targetEPDirection.
const G4ThreeVector & CexmcReconstructor::GetTargetEPPosition (void) const inline
Definition at line 311 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 311 of file CexmcReconstructor.hh
References targetEPPosition.
Referenced by CexmcEventAction::PrintReconstructedData().
const G4ThreeVector & CexmcReconstructor::GetTargetEPWorldDirection (void) const inline
Definition at line 360 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 360 of file CexmcReconstructor.hh
References targetEPWorldDirection.
const G4ThreeVector & CexmcReconstructor::GetTargetEPWorldPosition (void) const inline
Definition at line 353 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 353 of file CexmcReconstructor.hh
References targetEPWorldPosition.
Referenced by CexmcEventAction::DrawReconstructionData().
G4double CexmcReconstructor::GetTheAngle (void) const inline
Definition at line 366 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 366 of file CexmcReconstructor.hh
References theAngle.
Referenced by CexmcEventAction::PrintReconstructedData().
G4bool CexmcReconstructor::HasBasicTrigger (void) const inline
Definition at line 372 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 372 of file CexmcReconstructor.hh
References hasBasicTrigger.
Referenced by CexmcEventAction::EndOfEventAction().
G4bool CexmcReconstructor::HasFullTrigger (void) const virtual
Reimplemented in CexmcChargeExchangeReconstructor.
Definition at line 87 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 87 of file CexmcReconstructor.cc
References hasBasicTrigger.
G4bool CexmcReconstructor::IsInnerRefCrystalUsed (void) const inline
Definition at line 270 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 270 of file CexmcReconstructor.hh
References useInnerRefCrystal.
void CexmcReconstructor::Reconstruct (const CexmcEnergyDepositStore * edStore) virtual
Reimplemented in CexmcChargeExchangeReconstructor.
Definition at line 76 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 76 of file CexmcReconstructor.cc
References hasBasicTrigger, ReconstructAngle(), ReconstructEntryPoints(), and ReconstructTargetPoint().
void CexmcReconstructor::ReconstructAngle (void) protected
Definition at line 268 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 268 of file CexmcReconstructor.cc
References CLHEP::Hep3Vector::angle(), calorimeterEPLeftWorldPosition, calorimeterEPRightWorldPosition, hasBasicTrigger, targetEPWorldPosition, and theAngle.
Referenced by Reconstruct(), and CexmcChargeExchangeReconstructor::Reconstruct().
void CexmcReconstructor::ReconstructEntryPoints (const CexmcEnergyDepositStore * edStore) protected
Definition at line 93 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 93 of file CexmcReconstructor.cc
References CalculateWeightedEPPosition(), calorimeterEDLeftAdjacent, CexmcEnergyDepositStore::calorimeterEDLeftCollection, CexmcEnergyDepositStore::calorimeterEDLeftMaxX, CexmcEnergyDepositStore::calorimeterEDLeftMaxY, calorimeterEDRightAdjacent, CexmcEnergyDepositStore::calorimeterEDRightCollection, CexmcEnergyDepositStore::calorimeterEDRightMaxX, CexmcEnergyDepositStore::calorimeterEDRightMaxY, calorimeterEPLeftDirection, calorimeterEPLeftPosition, calorimeterEPLeftWorldDirection, calorimeterEPLeftWorldPosition, calorimeterEPRightDirection, calorimeterEPRightPosition, calorimeterEPRightWorldDirection, calorimeterEPRightWorldPosition, calorimeterGeometry, calorimeterLeftTransform, calorimeterRightTransform, CexmcEntryPointByLinearEDWeights, CexmcEntryPointBySqrtEDWeights, CexmcEntryPointDepthPlain, CexmcEntryPointDepthSphere, CexmcEntryPointInTheCenter, CexmcEntryPointInTheCenterOfCrystalWithMaxED, CexmcSelectAdjacentCrystals, CollectEDInAdjacentCrystals(), collectEDInAdjacentCrystals, CexmcSetup::CalorimeterGeometryData::crystalHeight, CexmcSetup::CalorimeterGeometryData::crystalLength, CexmcSetup::CalorimeterGeometryData::crystalWidth, csAlgorithm, epDefinitionAlgorithm, epDepth, epDepthDefinitionAlgorithm, hasBasicTrigger, CLHEP::Hep3Vector::mag(), CexmcSetup::CalorimeterGeometryData::nCrystalsInColumn, CexmcSetup::CalorimeterGeometryData::nCrystalsInRow, G4AffineTransform::NetTranslation(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), G4AffineTransform::TransformAxis(), G4AffineTransform::TransformPoint(), TransformToAdjacentInnerCrystal(), useInnerRefCrystal, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, and CLHEP::Hep3Vector::z().
Referenced by Reconstruct(), and CexmcChargeExchangeReconstructor::Reconstruct().
void CexmcReconstructor::ReconstructTargetPoint (void) protected
Definition at line 247 of file CexmcReconstructor.cc.
View newest version in sPHENIX GitHub at line 247 of file CexmcReconstructor.cc
References hasBasicTrigger, G4AffineTransform::Inverse(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), targetEPDirection, targetEPInitialized, targetEPPosition, targetEPWorldDirection, targetEPWorldPosition, targetTransform, G4AffineTransform::TransformAxis(), and G4AffineTransform::TransformPoint().
Referenced by Reconstruct(), and CexmcChargeExchangeReconstructor::Reconstruct().
void CexmcReconstructor::SetCalorimeterEntryPointDefinitionAlgorithm (CexmcCalorimeterEntryPointDefinitionAlgorithm algo) inline
Definition at line 212 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 212 of file CexmcReconstructor.hh
References epDefinitionAlgorithm.
Referenced by CexmcReconstructorMessenger::SetNewValue().
void CexmcReconstructor::SetCalorimeterEntryPointDepth (G4double depth) inline
Definition at line 240 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 240 of file CexmcReconstructor.hh
References epDepth.
Referenced by CexmcReconstructorMessenger::SetNewValue().
void CexmcReconstructor::SetCalorimeterEntryPointDepthDefinitionAlgorithm (CexmcCalorimeterEntryPointDepthDefinitionAlgorithm algo) inline
Definition at line 220 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 220 of file CexmcReconstructor.hh
References epDepthDefinitionAlgorithm.
Referenced by CexmcReconstructorMessenger::SetNewValue().
void CexmcReconstructor::SetCrystalSelectionAlgorithm (CexmcCrystalSelectionAlgorithm algo) inline
Definition at line 227 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 227 of file CexmcReconstructor.hh
References csAlgorithm.
Referenced by CexmcReconstructorMessenger::SetNewValue().
void CexmcReconstructor::TransformToAdjacentInnerCrystal (G4int & column, G4int & row) const inline private
Definition at line 378 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 378 of file CexmcReconstructor.hh
References calorimeterGeometry, CexmcSetup::CalorimeterGeometryData::nCrystalsInColumn, and CexmcSetup::CalorimeterGeometryData::nCrystalsInRow.
Referenced by ReconstructEntryPoints().
void CexmcReconstructor::UseInnerRefCrystal (G4bool on = true) inline
Definition at line 234 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 234 of file CexmcReconstructor.hh
References useInnerRefCrystal.
Referenced by CexmcReconstructorMessenger::SetNewValue().
Member Data Documentation
G4double CexmcReconstructor::calorimeterEDLeftAdjacent protected
Definition at line 190 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 190 of file CexmcReconstructor.hh
Referenced by CexmcChargeExchangeReconstructor::Reconstruct(), and ReconstructEntryPoints().
G4double CexmcReconstructor::calorimeterEDRightAdjacent protected
Definition at line 192 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 192 of file CexmcReconstructor.hh
Referenced by CexmcChargeExchangeReconstructor::Reconstruct(), and ReconstructEntryPoints().
G4ThreeVector CexmcReconstructor::calorimeterEPLeftDirection protected
Definition at line 167 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 167 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEPLeftDirection(), and ReconstructEntryPoints().
G4ThreeVector CexmcReconstructor::calorimeterEPLeftPosition protected
Definition at line 163 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 163 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEPLeftPosition(), and ReconstructEntryPoints().
G4ThreeVector CexmcReconstructor::calorimeterEPLeftWorldDirection protected
Definition at line 179 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 179 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEPLeftWorldDirection(), and ReconstructEntryPoints().
G4ThreeVector CexmcReconstructor::calorimeterEPLeftWorldPosition protected
Definition at line 175 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 175 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEPLeftWorldPosition(), CexmcChargeExchangeReconstructor::Reconstruct(), ReconstructAngle(), and ReconstructEntryPoints().
G4ThreeVector CexmcReconstructor::calorimeterEPRightDirection protected
Definition at line 169 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 169 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEPRightDirection(), and ReconstructEntryPoints().
G4ThreeVector CexmcReconstructor::calorimeterEPRightPosition protected
Definition at line 165 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 165 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEPRightPosition(), and ReconstructEntryPoints().
G4ThreeVector CexmcReconstructor::calorimeterEPRightWorldDirection protected
Definition at line 181 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 181 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEPRightWorldDirection(), and ReconstructEntryPoints().
G4ThreeVector CexmcReconstructor::calorimeterEPRightWorldPosition protected
Definition at line 177 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 177 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEPRightWorldPosition(), CexmcChargeExchangeReconstructor::Reconstruct(), ReconstructAngle(), and ReconstructEntryPoints().
CexmcSetup::CalorimeterGeometryData CexmcReconstructor::calorimeterGeometry private
Definition at line 197 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 197 of file CexmcReconstructor.hh
Referenced by CalculateWeightedEPPosition(), CexmcReconstructor(), ReconstructEntryPoints(), and TransformToAdjacentInnerCrystal().
G4AffineTransform CexmcReconstructor::calorimeterLeftTransform private
Definition at line 199 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 199 of file CexmcReconstructor.hh
Referenced by CexmcReconstructor(), and ReconstructEntryPoints().
G4AffineTransform CexmcReconstructor::calorimeterRightTransform private
Definition at line 201 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 201 of file CexmcReconstructor.hh
Referenced by CexmcReconstructor(), and ReconstructEntryPoints().
G4bool CexmcReconstructor::collectEDInAdjacentCrystals protected
Definition at line 194 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 194 of file CexmcReconstructor.hh
Referenced by CexmcChargeExchangeReconstructor::Reconstruct(), and ReconstructEntryPoints().
CexmcCrystalSelectionAlgorithm CexmcReconstructor::csAlgorithm protected
Definition at line 156 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 156 of file CexmcReconstructor.hh
Referenced by CalculateWeightedEPPosition(), GetCrystalSelectionAlgorithm(), ReconstructEntryPoints(), and SetCrystalSelectionAlgorithm().
CexmcCalorimeterEntryPointDefinitionAlgorithm CexmcReconstructor::epDefinitionAlgorithm protected
Definition at line 151 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 151 of file CexmcReconstructor.hh
Referenced by CalculateWeightedEPPosition(), GetCalorimeterEntryPointDefinitionAlgorithm(), ReconstructEntryPoints(), and SetCalorimeterEntryPointDefinitionAlgorithm().
G4double CexmcReconstructor::epDepth protected
Definition at line 160 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 160 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEntryPointDepth(), ReconstructEntryPoints(), and SetCalorimeterEntryPointDepth().
CexmcCalorimeterEntryPointDepthDefinitionAlgorithm CexmcReconstructor::epDepthDefinitionAlgorithm protected
Definition at line 154 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 154 of file CexmcReconstructor.hh
Referenced by GetCalorimeterEntryPointDepthDefinitionAlgorithm(), ReconstructEntryPoints(), and SetCalorimeterEntryPointDepthDefinitionAlgorithm().
G4bool CexmcReconstructor::hasBasicTrigger protected
Definition at line 148 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 148 of file CexmcReconstructor.hh
Referenced by HasBasicTrigger(), HasFullTrigger(), CexmcChargeExchangeReconstructor::HasFullTrigger(), Reconstruct(), CexmcChargeExchangeReconstructor::Reconstruct(), ReconstructAngle(), ReconstructEntryPoints(), and ReconstructTargetPoint().
CexmcReconstructorMessenger* CexmcReconstructor::messenger private
Definition at line 208 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 208 of file CexmcReconstructor.hh
Referenced by CexmcReconstructor(), and ~CexmcReconstructor().
G4ThreeVector CexmcReconstructor::targetEPDirection protected
Definition at line 173 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 173 of file CexmcReconstructor.hh
Referenced by GetTargetEPDirection(), and ReconstructTargetPoint().
G4bool CexmcReconstructor::targetEPInitialized private
Definition at line 205 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 205 of file CexmcReconstructor.hh
Referenced by ReconstructTargetPoint().
G4ThreeVector CexmcReconstructor::targetEPPosition protected
Definition at line 171 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 171 of file CexmcReconstructor.hh
Referenced by GetTargetEPPosition(), and ReconstructTargetPoint().
G4ThreeVector CexmcReconstructor::targetEPWorldDirection protected
Definition at line 185 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 185 of file CexmcReconstructor.hh
Referenced by GetTargetEPWorldDirection(), and ReconstructTargetPoint().
G4ThreeVector CexmcReconstructor::targetEPWorldPosition protected
Definition at line 183 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 183 of file CexmcReconstructor.hh
Referenced by GetTargetEPWorldPosition(), CexmcChargeExchangeReconstructor::Reconstruct(), ReconstructAngle(), and ReconstructTargetPoint().
G4AffineTransform CexmcReconstructor::targetTransform private
Definition at line 203 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 203 of file CexmcReconstructor.hh
Referenced by CexmcReconstructor(), and ReconstructTargetPoint().
G4double CexmcReconstructor::theAngle protected
Definition at line 187 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 187 of file CexmcReconstructor.hh
Referenced by GetTheAngle(), CexmcChargeExchangeReconstructor::Reconstruct(), and ReconstructAngle().
G4bool CexmcReconstructor::useInnerRefCrystal protected
Definition at line 158 of file CexmcReconstructor.hh.
View newest version in sPHENIX GitHub at line 158 of file CexmcReconstructor.hh
Referenced by IsInnerRefCrystalUsed(), ReconstructEntryPoints(), and UseInnerRefCrystal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcReconstructor.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcReconstructor.cc