ECCE @ EIC Software: G4AdjointPhysicsList Class Reference
G4AdjointPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/G4AdjointPhysicsList.hh>
Public Member Functions
G4AdjointPhysicsList ()
virtual ~G4AdjointPhysicsList ()
void SetLossFluctuationFlag (bool aBool)
void SetUseIonisation (bool aBool)
void SetUseProtonIonisation (bool aBool)
void SetUseBrem (bool aBool)
void SetUseCompton (bool aBool)
void SetUseMS (bool aBool)
void SetUsePEEffect (bool aBool)
void SetUseGammaConversion (bool aBool)
void SetUseEgainFluctuation (bool aBool)
void SetEminAdjModels (G4double aVal)
void SetEmaxAdjModels (G4double aVal)
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
virtual void TerminateWorker ()
Protected Member Functions
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
void ConstructBosons ()
void ConstructLeptons ()
void ConstructMesons ()
void ConstructBaryons ()
void ConstructAdjointParticles ()
void ConstructGeneral ()
void ConstructEM ()
Protected Member Functions inherited from G4VUserPhysicsList
void AddTransportation ()
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
void BuildIntegralPhysicsTable (G4VProcess *, G4ParticleDefinition *)
virtual void RetrievePhysicsTable (G4ParticleDefinition *, const G4String &directory, G4bool ascii=false)
void InitializeProcessManager ()
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
Protected Attributes
G4eIonisation * fEminusIonisation
G4hIonisation * fPIonisation
Protected Attributes inherited from G4VUserPhysicsList
G4ParticleTable * theParticleTable
G4int verboseLevel
G4double defaultCutValue
G4bool isSetDefaultCutValue
G4ProductionCutsTable * fCutsTable
G4bool fRetrievePhysicsTable
G4bool fStoredInAscii
G4bool fIsCheckedForRetrievePhysicsTable
G4bool fIsRestoredCutValues
G4String directoryPhysicsTable
G4bool fDisableCheckParticleList
G4int g4vuplInstanceID
Private Attributes
G4AdjointPhysicsMessenger * fPhysicsMessenger
G4bool fUse_forced_interaction
G4bool fUse_eionisation
G4bool fUse_pionisation
G4bool fUse_brem
G4bool fUse_compton
G4bool fUse_ms
G4bool fUse_egain_fluctuation
G4bool fUse_peeffect
G4bool fUse_gamma_conversion
G4double fEmin_adj_models
G4double fEmax_adj_models
G4double fCS_biasing_factor_compton
G4double fCS_biasing_factor_brem
G4double fCS_biasing_factor_ionisation
G4double fCS_biasing_factor_PEeffect
Additional Inherited Members
Static Public Member Functions inherited from G4VUserPhysicsList
static const G4VUPLManager & GetSubInstanceManager ()
Static Protected Attributes inherited from G4VUserPhysicsList
static G4RUN_DLL G4VUPLManager subInstanceManager
Detailed Description
Definition at line 57 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 57 of file G4AdjointPhysicsList.hh
Constructor & Destructor Documentation
G4AdjointPhysicsList::G4AdjointPhysicsList ()
Definition at line 49 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 49 of file G4AdjointPhysicsList.cc
References G4VUserPhysicsList::defaultCutValue, fPhysicsMessenger, mm, and G4VUserPhysicsList::SetVerboseLevel().
G4AdjointPhysicsList::~G4AdjointPhysicsList () virtual
Definition at line 67 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 67 of file G4AdjointPhysicsList.cc
Member Function Documentation
void G4AdjointPhysicsList::ConstructAdjointParticles () protected
Definition at line 155 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 155 of file G4AdjointPhysicsList.cc
References G4AdjointElectron::AdjointElectronDefinition(), G4AdjointGamma::AdjointGammaDefinition(), and G4AdjointProton::AdjointProtonDefinition().
Referenced by ConstructParticle().
void G4AdjointPhysicsList::ConstructBaryons () protected
Definition at line 141 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 141 of file G4AdjointPhysicsList.cc
References G4AntiNeutron::AntiNeutronDefinition(), G4AntiProton::AntiProtonDefinition(), G4Neutron::NeutronDefinition(), and G4Proton::ProtonDefinition().
Referenced by ConstructParticle().
void G4AdjointPhysicsList::ConstructBosons () protected
Definition at line 92 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 92 of file G4AdjointPhysicsList.cc
References G4ChargedGeantino::ChargedGeantinoDefinition(), G4Gamma::GammaDefinition(), G4Geantino::GeantinoDefinition(), and G4OpticalPhoton::OpticalPhotonDefinition().
Referenced by ConstructParticle().
void G4AdjointPhysicsList::ConstructEM () protected
Definition at line 222 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 222 of file G4AdjointPhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4AdjointElectron::AdjointElectron(), G4AdjointGamma::AdjointGamma(), G4AdjointProton::AdjointProton(), G4AdjointSimManager::ConsiderParticleAsPrimary(), G4Electron::Electron(), fCS_biasing_factor_brem, fCS_biasing_factor_compton, fCS_biasing_factor_ionisation, fCS_biasing_factor_PEeffect, fEmax_adj_models, fEmin_adj_models, fEminusIonisation, fPIonisation, fUse_brem, fUse_compton, fUse_egain_fluctuation, fUse_eionisation, fUse_forced_interaction, fUse_gamma_conversion, fUse_ms, fUse_peeffect, fUse_pionisation, G4AdjointCSManager::GetAdjointCSManager(), G4AdjointSimManager::GetInstance(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetProcessManager(), idxAlongStep, idxAtRest, idxPostStep, particle, G4Proton::Proton(), G4AdjointForcedInteractionForGamma::RegisterAdjointBremModel(), G4AdjointCSManager::RegisterAdjointParticle(), G4VEmAdjointModel::SetCSBiasingFactor(), G4ContinuousGainOfEnergy::SetDirectEnergyLossProcess(), G4ContinuousGainOfEnergy::SetDirectParticle(), G4AdjointComptonModel::SetDirectProcess(), G4VMultipleScattering::SetEmModel(), G4VEmAdjointModel::SetHighEnergyLimit(), G4ContinuousGainOfEnergy::SetLossFluctuations(), G4VEnergyLossProcess::SetLossFluctuations(), G4VEmAdjointModel::SetLowEnergyLimit(), G4ParticleDefinition::SetProcessManager(), G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToFirst(), and G4VEmAdjointModel::SetUseMatrix().
Referenced by ConstructProcess().
void G4AdjointPhysicsList::ConstructGeneral () protected
Definition at line 684 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 684 of file G4AdjointPhysicsList.cc
References G4ProcessManager::AddProcess(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), idxAtRest, idxPostStep, G4Decay::IsApplicable(), particle, and G4ProcessManager::SetProcessOrdering().
Referenced by ConstructProcess().
void G4AdjointPhysicsList::ConstructLeptons () protected
Definition at line 107 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 107 of file G4AdjointPhysicsList.cc
References G4AntiNeutrinoE::AntiNeutrinoEDefinition(), G4AntiNeutrinoMu::AntiNeutrinoMuDefinition(), G4Electron::ElectronDefinition(), G4MuonMinus::MuonMinusDefinition(), G4MuonPlus::MuonPlusDefinition(), G4NeutrinoE::NeutrinoEDefinition(), G4NeutrinoMu::NeutrinoMuDefinition(), and G4Positron::PositronDefinition().
Referenced by ConstructParticle().
void G4AdjointPhysicsList::ConstructMesons () protected
Definition at line 123 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 123 of file G4AdjointPhysicsList.cc
References G4AntiKaonZero::AntiKaonZeroDefinition(), G4Eta::EtaDefinition(), G4EtaPrime::EtaPrimeDefinition(), G4KaonMinus::KaonMinusDefinition(), G4KaonPlus::KaonPlusDefinition(), G4KaonZero::KaonZeroDefinition(), G4KaonZeroLong::KaonZeroLongDefinition(), G4KaonZeroShort::KaonZeroShortDefinition(), G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), and G4PionZero::PionZeroDefinition().
Referenced by ConstructParticle().
void G4AdjointPhysicsList::ConstructParticle (void) protected virtual
Implements G4VUserPhysicsList.
Definition at line 70 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 70 of file G4AdjointPhysicsList.cc
References ConstructAdjointParticles(), ConstructBaryons(), ConstructBosons(), ConstructLeptons(), and ConstructMesons().
void G4AdjointPhysicsList::ConstructProcess (void) protected virtual
Implements G4VUserPhysicsList.
Definition at line 169 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 169 of file G4AdjointPhysicsList.cc
References G4VUserPhysicsList::AddTransportation(), ConstructEM(), and ConstructGeneral().
void G4AdjointPhysicsList::SetCuts () protected virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 704 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 704 of file G4AdjointPhysicsList.cc
References G4VUserPhysicsList::defaultCutValue, G4VUserPhysicsList::DumpCutValuesTable(), G4BestUnit, G4cout, G4endl, G4VUserPhysicsList::SetCutValue(), and G4VUserPhysicsList::verboseLevel.
void G4AdjointPhysicsList::SetEmaxAdjModels (G4double aVal) inline
Definition at line 74 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 74 of file G4AdjointPhysicsList.hh
References fEmax_adj_models.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
void G4AdjointPhysicsList::SetEminAdjModels (G4double aVal) inline
Definition at line 73 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 73 of file G4AdjointPhysicsList.hh
References fEmin_adj_models.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
void G4AdjointPhysicsList::SetLossFluctuationFlag (bool aBool)
Definition at line 85 of file G4AdjointPhysicsList.cc.
View newest version in sPHENIX GitHub at line 85 of file G4AdjointPhysicsList.cc
References fEminusIonisation, and G4VEnergyLossProcess::SetLossFluctuations().
void G4AdjointPhysicsList::SetUseBrem (bool aBool) inline
Definition at line 65 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 65 of file G4AdjointPhysicsList.hh
References fUse_brem.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
void G4AdjointPhysicsList::SetUseCompton (bool aBool) inline
Definition at line 66 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 66 of file G4AdjointPhysicsList.hh
References fUse_compton.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
void G4AdjointPhysicsList::SetUseEgainFluctuation (bool aBool) inline
Definition at line 71 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 71 of file G4AdjointPhysicsList.hh
References fUse_egain_fluctuation.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
void G4AdjointPhysicsList::SetUseGammaConversion (bool aBool) inline
Definition at line 69 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 69 of file G4AdjointPhysicsList.hh
References fUse_gamma_conversion.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
void G4AdjointPhysicsList::SetUseIonisation (bool aBool) inline
Definition at line 63 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 63 of file G4AdjointPhysicsList.hh
References fUse_eionisation.
void G4AdjointPhysicsList::SetUseMS (bool aBool) inline
Definition at line 67 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 67 of file G4AdjointPhysicsList.hh
References fUse_ms.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
void G4AdjointPhysicsList::SetUsePEEffect (bool aBool) inline
Definition at line 68 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 68 of file G4AdjointPhysicsList.hh
References fUse_peeffect.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
void G4AdjointPhysicsList::SetUseProtonIonisation (bool aBool) inline
Definition at line 64 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 64 of file G4AdjointPhysicsList.hh
References fUse_pionisation.
Referenced by G4AdjointPhysicsMessenger::SetNewValue().
Member Data Documentation
G4double G4AdjointPhysicsList::fCS_biasing_factor_brem private
Definition at line 109 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 109 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM().
G4double G4AdjointPhysicsList::fCS_biasing_factor_compton private
Definition at line 108 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 108 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM().
G4double G4AdjointPhysicsList::fCS_biasing_factor_ionisation private
Definition at line 110 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 110 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM().
G4double G4AdjointPhysicsList::fCS_biasing_factor_PEeffect private
Definition at line 111 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 111 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM().
G4double G4AdjointPhysicsList::fEmax_adj_models private
Definition at line 107 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 107 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetEmaxAdjModels().
G4double G4AdjointPhysicsList::fEmin_adj_models private
Definition at line 106 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 106 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetEminAdjModels().
G4eIonisation* G4AdjointPhysicsList::fEminusIonisation protected
Definition at line 92 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 92 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetLossFluctuationFlag().
G4AdjointPhysicsMessenger* G4AdjointPhysicsList::fPhysicsMessenger private
Definition at line 96 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 96 of file G4AdjointPhysicsList.hh
Referenced by G4AdjointPhysicsList().
G4hIonisation* G4AdjointPhysicsList::fPIonisation protected
Definition at line 93 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 93 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM().
G4bool G4AdjointPhysicsList::fUse_brem private
Definition at line 100 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 100 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetUseBrem().
G4bool G4AdjointPhysicsList::fUse_compton private
Definition at line 101 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 101 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetUseCompton().
G4bool G4AdjointPhysicsList::fUse_egain_fluctuation private
Definition at line 103 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 103 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetUseEgainFluctuation().
G4bool G4AdjointPhysicsList::fUse_eionisation private
Definition at line 98 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 98 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetUseIonisation().
G4bool G4AdjointPhysicsList::fUse_forced_interaction private
Definition at line 97 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 97 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM().
G4bool G4AdjointPhysicsList::fUse_gamma_conversion private
Definition at line 105 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 105 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetUseGammaConversion().
G4bool G4AdjointPhysicsList::fUse_ms private
Definition at line 102 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 102 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetUseMS().
G4bool G4AdjointPhysicsList::fUse_peeffect private
Definition at line 104 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 104 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetUsePEEffect().
G4bool G4AdjointPhysicsList::fUse_pionisation private
Definition at line 99 of file G4AdjointPhysicsList.hh.
View newest version in sPHENIX GitHub at line 99 of file G4AdjointPhysicsList.hh
Referenced by ConstructEM(), and SetUseProtonIonisation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/include/G4AdjointPhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/biasing/ReverseMC01/src/G4AdjointPhysicsList.cc