ECCE @ EIC Software: DicomIntersectVolume Class Reference
DicomIntersectVolume Class Reference
Manages intersections of DICOM files with volumes.
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomIntersectVolume.hh>
Public Member Functions
DicomIntersectVolume ()
~DicomIntersectVolume ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void BuildUserSolid (std::vector< G4String > params)
void BuildG4Solid (std::vector< G4String > params)
G4PhantomParameterisation * GetPhantomParam (G4bool bMustExist)
G4bool IsPhantomVolume (G4VPhysicalVolume *pv)
std::vector< G4VPhysicalVolume * > GetPhysicalVolumes (const G4String &name, G4bool exists, G4int nVols)
std::vector< G4LogicalVolume * > GetLogicalVolumes (const G4String &name, G4bool exists, G4int nVols)
std::vector< G4String > GetWordsInString (const G4String &stemp)
Private Attributes
G4UIcmdWithAString * fUserVolumeCmd
G4UIcmdWithAString * fG4VolumeCmd
G4VSolid * fSolid
std::ofstream fout
G4ThreeVector fPhantomMinusCorner
G4bool * fVoxelIsInside
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Manages intersections of DICOM files with volumes.
Definition at line 49 of file DicomIntersectVolume.hh.
View newest version in sPHENIX GitHub at line 49 of file DicomIntersectVolume.hh
Constructor & Destructor Documentation
DicomIntersectVolume::DicomIntersectVolume ()
Definition at line 48 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 48 of file DicomIntersectVolume.cc
References G4UIcommand::AvailableForStates(), fG4VolumeCmd, fUserVolumeCmd, G4State_Idle, G4UIcommand::SetGuidance(), and G4UIcmdWithAString::SetParameterName().
DicomIntersectVolume::~DicomIntersectVolume ()
Definition at line 73 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 73 of file DicomIntersectVolume.cc
References fG4VolumeCmd, and fUserVolumeCmd.
Member Function Documentation
void DicomIntersectVolume::BuildG4Solid (std::vector< G4String > params) private
Definition at line 280 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 280 of file DicomIntersectVolume.cc
References fSolid, and GetLogicalVolumes().
Referenced by SetNewValue().
void DicomIntersectVolume::BuildUserSolid (std::vector< G4String > params) private
Definition at line 267 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 267 of file DicomIntersectVolume.cc
References G4tgbVolume::FindOrConstructG4Solid(), and fSolid.
Referenced by SetNewValue().
std::vector< G4LogicalVolume * > DicomIntersectVolume::GetLogicalVolumes (const G4String & name, G4bool exists, G4int nVols) private
Definition at line 400 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 400 of file DicomIntersectVolume.cc
References G4UIcommand::ConvertToString(), FatalErrorInArgument, G4Exception(), G4LogicalVolumeStore::GetInstance(), and JustWarning.
Referenced by BuildG4Solid().
G4PhantomParameterisation * DicomIntersectVolume::GetPhantomParam (G4bool bMustExist) private
Definition at line 288 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 288 of file DicomIntersectVolume.cc
References FatalErrorInArgument, G4Exception(), G4PhysicalVolumeStore::GetInstance(), G4PVParameterised::GetParameterisation(), and IsPhantomVolume().
Referenced by SetNewValue().
std::vector< G4VPhysicalVolume * > DicomIntersectVolume::GetPhysicalVolumes (const G4String & name, G4bool exists, G4int nVols) private
Definition at line 318 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 318 of file DicomIntersectVolume.cc
References G4UIcommand::ConvertToInt(), G4UIcommand::ConvertToString(), FatalErrorInArgument, G4cerr, G4endl, G4Exception(), and G4PhysicalVolumeStore::GetInstance().
Referenced by SetNewValue().
std::vector< G4String > DicomIntersectVolume::GetWordsInString (const G4String & stemp) private
Definition at line 448 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 448 of file DicomIntersectVolume.cc
References FatalException, and G4Exception().
Referenced by SetNewValue().
G4bool DicomIntersectVolume::IsPhantomVolume (G4VPhysicalVolume * pv) private
Definition at line 383 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 383 of file DicomIntersectVolume.cc
References FALSE, G4VPhysicalVolume::GetRegularStructureId(), G4VPhysicalVolume::GetReplicationData(), kParameterised, kReplica, offset, TRUE, and width.
Referenced by GetPhantomParam().
void DicomIntersectVolume::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 80 of file DicomIntersectVolume.cc.
View newest version in sPHENIX GitHub at line 80 of file DicomIntersectVolume.cc
References G4AffineTransform::ApplyAxisTransform(), G4AffineTransform::ApplyPointTransform(), BuildG4Solid(), BuildUserSolid(), cm3, G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToString(), FatalErrorInArgument, FatalException, fG4VolumeCmd, fout, fSolid, fUserVolumeCmd, fVoxelIsInside, Acts::UnitConstants::g, G4endl, G4Exception(), G4UIcommand::GetCommandName(), G4UIcommand::GetCommandPath(), G4Material::GetDensity(), G4VPhysicalVolume::GetFrameRotation(), G4VPhysicalVolume::GetFrameTranslation(), G4PhantomParameterisation::GetMaterial(), G4PhantomParameterisation::GetMaterialIndex(), G4PhantomParameterisation::GetMaterials(), G4PhantomParameterisation::GetNoVoxelX(), G4PhantomParameterisation::GetNoVoxelY(), G4PhantomParameterisation::GetNoVoxelZ(), GetPhantomParam(), GetPhysicalVolumes(), G4PhantomParameterisation::GetVoxelHalfX(), G4PhantomParameterisation::GetVoxelHalfY(), G4PhantomParameterisation::GetVoxelHalfZ(), GetWordsInString(), G4VSolid::Inside(), G4AffineTransform::Invert(), kOutside, G4TrackingService::materials, pos(), CLHEP::HepRotation::rotateX(), and CLHEP::HepRotation::rotateY().
Member Data Documentation
G4UIcmdWithAString* DicomIntersectVolume::fG4VolumeCmd private
Definition at line 72 of file DicomIntersectVolume.hh.
View newest version in sPHENIX GitHub at line 72 of file DicomIntersectVolume.hh
Referenced by DicomIntersectVolume(), SetNewValue(), and ~DicomIntersectVolume().
std::ofstream DicomIntersectVolume::fout private
Definition at line 76 of file DicomIntersectVolume.hh.
View newest version in sPHENIX GitHub at line 76 of file DicomIntersectVolume.hh
Referenced by SetNewValue().
G4ThreeVector DicomIntersectVolume::fPhantomMinusCorner private
Definition at line 78 of file DicomIntersectVolume.hh.
View newest version in sPHENIX GitHub at line 78 of file DicomIntersectVolume.hh
G4VSolid* DicomIntersectVolume::fSolid private
Definition at line 74 of file DicomIntersectVolume.hh.
View newest version in sPHENIX GitHub at line 74 of file DicomIntersectVolume.hh
Referenced by BuildG4Solid(), BuildUserSolid(), and SetNewValue().
G4UIcmdWithAString* DicomIntersectVolume::fUserVolumeCmd private
Definition at line 71 of file DicomIntersectVolume.hh.
View newest version in sPHENIX GitHub at line 71 of file DicomIntersectVolume.hh
Referenced by DicomIntersectVolume(), SetNewValue(), and ~DicomIntersectVolume().
G4bool* DicomIntersectVolume::fVoxelIsInside private
Definition at line 80 of file DicomIntersectVolume.hh.
View newest version in sPHENIX GitHub at line 80 of file DicomIntersectVolume.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomIntersectVolume.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/src/DicomIntersectVolume.cc