ECCE @ EIC Software: G4IsotopeProperty Class Reference
G4IsotopeProperty Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4IsotopeProperty.hh>
Public Member Functions
G4IsotopeProperty ()
G4IsotopeProperty (const G4IsotopeProperty &right)
G4IsotopeProperty & operator= (G4IsotopeProperty &right)
G4bool operator== (const G4IsotopeProperty &right) const
G4bool operator!= (const G4IsotopeProperty &right) const
virtual ~G4IsotopeProperty ()
G4int GetAtomicNumber () const
void SetAtomicNumber (G4int Z)
G4int GetAtomicMass () const
void SetAtomicMass (G4int A)
G4int GetiSpin () const
void SetiSpin (G4int J)
G4double GetMagneticMoment () const
void SetMagneticMoment (G4double M)
G4double GetEnergy () const
void SetEnergy (G4double E)
G4int GetIsomerLevel () const
void SetIsomerLevel (G4int level)
G4Ions::G4FloatLevelBase GetFloatLevelBase () const
void SetFloatLevelBase (G4Ions::G4FloatLevelBase flb)
void SetFloatLevelBase (G4int flbIndex)
G4double GetLifeTime () const
void SetLifeTime (G4double T)
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *table)
void DumpInfo () const
Private Attributes
G4int fAtomicNumber
G4int fAtomicMass
G4int fISpin
G4double fEnergy
G4double fLifeTime
G4DecayTable * fDecayTable
G4double fMagneticMoment
G4int fIsomerLevel
G4Ions::G4FloatLevelBase fFloatLevelBase
Detailed Description
Definition at line 44 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 44 of file G4IsotopeProperty.hh
Constructor & Destructor Documentation
G4IsotopeProperty::G4IsotopeProperty ()
Definition at line 47 of file G4IsotopeProperty.cc.
View newest version in sPHENIX GitHub at line 47 of file G4IsotopeProperty.cc
G4IsotopeProperty::G4IsotopeProperty (const G4IsotopeProperty & right)
Definition at line 65 of file G4IsotopeProperty.cc.
View newest version in sPHENIX GitHub at line 65 of file G4IsotopeProperty.cc
G4IsotopeProperty::~G4IsotopeProperty () virtual
Definition at line 59 of file G4IsotopeProperty.cc.
View newest version in sPHENIX GitHub at line 59 of file G4IsotopeProperty.cc
References fDecayTable.
Member Function Documentation
void G4IsotopeProperty::DumpInfo () const
Definition at line 118 of file G4IsotopeProperty.cc.
View newest version in sPHENIX GitHub at line 118 of file G4IsotopeProperty.cc
References G4DecayTable::DumpInfo(), fAtomicMass, fAtomicNumber, fDecayTable, fEnergy, fFloatLevelBase, fIsomerLevel, fISpin, fLifeTime, G4Ions::FloatLevelBaseChar(), fMagneticMoment, G4cout, G4endl, keV, MeV, ns, and tesla.
Referenced by G4VIsotopeTable::DumpTable().
G4int G4IsotopeProperty::GetAtomicMass () const inline
Definition at line 133 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 133 of file G4IsotopeProperty.hh
References fAtomicMass.
Referenced by G4IsotopeMagneticMomentTable::FindIsotope(), G4IsotopeMagneticMomentTable::GetIsotope(), G4IsotopeMagneticMomentTable::GetIsotopeByIsoLvl(), and G4IonTable::PreloadNuclide().
G4int G4IsotopeProperty::GetAtomicNumber () const inline
Definition at line 121 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 121 of file G4IsotopeProperty.hh
References fAtomicNumber.
Referenced by G4IsotopeMagneticMomentTable::FindIsotope(), G4IsotopeMagneticMomentTable::GetIsotope(), G4IsotopeMagneticMomentTable::GetIsotopeByIsoLvl(), and G4IonTable::PreloadNuclide().
G4DecayTable * G4IsotopeProperty::GetDecayTable () const inline
Definition at line 204 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 204 of file G4IsotopeProperty.hh
References fDecayTable.
Referenced by G4IonTable::CreateIon().
G4double G4IsotopeProperty::GetEnergy () const inline
Definition at line 169 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 169 of file G4IsotopeProperty.hh
References fEnergy.
Referenced by G4IonTable::CreateIon(), G4IsotopeMagneticMomentTable::FindIsotope(), G4IsotopeMagneticMomentTable::GetIsotope(), G4NuclideTable::GetIsotope(), G4IonTable::GetNucleusMass(), and G4IonTable::PreloadNuclide().
G4Ions::G4FloatLevelBase G4IsotopeProperty::GetFloatLevelBase () const inline
Definition at line 216 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 216 of file G4IsotopeProperty.hh
References fFloatLevelBase.
G4int G4IsotopeProperty::GetIsomerLevel () const inline
Definition at line 181 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 181 of file G4IsotopeProperty.hh
References fIsomerLevel.
Referenced by G4IonTable::CreateIon(), G4IsotopeMagneticMomentTable::FindIsotope(), and G4IsotopeMagneticMomentTable::GetIsotopeByIsoLvl().
G4int G4IsotopeProperty::GetiSpin () const inline
Definition at line 145 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 145 of file G4IsotopeProperty.hh
References fISpin.
Referenced by G4IonTable::CreateIon().
G4double G4IsotopeProperty::GetLifeTime () const inline
Definition at line 192 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 192 of file G4IsotopeProperty.hh
References fLifeTime.
Referenced by G4IonTable::CreateIon(), and G4IonTable::GetLifeTime().
G4double G4IsotopeProperty::GetMagneticMoment () const inline
Definition at line 157 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 157 of file G4IsotopeProperty.hh
References fMagneticMoment.
Referenced by G4IonTable::CreateIon().
G4bool G4IsotopeProperty::operator!= (const G4IsotopeProperty & right) const
Definition at line 113 of file G4IsotopeProperty.cc.
View newest version in sPHENIX GitHub at line 113 of file G4IsotopeProperty.cc
References right.
G4IsotopeProperty & G4IsotopeProperty::operator= (G4IsotopeProperty & right)
Definition at line 80 of file G4IsotopeProperty.cc.
View newest version in sPHENIX GitHub at line 80 of file G4IsotopeProperty.cc
References fAtomicMass, fAtomicNumber, fDecayTable, fEnergy, fFloatLevelBase, fIsomerLevel, fISpin, fLifeTime, and fMagneticMoment.
G4bool G4IsotopeProperty::operator== (const G4IsotopeProperty & right) const
Definition at line 99 of file G4IsotopeProperty.cc.
View newest version in sPHENIX GitHub at line 99 of file G4IsotopeProperty.cc
References fAtomicMass, fAtomicNumber, fEnergy, fFloatLevelBase, fIsomerLevel, fISpin, fLifeTime, and fMagneticMoment.
void G4IsotopeProperty::SetAtomicMass (G4int A) inline
Definition at line 139 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 139 of file G4IsotopeProperty.hh
References A(), and fAtomicMass.
Referenced by G4NuclideTable::AddState(), G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable(), and G4NuclideTable::GenerateNuclide().
void G4IsotopeProperty::SetAtomicNumber (G4int Z) inline
Definition at line 127 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 127 of file G4IsotopeProperty.hh
References fAtomicNumber, and Z.
Referenced by G4NuclideTable::AddState(), G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable(), and G4NuclideTable::GenerateNuclide().
void G4IsotopeProperty::SetDecayTable (G4DecayTable * table) inline
Definition at line 210 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 210 of file G4IsotopeProperty.hh
References fDecayTable.
Referenced by G4NuclideTable::AddState(), and G4NuclideTable::GenerateNuclide().
void G4IsotopeProperty::SetEnergy (G4double E) inline
Definition at line 175 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 175 of file G4IsotopeProperty.hh
References E, and fEnergy.
Referenced by G4NuclideTable::AddState(), G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable(), and G4NuclideTable::GenerateNuclide().
void G4IsotopeProperty::SetFloatLevelBase (G4Ions::G4FloatLevelBase flb) inline
Definition at line 222 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 222 of file G4IsotopeProperty.hh
References fFloatLevelBase.
Referenced by G4NuclideTable::AddState(), and G4NuclideTable::GenerateNuclide().
void G4IsotopeProperty::SetFloatLevelBase (G4int flbIndex) inline
Definition at line 228 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 228 of file G4IsotopeProperty.hh
References fFloatLevelBase, and G4Ions::FloatLevelBase().
void G4IsotopeProperty::SetIsomerLevel (G4int level) inline
Definition at line 186 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 186 of file G4IsotopeProperty.hh
References fIsomerLevel.
Referenced by G4NuclideTable::AddState(), G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable(), and G4NuclideTable::GenerateNuclide().
void G4IsotopeProperty::SetiSpin (G4int J) inline
Definition at line 151 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 151 of file G4IsotopeProperty.hh
References fISpin.
Referenced by G4NuclideTable::AddState(), G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable(), and G4NuclideTable::GenerateNuclide().
void G4IsotopeProperty::SetLifeTime (G4double T) inline
Definition at line 198 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 198 of file G4IsotopeProperty.hh
References fLifeTime, and T.
Referenced by G4NuclideTable::AddState(), and G4NuclideTable::GenerateNuclide().
void G4IsotopeProperty::SetMagneticMoment (G4double M) inline
Definition at line 163 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 163 of file G4IsotopeProperty.hh
References fMagneticMoment.
Referenced by G4NuclideTable::AddState(), G4IsotopeMagneticMomentTable::G4IsotopeMagneticMomentTable(), and G4NuclideTable::GenerateNuclide().
Member Data Documentation
G4int G4IsotopeProperty::fAtomicMass private
Definition at line 110 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 110 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetAtomicMass(), operator=(), operator==(), and SetAtomicMass().
G4int G4IsotopeProperty::fAtomicNumber private
Definition at line 109 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 109 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetAtomicNumber(), operator=(), operator==(), and SetAtomicNumber().
G4DecayTable* G4IsotopeProperty::fDecayTable private
Definition at line 114 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 114 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetDecayTable(), operator=(), SetDecayTable(), and ~G4IsotopeProperty().
G4double G4IsotopeProperty::fEnergy private
Definition at line 112 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 112 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetEnergy(), operator=(), operator==(), and SetEnergy().
G4Ions::G4FloatLevelBase G4IsotopeProperty::fFloatLevelBase private
Definition at line 117 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 117 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetFloatLevelBase(), operator=(), operator==(), and SetFloatLevelBase().
G4int G4IsotopeProperty::fIsomerLevel private
Definition at line 116 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 116 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetIsomerLevel(), operator=(), operator==(), and SetIsomerLevel().
G4int G4IsotopeProperty::fISpin private
Definition at line 111 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 111 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetiSpin(), operator=(), operator==(), and SetiSpin().
G4double G4IsotopeProperty::fLifeTime private
Definition at line 113 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 113 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetLifeTime(), operator=(), operator==(), and SetLifeTime().
G4double G4IsotopeProperty::fMagneticMoment private
Definition at line 115 of file G4IsotopeProperty.hh.
View newest version in sPHENIX GitHub at line 115 of file G4IsotopeProperty.hh
Referenced by DumpInfo(), GetMagneticMoment(), operator=(), operator==(), and SetMagneticMoment().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4IsotopeProperty.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4IsotopeProperty.cc