ECCE @ EIC Software: G4LatticeManager Class Reference
G4LatticeManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4LatticeManager.hh>
Public Member Functions
void SetVerboseLevel (G4int vb)
void Reset ()
G4bool RegisterLattice (G4VPhysicalVolume *, G4LatticePhysical *)
G4bool RegisterLattice (G4VPhysicalVolume *, G4LatticeLogical *)
G4bool RegisterLattice (G4Material *, G4LatticeLogical *)
G4LatticeLogical * LoadLattice (G4Material *, const G4String &latDir)
G4LatticeLogical * GetLattice (G4Material *) const
G4bool HasLattice (G4Material *) const
G4LatticePhysical * LoadLattice (G4VPhysicalVolume *, const G4String &latDir)
G4LatticePhysical * GetLattice (G4VPhysicalVolume *) const
G4bool HasLattice (G4VPhysicalVolume *) const
G4double MapKtoV (G4VPhysicalVolume *, G4int, const G4ThreeVector &) const
G4ThreeVector MapKtoVDir (G4VPhysicalVolume *, G4int, const G4ThreeVector &) const
Static Public Member Functions
static G4LatticeManager * GetLatticeManager ()
Protected Types
typedef std::map< G4Material
*, G4LatticeLogical * > LatticeMatMap
typedef std::set
< G4LatticeLogical * > LatticeLogReg
typedef std::map
< G4VPhysicalVolume
*, G4LatticePhysical * > LatticeVolMap
typedef std::set
< G4LatticePhysical * > LatticePhyReg
Protected Member Functions
void Clear ()
Protected Attributes
G4int verboseLevel
LatticeLogReg fLLattices
LatticeMatMap fLLatticeList
LatticePhyReg fPLattices
LatticeVolMap fPLatticeList
Private Member Functions
G4LatticeManager ()
virtual ~G4LatticeManager ()
Static Private Attributes
static G4LatticeManager * fLM = 0
Detailed Description
Definition at line 47 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 47 of file G4LatticeManager.hh
Member Typedef Documentation
typedef std::set<G4LatticeLogical*> G4LatticeManager::LatticeLogReg protected
Definition at line 89 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 89 of file G4LatticeManager.hh
typedef std::map<G4Material*, G4LatticeLogical*> G4LatticeManager::LatticeMatMap protected
Definition at line 88 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 88 of file G4LatticeManager.hh
typedef std::set<G4LatticePhysical*> G4LatticeManager::LatticePhyReg protected
Definition at line 95 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 95 of file G4LatticeManager.hh
typedef std::map<G4VPhysicalVolume*, G4LatticePhysical*> G4LatticeManager::LatticeVolMap protected
Definition at line 94 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 94 of file G4LatticeManager.hh
Constructor & Destructor Documentation
G4LatticeManager::G4LatticeManager () private
Definition at line 53 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 53 of file G4LatticeManager.cc
References Clear().
Referenced by GetLatticeManager().
G4LatticeManager::~G4LatticeManager () private virtual
Definition at line 57 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 57 of file G4LatticeManager.cc
References Reset().
Member Function Documentation
void G4LatticeManager::Clear () protected
Definition at line 79 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 79 of file G4LatticeManager.cc
References fLLatticeList, fLLattices, fPLatticeList, and fPLattices.
Referenced by G4LatticeManager(), and Reset().
G4LatticeLogical * G4LatticeManager::GetLattice (G4Material * Mat) const
Definition at line 209 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 209 of file G4LatticeManager.cc
References fLLatticeList, G4cerr, G4cout, G4endl, G4Material::GetName(), and verboseLevel.
Referenced by MapKtoV(), MapKtoVDir(), and G4VPhononProcess::StartTracking().
G4LatticePhysical * G4LatticeManager::GetLattice (G4VPhysicalVolume * Vol) const
Definition at line 228 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 228 of file G4LatticeManager.cc
References fPLatticeList, G4cerr, G4cout, G4endl, G4VPhysicalVolume::GetName(), and verboseLevel.
G4LatticeManager * G4LatticeManager::GetLatticeManager () static
Definition at line 89 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 89 of file G4LatticeManager.cc
References fLM, G4LatticeManager(), and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by XPhononStackingAction::ClassifyNewTrack(), XDetectorConstruction::SetupGeometry(), and G4VPhononProcess::StartTracking().
G4bool G4LatticeManager::HasLattice (G4Material * Mat) const
Definition at line 254 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 254 of file G4LatticeManager.cc
References fLLatticeList.
G4bool G4LatticeManager::HasLattice (G4VPhysicalVolume * Vol) const
Definition at line 248 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 248 of file G4LatticeManager.cc
References fPLatticeList.
G4LatticeLogical * G4LatticeManager::LoadLattice (G4Material * Mat, const G4String & latDir)
Definition at line 122 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 122 of file G4LatticeManager.cc
References G4cerr, G4cout, G4endl, G4Material::GetName(), G4LatticeReader::MakeLattice(), RegisterLattice(), and verboseLevel.
Referenced by LoadLattice(), and XDetectorConstruction::SetupGeometry().
G4LatticePhysical * G4LatticeManager::LoadLattice (G4VPhysicalVolume * Vol, const G4String & latDir)
Definition at line 144 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 144 of file G4LatticeManager.cc
References G4cout, G4endl, G4VPhysicalVolume::GetFrameRotation(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), G4VPhysicalVolume::GetName(), LoadLattice(), RegisterLattice(), and verboseLevel.
G4double G4LatticeManager::MapKtoV (G4VPhysicalVolume * Vol, G4int polarizationState, const G4ThreeVector & k) const
Definition at line 264 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 264 of file G4LatticeManager.cc
References G4cout, G4endl, GetLattice(), m, G4LatticePhysical::MapKtoV(), and verboseLevel.
Referenced by XPhononStackingAction::ClassifyNewTrack().
G4ThreeVector G4LatticeManager::MapKtoVDir (G4VPhysicalVolume * Vol, G4int polarizationState, const G4ThreeVector & k) const
Definition at line 282 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 282 of file G4LatticeManager.cc
References G4cout, G4endl, GetLattice(), G4LatticePhysical::MapKtoVDir(), CLHEP::Hep3Vector::unit(), and verboseLevel.
Referenced by XPhononStackingAction::ClassifyNewTrack().
G4bool G4LatticeManager::RegisterLattice (G4VPhysicalVolume * Vol, G4LatticePhysical * Lat)
Definition at line 171 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 171 of file G4LatticeManager.cc
References fPLatticeList, fPLattices, G4cout, G4endl, G4TemplateAutoLock< _Mutex_t >::unlock(), and verboseLevel.
Referenced by LoadLattice(), RegisterLattice(), and XDetectorConstruction::SetupGeometry().
G4bool G4LatticeManager::RegisterLattice (G4VPhysicalVolume * Vol, G4LatticeLogical * LLat)
Definition at line 194 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 194 of file G4LatticeManager.cc
References G4VPhysicalVolume::GetFrameRotation(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), and RegisterLattice().
G4bool G4LatticeManager::RegisterLattice (G4Material * Mat, G4LatticeLogical * Lat)
Definition at line 102 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 102 of file G4LatticeManager.cc
References fLLatticeList, fLLattices, G4cout, G4endl, G4TemplateAutoLock< _Mutex_t >::unlock(), and verboseLevel.
void G4LatticeManager::Reset ()
Definition at line 63 of file G4LatticeManager.cc.
View newest version in sPHENIX GitHub at line 63 of file G4LatticeManager.cc
References Clear(), fLLattices, fPLattices, and Acts::UnitConstants::pm.
Referenced by ~G4LatticeManager().
void G4LatticeManager::SetVerboseLevel (G4int vb) inline
Definition at line 54 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 54 of file G4LatticeManager.hh
References verboseLevel.
Member Data Documentation
LatticeMatMap G4LatticeManager::fLLatticeList protected
Definition at line 92 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 92 of file G4LatticeManager.hh
Referenced by Clear(), GetLattice(), HasLattice(), and RegisterLattice().
LatticeLogReg G4LatticeManager::fLLattices protected
Definition at line 91 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 91 of file G4LatticeManager.hh
Referenced by Clear(), RegisterLattice(), and Reset().
G4LatticeManager * G4LatticeManager::fLM = 0 static private
Definition at line 49 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 49 of file G4LatticeManager.hh
Referenced by GetLatticeManager().
LatticeVolMap G4LatticeManager::fPLatticeList protected
Definition at line 98 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 98 of file G4LatticeManager.hh
Referenced by Clear(), GetLattice(), HasLattice(), and RegisterLattice().
LatticePhyReg G4LatticeManager::fPLattices protected
Definition at line 97 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 97 of file G4LatticeManager.hh
Referenced by Clear(), RegisterLattice(), and Reset().
G4int G4LatticeManager::verboseLevel protected
Definition at line 86 of file G4LatticeManager.hh.
View newest version in sPHENIX GitHub at line 86 of file G4LatticeManager.hh
Referenced by GetLattice(), LoadLattice(), MapKtoV(), MapKtoVDir(), RegisterLattice(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4LatticeManager.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/src/G4LatticeManager.cc