ECCE @ EIC Software: G4VUserChemistryList Class Reference
G4VUserChemistryList Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4VUserChemistryList.hh>
Public Member Functions
G4VUserChemistryList (bool flag=true)
virtual ~G4VUserChemistryList ()
bool IsPhysicsConstructor ()
void ThisIsAPhysicsConstructor (bool flag=true)
virtual void ConstructMolecule ()
virtual void ConstructProcess ()
virtual void ConstructDissociationChannels ()
virtual void ConstructReactionTable (G4DNAMolecularReactionTable *reactionTable)=0
virtual void ConstructTimeStepModel (G4DNAMolecularReactionTable *reactionTable)=0
void BuildPhysicsTable ()
Protected Member Functions
void RegisterTimeStepModel (G4VITStepModel *timeStepModel, double startingTime=0)
void BuildPhysicsTable (G4MoleculeDefinition *)
Protected Attributes
int verboseLevel
bool fIsPhysicsConstructor
Detailed Description
Definition at line 53 of file G4VUserChemistryList.hh.
View newest version in sPHENIX GitHub at line 53 of file G4VUserChemistryList.hh
Constructor & Destructor Documentation
G4VUserChemistryList::G4VUserChemistryList (bool flag = true)
Definition at line 41 of file G4VUserChemistryList.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VUserChemistryList.cc
References verboseLevel.
G4VUserChemistryList::~G4VUserChemistryList () virtual
Definition at line 47 of file G4VUserChemistryList.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VUserChemistryList.cc
References G4DNAChemistryManager::Deregister(), and G4DNAChemistryManager::GetInstanceIfExists().
Member Function Documentation
void G4VUserChemistryList::BuildPhysicsTable ()
Definition at line 62 of file G4VUserChemistryList.cc.
View newest version in sPHENIX GitHub at line 62 of file G4VUserChemistryList.cc
References G4MoleculeTable::GetDefintionIterator(), G4MoleculeTable::Instance(), G4MoleculeIterator< MOLECULE >::reset(), and G4MoleculeIterator< MOLECULE >::value().
void G4VUserChemistryList::BuildPhysicsTable (G4MoleculeDefinition * moleculeDef) protected
Definition at line 77 of file G4VUserChemistryList.cc.
View newest version in sPHENIX GitHub at line 77 of file G4VUserChemistryList.cc
References FatalException, G4cout, G4endl, G4Exception(), G4ParticleDefinition::GetMasterProcessManager(), G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetProcessList(), G4ParticleDefinition::GetProcessManager(), G4ProcessVector::size(), and verboseLevel.
virtual void G4VUserChemistryList::ConstructDissociationChannels () inline virtual
Reimplemented in G4EmDNAChemistry_option2, G4EmDNAChemistry, and G4EmDNAChemistry_option1.
Definition at line 85 of file G4VUserChemistryList.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VUserChemistryList.hh
virtual void G4VUserChemistryList::ConstructMolecule () inline virtual
Reimplemented in G4EmDNAChemistry_option2, G4EmDNAChemistry, and G4EmDNAChemistry_option1.
Definition at line 74 of file G4VUserChemistryList.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VUserChemistryList.hh
virtual void G4VUserChemistryList::ConstructProcess (void) inline virtual
Reimplemented in G4EmDNAChemistry_option2, G4EmDNAChemistry, and G4EmDNAChemistry_option1.
Definition at line 78 of file G4VUserChemistryList.hh.
View newest version in sPHENIX GitHub at line 78 of file G4VUserChemistryList.hh
virtual void G4VUserChemistryList::ConstructReactionTable (G4DNAMolecularReactionTable * reactionTable) pure virtual
Implemented in G4EmDNAChemistry_option2, G4EmDNAChemistry, and G4EmDNAChemistry_option1.
virtual void G4VUserChemistryList::ConstructTimeStepModel (G4DNAMolecularReactionTable * reactionTable) pure virtual
Implemented in G4EmDNAChemistry_option2, G4EmDNAChemistry, and G4EmDNAChemistry_option1.
bool G4VUserChemistryList::IsPhysicsConstructor () inline
Definition at line 61 of file G4VUserChemistryList.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VUserChemistryList.hh
References fIsPhysicsConstructor.
void G4VUserChemistryList::RegisterTimeStepModel (G4VITStepModel * timeStepModel, double startingTime = 0) protected
Definition at line 56 of file G4VUserChemistryList.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VUserChemistryList.cc
References G4VScheduler::Instance(), and G4VScheduler::RegisterModel().
Referenced by G4EmDNAChemistry::ConstructTimeStepModel(), G4EmDNAChemistry_option1::ConstructTimeStepModel(), and G4EmDNAChemistry_option2::ConstructTimeStepModel().
void G4VUserChemistryList::ThisIsAPhysicsConstructor (bool flag = true) inline
Definition at line 66 of file G4VUserChemistryList.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VUserChemistryList.hh
References fIsPhysicsConstructor.
Member Data Documentation
bool G4VUserChemistryList::fIsPhysicsConstructor protected
Definition at line 100 of file G4VUserChemistryList.hh.
View newest version in sPHENIX GitHub at line 100 of file G4VUserChemistryList.hh
Referenced by IsPhysicsConstructor(), and ThisIsAPhysicsConstructor().
int G4VUserChemistryList::verboseLevel protected
Definition at line 99 of file G4VUserChemistryList.hh.
View newest version in sPHENIX GitHub at line 99 of file G4VUserChemistryList.hh
Referenced by BuildPhysicsTable(), and G4VUserChemistryList().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4VUserChemistryList.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4VUserChemistryList.cc