ECCE @ EIC Software: G4DecayTableMessenger Class Reference
G4DecayTableMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/management/include/G4DecayTableMessenger.hh>
Public Member Functions
G4DecayTableMessenger (G4ParticleTable *pTable=0)
virtual ~G4DecayTableMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
virtual G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4DecayTableMessenger (const G4DecayTableMessenger &)
G4DecayTableMessenger & operator= (const G4DecayTableMessenger &)
G4ParticleDefinition * SetCurrentParticle ()
Private Attributes
G4ParticleTable * theParticleTable
G4ParticleDefinition * currentParticle
G4DecayTable * currentDecayTable
G4int idxCurrentChannel
G4VDecayChannel * currentChannel
G4UIdirectory * thisDirectory
G4UIcmdWithoutParameter * dumpCmd
G4UIcmdWithAnInteger * selectCmd
G4UIcmdWithADouble * brCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 66 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 66 of file G4DecayTableMessenger.hh
Constructor & Destructor Documentation
G4DecayTableMessenger::G4DecayTableMessenger (G4ParticleTable * pTable = 0)
Definition at line 57 of file G4DecayTableMessenger.cc.
View newest version in sPHENIX GitHub at line 57 of file G4DecayTableMessenger.cc
References brCmd, currentChannel, currentParticle, dumpCmd, G4ParticleTable::GetParticleTable(), selectCmd, G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcommand::SetRange(), theParticleTable, and thisDirectory.
G4DecayTableMessenger::~G4DecayTableMessenger () virtual
Definition at line 97 of file G4DecayTableMessenger.cc.
View newest version in sPHENIX GitHub at line 97 of file G4DecayTableMessenger.cc
References brCmd, dumpCmd, selectCmd, and thisDirectory.
G4DecayTableMessenger::G4DecayTableMessenger (const G4DecayTableMessenger &) inline private
Definition at line 76 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4DecayTableMessenger.hh
Member Function Documentation
G4String G4DecayTableMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 185 of file G4DecayTableMessenger.cc.
View newest version in sPHENIX GitHub at line 185 of file G4DecayTableMessenger.cc
References brCmd, G4UIcommand::ConvertToString(), currentChannel, G4VDecayChannel::GetBR(), idxCurrentChannel, selectCmd, and SetCurrentParticle().
G4DecayTableMessenger& G4DecayTableMessenger::operator= (const G4DecayTableMessenger &) inline private
Definition at line 77 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4DecayTableMessenger.hh
G4ParticleDefinition * G4DecayTableMessenger::SetCurrentParticle () private
Definition at line 148 of file G4DecayTableMessenger.cc.
View newest version in sPHENIX GitHub at line 148 of file G4DecayTableMessenger.cc
References currentChannel, currentDecayTable, currentParticle, G4ParticleTable::FindParticle(), G4UImanager::GetCurrentStringValue(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4ParticleDefinition::GetParticleName(), G4UImanager::GetUIpointer(), idxCurrentChannel, and theParticleTable.
Referenced by GetCurrentValue(), and SetNewValue().
void G4DecayTableMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 105 of file G4DecayTableMessenger.cc.
View newest version in sPHENIX GitHub at line 105 of file G4DecayTableMessenger.cc
References brCmd, currentChannel, currentDecayTable, dumpCmd, G4DecayTable::DumpInfo(), G4cout, G4endl, G4DecayTable::GetDecayChannel(), G4UIcmdWithADouble::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), idxCurrentChannel, selectCmd, G4VDecayChannel::SetBR(), and SetCurrentParticle().
Member Data Documentation
G4UIcmdWithADouble* G4DecayTableMessenger::brCmd private
Definition at line 90 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 90 of file G4DecayTableMessenger.hh
Referenced by G4DecayTableMessenger(), GetCurrentValue(), SetNewValue(), and ~G4DecayTableMessenger().
G4VDecayChannel* G4DecayTableMessenger::currentChannel private
Definition at line 85 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4DecayTableMessenger.hh
Referenced by G4DecayTableMessenger(), GetCurrentValue(), SetCurrentParticle(), and SetNewValue().
G4DecayTable* G4DecayTableMessenger::currentDecayTable private
Definition at line 83 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4DecayTableMessenger.hh
Referenced by SetCurrentParticle(), and SetNewValue().
G4ParticleDefinition* G4DecayTableMessenger::currentParticle private
Definition at line 82 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4DecayTableMessenger.hh
Referenced by G4DecayTableMessenger(), and SetCurrentParticle().
G4UIcmdWithoutParameter* G4DecayTableMessenger::dumpCmd private
Definition at line 88 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4DecayTableMessenger.hh
Referenced by G4DecayTableMessenger(), SetNewValue(), and ~G4DecayTableMessenger().
G4int G4DecayTableMessenger::idxCurrentChannel private
Definition at line 84 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4DecayTableMessenger.hh
Referenced by GetCurrentValue(), SetCurrentParticle(), and SetNewValue().
G4UIcmdWithAnInteger* G4DecayTableMessenger::selectCmd private
Definition at line 89 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4DecayTableMessenger.hh
Referenced by G4DecayTableMessenger(), GetCurrentValue(), SetNewValue(), and ~G4DecayTableMessenger().
G4ParticleTable* G4DecayTableMessenger::theParticleTable private
Definition at line 81 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4DecayTableMessenger.hh
Referenced by G4DecayTableMessenger(), and SetCurrentParticle().
G4UIdirectory* G4DecayTableMessenger::thisDirectory private
Definition at line 87 of file G4DecayTableMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4DecayTableMessenger.hh
Referenced by G4DecayTableMessenger(), and ~G4DecayTableMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/management/include/G4DecayTableMessenger.hh
geant4/tree/geant4-10.6-release/source/particles/management/src/G4DecayTableMessenger.cc