ECCE @ EIC Software: G4VNestedParameterisation Class Reference
G4VNestedParameterisation Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VNestedParameterisation.hh>
Public Member Functions
G4VNestedParameterisation ()
virtual ~G4VNestedParameterisation ()
virtual G4Material * ComputeMaterial (G4VPhysicalVolume *currentVol, const G4int repNo, const G4VTouchable *parentTouch=nullptr)=0
virtual G4int GetNumberOfMaterials () const =0
virtual G4Material * GetMaterial (G4int idx) const =0
virtual void ComputeTransformation (const G4int no, G4VPhysicalVolume *currentPV) const =0
virtual G4VSolid * ComputeSolid (const G4int no, G4VPhysicalVolume *thisVol)
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
Public Member Functions inherited from G4VVolumeMaterialScanner
G4VVolumeMaterialScanner ()
virtual ~G4VVolumeMaterialScanner ()
Detailed Description
Definition at line 75 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VNestedParameterisation.hh
Constructor & Destructor Documentation
G4VNestedParameterisation::G4VNestedParameterisation ()
Definition at line 37 of file G4VNestedParameterisation.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VNestedParameterisation.cc
G4VNestedParameterisation::~G4VNestedParameterisation () virtual
Definition at line 43 of file G4VNestedParameterisation.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VNestedParameterisation.cc
Member Function Documentation
virtual void G4VNestedParameterisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 108 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 108 of file G4VNestedParameterisation.hh
Referenced by G4GMocrenFileSceneHandler::AddSolid().
virtual void G4VNestedParameterisation::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 112 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 112 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 116 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 116 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 120 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 120 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 124 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 124 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 128 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 128 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 132 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 132 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 136 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 136 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 140 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 140 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 144 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 144 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 148 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 148 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 152 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 152 of file G4VNestedParameterisation.hh
virtual void G4VNestedParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline virtual
Reimplemented from G4VPVParameterisation.
Reimplemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Definition at line 156 of file G4VNestedParameterisation.hh.
View newest version in sPHENIX GitHub at line 156 of file G4VNestedParameterisation.hh
virtual G4Material* G4VNestedParameterisation::ComputeMaterial (G4VPhysicalVolume * currentVol, const G4int repNo, const G4VTouchable * parentTouch = nullptr) pure virtual
Implemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), and ComputeMaterial().
G4Material * G4VNestedParameterisation::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = nullptr) virtual
Reimplemented from G4VPVParameterisation.
Definition at line 64 of file G4VNestedParameterisation.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VNestedParameterisation.cc
References ComputeMaterial().
G4VSolid * G4VNestedParameterisation::ComputeSolid (const G4int no, G4VPhysicalVolume * thisVol) virtual
Reimplemented from G4VPVParameterisation.
Definition at line 47 of file G4VNestedParameterisation.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VNestedParameterisation.cc
References G4VPhysicalVolume::GetLogicalVolume(), and G4LogicalVolume::GetSolid().
virtual void G4VNestedParameterisation::ComputeTransformation (const G4int no, G4VPhysicalVolume * currentPV) const pure virtual
Implements G4VPVParameterisation.
Implemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
Referenced by G4GMocrenFileSceneHandler::AddSolid().
virtual G4Material* G4VNestedParameterisation::GetMaterial (G4int idx) const pure virtual
Implements G4VVolumeMaterialScanner.
Implemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
G4VVolumeMaterialScanner * G4VNestedParameterisation::GetMaterialScanner () virtual
Reimplemented from G4VPVParameterisation.
Definition at line 58 of file G4VNestedParameterisation.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VNestedParameterisation.cc
virtual G4int G4VNestedParameterisation::GetNumberOfMaterials () const pure virtual
Implements G4VVolumeMaterialScanner.
Implemented in RE02NestedPhantomParameterisation, and DicomNestedPhantomParameterisation.
G4bool G4VNestedParameterisation::IsNested () const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 53 of file G4VNestedParameterisation.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VNestedParameterisation.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/management/include/G4VNestedParameterisation.hh
geant4/tree/geant4-10.6-release/source/geometry/management/src/G4VNestedParameterisation.cc