ECCE @ EIC Software: G4Text Class Reference
G4Text Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4Text.hh>
Public Types
enum Layout { left, centre, right }
Public Types inherited from G4VMarker
enum FillStyle { noFill, hashed, filled }
enum SizeType { none, world, screen }
Public Member Functions
G4Text (const G4String &text)
G4Text (const G4String &text, const G4Point3D &position)
G4Text (const G4VMarker &)
G4Text (const G4Text &)
virtual ~G4Text ()
G4Text & operator= (const G4Text &)
G4String GetText () const
Layout GetLayout () const
G4double GetXOffset () const
G4double GetYOffset () const
void SetText (const G4String &text)
void SetLayout (Layout)
void SetOffset (double dx, double dy)
Public Member Functions inherited from G4VMarker
G4VMarker ()
G4VMarker (const G4VMarker &)
G4VMarker (const G4Point3D &position)
virtual ~G4VMarker ()
G4VMarker & operator= (const G4VMarker &)
G4bool operator!= (const G4VMarker &) const
G4Point3D GetPosition () const
SizeType GetSizeType () const
G4double GetWorldSize () const
G4double GetWorldDiameter () const
G4double GetWorldRadius () const
G4double GetScreenSize () const
G4double GetScreenDiameter () const
G4double GetScreenRadius () const
FillStyle GetFillStyle () const
void SetPosition (const G4Point3D &)
void SetSize (SizeType, G4double)
void SetDiameter (SizeType, G4double)
void SetRadius (SizeType, G4double)
void SetWorldSize (G4double)
void SetWorldDiameter (G4double)
void SetWorldRadius (G4double)
void SetScreenSize (G4double)
void SetScreenDiameter (G4double)
void SetScreenRadius (G4double)
void SetFillStyle (FillStyle)
virtual const G4String & GetInfo () const
virtual void SetInfo (const G4String &info)
Public Member Functions inherited from G4Visible
G4Visible ()
G4Visible (const G4Visible &)
G4Visible (const G4VisAttributes *)
virtual ~G4Visible ()
G4Visible & operator= (const G4Visible &)
G4bool operator!= (const G4Visible &right) const
const G4VisAttributes * GetVisAttributes () const
void SetVisAttributes (const G4VisAttributes *)
void SetVisAttributes (const G4VisAttributes &)
Private Attributes
G4String fText
Layout fLayout
G4double fXOffset
G4double fYOffset
Additional Inherited Members
Protected Attributes inherited from G4Visible
const G4VisAttributes * fpVisAttributes
G4bool fAllocatedVisAttributes
Detailed Description
Definition at line 72 of file G4Text.hh.
View newest version in sPHENIX GitHub at line 72 of file G4Text.hh
Member Enumeration Documentation
enum G4Text::Layout
Enumerator:
left
centre
right
Definition at line 76 of file G4Text.hh.
View newest version in sPHENIX GitHub at line 76 of file G4Text.hh
Constructor & Destructor Documentation
G4Text::G4Text (const G4String & text)
Definition at line 33 of file G4Text.cc.
View newest version in sPHENIX GitHub at line 33 of file G4Text.cc
G4Text::G4Text (const G4String & text, const G4Point3D & position)
Definition at line 39 of file G4Text.cc.
View newest version in sPHENIX GitHub at line 39 of file G4Text.cc
G4Text::G4Text (const G4VMarker & marker)
Definition at line 46 of file G4Text.cc.
View newest version in sPHENIX GitHub at line 46 of file G4Text.cc
G4Text::G4Text (const G4Text & text)
Definition at line 53 of file G4Text.cc.
View newest version in sPHENIX GitHub at line 53 of file G4Text.cc
G4Text::~G4Text () virtual
Definition at line 61 of file G4Text.cc.
View newest version in sPHENIX GitHub at line 61 of file G4Text.cc
Member Function Documentation
Layout G4Text::GetLayout () const
Referenced by operator<<().
G4String G4Text::GetText () const
Referenced by G4HepRepFileSceneHandler::AddPrimitive(), G4TextModel::G4TextModel(), and operator<<().
G4double G4Text::GetXOffset () const
Referenced by G4HepRepFileSceneHandler::AddPrimitive(), G4TextModel::G4TextModel(), and operator<<().
G4double G4Text::GetYOffset () const
Referenced by G4HepRepFileSceneHandler::AddPrimitive(), G4TextModel::G4TextModel(), and operator<<().
G4Text & G4Text::operator= (const G4Text & rhs)
Definition at line 63 of file G4Text.cc.
View newest version in sPHENIX GitHub at line 63 of file G4Text.cc
References fLayout, fText, fXOffset, fYOffset, and G4VMarker::operator=().
void G4Text::SetLayout (Layout)
Referenced by G4AxesModel::G4AxesModel(), G4VisCommandSceneAddDate::Date::operator()(), G4VisCommandSceneAddLogo2D::Logo2D::operator()(), G4VisCommandSceneAddText::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
void G4Text::SetOffset (double dx, double dy)
Referenced by G4AxesModel::G4AxesModel(), G4VisCommandSceneAddText::SetNewValue(), and G4VisCommandSceneAddText2D::SetNewValue().
void G4Text::SetText (const G4String & text)
Member Data Documentation
Layout G4Text::fLayout private
Definition at line 97 of file G4Text.hh.
View newest version in sPHENIX GitHub at line 97 of file G4Text.hh
Referenced by operator=().
G4String G4Text::fText private
Definition at line 96 of file G4Text.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Text.hh
Referenced by operator=().
G4double G4Text::fXOffset private
Definition at line 98 of file G4Text.hh.
View newest version in sPHENIX GitHub at line 98 of file G4Text.hh
Referenced by operator=().
G4double G4Text::fYOffset private
Definition at line 98 of file G4Text.hh.
View newest version in sPHENIX GitHub at line 98 of file G4Text.hh
Referenced by operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4Text.hh
geant4/tree/geant4-10.6-release/source/graphics_reps/src/G4Text.cc