ECCE @ EIC Software: G4PhysicsBuilderInterface Class Reference
G4PhysicsBuilderInterface Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4PhysicsBuilderInterface.hh>
Public Member Functions
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMinEnergy (G4double)
virtual void SetMaxEnergy (G4double)
Detailed Description
Definition at line 43 of file G4PhysicsBuilderInterface.hh.
View newest version in sPHENIX GitHub at line 43 of file G4PhysicsBuilderInterface.hh
Constructor & Destructor Documentation
G4PhysicsBuilderInterface::G4PhysicsBuilderInterface () default
virtual G4PhysicsBuilderInterface::~G4PhysicsBuilderInterface () inline virtual
Definition at line 46 of file G4PhysicsBuilderInterface.hh.
View newest version in sPHENIX GitHub at line 46 of file G4PhysicsBuilderInterface.hh
Member Function Documentation
virtual void G4PhysicsBuilderInterface::Build (void) inline virtual
Reimplemented in G4HyperonFTFPBuilder, G4NeutronBuilder, G4KaonBuilder, G4ProtonBuilder, G4PiKBuilder, G4AntiBarionBuilder, G4DeuteronBuilder, G4PionBuilder, G4TritonBuilder, G4He3Builder, and G4AlphaBuilder.
Definition at line 47 of file G4PhysicsBuilderInterface.hh.
View newest version in sPHENIX GitHub at line 47 of file G4PhysicsBuilderInterface.hh
References FatalException, and G4Exception().
virtual void G4PhysicsBuilderInterface::RegisterMe (G4PhysicsBuilderInterface *) inline virtual
Reimplemented in G4NeutronBuilder, G4KaonBuilder, G4ProtonBuilder, G4PiKBuilder, G4AntiBarionBuilder, G4DeuteronBuilder, G4PionBuilder, G4TritonBuilder, G4He3Builder, and G4AlphaBuilder.
Definition at line 52 of file G4PhysicsBuilderInterface.hh.
View newest version in sPHENIX GitHub at line 52 of file G4PhysicsBuilderInterface.hh
References FatalException, and G4Exception().
Referenced by G4AlphaBuilder::RegisterMe(), G4He3Builder::RegisterMe(), G4AntiBarionBuilder::RegisterMe(), G4PionBuilder::RegisterMe(), G4TritonBuilder::RegisterMe(), G4DeuteronBuilder::RegisterMe(), G4PiKBuilder::RegisterMe(), G4ProtonBuilder::RegisterMe(), G4KaonBuilder::RegisterMe(), and G4NeutronBuilder::RegisterMe().
virtual void G4PhysicsBuilderInterface::SetMaxEnergy (G4double) inline virtual
Reimplemented in G4INCLXXProtonBuilder, G4FTFPPiKBuilder, G4FTFPAntiBarionBuilder, UrQMDNeutronBuilder, UrQMDPiKBuilder, G4FTFPKaonBuilder, G4FTFPNeutronBuilder, HIJINGNeutronBuilder, UrQMDAntiBarionBuilder, G4FTFBinaryKaonBuilder, G4FTFBinaryNeutronBuilder, G4FTFBinaryPionBuilder, G4FTFPPionBuilder, G4NeutronPHPBuilder, G4BertiniPiKBuilder, G4BinaryPiKBuilder, G4FTFBinaryProtonBuilder, G4FTFPProtonBuilder, G4INCLXXNeutronBuilder, G4INCLXXPionBuilder, G4NeutronLENDBuilder, G4BertiniKaonBuilder, G4BertiniPionBuilder, CRMCNeutronBuilder, CRMCPiKBuilder, G4BertiniNeutronBuilder, G4BinaryNeutronBuilder, G4DeuteronPHPBuilder, G4TritonPHPBuilder, G4BinaryPionBuilder, G4He3PHPBuilder, CRMCKaonBuilder, G4BertiniProtonBuilder, G4BinaryAlphaBuilder, G4BinaryDeuteronBuilder, G4BinaryHe3Builder, G4BinaryTritonBuilder, G4BinaryProtonBuilder, CRMCPionBuilder, G4AlphaPHPBuilder, G4ProtonPHPBuilder, CRMCProtonBuilder, HIJINGProtonBuilder, and UrQMDProtonBuilder.
Definition at line 63 of file G4PhysicsBuilderInterface.hh.
View newest version in sPHENIX GitHub at line 63 of file G4PhysicsBuilderInterface.hh
References FatalException, and G4Exception().
virtual void G4PhysicsBuilderInterface::SetMinEnergy (G4double) inline virtual
Reimplemented in G4INCLXXProtonBuilder, G4FTFPPiKBuilder, G4QGSBinaryPiKBuilder, G4QGSPPiKBuilder, G4FTFBinaryPiKBuilder, G4FTFPAntiBarionBuilder, G4QGSBinaryKaonBuilder, G4QGSPKaonBuilder, G4QGSPNeutronBuilder, UrQMDNeutronBuilder, UrQMDPiKBuilder, G4FTFPKaonBuilder, G4FTFPNeutronBuilder, G4QGSBinaryNeutronBuilder, G4QGSPPionBuilder, HIJINGNeutronBuilder, UrQMDAntiBarionBuilder, G4FTFBinaryKaonBuilder, G4FTFBinaryNeutronBuilder, G4QGSBinaryPionBuilder, G4QGSPProtonBuilder, G4FTFBinaryPionBuilder, G4FTFPPionBuilder, G4QGSPLundStrFragmProtonBuilder, G4BertiniPiKBuilder, G4BinaryPiKBuilder, G4FTFBinaryProtonBuilder, G4FTFPProtonBuilder, G4INCLXXNeutronBuilder, G4INCLXXPionBuilder, G4QGSBinaryProtonBuilder, G4BertiniKaonBuilder, G4PrecoNeutronBuilder, G4BertiniPionBuilder, CRMCNeutronBuilder, CRMCPiKBuilder, G4BertiniNeutronBuilder, G4BinaryNeutronBuilder, G4BinaryPionBuilder, CRMCKaonBuilder, G4BertiniProtonBuilder, G4BinaryAlphaBuilder, G4BinaryDeuteronBuilder, G4BinaryHe3Builder, G4BinaryTritonBuilder, G4PrecoProtonBuilder, G4BinaryProtonBuilder, G4DeuteronPHPBuilder, G4TritonPHPBuilder, CRMCPionBuilder, G4He3PHPBuilder, G4NeutronPHPBuilder, G4NeutronLENDBuilder, CRMCProtonBuilder, HIJINGProtonBuilder, UrQMDProtonBuilder, G4AlphaPHPBuilder, and G4ProtonPHPBuilder.
Definition at line 57 of file G4PhysicsBuilderInterface.hh.
View newest version in sPHENIX GitHub at line 57 of file G4PhysicsBuilderInterface.hh
References FatalException, and G4Exception().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/run/include/G4PhysicsBuilderInterface.hh