ECCE @ EIC Software: G4RToEConvForElectron Class Reference
G4RToEConvForElectron Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4RToEConvForElectron.hh>
Public Member Functions
G4RToEConvForElectron ()
virtual ~G4RToEConvForElectron ()
Public Member Functions inherited from G4VRangeToEnergyConverter
G4VRangeToEnergyConverter ()
G4VRangeToEnergyConverter (const G4VRangeToEnergyConverter &right)
G4VRangeToEnergyConverter & operator= (const G4VRangeToEnergyConverter &right)
virtual ~G4VRangeToEnergyConverter ()
G4bool operator== (const G4VRangeToEnergyConverter &right) const
G4bool operator!= (const G4VRangeToEnergyConverter &right) const
virtual G4double Convert (G4double rangeCut, const G4Material *material)
const G4ParticleDefinition * GetParticleType () const
const G4PhysicsTable * GetLossTable () const
virtual void Reset ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
Protected Member Functions
virtual G4double ComputeLoss (G4double AtomicNumber, G4double KineticEnergy)
Protected Member Functions inherited from G4VRangeToEnergyConverter
virtual void BuildLossTable ()
virtual void BuildRangeVector (const G4Material *aMaterial, G4RangeVector *rangeVector)
G4double ConvertCutToKineticEnergy (G4RangeVector *theRangeVector, G4double theCutInLength, size_t materialIndex) const
Protected Attributes
G4double Mass
G4double Z
G4double taul
G4double ionpot
G4double ionpotlog
G4double bremfactor
Protected Attributes inherited from G4VRangeToEnergyConverter
G4double fMaxEnergyCut
const G4ParticleDefinition * theParticle
G4LossTable * theLossTable
G4int NumberOfElements
const G4int TotBin
std::vector< G4RangeVector * > fRangeVectorStore
Additional Inherited Members
Static Public Member Functions inherited from G4VRangeToEnergyConverter
static void SetEnergyRange (G4double lowedge, G4double highedge)
static G4double GetLowEdgeEnergy ()
static G4double GetHighEdgeEnergy ()
static G4double GetMaxEnergyCut ()
static void SetMaxEnergyCut (G4double value)
Protected Types inherited from G4VRangeToEnergyConverter
typedef G4PhysicsTable G4LossTable
typedef G4PhysicsLogVector G4LossVector
typedef G4PhysicsLogVector G4RangeVector
Static Protected Attributes inherited from G4VRangeToEnergyConverter
static G4double LowestEnergy = 0.99e-3*MeV
static G4double HighestEnergy = 100.0e6*MeV
static G4double MaxEnergyCut = 10.0*GeV
Detailed Description
Definition at line 50 of file G4RToEConvForElectron.hh.
View newest version in sPHENIX GitHub at line 50 of file G4RToEConvForElectron.hh
Constructor & Destructor Documentation
G4RToEConvForElectron::G4RToEConvForElectron ()
Definition at line 44 of file G4RToEConvForElectron.cc.
View newest version in sPHENIX GitHub at line 44 of file G4RToEConvForElectron.cc
References G4ParticleTable::FindParticle(), G4cout, G4endl, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4VRangeToEnergyConverter::GetVerboseLevel(), Mass, and G4VRangeToEnergyConverter::theParticle.
G4RToEConvForElectron::~G4RToEConvForElectron () virtual
Definition at line 66 of file G4RToEConvForElectron.cc.
View newest version in sPHENIX GitHub at line 66 of file G4RToEConvForElectron.cc
Member Function Documentation
G4double G4RToEConvForElectron::ComputeLoss (G4double AtomicNumber, G4double KineticEnergy) protected virtual
Implements G4VRangeToEnergyConverter.
Definition at line 74 of file G4RToEConvForElectron.cc.
View newest version in sPHENIX GitHub at line 74 of file G4RToEConvForElectron.cc
References bremfactor, f, GeV, ionpot, ionpotlog, keV, Mass, MeV, t1, t2, taul, source.hepunit::twopi_mc2_rcl2, and Z.
Member Data Documentation
G4double G4RToEConvForElectron::bremfactor protected
Definition at line 71 of file G4RToEConvForElectron.hh.
View newest version in sPHENIX GitHub at line 71 of file G4RToEConvForElectron.hh
Referenced by ComputeLoss().
G4double G4RToEConvForElectron::ionpot protected
Definition at line 69 of file G4RToEConvForElectron.hh.
View newest version in sPHENIX GitHub at line 69 of file G4RToEConvForElectron.hh
Referenced by ComputeLoss().
G4double G4RToEConvForElectron::ionpotlog protected
Definition at line 70 of file G4RToEConvForElectron.hh.
View newest version in sPHENIX GitHub at line 70 of file G4RToEConvForElectron.hh
Referenced by ComputeLoss().
G4double G4RToEConvForElectron::Mass protected
Definition at line 66 of file G4RToEConvForElectron.hh.
View newest version in sPHENIX GitHub at line 66 of file G4RToEConvForElectron.hh
Referenced by ComputeLoss(), and G4RToEConvForElectron().
G4double G4RToEConvForElectron::taul protected
Definition at line 68 of file G4RToEConvForElectron.hh.
View newest version in sPHENIX GitHub at line 68 of file G4RToEConvForElectron.hh
Referenced by ComputeLoss().
G4double G4RToEConvForElectron::Z protected
Definition at line 67 of file G4RToEConvForElectron.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RToEConvForElectron.hh
Referenced by ComputeLoss().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/cuts/include/G4RToEConvForElectron.hh
geant4/tree/geant4-10.6-release/source/processes/cuts/src/G4RToEConvForElectron.cc