ECCE @ EIC Software: G4HCIOcatalog Class Reference
G4HCIOcatalog Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4HCIOcatalog.hh>
Public Member Functions
G4HCIOcatalog ()
virtual ~G4HCIOcatalog ()
void SetVerboseLevel (int v)
void RegisterEntry (G4VHCIOentry *d)
void RegisterHCIOmanager (G4VPHitsCollectionIO *d)
G4VHCIOentry * GetEntry (std::string name)
G4VPHitsCollectionIO * GetHCIOmanager (std::string name)
void PrintEntries ()
std::string CurrentHCIOmanager ()
void PrintHCIOmanager ()
size_t NumberOfHCIOmanager ()
G4VPHitsCollectionIO * GetHCIOmanager (int n)
Static Public Member Functions
static G4HCIOcatalog * GetHCIOcatalog ()
Private Attributes
int m_verbose
HCIOmap theCatalog
HCIOstore theStore
Static Private Attributes
static G4ThreadLocal
G4HCIOcatalog * f_thePointer = 0
Detailed Description
Definition at line 47 of file G4HCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 47 of file G4HCIOcatalog.hh
Constructor & Destructor Documentation
G4HCIOcatalog::G4HCIOcatalog ()
Definition at line 39 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HCIOcatalog.cc
Referenced by GetHCIOcatalog().
virtual G4HCIOcatalog::~G4HCIOcatalog () inline virtual
Definition at line 53 of file G4HCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 53 of file G4HCIOcatalog.hh
Member Function Documentation
std::string G4HCIOcatalog::CurrentHCIOmanager ()
Definition at line 116 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 116 of file G4HCIOcatalog.cc
References it, and theStore.
Referenced by G4PersistencyCenter::CurrentHCIOmanager().
G4VHCIOentry * G4HCIOcatalog::GetEntry (std::string name)
Definition at line 79 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 79 of file G4HCIOcatalog.cc
References G4cout, and theCatalog.
Referenced by G4PersistencyCenter::AddHCIOmanager().
G4HCIOcatalog * G4HCIOcatalog::GetHCIOcatalog () static
Definition at line 44 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 44 of file G4HCIOcatalog.cc
References f_thePointer, and G4HCIOcatalog().
Referenced by G4PersistencyCenter::AddHCIOmanager(), G4HCIOentryT< T >::CreateHCIOmanager(), G4PersistencyCenter::CurrentHCIOmanager(), G4VHCIOentry::G4VHCIOentry(), G4VPHitIO::G4VPHitIO(), G4PersistencyCenter::PrintAll(), and G4PersistencyManager::SetVerboseLevel().
G4VPHitsCollectionIO * G4HCIOcatalog::GetHCIOmanager (std::string name)
Definition at line 92 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 92 of file G4HCIOcatalog.cc
References G4cout, G4endl, and theStore.
Referenced by G4VPHitIO::SetVerboseLevel(), and G4PersistencyManager::SetVerboseLevel().
G4VPHitsCollectionIO * G4HCIOcatalog::GetHCIOmanager (int n)
Definition at line 139 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 139 of file G4HCIOcatalog.cc
References it, and theStore.
size_t G4HCIOcatalog::NumberOfHCIOmanager () inline
Definition at line 84 of file G4HCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 84 of file G4HCIOcatalog.hh
References theStore.
Referenced by G4VPHitIO::SetVerboseLevel(), and G4PersistencyManager::SetVerboseLevel().
void G4HCIOcatalog::PrintEntries ()
Definition at line 105 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 105 of file G4HCIOcatalog.cc
References G4cout, G4endl, it, and theCatalog.
Referenced by G4PersistencyCenter::PrintAll().
void G4HCIOcatalog::PrintHCIOmanager ()
Definition at line 127 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 127 of file G4HCIOcatalog.cc
References G4cout, G4endl, it, and theStore.
Referenced by G4HCIOentryT< T >::CreateHCIOmanager(), and G4PersistencyCenter::PrintAll().
void G4HCIOcatalog::RegisterEntry (G4VHCIOentry * d)
Definition at line 51 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 51 of file G4HCIOcatalog.cc
References d, G4cout, G4endl, G4VHCIOentry::GetName(), m_verbose, and theCatalog.
Referenced by G4VHCIOentry::G4VHCIOentry().
void G4HCIOcatalog::RegisterHCIOmanager (G4VPHitsCollectionIO * d)
Definition at line 65 of file G4HCIOcatalog.cc.
View newest version in sPHENIX GitHub at line 65 of file G4HCIOcatalog.cc
References d, G4cout, G4endl, m_verbose, G4VPHitsCollectionIO::SDname(), and theStore.
Referenced by G4HCIOentryT< T >::CreateHCIOmanager().
void G4HCIOcatalog::SetVerboseLevel (int v) inline
Definition at line 60 of file G4HCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 60 of file G4HCIOcatalog.hh
References m_verbose, and v.
Referenced by G4PersistencyManager::SetVerboseLevel().
Member Data Documentation
G4ThreadLocal G4HCIOcatalog * G4HCIOcatalog::f_thePointer = 0 static private
Definition at line 92 of file G4HCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 92 of file G4HCIOcatalog.hh
Referenced by GetHCIOcatalog().
int G4HCIOcatalog::m_verbose private
Definition at line 91 of file G4HCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 91 of file G4HCIOcatalog.hh
Referenced by RegisterEntry(), RegisterHCIOmanager(), and SetVerboseLevel().
HCIOmap G4HCIOcatalog::theCatalog private
Definition at line 93 of file G4HCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 93 of file G4HCIOcatalog.hh
Referenced by GetEntry(), PrintEntries(), and RegisterEntry().
HCIOstore G4HCIOcatalog::theStore private
Definition at line 94 of file G4HCIOcatalog.hh.
View newest version in sPHENIX GitHub at line 94 of file G4HCIOcatalog.hh
Referenced by CurrentHCIOmanager(), GetHCIOmanager(), NumberOfHCIOmanager(), PrintHCIOmanager(), and RegisterHCIOmanager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4HCIOcatalog.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4HCIOcatalog.cc