ECCE @ EIC Software: G4MicroElecInelasticModel Class Reference
G4MicroElecInelasticModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4MicroElecInelasticModel.hh>
Public Member Functions
G4MicroElecInelasticModel (const G4ParticleDefinition *p=0, const G4String &nam="MicroElecInelasticModel")
virtual ~G4MicroElecInelasticModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual G4double CrossSectionPerVolume (const G4Material *material, const G4ParticleDefinition *p, G4double ekin, G4double emin, G4double emax)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy)
double DifferentialCrossSection (G4ParticleDefinition *aParticleDefinition, G4double k, G4double energyTransfer, G4int shell)
G4double TransferedEnergy (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell, G4double random)
void SelectFasterComputation (G4bool input)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Attributes
G4ParticleChangeForGamma * fParticleChangeForGamma
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Private Types
typedef std::map< G4String,
G4String, std::less< G4String > > MapFile
typedef std::map< G4String,
G4MicroElecCrossSectionDataSet
*, std::less< G4String > > MapData
typedef std::map< double,
std::map< double, double > > TriDimensionMap
typedef std::map< double,
std::vector< double > > VecMap
Private Member Functions
G4double RandomizeEjectedElectronEnergy (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double RandomizeEjectedElectronEnergyFromCumulatedDcs (G4ParticleDefinition *aParticleDefinition, G4double incomingParticleEnergy, G4int shell)
G4double Interpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2)
G4double QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e)
G4int RandomSelect (G4double energy, const G4String &particle)
G4MicroElecInelasticModel & operator= (const G4MicroElecInelasticModel &right)
G4MicroElecInelasticModel (const G4MicroElecInelasticModel &)
Private Attributes
G4bool fasterCode
G4VAtomDeexcitation * fAtomDeexcitation
G4Material * nistSi
std::map< G4String, G4double,
std::less< G4String > > lowEnergyLimit
std::map< G4String, G4double,
std::less< G4String > > highEnergyLimit
G4bool isInitialised
G4int verboseLevel
MapFile tableFile
MapData tableData
G4MicroElecSiStructure SiStructure
TriDimensionMap eDiffCrossSectionData [7]
TriDimensionMap eNrjTransfData [7]
TriDimensionMap pDiffCrossSectionData [7]
TriDimensionMap pNrjTransfData [7]
std::vector< double > eTdummyVec
std::vector< double > pTdummyVec
VecMap eVecm
VecMap pVecm
VecMap eProbaShellMap [7]
VecMap pProbaShellMap [7]
Additional Inherited Members
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Detailed Description
Definition at line 64 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 64 of file G4MicroElecInelasticModel.hh
Member Typedef Documentation
typedef std::map<G4String,G4MicroElecCrossSectionDataSet*,std::less<G4String> > G4MicroElecInelasticModel::MapData private
Definition at line 119 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 119 of file G4MicroElecInelasticModel.hh
typedef std::map<G4String,G4String,std::less<G4String> > G4MicroElecInelasticModel::MapFile private
Definition at line 116 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4MicroElecInelasticModel.hh
typedef std::map<double, std::map<double, double> > G4MicroElecInelasticModel::TriDimensionMap private
Definition at line 145 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 145 of file G4MicroElecInelasticModel.hh
typedef std::map<double, std::vector<double> > G4MicroElecInelasticModel::VecMap private
Definition at line 156 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4MicroElecInelasticModel.hh
Constructor & Destructor Documentation
G4MicroElecInelasticModel::G4MicroElecInelasticModel (const G4ParticleDefinition * p = 0, const G4String & nam = "MicroElecInelasticModel")
Definition at line 62 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 62 of file G4MicroElecInelasticModel.cc
References fasterCode, fAtomDeexcitation, G4NistManager::FindOrBuildMaterial(), fParticleChangeForGamma, G4cout, G4endl, G4NistManager::Instance(), nistSi, G4VEmModel::SetAngularDistribution(), G4VEmModel::SetDeexcitationFlag(), and verboseLevel.
G4MicroElecInelasticModel::~G4MicroElecInelasticModel () virtual
Definition at line 95 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 95 of file G4MicroElecInelasticModel.cc
References eVecm, pos(), pVecm, and tableData.
G4MicroElecInelasticModel::G4MicroElecInelasticModel (const G4MicroElecInelasticModel &) private
Member Function Documentation
G4double G4MicroElecInelasticModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * p, G4double ekin, G4double emin, G4double emax) virtual
Reimplemented from G4VEmModel.
Definition at line 324 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 324 of file G4MicroElecInelasticModel.cc
References cm, cm2, G4ionEffectiveCharge::EffectiveCharge(), eV, FatalException, G4MicroElecCrossSectionDataSet::FindValue(), G4cout, G4endl, G4Exception(), G4Material::GetBaseMaterial(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), G4Material::GetTotNbOfAtomsPerVolume(), highEnergyLimit, lowEnergyLimit, nistSi, pos(), source.hepunit::proton_mass_c2, tableData, and verboseLevel.
double G4MicroElecInelasticModel::DifferentialCrossSection (G4ParticleDefinition * aParticleDefinition, G4double k, G4double energyTransfer, G4int shell)
Definition at line 708 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 708 of file G4MicroElecInelasticModel.cc
References eDiffCrossSectionData, G4Electron::ElectronDefinition(), G4MicroElecSiStructure::Energy(), eTdummyVec, eVecm, k, pDiffCrossSectionData, G4Proton::ProtonDefinition(), pTdummyVec, pVecm, QuadInterpolator(), SiStructure, t1, and t2.
Referenced by RandomizeEjectedElectronEnergy().
void G4MicroElecInelasticModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector &) virtual
Implements G4VEmModel.
Definition at line 115 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 115 of file G4MicroElecInelasticModel.cc
References G4LossTableManager::AtomDeexcitation(), cm, e, eDiffCrossSectionData, G4InuclParticleNames::electron, G4Electron::ElectronDefinition(), eNrjTransfData, eProbaShellMap, eTdummyVec, eV, eVecm, fasterCode, FatalException, fAtomDeexcitation, fParticleChangeForGamma, G4cout, G4endl, G4Exception(), G4VEmModel::GetParticleChangeForGamma(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), GeV, highEnergyLimit, G4VEmModel::HighEnergyLimit(), G4LossTableManager::Instance(), isInitialised, keV, G4MicroElecCrossSectionDataSet::LoadData(), lowEnergyLimit, G4VEmModel::LowEnergyLimit(), MeV, pDiffCrossSectionData, pNrjTransfData, pProbaShellMap, G4InuclParticleNames::proton, source.hepunit::proton_mass_c2, G4Proton::ProtonDefinition(), pTdummyVec, pVecm, G4VEmModel::SetHighEnergyLimit(), G4VEmModel::SetLowEnergyLimit(), tableData, tableFile, tmp, and verboseLevel.
G4double G4MicroElecInelasticModel::Interpolate (G4double e1, G4double e2, G4double e, G4double xs1, G4double xs2) private
Definition at line 804 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 804 of file G4MicroElecInelasticModel.cc
References a, b, d1, d2, e1, and fasterCode.
Referenced by QuadInterpolator(), and TransferedEnergy().
G4MicroElecInelasticModel& G4MicroElecInelasticModel::operator= (const G4MicroElecInelasticModel & right) private
G4double G4MicroElecInelasticModel::QuadInterpolator (G4double e11, G4double e12, G4double e21, G4double e22, G4double x11, G4double x12, G4double x21, G4double x22, G4double t1, G4double t2, G4double t, G4double e) private
Definition at line 847 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 847 of file G4MicroElecInelasticModel.cc
References Interpolate().
Referenced by DifferentialCrossSection(), and TransferedEnergy().
G4double G4MicroElecInelasticModel::RandomizeEjectedElectronEnergy (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 601 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 601 of file G4MicroElecInelasticModel.cc
References DifferentialCrossSection(), source.hepunit::electron_mass_c2, G4Electron::ElectronDefinition(), G4MicroElecSiStructure::Energy(), eV, G4UniformRand, k, source.hepunit::proton_mass_c2, G4Proton::ProtonDefinition(), SiStructure, and Acts::Test::step().
Referenced by SampleSecondaries().
G4double G4MicroElecInelasticModel::RandomizeEjectedElectronEnergyFromCumulatedDcs (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell) private
Definition at line 917 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 917 of file G4MicroElecInelasticModel.cc
References G4MicroElecSiStructure::Energy(), eV, G4UniformRand, SiStructure, and TransferedEnergy().
Referenced by SampleSecondaries().
G4int G4MicroElecInelasticModel::RandomSelect (G4double energy, const G4String & particle) private
Definition at line 862 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 862 of file G4MicroElecInelasticModel.cc
References FatalException, G4VEMDataSet::FindValue(), G4Exception(), G4UniformRand, G4MicroElecCrossSectionDataSet::GetComponent(), n, G4MicroElecCrossSectionDataSet::NumberOfComponents(), pos(), and tableData.
Referenced by SampleSecondaries().
void G4MicroElecInelasticModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * particle, G4double tmin, G4double maxEnergy) virtual
Implements G4VEmModel.
Definition at line 435 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 435 of file G4MicroElecInelasticModel.cc
References G4InuclSpecialFunctions::bindingEnergy(), G4Electron::Electron(), source.hepunit::electron_mass_c2, G4Electron::ElectronDefinition(), G4MicroElecSiStructure::Energy(), eV, fasterCode, fAtomDeexcitation, fKShell, fParticleChangeForGamma, G4cout, G4endl, G4VAtomDeexcitation::GenerateParticles(), G4VEmModel::GetAngularDistribution(), G4VAtomDeexcitation::GetAtomicShell(), G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGMass(), highEnergyLimit, k, lowEnergyLimit, G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChangeForGamma::ProposeMomentumDirection(), source.hepunit::proton_mass_c2, G4Proton::ProtonDefinition(), RandomizeEjectedElectronEnergy(), RandomizeEjectedElectronEnergyFromCumulatedDcs(), RandomSelect(), G4VEmAngularDistribution::SampleDirectionForShell(), CLHEP::Hep3Vector::set(), G4ParticleChangeForGamma::SetProposedKineticEnergy(), SiStructure, CLHEP::Hep3Vector::unit(), verboseLevel, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), Z, and CLHEP::Hep3Vector::z().
void G4MicroElecInelasticModel::SelectFasterComputation (G4bool input) inline
Definition at line 177 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4MicroElecInelasticModel.hh
References fasterCode.
G4double G4MicroElecInelasticModel::TransferedEnergy (G4ParticleDefinition * aParticleDefinition, G4double incomingParticleEnergy, G4int shell, G4double random)
Definition at line 941 of file G4MicroElecInelasticModel.cc.
View newest version in sPHENIX GitHub at line 941 of file G4MicroElecInelasticModel.cc
References G4InuclSpecialFunctions::bindingEnergy(), e6, source.hepunit::electron_mass_c2, G4Electron::ElectronDefinition(), G4MicroElecSiStructure::Energy(), eNrjTransfData, eProbaShellMap, eTdummyVec, Interpolate(), k, k1, k2, pNrjTransfData, pProbaShellMap, source.hepunit::proton_mass_c2, G4Proton::ProtonDefinition(), pTdummyVec, QuadInterpolator(), and SiStructure.
Referenced by RandomizeEjectedElectronEnergyFromCumulatedDcs().
Member Data Documentation
TriDimensionMap G4MicroElecInelasticModel::eDiffCrossSectionData[7] private
Definition at line 147 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4MicroElecInelasticModel.hh
Referenced by DifferentialCrossSection(), and Initialise().
TriDimensionMap G4MicroElecInelasticModel::eNrjTransfData[7] private
Definition at line 148 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4MicroElecInelasticModel.hh
Referenced by Initialise(), and TransferedEnergy().
VecMap G4MicroElecInelasticModel::eProbaShellMap[7] private
Definition at line 161 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4MicroElecInelasticModel.hh
Referenced by Initialise(), and TransferedEnergy().
std::vector<double> G4MicroElecInelasticModel::eTdummyVec private
Definition at line 153 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4MicroElecInelasticModel.hh
Referenced by DifferentialCrossSection(), Initialise(), and TransferedEnergy().
VecMap G4MicroElecInelasticModel::eVecm private
Definition at line 158 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4MicroElecInelasticModel.hh
Referenced by DifferentialCrossSection(), Initialise(), and ~G4MicroElecInelasticModel().
G4bool G4MicroElecInelasticModel::fasterCode private
Definition at line 101 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4MicroElecInelasticModel.hh
Referenced by G4MicroElecInelasticModel(), Initialise(), Interpolate(), SampleSecondaries(), and SelectFasterComputation().
G4VAtomDeexcitation* G4MicroElecInelasticModel::fAtomDeexcitation private
Definition at line 104 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 104 of file G4MicroElecInelasticModel.hh
Referenced by G4MicroElecInelasticModel(), Initialise(), and SampleSecondaries().
G4ParticleChangeForGamma* G4MicroElecInelasticModel::fParticleChangeForGamma protected
Definition at line 97 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4MicroElecInelasticModel.hh
Referenced by G4MicroElecInelasticModel(), Initialise(), and SampleSecondaries().
std::map<G4String,G4double,std::less<G4String> > G4MicroElecInelasticModel::highEnergyLimit private
Definition at line 109 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4MicroElecInelasticModel.hh
Referenced by CrossSectionPerVolume(), Initialise(), and SampleSecondaries().
G4bool G4MicroElecInelasticModel::isInitialised private
Definition at line 111 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4MicroElecInelasticModel.hh
Referenced by Initialise().
std::map<G4String,G4double,std::less<G4String> > G4MicroElecInelasticModel::lowEnergyLimit private
Definition at line 108 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4MicroElecInelasticModel.hh
Referenced by CrossSectionPerVolume(), Initialise(), and SampleSecondaries().
G4Material* G4MicroElecInelasticModel::nistSi private
Definition at line 106 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4MicroElecInelasticModel.hh
Referenced by CrossSectionPerVolume(), and G4MicroElecInelasticModel().
TriDimensionMap G4MicroElecInelasticModel::pDiffCrossSectionData[7] private
Definition at line 150 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4MicroElecInelasticModel.hh
Referenced by DifferentialCrossSection(), and Initialise().
TriDimensionMap G4MicroElecInelasticModel::pNrjTransfData[7] private
Definition at line 151 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 151 of file G4MicroElecInelasticModel.hh
Referenced by Initialise(), and TransferedEnergy().
VecMap G4MicroElecInelasticModel::pProbaShellMap[7] private
Definition at line 162 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4MicroElecInelasticModel.hh
Referenced by Initialise(), and TransferedEnergy().
std::vector<double> G4MicroElecInelasticModel::pTdummyVec private
Definition at line 154 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4MicroElecInelasticModel.hh
Referenced by DifferentialCrossSection(), Initialise(), and TransferedEnergy().
VecMap G4MicroElecInelasticModel::pVecm private
Definition at line 159 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 159 of file G4MicroElecInelasticModel.hh
Referenced by DifferentialCrossSection(), Initialise(), and ~G4MicroElecInelasticModel().
G4MicroElecSiStructure G4MicroElecInelasticModel::SiStructure private
Definition at line 124 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 124 of file G4MicroElecInelasticModel.hh
Referenced by DifferentialCrossSection(), RandomizeEjectedElectronEnergy(), RandomizeEjectedElectronEnergyFromCumulatedDcs(), SampleSecondaries(), and TransferedEnergy().
MapData G4MicroElecInelasticModel::tableData private
Definition at line 120 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4MicroElecInelasticModel.hh
Referenced by CrossSectionPerVolume(), Initialise(), RandomSelect(), and ~G4MicroElecInelasticModel().
MapFile G4MicroElecInelasticModel::tableFile private
Definition at line 117 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4MicroElecInelasticModel.hh
Referenced by Initialise().
G4int G4MicroElecInelasticModel::verboseLevel private
Definition at line 112 of file G4MicroElecInelasticModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4MicroElecInelasticModel.hh
Referenced by CrossSectionPerVolume(), G4MicroElecInelasticModel(), Initialise(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4MicroElecInelasticModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4MicroElecInelasticModel.cc