ECCE @ EIC Software: G4XnpTotalLowE Class Reference
G4XnpTotalLowE Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XnpTotalLowE.hh>
Public Member Functions
G4XnpTotalLowE ()
virtual ~G4XnpTotalLowE ()
G4bool operator== (const G4XnpTotalLowE &right) const
G4bool operator!= (const G4XnpTotalLowE &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const
virtual G4bool IsValid (G4double e) const
virtual void Print () const
virtual G4String Name () const
virtual G4double HighLimit () const
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double LowLimit () const
Private Member Functions
G4XnpTotalLowE (const G4XnpTotalLowE &right)
const G4XnpTotalLowE & operator= (const G4XnpTotalLowE &right)
Private Attributes
G4PhysicsVector * _sigma
G4double _eMin
G4double _eMax
Static Private Attributes
static const G4double _lowLimit = 0.
static const G4double _highLimit = 3.*GeV
static const G4double _sigmaTable [101]
static const G4int _tableSize = 101
static const G4double _eMinTable = 1.8964808
static const G4double _eStepLog = 0.01
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 51 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 51 of file G4XnpTotalLowE.hh
Constructor & Destructor Documentation
G4XnpTotalLowE::G4XnpTotalLowE ()
Definition at line 88 of file G4XnpTotalLowE.cc.
View newest version in sPHENIX GitHub at line 88 of file G4XnpTotalLowE.cc
References _eMax, _eMin, _eMinTable, _eStepLog, _highLimit, _lowLimit, _sigma, _sigmaTable, _tableSize, G4Exp(), G4Log(), GeV, millibarn, and G4PhysicsVector::PutValue().
G4XnpTotalLowE::~G4XnpTotalLowE () virtual
Definition at line 114 of file G4XnpTotalLowE.cc.
View newest version in sPHENIX GitHub at line 114 of file G4XnpTotalLowE.cc
References _sigma.
G4XnpTotalLowE::G4XnpTotalLowE (const G4XnpTotalLowE & right) private
Member Function Documentation
G4double G4XnpTotalLowE::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 133 of file G4XnpTotalLowE.cc.
View newest version in sPHENIX GitHub at line 133 of file G4XnpTotalLowE.cc
References _eMax, _eMin, _sigma, G4KineticTrack::Get4Momentum(), G4KineticTrack::GetDefinition(), G4PhysicsVector::GetValue(), G4InuclParticleNames::neutron, G4Neutron::NeutronDefinition(), G4InuclParticleNames::proton, and G4Proton::ProtonDefinition().
virtual const G4CrossSectionVector* G4XnpTotalLowE::GetComponents () const inline virtual
Implements G4VCrossSectionSource.
Definition at line 65 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 65 of file G4XnpTotalLowE.hh
virtual G4double G4XnpTotalLowE::HighLimit () const inline virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 73 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 73 of file G4XnpTotalLowE.hh
References _highLimit.
G4bool G4XnpTotalLowE::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 185 of file G4XnpTotalLowE.cc.
View newest version in sPHENIX GitHub at line 185 of file G4XnpTotalLowE.cc
References _highLimit, _lowLimit, and G4VCrossSectionSource::InLimits().
G4String G4XnpTotalLowE::Name () const virtual
Implements G4VCrossSectionSource.
Definition at line 178 of file G4XnpTotalLowE.cc.
View newest version in sPHENIX GitHub at line 178 of file G4XnpTotalLowE.cc
Referenced by Print().
G4bool G4XnpTotalLowE::operator!= (const G4XnpTotalLowE & right) const
Definition at line 127 of file G4XnpTotalLowE.cc.
View newest version in sPHENIX GitHub at line 127 of file G4XnpTotalLowE.cc
const G4XnpTotalLowE& G4XnpTotalLowE::operator= (const G4XnpTotalLowE & right) private
G4bool G4XnpTotalLowE::operator== (const G4XnpTotalLowE & right) const
Definition at line 121 of file G4XnpTotalLowE.cc.
View newest version in sPHENIX GitHub at line 121 of file G4XnpTotalLowE.cc
void G4XnpTotalLowE::Print (void) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 159 of file G4XnpTotalLowE.cc.
View newest version in sPHENIX GitHub at line 159 of file G4XnpTotalLowE.cc
References _sigma, _tableSize, e, G4cout, G4endl, G4PhysicsVector::GetLowEdgeEnergy(), G4PhysicsVector::GetValue(), GeV, millibarn, Name(), and G4VCrossSectionSource::Print().
Member Data Documentation
G4double G4XnpTotalLowE::_eMax private
Definition at line 93 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 93 of file G4XnpTotalLowE.hh
Referenced by CrossSection(), and G4XnpTotalLowE().
G4double G4XnpTotalLowE::_eMin private
Definition at line 92 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 92 of file G4XnpTotalLowE.hh
Referenced by CrossSection(), and G4XnpTotalLowE().
const G4double G4XnpTotalLowE::_eMinTable = 1.8964808 static private
Definition at line 88 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 88 of file G4XnpTotalLowE.hh
Referenced by G4XnpTotalLowE().
const G4double G4XnpTotalLowE::_eStepLog = 0.01 static private
Definition at line 89 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 89 of file G4XnpTotalLowE.hh
Referenced by G4XnpTotalLowE().
const G4double G4XnpTotalLowE::_highLimit = 3.*GeV static private
Definition at line 85 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 85 of file G4XnpTotalLowE.hh
Referenced by G4XnpTotalLowE(), HighLimit(), and IsValid().
const G4double G4XnpTotalLowE::_lowLimit = 0. static private
Definition at line 84 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 84 of file G4XnpTotalLowE.hh
Referenced by G4XnpTotalLowE(), and IsValid().
G4PhysicsVector* G4XnpTotalLowE::_sigma private
Definition at line 91 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 91 of file G4XnpTotalLowE.hh
Referenced by CrossSection(), G4XnpTotalLowE(), Print(), and ~G4XnpTotalLowE().
const G4double G4XnpTotalLowE::_sigmaTable static private
Initial value:
=
{
  1500.0,
  248.20, 93.38, 55.26, 44.50, 41.33, 38.48, 37.20, 35.98,
  35.02, 34.47, 34.37, 34.67, 35.23, 35.97, 36.75, 37.37,
  37.77, 38.03, 38.40, 38.83, 39.26, 39.67, 40.06, 40.45,
  40.79, 41.06, 41.31, 41.52, 41.70, 41.81, 41.87, 41.98,
  42.12, 42.29, 42.55, 42.82, 43.01, 43.12, 43.16, 43.14,
  43.06, 42.95, 42.81, 42.67, 42.54, 42.45, 42.38, 42.33,
  42.30, 42.29, 42.28, 42.26, 42.24, 42.21, 42.17, 42.14,
  42.10, 42.07, 42.06, 42.05, 42.04, 42.03, 42.02, 42.00,
  41.97, 41.94, 41.89, 41.84, 41.79, 41.73, 41.67, 41.61,
  41.55, 41.49, 41.44, 41.38, 41.34, 41.31, 41.29, 41.28,
  41.27, 41.28, 41.30, 41.33, 41.36, 41.40, 41.44, 41.49,
  41.50, 41.51, 41.51, 41.51, 41.52, 41.51, 41.51, 41.50,
  41.50, 41.49, 41.47, 41.46
}
Definition at line 86 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 86 of file G4XnpTotalLowE.hh
Referenced by G4XnpTotalLowE().
const G4int G4XnpTotalLowE::_tableSize = 101 static private
Definition at line 87 of file G4XnpTotalLowE.hh.
View newest version in sPHENIX GitHub at line 87 of file G4XnpTotalLowE.hh
Referenced by G4XnpTotalLowE(), and Print().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4XnpTotalLowE.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4XnpTotalLowE.cc