ECCE @ EIC Software: G4tgbPlaceParamLinear Class Reference
G4tgbPlaceParamLinear Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbPlaceParamLinear.hh>
Public Member Functions
G4tgbPlaceParamLinear (G4tgrPlaceParameterisation *)
~G4tgbPlaceParamLinear ()
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4tgbPlaceParameterisation
G4tgbPlaceParameterisation (G4tgrPlaceParameterisation *tgrParam)
virtual ~G4tgbPlaceParameterisation ()
void CheckNExtraData (G4tgrPlaceParameterisation *tgrParam, G4int nWcheck, WLSIZEtype st, const G4String &methodName)
G4int GetNCopies () const
EAxis GetAxis () const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4ThreeVector theDirection
G4double theStep
G4double theOffset
Additional Inherited Members
Protected Attributes inherited from G4tgbPlaceParameterisation
G4int theNCopies
EAxis theAxis
G4ThreeVector theTranslation
G4RotationMatrix * theRotationMatrix
Detailed Description
Definition at line 50 of file G4tgbPlaceParamLinear.hh.
View newest version in sPHENIX GitHub at line 50 of file G4tgbPlaceParamLinear.hh
Constructor & Destructor Documentation
G4tgbPlaceParamLinear::G4tgbPlaceParamLinear (G4tgrPlaceParameterisation * tgrParam)
Definition at line 49 of file G4tgbPlaceParamLinear.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgbPlaceParamLinear.cc
References G4tgbPlaceParameterisation::CheckNExtraData(), FatalException, G4cout, G4endl, G4Exception(), G4tgrPlaceParameterisation::GetExtraData(), G4tgrPlaceParameterisation::GetParamType(), G4tgrMessenger::GetVerboseLevel(), kXAxis, kYAxis, kZAxis, CLHEP::Hep3Vector::mag(), G4tgbPlaceParameterisation::theAxis, theDirection, G4tgbPlaceParameterisation::theNCopies, theOffset, theStep, G4tgbPlaceParameterisation::theTranslation, and WLSIZE_EQ.
G4tgbPlaceParamLinear::~G4tgbPlaceParamLinear ()
Definition at line 42 of file G4tgbPlaceParamLinear.cc.
View newest version in sPHENIX GitHub at line 42 of file G4tgbPlaceParamLinear.cc
Member Function Documentation
void G4tgbPlaceParamLinear::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4tgbPlaceParameterisation.
Definition at line 110 of file G4tgbPlaceParamLinear.cc.
View newest version in sPHENIX GitHub at line 110 of file G4tgbPlaceParamLinear.cc
References G4cout, G4endl, G4VPhysicalVolume::GetName(), G4tgrMessenger::GetVerboseLevel(), Acts::Test::origin(), G4VPhysicalVolume::SetCopyNo(), G4VPhysicalVolume::SetRotation(), G4VPhysicalVolume::SetTranslation(), theDirection, G4tgbPlaceParameterisation::theRotationMatrix, theStep, and G4tgbPlaceParameterisation::theTranslation.
Member Data Documentation
G4ThreeVector G4tgbPlaceParamLinear::theDirection private
Definition at line 60 of file G4tgbPlaceParamLinear.hh.
View newest version in sPHENIX GitHub at line 60 of file G4tgbPlaceParamLinear.hh
Referenced by ComputeTransformation(), and G4tgbPlaceParamLinear().
G4double G4tgbPlaceParamLinear::theOffset private
Definition at line 62 of file G4tgbPlaceParamLinear.hh.
View newest version in sPHENIX GitHub at line 62 of file G4tgbPlaceParamLinear.hh
Referenced by G4tgbPlaceParamLinear().
G4double G4tgbPlaceParamLinear::theStep private
Definition at line 61 of file G4tgbPlaceParamLinear.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgbPlaceParamLinear.hh
Referenced by ComputeTransformation(), and G4tgbPlaceParamLinear().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbPlaceParamLinear.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbPlaceParamLinear.cc