ECCE @ EIC Software: HEPREP::HepRepTreeID Class Reference
HEPREP::HepRepTreeID Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepTreeID.h>
Public Member Functions
virtual ~HepRepTreeID ()
Destructor.
virtual std::string getName ()=0
virtual std::string getVersion ()=0
virtual std::string getQualifier ()=0
virtual void setQualifier (std::string qualifier)=0
Detailed Description
HepRepTreeID interface.
Author
Mark Donszelmann
Definition at line 21 of file HepRepTreeID.h.
View newest version in sPHENIX GitHub at line 21 of file HepRepTreeID.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepTreeID::~HepRepTreeID () inline virtual
Destructor.
Definition at line 25 of file HepRepTreeID.h.
View newest version in sPHENIX GitHub at line 25 of file HepRepTreeID.h
Member Function Documentation
virtual std::string HEPREP::HepRepTreeID::getName () pure virtual
Returns the name of this treeID.
Returns
name of treeID.
Implemented in cheprep::DefaultHepRepTreeID.
Referenced by cheprep::XMLHepRepWriter::write().
virtual std::string HEPREP::HepRepTreeID::getQualifier () pure virtual
Returns the qualifier that qualifies the relation that this treeID has with what it refers to.
Returns
qualifier.
Implemented in cheprep::DefaultHepRepTreeID.
Referenced by cheprep::XMLHepRepWriter::write().
virtual std::string HEPREP::HepRepTreeID::getVersion () pure virtual
Returns the version of this treeID.
Returns
version of treeID.
Implemented in cheprep::DefaultHepRepTreeID.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void HEPREP::HepRepTreeID::setQualifier (std::string qualifier) pure virtual
Sets the qualifier that qualifies the relation that this treeID has with what it refers to.
Parameters
qualifier to be set.
Implemented in cheprep::DefaultHepRepTreeID.
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepTreeID.h