ECCE @ EIC Software: G4VFermiBreakUp Class Reference
G4VFermiBreakUp Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4VFermiBreakUp.hh>
Public Member Functions
G4VFermiBreakUp ()
virtual ~G4VFermiBreakUp ()
virtual void Initialise ()=0
virtual G4bool IsApplicable (G4int Z, G4int A, G4double mass) const =0
virtual void BreakFragment (G4FragmentVector *results, G4Fragment *theNucleus)=0
void SetVerbose (G4int val)
Protected Attributes
G4int verbose
Private Member Functions
G4VFermiBreakUp (const G4VFermiBreakUp &right)
const G4VFermiBreakUp & operator= (const G4VFermiBreakUp &right)
G4bool operator== (const G4VFermiBreakUp &right) const
G4bool operator!= (const G4VFermiBreakUp &right) const
Detailed Description
Definition at line 39 of file G4VFermiBreakUp.hh.
View newest version in sPHENIX GitHub at line 39 of file G4VFermiBreakUp.hh
Constructor & Destructor Documentation
G4VFermiBreakUp::G4VFermiBreakUp () inline explicit
Definition at line 43 of file G4VFermiBreakUp.hh.
View newest version in sPHENIX GitHub at line 43 of file G4VFermiBreakUp.hh
virtual G4VFermiBreakUp::~G4VFermiBreakUp () inline virtual
Definition at line 44 of file G4VFermiBreakUp.hh.
View newest version in sPHENIX GitHub at line 44 of file G4VFermiBreakUp.hh
G4VFermiBreakUp::G4VFermiBreakUp (const G4VFermiBreakUp & right) private
Member Function Documentation
virtual void G4VFermiBreakUp::BreakFragment (G4FragmentVector * results, G4Fragment * theNucleus) pure virtual
Implemented in G4FermiBreakUpVI.
Referenced by G4ExcitationHandler::BreakItUp().
virtual void G4VFermiBreakUp::Initialise () pure virtual
Implemented in G4FermiBreakUpVI.
Referenced by G4ExcitationHandler::Initialise().
virtual G4bool G4VFermiBreakUp::IsApplicable (G4int Z, G4int A, G4double mass) const pure virtual
Implemented in G4FermiBreakUpVI.
Referenced by G4Evaporation::BreakFragment(), and G4ExcitationHandler::BreakItUp().
G4bool G4VFermiBreakUp::operator!= (const G4VFermiBreakUp & right) const private
const G4VFermiBreakUp& G4VFermiBreakUp::operator= (const G4VFermiBreakUp & right) private
G4bool G4VFermiBreakUp::operator== (const G4VFermiBreakUp & right) const private
void G4VFermiBreakUp::SetVerbose (G4int val) inline
Definition at line 59 of file G4VFermiBreakUp.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VFermiBreakUp.hh
References verbose.
Referenced by G4ExcitationHandler::SetParameters().
Member Data Documentation
G4int G4VFermiBreakUp::verbose protected
Definition at line 63 of file G4VFermiBreakUp.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VFermiBreakUp.hh
Referenced by G4FermiBreakUpVI::BreakFragment(), G4FermiBreakUpVI::Initialise(), G4FermiBreakUpVI::SampleDecay(), and SetVerbose().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4VFermiBreakUp.hh