ECCE @ EIC Software: G4EmCaptureCascade Class Reference
G4EmCaptureCascade Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4EmCaptureCascade.hh>
Public Member Functions
G4EmCaptureCascade ()
virtual ~G4EmCaptureCascade ()
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
virtual void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
void AddNewParticle (G4ParticleDefinition *aParticle, G4double kinEnergy)
G4EmCaptureCascade & operator= (const G4EmCaptureCascade &right)=delete
G4EmCaptureCascade (const G4EmCaptureCascade &)=delete
Private Attributes
G4HadFinalState result
G4ParticleDefinition * theElectron
G4ParticleDefinition * theGamma
G4double fMuMass
G4double fTime
G4double fLevelEnergy [14]
G4double fKLevelEnergy [93]
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 66 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 66 of file G4EmCaptureCascade.hh
Constructor & Destructor Documentation
G4EmCaptureCascade::G4EmCaptureCascade () explicit
Definition at line 55 of file G4EmCaptureCascade.cc.
View newest version in sPHENIX GitHub at line 55 of file G4EmCaptureCascade.cc
References dz, G4Electron::Electron(), fKLevelEnergy, fLevelEnergy, fMuMass, fTime, G4Gamma::Gamma(), G4ParticleDefinition::GetPDGMass(), incremental_prev_tag::idx, G4MuonMinus::MuonMinus(), theElectron, theGamma, y1, y2, z, z1, and z2.
G4EmCaptureCascade::~G4EmCaptureCascade () virtual
Definition at line 101 of file G4EmCaptureCascade.cc.
View newest version in sPHENIX GitHub at line 101 of file G4EmCaptureCascade.cc
G4EmCaptureCascade::G4EmCaptureCascade (const G4EmCaptureCascade &) private delete
Member Function Documentation
void G4EmCaptureCascade::AddNewParticle (G4ParticleDefinition * aParticle, G4double kinEnergy) inline private
Definition at line 100 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 100 of file G4EmCaptureCascade.hh
References G4HadFinalState::AddSecondary(), fTime, G4RandomDirection(), result, and G4HadSecondary::SetTime().
Referenced by ApplyYourself().
G4HadFinalState * G4EmCaptureCascade::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 107 of file G4EmCaptureCascade.cc.
View newest version in sPHENIX GitHub at line 107 of file G4EmCaptureCascade.cc
References A(), AddNewParticle(), G4HadFinalState::Clear(), e, edep, source.hepunit::electron_mass_c2, eV, fKLevelEnergy, fLevelEnergy, fMuMass, fTime, G4UniformRand, G4Nucleus::GetA_asInt(), G4HadProjectile::GetGlobalTime(), G4NucleiProperties::GetNuclearMass(), G4Nucleus::GetZ_asInt(), isAlive, mass, min, result, G4HadFinalState::SetLocalEnergyDeposit(), G4HadFinalState::SetStatusChange(), theElectron, theGamma, and Z.
void G4EmCaptureCascade::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 172 of file G4EmCaptureCascade.cc.
View newest version in sPHENIX GitHub at line 172 of file G4EmCaptureCascade.cc
G4EmCaptureCascade& G4EmCaptureCascade::operator= (const G4EmCaptureCascade & right) private delete
Member Data Documentation
G4double G4EmCaptureCascade::fKLevelEnergy[93] private
Definition at line 94 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 94 of file G4EmCaptureCascade.hh
Referenced by ApplyYourself(), and G4EmCaptureCascade().
G4double G4EmCaptureCascade::fLevelEnergy[14] private
Definition at line 93 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 93 of file G4EmCaptureCascade.hh
Referenced by ApplyYourself(), and G4EmCaptureCascade().
G4double G4EmCaptureCascade::fMuMass private
Definition at line 91 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 91 of file G4EmCaptureCascade.hh
Referenced by ApplyYourself(), and G4EmCaptureCascade().
G4double G4EmCaptureCascade::fTime private
Definition at line 92 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 92 of file G4EmCaptureCascade.hh
Referenced by AddNewParticle(), ApplyYourself(), and G4EmCaptureCascade().
G4HadFinalState G4EmCaptureCascade::result private
Definition at line 88 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 88 of file G4EmCaptureCascade.hh
Referenced by AddNewParticle(), and ApplyYourself().
G4ParticleDefinition* G4EmCaptureCascade::theElectron private
Definition at line 89 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 89 of file G4EmCaptureCascade.hh
Referenced by ApplyYourself(), and G4EmCaptureCascade().
G4ParticleDefinition* G4EmCaptureCascade::theGamma private
Definition at line 90 of file G4EmCaptureCascade.hh.
View newest version in sPHENIX GitHub at line 90 of file G4EmCaptureCascade.hh
Referenced by ApplyYourself(), and G4EmCaptureCascade().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4EmCaptureCascade.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/src/G4EmCaptureCascade.cc