ECCE @ EIC Software: G4DecayWithSpin Class Reference
G4DecayWithSpin Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/decay/include/G4DecayWithSpin.hh>
Public Member Functions
G4DecayWithSpin (const G4String &processName="DecayWithSpin")
virtual ~G4DecayWithSpin ()
virtual void ProcessDescription (std::ostream &outFile) const override
Public Member Functions inherited from G4Decay
G4Decay (const G4String &processName="Decay")
virtual ~G4Decay ()
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
virtual G4bool IsApplicable (const G4ParticleDefinition &) override
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition) override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
virtual void StartTracking (G4Track *) override
virtual void EndTracking () override
void SetExtDecayer (G4VExtDecayer *)
const G4VExtDecayer * GetExtDecayer () const
G4double GetRemainderLifeTime () const
Public Member Functions inherited from G4VRestDiscreteProcess
G4VRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VRestDiscreteProcess (G4VRestDiscreteProcess &)
virtual ~G4VRestDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual G4VParticleChange * AtRestDoIt (const G4Track &aTrack, const G4Step &aStep) override
Protected Member Functions inherited from G4Decay
virtual G4VParticleChange * DecayIt (const G4Track &aTrack, const G4Step &aStep)
virtual void DaughterPolarization (const G4Track &aTrack, G4DecayProducts *products)
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition) override
virtual G4double GetMeanLifeTime (const G4Track &aTrack, G4ForceCondition *condition) override
Private Member Functions
G4ThreeVector Spin_Precession (const G4Step &aStep, G4ThreeVector B, G4double deltatime)
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4Decay
G4int verboseLevel
const G4double HighestValue
G4double fRemainderLifeTime
G4ParticleChangeForDecay fParticleChangeForDecay
G4VExtDecayer * pExtDecayer
Detailed Description
Definition at line 43 of file G4DecayWithSpin.hh.
View newest version in sPHENIX GitHub at line 43 of file G4DecayWithSpin.hh
Constructor & Destructor Documentation
G4DecayWithSpin::G4DecayWithSpin (const G4String & processName = "DecayWithSpin")
Definition at line 52 of file G4DecayWithSpin.cc.
View newest version in sPHENIX GitHub at line 52 of file G4DecayWithSpin.cc
References DECAY_WithSpin, and G4VProcess::SetProcessSubType().
G4DecayWithSpin::~G4DecayWithSpin () virtual
Definition at line 59 of file G4DecayWithSpin.cc.
View newest version in sPHENIX GitHub at line 59 of file G4DecayWithSpin.cc
Member Function Documentation
G4VParticleChange * G4DecayWithSpin::AtRestDoIt (const G4Track & aTrack, const G4Step & aStep) override protected virtual
Reimplemented from G4Decay.
Definition at line 109 of file G4DecayWithSpin.cc.
View newest version in sPHENIX GitHub at line 109 of file G4DecayWithSpin.cc
References B(), G4Decay::DecayIt(), G4DecayTable::entries(), G4Decay::fRemainderLifeTime, G4UniformRand, G4PropagatorInField::GetCurrentFieldManager(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4DynamicParticle::GetDefinition(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetPolarization(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4TransportationManager::GetPropagatorInField(), G4Step::GetTrack(), G4TransportationManager::GetTransportationManager(), G4Track::GetVolume(), CLHEP::Hep3Vector::mag2(), phi, G4ParticleChangeForDecay::ProposePolarization(), G4VDecayChannel::SetPolarization(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), Spin_Precession(), and twopi.
G4VParticleChange * G4DecayWithSpin::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) override protected virtual
Reimplemented from G4Decay.
Definition at line 61 of file G4DecayWithSpin.cc.
View newest version in sPHENIX GitHub at line 61 of file G4DecayWithSpin.cc
References G4Decay::DecayIt(), G4DecayTable::entries(), G4Decay::fParticleChangeForDecay, fStopAndKill, fStopButAlive, G4UniformRand, G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetPolarization(), G4Track::GetTrackStatus(), G4ParticleChangeForDecay::Initialize(), phi, G4ParticleChangeForDecay::ProposePolarization(), G4VDecayChannel::SetPolarization(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), and twopi.
void G4DecayWithSpin::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4Decay.
Definition at line 225 of file G4DecayWithSpin.cc.
View newest version in sPHENIX GitHub at line 225 of file G4DecayWithSpin.cc
References G4VProcess::GetProcessName().
G4ThreeVector G4DecayWithSpin::Spin_Precession (const G4Step & aStep, G4ThreeVector B, G4double deltatime) private
Definition at line 186 of file G4DecayWithSpin.cc.
View newest version in sPHENIX GitHub at line 186 of file G4DecayWithSpin.cc
References a, G4cout, G4endl, G4Track::GetDefinition(), G4ParticleDefinition::GetPDGCharge(), G4Step::GetTrack(), G4VProcess::GetVerboseLevel(), kilogauss, rad, sqr(), and CLHEP::Hep3Vector::unit().
Referenced by AtRestDoIt().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/decay/include/G4DecayWithSpin.hh
geant4/tree/geant4-10.6-release/source/processes/decay/src/G4DecayWithSpin.cc