ECCE @ EIC Software: CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel > Class Template Reference
CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel > Class Template Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcPhysicsList.hh>
Public Member Functions
CexmcPhysicsList ()
CexmcProductionModel * GetProductionModel (void)
G4bool IsStudiedProcessAllowed (void) const
void ResampleTrackLengthInTarget (const G4Track *track, const G4StepPoint *stepPoint)
void SetupConstructionHook (const CexmcSetup *setup)
Public Member Functions inherited from CexmcPhysicsManager
CexmcPhysicsManager ()
virtual ~CexmcPhysicsManager ()
G4bool OnlyBeamParticleCanTriggerStudiedProcess (void) const
void IncrementNumberOfTriggeredStudiedInteractions (void)
void ResetNumberOfTriggeredStudiedInteractions (void)
G4double GetProposedMaxIL (void) const
void SetMaxIL (const G4ThreeVector &direction)
void SetMaxILCorrection (G4double value)
void SetProposedMaxIL (G4double value)
Protected Member Functions
void CalculateBasicMaxIL (const G4ThreeVector &direction)
Private Attributes
StudiedPhysics< ProductionModel > * studiedPhysics
G4VSolid * targetSolid
G4AffineTransform targetTransform
Additional Inherited Members
Protected Attributes inherited from CexmcPhysicsManager
G4double basicMaxIL
G4double maxILCorrection
G4double proposedMaxIL
G4int numberOfTriggeredStudiedInteractions
G4bool onlyBeamParticleCanTriggerStudiedProcess
Detailed Description
template<typename BasePhysics, template< typename > class StudiedPhysics, typename ProductionModel>
class CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >
Definition at line 62 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 62 of file CexmcPhysicsList.hh
Constructor & Destructor Documentation
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::CexmcPhysicsList ()
Definition at line 92 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 92 of file CexmcPhysicsList.hh
References CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::studiedPhysics.
Member Function Documentation
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > void CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::CalculateBasicMaxIL (const G4ThreeVector & direction) protected virtual
Implements CexmcPhysicsManager.
Definition at line 164 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 164 of file CexmcPhysicsList.hh
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > CexmcProductionModel * CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::GetProductionModel (void) virtual
Implements CexmcPhysicsManager.
Definition at line 103 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 103 of file CexmcPhysicsList.hh
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > G4bool CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::IsStudiedProcessAllowed (void) const virtual
Implements CexmcPhysicsManager.
Definition at line 112 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 112 of file CexmcPhysicsList.hh
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > void CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget (const G4Track * track, const G4StepPoint * stepPoint) virtual
Implements CexmcPhysicsManager.
Definition at line 121 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 121 of file CexmcPhysicsList.hh
References G4UniformRand, G4StepPoint::GetMomentumDirection(), G4Track::GetMomentumDirection(), G4StepPoint::GetPosition(), G4Track::GetPosition(), G4Track::GetUserInformation(), max, position, CexmcIncidentParticleTrackInfo::ResetCurrentTrackLengthInTarget(), CexmcIncidentParticleTrackInfo::SetFinalTrackLengthInTarget(), and CexmcIncidentParticleTrackInfo::SetNeedsTrackLengthResampling().
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > void CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::SetupConstructionHook (const CexmcSetup * setup) virtual
Implements CexmcPhysicsManager.
Definition at line 176 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 176 of file CexmcPhysicsList.hh
References G4LogicalVolume::GetSolid(), CexmcSetup::GetTargetTransform(), CexmcSetup::GetVolume(), G4AffineTransform::Inverse(), and CexmcSetup::Target.
Member Data Documentation
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > StudiedPhysics< ProductionModel >* CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::studiedPhysics private
Definition at line 81 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 81 of file CexmcPhysicsList.hh
Referenced by CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::CexmcPhysicsList().
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > G4VSolid* CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::targetSolid private
Definition at line 83 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 83 of file CexmcPhysicsList.hh
template<typename BasePhysics , template< typename > class StudiedPhysics, typename ProductionModel > G4AffineTransform CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::targetTransform private
Definition at line 85 of file CexmcPhysicsList.hh.
View newest version in sPHENIX GitHub at line 85 of file CexmcPhysicsList.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcPhysicsList.hh