ECCE @ EIC Software: DrcPidFast Class Reference
DrcPidFast Class Reference
#include <ecce-detectors/blob/master/FastPID/hpDIRC/DrcPidFast.h>
Public Member Functions
DrcPidFast (int barid=0)
~DrcPidFast ()
void ReadMap (TString name)
DrcPidInfo GetInfo (int pdg, TVector3 mom, double track_err=0)
DrcPidInfo GetInfo (int pdg, double p, double theta, double track_err=0)
TH2F * GetTrrMap ()
Private Member Functions
int get_pid (int pdg)
Private Attributes
TH2F * fTrrMap
double fMass [5]
TF1 * fMs_mom
TF1 * fMs_thickness
double fMs_thickness_max
Detailed Description
Definition at line 25 of file DrcPidFast.h.
View newest version in sPHENIX GitHub at line 25 of file DrcPidFast.h
Constructor & Destructor Documentation
DrcPidFast::DrcPidFast (int barid = 0)
Definition at line 3 of file DrcPidFast.cxx.
View newest version in sPHENIX GitHub at line 3 of file DrcPidFast.cxx
References e, fMass, fMs_mom, fMs_thickness, fMs_thickness_max, and ReadMap().
DrcPidFast::~DrcPidFast () inline
Definition at line 32 of file DrcPidFast.h.
View newest version in sPHENIX GitHub at line 32 of file DrcPidFast.h
Member Function Documentation
int DrcPidFast::get_pid (int pdg) private
Definition at line 111 of file DrcPidFast.cxx.
View newest version in sPHENIX GitHub at line 111 of file DrcPidFast.cxx
References pid.
Referenced by GetInfo().
DrcPidInfo DrcPidFast::GetInfo (int pdg, TVector3 mom, double track_err = 0)
Definition at line 37 of file DrcPidFast.cxx.
View newest version in sPHENIX GitHub at line 37 of file DrcPidFast.cxx
References GetInfo(), and theta().
Referenced by example(), GetInfo(), plot_map(), and scan_mom().
DrcPidInfo DrcPidFast::GetInfo (int pdg, double p, double theta, double track_err = 0)
Definition at line 43 of file DrcPidFast.cxx.
View newest version in sPHENIX GitHub at line 43 of file DrcPidFast.cxx
References alpha, bin, DrcPidInfo::cangle, DrcPidInfo::cctr, Acts::Test::delta, fMass, fMs_mom, fMs_thickness, fMs_thickness_max, fTrrMap, get_pid(), max, pid, DrcPidInfo::probability, DrcPidInfo::sigma, and sum.
TH2F* DrcPidFast::GetTrrMap () inline
Definition at line 45 of file DrcPidFast.h.
View newest version in sPHENIX GitHub at line 45 of file DrcPidFast.h
References fTrrMap.
Referenced by plot_map().
void DrcPidFast::ReadMap (TString name)
Definition at line 31 of file DrcPidFast.cxx.
View newest version in sPHENIX GitHub at line 31 of file DrcPidFast.cxx
References file, and fTrrMap.
Referenced by DrcPidFast().
Member Data Documentation
double DrcPidFast::fMass[5] private
Definition at line 50 of file DrcPidFast.h.
View newest version in sPHENIX GitHub at line 50 of file DrcPidFast.h
Referenced by DrcPidFast(), and GetInfo().
TF1* DrcPidFast::fMs_mom private
Definition at line 51 of file DrcPidFast.h.
View newest version in sPHENIX GitHub at line 51 of file DrcPidFast.h
Referenced by DrcPidFast(), and GetInfo().
TF1 * DrcPidFast::fMs_thickness private
Definition at line 51 of file DrcPidFast.h.
View newest version in sPHENIX GitHub at line 51 of file DrcPidFast.h
Referenced by DrcPidFast(), and GetInfo().
double DrcPidFast::fMs_thickness_max private
Definition at line 52 of file DrcPidFast.h.
View newest version in sPHENIX GitHub at line 52 of file DrcPidFast.h
Referenced by DrcPidFast(), and GetInfo().
TH2F* DrcPidFast::fTrrMap private
Definition at line 49 of file DrcPidFast.h.
View newest version in sPHENIX GitHub at line 49 of file DrcPidFast.h
Referenced by GetInfo(), GetTrrMap(), and ReadMap().
The documentation for this class was generated from the following files:
ecce-detectors/blob/master/FastPID/hpDIRC/DrcPidFast.h
ecce-detectors/blob/master/FastPID/hpDIRC/DrcPidFast.cxx