ECCE @ EIC Software: G4tgrRotationMatrixFactory Class Reference
G4tgrRotationMatrixFactory Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrRotationMatrixFactory.hh>
Public Member Functions
G4tgrRotationMatrix * AddRotMatrix (const std::vector< G4String > &wl)
G4tgrRotationMatrix * FindRotMatrix (const G4String &rotm)
const G4mstgrrotm & GetRotMatMap () const
std::vector
< G4tgrRotationMatrix * > GetRotMatList () const
void DumpRotmList ()
Static Public Member Functions
static G4tgrRotationMatrixFactory * GetInstance ()
Private Member Functions
G4tgrRotationMatrixFactory ()
~G4tgrRotationMatrixFactory ()
Private Attributes
std::vector
< G4tgrRotationMatrix * > theTgrRotMatList
G4mstgrrotm theTgrRotMats
Static Private Attributes
static G4ThreadLocal
G4tgrRotationMatrixFactory * theInstance = 0
Detailed Description
Definition at line 50 of file G4tgrRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 50 of file G4tgrRotationMatrixFactory.hh
Constructor & Destructor Documentation
G4tgrRotationMatrixFactory::G4tgrRotationMatrixFactory () private
Definition at line 55 of file G4tgrRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgrRotationMatrixFactory.cc
Referenced by GetInstance().
G4tgrRotationMatrixFactory::~G4tgrRotationMatrixFactory () private
Definition at line 61 of file G4tgrRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 61 of file G4tgrRotationMatrixFactory.cc
References theInstance, and theTgrRotMats.
Member Function Documentation
G4tgrRotationMatrix * G4tgrRotationMatrixFactory::AddRotMatrix (const std::vector< G4String > & wl)
Definition at line 75 of file G4tgrRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 75 of file G4tgrRotationMatrixFactory.cc
References G4tgrUtils::DumpVS(), FatalException, FindRotMatrix(), G4cout, G4endl, G4Exception(), G4tgrRotationMatrix::GetName(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), theTgrRotMatList, and theTgrRotMats.
Referenced by G4tgrLineProcessor::ProcessLine().
void G4tgrRotationMatrixFactory::DumpRotmList ()
Definition at line 125 of file G4tgrRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 125 of file G4tgrRotationMatrixFactory.cc
References G4cout, G4endl, and theTgrRotMats.
Referenced by G4tgrVolumeMgr::DumpSummary().
G4tgrRotationMatrix * G4tgrRotationMatrixFactory::FindRotMatrix (const G4String & rotm)
Definition at line 110 of file G4tgrRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 110 of file G4tgrRotationMatrixFactory.cc
References theTgrRotMats.
Referenced by AddRotMatrix().
G4tgrRotationMatrixFactory * G4tgrRotationMatrixFactory::GetInstance (void) static
Definition at line 44 of file G4tgrRotationMatrixFactory.cc.
View newest version in sPHENIX GitHub at line 44 of file G4tgrRotationMatrixFactory.cc
References G4tgrRotationMatrixFactory(), and theInstance.
Referenced by G4tgbRotationMatrixMgr::CopyRotMats(), G4tgrVolumeMgr::DumpSummary(), and G4tgrLineProcessor::ProcessLine().
std::vector<G4tgrRotationMatrix*> G4tgrRotationMatrixFactory::GetRotMatList () const inline
Definition at line 65 of file G4tgrRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 65 of file G4tgrRotationMatrixFactory.hh
References theTgrRotMatList.
Referenced by G4tgrVolumeMgr::DumpSummary().
const G4mstgrrotm& G4tgrRotationMatrixFactory::GetRotMatMap () const inline
Definition at line 63 of file G4tgrRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 63 of file G4tgrRotationMatrixFactory.hh
References theTgrRotMats.
Referenced by G4tgbRotationMatrixMgr::CopyRotMats().
Member Data Documentation
G4ThreadLocal G4tgrRotationMatrixFactory * G4tgrRotationMatrixFactory::theInstance = 0 static private
Definition at line 78 of file G4tgrRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 78 of file G4tgrRotationMatrixFactory.hh
Referenced by GetInstance(), and ~G4tgrRotationMatrixFactory().
std::vector<G4tgrRotationMatrix*> G4tgrRotationMatrixFactory::theTgrRotMatList private
Definition at line 80 of file G4tgrRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 80 of file G4tgrRotationMatrixFactory.hh
Referenced by AddRotMatrix(), and GetRotMatList().
G4mstgrrotm G4tgrRotationMatrixFactory::theTgrRotMats private
Definition at line 81 of file G4tgrRotationMatrixFactory.hh.
View newest version in sPHENIX GitHub at line 81 of file G4tgrRotationMatrixFactory.hh
Referenced by AddRotMatrix(), DumpRotmList(), FindRotMatrix(), GetRotMatMap(), and ~G4tgrRotationMatrixFactory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrRotationMatrixFactory.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrRotationMatrixFactory.cc