ECCE @ EIC Software: G4RK547FEq3 Class Reference
G4RK547FEq3 Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4RK547FEq3.hh>
Public Member Functions
G4RK547FEq3 (G4EquationOfMotion *EqRhs, G4int integrationVariables=6)
G4RK547FEq3 (const G4RK547FEq3 &)=delete
G4RK547FEq3 & operator= (const G4RK547FEq3 &)=delete
virtual void Stepper (const G4double yInput[], const G4double dydx[], G4double hstep, G4double yOutput[], G4double yError[]) override
void Stepper (const G4double yInput[], const G4double dydx[], G4double hstep, G4double yOutput[], G4double yError[], G4double dydxOutput[])
virtual G4double DistChord () const override
virtual G4int IntegratorOrder () const override
Public Member Functions inherited from G4MagIntegratorStepper
G4MagIntegratorStepper (G4EquationOfMotion *Equation, G4int numIntegrationVariables, G4int numStateVariables=12, G4bool isFSAL=false)
virtual ~G4MagIntegratorStepper ()=default
G4MagIntegratorStepper (const G4MagIntegratorStepper &)=delete
G4MagIntegratorStepper & operator= (const G4MagIntegratorStepper &)=delete
void NormaliseTangentVector (G4double vec[6])
void NormalisePolarizationVector (G4double vec[12])
void RightHandSide (const G4double y[], G4double dydx[]) const
void RightHandSide (const G4double y[], G4double dydx[], G4double field[]) const
G4int GetNumberOfVariables () const
G4int GetNumberOfStateVariables () const
G4int IntegrationOrder ()
G4EquationOfMotion * GetEquationOfMotion ()
const G4EquationOfMotion * GetEquationOfMotion () const
void SetEquationOfMotion (G4EquationOfMotion *newEquation)
unsigned long GetfNoRHSCalls ()
void ResetfNORHSCalls ()
G4bool IsFSAL () const
Private Member Functions
void makeStep (const G4double yInput[], const G4double dydx[], const G4double hstep, G4double yOutput[], G4double *dydxOutput=nullptr, G4double *yError=nullptr) const
Private Attributes
G4double fyIn [G4FieldTrack::ncompSVEC]
G4double fdydx [G4FieldTrack::ncompSVEC]
G4double fyOut [G4FieldTrack::ncompSVEC]
G4double fdydxOut [G4FieldTrack::ncompSVEC]
G4double fhstep = -1.0
Additional Inherited Members
Protected Member Functions inherited from G4MagIntegratorStepper
void SetIntegrationOrder (G4int order)
void SetFSAL (G4bool flag=true)
Detailed Description
Definition at line 44 of file G4RK547FEq3.hh.
View newest version in sPHENIX GitHub at line 44 of file G4RK547FEq3.hh
Constructor & Destructor Documentation
G4RK547FEq3::G4RK547FEq3 (G4EquationOfMotion * EqRhs, G4int integrationVariables = 6)
Definition at line 51 of file G4RK547FEq3.cc.
View newest version in sPHENIX GitHub at line 51 of file G4RK547FEq3.cc
G4RK547FEq3::G4RK547FEq3 (const G4RK547FEq3 &) delete
Member Function Documentation
G4double G4RK547FEq3::DistChord () const override virtual
Implements G4MagIntegratorStepper.
Definition at line 167 of file G4RK547FEq3.cc.
View newest version in sPHENIX GitHub at line 167 of file G4RK547FEq3.cc
References G4LineSection::Distline(), fdydx, fhstep, fyIn, fyOut, makeStep(), field_utils::makeVector(), and G4FieldTrack::ncompSVEC.
virtual G4int G4RK547FEq3::IntegratorOrder () const inline override virtual
Implements G4MagIntegratorStepper.
Definition at line 67 of file G4RK547FEq3.hh.
View newest version in sPHENIX GitHub at line 67 of file G4RK547FEq3.hh
void G4RK547FEq3::makeStep (const G4double yInput[], const G4double dydx[], const G4double hstep, G4double yOutput[], G4double * dydxOutput = nullptr, G4double * yError = nullptr) const private
Definition at line 56 of file G4RK547FEq3.cc.
View newest version in sPHENIX GitHub at line 56 of file G4RK547FEq3.cc
References ak2, G4MagIntegratorStepper::GetNumberOfStateVariables(), G4MagIntegratorStepper::GetNumberOfVariables(), G4FieldTrack::ncompSVEC, and G4MagIntegratorStepper::RightHandSide().
Referenced by DistChord(), and Stepper().
G4RK547FEq3& G4RK547FEq3::operator= (const G4RK547FEq3 &) delete
void G4RK547FEq3::Stepper (const G4double yInput[], const G4double dydx[], G4double hstep, G4double yOutput[], G4double yError[]) override virtual
Implements G4MagIntegratorStepper.
Definition at line 135 of file G4RK547FEq3.cc.
View newest version in sPHENIX GitHub at line 135 of file G4RK547FEq3.cc
References field_utils::copy(), fdydx, fdydxOut, fhstep, fyIn, fyOut, and makeStep().
void G4RK547FEq3::Stepper (const G4double yInput[], const G4double dydx[], G4double hstep, G4double yOutput[], G4double yError[], G4double dydxOutput[])
Definition at line 150 of file G4RK547FEq3.cc.
View newest version in sPHENIX GitHub at line 150 of file G4RK547FEq3.cc
References field_utils::copy(), fdydx, fdydxOut, fhstep, fyIn, fyOut, and makeStep().
Member Data Documentation
G4double G4RK547FEq3::fdydx[G4FieldTrack::ncompSVEC] private
Definition at line 79 of file G4RK547FEq3.hh.
View newest version in sPHENIX GitHub at line 79 of file G4RK547FEq3.hh
Referenced by DistChord(), and Stepper().
G4double G4RK547FEq3::fdydxOut[G4FieldTrack::ncompSVEC] private
Definition at line 79 of file G4RK547FEq3.hh.
View newest version in sPHENIX GitHub at line 79 of file G4RK547FEq3.hh
Referenced by Stepper().
G4double G4RK547FEq3::fhstep = -1.0 private
Definition at line 84 of file G4RK547FEq3.hh.
View newest version in sPHENIX GitHub at line 84 of file G4RK547FEq3.hh
Referenced by DistChord(), and Stepper().
G4double G4RK547FEq3::fyIn[G4FieldTrack::ncompSVEC] private
Definition at line 79 of file G4RK547FEq3.hh.
View newest version in sPHENIX GitHub at line 79 of file G4RK547FEq3.hh
Referenced by DistChord(), and Stepper().
G4double G4RK547FEq3::fyOut[G4FieldTrack::ncompSVEC] private
Definition at line 79 of file G4RK547FEq3.hh.
View newest version in sPHENIX GitHub at line 79 of file G4RK547FEq3.hh
Referenced by DistChord(), and Stepper().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4RK547FEq3.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4RK547FEq3.cc