ECCE @ EIC Software: G4VExternalPhysicalVolume Class Reference
G4VExternalPhysicalVolume Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4VExternalPhysicalVolume.hh>
Public Member Functions
G4VExternalPhysicalVolume (G4RotationMatrix *pRot, const G4ThreeVector &tlate, G4LogicalVolume *pCurrentLogical, const G4String &pName, G4VPhysicalVolume *pMother)
G4VExternalPhysicalVolume (const G4VExternalPhysicalVolume &)=delete
G4VExternalPhysicalVolume & operator= (const G4VExternalPhysicalVolume &)=delete
virtual ~G4VExternalPhysicalVolume ()
virtual G4bool CheckOverlaps (G4int res=1000, G4double tol=0., G4bool verbose=true, G4int maxErr=1)=0
G4VExternalPhysicalVolume (__void__ &)
EVolume VolumeType () const final
G4bool IsMany () const final
G4bool IsReplicated () const final
G4bool IsParameterised () const final
G4VPVParameterisation * GetParameterisation () const final
void GetReplicationData (EAxis &axis, G4int &nReplicas, G4double &width, G4double &offset, G4bool &consuming) const final
G4bool IsRegularStructure () const final
G4int GetRegularStructureId () const final
void SetMany (G4bool overlap)
Public Member Functions inherited from G4VPhysicalVolume
G4VPhysicalVolume (G4RotationMatrix *pRot, const G4ThreeVector &tlate, const G4String &pName, G4LogicalVolume *pLogical, G4VPhysicalVolume *pMother)
virtual ~G4VPhysicalVolume ()
G4VPhysicalVolume (const G4VPhysicalVolume &)=delete
G4VPhysicalVolume & operator= (const G4VPhysicalVolume &)=delete
G4bool operator== (const G4VPhysicalVolume &p) const
G4RotationMatrix * GetObjectRotation () const
G4RotationMatrix GetObjectRotationValue () const
G4ThreeVector GetObjectTranslation () const
const G4RotationMatrix * GetFrameRotation () const
G4ThreeVector GetFrameTranslation () const
const G4ThreeVector GetTranslation () const
const G4RotationMatrix * GetRotation () const
void SetTranslation (const G4ThreeVector &v)
G4RotationMatrix * GetRotation ()
void SetRotation (G4RotationMatrix *)
G4LogicalVolume * GetLogicalVolume () const
void SetLogicalVolume (G4LogicalVolume *pLogical)
G4LogicalVolume * GetMotherLogical () const
void SetMotherLogical (G4LogicalVolume *pMother)
const G4String & GetName () const
void SetName (const G4String &pName)
virtual G4int GetMultiplicity () const
virtual G4int GetCopyNo () const =0
virtual void SetCopyNo (G4int CopyNo)=0
G4VPhysicalVolume (__void__ &)
G4int GetInstanceID () const
EVolume DeduceVolumeType () const
Private Attributes
G4bool fMany = false
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicalVolume
static const G4PVManager & GetSubInstanceManager ()
static void Clean ()
Protected Member Functions inherited from G4VPhysicalVolume
void InitialiseWorker (G4VPhysicalVolume *pMasterObject, G4RotationMatrix *pRot, const G4ThreeVector &tlate)
void TerminateWorker (G4VPhysicalVolume *pMasterObject)
Protected Attributes inherited from G4VPhysicalVolume
G4int instanceID
Static Protected Attributes inherited from G4VPhysicalVolume
static G4GEOM_DLL G4PVManager subInstanceManager
Detailed Description
Definition at line 45 of file G4VExternalPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 45 of file G4VExternalPhysicalVolume.hh
Constructor & Destructor Documentation
G4VExternalPhysicalVolume::G4VExternalPhysicalVolume (G4RotationMatrix * pRot, const G4ThreeVector & tlate, G4LogicalVolume * pCurrentLogical, const G4String & pName, G4VPhysicalVolume * pMother)
Definition at line 41 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VExternalPhysicalVolume.cc
References G4LogicalVolume::AddDaughter(), FatalException, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), and G4VPhysicalVolume::SetMotherLogical().
G4VExternalPhysicalVolume::G4VExternalPhysicalVolume (const G4VExternalPhysicalVolume &) delete
G4VExternalPhysicalVolume::~G4VExternalPhysicalVolume () virtual
Definition at line 74 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 74 of file G4VExternalPhysicalVolume.cc
G4VExternalPhysicalVolume::G4VExternalPhysicalVolume (__void__ & a)
Definition at line 66 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 66 of file G4VExternalPhysicalVolume.cc
Member Function Documentation
virtual G4bool G4VExternalPhysicalVolume::CheckOverlaps (G4int res = 1000, G4double tol = 0., G4bool verbose = true, G4int maxErr = 1) pure virtual
Reimplemented from G4VPhysicalVolume.
G4VPVParameterisation * G4VExternalPhysicalVolume::GetParameterisation () const final virtual
Implements G4VPhysicalVolume.
Definition at line 113 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 113 of file G4VExternalPhysicalVolume.cc
G4int G4VExternalPhysicalVolume::GetRegularStructureId () const final virtual
Implements G4VPhysicalVolume.
Definition at line 142 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 142 of file G4VExternalPhysicalVolume.cc
void G4VExternalPhysicalVolume::GetReplicationData (EAxis & axis, G4int & nReplicas, G4double & width, G4double & offset, G4bool & consuming) const final virtual
Implements G4VPhysicalVolume.
Definition at line 122 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 122 of file G4VExternalPhysicalVolume.cc
G4bool G4VExternalPhysicalVolume::IsMany () const final virtual
Implements G4VPhysicalVolume.
Definition at line 81 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 81 of file G4VExternalPhysicalVolume.cc
References fMany.
G4bool G4VExternalPhysicalVolume::IsParameterised () const final virtual
Implements G4VPhysicalVolume.
Definition at line 105 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 105 of file G4VExternalPhysicalVolume.cc
G4bool G4VExternalPhysicalVolume::IsRegularStructure () const final virtual
Implements G4VPhysicalVolume.
Definition at line 132 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 132 of file G4VExternalPhysicalVolume.cc
G4bool G4VExternalPhysicalVolume::IsReplicated () const final virtual
Implements G4VPhysicalVolume.
Definition at line 97 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 97 of file G4VExternalPhysicalVolume.cc
G4VExternalPhysicalVolume& G4VExternalPhysicalVolume::operator= (const G4VExternalPhysicalVolume &) delete
void G4VExternalPhysicalVolume::SetMany (G4bool overlap)
Definition at line 89 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 89 of file G4VExternalPhysicalVolume.cc
References fMany.
EVolume G4VExternalPhysicalVolume::VolumeType () const final virtual
Implements G4VPhysicalVolume.
Definition at line 152 of file G4VExternalPhysicalVolume.cc.
View newest version in sPHENIX GitHub at line 152 of file G4VExternalPhysicalVolume.cc
References kExternal.
Member Data Documentation
G4bool G4VExternalPhysicalVolume::fMany = false private
Definition at line 101 of file G4VExternalPhysicalVolume.hh.
View newest version in sPHENIX GitHub at line 101 of file G4VExternalPhysicalVolume.hh
Referenced by IsMany(), and SetMany().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/volumes/include/G4VExternalPhysicalVolume.hh
geant4/tree/geant4-10.6-release/source/geometry/volumes/src/G4VExternalPhysicalVolume.cc