ECCE @ EIC Software: G4ParticleHPLevel Class Reference
G4ParticleHPLevel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPLevel.hh>
Public Member Functions
G4ParticleHPLevel ()
~G4ParticleHPLevel ()
void SetNumberOfGammas (G4int aGammas)
void SetGamma (G4int i, G4ParticleHPGamma *aGamma)
G4DynamicParticleVector * GetDecayGammas ()
void SetLevelEnergy (G4double anEnergy)
G4double GetLevelEnergy ()
G4double GetGammaEnergy (G4int i)
Private Attributes
G4double levelEnergy
G4int nGammas
G4ParticleHPGamma ** theGammas
Detailed Description
Definition at line 40 of file G4ParticleHPLevel.hh.
View newest version in sPHENIX GitHub at line 40 of file G4ParticleHPLevel.hh
Constructor & Destructor Documentation
G4ParticleHPLevel::G4ParticleHPLevel () inline
Definition at line 44 of file G4ParticleHPLevel.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPLevel.hh
References levelEnergy, nGammas, and theGammas.
G4ParticleHPLevel::~G4ParticleHPLevel ()
Definition at line 35 of file G4ParticleHPLevel.cc.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleHPLevel.cc
References nGammas, and theGammas.
Member Function Documentation
G4DynamicParticleVector * G4ParticleHPLevel::GetDecayGammas ()
Definition at line 66 of file G4ParticleHPLevel.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPLevel.cc
References G4UniformRand, G4ParticleHPGamma::GetDecayGammas(), G4ParticleHPGamma::GetWeight(), it, nGammas, sum, and theGammas.
Referenced by G4ParticleHPGamma::GetDecayGammas().
G4double G4ParticleHPLevel::GetGammaEnergy (G4int i)
Definition at line 61 of file G4ParticleHPLevel.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleHPLevel.cc
References G4ParticleHPGamma::GetGammaEnergy(), and theGammas.
G4double G4ParticleHPLevel::GetLevelEnergy () inline
Definition at line 64 of file G4ParticleHPLevel.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleHPLevel.hh
References levelEnergy.
Referenced by G4ParticleHPInelasticCompFS::CompositeApply(), G4ParticleHPDeExGammas::GetLevelEnergy(), and G4ParticleHPDeExGammas::Init().
void G4ParticleHPLevel::SetGamma (G4int i, G4ParticleHPGamma * aGamma)
Definition at line 55 of file G4ParticleHPLevel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPLevel.cc
References G4ParticleHPGamma::GetLevelEnergy(), SetLevelEnergy(), and theGammas.
Referenced by G4ParticleHPDeExGammas::Init().
void G4ParticleHPLevel::SetLevelEnergy (G4double anEnergy) inline
Definition at line 59 of file G4ParticleHPLevel.hh.
View newest version in sPHENIX GitHub at line 59 of file G4ParticleHPLevel.hh
References levelEnergy.
Referenced by SetGamma().
void G4ParticleHPLevel::SetNumberOfGammas (G4int aGammas)
Definition at line 44 of file G4ParticleHPLevel.cc.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPLevel.cc
References nGammas, and theGammas.
Referenced by G4ParticleHPDeExGammas::Init().
Member Data Documentation
G4double G4ParticleHPLevel::levelEnergy private
Definition at line 73 of file G4ParticleHPLevel.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleHPLevel.hh
Referenced by G4ParticleHPLevel(), GetLevelEnergy(), and SetLevelEnergy().
G4int G4ParticleHPLevel::nGammas private
Definition at line 75 of file G4ParticleHPLevel.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ParticleHPLevel.hh
Referenced by G4ParticleHPLevel(), GetDecayGammas(), SetNumberOfGammas(), and ~G4ParticleHPLevel().
G4ParticleHPGamma** G4ParticleHPLevel::theGammas private
Definition at line 76 of file G4ParticleHPLevel.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleHPLevel.hh
Referenced by G4ParticleHPLevel(), GetDecayGammas(), GetGammaEnergy(), SetGamma(), SetNumberOfGammas(), and ~G4ParticleHPLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPLevel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPLevel.cc