ECCE @ EIC Software: G4PartialPhantomParameterisation Class Reference
G4PartialPhantomParameterisation Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4PartialPhantomParameterisation.hh>
Public Member Functions
G4PartialPhantomParameterisation ()
~G4PartialPhantomParameterisation ()
void ComputeTransformation (const G4int, G4VPhysicalVolume *) const
G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
G4int GetReplicaNo (const G4ThreeVector &localPoint, const G4ThreeVector &localDir)
G4ThreeVector GetTranslation (const G4int copyNo) const
size_t GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
size_t GetMaterialIndex (size_t copyNo) const
G4Material * GetMaterial (size_t nx, size_t ny, size_t nz) const
G4Material * GetMaterial (size_t copyNo) const
void SetFilledIDs (std::multimap< G4int, G4int > fid)
void SetFilledMins (std::map< G4int, std::map< G4int, G4int > > fmins)
void BuildContainerWalls ()
Public Member Functions inherited from G4PhantomParameterisation
G4PhantomParameterisation ()
~G4PhantomParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
void BuildContainerSolid (G4VPhysicalVolume *pPhysicalVol)
void BuildContainerSolid (G4VSolid *pMotherSolid)
void SetMaterials (std::vector< G4Material * > &mates)
void SetMaterialIndices (size_t *matInd)
void SetVoxelDimensions (G4double halfx, G4double halfy, G4double halfz)
void SetNoVoxel (size_t nx, size_t ny, size_t nz)
G4double GetVoxelHalfX () const
G4double GetVoxelHalfY () const
G4double GetVoxelHalfZ () const
size_t GetNoVoxelX () const
size_t GetNoVoxelY () const
size_t GetNoVoxelZ () const
size_t GetNoVoxel () const
std::vector< G4Material * > GetMaterials () const
size_t * GetMaterialIndices () const
G4VSolid * GetContainerSolid () const
G4ThreeVector GetTranslation (const G4int copyNo) const
G4bool SkipEqualMaterials () const
void SetSkipEqualMaterials (G4bool skip)
size_t GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
size_t GetMaterialIndex (size_t copyNo) const
G4Material * GetMaterial (size_t nx, size_t ny, size_t nz) const
G4Material * GetMaterial (size_t copyNo) const
void CheckVoxelsFillContainer (G4double contX, G4double contY, G4double contZ) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeVoxelIndices (const G4int copyNo, size_t &nx, size_t &ny, size_t &nz) const
void CheckCopyNo (const G4int copyNo) const
Private Attributes
std::multimap< G4int, G4int > fFilledIDs
std::map< G4int, std::map
< G4int, G4int > > fFilledMins
Additional Inherited Members
Protected Attributes inherited from G4PhantomParameterisation
G4double fVoxelHalfX = 0.0
G4double fVoxelHalfY = 0.0
G4double fVoxelHalfZ = 0.0
size_t fNoVoxelX = 0
size_t fNoVoxelY = 0
size_t fNoVoxelZ = 0
size_t fNoVoxelXY = 0
size_t fNoVoxel = 0
std::vector< G4Material * > fMaterials
size_t * fMaterialIndices = nullptr
G4VSolid * fContainerSolid = nullptr
G4double fContainerWallX =0.0
G4double fContainerWallY =0.0
G4double fContainerWallZ =0.0
G4double kCarTolerance
G4bool bSkipEqualMaterials = true
Detailed Description
Definition at line 52 of file G4PartialPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 52 of file G4PartialPhantomParameterisation.hh
Constructor & Destructor Documentation
G4PartialPhantomParameterisation::G4PartialPhantomParameterisation ()
Definition at line 44 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 44 of file G4PartialPhantomParameterisation.cc
G4PartialPhantomParameterisation::~G4PartialPhantomParameterisation ()
Definition at line 51 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 51 of file G4PartialPhantomParameterisation.cc
Member Function Documentation
void G4PartialPhantomParameterisation::BuildContainerWalls ()
Definition at line 334 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 334 of file G4PartialPhantomParameterisation.cc
References G4PhantomParameterisation::fContainerWallX, G4PhantomParameterisation::fContainerWallY, G4PhantomParameterisation::fContainerWallZ, G4PhantomParameterisation::fNoVoxelX, G4PhantomParameterisation::fNoVoxelY, G4PhantomParameterisation::fNoVoxelZ, G4PhantomParameterisation::fVoxelHalfX, G4PhantomParameterisation::fVoxelHalfY, and G4PhantomParameterisation::fVoxelHalfZ.
Referenced by DicomPartialDetectorConstruction::ConstructPhantom().
void G4PartialPhantomParameterisation::CheckCopyNo (const G4int copyNo) const private
Definition at line 319 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 319 of file G4PartialPhantomParameterisation.cc
References FatalErrorInArgument, G4PhantomParameterisation::fNoVoxel, G4endl, G4Exception(), and message().
Referenced by ComputeMaterial(), ComputeVoxelIndices(), GetMaterialIndex(), and GetTranslation().
G4Material * G4PartialPhantomParameterisation::ComputeMaterial (const G4int repNo, G4VPhysicalVolume * currentVol, const G4VTouchable * parentTouch = nullptr) virtual
Reimplemented from G4PhantomParameterisation.
Definition at line 84 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 84 of file G4PartialPhantomParameterisation.cc
References CheckCopyNo(), G4PhantomParameterisation::fMaterials, and GetMaterialIndex().
void G4PartialPhantomParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4PhantomParameterisation.
Definition at line 57 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 57 of file G4PartialPhantomParameterisation.cc
References GetTranslation(), and G4VPhysicalVolume::SetTranslation().
void G4PartialPhantomParameterisation::ComputeVoxelIndices (const G4int copyNo, size_t & nx, size_t & ny, size_t & nz) const private
Definition at line 132 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 132 of file G4PartialPhantomParameterisation.cc
References CheckCopyNo(), fFilledIDs, and G4PhantomParameterisation::fNoVoxelY.
Referenced by GetTranslation().
G4Material * G4PartialPhantomParameterisation::GetMaterial (size_t nx, size_t ny, size_t nz) const
Definition at line 116 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 116 of file G4PartialPhantomParameterisation.cc
References G4PhantomParameterisation::fMaterials, and GetMaterialIndex().
G4Material * G4PartialPhantomParameterisation::GetMaterial (size_t copyNo) const
Definition at line 124 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 124 of file G4PartialPhantomParameterisation.cc
References G4PhantomParameterisation::fMaterials, and GetMaterialIndex().
size_t G4PartialPhantomParameterisation::GetMaterialIndex (size_t nx, size_t ny, size_t nz) const
Definition at line 107 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 107 of file G4PartialPhantomParameterisation.cc
References G4PhantomParameterisation::fNoVoxelX, and G4PhantomParameterisation::fNoVoxelXY.
Referenced by ComputeMaterial(), and GetMaterial().
size_t G4PartialPhantomParameterisation::GetMaterialIndex (size_t copyNo) const
Definition at line 95 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 95 of file G4PartialPhantomParameterisation.cc
References CheckCopyNo(), and G4PhantomParameterisation::fMaterialIndices.
G4int G4PartialPhantomParameterisation::GetReplicaNo (const G4ThreeVector & localPoint, const G4ThreeVector & localDir) virtual
Reimplemented from G4PhantomParameterisation.
Definition at line 160 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 160 of file G4PartialPhantomParameterisation.cc
References G4PhantomParameterisation::fContainerWallX, G4PhantomParameterisation::fContainerWallY, G4PhantomParameterisation::fContainerWallZ, fFilledIDs, G4PhantomParameterisation::fNoVoxelX, G4PhantomParameterisation::fNoVoxelY, G4PhantomParameterisation::fNoVoxelZ, G4PhantomParameterisation::fVoxelHalfX, G4PhantomParameterisation::fVoxelHalfY, G4PhantomParameterisation::fVoxelHalfZ, G4endl, G4Exception(), JustWarning, G4PhantomParameterisation::kCarTolerance, message(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4ThreeVector G4PartialPhantomParameterisation::GetTranslation (const G4int copyNo) const
Definition at line 68 of file G4PartialPhantomParameterisation.cc.
View newest version in sPHENIX GitHub at line 68 of file G4PartialPhantomParameterisation.cc
References CheckCopyNo(), ComputeVoxelIndices(), G4PhantomParameterisation::fContainerWallX, G4PhantomParameterisation::fContainerWallY, G4PhantomParameterisation::fContainerWallZ, G4PhantomParameterisation::fVoxelHalfX, G4PhantomParameterisation::fVoxelHalfY, and G4PhantomParameterisation::fVoxelHalfZ.
Referenced by ComputeTransformation().
void G4PartialPhantomParameterisation::SetFilledIDs (std::multimap< G4int, G4int > fid) inline
Definition at line 78 of file G4PartialPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 78 of file G4PartialPhantomParameterisation.hh
References fFilledIDs.
Referenced by DicomPartialDetectorConstruction::ConstructPhantom().
void G4PartialPhantomParameterisation::SetFilledMins (std::map< G4int, std::map< G4int, G4int > > fmins) inline
Definition at line 83 of file G4PartialPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 83 of file G4PartialPhantomParameterisation.hh
References fFilledMins.
Referenced by DicomPartialDetectorConstruction::ConstructPhantom().
Member Data Documentation
std::multimap<G4int,G4int> G4PartialPhantomParameterisation::fFilledIDs private
Definition at line 101 of file G4PartialPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 101 of file G4PartialPhantomParameterisation.hh
Referenced by ComputeVoxelIndices(), GetReplicaNo(), and SetFilledIDs().
std::map< G4int, std::map<G4int,G4int> > G4PartialPhantomParameterisation::fFilledMins private
Definition at line 102 of file G4PartialPhantomParameterisation.hh.
View newest version in sPHENIX GitHub at line 102 of file G4PartialPhantomParameterisation.hh
Referenced by SetFilledMins().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4PartialPhantomParameterisation.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4PartialPhantomParameterisation.cc