ECCE @ EIC Software: G4INCL::ParticleConfig Namespace Reference
G4INCL::ParticleConfig Namespace Reference
Functions
G4bool isPair (Particle const *const p1, Particle const *const p2, ParticleType t1, ParticleType t2)
Function Documentation
G4bool G4INCL::ParticleConfig::isPair (Particle const *const p1, Particle const *const p2, ParticleType t1, ParticleType t2)
Definition at line 110 of file G4INCLGlobals.cc.
View newest version in sPHENIX GitHub at line 110 of file G4INCLGlobals.cc
References G4INCL::Particle::getType(), t1, and t2.
Referenced by G4INCL::PiNToDeltaChannel::fillFinalState(), and G4INCL::StrangeAbsorbtionChannel::fillFinalState().