ECCE @ EIC Software: G4INCL::FinalState Class Reference
G4INCL::FinalState Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLFinalState.hh>
Public Member Functions
FinalState ()
virtual ~FinalState ()
void reset ()
void setTotalEnergyBeforeInteraction (G4double E)
G4double getTotalEnergyBeforeInteraction () const
void addModifiedParticle (Particle *p)
void addOutgoingParticle (Particle *p)
void addDestroyedParticle (Particle *p)
void addCreatedParticle (Particle *p)
void addEnteringParticle (Particle *p)
ParticleList const & getModifiedParticles () const
ParticleList const & getOutgoingParticles () const
ParticleList const & getDestroyedParticles () const
ParticleList const & getCreatedParticles () const
ParticleList const & getEnteringParticles () const
FinalStateValidity getValidity () const
void makeValid ()
void makePauliBlocked ()
void makeNoEnergyConservation ()
void makeParticleBelowFermi ()
void makeParticleBelowZero ()
std::string print () const
Private Attributes
ParticleList outgoing
ParticleList created
ParticleList destroyed
ParticleList modified
ParticleList entering
G4double totalEnergyBeforeInteraction
FinalStateValidity validity
Detailed Description
Final state of an interaction
Definition at line 64 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 64 of file G4INCLFinalState.hh
Constructor & Destructor Documentation
G4INCL::FinalState::FinalState ()
Definition at line 42 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 42 of file G4INCLFinalState.cc
References reset().
G4INCL::FinalState::~FinalState () virtual
Definition at line 46 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 46 of file G4INCLFinalState.cc
Member Function Documentation
void G4INCL::FinalState::addCreatedParticle (Particle * p)
Definition at line 75 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 75 of file G4INCLFinalState.cc
References created.
Referenced by G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), and G4INCL::PionResonanceDecayChannel::fillFinalState().
void G4INCL::FinalState::addDestroyedParticle (Particle * p)
Definition at line 70 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 70 of file G4INCLFinalState.cc
References destroyed.
Referenced by G4INCL::PiNToDeltaChannel::fillFinalState().
void G4INCL::FinalState::addEnteringParticle (Particle * p)
Definition at line 80 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 80 of file G4INCLFinalState.cc
References entering.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState().
void G4INCL::FinalState::addModifiedParticle (Particle * p)
Definition at line 60 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 60 of file G4INCLFinalState.cc
References modified.
Referenced by G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::NDeltaToDeltaLKChannel::fillFinalState(), G4INCL::NKbElasticChannel::fillFinalState(), G4INCL::NKbToL2piChannel::fillFinalState(), G4INCL::NNToMultiPionsChannel::fillFinalState(), G4INCL::NNToNLK2piChannel::fillFinalState(), G4INCL::NNToNLKChannel::fillFinalState(), G4INCL::PiNToMultiPionsChannel::fillFinalState(), G4INCL::PiNToEtaChannel::fillFinalState(), G4INCL::PiNToDeltaChannel::fillFinalState(), G4INCL::PiNElasticChannel::fillFinalState(), G4INCL::OmegaNToPiPiNChannel::fillFinalState(), G4INCL::OmegaNToPiNChannel::fillFinalState(), G4INCL::OmegaNElasticChannel::fillFinalState(), G4INCL::NYElasticChannel::fillFinalState(), G4INCL::NSToNSChannel::fillFinalState(), G4INCL::NSToNLChannel::fillFinalState(), G4INCL::NpiToSKpiChannel::fillFinalState(), G4INCL::NNToNLKpiChannel::fillFinalState(), G4INCL::NpiToSK2piChannel::fillFinalState(), G4INCL::NpiToNKKbChannel::fillFinalState(), G4INCL::NpiToMissingStrangenessChannel::fillFinalState(), G4INCL::NKbToLpiChannel::fillFinalState(), G4INCL::NpiToLKChannel::fillFinalState(), G4INCL::NpiToLK2piChannel::fillFinalState(), G4INCL::NNToNSKpiChannel::fillFinalState(), G4INCL::NNToNNEtaChannel::fillFinalState(), G4INCL::NNToNNKKbChannel::fillFinalState(), G4INCL::NKbToNKb2piChannel::fillFinalState(), G4INCL::NNToNNOmegaChannel::fillFinalState(), G4INCL::NNToNSK2piChannel::fillFinalState(), G4INCL::NDeltaToDeltaSKChannel::fillFinalState(), G4INCL::NKbToNKbChannel::fillFinalState(), G4INCL::NNToNSKChannel::fillFinalState(), G4INCL::NKbToNKbpiChannel::fillFinalState(), G4INCL::NNToMissingStrangenessChannel::fillFinalState(), G4INCL::PiNToOmegaChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NLToNSChannel::fillFinalState(), G4INCL::NKToNKpiChannel::fillFinalState(), G4INCL::NKToNKChannel::fillFinalState(), G4INCL::NKToNK2piChannel::fillFinalState(), G4INCL::NpiToSKChannel::fillFinalState(), G4INCL::NKbToS2piChannel::fillFinalState(), G4INCL::NpiToLKpiChannel::fillFinalState(), G4INCL::NKbToSpiChannel::fillFinalState(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::NDeltaToNLKChannel::fillFinalState(), G4INCL::NKElasticChannel::fillFinalState(), G4INCL::NDeltaToNNKKbChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NDeltaToNSKChannel::fillFinalState(), G4INCL::NNOmegaToMultiPionsChannel::fillFinalState(), G4INCL::StrangeAbsorbtionChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), G4INCL::ReflectionChannel::fillFinalState(), G4INCL::NDeltaOmegaProductionChannel::fillFinalState(), G4INCL::NeutralKaonDecayChannel::fillFinalState(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4INCL::SigmaZeroDecayChannel::fillFinalState(), G4INCL::DeltaDecayChannel::fillFinalState(), G4INCL::PionResonanceDecayChannel::fillFinalState(), G4INCL::RecombinationChannel::fillFinalState(), and G4INCL::DecayAvatar::postInteraction().
void G4INCL::FinalState::addOutgoingParticle (Particle * p)
Definition at line 65 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 65 of file G4INCLFinalState.cc
References outgoing.
Referenced by G4INCL::TransmissionChannel::fillFinalState(), and G4INCL::InteractionAvatar::postInteraction().
ParticleList const & G4INCL::FinalState::getCreatedParticles () const
Definition at line 100 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 100 of file G4INCLFinalState.cc
References created.
Referenced by G4INCL::CascadeAction::afterAvatarDefaultAction(), G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::DecayAvatar::postInteraction(), G4INCL::InteractionAvatar::postInteraction(), and G4INCL::StandardPropagationModel::propagate().
ParticleList const & G4INCL::FinalState::getDestroyedParticles () const
Definition at line 95 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 95 of file G4INCLFinalState.cc
References destroyed.
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::Nucleus::applyFinalState(), G4INCL::DecayAvatar::postInteraction(), and G4INCL::InteractionAvatar::postInteraction().
ParticleList const & G4INCL::FinalState::getEnteringParticles () const
Definition at line 105 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 105 of file G4INCLFinalState.cc
References entering.
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::Nucleus::applyFinalState(), and G4INCL::StandardPropagationModel::propagate().
ParticleList const & G4INCL::FinalState::getModifiedParticles () const
Definition at line 85 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 85 of file G4INCLFinalState.cc
References modified.
Referenced by G4INCL::CascadeAction::afterAvatarDefaultAction(), G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), G4INCL::DecayAvatar::postInteraction(), G4INCL::InteractionAvatar::postInteraction(), and G4INCL::StandardPropagationModel::propagate().
ParticleList const & G4INCL::FinalState::getOutgoingParticles () const
Definition at line 90 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 90 of file G4INCLFinalState.cc
References outgoing.
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::Nucleus::applyFinalState(), and G4INCL::SurfaceAvatar::postInteraction().
G4double G4INCL::FinalState::getTotalEnergyBeforeInteraction () const inline
Definition at line 72 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 72 of file G4INCLFinalState.hh
References totalEnergyBeforeInteraction.
Referenced by G4INCL::Nucleus::applyFinalState(), and G4INCL::InteractionAvatar::enforceEnergyConservation().
FinalStateValidity G4INCL::FinalState::getValidity () const inline
Definition at line 86 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 86 of file G4INCLFinalState.hh
References validity.
Referenced by G4INCL::Nucleus::applyFinalState(), G4INCL::Nucleus::decayInsideDeltas(), G4INCL::INCL::makeCompoundNucleus(), G4INCL::DecayAvatar::postInteraction(), G4INCL::BinaryCollisionAvatar::postInteraction(), and G4INCL::StandardPropagationModel::propagate().
void G4INCL::FinalState::makeNoEnergyConservation () inline
Definition at line 89 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 89 of file G4INCLFinalState.hh
References G4INCL::NoEnergyConservationFS, and validity.
Referenced by G4INCL::DecayAvatar::postInteraction(), and G4INCL::InteractionAvatar::postInteraction().
void G4INCL::FinalState::makeParticleBelowFermi () inline
Definition at line 90 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 90 of file G4INCLFinalState.hh
References G4INCL::ParticleBelowFermiFS, and validity.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState().
void G4INCL::FinalState::makeParticleBelowZero () inline
Definition at line 91 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 91 of file G4INCLFinalState.hh
References G4INCL::ParticleBelowZeroFS, and validity.
Referenced by G4INCL::ParticleEntryChannel::fillFinalState().
void G4INCL::FinalState::makePauliBlocked () inline
Definition at line 88 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 88 of file G4INCLFinalState.hh
References G4INCL::PauliBlockedFS, and validity.
Referenced by G4INCL::DecayAvatar::postInteraction(), and G4INCL::InteractionAvatar::postInteraction().
void G4INCL::FinalState::makeValid () inline
Definition at line 87 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 87 of file G4INCLFinalState.hh
References G4INCL::ValidFS, and validity.
std::string G4INCL::FinalState::print () const
Definition at line 110 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 110 of file G4INCLFinalState.cc
References created, destroyed, e, entering, modified, and outgoing.
Referenced by G4INCL::Nucleus::applyFinalState(), and G4INCL::InteractionAvatar::postInteraction().
void G4INCL::FinalState::reset ()
Definition at line 50 of file G4INCLFinalState.cc.
View newest version in sPHENIX GitHub at line 50 of file G4INCLFinalState.cc
References created, destroyed, entering, modified, outgoing, totalEnergyBeforeInteraction, G4INCL::ValidFS, and validity.
Referenced by G4INCL::INCL::cascade(), FinalState(), G4INCL::DecayAvatar::postInteraction(), and G4INCL::InteractionAvatar::postInteraction().
void G4INCL::FinalState::setTotalEnergyBeforeInteraction (G4double E) inline
Definition at line 71 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 71 of file G4INCLFinalState.hh
References E, and totalEnergyBeforeInteraction.
Referenced by G4INCL::ReflectionChannel::fillFinalState(), G4INCL::ParticleEntryChannel::fillFinalState(), G4INCL::TransmissionChannel::fillFinalState(), G4INCL::DecayAvatar::postInteraction(), and G4INCL::InteractionAvatar::postInteraction().
Member Data Documentation
ParticleList G4INCL::FinalState::created private
Definition at line 96 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 96 of file G4INCLFinalState.hh
Referenced by addCreatedParticle(), getCreatedParticles(), print(), and reset().
ParticleList G4INCL::FinalState::destroyed private
Definition at line 96 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 96 of file G4INCLFinalState.hh
Referenced by addDestroyedParticle(), getDestroyedParticles(), print(), and reset().
ParticleList G4INCL::FinalState::entering private
Definition at line 96 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 96 of file G4INCLFinalState.hh
Referenced by addEnteringParticle(), getEnteringParticles(), print(), and reset().
ParticleList G4INCL::FinalState::modified private
Definition at line 96 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 96 of file G4INCLFinalState.hh
Referenced by addModifiedParticle(), getModifiedParticles(), print(), and reset().
ParticleList G4INCL::FinalState::outgoing private
Definition at line 96 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 96 of file G4INCLFinalState.hh
Referenced by addOutgoingParticle(), getOutgoingParticles(), print(), and reset().
G4double G4INCL::FinalState::totalEnergyBeforeInteraction private
Definition at line 97 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 97 of file G4INCLFinalState.hh
Referenced by getTotalEnergyBeforeInteraction(), reset(), and setTotalEnergyBeforeInteraction().
FinalStateValidity G4INCL::FinalState::validity private
Definition at line 98 of file G4INCLFinalState.hh.
View newest version in sPHENIX GitHub at line 98 of file G4INCLFinalState.hh
Referenced by getValidity(), makeNoEnergyConservation(), makeParticleBelowFermi(), makeParticleBelowZero(), makePauliBlocked(), makeValid(), and reset().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLFinalState.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/src/G4INCLFinalState.cc