ECCE @ EIC Software: G4MoleculeTable Class Reference
G4MoleculeTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MoleculeTable.hh>
Public Member Functions
virtual ~G4MoleculeTable ()
G4MoleculeDefinition * CreateMoleculeDefinition (const G4String &userIdentifier, double diffusion_coefficient)
G4MolecularConfiguration * CreateConfiguration (const G4String &userIdentifier, const G4MoleculeDefinition *molDef, const G4String &configurationLabel, const G4ElectronOccupancy &eOcc)
G4MolecularConfiguration * CreateConfiguration (const G4String &userIdentifier, G4MoleculeDefinition *, int charge, double diffusion_coefficient=-1)
G4MolecularConfiguration * CreateConfiguration (const G4String &userIdentifier, G4MoleculeDefinition *)
G4MolecularConfiguration * CreateConfiguration (const G4String &userIdentifier, G4MoleculeDefinition *, const G4String &configurationLabel, int charge=0)
G4MoleculeDefinition * GetMoleculeDefinition (const G4String &, bool mustExist=true)
G4MolecularConfiguration * GetConfiguration (const G4String &, bool mustExist=true)
G4MolecularConfiguration * GetConfiguration (G4int id)
void Insert (G4MoleculeDefinition *)
void Finalize (G4MoleculeDefinition *)
void Finalize ()
G4MoleculeDefinitionIterator GetDefintionIterator ()
G4ConfigurationIterator GetConfigurationIterator ()
void PrepareMolecularConfiguration ()
int GetNumberOfDefinedSpecies ()
Static Public Member Functions
static G4MoleculeTable * Instance ()
static G4MoleculeTable * GetMoleculeTable ()
Protected Types
typedef std::map< G4String,
G4MoleculeDefinition * > MoleculeDefTable
Protected Member Functions
G4MoleculeTable ()
Protected Attributes
MoleculeDefTable fMoleculeDefTable
Static Protected Attributes
static G4MoleculeTable * fpgMoleculeTable
Detailed Description
Definition at line 58 of file G4MoleculeTable.hh.
View newest version in sPHENIX GitHub at line 58 of file G4MoleculeTable.hh
Member Typedef Documentation
typedef std::map<G4String, G4MoleculeDefinition*> G4MoleculeTable::MoleculeDefTable protected
Definition at line 131 of file G4MoleculeTable.hh.
View newest version in sPHENIX GitHub at line 131 of file G4MoleculeTable.hh
Constructor & Destructor Documentation
G4MoleculeTable::~G4MoleculeTable () virtual
Definition at line 47 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 47 of file G4MoleculeTable.cc
G4MoleculeTable::G4MoleculeTable () protected
Definition at line 41 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 41 of file G4MoleculeTable.cc
Referenced by Instance().
Member Function Documentation
G4MolecularConfiguration * G4MoleculeTable::CreateConfiguration (const G4String & userIdentifier, const G4MoleculeDefinition * molDef, const G4String & configurationLabel, const G4ElectronOccupancy & eOcc)
Definition at line 233 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 233 of file G4MoleculeTable.cc
References G4MolecularConfiguration::CreateMolecularConfiguration().
Referenced by G4EmDNAChemistry::ConstructMolecule(), and G4EmDNAChemistry_option1::ConstructMolecule().
G4MolecularConfiguration * G4MoleculeTable::CreateConfiguration (const G4String & userIdentifier, G4MoleculeDefinition * molDef, int charge, double diffusion_coefficient = -1)
Definition at line 209 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 209 of file G4MoleculeTable.cc
References G4MolecularConfiguration::CreateMolecularConfiguration(), and G4MolecularConfiguration::SetDiffusionCoefficient().
G4MolecularConfiguration * G4MoleculeTable::CreateConfiguration (const G4String & userIdentifier, G4MoleculeDefinition * molDef)
Definition at line 173 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 173 of file G4MoleculeTable.cc
References G4MolecularConfiguration::CreateMolecularConfiguration().
G4MolecularConfiguration * G4MoleculeTable::CreateConfiguration (const G4String & userIdentifier, G4MoleculeDefinition * molDef, const G4String & configurationLabel, int charge = 0)
Definition at line 189 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 189 of file G4MoleculeTable.cc
References G4MolecularConfiguration::CreateMolecularConfiguration().
G4MoleculeDefinition * G4MoleculeTable::CreateMoleculeDefinition (const G4String & userIdentifier, double diffusion_coefficient)
Definition at line 69 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 69 of file G4MoleculeTable.cc
void G4MoleculeTable::Finalize (G4MoleculeDefinition *) inline
Definition at line 112 of file G4MoleculeTable.hh.
View newest version in sPHENIX GitHub at line 112 of file G4MoleculeTable.hh
Referenced by G4MoleculeDefinition::Finalize(), G4DNAChemistryManager::InitializeThreadSharedData(), and G4DNAChemistryManager::Run().
void G4MoleculeTable::Finalize ()
Definition at line 252 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 252 of file G4MoleculeTable.cc
References G4MolecularConfiguration::FinalizeAll().
G4MolecularConfiguration * G4MoleculeTable::GetConfiguration (const G4String & name, bool mustExist = true)
Definition at line 105 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 105 of file G4MoleculeTable.cc
References FatalException, G4endl, G4Exception(), and G4MolecularConfiguration::GetMolecularConfiguration().
Referenced by G4MoleculeGun::BuildAndPushTrack(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option2::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructMolecule(), G4EmDNAChemistry::ConstructReactionTable(), G4EmDNAChemistry_option1::ConstructReactionTable(), G4EmDNAChemistry_option2::ConstructReactionTable(), G4DNAMolecularReactionTable::GetReactionData(), G4DNAMolecularMaterial::SetMolecularConfiguration(), G4DNAMolecularReactionData::SetReactant1(), G4DNAMolecularReactionData::SetReactant2(), and G4DNAMolecularReactionData::SetReactants().
G4MolecularConfiguration * G4MoleculeTable::GetConfiguration (G4int id)
Definition at line 128 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 128 of file G4MoleculeTable.cc
References G4MolecularConfiguration::GetMolecularConfiguration().
G4ConfigurationIterator G4MoleculeTable::GetConfigurationIterator ()
Definition at line 259 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 259 of file G4MoleculeTable.cc
References G4MolecularConfiguration::GetUserIDTable().
Referenced by G4MoleculeCounter::Initialize(), and G4MolecularConfiguration::ScaleAllDiffusionCoefficientsOnWater().
G4MoleculeDefinitionIterator G4MoleculeTable::GetDefintionIterator () inline
Definition at line 116 of file G4MoleculeTable.hh.
View newest version in sPHENIX GitHub at line 116 of file G4MoleculeTable.hh
References fMoleculeDefTable.
Referenced by G4VUserChemistryList::BuildPhysicsTable(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), and G4EmDNAChemistry_option2::ConstructProcess().
G4MoleculeDefinition * G4MoleculeTable::GetMoleculeDefinition (const G4String & name, bool mustExist = true)
Definition at line 79 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 79 of file G4MoleculeTable.cc
References FatalException, fMoleculeDefTable, G4endl, G4Exception(), and it.
Referenced by G4MolecularConfiguration::Unserialize().
G4MoleculeTable * G4MoleculeTable::GetMoleculeTable () static
Definition at line 61 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 61 of file G4MoleculeTable.cc
References Instance().
Referenced by G4DNAMolecularReactionTable::GetReactionData().
int G4MoleculeTable::GetNumberOfDefinedSpecies ()
Definition at line 266 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 266 of file G4MoleculeTable.cc
References G4MolecularConfiguration::GetNumberOfSpecies().
void G4MoleculeTable::Insert (G4MoleculeDefinition * moleculeDefinition)
Definition at line 138 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 138 of file G4MoleculeTable.cc
References FatalException, fMoleculeDefTable, G4endl, G4Exception(), G4MoleculeDefinition::GetName(), and it.
Referenced by G4MoleculeDefinition::G4MoleculeDefinition().
G4MoleculeTable * G4MoleculeTable::Instance (void) static
Definition at line 53 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 53 of file G4MoleculeTable.cc
References fpgMoleculeTable, and G4MoleculeTable().
Referenced by G4DNAMolecularReactionData::AddProduct(), G4MoleculeGun::BuildAndPushTrack(), G4DNAElectronHoleRecombination::BuildDissociationChannels(), G4VUserChemistryList::BuildPhysicsTable(), G4EmDNAChemistry::ConstructDissociationChannels(), G4EmDNAChemistry_option1::ConstructDissociationChannels(), G4EmDNAChemistry_option2::ConstructDissociationChannels(), G4EmDNAChemistry::ConstructMolecule(), G4EmDNAChemistry_option1::ConstructMolecule(), G4EmDNAChemistry_option2::ConstructMolecule(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), G4EmDNAChemistry::ConstructReactionTable(), G4EmDNAChemistry_option1::ConstructReactionTable(), G4EmDNAChemistry_option2::ConstructReactionTable(), G4MoleculeDefinition::Finalize(), G4MoleculeDefinition::G4MoleculeDefinition(), GetMoleculeTable(), G4MoleculeCounter::Initialize(), G4DNAChemistryManager::InitializeThreadSharedData(), G4DNAChemistryManager::Run(), G4MolecularConfiguration::ScaleAllDiffusionCoefficientsOnWater(), G4DNAMolecularMaterial::SetMolecularConfiguration(), G4DNAMolecularReactionData::SetReactant1(), G4DNAMolecularReactionData::SetReactant2(), G4DNAMolecularReactionData::SetReactants(), and G4MolecularConfiguration::Unserialize().
void G4MoleculeTable::PrepareMolecularConfiguration ()
Definition at line 160 of file G4MoleculeTable.cc.
View newest version in sPHENIX GitHub at line 160 of file G4MoleculeTable.cc
References fMoleculeDefTable, G4MolecularConfiguration::GetOrCreateMolecularConfiguration(), and it.
Referenced by G4DNAChemistryManager::InitializeThreadSharedData().
Member Data Documentation
MoleculeDefTable G4MoleculeTable::fMoleculeDefTable protected
Definition at line 133 of file G4MoleculeTable.hh.
View newest version in sPHENIX GitHub at line 133 of file G4MoleculeTable.hh
Referenced by GetDefintionIterator(), GetMoleculeDefinition(), Insert(), and PrepareMolecularConfiguration().
G4MoleculeTable * G4MoleculeTable::fpgMoleculeTable static protected
Definition at line 130 of file G4MoleculeTable.hh.
View newest version in sPHENIX GitHub at line 130 of file G4MoleculeTable.hh
Referenced by Instance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/include/G4MoleculeTable.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/molecules/management/src/G4MoleculeTable.cc