ECCE @ EIC Software: G4MoleculeGun Class Reference
G4MoleculeGun Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4MoleculeGun.hh>
Public Types
typedef std::map< G4String, int > NameNumber
Public Member Functions
G4MoleculeGun ()
virtual ~G4MoleculeGun ()
virtual void DefineTracks ()
void AddMolecule (const G4String &moleculeName, const G4ThreeVector &position, double time=0)
void AddNMolecules (size_t n, const G4String &moleculeName, const G4ThreeVector &position, double time=0)
void AddMoleculesRandomPositionInBox (size_t n, const G4String &moleculeName, const G4ThreeVector &boxCenter, const G4ThreeVector &boxExtension, double time=0)
void AddMoleculeInCMRepresentation (size_t n, const G4String &moleculeName, double time=0)
const std::vector
< G4shared_ptr
< G4MoleculeShoot > > & GetMoleculeShoot ()
void GetNameAndNumber (NameNumber &)
void AddMoleculeShoot (G4shared_ptr< G4MoleculeShoot >)
Public Member Functions inherited from G4ITGun
G4ITGun ()
virtual ~G4ITGun ()
Protected Member Functions
void BuildAndPushTrack (const G4String &name, const G4ThreeVector &position, double time=0)
Protected Member Functions inherited from G4ITGun
void PushTrack (G4Track *)
Protected Attributes
G4MoleculeGunMessenger * fpMessenger
std::vector< G4shared_ptr
< G4MoleculeShoot > > fShoots
Friends
class G4MoleculeShoot
template<class T >
class TG4MoleculeShoot
Detailed Description
Definition at line 126 of file G4MoleculeGun.hh.
View newest version in sPHENIX GitHub at line 126 of file G4MoleculeGun.hh
Member Typedef Documentation
typedef std::map<G4String, int> G4MoleculeGun::NameNumber
Definition at line 193 of file G4MoleculeGun.hh.
View newest version in sPHENIX GitHub at line 193 of file G4MoleculeGun.hh
Constructor & Destructor Documentation
G4MoleculeGun::G4MoleculeGun ()
Definition at line 93 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 93 of file G4MoleculeGun.cc
References fpMessenger.
G4MoleculeGun::~G4MoleculeGun () virtual
Definition at line 100 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 100 of file G4MoleculeGun.cc
References fpMessenger.
Member Function Documentation
void G4MoleculeGun::AddMolecule (const G4String & moleculeName, const G4ThreeVector & position, double time = 0)
Definition at line 117 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 117 of file G4MoleculeGun.cc
References fShoots, position, G4INCL::DeJongSpin::shoot(), and Acts::VectorHelpers::time().
void G4MoleculeGun::AddMoleculeInCMRepresentation (size_t n, const G4String & moleculeName, double time = 0)
Definition at line 221 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 221 of file G4MoleculeGun.cc
References fShoots, n, G4INCL::DeJongSpin::shoot(), and Acts::VectorHelpers::time().
void G4MoleculeGun::AddMoleculeShoot (G4shared_ptr< G4MoleculeShoot > shoot)
Definition at line 216 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 216 of file G4MoleculeGun.cc
References fShoots.
Referenced by G4MoleculeGunMessenger::CreateNewType().
void G4MoleculeGun::AddMoleculesRandomPositionInBox (size_t n, const G4String & moleculeName, const G4ThreeVector & boxCenter, const G4ThreeVector & boxExtension, double time = 0)
Definition at line 146 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 146 of file G4MoleculeGun.cc
References fShoots, n, G4INCL::DeJongSpin::shoot(), and Acts::VectorHelpers::time().
void G4MoleculeGun::AddNMolecules (size_t n, const G4String & moleculeName, const G4ThreeVector & position, double time = 0)
Definition at line 130 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 130 of file G4MoleculeGun.cc
References fShoots, n, position, G4INCL::DeJongSpin::shoot(), and Acts::VectorHelpers::time().
void G4MoleculeGun::BuildAndPushTrack (const G4String & name, const G4ThreeVector & position, double time = 0) protected
Definition at line 163 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 163 of file G4MoleculeGun.cc
References G4Molecule::BuildTrack(), G4MoleculeTable::GetConfiguration(), G4MoleculeTable::Instance(), molecule(), and G4ITGun::PushTrack().
Referenced by TG4MoleculeShoot< TYPE >::ShootAtFixedPosition(), and TG4MoleculeShoot< TYPE >::ShootAtRandomPosition().
void G4MoleculeGun::DefineTracks () virtual
Reimplemented from G4ITGun.
Definition at line 107 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 107 of file G4MoleculeGun.cc
References fShoots.
const std::vector<G4shared_ptr<G4MoleculeShoot> >& G4MoleculeGun::GetMoleculeShoot () inline
Definition at line 189 of file G4MoleculeGun.hh.
View newest version in sPHENIX GitHub at line 189 of file G4MoleculeGun.hh
References fShoots.
void G4MoleculeGun::GetNameAndNumber (G4MoleculeGun::NameNumber & output)
Definition at line 177 of file G4MoleculeGun.cc.
View newest version in sPHENIX GitHub at line 177 of file G4MoleculeGun.cc
References fShoots.
Friends And Related Function Documentation
friend class G4MoleculeShoot friend
Definition at line 206 of file G4MoleculeGun.hh.
View newest version in sPHENIX GitHub at line 206 of file G4MoleculeGun.hh
template<class T > friend class TG4MoleculeShoot friend
Definition at line 207 of file G4MoleculeGun.hh.
View newest version in sPHENIX GitHub at line 207 of file G4MoleculeGun.hh
Member Data Documentation
G4MoleculeGunMessenger* G4MoleculeGun::fpMessenger protected
Definition at line 203 of file G4MoleculeGun.hh.
View newest version in sPHENIX GitHub at line 203 of file G4MoleculeGun.hh
Referenced by G4MoleculeGun(), and ~G4MoleculeGun().
std::vector<G4shared_ptr<G4MoleculeShoot> > G4MoleculeGun::fShoots protected
Definition at line 205 of file G4MoleculeGun.hh.
View newest version in sPHENIX GitHub at line 205 of file G4MoleculeGun.hh
Referenced by AddMolecule(), AddMoleculeInCMRepresentation(), AddMoleculeShoot(), AddMoleculesRandomPositionInBox(), AddNMolecules(), DefineTracks(), GetMoleculeShoot(), and GetNameAndNumber().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4MoleculeGun.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4MoleculeGun.cc