ECCE @ EIC Software: G4HETCChargedFragment Class Reference
G4HETCChargedFragment Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4HETCChargedFragment.hh>
Public Member Functions
G4HETCChargedFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4HETCChargedFragment ()
virtual G4double SampleKineticEnergy (const G4Fragment &aFragment)
Public Member Functions inherited from G4HETCFragment
G4HETCFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4HETCFragment ()
G4double CalcEmissionProbability (const G4Fragment &aFragment)
Public Member Functions inherited from G4VPreCompoundFragment
G4VPreCompoundFragment (const G4ParticleDefinition *, G4VCoulombBarrier *aCoulombBarrier)
virtual ~G4VPreCompoundFragment ()
void Initialize (const G4Fragment &aFragment)
G4bool IsItPossible (const G4Fragment &aFragment) const
G4ReactionProduct * GetReactionProduct () const
G4int GetA () const
G4int GetZ () const
G4int GetRestA () const
G4int GetRestZ () const
G4double GetBindingEnergy () const
G4double GetEnergyThreshold () const
G4double GetEmissionProbability () const
G4double GetNuclearMass () const
G4double GetRestNuclearMass () const
const G4LorentzVector & GetMomentum () const
void SetMomentum (const G4LorentzVector &value)
void SetOPTxs (G4int)
void UseSICB (G4bool)
Private Member Functions
G4HETCChargedFragment ()
G4HETCChargedFragment (const G4HETCChargedFragment &right)
const G4HETCChargedFragment & operator= (const G4HETCChargedFragment &right)
G4bool operator== (const G4HETCChargedFragment &right) const
G4bool operator!= (const G4HETCChargedFragment &right) const
Additional Inherited Members
Protected Member Functions inherited from G4HETCFragment
virtual G4double K (const G4Fragment &aFragment)=0
virtual G4double GetSpinFactor () const =0
virtual G4double GetAlpha () const =0
virtual G4double GetBeta () const =0
G4double BetaRand (G4int N, G4int L) const
Protected Attributes inherited from G4VPreCompoundFragment
G4NuclearLevelData * fNucData
G4DeexPrecoParameters * theParameters
G4Pow * g4calc
G4int theA
G4int theZ
G4int theResA
G4int theResZ
G4int theFragA
G4int theFragZ
G4double theResA13
G4double theBindingEnergy
G4double theMinKinEnergy
G4double theMaxKinEnergy
G4double theResMass
G4double theReducedMass
G4double theMass
G4double theEmissionProbability
G4double theCoulombBarrier
G4int OPTxs
G4bool useSICB
Detailed Description
Definition at line 34 of file G4HETCChargedFragment.hh.
View newest version in sPHENIX GitHub at line 34 of file G4HETCChargedFragment.hh
Constructor & Destructor Documentation
G4HETCChargedFragment::G4HETCChargedFragment (const G4ParticleDefinition * pd, G4VCoulombBarrier * aCoulombBarrier)
Definition at line 39 of file G4HETCChargedFragment.cc.
View newest version in sPHENIX GitHub at line 39 of file G4HETCChargedFragment.cc
G4HETCChargedFragment::~G4HETCChargedFragment () virtual
Definition at line 44 of file G4HETCChargedFragment.cc.
View newest version in sPHENIX GitHub at line 44 of file G4HETCChargedFragment.cc
G4HETCChargedFragment::G4HETCChargedFragment () private
G4HETCChargedFragment::G4HETCChargedFragment (const G4HETCChargedFragment & right) private
Member Function Documentation
G4bool G4HETCChargedFragment::operator!= (const G4HETCChargedFragment & right) const private
const G4HETCChargedFragment& G4HETCChargedFragment::operator= (const G4HETCChargedFragment & right) private
G4bool G4HETCChargedFragment::operator== (const G4HETCChargedFragment & right) const private
G4double G4HETCChargedFragment::SampleKineticEnergy (const G4Fragment & aFragment) virtual
Implements G4VPreCompoundFragment.
Definition at line 48 of file G4HETCChargedFragment.cc.
View newest version in sPHENIX GitHub at line 48 of file G4HETCChargedFragment.cc
References G4HETCFragment::BetaRand(), Emax, G4VPreCompoundFragment::fNucData, G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), H, max, pi2, G4VPreCompoundFragment::theCoulombBarrier, G4VPreCompoundFragment::theFragA, G4VPreCompoundFragment::theFragZ, G4VPreCompoundFragment::theMaxKinEnergy, and x.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4HETCChargedFragment.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4HETCChargedFragment.cc