ECCE @ EIC Software: G4RDGenerator2BN Class Reference
G4RDGenerator2BN Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDGenerator2BN.hh>
Public Member Functions
G4RDGenerator2BN (const G4String &name)
~G4RDGenerator2BN ()
G4double PolarAngle (const G4double initial_energy, const G4double final_energy, const G4int Z)
void PrintGeneratorInformation () const
void SetInterpolationThetaIncrement (G4double increment)
G4double GetInterpolationThetaIncrement ()
void SetGammaCutValue (G4double cutValue)
G4double GetGammaCutValue ()
void ConstructMajorantSurface ()
Public Member Functions inherited from G4RDVBremAngularDistribution
G4RDVBremAngularDistribution (const G4String &name)
virtual ~G4RDVBremAngularDistribution ()
Protected Member Functions
G4double CalculateFkt (G4double k, G4double theta, G4double A, G4double c) const
G4double Calculatedsdkdt (G4double kout, G4double theta, G4double Eel) const
G4double Generate2BN (G4double Ek, G4double k) const
Private Member Functions
G4RDGenerator2BN & operator= (const G4RDGenerator2BN &right)
G4RDGenerator2BN (const G4RDGenerator2BN &)
Private Attributes
G4double b
G4int index_min
G4int index_max
G4double kmin
G4double Ekmin
G4double dtheta
G4double kcut
Static Private Attributes
static G4double Atab [320]
static G4double ctab [320]
Detailed Description
Definition at line 60 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 60 of file G4RDGenerator2BN.hh
Constructor & Destructor Documentation
G4RDGenerator2BN::G4RDGenerator2BN (const G4String & name)
Definition at line 154 of file G4RDGenerator2BN.cc.
View newest version in sPHENIX GitHub at line 154 of file G4RDGenerator2BN.cc
References b, dtheta, Ekmin, eV, index_max, index_min, kcut, kmin, and rad.
G4RDGenerator2BN::~G4RDGenerator2BN ()
Definition at line 175 of file G4RDGenerator2BN.cc.
View newest version in sPHENIX GitHub at line 175 of file G4RDGenerator2BN.cc
G4RDGenerator2BN::G4RDGenerator2BN (const G4RDGenerator2BN &) private
Member Function Documentation
G4double G4RDGenerator2BN::Calculatedsdkdt (G4double kout, G4double theta, G4double Eel) const protected
Definition at line 202 of file G4RDGenerator2BN.cc.
View newest version in sPHENIX GitHub at line 202 of file G4RDGenerator2BN.cc
References E, source.hepunit::electron_mass_c2, epsilon(), k, k2, L, MeV, pi, Q, Z, and Z2.
Referenced by ConstructMajorantSurface(), and Generate2BN().
G4double G4RDGenerator2BN::CalculateFkt (G4double k, G4double theta, G4double A, G4double c) const protected
Definition at line 195 of file G4RDGenerator2BN.cc.
View newest version in sPHENIX GitHub at line 195 of file G4RDGenerator2BN.cc
References b, and theta().
Referenced by ConstructMajorantSurface().
void G4RDGenerator2BN::ConstructMajorantSurface ()
Definition at line 268 of file G4RDGenerator2BN.cc.
View newest version in sPHENIX GitHub at line 268 of file G4RDGenerator2BN.cc
References A(), Atab, b, c, Calculatedsdkdt(), CalculateFkt(), ctab, dtheta, source.hepunit::electron_mass_c2, G4cout, G4endl, index_max, index_min, k, G4InuclParticleNames::k0, kcut, kmin, pi, ratio, theta(), and v.
G4double G4RDGenerator2BN::Generate2BN (G4double Ek, G4double k) const protected
Definition at line 360 of file G4RDGenerator2BN.cc.
View newest version in sPHENIX GitHub at line 360 of file G4RDGenerator2BN.cc
References A(), Atab, b, c, Calculatedsdkdt(), ctab, source.hepunit::electron_mass_c2, G4cout, G4endl, G4UniformRand, index_max, index_min, pi2, t, Acts::UnitConstants::u, and y.
Referenced by PolarAngle().
G4double G4RDGenerator2BN::GetGammaCutValue () inline
Definition at line 81 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 81 of file G4RDGenerator2BN.hh
References kcut.
G4double G4RDGenerator2BN::GetInterpolationThetaIncrement () inline
Definition at line 78 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 78 of file G4RDGenerator2BN.hh
References dtheta.
G4RDGenerator2BN& G4RDGenerator2BN::operator= (const G4RDGenerator2BN & right) private
G4double G4RDGenerator2BN::PolarAngle (const G4double initial_energy, const G4double final_energy, const G4int Z) virtual
Implements G4RDVBremAngularDistribution.
Definition at line 180 of file G4RDGenerator2BN.cc.
View newest version in sPHENIX GitHub at line 180 of file G4RDGenerator2BN.cc
References Generate2BN(), k, and theta().
void G4RDGenerator2BN::PrintGeneratorInformation () const virtual
Implements G4RDVBremAngularDistribution.
Definition at line 417 of file G4RDGenerator2BN.cc.
View newest version in sPHENIX GitHub at line 417 of file G4RDGenerator2BN.cc
References G4cout, and G4endl.
void G4RDGenerator2BN::SetGammaCutValue (G4double cutValue) inline
Definition at line 80 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 80 of file G4RDGenerator2BN.hh
References kcut.
void G4RDGenerator2BN::SetInterpolationThetaIncrement (G4double increment) inline
Definition at line 77 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 77 of file G4RDGenerator2BN.hh
References dtheta.
Member Data Documentation
G4double G4RDGenerator2BN::Atab static private
Definition at line 99 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 99 of file G4RDGenerator2BN.hh
Referenced by ConstructMajorantSurface(), and Generate2BN().
G4double G4RDGenerator2BN::b private
Definition at line 94 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 94 of file G4RDGenerator2BN.hh
Referenced by CalculateFkt(), ConstructMajorantSurface(), G4RDGenerator2BN(), and Generate2BN().
G4double G4RDGenerator2BN::ctab static private
Definition at line 100 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 100 of file G4RDGenerator2BN.hh
Referenced by ConstructMajorantSurface(), and Generate2BN().
G4double G4RDGenerator2BN::dtheta private
Definition at line 97 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 97 of file G4RDGenerator2BN.hh
Referenced by ConstructMajorantSurface(), G4RDGenerator2BN(), GetInterpolationThetaIncrement(), and SetInterpolationThetaIncrement().
G4double G4RDGenerator2BN::Ekmin private
Definition at line 96 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 96 of file G4RDGenerator2BN.hh
Referenced by G4RDGenerator2BN().
G4int G4RDGenerator2BN::index_max private
Definition at line 95 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RDGenerator2BN.hh
Referenced by ConstructMajorantSurface(), G4RDGenerator2BN(), and Generate2BN().
G4int G4RDGenerator2BN::index_min private
Definition at line 95 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 95 of file G4RDGenerator2BN.hh
Referenced by ConstructMajorantSurface(), G4RDGenerator2BN(), and Generate2BN().
G4double G4RDGenerator2BN::kcut private
Definition at line 98 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 98 of file G4RDGenerator2BN.hh
Referenced by ConstructMajorantSurface(), G4RDGenerator2BN(), GetGammaCutValue(), and SetGammaCutValue().
G4double G4RDGenerator2BN::kmin private
Definition at line 96 of file G4RDGenerator2BN.hh.
View newest version in sPHENIX GitHub at line 96 of file G4RDGenerator2BN.hh
Referenced by ConstructMajorantSurface(), and G4RDGenerator2BN().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDGenerator2BN.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDGenerator2BN.cc