ECCE @ EIC Software: G4ModifiedTsai Class Reference
G4ModifiedTsai Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4ModifiedTsai.hh>
Public Member Functions
G4ModifiedTsai (const G4String &name="")
virtual ~G4ModifiedTsai ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double out_energy, G4int Z, const G4Material *mat=nullptr) final
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr) final
virtual void PrintGeneratorInformation () const final
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material *)
const G4String & GetName () const
Private Member Functions
G4double SampleCosTheta (G4double kinEnergy)
G4ModifiedTsai & operator= (const G4ModifiedTsai &right)=delete
G4ModifiedTsai (const G4ModifiedTsai &)=delete
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 62 of file G4ModifiedTsai.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ModifiedTsai.hh
Constructor & Destructor Documentation
G4ModifiedTsai::G4ModifiedTsai (const G4String & name = "") explicit
Definition at line 65 of file G4ModifiedTsai.cc.
View newest version in sPHENIX GitHub at line 65 of file G4ModifiedTsai.cc
G4ModifiedTsai::~G4ModifiedTsai () virtual
Definition at line 71 of file G4ModifiedTsai.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ModifiedTsai.cc
G4ModifiedTsai::G4ModifiedTsai (const G4ModifiedTsai &) private delete
Member Function Documentation
G4ModifiedTsai& G4ModifiedTsai::operator= (const G4ModifiedTsai & right) private delete
void G4ModifiedTsai::PrintGeneratorInformation () const final virtual
Definition at line 144 of file G4ModifiedTsai.cc.
View newest version in sPHENIX GitHub at line 144 of file G4ModifiedTsai.cc
References G4cout, and G4endl.
G4double G4ModifiedTsai::SampleCosTheta (G4double kinEnergy) private
Definition at line 93 of file G4ModifiedTsai.cc.
View newest version in sPHENIX GitHub at line 93 of file G4ModifiedTsai.cc
References border, CLHEP::electron_mass_c2, CLHEP::HepRandomEngine::flat(), G4Log(), and Acts::UnitConstants::u.
Referenced by SampleDirection(), and SamplePairDirections().
G4ThreeVector & G4ModifiedTsai::SampleDirection (const G4DynamicParticle * dp, G4double out_energy, G4int Z, const G4Material * mat = nullptr) final virtual
Implements G4VEmAngularDistribution.
Definition at line 77 of file G4ModifiedTsai.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ModifiedTsai.cc
References G4VEmAngularDistribution::fLocalDirection, G4UniformRand, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), phi, CLHEP::Hep3Vector::rotateUz(), SampleCosTheta(), CLHEP::Hep3Vector::set(), and CLHEP::twopi.
void G4ModifiedTsai::SamplePairDirections (const G4DynamicParticle * dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector & dirElectron, G4ThreeVector & dirPositron, G4int Z = 0, const G4Material * mat = nullptr) final virtual
Reimplemented from G4VEmAngularDistribution.
Definition at line 118 of file G4ModifiedTsai.cc.
View newest version in sPHENIX GitHub at line 118 of file G4ModifiedTsai.cc
References G4UniformRand, G4DynamicParticle::GetMomentumDirection(), phi, CLHEP::Hep3Vector::rotateUz(), SampleCosTheta(), CLHEP::Hep3Vector::set(), and CLHEP::twopi.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4ModifiedTsai.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4ModifiedTsai.cc