ECCE @ EIC Software: G4BOptnForceFreeFlight Class Reference
G4BOptnForceFreeFlight Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnForceFreeFlight.hh>
Public Member Functions
G4BOptnForceFreeFlight (G4String name)
virtual ~G4BOptnForceFreeFlight ()
virtual const
G4VBiasingInteractionLaw * ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface *, G4ForceCondition &)
virtual void AlongMoveBy (const G4BiasingProcessInterface *, const G4Step *, G4double)
virtual G4VParticleChange * ApplyFinalStateBiasing (const G4BiasingProcessInterface *, const G4Track *, const G4Step *, G4bool &)
virtual G4double DistanceToApplyOperation (const G4Track *, G4double, G4ForceCondition *)
virtual G4VParticleChange * GenerateBiasingFinalState (const G4Track *, const G4Step *)
G4ILawForceFreeFlight * GetForceFreeFlightLaw ()
void ResetInitialTrackWeight (G4double w)
G4bool OperationComplete () const
Public Member Functions inherited from G4VBiasingOperation
G4VBiasingOperation (G4String name)
virtual ~G4VBiasingOperation ()
virtual G4double ProposeAlongStepLimit (const G4BiasingProcessInterface *)
virtual G4GPILSelection ProposeGPILSelection (const G4GPILSelection wrappedProcessSelection)
const G4String & GetName () const
std::size_t GetUniqueID () const
Private Attributes
G4ILawForceFreeFlight * fForceFreeFlightInteractionLaw
G4double fCumulatedWeightChange
G4double fInitialTrackWeight
G4ParticleChange fParticleChange
G4bool fOperationComplete
Detailed Description
Definition at line 55 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 55 of file G4BOptnForceFreeFlight.hh
Constructor & Destructor Documentation
G4BOptnForceFreeFlight::G4BOptnForceFreeFlight (G4String name)
Definition at line 33 of file G4BOptnForceFreeFlight.cc.
View newest version in sPHENIX GitHub at line 33 of file G4BOptnForceFreeFlight.cc
References fForceFreeFlightInteractionLaw.
G4BOptnForceFreeFlight::~G4BOptnForceFreeFlight () virtual
Definition at line 42 of file G4BOptnForceFreeFlight.cc.
View newest version in sPHENIX GitHub at line 42 of file G4BOptnForceFreeFlight.cc
References fForceFreeFlightInteractionLaw.
Member Function Documentation
void G4BOptnForceFreeFlight::AlongMoveBy (const G4BiasingProcessInterface * , const G4Step * , G4double weightChange) virtual
Reimplemented from G4VBiasingOperation.
Definition at line 101 of file G4BOptnForceFreeFlight.cc.
View newest version in sPHENIX GitHub at line 101 of file G4BOptnForceFreeFlight.cc
References fCumulatedWeightChange.
G4VParticleChange * G4BOptnForceFreeFlight::ApplyFinalStateBiasing (const G4BiasingProcessInterface * callingProcess, const G4Track * track, const G4Step * step, G4bool & forceFinalState) virtual
Implements G4VBiasingOperation.
Definition at line 55 of file G4BOptnForceFreeFlight.cc.
View newest version in sPHENIX GitHub at line 55 of file G4BOptnForceFreeFlight.cc
References DBL_MIN, fCumulatedWeightChange, fGeomBoundary, fInitialTrackWeight, fOperationComplete, fParticleChange, G4endl, G4Exception(), G4BiasingProcessInterface::GetIsFirstPostStepDoItInterface(), G4Step::GetPostStepPoint(), G4StepPoint::GetStepStatus(), G4Track::GetWeight(), G4ParticleChange::Initialize(), JustWarning, and G4VParticleChange::ProposeWeight().
virtual G4double G4BOptnForceFreeFlight::DistanceToApplyOperation (const G4Track * , G4double , G4ForceCondition *) inline virtual
Implements G4VBiasingOperation.
Definition at line 71 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 71 of file G4BOptnForceFreeFlight.hh
References DBL_MAX.
virtual G4VParticleChange* G4BOptnForceFreeFlight::GenerateBiasingFinalState (const G4Track * , const G4Step *) inline virtual
Implements G4VBiasingOperation.
Definition at line 74 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 74 of file G4BOptnForceFreeFlight.hh
G4ILawForceFreeFlight* G4BOptnForceFreeFlight::GetForceFreeFlightLaw () inline
Definition at line 82 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 82 of file G4BOptnForceFreeFlight.hh
References fForceFreeFlightInteractionLaw.
G4bool G4BOptnForceFreeFlight::OperationComplete () const inline
Definition at line 87 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 87 of file G4BOptnForceFreeFlight.hh
References fOperationComplete.
const G4VBiasingInteractionLaw * G4BOptnForceFreeFlight::ProvideOccurenceBiasingInteractionLaw (const G4BiasingProcessInterface * , G4ForceCondition & proposeForceCondition) virtual
Implements G4VBiasingOperation.
Definition at line 47 of file G4BOptnForceFreeFlight.cc.
View newest version in sPHENIX GitHub at line 47 of file G4BOptnForceFreeFlight.cc
References fForceFreeFlightInteractionLaw, fOperationComplete, and Forced.
void G4BOptnForceFreeFlight::ResetInitialTrackWeight (G4double w) inline
Definition at line 86 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 86 of file G4BOptnForceFreeFlight.hh
References fCumulatedWeightChange, fInitialTrackWeight, and w.
Referenced by G4BOptrForceCollision::ProposeOccurenceBiasingOperation().
Member Data Documentation
G4double G4BOptnForceFreeFlight::fCumulatedWeightChange private
Definition at line 91 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BOptnForceFreeFlight.hh
Referenced by AlongMoveBy(), ApplyFinalStateBiasing(), and ResetInitialTrackWeight().
G4ILawForceFreeFlight* G4BOptnForceFreeFlight::fForceFreeFlightInteractionLaw private
Definition at line 90 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 90 of file G4BOptnForceFreeFlight.hh
Referenced by G4BOptnForceFreeFlight(), GetForceFreeFlightLaw(), ProvideOccurenceBiasingInteractionLaw(), and ~G4BOptnForceFreeFlight().
G4double G4BOptnForceFreeFlight::fInitialTrackWeight private
Definition at line 91 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BOptnForceFreeFlight.hh
Referenced by ApplyFinalStateBiasing(), and ResetInitialTrackWeight().
G4bool G4BOptnForceFreeFlight::fOperationComplete private
Definition at line 94 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 94 of file G4BOptnForceFreeFlight.hh
Referenced by ApplyFinalStateBiasing(), OperationComplete(), and ProvideOccurenceBiasingInteractionLaw().
G4ParticleChange G4BOptnForceFreeFlight::fParticleChange private
Definition at line 93 of file G4BOptnForceFreeFlight.hh.
View newest version in sPHENIX GitHub at line 93 of file G4BOptnForceFreeFlight.hh
Referenced by ApplyFinalStateBiasing().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4BOptnForceFreeFlight.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4BOptnForceFreeFlight.cc