ECCE @ EIC Software: G4VUPLSplitter< T > Class Template Reference
G4VUPLSplitter< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4VUPLSplitter.hh>
Public Member Functions
G4VUPLSplitter ()
G4int CreateSubInstance ()
void NewSubInstances ()
void FreeWorker ()
T * GetOffset ()
void UseWorkArea (T *newOffset)
T * FreeWorkArea ()
void WorkerCopySubInstanceArray ()
Public Attributes
G4RUN_DLL G4ThreadLocalStatic G4int workertotalspace =0
G4RUN_DLL G4ThreadLocalStatic T * offset =0
Private Attributes
G4int totalobj
G4int totalspace
T * sharedOffset
G4Mutex mutex
Detailed Description
template<class T>
class G4VUPLSplitter< T >
Definition at line 71 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VUPLSplitter.hh
Constructor & Destructor Documentation
template<class T > G4VUPLSplitter< T >::G4VUPLSplitter () inline
Definition at line 75 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VUPLSplitter.hh
References G4MUTEXINIT.
Member Function Documentation
template<class T > G4int G4VUPLSplitter< T >::CreateSubInstance () inline
Definition at line 80 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VUPLSplitter.hh
References G4TemplateAutoLock< _Mutex_t >::lock(), G4VUPLSplitter< T >::NewSubInstances(), G4VUPLSplitter< T >::offset, G4VUPLSplitter< T >::sharedOffset, G4VUPLSplitter< T >::totalobj, G4VUPLSplitter< T >::totalspace, G4TemplateAutoLock< _Mutex_t >::unlock(), and G4VUPLSplitter< T >::workertotalspace.
Referenced by G4VModularPhysicsList::G4VModularPhysicsList(), G4VPhysicsConstructor::G4VPhysicsConstructor(), G4VUserPhysicsList::G4VUserPhysicsList(), and G4VModularPhysicsList::operator=().
template<class T > T* G4VUPLSplitter< T >::FreeWorkArea () inline
Definition at line 153 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 153 of file G4VUPLSplitter.hh
References G4VUPLSplitter< T >::offset, and T.
template<class T > void G4VUPLSplitter< T >::FreeWorker () inline
Definition at line 129 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 129 of file G4VUPLSplitter.hh
References G4VUPLSplitter< T >::offset.
Referenced by G4PhysicsListWorkspace::DestroyWorkspace().
template<class T > T* G4VUPLSplitter< T >::GetOffset () inline
Definition at line 137 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 137 of file G4VUPLSplitter.hh
References G4VUPLSplitter< T >::offset.
Referenced by G4PhysicsListWorkspace::G4PhysicsListWorkspace().
template<class T > void G4VUPLSplitter< T >::NewSubInstances () inline
Definition at line 103 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 103 of file G4VUPLSplitter.hh
References FatalException, G4Exception(), G4VUPLSplitter< T >::offset, T, G4VUPLSplitter< T >::totalobj, and G4VUPLSplitter< T >::workertotalspace.
Referenced by G4VUPLSplitter< T >::CreateSubInstance(), and G4PhysicsListWorkspace::InitialiseWorkspace().
template<class T > void G4VUPLSplitter< T >::UseWorkArea (T * newOffset) inline
Definition at line 139 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 139 of file G4VUPLSplitter.hh
References FatalException, G4Exception(), and G4VUPLSplitter< T >::offset.
Referenced by G4PhysicsListWorkspace::ReleaseWorkspace(), and G4PhysicsListWorkspace::UseWorkspace().
template<class T > void G4VUPLSplitter< T >::WorkerCopySubInstanceArray () inline
Definition at line 165 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 165 of file G4VUPLSplitter.hh
References FatalException, G4Exception(), G4VUPLSplitter< T >::offset, G4VUPLSplitter< T >::sharedOffset, T, and G4VUPLSplitter< T >::totalspace.
Referenced by G4PhysicsListWorkspace::InitialiseWorkspace().
Member Data Documentation
template<class T > G4Mutex G4VUPLSplitter< T >::mutex private
Definition at line 193 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 193 of file G4VUPLSplitter.hh
template<class T > G4ThreadLocal T * G4VUPLSplitter< T >::offset =0
Definition at line 187 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 187 of file G4VUPLSplitter.hh
Referenced by G4VPhysicsConstructor::AddBuilder(), G4VUPLSplitter< T >::CreateSubInstance(), G4VUPLSplitter< T >::FreeWorkArea(), G4VUPLSplitter< T >::FreeWorker(), G4VUserPhysicsList::G4VUserPhysicsList(), G4VPhysicsConstructor::GetBuilders(), G4VUPLSplitter< T >::GetOffset(), G4VPhysicsConstructor::GetParticleIterator(), G4VUserPhysicsList::GetParticleIterator(), G4VUPLSplitter< T >::NewSubInstances(), G4VModularPhysicsList::operator=(), G4VUserPhysicsList::operator=(), G4VPhysicsConstructor::TerminateWorker(), G4VUPLSplitter< T >::UseWorkArea(), and G4VUPLSplitter< T >::WorkerCopySubInstanceArray().
template<class T > T* G4VUPLSplitter< T >::sharedOffset private
Definition at line 192 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 192 of file G4VUPLSplitter.hh
Referenced by G4VUPLSplitter< T >::CreateSubInstance(), and G4VUPLSplitter< T >::WorkerCopySubInstanceArray().
template<class T > G4int G4VUPLSplitter< T >::totalobj private
Definition at line 190 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 190 of file G4VUPLSplitter.hh
Referenced by G4VUPLSplitter< T >::CreateSubInstance(), and G4VUPLSplitter< T >::NewSubInstances().
template<class T > G4int G4VUPLSplitter< T >::totalspace private
Definition at line 191 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 191 of file G4VUPLSplitter.hh
Referenced by G4VUPLSplitter< T >::CreateSubInstance(), and G4VUPLSplitter< T >::WorkerCopySubInstanceArray().
template<class T > G4ThreadLocal G4int G4VUPLSplitter< T >::workertotalspace =0
Definition at line 186 of file G4VUPLSplitter.hh.
View newest version in sPHENIX GitHub at line 186 of file G4VUPLSplitter.hh
Referenced by G4VUPLSplitter< T >::CreateSubInstance(), and G4VUPLSplitter< T >::NewSubInstances().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/run/include/G4VUPLSplitter.hh