ECCE @ EIC Software: G4RDFluoData Class Reference
G4RDFluoData Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDFluoData.hh>
Public Member Functions
G4RDFluoData ()
~G4RDFluoData ()
size_t NumberOfVacancies () const
G4int VacancyId (G4int vacancyIndex) const
size_t NumberOfTransitions (G4int vacancyIndex) const
G4int StartShellId (G4int initIndex, G4int vacancyIndex) const
G4double StartShellEnergy (G4int initIndex, G4int vacancyIndex) const
G4double StartShellProb (G4int initIndex, G4int vacancyIndex) const
void LoadData (G4int Z)
void PrintData ()
Private Member Functions
G4RDFluoData & operator= (const G4RDFluoData &right)
G4RDFluoData (const G4RDFluoData &)
Private Attributes
std::map< G4int, G4DataVector
*, std::less< G4int > > idMap
std::map< G4int, G4DataVector
*, std::less< G4int > > energyMap
std::map< G4int, G4DataVector
*, std::less< G4int > > probabilityMap
std::vector< G4int > nInitShells
G4int numberOfVacancies
std::map< G4int, std::vector
< G4RDFluoTransition * >
, std::less< G4int > > fluoTransitionTable
Detailed Description
Definition at line 52 of file G4RDFluoData.hh.
View newest version in sPHENIX GitHub at line 52 of file G4RDFluoData.hh
Constructor & Destructor Documentation
G4RDFluoData::G4RDFluoData ()
Definition at line 44 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 44 of file G4RDFluoData.cc
References numberOfVacancies.
G4RDFluoData::~G4RDFluoData ()
Definition at line 49 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 49 of file G4RDFluoData.cc
References energyMap, idMap, pos(), and probabilityMap.
G4RDFluoData::G4RDFluoData (const G4RDFluoData &) private
Member Function Documentation
void G4RDFluoData::LoadData (G4int Z)
Definition at line 186 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 186 of file G4RDFluoData.cc
References a, e, energyMap, FatalException, file, G4Exception(), idMap, k, MeV, n, nInitShells, numberOfVacancies, and probabilityMap.
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager().
size_t G4RDFluoData::NumberOfTransitions (G4int vacancyIndex) const
Definition at line 94 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 94 of file G4RDFluoData.cc
References FatalException, G4Exception(), n, nInitShells, and numberOfVacancies.
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager(), and PrintData().
size_t G4RDFluoData::NumberOfVacancies () const
Definition at line 70 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 70 of file G4RDFluoData.cc
References numberOfVacancies.
G4RDFluoData& G4RDFluoData::operator= (const G4RDFluoData & right) private
void G4RDFluoData::PrintData (void)
Definition at line 308 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 308 of file G4RDFluoData.cc
References e, G4cout, G4endl, k, MeV, NumberOfTransitions(), numberOfVacancies, StartShellEnergy(), StartShellId(), and StartShellProb().
G4double G4RDFluoData::StartShellEnergy (G4int initIndex, G4int vacancyIndex) const
Definition at line 136 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 136 of file G4RDFluoData.cc
References energyMap, FatalException, G4Exception(), n, numberOfVacancies, and pos().
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager(), and PrintData().
G4int G4RDFluoData::StartShellId (G4int initIndex, G4int vacancyIndex) const
Definition at line 109 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 109 of file G4RDFluoData.cc
References FatalException, G4Exception(), idMap, n, numberOfVacancies, and pos().
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager(), and PrintData().
G4double G4RDFluoData::StartShellProb (G4int initIndex, G4int vacancyIndex) const
Definition at line 161 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 161 of file G4RDFluoData.cc
References FatalException, G4Exception(), n, numberOfVacancies, pos(), and probabilityMap.
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager(), and PrintData().
G4int G4RDFluoData::VacancyId (G4int vacancyIndex) const
Definition at line 75 of file G4RDFluoData.cc.
View newest version in sPHENIX GitHub at line 75 of file G4RDFluoData.cc
References FatalException, G4Exception(), idMap, n, numberOfVacancies, and pos().
Referenced by G4RDAtomicTransitionManager::G4RDAtomicTransitionManager().
Member Data Documentation
std::map<G4int,G4DataVector*,std::less<G4int> > G4RDFluoData::energyMap private
Definition at line 99 of file G4RDFluoData.hh.
View newest version in sPHENIX GitHub at line 99 of file G4RDFluoData.hh
Referenced by LoadData(), StartShellEnergy(), and ~G4RDFluoData().
std::map<G4int,std::vector<G4RDFluoTransition*>,std::less<G4int> > G4RDFluoData::fluoTransitionTable private
Definition at line 103 of file G4RDFluoData.hh.
View newest version in sPHENIX GitHub at line 103 of file G4RDFluoData.hh
std::map<G4int,G4DataVector*,std::less<G4int> > G4RDFluoData::idMap private
Definition at line 98 of file G4RDFluoData.hh.
View newest version in sPHENIX GitHub at line 98 of file G4RDFluoData.hh
Referenced by LoadData(), StartShellId(), VacancyId(), and ~G4RDFluoData().
std::vector<G4int> G4RDFluoData::nInitShells private
Definition at line 101 of file G4RDFluoData.hh.
View newest version in sPHENIX GitHub at line 101 of file G4RDFluoData.hh
Referenced by LoadData(), and NumberOfTransitions().
G4int G4RDFluoData::numberOfVacancies private
Definition at line 102 of file G4RDFluoData.hh.
View newest version in sPHENIX GitHub at line 102 of file G4RDFluoData.hh
Referenced by G4RDFluoData(), LoadData(), NumberOfTransitions(), NumberOfVacancies(), PrintData(), StartShellEnergy(), StartShellId(), StartShellProb(), and VacancyId().
std::map<G4int,G4DataVector*,std::less<G4int> > G4RDFluoData::probabilityMap private
Definition at line 100 of file G4RDFluoData.hh.
View newest version in sPHENIX GitHub at line 100 of file G4RDFluoData.hh
Referenced by LoadData(), StartShellProb(), and ~G4RDFluoData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDFluoData.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDFluoData.cc