ECCE @ EIC Software: G4TextPPReporter Class Reference
G4TextPPReporter Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/utils/include/G4TextPPReporter.hh>
Public Member Functions
G4TextPPReporter ()
virtual ~G4TextPPReporter ()
virtual void Print (const G4String &option="")
Public Member Functions inherited from G4VParticlePropertyReporter
G4VParticlePropertyReporter ()
virtual ~G4VParticlePropertyReporter ()
G4bool operator== (const G4VParticlePropertyReporter &right) const
G4bool operator!= (const G4VParticlePropertyReporter &right) const
virtual G4bool FillList (G4String name)
virtual void Clear ()
const G4PPDContainer & GetList () const
Protected Member Functions
void SparseOption (const G4String &option)
void GeneratePropertyTable (const G4ParticleDefinition *)
Protected Attributes
G4String baseDir
Protected Attributes inherited from G4VParticlePropertyReporter
G4PPDContainer pList
G4ParticlePropertyTable * pPropertyTable
Additional Inherited Members
Public Types inherited from G4VParticlePropertyReporter
typedef std::vector
< G4ParticlePropertyData * > G4PPDContainer
Detailed Description
Definition at line 43 of file G4TextPPReporter.hh.
View newest version in sPHENIX GitHub at line 43 of file G4TextPPReporter.hh
Constructor & Destructor Documentation
G4TextPPReporter::G4TextPPReporter ()
Definition at line 48 of file G4TextPPReporter.cc.
View newest version in sPHENIX GitHub at line 48 of file G4TextPPReporter.cc
G4TextPPReporter::~G4TextPPReporter () virtual
Definition at line 53 of file G4TextPPReporter.cc.
View newest version in sPHENIX GitHub at line 53 of file G4TextPPReporter.cc
Member Function Documentation
void G4TextPPReporter::GeneratePropertyTable (const G4ParticleDefinition * particle) protected
Definition at line 85 of file G4TextPPReporter.cc.
View newest version in sPHENIX GitHub at line 85 of file G4TextPPReporter.cc
References baseDir, G4DecayTable::entries(), eplus, G4endl, G4VDecayChannel::GetBR(), G4VDecayChannel::GetDaughter(), G4DecayTable::GetDecayChannel(), G4ParticleDefinition::GetDecayTable(), G4VDecayChannel::GetKinematicsName(), G4VDecayChannel::GetNumberOfDaughters(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGiConjugation(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiParity(), G4ParticleDefinition::GetPDGiSpin(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGWidth(), GeV, and second.
Referenced by Print().
void G4TextPPReporter::Print (const G4String & option = "") virtual
Implements G4VParticlePropertyReporter.
Definition at line 58 of file G4TextPPReporter.cc.
View newest version in sPHENIX GitHub at line 58 of file G4TextPPReporter.cc
References G4ParticleTable::FindParticle(), GeneratePropertyTable(), G4ParticleTable::GetParticleTable(), particle, G4VParticlePropertyReporter::pList, and SparseOption().
void G4TextPPReporter::SparseOption (const G4String & option) protected
Definition at line 70 of file G4TextPPReporter.cc.
View newest version in sPHENIX GitHub at line 70 of file G4TextPPReporter.cc
References baseDir, and G4String::isNull().
Referenced by Print().
Member Data Documentation
G4String G4TextPPReporter::baseDir protected
Definition at line 60 of file G4TextPPReporter.hh.
View newest version in sPHENIX GitHub at line 60 of file G4TextPPReporter.hh
Referenced by GeneratePropertyTable(), and SparseOption().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/utils/include/G4TextPPReporter.hh
geant4/tree/geant4-10.6-release/source/particles/utils/src/G4TextPPReporter.cc