ECCE @ EIC Software: G4VTrajectoryPoint Class Reference
G4VTrajectoryPoint Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/tracking/include/G4VTrajectoryPoint.hh>
Public Member Functions
G4VTrajectoryPoint ()
virtual ~G4VTrajectoryPoint ()
G4bool operator== (const G4VTrajectoryPoint &right) const
virtual const G4ThreeVector GetPosition () const =0
virtual const std::vector
< G4ThreeVector > * GetAuxiliaryPoints () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Detailed Description
Definition at line 50 of file G4VTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 50 of file G4VTrajectoryPoint.hh
Constructor & Destructor Documentation
G4VTrajectoryPoint::G4VTrajectoryPoint ()
Definition at line 36 of file G4VTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VTrajectoryPoint.cc
G4VTrajectoryPoint::~G4VTrajectoryPoint () virtual
Definition at line 37 of file G4VTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VTrajectoryPoint.cc
Member Function Documentation
virtual std::vector<G4AttValue>* G4VTrajectoryPoint::CreateAttValues () const inline virtual
Reimplemented in G4RichTrajectoryPoint, RE04TrajectoryPoint, G4TrajectoryPoint, G4SmoothTrajectoryPoint, WLSTrajectoryPoint, and F04TrajectoryPoint.
Definition at line 81 of file G4VTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VTrajectoryPoint.hh
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoryDrawByEncounteredVolume::Draw(), G4TrajectoryEncounteredVolumeFilter::Evaluate(), G4TrajectoriesModelDebugG4AttValues(), G4TrajectoryDrawerUtils::GetPointsAndTimes(), G4VSceneHandler::LoadAtts(), and G4VTrajectory::ShowTrajectory().
virtual const std::map<G4String,G4AttDef>* G4VTrajectoryPoint::GetAttDefs () const inline virtual
Reimplemented in G4RichTrajectoryPoint, RE04TrajectoryPoint, G4TrajectoryPoint, G4SmoothTrajectoryPoint, WLSTrajectoryPoint, and F04TrajectoryPoint.
Definition at line 73 of file G4VTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VTrajectoryPoint.hh
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4TrajectoriesModelDebugG4AttValues(), G4VSceneHandler::LoadAtts(), and G4VTrajectory::ShowTrajectory().
virtual const std::vector<G4ThreeVector>* G4VTrajectoryPoint::GetAuxiliaryPoints () const inline virtual
Reimplemented in G4RichTrajectoryPoint, and G4SmoothTrajectoryPoint.
Definition at line 65 of file G4VTrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VTrajectoryPoint.hh
Referenced by G4HepRepFileSceneHandler::AddCompound(), LXeTrajectory::DrawTrajectory(), and G4TrajectoryDrawerUtils::GetPointsAndTimes().
virtual const G4ThreeVector G4VTrajectoryPoint::GetPosition () const pure virtual
Implemented in G4TrajectoryPoint, RE04TrajectoryPoint, G4SmoothTrajectoryPoint, and G4RayTrajectoryPoint.
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4GMocrenFileSceneHandler::AddCompound(), G4TrajectoryDrawByOriginVolume::Draw(), LXeTrajectory::DrawTrajectory(), G4TrajectoryOriginVolumeFilter::Evaluate(), and G4TrajectoryDrawerUtils::GetPointsAndTimes().
G4bool G4VTrajectoryPoint::operator== (const G4VTrajectoryPoint & right) const
Definition at line 39 of file G4VTrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VTrajectoryPoint.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/tracking/include/G4VTrajectoryPoint.hh
geant4/tree/geant4-10.6-release/source/tracking/src/G4VTrajectoryPoint.cc