ECCE @ EIC Software: G4RTSteppingAction Class Reference
G4RTSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTSteppingAction.hh>
Public Member Functions
G4RTSteppingAction ()
virtual ~G4RTSteppingAction ()
virtual void UserSteppingAction (const G4Step *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Static Public Member Functions
static void SetIgnoreTransparency (G4bool val)
static G4bool GetIgnoreTransparency ()
Static Private Attributes
static G4bool ignoreTransparency = false
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 51 of file G4RTSteppingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file G4RTSteppingAction.hh
Constructor & Destructor Documentation
G4RTSteppingAction::G4RTSteppingAction ()
Definition at line 45 of file G4RTSteppingAction.cc.
View newest version in sPHENIX GitHub at line 45 of file G4RTSteppingAction.cc
virtual G4RTSteppingAction::~G4RTSteppingAction () inline virtual
Definition at line 55 of file G4RTSteppingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file G4RTSteppingAction.hh
Member Function Documentation
G4bool G4RTSteppingAction::GetIgnoreTransparency () static
Definition at line 99 of file G4RTSteppingAction.cc.
View newest version in sPHENIX GitHub at line 99 of file G4RTSteppingAction.cc
References ignoreTransparency.
Referenced by G4RTMessenger::GetCurrentValue().
void G4RTSteppingAction::SetIgnoreTransparency (G4bool val) static
Definition at line 97 of file G4RTSteppingAction.cc.
View newest version in sPHENIX GitHub at line 97 of file G4RTSteppingAction.cc
References ignoreTransparency.
Referenced by G4RTMessenger::SetNewValue().
void G4RTSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 48 of file G4RTSteppingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file G4RTSteppingAction.cc
References fStopAndKill, G4VisAttributes::GetColour(), G4VTouchable::GetCopyNumber(), G4VisManager::GetCurrentSceneHandler(), G4VisAttributes::GetForcedDrawingStyle(), G4VTouchable::GetHistoryDepth(), G4VisManager::GetInstance(), G4StepPoint::GetPhysicalVolume(), G4RayTracerSceneHandler::GetSceneVisAttsMap(), G4StepPoint::GetTouchable(), G4VTouchable::GetVolume(), ignoreTransparency, G4VisAttributes::IsForceDrawingStyle(), G4VisAttributes::IsVisible(), and G4VisAttributes::wireframe.
Member Data Documentation
G4bool G4RTSteppingAction::ignoreTransparency = false static private
Definition at line 60 of file G4RTSteppingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file G4RTSteppingAction.hh
Referenced by GetIgnoreTransparency(), SetIgnoreTransparency(), and UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/include/G4RTSteppingAction.hh
geant4/tree/geant4-10.6-release/source/visualization/RayTracer/src/G4RTSteppingAction.cc