ECCE @ EIC Software: G4GeometryMessenger Class Reference
G4GeometryMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4GeometryMessenger.hh>
Public Member Functions
G4GeometryMessenger (G4TransportationManager *tman)
~G4GeometryMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
G4String GetCurrentValue (G4UIcommand *command)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
void Init ()
void CheckGeometry ()
void ResetNavigator ()
void SetVerbosity (G4String newValue)
void SetCheckMode (G4String newValue)
void SetPushFlag (G4String newValue)
void RecursiveOverlapTest ()
Private Attributes
G4UIdirectory * geodir
G4UIdirectory * navdir
G4UIdirectory * testdir
G4UIcmdWithABool * chkCmd
G4UIcmdWithABool * pchkCmd
G4UIcmdWithABool * verCmd
G4UIcmdWithoutParameter * recCmd
G4UIcmdWithoutParameter * resCmd
G4UIcmdWithADoubleAndUnit * tolCmd
G4UIcmdWithAnInteger * verbCmd
G4UIcmdWithAnInteger * rslCmd
G4UIcmdWithAnInteger * rcsCmd
G4UIcmdWithAnInteger * rcdCmd
G4UIcmdWithAnInteger * errCmd
G4double tol = 0.0
G4int recLevel = 0
G4int recDepth = -1
G4TransportationManager * tmanager
G4GeomTestVolume * tvolume = nullptr
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 51 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 51 of file G4GeometryMessenger.hh
Constructor & Destructor Documentation
G4GeometryMessenger::G4GeometryMessenger (G4TransportationManager * tman)
Definition at line 52 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 52 of file G4GeometryMessenger.cc
References G4UIcommand::AvailableForStates(), chkCmd, errCmd, G4State_Idle, geodir, navdir, pchkCmd, rcdCmd, rcsCmd, recCmd, resCmd, rslCmd, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIcmdWithADoubleAndUnit::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), G4UIcmdWithADoubleAndUnit::SetUnitCategory(), testdir, tolCmd, verbCmd, and verCmd.
G4GeometryMessenger::~G4GeometryMessenger ()
Definition at line 172 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 172 of file G4GeometryMessenger.cc
References chkCmd, errCmd, geodir, navdir, pchkCmd, rcdCmd, rcsCmd, recCmd, resCmd, rslCmd, testdir, tolCmd, tvolume, verbCmd, and verCmd.
Member Function Documentation
void G4GeometryMessenger::CheckGeometry () private
Definition at line 271 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 271 of file G4GeometryMessenger.cc
References G4GeometryManager::CloseGeometry(), G4GeometryManager::GetInstance(), G4GeometryManager::IsGeometryClosed(), and G4GeometryManager::OpenGeometry().
Referenced by RecursiveOverlapTest(), and ResetNavigator().
G4String G4GeometryMessenger::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 257 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 257 of file G4GeometryMessenger.cc
References G4UIcommand::ConvertToString(), tol, and tolCmd.
void G4GeometryMessenger::Init () private
Definition at line 186 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 186 of file G4GeometryMessenger.cc
References G4TransportationManager::GetNavigatorForTracking(), G4Navigator::GetWorldVolume(), tmanager, tvolume, and Acts::Test::world.
Referenced by SetNewValue().
void G4GeometryMessenger::RecursiveOverlapTest () private
Definition at line 337 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 337 of file G4GeometryMessenger.cc
References CheckGeometry(), recDepth, recLevel, G4GeomTestVolume::TestRecursiveOverlap(), and tvolume.
Referenced by SetNewValue().
void G4GeometryMessenger::ResetNavigator () private
Definition at line 287 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 287 of file G4GeometryMessenger.cc
References CheckGeometry(), G4TransportationManager::GetNavigatorForTracking(), G4Navigator::LocateGlobalPointAndSetup(), Acts::Test::navigator, pt, and tmanager.
Referenced by SetNewValue().
void G4GeometryMessenger::SetCheckMode (G4String newValue) private
Definition at line 315 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 315 of file G4GeometryMessenger.cc
References G4Navigator::CheckMode(), chkCmd, G4TransportationManager::GetNavigatorForTracking(), G4UIcmdWithABool::GetNewBoolValue(), Acts::Test::navigator, and tmanager.
Referenced by SetNewValue().
void G4GeometryMessenger::SetNewValue (G4UIcommand * command, G4String newValues) virtual
Reimplemented from G4UImessenger.
Definition at line 207 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 207 of file G4GeometryMessenger.cc
References chkCmd, errCmd, G4cout, G4endl, G4UIcmdWithABool::GetNewBoolValue(), G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), G4UIcmdWithADoubleAndUnit::GetNewUnitValue(), Init(), pchkCmd, rcdCmd, rcsCmd, recCmd, recDepth, recLevel, RecursiveOverlapTest(), resCmd, ResetNavigator(), rslCmd, SetCheckMode(), G4GeomTestVolume::SetErrorsThreshold(), SetPushFlag(), G4GeomTestVolume::SetResolution(), G4GeomTestVolume::SetTolerance(), G4GeomTestVolume::SetVerbosity(), SetVerbosity(), tol, tolCmd, tvolume, verbCmd, and verCmd.
void G4GeometryMessenger::SetPushFlag (G4String newValue) private
Definition at line 326 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 326 of file G4GeometryMessenger.cc
References G4TransportationManager::GetNavigatorForTracking(), G4UIcmdWithABool::GetNewBoolValue(), Acts::Test::navigator, pchkCmd, G4Navigator::SetPushVerbosity(), and tmanager.
Referenced by SetNewValue().
void G4GeometryMessenger::SetVerbosity (G4String newValue) private
Definition at line 304 of file G4GeometryMessenger.cc.
View newest version in sPHENIX GitHub at line 304 of file G4GeometryMessenger.cc
References G4TransportationManager::GetNavigatorForTracking(), G4UIcmdWithAnInteger::GetNewIntValue(), Acts::Test::navigator, G4Navigator::SetVerboseLevel(), tmanager, and verbCmd.
Referenced by SetNewValue().
Member Data Documentation
G4UIcmdWithABool* G4GeometryMessenger::chkCmd private
Definition at line 73 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetCheckMode(), SetNewValue(), and ~G4GeometryMessenger().
G4UIcmdWithAnInteger * G4GeometryMessenger::errCmd private
Definition at line 76 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), and ~G4GeometryMessenger().
G4UIdirectory* G4GeometryMessenger::geodir private
Definition at line 72 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), and ~G4GeometryMessenger().
G4UIdirectory * G4GeometryMessenger::navdir private
Definition at line 72 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), and ~G4GeometryMessenger().
G4UIcmdWithABool * G4GeometryMessenger::pchkCmd private
Definition at line 73 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), SetPushFlag(), and ~G4GeometryMessenger().
G4UIcmdWithAnInteger * G4GeometryMessenger::rcdCmd private
Definition at line 76 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), and ~G4GeometryMessenger().
G4UIcmdWithAnInteger * G4GeometryMessenger::rcsCmd private
Definition at line 76 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), and ~G4GeometryMessenger().
G4UIcmdWithoutParameter* G4GeometryMessenger::recCmd private
Definition at line 74 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), and ~G4GeometryMessenger().
G4int G4GeometryMessenger::recDepth = -1 private
Definition at line 79 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4GeometryMessenger.hh
Referenced by RecursiveOverlapTest(), and SetNewValue().
G4int G4GeometryMessenger::recLevel = 0 private
Definition at line 79 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4GeometryMessenger.hh
Referenced by RecursiveOverlapTest(), and SetNewValue().
G4UIcmdWithoutParameter * G4GeometryMessenger::resCmd private
Definition at line 74 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), and ~G4GeometryMessenger().
G4UIcmdWithAnInteger * G4GeometryMessenger::rslCmd private
Definition at line 76 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), and ~G4GeometryMessenger().
G4UIdirectory * G4GeometryMessenger::testdir private
Definition at line 72 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), and ~G4GeometryMessenger().
G4TransportationManager* G4GeometryMessenger::tmanager private
Definition at line 81 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4GeometryMessenger.hh
Referenced by Init(), ResetNavigator(), SetCheckMode(), SetPushFlag(), and SetVerbosity().
G4double G4GeometryMessenger::tol = 0.0 private
Definition at line 78 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4GeometryMessenger.hh
Referenced by GetCurrentValue(), and SetNewValue().
G4UIcmdWithADoubleAndUnit* G4GeometryMessenger::tolCmd private
Definition at line 75 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), GetCurrentValue(), SetNewValue(), and ~G4GeometryMessenger().
G4GeomTestVolume* G4GeometryMessenger::tvolume = nullptr private
Definition at line 82 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4GeometryMessenger.hh
Referenced by Init(), RecursiveOverlapTest(), SetNewValue(), and ~G4GeometryMessenger().
G4UIcmdWithAnInteger* G4GeometryMessenger::verbCmd private
Definition at line 76 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), SetVerbosity(), and ~G4GeometryMessenger().
G4UIcmdWithABool * G4GeometryMessenger::verCmd private
Definition at line 73 of file G4GeometryMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file G4GeometryMessenger.hh
Referenced by G4GeometryMessenger(), SetNewValue(), and ~G4GeometryMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4GeometryMessenger.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4GeometryMessenger.cc