ECCE @ EIC Software: G4ParticleHPFissionData Class Reference
G4ParticleHPFissionData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFissionData.hh>
Public Member Functions
G4ParticleHPFissionData ()
~G4ParticleHPFissionData ()
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int, G4int, const G4Element *, const G4Material *)
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int, G4int, const G4Isotope *, const G4Element *, const G4Material *)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, G4double aT)
void BuildPhysicsTable (const G4ParticleDefinition &)
void DumpPhysicsTable (const G4ParticleDefinition &)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int)
virtual void CrossSectionDescription (std::ostream &) const
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Attributes
G4PhysicsTable * theCrossSections
G4bool onFlightDB
G4bool instanceOfWorker
G4double ke_cache
G4double xs_cache
const G4Element * element_cache
const G4Material * material_cache
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 48 of file G4ParticleHPFissionData.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPFissionData.hh
Constructor & Destructor Documentation
G4ParticleHPFissionData::G4ParticleHPFissionData ()
Definition at line 47 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPFissionData.cc
References element_cache, instanceOfWorker, G4Threading::IsWorkerThread(), ke_cache, material_cache, MeV, onFlightDB, G4VCrossSectionDataSet::SetMaxKinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), theCrossSections, and xs_cache.
G4ParticleHPFissionData::~G4ParticleHPFissionData ()
Definition at line 66 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ParticleHPFissionData.cc
References G4PhysicsTable::clearAndDestroy(), instanceOfWorker, and theCrossSections.
Member Function Documentation
void G4ParticleHPFissionData::BuildPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 114 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleHPFissionData.cc
References G4PhysicsTable::clearAndDestroy(), G4cout, G4endl, G4ThreadLocal, G4Element::GetElementTable(), G4ParticleHPManager::GetFissionCrossSections(), G4ParticleHPManager::GetInstance(), G4Element::GetNumberOfElements(), G4ParticleHPData::Instance(), G4Threading::IsWorkerThread(), G4ParticleHPData::MakePhysicsVector(), G4Neutron::Neutron(), onFlightDB, G4PhysicsTable::push_back(), G4ParticleHPManager::RegisterFissionCrossSections(), and theCrossSections.
void G4ParticleHPFissionData::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 288 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 288 of file G4ParticleHPFissionData.cc
void G4ParticleHPFissionData::DumpPhysicsTable (const G4ParticleDefinition & aP) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 153 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 153 of file G4ParticleHPFissionData.cc
References barn, eV, G4cout, G4endl, G4ThreadLocal, G4Element::GetElementTable(), G4Pow::GetInstance(), G4Element::GetNumberOfElements(), MeV, G4Neutron::Neutron(), G4Pow::powA(), and theCrossSections.
G4double G4ParticleHPFissionData::GetCrossSection (const G4DynamicParticle * aP, const G4Element * anE, G4double aT)
Definition at line 212 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 212 of file G4ParticleHPFissionData.cc
References kdfinder::abs(), eps, G4DynamicParticle::GetDefinition(), G4Element::GetIndex(), G4ReactionProduct::GetKineticEnergy(), G4DynamicParticle::GetKineticEnergy(), G4ReactionProduct::GetMass(), G4ReactionProduct::GetMomentum(), G4DynamicParticle::GetMomentum(), G4Element::GetN(), G4NucleiProperties::GetNuclearMass(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetThermalNucleus(), G4Element::GetZ(), source.hepunit::k_Boltzmann, kelvin, G4ReactionProduct::Lorentz(), CLHEP::Hep3Vector::mag(), max, G4Neutron::Neutron(), onFlightDB, G4ReactionProduct::SetMomentum(), and theCrossSections.
Referenced by GetIsoCrossSection().
G4double G4ParticleHPFissionData::GetIsoCrossSection (const G4DynamicParticle * dp, G4int , G4int , const G4Isotope * , const G4Element * element, const G4Material * material) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 88 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleHPFissionData.cc
References element_cache, GetCrossSection(), G4DynamicParticle::GetKineticEnergy(), ke_cache, material(), material_cache, and xs_cache.
G4int G4ParticleHPFissionData::GetVerboseLevel () const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 280 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 280 of file G4ParticleHPFissionData.cc
References G4ParticleHPManager::GetInstance(), and G4ParticleHPManager::GetVerboseLevel().
G4bool G4ParticleHPFissionData::IsIsoApplicable (const G4DynamicParticle * dp, G4int , G4int , const G4Element * , const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 75 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 75 of file G4ParticleHPFissionData.cc
References G4DynamicParticle::GetDefinition(), G4DynamicParticle::GetKineticEnergy(), G4VCrossSectionDataSet::GetMaxKinEnergy(), G4VCrossSectionDataSet::GetMinKinEnergy(), and G4Neutron::Neutron().
void G4ParticleHPFissionData::SetVerboseLevel (G4int newValue) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 284 of file G4ParticleHPFissionData.cc.
View newest version in sPHENIX GitHub at line 284 of file G4ParticleHPFissionData.cc
References G4ParticleHPManager::GetInstance(), and G4ParticleHPManager::SetVerboseLevel().
Member Data Documentation
const G4Element* G4ParticleHPFissionData::element_cache private
Definition at line 93 of file G4ParticleHPFissionData.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPFissionData.hh
Referenced by G4ParticleHPFissionData(), and GetIsoCrossSection().
G4bool G4ParticleHPFissionData::instanceOfWorker private
Definition at line 89 of file G4ParticleHPFissionData.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPFissionData.hh
Referenced by G4ParticleHPFissionData(), and ~G4ParticleHPFissionData().
G4double G4ParticleHPFissionData::ke_cache private
Definition at line 91 of file G4ParticleHPFissionData.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPFissionData.hh
Referenced by G4ParticleHPFissionData(), and GetIsoCrossSection().
const G4Material* G4ParticleHPFissionData::material_cache private
Definition at line 94 of file G4ParticleHPFissionData.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPFissionData.hh
Referenced by G4ParticleHPFissionData(), and GetIsoCrossSection().
G4bool G4ParticleHPFissionData::onFlightDB private
Definition at line 88 of file G4ParticleHPFissionData.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleHPFissionData.hh
Referenced by BuildPhysicsTable(), G4ParticleHPFissionData(), and GetCrossSection().
G4PhysicsTable* G4ParticleHPFissionData::theCrossSections private
Definition at line 86 of file G4ParticleHPFissionData.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPFissionData.hh
Referenced by BuildPhysicsTable(), DumpPhysicsTable(), G4ParticleHPFissionData(), GetCrossSection(), and ~G4ParticleHPFissionData().
G4double G4ParticleHPFissionData::xs_cache private
Definition at line 92 of file G4ParticleHPFissionData.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPFissionData.hh
Referenced by G4ParticleHPFissionData(), and GetIsoCrossSection().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPFissionData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPFissionData.cc