ECCE @ EIC Software: G4ParticleHPEnergyDistribution Class Reference
G4ParticleHPEnergyDistribution Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPEnergyDistribution.hh>
Public Member Functions
G4ParticleHPEnergyDistribution ()
~G4ParticleHPEnergyDistribution ()
void Init (std::istream &theData)
G4double Sample (G4double anEnergy, G4int &it)
Private Attributes
G4int theNumberOfPartials
G4int theRepresentationType
G4VParticleHPEDis ** theEnergyDistribution
Detailed Description
Definition at line 47 of file G4ParticleHPEnergyDistribution.hh.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPEnergyDistribution.hh
Constructor & Destructor Documentation
G4ParticleHPEnergyDistribution::G4ParticleHPEnergyDistribution () inline
Definition at line 50 of file G4ParticleHPEnergyDistribution.hh.
View newest version in sPHENIX GitHub at line 50 of file G4ParticleHPEnergyDistribution.hh
References theEnergyDistribution, theNumberOfPartials, and theRepresentationType.
G4ParticleHPEnergyDistribution::~G4ParticleHPEnergyDistribution () inline
Definition at line 56 of file G4ParticleHPEnergyDistribution.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPEnergyDistribution.hh
References theEnergyDistribution, and theNumberOfPartials.
Member Function Documentation
void G4ParticleHPEnergyDistribution::Init (std::istream & theData) inline
Definition at line 68 of file G4ParticleHPEnergyDistribution.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPEnergyDistribution.hh
References G4VParticleHPEDis::Init(), theEnergyDistribution, theNumberOfPartials, and theRepresentationType.
Referenced by G4ParticleHPFSFissionFS::Init(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), and G4FissionLibrary::Init().
G4double G4ParticleHPEnergyDistribution::Sample (G4double anEnergy, G4int & it) inline
Definition at line 101 of file G4ParticleHPEnergyDistribution.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPEnergyDistribution.hh
References G4UniformRand, G4VParticleHPEDis::GetFractionalProbability(), it, G4VParticleHPEDis::Sample(), sum, theEnergyDistribution, and theNumberOfPartials.
Referenced by G4ParticleHPFSFissionFS::ApplyYourself(), G4ParticleHPFissionBaseFS::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), and G4ParticleHPInelasticCompFS::CompositeApply().
Member Data Documentation
G4VParticleHPEDis** G4ParticleHPEnergyDistribution::theEnergyDistribution private
Definition at line 134 of file G4ParticleHPEnergyDistribution.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ParticleHPEnergyDistribution.hh
Referenced by G4ParticleHPEnergyDistribution(), Init(), Sample(), and ~G4ParticleHPEnergyDistribution().
G4int G4ParticleHPEnergyDistribution::theNumberOfPartials private
Definition at line 132 of file G4ParticleHPEnergyDistribution.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ParticleHPEnergyDistribution.hh
Referenced by G4ParticleHPEnergyDistribution(), Init(), Sample(), and ~G4ParticleHPEnergyDistribution().
G4int G4ParticleHPEnergyDistribution::theRepresentationType private
Definition at line 133 of file G4ParticleHPEnergyDistribution.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ParticleHPEnergyDistribution.hh
Referenced by G4ParticleHPEnergyDistribution(), and Init().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPEnergyDistribution.hh