ECCE @ EIC Software: G4VScoreWriter Class Reference
G4VScoreWriter Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4VScoreWriter.hh>
Public Member Functions
G4VScoreWriter ()
virtual ~G4VScoreWriter ()
virtual void DumpQuantityToFile (const G4String &psName, const G4String &fileName, const G4String &option)
virtual void DumpAllQuantitiesToFile (const G4String &fileName, const G4String &option)
void SetScoringMesh (G4VScoringMesh *sm)
void SetVerboseLevel (G4int vl)
void SetFactor (G4double val=1.0)
G4double GetFactor () const
Protected Member Functions
G4int GetIndex (G4int x, G4int y, G4int z) const
Protected Attributes
G4int fNMeshSegments [3]
G4VScoringMesh * fScoringMesh
G4int verboseLevel
G4double fact
Detailed Description
Definition at line 40 of file G4VScoreWriter.hh.
View newest version in sPHENIX GitHub at line 40 of file G4VScoreWriter.hh
Constructor & Destructor Documentation
G4VScoreWriter::G4VScoreWriter ()
Definition at line 39 of file G4VScoreWriter.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VScoreWriter.cc
References fNMeshSegments.
G4VScoreWriter::~G4VScoreWriter () virtual
Definition at line 45 of file G4VScoreWriter.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VScoreWriter.cc
Member Function Documentation
void G4VScoreWriter::DumpAllQuantitiesToFile (const G4String & fileName, const G4String & option) virtual
Definition at line 153 of file G4VScoreWriter.cc.
View newest version in sPHENIX GitHub at line 153 of file G4VScoreWriter.cc
References fact, G4String::first(), fNMeshSegments, fScoringMesh, G4cerr, G4endl, G4VScoringMesh::GetDivisionAxisNames(), GetIndex(), G4VScoringMesh::GetPSUnit(), G4VScoringMesh::GetPSUnitValue(), G4VScoringMesh::GetScoreMap(), G4VScoringMesh::GetWorldName(), incremental_prev_tag::idx, int(), ofile, Acts::Test::transform, x, y, and z.
Referenced by G4ScoringManager::DumpAllQuantitiesToFile().
void G4VScoreWriter::DumpQuantityToFile (const G4String & psName, const G4String & fileName, const G4String & option) virtual
Reimplemented in BrachyUserScoreWriter, and RE03UserScoreWriter.
Definition at line 53 of file G4VScoreWriter.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VScoreWriter.cc
References fact, fNMeshSegments, fScoringMesh, G4cerr, G4endl, G4VScoringMesh::GetDivisionAxisNames(), GetIndex(), G4VScoringMesh::GetPSUnit(), G4VScoringMesh::GetPSUnitValue(), G4VScoringMesh::GetScoreMap(), G4VScoringMesh::GetWorldName(), incremental_prev_tag::idx, int(), ofile, Acts::Test::transform, x, y, and z.
Referenced by G4ScoringManager::DumpQuantityToFile().
G4double G4VScoreWriter::GetFactor () const inline
Definition at line 60 of file G4VScoreWriter.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VScoreWriter.hh
References fact.
Referenced by G4ScoringManager::GetFactor().
G4int G4VScoreWriter::GetIndex (G4int x, G4int y, G4int z) const protected
Definition at line 251 of file G4VScoreWriter.cc.
View newest version in sPHENIX GitHub at line 251 of file G4VScoreWriter.cc
References fNMeshSegments, and z.
Referenced by DumpAllQuantitiesToFile(), DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), and RE03UserScoreWriter::DumpQuantityToFile().
void G4VScoreWriter::SetFactor (G4double val = 1.0) inline
Definition at line 59 of file G4VScoreWriter.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VScoreWriter.hh
References fact.
Referenced by G4ScoringManager::SetFactor().
void G4VScoreWriter::SetScoringMesh (G4VScoringMesh * sm)
Definition at line 48 of file G4VScoreWriter.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VScoreWriter.cc
References fNMeshSegments, fScoringMesh, G4VScoringMesh::GetNumberOfSegments(), and G4InuclParticleNames::sm.
Referenced by G4ScoringManager::DumpAllQuantitiesToFile(), and G4ScoringManager::DumpQuantityToFile().
void G4VScoreWriter::SetVerboseLevel (G4int vl) inline
Definition at line 58 of file G4VScoreWriter.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VScoreWriter.hh
References verboseLevel.
Referenced by G4ScoringManager::SetScoreWriter(), and G4ScoringManager::SetVerboseLevel().
Member Data Documentation
G4double G4VScoreWriter::fact protected
Definition at line 70 of file G4VScoreWriter.hh.
View newest version in sPHENIX GitHub at line 70 of file G4VScoreWriter.hh
Referenced by DumpAllQuantitiesToFile(), DumpQuantityToFile(), GetFactor(), and SetFactor().
G4int G4VScoreWriter::fNMeshSegments[3] protected
Definition at line 67 of file G4VScoreWriter.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VScoreWriter.hh
Referenced by DumpAllQuantitiesToFile(), DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), G4VScoreWriter(), GetIndex(), and SetScoringMesh().
G4VScoringMesh* G4VScoreWriter::fScoringMesh protected
Definition at line 68 of file G4VScoreWriter.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VScoreWriter.hh
Referenced by DumpAllQuantitiesToFile(), DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), BrachyUserScoreWriter::DumpQuantityToFile(), and SetScoringMesh().
G4int G4VScoreWriter::verboseLevel protected
Definition at line 69 of file G4VScoreWriter.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VScoreWriter.hh
Referenced by BrachyUserScoreWriter::DumpQuantityToFile(), RE03UserScoreWriter::DumpQuantityToFile(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/utils/include/G4VScoreWriter.hh
geant4/tree/geant4-10.6-release/source/digits_hits/utils/src/G4VScoreWriter.cc