ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/lPoPs.cc File Reference
lPoPs.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "PoPs.h"
#include "PoPs_mass.h"
Classes
struct ZLabels
Functions
static char const * lPoPs_ZSymbol (int Z)
int lPoPs_addParticleIfNeeded (statusMessageReporting *smr, char const *name, char const *special)
Variables
static struct ZLabels Zs []
static const int nZs = sizeof(Zs) / sizeof(Zs[0])
Function Documentation
int lPoPs_addParticleIfNeeded (statusMessageReporting * smr, char const * name, char const * special)
Definition at line 36 of file lPoPs.cc.
View newest version in sPHENIX GitHub at line 36 of file lPoPs.cc
References A(), PoP_s::index, int(), lPoPs_ZSymbol(), PoP_free(), PoP_makeAlias(), PoPs_addParticleIfNeeded(), PoPs_errorToken_badName, PoPs_particleCreateLoadInfo(), PoPs_particleIndex(), PoPs_smr_ID, smr_setReportError2, and Z.
Referenced by _MCGIDI_map_addEntry(), MCGIDI_map_findAllOfTarget(), MCGIDI_map_findTarget(), MCGIDI_map_initialize(), MCGIDI_POPs_addParticleIfNeeded(), and PoPs_particleReadDatabase().
static char const * lPoPs_ZSymbol (int Z) static
Definition at line 183 of file lPoPs.cc.
View newest version in sPHENIX GitHub at line 183 of file lPoPs.cc
References nZs, and Zs.
Referenced by lPoPs_addParticleIfNeeded().
Variable Documentation
const int nZs = sizeof(Zs) / sizeof(Zs[0]) static
Definition at line 30 of file lPoPs.cc.
View newest version in sPHENIX GitHub at line 30 of file lPoPs.cc
Referenced by lPoPs_ZSymbol().
struct ZLabels Zs[] static
Initial value:
= {  {   0,  "n" }, {   1,  "H" }, {   2, "He" }, {   3, "Li" }, {   4, "Be" }, {   5,  "B" }, {   6,  "C" }, {   7,  "N" }, {   8,  "O" },
            {   9,  "F" }, {  10, "Ne" }, {  11, "Na" }, {  12, "Mg" }, {  13, "Al" }, {  14, "Si" }, {  15,  "P" }, {  16,  "S" }, {  17, "Cl" },
            {  18, "Ar" }, {  19,  "K" }, {  20, "Ca" }, {  21, "Sc" }, {  22, "Ti" }, {  23,  "V" }, {  24, "Cr" }, {  25, "Mn" }, {  26, "Fe" },
            {  27, "Co" }, {  28, "Ni" }, {  29, "Cu" }, {  30, "Zn" }, {  31, "Ga" }, {  32, "Ge" }, {  33, "As" }, {  34, "Se" }, {  35, "Br" },
            {  36, "Kr" }, {  37, "Rb" }, {  38, "Sr" }, {  39,  "Y" }, {  40, "Zr" }, {  41, "Nb" }, {  42, "Mo" }, {  43, "Tc" }, {  44, "Ru" },
            {  45, "Rh" }, {  46, "Pd" }, {  47, "Ag" }, {  48, "Cd" }, {  49, "In" }, {  50, "Sn" }, {  51, "Sb" }, {  52, "Te" }, {  53,  "I" },
            {  54, "Xe" }, {  55, "Cs" }, {  56, "Ba" }, {  57, "La" }, {  58, "Ce" }, {  59, "Pr" }, {  60, "Nd" }, {  61, "Pm" }, {  62, "Sm" },
            {  63, "Eu" }, {  64, "Gd" }, {  65, "Tb" }, {  66, "Dy" }, {  67, "Ho" }, {  68, "Er" }, {  69, "Tm" }, {  70, "Yb" }, {  71, "Lu" },
            {  72, "Hf" }, {  73, "Ta" }, {  74,  "W" }, {  75, "Re" }, {  76, "Os" }, {  77, "Ir" }, {  78, "Pt" }, {  79, "Au" }, {  80, "Hg" },
            {  81, "Tl" }, {  82, "Pb" }, {  83, "Bi" }, {  84, "Po" }, {  85, "At" }, {  86, "Rn" }, {  87, "Fr" }, {  88, "Ra" }, {  89, "Ac" },
            {  90, "Th" }, {  91, "Pa" }, {  92,  "U" }, {  93, "Np" }, {  94, "Pu" }, {  95, "Am" }, {  96, "Cm" }, {  97, "Bk" }, {  98, "Cf" },
            {  99, "Es" }, { 100, "Fm" }, { 101, "Md" }, { 102, "No" }, { 103, "Lr" }, { 104, "Rf" }, { 105, "Db" }, { 106, "Sg" }, { 107, "Bh" },
            { 108, "Hs" }, { 109, "Mt" } }
Referenced by lPoPs_ZSymbol().