ECCE @ EIC Software: F01DetectorConstruction Class Reference
F01DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01DetectorConstruction.hh>
Public Member Functions
F01DetectorConstruction ()
virtual ~F01DetectorConstruction ()
void SetAbsorberMaterial (G4String)
void SetAbsorberThickness (G4double)
void SetAbsorberRadius (G4double)
void SetAbsorberZpos (G4double)
void SetWorldMaterial (G4String)
void SetWorldSizeZ (G4double)
void SetWorldSizeR (G4double)
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
void PrintCalorParameters ()
G4Material * GetWorldMaterial ()
G4double GetWorldSizeZ ()
G4double GetWorldSizeR ()
G4double GetAbsorberZpos ()
G4double GetZStartAbs ()
G4double GetZEndAbs ()
G4Material * GetAbsorberMaterial ()
G4double GetAbsorberThickness ()
G4double GetAbsorberRadius ()
const G4VPhysicalVolume * GetPhysiWorld ()
const G4VPhysicalVolume * GetAbsorber ()
G4LogicalVolume * GetLogicalAbsorber ()
void SetUseFSALstepper (G4bool val)
G4bool AreUsingFSALstepper ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
void ComputeCalorParameters ()
G4VPhysicalVolume * ConstructCalorimeter ()
Private Attributes
F01DetectorMessenger * fDetectorMessenger
G4Cache< F01CalorimeterSD * > fCalorimeterSD
G4Cache< F01FieldSetup * > fEmFieldSetup
G4Tubs * fSolidWorld
G4LogicalVolume * fLogicWorld
G4VPhysicalVolume * fPhysiWorld
G4Tubs * fSolidAbsorber
G4LogicalVolume * fLogicAbsorber
G4VPhysicalVolume * fPhysiAbsorber
G4Material * fAbsorberMaterial
G4double fAbsorberThickness
G4double fAbsorberRadius
G4double fZAbsorber
G4double fZStartAbs
G4double fZEndAbs
G4Material * fWorldMaterial
G4double fWorldSizeR
G4double fWorldSizeZ
G4bool fUseFSALstepper = false
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 55 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file F01DetectorConstruction.hh
Constructor & Destructor Documentation
F01DetectorConstruction::F01DetectorConstruction ()
Definition at line 59 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 59 of file F01DetectorConstruction.cc
References DefineMaterials(), fAbsorberRadius, fAbsorberThickness, fDetectorMessenger, fWorldSizeR, fWorldSizeZ, fZAbsorber, and mm.
F01DetectorConstruction::~F01DetectorConstruction () virtual
Definition at line 90 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 90 of file F01DetectorConstruction.cc
References fDetectorMessenger.
Member Function Documentation
G4bool F01DetectorConstruction::AreUsingFSALstepper () inline
Definition at line 98 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 98 of file F01DetectorConstruction.hh
References fUseFSALstepper.
void F01DetectorConstruction::ComputeCalorParameters () inline private
Definition at line 136 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 136 of file F01DetectorConstruction.hh
References fAbsorberThickness, fZAbsorber, fZEndAbs, and fZStartAbs.
Referenced by ConstructCalorimeter(), SetAbsorberRadius(), SetAbsorberThickness(), SetAbsorberZpos(), SetWorldSizeR(), and SetWorldSizeZ().
G4VPhysicalVolume * F01DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 97 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 97 of file F01DetectorConstruction.cc
References ConstructCalorimeter().
G4VPhysicalVolume * F01DetectorConstruction::ConstructCalorimeter () private
Definition at line 222 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 222 of file F01DetectorConstruction.cc
References G4PhysicalVolumeStore::Clean(), G4LogicalVolumeStore::Clean(), G4SolidStore::Clean(), ComputeCalorParameters(), fAbsorberMaterial, fAbsorberRadius, fAbsorberThickness, fLogicAbsorber, fLogicWorld, fPhysiAbsorber, fPhysiWorld, fSolidAbsorber, fSolidWorld, fWorldMaterial, fWorldSizeR, fWorldSizeZ, fZAbsorber, G4PhysicalVolumeStore::GetInstance(), G4LogicalVolumeStore::GetInstance(), G4SolidStore::GetInstance(), G4GeometryManager::GetInstance(), mm, G4GeometryManager::OpenGeometry(), PrintCalorParameters(), and twopi.
Referenced by Construct().
void F01DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 383 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 383 of file F01DetectorConstruction.cc
References G4SDManager::AddNewDetector(), fCalorimeterSD, fEmFieldSetup, fLogicAbsorber, fUseFSALstepper, G4Cache< VALTYPE >::Get(), G4SDManager::GetSDMpointer(), G4Cache< VALTYPE >::Put(), G4AutoDelete::Register(), G4VUserDetectorConstruction::SetSensitiveDetector(), and tesla.
void F01DetectorConstruction::DefineMaterials () private
Definition at line 104 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 104 of file F01DetectorConstruction.cc
References a, G4Material::AddElement(), G4Material::AddMaterial(), cm3, fAbsorberMaterial, fWorldMaterial, Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetMaterialTable(), kStateGas, mg, mole, source.hepunit::STP_Pressure, source.hepunit::STP_Temperature, and z.
Referenced by F01DetectorConstruction().
const G4VPhysicalVolume* F01DetectorConstruction::GetAbsorber () inline
Definition at line 94 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file F01DetectorConstruction.hh
References fPhysiAbsorber.
Referenced by F01CalorimeterSD::ProcessHits().
G4Material* F01DetectorConstruction::GetAbsorberMaterial () inline
Definition at line 89 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 89 of file F01DetectorConstruction.hh
References fAbsorberMaterial.
G4double F01DetectorConstruction::GetAbsorberRadius () inline
Definition at line 91 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file F01DetectorConstruction.hh
References fAbsorberRadius.
Referenced by F01PrimaryGeneratorAction::GeneratePrimaries().
G4double F01DetectorConstruction::GetAbsorberThickness () inline
Definition at line 90 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 90 of file F01DetectorConstruction.hh
References fAbsorberThickness.
Referenced by F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), and F01PrimaryGeneratorAction::GeneratePrimaries().
G4double F01DetectorConstruction::GetAbsorberZpos () inline
Definition at line 85 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file F01DetectorConstruction.hh
References fZAbsorber.
Referenced by F01PrimaryGeneratorAction::F01PrimaryGeneratorAction(), and F01PrimaryGeneratorAction::GeneratePrimaries().
G4LogicalVolume* F01DetectorConstruction::GetLogicalAbsorber () inline
Definition at line 95 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 95 of file F01DetectorConstruction.hh
References fLogicAbsorber.
const G4VPhysicalVolume* F01DetectorConstruction::GetPhysiWorld () inline
Definition at line 93 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 93 of file F01DetectorConstruction.hh
References fPhysiWorld.
G4Material* F01DetectorConstruction::GetWorldMaterial () inline
Definition at line 81 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 81 of file F01DetectorConstruction.hh
References fWorldMaterial.
G4double F01DetectorConstruction::GetWorldSizeR () inline
Definition at line 83 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 83 of file F01DetectorConstruction.hh
References fWorldSizeR.
G4double F01DetectorConstruction::GetWorldSizeZ () inline
Definition at line 82 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file F01DetectorConstruction.hh
References fWorldSizeZ.
G4double F01DetectorConstruction::GetZEndAbs () inline
Definition at line 87 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file F01DetectorConstruction.hh
References fZEndAbs.
G4double F01DetectorConstruction::GetZStartAbs () inline
Definition at line 86 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 86 of file F01DetectorConstruction.hh
References fZStartAbs.
void F01DetectorConstruction::PrintCalorParameters ()
Definition at line 279 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 279 of file F01DetectorConstruction.cc
References fAbsorberMaterial, fAbsorberRadius, fAbsorberThickness, fWorldMaterial, fWorldSizeR, fWorldSizeZ, fZAbsorber, G4cout, G4endl, G4Material::GetName(), and mm.
Referenced by ConstructCalorimeter().
void F01DetectorConstruction::SetAbsorberMaterial (G4String materialChoice)
Definition at line 296 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 296 of file F01DetectorConstruction.cc
References fAbsorberMaterial, fLogicAbsorber, G4Material::GetMaterialTable(), G4Material::GetName(), G4RunManager::GetRunManager(), material(), G4RunManager::PhysicsHasBeenModified(), and G4LogicalVolume::SetMaterial().
Referenced by F01DetectorMessenger::SetNewValue().
void F01DetectorConstruction::SetAbsorberRadius (G4double val)
Definition at line 346 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 346 of file F01DetectorConstruction.cc
References ComputeCalorParameters(), fAbsorberRadius, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F01DetectorMessenger::SetNewValue().
void F01DetectorConstruction::SetAbsorberThickness (G4double val)
Definition at line 336 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 336 of file F01DetectorConstruction.cc
References ComputeCalorParameters(), fAbsorberThickness, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F01DetectorMessenger::SetNewValue().
void F01DetectorConstruction::SetAbsorberZpos (G4double val)
Definition at line 374 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 374 of file F01DetectorConstruction.cc
References ComputeCalorParameters(), fZAbsorber, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F01DetectorMessenger::SetNewValue().
void F01DetectorConstruction::SetUseFSALstepper (G4bool val) inline
Definition at line 97 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 97 of file F01DetectorConstruction.hh
References fUseFSALstepper.
void F01DetectorConstruction::SetWorldMaterial (G4String materialChoice)
Definition at line 316 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 316 of file F01DetectorConstruction.cc
References fLogicWorld, fWorldMaterial, G4Material::GetMaterialTable(), G4Material::GetName(), G4RunManager::GetRunManager(), material(), G4RunManager::PhysicsHasBeenModified(), and G4LogicalVolume::SetMaterial().
Referenced by F01DetectorMessenger::SetNewValue().
void F01DetectorConstruction::SetWorldSizeR (G4double val)
Definition at line 365 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 365 of file F01DetectorConstruction.cc
References ComputeCalorParameters(), fWorldSizeR, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F01DetectorMessenger::SetNewValue().
void F01DetectorConstruction::SetWorldSizeZ (G4double val)
Definition at line 356 of file F01DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 356 of file F01DetectorConstruction.cc
References ComputeCalorParameters(), fWorldSizeZ, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F01DetectorMessenger::SetNewValue().
Member Data Documentation
G4Material* F01DetectorConstruction::fAbsorberMaterial private
Definition at line 114 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 114 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), DefineMaterials(), GetAbsorberMaterial(), PrintCalorParameters(), and SetAbsorberMaterial().
G4double F01DetectorConstruction::fAbsorberRadius private
Definition at line 116 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 116 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), F01DetectorConstruction(), GetAbsorberRadius(), PrintCalorParameters(), and SetAbsorberRadius().
G4double F01DetectorConstruction::fAbsorberThickness private
Definition at line 115 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 115 of file F01DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), F01DetectorConstruction(), GetAbsorberThickness(), PrintCalorParameters(), and SetAbsorberThickness().
G4Cache<F01CalorimeterSD*> F01DetectorConstruction::fCalorimeterSD private
Definition at line 103 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 103 of file F01DetectorConstruction.hh
Referenced by ConstructSDandField().
F01DetectorMessenger* F01DetectorConstruction::fDetectorMessenger private
Definition at line 102 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 102 of file F01DetectorConstruction.hh
Referenced by F01DetectorConstruction(), and ~F01DetectorConstruction().
G4Cache<F01FieldSetup*> F01DetectorConstruction::fEmFieldSetup private
Definition at line 104 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file F01DetectorConstruction.hh
Referenced by ConstructSDandField().
G4LogicalVolume* F01DetectorConstruction::fLogicAbsorber private
Definition at line 111 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 111 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), ConstructSDandField(), GetLogicalAbsorber(), and SetAbsorberMaterial().
G4LogicalVolume* F01DetectorConstruction::fLogicWorld private
Definition at line 107 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 107 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and SetWorldMaterial().
G4VPhysicalVolume* F01DetectorConstruction::fPhysiAbsorber private
Definition at line 112 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 112 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetAbsorber().
G4VPhysicalVolume* F01DetectorConstruction::fPhysiWorld private
Definition at line 108 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 108 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetPhysiWorld().
G4Tubs* F01DetectorConstruction::fSolidAbsorber private
Definition at line 110 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 110 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Tubs* F01DetectorConstruction::fSolidWorld private
Definition at line 106 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4bool F01DetectorConstruction::fUseFSALstepper = false private
Definition at line 125 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 125 of file F01DetectorConstruction.hh
Referenced by AreUsingFSALstepper(), ConstructSDandField(), and SetUseFSALstepper().
G4Material* F01DetectorConstruction::fWorldMaterial private
Definition at line 121 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 121 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), DefineMaterials(), GetWorldMaterial(), PrintCalorParameters(), and SetWorldMaterial().
G4double F01DetectorConstruction::fWorldSizeR private
Definition at line 122 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 122 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), F01DetectorConstruction(), GetWorldSizeR(), PrintCalorParameters(), and SetWorldSizeR().
G4double F01DetectorConstruction::fWorldSizeZ private
Definition at line 123 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 123 of file F01DetectorConstruction.hh
Referenced by ConstructCalorimeter(), F01DetectorConstruction(), GetWorldSizeZ(), PrintCalorParameters(), and SetWorldSizeZ().
G4double F01DetectorConstruction::fZAbsorber private
Definition at line 118 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 118 of file F01DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), F01DetectorConstruction(), GetAbsorberZpos(), PrintCalorParameters(), and SetAbsorberZpos().
G4double F01DetectorConstruction::fZEndAbs private
Definition at line 119 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 119 of file F01DetectorConstruction.hh
Referenced by ComputeCalorParameters(), and GetZEndAbs().
G4double F01DetectorConstruction::fZStartAbs private
Definition at line 119 of file F01DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 119 of file F01DetectorConstruction.hh
Referenced by ComputeCalorParameters(), and GetZStartAbs().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field01/src/F01DetectorConstruction.cc