ECCE @ EIC Software: RE06Run Class Reference
RE06Run Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/include/RE06Run.hh>
Public Member Functions
RE06Run ()
virtual ~RE06Run ()
virtual void RecordEvent (const G4Event *)
virtual void Merge (const G4Run *)
G4double GetTotalE (G4int i) const
G4double GetNGamma (G4int i) const
G4double GetNElectron (G4int i) const
G4double GetNPositron (G4int i) const
G4double GetTotalL (G4int i) const
G4double GetNStep (G4int i) const
G4double GetEMinGamma (G4int i) const
G4double GetEMinElectron (G4int i) const
G4double GetEMinPositron (G4int i) const
G4double GetParaValue (G4int i, G4int j, G4int k) const
Public Member Functions inherited from G4Run
G4Run ()
virtual ~G4Run ()
G4int GetRunID () const
G4int GetNumberOfEvent () const
G4int GetNumberOfEventToBeProcessed () const
const G4HCtable * GetHCtable () const
const G4DCtable * GetDCtable () const
const G4String & GetRandomNumberStatus () const
void SetRunID (G4int id)
void SetNumberOfEventToBeProcessed (G4int n_ev)
void SetHCtable (G4HCtable *HCtbl)
void SetDCtable (G4DCtable *DCtbl)
void SetRandomNumberStatus (G4String &st)
void StoreEvent (G4Event *evt)
const std::vector< const
G4Event * > * GetEventVector () const
Private Member Functions
G4double GetTotal (const G4THitsMap< G4double > &map) const
G4double FindMinimum (const G4THitsMap< G4double > &map) const
Private Attributes
G4THitsMap< G4double > fMapSum [6][6]
G4int fColIDSum [6][6]
G4THitsMap< G4double > fMapMin [6][3]
G4int fColIDMin [6][3]
G4THitsMap< G4double > fMapPara [3][6]
G4int fColIDPara [3][6]
Additional Inherited Members
Protected Attributes inherited from G4Run
G4int runID
G4int numberOfEvent
G4int numberOfEventToBeProcessed
G4HCtable * HCtable
G4DCtable * DCtable
G4String randomNumberStatus
std::vector< const G4Event * > * eventVector
Detailed Description
Definition at line 41 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 41 of file RE06Run.hh
Constructor & Destructor Documentation
RE06Run::RE06Run ()
Definition at line 38 of file RE06Run.cc.
View newest version in sPHENIX GitHub at line 38 of file RE06Run.cc
References fColIDMin, fColIDPara, fColIDSum, G4SDManager::GetCollectionID(), and G4SDManager::GetSDMpointer().
RE06Run::~RE06Run () virtual
Definition at line 84 of file RE06Run.cc.
View newest version in sPHENIX GitHub at line 84 of file RE06Run.cc
Member Function Documentation
G4double RE06Run::FindMinimum (const G4THitsMap< G4double > & map) const private
Definition at line 173 of file RE06Run.cc.
View newest version in sPHENIX GitHub at line 173 of file RE06Run.cc
References DBL_MAX, G4VTHitsMap< T, Map_t >::GetMap(), and G4VTHitsMap< T, Map_t >::GetSize().
Referenced by GetEMinElectron(), GetEMinGamma(), and GetEMinPositron().
G4double RE06Run::GetEMinElectron (G4int i) const inline
Definition at line 58 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 58 of file RE06Run.hh
References FindMinimum(), and fMapMin.
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetEMinGamma (G4int i) const inline
Definition at line 57 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 57 of file RE06Run.hh
References FindMinimum(), and fMapMin.
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetEMinPositron (G4int i) const inline
Definition at line 59 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 59 of file RE06Run.hh
References FindMinimum(), and fMapMin.
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetNElectron (G4int i) const inline
Definition at line 52 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 52 of file RE06Run.hh
References fMapSum, and GetTotal().
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetNGamma (G4int i) const inline
Definition at line 51 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 51 of file RE06Run.hh
References fMapSum, and GetTotal().
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetNPositron (G4int i) const inline
Definition at line 53 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 53 of file RE06Run.hh
References fMapSum, and GetTotal().
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetNStep (G4int i) const inline
Definition at line 55 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 55 of file RE06Run.hh
References fMapSum, and GetTotal().
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetParaValue (G4int i, G4int j, G4int k) const inline
Definition at line 61 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 61 of file RE06Run.hh
References fMapPara, and k.
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetTotal (const G4THitsMap< G4double > & map) const private
Definition at line 161 of file RE06Run.cc.
View newest version in sPHENIX GitHub at line 161 of file RE06Run.cc
References G4VTHitsMap< T, Map_t >::GetMap(), and G4VTHitsMap< T, Map_t >::GetSize().
Referenced by GetNElectron(), GetNGamma(), GetNPositron(), GetNStep(), GetTotalE(), and GetTotalL().
G4double RE06Run::GetTotalE (G4int i) const inline
Definition at line 50 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 50 of file RE06Run.hh
References fMapSum, and GetTotal().
Referenced by RE06RunAction::EndOfRunAction().
G4double RE06Run::GetTotalL (G4int i) const inline
Definition at line 54 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 54 of file RE06Run.hh
References fMapSum, and GetTotal().
Referenced by RE06RunAction::EndOfRunAction().
void RE06Run::Merge (const G4Run * aRun) virtual
Reimplemented from G4Run.
Definition at line 132 of file RE06Run.cc.
View newest version in sPHENIX GitHub at line 132 of file RE06Run.cc
References fMapMin, fMapPara, fMapSum, G4VTHitsMap< T, Map_t >::GetMap(), G4Run::Merge(), and G4VTHitsMap< T, Map_t >::set().
void RE06Run::RecordEvent (const G4Event * evt) virtual
Reimplemented from G4Run.
Definition at line 89 of file RE06Run.cc.
View newest version in sPHENIX GitHub at line 89 of file RE06Run.cc
References fColIDMin, fColIDPara, fColIDSum, fMapMin, fMapPara, fMapSum, G4HCofThisEvent::GetHC(), G4Event::GetHCofThisEvent(), G4VTHitsMap< T, Map_t >::GetMap(), G4Run::numberOfEvent, and G4VTHitsMap< T, Map_t >::set().
Member Data Documentation
G4int RE06Run::fColIDMin[6][3] private
Definition at line 91 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 91 of file RE06Run.hh
Referenced by RE06Run(), and RecordEvent().
G4int RE06Run::fColIDPara[3][6] private
Definition at line 102 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 102 of file RE06Run.hh
Referenced by RE06Run(), and RecordEvent().
G4int RE06Run::fColIDSum[6][6] private
Definition at line 81 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 81 of file RE06Run.hh
Referenced by RE06Run(), and RecordEvent().
G4THitsMap<G4double> RE06Run::fMapMin[6][3] private
Definition at line 90 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 90 of file RE06Run.hh
Referenced by GetEMinElectron(), GetEMinGamma(), GetEMinPositron(), Merge(), and RecordEvent().
G4THitsMap<G4double> RE06Run::fMapPara[3][6] private
Definition at line 101 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 101 of file RE06Run.hh
Referenced by GetParaValue(), Merge(), and RecordEvent().
G4THitsMap<G4double> RE06Run::fMapSum[6][6] private
Definition at line 80 of file RE06Run.hh.
View newest version in sPHENIX GitHub at line 80 of file RE06Run.hh
Referenced by GetNElectron(), GetNGamma(), GetNPositron(), GetNStep(), GetTotalE(), GetTotalL(), Merge(), and RecordEvent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/include/RE06Run.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE06/src/RE06Run.cc