ECCE @ EIC Software: F04PhysicsList Class Reference
F04PhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04PhysicsList.hh>
Public Member Functions
F04PhysicsList (G4String)
virtual ~F04PhysicsList ()
void SetStepMax (G4double)
F04StepMax * GetStepMaxProcess ()
void AddStepMax ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
Public Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList ()
virtual ~G4VModularPhysicsList ()
void RegisterPhysics (G4VPhysicsConstructor *)
const G4VPhysicsConstructor * GetPhysics (G4int index) const
const G4VPhysicsConstructor * GetPhysics (const G4String &name) const
const G4VPhysicsConstructor * GetPhysicsWithType (G4int physics_type) const
void ReplacePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4int type)
void RemovePhysics (const G4String &name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker () override
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
virtual void SetCuts ()
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
Private Attributes
G4double fMaxChargedStep
F04PhysicsListMessenger * fMessenger
Static Private Attributes
static G4ThreadLocal F04StepMax * fStepMaxProcess = 0
Additional Inherited Members
Static Public Member Functions inherited from G4VModularPhysicsList
static const G4VMPLManager & GetSubInstanceManager ()
Protected Types inherited from G4VModularPhysicsList
typedef
G4VMPLData::G4PhysConstVectorData G4PhysConstVector
Protected Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList (const G4VModularPhysicsList &)
G4VModularPhysicsList & operator= (const G4VModularPhysicsList &)
Protected Attributes inherited from G4VModularPhysicsList
G4int verboseLevel
G4int g4vmplInstanceID
Static Protected Attributes inherited from G4VModularPhysicsList
static G4RUN_DLL G4VMPLManager G4VMPLsubInstanceManager
Detailed Description
Definition at line 42 of file F04PhysicsList.hh.
View newest version in sPHENIX GitHub at line 42 of file F04PhysicsList.hh
Constructor & Destructor Documentation
F04PhysicsList::F04PhysicsList (G4String physName)
Definition at line 72 of file F04PhysicsList.cc.
View newest version in sPHENIX GitHub at line 72 of file F04PhysicsList.cc
References DBL_MAX, G4VUserPhysicsList::defaultCutValue, FatalException, fMaxChargedStep, fMessenger, G4cout, G4endl, G4Exception(), G4VModularPhysicsList::GetPhysics(), G4VPhysicsConstructor::GetPhysicsName(), G4LossTableManager::Instance(), mm, G4VModularPhysicsList::RegisterPhysics(), and G4VModularPhysicsList::SetVerboseLevel().
F04PhysicsList::~F04PhysicsList () virtual
Definition at line 115 of file F04PhysicsList.cc.
View newest version in sPHENIX GitHub at line 115 of file F04PhysicsList.cc
References fMessenger.
Member Function Documentation
void F04PhysicsList::AddStepMax ()
Definition at line 273 of file F04PhysicsList.cc.
View newest version in sPHENIX GitHub at line 273 of file F04PhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), fStepMaxProcess, G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), F04StepMax::IsApplicable(), G4ParticleDefinition::IsShortLived(), and particle.
Referenced by ConstructProcess().
void F04PhysicsList::ConstructParticle (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 124 of file F04PhysicsList.cc.
View newest version in sPHENIX GitHub at line 124 of file F04PhysicsList.cc
References G4VModularPhysicsList::ConstructParticle(), G4GenericIon::GenericIonDefinition(), JA::Insert(), G4MuonMinus::MuonMinusDefinition(), and G4MuonPlus::MuonPlusDefinition().
void F04PhysicsList::ConstructProcess (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 147 of file F04PhysicsList.cc.
View newest version in sPHENIX GitHub at line 147 of file F04PhysicsList.cc
References G4ProcessManager::AddProcess(), G4ProcessManager::AddRestProcess(), AddStepMax(), G4VModularPhysicsList::ConstructProcess(), G4INCL::ClusterDecay::decay(), G4ProcessTable::FindProcess(), fStepMaxProcess, G4ParticleDefinition::GetProcessManager(), G4ProcessTable::GetProcessTable(), idxAtRest, idxPostStep, G4MuonMinus::MuonMinus(), G4MuonPlus::MuonPlus(), G4PionMinus::PionMinus(), G4PionPlus::PionPlus(), G4AutoDelete::Register(), G4ProcessManager::RemoveProcess(), and G4ProcessManager::SetProcessOrdering().
F04StepMax * F04PhysicsList::GetStepMaxProcess ()
Definition at line 266 of file F04PhysicsList.cc.
View newest version in sPHENIX GitHub at line 266 of file F04PhysicsList.cc
References fStepMaxProcess.
void F04PhysicsList::SetStepMax (G4double step)
Definition at line 258 of file F04PhysicsList.cc.
View newest version in sPHENIX GitHub at line 258 of file F04PhysicsList.cc
References fMaxChargedStep, fStepMaxProcess, F04StepMax::SetStepMax(), and Acts::Test::step().
Referenced by F04PhysicsListMessenger::SetNewValue().
Member Data Documentation
G4double F04PhysicsList::fMaxChargedStep private
Definition at line 64 of file F04PhysicsList.hh.
View newest version in sPHENIX GitHub at line 64 of file F04PhysicsList.hh
Referenced by F04PhysicsList(), and SetStepMax().
F04PhysicsListMessenger* F04PhysicsList::fMessenger private
Definition at line 67 of file F04PhysicsList.hh.
View newest version in sPHENIX GitHub at line 67 of file F04PhysicsList.hh
Referenced by F04PhysicsList(), and ~F04PhysicsList().
G4ThreadLocal F04StepMax * F04PhysicsList::fStepMaxProcess = 0 static private
Definition at line 65 of file F04PhysicsList.hh.
View newest version in sPHENIX GitHub at line 65 of file F04PhysicsList.hh
Referenced by AddStepMax(), ConstructProcess(), GetStepMaxProcess(), and SetStepMax().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04PhysicsList.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04PhysicsList.cc