ECCE @ EIC Software: geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/macro.C File Reference
macro.C File Reference
Functions
TFile f ("human_phantom.root")
ntuple Print ()
ntuple GetBranch ("organID") -> SetAddress(&xx)
ntuple GetBranch ("edep") -> SetAddress(&edep)
for (Int_t i=0;i< nevent;i++)
Variables
TDirectory * dir = (TDirectory*)f.Get("human_phantom_ntuple")
TTree * ntuple = (TTree*)dir->Get("1")
Int_t nevent = Int_t(ntuple->GetEntries())
Double_t xx
Double_t edep
Function Documentation
TFile f ("human_phantom.root")
for ()
Definition at line 17 of file macro.C.
View newest version in sPHENIX GitHub at line 17 of file macro.C
ntuple GetBranch ("organID") -> SetAddress(&xx)
ntuple GetBranch ("edep") -> SetAddress(&edep)
ntuple Print ()
Variable Documentation
TDirectory* dir = (TDirectory*)f.Get("human_phantom_ntuple")
Definition at line 5 of file macro.C.
View newest version in sPHENIX GitHub at line 5 of file macro.C
Referenced by accessStepWise(), CML2ExpVoxels::add(), G4ParticleHPFinalState::adjust_final_state(), XrayTelAnalysis::analyseStepping(), AnnularFieldSim::analyticFieldIntegral(), PHG4TpcDirectLaser::AppendLaserTrack(), G4ModelCmdAddIntervalContext< M >::Apply(), G4ModelCmdAddValueContext< M >::Apply(), G4LowEGammaNuclearModel::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), G4UnstableFragmentBreakUp::BreakUpChain(), G4ElectroVDNuclearModel::CalculateEMVertex(), checkForDir(), G4RadioactiveDecayBase::ChooseCollimationDirection(), G4RadioactiveDecay::ChooseCollimationDirection(), G4NeutrinoNucleusModel::ClusterDecay(), compareAssignedRealPos(), compareHitHistograms(), G4AdjointPosOnPhysVolGenerator::ComputeAreaOfExtSurface(), G4QuadrangularFacet::Distance(), G4TriangularFacet::Distance(), dokinematics(), TDirectoryHelper::duplicateDir(), GFlashShowerModel::ElectronDoIt(), FW::ParticleSmearing::execute(), AnnularFieldSim::fieldIntegral(), G4HadronicProcess::FillResult(), PHTpcTrackFollower::followTrack(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4FluoData::G4FluoData(), G4ModelCmdApplyBool< M >::G4ModelCmdApplyBool(), G4ModelCmdApplyColour< M >::G4ModelCmdApplyColour(), G4ModelCmdApplyDouble< M >::G4ModelCmdApplyDouble(), G4ModelCmdApplyDoubleAndUnit< M >::G4ModelCmdApplyDoubleAndUnit(), G4ModelCmdApplyInteger< M >::G4ModelCmdApplyInteger(), G4ModelCmdApplyNull< M >::G4ModelCmdApplyNull(), G4ModelCmdApplyString< M >::G4ModelCmdApplyString(), G4ModelCmdApplyStringColour< M >::G4ModelCmdApplyStringColour(), G4MoleculeShootMessenger::G4MoleculeShootMessenger(), G4UIbridge::G4UIbridge(), G4eeToHadronsModel::GenerateCMPhoton(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction2::GeneratePrimaries(), PrimaryGeneratorAction3::GeneratePrimaries(), PrimaryGeneratorAction4::GeneratePrimaries(), TSPrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), PHTpcTrackFollower::get_track_layer(), G4ParticleHPNames::GetName(), HepMCG4AsciiReaderMessenger::HepMCG4AsciiReaderMessenger(), AnnularFieldSim::interpolatedFieldIntegral(), G4ErrorPlaneSurfaceTarget::Intersect(), layerMaterial(), G4VUIshell::ListCommand(), G4LatticeLogical::Load_NMap(), makeinsplit(), makesplitting(), makestrings_minl(), G4NeutrinoNucleusModel::MesonDecay(), TDirectoryHelper::mkdir(), TDirectoryHelper::mkpath(), TDirectoryHelper::pathIsInDir(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4ParticleChangeForLoss::ProposeMomentumDirection(), G4ParticleChangeForGamma::ProposePolarization(), G4ParticleChangeForLoss::ProposePolarization(), prt_createDir(), prt_createSubDir(), PHParameters::ReadFromFile(), G4QuasiElRatios::RelDecayIn2(), G4MuPairProductionModel::RetrieveTables(), G4LatticePhysical::RotateToGlobal(), G4LatticePhysical::RotateToLocal(), G4WentzelVIModel::SampleScattering(), G4ee2KChargedModel::SampleSecondaries(), G4ee2KNeutralModel::SampleSecondaries(), G4eeToTwoPiModel::SampleSecondaries(), G4eeToPGammaModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4SeltzerBergerModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eBremsstrahlungRelModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4eeToHadronsModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), Run::ScoreNewTrack(), HistoManager::ScoreNewTrack(), G4VUIshell::SetCurrentDirectory(), G4GenericMessenger::SetDirectory(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), G4RunManager::SetRandomNumberStoreDir(), G4ScoringBox::SetSegmentDirection(), G4RPGInelastic::SetUpChange(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::State::State(), G4VUserPhysicsList::StorePhysicsTable(), Acts::DefaultExtension::transportMatrix(), Acts::DenseEnvironmentExtension::transportMatrix(), PHParametersContainer::WriteToFile(), PdbParameterMapContainer::WriteToFile(), and PHParameters::WriteToFile().
Double_t edep
Definition at line 13 of file macro.C.
View newest version in sPHENIX GitHub at line 13 of file macro.C
Referenced by PHG4CylinderCellv1::add_edep(), PHG4Cellv1::add_edep(), PHG4CylinderCellv1::add_shower_edep(), PHG4Cellv1::add_shower_edep(), EventAction::AddCytoEdep(), B1EventAction::AddEdep(), B1Run::AddEdep(), EventAction::AddEdep(), B1RunAction::AddEdep(), EventAction::AddEdepEvent(), EventAction::AddEdepToNucleotide(), TrkrHitv1::addEnergy(), EventAction::AddEnergy(), Run::AddEnergy(), HistoManager::AddEnergy(), EventAction::AddNuclEdep(), Run::AddPhantomStep(), G4eLowEnergyLoss::AlongStepDoIt(), G4EmCaptureCascade::ApplyYourself(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), TSDetectorConstruction::ConstructSDandField(), SensitiveDetector::EndOfEvent(), G4HumanPhantomEventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), B3aEventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), STCyclotronRun::EnergyDepositionFoil(), STCyclotronRun::EnergyDepositionTarget(), CaloRawClusterEval::get_energy_contribution(), PHG4TpcCentralMembrane::GetPHG4HitFromStripe(), PHG4Hitv1::identify(), PHG4RICHSteppingAction::MakeHit(), plot(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), PHG4Hitv1::print(), TPCIntegratedCharge::process_event(), G4CellNtuple::process_event(), TPCDataStreamEmulator::process_event(), VoxelSD::ProcessHits(), G4HumanPhantomSD::ProcessHits(), ExN04CalorimeterSD::ProcessHits(), RE05CalorimeterSD::ProcessHits(), RE05TrackerSD::ProcessHits(), ExN04MuonSD::ProcessHits(), ExN04TrackerSD::ProcessHits(), Par01CalorimeterSD::ProcessHits(), RE05MuonSD::ProcessHits(), LXeScintSD::ProcessHits(), ExTGTrackerSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), STCyclotronSensitiveTarget::ProcessHits(), B5HodoscopeSD::ProcessHits(), RE01TrackerSD::ProcessHits(), B5EmCalorimeterSD::ProcessHits(), B5HadCalorimeterSD::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), RE01CalorimeterSD::ProcessHits(), ExN02TrackerSD::ProcessHits(), G4PSDoseDeposit::ProcessHits(), SensitiveDetector::ProcessHits(), G4PSEnergyDeposit::ProcessHits(), F02CalorimeterSD::ProcessHits(), ExP01TrackerSD::ProcessHits(), FCALHadModuleSD::ProcessHits(), F01CalorimeterSD::ProcessHits(), F03CalorimeterSD::ProcessHits(), FCALEMModuleSD::ProcessHits(), FCALTestbeamSetupSD::ProcessHits(), GammaRayTelAnticoincidenceSD::ProcessHits(), GammaRayTelCalorimeterSD::ProcessHits(), GammaRayTelTrackerSD::ProcessHits(), B2TrackerSD::ProcessHits(), B4cCalorimeterSD::ProcessHits(), PhantomSD::ProcessHits(), DMXScintSD::ProcessHits(), TargetSD::ProcessHits(), TrackerSD::ProcessHits(), XrayFluoHPGeSD::ProcessHits(), RMC01SD::ProcessHits(), XrayFluoSD::ProcessHits(), ScoreSpecies::ProcessHits(), PHG4TruthEventAction::ProcessShowers(), ReadASCII(), doiPETAnalysis::ReadOut(), B3bRun::RecordEvent(), Run::RecordEvent(), PHG4Hitv1::Reset(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermorePolarizedPhotoElectricModel::SampleSecondaries(), G4LivermorePhotoElectricModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4PEEffectFluoModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), PHG4Showerv1::set_edep(), Run::SetEdepAndRMS(), LXeEventAction::SetPosMax(), G4EnergySplitter::SplitEnergyInVolumes(), EventAction::SumEnergyDeposited(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), SteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), and G4EmSaturation::VisibleEnergyDeposition().
Int_t nevent = Int_t(ntuple->GetEntries())
Definition at line 10 of file macro.C.
View newest version in sPHENIX GitHub at line 10 of file macro.C
Referenced by grun(), gustep(), G4MPImessenger::SetNewValue(), and Run::WriteActivity().
TTree* ntuple = (TTree*)dir->Get("1")
Definition at line 6 of file macro.C.
View newest version in sPHENIX GitHub at line 6 of file macro.C
Referenced by G4RootMainNtupleManager::CreateNtuple(), G4RootMpiPNtupleManager::CreateNtuple(), G4XmlNtupleManager::CreateTNtuple(), G4CsvNtupleManager::CreateTNtuple(), G4Hdf5NtupleManager::CreateTNtuple(), G4RootNtupleManager::CreateTNtuple(), G4XmlNtupleManager::CreateTNtupleFromBooking(), G4CsvNtupleManager::CreateTNtupleFromBooking(), G4TNtupleManager< tools::hdf5::ntuple >::FillNtupleTColumn(), G4TNtupleManager< tools::wroot::ntuple >::FillNtupleTColumn(), G4RootMpiPNtupleManager::FillNtupleTColumn(), G4RootPNtupleManager::FillNtupleTColumn(), G4Hdf5RNtupleManager::GetTNtupleRow(), G4CsvRNtupleManager::GetTNtupleRow(), G4RootRNtupleManager::GetTNtupleRow(), G4XmlRNtupleManager::GetTNtupleRow(), G4RootMainNtupleManager::Merge(), plot(), G4CsvAnalysisReader::ReadNtupleImpl(), G4Hdf5AnalysisReader::ReadNtupleImpl(), G4XmlAnalysisReader::ReadNtupleImpl(), G4RootAnalysisReader::ReadNtupleImpl(), G4RootMainNtupleManager::Reset(), G4XmlRNtupleManager::SetNtupleDColumn(), G4XmlRNtupleManager::SetNtupleFColumn(), G4XmlRNtupleManager::SetNtupleIColumn(), and G4XmlAnalysisManager::WriteNtuple().
Double_t xx
Definition at line 12 of file macro.C.
View newest version in sPHENIX GitHub at line 12 of file macro.C
Referenced by G4ReflectedSolid::BoundingLimits(), G4Polyhedra::BoundingLimits(), G4PreCompoundTransitions::CalculateProbability(), G4MIRDLiver::Construct(), G4MIRDRightKidney::Construct(), G4MIRDRightScapula::Construct(), G4MIRDLeftScapula::Construct(), G4MIRDLeftKidney::Construct(), G4MIRDThyroid::Construct(), G4MIRDPancreas::Construct(), G4MIRDRibCage::Construct(), G4MIRDUpperSpine::Construct(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), Packet_idcdevdescr::decode(), G4Abla::direct(), G4VTwistedFaceted::DistanceToIn(), G4TwistedTubs::DistanceToIn(), G4Para::DistanceToIn(), G4VTwistedFaceted::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4Para::DistanceToOut(), G4TwistTrapFlatSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), oncsSub_iddreamv0::dump(), BrachyUserScoreWriter::DumpQuantityToFile(), G4ionEffectiveCharge::EffectiveCharge(), HistoManager::EndOfRun(), G4INCL::DeltaProductionChannel::fillFinalState(), G4INCL::ElasticChannel::fillFinalState(), G4ElasticHadrNucleusHE::FillFq2(), G4JTPolynomialSolver::FindRoots(), G4BoundingEnvelope::FindScaleFactor(), G4DensityEffectCalculator::G4DensityEffectCalculator(), G4Exp(), G4Abla::gammln(), EmcCluster::GetCorrPos(), EmcCluster::GetE4(), EmcCluster::GetE9(), EmcCluster::GetECore(), EmcCluster::GetECoreCorrected(), G4ParticleHPThermalScattering::getMu(), G4TwistTrapAlphaSide::GetNormal(), G4TwistBoxSide::GetNormal(), G4TwistTrapParallelSide::GetNormal(), G4TwistTubsSide::GetNormal(), G4TwistTubsHypeSide::GetNormal(), G4EllipticalCone::GetPointOnSurface(), G4ElasticHadrNucleusHE::GetQ2_2(), G4NuMuNucleusCcModel::GetXkr(), G4NuMuNucleusNcModel::GetXkr(), G4NeutrinoNucleusModel::GgSampleNM(), G4Abla::guet(), hifun(), hirnd(), hirnd2(), G4LFission::init(), PrimaryGeneratorAction2::InitFunction(), G4PolarizedBhabhaCrossSection::Initialize(), G4PolarizedMollerCrossSection::Initialize(), G4Para::Inside(), G4VEmissionProbability::IntegrateProbability(), luradk(), BEmcRec::Momenta(), HepGeom::operator*(), BEmcProfile::PredictEnergy(), RawClusterBuilderTemplate::process_event(), G4TwistTubsSide::ProjectAtPXPZ(), G4TwistBoxSide::ProjectPoint(), G4TwistTrapParallelSide::ProjectPoint(), G4TwistTrapAlphaSide::ProjectPoint(), pygraw(), pymirm(), pypdel(), pypdfu(), pyradk(), DicomHandler::ReadData(), G4VTwistSurface::CurrentStatus::ResetfDone(), HepGeom::BasicVector3D< T >::rotate(), CLHEP::Hep2Vector::rotate(), G4ParticleHPLabAngularEnergy::Sample(), G4UrbanMscModel::SampleCosineTheta(), G4UrbanAdjointMscModel::SampleCosineTheta(), G4RayleighAngularGenerator::SampleDirection(), G4PenelopeRayleighModel::SampleSecondaries(), G4NuMuNucleusCcModel::SampleXkr(), G4NuMuNucleusNcModel::SampleXkr(), G4VTwistSurface::CurrentStatus::SetCurrentStatus(), HadrontherapyDetectorHit::SetEdepAndPosition(), BEmcRec::SetTowerGeometry(), DicomHandler::StoreData(), G4VTwistedFaceted::SurfaceNormal(), G4TwistedTubs::SurfaceNormal(), G4Para::SurfaceNormal(), HepGeom::Normal3D< float >::transform(), HepGeom::Normal3D< double >::transform(), and G4Physics2DVector::Value().