ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/global/pyG4UnitsTable.cc File Reference
pyG4UnitsTable.cc File Reference
#include <boost/python.hpp>
#include "pyG4indexing.hh"
#include "G4UnitsTable.hh"
Functions
void export_G4UnitsTable ()
Function Documentation
void export_G4UnitsTable ()
Definition at line 40 of file pyG4UnitsTable.cc.
View newest version in sPHENIX GitHub at line 40 of file pyG4UnitsTable.cc
References G4UnitDefinition::BuildUnitsTable(), G4UnitDefinition::GetCategory(), G4BestUnit::GetCategory(), G4BestUnit::GetIndexOfCategory(), G4UnitDefinition::GetName(), G4UnitsCategory::GetName(), G4UnitsCategory::GetNameMxLen(), G4UnitsCategory::GetSymbMxLen(), G4UnitDefinition::GetSymbol(), G4UnitsCategory::GetUnitsList(), G4UnitDefinition::GetUnitsTable(), G4UnitDefinition::GetValue(), G4UnitDefinition::GetValueOf(), G4UnitsCategory::PrintCategory(), G4UnitDefinition::PrintDefinition(), G4UnitDefinition::PrintUnitsTable(), G4UnitsCategory::UpdateNameMxLen(), and G4UnitsCategory::UpdateSymbMxLen().
Referenced by BOOST_PYTHON_MODULE().