ECCE @ EIC Software: G4VDCIOentry Class Reference
G4VDCIOentry Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VDCIOentry.hh>
Public Member Functions
G4VDCIOentry (std::string n)
virtual ~G4VDCIOentry ()
void SetVerboseLevel (G4int v)
std::string GetName ()
virtual void CreateDCIOmanager (std::string, std::string)
Protected Attributes
G4int m_verbose
Private Attributes
std::string m_name
Detailed Description
Definition at line 41 of file G4VDCIOentry.hh.
View newest version in sPHENIX GitHub at line 41 of file G4VDCIOentry.hh
Constructor & Destructor Documentation
G4VDCIOentry::G4VDCIOentry (std::string n)
Definition at line 37 of file G4VDCIOentry.cc.
View newest version in sPHENIX GitHub at line 37 of file G4VDCIOentry.cc
References c, G4DCIOcatalog::GetDCIOcatalog(), G4PersistencyCenter::GetPersistencyCenter(), m_verbose, G4DCIOcatalog::RegisterEntry(), and G4PersistencyCenter::VerboseLevel().
virtual G4VDCIOentry::~G4VDCIOentry () inline virtual
Definition at line 47 of file G4VDCIOentry.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VDCIOentry.hh
Member Function Documentation
virtual void G4VDCIOentry::CreateDCIOmanager (std::string , std::string) inline virtual
Reimplemented in G4DCIOentryT< T >.
Definition at line 57 of file G4VDCIOentry.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VDCIOentry.hh
Referenced by G4PersistencyCenter::AddDCIOmanager().
std::string G4VDCIOentry::GetName (void) inline
Definition at line 54 of file G4VDCIOentry.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VDCIOentry.hh
References m_name.
Referenced by G4DCIOcatalog::RegisterEntry().
void G4VDCIOentry::SetVerboseLevel (G4int v) inline
Definition at line 51 of file G4VDCIOentry.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VDCIOentry.hh
References m_verbose, and v.
Member Data Documentation
std::string G4VDCIOentry::m_name private
Definition at line 64 of file G4VDCIOentry.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VDCIOentry.hh
Referenced by GetName().
G4int G4VDCIOentry::m_verbose protected
Definition at line 61 of file G4VDCIOentry.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VDCIOentry.hh
Referenced by G4DCIOentryT< T >::CreateDCIOmanager(), G4DCIOentryT< T >::G4DCIOentryT(), G4VDCIOentry(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VDCIOentry.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4VDCIOentry.cc