ECCE @ EIC Software: CLHEP::HepRotationZ Class Reference
CLHEP::HepRotationZ Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/RotationZ.h>
Public Member Functions
HepRotationZ ()
HepRotationZ (double delta)
HepRotationZ (const HepRotationZ &orig)
HepRotationZ (HepRotationZ &&orig)=default
HepRotationZ & operator= (const HepRotationZ &r)
HepRotationZ & operator= (HepRotationZ &&r)=default
HepRotationZ & set (double delta)
~HepRotationZ ()
Hep3Vector colX () const
Hep3Vector colY () const
Hep3Vector colZ () const
Hep3Vector rowX () const
Hep3Vector rowY () const
Hep3Vector rowZ () const
double xx () const
double xy () const
double xz () const
double yx () const
double yy () const
double yz () const
double zx () const
double zy () const
double zz () const
HepRep3x3 rep3x3 () const
double getPhi () const
double getTheta () const
double getPsi () const
double phi () const
double theta () const
double psi () const
HepEulerAngles eulerAngles () const
double getDelta () const
Hep3Vector getAxis () const
double delta () const
Hep3Vector axis () const
HepAxisAngle axisAngle () const
void getAngleAxis (double &delta, Hep3Vector &axis) const
double phiX () const
double phiY () const
double phiZ () const
double thetaX () const
double thetaY () const
double thetaZ () const
HepLorentzVector col1 () const
HepLorentzVector col2 () const
HepLorentzVector col3 () const
HepLorentzVector col4 () const
HepLorentzVector row1 () const
HepLorentzVector row2 () const
HepLorentzVector row3 () const
HepLorentzVector row4 () const
double xt () const
double yt () const
double zt () const
double tx () const
double ty () const
double tz () const
double tt () const
HepRep4x4 rep4x4 () const
void setDelta (double delta)
void decompose (HepAxisAngle &rotation, Hep3Vector &boost) const
void decompose (Hep3Vector &boost, HepAxisAngle &rotation) const
void decompose (HepRotation &rotation, HepBoost &boost) const
void decompose (HepBoost &boost, HepRotation &rotation) const
bool isIdentity () const
int compare (const HepRotationZ &r) const
bool operator== (const HepRotationZ &r) const
bool operator!= (const HepRotationZ &r) const
bool operator< (const HepRotationZ &r) const
bool operator> (const HepRotationZ &r) const
bool operator<= (const HepRotationZ &r) const
bool operator>= (const HepRotationZ &r) const
double distance2 (const HepRotationZ &r) const
double distance2 (const HepRotation &r) const
double howNear (const HepRotationZ &r) const
double howNear (const HepRotation &r) const
bool isNear (const HepRotationZ &r, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepRotation &r, double epsilon=Hep4RotationInterface::tolerance) const
double distance2 (const HepBoost &lt) const
double distance2 (const HepLorentzRotation &lt) const
double howNear (const HepBoost &lt) const
double howNear (const HepLorentzRotation &lt) const
bool isNear (const HepBoost &lt, double epsilon=Hep4RotationInterface::tolerance) const
bool isNear (const HepLorentzRotation &lt, double epsilon=Hep4RotationInterface::tolerance) const
double norm2 () const
void rectify ()
Hep3Vector operator() (const Hep3Vector &p) const
Hep3Vector operator* (const Hep3Vector &p) const
HepLorentzVector operator() (const HepLorentzVector &w) const
HepLorentzVector operator* (const HepLorentzVector &w) const
HepRotationZ operator* (const HepRotationZ &rz) const
HepRotationZ & operator*= (const HepRotationZ &r)
HepRotationZ & transform (const HepRotationZ &r)
HepRotationZ inverse () const
HepRotationZ & invert ()
std::ostream & print (std::ostream &os) const
Static Public Member Functions
static double getTolerance ()
static double setTolerance (double tol)
Protected Member Functions
HepRotationZ (double dd, double ss, double cc)
Static Protected Member Functions
static double proper (double delta)
Protected Attributes
double its_d
double its_s
double its_c
Friends
HepRotationZ inverseOf (const HepRotationZ &r)
Detailed Description
Author
Definition at line 42 of file RotationZ.h.
View newest version in sPHENIX GitHub at line 42 of file RotationZ.h
Constructor & Destructor Documentation
CLHEP::HepRotationZ::HepRotationZ () inline
CLHEP::HepRotationZ::HepRotationZ (double delta)
Definition at line 31 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 31 of file RotationZ.cc
CLHEP::HepRotationZ::HepRotationZ (const HepRotationZ & orig) inline
CLHEP::HepRotationZ::HepRotationZ (HepRotationZ && orig) inline default
CLHEP::HepRotationZ::~HepRotationZ () inline
CLHEP::HepRotationZ::HepRotationZ (double dd, double ss, double cc) inline protected
Member Function Documentation
Hep3Vector CLHEP::HepRotationZ::axis () const inline
HepAxisAngle CLHEP::HepRotationZ::axisAngle () const inline
HepLorentzVector CLHEP::HepRotationZ::col1 () const inline
HepLorentzVector CLHEP::HepRotationZ::col2 () const inline
HepLorentzVector CLHEP::HepRotationZ::col3 () const inline
HepLorentzVector CLHEP::HepRotationZ::col4 () const inline
Hep3Vector CLHEP::HepRotationZ::colX () const inline
Hep3Vector CLHEP::HepRotationZ::colY () const inline
Hep3Vector CLHEP::HepRotationZ::colZ () const inline
int CLHEP::HepRotationZ::compare (const HepRotationZ & r) const inline
void CLHEP::HepRotationZ::decompose (HepAxisAngle & rotation, Hep3Vector & boost) const
Definition at line 100 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 100 of file RotationZ.cc
References CLHEP::Hep3Vector::set().
void CLHEP::HepRotationZ::decompose (Hep3Vector & boost, HepAxisAngle & rotation) const
Definition at line 106 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 106 of file RotationZ.cc
References CLHEP::Hep3Vector::set().
void CLHEP::HepRotationZ::decompose (HepRotation & rotation, HepBoost & boost) const
Definition at line 112 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 112 of file RotationZ.cc
References CLHEP::HepBoost::set().
void CLHEP::HepRotationZ::decompose (HepBoost & boost, HepRotation & rotation) const
Definition at line 118 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 118 of file RotationZ.cc
References CLHEP::HepBoost::set().
double CLHEP::HepRotationZ::delta () const inline
double CLHEP::HepRotationZ::distance2 (const HepRotationZ & r) const
Definition at line 123 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 123 of file RotationZ.cc
References its_c, and its_s.
Referenced by distance2(), howNear(), and isNear().
double CLHEP::HepRotationZ::distance2 (const HepRotation & r) const
Definition at line 128 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 128 of file RotationZ.cc
References sum, xx(), CLHEP::HepRotation::xx(), xy(), CLHEP::HepRotation::xy(), yx(), CLHEP::HepRotation::yx(), yy(), CLHEP::HepRotation::yy(), and CLHEP::HepRotation::zz().
double CLHEP::HepRotationZ::distance2 (const HepBoost & lt) const
Definition at line 146 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 146 of file RotationZ.cc
References distance2().
double CLHEP::HepRotationZ::distance2 (const HepLorentzRotation & lt) const
Definition at line 136 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 136 of file RotationZ.cc
References a, b, CLHEP::Hep3Vector::beta(), CLHEP::HepLorentzRotation::decompose(), distance2(), and r.
HepEulerAngles CLHEP::HepRotationZ::eulerAngles () const
Definition at line 54 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 54 of file RotationZ.cc
References phi(), psi(), and theta().
void CLHEP::HepRotationZ::getAngleAxis (double & delta, Hep3Vector & axis) const inline
Hep3Vector CLHEP::HepRotationZ::getAxis () const inline
double CLHEP::HepRotationZ::getDelta () const inline
double CLHEP::HepRotationZ::getPhi () const inline
double CLHEP::HepRotationZ::getPsi () const inline
double CLHEP::HepRotationZ::getTheta () const inline
static double CLHEP::HepRotationZ::getTolerance () inline static
double CLHEP::HepRotationZ::howNear (const HepRotationZ & r) const
Definition at line 150 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 150 of file RotationZ.cc
References distance2().
double CLHEP::HepRotationZ::howNear (const HepRotation & r) const
Definition at line 153 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 153 of file RotationZ.cc
References distance2().
double CLHEP::HepRotationZ::howNear (const HepBoost & lt) const
Definition at line 156 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 156 of file RotationZ.cc
References distance2().
double CLHEP::HepRotationZ::howNear (const HepLorentzRotation & lt) const
Definition at line 159 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 159 of file RotationZ.cc
References distance2().
HepRotationZ CLHEP::HepRotationZ::inverse () const inline
HepRotationZ& CLHEP::HepRotationZ::invert () inline
bool CLHEP::HepRotationZ::isIdentity () const inline
bool CLHEP::HepRotationZ::isNear (const HepRotationZ & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 162 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 162 of file RotationZ.cc
References distance2().
bool CLHEP::HepRotationZ::isNear (const HepRotation & r, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 165 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 165 of file RotationZ.cc
References distance2().
bool CLHEP::HepRotationZ::isNear (const HepBoost & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 168 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 168 of file RotationZ.cc
References distance2().
bool CLHEP::HepRotationZ::isNear (const HepLorentzRotation & lt, double epsilon = Hep4RotationInterface::tolerance) const
Definition at line 171 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 171 of file RotationZ.cc
References distance2().
double CLHEP::HepRotationZ::norm2 () const
Definition at line 176 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 176 of file RotationZ.cc
References its_c.
bool CLHEP::HepRotationZ::operator!= (const HepRotationZ & r) const inline
Hep3Vector CLHEP::HepRotationZ::operator() (const Hep3Vector & p) const inline
HepLorentzVector CLHEP::HepRotationZ::operator() (const HepLorentzVector & w) const inline
Hep3Vector CLHEP::HepRotationZ::operator* (const Hep3Vector & p) const inline
HepLorentzVector CLHEP::HepRotationZ::operator* (const HepLorentzVector & w) const inline
HepRotationZ CLHEP::HepRotationZ::operator* (const HepRotationZ & rz) const inline
HepRotationZ& CLHEP::HepRotationZ::operator*= (const HepRotationZ & r) inline
bool CLHEP::HepRotationZ::operator< (const HepRotationZ & r) const inline
bool CLHEP::HepRotationZ::operator<= (const HepRotationZ & r) const inline
HepRotationZ& CLHEP::HepRotationZ::operator= (const HepRotationZ & r) inline
HepRotationZ& CLHEP::HepRotationZ::operator= (HepRotationZ && r) inline default
bool CLHEP::HepRotationZ::operator== (const HepRotationZ & r) const inline
bool CLHEP::HepRotationZ::operator> (const HepRotationZ & r) const inline
bool CLHEP::HepRotationZ::operator>= (const HepRotationZ & r) const inline
double CLHEP::HepRotationZ::phi () const
Definition at line 42 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 42 of file RotationZ.cc
References its_d.
Referenced by eulerAngles().
double CLHEP::HepRotationZ::phiX () const
Definition at line 66 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 66 of file RotationZ.cc
References xx(), and yx().
double CLHEP::HepRotationZ::phiY () const
Definition at line 71 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 71 of file RotationZ.cc
References xy(), and yy().
double CLHEP::HepRotationZ::phiZ () const
Definition at line 75 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 75 of file RotationZ.cc
References xz(), and yz().
std::ostream & CLHEP::HepRotationZ::print (std::ostream & os) const
Definition at line 180 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 180 of file RotationZ.cc
References its_c, its_d, and its_s.
static double CLHEP::HepRotationZ::proper (double delta) inline static protected
Referenced by set().
double CLHEP::HepRotationZ::psi () const
Definition at line 50 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 50 of file RotationZ.cc
References its_d.
Referenced by eulerAngles().
void CLHEP::HepRotationZ::rectify () inline
HepRep3x3 CLHEP::HepRotationZ::rep3x3 () const inline
HepRep4x4 CLHEP::HepRotationZ::rep4x4 () const inline
HepLorentzVector CLHEP::HepRotationZ::row1 () const inline
HepLorentzVector CLHEP::HepRotationZ::row2 () const inline
HepLorentzVector CLHEP::HepRotationZ::row3 () const inline
HepLorentzVector CLHEP::HepRotationZ::row4 () const inline
Hep3Vector CLHEP::HepRotationZ::rowX () const inline
Hep3Vector CLHEP::HepRotationZ::rowY () const inline
Hep3Vector CLHEP::HepRotationZ::rowZ () const inline
HepRotationZ & CLHEP::HepRotationZ::set (double delta)
Definition at line 35 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 35 of file RotationZ.cc
References its_c, its_d, its_s, and proper().
void CLHEP::HepRotationZ::setDelta (double delta)
Definition at line 95 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 95 of file RotationZ.cc
static double CLHEP::HepRotationZ::setTolerance (double tol) inline static
double CLHEP::HepRotationZ::theta () const
Definition at line 46 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 46 of file RotationZ.cc
Referenced by eulerAngles().
double CLHEP::HepRotationZ::thetaX () const
Definition at line 80 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 80 of file RotationZ.cc
References CLHEP::safe_acos(), and zx().
double CLHEP::HepRotationZ::thetaY () const
Definition at line 85 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 85 of file RotationZ.cc
References CLHEP::safe_acos(), and zy().
double CLHEP::HepRotationZ::thetaZ () const
Definition at line 90 of file RotationZ.cc.
View newest version in sPHENIX GitHub at line 90 of file RotationZ.cc
References CLHEP::safe_acos(), and zz().
HepRotationZ& CLHEP::HepRotationZ::transform (const HepRotationZ & r) inline
double CLHEP::HepRotationZ::tt () const inline
double CLHEP::HepRotationZ::tx () const inline
double CLHEP::HepRotationZ::ty () const inline
double CLHEP::HepRotationZ::tz () const inline
double CLHEP::HepRotationZ::xt () const inline
double CLHEP::HepRotationZ::xx () const inline
Referenced by distance2(), and phiX().
double CLHEP::HepRotationZ::xy () const inline
Referenced by distance2(), and phiY().
double CLHEP::HepRotationZ::xz () const inline
Referenced by phiZ().
double CLHEP::HepRotationZ::yt () const inline
double CLHEP::HepRotationZ::yx () const inline
Referenced by distance2(), and phiX().
double CLHEP::HepRotationZ::yy () const inline
Referenced by distance2(), and phiY().
double CLHEP::HepRotationZ::yz () const inline
Referenced by phiZ().
double CLHEP::HepRotationZ::zt () const inline
double CLHEP::HepRotationZ::zx () const inline
Referenced by thetaX().
double CLHEP::HepRotationZ::zy () const inline
Referenced by thetaY().
double CLHEP::HepRotationZ::zz () const inline
Referenced by thetaZ().
Friends And Related Function Documentation
HepRotationZ inverseOf (const HepRotationZ & r) friend
Member Data Documentation
double CLHEP::HepRotationZ::its_c protected
Definition at line 267 of file RotationZ.h.
View newest version in sPHENIX GitHub at line 267 of file RotationZ.h
Referenced by distance2(), norm2(), print(), and set().
double CLHEP::HepRotationZ::its_d protected
Definition at line 263 of file RotationZ.h.
View newest version in sPHENIX GitHub at line 263 of file RotationZ.h
Referenced by phi(), print(), psi(), and set().
double CLHEP::HepRotationZ::its_s protected
Definition at line 266 of file RotationZ.h.
View newest version in sPHENIX GitHub at line 266 of file RotationZ.h
Referenced by distance2(), print(), and set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/RotationZ.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/RotationZ.cc