ECCE @ EIC Software: ExN02ChamberParameterisation Class Reference
ExN02ChamberParameterisation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/ExN02ChamberParameterisation.hh>
Public Member Functions
ExN02ChamberParameterisation (G4int NoChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
virtual ~ExN02ChamberParameterisation ()
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Box &trackerLayer, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Tubs &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4int fNoChambers
G4double fStartZ
G4double fHalfWidth
G4double fSpacing
G4double fHalfLengthFirst
G4double fHalfLengthIncr
Detailed Description
Definition at line 64 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 64 of file ExN02ChamberParameterisation.hh
Constructor & Destructor Documentation
ExN02ChamberParameterisation::ExN02ChamberParameterisation (G4int NoChambers, G4double startZ, G4double spacing, G4double widthChamber, G4double lengthInitial, G4double lengthFinal)
Definition at line 42 of file ExN02ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 42 of file ExN02ChamberParameterisation.cc
References FatalException, fHalfLengthFirst, fHalfLengthIncr, fHalfWidth, fNoChambers, fSpacing, fStartZ, and G4Exception().
ExN02ChamberParameterisation::~ExN02ChamberParameterisation () virtual
Definition at line 69 of file ExN02ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 69 of file ExN02ChamberParameterisation.cc
Member Function Documentation
void ExN02ChamberParameterisation::ComputeDimensions (G4Box & trackerLayer, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 86 of file ExN02ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 86 of file ExN02ChamberParameterisation.cc
References G4Box::SetXHalfLength(), G4Box::SetYHalfLength(), and G4Box::SetZHalfLength().
void ExN02ChamberParameterisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 86 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 86 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 87 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 87 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 88 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 88 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 89 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 90 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 90 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 91 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 91 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 92 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 92 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 93 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 93 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 94 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 94 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Tubs & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 95 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 95 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 96 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 96 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 97 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 97 of file ExN02ChamberParameterisation.hh
void ExN02ChamberParameterisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Definition at line 75 of file ExN02ChamberParameterisation.cc.
View newest version in sPHENIX GitHub at line 75 of file ExN02ChamberParameterisation.cc
References Acts::Test::origin(), G4VPhysicalVolume::SetRotation(), and G4VPhysicalVolume::SetTranslation().
Member Data Documentation
G4double ExN02ChamberParameterisation::fHalfLengthFirst private
Definition at line 104 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 104 of file ExN02ChamberParameterisation.hh
Referenced by ExN02ChamberParameterisation().
G4double ExN02ChamberParameterisation::fHalfLengthIncr private
Definition at line 105 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 105 of file ExN02ChamberParameterisation.hh
Referenced by ExN02ChamberParameterisation().
G4double ExN02ChamberParameterisation::fHalfWidth private
Definition at line 102 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 102 of file ExN02ChamberParameterisation.hh
Referenced by ExN02ChamberParameterisation().
G4int ExN02ChamberParameterisation::fNoChambers private
Definition at line 100 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 100 of file ExN02ChamberParameterisation.hh
Referenced by ExN02ChamberParameterisation().
G4double ExN02ChamberParameterisation::fSpacing private
Definition at line 103 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 103 of file ExN02ChamberParameterisation.hh
Referenced by ExN02ChamberParameterisation().
G4double ExN02ChamberParameterisation::fStartZ private
Definition at line 101 of file ExN02ChamberParameterisation.hh.
View newest version in sPHENIX GitHub at line 101 of file ExN02ChamberParameterisation.hh
Referenced by ExN02ChamberParameterisation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/ExN02ChamberParameterisation.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/src/ExN02ChamberParameterisation.cc