ECCE @ EIC Software: G4ElementSelector Class Reference
G4ElementSelector Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4ElementSelector.hh>
Public Member Functions
G4ElementSelector ()
virtual ~G4ElementSelector ()
virtual G4Element * SelectZandA (const G4Track &track, G4Nucleus *)
Private Member Functions
G4ElementSelector & operator= (const G4ElementSelector &right)
G4ElementSelector (const G4ElementSelector &)
Private Attributes
std::vector< G4double > prob
Detailed Description
Definition at line 60 of file G4ElementSelector.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ElementSelector.hh
Constructor & Destructor Documentation
G4ElementSelector::G4ElementSelector ()
Definition at line 48 of file G4ElementSelector.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ElementSelector.cc
G4ElementSelector::~G4ElementSelector () virtual
Definition at line 53 of file G4ElementSelector.cc.
View newest version in sPHENIX GitHub at line 53 of file G4ElementSelector.cc
G4ElementSelector::G4ElementSelector (const G4ElementSelector &) private
Member Function Documentation
G4ElementSelector& G4ElementSelector::operator= (const G4ElementSelector & right) private
G4Element * G4ElementSelector::SelectZandA (const G4Track & track, G4Nucleus * target) virtual
Definition at line 59 of file G4ElementSelector.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ElementSelector.cc
References A(), ab, G4lrint(), G4UniformRand, G4Material::GetAtomicNumDensityVector(), G4Material::GetElementVector(), G4Element::GetIsotope(), G4Element::GetIsotopeVector(), G4Track::GetMaterial(), G4Isotope::GetN(), G4Material::GetNumberOfElements(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZ(), mat, prob, G4Nucleus::SetParameters(), sum, y, and Z.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), and G4HadronStoppingProcess::AtRestDoIt().
Member Data Documentation
std::vector<G4double> G4ElementSelector::prob private
Definition at line 76 of file G4ElementSelector.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ElementSelector.hh
Referenced by SelectZandA().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4ElementSelector.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/src/G4ElementSelector.cc