ECCE @ EIC Software: G4MPImanager Class Reference
G4MPImanager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/include/G4MPImanager.hh>
Public Types
enum { kRANK_MASTER = 0 }
enum {
kTAG_G4COMMAND = 100, kTAG_G4STATUS = 200, kTAG_G4SEED = 300, kTAG_DATA = 1000,
kTAG_HISTO = 1001, kTAG_RUN = 1002, kTAG_CMDSCR = 1003, kTAG_NTUPLE = 1004
}
Public Member Functions
G4MPImanager (int nof_extra_workers=0)
G4MPImanager (int argc, char **argv, int nof_extra_workers=0)
~G4MPImanager ()
G4MPIsession * GetMPIsession () const
G4int GetVerbose () const
void SetVerbose (G4int iverbose)
G4int GetTotalSize () const
G4int GetActiveSize () const
G4int GetRank () const
G4bool IsMaster () const
G4bool IsSlave () const
G4bool IsExtraWorker () const
G4bool IsInitMacro () const
const G4String & GetInitFileName () const
G4bool IsBatchMode () const
const G4String & GetMacroFileName () const
void SetMasterWeight (G4double aweight)
G4double GetMasterWeight () const
void SetExtraWorker (G4VMPIextraWorker *extraWorker)
G4VMPIextraWorker * GetExtraWorker () const
G4VMPIseedGenerator * GetSeedGenerator () const
G4String BcastCommand (const G4String &command)
void ShowStatus ()
void ShowSeeds ()
void SetSeed (G4int inode, G4long seed)
void WaitBeamOn ()
void DistributeSeeds ()
void ExecuteMacroFile (const G4String &fname, G4bool qbatch=false)
G4bool CheckThreadStatus ()
void ExecuteThreadCommand (const G4String &command)
void ExecuteBeamOnThread (const G4String &command)
void JoinBeamOnThread ()
void BeamOn (G4int nevent, G4bool qdivide=true)
void Print (const G4String &message)
void ShowHelp () const
const MPI::Intracomm * GetComm () const
const MPI_Comm * GetProcessingComm () const
const MPI_Comm * GetCollectingComm () const
const MPI_Comm * GetAllComm () const
Static Public Member Functions
static G4MPImanager * GetManager ()
Private Member Functions
DISALLOW_COPY_AND_ASSIGN (G4MPImanager)
void Initialize ()
void ParseArguments (G4int argc, char **argv)
void UpdateStatus ()
Private Attributes
G4MPImessenger * messenger_
G4MPIsession * session_
G4VMPIextraWorker * extra_worker_
G4VMPIseedGenerator * seed_generator_
G4MPIstatus * status_
G4int verbose_
G4bool is_master_
G4bool is_slave_
G4bool is_extra_worker_
G4int rank_
G4int size_
G4int world_size_
MPI::Intracomm COMM_G4COMMAND_
MPI_Comm processing_comm_
MPI_Comm collecting_comm_
MPI_Comm all_comm_
MPI_Group world_group_
MPI_Group processing_group_
MPI_Group collecting_group_
MPI_Group all_group_
G4bool qfcout_
std::ofstream fscout_
G4bool qinitmacro_
G4String init_file_name_
G4bool qbatchmode_
G4String macro_file_name_
pthread_t thread_id_
G4double master_weight_
G4int nof_extra_workers_
Static Private Attributes
static G4MPImanager * g4mpi_ = NULL
Detailed Description
Definition at line 46 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4MPImanager.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
kRANK_MASTER
Definition at line 49 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 49 of file G4MPImanager.hh
anonymous enum
Enumerator:
kTAG_G4COMMAND
kTAG_G4STATUS
kTAG_G4SEED
kTAG_DATA
kTAG_HISTO
kTAG_RUN
kTAG_CMDSCR
kTAG_NTUPLE
Definition at line 51 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 51 of file G4MPImanager.hh
Constructor & Destructor Documentation
G4MPImanager::G4MPImanager (int nof_extra_workers = 0)
Definition at line 69 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 69 of file G4MPImanager.cc
References Initialize().
G4MPImanager::G4MPImanager (int argc, char ** argv, int nof_extra_workers = 0)
Definition at line 82 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 82 of file G4MPImanager.cc
References Initialize(), and ParseArguments().
G4MPImanager::~G4MPImanager ()
Definition at line 96 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 96 of file G4MPImanager.cc
References all_comm_, all_group_, collecting_comm_, collecting_group_, COMM_G4COMMAND_, Finalize(), fscout_, is_slave_, messenger_, nof_extra_workers_, processing_comm_, processing_group_, qfcout_, session_, status_, and world_group_.
Member Function Documentation
G4String G4MPImanager::BcastCommand (const G4String & command)
Definition at line 515 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 515 of file G4MPImanager.cc
References COMM_G4COMMAND_, is_extra_worker_, is_master_, kRANK_MASTER, kTAG_G4COMMAND, and size_.
void G4MPImanager::BeamOn (G4int nevent, G4bool qdivide = true)
Definition at line 562 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 562 of file G4MPImanager.cc
References G4UIcommand::ConvertToString(), G4cout, G4endl, G4RunManager::GetRunManager(), G4UImanager::GetUIpointer(), is_master_, master_weight_, size_, status_, and verbose_.
G4bool G4MPImanager::CheckThreadStatus ()
Definition at line 424 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 424 of file G4MPImanager.cc
References COMM_G4COMMAND_, is_master_, kRANK_MASTER, kTAG_G4STATUS, size_, and thread_id_.
Referenced by ExecuteBeamOnThread(), and ShowStatus().
G4MPImanager::DISALLOW_COPY_AND_ASSIGN (G4MPImanager) private
void G4MPImanager::DistributeSeeds ()
Definition at line 383 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 383 of file G4MPImanager.cc
References is_extra_worker_, rank_, and seed_generator_.
Referenced by Initialize().
void G4MPImanager::ExecuteBeamOnThread (const G4String & command)
Definition at line 484 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 484 of file G4MPImanager.cc
References CheckThreadStatus(), test::cmdstr, FatalException, G4cout, G4endl, G4Exception(), is_master_, and thread_id_.
void G4MPImanager::ExecuteMacroFile (const G4String & fname, G4bool qbatch = false)
Definition at line 551 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 551 of file G4MPImanager.cc
References qbatchmode_.
void G4MPImanager::ExecuteThreadCommand (const G4String & command)
Definition at line 455 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 455 of file G4MPImanager.cc
References fCommandSucceeded, fIllegalApplicationState, G4cerr, G4endl, G4UImanager::GetUIpointer(), and thread_id_.
G4int G4MPImanager::GetActiveSize () const inline
Definition at line 212 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 212 of file G4MPImanager.hh
References size_.
Referenced by G4MPIntupleMerger::G4MPIntupleMerger(), G4VUserMPIrunMerger::Merge(), and G4MPIscorerMerger::Merge().
const MPI_Comm* G4MPImanager::GetAllComm () const inline
Definition at line 120 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4MPImanager.hh
References all_comm_.
Referenced by G4MPIntupleMerger::G4MPIntupleMerger().
const MPI_Comm* G4MPImanager::GetCollectingComm () const inline
Definition at line 119 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4MPImanager.hh
References collecting_comm_.
const MPI::Intracomm* G4MPImanager::GetComm () const inline
Definition at line 117 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 117 of file G4MPImanager.hh
References COMM_G4COMMAND_.
Referenced by G4VUserMPIrunMerger::Merge(), G4MPIhistoMerger::Merge(), G4MPIscorerMerger::Merge(), and G4VUserMPIrunMerger::Receive().
G4VMPIextraWorker * G4MPImanager::GetExtraWorker () const inline
Definition at line 267 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 267 of file G4MPImanager.hh
References extra_worker_.
const G4String & G4MPImanager::GetInitFileName () const inline
Definition at line 238 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 238 of file G4MPImanager.hh
References init_file_name_.
Referenced by G4MPIsession::SessionStart().
const G4String & G4MPImanager::GetMacroFileName () const inline
Definition at line 249 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 249 of file G4MPImanager.hh
References macro_file_name_.
Referenced by G4MPIsession::SessionStart().
G4MPImanager * G4MPImanager::GetManager () static
Definition at line 127 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 127 of file G4MPImanager.cc
References FatalException, G4Exception(), and g4mpi_.
Referenced by G4MPIrandomSeedGenerator::CheckDoubleCount(), RunActionMaster::EndOfRunAction(), G4MPIntupleMerger::G4MPIntupleMerger(), G4VMPIsession::G4VMPIsession(), G4MPIrandomSeedGenerator::GenerateSeeds(), G4VUserMPIrunMerger::Merge(), G4MPIhistoMerger::Merge(), G4MPIscorerMerger::Merge(), G4VUserMPIrunMerger::Receive(), RunAction::RunAction(), and RunActionMaster::RunActionMaster().
G4double G4MPImanager::GetMasterWeight () const inline
Definition at line 262 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 262 of file G4MPImanager.hh
References master_weight_.
Referenced by G4MPImessenger::GetCurrentValue().
G4MPIsession * G4MPImanager::GetMPIsession () const inline
Definition at line 182 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 182 of file G4MPImanager.hh
References session_.
const MPI_Comm* G4MPImanager::GetProcessingComm () const inline
Definition at line 118 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 118 of file G4MPImanager.hh
References processing_comm_.
G4int G4MPImanager::GetRank () const inline
Definition at line 202 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 202 of file G4MPImanager.hh
References rank_.
Referenced by G4MPIntupleMerger::G4MPIntupleMerger(), and G4MPIscorerMerger::Merge().
G4VMPIseedGenerator * G4MPImanager::GetSeedGenerator () const inline
Definition at line 272 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 272 of file G4MPImanager.hh
References seed_generator_.
G4int G4MPImanager::GetTotalSize () const inline
Definition at line 207 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 207 of file G4MPImanager.hh
References world_size_.
G4int G4MPImanager::GetVerbose () const inline
Definition at line 187 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 187 of file G4MPImanager.hh
References verbose_.
Referenced by G4MPImessenger::GetCurrentValue().
void G4MPImanager::Initialize () private
Definition at line 148 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 148 of file G4MPImanager.cc
References all_comm_, all_group_, collecting_comm_, collecting_group_, COMM_G4COMMAND_, DistributeSeeds(), FatalException, G4Exception(), g4mpi_, is_extra_worker_, is_master_, is_slave_, JustWarning, kRANK_MASTER, messenger_, MPI_COMM_WORLD, nof_extra_workers_, processing_comm_, processing_group_, rank_, seed_generator_, session_, size_, status_, world_group_, and world_size_.
Referenced by G4MPImanager().
G4bool G4MPImanager::IsBatchMode () const inline
Definition at line 244 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 244 of file G4MPImanager.hh
References qbatchmode_.
G4bool G4MPImanager::IsExtraWorker () const inline
Definition at line 227 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 227 of file G4MPImanager.hh
References is_extra_worker_.
Referenced by main().
G4bool G4MPImanager::IsInitMacro () const inline
Definition at line 232 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 232 of file G4MPImanager.hh
References qinitmacro_.
G4bool G4MPImanager::IsMaster () const inline
Definition at line 217 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 217 of file G4MPImanager.hh
References is_master_.
G4bool G4MPImanager::IsSlave () const inline
Definition at line 222 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 222 of file G4MPImanager.hh
References is_slave_.
void G4MPImanager::JoinBeamOnThread ()
Definition at line 506 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 506 of file G4MPImanager.cc
References thread_id_.
void G4MPImanager::ParseArguments (G4int argc, char ** argv) private
Definition at line 239 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 239 of file G4MPImanager.cc
References c, g4zmq::exit(), Finalize(), test::fname, fscout_, G4cerr, G4endl, init_file_name_, is_master_, is_slave_, macro_file_name_, optarg, opterr, optind, qbatchmode_, qfcout_, qinitmacro_, rank_, ShowHelp(), and verbose_.
Referenced by G4MPImanager().
void G4MPImanager::Print (const G4String & message)
Definition at line 651 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 651 of file G4MPImanager.cc
References fscout_, is_master_, qfcout_, and rank_.
Referenced by ShowStatus().
void G4MPImanager::SetExtraWorker (G4VMPIextraWorker * extraWorker)
Definition at line 137 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 137 of file G4MPImanager.cc
References extra_worker_, FatalException, G4Exception(), and nof_extra_workers_.
Referenced by main().
void G4MPImanager::SetMasterWeight (G4double aweight) inline
Definition at line 254 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 254 of file G4MPImanager.hh
References master_weight_.
void G4MPImanager::SetSeed (G4int inode, G4long seed)
Definition at line 416 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 416 of file G4MPImanager.cc
References rank_, and CLHEP::HepRandom::setTheSeed().
void G4MPImanager::SetVerbose (G4int iverbose) inline
Definition at line 192 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 192 of file G4MPImanager.hh
References verbose_.
Referenced by main().
void G4MPImanager::ShowHelp () const
Definition at line 665 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 665 of file G4MPImanager.cc
References G4cout, G4endl, and is_slave_.
Referenced by ParseArguments().
void G4MPImanager::ShowSeeds ()
Definition at line 393 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 393 of file G4MPImanager.cc
References COMM_G4COMMAND_, G4cout, G4endl, is_master_, kRANK_MASTER, kTAG_G4SEED, rank_, and size_.
void G4MPImanager::ShowStatus ()
Definition at line 334 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 334 of file G4MPImanager.cc
References CheckThreadStatus(), COMM_G4COMMAND_, G4cout, G4endl, G4FFGEnumerations::INT, is_master_, G4MPIstatus::kNSIZE, kRANK_MASTER, kTAG_G4STATUS, Print(), size_, status_, and UpdateStatus().
void G4MPImanager::UpdateStatus () private
Definition at line 307 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 307 of file G4MPImanager.cc
References G4State_EventProc, G4State_GeomClosed, G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), rank_, and status_.
Referenced by ShowStatus().
void G4MPImanager::WaitBeamOn ()
Definition at line 615 of file G4MPImanager.cc.
View newest version in sPHENIX GitHub at line 615 of file G4MPImanager.cc
References G4VMPIextraWorker::BeamOn(), COMM_G4COMMAND_, extra_worker_, G4cout, G4endl, G4FFGEnumerations::INT, is_extra_worker_, is_master_, kRANK_MASTER, kTAG_G4STATUS, qbatchmode_, and size_.
Member Data Documentation
MPI_Comm G4MPImanager::all_comm_ private
Definition at line 156 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 156 of file G4MPImanager.hh
Referenced by GetAllComm(), Initialize(), and ~G4MPImanager().
MPI_Group G4MPImanager::all_group_ private
Definition at line 161 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 161 of file G4MPImanager.hh
Referenced by Initialize(), and ~G4MPImanager().
MPI_Comm G4MPImanager::collecting_comm_ private
Definition at line 154 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 154 of file G4MPImanager.hh
Referenced by GetCollectingComm(), Initialize(), and ~G4MPImanager().
MPI_Group G4MPImanager::collecting_group_ private
Definition at line 160 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 160 of file G4MPImanager.hh
Referenced by Initialize(), and ~G4MPImanager().
MPI::Intracomm G4MPImanager::COMM_G4COMMAND_ private
Definition at line 150 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 150 of file G4MPImanager.hh
Referenced by BcastCommand(), CheckThreadStatus(), GetComm(), Initialize(), ShowSeeds(), ShowStatus(), WaitBeamOn(), and ~G4MPImanager().
G4VMPIextraWorker* G4MPImanager::extra_worker_ private
Definition at line 132 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 132 of file G4MPImanager.hh
Referenced by GetExtraWorker(), SetExtraWorker(), and WaitBeamOn().
std::ofstream G4MPImanager::fscout_ private
Definition at line 165 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 165 of file G4MPImanager.hh
Referenced by ParseArguments(), Print(), and ~G4MPImanager().
G4MPImanager * G4MPImanager::g4mpi_ = NULL static private
Definition at line 129 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 129 of file G4MPImanager.hh
Referenced by GetManager(), and Initialize().
G4String G4MPImanager::init_file_name_ private
Definition at line 169 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 169 of file G4MPImanager.hh
Referenced by GetInitFileName(), and ParseArguments().
G4bool G4MPImanager::is_extra_worker_ private
Definition at line 144 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 144 of file G4MPImanager.hh
Referenced by BcastCommand(), DistributeSeeds(), Initialize(), IsExtraWorker(), and WaitBeamOn().
G4bool G4MPImanager::is_master_ private
Definition at line 142 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 142 of file G4MPImanager.hh
Referenced by BcastCommand(), BeamOn(), CheckThreadStatus(), ExecuteBeamOnThread(), Initialize(), IsMaster(), ParseArguments(), Print(), ShowSeeds(), ShowStatus(), and WaitBeamOn().
G4bool G4MPImanager::is_slave_ private
Definition at line 143 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 143 of file G4MPImanager.hh
Referenced by Initialize(), IsSlave(), ParseArguments(), ShowHelp(), and ~G4MPImanager().
G4String G4MPImanager::macro_file_name_ private
Definition at line 171 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 171 of file G4MPImanager.hh
Referenced by GetMacroFileName(), and ParseArguments().
G4double G4MPImanager::master_weight_ private
Definition at line 177 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 177 of file G4MPImanager.hh
Referenced by BeamOn(), GetMasterWeight(), and SetMasterWeight().
G4MPImessenger* G4MPImanager::messenger_ private
Definition at line 130 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 130 of file G4MPImanager.hh
Referenced by Initialize(), and ~G4MPImanager().
G4int G4MPImanager::nof_extra_workers_ private
Definition at line 178 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 178 of file G4MPImanager.hh
Referenced by Initialize(), SetExtraWorker(), and ~G4MPImanager().
MPI_Comm G4MPImanager::processing_comm_ private
Definition at line 152 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 152 of file G4MPImanager.hh
Referenced by GetProcessingComm(), Initialize(), and ~G4MPImanager().
MPI_Group G4MPImanager::processing_group_ private
Definition at line 159 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 159 of file G4MPImanager.hh
Referenced by Initialize(), and ~G4MPImanager().
G4bool G4MPImanager::qbatchmode_ private
Definition at line 170 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 170 of file G4MPImanager.hh
Referenced by ExecuteMacroFile(), IsBatchMode(), ParseArguments(), and WaitBeamOn().
G4bool G4MPImanager::qfcout_ private
Definition at line 164 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 164 of file G4MPImanager.hh
Referenced by ParseArguments(), Print(), and ~G4MPImanager().
G4bool G4MPImanager::qinitmacro_ private
Definition at line 168 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 168 of file G4MPImanager.hh
Referenced by IsInitMacro(), and ParseArguments().
G4int G4MPImanager::rank_ private
Definition at line 145 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 145 of file G4MPImanager.hh
Referenced by DistributeSeeds(), GetRank(), Initialize(), ParseArguments(), Print(), SetSeed(), ShowSeeds(), and UpdateStatus().
G4VMPIseedGenerator* G4MPImanager::seed_generator_ private
Definition at line 135 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 135 of file G4MPImanager.hh
Referenced by DistributeSeeds(), GetSeedGenerator(), and Initialize().
G4MPIsession* G4MPImanager::session_ private
Definition at line 131 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 131 of file G4MPImanager.hh
Referenced by GetMPIsession(), Initialize(), and ~G4MPImanager().
G4int G4MPImanager::size_ private
Definition at line 146 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 146 of file G4MPImanager.hh
Referenced by BcastCommand(), BeamOn(), CheckThreadStatus(), GetActiveSize(), Initialize(), ShowSeeds(), ShowStatus(), and WaitBeamOn().
G4MPIstatus* G4MPImanager::status_ private
Definition at line 137 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 137 of file G4MPImanager.hh
Referenced by BeamOn(), Initialize(), ShowStatus(), UpdateStatus(), and ~G4MPImanager().
pthread_t G4MPImanager::thread_id_ private
Definition at line 174 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 174 of file G4MPImanager.hh
Referenced by CheckThreadStatus(), ExecuteBeamOnThread(), ExecuteThreadCommand(), and JoinBeamOnThread().
G4int G4MPImanager::verbose_ private
Definition at line 139 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 139 of file G4MPImanager.hh
Referenced by BeamOn(), GetVerbose(), ParseArguments(), and SetVerbose().
MPI_Group G4MPImanager::world_group_ private
Definition at line 158 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 158 of file G4MPImanager.hh
Referenced by Initialize(), and ~G4MPImanager().
G4int G4MPImanager::world_size_ private
Definition at line 147 of file G4MPImanager.hh.
View newest version in sPHENIX GitHub at line 147 of file G4MPImanager.hh
Referenced by GetTotalSize(), and Initialize().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/include/G4MPImanager.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/MPI/source/src/G4MPImanager.cc