ECCE @ EIC Software: G4FissionLibrary Class Reference
G4FissionLibrary Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/include/G4FissionLibrary.hh>
Public Member Functions
G4FissionLibrary ()
~G4FissionLibrary ()
void Init (G4double A, G4double Z, G4int M, G4String &dirName, G4String &, G4ParticleDefinition *)
G4HadFinalState * ApplyYourself (const G4HadProjectile &theTrack)
G4ParticleHPFinalState * New ()
Public Member Functions inherited from G4ParticleHPFinalState
G4ParticleHPFinalState ()
virtual ~G4ParticleHPFinalState ()
void Init (G4double A, G4double Z, G4String &dirName, G4String &aFSType, G4ParticleDefinition *projectile)
G4bool HasXsec ()
G4bool HasFSData ()
G4bool HasAnyData ()
virtual G4double GetXsec (G4double)
virtual G4ParticleHPVector * GetXsec ()
void SetA_Z (G4double anA, G4double aZ, G4int aM=0)
G4double GetZ ()
G4double GetN ()
G4double GetA ()
G4int GetM ()
void SetAZMs (G4double anA, G4double aZ, G4int aM, G4ParticleHPDataUsed used)
void SetProjectile (G4ParticleDefinition *projectile)
Private Member Functions
void SampleMult (const G4HadProjectile &theTrack, G4int *nPrompt, G4int *gPrompt, G4double eKinetic)
G4ParticleHPFissionERelease * GetEnergyRelease ()
Private Attributes
G4fissionEvent * fe
G4int theIsotope
G4double targetMass
G4ParticleHPParticleYield theFinalStateNeutrons
G4ParticleHPEnergyDistribution thePromptNeutronEnDis
G4ParticleHPEnergyDistribution theDelayedNeutronEnDis
G4ParticleHPAngular theNeutronAngularDis
G4ParticleHPPhotonDist theFinalStatePhotons
G4ParticleHPFissionERelease theEnergyRelease
Additional Inherited Members
Protected Member Functions inherited from G4ParticleHPFinalState
void adjust_final_state (G4LorentzVector)
G4bool DoNotAdjustFinalState ()
Protected Attributes inherited from G4ParticleHPFinalState
G4bool hasXsec
G4bool hasFSData
G4bool hasAnyData
G4ParticleHPNames theNames
G4Cache< G4HadFinalState * > theResult
G4ParticleDefinition * theProjectile
G4double theBaseA
G4double theBaseZ
G4int theBaseM
G4int theNDLDataZ
G4int theNDLDataA
G4int theNDLDataM
Detailed Description
Definition at line 76 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 76 of file G4FissionLibrary.hh
Constructor & Destructor Documentation
G4FissionLibrary::G4FissionLibrary ()
Definition at line 66 of file G4FissionLibrary.cc.
View newest version in sPHENIX GitHub at line 66 of file G4FissionLibrary.cc
References fe, and G4ParticleHPFinalState::hasXsec.
Referenced by New().
G4FissionLibrary::~G4FissionLibrary ()
Definition at line 73 of file G4FissionLibrary.cc.
View newest version in sPHENIX GitHub at line 73 of file G4FissionLibrary.cc
Member Function Documentation
G4HadFinalState * G4FissionLibrary::ApplyYourself (const G4HadProjectile & theTrack) virtual
Reimplemented from G4ParticleHPFinalState.
Definition at line 141 of file G4FissionLibrary.cc.
View newest version in sPHENIX GitHub at line 141 of file G4FissionLibrary.cc
References G4HadFinalState::AddSecondary(), G4HadFinalState::Clear(), fe, G4Gamma::Gamma(), G4Cache< VALTYPE >::Get(), G4HadProjectile::Get4Momentum(), G4Nucleus::GetBiasedThermalNucleus(), G4HadProjectile::GetDefinition(), G4ReactionProduct::GetDefinition(), G4ParticleHPFissionERelease::GetFragmentKinetic(), G4HadProjectile::GetKineticEnergy(), G4HadProjectile::GetMaterial(), G4ReactionProduct::GetMomentum(), G4fissionEvent::getNeutronDircosu(), G4fissionEvent::getNeutronDircosv(), G4fissionEvent::getNeutronDircosw(), G4fissionEvent::getNeutronEnergy(), G4ParticleDefinition::GetPDGMass(), G4fissionEvent::getPhotonDircosu(), G4fissionEvent::getPhotonDircosv(), G4fissionEvent::getPhotonDircosw(), G4fissionEvent::getPhotonEnergy(), G4Material::GetTemperature(), G4ReactionProduct::GetTotalMomentum(), G4DynamicParticle::GetTotalMomentum(), it, G4ReactionProduct::Lorentz(), MeV, momentum, G4Neutron::Neutron(), G4Cache< VALTYPE >::Put(), SampleMult(), G4ReactionProduct::SetDefinition(), G4DynamicParticle::SetDefinition(), G4ReactionProduct::SetKineticEnergy(), G4DynamicParticle::SetKineticEnergy(), G4HadFinalState::SetLocalEnergyDeposit(), G4ReactionProduct::SetMomentum(), G4DynamicParticle::SetMomentum(), G4ParticleHPAngular::SetProjectileRP(), G4HadFinalState::SetStatusChange(), G4ParticleHPAngular::SetTarget(), stopAndKill, targetMass, theEnergyRelease, theNeutronAngularDis, G4ParticleHPFinalState::theResult, theTarget, and CLHEP::HepLorentzVector::vect().
G4ParticleHPFissionERelease* G4FissionLibrary::GetEnergyRelease () inline private
Definition at line 95 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 95 of file G4FissionLibrary.hh
References theEnergyRelease.
void G4FissionLibrary::Init (G4double A, G4double Z, G4int M, G4String & dirName, G4String & , G4ParticleDefinition *) virtual
Implements G4ParticleHPFinalState.
Definition at line 83 of file G4FissionLibrary.cc.
View newest version in sPHENIX GitHub at line 83 of file G4FissionLibrary.cc
References A(), INPUTHEPMC::filename, G4cout, G4endl, G4ParticleHPManager::GetDataStream(), G4ParticleHPManager::GetInstance(), G4ParticleHPNames::GetName(), G4ParticleHPDataUsed::GetName(), G4ParticleHPParticleYield::GetTargetMass(), G4ParticleHPFinalState::hasAnyData, G4ParticleHPFinalState::hasFSData, G4ParticleHPFinalState::hasXsec, in, G4ParticleHPFissionERelease::Init(), G4ParticleHPEnergyDistribution::Init(), G4ParticleHPAngular::Init(), G4ParticleHPPhotonDist::InitAngular(), G4ParticleHPParticleYield::InitDelayed(), G4ParticleHPPhotonDist::InitEnergies(), G4ParticleHPParticleYield::InitMean(), G4ParticleHPPhotonDist::InitMean(), G4ParticleHPParticleYield::InitPrompt(), targetMass, theDelayedNeutronEnDis, theEnergyRelease, theFinalStateNeutrons, theFinalStatePhotons, theIsotope, G4ParticleHPFinalState::theNames, theNeutronAngularDis, and thePromptNeutronEnDis.
G4ParticleHPFinalState * G4FissionLibrary::New () virtual
Implements G4ParticleHPFinalState.
Definition at line 76 of file G4FissionLibrary.cc.
View newest version in sPHENIX GitHub at line 76 of file G4FissionLibrary.cc
References G4FissionLibrary().
void G4FissionLibrary::SampleMult (const G4HadProjectile & theTrack, G4int * nPrompt, G4int * gPrompt, G4double eKinetic) private
Definition at line 228 of file G4FissionLibrary.cc.
View newest version in sPHENIX GitHub at line 228 of file G4FissionLibrary.cc
References fe, G4ParticleHPParticleYield::GetDelayed(), G4HadProjectile::GetGlobalTime(), G4ParticleHPParticleYield::GetMean(), G4fissionEvent::getNeutronNu(), G4fissionEvent::getPhotonNu(), G4ParticleHPParticleYield::GetPrompt(), second, theFinalStateNeutrons, theIsotope, and Acts::VectorHelpers::time().
Referenced by ApplyYourself().
Member Data Documentation
G4fissionEvent* G4FissionLibrary::fe private
Definition at line 90 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 90 of file G4FissionLibrary.hh
Referenced by ApplyYourself(), G4FissionLibrary(), and SampleMult().
G4double G4FissionLibrary::targetMass private
Definition at line 92 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 92 of file G4FissionLibrary.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPEnergyDistribution G4FissionLibrary::theDelayedNeutronEnDis private
Definition at line 100 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 100 of file G4FissionLibrary.hh
Referenced by Init().
G4ParticleHPFissionERelease G4FissionLibrary::theEnergyRelease private
Definition at line 104 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 104 of file G4FissionLibrary.hh
Referenced by ApplyYourself(), GetEnergyRelease(), and Init().
G4ParticleHPParticleYield G4FissionLibrary::theFinalStateNeutrons private
Definition at line 98 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 98 of file G4FissionLibrary.hh
Referenced by Init(), and SampleMult().
G4ParticleHPPhotonDist G4FissionLibrary::theFinalStatePhotons private
Definition at line 103 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 103 of file G4FissionLibrary.hh
Referenced by Init().
G4int G4FissionLibrary::theIsotope private
Definition at line 91 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 91 of file G4FissionLibrary.hh
Referenced by Init(), and SampleMult().
G4ParticleHPAngular G4FissionLibrary::theNeutronAngularDis private
Definition at line 101 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 101 of file G4FissionLibrary.hh
Referenced by ApplyYourself(), and Init().
G4ParticleHPEnergyDistribution G4FissionLibrary::thePromptNeutronEnDis private
Definition at line 99 of file G4FissionLibrary.hh.
View newest version in sPHENIX GitHub at line 99 of file G4FissionLibrary.hh
Referenced by Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/include/G4FissionLibrary.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/fission/src/G4FissionLibrary.cc