ECCE @ EIC Software: STCyclotronPhysicsList Class Reference
STCyclotronPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/include/STCyclotronPhysicsList.hh>
Public Member Functions
STCyclotronPhysicsList (STCyclotronDetectorConstruction *det)
virtual ~STCyclotronPhysicsList ()
void ConstructParticle ()
void ConstructProcess ()
void SetCuts ()
void SetCutForGamma (G4double)
void SetCutForElectron (G4double)
void SetCutForPositron (G4double)
void SetCutFoil (G4double cutProton, G4double cutElectron, G4double cutPositron, G4double cutGamma, G4double cutNeutron)
void SetCutTarget (G4double cutProton, G4double cutElectron, G4double cutPositron, G4double cutGamma, G4double cutNeutron)
Public Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList ()
virtual ~G4VModularPhysicsList ()
void RegisterPhysics (G4VPhysicsConstructor *)
const G4VPhysicsConstructor * GetPhysics (G4int index) const
const G4VPhysicsConstructor * GetPhysics (const G4String &name) const
const G4VPhysicsConstructor * GetPhysicsWithType (G4int physics_type) const
void ReplacePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4int type)
void RemovePhysics (const G4String &name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker () override
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
Private Attributes
G4String fEmName
G4VPhysicsConstructor * fEmPhysicsList
G4VPhysicsConstructor * fDecPhysicsList
G4VPhysicsConstructor * fHadPhysicsList
G4VPhysicsConstructor * fRaddecayList
G4double fThickness_target
G4double fThickness_foil
G4double fCutForGamma
G4double fCutForElectron
G4double fCutForPositron
G4double fCutTargetProton
G4double fCutTargetElectron
G4double fCutTargetPositron
G4double fCutTargetGamma
G4double fCutTargetNeutron
G4double fCutFoilProton
G4double fCutFoilElectron
G4double fCutFoilPositron
G4double fCutFoilGamma
G4double fCutFoilNeutron
STCyclotronDetectorConstruction * fDetector
Additional Inherited Members
Static Public Member Functions inherited from G4VModularPhysicsList
static const G4VMPLManager & GetSubInstanceManager ()
Protected Types inherited from G4VModularPhysicsList
typedef
G4VMPLData::G4PhysConstVectorData G4PhysConstVector
Protected Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList (const G4VModularPhysicsList &)
G4VModularPhysicsList & operator= (const G4VModularPhysicsList &)
Protected Attributes inherited from G4VModularPhysicsList
G4int verboseLevel
G4int g4vmplInstanceID
Static Protected Attributes inherited from G4VModularPhysicsList
static G4RUN_DLL G4VMPLManager G4VMPLsubInstanceManager
Detailed Description
Definition at line 42 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 42 of file STCyclotronPhysicsList.hh
Constructor & Destructor Documentation
STCyclotronPhysicsList::STCyclotronPhysicsList (STCyclotronDetectorConstruction * det)
Definition at line 63 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 63 of file STCyclotronPhysicsList.cc
References G4VUserPhysicsList::defaultCutValue, e, eV, fCutFoilElectron, fCutFoilGamma, fCutFoilNeutron, fCutFoilPositron, fCutFoilProton, fCutForElectron, fCutForGamma, fCutForPositron, fCutTargetElectron, fCutTargetGamma, fCutTargetNeutron, fCutTargetPositron, fCutTargetProton, fDecPhysicsList, fDetector, fEmName, fEmPhysicsList, fHadPhysicsList, fRaddecayList, fThickness_foil, fThickness_target, G4NuclideTable::GetInstance(), G4LossTableManager::Instance(), mm, second, G4NuclideTable::SetLevelTolerance(), and G4NuclideTable::SetThresholdOfHalfLife().
STCyclotronPhysicsList::~STCyclotronPhysicsList () virtual
Definition at line 127 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 127 of file STCyclotronPhysicsList.cc
References fDecPhysicsList, fEmPhysicsList, fHadPhysicsList, and fRaddecayList.
Member Function Documentation
void STCyclotronPhysicsList::ConstructParticle (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 138 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 138 of file STCyclotronPhysicsList.cc
References G4VPhysicsConstructor::ConstructParticle(), G4Deuteron::DeuteronDefinition(), G4Electron::ElectronDefinition(), fDecPhysicsList, G4Gamma::GammaDefinition(), G4Neutron::NeutronDefinition(), G4Positron::PositronDefinition(), and G4Proton::ProtonDefinition().
void STCyclotronPhysicsList::ConstructProcess (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 153 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 153 of file STCyclotronPhysicsList.cc
References G4VUserPhysicsList::AddTransportation(), G4VPhysicsConstructor::ConstructProcess(), fDecPhysicsList, fDetector, fEmPhysicsList, fHadPhysicsList, fRaddecayList, fThickness_foil, fThickness_target, STCyclotronDetectorConstruction::GetFoilThickness(), STCyclotronDetectorConstruction::GetTargetThickness(), mm, and SetCutTarget().
void STCyclotronPhysicsList::SetCutFoil (G4double cutProton, G4double cutElectron, G4double cutPositron, G4double cutGamma, G4double cutNeutron)
Definition at line 245 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 245 of file STCyclotronPhysicsList.cc
References fCutFoilElectron, fCutFoilGamma, fCutFoilNeutron, fCutFoilPositron, fCutFoilProton, G4ProductionCuts::GetIndex(), G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), mm, and G4ProductionCuts::SetProductionCut().
Referenced by SetCuts().
void STCyclotronPhysicsList::SetCutForElectron (G4double cut)
Definition at line 210 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 210 of file STCyclotronPhysicsList.cc
References G4Electron::Electron(), fCutForElectron, and G4VUserPhysicsList::SetParticleCuts().
void STCyclotronPhysicsList::SetCutForGamma (G4double cut)
Definition at line 204 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 204 of file STCyclotronPhysicsList.cc
References fCutForGamma, G4Gamma::Gamma(), and G4VUserPhysicsList::SetParticleCuts().
void STCyclotronPhysicsList::SetCutForPositron (G4double cut)
Definition at line 216 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 216 of file STCyclotronPhysicsList.cc
References fCutForPositron, G4Positron::Positron(), and G4VUserPhysicsList::SetParticleCuts().
void STCyclotronPhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 184 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 184 of file STCyclotronPhysicsList.cc
References G4VUserPhysicsList::defaultCutValue, G4VUserPhysicsList::DumpCutValuesTable(), fCutForElectron, fCutForGamma, fCutForPositron, fThickness_foil, fThickness_target, G4BestUnit, G4cout, G4endl, SetCutFoil(), SetCutTarget(), G4VUserPhysicsList::SetCutValue(), and G4VModularPhysicsList::verboseLevel.
void STCyclotronPhysicsList::SetCutTarget (G4double cutProton, G4double cutElectron, G4double cutPositron, G4double cutGamma, G4double cutNeutron)
Definition at line 222 of file STCyclotronPhysicsList.cc.
View newest version in sPHENIX GitHub at line 222 of file STCyclotronPhysicsList.cc
References fCutTargetElectron, fCutTargetGamma, fCutTargetNeutron, fCutTargetPositron, fCutTargetProton, G4ProductionCuts::GetIndex(), G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), mm, and G4ProductionCuts::SetProductionCut().
Referenced by ConstructProcess(), and SetCuts().
Member Data Documentation
G4double STCyclotronPhysicsList::fCutFoilElectron private
Definition at line 83 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 83 of file STCyclotronPhysicsList.hh
Referenced by SetCutFoil(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutFoilGamma private
Definition at line 85 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 85 of file STCyclotronPhysicsList.hh
Referenced by SetCutFoil(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutFoilNeutron private
Definition at line 86 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 86 of file STCyclotronPhysicsList.hh
Referenced by SetCutFoil(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutFoilPositron private
Definition at line 84 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 84 of file STCyclotronPhysicsList.hh
Referenced by SetCutFoil(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutFoilProton private
Definition at line 82 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 82 of file STCyclotronPhysicsList.hh
Referenced by SetCutFoil(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutForElectron private
Definition at line 73 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 73 of file STCyclotronPhysicsList.hh
Referenced by SetCutForElectron(), SetCuts(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutForGamma private
Definition at line 72 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 72 of file STCyclotronPhysicsList.hh
Referenced by SetCutForGamma(), SetCuts(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutForPositron private
Definition at line 74 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 74 of file STCyclotronPhysicsList.hh
Referenced by SetCutForPositron(), SetCuts(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutTargetElectron private
Definition at line 77 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 77 of file STCyclotronPhysicsList.hh
Referenced by SetCutTarget(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutTargetGamma private
Definition at line 79 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 79 of file STCyclotronPhysicsList.hh
Referenced by SetCutTarget(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutTargetNeutron private
Definition at line 80 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 80 of file STCyclotronPhysicsList.hh
Referenced by SetCutTarget(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutTargetPositron private
Definition at line 78 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 78 of file STCyclotronPhysicsList.hh
Referenced by SetCutTarget(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fCutTargetProton private
Definition at line 76 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 76 of file STCyclotronPhysicsList.hh
Referenced by SetCutTarget(), and STCyclotronPhysicsList().
G4VPhysicsConstructor* STCyclotronPhysicsList::fDecPhysicsList private
Definition at line 65 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 65 of file STCyclotronPhysicsList.hh
Referenced by ConstructParticle(), ConstructProcess(), STCyclotronPhysicsList(), and ~STCyclotronPhysicsList().
STCyclotronDetectorConstruction* STCyclotronPhysicsList::fDetector private
Definition at line 88 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 88 of file STCyclotronPhysicsList.hh
Referenced by ConstructProcess(), and STCyclotronPhysicsList().
G4String STCyclotronPhysicsList::fEmName private
Definition at line 63 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 63 of file STCyclotronPhysicsList.hh
Referenced by STCyclotronPhysicsList().
G4VPhysicsConstructor* STCyclotronPhysicsList::fEmPhysicsList private
Definition at line 64 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 64 of file STCyclotronPhysicsList.hh
Referenced by ConstructProcess(), STCyclotronPhysicsList(), and ~STCyclotronPhysicsList().
G4VPhysicsConstructor* STCyclotronPhysicsList::fHadPhysicsList private
Definition at line 66 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 66 of file STCyclotronPhysicsList.hh
Referenced by ConstructProcess(), STCyclotronPhysicsList(), and ~STCyclotronPhysicsList().
G4VPhysicsConstructor* STCyclotronPhysicsList::fRaddecayList private
Definition at line 67 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 67 of file STCyclotronPhysicsList.hh
Referenced by ConstructProcess(), STCyclotronPhysicsList(), and ~STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fThickness_foil private
Definition at line 70 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 70 of file STCyclotronPhysicsList.hh
Referenced by ConstructProcess(), SetCuts(), and STCyclotronPhysicsList().
G4double STCyclotronPhysicsList::fThickness_target private
Definition at line 69 of file STCyclotronPhysicsList.hh.
View newest version in sPHENIX GitHub at line 69 of file STCyclotronPhysicsList.hh
Referenced by ConstructProcess(), SetCuts(), and STCyclotronPhysicsList().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/include/STCyclotronPhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/src/STCyclotronPhysicsList.cc