ECCE @ EIC Software: G4QMDParticipant Class Reference
G4QMDParticipant Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDParticipant.hh>
Public Member Functions
G4QMDParticipant (const G4ParticleDefinition *, G4ThreeVector, G4ThreeVector)
~G4QMDParticipant ()
void SetDefinition (const G4ParticleDefinition *pd)
const G4ParticleDefinition * GetDefinition ()
void SetPosition (G4ThreeVector r)
G4ThreeVector GetPosition ()
void SetMomentum (G4ThreeVector p)
G4ThreeVector GetMomentum ()
G4double GetMass ()
G4LorentzVector Get4Momentum ()
G4double GetKineticEnergy ()
G4int GetBaryonNumber ()
G4int GetNuc ()
G4int GetChargeInUnitOfEplus ()
void UnsetInitialMark ()
void UnsetHitMark ()
G4bool IsThisHit ()
void SetHitMark ()
void SetProjectile ()
void SetTarget ()
G4bool IsThisProjectile ()
G4bool IsThisTarget ()
Private Attributes
const G4ParticleDefinition * definition
G4ThreeVector momentum
G4ThreeVector position
G4bool projectile
G4bool target
G4bool hit
Detailed Description
Definition at line 48 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 48 of file G4QMDParticipant.hh
Constructor & Destructor Documentation
G4QMDParticipant::G4QMDParticipant (const G4ParticleDefinition * pd, G4ThreeVector p, G4ThreeVector r)
Definition at line 30 of file G4QMDParticipant.cc.
View newest version in sPHENIX GitHub at line 30 of file G4QMDParticipant.cc
G4QMDParticipant::~G4QMDParticipant ()
Definition at line 43 of file G4QMDParticipant.cc.
View newest version in sPHENIX GitHub at line 43 of file G4QMDParticipant.cc
Member Function Documentation
G4LorentzVector G4QMDParticipant::Get4Momentum ()
Definition at line 50 of file G4QMDParticipant.cc.
View newest version in sPHENIX GitHub at line 50 of file G4QMDParticipant.cc
References definition, G4Pow::GetInstance(), G4ParticleDefinition::GetPDGMass(), GeV, and momentum.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDMeanField::Cal2BodyQuantities(), G4QMDCollision::CalFinalStateOfTheBinaryCollision(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDMeanField::CalGraduate(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), and GetKineticEnergy().
G4int G4QMDParticipant::GetBaryonNumber () inline
Definition at line 70 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QMDParticipant.hh
References definition, and G4ParticleDefinition::GetBaryonNumber().
Referenced by G4QMDMeanField::Cal2BodyQuantities(), and G4QMDMeanField::DoClusterJudgment().
G4int G4QMDParticipant::GetChargeInUnitOfEplus () inline
Definition at line 73 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QMDParticipant.hh
References definition, CLHEP::eplus, G4ParticleDefinition::GetPDGCharge(), and int().
Referenced by G4QMDMeanField::Cal2BodyQuantities(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDMeanField::CalGraduate(), G4QMDMeanField::calPauliBlockingFactor(), G4QMDMeanField::GetPotential(), and G4QMDMeanField::GetTotalPotential().
const G4ParticleDefinition* G4QMDParticipant::GetDefinition () inline
Definition at line 56 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 56 of file G4QMDParticipant.hh
References definition.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDCollision::CalFinalStateOfTheBinaryCollision(), and G4QMDCollision::CalKinematicsOfBinaryCollisions().
G4double G4QMDParticipant::GetKineticEnergy () inline
Definition at line 68 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 68 of file G4QMDParticipant.hh
References CLHEP::HepLorentzVector::e(), Get4Momentum(), and GetMass().
G4double G4QMDParticipant::GetMass () inline
Definition at line 64 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QMDParticipant.hh
References definition, G4ParticleDefinition::GetPDGMass(), and CLHEP::GeV.
Referenced by G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), and GetKineticEnergy().
G4ThreeVector G4QMDParticipant::GetMomentum (void) inline
Definition at line 62 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 62 of file G4QMDParticipant.hh
References momentum.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), and G4QMDMeanField::DoPropagation().
G4int G4QMDParticipant::GetNuc () inline
Definition at line 71 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 71 of file G4QMDParticipant.hh
References definition, and G4ParticleDefinition::GetBaryonNumber().
Referenced by G4QMDMeanField::CalGraduate(), G4QMDMeanField::calPauliBlockingFactor(), G4QMDMeanField::GetPotential(), G4QMDMeanField::GetTotalPotential(), and G4QMDMeanField::IsPauliBlocked().
G4ThreeVector G4QMDParticipant::GetPosition (void) inline
Definition at line 59 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 59 of file G4QMDParticipant.hh
References position.
Referenced by G4QMDReaction::ApplyYourself(), G4QMDMeanField::Cal2BodyQuantities(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDCollision::CalFinalStateOfTheBinaryCollision(), G4QMDMeanField::CalGraduate(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), and G4QMDMeanField::DoPropagation().
G4bool G4QMDParticipant::IsThisHit () inline
Definition at line 77 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QMDParticipant.hh
References hit.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions().
G4bool G4QMDParticipant::IsThisProjectile () inline
Definition at line 82 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 82 of file G4QMDParticipant.hh
References projectile.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions().
G4bool G4QMDParticipant::IsThisTarget () inline
Definition at line 83 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QMDParticipant.hh
References target.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions().
void G4QMDParticipant::SetDefinition (const G4ParticleDefinition * pd) inline
Definition at line 55 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 55 of file G4QMDParticipant.hh
References definition.
Referenced by G4QMDCollision::CalFinalStateOfTheBinaryCollision(), and G4QMDCollision::CalKinematicsOfBinaryCollisions().
void G4QMDParticipant::SetHitMark () inline
Definition at line 78 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QMDParticipant.hh
References hit.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions().
void G4QMDParticipant::SetMomentum (G4ThreeVector p) inline
Definition at line 61 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 61 of file G4QMDParticipant.hh
References momentum.
Referenced by G4QMDCollision::CalFinalStateOfTheBinaryCollision(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), and G4QMDMeanField::DoPropagation().
void G4QMDParticipant::SetPosition (G4ThreeVector r) inline
Definition at line 58 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 58 of file G4QMDParticipant.hh
References r.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions(), and G4QMDMeanField::DoPropagation().
void G4QMDParticipant::SetProjectile () inline
Definition at line 80 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 80 of file G4QMDParticipant.hh
References projectile.
Referenced by G4QMDReaction::ApplyYourself().
void G4QMDParticipant::SetTarget () inline
Definition at line 81 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 81 of file G4QMDParticipant.hh
Referenced by G4QMDReaction::ApplyYourself().
void G4QMDParticipant::UnsetHitMark () inline
Definition at line 76 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QMDParticipant.hh
References hit.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions().
void G4QMDParticipant::UnsetInitialMark () inline
Definition at line 75 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QMDParticipant.hh
References projectile.
Referenced by G4QMDCollision::CalKinematicsOfBinaryCollisions().
Member Data Documentation
const G4ParticleDefinition* G4QMDParticipant::definition private
Definition at line 86 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 86 of file G4QMDParticipant.hh
Referenced by Get4Momentum(), GetBaryonNumber(), GetChargeInUnitOfEplus(), GetDefinition(), GetMass(), GetNuc(), and SetDefinition().
G4bool G4QMDParticipant::hit private
Definition at line 92 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 92 of file G4QMDParticipant.hh
Referenced by IsThisHit(), SetHitMark(), and UnsetHitMark().
G4ThreeVector G4QMDParticipant::momentum private
Definition at line 87 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 87 of file G4QMDParticipant.hh
Referenced by Get4Momentum(), GetMomentum(), and SetMomentum().
G4ThreeVector G4QMDParticipant::position private
Definition at line 88 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 88 of file G4QMDParticipant.hh
Referenced by GetPosition().
G4bool G4QMDParticipant::projectile private
Definition at line 90 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 90 of file G4QMDParticipant.hh
Referenced by IsThisProjectile(), SetProjectile(), and UnsetInitialMark().
G4bool G4QMDParticipant::target private
Definition at line 91 of file G4QMDParticipant.hh.
View newest version in sPHENIX GitHub at line 91 of file G4QMDParticipant.hh
Referenced by IsThisTarget().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDParticipant.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/src/G4QMDParticipant.cc