ECCE @ EIC Software: G4IonYangFluctuationModel Class Reference
G4IonYangFluctuationModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4IonYangFluctuationModel.hh>
Public Member Functions
G4IonYangFluctuationModel (const G4String &name)
~G4IonYangFluctuationModel ()
G4double TheValue (const G4DynamicParticle *particle, const G4Material *material)
G4double TheValue (const G4ParticleDefinition *aParticle, const G4Material *material, G4double kineticEnergy)
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle, const G4Material *material) const
G4double HighEnergyLimit (const G4ParticleDefinition *aParticle) const
G4double LowEnergyLimit (const G4ParticleDefinition *aParticle) const
G4bool IsInCharge (const G4DynamicParticle *particle, const G4Material *material) const
G4bool IsInCharge (const G4ParticleDefinition *aParticle, const G4Material *material) const
Public Member Functions inherited from G4VLowEnergyModel
G4VLowEnergyModel (const G4String &name)
virtual ~G4VLowEnergyModel ()
Private Member Functions
G4double YangFluctuationModel (const G4Material *material, G4double kineticEnergy, G4double particleMass, G4double charge) const
Detailed Description
Definition at line 56 of file G4IonYangFluctuationModel.hh.
View newest version in sPHENIX GitHub at line 56 of file G4IonYangFluctuationModel.hh
Constructor & Destructor Documentation
G4IonYangFluctuationModel::G4IonYangFluctuationModel (const G4String & name)
Definition at line 68 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 68 of file G4IonYangFluctuationModel.cc
G4IonYangFluctuationModel::~G4IonYangFluctuationModel ()
Definition at line 74 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 74 of file G4IonYangFluctuationModel.cc
Member Function Documentation
G4double G4IonYangFluctuationModel::HighEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 107 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 107 of file G4IonYangFluctuationModel.cc
References TeV.
G4double G4IonYangFluctuationModel::HighEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 123 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 123 of file G4IonYangFluctuationModel.cc
References TeV.
G4bool G4IonYangFluctuationModel::IsInCharge (const G4DynamicParticle * particle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 138 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 138 of file G4IonYangFluctuationModel.cc
References true.
G4bool G4IonYangFluctuationModel::IsInCharge (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 146 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 146 of file G4IonYangFluctuationModel.cc
References true.
G4double G4IonYangFluctuationModel::LowEnergyLimit (const G4ParticleDefinition * aParticle, const G4Material * material) const virtual
Implements G4VLowEnergyModel.
Definition at line 115 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 115 of file G4IonYangFluctuationModel.cc
G4double G4IonYangFluctuationModel::LowEnergyLimit (const G4ParticleDefinition * aParticle) const virtual
Implements G4VLowEnergyModel.
Definition at line 130 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 130 of file G4IonYangFluctuationModel.cc
G4double G4IonYangFluctuationModel::TheValue (const G4DynamicParticle * particle, const G4Material * material) virtual
Implements G4VLowEnergyModel.
Definition at line 79 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 79 of file G4IonYangFluctuationModel.cc
References charge, energy, eplus, G4DynamicParticle::GetCharge(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), mass, and YangFluctuationModel().
G4double G4IonYangFluctuationModel::TheValue (const G4ParticleDefinition * aParticle, const G4Material * material, G4double kineticEnergy) virtual
Implements G4VLowEnergyModel.
Definition at line 93 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 93 of file G4IonYangFluctuationModel.cc
References charge, eplus, G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), mass, and YangFluctuationModel().
G4double G4IonYangFluctuationModel::YangFluctuationModel (const G4Material * material, G4double kineticEnergy, G4double particleMass, G4double charge) const private
Definition at line 154 of file G4IonYangFluctuationModel.cc.
View newest version in sPHENIX GitHub at line 154 of file G4IonYangFluctuationModel.cc
References source.hepunit::amu_c2, b, energy, G4Exp(), G4Material::GetElectronDensity(), G4Material::GetNumberOfElements(), G4Material::GetState(), G4Material::GetTotNbOfAtomsPerVolume(), kStateGas, MeV, and x.
Referenced by TheValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4IonYangFluctuationModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4IonYangFluctuationModel.cc