ECCE @ EIC Software: G4EllipticalCone Class Reference
G4EllipticalCone Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4EllipticalCone.hh>
Public Member Functions
G4EllipticalCone (const G4String &pName, G4double pxSemiAxis, G4double pySemiAxis, G4double zMax, G4double pzTopCut)
virtual ~G4EllipticalCone ()
G4double GetSemiAxisMin () const
G4double GetSemiAxisMax () const
G4double GetSemiAxisX () const
G4double GetSemiAxisY () const
G4double GetZMax () const
G4double GetZTopCut () const
void SetSemiAxis (G4double x, G4double y, G4double z)
void SetZCut (G4double newzTopCut)
G4double GetCubicVolume ()
G4double GetSurfaceArea ()
void BoundingLimits (G4ThreeVector &pMin, G4ThreeVector &pMax) const
G4bool CalculateExtent (const EAxis pAxis, const G4VoxelLimits &pVoxelLimit, const G4AffineTransform &pTransform, G4double &pMin, G4double &pMax) const
EInside Inside (const G4ThreeVector &p) const
G4ThreeVector SurfaceNormal (const G4ThreeVector &p) const
G4double DistanceToIn (const G4ThreeVector &p, const G4ThreeVector &v) const
G4double DistanceToIn (const G4ThreeVector &p) const
G4double DistanceToOut (const G4ThreeVector &p, const G4ThreeVector &v, const G4bool calcNorm=false, G4bool *validNorm=nullptr, G4ThreeVector *n=nullptr) const
G4double DistanceToOut (const G4ThreeVector &p) const
G4GeometryType GetEntityType () const
G4VSolid * Clone () const
G4ThreeVector GetPointOnSurface () const
std::ostream & StreamInfo (std::ostream &os) const
G4Polyhedron * GetPolyhedron () const
void DescribeYourselfTo (G4VGraphicsScene &scene) const
G4VisExtent GetExtent () const
G4Polyhedron * CreatePolyhedron () const
G4EllipticalCone (__void__ &)
G4EllipticalCone (const G4EllipticalCone &rhs)
G4EllipticalCone & operator= (const G4EllipticalCone &rhs)
Public Member Functions inherited from G4VSolid
G4VSolid (const G4String &name)
virtual ~G4VSolid ()
G4bool operator== (const G4VSolid &s) const
G4String GetName () const
void SetName (const G4String &name)
G4double GetTolerance () const
virtual void ComputeDimensions (G4VPVParameterisation *p, const G4int n, const G4VPhysicalVolume *pRep)
void DumpInfo () const
virtual const G4VSolid * GetConstituentSolid (G4int no) const
virtual G4VSolid * GetConstituentSolid (G4int no)
virtual const G4DisplacedSolid * GetDisplacedSolidPtr () const
virtual G4DisplacedSolid * GetDisplacedSolidPtr ()
G4VSolid (__void__ &)
G4VSolid (const G4VSolid &rhs)
G4VSolid & operator= (const G4VSolid &rhs)
G4double EstimateCubicVolume (G4int nStat, G4double epsilon) const
G4double EstimateSurfaceArea (G4int nStat, G4double ell) const
Protected Attributes
G4bool fRebuildPolyhedron = false
G4Polyhedron * fpPolyhedron = nullptr
Protected Attributes inherited from G4VSolid
G4double kCarTolerance
Private Member Functions
G4ThreeVector ApproxSurfaceNormal (const G4ThreeVector &p) const
Private Attributes
G4double halfCarTol
G4double fCubicVolume = 0.0
G4double fSurfaceArea = 0.0
G4double xSemiAxis
G4double ySemiAxis
G4double zheight
G4double zTopCut
G4double cosAxisMin
G4double invXX
G4double invYY
Additional Inherited Members
Protected Member Functions inherited from G4VSolid
void CalculateClippedPolygonExtent (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipCrossSection (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipBetweenSections (G4ThreeVectorList *pVertices, const G4int pSectionIndex, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis, G4double &pMin, G4double &pMax) const
void ClipPolygon (G4ThreeVectorList &pPolygon, const G4VoxelLimits &pVoxelLimit, const EAxis pAxis) const
Detailed Description
Definition at line 87 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 87 of file G4EllipticalCone.hh
Constructor & Destructor Documentation
G4EllipticalCone::G4EllipticalCone (const G4String & pName, G4double pxSemiAxis, G4double pySemiAxis, G4double zMax, G4double pzTopCut)
Definition at line 72 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 72 of file G4EllipticalCone.cc
References FatalErrorInArgument, G4Exception(), G4VSolid::GetName(), halfCarTol, G4VSolid::kCarTolerance, message(), SetSemiAxis(), and SetZCut().
Referenced by Clone().
G4EllipticalCone::~G4EllipticalCone () virtual
Definition at line 122 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 122 of file G4EllipticalCone.cc
References fpPolyhedron.
G4EllipticalCone::G4EllipticalCone (__void__ & a)
Definition at line 111 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 111 of file G4EllipticalCone.cc
G4EllipticalCone::G4EllipticalCone (const G4EllipticalCone & rhs)
Definition at line 131 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 131 of file G4EllipticalCone.cc
Member Function Documentation
G4ThreeVector G4EllipticalCone::ApproxSurfaceNormal (const G4ThreeVector & p) const private
Definition at line 330 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 330 of file G4EllipticalCone.cc
References kdfinder::abs(), cosAxisMin, dz, halfCarTol, invXX, invYY, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), zheight, and zTopCut.
Referenced by SurfaceNormal().
void G4EllipticalCone::BoundingLimits (G4ThreeVector & pMin, G4ThreeVector & pMax) const virtual
Reimplemented from G4VSolid.
Definition at line 172 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 172 of file G4EllipticalCone.cc
References G4VSolid::DumpInfo(), G4Exception(), G4VSolid::GetName(), GetSemiAxisX(), GetSemiAxisY(), GetZMax(), GetZTopCut(), JustWarning, message(), pMax, CLHEP::Hep3Vector::set(), CLHEP::Hep3Vector::x(), xmax, CLHEP::Hep3Vector::y(), ymax, and CLHEP::Hep3Vector::z().
Referenced by CalculateExtent(), and GetExtent().
G4bool G4EllipticalCone::CalculateExtent (const EAxis pAxis, const G4VoxelLimits & pVoxelLimit, const G4AffineTransform & pTransform, G4double & pMin, G4double & pMax) const virtual
Implements G4VSolid.
Definition at line 202 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 202 of file G4EllipticalCone.cc
References G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), BoundingLimits(), G4BoundingEnvelope::CalculateExtent(), GetSemiAxisX(), GetSemiAxisY(), GetZMax(), k, pMax, twopi, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4VSolid * G4EllipticalCone::Clone () const virtual
Reimplemented from G4VSolid.
Definition at line 809 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 809 of file G4EllipticalCone.cc
References G4EllipticalCone().
G4Polyhedron * G4EllipticalCone::CreatePolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 973 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 973 of file G4EllipticalCone.cc
References xSemiAxis, ySemiAxis, zheight, and zTopCut.
Referenced by GetPolyhedron().
void G4EllipticalCone::DescribeYourselfTo (G4VGraphicsScene & scene) const virtual
Implements G4VSolid.
Definition at line 957 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 957 of file G4EllipticalCone.cc
References G4VGraphicsScene::AddSolid().
G4double G4EllipticalCone::DistanceToIn (const G4ThreeVector & p, const G4ThreeVector & v) const virtual
Implements G4VSolid.
Definition at line 346 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 346 of file G4EllipticalCone.cc
References A(), B(), C(), halfCarTol, kInfinity, G4InuclParticleNames::lambda, sqr(), v, CLHEP::Hep3Vector::x(), xSemiAxis, CLHEP::Hep3Vector::y(), ySemiAxis, CLHEP::Hep3Vector::z(), zheight, and zTopCut.
G4double G4EllipticalCone::DistanceToIn (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 595 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 595 of file G4EllipticalCone.cc
References kdfinder::abs(), cosAxisMin, dz, invXX, invYY, max, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), zheight, and zTopCut.
G4double G4EllipticalCone::DistanceToOut (const G4ThreeVector & p, const G4ThreeVector & v, const G4bool calcNorm = false, G4bool * validNorm = nullptr, G4ThreeVector * n = nullptr) const virtual
Implements G4VSolid.
Definition at line 609 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 609 of file G4EllipticalCone.cc
References A(), B(), C(), CLHEP::Hep3Vector::dot(), G4VSolid::DumpInfo(), G4endl, G4Exception(), halfCarTol, JustWarning, kInfinity, G4InuclParticleNames::lambda, CLHEP::Hep3Vector::mag(), message(), mm, sqr(), surface(), v, CLHEP::Hep3Vector::x(), xSemiAxis, CLHEP::Hep3Vector::y(), ySemiAxis, CLHEP::Hep3Vector::z(), zheight, and zTopCut.
G4double G4EllipticalCone::DistanceToOut (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 771 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 771 of file G4EllipticalCone.cc
References kdfinder::abs(), cosAxisMin, G4VSolid::DumpInfo(), dz, G4Exception(), G4VSolid::GetName(), Inside(), invXX, invYY, JustWarning, kOutside, message(), min, mm, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), zheight, and zTopCut.
G4double G4EllipticalCone::GetCubicVolume () virtual
Reimplemented from G4VSolid.
Definition at line 920 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 920 of file G4EllipticalCone.cc
References fCubicVolume, CLHEP::pi, xSemiAxis, ySemiAxis, zheight, and zTopCut.
G4GeometryType G4EllipticalCone::GetEntityType () const virtual
Implements G4VSolid.
Definition at line 800 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 800 of file G4EllipticalCone.cc
G4VisExtent G4EllipticalCone::GetExtent () const virtual
Reimplemented from G4VSolid.
Definition at line 962 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 962 of file G4EllipticalCone.cc
References BoundingLimits(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4ThreeVector G4EllipticalCone::GetPointOnSurface () const virtual
Reimplemented from G4VSolid.
Definition at line 841 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 841 of file G4EllipticalCone.cc
References a, b, bb, E, G4GeomTools::EllipticConeLateralArea(), F, G, G4RandomPointInEllipse(), G4RandomRadiusInRing(), G4UniformRand, hh, k, max, phi, pi, Acts::IntegrationTest::R, G4InuclParticleNames::s0, CLHEP::Hep3Vector::set(), CLHEP::twopi, CLHEP::Hep2Vector::x(), x, xSemiAxis, xx, CLHEP::Hep2Vector::y(), y, ySemiAxis, zheight, and zTopCut.
G4Polyhedron * G4EllipticalCone::GetPolyhedron () const virtual
Reimplemented from G4VSolid.
Definition at line 978 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 978 of file G4EllipticalCone.cc
References CreatePolyhedron(), fpPolyhedron, fRebuildPolyhedron, HepPolyhedron::GetNumberOfRotationSteps(), G4Polyhedron::GetNumberOfRotationStepsAtTimeOfCreation(), and G4TemplateAutoLock< _Mutex_t >::unlock().
G4double G4EllipticalCone::GetSemiAxisMax () const inline
Referenced by export_G4EllipticalCone().
G4double G4EllipticalCone::GetSemiAxisMin () const inline
G4double G4EllipticalCone::GetSemiAxisX () const inline
Referenced by BoundingLimits(), CalculateExtent(), PHG4GDMLWriteSolids::ElconeWrite(), and G4GDMLWriteSolids::ElconeWrite().
G4double G4EllipticalCone::GetSemiAxisY () const inline
Referenced by BoundingLimits(), CalculateExtent(), PHG4GDMLWriteSolids::ElconeWrite(), and G4GDMLWriteSolids::ElconeWrite().
G4double G4EllipticalCone::GetSurfaceArea () virtual
Reimplemented from G4VSolid.
Definition at line 938 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 938 of file G4EllipticalCone.cc
References G4GeomTools::EllipticConeLateralArea(), fSurfaceArea, CLHEP::pi, G4InuclParticleNames::s0, xSemiAxis, ySemiAxis, zheight, and zTopCut.
G4double G4EllipticalCone::GetZMax () const inline
Referenced by BoundingLimits(), CalculateExtent(), PHG4GDMLWriteSolids::ElconeWrite(), and G4GDMLWriteSolids::ElconeWrite().
G4double G4EllipticalCone::GetZTopCut () const inline
Referenced by BoundingLimits(), PHG4GDMLWriteSolids::ElconeWrite(), G4GDMLWriteSolids::ElconeWrite(), and export_G4EllipticalCone().
EInside G4EllipticalCone::Inside (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 262 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 262 of file G4EllipticalCone.cc
References kdfinder::abs(), cosAxisMin, dz, halfCarTol, invXX, invYY, kInside, kOutside, kSurface, max, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), zheight, and zTopCut.
Referenced by DistanceToOut().
G4EllipticalCone & G4EllipticalCone::operator= (const G4EllipticalCone & rhs)
Definition at line 144 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 144 of file G4EllipticalCone.cc
References cosAxisMin, fCubicVolume, fpPolyhedron, fRebuildPolyhedron, fSurfaceArea, halfCarTol, invXX, invYY, G4VSolid::operator=(), xSemiAxis, ySemiAxis, zheight, and zTopCut.
void G4EllipticalCone::SetSemiAxis (G4double x, G4double y, G4double z) inline
Referenced by export_G4EllipticalCone(), and G4EllipticalCone().
void G4EllipticalCone::SetZCut (G4double newzTopCut) inline
Referenced by export_G4EllipticalCone(), and G4EllipticalCone().
std::ostream & G4EllipticalCone::StreamInfo (std::ostream & os) const virtual
Implements G4VSolid.
Definition at line 818 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 818 of file G4EllipticalCone.cc
References G4VSolid::GetName(), mm, xSemiAxis, ySemiAxis, zheight, and zTopCut.
G4ThreeVector G4EllipticalCone::SurfaceNormal (const G4ThreeVector & p) const virtual
Implements G4VSolid.
Definition at line 277 of file G4EllipticalCone.cc.
View newest version in sPHENIX GitHub at line 277 of file G4EllipticalCone.cc
References kdfinder::abs(), ApproxSurfaceNormal(), cosAxisMin, G4VSolid::DumpInfo(), dz, G4cout, G4endl, G4Exception(), G4VSolid::GetName(), halfCarTol, invXX, invYY, JustWarning, CLHEP::Hep3Vector::mag(), message(), mm, norm, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), CLHEP::Hep3Vector::z(), zheight, and zTopCut.
Member Data Documentation
G4double G4EllipticalCone::cosAxisMin private
Definition at line 182 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 182 of file G4EllipticalCone.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4EllipticalCone::fCubicVolume = 0.0 private
Definition at line 179 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 179 of file G4EllipticalCone.hh
Referenced by GetCubicVolume(), and operator=().
G4Polyhedron* G4EllipticalCone::fpPolyhedron = nullptr mutable protected
Definition at line 168 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 168 of file G4EllipticalCone.hh
Referenced by GetPolyhedron(), operator=(), and ~G4EllipticalCone().
G4bool G4EllipticalCone::fRebuildPolyhedron = false mutable protected
Definition at line 167 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 167 of file G4EllipticalCone.hh
Referenced by GetPolyhedron(), and operator=().
G4double G4EllipticalCone::fSurfaceArea = 0.0 private
Definition at line 180 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 180 of file G4EllipticalCone.hh
Referenced by GetSurfaceArea(), and operator=().
G4double G4EllipticalCone::halfCarTol private
Definition at line 178 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 178 of file G4EllipticalCone.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), G4EllipticalCone(), Inside(), operator=(), and SurfaceNormal().
G4double G4EllipticalCone::invXX private
Definition at line 182 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 182 of file G4EllipticalCone.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4EllipticalCone::invYY private
Definition at line 182 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 182 of file G4EllipticalCone.hh
Referenced by ApproxSurfaceNormal(), DistanceToIn(), DistanceToOut(), Inside(), operator=(), and SurfaceNormal().
G4double G4EllipticalCone::xSemiAxis private
Definition at line 181 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 181 of file G4EllipticalCone.hh
Referenced by CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), operator=(), and StreamInfo().
G4double G4EllipticalCone::ySemiAxis private
Definition at line 181 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 181 of file G4EllipticalCone.hh
Referenced by CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), operator=(), and StreamInfo().
G4double G4EllipticalCone::zheight private
Definition at line 181 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 181 of file G4EllipticalCone.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
G4double G4EllipticalCone::zTopCut private
Definition at line 181 of file G4EllipticalCone.hh.
View newest version in sPHENIX GitHub at line 181 of file G4EllipticalCone.hh
Referenced by ApproxSurfaceNormal(), CreatePolyhedron(), DistanceToIn(), DistanceToOut(), GetCubicVolume(), GetPointOnSurface(), GetSurfaceArea(), Inside(), operator=(), StreamInfo(), and SurfaceNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/include/G4EllipticalCone.hh
geant4/tree/geant4-10.6-release/source/geometry/solids/specific/src/G4EllipticalCone.cc