ECCE @ EIC Software: HEPREP::HepRepType Class Reference
HEPREP::HepRepType Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepType.h>
Public Member Functions
virtual ~HepRepType ()
Destructor.
virtual void addType (HepRepType *type)=0
virtual std::string getName ()=0
virtual std::string getFullName ()=0
virtual std::string getDescription ()=0
virtual void setDescription (std::string description)=0
virtual std::string getInfoURL ()=0
virtual void setInfoURL (std::string infoURL)=0
virtual HepRepType * getSuperType ()=0
virtual std::vector< HepRepType * > getTypeList ()=0
virtual HepRepType * copy (HepRepType *parent)=0
Public Member Functions inherited from HEPREP::HepRepDefinition
virtual ~HepRepDefinition ()
Destructor.
virtual void addAttDef (std::string name, std::string desc, std::string category, std::string extra)=0
virtual void addAttDef (HepRepAttDef *attDef)=0
virtual HepRepAttDef * getAttDef (std::string name)=0
virtual std::set< HepRepAttDef * > getAttDefsFromNode ()=0
virtual HepRepAttDef * getAttDefFromNode (std::string lowerCaseName)=0
Public Member Functions inherited from HEPREP::HepRepAttribute
virtual ~HepRepAttribute ()
Destructor.
virtual void addAttValue (HepRepAttValue *attValue)=0
virtual void addAttValue (std::string key, char *value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, std::string value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, int64 value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, int value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, double value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, bool value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, std::vector< double > value, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual void addAttValue (std::string key, double red, double green, double blue, double alpha=1.0, int showLabel=HepRepConstants::SHOW_NONE)=0
virtual HepRepAttValue * removeAttValue (std::string key)=0
virtual HepRepAttValue * getAttValue (std::string name)=0
virtual std::set
< HepRepAttValue * > getAttValuesFromNode ()=0
virtual HepRepAttValue * getAttValueFromNode (std::string lowerCaseName)=0
Detailed Description
HepRepType interface.
Author
Mark Donszelmann
Definition at line 24 of file HepRepType.h.
View newest version in sPHENIX GitHub at line 24 of file HepRepType.h
Constructor & Destructor Documentation
virtual HEPREP::HepRepType::~HepRepType () inline virtual
Destructor.
Definition at line 28 of file HepRepType.h.
View newest version in sPHENIX GitHub at line 28 of file HepRepType.h
Member Function Documentation
virtual void HEPREP::HepRepType::addType (HepRepType * type) pure virtual
Adds a sub-type to this type.
Parameters
type sub-type to be added.
Implemented in cheprep::DefaultHepRepType.
Referenced by cheprep::DefaultHepRepType::DefaultHepRepType().
virtual HepRepType* HEPREP::HepRepType::copy (HepRepType * parent) pure virtual
Returns a deep copy of this type.
Parameters
parent to which this copy is added.
Returns
copy of this type.
Implemented in cheprep::DefaultHepRepType.
virtual std::string HEPREP::HepRepType::getDescription () pure virtual
Returns the description of this type.
Returns
description of type.
Implemented in cheprep::DefaultHepRepType.
virtual std::string HEPREP::HepRepType::getFullName () pure virtual
Returns the full name of this type. The full name is constructed from the root of the typeTree (without the typeTreeName) by concatenating all the node names separated by slashes "/". For example: Geometry/InnerDetector/Sector24/Wire20
Returns
full name of type.
See Also
getName()
Implemented in cheprep::DefaultHepRepType.
Referenced by cheprep::DefaultHepRepType::getFullName(), and cheprep::XMLHepRepWriter::write().
virtual std::string HEPREP::HepRepType::getInfoURL () pure virtual
Returns the information URL of this type.
Returns
info URL of type.
Implemented in cheprep::DefaultHepRepType.
virtual std::string HEPREP::HepRepType::getName () pure virtual
Returns the name of this type. This is the full name if one uses flat-types, and the node name if one uses hierarchical typenames. It is the name supplied at construction of the type.
Returns
name of type.
See Also
getFullName()
Implemented in cheprep::DefaultHepRepType.
Referenced by G4HepRepSceneHandler::getGeometryRootType(), and cheprep::XMLHepRepWriter::write().
virtual HepRepType* HEPREP::HepRepType::getSuperType () pure virtual
Returns the parent of this type.
Returns
parent of type, or null if top-level.
Implemented in cheprep::DefaultHepRepType.
Referenced by cheprep::DefaultHepRepType::getAttDef(), and cheprep::DefaultHepRepType::getAttValue().
virtual std::vector<HepRepType *> HEPREP::HepRepType::getTypeList () pure virtual
Returns a collection of all the sub-types of this type.
Returns
collection of HepRepTypes.
Implemented in cheprep::DefaultHepRepType.
Referenced by cheprep::XMLHepRepWriter::write().
virtual void HEPREP::HepRepType::setDescription (std::string description) pure virtual
Sets the description of this type.
Parameters
infoURL
Implemented in cheprep::DefaultHepRepType.
virtual void HEPREP::HepRepType::setInfoURL (std::string infoURL) pure virtual
Sets the information URL of this type.
Parameters
infoURL
Implemented in cheprep::DefaultHepRepType.
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/HEPREP/HepRepType.h