ECCE @ EIC Software: G4ParticleHPEvapSpectrum Class Reference
G4ParticleHPEvapSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPEvapSpectrum.hh>
Public Member Functions
G4ParticleHPEvapSpectrum ()
~G4ParticleHPEvapSpectrum ()
void Init (std::istream &aDataFile)
G4double GetFractionalProbability (G4double anEnergy)
G4double Sample (G4double anEnergy)
Public Member Functions inherited from G4VParticleHPEDis
G4VParticleHPEDis ()
virtual ~G4VParticleHPEDis ()
Private Attributes
G4ParticleHPVector theFractionalProb
G4ParticleHPVector theThetaDist
G4ParticleHPVector theXDist
Detailed Description
Definition at line 43 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ParticleHPEvapSpectrum.hh
Constructor & Destructor Documentation
G4ParticleHPEvapSpectrum::G4ParticleHPEvapSpectrum () inline
Definition at line 46 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleHPEvapSpectrum.hh
G4ParticleHPEvapSpectrum::~G4ParticleHPEvapSpectrum () inline
Definition at line 49 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 49 of file G4ParticleHPEvapSpectrum.hh
Member Function Documentation
G4double G4ParticleHPEvapSpectrum::GetFractionalProbability (G4double anEnergy) inline virtual
Implements G4VParticleHPEDis.
Definition at line 60 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPEvapSpectrum.hh
References G4ParticleHPVector::GetY(), and theFractionalProb.
void G4ParticleHPEvapSpectrum::Init (std::istream & aDataFile) inline virtual
Implements G4VParticleHPEDis.
Definition at line 53 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPEvapSpectrum.hh
References G4ParticleHPVector::Init(), theFractionalProb, theThetaDist, and theXDist.
G4double G4ParticleHPEvapSpectrum::Sample (G4double anEnergy) inline virtual
Implements G4VParticleHPEDis.
Definition at line 65 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 65 of file G4ParticleHPEvapSpectrum.hh
References CLHEP::eV, G4ParticleHPVector::GetY(), G4ParticleHPVector::Sample(), theta(), theThetaDist, theXDist, and x.
Member Data Documentation
G4ParticleHPVector G4ParticleHPEvapSpectrum::theFractionalProb private
Definition at line 76 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ParticleHPEvapSpectrum.hh
Referenced by GetFractionalProbability(), and Init().
G4ParticleHPVector G4ParticleHPEvapSpectrum::theThetaDist private
Definition at line 78 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleHPEvapSpectrum.hh
Referenced by Init(), and Sample().
G4ParticleHPVector G4ParticleHPEvapSpectrum::theXDist private
Definition at line 79 of file G4ParticleHPEvapSpectrum.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPEvapSpectrum.hh
Referenced by Init(), and Sample().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPEvapSpectrum.hh