ECCE @ EIC Software: CexmcSteppingAction Class Reference
CexmcSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcSteppingAction.hh>
Public Member Functions
CexmcSteppingAction (CexmcPhysicsManager *physicsManager)
void UserSteppingAction (const G4Step *step)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
CexmcPhysicsManager * physicsManager
const G4LogicalVolume * targetVolume
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 54 of file CexmcSteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file CexmcSteppingAction.hh
Constructor & Destructor Documentation
CexmcSteppingAction::CexmcSteppingAction (CexmcPhysicsManager * physicsManager) explicit
Definition at line 59 of file CexmcSteppingAction.cc.
View newest version in sPHENIX GitHub at line 59 of file CexmcSteppingAction.cc
References G4RunManager::GetRunManager(), G4RunManager::GetUserDetectorConstruction(), CexmcSetup::GetVolume(), CexmcSetup::Target, and targetVolume.
Member Function Documentation
void CexmcSteppingAction::UserSteppingAction (const G4Step * step) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 70 of file CexmcSteppingAction.cc.
View newest version in sPHENIX GitHub at line 70 of file CexmcSteppingAction.cc
References CexmcIncidentParticleTrackInfo::ActivateStudiedProcess(), CexmcIncidentParticleTrackInfo::AddTrackLengthInTarget(), CexmcIncidentParticleTrackType, fGeomBoundary, G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetStepLength(), G4StepPoint::GetTouchable(), G4Step::GetTrack(), CexmcIncidentParticleTrackInfo::IsStudiedProcessActivated(), CexmcIncidentParticleTrackInfo::NeedsTrackLengthResampling(), physicsManager, CexmcPhysicsManager::ResampleTrackLengthInTarget(), targetVolume, track, and Acts::Test::volume.
Member Data Documentation
CexmcPhysicsManager* CexmcSteppingAction::physicsManager private
Definition at line 63 of file CexmcSteppingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file CexmcSteppingAction.hh
Referenced by UserSteppingAction().
const G4LogicalVolume* CexmcSteppingAction::targetVolume private
Definition at line 65 of file CexmcSteppingAction.hh.
View newest version in sPHENIX GitHub at line 65 of file CexmcSteppingAction.hh
Referenced by CexmcSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcSteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcSteppingAction.cc