ECCE @ EIC Software: G4QMDReaction Class Reference
G4QMDReaction Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDReaction.hh>
Public Member Functions
G4QMDReaction ()
~G4QMDReaction ()
std::vector< G4QMDSystem * > GetFinalStates ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4ExcitationHandler * GetExcitationHandler ()
void UnUseGEM ()
void UseFRAG ()
void SetTMAX (G4int i)
void SetDT (G4double t)
void SetEF (G4double x)
virtual void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
void operator= (const G4QMDReaction &)
G4QMDReaction (const G4QMDReaction &)
void setEvaporationCh ()
void setHighEnergyModel ()
void doCollision ()
std::vector< G4QMDSystem * > doClusterJudgment ()
void calcOffSetOfCollision (G4double, const G4ParticleDefinition *, const G4ParticleDefinition *, G4double, G4double, G4double, G4ThreeVector)
Private Attributes
G4QMDMeanField * meanField
G4QMDCollision * collision
G4QMDSystem * system
G4double deltaT
G4int maxTime
G4double envelopF
G4Evaporation * evaporation
G4ExcitationHandler * excitationHandler
G4double coulomb_collision_gamma_proj
G4double coulomb_collision_rx_proj
G4double coulomb_collision_rz_proj
G4double coulomb_collision_px_proj
G4double coulomb_collision_pz_proj
G4double coulomb_collision_gamma_targ
G4double coulomb_collision_rx_targ
G4double coulomb_collision_rz_targ
G4double coulomb_collision_px_targ
G4double coulomb_collision_pz_targ
G4IonsShenCrossSection * shenXS
G4PiNuclearCrossSection * piNucXS
G4bool gem
G4bool frag
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 60 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 60 of file G4QMDReaction.hh
Constructor & Destructor Documentation
G4QMDReaction::G4QMDReaction ()
Definition at line 47 of file G4QMDReaction.cc.
View newest version in sPHENIX GitHub at line 47 of file G4QMDReaction.cc
References collision, coulomb_collision_gamma_proj, coulomb_collision_gamma_targ, coulomb_collision_px_proj, coulomb_collision_px_targ, coulomb_collision_pz_proj, coulomb_collision_pz_targ, coulomb_collision_rx_proj, coulomb_collision_rx_targ, coulomb_collision_rz_proj, coulomb_collision_rz_targ, G4PiNuclearCrossSection::Default_Name(), evaporation, excitationHandler, fCombined, G4CrossSectionDataSetRegistry::GetCrossSectionDataSet(), G4CrossSectionDataSetRegistry::Instance(), meanField, piNucXS, G4ExcitationHandler::SetDeexChannelsType(), G4ExcitationHandler::SetEvaporation(), setEvaporationCh(), and shenXS.
G4QMDReaction::~G4QMDReaction ()
Definition at line 89 of file G4QMDReaction.cc.
View newest version in sPHENIX GitHub at line 89 of file G4QMDReaction.cc
References collision, evaporation, excitationHandler, and meanField.
G4QMDReaction::G4QMDReaction (const G4QMDReaction &) inline private
Definition at line 84 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 84 of file G4QMDReaction.hh
Member Function Documentation
G4HadFinalState * G4QMDReaction::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 99 of file G4QMDReaction.cc.
View newest version in sPHENIX GitHub at line 99 of file G4QMDReaction.cc
References G4HadFinalState::AddSecondary(), G4Alpha::Alpha(), b, CLHEP::Hep3Vector::beta(), CLHEP::boostOf(), G4ExcitationHandler::BreakItUp(), calcOffSetOfCollision(), G4QMDNucleus::CalEnergyAndAngularMomentumInCM(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4QMDSystem::Clear(), G4HadFinalState::Clear(), collision, coulomb_collision_gamma_proj, coulomb_collision_gamma_targ, coulomb_collision_px_proj, coulomb_collision_px_targ, coulomb_collision_pz_proj, coulomb_collision_pz_targ, coulomb_collision_rx_proj, coulomb_collision_rx_targ, coulomb_collision_rz_proj, coulomb_collision_rz_targ, deltaT, G4QMDMeanField::DoClusterJudgment(), G4QMDMeanField::DoPropagation(), e1, e2, G4INCL::CrossSections::elastic(), envelopF, eplus, excitationHandler, fermi, CLHEP::HepLorentzVector::findBoostToCM(), frag, G4cout, G4endl, G4UniformRand, G4HadProjectile::Get4Momentum(), G4QMDParticipant::Get4Momentum(), G4DynamicParticle::Get4Momentum(), G4Nucleus::GetA_asInt(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4HadProjectile::GetDefinition(), G4QMDParticipant::GetDefinition(), G4DynamicParticle::GetDefinition(), G4Pow::GetInstance(), G4IonTable::GetIon(), G4IonTable::GetIonMass(), G4IonTable::GetIonTable(), G4VCrossSectionDataSet::GetIsoCrossSection(), G4HadProjectile::GetKineticEnergy(), G4QMDParticipant::GetMomentum(), G4DynamicParticle::GetMomentum(), G4QMDSystem::GetNOCollision(), G4QMDSystem::GetParticipant(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), G4QMDParticipant::GetPosition(), G4HadProjectile::GetTotalMomentum(), G4QMDSystem::GetTotalNumberOfParticipant(), G4QMDMeanField::GetTotalPotential(), G4Nucleus::GetZ_asInt(), GeV, int(), it, CLHEP::Hep3Vector::mag(), maxTime, meanField, MeV, pi, piNucXS, G4Pow::powN(), proj, r, G4QMDCollision::SetMeanField(), G4QMDMeanField::SetNucleus(), G4QMDSystem::SetParticipant(), G4QMDParticipant::SetProjectile(), G4HadFinalState::SetStatusChange(), G4QMDMeanField::SetSystem(), G4QMDParticipant::SetTarget(), G4QMDNucleus::SetTotalPotential(), shenXS, stopAndKill, system, targ, G4HadronicInteraction::theParticleChange, CLHEP::Hep3Vector::unit(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4QMDReaction::calcOffSetOfCollision (G4double b, const G4ParticleDefinition * pd_proj, const G4ParticleDefinition * pd_targ, G4double ptot, G4double etot, G4double bmax, G4ThreeVector boostToCM) private
Definition at line 661 of file G4QMDReaction.cc.
View newest version in sPHENIX GitHub at line 661 of file G4QMDReaction.cc
References G4InuclParticleNames::ap, Acts::Test::at, coulomb_collision_gamma_proj, coulomb_collision_gamma_targ, coulomb_collision_px_proj, coulomb_collision_px_targ, coulomb_collision_pz_proj, coulomb_collision_pz_targ, coulomb_collision_rx_proj, coulomb_collision_rx_targ, coulomb_collision_rz_proj, coulomb_collision_rz_targ, eplus, Acts::VectorHelpers::eta(), CLHEP::Hep3Vector::gamma(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGMass(), GeV, int(), rmax(), theta(), and CLHEP::Hep3Vector::z().
Referenced by ApplyYourself().
std::vector< G4QMDSystem* > G4QMDReaction::doClusterJudgment () private
void G4QMDReaction::doCollision () private
G4ExcitationHandler* G4QMDReaction::GetExcitationHandler () inline
Definition at line 70 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QMDReaction.hh
References excitationHandler.
std::vector< G4QMDSystem* > G4QMDReaction::GetFinalStates ()
void G4QMDReaction::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 816 of file G4QMDReaction.cc.
View newest version in sPHENIX GitHub at line 816 of file G4QMDReaction.cc
void G4QMDReaction::operator= (const G4QMDReaction &) inline private
Definition at line 83 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QMDReaction.hh
void G4QMDReaction::SetDT (G4double t) inline
Definition at line 76 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QMDReaction.hh
References deltaT, and t.
void G4QMDReaction::SetEF (G4double x) inline
Definition at line 77 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QMDReaction.hh
References envelopF, and x.
void G4QMDReaction::setEvaporationCh () private
Definition at line 806 of file G4QMDReaction.cc.
View newest version in sPHENIX GitHub at line 806 of file G4QMDReaction.cc
References evaporation, gem, G4Evaporation::SetDefaultChannel(), and G4Evaporation::SetGEMChannel().
Referenced by G4QMDReaction(), and UnUseGEM().
void G4QMDReaction::setHighEnergyModel () private
void G4QMDReaction::SetTMAX (G4int i) inline
Definition at line 75 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QMDReaction.hh
References maxTime.
void G4QMDReaction::UnUseGEM () inline
Definition at line 72 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QMDReaction.hh
References gem, and setEvaporationCh().
void G4QMDReaction::UseFRAG () inline
Definition at line 73 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QMDReaction.hh
References frag.
Member Data Documentation
G4QMDCollision* G4QMDReaction::collision private
Definition at line 91 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 91 of file G4QMDReaction.hh
Referenced by ApplyYourself(), G4QMDReaction(), and ~G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_gamma_proj private
Definition at line 111 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 111 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_gamma_targ private
Definition at line 117 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 117 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_px_proj private
Definition at line 114 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 114 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_px_targ private
Definition at line 120 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 120 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_pz_proj private
Definition at line 115 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 115 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_pz_targ private
Definition at line 121 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 121 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_rx_proj private
Definition at line 112 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 112 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_rx_targ private
Definition at line 118 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 118 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_rz_proj private
Definition at line 113 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 113 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::coulomb_collision_rz_targ private
Definition at line 119 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 119 of file G4QMDReaction.hh
Referenced by ApplyYourself(), calcOffSetOfCollision(), and G4QMDReaction().
G4double G4QMDReaction::deltaT private
Definition at line 97 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 97 of file G4QMDReaction.hh
Referenced by ApplyYourself(), and SetDT().
G4double G4QMDReaction::envelopF private
Definition at line 99 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 99 of file G4QMDReaction.hh
Referenced by ApplyYourself(), and SetEF().
G4Evaporation* G4QMDReaction::evaporation private
Definition at line 101 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 101 of file G4QMDReaction.hh
Referenced by G4QMDReaction(), setEvaporationCh(), and ~G4QMDReaction().
G4ExcitationHandler* G4QMDReaction::excitationHandler private
Definition at line 102 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 102 of file G4QMDReaction.hh
Referenced by ApplyYourself(), G4QMDReaction(), GetExcitationHandler(), and ~G4QMDReaction().
G4bool G4QMDReaction::frag private
Definition at line 130 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 130 of file G4QMDReaction.hh
Referenced by ApplyYourself(), and UseFRAG().
G4bool G4QMDReaction::gem private
Definition at line 129 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 129 of file G4QMDReaction.hh
Referenced by setEvaporationCh(), and UnUseGEM().
G4int G4QMDReaction::maxTime private
Definition at line 98 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 98 of file G4QMDReaction.hh
Referenced by ApplyYourself(), and SetTMAX().
G4QMDMeanField* G4QMDReaction::meanField private
Definition at line 89 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 89 of file G4QMDReaction.hh
Referenced by ApplyYourself(), G4QMDReaction(), and ~G4QMDReaction().
G4PiNuclearCrossSection* G4QMDReaction::piNucXS private
Definition at line 127 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 127 of file G4QMDReaction.hh
Referenced by ApplyYourself(), and G4QMDReaction().
G4IonsShenCrossSection* G4QMDReaction::shenXS private
Definition at line 124 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 124 of file G4QMDReaction.hh
Referenced by ApplyYourself(), and G4QMDReaction().
G4QMDSystem* G4QMDReaction::system private
Definition at line 96 of file G4QMDReaction.hh.
View newest version in sPHENIX GitHub at line 96 of file G4QMDReaction.hh
Referenced by ApplyYourself().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/include/G4QMDReaction.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/qmd/src/G4QMDReaction.cc