ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/ptwXY_unitaryOperators.cc File Reference
ptwXY_unitaryOperators.cc File Reference
#include <cmath>
#include <float.h>
#include "ptwXY.h"
Functions
nfu_status ptwXY_abs (ptwXYPoints *ptwXY)
nfu_status ptwXY_neg (ptwXYPoints *ptwXY)
Function Documentation
nfu_status ptwXY_abs (ptwXYPoints * ptwXY)
Definition at line 19 of file ptwXY_unitaryOperators.cc.
View newest version in sPHENIX GitHub at line 19 of file ptwXY_unitaryOperators.cc
References ptwXYOverflowPoint_s::next, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
nfu_status ptwXY_neg (ptwXYPoints * ptwXY)
Definition at line 34 of file ptwXY_unitaryOperators.cc.
View newest version in sPHENIX GitHub at line 34 of file ptwXY_unitaryOperators.cc
References ptwXYOverflowPoint_s::next, nfu_Okay, ptwXYPoints_s::overflowHeader, ptwXYOverflowPoint_s::point, ptwXYPoints_s::points, ptwXY_getNonOverflowLength(), ptwXYPoints_s::status, and ptwXYPoint_s::y.
Referenced by ptwXY_sub_ptwXY().