ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/particles/pyG4ParticleDefinition.cc File Reference
pyG4ParticleDefinition.cc File Reference
#include <boost/python.hpp>
#include "G4Version.hh"
#include "G4ParticleDefinition.hh"
#include "G4ParticleTable.hh"
#include "G4DecayTable.hh"
#include "G4ProcessManager.hh"
Functions
void export_G4ParticleDefinition ()
Function Documentation
void export_G4ParticleDefinition ()
Definition at line 43 of file pyG4ParticleDefinition.cc.
View newest version in sPHENIX GitHub at line 43 of file pyG4ParticleDefinition.cc
References G4ParticleDefinition::DumpTable(), G4ParticleDefinition::GetAntiPDGEncoding(), G4ParticleDefinition::GetAntiQuarkContent(), G4ParticleDefinition::GetApplyCutsFlag(), G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4ParticleDefinition::GetBaryonNumber(), G4ParticleDefinition::GetDecayTable(), G4ParticleDefinition::GetLeptonNumber(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetParticleSubType(), G4ParticleDefinition::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), G4ParticleDefinition::GetPDGiConjugation(), G4ParticleDefinition::GetPDGiGParity(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGiIsospin3(), G4ParticleDefinition::GetPDGiParity(), G4ParticleDefinition::GetPDGIsospin(), G4ParticleDefinition::GetPDGIsospin3(), G4ParticleDefinition::GetPDGiSpin(), G4ParticleDefinition::GetPDGLifeTime(), G4ParticleDefinition::GetPDGMass(), G4ParticleDefinition::GetPDGSpin(), G4ParticleDefinition::GetPDGStable(), G4ParticleDefinition::GetPDGWidth(), G4ParticleDefinition::GetProcessManager(), G4ParticleDefinition::GetQuarkContent(), G4ParticleDefinition::GetVerboseLevel(), G4ParticleDefinition::IsShortLived(), G4ParticleDefinition::SetApplyCutsFlag(), G4ParticleDefinition::SetDecayTable(), G4ParticleDefinition::SetPDGLifeTime(), G4ParticleDefinition::SetPDGStable(), G4ParticleDefinition::SetProcessManager(), and G4ParticleDefinition::SetVerboseLevel().
Referenced by BOOST_PYTHON_MODULE().