ECCE @ EIC Software: G4PhysChemIO::G4Analysis Class Reference
G4PhysChemIO::G4Analysis Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4PhysChemIO.hh>
Public Member Functions
G4Analysis (G4VAnalysisManager *)
virtual ~G4Analysis ()
virtual void InitializeMaster ()
virtual void InitializeThread ()
virtual void InitializeFile ()
virtual void NewRun ()
virtual void NewEvent ()
virtual void CreateWaterMolecule (G4int electronicModif, G4int, G4double energy, const G4Track *)
virtual void CreateSolvatedElectron (const G4Track *, G4ThreeVector *finalPosition=0)
virtual void WriteInto (const G4String &, std::ios_base::openmode mode=std::ios_base::out)
virtual void AddEmptyLineInOutputFile ()
virtual void CloseFile ()
Public Member Functions inherited from G4VPhysChemIO
G4VPhysChemIO ()
virtual ~G4VPhysChemIO ()
Protected Attributes
G4VAnalysisManager * fpAnalysisManager
int fNtupleID
G4bool fFileInitialized
Detailed Description
Definition at line 101 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 101 of file G4PhysChemIO.hh
Constructor & Destructor Documentation
G4PhysChemIO::G4Analysis::G4Analysis (G4VAnalysisManager * analysisManager)
Definition at line 162 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 162 of file G4PhysChemIO.cc
References fFileInitialized, and fNtupleID.
G4PhysChemIO::G4Analysis::~G4Analysis () virtual
Definition at line 171 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 171 of file G4PhysChemIO.cc
References fpAnalysisManager.
Member Function Documentation
virtual void G4PhysChemIO::G4Analysis::AddEmptyLineInOutputFile () inline virtual
Reimplemented from G4VPhysChemIO.
Definition at line 145 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 145 of file G4PhysChemIO.hh
void G4PhysChemIO::G4Analysis::CloseFile () virtual
Close the file specified with WriteInto
Implements G4VPhysChemIO.
Definition at line 218 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 218 of file G4PhysChemIO.cc
void G4PhysChemIO::G4Analysis::CreateSolvatedElectron (const G4Track * electronTrack, G4ThreeVector * finalPosition = 0) virtual
Same idea as the previous method but for solvated electron. This method should be used by the physics model of the ElectronSolvatation process.
Implements G4VPhysChemIO.
Definition at line 264 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 264 of file G4PhysChemIO.cc
References G4VAnalysisManager::AddNtupleRow(), eV, fFileInitialized, G4VAnalysisManager::FillNtupleDColumn(), G4VAnalysisManager::FillNtupleIColumn(), G4VAnalysisManager::FillNtupleSColumn(), fNtupleID, fpAnalysisManager, G4Track::GetKineticEnergy(), G4Track::GetPosition(), G4Track::GetTrackID(), InitializeFile(), nanometer, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4PhysChemIO::G4Analysis::CreateWaterMolecule (G4int electronicModif, G4int electronicLevel, G4double energy, const G4Track * theIncomingTrack) virtual
Method used by DNA physics model to create a water molecule. The ElectronicModification is a flag telling wheter the molecule is ionized or excited, the electronic level is calculated by the model and the IncomingTrack is the track responsible for the creation of this molecule, for instance an electron.
Implements G4VPhysChemIO.
Definition at line 226 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 226 of file G4PhysChemIO.cc
References G4VAnalysisManager::AddNtupleRow(), eV, fFileInitialized, G4VAnalysisManager::FillNtupleDColumn(), G4VAnalysisManager::FillNtupleIColumn(), G4VAnalysisManager::FillNtupleSColumn(), fNtupleID, fpAnalysisManager, G4Track::GetPosition(), G4Track::GetTrackID(), InitializeFile(), nanometer, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
void G4PhysChemIO::G4Analysis::InitializeFile () virtual
Implements G4VPhysChemIO.
Definition at line 178 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 178 of file G4PhysChemIO.cc
References G4VAnalysisManager::CreateNtuple(), G4VAnalysisManager::CreateNtupleDColumn(), G4VAnalysisManager::CreateNtupleIColumn(), G4VAnalysisManager::CreateNtupleSColumn(), fFileInitialized, G4VAnalysisManager::FinishNtuple(), fNtupleID, and fpAnalysisManager.
Referenced by CreateSolvatedElectron(), and CreateWaterMolecule().
virtual void G4PhysChemIO::G4Analysis::InitializeMaster () inline virtual
Reimplemented from G4VPhysChemIO.
Definition at line 107 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 107 of file G4PhysChemIO.hh
virtual void G4PhysChemIO::G4Analysis::InitializeThread () inline virtual
Reimplemented from G4VPhysChemIO.
Definition at line 108 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 108 of file G4PhysChemIO.hh
virtual void G4PhysChemIO::G4Analysis::NewEvent () inline virtual
Implements G4VPhysChemIO.
Definition at line 112 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 112 of file G4PhysChemIO.hh
virtual void G4PhysChemIO::G4Analysis::NewRun () inline virtual
Implements G4VPhysChemIO.
Definition at line 111 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 111 of file G4PhysChemIO.hh
void G4PhysChemIO::G4Analysis::WriteInto (const G4String & , std::ios_base::openmode mode = std::ios_base::out) virtual
Tells the chemMan to write into a file the position and electronic state of the water molecule and the position thermalized or not of the solvated electron
Implements G4VPhysChemIO.
Definition at line 209 of file G4PhysChemIO.cc.
View newest version in sPHENIX GitHub at line 209 of file G4PhysChemIO.cc
References fFileInitialized, fpAnalysisManager, and G4VAnalysisManager::OpenFile().
Member Data Documentation
G4bool G4PhysChemIO::G4Analysis::fFileInitialized protected
Definition at line 155 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 155 of file G4PhysChemIO.hh
Referenced by CreateSolvatedElectron(), CreateWaterMolecule(), G4Analysis(), InitializeFile(), and WriteInto().
int G4PhysChemIO::G4Analysis::fNtupleID protected
Definition at line 154 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 154 of file G4PhysChemIO.hh
Referenced by CreateSolvatedElectron(), CreateWaterMolecule(), G4Analysis(), and InitializeFile().
G4VAnalysisManager* G4PhysChemIO::G4Analysis::fpAnalysisManager protected
Definition at line 153 of file G4PhysChemIO.hh.
View newest version in sPHENIX GitHub at line 153 of file G4PhysChemIO.hh
Referenced by CreateSolvatedElectron(), CreateWaterMolecule(), InitializeFile(), WriteInto(), and ~G4Analysis().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/include/G4PhysChemIO.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/utils/src/G4PhysChemIO.cc