ECCE @ EIC Software: G4StatMFMacroChemicalPotential Class Reference
G4StatMFMacroChemicalPotential Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroChemicalPotential.hh>
Public Member Functions
G4StatMFMacroChemicalPotential (const G4double anA, const G4double aZ, const G4double kappa, const G4double temp, std::vector< G4VStatMFMacroCluster * > *ClusterVector)
~G4StatMFMacroChemicalPotential ()
G4double operator() (const G4double nu)
G4double GetMeanMultiplicity (void) const
G4double GetChemicalPotentialMu (void) const
G4double GetChemicalPotentialNu (void) const
G4double CalcChemicalPotentialNu (void)
Private Member Functions
G4StatMFMacroChemicalPotential ()
G4StatMFMacroChemicalPotential (const G4StatMFMacroChemicalPotential &)
G4StatMFMacroChemicalPotential & operator= (const G4StatMFMacroChemicalPotential &right)
G4bool operator== (const G4StatMFMacroChemicalPotential &right) const
G4bool operator!= (const G4StatMFMacroChemicalPotential &right) const
G4double CalcMeanZ (const G4double nu)
void CalcChemicalPotentialMu (const G4double nu)
Private Attributes
G4double theA
G4double theZ
G4double _Kappa
G4double _MeanMultiplicity
G4double _MeanTemperature
G4double _ChemPotentialMu
G4double _ChemPotentialNu
std::vector
< G4VStatMFMacroCluster * > * _theClusters
Detailed Description
Definition at line 43 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 43 of file G4StatMFMacroChemicalPotential.hh
Constructor & Destructor Documentation
G4StatMFMacroChemicalPotential::G4StatMFMacroChemicalPotential (const G4double anA, const G4double aZ, const G4double kappa, const G4double temp, std::vector< G4VStatMFMacroCluster * > * ClusterVector) inline
Definition at line 47 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 47 of file G4StatMFMacroChemicalPotential.hh
G4StatMFMacroChemicalPotential::~G4StatMFMacroChemicalPotential () inline
Definition at line 61 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 61 of file G4StatMFMacroChemicalPotential.hh
G4StatMFMacroChemicalPotential::G4StatMFMacroChemicalPotential () inline private
Definition at line 68 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 68 of file G4StatMFMacroChemicalPotential.hh
G4StatMFMacroChemicalPotential::G4StatMFMacroChemicalPotential (const G4StatMFMacroChemicalPotential &) inline private
Definition at line 71 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 71 of file G4StatMFMacroChemicalPotential.hh
Member Function Documentation
void G4StatMFMacroChemicalPotential::CalcChemicalPotentialMu (const G4double nu) private
Definition at line 130 of file G4StatMFMacroChemicalPotential.cc.
View newest version in sPHENIX GitHub at line 130 of file G4StatMFMacroChemicalPotential.cc
References _ChemPotentialMu, _Kappa, _MeanMultiplicity, _MeanTemperature, _theClusters, G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroMultiplicity::GetMeanMultiplicity(), and theA.
Referenced by CalcMeanZ().
G4double G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu (void)
Definition at line 56 of file G4StatMFMacroChemicalPotential.cc.
View newest version in sPHENIX GitHub at line 56 of file G4StatMFMacroChemicalPotential.cc
References _ChemPotentialNu, kdfinder::abs(), G4Solver< Function >::Brent(), G4cout, G4endl, G4StatMFParameters::GetCoulomb(), G4StatMFParameters::GetGamma0(), G4Pow::GetInstance(), G4Solver< Function >::GetRoot(), operator()(), G4Solver< Function >::SetIntervalLimits(), theA, theZ, and G4Pow::Z23().
Referenced by G4StatMFMacroTemperature::CalcChemicalPotentialNu().
G4double G4StatMFMacroChemicalPotential::CalcMeanZ (const G4double nu) private
Definition at line 108 of file G4StatMFMacroChemicalPotential.cc.
View newest version in sPHENIX GitHub at line 108 of file G4StatMFMacroChemicalPotential.cc
References _theClusters, CalcChemicalPotentialMu(), and n.
Referenced by operator()().
G4double G4StatMFMacroChemicalPotential::GetChemicalPotentialMu (void) const inline
Definition at line 83 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 83 of file G4StatMFMacroChemicalPotential.hh
References _ChemPotentialMu.
Referenced by G4StatMFMacroTemperature::CalcChemicalPotentialNu().
G4double G4StatMFMacroChemicalPotential::GetChemicalPotentialNu (void) const inline
Definition at line 85 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 85 of file G4StatMFMacroChemicalPotential.hh
References _ChemPotentialNu.
G4double G4StatMFMacroChemicalPotential::GetMeanMultiplicity (void) const inline
Definition at line 81 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 81 of file G4StatMFMacroChemicalPotential.hh
References _MeanMultiplicity.
Referenced by G4StatMFMacroTemperature::CalcChemicalPotentialNu().
G4bool G4StatMFMacroChemicalPotential::operator!= (const G4StatMFMacroChemicalPotential & right) const private
Definition at line 50 of file G4StatMFMacroChemicalPotential.cc.
View newest version in sPHENIX GitHub at line 50 of file G4StatMFMacroChemicalPotential.cc
G4double G4StatMFMacroChemicalPotential::operator() (const G4double nu) inline
Definition at line 63 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 63 of file G4StatMFMacroChemicalPotential.hh
References CalcMeanZ(), and theZ.
Referenced by CalcChemicalPotentialNu().
G4StatMFMacroChemicalPotential & G4StatMFMacroChemicalPotential::operator= (const G4StatMFMacroChemicalPotential & right) private
Definition at line 37 of file G4StatMFMacroChemicalPotential.cc.
View newest version in sPHENIX GitHub at line 37 of file G4StatMFMacroChemicalPotential.cc
G4bool G4StatMFMacroChemicalPotential::operator== (const G4StatMFMacroChemicalPotential & right) const private
Definition at line 43 of file G4StatMFMacroChemicalPotential.cc.
View newest version in sPHENIX GitHub at line 43 of file G4StatMFMacroChemicalPotential.cc
Member Data Documentation
G4double G4StatMFMacroChemicalPotential::_ChemPotentialMu private
Definition at line 107 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 107 of file G4StatMFMacroChemicalPotential.hh
Referenced by CalcChemicalPotentialMu(), and GetChemicalPotentialMu().
G4double G4StatMFMacroChemicalPotential::_ChemPotentialNu private
Definition at line 109 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 109 of file G4StatMFMacroChemicalPotential.hh
Referenced by CalcChemicalPotentialNu(), and GetChemicalPotentialNu().
G4double G4StatMFMacroChemicalPotential::_Kappa private
Definition at line 101 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 101 of file G4StatMFMacroChemicalPotential.hh
Referenced by CalcChemicalPotentialMu().
G4double G4StatMFMacroChemicalPotential::_MeanMultiplicity private
Definition at line 103 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 103 of file G4StatMFMacroChemicalPotential.hh
Referenced by CalcChemicalPotentialMu(), and GetMeanMultiplicity().
G4double G4StatMFMacroChemicalPotential::_MeanTemperature private
Definition at line 105 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 105 of file G4StatMFMacroChemicalPotential.hh
Referenced by CalcChemicalPotentialMu().
std::vector<G4VStatMFMacroCluster*>* G4StatMFMacroChemicalPotential::_theClusters private
Definition at line 111 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 111 of file G4StatMFMacroChemicalPotential.hh
Referenced by CalcChemicalPotentialMu(), and CalcMeanZ().
G4double G4StatMFMacroChemicalPotential::theA private
Definition at line 97 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 97 of file G4StatMFMacroChemicalPotential.hh
Referenced by CalcChemicalPotentialMu(), and CalcChemicalPotentialNu().
G4double G4StatMFMacroChemicalPotential::theZ private
Definition at line 99 of file G4StatMFMacroChemicalPotential.hh.
View newest version in sPHENIX GitHub at line 99 of file G4StatMFMacroChemicalPotential.hh
Referenced by CalcChemicalPotentialNu(), and operator()().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMFMacroChemicalPotential.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMFMacroChemicalPotential.cc