ECCE @ EIC Software: G4TrajectoryDrawerUtils Namespace Reference
G4TrajectoryDrawerUtils Namespace Reference
Enumerations
enum TimesValidity { InvalidTimes, ValidTimes }
Functions
void GetPoints (const G4VTrajectory &traj, G4Polyline &trajectoryLine, G4Polymarker &auxiliaryPoints, G4Polymarker &stepPoints)
void DrawLineAndPoints (const G4VTrajectory &traj, const G4VisTrajContext &)
TimesValidity GetPointsAndTimes (const G4VTrajectory &traj, const G4VisTrajContext &context, G4Polyline &trajectoryLine, G4Polymarker &auxiliaryPoints, G4Polymarker &stepPoints, std::vector< G4double > &trajectoryLineTimes, std::vector< G4double > &auxiliaryPointTimes, std::vector< G4double > &stepPointTimes)
static void SliceLine (G4double timeIncrement, G4Polyline &trajectoryLine, std::vector< G4double > &trajectoryLineTimes)
static void DrawWithoutTime (const G4VisTrajContext &myContext, G4Polyline &trajectoryLine, G4Polymarker &auxiliaryPoints, G4Polymarker &stepPoints)
static void DrawWithTime (const G4VisTrajContext &myContext, G4Polyline &trajectoryLine, G4Polymarker &auxiliaryPoints, G4Polymarker &stepPoints, std::vector< G4double > &trajectoryLineTimes, std::vector< G4double > &auxiliaryPointTimes, std::vector< G4double > &stepPointTimes)
Enumeration Type Documentation
enum G4TrajectoryDrawerUtils::TimesValidity
Enumerator:
InvalidTimes
ValidTimes
Definition at line 43 of file G4TrajectoryDrawerUtils.cc.
View newest version in sPHENIX GitHub at line 43 of file G4TrajectoryDrawerUtils.cc
Function Documentation
void G4TrajectoryDrawerUtils::DrawLineAndPoints (const G4VTrajectory & traj, const G4VisTrajContext & context)
Definition at line 314 of file G4TrajectoryDrawerUtils.cc.
View newest version in sPHENIX GitHub at line 314 of file G4TrajectoryDrawerUtils.cc
References DrawWithoutTime(), DrawWithTime(), G4VisTrajContext::GetDrawAuxPts(), G4VisTrajContext::GetDrawLine(), G4VisTrajContext::GetDrawStepPts(), GetPointsAndTimes(), G4VisTrajContext::GetTimeSliceInterval(), SliceLine(), and ValidTimes.
Referenced by G4TrajectoryGenericDrawer::Draw(), G4TrajectoryDrawByOriginVolume::Draw(), G4TrajectoryDrawByParticleID::Draw(), G4TrajectoryDrawByAttribute::Draw(), G4TrajectoryDrawByEncounteredVolume::Draw(), and G4TrajectoryDrawByCharge::Draw().
static void G4TrajectoryDrawerUtils::DrawWithoutTime (const G4VisTrajContext & myContext, G4Polyline & trajectoryLine, G4Polymarker & auxiliaryPoints, G4Polymarker & stepPoints) static
Definition at line 208 of file G4TrajectoryDrawerUtils.cc.
View newest version in sPHENIX GitHub at line 208 of file G4TrajectoryDrawerUtils.cc
References G4VVisManager::Draw(), G4VisTrajContext::GetAuxPtsColour(), G4VisTrajContext::GetAuxPtsFillStyle(), G4VisTrajContext::GetAuxPtsSize(), G4VisTrajContext::GetAuxPtsSizeType(), G4VisTrajContext::GetAuxPtsType(), G4VisTrajContext::GetAuxPtsVisible(), G4VVisManager::GetConcreteInstance(), G4VisTrajContext::GetDrawAuxPts(), G4VisTrajContext::GetDrawLine(), G4VisTrajContext::GetDrawStepPts(), G4VisTrajContext::GetLineColour(), G4VisTrajContext::GetLineVisible(), G4VisTrajContext::GetLineWidth(), G4VisTrajContext::GetStepPtsColour(), G4VisTrajContext::GetStepPtsFillStyle(), G4VisTrajContext::GetStepPtsSize(), G4VisTrajContext::GetStepPtsSizeType(), G4VisTrajContext::GetStepPtsType(), G4VisTrajContext::GetStepPtsVisible(), G4VMarker::SetFillStyle(), G4VisAttributes::SetLineWidth(), G4Polymarker::SetMarkerType(), G4VMarker::SetSize(), and G4Visible::SetVisAttributes().
Referenced by DrawLineAndPoints().
static void G4TrajectoryDrawerUtils::DrawWithTime (const G4VisTrajContext & myContext, G4Polyline & trajectoryLine, G4Polymarker & auxiliaryPoints, G4Polymarker & stepPoints, std::vector< G4double > & trajectoryLineTimes, std::vector< G4double > & auxiliaryPointTimes, std::vector< G4double > & stepPointTimes) static
Definition at line 251 of file G4TrajectoryDrawerUtils.cc.
View newest version in sPHENIX GitHub at line 251 of file G4TrajectoryDrawerUtils.cc
References G4VVisManager::Draw(), G4VisTrajContext::GetAuxPtsColour(), G4VisTrajContext::GetAuxPtsFillStyle(), G4VisTrajContext::GetAuxPtsSize(), G4VisTrajContext::GetAuxPtsSizeType(), G4VisTrajContext::GetAuxPtsType(), G4VisTrajContext::GetAuxPtsVisible(), G4VVisManager::GetConcreteInstance(), G4VisTrajContext::GetDrawAuxPts(), G4VisTrajContext::GetDrawLine(), G4VisTrajContext::GetDrawStepPts(), G4VisTrajContext::GetLineColour(), G4VisTrajContext::GetLineVisible(), G4VisTrajContext::GetLineWidth(), G4VisTrajContext::GetStepPtsColour(), G4VisTrajContext::GetStepPtsFillStyle(), G4VisTrajContext::GetStepPtsSize(), G4VisTrajContext::GetStepPtsSizeType(), G4VisTrajContext::GetStepPtsType(), G4VisTrajContext::GetStepPtsVisible(), G4VMarker::SetFillStyle(), G4VisAttributes::SetLineWidth(), G4Polymarker::SetMarkerType(), G4VMarker::SetSize(), and G4Visible::SetVisAttributes().
Referenced by DrawLineAndPoints().
void G4TrajectoryDrawerUtils::GetPoints (const G4VTrajectory & traj, G4Polyline & trajectoryLine, G4Polymarker & auxiliaryPoints, G4Polymarker & stepPoints)
TimesValidity G4TrajectoryDrawerUtils::GetPointsAndTimes (const G4VTrajectory & traj, const G4VisTrajContext & context, G4Polyline & trajectoryLine, G4Polymarker & auxiliaryPoints, G4Polymarker & stepPoints, std::vector< G4double > & trajectoryLineTimes, std::vector< G4double > & auxiliaryPointTimes, std::vector< G4double > & stepPointTimes)
Definition at line 46 of file G4TrajectoryDrawerUtils.cc.
View newest version in sPHENIX GitHub at line 46 of file G4TrajectoryDrawerUtils.cc
References G4UIcommand::ConvertToDimensionedDouble(), G4VTrajectoryPoint::CreateAttValues(), G4cout, G4endl, G4VTrajectoryPoint::GetAuxiliaryPoints(), G4VTrajectory::GetPoint(), G4VTrajectory::GetPointEntries(), G4VTrajectoryPoint::GetPosition(), G4VisTrajContext::GetTimeSliceInterval(), InvalidTimes, max, s1, t, and ValidTimes.
Referenced by DrawLineAndPoints().
static void G4TrajectoryDrawerUtils::SliceLine (G4double timeIncrement, G4Polyline & trajectoryLine, std::vector< G4double > & trajectoryLineTimes) static
Definition at line 169 of file G4TrajectoryDrawerUtils.cc.
View newest version in sPHENIX GitHub at line 169 of file G4TrajectoryDrawerUtils.cc
References max, pos(), and t.
Referenced by DrawLineAndPoints().