ECCE @ EIC Software: XrayFluoNistMaterials Class Reference
XrayFluoNistMaterials Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoNistMaterials.hh>
Public Member Functions
~XrayFluoNistMaterials ()
G4Material * GetMaterial (G4String)
Static Public Member Functions
static XrayFluoNistMaterials * GetInstance ()
Private Member Functions
XrayFluoNistMaterials ()
void CreateMaterials ()
Private Attributes
G4NistManager * nistMan
G4Material * copper
G4Material * SiLi
G4Material * dolorite
G4Material * HPGe
G4Material * mars1
G4Material * hawaiianWD
G4Material * hawaiianRF
G4Material * anorthosite
G4Material * basalt
G4Material * gabbro
G4Material * gabbroWD
G4Material * gabbroRF
G4Material * Air
G4Material * Sci
G4Material * Vacuum
G4Material * madaBasalt
G4Material * icelandicBasalt
G4Material * icelandicWD
G4Material * icelandicRF
G4Material * GaAs
G4Material * galactic
Static Private Attributes
static XrayFluoNistMaterials * instance = 0
Detailed Description
Definition at line 43 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 43 of file XrayFluoNistMaterials.hh
Constructor & Destructor Documentation
XrayFluoNistMaterials::~XrayFluoNistMaterials ()
Definition at line 43 of file XrayFluoNistMaterials.cc.
View newest version in sPHENIX GitHub at line 43 of file XrayFluoNistMaterials.cc
References Air, anorthosite, basalt, copper, dolorite, GaAs, gabbro, gabbroRF, gabbroWD, galactic, hawaiianRF, hawaiianWD, HPGe, icelandicBasalt, icelandicRF, icelandicWD, madaBasalt, mars1, Sci, SiLi, and Vacuum.
XrayFluoNistMaterials::XrayFluoNistMaterials () private
Definition at line 40 of file XrayFluoNistMaterials.cc.
View newest version in sPHENIX GitHub at line 40 of file XrayFluoNistMaterials.cc
References CreateMaterials().
Referenced by GetInstance().
Member Function Documentation
void XrayFluoNistMaterials::CreateMaterials () private
Definition at line 100 of file XrayFluoNistMaterials.cc.
View newest version in sPHENIX GitHub at line 100 of file XrayFluoNistMaterials.cc
References G4Material::AddMaterial(), anorthosite, basalt, cm3, G4NistManager::ConstructNewMaterial(), copper, dolorite, E, e, elements, Acts::UnitConstants::g, G4cout, G4endl, GaAs, gabbro, gabbroRF, gabbroWD, G4Material::GetMaterialTable(), hawaiianRF, hawaiianWD, icelandicBasalt, icelandicRF, icelandicWD, G4NistManager::Instance(), kelvin, kg, kStateGas, m3, madaBasalt, mars1, mole, nistMan, pascal, Sci, G4NistManager::SetVerbose(), SiLi, source.hepunit::universe_mean_density, and Vacuum.
Referenced by XrayFluoNistMaterials().
XrayFluoNistMaterials * XrayFluoNistMaterials::GetInstance (void) static
Definition at line 73 of file XrayFluoNistMaterials.cc.
View newest version in sPHENIX GitHub at line 73 of file XrayFluoNistMaterials.cc
References instance, and XrayFluoNistMaterials().
Referenced by XrayFluoDetectorConstruction::XrayFluoDetectorConstruction(), XrayFluoMercuryDetectorConstruction::XrayFluoMercuryDetectorConstruction(), and XrayFluoPlaneDetectorConstruction::XrayFluoPlaneDetectorConstruction().
G4Material * XrayFluoNistMaterials::GetMaterial (G4String material)
Definition at line 83 of file XrayFluoNistMaterials.cc.
View newest version in sPHENIX GitHub at line 83 of file XrayFluoNistMaterials.cc
References G4NistManager::FindOrBuildMaterial(), G4cout, G4endl, G4Material::GetMaterial(), G4NistManager::Instance(), mat, nistMan, and G4NistManager::SetVerbose().
Referenced by XrayFluoMercuryDetectorConstruction::DefineDefaultMaterials(), XrayFluoPlaneDetectorConstruction::DefineDefaultMaterials(), XrayFluoDetectorConstruction::DefineDefaultMaterials(), XrayFluoMercuryDetectorConstruction::SetMercuryMaterial(), XrayFluoDetectorConstruction::SetOhmicPosThickness(), XrayFluoPlaneDetectorConstruction::SetPlaneMaterial(), and XrayFluoDetectorConstruction::SetSampleMaterial().
Member Data Documentation
G4Material* XrayFluoNistMaterials::Air private
Definition at line 78 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 78 of file XrayFluoNistMaterials.hh
Referenced by ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::anorthosite private
Definition at line 73 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 73 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::basalt private
Definition at line 74 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 74 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::copper private
Definition at line 66 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 66 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::dolorite private
Definition at line 68 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 68 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::GaAs private
Definition at line 85 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 85 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::gabbro private
Definition at line 75 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 75 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::gabbroRF private
Definition at line 77 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 77 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::gabbroWD private
Definition at line 76 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 76 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::galactic private
Definition at line 86 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 86 of file XrayFluoNistMaterials.hh
Referenced by ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::hawaiianRF private
Definition at line 72 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 72 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::hawaiianWD private
Definition at line 71 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 71 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::HPGe private
Definition at line 69 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 69 of file XrayFluoNistMaterials.hh
Referenced by ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::icelandicBasalt private
Definition at line 82 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 82 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::icelandicRF private
Definition at line 84 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 84 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::icelandicWD private
Definition at line 83 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 83 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
XrayFluoNistMaterials * XrayFluoNistMaterials::instance = 0 static private
Definition at line 62 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 62 of file XrayFluoNistMaterials.hh
Referenced by GetInstance().
G4Material* XrayFluoNistMaterials::madaBasalt private
Definition at line 81 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 81 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::mars1 private
Definition at line 70 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 70 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4NistManager* XrayFluoNistMaterials::nistMan private
Definition at line 64 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 64 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and GetMaterial().
G4Material* XrayFluoNistMaterials::Sci private
Definition at line 79 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 79 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::SiLi private
Definition at line 67 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 67 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
G4Material* XrayFluoNistMaterials::Vacuum private
Definition at line 80 of file XrayFluoNistMaterials.hh.
View newest version in sPHENIX GitHub at line 80 of file XrayFluoNistMaterials.hh
Referenced by CreateMaterials(), and ~XrayFluoNistMaterials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/include/XrayFluoNistMaterials.hh
geant4/tree/geant4-10.6-release/examples/advanced/xray_fluorescence/src/XrayFluoNistMaterials.cc