ECCE @ EIC Software: cheprep::DefaultHepRepAttribute Class Reference
cheprep::DefaultHepRepAttribute Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepAttribute.h>
Public Member Functions
DefaultHepRepAttribute ()
~DefaultHepRepAttribute ()
std::set
< HEPREP::HepRepAttValue * > getAttValuesFromNode ()
void addAttValue (HEPREP::HepRepAttValue *hepRepAttValue)
void addAttValue (std::string key, char *value, int showLabel)
void addAttValue (std::string key, std::string value, int showLabel)
void addAttValue (std::string key, int value, int showLabel)
void addAttValue (std::string key, int64 value, int showLabel)
void addAttValue (std::string key, double value, int showLabel)
void addAttValue (std::string key, bool value, int showLabel)
void addAttValue (std::string key, std::vector< double > value, int showLabel)
void addAttValue (std::string key, double red, double green, double blue, double alpha, int showLabel)
HEPREP::HepRepAttValue * getAttValueFromNode (std::string lowerCaseName)
HEPREP::HepRepAttValue * removeAttValue (std::string key)
HEPREP::HepRepAttValue * getAttValue (std::string name)=0
Public Member Functions inherited from HEPREP::HepRepAttribute
virtual ~HepRepAttribute ()
Destructor.
Private Attributes
std::map< std::string,
HEPREP::HepRepAttValue * > attValues
Detailed Description
Definition at line 22 of file DefaultHepRepAttribute.h.
View newest version in sPHENIX GitHub at line 22 of file DefaultHepRepAttribute.h
Constructor & Destructor Documentation
cheprep::DefaultHepRepAttribute::DefaultHepRepAttribute ()
Definition at line 20 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 20 of file DefaultHepRepAttribute.cc
cheprep::DefaultHepRepAttribute::~DefaultHepRepAttribute ()
Definition at line 23 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 23 of file DefaultHepRepAttribute.cc
Member Function Documentation
void cheprep::DefaultHepRepAttribute::addAttValue (HEPREP::HepRepAttValue * attValue) virtual
Adds an attValue.
Parameters
attValue to be added.
Implements HEPREP::HepRepAttribute.
Definition at line 37 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 37 of file DefaultHepRepAttribute.cc
References HEPREP::HepRepAttValue::getLowerCaseName().
void cheprep::DefaultHepRepAttribute::addAttValue (std::string key, char * value, int showLabel) virtual
Adds a char* attValue as a String. This call should be mapped to addAttValue(std::string, std::string, int); and necessary because C++ converts char* into bool and would thus call addAttValue(std::string, bool, int) for a call such as addAttValue("drawAs", "Cylinder", 0);
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implements HEPREP::HepRepAttribute.
Definition at line 43 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 43 of file DefaultHepRepAttribute.cc
void cheprep::DefaultHepRepAttribute::addAttValue (std::string key, std::string value, int showLabel) virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implements HEPREP::HepRepAttribute.
Definition at line 47 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 47 of file DefaultHepRepAttribute.cc
void cheprep::DefaultHepRepAttribute::addAttValue (std::string key, int value, int showLabel) virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implements HEPREP::HepRepAttribute.
Definition at line 55 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 55 of file DefaultHepRepAttribute.cc
void cheprep::DefaultHepRepAttribute::addAttValue (std::string key, int64 value, int showLabel) virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implements HEPREP::HepRepAttribute.
Definition at line 51 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 51 of file DefaultHepRepAttribute.cc
void cheprep::DefaultHepRepAttribute::addAttValue (std::string key, double value, int showLabel) virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implements HEPREP::HepRepAttribute.
Definition at line 59 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 59 of file DefaultHepRepAttribute.cc
void cheprep::DefaultHepRepAttribute::addAttValue (std::string key, bool value, int showLabel) virtual
Adds an attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implements HEPREP::HepRepAttribute.
Definition at line 63 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 63 of file DefaultHepRepAttribute.cc
void cheprep::DefaultHepRepAttribute::addAttValue (std::string key, std::vector< double > value, int showLabel) virtual
Adds a Color attValue.
Parameters
key name of attValue
value value of attValue
showLabel show this as label
Implements HEPREP::HepRepAttribute.
Definition at line 67 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 67 of file DefaultHepRepAttribute.cc
void cheprep::DefaultHepRepAttribute::addAttValue (std::string key, double red, double green, double blue, double alpha, int showLabel) virtual
Adds a Color attValue.
Parameters
key name of attValue
red color
green color
blue color
alpha value
showLabel show this as label
Implements HEPREP::HepRepAttribute.
Definition at line 71 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 71 of file DefaultHepRepAttribute.cc
References color().
HEPREP::HepRepAttValue* cheprep::DefaultHepRepAttribute::getAttValue (std::string name) pure virtual
Returns the attValue specified by name. This attValue is normally searched on the node itself and then on its type, moving up the typetree.
Parameters
name of attribute value.
Returns
attribute value.
Implements HEPREP::HepRepAttribute.
Implemented in cheprep::DefaultHepRepInstance, cheprep::DefaultHepRepType, cheprep::DefaultHepRepDefinition, and cheprep::DefaultHepRepPoint.
HepRepAttValue * cheprep::DefaultHepRepAttribute::getAttValueFromNode (std::string lowerCaseName) virtual
Returns a named attribute value from this node.
Parameters
lowerCaseName name in all lowercase.
Returns
corresponding HepRepAttValue.
Implements HEPREP::HepRepAttribute.
Definition at line 80 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 80 of file DefaultHepRepAttribute.cc
References int(), and Acts::Test::transform.
Referenced by cheprep::DefaultHepRepPoint::getAttValue(), and cheprep::DefaultHepRepInstance::getAttValue().
set< HepRepAttValue * > cheprep::DefaultHepRepAttribute::getAttValuesFromNode () virtual
Returns a collection of all attribute values from this node.
Returns
collection of HepRepAttValues.
Implements HEPREP::HepRepAttribute.
Definition at line 29 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 29 of file DefaultHepRepAttribute.cc
HepRepAttValue * cheprep::DefaultHepRepAttribute::removeAttValue (std::string key) virtual
Remove the attvalue named by key.
Parameters
key name of the attValue to be removed.
Returns
removed HepRepAttValue, or null if not removed.
Implements HEPREP::HepRepAttribute.
Definition at line 86 of file DefaultHepRepAttribute.cc.
View newest version in sPHENIX GitHub at line 86 of file DefaultHepRepAttribute.cc
References int(), and Acts::Test::transform.
Member Data Documentation
std::map<std::string, HEPREP::HepRepAttValue*> cheprep::DefaultHepRepAttribute::attValues private
Definition at line 25 of file DefaultHepRepAttribute.h.
View newest version in sPHENIX GitHub at line 25 of file DefaultHepRepAttribute.h
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepAttribute.h
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/DefaultHepRepAttribute.cc