ECCE @ EIC Software: GVFlashHomoShowerTuning Class Reference
GVFlashHomoShowerTuning Class Reference
#include <geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GVFlashHomoShowerTuning.hh>
Public Member Functions
GVFlashHomoShowerTuning ()
virtual ~GVFlashHomoShowerTuning ()
virtual G4double ParAveT1 ()
virtual G4double ParAveA1 ()
virtual G4double ParAveA2 ()
virtual G4double ParAveA3 ()
virtual G4double ParSigLogT1 ()
virtual G4double ParSigLogT2 ()
virtual G4double ParSigLogA1 ()
virtual G4double ParSigLogA2 ()
virtual G4double ParRho1 ()
virtual G4double ParRho2 ()
virtual G4double ParRC1 ()
virtual G4double ParRC2 ()
virtual G4double ParRC3 ()
virtual G4double ParRC4 ()
virtual G4double ParRT1 ()
virtual G4double ParRT2 ()
virtual G4double ParRT3 ()
virtual G4double ParRT4 ()
virtual G4double ParRT5 ()
virtual G4double ParRT6 ()
virtual G4double ParWC1 ()
virtual G4double ParWC2 ()
virtual G4double ParWC3 ()
virtual G4double ParWC4 ()
virtual G4double ParWC5 ()
virtual G4double ParWC6 ()
virtual G4double ParSpotN1 ()
virtual G4double ParSpotN2 ()
virtual G4double ParSpotT1 ()
virtual G4double ParSpotT2 ()
virtual G4double ParSpotA1 ()
virtual G4double ParSpotA2 ()
Detailed Description
Definition at line 63 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 63 of file GVFlashHomoShowerTuning.hh
Constructor & Destructor Documentation
GVFlashHomoShowerTuning::GVFlashHomoShowerTuning () inline
Definition at line 66 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 66 of file GVFlashHomoShowerTuning.hh
virtual GVFlashHomoShowerTuning::~GVFlashHomoShowerTuning () inline virtual
Definition at line 67 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 67 of file GVFlashHomoShowerTuning.hh
Member Function Documentation
virtual G4double GVFlashHomoShowerTuning::ParAveA1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 72 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 72 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParAveA2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 73 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 73 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParAveA3 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 74 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 74 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParAveT1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 71 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 71 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRC1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 94 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 94 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRC2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 95 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 95 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRC3 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 96 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 96 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRC4 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 97 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 97 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRho1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 84 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 84 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRho2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 85 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 85 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRT1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 102 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 102 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRT2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 103 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 103 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRT3 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 104 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 104 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRT4 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 105 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 105 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRT5 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 106 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 106 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParRT6 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 107 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 107 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSigLogA1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 80 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 80 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSigLogA2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 81 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 81 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSigLogT1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 76 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 76 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSigLogT2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 77 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 77 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSpotA1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 141 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 141 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSpotA2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 142 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 142 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSpotN1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 123 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 123 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSpotN2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 124 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 124 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSpotT1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 138 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 138 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParSpotT2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 139 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 139 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParWC1 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 112 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 112 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParWC2 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 113 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 113 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParWC3 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 114 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 114 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParWC4 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 115 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 115 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParWC5 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 116 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 116 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
virtual G4double GVFlashHomoShowerTuning::ParWC6 () inline virtual
Reimplemented in ExGflashHomoShowerTuning.
Definition at line 117 of file GVFlashHomoShowerTuning.hh.
View newest version in sPHENIX GitHub at line 117 of file GVFlashHomoShowerTuning.hh
Referenced by GFlashHomoShowerParameterisation::GFlashHomoShowerParameterisation(), and GFlashSamplingShowerParameterisation::GFlashSamplingShowerParameterisation().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/parameterisations/gflash/include/GVFlashHomoShowerTuning.hh