ECCE @ EIC Software: Acts::VectorHelpers Namespace Reference
Acts::VectorHelpers Namespace Reference
Namespaces
namespace detail
Functions
template<typename Derived >
double phi (const Eigen::MatrixBase< Derived > &v) noexcept
template<typename T , std::enable_if_t< detail::has_phi_method< T >::value, int > = 0>
double phi (const T &v) noexcept
template<typename Derived >
double perp (const Eigen::MatrixBase< Derived > &v) noexcept
template<typename Derived >
double theta (const Eigen::MatrixBase< Derived > &v) noexcept
template<typename Derived >
double eta (const Eigen::MatrixBase< Derived > &v) noexcept
static double cast (const Vector3D &position, BinningValue bval)
ActsMatrixD< 3, 3 > cross (const ActsMatrixD< 3, 3 > &m, const Vector3D &v)
Calculates column-wise cross products of a matrix and a vector and stores the result column-wise in a matrix.
ParValue_t & time (SpacePointVector &spacePointVec)
Access to the time component of input parameter.
const ParValue_t & time (const SpacePointVector &spacePointVec)
Const overload access to the time component of input parameter.
ParValue_t & time (BoundVector &boundVec)
Access to the time component of input parameter.
const ParValue_t & time (const BoundVector &boundVec)
Const overload access to the time component of input parameter.
ParValue_t & time (FreeVector &freeVec)
Access to the time component of input parameter.
const ParValue_t & time (const FreeVector &freeVec)
Const overload access to the time component of input parameter.
auto position (SpacePointVector &spacePointVec)
Access to the position components of input parameter.
auto position (const SpacePointVector &spacePointVec)
Const overload access to the position components of input parameter.
auto position (FreeVector &freeVec)
Access to the position components of input parameter.
auto position (const FreeVector &freeVec)
Const overload access to the position components of input parameter.
Detailed Description
EventPrimitvesToStringConverter
inline methods for conversion of EventPrimitives (Matrix) to std::string.
This is to enhance formatted screen ouput and for ASCII based testing.
The offset can be used to offset the lines (starting from line 2) wrt to the zero position for formatting reasons.
Function Documentation
static double Acts::VectorHelpers::cast (const Vector3D & position, BinningValue bval) static
Helper method to cast out the binning value from a 3D Vector
For this method a 3D vector is required to guarantee all potential binning values
Definition at line 171 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 171 of file Helpers.hpp
References Acts::binEta, Acts::binH, Acts::binMag, Acts::binPhi, Acts::binR, eta(), perp(), phi(), and theta().
Referenced by Acts::GeometryObject::binningPositionValue(), and Acts::Extent::check().
ActsMatrixD<3, 3> Acts::VectorHelpers::cross (const ActsMatrixD< 3, 3 > & m, const Vector3D & v) inline
Calculates column-wise cross products of a matrix and a vector and stores the result column-wise in a matrix.
Parameters
[in] m Matrix that will be used for cross products
[in] v Vector for cross products
Returns
Constructed matrix
Definition at line 200 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 200 of file Helpers.hpp
References r.
Referenced by CylindricalHough::addHits(), G4ReduciblePolygon::BisectedBy(), Acts::Test::BOOST_AUTO_TEST_CASE(), G4CrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDCrossSectionHandler::BuildCrossSectionsForMaterials(), G4RDeIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4eIonisationCrossSectionHandler::BuildCrossSectionsForMaterials(), G4PixeCrossSectionHandler::BuildCrossSectionsForMaterials(), G4LowEnergyIonisation::BuildLossTable(), HelixHoughFuncs_v1::calculate_phi_range(), G4Tet::CheckDegeneracy(), G4PenelopeRayleighModel::ComputeCrossSectionPerAtom(), G4eplusTo3GammaOKVIModel::ComputeCrossSectionPerAtom(), G4eplusTo2GammaOKVIModel::ComputeCrossSectionPerAtom(), G4PenelopePhotoElectricModel::ComputeCrossSectionPerAtom(), G4LDMBremModel::ComputeCrossSectionPerAtom(), G4eeToTwoGammaModel::ComputeCrossSectionPerAtom(), G4WentzelVIRelModel::ComputeCrossSectionPerAtom(), G4EmMultiModel::ComputeCrossSectionPerAtom(), G4AtimaEnergyLossModel::ComputeCrossSectionPerAtom(), G4mplIonisationWithDeltaModel::ComputeCrossSectionPerAtom(), G4eBremParametrizedModel::ComputeCrossSectionPerAtom(), G4eSingleCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4hCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4WentzelVIModel::ComputeCrossSectionPerAtom(), G4IonCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4MuPairProductionModel::ComputeCrossSectionPerAtom(), G4ICRU73QOModel::ComputeCrossSectionPerAtom(), G4MuBetheBlochModel::ComputeCrossSectionPerAtom(), G4MuBremsstrahlungModel::ComputeCrossSectionPerAtom(), G4eCoulombScatteringModel::ComputeCrossSectionPerAtom(), G4eplusTo3GammaOKVIModel::ComputeCrossSectionPerElectron(), G4eplusTo2GammaOKVIModel::ComputeCrossSectionPerElectron(), G4eeToTwoGammaModel::ComputeCrossSectionPerElectron(), G4AtimaEnergyLossModel::ComputeCrossSectionPerElectron(), G4mplIonisationWithDeltaModel::ComputeCrossSectionPerElectron(), G4MollerBhabhaModel::ComputeCrossSectionPerElectron(), G4LindhardSorensenIonModel::ComputeCrossSectionPerElectron(), G4BetheBlochModel::ComputeCrossSectionPerElectron(), G4ICRU73QOModel::ComputeCrossSectionPerElectron(), G4MuBetheBlochModel::ComputeCrossSectionPerElectron(), G4BraggIonModel::ComputeCrossSectionPerElectron(), G4BraggModel::ComputeCrossSectionPerElectron(), G4hPairProductionModel::ComputeDMicroscopicCrossSection(), G4MuPairProductionModel::ComputeDMicroscopicCrossSection(), G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom(), G4eBremParametrizedModel::ComputeDXSectionPerAtom(), G4VEmModel::ComputeMeanFreePath(), G4MuBremsstrahlungModel::ComputeMicroscopicCrossSection(), G4MuPairProductionModel::ComputeMicroscopicCrossSection(), G4WentzelVIModel::ComputeTrueStepLength(), G4eBremParametrizedModel::ComputeXSectionPerAtom(), G4BoundingEnvelope::CreateListOfPlanes(), G4GenericTrap::CreateTessellatedSolid(), G4AngularDistribution::Cross(), G4LivermoreIonisationCrossSection::CrossSection(), G4PenelopeIonisationCrossSection::CrossSection(), G4eeCrossSections::CrossSection2Kcharged(), G4eeCrossSections::CrossSection2Kneutral(), G4eeCrossSections::CrossSection2pi(), G4eeCrossSections::CrossSection3pi(), G4eeCrossSections::CrossSectionEtaG(), G4PAIPhotData::CrossSectionPerVolume(), G4PAIModelData::CrossSectionPerVolume(), G4eplusTo3GammaOKVIModel::CrossSectionPerVolume(), G4eplusTo2GammaOKVIModel::CrossSectionPerVolume(), G4eeToTwoGammaModel::CrossSectionPerVolume(), G4AtimaEnergyLossModel::CrossSectionPerVolume(), G4ICRU73QOModel::CrossSectionPerVolume(), G4MuBetheBlochModel::CrossSectionPerVolume(), G4IonParametrisedLossModel::CrossSectionPerVolume(), G4VEmModel::CrossSectionPerVolume(), G4VEmProcess::CrossSectionPerVolume(), G4VEnergyLossProcess::CrossSectionPerVolume(), G4eeCrossSections::CrossSectionPi0G(), Acts::Frustum< value_t, DIM, SIDES >::draw(), HistoManager::EndOfRun(), export_G4ThreeVector(), G4EmModelManager::FillLambdaVector(), G4HadElementSelector::G4HadElementSelector(), G4QuadrangularFacet::G4QuadrangularFacet(), G4Tet::G4Tet(), kdfinder::Helix< T >::geometricSignedDistance(), G4HadronicProcessStore::GetCaptureCrossSectionPerAtom(), G4HadronicProcessStore::GetCaptureCrossSectionPerVolume(), G4ComponentSAIDTotalXS::GetChargeExchangeCrossSection(), G4HadronicProcessStore::GetChargeExchangeCrossSectionPerAtom(), G4HadronicProcessStore::GetChargeExchangeCrossSectionPerVolume(), PHSiliconTpcTrackMatching::getCrossingNumber(), G4eIonisationCrossSectionHandler::GetCrossSectionAboveThresholdForElement(), G4HadronicProcessStore::GetCrossSectionPerAtom(), G4HadronicProcessStore::GetCrossSectionPerVolume(), G4HadronicProcessStore::GetElasticCrossSectionPerAtom(), G4HadronicProcessStore::GetElasticCrossSectionPerVolume(), G4ComponentSAIDTotalXS::GetElasticIsotopeCrossSection(), G4BGGNucleonElasticXS::GetElementCrossSection(), G4BGGNucleonInelasticXS::GetElementCrossSection(), G4BGGPionElasticXS::GetElementCrossSection(), G4BGGPionInelasticXS::GetElementCrossSection(), G4GenericTrap::GetFaceCubicVolume(), G4GenericTrap::GetFaceSurfaceArea(), G4HadronicProcessStore::GetFissionCrossSectionPerAtom(), G4HadronicProcessStore::GetFissionCrossSectionPerVolume(), G4VXTRenergyLoss::GetGasLinearPhotoAbs(), G4HadronicProcessStore::GetInelasticCrossSectionPerAtom(), G4HadronicProcessStore::GetInelasticCrossSectionPerVolume(), G4ComponentSAIDTotalXS::GetInelasticIsotopeCrossSection(), G4BGGNucleonInelasticXS::GetIsoCrossSection(), G4BGGNucleonElasticXS::GetIsoCrossSection(), G4BGGPionElasticXS::GetIsoCrossSection(), G4BGGPionInelasticXS::GetIsoCrossSection(), G4LowEnergyPhotoElectric::GetMeanFreePath(), G4StrawTubeXTRadiator::GetMediumLinearPhotoAbs(), G4PAIPhotData::GetPlasmonRatio(), G4VXTRenergyLoss::GetPlateLinearPhotoAbs(), G4PenelopePhotoElectricModel::GetShellCrossSection(), HepPolyhedron::GetSurfaceArea(), HepPolyhedron::GetUnitNormal(), HepPolyhedron::GetVolume(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), G4EmElementSelector::Initialise(), G4LivermoreGammaConversionModel::InitialiseProbability(), G4Tet::Initialize(), Acts::LineSurface::initJacobianToGlobal(), G4GenericTrap::InsidePolygone(), G4GeomTools::IsConvex(), G4GenericTrap::IsSegCrossingZ(), Acts::DefaultExtension::k(), Acts::DenseEnvironmentExtension::k(), G4Ellipsoid::LateralSurfaceArea(), main(), G4GenericTrap::MakeDownFacet(), G4ExtrudedSolid::MakeDownFacet(), G4Trap::MakePlane(), G4GenericTrap::MakeUpFacet(), G4ExtrudedSolid::MakeUpFacet(), G4PixeCrossSectionHandler::MicroscopicCrossSection(), G4GenericTrap::NormalToPlane(), G4DNAMillerGreenExcitationModel::PartialCrossSection(), HepGeom::Plane3D< G4double >::Plane3D(), G4GeomTools::QuadAreaNormal(), G4DNAScreenedRutherfordElasticModel::RutherfordCrossSection(), G4DNAUeharaScreenedRutherfordElasticModel::RutherfordCrossSection(), G4BetheHeitler5DModel::SampleSecondaries(), G4EmMultiModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4CrossSectionDataStore::SampleZandA(), G4RDVCrossSectionHandler::SelectRandomAtom(), G4VCrossSectionHandler::SelectRandomAtom(), G4PixeCrossSectionHandler::SelectRandomAtom(), G4RDVCrossSectionHandler::SelectRandomElement(), G4VCrossSectionHandler::SelectRandomElement(), G4Tet::SetVertices(), G4EnclosingCylinder::ShouldMiss(), G4GenericTrap::SurfaceNormal(), Acts::Frustum< value_t, DIM, SIDES >::svg(), G4GammaGeneralProcess::TotalCrossSectionPerVolume(), Acts::DefaultExtension::transportMatrix(), Acts::DenseEnvironmentExtension::transportMatrix(), and G4GeomTools::TriangleAreaNormal().
template<typename Derived > double Acts::VectorHelpers::eta (const Eigen::MatrixBase< Derived > & v) noexcept
Calculate the pseudorapidity for a vector.
Template Parameters
Derived Eigen derived concrete type
Parameters
v Any vector like Eigen type, static or dynamic
Note
Will static assert that the number of rows of v is at least 3, or in case of dynamic size, will abort execution if that is not the case.
Returns
The pseudorapidity value
Definition at line 150 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 150 of file Helpers.hpp
References v.
Referenced by AddFlowToParent(), G4AtimaEnergyLossModel::Bethek_dedx_e(), Acts::Test::BOOST_AUTO_TEST_CASE(), BOOST_DATA_TEST_CASE(), G4QMDReaction::calcOffSetOfCollision(), cast(), PHTruthTrackSeeding::circleFitSeed(), PHActsSiliconSeeding::circleFitSeed(), G4PairProductionRelModel::ComputeCrossSectionPerAtom(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), G4INCL::CoulombNonRelativistic::distortOut(), dRICH(), CCaloOrganization::energyInMatrix(), Acts::SingleTrackParameters< ChargedPolicy >::eta(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNElastic(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiN(), G4INCL::CrossSectionsMultiPionsAndResonances::etaNToPiPiN(), QAG4SimulationCalorimeterSum::eval_trk_proj(), FW::PrintParticles::execute(), FW::TrackSelector::execute(), FW::ParticleSelector::execute(), G4LivermoreGammaConversionModelRC::fbeta(), G4BetaDecayCorrections::FermiFunction(), FW::EffPlotTool::fill(), FW::FakeRatePlotTool::fill(), FW::TrackSummaryPlotTool::fill(), FW::ResPlotTool::fill(), G4INCL::EtaNToPiNChannel::fillFinalState(), G4INCL::EtaNElasticChannel::fillFinalState(), G4INCL::EtaNToPiPiNChannel::fillFinalState(), G4INCL::NNEtaToMultiPionsChannel::fillFinalState(), G4INCL::NDeltaEtaProductionChannel::fillFinalState(), JetEvaluator::fillOutputNtuples(), CaloEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), flowAfterburner(), fullMaterial(), CCalPrimaryGeneratorAction::GeneratePrimaries(), PHG4Utils::get_eta(), PHG4InputFilter::get_eta(), RawTowerGeomv1::get_eta(), RawTowerGeomv4::get_eta(), RawTowerGeomv2::get_eta(), RawTowerZDCGeomv1::get_eta(), RawTowerGeomv3::get_eta(), PHG4Utils::get_etaphi(), TowerJetInput::get_input(), TruthJetInput::get_input(), G4SynchrotronRadiationInMat::GetAngleK(), ECCEdRICHFastPIDMap::getFastSmearLogLikelihood(), CCaloOrganization::getUnitWithMaxEnergy(), hijfst_(), TowerBackgroundv1::identify(), RawTowerDeadMapLoader::InitRun(), G4EmCorrections::KShell(), G4EmCorrections::KShellCorrection(), CaloCalibEmc_Pi0::Loop(), G4EmCorrections::LShell(), G4EmCorrections::LShellCorrection(), PHActsTrackProjection::makeCaloSurfacePtrs(), momentumDistributions(), Acts::ObjectSorterT< Vector3D >::operator()(), FW::ParametricProcessGenerator::operator()(), Acts::DistanceSorterT< T >::operator()(), printHits(), PHG4InputFilter::process_event(), PHG4ParticleGenerator::process_event(), PHG4ParticleGenerator_flat_pT::process_event(), PHG4ParticleGeneratorD0::process_event(), RawTowerZDCCalibration::process_event(), RawTowerCalibration::process_event(), PHHepMCParticleSelectorDecayProductChain::process_event(), RawTowerDigitizer::process_event(), RawTowerZDCDigitizer::process_event(), G4CellNtuple::process_event(), G4TowerNtuple::process_event(), PHG4SimpleEventGenerator::process_event(), PHG4ParticleGeneratorVectorMeson::process_event(), SubtractTowersCS::process_event(), SubtractTowers::process_event(), RetowerCEMC::process_event(), DetermineTowerBackground::process_event(), TPCDataStreamEmulator::process_event(), PHGenFitTrackProjection::process_event(), LiteCaloEval::process_event(), RawTowerCombiner::process_event(), CaloAna::process_towers(), G4ErrorFreeTrajState::PropagateErrorIoni(), FW::Options::readParticleGunOptions(), RUNME(), G4GoudsmitSaundersonMscModel::SampleMSC(), CaloTriggerInfov1::set_best2_EMCal_4x4_eta(), CaloTriggerInfov1::set_best_EMCal_2x2_eta(), CaloTriggerInfov1::set_best_EMCal_4x4_eta(), CaloTriggerInfov1::set_best_FullCalo_0p2x0p2_eta(), CaloTriggerInfov1::set_best_FullCalo_0p4x0p4_eta(), CaloTriggerInfov1::set_best_FullCalo_0p6x0p6_eta(), CaloTriggerInfov1::set_best_FullCalo_0p8x0p8_eta(), CaloTriggerInfov1::set_best_FullCalo_1p0x1p0_eta(), PHG4Reco::set_rapidity_coverage(), PHSartreParticleTrigger::SetAbsEtaHigh(), PHPy8ParticleTrigger::SetAbsEtaHigh(), PHPy6ParticleTrigger::SetAbsEtaHigh(), PHSartreParticleTrigger::SetAbsEtaLow(), PHPy8ParticleTrigger::SetAbsEtaLow(), PHPy6ParticleTrigger::SetAbsEtaLow(), G4SynchrotronRadiationInMat::SetEta(), PHSartreParticleTrigger::SetEtaHigh(), PHPy8ParticleTrigger::SetEtaHigh(), PHPy6ParticleTrigger::SetEtaHigh(), PHSartreParticleTrigger::SetEtaLow(), PHPy8ParticleTrigger::SetEtaLow(), PHPy6ParticleTrigger::SetEtaLow(), PHG4Utils::SetPseudoRapidityCoverage(), G4BetaDecayCorrections::ShapeFactor(), G4EmCorrections::ShellCorrection(), Acts::BinningData::value(), ActsEvaluator::visitTrackStates(), FW::RootParticleWriter::writeT(), FW::RootTrajectoryWriter::writeT(), and FW::RootMaterialTrackWriter::writeT().
template<typename Derived > double Acts::VectorHelpers::perp (const Eigen::MatrixBase< Derived > & v) noexcept
Calculate radius in the transverse (xy) plane of a vector
Template Parameters
Derived Eigen derived concrete type
Parameters
v Any vector like Eigen type, static or dynamic
Note
Will static assert that the number of rows of v is at least 2, or in case of dynamic size, will abort execution if that is not the case.
Returns
The transverse radius value.
Definition at line 103 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 103 of file Helpers.hpp
References v.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_FIXTURE_TEST_CASE(), cast(), Acts::LayerCreator::checkBinning(), Acts::IntegrationTest::constant_field_propagation(), PHG4InnerHcalDetector::ConstructScintillatorBox(), PHG4OuterHcalDetector::ConstructScintillatorBox(), PHG4InnerHcalDetector::ConstructSteelPlate(), PHG4OuterHcalDetector::ConstructSteelPlate(), Acts::detail::PointwiseMaterialInteraction::covarianceContributions(), Acts::SurfaceArrayCreator::createVariableAxis(), Acts::EllipseBounds::distanceToBoundary(), FW::ParticleSelector::execute(), FW::TruthVerticesToTracksAlgorithm::execute(), FW::PropagationAlgorithm< propagator_t >::executeTest(), Acts::fieldMapperRZ(), FW::TrackSummaryPlotTool::fill(), FW::ResPlotTool::fill(), FastJetAlgoSub::get_jets(), FastJetAlgo::get_jets(), Acts::SolenoidBField::getField(), G4PolarizationHelper::GetParticleFrameX(), G4PolarizationHelper::GetSpinInPRF(), Acts::ConeSurface::globalToLocal(), Acts::CylinderSurface::globalToLocal(), Acts::LineSurface::globalToLocal(), Acts::globalToLocalFromBin(), Acts::CutoutCylinderVolumeBounds::inside(), Acts::CylinderVolumeBounds::inside(), Acts::CylinderBounds::inside3D(), Acts::SurfaceArrayCreator::isSurfaceEquivalent(), Acts::materialMapperRZ(), Acts::ProtoLayer::measure(), Acts::ObjectSorterT< Vector3D >::operator()(), Acts::Test::PerpendicularMeasure::operator()(), Acts::Test::SurfaceObserver< Surface >::operator()(), Acts::DistanceSorterT< T >::operator()(), G4OpWLS::PostStepDoIt(), G4Scintillation::PostStepDoIt(), PHHepMCParticleSelectorDecayProductChain::process_event(), Acts::SingleTrackParameters< ChargedPolicy >::pT(), FW::RootBFieldWriter< bfield_t >::run(), Acts::solenoidFieldMapper(), Acts::SurfaceArrayCreator::surfaceArrayOnDisc(), CCalSteppingAction::UserSteppingAction(), Acts::BinningData::value(), FW::RootParticleWriter::writeT(), and FW::RootTrajectoryWriter::writeT().
template<typename Derived > double Acts::VectorHelpers::phi (const Eigen::MatrixBase< Derived > & v) noexcept
Calculate phi (transverse plane angle) from compatible Eigen types
Template Parameters
Derived Eigen derived concrete type
Parameters
v Any vector like Eigen type, static or dynamic
Note
Will static assert that the number of rows of v is at least 2, or in case of dynamic size, will abort execution if that is not the case.
Returns
The value of the angle in the transverse plane.
Definition at line 67 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 67 of file Helpers.hpp
References v.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), cast(), Acts::TGeoDetectorElement::construct(), Acts::detail::differenceOfClustersChecked(), Acts::AnnulusBounds::distanceToBoundary(), FW::PrintParticles::execute(), FW::ParticleSelector::execute(), FW::ResPlotTool::fill(), Acts::Frustum< value_t, DIM, SIDES >::Frustum(), Acts::globalToLocalFromBin(), Acts::EllipseBounds::inside(), Acts::CutoutCylinderVolumeBounds::inside(), Acts::CylinderVolumeBounds::inside(), Acts::ObjectSorterT< Vector3D >::operator()(), Acts::Test::CylindricalTrackingGeometry::operator()(), Acts::DistanceSorterT< T >::operator()(), Acts::ConeSurface::pathCorrection(), Acts::AnnulusBounds::stripXYToModulePC(), Acts::BinningData::value(), Acts::AnnulusBounds::vertices(), and FW::RootParticleWriter::writeT().
template<typename T , std::enable_if_t< detail::has_phi_method< T >::value, int > = 0> double Acts::VectorHelpers::phi (const T & v) noexcept
Calculate phi (transverse plane angle) from anything implementing a method like phi() returing anything convertible to double.
Template Parameters
T anything that has a phi method
Parameters
v Any type that implements a phi method
Returns
The phi value
Definition at line 92 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 92 of file Helpers.hpp
References v.
auto Acts::VectorHelpers::position (SpacePointVector & spacePointVec) inline
Access to the position components of input parameter.
Parameters
spacePointVec The SpacePointVector
Returns
Reference to the position components
Definition at line 264 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 264 of file Helpers.hpp
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::Vertex< input_track_t >::position(), Acts::Vertex< input_track_t >::setPosition(), and Acts::Vertex< input_track_t >::Vertex().
auto Acts::VectorHelpers::position (const SpacePointVector & spacePointVec) inline
Const overload access to the position components of input parameter.
Parameters
spacePointVec The SpacePointVector
Returns
Reference to the position components
Definition at line 273 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 273 of file Helpers.hpp
auto Acts::VectorHelpers::position (FreeVector & freeVec) inline
Access to the position components of input parameter.
Parameters
freeVec The SpacePointVector
Returns
Reference to the position components
Definition at line 282 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 282 of file Helpers.hpp
auto Acts::VectorHelpers::position (const FreeVector & freeVec) inline
Const overload access to the position components of input parameter.
Parameters
freeVec The SpacePointVector
Returns
Reference to the position components
Definition at line 291 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 291 of file Helpers.hpp
template<typename Derived > double Acts::VectorHelpers::theta (const Eigen::MatrixBase< Derived > & v) noexcept
Calculate the theta angle (longitudinal w.r.t. z axis) of a vector
Template Parameters
Derived Eigen derived concrete type
Parameters
v Any vector like Eigen type, static or dynamic
Note
Will static assert that the number of rows of v is at least 3, or in case of dynamic size, will abort execution if that is not the case.
Returns
The theta value
Definition at line 127 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 127 of file Helpers.hpp
References v.
Referenced by Acts::Test::BOOST_AUTO_TEST_CASE(), cast(), Acts::detail::differenceOfClustersChecked(), and FW::ResPlotTool::fill().
ParValue_t& Acts::VectorHelpers::time (SpacePointVector & spacePointVec) inline
Access to the time component of input parameter.
Parameters
spacePointVec The SpacePointVector
Returns
Reference to the time component
Definition at line 213 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 213 of file Helpers.hpp
Referenced by G4MoleculeCounter::AddAMoleculeAtTime(), G4CollisionManager::AddCollision(), EventAction::AddEdep(), G4MoleculeGun::AddMolecule(), G4MoleculeGun::AddMoleculeInCMRepresentation(), G4MoleculeGun::AddMoleculesRandomPositionInBox(), G4MoleculeGun::AddNMolecules(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4eLowEnergyLoss::AlongStepDoIt(), G4BinaryLightIonReaction::ApplyYourself(), G4ParticleHPFissionFS::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4LENDFission::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4PreCompoundModel::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), F04RunAction::BeginOfRunAction(), WLSRunAction::BeginOfRunAction(), UltraRunAction::BeginOfRunAction(), Acts::Test::BOOST_AUTO_TEST_CASE(), Acts::IntegrationTest::BOOST_DATA_TEST_CASE(), Acts::Test::BOOST_DATA_TEST_CASE(), Acts::detail::boundState(), G4FermiBreakUpVI::BreakFragment(), G4UnstableFragmentBreakUp::BreakUpChain(), Acts::Test::consistencyCheck(), Acts::IntegrationTest::covariance_bound(), Acts::IntegrationTest::covariance_curvilinear(), Acts::detail::curvilinearState(), STCyclotronRun::DecayIsotopeCountTarget(), G4VFieldModel::DescribeYourselfTo(), DMXEventAction::EndOfEventAction(), G4Abla::evap_postsaddle(), Run::EventTiming(), FW::ParticleSmearing::execute(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), Acts::IntegrationTest::foward_backward(), G4CollisionInitialState::G4CollisionInitialState(), G4DNAIndirectHit::G4DNAIndirectHit(), G4fissionEvent::G4fissionEvent(), generate_hash_secret_salt(), G4INCL::StandardPropagationModel::generateAllAvatars(), G4PhotonEvaporation::GenerateGamma(), G4WLSTimeGeneratorProfileExponential::GenerateTime(), pyG4MagneticField::CB_PyG4MagneticField::GetFieldValue(), G4EnergyLossTables::GetLabTime(), testEventiterator::getNextEvent(), G4EnergyLossTables::GetProperTime(), G4INCL::StandardPropagationModel::getReflectionTime(), G4INCL::StandardPropagationModel::getTime(), G4MesonAbsorption::GetTimeToAbsorption(), G4Scatterer::GetTimeToInteraction(), main(), STCyclotronRun::Merge(), noise(), Acts::Logging::TimedOutputDecorator::now(), G4VisCommandSceneAddDate::Date::operator()(), Par02Smearer::Par02Smearer(), PHTimeStamp::PHTimeStamp(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), ospEvent::prepare_next(), oEvent::prepare_next(), STCyclotronRun::PrimaryIsotopeCountTarget(), G4MCTSimVertex::Print(), HepMCNodeReader::process_event(), ScreenSD::ProcessHits(), ProcessSingleFile(), prt_createDir(), cheprep::ZipOutputStreamBuffer::putNextEntry(), RawTowerv1::RawTowerv1(), RawTowerZDCv1::RawTowerZDCv1(), FW::CsvPlanarClusterReader::read(), G4MoleculeCounter::RemoveAMoleculeAtTime(), G4FissionLibrary::SampleMult(), G4Abla::secnds(), G4Fragment::SetCreationTime(), WLSPrimaryGeneratorAction::SetDecayTimeConstant(), G4GMocrenIO::setID(), STCyclotronRunAction::SetIrradiationTime(), WLSPrimaryGeneratorAction::SetOptPhotonTime(), Acts::Vertex< input_track_t >::setPosition(), SetSeed(), G4INCL::StandardPropagationModel::setStoppingTime(), Acts::Vertex< input_track_t >::setTime(), G4Scheduler::SetTimeTolerance(), PHTimeStamp::setToSystemTime(), FW::HepMC3Event::shiftPositionTo(), testEventiterator::testEventiterator(), Acts::Vertex< input_track_t >::time(), FW::HepMC3Vertex::time(), Acts::IntegrationTest::to_cylinder(), Acts::IntegrationTest::to_surface(), Acts::EigenStepper< bfield_t, extensionlist_t, auctioneer_t >::update(), Acts::AtlasStepper< ConstantBField >::update(), update_process(), G4INCL::StandardPropagationModel::updateAvatars(), TrackingAction::UpdateTrackInfo(), CCalSteppingAction::UserSteppingAction(), PHParametersContainer::WriteToFile(), PdbParameterMapContainer::WriteToFile(), PHParameters::WriteToFile(), and ScoreSpecies::WriteWithAnalysisManager().
const ParValue_t& Acts::VectorHelpers::time (const SpacePointVector & spacePointVec) inline
Const overload access to the time component of input parameter.
Parameters
spacePointVec The SpacePointVector
Returns
Reference to the time component
Definition at line 222 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 222 of file Helpers.hpp
ParValue_t& Acts::VectorHelpers::time (BoundVector & boundVec) inline
Access to the time component of input parameter.
Parameters
boundVec The BoundVector
Returns
Reference to the time component
Definition at line 230 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 230 of file Helpers.hpp
References Acts::eT.
const ParValue_t& Acts::VectorHelpers::time (const BoundVector & boundVec) inline
Const overload access to the time component of input parameter.
Parameters
boundVec The BoundVector
Returns
Reference to the time component
Definition at line 239 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 239 of file Helpers.hpp
References Acts::eT.
ParValue_t& Acts::VectorHelpers::time (FreeVector & freeVec) inline
Access to the time component of input parameter.
Parameters
freeVec The FreeVector
Returns
Reference to the time component
Definition at line 247 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 247 of file Helpers.hpp
const ParValue_t& Acts::VectorHelpers::time (const FreeVector & freeVec) inline
Const overload access to the time component of input parameter.
Parameters
freeVec The FreeVector
Returns
Reference to the time component
Definition at line 256 of file Helpers.hpp.
View newest version in sPHENIX GitHub at line 256 of file Helpers.hpp