ECCE @ EIC Software: G4VHit Class Reference
G4VHit Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4VHit.hh>
Inherited by B2TrackerHit, B2TrackerHit, B2TrackerHit, B4cCalorHit, B5DriftChamberHit, B5EmCalorimeterHit, B5HadCalorimeterHit, B5HodoscopeHit, CCalG4Hit, DMXPmtHit, DMXScintHit, eRositaTrackerHit, ExGflashHit, ExGflashHit, ExGflashHit, ExGflashHit, ExN02TrackerHit, ExN04CalorimeterHit, ExN04CalorimeterHit, ExN04MuonHit, ExN04MuonHit, ExN04TrackerHit, ExN04TrackerHit, ExP01TrackerHit, ExTGTrackerHit, F01CalorHit, F02CalorHit, F03CalorHit, FCALCalorHit, G4HumanPhantomHit, GammaRayTelAnticoincidenceHit, GammaRayTelCalorimeterHit, GammaRayTelTrackerHit, H02MuonHit, HadrontherapyDetectorHit, LXePMTHit, LXeScintHit, Par01CalorimeterHit, RE01CalorimeterHit, RE01TrackerHit, RE05CalorimeterHit, RE05MuonHit, RE05TrackerHit, RMC01DoubleWithWeightHit, SensitiveDetectorHit, SensitiveDetectorHit, TrackerHit, TrackerHit, UltraOpticalHit, WLSPhotonDetHit, XAluminumElectrodeHit, and XrayFluoSensorHit.
Public Member Functions
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual void Draw ()
virtual void Print ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Detailed Description
Definition at line 47 of file G4VHit.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VHit.hh
Constructor & Destructor Documentation
G4VHit::G4VHit ()
Definition at line 33 of file G4VHit.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VHit.cc
G4VHit::~G4VHit () virtual
Definition at line 36 of file G4VHit.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VHit.cc
Member Function Documentation
virtual std::vector<G4AttValue>* G4VHit::CreateAttValues () const inline virtual
Reimplemented in B5DriftChamberHit, B5EmCalorimeterHit, B5HadCalorimeterHit, B5HodoscopeHit, XAluminumElectrodeHit, RE05CalorimeterHit, RE01CalorimeterHit, SensitiveDetectorHit, RE05MuonHit, RE05TrackerHit, and RE01TrackerHit.
Definition at line 66 of file G4VHit.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VHit.hh
Referenced by G4HepRepSceneHandler::addAttributes(), G4HepRepFileSceneHandler::AddCompound(), G4GMocrenFileSceneHandler::AddCompound(), and G4VSceneHandler::LoadAtts().
void G4VHit::Draw () virtual
Reimplemented in H02MuonHit, TrackerHit, DMXPmtHit, DMXScintHit, B5DriftChamberHit, B5EmCalorimeterHit, B5HadCalorimeterHit, B5HodoscopeHit, TrackerHit, ExN04CalorimeterHit, GammaRayTelAnticoincidenceHit, GammaRayTelCalorimeterHit, Par01CalorimeterHit, UltraOpticalHit, GammaRayTelTrackerHit, ExN02TrackerHit, ExN04TrackerHit, XrayFluoSensorHit, XAluminumElectrodeHit, LXePMTHit, B2TrackerHit, B2TrackerHit, B4cCalorHit, B2TrackerHit, LXeScintHit, ExGflashHit, ExGflashHit, ExGflashHit, ExP01TrackerHit, RE05CalorimeterHit, ExN04MuonHit, ExGflashHit, SensitiveDetectorHit, RE01CalorimeterHit, ExN04CalorimeterHit, SensitiveDetectorHit, RE05MuonHit, RE05TrackerHit, FCALCalorHit, CCalG4Hit, eRositaTrackerHit, ExTGTrackerHit, RE01TrackerHit, G4HumanPhantomHit, ExN04TrackerHit, and ExN04MuonHit.
Definition at line 42 of file G4VHit.cc.
View newest version in sPHENIX GitHub at line 42 of file G4VHit.cc
virtual const std::map<G4String,G4AttDef>* G4VHit::GetAttDefs () const inline virtual
Reimplemented in B5DriftChamberHit, B5EmCalorimeterHit, B5HadCalorimeterHit, B5HodoscopeHit, XAluminumElectrodeHit, RE05CalorimeterHit, RE01CalorimeterHit, SensitiveDetectorHit, RE05MuonHit, RE05TrackerHit, and RE01TrackerHit.
Definition at line 59 of file G4VHit.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VHit.hh
Referenced by G4HepRepSceneHandler::addAttributes(), G4HepRepFileSceneHandler::AddCompound(), and G4VSceneHandler::LoadAtts().
G4bool G4VHit::operator== (const G4VHit & right) const
Definition at line 39 of file G4VHit.cc.
View newest version in sPHENIX GitHub at line 39 of file G4VHit.cc
void G4VHit::Print (void) virtual
Reimplemented in H02MuonHit, B5DriftChamberHit, B5EmCalorimeterHit, B5HadCalorimeterHit, TrackerHit, B5HodoscopeHit, DMXPmtHit, DMXScintHit, TrackerHit, ExN04CalorimeterHit, GammaRayTelAnticoincidenceHit, GammaRayTelCalorimeterHit, XAluminumElectrodeHit, Par01CalorimeterHit, UltraOpticalHit, GammaRayTelTrackerHit, ExN02TrackerHit, ExN04TrackerHit, XrayFluoSensorHit, LXePMTHit, RE05CalorimeterHit, B2TrackerHit, B2TrackerHit, B4cCalorHit, B2TrackerHit, SensitiveDetectorHit, LXeScintHit, ExGflashHit, ExGflashHit, ExGflashHit, ExP01TrackerHit, ExN04MuonHit, ExGflashHit, F01CalorHit, F03CalorHit, RE01CalorimeterHit, RE05MuonHit, RE05TrackerHit, ExN04CalorimeterHit, SensitiveDetectorHit, F02CalorHit, FCALCalorHit, CCalG4Hit, eRositaTrackerHit, ExTGTrackerHit, RE01TrackerHit, G4HumanPhantomHit, ExN04TrackerHit, and ExN04MuonHit.
Definition at line 45 of file G4VHit.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VHit.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4VHit.hh
geant4/tree/geant4-10.6-release/source/digits_hits/hits/src/G4VHit.cc