ECCE @ EIC Software: DicomPhantomZSliceHeader Class Reference
DicomPhantomZSliceHeader Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomPhantomZSliceHeader.hh>
Public Member Functions
DicomPhantomZSliceHeader (const G4String &)
DicomPhantomZSliceHeader (const DicomPhantomZSliceHeader &)=default
DicomPhantomZSliceHeader (std::ifstream &fin)
~DicomPhantomZSliceHeader ()
G4int GetNoVoxelX () const
G4int GetNoVoxelY () const
G4int GetNoVoxelZ () const
G4int GetNoVoxels () const
G4double GetMinX () const
G4double GetMinY () const
G4double GetMinZ () const
G4double GetMaxX () const
G4double GetMaxY () const
G4double GetMaxZ () const
G4double GetVoxelHalfX () const
G4double GetVoxelHalfY () const
G4double GetVoxelHalfZ () const
const std::vector< G4String > & GetMaterialNames () const
void SetNoVoxelX (const G4int &val)
void SetNoVoxelY (const G4int &val)
void SetNoVoxelZ (const G4int &val)
void SetMinX (const G4double &val)
void SetMaxX (const G4double &val)
void SetMinY (const G4double &val)
void SetMaxY (const G4double &val)
void SetMinZ (const G4double &val)
void SetMaxZ (const G4double &val)
void SetMaterialNames (std::vector< G4String > &mn)
void operator+= (const DicomPhantomZSliceHeader &rhs)
DicomPhantomZSliceHeader operator+ (const DicomPhantomZSliceHeader &rhs)
void SetFilename (const G4String &val)
void SetSliceLocation (const G4double &val)
void AddMaterial (const G4String &val)
const G4double & GetSliceLocation () const
void AddRow ()
void AddValue (G4double val)
void AddValue (const std::vector< G4double > &val)
void AddValue (const std::vector< std::vector< G4double > > &val)
void AddMateID (G4int val)
void AddMateID (const std::vector< G4int > &val)
void AddMateID (const std::vector< std::vector< G4int > > &val)
const std::vector< std::vector
< G4double > > & GetValues () const
const std::vector< std::vector
< G4int > > & GetMateIDs () const
void DumpToFile ()
void ReadDataFromFile ()
void DumpExcessMemory ()
void FlipData ()
Private Member Functions
G4bool IsInteger (const G4String &)
template<typename T >
void Print (std::ostream &, const std::vector< T > &, const G4String &, G4int breakLine=-1)
template<typename T >
T G4s2n (const G4String &)
template<typename T >
bool CheckConsistency (const T &, const T &, G4String)
G4bool CheckMaterialExists (const G4String &mateName)
Private Attributes
G4int fNoVoxelX
G4int fNoVoxelY
G4int fNoVoxelZ
G4double fMinX
G4double fMinY
G4double fMinZ
G4double fMaxX
G4double fMaxY
G4double fMaxZ
std::vector< G4String > fMaterialNames
G4String fFilename
std::vector< std::vector
< G4double > > fValues
std::vector< std::vector< G4int > > fMateIDs
G4double fSliceLocation
Detailed Description
DicomPhantomZSliceHeader class
Contains the meta data information corresponding to one or several Z slices (number of voxels, dimension)
History: 30.11.07 First version
Author
P. Arce
Definition at line 50 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 50 of file DicomPhantomZSliceHeader.hh
Constructor & Destructor Documentation
DicomPhantomZSliceHeader::DicomPhantomZSliceHeader (const G4String & fname)
Definition at line 41 of file DicomPhantomZSliceHeader.cc.
View newest version in sPHENIX GitHub at line 41 of file DicomPhantomZSliceHeader.cc
DicomPhantomZSliceHeader::DicomPhantomZSliceHeader (const DicomPhantomZSliceHeader &) default
DicomPhantomZSliceHeader::DicomPhantomZSliceHeader (std::ifstream & fin)
Definition at line 57 of file DicomPhantomZSliceHeader.cc.
View newest version in sPHENIX GitHub at line 57 of file DicomPhantomZSliceHeader.cc
References CheckMaterialExists(), FatalErrorInArgument, fMaterialNames, fMaxX, fMaxY, fMaxZ, fMinX, fMinY, fMinZ, fNoVoxelX, fNoVoxelY, fNoVoxelZ, fSliceLocation, G4cout, G4endl, and G4Exception().
DicomPhantomZSliceHeader::~DicomPhantomZSliceHeader ()
Definition at line 51 of file DicomPhantomZSliceHeader.cc.
View newest version in sPHENIX GitHub at line 51 of file DicomPhantomZSliceHeader.cc
Member Function Documentation
void DicomPhantomZSliceHeader::AddMateID (G4int val) inline
Definition at line 130 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 130 of file DicomPhantomZSliceHeader.hh
References fMateIDs.
Referenced by DicomHandler::StoreData().
void DicomPhantomZSliceHeader::AddMateID (const std::vector< G4int > & val) inline
Definition at line 133 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 133 of file DicomPhantomZSliceHeader.hh
References fMateIDs.
void DicomPhantomZSliceHeader::AddMateID (const std::vector< std::vector< G4int > > & val) inline
Definition at line 134 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 134 of file DicomPhantomZSliceHeader.hh
References fMateIDs.
void DicomPhantomZSliceHeader::AddMaterial (const G4String & val) inline
Definition at line 115 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 115 of file DicomPhantomZSliceHeader.hh
References fMaterialNames.
Referenced by DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::AddRow () inline
Definition at line 119 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 119 of file DicomPhantomZSliceHeader.hh
References fMateIDs, and fValues.
Referenced by DicomHandler::StoreData().
void DicomPhantomZSliceHeader::AddValue (G4double val) inline
Definition at line 122 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 122 of file DicomPhantomZSliceHeader.hh
References fValues.
Referenced by DicomHandler::StoreData().
void DicomPhantomZSliceHeader::AddValue (const std::vector< G4double > & val) inline
Definition at line 125 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 125 of file DicomPhantomZSliceHeader.hh
References fValues.
void DicomPhantomZSliceHeader::AddValue (const std::vector< std::vector< G4double > > & val) inline
Definition at line 126 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 126 of file DicomPhantomZSliceHeader.hh
References fValues.
template<typename T > bool DicomPhantomZSliceHeader::CheckConsistency (const T & val1, const T & val2, G4String category) inline private
Definition at line 203 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 203 of file DicomPhantomZSliceHeader.hh
References G4Exception(), and JustWarning.
Referenced by ReadDataFromFile().
G4bool DicomPhantomZSliceHeader::CheckMaterialExists (const G4String & mateName) private
Definition at line 106 of file DicomPhantomZSliceHeader.cc.
View newest version in sPHENIX GitHub at line 106 of file DicomPhantomZSliceHeader.cc
References G4NistManager::FindOrBuildMaterial(), G4Material::GetMaterialTable(), and G4NistManager::Instance().
Referenced by DicomPhantomZSliceHeader().
void DicomPhantomZSliceHeader::DumpExcessMemory () inline
Definition at line 144 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 144 of file DicomPhantomZSliceHeader.hh
References fFilename, fMateIDs, and fValues.
void DicomPhantomZSliceHeader::DumpToFile ()
Definition at line 205 of file DicomPhantomZSliceHeader.cc.
View newest version in sPHENIX GitHub at line 205 of file DicomPhantomZSliceHeader.cc
References FatalException, fFilename, fMateIDs, fMaterialNames, fMaxX, fMaxY, fMaxZ, fMinX, fMinY, fMinZ, fNoVoxelX, fNoVoxelY, fNoVoxelZ, fValues, G4cout, G4endl, G4Exception(), Print(), and ReadDataFromFile().
void DicomPhantomZSliceHeader::FlipData () inline
Definition at line 181 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 181 of file DicomPhantomZSliceHeader.hh
References fMateIDs, fValues, and reverse.
Referenced by DicomHandler::StoreData().
template<typename T > T DicomPhantomZSliceHeader::G4s2n (const G4String & str) inline private
Definition at line 193 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 193 of file DicomPhantomZSliceHeader.hh
References T.
const std::vector<std::vector<G4int> >& DicomPhantomZSliceHeader::GetMateIDs () const inline
Definition at line 139 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 139 of file DicomPhantomZSliceHeader.hh
References fMateIDs.
const std::vector<G4String>& DicomPhantomZSliceHeader::GetMaterialNames () const inline
Definition at line 80 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 80 of file DicomPhantomZSliceHeader.hh
References fMaterialNames.
Referenced by operator+().
G4double DicomPhantomZSliceHeader::GetMaxX () const inline
Definition at line 72 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 72 of file DicomPhantomZSliceHeader.hh
References fMaxX.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
G4double DicomPhantomZSliceHeader::GetMaxY () const inline
Definition at line 73 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 73 of file DicomPhantomZSliceHeader.hh
References fMaxY.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
G4double DicomPhantomZSliceHeader::GetMaxZ () const inline
Definition at line 74 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 74 of file DicomPhantomZSliceHeader.hh
References fMaxZ.
Referenced by DicomPhantomZSliceMerged::CheckSlices(), DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
G4double DicomPhantomZSliceHeader::GetMinX () const inline
Definition at line 69 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 69 of file DicomPhantomZSliceHeader.hh
References fMinX.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
G4double DicomPhantomZSliceHeader::GetMinY () const inline
Definition at line 70 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 70 of file DicomPhantomZSliceHeader.hh
References fMinY.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
G4double DicomPhantomZSliceHeader::GetMinZ () const inline
Definition at line 71 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 71 of file DicomPhantomZSliceHeader.hh
References fMinZ.
Referenced by DicomPhantomZSliceMerged::CheckSlices(), DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
G4int DicomPhantomZSliceHeader::GetNoVoxels () const inline
Definition at line 67 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 67 of file DicomPhantomZSliceHeader.hh
References fNoVoxelX, fNoVoxelY, and fNoVoxelZ.
Referenced by DicomDetectorConstruction::ReadPhantomDataFile().
G4int DicomPhantomZSliceHeader::GetNoVoxelX () const inline
Definition at line 64 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 64 of file DicomPhantomZSliceHeader.hh
References fNoVoxelX.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
G4int DicomPhantomZSliceHeader::GetNoVoxelY () const inline
Definition at line 65 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 65 of file DicomPhantomZSliceHeader.hh
References fNoVoxelY.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
G4int DicomPhantomZSliceHeader::GetNoVoxelZ () const inline
Definition at line 66 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 66 of file DicomPhantomZSliceHeader.hh
References fNoVoxelZ.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer(), and operator+().
const G4double& DicomPhantomZSliceHeader::GetSliceLocation () const inline
Definition at line 117 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 117 of file DicomPhantomZSliceHeader.hh
References fSliceLocation.
Referenced by DicomPhantomZSliceMerged::AddZSlice(), and DicomPhantomZSliceMerged::CheckSlices().
const std::vector<std::vector<G4double> >& DicomPhantomZSliceHeader::GetValues () const inline
Definition at line 138 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 138 of file DicomPhantomZSliceHeader.hh
References fValues.
G4double DicomPhantomZSliceHeader::GetVoxelHalfX () const inline
Definition at line 76 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 76 of file DicomPhantomZSliceHeader.hh
References fMaxX, fMinX, and fNoVoxelX.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer().
G4double DicomPhantomZSliceHeader::GetVoxelHalfY () const inline
Definition at line 77 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 77 of file DicomPhantomZSliceHeader.hh
References fMaxY, fMinY, and fNoVoxelY.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer().
G4double DicomPhantomZSliceHeader::GetVoxelHalfZ () const inline
Definition at line 78 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 78 of file DicomPhantomZSliceHeader.hh
References fMaxZ, fMinZ, and fNoVoxelZ.
Referenced by DicomDetectorConstruction::ConstructPhantomContainer().
G4bool DicomPhantomZSliceHeader::IsInteger (const G4String & str) inline private
Definition at line 187 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 187 of file DicomPhantomZSliceHeader.hh
Referenced by ReadDataFromFile().
DicomPhantomZSliceHeader DicomPhantomZSliceHeader::operator+ (const DicomPhantomZSliceHeader & rhs)
Definition at line 130 of file DicomPhantomZSliceHeader.cc.
View newest version in sPHENIX GitHub at line 130 of file DicomPhantomZSliceHeader.cc
References FatalErrorInArgument, fMaterialNames, fMaxX, fMaxY, fMaxZ, fMinX, fMinY, fMinZ, fNoVoxelX, fNoVoxelY, fNoVoxelZ, G4cerr, G4endl, G4Exception(), G4GeometryTolerance::GetInstance(), GetMaterialNames(), GetMaxX(), GetMaxY(), GetMaxZ(), GetMinX(), GetMinY(), GetMinZ(), GetNoVoxelX(), GetNoVoxelY(), GetNoVoxelZ(), G4GeometryTolerance::GetRadialTolerance(), max, min, SetMaxZ(), SetMinZ(), and SetNoVoxelZ().
void DicomPhantomZSliceHeader::operator+= (const DicomPhantomZSliceHeader & rhs)
Definition at line 124 of file DicomPhantomZSliceHeader.cc.
View newest version in sPHENIX GitHub at line 124 of file DicomPhantomZSliceHeader.cc
template<typename T > void DicomPhantomZSliceHeader::Print (std::ostream & out, const std::vector< T > & val, const G4String & delim, G4int breakLine = -1) inline private
Definition at line 215 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 215 of file DicomPhantomZSliceHeader.hh
References G4endl.
Referenced by DumpToFile().
void DicomPhantomZSliceHeader::ReadDataFromFile ()
Definition at line 247 of file DicomPhantomZSliceHeader.cc.
View newest version in sPHENIX GitHub at line 247 of file DicomPhantomZSliceHeader.cc
References CheckConsistency(), FatalException, fFilename, fMateIDs, fMaterialNames, fMaxX, fMaxY, fMaxZ, fMinX, fMinY, fMinZ, fNoVoxelX, fNoVoxelY, fNoVoxelZ, fValues, G4Exception(), in, IsInteger(), k, and G4TrackingService::nMaterials.
Referenced by DumpToFile().
void DicomPhantomZSliceHeader::SetFilename (const G4String & val) inline
Definition at line 113 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 113 of file DicomPhantomZSliceHeader.hh
References fFilename.
void DicomPhantomZSliceHeader::SetMaterialNames (std::vector< G4String > & mn) inline
Definition at line 93 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 93 of file DicomPhantomZSliceHeader.hh
References fMaterialNames.
void DicomPhantomZSliceHeader::SetMaxX (const G4double & val) inline
Definition at line 87 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 87 of file DicomPhantomZSliceHeader.hh
References fMaxX.
Referenced by DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetMaxY (const G4double & val) inline
Definition at line 89 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 89 of file DicomPhantomZSliceHeader.hh
References fMaxY.
Referenced by DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetMaxZ (const G4double & val) inline
Definition at line 91 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 91 of file DicomPhantomZSliceHeader.hh
References fMaxZ.
Referenced by DicomPhantomZSliceMerged::CheckSlices(), operator+(), and DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetMinX (const G4double & val) inline
Definition at line 86 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 86 of file DicomPhantomZSliceHeader.hh
References fMinX.
Referenced by DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetMinY (const G4double & val) inline
Definition at line 88 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 88 of file DicomPhantomZSliceHeader.hh
References fMinY.
Referenced by DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetMinZ (const G4double & val) inline
Definition at line 90 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 90 of file DicomPhantomZSliceHeader.hh
References fMinZ.
Referenced by DicomPhantomZSliceMerged::CheckSlices(), operator+(), and DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetNoVoxelX (const G4int & val) inline
Definition at line 82 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 82 of file DicomPhantomZSliceHeader.hh
References fNoVoxelX.
Referenced by DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetNoVoxelY (const G4int & val) inline
Definition at line 83 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 83 of file DicomPhantomZSliceHeader.hh
References fNoVoxelY.
Referenced by DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetNoVoxelZ (const G4int & val) inline
Definition at line 84 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 84 of file DicomPhantomZSliceHeader.hh
References fNoVoxelZ.
Referenced by operator+(), and DicomHandler::ReadFile().
void DicomPhantomZSliceHeader::SetSliceLocation (const G4double & val) inline
Definition at line 114 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 114 of file DicomPhantomZSliceHeader.hh
References fSliceLocation.
Referenced by DicomHandler::StoreData().
Member Data Documentation
G4String DicomPhantomZSliceHeader::fFilename private
Definition at line 171 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 171 of file DicomPhantomZSliceHeader.hh
Referenced by DumpExcessMemory(), DumpToFile(), ReadDataFromFile(), and SetFilename().
std::vector<std::vector<G4int> > DicomPhantomZSliceHeader::fMateIDs private
Definition at line 173 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 173 of file DicomPhantomZSliceHeader.hh
Referenced by AddMateID(), AddRow(), DumpExcessMemory(), DumpToFile(), FlipData(), GetMateIDs(), and ReadDataFromFile().
std::vector<G4String> DicomPhantomZSliceHeader::fMaterialNames private
Definition at line 169 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 169 of file DicomPhantomZSliceHeader.hh
Referenced by AddMaterial(), DicomPhantomZSliceHeader(), DumpToFile(), GetMaterialNames(), operator+(), ReadDataFromFile(), and SetMaterialNames().
G4double DicomPhantomZSliceHeader::fMaxX private
Definition at line 167 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 167 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetMaxX(), GetVoxelHalfX(), operator+(), ReadDataFromFile(), and SetMaxX().
G4double DicomPhantomZSliceHeader::fMaxY private
Definition at line 167 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 167 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetMaxY(), GetVoxelHalfY(), operator+(), ReadDataFromFile(), and SetMaxY().
G4double DicomPhantomZSliceHeader::fMaxZ private
Definition at line 167 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 167 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetMaxZ(), GetVoxelHalfZ(), operator+(), ReadDataFromFile(), and SetMaxZ().
G4double DicomPhantomZSliceHeader::fMinX private
Definition at line 166 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 166 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetMinX(), GetVoxelHalfX(), operator+(), ReadDataFromFile(), and SetMinX().
G4double DicomPhantomZSliceHeader::fMinY private
Definition at line 166 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 166 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetMinY(), GetVoxelHalfY(), operator+(), ReadDataFromFile(), and SetMinY().
G4double DicomPhantomZSliceHeader::fMinZ private
Definition at line 166 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 166 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetMinZ(), GetVoxelHalfZ(), operator+(), ReadDataFromFile(), and SetMinZ().
G4int DicomPhantomZSliceHeader::fNoVoxelX private
Definition at line 165 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 165 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetNoVoxels(), GetNoVoxelX(), GetVoxelHalfX(), operator+(), ReadDataFromFile(), and SetNoVoxelX().
G4int DicomPhantomZSliceHeader::fNoVoxelY private
Definition at line 165 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 165 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetNoVoxels(), GetNoVoxelY(), GetVoxelHalfY(), operator+(), ReadDataFromFile(), and SetNoVoxelY().
G4int DicomPhantomZSliceHeader::fNoVoxelZ private
Definition at line 165 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 165 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), DumpToFile(), GetNoVoxels(), GetNoVoxelZ(), GetVoxelHalfZ(), operator+(), ReadDataFromFile(), and SetNoVoxelZ().
G4double DicomPhantomZSliceHeader::fSliceLocation private
Definition at line 174 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 174 of file DicomPhantomZSliceHeader.hh
Referenced by DicomPhantomZSliceHeader(), GetSliceLocation(), and SetSliceLocation().
std::vector<std::vector<G4double> > DicomPhantomZSliceHeader::fValues private
Definition at line 172 of file DicomPhantomZSliceHeader.hh.
View newest version in sPHENIX GitHub at line 172 of file DicomPhantomZSliceHeader.hh
Referenced by AddRow(), AddValue(), DumpExcessMemory(), DumpToFile(), FlipData(), GetValues(), and ReadDataFromFile().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomPhantomZSliceHeader.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/src/DicomPhantomZSliceHeader.cc