ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/G4gsvolu.cc File Reference
G4gsvolu.cc File Reference
#include <iomanip>
#include "G3VolTable.hh"
#include "globals.hh"
#include "G3toG4.hh"
#include "G3toG4MakeSolid.hh"
Functions
void PG4gsvolu (G4String *tokens)
G3VolTableEntry * G4CreateVTE (G4String vname, G4String shape, G4int nmed, G4double rpar[], G4int npar)
void G4gsvolu (G4String vname, G4String shape, G4int nmed, G4double *rpar, G4int npar)
Function Documentation
G3VolTableEntry* G4CreateVTE (G4String vname, G4String shape, G4int nmed, G4double rpar[], G4int npar)
Definition at line 50 of file G4gsvolu.cc.
View newest version in sPHENIX GitHub at line 50 of file G4gsvolu.cc
References G3toG4MakeSolid(), G3Vol, and G3VolTable::PutVTE().
Referenced by G3Division::CreateEnvelope(), and G4gsvolu().
void G4gsvolu (G4String vname, G4String shape, G4int nmed, G4double * rpar, G4int npar)
Definition at line 72 of file G4gsvolu.cc.
View newest version in sPHENIX GitHub at line 72 of file G4gsvolu.cc
References FatalException, G3Vol, G4CreateVTE(), G4Exception(), and G3VolTable::GetVTE().
Referenced by PG4gsvolu().
void PG4gsvolu (G4String * tokens)
Definition at line 36 of file G4gsvolu.cc.
View newest version in sPHENIX GitHub at line 36 of file G4gsvolu.cc
References G3fillParams(), G4gsvolu(), Ipar, PTgsvolu, Rpar, and Spar.
Referenced by G3CLEval().