ECCE @ EIC Software: macros/blob/master/detectors/EICDetector/Fun4All_G4_EICDetector.C File Reference
Fun4All_G4_EICDetector.C File Reference
#include <GlobalVariables.C>
#include <DisplayOn.C>
#include <G4Setup_EICDetector.C>
#include <G4_DSTReader_EICDetector.C>
#include <G4_EventEvaluator.C>
#include <G4_FwdJets.C>
#include <G4_Global.C>
#include <G4_Input.C>
#include <G4_Production.C>
#include <G4_User.C>
#include <TROOT.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <phool/recoConsts.h>
#include <RooUnblindPrecision.h>
Macros
#define MACRO_FUN4ALLG4EICDETECTOR_C
Functions
int Fun4All_G4_EICDetector (const int nEvents=1, const string &inputFile="https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const string &outputFile="G4EICDetector.root", const string &embed_input_file="https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const int skip=0, const string &outdir=".")
Macro Definition Documentation
#define MACRO_FUN4ALLG4EICDETECTOR_C
Definition at line 2 of file Fun4All_G4_EICDetector.C.
View newest version in sPHENIX GitHub at line 2 of file Fun4All_G4_EICDetector.C
Function Documentation
int Fun4All_G4_EICDetector (const int nEvents = 1, const string & inputFile = "https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const string & outputFile = "G4EICDetector.root", const string & embed_input_file = "https://www.phenix.bnl.gov/WWW/publish/phnxbld/sPHENIX/files/sPHENIX_G4Hits_sHijing_9-11fm_00000_00010.root", const int skip = 0, const string & outdir = ".")
apply EIC beam parameter following EIC CDR
apply EIC beam parameter following EIC CDR
apply EIC beam parameter following EIC CDR
apply EIC beam parameter following EIC CDR
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
apply EIC beam parameter following EIC CDR
Definition at line 27 of file Fun4All_G4_EICDetector.C.
View newest version in sPHENIX GitHub at line 27 of file Fun4All_G4_EICDetector.C
References kdfinder::abs(), Input::ApplyEICBeamParameter(), Enable::B0ECAL_CLUSTER, B0ECAL_Clusters(), Enable::B0ECAL_EVAL, B0ECAL_Eval(), Enable::B0ECAL_TOWER, B0ECAL_Towers(), Enable::BARREL, Enable::BEAM_COLLISION_SETTING, Enable::BECAL, Enable::BECAL_CELL, Enable::BECAL_CLUSTER, BECAL_Clusters(), Enable::BECAL_EVAL, Enable::BECAL_TOWER, BECAL_Towers(), Enable::BLACKHOLE, Enable::BMMG, Enable::BTOF, Enable::BWD_CLUSTER, BWD_Clusters(), Enable::BWD_EVAL, BWD_Eval(), Enable::BWD_TOWER, BWD_Towers(), Enable::CEMC_CELL, CEMC_Cells(), Enable::CEMC_CLUSTER, CEMC_Clusters(), Enable::CEMC_EVAL, CEMC_Eval(), Enable::CEMC_TOWER, CEMC_Towers(), Enable::CTTL, Enable::DIRC, Enable::DIRC_RECO, DIRCReco(), G4TRACKING::DISPLACED_VERTEX, Enable::DISPLAY, DisplayOn(), Enable::DRCALO, Enable::DRCALO_CELL, Enable::DRCALO_CLUSTER, DRCALO_Clusters(), Enable::DRCALO_EVAL, Enable::DRCALO_TOWER, DRCALO_Towers(), DstCompress(), Enable::DSTOUT, Enable::DSTOUT_COMPRESS, Enable::DSTREADER, e, e2, Enable::EEMC_CLUSTER, EEMC_Clusters(), Enable::EEMC_EVAL, EEMC_Eval(), Enable::EEMC_TOWER, EEMC_Towers(), Enable::EEMCH, Enable::EEMCH_CLUSTER, EEMCH_Clusters(), Enable::EEMCH_EVAL, Enable::EEMCH_TOWER, EEMCH_Towers(), Enable::EGEM, Enable::EHCAL, Enable::EHCAL_CELL, Enable::EHCAL_CLUSTER, EHCAL_Clusters(), Enable::EHCAL_EVAL, Enable::EHCAL_TOWER, EHCAL_Towers(), INPUTGENERATOR::EICFileReader, Input::EMBED, Fun4AllServer::End(), Enable::ETOF, Enable::ETOF_GAS, Enable::ETTL, Enable::EVENT_EVAL, Event_Eval(), Enable::EVENT_EVAL_DO_EVT_LVL, Enable::EVENT_EVAL_DO_HEPMC, Enable::EVENT_EVAL_DO_HITS, Enable::FEMC, Enable::FEMC_CLUSTER, FEMC_Clusters(), Enable::FEMC_EVAL, FEMC_Eval(), Enable::FEMC_TOWER, FEMC_Towers(), Enable::FFR_EVAL, FFR_Eval(), Enable::FGEM, Enable::FHCAL_CLUSTER, FHCAL_Clusters(), Enable::FHCAL_EVAL, FHCAL_Eval(), Enable::FHCAL_TOWER, FHCAL_Towers(), INPUTHEPMC::filename, INPUTREADEIC::filename, INPUTREADHITS::filename, INPUTEMBED::filename, Enable::FST, Enable::FTTL, Enable::FWDJETS, Enable::FWDJETS_EVAL, G4DSTreader_EICDetector(), G4Init(), G4Setup(), Enable::GLOBAL_FASTSIM, Global_FastSim(), Enable::GLOBAL_RECO, Global_Reco(), Input::GUN, INPUTGENERATOR::Gun, Enable::HCALIN, Enable::HCALIN_CELL, Enable::HCALIN_CLUSTER, Enable::HCALIN_EVAL, Enable::HCALIN_TOWER, HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_Towers(), Enable::HCALOUT, Enable::HCALOUT_CELL, Enable::HCALOUT_CLUSTER, Enable::HCALOUT_EVAL, Enable::HCALOUT_TOWER, HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_Towers(), Input::HEPMC, INPUTMANAGER::HepMCInputManager, Enable::HFARBWD_E_ENERGY, Enable::HFARBWD_MAGNETS, Enable::HFARBWD_VIRTUAL_DETECTORS, Enable::HFARFWD_ION_ENERGY, Enable::HFARFWD_MAGNETS, Enable::HFARFWD_VIRTUAL_DETECTORS, Enable::HTOF, Enable::HTOF_GAS, InputInit(), InputManagers(), InputRegister(), recoConsts::instance(), Fun4AllServer::instance(), Input::IONGUN, INPUTGENERATOR::IonGun, Enable::IP6, Jet_FwdEval(), Jet_FwdReco(), Enable::LFHCAL, Enable::LFHCAL_ABSORBER, Enable::LFHCAL_CELL, Enable::LFHCAL_CLUSTER, LFHCAL_Clusters(), Enable::LFHCAL_EVAL, Enable::LFHCAL_TOWER, LFHCAL_Towers(), M_PI, G4MAGNET::magfield_rescale, Enable::MAGNET, Enable::mRICH, Enable::mRICH_RECO, mRICHReco(), nEvents, G4TTL::SETTING::optionEEMCH, DstOut::OutputDir, DstOut::OutputFile, Enable::PIPE, Enable::PLUGDOOR, pos(), Enable::PRODUCTION, Production_CreateOutputDir(), Production_MoveOutput(), G4TRACKING::PROJECTION_BECAL, G4TRACKING::PROJECTION_CEMC, G4TRACKING::PROJECTION_EEMC, G4TRACKING::PROJECTION_EHCAL, G4TRACKING::PROJECTION_FEMC, G4TRACKING::PROJECTION_FHCAL, G4TRACKING::PROJECTION_HCALIN, G4TRACKING::PROJECTION_HCALOUT, G4TRACKING::PROJECTION_LFHCAL, Input::PYTHIA6, INPUTGENERATOR::Pythia6, Input::PYTHIA8, INPUTGENERATOR::Pythia8, Input::READEIC, Input::READHITS, Fun4AllServer::registerOutputManager(), Enable::RICH, Enable::RICH_RECO, RICHReco(), Fun4AllServer::run(), Enable::RWELL, Input::SARTRE, INPUTGENERATOR::Sartre, PHPythia6::set_config_file(), PHFlag::set_IntFlag(), ReadEICFiles::SetFirstEntry(), ShowerCompress(), Input::SIMPLE, INPUTGENERATOR::SimpleEventGenerator, Fun4AllServer::skip(), theta(), Enable::TRACKING, Enable::TRACKING_EVAL, Tracking_Eval(), Tracking_Reco(), Enable::TrackingService, Enable::TRD, Enable::TRD_GAS, PHG4SimpleEventGenerator::Uniform, Input::UPSILON, G4PIPE::use_forward_pipes, G4EEMCH::SETTING::USECUSTOMMAPUPDATED, Enable::USER, UserAnalysisInit(), INPUTGENERATOR::VectorMesonGenerator, Fun4AllBase::Verbosity(), and Input::VERBOSITY.