ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_fromTOM.cc File Reference
MCGIDI_fromTOM.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cmath>
#include "MCGIDI_fromTOM.h"
#include "MCGIDI_misc.h"
Functions
static int MCGIDI_fromTOM_pdfOfXGivenW (statusMessageReporting *smr, ptwXYPoints *pdfXY, MCGIDI_pdfsOfXGivenW *dists, int i, double *norm)
int MCGIDI_fromTOM_pdfsOfXGivenW (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_pdfsOfXGivenW *dists, ptwXYPoints *norms, char const *toUnits[3])
int MCGIDI_fromTOM_pdfOfX (statusMessageReporting *smr, ptwXYPoints *pdfXY, MCGIDI_pdfOfX *dist, double *norm)
int MCGIDI_fromTOM_interpolation (statusMessageReporting *smr, xDataTOM_element *element, int index, ptwXY_interpolation *interpolation)
Function Documentation
int MCGIDI_fromTOM_interpolation (statusMessageReporting * smr, xDataTOM_element * element, int index, ptwXY_interpolation * interpolation)
Definition at line 143 of file MCGIDI_fromTOM.cc.
View newest version in sPHENIX GitHub at line 143 of file MCGIDI_fromTOM.cc
References ptwXY_interpolationFlat, ptwXY_interpolationLinLin, ptwXY_interpolationLinLog, ptwXY_interpolationLogLin, ptwXY_interpolationLogLog, ptwXY_interpolationOther, xDataTOM_interpolationFlag_flat, xDataTOM_interpolationFlag_linear, xDataTOM_interpolationFlag_log, and xDataTOME_getInterpolation().
int MCGIDI_fromTOM_pdfOfX (statusMessageReporting * smr, ptwXYPoints * pdfXY, MCGIDI_pdfOfX * dist, double * norm)
Definition at line 90 of file MCGIDI_fromTOM.cc.
View newest version in sPHENIX GitHub at line 90 of file MCGIDI_fromTOM.cc
References MCGIDI_pdfOfX_s::cdf, check_license::err(), int(), n1, nfu_Okay, nfu_statusMessage(), norm, MCGIDI_pdfOfX_s::numberOfXs, MCGIDI_pdfOfX_s::pdf, ptwX_free(), ptwX_getPointAtIndex_Unsafely(), ptwXY_getPointAtIndex_Unsafely(), ptwXY_length(), ptwXY_runningIntegral(), ptwXY_simpleCoalescePoints(), smr_freeMemory(), smr_malloc2, smr_setReportError2, smr_unknownID, sum, ptwXYPoint_s::x, MCGIDI_pdfOfX_s::Xs, and ptwXYPoint_s::y.
Referenced by MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfOfXGivenW(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
static int MCGIDI_fromTOM_pdfOfXGivenW (statusMessageReporting * smr, ptwXYPoints * pdfXY, MCGIDI_pdfsOfXGivenW * dists, int i, double * norm) static
Definition at line 81 of file MCGIDI_fromTOM.cc.
View newest version in sPHENIX GitHub at line 81 of file MCGIDI_fromTOM.cc
References MCGIDI_pdfsOfXGivenW_s::dist, MCGIDI_fromTOM_pdfOfX(), and MCGIDI_pdfsOfXGivenW_s::numberOfWs.
Referenced by MCGIDI_fromTOM_pdfsOfXGivenW().
int MCGIDI_fromTOM_pdfsOfXGivenW (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_pdfsOfXGivenW * dists, ptwXYPoints * norms, char const * toUnits[3])
Definition at line 26 of file MCGIDI_fromTOM.cc.
View newest version in sPHENIX GitHub at line 26 of file MCGIDI_fromTOM.cc
References xDataTOM_xDataInfo_s::axes, MCGIDI_pdfsOfXGivenW_s::dist, check_license::err(), MCGIDI_pdfsOfXGivenW_s::interpolationWY, MCGIDI_pdfsOfXGivenW_s::interpolationXY, xDataTOM_W_XYs_s::length, MCGIDI_fromTOM_interpolation(), MCGIDI_fromTOM_pdfOfXGivenW(), MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf(), MCGIDI_misc_getUnitConversionFactor(), norm, ptwXY_free(), ptwXY_interpolationOther, ptwXY_setValueAtX(), smr_isOk(), smr_malloc2, smr_setReportError2, smr_setReportError2p, smr_unknownID, xDataTOM_XYs_s::value, MCGIDI_pdfsOfXGivenW_s::Ws, xDataTOM_element_s::xDataInfo, xDataTOM_axes_getUnit(), xDataTOME_getXDataIfID(), and xDataTOM_W_XYs_s::XYs.
Referenced by MCGIDI_energy_parseFromTOM().