ECCE @ EIC Software: G4PlotManager Class Reference
G4PlotManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4PlotManager.hh>
Public Member Functions
G4PlotManager (const G4AnalysisManagerState &state)
~G4PlotManager ()
G4PlotManager (const G4PlotManager &rhs)=delete
G4PlotManager & operator= (const G4PlotManager &rhs)=delete
G4bool OpenFile (const G4String &fileName)
template<typename T >
G4bool PlotAndWrite (const std::vector< T * > &htVector, const std::vector< G4HnInformation * > &hnVector)
G4bool CloseFile ()
Private Member Functions
G4int GetNofPlotsPerPage () const
G4bool WritePage ()
Private Attributes
const G4AnalysisManagerState & fState
G4PlotParameters fPlotParameters
std::unique_ptr< tools::viewplot > fViewer
G4String fFileName
Detailed Description
Definition at line 43 of file G4PlotManager.hh.
View newest version in sPHENIX GitHub at line 43 of file G4PlotManager.hh
Constructor & Destructor Documentation
G4PlotManager::G4PlotManager (const G4AnalysisManagerState & state) explicit
Definition at line 152 of file G4PlotManager.cc.
View newest version in sPHENIX GitHub at line 152 of file G4PlotManager.cc
References fPlotParameters, fState, fViewer, G4cout, G4endl, G4PlotParameters::GetColumns(), G4PlotParameters::GetHeight(), G4PlotParameters::GetRows(), G4AnalysisManagerState::GetVerboseL1(), and G4PlotParameters::GetWidth().
G4PlotManager::~G4PlotManager ()
Definition at line 196 of file G4PlotManager.cc.
View newest version in sPHENIX GitHub at line 196 of file G4PlotManager.cc
G4PlotManager::G4PlotManager (const G4PlotManager & rhs) delete
Member Function Documentation
G4bool G4PlotManager::CloseFile ()
Definition at line 268 of file G4PlotManager.cc.
View newest version in sPHENIX GitHub at line 268 of file G4PlotManager.cc
References fFileName, fState, fViewer, G4Exception(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, and G4AnalysisVerbose::Message().
G4int G4PlotManager::GetNofPlotsPerPage () const inline private
Definition at line 76 of file G4PlotManager.hh.
View newest version in sPHENIX GitHub at line 76 of file G4PlotManager.hh
References fPlotParameters, G4PlotParameters::GetColumns(), and G4PlotParameters::GetRows().
Referenced by PlotAndWrite().
G4bool G4PlotManager::OpenFile (const G4String & fileName)
Definition at line 241 of file G4PlotManager.cc.
View newest version in sPHENIX GitHub at line 241 of file G4PlotManager.cc
References fFileName, fState, fViewer, G4Exception(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, and G4AnalysisVerbose::Message().
G4PlotManager& G4PlotManager::operator= (const G4PlotManager & rhs) delete
template<typename T > G4bool G4PlotManager::PlotAndWrite (const std::vector< T * > & htVector, const std::vector< G4HnInformation * > & hnVector) inline
Definition at line 82 of file G4PlotManager.hh.
View newest version in sPHENIX GitHub at line 82 of file G4PlotManager.hh
References fPlotParameters, fState, fViewer, G4HnInformation::GetActivation(), G4PlotParameters::GetColumns(), G4AnalysisManagerState::GetIsActivation(), G4HnInformation::GetIsLogAxis(), G4HnInformation::GetName(), GetNofPlotsPerPage(), G4HnInformation::GetPlotting(), G4PlotParameters::GetRows(), G4PlotParameters::GetStyle(), G4AnalysisManagerState::GetVerboseL3(), G4Analysis::kX, G4Analysis::kY, G4Analysis::kZ, G4AnalysisVerbose::Message(), T, title(), and WritePage().
G4bool G4PlotManager::WritePage () private
Definition at line 204 of file G4PlotManager.cc.
View newest version in sPHENIX GitHub at line 204 of file G4PlotManager.cc
References fFileName, fPlotParameters, fState, fViewer, G4Exception(), G4PlotParameters::GetScale(), G4AnalysisManagerState::GetVerboseL3(), G4AnalysisManagerState::GetVerboseL4(), JustWarning, and G4AnalysisVerbose::Message().
Referenced by PlotAndWrite().
Member Data Documentation
G4String G4PlotManager::fFileName private
Definition at line 70 of file G4PlotManager.hh.
View newest version in sPHENIX GitHub at line 70 of file G4PlotManager.hh
Referenced by CloseFile(), OpenFile(), and WritePage().
G4PlotParameters G4PlotManager::fPlotParameters private
Definition at line 68 of file G4PlotManager.hh.
View newest version in sPHENIX GitHub at line 68 of file G4PlotManager.hh
Referenced by G4PlotManager(), GetNofPlotsPerPage(), PlotAndWrite(), and WritePage().
const G4AnalysisManagerState& G4PlotManager::fState private
Definition at line 67 of file G4PlotManager.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PlotManager.hh
Referenced by CloseFile(), G4PlotManager(), OpenFile(), PlotAndWrite(), and WritePage().
std::unique_ptr<tools::viewplot> G4PlotManager::fViewer private
Definition at line 69 of file G4PlotManager.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PlotManager.hh
Referenced by CloseFile(), G4PlotManager(), OpenFile(), PlotAndWrite(), and WritePage().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4PlotManager.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4PlotManager.cc