ECCE @ EIC Software: G4ITNavigator1 Class Reference
G4ITNavigator1 Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITNavigator1.hh>
Classes
struct G4SaveNavigatorState
Public Member Functions
G4ITNavigator1 ()
virtual ~G4ITNavigator1 ()
G4ITNavigatorState_Lock1 * GetNavigatorState ()
void SetNavigatorState (G4ITNavigatorState_Lock1 *)
void NewNavigatorState ()
virtual G4double ComputeStep (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double &pNewSafety)
G4double CheckNextStep (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double &pNewSafety)
virtual G4VPhysicalVolume * ResetHierarchyAndLocate (const G4ThreeVector &point, const G4ThreeVector &direction, const G4TouchableHistory &h)
virtual G4VPhysicalVolume * LocateGlobalPointAndSetup (const G4ThreeVector &point, const G4ThreeVector *direction=0, const G4bool pRelativeSearch=true, const G4bool ignoreDirection=true)
virtual void LocateGlobalPointWithinVolume (const G4ThreeVector &position)
void LocateGlobalPointAndUpdateTouchableHandle (const G4ThreeVector &position, const G4ThreeVector &direction, G4TouchableHandle &oldTouchableToUpdate, const G4bool RelativeSearch=true)
void LocateGlobalPointAndUpdateTouchable (const G4ThreeVector &position, const G4ThreeVector &direction, G4VTouchable *touchableToUpdate, const G4bool RelativeSearch=true)
void LocateGlobalPointAndUpdateTouchable (const G4ThreeVector &position, G4VTouchable *touchableToUpdate, const G4bool RelativeSearch=true)
void SetGeometricallyLimitedStep ()
virtual G4double ComputeSafety (const G4ThreeVector &globalpoint, const G4double pProposedMaxLength=DBL_MAX, const G4bool keepState=true)
G4VPhysicalVolume * GetWorldVolume () const
void SetWorldVolume (G4VPhysicalVolume *pWorld)
G4GRSVolume * CreateGRSVolume () const
G4GRSSolid * CreateGRSSolid () const
G4TouchableHistory * CreateTouchableHistory () const
G4TouchableHistory * CreateTouchableHistory (const G4NavigationHistory *) const
virtual G4TouchableHistoryHandle CreateTouchableHistoryHandle () const
virtual G4ThreeVector GetLocalExitNormal (G4bool *valid)
virtual G4ThreeVector GetLocalExitNormalAndCheck (const G4ThreeVector &point, G4bool *valid)
virtual G4ThreeVector GetGlobalExitNormal (const G4ThreeVector &point, G4bool *valid)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int level)
G4bool IsActive () const
void Activate (G4bool flag)
G4bool EnteredDaughterVolume () const
G4bool ExitedMotherVolume () const
void CheckMode (G4bool mode)
G4bool IsCheckModeActive () const
void SetPushVerbosity (G4bool mode)
void PrintState () const
const G4AffineTransform & GetGlobalToLocalTransform () const
const G4AffineTransform GetLocalToGlobalTransform () const
G4AffineTransform GetMotherToDaughterTransform (G4VPhysicalVolume *dVolume, G4int dReplicaNo, EVolume dVolumeType)
void ResetStackAndState ()
G4int SeverityOfZeroStepping (G4int *noZeroSteps) const
void SetSavedState ()
void RestoreSavedState ()
G4ThreeVector GetCurrentLocalCoordinate () const
G4ThreeVector NetTranslation () const
G4RotationMatrix NetRotation () const
void EnableBestSafety (G4bool value=false)
virtual void ResetState ()
Static Public Attributes
static const G4int fMaxNav = 8
Protected Member Functions
G4ThreeVector ComputeLocalPoint (const G4ThreeVector &rGlobPoint) const
G4ThreeVector ComputeLocalAxis (const G4ThreeVector &pVec) const
EVolume VolumeType (const G4VPhysicalVolume *pVol) const
EVolume CharacteriseDaughters (const G4LogicalVolume *pLog) const
G4int GetDaughtersRegularStructureId (const G4LogicalVolume *pLog) const
virtual void SetupHierarchy ()
Protected Attributes
G4double kCarTolerance
G4NavigationHistory fHistory
G4bool fEnteredDaughter
G4bool fExitedMother
G4bool fWasLimitedByGeometry
G4ThreeVector fStepEndPoint
G4ThreeVector fLastStepEndPointLocal
G4int fVerbose
Private Member Functions
G4ITNavigator1 (const G4ITNavigator1 &)
G4ITNavigator1 & operator= (const G4ITNavigator1 &)
void ComputeStepLog (const G4ThreeVector &pGlobalpoint, G4double moveLenSq) const
Private Attributes
G4bool fActive
G4bool fLastTriedStepComputation
G4bool fEntering
G4bool fExiting
G4VPhysicalVolume * fBlockedPhysicalVolume
G4int fBlockedReplicaNo
G4ThreeVector fLastLocatedPointLocal
G4bool fLocatedOutsideWorld
G4bool fValidExitNormal
G4ThreeVector fExitNormal
G4ThreeVector fGrandMotherExitNormal
G4bool fChangedGrandMotherRefFrame
G4ThreeVector fExitNormalGlobalFrame
G4bool fCalculatedExitNormal
G4bool fLastStepWasZero
G4bool fLocatedOnEdge
G4int fNumberZeroSteps
G4int fActionThreshold_NoZeroSteps
G4int fAbandonThreshold_NoZeroSteps
G4ThreeVector fPreviousSftOrigin
G4double fPreviousSafety
G4SaveNavigatorState * fpSaveState
G4VPhysicalVolume * fTopPhysical
G4bool fCheck
G4bool fPushed
G4bool fWarnPush
G4NormalNavigation fnormalNav
G4VoxelNavigation fvoxelNav
G4ParameterisedNavigation fparamNav
G4ReplicaNavigation freplicaNav
G4RegularNavigation fregularNav
G4VoxelSafety * fpVoxelSafety
Friends
std::ostream & operator<< (std::ostream &os, const G4ITNavigator1 &n)
Detailed Description
Definition at line 90 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ITNavigator1.hh
Constructor & Destructor Documentation
G4ITNavigator1::G4ITNavigator1 ()
Definition at line 59 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ITNavigator1.cc
References fAbandonThreshold_NoZeroSteps, fActionThreshold_NoZeroSteps, fActive, fLastStepEndPointLocal, fLastTriedStepComputation, fnormalNav, fpSaveState, fpVoxelSafety, fregularNav, fStepEndPoint, G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, kInfinity, ResetStackAndState(), and G4RegularNavigation::SetNormalNavigation().
G4ITNavigator1::~G4ITNavigator1 () virtual
Definition at line 123 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 123 of file G4ITNavigator1.cc
References fpVoxelSafety.
G4ITNavigator1::G4ITNavigator1 (const G4ITNavigator1 &) private
Member Function Documentation
void G4ITNavigator1::Activate (G4bool flag) inline
EVolume G4ITNavigator1::CharacteriseDaughters (const G4LogicalVolume * pLog) const inline protected
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
void G4ITNavigator1::CheckMode (G4bool mode) inline
G4double G4ITNavigator1::CheckNextStep (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double pCurrentProposedStepLength, G4double & pNewSafety)
Definition at line 1248 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1248 of file G4ITNavigator1.cc
References ComputeStep(), RestoreSavedState(), SetSavedState(), and Acts::Test::step().
G4ThreeVector G4ITNavigator1::ComputeLocalAxis (const G4ThreeVector & pVec) const inline protected
Referenced by ComputeStep().
G4ThreeVector G4ITNavigator1::ComputeLocalPoint (const G4ThreeVector & rGlobPoint) const inline protected
Referenced by ComputeSafety(), ComputeStep(), and LocateGlobalPointWithinVolume().
G4double G4ITNavigator1::ComputeSafety (const G4ThreeVector & globalpoint, const G4double pProposedMaxLength = DBL_MAX, const G4bool keepState = true) virtual
Definition at line 1721 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1721 of file G4ITNavigator1.cc
References CharacteriseDaughters(), ComputeLocalPoint(), G4VoxelSafety::ComputeSafety(), G4ParameterisedNavigation::ComputeSafety(), G4NormalNavigation::ComputeSafety(), G4VoxelNavigation::ComputeSafety(), G4RegularNavigation::ComputeSafety(), G4ReplicaNavigation::ComputeSafety(), FatalException, fEnteredDaughter, fExitedMother, fHistory, fnormalNav, fparamNav, fPreviousSafety, fPreviousSftOrigin, fpVoxelSafety, fregularNav, freplicaNav, fStepEndPoint, fVerbose, fvoxelNav, G4cout, G4endl, G4Exception(), GetDaughtersRegularStructureId(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4NavigationHistory::GetTopVolume(), G4NavigationHistory::GetTopVolumeType(), G4LogicalVolume::GetVoxelHeader(), kCarTolerance, kExternal, kNormal, kParameterised, kReplica, LocateGlobalPointWithinVolume(), PrintState(), RestoreSavedState(), and SetSavedState().
G4double G4ITNavigator1::ComputeStep (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double pCurrentProposedStepLength, G4double & pNewSafety) virtual
Definition at line 801 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 801 of file G4ITNavigator1.cc
References CharacteriseDaughters(), G4VPhysicalVolume::CheckOverlaps(), ComputeLocalAxis(), ComputeLocalPoint(), G4RegularNavigation::ComputeStep(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), ComputeStepLog(), incremental_prev_tag::desc, EventMustBeAborted, fAbandonThreshold_NoZeroSteps, fActionThreshold_NoZeroSteps, FatalException, fBlockedPhysicalVolume, fBlockedReplicaNo, fCalculatedExitNormal, fChangedGrandMotherRefFrame, fEnteredDaughter, fEntering, fExitedMother, fExiting, fExitNormal, fExitNormalGlobalFrame, fGrandMotherExitNormal, fHistory, fLastLocatedPointLocal, fLastStepEndPointLocal, fLastStepWasZero, fLastTriedStepComputation, fLocatedOnEdge, fnormalNav, fNumberZeroSteps, fparamNav, fPreviousSafety, fPreviousSftOrigin, fPushed, fregularNav, freplicaNav, fStepEndPoint, fValidExitNormal, fVerbose, fvoxelNav, fWarnPush, G4cout, G4endl, G4Exception(), G4ThreadLocal, G4VPhysicalVolume::GetCopyNo(), GetDaughtersRegularStructureId(), G4NavigationHistory::GetDepth(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetName(), G4VPhysicalVolume::GetRegularStructureId(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTopVolume(), G4NavigationHistory::GetTopVolumeType(), G4NavigationHistory::GetTransform(), G4LogicalVolume::GetVoxelHeader(), G4AffineTransform::Inverse(), JustWarning, kCarTolerance, kExternal, kInfinity, kNormal, kParameterised, kReplica, LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), message(), PrintState(), G4VSolid::SurfaceNormal(), and G4AffineTransform::TransformAxis().
Referenced by CheckNextStep().
void G4ITNavigator1::ComputeStepLog (const G4ThreeVector & pGlobalpoint, G4double moveLenSq) const private
Definition at line 1938 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1938 of file G4ITNavigator1.cc
References fHistory, fLastLocatedPointLocal, fPreviousSafety, fPreviousSftOrigin, G4cerr, G4cout, G4endl, G4Exception(), G4ThreadLocal, G4NavigationHistory::GetTopTransform(), G4AffineTransform::Inverse(), JustWarning, kCarTolerance, message(), mm, and sqr().
Referenced by ComputeStep().
G4GRSSolid* G4ITNavigator1::CreateGRSSolid () const inline
G4GRSVolume* G4ITNavigator1::CreateGRSVolume () const inline
G4TouchableHistory* G4ITNavigator1::CreateTouchableHistory () const inline
Referenced by CreateTouchableHistoryHandle().
G4TouchableHistory* G4ITNavigator1::CreateTouchableHistory (const G4NavigationHistory *) const inline
G4TouchableHistoryHandle G4ITNavigator1::CreateTouchableHistoryHandle () const virtual
Definition at line 1866 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1866 of file G4ITNavigator1.cc
References CreateTouchableHistory().
void G4ITNavigator1::EnableBestSafety (G4bool value = false) inline
G4bool G4ITNavigator1::EnteredDaughterVolume () const inline
Referenced by GetLocalExitNormal().
G4bool G4ITNavigator1::ExitedMotherVolume () const inline
G4ThreeVector G4ITNavigator1::GetCurrentLocalCoordinate () const inline
G4int G4ITNavigator1::GetDaughtersRegularStructureId (const G4LogicalVolume * pLog) const inline protected
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
G4ThreeVector G4ITNavigator1::GetGlobalExitNormal (const G4ThreeVector & point, G4bool * valid) virtual
Definition at line 1619 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1619 of file G4ITNavigator1.cc
References fCalculatedExitNormal, fEntering, fExiting, fExitNormalGlobalFrame, fLastTriedStepComputation, G4endl, G4Exception(), GetLocalExitNormalAndCheck(), GetLocalToGlobalTransform(), GetVerboseLevel(), JustWarning, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), CLHEP::perMillion, perMillion, SetVerboseLevel(), G4AffineTransform::TransformAxis(), and CLHEP::Hep3Vector::unit().
const G4AffineTransform& G4ITNavigator1::GetGlobalToLocalTransform () const inline
Referenced by GetLocalExitNormalAndCheck().
G4ThreeVector G4ITNavigator1::GetLocalExitNormal (G4bool * valid) virtual
Definition at line 1372 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1372 of file G4ITNavigator1.cc
References incremental_prev_tag::desc, G4VSolid::DistanceToIn(), G4VSolid::DistanceToOut(), EnteredDaughterVolume(), FatalException, fBlockedPhysicalVolume, fBlockedReplicaNo, fCalculatedExitNormal, fCheck, fEntering, fExitedMother, fExiting, fGrandMotherExitNormal, fHistory, fLastLocatedPointLocal, fLastStepEndPointLocal, fLastTriedStepComputation, fVerbose, G4endl, G4Exception(), G4VSolid::GetEntityType(), G4VPhysicalVolume::GetLogicalVolume(), GetMotherToDaughterTransform(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), G4LogicalVolume::GetName(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTopVolume(), G4VSolid::Inside(), JustWarning, kCarTolerance, kInside, kOutside, kSurface, CLHEP::Hep3Vector::mag2(), message(), CLHEP::perMillion, G4VSolid::SurfaceNormal(), G4AffineTransform::TransformPoint(), and VolumeType().
Referenced by GetLocalExitNormalAndCheck().
G4ThreeVector G4ITNavigator1::GetLocalExitNormalAndCheck (const G4ThreeVector & point, G4bool * valid) virtual
Definition at line 1584 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1584 of file G4ITNavigator1.cc
References fLastTriedStepComputation, GetGlobalToLocalTransform(), GetLocalExitNormal(), and G4AffineTransform::TransformPoint().
Referenced by GetGlobalExitNormal().
const G4AffineTransform G4ITNavigator1::GetLocalToGlobalTransform () const inline
Referenced by GetGlobalExitNormal().
G4AffineTransform G4ITNavigator1::GetMotherToDaughterTransform (G4VPhysicalVolume * dVolume, G4int dReplicaNo, EVolume dVolumeType)
Definition at line 1533 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1533 of file G4ITNavigator1.cc
References G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeTransformation(), FatalException, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetParameterisation(), G4VPhysicalVolume::GetRegularStructureId(), G4VPhysicalVolume::GetRotation(), G4VPhysicalVolume::GetTranslation(), kExternal, kNormal, kParameterised, kReplica, and G4LogicalVolume::SetSolid().
Referenced by GetLocalExitNormal().
G4ITNavigatorState_Lock1 * G4ITNavigator1::GetNavigatorState ()
Definition at line 670 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 670 of file G4ITNavigator1.cc
References fpSaveState, and SetSavedState().
G4int G4ITNavigator1::GetVerboseLevel () const inline
Referenced by GetGlobalExitNormal().
G4VPhysicalVolume* G4ITNavigator1::GetWorldVolume () const inline
G4bool G4ITNavigator1::IsActive () const inline
G4bool G4ITNavigator1::IsCheckModeActive () const inline
G4VPhysicalVolume * G4ITNavigator1::LocateGlobalPointAndSetup (const G4ThreeVector & point, const G4ThreeVector * direction = 0, const G4bool pRelativeSearch = true, const G4bool ignoreDirection = true) virtual
Definition at line 159 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 159 of file G4ITNavigator1.cc
References G4NavigationHistory::BackLevel(), G4ReplicaNavigation::BackLocate(), CharacteriseDaughters(), G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeTransformation(), G4ReplicaNavigation::ComputeTransformation(), CLHEP::Hep3Vector::dot(), FatalException, fBlockedPhysicalVolume, fBlockedReplicaNo, fChangedGrandMotherRefFrame, fCheck, fEnteredDaughter, fEntering, fExitedMother, fExiting, fGrandMotherExitNormal, fHistory, fLastLocatedPointLocal, fLastTriedStepComputation, fLocatedOnEdge, fLocatedOutsideWorld, fnormalNav, fparamNav, fregularNav, freplicaNav, fValidExitNormal, fVerbose, fvoxelNav, fWasLimitedByGeometry, G4cout, G4endl, G4Exception(), G4VPhysicalVolume::GetCopyNo(), GetDaughtersRegularStructureId(), G4NavigationHistory::GetDepth(), G4VPhysicalVolume::GetLogicalVolume(), G4VSolid::GetName(), G4VPhysicalVolume::GetName(), G4VPhysicalVolume::GetParameterisation(), G4VPhysicalVolume::GetRegularStructureId(), G4VPhysicalVolume::GetRotation(), G4LogicalVolume::GetSolid(), G4NavigationHistory::GetTopReplicaNo(), G4NavigationHistory::GetTopTransform(), G4NavigationHistory::GetTopVolume(), G4NavigationHistory::GetTopVolumeType(), G4LogicalVolume::GetVoxelHeader(), G4VSolid::Inside(), kExternal, kNormal, kOutside, kParameterised, kReplica, kSurface, G4RegularNavigation::LevelLocate(), G4NormalNavigation::LevelLocate(), G4ParameterisedNavigation::LevelLocate(), G4VoxelNavigation::LevelLocate(), G4ReplicaNavigation::LevelLocate(), G4NavigationHistory::NewLevel(), CLHEP::normal(), PrintState(), ResetStackAndState(), G4VPhysicalVolume::SetCopyNo(), G4LogicalVolume::SetSolid(), G4VSolid::SurfaceNormal(), G4AffineTransform::TransformAxis(), G4AffineTransform::TransformPoint(), G4LogicalVolume::UpdateMaterial(), and VolumeType().
Referenced by ComputeStep(), and ResetHierarchyAndLocate().
void G4ITNavigator1::LocateGlobalPointAndUpdateTouchable (const G4ThreeVector & position, const G4ThreeVector & direction, G4VTouchable * touchableToUpdate, const G4bool RelativeSearch = true) inline
void G4ITNavigator1::LocateGlobalPointAndUpdateTouchable (const G4ThreeVector & position, G4VTouchable * touchableToUpdate, const G4bool RelativeSearch = true) inline
void G4ITNavigator1::LocateGlobalPointAndUpdateTouchableHandle (const G4ThreeVector & position, const G4ThreeVector & direction, G4TouchableHandle & oldTouchableToUpdate, const G4bool RelativeSearch = true) inline
void G4ITNavigator1::LocateGlobalPointWithinVolume (const G4ThreeVector & position) virtual
Definition at line 601 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 601 of file G4ITNavigator1.cc
References CharacteriseDaughters(), ComputeLocalPoint(), FatalException, fBlockedPhysicalVolume, fBlockedReplicaNo, fChangedGrandMotherRefFrame, fEnteredDaughter, fEntering, fExitedMother, fExiting, fHistory, fLastLocatedPointLocal, fLastTriedStepComputation, fparamNav, fVerbose, fvoxelNav, G4cout, G4endl, G4Exception(), GetDaughtersRegularStructureId(), G4VPhysicalVolume::GetLogicalVolume(), G4NavigationHistory::GetTopVolume(), G4NavigationHistory::GetTopVolumeType(), G4LogicalVolume::GetVoxelHeader(), kExternal, kNormal, kParameterised, kReplica, G4ParameterisedNavigation::ParamVoxelLocate(), and G4VoxelNavigation::VoxelLocate().
Referenced by ComputeSafety(), and ComputeStep().
G4RotationMatrix G4ITNavigator1::NetRotation () const inline
G4ThreeVector G4ITNavigator1::NetTranslation () const inline
void G4ITNavigator1::NewNavigatorState ()
Definition at line 682 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 682 of file G4ITNavigator1.cc
References fpSaveState, and ResetState().
G4ITNavigator1& G4ITNavigator1::operator= (const G4ITNavigator1 &) private
void G4ITNavigator1::PrintState () const
Definition at line 1875 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1875 of file G4ITNavigator1.cc
References fBlockedPhysicalVolume, fBlockedReplicaNo, fEntering, fExiting, fExitNormal, fLastLocatedPointLocal, fLastStepWasZero, fPreviousSafety, fPreviousSftOrigin, fValidExitNormal, fVerbose, G4cout, G4endl, G4VPhysicalVolume::GetName(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by ComputeSafety(), ComputeStep(), and LocateGlobalPointAndSetup().
G4VPhysicalVolume * G4ITNavigator1::ResetHierarchyAndLocate (const G4ThreeVector & point, const G4ThreeVector & direction, const G4TouchableHistory & h) virtual
Definition at line 131 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 131 of file G4ITNavigator1.cc
References fHistory, fLastTriedStepComputation, G4TouchableHistory::GetHistory(), LocateGlobalPointAndSetup(), ResetState(), and SetupHierarchy().
void G4ITNavigator1::ResetStackAndState () inline
Referenced by G4ITNavigator1(), and LocateGlobalPointAndSetup().
void G4ITNavigator1::ResetState () virtual
Definition at line 1277 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1277 of file G4ITNavigator1.cc
References fBlockedPhysicalVolume, fBlockedReplicaNo, fCalculatedExitNormal, fChangedGrandMotherRefFrame, fEnteredDaughter, fEntering, fExitedMother, fExiting, fExitNormal, fExitNormalGlobalFrame, fGrandMotherExitNormal, fLastLocatedPointLocal, fLastStepWasZero, fLocatedOnEdge, fLocatedOutsideWorld, fNumberZeroSteps, fPreviousSafety, fPreviousSftOrigin, fPushed, fValidExitNormal, fWasLimitedByGeometry, and kInfinity.
Referenced by NewNavigatorState(), and ResetHierarchyAndLocate().
void G4ITNavigator1::RestoreSavedState ()
Definition at line 741 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 741 of file G4ITNavigator1.cc
References fBlockedPhysicalVolume, fBlockedReplicaNo, fEnteredDaughter, fEntering, fExitedMother, fExiting, fExitNormal, fLastLocatedPointLocal, fLastStepWasZero, fLocatedOnEdge, fLocatedOutsideWorld, fNumberZeroSteps, fPreviousSafety, fPreviousSftOrigin, fpSaveState, fPushed, fValidExitNormal, fWasLimitedByGeometry, G4ITNavigator1::G4SaveNavigatorState::sBlockedReplicaNo, G4ITNavigator1::G4SaveNavigatorState::sEnteredDaughter, G4ITNavigator1::G4SaveNavigatorState::sEntering, G4ITNavigator1::G4SaveNavigatorState::sExitedMother, G4ITNavigator1::G4SaveNavigatorState::sExiting, G4ITNavigator1::G4SaveNavigatorState::sExitNormal, G4ITNavigator1::G4SaveNavigatorState::sLastLocatedPointLocal, G4ITNavigator1::G4SaveNavigatorState::sLastStepWasZero, G4ITNavigator1::G4SaveNavigatorState::sLocatedOnEdge, G4ITNavigator1::G4SaveNavigatorState::sLocatedOutsideWorld, G4ITNavigator1::G4SaveNavigatorState::sNumberZeroSteps, G4ITNavigator1::G4SaveNavigatorState::spBlockedPhysicalVolume, G4ITNavigator1::G4SaveNavigatorState::sPreviousSafety, G4ITNavigator1::G4SaveNavigatorState::sPreviousSftOrigin, G4ITNavigator1::G4SaveNavigatorState::sPushed, G4ITNavigator1::G4SaveNavigatorState::sValidExitNormal, and G4ITNavigator1::G4SaveNavigatorState::sWasLimitedByGeometry.
Referenced by CheckNextStep(), ComputeSafety(), and SetNavigatorState().
void G4ITNavigator1::SetGeometricallyLimitedStep () inline
void G4ITNavigator1::SetNavigatorState (G4ITNavigatorState_Lock1 * navState)
Definition at line 676 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 676 of file G4ITNavigator1.cc
References fpSaveState, and RestoreSavedState().
void G4ITNavigator1::SetPushVerbosity (G4bool mode) inline
void G4ITNavigator1::SetSavedState ()
Definition at line 697 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 697 of file G4ITNavigator1.cc
References fBlockedPhysicalVolume, fBlockedReplicaNo, fEnteredDaughter, fEntering, fExitedMother, fExiting, fExitNormal, fLastLocatedPointLocal, fLastStepWasZero, fLocatedOnEdge, fLocatedOutsideWorld, fNumberZeroSteps, fPreviousSafety, fPreviousSftOrigin, fpSaveState, fPushed, fValidExitNormal, fWasLimitedByGeometry, G4ITNavigator1::G4SaveNavigatorState::sBlockedReplicaNo, G4ITNavigator1::G4SaveNavigatorState::sEnteredDaughter, G4ITNavigator1::G4SaveNavigatorState::sEntering, G4ITNavigator1::G4SaveNavigatorState::sExitedMother, G4ITNavigator1::G4SaveNavigatorState::sExiting, G4ITNavigator1::G4SaveNavigatorState::sExitNormal, G4ITNavigator1::G4SaveNavigatorState::sLastLocatedPointLocal, G4ITNavigator1::G4SaveNavigatorState::sLastStepWasZero, G4ITNavigator1::G4SaveNavigatorState::sLocatedOnEdge, G4ITNavigator1::G4SaveNavigatorState::sLocatedOutsideWorld, G4ITNavigator1::G4SaveNavigatorState::sNumberZeroSteps, G4ITNavigator1::G4SaveNavigatorState::spBlockedPhysicalVolume, G4ITNavigator1::G4SaveNavigatorState::sPreviousSafety, G4ITNavigator1::G4SaveNavigatorState::sPreviousSftOrigin, G4ITNavigator1::G4SaveNavigatorState::sPushed, G4ITNavigator1::G4SaveNavigatorState::sValidExitNormal, and G4ITNavigator1::G4SaveNavigatorState::sWasLimitedByGeometry.
Referenced by CheckNextStep(), ComputeSafety(), and GetNavigatorState().
void G4ITNavigator1::SetupHierarchy () protected virtual
Definition at line 1316 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 1316 of file G4ITNavigator1.cc
References G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), G4VPVParameterisation::ComputeTransformation(), G4ReplicaNavigation::ComputeTransformation(), FatalException, fHistory, freplicaNav, G4Exception(), G4NavigationHistory::GetDepth(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetParameterisation(), G4NavigationHistory::GetReplicaNo(), G4NavigationHistory::GetVolume(), G4NavigationHistory::GetVolumeType(), kExternal, kNormal, kParameterised, kReplica, G4TouchableHistory::MoveUpHistory(), G4LogicalVolume::SetSolid(), and G4LogicalVolume::UpdateMaterial().
Referenced by ResetHierarchyAndLocate().
void G4ITNavigator1::SetVerboseLevel (G4int level) inline
Referenced by GetGlobalExitNormal().
void G4ITNavigator1::SetWorldVolume (G4VPhysicalVolume * pWorld) inline
G4int G4ITNavigator1::SeverityOfZeroStepping (G4int * noZeroSteps) const inline
EVolume G4ITNavigator1::VolumeType (const G4VPhysicalVolume * pVol) const inline protected
Referenced by GetLocalExitNormal(), and LocateGlobalPointAndSetup().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4ITNavigator1 & n) friend
Definition at line 2041 of file G4ITNavigator1.cc.
View newest version in sPHENIX GitHub at line 2041 of file G4ITNavigator1.cc
Member Data Documentation
G4int G4ITNavigator1::fAbandonThreshold_NoZeroSteps private
Definition at line 457 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 457 of file G4ITNavigator1.hh
Referenced by ComputeStep(), and G4ITNavigator1().
G4int G4ITNavigator1::fActionThreshold_NoZeroSteps private
Definition at line 455 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 455 of file G4ITNavigator1.hh
Referenced by ComputeStep(), and G4ITNavigator1().
G4bool G4ITNavigator1::fActive private
Definition at line 403 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 403 of file G4ITNavigator1.hh
Referenced by G4ITNavigator1().
G4VPhysicalVolume* G4ITNavigator1::fBlockedPhysicalVolume private
Definition at line 421 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 421 of file G4ITNavigator1.hh
Referenced by ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4int G4ITNavigator1::fBlockedReplicaNo private
Definition at line 422 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 422 of file G4ITNavigator1.hh
Referenced by ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4bool G4ITNavigator1::fCalculatedExitNormal private
Definition at line 439 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 439 of file G4ITNavigator1.hh
Referenced by ComputeStep(), GetGlobalExitNormal(), GetLocalExitNormal(), and ResetState().
G4bool G4ITNavigator1::fChangedGrandMotherRefFrame private
Definition at line 435 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 435 of file G4ITNavigator1.hh
Referenced by ComputeStep(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), and ResetState().
G4bool G4ITNavigator1::fCheck private
Definition at line 510 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 510 of file G4ITNavigator1.hh
Referenced by GetLocalExitNormal(), and LocateGlobalPointAndSetup().
G4bool G4ITNavigator1::fEnteredDaughter protected
Definition at line 378 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 378 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), ResetState(), RestoreSavedState(), and SetSavedState().
G4bool G4ITNavigator1::fEntering private
Definition at line 412 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 412 of file G4ITNavigator1.hh
Referenced by ComputeStep(), GetGlobalExitNormal(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4bool G4ITNavigator1::fExitedMother protected
Definition at line 384 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 384 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), ResetState(), RestoreSavedState(), and SetSavedState().
G4bool G4ITNavigator1::fExiting private
Definition at line 412 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 412 of file G4ITNavigator1.hh
Referenced by ComputeStep(), GetGlobalExitNormal(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4ThreeVector G4ITNavigator1::fExitNormal private
Definition at line 430 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 430 of file G4ITNavigator1.hh
Referenced by ComputeStep(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4ThreeVector G4ITNavigator1::fExitNormalGlobalFrame private
Definition at line 437 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 437 of file G4ITNavigator1.hh
Referenced by ComputeStep(), GetGlobalExitNormal(), and ResetState().
G4ThreeVector G4ITNavigator1::fGrandMotherExitNormal private
Definition at line 433 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 433 of file G4ITNavigator1.hh
Referenced by ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), and ResetState().
G4NavigationHistory G4ITNavigator1::fHistory protected
Definition at line 374 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 374 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), operator<<(), ResetHierarchyAndLocate(), and SetupHierarchy().
G4ThreeVector G4ITNavigator1::fLastLocatedPointLocal private
Definition at line 424 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 424 of file G4ITNavigator1.hh
Referenced by ComputeStep(), ComputeStepLog(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4ThreeVector G4ITNavigator1::fLastStepEndPointLocal protected
Definition at line 394 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 394 of file G4ITNavigator1.hh
Referenced by ComputeStep(), G4ITNavigator1(), and GetLocalExitNormal().
G4bool G4ITNavigator1::fLastStepWasZero private
Definition at line 448 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 448 of file G4ITNavigator1.hh
Referenced by ComputeStep(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4bool G4ITNavigator1::fLastTriedStepComputation private
Definition at line 406 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 406 of file G4ITNavigator1.hh
Referenced by ComputeStep(), G4ITNavigator1(), GetGlobalExitNormal(), GetLocalExitNormal(), GetLocalExitNormalAndCheck(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), and ResetHierarchyAndLocate().
G4bool G4ITNavigator1::fLocatedOnEdge private
Definition at line 451 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 451 of file G4ITNavigator1.hh
Referenced by ComputeStep(), LocateGlobalPointAndSetup(), ResetState(), RestoreSavedState(), and SetSavedState().
G4bool G4ITNavigator1::fLocatedOutsideWorld private
Definition at line 426 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 426 of file G4ITNavigator1.hh
Referenced by LocateGlobalPointAndSetup(), ResetState(), RestoreSavedState(), and SetSavedState().
const G4int G4ITNavigator1::fMaxNav = 8 static
Definition at line 93 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ITNavigator1.hh
G4NormalNavigation G4ITNavigator1::fnormalNav private
Definition at line 517 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 517 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), G4ITNavigator1(), and LocateGlobalPointAndSetup().
G4int G4ITNavigator1::fNumberZeroSteps private
Definition at line 453 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 453 of file G4ITNavigator1.hh
Referenced by ComputeStep(), ResetState(), RestoreSavedState(), and SetSavedState().
G4ParameterisedNavigation G4ITNavigator1::fparamNav private
Definition at line 519 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 519 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
G4double G4ITNavigator1::fPreviousSafety private
Definition at line 461 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 461 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4ThreeVector G4ITNavigator1::fPreviousSftOrigin private
Definition at line 460 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 460 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4SaveNavigatorState* G4ITNavigator1::fpSaveState private
Definition at line 499 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 499 of file G4ITNavigator1.hh
Referenced by G4ITNavigator1(), GetNavigatorState(), NewNavigatorState(), RestoreSavedState(), SetNavigatorState(), and SetSavedState().
G4bool G4ITNavigator1::fPushed private
Definition at line 512 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 512 of file G4ITNavigator1.hh
Referenced by ComputeStep(), ResetState(), RestoreSavedState(), and SetSavedState().
G4VoxelSafety* G4ITNavigator1::fpVoxelSafety private
Definition at line 522 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 522 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), G4ITNavigator1(), and ~G4ITNavigator1().
G4RegularNavigation G4ITNavigator1::fregularNav private
Definition at line 521 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 521 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), G4ITNavigator1(), and LocateGlobalPointAndSetup().
G4ReplicaNavigation G4ITNavigator1::freplicaNav private
Definition at line 520 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 520 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and SetupHierarchy().
G4ThreeVector G4ITNavigator1::fStepEndPoint protected
Definition at line 391 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 391 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), and G4ITNavigator1().
G4VPhysicalVolume* G4ITNavigator1::fTopPhysical private
Definition at line 504 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 504 of file G4ITNavigator1.hh
G4bool G4ITNavigator1::fValidExitNormal private
Definition at line 429 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 429 of file G4ITNavigator1.hh
Referenced by ComputeStep(), LocateGlobalPointAndSetup(), operator<<(), PrintState(), ResetState(), RestoreSavedState(), and SetSavedState().
G4int G4ITNavigator1::fVerbose protected
Definition at line 398 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 398 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), GetLocalExitNormal(), LocateGlobalPointAndSetup(), LocateGlobalPointWithinVolume(), operator<<(), and PrintState().
G4VoxelNavigation G4ITNavigator1::fvoxelNav private
Definition at line 518 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 518 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), LocateGlobalPointAndSetup(), and LocateGlobalPointWithinVolume().
G4bool G4ITNavigator1::fWarnPush private
Definition at line 512 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 512 of file G4ITNavigator1.hh
Referenced by ComputeStep().
G4bool G4ITNavigator1::fWasLimitedByGeometry protected
Definition at line 388 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 388 of file G4ITNavigator1.hh
Referenced by LocateGlobalPointAndSetup(), ResetState(), RestoreSavedState(), and SetSavedState().
G4double G4ITNavigator1::kCarTolerance protected
Definition at line 367 of file G4ITNavigator1.hh.
View newest version in sPHENIX GitHub at line 367 of file G4ITNavigator1.hh
Referenced by ComputeSafety(), ComputeStep(), ComputeStepLog(), G4ITNavigator1(), and GetLocalExitNormal().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITNavigator1.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITNavigator1.cc