ECCE @ EIC Software: macros/blob/master/common/G4_BMMG.C File Reference
G4_BMMG.C File Reference
#include <GlobalVariables.C>
#include <fun4all/Fun4AllServer.h>
#include <g4barrelmmg/CreateCZHitContainer.h>
#include <g4barrelmmg/PHG4CylinderStripSubsystem.h>
#include <g4main/PHG4Reco.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
Namespaces
namespace Enable
namespace BMMG
Macros
#define MACRO_G4BMMG_C
Functions
void BMMGInit (int verbosity=1)
void BMMGSetup (PHG4Reco *g4Reco)
void BMMGT_Reco ()
Variables
bool Enable::BMMG = false
bool Enable::use_2Dreadout = true
bool Enable::BMMG_OVERLAPCHECK = true
int Enable::BMMG_VERBOSITY = 0
const int BMMG::n_layer = 3
const double BMMG::rad [BMMG::n_layer] = {45., 47.4, 67.4}
const double BMMG::len [BMMG::n_layer] = {140, 150, 280.0}
Macro Definition Documentation
#define MACRO_G4BMMG_C
Definition at line 2 of file G4_BMMG.C.
View newest version in sPHENIX GitHub at line 2 of file G4_BMMG.C
Function Documentation
void BMMGInit (int verbosity = 1)
Definition at line 33 of file G4_BMMG.C.
View newest version in sPHENIX GitHub at line 33 of file G4_BMMG.C
References BMMG::len, max, BlackHoleGeometry::max_radius, BlackHoleGeometry::max_z, min, BlackHoleGeometry::min_z, BMMG::n_layer, and BMMG::rad.
Referenced by G4Init().
void BMMGSetup (PHG4Reco * g4Reco)
Definition at line 40 of file G4_BMMG.C.
View newest version in sPHENIX GitHub at line 40 of file G4_BMMG.C
References PHG4TrackFastSim::add_phg4hits(), Enable::BMMG_OVERLAPCHECK, Enable::BMMG_VERBOSITY, PHG4TrackFastSim::Cylinder, e, TRACKING::FastKalmanFilter(), Fun4AllServer::instance(), BMMG::len, max, BMMG::n_layer, Enable::OVERLAPCHECK, PHG4DetectorSubsystem::OverlapCheck(), BMMG::rad, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), thickness, Enable::use_2Dreadout, Enable::VERBOSITY, and Fun4AllBase::Verbosity().
Referenced by G4Setup().
void BMMGT_Reco ()
Definition at line 115 of file G4_BMMG.C.
View newest version in sPHENIX GitHub at line 115 of file G4_BMMG.C
References Enable::BMMG_VERBOSITY, Fun4AllServer::instance(), max, and Enable::VERBOSITY.