ECCE @ EIC Software: G4IonParametrisedLossModel Class Reference
G4IonParametrisedLossModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4IonParametrisedLossModel.hh>
Public Member Functions
G4IonParametrisedLossModel (const G4ParticleDefinition *particle=0, const G4String &name="ParamICRU73")
virtual ~G4IonParametrisedLossModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double, G4double, G4double, G4double, G4double)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double, G4double, G4double)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double, G4double)
G4double ComputeLossForStep (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double, G4double)
G4double DeltaRayMeanEnergyTransferRate (const G4Material *, const G4ParticleDefinition *, G4double, G4double)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double, G4double)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &, G4double &, G4double)
G4bool AddDEDXTable (const G4String &name, G4VIonDEDXTable *table, G4VIonDEDXScalingAlgorithm *algorithm=0)
G4bool RemoveDEDXTable (const G4String &name)
LossTableList::iterator IsApplicable (const G4ParticleDefinition *, const G4Material *)
void PrintDEDXTable (const G4ParticleDefinition *, const G4Material *, G4double, G4double, G4int, G4bool)
void PrintDEDXTableHandlers (const G4ParticleDefinition *, const G4Material *, G4double, G4double, G4int, G4bool)
void SetEnergyLossLimit (G4double ionEnergyLossLimit)
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel)
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual void StartTracking (G4Track *)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Types
typedef std::map< IonMatCouple,
G4LPhysicsFreeVector * > RangeEnergyTable
typedef std::map< IonMatCouple,
G4LPhysicsFreeVector * > EnergyRangeTable
Private Member Functions
void UpdateDEDXCache (const G4ParticleDefinition *, const G4Material *, G4double cutEnergy)
void UpdateRangeCache (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
void UpdateCache (const G4ParticleDefinition *)
void BuildRangeVector (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
G4IonParametrisedLossModel & operator= (const G4IonParametrisedLossModel &right)
G4IonParametrisedLossModel (const G4IonParametrisedLossModel &)
Private Attributes
G4BraggIonModel * braggIonModel
G4BetheBlochModel * betheBlochModel
LossTableList lossTableList
RangeEnergyTable r
EnergyRangeTable E
G4double lowerEnergyEdgeIntegr
G4double upperEnergyEdgeIntegr
size_t nmbBins
size_t nmbSubBins
G4ParticleChangeForLoss * particleChangeLoss
G4EmCorrections * corrections
G4double corrFactor
G4double energyLossLimit
G4DataVector cutEnergies
const G4ParticleDefinition * genericIon
G4double genericIonPDGMass
const G4ParticleDefinition * cacheParticle
G4double cacheMass
G4double cacheElecMassRatio
G4double cacheChargeSquare
const G4ParticleDefinition * rangeCacheParticle
const G4MaterialCutsCouple * rangeCacheMatCutsCouple
G4PhysicsVector * rangeCacheEnergyRange
G4PhysicsVector * rangeCacheRangeEnergy
const G4ParticleDefinition * dedxCacheParticle
const G4Material * dedxCacheMaterial
G4double dedxCacheEnergyCut
LossTableList::iterator dedxCacheIter
G4double dedxCacheTransitionEnergy
G4double dedxCacheTransitionFactor
G4double dedxCacheGenIonMassRatio
G4bool isInitialised
Additional Inherited Members
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Detailed Description
Definition at line 92 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 92 of file G4IonParametrisedLossModel.hh
Member Typedef Documentation
typedef std::map<IonMatCouple, G4LPhysicsFreeVector*> G4IonParametrisedLossModel::EnergyRangeTable private
Definition at line 272 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 272 of file G4IonParametrisedLossModel.hh
typedef std::map<IonMatCouple, G4LPhysicsFreeVector*> G4IonParametrisedLossModel::RangeEnergyTable private
Definition at line 269 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 269 of file G4IonParametrisedLossModel.hh
Constructor & Destructor Documentation
G4IonParametrisedLossModel::G4IonParametrisedLossModel (const G4ParticleDefinition * particle = 0, const G4String & name = "ParamICRU73")
Definition at line 105 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 105 of file G4IonParametrisedLossModel.cc
References betheBlochModel, braggIonModel, cacheChargeSquare, cacheElecMassRatio, cacheMass, cacheParticle, corrections, dedxCacheEnergyCut, dedxCacheGenIonMassRatio, dedxCacheIter, dedxCacheMaterial, dedxCacheParticle, dedxCacheTransitionEnergy, dedxCacheTransitionFactor, G4GenericIon::Definition(), G4LossTableManager::EmCorrections(), genericIon, genericIonPDGMass, G4ParticleDefinition::GetPDGMass(), G4VEmModel::HighEnergyLimit(), G4LossTableManager::Instance(), lossTableList, lowerEnergyEdgeIntegr, MeV, rangeCacheEnergyRange, rangeCacheMatCutsCouple, rangeCacheParticle, rangeCacheRangeEnergy, G4VEmModel::SetAngularDistribution(), and upperEnergyEdgeIntegr.
G4IonParametrisedLossModel::~G4IonParametrisedLossModel () virtual
Definition at line 158 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 158 of file G4IonParametrisedLossModel.cc
References E, lossTableList, and r.
G4IonParametrisedLossModel::G4IonParametrisedLossModel (const G4IonParametrisedLossModel &) private
Member Function Documentation
G4bool G4IonParametrisedLossModel::AddDEDXTable (const G4String & name, G4VIonDEDXTable * table, G4VIonDEDXScalingAlgorithm * algorithm = 0)
Definition at line 1237 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 1237 of file G4IonParametrisedLossModel.cc
References algorithm, G4cout, G4endl, and lossTableList.
Referenced by Initialise().
void G4IonParametrisedLossModel::BuildRangeVector (const G4ParticleDefinition * particle, const G4MaterialCutsCouple * matCutsCouple) private
Definition at line 1059 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 1059 of file G4IonParametrisedLossModel.cc
References ComputeDEDXPerVolume(), cutEnergies, DBL_MAX, E, energy, G4cout, G4endl, G4Exp(), genericIonPDGMass, lowerEnergyEdgeIntegr, material(), MeV, mm, nmbBins, nmbSubBins, r, upperEnergyEdgeIntegr, and G4VEmModel::Value().
Referenced by UpdateRangeCache().
G4double G4IonParametrisedLossModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * particle, G4double kineticEnergy, G4double atomicNumber, G4double , G4double cutEnergy, G4double maxKinEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 368 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 368 of file G4IonParametrisedLossModel.cc
References cacheChargeSquare, cacheMass, energy, G4cout, G4endl, MaxSecondaryEnergy(), MeV, min, right, source.hepunit::twopi_mc2_rcl2, and um.
Referenced by CrossSectionPerVolume().
G4double G4IonParametrisedLossModel::ComputeDEDXPerVolume (const G4Material * material, const G4ParticleDefinition * particle, G4double kineticEnergy, G4double cutEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 452 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 452 of file G4IonParametrisedLossModel.cc
References betheBlochModel, braggIonModel, corrections, dedxCacheGenIonMassRatio, dedxCacheIter, dedxCacheTransitionEnergy, dedxCacheTransitionFactor, DeltaRayMeanEnergyTransferRate(), genericIon, genericIonPDGMass, GetChargeSquareRatio(), lossTableList, G4VEmModel::LowEnergyLimit(), and UpdateDEDXCache().
Referenced by BuildRangeVector(), CorrectionsAlongStep(), PrintDEDXTable(), and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::ComputeLossForStep (const G4MaterialCutsCouple * matCutsCouple, const G4ParticleDefinition * particle, G4double kineticEnergy, G4double stepLength)
Definition at line 1178 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 1178 of file G4IonParametrisedLossModel.cc
References energy, G4cout, G4endl, mm, rangeCacheEnergyRange, rangeCacheRangeEnergy, ratio, UpdateRangeCache(), and G4VEmModel::Value().
Referenced by CorrectionsAlongStep().
void G4IonParametrisedLossModel::CorrectionsAlongStep (const G4MaterialCutsCouple * couple, const G4DynamicParticle * dynamicParticle, G4double & eloss, G4double & , G4double length) virtual
Reimplemented from G4VEmModel.
Definition at line 912 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 912 of file G4IonParametrisedLossModel.cc
References betheBlochModel, ComputeDEDXPerVolume(), ComputeLossForStep(), corrections, corrFactor, cutEnergies, DBL_MAX, dedxCacheGenIonMassRatio, dedxCacheIter, dedxCacheTransitionEnergy, energy, energyLossLimit, G4cout, G4endl, G4VEmModel::GetModelOfFluctuations(), lossTableList, G4VEmModel::LowEnergyLimit(), material(), MeV, particle, right, um, and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::CrossSectionPerVolume (const G4Material * material, const G4ParticleDefinition * particle, G4double kineticEnergy, G4double cutEnergy, G4double maxEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 433 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 433 of file G4IonParametrisedLossModel.cc
References ComputeCrossSectionPerAtom(), and Acts::VectorHelpers::cross().
G4double G4IonParametrisedLossModel::DeltaRayMeanEnergyTransferRate (const G4Material * , const G4ParticleDefinition * , G4double , G4double) inline
Referenced by ComputeDEDXPerVolume(), and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::GetChargeSquareRatio (const G4ParticleDefinition * particle, const G4Material * material, G4double kineticEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 220 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 220 of file G4IonParametrisedLossModel.cc
References corrections, and corrFactor.
Referenced by ComputeDEDXPerVolume(), and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::GetParticleCharge (const G4ParticleDefinition * particle, const G4Material * material, G4double kineticEnergy) virtual
Reimplemented from G4VEmModel.
Definition at line 238 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 238 of file G4IonParametrisedLossModel.cc
References corrections.
void G4IonParametrisedLossModel::Initialise (const G4ParticleDefinition * particle, const G4DataVector & cuts) virtual
Implements G4VEmModel.
Definition at line 248 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 248 of file G4IonParametrisedLossModel.cc
References AddDEDXTable(), betheBlochModel, braggIonModel, cacheChargeSquare, cacheElecMassRatio, cacheMass, cacheParticle, cutEnergies, dedxCacheEnergyCut, dedxCacheGenIonMassRatio, dedxCacheIter, dedxCacheMaterial, dedxCacheParticle, dedxCacheTransitionEnergy, dedxCacheTransitionFactor, E, G4cout, G4endl, G4MaterialCutsCouple::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4VEmModel::GetName(), G4VEmModel::GetParticleChangeForLoss(), G4ProductionCutsTable::GetProductionCutsTable(), G4ProductionCutsTable::GetTableSize(), G4EmParameters::Instance(), isInitialised, lossTableList, material(), particleChangeLoss, r, rangeCacheEnergyRange, rangeCacheMatCutsCouple, rangeCacheParticle, rangeCacheRangeEnergy, G4VEmModel::SetParticleChange(), and G4EmParameters::UseICRU90Data().
LossTableList::iterator G4IonParametrisedLossModel::IsApplicable (const G4ParticleDefinition * , const G4Material *) inline
Referenced by PrintDEDXTableHandlers(), UpdateDEDXCache(), and UpdateRangeCache().
G4double G4IonParametrisedLossModel::MaxSecondaryEnergy (const G4ParticleDefinition * particle, G4double kineticEnergy) protected virtual
Reimplemented from G4VEmModel.
Definition at line 192 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 192 of file G4IonParametrisedLossModel.cc
References cacheElecMassRatio, cacheMass, cacheParticle, source.hepunit::electron_mass_c2, and UpdateCache().
Referenced by ComputeCrossSectionPerAtom().
G4double G4IonParametrisedLossModel::MinEnergyCut (const G4ParticleDefinition * , const G4MaterialCutsCouple * couple) virtual
Reimplemented from G4VEmModel.
Definition at line 183 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 183 of file G4IonParametrisedLossModel.cc
References G4Material::GetIonisation(), G4MaterialCutsCouple::GetMaterial(), and G4IonisParamMat::GetMeanExcitationEnergy().
G4IonParametrisedLossModel& G4IonParametrisedLossModel::operator= (const G4IonParametrisedLossModel & right) private
void G4IonParametrisedLossModel::PrintDEDXTable (const G4ParticleDefinition * particle, const G4Material * material, G4double lowerBoundary, G4double upperBoundary, G4int numBins, G4bool logScaleEnergy)
Definition at line 601 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 601 of file G4IonParametrisedLossModel.cc
References cm, cm2, cm3, ComputeDEDXPerVolume(), DBL_MAX, energy, Acts::UnitConstants::g, G4cout, G4endl, G4Exp(), G4VEmModel::GetName(), MeV, nmbBins, and right.
Referenced by PrintDEDXTableHandlers().
void G4IonParametrisedLossModel::PrintDEDXTableHandlers (const G4ParticleDefinition * particle, const G4Material * material, G4double lowerBoundary, G4double upperBoundary, G4int numBins, G4bool logScaleEnergy)
Definition at line 665 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 665 of file G4IonParametrisedLossModel.cc
References IsApplicable(), lossTableList, and PrintDEDXTable().
G4bool G4IonParametrisedLossModel::RemoveDEDXTable (const G4String & name)
Definition at line 1280 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 1280 of file G4IonParametrisedLossModel.cc
References E, G4VEmModel::GetName(), lossTableList, r, and second.
void G4IonParametrisedLossModel::SampleSecondaries (std::vector< G4DynamicParticle * > * secondaries, const G4MaterialCutsCouple * couple, const G4DynamicParticle * particle, G4double cutKinEnergySec, G4double userMaxKinEnergySec) virtual
Implements G4VEmModel.
Definition at line 689 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 689 of file G4IonParametrisedLossModel.cc
References cacheMass, Acts::Test::delta, G4InuclParticleNames::electron, G4Electron::Electron(), energy, G4cout, G4endl, G4UniformRand, G4VEmModel::GetAngularDistribution(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentum(), G4DynamicParticle::GetMomentumDirection(), mat, G4VEmModel::MaxSecondaryKinEnergy(), min, particleChangeLoss, G4VEmModel::SelectRandomAtomNumber(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), CLHEP::Hep3Vector::unit(), and Z.
void G4IonParametrisedLossModel::SetEnergyLossLimit (G4double ionEnergyLossLimit) inline
void G4IonParametrisedLossModel::UpdateCache (const G4ParticleDefinition *) inline private
Referenced by MaxSecondaryEnergy().
void G4IonParametrisedLossModel::UpdateDEDXCache (const G4ParticleDefinition * particle, const G4Material * material, G4double cutEnergy) private
Definition at line 824 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 824 of file G4IonParametrisedLossModel.cc
References betheBlochModel, ComputeDEDXPerVolume(), corrections, dedxCacheEnergyCut, dedxCacheGenIonMassRatio, dedxCacheIter, dedxCacheMaterial, dedxCacheParticle, dedxCacheTransitionEnergy, dedxCacheTransitionFactor, DeltaRayMeanEnergyTransferRate(), genericIon, genericIonPDGMass, GetChargeSquareRatio(), IsApplicable(), lossTableList, material(), and particle.
Referenced by ComputeDEDXPerVolume(), and CorrectionsAlongStep().
void G4IonParametrisedLossModel::UpdateRangeCache (const G4ParticleDefinition * particle, const G4MaterialCutsCouple * matCutsCouple) private
Definition at line 785 of file G4IonParametrisedLossModel.cc.
View newest version in sPHENIX GitHub at line 785 of file G4IonParametrisedLossModel.cc
References BuildRangeVector(), E, IsApplicable(), lossTableList, material(), particle, r, rangeCacheEnergyRange, rangeCacheMatCutsCouple, rangeCacheParticle, and rangeCacheRangeEnergy.
Referenced by ComputeLossForStep().
Member Data Documentation
G4BetheBlochModel* G4IonParametrisedLossModel::betheBlochModel private
Definition at line 259 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 259 of file G4IonParametrisedLossModel.hh
Referenced by ComputeDEDXPerVolume(), CorrectionsAlongStep(), G4IonParametrisedLossModel(), Initialise(), and UpdateDEDXCache().
G4BraggIonModel* G4IonParametrisedLossModel::braggIonModel private
Definition at line 258 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 258 of file G4IonParametrisedLossModel.hh
Referenced by ComputeDEDXPerVolume(), G4IonParametrisedLossModel(), and Initialise().
G4double G4IonParametrisedLossModel::cacheChargeSquare private
Definition at line 339 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 339 of file G4IonParametrisedLossModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4IonParametrisedLossModel(), and Initialise().
G4double G4IonParametrisedLossModel::cacheElecMassRatio private
Definition at line 338 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 338 of file G4IonParametrisedLossModel.hh
Referenced by G4IonParametrisedLossModel(), Initialise(), and MaxSecondaryEnergy().
G4double G4IonParametrisedLossModel::cacheMass private
Definition at line 337 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 337 of file G4IonParametrisedLossModel.hh
Referenced by ComputeCrossSectionPerAtom(), G4IonParametrisedLossModel(), Initialise(), MaxSecondaryEnergy(), and SampleSecondaries().
const G4ParticleDefinition* G4IonParametrisedLossModel::cacheParticle private
Definition at line 336 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 336 of file G4IonParametrisedLossModel.hh
Referenced by G4IonParametrisedLossModel(), Initialise(), and MaxSecondaryEnergy().
G4EmCorrections* G4IonParametrisedLossModel::corrections private
Definition at line 304 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 304 of file G4IonParametrisedLossModel.hh
Referenced by ComputeDEDXPerVolume(), CorrectionsAlongStep(), G4IonParametrisedLossModel(), GetChargeSquareRatio(), GetParticleCharge(), and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::corrFactor private
Definition at line 308 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 308 of file G4IonParametrisedLossModel.hh
Referenced by CorrectionsAlongStep(), and GetChargeSquareRatio().
G4DataVector G4IonParametrisedLossModel::cutEnergies private
Definition at line 323 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 323 of file G4IonParametrisedLossModel.hh
Referenced by BuildRangeVector(), CorrectionsAlongStep(), and Initialise().
G4double G4IonParametrisedLossModel::dedxCacheEnergyCut private
Definition at line 350 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 350 of file G4IonParametrisedLossModel.hh
Referenced by G4IonParametrisedLossModel(), Initialise(), and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::dedxCacheGenIonMassRatio private
Definition at line 357 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 357 of file G4IonParametrisedLossModel.hh
Referenced by ComputeDEDXPerVolume(), CorrectionsAlongStep(), G4IonParametrisedLossModel(), Initialise(), and UpdateDEDXCache().
LossTableList::iterator G4IonParametrisedLossModel::dedxCacheIter private
Definition at line 351 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 351 of file G4IonParametrisedLossModel.hh
Referenced by ComputeDEDXPerVolume(), CorrectionsAlongStep(), G4IonParametrisedLossModel(), Initialise(), and UpdateDEDXCache().
const G4Material* G4IonParametrisedLossModel::dedxCacheMaterial private
Definition at line 349 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 349 of file G4IonParametrisedLossModel.hh
Referenced by G4IonParametrisedLossModel(), Initialise(), and UpdateDEDXCache().
const G4ParticleDefinition* G4IonParametrisedLossModel::dedxCacheParticle private
Definition at line 348 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 348 of file G4IonParametrisedLossModel.hh
Referenced by G4IonParametrisedLossModel(), Initialise(), and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::dedxCacheTransitionEnergy private
Definition at line 352 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 352 of file G4IonParametrisedLossModel.hh
Referenced by ComputeDEDXPerVolume(), CorrectionsAlongStep(), G4IonParametrisedLossModel(), Initialise(), and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::dedxCacheTransitionFactor private
Definition at line 355 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 355 of file G4IonParametrisedLossModel.hh
Referenced by ComputeDEDXPerVolume(), G4IonParametrisedLossModel(), Initialise(), and UpdateDEDXCache().
EnergyRangeTable G4IonParametrisedLossModel::E private
Definition at line 273 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 273 of file G4IonParametrisedLossModel.hh
Referenced by BuildRangeVector(), Initialise(), RemoveDEDXTable(), UpdateRangeCache(), and ~G4IonParametrisedLossModel().
G4double G4IonParametrisedLossModel::energyLossLimit private
Definition at line 314 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 314 of file G4IonParametrisedLossModel.hh
Referenced by CorrectionsAlongStep().
const G4ParticleDefinition* G4IonParametrisedLossModel::genericIon private
Definition at line 326 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 326 of file G4IonParametrisedLossModel.hh
Referenced by ComputeDEDXPerVolume(), G4IonParametrisedLossModel(), and UpdateDEDXCache().
G4double G4IonParametrisedLossModel::genericIonPDGMass private
Definition at line 327 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 327 of file G4IonParametrisedLossModel.hh
Referenced by BuildRangeVector(), ComputeDEDXPerVolume(), G4IonParametrisedLossModel(), and UpdateDEDXCache().
G4bool G4IonParametrisedLossModel::isInitialised private
Definition at line 359 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 359 of file G4IonParametrisedLossModel.hh
Referenced by Initialise().
LossTableList G4IonParametrisedLossModel::lossTableList private
Definition at line 262 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 262 of file G4IonParametrisedLossModel.hh
Referenced by AddDEDXTable(), ComputeDEDXPerVolume(), CorrectionsAlongStep(), G4IonParametrisedLossModel(), Initialise(), PrintDEDXTableHandlers(), RemoveDEDXTable(), UpdateDEDXCache(), UpdateRangeCache(), and ~G4IonParametrisedLossModel().
G4double G4IonParametrisedLossModel::lowerEnergyEdgeIntegr private
Definition at line 280 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 280 of file G4IonParametrisedLossModel.hh
Referenced by BuildRangeVector(), and G4IonParametrisedLossModel().
size_t G4IonParametrisedLossModel::nmbBins private
Definition at line 283 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 283 of file G4IonParametrisedLossModel.hh
Referenced by BuildRangeVector(), and PrintDEDXTable().
size_t G4IonParametrisedLossModel::nmbSubBins private
Definition at line 284 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 284 of file G4IonParametrisedLossModel.hh
Referenced by BuildRangeVector().
G4ParticleChangeForLoss* G4IonParametrisedLossModel::particleChangeLoss private
Definition at line 294 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 294 of file G4IonParametrisedLossModel.hh
Referenced by Initialise(), and SampleSecondaries().
RangeEnergyTable G4IonParametrisedLossModel::r private
Definition at line 270 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 270 of file G4IonParametrisedLossModel.hh
Referenced by BuildRangeVector(), Initialise(), RemoveDEDXTable(), UpdateRangeCache(), and ~G4IonParametrisedLossModel().
G4PhysicsVector* G4IonParametrisedLossModel::rangeCacheEnergyRange private
Definition at line 344 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 344 of file G4IonParametrisedLossModel.hh
Referenced by ComputeLossForStep(), G4IonParametrisedLossModel(), Initialise(), and UpdateRangeCache().
const G4MaterialCutsCouple* G4IonParametrisedLossModel::rangeCacheMatCutsCouple private
Definition at line 343 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 343 of file G4IonParametrisedLossModel.hh
Referenced by G4IonParametrisedLossModel(), Initialise(), and UpdateRangeCache().
const G4ParticleDefinition* G4IonParametrisedLossModel::rangeCacheParticle private
Definition at line 342 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 342 of file G4IonParametrisedLossModel.hh
Referenced by G4IonParametrisedLossModel(), Initialise(), and UpdateRangeCache().
G4PhysicsVector* G4IonParametrisedLossModel::rangeCacheRangeEnergy private
Definition at line 345 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 345 of file G4IonParametrisedLossModel.hh
Referenced by ComputeLossForStep(), G4IonParametrisedLossModel(), Initialise(), and UpdateRangeCache().
G4double G4IonParametrisedLossModel::upperEnergyEdgeIntegr private
Definition at line 281 of file G4IonParametrisedLossModel.hh.
View newest version in sPHENIX GitHub at line 281 of file G4IonParametrisedLossModel.hh
Referenced by BuildRangeVector(), and G4IonParametrisedLossModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4IonParametrisedLossModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4IonParametrisedLossModel.cc