ECCE @ EIC Software: G4PhysicalVolumeModel Class Reference
G4PhysicalVolumeModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PhysicalVolumeModel.hh>
Classes
class G4PhysicalVolumeModelTouchable
class G4PhysicalVolumeNodeID
struct TouchableProperties
Public Types
enum { UNLIMITED = -1 }
enum ClippingMode { subtraction, intersection }
Public Member Functions
G4PhysicalVolumeModel (G4VPhysicalVolume *=0, G4int requestedDepth=UNLIMITED, const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0, G4bool useFullExtent=false, const std::vector< G4PhysicalVolumeNodeID > &baseFullPVPath=std::vector< G4PhysicalVolumeNodeID >())
virtual ~G4PhysicalVolumeModel ()
void DescribeYourselfTo (G4VGraphicsScene &)
G4String GetCurrentDescription () const
G4String GetCurrentTag () const
G4VPhysicalVolume * GetTopPhysicalVolume () const
G4int GetRequestedDepth () const
const G4VSolid * GetClippingSolid () const
G4int GetCurrentDepth () const
G4VPhysicalVolume * GetCurrentPV () const
G4int GetCurrentPVCopyNo () const
G4LogicalVolume * GetCurrentLV () const
G4Material * GetCurrentMaterial () const
G4Transform3D * GetCurrentTransform () const
const std::vector
< G4PhysicalVolumeNodeID > & GetBaseFullPVPath () const
const std::vector
< G4PhysicalVolumeNodeID > & GetFullPVPath () const
const std::vector
< G4PhysicalVolumeNodeID > & GetDrawnPVPath () const
const std::map< G4String,
G4AttDef > * GetAttDefs () const
std::vector< G4AttValue > * CreateCurrentAttValues () const
void SetRequestedDepth (G4int requestedDepth)
void SetClippingSolid (G4VSolid *pClippingSolid)
void SetClippingMode (ClippingMode mode)
G4bool Validate (G4bool warn)
void Abort () const
void CurtailDescent () const
Public Member Functions inherited from G4VModel
G4VModel (const G4Transform3D &modelTransformation=G4Transform3D(), const G4ModelingParameters *=0)
virtual ~G4VModel ()
const G4ModelingParameters * GetModelingParameters () const
const G4String & GetType () const
const G4VisExtent & GetExtent () const
const G4VisExtent & GetTransformedExtent () const
const G4String & GetGlobalDescription () const
const G4String & GetGlobalTag () const
const G4Transform3D & GetTransformation () const
void SetModelingParameters (const G4ModelingParameters *)
void SetExtent (const G4VisExtent &)
void SetType (const G4String &)
void SetGlobalDescription (const G4String &)
void SetGlobalTag (const G4String &)
void SetTransformation (const G4Transform3D &)
Static Public Member Functions
static
G4ModelingParameters::PVNameCopyNoPath GetPVNameCopyNoPath (const std::vector< G4PhysicalVolumeNodeID > &)
Protected Member Functions
void VisitGeometryAndGetVisReps (G4VPhysicalVolume *, G4int requestedDepth, const G4Transform3D &, G4VGraphicsScene &)
void DescribeAndDescend (G4VPhysicalVolume *, G4int requestedDepth, G4LogicalVolume *, G4VSolid *, G4Material *, const G4Transform3D &, G4VGraphicsScene &)
virtual void DescribeSolid (const G4Transform3D &theAT, G4VSolid *pSol, const G4VisAttributes *pVisAttribs, G4VGraphicsScene &sceneHandler)
void CalculateExtent ()
Protected Attributes
G4VPhysicalVolume * fpTopPV
G4String fTopPVName
G4int fTopPVCopyNo
G4int fRequestedDepth
G4bool fUseFullExtent
G4int fCurrentDepth
G4VPhysicalVolume * fpCurrentPV
G4int fCurrentPVCopyNo
G4LogicalVolume * fpCurrentLV
G4Material * fpCurrentMaterial
G4Transform3D * fpCurrentTransform
std::vector
< G4PhysicalVolumeNodeID > fBaseFullPVPath
std::vector
< G4PhysicalVolumeNodeID > fFullPVPath
std::vector
< G4PhysicalVolumeNodeID > fDrawnPVPath
G4bool fAbort
G4bool fCurtailDescent
G4VSolid * fpClippingSolid
ClippingMode fClippingMode
Protected Attributes inherited from G4VModel
G4String fType
G4String fGlobalTag
G4String fGlobalDescription
G4VisExtent fExtent
G4Transform3D fTransform
const G4ModelingParameters * fpMP
Private Member Functions
G4PhysicalVolumeModel (const G4PhysicalVolumeModel &)
G4PhysicalVolumeModel & operator= (const G4PhysicalVolumeModel &)
Detailed Description
Definition at line 82 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 82 of file G4PhysicalVolumeModel.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
UNLIMITED
Definition at line 86 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PhysicalVolumeModel.hh
enum G4PhysicalVolumeModel::ClippingMode
Enumerator:
subtraction
intersection
Definition at line 88 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 88 of file G4PhysicalVolumeModel.hh
Constructor & Destructor Documentation
G4PhysicalVolumeModel::G4PhysicalVolumeModel (G4VPhysicalVolume * pVPV = 0, G4int requestedDepth = UNLIMITED, const G4Transform3D & modelTransformation = G4Transform3D(), const G4ModelingParameters * pMP = 0, G4bool useFullExtent = false, const std::vector< G4PhysicalVolumeNodeID > & baseFullPVPath = std::vector<G4PhysicalVolumeNodeID>())
Definition at line 62 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 62 of file G4PhysicalVolumeModel.cc
G4PhysicalVolumeModel::~G4PhysicalVolumeModel () virtual
Definition at line 114 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 114 of file G4PhysicalVolumeModel.cc
References fpClippingSolid.
G4PhysicalVolumeModel::G4PhysicalVolumeModel (const G4PhysicalVolumeModel &) private
Member Function Documentation
void G4PhysicalVolumeModel::Abort () const inline
Definition at line 244 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 244 of file G4PhysicalVolumeModel.hh
References fAbort.
Referenced by G4TouchablePropertiesScene::ProcessVolume().
void G4PhysicalVolumeModel::CalculateExtent () protected
Definition at line 131 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 131 of file G4PhysicalVolumeModel.cc
References DescribeYourselfTo(), G4VModel::fExtent, G4VModel::fpMP, fpTopPV, fRequestedDepth, fTopPVCopyNo, G4VModel::fTransform, fUseFullExtent, G4BoundingExtentScene::GetBoundingExtent(), G4VModel::GetExtent(), G4VisExtent::GetExtentRadius(), radius, and G4ModelingParameters::wf.
Referenced by Validate().
std::vector< G4AttValue > * G4PhysicalVolumeModel::CreateCurrentAttValues () const
Definition at line 918 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 918 of file G4PhysicalVolumeModel.cc
References fBaseFullPVPath, fFullPVPath, fpCurrentLV, fpCurrentMaterial, fpCurrentPV, fpCurrentTransform, G4BestUnit, G4Exception(), G4Material::GetDensity(), G4VSolid::GetEntityType(), G4VSolid::GetName(), G4Region::GetName(), G4Material::GetName(), G4LogicalVolume::GetName(), G4VPhysicalVolume::GetObjectRotationValue(), G4Material::GetRadlen(), G4LogicalVolume::GetRegion(), G4LogicalVolume::GetSolid(), G4Material::GetState(), G4VPhysicalVolume::GetTranslation(), G4LogicalVolume::IsRootRegion(), JustWarning, kStateUndefined, and Acts::Test::values.
Referenced by G4VSceneHandler::LoadAtts(), G4XXXStoredSceneHandler::PreAddSolid(), G4ASCIITreeSceneHandler::RequestPrimitives(), and G4VisCommandsTouchable::SetNewValue().
void G4PhysicalVolumeModel::CurtailDescent () const inline
Definition at line 247 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 247 of file G4PhysicalVolumeModel.hh
References fCurtailDescent.
Referenced by G4BoundingExtentScene::ProcessVolume(), G4BoundingSphereScene::ProcessVolume(), and G4ASCIITreeSceneHandler::RequestPrimitives().
void G4PhysicalVolumeModel::DescribeAndDescend (G4VPhysicalVolume * pVPV, G4int requestedDepth, G4LogicalVolume * pLV, G4VSolid * pSol, G4Material * pMaterial, const G4Transform3D & theAT, G4VGraphicsScene & sceneHandler) protected
Definition at line 379 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 379 of file G4PhysicalVolumeModel.cc
References G4VisAttributes::cloud, d, d1, d2, HepGeom::Transform3D::dx(), HepGeom::Transform3D::dy(), HepGeom::Transform3D::dz(), FatalErrorInArgument, G4Exception(), G4Colour::GetAlpha(), G4VisAttributes::GetColour(), G4VPhysicalVolume::GetCopyNo(), HepGeom::Transform3D::getDecomposition(), G4Material::GetDensity(), G4VisAttributes::GetForcedDrawingStyle(), G4VisAttributes::GetForcedLineSegmentsPerCircle(), G4VisAttributes::GetForcedNumberOfCloudPoints(), G4VisAttributes::GetLineStyle(), G4VisAttributes::GetLineWidth(), G4LogicalVolume::GetNoDaughters(), G4LogicalVolume::GetVisAttributes(), G4ModelingParameters::hlhsr, G4ModelingParameters::hsr, HepGeom::Transform3D::inverse(), G4VisAttributes::IsDaughtersInvisible(), G4VisAttributes::IsForceAuxEdgeVisible(), G4VisAttributes::IsForcedAuxEdgeVisible(), G4VisAttributes::IsForceDrawingStyle(), G4VisAttributes::IsVisible(), G4VisAttributes::SetColour(), G4VisAttributes::SetDaughtersInvisible(), G4VisAttributes::SetForceAuxEdgeVisible(), G4VisAttributes::SetForceCloud(), G4VisAttributes::SetForceLineSegmentsPerCircle(), G4VisAttributes::SetForceNumberOfCloudPoints(), G4VisAttributes::SetForceSolid(), G4VisAttributes::SetForceWireframe(), G4VisAttributes::SetLineStyle(), G4VisAttributes::SetLineWidth(), G4VisAttributes::SetVisibility(), G4VisAttributes::solid, G4ModelingParameters::VASColour, G4ModelingParameters::VASDaughtersInvisible, G4ModelingParameters::VASForceAuxEdgeVisible, G4ModelingParameters::VASForceCloud, G4ModelingParameters::VASForceLineSegmentsPerCircle, G4ModelingParameters::VASForceNumberOfCloudPoints, G4ModelingParameters::VASForceSolid, G4ModelingParameters::VASForceWireframe, G4ModelingParameters::VASLineStyle, G4ModelingParameters::VASLineWidth, G4ModelingParameters::VASVisibility, and G4VisAttributes::wireframe.
void G4PhysicalVolumeModel::DescribeSolid (const G4Transform3D & theAT, G4VSolid * pSol, const G4VisAttributes * pVisAttribs, G4VGraphicsScene & sceneHandler) protected virtual
Reimplemented in G4LogicalVolumeModel.
Definition at line 685 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 685 of file G4PhysicalVolumeModel.cc
References G4VGraphicsScene::AddPrimitive(), G4VGraphicsScene::BeginPrimitives(), G4VGraphicsScene::EndPrimitives(), G4cout, G4endl, G4VisAttributes::GetForcedLineSegmentsPerCircle(), G4VSolid::GetName(), HepPolyhedron::GetNoFacets(), G4VSolid::GetPolyhedron(), HepGeom::Transform3D::inverse(), G4VisAttributes::IsForceLineSegmentsPerCircle(), G4VGraphicsScene::PostAddSolid(), G4VGraphicsScene::PreAddSolid(), HepPolyhedron::ResetNumberOfRotationSteps(), and HepPolyhedron::SetNumberOfRotationSteps().
void G4PhysicalVolumeModel::DescribeYourselfTo (G4VGraphicsScene & sceneHandler) virtual
Implements G4VModel.
Definition at line 176 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 176 of file G4PhysicalVolumeModel.cc
References FatalException, and G4Exception().
Referenced by CalculateExtent(), G4LogicalVolumeModel::DescribeYourselfTo(), G4ASCIITreeSceneHandler::EndModeling(), G4TouchableUtils::FindTouchableProperties(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VisCommandSetVolumeForField::SetNewValue(), G4VisCommandSceneAddVolume::SetNewValue(), and Validate().
const std::map< G4String, G4AttDef > * G4PhysicalVolumeModel::GetAttDefs () const
Definition at line 841 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 841 of file G4PhysicalVolumeModel.cc
References G4AttDefStore::GetInstance().
Referenced by G4VSceneHandler::LoadAtts(), G4XXXStoredSceneHandler::PreAddSolid(), G4ASCIITreeSceneHandler::RequestPrimitives(), G4VisCommandsTouchable::SetNewValue(), and G4VisCommandList::SetNewValue().
const std::vector<G4PhysicalVolumeNodeID>& G4PhysicalVolumeModel::GetBaseFullPVPath () const inline
Definition at line 191 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 191 of file G4PhysicalVolumeModel.hh
References fBaseFullPVPath.
const G4VSolid* G4PhysicalVolumeModel::GetClippingSolid () const inline
Definition at line 170 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4PhysicalVolumeModel.hh
References fpClippingSolid.
G4int G4PhysicalVolumeModel::GetCurrentDepth () const inline
Definition at line 173 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 173 of file G4PhysicalVolumeModel.hh
References fCurrentDepth.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4HepRepSceneHandler::getGeometryOrEventInstance(), G4PhysicalVolumeSearchScene::ProcessVolume(), G4PhysicalVolumeMassScene::ProcessVolume(), and G4PhysicalVolumesSearchScene::ProcessVolume().
G4String G4PhysicalVolumeModel::GetCurrentDescription () const virtual
Reimplemented from G4VModel.
Definition at line 225 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 225 of file G4PhysicalVolumeModel.cc
References GetCurrentTag().
G4LogicalVolume* G4PhysicalVolumeModel::GetCurrentLV () const inline
Definition at line 182 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4PhysicalVolumeModel.hh
References fpCurrentLV.
Referenced by G4GMocrenFileSceneHandler::AddDetector(), G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), G4HepRepSceneHandler::AddSolid(), G4HepRepSceneHandler::getGeometryOrEventInstance(), and G4ASCIITreeSceneHandler::RequestPrimitives().
G4Material* G4PhysicalVolumeModel::GetCurrentMaterial () const inline
Definition at line 185 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 185 of file G4PhysicalVolumeModel.hh
References fpCurrentMaterial.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4HepRepSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), G4HepRepSceneHandler::getGeometryOrEventInstance(), G4PhysicalVolumeMassScene::ProcessVolume(), and G4ASCIITreeSceneHandler::RequestPrimitives().
G4VPhysicalVolume* G4PhysicalVolumeModel::GetCurrentPV () const inline
Definition at line 176 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4PhysicalVolumeModel.hh
References fpCurrentPV.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddPrimitive(), G4GMocrenFileSceneHandler::AddSolid(), G4TouchablePropertiesScene::ProcessVolume(), G4PhysicalVolumeSearchScene::ProcessVolume(), G4PhysicalVolumeMassScene::ProcessVolume(), G4PhysicalVolumesSearchScene::ProcessVolume(), and G4ASCIITreeSceneHandler::RequestPrimitives().
G4int G4PhysicalVolumeModel::GetCurrentPVCopyNo () const inline
Definition at line 179 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4PhysicalVolumeModel.hh
References fCurrentPVCopyNo.
Referenced by G4TouchablePropertiesScene::ProcessVolume(), and G4PhysicalVolumesSearchScene::ProcessVolume().
G4String G4PhysicalVolumeModel::GetCurrentTag () const virtual
Reimplemented from G4VModel.
Definition at line 213 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 213 of file G4PhysicalVolumeModel.cc
References G4VModel::fGlobalTag, and fpCurrentPV.
Referenced by GetCurrentDescription().
G4Transform3D* G4PhysicalVolumeModel::GetCurrentTransform () const inline
Definition at line 188 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 188 of file G4PhysicalVolumeModel.hh
References fpCurrentTransform.
Referenced by G4TouchablePropertiesScene::ProcessVolume(), G4ASCIITreeSceneHandler::RequestPrimitives(), and G4VisCommandsTouchable::SetNewValue().
const std::vector<G4PhysicalVolumeNodeID>& G4PhysicalVolumeModel::GetDrawnPVPath () const inline
Definition at line 205 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 205 of file G4PhysicalVolumeModel.hh
References fDrawnPVPath.
Referenced by G4HepRepFileSceneHandler::AddHepRepInstance(), G4GMocrenFileSceneHandler::AddSolid(), G4XXXSGSceneHandler::CreateCurrentItem(), G4VTreeSceneHandler::PreAddSolid(), and G4ASCIITreeSceneHandler::RequestPrimitives().
const std::vector<G4PhysicalVolumeNodeID>& G4PhysicalVolumeModel::GetFullPVPath () const inline
Definition at line 198 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 198 of file G4PhysicalVolumeModel.hh
References fFullPVPath.
Referenced by G4RayTracerSceneHandler::BuildVisAttsMap(), G4TouchablePropertiesScene::ProcessVolume(), G4PhysicalVolumeSearchScene::ProcessVolume(), G4PhysicalVolumesSearchScene::ProcessVolume(), and G4VSceneHandler::RequestPrimitives().
G4ModelingParameters::PVNameCopyNoPath G4PhysicalVolumeModel::GetPVNameCopyNoPath (const std::vector< G4PhysicalVolumeNodeID > & path) static
Definition at line 120 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 120 of file G4PhysicalVolumeModel.cc
Referenced by G4VViewer::TouchableSetColour(), and G4VViewer::TouchableSetVisibility().
G4int G4PhysicalVolumeModel::GetRequestedDepth () const inline
Definition at line 168 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 168 of file G4PhysicalVolumeModel.hh
References fRequestedDepth.
Referenced by G4ASCIITreeSceneHandler::EndModeling().
G4VPhysicalVolume* G4PhysicalVolumeModel::GetTopPhysicalVolume () const inline
Definition at line 166 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4PhysicalVolumeModel.hh
References fpTopPV.
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4ASCIITreeSceneHandler::EndModeling(), and G4PhysicalVolumesSearchScene::ProcessVolume().
G4PhysicalVolumeModel& G4PhysicalVolumeModel::operator= (const G4PhysicalVolumeModel &) private
void G4PhysicalVolumeModel::SetClippingMode (ClippingMode mode) inline
Definition at line 237 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 237 of file G4PhysicalVolumeModel.hh
References fClippingMode.
Referenced by G4VisCommandSceneAddVolume::SetNewValue().
void G4PhysicalVolumeModel::SetClippingSolid (G4VSolid * pClippingSolid) inline
Definition at line 233 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 233 of file G4PhysicalVolumeModel.hh
References fpClippingSolid.
Referenced by G4VisCommandSceneAddVolume::SetNewValue().
void G4PhysicalVolumeModel::SetRequestedDepth (G4int requestedDepth) inline
Definition at line 229 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 229 of file G4PhysicalVolumeModel.hh
References fRequestedDepth.
G4bool G4PhysicalVolumeModel::Validate (G4bool warn) virtual
Reimplemented from G4VModel.
Definition at line 786 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 786 of file G4PhysicalVolumeModel.cc
References CalculateExtent(), DescribeYourselfTo(), G4VModel::fpMP, fpTopPV, fTopPVCopyNo, fTopPVName, G4cout, G4endl, G4ModelingParameters::GetDefaultVisAttributes(), G4PhysicalVolumeSearchScene::GetFoundVolume(), G4TransportationManager::GetNoWorlds(), G4TransportationManager::GetTransportationManager(), G4TransportationManager::GetWorldsIterator(), G4ModelingParameters::SetDefaultVisAttributes(), G4VModel::SetModelingParameters(), and Acts::Test::world.
Referenced by G4VisCommandSceneAddVolume::SetNewValue().
void G4PhysicalVolumeModel::VisitGeometryAndGetVisReps (G4VPhysicalVolume * pVPV, G4int requestedDepth, const G4Transform3D & theAT, G4VGraphicsScene & sceneHandler) protected
Definition at line 231 of file G4PhysicalVolumeModel.cc.
View newest version in sPHENIX GitHub at line 231 of file G4PhysicalVolumeModel.cc
References G4cout, G4endl, G4VSolid::GetEntityType(), G4VSolid::GetName(), pyG4VTouchable::GetRotation, kPhi, kRho, kXAxis, kYAxis, kZAxis, n, offset, CLHEP::HepRotation::rotateZ(), and width.
Member Data Documentation
G4bool G4PhysicalVolumeModel::fAbort mutable protected
Definition at line 290 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 290 of file G4PhysicalVolumeModel.hh
Referenced by Abort().
std::vector<G4PhysicalVolumeNodeID> G4PhysicalVolumeModel::fBaseFullPVPath protected
Definition at line 287 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 287 of file G4PhysicalVolumeModel.hh
Referenced by CreateCurrentAttValues(), and GetBaseFullPVPath().
ClippingMode G4PhysicalVolumeModel::fClippingMode protected
Definition at line 293 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 293 of file G4PhysicalVolumeModel.hh
Referenced by SetClippingMode().
G4int G4PhysicalVolumeModel::fCurrentDepth protected
Definition at line 281 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 281 of file G4PhysicalVolumeModel.hh
Referenced by GetCurrentDepth().
G4int G4PhysicalVolumeModel::fCurrentPVCopyNo protected
Definition at line 283 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 283 of file G4PhysicalVolumeModel.hh
Referenced by GetCurrentPVCopyNo().
G4bool G4PhysicalVolumeModel::fCurtailDescent mutable protected
Definition at line 291 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 291 of file G4PhysicalVolumeModel.hh
Referenced by CurtailDescent().
std::vector<G4PhysicalVolumeNodeID> G4PhysicalVolumeModel::fDrawnPVPath protected
Definition at line 289 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 289 of file G4PhysicalVolumeModel.hh
Referenced by GetDrawnPVPath().
std::vector<G4PhysicalVolumeNodeID> G4PhysicalVolumeModel::fFullPVPath protected
Definition at line 288 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 288 of file G4PhysicalVolumeModel.hh
Referenced by CreateCurrentAttValues(), GetFullPVPath(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetReplicaNumber(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetRotation(), G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetSolid(), and G4PhysicalVolumeModel::G4PhysicalVolumeModelTouchable::GetVolume().
G4VSolid* G4PhysicalVolumeModel::fpClippingSolid protected
Definition at line 292 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 292 of file G4PhysicalVolumeModel.hh
Referenced by GetClippingSolid(), SetClippingSolid(), and ~G4PhysicalVolumeModel().
G4LogicalVolume* G4PhysicalVolumeModel::fpCurrentLV protected
Definition at line 284 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 284 of file G4PhysicalVolumeModel.hh
Referenced by CreateCurrentAttValues(), and GetCurrentLV().
G4Material* G4PhysicalVolumeModel::fpCurrentMaterial protected
Definition at line 285 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 285 of file G4PhysicalVolumeModel.hh
Referenced by CreateCurrentAttValues(), and GetCurrentMaterial().
G4VPhysicalVolume* G4PhysicalVolumeModel::fpCurrentPV protected
Definition at line 282 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 282 of file G4PhysicalVolumeModel.hh
Referenced by CreateCurrentAttValues(), GetCurrentPV(), and GetCurrentTag().
G4Transform3D* G4PhysicalVolumeModel::fpCurrentTransform protected
Definition at line 286 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 286 of file G4PhysicalVolumeModel.hh
Referenced by CreateCurrentAttValues(), and GetCurrentTransform().
G4VPhysicalVolume* G4PhysicalVolumeModel::fpTopPV protected
Definition at line 275 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 275 of file G4PhysicalVolumeModel.hh
Referenced by CalculateExtent(), GetTopPhysicalVolume(), and Validate().
G4int G4PhysicalVolumeModel::fRequestedDepth protected
Definition at line 278 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 278 of file G4PhysicalVolumeModel.hh
Referenced by CalculateExtent(), GetRequestedDepth(), and SetRequestedDepth().
G4int G4PhysicalVolumeModel::fTopPVCopyNo protected
Definition at line 277 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 277 of file G4PhysicalVolumeModel.hh
Referenced by CalculateExtent(), and Validate().
G4String G4PhysicalVolumeModel::fTopPVName protected
Definition at line 276 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 276 of file G4PhysicalVolumeModel.hh
Referenced by Validate().
G4bool G4PhysicalVolumeModel::fUseFullExtent protected
Definition at line 280 of file G4PhysicalVolumeModel.hh.
View newest version in sPHENIX GitHub at line 280 of file G4PhysicalVolumeModel.hh
Referenced by CalculateExtent().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4PhysicalVolumeModel.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4PhysicalVolumeModel.cc