ECCE @ EIC Software: ExTGRCRegionCutsMgr Class Reference
ExTGRCRegionCutsMgr Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/P03/include/ExTGRCRegionCutsMgr.hh>
Public Member Functions
~ExTGRCRegionCutsMgr ()
void AddRegionData (const std::vector< G4String > &rd)
void AddRegionCuts (const std::vector< G4String > &rc)
std::vector< ExTGRCRegionData * > FindRegionData (const G4String &name)
void BuildRegions ()
void BuildProductionCuts ()
Static Public Member Functions
static ExTGRCRegionCutsMgr * GetInstance ()
Private Member Functions
ExTGRCRegionCutsMgr ()
Private Attributes
std::vector< ExTGRCRegionData * > fRegionDatae
Static Private Attributes
static ExTGRCRegionCutsMgr * fInstance = 0
Detailed Description
Region cuts manager
Changes: creation May 2007
Author
P. Arce
Definition at line 43 of file ExTGRCRegionCutsMgr.hh.
View newest version in sPHENIX GitHub at line 43 of file ExTGRCRegionCutsMgr.hh
Constructor & Destructor Documentation
ExTGRCRegionCutsMgr::~ExTGRCRegionCutsMgr ()
Definition at line 59 of file ExTGRCRegionCutsMgr.cc.
View newest version in sPHENIX GitHub at line 59 of file ExTGRCRegionCutsMgr.cc
References fInstance.
ExTGRCRegionCutsMgr::ExTGRCRegionCutsMgr () private
Definition at line 54 of file ExTGRCRegionCutsMgr.cc.
View newest version in sPHENIX GitHub at line 54 of file ExTGRCRegionCutsMgr.cc
Referenced by GetInstance().
Member Function Documentation
void ExTGRCRegionCutsMgr::AddRegionCuts (const std::vector< G4String > & rc)
Definition at line 79 of file ExTGRCRegionCutsMgr.cc.
View newest version in sPHENIX GitHub at line 79 of file ExTGRCRegionCutsMgr.cc
References G4UIcommand::ConvertToString(), FatalErrorInArgument, FindRegionData(), G4cerr, G4endl, and G4Exception().
Referenced by ExTGRCLineProcessor::ProcessLine().
void ExTGRCRegionCutsMgr::AddRegionData (const std::vector< G4String > & rd)
Definition at line 65 of file ExTGRCRegionCutsMgr.cc.
View newest version in sPHENIX GitHub at line 65 of file ExTGRCRegionCutsMgr.cc
References FindRegionData(), fRegionDatae, G4Exception(), and JustWarning.
Referenced by ExTGRCLineProcessor::ProcessLine().
void ExTGRCRegionCutsMgr::BuildProductionCuts ()
Definition at line 143 of file ExTGRCRegionCutsMgr.cc.
View newest version in sPHENIX GitHub at line 143 of file ExTGRCRegionCutsMgr.cc
References FatalErrorInArgument, fRegionDatae, G4Exception(), G4RegionStore::GetInstance(), G4RegionStore::GetRegion(), reg, G4ProductionCuts::SetProductionCut(), and G4Region::SetProductionCuts().
Referenced by ExTGRCDetectorBuilder::ConstructDetector().
void ExTGRCRegionCutsMgr::BuildRegions ()
Definition at line 124 of file ExTGRCRegionCutsMgr.cc.
View newest version in sPHENIX GitHub at line 124 of file ExTGRCRegionCutsMgr.cc
References G4Region::AddRootLogicalVolume(), G4tgbVolumeMgr::FindG4LogVol(), fRegionDatae, G4tgbVolumeMgr::GetInstance(), and reg.
Referenced by ExTGRCDetectorBuilder::ConstructDetector().
std::vector< ExTGRCRegionData * > ExTGRCRegionCutsMgr::FindRegionData (const G4String & name)
Definition at line 109 of file ExTGRCRegionCutsMgr.cc.
View newest version in sPHENIX GitHub at line 109 of file ExTGRCRegionCutsMgr.cc
References G4tgrUtils::AreWordsEquivalent(), and fRegionDatae.
Referenced by AddRegionCuts(), and AddRegionData().
ExTGRCRegionCutsMgr * ExTGRCRegionCutsMgr::GetInstance (void) static
Definition at line 44 of file ExTGRCRegionCutsMgr.cc.
View newest version in sPHENIX GitHub at line 44 of file ExTGRCRegionCutsMgr.cc
References ExTGRCRegionCutsMgr(), and fInstance.
Referenced by ExTGRCDetectorBuilder::ConstructDetector(), and ExTGRCLineProcessor::ProcessLine().
Member Data Documentation
ExTGRCRegionCutsMgr * ExTGRCRegionCutsMgr::fInstance = 0 static private
Definition at line 67 of file ExTGRCRegionCutsMgr.hh.
View newest version in sPHENIX GitHub at line 67 of file ExTGRCRegionCutsMgr.hh
Referenced by GetInstance(), and ~ExTGRCRegionCutsMgr().
std::vector<ExTGRCRegionData*> ExTGRCRegionCutsMgr::fRegionDatae private
Definition at line 68 of file ExTGRCRegionCutsMgr.hh.
View newest version in sPHENIX GitHub at line 68 of file ExTGRCRegionCutsMgr.hh
Referenced by AddRegionData(), BuildProductionCuts(), BuildRegions(), and FindRegionData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/P03/include/ExTGRCRegionCutsMgr.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/P03/src/ExTGRCRegionCutsMgr.cc