ECCE @ EIC Software: G4TrajectoryContainer Class Reference
G4TrajectoryContainer Class Reference
#include <geant4/tree/geant4-10.6-release/source/event/include/G4TrajectoryContainer.hh>
Public Member Functions
G4TrajectoryContainer ()
~G4TrajectoryContainer ()
G4TrajectoryContainer (const G4TrajectoryContainer &)=delete
G4TrajectoryContainer & operator= (const G4TrajectoryContainer &)=delete
void * operator new (size_t)
void operator delete (void *anEvent)
G4bool operator== (const G4TrajectoryContainer &right) const
G4bool operator!= (const G4TrajectoryContainer &right) const
size_t size () const
void push_back (G4VTrajectory *p)
size_t entries () const
G4bool insert (G4VTrajectory *p)
void clearAndDestroy ()
G4VTrajectory * operator[] (size_t n)
TrajectoryVector * GetVector () const
Private Attributes
TrajectoryVector * vect
Detailed Description
Definition at line 47 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 47 of file G4TrajectoryContainer.hh
Constructor & Destructor Documentation
G4TrajectoryContainer::G4TrajectoryContainer ()
Definition at line 37 of file G4TrajectoryContainer.cc.
View newest version in sPHENIX GitHub at line 37 of file G4TrajectoryContainer.cc
References vect.
G4TrajectoryContainer::~G4TrajectoryContainer ()
Definition at line 42 of file G4TrajectoryContainer.cc.
View newest version in sPHENIX GitHub at line 42 of file G4TrajectoryContainer.cc
References clearAndDestroy(), and vect.
G4TrajectoryContainer::G4TrajectoryContainer (const G4TrajectoryContainer &) delete
Member Function Documentation
void G4TrajectoryContainer::clearAndDestroy () inline
Definition at line 67 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 67 of file G4TrajectoryContainer.hh
References size(), and vect.
Referenced by G4Event::~G4Event(), and ~G4TrajectoryContainer().
size_t G4TrajectoryContainer::entries () const inline
Definition at line 65 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 65 of file G4TrajectoryContainer.hh
References size().
Referenced by G4TrajectoriesModel::DescribeYourselfTo(), G4Event::Draw(), DMXEventAction::drawTracks(), CexmcEventAction::DrawTrajectories(), ExGflashEventAction::EndOfEventAction(), B2EventAction::EndOfEventAction(), RE01EventAction::EndOfEventAction(), ExN02EventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), ExP01EventAction::EndOfEventAction(), RE04EventAction::EndOfEventAction(), and RE02EventAction::EndOfEventAction().
TrajectoryVector* G4TrajectoryContainer::GetVector () const inline
Definition at line 73 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 73 of file G4TrajectoryContainer.hh
References vect.
G4bool G4TrajectoryContainer::insert (G4VTrajectory * p) inline
Definition at line 66 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 66 of file G4TrajectoryContainer.hh
References push_back().
Referenced by G4EventManager::DoProcessing(), and ITTrackingInteractivity::EndTracking().
void G4TrajectoryContainer::operator delete (void * anEvent) inline
Definition at line 90 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 90 of file G4TrajectoryContainer.hh
References aTrajectoryContainerAllocator().
void * G4TrajectoryContainer::operator new (size_t) inline
Definition at line 83 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 83 of file G4TrajectoryContainer.hh
References aTrajectoryContainerAllocator().
G4bool G4TrajectoryContainer::operator!= (const G4TrajectoryContainer & right) const
Definition at line 55 of file G4TrajectoryContainer.cc.
View newest version in sPHENIX GitHub at line 55 of file G4TrajectoryContainer.cc
G4TrajectoryContainer& G4TrajectoryContainer::operator= (const G4TrajectoryContainer &) delete
G4bool G4TrajectoryContainer::operator== (const G4TrajectoryContainer & right) const
Definition at line 49 of file G4TrajectoryContainer.cc.
View newest version in sPHENIX GitHub at line 49 of file G4TrajectoryContainer.cc
G4VTrajectory* G4TrajectoryContainer::operator[] (size_t n) inline
Definition at line 72 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 72 of file G4TrajectoryContainer.hh
References n, and vect.
void G4TrajectoryContainer::push_back (G4VTrajectory * p) inline
Definition at line 64 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 64 of file G4TrajectoryContainer.hh
References vect.
Referenced by insert().
size_t G4TrajectoryContainer::size (void) const inline
Definition at line 63 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 63 of file G4TrajectoryContainer.hh
References vect.
Referenced by clearAndDestroy(), and entries().
Member Data Documentation
TrajectoryVector* G4TrajectoryContainer::vect private
Definition at line 77 of file G4TrajectoryContainer.hh.
View newest version in sPHENIX GitHub at line 77 of file G4TrajectoryContainer.hh
Referenced by clearAndDestroy(), G4TrajectoryContainer(), GetVector(), operator[](), push_back(), size(), and ~G4TrajectoryContainer().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/event/include/G4TrajectoryContainer.hh
geant4/tree/geant4-10.6-release/source/event/src/G4TrajectoryContainer.cc