ECCE @ EIC Software: G4TDigiCollection< T > Class Template Reference
G4TDigiCollection< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/digits/include/G4TDigiCollection.hh>
Public Member Functions
G4TDigiCollection ()
G4TDigiCollection (G4String detName, G4String colNam)
virtual ~G4TDigiCollection ()
G4bool operator== (const G4TDigiCollection &right) const
void * operator new (size_t)
void operator delete (void *aDC)
virtual void DrawAllDigi ()
virtual void PrintAllDigi ()
T * operator[] (size_t i) const
std::vector< T * > * GetVector () const
size_t insert (T *aHit)
size_t entries () const
virtual G4VDigi * GetDigi (size_t i) const
virtual size_t GetSize () const
Public Member Functions inherited from G4DigiCollection
G4DigiCollection ()
G4DigiCollection (G4String detName, G4String colNam)
virtual ~G4DigiCollection ()
G4bool operator== (const G4DigiCollection &right) const
Public Member Functions inherited from G4VDigiCollection
G4VDigiCollection ()
G4VDigiCollection (G4String DMnam, G4String colNam)
virtual ~G4VDigiCollection ()
G4bool operator== (const G4VDigiCollection &right) const
const G4String & GetName () const
const G4String & GetDMname () const
Additional Inherited Members
Protected Attributes inherited from G4DigiCollection
void * theCollection
Detailed Description
template<class T>
class G4TDigiCollection< T >
Definition at line 65 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 65 of file G4TDigiCollection.hh
Constructor & Destructor Documentation
template<class T > G4TDigiCollection< T >::G4TDigiCollection ()
Definition at line 146 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 146 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_().
template<class T > G4TDigiCollection< T >::G4TDigiCollection (G4String detName, G4String colNam)
Definition at line 153 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 153 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4DigiCollection::theCollection.
template<class T > G4TDigiCollection< T >::~G4TDigiCollection () virtual
Definition at line 162 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 162 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_().
Member Function Documentation
template<class T > void G4TDigiCollection< T >::DrawAllDigi () virtual
Reimplemented from G4VDigiCollection.
Definition at line 179 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 179 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and n.
template<class T> size_t G4TDigiCollection< T >::entries () const inline
Definition at line 107 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 107 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4DigiCollection::theCollection.
Referenced by GammaRayTelDigitizer::Digitize(), and GammaRayTelEventAction::EndOfEventAction().
template<class T> virtual G4VDigi* G4TDigiCollection< T >::GetDigi (size_t i) const inline virtual
Reimplemented from G4VDigiCollection.
Definition at line 117 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 117 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4DigiCollection::theCollection.
template<class T> virtual size_t G4TDigiCollection< T >::GetSize () const inline virtual
Reimplemented from G4VDigiCollection.
Definition at line 122 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 122 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4DigiCollection::theCollection.
template<class T> std::vector<T*>* G4TDigiCollection< T >::GetVector () const inline
Definition at line 91 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 91 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4DigiCollection::theCollection.
template<class T> size_t G4TDigiCollection< T >::insert (T * aHit) inline
Definition at line 97 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 97 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4DigiCollection::theCollection.
Referenced by GammaRayTelDigitizer::Digitize().
template<class T > void G4TDigiCollection< T >::operator delete (void * aDC) inline
Definition at line 139 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 139 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4Allocator< Type >::FreeSingle().
template<class T > void * G4TDigiCollection< T >::operator new (size_t) inline
Definition at line 130 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 130 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4Allocator< Type >::MallocSingle().
template<class T > G4bool G4TDigiCollection< T >::operator== (const G4TDigiCollection< T > & right) const
Definition at line 173 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 173 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4VDigiCollection::collectionName.
template<class T> T* G4TDigiCollection< T >::operator[] (size_t i) const inline
Definition at line 85 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 85 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and G4DigiCollection::theCollection.
template<class T > void G4TDigiCollection< T >::PrintAllDigi () virtual
Reimplemented from G4VDigiCollection.
Definition at line 188 of file G4TDigiCollection.hh.
View newest version in sPHENIX GitHub at line 188 of file G4TDigiCollection.hh
References aDCAllocator_G4MT_TLS_(), and n.
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/digits_hits/digits/include/G4TDigiCollection.hh