ECCE @ EIC Software: G4ee2KNeutralModel Class Reference
G4ee2KNeutralModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4ee2KNeutralModel.hh>
Public Member Functions
G4ee2KNeutralModel (G4eeCrossSections *, G4double, G4double)
virtual ~G4ee2KNeutralModel ()
virtual G4double PeakEnergy () const override
virtual G4double ComputeCrossSection (G4double) const override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, G4double, const G4ThreeVector &) override
Public Member Functions inherited from G4Vee2hadrons
G4Vee2hadrons (G4eeCrossSections *cr, G4double vlowEnergy, G4double vhighEnergy, G4double vdelta)
virtual ~G4Vee2hadrons ()
G4PhysicsVector * PhysicsVector () const
G4double LowEnergy () const
G4double HighEnergy () const
Private Member Functions
G4ee2KNeutralModel & operator= (const G4ee2KNeutralModel &right)=delete
G4ee2KNeutralModel (const G4ee2KNeutralModel &)=delete
Private Attributes
G4double massK
G4double massPhi
Additional Inherited Members
Protected Attributes inherited from G4Vee2hadrons
G4eeCrossSections * cross
Detailed Description
Definition at line 58 of file G4ee2KNeutralModel.hh.
View newest version in sPHENIX GitHub at line 58 of file G4ee2KNeutralModel.hh
Constructor & Destructor Documentation
G4ee2KNeutralModel::G4ee2KNeutralModel (G4eeCrossSections * cr, G4double maxkinEnergy, G4double binWidth) explicit
Definition at line 63 of file G4ee2KNeutralModel.cc.
View newest version in sPHENIX GitHub at line 63 of file G4ee2KNeutralModel.cc
References G4cout, G4endl, G4ParticleDefinition::GetPDGMass(), G4KaonZeroLong::KaonZeroLong(), massK, massPhi, and MeV.
G4ee2KNeutralModel::~G4ee2KNeutralModel () virtual
Definition at line 79 of file G4ee2KNeutralModel.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ee2KNeutralModel.cc
G4ee2KNeutralModel::G4ee2KNeutralModel (const G4ee2KNeutralModel &) private delete
Member Function Documentation
G4double G4ee2KNeutralModel::ComputeCrossSection (G4double e) const override virtual
Implements G4Vee2hadrons.
Definition at line 91 of file G4ee2KNeutralModel.cc.
View newest version in sPHENIX GitHub at line 91 of file G4ee2KNeutralModel.cc
References G4Vee2hadrons::cross, and G4eeCrossSections::CrossSection2Kneutral().
G4ee2KNeutralModel& G4ee2KNeutralModel::operator= (const G4ee2KNeutralModel & right) private delete
G4double G4ee2KNeutralModel::PeakEnergy () const override virtual
Implements G4Vee2hadrons.
Definition at line 84 of file G4ee2KNeutralModel.cc.
View newest version in sPHENIX GitHub at line 84 of file G4ee2KNeutralModel.cc
References massPhi.
void G4ee2KNeutralModel::SampleSecondaries (std::vector< G4DynamicParticle * > * newp, G4double e, const G4ThreeVector & direction) override virtual
Implements G4Vee2hadrons.
Definition at line 98 of file G4ee2KNeutralModel.cc.
View newest version in sPHENIX GitHub at line 98 of file G4ee2KNeutralModel.cc
References dir, G4UniformRand, G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), massK, phi, CLHEP::Hep3Vector::rotateUz(), and twopi.
Member Data Documentation
G4double G4ee2KNeutralModel::massK private
Definition at line 80 of file G4ee2KNeutralModel.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ee2KNeutralModel.hh
Referenced by G4ee2KNeutralModel(), and SampleSecondaries().
G4double G4ee2KNeutralModel::massPhi private
Definition at line 81 of file G4ee2KNeutralModel.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ee2KNeutralModel.hh
Referenced by G4ee2KNeutralModel(), and PeakEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/include/G4ee2KNeutralModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/highenergy/src/G4ee2KNeutralModel.cc