ECCE @ EIC Software: G4HadronBuilder Class Reference
G4HadronBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4HadronBuilder.hh>
Public Member Functions
G4ParticleDefinition * Build (G4ParticleDefinition *black, G4ParticleDefinition *white)
G4ParticleDefinition * BuildLowSpin (G4ParticleDefinition *black, G4ParticleDefinition *white)
G4ParticleDefinition * BuildHighSpin (G4ParticleDefinition *black, G4ParticleDefinition *white)
G4HadronBuilder (G4double mesonMix, G4double barionMix, std::vector< double > scalarMesonMix, std::vector< double > vectorMesonMix, G4double Eta_cProb, G4double Eta_bProb)
Private Types
enum Spin { SpinZero =1, SpinHalf =2, SpinOne =3, SpinThreeHalf =4 }
Private Member Functions
G4HadronBuilder ()
G4ParticleDefinition * Meson (G4ParticleDefinition *black, G4ParticleDefinition *white, Spin spin)
G4ParticleDefinition * Barion (G4ParticleDefinition *black, G4ParticleDefinition *white, Spin spin)
Private Attributes
G4double mesonSpinMix
G4double barionSpinMix
std::vector< double > scalarMesonMixings
std::vector< double > vectorMesonMixings
G4double ProbEta_c
G4double ProbEta_b
Detailed Description
Definition at line 45 of file G4HadronBuilder.hh.
View newest version in sPHENIX GitHub at line 45 of file G4HadronBuilder.hh
Member Enumeration Documentation
enum G4HadronBuilder::Spin private
Enumerator:
SpinZero
SpinHalf
SpinOne
SpinThreeHalf
Definition at line 61 of file G4HadronBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4HadronBuilder.hh
Constructor & Destructor Documentation
G4HadronBuilder::G4HadronBuilder (G4double mesonMix, G4double barionMix, std::vector< double > scalarMesonMix, std::vector< double > vectorMesonMix, G4double Eta_cProb, G4double Eta_bProb)
Definition at line 44 of file G4HadronBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4HadronBuilder.cc
References barionSpinMix, mesonSpinMix, ProbEta_b, ProbEta_c, scalarMesonMixings, and vectorMesonMixings.
G4HadronBuilder::G4HadronBuilder () private
Member Function Documentation
G4ParticleDefinition * G4HadronBuilder::Barion (G4ParticleDefinition * black, G4ParticleDefinition * white, Spin spin) private
Definition at line 194 of file G4HadronBuilder.cc.
View newest version in sPHENIX GitHub at line 194 of file G4HadronBuilder.cc
References kdfinder::abs(), charge, G4ParticleTable::FindParticle(), G4cerr, G4endl, G4UniformRand, G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), max, min, perCent, SpinHalf, and SpinThreeHalf.
Referenced by Build(), BuildHighSpin(), and BuildLowSpin().
G4ParticleDefinition * G4HadronBuilder::Build (G4ParticleDefinition * black, G4ParticleDefinition * white)
Definition at line 58 of file G4HadronBuilder.cc.
View newest version in sPHENIX GitHub at line 58 of file G4HadronBuilder.cc
References Barion(), barionSpinMix, G4UniformRand, G4ParticleDefinition::GetParticleSubType(), Meson(), mesonSpinMix, SpinHalf, SpinOne, SpinThreeHalf, and SpinZero.
Referenced by G4LundStringFragmentation::Diquark_AntiDiquark_belowThreshold_lastSplitting(), G4QGSMFragmentation::DiQuarkSplitup(), G4LundStringFragmentation::DiQuarkSplitup(), and G4VLongitudinalStringDecay::QuarkSplitup().
G4ParticleDefinition * G4HadronBuilder::BuildHighSpin (G4ParticleDefinition * black, G4ParticleDefinition * white)
Definition at line 85 of file G4HadronBuilder.cc.
View newest version in sPHENIX GitHub at line 85 of file G4HadronBuilder.cc
References Barion(), G4ParticleDefinition::GetParticleSubType(), Meson(), SpinOne, and SpinThreeHalf.
G4ParticleDefinition * G4HadronBuilder::BuildLowSpin (G4ParticleDefinition * black, G4ParticleDefinition * white)
Definition at line 73 of file G4HadronBuilder.cc.
View newest version in sPHENIX GitHub at line 73 of file G4HadronBuilder.cc
References Barion(), G4ParticleDefinition::GetParticleSubType(), Meson(), SpinHalf, and SpinZero.
Referenced by G4VLongitudinalStringDecay::PossibleHadronMass(), and G4QGSMFragmentation::SplitLast().
G4ParticleDefinition * G4HadronBuilder::Meson (G4ParticleDefinition * black, G4ParticleDefinition * white, Spin spin) private
Definition at line 96 of file G4HadronBuilder.cc.
View newest version in sPHENIX GitHub at line 96 of file G4HadronBuilder.cc
References kdfinder::abs(), charge, G4ParticleTable::FindParticle(), G4cerr, G4endl, G4UniformRand, G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGCharge(), G4ParticleDefinition::GetPDGEncoding(), perCent, ProbEta_b, ProbEta_c, scalarMesonMixings, SpinZero, and vectorMesonMixings.
Referenced by Build(), BuildHighSpin(), and BuildLowSpin().
Member Data Documentation
G4double G4HadronBuilder::barionSpinMix private
Definition at line 68 of file G4HadronBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4HadronBuilder.hh
Referenced by Build(), and G4HadronBuilder().
G4double G4HadronBuilder::mesonSpinMix private
Definition at line 67 of file G4HadronBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HadronBuilder.hh
Referenced by Build(), and G4HadronBuilder().
G4double G4HadronBuilder::ProbEta_b private
Definition at line 72 of file G4HadronBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HadronBuilder.hh
Referenced by G4HadronBuilder(), and Meson().
G4double G4HadronBuilder::ProbEta_c private
Definition at line 72 of file G4HadronBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4HadronBuilder.hh
Referenced by G4HadronBuilder(), and Meson().
std::vector<double> G4HadronBuilder::scalarMesonMixings private
Definition at line 69 of file G4HadronBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4HadronBuilder.hh
Referenced by G4HadronBuilder(), and Meson().
std::vector<double> G4HadronBuilder::vectorMesonMixings private
Definition at line 70 of file G4HadronBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4HadronBuilder.hh
Referenced by G4HadronBuilder(), and Meson().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/include/G4HadronBuilder.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/hadronization/src/G4HadronBuilder.cc