ECCE @ EIC Software: G4DeltaAngleFreeScat Class Reference
G4DeltaAngleFreeScat Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4DeltaAngleFreeScat.hh>
Public Member Functions
G4DeltaAngleFreeScat (const G4String &name="")
virtual ~G4DeltaAngleFreeScat ()
virtual G4ThreeVector & SampleDirection (const G4DynamicParticle *dp, G4double kinEnergyFinal, G4int Z, const G4Material *mat=nullptr) final
virtual void PrintGeneratorInformation () const final
Public Member Functions inherited from G4VEmAngularDistribution
G4VEmAngularDistribution (const G4String &name)
virtual ~G4VEmAngularDistribution ()
virtual G4ThreeVector & SampleDirectionForShell (const G4DynamicParticle *dp, G4double finalTotalEnergy, G4int Z, G4int shellID, const G4Material *)
virtual void SamplePairDirections (const G4DynamicParticle *dp, G4double elecKinEnergy, G4double posiKinEnergy, G4ThreeVector &dirElectron, G4ThreeVector &dirPositron, G4int Z=0, const G4Material *mat=nullptr)
const G4String & GetName () const
Private Member Functions
G4DeltaAngleFreeScat & operator= (const G4DeltaAngleFreeScat &right)=delete
G4DeltaAngleFreeScat (const G4DeltaAngleFreeScat &)=delete
Additional Inherited Members
Protected Attributes inherited from G4VEmAngularDistribution
G4ThreeVector fLocalDirection
Detailed Description
Definition at line 53 of file G4DeltaAngleFreeScat.hh.
View newest version in sPHENIX GitHub at line 53 of file G4DeltaAngleFreeScat.hh
Constructor & Destructor Documentation
G4DeltaAngleFreeScat::G4DeltaAngleFreeScat (const G4String & name = "") explicit
Definition at line 55 of file G4DeltaAngleFreeScat.cc.
View newest version in sPHENIX GitHub at line 55 of file G4DeltaAngleFreeScat.cc
G4DeltaAngleFreeScat::~G4DeltaAngleFreeScat () virtual
Definition at line 59 of file G4DeltaAngleFreeScat.cc.
View newest version in sPHENIX GitHub at line 59 of file G4DeltaAngleFreeScat.cc
G4DeltaAngleFreeScat::G4DeltaAngleFreeScat (const G4DeltaAngleFreeScat &) private delete
Member Function Documentation
G4DeltaAngleFreeScat& G4DeltaAngleFreeScat::operator= (const G4DeltaAngleFreeScat & right) private delete
void G4DeltaAngleFreeScat::PrintGeneratorInformation () const final virtual
Definition at line 82 of file G4DeltaAngleFreeScat.cc.
View newest version in sPHENIX GitHub at line 82 of file G4DeltaAngleFreeScat.cc
G4ThreeVector & G4DeltaAngleFreeScat::SampleDirection (const G4DynamicParticle * dp, G4double kinEnergyFinal, G4int Z, const G4Material * mat = nullptr) final virtual
Implements G4VEmAngularDistribution.
Definition at line 63 of file G4DeltaAngleFreeScat.cc.
View newest version in sPHENIX GitHub at line 63 of file G4DeltaAngleFreeScat.cc
References source.hepunit::electron_mass_c2, G4VEmAngularDistribution::fLocalDirection, G4UniformRand, G4DynamicParticle::GetMomentumDirection(), G4DynamicParticle::GetTotalEnergy(), G4DynamicParticle::GetTotalMomentum(), phi, CLHEP::Hep3Vector::rotateUz(), CLHEP::Hep3Vector::set(), and twopi.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4DeltaAngleFreeScat.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4DeltaAngleFreeScat.cc