ECCE @ EIC Software: G4ProcessPlacer Class Reference
G4ProcessPlacer Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4ProcessPlacer.hh>
Public Types
enum SecondOrLast { eSecond = 1, eLast = 0 }
Public Member Functions
G4ProcessPlacer (const G4String &particlename)
virtual ~G4ProcessPlacer ()
virtual void AddProcessAsLastDoIt (G4VProcess *process)
virtual void AddProcessAsSecondDoIt (G4VProcess *process)
virtual void RemoveProcess (G4VProcess *process)
Public Member Functions inherited from G4VProcessPlacer
G4VProcessPlacer ()
virtual ~G4VProcessPlacer ()
Private Member Functions
G4ProcessManager * GetProcessManager ()
void AddProcessAs (G4VProcess *process, SecondOrLast)
void PrintProcVec (G4ProcessVector *processVec)
void PrintAlongStepGPILVec ()
void PrintAlongStepDoItVec ()
void PrintPostStepGPILVec ()
void PrintPostStepDoItVec ()
Private Attributes
G4String fParticleName
Detailed Description
Definition at line 48 of file G4ProcessPlacer.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ProcessPlacer.hh
Member Enumeration Documentation
enum G4ProcessPlacer::SecondOrLast
Enumerator:
eSecond
eLast
Definition at line 71 of file G4ProcessPlacer.hh.
View newest version in sPHENIX GitHub at line 71 of file G4ProcessPlacer.hh
Constructor & Destructor Documentation
G4ProcessPlacer::G4ProcessPlacer (const G4String & particlename) explicit
Definition at line 40 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ProcessPlacer.cc
G4ProcessPlacer::~G4ProcessPlacer () virtual
Definition at line 45 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 45 of file G4ProcessPlacer.cc
Member Function Documentation
void G4ProcessPlacer::AddProcessAs (G4VProcess * process, SecondOrLast sol) private
Definition at line 78 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 78 of file G4ProcessPlacer.cc
References G4ProcessManager::AddProcess(), eLast, eSecond, G4cout, G4endl, G4Exception(), G4ProcessManager::GetProcessList(), GetProcessManager(), G4VProcess::GetProcessName(), idxAlongStep, idxPostStep, ordInActive, ordLast, PrintAlongStepDoItVec(), PrintAlongStepGPILVec(), PrintPostStepDoItVec(), PrintPostStepGPILVec(), RunMustBeAborted, and G4ProcessManager::SetProcessOrderingToSecond().
Referenced by AddProcessAsLastDoIt(), and AddProcessAsSecondDoIt().
void G4ProcessPlacer::AddProcessAsLastDoIt (G4VProcess * process) virtual
Implements G4VProcessPlacer.
Definition at line 149 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 149 of file G4ProcessPlacer.cc
References AddProcessAs(), eLast, fParticleName, G4cout, and G4endl.
Referenced by G4WeightCutOffConfigurator::Configure().
void G4ProcessPlacer::AddProcessAsSecondDoIt (G4VProcess * process) virtual
Implements G4VProcessPlacer.
Definition at line 142 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 142 of file G4ProcessPlacer.cc
References AddProcessAs(), eSecond, fParticleName, G4cout, and G4endl.
Referenced by G4WeightWindowConfigurator::Configure(), and G4ImportanceConfigurator::Configure().
G4ProcessManager * G4ProcessPlacer::GetProcessManager () private
Definition at line 156 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 156 of file G4ProcessPlacer.cc
References FatalException, fParticleName, G4Exception(), G4ParticleTable::GetIterator(), G4ParticleDefinition::GetParticleName(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetProcessManager(), particle, G4ParticleTableIterator< K, V >::reset(), theParticleIterator, and G4ParticleTableIterator< K, V >::value().
Referenced by AddProcessAs(), PrintAlongStepDoItVec(), PrintAlongStepGPILVec(), PrintPostStepDoItVec(), PrintPostStepGPILVec(), and RemoveProcess().
void G4ProcessPlacer::PrintAlongStepDoItVec () private
Definition at line 193 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 193 of file G4ProcessPlacer.cc
References G4cout, G4endl, G4ProcessManager::GetAlongStepProcessVector(), GetProcessManager(), PrintProcVec(), and typeDoIt.
Referenced by AddProcessAs(), and RemoveProcess().
void G4ProcessPlacer::PrintAlongStepGPILVec () private
Definition at line 185 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 185 of file G4ProcessPlacer.cc
References G4cout, G4endl, G4ProcessManager::GetAlongStepProcessVector(), GetProcessManager(), PrintProcVec(), and typeGPIL.
Referenced by AddProcessAs(), and RemoveProcess().
void G4ProcessPlacer::PrintPostStepDoItVec () private
Definition at line 210 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 210 of file G4ProcessPlacer.cc
References G4cout, G4endl, G4ProcessManager::GetPostStepProcessVector(), GetProcessManager(), PrintProcVec(), and typeDoIt.
Referenced by AddProcessAs(), and RemoveProcess().
void G4ProcessPlacer::PrintPostStepGPILVec () private
Definition at line 202 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 202 of file G4ProcessPlacer.cc
References G4cout, G4endl, G4ProcessManager::GetPostStepProcessVector(), GetProcessManager(), PrintProcVec(), and typeGPIL.
Referenced by AddProcessAs(), and RemoveProcess().
void G4ProcessPlacer::PrintProcVec (G4ProcessVector * processVec) private
Definition at line 219 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 219 of file G4ProcessPlacer.cc
References FatalException, G4cout, G4endl, G4Exception(), G4VProcess::GetProcessName(), and G4ProcessVector::length().
Referenced by PrintAlongStepDoItVec(), PrintAlongStepGPILVec(), PrintPostStepDoItVec(), and PrintPostStepGPILVec().
void G4ProcessPlacer::RemoveProcess (G4VProcess * process) virtual
Implements G4VProcessPlacer.
Definition at line 49 of file G4ProcessPlacer.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ProcessPlacer.cc
References fParticleName, G4cout, G4endl, GetProcessManager(), G4VProcess::GetProcessName(), PrintAlongStepDoItVec(), PrintAlongStepGPILVec(), PrintPostStepDoItVec(), PrintPostStepGPILVec(), and G4ProcessManager::RemoveProcess().
Referenced by G4ImportanceConfigurator::~G4ImportanceConfigurator(), G4WeightCutOffConfigurator::~G4WeightCutOffConfigurator(), and G4WeightWindowConfigurator::~G4WeightWindowConfigurator().
Member Data Documentation
G4String G4ProcessPlacer::fParticleName private
Definition at line 90 of file G4ProcessPlacer.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ProcessPlacer.hh
Referenced by AddProcessAsLastDoIt(), AddProcessAsSecondDoIt(), GetProcessManager(), and RemoveProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/management/include/G4ProcessPlacer.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/management/src/G4ProcessPlacer.cc