ECCE @ EIC Software: G4QGSBuilder Class Reference
G4QGSBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBuilder.hh>
Public Member Functions
G4QGSBuilder (const G4String &name="", G4PreCompoundModel *p=0, G4bool quasiElastic=true)
virtual ~G4QGSBuilder ()
Public Member Functions inherited from G4VHadronModelBuilder
G4VHadronModelBuilder (const G4String &name="")
virtual ~G4VHadronModelBuilder ()
G4HadronicInteraction * GetModel ()
const G4String & GetName () const
Protected Member Functions
virtual G4HadronicInteraction * BuildModel ()
Private Member Functions
G4QGSBuilder (G4QGSBuilder &)
G4QGSBuilder & operator= (const G4QGSBuilder &right)
Private Attributes
G4QGSModel< G4QGSParticipants > * theQGStringModel
G4ExcitedStringDecay * theQGStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4PreCompoundModel * thePreCompound
G4QGSMFragmentation * theQGSM
G4bool quasielFlag
Detailed Description
Definition at line 50 of file G4QGSBuilder.hh.
View newest version in sPHENIX GitHub at line 50 of file G4QGSBuilder.hh
Constructor & Destructor Documentation
G4QGSBuilder::G4QGSBuilder (const G4String & name = "", G4PreCompoundModel * p = 0, G4bool quasiElastic = true)
Definition at line 50 of file G4QGSBuilder.cc.
View newest version in sPHENIX GitHub at line 50 of file G4QGSBuilder.cc
G4QGSBuilder::~G4QGSBuilder () virtual
Definition at line 58 of file G4QGSBuilder.cc.
View newest version in sPHENIX GitHub at line 58 of file G4QGSBuilder.cc
References theQGSM, theQGStringDecay, theQGStringModel, and theQuasiElastic.
G4QGSBuilder::G4QGSBuilder (G4QGSBuilder &) private
Member Function Documentation
G4HadronicInteraction * G4QGSBuilder::BuildModel () protected virtual
Implements G4VHadronModelBuilder.
Definition at line 66 of file G4QGSBuilder.cc.
View newest version in sPHENIX GitHub at line 66 of file G4QGSBuilder.cc
References G4VHadronModelBuilder::GetName(), quasielFlag, G4VIntraNuclearTransportModel::SetDeExcitation(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), thePreCompound, theQGSM, theQGStringDecay, theQGStringModel, and theQuasiElastic.
G4QGSBuilder& G4QGSBuilder::operator= (const G4QGSBuilder & right) private
Member Data Documentation
G4bool G4QGSBuilder::quasielFlag private
Definition at line 78 of file G4QGSBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSBuilder.hh
Referenced by BuildModel().
G4PreCompoundModel* G4QGSBuilder::thePreCompound private
Definition at line 75 of file G4QGSBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSBuilder.hh
Referenced by BuildModel().
G4QGSMFragmentation* G4QGSBuilder::theQGSM private
Definition at line 76 of file G4QGSBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSBuilder.hh
Referenced by BuildModel(), and ~G4QGSBuilder().
G4ExcitedStringDecay* G4QGSBuilder::theQGStringDecay private
Definition at line 72 of file G4QGSBuilder.hh.
View newest version in sPHENIX GitHub at line 72 of file G4QGSBuilder.hh
Referenced by BuildModel(), and ~G4QGSBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSBuilder::theQGStringModel private
Definition at line 70 of file G4QGSBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QGSBuilder.hh
Referenced by BuildModel(), and ~G4QGSBuilder().
G4QuasiElasticChannel* G4QGSBuilder::theQuasiElastic private
Definition at line 73 of file G4QGSBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QGSBuilder.hh
Referenced by BuildModel(), and ~G4QGSBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSBuilder.cc