ECCE @ EIC Software: G4ParticleTypeConverter Class Reference
G4ParticleTypeConverter Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4ParticleTypeConverter.hh>
Public Types
enum GenericType {
NUCLEON, N1440, N1520, N1535,
N1650, N1675, N1680, N1700,
N1710, N1720, N1900, N1990,
N2090, N2190, N2220, N2250,
D1232, D1600, D1620, D1700,
D1900, D1905, D1910, D1920,
D1930, D1950, L1405, L1520,
L1600, L1670, L1690, L1800,
L1810, L1820, L1830, L1890,
L2100, L2110, Sigma, S1385,
S1660, S1670, S1750, S1775,
S1915, S1940, S2030, X1530,
X1690, X1820, X1950, X2030,
GAMMA, PION, KAON, ETA,
RHO, omega, Lambda, UNKNOWN
}
Public Member Functions
G4ParticleTypeConverter ()
GenericType GetGenericType (const G4ParticleDefinition *const aParticleDef) const
GenericType GetGenericType (const G4KineticTrack &aTrack) const
GenericType GetGenericType (const G4String &aParticleName) const
G4int GetUrqmdItyp (GenericType gType) const
G4int GetUrqmdItyp (const G4ParticleDefinition *aParticleDef) const
const G4ParticleDefinition * FindIso3State (const GenericType gType, const G4int isospin3) const
Private Types
typedef std::vector< std::pair
< const G4ParticleDefinition
*, GenericType >
>::const_iterator MapIterator
Private Attributes
std::vector< std::pair< const
G4ParticleDefinition
*, GenericType > > defMap
Detailed Description
Definition at line 35 of file G4ParticleTypeConverter.hh.
View newest version in sPHENIX GitHub at line 35 of file G4ParticleTypeConverter.hh
Member Typedef Documentation
typedef std::vector<std::pair<const G4ParticleDefinition*, GenericType> >::const_iterator G4ParticleTypeConverter::MapIterator private
Definition at line 60 of file G4ParticleTypeConverter.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleTypeConverter.hh
Member Enumeration Documentation
enum G4ParticleTypeConverter::GenericType
Enumerator:
NUCLEON
N1440
N1520
N1535
N1650
N1675
N1680
N1700
N1710
N1720
N1900
N1990
N2090
N2190
N2220
N2250
D1232
D1600
D1620
D1700
D1900
D1905
D1910
D1920
D1930
D1950
L1405
L1520
L1600
L1670
L1690
L1800
L1810
L1820
L1830
L1890
L2100
L2110
Sigma
S1385
S1660
S1670
S1750
S1775
S1915
S1940
S2030
X1530
X1690
X1820
X1950
X2030
GAMMA
PION
KAON
ETA
RHO
omega
Lambda
UNKNOWN
Definition at line 39 of file G4ParticleTypeConverter.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleTypeConverter.hh
Constructor & Destructor Documentation
G4ParticleTypeConverter::G4ParticleTypeConverter ()
Definition at line 46 of file G4ParticleTypeConverter.cc.
View newest version in sPHENIX GitHub at line 46 of file G4ParticleTypeConverter.cc
References G4AntiKaonZero::AntiKaonZeroDefinition(), G4ShortLivedConstructor::ConstructParticle(), D1600, D1620, D1700, D1900, D1905, D1910, D1920, D1930, D1950, defMap, ETA, GAMMA, G4Gamma::GammaDefinition(), G4ParticleTable::GetParticleTable(), KAON, G4KaonMinus::KaonMinusDefinition(), G4KaonPlus::KaonPlusDefinition(), G4KaonZero::KaonZeroDefinition(), G4KaonZeroLong::KaonZeroLongDefinition(), G4KaonZeroShort::KaonZeroShortDefinition(), L1405, L1520, L1600, L1670, L1690, L1800, L1810, L1820, L1830, L1890, L2100, L2110, Lambda, G4Lambda::LambdaDefinition(), N1440, N1520, N1535, N1650, N1675, N1680, N1700, N1710, N1720, N1900, N1990, N2090, N2190, N2220, N2250, G4Neutron::NeutronDefinition(), NUCLEON, omega, PION, G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), G4PionZero::PionZeroDefinition(), G4Proton::ProtonDefinition(), RHO, S1385, S1660, S1670, S1750, S1775, S1915, S1940, S2030, Sigma, X1530, X1690, X1820, X1950, and X2030.
Member Function Documentation
const G4ParticleDefinition * G4ParticleTypeConverter::FindIso3State (const GenericType gType, const G4int isospin3) const
Definition at line 240 of file G4ParticleTypeConverter.cc.
View newest version in sPHENIX GitHub at line 240 of file G4ParticleTypeConverter.cc
References defMap.
G4ParticleTypeConverter::GenericType G4ParticleTypeConverter::GetGenericType (const G4ParticleDefinition *const aParticleDef) const
Definition at line 214 of file G4ParticleTypeConverter.cc.
View newest version in sPHENIX GitHub at line 214 of file G4ParticleTypeConverter.cc
References defMap, and UNKNOWN.
Referenced by GetGenericType(), and G4ConcreteMesonBaryonToResonance::GetOutgoingParticle().
G4ParticleTypeConverter::GenericType G4ParticleTypeConverter::GetGenericType (const G4KineticTrack & aTrack) const
Definition at line 226 of file G4ParticleTypeConverter.cc.
View newest version in sPHENIX GitHub at line 226 of file G4ParticleTypeConverter.cc
References G4KineticTrack::GetDefinition(), and GetGenericType().
GenericType G4ParticleTypeConverter::GetGenericType (const G4String & aParticleName) const
G4int G4ParticleTypeConverter::GetUrqmdItyp (G4ParticleTypeConverter::GenericType gType) const
Definition at line 231 of file G4ParticleTypeConverter.cc.
View newest version in sPHENIX GitHub at line 231 of file G4ParticleTypeConverter.cc
G4int G4ParticleTypeConverter::GetUrqmdItyp (const G4ParticleDefinition * aParticleDef) const
Member Data Documentation
std::vector<std::pair<const G4ParticleDefinition*, GenericType> > G4ParticleTypeConverter::defMap private
Definition at line 61 of file G4ParticleTypeConverter.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParticleTypeConverter.hh
Referenced by FindIso3State(), G4ParticleTypeConverter(), and GetGenericType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4ParticleTypeConverter.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4ParticleTypeConverter.cc