ECCE @ EIC Software: G4tgbMaterialSimple Class Reference
G4tgbMaterialSimple Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialSimple.hh>
Public Member Functions
G4tgbMaterialSimple ()
~G4tgbMaterialSimple ()
G4tgbMaterialSimple (G4tgrMaterial *tgr)
G4Material * BuildG4Material ()
G4double GetZ () const
G4double GetA () const
Public Member Functions inherited from G4tgbMaterial
G4tgbMaterial ()
virtual ~G4tgbMaterial ()
G4tgbMaterial (G4tgrMaterial *tgr)
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfMaterials () const
G4double GetA () const
G4double GetZ () const
const G4String & GetType () const
G4tgrMaterial * GetTgrMate () const
Private Attributes
G4double theZ
G4double theA
Friends
std::ostream & operator<< (std::ostream &, const G4tgbMaterialSimple &)
Additional Inherited Members
Protected Attributes inherited from G4tgbMaterial
G4tgrMaterial * theTgrMate
G4Material * theG4Mate
Detailed Description
Definition at line 50 of file G4tgbMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 50 of file G4tgbMaterialSimple.hh
Constructor & Destructor Documentation
G4tgbMaterialSimple::G4tgbMaterialSimple ()
Definition at line 42 of file G4tgbMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 42 of file G4tgbMaterialSimple.cc
G4tgbMaterialSimple::~G4tgbMaterialSimple ()
Definition at line 49 of file G4tgbMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgbMaterialSimple.cc
G4tgbMaterialSimple::G4tgbMaterialSimple (G4tgrMaterial * tgr)
Definition at line 55 of file G4tgbMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgbMaterialSimple.cc
References G4tgrMaterialSimple::GetA(), G4tgrMaterialSimple::GetZ(), theA, G4tgbMaterial::theTgrMate, and theZ.
Member Function Documentation
G4Material * G4tgbMaterialSimple::BuildG4Material () virtual
Implements G4tgbMaterial.
Definition at line 65 of file G4tgbMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 65 of file G4tgbMaterialSimple.cc
References G4cout, G4endl, GetA(), G4tgrMaterial::GetDensity(), G4tgbMaterial::GetName(), G4tgrMessenger::GetVerboseLevel(), GetZ(), kStateUndefined, source.hepunit::STP_Temperature, and G4tgbMaterial::theTgrMate.
G4double G4tgbMaterialSimple::GetA () const inline
Definition at line 67 of file G4tgbMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 67 of file G4tgbMaterialSimple.hh
References theA.
Referenced by BuildG4Material(), and operator<<().
G4double G4tgbMaterialSimple::GetZ () const inline
Definition at line 66 of file G4tgbMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 66 of file G4tgbMaterialSimple.hh
References theZ.
Referenced by BuildG4Material(), and operator<<().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgbMaterialSimple & mate) friend
Definition at line 85 of file G4tgbMaterialSimple.cc.
View newest version in sPHENIX GitHub at line 85 of file G4tgbMaterialSimple.cc
Member Data Documentation
G4double G4tgbMaterialSimple::theA private
Definition at line 72 of file G4tgbMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 72 of file G4tgbMaterialSimple.hh
Referenced by G4tgbMaterialSimple(), and GetA().
G4double G4tgbMaterialSimple::theZ private
Definition at line 71 of file G4tgbMaterialSimple.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgbMaterialSimple.hh
Referenced by G4tgbMaterialSimple(), and GetZ().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgbMaterialSimple.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgbMaterialSimple.cc