ECCE @ EIC Software: G4INCL::ReflectionChannel Class Reference
G4INCL::ReflectionChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLReflectionChannel.hh>
Public Member Functions
ReflectionChannel (Nucleus *n, Particle *p)
virtual ~ReflectionChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Attributes
Nucleus * theNucleus
Particle * theParticle
Static Private Attributes
static const G4double sinMinReflectionAngleSquaredOverFour = std::pow(std::sin(2.*Math::pi/200.),2.)
Sine^2 of the smallest acceptable reflection angle / 4.
static const G4double positionScalingFactor = 0.99
Scaling factor for excessively tangential reflection.
Detailed Description
Definition at line 48 of file G4INCLReflectionChannel.hh.
View newest version in sPHENIX GitHub at line 48 of file G4INCLReflectionChannel.hh
Constructor & Destructor Documentation
G4INCL::ReflectionChannel::ReflectionChannel (Nucleus * n, Particle * p)
Definition at line 49 of file G4INCLReflectionChannel.cc.
View newest version in sPHENIX GitHub at line 49 of file G4INCLReflectionChannel.cc
G4INCL::ReflectionChannel::~ReflectionChannel () virtual
Definition at line 54 of file G4INCLReflectionChannel.cc.
View newest version in sPHENIX GitHub at line 54 of file G4INCLReflectionChannel.cc
Member Function Documentation
void G4INCL::ReflectionChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 58 of file G4INCLReflectionChannel.cc.
View newest version in sPHENIX GitHub at line 58 of file G4INCLReflectionChannel.cc
References G4INCL::FinalState::addModifiedParticle(), G4INCL::ThreeVector::dot(), G4INCL::Particle::getEnergy(), G4INCL::Particle::getID(), G4INCL::Particle::getMomentum(), G4INCL::Particle::getPosition(), G4INCL::Particle::getPotentialEnergy(), G4INCL::ThreeVector::getX(), G4INCL::ThreeVector::getY(), G4INCL::ThreeVector::getZ(), INCL_DEBUG, G4INCL::ThreeVector::mag2(), positionScalingFactor, G4INCL::Particle::setMomentum(), G4INCL::Particle::setPosition(), G4INCL::FinalState::setTotalEnergyBeforeInteraction(), sinMinReflectionAngleSquaredOverFour, G4INCL::Particle::thawPropagation(), theNucleus, theParticle, and G4INCL::Nucleus::updatePotentialEnergy().
Member Data Documentation
const G4double G4INCL::ReflectionChannel::positionScalingFactor = 0.99 static private
Scaling factor for excessively tangential reflection.
Definition at line 67 of file G4INCLReflectionChannel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLReflectionChannel.hh
Referenced by fillFinalState().
const G4double G4INCL::ReflectionChannel::sinMinReflectionAngleSquaredOverFour = std::pow(std::sin(2.*Math::pi/200.),2.) static private
Sine^2 of the smallest acceptable reflection angle / 4.
Particles impinging almost tangentially on the surface generate a large number of reflections. If the impinging angle is larger than a certain limit, we move the particle a bit towards the inside of the nucleus. The limit angle is arbitrarily chosen to correspond to 100 reflections per orbit. The position scaling factor is given by the positionScalingFactor member.
Definition at line 65 of file G4INCLReflectionChannel.hh.
View newest version in sPHENIX GitHub at line 65 of file G4INCLReflectionChannel.hh
Referenced by fillFinalState().
Nucleus* G4INCL::ReflectionChannel::theNucleus private
Definition at line 68 of file G4INCLReflectionChannel.hh.
View newest version in sPHENIX GitHub at line 68 of file G4INCLReflectionChannel.hh
Referenced by fillFinalState().
Particle* G4INCL::ReflectionChannel::theParticle private
Definition at line 69 of file G4INCLReflectionChannel.hh.
View newest version in sPHENIX GitHub at line 69 of file G4INCLReflectionChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLReflectionChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLReflectionChannel.cc