ECCE @ EIC Software: G4tgrMaterialFactory Class Reference
G4tgrMaterialFactory Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrMaterialFactory.hh>
Public Member Functions
~G4tgrMaterialFactory ()
G4tgrIsotope * AddIsotope (const std::vector< G4String > &wl)
G4tgrElementSimple * AddElementSimple (const std::vector< G4String > &wl)
G4tgrElementFromIsotopes * AddElementFromIsotopes (const std::vector< G4String > &wl)
G4tgrMaterialSimple * AddMaterialSimple (const std::vector< G4String > &wl)
G4tgrMaterialMixture * AddMaterialMixture (const std::vector< G4String > &wl, const G4String &mixtType)
G4tgrIsotope * FindIsotope (const G4String &name) const
G4tgrElement * FindElement (const G4String &name) const
G4tgrMaterial * FindMaterial (const G4String &name) const
void DumpIsotopeList () const
void DumpElementList () const
void DumpMaterialList () const
const G4mstgrisot & GetIsotopeList () const
const G4mstgrelem & GetElementList () const
const G4mstgrmate & GetMaterialList () const
Static Public Member Functions
static G4tgrMaterialFactory * GetInstance ()
Private Member Functions
G4tgrMaterialFactory ()
void ErrorAlreadyExists (const G4String &object, const std::vector< G4String > &wl, const G4bool bNoRepeating=true)
Private Attributes
G4mstgrisot theG4tgrIsotopes
G4mstgrelem theG4tgrElements
G4mstgrmate theG4tgrMaterials
Static Private Attributes
static G4ThreadLocal
G4tgrMaterialFactory * theInstance = 0
Detailed Description
Definition at line 57 of file G4tgrMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 57 of file G4tgrMaterialFactory.hh
Constructor & Destructor Documentation
G4tgrMaterialFactory::~G4tgrMaterialFactory ()
Definition at line 66 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 66 of file G4tgrMaterialFactory.cc
References theG4tgrElements, theG4tgrIsotopes, theG4tgrMaterials, and theInstance.
G4tgrMaterialFactory::G4tgrMaterialFactory () private
Definition at line 49 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgrMaterialFactory.cc
Referenced by GetInstance().
Member Function Documentation
G4tgrElementFromIsotopes * G4tgrMaterialFactory::AddElementFromIsotopes (const std::vector< G4String > & wl)
Definition at line 130 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 130 of file G4tgrMaterialFactory.cc
References ErrorAlreadyExists(), FindElement(), G4tgrElement::GetName(), G4tgrUtils::GetString(), and theG4tgrElements.
Referenced by G4tgrLineProcessor::ProcessLine().
G4tgrElementSimple * G4tgrMaterialFactory::AddElementSimple (const std::vector< G4String > & wl)
Definition at line 113 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 113 of file G4tgrMaterialFactory.cc
References ErrorAlreadyExists(), FindElement(), G4tgrElement::GetName(), G4tgrUtils::GetString(), and theG4tgrElements.
Referenced by G4tgrLineProcessor::ProcessLine().
G4tgrIsotope * G4tgrMaterialFactory::AddIsotope (const std::vector< G4String > & wl)
Definition at line 97 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 97 of file G4tgrMaterialFactory.cc
References ErrorAlreadyExists(), FindIsotope(), G4tgrIsotope::GetName(), G4tgrUtils::GetString(), and theG4tgrIsotopes.
Referenced by G4tgrLineProcessor::ProcessLine().
G4tgrMaterialMixture * G4tgrMaterialFactory::AddMaterialMixture (const std::vector< G4String > & wl, const G4String & mixtType)
Definition at line 173 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 173 of file G4tgrMaterialFactory.cc
References ErrorAlreadyExists(), FindMaterial(), G4cout, G4endl, G4tgrMaterial::GetName(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), and theG4tgrMaterials.
Referenced by G4tgrLineProcessor::ProcessLine().
G4tgrMaterialSimple * G4tgrMaterialFactory::AddMaterialSimple (const std::vector< G4String > & wl)
Definition at line 147 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 147 of file G4tgrMaterialFactory.cc
References ErrorAlreadyExists(), FindMaterial(), G4cout, G4endl, G4tgrMaterial::GetName(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), and theG4tgrMaterials.
Referenced by G4tgrLineProcessor::ProcessLine().
void G4tgrMaterialFactory::DumpElementList () const
Definition at line 294 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 294 of file G4tgrMaterialFactory.cc
References G4cout, G4endl, and theG4tgrElements.
Referenced by G4tgrVolumeMgr::DumpSummary(), and FindElement().
void G4tgrMaterialFactory::DumpIsotopeList () const
Definition at line 282 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 282 of file G4tgrMaterialFactory.cc
References G4cout, G4endl, and theG4tgrIsotopes.
Referenced by G4tgrVolumeMgr::DumpSummary().
void G4tgrMaterialFactory::DumpMaterialList () const
Definition at line 306 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 306 of file G4tgrMaterialFactory.cc
References G4cout, G4endl, G4tgrMaterial::GetName(), G4tgrMaterial::GetNumberOfComponents(), G4tgrMaterial::GetType(), and theG4tgrMaterials.
Referenced by G4tgrVolumeMgr::DumpSummary().
void G4tgrMaterialFactory::ErrorAlreadyExists (const G4String & object, const std::vector< G4String > & wl, const G4bool bNoRepeating = true) private
Definition at line 321 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 321 of file G4tgrMaterialFactory.cc
References G4tgrUtils::DumpVS(), FatalException, G4Exception(), and G4tgrMessenger::GetVerboseLevel().
Referenced by AddElementFromIsotopes(), AddElementSimple(), AddIsotope(), AddMaterialMixture(), and AddMaterialSimple().
G4tgrElement * G4tgrMaterialFactory::FindElement (const G4String & name) const
Definition at line 230 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 230 of file G4tgrMaterialFactory.cc
References DumpElementList(), G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theG4tgrElements.
Referenced by AddElementFromIsotopes(), and AddElementSimple().
G4tgrIsotope * G4tgrMaterialFactory::FindIsotope (const G4String & name) const
Definition at line 200 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 200 of file G4tgrMaterialFactory.cc
References G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theG4tgrIsotopes.
Referenced by AddIsotope().
G4tgrMaterial * G4tgrMaterialFactory::FindMaterial (const G4String & name) const
Definition at line 260 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 260 of file G4tgrMaterialFactory.cc
References G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theG4tgrMaterials.
Referenced by AddMaterialMixture(), AddMaterialSimple(), and G4tgrLineProcessor::ProcessLine().
const G4mstgrelem& G4tgrMaterialFactory::GetElementList () const inline
Definition at line 100 of file G4tgrMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 100 of file G4tgrMaterialFactory.hh
References theG4tgrElements.
Referenced by G4tgbMaterialMgr::CopyElements(), and G4tgrVolumeMgr::DumpSummary().
G4tgrMaterialFactory * G4tgrMaterialFactory::GetInstance (void) static
Definition at line 55 of file G4tgrMaterialFactory.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgrMaterialFactory.cc
References G4tgrMaterialFactory(), and theInstance.
Referenced by G4tgbMaterialMgr::CopyElements(), G4tgbMaterialMgr::CopyIsotopes(), G4tgbMaterialMgr::CopyMaterials(), G4tgrVolumeMgr::DumpSummary(), and G4tgrLineProcessor::ProcessLine().
const G4mstgrisot& G4tgrMaterialFactory::GetIsotopeList () const inline
Definition at line 99 of file G4tgrMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 99 of file G4tgrMaterialFactory.hh
References theG4tgrIsotopes.
Referenced by G4tgbMaterialMgr::CopyIsotopes(), and G4tgrVolumeMgr::DumpSummary().
const G4mstgrmate& G4tgrMaterialFactory::GetMaterialList () const inline
Definition at line 101 of file G4tgrMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 101 of file G4tgrMaterialFactory.hh
References theG4tgrMaterials.
Referenced by G4tgbMaterialMgr::CopyMaterials(), and G4tgrVolumeMgr::DumpSummary().
Member Data Documentation
G4mstgrelem G4tgrMaterialFactory::theG4tgrElements private
Definition at line 117 of file G4tgrMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 117 of file G4tgrMaterialFactory.hh
Referenced by AddElementFromIsotopes(), AddElementSimple(), DumpElementList(), FindElement(), GetElementList(), and ~G4tgrMaterialFactory().
G4mstgrisot G4tgrMaterialFactory::theG4tgrIsotopes private
Definition at line 115 of file G4tgrMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 115 of file G4tgrMaterialFactory.hh
Referenced by AddIsotope(), DumpIsotopeList(), FindIsotope(), GetIsotopeList(), and ~G4tgrMaterialFactory().
G4mstgrmate G4tgrMaterialFactory::theG4tgrMaterials private
Definition at line 119 of file G4tgrMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 119 of file G4tgrMaterialFactory.hh
Referenced by AddMaterialMixture(), AddMaterialSimple(), DumpMaterialList(), FindMaterial(), GetMaterialList(), and ~G4tgrMaterialFactory().
G4ThreadLocal G4tgrMaterialFactory * G4tgrMaterialFactory::theInstance = 0 static private
Definition at line 113 of file G4tgrMaterialFactory.hh.
View newest version in sPHENIX GitHub at line 113 of file G4tgrMaterialFactory.hh
Referenced by GetInstance(), and ~G4tgrMaterialFactory().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrMaterialFactory.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrMaterialFactory.cc