ECCE @ EIC Software: G4GNASHTransitions Class Reference
G4GNASHTransitions Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4GNASHTransitions.hh>
Public Member Functions
G4GNASHTransitions ()
virtual ~G4GNASHTransitions ()
virtual G4double CalculateProbability (const G4Fragment &aFragment)
virtual void PerformTransition (G4Fragment &aFragment)
Public Member Functions inherited from G4VPreCompoundTransitions
G4VPreCompoundTransitions ()
virtual ~G4VPreCompoundTransitions ()
G4double GetTransitionProb1 () const
G4double GetTransitionProb2 () const
G4double GetTransitionProb3 () const
void UseNGB (G4bool use)
void UseCEMtr (G4bool use)
Private Member Functions
G4GNASHTransitions (const G4GNASHTransitions &)=delete
const G4GNASHTransitions & operator= (const G4GNASHTransitions &right)=delete
G4bool operator== (const G4GNASHTransitions &right) const =delete
G4bool operator!= (const G4GNASHTransitions &right) const =delete
Private Attributes
G4DeexPrecoParameters * theParameters
Additional Inherited Members
Protected Attributes inherited from G4VPreCompoundTransitions
G4bool useNGB
G4bool useCEMtr
G4double TransitionProb1
G4double TransitionProb2
G4double TransitionProb3
Detailed Description
Definition at line 35 of file G4GNASHTransitions.hh.
View newest version in sPHENIX GitHub at line 35 of file G4GNASHTransitions.hh
Constructor & Destructor Documentation
G4GNASHTransitions::G4GNASHTransitions () explicit
Definition at line 37 of file G4GNASHTransitions.cc.
View newest version in sPHENIX GitHub at line 37 of file G4GNASHTransitions.cc
References G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetParameters(), and theParameters.
G4GNASHTransitions::~G4GNASHTransitions () virtual
Definition at line 42 of file G4GNASHTransitions.cc.
View newest version in sPHENIX GitHub at line 42 of file G4GNASHTransitions.cc
G4GNASHTransitions::G4GNASHTransitions (const G4GNASHTransitions &) private delete
Member Function Documentation
G4double G4GNASHTransitions::CalculateProbability (const G4Fragment & aFragment) virtual
Implements G4VPreCompoundTransitions.
Definition at line 46 of file G4GNASHTransitions.cc.
View newest version in sPHENIX GitHub at line 46 of file G4GNASHTransitions.cc
References A(), E, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4NuclearLevelData::GetInstance(), G4NuclearLevelData::GetLevelDensity(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), G4Fragment::GetZ_asInt(), H, CLHEP::h_Planck, k, CLHEP::MeV, N, P, pi2, x, and Z.
G4bool G4GNASHTransitions::operator!= (const G4GNASHTransitions & right) const private delete
const G4GNASHTransitions& G4GNASHTransitions::operator= (const G4GNASHTransitions & right) private delete
G4bool G4GNASHTransitions::operator== (const G4GNASHTransitions & right) const private delete
void G4GNASHTransitions::PerformTransition (G4Fragment & aFragment) virtual
Implements G4VPreCompoundTransitions.
Definition at line 74 of file G4GNASHTransitions.cc.
View newest version in sPHENIX GitHub at line 74 of file G4GNASHTransitions.cc
References G4UniformRand, G4Fragment::GetA_asInt(), G4Fragment::GetNumberOfCharged(), G4Fragment::GetNumberOfHoles(), G4Fragment::GetNumberOfParticles(), G4Fragment::GetZ_asInt(), G4Fragment::SetNumberOfCharged(), G4Fragment::SetNumberOfHoles(), and G4Fragment::SetNumberOfParticles().
Member Data Documentation
G4DeexPrecoParameters* G4GNASHTransitions::theParameters private
Definition at line 54 of file G4GNASHTransitions.hh.
View newest version in sPHENIX GitHub at line 54 of file G4GNASHTransitions.hh
Referenced by G4GNASHTransitions().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/include/G4GNASHTransitions.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/pre_equilibrium/exciton_model/src/G4GNASHTransitions.cc