ECCE @ EIC Software: STCyclotronDetectorConstruction Class Reference
STCyclotronDetectorConstruction Class Reference
Detector construction class to define materials and geometry.
#include <geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/include/STCyclotronDetectorConstruction.hh>
Public Member Functions
STCyclotronDetectorConstruction ()
~STCyclotronDetectorConstruction ()
G4VPhysicalVolume * Construct ()
void ConstructSDandField ()
void SetTargetDiameter (G4double)
void SetTargetIsotopeName (G4String)
void SetTargetIsotopeZ (G4double)
void SetTargetIsotopeN (G4int)
void SetTargetIsotopeA (G4double)
void SetTargetElementName (G4String)
void SetTargetElementSymbole (G4String)
void SetTargetElementNComponents (G4int)
void SetTargetElementAbundance (G4double)
void SetTargetMaterialDensity (G4double)
void SetTargetMaterialNComponents (G4int)
void SetTargetMaterialFractionMass (G4double)
void SetTargetNaturalElement (G4String)
void SetTargetNaturalMaterialFractionMass (G4double)
G4bool UpdateMaterial ()
void SetTargetMaterial (G4String)
void SetFoilIsotopeName (G4String)
void SetFoilIsotopeZ (G4double)
void SetFoilIsotopeN (G4int)
void SetFoilIsotopeA (G4double)
void SetFoilElementName (G4String)
void SetFoilElementSymbole (G4String)
void SetFoilElementNComponents (G4int)
void SetFoilElementAbundance (G4double)
void SetFoilMaterialDensity (G4double)
void SetFoilMaterialNComponents (G4int)
void SetFoilMaterialFractionMass (G4double)
void SetFoilNaturalElement (G4String)
void SetFoilNaturalMaterialFractionMass (G4double)
G4bool UpdateFoilMaterial ()
void SetFoilMaterial (G4String)
void SetTargetThickness (G4double)
void SetFoilThickness (G4double)
G4double GetTargetPosition1 ()
G4double GetTargetPosition2 ()
G4double GetVolumeTarget ()
G4double GetFoilPosition1 ()
G4double GetTargetVolume ()
G4double GetFoilVolume ()
G4double GetFoilThickness ()
G4double GetTargetThickness ()
G4double GetTargetDiameter ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Attributes
STCyclotronDetectorMessenger * fDetectorMessenger
G4double fTarget_diameter
std::vector< G4String > fIsotopeName
std::vector< G4double > fIsotopeZ
std::vector< G4int > fIsotopeN
std::vector< G4double > fIsotopeA
std::vector< G4String > fElementName
std::vector< G4String > fElementSymbole
std::vector< G4int > fElementNComponents
std::vector< G4double > fElementAbundance
std::vector< G4String > fNaturalElementName
std::vector< G4double > fNaturalMaterialFractionMass
G4double fDensity_target
G4int fTarget_NComponents
std::vector< G4double > fMaterialFractionMass
std::vector< G4String > fIsotopeNameFoil
std::vector< G4double > fIsotopeZFoil
std::vector< G4int > fIsotopeNFoil
std::vector< G4double > fIsotopeAFoil
std::vector< G4String > fElementNameFoil
std::vector< G4String > fElementSymboleFoil
std::vector< G4int > fElementNComponentsFoil
std::vector< G4double > fElementAbundanceFoil
std::vector< G4String > fNaturalElementNameFoil
std::vector< G4double > fNaturalMaterialFractionMassFoil
G4double fDensity_foil
G4int fFoil_NComponents
std::vector< G4double > fMaterialFractionMassFoil
G4double fTarget_thickness
G4double fFoil_thickness
G4Material * fTarget_Material
G4Material * fFoil_Material
G4double fZ_foil_position
G4Tubs * fSolidFoil
G4LogicalVolume * fLogicFoil
G4VPhysicalVolume * fPhysFoil
G4LogicalVolume * fLogicWorld
G4double fLayer_z_position_PART3
G4VPhysicalVolume * fPhysLayer_PART3
G4VPhysicalVolume * fPhysTube_PART3
G4double fTube_outerRadius_PART4
G4double fTube_length_PART4
G4double fLayer_z_position_PART4
G4VPhysicalVolume * fPhysTube_PART4
G4VPhysicalVolume * fPhysLayer_PART4
G4double fLayer1_z_position_PART4
G4VPhysicalVolume * fPhysLayer1_PART4
G4LogicalVolume * fLogicTarget
G4double fTarget_z_position
G4Tubs * fSolidTarget
G4VPhysicalVolume * fPhysTarget
G4double fLayer1_z_position_PART5
G4VPhysicalVolume * fPhysLayer1_PART5
G4double fLayer2_z_position_PART5
G4VPhysicalVolume * fPhysLayer2_PART5
G4double fLayer3_z_position_PART5
G4VPhysicalVolume * fPhysLayer3_PART5
G4Region * fRegionTarget
G4Region * fRegionFoil
G4double fTargetVolume
G4double fFoilVolume
std::ofstream fParametersSummary
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Detector construction class to define materials and geometry.
Definition at line 48 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 48 of file STCyclotronDetectorConstruction.hh
Constructor & Destructor Documentation
STCyclotronDetectorConstruction::STCyclotronDetectorConstruction ()
Definition at line 72 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 72 of file STCyclotronDetectorConstruction.cc
References fDetectorMessenger.
STCyclotronDetectorConstruction::~STCyclotronDetectorConstruction ()
Definition at line 98 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 98 of file STCyclotronDetectorConstruction.cc
References fDetectorMessenger.
Member Function Documentation
G4VPhysicalVolume * STCyclotronDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 103 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 103 of file STCyclotronDetectorConstruction.cc
References bar, cm3, deg, fDensity_foil, fDensity_target, fFoil_Material, fFoil_thickness, fFoilVolume, G4NistManager::FindOrBuildMaterial(), fLayer1_z_position_PART4, fLayer1_z_position_PART5, fLayer2_z_position_PART5, fLayer3_z_position_PART5, fLayer_z_position_PART3, fLayer_z_position_PART4, fLogicFoil, fLogicTarget, fLogicWorld, fPhysFoil, fPhysLayer1_PART4, fPhysLayer1_PART5, fPhysLayer2_PART5, fPhysLayer3_PART5, fPhysLayer_PART3, fPhysLayer_PART4, fPhysTarget, fPhysTube_PART3, fPhysTube_PART4, fRegionFoil, fRegionTarget, fSolidFoil, fSolidTarget, fTarget_diameter, fTarget_Material, fTarget_thickness, fTarget_z_position, fTargetVolume, fTube_length_PART4, fTube_outerRadius_PART4, fZ_foil_position, Acts::UnitConstants::g, G4Tubs::GetCubicVolume(), G4NistManager::Instance(), kelvin, kStateGas, m, mm, mole, numSide(), physWorld, and pt.
void STCyclotronDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 958 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 958 of file STCyclotronDetectorConstruction.cc
References fLogicFoil, fLogicTarget, and G4VUserDetectorConstruction::SetSensitiveDetector().
G4double STCyclotronDetectorConstruction::GetFoilPosition1 () inline
Definition at line 97 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 97 of file STCyclotronDetectorConstruction.hh
References fFoil_thickness, and fZ_foil_position.
G4double STCyclotronDetectorConstruction::GetFoilThickness () inline
Definition at line 100 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file STCyclotronDetectorConstruction.hh
References fFoil_thickness.
Referenced by STCyclotronPhysicsList::ConstructProcess(), and STCyclotronSensitiveFoil::ProcessHits().
G4double STCyclotronDetectorConstruction::GetFoilVolume () inline
Definition at line 99 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 99 of file STCyclotronDetectorConstruction.hh
References fFoilVolume.
Referenced by STCyclotronSensitiveFoil::ProcessHits().
G4double STCyclotronDetectorConstruction::GetTargetDiameter () inline
Definition at line 102 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 102 of file STCyclotronDetectorConstruction.hh
References fTarget_diameter.
Referenced by STCyclotronSensitiveTarget::ProcessHits().
G4double STCyclotronDetectorConstruction::GetTargetPosition1 () inline
Definition at line 94 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file STCyclotronDetectorConstruction.hh
References fLayer1_z_position_PART4, and fTarget_thickness.
Referenced by SetTargetThickness().
G4double STCyclotronDetectorConstruction::GetTargetPosition2 () inline
Definition at line 95 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 95 of file STCyclotronDetectorConstruction.hh
References fLayer1_z_position_PART4.
Referenced by SetTargetThickness().
G4double STCyclotronDetectorConstruction::GetTargetThickness () inline
Definition at line 101 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 101 of file STCyclotronDetectorConstruction.hh
References fTarget_thickness.
Referenced by STCyclotronPhysicsList::ConstructProcess(), and STCyclotronSensitiveTarget::ProcessHits().
G4double STCyclotronDetectorConstruction::GetTargetVolume () inline
Definition at line 98 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 98 of file STCyclotronDetectorConstruction.hh
References fTargetVolume.
Referenced by STCyclotronSensitiveTarget::ProcessHits().
G4double STCyclotronDetectorConstruction::GetVolumeTarget () inline
Definition at line 96 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 96 of file STCyclotronDetectorConstruction.hh
References fTarget_diameter, fTarget_thickness, and pi.
void STCyclotronDetectorConstruction::SetFoilElementAbundance (G4double abundance)
Definition at line 1259 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1259 of file STCyclotronDetectorConstruction.cc
References fElementAbundanceFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilElementName (G4String name)
Definition at line 1241 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1241 of file STCyclotronDetectorConstruction.cc
References fElementNameFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilElementNComponents (G4int n)
Definition at line 1253 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1253 of file STCyclotronDetectorConstruction.cc
References fElementNComponentsFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilElementSymbole (G4String symbole)
Definition at line 1247 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1247 of file STCyclotronDetectorConstruction.cc
References fElementSymboleFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilIsotopeA (G4double a)
Definition at line 1235 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1235 of file STCyclotronDetectorConstruction.cc
References fIsotopeAFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilIsotopeN (G4int n)
Definition at line 1229 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1229 of file STCyclotronDetectorConstruction.cc
References fIsotopeNFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilIsotopeName (G4String name)
Definition at line 1217 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1217 of file STCyclotronDetectorConstruction.cc
References fIsotopeNameFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilIsotopeZ (G4double z)
Definition at line 1223 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1223 of file STCyclotronDetectorConstruction.cc
References fIsotopeZFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilMaterial (G4String materialName)
Definition at line 1406 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1406 of file STCyclotronDetectorConstruction.cc
References fFoil_Material, G4NistManager::FindOrBuildMaterial(), fLogicFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), G4NistManager::Instance(), and G4LogicalVolume::SetMaterial().
void STCyclotronDetectorConstruction::SetFoilMaterialDensity (G4double materialDensity)
Definition at line 1265 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1265 of file STCyclotronDetectorConstruction.cc
References fDensity_foil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilMaterialFractionMass (G4double fractionMass)
Definition at line 1277 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1277 of file STCyclotronDetectorConstruction.cc
References fMaterialFractionMassFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetFoilMaterialNComponents (G4int n)
Definition at line 1271 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1271 of file STCyclotronDetectorConstruction.cc
References fFoil_NComponents, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), and n.
void STCyclotronDetectorConstruction::SetFoilNaturalElement (G4String name)
Definition at line 1283 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1283 of file STCyclotronDetectorConstruction.cc
References fNaturalElementNameFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
Referenced by STCyclotronDetectorMessenger::SetNewValue().
void STCyclotronDetectorConstruction::SetFoilNaturalMaterialFractionMass (G4double fractionMass)
Definition at line 1289 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1289 of file STCyclotronDetectorConstruction.cc
References fNaturalMaterialFractionMassFoil, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
Referenced by STCyclotronDetectorMessenger::SetNewValue().
void STCyclotronDetectorConstruction::SetFoilThickness (G4double foilThickness)
Definition at line 1454 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1454 of file STCyclotronDetectorConstruction.cc
References fFoil_thickness, fLayer1_z_position_PART4, fLayer1_z_position_PART5, fLayer2_z_position_PART5, fLayer3_z_position_PART5, fLayer_z_position_PART3, fLayer_z_position_PART4, fPhysFoil, fPhysLayer1_PART4, fPhysLayer1_PART5, fPhysLayer2_PART5, fPhysLayer3_PART5, fPhysLayer_PART3, fPhysLayer_PART4, fPhysTube_PART3, fPhysTube_PART4, fSolidFoil, fZ_foil_position, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), mm, G4VPhysicalVolume::SetTranslation(), and G4Tubs::SetZHalfLength().
void STCyclotronDetectorConstruction::SetTargetDiameter (G4double targetDiameter)
Definition at line 973 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 973 of file STCyclotronDetectorConstruction.cc
References fSolidTarget, fTarget_diameter, fTube_outerRadius_PART4, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), and G4Tubs::SetOuterRadius().
void STCyclotronDetectorConstruction::SetTargetElementAbundance (G4double abundance)
Definition at line 1034 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1034 of file STCyclotronDetectorConstruction.cc
References fElementAbundance, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetElementName (G4String name)
Definition at line 1016 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1016 of file STCyclotronDetectorConstruction.cc
References fElementName, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetElementNComponents (G4int n)
Definition at line 1028 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1028 of file STCyclotronDetectorConstruction.cc
References fElementNComponents, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetElementSymbole (G4String symbole)
Definition at line 1022 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1022 of file STCyclotronDetectorConstruction.cc
References fElementSymbole, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetIsotopeA (G4double a)
Definition at line 1010 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1010 of file STCyclotronDetectorConstruction.cc
References fIsotopeA, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetIsotopeN (G4int n)
Definition at line 1004 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1004 of file STCyclotronDetectorConstruction.cc
References fIsotopeN, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetIsotopeName (G4String name)
Definition at line 992 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 992 of file STCyclotronDetectorConstruction.cc
References fIsotopeName, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetIsotopeZ (G4double z)
Definition at line 998 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 998 of file STCyclotronDetectorConstruction.cc
References fIsotopeZ, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetMaterial (G4String materialName)
Definition at line 1193 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1193 of file STCyclotronDetectorConstruction.cc
References G4NistManager::FindOrBuildMaterial(), fLogicTarget, fTarget_Material, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), G4NistManager::Instance(), and G4LogicalVolume::SetMaterial().
void STCyclotronDetectorConstruction::SetTargetMaterialDensity (G4double materialDensity)
Definition at line 1040 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1040 of file STCyclotronDetectorConstruction.cc
References fDensity_target, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetMaterialFractionMass (G4double fractionMass)
Definition at line 1052 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1052 of file STCyclotronDetectorConstruction.cc
References fMaterialFractionMass, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
void STCyclotronDetectorConstruction::SetTargetMaterialNComponents (G4int n)
Definition at line 1046 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1046 of file STCyclotronDetectorConstruction.cc
References fTarget_NComponents, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), and n.
void STCyclotronDetectorConstruction::SetTargetNaturalElement (G4String name)
Definition at line 1058 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1058 of file STCyclotronDetectorConstruction.cc
References fNaturalElementName, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
Referenced by STCyclotronDetectorMessenger::SetNewValue().
void STCyclotronDetectorConstruction::SetTargetNaturalMaterialFractionMass (G4double fractionMass)
Definition at line 1064 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1064 of file STCyclotronDetectorConstruction.cc
References fNaturalMaterialFractionMass, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, and G4RunManager::GetRunManager().
Referenced by STCyclotronDetectorMessenger::SetNewValue().
void STCyclotronDetectorConstruction::SetTargetThickness (G4double targetThickness)
Definition at line 1430 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1430 of file STCyclotronDetectorConstruction.cc
References fPhysTarget, fSolidTarget, fTarget_thickness, fTarget_z_position, fTube_length_PART4, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4RunManager::GetRunManager(), GetTargetPosition1(), GetTargetPosition2(), mm, G4VPhysicalVolume::SetTranslation(), and G4Tubs::SetZHalfLength().
G4bool STCyclotronDetectorConstruction::UpdateFoilMaterial ()
Definition at line 1295 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1295 of file STCyclotronDetectorConstruction.cc
References A(), G4Material::AddElement(), G4Element::AddIsotope(), cm3, E, fDensity_foil, fElementAbundanceFoil, fElementNameFoil, fElementNComponentsFoil, fElementSymboleFoil, fFoil_Material, fFoil_NComponents, G4NistManager::FindOrBuildElement(), fIsotopeAFoil, fIsotopeNameFoil, fIsotopeNFoil, fIsotopeZFoil, fLogicFoil, fMaterialFractionMassFoil, fNaturalElementNameFoil, fNaturalMaterialFractionMassFoil, Acts::UnitConstants::g, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4Material::GetElement(), G4Element::GetIsotope(), G4Isotope::GetN(), G4Isotope::GetName(), G4Element::GetName(), G4Material::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4RunManager::GetRunManager(), G4Isotope::GetZ(), G4NistManager::Instance(), material(), and G4LogicalVolume::SetMaterial().
G4bool STCyclotronDetectorConstruction::UpdateMaterial ()
Definition at line 1072 of file STCyclotronDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 1072 of file STCyclotronDetectorConstruction.cc
References A(), G4Material::AddElement(), G4Element::AddIsotope(), cm3, E, fDensity_target, fElementAbundance, fElementName, fElementNComponents, fElementSymbole, G4NistManager::FindOrBuildElement(), fIsotopeA, fIsotopeN, fIsotopeName, fIsotopeZ, fLogicTarget, fMaterialFractionMass, fNaturalElementName, fNaturalMaterialFractionMass, fTarget_Material, fTarget_NComponents, Acts::UnitConstants::g, G4cout, G4endl, pyG4RunManager::GeometryHasBeenModified, G4Material::GetElement(), G4Element::GetIsotope(), G4Isotope::GetN(), G4Isotope::GetName(), G4Element::GetName(), G4Material::GetNumberOfElements(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4RunManager::GetRunManager(), G4Isotope::GetZ(), G4NistManager::Instance(), material(), mole, and G4LogicalVolume::SetMaterial().
Member Data Documentation
G4double STCyclotronDetectorConstruction::fDensity_foil private
Definition at line 134 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 134 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), SetFoilMaterialDensity(), and UpdateFoilMaterial().
G4double STCyclotronDetectorConstruction::fDensity_target private
Definition at line 120 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 120 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), SetTargetMaterialDensity(), and UpdateMaterial().
STCyclotronDetectorMessenger* STCyclotronDetectorConstruction::fDetectorMessenger private
Definition at line 106 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 106 of file STCyclotronDetectorConstruction.hh
Referenced by STCyclotronDetectorConstruction(), and ~STCyclotronDetectorConstruction().
std::vector<G4double> STCyclotronDetectorConstruction::fElementAbundance private
Definition at line 117 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 117 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetElementAbundance(), and UpdateMaterial().
std::vector<G4double> STCyclotronDetectorConstruction::fElementAbundanceFoil private
Definition at line 131 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 131 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilElementAbundance(), and UpdateFoilMaterial().
std::vector<G4String> STCyclotronDetectorConstruction::fElementName private
Definition at line 114 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 114 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetElementName(), and UpdateMaterial().
std::vector<G4String> STCyclotronDetectorConstruction::fElementNameFoil private
Definition at line 128 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 128 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilElementName(), and UpdateFoilMaterial().
std::vector<G4int> STCyclotronDetectorConstruction::fElementNComponents private
Definition at line 116 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 116 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetElementNComponents(), and UpdateMaterial().
std::vector<G4int> STCyclotronDetectorConstruction::fElementNComponentsFoil private
Definition at line 130 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 130 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilElementNComponents(), and UpdateFoilMaterial().
std::vector<G4String> STCyclotronDetectorConstruction::fElementSymbole private
Definition at line 115 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 115 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetElementSymbole(), and UpdateMaterial().
std::vector<G4String> STCyclotronDetectorConstruction::fElementSymboleFoil private
Definition at line 129 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 129 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilElementSymbole(), and UpdateFoilMaterial().
G4Material* STCyclotronDetectorConstruction::fFoil_Material private
Definition at line 146 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 146 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), SetFoilMaterial(), and UpdateFoilMaterial().
G4int STCyclotronDetectorConstruction::fFoil_NComponents private
Definition at line 135 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 135 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilMaterialNComponents(), and UpdateFoilMaterial().
G4double STCyclotronDetectorConstruction::fFoil_thickness private
Definition at line 139 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 139 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), GetFoilPosition1(), GetFoilThickness(), and SetFoilThickness().
G4double STCyclotronDetectorConstruction::fFoilVolume private
Definition at line 183 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 183 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and GetFoilVolume().
std::vector<G4double> STCyclotronDetectorConstruction::fIsotopeA private
Definition at line 113 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 113 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetIsotopeA(), and UpdateMaterial().
std::vector<G4double> STCyclotronDetectorConstruction::fIsotopeAFoil private
Definition at line 127 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 127 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilIsotopeA(), and UpdateFoilMaterial().
std::vector<G4int> STCyclotronDetectorConstruction::fIsotopeN private
Definition at line 112 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 112 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetIsotopeN(), and UpdateMaterial().
std::vector<G4String> STCyclotronDetectorConstruction::fIsotopeName private
Definition at line 110 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 110 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetIsotopeName(), and UpdateMaterial().
std::vector<G4String> STCyclotronDetectorConstruction::fIsotopeNameFoil private
Definition at line 124 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 124 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilIsotopeName(), and UpdateFoilMaterial().
std::vector<G4int> STCyclotronDetectorConstruction::fIsotopeNFoil private
Definition at line 126 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 126 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilIsotopeN(), and UpdateFoilMaterial().
std::vector<G4double> STCyclotronDetectorConstruction::fIsotopeZ private
Definition at line 111 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 111 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetIsotopeZ(), and UpdateMaterial().
std::vector<G4double> STCyclotronDetectorConstruction::fIsotopeZFoil private
Definition at line 125 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 125 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilIsotopeZ(), and UpdateFoilMaterial().
G4double STCyclotronDetectorConstruction::fLayer1_z_position_PART4 private
Definition at line 164 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 164 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), GetTargetPosition1(), GetTargetPosition2(), and SetFoilThickness().
G4double STCyclotronDetectorConstruction::fLayer1_z_position_PART5 private
Definition at line 172 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 172 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4double STCyclotronDetectorConstruction::fLayer2_z_position_PART5 private
Definition at line 174 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 174 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4double STCyclotronDetectorConstruction::fLayer3_z_position_PART5 private
Definition at line 176 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 176 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4double STCyclotronDetectorConstruction::fLayer_z_position_PART3 private
Definition at line 155 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 155 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4double STCyclotronDetectorConstruction::fLayer_z_position_PART4 private
Definition at line 161 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 161 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4LogicalVolume* STCyclotronDetectorConstruction::fLogicFoil private
Definition at line 150 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 150 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), ConstructSDandField(), SetFoilMaterial(), and UpdateFoilMaterial().
G4LogicalVolume* STCyclotronDetectorConstruction::fLogicTarget private
Definition at line 167 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 167 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), ConstructSDandField(), SetTargetMaterial(), and UpdateMaterial().
G4LogicalVolume* STCyclotronDetectorConstruction::fLogicWorld private
Definition at line 153 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 153 of file STCyclotronDetectorConstruction.hh
Referenced by Construct().
std::vector<G4double> STCyclotronDetectorConstruction::fMaterialFractionMass private
Definition at line 122 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 122 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetMaterialFractionMass(), and UpdateMaterial().
std::vector<G4double> STCyclotronDetectorConstruction::fMaterialFractionMassFoil private
Definition at line 136 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 136 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilMaterialFractionMass(), and UpdateFoilMaterial().
std::vector<G4String> STCyclotronDetectorConstruction::fNaturalElementName private
Definition at line 118 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 118 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetNaturalElement(), and UpdateMaterial().
std::vector<G4String> STCyclotronDetectorConstruction::fNaturalElementNameFoil private
Definition at line 132 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 132 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilNaturalElement(), and UpdateFoilMaterial().
std::vector<G4double> STCyclotronDetectorConstruction::fNaturalMaterialFractionMass private
Definition at line 119 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 119 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetNaturalMaterialFractionMass(), and UpdateMaterial().
std::vector<G4double> STCyclotronDetectorConstruction::fNaturalMaterialFractionMassFoil private
Definition at line 133 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 133 of file STCyclotronDetectorConstruction.hh
Referenced by SetFoilNaturalMaterialFractionMass(), and UpdateFoilMaterial().
std::ofstream STCyclotronDetectorConstruction::fParametersSummary private
Definition at line 185 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 185 of file STCyclotronDetectorConstruction.hh
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysFoil private
Definition at line 151 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 151 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysLayer1_PART4 private
Definition at line 165 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 165 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysLayer1_PART5 private
Definition at line 173 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 173 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysLayer2_PART5 private
Definition at line 175 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 175 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysLayer3_PART5 private
Definition at line 177 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 177 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysLayer_PART3 private
Definition at line 156 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 156 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysLayer_PART4 private
Definition at line 163 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 163 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysTarget private
Definition at line 170 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 170 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetTargetThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysTube_PART3 private
Definition at line 157 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 157 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4VPhysicalVolume* STCyclotronDetectorConstruction::fPhysTube_PART4 private
Definition at line 162 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 162 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4Region* STCyclotronDetectorConstruction::fRegionFoil private
Definition at line 180 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 180 of file STCyclotronDetectorConstruction.hh
Referenced by Construct().
G4Region* STCyclotronDetectorConstruction::fRegionTarget private
Definition at line 179 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 179 of file STCyclotronDetectorConstruction.hh
Referenced by Construct().
G4Tubs* STCyclotronDetectorConstruction::fSolidFoil private
Definition at line 149 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 149 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetFoilThickness().
G4Tubs* STCyclotronDetectorConstruction::fSolidTarget private
Definition at line 169 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 169 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), SetTargetDiameter(), and SetTargetThickness().
G4double STCyclotronDetectorConstruction::fTarget_diameter private
Definition at line 109 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 109 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), GetTargetDiameter(), GetVolumeTarget(), and SetTargetDiameter().
G4Material* STCyclotronDetectorConstruction::fTarget_Material private
Definition at line 145 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 145 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), SetTargetMaterial(), and UpdateMaterial().
G4int STCyclotronDetectorConstruction::fTarget_NComponents private
Definition at line 121 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 121 of file STCyclotronDetectorConstruction.hh
Referenced by SetTargetMaterialNComponents(), and UpdateMaterial().
G4double STCyclotronDetectorConstruction::fTarget_thickness private
Definition at line 138 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 138 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), GetTargetPosition1(), GetTargetThickness(), GetVolumeTarget(), and SetTargetThickness().
G4double STCyclotronDetectorConstruction::fTarget_z_position private
Definition at line 168 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 168 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetTargetThickness().
G4double STCyclotronDetectorConstruction::fTargetVolume private
Definition at line 182 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 182 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and GetTargetVolume().
G4double STCyclotronDetectorConstruction::fTube_length_PART4 private
Definition at line 160 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 160 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetTargetThickness().
G4double STCyclotronDetectorConstruction::fTube_outerRadius_PART4 private
Definition at line 159 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 159 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), and SetTargetDiameter().
G4double STCyclotronDetectorConstruction::fZ_foil_position private
Definition at line 148 of file STCyclotronDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 148 of file STCyclotronDetectorConstruction.hh
Referenced by Construct(), GetFoilPosition1(), and SetFoilThickness().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/include/STCyclotronDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/src/STCyclotronDetectorConstruction.cc