ECCE @ EIC Software: G4ParticleHPManager Class Reference
G4ParticleHPManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPManager.hh>
Public Member Functions
G4ParticleHPReactionWhiteBoard * GetReactionWhiteBoard ()
void OpenReactionWhiteBoard ()
void CloseReactionWhiteBoard ()
void GetDataStream (G4String, std::istringstream &iss)
void GetDataStream2 (G4String, std::istringstream &iss)
void SetVerboseLevel (G4int i)
G4int GetVerboseLevel ()
void DumpDataSource ()
G4bool GetUseOnlyPhotoEvaporation ()
void SetUseOnlyPhotoEvaporation (G4bool val)
G4bool GetSkipMissingIsotopes ()
G4bool GetNeglectDoppler ()
G4bool GetDoNotAdjustFinalState ()
G4bool GetProduceFissionFragments ()
G4bool GetUseNRESP71Model ()
void SetSkipMissingIsotopes (G4bool val)
void SetNeglectDoppler (G4bool val)
void SetDoNotAdjustFinalState (G4bool val)
void SetProduceFissionFragments (G4bool val)
void SetUseNRESP71Model (G4bool val)
void RegisterElasticCrossSections (G4PhysicsTable *val)
G4PhysicsTable * GetElasticCrossSections ()
void RegisterCaptureCrossSections (G4PhysicsTable *val)
G4PhysicsTable * GetCaptureCrossSections ()
void RegisterInelasticCrossSections (const G4ParticleDefinition *, G4PhysicsTable *)
G4PhysicsTable * GetInelasticCrossSections (const G4ParticleDefinition *)
void RegisterFissionCrossSections (G4PhysicsTable *val)
G4PhysicsTable * GetFissionCrossSections ()
std::vector
< G4ParticleHPChannel * > * GetElasticFinalStates ()
void RegisterElasticFinalStates (std::vector< G4ParticleHPChannel * > *val)
std::vector
< G4ParticleHPChannelList * > * GetInelasticFinalStates (const G4ParticleDefinition *)
void RegisterInelasticFinalStates (const G4ParticleDefinition *, std::vector< G4ParticleHPChannelList * > *)
std::vector
< G4ParticleHPChannel * > * GetCaptureFinalStates ()
void RegisterCaptureFinalStates (std::vector< G4ParticleHPChannel * > *val)
std::vector
< G4ParticleHPChannel * > * GetFissionFinalStates ()
void RegisterFissionFinalStates (std::vector< G4ParticleHPChannel * > *val)
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * GetThermalScatteringCoherentCrossSections ()
void RegisterThermalScatteringCoherentCrossSections (std::map< G4int, std::map< G4double, G4ParticleHPVector * > * > *val)
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * GetThermalScatteringIncoherentCrossSections ()
void RegisterThermalScatteringIncoherentCrossSections (std::map< G4int, std::map< G4double, G4ParticleHPVector * > * > *val)
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * GetThermalScatteringInelasticCrossSections ()
void RegisterThermalScatteringInelasticCrossSections (std::map< G4int, std::map< G4double, G4ParticleHPVector * > * > *val)
std::map< G4int, std::map
< G4double, std::vector
< std::pair< G4double,
G4double > * > * > * > * GetThermalScatteringCoherentFinalStates ()
void RegisterThermalScatteringCoherentFinalStates (std::map< G4int, std::map< G4double, std::vector< std::pair< G4double, G4double > * > * > * > *val)
std::map< G4int, std::map
< G4double, std::vector
< E_isoAng * > * > * > * GetThermalScatteringIncoherentFinalStates ()
void RegisterThermalScatteringIncoherentFinalStates (std::map< G4int, std::map< G4double, std::vector< E_isoAng * > * > * > *val)
std::map< G4int, std::map
< G4double, std::vector
< E_P_E_isoAng * > * > * > * GetThermalScatteringInelasticFinalStates ()
void RegisterThermalScatteringInelasticFinalStates (std::map< G4int, std::map< G4double, std::vector< E_P_E_isoAng * > * > * > *val)
Static Public Member Functions
static G4ParticleHPManager * GetInstance ()
Private Member Functions
G4ParticleHPManager ()
G4ParticleHPManager (const G4ParticleHPManager &)
~G4ParticleHPManager ()
void register_data_file (G4String, G4String)
Private Attributes
std::map< G4String, G4String > mDataEvaluation
G4int verboseLevel
G4ParticleHPMessenger * messenger
G4bool USE_ONLY_PHOTONEVAPORATION
G4bool SKIP_MISSING_ISOTOPES
G4bool NEGLECT_DOPPLER
G4bool DO_NOT_ADJUST_FINAL_STATE
G4bool PRODUCE_FISSION_FRAGMENTS
G4bool USE_NRESP71_MODEL
G4PhysicsTable * theElasticCrossSections
G4PhysicsTable * theCaptureCrossSections
std::map< const
G4ParticleDefinition
*, G4PhysicsTable * > theInelasticCrossSections
G4PhysicsTable * theFissionCrossSections
std::vector
< G4ParticleHPChannel * > * theElasticFSs
std::map< const
G4ParticleDefinition
*, std::vector
< G4ParticleHPChannelList * > * > theInelasticFSs
std::vector
< G4ParticleHPChannel * > * theCaptureFSs
std::vector
< G4ParticleHPChannel * > * theFissionFSs
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * theTSCoherentCrossSections
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * theTSIncoherentCrossSections
std::map< G4int, std::map
< G4double, G4ParticleHPVector * > * > * theTSInelasticCrossSections
std::map< G4int, std::map
< G4double, std::vector
< std::pair< G4double,
G4double > * > * > * > * theTSCoherentFinalStates
std::map< G4int, std::map
< G4double, std::vector
< E_isoAng * > * > * > * theTSIncoherentFinalStates
std::map< G4int, std::map
< G4double, std::vector
< E_P_E_isoAng * > * > * > * theTSInelasticFinalStates
Static Private Attributes
static G4ParticleHPManager * instance = 0
Detailed Description
Definition at line 53 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 53 of file G4ParticleHPManager.hh
Constructor & Destructor Documentation
G4ParticleHPManager::G4ParticleHPManager () private
Definition at line 42 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 42 of file G4ParticleHPManager.cc
References DO_NOT_ADJUST_FINAL_STATE, messenger, NEGLECT_DOPPLER, PRODUCE_FISSION_FRAGMENTS, SKIP_MISSING_ISOTOPES, USE_NRESP71_MODEL, and USE_ONLY_PHOTONEVAPORATION.
G4ParticleHPManager::G4ParticleHPManager (const G4ParticleHPManager &) inline private
Definition at line 60 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPManager.hh
G4ParticleHPManager::~G4ParticleHPManager () private
Definition at line 72 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ParticleHPManager.cc
References messenger.
Member Function Documentation
void G4ParticleHPManager::CloseReactionWhiteBoard ()
Definition at line 97 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPManager.cc
References G4ParticleHPThreadLocalManager::CloseReactionWhiteBoard(), and G4ParticleHPThreadLocalManager::GetInstance().
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), and G4FissLib::ApplyYourself().
void G4ParticleHPManager::DumpDataSource ()
Definition at line 221 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 221 of file G4ParticleHPManager.cc
References G4cout, G4endl, it, and mDataEvaluation.
G4PhysicsTable* G4ParticleHPManager::GetCaptureCrossSections () inline
Definition at line 94 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParticleHPManager.hh
References theCaptureCrossSections.
Referenced by G4ParticleHPCaptureData::BuildPhysicsTable().
std::vector<G4ParticleHPChannel*>* G4ParticleHPManager::GetCaptureFinalStates () inline
Definition at line 104 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParticleHPManager.hh
References theCaptureFSs.
Referenced by G4ParticleHPCapture::BuildPhysicsTable().
void G4ParticleHPManager::GetDataStream (G4String filename, std::istringstream & iss)
Definition at line 102 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 102 of file G4ParticleHPManager.cc
References in, register_data_file(), uncompress(), and Z_OK.
Referenced by G4ParticleHPFFFissionFS::Init(), G4ParticleHPCaptureFS::Init(), G4ParticleHPFSFissionFS::Init(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPElasticFS::Init(), G4ParticleHPIsoData::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), G4FissionLibrary::Init(), G4ENDFTapeRead::Initialize(), G4WendtFissionFragmentGenerator::InitializeANucleus(), G4ParticleHPThermalScattering::readACoherentFSDATA(), G4ParticleHPThermalScattering::readAnIncoherentFSDATA(), G4ParticleHPThermalScattering::readAnInelasticFSDATA(), and G4ParticleHPThermalScatteringData::readData().
void G4ParticleHPManager::GetDataStream2 (G4String filename, std::istringstream & iss)
Definition at line 179 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 179 of file G4ParticleHPManager.cc
References in.
Referenced by G4ParticleHPNames::GetName().
G4bool G4ParticleHPManager::GetDoNotAdjustFinalState () inline
Definition at line 81 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ParticleHPManager.hh
References DO_NOT_ADJUST_FINAL_STATE.
Referenced by G4ParticleHPFinalState::DoNotAdjustFinalState().
G4PhysicsTable* G4ParticleHPManager::GetElasticCrossSections () inline
Definition at line 92 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPManager.hh
References theElasticCrossSections.
Referenced by G4ParticleHPElasticData::BuildPhysicsTable().
std::vector<G4ParticleHPChannel*>* G4ParticleHPManager::GetElasticFinalStates () inline
Definition at line 100 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ParticleHPManager.hh
References theElasticFSs.
Referenced by G4ParticleHPElastic::BuildPhysicsTable().
G4PhysicsTable* G4ParticleHPManager::GetFissionCrossSections () inline
Definition at line 98 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 98 of file G4ParticleHPManager.hh
References theFissionCrossSections.
Referenced by G4ParticleHPFissionData::BuildPhysicsTable().
std::vector<G4ParticleHPChannel*>* G4ParticleHPManager::GetFissionFinalStates () inline
Definition at line 106 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParticleHPManager.hh
References theFissionFSs.
Referenced by G4ParticleHPFission::BuildPhysicsTable().
G4PhysicsTable * G4ParticleHPManager::GetInelasticCrossSections (const G4ParticleDefinition * particle)
Definition at line 233 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 233 of file G4ParticleHPManager.cc
References theInelasticCrossSections.
Referenced by G4ParticleHPInelasticData::BuildPhysicsTable().
std::vector< G4ParticleHPChannelList * > * G4ParticleHPManager::GetInelasticFinalStates (const G4ParticleDefinition * particle)
Definition at line 246 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 246 of file G4ParticleHPManager.cc
References theInelasticFSs.
Referenced by G4ParticleHPInelastic::BuildPhysicsTable().
G4ParticleHPManager * G4ParticleHPManager::GetInstance (void) static
Definition at line 77 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPManager.cc
References instance.
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4ParticleHPFissionFS::ApplyYourself(), G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), G4ParticleHPChannel::ApplyYourself(), G4ParticleHPCapture::BuildPhysicsTable(), G4ParticleHPFission::BuildPhysicsTable(), G4ParticleHPElastic::BuildPhysicsTable(), G4ParticleHPFissionData::BuildPhysicsTable(), G4ParticleHPCaptureData::BuildPhysicsTable(), G4ParticleHPElasticData::BuildPhysicsTable(), G4ParticleHPInelasticData::BuildPhysicsTable(), G4ParticleHPThermalScatteringData::BuildPhysicsTable(), G4ParticleHPInelastic::BuildPhysicsTable(), G4ParticleHPThermalScattering::buildPhysicsTable(), G4ParticleHPInelasticCompFS::CompositeApply(), G4ParticleHPFinalState::DoNotAdjustFinalState(), G4ParticleHPNames::GetName(), G4ParticleHPCapture::GetVerboseLevel(), G4ParticleHPFission::GetVerboseLevel(), G4ParticleHPElastic::GetVerboseLevel(), G4ParticleHPFissionData::GetVerboseLevel(), G4ParticleHPCaptureData::GetVerboseLevel(), G4ParticleHPElasticData::GetVerboseLevel(), G4ParticleHPInelasticData::GetVerboseLevel(), G4ParticleHPInelastic::GetVerboseLevel(), G4ParticleHPFFFissionFS::Init(), G4ParticleHPFissionFS::Init(), G4ParticleHPCaptureFS::Init(), G4ParticleHPFSFissionFS::Init(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPElasticFS::Init(), G4ParticleHPIsoData::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), G4FissionLibrary::Init(), G4ENDFTapeRead::Initialize(), G4WendtFissionFragmentGenerator::InitializeANucleus(), G4ParticleHPThermalScattering::readACoherentFSDATA(), G4ParticleHPThermalScattering::readAnIncoherentFSDATA(), G4ParticleHPThermalScattering::readAnInelasticFSDATA(), G4ParticleHPThermalScatteringData::readData(), G4ParticleHPCapture::SetVerboseLevel(), G4ParticleHPFission::SetVerboseLevel(), G4ParticleHPElastic::SetVerboseLevel(), G4ParticleHPFissionData::SetVerboseLevel(), G4ParticleHPElasticData::SetVerboseLevel(), G4ParticleHPCaptureData::SetVerboseLevel(), G4ParticleHPInelasticData::SetVerboseLevel(), G4ParticleHPInelastic::SetVerboseLevel(), and Shielding::Shielding().
G4bool G4ParticleHPManager::GetNeglectDoppler () inline
Definition at line 80 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParticleHPManager.hh
References NEGLECT_DOPPLER.
G4bool G4ParticleHPManager::GetProduceFissionFragments () inline
Definition at line 82 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 82 of file G4ParticleHPManager.hh
References PRODUCE_FISSION_FRAGMENTS.
Referenced by G4ParticleHPFissionFS::ApplyYourself().
G4ParticleHPReactionWhiteBoard * G4ParticleHPManager::GetReactionWhiteBoard ()
Definition at line 92 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 92 of file G4ParticleHPManager.cc
References G4ParticleHPThreadLocalManager::GetInstance(), and G4ParticleHPThreadLocalManager::GetReactionWhiteBoard().
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4FissLib::ApplyYourself(), and G4ParticleHPChannel::ApplyYourself().
G4bool G4ParticleHPManager::GetSkipMissingIsotopes () inline
Definition at line 79 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPManager.hh
References SKIP_MISSING_ISOTOPES.
Referenced by G4ParticleHPNames::GetName().
std::map<G4int,std::map<G4double,G4ParticleHPVector*>*>* G4ParticleHPManager::GetThermalScatteringCoherentCrossSections () inline
Definition at line 109 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 109 of file G4ParticleHPManager.hh
References theTSCoherentCrossSections.
Referenced by G4ParticleHPThermalScatteringData::BuildPhysicsTable().
std::map< G4int , std::map < G4double , std::vector < std::pair< G4double , G4double >* >* >* >* G4ParticleHPManager::GetThermalScatteringCoherentFinalStates () inline
Definition at line 116 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ParticleHPManager.hh
References theTSCoherentFinalStates.
Referenced by G4ParticleHPThermalScattering::buildPhysicsTable().
std::map<G4int,std::map<G4double,G4ParticleHPVector*>*>* G4ParticleHPManager::GetThermalScatteringIncoherentCrossSections () inline
Definition at line 111 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParticleHPManager.hh
References theTSIncoherentCrossSections.
Referenced by G4ParticleHPThermalScatteringData::BuildPhysicsTable().
std::map< G4int , std::map < G4double , std::vector < E_isoAng* >* >* >* G4ParticleHPManager::GetThermalScatteringIncoherentFinalStates () inline
Definition at line 118 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ParticleHPManager.hh
References theTSIncoherentFinalStates.
Referenced by G4ParticleHPThermalScattering::buildPhysicsTable().
std::map<G4int,std::map<G4double,G4ParticleHPVector*>*>* G4ParticleHPManager::GetThermalScatteringInelasticCrossSections () inline
Definition at line 113 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ParticleHPManager.hh
References theTSInelasticCrossSections.
Referenced by G4ParticleHPThermalScatteringData::BuildPhysicsTable().
std::map< G4int , std::map < G4double , std::vector < E_P_E_isoAng* >* >* >* G4ParticleHPManager::GetThermalScatteringInelasticFinalStates () inline
Definition at line 120 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 120 of file G4ParticleHPManager.hh
References theTSInelasticFinalStates.
Referenced by G4ParticleHPThermalScattering::buildPhysicsTable().
G4bool G4ParticleHPManager::GetUseNRESP71Model () inline
Definition at line 83 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 83 of file G4ParticleHPManager.hh
References USE_NRESP71_MODEL.
G4bool G4ParticleHPManager::GetUseOnlyPhotoEvaporation () inline
Definition at line 77 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPManager.hh
References USE_ONLY_PHOTONEVAPORATION.
G4int G4ParticleHPManager::GetVerboseLevel () inline
Definition at line 73 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleHPManager.hh
References verboseLevel.
Referenced by G4ParticleHPInelastic::BuildPhysicsTable(), G4ParticleHPNames::GetName(), G4ParticleHPCapture::GetVerboseLevel(), G4ParticleHPFission::GetVerboseLevel(), G4ParticleHPElastic::GetVerboseLevel(), G4ParticleHPFissionData::GetVerboseLevel(), G4ParticleHPCaptureData::GetVerboseLevel(), G4ParticleHPElasticData::GetVerboseLevel(), G4ParticleHPInelasticData::GetVerboseLevel(), and G4ParticleHPInelastic::GetVerboseLevel().
void G4ParticleHPManager::OpenReactionWhiteBoard ()
Definition at line 87 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPManager.cc
References G4ParticleHPThreadLocalManager::GetInstance(), and G4ParticleHPThreadLocalManager::OpenReactionWhiteBoard().
Referenced by G4ParticleHPElastic::ApplyYourself(), G4ParticleHPCapture::ApplyYourself(), G4ParticleHPFission::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), and G4FissLib::ApplyYourself().
void G4ParticleHPManager::register_data_file (G4String filename, G4String source) private
Definition at line 216 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 216 of file G4ParticleHPManager.cc
References mDataEvaluation.
Referenced by GetDataStream().
void G4ParticleHPManager::RegisterCaptureCrossSections (G4PhysicsTable * val) inline
Definition at line 93 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPManager.hh
References theCaptureCrossSections.
Referenced by G4ParticleHPCaptureData::BuildPhysicsTable().
void G4ParticleHPManager::RegisterCaptureFinalStates (std::vector< G4ParticleHPChannel * > * val) inline
Definition at line 105 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPManager.hh
References theCaptureFSs.
Referenced by G4ParticleHPCapture::BuildPhysicsTable().
void G4ParticleHPManager::RegisterElasticCrossSections (G4PhysicsTable * val) inline
Definition at line 91 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ParticleHPManager.hh
References theElasticCrossSections.
Referenced by G4ParticleHPElasticData::BuildPhysicsTable().
void G4ParticleHPManager::RegisterElasticFinalStates (std::vector< G4ParticleHPChannel * > * val) inline
Definition at line 101 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPManager.hh
References theElasticFSs.
Referenced by G4ParticleHPElastic::BuildPhysicsTable().
void G4ParticleHPManager::RegisterFissionCrossSections (G4PhysicsTable * val) inline
Definition at line 97 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParticleHPManager.hh
References theFissionCrossSections.
Referenced by G4ParticleHPFissionData::BuildPhysicsTable().
void G4ParticleHPManager::RegisterFissionFinalStates (std::vector< G4ParticleHPChannel * > * val) inline
Definition at line 107 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPManager.hh
References theFissionFSs.
Referenced by G4ParticleHPFission::BuildPhysicsTable().
void G4ParticleHPManager::RegisterInelasticCrossSections (const G4ParticleDefinition * particle, G4PhysicsTable * val)
Definition at line 241 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 241 of file G4ParticleHPManager.cc
References theInelasticCrossSections.
Referenced by G4ParticleHPInelasticData::BuildPhysicsTable().
void G4ParticleHPManager::RegisterInelasticFinalStates (const G4ParticleDefinition * particle, std::vector< G4ParticleHPChannelList * > * val)
Definition at line 254 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 254 of file G4ParticleHPManager.cc
References theInelasticFSs.
Referenced by G4ParticleHPInelastic::BuildPhysicsTable().
void G4ParticleHPManager::RegisterThermalScatteringCoherentCrossSections (std::map< G4int, std::map< G4double, G4ParticleHPVector * > * > * val) inline
Definition at line 110 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPManager.hh
References theTSCoherentCrossSections.
Referenced by G4ParticleHPThermalScatteringData::BuildPhysicsTable().
void G4ParticleHPManager::RegisterThermalScatteringCoherentFinalStates (std::map< G4int, std::map< G4double, std::vector< std::pair< G4double, G4double > * > * > * > * val) inline
Definition at line 117 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 117 of file G4ParticleHPManager.hh
References theTSCoherentFinalStates.
Referenced by G4ParticleHPThermalScattering::buildPhysicsTable().
void G4ParticleHPManager::RegisterThermalScatteringIncoherentCrossSections (std::map< G4int, std::map< G4double, G4ParticleHPVector * > * > * val) inline
Definition at line 112 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPManager.hh
References theTSIncoherentCrossSections.
Referenced by G4ParticleHPThermalScatteringData::BuildPhysicsTable().
void G4ParticleHPManager::RegisterThermalScatteringIncoherentFinalStates (std::map< G4int, std::map< G4double, std::vector< E_isoAng * > * > * > * val) inline
Definition at line 119 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ParticleHPManager.hh
References theTSIncoherentFinalStates.
Referenced by G4ParticleHPThermalScattering::buildPhysicsTable().
void G4ParticleHPManager::RegisterThermalScatteringInelasticCrossSections (std::map< G4int, std::map< G4double, G4ParticleHPVector * > * > * val) inline
Definition at line 114 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleHPManager.hh
References theTSInelasticCrossSections.
Referenced by G4ParticleHPThermalScatteringData::BuildPhysicsTable().
void G4ParticleHPManager::RegisterThermalScatteringInelasticFinalStates (std::map< G4int, std::map< G4double, std::vector< E_P_E_isoAng * > * > * > * val) inline
Definition at line 121 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 121 of file G4ParticleHPManager.hh
References theTSInelasticFinalStates.
Referenced by G4ParticleHPThermalScattering::buildPhysicsTable().
void G4ParticleHPManager::SetDoNotAdjustFinalState (G4bool val) inline
Definition at line 87 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ParticleHPManager.hh
References DO_NOT_ADJUST_FINAL_STATE.
Referenced by G4ParticleHPMessenger::SetNewValue().
void G4ParticleHPManager::SetNeglectDoppler (G4bool val) inline
Definition at line 86 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ParticleHPManager.hh
References NEGLECT_DOPPLER.
Referenced by G4ParticleHPMessenger::SetNewValue().
void G4ParticleHPManager::SetProduceFissionFragments (G4bool val) inline
Definition at line 88 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ParticleHPManager.hh
References PRODUCE_FISSION_FRAGMENTS.
Referenced by G4ParticleHPMessenger::SetNewValue(), and Shielding::Shielding().
void G4ParticleHPManager::SetSkipMissingIsotopes (G4bool val) inline
Definition at line 85 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPManager.hh
References SKIP_MISSING_ISOTOPES.
Referenced by G4ParticleHPMessenger::SetNewValue().
void G4ParticleHPManager::SetUseNRESP71Model (G4bool val) inline
Definition at line 89 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ParticleHPManager.hh
References USE_NRESP71_MODEL.
Referenced by G4ParticleHPMessenger::SetNewValue().
void G4ParticleHPManager::SetUseOnlyPhotoEvaporation (G4bool val) inline
Definition at line 78 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ParticleHPManager.hh
References USE_ONLY_PHOTONEVAPORATION.
Referenced by G4ParticleHPMessenger::SetNewValue().
void G4ParticleHPManager::SetVerboseLevel (G4int i)
Definition at line 209 of file G4ParticleHPManager.cc.
View newest version in sPHENIX GitHub at line 209 of file G4ParticleHPManager.cc
References G4cout, G4endl, and verboseLevel.
Referenced by G4ParticleHPMessenger::SetNewValue(), G4ParticleHPCapture::SetVerboseLevel(), G4ParticleHPFission::SetVerboseLevel(), G4ParticleHPElastic::SetVerboseLevel(), G4ParticleHPFissionData::SetVerboseLevel(), G4ParticleHPElasticData::SetVerboseLevel(), G4ParticleHPCaptureData::SetVerboseLevel(), G4ParticleHPInelasticData::SetVerboseLevel(), and G4ParticleHPInelastic::SetVerboseLevel().
Member Data Documentation
G4bool G4ParticleHPManager::DO_NOT_ADJUST_FINAL_STATE private
Definition at line 135 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ParticleHPManager.hh
Referenced by G4ParticleHPManager(), GetDoNotAdjustFinalState(), and SetDoNotAdjustFinalState().
G4ParticleHPManager * G4ParticleHPManager::instance = 0 static private
Definition at line 62 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ParticleHPManager.hh
Referenced by GetInstance().
std::map<G4String,G4String> G4ParticleHPManager::mDataEvaluation private
Definition at line 126 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 126 of file G4ParticleHPManager.hh
Referenced by DumpDataSource(), and register_data_file().
G4ParticleHPMessenger* G4ParticleHPManager::messenger private
Definition at line 131 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 131 of file G4ParticleHPManager.hh
Referenced by G4ParticleHPManager(), and ~G4ParticleHPManager().
G4bool G4ParticleHPManager::NEGLECT_DOPPLER private
Definition at line 134 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ParticleHPManager.hh
Referenced by G4ParticleHPManager(), GetNeglectDoppler(), and SetNeglectDoppler().
G4bool G4ParticleHPManager::PRODUCE_FISSION_FRAGMENTS private
Definition at line 136 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 136 of file G4ParticleHPManager.hh
Referenced by G4ParticleHPManager(), GetProduceFissionFragments(), and SetProduceFissionFragments().
G4bool G4ParticleHPManager::SKIP_MISSING_ISOTOPES private
Definition at line 133 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 133 of file G4ParticleHPManager.hh
Referenced by G4ParticleHPManager(), GetSkipMissingIsotopes(), and SetSkipMissingIsotopes().
G4PhysicsTable* G4ParticleHPManager::theCaptureCrossSections private
Definition at line 140 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 140 of file G4ParticleHPManager.hh
Referenced by GetCaptureCrossSections(), and RegisterCaptureCrossSections().
std::vector<G4ParticleHPChannel*>* G4ParticleHPManager::theCaptureFSs private
Definition at line 146 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 146 of file G4ParticleHPManager.hh
Referenced by GetCaptureFinalStates(), and RegisterCaptureFinalStates().
G4PhysicsTable* G4ParticleHPManager::theElasticCrossSections private
Definition at line 139 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 139 of file G4ParticleHPManager.hh
Referenced by GetElasticCrossSections(), and RegisterElasticCrossSections().
std::vector<G4ParticleHPChannel*>* G4ParticleHPManager::theElasticFSs private
Definition at line 144 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 144 of file G4ParticleHPManager.hh
Referenced by GetElasticFinalStates(), and RegisterElasticFinalStates().
G4PhysicsTable* G4ParticleHPManager::theFissionCrossSections private
Definition at line 142 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 142 of file G4ParticleHPManager.hh
Referenced by GetFissionCrossSections(), and RegisterFissionCrossSections().
std::vector<G4ParticleHPChannel*>* G4ParticleHPManager::theFissionFSs private
Definition at line 147 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ParticleHPManager.hh
Referenced by GetFissionFinalStates(), and RegisterFissionFinalStates().
std::map< const G4ParticleDefinition* , G4PhysicsTable* > G4ParticleHPManager::theInelasticCrossSections private
Definition at line 141 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 141 of file G4ParticleHPManager.hh
Referenced by GetInelasticCrossSections(), and RegisterInelasticCrossSections().
std::map< const G4ParticleDefinition* , std::vector<G4ParticleHPChannelList*>* > G4ParticleHPManager::theInelasticFSs private
Definition at line 145 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 145 of file G4ParticleHPManager.hh
Referenced by GetInelasticFinalStates(), and RegisterInelasticFinalStates().
std::map< G4int , std::map< G4double , G4ParticleHPVector* >* >* G4ParticleHPManager::theTSCoherentCrossSections private
Definition at line 149 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ParticleHPManager.hh
Referenced by GetThermalScatteringCoherentCrossSections(), and RegisterThermalScatteringCoherentCrossSections().
std::map< G4int , std::map< G4double , std::vector< std::pair< G4double , G4double >* >* >* >* G4ParticleHPManager::theTSCoherentFinalStates private
Definition at line 153 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ParticleHPManager.hh
Referenced by GetThermalScatteringCoherentFinalStates(), and RegisterThermalScatteringCoherentFinalStates().
std::map< G4int , std::map< G4double , G4ParticleHPVector* >* >* G4ParticleHPManager::theTSIncoherentCrossSections private
Definition at line 150 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 150 of file G4ParticleHPManager.hh
Referenced by GetThermalScatteringIncoherentCrossSections(), and RegisterThermalScatteringIncoherentCrossSections().
std::map< G4int , std::map< G4double , std::vector< E_isoAng* >* >* >* G4ParticleHPManager::theTSIncoherentFinalStates private
Definition at line 154 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParticleHPManager.hh
Referenced by GetThermalScatteringIncoherentFinalStates(), and RegisterThermalScatteringIncoherentFinalStates().
std::map< G4int , std::map< G4double , G4ParticleHPVector* >* >* G4ParticleHPManager::theTSInelasticCrossSections private
Definition at line 151 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ParticleHPManager.hh
Referenced by GetThermalScatteringInelasticCrossSections(), and RegisterThermalScatteringInelasticCrossSections().
std::map< G4int , std::map< G4double , std::vector< E_P_E_isoAng* >* >* >* G4ParticleHPManager::theTSInelasticFinalStates private
Definition at line 155 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ParticleHPManager.hh
Referenced by GetThermalScatteringInelasticFinalStates(), and RegisterThermalScatteringInelasticFinalStates().
G4bool G4ParticleHPManager::USE_NRESP71_MODEL private
Definition at line 137 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 137 of file G4ParticleHPManager.hh
Referenced by G4ParticleHPManager(), GetUseNRESP71Model(), and SetUseNRESP71Model().
G4bool G4ParticleHPManager::USE_ONLY_PHOTONEVAPORATION private
Definition at line 132 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ParticleHPManager.hh
Referenced by G4ParticleHPManager(), GetUseOnlyPhotoEvaporation(), and SetUseOnlyPhotoEvaporation().
G4int G4ParticleHPManager::verboseLevel private
Definition at line 129 of file G4ParticleHPManager.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ParticleHPManager.hh
Referenced by GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPManager.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPManager.cc