ECCE @ EIC Software: CexmcReimplementedGenbod Class Reference
CexmcReimplementedGenbod Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcReimplementedGenbod.hh>
Public Member Functions
CexmcReimplementedGenbod ()
G4double Generate (void)
Public Member Functions inherited from CexmcPhaseSpaceGenerator
CexmcPhaseSpaceGenerator ()
virtual ~CexmcPhaseSpaceGenerator ()
virtual G4bool CheckKinematics (void)
void SetParticles (const CexmcPhaseSpaceInVector &inVec_, const CexmcPhaseSpaceOutVector &outVec_)
void SetFermiEnergyDependence (G4bool on=true)
Private Member Functions
void ParticleChangeHook (void)
void FermiEnergyDepStatusChangeHook (void)
void SetMaxWeight (void)
Private Attributes
G4double maxWeight
G4int nmbOfOutputParticles
Static Private Attributes
static const G4int maxParticles = 18
Additional Inherited Members
Protected Attributes inherited from CexmcPhaseSpaceGenerator
CexmcPhaseSpaceInVector inVec
CexmcPhaseSpaceOutVector outVec
G4bool fermiEnergyDepIsOn
G4double totalEnergy
G4double totalMass
Detailed Description
Definition at line 51 of file CexmcReimplementedGenbod.hh.
View newest version in sPHENIX GitHub at line 51 of file CexmcReimplementedGenbod.hh
Constructor & Destructor Documentation
CexmcReimplementedGenbod::CexmcReimplementedGenbod ()
Definition at line 81 of file CexmcReimplementedGenbod.cc.
View newest version in sPHENIX GitHub at line 81 of file CexmcReimplementedGenbod.cc
Member Function Documentation
void CexmcReimplementedGenbod::FermiEnergyDepStatusChangeHook (void) private virtual
Reimplemented from CexmcPhaseSpaceGenerator.
Definition at line 202 of file CexmcReimplementedGenbod.cc.
View newest version in sPHENIX GitHub at line 202 of file CexmcReimplementedGenbod.cc
References SetMaxWeight().
G4double CexmcReimplementedGenbod::Generate (void) virtual
Implements CexmcPhaseSpaceGenerator.
Definition at line 87 of file CexmcReimplementedGenbod.cc.
View newest version in sPHENIX GitHub at line 87 of file CexmcReimplementedGenbod.cc
References G4UniformRand, GeV, mass, maxParticles, maxWeight, nmbOfOutputParticles, CexmcPhaseSpaceGenerator::outVec, pi, CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), CLHEP::HepLorentzVector::pz(), CLHEP::HepLorentzVector::setPx(), CLHEP::HepLorentzVector::setPy(), CLHEP::HepLorentzVector::setPz(), sum, CexmcPhaseSpaceGenerator::totalEnergy, CexmcPhaseSpaceGenerator::totalMass, v, x, y, and z.
void CexmcReimplementedGenbod::ParticleChangeHook (void) private virtual
Reimplemented from CexmcPhaseSpaceGenerator.
Definition at line 191 of file CexmcReimplementedGenbod.cc.
View newest version in sPHENIX GitHub at line 191 of file CexmcReimplementedGenbod.cc
References CexmcKinematicsException, maxParticles, nmbOfOutputParticles, CexmcPhaseSpaceGenerator::outVec, and SetMaxWeight().
void CexmcReimplementedGenbod::SetMaxWeight (void) private
Definition at line 208 of file CexmcReimplementedGenbod.cc.
View newest version in sPHENIX GitHub at line 208 of file CexmcReimplementedGenbod.cc
References CexmcPhaseSpaceGenerator::fermiEnergyDepIsOn, GeV, mass, maxWeight, nmbOfOutputParticles, CexmcPhaseSpaceGenerator::outVec, CexmcPhaseSpaceGenerator::totalEnergy, and CexmcPhaseSpaceGenerator::totalMass.
Referenced by FermiEnergyDepStatusChangeHook(), and ParticleChangeHook().
Member Data Documentation
const G4int CexmcReimplementedGenbod::maxParticles = 18 static private
Definition at line 72 of file CexmcReimplementedGenbod.hh.
View newest version in sPHENIX GitHub at line 72 of file CexmcReimplementedGenbod.hh
Referenced by Generate(), and ParticleChangeHook().
G4double CexmcReimplementedGenbod::maxWeight private
Definition at line 67 of file CexmcReimplementedGenbod.hh.
View newest version in sPHENIX GitHub at line 67 of file CexmcReimplementedGenbod.hh
Referenced by Generate(), and SetMaxWeight().
G4int CexmcReimplementedGenbod::nmbOfOutputParticles private
Definition at line 69 of file CexmcReimplementedGenbod.hh.
View newest version in sPHENIX GitHub at line 69 of file CexmcReimplementedGenbod.hh
Referenced by Generate(), ParticleChangeHook(), and SetMaxWeight().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/include/CexmcReimplementedGenbod.hh
geant4/tree/geant4-10.6-release/examples/advanced/ChargeExchangeMC/src/CexmcReimplementedGenbod.cc