ECCE @ EIC Software: G4ErrorSurfaceTrajState Class Reference
G4ErrorSurfaceTrajState Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorSurfaceTrajState.hh>
Public Member Functions
G4ErrorSurfaceTrajState (const G4String &partType, const G4Point3D &pos, const G4Vector3D &mom, const G4Plane3D &plane, const G4ErrorTrajErr &errmat=G4ErrorTrajErr(5, 0))
G4ErrorSurfaceTrajState (const G4String &partType, const G4Point3D &pos, const G4Vector3D &mom, const G4Vector3D &vecV, const G4Vector3D &vecW, const G4ErrorTrajErr &errmat=G4ErrorTrajErr(5, 0))
G4ErrorSurfaceTrajState (G4ErrorFreeTrajState &tpSC, const G4Plane3D &plane)
G4ErrorSurfaceTrajState (G4ErrorFreeTrajState &tpSC, const G4Vector3D &vecV, const G4Vector3D &vecW, G4ErrorMatrix &transfM)
~G4ErrorSurfaceTrajState ()
G4ErrorMatrix BuildErrorMatrix (G4ErrorFreeTrajState &tpSC, const G4Vector3D &vecV, const G4Vector3D &vecW)
virtual void Dump (std::ostream &out=G4cout) const
G4ErrorSurfaceTrajParam GetParameters () const
void SetParameters (const G4Point3D &pos, const G4Vector3D &mom, const G4Vector3D &vecV, const G4Vector3D &vecW)
void SetParameters (const G4Point3D &pos, const G4Vector3D &mom, const G4Plane3D &plane)
G4Vector3D GetVectorV () const
G4Vector3D GetVectorW () const
virtual void SetPosition (const G4Point3D pos)
virtual void SetMomentum (const G4Vector3D &mom)
Public Member Functions inherited from G4ErrorTrajState
G4ErrorTrajState ()
G4ErrorTrajState (const G4String &partType, const G4Point3D &pos, const G4Vector3D &mom, const G4ErrorTrajErr &errmat=G4ErrorTrajErr(5, 0))
virtual ~G4ErrorTrajState ()
void SetData (const G4String &partType, const G4Point3D &pos, const G4Vector3D &mom)
void BuildCharge ()
virtual G4int PropagateError (const G4Track *)
virtual G4int Update (const G4Track *)
void UpdatePosMom (const G4Point3D &pos, const G4Vector3D &mom)
void DumpPosMomError (std::ostream &out=G4cout) const
const G4String & GetParticleType () const
void SetParticleType (const G4String &partType)
G4Point3D GetPosition () const
G4Vector3D GetMomentum () const
G4ErrorTrajErr GetError () const
virtual void SetError (G4ErrorTrajErr em)
G4Track * GetG4Track () const
void SetG4Track (G4Track *trk)
G4double GetCharge () const
void SetCharge (G4double ch)
virtual G4eTSType GetTSType () const
Private Member Functions
void Init ()
Private Attributes
G4ErrorSurfaceTrajParam fTrajParam
Friends
std::ostream & operator<< (std::ostream &, const G4ErrorSurfaceTrajState &ts)
Additional Inherited Members
Protected Attributes inherited from G4ErrorTrajState
G4String fParticleType
G4Point3D fPosition
G4Vector3D fMomentum
G4double fCharge
G4ErrorTrajErr fError
G4eTSType theTSType
G4Track * theG4Track
G4int iverbose
Detailed Description
Definition at line 55 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ErrorSurfaceTrajState.hh
Constructor & Destructor Documentation
G4ErrorSurfaceTrajState::G4ErrorSurfaceTrajState (const G4String & partType, const G4Point3D & pos, const G4Vector3D & mom, const G4Plane3D & plane, const G4ErrorTrajErr & errmat = G4ErrorTrajErr(5,0))
Definition at line 59 of file G4ErrorSurfaceTrajState.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ErrorSurfaceTrajState.cc
References fTrajParam, and Init().
G4ErrorSurfaceTrajState::G4ErrorSurfaceTrajState (const G4String & partType, const G4Point3D & pos, const G4Vector3D & mom, const G4Vector3D & vecV, const G4Vector3D & vecW, const G4ErrorTrajErr & errmat = G4ErrorTrajErr(5,0))
Definition at line 47 of file G4ErrorSurfaceTrajState.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ErrorSurfaceTrajState.cc
References fTrajParam, and Init().
G4ErrorSurfaceTrajState::G4ErrorSurfaceTrajState (G4ErrorFreeTrajState & tpSC, const G4Plane3D & plane)
Definition at line 72 of file G4ErrorSurfaceTrajState.cc.
View newest version in sPHENIX GitHub at line 72 of file G4ErrorSurfaceTrajState.cc
References BuildErrorMatrix(), G4ErrorTrajState::fMomentum, G4ErrorTrajState::fPosition, fTrajParam, GetVectorV(), GetVectorW(), and Init().
G4ErrorSurfaceTrajState::G4ErrorSurfaceTrajState (G4ErrorFreeTrajState & tpSC, const G4Vector3D & vecV, const G4Vector3D & vecW, G4ErrorMatrix & transfM)
Definition at line 89 of file G4ErrorSurfaceTrajState.cc.
View newest version in sPHENIX GitHub at line 89 of file G4ErrorSurfaceTrajState.cc
References BuildErrorMatrix(), G4ErrorTrajState::fMomentum, G4ErrorTrajState::fPosition, fTrajParam, and Init().
G4ErrorSurfaceTrajState::~G4ErrorSurfaceTrajState () inline
Definition at line 80 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ErrorSurfaceTrajState.hh
Member Function Documentation
G4ErrorMatrix G4ErrorSurfaceTrajState::BuildErrorMatrix (G4ErrorFreeTrajState & tpSC, const G4Vector3D & vecV, const G4Vector3D & vecW)
Definition at line 103 of file G4ErrorSurfaceTrajState.cc.
View newest version in sPHENIX GitHub at line 103 of file G4ErrorSurfaceTrajState.cc
References source.hepunit::c_light, cm, HepGeom::BasicVector3D< T >::cross(), G4ErrorTrajState::fCharge, G4ErrorTrajState::fError, G4ErrorTrajState::fMomentum, G4ErrorTrajState::fPosition, G4cout, G4endl, G4ErrorMode_PropBackwards, G4FieldManager::GetDetectorField(), G4ErrorTrajState::GetError(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4TransportationManager::GetFieldManager(), G4Field::GetFieldValue(), G4ErrorFreeTrajParam::GetLambda(), G4ErrorFreeTrajState::GetParameters(), G4ErrorFreeTrajParam::GetPhi(), G4TransportationManager::GetTransportationManager(), GetVectorV(), GetVectorW(), GeV, H, G4ErrorTrajState::iverbose, km, CLHEP::Hep3Vector::mag(), HepGeom::BasicVector3D< T >::mag(), ns, CLHEP::pi, pos(), Q, G4ErrorSymMatrix::similarity(), tesla, CLHEP::Hep3Vector::x(), HepGeom::BasicVector3D< T >::x(), CLHEP::Hep3Vector::y(), HepGeom::BasicVector3D< T >::y(), CLHEP::Hep3Vector::z(), and HepGeom::BasicVector3D< T >::z().
Referenced by G4ErrorSurfaceTrajState().
void G4ErrorSurfaceTrajState::Dump (std::ostream & out = G4cout) const virtual
Implements G4ErrorTrajState.
Definition at line 217 of file G4ErrorSurfaceTrajState.cc.
View newest version in sPHENIX GitHub at line 217 of file G4ErrorSurfaceTrajState.cc
G4ErrorSurfaceTrajParam G4ErrorSurfaceTrajState::GetParameters () const inline
Definition at line 92 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ErrorSurfaceTrajState.hh
References fTrajParam.
Referenced by G4ErrorFreeTrajState::G4ErrorFreeTrajState().
G4Vector3D G4ErrorSurfaceTrajState::GetVectorV () const inline
Definition at line 110 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ErrorSurfaceTrajState.hh
References fTrajParam, and G4ErrorSurfaceTrajParam::GetVectorV().
Referenced by BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4ErrorSurfaceTrajState(), SetMomentum(), and SetPosition().
G4Vector3D G4ErrorSurfaceTrajState::GetVectorW () const inline
Definition at line 113 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ErrorSurfaceTrajState.hh
References fTrajParam, and G4ErrorSurfaceTrajParam::GetVectorW().
Referenced by BuildErrorMatrix(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4ErrorSurfaceTrajState(), SetMomentum(), and SetPosition().
void G4ErrorSurfaceTrajState::Init () private
Definition at line 209 of file G4ErrorSurfaceTrajState.cc.
View newest version in sPHENIX GitHub at line 209 of file G4ErrorSurfaceTrajState.cc
References G4ErrorTrajState::BuildCharge(), G4eTS_OS, and G4ErrorTrajState::theTSType.
Referenced by G4ErrorSurfaceTrajState().
virtual void G4ErrorSurfaceTrajState::SetMomentum (const G4Vector3D & mom) inline virtual
Reimplemented from G4ErrorTrajState.
Definition at line 119 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ErrorSurfaceTrajState.hh
References G4ErrorTrajState::fPosition, GetVectorV(), GetVectorW(), and SetParameters().
void G4ErrorSurfaceTrajState::SetParameters (const G4Point3D & pos, const G4Vector3D & mom, const G4Vector3D & vecV, const G4Vector3D & vecW) inline
Definition at line 94 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ErrorSurfaceTrajState.hh
References G4ErrorTrajState::fMomentum, G4ErrorTrajState::fPosition, fTrajParam, mom, pos(), and G4ErrorSurfaceTrajParam::SetParameters().
Referenced by SetMomentum(), and SetPosition().
void G4ErrorSurfaceTrajState::SetParameters (const G4Point3D & pos, const G4Vector3D & mom, const G4Plane3D & plane) inline
Definition at line 102 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 102 of file G4ErrorSurfaceTrajState.hh
References G4ErrorTrajState::fMomentum, G4ErrorTrajState::fPosition, fTrajParam, mom, pos(), and G4ErrorSurfaceTrajParam::SetParameters().
virtual void G4ErrorSurfaceTrajState::SetPosition (const G4Point3D pos) inline virtual
Reimplemented from G4ErrorTrajState.
Definition at line 116 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ErrorSurfaceTrajState.hh
References G4ErrorTrajState::fMomentum, GetVectorV(), GetVectorW(), and SetParameters().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4ErrorSurfaceTrajState & ts) friend
Definition at line 224 of file G4ErrorSurfaceTrajState.cc.
View newest version in sPHENIX GitHub at line 224 of file G4ErrorSurfaceTrajState.cc
Member Data Documentation
G4ErrorSurfaceTrajParam G4ErrorSurfaceTrajState::fTrajParam private
Definition at line 129 of file G4ErrorSurfaceTrajState.hh.
View newest version in sPHENIX GitHub at line 129 of file G4ErrorSurfaceTrajState.hh
Referenced by G4ErrorSurfaceTrajState(), GetParameters(), GetVectorV(), GetVectorW(), operator<<(), and SetParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorSurfaceTrajState.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorSurfaceTrajState.cc