ECCE @ EIC Software: FCALSteppingAction Class Reference
FCALSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/lAr_calorimeter/include/FCALSteppingAction.hh>
Public Member Functions
FCALSteppingAction ()
virtual ~FCALSteppingAction ()
virtual void UserSteppingAction (const G4Step *)
void initialize (G4int)
G4double GetOutOfWorldTracks (G4int, G4int)
G4double GetSecondaries (G4int, G4int)
G4double GetEdepFCAL (G4String)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
G4int EventNo
G4int IDnow
G4int IDold
G4int IDout
G4int NTracks
G4int NSecondaries
G4double OutOfWorldTracksData [6000][11]
G4double Secondaries [6000][11]
G4double EdepFCALEm
G4double EdepFCALHad
G4ThreeVector PrimaryVertex
G4ThreeVector PrimaryDirection
G4ThreeVector SecondaryVertex
G4ThreeVector SecondaryDirection
G4ThreeVector Distance
G4ThreeVector VectorProduct
G4ThreeVector VectorProductNorm
G4double VectorProductMagnitude
G4double DistOfClosestApproach
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 41 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 41 of file FCALSteppingAction.hh
Constructor & Destructor Documentation
FCALSteppingAction::FCALSteppingAction ()
Definition at line 56 of file FCALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 56 of file FCALSteppingAction.cc
FCALSteppingAction::~FCALSteppingAction () virtual
Definition at line 61 of file FCALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 61 of file FCALSteppingAction.cc
Member Function Documentation
G4double FCALSteppingAction::GetEdepFCAL (G4String FCAL)
Definition at line 238 of file FCALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 238 of file FCALSteppingAction.cc
References EdepFCALEm, and EdepFCALHad.
Referenced by FCALTBEventAction::EndOfEventAction().
G4double FCALSteppingAction::GetOutOfWorldTracks (G4int i, G4int j)
Definition at line 230 of file FCALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 230 of file FCALSteppingAction.cc
References OutOfWorldTracksData.
Referenced by FCALTBEventAction::EndOfEventAction().
G4double FCALSteppingAction::GetSecondaries (G4int i, G4int j)
Definition at line 234 of file FCALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 234 of file FCALSteppingAction.cc
References Secondaries.
Referenced by FCALTBEventAction::EndOfEventAction().
void FCALSteppingAction::initialize (G4int Nev)
Definition at line 214 of file FCALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 214 of file FCALSteppingAction.cc
References EdepFCALEm, EdepFCALHad, EventNo, NSecondaries, NTracks, OutOfWorldTracksData, and Secondaries.
Referenced by FCALTBEventAction::BeginOfEventAction().
void FCALSteppingAction::UserSteppingAction (const G4Step * astep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 66 of file FCALSteppingAction.cc.
View newest version in sPHENIX GitHub at line 66 of file FCALSteppingAction.cc
References kdfinder::abs(), cm, CLHEP::Hep3Vector::cross(), Distance, DistOfClosestApproach, EdepFCALEm, EdepFCALHad, EventNo, G4cout, G4endl, G4Track::GetCurrentStepNumber(), G4Track::GetDefinition(), G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterial(), G4DynamicParticle::GetMomentum(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4Track::GetNextVolume(), G4Track::GetParentID(), G4ParticleDefinition::GetParticleName(), G4ParticleDefinition::GetPDGEncoding(), G4DynamicParticle::GetTotalEnergy(), G4Step::GetTotalEnergyDeposit(), G4DynamicParticle::GetTotalMomentum(), G4Track::GetTouchable(), G4Step::GetTrack(), G4Track::GetTrackID(), G4Track::GetVertexMomentumDirection(), G4Track::GetVertexPosition(), G4TouchableHistory::GetVolume(), IDnow, IDold, IDout, CLHEP::Hep3Vector::mag(), mm, NSecondaries, NTracks, OutOfWorldTracksData, PrimaryDirection, PrimaryVertex, Secondaries, SecondaryDirection, SecondaryVertex, VectorProduct, VectorProductMagnitude, VectorProductNorm, CLHEP::Hep3Vector::x(), x, CLHEP::Hep3Vector::y(), y, CLHEP::Hep3Vector::z(), and z.
Member Data Documentation
G4ThreeVector FCALSteppingAction::Distance private
Definition at line 58 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4double FCALSteppingAction::DistOfClosestApproach private
Definition at line 59 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4double FCALSteppingAction::EdepFCALEm private
Definition at line 54 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file FCALSteppingAction.hh
Referenced by GetEdepFCAL(), initialize(), and UserSteppingAction().
G4double FCALSteppingAction::EdepFCALHad private
Definition at line 54 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file FCALSteppingAction.hh
Referenced by GetEdepFCAL(), initialize(), and UserSteppingAction().
G4int FCALSteppingAction::EventNo private
Definition at line 50 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 50 of file FCALSteppingAction.hh
Referenced by initialize(), and UserSteppingAction().
G4int FCALSteppingAction::IDnow private
Definition at line 51 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4int FCALSteppingAction::IDold private
Definition at line 51 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4int FCALSteppingAction::IDout private
Definition at line 51 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4int FCALSteppingAction::NSecondaries private
Definition at line 52 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file FCALSteppingAction.hh
Referenced by initialize(), and UserSteppingAction().
G4int FCALSteppingAction::NTracks private
Definition at line 52 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file FCALSteppingAction.hh
Referenced by initialize(), and UserSteppingAction().
G4double FCALSteppingAction::OutOfWorldTracksData[6000][11] private
Definition at line 53 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file FCALSteppingAction.hh
Referenced by GetOutOfWorldTracks(), initialize(), and UserSteppingAction().
G4ThreeVector FCALSteppingAction::PrimaryDirection private
Definition at line 56 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4ThreeVector FCALSteppingAction::PrimaryVertex private
Definition at line 56 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4double FCALSteppingAction::Secondaries[6000][11] private
Definition at line 53 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file FCALSteppingAction.hh
Referenced by GetSecondaries(), initialize(), and UserSteppingAction().
G4ThreeVector FCALSteppingAction::SecondaryDirection private
Definition at line 57 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4ThreeVector FCALSteppingAction::SecondaryVertex private
Definition at line 57 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4ThreeVector FCALSteppingAction::VectorProduct private
Definition at line 58 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4double FCALSteppingAction::VectorProductMagnitude private
Definition at line 59 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
G4ThreeVector FCALSteppingAction::VectorProductNorm private
Definition at line 58 of file FCALSteppingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file FCALSteppingAction.hh
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/lAr_calorimeter/include/FCALSteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/lAr_calorimeter/src/FCALSteppingAction.cc