ECCE @ EIC Software: G4AugerData Class Reference
G4AugerData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4AugerData.hh>
Public Member Functions
G4AugerData ()
~G4AugerData ()
size_t NumberOfVacancies (G4int Z) const
G4int VacancyId (G4int Z, G4int vacancyIndex) const
size_t NumberOfTransitions (G4int Z, G4int vacancyIndex) const
G4int StartShellId (G4int Z, G4int initialVacancyIndex, G4int transitionShellIndex) const
G4double StartShellEnergy (G4int Z, G4int vacancyIndex, G4int transitionId, G4int augerIndex) const
G4double StartShellProb (G4int Z, G4int vacancyIndex, G4int transitionId, G4int augerIndex) const
size_t NumberOfAuger (G4int Z, G4int initIndex, G4int vacancyId) const
size_t AugerShellId (G4int Z, G4int vacancyIndex, G4int transId, G4int augerIndex) const
std::vector< G4AugerTransition > LoadData (G4int Z)
void BuildAugerTransitionTable ()
void PrintData (G4int Z)
G4AugerTransition * GetAugerTransition (G4int Z, G4int vacancyShellIndex)
std::vector< G4AugerTransition > * GetAugerTransitions (G4int Z)
Private Types
typedef std::map< G4int,
std::vector< G4AugerTransition >
, std::less< G4int > > trans_Table
Private Attributes
trans_Table augerTransitionTable
std::vector< G4int > nInitShells
std::vector< G4int > numberOfVacancies
Detailed Description
Definition at line 53 of file G4AugerData.hh.
View newest version in sPHENIX GitHub at line 53 of file G4AugerData.hh
Member Typedef Documentation
typedef std::map<G4int,std::vector<G4AugerTransition>,std::less<G4int> > G4AugerData::trans_Table private
Definition at line 113 of file G4AugerData.hh.
View newest version in sPHENIX GitHub at line 113 of file G4AugerData.hh
Constructor & Destructor Documentation
G4AugerData::G4AugerData ()
Definition at line 49 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 49 of file G4AugerData.cc
References BuildAugerTransitionTable(), n, numberOfVacancies, and pos().
G4AugerData::~G4AugerData ()
Definition at line 65 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 65 of file G4AugerData.cc
Member Function Documentation
size_t G4AugerData::AugerShellId (G4int Z, G4int vacancyIndex, G4int transId, G4int augerIndex) const
Definition at line 185 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 185 of file G4AugerData.cc
References augerTransitionTable, FatalErrorInArgument, G4Exception(), n, and numberOfVacancies.
Referenced by PrintData().
void G4AugerData::BuildAugerTransitionTable ()
Definition at line 507 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 507 of file G4AugerData.cc
References augerTransitionTable, G4DataVector::contains(), G4Material::GetElementVector(), G4Material::GetMaterialTable(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), G4Element::GetZ(), LoadData(), material(), G4TrackingService::nMaterials, and Z.
Referenced by G4AugerData().
G4AugerTransition * G4AugerData::GetAugerTransition (G4int Z, G4int vacancyShellIndex)
Definition at line 576 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 576 of file G4AugerData.cc
References augerTransitionTable, and Z.
Referenced by G4AtomicTransitionManager::ReachableAugerShell().
std::vector< G4AugerTransition > * G4AugerData::GetAugerTransitions (G4int Z)
Definition at line 585 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 585 of file G4AugerData.cc
References augerTransitionTable, and Z.
std::vector< G4AugerTransition > G4AugerData::LoadData (G4int Z)
Definition at line 275 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 275 of file G4AugerData.cc
References a, e, FatalException, file, G4Exception(), k, MeV, n, nInitShells, numberOfVacancies, and Z.
Referenced by BuildAugerTransitionTable().
size_t G4AugerData::NumberOfAuger (G4int Z, G4int initIndex, G4int vacancyId) const
Definition at line 164 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 164 of file G4AugerData.cc
References augerTransitionTable, FatalErrorInArgument, G4Exception(), n, and numberOfVacancies.
Referenced by PrintData().
size_t G4AugerData::NumberOfTransitions (G4int Z, G4int vacancyIndex) const
Definition at line 141 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 141 of file G4AugerData.cc
References augerTransitionTable, FatalErrorInArgument, G4Exception(), JustWarning, n, and numberOfVacancies.
Referenced by PrintData().
size_t G4AugerData::NumberOfVacancies (G4int Z) const
Definition at line 112 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 112 of file G4AugerData.cc
References numberOfVacancies, and Z.
Referenced by G4AtomicTransitionManager::NumberOfReachableAugerShells().
void G4AugerData::PrintData (G4int Z)
Definition at line 545 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 545 of file G4AugerData.cc
References a, AugerShellId(), e, G4cout, G4endl, k, MeV, NumberOfAuger(), NumberOfTransitions(), numberOfVacancies, StartShellEnergy(), StartShellId(), StartShellProb(), and Z.
G4double G4AugerData::StartShellEnergy (G4int Z, G4int vacancyIndex, G4int transitionId, G4int augerIndex) const
Definition at line 228 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 228 of file G4AugerData.cc
References augerTransitionTable, energy, FatalErrorInArgument, G4Exception(), and numberOfVacancies.
Referenced by PrintData().
G4int G4AugerData::StartShellId (G4int Z, G4int initialVacancyIndex, G4int transitionShellIndex) const
Definition at line 205 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 205 of file G4AugerData.cc
References augerTransitionTable, FatalErrorInArgument, G4Exception(), n, and numberOfVacancies.
Referenced by PrintData().
G4double G4AugerData::StartShellProb (G4int Z, G4int vacancyIndex, G4int transitionId, G4int augerIndex) const
Definition at line 251 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 251 of file G4AugerData.cc
References augerTransitionTable, FatalErrorInArgument, G4Exception(), and numberOfVacancies.
Referenced by PrintData().
G4int G4AugerData::VacancyId (G4int Z, G4int vacancyIndex) const
Definition at line 117 of file G4AugerData.cc.
View newest version in sPHENIX GitHub at line 117 of file G4AugerData.cc
References augerTransitionTable, FatalErrorInArgument, G4Exception(), n, and numberOfVacancies.
Member Data Documentation
trans_Table G4AugerData::augerTransitionTable private
Definition at line 114 of file G4AugerData.hh.
View newest version in sPHENIX GitHub at line 114 of file G4AugerData.hh
Referenced by AugerShellId(), BuildAugerTransitionTable(), GetAugerTransition(), GetAugerTransitions(), NumberOfAuger(), NumberOfTransitions(), StartShellEnergy(), StartShellId(), StartShellProb(), and VacancyId().
std::vector<G4int> G4AugerData::nInitShells private
Definition at line 121 of file G4AugerData.hh.
View newest version in sPHENIX GitHub at line 121 of file G4AugerData.hh
Referenced by LoadData().
std::vector<G4int> G4AugerData::numberOfVacancies private
Definition at line 122 of file G4AugerData.hh.
View newest version in sPHENIX GitHub at line 122 of file G4AugerData.hh
Referenced by AugerShellId(), G4AugerData(), LoadData(), NumberOfAuger(), NumberOfTransitions(), NumberOfVacancies(), PrintData(), StartShellEnergy(), StartShellId(), StartShellProb(), and VacancyId().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4AugerData.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4AugerData.cc