ECCE @ EIC Software: G4ErrorSurfaceTrajParam Class Reference
G4ErrorSurfaceTrajParam Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorSurfaceTrajParam.hh>
Public Member Functions
G4ErrorSurfaceTrajParam ()
G4ErrorSurfaceTrajParam (const G4Point3D &pos, const G4Vector3D &mom, const G4Vector3D &vecV, const G4Vector3D &vecW)
G4ErrorSurfaceTrajParam (const G4Point3D &pos, const G4Vector3D &mom, const G4Plane3D &plane)
virtual ~G4ErrorSurfaceTrajParam ()
void SetParameters (const G4Point3D &pos, const G4Vector3D &mom, const G4Vector3D &vecV, const G4Vector3D &vecW)
void SetParameters (const G4Point3D &pos, const G4Vector3D &mom, const G4Plane3D &plane)
G4Vector3D GetDirection () const
G4Vector3D GetPlaneNormal () const
G4Vector3D GetVectorV () const
G4Vector3D GetVectorW () const
G4double GetPV () const
G4double GetPW () const
G4double GetV () const
G4double GetW () const
G4double GetInvP () const
Private Attributes
G4ThreeVector fDir
G4Vector3D fVectorV
G4Vector3D fVectorW
G4double fInvP
G4double fPV
G4double fPW
G4double fV
G4double fW
Friends
std::ostream & operator<< (std::ostream &, const G4ErrorSurfaceTrajParam &ts)
Detailed Description
Definition at line 51 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ErrorSurfaceTrajParam.hh
Constructor & Destructor Documentation
G4ErrorSurfaceTrajParam::G4ErrorSurfaceTrajParam () inline
Definition at line 55 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ErrorSurfaceTrajParam.hh
G4ErrorSurfaceTrajParam::G4ErrorSurfaceTrajParam (const G4Point3D & pos, const G4Vector3D & mom, const G4Vector3D & vecV, const G4Vector3D & vecW)
Definition at line 40 of file G4ErrorSurfaceTrajParam.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ErrorSurfaceTrajParam.cc
References SetParameters().
G4ErrorSurfaceTrajParam::G4ErrorSurfaceTrajParam (const G4Point3D & pos, const G4Vector3D & mom, const G4Plane3D & plane)
Definition at line 49 of file G4ErrorSurfaceTrajParam.cc.
View newest version in sPHENIX GitHub at line 49 of file G4ErrorSurfaceTrajParam.cc
References SetParameters().
virtual G4ErrorSurfaceTrajParam::~G4ErrorSurfaceTrajParam () inline virtual
Definition at line 61 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ErrorSurfaceTrajParam.hh
Member Function Documentation
G4Vector3D G4ErrorSurfaceTrajParam::GetDirection () const inline
Definition at line 73 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ErrorSurfaceTrajParam.hh
References fDir.
G4double G4ErrorSurfaceTrajParam::GetInvP () const inline
Definition at line 81 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 81 of file G4ErrorSurfaceTrajParam.hh
References fInvP.
G4Vector3D G4ErrorSurfaceTrajParam::GetPlaneNormal () const inline
Definition at line 74 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ErrorSurfaceTrajParam.hh
References HepGeom::BasicVector3D< T >::cross(), fVectorV, and fVectorW.
G4double G4ErrorSurfaceTrajParam::GetPV () const inline
Definition at line 77 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ErrorSurfaceTrajParam.hh
References fPV.
Referenced by G4ErrorFreeTrajState::G4ErrorFreeTrajState().
G4double G4ErrorSurfaceTrajParam::GetPW () const inline
Definition at line 78 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ErrorSurfaceTrajParam.hh
References fPW.
Referenced by G4ErrorFreeTrajState::G4ErrorFreeTrajState().
G4double G4ErrorSurfaceTrajParam::GetV () const inline
Definition at line 79 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ErrorSurfaceTrajParam.hh
References fV.
G4Vector3D G4ErrorSurfaceTrajParam::GetVectorV () const inline
Definition at line 75 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ErrorSurfaceTrajParam.hh
References fVectorV.
Referenced by G4ErrorFreeTrajState::G4ErrorFreeTrajState(), and G4ErrorSurfaceTrajState::GetVectorV().
G4Vector3D G4ErrorSurfaceTrajParam::GetVectorW () const inline
Definition at line 76 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 76 of file G4ErrorSurfaceTrajParam.hh
References fVectorW.
Referenced by G4ErrorFreeTrajState::G4ErrorFreeTrajState(), and G4ErrorSurfaceTrajState::GetVectorW().
G4double G4ErrorSurfaceTrajParam::GetW () const inline
Definition at line 80 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ErrorSurfaceTrajParam.hh
References fW.
void G4ErrorSurfaceTrajParam::SetParameters (const G4Point3D & pos, const G4Vector3D & mom, const G4Vector3D & vecV, const G4Vector3D & vecW)
Definition at line 82 of file G4ErrorSurfaceTrajParam.cc.
View newest version in sPHENIX GitHub at line 82 of file G4ErrorSurfaceTrajParam.cc
References CLHEP::Hep3Vector::dot(), fDir, fInvP, fPV, fPW, fV, fVectorV, fVectorW, fW, HepGeom::BasicVector3D< T >::mag(), and mom.
Referenced by G4ErrorSurfaceTrajParam(), SetParameters(), and G4ErrorSurfaceTrajState::SetParameters().
void G4ErrorSurfaceTrajParam::SetParameters (const G4Point3D & pos, const G4Vector3D & mom, const G4Plane3D & plane)
Definition at line 57 of file G4ErrorSurfaceTrajParam.cc.
View newest version in sPHENIX GitHub at line 57 of file G4ErrorSurfaceTrajParam.cc
References CLHEP::Hep3Vector::cross(), G4GeometryTolerance::GetInstance(), G4GeometryTolerance::GetSurfaceTolerance(), kCarTolerance, HepGeom::BasicVector3D< T >::mag(), HepGeom::Plane3D< T >::normal(), and SetParameters().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4ErrorSurfaceTrajParam & ts) friend
Definition at line 113 of file G4ErrorSurfaceTrajParam.cc.
View newest version in sPHENIX GitHub at line 113 of file G4ErrorSurfaceTrajParam.cc
Member Data Documentation
G4ThreeVector G4ErrorSurfaceTrajParam::fDir private
Definition at line 85 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ErrorSurfaceTrajParam.hh
Referenced by GetDirection(), and SetParameters().
G4double G4ErrorSurfaceTrajParam::fInvP private
Definition at line 88 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 88 of file G4ErrorSurfaceTrajParam.hh
Referenced by GetInvP(), operator<<(), and SetParameters().
G4double G4ErrorSurfaceTrajParam::fPV private
Definition at line 89 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 89 of file G4ErrorSurfaceTrajParam.hh
Referenced by GetPV(), operator<<(), and SetParameters().
G4double G4ErrorSurfaceTrajParam::fPW private
Definition at line 90 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 90 of file G4ErrorSurfaceTrajParam.hh
Referenced by GetPW(), operator<<(), and SetParameters().
G4double G4ErrorSurfaceTrajParam::fV private
Definition at line 91 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 91 of file G4ErrorSurfaceTrajParam.hh
Referenced by GetV(), operator<<(), and SetParameters().
G4Vector3D G4ErrorSurfaceTrajParam::fVectorV private
Definition at line 86 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 86 of file G4ErrorSurfaceTrajParam.hh
Referenced by GetPlaneNormal(), GetVectorV(), operator<<(), and SetParameters().
G4Vector3D G4ErrorSurfaceTrajParam::fVectorW private
Definition at line 87 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 87 of file G4ErrorSurfaceTrajParam.hh
Referenced by GetPlaneNormal(), GetVectorW(), operator<<(), and SetParameters().
G4double G4ErrorSurfaceTrajParam::fW private
Definition at line 92 of file G4ErrorSurfaceTrajParam.hh.
View newest version in sPHENIX GitHub at line 92 of file G4ErrorSurfaceTrajParam.hh
Referenced by GetW(), operator<<(), and SetParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorSurfaceTrajParam.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorSurfaceTrajParam.cc