ECCE @ EIC Software: G4DNAElectronHoleRecombination Class Reference
G4DNAElectronHoleRecombination Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNAElectronHoleRecombination.hh>
Classes
struct ReactantInfo
struct State
Public Member Functions
G4DNAElectronHoleRecombination ()
virtual ~G4DNAElectronHoleRecombination ()
void Create ()
void StartTracking (G4Track *)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double GetMeanLifeTime (const G4Track &aTrack, G4ForceCondition *condition)
Public Member Functions inherited from G4VITRestDiscreteProcess
G4VITRestDiscreteProcess ()=delete
G4VITRestDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VITRestDiscreteProcess (const G4VITRestDiscreteProcess &)=delete
G4VITRestDiscreteProcess & operator= (const G4VITRestDiscreteProcess &right)=delete
~G4VITRestDiscreteProcess () override
G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *) override
G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *) override
G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &) override
Public Member Functions inherited from G4VITProcess
G4VITProcess (const G4String &name, G4ProcessType type=fNotDefined)
virtual ~G4VITProcess ()
G4VITProcess (const G4VITProcess &other)
G4VITProcess & operator= (const G4VITProcess &other)
G4bool operator== (const G4VITProcess &right) const
G4bool operator!= (const G4VITProcess &right) const
size_t GetProcessID () const
G4shared_ptr< G4ProcessState_Lock > GetProcessState ()
void SetProcessState (G4shared_ptr< G4ProcessState_Lock > aProcInfo)
void ResetProcessState ()
G4double GetInteractionTimeLeft ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4bool ProposesTimeStep () const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Member Functions
G4bool FindReactant (const G4Track &track)
void MakeReaction (const G4Track &track)
void BuildDissociationChannels ()
Private Attributes
const std::vector< double > * fpMoleculeDensity
G4ParticleChange fParticleChange
G4bool fIsInitialized
std::map< int, std::pair
< double, double > > fOnsagerRadiusPerMaterial
Additional Inherited Members
Static Public Member Functions inherited from G4VITProcess
static const size_t & GetMaxProcessIndex ()
Protected Member Functions inherited from G4VITProcess
void RetrieveProcessInfo ()
void CreateInfo ()
template<typename T >
T * GetState ()
virtual void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
virtual void ClearInteractionTimeLeft ()
virtual void ClearNumberOfInteractionLengthLeft ()
void SetInstantiateProcessState (G4bool flag)
G4bool InstantiateProcessState ()
Protected Attributes inherited from G4VITProcess
G4shared_ptr< G4ProcessState > fpState
G4bool fProposesTimeStep
Detailed Description
Definition at line 36 of file G4DNAElectronHoleRecombination.hh.
View newest version in sPHENIX GitHub at line 36 of file G4DNAElectronHoleRecombination.hh
Constructor & Destructor Documentation
G4DNAElectronHoleRecombination::G4DNAElectronHoleRecombination ()
Definition at line 106 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 106 of file G4DNAElectronHoleRecombination.cc
References Create().
G4DNAElectronHoleRecombination::~G4DNAElectronHoleRecombination () virtual default
Member Function Documentation
G4VParticleChange * G4DNAElectronHoleRecombination::AtRestDoIt (const G4Track & track, const G4Step &) virtual
Reimplemented from G4VITRestDiscreteProcess.
Definition at line 138 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 138 of file G4DNAElectronHoleRecombination.cc
References G4VITProcess::ClearInteractionTimeLeft(), G4VITProcess::ClearNumberOfInteractionLengthLeft(), fParticleChange, G4ParticleChange::Initialize(), and MakeReaction().
Referenced by PostStepDoIt().
void G4DNAElectronHoleRecombination::BuildDissociationChannels () private
Definition at line 272 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 272 of file G4DNAElectronHoleRecombination.cc
References G4H2O::Definition(), G4MoleculeTable::Instance(), and G4MoleculeDefinition::NewConfiguration().
Referenced by IsApplicable().
virtual void G4DNAElectronHoleRecombination::BuildPhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented from G4VITProcess.
Definition at line 47 of file G4DNAElectronHoleRecombination.hh.
View newest version in sPHENIX GitHub at line 47 of file G4DNAElectronHoleRecombination.hh
void G4DNAElectronHoleRecombination::Create ()
Definition at line 115 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 115 of file G4DNAElectronHoleRecombination.cc
References G4VProcess::enableAlongStepDoIt, G4VProcess::enableAtRestDoIt, G4VProcess::enablePostStepDoIt, fIsInitialized, fParticleChange, fpMoleculeDensity, G4VITProcess::fProposesTimeStep, G4VProcess::pParticleChange, G4VITProcess::SetInstantiateProcessState(), G4VProcess::SetProcessSubType(), and G4VProcess::verboseLevel.
Referenced by G4DNAElectronHoleRecombination().
G4bool G4DNAElectronHoleRecombination::FindReactant (const G4Track & track) private
Definition at line 215 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 215 of file G4DNAElectronHoleRecombination.cc
References G4Electron_aq::Definition(), e, eps, epsilon(), G4ITFinder< T >::FindNearestInRange(), G4VITProcess::fpState, G4DNAElectronHoleRecombination::State::fReactants, Acts::UnitConstants::g, G4Exp(), G4UniformRand, G4DNAMolecularMaterial::GetDensityTableFor(), G4Material::GetIndex(), G4Track::GetMaterial(), GetMolecule(), G4Molecule::GetMoleculeID(), G4Track::GetPosition(), G4Material::GetTemperature(), G4ITFinder< T >::Instance(), G4DNAMolecularMaterial::Instance(), m, and onsager_constant.
Referenced by GetMeanFreePath(), and GetMeanLifeTime().
G4double G4DNAElectronHoleRecombination::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) virtual
Implements G4VITRestDiscreteProcess.
Definition at line 360 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 360 of file G4DNAElectronHoleRecombination.cc
References DBL_MAX, and FindReactant().
G4double G4DNAElectronHoleRecombination::GetMeanLifeTime (const G4Track & aTrack, G4ForceCondition * condition) virtual
Implements G4VITRestDiscreteProcess.
Definition at line 374 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 374 of file G4DNAElectronHoleRecombination.cc
References DBL_MAX, and FindReactant().
G4bool G4DNAElectronHoleRecombination::IsApplicable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 343 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 343 of file G4DNAElectronHoleRecombination.cc
References BuildDissociationChannels(), G4H2O::DefinitionIfExists(), and G4Threading::IsMasterThread().
void G4DNAElectronHoleRecombination::MakeReaction (const G4Track & track) private
Definition at line 159 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 159 of file G4DNAElectronHoleRecombination.cc
References G4Molecule::ChangeConfigurationToLabel(), fAlive, fParticleChange, G4VITProcess::fpState, G4DNAElectronHoleRecombination::State::fSampleProba, fStopAndKill, fStopButAlive, G4Track::GetGlobalTime(), GetMolecule(), G4Track::GetPosition(), G4ParticleChange::Initialize(), G4VMoleculeCounter::Instance(), G4VMoleculeCounter::InUse(), G4VParticleChange::ProposeTrackStatus(), and G4Track::SetTrackStatus().
Referenced by AtRestDoIt().
G4VParticleChange * G4DNAElectronHoleRecombination::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Reimplemented from G4VITRestDiscreteProcess.
Definition at line 385 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 385 of file G4DNAElectronHoleRecombination.cc
References AtRestDoIt().
void G4DNAElectronHoleRecombination::StartTracking (G4Track * pTrack) virtual
Reimplemented from G4VITProcess.
Definition at line 150 of file G4DNAElectronHoleRecombination.cc.
View newest version in sPHENIX GitHub at line 150 of file G4DNAElectronHoleRecombination.cc
References G4VITProcess::fpState, G4VITProcess::StartTracking(), G4VProcess::StartTracking(), and State.
Member Data Documentation
G4bool G4DNAElectronHoleRecombination::fIsInitialized private
Definition at line 105 of file G4DNAElectronHoleRecombination.hh.
View newest version in sPHENIX GitHub at line 105 of file G4DNAElectronHoleRecombination.hh
Referenced by Create().
std::map<int, std::pair<double, double> > G4DNAElectronHoleRecombination::fOnsagerRadiusPerMaterial private
Definition at line 106 of file G4DNAElectronHoleRecombination.hh.
View newest version in sPHENIX GitHub at line 106 of file G4DNAElectronHoleRecombination.hh
G4ParticleChange G4DNAElectronHoleRecombination::fParticleChange private
Definition at line 104 of file G4DNAElectronHoleRecombination.hh.
View newest version in sPHENIX GitHub at line 104 of file G4DNAElectronHoleRecombination.hh
Referenced by AtRestDoIt(), Create(), and MakeReaction().
const std::vector<double>* G4DNAElectronHoleRecombination::fpMoleculeDensity private
Definition at line 103 of file G4DNAElectronHoleRecombination.hh.
View newest version in sPHENIX GitHub at line 103 of file G4DNAElectronHoleRecombination.hh
Referenced by Create().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/include/G4DNAElectronHoleRecombination.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/processes/src/G4DNAElectronHoleRecombination.cc