ECCE @ EIC Software: G4HadronPhysicsShieldingLEND Class Reference
G4HadronPhysicsShieldingLEND Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsShieldingLEND.hh>
Public Member Functions
G4HadronPhysicsShieldingLEND (G4int verbose=1)
G4HadronPhysicsShieldingLEND (const G4String &name, G4bool)
G4HadronPhysicsShieldingLEND (const G4String &name, G4int verbose=1, G4double minFTFPEnergy=G4HadronicParameters::Instance() ->GetMinEnergyTransitionFTF_Cascade(), G4double maxBertiniEnergy=G4HadronicParameters::Instance() ->GetMaxEnergyTransitionFTF_Cascade())
virtual ~G4HadronPhysicsShieldingLEND ()
virtual void ConstructParticle () override
virtual void ConstructProcess () override
void UseLEND (G4String ss="")
void UnuseLEND ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Private Member Functions
virtual void CreateModels ()
virtual void Neutron ()
virtual void Proton ()
virtual void Pion ()
virtual void Kaon ()
virtual void Others ()
virtual void DumpBanner ()
virtual void ExtraConfiguration ()
Private Attributes
G4bool useLEND_
G4String evaluation_
const G4double minFTFPEnergy_
const G4double maxBertiniEnergy_
const G4double minNonHPNeutronEnergy_
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 47 of file G4HadronPhysicsShieldingLEND.hh.
View newest version in sPHENIX GitHub at line 47 of file G4HadronPhysicsShieldingLEND.hh
Constructor & Destructor Documentation
G4HadronPhysicsShieldingLEND::G4HadronPhysicsShieldingLEND (G4int verbose = 1) explicit
Definition at line 103 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 103 of file G4HadronPhysicsShieldingLEND.cc
G4HadronPhysicsShieldingLEND::G4HadronPhysicsShieldingLEND (const G4String & name, G4bool) explicit
Definition at line 112 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 112 of file G4HadronPhysicsShieldingLEND.cc
G4HadronPhysicsShieldingLEND::G4HadronPhysicsShieldingLEND (const G4String & name, G4int verbose = 1, G4double minFTFPEnergy = G4HadronicParameters::Instance()->GetMinEnergyTransitionFTF_Cascade(), G4double maxBertiniEnergy = G4HadronicParameters::Instance()->GetMaxEnergyTransitionFTF_Cascade()) explicit
Definition at line 121 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 121 of file G4HadronPhysicsShieldingLEND.cc
G4HadronPhysicsShieldingLEND::~G4HadronPhysicsShieldingLEND () virtual
Definition at line 132 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 132 of file G4HadronPhysicsShieldingLEND.cc
Member Function Documentation
void G4HadronPhysicsShieldingLEND::ConstructParticle (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 145 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 145 of file G4HadronPhysicsShieldingLEND.cc
References G4MesonConstructor::ConstructParticle(), G4IonConstructor::ConstructParticle(), G4BaryonConstructor::ConstructParticle(), and G4ShortLivedConstructor::ConstructParticle().
void G4HadronPhysicsShieldingLEND::ConstructProcess (void) override virtual
Implements G4VPhysicsConstructor.
Definition at line 256 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 256 of file G4HadronPhysicsShieldingLEND.cc
References CreateModels(), DumpBanner(), ExtraConfiguration(), and G4Threading::IsMasterThread().
void G4HadronPhysicsShieldingLEND::CreateModels () private virtual
Definition at line 161 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 161 of file G4HadronPhysicsShieldingLEND.cc
References Kaon(), Neutron(), Others(), Pion(), and Proton().
Referenced by ConstructProcess().
void G4HadronPhysicsShieldingLEND::DumpBanner () private virtual
Definition at line 136 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 136 of file G4HadronPhysicsShieldingLEND.cc
References G4cout, G4endl, GeV, maxBertiniEnergy_, and minFTFPEnergy_.
Referenced by ConstructProcess().
void G4HadronPhysicsShieldingLEND::ExtraConfiguration () private virtual
Definition at line 266 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 266 of file G4HadronPhysicsShieldingLEND.cc
References G4CrossSectionDataStore::AddDataSet(), G4HadronicProcess::AddDataSet(), G4PhysListUtil::FindCaptureProcess(), G4PhysListUtil::FindFissionProcess(), G4PhysListUtil::FindInelasticProcess(), G4HadronicProcess::GetCrossSectionDataStore(), G4HadronicParameters::Instance(), G4KaonMinus::KaonMinus(), G4KaonPlus::KaonPlus(), G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), minNonHPNeutronEnergy_, G4InuclParticleNames::neutron, G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), and G4HadronicInteraction::SetMinEnergy().
Referenced by ConstructProcess().
void G4HadronPhysicsShieldingLEND::Kaon () private virtual
Definition at line 223 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 223 of file G4HadronPhysicsShieldingLEND.cc
References G4VPhysicsConstructor::AddBuilder(), k, maxBertiniEnergy_, and minFTFPEnergy_.
Referenced by CreateModels().
void G4HadronPhysicsShieldingLEND::Neutron () private virtual
Definition at line 171 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 171 of file G4HadronPhysicsShieldingLEND.cc
References G4VPhysicsConstructor::AddBuilder(), evaluation_, maxBertiniEnergy_, minFTFPEnergy_, minNonHPNeutronEnergy_, and G4InuclParticleNames::neu.
Referenced by CreateModels().
void G4HadronPhysicsShieldingLEND::Others () private virtual
Definition at line 239 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 239 of file G4HadronPhysicsShieldingLEND.cc
References G4VPhysicsConstructor::AddBuilder().
Referenced by CreateModels().
void G4HadronPhysicsShieldingLEND::Pion () private virtual
Definition at line 207 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 207 of file G4HadronPhysicsShieldingLEND.cc
References G4VPhysicsConstructor::AddBuilder(), maxBertiniEnergy_, minFTFPEnergy_, and pi.
Referenced by CreateModels().
void G4HadronPhysicsShieldingLEND::Proton () private virtual
Definition at line 191 of file G4HadronPhysicsShieldingLEND.cc.
View newest version in sPHENIX GitHub at line 191 of file G4HadronPhysicsShieldingLEND.cc
References G4VPhysicsConstructor::AddBuilder(), maxBertiniEnergy_, minFTFPEnergy_, and G4InuclParticleNames::pro.
Referenced by CreateModels().
void G4HadronPhysicsShieldingLEND::UnuseLEND () inline
Definition at line 61 of file G4HadronPhysicsShieldingLEND.hh.
View newest version in sPHENIX GitHub at line 61 of file G4HadronPhysicsShieldingLEND.hh
References useLEND_.
void G4HadronPhysicsShieldingLEND::UseLEND (G4String ss = "") inline
Definition at line 60 of file G4HadronPhysicsShieldingLEND.hh.
View newest version in sPHENIX GitHub at line 60 of file G4HadronPhysicsShieldingLEND.hh
References evaluation_, and useLEND_.
Member Data Documentation
G4String G4HadronPhysicsShieldingLEND::evaluation_ private
Definition at line 75 of file G4HadronPhysicsShieldingLEND.hh.
View newest version in sPHENIX GitHub at line 75 of file G4HadronPhysicsShieldingLEND.hh
Referenced by Neutron(), and UseLEND().
const G4double G4HadronPhysicsShieldingLEND::maxBertiniEnergy_ private
Definition at line 78 of file G4HadronPhysicsShieldingLEND.hh.
View newest version in sPHENIX GitHub at line 78 of file G4HadronPhysicsShieldingLEND.hh
Referenced by DumpBanner(), Kaon(), Neutron(), Pion(), and Proton().
const G4double G4HadronPhysicsShieldingLEND::minFTFPEnergy_ private
Definition at line 77 of file G4HadronPhysicsShieldingLEND.hh.
View newest version in sPHENIX GitHub at line 77 of file G4HadronPhysicsShieldingLEND.hh
Referenced by DumpBanner(), Kaon(), Neutron(), Pion(), and Proton().
const G4double G4HadronPhysicsShieldingLEND::minNonHPNeutronEnergy_ private
Definition at line 79 of file G4HadronPhysicsShieldingLEND.hh.
View newest version in sPHENIX GitHub at line 79 of file G4HadronPhysicsShieldingLEND.hh
Referenced by ExtraConfiguration(), and Neutron().
G4bool G4HadronPhysicsShieldingLEND::useLEND_ private
Definition at line 74 of file G4HadronPhysicsShieldingLEND.hh.
View newest version in sPHENIX GitHub at line 74 of file G4HadronPhysicsShieldingLEND.hh
Referenced by UnuseLEND(), and UseLEND().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/include/G4HadronPhysicsShieldingLEND.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/hadron_inelastic/src/G4HadronPhysicsShieldingLEND.cc