ECCE @ EIC Software: G4AttValue Class Reference
G4AttValue Class Reference
#include <geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4AttValue.hh>
Public Member Functions
G4AttValue (const G4String &name, const G4String &value, const G4String &showLabel)
G4AttValue ()
const G4String & GetName () const
const G4String & GetValue () const
const G4String & GetShowLabel () const
void SetName (const G4String &name)
void SetValue (const G4String &val)
void SetShowLabel (const G4String &lab)
Private Attributes
G4String m_name
The name of the attribute.
G4String m_value
The value of the attribute.
G4String m_showLabel
The bitmap for the label display.
Detailed Description
Definition at line 52 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 52 of file G4AttValue.hh
Constructor & Destructor Documentation
G4AttValue::G4AttValue (const G4String & name, const G4String & value, const G4String & showLabel) inline
Definition at line 55 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 55 of file G4AttValue.hh
G4AttValue::G4AttValue () inline
Definition at line 60 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 60 of file G4AttValue.hh
Member Function Documentation
const G4String& G4AttValue::GetName (void) const inline
Definition at line 62 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 62 of file G4AttValue.hh
References m_name.
const G4String& G4AttValue::GetShowLabel () const inline
Definition at line 64 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 64 of file G4AttValue.hh
References m_showLabel.
const G4String& G4AttValue::GetValue () const inline
Definition at line 63 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 63 of file G4AttValue.hh
References m_value.
Referenced by G4AttValueFilterT< T, ConversionErrorPolicy >::Accept(), G4TrajectoryDrawByAttribute::Draw(), G4AttributeFilterT< T >::Evaluate(), and G4AttValueFilterT< T, ConversionErrorPolicy >::GetValidElement().
void G4AttValue::SetName (const G4String & name) inline
Definition at line 66 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 66 of file G4AttValue.hh
References m_name.
void G4AttValue::SetShowLabel (const G4String & lab) inline
Definition at line 68 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 68 of file G4AttValue.hh
References m_showLabel.
void G4AttValue::SetValue (const G4String & val) inline
Definition at line 67 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 67 of file G4AttValue.hh
References m_value.
Member Data Documentation
G4String G4AttValue::m_name private
The name of the attribute.
Definition at line 68 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 68 of file G4AttValue.hh
Referenced by GetName(), and SetName().
G4String G4AttValue::m_showLabel private
The bitmap for the label display.
Definition at line 76 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 76 of file G4AttValue.hh
Referenced by GetShowLabel(), and SetShowLabel().
G4String G4AttValue::m_value private
The value of the attribute.
Definition at line 74 of file G4AttValue.hh.
View newest version in sPHENIX GitHub at line 74 of file G4AttValue.hh
Referenced by GetValue(), and SetValue().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/graphics_reps/include/G4AttValue.hh