ECCE @ EIC Software: G4Track Class Reference
G4Track Class Reference
#include <geant4/tree/geant4-10.6-release/source/track/include/G4Track.hh>
Public Member Functions
G4Track ()
G4Track (G4DynamicParticle *apValueDynamicParticle, G4double aValueTime, const G4ThreeVector &aValuePosition)
G4Track (const G4Track &)
~G4Track ()
void * operator new (size_t)
void operator delete (void *aTrack)
G4bool operator== (const G4Track &)
void CopyTrackInfo (const G4Track &)
G4int GetTrackID () const
void SetTrackID (const G4int aValue)
G4int GetParentID () const
void SetParentID (const G4int aValue)
const G4DynamicParticle * GetDynamicParticle () const
const G4ParticleDefinition * GetParticleDefinition () const
G4ParticleDefinition * GetDefinition () const
const G4ThreeVector & GetPosition () const
void SetPosition (const G4ThreeVector &aValue)
G4double GetGlobalTime () const
void SetGlobalTime (const G4double aValue)
G4double GetLocalTime () const
void SetLocalTime (const G4double aValue)
G4double GetProperTime () const
void SetProperTime (const G4double aValue)
G4VPhysicalVolume * GetVolume () const
G4VPhysicalVolume * GetNextVolume () const
G4Material * GetMaterial () const
G4Material * GetNextMaterial () const
const G4MaterialCutsCouple * GetMaterialCutsCouple () const
const G4MaterialCutsCouple * GetNextMaterialCutsCouple () const
const G4VTouchable * GetTouchable () const
const G4TouchableHandle & GetTouchableHandle () const
void SetTouchableHandle (const G4TouchableHandle &apValue)
const G4VTouchable * GetNextTouchable () const
const G4TouchableHandle & GetNextTouchableHandle () const
void SetNextTouchableHandle (const G4TouchableHandle &apValue)
const G4VTouchable * GetOriginTouchable () const
const G4TouchableHandle & GetOriginTouchableHandle () const
void SetOriginTouchableHandle (const G4TouchableHandle &apValue)
G4double GetKineticEnergy () const
void SetKineticEnergy (const G4double aValue)
G4double GetTotalEnergy () const
const G4ThreeVector & GetMomentumDirection () const
void SetMomentumDirection (const G4ThreeVector &aValue)
G4ThreeVector GetMomentum () const
G4double GetVelocity () const
void SetVelocity (G4double val)
G4double CalculateVelocity () const
G4double CalculateVelocityForOpticalPhoton () const
G4bool UseGivenVelocity () const
void UseGivenVelocity (G4bool val)
const G4ThreeVector & GetPolarization () const
void SetPolarization (const G4ThreeVector &aValue)
G4TrackStatus GetTrackStatus () const
void SetTrackStatus (const G4TrackStatus aTrackStatus)
G4bool IsBelowThreshold () const
void SetBelowThresholdFlag (G4bool value=true)
G4bool IsGoodForTracking () const
void SetGoodForTrackingFlag (G4bool value=true)
G4double GetTrackLength () const
void AddTrackLength (const G4double aValue)
const G4Step * GetStep () const
void SetStep (const G4Step *aValue)
G4int GetCurrentStepNumber () const
void IncrementCurrentStepNumber ()
G4double GetStepLength () const
void SetStepLength (G4double value)
const G4ThreeVector & GetVertexPosition () const
void SetVertexPosition (const G4ThreeVector &aValue)
const G4ThreeVector & GetVertexMomentumDirection () const
void SetVertexMomentumDirection (const G4ThreeVector &aValue)
G4double GetVertexKineticEnergy () const
void SetVertexKineticEnergy (const G4double aValue)
const G4LogicalVolume * GetLogicalVolumeAtVertex () const
void SetLogicalVolumeAtVertex (const G4LogicalVolume *)
const G4VProcess * GetCreatorProcess () const
void SetCreatorProcess (const G4VProcess *aValue)
void SetCreatorModelIndex (G4int idx)
const G4String & GetCreatorModelName () const
G4int GetCreatorModelID () const
G4double GetWeight () const
void SetWeight (G4double aValue)
G4VUserTrackInformation * GetUserInformation () const
void SetUserInformation (G4VUserTrackInformation *aValue) const
void SetAuxiliaryTrackInformation (G4int idx, G4VAuxiliaryTrackInformation *info) const
G4VAuxiliaryTrackInformation * GetAuxiliaryTrackInformation (G4int idx) const
std::map< G4int,
G4VAuxiliaryTrackInformation * > * GetAuxiliaryTrackInformationMap () const
void RemoveAuxiliaryTrackInformation (G4int idx)
void RemoveAuxiliaryTrackInformation (G4String &name)
Static Public Member Functions
static void SetVelocityTableProperties (G4double t_max, G4double t_min, G4int nbin)
static G4double GetMaxTOfVelocityTable ()
static G4double GetMinTOfVelocityTable ()
static G4int GetNbinOfVelocityTable ()
Private Member Functions
G4Track & operator= (const G4Track &)
void ClearAuxiliaryTrackInformation ()
Static Private Member Functions
static G4VelocityTable *& velTable ()
Private Attributes
G4int fCurrentStepNumber
G4ThreeVector fPosition
G4double fGlobalTime
G4double fLocalTime
G4double fTrackLength
G4int fParentID
G4int fTrackID
G4double fVelocity
G4TouchableHandle fpTouchable
G4TouchableHandle fpNextTouchable
G4TouchableHandle fpOriginTouchable
G4DynamicParticle * fpDynamicParticle
G4TrackStatus fTrackStatus
G4bool fBelowThreshold
G4bool fGoodForTracking
G4double fStepLength
G4double fWeight
const G4Step * fpStep
G4ThreeVector fVtxPosition
G4ThreeVector fVtxMomentumDirection
G4double fVtxKineticEnergy
const G4LogicalVolume * fpLVAtVertex
const G4VProcess * fpCreatorProcess
G4int fCreatorModelIndex
G4VUserTrackInformation * fpUserInformation
G4Material * prev_mat
G4MaterialPropertyVector * groupvel
G4double prev_velocity
G4double prev_momentum
G4bool is_OpticalPhoton
G4bool useGivenVelocity
std::map< G4int,
G4VAuxiliaryTrackInformation * > * fpAuxiliaryTrackInformationMap
Detailed Description
Definition at line 76 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 76 of file G4Track.hh
Constructor & Destructor Documentation
G4Track::G4Track ()
Definition at line 105 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 105 of file G4Track.cc
G4Track::G4Track (G4DynamicParticle * apValueDynamicParticle, G4double aValueTime, const G4ThreeVector & aValuePosition)
Definition at line 64 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 64 of file G4Track.cc
References CalculateVelocity(), G4ParticleTable::FindParticle(), fpDynamicParticle, fVelocity, G4ThreadLocal, G4DynamicParticle::GetDefinition(), G4ParticleTable::GetParticleTable(), G4VelocityTable::GetVelocityTable(), is_OpticalPhoton, and velTable().
G4Track::G4Track (const G4Track & right)
Definition at line 130 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 130 of file G4Track.cc
References right.
G4Track::~G4Track ()
Definition at line 156 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 156 of file G4Track.cc
References ClearAuxiliaryTrackInformation(), fpDynamicParticle, and fpUserInformation.
Member Function Documentation
void G4Track::AddTrackLength (const G4double aValue)
Referenced by G4SteppingManager::Stepping().
G4double G4Track::CalculateVelocity () const
Definition at line 234 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 234 of file G4Track.cc
References source.hepunit::c_light, CalculateVelocityForOpticalPhoton(), DBL_MIN, fpDynamicParticle, fVelocity, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetMass(), GetMaxTOfVelocityTable(), GetMinTOfVelocityTable(), is_OpticalPhoton, mass, T, useGivenVelocity, G4VelocityTable::Value(), and velTable().
Referenced by G4ITTransportation::ComputeStep(), G4Track(), G4ParallelWorldProcess::StartTracking(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAtRest(), G4ParticleChangeForGamma::UpdateStepForPostStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and G4ParticleChange::UpdateStepForPostStep().
G4double G4Track::CalculateVelocityForOpticalPhoton () const
Definition at line 267 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 267 of file G4Track.cc
References source.hepunit::c_light, fpDynamicParticle, fpStep, fpTouchable, G4VPhysicalVolume::GetLogicalVolume(), GetMaterial(), G4LogicalVolume::GetMaterial(), G4Material::GetMaterialPropertiesTable(), G4MaterialPropertiesTable::GetProperty(), G4DynamicParticle::GetTotalMomentum(), G4VTouchable::GetVolume(), groupvel, mat, prev_mat, prev_momentum, prev_velocity, and G4PhysicsVector::Value().
Referenced by G4ITTransportation::AlongStepDoIt(), and CalculateVelocity().
void G4Track::ClearAuxiliaryTrackInformation () private
Definition at line 383 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 383 of file G4Track.cc
References fpAuxiliaryTrackInformationMap.
Referenced by operator=(), and ~G4Track().
void G4Track::CopyTrackInfo (const G4Track & right)
Definition at line 227 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 227 of file G4Track.cc
References right.
G4VAuxiliaryTrackInformation * G4Track::GetAuxiliaryTrackInformation (G4int idx) const
Definition at line 352 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 352 of file G4Track.cc
References incremental_prev_tag::idx.
Referenced by G4Channeling::GetTrackData(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), and G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
std::map<G4int,G4VAuxiliaryTrackInformation*>* G4Track::GetAuxiliaryTrackInformationMap () const inline
Definition at line 338 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 338 of file G4Track.hh
References fpAuxiliaryTrackInformationMap.
G4int G4Track::GetCreatorModelID () const inline
Referenced by G4RichTrajectory::G4RichTrajectory().
const G4String& G4Track::GetCreatorModelName () const inline
Referenced by G4ExceptionHandler::DumpTrackInfo().
const G4VProcess* G4Track::GetCreatorProcess () const
Referenced by XrayFluoAnalysisManager::analyseStepping(), G4EicDircStackingAction::ClassifyNewTrack(), LXeStackingAction::ClassifyNewTrack(), OpNoviceStackingAction::ClassifyNewTrack(), G4StackChecker::ClassifyNewTrack(), CCaloSD::createNewHit(), G4ExceptionHandler::DumpTrackInfo(), export_G4Track(), G4RichTrajectory::G4RichTrajectory(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), LXeTrackingAction::PostUserTrackingAction(), CexmcTrackingAction::PreUserTrackingAction(), STCyclotronSensitiveTarget::ProcessHits(), G4StackManager::PushOneTrack(), HistoManager::ScoreNewTrack(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
G4int G4Track::GetCurrentStepNumber () const
Referenced by G4CoupledTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4WeightCutOffProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess::AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::AlongStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::AlongStepGetPhysicalInteractionLength(), XrayFluoAnalysisManager::analyseStepping(), G4RichTrajectory::AppendStep(), G4DNABrownianTransportation::Diffusion(), Par02FastSimModelTracker::DoIt(), export_G4Track(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), STCyclotronSensitiveTarget::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSMinKinEAtGeneration::ProcessHits(), G4PSNofSecondary::ProcessHits(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), G4TransportationLogger::ReportLoopingTrack(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), RE01SteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
G4ParticleDefinition* G4Track::GetDefinition () const
Referenced by G4SDParticleFilter::Accept(), HistoManager::AddLeakingParticle(), PHG4TruthTrackingAction::AddParticle(), Run::AddSecondaryTrack(), HistoManager::AddTargetStep(), G4VAtomDeexcitation::AlongStepDeexcitation(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4FastSimulationManager::AtRestGetFastSimulationManagerTrigger(), SteppingAction::BirksAttenuation(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), GFlashShowerModel::CheckParticleDefAndContainment(), G4VParticleChange::CheckSecondary(), G4EicDircStackingAction::ClassifyNewTrack(), F04StackingAction::ClassifyNewTrack(), XPhononStackingAction::ClassifyNewTrack(), LXeStackingAction::ClassifyNewTrack(), StackingAction::ClassifyNewTrack(), B3StackingAction::ClassifyNewTrack(), ExN04StackingAction::ClassifyNewTrack(), OpNoviceStackingAction::ClassifyNewTrack(), CCalStackingAction::ClassifyNewTrack(), WLSStackingAction::ClassifyNewTrack(), RE05StackingAction::ClassifyNewTrack(), G4StackChecker::ClassifyNewTrack(), DMXStackingAction::ClassifyNewTrack(), CCaloSD::createNewHit(), G4ITStepProcessor::DealWithSecondaries(), G4ScreenedCoulombClassicalKinematics::DoCollisionStep(), GFlashShowerModel::DoIt(), Par01EMShowerModel::Explode(), export_G4Track(), F04Trajectory::F04Trajectory(), G4MuonicAtomDecay::FillResult(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), G4VTransitionRadiation::GetMeanFreePath(), G4VAdjointReverseReaction::GetMeanFreePath(), G4ITStepProcessor::GetProcessInfo(), G4SteppingManager::GetProcessNumber(), CCaloSD::getStepInfo(), G4Pythia6Decayer::ImportDecayProducts(), G4ErrorPropagator::InitG4Track(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), LXeTrajectory::LXeTrajectory(), GFlashShowerModel::ModelTrigger(), RE06SteppingVerbose::NewStep(), G4hImpactIonisation::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), G4FastSimulationManager::PostStepGetFastSimulationManagerTrigger(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), F04TrackingAction::PostUserTrackingAction(), LXeTrackingAction::PostUserTrackingAction(), TrackingAction::PostUserTrackingAction(), MCTruthTrackingAction::PostUserTrackingAction(), CexmcTrackingAction::PreUserTrackingAction(), ScreenSD::ProcessHits(), STCyclotronSensitiveTarget::ProcessHits(), eRositaTrackerSD::ProcessHits(), B5DriftChamberSD::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), B4cCalorimeterSD::ProcessHits(), DMXScintSD::ProcessHits(), UltraPMTSD::ProcessHits(), G4PSNofSecondary::ProcessHits(), RMC01SD::ProcessHits(), WLSPhotonDetSD::ProcessHits_constStep(), LXePMTSD::ProcessHits_constStep(), G4TrackingManager::ProcessOneTrack(), G4ErrorPropagator::Propagate(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), GB05BOptrSplitAndKillByCrossSection::ProposeNonPhysicsBiasingOperation(), GB06BOptrSplitAndKillByImportance::ProposeNonPhysicsBiasingOperation(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), RE01TrackInformation::RE01TrackInformation(), RE01Trajectory::RE01Trajectory(), RE04Trajectory::RE04Trajectory(), HistoManager::ScoreNewTrack(), RE01TrackInformation::SetSourceTrackInformation(), G4DecayWithSpin::Spin_Precession(), G4EnergySplitter::SplitEnergyInVolumes(), GB07BOptrLeadingParticle::StartTracking(), G4ITTrackingManager::StartTracking(), G4VEnergyLossProcess::StartTracking(), F04SteppingVerbose::StepInfo(), G4ITTrackingInteractivity::TrackBanner(), G4VITSteppingVerbose::TrackBanner(), G4TrackingManager::TrackBanner(), G4ITSteppingVerbose::TrackingEnded(), F04SteppingVerbose::TrackingStarted(), MCTruthTrackingAction::TrackToBeStored(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), ExN04SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), PHG4RICHSteppingAction::UserSteppingAction(), B4bSteppingAction::UserSteppingAction(), B4aSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), DMXSteppingAction::UserSteppingAction(), G4AdjointSteppingAction::UserSteppingAction(), and WLSTrajectory::WLSTrajectory().
const G4DynamicParticle* G4Track::GetDynamicParticle () const
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4Transportation::AlongStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4AdjointAlongStepWeightCorrection::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4VContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), XrayFluoAnalysisManager::analyseStepping(), G4EmBiasingManager::ApplyDirectionalSplitting(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4EmBiasingManager::ApplySplitting(), G4DecayWithSpin::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4AdjointProcessEquivalentToDirectProcess::AtRestDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::AtRestGetPhysicalInteractionLength(), G4Decay::AtRestGetPhysicalInteractionLength(), G4BetheBlochIonGasModel::ChargeSquareRatio(), G4BraggIonGasModel::ChargeSquareRatio(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4ITTransportation::ComputeStep(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4FieldTrackUpdator::CreateFieldTrack(), G4PionDecayMakeSpin::DaughterPolarization(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4ScreenedCoulombClassicalKinematics::DoCollisionStep(), G4SingleScatter::DoCollisionStep(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelTracker::DoIt(), export_G4Track(), G4ErrorEnergyLoss::GetContinuousStepLimit(), G4hImpactIonisation::GetContinuousStepLimit(), G4OpMieHG::GetMeanFreePath(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4SynchrotronRadiation::GetMeanFreePath(), G4LowEnergyRayleigh::GetMeanFreePath(), G4LowEnergyCompton::GetMeanFreePath(), G4OpAbsorption::GetMeanFreePath(), G4LowEnergyGammaConversion::GetMeanFreePath(), G4OpRayleigh::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4OpWLS::GetMeanFreePath(), G4GammaConversionToMuons::GetMeanFreePath(), G4AnnihiToMuPair::GetMeanFreePath(), G4hImpactIonisation::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4LowEnergyPolarizedCompton::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanFreePath(), G4LowEnergyPhotoElectric::GetMeanFreePath(), G4HadronicProcess::GetMeanFreePath(), G4Decay::GetMeanFreePath(), G4RadioactiveDecayBase::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4RadioactiveDecay::GetMeanFreePath(), G4MuonicAtomDecay::GetMeanLifeTime(), G4Decay::GetMeanLifeTime(), G4RadioactiveDecayBase::GetMeanLifeTime(), G4RadioactiveDecay::GetMeanLifeTime(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4Scintillation::GetScintillationYieldByParticleType(), G4Pythia6Decayer::ImportDecayProducts(), G4HadProjectile::Initialise(), G4ParticleChangeForDecay::Initialize(), G4ParticleChange::Initialize(), G4FastStep::Initialize(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4VEmProcess::MeanFreePath(), G4VEnergyLossProcess::MeanFreePath(), G4DNARuddIonisationModel::PartialCrossSection(), G4DNARuddIonisationExtendedModel::PartialCrossSection(), G4SmartTrackStack::PopFromStack(), G4HadronElasticProcess::PostStepDoIt(), G4DecayWithSpin::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4OpAbsorption::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), XrayTelStepCut::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4UnknownDecay::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), Par02TrackingAction::PostUserTrackingAction(), PHG4TruthTrackingAction::PreUserTrackingAction(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4SmartTrackStack::PushToStack(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), RE01Trajectory::RE01Trajectory(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4GammaGeneralProcess::SampleSecondaries(), G4VEnergyLossProcess::SampleSubCutSecondaries(), Run::ScoreNewTrack(), HistoManager::ScoreNewTrack(), G4SteppingManager::SetInitialStep(), G4UrbanMscModel::StartTracking(), G4UrbanAdjointMscModel::StartTracking(), G4AdjointProcessEquivalentToDirectProcess::StartTracking(), G4GoudsmitSaundersonMscModel::StartTracking(), G4FieldTrackUpdator::Update(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), OpNoviceSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), and PurgMagSteppingAction::UserSteppingAction().
G4double G4Track::GetGlobalTime () const
Referenced by G4ITTrackHolder::_PushTrack(), G4ParticleChangeForGamma::AddSecondary(), PHG4TruthTrackingAction::AddVertex(), G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DecayWithSpin::AtRestDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), G4ParticleChange::CheckIt(), G4FastStep::CheckIt(), G4VParticleChange::CheckSecondary(), CCalStackingAction::ClassifyNewTrack(), G4StackChecker::ClassifyNewTrack(), G4ITStepProcessor::ComputeInteractionLength(), G4ITTransportation::ComputeStep(), G4ITModelProcessor::ComputeTrackReaction(), G4FieldTrackUpdator::CreateFieldTrack(), G4VPhononProcess::CreateSecondary(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4DNAMolecularDissociation::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4DNABrownianTransportation::Diffusion(), Par01PiModel::DoIt(), export_G4Track(), F04TrajectoryPoint::F04TrajectoryPoint(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4ParticleChangeForDecay::Initialize(), G4ParticleChange::Initialize(), G4FastStep::Initialize(), G4DNAMolecularReaction::MakeReaction(), G4DNAElectronHoleRecombination::MakeReaction(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4DNASecondOrderReaction::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4DNABrownianTransportation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4NeutronKiller::PostStepGetPhysicalInteractionLength(), MCTruthTrackingAction::PostUserTrackingAction(), G4ITSteppingVerbose::PreStepVerbose(), G4ITTrackHolder::PushDelayed(), RE01TrackInformation::RE01TrackInformation(), RE01Trajectory::RE01Trajectory(), G4TrackingInformation::RecordCurrentPositionNTime(), RE01TrackInformation::SetSourceTrackInformation(), F05SteppingVerbose::StepInfo(), F05SteppingVerbose::TrackingStarted(), G4FieldTrackUpdator::Update(), G4FastStep::UpdateStepForAtRest(), G4FastStep::UpdateStepForPostStep(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), F05SteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), G4SteppingVerbose::VerboseTrack(), WLSTrajectoryPoint::WLSTrajectoryPoint(), and G4Molecule::~G4Molecule().
G4double G4Track::GetKineticEnergy () const
Referenced by HistoManager::AddTargetStep(), G4ErrorEnergyLoss::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4VMultipleScattering::AlongStepGetPhysicalInteractionLength(), XrayTelAnalysis::analyseStepping(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4VEmModel::ChargeSquareRatio(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), G4FastStep::CheckIt(), G4VParticleChange::CheckSecondary(), StackingAction::ClassifyNewTrack(), CCalStackingAction::ClassifyNewTrack(), G4StackChecker::ClassifyNewTrack(), G4FieldTrackUpdator::CreateFieldTrack(), G4PhysChemIO::FormattedText::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4ITStepProcessor::DealWithSecondaries(), Par01PionShowerModel::DoIt(), Par01EMShowerModel::DoIt(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4ExceptionHandler::DumpTrackInfo(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01EMShowerModel::Explode(), export_G4Track(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4RichTrajectory::G4RichTrajectory(), G4RichTrajectoryPoint::G4RichTrajectoryPoint(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), G4ErrorEnergyLoss::GetContinuousStepLimit(), G4AdjointAlongStepWeightCorrection::GetContinuousStepLimit(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4PhononScattering::GetMeanFreePath(), G4PhononDownconversion::GetMeanFreePath(), G4VTransitionRadiation::GetMeanFreePath(), G4VAdjointReverseReaction::GetMeanFreePath(), G4LowEnergyIonisation::GetMeanFreePath(), G4LowEnergyBremsstrahlung::GetMeanFreePath(), G4Scintillation::GetScintillationYieldByParticleType(), G4ErrorPropagator::InitG4Track(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4UCNBoundaryProcess::InvokeSD(), G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), G4VEmProcess::MeanFreePath(), G4VEnergyLossProcess::MeanFreePath(), Par01EMShowerModel::ModelTrigger(), GFlashShowerModel::ModelTrigger(), G4PhononScattering::PostStepDoIt(), G4PhononReflection::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4UserSpecialCuts::PostStepDoIt(), G4SpecialCuts::PostStepDoIt(), DMXSpecialCuts::PostStepDoIt(), G4ElectronCapture::PostStepDoIt(), G4LowECapture::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4ElectronCapture::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4NeutronKiller::PostStepGetPhysicalInteractionLength(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), TrackingAction::PostUserTrackingAction(), UltraPMTSD::ProcessHits(), G4ErrorPropagator::Propagate(), RE04Trajectory::RE04Trajectory(), G4TransportationLogger::ReportLoopingTrack(), G4VEnergyLossProcess::SampleSubCutSecondaries(), Run::ScoreNewTrack(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), Par02Smearer::SmearEnergy(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F04SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), G4FieldTrackUpdator::Update(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), XrayTelSteppingAction::UserSteppingAction(), G4AdjointSteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
G4double G4Track::GetLocalTime () const
Referenced by G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), G4RadioactiveDecayBase::DecayAnalog(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), export_G4Track(), G4ParticleChangeForDecay::Initialize(), G4ParticleChange::Initialize(), MCTruthTrackingAction::PostUserTrackingAction(), G4TrackingInformation::RecordCurrentPositionNTime(), and G4SteppingVerbose::VerboseTrack().
const G4LogicalVolume* G4Track::GetLogicalVolumeAtVertex () const
Referenced by export_G4Track().
G4Material* G4Track::GetMaterial () const
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4VContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousProcess::AlongStepGetPhysicalInteractionLength(), XrayFluoAnalysisManager::analyseStepping(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), SteppingAction::BirksAttenuation(), CalculateVelocityForOpticalPhoton(), G4VEmModel::ChargeSquareRatio(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4DNABrownianTransportation::ComputeStep(), G4DNABrownianTransportation::Diffusion(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), export_G4Track(), G4DNAElectronHoleRecombination::FindReactant(), G4ErrorEnergyLoss::GetContinuousStepLimit(), G4OpMieHG::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4OpAbsorption::GetMeanFreePath(), G4OpRayleigh::GetMeanFreePath(), G4OpWLS::GetMeanFreePath(), G4GammaConversionToMuons::GetMeanFreePath(), G4AnnihiToMuPair::GetMeanFreePath(), G4LowEnergyPhotoElectric::GetMeanFreePath(), G4UCNAbsorption::GetMeanFreePath(), G4UCNLoss::GetMeanFreePath(), G4UCNMultiScattering::GetMeanFreePath(), G4HadronicProcess::GetMeanFreePath(), G4Scintillation::GetScintillationYieldByParticleType(), PHG4SteppingAction::GetScintLightYield(), G4HadProjectile::Initialise(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), CexmcHadronicProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), RE04Trajectory::RE04Trajectory(), G4GammaGeneralProcess::SampleSecondaries(), G4ElementSelector::SelectZandA(), RE04SteppingAction::UserSteppingAction(), and FCALSteppingAction::UserSteppingAction().
const G4MaterialCutsCouple* G4Track::GetMaterialCutsCouple () const
Referenced by G4NuclearStopping::AlongStepDoIt(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4VMultipleScattering::AlongStepDoIt(), G4VMultipleScattering::AlongStepGetPhysicalInteractionLength(), G4EmBiasingManager::ApplyDirectionalSplitting(), G4EmBiasingManager::ApplyRangeCut(), G4EmBiasingManager::ApplySplitting(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4AdjointAlongStepWeightCorrection::GetContinuousStepLimit(), G4ContinuousGainOfEnergy::GetContinuousStepLimit(), G4hImpactIonisation::GetContinuousStepLimit(), G4LowEnergyRayleigh::GetMeanFreePath(), G4LowEnergyCompton::GetMeanFreePath(), G4LowEnergyGammaConversion::GetMeanFreePath(), G4hImpactIonisation::GetMeanFreePath(), G4VAdjointReverseReaction::GetMeanFreePath(), G4LowEnergyIonisation::GetMeanFreePath(), G4LowEnergyPolarizedCompton::GetMeanFreePath(), G4LowEnergyBremsstrahlung::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetMeanFreePath(), G4VEmProcess::MeanFreePath(), G4VEnergyLossProcess::MeanFreePath(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4ScreenedNuclearRecoil::PostStepDoIt(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4Cerenkov::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4VEnergyLossProcess::SampleSubCutSecondaries(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
G4double G4Track::GetMaxTOfVelocityTable () static
Definition at line 321 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 321 of file G4Track.cc
References G4VelocityTable::GetMaxTOfVelocityTable().
Referenced by CalculateVelocity().
G4double G4Track::GetMinTOfVelocityTable () static
Definition at line 326 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 326 of file G4Track.cc
References G4VelocityTable::GetMinTOfVelocityTable().
Referenced by CalculateVelocity().
G4ThreeVector G4Track::GetMomentum () const
Referenced by G4HadronicProcess::CheckEnergyMomentumConservation(), G4EicDircStackingAction::ClassifyNewTrack(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelTracker::DoIt(), export_G4Track(), F04Trajectory::F04Trajectory(), F04TrajectoryPoint::F04TrajectoryPoint(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), G4Pythia6Decayer::ImportDecayProducts(), G4BOptnForceCommonTruncatedExp::Initialize(), Par01PiModel::ModelTrigger(), G4AdjointForcedInteractionForGamma::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), Par02TrackingAction::PreUserTrackingAction(), MCTruthTrackingAction::PreUserTrackingAction(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), RE01TrackInformation::RE01TrackInformation(), RE01Trajectory::RE01Trajectory(), RE04Trajectory::RE04Trajectory(), G4TransportationLogger::ReportLoopingTrack(), G4FastTrack::SetCurrentTrack(), RE01TrackInformation::SetSourceTrackInformation(), Par02Smearer::SmearGaussian(), G4FieldTrackUpdator::Update(), G4ErrorFreeTrajParam::Update(), G4ErrorFreeTrajState::Update(), EICG4dRICHSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), G4AdjointSteppingAction::UserSteppingAction(), WLSTrajectory::WLSTrajectory(), and WLSTrajectoryPoint::WLSTrajectoryPoint().
const G4ThreeVector& G4Track::GetMomentumDirection () const
Referenced by G4DNABrownianTransportation::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), XrayTelAnalysis::analyseStepping(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4VParticleChange::CheckSecondary(), G4StackChecker::ClassifyNewTrack(), G4VMscModel::ComputeGeomLimit(), G4DNABrownianTransportation::ComputeGeomLimit(), G4DNABrownianTransportation::ComputeStep(), G4FieldTrackUpdator::CreateFieldTrack(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4ExceptionHandler::DumpTrackInfo(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01EMShowerModel::Explode(), export_G4Track(), G4HadronicProcess::FillResult(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), G4VGFlashSensitiveDetector::Hit(), G4BOptnForceCommonTruncatedExp::Initialize(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4PhononReflection::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), F04TrackingAction::PreUserTrackingAction(), WLSTrackingAction::PreUserTrackingAction(), CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget(), Run::ScoreNewTrack(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), G4SamplingPostStepAction::Split(), G4VPhononProcess::StartTracking(), G4WeightCutOffProcess::StartTracking(), G4ImportanceProcess::StartTracking(), G4WeightWindowProcess::StartTracking(), G4ParallelWorldScoringProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), G4FastSimulationManagerProcess::StartTracking(), G4ParallelGeometriesLimiterProcess::StartTracking(), G4CoupledTransportation::StartTracking(), F05SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F05SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), G4FieldTrackUpdator::Update(), EICG4dRICHSteppingAction::UserSteppingAction(), F05SteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), and G4SteppingVerbose::VerboseTrack().
G4int G4Track::GetNbinOfVelocityTable () static
Definition at line 331 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 331 of file G4Track.cc
References G4VelocityTable::GetNbinOfVelocityTable().
G4Material* G4Track::GetNextMaterial () const
const G4MaterialCutsCouple* G4Track::GetNextMaterialCutsCouple () const
const G4VTouchable* G4Track::GetNextTouchable () const
const G4TouchableHandle& G4Track::GetNextTouchableHandle () const
Referenced by G4RichTrajectory::AppendStep(), G4RichTrajectory::G4RichTrajectory(), G4ITStepProcessor::InitDefineStep(), G4ScoreSplittingProcess::PostStepDoIt(), G4ITSteppingVerbose::PostStepVerbose(), G4ITSteppingVerbose::PreStepVerbose(), and G4SteppingManager::Stepping().
G4VPhysicalVolume* G4Track::GetNextVolume () const
Referenced by XrayFluoAnalysisManager::analyseStepping(), G4ErrorPropagator::CheckIfLastStep(), G4ITStepProcessor::DoDefinePhysicalStepLength(), G4Channeling::GetMeanFreePath(), G4SteppingManager::InvokePostStepDoItProcs(), G4Channeling::PostStepDoIt(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), G4ErrorGeomVolumeTarget::TargetReached(), G4ITSteppingVerbose::TrackingEnded(), F04SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), FCALSteppingAction::UserSteppingAction(), XrayFluoSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), XrayTelSteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
const G4VTouchable* G4Track::GetOriginTouchable () const
const G4TouchableHandle& G4Track::GetOriginTouchableHandle () const
G4int G4Track::GetParentID () const
Referenced by PHG4TruthTrackingAction::AddParticle(), PHG4TruthTrackingAction::AddVertex(), XrayFluoAnalysisManager::analyseStepping(), G4EicDircStackingAction::ClassifyNewTrack(), F04StackingAction::ClassifyNewTrack(), XPhononStackingAction::ClassifyNewTrack(), LXeStackingAction::ClassifyNewTrack(), B3StackingAction::ClassifyNewTrack(), StackingAction::ClassifyNewTrack(), RE01StackingAction::ClassifyNewTrack(), OpNoviceStackingAction::ClassifyNewTrack(), ExN04StackingAction::ClassifyNewTrack(), WLSStackingAction::ClassifyNewTrack(), CCalStackingAction::ClassifyNewTrack(), RE05StackingAction::ClassifyNewTrack(), G4StackChecker::ClassifyNewTrack(), CCaloSD::createNewHit(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelTracker::DoIt(), G4EventManager::DoProcessing(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4ExceptionHandler::DumpTrackInfo(), export_G4Track(), F04Trajectory::F04Trajectory(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), G4Scintillation::GetScintillationYieldByParticleType(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4StackManager::PopNextTrack(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), MCTruthTrackingAction::PostUserTrackingAction(), Par02TrackingAction::PostUserTrackingAction(), PHG4TruthTrackingAction::PreUserTrackingAction(), RE05TrackingAction::PreUserTrackingAction(), CML2TrackingAction::PreUserTrackingAction(), CexmcTrackingAction::PreUserTrackingAction(), STCyclotronSensitiveTarget::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSMinKinEAtGeneration::ProcessHits(), TrackerSD::ProcessHits(), G4PSNofSecondary::ProcessHits(), GB04BOptrBremSplitting::ProposeFinalStateBiasingOperation(), GB01BOptrMultiParticleChangeCrossSection::ProposeOccurenceBiasingOperation(), G4StackManager::PushOneTrack(), G4SmartTrackStack::PushToStack(), RE01Trajectory::RE01Trajectory(), RE04Trajectory::RE04Trajectory(), Run::ScoreNewTrack(), HistoManager::ScoreNewTrack(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), G4VEmProcess::StartTracking(), G4VEnergyLossProcess::StartTracking(), G4ITTrackingInteractivity::TrackBanner(), G4VITSteppingVerbose::TrackBanner(), G4TrackingManager::TrackBanner(), F04SteppingVerbose::TrackingStarted(), PHG4TruthTrackingAction::UpdateG4ParticleStack(), PHG4InttSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), ExN04SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), G4SteppingVerbose::VerboseTrack(), and WLSTrajectory::WLSTrajectory().
const G4ParticleDefinition* G4Track::GetParticleDefinition () const
Referenced by G4NuclearStopping::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4VEnergyLossProcess::AlongStepDoIt(), G4VMultipleScattering::AlongStepGetPhysicalInteractionLength(), BiasingOperation::ApplyFinalStateBiasing(), G4VEmModel::ChargeSquareRatio(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4AdjointStackingAction::ClassifyNewTrack(), G4NIELCalculator::ComputeNIEL(), G4ITModelProcessor::ComputeTrackReaction(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4ExceptionHandler::DumpTrackInfo(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4Channeling::GetParticleDefinition(), G4VPhononProcess::GetPolarization(), G4Scintillation::GetScintillationYieldByParticleType(), G4ElectronIonPair::MeanNumberOfIonsAlongStep(), G4AdjointTrackingAction::PreUserTrackingAction(), G4StackManager::PushOneTrack(), G4TransportationLogger::ReportLoopingTrack(), G4ElectronIonPair::ResidualeChargePostStep(), G4VEnergyLossProcess::SampleSubCutSecondaries(), Run::ScoreNewTrack(), G4WentzelVIModel::StartTracking(), GB02BOptrMultiParticleForceCollision::StartTracking(), G4ChannelingOptrMultiParticleChangeCrossSection::StartTracking(), GB01BOptrMultiParticleChangeCrossSection::StartTracking(), G4VEmProcess::StartTracking(), G4VMultipleScattering::StartTracking(), G4ParticleChangeForGamma::UpdateStepForPostStep(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), and G4EmSaturation::VisibleEnergyDepositionAtAStep().
const G4ThreeVector& G4Track::GetPolarization () const
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), export_G4Track(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4FastTrack::SetCurrentTrack(), F05SteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
const G4ThreeVector& G4Track::GetPosition () const
Referenced by G4ParticleChangeForGamma::AddSecondary(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), XrayTelAnalysis::analyseStepping(), G4EmBiasingManager::ApplyDirectionalSplitting(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4Molecule::BuildTrack(), G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), G4VParticleChange::CheckSecondary(), G4StackChecker::ClassifyNewTrack(), DMXStackingAction::ClassifyNewTrack(), G4ITTransportation::ComputeStep(), G4DNABrownianTransportation::ComputeStep(), G4FieldTrackUpdator::CreateFieldTrack(), G4VPhononProcess::CreateSecondary(), G4PhysChemIO::FormattedText::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4DNAChemistryManager::CreateSolvatedElectron(), G4PhysChemIO::FormattedText::CreateWaterMolecule(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), G4DNAChemistryManager::CreateWaterMolecule(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4DNAMolecularDissociation::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelHCal::DoIt(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), GFlashShowerModel::ElectronDoIt(), Par01EMShowerModel::Explode(), export_G4Track(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4DNAElectronHoleRecombination::FindReactant(), G4DNASmoluchowskiReactionModel::FindReaction(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4GFlashSpot::GetPosition(), G4IT::GetPosition(), G4BOptnForceCommonTruncatedExp::Initialize(), G4ParticleChange::Initialize(), G4FastStep::Initialize(), RE05StackingAction::InsideRoI(), ExN04StackingAction::InsideRoI(), G4DNAMolecularReaction::MakeReaction(), G4DNAElectronHoleRecombination::MakeReaction(), Par01PiModel::ModelTrigger(), G4IT::operator[](), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4DNASecondOrderReaction::PostStepDoIt(), G4Transportation::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), G4ITSteppingVerbose::PostStepVerbose(), TrackingAction::PostUserTrackingAction(), MCTruthTrackingAction::PostUserTrackingAction(), G4ITSteppingVerbose::PreStepVerbose(), STCyclotronSensitiveTarget::ProcessHits(), G4ErrorFreeTrajState::PropagateError(), RE01TrackInformation::RE01TrackInformation(), RE01Trajectory::RE01Trajectory(), RE04Trajectory::RE04Trajectory(), G4TrackingInformation::RecordCurrentPositionNTime(), G4TransportationLogger::ReportLoopingTrack(), CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget(), G4TDNAOneStepThermalizationModel< MODEL >::SampleSecondaries(), G4FastTrack::SetCurrentTrack(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), RE01TrackInformation::SetSourceTrackInformation(), Par02Smearer::SmearGaussian(), G4WeightCutOffProcess::StartTracking(), G4ImportanceProcess::StartTracking(), G4WeightWindowProcess::StartTracking(), G4ParallelWorldScoringProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), G4FastSimulationManagerProcess::StartTracking(), G4ParallelGeometriesLimiterProcess::StartTracking(), G4CoupledTransportation::StartTracking(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), G4FieldTrackUpdator::Update(), G4ErrorFreeTrajParam::Update(), G4ErrorFreeTrajState::Update(), doiPETSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), G4SteppingVerbose::VerboseTrack(), and G4Molecule::~G4Molecule().
G4double G4Track::GetProperTime () const
Referenced by G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4Decay::AtRestGetPhysicalInteractionLength(), G4ParticleChange::CheckIt(), G4FastStep::CheckIt(), export_G4Track(), G4DNAMolecularDissociation::GetMeanLifeTime(), G4UCNAbsorption::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4UnknownDecay::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), and G4FieldTrackUpdator::Update().
const G4Step* G4Track::GetStep () const
Referenced by HistoManager::AddLeakingParticle(), G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4VMscModel::ComputeGeomLimit(), G4DNABrownianTransportation::ComputeGeomLimit(), G4ITModelProcessor::ComputeTrackReaction(), G4LowEWentzelVIModel::ComputeTruePathLengthLimit(), G4WentzelVIModel::ComputeTruePathLengthLimit(), G4UrbanMscModel::ComputeTruePathLengthLimit(), G4UrbanAdjointMscModel::ComputeTruePathLengthLimit(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), G4FastList< G4Track >::DeleteObject(), export_G4Track(), G4DNASmoluchowskiReactionModel::FindReaction(), G4MuNeutrinoNucleusProcess::GetMeanFreePath(), G4NeutrinoElectronProcess::GetMeanFreePath(), G4Channeling::GetPost(), G4Channeling::GetPre(), G4ErrorPropagator::MakeOneStep(), RE06SteppingVerbose::NewStep(), G4Channeling::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), G4ITSteppingVerbose::PostStepVerbose(), G4PSDoseDeposit::ProcessHits(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), G4ITStepProcessor::SetTrack(), G4ScoreSplittingProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), G4ITSteppingVerbose::TrackingStarted(), and G4Channeling::UpdateParameters().
G4double G4Track::GetStepLength () const
Referenced by G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4ITTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepDoIt(), export_G4Track(), G4ITStepProcessor::InitDefineStep(), G4ErrorPropagator::MakeOneStep(), G4PhononReflection::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), and G4SteppingVerbose::ShowStep().
G4double G4Track::GetTotalEnergy () const
Referenced by PHG4TruthTrackingAction::AddParticle(), G4Transportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), CCaloSD::createNewHit(), export_G4Track(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), MCTruthTrackingAction::PreUserTrackingAction(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), RE01TrackInformation::RE01TrackInformation(), and RE01TrackInformation::SetSourceTrackInformation().
const G4VTouchable* G4Track::GetTouchable () const
Referenced by CCaloSD::createNewHit(), G4DNAMolecularDissociation::DecayIt(), export_G4Track(), PHG4RICHSteppingAction::MakeHit(), G4TDNAOneStepThermalizationModel< MODEL >::SampleSecondaries(), and FCALSteppingAction::UserSteppingAction().
const G4TouchableHandle& G4Track::GetTouchableHandle () const
Referenced by G4ParticleChangeForGamma::AddSecondary(), G4ParticleChange::AddSecondary(), G4RichTrajectory::AppendStep(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4RichTrajectory::G4RichTrajectory(), G4ITStepProcessor::InitDefineStep(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4Transportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), G4ScoreSplittingProcess::StartTracking(), G4ITTransportation::StartTracking(), G4MonopoleTransportation::StartTracking(), G4Transportation::StartTracking(), and G4CoupledTransportation::StartTracking().
G4int G4Track::GetTrackID () const
Referenced by G4ITTrackHolder::_PushTrack(), Run::AddEnergy(), G4DNABrownianTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DNAMoleculeEncounterStepper::CalculateStep(), G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), G4FastList< G4Track >::CheckFlag(), CCalStackingAction::ClassifyNewTrack(), G4StackChecker::ClassifyNewTrack(), G4ITStepProcessor::ComputeInteractionLength(), G4DNABrownianTransportation::ComputeStep(), G4ITModelProcessor::ComputeTrackReaction(), CCaloSD::createNewHit(), G4PhysChemIO::FormattedText::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4DNAChemistryManager::CreateSolvatedElectron(), G4PhysChemIO::FormattedText::CreateWaterMolecule(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), G4DNAChemistryManager::CreateWaterMolecule(), G4DNAMolecularDissociation::DecayIt(), G4DNABrownianTransportation::Diffusion(), G4ITStepProcessor::DoIt(), G4EventManager::DoProcessing(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4ExceptionHandler::DumpTrackInfo(), export_G4Track(), F04Trajectory::F04Trajectory(), G4HadronicProcess::FillResult(), G4SmoothTrajectory::G4SmoothTrajectory(), G4Trajectory::G4Trajectory(), G4VAdjointReverseReaction::GetMeanFreePath(), G4Scintillation::GetScintillationYieldByParticleType(), EICG4dRICHSteppingAction::InitHit(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4PSPassageTrackLength::IsPassed(), G4PSPassageCellCurrent::IsPassed(), G4PSPassageCellFlux::IsPassed(), G4ITTrackHolder::KillTracks(), PHG4RICHSteppingAction::MakeHit(), compTrackPerID::operator()(), G4StackManager::PopNextTrack(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4DNABrownianTransportation::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4ITSteppingVerbose::PostStepVerbose(), PHG4TruthTrackingAction::PostUserTrackingAction(), MCTruthTrackingAction::PostUserTrackingAction(), G4ITSteppingVerbose::PreStepVerbose(), PHG4TruthTrackingAction::PreUserTrackingAction(), CexmcTrackingAction::PreUserTrackingAction(), ScreenSD::ProcessHits(), STCyclotronSensitiveTarget::ProcessHits(), ExTGTrackerSD::ProcessHits(), eRositaTrackerSD::ProcessHits(), RE01TrackerSD::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), ExN02TrackerSD::ProcessHits(), ExP01TrackerSD::ProcessHits(), G4PSPopulation::ProcessHits(), B2TrackerSD::ProcessHits(), TrackerSD::ProcessHits(), CheckVolumeSD::ProcessHits(), PrimaryKiller::ProcessHits(), G4StackManager::PushOneTrack(), RE01TrackInformation::RE01TrackInformation(), RE01Trajectory::RE01Trajectory(), RE04Trajectory::RE04Trajectory(), PHG4TrackUserInfo::SetKeep(), PHG4TrackUserInfo::SetShower(), RE01TrackInformation::SetSourceTrackInformation(), G4ITStepProcessor::SetTrack(), PHG4TrackUserInfo::SetUserParentId(), PHG4TrackUserInfo::SetUserPrimaryId(), PHG4TrackUserInfo::SetUserTrackId(), PHG4TrackUserInfo::SetWanted(), G4ITStepProcessor::Stepping(), G4ITTrackingInteractivity::TrackBanner(), G4VITSteppingVerbose::TrackBanner(), G4TrackingManager::TrackBanner(), G4ITSteppingVerbose::TrackingEnded(), F04SteppingVerbose::TrackingStarted(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), G4SteppingVerbose::VerboseTrack(), and WLSTrajectory::WLSTrajectory().
G4double G4Track::GetTrackLength () const
Referenced by export_G4Track(), G4ErrorTrackLengthTarget::GetMeanFreePath(), G4UCNAbsorption::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
G4TrackStatus G4Track::GetTrackStatus () const
Referenced by G4BiasingProcessInterface::AlongStepDoIt(), G4DNAMoleculeEncounterStepper::CheckAndRecordResults(), G4ErrorPropagator::CheckIfLastStep(), RE01StackingAction::ClassifyNewTrack(), ExN04StackingAction::ClassifyNewTrack(), CCalStackingAction::ClassifyNewTrack(), RE05StackingAction::ClassifyNewTrack(), G4RadioactiveDecayBase::DecayAnalog(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4RadioactiveDecay::DecayIt(), G4StackManager::DefaultClassification(), G4ITStepProcessor::DoDefinePhysicalStepLength(), G4ITStepProcessor::DoIt(), G4EventManager::DoProcessing(), ITTrackingInteractivity::EndTracking(), G4BOptrForceCollision::EndTracking(), export_G4Track(), G4ITStepProcessor::ExtractILData(), G4ITModelProcessor::FindReaction(), G4Scintillation::GetScintillationYieldByParticleType(), G4ParticleChangeForNothing::Initialize(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokePostStepDoItProcs(), G4ErrorPropagator::MakeSteps(), G4HadronElasticProcess::PostStepDoIt(), G4DecayWithSpin::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), CexmcHadronicProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4Transportation::PostStepDoIt(), G4Decay::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4MonopoleTransportation::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4ITTransportation::PostStepDoIt(), G4Scintillation::PostStepDoIt(), Par02TrackingAction::PostUserTrackingAction(), G4PSTermination::ProcessHits(), G4TrackingManager::ProcessOneTrack(), G4ITTrackHolder::PushToKill(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), G4SteppingManager::Stepping(), G4ParticleChangeForMSC::UpdateStepForAlongStep(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), ExN04SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
G4VUserTrackInformation* G4Track::GetUserInformation () const
Referenced by RE01StackingAction::ClassifyNewTrack(), GetIT(), CexmcTrackPoints::GetTrackId(), PHG4RICHSteppingAction::MakeHit(), SplitProcess::PostStepDoIt(), CexmcHadronicProcess::PostStepDoIt(), CexmcStudiedProcess::PostStepGetPhysicalInteractionLength(), PHG4TruthTrackingAction::PostUserTrackingAction(), RE01TrackingAction::PostUserTrackingAction(), F04TrackingAction::PostUserTrackingAction(), LXeTrackingAction::PostUserTrackingAction(), MCTruthTrackingAction::PostUserTrackingAction(), PHG4TruthTrackingAction::PreUserTrackingAction(), RE01TrackingAction::PreUserTrackingAction(), MCTruthTrackingAction::PreUserTrackingAction(), CexmcTrackingAction::PreUserTrackingAction(), RE01TrackerSD::ProcessHits(), LXePMTSD::ProcessHits_constStep(), WLSPhotonDetSD::ProcessHits_constStep(), RE01Trajectory::RE01Trajectory(), CexmcPhysicsList< BasePhysics, StudiedPhysics, ProductionModel >::ResampleTrackLengthInTarget(), PHG4TrackUserInfo::SetKeep(), PHG4TrackUserInfo::SetShower(), RE01CalorimeterHit::SetTrackInformation(), CexmcTrackingAction::SetupIncidentParticleTrackInfo(), PHG4TrackUserInfo::SetUserParentId(), PHG4TrackUserInfo::SetUserPrimaryId(), PHG4TrackUserInfo::SetUserTrackId(), PHG4TrackUserInfo::SetWanted(), PHG4TruthTrackingAction::UpdateG4ParticleStack(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4dRICHSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), and WLSSteppingAction::UserSteppingAction().
G4double G4Track::GetVelocity () const
Referenced by G4MonopoleTransportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::ComputeStep(), export_G4Track(), G4PhononScattering::GetMeanFreePath(), G4PhononDownconversion::GetMeanFreePath(), G4UCNAbsorption::GetMeanFreePath(), G4ParticleChange::Initialize(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), and G4Channeling::UpdateParameters().
G4double G4Track::GetVertexKineticEnergy () const
Referenced by PHG4TruthTrackingAction::AddParticle(), export_G4Track(), G4Scintillation::GetScintillationYieldByParticleType(), TrackerSD::ProcessHits(), and G4SteppingVerbose::VerboseTrack().
const G4ThreeVector& G4Track::GetVertexMomentumDirection () const
Referenced by PHG4TruthTrackingAction::AddParticle(), export_G4Track(), EICG4dRICHSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
const G4ThreeVector& G4Track::GetVertexPosition () const
Referenced by PHG4TruthTrackingAction::AddVertex(), XrayFluoAnalysisManager::analyseStepping(), export_G4Track(), MCTruthTrackingAction::PostUserTrackingAction(), Run::ScoreNewTrack(), HistoManager::ScoreNewTrack(), EICG4dRICHSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), and G4SteppingVerbose::VerboseTrack().
G4VPhysicalVolume* G4Track::GetVolume () const
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(), G4WeightCutOffProcess::AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::AlongStepGetPhysicalInteractionLength(), XrayFluoAnalysisManager::analyseStepping(), G4DecayWithSpin::AtRestDoIt(), G4FastSimulationManagerProcess::AtRestGetPhysicalInteractionLength(), G4EicDircStackingAction::ClassifyNewTrack(), XPhononStackingAction::ClassifyNewTrack(), G4DNABrownianTransportation::ComputeGeomLimit(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), Par02FastSimModelTracker::DoIt(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), export_G4Track(), F04TrajectoryPoint::F04TrajectoryPoint(), G4Channeling::GetMatData(), G4Channeling::GetMeanFreePath(), G4VTransitionRadiation::GetMeanFreePath(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4BOptnForceCommonTruncatedExp::Initialize(), G4Channeling::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), HadrontherapyStepMax::PostStepGetPhysicalInteractionLength(), G4StepLimiter::PostStepGetPhysicalInteractionLength(), DMXMinEkineCuts::PostStepGetPhysicalInteractionLength(), G4MinEkineCuts::PostStepGetPhysicalInteractionLength(), G4UserSpecialCuts::PostStepGetPhysicalInteractionLength(), DMXMaxTimeCuts::PostStepGetPhysicalInteractionLength(), G4MaxTimeCuts::PostStepGetPhysicalInteractionLength(), IORTStepMax::PostStepGetPhysicalInteractionLength(), ML2StepMax::PostStepGetPhysicalInteractionLength(), XrayTelStepCut::PostStepGetPhysicalInteractionLength(), G4ElectronCapture::PostStepGetPhysicalInteractionLength(), G4LowECapture::PostStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), TrackingAction::PostUserTrackingAction(), WLSTrackingAction::PreUserTrackingAction(), UltraPMTSD::ProcessHits(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4TransportationLogger::ReportLoopingTrack(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), Run::ScoreNewTrack(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), CexmcTrackingAction::SetupIncidentParticleTrackInfo(), G4VPhononProcess::StartTracking(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), G4Channeling::UpdateParameters(), HadrontherapySteppingAction::UserSteppingAction(), XrayTelSteppingAction::UserSteppingAction(), and WLSTrajectoryPoint::WLSTrajectoryPoint().
G4double G4Track::GetWeight () const
Referenced by HistoManager::AddTargetStep(), G4EmBiasingManager::ApplyDirectionalSplitting(), G4BOptnForceFreeFlight::ApplyFinalStateBiasing(), GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4EmBiasingManager::ApplySplitting(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), export_G4Track(), G4MuonicAtomDecay::FillResult(), CexmcHadronicProcess::FillTotalResult(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4FastStep::Initialize(), G4ParticleChangeForLoss::InitializeForAlongStep(), G4ParticleChangeForGamma::InitializeForPostStep(), G4ParticleChangeForLoss::InitializeForPostStep(), SplitProcess::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4AdjointTrackingAction::PreUserTrackingAction(), RMC01SD::ProcessHits(), G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation(), GB01BOptrMultiParticleChangeCrossSection::ProposeOccurenceBiasingOperation(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4ParticleChangeForOccurenceBiasing::StealSecondaries(), and G4AdjointSteppingAction::UserSteppingAction().
void G4Track::IncrementCurrentStepNumber ()
Referenced by G4ErrorPropagator::MakeOneStep(), and G4TrackingManager::ProcessOneTrack().
G4bool G4Track::IsBelowThreshold () const
G4bool G4Track::IsGoodForTracking () const
Referenced by G4SteppingManager::ApplyProductionCut(), and G4ITStepProcessor::ApplyProductionCut().
void G4Track::operator delete (void * aTrack) inline
void* G4Track::operator new (size_t) inline
G4Track & G4Track::operator= (const G4Track & right) private
Definition at line 167 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 167 of file G4Track.cc
References ClearAuxiliaryTrackInformation(), fBelowThreshold, fCurrentStepNumber, fGlobalTime, fGoodForTracking, fLocalTime, fParentID, fpCreatorProcess, fpDynamicParticle, fpLVAtVertex, fPosition, fpStep, fpUserInformation, fStepLength, fTrackID, fTrackLength, fTrackStatus, fVelocity, fVtxKineticEnergy, fVtxMomentumDirection, fVtxPosition, fWeight, groupvel, is_OpticalPhoton, prev_mat, prev_momentum, prev_velocity, and useGivenVelocity.
G4bool G4Track::operator== (const G4Track &)
void G4Track::RemoveAuxiliaryTrackInformation (G4int idx)
Definition at line 363 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 363 of file G4Track.cc
References G4PhysicsModelCatalog::Entries(), and fpAuxiliaryTrackInformationMap.
Referenced by RemoveAuxiliaryTrackInformation().
void G4Track::RemoveAuxiliaryTrackInformation (G4String & name)
Definition at line 373 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 373 of file G4Track.cc
References fpAuxiliaryTrackInformationMap, G4PhysicsModelCatalog::GetIndex(), incremental_prev_tag::idx, and RemoveAuxiliaryTrackInformation().
void G4Track::SetAuxiliaryTrackInformation (G4int idx, G4VAuxiliaryTrackInformation * info) const
Definition at line 336 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 336 of file G4Track.cc
References G4PhysicsModelCatalog::Entries(), FatalException, G4Exception(), and incremental_prev_tag::idx.
Referenced by G4Channeling::GetTrackData(), G4BOptrForceCollision::OperationApplied(), and G4BOptrForceCollision::ProposeNonPhysicsBiasingOperation().
void G4Track::SetBelowThresholdFlag (G4bool value = true)
void G4Track::SetCreatorModelIndex (G4int idx) inline
Referenced by G4VAtomDeexcitation::AlongStepDeexcitation(), G4eplusAnnihilation::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4RadioactiveDecayBase::DecayAnalog(), G4RadioactiveDecay::DecayIt(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4VEnergyLossProcess::FillSecondariesAlongStep(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), and G4VEnergyLossProcess::SampleSubCutSecondaries().
void G4Track::SetCreatorProcess (const G4VProcess * aValue)
Referenced by G4ITStepProcessor::DealWithSecondaries(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), and G4SteppingManager::InvokePSDIP().
void G4Track::SetGlobalTime (const G4double aValue)
void G4Track::SetGoodForTrackingFlag (G4bool value = true)
Referenced by G4ParticleChange::AddSecondary(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), and G4RadioactiveDecay::DecayIt().
void G4Track::SetKineticEnergy (const G4double aValue)
Referenced by G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4SteppingManager::ApplyProductionCut(), G4ITStepProcessor::ApplyProductionCut(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4VParticleChange::CheckSecondary(), G4DNAChemistryManager::CreateWaterMolecule(), G4ParticleChangeForLoss::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), G4ParticleChangeForLoss::UpdateStepForPostStep(), and G4ParticleChange::UpdateStepForPostStep().
void G4Track::SetLocalTime (const G4double aValue)
void G4Track::SetLogicalVolumeAtVertex (const G4LogicalVolume *)
Referenced by G4SteppingManager::SetInitialStep(), and G4ITStepProcessor::SetInitialStep().
void G4Track::SetMomentumDirection (const G4ThreeVector & aValue)
Referenced by G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4VParticleChange::CheckSecondary(), and XPhononStackingAction::ClassifyNewTrack().
void G4Track::SetNextTouchableHandle (const G4TouchableHandle & apValue)
Referenced by G4ITStepProcessor::InitDefineStep(), G4SteppingManager::SetInitialStep(), and G4ITStepProcessor::SetInitialStep().
void G4Track::SetOriginTouchableHandle (const G4TouchableHandle & apValue)
Referenced by G4SteppingManager::SetInitialStep().
void G4Track::SetParentID (const G4int aValue)
Referenced by G4DNAChemistryManager::CreateWaterMolecule(), G4ITStepProcessor::DealWithSecondaries(), G4PrimaryTransformer::GenerateSingleTrack(), G4ErrorPropagator::InitG4Track(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), MCTruthTrackingAction::PostUserTrackingAction(), G4StackManager::PrepareNewEvent(), and G4DNAChemistryManager::PushMolecule().
void G4Track::SetPolarization (const G4ThreeVector & aValue)
void G4Track::SetPosition (const G4ThreeVector & aValue)
void G4Track::SetProperTime (const G4double aValue)
void G4Track::SetStep (const G4Step * aValue)
Referenced by G4ITStepProcessor::InitDefineStep(), G4ErrorPropagator::InitG4Track(), and G4TrackingManager::ProcessOneTrack().
void G4Track::SetStepLength (G4double value)
Referenced by G4SteppingManager::InvokeAtRestDoItProcs(), and G4SteppingManager::Stepping().
void G4Track::SetTouchableHandle (const G4TouchableHandle & apValue)
Referenced by G4ParticleChangeForGamma::AddSecondary(), G4ParticleChange::AddSecondary(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), CexmcHadronicProcess::FillTotalResult(), G4ITStepProcessor::InitDefineStep(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4VEnergyLossProcess::SampleSubCutSecondaries(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), and G4SteppingManager::Stepping().
void G4Track::SetTrackID (const G4int aValue)
Referenced by G4ITTrackHolder::AddTrackID(), G4PrimaryTransformer::GenerateSingleTrack(), and G4StackManager::PrepareNewEvent().
void G4Track::SetTrackStatus (const G4TrackStatus aTrackStatus)
Referenced by G4DNAChemistryManager::CreateWaterMolecule(), G4ITStepProcessor::DealWithSecondaries(), G4TrackingManager::EventAborted(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4DNAElectronHoleRecombination::MakeReaction(), UltraPMTSD::ProcessHits(), G4TrackingManager::ProcessOneTrack(), G4DNAChemistryManager::PushMolecule(), G4ITTrackHolder::PushToKill(), G4SteppingManager::SetInitialStep(), G4ITStepProcessor::SetInitialStep(), G4TrackingMessenger::SetNewValue(), G4SteppingManager::Stepping(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), ExN04SteppingAction::UserSteppingAction(), RE05SteppingAction::UserSteppingAction(), RE01SteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), and G4AdjointSteppingAction::UserSteppingAction().
void G4Track::SetUserInformation (G4VUserTrackInformation * aValue) const
Referenced by G4Molecule::BuildTrack(), RE01StackingAction::ClassifyNewTrack(), SplitProcess::PostStepDoIt(), MCTruthTrackingAction::PostUserTrackingAction(), CexmcTrackingAction::PreUserTrackingAction(), PHG4TrackUserInfo::SetKeep(), PHG4TrackUserInfo::SetShower(), PHG4TrackUserInfo::SetUserParentId(), PHG4TrackUserInfo::SetUserPrimaryId(), PHG4TrackUserInfo::SetUserTrackId(), G4TrackingManager::SetUserTrackInformation(), PHG4TrackUserInfo::SetWanted(), PHG4FPbScSteppingAction::UserSteppingAction(), and PHG4FCalSteppingAction::UserSteppingAction().
void G4Track::SetVelocity (G4double val)
Referenced by XPhononStackingAction::ClassifyNewTrack(), G4VPhononProcess::CreateSecondary(), and G4ParallelWorldProcess::StartTracking().
void G4Track::SetVelocityTableProperties (G4double t_max, G4double t_min, G4int nbin) static
Definition at line 313 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 313 of file G4Track.cc
References G4VelocityTable::GetVelocityTable(), G4VelocityTable::SetVelocityTableProperties(), and velTable().
void G4Track::SetVertexKineticEnergy (const G4double aValue)
Referenced by G4SteppingManager::SetInitialStep(), and G4ITStepProcessor::SetInitialStep().
void G4Track::SetVertexMomentumDirection (const G4ThreeVector & aValue)
Referenced by G4SteppingManager::SetInitialStep(), and G4ITStepProcessor::SetInitialStep().
void G4Track::SetVertexPosition (const G4ThreeVector & aValue)
Referenced by G4SteppingManager::SetInitialStep(), and G4ITStepProcessor::SetInitialStep().
void G4Track::SetWeight (G4double aValue)
Referenced by G4VParticleChange::AddSecondary(), GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4eplusAnnihilation::AtRestDoIt(), G4MuonMinusAtomicCapture::AtRestDoIt(), G4HadronStoppingProcess::AtRestDoIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecay::DecayIt(), export_G4Track(), G4MuonicAtomDecay::FillResult(), G4HadronicProcess::FillResult(), G4VEnergyLossProcess::FillSecondariesAlongStep(), CexmcHadronicProcess::FillTotalResult(), G4BOptnCloning::GenerateBiasingFinalState(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState(), G4PrimaryTransformer::GenerateSingleTrack(), SplitProcess::PostStepDoIt(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4SamplingPostStepAction::Split(), and G4ParticleChangeForOccurenceBiasing::StealSecondaries().
G4bool G4Track::UseGivenVelocity () const
Referenced by XPhononStackingAction::ClassifyNewTrack(), and G4VPhononProcess::CreateSecondary().
void G4Track::UseGivenVelocity (G4bool val)
G4VelocityTable *& G4Track::velTable () static private
Definition at line 57 of file G4Track.cc.
View newest version in sPHENIX GitHub at line 57 of file G4Track.cc
References G4ThreadLocalStatic.
Referenced by CalculateVelocity(), G4Track(), and SetVelocityTableProperties().
Member Data Documentation
G4bool G4Track::fBelowThreshold private
Definition at line 290 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 290 of file G4Track.hh
Referenced by operator=().
G4int G4Track::fCreatorModelIndex private
Definition at line 313 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 313 of file G4Track.hh
G4int G4Track::fCurrentStepNumber private
Definition at line 273 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 273 of file G4Track.hh
Referenced by operator=().
G4double G4Track::fGlobalTime private
Definition at line 275 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 275 of file G4Track.hh
Referenced by operator=().
G4bool G4Track::fGoodForTracking private
Definition at line 293 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 293 of file G4Track.hh
Referenced by operator=().
G4double G4Track::fLocalTime private
Definition at line 276 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 276 of file G4Track.hh
Referenced by operator=().
G4int G4Track::fParentID private
Definition at line 278 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 278 of file G4Track.hh
Referenced by operator=().
std::map<G4int,G4VAuxiliaryTrackInformation*>* G4Track::fpAuxiliaryTrackInformationMap mutable private
Definition at line 330 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 330 of file G4Track.hh
Referenced by ClearAuxiliaryTrackInformation(), GetAuxiliaryTrackInformationMap(), and RemoveAuxiliaryTrackInformation().
const G4VProcess* G4Track::fpCreatorProcess private
Definition at line 312 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 312 of file G4Track.hh
Referenced by operator=().
G4DynamicParticle* G4Track::fpDynamicParticle private
Definition at line 287 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 287 of file G4Track.hh
Referenced by CalculateVelocity(), CalculateVelocityForOpticalPhoton(), G4Track(), operator=(), and ~G4Track().
const G4LogicalVolume* G4Track::fpLVAtVertex private
Definition at line 311 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 311 of file G4Track.hh
Referenced by operator=().
G4TouchableHandle G4Track::fpNextTouchable private
Definition at line 283 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 283 of file G4Track.hh
G4TouchableHandle G4Track::fpOriginTouchable private
Definition at line 284 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 284 of file G4Track.hh
G4ThreeVector G4Track::fPosition private
Definition at line 274 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 274 of file G4Track.hh
Referenced by operator=().
const G4Step* G4Track::fpStep private
Definition at line 306 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 306 of file G4Track.hh
Referenced by CalculateVelocityForOpticalPhoton(), and operator=().
G4TouchableHandle G4Track::fpTouchable private
Definition at line 282 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 282 of file G4Track.hh
Referenced by CalculateVelocityForOpticalPhoton().
G4VUserTrackInformation* G4Track::fpUserInformation mutable private
Definition at line 315 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 315 of file G4Track.hh
Referenced by operator=(), and ~G4Track().
G4double G4Track::fStepLength private
Definition at line 297 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 297 of file G4Track.hh
Referenced by operator=().
G4int G4Track::fTrackID private
Definition at line 279 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 279 of file G4Track.hh
Referenced by operator=().
G4double G4Track::fTrackLength private
Definition at line 277 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 277 of file G4Track.hh
Referenced by operator=().
G4TrackStatus G4Track::fTrackStatus private
Definition at line 288 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 288 of file G4Track.hh
Referenced by operator=().
G4double G4Track::fVelocity private
Definition at line 280 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 280 of file G4Track.hh
Referenced by CalculateVelocity(), G4Track(), and operator=().
G4double G4Track::fVtxKineticEnergy private
Definition at line 310 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 310 of file G4Track.hh
Referenced by operator=().
G4ThreeVector G4Track::fVtxMomentumDirection private
Definition at line 309 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 309 of file G4Track.hh
Referenced by operator=().
G4ThreeVector G4Track::fVtxPosition private
Definition at line 308 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 308 of file G4Track.hh
Referenced by operator=().
G4double G4Track::fWeight private
Definition at line 303 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 303 of file G4Track.hh
Referenced by operator=().
G4MaterialPropertyVector* G4Track::groupvel mutable private
Definition at line 319 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 319 of file G4Track.hh
Referenced by CalculateVelocityForOpticalPhoton(), and operator=().
G4bool G4Track::is_OpticalPhoton private
Definition at line 323 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 323 of file G4Track.hh
Referenced by CalculateVelocity(), G4Track(), and operator=().
G4Material* G4Track::prev_mat mutable private
Definition at line 318 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 318 of file G4Track.hh
Referenced by CalculateVelocityForOpticalPhoton(), and operator=().
G4double G4Track::prev_momentum mutable private
Definition at line 321 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 321 of file G4Track.hh
Referenced by CalculateVelocityForOpticalPhoton(), and operator=().
G4double G4Track::prev_velocity mutable private
Definition at line 320 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 320 of file G4Track.hh
Referenced by CalculateVelocityForOpticalPhoton(), and operator=().
G4bool G4Track::useGivenVelocity private
Definition at line 326 of file G4Track.hh.
View newest version in sPHENIX GitHub at line 326 of file G4Track.hh
Referenced by CalculateVelocity(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/track/include/G4Track.hh
geant4/tree/geant4-10.6-release/source/track/src/G4Track.cc