ECCE @ EIC Software: G4PhysicsModelCatalog Class Reference
G4PhysicsModelCatalog Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4PhysicsModelCatalog.hh>
Public Member Functions
~G4PhysicsModelCatalog ()
Static Public Member Functions
static G4int Register (const G4String &)
static const G4String & GetModelName (G4int)
static G4int GetIndex (const G4String &)
static G4int Entries ()
static void Destroy ()
Private Member Functions
G4PhysicsModelCatalog ()
G4PhysicsModelCatalog (const G4PhysicsModelCatalog &)
G4PhysicsModelCatalog & operator= (const G4PhysicsModelCatalog &)
Static Private Attributes
static modelCatalog * catalog = 0
Detailed Description
Definition at line 45 of file G4PhysicsModelCatalog.hh.
View newest version in sPHENIX GitHub at line 45 of file G4PhysicsModelCatalog.hh
Constructor & Destructor Documentation
G4PhysicsModelCatalog::G4PhysicsModelCatalog () private
Definition at line 35 of file G4PhysicsModelCatalog.cc.
View newest version in sPHENIX GitHub at line 35 of file G4PhysicsModelCatalog.cc
References catalog.
Referenced by Register().
G4PhysicsModelCatalog::G4PhysicsModelCatalog (const G4PhysicsModelCatalog &) private
G4PhysicsModelCatalog::~G4PhysicsModelCatalog ()
Definition at line 42 of file G4PhysicsModelCatalog.cc.
View newest version in sPHENIX GitHub at line 42 of file G4PhysicsModelCatalog.cc
Member Function Documentation
void G4PhysicsModelCatalog::Destroy (void) static
Definition at line 75 of file G4PhysicsModelCatalog.cc.
View newest version in sPHENIX GitHub at line 75 of file G4PhysicsModelCatalog.cc
G4int G4PhysicsModelCatalog::Entries () static
Definition at line 72 of file G4PhysicsModelCatalog.cc.
View newest version in sPHENIX GitHub at line 72 of file G4PhysicsModelCatalog.cc
References catalog.
Referenced by GetIndex(), GetModelName(), G4Track::RemoveAuxiliaryTrackInformation(), and G4Track::SetAuxiliaryTrackInformation().
G4int G4PhysicsModelCatalog::GetIndex (const G4String & name) static
Definition at line 65 of file G4PhysicsModelCatalog.cc.
View newest version in sPHENIX GitHub at line 65 of file G4PhysicsModelCatalog.cc
References catalog, Entries(), and incremental_prev_tag::idx.
Referenced by G4HadronicProcess::FillResult(), G4Channeling::G4Channeling(), G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), Register(), and G4Track::RemoveAuxiliaryTrackInformation().
const G4String & G4PhysicsModelCatalog::GetModelName (G4int idx) static
Definition at line 58 of file G4PhysicsModelCatalog.cc.
View newest version in sPHENIX GitHub at line 58 of file G4PhysicsModelCatalog.cc
References catalog, Entries(), and incremental_prev_tag::idx.
Referenced by G4RichTrajectory::CreateAttValues().
G4PhysicsModelCatalog& G4PhysicsModelCatalog::operator= (const G4PhysicsModelCatalog &) private
G4int G4PhysicsModelCatalog::Register (const G4String & name) static
Definition at line 46 of file G4PhysicsModelCatalog.cc.
View newest version in sPHENIX GitHub at line 46 of file G4PhysicsModelCatalog.cc
References catalog, G4PhysicsModelCatalog(), GetIndex(), incremental_prev_tag::idx, and G4Threading::IsWorkerThread().
Referenced by G4BOptrForceCollision::Configure(), G4BOptrForceCollision::ConfigureForWorker(), G4BinaryCascade::G4BinaryCascade(), G4BinaryLightIonReaction::G4BinaryLightIonReaction(), G4Channeling::G4Channeling(), G4VAtomDeexcitation::G4VAtomDeexcitation(), G4HadronStoppingProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), and G4DeexPrecoParameters::SetDefaults().
Member Data Documentation
modelCatalog * G4PhysicsModelCatalog::catalog = 0 static private
Definition at line 67 of file G4PhysicsModelCatalog.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PhysicsModelCatalog.hh
Referenced by Entries(), G4PhysicsModelCatalog(), GetIndex(), GetModelName(), and Register().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/global/management/include/G4PhysicsModelCatalog.hh
geant4/tree/geant4-10.6-release/source/global/management/src/G4PhysicsModelCatalog.cc