ECCE @ EIC Software: G4PathFinder Class Reference
G4PathFinder Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4PathFinder.hh>
Public Member Functions
G4double ComputeStep (const G4FieldTrack &pFieldTrack, G4double pCurrentProposedStepLength, G4int navigatorId, G4int stepNo, G4double &pNewSafety, ELimited &limitedStep, G4FieldTrack &EndState, G4VPhysicalVolume *currentVolume)
void Locate (const G4ThreeVector &position, const G4ThreeVector &direction, G4bool relativeSearch=true)
void ReLocate (const G4ThreeVector &position)
void PrepareNewTrack (const G4ThreeVector &position, const G4ThreeVector &direction, G4VPhysicalVolume *massStartVol=nullptr)
void EndTrack ()
G4TouchableHandle CreateTouchableHandle (G4int navId) const
G4VPhysicalVolume * GetLocatedVolume (G4int navId) const
G4bool RecheckDistanceToCurrentBoundary (const G4ThreeVector &pGlobalPoint, const G4ThreeVector &pDirection, const G4double pCurrentProposedStepLength, G4double *prDistance, G4double *prNewSafety=nullptr) const
G4bool IsParticleLooping () const
G4double GetCurrentSafety () const
G4double GetMinimumStep () const
unsigned int GetNumberGeometriesLimitingStep () const
G4double ComputeSafety (const G4ThreeVector &globalPoint)
G4double ObtainSafety (G4int navId, G4ThreeVector &globalCenterPoint)
void EnableParallelNavigation (G4bool enableChoice=true)
G4int SetVerboseLevel (G4int lev=-1)
G4int GetMaxLoopCount () const
void SetMaxLoopCount (G4int new_max)
void MovePoint ()
G4double LastPreSafety (G4int navId, G4ThreeVector &globalCenterPoint, G4double &minSafety)
void PushPostSafetyToPreSafety ()
G4String & LimitedString (ELimited lim)
~G4PathFinder ()
Static Public Member Functions
static G4PathFinder * GetInstance ()
static G4PathFinder * GetInstanceIfExist ()
Protected Member Functions
G4double DoNextLinearStep (const G4FieldTrack &FieldTrack, G4double proposedStepLength)
G4double DoNextCurvedStep (const G4FieldTrack &FieldTrack, G4double proposedStepLength, G4VPhysicalVolume *pCurrentPhysVolume)
void WhichLimited ()
void PrintLimited ()
G4bool UseSafetyForOptimization (G4bool)
void ReportMove (const G4ThreeVector &OldV, const G4ThreeVector &NewV, const G4String &Quantity) const
G4PathFinder ()
G4Navigator * GetNavigator (G4int n) const
Private Attributes
G4MultiNavigator * fpMultiNavigator
G4int fNoActiveNavigators = 0
G4bool fNewTrack = false
G4Navigator * fpNavigator [fMaxNav]
ELimited fLimitedStep [fMaxNav]
G4bool fLimitTruth [fMaxNav]
G4double fCurrentStepSize [fMaxNav]
G4int fNoGeometriesLimiting = 0
G4ThreeVector fPreSafetyLocation
G4double fPreSafetyMinValue = -1.0
G4double fPreSafetyValues [fMaxNav]
G4ThreeVector fPreStepLocation
G4double fMinSafety_PreStepPt = -1.0
G4double fCurrentPreStepSafety [fMaxNav]
G4bool fPreStepCenterRenewed = false
G4double fMinStep = -1.0
G4double fTrueMinStep = -1.0
G4VPhysicalVolume * fLocatedVolume [fMaxNav]
G4ThreeVector fLastLocatedPosition
G4FieldTrack fEndState
G4bool fFieldExertedForce = false
G4bool fRelocatedPoint = false
G4ThreeVector fSafetyLocation
G4double fMinSafety_atSafLocation = -1.0
G4double fNewSafetyComputed [fMaxNav]
G4int fLastStepNo = -1
G4int fCurrentStepNo = -1
G4int fVerboseLevel = 0
G4TransportationManager * fpTransportManager
G4PropagatorInField * fpFieldPropagator
G4double kCarTolerance
Static Private Attributes
static const G4int fMaxNav = 16
static G4ThreadLocal G4PathFinder * fpPathFinder = nullptr
Detailed Description
Definition at line 59 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4PathFinder.hh
Constructor & Destructor Documentation
G4PathFinder::~G4PathFinder ()
Definition at line 106 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 106 of file G4PathFinder.cc
References fpMultiNavigator, and fpPathFinder.
G4PathFinder::G4PathFinder () protected
Definition at line 74 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 74 of file G4PathFinder.cc
References fCurrentPreStepSafety, fCurrentStepSize, fLastLocatedPosition, fLimitedStep, fLimitTruth, fLocatedVolume, fMaxNav, fNewSafetyComputed, fpFieldPropagator, fpMultiNavigator, fpNavigator, fPreSafetyLocation, fPreSafetyValues, fPreStepLocation, fpTransportManager, fSafetyLocation, G4GeometryTolerance::GetInstance(), G4TransportationManager::GetPropagatorInField(), G4GeometryTolerance::GetSurfaceTolerance(), G4TransportationManager::GetTransportationManager(), kCarTolerance, kInfinity, kUndefLimited, and num.
Referenced by GetInstance().
Member Function Documentation
G4double G4PathFinder::ComputeSafety (const G4ThreeVector & globalPoint)
Definition at line 735 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 735 of file G4PathFinder.cc
References DBL_MAX, fMinSafety_atSafLocation, fNewSafetyComputed, fNoActiveNavigators, fpTransportManager, fSafetyLocation, fVerboseLevel, G4cout, G4endl, G4TransportationManager::GetActiveNavigatorsIterator(), kInfinity, num, and position.
Referenced by G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4SafetyHelper::ComputeSafety(), G4ITSafetyHelper::ComputeSafety(), and ReLocate().
G4double G4PathFinder::ComputeStep (const G4FieldTrack & pFieldTrack, G4double pCurrentProposedStepLength, G4int navigatorId, G4int stepNo, G4double & pNewSafety, ELimited & limitedStep, G4FieldTrack & EndState, G4VPhysicalVolume * currentVolume)
Definition at line 142 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 142 of file G4PathFinder.cc
References DoNextCurvedStep(), DoNextLinearStep(), false, FatalException, fCurrentPreStepSafety, fCurrentStepNo, fCurrentStepSize, fEndState, fFieldExertedForce, G4PropagatorInField::FindAndSetFieldManager(), fLastLocatedPosition, fLastStepNo, fLimitedStep, fMinStep, fNewTrack, fNoActiveNavigators, fNoGeometriesLimiting, fpFieldPropagator, fRelocatedPoint, fTrueMinStep, fVerboseLevel, G4cout, G4endl, G4Exception(), G4FieldTrack::GetCharge(), G4FieldManager::GetDetectorField(), G4FieldTrack::GetMomentumDirection(), G4FieldTrack::GetPosition(), kCarTolerance, Locate(), CLHEP::Hep3Vector::mag2(), max, message(), min, mm, MovePoint(), and sqr().
Referenced by G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4WeightCutOffProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(), G4ImportanceProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldScoringProcess::AlongStepGetPhysicalInteractionLength(), G4WeightWindowProcess::AlongStepGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::AlongStepGetPhysicalInteractionLength(), and Par02FastSimModelTracker::DoIt().
G4TouchableHandle G4PathFinder::CreateTouchableHandle (G4int navId) const
Definition at line 768 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 768 of file G4PathFinder.cc
References G4Navigator::CreateTouchableHistory(), fLocatedVolume, fVerboseLevel, G4cout, G4endl, G4TouchableHistory::GetHistory(), G4VPhysicalVolume::GetName(), GetNavigator(), and G4TouchableHistory::UpdateYourself().
Referenced by G4CoupledTransportation::PostStepDoIt(), G4ImportanceProcess::PostStepDoIt(), G4WeightCutOffProcess::PostStepDoIt(), G4WeightWindowProcess::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4WeightCutOffProcess::StartTracking(), G4ImportanceProcess::StartTracking(), G4WeightWindowProcess::StartTracking(), G4ParallelWorldScoringProcess::StartTracking(), and G4ParallelWorldProcess::StartTracking().
G4double G4PathFinder::DoNextCurvedStep (const G4FieldTrack & FieldTrack, G4double proposedStepLength, G4VPhysicalVolume * pCurrentPhysVolume) protected
Definition at line 1145 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 1145 of file G4PathFinder.cc
References kdfinder::abs(), G4Navigator::ComputeSafety(), G4PropagatorInField::ComputeStep(), DBL_MAX, FatalException, fCurrentPreStepSafety, fCurrentStepSize, fEndState, fLimitedStep, fLimitTruth, fMinSafety_PreStepPt, fMinStep, fNoActiveNavigators, fNoGeometriesLimiting, fpFieldPropagator, fpMultiNavigator, fpNavigator, fPreSafetyLocation, fPreSafetyMinValue, fPreSafetyValues, fPreStepCenterRenewed, fPreStepLocation, fTrueMinStep, fVerboseLevel, G4cout, G4endl, G4Exception(), G4FieldTrack::GetChargeState(), G4PropagatorInField::GetCurrentEquationOfMotion(), G4FieldTrack::GetMomentum(), G4FieldTrack::GetPosition(), G4FieldTrack::GetRestMass(), kDoNot, kInfinity, LimitedString(), CLHEP::Hep3Vector::mag(), message(), min, G4MultiNavigator::ObtainFinalStep(), PrintLimited(), and G4EquationOfMotion::SetChargeMomentumMass().
Referenced by ComputeStep().
G4double G4PathFinder::DoNextLinearStep (const G4FieldTrack & FieldTrack, G4double proposedStepLength) protected
Definition at line 804 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 804 of file G4PathFinder.cc
References fCurrentPreStepSafety, fCurrentStepSize, fEndState, fLimitedStep, fLimitTruth, fMinSafety_PreStepPt, fMinStep, fNoActiveNavigators, fNoGeometriesLimiting, fPreSafetyLocation, fPreSafetyMinValue, fPreSafetyValues, fPreStepCenterRenewed, fPreStepLocation, fpTransportManager, fTrueMinStep, fVerboseLevel, G4cout, G4endl, G4FieldTrack::GetMomentumDirection(), G4FieldTrack::GetPosition(), kDoNot, kInfinity, kUnique, CLHEP::Hep3Vector::mag2(), max, min, num, G4FieldTrack::SetPosition(), G4FieldTrack::SetProperTimeOfFlight(), sqr(), Acts::Test::step(), and WhichLimited().
Referenced by ComputeStep().
void G4PathFinder::EnableParallelNavigation (G4bool enableChoice = true)
Definition at line 115 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 115 of file G4PathFinder.cc
References G4SafetyHelper::EnableParallelNavigation(), fpFieldPropagator, fpMultiNavigator, fpTransportManager, G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetSafetyHelper(), and G4PropagatorInField::SetNavigatorForPropagating().
Referenced by EndTrack(), and PrepareNewTrack().
void G4PathFinder::EndTrack ()
Definition at line 432 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 432 of file G4PathFinder.cc
References EnableParallelNavigation().
Referenced by G4CoupledTransportation::EndTracking().
G4double G4PathFinder::GetCurrentSafety () const inline
Definition at line 317 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 317 of file G4PathFinder.hh
References fMinSafety_PreStepPt.
Referenced by G4CoupledTransportation::AlongStepGetPhysicalInteractionLength().
G4PathFinder * G4PathFinder::GetInstance (void) static
Definition at line 52 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 52 of file G4PathFinder.cc
References fpPathFinder, and G4PathFinder().
Referenced by Par02FastSimModelTracker::DoIt(), G4CoupledTransportation::G4CoupledTransportation(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), G4ImportanceProcess::G4ImportanceProcess(), G4ParallelGeometriesLimiterProcess::G4ParallelGeometriesLimiterProcess(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), G4ITSafetyHelper::InitialiseNavigator(), and G4SafetyHelper::InitialiseNavigator().
G4PathFinder * G4PathFinder::GetInstanceIfExist () static
Definition at line 66 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 66 of file G4PathFinder.cc
References fpPathFinder.
Referenced by G4RunManagerKernel::~G4RunManagerKernel().
G4VPhysicalVolume * G4PathFinder::GetLocatedVolume (G4int navId) const inline
Definition at line 292 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 292 of file G4PathFinder.hh
References fLocatedVolume, and fMaxNav.
Referenced by G4FastSimulationManagerProcess::AtRestGetPhysicalInteractionLength(), G4FastSimulationManagerProcess::PostStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess::PostStepGetPhysicalInteractionLength(), and G4ParallelGeometriesLimiterProcess::StartTracking().
G4int G4PathFinder::GetMaxLoopCount () const inline
G4double G4PathFinder::GetMinimumStep () const inline
Definition at line 306 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 306 of file G4PathFinder.hh
References fMinStep.
G4Navigator * G4PathFinder::GetNavigator (G4int n) const inline protected
Definition at line 327 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 327 of file G4PathFinder.hh
References fNoActiveNavigators, fpNavigator, and n.
Referenced by CreateTouchableHandle(), and PrintLimited().
unsigned int G4PathFinder::GetNumberGeometriesLimitingStep () const inline
Definition at line 311 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 311 of file G4PathFinder.hh
References fNoGeometriesLimiting.
Referenced by G4CoupledTransportation::AlongStepGetPhysicalInteractionLength().
G4bool G4PathFinder::IsParticleLooping () const inline
G4double G4PathFinder::LastPreSafety (G4int navId, G4ThreeVector & globalCenterPoint, G4double & minSafety) inline
Definition at line 341 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 341 of file G4PathFinder.hh
References fPreSafetyLocation, fPreSafetyMinValue, and fPreSafetyValues.
G4String & G4PathFinder::LimitedString (ELimited lim)
Definition at line 1413 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 1413 of file G4PathFinder.cc
References kDoNot, kSharedOther, kSharedTransport, and kUnique.
Referenced by DoNextCurvedStep(), and PrintLimited().
void G4PathFinder::Locate (const G4ThreeVector & position, const G4ThreeVector & direction, G4bool relativeSearch = true)
Definition at line 461 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 461 of file G4PathFinder.cc
References fCurrentStepSize, fEndState, fLastLocatedPosition, fLimitedStep, fLimitTruth, fLocatedVolume, fNewTrack, fNoActiveNavigators, fpTransportManager, fRelocatedPoint, fVerboseLevel, G4cout, G4endl, G4TransportationManager::GetActiveNavigatorsIterator(), G4FieldTrack::GetPosition(), kCarTolerance, kDoNot, CLHEP::Hep3Vector::mag2(), num, position, ReportMove(), and sqr().
Referenced by ComputeStep(), G4SafetyHelper::Locate(), G4ITSafetyHelper::Locate(), G4CoupledTransportation::PostStepDoIt(), and PrepareNewTrack().
void G4PathFinder::MovePoint () inline
Definition at line 322 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 322 of file G4PathFinder.hh
References fRelocatedPoint.
Referenced by ComputeStep(), and PrepareNewTrack().
G4double G4PathFinder::ObtainSafety (G4int navId, G4ThreeVector & globalCenterPoint) inline
Definition at line 334 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 334 of file G4PathFinder.hh
References fNewSafetyComputed, and fSafetyLocation.
Referenced by G4CoupledTransportation::AlongStepGetPhysicalInteractionLength().
void G4PathFinder::PrepareNewTrack (const G4ThreeVector & position, const G4ThreeVector & direction, G4VPhysicalVolume * massStartVol = nullptr)
Definition at line 342 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 342 of file G4PathFinder.cc
References EnableParallelNavigation(), FatalException, fCurrentPreStepSafety, fCurrentStepSize, fLastLocatedPosition, fLimitedStep, fLimitTruth, fLocatedVolume, fMaxNav, fMinSafety_atSafLocation, fMinSafety_PreStepPt, fNewSafetyComputed, fNewTrack, fNoActiveNavigators, fNoGeometriesLimiting, fpFieldPropagator, fpMultiNavigator, fpNavigator, fPreSafetyMinValue, fPreSafetyValues, fpTransportManager, fRelocatedPoint, G4endl, G4Exception(), G4TransportationManager::GetActiveNavigatorsIterator(), G4TransportationManager::GetSafetyHelper(), G4SafetyHelper::InitialiseHelper(), kDoNot, Locate(), message(), MovePoint(), num, position, G4MultiNavigator::PrepareNavigators(), and G4PropagatorInField::PrepareNewTrack().
Referenced by G4WeightCutOffProcess::StartTracking(), G4ImportanceProcess::StartTracking(), G4WeightWindowProcess::StartTracking(), G4ParallelWorldScoringProcess::StartTracking(), G4ParallelWorldProcess::StartTracking(), G4FastSimulationManagerProcess::StartTracking(), G4ParallelGeometriesLimiterProcess::StartTracking(), and G4CoupledTransportation::StartTracking().
void G4PathFinder::PrintLimited () protected
Definition at line 1085 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 1085 of file G4PathFinder.cc
References fCurrentPreStepSafety, fCurrentStepNo, fCurrentStepSize, fLimitedStep, fLimitTruth, fMinStep, fNoActiveNavigators, fTrueMinStep, fVerboseLevel, G4cout, G4endl, G4VPhysicalVolume::GetName(), GetNavigator(), G4Navigator::GetWorldVolume(), LimitedString(), and num.
Referenced by DoNextCurvedStep(), and WhichLimited().
void G4PathFinder::PushPostSafetyToPreSafety ()
Definition at line 1433 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 1433 of file G4PathFinder.cc
References fMinSafety_atSafLocation, fNewSafetyComputed, fNoActiveNavigators, fPreSafetyLocation, fPreSafetyMinValue, fPreSafetyValues, and fSafetyLocation.
G4bool G4PathFinder::RecheckDistanceToCurrentBoundary (const G4ThreeVector & pGlobalPoint, const G4ThreeVector & pDirection, const G4double pCurrentProposedStepLength, G4double * prDistance, G4double * prNewSafety = nullptr) const
Definition at line 1364 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 1364 of file G4PathFinder.cc
References fNoActiveNavigators, fpNavigator, kInfinity, min, and G4Navigator::RecheckDistanceToCurrentBoundary().
Referenced by G4SafetyHelper::RecheckDistanceToCurrentBoundary().
void G4PathFinder::ReLocate (const G4ThreeVector & position)
Definition at line 542 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 542 of file G4PathFinder.cc
References ComputeSafety(), e, FatalException, fCurrentStepSize, fEndState, fLastLocatedPosition, fLimitedStep, fLimitTruth, fMinSafety_atSafLocation, fMinSafety_PreStepPt, fNewTrack, fNoActiveNavigators, fPreSafetyLocation, fPreSafetyMinValue, fPreStepLocation, fpTransportManager, fRelocatedPoint, fSafetyLocation, fVerboseLevel, G4cout, G4endl, G4Exception(), G4TransportationManager::GetActiveNavigatorsIterator(), G4GeometryTolerance::GetInstance(), G4FieldTrack::GetPosition(), G4GeometryTolerance::GetRadialTolerance(), kDoNot, CLHEP::Hep3Vector::mag(), CLHEP::Hep3Vector::mag2(), max, message(), num, position, ReportMove(), sqr(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by G4CoupledTransportation::PostStepDoIt(), G4SafetyHelper::ReLocateWithinVolume(), and G4ITSafetyHelper::ReLocateWithinVolume().
void G4PathFinder::ReportMove (const G4ThreeVector & OldV, const G4ThreeVector & NewV, const G4String & Quantity) const protected
Definition at line 440 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 440 of file G4PathFinder.cc
References G4endl, G4Exception(), JustWarning, CLHEP::Hep3Vector::mag(), message(), and mm.
Referenced by Locate(), and ReLocate().
void G4PathFinder::SetMaxLoopCount (G4int new_max) inline
G4int G4PathFinder::SetVerboseLevel (G4int lev = -1) inline
Definition at line 299 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 299 of file G4PathFinder.hh
References fVerboseLevel.
G4bool G4PathFinder::UseSafetyForOptimization (G4bool) inline protected
void G4PathFinder::WhichLimited () protected
Definition at line 1025 of file G4PathFinder.cc.
View newest version in sPHENIX GitHub at line 1025 of file G4PathFinder.cc
References fCurrentStepSize, fLimitedStep, fLimitTruth, fMinStep, fNoActiveNavigators, fNoGeometriesLimiting, fVerboseLevel, G4cout, G4endl, kCarTolerance, kDoNot, kInfinity, kSharedOther, kSharedTransport, kUnique, num, PrintLimited(), and Acts::Test::step().
Referenced by DoNextLinearStep().
Member Data Documentation
G4double G4PathFinder::fCurrentPreStepSafety[fMaxNav] private
Definition at line 238 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 238 of file G4PathFinder.hh
Referenced by ComputeStep(), DoNextCurvedStep(), DoNextLinearStep(), G4PathFinder(), PrepareNewTrack(), and PrintLimited().
G4int G4PathFinder::fCurrentStepNo = -1 private
Definition at line 276 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 276 of file G4PathFinder.hh
Referenced by ComputeStep(), and PrintLimited().
G4double G4PathFinder::fCurrentStepSize[fMaxNav] private
Definition at line 222 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 222 of file G4PathFinder.hh
Referenced by ComputeStep(), DoNextCurvedStep(), DoNextLinearStep(), G4PathFinder(), Locate(), PrepareNewTrack(), PrintLimited(), ReLocate(), and WhichLimited().
G4FieldTrack G4PathFinder::fEndState private
Definition at line 257 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 257 of file G4PathFinder.hh
Referenced by ComputeStep(), DoNextCurvedStep(), DoNextLinearStep(), Locate(), and ReLocate().
G4bool G4PathFinder::fFieldExertedForce = false private
Definition at line 258 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 258 of file G4PathFinder.hh
Referenced by ComputeStep().
G4ThreeVector G4PathFinder::fLastLocatedPosition private
Definition at line 252 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 252 of file G4PathFinder.hh
Referenced by ComputeStep(), G4PathFinder(), Locate(), PrepareNewTrack(), and ReLocate().
G4int G4PathFinder::fLastStepNo = -1 private
Definition at line 276 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 276 of file G4PathFinder.hh
Referenced by ComputeStep().
ELimited G4PathFinder::fLimitedStep[fMaxNav] private
Definition at line 220 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 220 of file G4PathFinder.hh
Referenced by ComputeStep(), DoNextCurvedStep(), DoNextLinearStep(), G4PathFinder(), Locate(), PrepareNewTrack(), PrintLimited(), ReLocate(), and WhichLimited().
G4bool G4PathFinder::fLimitTruth[fMaxNav] private
Definition at line 221 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 221 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), DoNextLinearStep(), G4PathFinder(), Locate(), PrepareNewTrack(), PrintLimited(), ReLocate(), and WhichLimited().
G4VPhysicalVolume* G4PathFinder::fLocatedVolume[fMaxNav] private
Definition at line 251 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 251 of file G4PathFinder.hh
Referenced by CreateTouchableHandle(), G4PathFinder(), GetLocatedVolume(), Locate(), and PrepareNewTrack().
const G4int G4PathFinder::fMaxNav = 16 static private
Definition at line 212 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 212 of file G4PathFinder.hh
Referenced by G4PathFinder(), GetLocatedVolume(), and PrepareNewTrack().
G4double G4PathFinder::fMinSafety_atSafLocation = -1.0 private
Definition at line 269 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 269 of file G4PathFinder.hh
Referenced by ComputeSafety(), PrepareNewTrack(), PushPostSafetyToPreSafety(), and ReLocate().
G4double G4PathFinder::fMinSafety_PreStepPt = -1.0 private
Definition at line 236 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 236 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), DoNextLinearStep(), GetCurrentSafety(), PrepareNewTrack(), and ReLocate().
G4double G4PathFinder::fMinStep = -1.0 private
Definition at line 246 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 246 of file G4PathFinder.hh
Referenced by ComputeStep(), DoNextCurvedStep(), DoNextLinearStep(), GetMinimumStep(), PrintLimited(), and WhichLimited().
G4double G4PathFinder::fNewSafetyComputed[fMaxNav] private
Definition at line 271 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 271 of file G4PathFinder.hh
Referenced by ComputeSafety(), G4PathFinder(), ObtainSafety(), PrepareNewTrack(), and PushPostSafetyToPreSafety().
G4bool G4PathFinder::fNewTrack = false private
Definition at line 210 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 210 of file G4PathFinder.hh
Referenced by ComputeStep(), Locate(), PrepareNewTrack(), and ReLocate().
G4int G4PathFinder::fNoActiveNavigators = 0 private
Definition at line 209 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 209 of file G4PathFinder.hh
Referenced by ComputeSafety(), ComputeStep(), DoNextCurvedStep(), DoNextLinearStep(), GetNavigator(), Locate(), PrepareNewTrack(), PrintLimited(), PushPostSafetyToPreSafety(), RecheckDistanceToCurrentBoundary(), ReLocate(), and WhichLimited().
G4int G4PathFinder::fNoGeometriesLimiting = 0 private
Definition at line 223 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 223 of file G4PathFinder.hh
Referenced by ComputeStep(), DoNextCurvedStep(), DoNextLinearStep(), GetNumberGeometriesLimitingStep(), PrepareNewTrack(), and WhichLimited().
G4PropagatorInField* G4PathFinder::fpFieldPropagator private
Definition at line 281 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 281 of file G4PathFinder.hh
Referenced by ComputeStep(), DoNextCurvedStep(), EnableParallelNavigation(), G4PathFinder(), and PrepareNewTrack().
G4MultiNavigator* G4PathFinder::fpMultiNavigator private
Definition at line 206 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 206 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), EnableParallelNavigation(), G4PathFinder(), PrepareNewTrack(), and ~G4PathFinder().
G4Navigator* G4PathFinder::fpNavigator[fMaxNav] private
Definition at line 216 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 216 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), G4PathFinder(), GetNavigator(), PrepareNewTrack(), and RecheckDistanceToCurrentBoundary().
G4ThreadLocal G4PathFinder * G4PathFinder::fpPathFinder = nullptr static private
Definition at line 285 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 285 of file G4PathFinder.hh
Referenced by GetInstance(), GetInstanceIfExist(), and ~G4PathFinder().
G4ThreeVector G4PathFinder::fPreSafetyLocation private
Definition at line 225 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 225 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), DoNextLinearStep(), G4PathFinder(), LastPreSafety(), PushPostSafetyToPreSafety(), and ReLocate().
G4double G4PathFinder::fPreSafetyMinValue = -1.0 private
Definition at line 227 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 227 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), DoNextLinearStep(), LastPreSafety(), PrepareNewTrack(), PushPostSafetyToPreSafety(), and ReLocate().
G4double G4PathFinder::fPreSafetyValues[fMaxNav] private
Definition at line 229 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 229 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), DoNextLinearStep(), G4PathFinder(), LastPreSafety(), PrepareNewTrack(), and PushPostSafetyToPreSafety().
G4bool G4PathFinder::fPreStepCenterRenewed = false private
Definition at line 243 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 243 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), and DoNextLinearStep().
G4ThreeVector G4PathFinder::fPreStepLocation private
Definition at line 234 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 234 of file G4PathFinder.hh
Referenced by DoNextCurvedStep(), DoNextLinearStep(), G4PathFinder(), and ReLocate().
G4TransportationManager* G4PathFinder::fpTransportManager private
Definition at line 280 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 280 of file G4PathFinder.hh
Referenced by ComputeSafety(), DoNextLinearStep(), EnableParallelNavigation(), G4PathFinder(), Locate(), PrepareNewTrack(), and ReLocate().
G4bool G4PathFinder::fRelocatedPoint = false private
Definition at line 260 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 260 of file G4PathFinder.hh
Referenced by ComputeStep(), Locate(), MovePoint(), PrepareNewTrack(), and ReLocate().
G4ThreeVector G4PathFinder::fSafetyLocation private
Definition at line 267 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 267 of file G4PathFinder.hh
Referenced by ComputeSafety(), G4PathFinder(), ObtainSafety(), PushPostSafetyToPreSafety(), and ReLocate().
G4double G4PathFinder::fTrueMinStep = -1.0 private
Definition at line 247 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 247 of file G4PathFinder.hh
Referenced by ComputeStep(), DoNextCurvedStep(), DoNextLinearStep(), and PrintLimited().
G4int G4PathFinder::fVerboseLevel = 0 private
Definition at line 278 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 278 of file G4PathFinder.hh
Referenced by ComputeSafety(), ComputeStep(), CreateTouchableHandle(), DoNextCurvedStep(), DoNextLinearStep(), Locate(), PrintLimited(), ReLocate(), SetVerboseLevel(), and WhichLimited().
G4double G4PathFinder::kCarTolerance private
Definition at line 283 of file G4PathFinder.hh.
View newest version in sPHENIX GitHub at line 283 of file G4PathFinder.hh
Referenced by ComputeStep(), G4PathFinder(), Locate(), and WhichLimited().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4PathFinder.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4PathFinder.cc