ECCE @ EIC Software: G4BinaryTritonBuilder Class Reference
G4BinaryTritonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BinaryTritonBuilder.hh>
Public Member Functions
G4BinaryTritonBuilder ()
virtual ~G4BinaryTritonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4TritonInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VTritonBuilder
G4VTritonBuilder ()=default
virtual ~G4VTritonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4BinaryCascade * theModel
G4double theMin
G4double theMax
Detailed Description
Definition at line 52 of file G4BinaryTritonBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BinaryTritonBuilder.hh
Constructor & Destructor Documentation
G4BinaryTritonBuilder::G4BinaryTritonBuilder ()
Definition at line 48 of file G4BinaryTritonBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4BinaryTritonBuilder.cc
References G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), theMax, theMin, and theModel.
virtual G4BinaryTritonBuilder::~G4BinaryTritonBuilder () inline virtual
Definition at line 56 of file G4BinaryTritonBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4BinaryTritonBuilder.hh
Member Function Documentation
virtual void G4BinaryTritonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VTritonBuilder.
Definition at line 58 of file G4BinaryTritonBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BinaryTritonBuilder.hh
void G4BinaryTritonBuilder::Build (G4TritonInelasticProcess * aP) final override virtual
Implements G4VTritonBuilder.
Definition at line 56 of file G4BinaryTritonBuilder.cc.
View newest version in sPHENIX GitHub at line 56 of file G4BinaryTritonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4BinaryTritonBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 62 of file G4BinaryTritonBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BinaryTritonBuilder.hh
References theMax.
virtual void G4BinaryTritonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 61 of file G4BinaryTritonBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryTritonBuilder.hh
References theMin.
Member Data Documentation
G4double G4BinaryTritonBuilder::theMax private
Definition at line 70 of file G4BinaryTritonBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BinaryTritonBuilder.hh
Referenced by Build(), G4BinaryTritonBuilder(), and SetMaxEnergy().
G4double G4BinaryTritonBuilder::theMin private
Definition at line 69 of file G4BinaryTritonBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BinaryTritonBuilder.hh
Referenced by Build(), G4BinaryTritonBuilder(), and SetMinEnergy().
G4BinaryCascade* G4BinaryTritonBuilder::theModel private
Definition at line 68 of file G4BinaryTritonBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4BinaryTritonBuilder.hh
Referenced by Build(), and G4BinaryTritonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BinaryTritonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4BinaryTritonBuilder.cc