ECCE @ EIC Software: G4PSTARStopping Class Reference
G4PSTARStopping Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PSTARStopping.hh>
Public Member Functions
G4PSTARStopping ()
~G4PSTARStopping ()
void Initialise ()
G4int GetIndex (const G4Material *) const
G4int GetIndex (const G4String &) const
G4double GetElectronicDEDX (G4int idx, G4double energy) const
G4double GetElectronicDEDX (const G4Material *, G4double energy) const
Private Member Functions
void AddData (const G4float *s, const G4Material *)
void FindData (G4int idx, const G4Material *)
void PrintWarning (G4int idx) const
G4PSTARStopping & operator= (const G4PSTARStopping &right)=delete
G4PSTARStopping (const G4PSTARStopping &)=delete
Private Attributes
G4int nvectors
G4double emin
std::vector< const G4Material * > materials
std::vector
< G4LPhysicsFreeVector * > sdata
Detailed Description
Definition at line 62 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 62 of file G4PSTARStopping.hh
Constructor & Destructor Documentation
G4PSTARStopping::G4PSTARStopping () explicit
Definition at line 55 of file G4PSTARStopping.cc.
View newest version in sPHENIX GitHub at line 55 of file G4PSTARStopping.cc
References Initialise().
G4PSTARStopping::~G4PSTARStopping ()
Definition at line 63 of file G4PSTARStopping.cc.
View newest version in sPHENIX GitHub at line 63 of file G4PSTARStopping.cc
References nvectors, and sdata.
G4PSTARStopping::G4PSTARStopping (const G4PSTARStopping &) private delete
Member Function Documentation
void G4PSTARStopping::AddData (const G4float * s, const G4Material * mat) private
Definition at line 353 of file G4PSTARStopping.cc.
View newest version in sPHENIX GitHub at line 353 of file G4PSTARStopping.cc
References fac, G4PhysicsVector::FillSecondDerivatives(), materials, nvectors, G4LPhysicsFreeVector::PutValues(), sdata, G4PhysicsVector::SetSpline(), T0, and v.
Referenced by FindData().
void G4PSTARStopping::FindData (G4int idx, const G4Material * mat) private
Definition at line 125 of file G4PSTARStopping.cc.
View newest version in sPHENIX GitHub at line 125 of file G4PSTARStopping.cc
References AddData(), e1, e2, e3, e4, e5, e6, and f.
Referenced by Initialise().
G4double G4PSTARStopping::GetElectronicDEDX (G4int idx, G4double energy) const inline
Definition at line 129 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 129 of file G4PSTARStopping.hh
References emin, incremental_prev_tag::idx, nvectors, PrintWarning(), and sdata.
Referenced by G4BraggModel::DEDX(), and GetElectronicDEDX().
G4double G4PSTARStopping::GetElectronicDEDX (const G4Material * mat, G4double energy) const inline
Definition at line 141 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 141 of file G4PSTARStopping.hh
References GetElectronicDEDX(), and GetIndex().
G4int G4PSTARStopping::GetIndex (const G4Material * mat) const inline
Definition at line 100 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 100 of file G4PSTARStopping.hh
References incremental_prev_tag::idx, materials, and nvectors.
Referenced by G4BraggModel::DEDX(), and GetElectronicDEDX().
G4int G4PSTARStopping::GetIndex (const G4String & nam) const inline
Definition at line 114 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 114 of file G4PSTARStopping.hh
References incremental_prev_tag::idx, materials, and nvectors.
void G4PSTARStopping::Initialise ()
Definition at line 82 of file G4PSTARStopping.cc.
View newest version in sPHENIX GitHub at line 82 of file G4PSTARStopping.cc
References FindData(), G4Material::GetChemicalFormula(), G4Material::GetMaterialTable(), G4Material::GetName(), G4Material::GetNumberOfMaterials(), mat, materials, molecularIndex, molecularName, nameNIST, numberOfMolecula, and nvectors.
Referenced by G4PSTARStopping(), and G4BraggModel::Initialise().
G4PSTARStopping& G4PSTARStopping::operator= (const G4PSTARStopping & right) private delete
void G4PSTARStopping::PrintWarning (G4int idx) const private
Definition at line 72 of file G4PSTARStopping.cc.
View newest version in sPHENIX GitHub at line 72 of file G4PSTARStopping.cc
References G4Exception(), JustWarning, and nvectors.
Referenced by GetElectronicDEDX().
Member Data Documentation
G4double G4PSTARStopping::emin private
Definition at line 93 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PSTARStopping.hh
Referenced by GetElectronicDEDX().
std::vector<const G4Material*> G4PSTARStopping::materials private
Definition at line 94 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PSTARStopping.hh
Referenced by AddData(), GetIndex(), and Initialise().
G4int G4PSTARStopping::nvectors private
Definition at line 92 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PSTARStopping.hh
Referenced by AddData(), GetElectronicDEDX(), GetIndex(), Initialise(), PrintWarning(), and ~G4PSTARStopping().
std::vector<G4LPhysicsFreeVector*> G4PSTARStopping::sdata private
Definition at line 95 of file G4PSTARStopping.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PSTARStopping.hh
Referenced by AddData(), GetElectronicDEDX(), and ~G4PSTARStopping().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PSTARStopping.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4PSTARStopping.cc