ECCE @ EIC Software: G4GEMCoulombBarrier Class Reference
G4GEMCoulombBarrier Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/include/G4GEMCoulombBarrier.hh>
Public Member Functions
G4GEMCoulombBarrier (G4int anA, G4int aZ)
virtual ~G4GEMCoulombBarrier ()
virtual G4double GetCoulombBarrier (G4int ARes, G4int ZRes, G4double U) const
Public Member Functions inherited from G4CoulombBarrier
G4CoulombBarrier (G4int anA, G4int aZ)
virtual ~G4CoulombBarrier ()
G4double GetCoulombBarrier (G4int ARes, G4int ZRes, G4double U) const
virtual G4double BarrierPenetrationFactor (G4int Eexc) const
Public Member Functions inherited from G4VCoulombBarrier
G4VCoulombBarrier (G4int anA, G4int aZ)
virtual ~G4VCoulombBarrier ()
void SetParameters (G4double rho, G4double r0)
G4int GetA (void) const
G4int GetZ (void) const
G4double GetRho (void) const
G4double GetR0 (void) const
Private Member Functions
G4GEMCoulombBarrier (const G4GEMCoulombBarrier &right)=delete
const G4GEMCoulombBarrier & operator= (const G4GEMCoulombBarrier &right)=delete
G4bool operator== (const G4GEMCoulombBarrier &right) const =delete
G4bool operator!= (const G4GEMCoulombBarrier &right) const =delete
G4double CalcCompoundRadius (G4int ARes) const
Private Attributes
G4double AejectOneThird
Additional Inherited Members
Protected Attributes inherited from G4CoulombBarrier
G4Pow * g4calc
Detailed Description
Definition at line 37 of file G4GEMCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 37 of file G4GEMCoulombBarrier.hh
Constructor & Destructor Documentation
G4GEMCoulombBarrier::G4GEMCoulombBarrier (G4int anA, G4int aZ) explicit
Definition at line 36 of file G4GEMCoulombBarrier.cc.
View newest version in sPHENIX GitHub at line 36 of file G4GEMCoulombBarrier.cc
References AejectOneThird, G4CoulombBarrier::g4calc, and G4Pow::Z13().
G4GEMCoulombBarrier::~G4GEMCoulombBarrier () virtual
Definition at line 42 of file G4GEMCoulombBarrier.cc.
View newest version in sPHENIX GitHub at line 42 of file G4GEMCoulombBarrier.cc
G4GEMCoulombBarrier::G4GEMCoulombBarrier (const G4GEMCoulombBarrier & right) private delete
Member Function Documentation
G4double G4GEMCoulombBarrier::CalcCompoundRadius (G4int ARes) const private
Definition at line 65 of file G4GEMCoulombBarrier.cc.
View newest version in sPHENIX GitHub at line 65 of file G4GEMCoulombBarrier.cc
References A(), AejectOneThird, fermi, G4CoulombBarrier::g4calc, G4VCoulombBarrier::GetA(), and G4Pow::Z13().
G4double G4GEMCoulombBarrier::GetCoulombBarrier (G4int ARes, G4int ZRes, G4double U) const virtual
Implements G4VCoulombBarrier.
Definition at line 45 of file G4GEMCoulombBarrier.cc.
View newest version in sPHENIX GitHub at line 45 of file G4GEMCoulombBarrier.cc
References CLHEP::elm_coupling.
G4bool G4GEMCoulombBarrier::operator!= (const G4GEMCoulombBarrier & right) const private delete
const G4GEMCoulombBarrier& G4GEMCoulombBarrier::operator= (const G4GEMCoulombBarrier & right) private delete
G4bool G4GEMCoulombBarrier::operator== (const G4GEMCoulombBarrier & right) const private delete
Member Data Documentation
G4double G4GEMCoulombBarrier::AejectOneThird private
Definition at line 55 of file G4GEMCoulombBarrier.hh.
View newest version in sPHENIX GitHub at line 55 of file G4GEMCoulombBarrier.hh
Referenced by CalcCompoundRadius(), and G4GEMCoulombBarrier().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/include/G4GEMCoulombBarrier.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/gem_evaporation/src/G4GEMCoulombBarrier.cc