ECCE @ EIC Software: F02DetectorConstruction Class Reference
F02DetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02DetectorConstruction.hh>
Public Member Functions
F02DetectorConstruction ()
virtual ~F02DetectorConstruction ()
void SetAbsorberMaterial (G4String)
void SetAbsorberThickness (G4double)
void SetAbsorberRadius (G4double)
void SetAbsorberZpos (G4double)
void SetWorldMaterial (G4String)
void SetWorldSizeZ (G4double)
void SetWorldSizeR (G4double)
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
void PrintCalorParameters ()
G4Material * GetWorldMaterial ()
G4double GetWorldSizeZ ()
G4double GetWorldSizeR ()
G4double GetAbsorberZpos ()
G4double GetZStartAbs ()
G4double GetZEndAbs ()
G4Material * GetAbsorberMaterial ()
G4double GetAbsorberThickness ()
G4double GetAbsorberRadius ()
const G4VPhysicalVolume * GetPhysiWorld ()
const G4VPhysicalVolume * GetAbsorber ()
G4LogicalVolume * GetLogicalAbsorber ()
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
void ComputeCalorParameters ()
G4VPhysicalVolume * ConstructCalorimeter ()
Private Attributes
F02DetectorMessenger * fDetectorMessenger
G4Cache< F02CalorimeterSD * > fCalorimeterSD
G4Cache< F02ElectricFieldSetup * > fEmFieldSetup
G4Tubs * fSolidWorld
G4LogicalVolume * fLogicWorld
G4VPhysicalVolume * fPhysiWorld
G4Tubs * fSolidAbsorber
G4LogicalVolume * fLogicAbsorber
G4VPhysicalVolume * fPhysiAbsorber
G4Material * fAbsorberMaterial
G4double fAbsorberThickness
G4double fAbsorberRadius
G4bool fWorldChanged
G4double fZAbsorber
G4double fZStartAbs
G4double fZEndAbs
G4Material * fWorldMaterial
G4double fWorldSizeR
G4double fWorldSizeZ
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Definition at line 55 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 55 of file F02DetectorConstruction.hh
Constructor & Destructor Documentation
F02DetectorConstruction::F02DetectorConstruction ()
Definition at line 59 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 59 of file F02DetectorConstruction.cc
References cm, DefineMaterials(), fAbsorberRadius, fAbsorberThickness, fDetectorMessenger, fWorldSizeR, fWorldSizeZ, fZAbsorber, and mm.
F02DetectorConstruction::~F02DetectorConstruction () virtual
Definition at line 90 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 90 of file F02DetectorConstruction.cc
References fDetectorMessenger.
Member Function Documentation
void F02DetectorConstruction::ComputeCalorParameters () inline private
Definition at line 132 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 132 of file F02DetectorConstruction.hh
References fAbsorberThickness, fZAbsorber, fZEndAbs, and fZStartAbs.
Referenced by ConstructCalorimeter(), SetAbsorberRadius(), SetAbsorberThickness(), SetAbsorberZpos(), SetWorldSizeR(), and SetWorldSizeZ().
G4VPhysicalVolume * F02DetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 97 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 97 of file F02DetectorConstruction.cc
References ConstructCalorimeter().
G4VPhysicalVolume * F02DetectorConstruction::ConstructCalorimeter () private
Definition at line 220 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 220 of file F02DetectorConstruction.cc
References G4PhysicalVolumeStore::Clean(), G4LogicalVolumeStore::Clean(), G4SolidStore::Clean(), ComputeCalorParameters(), fAbsorberMaterial, fAbsorberRadius, fAbsorberThickness, fLogicAbsorber, fLogicWorld, fPhysiAbsorber, fPhysiWorld, fSolidAbsorber, fSolidWorld, fWorldMaterial, fWorldSizeR, fWorldSizeZ, fZAbsorber, G4LogicalVolumeStore::GetInstance(), G4PhysicalVolumeStore::GetInstance(), G4SolidStore::GetInstance(), G4GeometryManager::GetInstance(), G4GeometryManager::OpenGeometry(), PrintCalorParameters(), and twopi.
Referenced by Construct().
void F02DetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 383 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 383 of file F02DetectorConstruction.cc
References G4SDManager::AddNewDetector(), fCalorimeterSD, fEmFieldSetup, fLogicAbsorber, G4Cache< VALTYPE >::Get(), G4SDManager::GetSDMpointer(), G4Cache< VALTYPE >::Put(), G4AutoDelete::Register(), and G4VUserDetectorConstruction::SetSensitiveDetector().
void F02DetectorConstruction::DefineMaterials () private
Definition at line 104 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 104 of file F02DetectorConstruction.cc
References a, G4Material::AddElement(), G4Material::AddMaterial(), cm3, fAbsorberMaterial, fWorldMaterial, Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetMaterialTable(), kStateGas, mg, mole, source.hepunit::STP_Pressure, source.hepunit::STP_Temperature, and z.
Referenced by F02DetectorConstruction().
const G4VPhysicalVolume* F02DetectorConstruction::GetAbsorber () inline
Definition at line 94 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 94 of file F02DetectorConstruction.hh
References fPhysiAbsorber.
Referenced by F02CalorimeterSD::ProcessHits().
G4Material* F02DetectorConstruction::GetAbsorberMaterial () inline
Definition at line 89 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 89 of file F02DetectorConstruction.hh
References fAbsorberMaterial.
G4double F02DetectorConstruction::GetAbsorberRadius () inline
Definition at line 91 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 91 of file F02DetectorConstruction.hh
References fAbsorberRadius.
Referenced by F02PrimaryGeneratorAction::GeneratePrimaries().
G4double F02DetectorConstruction::GetAbsorberThickness () inline
Definition at line 90 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 90 of file F02DetectorConstruction.hh
References fAbsorberThickness.
G4double F02DetectorConstruction::GetAbsorberZpos () inline
Definition at line 85 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file F02DetectorConstruction.hh
References fZAbsorber.
G4LogicalVolume* F02DetectorConstruction::GetLogicalAbsorber () inline
Definition at line 95 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 95 of file F02DetectorConstruction.hh
References fLogicAbsorber.
const G4VPhysicalVolume* F02DetectorConstruction::GetPhysiWorld () inline
Definition at line 93 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 93 of file F02DetectorConstruction.hh
References fPhysiWorld.
G4Material* F02DetectorConstruction::GetWorldMaterial () inline
Definition at line 81 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 81 of file F02DetectorConstruction.hh
References fWorldMaterial.
G4double F02DetectorConstruction::GetWorldSizeR () inline
Definition at line 83 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 83 of file F02DetectorConstruction.hh
References fWorldSizeR.
G4double F02DetectorConstruction::GetWorldSizeZ () inline
Definition at line 82 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file F02DetectorConstruction.hh
References fWorldSizeZ.
G4double F02DetectorConstruction::GetZEndAbs () inline
Definition at line 87 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 87 of file F02DetectorConstruction.hh
References fZEndAbs.
G4double F02DetectorConstruction::GetZStartAbs () inline
Definition at line 86 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 86 of file F02DetectorConstruction.hh
References fZStartAbs.
void F02DetectorConstruction::PrintCalorParameters ()
Definition at line 277 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 277 of file F02DetectorConstruction.cc
References fAbsorberMaterial, fAbsorberRadius, fAbsorberThickness, fWorldMaterial, fWorldSizeR, fWorldSizeZ, fZAbsorber, G4cout, G4endl, G4Material::GetName(), and mm.
Referenced by ConstructCalorimeter().
void F02DetectorConstruction::SetAbsorberMaterial (G4String materialChoice)
Definition at line 294 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 294 of file F02DetectorConstruction.cc
References fAbsorberMaterial, fLogicAbsorber, G4Material::GetMaterialTable(), G4Material::GetName(), G4RunManager::GetRunManager(), material(), G4RunManager::PhysicsHasBeenModified(), and G4LogicalVolume::SetMaterial().
Referenced by F02DetectorMessenger::SetNewValue().
void F02DetectorConstruction::SetAbsorberRadius (G4double val)
Definition at line 344 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 344 of file F02DetectorConstruction.cc
References ComputeCalorParameters(), fAbsorberRadius, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F02DetectorMessenger::SetNewValue().
void F02DetectorConstruction::SetAbsorberThickness (G4double val)
Definition at line 334 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 334 of file F02DetectorConstruction.cc
References ComputeCalorParameters(), fAbsorberThickness, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F02DetectorMessenger::SetNewValue().
void F02DetectorConstruction::SetAbsorberZpos (G4double val)
Definition at line 374 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 374 of file F02DetectorConstruction.cc
References ComputeCalorParameters(), fZAbsorber, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F02DetectorMessenger::SetNewValue().
void F02DetectorConstruction::SetWorldMaterial (G4String materialChoice)
Definition at line 314 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 314 of file F02DetectorConstruction.cc
References fLogicWorld, fWorldMaterial, G4Material::GetMaterialTable(), G4Material::GetName(), G4RunManager::GetRunManager(), material(), G4RunManager::PhysicsHasBeenModified(), and G4LogicalVolume::SetMaterial().
Referenced by F02DetectorMessenger::SetNewValue().
void F02DetectorConstruction::SetWorldSizeR (G4double val)
Definition at line 364 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 364 of file F02DetectorConstruction.cc
References ComputeCalorParameters(), fWorldChanged, fWorldSizeR, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F02DetectorMessenger::SetNewValue().
void F02DetectorConstruction::SetWorldSizeZ (G4double val)
Definition at line 354 of file F02DetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 354 of file F02DetectorConstruction.cc
References ComputeCalorParameters(), fWorldChanged, fWorldSizeZ, G4RunManager::GetRunManager(), and G4RunManager::ReinitializeGeometry().
Referenced by F02DetectorMessenger::SetNewValue().
Member Data Documentation
G4Material* F02DetectorConstruction::fAbsorberMaterial private
Definition at line 111 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 111 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), DefineMaterials(), GetAbsorberMaterial(), PrintCalorParameters(), and SetAbsorberMaterial().
G4double F02DetectorConstruction::fAbsorberRadius private
Definition at line 113 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 113 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), F02DetectorConstruction(), GetAbsorberRadius(), PrintCalorParameters(), and SetAbsorberRadius().
G4double F02DetectorConstruction::fAbsorberThickness private
Definition at line 112 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 112 of file F02DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), F02DetectorConstruction(), GetAbsorberThickness(), PrintCalorParameters(), and SetAbsorberThickness().
G4Cache<F02CalorimeterSD*> F02DetectorConstruction::fCalorimeterSD private
Definition at line 100 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 100 of file F02DetectorConstruction.hh
Referenced by ConstructSDandField().
F02DetectorMessenger* F02DetectorConstruction::fDetectorMessenger private
Definition at line 99 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 99 of file F02DetectorConstruction.hh
Referenced by F02DetectorConstruction(), and ~F02DetectorConstruction().
G4Cache<F02ElectricFieldSetup*> F02DetectorConstruction::fEmFieldSetup private
Definition at line 101 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 101 of file F02DetectorConstruction.hh
Referenced by ConstructSDandField().
G4LogicalVolume* F02DetectorConstruction::fLogicAbsorber private
Definition at line 108 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 108 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), ConstructSDandField(), GetLogicalAbsorber(), and SetAbsorberMaterial().
G4LogicalVolume* F02DetectorConstruction::fLogicWorld private
Definition at line 104 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 104 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and SetWorldMaterial().
G4VPhysicalVolume* F02DetectorConstruction::fPhysiAbsorber private
Definition at line 109 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 109 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetAbsorber().
G4VPhysicalVolume* F02DetectorConstruction::fPhysiWorld private
Definition at line 105 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 105 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), and GetPhysiWorld().
G4Tubs* F02DetectorConstruction::fSolidAbsorber private
Definition at line 107 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 107 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4Tubs* F02DetectorConstruction::fSolidWorld private
Definition at line 103 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 103 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter().
G4bool F02DetectorConstruction::fWorldChanged private
Definition at line 114 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 114 of file F02DetectorConstruction.hh
Referenced by SetWorldSizeR(), and SetWorldSizeZ().
G4Material* F02DetectorConstruction::fWorldMaterial private
Definition at line 119 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 119 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), DefineMaterials(), GetWorldMaterial(), PrintCalorParameters(), and SetWorldMaterial().
G4double F02DetectorConstruction::fWorldSizeR private
Definition at line 120 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 120 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), F02DetectorConstruction(), GetWorldSizeR(), PrintCalorParameters(), and SetWorldSizeR().
G4double F02DetectorConstruction::fWorldSizeZ private
Definition at line 121 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 121 of file F02DetectorConstruction.hh
Referenced by ConstructCalorimeter(), F02DetectorConstruction(), GetWorldSizeZ(), PrintCalorParameters(), and SetWorldSizeZ().
G4double F02DetectorConstruction::fZAbsorber private
Definition at line 116 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 116 of file F02DetectorConstruction.hh
Referenced by ComputeCalorParameters(), ConstructCalorimeter(), F02DetectorConstruction(), GetAbsorberZpos(), PrintCalorParameters(), and SetAbsorberZpos().
G4double F02DetectorConstruction::fZEndAbs private
Definition at line 117 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 117 of file F02DetectorConstruction.hh
Referenced by ComputeCalorParameters(), and GetZEndAbs().
G4double F02DetectorConstruction::fZStartAbs private
Definition at line 117 of file F02DetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 117 of file F02DetectorConstruction.hh
Referenced by ComputeCalorParameters(), and GetZStartAbs().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field02/include/F02DetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field02/src/F02DetectorConstruction.cc