ECCE @ EIC Software: SteppingAction Class Reference
SteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/SteppingAction.hh>
Inherits G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, RunInitObserver, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, RunInitObserver, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, G4UserSteppingAction, and G4UserSteppingAction.
Public Member Functions
SteppingAction (DetectorConstruction *, EventAction *)
~SteppingAction ()
void UserSteppingAction (const G4Step *)
G4double BirksAttenuation (const G4Step *)
SteppingAction (RunAction *, const DetectorConstruction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
void UserSteppingAction (const G4Step *)
SteppingAction (RunAction *, DetectorConstruction *)
~SteppingAction ()
void UserSteppingAction (const G4Step *)
SteppingAction (AnalysisManager *analysis)
~SteppingAction ()
void UserSteppingAction (const G4Step *aStep)
SteppingAction (DetectorConstruction *, EventAction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, EventAction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, EventAction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, EventAction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (EventAction *)
~SteppingAction () override
void UserSteppingAction (const G4Step *) override
SteppingAction (DetectorConstruction *, EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, RunAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (RunAction *, HistoManager *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (RunAction *, EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
G4double BirksAttenuation (const G4Step *)
SteppingAction (EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (RunAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, RunAction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (TrackingAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
virtual void Initialize ()
SteppingAction (DetectorConstruction *fpDet)
~SteppingAction () override
void UserSteppingAction (const G4Step *step) override
SteppingAction ()
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
void UserSteppingAction (const G4Step *)
SteppingAction (RunAction *)
~SteppingAction ()
void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
virtual void Initialize ()
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (EventAction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
G4double GetStoppingPower ()
SteppingAction (EventAction *, DetectorConstruction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, TrackingAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, TrackingAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction ()
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, PrimaryGeneratorAction *, RunAction *)
virtual ~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
SteppingAction (DetectorConstruction *, EventAction *)
~SteppingAction ()
virtual void UserSteppingAction (const G4Step *)
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Member Functions
SteppingAction & operator= (const SteppingAction &right)
SteppingAction (const SteppingAction &)
void SetupFlags (const G4Step *step)
DNAVolumeType SetupVolumeType (const G4VPhysicalVolume *pPhyVolume)
G4bool CheckAndProcessDNAHit (G4double x, G4double y, G4double z, G4double edep)
Private Attributes
DetectorConstruction * detector
EventAction * eventAct
G4bool first
G4LogicalVolume * lvol_world
G4LogicalVolume * lvol_module
G4LogicalVolume * lvol_layer
G4LogicalVolume * lvol_fiber
RunAction * fRun
const DetectorConstruction * fDetector
const CellParameterisation * fMyCellParameterisation
DetectorConstruction * fDetector
G4double fXIn
G4double fYIn
G4double fZIn
G4double fThetaIn
G4double fPhiIn
G4double fE
AnalysisManager * analysis
G4TrackVector * fSecondary
EventAction * fEventAction
G4NIELCalculator * fNIELCalculator
RunAction * fRunAction
HistoManager * fHistoManager
RunAction * fRunaction
EventAction * fEventaction
EventAction * fEventAct
G4double fMuonMass
HistoManager * fHisto
std::map< G4ParticleDefinition
*, G4int > fParticleFlag
TrackingAction * fTrackingAction
EventAction * fpEventAction
DetectorConstruction * fpDetector
DNAVolumeType fVolumeType
EventAction * fpEventaction
G4Region * fRegion
G4double fSumOfStepLength
G4double fLength
G4double fDeltaE
G4double fTotalStoppingPower
G4double fTotalNumberOfSteps
G4double fDepositedEnergy
G4int fNumberOfSteps
DetectorConstruction * fDetectorConstruction
TrackingAction * fTrackAction
G4VPhysicalVolume * fWall
G4VPhysicalVolume * fCavity
G4double fTrackSegm
G4ThreeVector fDirectionIn
G4int fVerbose
PrimaryGeneratorAction * fPrimary
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 43 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 43 of file SteppingAction.hh
Constructor & Destructor Documentation
SteppingAction::SteppingAction (DetectorConstruction * det, EventAction * evt)
Definition at line 39 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 39 of file SteppingAction.cc
References first, lvol_fiber, lvol_layer, lvol_module, and lvol_world.
SteppingAction::~SteppingAction ()
Definition at line 48 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file SteppingAction.cc
SteppingAction::SteppingAction (RunAction * run, const DetectorConstruction * det)
Definition at line 48 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 48 of file SteppingAction.cc
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction ()
Definition at line 45 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 45 of file SteppingAction.cc
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (RunAction * run, DetectorConstruction * det)
Definition at line 35 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 35 of file SteppingAction.cc
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (AnalysisManager * analysis)
Definition at line 40 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 40 of file SteppingAction.cc
References analysis, and fSecondary.
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (EventAction * event)
Definition at line 47 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file SteppingAction.cc
References fNIELCalculator.
SteppingAction::~SteppingAction () override
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * det, RunAction * RuAct)
Definition at line 46 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.cc
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (RunAction * RuAct, HistoManager * Hist)
Definition at line 41 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file SteppingAction.cc
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (RunAction * RA, EventAction * EA)
Definition at line 44 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 44 of file SteppingAction.cc
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * det)
Definition at line 42 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 42 of file SteppingAction.cc
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (RunAction * RuAct)
Definition at line 41 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 41 of file SteppingAction.cc
References fMuonMass, G4ParticleDefinition::GetPDGMass(), and G4MuonPlus::MuonPlus().
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * , RunAction *)
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction ()
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (const SteppingAction &) private
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (TrackingAction * TrAct)
Definition at line 42 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 42 of file SteppingAction.cc
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * fpDet)
SteppingAction::~SteppingAction () override
SteppingAction::SteppingAction ()
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (RunAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (EventAction *)
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (EventAction * event, DetectorConstruction * detector)
Definition at line 46 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.cc
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * det, TrackingAction * TrAct)
Definition at line 47 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file SteppingAction.cc
References fDirectionIn, first, and fTrackSegm.
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * , TrackingAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction ()
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (DetectorConstruction * det, PrimaryGeneratorAction * prim, RunAction * ruAct)
Definition at line 43 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 43 of file SteppingAction.cc
virtual SteppingAction::~SteppingAction () virtual
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
SteppingAction::~SteppingAction ()
SteppingAction::SteppingAction (DetectorConstruction * , EventAction *)
SteppingAction::~SteppingAction ()
Member Function Documentation
G4double SteppingAction::BirksAttenuation (const G4Step * aStep)
Definition at line 94 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 94 of file SteppingAction.cc
References charge, G4IonisParamMat::GetBirksConstant(), G4Track::GetDefinition(), G4Material::GetIonisation(), G4Track::GetMaterial(), G4ParticleDefinition::GetPDGCharge(), G4Step::GetStepLength(), G4Step::GetTotalEnergyDeposit(), G4Step::GetTrack(), and material().
G4double SteppingAction::BirksAttenuation (const G4Step *)
G4bool SteppingAction::CheckAndProcessDNAHit (G4double x, G4double y, G4double z, G4double edep) private
Definition at line 110 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 110 of file SteppingAction.cc
References EventAction::AddEdepToNucleotide(), fpDetector, fpEventAction, DetectorConstruction::GetBarycenterList(), DetectorConstruction::GetMoleculeList(), and DetectorConstruction::GetPDBlib().
G4double SteppingAction::GetStoppingPower () inline
Definition at line 46 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.hh
References fTotalStoppingPower.
void SteppingAction::Initialize () virtual
Implements RunInitObserver.
Definition at line 58 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 58 of file SteppingAction.cc
References fpEventAction, and G4EventManager::GetEventManager().
virtual void SteppingAction::Initialize () virtual
Implements RunInitObserver.
SteppingAction& SteppingAction::operator= (const SteppingAction & right) private
void SteppingAction::SetupFlags (const G4Step * step) private
Definition at line 142 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 142 of file SteppingAction.cc
References fVolumeType, G4Step::GetPreStepPoint(), and SetupVolumeType().
DNAVolumeType SteppingAction::SetupVolumeType (const G4VPhysicalVolume * pPhyVolume) private
Definition at line 150 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 150 of file SteppingAction.cc
References FatalException, fpDetector, G4Exception(), DetectorConstruction::GetGeoDataMap(), G4VPhysicalVolume::GetName(), and it.
Referenced by SetupFlags().
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
void SteppingAction::UserSteppingAction (const G4Step * step) override virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
void SteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
void SteppingAction::UserSteppingAction (const G4Step * step) virtual
if (edep == 0.) return;
Reimplemented from G4UserSteppingAction.
Definition at line 53 of file SteppingAction.cc.
View newest version in sPHENIX GitHub at line 53 of file SteppingAction.cc
References detector, edep, eventAct, first, G4VTouchable::GetCopyNumber(), G4VPhysicalVolume::GetLogicalVolume(), DetectorConstruction::GetLvolFiber(), DetectorConstruction::GetLvolLayer(), DetectorConstruction::GetLvolModule(), DetectorConstruction::GetLvolWorld(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), G4StepPoint::GetTouchableHandle(), G4VTouchable::GetVolume(), lvol_fiber, lvol_layer, lvol_module, lvol_world, and EventAction::SumDeStep().
void SteppingAction::UserSteppingAction (const G4Step *) override virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
virtual void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
void SteppingAction::UserSteppingAction (const G4Step *) virtual
Reimplemented from G4UserSteppingAction.
Member Data Documentation
AnalysisManager* SteppingAction::analysis private
Definition at line 51 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file SteppingAction.hh
Referenced by SteppingAction().
DetectorConstruction* SteppingAction::detector private
Definition at line 54 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file SteppingAction.hh
Referenced by UserSteppingAction().
EventAction* SteppingAction::eventAct private
Definition at line 55 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file SteppingAction.hh
Referenced by UserSteppingAction().
G4VPhysicalVolume * SteppingAction::fCavity private
Definition at line 61 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file SteppingAction.hh
G4double SteppingAction::fDeltaE private
Definition at line 46 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.hh
G4double SteppingAction::fDepositedEnergy private
Definition at line 46 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.hh
DetectorConstruction* SteppingAction::fDetector private
Definition at line 52 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file SteppingAction.hh
DetectorConstruction * SteppingAction::fDetector private
Definition at line 55 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file SteppingAction.hh
DetectorConstruction* SteppingAction::fDetectorConstruction private
Definition at line 56 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file SteppingAction.hh
G4ThreeVector SteppingAction::fDirectionIn private
Definition at line 64 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 64 of file SteppingAction.hh
Referenced by SteppingAction().
G4double SteppingAction::fE private
Definition at line 58 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file SteppingAction.hh
EventAction* SteppingAction::fEventAct private
Definition at line 56 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file SteppingAction.hh
EventAction* SteppingAction::fEventaction private
Definition at line 54 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file SteppingAction.hh
EventAction * SteppingAction::fEventAction private
Definition at line 56 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file SteppingAction.hh
HistoManager* SteppingAction::fHisto private
Definition at line 67 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 67 of file SteppingAction.hh
HistoManager* SteppingAction::fHistoManager private
Definition at line 54 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file SteppingAction.hh
G4bool SteppingAction::first private
Definition at line 57 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file SteppingAction.hh
Referenced by SteppingAction(), and UserSteppingAction().
G4double SteppingAction::fLength private
Definition at line 46 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.hh
G4double SteppingAction::fMuonMass private
Definition at line 53 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file SteppingAction.hh
Referenced by SteppingAction().
const CellParameterisation* SteppingAction::fMyCellParameterisation private
Definition at line 56 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file SteppingAction.hh
G4NIELCalculator* SteppingAction::fNIELCalculator private
Definition at line 53 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file SteppingAction.hh
Referenced by SteppingAction().
G4int SteppingAction::fNumberOfSteps private
Definition at line 53 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file SteppingAction.hh
std::map<G4ParticleDefinition*,G4int> SteppingAction::fParticleFlag private
Definition at line 53 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file SteppingAction.hh
DetectorConstruction * SteppingAction::fpDetector private
Definition at line 48 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 48 of file SteppingAction.hh
Referenced by CheckAndProcessDNAHit(), and SetupVolumeType().
EventAction* SteppingAction::fpEventaction private
Definition at line 57 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file SteppingAction.hh
EventAction * SteppingAction::fpEventAction private
Definition at line 57 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file SteppingAction.hh
Referenced by CheckAndProcessDNAHit(), and Initialize().
G4double SteppingAction::fPhiIn private
Definition at line 57 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file SteppingAction.hh
PrimaryGeneratorAction* SteppingAction::fPrimary private
Definition at line 56 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file SteppingAction.hh
G4Region* SteppingAction::fRegion private
Definition at line 52 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file SteppingAction.hh
RunAction * SteppingAction::fRun private
Definition at line 54 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file SteppingAction.hh
RunAction* SteppingAction::fRunaction private
Definition at line 53 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 53 of file SteppingAction.hh
RunAction * SteppingAction::fRunAction private
Definition at line 54 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file SteppingAction.hh
G4TrackVector* SteppingAction::fSecondary private
Definition at line 52 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file SteppingAction.hh
Referenced by SteppingAction().
G4double SteppingAction::fSumOfStepLength private
Definition at line 46 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.hh
G4double SteppingAction::fThetaIn private
Definition at line 57 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 57 of file SteppingAction.hh
G4double SteppingAction::fTotalNumberOfSteps private
Definition at line 46 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.hh
G4double SteppingAction::fTotalStoppingPower private
Definition at line 46 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 46 of file SteppingAction.hh
Referenced by GetStoppingPower().
TrackingAction * SteppingAction::fTrackAction private
Definition at line 58 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file SteppingAction.hh
TrackingAction* SteppingAction::fTrackingAction private
Definition at line 52 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file SteppingAction.hh
G4double SteppingAction::fTrackSegm private
Definition at line 63 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 63 of file SteppingAction.hh
Referenced by SteppingAction().
G4int SteppingAction::fVerbose private
Definition at line 49 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 49 of file SteppingAction.hh
DNAVolumeType SteppingAction::fVolumeType private
Definition at line 49 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 49 of file SteppingAction.hh
Referenced by SetupFlags().
G4VPhysicalVolume * SteppingAction::fWall private
Definition at line 60 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file SteppingAction.hh
G4double SteppingAction::fXIn private
Definition at line 54 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 54 of file SteppingAction.hh
G4double SteppingAction::fYIn private
Definition at line 55 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 55 of file SteppingAction.hh
G4double SteppingAction::fZIn private
Definition at line 56 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 56 of file SteppingAction.hh
G4LogicalVolume* SteppingAction::lvol_fiber private
Definition at line 61 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 61 of file SteppingAction.hh
Referenced by SteppingAction(), and UserSteppingAction().
G4LogicalVolume* SteppingAction::lvol_layer private
Definition at line 60 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 60 of file SteppingAction.hh
Referenced by SteppingAction(), and UserSteppingAction().
G4LogicalVolume* SteppingAction::lvol_module private
Definition at line 59 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 59 of file SteppingAction.hh
Referenced by SteppingAction(), and UserSteppingAction().
G4LogicalVolume* SteppingAction::lvol_world private
Definition at line 58 of file SteppingAction.hh.
View newest version in sPHENIX GitHub at line 58 of file SteppingAction.hh
Referenced by SteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx01/shared/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx02/shared/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx03/shared/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/analysis/shared/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm4/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/icsd/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnaphysics/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/include/SteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/amsEcal/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/microbeam/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/microelectronics/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/nanobeam/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/advanced/radioprotection/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx01/shared/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx02/shared/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/AnaEx03/shared/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/analysis/shared/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm1/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm11/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm12/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm13/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm14/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm15/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm16/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm17/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm18/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm2/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm3/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm4/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm5/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm6/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm7/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/electromagnetic/TestEm9/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/exoticphysics/monopole/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr03/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr04/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr06/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/Hadr07/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/hadronic/NeutronSource/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/chem3/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/clustering/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnadamage1/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/dnaphysics/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/icsd/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/mfp/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/microdosimetry/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/neuron/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/pdb4dna/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/range/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/slowing/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/splitting/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/spower/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/svalue/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wholeNuclearDNA/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/dna/wvalue/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/medical/fanoCavity2/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/optical/OpNovice2/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/polarisation/Pol01/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/Activation/src/SteppingAction.cc
geant4/tree/geant4-10.6-release/examples/extended/radioactivedecay/rdecay02/src/SteppingAction.cc