ECCE @ EIC Software: G4tgrMaterial Class Reference
G4tgrMaterial Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrMaterial.hh>
Public Member Functions
G4tgrMaterial ()
virtual ~G4tgrMaterial ()
const G4String & GetName () const
G4double GetDensity () const
G4int GetNumberOfComponents () const
const G4String & GetType () const
virtual G4double GetA () const =0
virtual G4double GetZ () const =0
virtual const G4String & GetComponent (G4int i) const =0
virtual G4double GetFraction (G4int i)=0
G4double GetIonisationMeanExcitationEnergy () const
void SetIonisationMeanExcitationEnergy (G4double mee)
G4State GetState () const
void SetState (G4String val)
G4double GetTemperature () const
void SetTemperature (G4double val)
G4double GetPressure () const
void SetPressure (G4double val)
Protected Attributes
G4String theName
G4double theDensity
G4int theNoComponents
G4String theMateType
G4double theIonisationMeanExcitationEnergy
G4State theState
G4double theTemperature
G4double thePressure
Detailed Description
Definition at line 44 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 44 of file G4tgrMaterial.hh
Constructor & Destructor Documentation
G4tgrMaterial::G4tgrMaterial ()
Definition at line 39 of file G4tgrMaterial.cc.
View newest version in sPHENIX GitHub at line 39 of file G4tgrMaterial.cc
G4tgrMaterial::~G4tgrMaterial () virtual
Definition at line 49 of file G4tgrMaterial.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgrMaterial.cc
Member Function Documentation
virtual G4double G4tgrMaterial::GetA () const pure virtual
Implemented in G4tgrMaterialMixture, and G4tgrMaterialSimple.
Referenced by G4tgbMaterial::GetA().
virtual const G4String& G4tgrMaterial::GetComponent (G4int i) const pure virtual
Implemented in G4tgrMaterialSimple, and G4tgrMaterialMixture.
Referenced by G4tgbMaterialMixture::GetComponent().
G4double G4tgrMaterial::GetDensity () const inline
Definition at line 55 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 55 of file G4tgrMaterial.hh
References theDensity.
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4tgbMaterialSimple::BuildG4Material(), and G4tgbMaterial::GetDensity().
virtual G4double G4tgrMaterial::GetFraction (G4int i) pure virtual
Implemented in G4tgrMaterialSimple, and G4tgrMaterialMixture.
Referenced by G4tgbMaterialMixture::GetFraction().
G4double G4tgrMaterial::GetIonisationMeanExcitationEnergy () const inline
Definition at line 66 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 66 of file G4tgrMaterial.hh
References theIonisationMeanExcitationEnergy.
Referenced by G4tgbMaterialMgr::FindOrBuildG4Material().
const G4String& G4tgrMaterial::GetName (void) const inline
Definition at line 53 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 53 of file G4tgrMaterial.hh
References theName.
Referenced by G4tgrMaterialFactory::AddMaterialMixture(), G4tgrMaterialFactory::AddMaterialSimple(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4tgrMaterialFactory::DumpMaterialList(), G4tgbMaterial::GetName(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
G4int G4tgrMaterial::GetNumberOfComponents () const inline
Definition at line 58 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 58 of file G4tgrMaterial.hh
References theNoComponents.
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), G4tgbMaterialMixtureByNoAtoms::BuildG4Material(), G4tgrMaterialFactory::DumpMaterialList(), G4tgbMaterial::GetNumberOfMaterials(), and G4tgbMaterialMixtureByVolume::TransformToFractionsByWeight().
G4double G4tgrMaterial::GetPressure () const inline
Definition at line 78 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 78 of file G4tgrMaterial.hh
References thePressure.
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), and G4tgbMaterialMixtureByNoAtoms::BuildG4Material().
G4State G4tgrMaterial::GetState () const inline
Definition at line 72 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 72 of file G4tgrMaterial.hh
References theState.
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), and G4tgbMaterialMixtureByNoAtoms::BuildG4Material().
G4double G4tgrMaterial::GetTemperature () const inline
Definition at line 75 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 75 of file G4tgrMaterial.hh
References theTemperature.
Referenced by G4tgbMaterialMixtureByVolume::BuildG4Material(), G4tgbMaterialMixtureByWeight::BuildG4Material(), and G4tgbMaterialMixtureByNoAtoms::BuildG4Material().
const G4String& G4tgrMaterial::GetType () const inline
Definition at line 59 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 59 of file G4tgrMaterial.hh
References theMateType.
Referenced by G4tgbMaterialMgr::CopyMaterials(), G4tgrMaterialFactory::DumpMaterialList(), and G4tgbMaterial::GetType().
virtual G4double G4tgrMaterial::GetZ () const pure virtual
Implemented in G4tgrMaterialMixture, and G4tgrMaterialSimple.
Referenced by G4tgbMaterial::GetZ().
void G4tgrMaterial::SetIonisationMeanExcitationEnergy (G4double mee) inline
Definition at line 69 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 69 of file G4tgrMaterial.hh
References theIonisationMeanExcitationEnergy.
Referenced by G4tgrLineProcessor::ProcessLine().
void G4tgrMaterial::SetPressure (G4double val) inline
Definition at line 79 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 79 of file G4tgrMaterial.hh
References thePressure.
Referenced by G4tgrLineProcessor::ProcessLine().
void G4tgrMaterial::SetState (G4String val)
Definition at line 55 of file G4tgrMaterial.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgrMaterial.cc
References FatalErrorInArgument, G4Exception(), kStateGas, kStateLiquid, kStateSolid, kStateUndefined, and theState.
Referenced by G4tgrLineProcessor::ProcessLine().
void G4tgrMaterial::SetTemperature (G4double val) inline
Definition at line 76 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 76 of file G4tgrMaterial.hh
References theTemperature.
Referenced by G4tgrLineProcessor::ProcessLine().
Member Data Documentation
G4double G4tgrMaterial::theDensity protected
Definition at line 84 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 84 of file G4tgrMaterial.hh
Referenced by G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrMaterialSimple::G4tgrMaterialSimple(), GetDensity(), and operator<<().
G4double G4tgrMaterial::theIonisationMeanExcitationEnergy protected
Definition at line 87 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 87 of file G4tgrMaterial.hh
Referenced by GetIonisationMeanExcitationEnergy(), and SetIonisationMeanExcitationEnergy().
G4String G4tgrMaterial::theMateType protected
Definition at line 86 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 86 of file G4tgrMaterial.hh
Referenced by G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrMaterialSimple::G4tgrMaterialSimple(), and GetType().
G4String G4tgrMaterial::theName protected
Definition at line 83 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 83 of file G4tgrMaterial.hh
Referenced by G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrMaterialSimple::G4tgrMaterialSimple(), GetName(), and operator<<().
G4int G4tgrMaterial::theNoComponents protected
Definition at line 85 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 85 of file G4tgrMaterial.hh
Referenced by G4tgrMaterialMixture::G4tgrMaterialMixture(), G4tgrMaterialSimple::G4tgrMaterialSimple(), GetNumberOfComponents(), and operator<<().
G4double G4tgrMaterial::thePressure protected
Definition at line 90 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 90 of file G4tgrMaterial.hh
Referenced by GetPressure(), and SetPressure().
G4State G4tgrMaterial::theState protected
Definition at line 88 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 88 of file G4tgrMaterial.hh
Referenced by GetState(), and SetState().
G4double G4tgrMaterial::theTemperature protected
Definition at line 89 of file G4tgrMaterial.hh.
View newest version in sPHENIX GitHub at line 89 of file G4tgrMaterial.hh
Referenced by GetTemperature(), and SetTemperature().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrMaterial.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrMaterial.cc