ECCE @ EIC Software: G4AlphaPHPBuilder Class Reference
G4AlphaPHPBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4AlphaPHPBuilder.hh>
Public Member Functions
G4AlphaPHPBuilder ()
virtual ~G4AlphaPHPBuilder ()
virtual void Build (G4AlphaInelasticProcess *aP) finaloverride
virtual void Build (G4HadronElasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VAlphaBuilder
G4VAlphaBuilder ()=default
virtual ~G4VAlphaBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4double theMin
G4double theMax
G4ParticleHPInelastic * theParticlePHPModel
Detailed Description
Definition at line 46 of file G4AlphaPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 46 of file G4AlphaPHPBuilder.hh
Constructor & Destructor Documentation
G4AlphaPHPBuilder::G4AlphaPHPBuilder ()
Definition at line 34 of file G4AlphaPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 34 of file G4AlphaPHPBuilder.cc
References MeV, theMax, theMin, and theParticlePHPModel.
virtual G4AlphaPHPBuilder::~G4AlphaPHPBuilder () inline virtual
Definition at line 50 of file G4AlphaPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 50 of file G4AlphaPHPBuilder.hh
Member Function Documentation
void G4AlphaPHPBuilder::Build (G4AlphaInelasticProcess * aP) final override virtual
Implements G4VAlphaBuilder.
Definition at line 48 of file G4AlphaPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 48 of file G4AlphaPHPBuilder.cc
References G4HadronicProcess::AddDataSet(), G4Alpha::Alpha(), G4cout, G4endl, G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4VCrossSectionDataSet::SetMaxKinEnergy(), G4HadronicInteraction::SetMinEnergy(), G4VCrossSectionDataSet::SetMinKinEnergy(), theMax, theMin, and theParticlePHPModel.
void G4AlphaPHPBuilder::Build (G4HadronElasticProcess * aP) final override virtual
Implements G4VAlphaBuilder.
Definition at line 42 of file G4AlphaPHPBuilder.cc.
View newest version in sPHENIX GitHub at line 42 of file G4AlphaPHPBuilder.cc
References G4cout, and G4endl.
virtual void G4AlphaPHPBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 59 of file G4AlphaPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4AlphaPHPBuilder.hh
References theMax.
virtual void G4AlphaPHPBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 55 of file G4AlphaPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 55 of file G4AlphaPHPBuilder.hh
References theMin.
Member Data Documentation
G4double G4AlphaPHPBuilder::theMax private
Definition at line 68 of file G4AlphaPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4AlphaPHPBuilder.hh
Referenced by Build(), G4AlphaPHPBuilder(), and SetMaxEnergy().
G4double G4AlphaPHPBuilder::theMin private
Definition at line 67 of file G4AlphaPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4AlphaPHPBuilder.hh
Referenced by Build(), G4AlphaPHPBuilder(), and SetMinEnergy().
G4ParticleHPInelastic* G4AlphaPHPBuilder::theParticlePHPModel private
Definition at line 69 of file G4AlphaPHPBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4AlphaPHPBuilder.hh
Referenced by Build(), and G4AlphaPHPBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4AlphaPHPBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4AlphaPHPBuilder.cc