ECCE @ EIC Software: G4strstreambuf Class Reference
G4strstreambuf Class Reference
#include <geant4/tree/geant4-10.6-release/source/global/management/include/G4strstreambuf.hh>
Public Member Functions
G4strstreambuf ()
~G4strstreambuf ()
virtual G4int overflow (G4int c=EOF)
virtual G4int sync ()
void SetDestination (G4coutDestination *dest)
G4coutDestination * GetDestination () const
G4int ReceiveString ()
Private Member Functions
G4strstreambuf (const G4strstreambuf &)
G4strstreambuf & operator= (const G4strstreambuf &)
Private Attributes
char * buffer
G4int count
G4int size
G4coutDestination * destination
Detailed Description
Definition at line 57 of file G4strstreambuf.hh.
View newest version in sPHENIX GitHub at line 57 of file G4strstreambuf.hh
Constructor & Destructor Documentation
G4strstreambuf::G4strstreambuf ()
G4strstreambuf::~G4strstreambuf ()
G4strstreambuf::G4strstreambuf (const G4strstreambuf &) private
Member Function Documentation
G4coutDestination* G4strstreambuf::GetDestination () const inline
G4strstreambuf& G4strstreambuf::operator= (const G4strstreambuf &) private
virtual G4int G4strstreambuf::overflow (G4int c = EOF) virtual
G4int G4strstreambuf::ReceiveString () inline
void G4strstreambuf::SetDestination (G4coutDestination * dest)
Referenced by G4MTcoutDestination::G4MTcoutDestination(), G4UImanager::SetCoutDestination(), pyglobals::SetG4PyCoutDestination(), and G4coutFormatters::SetupStyleGlobally().
virtual G4int G4strstreambuf::sync () virtual
Member Data Documentation
char* G4strstreambuf::buffer private
Definition at line 77 of file G4strstreambuf.hh.
View newest version in sPHENIX GitHub at line 77 of file G4strstreambuf.hh
G4int G4strstreambuf::count private
Definition at line 78 of file G4strstreambuf.hh.
View newest version in sPHENIX GitHub at line 78 of file G4strstreambuf.hh
G4coutDestination* G4strstreambuf::destination private
Definition at line 79 of file G4strstreambuf.hh.
View newest version in sPHENIX GitHub at line 79 of file G4strstreambuf.hh
G4int G4strstreambuf::size private
Definition at line 78 of file G4strstreambuf.hh.
View newest version in sPHENIX GitHub at line 78 of file G4strstreambuf.hh
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/global/management/include/G4strstreambuf.hh