ECCE @ EIC Software: G4RDeIonisationSpectrum Class Reference
G4RDeIonisationSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDeIonisationSpectrum.hh>
Public Member Functions
G4RDeIonisationSpectrum ()
~G4RDeIonisationSpectrum ()
G4double Probability (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition *pd=0) const
G4double AverageEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition *pd=0) const
G4double SampleEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition *pd=0) const
G4double MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z=0, const G4ParticleDefinition *pd=0) const
G4double Excitation (G4int Z, G4double e) const
void PrintData () const
Public Member Functions inherited from G4RDVEnergySpectrum
G4RDVEnergySpectrum ()
virtual ~G4RDVEnergySpectrum ()
Private Member Functions
G4double IntSpectrum (G4double xMin, G4double xMax, const G4DataVector &p) const
G4double AverageValue (G4double xMin, G4double xMax, const G4DataVector &p) const
G4double Function (G4double x, const G4DataVector &p) const
G4RDeIonisationSpectrum (const G4RDeIonisationSpectrum &)
G4RDeIonisationSpectrum & operator= (const G4RDeIonisationSpectrum &right)
Private Attributes
G4RDeIonisationParameters * theParam
G4double lowestE
G4double factor
G4int iMax
G4int verbose
Detailed Description
Definition at line 63 of file G4RDeIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 63 of file G4RDeIonisationSpectrum.hh
Constructor & Destructor Documentation
G4RDeIonisationSpectrum::G4RDeIonisationSpectrum ()
Definition at line 59 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 59 of file G4RDeIonisationSpectrum.cc
References theParam.
G4RDeIonisationSpectrum::~G4RDeIonisationSpectrum ()
Definition at line 69 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 69 of file G4RDeIonisationSpectrum.cc
References theParam.
G4RDeIonisationSpectrum::G4RDeIonisationSpectrum (const G4RDeIonisationSpectrum &) private
Member Function Documentation
G4double G4RDeIonisationSpectrum::AverageEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition * pd = 0) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 161 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 161 of file G4RDeIonisationSpectrum.cc
References AverageValue(), G4InuclSpecialFunctions::bindingEnergy(), source.hepunit::electron_mass_c2, energy, Function(), Acts::UnitConstants::g, G4cout, G4endl, iMax, G4RDAtomicTransitionManager::Instance(), IntSpectrum(), keV, lowestE, max, MaxEnergyOfSecondaries(), MeV, min, G4RDeIonisationParameters::Parameter(), theParam, G4InuclParticleNames::tm, verbose, x, x1, and x2.
G4double G4RDeIonisationSpectrum::AverageValue (G4double xMin, G4double xMax, const G4DataVector & p) const private
Definition at line 485 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 485 of file G4RDeIonisationSpectrum.cc
References dx, iMax, max, sum, x1, x2, y1, and y2.
Referenced by AverageEnergy().
G4double G4RDeIonisationSpectrum::Excitation (G4int Z, G4double e) const inline virtual
Implements G4RDVEnergySpectrum.
Definition at line 128 of file G4RDeIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 128 of file G4RDeIonisationSpectrum.hh
References G4RDeIonisationParameters::Excitation(), and theParam.
G4double G4RDeIonisationSpectrum::Function (G4double x, const G4DataVector & p) const inline private
Definition at line 118 of file G4RDeIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 118 of file G4RDeIonisationSpectrum.hh
References f, iMax, and x.
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4double G4RDeIonisationSpectrum::IntSpectrum (G4double xMin, G4double xMax, const G4DataVector & p) const private
Definition at line 401 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 401 of file G4RDeIonisationSpectrum.cc
References dx, G4cout, G4endl, iMax, max, sum, x1, x2, y1, and y2.
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4double G4RDeIonisationSpectrum::MaxEnergyOfSecondaries (G4double kineticEnergy, G4int Z = 0, const G4ParticleDefinition * pd = 0) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 569 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 569 of file G4RDeIonisationSpectrum.cc
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4RDeIonisationSpectrum& G4RDeIonisationSpectrum::operator= (const G4RDeIonisationSpectrum & right) private
void G4RDeIonisationSpectrum::PrintData (void) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 564 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 564 of file G4RDeIonisationSpectrum.cc
References G4RDeIonisationParameters::PrintData(), and theParam.
G4double G4RDeIonisationSpectrum::Probability (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition * pd = 0) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 75 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 75 of file G4RDeIonisationSpectrum.cc
References G4InuclSpecialFunctions::bindingEnergy(), source.hepunit::electron_mass_c2, energy, Function(), Acts::UnitConstants::g, G4cout, G4endl, iMax, G4RDAtomicTransitionManager::Instance(), IntSpectrum(), keV, lowestE, max, MaxEnergyOfSecondaries(), min, G4RDeIonisationParameters::Parameter(), theParam, G4InuclParticleNames::tm, verbose, x, x1, and x2.
G4double G4RDeIonisationSpectrum::SampleEnergy (G4int Z, G4double tMin, G4double tMax, G4double kineticEnergy, G4int shell, const G4ParticleDefinition * pd = 0) const virtual
Implements G4RDVEnergySpectrum.
Definition at line 243 of file G4RDeIonisationSpectrum.cc.
View newest version in sPHENIX GitHub at line 243 of file G4RDeIonisationSpectrum.cc
References G4InuclSpecialFunctions::bindingEnergy(), dx, source.hepunit::electron_mass_c2, energy, factor, Function(), Acts::UnitConstants::g, G4cout, G4endl, G4UniformRand, iMax, G4RDAtomicTransitionManager::Instance(), IntSpectrum(), keV, lowestE, max, MaxEnergyOfSecondaries(), MeV, min, G4RDeIonisationParameters::Parameter(), theParam, G4InuclParticleNames::tm, verbose, x, x1, x2, z1, and z2.
Member Data Documentation
G4double G4RDeIonisationSpectrum::factor private
Definition at line 112 of file G4RDeIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 112 of file G4RDeIonisationSpectrum.hh
Referenced by SampleEnergy().
G4int G4RDeIonisationSpectrum::iMax private
Definition at line 113 of file G4RDeIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 113 of file G4RDeIonisationSpectrum.hh
Referenced by AverageEnergy(), AverageValue(), Function(), IntSpectrum(), Probability(), and SampleEnergy().
G4double G4RDeIonisationSpectrum::lowestE private
Definition at line 111 of file G4RDeIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 111 of file G4RDeIonisationSpectrum.hh
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
G4RDeIonisationParameters* G4RDeIonisationSpectrum::theParam private
Definition at line 110 of file G4RDeIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 110 of file G4RDeIonisationSpectrum.hh
Referenced by AverageEnergy(), Excitation(), G4RDeIonisationSpectrum(), PrintData(), Probability(), SampleEnergy(), and ~G4RDeIonisationSpectrum().
G4int G4RDeIonisationSpectrum::verbose private
Definition at line 114 of file G4RDeIonisationSpectrum.hh.
View newest version in sPHENIX GitHub at line 114 of file G4RDeIonisationSpectrum.hh
Referenced by AverageEnergy(), Probability(), and SampleEnergy().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDeIonisationSpectrum.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDeIonisationSpectrum.cc