ECCE @ EIC Software: STCyclotronRunAction Class Reference
STCyclotronRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/include/STCyclotronRunAction.hh>
Public Member Functions
STCyclotronRunAction (STCyclotronDetectorConstruction *)
virtual ~STCyclotronRunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
virtual G4Run * GenerateRun ()
void SetIrradiationTime (G4double)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
STCyclotronRun * fRun
STCyclotronRunActionMessenger * fMessenger
G4double fIn
G4double fOut
G4double fIrradiationTime
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Definition at line 44 of file STCyclotronRunAction.hh.
View newest version in sPHENIX GitHub at line 44 of file STCyclotronRunAction.hh
Constructor & Destructor Documentation
STCyclotronRunAction::STCyclotronRunAction (STCyclotronDetectorConstruction *)
Definition at line 52 of file STCyclotronRunAction.cc.
View newest version in sPHENIX GitHub at line 52 of file STCyclotronRunAction.cc
References fIn, fIrradiationTime, fMessenger, fOut, G4cout, G4endl, and G4ToolsAnalysisManager::Instance().
STCyclotronRunAction::~STCyclotronRunAction () virtual
Definition at line 100 of file STCyclotronRunAction.cc.
View newest version in sPHENIX GitHub at line 100 of file STCyclotronRunAction.cc
References fMessenger, and G4ToolsAnalysisManager::Instance().
Member Function Documentation
void STCyclotronRunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 112 of file STCyclotronRunAction.cc.
View newest version in sPHENIX GitHub at line 112 of file STCyclotronRunAction.cc
References G4RunManager::GetRunManager(), G4ToolsAnalysisManager::Instance(), and G4RunManager::SetRandomNumberStore().
void STCyclotronRunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 122 of file STCyclotronRunAction.cc.
View newest version in sPHENIX GitHub at line 122 of file STCyclotronRunAction.cc
References STCyclotronRun::EndOfRun(), fIrradiationTime, fRun, G4ToolsAnalysisManager::Instance(), and G4UserRunAction::isMaster.
G4Run * STCyclotronRunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 106 of file STCyclotronRunAction.cc.
View newest version in sPHENIX GitHub at line 106 of file STCyclotronRunAction.cc
References fRun.
void STCyclotronRunAction::SetIrradiationTime (G4double time)
Definition at line 131 of file STCyclotronRunAction.cc.
View newest version in sPHENIX GitHub at line 131 of file STCyclotronRunAction.cc
References fIrradiationTime, G4cout, G4endl, and Acts::VectorHelpers::time().
Member Data Documentation
G4double STCyclotronRunAction::fIn private
Definition at line 63 of file STCyclotronRunAction.hh.
View newest version in sPHENIX GitHub at line 63 of file STCyclotronRunAction.hh
Referenced by STCyclotronRunAction().
G4double STCyclotronRunAction::fIrradiationTime private
Definition at line 66 of file STCyclotronRunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file STCyclotronRunAction.hh
Referenced by EndOfRunAction(), SetIrradiationTime(), and STCyclotronRunAction().
STCyclotronRunActionMessenger* STCyclotronRunAction::fMessenger private
Definition at line 59 of file STCyclotronRunAction.hh.
View newest version in sPHENIX GitHub at line 59 of file STCyclotronRunAction.hh
Referenced by STCyclotronRunAction(), and ~STCyclotronRunAction().
G4double STCyclotronRunAction::fOut private
Definition at line 63 of file STCyclotronRunAction.hh.
View newest version in sPHENIX GitHub at line 63 of file STCyclotronRunAction.hh
Referenced by STCyclotronRunAction().
STCyclotronRun* STCyclotronRunAction::fRun private
Definition at line 58 of file STCyclotronRunAction.hh.
View newest version in sPHENIX GitHub at line 58 of file STCyclotronRunAction.hh
Referenced by EndOfRunAction(), and GenerateRun().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/include/STCyclotronRunAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/STCyclotron/src/STCyclotronRunAction.cc