ECCE @ EIC Software: CCalVOrganization Class Reference
CCalVOrganization Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalVOrganization.hh>
Public Member Functions
CCalVOrganization ()
virtual ~CCalVOrganization ()
virtual unsigned int GetUnitID (const G4Step *aStep) const =0
virtual G4int Levels (const G4Step *) const
virtual void DetectorLevel (const G4Step *, G4int &, G4int *, G4String *) const
Protected Attributes
CCaloOrganization theOrg
Detailed Description
Definition at line 36 of file CCalVOrganization.hh.
View newest version in sPHENIX GitHub at line 36 of file CCalVOrganization.hh
Constructor & Destructor Documentation
CCalVOrganization::CCalVOrganization () inline
Definition at line 39 of file CCalVOrganization.hh.
View newest version in sPHENIX GitHub at line 39 of file CCalVOrganization.hh
virtual CCalVOrganization::~CCalVOrganization () inline virtual
Definition at line 40 of file CCalVOrganization.hh.
View newest version in sPHENIX GitHub at line 40 of file CCalVOrganization.hh
Member Function Documentation
void CCalVOrganization::DetectorLevel (const G4Step * aStep, G4int & level, G4int * copyno, G4String * name) const virtual
Definition at line 43 of file CCalVOrganization.cc.
View newest version in sPHENIX GitHub at line 43 of file CCalVOrganization.cc
References G4VPhysicalVolume::GetName(), G4Step::GetPreStepPoint(), G4TouchableHistory::GetReplicaNumber(), G4StepPoint::GetTouchable(), and G4TouchableHistory::GetVolume().
virtual unsigned int CCalVOrganization::GetUnitID (const G4Step * aStep) const pure virtual
Implemented in CCalEcalOrganization, and CCalHcalOrganization.
Referenced by CCaloSD::getStepInfo().
G4int CCalVOrganization::Levels (const G4Step * aStep) const virtual
Definition at line 34 of file CCalVOrganization.cc.
View newest version in sPHENIX GitHub at line 34 of file CCalVOrganization.cc
References G4TouchableHistory::GetHistoryDepth(), G4Step::GetPreStepPoint(), and G4StepPoint::GetTouchable().
Member Data Documentation
CCaloOrganization CCalVOrganization::theOrg protected
Definition at line 47 of file CCalVOrganization.hh.
View newest version in sPHENIX GitHub at line 47 of file CCalVOrganization.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalVOrganization.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalVOrganization.cc