ECCE @ EIC Software: G4Mag_SpinEqRhs Class Reference
G4Mag_SpinEqRhs Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4Mag_SpinEqRhs.hh>
Public Member Functions
G4Mag_SpinEqRhs (G4MagneticField *MagField)
~G4Mag_SpinEqRhs ()
void SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double mass)
void EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const
void SetAnomaly (G4double a)
G4double GetAnomaly () const
Public Member Functions inherited from G4Mag_EqRhs
G4Mag_EqRhs (G4MagneticField *magField)
virtual ~G4Mag_EqRhs ()
G4double FCof () const
Public Member Functions inherited from G4EquationOfMotion
G4EquationOfMotion (G4Field *Field)
virtual ~G4EquationOfMotion ()
void RightHandSide (const G4double y[], G4double dydx[]) const
void EvaluateRhsReturnB (const G4double y[], G4double dydx[], G4double Field[]) const
void GetFieldValue (const G4double Point[4], G4double Field[]) const
const G4Field * GetFieldObj () const
G4Field * GetFieldObj ()
void SetFieldObj (G4Field *pField)
Private Attributes
G4double charge =0.0
G4double mass =0.0
G4double magMoment =0.0
G4double spin =0.0
G4double omegac =0.0
G4double anomaly =0.0011659208
G4double beta =0.0
G4double gamma =0.0
Detailed Description
Definition at line 45 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 45 of file G4Mag_SpinEqRhs.hh
Constructor & Destructor Documentation
G4Mag_SpinEqRhs::G4Mag_SpinEqRhs (G4MagneticField * MagField)
Definition at line 37 of file G4Mag_SpinEqRhs.cc.
View newest version in sPHENIX GitHub at line 37 of file G4Mag_SpinEqRhs.cc
G4Mag_SpinEqRhs::~G4Mag_SpinEqRhs ()
Definition at line 42 of file G4Mag_SpinEqRhs.cc.
View newest version in sPHENIX GitHub at line 42 of file G4Mag_SpinEqRhs.cc
Member Function Documentation
void G4Mag_SpinEqRhs::EvaluateRhsGivenB (const G4double y[], const G4double B[3], G4double dydx[]) const virtual
Implements G4Mag_EqRhs.
Definition at line 74 of file G4Mag_SpinEqRhs.cc.
View newest version in sPHENIX GitHub at line 74 of file G4Mag_SpinEqRhs.cc
References anomaly, beta, charge, CLHEP::Hep3Vector::cross(), G4Mag_EqRhs::FCof(), gamma, CLHEP::Hep3Vector::mag2(), omegac, sqr(), Acts::UnitConstants::u, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double G4Mag_SpinEqRhs::GetAnomaly () const inline
Definition at line 64 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 64 of file G4Mag_SpinEqRhs.hh
References anomaly.
void G4Mag_SpinEqRhs::SetAnomaly (G4double a) inline
Definition at line 63 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 63 of file G4Mag_SpinEqRhs.hh
References a, and anomaly.
void G4Mag_SpinEqRhs::SetChargeMomentumMass (G4ChargeState particleCharge, G4double MomentumXc, G4double mass) virtual
Reimplemented from G4Mag_EqRhs.
Definition at line 47 of file G4Mag_SpinEqRhs.cc.
View newest version in sPHENIX GitHub at line 47 of file G4Mag_SpinEqRhs.cc
References kdfinder::abs(), anomaly, beta, source.hepunit::c_light, source.hepunit::c_squared, charge, E, eplus, gamma, G4ChargeState::GetCharge(), G4ChargeState::GetMagneticDipoleMoment(), G4ChargeState::GetSpin(), source.hepunit::hbar_Planck, magMoment, mass, omegac, G4Mag_EqRhs::SetChargeMomentumMass(), spin, and sqr().
Member Data Documentation
G4double G4Mag_SpinEqRhs::anomaly =0.0011659208 private
Definition at line 70 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 70 of file G4Mag_SpinEqRhs.hh
Referenced by EvaluateRhsGivenB(), GetAnomaly(), SetAnomaly(), and SetChargeMomentumMass().
G4double G4Mag_SpinEqRhs::beta =0.0 private
Definition at line 71 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Mag_SpinEqRhs.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4Mag_SpinEqRhs::charge =0.0 private
Definition at line 69 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 69 of file G4Mag_SpinEqRhs.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4Mag_SpinEqRhs::gamma =0.0 private
Definition at line 71 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Mag_SpinEqRhs.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4Mag_SpinEqRhs::magMoment =0.0 private
Definition at line 69 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 69 of file G4Mag_SpinEqRhs.hh
Referenced by SetChargeMomentumMass().
G4double G4Mag_SpinEqRhs::mass =0.0 private
Definition at line 69 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 69 of file G4Mag_SpinEqRhs.hh
Referenced by SetChargeMomentumMass().
G4double G4Mag_SpinEqRhs::omegac =0.0 private
Definition at line 70 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 70 of file G4Mag_SpinEqRhs.hh
Referenced by EvaluateRhsGivenB(), and SetChargeMomentumMass().
G4double G4Mag_SpinEqRhs::spin =0.0 private
Definition at line 69 of file G4Mag_SpinEqRhs.hh.
View newest version in sPHENIX GitHub at line 69 of file G4Mag_SpinEqRhs.hh
Referenced by SetChargeMomentumMass().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4Mag_SpinEqRhs.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4Mag_SpinEqRhs.cc