ECCE @ EIC Software: G4RDBremsstrahlungParameters Class Reference
G4RDBremsstrahlungParameters Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDBremsstrahlungParameters.hh>
Public Member Functions
G4RDBremsstrahlungParameters (const G4String &name, size_t num, G4int minZ=1, G4int maxZ=99)
~G4RDBremsstrahlungParameters ()
G4double Parameter (G4int parameterIndex, G4int Z, G4double energy) const
G4double ParameterC (G4int index) const
void PrintData () const
Private Member Functions
G4RDBremsstrahlungParameters (const G4RDBremsstrahlungParameters &)
G4RDBremsstrahlungParameters & operator= (const G4RDBremsstrahlungParameters &right)
void LoadData (const G4String &name)
Private Attributes
std::map< G4int,
G4RDVEMDataSet *, std::less
< G4int > > param
G4DataVector paramC
G4DataVector activeZ
G4int zMin
G4int zMax
size_t length
Detailed Description
Definition at line 61 of file G4RDBremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 61 of file G4RDBremsstrahlungParameters.hh
Constructor & Destructor Documentation
G4RDBremsstrahlungParameters::G4RDBremsstrahlungParameters (const G4String & name, size_t num, G4int minZ = 1, G4int maxZ = 99)
Definition at line 51 of file G4RDBremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 51 of file G4RDBremsstrahlungParameters.cc
References LoadData().
G4RDBremsstrahlungParameters::~G4RDBremsstrahlungParameters ()
Definition at line 61 of file G4RDBremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 61 of file G4RDBremsstrahlungParameters.cc
References activeZ, param, paramC, and pos().
G4RDBremsstrahlungParameters::G4RDBremsstrahlungParameters (const G4RDBremsstrahlungParameters &) private
Member Function Documentation
void G4RDBremsstrahlungParameters::LoadData (const G4String & name) private
Definition at line 102 of file G4RDBremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 102 of file G4RDBremsstrahlungParameters.cc
References a, activeZ, G4DataVector::contains(), e, FatalException, G4Exception(), G4Material::GetElementVector(), G4Material::GetMaterialTable(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), G4Material::GetTotNbOfElectPerVolume(), G4Element::GetZ(), k, length, m, material(), mm, G4TrackingService::nMaterials, param, paramC, sum, x, Z, and z.
Referenced by G4RDBremsstrahlungParameters().
G4RDBremsstrahlungParameters& G4RDBremsstrahlungParameters::operator= (const G4RDBremsstrahlungParameters & right) private
G4double G4RDBremsstrahlungParameters::Parameter (G4int parameterIndex, G4int Z, G4double energy) const
Definition at line 77 of file G4RDBremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 77 of file G4RDBremsstrahlungParameters.cc
References energy, G4RDVEMDataSet::FindValue(), G4cout, G4endl, G4RDVEMDataSet::GetEnergies(), length, max, min, param, and pos().
Referenced by G4RDeBremsstrahlungSpectrum::AverageEnergy(), G4RDeBremsstrahlungSpectrum::Probability(), and G4RDeBremsstrahlungSpectrum::SampleEnergy().
G4double G4RDBremsstrahlungParameters::ParameterC (G4int index) const
Definition at line 239 of file G4RDBremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 239 of file G4RDBremsstrahlungParameters.cc
References FatalException, G4Exception(), n, and paramC.
Referenced by G4RDeBremsstrahlungSpectrum::AverageEnergy().
void G4RDBremsstrahlungParameters::PrintData () const
Definition at line 255 of file G4RDBremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 255 of file G4RDBremsstrahlungParameters.cc
References activeZ, G4cout, G4endl, length, param, pos(), G4RDVEMDataSet::PrintData(), and Z.
Referenced by G4RDeBremsstrahlungSpectrum::PrintData().
Member Data Documentation
G4DataVector G4RDBremsstrahlungParameters::activeZ private
Definition at line 86 of file G4RDBremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 86 of file G4RDBremsstrahlungParameters.hh
Referenced by LoadData(), PrintData(), and ~G4RDBremsstrahlungParameters().
size_t G4RDBremsstrahlungParameters::length private
Definition at line 91 of file G4RDBremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 91 of file G4RDBremsstrahlungParameters.hh
Referenced by LoadData(), Parameter(), and PrintData().
std::map<G4int,G4RDVEMDataSet*,std::less<G4int> > G4RDBremsstrahlungParameters::param private
Definition at line 83 of file G4RDBremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 83 of file G4RDBremsstrahlungParameters.hh
Referenced by LoadData(), Parameter(), PrintData(), and ~G4RDBremsstrahlungParameters().
G4DataVector G4RDBremsstrahlungParameters::paramC private
Definition at line 85 of file G4RDBremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 85 of file G4RDBremsstrahlungParameters.hh
Referenced by LoadData(), ParameterC(), and ~G4RDBremsstrahlungParameters().
G4int G4RDBremsstrahlungParameters::zMax private
Definition at line 89 of file G4RDBremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 89 of file G4RDBremsstrahlungParameters.hh
G4int G4RDBremsstrahlungParameters::zMin private
Definition at line 88 of file G4RDBremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 88 of file G4RDBremsstrahlungParameters.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4RDBremsstrahlungParameters.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4RDBremsstrahlungParameters.cc