ECCE @ EIC Software: G4CrossSectionComposite Class Reference
G4CrossSectionComposite Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CrossSectionComposite.hh>
Public Member Functions
G4CrossSectionComposite ()
virtual ~G4CrossSectionComposite ()
G4bool operator== (const G4CrossSectionComposite &right) const
G4bool operator!= (const G4CrossSectionComposite &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual const
G4CrossSectionVector * GetComponents () const =0
virtual G4bool IsValid (G4double e) const
G4CrossSectionComposite ()
virtual ~G4CrossSectionComposite ()
G4bool operator== (const G4CrossSectionComposite &right) const
G4bool operator!= (const G4CrossSectionComposite &right) const
virtual G4double CrossSection (const G4KineticTrack &trk1, const G4KineticTrack &trk2)
virtual void Add (G4CrossSectionComposite *component)
virtual void Remove (G4CrossSectionComposite *component)
Public Member Functions inherited from G4VCrossSectionSource
G4VCrossSectionSource ()
virtual ~G4VCrossSectionSource ()
G4bool operator== (const G4VCrossSectionSource &right) const
G4bool operator!= (const G4VCrossSectionSource &right) const
virtual G4String Name () const =0
virtual void Print () const
virtual void PrintAll (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
virtual G4double HighLimit () const
virtual G4double LowLimit () const
Protected Attributes
G4CrossSectionVector * _components
Private Member Functions
G4CrossSectionComposite (const G4CrossSectionComposite &right)
G4CrossSectionComposite & operator= (const G4CrossSectionComposite &right)
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionSource
G4bool InLimits (G4double e, G4double eLow, G4double eHigh) const
const G4ParticleDefinition * FindLightParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
G4double FcrossX (G4double e, G4double e0, G4double sigma, G4double eParam, G4double power) const
const G4ParticleDefinition * FindKeyParticle (const G4KineticTrack &trk1, const G4KineticTrack &trk2) const
Detailed Description
Definition at line 50 of file G4CrossSectionComposite.hh.
View newest version in sPHENIX GitHub at line 50 of file G4CrossSectionComposite.hh
Constructor & Destructor Documentation
G4CrossSectionComposite::G4CrossSectionComposite ()
Definition at line 48 of file G4CrossSectionComposite.cc.
View newest version in sPHENIX GitHub at line 48 of file G4CrossSectionComposite.cc
G4CrossSectionComposite::~G4CrossSectionComposite () virtual
Definition at line 52 of file G4CrossSectionComposite.cc.
View newest version in sPHENIX GitHub at line 52 of file G4CrossSectionComposite.cc
G4CrossSectionComposite::G4CrossSectionComposite (const G4CrossSectionComposite & right) private
G4CrossSectionComposite::G4CrossSectionComposite ()
virtual G4CrossSectionComposite::~G4CrossSectionComposite () virtual
Member Function Documentation
virtual void G4CrossSectionComposite::Add (G4CrossSectionComposite * component) virtual
virtual G4double G4CrossSectionComposite::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) virtual
G4double G4CrossSectionComposite::CrossSection (const G4KineticTrack & trk1, const G4KineticTrack & trk2) const virtual
Implements G4VCrossSectionSource.
Definition at line 68 of file G4CrossSectionComposite.cc.
View newest version in sPHENIX GitHub at line 68 of file G4CrossSectionComposite.cc
References components, G4VCrossSectionSource::CrossSection(), G4KineticTrack::Get4Momentum(), GetComponents(), and G4VCrossSectionSource::IsValid().
virtual const G4CrossSectionVector* G4CrossSectionComposite::GetComponents () const pure virtual
Implements G4VCrossSectionSource.
Referenced by CrossSection(), and IsValid().
G4bool G4CrossSectionComposite::IsValid (G4double e) const virtual
Reimplemented from G4VCrossSectionSource.
Definition at line 98 of file G4CrossSectionComposite.cc.
View newest version in sPHENIX GitHub at line 98 of file G4CrossSectionComposite.cc
References components, GetComponents(), G4VCrossSectionSource::IsValid(), and n.
G4bool G4CrossSectionComposite::operator!= (const G4CrossSectionComposite & right) const
G4bool G4CrossSectionComposite::operator!= (const G4CrossSectionComposite & right) const
Definition at line 62 of file G4CrossSectionComposite.cc.
View newest version in sPHENIX GitHub at line 62 of file G4CrossSectionComposite.cc
G4CrossSectionComposite& G4CrossSectionComposite::operator= (const G4CrossSectionComposite & right) private
G4bool G4CrossSectionComposite::operator== (const G4CrossSectionComposite & right) const
G4bool G4CrossSectionComposite::operator== (const G4CrossSectionComposite & right) const
Definition at line 56 of file G4CrossSectionComposite.cc.
View newest version in sPHENIX GitHub at line 56 of file G4CrossSectionComposite.cc
virtual void G4CrossSectionComposite::Remove (G4CrossSectionComposite * component) virtual
Member Data Documentation
G4CrossSectionVector* G4CrossSectionComposite::_components protected
Definition at line 69 of file G4VCrossSectionComposite.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VCrossSectionComposite.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4CrossSectionComposite.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/include/G4VCrossSectionComposite.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/im_r_matrix/src/G4CrossSectionComposite.cc