ECCE @ EIC Software: G4MaterialPropertiesTable Class Reference
G4MaterialPropertiesTable Class Reference
#include <geant4/tree/geant4-10.6-release/source/materials/include/G4MaterialPropertiesTable.hh>
Public Member Functions
G4MaterialPropertiesTable ()
virtual ~G4MaterialPropertiesTable ()
void AddConstProperty (const char *key, G4double PropertyValue)
G4MaterialPropertyVector * AddProperty (const char *key, G4double *PhotonEnergies, G4double *PropertyValues, G4int NumEntries)
void AddProperty (const char *key, G4MaterialPropertyVector *opv)
void RemoveConstProperty (const char *key)
void RemoveProperty (const char *key)
G4double GetConstProperty (const char *key) const
G4double GetConstProperty (const G4int index) const
G4bool ConstPropertyExists (const char *key) const
G4MaterialPropertyVector * GetProperty (const char *key, G4bool warning=false)
G4MaterialPropertyVector * GetProperty (const G4int index, G4bool warning=false)
void AddEntry (const char *key, G4double aPhotonEnergy, G4double aPropertyValue)
G4int GetConstPropertyIndex (const G4String &key, G4bool warning=false) const
G4int GetPropertyIndex (const G4String &key, G4bool warning=false) const
std::vector< G4String > GetMaterialPropertyNames () const
std::vector< G4String > GetMaterialConstPropertyNames () const
void DumpTable ()
std::map< G4String,
G4MaterialPropertyVector
*, std::less< G4String > > * GetPropertiesMap ()
std::map< G4String, G4double,
std::less< G4String > > * GetPropertiesCMap ()
const std::map< G4int,
G4MaterialPropertyVector
*, std::less< G4int > > * GetPropertyMap () const
const std::map< G4int,
G4double, std::less< G4int > > * GetConstPropertyMap () const
Private Types
typedef std::map< G4String,
G4MaterialPropertyVector
*, std::less< G4String >
>::const_iterator MPTiterator
typedef std::map< G4String,
G4double, std::less< G4String >
>::const_iterator MPTCiterator
typedef std::map< G4int,
G4MaterialPropertyVector
*, std::less< G4int >
>::const_iterator MPiterator
typedef std::map< G4int,
G4double, std::less< G4int >
>::const_iterator MCPiterator
Private Member Functions
G4MaterialPropertyVector * CalculateGROUPVEL ()
G4MaterialPropertyVector * SetGROUPVEL ()
Private Attributes
std::map< G4String,
G4MaterialPropertyVector
*, std::less< G4String > > MPT
std::map< G4String, G4double,
std::less< G4String > > MPTC
std::map< G4int,
G4MaterialPropertyVector
*, std::less< G4int > > MP
std::map< G4int, G4double,
std::less< G4int > > MCP
std::vector< G4String > G4MaterialPropertyName
std::vector< G4String > G4MaterialConstPropertyName
Detailed Description
Definition at line 70 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 70 of file G4MaterialPropertiesTable.hh
Member Typedef Documentation
typedef std::map< G4int, G4double, std::less<G4int> >::const_iterator G4MaterialPropertiesTable::MCPiterator private
Definition at line 172 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 172 of file G4MaterialPropertiesTable.hh
typedef std::map< G4int, G4MaterialPropertyVector*, std::less<G4int> >::const_iterator G4MaterialPropertiesTable::MPiterator private
Definition at line 168 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 168 of file G4MaterialPropertiesTable.hh
typedef std::map< G4String, G4double, std::less<G4String> >::const_iterator G4MaterialPropertiesTable::MPTCiterator private
Definition at line 162 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 162 of file G4MaterialPropertiesTable.hh
typedef std::map< G4String, G4MaterialPropertyVector*, std::less<G4String> >::const_iterator G4MaterialPropertiesTable::MPTiterator private
Definition at line 158 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 158 of file G4MaterialPropertiesTable.hh
Constructor & Destructor Documentation
G4MaterialPropertiesTable::G4MaterialPropertiesTable ()
Definition at line 59 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 59 of file G4MaterialPropertiesTable.cc
References G4MaterialConstPropertyName, and G4MaterialPropertyName.
G4MaterialPropertiesTable::~G4MaterialPropertiesTable () virtual
Definition at line 126 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 126 of file G4MaterialPropertiesTable.cc
References G4MaterialConstPropertyName, G4MaterialPropertyName, it, MCP, MP, MPT, and MPTC.
Member Function Documentation
void G4MaterialPropertiesTable::AddConstProperty (const char * key, G4double PropertyValue) inline
Referenced by DetectorConstruction::AddSurfaceMPC(), DetectorConstruction::AddTankMPC(), DetectorConstruction::AddWorldMPC(), OpNoviceDetectorConstruction::Construct(), WLSMaterials::CreateMaterials(), PHG4HybridHomogeneousCalorimeterDetector::CrystalTable(), ExUCNDetectorConstruction::DefineMaterials(), LXeDetectorConstruction::DefineMaterials(), PHG4Reco::DefineMaterials(), PHG4LFHcalDetector::GetScintillatorMaterial(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetWLSFiberFEMCMaterial(), PHG4LFHcalDetector::GetWLSFiberMaterial(), G4GDMLReadMaterials::PropertyRead(), G4GDMLReadSolids::PropertyRead(), LXeDetectorConstruction::SetDefaults(), LXeDetectorConstruction::SetMainScintYield(), G4UCNMaterialPropertiesTable::SetMicroRoughnessParameters(), and LXeDetectorConstruction::SetWLSScintYield().
void G4MaterialPropertiesTable::AddEntry (const char * key, G4double aPhotonEnergy, G4double aPropertyValue)
Definition at line 298 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 298 of file G4MaterialPropertiesTable.cc
References FatalException, G4Exception(), G4MaterialPropertyName, GetPropertyIndex(), G4PhysicsOrderedFreeVector::InsertValues(), k, and MP.
Referenced by UltraDetectorConstruction::ConstructTableMaterials().
G4MaterialPropertyVector * G4MaterialPropertiesTable::AddProperty (const char * key, G4double * PhotonEnergies, G4double * PropertyValues, G4int NumEntries)
Definition at line 246 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 246 of file G4MaterialPropertiesTable.cc
References CalculateGROUPVEL(), G4MaterialPropertyName, GetPropertyIndex(), k, and MP.
Referenced by EICG4dRICHOptics::addSkinPropTable(), DetectorConstruction::AddSurfaceMPV(), DetectorConstruction::AddTankMPV(), DetectorConstruction::AddWorldMPV(), PHG4mRICHDetector::build_aerogel(), PHG4mRICHDetector::build_mirror(), CalculateGROUPVEL(), OpNoviceDetectorConstruction::Construct(), LXeDetectorConstruction::Construct(), DMXDetectorConstruction::Construct(), WLSDetectorConstruction::ConstructFiber(), G4EicDircDetector::ConstructMe(), UltraDetectorConstruction::ConstructReflector(), UltraDetectorConstruction::ConstructTableMaterials(), UltraDetectorConstruction::ConstructUVscope(), WLSMaterials::CreateMaterials(), ePHENIXRICH::RICH_Geometry::CreateOpticalSurfaces(), PHG4HybridHomogeneousCalorimeterDetector::CrystalTable(), LXeDetectorConstruction::DefineMaterials(), G4EicDircDetector::DefineMaterials(), PHG4Reco::DefineMaterials(), PHG4ForwardDualReadoutDetector::GetPMMAMaterial(), PHG4ForwardDualReadoutDetector::GetQuartzMaterial(), PHG4LFHcalDetector::GetScintillatorMaterial(), PHG4ForwardDualReadoutDetector::GetScintillatorMaterial(), PHG4ForwardEcalDetector::GetScintillatorMaterial(), PHG4HybridHomogeneousCalorimeterDetector::GetVM2000Material(), PHG4ForwardEcalDetector::GetWLSFiberFEMCMaterial(), PHG4LFHcalDetector::GetWLSFiberMaterial(), PHG4LFHcalDetector::MakeBoundary(), PHG4HybridHomogeneousCalorimeterDetector::MakeBoundary(), PHG4LFHcalDetector::MakeBoundary_Fiber_Scint(), G4GDMLReadMaterials::PropertyRead(), G4GDMLReadSolids::PropertyRead(), EICG4dRICHOptics::setMatPropTable(), LXeMainVolume::SurfaceProperties(), PHG4LFHcalDetector::SurfaceTable(), and PHG4HybridHomogeneousCalorimeterDetector::SurfaceTable().
void G4MaterialPropertiesTable::AddProperty (const char * key, G4MaterialPropertyVector * opv)
Definition at line 277 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 277 of file G4MaterialPropertiesTable.cc
References CalculateGROUPVEL(), G4MaterialPropertyName, GetPropertyIndex(), k, and MP.
G4MaterialPropertyVector * G4MaterialPropertiesTable::CalculateGROUPVEL () private
Definition at line 365 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 365 of file G4MaterialPropertiesTable.cc
References AddProperty(), source.hepunit::c_light, FatalException, G4Exception(), G4Log(), G4PhysicsOrderedFreeVector::InsertValues(), kGROUPVEL, kRINDEX, MP, and n1.
Referenced by AddProperty(), and SetGROUPVEL().
G4bool G4MaterialPropertiesTable::ConstPropertyExists (const char * key) const
Definition at line 211 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 211 of file G4MaterialPropertiesTable.cc
References GetConstPropertyIndex(), and MCP.
Referenced by G4OpRayleigh::CalculateRayleighMeanFreePaths(), PHG4SteppingAction::GetScintLightYield(), G4UCNMaterialPropertiesTable::InitMicroRoughnessTables(), G4OpWLS::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), and G4UCNMaterialPropertiesTable::SetMicroRoughnessParameters().
void G4MaterialPropertiesTable::DumpTable ()
Definition at line 324 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 324 of file G4MaterialPropertiesTable.cc
References G4cout, G4endl, G4Exception(), G4MaterialConstPropertyName, G4MaterialPropertyName, JustWarning, MCP, and MP.
Referenced by EICG4dRICHOptics::addSkinPropTable(), DetectorConstruction::AddSurfaceMPC(), DetectorConstruction::AddSurfaceMPV(), DetectorConstruction::AddTankMPC(), DetectorConstruction::AddTankMPV(), DetectorConstruction::AddWorldMPC(), DetectorConstruction::AddWorldMPV(), OpNoviceDetectorConstruction::Construct(), EICG4dRICHOptics::EICG4dRICHOptics(), and EICG4dRICHOptics::setMatPropTable().
G4double G4MaterialPropertiesTable::GetConstProperty (const char * key) const
Definition at line 202 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 202 of file G4MaterialPropertiesTable.cc
References GetConstPropertyIndex().
Referenced by G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4UCNMaterialPropertiesTable::ComputeMicroRoughnessTables(), G4UCNAbsorption::GetMeanFreePath(), G4UCNMultiScattering::GetMeanFreePath(), G4UCNLoss::GetMeanFreePath(), PHG4SteppingAction::GetScintLightYield(), G4UCNMaterialPropertiesTable::InitMicroRoughnessTables(), G4OpMieHG::PostStepDoIt(), and G4UCNBoundaryProcess::PostStepDoIt().
G4double G4MaterialPropertiesTable::GetConstProperty (const G4int index) const
Definition at line 187 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 187 of file G4MaterialPropertiesTable.cc
References FatalException, G4Exception(), and MCP.
G4int G4MaterialPropertiesTable::GetConstPropertyIndex (const G4String & key, G4bool warning = false) const
Definition at line 152 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 152 of file G4MaterialPropertiesTable.cc
References G4Exception(), G4MaterialConstPropertyName, and JustWarning.
Referenced by ConstPropertyExists(), and GetConstProperty().
const std::map<G4int, G4double, std::less<G4int> >* G4MaterialPropertiesTable::GetConstPropertyMap () const inline
Definition at line 143 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 143 of file G4MaterialPropertiesTable.hh
References MCP.
Referenced by G4GDMLWriteMaterials::PropertyWrite(), PHG4GDMLWriteMaterials::PropertyWrite(), and G4GDMLWriteSolids::PropertyWrite().
std::vector< G4String > G4MaterialPropertiesTable::GetMaterialConstPropertyNames () const
Definition at line 527 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 527 of file G4MaterialPropertiesTable.cc
References G4MaterialConstPropertyName.
Referenced by G4GDMLWriteMaterials::PropertyWrite(), PHG4GDMLWriteMaterials::PropertyWrite(), and G4GDMLWriteSolids::PropertyWrite().
std::vector< G4String > G4MaterialPropertiesTable::GetMaterialPropertyNames () const
Definition at line 522 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 522 of file G4MaterialPropertiesTable.cc
References G4MaterialPropertyName.
Referenced by G4GDMLWriteMaterials::PropertyWrite(), PHG4GDMLWriteMaterials::PropertyWrite(), and G4GDMLWriteSolids::PropertyWrite().
std::map< G4String, G4double, std::less< G4String > > * G4MaterialPropertiesTable::GetPropertiesCMap ()
Definition at line 508 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 508 of file G4MaterialPropertiesTable.cc
References G4Exception(), G4MaterialConstPropertyName, JustWarning, MCP, message(), and MPTC.
std::map< G4String, G4MaterialPropertyVector *, std::less< G4String > > * G4MaterialPropertiesTable::GetPropertiesMap ()
Definition at line 486 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 486 of file G4MaterialPropertiesTable.cc
References G4Exception(), G4MaterialPropertyName, JustWarning, message(), MP, and MPT.
G4MaterialPropertyVector * G4MaterialPropertiesTable::GetProperty (const char * key, G4bool warning = false)
Definition at line 223 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 223 of file G4MaterialPropertiesTable.cc
References GetPropertyIndex().
Referenced by WLSPrimaryGeneratorAction::BuildEmissionSpectrum(), G4OpRayleigh::BuildPhysicsTable(), G4OpWLS::BuildPhysicsTable(), G4Cerenkov::BuildThePhysicsTable(), G4Scintillation::BuildThePhysicsTable(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4Track::CalculateVelocityForOpticalPhoton(), WLSPrimaryGeneratorAction::GeneratePrimaries(), G4OpMieHG::GetMeanFreePath(), G4OpAbsorption::GetMeanFreePath(), G4OpBoundaryProcess::GetReflectivity(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), and G4Cerenkov::PostStepGetPhysicalInteractionLength().
G4MaterialPropertyVector * G4MaterialPropertiesTable::GetProperty (const G4int index, G4bool warning = false)
Definition at line 231 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 231 of file G4MaterialPropertiesTable.cc
References G4Exception(), if(), JustWarning, and MP.
G4int G4MaterialPropertiesTable::GetPropertyIndex (const G4String & key, G4bool warning = false) const
Definition at line 170 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 170 of file G4MaterialPropertiesTable.cc
References G4Exception(), G4MaterialPropertyName, and JustWarning.
Referenced by AddEntry(), AddProperty(), and GetProperty().
const std::map<G4int, G4MaterialPropertyVector*, std::less<G4int> >* G4MaterialPropertiesTable::GetPropertyMap () const inline
Definition at line 141 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 141 of file G4MaterialPropertiesTable.hh
References MP.
Referenced by G4GDMLWriteMaterials::PropertyWrite(), PHG4GDMLWriteMaterials::PropertyWrite(), and G4GDMLWriteSolids::PropertyWrite().
void G4MaterialPropertiesTable::RemoveConstProperty (const char * key) inline
Referenced by G4UCNMaterialPropertiesTable::SetMicroRoughnessParameters().
void G4MaterialPropertiesTable::RemoveProperty (const char * key) inline
G4MaterialPropertyVector * G4MaterialPropertiesTable::SetGROUPVEL () private
Definition at line 475 of file G4MaterialPropertiesTable.cc.
View newest version in sPHENIX GitHub at line 475 of file G4MaterialPropertiesTable.cc
References CalculateGROUPVEL(), G4Exception(), JustWarning, and message().
Member Data Documentation
std::vector<G4String> G4MaterialPropertiesTable::G4MaterialConstPropertyName private
Definition at line 176 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 176 of file G4MaterialPropertiesTable.hh
Referenced by DumpTable(), G4MaterialPropertiesTable(), GetConstPropertyIndex(), GetMaterialConstPropertyNames(), GetPropertiesCMap(), and ~G4MaterialPropertiesTable().
std::vector<G4String> G4MaterialPropertiesTable::G4MaterialPropertyName private
Definition at line 175 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 175 of file G4MaterialPropertiesTable.hh
Referenced by AddEntry(), AddProperty(), DumpTable(), G4MaterialPropertiesTable(), GetMaterialPropertyNames(), GetPropertiesMap(), GetPropertyIndex(), and ~G4MaterialPropertiesTable().
std::map< G4int, G4double, std::less<G4int> > G4MaterialPropertiesTable::MCP private
Definition at line 170 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 170 of file G4MaterialPropertiesTable.hh
Referenced by ConstPropertyExists(), DumpTable(), GetConstProperty(), GetConstPropertyMap(), GetPropertiesCMap(), and ~G4MaterialPropertiesTable().
std::map<G4int, G4MaterialPropertyVector*, std::less<G4int> > G4MaterialPropertiesTable::MP private
Definition at line 166 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 166 of file G4MaterialPropertiesTable.hh
Referenced by AddEntry(), AddProperty(), CalculateGROUPVEL(), DumpTable(), GetPropertiesMap(), GetProperty(), GetPropertyMap(), and ~G4MaterialPropertiesTable().
std::map<G4String, G4MaterialPropertyVector*, std::less<G4String> > G4MaterialPropertiesTable::MPT private
Definition at line 156 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 156 of file G4MaterialPropertiesTable.hh
Referenced by GetPropertiesMap(), and ~G4MaterialPropertiesTable().
std::map< G4String, G4double, std::less<G4String> > G4MaterialPropertiesTable::MPTC private
Definition at line 160 of file G4MaterialPropertiesTable.hh.
View newest version in sPHENIX GitHub at line 160 of file G4MaterialPropertiesTable.hh
Referenced by GetPropertiesCMap(), and ~G4MaterialPropertiesTable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/materials/include/G4MaterialPropertiesTable.hh
geant4/tree/geant4-10.6-release/source/materials/src/G4MaterialPropertiesTable.cc