ECCE @ EIC Software: mRICH Class Reference
mRICH Class Reference
#include <ecce-detectors/blob/master/FastPID/mRICH/mRICH.h>
Public Member Functions
mRICH (double trackResolution=0.5, double timePrecision=1.0, double pixS=0.5, double p=5.0)
virtual ~mRICH ()
bool valid (double eta, double p)
double maxP (double eta, double p, double numSigma, PID::type PID)
double minP (double eta, double numSigma, PID::type PID)
string name ()
void description ()
void ReadMap (TString name)
double getAng (double mass)
double getdAng (double mass)
double getNgamma (double t, double mass)
double T_Aer (double t, double lam)
double T_QE (double lam)
double SetLensFocalLength (double f)
double SetAerogelThickness (double t)
double GetmRICHParameters ()
Public Member Functions inherited from PID
PID ()
virtual ~PID ()
Protected Attributes
std::string myName
double Nsigma
double mPion
double mKaon
double mProton
double mom
double c
double n
double f
double a
double N_gam
double pi
double alpha
double L
double th0
double fTrackResolution
double fTimePrecision
double pLow
double pHigh
TH2F * fpixMap
Additional Inherited Members
Public Types inherited from PID
enum type { pi_k, k_p }
Detailed Description
Definition at line 28 of file mRICH.h.
View newest version in sPHENIX GitHub at line 28 of file mRICH.h
Constructor & Destructor Documentation
mRICH::mRICH (double trackResolution = 0.5, double timePrecision = 1.0, double pixS = 0.5, double p = 5.0)
Definition at line 6 of file mRICH.C.
View newest version in sPHENIX GitHub at line 6 of file mRICH.C
References a, alpha, c, f, L, mom, n, and pi.
virtual mRICH::~mRICH () inline virtual
Definition at line 32 of file mRICH.h.
View newest version in sPHENIX GitHub at line 32 of file mRICH.h
Member Function Documentation
void mRICH::description () virtual
Implements PID.
Definition at line 154 of file mRICH.C.
View newest version in sPHENIX GitHub at line 154 of file mRICH.C
double mRICH::getAng (double mass)
Definition at line 70 of file mRICH.C.
View newest version in sPHENIX GitHub at line 70 of file mRICH.C
References mom, n, and theta().
double mRICH::getdAng (double mass)
Definition at line 83 of file mRICH.C.
View newest version in sPHENIX GitHub at line 83 of file mRICH.C
References a, f, mom, n, and theta().
double mRICH::GetmRICHParameters ()
double mRICH::getNgamma (double t, double mass)
Definition at line 117 of file mRICH.C.
View newest version in sPHENIX GitHub at line 117 of file mRICH.C
References alpha, dx, mom, n, pi, sum, x, xmax, and xmin.
double mRICH::maxP (double eta, double p, double numSigma, PID::type PID) virtual
Implements PID.
Definition at line 56 of file mRICH.C.
View newest version in sPHENIX GitHub at line 56 of file mRICH.C
References Acts::IntegrationTest::valid().
double mRICH::minP (double eta, double numSigma, PID::type PID) inline virtual
Implements PID.
Definition at line 37 of file mRICH.h.
View newest version in sPHENIX GitHub at line 37 of file mRICH.h
string mRICH::name () inline virtual
Implements PID.
Definition at line 38 of file mRICH.h.
View newest version in sPHENIX GitHub at line 38 of file mRICH.h
References myName.
void mRICH::ReadMap (TString name)
Definition at line 148 of file mRICH.C.
View newest version in sPHENIX GitHub at line 148 of file mRICH.C
References file.
double mRICH::SetAerogelThickness (double t)
double mRICH::SetLensFocalLength (double f)
double mRICH::T_Aer (double t, double lam)
Definition at line 141 of file mRICH.C.
View newest version in sPHENIX GitHub at line 141 of file mRICH.C
References e.
double mRICH::T_QE (double lam)
Definition at line 135 of file mRICH.C.
View newest version in sPHENIX GitHub at line 135 of file mRICH.C
References e.
bool mRICH::valid (double eta, double p) inline virtual
Implements PID.
Definition at line 35 of file mRICH.h.
View newest version in sPHENIX GitHub at line 35 of file mRICH.h
References pHigh, and pLow.
Member Data Documentation
double mRICH::a protected
Definition at line 64 of file mRICH.h.
View newest version in sPHENIX GitHub at line 64 of file mRICH.h
double mRICH::alpha protected
Definition at line 67 of file mRICH.h.
View newest version in sPHENIX GitHub at line 67 of file mRICH.h
double mRICH::c protected
Definition at line 61 of file mRICH.h.
View newest version in sPHENIX GitHub at line 61 of file mRICH.h
double mRICH::f protected
Definition at line 63 of file mRICH.h.
View newest version in sPHENIX GitHub at line 63 of file mRICH.h
TH2F* mRICH::fpixMap protected
Definition at line 77 of file mRICH.h.
View newest version in sPHENIX GitHub at line 77 of file mRICH.h
double mRICH::fTimePrecision protected
Definition at line 72 of file mRICH.h.
View newest version in sPHENIX GitHub at line 72 of file mRICH.h
double mRICH::fTrackResolution protected
Definition at line 71 of file mRICH.h.
View newest version in sPHENIX GitHub at line 71 of file mRICH.h
double mRICH::L protected
Definition at line 68 of file mRICH.h.
View newest version in sPHENIX GitHub at line 68 of file mRICH.h
double mRICH::mKaon protected
Definition at line 58 of file mRICH.h.
View newest version in sPHENIX GitHub at line 58 of file mRICH.h
double mRICH::mom protected
Definition at line 60 of file mRICH.h.
View newest version in sPHENIX GitHub at line 60 of file mRICH.h
double mRICH::mPion protected
Definition at line 57 of file mRICH.h.
View newest version in sPHENIX GitHub at line 57 of file mRICH.h
double mRICH::mProton protected
Definition at line 59 of file mRICH.h.
View newest version in sPHENIX GitHub at line 59 of file mRICH.h
std::string mRICH::myName protected
Definition at line 52 of file mRICH.h.
View newest version in sPHENIX GitHub at line 52 of file mRICH.h
Referenced by name().
double mRICH::n protected
Definition at line 62 of file mRICH.h.
View newest version in sPHENIX GitHub at line 62 of file mRICH.h
double mRICH::N_gam protected
Definition at line 65 of file mRICH.h.
View newest version in sPHENIX GitHub at line 65 of file mRICH.h
double mRICH::Nsigma protected
Definition at line 54 of file mRICH.h.
View newest version in sPHENIX GitHub at line 54 of file mRICH.h
double mRICH::pHigh protected
Definition at line 75 of file mRICH.h.
View newest version in sPHENIX GitHub at line 75 of file mRICH.h
Referenced by valid().
double mRICH::pi protected
Definition at line 66 of file mRICH.h.
View newest version in sPHENIX GitHub at line 66 of file mRICH.h
double mRICH::pLow protected
Definition at line 74 of file mRICH.h.
View newest version in sPHENIX GitHub at line 74 of file mRICH.h
Referenced by valid().
double mRICH::th0 protected
Definition at line 69 of file mRICH.h.
View newest version in sPHENIX GitHub at line 69 of file mRICH.h
The documentation for this class was generated from the following files:
ecce-detectors/blob/master/FastPID/mRICH/mRICH.h
ecce-detectors/blob/master/FastPID/mRICH/mRICH.C