ECCE @ EIC Software: G4QGSPNeutronBuilder Class Reference
G4QGSPNeutronBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPNeutronBuilder.hh>
Public Member Functions
G4QGSPNeutronBuilder (G4bool quasiElastic=false)
virtual ~G4QGSPNeutronBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4HadronFissionProcess *) finaloverride
virtual void Build (G4HadronCaptureProcess *) finaloverride
virtual void Build (G4NeutronInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VNeutronBuilder
G4VNeutronBuilder ()=default
virtual ~G4VNeutronBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4QGSMFragmentation * theQGSM
G4double theMin
Detailed Description
Definition at line 58 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4QGSPNeutronBuilder.hh
Constructor & Destructor Documentation
G4QGSPNeutronBuilder::G4QGSPNeutronBuilder (G4bool quasiElastic = false)
Definition at line 51 of file G4QGSPNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 51 of file G4QGSPNeutronBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQGSM, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSPNeutronBuilder::~G4QGSPNeutronBuilder () virtual
Definition at line 72 of file G4QGSPNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 72 of file G4QGSPNeutronBuilder.cc
References theQGSM, theQuasiElastic, and theStringDecay.
Member Function Documentation
virtual void G4QGSPNeutronBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 65 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4QGSPNeutronBuilder.hh
virtual void G4QGSPNeutronBuilder::Build (G4HadronFissionProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 66 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4QGSPNeutronBuilder.hh
virtual void G4QGSPNeutronBuilder::Build (G4HadronCaptureProcess *) inline final override virtual
Implements G4VNeutronBuilder.
Definition at line 67 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4QGSPNeutronBuilder.hh
void G4QGSPNeutronBuilder::Build (G4NeutronInelasticProcess * aP) final override virtual
Implements G4VNeutronBuilder.
Definition at line 80 of file G4QGSPNeutronBuilder.cc.
View newest version in sPHENIX GitHub at line 80 of file G4QGSPNeutronBuilder.cc
References G4HadronicProcess::AddDataSet(), G4HadronicParameters::Instance(), G4Neutron::Neutron(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSPNeutronBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 70 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QGSPNeutronBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4QGSPNeutronBuilder::theCascade private
Definition at line 76 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSPNeutronBuilder.hh
Referenced by G4QGSPNeutronBuilder().
G4double G4QGSPNeutronBuilder::theMin private
Definition at line 83 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 83 of file G4QGSPNeutronBuilder.hh
Referenced by Build(), G4QGSPNeutronBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSPNeutronBuilder::theModel private
Definition at line 75 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSPNeutronBuilder.hh
Referenced by Build(), and G4QGSPNeutronBuilder().
G4QGSMFragmentation* G4QGSPNeutronBuilder::theQGSM private
Definition at line 81 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 81 of file G4QGSPNeutronBuilder.hh
Referenced by G4QGSPNeutronBuilder(), and ~G4QGSPNeutronBuilder().
G4QuasiElasticChannel* G4QGSPNeutronBuilder::theQuasiElastic private
Definition at line 79 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QGSPNeutronBuilder.hh
Referenced by G4QGSPNeutronBuilder(), and ~G4QGSPNeutronBuilder().
G4ExcitedStringDecay* G4QGSPNeutronBuilder::theStringDecay private
Definition at line 78 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSPNeutronBuilder.hh
Referenced by G4QGSPNeutronBuilder(), and ~G4QGSPNeutronBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSPNeutronBuilder::theStringModel private
Definition at line 77 of file G4QGSPNeutronBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QGSPNeutronBuilder.hh
Referenced by G4QGSPNeutronBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPNeutronBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSPNeutronBuilder.cc