ECCE @ EIC Software: G4ProtonInelasticCrossSection Class Reference
G4ProtonInelasticCrossSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ProtonInelasticCrossSection.hh>
Public Member Functions
G4ProtonInelasticCrossSection ()
~G4ProtonInelasticCrossSection ()
virtual G4bool IsElementApplicable (const G4DynamicParticle *aPart, G4int Z, const G4Material *)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *)
G4double GetProtonCrossSection (G4double kineticEnergy, G4int Z)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual void CrossSectionDescription (std::ostream &) const
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Attributes
G4NistManager * nist
G4Proton * theProton
G4double thEnergy
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 52 of file G4ProtonInelasticCrossSection.hh.
View newest version in sPHENIX GitHub at line 52 of file G4ProtonInelasticCrossSection.hh
Constructor & Destructor Documentation
G4ProtonInelasticCrossSection::G4ProtonInelasticCrossSection ()
Definition at line 41 of file G4ProtonInelasticCrossSection.cc.
View newest version in sPHENIX GitHub at line 41 of file G4ProtonInelasticCrossSection.cc
References G4NistManager::Instance(), nist, G4Proton::Proton(), and theProton.
G4ProtonInelasticCrossSection::~G4ProtonInelasticCrossSection ()
Definition at line 48 of file G4ProtonInelasticCrossSection.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ProtonInelasticCrossSection.cc
Member Function Documentation
G4double G4ProtonInelasticCrossSection::GetElementCrossSection (const G4DynamicParticle * aPart, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 59 of file G4ProtonInelasticCrossSection.cc.
View newest version in sPHENIX GitHub at line 59 of file G4ProtonInelasticCrossSection.cc
References G4DynamicParticle::GetKineticEnergy(), GetProtonCrossSection(), and Z.
G4double G4ProtonInelasticCrossSection::GetProtonCrossSection (G4double kineticEnergy, G4int Z)
Definition at line 66 of file G4ProtonInelasticCrossSection.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ProtonInelasticCrossSection.cc
References a, fac, G4Exp(), G4Log(), G4lrint(), G4NistManager::GetAtomicMassAmu(), G4Pow::GetInstance(), GeV, millibarn, nist, CLHEP::pi, G4Pow::powA(), thEnergy, and Z.
Referenced by GetElementCrossSection().
G4bool G4ProtonInelasticCrossSection::IsElementApplicable (const G4DynamicParticle * aPart, G4int Z, const G4Material *) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 52 of file G4ProtonInelasticCrossSection.cc.
View newest version in sPHENIX GitHub at line 52 of file G4ProtonInelasticCrossSection.cc
References G4DynamicParticle::GetDefinition(), and theProton.
Member Data Documentation
G4NistManager* G4ProtonInelasticCrossSection::nist private
Definition at line 72 of file G4ProtonInelasticCrossSection.hh.
View newest version in sPHENIX GitHub at line 72 of file G4ProtonInelasticCrossSection.hh
Referenced by G4ProtonInelasticCrossSection(), and GetProtonCrossSection().
G4double G4ProtonInelasticCrossSection::thEnergy private
Definition at line 74 of file G4ProtonInelasticCrossSection.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ProtonInelasticCrossSection.hh
Referenced by GetProtonCrossSection().
G4Proton* G4ProtonInelasticCrossSection::theProton private
Definition at line 73 of file G4ProtonInelasticCrossSection.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ProtonInelasticCrossSection.hh
Referenced by G4ProtonInelasticCrossSection(), and IsElementApplicable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4ProtonInelasticCrossSection.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4ProtonInelasticCrossSection.cc