ECCE @ EIC Software: G4PAIxSection Class Reference
G4PAIxSection Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIxSection.hh>
Public Member Functions
G4PAIxSection ()
G4PAIxSection (G4MaterialCutsCouple *matCC)
G4PAIxSection (G4int materialIndex, G4double maxEnergyTransfer)
G4PAIxSection (G4int materialIndex, G4double maxEnergyTransfer, G4double betaGammaSq, G4double **photoAbsCof, G4int intNumber)
G4PAIxSection (G4int materialIndex, G4double maxEnergyTransfer, G4double betaGammaSq)
~G4PAIxSection ()
void Initialize (const G4Material *material, G4double maxEnergyTransfer, G4double betaGammaSq, G4SandiaTable *)
void ComputeLowEnergyCof (const G4Material *material)
void ComputeLowEnergyCof ()
void InitPAI ()
void NormShift (G4double betaGammaSq)
void SplainPAI (G4double betaGammaSq)
G4double RutherfordIntegral (G4int intervalNumber, G4double limitLow, G4double limitHigh)
G4double ImPartDielectricConst (G4int intervalNumber, G4double energy)
G4double GetPhotonRange (G4double energy)
G4double GetElectronRange (G4double energy)
G4double RePartDielectricConst (G4double energy)
G4double DifPAIxSection (G4int intervalNumber, G4double betaGammaSq)
G4double PAIdNdxCerenkov (G4int intervalNumber, G4double betaGammaSq)
G4double PAIdNdxMM (G4int intervalNumber, G4double betaGammaSq)
G4double PAIdNdxPlasmon (G4int intervalNumber, G4double betaGammaSq)
G4double PAIdNdxResonance (G4int intervalNumber, G4double betaGammaSq)
void IntegralPAIxSection ()
void IntegralCerenkov ()
void IntegralMM ()
void IntegralPlasmon ()
void IntegralResonance ()
G4double SumOverInterval (G4int intervalNumber)
G4double SumOverIntervaldEdx (G4int intervalNumber)
G4double SumOverInterCerenkov (G4int intervalNumber)
G4double SumOverInterMM (G4int intervalNumber)
G4double SumOverInterPlasmon (G4int intervalNumber)
G4double SumOverInterResonance (G4int intervalNumber)
G4double SumOverBorder (G4int intervalNumber, G4double energy)
G4double SumOverBorderdEdx (G4int intervalNumber, G4double energy)
G4double SumOverBordCerenkov (G4int intervalNumber, G4double energy)
G4double SumOverBordMM (G4int intervalNumber, G4double energy)
G4double SumOverBordPlasmon (G4int intervalNumber, G4double energy)
G4double SumOverBordResonance (G4int intervalNumber, G4double energy)
G4double GetStepEnergyLoss (G4double step)
G4double GetStepCerenkovLoss (G4double step)
G4double GetStepMMLoss (G4double step)
G4double GetStepPlasmonLoss (G4double step)
G4double GetStepResonanceLoss (G4double step)
G4double GetEnergyTransfer ()
G4double GetCerenkovEnergyTransfer ()
G4double GetMMEnergyTransfer ()
G4double GetPlasmonEnergyTransfer ()
G4double GetResonanceEnergyTransfer ()
G4double GetRutherfordEnergyTransfer ()
G4int GetNumberOfGammas () const
G4int GetSplineSize () const
G4int GetIntervalNumber () const
G4double GetEnergyInterval (G4int i)
G4double GetDifPAIxSection (G4int i)
G4double GetPAIdNdxCerenkov (G4int i)
G4double GetPAIdNdxMM (G4int i)
G4double GetPAIdNdxPlasmon (G4int i)
G4double GetPAIdNdxResonance (G4int i)
G4double GetMeanEnergyLoss () const
G4double GetMeanCerenkovLoss () const
G4double GetMeanMMLoss () const
G4double GetMeanPlasmonLoss () const
G4double GetMeanResonanceLoss () const
G4double GetNormalizationCof () const
G4double GetLowEnergyCof () const
G4double GetLorentzFactor (G4int i) const
void SetVerbose (G4int v)
G4double GetPAItable (G4int i, G4int j) const
G4double GetSplineEnergy (G4int i) const
G4double GetIntegralPAIxSection (G4int i) const
G4double GetIntegralPAIdEdx (G4int i) const
G4double GetIntegralCerenkov (G4int i) const
G4double GetIntegralMM (G4int i) const
G4double GetIntegralPlasmon (G4int i) const
G4double GetIntegralResonance (G4int i) const
Private Member Functions
void CallError (G4int i, const G4String &methodName) const
G4PAIxSection & operator= (const G4PAIxSection &right)=delete
G4PAIxSection (const G4PAIxSection &)=delete
Private Attributes
G4int fIntervalNumber
G4double fNormalizationCof
G4int fMaterialIndex
G4double fDensity
G4double fElectronDensity
G4double fLowEnergyCof
G4int fSplineNumber
G4int fVerbose
G4OrderedTable * fMatSandiaMatrix
G4SandiaTable * fSandia
G4DataVector fEnergyInterval
G4DataVector fA1
G4DataVector fA2
G4DataVector fA3
G4DataVector fA4
G4DataVector fSplineEnergy
G4DataVector fRePartDielectricConst
G4DataVector fImPartDielectricConst
G4DataVector fIntegralTerm
G4DataVector fDifPAIxSection
G4DataVector fdNdxCerenkov
G4DataVector fdNdxPlasmon
G4DataVector fdNdxMM
G4DataVector fdNdxResonance
G4DataVector fIntegralPAIxSection
G4DataVector fIntegralPAIdEdx
G4DataVector fIntegralCerenkov
G4DataVector fIntegralPlasmon
G4DataVector fIntegralMM
G4DataVector fIntegralResonance
G4double fPAItable [500][112]
Static Private Attributes
static const G4double fDelta = 0.005
static const G4double fError = 0.005
static G4int fNumberOfGammas = 111
static const G4double fLorentzFactor [112]
static const G4int fRefGammaNumber = 29
static const G4int fMaxSplineSize = 1000
Detailed Description
Definition at line 67 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PAIxSection.hh
Constructor & Destructor Documentation
G4PAIxSection::G4PAIxSection ()
Definition at line 90 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 90 of file G4PAIxSection.cc
G4PAIxSection::G4PAIxSection (G4MaterialCutsCouple * matCC)
Definition at line 127 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 127 of file G4PAIxSection.cc
References G4Material::GetDensity(), G4Material::GetIndex(), G4MaterialCutsCouple::GetMaterial(), and G4Material::GetMaterialTable().
G4PAIxSection::G4PAIxSection (G4int materialIndex, G4double maxEnergyTransfer)
Definition at line 160 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 160 of file G4PAIxSection.cc
References G4Material::GetMaterialTable().
G4PAIxSection::G4PAIxSection (G4int materialIndex, G4double maxEnergyTransfer, G4double betaGammaSq, G4double ** photoAbsCof, G4int intNumber)
Definition at line 272 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 272 of file G4PAIxSection.cc
References G4Material::GetMaterialTable().
G4PAIxSection::G4PAIxSection (G4int materialIndex, G4double maxEnergyTransfer, G4double betaGammaSq)
Definition at line 433 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 433 of file G4PAIxSection.cc
References G4Material::GetMaterialTable(), G4SandiaTable::GetPhotoAbsorpCof(), G4SandiaTable::SandiaIntervals(), and G4SandiaTable::SandiaMixing().
G4PAIxSection::~G4PAIxSection ()
Definition at line 584 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 584 of file G4PAIxSection.cc
G4PAIxSection::G4PAIxSection (const G4PAIxSection &) private delete
Member Function Documentation
void G4PAIxSection::CallError (G4int i, const G4String & methodName) const private
Definition at line 2525 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2525 of file G4PAIxSection.cc
References FatalException, and G4Exception().
Referenced by GetIntegralCerenkov(), GetIntegralMM(), GetIntegralPAIdEdx(), GetIntegralPAIxSection(), GetIntegralPlasmon(), GetIntegralResonance(), and GetSplineEnergy().
void G4PAIxSection::ComputeLowEnergyCof (const G4Material * material)
Definition at line 746 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 746 of file G4PAIxSection.cc
References G4Material::GetElement(), G4Material::GetNumberOfElements(), and G4Element::GetZ().
void G4PAIxSection::ComputeLowEnergyCof ()
Definition at line 779 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 779 of file G4PAIxSection.cc
References G4Material::GetMaterialTable().
G4double G4PAIxSection::DifPAIxSection (G4int intervalNumber, G4double betaGammaSq)
Definition at line 1225 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1225 of file G4PAIxSection.cc
References e, source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, source.hepunit::hbarc, pi, x1, x2, x3, x4, x5, and x6.
G4double G4PAIxSection::GetCerenkovEnergyTransfer ()
Definition at line 2335 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2335 of file G4PAIxSection.cc
References G4UniformRand, and position.
G4double G4PAIxSection::GetDifPAIxSection (G4int i) inline
Definition at line 180 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 180 of file G4PAIxSection.hh
References fDifPAIxSection.
G4double G4PAIxSection::GetElectronRange (G4double energy)
Definition at line 1129 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1129 of file G4PAIxSection.cc
References cm2, energy, Acts::UnitConstants::g, and keV.
G4double G4PAIxSection::GetEnergyInterval (G4int i) inline
Definition at line 178 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 178 of file G4PAIxSection.hh
References fEnergyInterval.
G4double G4PAIxSection::GetEnergyTransfer ()
Definition at line 2254 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2254 of file G4PAIxSection.cc
References G4UniformRand, and position.
G4double G4PAIxSection::GetIntegralCerenkov (G4int i) const inline
Definition at line 304 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 304 of file G4PAIxSection.hh
References CallError(), fIntegralCerenkov, and fSplineNumber.
G4double G4PAIxSection::GetIntegralMM (G4int i) const inline
Definition at line 310 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 310 of file G4PAIxSection.hh
References CallError(), fIntegralMM, and fSplineNumber.
G4double G4PAIxSection::GetIntegralPAIdEdx (G4int i) const inline
Definition at line 298 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 298 of file G4PAIxSection.hh
References CallError(), fIntegralPAIdEdx, and fSplineNumber.
G4double G4PAIxSection::GetIntegralPAIxSection (G4int i) const inline
Definition at line 292 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 292 of file G4PAIxSection.hh
References CallError(), fIntegralPAIxSection, and fSplineNumber.
G4double G4PAIxSection::GetIntegralPlasmon (G4int i) const inline
Definition at line 316 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 316 of file G4PAIxSection.hh
References CallError(), fIntegralPlasmon, and fSplineNumber.
G4double G4PAIxSection::GetIntegralResonance (G4int i) const inline
Definition at line 322 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 322 of file G4PAIxSection.hh
References CallError(), fIntegralResonance, and fSplineNumber.
G4int G4PAIxSection::GetIntervalNumber () const inline
Definition at line 176 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 176 of file G4PAIxSection.hh
References fIntervalNumber.
G4double G4PAIxSection::GetLorentzFactor (G4int i) const
Definition at line 597 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 597 of file G4PAIxSection.cc
G4double G4PAIxSection::GetLowEnergyCof () const inline
Definition at line 194 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 194 of file G4PAIxSection.hh
References fLowEnergyCof.
G4double G4PAIxSection::GetMeanCerenkovLoss () const inline
Definition at line 187 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 187 of file G4PAIxSection.hh
References fIntegralCerenkov.
G4double G4PAIxSection::GetMeanEnergyLoss () const inline
Definition at line 186 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 186 of file G4PAIxSection.hh
References fIntegralPAIxSection.
G4double G4PAIxSection::GetMeanMMLoss () const inline
Definition at line 188 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 188 of file G4PAIxSection.hh
References fIntegralMM.
G4double G4PAIxSection::GetMeanPlasmonLoss () const inline
Definition at line 189 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 189 of file G4PAIxSection.hh
References fIntegralPlasmon.
G4double G4PAIxSection::GetMeanResonanceLoss () const inline
Definition at line 190 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 190 of file G4PAIxSection.hh
References fIntegralResonance.
G4double G4PAIxSection::GetMMEnergyTransfer ()
Definition at line 2362 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2362 of file G4PAIxSection.cc
References G4UniformRand, and position.
G4double G4PAIxSection::GetNormalizationCof () const inline
Definition at line 192 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 192 of file G4PAIxSection.hh
References fNormalizationCof.
G4int G4PAIxSection::GetNumberOfGammas () const inline
Definition at line 172 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 172 of file G4PAIxSection.hh
References fNumberOfGammas.
G4double G4PAIxSection::GetPAIdNdxCerenkov (G4int i) inline
Definition at line 181 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 181 of file G4PAIxSection.hh
References fdNdxCerenkov.
G4double G4PAIxSection::GetPAIdNdxMM (G4int i) inline
Definition at line 182 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 182 of file G4PAIxSection.hh
References fdNdxMM.
G4double G4PAIxSection::GetPAIdNdxPlasmon (G4int i) inline
Definition at line 183 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 183 of file G4PAIxSection.hh
References fdNdxPlasmon.
G4double G4PAIxSection::GetPAIdNdxResonance (G4int i) inline
Definition at line 184 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 184 of file G4PAIxSection.hh
References fdNdxResonance.
G4double G4PAIxSection::GetPAItable (G4int i, G4int j) const inline
Definition at line 281 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 281 of file G4PAIxSection.hh
References fPAItable.
G4double G4PAIxSection::GetPhotonRange (G4double energy)
Definition at line 1096 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1096 of file G4PAIxSection.cc
References DBL_MAX, DBL_MIN, and G4InuclParticleNames::lambda.
G4double G4PAIxSection::GetPlasmonEnergyTransfer ()
Definition at line 2416 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2416 of file G4PAIxSection.cc
References G4UniformRand, and position.
G4double G4PAIxSection::GetResonanceEnergyTransfer ()
Definition at line 2471 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2471 of file G4PAIxSection.cc
References G4UniformRand, and position.
G4double G4PAIxSection::GetRutherfordEnergyTransfer ()
Definition at line 2499 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2499 of file G4PAIxSection.cc
References G4UniformRand, and position.
G4double G4PAIxSection::GetSplineEnergy (G4int i) const inline
Definition at line 286 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 286 of file G4PAIxSection.hh
References CallError(), fSplineEnergy, and fSplineNumber.
G4int G4PAIxSection::GetSplineSize () const inline
Definition at line 174 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 174 of file G4PAIxSection.hh
References fSplineNumber.
G4double G4PAIxSection::GetStepCerenkovLoss (G4double step)
Definition at line 2281 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2281 of file G4PAIxSection.cc
References G4Poisson(), and Acts::Test::step().
G4double G4PAIxSection::GetStepEnergyLoss (G4double step)
Definition at line 2227 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2227 of file G4PAIxSection.cc
References G4Poisson(), and Acts::Test::step().
G4double G4PAIxSection::GetStepMMLoss (G4double step)
Definition at line 2308 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2308 of file G4PAIxSection.cc
References G4Poisson(), and Acts::Test::step().
G4double G4PAIxSection::GetStepPlasmonLoss (G4double step)
Definition at line 2389 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2389 of file G4PAIxSection.cc
References G4Poisson(), and Acts::Test::step().
G4double G4PAIxSection::GetStepResonanceLoss (G4double step)
Definition at line 2443 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2443 of file G4PAIxSection.cc
References G4Poisson(), and Acts::Test::step().
G4double G4PAIxSection::ImPartDielectricConst (G4int intervalNumber, G4double energy)
Definition at line 1076 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1076 of file G4PAIxSection.cc
References source.hepunit::hbarc, and k.
void G4PAIxSection::Initialize (const G4Material * material, G4double maxEnergyTransfer, G4double betaGammaSq, G4SandiaTable * sandia)
Definition at line 606 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 606 of file G4PAIxSection.cc
References eV, G4cout, G4endl, G4Material::GetDensity(), G4Material::GetElectronDensity(), G4SandiaTable::GetLowerI1(), G4SandiaTable::GetMaxInterval(), G4SandiaTable::GetSandiaMatTablePAI(), and keV.
void G4PAIxSection::InitPAI ()
Definition at line 813 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 813 of file G4PAIxSection.cc
void G4PAIxSection::IntegralCerenkov ()
Definition at line 1522 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1522 of file G4PAIxSection.cc
References k.
void G4PAIxSection::IntegralMM ()
Definition at line 1553 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1553 of file G4PAIxSection.cc
References k.
void G4PAIxSection::IntegralPAIxSection ()
Definition at line 1490 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1490 of file G4PAIxSection.cc
References G4cout, G4endl, and k.
void G4PAIxSection::IntegralPlasmon ()
Definition at line 1584 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1584 of file G4PAIxSection.cc
References k.
void G4PAIxSection::IntegralResonance ()
Definition at line 1611 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1611 of file G4PAIxSection.cc
References k.
void G4PAIxSection::NormShift (G4double betaGammaSq)
Definition at line 873 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 873 of file G4PAIxSection.cc
References source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, G4cout, G4endl, source.hepunit::hbarc, k, keV, pi, and x.
G4PAIxSection& G4PAIxSection::operator= (const G4PAIxSection & right) private delete
G4double G4PAIxSection::PAIdNdxCerenkov (G4int intervalNumber, G4double betaGammaSq)
Definition at line 1302 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1302 of file G4PAIxSection.cc
References e, source.hepunit::fine_structure_const, source.hepunit::hbarc, pi, x3, and x5.
G4double G4PAIxSection::PAIdNdxMM (G4int intervalNumber, G4double betaGammaSq)
Definition at line 1360 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1360 of file G4PAIxSection.cc
References e, source.hepunit::fine_structure_const, source.hepunit::hbarc, pi, x3, and x5.
G4double G4PAIxSection::PAIdNdxPlasmon (G4int intervalNumber, G4double betaGammaSq)
Definition at line 1410 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1410 of file G4PAIxSection.cc
References e, source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, source.hepunit::hbarc, and pi.
G4double G4PAIxSection::PAIdNdxResonance (G4int intervalNumber, G4double betaGammaSq)
Definition at line 1450 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1450 of file G4PAIxSection.cc
References e, source.hepunit::electron_mass_c2, source.hepunit::fine_structure_const, source.hepunit::hbarc, and pi.
G4double G4PAIxSection::RePartDielectricConst (G4double energy)
Definition at line 1171 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1171 of file G4PAIxSection.cc
References c1, c2, source.hepunit::hbarc, pi, x1, and x2.
G4double G4PAIxSection::RutherfordIntegral (G4int intervalNumber, G4double limitLow, G4double limitHigh)
Definition at line 1055 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1055 of file G4PAIxSection.cc
References c1, c2, k, x1, and x2.
void G4PAIxSection::SetVerbose (G4int v) inline
Definition at line 198 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 198 of file G4PAIxSection.hh
References fVerbose, and v.
void G4PAIxSection::SplainPAI (G4double betaGammaSq)
Definition at line 950 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 950 of file G4PAIxSection.cc
References a, b, Acts::Test::delta, G4cout, G4endl, k, x, x1, x2, y, and y2.
G4double G4PAIxSection::SumOverBordCerenkov (G4int intervalNumber, G4double energy)
Definition at line 1990 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1990 of file G4PAIxSection.cc
References a, b, c, d, and x1.
G4double G4PAIxSection::SumOverBorder (G4int intervalNumber, G4double energy)
Definition at line 1862 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1862 of file G4PAIxSection.cc
References a, kdfinder::abs(), b, d, e, G4cout, G4endl, and x1.
G4double G4PAIxSection::SumOverBorderdEdx (G4int intervalNumber, G4double energy)
Definition at line 1935 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1935 of file G4PAIxSection.cc
References a, b, d, and x1.
G4double G4PAIxSection::SumOverBordMM (G4int intervalNumber, G4double energy)
Definition at line 2055 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2055 of file G4PAIxSection.cc
References a, b, c, d, and x1.
G4double G4PAIxSection::SumOverBordPlasmon (G4int intervalNumber, G4double energy)
Definition at line 2120 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2120 of file G4PAIxSection.cc
References a, b, c, d, and x1.
G4double G4PAIxSection::SumOverBordResonance (G4int intervalNumber, G4double energy)
Definition at line 2174 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 2174 of file G4PAIxSection.cc
References a, b, c, d, and x1.
G4double G4PAIxSection::SumOverInterCerenkov (G4int intervalNumber)
Definition at line 1719 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1719 of file G4PAIxSection.cc
References a, kdfinder::abs(), b, c, e, and x1.
G4double G4PAIxSection::SumOverInterMM (G4int intervalNumber)
Definition at line 1755 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1755 of file G4PAIxSection.cc
References a, kdfinder::abs(), b, c, e, and x1.
G4double G4PAIxSection::SumOverInterPlasmon (G4int intervalNumber)
Definition at line 1793 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1793 of file G4PAIxSection.cc
References a, kdfinder::abs(), b, c, e, and x1.
G4double G4PAIxSection::SumOverInterResonance (G4int intervalNumber)
Definition at line 1828 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1828 of file G4PAIxSection.cc
References a, kdfinder::abs(), b, c, e, and x1.
G4double G4PAIxSection::SumOverInterval (G4int intervalNumber)
Definition at line 1638 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1638 of file G4PAIxSection.cc
References a, kdfinder::abs(), b, c, e, G4cout, G4endl, and x1.
G4double G4PAIxSection::SumOverIntervaldEdx (G4int intervalNumber)
Definition at line 1685 of file G4PAIxSection.cc.
View newest version in sPHENIX GitHub at line 1685 of file G4PAIxSection.cc
References a, kdfinder::abs(), b, c, e, and x1.
Member Data Documentation
G4DataVector G4PAIxSection::fA1 private
Definition at line 249 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 249 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fA2 private
Definition at line 250 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 250 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fA3 private
Definition at line 251 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 251 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fA4 private
Definition at line 252 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 252 of file G4PAIxSection.hh
const G4double G4PAIxSection::fDelta = 0.005 static private
Definition at line 221 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 221 of file G4PAIxSection.hh
G4double G4PAIxSection::fDensity private
Definition at line 236 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 236 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fDifPAIxSection private
Definition at line 261 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 261 of file G4PAIxSection.hh
Referenced by GetDifPAIxSection().
G4DataVector G4PAIxSection::fdNdxCerenkov private
Definition at line 262 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 262 of file G4PAIxSection.hh
Referenced by GetPAIdNdxCerenkov().
G4DataVector G4PAIxSection::fdNdxMM private
Definition at line 264 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 264 of file G4PAIxSection.hh
Referenced by GetPAIdNdxMM().
G4DataVector G4PAIxSection::fdNdxPlasmon private
Definition at line 263 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 263 of file G4PAIxSection.hh
Referenced by GetPAIdNdxPlasmon().
G4DataVector G4PAIxSection::fdNdxResonance private
Definition at line 265 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 265 of file G4PAIxSection.hh
Referenced by GetPAIdNdxResonance().
G4double G4PAIxSection::fElectronDensity private
Definition at line 237 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 237 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fEnergyInterval private
Definition at line 248 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 248 of file G4PAIxSection.hh
Referenced by GetEnergyInterval().
const G4double G4PAIxSection::fError = 0.005 static private
Definition at line 222 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 222 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fImPartDielectricConst private
Definition at line 259 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 259 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fIntegralCerenkov private
Definition at line 269 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 269 of file G4PAIxSection.hh
Referenced by GetIntegralCerenkov(), and GetMeanCerenkovLoss().
G4DataVector G4PAIxSection::fIntegralMM private
Definition at line 271 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 271 of file G4PAIxSection.hh
Referenced by GetIntegralMM(), and GetMeanMMLoss().
G4DataVector G4PAIxSection::fIntegralPAIdEdx private
Definition at line 268 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 268 of file G4PAIxSection.hh
Referenced by GetIntegralPAIdEdx().
G4DataVector G4PAIxSection::fIntegralPAIxSection private
Definition at line 267 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 267 of file G4PAIxSection.hh
Referenced by GetIntegralPAIxSection(), and GetMeanEnergyLoss().
G4DataVector G4PAIxSection::fIntegralPlasmon private
Definition at line 270 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 270 of file G4PAIxSection.hh
Referenced by GetIntegralPlasmon(), and GetMeanPlasmonLoss().
G4DataVector G4PAIxSection::fIntegralResonance private
Definition at line 272 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 272 of file G4PAIxSection.hh
Referenced by GetIntegralResonance(), and GetMeanResonanceLoss().
G4DataVector G4PAIxSection::fIntegralTerm private
Definition at line 260 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 260 of file G4PAIxSection.hh
G4int G4PAIxSection::fIntervalNumber private
Definition at line 230 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 230 of file G4PAIxSection.hh
Referenced by GetIntervalNumber().
const G4double G4PAIxSection::fLorentzFactor static private
Initial value:
=
{
0.0,
1.094989e+00, 1.107813e+00, 1.122369e+00, 1.138890e+00, 1.157642e+00,
1.178925e+00, 1.203082e+00, 1.230500e+00, 1.261620e+00, 1.296942e+00,
1.337032e+00, 1.382535e+00, 1.434181e+00, 1.492800e+00, 1.559334e+00,
1.634850e+00, 1.720562e+00, 1.817845e+00, 1.928263e+00, 2.053589e+00,
2.195835e+00, 2.357285e+00, 2.540533e+00, 2.748522e+00, 2.984591e+00,
3.252533e+00, 3.556649e+00, 3.901824e+00, 4.293602e+00, 4.738274e+00,
5.242981e+00, 5.815829e+00, 6.466019e+00, 7.203990e+00, 8.041596e+00,
8.992288e+00, 1.007133e+01, 1.129606e+01, 1.268614e+01, 1.426390e+01,
1.605467e+01, 1.808721e+01, 2.039417e+01, 2.301259e+01, 2.598453e+01,
2.935771e+01, 3.318630e+01, 3.753180e+01, 4.246399e+01, 4.806208e+01,
5.441597e+01, 6.162770e+01, 6.981310e+01, 7.910361e+01, 8.964844e+01,
1.016169e+02, 1.152013e+02, 1.306197e+02, 1.481198e+02, 1.679826e+02,
1.905270e+02, 2.161152e+02, 2.451581e+02, 2.781221e+02, 3.155365e+02,
3.580024e+02, 4.062016e+02, 4.609081e+02, 5.230007e+02, 5.934765e+02,
6.734672e+02, 7.642575e+02, 8.673056e+02, 9.842662e+02, 1.117018e+03,
1.267692e+03, 1.438709e+03, 1.632816e+03, 1.853128e+03, 2.103186e+03,
2.387004e+03, 2.709140e+03, 3.074768e+03, 3.489760e+03, 3.960780e+03,
4.495394e+03, 5.102185e+03, 5.790900e+03, 6.572600e+03, 7.459837e+03,
8.466860e+03, 9.609843e+03, 1.090714e+04, 1.237959e+04, 1.405083e+04,
1.594771e+04, 1.810069e+04, 2.054434e+04, 2.331792e+04, 2.646595e+04,
3.003901e+04, 3.409446e+04, 3.869745e+04, 4.392189e+04, 4.985168e+04,
5.658206e+04, 6.422112e+04, 7.289153e+04, 8.273254e+04, 9.390219e+04,
1.065799e+05
}
Definition at line 225 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 225 of file G4PAIxSection.hh
G4double G4PAIxSection::fLowEnergyCof private
Definition at line 238 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 238 of file G4PAIxSection.hh
Referenced by GetLowEnergyCof().
G4int G4PAIxSection::fMaterialIndex private
Definition at line 235 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 235 of file G4PAIxSection.hh
G4OrderedTable* G4PAIxSection::fMatSandiaMatrix private
Definition at line 244 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 244 of file G4PAIxSection.hh
const G4int G4PAIxSection::fMaxSplineSize = 1000 static private
Definition at line 255 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 255 of file G4PAIxSection.hh
G4double G4PAIxSection::fNormalizationCof private
Definition at line 231 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 231 of file G4PAIxSection.hh
Referenced by GetNormalizationCof().
G4int G4PAIxSection::fNumberOfGammas = 111 static private
Definition at line 224 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 224 of file G4PAIxSection.hh
Referenced by GetNumberOfGammas().
G4double G4PAIxSection::fPAItable[500][112] private
Definition at line 274 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 274 of file G4PAIxSection.hh
Referenced by GetPAItable().
const G4int G4PAIxSection::fRefGammaNumber = 29 static private
Definition at line 228 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 228 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fRePartDielectricConst private
Definition at line 258 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 258 of file G4PAIxSection.hh
G4SandiaTable* G4PAIxSection::fSandia private
Definition at line 246 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 246 of file G4PAIxSection.hh
G4DataVector G4PAIxSection::fSplineEnergy private
Definition at line 257 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 257 of file G4PAIxSection.hh
Referenced by GetSplineEnergy().
G4int G4PAIxSection::fSplineNumber private
Definition at line 239 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 239 of file G4PAIxSection.hh
Referenced by GetIntegralCerenkov(), GetIntegralMM(), GetIntegralPAIdEdx(), GetIntegralPAIxSection(), GetIntegralPlasmon(), GetIntegralResonance(), GetSplineEnergy(), and GetSplineSize().
G4int G4PAIxSection::fVerbose private
Definition at line 240 of file G4PAIxSection.hh.
View newest version in sPHENIX GitHub at line 240 of file G4PAIxSection.hh
Referenced by SetVerbose().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PAIxSection.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4PAIxSection.cc