ECCE @ EIC Software: ExN04TrackerHit Class Reference
ExN04TrackerHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04TrackerHit.hh>
Public Member Functions
ExN04TrackerHit ()
~ExN04TrackerHit ()
ExN04TrackerHit (const ExN04TrackerHit &right)
const ExN04TrackerHit & operator= (const ExN04TrackerHit &right)
G4bool operator== (const ExN04TrackerHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
virtual void Draw ()
virtual void Print ()
void SetEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4ThreeVector GetPos ()
ExN04TrackerHit ()
~ExN04TrackerHit ()
ExN04TrackerHit (const ExN04TrackerHit &right)
const ExN04TrackerHit & operator= (const ExN04TrackerHit &right)
G4bool operator== (const ExN04TrackerHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
void Draw ()
void Print ()
void SetEdep (G4double de)
void SetPos (G4ThreeVector xyz)
G4double GetEdep () const
G4ThreeVector GetPos () const
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Private Attributes
G4double fEdep
G4ThreeVector fPos
G4ThreeVector pos
G4double edep
Detailed Description
Definition at line 39 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 39 of file ExN04TrackerHit.hh
Constructor & Destructor Documentation
ExN04TrackerHit::ExN04TrackerHit ()
Definition at line 41 of file ExN04TrackerHit.cc.
View newest version in sPHENIX GitHub at line 41 of file ExN04TrackerHit.cc
ExN04TrackerHit::~ExN04TrackerHit ()
Definition at line 47 of file ExN04TrackerHit.cc.
View newest version in sPHENIX GitHub at line 47 of file ExN04TrackerHit.cc
ExN04TrackerHit::ExN04TrackerHit (const ExN04TrackerHit & right)
Definition at line 52 of file ExN04TrackerHit.cc.
View newest version in sPHENIX GitHub at line 52 of file ExN04TrackerHit.cc
References fEdep, and fPos.
ExN04TrackerHit::ExN04TrackerHit ()
ExN04TrackerHit::~ExN04TrackerHit ()
ExN04TrackerHit::ExN04TrackerHit (const ExN04TrackerHit & right)
Member Function Documentation
void ExN04TrackerHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 74 of file ExN04TrackerHit.cc.
View newest version in sPHENIX GitHub at line 74 of file ExN04TrackerHit.cc
References G4VVisManager::Draw(), G4VMarker::filled, fPos, G4VVisManager::GetConcreteInstance(), G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
void ExN04TrackerHit::Draw () virtual
Reimplemented from G4VHit.
G4double ExN04TrackerHit::GetEdep () inline
Definition at line 55 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 55 of file ExN04TrackerHit.hh
References fEdep.
Referenced by MarshaledExN04TrackerHit::marshal2().
G4double ExN04TrackerHit::GetEdep () const inline
Definition at line 81 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 81 of file ExN04TrackerHit.hh
References edep.
G4ThreeVector ExN04TrackerHit::GetPos () inline
Definition at line 57 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 57 of file ExN04TrackerHit.hh
References fPos.
Referenced by MarshaledExN04TrackerHit::marshal1().
G4ThreeVector ExN04TrackerHit::GetPos () const inline
Definition at line 82 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 82 of file ExN04TrackerHit.hh
References pos.
void ExN04TrackerHit::operator delete (void * aHit) inline
Definition at line 76 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 76 of file ExN04TrackerHit.hh
References G4Allocator< Type >::FreeSingle().
void ExN04TrackerHit::operator delete (void * aHit) inline
void * ExN04TrackerHit::operator new (size_t) inline
Definition at line 69 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 69 of file ExN04TrackerHit.hh
References G4Allocator< Type >::MallocSingle().
void* ExN04TrackerHit::operator new (size_t) inline
const ExN04TrackerHit & ExN04TrackerHit::operator= (const ExN04TrackerHit & right)
Definition at line 60 of file ExN04TrackerHit.cc.
View newest version in sPHENIX GitHub at line 60 of file ExN04TrackerHit.cc
References fEdep, and fPos.
const ExN04TrackerHit& ExN04TrackerHit::operator= (const ExN04TrackerHit & right)
G4bool ExN04TrackerHit::operator== (const ExN04TrackerHit & right) const
Definition at line 68 of file ExN04TrackerHit.cc.
View newest version in sPHENIX GitHub at line 68 of file ExN04TrackerHit.cc
G4bool ExN04TrackerHit::operator== (const ExN04TrackerHit & right) const
void ExN04TrackerHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 90 of file ExN04TrackerHit.cc.
View newest version in sPHENIX GitHub at line 90 of file ExN04TrackerHit.cc
void ExN04TrackerHit::Print () virtual
Reimplemented from G4VHit.
void ExN04TrackerHit::SetEdep (G4double de) inline
Definition at line 54 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 54 of file ExN04TrackerHit.hh
References fEdep.
Referenced by ExN04TrackerSD::ProcessHits(), and MarshaledExN04TrackerHit::unmarshal2().
void ExN04TrackerHit::SetEdep (G4double de) inline
Definition at line 78 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 78 of file ExN04TrackerHit.hh
References edep.
void ExN04TrackerHit::SetPos (G4ThreeVector xyz) inline
Definition at line 56 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 56 of file ExN04TrackerHit.hh
References fPos.
Referenced by ExN04TrackerSD::ProcessHits(), and MarshaledExN04TrackerHit::unmarshal1().
void ExN04TrackerHit::SetPos (G4ThreeVector xyz) inline
Definition at line 79 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 79 of file ExN04TrackerHit.hh
References pos.
Member Data Documentation
G4double ExN04TrackerHit::edep private
Definition at line 71 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 71 of file ExN04TrackerHit.hh
Referenced by GetEdep(), and SetEdep().
G4double ExN04TrackerHit::fEdep private
Definition at line 60 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 60 of file ExN04TrackerHit.hh
Referenced by ExN04TrackerHit(), GetEdep(), operator=(), and SetEdep().
G4ThreeVector ExN04TrackerHit::fPos private
Definition at line 61 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 61 of file ExN04TrackerHit.hh
Referenced by Draw(), ExN04TrackerHit(), GetPos(), operator=(), and SetPos().
G4ThreeVector ExN04TrackerHit::pos private
Definition at line 67 of file ExN04TrackerHit.hh.
View newest version in sPHENIX GitHub at line 67 of file ExN04TrackerHit.hh
Referenced by GetPos(), and SetPos().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/include/ExN04TrackerHit.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/include/ExN04TrackerHit.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/HepMCEx01/src/ExN04TrackerHit.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/src/ExN04TrackerHit.cc