ECCE @ EIC Software: G4String Class Reference
G4String Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/G4String.hh>
Public Types
enum caseCompare { exact, ignoreCase }
enum stripType { leading, trailing, both }
Public Member Functions
G4String ()
G4String (char)
G4String (const char *)
G4String (const char *, str_size)
G4String (const G4String &)
G4String (const std::string &)
G4String (G4String &&)=default
~G4String ()
G4String & operator= (const G4String &)
G4String & operator= (const std::string &)
G4String & operator= (const char *)
G4String & operator= (G4String &&)=default
char operator() (str_size) const
char & operator() (str_size)
G4String & operator+= (const char *)
G4String & operator+= (const std::string &)
G4String & operator+= (const char &)
G4bool operator== (const G4String &) const
G4bool operator== (const char *) const
G4bool operator!= (const G4String &) const
G4bool operator!= (const char *) const
operator const char * () const
G4String operator() (str_size, str_size)
G4int compareTo (const char *, caseCompare mode=exact) const
G4int compareTo (const G4String &, caseCompare mode=exact) const
G4String & prepend (const char *)
G4String & append (const G4String &)
std::istream & readLine (std::istream &, G4bool skipWhite=true)
G4String & replace (unsigned int, unsigned int, const char *, unsigned int)
G4String & replace (str_size, str_size, const char *)
G4String & remove (str_size)
G4String & remove (str_size, str_size)
std::size_t first (char) const
std::size_t last (char) const
G4bool contains (const std::string &) const
G4bool contains (char) const
G4String strip (G4int strip_Type=trailing, char c=' ')
void toLower ()
void toUpper ()
G4bool isNull () const
str_size index (const char *, G4int pos=0) const
str_size index (char, G4int pos=0) const
str_size index (const G4String &, str_size, str_size, caseCompare) const
const char * data () const
G4int strcasecompare (const char *, const char *) const
unsigned int hash (caseCompare cmp=exact) const
unsigned int stlhash () const
Private Types
typedef std::string std_string
Private Attributes
int dummy
Detailed Description
Definition at line 45 of file G4String.hh.
View newest version in sPHENIX GitHub at line 45 of file G4String.hh
Member Typedef Documentation
typedef std::string G4String::std_string private
Definition at line 61 of file G4String.hh.
View newest version in sPHENIX GitHub at line 61 of file G4String.hh
Member Enumeration Documentation
enum G4String::caseCompare
Enumerator:
exact
ignoreCase
Definition at line 65 of file G4String.hh.
View newest version in sPHENIX GitHub at line 65 of file G4String.hh
enum G4String::stripType
Enumerator:
leading
trailing
both
Definition at line 66 of file G4String.hh.
View newest version in sPHENIX GitHub at line 66 of file G4String.hh
Constructor & Destructor Documentation
G4String::G4String () inline
G4String::G4String (char) inline
G4String::G4String (const char *) inline
G4String::G4String (const char * , str_size) inline
G4String::G4String (const G4String &) inline
G4String::G4String (const std::string &) inline
G4String::G4String (G4String &&) inline default
G4String::~G4String () inline
Definition at line 75 of file G4String.hh.
View newest version in sPHENIX GitHub at line 75 of file G4String.hh
Member Function Documentation
G4String& G4String::append (const G4String &) inline
Referenced by G4UIcommandTree::AddNewCommand(), G4AccumulableManager::CheckName(), G4UIGAG::CodeGenTclTree(), G4CascadeParamMessenger::CreateDirectory(), G4UImessenger::CreateDirectory(), G4UIcommand::DoIt(), G4UIcommandTree::FindCommandTree(), G4UIcommandTree::FindPath(), G4XmlNtupleManager::FinishTNtuple(), G4CloneDaughters(), G4CreateCloneVTE(), G4CreateCloneVTEWithDivision(), G4AccumulableManager::GenerateName(), G4UIGAG::GetCommand(), G4UIGainServer::GetCommand(), G4UIcsh::GetCommandLineString(), G4UItcsh::GetCommandLineString(), G4UImanager::GetCurrentStringValue(), G4BaseFileManager::GetFullFileName(), G4UIGAG::GetFullPath(), G4UIGainServer::GetFullPath(), G4XmlAnalysisReader::GetHandler(), G4BaseFileManager::GetHnFileName(), G4BaseFileManager::GetNtupleFileName(), G4BaseFileManager::GetPlotFileName(), G4tgrFileIn::GetWordsInLine(), main(), G4VUIshell::MakePrompt(), G4UItcsh::MakePrompt(), G4UIcommandTree::RemoveCommand(), G4UIGAG::SendAParamProperty(), G4UIGainServer::SendAParamProperty(), G4UIGAG::SendATclParamProperty(), G4PlotMessenger::SetLayoutCmd(), G4GDMLEvaluator::SolveBrackets(), G4BaseFileManager::TakeOffExtension(), and G4VAnalysisManager::WriteAscii().
G4int G4String::compareTo (const char * , caseCompare mode = exact) const inline
Referenced by G4VisCommandsViewerSet::SetNewValue(), G4VisCommandSceneHandlerCreate::SetNewValue(), and EICG4LumiSteppingAction::UserSteppingAction().
G4int G4String::compareTo (const G4String & , caseCompare mode = exact) const inline
G4bool G4String::contains (const std::string &) const inline
Referenced by EICG4dRICHDetector::ActivateVolumeTree(), G4AdjointStackingAction::ClassifyNewTrack(), G4GDMLParser::ExportRegions(), G4GDMLWrite::GenerateName(), PHG4GDMLWrite::GenerateName(), G3VolTableEntry::GetMasterClone(), EICG4dRICHDetector::GetPSST(), G4GDMLParser::ImportRegions(), G4VVisCommand::InterpolateViews(), G4AdjointTrackingAction::PreUserTrackingAction(), G4VisCommandViewerSave::SetNewValue(), G4ProcessTableMessenger::SetNumberOfProcessType(), and EICG4dRICHSteppingAction::UserSteppingAction().
G4bool G4String::contains (char) const inline
const char* G4String::data () const inline
Referenced by EICG4dRICHOptics::addSkinPropTable(), G4UImanager::ApplyCommand(), DicomHandler::CheckFileFormat(), EICG4dRICHDetector::ConstructMe(), G4PhysListRegistry::DeconstructPhysListName(), EICG4dRICHGas::EICG4dRICHGas(), EICG4dRICHOptics::EICG4dRICHOptics(), GetValues(), G4LatticeLogical::Load_NMap(), G4LatticeLogical::LoadMap(), PHG4ScoringManager::makeScoringHistograms(), MyFileReader::MyFileReader(), PG4gsdetu(), PG4gsmixt(), EICG4dRICHOptics::setMatPropTable(), G4OpticalPhysicsMessenger::SetNewValue(), EICG4dRICHGas::setOpticalParams(), G4UIparameter::TypeCheck(), G4PhysChemIO::FormattedText::WriteInto(), G4DNAChemistryManager::WriteInto(), G4UIparameter::Yylex(), and G4UIcommand::Yylex().
std::size_t G4String::first (char) const inline
Referenced by G4SDStructure::Activate(), G4VSceneHandler::AddCompound(), G4UIcommandTree::AddNewCommand(), CCalSensAssign::assign(), G4DNAModelInterface::BuildMaterialMolPerVolTable(), G4VLEPTSModel::BuildPhysicsTable(), G4HadronicProcess::CheckEnergyMomentumConservation(), DicomPhantomParameterisationColour::ComputeMaterial(), DicomNestedPhantomParameterisation::ComputeMaterial(), G4XDeltaNstarTable::CrossSectionTable(), G4XNNstarTable::CrossSectionTable(), G4XDeltaDeltastarTable::CrossSectionTable(), G4XNDeltastarTable::CrossSectionTable(), G4PSHitsModel::DescribeYourselfTo(), G4GDMLReadStructure::DivisionvolRead(), G4TrajectoryDrawByEncounteredVolume::Draw(), G4VScoreWriter::DumpAllQuantitiesToFile(), G4SDStructure::ExtractDirName(), G4UIcommandTree::FindCommandTree(), G4UIcommandTree::FindPath(), G4SDStructure::FindSensitiveDetector(), G4tgbGeometryDumper::FindSolidName(), G4tgbGeometryDumper::GetIsotopeName(), G3VolTableEntry::GetMasterClone(), G4tgbGeometryDumper::GetObjectName(), G4AttValueFilterT< T, ConversionErrorPolicy >::GetValidElement(), PHG4MvtxDetector::IsInMvtx(), PHG4EICMvtxDetector::IsInMvtx(), G4tgbGeometryDumper::LookForExistingRotation(), PHG4ScoringManager::makeScoringHistograms(), G4BaryonWidth::MassDependentWidth(), Run::Merge(), G4GDMLReadStructure::PhysvolRead(), G4UIcommandTree::RemoveCommand(), G4GDMLReadStructure::ReplicaRead(), and ScoreSpecies::WriteWithAnalysisManager().
unsigned int G4String::hash (caseCompare cmp = exact) const inline
str_size G4String::index (const char * , G4int pos = 0) const inline
Referenced by G4UImanager::ApplyCommand(), G4VBasicShell::Complete(), G4UItcsh::CompleteCommand(), G4UIcommandTree::CompleteCommandPath(), G4UIcommandTree::CreateFileName(), G4UIcommand::DoIt(), G4UIterminal::ExecuteCommand(), G4VBasicShell::FindCommand(), G4UIcommandTree::FindCommandTree(), G4VBasicShell::FindDirectory(), G4UImanager::FindDirectory(), G4UIGAG::FindDirPath(), G4UIGainServer::FindDirPath(), G4UIcommandTree::FindPath(), G4UIArrayString::G4UIArrayString(), G4VUIshell::GetAbsCommandDirPath(), G4HCtable::GetCollectionID(), G4DCtable::GetCollectionID(), G4VUIshell::GetCommandTree(), G4VUIshell::ListCommand(), G4VBasicShell::ModifyToFullPathCommand(), G4UImanager::ParseMacroSearchPath(), G4RunManager::RestoreRandomNumberStatus(), G4UImanager::SetAlias(), G4UImanager::SolveAlias(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), and G4UIGainServer::TerminalHelp().
str_size G4String::index (char , G4int pos = 0) const inline
str_size G4String::index (const G4String & , str_size , str_size , caseCompare) const inline
G4bool G4String::isNull () const inline
Referenced by G4SDStructure::Activate(), G4UIcommandTree::AddNewCommand(), G4SDStructure::AddNewDetector(), G4UImanager::ApplyCommand(), G4UIparameter::CheckNewValue(), G4UIcommand::CheckNewValue(), G4UIcommand::DoIt(), G4TrajectoryDrawByAttribute::Draw(), G4UImanager::GetCurrentStringValue(), GetValues(), G4ParticleGunMessenger::IonCommand(), G4GeneralParticleSourceMessenger::IonCommand(), G4ParticleGunMessenger::IonLevelCommand(), G4GeneralParticleSourceMessenger::IonLvlCommand(), G4UIparameter::List(), G4UIcommand::List(), G4PhysicalVolumesSearchScene::Matcher::Matcher(), G4VBasicShell::ModifyToFullPathCommand(), G4FilecoutDestination::Open(), G4VisListManager< T >::Print(), G4VisFilterManager< T >::Print(), G4UIcommandTree::RemoveCommand(), G4VisCommandModelCreate< Factory >::SetNewValue(), G4PolarizationMessenger::SetNewValue(), G4ProcessTableMessenger::SetNewValue(), DMXParticleSourceMessenger::SetNewValue(), G4UIcontrolMessenger::SetNewValue(), G4VisCommandSetTouchable::SetNewValue(), G4VUserPhysicsList::SetPhysicsTableRetrieved(), G4UIGAG::ShowCurrent(), G4VBasicShell::ShowCurrent(), G4UIGainServer::ShowCurrent(), G4TextPPReporter::SparseOption(), G4HtmlPPReporter::SparseOption(), G4TextPPRetriever::SparseOption(), and G4VUserPhysicsList::StorePhysicsTable().
std::size_t G4String::last (char) const inline
Referenced by G4UItcsh::CompleteCommand(), G4UIcommandTree::CompleteCommandPath(), G4SDStructure::G4SDStructure(), G4VSensitiveDetector::G4VSensitiveDetector(), G4VUIshell::GetAbsCommandDirPath(), G4UItcsh::ListMatchedCommand(), G4UIGAG::ModifyPrefix(), G4UIGainServer::ModifyPrefix(), and G4LatticeReader::OpenFile().
G4String::operator const char * () const inline
G4bool G4String::operator!= (const G4String &) const inline
G4bool G4String::operator!= (const char *) const inline
char G4String::operator() (str_size) const inline
char& G4String::operator() (str_size) inline
G4String G4String::operator() (str_size , str_size) inline
G4String& G4String::operator+= (const char *) inline
G4String& G4String::operator+= (const std::string &) inline
G4String& G4String::operator+= (const char &) inline
G4String& G4String::operator= (const G4String &) inline
G4String& G4String::operator= (const std::string &) inline
G4String& G4String::operator= (const char *) inline
G4String& G4String::operator= (G4String &&) inline default
G4bool G4String::operator== (const G4String &) const inline
G4bool G4String::operator== (const char *) const inline
G4String& G4String::prepend (const char *) inline
Referenced by G4SDManager::Activate(), G4SDStructure::AddNewDetector(), G4SDManager::AddNewDetector(), G4CascadeParamMessenger::CreateDirectory(), G4SDManager::FindSensitiveDetector(), G4VSensitiveDetector::G4VSensitiveDetector(), G4UIGAG::TerminalHelp(), and G4UIGainServer::TerminalHelp().
std::istream& G4String::readLine (std::istream & , G4bool skipWhite = true) inline
Referenced by G3CLRead(), G4UIGAG::GetCommand(), G4UIGainServer::GetCommand(), and G4UIcsh::GetCommandLineString().
G4String& G4String::remove (str_size) inline
Referenced by G4SDStructure::Activate(), G4UIcommandTree::AddNewCommand(), G4SDStructure::AddNewDetector(), G4UImanager::ApplyCommand(), G4UItcsh::CompleteCommand(), G4UIcommandTree::CompleteCommandPath(), G4SDStructure::ExtractDirName(), G4UIcommandTree::FindCommandTree(), G4UIcommandTree::FindPath(), G4SDStructure::FindSensitiveDetector(), G4SDStructure::G4SDStructure(), G4VSensitiveDetector::G4VSensitiveDetector(), G4VUIshell::GetAbsCommandDirPath(), G4MPIsession::GetCommand(), G4ZMQServer::GetCommand(), G4UIGAG::GetCommand(), G4UIterminal::GetCommand(), G4UIGainServer::GetCommand(), G4UIcsh::GetCommandLineString(), G4UItcsh::GetCommandLineString(), G4UItcsh::ListMatchedCommand(), G4AdjointTrackingAction::PostUserTrackingAction(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4UIcommandTree::RemoveCommand(), G4GDMLRead::Strip(), and G4GDMLRead::StripName().
G4String& G4String::remove (str_size , str_size) inline
G4String& G4String::replace (unsigned int, unsigned int, const char * , unsigned int) inline
Referenced by G4VMPIsession::BypassCommand(), G4MPIbatch::ReadCommand(), and G4UIbatch::ReadCommand().
G4String& G4String::replace (str_size , str_size , const char *) inline
unsigned int G4String::stlhash () const inline
G4int G4String::strcasecompare (const char * , const char *) const inline
G4String G4String::strip (G4int strip_Type = trailing, char c = ' ') inline
Referenced by G4VBasicShell::ApplyShellCommand(), G4VBasicShell::ChangeDirectory(), G4UIGAG::ChangeDirectory(), G4UIGainServer::ChangeDirectory(), G4VBasicShell::ChangeDirectoryCommand(), G4VBasicShell::Complete(), G4UItcsh::CompleteCommand(), F04DetectorConstruction::ConstructDetector(), G4ConversionUtils::Convert(), G4VBasicShell::FindCommand(), G4VBasicShell::FindDirectory(), G4UImanager::FindDirectory(), G4gsmate(), G4UIArrayString::G4UIArrayString(), G4UItcsh::G4UItcsh(), G4VisCommandSceneHandlerCreate::G4VisCommandSceneHandlerCreate(), G4VViewer::G4VViewer(), G4MPIsession::GetCommand(), G4ZMQServer::GetCommand(), G4UIGAG::GetCommand(), G4UIterminal::GetCommand(), G4UIGainServer::GetCommand(), G4UIcsh::GetCommandLineString(), G4VUIshell::GetCommandTree(), G4UIGAG::GetFullPath(), G4UIGainServer::GetFullPath(), GetValues(), G4VUIshell::ListCommand(), G4UIGAG::ListDirectory(), G4VBasicShell::ListDirectory(), G4UIGainServer::ListDirectory(), G4UItcsh::ListMatchedCommand(), G4RadioactiveDecayBase::LoadDecayTable(), G4RadioactiveDecay::LoadDecayTable(), G4VBasicShell::ModifyToFullPathCommand(), G4MPIbatch::ReadCommand(), G4UIbatch::ReadCommand(), readName(), G4UImanager::RemoveAlias(), G4UIExecutive::SelectSessionByFile(), G4VViewer::SetName(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandViewerCreate::SetNewValue(), split(), G4AttCheck::Standard(), G4UIGAG::TerminalHelp(), G4VBasicShell::TerminalHelp(), G4UIGainServer::TerminalHelp(), and G4VisManager::ViewerShortName().
void G4String::toLower () inline
Referenced by G4Colour::AddToMap(), G4HnMessenger::G4HnMessenger(), G4UIExecutive::G4UIExecutive(), G4Colour::GetColour(), G4BaseFileManager::GetFileType(), G4VisManager::GetVerbosityValue(), G4LatticeReader::ReadMapInfo(), G4UIExecutive::SelectSessionByFile(), G4VisFilterManager< T >::SetMode(), G4INCLXXInterfaceMessenger::SetNewValue(), and G4AnalysisMessengerHelper::Update().
void G4String::toUpper () inline
Referenced by G4UIcommand::ConvertToBool(), G4UImessenger::StoB(), G4UIparameter::TypeCheck(), and G4AnalysisMessengerHelper::Update().
Member Data Documentation
int G4String::dummy private
Definition at line 47 of file G4String.hh.
View newest version in sPHENIX GitHub at line 47 of file G4String.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/G4String.hh
geant4/tree/geant4-10.6-release/source/global/management/include/G4String.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/AnnotatedFiles/G4String.hh