ECCE @ EIC Software: G4PSCylinderSurfaceCurrent Class Reference
G4PSCylinderSurfaceCurrent Class Reference
#include <geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSCylinderSurfaceCurrent.hh>
Public Member Functions
G4PSCylinderSurfaceCurrent (G4String name, G4int direction, G4int depth=0)
G4PSCylinderSurfaceCurrent (G4String name, G4int direction, const G4String &unit, G4int depth=0)
virtual ~G4PSCylinderSurfaceCurrent ()
void Weighted (G4bool flg=true)
void DivideByArea (G4bool flg=true)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
virtual void SetUnit (const G4String &unit)
Public Member Functions inherited from G4VPrimitiveScorer
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)
G4int IsSelectedSurface (G4Step *, G4Tubs *)
virtual void DefineUnitAndCategory ()
Protected Member Functions inherited from G4VPrimitiveScorer
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Private Attributes
G4int HCID
G4int fDirection
G4THitsMap< G4double > * EvtMap
G4bool weighted
G4bool divideByArea
Additional Inherited Members
Protected Attributes inherited from G4VPrimitiveScorer
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Detailed Description
Definition at line 57 of file G4PSCylinderSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 57 of file G4PSCylinderSurfaceCurrent.hh
Constructor & Destructor Documentation
G4PSCylinderSurfaceCurrent::G4PSCylinderSurfaceCurrent (G4String name, G4int direction, G4int depth = 0)
Definition at line 56 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 56 of file G4PSCylinderSurfaceCurrent.cc
References DefineUnitAndCategory(), and SetUnit().
G4PSCylinderSurfaceCurrent::G4PSCylinderSurfaceCurrent (G4String name, G4int direction, const G4String & unit, G4int depth = 0)
Definition at line 65 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 65 of file G4PSCylinderSurfaceCurrent.cc
References DefineUnitAndCategory(), and SetUnit().
G4PSCylinderSurfaceCurrent::~G4PSCylinderSurfaceCurrent () virtual
Definition at line 76 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 76 of file G4PSCylinderSurfaceCurrent.cc
Member Function Documentation
void G4PSCylinderSurfaceCurrent::clear (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 170 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 170 of file G4PSCylinderSurfaceCurrent.cc
References G4VTHitsMap< T, Map_t >::clear(), and EvtMap.
void G4PSCylinderSurfaceCurrent::DefineUnitAndCategory () protected virtual
Definition at line 212 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 212 of file G4PSCylinderSurfaceCurrent.cc
References cm2, m2, and mm2.
Referenced by G4PSCylinderSurfaceCurrent().
void G4PSCylinderSurfaceCurrent::DivideByArea (G4bool flg = true) inline
Definition at line 70 of file G4PSCylinderSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 70 of file G4PSCylinderSurfaceCurrent.hh
References divideByArea.
void G4PSCylinderSurfaceCurrent::DrawAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 174 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 174 of file G4PSCylinderSurfaceCurrent.cc
void G4PSCylinderSurfaceCurrent::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 167 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 167 of file G4PSCylinderSurfaceCurrent.cc
void G4PSCylinderSurfaceCurrent::Initialize (G4HCofThisEvent * HCE) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 160 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 160 of file G4PSCylinderSurfaceCurrent.cc
References G4HCofThisEvent::AddHitsCollection(), G4VPrimitiveScorer::detector, EvtMap, G4VPrimitiveScorer::GetCollectionID(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), and HCID.
G4int G4PSCylinderSurfaceCurrent::IsSelectedSurface (G4Step * aStep, G4Tubs * tubsSolid) protected
Definition at line 123 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 123 of file G4PSCylinderSurfaceCurrent.cc
References fCurrent_In, fCurrent_Out, fGeomBoundary, G4VTouchable::GetHistory(), G4Tubs::GetInnerRadius(), G4GeometryTolerance::GetInstance(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetStepStatus(), G4GeometryTolerance::GetSurfaceTolerance(), G4NavigationHistory::GetTopTransform(), G4StepPoint::GetTouchableHandle(), G4Tubs::GetZHalfLength(), kCarTolerance, G4AffineTransform::TransformPoint(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by ProcessHits().
void G4PSCylinderSurfaceCurrent::PrintAll (void) virtual
Reimplemented from G4VPrimitiveScorer.
Definition at line 177 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 177 of file G4PSCylinderSurfaceCurrent.cc
References G4VPrimitiveScorer::detector, divideByArea, G4VTHitsMap< T, Map_t >::entries(), EvtMap, G4cout, G4endl, G4VTHitsMap< T, Map_t >::GetMap(), G4VPrimitiveScorer::GetName(), G4VSensitiveDetector::GetName(), G4VPrimitiveScorer::GetUnit(), and G4VPrimitiveScorer::GetUnitValue().
G4bool G4PSCylinderSurfaceCurrent::ProcessHits (G4Step * aStep, G4TouchableHistory *) protected virtual
Implements G4VPrimitiveScorer.
Definition at line 79 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 79 of file G4PSCylinderSurfaceCurrent.cc
References G4VTHitsMap< T, Map_t >::add(), G4VSolid::ComputeDimensions(), G4VPVParameterisation::ComputeSolid(), divideByArea, EvtMap, fCurrent_InOut, fDirection, G4Tubs::GetDeltaPhiAngle(), G4VPrimitiveScorer::GetIndex(), G4Tubs::GetInnerRadius(), G4VPhysicalVolume::GetLogicalVolume(), G4VPhysicalVolume::GetParameterisation(), G4StepPoint::GetPhysicalVolume(), G4Step::GetPreStepPoint(), G4LogicalVolume::GetSolid(), G4StepPoint::GetTouchable(), G4StepPoint::GetTouchableHandle(), G4StepPoint::GetWeight(), G4Tubs::GetZHalfLength(), incremental_prev_tag::idx, G4VPrimitiveScorer::indexDepth, IsSelectedSurface(), radian, square(), TRUE, and weighted.
void G4PSCylinderSurfaceCurrent::SetUnit (const G4String & unit) virtual
Definition at line 196 of file G4PSCylinderSurfaceCurrent.cc.
View newest version in sPHENIX GitHub at line 196 of file G4PSCylinderSurfaceCurrent.cc
References G4VPrimitiveScorer::CheckAndSetUnit(), divideByArea, G4Exception(), G4VPrimitiveScorer::GetName(), G4VPrimitiveScorer::GetUnit(), JustWarning, G4VPrimitiveScorer::unitName, and G4VPrimitiveScorer::unitValue.
Referenced by G4PSCylinderSurfaceCurrent(), and G4PSCylinderSurfaceCurrent3D::G4PSCylinderSurfaceCurrent3D().
void G4PSCylinderSurfaceCurrent::Weighted (G4bool flg = true) inline
Definition at line 67 of file G4PSCylinderSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PSCylinderSurfaceCurrent.hh
References weighted.
Member Data Documentation
G4bool G4PSCylinderSurfaceCurrent::divideByArea private
Definition at line 95 of file G4PSCylinderSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 95 of file G4PSCylinderSurfaceCurrent.hh
Referenced by DivideByArea(), PrintAll(), ProcessHits(), and SetUnit().
G4THitsMap<G4double>* G4PSCylinderSurfaceCurrent::EvtMap private
Definition at line 93 of file G4PSCylinderSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PSCylinderSurfaceCurrent.hh
Referenced by clear(), Initialize(), PrintAll(), and ProcessHits().
G4int G4PSCylinderSurfaceCurrent::fDirection private
Definition at line 92 of file G4PSCylinderSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 92 of file G4PSCylinderSurfaceCurrent.hh
Referenced by ProcessHits().
G4int G4PSCylinderSurfaceCurrent::HCID private
Definition at line 91 of file G4PSCylinderSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 91 of file G4PSCylinderSurfaceCurrent.hh
Referenced by Initialize().
G4bool G4PSCylinderSurfaceCurrent::weighted private
Definition at line 94 of file G4PSCylinderSurfaceCurrent.hh.
View newest version in sPHENIX GitHub at line 94 of file G4PSCylinderSurfaceCurrent.hh
Referenced by ProcessHits(), and Weighted().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/include/G4PSCylinderSurfaceCurrent.hh
geant4/tree/geant4-10.6-release/source/digits_hits/scorer/src/G4PSCylinderSurfaceCurrent.cc