ECCE @ EIC Software: GammaRayTelHadronPhysics Class Reference
GammaRayTelHadronPhysics Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelHadronPhysics.hh>
Public Member Functions
GammaRayTelHadronPhysics (const G4String &name="hadron")
virtual ~GammaRayTelHadronPhysics ()
void ConstructParticle ()
void ConstructProcess ()
Public Member Functions inherited from G4VPhysicsConstructor
G4VPhysicsConstructor (const G4String &="")
G4VPhysicsConstructor (const G4String &name, G4int physics_type)
virtual ~G4VPhysicsConstructor ()
void SetPhysicsName (const G4String &="")
const G4String & GetPhysicsName () const
void SetPhysicsType (G4int)
G4int GetPhysicsType () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker ()
Protected Attributes
G4HadronElasticProcess theElasticProcess
G4HadronElastic * theElasticModel
G4PionPlusInelasticProcess thePionPlusInelastic
G4hMultipleScattering thePionPlusMult
G4hIonisation thePionPlusIonisation
G4PionMinusInelasticProcess thePionMinusInelastic
G4hMultipleScattering thePionMinusMult
G4hIonisation thePionMinusIonisation
G4PiMinusAbsorptionBertini thePionMinusAbsorption
G4TheoFSGenerator * theModel
G4ExcitationHandler theHandler
G4PreCompoundModel * thePreEquilib
G4GeneratorPrecompoundInterface * theCascade
G4FTFModel * theStringModel
G4QGSMFragmentation theFragmentation
G4ExcitedStringDecay * theStringDecay
G4KaonPlusInelasticProcess theKaonPlusInelastic
G4hMultipleScattering theKaonPlusMult
G4hIonisation theKaonPlusIonisation
G4KaonMinusInelasticProcess theKaonMinusInelastic
G4hMultipleScattering theKaonMinusMult
G4hIonisation theKaonMinusIonisation
G4KaonMinusAbsorptionBertini theKaonMinusAbsorption
G4KaonZeroLInelasticProcess theKaonZeroLInelastic
G4KaonZeroSInelasticProcess theKaonZeroSInelastic
G4ProtonInelasticProcess theProtonInelastic
G4hMultipleScattering theProtonMult
G4hIonisation theProtonIonisation
G4AntiProtonInelasticProcess theAntiProtonInelastic
G4hMultipleScattering theAntiProtonMult
G4hIonisation theAntiProtonIonisation
G4AntiProtonAbsorptionFritiof theAntiProtonAnnihilation
G4NeutronInelasticProcess theNeutronInelastic
G4HadronFissionProcess theNeutronFission
G4LFission * theNeutronFissionModel
G4HadronCaptureProcess * theNeutronCapture
G4AntiNeutronInelasticProcess theAntiNeutronInelastic
Protected Attributes inherited from G4VPhysicsConstructor
G4int verboseLevel
G4String namePhysics
G4int typePhysics
G4ParticleTable * theParticleTable
G4int g4vpcInstanceID
Additional Inherited Members
Static Public Member Functions inherited from G4VPhysicsConstructor
static const G4VPCManager & GetSubInstanceManager ()
Protected Types inherited from G4VPhysicsConstructor
using PhysicsBuilder_V = G4VPCData::PhysicsBuilders_V
Protected Member Functions inherited from G4VPhysicsConstructor
G4bool RegisterProcess (G4VProcess *process, G4ParticleDefinition *particle)
G4ParticleTable::G4PTblDicIterator * GetParticleIterator () const
PhysicsBuilder_V GetBuilders () const
void AddBuilder (G4PhysicsBuilderInterface *bld)
Static Protected Attributes inherited from G4VPhysicsConstructor
static G4RUN_DLL G4VPCManager subInstanceManager
Detailed Description
Definition at line 94 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 94 of file GammaRayTelHadronPhysics.hh
Constructor & Destructor Documentation
GammaRayTelHadronPhysics::GammaRayTelHadronPhysics (const G4String & name = "hadron")
Definition at line 39 of file GammaRayTelHadronPhysics.cc.
View newest version in sPHENIX GitHub at line 39 of file GammaRayTelHadronPhysics.cc
GammaRayTelHadronPhysics::~GammaRayTelHadronPhysics () virtual
Definition at line 43 of file GammaRayTelHadronPhysics.cc.
View newest version in sPHENIX GitHub at line 43 of file GammaRayTelHadronPhysics.cc
References theStringDecay.
Member Function Documentation
void GammaRayTelHadronPhysics::ConstructParticle (void) inline virtual
Implements G4VPhysicsConstructor.
Definition at line 103 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 103 of file GammaRayTelHadronPhysics.hh
void GammaRayTelHadronPhysics::ConstructProcess (void) virtual
Implements G4VPhysicsConstructor.
Definition at line 52 of file GammaRayTelHadronPhysics.cc.
View newest version in sPHENIX GitHub at line 52 of file GammaRayTelHadronPhysics.cc
References G4HadronicProcess::AddDataSet(), G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4ProcessManager::AddRestProcess(), G4AntiNeutron::AntiNeutron(), G4AntiProton::AntiProton(), G4ChipsKaonMinusInelasticXS::Default_Name(), G4ChipsKaonPlusInelasticXS::Default_Name(), G4ChipsKaonZeroInelasticXS::Default_Name(), eV, G4HadronicParameters::GetMaxEnergy(), G4ParticleDefinition::GetProcessManager(), GeV, idxAlongStep, idxPostStep, G4HadronicParameters::Instance(), G4CrossSectionDataSetRegistry::Instance(), G4InuclParticleNames::kaonMinus, G4KaonMinus::KaonMinusDefinition(), G4InuclParticleNames::kaonPlus, G4KaonPlus::KaonPlusDefinition(), G4KaonZeroLong::KaonZeroLong(), G4KaonZeroShort::KaonZeroShort(), G4Neutron::Neutron(), ordDefault, ordInActive, G4InuclParticleNames::pion(), G4InuclParticleNames::pionMinus, G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), G4Proton::Proton(), G4HadronicProcess::RegisterMe(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4ProcessManager::SetProcessOrdering(), G4TheoFSGenerator::SetTransport(), theAntiNeutronInelastic, theAntiProtonAnnihilation, theAntiProtonInelastic, theAntiProtonIonisation, theAntiProtonMult, theCascade, theElasticModel, theElasticProcess, theKaonMinusAbsorption, theKaonMinusInelastic, theKaonMinusIonisation, theKaonMinusMult, theKaonPlusInelastic, theKaonPlusIonisation, theKaonPlusMult, theKaonZeroLInelastic, theKaonZeroSInelastic, theModel, theNeutronCapture, theNeutronFission, theNeutronFissionModel, theNeutronInelastic, thePionMinusAbsorption, thePionMinusInelastic, thePionMinusIonisation, thePionMinusMult, thePionPlusInelastic, thePionPlusIonisation, thePionPlusMult, thePreEquilib, theProtonInelastic, theProtonIonisation, theProtonMult, theStringDecay, and theStringModel.
Member Data Documentation
G4AntiNeutronInelasticProcess GammaRayTelHadronPhysics::theAntiNeutronInelastic protected
Definition at line 171 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 171 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4AntiProtonAbsorptionFritiof GammaRayTelHadronPhysics::theAntiProtonAnnihilation protected
Definition at line 162 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 162 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4AntiProtonInelasticProcess GammaRayTelHadronPhysics::theAntiProtonInelastic protected
Definition at line 159 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 159 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hIonisation GammaRayTelHadronPhysics::theAntiProtonIonisation protected
Definition at line 161 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 161 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hMultipleScattering GammaRayTelHadronPhysics::theAntiProtonMult protected
Definition at line 160 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 160 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4GeneratorPrecompoundInterface* GammaRayTelHadronPhysics::theCascade protected
Definition at line 131 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 131 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4HadronElastic* GammaRayTelHadronPhysics::theElasticModel protected
Definition at line 113 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 113 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4HadronElasticProcess GammaRayTelHadronPhysics::theElasticProcess protected
Definition at line 112 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 112 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4QGSMFragmentation GammaRayTelHadronPhysics::theFragmentation protected
Definition at line 133 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 133 of file GammaRayTelHadronPhysics.hh
G4ExcitationHandler GammaRayTelHadronPhysics::theHandler protected
Definition at line 129 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 129 of file GammaRayTelHadronPhysics.hh
G4KaonMinusAbsorptionBertini GammaRayTelHadronPhysics::theKaonMinusAbsorption protected
Definition at line 145 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 145 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4KaonMinusInelasticProcess GammaRayTelHadronPhysics::theKaonMinusInelastic protected
Definition at line 142 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 142 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hIonisation GammaRayTelHadronPhysics::theKaonMinusIonisation protected
Definition at line 144 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 144 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hMultipleScattering GammaRayTelHadronPhysics::theKaonMinusMult protected
Definition at line 143 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 143 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4KaonPlusInelasticProcess GammaRayTelHadronPhysics::theKaonPlusInelastic protected
Definition at line 137 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 137 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hIonisation GammaRayTelHadronPhysics::theKaonPlusIonisation protected
Definition at line 139 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 139 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hMultipleScattering GammaRayTelHadronPhysics::theKaonPlusMult protected
Definition at line 138 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 138 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4KaonZeroLInelasticProcess GammaRayTelHadronPhysics::theKaonZeroLInelastic protected
Definition at line 148 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 148 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4KaonZeroSInelasticProcess GammaRayTelHadronPhysics::theKaonZeroSInelastic protected
Definition at line 151 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 151 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4TheoFSGenerator* GammaRayTelHadronPhysics::theModel protected
Definition at line 128 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 128 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4HadronCaptureProcess* GammaRayTelHadronPhysics::theNeutronCapture protected
Definition at line 168 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 168 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4HadronFissionProcess GammaRayTelHadronPhysics::theNeutronFission protected
Definition at line 166 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 166 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4LFission* GammaRayTelHadronPhysics::theNeutronFissionModel protected
Definition at line 167 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 167 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4NeutronInelasticProcess GammaRayTelHadronPhysics::theNeutronInelastic protected
Definition at line 165 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 165 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4PiMinusAbsorptionBertini GammaRayTelHadronPhysics::thePionMinusAbsorption protected
Definition at line 124 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 124 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4PionMinusInelasticProcess GammaRayTelHadronPhysics::thePionMinusInelastic protected
Definition at line 121 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 121 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hIonisation GammaRayTelHadronPhysics::thePionMinusIonisation protected
Definition at line 123 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 123 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hMultipleScattering GammaRayTelHadronPhysics::thePionMinusMult protected
Definition at line 122 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 122 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4PionPlusInelasticProcess GammaRayTelHadronPhysics::thePionPlusInelastic protected
Definition at line 116 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 116 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hIonisation GammaRayTelHadronPhysics::thePionPlusIonisation protected
Definition at line 118 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 118 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hMultipleScattering GammaRayTelHadronPhysics::thePionPlusMult protected
Definition at line 117 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 117 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4PreCompoundModel* GammaRayTelHadronPhysics::thePreEquilib protected
Definition at line 130 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 130 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4ProtonInelasticProcess GammaRayTelHadronPhysics::theProtonInelastic protected
Definition at line 154 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 154 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hIonisation GammaRayTelHadronPhysics::theProtonIonisation protected
Definition at line 156 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 156 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4hMultipleScattering GammaRayTelHadronPhysics::theProtonMult protected
Definition at line 155 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 155 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
G4ExcitedStringDecay* GammaRayTelHadronPhysics::theStringDecay protected
Definition at line 134 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 134 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess(), and ~GammaRayTelHadronPhysics().
G4FTFModel* GammaRayTelHadronPhysics::theStringModel protected
Definition at line 132 of file GammaRayTelHadronPhysics.hh.
View newest version in sPHENIX GitHub at line 132 of file GammaRayTelHadronPhysics.hh
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/include/GammaRayTelHadronPhysics.hh
geant4/tree/geant4-10.6-release/examples/advanced/gammaray_telescope/src/GammaRayTelHadronPhysics.cc