ECCE @ EIC Software: DicomPartialDetectorConstruction Class Reference
DicomPartialDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomPartialDetectorConstruction.hh>
Public Member Functions
DicomPartialDetectorConstruction ()
~DicomPartialDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
Public Member Functions inherited from DicomDetectorConstruction
DicomDetectorConstruction ()
~DicomDetectorConstruction ()
G4int GetTotalVoxels () const
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
virtual void ReadPhantomData ()
void ReadPhantomDataFile (const G4String &fname)
void ConstructPhantomContainer ()
virtual void ConstructPhantom ()
void ReadVoxelDensitiesPartial (std::ifstream &fin)
Private Attributes
G4PartialPhantomParameterisation * fPartialPhantomParam
std::multimap< G4int, G4int > fFilledIDs
std::map< G4int, std::map
< G4int, G4int > > fFilledMins
std::map< G4int, std::map
< G4int, G4int > > fFilledMaxs
G4int fNVoxels
G4double fDimX
G4double fDimY
G4double fDimZ
G4double fOffsetX
G4double fOffsetY
G4double fOffsetZ
std::vector< G4Material * > fPhantomMaterials
Additional Inherited Members
Protected Member Functions inherited from DicomDetectorConstruction
void InitialisationOfMaterials ()
void ReadPhantomData ()
void ReadPhantomDataNew ()
void ReadVoxelDensities (std::ifstream &fin)
void ReadPhantomDataFile (const G4String &fname)
void MergeZSliceHeaders ()
G4Material * BuildMaterialWithChangingDensity (const G4Material *origMate, G4float density, G4String newMateName)
void ConstructPhantomContainer ()
void ConstructPhantomContainerNew ()
void SetScorer (G4LogicalVolume *voxel_logic)
virtual void ConstructSDandField ()
Protected Attributes inherited from DicomDetectorConstruction
G4Material * fAir
G4Box * fWorld_solid
G4LogicalVolume * fWorld_logic
G4VPhysicalVolume * fWorld_phys
G4Box * fContainer_solid
G4LogicalVolume * fContainer_logic
G4VPhysicalVolume * fContainer_phys
G4int fNoFiles
std::vector< G4Material * > fOriginalMaterials
std::vector< G4Material * > fMaterials
size_t * fMateIDs
std::map< G4int, G4double > fDensityDiffs
std::vector
< DicomPhantomZSliceHeader * > fZSliceHeaders
DicomPhantomZSliceHeader * fZSliceHeaderMerged
G4int fNVoxelX
G4int fNVoxelY
G4int fNVoxelZ
G4double fVoxelHalfDimX
G4double fVoxelHalfDimY
G4double fVoxelHalfDimZ
G4double fMinX
G4double fMinY
G4double fMinZ
G4double fMaxX
G4double fMaxY
G4double fMaxZ
std::map< G4int, G4Material * > thePhantomMaterialsOriginal
DicomPhantomZSliceMerged * fMergedSlices
std::set< G4LogicalVolume * > fScorers
G4bool fConstructed
Detailed Description
Construct a DICOM Geant4 geometry produced from the intersetion of a DICOM file and a volume
Definition at line 46 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 46 of file DicomPartialDetectorConstruction.hh
Constructor & Destructor Documentation
DicomPartialDetectorConstruction::DicomPartialDetectorConstruction ()
Definition at line 58 of file DicomPartialDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 58 of file DicomPartialDetectorConstruction.cc
DicomPartialDetectorConstruction::~DicomPartialDetectorConstruction ()
Definition at line 72 of file DicomPartialDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 72 of file DicomPartialDetectorConstruction.cc
Member Function Documentation
G4VPhysicalVolume * DicomPartialDetectorConstruction::Construct (void) virtual
Reimplemented from DicomDetectorConstruction.
Definition at line 77 of file DicomPartialDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 77 of file DicomPartialDetectorConstruction.cc
References ConstructPhantom(), ConstructPhantomContainer(), DicomDetectorConstruction::fAir, DicomDetectorConstruction::fWorld_logic, DicomDetectorConstruction::InitialisationOfMaterials(), m, and ReadPhantomData().
void DicomPartialDetectorConstruction::ConstructPhantom () private virtual
Implements DicomDetectorConstruction.
Definition at line 440 of file DicomPartialDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 440 of file DicomPartialDetectorConstruction.cc
References G4PartialPhantomParameterisation::BuildContainerWalls(), DicomDetectorConstruction::fAir, FALSE, FatalErrorInArgument, DicomDetectorConstruction::fContainer_logic, fDimX, fDimY, fDimZ, fFilledIDs, fFilledMins, DicomDetectorConstruction::fMateIDs, fNVoxels, DicomDetectorConstruction::fNVoxelX, DicomDetectorConstruction::fNVoxelY, DicomDetectorConstruction::fNVoxelZ, fPartialPhantomParam, fPhantomMaterials, G4Exception(), kUndefined, kXAxis, G4PartialPhantomParameterisation::SetFilledIDs(), G4PartialPhantomParameterisation::SetFilledMins(), G4PhantomParameterisation::SetMaterialIndices(), G4PhantomParameterisation::SetMaterials(), G4PhantomParameterisation::SetNoVoxel(), G4PVParameterised::SetRegularStructureId(), G4PhantomParameterisation::SetSkipEqualMaterials(), G4LogicalVolume::SetSmartless(), G4LogicalVolume::SetVisAttributes(), and G4PhantomParameterisation::SetVoxelDimensions().
Referenced by Construct().
void DicomPartialDetectorConstruction::ConstructPhantomContainer () private
Definition at line 407 of file DicomPartialDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 407 of file DicomPartialDetectorConstruction.cc
References deg, DicomDetectorConstruction::fAir, DicomDetectorConstruction::fContainer_logic, DicomDetectorConstruction::fContainer_phys, and DicomDetectorConstruction::fWorld_logic.
Referenced by Construct().
void DicomPartialDetectorConstruction::ReadPhantomData () private virtual
Definition at line 113 of file DicomPartialDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 113 of file DicomPartialDetectorConstruction.cc
References FatalErrorInArgument, test::fname, G4Exception(), and ReadPhantomDataFile().
Referenced by Construct().
void DicomPartialDetectorConstruction::ReadPhantomDataFile (const G4String & fname) private
Definition at line 148 of file DicomPartialDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 148 of file DicomPartialDetectorConstruction.cc
References G4UIcommand::ConvertToString(), FatalErrorInArgument, FatalException, fDimX, fDimY, fDimZ, fFilledIDs, fFilledMaxs, fFilledMins, fin, DicomDetectorConstruction::fMateIDs, fNVoxels, DicomDetectorConstruction::fNVoxelX, DicomDetectorConstruction::fNVoxelY, DicomDetectorConstruction::fNVoxelZ, fOffsetX, fOffsetY, fOffsetZ, G4cout, G4endl, G4Exception(), in, G4TrackingService::nMaterials, and ReadVoxelDensitiesPartial().
Referenced by ReadPhantomData().
void DicomPartialDetectorConstruction::ReadVoxelDensitiesPartial (std::ifstream & fin) private
Definition at line 263 of file DicomPartialDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 263 of file DicomPartialDetectorConstruction.cc
References DicomDetectorConstruction::BuildMaterialWithChangingDensity(), cm3, G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToString(), DBL_MAX, e, fFilledMaxs, fFilledMins, matInfo::fId, DicomDetectorConstruction::fMateIDs, DicomDetectorConstruction::fMaterials, matInfo::fNvoxels, DicomDetectorConstruction::fNVoxelX, DicomDetectorConstruction::fNVoxelY, DicomDetectorConstruction::fNVoxelZ, DicomDetectorConstruction::fOriginalMaterials, fPhantomMaterials, matInfo::fSumdens, Acts::UnitConstants::g, G4cout, G4endl, G4Material::GetDensity(), G4Material::GetName(), and part.
Referenced by ReadPhantomDataFile().
Member Data Documentation
G4double DicomPartialDetectorConstruction::fDimX private
Definition at line 84 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file DicomPartialDetectorConstruction.hh
Referenced by ConstructPhantom(), and ReadPhantomDataFile().
G4double DicomPartialDetectorConstruction::fDimY private
Definition at line 84 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file DicomPartialDetectorConstruction.hh
Referenced by ConstructPhantom(), and ReadPhantomDataFile().
G4double DicomPartialDetectorConstruction::fDimZ private
Definition at line 84 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 84 of file DicomPartialDetectorConstruction.hh
Referenced by ConstructPhantom(), and ReadPhantomDataFile().
std::multimap<G4int,G4int> DicomPartialDetectorConstruction::fFilledIDs private
Definition at line 80 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file DicomPartialDetectorConstruction.hh
Referenced by ConstructPhantom(), and ReadPhantomDataFile().
std::map< G4int, std::map< G4int, G4int > > DicomPartialDetectorConstruction::fFilledMaxs private
Definition at line 82 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 82 of file DicomPartialDetectorConstruction.hh
Referenced by ReadPhantomDataFile(), and ReadVoxelDensitiesPartial().
std::map< G4int, std::map< G4int, G4int > > DicomPartialDetectorConstruction::fFilledMins private
Definition at line 81 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 81 of file DicomPartialDetectorConstruction.hh
Referenced by ConstructPhantom(), ReadPhantomDataFile(), and ReadVoxelDensitiesPartial().
G4int DicomPartialDetectorConstruction::fNVoxels private
Definition at line 83 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 83 of file DicomPartialDetectorConstruction.hh
Referenced by ConstructPhantom(), and ReadPhantomDataFile().
G4double DicomPartialDetectorConstruction::fOffsetX private
Definition at line 85 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file DicomPartialDetectorConstruction.hh
Referenced by ReadPhantomDataFile().
G4double DicomPartialDetectorConstruction::fOffsetY private
Definition at line 85 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file DicomPartialDetectorConstruction.hh
Referenced by ReadPhantomDataFile().
G4double DicomPartialDetectorConstruction::fOffsetZ private
Definition at line 85 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 85 of file DicomPartialDetectorConstruction.hh
Referenced by ReadPhantomDataFile().
G4PartialPhantomParameterisation* DicomPartialDetectorConstruction::fPartialPhantomParam private
Definition at line 78 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 78 of file DicomPartialDetectorConstruction.hh
Referenced by ConstructPhantom().
std::vector<G4Material*> DicomPartialDetectorConstruction::fPhantomMaterials private
Definition at line 86 of file DicomPartialDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 86 of file DicomPartialDetectorConstruction.hh
Referenced by ConstructPhantom(), and ReadVoxelDensitiesPartial().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/include/DicomPartialDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/src/DicomPartialDetectorConstruction.cc