ECCE @ EIC Software: G4Electron Class Reference
G4Electron Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/leptons/include/G4Electron.hh>
Static Public Member Functions
static G4Electron * Definition ()
static G4Electron * ElectronDefinition ()
static G4Electron * Electron ()
Static Public Member Functions inherited from G4ParticleDefinition
static const G4PDefManager & GetSubInstanceManager ()
static void Clean ()
Private Member Functions
G4Electron ()
~G4Electron ()
Static Private Attributes
static G4Electron * theInstance = 0
Additional Inherited Members
Public Member Functions inherited from G4ParticleDefinition
G4ParticleDefinition (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospinZ, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable, G4bool shortlived=false, const G4String &subType="", G4int anti_encoding=0, G4double magneticMoment=0.0)
virtual ~G4ParticleDefinition ()
const G4String & GetParticleName () const
G4double GetPDGMass () const
G4double GetPDGWidth () const
G4double GetPDGCharge () const
G4double GetPDGSpin () const
G4int GetPDGiSpin () const
G4int GetPDGiParity () const
G4int GetPDGiConjugation () const
G4double GetPDGIsospin () const
G4double GetPDGIsospin3 () const
G4int GetPDGiIsospin () const
G4int GetPDGiIsospin3 () const
G4int GetPDGiGParity () const
G4double GetPDGMagneticMoment () const
void SetPDGMagneticMoment (G4double mageticMoment)
G4double CalculateAnomaly () const
const G4String & GetParticleType () const
const G4String & GetParticleSubType () const
G4int GetLeptonNumber () const
G4int GetBaryonNumber () const
G4int GetPDGEncoding () const
G4int GetAntiPDGEncoding () const
void SetAntiPDGEncoding (G4int aEncoding)
G4int GetQuarkContent (G4int flavor) const
G4int GetAntiQuarkContent (G4int flavor) const
G4bool IsShortLived () const
G4bool GetPDGStable () const
void SetPDGStable (const G4bool aFlag)
G4double GetPDGLifeTime () const
void SetPDGLifeTime (G4double aLifeTime)
G4double GetIonLifeTime () const
G4DecayTable * GetDecayTable () const
void SetDecayTable (G4DecayTable *aDecayTable)
G4ProcessManager * GetProcessManager () const
void SetProcessManager (G4ProcessManager *aProcessManager)
G4ParticleTable * GetParticleTable () const
G4int GetAtomicNumber () const
G4int GetAtomicMass () const
void DumpTable () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetApplyCutsFlag (G4bool)
G4bool GetApplyCutsFlag () const
G4bool IsGeneralIon () const
G4bool IsMuonicAtom () const
G4bool operator== (const G4ParticleDefinition &right) const
G4bool operator!= (const G4ParticleDefinition &right) const
G4ProcessManager * GetMasterProcessManager () const
void SetMasterProcessManager (G4ProcessManager *aNewPM)
G4int GetInstanceID () const
void SetParticleDefinitionID (G4int id=-1)
G4int GetParticleDefinitionID () const
Protected Types inherited from G4ParticleDefinition
enum { NumberOfQuarkFlavor = 6 }
Protected Member Functions inherited from G4ParticleDefinition
G4int FillQuarkContents ()
void SetParticleSubType (const G4String &subtype)
void SetAtomicNumber (G4int)
void SetAtomicMass (G4int)
G4ParticleDefinition (const G4ParticleDefinition &right)
G4ParticleDefinition ()
Protected Attributes inherited from G4ParticleDefinition
G4int theQuarkContent [NumberOfQuarkFlavor]
G4int theAntiQuarkContent [NumberOfQuarkFlavor]
G4bool isGeneralIon
G4bool isMuonicAtom
Detailed Description
Definition at line 49 of file G4Electron.hh.
View newest version in sPHENIX GitHub at line 49 of file G4Electron.hh
Constructor & Destructor Documentation
G4Electron::G4Electron () inline private
Definition at line 53 of file G4Electron.hh.
View newest version in sPHENIX GitHub at line 53 of file G4Electron.hh
G4Electron::~G4Electron () inline private
Definition at line 54 of file G4Electron.hh.
View newest version in sPHENIX GitHub at line 54 of file G4Electron.hh
Member Function Documentation
G4Electron * G4Electron::Definition () static
Definition at line 48 of file G4Electron.cc.
View newest version in sPHENIX GitHub at line 48 of file G4Electron.cc
References source.hepunit::c_squared, source.hepunit::electron_mass_c2, eplus, G4ParticleTable::FindParticle(), G4ParticleDefinition::G4ParticleDefinition(), G4ParticleTable::GetParticleTable(), source.hepunit::hbar_Planck, MeV, G4ParticleDefinition::SetPDGMagneticMoment(), and theInstance.
Referenced by XrayFluoAnalysisManager::analyseStepping(), F01RunAction::BeginOfRunAction(), F01RunAction::ChangeLooperParameters(), G4RadioactiveDecayBase::CollimateDecay(), G4RadioactiveDecay::CollimateDecay(), G4EmDNAChemistry_option1::ConstructMolecule(), G4EmDNAChemistry::ConstructMolecule(), G4EmDNAChemistry_option2::ConstructMolecule(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), G4DNASolvationModelFactory::Create(), Electron(), ElectronDefinition(), F01RunAction::EndOfRunAction(), Par02FastSimModelEMCal::IsApplicable(), G4InuclElementaryParticle::makeDefinition(), PurgMagPrimaryGeneratorAction::PurgMagPrimaryGeneratorAction(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4BetheHeitler5DModel::SetLeptonPair(), G4InuclElementaryParticle::type(), PurgMagSteppingAction::UserSteppingAction(), and DMXSteppingAction::UserSteppingAction().
G4Electron * G4Electron::Electron () static
Definition at line 93 of file G4Electron.cc.
View newest version in sPHENIX GitHub at line 93 of file G4Electron.cc
References Definition().
Referenced by G4EmModelActivator::ActivateEmOptions(), G4EmModelActivator::ActivateMicroElec(), G4EmModelActivator::ActivatePAI(), G4VEmProcess::ActivateSecondaryBiasing(), G4VEnergyLossProcess::ActivateSecondaryBiasing(), Run::AddSecondaryTrack(), HistoManager::AddTargetStep(), G4AdjointBremsstrahlungModel::AdjointCrossSection(), G4eLowEnergyLoss::AlongStepDoIt(), G4MuonMinusBoundDecay::ApplyYourself(), RunAction::BeginOfRunAction(), G4BertiniElectroNuclearBuilder::Build(), G4eLowEnergyLoss::BuildDEDXTable(), G4LowEnergyIonisation::BuildPhysicsTable(), G4LowEnergyBremsstrahlung::BuildPhysicsTable(), G4SynchrotronRadiation::BuildPhysicsTable(), G4PenelopeIonisationXSHandler::BuildXSTable(), G4CascadeCheckBalance::collide(), G4EmCalculator::ComputeDEDXForCutInRange(), G4AdjointPhysicsList::ConstructEM(), G4EmExtraPhysics::ConstructGammaElectroNuclear(), G4EmDNAPhysics_option3::ConstructParticle(), G4EmDNAPhysics_stationary::ConstructParticle(), G4EmDNAPhysics_stationary_option2::ConstructParticle(), G4EmDNAPhysics_stationary_option4::ConstructParticle(), G4EmDNAPhysics_stationary_option6::ConstructParticle(), G4EmPenelopePhysics::ConstructParticle(), G4EmDNAPhysics_option1::ConstructParticle(), G4EmDNAPhysics_option2::ConstructParticle(), G4EmDNAPhysics::ConstructParticle(), G4EmLivermorePhysics::ConstructParticle(), G4EmLivermorePolarizedPhysics::ConstructParticle(), G4EmLowEPPhysics::ConstructParticle(), G4EmDNAPhysics_option4::ConstructParticle(), G4EmDNAPhysics_option5::ConstructParticle(), G4EmDNAPhysics_option8::ConstructParticle(), G4EmDNAPhysics_option7::ConstructParticle(), G4EmDNAPhysicsActivator::ConstructParticle(), G4EmLEPTSPhysics::ConstructParticle(), G4EmDNAPhysics_option6::ConstructParticle(), G4EmStandardPhysicsSS::ConstructParticle(), PhysListEm5DStandard::ConstructParticle(), PhysListEm19DStandard::ConstructParticle(), G4EmStandardPhysics::ConstructParticle(), G4EmStandardPhysics_option3::ConstructParticle(), G4EmStandardPhysicsGS::ConstructParticle(), G4EmStandardPhysics_option4_channeling::ConstructParticle(), G4EmStandardPhysics_option4::ConstructParticle(), G4EmStandardPhysicsWVI::ConstructParticle(), G4EmStandardPhysics_option1::ConstructParticle(), G4EmStandardPhysics_option2::ConstructParticle(), G4EmExtraPhysics::ConstructParticle(), GammaLeptoNuclearPhysics::ConstructProcess(), G4EmDNAPhysicsActivator::ConstructProcess(), PhysicsListEMstd::ConstructProcess(), TransitionRadiationPhysics::ConstructProcess(), GammaRayTelEMlowePhysics::ConstructProcess(), GammaRayTelEMstdPhysics::ConstructProcess(), G4EmExtraPhysics::ConstructProcess(), Run::CountParticles(), RunAction::CriticalEnergy(), G4PenelopeIonisationCrossSection::CrossSection(), G4ECDecay::DecayIt(), G4ITDecay::DecayIt(), G4LowEnergyIonisation::DeexciteAtom(), G4AdjointBremsstrahlungModel::DiffCrossSectionPerVolumePrimToSecond(), G4LossTableManager::DumpHtml(), G4HadronicProcessStore::DumpHtml(), RMC01AnalysisManager::EndOfEventForAdjointSimulation(), G4RDRangeTest::Escape(), PHG4GDMLWriteStructure::ExportEnergyCuts(), G4GDMLWriteStructure::ExportEnergyCuts(), G4AdjointBremsstrahlungModel::G4AdjointBremsstrahlungModel(), G4AdjointeIonisationModel::G4AdjointeIonisationModel(), G4AtimaEnergyLossModel::G4AtimaEnergyLossModel(), G4BetheBlochModel::G4BetheBlochModel(), G4BraggIonModel::G4BraggIonModel(), G4BraggModel::G4BraggModel(), G4ComptonScattering::G4ComptonScattering(), G4DeltaAngle::G4DeltaAngle(), G4DNABornAngle::G4DNABornAngle(), G4DNARuddAngle::G4DNARuddAngle(), G4EmBiasingManager::G4EmBiasingManager(), G4EmCaptureCascade::G4EmCaptureCascade(), G4ExcitationHandler::G4ExcitationHandler(), G4GammaConversion::G4GammaConversion(), G4hhIonisation::G4hhIonisation(), G4hIonisation::G4hIonisation(), G4ICRU73QOModel::G4ICRU73QOModel(), G4ionIonisation::G4ionIonisation(), G4KleinNishinaCompton::G4KleinNishinaCompton(), G4KleinNishinaModel::G4KleinNishinaModel(), G4LindhardSorensenIonModel::G4LindhardSorensenIonModel(), G4LivermorePhotoElectricModel::G4LivermorePhotoElectricModel(), G4LivermorePolarizedPhotoElectricGDModel::G4LivermorePolarizedPhotoElectricGDModel(), G4LivermorePolarizedPhotoElectricModel::G4LivermorePolarizedPhotoElectricModel(), G4LossTableManager::G4LossTableManager(), G4MollerBhabhaModel::G4MollerBhabhaModel(), G4mplIonisation::G4mplIonisation(), G4mplIonisationWithDeltaModel::G4mplIonisationWithDeltaModel(), G4MuBetheBlochModel::G4MuBetheBlochModel(), G4MuIonisation::G4MuIonisation(), G4MuPairProductionModel::G4MuPairProductionModel(), G4NeutrinoElectronNcModel::G4NeutrinoElectronNcModel(), G4NeutronElectronElModel::G4NeutronElectronElModel(), G4NeutronRadCapture::G4NeutronRadCapture(), G4PAIModel::G4PAIModel(), G4PAIPhotModel::G4PAIPhotModel(), G4PEEffectFluoModel::G4PEEffectFluoModel(), G4PhotoElectricEffect::G4PhotoElectricEffect(), G4PolarizedCompton::G4PolarizedCompton(), G4PolarizedGammaConversion::G4PolarizedGammaConversion(), G4PolarizedPhotoElectricEffect::G4PolarizedPhotoElectricEffect(), G4TablesForExtrapolator::G4TablesForExtrapolator(), G4UAtomicDeexcitation::G4UAtomicDeexcitation(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4WentzelOKandVIxSection::G4WentzelOKandVIxSection(), G4RDAtomicDeexcitation::GenerateAuger(), G4AtomicDeexcitation::GenerateAuger(), G4UAtomicDeexcitation::GenerateAuger(), G4DNAPTBAugerModel::GenerateAugerWithRandomDirection(), G4PenelopeIonisationXSHandler::GetCrossSectionTableForCouple(), G4PenelopeBremsstrahlungModel::GetCrossSectionTableForCouple(), G4AdjointCSManager::GetForwardParticleEquivalent(), G4ParticleHPPhotonDist::GetPhotons(), PhysicsList::GetRange(), G4EnergyLossForExtrapolator::Initialisation(), G4LivermoreIonisationModel::Initialise(), G4PenelopeIonisationModel::Initialise(), G4UrbanAdjointMscModel::Initialise(), G4EmModelManager::Initialise(), G4alphaIonisation::InitialiseEnergyLossProcess(), G4DNADissociation::IsApplicable(), G4DNARotExcitation::IsApplicable(), G4DNAVibExcitation::IsApplicable(), G4DNAAttachment::IsApplicable(), G4DNAElastic::IsApplicable(), G4DNAExcitation::IsApplicable(), G4DNAIonisation::IsApplicable(), G4MicroElecElastic::IsApplicable(), G4MuElecElastic::IsApplicable(), G4DNAElectronSolvation::IsApplicable(), G4ePairProduction::IsApplicable(), G4MicroElecInelastic::IsApplicable(), G4MuElecInelastic::IsApplicable(), G4ePolarizedIonisation::IsApplicable(), G4LowEnergyIonisation::IsApplicable(), G4LowEnergyBremsstrahlung::IsApplicable(), G4eBremsstrahlung::IsApplicable(), main(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4VMultipleScattering::PreparePhysicsTable(), RMC01SD::ProcessHits(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), RMC01AnalysisManager::RMC01AnalysisManager(), Run::Run(), G4ParticleHPIsotropic::Sample(), G4ParticleHPNBodyPhaseSpace::Sample(), G4ParticleHPLabAngularEnergy::Sample(), G4ParticleHPDiscreteTwoBody::Sample(), G4ParticleHPContAngularPar::Sample(), G4PenelopeIonisationModel::SampleFinalStateElectron(), G4LEPTSIonisationModel::SampleSecondaries(), G4DNADingfelderChargeIncreaseModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4DNARuddIonisationModel::SampleSecondaries(), G4DNARuddIonisationExtendedModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4IonParametrisedLossModel::SampleSecondaries(), G4GammaTransition::SampleTransition(), G4VEmAdjointModel::SetAdjointEquivalentOfDirectPrimaryParticleDefinition(), GammaKnifePhysicsList::SetCutForElectron(), GammaRayTelPhysicsList::SetCutForElectron(), STCyclotronPhysicsList::SetCutForElectron(), PhysicsList::SetCutForElectron(), XrayFluoPhysicsList::SetCutForElectron(), IORTPhysicsList::SetCutForElectron(), G4CollisionOutput::setOnShell(), G4eBremsstrahlungRelModel::SetParticle(), G4eBremParametrizedModel::SetParticle(), G4UrbanAdjointMscModel::SetParticle(), RMC01AnalysisManager::SetPrimaryExpSpectrumForAdjointSim(), RMC01AnalysisManager::SetPrimaryPowerLawSpectrumForAdjointSim(), and G4eAdjointMultipleScattering::StartTracking().
G4Electron * G4Electron::ElectronDefinition () static
Definition at line 88 of file G4Electron.cc.
View newest version in sPHENIX GitHub at line 88 of file G4Electron.cc
References Definition().
Referenced by G4LFission::Atomas(), GFlashShowerModel::CheckParticleDefAndContainment(), G4LeptonConstructor::ConstructELeptons(), eRositaPhysicsList::ConstructLeptons(), PhysicsList::ConstructLeptons(), ExN02PhysicsList::ConstructLeptons(), XrayTelPhysicsList::ConstructLeptons(), G4AdjointPhysicsList::ConstructLeptons(), PurgMagPhysicsList::ConstructLeptons(), DMXPhysicsList::ConstructMyLeptons(), LBE::ConstructMyLeptons(), GammaKnifeParticles::ConstructParticle(), ExUCNPhysicsList::ConstructParticle(), STCyclotronPhysicsList::ConstructParticle(), XrayFluoPhysicsList::ConstructParticle(), F06PhysicsList::ConstructParticle(), PhysicsListEMstd::ConstructParticle(), PhysicsList::ConstructParticle(), G4ErrorPhysicsList::ConstructParticle(), G4SpinDecayPhysics::ConstructParticle(), G4DNABornIonisationModel1::CrossSectionPerVolume(), G4DNAEmfietzoglouExcitationModel::CrossSectionPerVolume(), G4DNAEmfietzoglouIonisationModel::CrossSectionPerVolume(), G4DNACPA100ExcitationModel::CrossSectionPerVolume(), G4DNACPA100IonisationModel::CrossSectionPerVolume(), G4DNABornIonisationModel1::DifferentialCrossSection(), G4DNAEmfietzoglouIonisationModel::DifferentialCrossSection(), G4DNACPA100IonisationModel::DifferentialCrossSection(), G4MicroElecInelasticModel::DifferentialCrossSection(), G4MuElecInelasticModel::DifferentialCrossSection(), G4DNAPTBIonisationModel::DifferentialCrossSection(), GFlashShowerModel::DoIt(), RE01Trajectory::DrawTrajectory(), GFlashShowerModelMessenger::GetCurrentValue(), GFlashParticleBounds::GetEneToKill(), GFlashParticleBounds::GetMaxEneToParametrise(), GFlashParticleBounds::GetMinEneToParametrise(), G4Scintillation::GetScintillationYieldByParticleType(), G4DNABornIonisationModel1::Initialise(), G4MicroElecElasticModel::Initialise(), G4MuElecElasticModel::Initialise(), G4DNAEmfietzoglouExcitationModel::Initialise(), G4DNACPA100ElasticModel::Initialise(), G4DNAEmfietzoglouIonisationModel::Initialise(), G4DNACPA100ExcitationModel::Initialise(), G4DNACPA100IonisationModel::Initialise(), G4MicroElecInelasticModel::Initialise(), G4MuElecInelasticModel::Initialise(), G4DNAPTBExcitationModel::Initialise(), G4DNAPTBElasticModel::Initialise(), G4DNAPTBIonisationModel::Initialise(), Par01EMShowerModel::IsApplicable(), GFlashShowerModel::IsApplicable(), RE06SteppingVerbose::NewStep(), G4MuElecElasticModel::RandomizeCosTheta(), G4MicroElecElasticModel::RandomizeCosTheta(), G4DNACPA100ElasticModel::RandomizeCosTheta(), G4DNAPTBElasticModel::RandomizeCosTheta(), G4MuElecInelasticModel::RandomizeEjectedElectronDirection(), G4DNAPTBIonisationModel::RandomizeEjectedElectronDirection(), G4DNABornIonisationModel2::RandomizeEjectedElectronEnergy(), G4MuElecInelasticModel::RandomizeEjectedElectronEnergy(), G4DNAEmfietzoglouIonisationModel::RandomizeEjectedElectronEnergy(), G4DNABornIonisationModel1::RandomizeEjectedElectronEnergy(), G4MicroElecInelasticModel::RandomizeEjectedElectronEnergy(), G4DNACPA100IonisationModel::RandomizeEjectedElectronEnergy(), G4DNAPTBIonisationModel::RandomizeEjectedElectronEnergy(), G4DNAEmfietzoglouIonisationModel::RandomTransferedEnergy(), G4DNACPA100IonisationModel::RandomTransferedEnergy(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), GFlashParticleBounds::SetEneToKill(), GFlashParticleBounds::SetMaxEneToParametrise(), GFlashParticleBounds::SetMinEneToParametrise(), GFlashShowerModelMessenger::SetNewValue(), G4MicroElecElasticModel::Theta(), G4MuElecElasticModel::Theta(), G4DNAPTBElasticModel::Theta(), G4DNABornIonisationModel1::TransferedEnergy(), and G4MicroElecInelasticModel::TransferedEnergy().
Member Data Documentation
G4Electron * G4Electron::theInstance = 0 static private
Definition at line 52 of file G4Electron.hh.
View newest version in sPHENIX GitHub at line 52 of file G4Electron.hh
Referenced by Definition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/leptons/include/G4Electron.hh
geant4/tree/geant4-10.6-release/source/particles/leptons/src/G4Electron.cc