ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/global/pyRandomize.cc File Reference
pyRandomize.cc File Reference
#include <boost/python.hpp>
#include "Randomize.hh"
#include <vector>
Namespaces
namespace pyRandomize
Functions
void pyRandomize::f1_setTheSeed (long seed)
void pyRandomize::f2_setTheSeed (long seed, int lux)
void pyRandomize::f1_setTheSeeds (const list &seedList)
void pyRandomize::f2_setTheSeeds (const list &seedList, int aux)
list pyRandomize::f_getTheSeeds ()
list pyRandomize::f_getTheTableSeeds (int index)
void pyRandomize::f1_saveEngineStatus ()
void pyRandomize::f2_saveEngineStatus (const char *filename)
void pyRandomize::f1_restoreEngineStatus ()
void pyRandomize::f2_restoreEngineStatus (const char *filename)
int pyRandomize::f1_RandBit_shootBit ()
double pyRandomize::f1_RandGaussQ_shoot ()
double pyRandomize::f2_RandGaussQ_shoot (double mean, double stdDev)
double pyRandomize::f_G4UniformRand ()
void export_Randomize ()
Function Documentation
void export_Randomize ()
Definition at line 176 of file pyRandomize.cc.
View newest version in sPHENIX GitHub at line 176 of file pyRandomize.cc
References pyRandomize::f1_RandBit_shootBit(), pyRandomize::f1_RandGaussQ_shoot(), pyRandomize::f1_restoreEngineStatus(), pyRandomize::f1_saveEngineStatus(), pyRandomize::f1_setTheSeed(), pyRandomize::f1_setTheSeeds(), pyRandomize::f2_RandGaussQ_shoot(), pyRandomize::f2_restoreEngineStatus(), pyRandomize::f2_saveEngineStatus(), pyRandomize::f2_setTheSeed(), pyRandomize::f2_setTheSeeds(), pyRandomize::f_G4UniformRand(), pyRandomize::f_getTheSeeds(), and pyRandomize::f_getTheTableSeeds().
Referenced by BOOST_PYTHON_MODULE().