ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/xDataTOM_importXML.cc File Reference
xDataTOM_importXML.cc File Reference
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include "xDataTOM_importXML_private.h"
Macros
#define PATH_MAX 4096
Functions
static xDataXML_document * xDataXML_mallocDoc (statusMessageReporting *smr)
static int xDataXML_initializeDoc (statusMessageReporting *smr, xDataXML_document *doc)
static int xDataXML_endXMLParsing (statusMessageReporting *smr, xDataXML_document *doc)
static void * xDataXML_freeElement (statusMessageReporting *smr, xDataXML_element *element)
static void xDataXML_freeElementItems (statusMessageReporting *smr, xDataXML_element *element)
static int xDataXML_parse (xDataXML_document *doc, char const *s)
static void XMLCALL xDataXML_parseStartElement (void *userData, char const *name, char const **attris)
static void XMLCALL xDataXML_parseEndElement (void *userData, char const *name)
static void XMLCALL xDataXML_parseCharacterData (void *userData, XML_Char const *s, int len)
static void xDataXML_initializeRootElement (xDataXML_document *doc, xDataXML_rootElement *re, xDataXML_element *parentElement, int depth)
static int xDataXML_parseInitializeText (xDataXML_document *doc, xDataXML_text *text)
static int xDataXML_addElementToRoot (statusMessageReporting *smr, xDataXML_rootElement *parentRoot, char const *name, char const **attris)
static enum xDataXML_errorCodes xDataXML_parseGetCurrentPosition (xDataXML_document *doc, xDataXML_docInfo *docInfo)
static int xDataXML_init_xDataTypeNone (xDataXMLType *xDT, xDataXML_element *element)
static char * xDataXML_getTraceback (statusMessageReporting *smr, xDataXML_element *element)
static char * xDataXML_getTraceback2 (statusMessageReporting *smr, xDataXML_rootElement *parentRoot, int n)
static int xDataXML_setFileName (statusMessageReporting *smr, xDataXML_document *doc, char const *fileName)
static int xDataXML_smrUserInterfaceInitialize (xDataXML_document *doc)
static int xDataXML_smrUserInterfaceFree (xDataXML_document *doc)
static char * xDataXML_smrUserInterface (void *userData)
static char const * xDataXML_shortStringForMessage (size_t size, char *Out, char const *In)
static int xDataXML_constructTOM (statusMessageReporting *smr, xDataTOM_element *TE, xDataXML_element *element)
xDataTOM_TOM * xDataXML_importFile (statusMessageReporting *smr, char const *fileName)
xDataXML_document * xDataXML_importFile2 (statusMessageReporting *smr, char const *fileName)
void * xDataXML_freeDoc (statusMessageReporting *smr, xDataXML_document *doc)
int xDataXML_parseIsError (xDataXML_document *doc)
xDataXML_element * xDataXML_getDocumentsElement (xDataXML_document *doc)
xDataXML_element * xDataXML_getFirstElement (xDataXML_element *element)
xDataXML_element * xDataXML_getNextElement (xDataXML_element *element)
enum xDataXML_itemMode xDataXML_getFirstItem (xDataXML_element *element, xDataXML_item *item)
enum xDataXML_itemMode xDataXML_getNextItem (xDataXML_item *item)
int xDataXML_isAttributeInList (xDataXML_attributionList *attributes, char const *name)
int xDataXML_isAttributeInElement (xDataXML_element *element, char const *name)
char * xDataXML_getAttributesValue (xDataXML_attributionList *attributes, char const *name)
char const * xDataXML_getAttributesValueInElement (xDataXML_element *element, char const *name)
int xDataXML_attributeListLength (xDataXML_attributionList *attributes)
xDataXML_attribute * xDataXML_attributeByIndex (xDataXML_attributionList *attributes, int index)
int xDataXML_getCommonData (statusMessageReporting *smr, xDataXML_element *element, xDataTOM_Int *index, xDataTOM_Int *start, xDataTOM_Int *end, xDataTOM_Int *length)
int xDataXML_xDataTypeConvertAttributes (statusMessageReporting *smr, xDataXML_element *element)
xDataTOM_Int xDataXML_convertAttributeTo_xDataTOM_Int (statusMessageReporting *smr, xDataXML_element *element, char const *name, xDataTOM_Int *n, int required)
int xDataXML_convertAttributeToDouble (statusMessageReporting *smr, xDataXML_element *element, char const *name, double *d, int required)
int xDataXML_numberOfElementsByTagName (statusMessageReporting *, xDataXML_element *element, char const *tagName)
xDataXML_elementList * xDataXML_getElementsByTagName (statusMessageReporting *smr, xDataXML_element *element, char const *tagName)
xDataXML_element * xDataXML_getOneElementByTagName (statusMessageReporting *smr, xDataXML_element *element, char *name, int required)
void xDataXML_freeElementList (statusMessageReporting *, xDataXML_elementList *list)
int xDataXML_is_xDataType (statusMessageReporting *smr, xDataXMLType *xDT, char const *const ID, int setMsg)
char const * xDataXML_getFileName (xDataXML_document *doc)
char const * xDataXML_getRealFileName (xDataXML_document *doc)
xDataXML_document * xDataXML_getElementsDocument (xDataXML_element *element)
void * xDataXML_get_smrUserInterfaceFromDocument (xDataXML_document *doc)
void * xDataXML_get_smrUserInterfaceFromElement (xDataXML_element *element)
int xDataXML_stringTo_xDataTOM_Int (statusMessageReporting *smr, void *smrUserInterface, char const *c, xDataTOM_Int *value, char const *endings, char **e)
int xDataXML_stringTo_double (statusMessageReporting *smr, void *smrUserInterface, char const *c, double *value, char const *endings, char **e)
int xDataXML_addToAccessed (statusMessageReporting *, xDataXML_element *element, int increment)
int xDataXML_getAccessed (statusMessageReporting *, xDataXML_element *element)
void * xDataXML_initializeData (statusMessageReporting *smr, xDataXML_element *XE, xDataTOM_element *TE, char const *ID, size_t size)
Macro Definition Documentation
#define PATH_MAX 4096
Definition at line 33 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 33 of file xDataTOM_importXML.cc
Referenced by xDataXML_setFileName().
Function Documentation
static int xDataXML_addElementToRoot (statusMessageReporting * smr, xDataXML_rootElement * parentRoot, char const * name, char const ** attris) static
Definition at line 311 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 311 of file xDataTOM_importXML.cc
References a, xDataXML_element_s::accessed, xDataXML_attributionList_s::attributes, xDataXML_element_s::attributes, xDataXML_rootElement_s::children, xDataXML_element_s::childrenRoot, xDataXML_rootElement_s::currentChild, xDataXML_document_s::currentRoot, xDataXML_rootElement_s::depth, xDataXML_element_s::docInfo, e, xDataXML_element_s::fullName, xDataXML_element_s::index, int(), xDataXML_text_s::length, n, xDataXML_attribute_s::name, xDataXML_element_s::name, xDataXML_element_s::next, xDataXML_attributionList_s::number, xDataXML_rootElement_s::numberOfElements, xDataXML_element_s::ordinal, xDataXML_rootElement_s::parentElement, xDataXML_element_s::parentRoot, xDataXML_attributionList_s::size, xDataXML_document_s::smr, smr_freeMemory(), smr_malloc2, smr_setReportError3, xDataXML_element_s::text, xDataXML_element_s::textOffset, xDataXML_rootElement_s::xData_doc, xDataTOM_smrLibraryID, xDataXML_element_s::xDataTypeInfo, xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getTraceback(), xDataXML_init_xDataTypeNone(), xDataXML_initializeRootElement(), xDataXML_parseGetCurrentPosition(), and xDataXML_parseInitializeText().
Referenced by xDataXML_parseStartElement().
int xDataXML_addToAccessed (statusMessageReporting * , xDataXML_element * element, int increment)
Definition at line 925 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 925 of file xDataTOM_importXML.cc
References xDataXML_element_s::accessed.
xDataXML_attribute* xDataXML_attributeByIndex (xDataXML_attributionList * attributes, int index)
Definition at line 512 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 512 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::attributes, and xDataXML_attributionList_s::number.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), and xDataXML_constructTOM().
int xDataXML_attributeListLength (xDataXML_attributionList * attributes)
Definition at line 505 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 505 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::number.
static int xDataXML_constructTOM (statusMessageReporting * smr, xDataTOM_element * TE, xDataXML_element * element) static
Definition at line 953 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 953 of file xDataTOM_importXML.cc
References xDataXML_element_s::attributes, xDataXML_element_s::index, xDataXML_attribute_s::name, xDataXML_element_s::name, printf(), smr_isOk(), smr_setReportError3, xDataXML_attribute_s::value, xDataTOM_addElementInElement(), xDataTOM_KalbachMann_ID, xDataTOM_polynomial_ID, xDataTOM_regionsW_XYs_LegendreSeries_ID, xDataTOM_regionsXYs_ID, xDataTOM_smrLibraryID, xDataTOM_V_W_XYs_ID, xDataTOM_V_W_XYs_LegendreSeries_ID, xDataTOM_W_XYs_ID, xDataTOM_W_XYs_LegendreSeries_ID, xDataTOM_XYs_ID, xDataTOME_addAttribute(), xDataXML_attributeByIndex(), xDataXML_get_smrUserInterfaceFromElement(), xDataXML_getAttributesValueInElement(), xDataXML_getFirstElement(), xDataXML_getNextElement(), xDataXML_KalbachMannToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsToTOM(), and xDataXML_XYsToTOM().
Referenced by xDataXML_importFile().
xDataTOM_Int xDataXML_convertAttributeTo_xDataTOM_Int (statusMessageReporting * smr, xDataXML_element * element, char const * name, xDataTOM_Int * n, int required)
Definition at line 601 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 601 of file xDataTOM_importXML.cc
References e, smr_setReportError3, xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), and xDataXML_getAttributesValueInElement().
Referenced by xDataXML_axesToTOM(), xDataXML_KalbachMannCoefficientsToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM(), xDataXML_W_XYs_XYsToTOM(), xDataXML_xDataTypeConvertAttributes(), and xDataXML_XYsToTOM().
int xDataXML_convertAttributeToDouble (statusMessageReporting * smr, xDataXML_element * element, char const * name, double * d, int required)
Definition at line 624 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 624 of file xDataTOM_importXML.cc
References e, smr_setReportError3, xDataTOM_smrLibraryID, xDataXML_get_smrUserInterfaceFromElement(), and xDataXML_getAttributesValueInElement().
Referenced by MCGIDI_target_read(), xDataXML_KalbachMannCoefficientsToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeries_LegendreSeriesToTOM(), xDataXML_W_XYs_XYsToTOM(), and xDataXML_XYsToTOM().
static int xDataXML_endXMLParsing (statusMessageReporting * smr, xDataXML_document * doc) static
Definition at line 167 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 167 of file xDataTOM_importXML.cc
References xDataXML_document_s::err, xDataXML_document_s::err_column, xDataXML_document_s::err_line, smr_isOk(), smr_setReportError3, xDataXML_document_s::status, xDataTOM_smrLibraryID, xDataXML_errXMLParser, xDataXML_get_smrUserInterfaceFromDocument(), xDataXML_statusCompleted, xDataXML_statusError, XML_ErrorString(), XML_GetCurrentColumnNumber(), XML_GetCurrentLineNumber(), XML_GetErrorCode(), XML_Parse(), XML_ParserFree(), XML_STATUS_ERROR, and xDataXML_document_s::xmlParser.
Referenced by xDataXML_freeDoc(), and xDataXML_importFile2().
void* xDataXML_freeDoc (statusMessageReporting * smr, xDataXML_document * doc)
Definition at line 188 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 188 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::children, xDataXML_document_s::fileName, xDataXML_document_s::realFileName, xDataXML_document_s::root, smr_freeMemory(), xDataXML_endXMLParsing(), xDataXML_freeElement(), and xDataXML_smrUserInterfaceFree().
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), xDataXML_importFile(), xDataXML_importFile2(), and xDataXML_mallocDoc().
static void * xDataXML_freeElement (statusMessageReporting * smr, xDataXML_element * element) static
Definition at line 201 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 201 of file xDataTOM_importXML.cc
References xDataXML_element_s::next, smr_freeMemory(), and xDataXML_freeElementItems().
Referenced by xDataXML_freeDoc(), and xDataXML_freeElementItems().
static void xDataXML_freeElementItems (statusMessageReporting * smr, xDataXML_element * element) static
Definition at line 215 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 215 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::attributes, xDataXML_element_s::attributes, xDataXML_rootElement_s::children, xDataXML_element_s::childrenRoot, xDataXML_element_s::fullName, xDataXML_element_s::name, xDataXMLType_s::release, smr_freeMemory(), xDataXML_text_s::text, xDataXML_element_s::text, xDataXML_element_s::xDataTypeInfo, and xDataXML_freeElement().
Referenced by xDataXML_freeElement().
void xDataXML_freeElementList (statusMessageReporting * , xDataXML_elementList * list)
Definition at line 706 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 706 of file xDataTOM_importXML.cc
References smr_freeMemory().
Referenced by xDataXML_getOneElementByTagName().
void* xDataXML_get_smrUserInterfaceFromDocument (xDataXML_document * doc)
Definition at line 808 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 808 of file xDataTOM_importXML.cc
References xDataXML_document_s::smrUserInterface.
Referenced by xDataXML_endXMLParsing(), and xDataXML_get_smrUserInterfaceFromElement().
void* xDataXML_get_smrUserInterfaceFromElement (xDataXML_element * element)
Definition at line 816 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 816 of file xDataTOM_importXML.cc
References xDataXML_get_smrUserInterfaceFromDocument(), and xDataXML_getElementsDocument().
Referenced by xDataXML_addElementToRoot(), xDataXML_axesElememtToTOM(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_getCommonData(), xDataXML_getOneElementByTagName(), xDataXML_is_xDataType(), xDataXML_KalbachMannToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_stringToDoubles(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), xDataXML_xDataTypeConvertAttributes(), and xDataXML_XYsToTOM().
int xDataXML_getAccessed (statusMessageReporting * , xDataXML_element * element)
Definition at line 933 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 933 of file xDataTOM_importXML.cc
References xDataXML_element_s::accessed.
char* xDataXML_getAttributesValue (xDataXML_attributionList * attributes, char const * name)
Definition at line 486 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 486 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::attributes, xDataXML_attribute_s::name, xDataXML_attributionList_s::number, and xDataXML_attribute_s::value.
Referenced by xDataXML_getAttributesValueInElement().
char const* xDataXML_getAttributesValueInElement (xDataXML_element * element, char const * name)
Definition at line 498 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 498 of file xDataTOM_importXML.cc
References xDataXML_element_s::attributes, and xDataXML_getAttributesValue().
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_convertAttributeTo_xDataTOM_Int(), xDataXML_convertAttributeToDouble(), xDataXML_KalbachMannToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), and xDataXML_regionsXYs_regionToTOM().
int xDataXML_getCommonData (statusMessageReporting * smr, xDataXML_element * element, xDataTOM_Int * index, xDataTOM_Int * start, xDataTOM_Int * end, xDataTOM_Int * length)
Definition at line 542 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 542 of file xDataTOM_importXML.cc
References xDataXMLType_s::end, xDataXML_element_s::fullName, xDataXMLType_s::ID, xDataXMLType_s::index, xDataXMLType_s::length, smr_setReportError3, xDataXMLType_s::start, xDataTOM_smrLibraryID, xDataXML_element_s::xDataTypeInfo, and xDataXML_get_smrUserInterfaceFromElement().
xDataXML_element* xDataXML_getDocumentsElement (xDataXML_document * doc)
Definition at line 413 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 413 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::children, and xDataXML_document_s::root.
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), and xDataXML_importFile().
xDataXML_elementList* xDataXML_getElementsByTagName (statusMessageReporting * smr, xDataXML_element * element, char const * tagName)
Definition at line 658 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 658 of file xDataTOM_importXML.cc
References xDataXML_elementListItem_s::element, xDataXML_elementList_s::items, n, xDataXML_elementList_s::n, xDataXML_element_s::name, smr_malloc2, xDataXML_elementListItem_s::sortString, xDataXML_getFirstElement(), xDataXML_getNextElement(), and xDataXML_numberOfElementsByTagName().
Referenced by xDataXML_getOneElementByTagName().
xDataXML_document* xDataXML_getElementsDocument (xDataXML_element * element)
Definition at line 798 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 798 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::parentRoot, xDataXML_element_s::parentRoot, and xDataXML_rootElement_s::xData_doc.
Referenced by xDataXML_get_smrUserInterfaceFromElement().
char const* xDataXML_getFileName (xDataXML_document * doc)
Definition at line 767 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 767 of file xDataTOM_importXML.cc
References xDataXML_document_s::fileName.
xDataXML_element* xDataXML_getFirstElement (xDataXML_element * element)
Definition at line 414 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 414 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::children, and xDataXML_element_s::childrenRoot.
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), xDataXML_axesElememtToTOM(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_getElementsByTagName(), xDataXML_getFirstItem(), xDataXML_KalbachMannToTOM(), xDataXML_numberOfElementsByTagName(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), and xDataXML_XYsToTOM().
enum xDataXML_itemMode xDataXML_getFirstItem (xDataXML_element * element, xDataXML_item * item)
Definition at line 419 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 419 of file xDataTOM_importXML.cc
References xDataXML_item_s::element, xDataXML_text_s::length, xDataXML_item_s::mode, xDataXML_item_s::parentElement, xDataXML_text_s::text, xDataXML_element_s::text, xDataXML_item_s::text, xDataXML_item_s::textLength, xDataXML_element_s::textOffset, xDataXML_item_s::textOffset, xDataXML_getFirstElement(), xDataXML_itemModeElement, xDataXML_itemModeEnd, and xDataXML_itemModeText.
xDataXML_element* xDataXML_getNextElement (xDataXML_element * element)
Definition at line 415 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 415 of file xDataTOM_importXML.cc
References xDataXML_element_s::next.
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), xDataXML_axesElememtToTOM(), xDataXML_axesToTOM(), xDataXML_constructTOM(), xDataXML_getElementsByTagName(), xDataXML_KalbachMannToTOM(), xDataXML_numberOfElementsByTagName(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYs_regionToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), xDataXML_W_XYsDataToTOM(), and xDataXML_XYsToTOM().
enum xDataXML_itemMode xDataXML_getNextItem (xDataXML_item * item)
Definition at line 439 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 439 of file xDataTOM_importXML.cc
References xDataXML_item_s::element, xDataXML_text_s::length, xDataXML_item_s::mode, xDataXML_element_s::next, xDataXML_item_s::parentElement, xDataXML_text_s::text, xDataXML_element_s::text, xDataXML_item_s::text, xDataXML_item_s::textLength, xDataXML_element_s::textOffset, xDataXML_item_s::textOffset, xDataXML_itemModeElement, xDataXML_itemModeEnd, and xDataXML_itemModeText.
xDataXML_element* xDataXML_getOneElementByTagName (statusMessageReporting * smr, xDataXML_element * element, char * name, int required)
Definition at line 684 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 684 of file xDataTOM_importXML.cc
References xDataXML_elementListItem_s::element, xDataXML_element_s::fullName, xDataXML_elementList_s::items, xDataXML_elementList_s::n, smr_setReportError3, xDataTOM_smrLibraryID, xDataXML_freeElementList(), xDataXML_get_smrUserInterfaceFromElement(), and xDataXML_getElementsByTagName().
char const* xDataXML_getRealFileName (xDataXML_document * doc)
Definition at line 774 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 774 of file xDataTOM_importXML.cc
References xDataXML_document_s::realFileName.
static char * xDataXML_getTraceback (statusMessageReporting * smr, xDataXML_element * element) static
Definition at line 713 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 713 of file xDataTOM_importXML.cc
References int(), xDataXML_element_s::name, xDataXML_element_s::parentRoot, and xDataXML_getTraceback2().
Referenced by xDataXML_addElementToRoot().
static char * xDataXML_getTraceback2 (statusMessageReporting * smr, xDataXML_rootElement * parentRoot, int n) static
Definition at line 731 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 731 of file xDataTOM_importXML.cc
References int(), xDataXML_element_s::name, xDataXML_rootElement_s::parentElement, xDataXML_rootElement_s::parentRoot, and smr_malloc2.
Referenced by xDataXML_getTraceback().
xDataTOM_TOM* xDataXML_importFile (statusMessageReporting * smr, char const * fileName)
Definition at line 63 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 63 of file xDataTOM_importXML.cc
References xDataTOM_TOM_s::root, xDataTOM_freeTOM(), xDataTOM_mallocTOM(), xDataTOM_setFileNameTOM(), xDataXML_constructTOM(), xDataXML_freeDoc(), xDataXML_getDocumentsElement(), and xDataXML_importFile2().
Referenced by xDataTOM_importFile().
xDataXML_document* xDataXML_importFile2 (statusMessageReporting * smr, char const * fileName)
Definition at line 90 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 90 of file xDataTOM_importXML.cc
References buffer, close(), f, n, Acts::open, xDataXML_document_s::smr, smr_isOk(), smr_setReportError2, xDataTOM_smrLibraryID, xDataXML_endXMLParsing(), xDataXML_errFileError, xDataXML_freeDoc(), xDataXML_mallocDoc(), xDataXML_parse(), and xDataXML_setFileName().
Referenced by MCGIDI_map_readFile(), MCGIDI_target_read(), and xDataXML_importFile().
static int xDataXML_init_xDataTypeNone (xDataXMLType * xDT, xDataXML_element * element) static
Definition at line 520 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 520 of file xDataTOM_importXML.cc
References xDataXMLType_s::data, xDataXMLType_s::element, xDataXMLType_s::end, xDataXMLType_s::endPresent, xDataXMLType_s::ID, xDataXMLType_s::index, xDataXMLType_s::indexPresent, xDataXMLType_s::length, xDataXMLType_s::lengthPresent, xDataXMLType_s::release, xDataXMLType_s::start, xDataXMLType_s::startPresent, xDataXMLType_s::status, xDataXMLType_s::toData, xDataXMLType_s::toString, and xDataXML_xDataType_Ok.
Referenced by xDataXML_addElementToRoot().
void* xDataXML_initializeData (statusMessageReporting * smr, xDataXML_element * XE, xDataTOM_element * TE, char const * ID, size_t size)
Definition at line 1009 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 1009 of file xDataTOM_importXML.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::data, smr_freeMemory(), xData_initializeData(), xDataTOM_element_s::xDataInfo, and xDataXML_axesElememtToTOM().
Referenced by xDataXML_KalbachMannToTOM(), xDataXML_polynomialToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYsToTOM().
static int xDataXML_initializeDoc (statusMessageReporting * smr, xDataXML_document * doc) static
Definition at line 142 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 142 of file xDataTOM_importXML.cc
References xDataXML_document_s::currentRoot, xDataXML_document_s::err, xDataXML_document_s::err_column, xDataXML_document_s::err_line, xDataXML_document_s::error, xDataXML_document_s::fileName, xDataXML_document_s::realFileName, xDataXML_document_s::root, xDataXML_document_s::smr, smr_isOk(), smr_setReportError2p, xDataXML_document_s::status, xDataTOM_smrLibraryID, xDataXML_errNone, xDataXML_errXML_ParserCreate, xDataXML_initializeRootElement(), xDataXML_parseCharacterData(), xDataXML_parseEndElement(), xDataXML_parseStartElement(), xDataXML_smrUserInterfaceInitialize(), xDataXML_statusParsing, XML_ERROR_NONE, XML_ParserCreate(), XML_SetCharacterDataHandler(), XML_SetElementHandler(), XML_SetUserData(), and xDataXML_document_s::xmlParser.
Referenced by xDataXML_mallocDoc().
static void xDataXML_initializeRootElement (xDataXML_document * doc, xDataXML_rootElement * re, xDataXML_element * parentElement, int depth) static
Definition at line 286 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 286 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::children, xDataXML_rootElement_s::currentChild, xDataXML_rootElement_s::depth, xDataXML_rootElement_s::numberOfElements, xDataXML_rootElement_s::parentElement, xDataXML_rootElement_s::parentRoot, xDataXML_element_s::parentRoot, and xDataXML_rootElement_s::xData_doc.
Referenced by xDataXML_addElementToRoot(), and xDataXML_initializeDoc().
int xDataXML_is_xDataType (statusMessageReporting * smr, xDataXMLType * xDT, char const *const ID, int setMsg)
Definition at line 753 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 753 of file xDataTOM_importXML.cc
References xDataXMLType_s::element, xDataXML_element_s::fullName, xDataXMLType_s::ID, smr_setReportError3, xDataTOM_smrLibraryID, and xDataXML_get_smrUserInterfaceFromElement().
int xDataXML_isAttributeInElement (xDataXML_element * element, char const * name)
Definition at line 479 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 479 of file xDataTOM_importXML.cc
References xDataXML_element_s::attributes, and xDataXML_isAttributeInList().
int xDataXML_isAttributeInList (xDataXML_attributionList * attributes, char const * name)
Definition at line 467 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 467 of file xDataTOM_importXML.cc
References xDataXML_attributionList_s::attributes, xDataXML_attribute_s::name, and xDataXML_attributionList_s::number.
Referenced by xDataXML_isAttributeInElement().
static xDataXML_document * xDataXML_mallocDoc (statusMessageReporting * smr) static
Definition at line 130 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 130 of file xDataTOM_importXML.cc
References smr_malloc2, xDataXML_freeDoc(), and xDataXML_initializeDoc().
Referenced by xDataXML_importFile2().
int xDataXML_numberOfElementsByTagName (statusMessageReporting * , xDataXML_element * element, char const * tagName)
Definition at line 647 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 647 of file xDataTOM_importXML.cc
References n, xDataXML_element_s::name, xDataXML_getFirstElement(), and xDataXML_getNextElement().
Referenced by xDataXML_getElementsByTagName(), xDataXML_KalbachMannToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_regionsXYsToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYsDataToTOM().
static int xDataXML_parse (xDataXML_document * doc, char const * s) static
Definition at line 228 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 228 of file xDataTOM_importXML.cc
References xDataXML_document_s::status, xDataXML_statusParsing, XML_Parse(), XML_STATUS_ERROR, and xDataXML_document_s::xmlParser.
Referenced by xDataXML_importFile2().
static void XMLCALL xDataXML_parseCharacterData (void * userData, XML_Char const * s, int len) static
Definition at line 257 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 257 of file xDataTOM_importXML.cc
References xDataXML_text_s::allocated, xDataXML_rootElement_s::currentChild, xDataXML_document_s::currentRoot, xDataXML_text_s::length, xDataXML_rootElement_s::parentRoot, xDataXML_document_s::smr, smr_isOk(), smr_realloc2, xDataXML_text_s::text, and xDataXML_element_s::text.
Referenced by xDataXML_initializeDoc().
static void XMLCALL xDataXML_parseEndElement (void * userData, char const * name) static
Definition at line 247 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 247 of file xDataTOM_importXML.cc
References xDataXML_rootElement_s::currentChild, xDataXML_document_s::currentRoot, and xDataXML_rootElement_s::parentRoot.
Referenced by xDataXML_initializeDoc().
static enum xDataXML_errorCodes xDataXML_parseGetCurrentPosition (xDataXML_document * doc, xDataXML_docInfo * docInfo) static
Definition at line 397 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 397 of file xDataTOM_importXML.cc
References xDataXML_docInfo_s::column, xDataXML_docInfo_s::line, xDataXML_errNone, XML_GetCurrentColumnNumber(), XML_GetCurrentLineNumber(), and xDataXML_document_s::xmlParser.
Referenced by xDataXML_addElementToRoot(), and xDataXML_parseInitializeText().
static int xDataXML_parseInitializeText (xDataXML_document * doc, xDataXML_text * text) static
Definition at line 300 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 300 of file xDataTOM_importXML.cc
References xDataXML_text_s::allocated, xDataXML_text_s::docInfo, xDataXML_text_s::length, xDataXML_text_s::text, and xDataXML_parseGetCurrentPosition().
Referenced by xDataXML_addElementToRoot().
int xDataXML_parseIsError (xDataXML_document * doc)
Definition at line 406 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 406 of file xDataTOM_importXML.cc
References xDataXML_document_s::status, and xDataXML_statusError.
static void XMLCALL xDataXML_parseStartElement (void * userData, char const * name, char const ** attris) static
Definition at line 237 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 237 of file xDataTOM_importXML.cc
References xDataXML_document_s::currentRoot, xDataXML_document_s::smr, smr_isOk(), and xDataXML_addElementToRoot().
Referenced by xDataXML_initializeDoc().
static int xDataXML_setFileName (statusMessageReporting * smr, xDataXML_document * doc, char const * fileName) static
Definition at line 781 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 781 of file xDataTOM_importXML.cc
References xDataXML_document_s::fileName, PATH_MAX, xDataXML_document_s::realFileName, smr_allocateCopyString2, and smr_freeMemory().
Referenced by xDataXML_importFile2().
static char const * xDataXML_shortStringForMessage (size_t size, char * Out, char const * In) static
Definition at line 940 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 940 of file xDataTOM_importXML.cc
Referenced by xDataXML_stringTo_double(), and xDataXML_stringTo_xDataTOM_Int().
static char * xDataXML_smrUserInterface (void * userData) static
Definition at line 841 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 841 of file xDataTOM_importXML.cc
References xDataXML_docInfo_s::column, xDataXML_document_s::currentRoot, xDataXML_smr_s::doc, xDataXML_element_s::docInfo, xDataXML_document_s::fileName, xDataXML_element_s::fullName, xDataXML_docInfo_s::line, xDataXML_rootElement_s::parentElement, and smr_allocateFormatMessage().
Referenced by xDataXML_smrUserInterfaceInitialize().
static int xDataXML_smrUserInterfaceFree (xDataXML_document * doc) static
Definition at line 832 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 832 of file xDataTOM_importXML.cc
References xDataXML_smr_s::doc, xDataXML_smr_s::smrUserInterface, and xDataXML_document_s::smrUserInterface.
Referenced by xDataXML_freeDoc().
static int xDataXML_smrUserInterfaceInitialize (xDataXML_document * doc) static
Definition at line 823 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 823 of file xDataTOM_importXML.cc
References xDataXML_smr_s::doc, xDataXML_smr_s::smrUserInterface, xDataXML_document_s::smrUserInterface, and xDataXML_smrUserInterface().
Referenced by xDataXML_initializeDoc().
int xDataXML_stringTo_double (statusMessageReporting * smr, void * smrUserInterface, char const * c, double * value, char const * endings, char ** e)
Definition at line 891 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 891 of file xDataTOM_importXML.cc
References n, smr_setReportError3, tmp, xDataTOM_smrLibraryID, and xDataXML_shortStringForMessage().
Referenced by xDataXML_stringToDoubles().
int xDataXML_stringTo_xDataTOM_Int (statusMessageReporting * smr, void * smrUserInterface, char const * c, xDataTOM_Int * value, char const * endings, char ** e)
Definition at line 858 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 858 of file xDataTOM_importXML.cc
References n, smr_setReportError3, tmp, xDataTOM_smrLibraryID, and xDataXML_shortStringForMessage().
int xDataXML_xDataTypeConvertAttributes (statusMessageReporting * smr, xDataXML_element * element)
Definition at line 559 of file xDataTOM_importXML.cc.
View newest version in sPHENIX GitHub at line 559 of file xDataTOM_importXML.cc
References xDataXMLType_s::end, xDataXMLType_s::endPresent, xDataXMLType_s::index, xDataXMLType_s::indexPresent, xDataXMLType_s::length, xDataXMLType_s::lengthPresent, smr_setReportError3, smr_setReportError3p, xDataXMLType_s::start, xDataXMLType_s::startPresent, xDataTOM_smrLibraryID, xDataXML_element_s::xDataTypeInfo, xDataXML_convertAttributeTo_xDataTOM_Int(), and xDataXML_get_smrUserInterfaceFromElement().