ECCE @ EIC Software: HepGeom::BasicVector3D< T > Class Template Reference
HepGeom::BasicVector3D< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Geometry/BasicVector3D.h>
Public Types
enum {
X = 0, Y = 1, Z = 2, NUM_COORDINATES = 3,
SIZE = NUM_COORDINATES
}
Public Member Functions
BasicVector3D (T x1, T y1, T z1)
BasicVector3D (const BasicVector3D< T > &)=default
template<typename U = T, typename = typename std::enable_if<!std::is_same<U,float>::value >::type>
BasicVector3D (const BasicVector3D< float > &v)
BasicVector3D (BasicVector3D< T > &&)=default
virtual ~BasicVector3D ()=default
operator T * ()
operator const T * () const
operator CLHEP::Hep3Vector () const
BasicVector3D< T > & operator= (const BasicVector3D< T > &)=default
BasicVector3D< T > & operator= (BasicVector3D< T > &&)=default
BasicVector3D< T > & operator+= (const BasicVector3D< T > &v)
BasicVector3D< T > & operator-= (const BasicVector3D< T > &v)
BasicVector3D< T > & operator*= (double a)
BasicVector3D< T > & operator/= (double a)
T operator() (int i) const
T operator[] (int i) const
T & operator() (int i)
T & operator[] (int i)
T x () const
T y () const
T z () const
void setX (T a)
void setY (T a)
void setZ (T a)
void set (T x1, T y1, T z1)
T perp2 () const
T perp () const
T rho () const
void setPerp (T rh)
T mag2 () const
T mag () const
T r () const
T phi () const
T theta () const
T cosTheta () const
T getR () const
T getPhi () const
T getTheta () const
void setMag (T ma)
void setR (T ma)
void setPhi (T ph)
void setTheta (T th)
T pseudoRapidity () const
T eta () const
T getEta () const
void setEta (T a)
T dot (const BasicVector3D< T > &v) const
BasicVector3D< T > cross (const BasicVector3D< T > &v) const
T perp2 (const BasicVector3D< T > &v) const
T perp (const BasicVector3D< T > &v) const
T angle (const BasicVector3D< T > &v) const
BasicVector3D< T > unit () const
BasicVector3D< T > orthogonal () const
BasicVector3D< T > & rotateX (T a)
BasicVector3D< T > & rotateY (T a)
BasicVector3D< T > & rotateZ (T a)
BasicVector3D< T > & rotate (T a, const BasicVector3D< T > &v)
template<>
float pseudoRapidity () const
template<>
void setEta (float a)
template<>
float angle (const BasicVector3D< float > &v) const
template<>
BasicVector3D< float > & rotateX (float a)
template<>
BasicVector3D< float > & rotateY (float a)
template<>
BasicVector3D< float > & rotateZ (float a)
template<>
BasicVector3D< float > & rotate (float a, const BasicVector3D< float > &v)
template<>
double pseudoRapidity () const
template<>
void setEta (double a)
template<>
double angle (const BasicVector3D< double > &v) const
template<>
BasicVector3D< double > & rotateX (double a)
template<>
BasicVector3D< double > & rotateY (double a)
template<>
BasicVector3D< double > & rotateZ (double a)
template<>
BasicVector3D< double > & rotate (double a, const BasicVector3D< double > &v)
Protected Member Functions
BasicVector3D ()
Protected Attributes
T v_ [3]
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &, const BasicVector3D< float > &)
std::istream & operator>> (std::istream &, BasicVector3D< float > &)
BasicVector3D< float > operator+ (const BasicVector3D< float > &v)
BasicVector3D< float > operator+ (const BasicVector3D< float > &a, const BasicVector3D< float > &b)
BasicVector3D< float > operator- (const BasicVector3D< float > &v)
BasicVector3D< float > operator- (const BasicVector3D< float > &a, const BasicVector3D< float > &b)
BasicVector3D< float > operator* (const BasicVector3D< float > &v, double a)
float operator* (const BasicVector3D< float > &a, const BasicVector3D< float > &b)
BasicVector3D< float > operator* (double a, const BasicVector3D< float > &v)
BasicVector3D< float > operator/ (const BasicVector3D< float > &v, double a)
bool operator== (const BasicVector3D< float > &a, const BasicVector3D< float > &b)
bool operator!= (const BasicVector3D< float > &a, const BasicVector3D< float > &b)
std::ostream & operator<< (std::ostream &, const BasicVector3D< double > &)
std::istream & operator>> (std::istream &, BasicVector3D< double > &)
BasicVector3D< double > operator+ (const BasicVector3D< double > &v)
BasicVector3D< double > operator+ (const BasicVector3D< double > &a, const BasicVector3D< double > &b)
BasicVector3D< double > operator- (const BasicVector3D< double > &v)
BasicVector3D< double > operator- (const BasicVector3D< double > &a, const BasicVector3D< double > &b)
BasicVector3D< double > operator* (const BasicVector3D< double > &v, double a)
double operator* (const BasicVector3D< double > &a, const BasicVector3D< double > &b)
BasicVector3D< double > operator* (double a, const BasicVector3D< double > &v)
BasicVector3D< double > operator/ (const BasicVector3D< double > &v, double a)
bool operator== (const BasicVector3D< double > &a, const BasicVector3D< double > &b)
bool operator!= (const BasicVector3D< double > &a, const BasicVector3D< double > &b)
Detailed Description
template<class T>
class HepGeom::BasicVector3D< T >
Base class for Point3D<T>, Vector3D<T> and Normal3D<T>. It defines only common functionality for those classes and should not be used as separate class.
Author
Evgeni Chernyaev Evgue.nosp@m.ni.T.nosp@m.chern.nosp@m.iaev.nosp@m.@cern.nosp@m..ch
Definition at line 27 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 27 of file BasicVector3D.h
Member Enumeration Documentation
template<class T> anonymous enum
Safe indexing of the coordinates when using with matrices, arrays, etc.
Enumerator:
X
index for x-component
Y
index for y-component
Z
index for z-component
NUM_COORDINATES
number of components
SIZE
number of components
Definition at line 41 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 41 of file BasicVector3D.h
Constructor & Destructor Documentation
template<class T> HepGeom::BasicVector3D< T >::BasicVector3D () inline protected
Default constructor. It is protected - this class should not be instantiated directly.
Definition at line 35 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 35 of file BasicVector3D.h
template<class T> HepGeom::BasicVector3D< T >::BasicVector3D (T x1, T y1, T z1) inline
Constructor from three numbers.
Definition at line 51 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 51 of file BasicVector3D.h
template<class T> HepGeom::BasicVector3D< T >::BasicVector3D (const BasicVector3D< T > &) default
Copy constructor.
template<class T> template<typename U = T, typename = typename std::enable_if<!std::is_same<U,float>::value >::type> HepGeom::BasicVector3D< T >::BasicVector3D (const BasicVector3D< float > & v) inline
Constructor for BasicVector3D<double> from BasicVector3D<float>.
Definition at line 61 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 61 of file BasicVector3D.h
template<class T> HepGeom::BasicVector3D< T >::BasicVector3D (BasicVector3D< T > &&) default
Move constructor.
template<class T> virtual HepGeom::BasicVector3D< T >::~BasicVector3D () virtual default
Destructor.
Member Function Documentation
template<> float HepGeom::BasicVector3D< float >::angle (const BasicVector3D< float > & v) const
Definition at line 35 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 35 of file BasicVector3D.cc
References HepGeom::BasicVector3D< T >::mag().
template<> double HepGeom::BasicVector3D< double >::angle (const BasicVector3D< double > & v) const
Definition at line 191 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 191 of file BasicVector3D.cc
References HepGeom::BasicVector3D< T >::mag().
template<class T> T HepGeom::BasicVector3D< T >::angle (const BasicVector3D< T > & v) const
Returns angle w.r.t. another vector.
Referenced by PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), and PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower().
template<class T> T HepGeom::BasicVector3D< T >::cosTheta () const inline
Gets cosine of polar angle.
Definition at line 217 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 217 of file BasicVector3D.h
template<class T> BasicVector3D<T> HepGeom::BasicVector3D< T >::cross (const BasicVector3D< T > & v) const inline
Vector product.
Definition at line 281 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 281 of file BasicVector3D.h
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), G4VSceneHandler::CreateSectionSolid(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4ErrorSurfaceTrajParam::GetPlaneNormal(), G4ViewParameters::IncrementPan(), G4ViewParameters::SetPan(), G4ErrorFreeTrajParam::SetParameters(), G4ViewParameters::SetViewAndLights(), HepPolyhedron::Transform(), and HepGeom::Transform3D::Transform3D().
template<class T> T HepGeom::BasicVector3D< T >::dot (const BasicVector3D< T > & v) const inline
Scalar product.
Definition at line 275 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 275 of file BasicVector3D.h
Referenced by G4VSceneHandler::CreateSectionSolid(), PHG4OuterHcalField::GetFieldValue(), HepGeom::BasicVector3D< T >::operator*(), and HepGeom::BasicVector3D< G4double >::perp2().
template<class T> T HepGeom::BasicVector3D< T >::eta () const inline
Gets pseudo-rapidity.
Definition at line 260 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 260 of file BasicVector3D.h
template<class T> T HepGeom::BasicVector3D< T >::getEta () const inline
Gets pseudo-rapidity.
Definition at line 263 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 263 of file BasicVector3D.h
template<class T> T HepGeom::BasicVector3D< T >::getPhi () const inline
Gets phi-component in spherical coordinate system
Definition at line 224 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 224 of file BasicVector3D.h
template<class T> T HepGeom::BasicVector3D< T >::getR () const inline
Gets r-component in spherical coordinate system
Definition at line 221 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 221 of file BasicVector3D.h
template<class T> T HepGeom::BasicVector3D< T >::getTheta () const inline
Gets theta-component in spherical coordinate system
Definition at line 227 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 227 of file BasicVector3D.h
template<class T> T HepGeom::BasicVector3D< T >::mag () const inline
Gets magnitude of the vector.
Definition at line 201 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 201 of file BasicVector3D.h
Referenced by G4BoundingSphereScene::AccrueBoundingSphere(), HepGeom::BasicVector3D< T >::angle(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), HepGeom::BasicVector3D< G4double >::cosTheta(), G4VSceneHandler::CreateSectionSolid(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4ErrorPropagator::Propagate(), G4ErrorFreeTrajState::PropagateError(), G4ErrorPropagator::PropagateOneStep(), HepGeom::BasicVector3D< G4double >::r(), HepGeom::BasicVector3D< G4double >::setMag(), G4ErrorFreeTrajParam::SetParameters(), G4ErrorSurfaceTrajParam::SetParameters(), HepGeom::BasicVector3D< G4double >::setTheta(), and HepGeom::BasicVector3D< G4double >::unit().
template<class T> T HepGeom::BasicVector3D< T >::mag2 () const inline
Gets magnitude squared of the vector.
Definition at line 198 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 198 of file BasicVector3D.h
Referenced by G4BoundingEnvelope::CreateListOfPlanes(), HepGeom::Point3D< float >::distance2(), HepGeom::Point3D< double >::distance2(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), HepGeom::BasicVector3D< G4double >::mag(), and HepGeom::BasicVector3D< G4double >::perp2().
template<class T> HepGeom::BasicVector3D< T >::operator CLHEP::Hep3Vector () const inline
Conversion (cast) to CLHEP::Hep3Vector. This operator is needed only for backward compatibility and in principle should not exit.
Definition at line 90 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 90 of file BasicVector3D.h
template<class T> HepGeom::BasicVector3D< T >::operator const T * () const inline
Conversion (cast) to ordinary const array.
Definition at line 83 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 83 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::v_.
template<class T> HepGeom::BasicVector3D< T >::operator T * () inline
Conversion (cast) to ordinary array.
Definition at line 79 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 79 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::v_.
template<class T> T HepGeom::BasicVector3D< T >::operator() (int i) const inline
Gets components by index.
Definition at line 129 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 129 of file BasicVector3D.h
template<class T> T& HepGeom::BasicVector3D< T >::operator() (int i) inline
Sets components by index.
Definition at line 136 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 136 of file BasicVector3D.h
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::operator*= (double a) inline
Multiplication by scalar.
Definition at line 114 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 114 of file BasicVector3D.h
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::operator+= (const BasicVector3D< T > & v) inline
Addition.
Definition at line 104 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 104 of file BasicVector3D.h
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::operator-= (const BasicVector3D< T > & v) inline
Subtraction.
Definition at line 109 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 109 of file BasicVector3D.h
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::operator/= (double a) inline
Division by scalar.
Definition at line 119 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 119 of file BasicVector3D.h
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::operator= (const BasicVector3D< T > &) default
Assignment.
Referenced by HepGeom::Normal3D< float >::operator=(), HepGeom::Vector3D< float >::operator=(), HepGeom::Point3D< float >::operator=(), HepGeom::Vector3D< double >::operator=(), HepGeom::Normal3D< double >::operator=(), and HepGeom::Point3D< double >::operator=().
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::operator= (BasicVector3D< T > &&) default
Move assignment.
template<class T> T HepGeom::BasicVector3D< T >::operator[] (int i) const inline
Gets components by index.
Definition at line 132 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 132 of file BasicVector3D.h
template<class T> T& HepGeom::BasicVector3D< T >::operator[] (int i) inline
Sets components by index.
Definition at line 139 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 139 of file BasicVector3D.h
template<class T> BasicVector3D<T> HepGeom::BasicVector3D< T >::orthogonal () const inline
Returns orthogonal vector.
Definition at line 318 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 318 of file BasicVector3D.h
template<class T> T HepGeom::BasicVector3D< T >::perp () const inline
Gets transverse component.
Definition at line 178 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 178 of file BasicVector3D.h
Referenced by G4ErrorFreeTrajState::PropagateError(), HepGeom::BasicVector3D< G4double >::rho(), HepGeom::BasicVector3D< G4double >::setPerp(), HepGeom::BasicVector3D< G4double >::setPhi(), and HepGeom::BasicVector3D< G4double >::theta().
template<class T> T HepGeom::BasicVector3D< T >::perp (const BasicVector3D< T > & v) const inline
Returns transverse component w.r.t. given axis.
Definition at line 296 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 296 of file BasicVector3D.h
template<class T> T HepGeom::BasicVector3D< T >::perp2 () const inline
Gets transverse component squared.
Definition at line 175 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 175 of file BasicVector3D.h
Referenced by HepGeom::BasicVector3D< G4double >::perp().
template<class T> T HepGeom::BasicVector3D< T >::perp2 (const BasicVector3D< T > & v) const inline
Returns transverse component w.r.t. given axis squared.
Definition at line 289 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 289 of file BasicVector3D.h
template<class T> T HepGeom::BasicVector3D< T >::phi () const inline
Gets azimuth angle.
Definition at line 207 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 207 of file BasicVector3D.h
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), G4ArrowModel::G4ArrowModel(), HepGeom::BasicVector3D< G4double >::getPhi(), G4ErrorFreeTrajParam::SetParameters(), and HepGeom::BasicVector3D< G4double >::setTheta().
template<> float HepGeom::BasicVector3D< float >::pseudoRapidity () const
Definition at line 12 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 12 of file BasicVector3D.cc
References dz, FLT_MAX, and z.
template<> double HepGeom::BasicVector3D< double >::pseudoRapidity () const
Definition at line 168 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 168 of file BasicVector3D.cc
References DBL_MAX, dz, and z.
template<class T> T HepGeom::BasicVector3D< T >::pseudoRapidity () const
Gets pseudo-rapidity: -ln(tan(theta/2))
Referenced by HepGeom::BasicVector3D< G4double >::eta(), and HepGeom::BasicVector3D< G4double >::getEta().
template<class T> T HepGeom::BasicVector3D< T >::r () const inline
Gets r-component in spherical coordinate system
Definition at line 204 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 204 of file BasicVector3D.h
Referenced by HepGeom::BasicVector3D< G4double >::getR().
template<class T> T HepGeom::BasicVector3D< T >::rho () const inline
Gets rho-component in cylindrical coordinate system
Definition at line 181 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 181 of file BasicVector3D.h
Referenced by pyhixtot(), and pyxtot().
template<> BasicVector3D< float > & HepGeom::BasicVector3D< float >::rotate (float a, const BasicVector3D< float > & v)
Definition at line 76 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 76 of file BasicVector3D.cc
References x, HepGeom::BasicVector3D< T >::x(), xx, HepGeom::BasicVector3D< T >::y(), y, HepGeom::BasicVector3D< T >::z(), z, and zz.
template<> BasicVector3D< double > & HepGeom::BasicVector3D< double >::rotate (double a, const BasicVector3D< double > & v)
Definition at line 232 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 232 of file BasicVector3D.cc
References x, HepGeom::BasicVector3D< T >::x(), xx, HepGeom::BasicVector3D< T >::y(), y, HepGeom::BasicVector3D< T >::z(), z, and zz.
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::rotate (T a, const BasicVector3D< T > & v)
Rotates around the axis specified by another vector.
template<> BasicVector3D< float > & HepGeom::BasicVector3D< float >::rotateX (float a)
Definition at line 48 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 48 of file BasicVector3D.cc
References dy, dz, y, and z.
template<> BasicVector3D< double > & HepGeom::BasicVector3D< double >::rotateX (double a)
Definition at line 204 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 204 of file BasicVector3D.cc
References dy, dz, y, and z.
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::rotateX (T a)
Rotates around x-axis.
template<> BasicVector3D< float > & HepGeom::BasicVector3D< float >::rotateY (float a)
Definition at line 57 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 57 of file BasicVector3D.cc
References dx, dz, x, and z.
template<> BasicVector3D< double > & HepGeom::BasicVector3D< double >::rotateY (double a)
Definition at line 213 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 213 of file BasicVector3D.cc
References dx, dz, x, and z.
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::rotateY (T a)
Rotates around y-axis.
template<> BasicVector3D< float > & HepGeom::BasicVector3D< float >::rotateZ (float a)
Definition at line 66 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 66 of file BasicVector3D.cc
References dx, dy, x, and y.
template<> BasicVector3D< double > & HepGeom::BasicVector3D< double >::rotateZ (double a)
Definition at line 222 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 222 of file BasicVector3D.cc
References dx, dy, x, and y.
template<class T> BasicVector3D<T>& HepGeom::BasicVector3D< T >::rotateZ (T a)
Rotates around z-axis.
Referenced by G4VisCommandSceneAddArrow2D::Arrow2D::Arrow2D().
template<class T> void HepGeom::BasicVector3D< T >::set (T x1, T y1, T z1) inline
Sets components in cartesian coordinate system.
Definition at line 167 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 167 of file BasicVector3D.h
Referenced by G4ElectricFieldModel::GetFieldAtLocation(), and G4MagneticFieldModel::GetFieldAtLocation().
template<> void HepGeom::BasicVector3D< float >::setEta (float a)
Definition at line 22 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 22 of file BasicVector3D.cc
References phi.
template<> void HepGeom::BasicVector3D< double >::setEta (double a)
Definition at line 178 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 178 of file BasicVector3D.cc
References phi.
template<class T> void HepGeom::BasicVector3D< T >::setEta (T a)
Sets pseudo-rapidity, keeping magnitude and phi fixed.
template<class T> void HepGeom::BasicVector3D< T >::setMag (T ma) inline
Sets magnitude.
Definition at line 231 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 231 of file BasicVector3D.h
Referenced by HepGeom::BasicVector3D< G4double >::setR().
template<class T> void HepGeom::BasicVector3D< T >::setPerp (T rh) inline
Sets transverse component keeping phi and z constant.
Definition at line 185 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 185 of file BasicVector3D.h
template<class T> void HepGeom::BasicVector3D< T >::setPhi (T ph) inline
Sets phi-component in spherical coordinate system.
Definition at line 242 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 242 of file BasicVector3D.h
template<class T> void HepGeom::BasicVector3D< T >::setR (T ma) inline
Sets r-component in spherical coordinate system.
Definition at line 239 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 239 of file BasicVector3D.h
template<class T> void HepGeom::BasicVector3D< T >::setTheta (T th) inline
Sets theta-component in spherical coordinate system.
Definition at line 245 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 245 of file BasicVector3D.h
template<class T> void HepGeom::BasicVector3D< T >::setX (T a) inline
Sets x-component in cartesian coordinate system.
Definition at line 157 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 157 of file BasicVector3D.h
Referenced by G4BoundingEnvelope::ClipEdgesByVoxel(), G4BoundingEnvelope::ClipVoxelByPlanes(), HepPolyhedronEllipsoid::HepPolyhedronEllipsoid(), HepPolyhedronEllipticalCone::HepPolyhedronEllipticalCone(), HepGeom::operator>>(), G4ErrorFreeTrajState::PropagateError(), and HepGeom::BasicVector3D< G4double >::setPhi().
template<class T> void HepGeom::BasicVector3D< T >::setY (T a) inline
Sets y-component in cartesian coordinate system.
Definition at line 160 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 160 of file BasicVector3D.h
Referenced by G4BoundingEnvelope::ClipEdgesByVoxel(), G4BoundingEnvelope::ClipVoxelByPlanes(), HepPolyhedronEllipsoid::HepPolyhedronEllipsoid(), HepPolyhedronEllipticalCone::HepPolyhedronEllipticalCone(), HepGeom::operator>>(), and HepGeom::BasicVector3D< G4double >::setPhi().
template<class T> void HepGeom::BasicVector3D< T >::setZ (T a) inline
Sets z-component in cartesian coordinate system.
Definition at line 163 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 163 of file BasicVector3D.h
Referenced by G4BoundingEnvelope::ClipEdgesByVoxel(), G4BoundingEnvelope::ClipVoxelByPlanes(), and HepGeom::operator>>().
template<class T> T HepGeom::BasicVector3D< T >::theta () const inline
Gets polar angle.
Definition at line 212 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 212 of file BasicVector3D.h
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), G4ArrowModel::G4ArrowModel(), HepGeom::BasicVector3D< G4double >::getTheta(), G4ErrorFreeTrajState::PropagateError(), G4DAWNFILEViewer::SendViewParameters(), and G4ErrorFreeTrajParam::SetParameters().
template<class T> BasicVector3D<T> HepGeom::BasicVector3D< T >::unit () const inline
Returns unit vector parallel to this.
Definition at line 310 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 310 of file BasicVector3D.h
Referenced by G4BoundingSphereScene::AccrueBoundingSphere(), G4VisCommandSceneAddArrow2D::Arrow2D::Arrow2D(), G4ViewParameters::CatmullRomCubicSplineInterpolation(), PerspectiveVisAction::ExtendedDraw(), HepPolyhedron::FindNodeNormal(), G4ArrowModel::G4ArrowModel(), G4DAWNFILEViewer::SendViewParameters(), G4RayTracerViewer::SetView(), and G4ViewParameters::SetViewAndLights().
template<class T> T HepGeom::BasicVector3D< T >::x () const inline
Gets x-component in cartesian coordinate system.
Definition at line 147 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 147 of file BasicVector3D.h
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4HepRepSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), HepGeom::BasicVector3D< G4double >::BasicVector3D(), G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4BoundingEnvelope::ClipVoxelByPlanes(), G4VViewer::ComputeFlyThrough(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), G4CutTubs::CreatePolyhedron(), HepGeom::BasicVector3D< G4double >::cross(), G4VFieldModel::DescribeYourselfTo(), HepGeom::Plane3D< G4double >::distance(), HepGeom::Point3D< float >::distance2(), HepGeom::Point3D< double >::distance2(), HepGeom::BasicVector3D< G4double >::dot(), PerspectiveVisAction::ExtendedDraw(), G4GMocrenFileSceneHandler::ExtractDetector(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4VisExtent::G4VisExtent(), G4ElectricFieldModel::GetFieldAtLocation(), G4MagneticFieldModel::GetFieldAtLocation(), PHG4OuterHcalField::GetFieldValue(), HepPolyhedronEllipsoid::HepPolyhedronEllipsoid(), HepPolyhedronEllipticalCone::HepPolyhedronEllipticalCone(), HepGeom::BasicVector3D< G4double >::mag2(), G4ViewParameters::MultiplyScaleFactor(), HepGeom::BasicVector3D< G4double >::operator CLHEP::Hep3Vector(), HepGeom::Normal3D< double >::operator CLHEP::Hep3Vector(), HepGeom::Vector3D< double >::operator CLHEP::Hep3Vector(), HepGeom::Point3D< double >::operator CLHEP::Hep3Vector(), HepGeom::BasicVector3D< T >::operator!=(), HepGeom::operator*(), HepGeom::BasicVector3D< T >::operator*(), HepGeom::BasicVector3D< T >::operator+(), HepGeom::BasicVector3D< T >::operator-(), HepGeom::BasicVector3D< T >::operator/(), operator<<(), HepGeom::BasicVector3D< T >::operator==(), HepGeom::BasicVector3D< G4double >::orthogonal(), HepGeom::BasicVector3D< G4double >::perp2(), HepGeom::BasicVector3D< G4double >::phi(), HepGeom::Plane3D< G4double >::Plane3D(), HepGeom::Plane3D< G4double >::point(), G4ErrorFreeTrajState::PropagateError(), HepGeom::BasicVector3D< T >::rotate(), HepGeom::Rotate3D::Rotate3D(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), G4ErrorFreeTrajParam::SetParameters(), G4ViewParameters::SetViewAndLights(), HepGeom::BasicVector3D< G4double >::theta(), HepGeom::Normal3D< float >::transform(), HepGeom::Vector3D< float >::transform(), HepGeom::Point3D< float >::transform(), HepGeom::Plane3D< G4double >::transform(), HepGeom::Normal3D< double >::transform(), HepGeom::Vector3D< double >::transform(), HepGeom::Point3D< double >::transform(), HepGeom::Transform3D::Transform3D(), and HepGeom::BasicVector3D< G4double >::unit().
template<class T> T HepGeom::BasicVector3D< T >::y () const inline
Gets y-component in cartesian coordinate system.
Definition at line 150 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 150 of file BasicVector3D.h
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4HepRepSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), HepGeom::BasicVector3D< G4double >::BasicVector3D(), G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4BoundingEnvelope::ClipVoxelByPlanes(), G4VViewer::ComputeFlyThrough(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), G4CutTubs::CreatePolyhedron(), HepGeom::BasicVector3D< G4double >::cross(), G4VFieldModel::DescribeYourselfTo(), HepGeom::Plane3D< G4double >::distance(), HepGeom::Point3D< float >::distance2(), HepGeom::Point3D< double >::distance2(), HepGeom::BasicVector3D< G4double >::dot(), PerspectiveVisAction::ExtendedDraw(), G4GMocrenFileSceneHandler::ExtractDetector(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4VisExtent::G4VisExtent(), G4ElectricFieldModel::GetFieldAtLocation(), G4MagneticFieldModel::GetFieldAtLocation(), PHG4OuterHcalField::GetFieldValue(), HepPolyhedronEllipsoid::HepPolyhedronEllipsoid(), HepPolyhedronEllipticalCone::HepPolyhedronEllipticalCone(), HepGeom::BasicVector3D< G4double >::mag2(), G4ViewParameters::MultiplyScaleFactor(), HepGeom::BasicVector3D< G4double >::operator CLHEP::Hep3Vector(), HepGeom::Normal3D< double >::operator CLHEP::Hep3Vector(), HepGeom::Vector3D< double >::operator CLHEP::Hep3Vector(), HepGeom::Point3D< double >::operator CLHEP::Hep3Vector(), HepGeom::BasicVector3D< T >::operator!=(), HepGeom::operator*(), HepGeom::BasicVector3D< T >::operator*(), HepGeom::BasicVector3D< T >::operator+(), HepGeom::BasicVector3D< T >::operator-(), HepGeom::BasicVector3D< T >::operator/(), operator<<(), HepGeom::BasicVector3D< T >::operator==(), HepGeom::BasicVector3D< G4double >::orthogonal(), HepGeom::BasicVector3D< G4double >::perp2(), HepGeom::BasicVector3D< G4double >::phi(), HepGeom::Plane3D< G4double >::Plane3D(), HepGeom::Plane3D< G4double >::point(), G4ErrorFreeTrajState::PropagateError(), HepGeom::BasicVector3D< T >::rotate(), HepGeom::Rotate3D::Rotate3D(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), G4ErrorFreeTrajParam::SetParameters(), G4ViewParameters::SetViewAndLights(), HepGeom::BasicVector3D< G4double >::theta(), HepGeom::Normal3D< float >::transform(), HepGeom::Vector3D< float >::transform(), HepGeom::Point3D< float >::transform(), HepGeom::Plane3D< G4double >::transform(), HepGeom::Normal3D< double >::transform(), HepGeom::Vector3D< double >::transform(), HepGeom::Point3D< double >::transform(), HepGeom::Transform3D::Transform3D(), and HepGeom::BasicVector3D< G4double >::unit().
template<class T> T HepGeom::BasicVector3D< T >::z () const inline
Gets z-component in cartesian coordinate system.
Definition at line 153 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 153 of file BasicVector3D.h
Referenced by G4HepRepFileSceneHandler::AddCompound(), G4HepRepSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddPrimitive(), G4HepRepFileSceneHandler::AddSolid(), G4HepRepSceneHandler::AddSolid(), G4GMocrenFileSceneHandler::AddSolid(), HepGeom::BasicVector3D< G4double >::BasicVector3D(), G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4BoundingEnvelope::CalculateExtent(), G4BoundingEnvelope::ClipEdgesByVoxel(), G4BoundingEnvelope::ClipVoxelByPlanes(), G4VViewer::ComputeFlyThrough(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), HepGeom::BasicVector3D< G4double >::cosTheta(), G4CutTubs::CreatePolyhedron(), HepGeom::BasicVector3D< G4double >::cross(), G4VFieldModel::DescribeYourselfTo(), HepGeom::Plane3D< G4double >::distance(), HepGeom::Point3D< float >::distance2(), HepGeom::Point3D< double >::distance2(), HepGeom::BasicVector3D< G4double >::dot(), PerspectiveVisAction::ExtendedDraw(), G4GMocrenFileSceneHandler::ExtractDetector(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4VisExtent::G4VisExtent(), G4ElectricFieldModel::GetFieldAtLocation(), G4MagneticFieldModel::GetFieldAtLocation(), PHG4OuterHcalField::GetFieldValue(), HepGeom::BasicVector3D< G4double >::mag2(), G4ViewParameters::MultiplyScaleFactor(), HepGeom::BasicVector3D< G4double >::operator CLHEP::Hep3Vector(), HepGeom::Vector3D< double >::operator CLHEP::Hep3Vector(), HepGeom::Normal3D< double >::operator CLHEP::Hep3Vector(), HepGeom::Point3D< double >::operator CLHEP::Hep3Vector(), HepGeom::BasicVector3D< T >::operator!=(), HepGeom::operator*(), HepGeom::BasicVector3D< T >::operator*(), HepGeom::BasicVector3D< T >::operator+(), HepGeom::BasicVector3D< T >::operator-(), HepGeom::BasicVector3D< T >::operator/(), operator<<(), HepGeom::BasicVector3D< T >::operator==(), HepGeom::BasicVector3D< G4double >::orthogonal(), HepGeom::Plane3D< G4double >::Plane3D(), HepGeom::Plane3D< G4double >::point(), G4ErrorFreeTrajState::PropagateError(), HepGeom::BasicVector3D< T >::rotate(), HepGeom::Rotate3D::Rotate3D(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), HepGeom::BasicVector3D< G4double >::theta(), HepGeom::Vector3D< float >::transform(), HepGeom::Normal3D< float >::transform(), HepGeom::Point3D< float >::transform(), HepGeom::Plane3D< G4double >::transform(), HepGeom::Vector3D< double >::transform(), HepGeom::Normal3D< double >::transform(), HepGeom::Point3D< double >::transform(), HepGeom::Transform3D::Transform3D(), and HepGeom::BasicVector3D< G4double >::unit().
Friends And Related Function Documentation
template<class T> bool operator!= (const BasicVector3D< float > & a, const BasicVector3D< float > & b) related
Comparison of two vectors for inequality.
Definition at line 453 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 453 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> bool operator!= (const BasicVector3D< double > & a, const BasicVector3D< double > & b) related
Comparison of two vectors for inequality.
Definition at line 562 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 562 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< float > operator* (const BasicVector3D< float > & v, double a) related
Multiplication vector by scalar.
Definition at line 408 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 408 of file BasicVector3D.h
References a, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> float operator* (const BasicVector3D< float > & a, const BasicVector3D< float > & b) related
Scalar product of two vectors.
Definition at line 417 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 417 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::dot().
template<class T> BasicVector3D< float > operator* (double a, const BasicVector3D< float > & v) related
Multiplication scalar by vector.
Definition at line 426 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 426 of file BasicVector3D.h
References a, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< double > operator* (const BasicVector3D< double > & v, double a) related
Multiplication vector by scalar.
Definition at line 516 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 516 of file BasicVector3D.h
References a, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> double operator* (const BasicVector3D< double > & a, const BasicVector3D< double > & b) related
Scalar product of two vectors.
Definition at line 525 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 525 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::dot().
template<class T> BasicVector3D< double > operator* (double a, const BasicVector3D< double > & v) related
Multiplication scalar by vector.
Definition at line 534 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 534 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< float > operator+ (const BasicVector3D< float > & v) related
Unary plus.
Definition at line 374 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 374 of file BasicVector3D.h
References v.
template<class T> BasicVector3D< float > operator+ (const BasicVector3D< float > & a, const BasicVector3D< float > & b) related
Addition of two vectors.
Definition at line 381 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 381 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< double > operator+ (const BasicVector3D< double > & v) related
Unary plus.
Definition at line 482 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 482 of file BasicVector3D.h
References v.
template<class T> BasicVector3D< double > operator+ (const BasicVector3D< double > & a, const BasicVector3D< double > & b) related
Addition of two vectors.
Definition at line 489 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 489 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< float > operator- (const BasicVector3D< float > & v) related
Unary minus.
Definition at line 390 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 390 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< float > operator- (const BasicVector3D< float > & a, const BasicVector3D< float > & b) related
Subtraction of two vectors.
Definition at line 399 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 399 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< double > operator- (const BasicVector3D< double > & v) related
Unary minus.
Definition at line 498 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 498 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< double > operator- (const BasicVector3D< double > & a, const BasicVector3D< double > & b) related
Subtraction of two vectors.
Definition at line 507 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 507 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< float > operator/ (const BasicVector3D< float > & v, double a) related
Division vector by scalar.
Definition at line 435 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 435 of file BasicVector3D.h
References a, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> BasicVector3D< double > operator/ (const BasicVector3D< double > & v, double a) related
Division vector by scalar.
Definition at line 543 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 543 of file BasicVector3D.h
References a, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> std::ostream & operator<< (std::ostream & , const BasicVector3D< float > &) related
Output to stream.
Definition at line 106 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 106 of file BasicVector3D.cc
template<class T> std::ostream & operator<< (std::ostream & , const BasicVector3D< double > &) related
Output to stream.
Definition at line 262 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 262 of file BasicVector3D.cc
template<class T> bool operator== (const BasicVector3D< float > & a, const BasicVector3D< float > & b) related
Comparison of two vectors for equality.
Definition at line 444 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 444 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
Referenced by G4Solver< Function >::operator!=().
template<class T> bool operator== (const BasicVector3D< double > & a, const BasicVector3D< double > & b) related
Comparison of two vectors for equality.
Definition at line 552 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 552 of file BasicVector3D.h
References HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
template<class T> std::istream & operator>> (std::istream & , BasicVector3D< float > &) related
Input from stream.
Definition at line 113 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 113 of file BasicVector3D.cc
template<class T> std::istream & operator>> (std::istream & , BasicVector3D< double > &) related
Input from stream.
Definition at line 269 of file BasicVector3D.cc.
View newest version in sPHENIX GitHub at line 269 of file BasicVector3D.cc
Member Data Documentation
template<class T> T HepGeom::BasicVector3D< T >::v_[3] protected
Definition at line 29 of file BasicVector3D.h.
View newest version in sPHENIX GitHub at line 29 of file BasicVector3D.h
Referenced by HepGeom::BasicVector3D< G4double >::BasicVector3D(), HepGeom::BasicVector3D< T >::operator const T *(), HepGeom::BasicVector3D< T >::operator T *(), HepGeom::BasicVector3D< G4double >::operator()(), HepGeom::BasicVector3D< G4double >::operator*=(), HepGeom::BasicVector3D< G4double >::operator+=(), HepGeom::BasicVector3D< G4double >::operator-=(), HepGeom::BasicVector3D< G4double >::operator/=(), HepGeom::BasicVector3D< G4double >::operator[](), HepGeom::BasicVector3D< G4double >::set(), HepGeom::BasicVector3D< G4double >::setMag(), HepGeom::BasicVector3D< G4double >::setPerp(), HepGeom::BasicVector3D< G4double >::setX(), HepGeom::BasicVector3D< G4double >::setY(), HepGeom::BasicVector3D< G4double >::setZ(), HepGeom::BasicVector3D< G4double >::x(), HepGeom::BasicVector3D< G4double >::y(), and HepGeom::BasicVector3D< G4double >::z().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Geometry/BasicVector3D.h