ECCE @ EIC Software: G4tgrParameterMgr Class Reference
G4tgrParameterMgr Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrParameterMgr.hh>
Public Member Functions
void AddParameterNumber (const std::vector< G4String > &wl, G4bool mustBeNew=0)
void AddParameterString (const std::vector< G4String > &wl, G4bool mustBeNew=0)
void CheckIfNewParameter (const std::vector< G4String > &wl, G4bool mustBeNew)
G4String FindParameter (const G4String &name, G4bool exists=true)
void DumpList ()
Static Public Member Functions
static G4tgrParameterMgr * GetInstance ()
Private Member Functions
G4tgrParameterMgr ()
~G4tgrParameterMgr ()
Private Attributes
G4mapss theParameterList
Static Private Attributes
static G4ThreadLocal
G4tgrParameterMgr * theInstance = 0
Detailed Description
Definition at line 49 of file G4tgrParameterMgr.hh.
View newest version in sPHENIX GitHub at line 49 of file G4tgrParameterMgr.hh
Constructor & Destructor Documentation
G4tgrParameterMgr::G4tgrParameterMgr () private
Definition at line 47 of file G4tgrParameterMgr.cc.
View newest version in sPHENIX GitHub at line 47 of file G4tgrParameterMgr.cc
Referenced by GetInstance().
G4tgrParameterMgr::~G4tgrParameterMgr () private
Definition at line 53 of file G4tgrParameterMgr.cc.
View newest version in sPHENIX GitHub at line 53 of file G4tgrParameterMgr.cc
References theInstance.
Member Function Documentation
void G4tgrParameterMgr::AddParameterNumber (const std::vector< G4String > & wl, G4bool mustBeNew = 0)
Definition at line 71 of file G4tgrParameterMgr.cc.
View newest version in sPHENIX GitHub at line 71 of file G4tgrParameterMgr.cc
References CheckIfNewParameter(), G4UIcommand::ConvertToString(), G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrMessenger::GetVerboseLevel(), and theParameterList.
Referenced by G4tgrLineProcessor::ProcessLine().
void G4tgrParameterMgr::AddParameterString (const std::vector< G4String > & wl, G4bool mustBeNew = 0)
Definition at line 93 of file G4tgrParameterMgr.cc.
View newest version in sPHENIX GitHub at line 93 of file G4tgrParameterMgr.cc
References CheckIfNewParameter(), G4cout, G4endl, G4tgrMessenger::GetVerboseLevel(), and theParameterList.
Referenced by G4tgrLineProcessor::ProcessLine().
void G4tgrParameterMgr::CheckIfNewParameter (const std::vector< G4String > & wl, G4bool mustBeNew)
Definition at line 112 of file G4tgrParameterMgr.cc.
View newest version in sPHENIX GitHub at line 112 of file G4tgrParameterMgr.cc
References G4tgrUtils::CheckWLsize(), FatalException, G4Exception(), JustWarning, theParameterList, and WLSIZE_EQ.
Referenced by AddParameterNumber(), and AddParameterString().
void G4tgrParameterMgr::DumpList ()
Definition at line 182 of file G4tgrParameterMgr.cc.
View newest version in sPHENIX GitHub at line 182 of file G4tgrParameterMgr.cc
References G4cout, G4endl, and theParameterList.
Referenced by FindParameter().
G4String G4tgrParameterMgr::FindParameter (const G4String & name, G4bool exists = true)
Definition at line 149 of file G4tgrParameterMgr.cc.
View newest version in sPHENIX GitHub at line 149 of file G4tgrParameterMgr.cc
References DumpList(), FatalException, G4cout, G4endl, G4Exception(), G4tgrMessenger::GetVerboseLevel(), and theParameterList.
Referenced by G4tgrUtils::GetDouble(), and G4tgrUtils::GetString().
G4tgrParameterMgr * G4tgrParameterMgr::GetInstance (void) static
Definition at line 60 of file G4tgrParameterMgr.cc.
View newest version in sPHENIX GitHub at line 60 of file G4tgrParameterMgr.cc
References G4tgrParameterMgr(), and theInstance.
Referenced by G4tgrUtils::GetDouble(), G4tgrUtils::GetString(), and G4tgrLineProcessor::ProcessLine().
Member Data Documentation
G4ThreadLocal G4tgrParameterMgr * G4tgrParameterMgr::theInstance = 0 static private
Definition at line 83 of file G4tgrParameterMgr.hh.
View newest version in sPHENIX GitHub at line 83 of file G4tgrParameterMgr.hh
Referenced by GetInstance(), and ~G4tgrParameterMgr().
G4mapss G4tgrParameterMgr::theParameterList private
Definition at line 79 of file G4tgrParameterMgr.hh.
View newest version in sPHENIX GitHub at line 79 of file G4tgrParameterMgr.hh
Referenced by AddParameterNumber(), AddParameterString(), CheckIfNewParameter(), DumpList(), and FindParameter().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrParameterMgr.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrParameterMgr.cc