ECCE @ EIC Software: G4FieldTrack Class Reference
G4FieldTrack Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4FieldTrack.hh>
Public Types
enum { ncompSVEC = 12 }
Public Member Functions
G4FieldTrack (const G4ThreeVector &pPosition, G4double LaboratoryTimeOfFlight, const G4ThreeVector &pMomentumDirection, G4double kineticEnergy, G4double restMass_c2, G4double charge, const G4ThreeVector &polarization, G4double magnetic_dipole_moment=0.0, G4double curve_length=0.0, G4double PDGspin=-1.0)
G4FieldTrack (char)
G4FieldTrack (const G4ThreeVector &pPosition, const G4ThreeVector &pMomentumDirection, G4double curve_length, G4double kineticEnergy, const G4double restMass_c2, G4double velocity, G4double LaboratoryTimeOfFlight=0.0, G4double ProperTimeOfFlight=0.0, const G4ThreeVector *pPolarization=nullptr, G4double PDGspin=-1.0)
~G4FieldTrack ()
G4FieldTrack (const G4FieldTrack &pFieldTrack)
G4FieldTrack & operator= (const G4FieldTrack &rStVec)
void UpdateState (const G4ThreeVector &pPosition, G4double LaboratoryTimeOfFlight, const G4ThreeVector &pMomentumDirection, G4double kineticEnergy)
void UpdateFourMomentum (G4double kineticEnergy, const G4ThreeVector &momentumDirection)
void SetChargeAndMoments (G4double charge, G4double magnetic_dipole_moment=DBL_MAX, G4double electric_dipole_moment=DBL_MAX, G4double magnetic_charge=DBL_MAX)
void SetPDGSpin (G4double pdgSpin)
G4double GetPDGSpin ()
G4ThreeVector GetMomentum () const
G4ThreeVector GetPosition () const
const G4ThreeVector & GetMomentumDir () const
G4ThreeVector GetMomentumDirection () const
G4double GetCurveLength () const
G4ThreeVector GetPolarization () const
void SetPolarization (const G4ThreeVector &vecPol)
const G4ChargeState * GetChargeState () const
G4double GetLabTimeOfFlight () const
G4double GetProperTimeOfFlight () const
G4double GetKineticEnergy () const
G4double GetCharge () const
G4double GetRestMass () const
void SetPosition (G4ThreeVector nPos)
void SetMomentum (G4ThreeVector nMomDir)
void SetMomentumDir (G4ThreeVector nMomDir)
void SetRestMass (G4double Mass_c2)
void SetCurveLength (G4double nCurve_s)
void SetKineticEnergy (G4double nEnergy)
void SetLabTimeOfFlight (G4double tofLab)
void SetProperTimeOfFlight (G4double tofProper)
void DumpToArray (G4double valArr[ncompSVEC]) const
void LoadFromArray (const G4double valArr[ncompSVEC], G4int noVarsIntegrated)
void InitialiseSpin (const G4ThreeVector &vecPolarization)
G4ThreeVector GetSpin () const
void SetSpin (G4ThreeVector vSpin)
Private Member Functions
G4FieldTrack & SetCurvePnt (const G4ThreeVector &pPosition, const G4ThreeVector &pMomentum, G4double s_curve)
Private Attributes
G4double SixVector [6]
G4double fDistanceAlongCurve
G4double fKineticEnergy
G4double fRestMass_c2
G4double fLabTimeOfFlight
G4double fProperTimeOfFlight
G4ThreeVector fPolarization
G4ThreeVector fMomentumDir
G4ChargeState fChargeState
Friends
std::ostream & operator<< (std::ostream &os, const G4FieldTrack &SixVec)
Detailed Description
Definition at line 44 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 44 of file G4FieldTrack.hh
Member Enumeration Documentation
anonymous enum
Enumerator:
ncompSVEC
Definition at line 140 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 140 of file G4FieldTrack.hh
Constructor & Destructor Documentation
G4FieldTrack::G4FieldTrack (const G4ThreeVector & pPosition, G4double LaboratoryTimeOfFlight, const G4ThreeVector & pMomentumDirection, G4double kineticEnergy, G4double restMass_c2, G4double charge, const G4ThreeVector & polarization, G4double magnetic_dipole_moment = 0.0, G4double curve_length = 0.0, G4double PDGspin = -1.0)
Definition at line 81 of file G4FieldTrack.cc.
View newest version in sPHENIX GitHub at line 81 of file G4FieldTrack.cc
References SetPolarization(), SetPosition(), and UpdateFourMomentum().
G4FieldTrack::G4FieldTrack (char)
Definition at line 136 of file G4FieldTrack.cc.
View newest version in sPHENIX GitHub at line 136 of file G4FieldTrack.cc
References SetCurvePnt(), and SetPolarization().
G4FieldTrack::G4FieldTrack (const G4ThreeVector & pPosition, const G4ThreeVector & pMomentumDirection, G4double curve_length, G4double kineticEnergy, const G4double restMass_c2, G4double velocity, G4double LaboratoryTimeOfFlight = 0.0, G4double ProperTimeOfFlight = 0.0, const G4ThreeVector * pPolarization = nullptr, G4double PDGspin = -1.0)
Definition at line 108 of file G4FieldTrack.cc.
View newest version in sPHENIX GitHub at line 108 of file G4FieldTrack.cc
References fChargeState, G4ChargeState::SetPDGSpin(), SetPolarization(), SetPosition(), and UpdateFourMomentum().
G4FieldTrack::~G4FieldTrack ()
G4FieldTrack::G4FieldTrack (const G4FieldTrack & pFieldTrack) inline
Member Function Documentation
void G4FieldTrack::DumpToArray (G4double valArr[ncompSVEC]) const inline
Referenced by G4MagInt_Driver::AccurateAdvance(), G4MagInt_Driver::GetDerivatives(), and G4MagInt_Driver::QuickAdvance().
G4double G4FieldTrack::GetCharge () const inline
Referenced by G4PathFinder::ComputeStep().
const G4ChargeState* G4FieldTrack::GetChargeState () const inline
Referenced by G4PathFinder::DoNextCurvedStep().
G4double G4FieldTrack::GetCurveLength () const inline
Referenced by G4MagInt_Driver::AccurateAdvance(), G4ChordFinder::ApproxCurvePointS(), G4ChordFinder::ApproxCurvePointV(), G4VIntersectionLocator::CheckAndReEstimateEndpoint(), G4PropagatorInField::ComputeStep(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), operator<<(), G4MagInt_Driver::PrintStat_Aux(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), G4MagInt_Driver::PrintStatus(), G4MagInt_Driver::QuickAdvance(), G4VIntersectionLocator::ReEstimateEndpoint(), and G4VIntersectionLocator::ReportReversedPoints().
G4double G4FieldTrack::GetKineticEnergy () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), and G4MagInt_Driver::PrintStat_Aux().
G4double G4FieldTrack::GetLabTimeOfFlight () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4BFieldIntegrationDriver::GetFieldValue(), and G4MultiLevelLocator::ReportFieldValue().
G4ThreeVector G4FieldTrack::GetMomentum () const inline
Referenced by G4PropagatorInField::ComputeStep(), G4BFieldIntegrationDriver::CurvatureRadius(), G4PathFinder::DoNextCurvedStep(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), and G4FieldTrackUpdator::Update().
const G4ThreeVector& G4FieldTrack::GetMomentumDir () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4PropagatorInField::ComputeStep(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4MagInt_Driver::PrintStat_Aux(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), and G4MagInt_Driver::PrintStatus().
G4ThreeVector G4FieldTrack::GetMomentumDirection () const inline
Referenced by G4PathFinder::ComputeStep(), G4ITPathFinder::ComputeStep(), G4PathFinder::DoNextLinearStep(), G4ITPathFinder::DoNextLinearStep(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), and G4MultiLevelLocator::EstimateIntersectionPoint().
G4double G4FieldTrack::GetPDGSpin () inline
G4ThreeVector G4FieldTrack::GetPolarization () const inline
Referenced by operator<<().
G4ThreeVector G4FieldTrack::GetPosition () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ChordFinder::ApproxCurvePointS(), G4ChordFinder::ApproxCurvePointV(), G4VIntersectionLocator::CheckAndReEstimateEndpoint(), G4PropagatorInField::ComputeStep(), G4PathFinder::ComputeStep(), G4ITPathFinder::ComputeStep(), G4PathFinder::DoNextCurvedStep(), G4ITPathFinder::DoNextCurvedStep(), G4PathFinder::DoNextLinearStep(), G4ITPathFinder::DoNextLinearStep(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4BFieldIntegrationDriver::GetFieldValue(), G4PathFinder::Locate(), G4MagInt_Driver::PrintStat_Aux(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), G4MagInt_Driver::PrintStatus(), G4MagInt_Driver::QuickAdvance(), G4VIntersectionLocator::ReEstimateEndpoint(), G4PathFinder::ReLocate(), and G4MultiLevelLocator::ReportFieldValue().
G4double G4FieldTrack::GetProperTimeOfFlight () const inline
G4double G4FieldTrack::GetRestMass () const inline
Referenced by G4PathFinder::DoNextCurvedStep(), and G4MultiLevelLocator::EstimateIntersectionPoint().
G4ThreeVector G4FieldTrack::GetSpin () const inline
Referenced by G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), and G4CoupledTransportation::AlongStepGetPhysicalInteractionLength().
void G4FieldTrack::InitialiseSpin (const G4ThreeVector & vecPolarization) inline
void G4FieldTrack::LoadFromArray (const G4double valArr[ncompSVEC], G4int noVarsIntegrated)
Definition at line 175 of file G4FieldTrack.cc.
View newest version in sPHENIX GitHub at line 175 of file G4FieldTrack.cc
References fKineticEnergy, fLabTimeOfFlight, fMomentumDir, fProperTimeOfFlight, fRestMass_c2, CLHEP::Hep3Vector::mag2(), ncompSVEC, SetPolarization(), SixVector, and CLHEP::Hep3Vector::unit().
Referenced by G4MagInt_Driver::AccurateAdvance(), G4MagInt_Driver::PrintStatus(), and G4MagInt_Driver::QuickAdvance().
G4FieldTrack& G4FieldTrack::operator= (const G4FieldTrack & rStVec) inline
void G4FieldTrack::SetChargeAndMoments (G4double charge, G4double magnetic_dipole_moment = DBL_MAX, G4double electric_dipole_moment = DBL_MAX, G4double magnetic_charge = DBL_MAX)
Definition at line 148 of file G4FieldTrack.cc.
View newest version in sPHENIX GitHub at line 148 of file G4FieldTrack.cc
References fChargeState, and G4ChargeState::SetChargesAndMoments().
Referenced by G4FieldTrackUpdator::Update().
void G4FieldTrack::SetCurveLength (G4double nCurve_s) inline
Referenced by G4MagInt_Driver::AccurateAdvance(), G4MagInt_Driver::PrintStatus(), and G4MagInt_Driver::QuickAdvance().
G4FieldTrack& G4FieldTrack::SetCurvePnt (const G4ThreeVector & pPosition, const G4ThreeVector & pMomentum, G4double s_curve) inline private
Referenced by G4FieldTrack().
void G4FieldTrack::SetKineticEnergy (G4double nEnergy) inline
void G4FieldTrack::SetLabTimeOfFlight (G4double tofLab) inline
void G4FieldTrack::SetMomentum (G4ThreeVector nMomDir) inline
void G4FieldTrack::SetMomentumDir (G4ThreeVector nMomDir) inline
void G4FieldTrack::SetPDGSpin (G4double pdgSpin) inline
Referenced by G4FieldTrackUpdator::Update().
void G4FieldTrack::SetPolarization (const G4ThreeVector & vecPol) inline
Referenced by G4FieldTrack(), and LoadFromArray().
void G4FieldTrack::SetPosition (G4ThreeVector nPos) inline
Referenced by G4PathFinder::DoNextLinearStep(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), and G4FieldTrack().
void G4FieldTrack::SetProperTimeOfFlight (G4double tofProper) inline
Referenced by G4PathFinder::DoNextLinearStep(), and G4FieldTrackUpdator::Update().
void G4FieldTrack::SetRestMass (G4double Mass_c2) inline
Referenced by G4FieldTrackUpdator::Update().
void G4FieldTrack::SetSpin (G4ThreeVector vSpin) inline
Referenced by G4FieldTrackUpdator::Update().
void G4FieldTrack::UpdateFourMomentum (G4double kineticEnergy, const G4ThreeVector & momentumDirection) inline
Referenced by G4FieldTrack().
void G4FieldTrack::UpdateState (const G4ThreeVector & pPosition, G4double LaboratoryTimeOfFlight, const G4ThreeVector & pMomentumDirection, G4double kineticEnergy) inline
Referenced by G4FieldTrackUpdator::Update().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4FieldTrack & SixVec) friend
Definition at line 33 of file G4FieldTrack.cc.
View newest version in sPHENIX GitHub at line 33 of file G4FieldTrack.cc
Member Data Documentation
G4ChargeState G4FieldTrack::fChargeState private
Definition at line 173 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 173 of file G4FieldTrack.hh
Referenced by G4FieldTrack(), and SetChargeAndMoments().
G4double G4FieldTrack::fDistanceAlongCurve private
Definition at line 163 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 163 of file G4FieldTrack.hh
G4double G4FieldTrack::fKineticEnergy private
Definition at line 164 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 164 of file G4FieldTrack.hh
Referenced by LoadFromArray(), and operator<<().
G4double G4FieldTrack::fLabTimeOfFlight private
Definition at line 166 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 166 of file G4FieldTrack.hh
Referenced by LoadFromArray(), and operator<<().
G4ThreeVector G4FieldTrack::fMomentumDir private
Definition at line 169 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 169 of file G4FieldTrack.hh
Referenced by LoadFromArray(), and operator<<().
G4ThreeVector G4FieldTrack::fPolarization private
Definition at line 168 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 168 of file G4FieldTrack.hh
G4double G4FieldTrack::fProperTimeOfFlight private
Definition at line 167 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 167 of file G4FieldTrack.hh
Referenced by LoadFromArray(), and operator<<().
G4double G4FieldTrack::fRestMass_c2 private
Definition at line 165 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 165 of file G4FieldTrack.hh
Referenced by LoadFromArray(), and operator<<().
G4double G4FieldTrack::SixVector[6] private
Definition at line 162 of file G4FieldTrack.hh.
View newest version in sPHENIX GitHub at line 162 of file G4FieldTrack.hh
Referenced by LoadFromArray(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4FieldTrack.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4FieldTrack.cc