ECCE @ EIC Software: DicomBeamDevice Class Reference
DicomBeamDevice Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomBeamDevice.hh>
Public Member Functions
DicomBeamDevice (DRTBeamLimitingDeviceSequenceInRTBeamsModule::Item bldsItem)
DicomBeamDevice (DRTBeamLimitingDevicePositionSequence::Item bldpsItem)
~DicomBeamDevice ()
void SetSourceToBeamLimitingDeviceDistance (Float64 dat)
Float64 GetSourceToBeamLimitingDeviceDistance () const
void SetNumberOfLeafJawPairs (Sint32 dat)
Sint32 GetNumberOfLeafJawPairs () const
void SetType (OFString dat)
OFString GetType () const
void AddPositionBoundary (Float64 dat)
Float64 GetPositionBoundary (size_t ii)
void Print (std::ostream &out)
Private Attributes
OFString theType
Float64 theSourceToBeamLimitingDeviceDistance
Sint32 theNumberOfLeafJawPairs
std::vector< Float64 > thePositionBoundaries
Detailed Description
Definition at line 39 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 39 of file DicomBeamDevice.hh
Constructor & Destructor Documentation
DicomBeamDevice::DicomBeamDevice (DRTBeamLimitingDeviceSequenceInRTBeamsModule::Item bldsItem)
Definition at line 31 of file DicomBeamDevice.cc.
View newest version in sPHENIX GitHub at line 31 of file DicomBeamDevice.cc
References AddPositionBoundary(), G4cout, G4endl, SetNumberOfLeafJawPairs(), SetSourceToBeamLimitingDeviceDistance(), and SetType().
DicomBeamDevice::DicomBeamDevice (DRTBeamLimitingDevicePositionSequence::Item bldpsItem)
Definition at line 56 of file DicomBeamDevice.cc.
View newest version in sPHENIX GitHub at line 56 of file DicomBeamDevice.cc
References AddPositionBoundary(), G4cout, G4endl, and SetType().
DicomBeamDevice::~DicomBeamDevice () inline
Definition at line 44 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 44 of file DicomBeamDevice.hh
Member Function Documentation
void DicomBeamDevice::AddPositionBoundary (Float64 dat) inline
Definition at line 65 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 65 of file DicomBeamDevice.hh
References thePositionBoundaries.
Referenced by DicomBeamDevice().
Sint32 DicomBeamDevice::GetNumberOfLeafJawPairs () const inline
Definition at line 56 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 56 of file DicomBeamDevice.hh
References theNumberOfLeafJawPairs.
Float64 DicomBeamDevice::GetPositionBoundary (size_t ii) inline
Definition at line 68 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 68 of file DicomBeamDevice.hh
References thePositionBoundaries.
Float64 DicomBeamDevice::GetSourceToBeamLimitingDeviceDistance () const inline
Definition at line 50 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 50 of file DicomBeamDevice.hh
References theSourceToBeamLimitingDeviceDistance.
OFString DicomBeamDevice::GetType () const inline
Definition at line 62 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 62 of file DicomBeamDevice.hh
References theType.
void DicomBeamDevice::Print (std::ostream & out)
Definition at line 75 of file DicomBeamDevice.cc.
View newest version in sPHENIX GitHub at line 75 of file DicomBeamDevice.cc
void DicomBeamDevice::SetNumberOfLeafJawPairs (Sint32 dat) inline
Definition at line 53 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 53 of file DicomBeamDevice.hh
References theNumberOfLeafJawPairs.
Referenced by DicomBeamDevice().
void DicomBeamDevice::SetSourceToBeamLimitingDeviceDistance (Float64 dat) inline
Definition at line 47 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 47 of file DicomBeamDevice.hh
References theSourceToBeamLimitingDeviceDistance.
Referenced by DicomBeamDevice().
void DicomBeamDevice::SetType (OFString dat) inline
Definition at line 59 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 59 of file DicomBeamDevice.hh
References theType.
Referenced by DicomBeamDevice().
Member Data Documentation
Sint32 DicomBeamDevice::theNumberOfLeafJawPairs private
Definition at line 76 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 76 of file DicomBeamDevice.hh
Referenced by GetNumberOfLeafJawPairs(), and SetNumberOfLeafJawPairs().
std::vector<Float64> DicomBeamDevice::thePositionBoundaries private
Definition at line 77 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 77 of file DicomBeamDevice.hh
Referenced by AddPositionBoundary(), and GetPositionBoundary().
Float64 DicomBeamDevice::theSourceToBeamLimitingDeviceDistance private
Definition at line 75 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 75 of file DicomBeamDevice.hh
Referenced by GetSourceToBeamLimitingDeviceDistance(), and SetSourceToBeamLimitingDeviceDistance().
OFString DicomBeamDevice::theType private
Definition at line 74 of file DicomBeamDevice.hh.
View newest version in sPHENIX GitHub at line 74 of file DicomBeamDevice.hh
Referenced by GetType(), and SetType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomBeamDevice.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/src/DicomBeamDevice.cc