ECCE @ EIC Software: CLHEP::Hep3Vector Class Reference
CLHEP::Hep3Vector Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/ThreeVector.h>
Public Types
enum {
X =0, Y =1, Z =2, NUM_COORDINATES =3,
SIZE =NUM_COORDINATES
}
enum { ToleranceTicks = 100 }
Public Member Functions
Hep3Vector ()
Hep3Vector (double x)
Hep3Vector (double x, double y)
Hep3Vector (double x, double y, double z)
Hep3Vector (const Hep3Vector &)
Hep3Vector (Hep3Vector &&)=default
~Hep3Vector ()
double operator() (int) const
double operator[] (int) const
double & operator() (int)
double & operator[] (int)
double x () const
double y () const
double z () const
void setX (double)
void setY (double)
void setZ (double)
void set (double x, double y, double z)
double phi () const
double theta () const
double cosTheta () const
double cos2Theta () const
double mag2 () const
double mag () const
void setPhi (double)
void setTheta (double)
void setMag (double)
double perp2 () const
double perp () const
void setPerp (double)
void setCylTheta (double)
double perp2 (const Hep3Vector &) const
double perp (const Hep3Vector &) const
Hep3Vector & operator= (const Hep3Vector &)
Hep3Vector & operator= (Hep3Vector &&)=default
bool operator== (const Hep3Vector &) const
bool operator!= (const Hep3Vector &) const
bool isNear (const Hep3Vector &, double epsilon=tolerance) const
double howNear (const Hep3Vector &v) const
double deltaR (const Hep3Vector &v) const
Hep3Vector & operator+= (const Hep3Vector &)
Hep3Vector & operator-= (const Hep3Vector &)
Hep3Vector operator- () const
Hep3Vector & operator*= (double)
Hep3Vector & operator/= (double)
Hep3Vector unit () const
Hep3Vector orthogonal () const
double dot (const Hep3Vector &) const
Hep3Vector cross (const Hep3Vector &) const
double angle (const Hep3Vector &) const
double pseudoRapidity () const
void setEta (double p)
void setCylEta (double p)
Hep3Vector & rotateX (double)
Hep3Vector & rotateY (double)
Hep3Vector & rotateZ (double)
Hep3Vector & rotateUz (const Hep3Vector &)
Hep3Vector & rotate (double, const Hep3Vector &)
Hep3Vector & operator*= (const HepRotation &)
Hep3Vector & transform (const HepRotation &)
void setRThetaPhi (double r, double theta, double phi)
void setREtaPhi (double r, double eta, double phi)
void setRhoPhiZ (double rho, double phi, double z)
void setRhoPhiTheta (double rho, double phi, double theta)
void setRhoPhiEta (double rho, double phi, double eta)
double getX () const
double getY () const
double getZ () const
double getR () const
double getTheta () const
double getPhi () const
double r () const
double rho () const
double getRho () const
double eta () const
double getEta () const
void setR (double s)
void setRho (double s)
int compare (const Hep3Vector &v) const
bool operator> (const Hep3Vector &v) const
bool operator< (const Hep3Vector &v) const
bool operator>= (const Hep3Vector &v) const
bool operator<= (const Hep3Vector &v) const
double diff2 (const Hep3Vector &v) const
bool isParallel (const Hep3Vector &v, double epsilon=tolerance) const
bool isOrthogonal (const Hep3Vector &v, double epsilon=tolerance) const
double howParallel (const Hep3Vector &v) const
double howOrthogonal (const Hep3Vector &v) const
double beta () const
double gamma () const
double coLinearRapidity () const
double angle () const
double theta (const Hep3Vector &v2) const
double cosTheta (const Hep3Vector &v2) const
double cos2Theta (const Hep3Vector &v2) const
Hep3Vector project () const
Hep3Vector project (const Hep3Vector &v2) const
Hep3Vector perpPart () const
Hep3Vector perpPart (const Hep3Vector &v2) const
double rapidity () const
double rapidity (const Hep3Vector &v2) const
double eta (const Hep3Vector &v2) const
double polarAngle (const Hep3Vector &v2) const
double deltaPhi (const Hep3Vector &v2) const
double azimAngle (const Hep3Vector &v2) const
double polarAngle (const Hep3Vector &v2, const Hep3Vector &ref) const
double azimAngle (const Hep3Vector &v2, const Hep3Vector &ref) const
Hep3Vector & rotate (const Hep3Vector &axis, double delta)
Hep3Vector & rotate (const HepAxisAngle &ax)
Hep3Vector & rotate (const HepEulerAngles &e)
Hep3Vector & rotate (double phi, double theta, double psi)
Static Public Member Functions
static double setTolerance (double tol)
static double getTolerance ()
Protected Member Functions
void setSpherical (double r, double theta, double phi)
void setCylindrical (double r, double phi, double z)
double negativeInfinity () const
Protected Attributes
double dx
double dy
double dz
Static Protected Attributes
static DLL_API double tolerance = Hep3Vector::ToleranceTicks * 2.22045e-16
Detailed Description
Author
Definition at line 40 of file ThreeVector.h.
View newest version in sPHENIX GitHub at line 40 of file ThreeVector.h
Member Enumeration Documentation
anonymous enum
Enumerator:
X
Y
Z
NUM_COORDINATES
SIZE
Definition at line 46 of file ThreeVector.h.
View newest version in sPHENIX GitHub at line 46 of file ThreeVector.h
anonymous enum
Enumerator:
ToleranceTicks
Definition at line 299 of file ThreeVector.h.
View newest version in sPHENIX GitHub at line 299 of file ThreeVector.h
Constructor & Destructor Documentation
CLHEP::Hep3Vector::Hep3Vector ()
CLHEP::Hep3Vector::Hep3Vector (double x) explicit
CLHEP::Hep3Vector::Hep3Vector (double x, double y)
CLHEP::Hep3Vector::Hep3Vector (double x, double y, double z)
CLHEP::Hep3Vector::Hep3Vector (const Hep3Vector &) inline
CLHEP::Hep3Vector::Hep3Vector (Hep3Vector &&) inline default
CLHEP::Hep3Vector::~Hep3Vector () inline
Member Function Documentation
double CLHEP::Hep3Vector::angle (const Hep3Vector &) const
Referenced by azimAngle(), G4EmBiasingManager::CheckDirection(), G4NucleiModel::choosePointAlongTraj(), G4OpBoundaryProcess::DielectricDichroic(), G4OpBoundaryProcess::DielectricLUT(), G4OpBoundaryProcess::DielectricLUTDAVIS(), RE05StackingAction::InsideRoI(), ExN04StackingAction::InsideRoI(), ExN04StackingAction::NewStage(), RE05StackingAction::NewStage(), polarAngle(), G4UCNBoundaryProcess::PostStepDoIt(), getVectors::process_event(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), CexmcReconstructor::ReconstructAngle(), and G4AdjointBremsstrahlungModel::SampleSecondaries().
double CLHEP::Hep3Vector::angle () const inline
Referenced by polarAngle().
double CLHEP::Hep3Vector::azimAngle (const Hep3Vector & v2) const
double CLHEP::Hep3Vector::azimAngle (const Hep3Vector & v2, const Hep3Vector & ref) const
Definition at line 40 of file SpaceVectorD.cc.
View newest version in sPHENIX GitHub at line 40 of file SpaceVectorD.cc
References angle(), cross(), dot(), mag2(), and perpPart().
double CLHEP::Hep3Vector::beta () const
Definition at line 30 of file SpaceVectorP.cc.
View newest version in sPHENIX GitHub at line 30 of file SpaceVectorP.cc
References b, and mag2().
Referenced by G4QMDReaction::ApplyYourself(), coLinearRapidity(), CLHEP::HepRotationZ::distance2(), CLHEP::HepRotationY::distance2(), CLHEP::HepRotationX::distance2(), and CLHEP::HepRotation::distance2().
double CLHEP::Hep3Vector::coLinearRapidity () const
Definition at line 69 of file SpaceVectorP.cc.
View newest version in sPHENIX GitHub at line 69 of file SpaceVectorP.cc
References b, and beta().
int CLHEP::Hep3Vector::compare (const Hep3Vector & v) const
Definition at line 122 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 122 of file SpaceVector.cc
References dx, dy, and dz.
Referenced by CLHEP::HepLorentzVector::compare(), operator<(), operator<=(), operator>(), and operator>=().
double CLHEP::Hep3Vector::cos2Theta () const inline
double CLHEP::Hep3Vector::cos2Theta (const Hep3Vector & v2) const
Definition at line 166 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 166 of file ThreeVector.cc
References dot(), and mag2().
double CLHEP::Hep3Vector::cosTheta () const inline
Referenced by G4BetheHeitler5DModel::SampleSecondaries(), and G4PenelopeBremsstrahlungModel::SampleSecondaries().
double CLHEP::Hep3Vector::cosTheta (const Hep3Vector & v2) const
Definition at line 153 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 153 of file ThreeVector.cc
References dot(), and mag2().
Hep3Vector CLHEP::Hep3Vector::cross (const Hep3Vector &) const inline
Referenced by G4MagHelicalStepper::AdvanceHelix(), G4VTwistSurface::AmIOnLeftSide(), azimAngle(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4PolyconeSide::CalculateExtent(), G4OpBoundaryProcess::CalculateReflectivity(), GFlashShowerModel::CheckContainment(), G4EmBiasingManager::CheckDirection(), G4NucleiModel::choosePointAlongTraj(), G4tgbVolume::ConstructG4PhysVol(), G4Tet::CreatePolyhedron(), G4SPSAngDistribution::DefineAngRefAxes(), G4OpBoundaryProcess::DielectricDielectric(), G4OpBoundaryProcess::DielectricLUT(), G4OpBoundaryProcess::DielectricLUTDAVIS(), G4OpBoundaryProcess::DielectricMetal(), GFlashShowerModel::ElectronDoIt(), ExGflashEventAction::EndOfEventAction(), G4EqEMFieldWithSpin::EvaluateRhsGivenB(), G4RepleteEofM::EvaluateRhsGivenB(), G4EqEMFieldWithEDM::EvaluateRhsGivenB(), G4Mag_SpinEqRhs::EvaluateRhsGivenB(), Par01PionShowerModel::Explode(), Par01EMShowerModel::Explode(), G4gsrotm(), G4PlaneVectorRand(), G4PolyhedraSide::G4PolyhedraSide(), G4QuadrangularFacet::G4QuadrangularFacet(), G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4TriangularFacet::G4TriangularFacet(), PHHepMCGenHelper::generate_vertx_with_bunch_interaction(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), G4SPSPosDistribution::GenerateRotationMatrices(), G4PrimaryTransformer::GenerateSingleTrack(), G4PolarizationHelper::GetFrame(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4LivermorePolarizedRayleighModel::GetPhotonPolarization(), G4Para::GetPointOnSurface(), G4LivermorePolarizedComptonModel::GetRandomPolarization(), G4LivermorePolarizedGammaConversionModel::GetRandomPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetRandomPolarization(), G4LowEnergyPolarizedCompton::GetRandomPolarization(), G4LowEPPolarizedComptonModel::GetRandomPolarization(), G4BinaryCascade::GetSpherePoint(), G4Para::GetSurfaceArea(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), howOrthogonal(), howParallel(), G4TriangularFacet::Intersect(), G4PolyhedraSide::Intersect(), G4PolyhedraSide::IntersectSidePlane(), G4StokesVector::InvRotateAz(), isOrthogonal(), isParallel(), G4GenericTrap::IsSegCrossingZ(), G4QMDGroundStateNucleus::killCMMotionAndAngularM(), G4Para::MakePlanes(), G4GenericTrap::NormalToPlane(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4PolyconeSide::PointOnCone(), G4GeomTools::PolygonAreaNormal(), G4SynchrotronRadiation::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), QAG4SimulationCalorimeter::process_event_Cluster(), G4ErrorFreeTrajState::PropagateError(), G4QuasiElRatios::RelDecayIn2(), G4LorentzConvertor::rotate(), G4RPGReaction::Rotate(), CLHEP::HepRotation::rotateAxes(), G4StokesVector::RotateAz(), G4StatMFChannel::RotateMomentum(), G4DNAUeharaScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAChampionElasticModel::SampleSecondaries(), G4DNAELSEPAElasticModel::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), CLHEP::HepRotation::setArbitrarily(), CLHEP::HepRotation::setCols(), OpNovicePrimaryGeneratorAction::SetOptPhotonPolar(), PrimaryGeneratorAction::SetOptPhotonPolar(), WLSPrimaryGeneratorAction::SetOptPhotonPolar(), G4ErrorSurfaceTrajParam::SetParameters(), G4GenericTrap::SurfaceNormal(), G4LivermorePolarizedGammaConversionModel::SystemOfRefChange(), G4LivermorePolarizedComptonModel::SystemOfRefChange(), G4LivermorePolarizedPhotoElectricGDModel::SystemOfRefChange(), G4LowEnergyPolarizedCompton::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChangeElect(), G4PolarizationHelper::TestPolarizationTransformations(), and FCALSteppingAction::UserSteppingAction().
double CLHEP::Hep3Vector::deltaPhi (const Hep3Vector & v2) const
Definition at line 137 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 137 of file ThreeVector.cc
References getPhi(), CLHEP::pi, and CLHEP::twopi.
Referenced by deltaR(), and CLHEP::HepLorentzVector::deltaR().
double CLHEP::Hep3Vector::deltaR (const Hep3Vector & v) const
Definition at line 147 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 147 of file ThreeVector.cc
References a, b, deltaPhi(), and eta().
double CLHEP::Hep3Vector::diff2 (const Hep3Vector & v) const inline
Referenced by G4QMDGroundStateNucleus::samplingMomentum().
double CLHEP::Hep3Vector::dot (const Hep3Vector &) const inline
Referenced by G4VIntersectionLocator::AdjustmentOfFoundIntersection(), G4MagHelicalStepper::AdvanceHelix(), G4Tet::ApproxSurfaceNormal(), azimAngle(), CLHEP::HepLorentzVector::boost(), G4NucleiModel::boundaryTransition(), G4GeomTools::ClosestPointOnSegment(), G4GeomTools::ClosestPointOnTriangle(), G4ParameterisedNavigation::ComputeStep(), G4NormalNavigation::ComputeStep(), G4VoxelNavigation::ComputeStep(), G4ReplicaNavigation::ComputeStep(), cos2Theta(), cosTheta(), G4Tet::CreatePolyhedron(), G4LineSection::Dist(), G4QuadrangularFacet::Distance(), G4TriangularFacet::Distance(), G4PolyPhiFace::Distance(), G4PolyhedraSide::Distance(), G4PolyhedraSide::DistanceAway(), G4GeomTools::DistancePointSegment(), G4Orb::DistanceToIn(), G4GenericTrap::DistanceToIn(), G4Tet::DistanceToIn(), G4CutTubs::DistanceToIn(), G4Cons::DistanceToIn(), G4PolyhedraSide::DistanceToOneSide(), G4Orb::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4GenericTrap::DistanceToOut(), G4Hype::DistanceToOut(), G4Tet::DistanceToOut(), G4CutTubs::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4Cons::DistanceToOut(), G4GenericTrap::DistToPlane(), G4GenericTrap::DistToTriangle(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4VSolid::EstimateSurfaceArea(), eta(), G4QuadrangularFacet::Extent(), G4TriangularFacet::Extent(), G4PolyconeSide::Extent(), G4PolyhedraSide::Extent(), G4LorentzConvertor::fillKinematics(), G4PolyhedraSide::G4PolyhedraSide(), G4QuadrangularFacet::G4QuadrangularFacet(), G4TriangularFacet::G4TriangularFacet(), PHHepMCGenHelper::generate_vertx_with_bunch_interaction(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), G4TessellatedSolid::GetCubicVolume(), G4MultiNavigator::GetGlobalExitNormal(), G4ITMultiNavigator::GetGlobalExitNormal(), G4CascadParticle::getPathToTheNextZone(), G4LivermorePolarizedGammaConversionModel::GetPerpendicularPolarization(), G4LivermorePolarizedComptonModel::GetPerpendicularPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetPerpendicularPolarization(), G4LowEnergyPolarizedCompton::GetPerpendicularPolarization(), G4LowEPPolarizedComptonModel::GetPerpendicularPolarization(), G4ClippablePolygon::GetPlanerExtent(), G4RKPropagation::GetSphereIntersectionTimes(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), howNear(), CLHEP::HepLorentzVector::howNear(), CLHEP::HepLorentzVector::howNearCM(), howOrthogonal(), howParallel(), G4Tet::Initialize(), G4NucleiModel::initializeCascad(), G4Tet::Inside(), G4PolyPhiFace::Inside(), G4TessellatedSolid::InsideNoVoxels(), G4TessellatedSolid::InsideVoxels(), G4TriangularFacet::Intersect(), G4PolyPhiFace::Intersect(), G4PolyhedraSide::Intersect(), G4PolyhedraSide::IntersectSidePlane(), G4VFacet::IsInside(), isNear(), CLHEP::HepLorentzVector::isNear(), CLHEP::HepLorentzVector::isNearCM(), isOrthogonal(), isParallel(), G4GenericTrap::IsSegCrossingZ(), G4Navigator::LocateGlobalPointAndSetup(), G4ITNavigator1::LocateGlobalPointAndSetup(), G4ITNavigator2::LocateGlobalPointAndSetup(), G4GHEKinematicsVector::Lor(), G4Trap::MakePlane(), G4Trap::MakePlanes(), CLHEP::HepLorentzVector::minus(), G4PolyPhiFace::Normal(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), CLHEP::HepLorentzVector::plus(), G4PolyconeSide::PointOnCone(), G4OpMieHG::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4MagInt_Driver::PrintStatus(), QAG4SimulationCalorimeter::process_event_Cluster(), project(), rapidity(), CLHEP::HepLorentzVector::rapidity(), G4VIntersectionLocator::ReportTrialStep(), G4LorentzConvertor::rotate(), G4RPGReaction::Rotate(), CLHEP::HepRotation::rotateAxes(), G4BetheHeitler5DModel::SampleSecondaries(), CLHEP::HepRotation::set(), CLHEP::HepRotation::setCols(), G4ErrorFreeTrajParam::SetParameters(), and G4ErrorSurfaceTrajParam::SetParameters().
double CLHEP::Hep3Vector::eta () const
Referenced by deltaR().
double CLHEP::Hep3Vector::eta (const Hep3Vector & v2) const
Definition at line 117 of file SpaceVectorP.cc.
View newest version in sPHENIX GitHub at line 117 of file SpaceVectorP.cc
References c, dot(), getR(), mag(), negativeInfinity(), and r1.
double CLHEP::Hep3Vector::gamma () const
Definition at line 39 of file SpaceVectorP.cc.
View newest version in sPHENIX GitHub at line 39 of file SpaceVectorP.cc
References mag2().
Referenced by G4QMDReaction::calcOffSetOfCollision().
double CLHEP::Hep3Vector::getEta () const
double CLHEP::Hep3Vector::getPhi () const inline
Referenced by deltaPhi(), G4StokesVector::GetBeta(), G4LatticeLogical::MapKtoV(), G4LatticeLogical::MapKtoVDir(), CaloCalibEmc_Pi0::process_event(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), setCylEta(), setCylTheta(), and setEta().
double CLHEP::Hep3Vector::getR () const inline
Referenced by DNAParser::CreateCutSolid(), eta(), G4SynchrotronRadiation::GetMeanFreePath(), and setEta().
double CLHEP::Hep3Vector::getRho () const inline
Referenced by G4VTwistSurface::DistanceToBoundary(), G4TwistTubsHypeSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsFlatSide::GetAreaCode(), G4TwistTubsHypeSide::Inside(), G4TwistedTubs::Inside(), setCylEta(), and setCylTheta().
double CLHEP::Hep3Vector::getTheta () const inline
Referenced by G4LatticeLogical::MapKtoV(), G4LatticeLogical::MapKtoVDir(), and polarAngle().
static double CLHEP::Hep3Vector::getTolerance () inline static
Referenced by PHHepMCGenHelper::generate_vertx_with_bunch_interaction(), and PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation().
double CLHEP::Hep3Vector::getX () const inline
Referenced by CML2ExpVoxels::add(), CLHEP::HepLorentzVector::boostX(), PHG4mRICHDetector::build_sensor(), CML2Ph_BoxInBox::Construct(), CML2PhantomConstruction::Construct(), CML2Ph_FullWater::Construct(), CML2AcceleratorConstruction::Construct(), DNAParser::CreateCutSolid(), PHG4GDMLWriteSolids::CutTubeWrite(), G4GDMLWriteSolids::CutTubeWrite(), G4FissionProductYieldDist::G4GetFission(), CML2PhantomConstruction::getCurrentTranslationString(), IORTDetectorConstruction::GetDetectorToPhantomPosition(), HadrontherapyDetectorConstruction::GetDetectorToPhantomPosition(), G4DecayProducts::IsChecked(), IORTDetectorConstruction::IsInside(), HadrontherapyDetectorConstruction::IsInside(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2Acc1::Jaw1Y(), CML2Acc2::Jaw1Y(), CML2Acc1::Jaw2X(), CML2Acc2::Jaw2X(), CML2Acc1::Jaw2Y(), CML2Acc2::Jaw2Y(), CML2ExpVoxels::loadData(), CML2Acc1::MLC(), CML2Acc2::MLC(), IORTDetectorConstruction::PrintParameters(), HadrontherapyDetectorConstruction::PrintParameters(), STCyclotronSensitiveTarget::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), rotate(), G4LundStringFragmentation::Sample4Momentum(), G4DNAPTBIonisationModel::SampleSecondaries(), CLHEP::HepRotation::set(), IORTDetectorConstruction::SetDetectorPosition(), HadrontherapyDetectorConstruction::SetDetectorPosition(), CML2Acc1::SetJawAperture(), CML2Acc2::SetJawAperture(), CML2AccSaturn::SetJawAperture(), HadrontherapyDetectorMessenger::SetNewValue(), IORTDetectorMessenger::SetNewValue(), CML2CInputData::setPhaseSpaceCentre(), CML2CInputData::setPhaseSpaceHalfSize(), G4LivermorePolarizedGammaConversionModel::SystemOfRefChange(), G4LivermorePolarizedComptonModel::SystemOfRefChange(), G4LivermorePolarizedPhotoElectricGDModel::SystemOfRefChange(), G4LowEnergyPolarizedCompton::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChangeElect(), CML2AccSaturn::target(), XAluminumElectrodeSensitivity::WriteHitInfo(), and CLHEP::ZMpvAxisAngleRep().
double CLHEP::Hep3Vector::getY () const inline
Referenced by CML2ExpVoxels::add(), CLHEP::HepLorentzVector::boostY(), CML2Ph_BoxInBox::Construct(), CML2PhantomConstruction::Construct(), CML2Ph_FullWater::Construct(), CML2AcceleratorConstruction::Construct(), DNAParser::CreateCutSolid(), PHG4GDMLWriteSolids::CutTubeWrite(), G4GDMLWriteSolids::CutTubeWrite(), G4FissionProductYieldDist::G4GetFission(), CML2PhantomConstruction::getCurrentTranslationString(), IORTDetectorConstruction::GetDetectorToPhantomPosition(), HadrontherapyDetectorConstruction::GetDetectorToPhantomPosition(), G4DecayProducts::IsChecked(), IORTDetectorConstruction::IsInside(), HadrontherapyDetectorConstruction::IsInside(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2Acc1::Jaw1Y(), CML2Acc2::Jaw1Y(), CML2Acc1::Jaw2X(), CML2Acc2::Jaw2X(), CML2Acc1::Jaw2Y(), CML2Acc2::Jaw2Y(), CML2ExpVoxels::loadData(), CML2Acc1::MLC(), CML2Acc2::MLC(), IORTDetectorConstruction::PrintParameters(), HadrontherapyDetectorConstruction::PrintParameters(), STCyclotronSensitiveTarget::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), rotate(), G4LundStringFragmentation::Sample4Momentum(), G4DNAPTBIonisationModel::SampleSecondaries(), CLHEP::HepRotation::set(), IORTDetectorConstruction::SetDetectorPosition(), HadrontherapyDetectorConstruction::SetDetectorPosition(), CML2Acc1::SetJawAperture(), CML2Acc2::SetJawAperture(), CML2AccSaturn::SetJawAperture(), HadrontherapyDetectorMessenger::SetNewValue(), IORTDetectorMessenger::SetNewValue(), CML2CInputData::setPhaseSpaceCentre(), CML2CInputData::setPhaseSpaceHalfSize(), G4LivermorePolarizedGammaConversionModel::SystemOfRefChange(), G4LivermorePolarizedComptonModel::SystemOfRefChange(), G4LivermorePolarizedPhotoElectricGDModel::SystemOfRefChange(), G4LowEnergyPolarizedCompton::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChangeElect(), CML2AccSaturn::target(), XAluminumElectrodeSensitivity::WriteHitInfo(), and CLHEP::ZMpvAxisAngleRep().
double CLHEP::Hep3Vector::getZ () const inline
Referenced by CML2ExpVoxels::add(), CLHEP::HepLorentzVector::boostZ(), CML2Ph_BoxInBox::Construct(), CML2PhantomConstruction::Construct(), CML2Ph_FullWater::Construct(), CML2AcceleratorConstruction::Construct(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), DNAParser::CreateCutSolid(), PHG4GDMLWriteSolids::CutTubeWrite(), G4GDMLWriteSolids::CutTubeWrite(), G4FissionProductYieldDist::G4GetFission(), CML2PhantomConstruction::getCurrentTranslationString(), IORTDetectorConstruction::GetDetectorToPhantomPosition(), HadrontherapyDetectorConstruction::GetDetectorToPhantomPosition(), G4DecayProducts::IsChecked(), IORTDetectorConstruction::IsInside(), HadrontherapyDetectorConstruction::IsInside(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2Acc1::Jaw1Y(), CML2Acc2::Jaw1Y(), CML2Acc1::Jaw2X(), CML2Acc2::Jaw2X(), CML2Acc1::Jaw2Y(), CML2Acc2::Jaw2Y(), CML2ExpVoxels::loadData(), CML2Acc1::MLC(), CML2Acc2::MLC(), IORTDetectorConstruction::PrintParameters(), HadrontherapyDetectorConstruction::PrintParameters(), STCyclotronSensitiveTarget::ProcessHits(), STCyclotronSensitiveFoil::ProcessHits(), CLHEP::HepLorentzVector::rapidity(), rotate(), G4DNAPTBIonisationModel::SampleSecondaries(), CLHEP::HepRotation::set(), IORTDetectorConstruction::SetDetectorPosition(), HadrontherapyDetectorConstruction::SetDetectorPosition(), CML2Acc1::SetJawAperture(), CML2Acc2::SetJawAperture(), CML2AccSaturn::SetJawAperture(), HadrontherapyDetectorMessenger::SetNewValue(), IORTDetectorMessenger::SetNewValue(), CML2CInputData::setPhaseSpaceCentre(), CML2CInputData::setPhaseSpaceHalfSize(), G4LivermorePolarizedGammaConversionModel::SystemOfRefChange(), G4LivermorePolarizedComptonModel::SystemOfRefChange(), G4LivermorePolarizedPhotoElectricGDModel::SystemOfRefChange(), G4LowEnergyPolarizedCompton::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChangeElect(), CML2AccSaturn::target(), XAluminumElectrodeSensitivity::WriteHitInfo(), and CLHEP::ZMpvAxisAngleRep().
double CLHEP::Hep3Vector::howNear (const Hep3Vector & v) const
Definition at line 124 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 124 of file ThreeVector.cc
References d, dot(), mag2(), and v.
double CLHEP::Hep3Vector::howOrthogonal (const Hep3Vector & v) const
Definition at line 219 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 219 of file SpaceVector.cc
References cross(), dot(), and mag().
Referenced by G4LivermorePolarizedRayleighModel::GetPhotonPolarization(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
double CLHEP::Hep3Vector::howParallel (const Hep3Vector & v) const
Definition at line 168 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 168 of file SpaceVector.cc
References cross(), dot(), mag(), and mag2().
bool CLHEP::Hep3Vector::isNear (const Hep3Vector & v, double epsilon = tolerance) const
Definition at line 119 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 119 of file ThreeVector.cc
References dot(), epsilon(), and mag2().
bool CLHEP::Hep3Vector::isOrthogonal (const Hep3Vector & v, double epsilon = tolerance) const
Definition at line 237 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 237 of file SpaceVector.cc
References cross(), dot(), dx, dy, dz, mag2(), x2, and y2.
Referenced by G4LivermorePolarizedRayleighModel::GetPhotonPolarization(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), and G4LowEPPolarizedComptonModel::SampleSecondaries().
bool CLHEP::Hep3Vector::isParallel (const Hep3Vector & v, double epsilon = tolerance) const
Definition at line 184 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 184 of file SpaceVector.cc
References cross(), dot(), dx, dy, dz, mag2(), and x2.
double CLHEP::Hep3Vector::mag () const inline
Referenced by G4ParticleHPFinalState::adjust_final_state(), G4MagHelicalStepper::AdvanceHelix(), G4BinaryLightIonReaction::ApplyYourself(), G4RPGNeutronInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGAntiLambdaInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiNeutronInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGAntiXiZeroInelastic::ApplyYourself(), G4RPGKZeroInelastic::ApplyYourself(), G4RPGLambdaInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4RPGAntiKZeroInelastic::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4ChordFinder::ApproxCurvePointV(), G4ParticleHPInelasticBaseFS::BaseApply(), G4NucleiModel::boundaryTransition(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4RPGInelastic::CalculateMomenta(), G4OpBoundaryProcess::CalculateReflectivity(), G4QMDCollision::CalKinematicsOfBinaryCollisions(), G4BinaryCascade::Capture(), G4RPGAntiKZeroInelastic::Cascade(), G4EmBiasingManager::CheckDirection(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChange::CheckIt(), G4FastStep::CheckIt(), G4NucleiModel::choosePointAlongTraj(), G4EicDircStackingAction::ClassifyNewTrack(), CLHEP::HepLorentzVector::coLinearRapidity(), G4DNABrownianTransportation::ComputeStep(), RE01Trajectory::CreateAttValues(), F04Trajectory::CreateAttValues(), WLSTrajectory::CreateAttValues(), G4SmoothTrajectory::CreateAttValues(), G4Trajectory::CreateAttValues(), RE04Trajectory::CreateAttValues(), G4VPhononProcess::CreateSecondary(), G4DiffractiveExcitation::CreateStrings(), G4AdjointCrossSurfChecker::CrossingASphere(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4AblaInterface::DeExcite(), G4GHEKinematicsVector::Defs(), G4RPGReaction::Defs1(), G4GHEKinematicsVector::Defs1(), G4OpBoundaryProcess::DielectricDielectric(), G4OpBoundaryProcess::DielectricLUT(), G4OpBoundaryProcess::DielectricLUTDAVIS(), G4QuadrangularFacet::Distance(), G4TriangularFacet::Distance(), G4GeomTools::DistancePointSegment(), G4ScaledSolid::DistanceToIn(), G4EllipticalTube::DistanceToIn(), G4Orb::DistanceToIn(), G4ScaledSolid::DistanceToOut(), G4Orb::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4TwistTubsHypeSide::DistanceToSurface(), Par02FastSimModelHCal::DoIt(), Par02FastSimModelEMCal::DoIt(), Par02FastSimModelTracker::DoIt(), G4PathFinder::DoNextCurvedStep(), ExGflashEventAction::EndOfEventAction(), RMC01AnalysisManager::EndOfEventForForwardSimulation(), G4MultiLevelLocator::EstimateIntersectionPoint(), eta(), PHG4OuterHcalSteppingAction::FieldChecker(), G4BinaryCascade::FillVoidNucleusProducts(), G4NeutrinoNucleusModel::FinalMomentum(), G4StatMFChannel::FragmentsMomenta(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4FissionProductYieldDist::G4GetFission(), G4PolyhedraSide::G4PolyhedraSide(), G4QuadrangularFacet::G4QuadrangularFacet(), G4tgbPlaceParamCircle::G4tgbPlaceParamCircle(), G4tgbPlaceParamLinear::G4tgbPlaceParamLinear(), G4tgbPlaceParamSquare::G4tgbPlaceParamSquare(), G4TriangularFacet::G4TriangularFacet(), PHHepMCGenHelper::generate_vertx_with_bunch_interaction(), G4NucleiModel::generateInteractionPartners(), TSPrimaryGeneratorAction::GeneratePrimaries(), DicomPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), G4RKFieldIntegrator::GetAntiprotonPotential(), G4Nucleus::GetBiasedThermalNucleus(), G4ParticleHPFissionData::GetCrossSection(), G4ParticleHPCaptureData::GetCrossSection(), G4ParticleHPElasticData::GetCrossSection(), G4ParticleHPInelasticData::GetCrossSection(), G4NuclearShellModelDensity::GetDeriv(), G4NuclearFermiDensity::GetDeriv(), G4ErrorCylSurfaceTarget::GetDistanceFromPoint(), G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint(), G4IonsKoxCrossSection::GetElementCrossSection(), RawClusterUtility::GetET(), G4OpBoundaryProcess::GetFacetNormal(), G4SigmaPlusField::GetField(), G4KaonZeroField::GetField(), G4SigmaMinusField::GetField(), G4SigmaZeroField::GetField(), G4AntiProtonField::GetField(), G4KaonMinusField::GetField(), G4KaonPlusField::GetField(), G4PionPlusField::GetField(), G4PionZeroField::GetField(), G4PionMinusField::GetField(), G4NeutronField::GetField(), G4ProtonField::GetField(), G4BinaryCascade::GetFinalNucleusMomentum(), G4Navigator::GetGlobalExitNormal(), G4ITNavigator1::GetGlobalExitNormal(), G4ITNavigator2::GetGlobalExitNormal(), G4OpBoundaryProcess::GetIncidentAngle(), G4NuclNuclDiffuseElastic::GetInvCoulombElasticXsc(), G4DiffuseElastic::GetInvCoulombElasticXsc(), G4NuclNuclDiffuseElastic::GetInvElasticSumXsc(), G4DiffuseElastic::GetInvElasticSumXsc(), G4NuclNuclDiffuseElastic::GetInvElasticXsc(), G4DiffuseElastic::GetInvElasticXsc(), G4IonsShenCrossSection::GetIsoCrossSection(), G4RKFieldIntegrator::GetKaonPotential(), G4QGSParticipants::GetList(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4FermiMomentum::GetMomentum(), G4RKFieldIntegrator::GetNeutronPotential(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4LivermorePolarizedRayleighModel::GetPhotonPolarization(), G4RKFieldIntegrator::GetPionPotential(), G4Trd::GetPointOnSurface(), G4Trap::GetPointOnSurface(), G4RKFieldIntegrator::GetProtonPotential(), G4NuclearFermiDensity::GetRelativeDensity(), G4tgrUtils::GetRotationFromDirection(), G4Trap::GetSurfaceArea(), G4VIntersectionLocator::GetSurfaceNormal(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), howOrthogonal(), howParallel(), G4Tet::Initialize(), G4NucleiModel::initializeCascad(), G4TwistTubsHypeSide::Inside(), G4BinaryLightIonReaction::Interact(), G4TriangularFacet::Intersect(), G4ErrorCylSurfaceTarget::IntersectLocal(), G4DecayProducts::IsChecked(), G4GenericTrap::IsSegCrossingZ(), G4GHEKinematicsVector::Length(), CLHEP::HepLorentzVector::minus(), G4RPGReaction::MomentumCheck(), G4RPGReaction::NuclearReaction(), operator<<(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), CLHEP::HepLorentzVector::plus(), G4OpMieHG::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), G4AdjointTrackingAction::PostUserTrackingAction(), CLHEP::HepBoost::print(), G4BinaryCascade::PrintKTVector(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), ClusterIso::process_event(), CaloCalibEmc_Pi0::process_event(), QAG4SimulationCalorimeter::process_event_Cluster(), G4IntraNucleiCascader::processSecondary(), G4BinaryCascade::Propagate(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorIoni(), G4ErrorFreeTrajState::PropagateErrorMSC(), pseudoRapidity(), rapidity(), G4RPGTwoBody::ReactionStage(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), CexmcReconstructor::ReconstructEntryPoints(), CLHEP::HepBoost::rectify(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4Fancy3DNucleus::ReduceSum(), G4VIntersectionLocator::ReEstimateEndpoint(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4SafetyHelper::ReLocateWithinVolume(), G4PropagatorInField::ReportLoopingParticle(), G4TransportationLogger::ReportLoopingTrack(), G4CoupledTransportation::ReportMove(), G4PathFinder::ReportMove(), G4ITPathFinder::ReportMove(), G4VIntersectionLocator::ReportTrialStep(), G4LorentzConvertor::rotate(), G4RPGReaction::Rotate(), CLHEP::HepRotation::rotate(), rotate(), G4StokesVector::RotateAz(), G4AntiNuclElastic::SampleInvariantT(), G4NuclNuclDiffuseElastic::SampleInvariantT(), G4DiffuseElasticV2::SampleInvariantT(), G4DiffuseElastic::SampleInvariantT(), G4LEPTSIonisationModel::SampleSecondaries(), G4LivermorePolarizedPhotoElectricGDModel::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermorePolarizedGammaConversionModel::SampleSecondaries(), G4ePolarizedBremsstrahlungModel::SampleSecondaries(), G4PolarizedGammaConversionModel::SampleSecondaries(), G4PolarizedPEEffectModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4LowEPPolarizedComptonModel::SampleSecondaries(), G4TDNAOneStepThermalizationModel< MODEL >::SampleSecondaries(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), CLHEP::HepBoost::set(), G4Fragment::SetAngularMomentum(), G4ReactionProduct::SetDefinitionAndUpdateE(), G4GHEKinematicsVector::SetEnergyAndUpdate(), G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), setMag(), G4GHEKinematicsVector::SetMassAndUpdate(), G4HadFinalState::SetMomentumChange(), G4ParticleGun::SetParticleMomentum(), G4RPGInelastic::SetUpChange(), G4QMDSystem::ShowParticipants(), G4RPGNeutronInelastic::SlowNeutron(), G4StatMFChannel::SolveEqOfMotion(), G4BinaryCascade::StepParticlesOut(), G4HelixMixedStepper::Stepper(), G4ScaledSolid::SurfaceNormal(), G4Orb::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4PolarizationHelper::TestPolarizationTransformations(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4ParticleChangeForTransport::UpdateStepForAlongStep(), G4ParticleChange::UpdateStepForAlongStep(), and FCALSteppingAction::UserSteppingAction().
double CLHEP::Hep3Vector::mag2 () const inline
Referenced by G4GHEKinematicsVector::Add(), G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_beforeSampling(), G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), G4VMultipleScattering::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4MonopoleTransportation::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation::AlongStepGetPhysicalInteractionLength(), G4GHEKinematicsVector::Ang(), G4LMsdGenerator::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4DecayWithSpin::AtRestDoIt(), azimAngle(), G4ParticleHPInelasticBaseFS::BaseApply(), beta(), CLHEP::HepLorentzVector::beta(), CLHEP::HepLorentzVector::boost(), G4KineticTrackVector::BoostBeam(), CLHEP::HepLorentzVector::boostVector(), G4StatMF::BreakItUp(), G4BinaryCascade::BuildTargetList(), G4NavigationLogger::CheckAndReportBadNormal(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChange::CheckIt(), G4FastStep::CheckIt(), G4Fancy3DNucleus::ChooseFermiMomenta(), G4NucleiModel::choosePointAlongTraj(), G4Fancy3DNucleus::ChoosePositions(), G4GeomTools::ClosestPointOnSegment(), G4GeomTools::ClosestPointOnTriangle(), G4ParticleHPInelasticCompFS::CompositeApply(), G4PathFinder::ComputeStep(), G4ITPathFinder::ComputeStep(), cos2Theta(), G4GHEKinematicsVector::CosAng(), cosTheta(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4BFieldIntegrationDriver::CurvatureRadius(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4BinaryCascade::DecayVoidNucleus(), G4QGSParticipants::DeterminePartonMomenta(), G4LineSection::Dist(), G4QuadrangularFacet::Distance(), G4TriangularFacet::Distance(), G4GeomTools::DistancePointSegment(), G4Orb::DistanceToIn(), G4Orb::DistanceToOut(), G4Fancy3DNucleus::DoLorentzContraction(), G4PathFinder::DoNextLinearStep(), G4ITPathFinder::DoNextLinearStep(), G4BinaryLightIonReaction::EnergyAndMomentumCorrector(), G4ExcitedStringDecay::EnergyAndMomentumCorrector(), G4SimpleLocator::EstimateIntersectionPoint(), G4BrentLocator::EstimateIntersectionPoint(), G4MultiLevelLocator::EstimateIntersectionPoint(), G4RepleteEofM::EvaluateRhsGivenB(), G4EqEMFieldWithSpin::EvaluateRhsGivenB(), G4EqEMFieldWithEDM::EvaluateRhsGivenB(), G4Mag_SpinEqRhs::EvaluateRhsGivenB(), G4RKPropagation::FieldTransport(), G4LorentzConvertor::fillKinematics(), G4VElasticCollision::FinalState(), G4VScatteringCollision::FinalState(), CLHEP::HepLorentzVector::findBoostToCM(), G4StatMFChannel::FragmentsMomenta(), G4ExcitedStringDecay::FragmentStrings(), G4CutTubs::G4CutTubs(), G4DynamicParticle::G4DynamicParticle(), G4LineSection::G4LineSection(), G4QuadrangularFacet::G4QuadrangularFacet(), G4TriangularFacet::G4TriangularFacet(), gamma(), CLHEP::HepLorentzVector::gamma(), G4PrimaryTransformer::GenerateSingleTrack(), G4WilsonAbrasionModel::GetAbradedNucleons(), G4BinaryCascade::GetFinalNucleusMomentum(), G4MesonAbsorption::GetFinalState(), G4StatMFFragment::GetFragment(), G4MultiNavigator::GetGlobalExitNormal(), G4ITMultiNavigator::GetGlobalExitNormal(), G4Navigator::GetGlobalExitNormal(), G4ITNavigator1::GetGlobalExitNormal(), G4ITNavigator2::GetGlobalExitNormal(), G4VIntersectionLocator::GetGlobalSurfaceNormal(), G4Navigator::GetLocalExitNormal(), G4ITNavigator1::GetLocalExitNormal(), G4ITNavigator2::GetLocalExitNormal(), G4VIntersectionLocator::GetLocalSurfaceNormal(), G4CascadParticle::getPathToTheNextZone(), G4NuclearShellModelDensity::GetRelativeDensity(), G4QGSParticipants::GetResiduals(), G4FTFModel::GetResiduals(), G4RKPropagation::GetSphereIntersectionTimes(), G4VIntersectionLocator::GetSurfaceNormal(), G4Scatterer::GetTimeToInteraction(), PHHepMCGenHelper::HepMC2Lab_boost_rotation_translation(), howNear(), CLHEP::HepLorentzVector::howNearCM(), howParallel(), G4PolarizedPairProductionCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), G4Orb::Inside(), isNear(), CLHEP::HepLorentzVector::isNearCM(), isOrthogonal(), isParallel(), G4FieldTrack::LoadFromArray(), G4PathFinder::Locate(), G4ITPathFinder::Locate(), G4GHEKinematicsVector::Lor(), G4GHEKinematicsVector::Norz(), G4MagInt_Driver::OneGoodStep(), operator<<(), G4StatMFChannel::PlaceFragments(), G4MagInt_Driver::PrintStat_Aux(), G4VLongitudinalStringDecay::ProduceOneHadron(), project(), G4GeneratorPrecompoundInterface::Propagate(), G4GeneratorPrecompoundInterface::PropagateNuclNucl(), G4MagInt_Driver::QuickAdvance(), CLHEP::HepLorentzVector::rapidity(), CexmcChargeExchangeReconstructor::Reconstruct(), CLHEP::HepBoost::rectify(), G4QuasiElRatios::RelDecayIn2(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4SafetyHelper::ReLocateWithinVolume(), G4ITSafetyHelper::ReLocateWithinVolume(), G4MultiLevelLocator::ReportFieldValue(), G4VIntersectionLocator::ReportTrialStep(), CLHEP::HepRotation::rotateAxes(), G4LundStringFragmentation::Sample4Momentum(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4QuasiElasticChannel::Scatter(), G4DynamicParticle::Set4Momentum(), CLHEP::HepRotation::setArbitrarily(), G4DynamicParticle::SetMomentum(), G4GHEKinematicsVector::SetMomentumAndUpdate(), G4VisCommandsViewerSet::SetNewValue(), G4KineticTrack::SetTrackingMomentum(), G4GHEKinematicsVector::SmulAndUpdate(), G4StatMFChannel::SolveEqOfMotion(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4GHEKinematicsVector::Sub(), G4Box::SurfaceNormal(), G4Paraboloid::SurfaceNormal(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4FieldTrackUpdator::Update(), G4KineticTrack::Update4Momentum(), and G4KineticTrack::UpdateTrackingMomentum().
double CLHEP::Hep3Vector::negativeInfinity () const protected
Definition at line 283 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 283 of file SpaceVector.cc
References d, k, and Acts::UnitConstants::u.
Referenced by eta().
bool CLHEP::Hep3Vector::operator!= (const Hep3Vector &) const inline
double CLHEP::Hep3Vector::operator() (int) const inline
double& CLHEP::Hep3Vector::operator() (int) inline
Hep3Vector& CLHEP::Hep3Vector::operator*= (double) inline
Referenced by rotate().
Hep3Vector & CLHEP::Hep3Vector::operator*= (const HepRotation & m1)
Definition at line 20 of file ThreeVectorR.cc.
View newest version in sPHENIX GitHub at line 20 of file ThreeVectorR.cc
Hep3Vector& CLHEP::Hep3Vector::operator+= (const Hep3Vector &) inline
Hep3Vector CLHEP::Hep3Vector::operator- () const inline
Hep3Vector& CLHEP::Hep3Vector::operator-= (const Hep3Vector &) inline
Hep3Vector & CLHEP::Hep3Vector::operator/= (double c)
Definition at line 312 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 312 of file ThreeVector.cc
References c, dx, dy, and dz.
bool CLHEP::Hep3Vector::operator< (const Hep3Vector & v) const
Definition at line 144 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 144 of file SpaceVector.cc
References compare().
bool CLHEP::Hep3Vector::operator<= (const Hep3Vector & v) const
Definition at line 150 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 150 of file SpaceVector.cc
References compare().
Hep3Vector& CLHEP::Hep3Vector::operator= (const Hep3Vector &) inline
Hep3Vector& CLHEP::Hep3Vector::operator= (Hep3Vector &&) inline default
bool CLHEP::Hep3Vector::operator== (const Hep3Vector &) const inline
bool CLHEP::Hep3Vector::operator> (const Hep3Vector & v) const
Definition at line 141 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 141 of file SpaceVector.cc
References compare().
bool CLHEP::Hep3Vector::operator>= (const Hep3Vector & v) const
Definition at line 147 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 147 of file SpaceVector.cc
References compare().
double CLHEP::Hep3Vector::operator[] (int) const inline
double& CLHEP::Hep3Vector::operator[] (int) inline
Hep3Vector CLHEP::Hep3Vector::orthogonal () const inline
Referenced by G4ElectroVDNuclearModel::CalculateEMVertex(), GFlashShowerModel::CheckContainment(), G4OpBoundaryProcess::DielectricLUT(), GFlashShowerModel::ElectronDoIt(), Par01PionShowerModel::Explode(), Par01EMShowerModel::Explode(), G4PlaneVectorRand(), G4LivermorePolarizedRayleighModel::GetPhotonPolarization(), G4BinaryCascade::GetSpherePoint(), G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), G4QuasiElRatios::RelDecayIn2(), G4DNAUeharaScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAChampionElasticModel::SampleSecondaries(), G4DNAELSEPAElasticModel::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), and G4DNAPTBElasticModel::SampleSecondaries().
double CLHEP::Hep3Vector::perp () const inline
Referenced by G4PolyconeSide::DistanceAway(), G4Paraboloid::DistanceToOut(), G4Hype::DistanceToOut(), G4ReplicaNavigation::DistanceToOut(), H02MuonHit::Draw(), G4PolyconeSide::Extent(), G4ErrorCylSurfaceTarget::GetDistanceFromPoint(), RawClusterUtility::GetETCore(), G4ErrorCylSurfaceTarget::GetTangentPlane(), G4PolyconeSide::Intersect(), G4ErrorCylSurfaceTarget::IntersectLocal(), G4EnclosingCylinder::MustBeOutside(), G4PolyconeSide::Normal(), G4PolyconeSide::PointOnCone(), Par02TrackingAction::PreUserTrackingAction(), H02MuonHit::Print(), CaloCalibEmc_Pi0::process_event(), G4ErrorFreeTrajState::PropagateError(), G4BetheHeitler5DModel::SampleSecondaries(), G4EnclosingCylinder::ShouldMiss(), and G4StokesVector::Transverse().
double CLHEP::Hep3Vector::perp (const Hep3Vector &) const inline
double CLHEP::Hep3Vector::perp2 () const inline
Referenced by G4Paraboloid::DistanceToIn(), G4Paraboloid::DistanceToOut(), G4PolyconeSide::Extent(), G4PolyhedraSide::Extent(), G4Paraboloid::Inside(), G4ReplicaNavigation::Inside(), and G4Paraboloid::SurfaceNormal().
double CLHEP::Hep3Vector::perp2 (const Hep3Vector &) const inline
Hep3Vector CLHEP::Hep3Vector::perpPart () const inline
Referenced by azimAngle(), G4UCNBoundaryProcess::GetCoordinateTransformMatrix(), and G4LivermorePolarizedRayleighModel::GetPhotonPolarization().
Hep3Vector CLHEP::Hep3Vector::perpPart (const Hep3Vector & v2) const inline
double CLHEP::Hep3Vector::phi () const inline
Referenced by XrayFluoAnalysisManager::analyseStepping(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4tgbVolume::BuildSolidForDivision(), G4RadioactiveDecayBase::ChooseCollimationDirection(), G4RadioactiveDecay::ChooseCollimationDirection(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4TheRayTracer::CreateBitMap(), G4ReplicaNavigation::DistanceToOutPhi(), G4VParameterisationPara::G4VParameterisationPara(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), G4PolyconeSide::GetPhi(), G4PolyhedraSide::GetPhi(), NeuronLoadDataFile::NeuralNetworkDATAfile(), ClusterIso::process_event(), DetectorConstruction::ResiduesView(), G4LogicalCrystalVolume::SetMillerOrientation(), G4MatScanMessenger::SetNewValue(), and NeuronLoadDataFile::SingleNeuronSWCfile().
double CLHEP::Hep3Vector::polarAngle (const Hep3Vector & v2) const
Definition at line 28 of file SpaceVectorD.cc.
View newest version in sPHENIX GitHub at line 28 of file SpaceVectorD.cc
References getTheta().
Referenced by G4UCNBoundaryProcess::MRDiffRefl(), and G4UCNBoundaryProcess::MRDiffTrans().
double CLHEP::Hep3Vector::polarAngle (const Hep3Vector & v2, const Hep3Vector & ref) const
Definition at line 32 of file SpaceVectorD.cc.
View newest version in sPHENIX GitHub at line 32 of file SpaceVectorD.cc
References angle().
Hep3Vector CLHEP::Hep3Vector::project () const inline
Referenced by project().
Hep3Vector CLHEP::Hep3Vector::project (const Hep3Vector & v2) const
Definition at line 89 of file SpaceVectorP.cc.
View newest version in sPHENIX GitHub at line 89 of file SpaceVectorP.cc
References dot(), mag2(), and project().
double CLHEP::Hep3Vector::pseudoRapidity () const
Definition at line 57 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 57 of file ThreeVector.cc
References mag(), and z().
Referenced by Par02TrackingAction::PreUserTrackingAction(), ClusterIso::process_event(), and CaloCalibEmc_Pi0::process_event().
double CLHEP::Hep3Vector::r () const inline
Referenced by XrayFluoPrimaryGeneratorAction::ActivatePhaseSpace().
double CLHEP::Hep3Vector::rapidity () const
Definition at line 54 of file SpaceVectorP.cc.
View newest version in sPHENIX GitHub at line 54 of file SpaceVectorP.cc
References dz.
double CLHEP::Hep3Vector::rapidity (const Hep3Vector & v2) const
Definition at line 100 of file SpaceVectorP.cc.
View newest version in sPHENIX GitHub at line 100 of file SpaceVectorP.cc
References dot(), mag(), and z1.
double CLHEP::Hep3Vector::rho () const inline
Hep3Vector & CLHEP::Hep3Vector::rotate (double angle1, const Hep3Vector & aaxis)
Definition at line 28 of file ThreeVectorR.cc.
View newest version in sPHENIX GitHub at line 28 of file ThreeVectorR.cc
References operator*=(), and CLHEP::HepRotation::rotate().
Referenced by G4NucleiModel::choosePointAlongTraj(), G4tgbPlaceParamCircle::ComputeTransformation(), G4OpBoundaryProcess::DielectricLUT(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), G4UCNBoundaryProcess::GetCoordinateTransformMatrix(), G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), G4LatticePhysical::MapKtoV(), G4LatticePhysical::MapKtoVDir(), G4Channeling::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4RPGReaction::Rotate(), CLHEP::HepLorentzVector::rotate(), rotate(), CLHEP::rotationOf(), G4RPGInelastic::SetUpChange(), and G4Channeling::UpdateParameters().
Hep3Vector & CLHEP::Hep3Vector::rotate (const Hep3Vector & axis, double delta)
Definition at line 25 of file SpaceVectorR.cc.
View newest version in sPHENIX GitHub at line 25 of file SpaceVectorR.cc
References cd, dx, dy, dz, getX(), getY(), getZ(), mag(), r1, scale, ux, and uy.
Hep3Vector & CLHEP::Hep3Vector::rotate (const HepAxisAngle & ax)
Definition at line 112 of file SpaceVectorR.cc.
View newest version in sPHENIX GitHub at line 112 of file SpaceVectorR.cc
References CLHEP::HepAxisAngle::delta(), CLHEP::HepAxisAngle::getAxis(), and rotate().
Hep3Vector & CLHEP::Hep3Vector::rotate (const HepEulerAngles & e)
Definition at line 116 of file SpaceVectorR.cc.
View newest version in sPHENIX GitHub at line 116 of file SpaceVectorR.cc
References CLHEP::HepEulerAngles::phi(), CLHEP::HepEulerAngles::psi(), rotate(), and CLHEP::HepEulerAngles::theta().
Hep3Vector & CLHEP::Hep3Vector::rotate (double phi, double theta, double psi)
Definition at line 74 of file SpaceVectorR.cc.
View newest version in sPHENIX GitHub at line 74 of file SpaceVectorR.cc
References dx, dy, and dz.
Hep3Vector & CLHEP::Hep3Vector::rotateUz (const Hep3Vector & NewUzVector)
Definition at line 37 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 37 of file ThreeVector.cc
References dx, dy, dz, x(), y(), and z().
Referenced by G4PreCompoundEmission::AngularDistribution(), G4MuonVDNuclearModel::CalculateEMVertex(), G4TheRayTracer::CreateBitMap(), G4MuonDecayChannelWithSpin::DecayIt(), G4PionRadiativeDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4SingleScatter::DoCollisionStep(), G4HadronicProcess::FillResult(), G4FissionProductYieldDist::G4GetFission(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), PrimaryGeneratorAction3::GeneratePrimaries(), PrimaryGeneratorAction4::GeneratePrimaries(), G4OpBoundaryProcess::GetFacetNormal(), G4RDPhotoElectricAngularGeneratorSauterGavrila::GetPhotoElectronDirection(), G4UCNBoundaryProcess::LDiffRefl(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), CLHEP::HepLorentzVector::rotateUz(), G4DeltaAngleFreeScat::SampleDirection(), G4DipBustGenerator::SampleDirection(), G4SauterGavrilaAngularDistribution::SampleDirection(), G4DeltaAngle::SampleDirection(), G4PhotoElectricAngularGeneratorSauterGavrila::SampleDirection(), G4RayleighAngularGenerator::SampleDirection(), G4Generator2BN::SampleDirection(), G4ModifiedTsai::SampleDirection(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4Generator2BS::SampleDirection(), G4DNABornAngle::SampleDirectionForShell(), G4DNARuddAngle::SampleDirectionForShell(), G4VLEPTSModel::SampleNewDirection(), G4DipBustGenerator::SamplePairDirections(), G4ModifiedTsai::SamplePairDirections(), G4WentzelVIModel::SampleScattering(), G4UrbanMscModel::SampleScattering(), G4UrbanAdjointMscModel::SampleScattering(), G4GoudsmitSaundersonMscModel::SampleScattering(), G4LEPTSIonisationModel::SampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), MyKleinNishinaCompton::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4BoldyshevTripletModel::SampleSecondaries(), G4XrayRayleighModel::SampleSecondaries(), G4LivermoreGammaConversionModelRC::SampleSecondaries(), G4LivermoreNuclearGammaConversionModel::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4LivermoreComptonModifiedModel::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4ee2KChargedModel::SampleSecondaries(), G4ee2KNeutralModel::SampleSecondaries(), G4eeToTwoPiModel::SampleSecondaries(), G4LivermoreGammaConversionModel::SampleSecondaries(), G4LivermoreComptonModel::SampleSecondaries(), G4AdjointPhotoElectricModel::SampleSecondaries(), G4eeToPGammaModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4PenelopeAnnihilationModel::SampleSecondaries(), G4PenelopeGammaConversionModel::SampleSecondaries(), G4JAEAElasticScatteringModel::SampleSecondaries(), G4PenelopeRayleighModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4PenelopePhotoElectricModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4PolarizedAnnihilationModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4mplIonisationWithDeltaModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PenelopeComptonModel::SampleSecondaries(), G4PenelopeIonisationModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4LowEPComptonModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), and G4PolarizationHelper::TestInteractionFrame().
Hep3Vector & CLHEP::Hep3Vector::rotateX (double phi1)
Definition at line 89 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 89 of file ThreeVector.cc
References dy, and dz.
Referenced by G4CrystalUnitCell::G4CrystalUnitCell(), CLHEP::HepLorentzVector::rotateX(), and CLHEP::rotationXOf().
Hep3Vector & CLHEP::Hep3Vector::rotateY (double phi1)
Definition at line 99 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 99 of file ThreeVector.cc
References dx, and dz.
Referenced by G4JLeicBeamLineMagnetDetector::ConstructMe(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASphereBoundary(), CLHEP::HepLorentzVector::rotateY(), and CLHEP::rotationYOf().
Hep3Vector & CLHEP::Hep3Vector::rotateZ (double phi1)
Definition at line 109 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 109 of file ThreeVector.cc
References dx, and dy.
Referenced by H02DetectorConstruction::Construct(), PHG4MvtxDetector::ConstructMvtx_Layer(), PHG4EICMvtxDetector::ConstructMvtx_Layer(), G4TheRayTracer::CreateBitMap(), DNAParser::CreateCutSolid(), G4CrystalUnitCell::G4CrystalUnitCell(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASphereBoundary(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), CLHEP::HepLorentzVector::rotateZ(), and CLHEP::rotationZOf().
void CLHEP::Hep3Vector::set (double x, double y, double z) inline
Referenced by G4GMocrenFileSceneHandler::AddSolid(), G4PreCompoundEmission::AngularDistribution(), G4ScaledSolid::BoundingLimits(), G4ReflectedSolid::BoundingLimits(), G4Box::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4VTwistedFaceted::BoundingLimits(), G4EllipticalTube::BoundingLimits(), G4Orb::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4UnionSolid::BoundingLimits(), G4GenericPolycone::BoundingLimits(), G4Hype::BoundingLimits(), G4Ellipsoid::BoundingLimits(), G4Paraboloid::BoundingLimits(), G4TwistedTubs::BoundingLimits(), G4Polycone::BoundingLimits(), G4Polyhedra::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Trd::BoundingLimits(), G4VSolid::BoundingLimits(), G4EllipticalCone::BoundingLimits(), G4Tubs::BoundingLimits(), G4Para::BoundingLimits(), G4Torus::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Cons::BoundingLimits(), G4Sphere::BoundingLimits(), G4Trap::BoundingLimits(), G4Voxelizer::BuildVoxelLimits(), G4NucleiModel::choosePointAlongTraj(), G4Fancy3DNucleus::ChoosePositions(), G4HadFinalState::Clear(), CML2ExpVoxels::CML2ExpVoxels(), CML2Ph_BoxInBox::CML2Ph_BoxInBox(), CML2Ph_FullWater::CML2Ph_FullWater(), G4GoudsmitSaundersonMscModel::ComputeTruePathLengthLimit(), FFDetectorConstruction::Construct(), CML2Ph_BoxInBox::Construct(), CML2AcceleratorConstruction::Construct(), PHG4TpcEndCapDetector::ConstructElectronics(), G4DiffractiveExcitation::CreateStrings(), G4VTwistSurface::CurrentStatus::CurrentStatus(), CLHEP::HepRotationY::decompose(), CLHEP::HepRotationZ::decompose(), CLHEP::HepRotationX::decompose(), CLHEP::HepRotation::decompose(), G4VTwistSurface::DistanceToBoundary(), G4VTwistedFaceted::DistanceToIn(), G4TwistedTubs::DistanceToIn(), G4VTwistedFaceted::DistanceToOut(), G4EllipticalTube::DistanceToOut(), G4Box::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4ExtrudedSolid::DistanceToOut(), G4Trd::DistanceToOut(), G4Para::DistanceToOut(), G4Trap::DistanceToOut(), G4TwistTrapFlatSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), CML2PrimaryGenerationAction::fillParticlesContainer(), CML2Acc1::flatteningFilter(), CML2Acc2::flatteningFilter(), G4BoundingEnvelope::G4BoundingEnvelope(), G4FissionProductYieldDist::G4GetFission(), G4GoudsmitSaundersonMscModel::G4GoudsmitSaundersonMscModel(), G4HadProjectile::G4HadProjectile(), G4LatticeLogical::G4LatticeLogical(), G4Para::G4Para(), G4TessellatedSolid::G4TessellatedSolid(), G4TriangularFacet::G4TriangularFacet(), G4TwistBoxSide::G4TwistBoxSide(), G4TwistTrapAlphaSide::G4TwistTrapAlphaSide(), G4TwistTrapFlatSide::G4TwistTrapFlatSide(), G4TwistTrapParallelSide::G4TwistTrapParallelSide(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4TwistTubsHypeSide::G4TwistTubsHypeSide(), G4TwistTubsSide::G4TwistTubsSide(), G4VTwistSurface::G4VTwistSurface(), G4eeToHadronsModel::GenerateCMPhoton(), CML2PrimaryGenerationAction::GenerateFromRandom(), G4InuclSpecialFunctions::generateWithFixedTheta(), G4InuclSpecialFunctions::generateWithRandomAngles(), ClusterJetInput::get_input(), G4EllipticalTube::GetPointOnSurface(), G4Ellipsoid::GetPointOnSurface(), G4Trd::GetPointOnSurface(), G4EllipticalCone::GetPointOnSurface(), G4Para::GetPointOnSurface(), G4Trap::GetVertices(), G4EmExtraParameters::Initialise(), G4TessellatedSolid::Initialize(), G4NucleiModel::initializeCascad(), G4VTwistedFaceted::Inside(), G4TwistedTubs::Inside(), G4QuadrangularFacet::Intersect(), G4TriangularFacet::Intersect(), CML2Acc1::ionizationChamber(), CML2Acc2::ionizationChamber(), CML2Acc1::Jaw1X(), CML2Acc2::Jaw1X(), CML2AccSaturn::Jaw1X(), CML2Acc1::Jaw1Y(), CML2Acc2::Jaw1Y(), CML2AccSaturn::Jaw1Y(), CML2Acc1::Jaw2X(), CML2Acc2::Jaw2X(), CML2AccSaturn::Jaw2X(), CML2Acc1::Jaw2Y(), CML2Acc2::Jaw2Y(), CML2AccSaturn::Jaw2Y(), G4VTwistedFaceted::LastState::LastState(), G4TwistedTubs::LastState::LastState(), G4VTwistedFaceted::LastValue::LastValue(), G4TwistedTubs::LastValue::LastValue(), G4VTwistedFaceted::LastValueWithDoubleVector::LastValueWithDoubleVector(), G4TwistedTubs::LastValueWithDoubleVector::LastValueWithDoubleVector(), G4VTwistedFaceted::LastVector::LastVector(), G4TwistedTubs::LastVector::LastVector(), G4LatticeLogical::Load_NMap(), CML2Acc1::MLC(), CML2Acc2::MLC(), CLHEP::operator>>(), G4OpMieHG::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), QAG4SimulationCalorimeter::process_event_Cluster(), G4DipBustGenerator::SampleDirection(), G4DeltaAngleFreeScat::SampleDirection(), G4SauterGavrilaAngularDistribution::SampleDirection(), G4DeltaAngle::SampleDirection(), G4PhotoElectricAngularGeneratorSauterGavrila::SampleDirection(), G4RayleighAngularGenerator::SampleDirection(), G4GammaTransition::SampleDirection(), G4PenelopeBremsstrahlungAngular::SampleDirection(), G4Generator2BN::SampleDirection(), G4ModifiedTsai::SampleDirection(), G4Generator2BS::SampleDirection(), G4DNABornAngle::SampleDirectionForShell(), G4DNARuddAngle::SampleDirectionForShell(), G4UrbanMscModel::SampleDisplacement(), G4UrbanAdjointMscModel::SampleDisplacement(), G4UrbanMscModel::SampleDisplacementNew(), G4UrbanAdjointMscModel::SampleDisplacementNew(), G4GoudsmitSaundersonMscModel::SampleMSC(), G4DipBustGenerator::SamplePairDirections(), G4ModifiedTsai::SamplePairDirections(), G4WentzelVIModel::SampleScattering(), G4UrbanMscModel::SampleScattering(), G4UrbanAdjointMscModel::SampleScattering(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4WentzelOKandVIxSection::SampleSingleScattering(), G4VTwistSurface::SetCorner(), CML2Acc1::SetJawAperture(), CML2Acc2::SetJawAperture(), CML2AccSaturn::SetJawAperture(), G4Voxelizer::SetMaxVoxels(), G4HadFinalState::SetMomentumChange(), CML2CInputData::setPhaseSpaceCentre(), CML2CInputData::setPhaseSpaceHalfSize(), G4Voxelizer::SetReductionRatio(), G4StatMFChannel::SolveEqOfMotion(), G4GeomTools::SphereExtent(), G4VTwistedFaceted::SurfaceNormal(), G4TwistedTubs::SurfaceNormal(), CML2AccSaturn::target(), G4MultiUnion::TransformLimits(), and G4Voxelizer::TransformLimits().
void CLHEP::Hep3Vector::setCylEta (double p)
Definition at line 258 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 258 of file ThreeVector.cc
References dx, dy, dz, getPhi(), getRho(), and CLHEP::pi.
void CLHEP::Hep3Vector::setCylindrical (double r, double phi, double z) protected
Definition at line 56 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 56 of file SpaceVector.cc
References dx, dy, dz, and z1.
void CLHEP::Hep3Vector::setCylTheta (double theta1)
Definition at line 210 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 210 of file ThreeVector.cc
References dx, dy, dz, getPhi(), getRho(), and CLHEP::pi.
void CLHEP::Hep3Vector::setEta (double p)
Definition at line 182 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 182 of file ThreeVector.cc
References dx, dy, dz, getPhi(), getR(), and r1.
void CLHEP::Hep3Vector::setMag (double ma)
Definition at line 24 of file ThreeVector.cc.
View newest version in sPHENIX GitHub at line 24 of file ThreeVector.cc
References mag(), setX(), setY(), setZ(), x(), y(), and z().
Referenced by G4EMDissociation::ApplyYourself(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), G4UCNBoundaryProcess::GetCoordinateTransformMatrix(), and CexmcChargeExchangeReconstructor::Reconstruct().
void CLHEP::Hep3Vector::setPerp (double) inline
void CLHEP::Hep3Vector::setPhi (double) inline
Referenced by G4RadioactiveDecayBase::ChooseCollimationDirection(), G4RadioactiveDecay::ChooseCollimationDirection(), and GammaRayTelPrimaryGeneratorAction::GeneratePrimaries().
void CLHEP::Hep3Vector::setR (double s) inline
Referenced by XrayFluoPrimaryGeneratorAction::ActivatePhaseSpace(), and G4FissionProductYieldDist::G4GetFission().
void CLHEP::Hep3Vector::setREtaPhi (double r, double eta, double phi) inline
void CLHEP::Hep3Vector::setRho (double s) inline
void CLHEP::Hep3Vector::setRhoPhiEta (double rho, double phi, double eta)
Definition at line 98 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 98 of file SpaceVector.cc
References dx, dy, and dz.
Referenced by RawTowerCombiner::CreateNodes().
void CLHEP::Hep3Vector::setRhoPhiTheta (double rho, double phi, double theta)
Definition at line 71 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 71 of file SpaceVector.cc
References dx, dy, and dz.
void CLHEP::Hep3Vector::setRhoPhiZ (double rho, double phi, double z) inline
void CLHEP::Hep3Vector::setRThetaPhi (double r, double theta, double phi) inline
Referenced by G4CascadeFinalStateAlgorithm::FillUsingKopylov(), G4FissionProductYieldDist::G4GetFission(), G4AdjointPosOnPhysVolGenerator::GenerateAPositionOnASphereBoundary(), FFPrimaryGeneratorAction::GeneratePrimaries(), G4CascadeFinalStateAlgorithm::GenerateTwoBody(), G4UCNBoundaryProcess::LDiffRefl(), G4UCNBoundaryProcess::MRDiffRefl(), G4UCNBoundaryProcess::MRDiffTrans(), and G4VHadPhaseSpaceAlgorithm::UniformVector().
void CLHEP::Hep3Vector::setSpherical (double r, double theta, double phi) protected
Definition at line 35 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 35 of file SpaceVector.cc
References dx, dy, and dz.
void CLHEP::Hep3Vector::setTheta (double) inline
Referenced by G4RadioactiveDecayBase::ChooseCollimationDirection(), G4RadioactiveDecay::ChooseCollimationDirection(), and GammaRayTelPrimaryGeneratorAction::GeneratePrimaries().
double CLHEP::Hep3Vector::setTolerance (double tol) static
Definition at line 271 of file SpaceVector.cc.
View newest version in sPHENIX GitHub at line 271 of file SpaceVector.cc
References tolerance.
void CLHEP::Hep3Vector::setX (double) inline
Referenced by G4GHEKinematicsVector::Add3(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4DecayWithSpin::AtRestDoIt(), CLHEP::HepLorentzVector::boostX(), G4Torus::CalculateExtent(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), CML2Ph_FullWater::CML2Ph_FullWater(), G4ParameterisationParaX::ComputeTransformation(), G4ParameterisationBoxX::ComputeTransformation(), G4ParameterisationTrdX::ComputeTransformation(), G4ReplicaNavigation::ComputeTransformation(), G4ParameterisationParaY::ComputeTransformation(), CML2Ph_FullWater::Construct(), RE02DetectorConstruction::Construct(), PHG4EICMvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtx_Layer(), CexmcSetup::ConvertToCrystalGeometry(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G3Division::CreatePVReplica(), G4TessellatedSolid::CreateVertexList(), G4GHEKinematicsVector::Cross(), G4GDMLReadSolids::CutTubeRead(), G4SFDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4GHEKinematicsVector::Defs(), G4GHEKinematicsVector::Defs1(), G4StokesVector::DiceP1(), G4StokesVector::DiceP2(), G4StokesVector::DiceP3(), G4StokesVector::DiceUniform(), CexmcTrackPointsDigitizer::Digitize(), Par01EnergySpot::Draw(), G4StatMFChannel::FragmentsMomenta(), G4FragmentingString::G4FragmentingString(), G4FissionProductYieldDist::G4GetFission(), G4GHEKinematicsVector::G4GHEKinematicsVector(), G4SPSAngDistribution::GenerateBeamFlux(), G4SPSAngDistribution::GenerateCosineLawFlux(), CML2PrimaryGenerationAction::GenerateFromRandom(), DMXParticleSource::GenerateIsotropicFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), G4SPSPosDistribution::GeneratePointsInBeam(), G4SPSPosDistribution::GeneratePointsInPlane(), DMXParticleSource::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), RE02PrimaryGeneratorAction::GeneratePrimaries(), G4SPSAngDistribution::GenerateUserDefFlux(), G4OpBoundaryProcess::GetFacetNormal(), G4LivermorePolarizedComptonModel::GetRandomPolarization(), G4LivermorePolarizedGammaConversionModel::GetRandomPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetRandomPolarization(), G4LowEnergyPolarizedCompton::GetRandomPolarization(), G4LowEPPolarizedComptonModel::GetRandomPolarization(), G4GDecay3::GetThreeBodyMomenta(), TrentoPassiveProtonBeamLine::HadrontherapyBeamMonitoring(), G4PolarizedPairProductionCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), G4PolarizedAnnihilationCrossSection::Initialize(), CML2ExpVoxels::loadData(), G4GHEKinematicsVector::Lor(), CCalMagneticField::MagneticField(), G4Trap::MakePlane(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), CML2Acc1::MLC(), CML2Acc2::MLC(), G4GHEKinematicsVector::Norz(), G4GHEKinematicsVector::operator=(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4STRead::PhysvolRead(), G4GDMLReadDefine::PositionRead(), G4DecayWithSpin::PostStepDoIt(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4ParticleChangeForLoss::ProposeMomentumDirection(), G4ParticleChangeForGamma::ProposePolarization(), G4ParticleChangeForDecay::ProposePolarization(), G4ParticleChangeForLoss::ProposePolarization(), RE02DetectorConstruction::RE02DetectorConstruction(), CexmcReconstructor::ReconstructEntryPoints(), CexmcReconstructor::ReconstructTargetPoint(), G4GDMLReadSolids::ReflectedSolidRead(), G4StokesVector::RotateAz(), G4GDMLReadDefine::RotationRead(), G4LEPTSIonisationModel::SampleSecondaries(), G4GDMLReadDefine::ScaleRead(), G4PrimaryParticle::Set4Momentum(), G4PSDoseDepositForCylinder3D::SetCylinderSize(), G4PSPassageCellFluxForCylinder3D::SetCylinderSize(), G4PSCellFluxForCylinder3D::SetCylinderSize(), IORTDetectorConstruction::SetDetectorPosition(), HadrontherapyDetectorConstruction::SetDetectorPosition(), G4GHEKinematicsVector::SetEnergyAndUpdate(), G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), setMag(), G4GHEKinematicsVector::SetMassAndUpdate(), G4ReactionProduct::SetMomentum(), G4GHEKinematicsVector::SetMomentum(), G4PrimaryParticle::SetMomentum(), G4GHEKinematicsVector::SetMomentumAndUpdate(), G4LivermorePolarizedComptonModel::SetNewPolarization(), G4LowEnergyPolarizedCompton::SetNewPolarization(), G4LowEPPolarizedComptonModel::SetNewPolarization(), G4ReactionProduct::SetPositionInNucleus(), G4GHEKinematicsVector::SetZero(), G4GHEKinematicsVector::Smul(), G4GHEKinematicsVector::SmulAndUpdate(), G4GHEKinematicsVector::Sub3(), G4Box::SurfaceNormal(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4GHEKinematicsVector::Trac(), G4MultiUnion::TransformLimits(), G4Voxelizer::TransformLimits(), G4Channeling::UpdateParameters(), and G4GDMLReadDefine::VectorRead().
void CLHEP::Hep3Vector::setY (double) inline
Referenced by G4GHEKinematicsVector::Add3(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4DecayWithSpin::AtRestDoIt(), CLHEP::HepLorentzVector::boostY(), G4Torus::CalculateExtent(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), CML2Ph_FullWater::CML2Ph_FullWater(), G4ReplicaNavigation::ComputeTransformation(), G4ParameterisationBoxY::ComputeTransformation(), G4ParameterisationParaY::ComputeTransformation(), G4ParameterisationTrdY::ComputeTransformation(), CML2Ph_FullWater::Construct(), RE02DetectorConstruction::Construct(), PHG4EICMvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtx_Layer(), CexmcSetup::ConvertToCrystalGeometry(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4TessellatedSolid::CreateVertexList(), G4GHEKinematicsVector::Cross(), G4GDMLReadSolids::CutTubeRead(), G4SFDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4GHEKinematicsVector::Defs(), G4GHEKinematicsVector::Defs1(), G4StokesVector::DiceP1(), G4StokesVector::DiceP2(), G4StokesVector::DiceP3(), G4StokesVector::DiceUniform(), CexmcTrackPointsDigitizer::Digitize(), Par01EnergySpot::Draw(), G4StatMFChannel::FragmentsMomenta(), G4FragmentingString::G4FragmentingString(), G4FissionProductYieldDist::G4GetFission(), G4GHEKinematicsVector::G4GHEKinematicsVector(), G4SPSAngDistribution::GenerateBeamFlux(), G4SPSAngDistribution::GenerateCosineLawFlux(), CML2PrimaryGenerationAction::GenerateFromRandom(), DMXParticleSource::GenerateIsotropicFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), G4SPSPosDistribution::GeneratePointsInBeam(), G4SPSPosDistribution::GeneratePointsInPlane(), DMXParticleSource::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), G01PrimaryGeneratorAction::GeneratePrimaries(), G04PrimaryGeneratorAction::GeneratePrimaries(), RE02PrimaryGeneratorAction::GeneratePrimaries(), G4SPSAngDistribution::GenerateUserDefFlux(), G4OpBoundaryProcess::GetFacetNormal(), G4LivermorePolarizedComptonModel::GetRandomPolarization(), G4LivermorePolarizedGammaConversionModel::GetRandomPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetRandomPolarization(), G4LowEnergyPolarizedCompton::GetRandomPolarization(), G4LowEPPolarizedComptonModel::GetRandomPolarization(), G4GDecay3::GetThreeBodyMomenta(), TrentoPassiveProtonBeamLine::HadrontherapyBeamMonitoring(), G4PolarizedPairProductionCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), G4PolarizedAnnihilationCrossSection::Initialize(), CML2ExpVoxels::loadData(), G4GHEKinematicsVector::Lor(), CCalMagneticField::MagneticField(), G4Trap::MakePlane(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), CML2Acc1::MLC(), CML2Acc2::MLC(), G4GHEKinematicsVector::Norz(), G4GHEKinematicsVector::operator=(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4STRead::PhysvolRead(), G4GDMLReadDefine::PositionRead(), G4DecayWithSpin::PostStepDoIt(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4ParticleChangeForLoss::ProposeMomentumDirection(), G4ParticleChangeForGamma::ProposePolarization(), G4ParticleChangeForDecay::ProposePolarization(), G4ParticleChangeForLoss::ProposePolarization(), RE02DetectorConstruction::RE02DetectorConstruction(), CexmcReconstructor::ReconstructEntryPoints(), CexmcReconstructor::ReconstructTargetPoint(), G4GDMLReadSolids::ReflectedSolidRead(), G4StokesVector::RotateAz(), G4GDMLReadDefine::RotationRead(), G4LEPTSIonisationModel::SampleSecondaries(), G4GDMLReadDefine::ScaleRead(), G4PrimaryParticle::Set4Momentum(), G4PSDoseDepositForCylinder3D::SetCylinderSize(), G4PSPassageCellFluxForCylinder3D::SetCylinderSize(), G4PSCellFluxForCylinder3D::SetCylinderSize(), IORTDetectorConstruction::SetDetectorPosition(), HadrontherapyDetectorConstruction::SetDetectorPosition(), G4GHEKinematicsVector::SetEnergyAndUpdate(), G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), setMag(), G4GHEKinematicsVector::SetMassAndUpdate(), G4ReactionProduct::SetMomentum(), G4GHEKinematicsVector::SetMomentum(), G4PrimaryParticle::SetMomentum(), G4GHEKinematicsVector::SetMomentumAndUpdate(), G4LivermorePolarizedComptonModel::SetNewPolarization(), G4LowEnergyPolarizedCompton::SetNewPolarization(), G4LowEPPolarizedComptonModel::SetNewPolarization(), G4ReactionProduct::SetPositionInNucleus(), G4GHEKinematicsVector::SetZero(), G4GHEKinematicsVector::Smul(), G4GHEKinematicsVector::SmulAndUpdate(), G4GHEKinematicsVector::Sub3(), G4Box::SurfaceNormal(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4GHEKinematicsVector::Trac(), G4MultiUnion::TransformLimits(), G4Voxelizer::TransformLimits(), and G4GDMLReadDefine::VectorRead().
void CLHEP::Hep3Vector::setZ (double) inline
Referenced by G4GHEKinematicsVector::Add3(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4DecayWithSpin::AtRestDoIt(), CLHEP::HepLorentzVector::boostZ(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), CML2Ph_FullWater::CML2Ph_FullWater(), G4ReplicaNavigation::ComputeTransformation(), G4ParameterisationBoxZ::ComputeTransformation(), G4ParameterisationTrdZ::ComputeTransformation(), FFDetectorConstruction::Construct(), CML2Ph_FullWater::Construct(), RE02DetectorConstruction::Construct(), PHG4EICMvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtx_Layer(), PHG4MvtxDetector::ConstructMvtxPassiveVol(), G4FTFAnnihilation::Create2QuarkAntiQuarkStrings(), G4FTFAnnihilation::Create3QuarkAntiQuarkStrings(), G4TessellatedSolid::CreateVertexList(), G4GHEKinematicsVector::Cross(), G4GDMLReadSolids::CutTubeRead(), G4SFDecay::DecayIt(), G4BetaMinusDecay::DecayIt(), G4BetaPlusDecay::DecayIt(), G4KL3DecayChannel::DecayIt(), G4GHEKinematicsVector::Defs(), G4GHEKinematicsVector::Defs1(), G4StokesVector::DiceP1(), G4StokesVector::DiceP2(), G4StokesVector::DiceP3(), G4StokesVector::DiceUniform(), Par01PiModel::DoIt(), Par01EnergySpot::Draw(), CML2Acc1::flatteningFilter(), G4StokesVector::FlipP3(), G4StatMFChannel::FragmentsMomenta(), G4CutTubs::G4CutTubs(), G4FragmentingString::G4FragmentingString(), G4FissionProductYieldDist::G4GetFission(), G4GHEKinematicsVector::G4GHEKinematicsVector(), G4SPSAngDistribution::GenerateBeamFlux(), G4SPSAngDistribution::GenerateCosineLawFlux(), CML2PrimaryGenerationAction::GenerateFromRandom(), DMXParticleSource::GenerateIsotropicFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), G4SPSPosDistribution::GeneratePointsInBeam(), G4SPSPosDistribution::GeneratePointsInPlane(), DMXParticleSource::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), HadrontherapyPrimaryGeneratorAction::GeneratePrimaries(), G01PrimaryGeneratorAction::GeneratePrimaries(), G04PrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GeneratePrimaries(), G4SPSAngDistribution::GenerateUserDefFlux(), G4OpBoundaryProcess::GetFacetNormal(), G4LivermorePolarizedComptonModel::GetRandomPolarization(), G4LivermorePolarizedGammaConversionModel::GetRandomPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetRandomPolarization(), G4LowEnergyPolarizedCompton::GetRandomPolarization(), G4LowEPPolarizedComptonModel::GetRandomPolarization(), G4GDecay3::GetThreeBodyMomenta(), TrentoPassiveProtonBeamLine::HadrontherapyBeamMonitoring(), G4PolarizedPairProductionCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), G4PolarizedAnnihilationCrossSection::Initialize(), CML2ExpVoxels::loadData(), G4GHEKinematicsVector::Lor(), G4FragmentingString::LorentzRotate(), CCalMagneticField::MagneticField(), G4Trap::MakePlane(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4GHEKinematicsVector::Norz(), G4GHEKinematicsVector::operator=(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4STRead::PhysvolRead(), G4GDMLReadDefine::PositionRead(), G4DecayWithSpin::PostStepDoIt(), G4ParticleChangeForGamma::ProposeMomentumDirection(), G4ParticleChangeForLoss::ProposeMomentumDirection(), G4ParticleChangeForGamma::ProposePolarization(), G4ParticleChangeForDecay::ProposePolarization(), G4ParticleChangeForLoss::ProposePolarization(), RE02DetectorConstruction::RE02DetectorConstruction(), CexmcReconstructor::ReconstructEntryPoints(), CexmcReconstructor::ReconstructTargetPoint(), G4GDMLReadSolids::ReflectedSolidRead(), G4GDMLReadDefine::RotationRead(), G4LundStringFragmentation::Sample4Momentum(), G4LEPTSIonisationModel::SampleSecondaries(), G4GDMLReadDefine::ScaleRead(), G4PrimaryParticle::Set4Momentum(), G4PSDoseDepositForCylinder3D::SetCylinderSize(), G4PSPassageCellFluxForCylinder3D::SetCylinderSize(), G4PSCellFluxForCylinder3D::SetCylinderSize(), IORTDetectorConstruction::SetDetectorPosition(), HadrontherapyDetectorConstruction::SetDetectorPosition(), G4GHEKinematicsVector::SetEnergyAndUpdate(), G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), setMag(), G4GHEKinematicsVector::SetMassAndUpdate(), G4ReactionProduct::SetMomentum(), G4GHEKinematicsVector::SetMomentum(), G4PrimaryParticle::SetMomentum(), G4GHEKinematicsVector::SetMomentumAndUpdate(), G4LivermorePolarizedComptonModel::SetNewPolarization(), G4LowEnergyPolarizedCompton::SetNewPolarization(), G4LowEPPolarizedComptonModel::SetNewPolarization(), G4ReactionProduct::SetPositionInNucleus(), G4GHEKinematicsVector::SetZero(), G4FTFParticipants::ShiftInteractionTime(), G4GHEKinematicsVector::Smul(), G4GHEKinematicsVector::SmulAndUpdate(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4GHEKinematicsVector::Sub3(), G4EllipticalTube::SurfaceNormal(), G4Box::SurfaceNormal(), G4Ellipsoid::SurfaceNormal(), G4PhaseSpaceDecayChannel::ThreeBodyDecayIt(), G4GeneralPhaseSpaceDecay::ThreeBodyDecayIt(), G4GHEKinematicsVector::Trac(), G4MultiUnion::TransformLimits(), G4Voxelizer::TransformLimits(), G4FragmentingString::TransformToCenterOfMass(), and G4GDMLReadDefine::VectorRead().
double CLHEP::Hep3Vector::theta () const inline
Referenced by XrayFluoAnalysisManager::analyseStepping(), G4LENDModel::ApplyYourself(), G4LENDElastic::ApplyYourself(), G4ParticleHPInelastic::ApplyYourself(), G4ParticleHPInelasticBaseFS::BaseApply(), G4tgbVolume::BuildSolidForDivision(), G4RadioactiveDecayBase::ChooseCollimationDirection(), G4RadioactiveDecay::ChooseCollimationDirection(), G4ParameterisationParaX::ComputeDimensions(), G4ParameterisationParaY::ComputeDimensions(), G4ParameterisationParaZ::ComputeDimensions(), G4TheRayTracer::CreateBitMap(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4VParameterisationPara::G4VParameterisationPara(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), GammaRayTelPrimaryGeneratorAction::GeneratePrimaries(), G4SynchrotronRadiation::GetMeanFreePath(), NeuronLoadDataFile::NeuralNetworkDATAfile(), DetectorConstruction::ResiduesView(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4LogicalCrystalVolume::SetMillerOrientation(), G4MatScanMessenger::SetNewValue(), NeuronLoadDataFile::SingleNeuronSWCfile(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), and G4DiffuseElastic::ThetaLabToThetaCMS().
double CLHEP::Hep3Vector::theta (const Hep3Vector & v2) const inline
Hep3Vector & CLHEP::Hep3Vector::transform (const HepRotation & m1)
Definition at line 24 of file ThreeVectorR.cc.
View newest version in sPHENIX GitHub at line 24 of file ThreeVectorR.cc
Referenced by G4GMocrenFileSceneHandler::AddPrimitive(), BeamLineMagnetDetector::ConstructMe(), G4VFieldModel::DescribeYourselfTo(), G4GMocrenFileSceneHandler::EndSavingGdd(), G4LogicalCrystalVolume::RotateToLattice(), G4LogicalCrystalVolume::RotateToSolid(), and G4VisExtent::Transform().
Hep3Vector CLHEP::Hep3Vector::unit () const inline
Referenced by G4PreCompoundEmission::AngularDistribution(), G4BinaryLightIonReaction::ApplyYourself(), G4RPGPiMinusInelastic::ApplyYourself(), G4RPGPiPlusInelastic::ApplyYourself(), G4RPGKMinusInelastic::ApplyYourself(), G4RPGProtonInelastic::ApplyYourself(), G4LEpp::ApplyYourself(), G4RPGAntiProtonInelastic::ApplyYourself(), G4RPGAntiSigmaPlusInelastic::ApplyYourself(), G4RPGSigmaPlusInelastic::ApplyYourself(), G4RPGXiMinusInelastic::ApplyYourself(), G4RPGAntiOmegaMinusInelastic::ApplyYourself(), G4LowEGammaNuclearModel::ApplyYourself(), G4RPGAntiSigmaMinusInelastic::ApplyYourself(), G4RPGAntiXiMinusInelastic::ApplyYourself(), G4RPGOmegaMinusInelastic::ApplyYourself(), G4RPGKPlusInelastic::ApplyYourself(), G4RPGSigmaMinusInelastic::ApplyYourself(), G4ElectroVDNuclearModel::ApplyYourself(), G4MuonVDNuclearModel::ApplyYourself(), G4RPGXiZeroInelastic::ApplyYourself(), G4HadronElastic::ApplyYourself(), G4ParticleHPCaptureFS::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ParticleHPChannelList::ApplyYourself(), G4NeutrinoElectronNcModel::ApplyYourself(), G4NeutrinoElectronCcModel::ApplyYourself(), G4NeutronElectronElModel::ApplyYourself(), G4TheoFSGenerator::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4NuMuNucleusCcModel::ApplyYourself(), CexmcChargeExchangeProductionModel< OutputParticle >::ApplyYourself(), G4LENDInelastic::ApplyYourself(), G4MuMinusCapturePrecompound::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4MuonMinusBoundDecay::ApplyYourself(), G4BinaryCascade::ApplyYourself(), G4WilsonAbrasionModel::ApplyYourself(), G4INCLXXInterface::ApplyYourself(), G4EllipticalTube::ApproxSurfaceNormal(), G4Ellipsoid::ApproxSurfaceNormal(), CLHEP::HepRotation::axis(), G4ParticleHPInelasticBaseFS::BaseApply(), CLHEP::HepLorentzVector::boost(), G4UnstableFragmentBreakUp::BreakUpChain(), G4ElectroVDNuclearModel::CalculateEMVertex(), G4MuonVDNuclearModel::CalculateEMVertex(), G4PolyconeSide::CalculateExtent(), G4OpBoundaryProcess::CalculateReflectivity(), G4NucleiModel::choosePointAlongTraj(), G4BinaryCascade::CorrectFinalPandE(), G4BinaryCascade::CorrectShortlivedFinalsForFermi(), G4TheRayTracer::CreateBitMap(), G4PionDecayMakeSpin::DaughterPolarization(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4IntraNucleiCascader::decayTrappedParticle(), G4SPSAngDistribution::DefineAngRefAxes(), G4OpBoundaryProcess::DielectricDielectric(), G4OpBoundaryProcess::DielectricMetal(), G4MultiUnion::DistanceToIn(), G4TessellatedSolid::DistanceToInCore(), G4MultiUnion::DistanceToInNoVoxels(), G4EllipticalTube::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4Hype::DistanceToOut(), G4Cons::DistanceToOut(), G4TessellatedSolid::DistanceToOutCore(), G4MultiUnion::DistanceToOutNoVoxels(), G4MultiUnion::DistanceToOutVoxels(), G4NRESP71M03::DKINMA(), G4SingleScatter::DoCollisionStep(), G4RKPropagation::FieldTransport(), G4LorentzConvertor::fillKinematics(), G4MuonicAtomDecay::FillResult(), G4CrystalUnitCell::G4CrystalUnitCell(), G4CutTubs::G4CutTubs(), G4DynamicParticle::G4DynamicParticle(), G4PolyhedraSide::G4PolyhedraSide(), G4PolyPhiFace::G4PolyPhiFace(), G4QuadrangularFacet::G4QuadrangularFacet(), G4TheRayTracer::G4TheRayTracer(), G4TriangularFacet::G4TriangularFacet(), G4TwistTubsFlatSide::G4TwistTubsFlatSide(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), G4SPSPosDistribution::GenerateRotationMatrices(), G4OpBoundaryProcess::GetFacetNormal(), G4Navigator::GetGlobalExitNormal(), G4ITNavigator1::GetGlobalExitNormal(), G4ITNavigator2::GetGlobalExitNormal(), G4TwistBoxSide::GetNormal(), G4TwistTrapAlphaSide::GetNormal(), G4TwistTrapParallelSide::GetNormal(), G4TwistTubsSide::GetNormal(), G4LivermorePolarizedRayleighModel::GetPhotonPolarization(), G4LivermorePolarizedComptonModel::GetRandomPolarization(), G4LivermorePolarizedGammaConversionModel::GetRandomPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetRandomPolarization(), G4LowEnergyPolarizedCompton::GetRandomPolarization(), G4LowEPPolarizedComptonModel::GetRandomPolarization(), G4BinaryCascade::GetSpherePoint(), G4Scatterer::GetTimeToInteraction(), G4CrystalUnitCell::GetUnitBasisTrigonal(), G4Tet::Initialize(), G4TessellatedSolid::InsideVoxels(), G4TriangularFacet::Intersect(), G4UCNBoundaryProcess::LDiffRefl(), G4LatticeLogical::Load_NMap(), G4FieldTrack::LoadFromArray(), G4CascadeInterface::makeDynamicParticle(), G4Trap::MakePlane(), G4LatticeManager::MapKtoVDir(), Par01PiModel::ModelTrigger(), G4UCNBoundaryProcess::MRDiffRefl(), G4UCNBoundaryProcess::MRDiffTrans(), G4UCNBoundaryProcess::MRreflect(), G4UCNBoundaryProcess::MRreflectHigh(), G4PolyconeSide::Normal(), G4GenericTrap::NormalToPlane(), G4TwistTrapParallelSide::NormAng(), G4TwistTrapAlphaSide::NormAng(), G4TwistBoxSide::NormAng(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4Channeling::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4CascadeHistory::PrintEntry(), QAG4SimulationCalorimeter::process_event_Cluster(), G4CascadParticle::propagateAlongThePath(), G4FastStep::ProposePrimaryTrackFinalKineticEnergyAndDirection(), G4FastStep::ProposePrimaryTrackFinalMomentumDirection(), G4AdjointComptonModel::RapidSampleSecondaries(), G4AdjointBremsstrahlungModel::RapidSampleSecondaries(), G4AdjointhIonisationModel::RapidSampleSecondaries(), CLHEP::HepRotation::rectify(), G4Fancy3DNucleus::ReduceSum(), G4UCNBoundaryProcess::Reflect(), G4QuasiElRatios::RelDecayIn2(), G4LENDModel::returnUnchanged(), G4LorentzConvertor::rotate(), G4StatMFChannel::RotateMomentum(), G4DNAUeharaScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAScreenedRutherfordElasticModel::SampleSecondaries(), G4DNAChampionElasticModel::SampleSecondaries(), G4AdjointComptonModel::SampleSecondaries(), MyKleinNishinaCompton::SampleSecondaries(), G4DNAELSEPAElasticModel::SampleSecondaries(), G4AdjointeIonisationModel::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNAIonElasticModel::SampleSecondaries(), G4HeatedKleinNishinaCompton::SampleSecondaries(), G4AdjointBremsstrahlungModel::SampleSecondaries(), G4MicroElecElasticModel::SampleSecondaries(), G4MuElecElasticModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4LivermorePolarizedRayleighModel::SampleSecondaries(), G4BetheHeitler5DModel::SampleSecondaries(), G4LivermorePolarizedComptonModel::SampleSecondaries(), G4LivermoreIonisationModel::SampleSecondaries(), G4PolarizedComptonModel::SampleSecondaries(), G4AdjointhIonisationModel::SampleSecondaries(), G4AdjointIonIonisationModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4LDMBremModel::SampleSecondaries(), G4KleinNishinaCompton::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4mplIonisationWithDeltaModel::SampleSecondaries(), G4eSingleCoulombScatteringModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4IonCoulombScatteringModel::SampleSecondaries(), G4PenelopeBremsstrahlungModel::SampleSecondaries(), G4PAIPhotModel::SampleSecondaries(), G4PAIModel::SampleSecondaries(), G4MuPairProductionModel::SampleSecondaries(), G4MollerBhabhaModel::SampleSecondaries(), G4MuBremsstrahlungModel::SampleSecondaries(), G4ICRU73QOModel::SampleSecondaries(), G4MuBetheBlochModel::SampleSecondaries(), G4BraggIonModel::SampleSecondaries(), G4BraggModel::SampleSecondaries(), G4DNAPTBElasticModel::SampleSecondaries(), G4AtimaEnergyLossModel::SampleSecondaries(), G4LindhardSorensenIonModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4BetheBlochModel::SampleSecondaries(), G4IonParametrisedLossModel::SampleSecondaries(), G4Scatterer::Scatter(), CLHEP::HepRotation::set(), G4DynamicParticle::Set4Momentum(), CLHEP::HepRotation::setArbitrarily(), G4TwistTrapParallelSide::SetBoundaries(), G4TwistBoxSide::SetBoundaries(), G4TwistTrapAlphaSide::SetBoundaries(), G4TwistTrapFlatSide::SetBoundaries(), G4TwistTubsFlatSide::SetBoundaries(), G4TwistTubsHypeSide::SetBoundaries(), G4TwistTubsSide::SetBoundaries(), CLHEP::HepRotation::setCols(), G4FastTrack::SetCurrentTrack(), G4RadioactiveDecayBase::SetDecayDirection(), G4RadioactiveDecay::SetDecayDirection(), G4TheRayTracer::SetLightDirection(), G4DynamicParticle::SetMomentum(), G4VisCommandsViewerSet::SetNewValue(), G4ParticleGun::SetParticleMomentum(), DMXParticleSource::SetParticleMomentumDirection(), G4ParticleGun::SetParticleMomentumDirection(), G4SPSAngDistribution::SetParticleMomentumDirection(), G4DecayWithSpin::Spin_Precession(), G4EllipticalTube::SurfaceNormal(), G4UnionSolid::SurfaceNormal(), G4Box::SurfaceNormal(), G4Paraboloid::SurfaceNormal(), G4Ellipsoid::SurfaceNormal(), G4GenericTrap::SurfaceNormal(), G4Tet::SurfaceNormal(), G4MultiUnion::SurfaceNormal(), G4CutTubs::SurfaceNormal(), G4Trd::SurfaceNormal(), G4ExtrudedSolid::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4Tubs::SurfaceNormal(), G4Para::SurfaceNormal(), G4Torus::SurfaceNormal(), G4Cons::SurfaceNormal(), G4Sphere::SurfaceNormal(), G4Trap::SurfaceNormal(), G4LivermorePolarizedGammaConversionModel::SystemOfRefChange(), G4LivermorePolarizedComptonModel::SystemOfRefChange(), G4LivermorePolarizedPhotoElectricGDModel::SystemOfRefChange(), G4LowEnergyPolarizedCompton::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChange(), G4LowEPPolarizedComptonModel::SystemOfRefChangeElect(), G4AblaInterface::toG4Particle(), G4INCLXXInterface::toG4Particle(), G4TheRayTracer::Trace(), G4TheMTRayTracer::Trace(), G4RKPropagation::Transport(), G4KineticTrack::Update4Momentum(), and G4KineticTrack::UpdateTrackingMomentum().
double CLHEP::Hep3Vector::x () const inline
Referenced by G4GHEKinematicsVector::Add3(), EICG4LumiDetector::AddCAL(), G4HepRepFileSceneHandler::AddCompound(), EICG4LumiDetector::AddCuboid(), EICG4LumiDetector::AddExitWindowForV2(), EICG4LumiDetector::AddExitWindowForV3(), G4TessellatedSolid::AddFacet(), HistoManager::AddLeakingParticle(), EICG4LumiDetector::AddLumiExitWindow(), EICG4LumiDetector::AddLumiMag_MagCore(), EICG4LumiDetector::AddLumiMag_OuterVessel(), EICG4LumiDetector::AddLumiTracker(), EICG4LumiDetector::AddLumiWindow(), G4HepRepFileXMLWriter::addPoint(), G4GMocrenFileSceneHandler::AddPrimitive(), EICG4LumiDetector::AddRecCone(), G4GMocrenFileSceneHandler::AddSolid(), EICG4LumiDetector::AddTriangularTrapezoid(), G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4FTFModel::AdjustNucleonsAlgorithm_Sampling(), G4MagHelicalStepper::AdvanceHelix(), G4VTwistSurface::AmIOnLeftSide(), XrayTelAnalysis::analyseStepping(), G4GHEKinematicsVector::Ang(), G4ReactionProduct::Angle(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4ParticleHPElasticFS::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LFission::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4Box::ApproxSurfaceNormal(), G4EllipticalTube::ApproxSurfaceNormal(), G4Ellipsoid::ApproxSurfaceNormal(), G4ExtrudedSolid::ApproxSurfaceNormal(), G4Trd::ApproxSurfaceNormal(), G4EllipticalCone::ApproxSurfaceNormal(), G4CutTubs::ApproxSurfaceNormal(), G4Para::ApproxSurfaceNormal(), G4Torus::ApproxSurfaceNormal(), G4Tubs::ApproxSurfaceNormal(), G4Cons::ApproxSurfaceNormal(), G4Sphere::ApproxSurfaceNormal(), G4Trap::ApproxSurfaceNormal(), G4SPSEneDistribution::ArbEnergyHisto(), ClusteringAlgo::AreOnTheSameCluster(), AreOnTheSameCluster(), G4GDMLReadSolids::BooleanRead(), PHG4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::BooleanWrite(), G4DecayProducts::Boost(), G4NucleiModel::boundaryTransition(), G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ScaledSolid::BoundingLimits(), G4ReflectedSolid::BoundingLimits(), G4Box::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4Orb::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4UnionSolid::BoundingLimits(), G4SubtractionSolid::BoundingLimits(), G4GenericPolycone::BoundingLimits(), G4Hype::BoundingLimits(), G4Paraboloid::BoundingLimits(), G4TwistedTubs::BoundingLimits(), G4Polycone::BoundingLimits(), G4Polyhedra::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Trd::BoundingLimits(), G4GenericTrap::BoundingLimits(), G4EllipticalCone::BoundingLimits(), G4Para::BoundingLimits(), G4Tubs::BoundingLimits(), G4Torus::BoundingLimits(), G4Cons::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Sphere::BoundingLimits(), G4TessellatedSolid::BoundingLimits(), G4Trap::BoundingLimits(), G4Voxelizer::BuildBoundingBox(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4tgbRotationMatrix::BuildG4RotMatrixFrom6(), G4tgbRotationMatrix::BuildG4RotMatrixFrom9(), G4BoundingEnvelope::CalculateExtent(), G4EllipticalCone::CalculateExtent(), PHG4TTLSteppingAction::CalculateSensorHitIndices(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4NavigationLogger::CheckAndReportBadNormal(), G4BoundingEnvelope::CheckBoundingBox(), G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), G4PVPlacement::CheckOverlaps(), G4VParticleChange::CheckSecondary(), G4VoxelLimits::ClipToLimits(), G4PolarizedAnnihilationModel::ComputeCrossSectionPerElectron(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4ReplicaNavigation::ComputeTransformation(), DetectorConstruction0::Construct(), F04ElementField::Construct(), CML2Ph_FullWater::Construct(), RE02DetectorConstruction::Construct(), BeamLineMagnetDetector::ConstructMe(), EICG4LumiDetector::ConstructMe(), doiPETDetectorConstruction::ConstructPhantom(), TSDetectorConstruction::ConstructWorld(), CexmcSetup::ConvertToCrystalGeometry(), G4UIcommand::ConvertToString(), G4GHEKinematicsVector::CosAng(), G4TheRayTracer::CreateBitMap(), DNAParser::CreateCutSolid(), RawTowerCombiner::CreateNodes(), G4GenericTrap::CreatePolyhedron(), G4FastStep::CreateSecondaryTrack(), G4PhysChemIO::FormattedText::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4TessellatedSolid::CreateVertexList(), G4PhysChemIO::FormattedText::CreateWaterMolecule(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), G4GHEKinematicsVector::Cross(), G4PionDecayMakeSpin::DaughterPolarization(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4PolarizedAnnihilationCrossSection::DefineCoefficients(), G4PolarizedComptonCrossSection::DefineCoefficients(), G4GHEKinematicsVector::Defs(), G4RPGReaction::Defs1(), G4GHEKinematicsVector::Defs1(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), CexmcTrackPointsDigitizer::Digitize(), G4VTwistSurface::DistanceToBoundary(), G4VTwistedFaceted::DistanceToIn(), G4EllipticalTube::DistanceToIn(), G4Box::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4TwistedTubs::DistanceToIn(), G4Hype::DistanceToIn(), G4CutTubs::DistanceToIn(), G4ExtrudedSolid::DistanceToIn(), G4Trd::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4Tubs::DistanceToIn(), G4Torus::DistanceToIn(), G4Para::DistanceToIn(), G4Cons::DistanceToIn(), G4Sphere::DistanceToIn(), G4Trap::DistanceToIn(), G4TessellatedSolid::DistanceToInNoVoxels(), G4VTwistedFaceted::DistanceToOut(), G4EllipticalTube::DistanceToOut(), G4Box::DistanceToOut(), G4IntersectionSolid::DistanceToOut(), G4UnionSolid::DistanceToOut(), G4Orb::DistanceToOut(), G4SubtractionSolid::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4GenericTrap::DistanceToOut(), G4Hype::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4CutTubs::DistanceToOut(), G4ExtrudedSolid::DistanceToOut(), G4Trd::DistanceToOut(), G4ReplicaNavigation::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4Tubs::DistanceToOut(), G4Torus::DistanceToOut(), G4Para::DistanceToOut(), G4Cons::DistanceToOut(), G4Sphere::DistanceToOut(), G4Trap::DistanceToOut(), G4TessellatedSolid::DistanceToOutNoVoxels(), G4ReplicaNavigation::DistanceToOutPhi(), G4ReplicaNavigation::DistanceToOutRad(), G4TwistTrapFlatSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), G4GenericTrap::DistToPlane(), G4GenericTrap::DistToTriangle(), G4GHEKinematicsVector::Dot(), G4GHEKinematicsVector::Dot4(), Par01EnergySpot::Draw(), G4LatticeLogical::Dump_NMap(), G4tgbGeometryDumper::DumpBooleanVolume(), G4ParticleChangeForMSC::DumpInfo(), G4ParticleChangeForLoss::DumpInfo(), G4ParticleChange::DumpInfo(), G4FastStep::DumpInfo(), G4tgbGeometryDumper::DumpPVPlacement(), DicomBeamControlPoint::DumpToFile(), TrackerSD::EndOfEvent(), ExGflashEventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), FW::Geant4::MMEventAction::EndOfEventAction(), G4SPSEneDistribution::EpnEnergyHisto(), G4VSolid::EstimateSurfaceArea(), G4EqEMFieldWithSpin::EvaluateRhsGivenB(), G4RepleteEofM::EvaluateRhsGivenB(), G4EqEMFieldWithEDM::EvaluateRhsGivenB(), G4Mag_SpinEqRhs::EvaluateRhsGivenB(), G4MultiUnion::Extent(), G4PolyPhiFace::Extent(), PHG4OuterHcalSteppingAction::FieldChecker(), Analysis::FillDose(), Analysis::FillIncident(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), CylinderGeomIntt::find_strip_center(), EICG4B0ECALSteppingAction::FindTowerIndexFromPosition(), EICG4BwdSteppingAction::FindTowerIndexFromPosition(), PHG4ForwardDualReadoutSteppingAction::FindTowerIndexFromPosition(), EICG4B0SteppingAction::FindTowerIndexFromPosition(), G4BestUnit::G4BestUnit(), G4CutTubs::G4CutTubs(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4GHEKinematicsVector::G4GHEKinematicsVector(), G4Para::G4Para(), G4PolyPhiFace::G4PolyPhiFace(), G4RandomPointOnEllipsoid(), G4UniformElectricField::G4UniformElectricField(), G4UniformGravityField::G4UniformGravityField(), G4UniformMagField::G4UniformMagField(), G4VPhysicalVolume::G4VPhysicalVolume(), PHHepMCGenHelper::generate_vertx_with_bunch_interaction(), G4SPSAngDistribution::GenerateBeamFlux(), G4SPSAngDistribution::GenerateCosineLawFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), G4SPSPosDistribution::GeneratePointsInBeam(), G4SPSPosDistribution::GeneratePointsInPlane(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), TSPrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GeneratePrimaries(), MedicalBeam::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), G4PrimaryTransformer::GenerateSingleTrack(), G4CascadeFinalStateAlgorithm::GenerateTwoBody(), G4SPSAngDistribution::GenerateUserDefFlux(), ClusterJetInput::get_input(), EICG4dRICHHit::get_x(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), G4TwistTubsFlatSide::GetBoundaryMax(), G4TwistTubsHypeSide::GetBoundaryMax(), G4TwistTubsFlatSide::GetBoundaryMin(), G4TwistTubsHypeSide::GetBoundaryMin(), G4Voxelizer::GetCandidatesVoxelArray(), G4ScaledSolid::GetCubicVolume(), G4MultiUnion::GetCubicVolume(), G4Trap::GetCubicVolume(), G4CutTubs::GetCutZ(), G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint(), G4ChannelingECHARM::GetEC(), G4Tet::GetExtent(), G4GenericTrap::GetExtent(), G4EllipticalCone::GetExtent(), G4TessellatedSolid::GetExtent(), G4TwistTrapFlatSide::GetFacets(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistBoxSide::GetFacets(), G4TwistTrapParallelSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), G4TwistTrapAlphaSide::GetFacets(), PyG4MagneticField::GetFieldValue(), G4CachedMagneticField::GetFieldValue(), G4QuadrupoleMagField::GetFieldValue(), G4BFieldIntegrationDriver::GetFieldValue(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4CutTubs::GetMaxMinZ(), G4TessellatedSolid::GetMaxXExtent(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4TessellatedSolid::GetMinXExtent(), G4TwistTubsSide::GetNormal(), G4TwistTubsHypeSide::GetNormal(), G4PolarizationHelper::GetParticleFrameX(), G4PolarizationHelper::GetParticleFrameY(), G4PolyconeSide::GetPhi(), G4PolyhedraSide::GetPhi(), G4TwistBoxSide::GetPhiUAtX(), G4TwistTrapParallelSide::GetPhiUAtX(), G4TwistTrapAlphaSide::GetPhiUAtX(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4PrimaryParticle::GetPx(), G4LivermorePolarizedComptonModel::GetRandomPolarization(), G4LivermorePolarizedGammaConversionModel::GetRandomPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetRandomPolarization(), G4LowEnergyPolarizedCompton::GetRandomPolarization(), G4LowEPPolarizedComptonModel::GetRandomPolarization(), G4PartialPhantomParameterisation::GetReplicaNo(), G4PhantomParameterisation::GetReplicaNo(), G4ScoringBox::GetReplicaPosition(), G4tgrUtils::GetRotationFromDirection(), G4GDMLReadDefine::GetRotationMatrix(), G4ScaledSolid::GetScaleTransform(), G4PolarizationHelper::GetSpinInPRF(), G4Scatterer::GetTimeToInteraction(), TSDetectorConstruction::GetTotalTargets(), G4ReactionProduct::GetXPositionInNucleus(), ClusterSBPoints::HasInBarycenter(), G4Pythia6Decayer::ImportDecayProducts(), G4GHEKinematicsVector::Impu(), G4PolarizedBhabhaCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), G4PolarizedMollerCrossSection::Initialize(), G4PolarizedAnnihilationCrossSection::Initialize(), G4PolarizedComptonCrossSection::Initialize(), G4EllipticalTube::Inside(), G4Box::Inside(), G4VTwistedFaceted::Inside(), G4Ellipsoid::Inside(), G4Hype::Inside(), G4PolyPhiFace::Inside(), G4CutTubs::Inside(), G4Trd::Inside(), G4ExtrudedSolid::Inside(), G4TwistedTubs::Inside(), G4EllipticalCone::Inside(), G4Torus::Inside(), G4Para::Inside(), G4Tubs::Inside(), G4ReplicaNavigation::Inside(), G4Cons::Inside(), G4Sphere::Inside(), G4Trap::Inside(), G4PolyPhiFace::InsideEdgesExact(), G4TessellatedSolid::InsideNoVoxels(), G4GenericTrap::InsidePolygone(), G4TessellatedSolid::InsideVoxels(), G4PolyconeSide::Intersect(), G4Hype::IntersectHype(), G4ErrorCylSurfaceTarget::IntersectLocal(), F04SimpleSolenoid::IsOutside(), G4GenericTrap::IsSegCrossingZ(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), F04SimpleSolenoid::IsWithin(), G4QMDGroundStateNucleus::killCMMotionAndAngularM(), G4IntersectingCone::LineHitsCone1(), G4IntersectingCone::LineHitsCone2(), G4PolyhedraSide::LineHitsSegments(), G4VScoringMesh::List(), G4GHEKinematicsVector::Lor(), G4ReactionProduct::Lorentz(), CCalMagneticField::MagneticField(), PHG4RICHSteppingAction::MakeHit(), G4Trap::MakePlane(), G4Para::MakePlanes(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4Voxelizer::MinDistanceToBox(), G4GDMLWriteSolids::MultiUnionWrite(), G4EnclosingCylinder::MustBeOutside(), G4PolyconeSide::Normal(), G4GHEKinematicsVector::Norz(), PHG4GDMLWriteSolids::G4ThreeVectorCompare::operator()(), G4GDMLWriteSolids::G4ThreeVectorCompare::operator()(), operator+(), operator-(), CLHEP::operator/(), operator<<(), CLHEP::operator<<(), G4GHEKinematicsVector::operator=(), G4VoxelLimits::OutCode(), G4TessellatedSolid::OutsideOfExtent(), G4StokesVector::p1(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), G4GDMLReadParamvol::ParametersRead(), G4PhotoElectricAngularGeneratorPolarized::PerpendicularVector(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4STRead::PhysvolRead(), G4GDMLReadStructure::PhysvolRead(), PHG4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteStructure::PhysvolWrite(), G4PolyconeSide::PointOnCone(), G4StokesVector::PolDiv(), G4StokesVector::PolSqr(), G4StokesVector::PolSqrt(), G4GDMLWriteDefine::Position_vectorWrite(), PHG4GDMLWriteDefine::Position_vectorWrite(), G4Channeling::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), B5DriftChamberHit::Print(), G4PrimaryParticle::Print(), G4GHEKinematicsVector::Print(), G4MagInt_Driver::PrintStat_Aux(), G4Navigator::PrintState(), G4ITNavigator1::PrintState(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), ExN04MuonSD::ProcessHits(), ScreenSD::ProcessHits(), RE05MuonSD::ProcessHits(), PhantomSD::ProcessHits(), UltraPMTSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4TwistTubsSide::ProjectAtPXPZ(), G4ExtrudedSolid::ProjectPoint(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4MoleculeShoot::RandomPosInBox(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4STRead::Read(), CexmcReconstructor::ReconstructEntryPoints(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4GDMLReadSolids::ReflectedSolidRead(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4MultiLevelLocator::ReportFieldValue(), CLHEP::HepRotation::rotate(), CLHEP::HepRotation::rotateAxes(), CexmcSetup::RotateMatrix(), G4StatMFChannel::RotateMomentum(), rotateUz(), G4GDMLWriteDefine::Rotation_vectorWrite(), PHG4GDMLWriteDefine::Rotation_vectorWrite(), G4TessellatedSolid::SafetyFromInside(), G4TessellatedSolid::SafetyFromOutside(), G4MultiUnion::SafetyFromOutsideNumberNode(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4eeTo3PiModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4GammaTransition::SampleTransition(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), Par02Output::SaveTrack(), G4GDMLWriteDefine::Scale_vectorWrite(), PHG4GDMLWriteDefine::Scale_vectorWrite(), G4GDMLReadSolids::ScaledSolidRead(), G4Scatterer::Scatter(), CLHEP::HepBoost::set(), CLHEP::HepRotation::set(), G4UIcmdWith3Vector::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), G4GHEKinematicsVector::SetEnergyAndUpdate(), G4SPSRandomGenerator::SetEnergyBias(), G4UniformMagField::SetFieldValue(), G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), setMag(), G4GHEKinematicsVector::SetMassAndUpdate(), CexmcProductionModelMessenger::SetNewValue(), G4BlineTracerMessenger::SetNewValue(), CexmcEnergyDepositDigitizerMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4RDPhotoElectricAngularGeneratorPolarized::SetPerpendicularVector(), G4LivermorePolarizedComptonModel::SetPerpendicularVector(), G4LivermorePolarizedGammaConversionModel::SetPerpendicularVector(), G4LivermorePolarizedPhotoElectricGDModel::SetPerpendicularVector(), G4LowEnergyPolarizedCompton::SetPerpendicularVector(), G4LowEPPolarizedComptonModel::SetPerpendicularVector(), G4SPSRandomGenerator::SetPhiBias(), G4PrimaryParticle::SetPolarization(), G4SPSRandomGenerator::SetPosPhiBias(), G4SPSRandomGenerator::SetPosThetaBias(), G3toG4RotationMatrix::SetRotationMatrixByCol(), G3toG4RotationMatrix::SetRotationMatrixByRow(), doiPETAnalysis::SetSourcePosition(), G4SPSRandomGenerator::SetThetaBias(), G4VPhysicalVolume::SetTranslation(), G4RPGInelastic::SetUpChange(), G4SPSRandomGenerator::SetXBias(), G4SPSRandomGenerator::SetYBias(), G4SPSRandomGenerator::SetZBias(), G4RayShooter::Shoot(), G4EnclosingCylinder::ShouldMiss(), G4SteppingVerbose::ShowStep(), NeuronLoadDataFile::SingleNeuronSWCfile(), Par02Smearer::SmearGaussian(), G4GHEKinematicsVector::Smul(), G4GHEKinematicsVector::SmulAndUpdate(), G4Torus::SolveNumericJT(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4AttCheck::Standard(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), PHG4SteppingAction::StoreLocalCoordinate(), G4ScaledSolid::StreamInfo(), G4QGSDiffractiveExcitation::String(), G4GHEKinematicsVector::Sub3(), G4EllipticalTube::SurfaceNormal(), G4Box::SurfaceNormal(), G4VTwistedFaceted::SurfaceNormal(), G4Ellipsoid::SurfaceNormal(), G4Paraboloid::SurfaceNormal(), G4Tet::SurfaceNormal(), G4Hype::SurfaceNormal(), G4CutTubs::SurfaceNormal(), G4Trd::SurfaceNormal(), G4ExtrudedSolid::SurfaceNormal(), G4TwistedTubs::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4Para::SurfaceNormal(), G4Tubs::SurfaceNormal(), G4Torus::SurfaceNormal(), G4Cons::SurfaceNormal(), G4Sphere::SurfaceNormal(), G4Trap::SurfaceNormal(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), G4DiffuseElastic::ThetaLabToThetaCMS(), G4Torus::TorusRootsJT(), G4PolarizedBhabhaCrossSection::TotalXSection(), G4PolarizedMollerCrossSection::TotalXSection(), G4GHEKinematicsVector::Trac(), F04SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), G4MultiUnion::TransformLimits(), G4Voxelizer::TransformLimits(), G4BoundingEnvelope::TransformVertices(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), G4GDMLWriteStructure::TraverseVolumeTree(), G4Channeling::UpdateIntegrationStep(), G4Channeling::UpdateParameters(), G4SPSAngDistribution::UserDefAngPhi(), G4SPSAngDistribution::UserDefAngTheta(), G4SPSEneDistribution::UserEnergyHisto(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), EICG4dRICHTree::vectorToArray(), and G4SteppingVerbose::VerboseTrack().
double CLHEP::Hep3Vector::y () const inline
Referenced by G4GHEKinematicsVector::Add3(), EICG4LumiDetector::AddCAL(), G4HepRepFileSceneHandler::AddCompound(), EICG4LumiDetector::AddCuboid(), EICG4LumiDetector::AddExitWindowForV2(), EICG4LumiDetector::AddExitWindowForV3(), G4TessellatedSolid::AddFacet(), HistoManager::AddLeakingParticle(), EICG4LumiDetector::AddLumiExitWindow(), EICG4LumiDetector::AddLumiMag_MagCore(), EICG4LumiDetector::AddLumiMag_OuterVessel(), EICG4LumiDetector::AddLumiTracker(), EICG4LumiDetector::AddLumiWindow(), G4HepRepFileXMLWriter::addPoint(), EICG4LumiDetector::AddRecCone(), G4GMocrenFileSceneHandler::AddSolid(), EICG4LumiDetector::AddTriangularTrapezoid(), G4FTFModel::AdjustNucleonsAlgorithm_afterSampling(), G4MagHelicalStepper::AdvanceHelix(), G4VTwistSurface::AmIOnLeftSide(), XrayTelAnalysis::analyseStepping(), G4GHEKinematicsVector::Ang(), G4ReactionProduct::Angle(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4LowEIonFragmentation::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LFission::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4Box::ApproxSurfaceNormal(), G4EllipticalTube::ApproxSurfaceNormal(), G4Ellipsoid::ApproxSurfaceNormal(), G4ExtrudedSolid::ApproxSurfaceNormal(), G4Trd::ApproxSurfaceNormal(), G4EllipticalCone::ApproxSurfaceNormal(), G4CutTubs::ApproxSurfaceNormal(), G4Para::ApproxSurfaceNormal(), G4Torus::ApproxSurfaceNormal(), G4Tubs::ApproxSurfaceNormal(), G4Cons::ApproxSurfaceNormal(), G4Sphere::ApproxSurfaceNormal(), G4Trap::ApproxSurfaceNormal(), G4SPSEneDistribution::ArbEnergyHisto(), ClusteringAlgo::AreOnTheSameCluster(), AreOnTheSameCluster(), G4GDMLReadSolids::BooleanRead(), PHG4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::BooleanWrite(), G4DecayProducts::Boost(), G4NucleiModel::boundaryTransition(), G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ScaledSolid::BoundingLimits(), G4ReflectedSolid::BoundingLimits(), G4Box::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4Orb::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4UnionSolid::BoundingLimits(), G4SubtractionSolid::BoundingLimits(), G4GenericPolycone::BoundingLimits(), G4Hype::BoundingLimits(), G4Paraboloid::BoundingLimits(), G4TwistedTubs::BoundingLimits(), G4Polycone::BoundingLimits(), G4Polyhedra::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Trd::BoundingLimits(), G4GenericTrap::BoundingLimits(), G4EllipticalCone::BoundingLimits(), G4Para::BoundingLimits(), G4Tubs::BoundingLimits(), G4Torus::BoundingLimits(), G4Cons::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Sphere::BoundingLimits(), G4TessellatedSolid::BoundingLimits(), G4Trap::BoundingLimits(), G4Voxelizer::BuildBoundingBox(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4tgbRotationMatrix::BuildG4RotMatrixFrom6(), G4tgbRotationMatrix::BuildG4RotMatrixFrom9(), G4BoundingEnvelope::CalculateExtent(), G4EllipticalCone::CalculateExtent(), PHG4TTLSteppingAction::CalculateSensorHitIndices(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4NavigationLogger::CheckAndReportBadNormal(), G4BoundingEnvelope::CheckBoundingBox(), G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), G4PVPlacement::CheckOverlaps(), G4VParticleChange::CheckSecondary(), G4VoxelLimits::ClipToLimits(), G4PolarizedAnnihilationModel::ComputeCrossSectionPerElectron(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4ReplicaNavigation::ComputeTransformation(), DetectorConstruction0::Construct(), F04ElementField::Construct(), CML2Ph_FullWater::Construct(), RE02DetectorConstruction::Construct(), BeamLineMagnetDetector::ConstructMe(), EICG4LumiDetector::ConstructMe(), doiPETDetectorConstruction::ConstructPhantom(), TSDetectorConstruction::ConstructWorld(), CexmcSetup::ConvertToCrystalGeometry(), G4UIcommand::ConvertToString(), G4GHEKinematicsVector::CosAng(), G4TheRayTracer::CreateBitMap(), DNAParser::CreateCutSolid(), RawTowerCombiner::CreateNodes(), G4GenericTrap::CreatePolyhedron(), G3Division::CreatePVReplica(), G4FastStep::CreateSecondaryTrack(), G4PhysChemIO::FormattedText::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4TessellatedSolid::CreateVertexList(), G4PhysChemIO::FormattedText::CreateWaterMolecule(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), G4GHEKinematicsVector::Cross(), G4PionDecayMakeSpin::DaughterPolarization(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4PolarizedAnnihilationCrossSection::DefineCoefficients(), G4PolarizedComptonCrossSection::DefineCoefficients(), G4GHEKinematicsVector::Defs(), G4RPGReaction::Defs1(), G4GHEKinematicsVector::Defs1(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), CexmcTrackPointsDigitizer::Digitize(), G4VTwistSurface::DistanceToBoundary(), G4VTwistedFaceted::DistanceToIn(), G4EllipticalTube::DistanceToIn(), G4Box::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4TwistedTubs::DistanceToIn(), G4Hype::DistanceToIn(), G4CutTubs::DistanceToIn(), G4ExtrudedSolid::DistanceToIn(), G4Trd::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4Tubs::DistanceToIn(), G4Torus::DistanceToIn(), G4Para::DistanceToIn(), G4Cons::DistanceToIn(), G4Sphere::DistanceToIn(), G4Trap::DistanceToIn(), G4TessellatedSolid::DistanceToInNoVoxels(), G4VTwistedFaceted::DistanceToOut(), G4EllipticalTube::DistanceToOut(), G4Box::DistanceToOut(), G4IntersectionSolid::DistanceToOut(), G4UnionSolid::DistanceToOut(), G4Orb::DistanceToOut(), G4SubtractionSolid::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4GenericTrap::DistanceToOut(), G4Hype::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4CutTubs::DistanceToOut(), G4ExtrudedSolid::DistanceToOut(), G4Trd::DistanceToOut(), G4ReplicaNavigation::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4Tubs::DistanceToOut(), G4Torus::DistanceToOut(), G4Para::DistanceToOut(), G4Cons::DistanceToOut(), G4Sphere::DistanceToOut(), G4Trap::DistanceToOut(), G4TessellatedSolid::DistanceToOutNoVoxels(), G4ReplicaNavigation::DistanceToOutPhi(), G4ReplicaNavigation::DistanceToOutRad(), G4TwistTrapFlatSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), G4GenericTrap::DistToPlane(), G4GenericTrap::DistToTriangle(), G4GHEKinematicsVector::Dot(), G4GHEKinematicsVector::Dot4(), Par01EnergySpot::Draw(), G4LatticeLogical::Dump_NMap(), G4tgbGeometryDumper::DumpBooleanVolume(), G4ParticleChangeForMSC::DumpInfo(), G4ParticleChangeForLoss::DumpInfo(), G4ParticleChange::DumpInfo(), G4FastStep::DumpInfo(), G4tgbGeometryDumper::DumpPVPlacement(), DicomBeamControlPoint::DumpToFile(), TrackerSD::EndOfEvent(), ExGflashEventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), FW::Geant4::MMEventAction::EndOfEventAction(), G4SPSEneDistribution::EpnEnergyHisto(), G4VSolid::EstimateSurfaceArea(), G4EqEMFieldWithSpin::EvaluateRhsGivenB(), G4RepleteEofM::EvaluateRhsGivenB(), G4EqEMFieldWithEDM::EvaluateRhsGivenB(), G4Mag_SpinEqRhs::EvaluateRhsGivenB(), G4MultiUnion::Extent(), G4PolyPhiFace::Extent(), PHG4OuterHcalSteppingAction::FieldChecker(), Analysis::FillDose(), Analysis::FillIncident(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), EICG4B0ECALSteppingAction::FindTowerIndexFromPosition(), EICG4BwdSteppingAction::FindTowerIndexFromPosition(), PHG4ForwardDualReadoutSteppingAction::FindTowerIndexFromPosition(), EICG4B0SteppingAction::FindTowerIndexFromPosition(), G4BestUnit::G4BestUnit(), G4CutTubs::G4CutTubs(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4GHEKinematicsVector::G4GHEKinematicsVector(), G4Para::G4Para(), G4PolyPhiFace::G4PolyPhiFace(), G4RandomPointOnEllipsoid(), G4UniformElectricField::G4UniformElectricField(), G4UniformGravityField::G4UniformGravityField(), G4UniformMagField::G4UniformMagField(), G4VPhysicalVolume::G4VPhysicalVolume(), PHHepMCGenHelper::generate_vertx_with_bunch_interaction(), G4SPSAngDistribution::GenerateBeamFlux(), G4SPSAngDistribution::GenerateCosineLawFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), G4SPSPosDistribution::GeneratePointsInBeam(), G4SPSPosDistribution::GeneratePointsInPlane(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), TSPrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GeneratePrimaries(), MedicalBeam::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), G4PrimaryTransformer::GenerateSingleTrack(), G4CascadeFinalStateAlgorithm::GenerateTwoBody(), G4SPSAngDistribution::GenerateUserDefFlux(), ClusterJetInput::get_input(), EICG4dRICHHit::get_y(), G4TwistTrapFlatSide::GetAreaCode(), G4TwistTubsFlatSide::GetBoundaryMax(), G4TwistTubsHypeSide::GetBoundaryMax(), G4TwistTubsFlatSide::GetBoundaryMin(), G4TwistTubsHypeSide::GetBoundaryMin(), G4Voxelizer::GetCandidatesVoxelArray(), G4ScaledSolid::GetCubicVolume(), G4MultiUnion::GetCubicVolume(), G4Trap::GetCubicVolume(), G4CutTubs::GetCutZ(), G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint(), G4ChannelingECHARM::GetEC(), G4Tet::GetExtent(), G4GenericTrap::GetExtent(), G4EllipticalCone::GetExtent(), G4TessellatedSolid::GetExtent(), G4TwistTrapFlatSide::GetFacets(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistBoxSide::GetFacets(), G4TwistTrapParallelSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), G4TwistTrapAlphaSide::GetFacets(), PyG4MagneticField::GetFieldValue(), G4CachedMagneticField::GetFieldValue(), G4QuadrupoleMagField::GetFieldValue(), G4BFieldIntegrationDriver::GetFieldValue(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4CutTubs::GetMaxMinZ(), G4TessellatedSolid::GetMaxYExtent(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4TessellatedSolid::GetMinYExtent(), G4TwistTubsHypeSide::GetNormal(), G4PolarizationHelper::GetParticleFrameX(), G4PolarizationHelper::GetParticleFrameY(), G4PolyconeSide::GetPhi(), G4PolyhedraSide::GetPhi(), G4TwistBoxSide::GetPhiUAtX(), G4TwistTrapParallelSide::GetPhiUAtX(), G4TwistTrapAlphaSide::GetPhiUAtX(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4PrimaryParticle::GetPy(), G4LivermorePolarizedComptonModel::GetRandomPolarization(), G4LivermorePolarizedGammaConversionModel::GetRandomPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetRandomPolarization(), G4LowEnergyPolarizedCompton::GetRandomPolarization(), G4LowEPPolarizedComptonModel::GetRandomPolarization(), G4PartialPhantomParameterisation::GetReplicaNo(), G4PhantomParameterisation::GetReplicaNo(), G4ScoringBox::GetReplicaPosition(), G4tgrUtils::GetRotationFromDirection(), G4GDMLReadDefine::GetRotationMatrix(), G4ScaledSolid::GetScaleTransform(), G4PolarizationHelper::GetSpinInPRF(), G4Scatterer::GetTimeToInteraction(), TSDetectorConstruction::GetTotalTargets(), G4ReactionProduct::GetYPositionInNucleus(), ClusterSBPoints::HasInBarycenter(), G4Pythia6Decayer::ImportDecayProducts(), G4GHEKinematicsVector::Impu(), G4PolarizedBhabhaCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), G4PolarizedMollerCrossSection::Initialize(), G4PolarizedComptonCrossSection::Initialize(), G4EllipticalTube::Inside(), G4Box::Inside(), G4VTwistedFaceted::Inside(), G4Ellipsoid::Inside(), G4Hype::Inside(), G4PolyPhiFace::Inside(), G4CutTubs::Inside(), G4Trd::Inside(), G4ExtrudedSolid::Inside(), G4TwistedTubs::Inside(), G4EllipticalCone::Inside(), G4Torus::Inside(), G4ReplicaNavigation::Inside(), G4Tubs::Inside(), G4Para::Inside(), G4Cons::Inside(), G4Sphere::Inside(), G4Trap::Inside(), G4PolyPhiFace::InsideEdgesExact(), G4TessellatedSolid::InsideNoVoxels(), G4GenericTrap::InsidePolygone(), G4TessellatedSolid::InsideVoxels(), G4PolyconeSide::Intersect(), G4Hype::IntersectHype(), G4ErrorCylSurfaceTarget::IntersectLocal(), F04SimpleSolenoid::IsOutside(), G4GenericTrap::IsSegCrossingZ(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), F04SimpleSolenoid::IsWithin(), G4QMDGroundStateNucleus::killCMMotionAndAngularM(), G4IntersectingCone::LineHitsCone1(), G4IntersectingCone::LineHitsCone2(), G4PolyhedraSide::LineHitsSegments(), G4VScoringMesh::List(), G4GHEKinematicsVector::Lor(), G4ReactionProduct::Lorentz(), CCalMagneticField::MagneticField(), PHG4RICHSteppingAction::MakeHit(), G4Trap::MakePlane(), G4Para::MakePlanes(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4Voxelizer::MinDistanceToBox(), G4GDMLWriteSolids::MultiUnionWrite(), G4EnclosingCylinder::MustBeOutside(), G4PolyconeSide::Normal(), G4GHEKinematicsVector::Norz(), G4GDMLWriteSolids::G4ThreeVectorCompare::operator()(), PHG4GDMLWriteSolids::G4ThreeVectorCompare::operator()(), operator+(), operator-(), CLHEP::operator/(), operator<<(), CLHEP::operator<<(), G4GHEKinematicsVector::operator=(), G4VoxelLimits::OutCode(), G4TessellatedSolid::OutsideOfExtent(), G4StokesVector::p2(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), G4GDMLReadParamvol::ParametersRead(), G4PhotoElectricAngularGeneratorPolarized::PerpendicularVector(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4STRead::PhysvolRead(), G4GDMLReadStructure::PhysvolRead(), PHG4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteStructure::PhysvolWrite(), G4PolyconeSide::PointOnCone(), G4StokesVector::PolDiv(), G4StokesVector::PolSqr(), G4StokesVector::PolSqrt(), G4GDMLWriteDefine::Position_vectorWrite(), PHG4GDMLWriteDefine::Position_vectorWrite(), G4VTransitionRadiation::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), B5DriftChamberHit::Print(), G4PrimaryParticle::Print(), G4GHEKinematicsVector::Print(), G4MagInt_Driver::PrintStat_Aux(), G4Navigator::PrintState(), G4ITNavigator1::PrintState(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), ExN04MuonSD::ProcessHits(), ScreenSD::ProcessHits(), RE05MuonSD::ProcessHits(), PhantomSD::ProcessHits(), UltraPMTSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4ExtrudedSolid::ProjectPoint(), G4ErrorFreeTrajState::PropagateError(), G4ErrorFreeTrajState::PropagateErrorMSC(), G4MoleculeShoot::RandomPosInBox(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4STRead::Read(), doiPETAnalysis::ReadOut(), CexmcReconstructor::ReconstructEntryPoints(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4GDMLReadSolids::ReflectedSolidRead(), G4QGSParticipants::ReggeonCascade(), G4FTFModel::ReggeonCascade(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4MultiLevelLocator::ReportFieldValue(), CLHEP::HepRotation::rotate(), CLHEP::HepRotation::rotateAxes(), CexmcSetup::RotateMatrix(), G4StatMFChannel::RotateMomentum(), rotateUz(), G4GDMLWriteDefine::Rotation_vectorWrite(), PHG4GDMLWriteDefine::Rotation_vectorWrite(), G4TessellatedSolid::SafetyFromInside(), G4TessellatedSolid::SafetyFromOutside(), G4MultiUnion::SafetyFromOutsideNumberNode(), G4DNABornIonisationModel2::SampleSecondaries(), G4DNABornIonisationModel1::SampleSecondaries(), G4eeTo3PiModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4GammaTransition::SampleTransition(), G4QGSParticipants::SamplingNucleonKinematics(), G4FTFModel::SamplingNucleonKinematics(), Par02Output::SaveTrack(), G4GDMLWriteDefine::Scale_vectorWrite(), PHG4GDMLWriteDefine::Scale_vectorWrite(), G4GDMLReadSolids::ScaledSolidRead(), G4Scatterer::Scatter(), CLHEP::HepBoost::set(), CLHEP::HepRotation::set(), G4UIcmdWith3Vector::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), G4GHEKinematicsVector::SetEnergyAndUpdate(), G4SPSRandomGenerator::SetEnergyBias(), G4UniformMagField::SetFieldValue(), G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), setMag(), G4GHEKinematicsVector::SetMassAndUpdate(), CexmcProductionModelMessenger::SetNewValue(), CexmcEnergyDepositDigitizerMessenger::SetNewValue(), G4BlineTracerMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4RDPhotoElectricAngularGeneratorPolarized::SetPerpendicularVector(), G4LivermorePolarizedComptonModel::SetPerpendicularVector(), G4LivermorePolarizedGammaConversionModel::SetPerpendicularVector(), G4LivermorePolarizedPhotoElectricGDModel::SetPerpendicularVector(), G4LowEnergyPolarizedCompton::SetPerpendicularVector(), G4LowEPPolarizedComptonModel::SetPerpendicularVector(), G4SPSRandomGenerator::SetPhiBias(), G4PrimaryParticle::SetPolarization(), G4SPSRandomGenerator::SetPosPhiBias(), G4SPSRandomGenerator::SetPosThetaBias(), G3toG4RotationMatrix::SetRotationMatrixByCol(), G3toG4RotationMatrix::SetRotationMatrixByRow(), doiPETAnalysis::SetSourcePosition(), G4SPSRandomGenerator::SetThetaBias(), G4VPhysicalVolume::SetTranslation(), G4RPGInelastic::SetUpChange(), G4SPSRandomGenerator::SetXBias(), G4SPSRandomGenerator::SetYBias(), G4SPSRandomGenerator::SetZBias(), G4RayShooter::Shoot(), G4EnclosingCylinder::ShouldMiss(), G4SteppingVerbose::ShowStep(), NeuronLoadDataFile::SingleNeuronSWCfile(), Par02Smearer::SmearGaussian(), G4GHEKinematicsVector::Smul(), G4GHEKinematicsVector::SmulAndUpdate(), G4Torus::SolveNumericJT(), G4LundStringFragmentation::SplitEandP(), G4QGSMFragmentation::SplitEandP(), G4AttCheck::Standard(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), PHG4SteppingAction::StoreLocalCoordinate(), G4ScaledSolid::StreamInfo(), G4QGSDiffractiveExcitation::String(), G4GHEKinematicsVector::Sub3(), G4EllipticalTube::SurfaceNormal(), G4Box::SurfaceNormal(), G4VTwistedFaceted::SurfaceNormal(), G4Ellipsoid::SurfaceNormal(), G4Paraboloid::SurfaceNormal(), G4Tet::SurfaceNormal(), G4Hype::SurfaceNormal(), G4CutTubs::SurfaceNormal(), G4Trd::SurfaceNormal(), G4ExtrudedSolid::SurfaceNormal(), G4TwistedTubs::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4Tubs::SurfaceNormal(), G4Para::SurfaceNormal(), G4Torus::SurfaceNormal(), G4Cons::SurfaceNormal(), G4Sphere::SurfaceNormal(), G4Trap::SurfaceNormal(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), G4DiffuseElastic::ThetaLabToThetaCMS(), G4Torus::TorusRootsJT(), G4PolarizedMollerCrossSection::TotalXSection(), G4PolarizedBhabhaCrossSection::TotalXSection(), G4GHEKinematicsVector::Trac(), F04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), G4MultiUnion::TransformLimits(), G4Voxelizer::TransformLimits(), G4BoundingEnvelope::TransformVertices(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), G4GDMLWriteStructure::TraverseVolumeTree(), G4Channeling::UpdateIntegrationStep(), G4SPSAngDistribution::UserDefAngPhi(), G4SPSAngDistribution::UserDefAngTheta(), G4SPSEneDistribution::UserEnergyHisto(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), CCalSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), EICG4dRICHTree::vectorToArray(), and G4SteppingVerbose::VerboseTrack().
double CLHEP::Hep3Vector::z () const inline
Referenced by G4GHEKinematicsVector::Add3(), EICG4LumiDetector::AddCAL(), G4HepRepFileSceneHandler::AddCompound(), EICG4LumiDetector::AddCuboid(), EICG4LumiDetector::AddExitWindowForV2(), EICG4LumiDetector::AddExitWindowForV3(), G4TessellatedSolid::AddFacet(), F04FocusSolenoid::AddFieldValue(), HistoManager::AddLeakingParticle(), EICG4LumiDetector::AddLumiExitWindow(), EICG4LumiDetector::AddLumiMag_MagCore(), EICG4LumiDetector::AddLumiMag_OuterVessel(), EICG4LumiDetector::AddLumiTracker(), EICG4LumiDetector::AddLumiWindow(), G4HepRepFileXMLWriter::addPoint(), EICG4LumiDetector::AddRecCone(), G4GMocrenFileSceneHandler::AddSolid(), HistoManager::AddTargetStep(), G4MagHelicalStepper::AdvanceHelix(), XrayTelAnalysis::analyseStepping(), G4GHEKinematicsVector::Ang(), G4ReactionProduct::Angle(), G4ChargeExchange::ApplyYourself(), G4NeutronRadCapture::ApplyYourself(), G4QMDReaction::ApplyYourself(), G4LFission::ApplyYourself(), G4LMsdGenerator::ApplyYourself(), G4Box::ApproxSurfaceNormal(), G4EllipticalTube::ApproxSurfaceNormal(), G4Ellipsoid::ApproxSurfaceNormal(), G4ExtrudedSolid::ApproxSurfaceNormal(), G4Trd::ApproxSurfaceNormal(), G4EllipticalCone::ApproxSurfaceNormal(), G4Para::ApproxSurfaceNormal(), G4Torus::ApproxSurfaceNormal(), G4Tubs::ApproxSurfaceNormal(), G4Cons::ApproxSurfaceNormal(), G4Sphere::ApproxSurfaceNormal(), G4Trap::ApproxSurfaceNormal(), ClusteringAlgo::AreOnTheSameCluster(), AreOnTheSameCluster(), G4GDMLReadSolids::BooleanRead(), PHG4GDMLWriteSolids::BooleanWrite(), G4GDMLWriteSolids::BooleanWrite(), G4DecayProducts::Boost(), G4NucleiModel::boundaryTransition(), G4BoundingEnvelope::BoundingBoxVsVoxelLimits(), G4ScaledSolid::BoundingLimits(), G4ReflectedSolid::BoundingLimits(), G4Box::BoundingLimits(), G4DisplacedSolid::BoundingLimits(), G4Orb::BoundingLimits(), G4UnionSolid::BoundingLimits(), G4IntersectionSolid::BoundingLimits(), G4SubtractionSolid::BoundingLimits(), G4GenericPolycone::BoundingLimits(), G4Hype::BoundingLimits(), G4Paraboloid::BoundingLimits(), G4TwistedTubs::BoundingLimits(), G4Polycone::BoundingLimits(), G4Polyhedra::BoundingLimits(), G4CutTubs::BoundingLimits(), G4Trd::BoundingLimits(), G4GenericTrap::BoundingLimits(), G4EllipticalCone::BoundingLimits(), G4Para::BoundingLimits(), G4Tubs::BoundingLimits(), G4Torus::BoundingLimits(), G4Cons::BoundingLimits(), G4ExtrudedSolid::BoundingLimits(), G4Sphere::BoundingLimits(), G4TessellatedSolid::BoundingLimits(), G4Trap::BoundingLimits(), G4Voxelizer::BuildBoundingBox(), G4ErrorSurfaceTrajState::BuildErrorMatrix(), G4tgbRotationMatrix::BuildG4RotMatrixFrom6(), G4tgbRotationMatrix::BuildG4RotMatrixFrom9(), G4QMDReaction::calcOffSetOfCollision(), G4BoundingEnvelope::CalculateExtent(), G4CutTubs::CalculateExtent(), G4EllipticalCone::CalculateExtent(), PHG4TTLSteppingAction::CalculateSensorHitIndices(), G4QMDCollision::CalFinalStateOfTheBinaryCollisionJQMD(), G4NavigationLogger::CheckAndReportBadNormal(), G4BoundingEnvelope::CheckBoundingBox(), G4ParticleChangeForGamma::CheckIt(), G4ParticleChangeForMSC::CheckIt(), G4ParticleChangeForLoss::CheckIt(), G4ParticleChangeForDecay::CheckIt(), G4ParticleChange::CheckIt(), G4PVPlacement::CheckOverlaps(), G4VParticleChange::CheckSecondary(), G4VoxelLimits::ClipToLimits(), G4PolarizedComptonModel::ComputeCrossSectionPerAtom(), G4PolarizedAnnihilationModel::ComputeCrossSectionPerElectron(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4ReplicaNavigation::ComputeTransformation(), G4ParameterisationParaZ::ComputeTransformation(), DetectorConstruction0::Construct(), F04ElementField::Construct(), CML2Ph_FullWater::Construct(), RE02DetectorConstruction::Construct(), BeamLineMagnetDetector::ConstructMe(), EICG4LumiDetector::ConstructMe(), doiPETDetectorConstruction::ConstructPhantom(), TSDetectorConstruction::ConstructWorld(), G4UIcommand::ConvertToString(), G4GHEKinematicsVector::CosAng(), G4TheRayTracer::CreateBitMap(), DNAParser::CreateCutSolid(), RawTowerCombiner::CreateNodes(), G4FastStep::CreateSecondaryTrack(), G4PhysChemIO::FormattedText::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4GenericTrap::CreateTessellatedSolid(), G4TessellatedSolid::CreateVertexList(), G4PhysChemIO::FormattedText::CreateWaterMolecule(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), G4GHEKinematicsVector::Cross(), CCaloSD::curve_LY(), G4PionDecayMakeSpin::DaughterPolarization(), G4DalitzDecayChannel::DecayIt(), G4TauLeptonicDecayChannel::DecayIt(), G4MuonRadiativeDecayChannelWithSpin::DecayIt(), G4PolarizedAnnihilationCrossSection::DefineCoefficients(), G4PolarizedComptonCrossSection::DefineCoefficients(), G4GHEKinematicsVector::Defs(), G4RPGReaction::Defs1(), G4GHEKinematicsVector::Defs1(), G4PolyPhiFace::Distance(), G4PolyconeSide::DistanceAway(), G4VTwistSurface::DistanceToBoundary(), G4VTwistedFaceted::DistanceToIn(), G4EllipticalTube::DistanceToIn(), G4Box::DistanceToIn(), G4Ellipsoid::DistanceToIn(), G4Paraboloid::DistanceToIn(), G4TwistedTubs::DistanceToIn(), G4GenericTrap::DistanceToIn(), G4Hype::DistanceToIn(), G4CutTubs::DistanceToIn(), G4ExtrudedSolid::DistanceToIn(), G4Trd::DistanceToIn(), G4EllipticalCone::DistanceToIn(), G4Tubs::DistanceToIn(), G4Para::DistanceToIn(), G4Torus::DistanceToIn(), G4Cons::DistanceToIn(), G4Sphere::DistanceToIn(), G4Trap::DistanceToIn(), G4TessellatedSolid::DistanceToInNoVoxels(), G4VTwistedFaceted::DistanceToOut(), G4EllipticalTube::DistanceToOut(), G4Box::DistanceToOut(), G4UnionSolid::DistanceToOut(), G4Orb::DistanceToOut(), G4IntersectionSolid::DistanceToOut(), G4SubtractionSolid::DistanceToOut(), G4Ellipsoid::DistanceToOut(), G4Paraboloid::DistanceToOut(), G4GenericTrap::DistanceToOut(), G4Hype::DistanceToOut(), G4TwistedTubs::DistanceToOut(), G4CutTubs::DistanceToOut(), G4ExtrudedSolid::DistanceToOut(), G4Trd::DistanceToOut(), G4EllipticalCone::DistanceToOut(), G4Tubs::DistanceToOut(), G4Torus::DistanceToOut(), G4Para::DistanceToOut(), G4Cons::DistanceToOut(), G4Sphere::DistanceToOut(), G4Trap::DistanceToOut(), G4TessellatedSolid::DistanceToOutNoVoxels(), G4ReplicaNavigation::DistanceToOutRad(), G4TwistTrapFlatSide::DistanceToSurface(), G4TwistBoxSide::DistanceToSurface(), G4TwistTrapAlphaSide::DistanceToSurface(), G4TwistTrapParallelSide::DistanceToSurface(), G4TwistTubsFlatSide::DistanceToSurface(), G4TwistTubsSide::DistanceToSurface(), G4TwistTubsHypeSide::DistanceToSurface(), G4GenericTrap::DistToPlane(), G4GenericTrap::DistToTriangle(), G4GHEKinematicsVector::Dot(), G4GHEKinematicsVector::Dot4(), Par01EnergySpot::Draw(), G4LatticeLogical::Dump_NMap(), G4tgbGeometryDumper::DumpBooleanVolume(), G4ParticleChangeForMSC::DumpInfo(), G4ParticleChangeForLoss::DumpInfo(), G4ParticleChange::DumpInfo(), G4FastStep::DumpInfo(), G4tgbGeometryDumper::DumpPVPlacement(), DicomBeamControlPoint::DumpToFile(), TrackerSD::EndOfEvent(), ExGflashEventAction::EndOfEventAction(), CCalEventAction::EndOfEventAction(), FW::Geant4::MMEventAction::EndOfEventAction(), G4VSolid::EstimateSurfaceArea(), G4EqEMFieldWithSpin::EvaluateRhsGivenB(), G4RepleteEofM::EvaluateRhsGivenB(), G4EqEMFieldWithEDM::EvaluateRhsGivenB(), G4Mag_SpinEqRhs::EvaluateRhsGivenB(), G4MultiUnion::Extent(), G4PolyPhiFace::Extent(), G4PolyconeSide::Extent(), G4PolyhedraSide::Extent(), PHG4OuterHcalSteppingAction::FieldChecker(), Analysis::FillDose(), G4QGSParticipants::FinalizeKinematics(), G4FTFModel::FinalizeKinematics(), G4StokesVector::FlipP3(), G4BestUnit::G4BestUnit(), G4CutTubs::G4CutTubs(), G4ErrorFreeTrajState::G4ErrorFreeTrajState(), G4Fancy3DNucleusHelperForSortInZ(), G4GHEKinematicsVector::G4GHEKinematicsVector(), G4Para::G4Para(), G4RandomPointOnEllipsoid(), G4UniformElectricField::G4UniformElectricField(), G4UniformGravityField::G4UniformGravityField(), G4UniformMagField::G4UniformMagField(), G4VPhysicalVolume::G4VPhysicalVolume(), PHHepMCGenHelper::generate_vertx_with_bunch_interaction(), G4SPSAngDistribution::GenerateBeamFlux(), GB03BOptnSplitOrKillOnBoundary::GenerateBiasingFinalState(), GB05BOptnSplitAndKillByCrossSection::GenerateBiasingFinalState(), G4SPSAngDistribution::GenerateCosineLawFlux(), G4SPSAngDistribution::GenerateIsotropicFlux(), G4SPSPosDistribution::GeneratePointsInBeam(), G4SPSPosDistribution::GeneratePointsInPlane(), G4SPSPosDistribution::GeneratePointsInVolume(), G4SPSPosDistribution::GeneratePointsOnSurface(), PHG4PrimaryGeneratorAction::GeneratePrimaries(), G4RTPrimaryGeneratorAction::GeneratePrimaries(), Dicom2PrimaryGeneratorAction::GeneratePrimaries(), TSPrimaryGeneratorAction::GeneratePrimaries(), FFPrimaryGeneratorAction::GeneratePrimaries(), MedicalBeam::GeneratePrimaries(), G4AdjointPrimaryGeneratorAction::GeneratePrimaries(), DMXParticleSource::GeneratePrimaryVertex(), G4ParticleGun::GeneratePrimaryVertex(), G4SingleParticleSource::GeneratePrimaryVertex(), G4PrimaryTransformer::GenerateSingleTrack(), G4CascadeFinalStateAlgorithm::GenerateTwoBody(), G4SPSAngDistribution::GenerateUserDefFlux(), ClusterJetInput::get_input(), EICG4dRICHHit::get_z(), G4TwistBoxSide::GetAreaCode(), G4TwistTrapParallelSide::GetAreaCode(), G4TwistTrapAlphaSide::GetAreaCode(), G4TwistTubsHypeSide::GetAreaCode(), G4TwistTubsSide::GetAreaCode(), G4VTwistSurface::GetBoundaryAtPZ(), G4ChannelingMaterialData::GetBR(), G4Voxelizer::GetCandidatesVoxelArray(), G4ScaledSolid::GetCubicVolume(), G4MultiUnion::GetCubicVolume(), G4Trap::GetCubicVolume(), G4CutTubs::GetCutZ(), G4ErrorPlaneSurfaceTarget::GetDistanceFromPoint(), G4Tet::GetExtent(), G4GenericTrap::GetExtent(), G4EllipticalCone::GetExtent(), G4TessellatedSolid::GetExtent(), G4TwistTrapFlatSide::GetFacets(), G4TwistTubsFlatSide::GetFacets(), G4TwistTubsSide::GetFacets(), G4TwistBoxSide::GetFacets(), G4TwistTrapParallelSide::GetFacets(), G4TwistTubsHypeSide::GetFacets(), G4TwistTrapAlphaSide::GetFacets(), PyG4MagneticField::GetFieldValue(), G4CachedMagneticField::GetFieldValue(), G4QuadrupoleMagField::GetFieldValue(), G4BFieldIntegrationDriver::GetFieldValue(), G4FTFParticipants::GetList(), G4TessellatedSolid::GetMaxZExtent(), G4SynchrotronRadiation::GetMeanFreePath(), G4SynchrotronRadiationInMat::GetMeanFreePath(), G4TessellatedSolid::GetMinZExtent(), G4TwistTubsSide::GetNormal(), G4TwistTubsHypeSide::GetNormal(), G4PolarizationHelper::GetParticleFrameX(), G4PolyconeSide::GetPhi(), G4PolyhedraSide::GetPhi(), G4TwistBoxSide::GetPhiUAtX(), G4TwistTrapParallelSide::GetPhiUAtX(), G4TwistTrapAlphaSide::GetPhiUAtX(), G4SynchrotronRadiationInMat::GetPhotonEnergy(), G4PrimaryParticle::GetPz(), G4LivermorePolarizedComptonModel::GetRandomPolarization(), G4LivermorePolarizedGammaConversionModel::GetRandomPolarization(), G4LivermorePolarizedPhotoElectricGDModel::GetRandomPolarization(), G4LowEnergyPolarizedCompton::GetRandomPolarization(), G4LowEPPolarizedComptonModel::GetRandomPolarization(), G4PartialPhantomParameterisation::GetReplicaNo(), G4PhantomParameterisation::GetReplicaNo(), G4ScoringBox::GetReplicaPosition(), G4TwistTubsHypeSide::GetRhoAtPZ(), G4tgrUtils::GetRotationFromDirection(), G4GDMLReadDefine::GetRotationMatrix(), G4ScaledSolid::GetScaleTransform(), G4PolarizationHelper::GetSpinInPRF(), G4Scatterer::GetTimeToInteraction(), TSDetectorConstruction::GetTotalTargets(), G4ReactionProduct::GetZPositionInNucleus(), ClusterSBPoints::HasInBarycenter(), G4Pythia6Decayer::ImportDecayProducts(), G4GHEKinematicsVector::Impu(), G4FTFModel::Init(), G4PolarizedPEEffectCrossSection::Initialize(), G4PolarizedBhabhaCrossSection::Initialize(), G4PolarizedPairProductionCrossSection::Initialize(), G4PolarizedBremsstrahlungCrossSection::Initialize(), G4PolarizedMollerCrossSection::Initialize(), G4PolarizedAnnihilationCrossSection::Initialize(), G4PolarizedComptonCrossSection::Initialize(), G4EllipticalTube::Inside(), G4UnionSolid::Inside(), G4Box::Inside(), G4VTwistedFaceted::Inside(), G4Ellipsoid::Inside(), G4Paraboloid::Inside(), G4GenericTrap::Inside(), G4Hype::Inside(), G4PolyPhiFace::Inside(), G4Trd::Inside(), G4ExtrudedSolid::Inside(), G4TwistedTubs::Inside(), G4Torus::Inside(), G4EllipticalCone::Inside(), G4Para::Inside(), G4Tubs::Inside(), G4Cons::Inside(), G4Sphere::Inside(), G4Trap::Inside(), G4PolyPhiFace::InsideEdgesExact(), G4TessellatedSolid::InsideNoVoxels(), G4TessellatedSolid::InsideVoxels(), G4PolyPhiFace::Intersect(), G4Hype::IntersectHype(), F04SimpleSolenoid::IsOutside(), G4GenericTrap::IsSegCrossingZ(), G4PSSphereSurfaceCurrent::IsSelectedSurface(), G4PSCylinderSurfaceFlux::IsSelectedSurface(), G4PSCylinderSurfaceCurrent::IsSelectedSurface(), G4PSFlatSurfaceCurrent::IsSelectedSurface(), G4PSSphereSurfaceFlux::IsSelectedSurface(), G4PSFlatSurfaceFlux::IsSelectedSurface(), F04SimpleSolenoid::IsWithin(), G4QMDGroundStateNucleus::killCMMotionAndAngularM(), G4IntersectingCone::LineHitsCone1(), G4IntersectingCone::LineHitsCone2(), G4VScoringMesh::List(), G4GHEKinematicsVector::Lor(), G4ReactionProduct::Lorentz(), CCalMagneticField::MagneticField(), G4GenericTrap::MakeDownFacet(), G4ExtrudedSolid::MakeDownFacet(), PHG4RICHSteppingAction::MakeHit(), G4Trap::MakePlane(), G4Para::MakePlanes(), G4GenericTrap::MakeUpFacet(), G4ExtrudedSolid::MakeUpFacet(), G4PhaseSpaceDecayChannel::ManyBodyDecayIt(), G4GeneralPhaseSpaceDecay::ManyBodyDecayIt(), G4Voxelizer::MinDistanceToBox(), G4GDMLWriteSolids::MultiUnionWrite(), G4EnclosingCylinder::MustBeOutside(), G4PolyPhiFace::Normal(), G4TessellatedSolid::Normal(), G4GenericTrap::NormalToPlane(), G4GHEKinematicsVector::Norz(), G4GDMLWriteSolids::G4ThreeVectorCompare::operator()(), PHG4GDMLWriteSolids::G4ThreeVectorCompare::operator()(), operator+(), operator-(), CLHEP::operator/(), DNAParser::Molecule::operator<(), operator<<(), CLHEP::operator<<(), G4GHEKinematicsVector::operator=(), G4VoxelLimits::OutCode(), G4TessellatedSolid::OutsideOfExtent(), G4StokesVector::p3(), G4GDMLWriteParamvol::Para_dimensionsWrite(), PHG4GDMLWriteParamvol::Para_dimensionsWrite(), G4GDMLReadParamvol::ParametersRead(), G4PhotoElectricAngularGeneratorPolarized::PerpendicularVector(), G4PhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4RDPhotoElectricAngularGeneratorPolarized::PhotoElectronRotationMatrix(), G4STRead::PhysvolRead(), G4GDMLReadStructure::PhysvolRead(), PHG4GDMLWriteStructure::PhysvolWrite(), G4GDMLWriteStructure::PhysvolWrite(), G4PolyconeSide::PointOnCone(), G4StokesVector::PolDiv(), G4StokesVector::PolSqr(), G4StokesVector::PolSqrt(), G4GDMLWriteDefine::Position_vectorWrite(), PHG4GDMLWriteDefine::Position_vectorWrite(), PrtOpBoundaryProcess::PostStepDoIt(), G4EicDircOpBoundaryProcess::PostStepDoIt(), G4Channeling::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4hImpactIonisation::PostStepDoIt(), G4ErrorMagFieldLimitProcess::PostStepGetPhysicalInteractionLength(), G4AdjointTrackingAction::PostUserTrackingAction(), F04TrackingAction::PreUserTrackingAction(), WLSTrackingAction::PreUserTrackingAction(), G4PrimaryParticle::Print(), G4GHEKinematicsVector::Print(), G4CascadeHistory::PrintEntry(), G4MagInt_Driver::PrintStat_Aux(), G4Navigator::PrintState(), G4ITNavigator1::PrintState(), G4PropagatorInField::printStatus(), G4VIntersectionLocator::printStatus(), ExN04MuonSD::ProcessHits(), RE05MuonSD::ProcessHits(), PhantomSD::ProcessHits(), UltraPMTSD::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), G4TwistTubsSide::ProjectAtPXPZ(), G4ExtrudedSolid::ProjectPoint(), G4ErrorFreeTrajState::PropagateError(), pseudoRapidity(), G4MoleculeShoot::RandomPosInBox(), G4RPGTwoCluster::ReactionStage(), G4RPGFragmentation::ReactionStage(), G4STRead::Read(), doiPETAnalysis::ReadOut(), CexmcReconstructor::ReconstructEntryPoints(), G4RPGFragmentation::ReduceEnergiesOfSecondaries(), G4GDMLReadSolids::ReflectedSolidRead(), G4AdjointSimManager::RegisterAtEndOfAdjointTrack(), G4PathFinder::ReLocate(), G4ITPathFinder::ReLocate(), G4MultiLevelLocator::ReportFieldValue(), CLHEP::HepRotation::rotate(), CLHEP::HepRotation::rotateAxes(), CexmcSetup::RotateMatrix(), G4StatMFChannel::RotateMomentum(), rotateUz(), G4GDMLWriteDefine::Rotation_vectorWrite(), PHG4GDMLWriteDefine::Rotation_vectorWrite(), G4TessellatedSolid::SafetyFromInside(), G4TessellatedSolid::SafetyFromOutside(), G4MultiUnion::SafetyFromOutsideNumberNode(), G4DNABornIonisationModel1::SampleSecondaries(), G4DNABornIonisationModel2::SampleSecondaries(), G4eeTo3PiModel::SampleSecondaries(), G4DNAEmfietzoglouIonisationModel::SampleSecondaries(), G4DNACPA100ElasticModel::SampleSecondaries(), G4DNACPA100ExcitationModel::SampleSecondaries(), G4PolarizedMollerBhabhaModel::SampleSecondaries(), G4DNACPA100IonisationModel::SampleSecondaries(), G4KleinNishinaModel::SampleSecondaries(), G4MicroElecInelasticModel::SampleSecondaries(), G4MuElecInelasticModel::SampleSecondaries(), G4eplusTo3GammaOKVIModel::SampleSecondaries(), G4eplusTo2GammaOKVIModel::SampleSecondaries(), G4eeToTwoGammaModel::SampleSecondaries(), G4hCoulombScatteringModel::SampleSecondaries(), G4eCoulombScatteringModel::SampleSecondaries(), G4DNAPTBIonisationModel::SampleSecondaries(), G4AntiNuclElastic::SampleThetaLab(), G4NuclNuclDiffuseElastic::SampleThetaLab(), G4DiffuseElastic::SampleThetaLab(), G4GammaTransition::SampleTransition(), Par02Output::SaveTrack(), G4GDMLWriteDefine::Scale_vectorWrite(), PHG4GDMLWriteDefine::Scale_vectorWrite(), G4GDMLReadSolids::ScaledSolidRead(), G4Scatterer::Scatter(), CLHEP::HepBoost::set(), CLHEP::HepRotation::set(), G4UIcmdWith3Vector::SetDefaultValue(), G4UIcmdWith3VectorAndUnit::SetDefaultValue(), G4GHEKinematicsVector::SetEnergyAndUpdate(), G4UniformMagField::SetFieldValue(), G4GHEKinematicsVector::SetKineticEnergyAndUpdate(), setMag(), G4GHEKinematicsVector::SetMassAndUpdate(), CexmcProductionModelMessenger::SetNewValue(), G4BlineTracerMessenger::SetNewValue(), CexmcEnergyDepositDigitizerMessenger::SetNewValue(), G4ScoringMessenger::SetNewValue(), G4RDPhotoElectricAngularGeneratorPolarized::SetPerpendicularVector(), G4LivermorePolarizedGammaConversionModel::SetPerpendicularVector(), G4LivermorePolarizedComptonModel::SetPerpendicularVector(), G4LivermorePolarizedPhotoElectricGDModel::SetPerpendicularVector(), G4LowEnergyPolarizedCompton::SetPerpendicularVector(), G4LowEPPolarizedComptonModel::SetPerpendicularVector(), G4PrimaryParticle::SetPolarization(), G3toG4RotationMatrix::SetRotationMatrixByCol(), G3toG4RotationMatrix::SetRotationMatrixByRow(), doiPETAnalysis::SetSourcePosition(), G4VPhysicalVolume::SetTranslation(), G4RPGInelastic::SetUpChange(), G4FTFParticipants::ShiftInteractionTime(), G4RayShooter::Shoot(), G4SteppingVerbose::ShowStep(), NeuronLoadDataFile::SingleNeuronSWCfile(), Par02Smearer::SmearGaussian(), G4GHEKinematicsVector::Smul(), G4GHEKinematicsVector::SmulAndUpdate(), G4Torus::SolveNumericJT(), G4AttCheck::Standard(), F04SteppingVerbose::StepInfo(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), PHG4SteppingAction::StoreLocalCoordinate(), G4ScaledSolid::StreamInfo(), G4GHEKinematicsVector::Sub3(), G4EllipticalTube::SurfaceNormal(), G4Box::SurfaceNormal(), G4VTwistedFaceted::SurfaceNormal(), G4Ellipsoid::SurfaceNormal(), G4Paraboloid::SurfaceNormal(), G4GenericTrap::SurfaceNormal(), G4Tet::SurfaceNormal(), G4Hype::SurfaceNormal(), G4CutTubs::SurfaceNormal(), G4Trd::SurfaceNormal(), G4ExtrudedSolid::SurfaceNormal(), G4TwistedTubs::SurfaceNormal(), G4EllipticalCone::SurfaceNormal(), G4Tubs::SurfaceNormal(), G4Para::SurfaceNormal(), G4Torus::SurfaceNormal(), G4Cons::SurfaceNormal(), G4Sphere::SurfaceNormal(), G4Trap::SurfaceNormal(), G4DiffuseElasticV2::ThetaCMStoThetaLab(), G4NuclNuclDiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElastic::ThetaCMStoThetaLab(), G4DiffuseElasticV2::ThetaLabToThetaCMS(), G4NuclNuclDiffuseElastic::ThetaLabToThetaCMS(), G4DiffuseElastic::ThetaLabToThetaCMS(), G4Torus::TorusRootsJT(), G4PolarizedMollerCrossSection::TotalXSection(), G4PolarizedBhabhaCrossSection::TotalXSection(), G4PolarizedComptonCrossSection::TotalXSection(), G4GHEKinematicsVector::Trac(), F04SteppingVerbose::TrackingStarted(), ExN04SteppingVerbose::TrackingStarted(), SteppingVerbose::TrackingStarted(), FCALSteppingVerbose::TrackingStarted(), eRositaSteppingVerbose::TrackingStarted(), XrayFluoSteppingVerbose::TrackingStarted(), PurgMagSteppingVerbose::TrackingStarted(), RE05SteppingVerbose::TrackingStarted(), ExN02SteppingVerbose::TrackingStarted(), ExP01SteppingVerbose::TrackingStarted(), F05SteppingVerbose::TrackingStarted(), G4SteppingVerbose::TrackingStarted(), F02SteppingVerbose::TrackingStarted(), F01SteppingVerbose::TrackingStarted(), F03SteppingVerbose::TrackingStarted(), G4MultiUnion::TransformLimits(), G4Voxelizer::TransformLimits(), G4BoundingEnvelope::TransformVertices(), G4GDMLWriteParamvol::Trap_dimensionsWrite(), PHG4GDMLWriteParamvol::Trap_dimensionsWrite(), G4GDMLWriteStructure::TraverseVolumeTree(), G4Channeling::UpdateParameters(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4EICMvtxSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), G4JLeicVTXSteppingAction::UserSteppingAction(), G4JLeicBeamLineMagnetSteppingAction::UserSteppingAction(), G4LBLVtxSteppingAction::UserSteppingAction(), G4JLeicDIRCSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), AllSiliconTrackerSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), EicFRichSteppingAction::UserSteppingAction(), PHG4EPDSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), AllSi_Al_support_SteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4CylinderStripSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), BeastMagnetSteppingAction::UserSteppingAction(), PHG4BarrelEcalSteppingAction::UserSteppingAction(), BeamLineMagnetSteppingAction::UserSteppingAction(), PHG4BbcSteppingAction::UserSteppingAction(), EICG4ZDCSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4BackwardHcalSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4HybridHomogeneousCalorimeterSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4LFHcalSteppingAction::UserSteppingAction(), PHG4ECAPToFSteppingAction::UserSteppingAction(), PHG4ForwardDualReadoutSteppingAction::UserSteppingAction(), PHG4TpcEndCapSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), EICG4RPSteppingAction::UserSteppingAction(), PHG4TRDSteppingAction::UserSteppingAction(), G4EicDircSteppingAction::UserSteppingAction(), PHG4ZDCSteppingAction::UserSteppingAction(), PHG4MicromegasSteppingAction::UserSteppingAction(), EICG4BwdSteppingAction::UserSteppingAction(), EICG4B0SteppingAction::UserSteppingAction(), EICG4B0ECALSteppingAction::UserSteppingAction(), EICG4LumiSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), CCalSteppingAction::UserSteppingAction(), FCALSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), HadrontherapySteppingAction::UserSteppingAction(), PHG4TTLSteppingAction::UserSteppingAction(), WLSSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), EICG4dRICHTree::vectorToArray(), and G4SteppingVerbose::VerboseTrack().
Member Data Documentation
double CLHEP::Hep3Vector::dx protected
Definition at line 395 of file ThreeVector.h.
View newest version in sPHENIX GitHub at line 395 of file ThreeVector.h
Referenced by compare(), isOrthogonal(), isParallel(), operator/=(), rotate(), rotateUz(), rotateY(), rotateZ(), setCylEta(), setCylindrical(), setCylTheta(), setEta(), setRhoPhiEta(), setRhoPhiTheta(), and setSpherical().
double CLHEP::Hep3Vector::dy protected
Definition at line 396 of file ThreeVector.h.
View newest version in sPHENIX GitHub at line 396 of file ThreeVector.h
Referenced by compare(), isOrthogonal(), isParallel(), operator/=(), rotate(), rotateUz(), rotateX(), rotateZ(), setCylEta(), setCylindrical(), setCylTheta(), setEta(), setRhoPhiEta(), setRhoPhiTheta(), and setSpherical().
double CLHEP::Hep3Vector::dz protected
Definition at line 397 of file ThreeVector.h.
View newest version in sPHENIX GitHub at line 397 of file ThreeVector.h
Referenced by compare(), isOrthogonal(), isParallel(), operator/=(), rapidity(), rotate(), rotateUz(), rotateX(), rotateY(), setCylEta(), setCylindrical(), setCylTheta(), setEta(), setRhoPhiEta(), setRhoPhiTheta(), and setSpherical().
double CLHEP::Hep3Vector::tolerance = Hep3Vector::ToleranceTicks * 2.22045e-16 static protected
Definition at line 400 of file ThreeVector.h.
View newest version in sPHENIX GitHub at line 400 of file ThreeVector.h
Referenced by setTolerance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Vector/ThreeVector.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/SpaceVector.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/SpaceVectorD.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/SpaceVectorP.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/SpaceVectorR.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/ThreeVector.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/ThreeVectorR.cc