ECCE @ EIC Software: G4ErrorPropagatorManager Class Reference
G4ErrorPropagatorManager Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorPropagatorManager.hh>
Public Member Functions
G4ErrorPropagatorManager ()
~G4ErrorPropagatorManager ()
void EventTermination ()
void RunTermination ()
void InitGeant4e ()
void InitTrackPropagation ()
G4bool InitFieldForBackwards ()
G4int Propagate (G4ErrorTrajState *currentTS, const G4ErrorTarget *target, G4ErrorMode mode=G4ErrorMode_PropForwards)
G4int PropagateOneStep (G4ErrorTrajState *currentTS, G4ErrorMode mode=G4ErrorMode_PropForwards)
G4bool CloseGeometry ()
void SetUserInitialization (G4VUserDetectorConstruction *userInit)
void SetUserInitialization (G4VPhysicalVolume *userInit)
void SetUserInitialization (G4VUserPhysicsList *userInit)
void SetUserAction (G4UserTrackingAction *userAction)
void SetUserAction (G4UserSteppingAction *userAction)
G4String PrintG4ErrorState ()
G4String PrintG4ErrorState (G4ErrorState state)
G4String PrintG4State ()
G4String PrintG4State (G4ApplicationState state)
G4ErrorRunManagerHelper * GetErrorRunManagerHelper () const
void SetSteppingManagerVerboseLevel ()
G4ErrorPropagationNavigator * GetErrorPropagationNavigator () const
G4ErrorPropagator * GetPropagator () const
Static Public Member Functions
static G4ErrorPropagatorManager * GetErrorPropagatorManager ()
Private Member Functions
void StartG4ErrorRunManagerHelper ()
void StartNavigator ()
Private Attributes
G4ErrorRunManagerHelper * theG4ErrorRunManagerHelper
G4ErrorPropagator * thePropagator
G4Mag_UsualEqRhs * theEquationOfMotion
G4ErrorPropagationNavigator * theG4ErrorPropagationNavigator
Static Private Attributes
static G4ThreadLocal
G4ErrorPropagatorManager * theG4ErrorPropagatorManager = 0
Detailed Description
Definition at line 62 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 62 of file G4ErrorPropagatorManager.hh
Constructor & Destructor Documentation
G4ErrorPropagatorManager::G4ErrorPropagatorManager ()
Definition at line 79 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ErrorPropagatorManager.cc
References G4ErrorState_PreInit, G4ErrorPropagatorData::GetErrorPropagatorData(), G4ErrorPropagatorData::SetState(), G4ErrorPropagatorData::SetVerbose(), StartG4ErrorRunManagerHelper(), StartNavigator(), theEquationOfMotion, theG4ErrorPropagationNavigator, and thePropagator.
Referenced by GetErrorPropagatorManager().
G4ErrorPropagatorManager::~G4ErrorPropagatorManager ()
Definition at line 108 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 108 of file G4ErrorPropagatorManager.cc
References theEquationOfMotion, theG4ErrorPropagationNavigator, theG4ErrorPropagatorManager, theG4ErrorRunManagerHelper, and thePropagator.
Member Function Documentation
G4bool G4ErrorPropagatorManager::CloseGeometry ()
Definition at line 302 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 302 of file G4ErrorPropagatorManager.cc
References G4State_GeomClosed, G4State_Quit, G4GeometryManager::GetInstance(), G4StateManager::GetStateManager(), G4GeometryManager::OpenGeometry(), G4StateManager::SetNewState(), and TRUE.
Referenced by Finalize().
void G4ErrorPropagatorManager::EventTermination ()
Definition at line 358 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 358 of file G4ErrorPropagatorManager.cc
References G4ErrorState_Init, G4ErrorPropagatorData::GetErrorPropagatorData(), and G4ErrorPropagatorData::SetState().
Referenced by Propagate().
G4ErrorPropagationNavigator* G4ErrorPropagatorManager::GetErrorPropagationNavigator () const inline
Definition at line 132 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ErrorPropagatorManager.hh
References theG4ErrorPropagationNavigator.
G4ErrorPropagatorManager * G4ErrorPropagatorManager::GetErrorPropagatorManager () static
Definition at line 68 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 68 of file G4ErrorPropagatorManager.cc
References G4ErrorPropagatorManager(), and theG4ErrorPropagatorManager.
Referenced by Finalize(), Initialize(), and ProcessEvent().
G4ErrorRunManagerHelper* G4ErrorPropagatorManager::GetErrorRunManagerHelper () const inline
Definition at line 127 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 127 of file G4ErrorPropagatorManager.hh
References theG4ErrorRunManagerHelper.
G4ErrorPropagator* G4ErrorPropagatorManager::GetPropagator () const inline
Definition at line 135 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ErrorPropagatorManager.hh
References thePropagator.
Referenced by ProcessEvent().
G4bool G4ErrorPropagatorManager::InitFieldForBackwards ()
Definition at line 228 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 228 of file G4ErrorPropagatorManager.cc
References e, G4cout, G4endl, G4FieldManager::GetChordFinder(), G4FieldManager::GetDetectorField(), G4VIntegrationDriver::GetEquationOfMotion(), G4TransportationManager::GetFieldManager(), G4ChordFinder::GetIntegrationDriver(), G4TransportationManager::GetTransportationManager(), mm, G4FieldManager::SetChordFinder(), theEquationOfMotion, and G4ErrorPropagatorData::verbose().
Referenced by InitGeant4e().
void G4ErrorPropagatorManager::InitGeant4e ()
Definition at line 171 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 171 of file G4ErrorPropagatorManager.cc
References G4cout, G4endl, G4ErrorState_Init, G4ErrorState_PreInit, G4Exception(), G4State_Idle, G4State_PreInit, G4StateManager::GetCurrentState(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4StateManager::GetStateManager(), InitFieldForBackwards(), G4ErrorRunManagerHelper::InitializeGeometry(), G4ErrorRunManagerHelper::InitializePhysics(), InitTrackPropagation(), JustWarning, message(), PrintG4ErrorState(), PrintG4State(), G4ErrorRunManagerHelper::RunInitialization(), G4ErrorPropagatorData::SetState(), theG4ErrorRunManagerHelper, thePropagator, and G4ErrorPropagatorData::verbose().
Referenced by Initialize().
void G4ErrorPropagatorManager::InitTrackPropagation ()
Definition at line 218 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 218 of file G4ErrorPropagatorManager.cc
References G4ErrorState_Propagating, G4ErrorPropagatorData::GetErrorPropagatorData(), G4ErrorPropagatorData::SetState(), G4ErrorPropagator::SetStepN(), and thePropagator.
Referenced by InitGeant4e(), ProcessEvent(), and Propagate().
G4String G4ErrorPropagatorManager::PrintG4ErrorState ()
Definition at line 373 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 373 of file G4ErrorPropagatorManager.cc
References G4ErrorPropagatorData::GetErrorPropagatorData().
Referenced by InitGeant4e(), and StartNavigator().
G4String G4ErrorPropagatorManager::PrintG4ErrorState (G4ErrorState state)
Definition at line 380 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 380 of file G4ErrorPropagatorManager.cc
References G4ErrorState_Init, G4ErrorState_PreInit, G4ErrorState_Propagating, G4ErrorState_StoppedAtTarget, and G4ErrorState_TargetCloserThanBoundary.
G4String G4ErrorPropagatorManager::PrintG4State ()
Definition at line 406 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 406 of file G4ErrorPropagatorManager.cc
References G4StateManager::GetStateManager().
Referenced by InitGeant4e().
G4String G4ErrorPropagatorManager::PrintG4State (G4ApplicationState state)
Definition at line 413 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 413 of file G4ErrorPropagatorManager.cc
References G4State_Abort, G4State_EventProc, G4State_GeomClosed, G4State_Idle, G4State_Init, G4State_PreInit, and G4State_Quit.
G4int G4ErrorPropagatorManager::Propagate (G4ErrorTrajState * currentTS, const G4ErrorTarget * target, G4ErrorMode mode = G4ErrorMode_PropForwards)
Definition at line 272 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 272 of file G4ErrorPropagatorManager.cc
References EventTermination(), G4ErrorPropagatorData::GetErrorPropagatorData(), InitTrackPropagation(), G4ErrorPropagator::Propagate(), G4ErrorPropagatorData::SetMode(), SetSteppingManagerVerboseLevel(), and thePropagator.
Referenced by ProcessEvent().
G4int G4ErrorPropagatorManager::PropagateOneStep (G4ErrorTrajState * currentTS, G4ErrorMode mode = G4ErrorMode_PropForwards)
Definition at line 289 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 289 of file G4ErrorPropagatorManager.cc
References G4ErrorPropagatorData::GetErrorPropagatorData(), G4ErrorPropagator::PropagateOneStep(), G4ErrorPropagatorData::SetMode(), SetSteppingManagerVerboseLevel(), and thePropagator.
Referenced by ProcessEvent().
void G4ErrorPropagatorManager::RunTermination ()
Definition at line 365 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 365 of file G4ErrorPropagatorManager.cc
References G4ErrorState_PreInit, G4ErrorPropagatorData::GetErrorPropagatorData(), G4ErrorRunManagerHelper::RunTermination(), G4ErrorPropagatorData::SetState(), and theG4ErrorRunManagerHelper.
void G4ErrorPropagatorManager::SetSteppingManagerVerboseLevel ()
Definition at line 350 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 350 of file G4ErrorPropagatorManager.cc
References G4EventManager::GetEventManager(), G4TrackingManager::GetSteppingManager(), G4EventManager::GetTrackingManager(), G4TrackingManager::GetVerboseLevel(), and G4SteppingManager::SetVerboseLevel().
Referenced by Propagate(), and PropagateOneStep().
void G4ErrorPropagatorManager::SetUserAction (G4UserTrackingAction * userAction)
Definition at line 336 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 336 of file G4ErrorPropagatorManager.cc
References G4EventManager::GetEventManager(), and G4EventManager::SetUserAction().
void G4ErrorPropagatorManager::SetUserAction (G4UserSteppingAction * userAction)
Definition at line 343 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 343 of file G4ErrorPropagatorManager.cc
References G4EventManager::GetEventManager(), and G4EventManager::SetUserAction().
void G4ErrorPropagatorManager::SetUserInitialization (G4VUserDetectorConstruction * userInit)
Definition at line 315 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 315 of file G4ErrorPropagatorManager.cc
References G4ErrorRunManagerHelper::SetUserInitialization(), and theG4ErrorRunManagerHelper.
Referenced by Initialize().
void G4ErrorPropagatorManager::SetUserInitialization (G4VPhysicalVolume * userInit)
Definition at line 322 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 322 of file G4ErrorPropagatorManager.cc
References G4ErrorRunManagerHelper::SetUserInitialization(), and theG4ErrorRunManagerHelper.
void G4ErrorPropagatorManager::SetUserInitialization (G4VUserPhysicsList * userInit)
Definition at line 329 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 329 of file G4ErrorPropagatorManager.cc
References G4ErrorRunManagerHelper::SetUserInitialization(), and theG4ErrorRunManagerHelper.
void G4ErrorPropagatorManager::StartG4ErrorRunManagerHelper () private
Definition at line 119 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 119 of file G4ErrorPropagatorManager.cc
References G4cout, G4endl, G4ErrorRunManagerHelper::GetRunManagerKernel(), theG4ErrorRunManagerHelper, and G4ErrorPropagatorData::verbose().
Referenced by G4ErrorPropagatorManager().
void G4ErrorPropagatorManager::StartNavigator () private
Definition at line 137 of file G4ErrorPropagatorManager.cc.
View newest version in sPHENIX GitHub at line 137 of file G4ErrorPropagatorManager.cc
References G4cout, G4endl, G4EventManager::GetEventManager(), G4PropagatorInField::GetIntersectionLocator(), G4TransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetPropagatorInField(), G4TrackingManager::GetSteppingManager(), G4EventManager::GetTrackingManager(), G4TransportationManager::GetTransportationManager(), G4Navigator::GetVerboseLevel(), G4Navigator::GetWorldVolume(), PrintG4ErrorState(), G4SteppingManager::SetNavigator(), G4VIntersectionLocator::SetNavigatorFor(), G4TransportationManager::SetNavigatorForTracking(), G4Navigator::SetVerboseLevel(), G4Navigator::SetWorldVolume(), theG4ErrorPropagationNavigator, G4ErrorPropagatorData::verbose(), and Acts::Test::world.
Referenced by G4ErrorPropagatorManager().
Member Data Documentation
G4Mag_UsualEqRhs* G4ErrorPropagatorManager::theEquationOfMotion private
Definition at line 155 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 155 of file G4ErrorPropagatorManager.hh
Referenced by G4ErrorPropagatorManager(), InitFieldForBackwards(), and ~G4ErrorPropagatorManager().
G4ErrorPropagationNavigator* G4ErrorPropagatorManager::theG4ErrorPropagationNavigator private
Definition at line 157 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 157 of file G4ErrorPropagatorManager.hh
Referenced by G4ErrorPropagatorManager(), GetErrorPropagationNavigator(), StartNavigator(), and ~G4ErrorPropagatorManager().
G4ThreadLocal G4ErrorPropagatorManager * G4ErrorPropagatorManager::theG4ErrorPropagatorManager = 0 static private
Definition at line 149 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 149 of file G4ErrorPropagatorManager.hh
Referenced by GetErrorPropagatorManager(), and ~G4ErrorPropagatorManager().
G4ErrorRunManagerHelper* G4ErrorPropagatorManager::theG4ErrorRunManagerHelper private
Definition at line 151 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ErrorPropagatorManager.hh
Referenced by GetErrorRunManagerHelper(), InitGeant4e(), RunTermination(), SetUserInitialization(), StartG4ErrorRunManagerHelper(), and ~G4ErrorPropagatorManager().
G4ErrorPropagator* G4ErrorPropagatorManager::thePropagator private
Definition at line 153 of file G4ErrorPropagatorManager.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ErrorPropagatorManager.hh
Referenced by G4ErrorPropagatorManager(), GetPropagator(), InitGeant4e(), InitTrackPropagation(), Propagate(), PropagateOneStep(), and ~G4ErrorPropagatorManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorPropagatorManager.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorPropagatorManager.cc