ECCE @ EIC Software: G4PairProductionRelModel Class Reference
G4PairProductionRelModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PairProductionRelModel.hh>
Classes
struct ElementData
struct LPMFuncs
Public Member Functions
G4PairProductionRelModel (const G4ParticleDefinition *p=nullptr, const G4String &nam="BetheHeitlerLPM")
virtual ~G4PairProductionRelModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &) override
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double kinEnergy, G4double Z, G4double A=0., G4double cut=0., G4double emax=DBL_MAX) override
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double tmin, G4double maxEnergy) override
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double) override
void SetLPMflag (G4bool val)
G4bool LPMflag () const
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cut=0.0)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
void ComputePhi12 (const G4double delta, G4double &phi1, G4double &phi2)
G4double ScreenFunction1 (const G4double delta)
G4double ScreenFunction2 (const G4double delta)
void ScreenFunction12 (const G4double delta, G4double &f1, G4double &f2)
G4double ComputeParametrizedXSectionPerAtom (G4double gammaEnergy, G4double Z)
G4double ComputeXSectionPerAtom (G4double gammaEnergy, G4double Z)
G4double ComputeDXSectionPerAtom (G4double eplusEnergy, G4double gammaEnergy, G4double Z)
G4double ComputeRelDXSectionPerAtom (G4double eplusEnergy, G4double gammaEnergy, G4double Z)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Protected Attributes
G4bool fIsUseLPMCorrection
G4bool fIsUseCompleteScreening
G4double fLPMEnergy
G4double fParametrizedXSectionThreshold
G4double fCoulombCorrectionThreshold
G4Pow * fG4Calc
G4ParticleDefinition * fTheGamma
G4ParticleDefinition * fTheElectron
G4ParticleDefinition * fThePositron
G4ParticleChangeForGamma * fParticleChange
Protected Attributes inherited from G4VEmModel
G4ElementData * fElementData
G4VParticleChange * pParticleChange
G4PhysicsTable * xSectionTable
const G4Material * pBaseMaterial
const std::vector< G4double > * theDensityFactor
const std::vector< G4int > * theDensityIdx
size_t idxTable
G4bool lossFlucFlag
G4double inveplus
G4double pFactor
Static Protected Attributes
static const G4int gMaxZet = 120
static const G4double gLPMconstant
static const G4double gXGL [8]
static const G4double gWGL [8]
static const G4double gFelLowZet [8]
static const G4double gFinelLowZet [8]
static const G4double gXSecFactor
static const G4double gEgLPMActivation = 100.*CLHEP::GeV
static std::vector< ElementData * > gElementData
static LPMFuncs gLPMFuncs
Private Member Functions
void InitialiseElementData ()
void InitLPMFunctions ()
void ComputeLPMGsPhis (G4double &funcGS, G4double &funcPhiS, const G4double varShat)
void GetLPMFunctions (G4double &lpmGs, G4double &lpmPhis, const G4double sval)
void ComputeLPMfunctions (G4double &fXiS, G4double &fGS, G4double &fPhiS, const G4double eps, const G4double egamma, const G4int izet)
G4PairProductionRelModel & operator= (const G4PairProductionRelModel &right)=delete
G4PairProductionRelModel (const G4PairProductionRelModel &)=delete
Detailed Description
Definition at line 67 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4PairProductionRelModel.hh
Constructor & Destructor Documentation
G4PairProductionRelModel::G4PairProductionRelModel (const G4ParticleDefinition * p = nullptr, const G4String & nam = "BetheHeitlerLPM") explicit
Definition at line 113 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 113 of file G4PairProductionRelModel.cc
References fCoulombCorrectionThreshold, fParametrizedXSectionThreshold, CLHEP::GeV, CLHEP::MeV, and G4VEmModel::SetAngularDistribution().
G4PairProductionRelModel::~G4PairProductionRelModel () virtual
Definition at line 129 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 129 of file G4PairProductionRelModel.cc
References G4PairProductionRelModel::LPMFuncs::fIsInitialized, fIsUseLPMCorrection, G4PairProductionRelModel::LPMFuncs::fLPMFuncG, G4PairProductionRelModel::LPMFuncs::fLPMFuncPhi, gElementData, gLPMFuncs, and G4VEmModel::IsMaster().
G4PairProductionRelModel::G4PairProductionRelModel (const G4PairProductionRelModel &) private delete
Member Function Documentation
G4double G4PairProductionRelModel::ComputeCrossSectionPerAtom (const G4ParticleDefinition * , G4double kinEnergy, G4double Z, G4double A = 0., G4double cut = 0., G4double emax = DBL_MAX) override virtual
Reimplemented from G4VEmModel.
Definition at line 310 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 310 of file G4PairProductionRelModel.cc
References ComputeParametrizedXSectionPerAtom(), ComputeXSectionPerAtom(), source.hepunit::electron_mass_c2, Acts::VectorHelpers::eta(), fParametrizedXSectionThreshold, G4lrint(), gElementData, gMaxZet, gXSecFactor, max, and min.
G4double G4PairProductionRelModel::ComputeDXSectionPerAtom (G4double eplusEnergy, G4double gammaEnergy, G4double Z) protected
Definition at line 227 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 227 of file G4PairProductionRelModel.cc
References ComputePhi12(), Acts::Test::delta, CLHEP::electron_mass_c2, eps, fIsUseCompleteScreening, G4lrint(), gElementData, gMaxZet, max, and min.
Referenced by ComputeXSectionPerAtom().
void G4PairProductionRelModel::ComputeLPMfunctions (G4double & fXiS, G4double & fGS, G4double & fPhiS, const G4double eps, const G4double egamma, const G4int izet) private
Definition at line 615 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 615 of file G4PairProductionRelModel.cc
References condition(), fLPMEnergy, G4Log(), gElementData, and GetLPMFunctions().
Referenced by ComputeRelDXSectionPerAtom(), and SampleSecondaries().
void G4PairProductionRelModel::ComputeLPMGsPhis (G4double & funcGS, G4double & funcPhiS, const G4double varShat) private
Definition at line 556 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 556 of file G4PairProductionRelModel.cc
References G4Exp(), and CLHEP::pi.
Referenced by InitLPMFunctions().
G4double G4PairProductionRelModel::ComputeParametrizedXSectionPerAtom (G4double gammaEnergy, G4double Z) protected
Definition at line 655 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 655 of file G4PairProductionRelModel.cc
References a0, c1, c2, CLHEP::electron_mass_c2, F1, F2, F3, G4Log(), kMC2, CLHEP::MeV, CLHEP::microbarn, x, x2, x3, x4, and x5.
Referenced by ComputeCrossSectionPerAtom().
void G4PairProductionRelModel::ComputePhi12 (const G4double delta, G4double & phi1, G4double & phi2) inline protected
Definition at line 211 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 211 of file G4PairProductionRelModel.hh
References Acts::Test::delta, and G4Log().
Referenced by ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), and SampleSecondaries().
G4double G4PairProductionRelModel::ComputeRelDXSectionPerAtom (G4double eplusEnergy, G4double gammaEnergy, G4double Z) protected
Definition at line 276 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 276 of file G4PairProductionRelModel.cc
References ComputeLPMfunctions(), ComputePhi12(), Acts::Test::delta, CLHEP::electron_mass_c2, eps, fIsUseCompleteScreening, G4lrint(), gElementData, gMaxZet, max, and min.
Referenced by ComputeXSectionPerAtom().
G4double G4PairProductionRelModel::ComputeXSectionPerAtom (G4double gammaEnergy, G4double Z) protected
Definition at line 172 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 172 of file G4PairProductionRelModel.cc
References ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), CLHEP::electron_mass_c2, fIsUseLPMCorrection, G4lrint(), gEgLPMActivation, gElementData, gMaxZet, gWGL, gXGL, max, and min.
Referenced by ComputeCrossSectionPerAtom().
void G4PairProductionRelModel::GetLPMFunctions (G4double & lpmGs, G4double & lpmPhis, const G4double sval) private
Definition at line 596 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 596 of file G4PairProductionRelModel.cc
References G4PairProductionRelModel::LPMFuncs::fISDelta, G4PairProductionRelModel::LPMFuncs::fLPMFuncG, G4PairProductionRelModel::LPMFuncs::fLPMFuncPhi, G4PairProductionRelModel::LPMFuncs::fSLimit, and gLPMFuncs.
Referenced by ComputeLPMfunctions().
void G4PairProductionRelModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) override virtual
Implements G4VEmModel.
Reimplemented in G4BetheHeitler5DModel.
Definition at line 146 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 146 of file G4PairProductionRelModel.cc
References fIsUseLPMCorrection, fParticleChange, G4VEmModel::GetParticleChangeForGamma(), G4VEmModel::HighEnergyLimit(), InitialiseElementData(), G4VEmModel::InitialiseElementSelectors(), InitLPMFunctions(), G4VEmModel::IsMaster(), and G4VEmModel::LowEnergyLimit().
Referenced by G4BetheHeitler5DModel::Initialise().
void G4PairProductionRelModel::InitialiseElementData () private
Definition at line 499 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 499 of file G4PairProductionRelModel.cc
References G4PairProductionRelModel::ElementData::fCoulomb, G4PairProductionRelModel::ElementData::fDeltaFactor, G4PairProductionRelModel::ElementData::fDeltaMaxHigh, G4PairProductionRelModel::ElementData::fDeltaMaxLow, G4PairProductionRelModel::ElementData::fEtaValue, G4PairProductionRelModel::ElementData::fLogZ13, G4PairProductionRelModel::ElementData::fLPMILVarS1Cond, G4PairProductionRelModel::ElementData::fLPMVarS1Cond, G4PairProductionRelModel::ElementData::fLradEl, G4Exp(), G4Log(), gElementData, G4Element::GetElementTable(), G4Element::GetfCoulomb(), G4Element::GetIonisation(), G4IonisParamElm::GetlogZ3(), G4IonisParamElm::GetZ3(), G4Element::GetZasInt(), gFelLowZet, gFinelLowZet, gMaxZet, and min.
Referenced by Initialise().
void G4PairProductionRelModel::InitialiseLocal (const G4ParticleDefinition * , G4VEmModel * masterModel) override virtual
Reimplemented from G4VEmModel.
Definition at line 164 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 164 of file G4PairProductionRelModel.cc
References G4VEmModel::GetElementSelectors(), G4VEmModel::HighEnergyLimit(), G4VEmModel::LowEnergyLimit(), and G4VEmModel::SetElementSelectors().
void G4PairProductionRelModel::InitLPMFunctions () private
Definition at line 542 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 542 of file G4PairProductionRelModel.cc
References ComputeLPMGsPhis(), G4PairProductionRelModel::LPMFuncs::fISDelta, G4PairProductionRelModel::LPMFuncs::fIsInitialized, G4PairProductionRelModel::LPMFuncs::fLPMFuncG, G4PairProductionRelModel::LPMFuncs::fLPMFuncPhi, G4PairProductionRelModel::LPMFuncs::fSLimit, gLPMFuncs, and num.
Referenced by Initialise().
G4bool G4PairProductionRelModel::LPMflag () const inline
Definition at line 101 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4PairProductionRelModel.hh
References fIsUseLPMCorrection.
G4PairProductionRelModel& G4PairProductionRelModel::operator= (const G4PairProductionRelModel & right) private delete
void G4PairProductionRelModel::SampleSecondaries (std::vector< G4DynamicParticle * > * fvect, const G4MaterialCutsCouple * couple, const G4DynamicParticle * aDynamicGamma, G4double tmin, G4double maxEnergy) override virtual
Implements G4VEmModel.
Reimplemented in G4BetheHeitler5DModel.
Definition at line 347 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 347 of file G4PairProductionRelModel.cc
References G4Pow::A13(), ComputeLPMfunctions(), ComputePhi12(), Acts::Test::delta, CLHEP::electron_mass_c2, eps, F10, F20, fCoulombCorrectionThreshold, fG4Calc, fIsUseLPMCorrection, fLPMEnergy, fParticleChange, fStopAndKill, fTheElectron, fTheGamma, fThePositron, gEgLPMActivation, gElementData, G4VEmModel::GetAngularDistribution(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4Material::GetRadlen(), G4Element::GetZasInt(), gLPMconstant, gMaxZet, mat, max, CLHEP::MeV, min, G4VParticleChange::ProposeTrackStatus(), G4VEmAngularDistribution::SamplePairDirections(), ScreenFunction1(), ScreenFunction12(), ScreenFunction2(), G4VEmModel::SelectTargetAtom(), and G4ParticleChangeForGamma::SetProposedKineticEnergy().
G4double G4PairProductionRelModel::ScreenFunction1 (const G4double delta) inline protected
Definition at line 225 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 225 of file G4PairProductionRelModel.hh
References Acts::Test::delta, and G4Log().
Referenced by SampleSecondaries().
void G4PairProductionRelModel::ScreenFunction12 (const G4double delta, G4double & f1, G4double & f2) inline protected
Definition at line 241 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 241 of file G4PairProductionRelModel.hh
References Acts::Test::delta, f1, and G4Log().
Referenced by SampleSecondaries().
G4double G4PairProductionRelModel::ScreenFunction2 (const G4double delta) inline protected
Definition at line 233 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 233 of file G4PairProductionRelModel.hh
References Acts::Test::delta, and G4Log().
Referenced by SampleSecondaries().
void G4PairProductionRelModel::SetLPMflag (G4bool val) inline
Definition at line 100 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 100 of file G4PairProductionRelModel.hh
References fIsUseLPMCorrection.
void G4PairProductionRelModel::SetupForMaterial (const G4ParticleDefinition * , const G4Material * mat, G4double) override virtual
Reimplemented from G4VEmModel.
Definition at line 340 of file G4PairProductionRelModel.cc.
View newest version in sPHENIX GitHub at line 340 of file G4PairProductionRelModel.cc
References fLPMEnergy, G4Material::GetRadlen(), and gLPMconstant.
Member Data Documentation
G4double G4PairProductionRelModel::fCoulombCorrectionThreshold protected
Definition at line 182 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4PairProductionRelModel.hh
Referenced by G4PairProductionRelModel(), and SampleSecondaries().
G4Pow* G4PairProductionRelModel::fG4Calc protected
Definition at line 184 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 184 of file G4PairProductionRelModel.hh
Referenced by SampleSecondaries().
G4bool G4PairProductionRelModel::fIsUseCompleteScreening protected
Definition at line 177 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4PairProductionRelModel.hh
Referenced by ComputeDXSectionPerAtom(), and ComputeRelDXSectionPerAtom().
G4bool G4PairProductionRelModel::fIsUseLPMCorrection protected
Definition at line 176 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4PairProductionRelModel.hh
Referenced by ComputeXSectionPerAtom(), Initialise(), LPMflag(), SampleSecondaries(), SetLPMflag(), and ~G4PairProductionRelModel().
G4double G4PairProductionRelModel::fLPMEnergy protected
Definition at line 179 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4PairProductionRelModel.hh
Referenced by ComputeLPMfunctions(), SampleSecondaries(), and SetupForMaterial().
G4double G4PairProductionRelModel::fParametrizedXSectionThreshold protected
Definition at line 181 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 181 of file G4PairProductionRelModel.hh
Referenced by ComputeCrossSectionPerAtom(), and G4PairProductionRelModel().
G4ParticleChangeForGamma* G4PairProductionRelModel::fParticleChange protected
Definition at line 188 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 188 of file G4PairProductionRelModel.hh
Referenced by Initialise(), G4BetheHeitler5DModel::SampleSecondaries(), and SampleSecondaries().
G4ParticleDefinition* G4PairProductionRelModel::fTheElectron protected
Definition at line 186 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 186 of file G4PairProductionRelModel.hh
Referenced by G4BetheHeitler5DModel::G4BetheHeitler5DModel(), G4BetheHeitler5DModel::Initialise(), G4BetheHeitler5DModel::SampleSecondaries(), and SampleSecondaries().
G4ParticleDefinition* G4PairProductionRelModel::fTheGamma protected
Definition at line 185 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 185 of file G4PairProductionRelModel.hh
Referenced by G4BetheHeitler5DModel::SampleSecondaries(), and SampleSecondaries().
G4ParticleDefinition* G4PairProductionRelModel::fThePositron protected
Definition at line 187 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 187 of file G4PairProductionRelModel.hh
Referenced by SampleSecondaries().
const G4double G4PairProductionRelModel::gEgLPMActivation = 100.*CLHEP::GeV static protected
Definition at line 171 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 171 of file G4PairProductionRelModel.hh
Referenced by ComputeXSectionPerAtom(), and SampleSecondaries().
std::vector< G4PairProductionRelModel::ElementData * > G4PairProductionRelModel::gElementData static protected
Definition at line 173 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 173 of file G4PairProductionRelModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeDXSectionPerAtom(), ComputeLPMfunctions(), ComputeRelDXSectionPerAtom(), ComputeXSectionPerAtom(), InitialiseElementData(), SampleSecondaries(), and ~G4PairProductionRelModel().
const G4double G4PairProductionRelModel::gFelLowZet static protected
Initial value:
= {
  0.0, 5.3104, 4.7935, 4.7402, 4.7112, 4.6694, 4.6134, 4.5520
}
Definition at line 167 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 167 of file G4PairProductionRelModel.hh
Referenced by InitialiseElementData().
const G4double G4PairProductionRelModel::gFinelLowZet static protected
Initial value:
= {
  0.0, 5.9173, 5.6125, 5.5377, 5.4728, 5.4174, 5.3688, 5.3236
}
Definition at line 168 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 168 of file G4PairProductionRelModel.hh
Referenced by InitialiseElementData().
const G4double G4PairProductionRelModel::gLPMconstant static protected
Initial value:
=
  CLHEP::fine_structure_const*CLHEP::electron_mass_c2*CLHEP::electron_mass_c2
  /(4.*CLHEP::pi*CLHEP::hbarc)
Definition at line 163 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 163 of file G4PairProductionRelModel.hh
Referenced by SampleSecondaries(), and SetupForMaterial().
G4PairProductionRelModel::LPMFuncs G4PairProductionRelModel::gLPMFuncs static protected
Definition at line 174 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4PairProductionRelModel.hh
Referenced by GetLPMFunctions(), InitLPMFunctions(), and ~G4PairProductionRelModel().
const G4int G4PairProductionRelModel::gMaxZet = 120 static protected
Definition at line 161 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 161 of file G4PairProductionRelModel.hh
Referenced by ComputeCrossSectionPerAtom(), ComputeDXSectionPerAtom(), ComputeRelDXSectionPerAtom(), ComputeXSectionPerAtom(), InitialiseElementData(), and SampleSecondaries().
const G4double G4PairProductionRelModel::gWGL static protected
Initial value:
= {
  5.06142681e-02, 1.11190517e-01, 1.56853323e-01, 1.81341892e-01,
  1.81341892e-01, 1.56853323e-01, 1.11190517e-01, 5.06142681e-02
}
Definition at line 166 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4PairProductionRelModel.hh
Referenced by ComputeXSectionPerAtom().
const G4double G4PairProductionRelModel::gXGL static protected
Initial value:
= {
  1.98550718e-02, 1.01666761e-01, 2.37233795e-01, 4.08282679e-01,
  5.91717321e-01, 7.62766205e-01, 8.98333239e-01, 9.80144928e-01
}
Definition at line 165 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4PairProductionRelModel.hh
Referenced by ComputeXSectionPerAtom().
const G4double G4PairProductionRelModel::gXSecFactor static protected
Initial value:
=
  4.*CLHEP::fine_structure_const*CLHEP::classic_electr_radius
  *CLHEP::classic_electr_radius
Definition at line 170 of file G4PairProductionRelModel.hh.
View newest version in sPHENIX GitHub at line 170 of file G4PairProductionRelModel.hh
Referenced by ComputeCrossSectionPerAtom().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/include/G4PairProductionRelModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/standard/src/G4PairProductionRelModel.cc