ECCE @ EIC Software: G4ParticleHPElementData Class Reference
G4ParticleHPElementData Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPElementData.hh>
Public Member Functions
G4ParticleHPElementData ()
~G4ParticleHPElementData ()
void Init (G4Element *theElement, G4ParticleDefinition *projectile, const char *dataDirVariable)
void UpdateData (G4int A, G4int Z, G4int index, G4double abundance, G4ParticleDefinition *projectile, const char *dataDirVariable)
void UpdateData (G4int A, G4int Z, G4int M, G4int index, G4double abundance, G4ParticleDefinition *projectile, const char *dataDirVariable)
void Harmonise (G4ParticleHPVector *&theStore, G4ParticleHPVector *theNew)
G4ParticleHPVector * GetData (G4ParticleHPFissionData *)
G4ParticleHPVector * GetData (G4ParticleHPCaptureData *)
G4ParticleHPVector * GetData (G4ParticleHPElasticData *)
G4ParticleHPVector * GetData (G4ParticleHPInelasticData *)
G4ParticleHPVector * MakePhysicsVector (G4Element *theElement, G4ParticleDefinition *projectile, G4ParticleHPFissionData *theSet, char *dataDirVariable)
G4ParticleHPVector * MakePhysicsVector (G4Element *theElement, G4ParticleDefinition *projectile, G4ParticleHPCaptureData *theSet, char *dataDirVariable)
G4ParticleHPVector * MakePhysicsVector (G4Element *theElement, G4ParticleDefinition *projectile, G4ParticleHPElasticData *theSet, char *dataDirVariable)
G4ParticleHPVector * MakePhysicsVector (G4Element *theElement, G4ParticleDefinition *projectile, G4ParticleHPInelasticData *theSet, char *dataDirVariable)
Private Attributes
G4ParticleHPVector * theFissionData
G4ParticleHPVector * theCaptureData
G4ParticleHPVector * theElasticData
G4ParticleHPVector * theInelasticData
G4double precision
G4ParticleHPVector * theBuffer
G4ParticleHPIsoData * theIsotopeWiseData
G4StableIsotopes theStableOnes
G4String filename
Detailed Description
Definition at line 55 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPElementData.hh
Constructor & Destructor Documentation
G4ParticleHPElementData::G4ParticleHPElementData ()
Definition at line 36 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 36 of file G4ParticleHPElementData.cc
References precision, theBuffer, theCaptureData, theElasticData, theFissionData, theInelasticData, and theIsotopeWiseData.
G4ParticleHPElementData::~G4ParticleHPElementData ()
Definition at line 47 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ParticleHPElementData.cc
References theCaptureData, theElasticData, theFissionData, theInelasticData, and theIsotopeWiseData.
Member Function Documentation
G4ParticleHPVector* G4ParticleHPElementData::GetData (G4ParticleHPFissionData *) inline
Definition at line 73 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ParticleHPElementData.hh
References theFissionData.
Referenced by MakePhysicsVector().
G4ParticleHPVector* G4ParticleHPElementData::GetData (G4ParticleHPCaptureData *) inline
Definition at line 75 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 75 of file G4ParticleHPElementData.hh
References theCaptureData.
G4ParticleHPVector* G4ParticleHPElementData::GetData (G4ParticleHPElasticData *) inline
Definition at line 77 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 77 of file G4ParticleHPElementData.hh
References theElasticData.
G4ParticleHPVector* G4ParticleHPElementData::GetData (G4ParticleHPInelasticData *) inline
Definition at line 79 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 79 of file G4ParticleHPElementData.hh
References theInelasticData.
void G4ParticleHPElementData::Harmonise (G4ParticleHPVector *& theStore, G4ParticleHPVector * theNew)
Definition at line 144 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 144 of file G4ParticleHPElementData.cc
References a, active, G4ParticleHPVector::GetEnergy(), G4ParticleHPVector::GetVectorLength(), G4ParticleHPVector::GetXsec(), max, n, Acts::passive, G4ParticleHPVector::SetData(), t, tmp, x, and y.
Referenced by UpdateData().
void G4ParticleHPElementData::Init (G4Element * theElement, G4ParticleDefinition * projectile, const char * dataDirVariable)
Definition at line 56 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPElementData.cc
References A(), G4StableIsotopes::GetAbundance(), G4StableIsotopes::GetFirstIsotope(), G4Element::GetIsotope(), G4StableIsotopes::GetIsotopeNucleonCount(), G4Isotope::Getm(), G4Isotope::GetN(), G4StableIsotopes::GetNumberOfIsotopes(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZ(), G4Neutron::Neutron(), CLHEP::perCent, precision, theCaptureData, theElasticData, theFissionData, theInelasticData, theIsotopeWiseData, theStableOnes, G4ParticleHPVector::ThinOut(), UpdateData(), and Z.
Referenced by MakePhysicsVector().
G4ParticleHPVector * G4ParticleHPElementData::MakePhysicsVector (G4Element * theElement, G4ParticleDefinition * projectile, G4ParticleHPFissionData * theSet, char * dataDirVariable)
Definition at line 199 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 199 of file G4ParticleHPElementData.cc
References GetData(), Init(), and G4Neutron::Neutron().
G4ParticleHPVector * G4ParticleHPElementData::MakePhysicsVector (G4Element * theElement, G4ParticleDefinition * projectile, G4ParticleHPCaptureData * theSet, char * dataDirVariable)
Definition at line 208 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 208 of file G4ParticleHPElementData.cc
References GetData(), Init(), and G4Neutron::Neutron().
G4ParticleHPVector * G4ParticleHPElementData::MakePhysicsVector (G4Element * theElement, G4ParticleDefinition * projectile, G4ParticleHPElasticData * theSet, char * dataDirVariable)
Definition at line 217 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 217 of file G4ParticleHPElementData.cc
References GetData(), Init(), and G4Neutron::Neutron().
G4ParticleHPVector * G4ParticleHPElementData::MakePhysicsVector (G4Element * theElement, G4ParticleDefinition * projectile, G4ParticleHPInelasticData * theSet, char * dataDirVariable)
Definition at line 226 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 226 of file G4ParticleHPElementData.cc
References GetData(), Init(), and G4Neutron::Neutron().
void G4ParticleHPElementData::UpdateData (G4int A, G4int Z, G4int index, G4double abundance, G4ParticleDefinition * projectile, const char * dataDirVariable) inline
Definition at line 68 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ParticleHPElementData.hh
References UpdateData().
Referenced by Init(), and UpdateData().
void G4ParticleHPElementData::UpdateData (G4int A, G4int Z, G4int M, G4int index, G4double abundance, G4ParticleDefinition * projectile, const char * dataDirVariable)
Definition at line 101 of file G4ParticleHPElementData.cc.
View newest version in sPHENIX GitHub at line 101 of file G4ParticleHPElementData.cc
References Harmonise(), G4ParticleHPIsoData::Init(), G4ParticleHPIsoData::MakeCaptureData(), G4ParticleHPIsoData::MakeElasticData(), G4ParticleHPIsoData::MakeFissionData(), G4ParticleHPIsoData::MakeInelasticData(), theBuffer, theCaptureData, theElasticData, theFissionData, theInelasticData, and theIsotopeWiseData.
Member Data Documentation
G4String G4ParticleHPElementData::filename private
Definition at line 116 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 116 of file G4ParticleHPElementData.hh
G4double G4ParticleHPElementData::precision private
Definition at line 108 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParticleHPElementData.hh
Referenced by G4ParticleHPElementData(), and Init().
G4ParticleHPVector* G4ParticleHPElementData::theBuffer private
Definition at line 110 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ParticleHPElementData.hh
Referenced by G4ParticleHPElementData(), and UpdateData().
G4ParticleHPVector* G4ParticleHPElementData::theCaptureData private
Definition at line 105 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 105 of file G4ParticleHPElementData.hh
Referenced by G4ParticleHPElementData(), GetData(), Init(), UpdateData(), and ~G4ParticleHPElementData().
G4ParticleHPVector* G4ParticleHPElementData::theElasticData private
Definition at line 106 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ParticleHPElementData.hh
Referenced by G4ParticleHPElementData(), GetData(), Init(), UpdateData(), and ~G4ParticleHPElementData().
G4ParticleHPVector* G4ParticleHPElementData::theFissionData private
Definition at line 104 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParticleHPElementData.hh
Referenced by G4ParticleHPElementData(), GetData(), Init(), UpdateData(), and ~G4ParticleHPElementData().
G4ParticleHPVector* G4ParticleHPElementData::theInelasticData private
Definition at line 107 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParticleHPElementData.hh
Referenced by G4ParticleHPElementData(), GetData(), Init(), UpdateData(), and ~G4ParticleHPElementData().
G4ParticleHPIsoData* G4ParticleHPElementData::theIsotopeWiseData private
Definition at line 112 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPElementData.hh
Referenced by G4ParticleHPElementData(), Init(), UpdateData(), and ~G4ParticleHPElementData().
G4StableIsotopes G4ParticleHPElementData::theStableOnes private
Definition at line 114 of file G4ParticleHPElementData.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParticleHPElementData.hh
Referenced by Init().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPElementData.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPElementData.cc