ECCE @ EIC Software: G4UnknownDecay Class Reference
G4UnknownDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/decay/include/G4UnknownDecay.hh>
Public Member Functions
G4UnknownDecay (const G4String &processName="UnknownDecay")
virtual ~G4UnknownDecay ()
virtual G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep) override
virtual void BuildPhysicsTable (const G4ParticleDefinition &) override
virtual G4bool IsApplicable (const G4ParticleDefinition &) override
virtual void ProcessDescription (std::ostream &outFile) const override
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition) override
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
virtual G4VParticleChange * DecayIt (const G4Track &aTrack, const G4Step &aStep)
virtual G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition) override
Private Member Functions
G4UnknownDecay (const G4UnknownDecay &right)
G4UnknownDecay & operator= (const G4UnknownDecay &right)
Private Attributes
G4int verboseLevel
const G4double HighestValue
G4ParticleChangeForDecay fParticleChangeForDecay
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 43 of file G4UnknownDecay.hh.
View newest version in sPHENIX GitHub at line 43 of file G4UnknownDecay.hh
Constructor & Destructor Documentation
G4UnknownDecay::G4UnknownDecay (const G4String & processName = "UnknownDecay")
Definition at line 46 of file G4UnknownDecay.cc.
View newest version in sPHENIX GitHub at line 46 of file G4UnknownDecay.cc
References DECAY_Unknown, fParticleChangeForDecay, G4cout, G4endl, G4VProcess::GetVerboseLevel(), G4VProcess::pParticleChange, and G4VProcess::SetProcessSubType().
G4UnknownDecay::~G4UnknownDecay () virtual
Definition at line 62 of file G4UnknownDecay.cc.
View newest version in sPHENIX GitHub at line 62 of file G4UnknownDecay.cc
G4UnknownDecay::G4UnknownDecay (const G4UnknownDecay & right) private
Member Function Documentation
void G4UnknownDecay::BuildPhysicsTable (const G4ParticleDefinition &) override virtual
Reimplemented from G4VProcess.
Definition at line 77 of file G4UnknownDecay.cc.
View newest version in sPHENIX GitHub at line 77 of file G4UnknownDecay.cc
G4VParticleChange * G4UnknownDecay::DecayIt (const G4Track & aTrack, const G4Step & aStep) protected virtual
Definition at line 82 of file G4UnknownDecay.cc.
View newest version in sPHENIX GitHub at line 82 of file G4UnknownDecay.cc
References G4VParticleChange::AddSecondary(), G4DecayProducts::Boost(), G4VProcess::ClearNumberOfInteractionLengthLeft(), cm, G4DecayProducts::DumpInfo(), G4DecayProducts::entries(), fParticleChangeForDecay, fStopAndKill, G4cout, G4endl, G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetMass(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), G4Track::GetPosition(), G4DynamicParticle::GetPreAssignedDecayProducts(), G4DynamicParticle::GetPreAssignedDecayProperTime(), G4DynamicParticle::GetTotalEnergy(), G4Track::GetTouchableHandle(), G4VProcess::GetVerboseLevel(), G4ParticleChangeForDecay::Initialize(), MeV, ns, G4DecayProducts::PopProducts(), G4ParticleChangeForDecay::ProposeGlobalTime(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4VParticleChange::ProposeTrackStatus(), G4Track::SetGoodForTrackingFlag(), G4VParticleChange::SetNumberOfSecondaries(), G4Track::SetTouchableHandle(), x, y, and z.
Referenced by PostStepDoIt().
G4double G4UnknownDecay::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) override protected virtual
Implements G4VDiscreteProcess.
Definition at line 72 of file G4UnknownDecay.cc.
View newest version in sPHENIX GitHub at line 72 of file G4UnknownDecay.cc
G4bool G4UnknownDecay::IsApplicable (const G4ParticleDefinition & aParticleType) override virtual
Reimplemented from G4VProcess.
Definition at line 66 of file G4UnknownDecay.cc.
View newest version in sPHENIX GitHub at line 66 of file G4UnknownDecay.cc
References G4ParticleDefinition::GetParticleName().
Referenced by G4UnknownDecayPhysics::ConstructProcess().
G4UnknownDecay& G4UnknownDecay::operator= (const G4UnknownDecay & right) private
G4VParticleChange * G4UnknownDecay::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) inline override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 149 of file G4UnknownDecay.hh.
View newest version in sPHENIX GitHub at line 149 of file G4UnknownDecay.hh
References DecayIt().
G4double G4UnknownDecay::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) inline override virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 124 of file G4UnknownDecay.hh.
View newest version in sPHENIX GitHub at line 124 of file G4UnknownDecay.hh
References CLHEP::c_light, DBL_MIN, G4Track::GetDynamicParticle(), G4DynamicParticle::GetPreAssignedDecayProperTime(), G4Track::GetProperTime(), and NotForced.
void G4UnknownDecay::ProcessDescription (std::ostream & outFile) const override virtual
Reimplemented from G4VProcess.
Definition at line 181 of file G4UnknownDecay.cc.
View newest version in sPHENIX GitHub at line 181 of file G4UnknownDecay.cc
References G4VProcess::GetProcessName().
Member Data Documentation
G4ParticleChangeForDecay G4UnknownDecay::fParticleChangeForDecay private
Definition at line 119 of file G4UnknownDecay.hh.
View newest version in sPHENIX GitHub at line 119 of file G4UnknownDecay.hh
Referenced by DecayIt(), and G4UnknownDecay().
const G4double G4UnknownDecay::HighestValue private
Definition at line 116 of file G4UnknownDecay.hh.
View newest version in sPHENIX GitHub at line 116 of file G4UnknownDecay.hh
G4int G4UnknownDecay::verboseLevel private
Definition at line 108 of file G4UnknownDecay.hh.
View newest version in sPHENIX GitHub at line 108 of file G4UnknownDecay.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/decay/include/G4UnknownDecay.hh
geant4/tree/geant4-10.6-release/source/processes/decay/src/G4UnknownDecay.cc