ECCE @ EIC Software: coresoftware/blob/master/offline/packages/HelixHough/helix_hough/HelixHough_vote_pairs_sse.cpp File Reference
HelixHough_vote_pairs_sse.cpp File Reference
#include "HelixHough.h"
#include "fastvec.h"
#include "SimpleHit3D.h"
#include <algorithm>
#include <cmath>
#include <memory>
#include <vector>
Functions
static void counting_sort (unsigned int MAX, std::vector< BinEntryPair5D > &A)
static void counting_sort (unsigned int SIZE, unsigned int MAX, unsigned int *A, unsigned int *B, unsigned int *C)
Function Documentation
static void counting_sort (unsigned int MAX, std::vector< BinEntryPair5D > & A) static
Definition at line 13 of file HelixHough_vote_pairs_sse.cpp.
View newest version in sPHENIX GitHub at line 13 of file HelixHough_vote_pairs_sse.cpp
References B(), and C().
Referenced by HelixHough::vote(), and HelixHough::vote_pairs().
static void counting_sort (unsigned int SIZE, unsigned int MAX, unsigned int * A, unsigned int * B, unsigned int * C) static
Definition at line 36 of file HelixHough_vote_pairs_sse.cpp.
View newest version in sPHENIX GitHub at line 36 of file HelixHough_vote_pairs_sse.cpp