ECCE @ EIC Software: G4PersistencyManagerT< T > Class Template Reference
G4PersistencyManagerT< T > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4PersistencyManagerT.hh>
Public Member Functions
G4PersistencyManagerT (G4PersistencyCenter *pc, std::string n)
~G4PersistencyManagerT ()
G4PersistencyManager * Create ()
void Delete ()
G4VPEventIO * EventIO ()
G4VPHitIO * HitIO ()
G4VPDigitIO * DigitIO ()
G4VHepMCIO * HepMCIO ()
G4VMCTruthIO * MCTruthIO ()
G4VTransactionManager * TransactionManager ()
void Initialize ()
void SetVerboseLevel (int v)
Public Member Functions inherited from G4PersistencyManager
G4PersistencyManager (G4PersistencyCenter *pc, std::string n)
virtual ~G4PersistencyManager ()
std::string GetName ()
void SetVerboseLevel (int v)
G4bool Store (const G4Event *evt)
G4bool Retrieve (G4Event *&evt)
G4bool Store (const G4Run *)
G4bool Retrieve (G4Run *&)
G4bool Store (const G4VPhysicalVolume *)
G4bool Retrieve (G4VPhysicalVolume *&)
Public Member Functions inherited from G4VPersistencyManager
virtual ~G4VPersistencyManager ()
Private Attributes
G4PersistencyManager * pm
Additional Inherited Members
Static Public Member Functions inherited from G4VPersistencyManager
static G4VPersistencyManager * GetPersistencyManager ()
Protected Member Functions inherited from G4VPersistencyManager
G4VPersistencyManager ()
Static Protected Member Functions inherited from G4PersistencyManager
static G4PersistencyManager * GetPersistencyManager ()
Protected Attributes inherited from G4PersistencyManager
G4PersistencyCenter * f_pc
int m_verbose
Detailed Description
template<class T>
class G4PersistencyManagerT< T >
Definition at line 42 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 42 of file G4PersistencyManagerT.hh
Constructor & Destructor Documentation
template<class T > G4PersistencyManagerT< T >::G4PersistencyManagerT (G4PersistencyCenter * pc, std::string n) inline
Definition at line 46 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 46 of file G4PersistencyManagerT.hh
References G4cout, G4endl, G4PersistencyCenter::GetPersistencyCenter(), and G4PersistencyManager::m_verbose.
template<class T > G4PersistencyManagerT< T >::~G4PersistencyManagerT () inline
Definition at line 58 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 58 of file G4PersistencyManagerT.hh
Member Function Documentation
template<class T > G4PersistencyManager* G4PersistencyManagerT< T >::Create () inline virtual
Reimplemented from G4PersistencyManager.
Definition at line 62 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 62 of file G4PersistencyManagerT.hh
References G4PersistencyManager::f_pc, G4PersistencyManager::GetName(), G4PersistencyManagerT< T >::pm, and T.
template<class T > void G4PersistencyManagerT< T >::Delete () inline
Definition at line 69 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 69 of file G4PersistencyManagerT.hh
References G4PersistencyManagerT< T >::pm.
template<class T > G4VPDigitIO* G4PersistencyManagerT< T >::DigitIO () inline virtual
Reimplemented from G4PersistencyManager.
Definition at line 86 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 86 of file G4PersistencyManagerT.hh
References G4PersistencyManager::DigitIO(), and G4PersistencyManagerT< T >::pm.
template<class T > G4VPEventIO* G4PersistencyManagerT< T >::EventIO () inline virtual
Reimplemented from G4PersistencyManager.
Definition at line 72 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 72 of file G4PersistencyManagerT.hh
References G4PersistencyManager::EventIO(), and G4PersistencyManagerT< T >::pm.
template<class T > G4VHepMCIO* G4PersistencyManagerT< T >::HepMCIO () inline
Definition at line 93 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 93 of file G4PersistencyManagerT.hh
References G4PersistencyManagerT< T >::pm.
template<class T > G4VPHitIO* G4PersistencyManagerT< T >::HitIO () inline virtual
Reimplemented from G4PersistencyManager.
Definition at line 79 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 79 of file G4PersistencyManagerT.hh
References G4PersistencyManager::HitIO(), and G4PersistencyManagerT< T >::pm.
template<class T > void G4PersistencyManagerT< T >::Initialize () inline virtual
Reimplemented from G4PersistencyManager.
Definition at line 114 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 114 of file G4PersistencyManagerT.hh
template<class T > G4VMCTruthIO* G4PersistencyManagerT< T >::MCTruthIO () inline virtual
Reimplemented from G4PersistencyManager.
Definition at line 100 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 100 of file G4PersistencyManagerT.hh
References G4PersistencyManager::MCTruthIO(), and G4PersistencyManagerT< T >::pm.
template<class T > void G4PersistencyManagerT< T >::SetVerboseLevel (int v) inline
Definition at line 117 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 117 of file G4PersistencyManagerT.hh
References G4PersistencyManagerT< T >::pm, and G4PersistencyManager::SetVerboseLevel().
template<class T > G4VTransactionManager* G4PersistencyManagerT< T >::TransactionManager () inline virtual
Reimplemented from G4PersistencyManager.
Definition at line 107 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 107 of file G4PersistencyManagerT.hh
References G4PersistencyManagerT< T >::pm, and G4PersistencyManager::TransactionManager().
Member Data Documentation
template<class T > G4PersistencyManager* G4PersistencyManagerT< T >::pm private
Definition at line 121 of file G4PersistencyManagerT.hh.
View newest version in sPHENIX GitHub at line 121 of file G4PersistencyManagerT.hh
Referenced by G4PersistencyManagerT< T >::Create(), G4PersistencyManagerT< T >::Delete(), G4PersistencyManagerT< T >::DigitIO(), G4PersistencyManagerT< T >::EventIO(), G4PersistencyManagerT< T >::HepMCIO(), G4PersistencyManagerT< T >::HitIO(), G4PersistencyManagerT< T >::MCTruthIO(), G4PersistencyManagerT< T >::SetVerboseLevel(), and G4PersistencyManagerT< T >::TransactionManager().
The documentation for this class was generated from the following file:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4PersistencyManagerT.hh