ECCE @ EIC Software: G4QGSBinaryKaonBuilder Class Reference
G4QGSBinaryKaonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBinaryKaonBuilder.hh>
Public Member Functions
G4QGSBinaryKaonBuilder (G4bool quasiElastic=false)
virtual ~G4QGSBinaryKaonBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4KaonPlusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroLInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroSInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VKaonBuilder
G4VKaonBuilder ()=default
virtual ~G4VKaonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4BinaryCascade * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4double theMin
Detailed Description
Definition at line 57 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4QGSBinaryKaonBuilder.hh
Constructor & Destructor Documentation
G4QGSBinaryKaonBuilder::G4QGSBinaryKaonBuilder (G4bool quasiElastic = false)
Definition at line 44 of file G4QGSBinaryKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4QGSBinaryKaonBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSBinaryKaonBuilder::~G4QGSBinaryKaonBuilder () virtual
Definition at line 66 of file G4QGSBinaryKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 66 of file G4QGSBinaryKaonBuilder.cc
References theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4QGSBinaryKaonBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VKaonBuilder.
Definition at line 64 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QGSBinaryKaonBuilder.hh
void G4QGSBinaryKaonBuilder::Build (G4KaonPlusInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 74 of file G4QGSBinaryKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 74 of file G4QGSBinaryKaonBuilder.cc
References G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSBinaryKaonBuilder::Build (G4KaonMinusInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 82 of file G4QGSBinaryKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 82 of file G4QGSBinaryKaonBuilder.cc
References G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSBinaryKaonBuilder::Build (G4KaonZeroLInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 90 of file G4QGSBinaryKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 90 of file G4QGSBinaryKaonBuilder.cc
References G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSBinaryKaonBuilder::Build (G4KaonZeroSInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 98 of file G4QGSBinaryKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 98 of file G4QGSBinaryKaonBuilder.cc
References G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSBinaryKaonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 70 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QGSBinaryKaonBuilder.hh
References theMin.
Member Data Documentation
G4BinaryCascade* G4QGSBinaryKaonBuilder::theCascade private
Definition at line 76 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSBinaryKaonBuilder.hh
Referenced by G4QGSBinaryKaonBuilder().
G4double G4QGSBinaryKaonBuilder::theMin private
Definition at line 80 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4QGSBinaryKaonBuilder.hh
Referenced by Build(), G4QGSBinaryKaonBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSBinaryKaonBuilder::theModel private
Definition at line 75 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSBinaryKaonBuilder.hh
Referenced by Build(), and G4QGSBinaryKaonBuilder().
G4QuasiElasticChannel* G4QGSBinaryKaonBuilder::theQuasiElastic private
Definition at line 79 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QGSBinaryKaonBuilder.hh
Referenced by G4QGSBinaryKaonBuilder(), and ~G4QGSBinaryKaonBuilder().
G4ExcitedStringDecay* G4QGSBinaryKaonBuilder::theStringDecay private
Definition at line 78 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSBinaryKaonBuilder.hh
Referenced by G4QGSBinaryKaonBuilder(), and ~G4QGSBinaryKaonBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSBinaryKaonBuilder::theStringModel private
Definition at line 77 of file G4QGSBinaryKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QGSBinaryKaonBuilder.hh
Referenced by G4QGSBinaryKaonBuilder(), and ~G4QGSBinaryKaonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBinaryKaonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSBinaryKaonBuilder.cc