ECCE @ EIC Software: G4BertiniElectroNuclearBuilder Class Reference
G4BertiniElectroNuclearBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/include/G4BertiniElectroNuclearBuilder.hh>
Public Member Functions
G4BertiniElectroNuclearBuilder (G4bool eNucl)
virtual ~G4BertiniElectroNuclearBuilder ()
virtual void Build ()
Protected Attributes
G4PhotoNuclearProcess * thePhotoNuclearProcess
G4ElectronNuclearProcess * theElectronNuclearProcess
G4PositronNuclearProcess * thePositronNuclearProcess
G4ElectroVDNuclearModel * theElectroReaction
G4CascadeInterface * theGammaReaction
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4QGSModel< G4GammaParticipants > * theStringModel
G4QGSMFragmentation * theFragmentation
G4ExcitedStringDecay * theStringDecay
G4bool wasActivated
G4bool eActivated
Detailed Description
Definition at line 48 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 48 of file G4BertiniElectroNuclearBuilder.hh
Constructor & Destructor Documentation
G4BertiniElectroNuclearBuilder::G4BertiniElectroNuclearBuilder (G4bool eNucl)
Definition at line 56 of file G4BertiniElectroNuclearBuilder.cc.
View newest version in sPHENIX GitHub at line 56 of file G4BertiniElectroNuclearBuilder.cc
G4BertiniElectroNuclearBuilder::~G4BertiniElectroNuclearBuilder () virtual
Definition at line 64 of file G4BertiniElectroNuclearBuilder.cc.
View newest version in sPHENIX GitHub at line 64 of file G4BertiniElectroNuclearBuilder.cc
References theFragmentation, theStringDecay, and wasActivated.
Member Function Documentation
void G4BertiniElectroNuclearBuilder::Build (void) virtual
Reimplemented in G4LENDBertiniGammaElectroNuclearBuilder.
Definition at line 72 of file G4BertiniElectroNuclearBuilder.cc.
View newest version in sPHENIX GitHub at line 72 of file G4BertiniElectroNuclearBuilder.cc
References G4ProcessManager::AddDiscreteProcess(), G4GammaGeneralProcess::AddHadProcess(), eActivated, G4Electron::Electron(), G4Gamma::Gamma(), G4LossTableManager::GetGammaGeneralProcess(), G4ParticleDefinition::GetProcessManager(), GeV, G4HadronicParameters::Instance(), G4LossTableManager::Instance(), G4Positron::Positron(), G4HadronicProcess::RegisterMe(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), G4TheoFSGenerator::SetTransport(), G4InuclParticleNames::sp, theCascade, theElectronNuclearProcess, theElectroReaction, theFragmentation, theGammaReaction, theModel, thePhotoNuclearProcess, thePositronNuclearProcess, theStringDecay, theStringModel, and wasActivated.
Referenced by G4LENDBertiniGammaElectroNuclearBuilder::Build().
Member Data Documentation
G4bool G4BertiniElectroNuclearBuilder::eActivated protected
Definition at line 70 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build().
G4GeneratorPrecompoundInterface* G4BertiniElectroNuclearBuilder::theCascade protected
Definition at line 65 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 65 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build().
G4ElectronNuclearProcess* G4BertiniElectroNuclearBuilder::theElectronNuclearProcess protected
Definition at line 59 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 59 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build().
G4ElectroVDNuclearModel* G4BertiniElectroNuclearBuilder::theElectroReaction protected
Definition at line 61 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build().
G4QGSMFragmentation* G4BertiniElectroNuclearBuilder::theFragmentation protected
Definition at line 67 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 67 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build(), and ~G4BertiniElectroNuclearBuilder().
G4CascadeInterface* G4BertiniElectroNuclearBuilder::theGammaReaction protected
Definition at line 62 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build(), and G4LENDBertiniGammaElectroNuclearBuilder::Build().
G4TheoFSGenerator* G4BertiniElectroNuclearBuilder::theModel protected
Definition at line 64 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build().
G4PhotoNuclearProcess* G4BertiniElectroNuclearBuilder::thePhotoNuclearProcess protected
Definition at line 58 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build(), and G4LENDBertiniGammaElectroNuclearBuilder::Build().
G4PositronNuclearProcess* G4BertiniElectroNuclearBuilder::thePositronNuclearProcess protected
Definition at line 60 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 60 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build().
G4ExcitedStringDecay* G4BertiniElectroNuclearBuilder::theStringDecay protected
Definition at line 68 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build(), and ~G4BertiniElectroNuclearBuilder().
G4QGSModel< G4GammaParticipants >* G4BertiniElectroNuclearBuilder::theStringModel protected
Definition at line 66 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 66 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build().
G4bool G4BertiniElectroNuclearBuilder::wasActivated protected
Definition at line 69 of file G4BertiniElectroNuclearBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BertiniElectroNuclearBuilder.hh
Referenced by Build(), and ~G4BertiniElectroNuclearBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/include/G4BertiniElectroNuclearBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/constructors/gamma_lepto_nuclear/src/G4BertiniElectroNuclearBuilder.cc