ECCE @ EIC Software: G4VPDigitIO Class Reference
G4VPDigitIO Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VPDigitIO.hh>
Public Member Functions
G4VPDigitIO ()
virtual ~G4VPDigitIO ()
G4VPDigitIO * GetVPDigitIO ()
virtual G4bool Store (const G4DCofThisEvent *)=0
virtual G4bool Retrieve (G4DCofThisEvent *&)=0
void SetVerboseLevel (int v)
Protected Member Functions
void SetG4VPDigitIO (G4VPDigitIO *digitMan)
Protected Attributes
G4int m_verbose
G4DCIOcatalog * f_catalog
Static Protected Attributes
static G4ThreadLocal G4VPDigitIO * f_G4VPDigitIO = 0
Detailed Description
Definition at line 41 of file G4VPDigitIO.hh.
View newest version in sPHENIX GitHub at line 41 of file G4VPDigitIO.hh
Constructor & Destructor Documentation
G4VPDigitIO::G4VPDigitIO ()
Definition at line 36 of file G4VPDigitIO.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VPDigitIO.cc
References f_catalog, and G4DCIOcatalog::GetDCIOcatalog().
virtual G4VPDigitIO::~G4VPDigitIO () inline virtual
Definition at line 47 of file G4VPDigitIO.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VPDigitIO.hh
Member Function Documentation
G4VPDigitIO* G4VPDigitIO::GetVPDigitIO () inline
Definition at line 51 of file G4VPDigitIO.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VPDigitIO.hh
References f_G4VPDigitIO.
virtual G4bool G4VPDigitIO::Retrieve (G4DCofThisEvent *&) pure virtual
void G4VPDigitIO::SetG4VPDigitIO (G4VPDigitIO * digitMan) inline protected
Definition at line 68 of file G4VPDigitIO.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPDigitIO.hh
References f_G4VPDigitIO.
void G4VPDigitIO::SetVerboseLevel (int v)
Definition at line 43 of file G4VPDigitIO.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VPDigitIO.cc
References f_catalog, G4DCIOcatalog::GetDCIOmanager(), m_verbose, G4DCIOcatalog::NumberOfDCIOmanager(), G4VPDigitsCollectionIO::SetVerboseLevel(), and v.
Referenced by G4PersistencyManager::SetVerboseLevel().
virtual G4bool G4VPDigitIO::Store (const G4DCofThisEvent *) pure virtual
Referenced by G4PersistencyManager::Store().
Member Data Documentation
G4DCIOcatalog* G4VPDigitIO::f_catalog protected
Definition at line 74 of file G4VPDigitIO.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VPDigitIO.hh
Referenced by G4VPDigitIO(), and SetVerboseLevel().
G4ThreadLocal G4VPDigitIO * G4VPDigitIO::f_G4VPDigitIO = 0 static protected
Definition at line 73 of file G4VPDigitIO.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VPDigitIO.hh
Referenced by GetVPDigitIO(), and SetG4VPDigitIO().
G4int G4VPDigitIO::m_verbose protected
Definition at line 68 of file G4VPDigitIO.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VPDigitIO.hh
Referenced by SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/mctruth/include/G4VPDigitIO.hh
geant4/tree/geant4-10.6-release/source/persistency/mctruth/src/G4VPDigitIO.cc