ECCE @ EIC Software: G4HumanPhantomMaterial Class Reference
G4HumanPhantomMaterial Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4HumanPhantomMaterial.hh>
Public Member Functions
G4HumanPhantomMaterial ()
~G4HumanPhantomMaterial ()
void DefineMaterials ()
G4Material * GetMaterial (G4String)
Private Attributes
G4Material * matH2O
G4Material * soft
G4Material * skeleton
G4Material * lung
G4Material * adipose
G4Material * glandular
G4Material * adipose_glandular
Detailed Description
Definition at line 38 of file G4HumanPhantomMaterial.hh.
View newest version in sPHENIX GitHub at line 38 of file G4HumanPhantomMaterial.hh
Constructor & Destructor Documentation
G4HumanPhantomMaterial::G4HumanPhantomMaterial ()
Definition at line 41 of file G4HumanPhantomMaterial.cc.
View newest version in sPHENIX GitHub at line 41 of file G4HumanPhantomMaterial.cc
G4HumanPhantomMaterial::~G4HumanPhantomMaterial ()
Definition at line 46 of file G4HumanPhantomMaterial.cc.
View newest version in sPHENIX GitHub at line 46 of file G4HumanPhantomMaterial.cc
Member Function Documentation
void G4HumanPhantomMaterial::DefineMaterials ()
Definition at line 49 of file G4HumanPhantomMaterial.cc.
View newest version in sPHENIX GitHub at line 49 of file G4HumanPhantomMaterial.cc
References A(), G4Material::AddElement(), adipose, adipose_glandular, cm3, d, eV, Acts::UnitConstants::g, G4Material::GetIonisation(), glandular, lung, matH2O, mg, mole, G4IonisParamMat::SetMeanExcitationEnergy(), skeleton, soft, and Z.
G4Material * G4HumanPhantomMaterial::GetMaterial (G4String material)
Definition at line 212 of file G4HumanPhantomMaterial.cc.
View newest version in sPHENIX GitHub at line 212 of file G4HumanPhantomMaterial.cc
References G4Material::GetMaterial().
Member Data Documentation
G4Material* G4HumanPhantomMaterial::adipose private
Definition at line 59 of file G4HumanPhantomMaterial.hh.
View newest version in sPHENIX GitHub at line 59 of file G4HumanPhantomMaterial.hh
Referenced by DefineMaterials().
G4Material* G4HumanPhantomMaterial::adipose_glandular private
Definition at line 61 of file G4HumanPhantomMaterial.hh.
View newest version in sPHENIX GitHub at line 61 of file G4HumanPhantomMaterial.hh
Referenced by DefineMaterials().
G4Material* G4HumanPhantomMaterial::glandular private
Definition at line 60 of file G4HumanPhantomMaterial.hh.
View newest version in sPHENIX GitHub at line 60 of file G4HumanPhantomMaterial.hh
Referenced by DefineMaterials().
G4Material* G4HumanPhantomMaterial::lung private
Definition at line 58 of file G4HumanPhantomMaterial.hh.
View newest version in sPHENIX GitHub at line 58 of file G4HumanPhantomMaterial.hh
Referenced by DefineMaterials().
G4Material* G4HumanPhantomMaterial::matH2O private
Definition at line 55 of file G4HumanPhantomMaterial.hh.
View newest version in sPHENIX GitHub at line 55 of file G4HumanPhantomMaterial.hh
Referenced by DefineMaterials().
G4Material* G4HumanPhantomMaterial::skeleton private
Definition at line 57 of file G4HumanPhantomMaterial.hh.
View newest version in sPHENIX GitHub at line 57 of file G4HumanPhantomMaterial.hh
Referenced by DefineMaterials().
G4Material* G4HumanPhantomMaterial::soft private
Definition at line 56 of file G4HumanPhantomMaterial.hh.
View newest version in sPHENIX GitHub at line 56 of file G4HumanPhantomMaterial.hh
Referenced by DefineMaterials().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4HumanPhantomMaterial.hh
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/src/G4HumanPhantomMaterial.cc