ECCE @ EIC Software: G4EmLowEParametersMessenger Class Reference
G4EmLowEParametersMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmLowEParametersMessenger.hh>
Public Member Functions
G4EmLowEParametersMessenger (G4EmLowEParameters *)
virtual ~G4EmLowEParametersMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String) override
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
G4EmLowEParameters * theParameters
G4UIcmdWithABool * deCmd
G4UIcmdWithABool * dirFluoCmd
G4UIcmdWithABool * auCmd
G4UIcmdWithABool * auCascadeCmd
G4UIcmdWithABool * pixeCmd
G4UIcmdWithABool * dcutCmd
G4UIcmdWithABool * dnafCmd
G4UIcmdWithABool * dnasCmd
G4UIcmdWithABool * dnamscCmd
G4UIcmdWithAString * pixeXsCmd
G4UIcmdWithAString * pixeeXsCmd
G4UIcmdWithAString * dnaSolCmd
G4UIcmdWithAString * meCmd
G4UIcommand * dnaCmd
G4UIcommand * deexCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 64 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file G4EmLowEParametersMessenger.hh
Constructor & Destructor Documentation
G4EmLowEParametersMessenger::G4EmLowEParametersMessenger (G4EmLowEParameters * ptr) explicit
Definition at line 58 of file G4EmLowEParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 58 of file G4EmLowEParametersMessenger.cc
References auCascadeCmd, auCmd, G4UIcommand::AvailableForStates(), dcutCmd, deCmd, deexCmd, dirFluoCmd, dnaCmd, dnafCmd, dnamscCmd, dnasCmd, dnaSolCmd, G4State_Idle, G4State_Init, G4State_PreInit, meCmd, pixeCmd, pixeeXsCmd, pixeXsCmd, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithABool::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIparameter::SetParameterCandidates(), G4UIcmdWithAString::SetParameterName(), and G4UIcmdWithABool::SetParameterName().
G4EmLowEParametersMessenger::~G4EmLowEParametersMessenger () virtual
Definition at line 176 of file G4EmLowEParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 176 of file G4EmLowEParametersMessenger.cc
References auCascadeCmd, auCmd, dcutCmd, deCmd, deexCmd, dirFluoCmd, dnaCmd, dnafCmd, dnamscCmd, dnasCmd, dnaSolCmd, meCmd, pixeCmd, pixeeXsCmd, and pixeXsCmd.
Member Function Documentation
void G4EmLowEParametersMessenger::SetNewValue (G4UIcommand * command, G4String newValue) override virtual
Reimplemented from G4UImessenger.
Definition at line 197 of file G4EmLowEParametersMessenger.cc.
View newest version in sPHENIX GitHub at line 197 of file G4EmLowEParametersMessenger.cc
References G4EmLowEParameters::AddDNA(), G4EmLowEParameters::AddMicroElec(), G4UImanager::ApplyCommand(), auCascadeCmd, auCmd, dcutCmd, deCmd, deexCmd, dirFluoCmd, dnaCmd, dnafCmd, dnamscCmd, dnasCmd, dnaSolCmd, fDNAUnknownModel, fKreipl2009eSolvation, fMeesungnoen2002eSolvation, fMeesungnoensolid2002eSolvation, fRitchie1994eSolvation, fTerrisol1990eSolvation, G4UIcmdWithABool::GetNewBoolValue(), G4UImanager::GetUIpointer(), meCmd, pixeCmd, pixeeXsCmd, pixeXsCmd, s1, G4EmLowEParameters::SetAuger(), G4EmLowEParameters::SetBeardenFluoDir(), G4EmLowEParameters::SetDeexActiveRegion(), G4EmLowEParameters::SetDeexcitationIgnoreCut(), G4EmLowEParameters::SetDNAElectronMsc(), G4EmLowEParameters::SetDNAeSolvationSubType(), G4EmLowEParameters::SetDNAFast(), G4EmLowEParameters::SetDNAStationary(), G4EmLowEParameters::SetFluo(), G4EmLowEParameters::SetPixe(), G4EmLowEParameters::SetPIXECrossSectionModel(), G4EmLowEParameters::SetPIXEElectronCrossSectionModel(), and theParameters.
Member Data Documentation
G4UIcmdWithABool* G4EmLowEParametersMessenger::auCascadeCmd private
Definition at line 80 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithABool* G4EmLowEParametersMessenger::auCmd private
Definition at line 79 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithABool* G4EmLowEParametersMessenger::dcutCmd private
Definition at line 82 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 82 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithABool* G4EmLowEParametersMessenger::deCmd private
Definition at line 77 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcommand* G4EmLowEParametersMessenger::deexCmd private
Definition at line 93 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 93 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithABool* G4EmLowEParametersMessenger::dirFluoCmd private
Definition at line 78 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcommand* G4EmLowEParametersMessenger::dnaCmd private
Definition at line 92 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 92 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithABool* G4EmLowEParametersMessenger::dnafCmd private
Definition at line 83 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 83 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithABool* G4EmLowEParametersMessenger::dnamscCmd private
Definition at line 85 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 85 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithABool* G4EmLowEParametersMessenger::dnasCmd private
Definition at line 84 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 84 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithAString* G4EmLowEParametersMessenger::dnaSolCmd private
Definition at line 89 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 89 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithAString* G4EmLowEParametersMessenger::meCmd private
Definition at line 91 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 91 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithABool* G4EmLowEParametersMessenger::pixeCmd private
Definition at line 81 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 81 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithAString* G4EmLowEParametersMessenger::pixeeXsCmd private
Definition at line 88 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 88 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4UIcmdWithAString* G4EmLowEParametersMessenger::pixeXsCmd private
Definition at line 87 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 87 of file G4EmLowEParametersMessenger.hh
Referenced by G4EmLowEParametersMessenger(), SetNewValue(), and ~G4EmLowEParametersMessenger().
G4EmLowEParameters* G4EmLowEParametersMessenger::theParameters private
Definition at line 75 of file G4EmLowEParametersMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file G4EmLowEParametersMessenger.hh
Referenced by SetNewValue().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/include/G4EmLowEParametersMessenger.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/utils/src/G4EmLowEParametersMessenger.cc