ECCE @ EIC Software: G4VViewer Class Reference
G4VViewer Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VViewer.hh>
Classes
class G4Spline
Public Member Functions
G4VViewer (G4VSceneHandler &, G4int id, const G4String &name="")
virtual ~G4VViewer ()
virtual void Initialise ()
virtual void ResetView ()
virtual void SetView ()=0
virtual void ClearView ()=0
virtual void DrawView ()=0
void RefreshView ()
virtual void ShowView ()
virtual void FinishView ()
std::vector< G4ThreeVector > ComputeFlyThrough (G4Vector3D *)
const G4String & GetName () const
const G4String & GetShortName () const
void SetName (const G4String &)
G4int GetViewId () const
G4VSceneHandler * GetSceneHandler () const
const G4ViewParameters & GetViewParameters () const
const G4ViewParameters & GetDefaultViewParameters () const
virtual const std::vector
< G4ModelingParameters::VisAttributesModifier > * GetPrivateVisAttributesModifiers () const
void SetViewParameters (const G4ViewParameters &vp)
void SetDefaultViewParameters (const G4ViewParameters &vp)
const G4VisAttributes * GetApplicableVisAttributes (const G4VisAttributes *) const
void SetNeedKernelVisit (G4bool need)
void NeedKernelVisit ()
void ProcessView ()
Protected Member Functions
void SetTouchable (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath)
void TouchableSetVisibility (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath, G4bool visibility)
void TouchableSetColour (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > &fullPath, const G4Colour &)
Protected Attributes
G4VSceneHandler & fSceneHandler
G4int fViewId
G4String fName
G4String fShortName
G4ViewParameters fVP
G4ViewParameters fDefaultVP
G4bool fNeedKernelVisit
Friends
std::ostream & operator<< (std::ostream &os, const G4VViewer &v)
Detailed Description
Definition at line 45 of file G4VViewer.hh.
View newest version in sPHENIX GitHub at line 45 of file G4VViewer.hh
Constructor & Destructor Documentation
G4VViewer::G4VViewer (G4VSceneHandler & sceneHandler, G4int id, const G4String & name = "")
Definition at line 45 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VViewer.cc
References fDefaultVP, fName, fSceneHandler, fShortName, fViewId, fVP, G4VisManager::GetDefaultViewParameters(), G4VisManager::GetInstance(), G4VSceneHandler::GetName(), and G4String::strip().
G4VViewer::~G4VViewer () virtual
Definition at line 67 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 67 of file G4VViewer.cc
References fSceneHandler, and G4VSceneHandler::RemoveViewerFromList().
Member Function Documentation
virtual void G4VViewer::ClearView () pure virtual
Implemented in G4GMocrenFileViewer, G4DAWNFILEViewer, G4HepRepFileViewer, G4HepRepViewer, G4RayTracerViewer, G4XXXFileViewer, G4XXXViewer, G4VRML2FileViewer, G4VRML1FileViewer, G4XXXSGViewer, G4XXXStoredViewer, and G4VTreeViewer.
Referenced by G4VisManager::GeometryHasChanged(), G4VisManager::NotifyHandlers(), G4VisCommandViewerClear::SetNewValue(), and G4VisCommandViewerRebuild::SetNewValue().
std::vector< G4ThreeVector > G4VViewer::ComputeFlyThrough (G4Vector3D *)
Definition at line 205 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 205 of file G4VViewer.cc
References G4VViewer::G4Spline::AddSplinePoint(), G4cout, G4endl, G4VViewer::G4Spline::GetInterpolatedSplinePoint(), t, HepGeom::BasicVector3D< T >::x(), HepGeom::BasicVector3D< T >::y(), and HepGeom::BasicVector3D< T >::z().
virtual void G4VViewer::DrawView () pure virtual
Implemented in G4GMocrenFileViewer, G4DAWNFILEViewer, G4HepRepFileViewer, G4HepRepViewer, G4RayTracerViewer, G4XXXFileViewer, G4XXXViewer, G4VRML2FileViewer, G4VRML1FileViewer, G4XXXSGViewer, G4XXXStoredViewer, and G4VTreeViewer.
Referenced by G4HepRepSceneHandler::closeHepRep(), and G4VisCommandViewerRebuild::SetNewValue().
void G4VViewer::FinishView (void) virtual
Reimplemented in G4HepRepViewer, G4VRML2FileViewer, and G4VRML1FileViewer.
Definition at line 100 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 100 of file G4VViewer.cc
Referenced by G4XXXSGViewer::DrawView(), G4XXXStoredViewer::DrawView(), G4XXXViewer::DrawView(), G4XXXFileViewer::DrawView(), G4HepRepViewer::FinishView(), G4VisManager::GeometryHasChanged(), G4VisManager::NotifyHandlers(), and G4VisCommandViewerClear::SetNewValue().
const G4VisAttributes* G4VViewer::GetApplicableVisAttributes (const G4VisAttributes *) const
Referenced by G4HepRepFileSceneHandler::AddSolid(), and G4GMocrenFileSceneHandler::IsVisible().
const G4ViewParameters& G4VViewer::GetDefaultViewParameters () const
Referenced by G4VisCommandsViewerSet::SetNewValue().
const G4String& G4VViewer::GetName () const
Referenced by G4VVisCommand::InterpolateViews(), G4VisCommandDrawTree::SetNewValue(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandViewerAddCutawayPlane::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandViewerChangeCutawayPlane::SetNewValue(), G4VisCommandViewerClearCutawayPlanes::SetNewValue(), G4VisCommandViewerClearVisAttributesModifiers::SetNewValue(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandViewerColourByDensity::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), and G4VisCommandViewerRebuild::SetNewValue().
virtual const std::vector<G4ModelingParameters::VisAttributesModifier>* G4VViewer::GetPrivateVisAttributesModifiers () const virtual
Referenced by G4VisCommandsViewerSet::SetNewValue(), and G4VisCommandViewerSave::SetNewValue().
G4VSceneHandler* G4VViewer::GetSceneHandler () const
Referenced by G4VVisCommand::RefreshIfRequired(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandViewerClearTransients::SetNewValue(), G4VisCommandViewerRefresh::SetNewValue(), G4VisCommandViewerRebuild::SetNewValue(), G4VisCommandViewerSave::SetNewValue(), G4VisCommandViewerUpdate::SetNewValue(), G4HepRepViewer::ShowView(), and G4HepRepViewer::~G4HepRepViewer().
const G4String& G4VViewer::GetShortName () const
G4int G4VViewer::GetViewId () const
Referenced by G4XXX::CreateViewer(), G4XXXFile::CreateViewer(), G4XXXSG::CreateViewer(), G4XXXStored::CreateViewer(), G4HepRepFile::CreateViewer(), and G4RayTracer::CreateViewer().
const G4ViewParameters& G4VViewer::GetViewParameters () const
Referenced by G4HepRepSceneHandler::addTopLevelAttributes(), G4VSceneHandler::CreateSectionSolid(), G4VisManager::EndOfRun(), G4VSceneHandler::GetAuxEdgeVisible(), G4VSceneHandler::GetNoOfSides(), G4VVisCommand::RefreshIfRequired(), G4VSceneHandler::RequestPrimitives(), G4VisCommandsTouchable::SetNewValue(), G4VisCommandsTouchableSet::SetNewValue(), G4VisCommandViewerAddCutawayPlane::SetNewValue(), G4VisCommandDrawView::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerCentreOn::SetNewValue(), G4VisCommandDrawLogicalVolume::SetNewValue(), G4VisCommandViewerChangeCutawayPlane::SetNewValue(), G4VisCommandViewerClearCutawayPlanes::SetNewValue(), G4VisCommandSceneNotifyHandlers::SetNewValue(), G4VisCommandViewerClearVisAttributesModifiers::SetNewValue(), G4VisCommandViewerClone::SetNewValue(), G4VisCommandViewerColourByDensity::SetNewValue(), G4VisCommandViewerCopyViewFrom::SetNewValue(), G4VisCommandViewerCreate::SetNewValue(), G4VisCommandViewerDolly::SetNewValue(), G4VisCommandGeometrySetDaughtersInvisible::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), G4VisCommandViewerPan::SetNewValue(), G4VisCommandViewerSave::SetNewValue(), G4VisCommandGeometrySetVisibility::SetNewValue(), G4VisCommandViewerScale::SetNewValue(), G4VisCommandSceneAddLogo::SetNewValue(), G4VisCommandViewerZoom::SetNewValue(), G4VisCommandSceneAddScale::SetNewValue(), and G4VisCommandGeometrySetVisibility::SetNewValueOnLV().
virtual void G4VViewer::Initialise () virtual
Reimplemented in G4RayTracerViewer.
void G4VViewer::NeedKernelVisit ()
Definition at line 77 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 77 of file G4VViewer.cc
References fNeedKernelVisit.
Referenced by G4VTreeViewer::DrawView(), G4VRML1FileViewer::DrawView(), G4VRML2FileViewer::DrawView(), G4XXXFileViewer::DrawView(), G4XXXViewer::DrawView(), G4HepRepViewer::DrawView(), G4HepRepFileViewer::DrawView(), G4DAWNFILEViewer::DrawView(), G4GMocrenFileViewer::DrawView(), G4VisManager::GeometryHasChanged(), G4XXXStoredViewer::KernelVisitDecision(), G4XXXSGViewer::KernelVisitDecision(), G4VisManager::NotifyHandlers(), and G4VisCommandViewerRebuild::SetNewValue().
void G4VViewer::ProcessView ()
Definition at line 104 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 104 of file G4VViewer.cc
References G4VSceneHandler::ClearStore(), fNeedKernelVisit, fSceneHandler, and G4VSceneHandler::ProcessScene().
Referenced by G4VTreeViewer::DrawView(), G4XXXSGViewer::DrawView(), G4XXXStoredViewer::DrawView(), G4VRML1FileViewer::DrawView(), G4VRML2FileViewer::DrawView(), G4XXXFileViewer::DrawView(), G4RayTracerViewer::DrawView(), G4XXXViewer::DrawView(), G4HepRepViewer::DrawView(), G4HepRepFileViewer::DrawView(), G4DAWNFILEViewer::DrawView(), and G4GMocrenFileViewer::DrawView().
void G4VViewer::RefreshView ()
Referenced by G4VisManager::EndOfRun(), G4VVisCommand::InterpolateViews(), and G4VisCommandViewerInterpolate::SetNewValue().
virtual void G4VViewer::ResetView () virtual
Referenced by G4VisCommandViewerReset::SetNewValue().
void G4VViewer::SetDefaultViewParameters (const G4ViewParameters & vp)
void G4VViewer::SetName (const G4String & name)
Definition at line 71 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 71 of file G4VViewer.cc
References fName, fShortName, and G4String::strip().
void G4VViewer::SetNeedKernelVisit (G4bool need)
void G4VViewer::SetTouchable (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > & fullPath) protected
Definition at line 124 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 124 of file G4VViewer.cc
References G4UImanager::ApplyCommand(), and G4UImanager::GetUIpointer().
virtual void G4VViewer::SetView () pure virtual
Implemented in G4GMocrenFileViewer, G4DAWNFILEViewer, G4VRML2FileViewer, G4VRML1FileViewer, G4HepRepFileViewer, G4HepRepViewer, G4RayTracerViewer, G4XXXFileViewer, G4XXXViewer, G4XXXSGViewer, G4XXXStoredViewer, and G4VTreeViewer.
Referenced by G4VisManager::GeometryHasChanged(), G4VisManager::NotifyHandlers(), G4VisManager::SetCurrentViewer(), G4VisCommandViewerClear::SetNewValue(), and G4VisCommandViewerRebuild::SetNewValue().
void G4VViewer::SetViewParameters (const G4ViewParameters & vp)
Definition at line 119 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 119 of file G4VViewer.cc
References fVP.
Referenced by G4VVisCommand::InterpolateViews(), G4VisCommandDrawView::SetNewValue(), G4VisCommandsViewerSet::SetNewValue(), G4VisCommandViewerInterpolate::SetNewValue(), and G4VVisCommand::SetViewParameters().
void G4VViewer::ShowView (void) virtual
Reimplemented in G4GMocrenFileViewer, G4DAWNFILEViewer, G4HepRepFileViewer, G4HepRepViewer, G4XXXFileViewer, G4XXXViewer, G4VRML2FileViewer, G4VRML1FileViewer, G4XXXSGViewer, and G4XXXStoredViewer.
Definition at line 102 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 102 of file G4VViewer.cc
Referenced by G4VisManager::EndOfEvent(), G4VisManager::EndOfRun(), G4VVisCommand::InterpolateViews(), G4HepRepViewer::ShowView(), and G4HepRepFileViewer::ShowView().
void G4VViewer::TouchableSetColour (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > & fullPath, const G4Colour & colour) protected
Definition at line 171 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 171 of file G4VViewer.cc
References G4cout, G4endl, G4Colour::GetAlpha(), G4Colour::GetBlue(), G4Colour::GetGreen(), G4PhysicalVolumeModel::GetPVNameCopyNoPath(), G4Colour::GetRed(), G4UImanager::GetUIpointer(), G4VisAttributes::SetColour(), and G4ModelingParameters::VASColour.
void G4VViewer::TouchableSetVisibility (const std::vector< G4PhysicalVolumeModel::G4PhysicalVolumeNodeID > & fullPath, G4bool visibility) protected
Definition at line 137 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 137 of file G4VViewer.cc
References G4cout, G4endl, G4PhysicalVolumeModel::GetPVNameCopyNoPath(), G4UImanager::GetUIpointer(), G4VisAttributes::SetVisibility(), and G4ModelingParameters::VASVisibility.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4VViewer & v) friend
Definition at line 383 of file G4VViewer.cc.
View newest version in sPHENIX GitHub at line 383 of file G4VViewer.cc
Member Data Documentation
G4ViewParameters G4VViewer::fDefaultVP protected
Definition at line 220 of file G4VViewer.hh.
View newest version in sPHENIX GitHub at line 220 of file G4VViewer.hh
Referenced by G4HepRepViewer::G4HepRepViewer(), and G4VViewer().
G4String G4VViewer::fName protected
Definition at line 217 of file G4VViewer.hh.
View newest version in sPHENIX GitHub at line 217 of file G4VViewer.hh
Referenced by G4XXXSGViewer::DrawFromStore(), G4XXXStoredViewer::DrawFromStore(), G4VViewer(), operator<<(), and SetName().
G4bool G4VViewer::fNeedKernelVisit protected
Definition at line 224 of file G4VViewer.hh.
View newest version in sPHENIX GitHub at line 224 of file G4VViewer.hh
Referenced by G4XXXSGViewer::DrawView(), G4XXXStoredViewer::DrawView(), NeedKernelVisit(), and ProcessView().
G4VSceneHandler& G4VViewer::fSceneHandler protected
Definition at line 215 of file G4VViewer.hh.
View newest version in sPHENIX GitHub at line 215 of file G4VViewer.hh
Referenced by G4XXXSGViewer::DrawFromStore(), G4XXXStoredViewer::DrawFromStore(), G4VViewer(), G4XXXSGViewer::KernelVisitDecision(), G4XXXStoredViewer::KernelVisitDecision(), ProcessView(), G4RayTracerViewer::SetView(), G4XXXViewer::ShowView(), and ~G4VViewer().
G4String G4VViewer::fShortName protected
Definition at line 218 of file G4VViewer.hh.
View newest version in sPHENIX GitHub at line 218 of file G4VViewer.hh
Referenced by G4RayTracerViewer::DrawView(), G4VViewer(), and SetName().
G4int G4VViewer::fViewId protected
Definition at line 216 of file G4VViewer.hh.
View newest version in sPHENIX GitHub at line 216 of file G4VViewer.hh
Referenced by G4VViewer().
G4ViewParameters G4VViewer::fVP protected
Definition at line 219 of file G4VViewer.hh.
View newest version in sPHENIX GitHub at line 219 of file G4VViewer.hh
Referenced by G4XXXSGViewer::CompareForKernelVisit(), G4XXXStoredViewer::CompareForKernelVisit(), G4RayTracerViewer::DrawView(), G4HepRepViewer::G4HepRepViewer(), G4VViewer(), G4RayTracerViewer::Initialise(), G4XXXSGViewer::KernelVisitDecision(), G4XXXStoredViewer::KernelVisitDecision(), operator<<(), G4DAWNFILEViewer::SendDrawingStyleToDAWNGUI(), G4VRML2FileViewer::SendViewParameters(), G4DAWNFILEViewer::SendViewParameters(), G4RayTracerViewer::SetView(), and SetViewParameters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VViewer.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VViewer.cc