ECCE @ EIC Software: G4FermiPhaseSpaceDecay Class Reference
G4FermiPhaseSpaceDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiPhaseSpaceDecay.hh>
Public Member Functions
G4FermiPhaseSpaceDecay ()
~G4FermiPhaseSpaceDecay ()
std::vector< G4LorentzVector * > * Decay (G4double parent_mass, const std::vector< G4double > &fragment_masses) const
Private Member Functions
G4double PtwoBody (G4double E, G4double P1, G4double P2) const
G4double BetaKopylov (G4int, CLHEP::HepRandomEngine *) const
std::vector< G4LorentzVector * > * KopylovNBodyDecay (G4double, const std::vector< G4double > &) const
G4FermiPhaseSpaceDecay (const G4FermiPhaseSpaceDecay &)=delete
const G4FermiPhaseSpaceDecay & operator= (const G4FermiPhaseSpaceDecay &)=delete
G4bool operator== (const G4FermiPhaseSpaceDecay &)=delete
G4bool operator!= (const G4FermiPhaseSpaceDecay &)=delete
Private Attributes
G4Pow * g4calc
Detailed Description
Definition at line 49 of file G4FermiPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 49 of file G4FermiPhaseSpaceDecay.hh
Constructor & Destructor Documentation
G4FermiPhaseSpaceDecay::G4FermiPhaseSpaceDecay ()
Definition at line 46 of file G4FermiPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 46 of file G4FermiPhaseSpaceDecay.cc
References g4calc, and G4Pow::GetInstance().
G4FermiPhaseSpaceDecay::~G4FermiPhaseSpaceDecay ()
Definition at line 51 of file G4FermiPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 51 of file G4FermiPhaseSpaceDecay.cc
G4FermiPhaseSpaceDecay::G4FermiPhaseSpaceDecay (const G4FermiPhaseSpaceDecay &) private delete
Member Function Documentation
G4double G4FermiPhaseSpaceDecay::BetaKopylov (G4int K, CLHEP::HepRandomEngine * rndmEngine) const private
Definition at line 114 of file G4FermiPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 114 of file G4FermiPhaseSpaceDecay.cc
References F, CLHEP::HepRandomEngine::flat(), g4calc, N, and G4Pow::powN().
std::vector< G4LorentzVector * > * G4FermiPhaseSpaceDecay::Decay (G4double parent_mass, const std::vector< G4double > & fragment_masses) const
Definition at line 54 of file G4FermiPhaseSpaceDecay.cc.
View newest version in sPHENIX GitHub at line 54 of file G4FermiPhaseSpaceDecay.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), CLHEP::eV, G4RandomDirection(), k, max, N, P, CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setVect(), and T.
Referenced by G4BinaryCascade::DecayVoidNucleus().
std::vector<G4LorentzVector*>* G4FermiPhaseSpaceDecay::KopylovNBodyDecay (G4double , const std::vector< G4double > &) const private
G4bool G4FermiPhaseSpaceDecay::operator!= (const G4FermiPhaseSpaceDecay &) private delete
const G4FermiPhaseSpaceDecay& G4FermiPhaseSpaceDecay::operator= (const G4FermiPhaseSpaceDecay &) private delete
G4bool G4FermiPhaseSpaceDecay::operator== (const G4FermiPhaseSpaceDecay &) private delete
G4double G4FermiPhaseSpaceDecay::PtwoBody (G4double E, G4double P1, G4double P2) const inline private
Definition at line 78 of file G4FermiPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 78 of file G4FermiPhaseSpaceDecay.hh
References E, P, and P2.
Member Data Documentation
G4Pow* G4FermiPhaseSpaceDecay::g4calc private
Definition at line 74 of file G4FermiPhaseSpaceDecay.hh.
View newest version in sPHENIX GitHub at line 74 of file G4FermiPhaseSpaceDecay.hh
Referenced by BetaKopylov(), and G4FermiPhaseSpaceDecay().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/include/G4FermiPhaseSpaceDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/fermi_breakup/src/G4FermiPhaseSpaceDecay.cc