ECCE @ EIC Software: G4tgrEvaluator Class Reference
G4tgrEvaluator Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrEvaluator.hh>
Public Member Functions
G4tgrEvaluator ()
~G4tgrEvaluator ()
void print_error (G4int status) const
Public Member Functions inherited from HepTool::Evaluator
Evaluator ()
~Evaluator ()
double evaluate (const char *expression)
int status () const
int error_position () const
void print_error () const
std::string error_name () const
void setVariable (const char *name, double value)
void setVariable (const char *name, const char *expression)
void setFunction (const char *name, double(*fun)())
void setFunction (const char *name, double(*fun)(double))
void setFunction (const char *name, double(*fun)(double, double))
void setFunction (const char *name, double(*fun)(double, double, double))
void setFunction (const char *name, double(*fun)(double, double, double, double))
void setFunction (const char *name, double(*fun)(double, double, double, double, double))
bool findVariable (const char *name) const
bool findFunction (const char *name, int npar) const
void removeVariable (const char *name)
void removeFunction (const char *name, int npar)
void clear ()
void setStdMath ()
void setSystemOfUnits (double meter=1.0, double kilogram=1.0, double second=1.0, double ampere=1.0, double kelvin=1.0, double mole=1.0, double candela=1.0)
Private Member Functions
void AddCommonFunctions ()
Additional Inherited Members
Public Types inherited from HepTool::Evaluator
enum {
OK, WARNING_EXISTING_VARIABLE, WARNING_EXISTING_FUNCTION, WARNING_BLANK_STRING,
ERROR_NOT_A_NAME, ERROR_SYNTAX_ERROR, ERROR_UNPAIRED_PARENTHESIS, ERROR_UNEXPECTED_SYMBOL,
ERROR_UNKNOWN_VARIABLE, ERROR_UNKNOWN_FUNCTION, ERROR_EMPTY_PARAMETER, ERROR_CALCULATION_ERROR
}
Detailed Description
Definition at line 45 of file G4tgrEvaluator.hh.
View newest version in sPHENIX GitHub at line 45 of file G4tgrEvaluator.hh
Constructor & Destructor Documentation
G4tgrEvaluator::G4tgrEvaluator ()
Definition at line 40 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 40 of file G4tgrEvaluator.cc
References AddCommonFunctions().
G4tgrEvaluator::~G4tgrEvaluator ()
Definition at line 47 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 47 of file G4tgrEvaluator.cc
Member Function Documentation
void G4tgrEvaluator::AddCommonFunctions () private
Definition at line 87 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 87 of file G4tgrEvaluator.cc
References facos(), fasin(), fatan(), fatan2(), fcos(), fcosh(), fexp(), flog(), flog10(), fpow(), fsin(), fsinh(), fsqrt(), ftan(), ftanh(), and HepTool::Evaluator::setFunction().
Referenced by G4tgrEvaluator().
void G4tgrEvaluator::print_error (G4int status) const
Definition at line 53 of file G4tgrEvaluator.cc.
View newest version in sPHENIX GitHub at line 53 of file G4tgrEvaluator.cc
References HepTool::Evaluator::ERROR_SYNTAX_ERROR, G4cerr, G4endl, and HepTool::Evaluator::print_error().
Referenced by G4tgrUtils::GetDouble().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrEvaluator.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrEvaluator.cc