ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/MCGIDI_distribution.cc File Reference
MCGIDI_distribution.cc File Reference
#include <string.h>
#include <cmath>
#include "MCGIDI.h"
#include "MCGIDI_misc.h"
Functions
MCGIDI_distribution * MCGIDI_distribution_new (statusMessageReporting *smr)
int MCGIDI_distribution_initialize (statusMessageReporting *, MCGIDI_distribution *distribution)
MCGIDI_distribution * MCGIDI_distribution_free (statusMessageReporting *smr, MCGIDI_distribution *distribution)
int MCGIDI_distribution_release (statusMessageReporting *smr, MCGIDI_distribution *distribution)
int MCGIDI_distribution_parseFromTOM (statusMessageReporting *smr, xDataTOM_element *element, MCGIDI_product *product, MCGIDI_POPs *, ptwXYPoints *norms)
Function Documentation
MCGIDI_distribution* MCGIDI_distribution_free (statusMessageReporting * smr, MCGIDI_distribution * distribution)
Definition at line 38 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 38 of file MCGIDI_distribution.cc
References MCGIDI_distribution_release(), and smr_freeMemory().
Referenced by MCGIDI_distribution_new().
int MCGIDI_distribution_initialize (statusMessageReporting * , MCGIDI_distribution * distribution)
Definition at line 30 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 30 of file MCGIDI_distribution.cc
Referenced by MCGIDI_distribution_new(), MCGIDI_distribution_parseFromTOM(), and MCGIDI_distribution_release().
MCGIDI_distribution* MCGIDI_distribution_new (statusMessageReporting * smr)
Definition at line 19 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 19 of file MCGIDI_distribution.cc
References MCGIDI_distribution_free(), MCGIDI_distribution_initialize(), and smr_malloc2.
int MCGIDI_distribution_parseFromTOM (statusMessageReporting * smr, xDataTOM_element * element, MCGIDI_product * product, MCGIDI_POPs * , ptwXYPoints * norms)
Definition at line 61 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 61 of file MCGIDI_distribution.cc
References MCGIDI_product_s::distribution, check_license::err(), MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_distribution_initialize(), MCGIDI_distribution_release(), MCGIDI_distributionType_none_e, MCGIDI_distributionType_unknown_e, MCGIDI_energyAngular_parseFromTOM(), MCGIDI_energyType_discreteGamma, MCGIDI_energyType_primaryGamma, MCGIDI_energyType_unknown, MCGIDI_LLNLAngular_angularEnergy_parseFromTOM(), MCGIDI_misc_PQUStringToDoubleInUnitOf(), MCGIDI_uncorrelated_parseFromTOM(), MCGIDI_POP_s::name, MCGIDI_product_s::pop, MCGIDI_distribution_s::product, smr_setReportError2, smr_unknownID, MCGIDI_distribution_s::type, xDataTOM_getAttributesValueInElement(), and xDataTOME_getOneElementByName().
Referenced by MCGIDI_product_parseFromTOM().
int MCGIDI_distribution_release (statusMessageReporting * smr, MCGIDI_distribution * distribution)
Definition at line 47 of file MCGIDI_distribution.cc.
View newest version in sPHENIX GitHub at line 47 of file MCGIDI_distribution.cc
References MCGIDI_distribution_s::angular, MCGIDI_distribution_s::angularEnergy, MCGIDI_distribution_s::energy, MCGIDI_distribution_s::energyAngular, MCGIDI_distribution_s::KalbachMann, MCGIDI_angular_free(), MCGIDI_angularEnergy_free(), MCGIDI_distribution_initialize(), MCGIDI_energy_free(), MCGIDI_energyAngular_free(), and MCGIDI_KalbachMann_free().
Referenced by MCGIDI_distribution_free(), MCGIDI_distribution_parseFromTOM(), and MCGIDI_product_release().