ECCE @ EIC Software: G4UserRunAction Class Reference
G4UserRunAction Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4UserRunAction.hh>
Inherited by B01RunAction, B02RunAction, B03RunAction, B1ConRunAction, B1RunAction, B1RunAction, B2RunAction, B2RunAction, B2RunAction, B3aRunAction, B3bRunAction, B4bRunAction, B4RunAction, B4RunAction, B4RunAction, B5RunAction, BrachyRunAction, CB_G4UserRunAction, CCalRunAction, CexmcRunAction, CML2RunAction, demo.MyRunAction, DicomRunAction, DMXRunAction, doiPETRunAction, ElectronRunAction, eRositaRunAction, ExGflashRunAction, ExGflashRunAction, ExGflashRunAction, ExGflashRunAction, ExN02RunAction, ExN04RunAction, ExN04RunAction, ExP01RunAction, ExTGRunAction, ExUCNRunAction, F01RunAction, F04RunAction, FCALRunAction, FFRunAction, FW::Geant4::MMRunAction, G02RunAction, G03RunAction, G4AdjointSimManager, G4BlineTracer, G4HumanPhantomRunAction, G4MultiRunAction, G4RTRunAction, GammaKnifeRunAction, GammaRayTelRunAction, HadrontherapyRunAction, IORTRunAction, LXeRunAction, OpNoviceRunAction, Par02RunAction, PurgMagRunAction, RE01RunAction, RE02RunAction, RE05RunAction, RE06RunAction, RMC01RunAction, root_test.MyRunAction, run.MyRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunActionMaster, RunActionMaster, STCyclotronRunAction, test.MyRunAction, test.MyRunAction, TSRunAction, UltraRunAction, WLSRunAction, XrayFluoRunAction, and XrayTelRunAction.
Public Member Functions
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *aRun)
virtual void EndOfRunAction (const G4Run *aRun)
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Protected Attributes
G4bool isMaster
Detailed Description
Definition at line 51 of file G4UserRunAction.hh.
View newest version in sPHENIX GitHub at line 51 of file G4UserRunAction.hh
Constructor & Destructor Documentation
G4UserRunAction::G4UserRunAction ()
Definition at line 34 of file G4UserRunAction.cc.
View newest version in sPHENIX GitHub at line 34 of file G4UserRunAction.cc
References FatalException, G4Exception(), and G4ParticleTable::GetParticleTable().
G4UserRunAction::~G4UserRunAction () virtual
Definition at line 51 of file G4UserRunAction.cc.
View newest version in sPHENIX GitHub at line 51 of file G4UserRunAction.cc
Member Function Documentation
void G4UserRunAction::BeginOfRunAction (const G4Run * aRun) virtual
Reimplemented in G4AdjointSimManager, RE02RunAction, RunAction, G4BlineTracer, XrayTelRunAction, G4MultiRunAction, XrayFluoRunAction, RMC01RunAction, RunAction, B4bRunAction, RunAction, RunAction, RunAction, TSRunAction, doiPETRunAction, B4RunAction, B4RunAction, B4RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, DMXRunAction, CML2RunAction, RunAction, RunAction, RunAction, UltraRunAction, IORTRunAction, B01RunAction, B02RunAction, B03RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, Par02RunAction, G02RunAction, RunAction, GammaRayTelRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, G03RunAction, RunAction, RunAction, PurgMagRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, BrachyRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, FFRunAction, RunAction, WLSRunAction, GammaKnifeRunAction, RunAction, RunAction, RunAction, B1ConRunAction, RunAction, RunAction, RunAction, RunAction, ExP01RunAction, B1RunAction, DicomRunAction, RunAction, OpNoviceRunAction, RunAction, B1RunAction, RunAction, HadrontherapyRunAction, STCyclotronRunAction, RunAction, ExUCNRunAction, RunAction, ExN02RunAction, ExN04RunAction, FCALRunAction, RunAction, F04RunAction, RunAction, RunAction, RunAction, RE05RunAction, G4RTRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, B2RunAction, B2RunAction, B5RunAction, RunAction, RunAction, LXeRunAction, B2RunAction, eRositaRunAction, B3bRunAction, ExTGRunAction, RE01RunAction, RE06RunAction, FW::Geant4::MMRunAction, G4HumanPhantomRunAction, ExN04RunAction, ExGflashRunAction, B3aRunAction, CCalRunAction, F01RunAction, ExGflashRunAction, ExGflashRunAction, ExGflashRunAction, RunActionMaster, CB_G4UserRunAction, RunAction, RunAction, RunAction, RunActionMaster, RunAction, and RunAction.
Definition at line 57 of file G4UserRunAction.cc.
View newest version in sPHENIX GitHub at line 57 of file G4UserRunAction.cc
Referenced by G4MPIextraWorker::BeamOn(), CB_G4UserRunAction::BeginOfRunAction(), G4AdjointSimManager::BeginOfRunAction(), export_G4UserRunAction(), G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
void G4UserRunAction::EndOfRunAction (const G4Run * aRun) virtual
Reimplemented in G4AdjointSimManager, RE02RunAction, RunAction, XrayTelRunAction, G4BlineTracer, G4MultiRunAction, XrayFluoRunAction, RMC01RunAction, RunAction, RunAction, RunAction, RunAction, B4bRunAction, RunAction, TSRunAction, doiPETRunAction, B4RunAction, B4RunAction, B4RunAction, Par02RunAction, RunAction, RunAction, RunAction, RunAction, CexmcRunAction, DMXRunAction, CML2RunAction, RunAction, RunAction, RunAction, RunAction, UltraRunAction, IORTRunAction, B01RunAction, B02RunAction, B03RunAction, RunAction, RunAction, RunAction, RunAction, G02RunAction, RunAction, GammaRayTelRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, G03RunAction, RunAction, RunAction, PurgMagRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, BrachyRunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, FFRunAction, Dicom2RunAction, RunAction, WLSRunAction, GammaKnifeRunAction, RunAction, RunAction, RunAction, B1ConRunAction, RunAction, RunAction, RunAction, RunAction, ExP01RunAction, B1RunAction, DicomRunAction, RunAction, OpNoviceRunAction, RunAction, B1RunAction, RunAction, HadrontherapyRunAction, FCALRunAction, STCyclotronRunAction, RunAction, ExUCNRunAction, RunAction, RunAction, RunAction, ExN02RunAction, RunAction, F04RunAction, RunAction, RunAction, RunAction, G4RTRunAction, CB_G4UserRunAction, RunAction, RunAction, RunAction, FW::Geant4::MMRunAction, RunAction, B2RunAction, B2RunAction, B5RunAction, RunAction, RunAction, LXeRunAction, B2RunAction, eRositaRunAction, B3bRunAction, ElectronRunAction, ExTGRunAction, RE01RunAction, RE06RunAction, G4HumanPhantomRunAction, ExGflashRunAction, B3aRunAction, CCalRunAction, F01RunAction, ExGflashRunAction, ExGflashRunAction, ExGflashRunAction, RunActionMaster, RunAction, RunAction, RunAction, RunActionMaster, RunAction, and RunAction.
Definition at line 60 of file G4UserRunAction.cc.
View newest version in sPHENIX GitHub at line 60 of file G4UserRunAction.cc
Referenced by G4MPIextraWorker::BeamOn(), CB_G4UserRunAction::EndOfRunAction(), G4AdjointSimManager::EndOfRunAction(), export_G4UserRunAction(), and G4RunManager::RunTermination().
G4Run * G4UserRunAction::GenerateRun (void) virtual
Reimplemented in RE02RunAction, RunAction, G4MultiRunAction, TSRunAction, B4bRunAction, RunAction, RunAction, CexmcRunAction, doiPETRunAction, CML2RunAction, RunAction, RunAction, RunAction, B01RunAction, B02RunAction, B03RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, RunAction, Dicom2RunAction, RunAction, STCyclotronRunAction, RunAction, RunAction, RunAction, B1ConRunAction, DicomRunAction, RunAction, B1RunAction, RunAction, RunAction, G4RTRunAction, LXeRunAction, B3bRunAction, ElectronRunAction, RE06RunAction, RunActionMaster, RunAction, RunActionMaster, and RunAction.
Definition at line 54 of file G4UserRunAction.cc.
View newest version in sPHENIX GitHub at line 54 of file G4UserRunAction.cc
Referenced by G4WorkerRunManager::RunInitialization(), and G4RunManager::RunInitialization().
G4bool G4UserRunAction::IsMaster () const inline
Definition at line 68 of file G4UserRunAction.hh.
View newest version in sPHENIX GitHub at line 68 of file G4UserRunAction.hh
References isMaster.
Referenced by ExTGRunAction::BeginOfRunAction(), HadrontherapyRunAction::BeginOfRunAction(), B1ConRunAction::BeginOfRunAction(), PurgMagRunAction::BeginOfRunAction(), GammaRayTelRunAction::BeginOfRunAction(), UltraRunAction::BeginOfRunAction(), DMXRunAction::BeginOfRunAction(), TSRunAction::BeginOfRunAction(), XrayFluoRunAction::BeginOfRunAction(), XrayTelRunAction::BeginOfRunAction(), B3aRunAction::EndOfRunAction(), B3bRunAction::EndOfRunAction(), RE06RunAction::EndOfRunAction(), HadrontherapyRunAction::EndOfRunAction(), DicomRunAction::EndOfRunAction(), B1RunAction::EndOfRunAction(), B1ConRunAction::EndOfRunAction(), Dicom2RunAction::EndOfRunAction(), PurgMagRunAction::EndOfRunAction(), B03RunAction::EndOfRunAction(), UltraRunAction::EndOfRunAction(), B02RunAction::EndOfRunAction(), B01RunAction::EndOfRunAction(), CML2RunAction::EndOfRunAction(), TSRunAction::EndOfRunAction(), XrayTelRunAction::EndOfRunAction(), RE02RunAction::EndOfRunAction(), and XrayFluoRunAction::Initialise().
virtual void G4UserRunAction::SetMaster (G4bool val = true) inline virtual
Reimplemented in G4MultiRunAction.
Definition at line 66 of file G4UserRunAction.hh.
View newest version in sPHENIX GitHub at line 66 of file G4UserRunAction.hh
References isMaster.
Referenced by G4MultiRunAction::SetMaster(), G4WorkerRunManager::SetUserAction(), and G4MTRunManager::SetUserAction().
Member Data Documentation
G4bool G4UserRunAction::isMaster protected
Definition at line 63 of file G4UserRunAction.hh.
View newest version in sPHENIX GitHub at line 63 of file G4UserRunAction.hh
Referenced by doiPETRunAction::BeginOfRunAction(), LXeRunAction::EndOfRunAction(), STCyclotronRunAction::EndOfRunAction(), B4RunAction::EndOfRunAction(), B4bRunAction::EndOfRunAction(), RunAction::InitializeWorker(), IsMaster(), SetMaster(), and Par02RunAction::~Par02RunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4UserRunAction.hh
geant4/tree/geant4-10.6-release/source/run/src/G4UserRunAction.cc