ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/include/xDataTOM.h File Reference
xDataTOM.h File Reference
#include <statusMessageReporting.h>
Classes
struct xDataTOM_interpolation_s
struct xDataTOM_axis_s
struct xDataTOM_axes_s
struct xDataTOM_subAxes_s
struct xDataTOM_XYs_s
struct xDataTOM_regionsXYs_s
struct xDataTOM_W_XYs_s
struct xDataTOM_V_W_XYs_s
struct xDataTOM_LegendreSeries_s
struct xDataTOM_W_XYs_LegendreSeries_s
struct xDataTOM_regionsW_XYs_LegendreSeries_s
struct xDataTOM_V_W_XYs_LegendreSeries_s
struct xDataTOM_KalbachMannCoefficients_s
struct xDataTOM_KalbachMann_s
struct xDataTOM_polynomial_s
struct xDataTOM_xDataInfo_s
struct xDataTOM_attribute_s
struct xDataTOM_attributionList_s
struct xDataTOM_elementListItem_s
struct xDataTOM_elementList_s
struct xDataTOM_element_s
struct xDataTOM_TOM_s
Macros
#define xDataTOMMisc_allocateCopyString2(smr, s, forItem) xDataTOMMisc_allocateCopyString(smr, s, forItem, __FILE__, __LINE__)
Typedefs
typedef int xDataTOM_Int
typedef struct
xDataTOM_interpolation_s xDataTOM_interpolation
typedef struct xDataTOM_axis_s xDataTOM_axis
typedef struct xDataTOM_axes_s xDataTOM_axes
typedef struct xDataTOM_subAxes_s xDataTOM_subAxes
typedef struct xDataTOM_XYs_s xDataTOM_XYs
typedef struct
xDataTOM_regionsXYs_s xDataTOM_regionsXYs
typedef struct xDataTOM_W_XYs_s xDataTOM_W_XYs
typedef struct xDataTOM_V_W_XYs_s xDataTOM_V_W_XYs
typedef struct
xDataTOM_LegendreSeries_s xDataTOM_LegendreSeries
typedef struct
xDataTOM_W_XYs_LegendreSeries_s xDataTOM_W_XYs_LegendreSeries
typedef struct
xDataTOM_regionsW_XYs_LegendreSeries_s xDataTOM_regionsW_XYs_LegendreSeries
typedef struct
xDataTOM_V_W_XYs_LegendreSeries_s xDataTOM_V_W_XYs_LegendreSeries
typedef struct
xDataTOM_KalbachMannCoefficients_s xDataTOM_KalbachMannCoefficients
typedef struct
xDataTOM_KalbachMann_s xDataTOM_KalbachMann
typedef struct
xDataTOM_polynomial_s xDataTOM_polynomial
typedef struct xDataTOM_xDataInfo_s xDataTOM_xDataInfo
typedef struct xDataTOM_attribute_s xDataTOM_attribute
typedef struct
xDataTOM_attributionList_s xDataTOM_attributionList
typedef struct
xDataTOM_elementListItem_s xDataTOM_elementListItem
typedef struct
xDataTOM_elementList_s xDataTOM_elementList
typedef struct xDataTOM_element_s xDataTOM_element
typedef struct xDataTOM_TOM_s xDataTOM_TOM
typedef int(* xDataTOM_sortElementFunc)(const void *, const void *)
Enumerations
enum xDataTOM_interpolationFlag {
xDataTOM_interpolationFlag_invalid, xDataTOM_interpolationFlag_linear, xDataTOM_interpolationFlag_log, xDataTOM_interpolationFlag_byRegion,
xDataTOM_interpolationFlag_flat
}
enum xDataTOM_interpolationQualifier {
xDataTOM_interpolationQualifier_invalid, xDataTOM_interpolationQualifier_dependent, xDataTOM_interpolationQualifier_none, xDataTOM_interpolationQualifier_unitBase,
xDataTOM_interpolationQualifier_correspondingPoints
}
enum xDataTOM_frame { xDataTOM_frame_invalid, xDataTOM_frame_lab, xDataTOM_frame_centerOfMass }
enum xDataTOM_subAxesType { xDataTOM_subAxesType_proxy, xDataTOM_subAxesType_intepolationAxes }
enum xDataTOM_KalbachMannType { xDataTOM_KalbachMannType_fr, xDataTOM_KalbachMannType_fra }
Functions
xDataTOM_TOM * xDataTOM_importFile (statusMessageReporting *smr, const char *fileName)
xDataTOM_TOM * xDataTOM_mallocTOM (statusMessageReporting *smr)
int xDataTOM_initializeTOM (statusMessageReporting *smr, xDataTOM_TOM *doc)
void * xDataTOM_freeTOM (statusMessageReporting *smr, xDataTOM_TOM **TOM)
int xDataTOM_setFileNameTOM (statusMessageReporting *smr, xDataTOM_TOM *doc, const char *fileName)
void xDataTOM_displayTree (statusMessageReporting *smr, xDataTOM_TOM *TOM, int printAttributes)
xDataTOM_element * xDataTOM_mallocElement (statusMessageReporting *smr, xDataTOM_element *parent, int ordinal, int index, char const *name)
void xDataTOM_freeElement (xDataTOM_element **element)
void xDataTOM_releaseElement (xDataTOM_element *element)
xDataTOM_element * xDataTOM_addElementInElement (statusMessageReporting *smr, xDataTOM_element *parent, int index, char const *name)
xDataTOM_element * xDataTOM_getDocumentsElement (xDataTOM_TOM *TOM)
xDataTOM_element * xDataTOME_getFirstElement (xDataTOM_element *element)
xDataTOM_element * xDataTOME_getNextElement (xDataTOM_element *element)
xDataTOM_element * xDataTOME_getOneElementByName (statusMessageReporting *smr, xDataTOM_element *element, char const *name, int required)
int xDataTOM_numberOfElementsByName (statusMessageReporting *smr, xDataTOM_element *element, char const *name)
int xDataTOME_addAttribute (statusMessageReporting *smr, xDataTOM_element *element, char const *name, char const *value)
char const * xDataTOM_getAttributesValueInElement (xDataTOM_element *element, char const *name)
int xDataTOME_copyAttributionList (statusMessageReporting *smr, xDataTOM_attributionList *desc, xDataTOM_element *element)
int xDataTOME_convertAttributeToInteger (statusMessageReporting *smr, xDataTOM_element *element, char const *name, int *n)
int xDataTOME_convertAttributeToDouble (statusMessageReporting *smr, xDataTOM_element *element, char const *name, double *d)
int xDataTOME_convertAttributeToDoubleWithUnit (statusMessageReporting *smr, xDataTOM_element *element, char const *name, double *d, char *unit)
int xDataTOME_getInterpolation (statusMessageReporting *smr, xDataTOM_element *element, int index, enum xDataTOM_interpolationFlag *independent, enum xDataTOM_interpolationFlag *dependent, enum xDataTOM_interpolationQualifier *qualifier)
void xDataTOMAL_initial (statusMessageReporting *smr, xDataTOM_attributionList *attributes)
void xDataTOMAL_release (xDataTOM_attributionList *attributes)
int xDataTOMAL_addAttribute (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, char const *value)
char const * xDataTOMAL_getAttributesValue (xDataTOM_attributionList *attributes, char const *name)
int xDataTOMAL_copyAttributionList (statusMessageReporting *smr, xDataTOM_attributionList *desc, xDataTOM_attributionList *src)
int xDataTOMAL_convertAttributeToInteger (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, int *n)
int xDataTOMAL_convertAttributeToDouble (statusMessageReporting *smr, xDataTOM_attributionList *attributes, char const *name, double *d)
void * xData_initializeData (statusMessageReporting *smr, xDataTOM_element *TE, char const *ID, size_t size)
int xDataTOM_isXDataID (xDataTOM_element *TE, char const *ID)
char * xDataTOMMisc_getAbsPath (statusMessageReporting *smr, const char *fileName)
int xDataTOM_setMessageError_ReturnInt (int value, statusMessageReporting *smr, void *userData, const char *file, int line, int code, const char *fmt,...)
xDataTOM_element * xDataTOM_getLinksElement (statusMessageReporting *smr, xDataTOM_element *element, char const *link)
int xDataTOM_interpolation_set (statusMessageReporting *smr, xDataTOM_interpolation *interpolation, enum xDataTOM_interpolationFlag independent, enum xDataTOM_interpolationFlag dependent, enum xDataTOM_interpolationQualifier qualifier)
int xDataTOM_interpolation_setFromString (statusMessageReporting *smr, xDataTOM_interpolation *interpolation, char const *str)
int xDataTOM_interpolation_copy (statusMessageReporting *smr, xDataTOM_interpolation *desc, xDataTOM_interpolation *src)
int xDataTOM_axes_initialize (statusMessageReporting *smr, xDataTOM_axes *axes, int numberOfAxes)
int xDataTOM_axes_release (xDataTOM_axes *axes)
char const * xDataTOM_axes_getLabel (statusMessageReporting *smr, xDataTOM_axes *axes, int index)
char const * xDataTOM_axes_getUnit (statusMessageReporting *smr, xDataTOM_axes *axes, int index)
int xDataTOM_axes_getInterpolation (statusMessageReporting *smr, xDataTOM_axes *axes, int index, enum xDataTOM_interpolationFlag *independent, enum xDataTOM_interpolationFlag *dependent, enum xDataTOM_interpolationQualifier *qualifier)
int xDataTOM_subAxes_initialize (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, enum xDataTOM_subAxesType type, int offset, xDataTOM_axes *axes, xDataTOM_interpolation *interpolation)
int xDataTOM_subAxes_release (xDataTOM_subAxes *subAxes)
char const * xDataTOM_subAxes_getLabel (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, int index)
char const * xDataTOM_subAxes_getUnit (statusMessageReporting *smr, xDataTOM_subAxes *subAxes, int index)
xDataTOM_axis * xDataTOM_axis_new (statusMessageReporting *smr, int index, char const *label, char const *unit, xDataTOM_interpolation *interpolation)
int xDataTOM_axis_initialize (statusMessageReporting *smr, xDataTOM_axis *axis, int index, char const *label, char const *unit, xDataTOM_interpolation *interpolation)
xDataTOM_axis * xDataTOM_axis_release (statusMessageReporting *smr, xDataTOM_axis *axis)
enum xDataTOM_frame xDataTOM_axis_stringToFrame (statusMessageReporting *smr, char const *frame)
char const * xDataTOM_axis_frameToString (statusMessageReporting *smr, enum xDataTOM_frame frame)
int xDataTOM_XYs_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_XYs_release (xDataTOM_XYs *XYs)
int xDataTOM_XYs_getData (xDataTOM_XYs *XYs, double **data)
int xDataTOM_XYs_getDataFromXDataInfo (xDataTOM_xDataInfo *xDI, double **data)
int xDataTOM_regionsXYs_free (xDataTOM_xDataInfo *xDI)
xDataTOM_W_XYs * xDataTOM_W_XYs_new (statusMessageReporting *smr, int index, int length, double value, xDataTOM_axes *axes, int axesOffset)
int xDataTOM_W_XYs_initialize (statusMessageReporting *smr, xDataTOM_W_XYs *W_XYs, int index, int length, double value, xDataTOM_axes *axes, int axesOffset)
xDataTOM_W_XYs * xDataTOM_W_XYs_free (xDataTOM_W_XYs *W_XYs)
int xDataTOM_W_XYs_freeFrom_xDataInfo (xDataTOM_xDataInfo *xDI)
int xDataTOM_W_XYs_release (xDataTOM_W_XYs *W_XYs)
xDataTOM_xDataInfo * xDataTOME_getXData (xDataTOM_element *TE)
void * xDataTOME_getXDataIfID (statusMessageReporting *smr, xDataTOM_element *TE, char const *ID)
int xDataTOM_V_W_XYs_initialize (statusMessageReporting *smr, xDataTOM_V_W_XYs *V_W_XYs, int length, xDataTOM_axes *axes)
int xDataTOM_V_W_XYs_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_LegendreSeries_initialize (statusMessageReporting *smr, xDataTOM_LegendreSeries *LegendreSeries, int index, int length, double value)
int xDataTOM_LegendreSeries_release (xDataTOM_LegendreSeries *LegendreSeries)
int xDataTOM_W_XYs_LegendreSeries_initialize (statusMessageReporting *smr, xDataTOM_W_XYs_LegendreSeries *W_XYs_LegendreSeries, int index, int length, double value, enum xDataTOM_subAxesType subAxesType, xDataTOM_axes *axes, xDataTOM_interpolation *interpolation)
int xDataTOM_W_XYs_LegendreSeries_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_W_XYs_LegendreSeries_release (xDataTOM_W_XYs_LegendreSeries *W_XYs_LegendreSeries)
int xDataTOM_regionsW_XYs_LegendreSeries_initialize (statusMessageReporting *smr, xDataTOM_regionsW_XYs_LegendreSeries *regionsW_XYs_LegendreSeries, int length, xDataTOM_axes *axes)
int xDataTOM_regionsW_XYs_LegendreSeries_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_regionsW_XYs_LegendreSeries_release (xDataTOM_regionsW_XYs_LegendreSeries *regionsW_XYs_LegendreSeries)
int xDataTOM_V_W_XYs_LegendreSeries_initialize (statusMessageReporting *smr, xDataTOM_V_W_XYs_LegendreSeries *V_W_XYs_LegendreSeries, int length, xDataTOM_axes *axes)
int xDataTOM_V_W_XYs_LegendreSeries_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_KalbachMann_initialize (statusMessageReporting *smr, xDataTOM_KalbachMann *KalbachMann, int length, xDataTOM_axes *axes)
int xDataTOM_KalbachMann_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_KalbachMann_release (xDataTOM_KalbachMann *KalbachMann)
int xDataTOM_polynomial_initialize (statusMessageReporting *smr, xDataTOM_polynomial *polynomial, int length, xDataTOM_axes *axes)
int xDataTOM_polynomial_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_polynomial_release (xDataTOM_polynomial *polynomial)
int xDataTOM_polynomial_getData (xDataTOM_polynomial *polynomial, double **data)
int xDataTOM_polynomial_getDataFromXDataInfo (xDataTOM_xDataInfo *xDI, double **data)
Macro Definition Documentation
#define xDataTOMMisc_allocateCopyString2 (smr, s, forItem) xDataTOMMisc_allocateCopyString(smr, s, forItem, __FILE__, __LINE__)
Definition at line 242 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 242 of file xDataTOM.h
Typedef Documentation
typedef struct xDataTOM_attribute_s xDataTOM_attribute
Definition at line 47 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 47 of file xDataTOM.h
typedef struct xDataTOM_attributionList_s xDataTOM_attributionList
Definition at line 48 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 48 of file xDataTOM.h
typedef struct xDataTOM_axes_s xDataTOM_axes
Definition at line 29 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 29 of file xDataTOM.h
typedef struct xDataTOM_axis_s xDataTOM_axis
Definition at line 28 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 28 of file xDataTOM.h
typedef struct xDataTOM_element_s xDataTOM_element
Definition at line 51 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 51 of file xDataTOM.h
typedef struct xDataTOM_elementList_s xDataTOM_elementList
Definition at line 50 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 50 of file xDataTOM.h
typedef struct xDataTOM_elementListItem_s xDataTOM_elementListItem
Definition at line 49 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 49 of file xDataTOM.h
typedef int xDataTOM_Int
Definition at line 16 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 16 of file xDataTOM.h
typedef struct xDataTOM_interpolation_s xDataTOM_interpolation
Definition at line 27 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 27 of file xDataTOM.h
typedef struct xDataTOM_KalbachMann_s xDataTOM_KalbachMann
Definition at line 42 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 42 of file xDataTOM.h
typedef struct xDataTOM_KalbachMannCoefficients_s xDataTOM_KalbachMannCoefficients
Definition at line 41 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 41 of file xDataTOM.h
typedef struct xDataTOM_LegendreSeries_s xDataTOM_LegendreSeries
Definition at line 37 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 37 of file xDataTOM.h
typedef struct xDataTOM_polynomial_s xDataTOM_polynomial
Definition at line 43 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 43 of file xDataTOM.h
typedef struct xDataTOM_regionsW_XYs_LegendreSeries_s xDataTOM_regionsW_XYs_LegendreSeries
Definition at line 39 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 39 of file xDataTOM.h
typedef struct xDataTOM_regionsXYs_s xDataTOM_regionsXYs
Definition at line 33 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 33 of file xDataTOM.h
typedef int(* xDataTOM_sortElementFunc)(const void *, const void *)
Definition at line 54 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 54 of file xDataTOM.h
typedef struct xDataTOM_subAxes_s xDataTOM_subAxes
Definition at line 30 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 30 of file xDataTOM.h
typedef struct xDataTOM_TOM_s xDataTOM_TOM
Definition at line 52 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 52 of file xDataTOM.h
typedef struct xDataTOM_V_W_XYs_s xDataTOM_V_W_XYs
Definition at line 35 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 35 of file xDataTOM.h
typedef struct xDataTOM_V_W_XYs_LegendreSeries_s xDataTOM_V_W_XYs_LegendreSeries
Definition at line 40 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 40 of file xDataTOM.h
typedef struct xDataTOM_W_XYs_s xDataTOM_W_XYs
Definition at line 34 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 34 of file xDataTOM.h
typedef struct xDataTOM_W_XYs_LegendreSeries_s xDataTOM_W_XYs_LegendreSeries
Definition at line 38 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 38 of file xDataTOM.h
typedef struct xDataTOM_xDataInfo_s xDataTOM_xDataInfo
Definition at line 45 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 45 of file xDataTOM.h
typedef struct xDataTOM_XYs_s xDataTOM_XYs
Definition at line 32 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 32 of file xDataTOM.h
Enumeration Type Documentation
enum xDataTOM_frame
Enumerator:
xDataTOM_frame_invalid
xDataTOM_frame_lab
xDataTOM_frame_centerOfMass
Definition at line 23 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 23 of file xDataTOM.h
enum xDataTOM_interpolationFlag
Enumerator:
xDataTOM_interpolationFlag_invalid
xDataTOM_interpolationFlag_linear
xDataTOM_interpolationFlag_log
xDataTOM_interpolationFlag_byRegion
xDataTOM_interpolationFlag_flat
Definition at line 19 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM.h
enum xDataTOM_interpolationQualifier
Enumerator:
xDataTOM_interpolationQualifier_invalid
xDataTOM_interpolationQualifier_dependent
xDataTOM_interpolationQualifier_none
xDataTOM_interpolationQualifier_unitBase
xDataTOM_interpolationQualifier_correspondingPoints
Definition at line 21 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 21 of file xDataTOM.h
enum xDataTOM_KalbachMannType
Enumerator:
xDataTOM_KalbachMannType_fr
xDataTOM_KalbachMannType_fra
Definition at line 25 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 25 of file xDataTOM.h
enum xDataTOM_subAxesType
Enumerator:
xDataTOM_subAxesType_proxy
xDataTOM_subAxesType_intepolationAxes
Definition at line 24 of file xDataTOM.h.
View newest version in sPHENIX GitHub at line 24 of file xDataTOM.h
Function Documentation
void* xData_initializeData (statusMessageReporting * smr, xDataTOM_element * TE, char const * ID, size_t size)
Definition at line 479 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 479 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::element, xDataTOM_xDataInfo_s::ID, smr_malloc2, and xDataTOM_element_s::xDataInfo.
Referenced by xDataXML_initializeData().
xDataTOM_element* xDataTOM_addElementInElement (statusMessageReporting * smr, xDataTOM_element * parent, int index, char const * name)
Definition at line 188 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 188 of file xDataTOM.cc
References xDataTOM_element_s::children, xDataTOM_element_s::next, xDataTOM_element_s::numberOfChildren, and xDataTOM_mallocElement().
Referenced by xDataXML_constructTOM().
int xDataTOM_axes_getInterpolation (statusMessageReporting * smr, xDataTOM_axes * axes, int index, enum xDataTOM_interpolationFlag * independent, enum xDataTOM_interpolationFlag * dependent, enum xDataTOM_interpolationQualifier * qualifier)
Definition at line 66 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 66 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_interpolation_s::dependent, xDataTOM_axis_s::interpolation, xDataTOM_axes_s::numberOfAxes, xDataTOM_interpolation_s::qualifier, smr_setReportError2, and xDataTOM_smrLibraryID.
Referenced by xDataTOME_getInterpolation().
char const* xDataTOM_axes_getLabel (statusMessageReporting * smr, xDataTOM_axes * axes, int index)
Definition at line 44 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 44 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_axis_s::label, xDataTOM_axes_s::numberOfAxes, smr_setReportError2, and xDataTOM_smrLibraryID.
Referenced by xDataTOM_subAxes_getLabel(), xDataXML_KalbachMannToTOM(), xDataXML_regionsW_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYs_LegendreSeriesToTOM(), xDataXML_V_W_XYsToTOM(), xDataXML_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYsDataToTOM().
char const* xDataTOM_axes_getUnit (statusMessageReporting * smr, xDataTOM_axes * axes, int index)
Definition at line 55 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 55 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_axes_s::numberOfAxes, smr_setReportError2, xDataTOM_axis_s::unit, and xDataTOM_smrLibraryID.
Referenced by MCGIDI_fromTOM_pdfsOfXGivenW(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_product_parsePolynomialMultiplicity(), and xDataTOM_subAxes_getUnit().
int xDataTOM_axes_initialize (statusMessageReporting * smr, xDataTOM_axes * axes, int numberOfAxes)
Definition at line 21 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 21 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_axes_s::numberOfAxes, and smr_malloc2.
Referenced by xDataXML_axesToTOM().
int xDataTOM_axes_release (xDataTOM_axes * axes)
Definition at line 31 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 31 of file xDataTOM_axes.cc
References xDataTOM_axes_s::axis, xDataTOM_axes_s::numberOfAxes, smr_freeMemory(), and xDataTOM_axis_release().
Referenced by xDataTOM_releaseElement().
char const* xDataTOM_axis_frameToString (statusMessageReporting * smr, enum xDataTOM_frame frame)
Definition at line 191 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 191 of file xDataTOM_axes.cc
References xDataTOM_frame_centerOfMass, xDataTOM_frame_centerOfMassString, xDataTOM_frame_invalidString, xDataTOM_frame_lab, and xDataTOM_frame_labString.
int xDataTOM_axis_initialize (statusMessageReporting * smr, xDataTOM_axis * axis, int index, char const * label, char const * unit, xDataTOM_interpolation * interpolation)
Definition at line 155 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 155 of file xDataTOM_axes.cc
References check_license::err(), xDataTOM_axis_s::index, xDataTOM_axis_s::interpolation, xDataTOM_axis_s::label, smr_allocateCopyString2, smr_freeMemory(), xDataTOM_axis_s::unit, and xDataTOM_interpolation_copy().
Referenced by xDataTOM_axis_new(), and xDataXML_axesToTOM().
xDataTOM_axis* xDataTOM_axis_new (statusMessageReporting * smr, int index, char const * label, char const * unit, xDataTOM_interpolation * interpolation)
Definition at line 144 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 144 of file xDataTOM_axes.cc
References smr_freeMemory(), smr_malloc2, and xDataTOM_axis_initialize().
xDataTOM_axis* xDataTOM_axis_release (statusMessageReporting * smr, xDataTOM_axis * axis)
Definition at line 172 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 172 of file xDataTOM_axes.cc
References xDataTOM_axis_s::index, xDataTOM_axis_s::label, smr_freeMemory(), and xDataTOM_axis_s::unit.
Referenced by xDataTOM_axes_release(), and xDataXML_axesToTOM().
enum xDataTOM_frame xDataTOM_axis_stringToFrame (statusMessageReporting * smr, char const * frame)
Definition at line 182 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 182 of file xDataTOM_axes.cc
References xDataTOM_frame_centerOfMass, xDataTOM_frame_invalid, and xDataTOM_frame_lab.
Referenced by MCGIDI_misc_getProductFrame().
void xDataTOM_displayTree (statusMessageReporting * smr, xDataTOM_TOM * TOM, int printAttributes)
Definition at line 114 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 114 of file xDataTOM.cc
References xDataTOM_element_s::children, xDataTOM_TOM_s::root, and xDataTOME_displayTree().
void xDataTOM_freeElement (xDataTOM_element ** element)
Definition at line 139 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 139 of file xDataTOM.cc
References smr_freeMemory(), and xDataTOM_releaseElement().
Referenced by xDataTOM_releaseElement().
void* xDataTOM_freeTOM (statusMessageReporting * smr, xDataTOM_TOM ** TOM)
Definition at line 78 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 78 of file xDataTOM.cc
References xDataTOM_TOM_s::fileName, xDataTOM_TOM_s::realFileName, xDataTOM_TOM_s::root, smr_freeMemory(), and xDataTOM_releaseElement().
Referenced by MCGIDI_target_heated_read(), and xDataXML_importFile().
char const* xDataTOM_getAttributesValueInElement (xDataTOM_element * element, char const * name)
Definition at line 286 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 286 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_getAttributesValue().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energyAngular_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), MCGIDI_misc_getProductFrame(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), MCGIDI_reaction_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parseReaction(), MCGIDI_target_heated_read(), and xDataTOM_getLinksElement2().
xDataTOM_element* xDataTOM_getDocumentsElement (xDataTOM_TOM * TOM)
Definition at line 223 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 223 of file xDataTOM.cc
References xDataTOM_element_s::children, and xDataTOM_TOM_s::root.
Referenced by MCGIDI_target_heated_read().
xDataTOM_element* xDataTOM_getLinksElement (statusMessageReporting * smr, xDataTOM_element * element, char const * link)
Definition at line 89 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 89 of file xDataTOM_Misc.cc
References xDataTOM_element_s::parent, smr_setReportError2, smr_unknownID, and xDataTOM_getLinksElement2().
Referenced by MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM().
xDataTOM_TOM* xDataTOM_importFile (statusMessageReporting * smr, const char * fileName)
Definition at line 44 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 44 of file xDataTOM.cc
References xDataXML_importFile().
Referenced by MCGIDI_target_heated_read().
int xDataTOM_initializeTOM (statusMessageReporting * smr, xDataTOM_TOM * doc)
Definition at line 68 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 68 of file xDataTOM.cc
References xDataTOM_TOM_s::fileName, xDataTOM_TOM_s::realFileName, xDataTOM_TOM_s::root, smr_isOk(), and xDataTOME_initializeElement().
Referenced by xDataTOM_mallocTOM().
int xDataTOM_interpolation_copy (statusMessageReporting * smr, xDataTOM_interpolation * desc, xDataTOM_interpolation * src)
Definition at line 102 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 102 of file xDataTOM_interpolation.cc
References xDataTOM_interpolation_s::dependent, xDataTOM_interpolation_s::qualifier, and xDataTOM_interpolation_set().
Referenced by xDataTOM_axis_initialize(), and xDataTOM_subAxes_initialize().
int xDataTOM_interpolation_set (statusMessageReporting * smr, xDataTOM_interpolation * interpolation, enum xDataTOM_interpolationFlag independent, enum xDataTOM_interpolationFlag dependent, enum xDataTOM_interpolationQualifier qualifier)
Definition at line 22 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 22 of file xDataTOM_interpolation.cc
References xDataTOM_interpolation_s::dependent, xDataTOM_interpolation_s::qualifier, smr_setReportError2, xDataTOM_interpolationFlag_byRegion, xDataTOM_interpolationFlag_flat, xDataTOM_interpolationFlag_linear, xDataTOM_interpolationQualifier_correspondingPoints, xDataTOM_interpolationQualifier_invalid, and xDataTOM_smrLibraryID.
Referenced by xDataTOM_interpolation_copy(), xDataTOM_interpolation_setFromString(), xDataTOM_subAxes_initialize(), and xDataXML_axesToTOM().
int xDataTOM_interpolation_setFromString (statusMessageReporting * smr, xDataTOM_interpolation * interpolation, char const * str)
Definition at line 46 of file xDataTOM_interpolation.cc.
View newest version in sPHENIX GitHub at line 46 of file xDataTOM_interpolation.cc
References c, dependentAxis, e, smr_setReportError2, xDataTOM_interpolation_getFromString(), xDataTOM_interpolation_set(), xDataTOM_interpolationFlag_invalid, xDataTOM_interpolationQualifier_correspondingPoints, xDataTOM_interpolationQualifier_none, xDataTOM_interpolationQualifier_unitBase, and xDataTOM_smrLibraryID.
Referenced by xDataXML_axesToTOM(), xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), and xDataXML_regionsXYs_regionToTOM().
int xDataTOM_isXDataID (xDataTOM_element * TE, char const * ID)
Definition at line 491 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 491 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::ID, and xDataTOM_element_s::xDataInfo.
int xDataTOM_KalbachMann_free (xDataTOM_xDataInfo * xDI)
Definition at line 35 of file xDataTOM_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 35 of file xDataTOM_KalbachMann.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, smr_freeMemory(), xDataTOM_KalbachMann_ID, and xDataTOM_KalbachMann_release().
Referenced by xDataTOM_releaseElement().
int xDataTOM_KalbachMann_initialize (statusMessageReporting * smr, xDataTOM_KalbachMann * KalbachMann, int length, xDataTOM_axes * axes)
Definition at line 19 of file xDataTOM_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_KalbachMann.cc
References xDataTOM_KalbachMann_s::coefficients, xDataTOM_KalbachMann_s::numberOfEnergies, smr_freeMemory(), smr_malloc2, xDataTOM_KalbachMann_s::subAxes, xDataTOM_subAxes_initialize(), and xDataTOM_subAxesType_proxy.
Referenced by xDataXML_KalbachMannToTOM().
int xDataTOM_KalbachMann_release (xDataTOM_KalbachMann * KalbachMann)
Definition at line 46 of file xDataTOM_KalbachMann.cc.
View newest version in sPHENIX GitHub at line 46 of file xDataTOM_KalbachMann.cc
References xDataTOM_KalbachMannCoefficients_s::coefficients, xDataTOM_KalbachMann_s::coefficients, xDataTOM_KalbachMann_s::numberOfEnergies, smr_freeMemory(), xDataTOM_KalbachMann_s::subAxes, and xDataTOM_subAxes_release().
Referenced by xDataTOM_KalbachMann_free().
int xDataTOM_LegendreSeries_initialize (statusMessageReporting * smr, xDataTOM_LegendreSeries * LegendreSeries, int index, int length, double value)
Definition at line 17 of file xDataTOM_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 17 of file xDataTOM_LegendreSeries.cc
References xDataTOM_LegendreSeries_s::index, xDataTOM_LegendreSeries_s::LegendreSeries, BTOF::length, xDataTOM_LegendreSeries_s::length, smr_malloc2, and xDataTOM_LegendreSeries_s::value.
Referenced by xDataXML_LegendreSeriesDataToTOM().
int xDataTOM_LegendreSeries_release (xDataTOM_LegendreSeries * LegendreSeries)
Definition at line 30 of file xDataTOM_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 30 of file xDataTOM_LegendreSeries.cc
References xDataTOM_LegendreSeries_s::LegendreSeries, and smr_freeMemory().
Referenced by xDataTOM_W_XYs_LegendreSeries_release(), and xDataXML_LegendreSeriesDataToTOM().
xDataTOM_element* xDataTOM_mallocElement (statusMessageReporting * smr, xDataTOM_element * parent, int ordinal, int index, char const * name)
Definition at line 125 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 125 of file xDataTOM.cc
References smr_freeMemory(), smr_malloc2, and xDataTOME_initializeElement().
Referenced by xDataTOM_addElementInElement().
xDataTOM_TOM* xDataTOM_mallocTOM (statusMessageReporting * smr)
Definition at line 54 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 54 of file xDataTOM.cc
References smr_freeMemory(), smr_malloc2, and xDataTOM_initializeTOM().
Referenced by xDataXML_importFile().
int xDataTOM_numberOfElementsByName (statusMessageReporting * smr, xDataTOM_element * element, char const * name)
Definition at line 268 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 268 of file xDataTOM.cc
References n, xDataTOM_element_s::name, xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by MCGIDI_outputChannel_parseFromTOM(), and MCGIDI_target_heated_read().
int xDataTOM_polynomial_free (xDataTOM_xDataInfo * xDI)
Definition at line 33 of file xDataTOM_polynomial.cc.
View newest version in sPHENIX GitHub at line 33 of file xDataTOM_polynomial.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, smr_freeMemory(), xDataTOM_polynomial_ID, and xDataTOM_polynomial_release().
Referenced by xDataTOM_releaseElement().
int xDataTOM_polynomial_getData (xDataTOM_polynomial * polynomial, double ** data)
Definition at line 55 of file xDataTOM_polynomial.cc.
View newest version in sPHENIX GitHub at line 55 of file xDataTOM_polynomial.cc
References xDataTOM_polynomial_s::coefficients, and xDataTOM_polynomial_s::length.
Referenced by xDataTOM_polynomial_getDataFromXDataInfo().
int xDataTOM_polynomial_getDataFromXDataInfo (xDataTOM_xDataInfo * xDI, double ** data)
Definition at line 63 of file xDataTOM_polynomial.cc.
View newest version in sPHENIX GitHub at line 63 of file xDataTOM_polynomial.cc
References xDataTOM_xDataInfo_s::data, and xDataTOM_polynomial_getData().
Referenced by MCGIDI_product_parsePolynomialMultiplicity().
int xDataTOM_polynomial_initialize (statusMessageReporting * smr, xDataTOM_polynomial * polynomial, int length, xDataTOM_axes * axes)
Definition at line 19 of file xDataTOM_polynomial.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_polynomial.cc
References xDataTOM_polynomial_s::coefficients, BTOF::length, xDataTOM_polynomial_s::length, smr_freeMemory(), smr_malloc2, xDataTOM_polynomial_s::subAxes, xDataTOM_subAxes_initialize(), and xDataTOM_subAxesType_proxy.
Referenced by xDataXML_polynomialToTOM().
int xDataTOM_polynomial_release (xDataTOM_polynomial * polynomial)
Definition at line 44 of file xDataTOM_polynomial.cc.
View newest version in sPHENIX GitHub at line 44 of file xDataTOM_polynomial.cc
References xDataTOM_polynomial_s::coefficients, xDataTOM_polynomial_s::length, smr_freeMemory(), xDataTOM_polynomial_s::subAxes, and xDataTOM_subAxes_release().
Referenced by xDataTOM_polynomial_free(), and xDataXML_polynomialToTOM().
int xDataTOM_regionsW_XYs_LegendreSeries_free (xDataTOM_xDataInfo * xDI)
Definition at line 33 of file xDataTOM_regionsW_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 33 of file xDataTOM_regionsW_XYs_LegendreSeries.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, smr_freeMemory(), xDataTOM_regionsW_XYs_LegendreSeries_ID, and xDataTOM_regionsW_XYs_LegendreSeries_release().
Referenced by xDataTOM_releaseElement().
int xDataTOM_regionsW_XYs_LegendreSeries_initialize (statusMessageReporting * smr, xDataTOM_regionsW_XYs_LegendreSeries * regionsW_XYs_LegendreSeries, int length, xDataTOM_axes * axes)
Definition at line 19 of file xDataTOM_regionsW_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_regionsW_XYs_LegendreSeries.cc
References xDataTOM_regionsW_XYs_LegendreSeries_s::axes, BTOF::length, xDataTOM_regionsW_XYs_LegendreSeries_s::length, smr_malloc2, and xDataTOM_regionsW_XYs_LegendreSeries_s::W_XYs_LegendreSeries.
Referenced by xDataXML_regionsW_XYs_LegendreSeriesToTOM().
int xDataTOM_regionsW_XYs_LegendreSeries_release (xDataTOM_regionsW_XYs_LegendreSeries * regionsW_XYs_LegendreSeries)
Definition at line 44 of file xDataTOM_regionsW_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 44 of file xDataTOM_regionsW_XYs_LegendreSeries.cc
References xDataTOM_regionsW_XYs_LegendreSeries_s::length, smr_freeMemory(), xDataTOM_regionsW_XYs_LegendreSeries_s::W_XYs_LegendreSeries, and xDataTOM_W_XYs_LegendreSeries_release().
Referenced by xDataTOM_regionsW_XYs_LegendreSeries_free().
int xDataTOM_regionsXYs_free (xDataTOM_xDataInfo * xDI)
Definition at line 19 of file xDataTOM_regionsXYs.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_regionsXYs.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, BTOF::length, smr_freeMemory(), xDataTOM_regionsXYs_ID, xDataTOM_XYs_release(), and xDataTOM_regionsXYs_s::XYs.
Referenced by xDataTOM_releaseElement().
void xDataTOM_releaseElement (xDataTOM_element * element)
Definition at line 148 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 148 of file xDataTOM.cc
References xDataTOM_element_s::attributes, xDataTOM_xDataInfo_s::axes, xDataTOM_element_s::children, xDataTOM_xDataInfo_s::ID, xDataTOM_element_s::name, xDataTOM_element_s::next, xDataTOM_element_s::parent, printf(), smr_freeMemory(), xDataTOM_element_s::xDataInfo, xDataTOM_axes_release(), xDataTOM_freeElement(), xDataTOM_KalbachMann_free(), xDataTOM_KalbachMann_ID, xDataTOM_polynomial_free(), xDataTOM_polynomial_ID, xDataTOM_regionsW_XYs_LegendreSeries_free(), xDataTOM_regionsW_XYs_LegendreSeries_ID, xDataTOM_regionsXYs_free(), xDataTOM_regionsXYs_ID, xDataTOM_V_W_XYs_free(), xDataTOM_V_W_XYs_ID, xDataTOM_V_W_XYs_LegendreSeries_free(), xDataTOM_V_W_XYs_LegendreSeries_ID, xDataTOM_W_XYs_freeFrom_xDataInfo(), xDataTOM_W_XYs_ID, xDataTOM_W_XYs_LegendreSeries_free(), xDataTOM_W_XYs_LegendreSeries_ID, xDataTOM_XYs_free(), xDataTOM_XYs_ID, and xDataTOMAL_release().
Referenced by xDataTOM_freeElement(), and xDataTOM_freeTOM().
int xDataTOM_setFileNameTOM (statusMessageReporting * smr, xDataTOM_TOM * doc, const char * fileName)
Definition at line 94 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 94 of file xDataTOM.cc
References xDataTOM_TOM_s::fileName, PATH_MAX, xDataTOM_TOM_s::realFileName, smr_allocateCopyString2, and smr_freeMemory().
Referenced by xDataXML_importFile().
int xDataTOM_setMessageError_ReturnInt (int value, statusMessageReporting * smr, void * userData, const char * file, int line, int code, const char * fmt, ...)
Definition at line 76 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 76 of file xDataTOM_Misc.cc
References smr_setReportError(), and xDataTOM_smrLibraryID.
char const* xDataTOM_subAxes_getLabel (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, int index)
Definition at line 126 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 126 of file xDataTOM_axes.cc
References xDataTOM_subAxes_s::axes, xDataTOM_subAxes_s::offset, and xDataTOM_axes_getLabel().
char const* xDataTOM_subAxes_getUnit (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, int index)
Definition at line 133 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 133 of file xDataTOM_axes.cc
References xDataTOM_subAxes_s::axes, xDataTOM_subAxes_s::offset, and xDataTOM_axes_getUnit().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), and MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf().
int xDataTOM_subAxes_initialize (statusMessageReporting * smr, xDataTOM_subAxes * subAxes, enum xDataTOM_subAxesType type, int offset, xDataTOM_axes * axes, xDataTOM_interpolation * interpolation)
Definition at line 89 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 89 of file xDataTOM_axes.cc
References xDataTOM_subAxes_s::axes, xDataTOM_subAxes_s::interpolation, xDataTOM_axes_s::numberOfAxes, offset, xDataTOM_subAxes_s::offset, smr_setReportError2, smr_setReportError2p, xDataTOM_subAxes_s::type, xDataTOM_interpolation_copy(), xDataTOM_interpolation_set(), xDataTOM_interpolationFlag_linear, xDataTOM_interpolationQualifier_none, xDataTOM_smrLibraryID, and xDataTOM_subAxesType_intepolationAxes.
Referenced by xDataTOM_KalbachMann_initialize(), xDataTOM_polynomial_initialize(), xDataTOM_V_W_XYs_initialize(), xDataTOM_V_W_XYs_LegendreSeries_initialize(), xDataTOM_W_XYs_initialize(), xDataTOM_W_XYs_LegendreSeries_initialize(), and xDataXML_XYsDataToTOM().
int xDataTOM_subAxes_release (xDataTOM_subAxes * subAxes)
Definition at line 118 of file xDataTOM_axes.cc.
View newest version in sPHENIX GitHub at line 118 of file xDataTOM_axes.cc
References xDataTOM_subAxes_s::axes.
Referenced by xDataTOM_KalbachMann_release(), xDataTOM_polynomial_release(), xDataTOM_W_XYs_release(), and xDataTOM_XYs_release().
int xDataTOM_V_W_XYs_free (xDataTOM_xDataInfo * xDI)
Definition at line 34 of file xDataTOM_V_W_XYs.cc.
View newest version in sPHENIX GitHub at line 34 of file xDataTOM_V_W_XYs.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, xDataTOM_V_W_XYs_s::length, smr_freeMemory(), xDataTOM_V_W_XYs_s::W_XYs, xDataTOM_V_W_XYs_ID, and xDataTOM_W_XYs_release().
Referenced by xDataTOM_releaseElement().
int xDataTOM_V_W_XYs_initialize (statusMessageReporting * smr, xDataTOM_V_W_XYs * V_W_XYs, int length, xDataTOM_axes * axes)
Definition at line 19 of file xDataTOM_V_W_XYs.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_V_W_XYs.cc
References BTOF::length, xDataTOM_V_W_XYs_s::length, smr_freeMemory(), smr_malloc2, xDataTOM_V_W_XYs_s::subAxes, xDataTOM_V_W_XYs_s::W_XYs, xDataTOM_subAxes_initialize(), and xDataTOM_subAxesType_proxy.
Referenced by xDataXML_V_W_XYsToTOM().
int xDataTOM_V_W_XYs_LegendreSeries_free (xDataTOM_xDataInfo * xDI)
Definition at line 33 of file xDataTOM_V_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 33 of file xDataTOM_V_W_XYs_LegendreSeries.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, BTOF::length, smr_freeMemory(), xDataTOM_V_W_XYs_LegendreSeries_s::W_XYs_LegendreSeries, xDataTOM_V_W_XYs_LegendreSeries_ID, and xDataTOM_W_XYs_LegendreSeries_release().
Referenced by xDataTOM_releaseElement().
int xDataTOM_V_W_XYs_LegendreSeries_initialize (statusMessageReporting * smr, xDataTOM_V_W_XYs_LegendreSeries * V_W_XYs_LegendreSeries, int length, xDataTOM_axes * axes)
Definition at line 19 of file xDataTOM_V_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_V_W_XYs_LegendreSeries.cc
References BTOF::length, xDataTOM_V_W_XYs_LegendreSeries_s::length, smr_malloc2, xDataTOM_V_W_XYs_LegendreSeries_s::subAxes, xDataTOM_V_W_XYs_LegendreSeries_s::W_XYs_LegendreSeries, xDataTOM_subAxes_initialize(), and xDataTOM_subAxesType_proxy.
Referenced by xDataXML_V_W_XYs_LegendreSeriesToTOM().
xDataTOM_W_XYs* xDataTOM_W_XYs_free (xDataTOM_W_XYs * W_XYs)
Definition at line 48 of file xDataTOM_W_XYs.cc.
View newest version in sPHENIX GitHub at line 48 of file xDataTOM_W_XYs.cc
References smr_freeMemory(), and xDataTOM_W_XYs_release().
Referenced by xDataTOM_W_XYs_freeFrom_xDataInfo().
int xDataTOM_W_XYs_freeFrom_xDataInfo (xDataTOM_xDataInfo * xDI)
Definition at line 58 of file xDataTOM_W_XYs.cc.
View newest version in sPHENIX GitHub at line 58 of file xDataTOM_W_XYs.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, xDataTOM_W_XYs_free(), and xDataTOM_W_XYs_ID.
Referenced by xDataTOM_releaseElement().
int xDataTOM_W_XYs_initialize (statusMessageReporting * smr, xDataTOM_W_XYs * W_XYs, int index, int length, double value, xDataTOM_axes * axes, int axesOffset)
Definition at line 30 of file xDataTOM_W_XYs.cc.
View newest version in sPHENIX GitHub at line 30 of file xDataTOM_W_XYs.cc
References xDataTOM_W_XYs_s::index, BTOF::length, xDataTOM_W_XYs_s::length, smr_freeMemory(), smr_malloc2, xDataTOM_W_XYs_s::subAxes, xDataTOM_W_XYs_s::value, xDataTOM_subAxes_initialize(), xDataTOM_subAxesType_proxy, and xDataTOM_W_XYs_s::XYs.
Referenced by xDataTOM_W_XYs_new(), and xDataXML_W_XYsDataToTOM().
int xDataTOM_W_XYs_LegendreSeries_free (xDataTOM_xDataInfo * xDI)
Definition at line 34 of file xDataTOM_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 34 of file xDataTOM_W_XYs_LegendreSeries.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, smr_freeMemory(), xDataTOM_W_XYs_LegendreSeries_ID, and xDataTOM_W_XYs_LegendreSeries_release().
Referenced by xDataTOM_releaseElement().
int xDataTOM_W_XYs_LegendreSeries_initialize (statusMessageReporting * smr, xDataTOM_W_XYs_LegendreSeries * W_XYs_LegendreSeries, int index, int length, double value, enum xDataTOM_subAxesType subAxesType, xDataTOM_axes * axes, xDataTOM_interpolation * interpolation)
Definition at line 19 of file xDataTOM_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_W_XYs_LegendreSeries.cc
References xDataTOM_W_XYs_LegendreSeries_s::index, xDataTOM_W_XYs_LegendreSeries_s::LegendreSeries, BTOF::length, xDataTOM_W_XYs_LegendreSeries_s::length, smr_malloc2, xDataTOM_W_XYs_LegendreSeries_s::subAxes, xDataTOM_W_XYs_LegendreSeries_s::value, and xDataTOM_subAxes_initialize().
Referenced by xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYs_LegendreSeriesToTOM().
int xDataTOM_W_XYs_LegendreSeries_release (xDataTOM_W_XYs_LegendreSeries * W_XYs_LegendreSeries)
Definition at line 45 of file xDataTOM_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 45 of file xDataTOM_W_XYs_LegendreSeries.cc
References xDataTOM_W_XYs_LegendreSeries_s::LegendreSeries, xDataTOM_W_XYs_LegendreSeries_s::length, smr_freeMemory(), and xDataTOM_LegendreSeries_release().
Referenced by xDataTOM_regionsW_XYs_LegendreSeries_release(), xDataTOM_V_W_XYs_LegendreSeries_free(), and xDataTOM_W_XYs_LegendreSeries_free().
xDataTOM_W_XYs* xDataTOM_W_XYs_new (statusMessageReporting * smr, int index, int length, double value, xDataTOM_axes * axes, int axesOffset)
Definition at line 19 of file xDataTOM_W_XYs.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_W_XYs.cc
References smr_freeMemory(), smr_malloc2, and xDataTOM_W_XYs_initialize().
int xDataTOM_W_XYs_release (xDataTOM_W_XYs * W_XYs)
Definition at line 68 of file xDataTOM_W_XYs.cc.
View newest version in sPHENIX GitHub at line 68 of file xDataTOM_W_XYs.cc
References xDataTOM_W_XYs_s::length, smr_freeMemory(), xDataTOM_W_XYs_s::subAxes, xDataTOM_subAxes_release(), xDataTOM_XYs_release(), and xDataTOM_W_XYs_s::XYs.
Referenced by xDataTOM_V_W_XYs_free(), and xDataTOM_W_XYs_free().
int xDataTOM_XYs_free (xDataTOM_xDataInfo * xDI)
Definition at line 19 of file xDataTOM_XYs.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_XYs.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, smr_freeMemory(), xDataTOM_XYs_ID, and xDataTOM_XYs_release().
Referenced by xDataTOM_releaseElement().
int xDataTOM_XYs_getData (xDataTOM_XYs * XYs, double ** data)
Definition at line 42 of file xDataTOM_XYs.cc.
View newest version in sPHENIX GitHub at line 42 of file xDataTOM_XYs.cc
References xDataTOM_XYs_s::data, and xDataTOM_XYs_s::length.
Referenced by MCGIDI_misc_dataFromXYs2ptwXYPointsInUnitsOf(), and xDataTOM_XYs_getDataFromXDataInfo().
int xDataTOM_XYs_getDataFromXDataInfo (xDataTOM_xDataInfo * xDI, double ** data)
Definition at line 50 of file xDataTOM_XYs.cc.
View newest version in sPHENIX GitHub at line 50 of file xDataTOM_XYs.cc
References xDataTOM_xDataInfo_s::data, and xDataTOM_XYs_getData().
Referenced by MCGIDI_misc_dataFromElement2ptwXYPointsInUnitsOf().
int xDataTOM_XYs_release (xDataTOM_XYs * XYs)
Definition at line 31 of file xDataTOM_XYs.cc.
View newest version in sPHENIX GitHub at line 31 of file xDataTOM_XYs.cc
References xDataTOM_XYs_s::data, xDataTOM_XYs_s::length, smr_freeMemory(), xDataTOM_XYs_s::subAxes, and xDataTOM_subAxes_release().
Referenced by xDataTOM_regionsXYs_free(), xDataTOM_W_XYs_release(), and xDataTOM_XYs_free().
int xDataTOMAL_addAttribute (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, char const * value)
Definition at line 376 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 376 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, check_license::err(), xDataTOM_attribute_s::name, xDataTOM_attribute_s::next, xDataTOM_attributionList_s::number, smr_allocateCopyString2, smr_freeMemory(), smr_malloc2, and xDataTOM_attribute_s::value.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), xDataTOMAL_copyAttributionList(), and xDataTOME_addAttribute().
int xDataTOMAL_convertAttributeToDouble (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, double * d)
Definition at line 450 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 450 of file xDataTOM.cc
References e, smr_setReportError2, xDataTOM_smrLibraryID, and xDataTOMAL_getAttributesValue().
Referenced by xDataTOME_convertAttributeToDouble().
int xDataTOMAL_convertAttributeToInteger (statusMessageReporting * smr, xDataTOM_attributionList * attributes, char const * name, int * n)
Definition at line 433 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 433 of file xDataTOM.cc
References e, int(), smr_setReportError2, xDataTOM_smrLibraryID, and xDataTOMAL_getAttributesValue().
Referenced by xDataTOME_convertAttributeToInteger().
int xDataTOMAL_copyAttributionList (statusMessageReporting * smr, xDataTOM_attributionList * desc, xDataTOM_attributionList * src)
Definition at line 415 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 415 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, check_license::err(), xDataTOM_attribute_s::name, xDataTOM_attribute_s::next, xDataTOM_attribute_s::value, xDataTOMAL_addAttribute(), xDataTOMAL_initial(), and xDataTOMAL_release().
Referenced by MCGIDI_target_heated_read(), and xDataTOME_copyAttributionList().
char const* xDataTOMAL_getAttributesValue (xDataTOM_attributionList * attributes, char const * name)
Definition at line 403 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 403 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, xDataTOM_attribute_s::name, xDataTOM_attribute_s::next, and xDataTOM_attribute_s::value.
Referenced by MCGIDI_misc_pointerToAttributeIfAllOk(), MCGIDI_misc_pointerToTOMAttributeIfAllOk(), MCGIDI_target_getAttributesValue(), xDataTOM_getAttributesValueInElement(), xDataTOMAL_convertAttributeToDouble(), and xDataTOMAL_convertAttributeToInteger().
void xDataTOMAL_initial (statusMessageReporting * smr, xDataTOM_attributionList * attributes)
Definition at line 353 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 353 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, and xDataTOM_attributionList_s::number.
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), MCGIDI_reaction_initialize2(), xDataTOMAL_copyAttributionList(), xDataTOMAL_release(), and xDataTOME_initializeElement().
void xDataTOMAL_release (xDataTOM_attributionList * attributes)
Definition at line 361 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 361 of file xDataTOM.cc
References xDataTOM_attributionList_s::attributes, xDataTOM_attribute_s::name, xDataTOM_attribute_s::next, smr_freeMemory(), xDataTOM_attribute_s::value, and xDataTOMAL_initial().
Referenced by MCGIDI_misc_copyXMLAttributesToTOM(), MCGIDI_reaction_release(), MCGIDI_target_heated_release(), MCGIDI_target_release(), xDataTOM_releaseElement(), and xDataTOMAL_copyAttributionList().
int xDataTOME_addAttribute (statusMessageReporting * smr, xDataTOM_element * element, char const * name, char const * value)
Definition at line 279 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 279 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_addAttribute().
Referenced by xDataXML_constructTOM().
int xDataTOME_convertAttributeToDouble (statusMessageReporting * smr, xDataTOM_element * element, char const * name, double * d)
Definition at line 307 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 307 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_convertAttributeToDouble().
Referenced by MCGIDI_target_heated_parseParticleGammas().
int xDataTOME_convertAttributeToDoubleWithUnit (statusMessageReporting * smr, xDataTOM_element * element, char const * name, double * d, char * unit)
int xDataTOME_convertAttributeToInteger (statusMessageReporting * smr, xDataTOM_element * element, char const * name, int * n)
Definition at line 300 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 300 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_convertAttributeToInteger().
Referenced by MCGIDI_energy_parseNBodyPhaseSpaceFromTOM(), MCGIDI_product_parseFromTOM(), and MCGIDI_reaction_parseFromTOM().
int xDataTOME_copyAttributionList (statusMessageReporting * smr, xDataTOM_attributionList * desc, xDataTOM_element * element)
Definition at line 293 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 293 of file xDataTOM.cc
References xDataTOM_element_s::attributes, and xDataTOMAL_copyAttributionList().
Referenced by MCGIDI_reaction_parseFromTOM().
xDataTOM_element* xDataTOME_getFirstElement (xDataTOM_element * element)
Definition at line 230 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 230 of file xDataTOM.cc
References xDataTOM_element_s::children.
Referenced by MCGIDI_energy_parseWeightedFunctionalsFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_read(), xDataTOM_numberOfElementsByName(), xDataTOME_displayTree(), and xDataTOME_getOneElementByName().
int xDataTOME_getInterpolation (statusMessageReporting * smr, xDataTOM_element * element, int index, enum xDataTOM_interpolationFlag * independent, enum xDataTOM_interpolationFlag * dependent, enum xDataTOM_interpolationQualifier * qualifier)
Definition at line 314 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 314 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::axes, xDataTOM_xDataInfo_s::ID, xDataTOM_element_s::xDataInfo, and xDataTOM_axes_getInterpolation().
Referenced by MCGIDI_fromTOM_interpolation(), and MCGIDI_reaction_parseFromTOM().
xDataTOM_element* xDataTOME_getNextElement (xDataTOM_element * element)
Definition at line 238 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 238 of file xDataTOM.cc
References xDataTOM_element_s::next.
Referenced by MCGIDI_energy_parseWeightedFunctionalsFromTOM(), MCGIDI_energy_parseWeightFromTOM(), MCGIDI_outputChannel_parseFromTOM(), MCGIDI_target_heated_parseParticle(), MCGIDI_target_heated_parseParticleGammas(), MCGIDI_target_heated_parseParticleLevel(), MCGIDI_target_heated_parsePOPs(), MCGIDI_target_heated_read(), xDataTOM_numberOfElementsByName(), xDataTOME_displayTree(), and xDataTOME_getOneElementByName().
xDataTOM_element* xDataTOME_getOneElementByName (statusMessageReporting * smr, xDataTOM_element * element, char const * name, int required)
Definition at line 246 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 246 of file xDataTOM.cc
References n, xDataTOM_element_s::name, smr_setReportError2, smr_unknownID, xDataTOME_getFirstElement(), and xDataTOME_getNextElement().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parseFromTOM(), MCGIDI_distribution_parseFromTOM(), MCGIDI_energy_parseEvaporationFromTOM(), MCGIDI_energy_parseFromTOM(), MCGIDI_energy_parseGeneralEvaporationFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energy_parseSimpleMaxwellianFissionFromTOM(), MCGIDI_energy_parseWattFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_energyAngular_parseFromTOM(), MCGIDI_KalbachMann_parseFromTOM(), MCGIDI_LLNL_angularEnergy_parseFromTOM(), MCGIDI_LLNLAngular_angularEnergy_parseFromTOM(), MCGIDI_product_parseFromTOM(), MCGIDI_product_parseWeightedReferenceMultiplicityFromTOM(), MCGIDI_reaction_parseFromTOM(), MCGIDI_target_heated_read(), and MCGIDI_uncorrelated_parseFromTOM().
xDataTOM_xDataInfo* xDataTOME_getXData (xDataTOM_element * TE)
Definition at line 504 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 504 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::ID, and xDataTOM_element_s::xDataInfo.
Referenced by xDataTOME_getXDataIfID().
void* xDataTOME_getXDataIfID (statusMessageReporting * smr, xDataTOM_element * TE, char const * ID)
Definition at line 512 of file xDataTOM.cc.
View newest version in sPHENIX GitHub at line 512 of file xDataTOM.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, xDataTOM_element_s::name, smr_setReportError2, xDataTOM_smrLibraryID, and xDataTOME_getXData().
Referenced by MCGIDI_angular_parseFromTOM(), MCGIDI_angularEnergy_parsePointwiseFromTOM(), MCGIDI_energy_parseMadlandNixFromTOM(), MCGIDI_energyAngular_linear_parseFromTOM(), MCGIDI_fromTOM_pdfsOfXGivenW(), and MCGIDI_LLNL_angularEnergy_parsePointwiseFromTOM().
char* xDataTOMMisc_getAbsPath (statusMessageReporting * smr, const char * fileName)
Definition at line 29 of file xDataTOM_Misc.cc.
View newest version in sPHENIX GitHub at line 29 of file xDataTOM_Misc.cc
References g4zmq::cwd(), int(), n, smr_malloc2, smr_setReportError2p, and xDataTOM_smrLibraryID.
Referenced by MCGIDI_target_heated_read().