ECCE @ EIC Software: G4BetaMinusDecay Class Reference
G4BetaMinusDecay Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4BetaMinusDecay.hh>
Public Member Functions
G4BetaMinusDecay (const G4ParticleDefinition *theParentNucleus, const G4double &theBR, const G4double &endpointE, const G4double &ex, const G4Ions::G4FloatLevelBase &flb, const G4BetaDecayType &type)
virtual ~G4BetaMinusDecay ()
virtual G4DecayProducts * DecayIt (G4double)
virtual void DumpNuclearInfo ()
Public Member Functions inherited from G4NuclearDecay
G4NuclearDecay (const G4String &channelName, const G4RadioactiveDecayMode &mode, const G4double &excitation, const G4Ions::G4FloatLevelBase &floatingLevel)
virtual ~G4NuclearDecay ()
G4RadioactiveDecayMode GetDecayMode ()
G4double GetDaughterExcitation ()
G4Ions::G4FloatLevelBase GetFloatingLevel ()
G4ParticleDefinition * GetDaughterNucleus ()
void SetHLThreshold (G4double HLT)
G4double GetHLThreshold ()
Public Member Functions inherited from G4VDecayChannel
G4VDecayChannel (const G4String &aName, G4int Verbose=1)
G4VDecayChannel (const G4String &aName, const G4String &theParentName, G4double theBR, G4int theNumberOfDaughters, const G4String &theDaughterName1, const G4String &theDaughterName2="", const G4String &theDaughterName3="", const G4String &theDaughterName4="")
virtual ~G4VDecayChannel ()
G4bool operator== (const G4VDecayChannel &right) const
G4bool operator!= (const G4VDecayChannel &right) const
G4bool operator< (const G4VDecayChannel &right) const
const G4String & GetKinematicsName () const
G4double GetBR () const
G4int GetNumberOfDaughters () const
G4ParticleDefinition * GetParent ()
G4ParticleDefinition * GetDaughter (G4int anIndex)
G4int GetAngularMomentum ()
const G4String & GetParentName () const
const G4String & GetDaughterName (G4int anIndex) const
G4double GetParentMass () const
G4double GetDaughterMass (G4int anIndex) const
void SetParent (const G4ParticleDefinition *particle_type)
void SetParent (const G4String &particle_name)
void SetBR (G4double value)
void SetNumberOfDaughters (G4int value)
void SetDaughter (G4int anIndex, const G4ParticleDefinition *particle_type)
void SetDaughter (G4int anIndex, const G4String &particle_name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void DumpInfo ()
G4double GetRangeMass () const
void SetRangeMass (G4double val)
virtual G4bool IsOKWithParentMass (G4double parentMass)
void SetPolarization (const G4ThreeVector &)
const G4ThreeVector & GetPolarization () const
Private Member Functions
void SetUpBetaSpectrumSampler (const G4int &parentZ, const G4int &parentA, const G4BetaDecayType &type)
Private Attributes
const G4double endpointEnergy
G4RandGeneral * spectrumSampler
Additional Inherited Members
Protected Member Functions inherited from G4VDecayChannel
void ClearDaughtersName ()
void CheckAndFillDaughters ()
void CheckAndFillParent ()
G4VDecayChannel ()
G4VDecayChannel (const G4VDecayChannel &)
G4VDecayChannel & operator= (const G4VDecayChannel &)
G4double DynamicalMass (G4double massPDG, G4double width, G4double maxDev=+1.) const
Protected Attributes inherited from G4NuclearDecay
const G4RadioactiveDecayMode theMode
Static Protected Attributes inherited from G4VDecayChannel
static const G4String noName = " "
Detailed Description
Definition at line 44 of file G4BetaMinusDecay.hh.
View newest version in sPHENIX GitHub at line 44 of file G4BetaMinusDecay.hh
Constructor & Destructor Documentation
G4BetaMinusDecay::G4BetaMinusDecay (const G4ParticleDefinition * theParentNucleus, const G4double & theBR, const G4double & endpointE, const G4double & ex, const G4Ions::G4FloatLevelBase & flb, const G4BetaDecayType & type)
Definition at line 44 of file G4BetaMinusDecay.cc.
View newest version in sPHENIX GitHub at line 44 of file G4BetaMinusDecay.cc
References G4ParticleDefinition::GetAtomicMass(), G4ParticleDefinition::GetAtomicNumber(), G4IonTable::GetIon(), G4ParticleTable::GetIonTable(), G4ParticleTable::GetParticleTable(), G4VDecayChannel::SetBR(), G4VDecayChannel::SetDaughter(), G4VDecayChannel::SetNumberOfDaughters(), G4VDecayChannel::SetParent(), and SetUpBetaSpectrumSampler().
G4BetaMinusDecay::~G4BetaMinusDecay () virtual
Definition at line 67 of file G4BetaMinusDecay.cc.
View newest version in sPHENIX GitHub at line 67 of file G4BetaMinusDecay.cc
References spectrumSampler.
Member Function Documentation
G4DecayProducts * G4BetaMinusDecay::DecayIt (G4double) virtual
Implements G4VDecayChannel.
Definition at line 73 of file G4BetaMinusDecay.cc.
View newest version in sPHENIX GitHub at line 73 of file G4BetaMinusDecay.cc
References G4VDecayChannel::CheckAndFillDaughters(), G4VDecayChannel::CheckAndFillParent(), endpointEnergy, G4VDecayChannel::G4MT_daughters, G4VDecayChannel::G4MT_parent, G4UniformRand, G4ParticleDefinition::GetPDGMass(), phi, G4DecayProducts::PushProducts(), rad, CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), spectrumSampler, and twopi.
void G4BetaMinusDecay::DumpNuclearInfo () virtual
Implements G4NuclearDecay.
Definition at line 198 of file G4BetaMinusDecay.cc.
View newest version in sPHENIX GitHub at line 198 of file G4BetaMinusDecay.cc
References endpointEnergy, G4cout, G4endl, G4VDecayChannel::GetBR(), G4VDecayChannel::GetDaughterName(), G4VDecayChannel::GetParentName(), and keV.
void G4BetaMinusDecay::SetUpBetaSpectrumSampler (const G4int & parentZ, const G4int & parentA, const G4BetaDecayType & type) private
Definition at line 163 of file G4BetaMinusDecay.cc.
View newest version in sPHENIX GitHub at line 163 of file G4BetaMinusDecay.cc
References e, CLHEP::electron_mass_c2, endpointEnergy, f, G4BetaDecayCorrections::FermiFunction(), G4RandGeneral, G4BetaDecayCorrections::ShapeFactor(), and spectrumSampler.
Referenced by G4BetaMinusDecay().
Member Data Documentation
const G4double G4BetaMinusDecay::endpointEnergy private
Definition at line 62 of file G4BetaMinusDecay.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BetaMinusDecay.hh
Referenced by DecayIt(), DumpNuclearInfo(), and SetUpBetaSpectrumSampler().
G4RandGeneral* G4BetaMinusDecay::spectrumSampler private
Definition at line 63 of file G4BetaMinusDecay.hh.
View newest version in sPHENIX GitHub at line 63 of file G4BetaMinusDecay.hh
Referenced by DecayIt(), SetUpBetaSpectrumSampler(), and ~G4BetaMinusDecay().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4BetaMinusDecay.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4BetaMinusDecay.cc