ECCE @ EIC Software: G4NeutronCaptureXS Class Reference
G4NeutronCaptureXS Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4NeutronCaptureXS.hh>
Public Member Functions
G4NeutronCaptureXS ()
~G4NeutronCaptureXS () final
G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *) final
G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *, const G4Material *) final
G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *) final
G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso, const G4Element *elm, const G4Material *mat) final
const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE) final
void BuildPhysicsTable (const G4ParticleDefinition &) final
void CrossSectionDescription (std::ostream &) const final
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Static Public Member Functions
static const char * Default_Name ()
Private Member Functions
void Initialise (G4int Z)
void InitialiseOnFly (G4int Z)
const G4String & FindDirectoryPath ()
const G4PhysicsVector * GetPhysicsVector (G4int Z)
G4PhysicsVector * RetrieveVector (std::ostringstream &in, G4bool warn)
G4double IsoCrossSection (G4double ekin, G4double logekin, G4int Z, G4int A)
G4NeutronCaptureXS & operator= (const G4NeutronCaptureXS &right)
G4NeutronCaptureXS (const G4NeutronCaptureXS &)
Private Attributes
G4double emax
G4double elimit
G4double logElimit
std::vector< G4double > temp
G4bool isMaster
Static Private Attributes
static G4ElementData * data = nullptr
static const G4int amin [MAXZCAPTURE]
static const G4int amax [MAXZCAPTURE]
static G4String gDataDirectory = ""
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 60 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 60 of file G4NeutronCaptureXS.hh
Constructor & Destructor Documentation
G4NeutronCaptureXS::G4NeutronCaptureXS () explicit
Definition at line 91 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 91 of file G4NeutronCaptureXS.cc
References elimit, G4cout, G4endl, G4Log(), isMaster, logElimit, MAXZCAPTURE, temp, and G4VCrossSectionDataSet::verboseLevel.
G4NeutronCaptureXS::~G4NeutronCaptureXS () final
Definition at line 105 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 105 of file G4NeutronCaptureXS.cc
References data, and isMaster.
G4NeutronCaptureXS::G4NeutronCaptureXS (const G4NeutronCaptureXS &) private
Member Function Documentation
void G4NeutronCaptureXS::BuildPhysicsTable (const G4ParticleDefinition & p) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 271 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 271 of file G4NeutronCaptureXS.cc
References FatalException, FindDirectoryPath(), G4cout, G4endl, G4Exception(), G4MUTEXLOCK, G4MUTEXUNLOCK, G4ParticleDefinition::GetParticleName(), G4ProductionCutsTable::GetProductionCutsTable(), Initialise(), isMaster, mat, max, MAXZCAPTURE, min, G4VCrossSectionDataSet::verboseLevel, and Z.
void G4NeutronCaptureXS::CrossSectionDescription (std::ostream & outFile) const final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 110 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 110 of file G4NeutronCaptureXS.cc
static const char* G4NeutronCaptureXS::Default_Name () inline static
Definition at line 68 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 68 of file G4NeutronCaptureXS.hh
Referenced by LBE::ConstructHad(), G4NeutronCrossSectionXS::ConstructProcess(), and G4HadronPhysicsFTFQGSP_BERT::CreateModels().
const G4String & G4NeutronCaptureXS::FindDirectoryPath () private
Definition at line 329 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 329 of file G4NeutronCaptureXS.cc
References FatalException, G4Exception(), and gDataDirectory.
Referenced by BuildPhysicsTable(), and Initialise().
G4double G4NeutronCaptureXS::GetElementCrossSection (const G4DynamicParticle * aParticle, G4int Z, const G4Material *) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 135 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 135 of file G4NeutronCaptureXS.cc
References CLHEP::barn, e1, elimit, emax, G4cout, G4endl, G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), GetPhysicsVector(), logElimit, MAXZCAPTURE, CLHEP::MeV, min, G4VCrossSectionDataSet::verboseLevel, and Z.
G4double G4NeutronCaptureXS::GetIsoCrossSection (const G4DynamicParticle * aParticle, G4int Z, G4int A, const G4Isotope * iso, const G4Element * elm, const G4Material * mat) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 164 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 164 of file G4NeutronCaptureXS.cc
References A(), G4DynamicParticle::GetKineticEnergy(), G4DynamicParticle::GetLogKineticEnergy(), IsoCrossSection(), and Z.
const G4PhysicsVector * G4NeutronCaptureXS::GetPhysicsVector (G4int Z) private
Definition at line 319 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 319 of file G4NeutronCaptureXS.cc
References InitialiseOnFly().
Referenced by GetElementCrossSection(), and IsoCrossSection().
void G4NeutronCaptureXS::Initialise (G4int Z) private
Definition at line 361 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 361 of file G4NeutronCaptureXS.cc
References A(), amax, amin, FindDirectoryPath(), gDataDirectory, nmax, RetrieveVector(), v, and Z.
Referenced by BuildPhysicsTable(), and InitialiseOnFly().
void G4NeutronCaptureXS::InitialiseOnFly (G4int Z) private
Definition at line 348 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 348 of file G4NeutronCaptureXS.cc
References G4MUTEXLOCK, G4MUTEXUNLOCK, and Initialise().
Referenced by GetPhysicsVector().
G4bool G4NeutronCaptureXS::IsElementApplicable (const G4DynamicParticle * , G4int Z, const G4Material *) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 120 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 120 of file G4NeutronCaptureXS.cc
G4bool G4NeutronCaptureXS::IsIsoApplicable (const G4DynamicParticle * , G4int Z, G4int A, const G4Element * , const G4Material *) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 127 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 127 of file G4NeutronCaptureXS.cc
G4double G4NeutronCaptureXS::IsoCrossSection (G4double ekin, G4double logekin, G4int Z, G4int A) private
Definition at line 174 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 174 of file G4NeutronCaptureXS.cc
References amax, amin, barn, e1, elimit, emax, G4PhysicsVector::Energy(), G4cout, G4endl, GetPhysicsVector(), logElimit, G4PhysicsVector::LogVectorValue(), MAXZCAPTURE, MeV, min, G4VCrossSectionDataSet::verboseLevel, and Z.
Referenced by GetIsoCrossSection(), and SelectIsotope().
G4NeutronCaptureXS& G4NeutronCaptureXS::operator= (const G4NeutronCaptureXS & right) private
G4PhysicsVector * G4NeutronCaptureXS::RetrieveVector (std::ostringstream & in, G4bool warn) private
Definition at line 386 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 386 of file G4NeutronCaptureXS.cc
References FatalException, G4cout, G4endl, G4Exception(), G4PhysicsLogVector::Retrieve(), v, and G4VCrossSectionDataSet::verboseLevel.
Referenced by Initialise().
const G4Isotope * G4NeutronCaptureXS::SelectIsotope (const G4Element * anElement, G4double kinEnergy, G4double logE) final virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 224 of file G4NeutronCaptureXS.cc.
View newest version in sPHENIX GitHub at line 224 of file G4NeutronCaptureXS.cc
References amin, G4UniformRand, G4Element::GetIsotope(), G4Isotope::GetN(), G4Element::GetNumberOfIsotopes(), G4Element::GetRelativeAbundanceVector(), G4Element::GetZasInt(), IsoCrossSection(), MAXZCAPTURE, G4InuclParticleNames::nn, sum, temp, and Z.
Member Data Documentation
const G4int G4NeutronCaptureXS::amax static private
Initial value:
= {
  0,
  2,   4,   7,   9, 11,  13,  15,  18,  19,  22,
 23,  26,  27,  30, 31,  34,  37,  40,  41,  48,
 45,  50,  51,  54, 55,  58,  59,  64,  65,  70,
 71,  76,  75,   0,  0,   0,   0,   0,   0,  96,
  0, 100,   0,   0,  0, 110, 109, 116, 115, 124,
  0,   0,   0,   0,  0,   0,   0,   0,   0,   0,
  0,   0,   0,   0,  0,   0,   0,   0,   0,   0,
  0,   0, 181, 186,  0,   0,   0, 198, 197,   0,
  0, 208, 209,   0,  0,   0,   0,   0,   0,   0,
  0, 238}
Definition at line 118 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 118 of file G4NeutronCaptureXS.hh
Referenced by Initialise(), and IsoCrossSection().
const G4int G4NeutronCaptureXS::amin static private
Initial value:
= {
  0,
  1,   4,   6,   9, 10,  12,  14,  16,  19,  20,
 23,  24,  27,  28, 31,  32,  35,  36,  39,  40,
 45,  46,  50,  50, 55,  54,  59,  58,  63,  64,
 69,  70,  75,   0,  0,   0,   0,   0,   0,  90,
  0,  92,   0,   0,  0, 102, 107, 106, 113, 112,
  0,   0,   0,   0,  0,   0,   0,   0,   0,   0,
  0,   0,   0,   0,  0,   0,   0,   0,   0,   0,
  0,   0, 181, 180,  0,   0,   0, 192, 197,   0,
  0, 204, 209,   0,  0,   0,   0,   0,   0,   0,
  0, 235}
Definition at line 117 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 117 of file G4NeutronCaptureXS.hh
Referenced by Initialise(), IsoCrossSection(), and SelectIsotope().
G4ElementData * G4NeutronCaptureXS::data = nullptr static private
Definition at line 116 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 116 of file G4NeutronCaptureXS.hh
Referenced by ~G4NeutronCaptureXS().
G4double G4NeutronCaptureXS::elimit private
Definition at line 109 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 109 of file G4NeutronCaptureXS.hh
Referenced by G4NeutronCaptureXS(), GetElementCrossSection(), and IsoCrossSection().
G4double G4NeutronCaptureXS::emax private
Definition at line 108 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 108 of file G4NeutronCaptureXS.hh
Referenced by GetElementCrossSection(), and IsoCrossSection().
G4String G4NeutronCaptureXS::gDataDirectory = "" static private
Definition at line 119 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 119 of file G4NeutronCaptureXS.hh
Referenced by FindDirectoryPath(), and Initialise().
G4bool G4NeutronCaptureXS::isMaster private
Definition at line 114 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 114 of file G4NeutronCaptureXS.hh
Referenced by BuildPhysicsTable(), G4NeutronCaptureXS(), and ~G4NeutronCaptureXS().
G4double G4NeutronCaptureXS::logElimit private
Definition at line 110 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 110 of file G4NeutronCaptureXS.hh
Referenced by G4NeutronCaptureXS(), GetElementCrossSection(), and IsoCrossSection().
std::vector<G4double> G4NeutronCaptureXS::temp private
Definition at line 112 of file G4NeutronCaptureXS.hh.
View newest version in sPHENIX GitHub at line 112 of file G4NeutronCaptureXS.hh
Referenced by G4NeutronCaptureXS(), and SelectIsotope().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4NeutronCaptureXS.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4NeutronCaptureXS.cc