ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lend/src/xDataTOM_W_XYs_LegendreSeries.cc File Reference
xDataTOM_W_XYs_LegendreSeries.cc File Reference
#include <string.h>
#include "xDataTOM_private.h"
Functions
int xDataTOM_W_XYs_LegendreSeries_initialize (statusMessageReporting *smr, xDataTOM_W_XYs_LegendreSeries *W_XYs_LegendreSeries, int index, int length, double value, enum xDataTOM_subAxesType subAxesType, xDataTOM_axes *axes, xDataTOM_interpolation *interpolation)
int xDataTOM_W_XYs_LegendreSeries_free (xDataTOM_xDataInfo *xDI)
int xDataTOM_W_XYs_LegendreSeries_release (xDataTOM_W_XYs_LegendreSeries *W_XYs_LegendreSeries)
Variables
char const * xDataTOM_W_XYs_LegendreSeries_ID = "W_XYs_LegendreSeries"
Function Documentation
int xDataTOM_W_XYs_LegendreSeries_free (xDataTOM_xDataInfo * xDI)
Definition at line 34 of file xDataTOM_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 34 of file xDataTOM_W_XYs_LegendreSeries.cc
References xDataTOM_xDataInfo_s::data, xDataTOM_xDataInfo_s::ID, smr_freeMemory(), xDataTOM_W_XYs_LegendreSeries_ID, and xDataTOM_W_XYs_LegendreSeries_release().
Referenced by xDataTOM_releaseElement().
int xDataTOM_W_XYs_LegendreSeries_initialize (statusMessageReporting * smr, xDataTOM_W_XYs_LegendreSeries * W_XYs_LegendreSeries, int index, int length, double value, enum xDataTOM_subAxesType subAxesType, xDataTOM_axes * axes, xDataTOM_interpolation * interpolation)
Definition at line 19 of file xDataTOM_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 19 of file xDataTOM_W_XYs_LegendreSeries.cc
References xDataTOM_W_XYs_LegendreSeries_s::index, xDataTOM_W_XYs_LegendreSeries_s::LegendreSeries, BTOF::length, xDataTOM_W_XYs_LegendreSeries_s::length, smr_malloc2, xDataTOM_W_XYs_LegendreSeries_s::subAxes, xDataTOM_W_XYs_LegendreSeries_s::value, and xDataTOM_subAxes_initialize().
Referenced by xDataXML_regionsW_XYs_LegendreSeries_regionToTOM(), xDataXML_V_W_XYs_LegendreSeries_W_XYs_LegendreSeriesToTOM(), and xDataXML_W_XYs_LegendreSeriesToTOM().
int xDataTOM_W_XYs_LegendreSeries_release (xDataTOM_W_XYs_LegendreSeries * W_XYs_LegendreSeries)
Definition at line 45 of file xDataTOM_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 45 of file xDataTOM_W_XYs_LegendreSeries.cc
References xDataTOM_W_XYs_LegendreSeries_s::LegendreSeries, xDataTOM_W_XYs_LegendreSeries_s::length, smr_freeMemory(), and xDataTOM_LegendreSeries_release().
Referenced by xDataTOM_regionsW_XYs_LegendreSeries_release(), xDataTOM_V_W_XYs_LegendreSeries_free(), and xDataTOM_W_XYs_LegendreSeries_free().
Variable Documentation
char const* xDataTOM_W_XYs_LegendreSeries_ID = "W_XYs_LegendreSeries"
Definition at line 14 of file xDataTOM_W_XYs_LegendreSeries.cc.
View newest version in sPHENIX GitHub at line 14 of file xDataTOM_W_XYs_LegendreSeries.cc
Referenced by xDataTOM_releaseElement(), xDataTOM_W_XYs_LegendreSeries_free(), xDataXML_constructTOM(), and xDataXML_W_XYs_LegendreSeriesToTOM().