ECCE @ EIC Software: RE04TrajectoryPoint Class Reference
RE04TrajectoryPoint Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/include/RE04TrajectoryPoint.hh>
Public Member Functions
RE04TrajectoryPoint ()
RE04TrajectoryPoint (G4ThreeVector pos, const G4Material *mat)
RE04TrajectoryPoint (const RE04TrajectoryPoint &right)
virtual ~RE04TrajectoryPoint ()
void * operator new (size_t)
void operator delete (void *aTrajectoryPoint)
G4bool operator== (const RE04TrajectoryPoint &right) const
virtual const G4ThreeVector GetPosition () const
const G4Material * GetMaterial () const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Public Member Functions inherited from G4VTrajectoryPoint
G4VTrajectoryPoint ()
virtual ~G4VTrajectoryPoint ()
G4bool operator== (const G4VTrajectoryPoint &right) const
virtual const std::vector
< G4ThreeVector > * GetAuxiliaryPoints () const
Private Attributes
G4ThreeVector fPosition
const G4Material * fpMaterial
Detailed Description
Trajectory point class
new, delete and "==" operators are overwritten
const G4ThreeVector GetPosition() const gets the position of this trajectory
const G4Material* GetMaterial() const gets material that this trajectory has.
const std::map<G4String,G4AttDef>* GetAttDefs() const defines the position and the material as attiributes
std::vector<G4AttValue>* CreateAttValues() const sets and returns the attributes
Definition at line 57 of file RE04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 57 of file RE04TrajectoryPoint.hh
Constructor & Destructor Documentation
RE04TrajectoryPoint::RE04TrajectoryPoint ()
Definition at line 47 of file RE04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 47 of file RE04TrajectoryPoint.cc
RE04TrajectoryPoint::RE04TrajectoryPoint (G4ThreeVector pos, const G4Material * mat)
Definition at line 55 of file RE04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 55 of file RE04TrajectoryPoint.cc
RE04TrajectoryPoint::RE04TrajectoryPoint (const RE04TrajectoryPoint & right)
Definition at line 64 of file RE04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 64 of file RE04TrajectoryPoint.cc
RE04TrajectoryPoint::~RE04TrajectoryPoint () virtual
Definition at line 72 of file RE04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 72 of file RE04TrajectoryPoint.cc
Member Function Documentation
std::vector< G4AttValue > * RE04TrajectoryPoint::CreateAttValues () const virtual
Reimplemented from G4VTrajectoryPoint.
Definition at line 94 of file RE04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 94 of file RE04TrajectoryPoint.cc
References fpMaterial, fPosition, G4BestUnit, G4cout, GetAttDefs(), G4Material::GetName(), and Acts::Test::values.
const std::map< G4String, G4AttDef > * RE04TrajectoryPoint::GetAttDefs () const virtual
Reimplemented from G4VTrajectoryPoint.
Definition at line 77 of file RE04TrajectoryPoint.cc.
View newest version in sPHENIX GitHub at line 77 of file RE04TrajectoryPoint.cc
References G4AttDefStore::GetInstance(), mat, and pos().
Referenced by CreateAttValues().
const G4Material* RE04TrajectoryPoint::GetMaterial () const inline
Definition at line 80 of file RE04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 80 of file RE04TrajectoryPoint.hh
References fpMaterial.
virtual const G4ThreeVector RE04TrajectoryPoint::GetPosition () const inline virtual
Implements G4VTrajectoryPoint.
Definition at line 78 of file RE04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 78 of file RE04TrajectoryPoint.hh
References fPosition.
void RE04TrajectoryPoint::operator delete (void * aTrajectoryPoint) inline
Definition at line 106 of file RE04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 106 of file RE04TrajectoryPoint.hh
References faTrajPointAllocator.
void * RE04TrajectoryPoint::operator new (size_t) inline
Definition at line 99 of file RE04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 99 of file RE04TrajectoryPoint.hh
References faTrajPointAllocator.
G4bool RE04TrajectoryPoint::operator== (const RE04TrajectoryPoint & right) const inline
Definition at line 74 of file RE04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 74 of file RE04TrajectoryPoint.hh
Member Data Documentation
const G4Material* RE04TrajectoryPoint::fpMaterial private
Definition at line 93 of file RE04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 93 of file RE04TrajectoryPoint.hh
Referenced by CreateAttValues(), and GetMaterial().
G4ThreeVector RE04TrajectoryPoint::fPosition private
Definition at line 92 of file RE04TrajectoryPoint.hh.
View newest version in sPHENIX GitHub at line 92 of file RE04TrajectoryPoint.hh
Referenced by CreateAttValues(), and GetPosition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/include/RE04TrajectoryPoint.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE04/src/RE04TrajectoryPoint.cc