ECCE @ EIC Software: G4VHitsCollection Class Reference
G4VHitsCollection Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/G4VHitsCollection.hh>
Public Member Functions
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
virtual void DrawAllHits ()
virtual void PrintAllHits ()
G4String GetName ()
G4String GetSDname ()
virtual G4VHit * GetHit (size_t) const
virtual size_t GetSize () const
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
virtual void DrawAllHits ()
virtual void PrintAllHits ()
G4String GetName ()
G4String GetSDname ()
virtual G4VHit * GetHit (size_t) const
virtual size_t GetSize () const
G4VHitsCollection ()
G4VHitsCollection (G4String detName, G4String colNam)
virtual ~G4VHitsCollection ()
G4bool operator== (const G4VHitsCollection &right) const
virtual void DrawAllHits ()
virtual void PrintAllHits ()
const G4String & GetName () const
const G4String & GetSDname () const
void SetColID (G4int i)
G4int GetColID () const
virtual G4VHit * GetHit (size_t) const
virtual size_t GetSize () const
Protected Attributes
G4String collectionName
G4String SDname
G4int colID
Detailed Description
Definition at line 48 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 48 of file G4VHitsCollection.hh
Constructor & Destructor Documentation
G4VHitsCollection::G4VHitsCollection ()
Definition at line 33 of file G4VHitsCollection.cc.
View newest version in sPHENIX GitHub at line 33 of file G4VHitsCollection.cc
References colID, collectionName, and SDname.
G4VHitsCollection::G4VHitsCollection (G4String detName, G4String colNam)
Definition at line 40 of file G4VHitsCollection.cc.
View newest version in sPHENIX GitHub at line 40 of file G4VHitsCollection.cc
References colID, collectionName, and SDname.
G4VHitsCollection::~G4VHitsCollection () virtual
Definition at line 47 of file G4VHitsCollection.cc.
View newest version in sPHENIX GitHub at line 47 of file G4VHitsCollection.cc
G4VHitsCollection::G4VHitsCollection ()
G4VHitsCollection::G4VHitsCollection (G4String detName, G4String colNam)
virtual G4VHitsCollection::~G4VHitsCollection () virtual
G4VHitsCollection::G4VHitsCollection ()
G4VHitsCollection::G4VHitsCollection (G4String detName, G4String colNam)
virtual G4VHitsCollection::~G4VHitsCollection () virtual
Member Function Documentation
virtual void G4VHitsCollection::DrawAllHits () virtual
Reimplemented in G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, and G4THitsCollection< T >.
void G4VHitsCollection::DrawAllHits () virtual
Reimplemented in G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, and G4THitsCollection< T >.
Definition at line 56 of file G4VHitsCollection.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VHitsCollection.cc
Referenced by G4Event::Draw().
virtual void G4VHitsCollection::DrawAllHits () virtual
Reimplemented in G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, and G4THitsCollection< T >.
G4int G4VHitsCollection::GetColID () const inline
Definition at line 70 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 70 of file G4VHitsCollection.hh
References colID.
Referenced by G4ScoringManager::FindMesh().
virtual G4VHit* G4VHitsCollection::GetHit (size_t) const inline virtual
Reimplemented in G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4THitsCollection< T >, and G4THitsCollection< T >.
Definition at line 77 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VHitsCollection.hh
virtual G4VHit* G4VHitsCollection::GetHit (size_t) const inline virtual
Reimplemented in G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4THitsCollection< T >, and G4THitsCollection< T >.
Definition at line 84 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VHitsCollection.hh
virtual G4VHit* G4VHitsCollection::GetHit (size_t) const inline virtual
Reimplemented in G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4THitsCollection< T >, and G4THitsCollection< T >.
Definition at line 86 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VHitsCollection.hh
const G4String& G4VHitsCollection::GetName (void) const inline
Definition at line 64 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VHitsCollection.hh
References collectionName.
G4String G4VHitsCollection::GetName (void) inline
Definition at line 75 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VHitsCollection.hh
References collectionName.
Referenced by G4ScoringManager::Accumulate(), G4VScoringMesh::Accumulate(), ML2Run::DumpAllScorer(), B02Run::DumpAllScorer(), B03Run::DumpAllScorer(), B01Run::DumpAllScorer(), RE02Run::DumpAllScorer(), ElectronRun::DumpData(), RE02RunAction::EndOfRunAction(), G4SDManager::GetCollectionID(), MarshaledG4VHitsCollection::marshal1(), MarshaledG4VHitsCollection::marshal3(), and CCaloSD::PrintAll().
G4String G4VHitsCollection::GetName (void) inline
Definition at line 77 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VHitsCollection.hh
References collectionName.
const G4String& G4VHitsCollection::GetSDname () const inline
Definition at line 66 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VHitsCollection.hh
References SDname.
G4String G4VHitsCollection::GetSDname () inline
Definition at line 77 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VHitsCollection.hh
References SDname.
Referenced by G4ScoringManager::Accumulate(), ML2Run::DumpAllScorer(), B01Run::DumpAllScorer(), B03Run::DumpAllScorer(), B02Run::DumpAllScorer(), RE02Run::DumpAllScorer(), G4ScoringManager::FindMesh(), G4SDManager::GetCollectionID(), and MarshaledG4VHitsCollection::marshal2().
G4String G4VHitsCollection::GetSDname () inline
Definition at line 79 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VHitsCollection.hh
References SDname.
virtual size_t G4VHitsCollection::GetSize () const inline virtual
Reimplemented in G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4THitsCollection< T >, and G4THitsCollection< T >.
Definition at line 78 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 78 of file G4VHitsCollection.hh
virtual size_t G4VHitsCollection::GetSize () const inline virtual
Reimplemented in G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4THitsCollection< T >, and G4THitsCollection< T >.
Definition at line 85 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VHitsCollection.hh
Referenced by G4HitsModel::DescribeYourselfTo(), and B2EventAction::EndOfEventAction().
virtual size_t G4VHitsCollection::GetSize () const inline virtual
Reimplemented in G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4THitsCollection< T >, and G4THitsCollection< T >.
Definition at line 87 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VHitsCollection.hh
G4bool G4VHitsCollection::operator== (const G4VHitsCollection & right) const
G4bool G4VHitsCollection::operator== (const G4VHitsCollection & right) const
G4bool G4VHitsCollection::operator== (const G4VHitsCollection & right) const
Definition at line 50 of file G4VHitsCollection.cc.
View newest version in sPHENIX GitHub at line 50 of file G4VHitsCollection.cc
References collectionName, and SDname.
virtual void G4VHitsCollection::PrintAllHits () virtual
Reimplemented in G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, and G4THitsCollection< T >.
void G4VHitsCollection::PrintAllHits () virtual
Reimplemented in G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, and G4THitsCollection< T >.
Definition at line 59 of file G4VHitsCollection.cc.
View newest version in sPHENIX GitHub at line 59 of file G4VHitsCollection.cc
virtual void G4VHitsCollection::PrintAllHits () virtual
Reimplemented in G4THitsCollection< T >, G4TAtomicHitsCollection< T >, G4VTHitsMap< T, Map_t >, G4VTHitsMap< _Tp, std::unordered_map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::map< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::unordered_multimap< G4int, _Tp * > >, G4VTHitsMap< _Tp, std::multimap< G4int, _Tp * > >, G4TAtomicHitsMap< T >, G4TAtomicHitsMap< G4double >, G4VTHitsVector< T, Vector_t >, G4VTHitsVector< G4ConvergenceTester, std::deque< G4ConvergenceTester * > >, G4VTHitsVector< _Tp, std::deque< _Tp * > >, G4VTHitsVector< _Tp, std::vector< _Tp * > >, G4VTHitsVector< G4StatAnalysis, std::deque< G4StatAnalysis * > >, G4THitsCollection< T >, and G4THitsCollection< T >.
void G4VHitsCollection::SetColID (G4int i) inline
Definition at line 68 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VHitsCollection.hh
References colID.
Referenced by G4HCofThisEvent::AddHitsCollection().
Member Data Documentation
G4int G4VHitsCollection::colID protected
Definition at line 61 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VHitsCollection.hh
Referenced by G4VHitsCollection(), GetColID(), and SetColID().
G4String G4VHitsCollection::collectionName protected
Definition at line 62 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VHitsCollection.hh
Referenced by G4VHitsCollection(), GetName(), operator==(), G4HitsCollection::operator==(), G4THitsCollection< T >::operator==(), G4VTHitsMap< T, Map_t >::operator==(), G4VTHitsVector< T, Vector_t >::operator==(), G4TAtomicHitsMap< T >::operator==(), G4TAtomicHitsCollection< T >::operator==(), and MarshaledG4VHitsCollection::unmarshal1().
G4String G4VHitsCollection::SDname protected
Definition at line 67 of file G4VHitsCollection.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VHitsCollection.hh
Referenced by G4VHitsCollection(), GetSDname(), operator==(), and MarshaledG4VHitsCollection::unmarshal2().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/AnnotatedFiles/G4VHitsCollection.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN04/AnnotatedFiles/G4VHitsCollection.hh
geant4/tree/geant4-10.6-release/source/digits_hits/hits/include/G4VHitsCollection.hh
geant4/tree/geant4-10.6-release/source/digits_hits/hits/src/G4VHitsCollection.cc