ECCE @ EIC Software: G4LowEnergyPhotoElectric Class Reference
G4LowEnergyPhotoElectric Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4LowEnergyPhotoElectric.hh>
Public Member Functions
G4LowEnergyPhotoElectric (const G4String &processName="LowEnPhotoElec")
~G4LowEnergyPhotoElectric ()
G4bool IsApplicable (const G4ParticleDefinition &)
void BuildPhysicsTable (const G4ParticleDefinition &photon)
G4VParticleChange * PostStepDoIt (const G4Track &aTrack, const G4Step &aStep)
void SetCutForLowEnSecPhotons (G4double)
void SetCutForLowEnSecElectrons (G4double)
void ActivateAuger (G4bool)
void SetAngularGenerator (G4RDVPhotoElectricAngularDistribution *distribution)
void SetAngularGenerator (const G4String &name)
G4double DumpMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
Public Member Functions inherited from G4VDiscreteProcess
G4VDiscreteProcess (const G4String &, G4ProcessType aType=fNotDefined)
G4VDiscreteProcess (G4VDiscreteProcess &)
virtual ~G4VDiscreteProcess ()
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4double GetMeanFreePath (const G4Track &aTrack, G4double previousStepSize, G4ForceCondition *condition)
Private Member Functions
G4LowEnergyPhotoElectric & operator= (const G4LowEnergyPhotoElectric &right)
G4LowEnergyPhotoElectric (const G4LowEnergyPhotoElectric &)
Private Attributes
G4double lowEnergyLimit
G4double highEnergyLimit
G4RDVEMDataSet * meanFreePathTable
G4RDVCrossSectionHandler * crossSectionHandler
G4RDVCrossSectionHandler * shellCrossSectionHandler
G4RDVRangeTest * rangeTest
const G4double intrinsicLowEnergyLimit
const G4double intrinsicHighEnergyLimit
G4double cutForLowEnergySecondaryPhotons
G4double cutForLowEnergySecondaryElectrons
G4RDAtomicDeexcitation deexcitationManager
G4RDVPhotoElectricAngularDistribution * ElectronAngularGenerator
G4String generatorName
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 63 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LowEnergyPhotoElectric.hh
Constructor & Destructor Documentation
G4LowEnergyPhotoElectric::G4LowEnergyPhotoElectric (const G4String & processName = "LowEnPhotoElec")
Definition at line 95 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 95 of file G4LowEnergyPhotoElectric.cc
References crossSectionHandler, ElectronAngularGenerator, FatalException, G4cout, G4endl, G4Exception(), generatorName, G4VProcess::GetProcessName(), GeV, highEnergyLimit, intrinsicHighEnergyLimit, intrinsicLowEnergyLimit, keV, lowEnergyLimit, meanFreePathTable, rangeTest, shellCrossSectionHandler, and G4VProcess::verboseLevel.
G4LowEnergyPhotoElectric::~G4LowEnergyPhotoElectric ()
Definition at line 128 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 128 of file G4LowEnergyPhotoElectric.cc
References crossSectionHandler, ElectronAngularGenerator, meanFreePathTable, rangeTest, and shellCrossSectionHandler.
G4LowEnergyPhotoElectric::G4LowEnergyPhotoElectric (const G4LowEnergyPhotoElectric &) private
Member Function Documentation
void G4LowEnergyPhotoElectric::ActivateAuger (G4bool val)
Definition at line 357 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 357 of file G4LowEnergyPhotoElectric.cc
References G4RDAtomicDeexcitation::ActivateAugerElectronProduction(), and deexcitationManager.
void G4LowEnergyPhotoElectric::BuildPhysicsTable (const G4ParticleDefinition & photon) virtual
Reimplemented from G4VProcess.
Definition at line 137 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 137 of file G4LowEnergyPhotoElectric.cc
References G4RDVCrossSectionHandler::BuildMeanFreePathForMaterials(), G4RDVCrossSectionHandler::Clear(), crossSectionHandler, G4RDVCrossSectionHandler::LoadData(), G4RDVCrossSectionHandler::LoadShellData(), meanFreePathTable, and shellCrossSectionHandler.
G4double G4LowEnergyPhotoElectric::DumpMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) inline
Definition at line 89 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 89 of file G4LowEnergyPhotoElectric.hh
References GetMeanFreePath().
G4double G4LowEnergyPhotoElectric::GetMeanFreePath (const G4Track & aTrack, G4double previousStepSize, G4ForceCondition * condition) protected virtual
Implements G4VDiscreteProcess.
Definition at line 323 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 323 of file G4LowEnergyPhotoElectric.cc
References Acts::VectorHelpers::cross(), DBL_MAX, energy, G4Track::GetDynamicParticle(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterial(), material(), G4InuclParticleNames::photon, shellCrossSectionHandler, and G4RDVCrossSectionHandler::ValueForMaterial().
Referenced by DumpMeanFreePath().
G4bool G4LowEnergyPhotoElectric::IsApplicable (const G4ParticleDefinition & particle) virtual
Reimplemented from G4VProcess.
Definition at line 318 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 318 of file G4LowEnergyPhotoElectric.cc
References G4Gamma::Gamma().
G4LowEnergyPhotoElectric& G4LowEnergyPhotoElectric::operator= (const G4LowEnergyPhotoElectric & right) private
G4VParticleChange * G4LowEnergyPhotoElectric::PostStepDoIt (const G4Track & aTrack, const G4Step & aStep) virtual
Reimplemented from G4VDiscreteProcess.
Definition at line 152 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 152 of file G4LowEnergyPhotoElectric.cc
References G4ParticleChange::AddSecondary(), G4VProcess::aParticleChange, G4InuclSpecialFunctions::bindingEnergy(), G4RDAtomicShell::BindingEnergy(), crossSectionHandler, cutForLowEnergySecondaryPhotons, deexcitationManager, G4InuclParticleNames::electron, G4Electron::Electron(), ElectronAngularGenerator, G4RDVRangeTest::Escape(), fStopAndKill, G4cout, G4endl, G4RDAtomicDeexcitation::GenerateParticles(), G4DynamicParticle::GetDefinition(), G4Track::GetDynamicParticle(), G4ProductionCutsTable::GetEnergyCutsVector(), G4MaterialCutsCouple::GetIndex(), G4DynamicParticle::GetKineticEnergy(), G4Track::GetMaterialCutsCouple(), G4DynamicParticle::GetMomentumDirection(), G4RDVPhotoElectricAngularDistribution::GetPhotoElectronDirection(), G4DynamicParticle::GetPolarization(), G4Step::GetPostStepPoint(), G4ProductionCutsTable::GetProductionCutsTable(), G4StepPoint::GetSafety(), G4ParticleChange::Initialize(), G4RDAtomicTransitionManager::Instance(), k, lowEnergyLimit, min, G4VDiscreteProcess::PostStepDoIt(), G4ParticleChange::ProposeEnergy(), G4VParticleChange::ProposeLocalEnergyDeposit(), G4ParticleChange::ProposeMomentumDirection(), G4VParticleChange::ProposeTrackStatus(), rangeTest, G4RDVCrossSectionHandler::SelectRandomAtom(), G4RDVCrossSectionHandler::SelectRandomShell(), G4VParticleChange::SetNumberOfSecondaries(), G4RDAtomicTransitionManager::Shell(), shellCrossSectionHandler, G4RDAtomicShell::ShellId(), and Z.
void G4LowEnergyPhotoElectric::SetAngularGenerator (G4RDVPhotoElectricAngularDistribution * distribution)
Definition at line 362 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 362 of file G4LowEnergyPhotoElectric.cc
References ElectronAngularGenerator, and G4RDVPhotoElectricAngularDistribution::PrintGeneratorInformation().
void G4LowEnergyPhotoElectric::SetAngularGenerator (const G4String & name)
Definition at line 368 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 368 of file G4LowEnergyPhotoElectric.cc
References ElectronAngularGenerator, FatalException, G4Exception(), generatorName, and G4RDVPhotoElectricAngularDistribution::PrintGeneratorInformation().
void G4LowEnergyPhotoElectric::SetCutForLowEnSecElectrons (G4double cut)
Definition at line 351 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 351 of file G4LowEnergyPhotoElectric.cc
References cutForLowEnergySecondaryElectrons, deexcitationManager, and G4RDAtomicDeexcitation::SetCutForAugerElectrons().
void G4LowEnergyPhotoElectric::SetCutForLowEnSecPhotons (G4double cut)
Definition at line 345 of file G4LowEnergyPhotoElectric.cc.
View newest version in sPHENIX GitHub at line 345 of file G4LowEnergyPhotoElectric.cc
References cutForLowEnergySecondaryPhotons, deexcitationManager, and G4RDAtomicDeexcitation::SetCutForSecondaryPhotons().
Member Data Documentation
G4RDVCrossSectionHandler* G4LowEnergyPhotoElectric::crossSectionHandler private
Definition at line 111 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 111 of file G4LowEnergyPhotoElectric.hh
Referenced by BuildPhysicsTable(), G4LowEnergyPhotoElectric(), PostStepDoIt(), and ~G4LowEnergyPhotoElectric().
G4double G4LowEnergyPhotoElectric::cutForLowEnergySecondaryElectrons private
Definition at line 120 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 120 of file G4LowEnergyPhotoElectric.hh
Referenced by SetCutForLowEnSecElectrons().
G4double G4LowEnergyPhotoElectric::cutForLowEnergySecondaryPhotons private
Definition at line 119 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 119 of file G4LowEnergyPhotoElectric.hh
Referenced by PostStepDoIt(), and SetCutForLowEnSecPhotons().
G4RDAtomicDeexcitation G4LowEnergyPhotoElectric::deexcitationManager private
Definition at line 122 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 122 of file G4LowEnergyPhotoElectric.hh
Referenced by ActivateAuger(), PostStepDoIt(), SetCutForLowEnSecElectrons(), and SetCutForLowEnSecPhotons().
G4RDVPhotoElectricAngularDistribution* G4LowEnergyPhotoElectric::ElectronAngularGenerator private
Definition at line 124 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 124 of file G4LowEnergyPhotoElectric.hh
Referenced by G4LowEnergyPhotoElectric(), PostStepDoIt(), SetAngularGenerator(), and ~G4LowEnergyPhotoElectric().
G4String G4LowEnergyPhotoElectric::generatorName private
Definition at line 125 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 125 of file G4LowEnergyPhotoElectric.hh
Referenced by G4LowEnergyPhotoElectric(), and SetAngularGenerator().
G4double G4LowEnergyPhotoElectric::highEnergyLimit private
Definition at line 107 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 107 of file G4LowEnergyPhotoElectric.hh
Referenced by G4LowEnergyPhotoElectric().
const G4double G4LowEnergyPhotoElectric::intrinsicHighEnergyLimit private
Definition at line 117 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 117 of file G4LowEnergyPhotoElectric.hh
Referenced by G4LowEnergyPhotoElectric().
const G4double G4LowEnergyPhotoElectric::intrinsicLowEnergyLimit private
Definition at line 116 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 116 of file G4LowEnergyPhotoElectric.hh
Referenced by G4LowEnergyPhotoElectric().
G4double G4LowEnergyPhotoElectric::lowEnergyLimit private
Definition at line 106 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 106 of file G4LowEnergyPhotoElectric.hh
Referenced by G4LowEnergyPhotoElectric(), and PostStepDoIt().
G4RDVEMDataSet* G4LowEnergyPhotoElectric::meanFreePathTable private
Definition at line 109 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 109 of file G4LowEnergyPhotoElectric.hh
Referenced by BuildPhysicsTable(), G4LowEnergyPhotoElectric(), and ~G4LowEnergyPhotoElectric().
G4RDVRangeTest* G4LowEnergyPhotoElectric::rangeTest private
Definition at line 114 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 114 of file G4LowEnergyPhotoElectric.hh
Referenced by G4LowEnergyPhotoElectric(), PostStepDoIt(), and ~G4LowEnergyPhotoElectric().
G4RDVCrossSectionHandler* G4LowEnergyPhotoElectric::shellCrossSectionHandler private
Definition at line 112 of file G4LowEnergyPhotoElectric.hh.
View newest version in sPHENIX GitHub at line 112 of file G4LowEnergyPhotoElectric.hh
Referenced by BuildPhysicsTable(), G4LowEnergyPhotoElectric(), GetMeanFreePath(), PostStepDoIt(), and ~G4LowEnergyPhotoElectric().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/include/G4LowEnergyPhotoElectric.hh
geant4/tree/geant4-10.6-release/examples/advanced/eRosita/physics/src/G4LowEnergyPhotoElectric.cc