ECCE @ EIC Software: G4VPrimitiveScorer Class Reference
G4VPrimitiveScorer Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4VPrimitiveScorer.hh>
Public Member Functions
G4VPrimitiveScorer (G4String name, G4int depth=0)
virtual ~G4VPrimitiveScorer ()
G4int GetCollectionID (G4int)
virtual void Initialize (G4HCofThisEvent *)
virtual void EndOfEvent (G4HCofThisEvent *)
virtual void clear ()
virtual void DrawAll ()
virtual void PrintAll ()
void SetUnit (const G4String &unit)
const G4String & GetUnit () const
G4double GetUnitValue () const
void SetMultiFunctionalDetector (G4MultiFunctionalDetector *d)
G4MultiFunctionalDetector * GetMultiFunctionalDetector () const
G4String GetName () const
void SetFilter (G4VSDFilter *f)
G4VSDFilter * GetFilter () const
void SetVerboseLevel (G4int vl)
G4int GetVerboseLevel () const
void SetNijk (G4int i, G4int j, G4int k)
Protected Member Functions
virtual G4bool ProcessHits (G4Step *, G4TouchableHistory *)=0
virtual G4int GetIndex (G4Step *)
void CheckAndSetUnit (const G4String &unit, const G4String &category)
Protected Attributes
G4String primitiveName
G4MultiFunctionalDetector * detector
G4VSDFilter * filter
G4int verboseLevel
G4int indexDepth
G4String unitName
G4double unitValue
G4int fNi
G4int fNj
G4int fNk
Private Member Functions
G4bool HitPrimitive (G4Step *aStep, G4TouchableHistory *ROhis)
Friends
class G4MultiFunctionalDetector
Detailed Description
Definition at line 49 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 49 of file G4VPrimitiveScorer.hh
Constructor & Destructor Documentation
G4VPrimitiveScorer::G4VPrimitiveScorer (G4String name, G4int depth = 0)
Definition at line 36 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 36 of file G4VPrimitiveScorer.cc
G4VPrimitiveScorer::~G4VPrimitiveScorer () virtual
Definition at line 41 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 41 of file G4VPrimitiveScorer.cc
Member Function Documentation
void G4VPrimitiveScorer::CheckAndSetUnit (const G4String & unit, const G4String & category) protected
Definition at line 75 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 75 of file G4VPrimitiveScorer.cc
References G4Exception(), G4UnitDefinition::GetCategory(), GetName(), GetUnit(), G4UnitDefinition::GetValueOf(), JustWarning, unitName, and unitValue.
Referenced by G4PSCellCharge::SetUnit(), G4PSEnergyDeposit::SetUnit(), G4PSDoseDeposit::SetUnit(), G4PSPassageTrackLength::SetUnit(), G4PSMinKinEAtGeneration::SetUnit(), G4PSPassageCellFlux::SetUnit(), G4PSTrackLength::SetUnit(), G4PSCellFlux::SetUnit(), G4PSSphereSurfaceCurrent::SetUnit(), G4PSCylinderSurfaceFlux::SetUnit(), G4PSSphereSurfaceFlux::SetUnit(), G4PSCylinderSurfaceCurrent::SetUnit(), G4PSFlatSurfaceCurrent::SetUnit(), and G4PSFlatSurfaceFlux::SetUnit().
void G4VPrimitiveScorer::clear (void) virtual
Reimplemented in ScoreSpecies, ScoreSpecies, PrimaryKiller, PrimaryKiller, G4PSFlatSurfaceFlux, G4PSCylinderSurfaceCurrent, G4PSFlatSurfaceCurrent, G4PSSphereSurfaceFlux, G4PSCylinderSurfaceFlux, G4PSSphereSurfaceCurrent, CexmcTrackPoints, G4PSCellFlux, CexmcSimpleEnergyDeposit, G4PSNofSecondary, G4PSTrackLength, G4PSPassageCellFlux, G4PSPassageCellCurrent, G4PSPopulation, G4PSPassageTrackLength, G4PSMinKinEAtGeneration, G4PSNofCollision, G4PSTermination, G4PSTrackCounter, G4PSNofStep, G4PSStepChecker, G4PSDoseDeposit, G4PSCellCharge, and G4PSEnergyDeposit.
Definition at line 59 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 59 of file G4VPrimitiveScorer.cc
void G4VPrimitiveScorer::DrawAll (void) virtual
Reimplemented in ScoreSpecies, ScoreSpecies, PrimaryKiller, PrimaryKiller, G4PSFlatSurfaceFlux, G4PSCylinderSurfaceCurrent, G4PSFlatSurfaceCurrent, G4PSSphereSurfaceFlux, G4PSCylinderSurfaceFlux, G4PSSphereSurfaceCurrent, G4PSNofSecondary, G4PSCellFlux, G4PSTrackLength, G4PSPassageCellFlux, CexmcTrackPoints, CexmcSimpleEnergyDeposit, G4PSPassageCellCurrent, G4PSPopulation, G4PSMinKinEAtGeneration, G4PSNofCollision, G4PSTermination, G4PSTrackCounter, G4PSPassageTrackLength, G4PSNofStep, G4PSStepChecker, G4PSDoseDeposit, G4PSCellCharge, and G4PSEnergyDeposit.
Definition at line 62 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 62 of file G4VPrimitiveScorer.cc
void G4VPrimitiveScorer::EndOfEvent (G4HCofThisEvent *) virtual
Reimplemented in ScoreSpecies, ScoreSpecies, PrimaryKiller, PrimaryKiller, G4PSFlatSurfaceFlux, G4PSCylinderSurfaceCurrent, G4PSFlatSurfaceCurrent, G4PSSphereSurfaceFlux, G4PSCylinderSurfaceFlux, G4PSSphereSurfaceCurrent, G4PSCellFlux, G4PSNofSecondary, G4PSTrackLength, G4PSPassageCellFlux, CexmcTrackPoints, CexmcSimpleEnergyDeposit, G4PSPassageCellCurrent, G4PSPopulation, G4PSPassageTrackLength, G4PSMinKinEAtGeneration, G4PSNofCollision, G4PSTermination, G4PSTrackCounter, G4PSNofStep, G4PSStepChecker, G4PSDoseDeposit, G4PSCellCharge, and G4PSEnergyDeposit.
Definition at line 56 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VPrimitiveScorer.cc
G4int G4VPrimitiveScorer::GetCollectionID (G4int)
Definition at line 44 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 44 of file G4VPrimitiveScorer.cc
References detector, G4SDManager::GetCollectionID(), G4VSensitiveDetector::GetName(), G4SDManager::GetSDMpointer(), and primitiveName.
Referenced by G4PSCellCharge::Initialize(), G4PSEnergyDeposit::Initialize(), G4PSDoseDeposit::Initialize(), G4PSNofStep::Initialize(), G4PSTermination::Initialize(), G4PSTrackCounter::Initialize(), G4PSNofCollision::Initialize(), G4PSMinKinEAtGeneration::Initialize(), G4PSPassageTrackLength::Initialize(), G4PSPassageCellCurrent::Initialize(), G4PSPopulation::Initialize(), CexmcSimpleEnergyDeposit::Initialize(), CexmcTrackPoints::Initialize(), G4PSPassageCellFlux::Initialize(), G4PSTrackLength::Initialize(), G4PSNofSecondary::Initialize(), G4PSCellFlux::Initialize(), G4PSSphereSurfaceCurrent::Initialize(), G4PSCylinderSurfaceFlux::Initialize(), G4PSFlatSurfaceCurrent::Initialize(), G4PSCylinderSurfaceCurrent::Initialize(), G4PSSphereSurfaceFlux::Initialize(), G4PSFlatSurfaceFlux::Initialize(), and ScoreSpecies::Initialize().
G4VSDFilter* G4VPrimitiveScorer::GetFilter () const inline
Definition at line 106 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 106 of file G4VPrimitiveScorer.hh
References filter.
Referenced by G4VScoringMesh::List(), and G4VScoringMesh::SetFilter().
G4int G4VPrimitiveScorer::GetIndex (G4Step * aStep) protected virtual
Reimplemented in CexmcTrackPoints, CexmcSimpleEnergyDeposit, G4PSFlatSurfaceFlux3D, G4PSSphereSurfaceCurrent3D, G4PSSphereSurfaceFlux3D, RE02PSFlatSurfaceFlux, G4PSCylinderSurfaceCurrent3D, G4PSCylinderSurfaceFlux3D, G4PSFlatSurfaceCurrent3D, CexmcEnergyDepositInLeftRightSet, CexmcTrackPointsInLeftRightSet, RE02PSFlatSurfaceCurrent, G4PSCellFlux3D, CexmcEnergyDepositInCalorimeter, CexmcTrackPointsInCalorimeter, RE02PSCellFlux, G4PSPassageCellFlux3D, G4PSPassageTrackLength3D, G4PSTrackLength3D, G4PSCellCharge3D, G4PSMinKinEAtGeneration3D, RE02PSPassageCellFlux, G4PSDoseDeposit3D, G4PSTrackCounter3D, G4PSEnergyDeposit3D, G4PSNofCollision3D, G4PSPassageCellCurrent3D, G4PSPopulation3D, G4PSStepChecker3D, G4PSTermination3D, G4PSNofStep3D, RE02PSNofStep, RE02PSEnergyDeposit, and G4PSNofSecondary3D.
Definition at line 68 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 68 of file G4VPrimitiveScorer.cc
References G4Step::GetPreStepPoint(), G4TouchableHistory::GetReplicaNumber(), G4StepPoint::GetTouchable(), and indexDepth.
Referenced by G4PSDoseDeposit::ProcessHits(), G4PSStepChecker::ProcessHits(), G4PSNofStep::ProcessHits(), G4PSNofCollision::ProcessHits(), G4PSTermination::ProcessHits(), G4PSTrackCounter::ProcessHits(), G4PSCellCharge::ProcessHits(), G4PSEnergyDeposit::ProcessHits(), G4PSPopulation::ProcessHits(), G4PSMinKinEAtGeneration::ProcessHits(), G4PSPassageTrackLength::ProcessHits(), G4PSPassageCellCurrent::ProcessHits(), G4PSPassageCellFlux::ProcessHits(), G4PSNofSecondary::ProcessHits(), G4PSTrackLength::ProcessHits(), G4PSCellFlux::ProcessHits(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSFlatSurfaceFlux::ProcessHits(), and ScoreSpecies::ProcessHits().
G4MultiFunctionalDetector* G4VPrimitiveScorer::GetMultiFunctionalDetector () const inline
Definition at line 100 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 100 of file G4VPrimitiveScorer.hh
References detector.
Referenced by CexmcSensitiveDetectorMessenger::CexmcSensitiveDetectorMessenger(), G4PSEnergyDeposit::Initialize(), G4PSDoseDeposit::Initialize(), G4PSCylinderSurfaceFlux::Initialize(), G4PSFlatSurfaceFlux::Initialize(), and ScoreSpecies::Initialize().
G4String G4VPrimitiveScorer::GetName (void) const inline
Definition at line 102 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 102 of file G4VPrimitiveScorer.hh
References primitiveName.
Referenced by B01Run::B01Run(), B02Run::B02Run(), B03Run::B03Run(), CexmcSensitiveDetectorMessenger::CexmcSensitiveDetectorMessenger(), CheckAndSetUnit(), DicomRun::ConstructMFD(), Dicom2Run::ConstructMFD(), TSRun::ConstructMFD(), G4VScoringMesh::GetPrimitiveScorer(), G4PSEnergyDeposit::Initialize(), G4PSCellCharge::Initialize(), G4PSDoseDeposit::Initialize(), G4PSNofStep::Initialize(), G4PSTrackCounter::Initialize(), G4PSMinKinEAtGeneration::Initialize(), G4PSNofCollision::Initialize(), G4PSTermination::Initialize(), G4PSPassageTrackLength::Initialize(), G4PSPassageCellCurrent::Initialize(), G4PSPopulation::Initialize(), G4PSPassageCellFlux::Initialize(), G4PSTrackLength::Initialize(), G4PSNofSecondary::Initialize(), G4PSCellFlux::Initialize(), G4PSSphereSurfaceCurrent::Initialize(), G4PSCylinderSurfaceFlux::Initialize(), G4PSCylinderSurfaceCurrent::Initialize(), G4PSFlatSurfaceCurrent::Initialize(), G4PSSphereSurfaceFlux::Initialize(), G4PSFlatSurfaceFlux::Initialize(), ScoreSpecies::Initialize(), G4VScoringMesh::List(), ML2Run::ML2Run(), G4PSEnergyDeposit::PrintAll(), G4PSCellCharge::PrintAll(), G4PSDoseDeposit::PrintAll(), G4PSNofStep::PrintAll(), G4PSPassageTrackLength::PrintAll(), G4PSTrackCounter::PrintAll(), G4PSMinKinEAtGeneration::PrintAll(), G4PSNofCollision::PrintAll(), G4PSTermination::PrintAll(), G4PSPassageCellCurrent::PrintAll(), G4PSPopulation::PrintAll(), G4PSPassageCellFlux::PrintAll(), G4PSTrackLength::PrintAll(), G4PSCellFlux::PrintAll(), G4PSNofSecondary::PrintAll(), G4PSSphereSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceFlux::PrintAll(), G4PSSphereSurfaceFlux::PrintAll(), G4PSCylinderSurfaceCurrent::PrintAll(), G4PSFlatSurfaceCurrent::PrintAll(), G4PSFlatSurfaceFlux::PrintAll(), ScoreSpecies::PrintAll(), RE02Run::RE02Run(), G4MultiFunctionalDetector::RegisterPrimitive(), G4MultiFunctionalDetector::RemovePrimitive(), G4VScoringMesh::SetFilter(), G4VScoringMesh::SetPrimitiveScorer(), G4PSNofStep::SetUnit(), G4PSNofCollision::SetUnit(), G4PSTrackCounter::SetUnit(), G4PSTermination::SetUnit(), G4PSPopulation::SetUnit(), G4PSPassageCellCurrent::SetUnit(), G4PSNofSecondary::SetUnit(), G4PSSphereSurfaceCurrent::SetUnit(), G4PSCylinderSurfaceFlux::SetUnit(), G4PSFlatSurfaceCurrent::SetUnit(), G4PSSphereSurfaceFlux::SetUnit(), G4PSCylinderSurfaceCurrent::SetUnit(), and G4PSFlatSurfaceFlux::SetUnit().
const G4String& G4VPrimitiveScorer::GetUnit () const inline
Definition at line 81 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VPrimitiveScorer.hh
References unitName.
Referenced by CheckAndSetUnit(), G4VScoringMesh::GetCurrentPSUnit(), G4VScoringMesh::GetPSUnit(), G4PSEnergyDeposit::PrintAll(), G4PSCellCharge::PrintAll(), G4PSDoseDeposit::PrintAll(), G4PSPassageTrackLength::PrintAll(), G4PSMinKinEAtGeneration::PrintAll(), G4PSPassageCellFlux::PrintAll(), G4PSTrackLength::PrintAll(), G4PSCellFlux::PrintAll(), G4PSSphereSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceFlux::PrintAll(), G4PSCylinderSurfaceCurrent::PrintAll(), G4PSFlatSurfaceCurrent::PrintAll(), G4PSSphereSurfaceFlux::PrintAll(), G4PSFlatSurfaceFlux::PrintAll(), ScoreSpecies::PrintAll(), G4PSNofStep::SetUnit(), G4PSNofCollision::SetUnit(), G4PSTrackCounter::SetUnit(), G4PSTermination::SetUnit(), G4PSPassageCellCurrent::SetUnit(), G4PSPopulation::SetUnit(), G4PSNofSecondary::SetUnit(), G4PSSphereSurfaceCurrent::SetUnit(), G4PSCylinderSurfaceFlux::SetUnit(), G4PSFlatSurfaceCurrent::SetUnit(), G4PSSphereSurfaceFlux::SetUnit(), G4PSCylinderSurfaceCurrent::SetUnit(), and G4PSFlatSurfaceFlux::SetUnit().
G4double G4VPrimitiveScorer::GetUnitValue () const inline
Definition at line 82 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VPrimitiveScorer.hh
References unitValue.
Referenced by G4VScoringMesh::GetPSUnitValue(), G4PSCellCharge::PrintAll(), G4PSEnergyDeposit::PrintAll(), G4PSDoseDeposit::PrintAll(), G4PSPassageTrackLength::PrintAll(), G4PSMinKinEAtGeneration::PrintAll(), G4PSNofCollision::PrintAll(), G4PSPopulation::PrintAll(), G4PSPassageCellFlux::PrintAll(), G4PSTrackLength::PrintAll(), G4PSCellFlux::PrintAll(), G4PSNofSecondary::PrintAll(), G4PSSphereSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceFlux::PrintAll(), G4PSSphereSurfaceFlux::PrintAll(), G4PSFlatSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceCurrent::PrintAll(), G4PSFlatSurfaceFlux::PrintAll(), and ScoreSpecies::PrintAll().
G4int G4VPrimitiveScorer::GetVerboseLevel () const inline
Definition at line 110 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 110 of file G4VPrimitiveScorer.hh
References verboseLevel.
Referenced by CexmcSimpleEnergyDeposit::EndOfEvent(), and CexmcTrackPoints::EndOfEvent().
G4bool G4VPrimitiveScorer::HitPrimitive (G4Step * aStep, G4TouchableHistory * ROhis) inline private
Definition at line 114 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 114 of file G4VPrimitiveScorer.hh
References G4VSDFilter::Accept(), filter, and ProcessHits().
void G4VPrimitiveScorer::Initialize (G4HCofThisEvent *) virtual
Reimplemented in ScoreSpecies, ScoreSpecies, PrimaryKiller, PrimaryKiller, G4PSFlatSurfaceFlux, G4PSCylinderSurfaceCurrent, G4PSFlatSurfaceCurrent, G4PSSphereSurfaceFlux, G4PSCylinderSurfaceFlux, G4PSSphereSurfaceCurrent, G4PSCellFlux, G4PSNofSecondary, G4PSTrackLength, G4PSPassageCellFlux, CexmcTrackPoints, CexmcSimpleEnergyDeposit, G4PSPassageCellCurrent, G4PSPopulation, G4PSPassageTrackLength, G4PSMinKinEAtGeneration, G4PSNofCollision, G4PSTermination, G4PSTrackCounter, G4PSNofStep, G4PSStepChecker, G4PSDoseDeposit, G4PSCellCharge, and G4PSEnergyDeposit.
Definition at line 53 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 53 of file G4VPrimitiveScorer.cc
void G4VPrimitiveScorer::PrintAll (void) virtual
Reimplemented in ScoreSpecies, ScoreSpecies, PrimaryKiller, PrimaryKiller, G4PSFlatSurfaceFlux, G4PSCylinderSurfaceCurrent, G4PSFlatSurfaceCurrent, G4PSSphereSurfaceFlux, G4PSCylinderSurfaceFlux, G4PSSphereSurfaceCurrent, G4PSNofSecondary, G4PSCellFlux, G4PSTrackLength, CexmcTrackPoints, G4PSPassageCellFlux, CexmcSimpleEnergyDeposit, G4PSPassageCellCurrent, G4PSPopulation, G4PSMinKinEAtGeneration, G4PSNofCollision, G4PSTermination, G4PSTrackCounter, G4PSPassageTrackLength, G4PSNofStep, G4PSStepChecker, CexmcEnergyDepositInLeftRightSet, CexmcTrackPointsInLeftRightSet, G4PSDoseDeposit, G4PSCellCharge, G4PSEnergyDeposit, CexmcEnergyDepositInCalorimeter, and CexmcTrackPointsInCalorimeter.
Definition at line 65 of file G4VPrimitiveScorer.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VPrimitiveScorer.cc
virtual G4bool G4VPrimitiveScorer::ProcessHits (G4Step * , G4TouchableHistory *) protected pure virtual
Implemented in ScoreSpecies, ScoreSpecies, PrimaryKiller, PrimaryKiller, CexmcTrackPoints, CexmcSimpleEnergyDeposit, G4PSFlatSurfaceFlux, G4PSCylinderSurfaceCurrent, G4PSFlatSurfaceCurrent, G4PSSphereSurfaceFlux, G4PSCylinderSurfaceFlux, G4PSSphereSurfaceCurrent, G4PSCellFlux, G4PSTrackLength, G4PSNofSecondary, G4PSPassageCellFlux, G4PSPassageCellCurrent, G4PSPassageTrackLength, G4PSMinKinEAtGeneration, G4PSPopulation, G4PSCellCharge, G4PSEnergyDeposit, G4PSNofCollision, G4PSTermination, G4PSTrackCounter, G4PSDoseDeposit, G4PSNofStep, and G4PSStepChecker.
Referenced by HitPrimitive().
void G4VPrimitiveScorer::SetFilter (G4VSDFilter * f) inline
Definition at line 104 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 104 of file G4VPrimitiveScorer.hh
References f, and filter.
Referenced by ElectronBenchmarkDetector::ConstructSDandField(), B4dDetectorConstruction::ConstructSDandField(), RE02DetectorConstruction::ConstructSDandField(), G4VScoringMesh::SetFilter(), RE06ParallelWorld::SetupDetectors(), GB03DetectorConstruction::SetupDetectors(), RE06DetectorConstruction::SetupDetectors(), and CexmcSetup::SetupSpecialVolumes().
void G4VPrimitiveScorer::SetMultiFunctionalDetector (G4MultiFunctionalDetector * d) inline
Definition at line 98 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 98 of file G4VPrimitiveScorer.hh
References d, and detector.
Referenced by G4MultiFunctionalDetector::RegisterPrimitive(), and G4MultiFunctionalDetector::RemovePrimitive().
void G4VPrimitiveScorer::SetNijk (G4int i, G4int j, G4int k) inline
Definition at line 124 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 124 of file G4VPrimitiveScorer.hh
References fNi, fNj, fNk, and k.
Referenced by G4VScoringMesh::SetPrimitiveScorer().
void G4VPrimitiveScorer::SetUnit (const G4String & unit) inline
Definition at line 80 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VPrimitiveScorer.hh
References unitName.
Referenced by G4VScoringMesh::SetCurrentPSUnit().
void G4VPrimitiveScorer::SetVerboseLevel (G4int vl) inline
Definition at line 108 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 108 of file G4VPrimitiveScorer.hh
References verboseLevel.
Referenced by CexmcSensitiveDetectorMessenger::SetNewValue().
Friends And Related Function Documentation
friend class G4MultiFunctionalDetector friend
Definition at line 51 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 51 of file G4VPrimitiveScorer.hh
Member Data Documentation
G4MultiFunctionalDetector* G4VPrimitiveScorer::detector protected
Definition at line 89 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VPrimitiveScorer.hh
Referenced by GetCollectionID(), GetMultiFunctionalDetector(), G4PSCellCharge::Initialize(), G4PSNofStep::Initialize(), G4PSTermination::Initialize(), G4PSMinKinEAtGeneration::Initialize(), G4PSNofCollision::Initialize(), G4PSTrackCounter::Initialize(), G4PSPassageTrackLength::Initialize(), G4PSPopulation::Initialize(), G4PSPassageCellCurrent::Initialize(), CexmcSimpleEnergyDeposit::Initialize(), CexmcTrackPoints::Initialize(), G4PSPassageCellFlux::Initialize(), G4PSTrackLength::Initialize(), G4PSNofSecondary::Initialize(), G4PSCellFlux::Initialize(), G4PSSphereSurfaceCurrent::Initialize(), G4PSFlatSurfaceCurrent::Initialize(), G4PSSphereSurfaceFlux::Initialize(), G4PSCylinderSurfaceCurrent::Initialize(), G4PSCellCharge::PrintAll(), G4PSEnergyDeposit::PrintAll(), G4PSDoseDeposit::PrintAll(), G4PSNofStep::PrintAll(), G4PSPassageTrackLength::PrintAll(), G4PSTrackCounter::PrintAll(), G4PSTermination::PrintAll(), G4PSNofCollision::PrintAll(), G4PSPopulation::PrintAll(), G4PSPassageCellCurrent::PrintAll(), G4PSPassageCellFlux::PrintAll(), G4PSTrackLength::PrintAll(), G4PSCellFlux::PrintAll(), G4PSSphereSurfaceCurrent::PrintAll(), G4PSCylinderSurfaceFlux::PrintAll(), G4PSCylinderSurfaceCurrent::PrintAll(), G4PSFlatSurfaceCurrent::PrintAll(), G4PSSphereSurfaceFlux::PrintAll(), G4PSFlatSurfaceFlux::PrintAll(), ScoreSpecies::PrintAll(), CexmcPrimitiveScorer::PrintHeader(), and SetMultiFunctionalDetector().
G4VSDFilter* G4VPrimitiveScorer::filter protected
Definition at line 90 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VPrimitiveScorer.hh
Referenced by GetFilter(), HitPrimitive(), and SetFilter().
G4int G4VPrimitiveScorer::fNi protected
Definition at line 122 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 122 of file G4VPrimitiveScorer.hh
Referenced by G4PSCellCharge3D::G4PSCellCharge3D(), G4PSCellFlux3D::G4PSCellFlux3D(), G4PSCylinderSurfaceCurrent3D::G4PSCylinderSurfaceCurrent3D(), G4PSCylinderSurfaceFlux3D::G4PSCylinderSurfaceFlux3D(), G4PSDoseDeposit3D::G4PSDoseDeposit3D(), G4PSEnergyDeposit3D::G4PSEnergyDeposit3D(), G4PSFlatSurfaceCurrent3D::G4PSFlatSurfaceCurrent3D(), G4PSFlatSurfaceFlux3D::G4PSFlatSurfaceFlux3D(), G4PSMinKinEAtGeneration3D::G4PSMinKinEAtGeneration3D(), G4PSNofCollision3D::G4PSNofCollision3D(), G4PSNofSecondary3D::G4PSNofSecondary3D(), G4PSNofStep3D::G4PSNofStep3D(), G4PSPassageCellCurrent3D::G4PSPassageCellCurrent3D(), G4PSPassageCellFlux3D::G4PSPassageCellFlux3D(), G4PSPassageTrackLength3D::G4PSPassageTrackLength3D(), G4PSPopulation3D::G4PSPopulation3D(), G4PSSphereSurfaceCurrent3D::G4PSSphereSurfaceCurrent3D(), G4PSSphereSurfaceFlux3D::G4PSSphereSurfaceFlux3D(), G4PSStepChecker3D::G4PSStepChecker3D(), G4PSTermination3D::G4PSTermination3D(), G4PSTrackCounter3D::G4PSTrackCounter3D(), G4PSTrackLength3D::G4PSTrackLength3D(), G4PSStepChecker3D::GetIndex(), and SetNijk().
G4int G4VPrimitiveScorer::fNj protected
Definition at line 122 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 122 of file G4VPrimitiveScorer.hh
Referenced by G4PSCellCharge3D::G4PSCellCharge3D(), G4PSCellFlux3D::G4PSCellFlux3D(), G4PSCylinderSurfaceCurrent3D::G4PSCylinderSurfaceCurrent3D(), G4PSCylinderSurfaceFlux3D::G4PSCylinderSurfaceFlux3D(), G4PSDoseDeposit3D::G4PSDoseDeposit3D(), G4PSEnergyDeposit3D::G4PSEnergyDeposit3D(), G4PSFlatSurfaceCurrent3D::G4PSFlatSurfaceCurrent3D(), G4PSFlatSurfaceFlux3D::G4PSFlatSurfaceFlux3D(), G4PSMinKinEAtGeneration3D::G4PSMinKinEAtGeneration3D(), G4PSNofCollision3D::G4PSNofCollision3D(), G4PSNofSecondary3D::G4PSNofSecondary3D(), G4PSNofStep3D::G4PSNofStep3D(), G4PSPassageCellCurrent3D::G4PSPassageCellCurrent3D(), G4PSPassageCellFlux3D::G4PSPassageCellFlux3D(), G4PSPassageTrackLength3D::G4PSPassageTrackLength3D(), G4PSPopulation3D::G4PSPopulation3D(), G4PSSphereSurfaceCurrent3D::G4PSSphereSurfaceCurrent3D(), G4PSSphereSurfaceFlux3D::G4PSSphereSurfaceFlux3D(), G4PSStepChecker3D::G4PSStepChecker3D(), G4PSTermination3D::G4PSTermination3D(), G4PSTrackCounter3D::G4PSTrackCounter3D(), G4PSTrackLength3D::G4PSTrackLength3D(), G4PSNofSecondary3D::GetIndex(), G4PSNofStep3D::GetIndex(), G4PSTermination3D::GetIndex(), G4PSPopulation3D::GetIndex(), G4PSStepChecker3D::GetIndex(), G4PSNofCollision3D::GetIndex(), G4PSEnergyDeposit3D::GetIndex(), G4PSPassageCellCurrent3D::GetIndex(), G4PSDoseDeposit3D::GetIndex(), G4PSTrackCounter3D::GetIndex(), G4PSCellCharge3D::GetIndex(), G4PSMinKinEAtGeneration3D::GetIndex(), G4PSTrackLength3D::GetIndex(), G4PSPassageTrackLength3D::GetIndex(), G4PSPassageCellFlux3D::GetIndex(), G4PSCellFlux3D::GetIndex(), G4PSFlatSurfaceCurrent3D::GetIndex(), G4PSCylinderSurfaceCurrent3D::GetIndex(), G4PSCylinderSurfaceFlux3D::GetIndex(), G4PSFlatSurfaceFlux3D::GetIndex(), G4PSSphereSurfaceFlux3D::GetIndex(), G4PSSphereSurfaceCurrent3D::GetIndex(), and SetNijk().
G4int G4VPrimitiveScorer::fNk protected
Definition at line 122 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 122 of file G4VPrimitiveScorer.hh
Referenced by G4PSCellCharge3D::G4PSCellCharge3D(), G4PSCellFlux3D::G4PSCellFlux3D(), G4PSCylinderSurfaceCurrent3D::G4PSCylinderSurfaceCurrent3D(), G4PSCylinderSurfaceFlux3D::G4PSCylinderSurfaceFlux3D(), G4PSDoseDeposit3D::G4PSDoseDeposit3D(), G4PSEnergyDeposit3D::G4PSEnergyDeposit3D(), G4PSFlatSurfaceCurrent3D::G4PSFlatSurfaceCurrent3D(), G4PSFlatSurfaceFlux3D::G4PSFlatSurfaceFlux3D(), G4PSMinKinEAtGeneration3D::G4PSMinKinEAtGeneration3D(), G4PSNofCollision3D::G4PSNofCollision3D(), G4PSNofSecondary3D::G4PSNofSecondary3D(), G4PSNofStep3D::G4PSNofStep3D(), G4PSPassageCellCurrent3D::G4PSPassageCellCurrent3D(), G4PSPassageCellFlux3D::G4PSPassageCellFlux3D(), G4PSPassageTrackLength3D::G4PSPassageTrackLength3D(), G4PSPopulation3D::G4PSPopulation3D(), G4PSSphereSurfaceCurrent3D::G4PSSphereSurfaceCurrent3D(), G4PSSphereSurfaceFlux3D::G4PSSphereSurfaceFlux3D(), G4PSStepChecker3D::G4PSStepChecker3D(), G4PSTermination3D::G4PSTermination3D(), G4PSTrackCounter3D::G4PSTrackCounter3D(), G4PSTrackLength3D::G4PSTrackLength3D(), G4PSNofSecondary3D::GetIndex(), G4PSNofStep3D::GetIndex(), G4PSTermination3D::GetIndex(), G4PSPopulation3D::GetIndex(), G4PSStepChecker3D::GetIndex(), G4PSNofCollision3D::GetIndex(), G4PSEnergyDeposit3D::GetIndex(), G4PSPassageCellCurrent3D::GetIndex(), G4PSDoseDeposit3D::GetIndex(), G4PSTrackCounter3D::GetIndex(), G4PSCellCharge3D::GetIndex(), G4PSMinKinEAtGeneration3D::GetIndex(), G4PSTrackLength3D::GetIndex(), G4PSPassageTrackLength3D::GetIndex(), G4PSPassageCellFlux3D::GetIndex(), G4PSCellFlux3D::GetIndex(), G4PSFlatSurfaceCurrent3D::GetIndex(), G4PSCylinderSurfaceCurrent3D::GetIndex(), G4PSCylinderSurfaceFlux3D::GetIndex(), G4PSFlatSurfaceFlux3D::GetIndex(), G4PSSphereSurfaceFlux3D::GetIndex(), G4PSSphereSurfaceCurrent3D::GetIndex(), and SetNijk().
G4int G4VPrimitiveScorer::indexDepth protected
Definition at line 92 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 92 of file G4VPrimitiveScorer.hh
Referenced by GetIndex(), G4PSDoseDeposit::ProcessHits(), G4PSPassageCellFlux::ProcessHits(), G4PSCellFlux::ProcessHits(), G4PSSphereSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceFlux::ProcessHits(), G4PSSphereSurfaceFlux::ProcessHits(), G4PSFlatSurfaceCurrent::ProcessHits(), G4PSCylinderSurfaceCurrent::ProcessHits(), and G4PSFlatSurfaceFlux::ProcessHits().
G4String G4VPrimitiveScorer::primitiveName protected
Definition at line 88 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VPrimitiveScorer.hh
Referenced by GetCollectionID(), GetName(), CexmcSimpleEnergyDeposit::Initialize(), CexmcTrackPoints::Initialize(), and CexmcPrimitiveScorer::PrintHeader().
G4String G4VPrimitiveScorer::unitName protected
Definition at line 93 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 93 of file G4VPrimitiveScorer.hh
Referenced by CheckAndSetUnit(), GetUnit(), G4PSNofStep::SetUnit(), G4PSTrackCounter::SetUnit(), G4PSNofCollision::SetUnit(), G4PSTermination::SetUnit(), G4PSPassageCellCurrent::SetUnit(), G4PSPopulation::SetUnit(), G4PSNofSecondary::SetUnit(), SetUnit(), G4PSSphereSurfaceCurrent::SetUnit(), G4PSCylinderSurfaceFlux::SetUnit(), G4PSCylinderSurfaceCurrent::SetUnit(), G4PSSphereSurfaceFlux::SetUnit(), G4PSFlatSurfaceCurrent::SetUnit(), and G4PSFlatSurfaceFlux::SetUnit().
G4double G4VPrimitiveScorer::unitValue protected
Definition at line 94 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 94 of file G4VPrimitiveScorer.hh
Referenced by CheckAndSetUnit(), GetUnitValue(), G4PSNofStep::SetUnit(), G4PSTrackCounter::SetUnit(), G4PSNofCollision::SetUnit(), G4PSTermination::SetUnit(), G4PSPassageCellCurrent::SetUnit(), G4PSPopulation::SetUnit(), G4PSNofSecondary::SetUnit(), G4PSSphereSurfaceCurrent::SetUnit(), G4PSCylinderSurfaceFlux::SetUnit(), G4PSFlatSurfaceCurrent::SetUnit(), G4PSCylinderSurfaceCurrent::SetUnit(), G4PSSphereSurfaceFlux::SetUnit(), and G4PSFlatSurfaceFlux::SetUnit().
G4int G4VPrimitiveScorer::verboseLevel protected
Definition at line 91 of file G4VPrimitiveScorer.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VPrimitiveScorer.hh
Referenced by G4PSCellFluxForCylinder3D::ComputeVolume(), GetVerboseLevel(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/digits_hits/detector/include/G4VPrimitiveScorer.hh
geant4/tree/geant4-10.6-release/source/digits_hits/detector/src/G4VPrimitiveScorer.cc