ECCE @ EIC Software: CCalG4Able Class Reference
CCalG4Able Class Reference abstract
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Able.hh>
Public Member Functions
CCalG4Able (G4String name)
virtual ~CCalG4Able ()
G4VPhysicalVolume * PhysicalVolume (G4VPhysicalVolume *)
void setVisType (CCalVisualisable::visType, G4LogicalVolume *)
void setSensitivity (G4bool sens=true)
G4bool isSensitive () const
G4String G4Name () const
void setName (const G4String &name)
G4bool operator== (const CCalG4Able &right) const
Protected Member Functions
void AddCCalG4Able (CCalG4Able *)
virtual G4VPhysicalVolume * constructIn (G4VPhysicalVolume *)=0
virtual void constructSensitive ()
Protected Attributes
G4VPhysicalVolume * detPhysicalVolume
CCalG4AbleTable theG4DetectorsInside
G4String g4ableName
G4bool sensitivity
CCalVisualisable visProperties
G4VisAttributes * g4VisAtt [CCalVisualisable::TotalVisTypes]
Friends
std::ostream & operator<< (std::ostream &, const CCalG4Able &)
Detailed Description
Definition at line 51 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 51 of file CCalG4Able.hh
Constructor & Destructor Documentation
CCalG4Able::CCalG4Able (G4String name)
Definition at line 49 of file CCalG4Able.cc.
View newest version in sPHENIX GitHub at line 49 of file CCalG4Able.cc
References g4VisAtt, CCalSensitiveConfiguration::getInstance(), CCalSensitiveConfiguration::getSensitiveFlag(), sensitivity, and CCalVisualisable::TotalVisTypes.
CCalG4Able::~CCalG4Able () virtual
Definition at line 60 of file CCalG4Able.cc.
View newest version in sPHENIX GitHub at line 60 of file CCalG4Able.cc
References detPhysicalVolume.
Member Function Documentation
void CCalG4Able::AddCCalG4Able (CCalG4Able * det) protected
Definition at line 100 of file CCalG4Able.cc.
View newest version in sPHENIX GitHub at line 100 of file CCalG4Able.cc
References theG4DetectorsInside.
Referenced by CCalG4Hall::constructDaughters().
virtual G4VPhysicalVolume* CCalG4Able::constructIn (G4VPhysicalVolume *) protected pure virtual
Implemented in CCalG4Ecal, CCalG4Hcal, and CCalG4Hall.
Referenced by PhysicalVolume().
virtual void CCalG4Able::constructSensitive () inline protected virtual
Reimplemented in CCalG4Ecal, and CCalG4Hcal.
Definition at line 94 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 94 of file CCalG4Able.hh
Referenced by PhysicalVolume().
G4String CCalG4Able::G4Name () const inline
Definition at line 78 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 78 of file CCalG4Able.hh
References g4ableName.
Referenced by PhysicalVolume().
G4bool CCalG4Able::isSensitive () const inline
Definition at line 75 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 75 of file CCalG4Able.hh
References sensitivity.
Referenced by operator<<().
G4bool CCalG4Able::operator== (const CCalG4Able & right) const
Definition at line 133 of file CCalG4Able.cc.
View newest version in sPHENIX GitHub at line 133 of file CCalG4Able.cc
References detPhysicalVolume.
G4VPhysicalVolume * CCalG4Able::PhysicalVolume (G4VPhysicalVolume * pv)
Definition at line 65 of file CCalG4Able.cc.
View newest version in sPHENIX GitHub at line 65 of file CCalG4Able.cc
References constructIn(), constructSensitive(), detPhysicalVolume, G4cout, G4endl, G4Name(), CCalGeometryConfiguration::getInstance(), G4VPhysicalVolume::GetName(), sensitivity, G4Timer::Start(), G4Timer::Stop(), tab(), and theG4DetectorsInside.
Referenced by CCalDetectorConstruction::Construct().
void CCalG4Able::setName (const G4String & name) inline
Definition at line 79 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 79 of file CCalG4Able.hh
References g4ableName.
void CCalG4Able::setSensitivity (G4bool sens = true) inline
Definition at line 74 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 74 of file CCalG4Able.hh
References sensitivity.
void CCalG4Able::setVisType (CCalVisualisable::visType vt, G4LogicalVolume * log)
Definition at line 104 of file CCalG4Able.cc.
View newest version in sPHENIX GitHub at line 104 of file CCalG4Able.cc
References col, CCalVisualisable::colorBlue(), CCalVisualisable::colorGreen(), CCalVisualisable::colorRed(), G4cout, G4endl, g4VisAtt, G4LogicalVolume::GetName(), CCalVisualisable::isVisible(), CCalVisualisable::isWireFrame(), G4VisAttributes::SetForceWireframe(), G4LogicalVolume::SetVisAttributes(), G4VisAttributes::SetVisibility(), tab(), BlackHoleGeometry::visible, and visProperties.
Referenced by CCalG4Hcal::constructAbsorberLayer(), CCalG4Ecal::constructGlobal(), CCalG4Hall::constructIn(), CCalG4Hcal::constructIn(), and CCalG4Hcal::constructScintillatorLayer().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCalG4Able & det) friend
Definition at line 144 of file CCalG4Able.cc.
View newest version in sPHENIX GitHub at line 144 of file CCalG4Able.cc
Member Data Documentation
G4VPhysicalVolume* CCalG4Able::detPhysicalVolume protected
Definition at line 99 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 99 of file CCalG4Able.hh
Referenced by operator<<(), operator==(), PhysicalVolume(), and ~CCalG4Able().
G4String CCalG4Able::g4ableName protected
Definition at line 102 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 102 of file CCalG4Able.hh
Referenced by G4Name(), and setName().
G4VisAttributes* CCalG4Able::g4VisAtt[CCalVisualisable::TotalVisTypes] protected
Definition at line 108 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 108 of file CCalG4Able.hh
Referenced by CCalG4Able(), and setVisType().
G4bool CCalG4Able::sensitivity protected
Definition at line 104 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 104 of file CCalG4Able.hh
Referenced by CCalG4Able(), isSensitive(), PhysicalVolume(), and setSensitivity().
CCalG4AbleTable CCalG4Able::theG4DetectorsInside protected
Definition at line 100 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 100 of file CCalG4Able.hh
Referenced by AddCCalG4Able(), and PhysicalVolume().
CCalVisualisable CCalG4Able::visProperties protected
Definition at line 107 of file CCalG4Able.hh.
View newest version in sPHENIX GitHub at line 107 of file CCalG4Able.hh
Referenced by setVisType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalG4Able.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalG4Able.cc