ECCE @ EIC Software: G4BremsstrahlungParameters Class Reference
G4BremsstrahlungParameters Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4BremsstrahlungParameters.hh>
Public Member Functions
G4BremsstrahlungParameters (const G4String &name, size_t num, G4int minZ=1, G4int maxZ=99)
~G4BremsstrahlungParameters ()
G4double Parameter (G4int parameterIndex, G4int Z, G4double energy) const
G4double ParameterC (G4int index) const
void PrintData () const
Private Member Functions
G4BremsstrahlungParameters (const G4BremsstrahlungParameters &)
G4BremsstrahlungParameters & operator= (const G4BremsstrahlungParameters &right)
void LoadData (const G4String &name)
Private Attributes
std::map< G4int, G4VEMDataSet
*, std::less< G4int > > param
G4DataVector paramC
G4DataVector activeZ
G4int zMin
G4int zMax
size_t length
Detailed Description
Definition at line 61 of file G4BremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BremsstrahlungParameters.hh
Constructor & Destructor Documentation
G4BremsstrahlungParameters::G4BremsstrahlungParameters (const G4String & name, size_t num, G4int minZ = 1, G4int maxZ = 99)
Definition at line 53 of file G4BremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 53 of file G4BremsstrahlungParameters.cc
References LoadData().
G4BremsstrahlungParameters::~G4BremsstrahlungParameters ()
Definition at line 63 of file G4BremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 63 of file G4BremsstrahlungParameters.cc
References activeZ, param, paramC, and pos().
G4BremsstrahlungParameters::G4BremsstrahlungParameters (const G4BremsstrahlungParameters &) private
Member Function Documentation
void G4BremsstrahlungParameters::LoadData (const G4String & name) private
Definition at line 104 of file G4BremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 104 of file G4BremsstrahlungParameters.cc
References a, activeZ, source.hepunit::classic_electr_radius, G4DataVector::contains(), e, source.hepunit::electron_Compton_length, FatalException, G4Exception(), G4Material::GetElementVector(), G4Material::GetMaterialTable(), G4Material::GetNumberOfElements(), G4Material::GetNumberOfMaterials(), G4Material::GetTotNbOfElectPerVolume(), G4Element::GetZ(), k, length, material(), G4TrackingService::nMaterials, param, paramC, pi, sum, x, Z, and z.
Referenced by G4BremsstrahlungParameters().
G4BremsstrahlungParameters& G4BremsstrahlungParameters::operator= (const G4BremsstrahlungParameters & right) private
G4double G4BremsstrahlungParameters::Parameter (G4int parameterIndex, G4int Z, G4double energy) const
Definition at line 79 of file G4BremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 79 of file G4BremsstrahlungParameters.cc
References energy, G4VEMDataSet::FindValue(), G4cout, G4endl, G4VEMDataSet::GetEnergies(), length, max, min, param, and pos().
Referenced by G4eBremsstrahlungSpectrum::AverageEnergy(), G4eBremsstrahlungSpectrum::Probability(), and G4eBremsstrahlungSpectrum::SampleEnergy().
G4double G4BremsstrahlungParameters::ParameterC (G4int index) const
Definition at line 248 of file G4BremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 248 of file G4BremsstrahlungParameters.cc
References FatalException, G4Exception(), n, and paramC.
Referenced by G4eBremsstrahlungSpectrum::AverageEnergy().
void G4BremsstrahlungParameters::PrintData (void) const
Definition at line 264 of file G4BremsstrahlungParameters.cc.
View newest version in sPHENIX GitHub at line 264 of file G4BremsstrahlungParameters.cc
References activeZ, G4cout, G4endl, length, param, pos(), G4VEMDataSet::PrintData(), and Z.
Referenced by G4eBremsstrahlungSpectrum::PrintData().
Member Data Documentation
G4DataVector G4BremsstrahlungParameters::activeZ private
Definition at line 86 of file G4BremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 86 of file G4BremsstrahlungParameters.hh
Referenced by LoadData(), PrintData(), and ~G4BremsstrahlungParameters().
size_t G4BremsstrahlungParameters::length private
Definition at line 91 of file G4BremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 91 of file G4BremsstrahlungParameters.hh
Referenced by LoadData(), Parameter(), and PrintData().
std::map<G4int,G4VEMDataSet*,std::less<G4int> > G4BremsstrahlungParameters::param private
Definition at line 83 of file G4BremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 83 of file G4BremsstrahlungParameters.hh
Referenced by LoadData(), Parameter(), PrintData(), and ~G4BremsstrahlungParameters().
G4DataVector G4BremsstrahlungParameters::paramC private
Definition at line 85 of file G4BremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 85 of file G4BremsstrahlungParameters.hh
Referenced by LoadData(), ParameterC(), and ~G4BremsstrahlungParameters().
G4int G4BremsstrahlungParameters::zMax private
Definition at line 89 of file G4BremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 89 of file G4BremsstrahlungParameters.hh
G4int G4BremsstrahlungParameters::zMin private
Definition at line 88 of file G4BremsstrahlungParameters.hh.
View newest version in sPHENIX GitHub at line 88 of file G4BremsstrahlungParameters.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4BremsstrahlungParameters.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4BremsstrahlungParameters.cc