ECCE @ EIC Software: G4ParticleHPMadlandNixSpectrum Class Reference
G4ParticleHPMadlandNixSpectrum Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPMadlandNixSpectrum.hh>
Public Member Functions
G4ParticleHPMadlandNixSpectrum ()
~G4ParticleHPMadlandNixSpectrum ()
void Init (std::istream &aDataFile)
G4double GetFractionalProbability (G4double anEnergy)
G4double Sample (G4double anEnergy)
Public Member Functions inherited from G4VParticleHPEDis
G4VParticleHPEDis ()
virtual ~G4VParticleHPEDis ()
Private Member Functions
G4double Madland (G4double aSecEnergy, G4double tm)
G4double FissionIntegral (G4double tm, G4double anEnergy)
G4double GIntegral (G4double tm, G4double anEnergy, G4double aMean)
G4double Gamma05 (G4double aValue)
G4double Gamma15 (G4double aValue)
G4double Gamma25 (G4double aValue)
G4double E1 (G4double aValue)
Private Attributes
G4double expm1
G4ParticleHPVector theFractionalProb
G4double theAvarageKineticPerNucleonForLightFragments
G4double theAvarageKineticPerNucleonForHeavyFragments
G4ParticleHPVector theMaxTemp
Detailed Description
Definition at line 51 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPMadlandNixSpectrum.hh
Constructor & Destructor Documentation
G4ParticleHPMadlandNixSpectrum::G4ParticleHPMadlandNixSpectrum () inline
Definition at line 54 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 54 of file G4ParticleHPMadlandNixSpectrum.hh
References expm1, G4Exp(), theAvarageKineticPerNucleonForHeavyFragments, and theAvarageKineticPerNucleonForLightFragments.
G4ParticleHPMadlandNixSpectrum::~G4ParticleHPMadlandNixSpectrum () inline
Definition at line 60 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 60 of file G4ParticleHPMadlandNixSpectrum.hh
Member Function Documentation
G4double G4ParticleHPMadlandNixSpectrum::E1 (G4double aValue) inline private
Definition at line 119 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ParticleHPMadlandNixSpectrum.hh
References G4Log(), and precision.
Referenced by GIntegral(), and Madland().
G4double G4ParticleHPMadlandNixSpectrum::FissionIntegral (G4double tm, G4double anEnergy) inline private
Definition at line 85 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 85 of file G4ParticleHPMadlandNixSpectrum.hh
References GIntegral(), theAvarageKineticPerNucleonForHeavyFragments, and theAvarageKineticPerNucleonForLightFragments.
Referenced by Sample().
G4double G4ParticleHPMadlandNixSpectrum::Gamma05 (G4double aValue) inline private
Definition at line 93 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 93 of file G4ParticleHPMadlandNixSpectrum.hh
References G4Exp(), CLHEP::pi, t, and x.
Referenced by Gamma15().
G4double G4ParticleHPMadlandNixSpectrum::Gamma15 (G4double aValue) inline private
Definition at line 104 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 104 of file G4ParticleHPMadlandNixSpectrum.hh
References G4Exp(), and Gamma05().
Referenced by Gamma25(), GIntegral(), and Madland().
G4double G4ParticleHPMadlandNixSpectrum::Gamma25 (G4double aValue) inline private
Definition at line 112 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPMadlandNixSpectrum.hh
References G4Exp(), Gamma15(), G4Pow::GetInstance(), and G4Pow::powA().
Referenced by GIntegral().
G4double G4ParticleHPMadlandNixSpectrum::GetFractionalProbability (G4double anEnergy) inline virtual
Implements G4VParticleHPEDis.
Definition at line 74 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleHPMadlandNixSpectrum.hh
References G4ParticleHPVector::GetY(), and theFractionalProb.
G4double G4ParticleHPMadlandNixSpectrum::GIntegral (G4double tm, G4double anEnergy, G4double aMean) private
Definition at line 112 of file G4ParticleHPMadlandNixSpectrum.cc.
View newest version in sPHENIX GitHub at line 112 of file G4ParticleHPMadlandNixSpectrum.cc
References A(), alpha, b, B(), E1(), eV, G4Exp(), Gamma15(), Gamma25(), G4Pow::GetInstance(), G4Pow::powA(), and G4InuclParticleNames::tm.
Referenced by FissionIntegral().
void G4ParticleHPMadlandNixSpectrum::Init (std::istream & aDataFile) inline virtual
Implements G4VParticleHPEDis.
Definition at line 64 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ParticleHPMadlandNixSpectrum.hh
References CLHEP::eV, G4ParticleHPVector::Init(), theAvarageKineticPerNucleonForHeavyFragments, theAvarageKineticPerNucleonForLightFragments, theFractionalProb, and theMaxTemp.
G4double G4ParticleHPMadlandNixSpectrum::Madland (G4double aSecEnergy, G4double tm) private
Definition at line 34 of file G4ParticleHPMadlandNixSpectrum.cc.
View newest version in sPHENIX GitHub at line 34 of file G4ParticleHPMadlandNixSpectrum.cc
References E1(), energy, eV, Gamma15(), G4Pow::GetInstance(), G4Pow::powA(), theAvarageKineticPerNucleonForHeavyFragments, theAvarageKineticPerNucleonForLightFragments, and G4InuclParticleNames::tm.
G4double G4ParticleHPMadlandNixSpectrum::Sample (G4double anEnergy) virtual
Implements G4VParticleHPEDis.
Definition at line 74 of file G4ParticleHPMadlandNixSpectrum.cc.
View newest version in sPHENIX GitHub at line 74 of file G4ParticleHPMadlandNixSpectrum.cc
References kdfinder::abs(), FissionIntegral(), G4cout, G4endl, G4UniformRand, G4ParticleHPVector::GetY(), MeV, precision, theMaxTemp, and G4InuclParticleNames::tm.
Member Data Documentation
G4double G4ParticleHPMadlandNixSpectrum::expm1 private
Definition at line 147 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 147 of file G4ParticleHPMadlandNixSpectrum.hh
Referenced by G4ParticleHPMadlandNixSpectrum().
G4double G4ParticleHPMadlandNixSpectrum::theAvarageKineticPerNucleonForHeavyFragments private
Definition at line 154 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 154 of file G4ParticleHPMadlandNixSpectrum.hh
Referenced by FissionIntegral(), G4ParticleHPMadlandNixSpectrum(), Init(), and Madland().
G4double G4ParticleHPMadlandNixSpectrum::theAvarageKineticPerNucleonForLightFragments private
Definition at line 153 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 153 of file G4ParticleHPMadlandNixSpectrum.hh
Referenced by FissionIntegral(), G4ParticleHPMadlandNixSpectrum(), Init(), and Madland().
G4ParticleHPVector G4ParticleHPMadlandNixSpectrum::theFractionalProb private
Definition at line 151 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 151 of file G4ParticleHPMadlandNixSpectrum.hh
Referenced by GetFractionalProbability(), and Init().
G4ParticleHPVector G4ParticleHPMadlandNixSpectrum::theMaxTemp private
Definition at line 156 of file G4ParticleHPMadlandNixSpectrum.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ParticleHPMadlandNixSpectrum.hh
Referenced by Init(), and Sample().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPMadlandNixSpectrum.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPMadlandNixSpectrum.cc