ECCE @ EIC Software: G4VProcess Class Reference
G4VProcess Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/management/include/G4VProcess.hh>
Public Member Functions
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &stepData)=0
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &stepData)=0
virtual G4VParticleChange * AtRestDoIt (const G4Track &track, const G4Step &stepData)=0
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)=0
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &track, G4ForceCondition *condition)=0
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)=0
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void StartTracking (G4Track *)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Static Public Member Functions
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Private Member Functions
G4VProcess & operator= (const G4VProcess &right)
Private Attributes
G4VProcess * masterProcessShadow
Detailed Description
Definition at line 74 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VProcess.hh
Constructor & Destructor Documentation
G4VProcess::G4VProcess (const G4String & aName = "NoName", G4ProcessType aType = fNotDefined)
Definition at line 52 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 52 of file G4VProcess.cc
References aParticleChange, and pParticleChange.
G4VProcess::G4VProcess (const G4VProcess & right)
Definition at line 76 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 76 of file G4VProcess.cc
G4VProcess::~G4VProcess () virtual
Definition at line 72 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 72 of file G4VProcess.cc
Member Function Documentation
virtual G4VParticleChange* G4VProcess::AlongStepDoIt (const G4Track & track, const G4Step & stepData) pure virtual
Implemented in G4BiasingProcessInterface, G4VMultipleScattering, G4VEnergyLossProcess, G4hImpactIonisation, G4Cerenkov, G4ParallelGeometriesLimiterProcess, G4DNABrownianTransportation, G4FastSimulationManagerProcess, G4ITTransportation, G4WeightWindowProcess, G4ImportanceProcess, G4ParallelWorldScoringProcess, G4ScoreSplittingProcess, G4WeightCutOffProcess, G4ParallelWorldProcess, G4eLowEnergyLoss, G4VRestProcess, G4ContinuousGainOfEnergy, G4DNASecondOrderReaction, G4VITRestProcess, G4VDiscreteProcess, G4VRestDiscreteProcess, G4AdjointAlongStepWeightCorrection, DMXSpecialCuts, G4SpecialCuts, G4VITRestDiscreteProcess, G4RDVeLowEnergyLoss, G4WrapperProcess, G4UserSpecialCuts, G4VRestContinuousDiscreteProcess, G4VRestContinuousProcess, G4StepLimiter, G4AdjointForcedInteractionForGamma, G4VContinuousDiscreteProcess, G4MonopoleTransportation, G4VITDiscreteProcess, G4CoupledTransportation, G4NuclearStopping, G4VContinuousProcess, G4AdjointProcessEquivalentToDirectProcess, G4Transportation, and G4ErrorEnergyLoss.
Referenced by G4AdjointProcessEquivalentToDirectProcess::AlongStepDoIt(), G4WrapperProcess::AlongStepDoIt(), G4BiasingProcessInterface::AlongStepDoIt(), and G4SteppingManager::InvokeAlongStepDoItProcs().
virtual G4double G4VProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) pure virtual
Implemented in G4BiasingProcessInterface, G4VMultipleScattering, G4VEnergyLossProcess, G4ParallelGeometriesLimiterProcess, G4Cerenkov, G4DNABrownianTransportation, G4FastSimulationManagerProcess, G4ITTransportation, G4WeightWindowProcess, G4ParallelWorldScoringProcess, G4ScoreSplittingProcess, G4ImportanceProcess, G4WeightCutOffProcess, G4ParallelWorldProcess, G4WrapperProcess, G4DNASecondOrderReaction, G4VRestDiscreteProcess, G4AdjointProcessEquivalentToDirectProcess, G4VRestProcess, DMXSpecialCuts, G4SpecialCuts, G4VDiscreteProcess, G4VITRestDiscreteProcess, G4VITRestProcess, G4UserSpecialCuts, G4VRestContinuousDiscreteProcess, G4VRestContinuousProcess, G4VContinuousDiscreteProcess, G4StepLimiter, G4MonopoleTransportation, G4NuclearStopping, G4CoupledTransportation, G4VContinuousProcess, G4Transportation, and G4VITDiscreteProcess.
Referenced by G4BiasingProcessInterface::AlongStepGetPhysicalInteractionLength(), and AlongStepGPIL().
G4double G4VProcess::AlongStepGPIL (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) inline
Definition at line 481 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 481 of file G4VProcess.hh
References AlongStepGetPhysicalInteractionLength().
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength().
virtual G4VParticleChange* G4VProcess::AtRestDoIt (const G4Track & track, const G4Step & stepData) pure virtual
Implemented in G4RadioactiveDecay, G4RadioactiveDecayBase, G4BiasingProcessInterface, G4Radioactivation, G4CoupledTransportation, G4ParallelGeometriesLimiterProcess, G4Transportation, G4Cerenkov, G4Scintillation, G4FastSimulationManagerProcess, G4MonopoleTransportation, G4WeightWindowProcess, G4ImportanceProcess, G4WeightCutOffProcess, G4ITTransportation, G4ParallelWorldScoringProcess, G4ScoreSplittingProcess, G4VContinuousDiscreteProcess, G4VContinuousProcess, G4ParallelWorldProcess, G4VRestContinuousDiscreteProcess, G4VDiscreteProcess, G4WrapperProcess, G4Decay, G4DNASecondOrderReaction, G4MuonicAtomDecay, G4VRestDiscreteProcess, G4AdjointProcessEquivalentToDirectProcess, G4DNAMolecularDissociation, G4HadronStoppingProcess, G4MuonMinusAtomicCapture, G4VRestProcess, DMXSpecialCuts, G4SpecialCuts, G4VITDiscreteProcess, G4VITRestDiscreteProcess, G4VITRestProcess, G4eplusAnnihilation, G4VRestContinuousProcess, G4UserSpecialCuts, G4StepLimiter, G4AntiNeutronAnnihilationAtRest, G4DecayWithSpin, and G4DNAElectronHoleRecombination.
Referenced by G4AdjointProcessEquivalentToDirectProcess::AtRestDoIt(), G4WrapperProcess::AtRestDoIt(), G4BiasingProcessInterface::AtRestDoIt(), and G4SteppingManager::InvokeAtRestDoItProcs().
virtual G4double G4VProcess::AtRestGetPhysicalInteractionLength (const G4Track & track, G4ForceCondition * condition) pure virtual
Implemented in G4RadioactiveDecay, G4RadioactiveDecayBase, G4BiasingProcessInterface, G4CoupledTransportation, G4ParallelGeometriesLimiterProcess, G4Transportation, G4Cerenkov, G4FastSimulationManagerProcess, G4MonopoleTransportation, G4Decay, G4WeightWindowProcess, G4ImportanceProcess, G4WeightCutOffProcess, G4WrapperProcess, G4ITTransportation, G4ParallelWorldProcess, G4ParallelWorldScoringProcess, G4AdjointProcessEquivalentToDirectProcess, G4ScoreSplittingProcess, G4VContinuousDiscreteProcess, G4VContinuousProcess, G4VRestContinuousDiscreteProcess, G4VDiscreteProcess, G4DNASecondOrderReaction, G4MuonicAtomDecay, G4DNAMolecularDissociation, G4eplusAnnihilation, G4VRestDiscreteProcess, G4HadronStoppingProcess, G4MuonMinusAtomicCapture, G4VITRestDiscreteProcess, G4VITRestProcess, G4VRestProcess, DMXSpecialCuts, G4SpecialCuts, G4VITDiscreteProcess, G4VRestContinuousProcess, G4UserSpecialCuts, G4StepLimiter, and G4AntiNeutronAnnihilationAtRest.
Referenced by G4AdjointProcessEquivalentToDirectProcess::AtRestGetPhysicalInteractionLength(), G4WrapperProcess::AtRestGetPhysicalInteractionLength(), G4BiasingProcessInterface::AtRestGetPhysicalInteractionLength(), and AtRestGPIL().
G4double G4VProcess::AtRestGPIL (const G4Track & track, G4ForceCondition * condition) inline
Definition at line 492 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 492 of file G4VProcess.hh
References AtRestGetPhysicalInteractionLength(), and thePILfactor.
Referenced by G4ITStepProcessor::GetAtRestIL(), and G4SteppingManager::InvokeAtRestDoItProcs().
virtual void G4VProcess::BuildPhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented in G4ScreenedNuclearRecoil, G4RadioactiveDecay, G4BiasingProcessInterface, G4RadioactiveDecayBase, G4VITProcess, G4VEnergyLossProcess, G4VMultipleScattering, G4Scintillation, G4WrapperProcess, G4DNABrownianTransportation, G4VEmProcess, G4AdjointProcessEquivalentToDirectProcess, G4Cerenkov, G4HadronicProcess, G4ContinuousGainOfEnergy, G4Decay, G4ePolarizedIonisation, G4VXTRenergyLoss, G4GammaGeneralProcess, G4PolarizedCompton, G4AdjointAlongStepWeightCorrection, G4SynchrotronRadiation, G4hImpactIonisation, G4ITTransportation, G4VAdjointReverseReaction, G4AdjointForcedInteractionForGamma, G4eplusPolarizedAnnihilation, G4OpWLS, G4LowEnergyBremsstrahlung, G4LowEnergyPolarizedCompton, G4OpRayleigh, G4LowEnergyIonisation, G4ElectronCapture, G4ElectronCapture, G4ElectronCapture, G4LowECapture, G4HadronStoppingProcess, G4MuonMinusAtomicCapture, G4LowEnergyPhotoElectric, G4ElectronCapture, G4GammaConversionToMuons, G4LowEnergyGammaConversion, G4DNASecondOrderReaction, G4LowEnergyCompton, G4UnknownDecay, G4LowEnergyRayleigh, G4AnnihiToMuPair, G4AntiNeutronAnnihilationAtRest, G4ChargeExchangeProcess, StepMax, StepMax, StepMax, StepMax, StepMax, G4Channeling, and G4DNAElectronHoleRecombination.
Definition at line 209 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 209 of file G4VProcess.hh
Referenced by G4VUserPhysicsList::BuildIntegralPhysicsTable(), G4AdjointProcessEquivalentToDirectProcess::BuildPhysicsTable(), G4WrapperProcess::BuildPhysicsTable(), G4BiasingProcessInterface::BuildPhysicsTable(), BuildWorkerPhysicsTable(), and export_G4VProcess().
void G4VProcess::BuildWorkerPhysicsTable (const G4ParticleDefinition & part) virtual
Reimplemented in G4BiasingProcessInterface.
Definition at line 206 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 206 of file G4VProcess.cc
References BuildPhysicsTable().
Referenced by G4BiasingProcessInterface::BuildWorkerPhysicsTable().
void G4VProcess::ClearNumberOfInteractionLengthLeft () inline protected
Definition at line 449 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 449 of file G4VProcess.hh
References theInitialNumberOfInteractionLength, and theNumberOfInteractionLengthLeft.
Referenced by G4VContinuousDiscreteProcess::AlongStepDoIt(), G4VRestContinuousProcess::AtRestDoIt(), G4VRestProcess::AtRestDoIt(), G4VRestDiscreteProcess::AtRestDoIt(), G4VRestContinuousDiscreteProcess::AtRestDoIt(), G4RadioactiveDecayBase::DecayAnalog(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4MuonicAtomDecay::DecayIt(), G4Radioactivation::DecayIt(), G4RadioactiveDecayBase::DecayIt(), G4RadioactiveDecay::DecayIt(), G4Decay::EndTracking(), G4HadronElasticProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4TransitionRadiation::PostStepDoIt(), G4VContinuousDiscreteProcess::PostStepDoIt(), G4VRestDiscreteProcess::PostStepDoIt(), G4VRestContinuousDiscreteProcess::PostStepDoIt(), G4VDiscreteProcess::PostStepDoIt(), G4VAdjointReverseReaction::PostStepDoIt(), G4HadronicProcess::PostStepDoIt(), and G4VEmProcess::PostStepDoIt().
void G4VProcess::DumpInfo () const virtual
Definition at line 178 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 178 of file G4VProcess.cc
References G4cout, G4endl, GetProcessTypeName(), theProcessName, theProcessSubType, and theProcessType.
Referenced by G4ProcessTable::DumpInfo(), export_G4VProcess(), and G4ProcessManagerMessenger::SetNewValue().
void G4VProcess::EndTracking () virtual
Reimplemented in G4WrapperProcess, G4BiasingProcessInterface, G4CoupledTransportation, G4AdjointProcessEquivalentToDirectProcess, G4Decay, G4ParallelGeometriesLimiterProcess, G4FastSimulationManagerProcess, and G4VPhononProcess.
Definition at line 113 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 113 of file G4VProcess.cc
References currentInteractionLength, G4cout, G4endl, theInitialNumberOfInteractionLength, theNumberOfInteractionLengthLeft, theProcessName, and verboseLevel.
Referenced by G4VPhononProcess::EndTracking(), G4AdjointProcessEquivalentToDirectProcess::EndTracking(), G4BiasingProcessInterface::EndTracking(), and G4WrapperProcess::EndTracking().
G4double G4VProcess::GetCurrentInteractionLength () const inline
Definition at line 464 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 464 of file G4VProcess.hh
References currentInteractionLength.
Referenced by G4BiasingProcessInterface::InvokeWrappedProcessPostStepGPIL(), G4BOptrForceCollision::ProposeOccurenceBiasingOperation(), GB01BOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), and G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation().
const G4VProcess * G4VProcess::GetMasterProcess () const inline
Definition at line 540 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 540 of file G4VProcess.hh
References masterProcessShadow.
Referenced by G4eplusPolarizedAnnihilation::BuildPhysicsTable(), G4PolarizedCompton::BuildPhysicsTable(), G4ePolarizedIonisation::BuildPhysicsTable(), G4VEmProcess::BuildPhysicsTable(), G4VMultipleScattering::BuildPhysicsTable(), G4VEnergyLossProcess::BuildPhysicsTable(), G4BiasingProcessInterface::SetMasterProcess(), and G4VMultipleScattering::StorePhysicsTable().
G4double G4VProcess::GetNumberOfInteractionLengthLeft () const inline
Definition at line 455 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 455 of file G4VProcess.hh
References theNumberOfInteractionLengthLeft.
const G4String & G4VProcess::GetPhysicsTableFileName (const G4ParticleDefinition * particle, const G4String & directory, const G4String & tableName, G4bool ascii = false)
Definition at line 190 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 190 of file G4VProcess.cc
References G4ParticleDefinition::GetParticleName(), thePhysicsTableFileName, and theProcessName.
Referenced by export_G4VProcess(), G4GammaGeneralProcess::RetrievePhysicsTable(), G4VEmProcess::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrieveTable(), G4GammaGeneralProcess::StorePhysicsTable(), G4VMultipleScattering::StorePhysicsTable(), G4VEmProcess::StorePhysicsTable(), and G4VEnergyLossProcess::StoreTable().
G4double G4VProcess::GetPILfactor () const inline
Definition at line 476 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 476 of file G4VProcess.hh
References thePILfactor.
Referenced by export_G4VProcess().
const G4ProcessManager * G4VProcess::GetProcessManager () inline virtual
Reimplemented in G4BiasingProcessInterface, and G4WrapperProcess.
Definition at line 516 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 516 of file G4VProcess.hh
References aProcessManager.
Referenced by G4WrapperProcess::GetProcessManager(), and G4BiasingProcessInterface::GetProcessManager().
const G4String & G4VProcess::GetProcessName () const inline
Definition at line 410 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 410 of file G4VProcess.hh
References theProcessName.
Referenced by G4VEmProcess::ActivateForcedInteraction(), G4VEnergyLossProcess::ActivateForcedInteraction(), G4ProcessManager::ActivateProcess(), G4VEmProcess::ActivateSecondaryBiasing(), G4VEnergyLossProcess::ActivateSecondaryBiasing(), G4VEnergyLossProcess::AddCollaborativeProcess(), G4ParallelGeometriesLimiterProcess::AddParallelWorld(), G4IonINCLXXPhysics::AddProcess(), G4IonQMDPhysics::AddProcess(), G4ProcessManager::AddProcess(), G4ProcessPlacer::AddProcessAs(), G4ITSteppingVerbose::AlongStepDoItAllDone(), G4SteppingVerbose::AlongStepDoItAllDone(), G4SteppingVerbose::AlongStepDoItOneByOne(), G4VContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(), XrayFluoAnalysisManager::analyseStepping(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4ITSteppingVerbose::AtRestDoItInvoked(), G4SteppingVerbose::AtRestDoItInvoked(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4HadronicProcess::BiasCrossSectionByFactor(), G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4VEnergyLossProcess::BuildDEDXTable(), G4VUserPhysicsList::BuildIntegralPhysicsTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), StepMax::BuildPhysicsTable(), G4LowEnergyIonisation::BuildPhysicsTable(), G4LowEnergyBremsstrahlung::BuildPhysicsTable(), G4LossTableManager::BuildPhysicsTable(), G4VEmProcess::BuildPhysicsTable(), G4DNABrownianTransportation::BuildPhysicsTable(), G4VMultipleScattering::BuildPhysicsTable(), G4VEnergyLossProcess::BuildPhysicsTable(), G4ScreenedNuclearRecoil::BuildPhysicsTable(), G4LossTableManager::BuildTables(), G4HadronicProcess::CheckEnergyMomentumConservation(), G4ProcessManager::CheckOrderingParameters(), G4HadronicProcess::CheckResult(), G4EicDircStackingAction::ClassifyNewTrack(), LXeStackingAction::ClassifyNewTrack(), OpNoviceStackingAction::ClassifyNewTrack(), G4StackChecker::ClassifyNewTrack(), G4BOptrForceCollision::ConfigureForWorker(), G4RunManagerKernel::ConfirmCoupledTransportation(), G4HadronDElasticPhysics::ConstructProcess(), G4IonElasticPhysics::ConstructProcess(), G4HadronHElasticPhysics::ConstructProcess(), G4FastSimulationPhysics::ConstructProcess(), G4HadronElasticPhysics::ConstructProcess(), G4GenericBiasingPhysics::ConstructProcess(), G4LossTableManager::CopyTables(), Run::CountProcesses(), G4RichTrajectory::CreateAttValues(), G4RichTrajectoryPoint::CreateAttValues(), CCaloSD::createNewHit(), G4VPhononProcess::CreateSecondary(), G4EmExtraParameters::DefineRegParamForEM(), G4EmExtraParameters::DefineRegParamForLoss(), G4HadronicProcessStore::DeRegisterExtraProcess(), DMXMaxTimeCuts::DMXMaxTimeCuts(), DMXMinEkineCuts::DMXMinEkineCuts(), DMXSpecialCuts::DMXSpecialCuts(), G4SteppingVerbose::DPSLAlongStep(), G4SteppingVerbose::DPSLPostStep(), G4HadronicProcessStore::Dump(), G4MuonicAtomDecay::DumpState(), G4HadronicProcess::DumpState(), G4ExceptionHandler::DumpTrackInfo(), export_G4VProcess(), F04StepMax::F04StepMax(), G4EmCalculator::FindEmModel(), G4VEmProcess::FindLambdaMax(), G4AntiNeutronAnnihilationAtRest::G4AntiNeutronAnnihilationAtRest(), G4BiasingProcessInterface::G4BiasingProcessInterface(), G4Cerenkov::G4Cerenkov(), G4ErrorEnergyLoss::G4ErrorEnergyLoss(), G4ErrorTrackLengthTarget::G4ErrorTrackLengthTarget(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), G4ImportanceProcess::G4ImportanceProcess(), G4LowEnergyCompton::G4LowEnergyCompton(), G4LowEnergyGammaConversion::G4LowEnergyGammaConversion(), G4LowEnergyPhotoElectric::G4LowEnergyPhotoElectric(), G4LowEnergyPolarizedCompton::G4LowEnergyPolarizedCompton(), G4LowEnergyRayleigh::G4LowEnergyRayleigh(), G4MaxTimeCuts::G4MaxTimeCuts(), G4MinEkineCuts::G4MinEkineCuts(), G4OpAbsorption::G4OpAbsorption(), G4OpBoundaryProcess::G4OpBoundaryProcess(), G4OpMieHG::G4OpMieHG(), G4OpRayleigh::G4OpRayleigh(), G4OpWLS::G4OpWLS(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4Scintillation::G4Scintillation(), G4ScoreSplittingProcess::G4ScoreSplittingProcess(), G4SpecialCuts::G4SpecialCuts(), G4StepLimiter::G4StepLimiter(), G4UCNAbsorption::G4UCNAbsorption(), G4UCNBoundaryProcess::G4UCNBoundaryProcess(), G4UCNLoss::G4UCNLoss(), G4UCNMultiScattering::G4UCNMultiScattering(), G4UserSpecialCuts::G4UserSpecialCuts(), G4VEmProcess::G4VEmProcess(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), G4HadronicProcess::GetElementCrossSection(), G4GammaGeneralProcess::GetEmProcess(), G4VEmProcess::GetEmProcess(), G4WeightWindowProcess::GetName(), PhysicsList::GetProcess(), G4ProcessManager::GetProcess(), G4GammaGeneralProcess::GetProcessName(), G4ProcessManager::GetProcessVectorIndex(), G4ProcessManager::InActivateProcess(), G4hhIonisation::InitialiseEnergyLossProcess(), G4ProcessTable::Insert(), G4SteppingManager::InvokeAlongStepDoItProcs(), G4SteppingManager::InvokeAtRestDoItProcs(), G4SteppingManager::InvokePSDIP(), G4LossTableManager::LocalPhysicsTables(), G4ErrorPropagator::MakeOneStep(), G4VEmProcess::PostStepDoIt(), G4SteppingVerbose::PostStepDoItAllDone(), G4ITSteppingVerbose::PostStepDoItAllDone(), G4SteppingVerbose::PostStepDoItOneByOne(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4ITSteppingVerbose::PostStepVerbose(), LXeTrackingAction::PostUserTrackingAction(), G4EmConfigurator::PrepareModels(), G4HadronStoppingProcess::PreparePhysicsTable(), G4LossTableManager::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), CexmcTrackingAction::PreUserTrackingAction(), G4HadronicProcessStore::Print(), G4HadronicProcessStore::PrintHtml(), G4AnnihiToMuPair::PrintInfoDefinition(), G4GammaConversionToMuons::PrintInfoDefinition(), G4LowEnergyIonisation::PrintInfoDefinition(), G4SynchrotronRadiation::PrintInfoDefinition(), G4LowEnergyBremsstrahlung::PrintInfoDefinition(), G4hImpactIonisation::PrintInfoDefinition(), G4ProcessPlacer::PrintProcVec(), G4VEmProcess::PrintWarning(), G4VEnergyLossProcess::PrintWarning(), G4PionDecayMakeSpin::ProcessDescription(), G4DecayWithSpin::ProcessDescription(), G4UnknownDecay::ProcessDescription(), G4Decay::ProcessDescription(), STCyclotronSensitiveTarget::ProcessHits(), BiasingOperator::ProposeFinalStateBiasingOperation(), G4ChannelingOptrChangeCrossSection::ProposeOccurenceBiasingOperation(), G4StackManager::PushOneTrack(), G4LossTableManager::Register(), G4HadronicProcessStore::Register(), G4LossTableManager::RegisterExtraParticle(), G4HadronicProcessStore::RegisterExtraProcess(), G4HadronicProcess::RegisterMe(), G4HadronicProcessStore::RegisterParticle(), G4PhysicsListHelper::RegisterProcess(), G4WrapperProcess::RegisterProcess(), G4ProcessTable::Remove(), G4ParallelGeometriesLimiterProcess::RemoveParallelWorld(), G4ProcessPlacer::RemoveProcess(), G4ProcessManager::RemoveProcess(), G4VEmProcess::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrievePhysicsTable(), G4VEmProcess::SetCrossSectionBiasingFactor(), G4VEnergyLossProcess::SetCrossSectionBiasingFactor(), G4VEnergyLossProcess::SetInverseRangeTable(), G4VEnergyLossProcess::SetLambdaTable(), G4ProcessTableMessenger::SetNewValue(), G4ProcessTable::SetProcessActivation(), G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToFirst(), G4ProcessManager::SetProcessOrderingToLast(), G4ProcessManager::SetProcessOrderingToSecond(), G4VEnergyLossProcess::SetRangeTableForLoss(), G4VEnergyLossProcess::SetSecondaryRangeTable(), G4VEnergyLossProcess::SetSubLambdaTable(), G4FastSimulationManagerProcess::SetWorldVolume(), G4SteppingVerbose::ShowStep(), GB01BOptrChangeCrossSection::StartRun(), G4ChannelingOptrChangeCrossSection::StartRun(), GB05BOptrSplitAndKillByCrossSection::StartRun(), ExN04SteppingVerbose::StepInfo(), SteppingVerbose::StepInfo(), FCALSteppingVerbose::StepInfo(), eRositaSteppingVerbose::StepInfo(), XrayFluoSteppingVerbose::StepInfo(), PurgMagSteppingVerbose::StepInfo(), ExN02SteppingVerbose::StepInfo(), RE05SteppingVerbose::StepInfo(), ExP01SteppingVerbose::StepInfo(), F05SteppingVerbose::StepInfo(), G4SteppingVerbose::StepInfo(), F02SteppingVerbose::StepInfo(), F03SteppingVerbose::StepInfo(), F01SteppingVerbose::StepInfo(), G4VMultipleScattering::StorePhysicsTable(), G4VEmProcess::StorePhysicsTable(), G4VEnergyLossProcess::StorePhysicsTable(), G4VEnergyLossProcess::StreamInfo(), G4VMultipleScattering::StreamInfo(), G4VEmProcess::StreamInfo(), EventAction::SumEnergyTransfered(), G4EmCalculator::UpdateParticle(), EICG4dRICHSteppingAction::UserSteppingAction(), PHG4RICHSteppingAction::UserSteppingAction(), LXeSteppingAction::UserSteppingAction(), F04SteppingAction::UserSteppingAction(), doiPETSteppingAction::UserSteppingAction(), PurgMagSteppingAction::UserSteppingAction(), G4ScoreSplittingProcess::Verbose(), G4ParallelWorldScoringProcess::Verbose(), G4SteppingVerbose::VerboseTrack(), and XrayTelStepCut::XrayTelStepCut().
G4int G4VProcess::GetProcessSubType () const inline
Definition at line 428 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 428 of file G4VProcess.hh
References theProcessSubType.
Referenced by G4GammaGeneralProcess::AddEmProcess(), StepMax::BuildPhysicsTable(), G4DNABrownianTransportation::BuildPhysicsTable(), G4ScreenedNuclearRecoil::BuildPhysicsTable(), G4HadronicProcessStore::FindProcess(), G4BiasingProcessInterface::G4BiasingProcessInterface(), G4HadronicProcessStore::GetCrossSectionPerAtom(), G4HadronicProcessStore::GetCrossSectionPerVolume(), G4GammaGeneralProcess::GetProcessSubType(), G4AnnihiToMuPair::PrintInfoDefinition(), G4GammaConversionToMuons::PrintInfoDefinition(), G4PhysicsListHelper::RegisterProcess(), G4ElectronIonPair::ResidualeChargePostStep(), HistoManager::ScoreNewTrack(), G4EmConfigurator::SetModelForRegion(), G4ChannelingOptrChangeCrossSection::StartRun(), G4VEnergyLossProcess::StreamInfo(), G4VMultipleScattering::StreamInfo(), G4VEmProcess::StreamInfo(), and PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
G4ProcessType G4VProcess::GetProcessType () const inline
Definition at line 416 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 416 of file G4VProcess.hh
References theProcessType.
Referenced by G4BiasingHelper::ActivatePhysicsBiasing(), G4RichTrajectory::CreateAttValues(), G4RichTrajectoryPoint::CreateAttValues(), export_G4VProcess(), G4ProcessTable::Find(), G4AdjointProcessEquivalentToDirectProcess::G4AdjointProcessEquivalentToDirectProcess(), G4PhysicsListHelper::RegisterProcess(), G4WrapperProcess::RegisterProcess(), G4ProcessTableMessenger::SetNewValue(), G4ProcessTable::SetProcessActivation(), G4ChannelingOptrChangeCrossSection::StartRun(), and PHG4ForwardDualReadoutSteppingAction::UserSteppingAction().
const G4String & G4VProcess::GetProcessTypeName (G4ProcessType aType) static
Definition at line 141 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 141 of file G4VProcess.cc
References fDecay, fElectromagnetic, fGeneral, fHadronic, fNotDefined, fOptical, fParameterisation, fPhonon, fPhotolepton_hadron, fTransportation, and fUserDefined.
Referenced by G4RichTrajectory::CreateAttValues(), G4RichTrajectoryPoint::CreateAttValues(), G4ProcessManager::DumpInfo(), DumpInfo(), G4ProcessTableMessenger::G4ProcessTableMessenger(), G4ProcessTableMessenger::GetProcessType(), G4ProcessTableMessenger::GetProcessTypeName(), and G4ProcessTableMessenger::SetNumberOfProcessType().
G4double G4VProcess::GetTotalNumberOfInteractionLengthTraversed () const inline
Definition at line 460 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 460 of file G4VProcess.hh
References theInitialNumberOfInteractionLength, and theNumberOfInteractionLengthLeft.
Referenced by G4HadronicProcess::XBiasSecondaryWeight(), and G4HadronicProcess::XBiasSurvivalProbability().
G4int G4VProcess::GetVerboseLevel () const inline
Definition at line 444 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 444 of file G4VProcess.hh
References verboseLevel.
Referenced by G4MuonMinusAtomicCapture::AtRestDoIt(), G4UnknownDecay::DecayIt(), G4Decay::DecayIt(), G4ProcessTable::DumpInfo(), export_G4VProcess(), G4Decay::G4Decay(), G4UnknownDecay::G4UnknownDecay(), G4Decay::GetMeanFreePath(), G4Decay::GetMeanLifeTime(), and G4DecayWithSpin::Spin_Precession().
G4bool G4VProcess::isAlongStepDoItIsEnabled () const inline
Definition at line 528 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 528 of file G4VProcess.hh
References enableAlongStepDoIt.
Referenced by G4ProcessManager::CheckOrderingParameters().
virtual G4bool G4VProcess::IsApplicable (const G4ParticleDefinition &) inline virtual
Reimplemented in G4ScreenedNuclearRecoil, G4BiasingProcessInterface, G4OpBoundaryProcess, G4Scintillation, G4WrapperProcess, G4UCNBoundaryProcess, G4Cerenkov, G4AdjointProcessEquivalentToDirectProcess, G4SynchrotronRadiationInMat, G4RadioactiveDecay, G4Decay, G4VMultipleScattering, G4VEnergyLossProcess, G4eLowEnergyLoss, G4UCNAbsorption, G4UCNLoss, G4UCNMultiScattering, G4MuIonisation, G4hIonisation, G4eBremsstrahlung, G4PhotoElectricEffect, G4SynchrotronRadiation, G4eIonisation, G4VXTRenergyLoss, G4PolarizedPhotoElectricEffect, G4MuBremsstrahlung, G4VEmProcess, G4hImpactIonisation, G4GammaConversion, G4ionIonisation, G4PolarizedCompton, G4RadioactiveDecayBase, G4ElectronCapture, G4AdjointhMultipleScattering, G4MuPairProduction, G4ComptonScattering, G4LowEnergyBremsstrahlung, G4LowEnergyPolarizedCompton, G4OpWLS, G4ElectronCapture, G4ElectronCapture, G4OpAbsorption, G4OpRayleigh, G4LowEnergyIonisation, G4NeutronKiller, G4GammaGeneralProcess, G4UnknownDecay, G4DNAMolecularDissociation, G4LowECapture, G4ElectronCapture, G4ePolarizedIonisation, G4mplIonisation, G4eplusAnnihilation, G4NuclearStopping, CexmcHadronicProcess, G4eAdjointMultipleScattering, G4PolarizedGammaConversion, G4LowEnergyPhotoElectric, G4hMultipleScattering, G4GammaConversionToMuons, G4HadronStoppingProcess, G4MuonMinusAtomicCapture, G4hBremsstrahlung, G4hhIonisation, G4MuMultipleScattering, G4eMultipleScattering, G4LowEnergyGammaConversion, G4LowEnergyCompton, G4eeToHadrons, G4HadronicAbsorptionFritiofWithBinaryCascade, G4LowEnergyRayleigh, G4hPairProduction, G4MicroElecInelastic, G4MuElecInelastic, G4alphaIonisation, G4TransitionRadiation, G4AnnihiToMuPair, G4ePairProduction, G4VTransitionRadiation, G4MuonicAtomDecay, G4DNAElectronSolvation, G4CoulombScattering, G4MuonMinusCapture, ML2StepMax, G4RayleighScattering, G4HadronFissionProcess, G4AntiNeutronAnnihilationAtRest, G4ChargeExchangeProcess, G4HadronCaptureProcess, G4HadronicAbsorptionFritiof, G4JAEAElasticScattering, G4OpMieHG, IORTStepMax, G4ErrorEnergyLoss, G4MicroElecElastic, G4MuElecElastic, StepMax, StepMax, StepMax, G4LDMBremsstrahlung, G4HadronInelasticProcess, G4DNAIonisation, StepMax, StepMax, StepMaxProcess, StepLimiter, G4DNAExcitation, StepMax, StepMax, StepMax, StepMax, F04StepMax, StepMax, StepMax, StepMax, StepMax, G4DNAChargeDecrease, G4DNAElastic, G4HadronicAbsorptionBertini, XrayFluoStepMax, StepMax, G4DNAAttachment, G4DNAChargeIncrease, G4DNAVibExcitation, StepMax, StepMax, StepMax, StepMax, StepMax, G4MuonNuclearProcess, G4Channeling, HadrontherapyStepMax, G4VPhononProcess, G4DNAElectronHoleRecombination, G4PhononDownconversion, G4DNADissociation, G4DNAPositronium, G4DNARotExcitation, and G4EicDircOpBoundaryProcess.
Definition at line 204 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 204 of file G4VProcess.hh
Referenced by G4ProcessManager::AddProcess(), XPhysicsList::ConstructProcess(), export_G4VProcess(), G4AdjointProcessEquivalentToDirectProcess::IsApplicable(), G4WrapperProcess::IsApplicable(), and G4BiasingProcessInterface::IsApplicable().
G4bool G4VProcess::isAtRestDoItIsEnabled () const inline
Definition at line 522 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 522 of file G4VProcess.hh
References enableAtRestDoIt.
Referenced by G4ProcessManager::CheckOrderingParameters().
G4bool G4VProcess::isPostStepDoItIsEnabled () const inline
Definition at line 534 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 534 of file G4VProcess.hh
References enablePostStepDoIt.
Referenced by G4ProcessManager::CheckOrderingParameters().
G4bool G4VProcess::operator!= (const G4VProcess & right) const
Definition at line 173 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 173 of file G4VProcess.cc
G4VProcess & G4VProcess::operator= (const G4VProcess & right) private
Definition at line 161 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 161 of file G4VProcess.cc
References G4Exception(), and JustWarning.
G4bool G4VProcess::operator== (const G4VProcess & right) const
Definition at line 168 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 168 of file G4VProcess.cc
virtual G4VParticleChange* G4VProcess::PostStepDoIt (const G4Track & track, const G4Step & stepData) pure virtual
Implemented in G4RadioactiveDecay, G4RadioactiveDecayBase, G4ScreenedNuclearRecoil, G4Radioactivation, G4BiasingProcessInterface, G4VMultipleScattering, G4VEnergyLossProcess, G4hImpactIonisation, G4Scintillation, G4OpBoundaryProcess, G4DNABrownianTransportation, G4ParallelGeometriesLimiterProcess, G4ITTransportation, G4ParallelWorldScoringProcess, G4VEmProcess, G4ScoreSplittingProcess, G4Cerenkov, G4FastSimulationManagerProcess, G4eLowEnergyLoss, G4UCNBoundaryProcess, G4ParallelWorldProcess, G4GammaGeneralProcess, G4hRDEnergyLoss, G4VContinuousProcess, G4GammaConversionToMuons, G4VRestContinuousProcess, G4UCNAbsorption, G4UCNLoss, G4UCNMultiScattering, G4AnnihiToMuPair, G4VRestProcess, G4RDVeLowEnergyLoss, G4WeightWindowProcess, G4VITRestProcess, G4HadronicProcess, G4ImportanceProcess, G4WeightCutOffProcess, G4OpWLS, G4MuonicAtomDecay, G4VXTRenergyLoss, G4OpRayleigh, G4MonopoleTransportation, G4Decay, G4SynchrotronRadiationInMat, G4CoupledTransportation, G4ForwardXrayTR, G4OpAbsorption, G4ElectronCapture, G4AdjointForcedInteractionForGamma, G4VAdjointReverseReaction, G4DNAMolecularDissociation, G4WrapperProcess, G4NeutronKiller, G4LowEnergyBremsstrahlung, G4ElectronCapture, G4ElectronCapture, G4Transportation, G4LowEnergyIonisation, G4LowEnergyPolarizedCompton, G4LowECapture, G4ElectronCapture, G4ErrorTrackLengthTarget, G4DNASecondOrderReaction, G4VDiscreteProcess, G4SynchrotronRadiation, XrayTelStepCut, G4VRestContinuousDiscreteProcess, G4AdjointProcessEquivalentToDirectProcess, G4VContinuousDiscreteProcess, G4VRestDiscreteProcess, G4LowEnergyPhotoElectric, G4VErrorLimitProcess, G4VITRestDiscreteProcess, G4LowEnergyGammaConversion, G4TransitionRadiation, G4LowEnergyCompton, G4VTransitionRadiation, CexmcHadronicProcess, G4LowEnergyRayleigh, ML2StepMax, G4OpMieHG, DMXSpecialCuts, G4SpecialCuts, G4UnknownDecay, IORTStepMax, CexmcStudiedProcess, StepMax, G4DNAElectronHoleRecombination, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, G4UserSpecialCuts, StepMax, F04StepMax, StepMaxProcess, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepLimiter, G4MuNeutrinoNucleusProcess, G4NeutrinoElectronProcess, G4StepLimiter, StepMax, StepMax, StepMax, StepMax, G4DecayWithSpin, XrayFluoStepMax, G4HadronElasticProcess, G4VITDiscreteProcess, StepMax, HadrontherapyStepMax, G4Channeling, SplitProcess, G4PhononReflection, G4PhononDownconversion, G4PhononScattering, G4EicDircOpBoundaryProcess, and PrtOpBoundaryProcess.
Referenced by GB04BOptnBremSplitting::ApplyFinalStateBiasing(), G4BOptnLeadingParticle::ApplyFinalStateBiasing(), G4BOptnForceCommonTruncatedExp::ApplyFinalStateBiasing(), G4SteppingManager::InvokePSDIP(), SplitProcess::PostStepDoIt(), CexmcStudiedProcess::PostStepDoIt(), G4AdjointProcessEquivalentToDirectProcess::PostStepDoIt(), G4WrapperProcess::PostStepDoIt(), and G4BiasingProcessInterface::PostStepDoIt().
virtual G4double G4VProcess::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) pure virtual
Implemented in G4BiasingProcessInterface, G4VMultipleScattering, G4VEnergyLossProcess, G4ParallelGeometriesLimiterProcess, G4Decay, G4ParallelWorldScoringProcess, G4ITTransportation, G4ScoreSplittingProcess, G4VEmProcess, G4Cerenkov, G4FastSimulationManagerProcess, G4WrapperProcess, G4ParallelWorldProcess, G4GammaGeneralProcess, G4AdjointProcessEquivalentToDirectProcess, G4PolarizedCompton, G4MonopoleTransportation, G4WeightWindowProcess, G4UnknownDecay, G4VRestContinuousProcess, G4CoupledTransportation, G4VRestProcess, G4VITRestProcess, G4ImportanceProcess, G4Transportation, G4ePolarizedIonisation, G4WeightCutOffProcess, G4VContinuousProcess, G4AdjointForcedInteractionForGamma, G4ElectronCapture, G4NeutronKiller, G4ElectronCapture, G4ElectronCapture, G4HadronStoppingProcess, G4eplusPolarizedAnnihilation, G4MuonicAtomDecay, G4DNAMolecularDissociation, G4LowECapture, G4ElectronCapture, G4DNASecondOrderReaction, G4ErrorTrackLengthTarget, G4VDiscreteProcess, XrayTelStepCut, G4VITRestDiscreteProcess, G4VRestContinuousDiscreteProcess, G4VContinuousDiscreteProcess, G4VRestDiscreteProcess, ML2StepMax, G4VErrorLimitProcess, G4ErrorStepLengthLimitProcess, G4ErrorMagFieldLimitProcess, IORTStepMax, DMXMaxTimeCuts, G4MaxTimeCuts, CexmcStudiedProcess, DMXSpecialCuts, G4SpecialCuts, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, F04StepMax, StepMaxProcess, StepMax, StepMax, StepMax, StepMax, StepMax, StepMax, StepLimiter, StepMax, StepMax, StepMax, G4UserSpecialCuts, DMXMinEkineCuts, StepMax, G4MinEkineCuts, XrayFluoStepMax, G4StepLimiter, G4VITDiscreteProcess, StepMax, and HadrontherapyStepMax.
Referenced by G4BiasingProcessInterface::InvokeWrappedProcessPostStepGPIL(), G4AdjointProcessEquivalentToDirectProcess::PostStepGetPhysicalInteractionLength(), G4WrapperProcess::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), and PostStepGPIL().
G4double G4VProcess::PostStepGPIL (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) inline
Definition at line 500 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 500 of file G4VProcess.hh
References PostStepGetPhysicalInteractionLength(), and thePILfactor.
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength().
virtual void G4VProcess::PreparePhysicsTable (const G4ParticleDefinition &) inline virtual
Reimplemented in G4BiasingProcessInterface, G4WrapperProcess, G4VEnergyLossProcess, G4AdjointProcessEquivalentToDirectProcess, G4VMultipleScattering, G4VEmProcess, G4ContinuousGainOfEnergy, G4HadronicProcess, G4GammaGeneralProcess, G4AdjointAlongStepWeightCorrection, G4VAdjointReverseReaction, G4AdjointForcedInteractionForGamma, G4HadronStoppingProcess, G4MuonMinusAtomicCapture, G4MuNeutrinoNucleusProcess, G4NeutrinoElectronProcess, G4AntiNeutronAnnihilationAtRest, StepMax, StepMax, StepMax, StepMax, and StepMax.
Definition at line 216 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 216 of file G4VProcess.hh
Referenced by export_G4VProcess(), G4GammaGeneralProcess::PreparePhysicsTable(), G4AdjointProcessEquivalentToDirectProcess::PreparePhysicsTable(), G4WrapperProcess::PreparePhysicsTable(), G4BiasingProcessInterface::PreparePhysicsTable(), and PrepareWorkerPhysicsTable().
void G4VProcess::PrepareWorkerPhysicsTable (const G4ParticleDefinition & part) virtual
Reimplemented in G4BiasingProcessInterface.
Definition at line 211 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 211 of file G4VProcess.cc
References PreparePhysicsTable().
Referenced by G4BiasingProcessInterface::PrepareWorkerPhysicsTable().
void G4VProcess::ProcessDescription (std::ostream & outfile) const virtual
Reimplemented in G4Decay, G4Transportation, G4HadronicProcess, G4VMultipleScattering, G4VEnergyLossProcess, G4MuIonisation, G4hIonisation, G4RadioactiveDecay, G4MuBremsstrahlung, G4PhotoElectricEffect, G4eIonisation, G4GammaConversion, G4ionIonisation, G4eBremsstrahlung, G4VEmProcess, G4NuclearStopping, G4MuPairProduction, G4ComptonScattering, G4HadronStoppingProcess, G4eplusAnnihilation, G4GammaGeneralProcess, G4mplIonisation, G4MuonMinusAtomicCapture, G4RadioactiveDecayBase, G4UnknownDecay, G4eeToHadrons, G4hhIonisation, G4MuonicAtomDecay, G4hMultipleScattering, G4ePairProduction, G4hBremsstrahlung, G4MuMultipleScattering, G4alphaIonisation, G4eMultipleScattering, G4hPairProduction, G4MuNeutrinoNucleusProcess, G4NeutrinoElectronProcess, G4HadronicAbsorptionFritiofWithBinaryCascade, G4RayleighScattering, G4CoulombScattering, G4HadronElasticProcess, G4MuonMinusCapture, G4HadronFissionProcess, G4Radioactivation, G4HadronCaptureProcess, G4HadronicAbsorptionFritiof, G4PhotoNuclearProcess, G4PhotoCaptureProcess, G4HadronicAbsorptionBertini, G4DecayWithSpin, G4NeutronInelasticProcess, G4PhotoFissionProcess, G4AntiAlphaInelasticProcess, G4AntiDeuteronInelasticProcess, G4AntiHe3InelasticProcess, G4AntiNeutronInelasticProcess, G4ElectronNuclearProcess, G4IonInelasticProcess, G4MuonNuclearProcess, G4PionMinusInelasticProcess, G4PionDecayMakeSpin, G4AlphaInelasticProcess, G4AntiOmegaMinusInelasticProcess, G4AntiProtonInelasticProcess, G4AntiSigmaMinusInelasticProcess, G4AntiSigmaPlusInelasticProcess, G4AntiTritonInelasticProcess, G4AntiXiMinusInelasticProcess, G4AntiXiZeroInelasticProcess, G4DeuteronInelasticProcess, G4KaonMinusInelasticProcess, G4KaonPlusInelasticProcess, G4KaonZeroLInelasticProcess, G4KaonZeroSInelasticProcess, G4LambdaInelasticProcess, G4OmegaMinusInelasticProcess, G4PionPlusInelasticProcess, G4ProtonInelasticProcess, G4SigmaMinusInelasticProcess, G4SigmaPlusInelasticProcess, G4TritonInelasticProcess, G4XiMinusInelasticProcess, G4XiZeroInelasticProcess, G4AntiLambdaInelasticProcess, G4He3InelasticProcess, G4PositronNuclearProcess, G4AntiBMesonZeroInelasticProcess, G4AntiBsMesonZeroInelasticProcess, G4AntiDMesonZeroInelasticProcess, G4AntiLambdabInelasticProcess, G4AntiLambdacPlusInelasticProcess, G4AntiOmegabMinusInelasticProcess, G4AntiOmegacZeroInelasticProcess, G4AntiXibMinusInelasticProcess, G4AntiXibZeroInelasticProcess, G4AntiXicPlusInelasticProcess, G4AntiXicZeroInelasticProcess, G4BcMesonMinusInelasticProcess, G4BcMesonPlusInelasticProcess, G4BMesonMinusInelasticProcess, G4BMesonPlusInelasticProcess, G4BMesonZeroInelasticProcess, G4BsMesonZeroInelasticProcess, G4DMesonMinusInelasticProcess, G4DMesonPlusInelasticProcess, G4DMesonZeroInelasticProcess, G4DsMesonMinusInelasticProcess, G4DsMesonPlusInelasticProcess, G4LambdabInelasticProcess, G4LambdacPlusInelasticProcess, G4OmegabMinusInelasticProcess, G4OmegacZeroInelasticProcess, G4XibMinusInelasticProcess, G4XibZeroInelasticProcess, G4XicPlusInelasticProcess, and G4XicZeroInelasticProcess.
Definition at line 185 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 185 of file G4VProcess.cc
Referenced by G4LossTableManager::DumpHtml(), G4HadronicProcessStore::PrintHtml(), and G4GammaGeneralProcess::ProcessDescription().
void G4VProcess::ResetNumberOfInteractionLengthLeft () virtual
Reimplemented in G4BiasingProcessInterface, G4WrapperProcess, G4AdjointProcessEquivalentToDirectProcess, and G4VITProcess.
Definition at line 95 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 95 of file G4VProcess.cc
References G4Log(), G4UniformRand, theInitialNumberOfInteractionLength, and theNumberOfInteractionLengthLeft.
Referenced by G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4MuonicAtomDecay::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4BiasingProcessInterface::InvokeWrappedProcessPostStepGPIL(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength(), G4AdjointProcessEquivalentToDirectProcess::ResetNumberOfInteractionLengthLeft(), G4WrapperProcess::ResetNumberOfInteractionLengthLeft(), G4BiasingProcessInterface::ResetNumberOfInteractionLengthLeft(), and G4Decay::StartTracking().
virtual G4bool G4VProcess::RetrievePhysicsTable (const G4ParticleDefinition * , const G4String & , G4bool) inline virtual
Reimplemented in G4BiasingProcessInterface, G4VEnergyLossProcess, G4WrapperProcess, G4AdjointProcessEquivalentToDirectProcess, G4VEmProcess, G4VMultipleScattering, and G4GammaGeneralProcess.
Definition at line 235 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 235 of file G4VProcess.hh
Referenced by export_G4VProcess(), G4AdjointProcessEquivalentToDirectProcess::RetrievePhysicsTable(), G4WrapperProcess::RetrievePhysicsTable(), and G4BiasingProcessInterface::RetrievePhysicsTable().
void G4VProcess::SetMasterProcess (G4VProcess * masterP) virtual
Reimplemented in G4BiasingProcessInterface, and G4WrapperProcess.
Definition at line 216 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 216 of file G4VProcess.cc
References masterProcessShadow.
Referenced by G4WrapperProcess::SetMasterProcess(), and G4BiasingProcessInterface::SetMasterProcess().
void G4VProcess::SetPILfactor (G4double value) inline
Definition at line 469 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 469 of file G4VProcess.hh
References thePILfactor.
Referenced by export_G4VProcess().
void G4VProcess::SetProcessManager (const G4ProcessManager * procMan) inline virtual
Reimplemented in G4BiasingProcessInterface, G4WrapperProcess, and G4ParallelGeometriesLimiterProcess.
Definition at line 510 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 510 of file G4VProcess.hh
References aProcessManager.
Referenced by G4ProcessManager::AddProcess(), G4WrapperProcess::SetProcessManager(), and G4BiasingProcessInterface::SetProcessManager().
void G4VProcess::SetProcessSubType (G4int value) inline
Definition at line 434 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 434 of file G4VProcess.hh
References theProcessSubType.
Referenced by G4DNAElectronHoleRecombination::Create(), G4DNASecondOrderReaction::Create(), G4alphaIonisation::G4alphaIonisation(), G4AnnihiToMuPair::G4AnnihiToMuPair(), G4AntiNeutronAnnihilationAtRest::G4AntiNeutronAnnihilationAtRest(), G4BiasingProcessInterface::G4BiasingProcessInterface(), G4Cerenkov::G4Cerenkov(), G4ComptonScattering::G4ComptonScattering(), G4CoulombScattering::G4CoulombScattering(), G4CoupledTransportation::G4CoupledTransportation(), G4Decay::G4Decay(), G4DecayWithSpin::G4DecayWithSpin(), G4DNAAttachment::G4DNAAttachment(), G4DNABrownianTransportation::G4DNABrownianTransportation(), G4DNAChargeDecrease::G4DNAChargeDecrease(), G4DNAChargeIncrease::G4DNAChargeIncrease(), G4DNAElastic::G4DNAElastic(), G4DNAElectronSolvation::G4DNAElectronSolvation(), G4DNAExcitation::G4DNAExcitation(), G4DNAIonisation::G4DNAIonisation(), G4DNAMolecularDissociation::G4DNAMolecularDissociation(), G4DNAVibExcitation::G4DNAVibExcitation(), G4eBremsstrahlung::G4eBremsstrahlung(), G4eeToHadrons::G4eeToHadrons(), G4eIonisation::G4eIonisation(), G4ePairProduction::G4ePairProduction(), G4eplusAnnihilation::G4eplusAnnihilation(), G4ePolarizedIonisation::G4ePolarizedIonisation(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), G4GammaConversion::G4GammaConversion(), G4GammaConversionToMuons::G4GammaConversionToMuons(), G4GammaGeneralProcess::G4GammaGeneralProcess(), G4HadronicProcess::G4HadronicProcess(), G4hhIonisation::G4hhIonisation(), G4hIonisation::G4hIonisation(), G4ionIonisation::G4ionIonisation(), G4ITTransportation::G4ITTransportation(), G4JAEAElasticScattering::G4JAEAElasticScattering(), G4MicroElecElastic::G4MicroElecElastic(), G4MicroElecInelastic::G4MicroElecInelastic(), G4MonopoleTransportation::G4MonopoleTransportation(), G4mplIonisation::G4mplIonisation(), G4MuBremsstrahlung::G4MuBremsstrahlung(), G4MuElecElastic::G4MuElecElastic(), G4MuElecInelastic::G4MuElecInelastic(), G4MuIonisation::G4MuIonisation(), G4MuonMinusAtomicCapture::G4MuonMinusAtomicCapture(), G4MuPairProduction::G4MuPairProduction(), G4NeutronKiller::G4NeutronKiller(), G4NuclearStopping::G4NuclearStopping(), G4OpAbsorption::G4OpAbsorption(), G4OpBoundaryProcess::G4OpBoundaryProcess(), G4OpMieHG::G4OpMieHG(), G4OpRayleigh::G4OpRayleigh(), G4OpWLS::G4OpWLS(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4PhotoElectricEffect::G4PhotoElectricEffect(), G4PionDecayMakeSpin::G4PionDecayMakeSpin(), G4PolarizedCompton::G4PolarizedCompton(), G4PolarizedGammaConversion::G4PolarizedGammaConversion(), G4PolarizedPhotoElectricEffect::G4PolarizedPhotoElectricEffect(), G4RadioactiveDecay::G4RadioactiveDecay(), G4RadioactiveDecayBase::G4RadioactiveDecayBase(), G4RayleighScattering::G4RayleighScattering(), G4Scintillation::G4Scintillation(), G4ScreenedNuclearRecoil::G4ScreenedNuclearRecoil(), G4StepLimiter::G4StepLimiter(), G4SynchrotronRadiation::G4SynchrotronRadiation(), G4SynchrotronRadiationInMat::G4SynchrotronRadiationInMat(), G4TransitionRadiation::G4TransitionRadiation(), G4Transportation::G4Transportation(), G4UCNAbsorption::G4UCNAbsorption(), G4UCNBoundaryProcess::G4UCNBoundaryProcess(), G4UCNLoss::G4UCNLoss(), G4UCNMultiScattering::G4UCNMultiScattering(), G4UnknownDecay::G4UnknownDecay(), G4UserSpecialCuts::G4UserSpecialCuts(), G4VMultipleScattering::G4VMultipleScattering(), G4VTransitionRadiation::G4VTransitionRadiation(), G4VXTRenergyLoss::G4VXTRenergyLoss(), G4Decay::SetExtDecayer(), and StepMax::StepMax().
void G4VProcess::SetProcessType (G4ProcessType aType) inline
Definition at line 422 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 422 of file G4VProcess.hh
References theProcessType.
Referenced by DMXMaxTimeCuts::DMXMaxTimeCuts(), DMXMinEkineCuts::DMXMinEkineCuts(), G4MaxTimeCuts::G4MaxTimeCuts(), and G4MinEkineCuts::G4MinEkineCuts().
void G4VProcess::SetVerboseLevel (G4int value) inline
Definition at line 439 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 439 of file G4VProcess.hh
References verboseLevel.
Referenced by DMXPhysicsList::ConstructOp(), LBE::ConstructOp(), XPhysicsList::ConstructProcess(), G4EmDNAChemistry::ConstructProcess(), G4EmDNAChemistry_option1::ConstructProcess(), G4EmDNAChemistry_option2::ConstructProcess(), TransitionRadiationPhysics::ConstructProcess(), ExUCNExtraPhysics::ConstructUCN(), G4ProcessTable::DumpInfo(), export_G4VProcess(), G4CoupledTransportation::G4CoupledTransportation(), G4GammaGeneralProcess::G4GammaGeneralProcess(), G4hhIonisation::G4hhIonisation(), G4mplIonisation::G4mplIonisation(), G4Transportation::G4Transportation(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMultipleScattering::G4VMultipleScattering(), G4CoulombScattering::InitialiseProcess(), G4GammaGeneralProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4OpticalPhysics::SetAbsorptionVerbosity(), G4OpticalPhysics::SetBoundaryVerbosity(), G4OpticalPhysics::SetCerenkovVerbosity(), G4OpticalPhysics::SetMieVerbosity(), G4ProcessTableMessenger::SetNewValue(), G4ProcessManagerMessenger::SetNewValue(), G4OpticalPhysics::SetRayleighVerbosity(), G4OpticalPhysics::SetScintillationVerbosity(), and G4OpticalPhysics::SetWLSVerbosity().
void G4VProcess::StartTracking (G4Track *) virtual
Reimplemented in G4WrapperProcess, G4BiasingProcessInterface, G4CoupledTransportation, G4AdjointProcessEquivalentToDirectProcess, G4Transportation, G4Decay, G4VMultipleScattering, G4MonopoleTransportation, G4VEnergyLossProcess, G4VITProcess, G4ParallelGeometriesLimiterProcess, G4DNABrownianTransportation, G4VEmProcess, G4FastSimulationManagerProcess, G4GammaGeneralProcess, G4ITTransportation, G4ParallelWorldProcess, G4ParallelWorldScoringProcess, G4WeightWindowProcess, G4ScoreSplittingProcess, G4ImportanceProcess, G4WeightCutOffProcess, G4eAdjointMultipleScattering, G4DNASecondOrderReaction, G4VPhononProcess, and G4DNAElectronHoleRecombination.
Definition at line 101 of file G4VProcess.cc.
View newest version in sPHENIX GitHub at line 101 of file G4VProcess.cc
References currentInteractionLength, G4cout, G4endl, theInitialNumberOfInteractionLength, theNumberOfInteractionLengthLeft, theProcessName, and verboseLevel.
Referenced by G4DNAElectronHoleRecombination::StartTracking(), G4VPhononProcess::StartTracking(), G4DNASecondOrderReaction::StartTracking(), G4ITTransportation::StartTracking(), G4MonopoleTransportation::StartTracking(), G4Transportation::StartTracking(), G4AdjointProcessEquivalentToDirectProcess::StartTracking(), G4BiasingProcessInterface::StartTracking(), and G4WrapperProcess::StartTracking().
virtual G4bool G4VProcess::StorePhysicsTable (const G4ParticleDefinition * , const G4String & , G4bool) inline virtual
Reimplemented in G4BiasingProcessInterface, G4VEnergyLossProcess, G4WrapperProcess, G4AdjointProcessEquivalentToDirectProcess, G4VEmProcess, G4VMultipleScattering, and G4GammaGeneralProcess.
Definition at line 230 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 230 of file G4VProcess.hh
Referenced by export_G4VProcess(), G4AdjointProcessEquivalentToDirectProcess::StorePhysicsTable(), G4WrapperProcess::StorePhysicsTable(), and G4BiasingProcessInterface::StorePhysicsTable().
void G4VProcess::SubtractNumberOfInteractionLengthLeft (G4double previousStepSize) inline protected
Definition at line 546 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 546 of file G4VProcess.hh
References currentInteractionLength, EventMustBeAborted, G4cerr, G4endl, G4Exception(), CLHEP::perMillion, theNumberOfInteractionLengthLeft, theProcessName, and verboseLevel.
Referenced by G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), and G4Decay::PostStepGetPhysicalInteractionLength().
Member Data Documentation
G4ParticleChange G4VProcess::aParticleChange protected
Definition at line 288 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 288 of file G4VProcess.hh
Referenced by G4ErrorEnergyLoss::AlongStepDoIt(), G4ContinuousGainOfEnergy::AlongStepDoIt(), G4eLowEnergyLoss::AlongStepDoIt(), G4hImpactIonisation::AlongStepDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4DNAMolecularDissociation::DecayIt(), G4OpBoundaryProcess::DoAbsorption(), G4DNAMolecularDissociation::G4DNAMolecularDissociation(), G4VProcess(), G4PhononDownconversion::MakeLTSecondaries(), G4PhononDownconversion::MakeTTSecondaries(), G4PhononDownconversion::PostStepDoIt(), G4PhononScattering::PostStepDoIt(), G4PhononReflection::PostStepDoIt(), G4Channeling::PostStepDoIt(), HadrontherapyStepMax::PostStepDoIt(), XrayFluoStepMax::PostStepDoIt(), StepLimiter::PostStepDoIt(), G4StepLimiter::PostStepDoIt(), StepMax::PostStepDoIt(), StepMaxProcess::PostStepDoIt(), F04StepMax::PostStepDoIt(), G4UserSpecialCuts::PostStepDoIt(), IORTStepMax::PostStepDoIt(), G4SpecialCuts::PostStepDoIt(), DMXSpecialCuts::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), ML2StepMax::PostStepDoIt(), G4LowEnergyRayleigh::PostStepDoIt(), G4LowEnergyCompton::PostStepDoIt(), G4TransitionRadiation::PostStepDoIt(), G4LowEnergyGammaConversion::PostStepDoIt(), G4LowEnergyPhotoElectric::PostStepDoIt(), XrayTelStepCut::PostStepDoIt(), G4SynchrotronRadiation::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4LowEnergyIonisation::PostStepDoIt(), G4LowEnergyBremsstrahlung::PostStepDoIt(), G4ForwardXrayTR::PostStepDoIt(), G4OpAbsorption::PostStepDoIt(), G4SynchrotronRadiationInMat::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4AnnihiToMuPair::PostStepDoIt(), G4UCNLoss::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4GammaConversionToMuons::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), and G4hImpactIonisation::PostStepDoIt().
const G4ProcessManager* G4VProcess::aProcessManager protected
Definition at line 279 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 279 of file G4VProcess.hh
Referenced by GetProcessManager(), and SetProcessManager().
G4double G4VProcess::currentInteractionLength protected
Definition at line 296 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 296 of file G4VProcess.hh
Referenced by G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4Decay::EndTracking(), EndTracking(), GetCurrentInteractionLength(), G4ScreenedNuclearRecoil::GetCurrentInteractionLength(), G4VEnergyLossProcess::PostStepDoIt(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4eplusPolarizedAnnihilation::PostStepGetPhysicalInteractionLength(), G4ePolarizedIonisation::PostStepGetPhysicalInteractionLength(), G4PolarizedCompton::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::StartTracking(), G4Decay::StartTracking(), StartTracking(), and SubtractNumberOfInteractionLengthLeft().
G4bool G4VProcess::enableAlongStepDoIt protected
Definition at line 350 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 350 of file G4VProcess.hh
Referenced by G4DNAElectronHoleRecombination::Create(), G4DNASecondOrderReaction::Create(), G4DNAMolecularDissociation::G4DNAMolecularDissociation(), G4ITTransportation::G4ITTransportation(), G4NuclearStopping::G4NuclearStopping(), G4VDiscreteProcess::G4VDiscreteProcess(), G4VITDiscreteProcess::G4VITDiscreteProcess(), G4VITRestDiscreteProcess::G4VITRestDiscreteProcess(), G4VITRestProcess::G4VITRestProcess(), G4VRestDiscreteProcess::G4VRestDiscreteProcess(), G4VRestProcess::G4VRestProcess(), and isAlongStepDoItIsEnabled().
G4bool G4VProcess::enableAtRestDoIt protected
Definition at line 349 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 349 of file G4VProcess.hh
Referenced by G4DNAElectronHoleRecombination::Create(), G4DNASecondOrderReaction::Create(), G4DNAMolecularDissociation::G4DNAMolecularDissociation(), G4eplusAnnihilation::G4eplusAnnihilation(), G4HadronStoppingProcess::G4HadronStoppingProcess(), G4ITTransportation::G4ITTransportation(), G4MuonicAtomDecay::G4MuonicAtomDecay(), G4VContinuousDiscreteProcess::G4VContinuousDiscreteProcess(), G4VContinuousProcess::G4VContinuousProcess(), G4VDiscreteProcess::G4VDiscreteProcess(), G4VITDiscreteProcess::G4VITDiscreteProcess(), and isAtRestDoItIsEnabled().
G4bool G4VProcess::enablePostStepDoIt protected
Definition at line 351 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 351 of file G4VProcess.hh
Referenced by G4DNAElectronHoleRecombination::Create(), G4DNASecondOrderReaction::Create(), G4DNAMolecularDissociation::G4DNAMolecularDissociation(), G4HadronStoppingProcess::G4HadronStoppingProcess(), G4ITTransportation::G4ITTransportation(), G4MuonicAtomDecay::G4MuonicAtomDecay(), G4NuclearStopping::G4NuclearStopping(), G4VContinuousProcess::G4VContinuousProcess(), G4VITRestProcess::G4VITRestProcess(), G4VRestContinuousProcess::G4VRestContinuousProcess(), G4VRestProcess::G4VRestProcess(), and isPostStepDoItIsEnabled().
G4VProcess* G4VProcess::masterProcessShadow private
Definition at line 374 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 374 of file G4VProcess.hh
Referenced by GetMasterProcess(), and SetMasterProcess().
G4VParticleChange* G4VProcess::pParticleChange protected
Definition at line 282 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 282 of file G4VProcess.hh
Referenced by G4VMultipleScattering::AddEmModel(), G4VEmProcess::AddEmModel(), G4VEnergyLossProcess::AddEmModel(), G4VContinuousProcess::AlongStepDoIt(), G4VContinuousDiscreteProcess::AlongStepDoIt(), G4VRestContinuousDiscreteProcess::AlongStepDoIt(), G4VRestContinuousProcess::AlongStepDoIt(), G4ParallelWorldProcess::AlongStepDoIt(), G4WeightCutOffProcess::AlongStepDoIt(), G4ImportanceProcess::AlongStepDoIt(), G4ParallelWorldScoringProcess::AlongStepDoIt(), G4WeightWindowProcess::AlongStepDoIt(), G4VRestContinuousProcess::AtRestDoIt(), G4eplusAnnihilation::AtRestDoIt(), G4VITRestProcess::AtRestDoIt(), G4VITRestDiscreteProcess::AtRestDoIt(), G4VRestProcess::AtRestDoIt(), G4VRestDiscreteProcess::AtRestDoIt(), G4VRestContinuousDiscreteProcess::AtRestDoIt(), G4ParallelWorldProcess::AtRestDoIt(), G4ScoreSplittingProcess::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4DNAElectronHoleRecombination::Create(), G4DNASecondOrderReaction::Create(), G4VEnergyLossProcess::FillSecondariesAlongStep(), G4Decay::G4Decay(), G4DNAMolecularDissociation::G4DNAMolecularDissociation(), G4ElectronCapture::G4ElectronCapture(), G4ImportanceProcess::G4ImportanceProcess(), G4ITTransportation::G4ITTransportation(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4RadioactiveDecay::G4RadioactiveDecay(), G4RadioactiveDecayBase::G4RadioactiveDecayBase(), G4ScoreSplittingProcess::G4ScoreSplittingProcess(), G4Transportation::G4Transportation(), G4UnknownDecay::G4UnknownDecay(), G4VEmProcess::G4VEmProcess(), G4VEnergyLossProcess::G4VEnergyLossProcess(), G4VMultipleScattering::G4VMultipleScattering(), G4VProcess(), G4VXTRenergyLoss::G4VXTRenergyLoss(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), G4EicDircOpBoundaryProcess::PostStepDoIt(), G4VITDiscreteProcess::PostStepDoIt(), G4VTransitionRadiation::PostStepDoIt(), G4VITRestDiscreteProcess::PostStepDoIt(), G4VRestDiscreteProcess::PostStepDoIt(), G4VContinuousDiscreteProcess::PostStepDoIt(), G4VRestContinuousDiscreteProcess::PostStepDoIt(), G4VDiscreteProcess::PostStepDoIt(), G4ElectronCapture::PostStepDoIt(), G4LowECapture::PostStepDoIt(), G4NeutronKiller::PostStepDoIt(), G4ParallelWorldProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), and G4ScreenedNuclearRecoil::PostStepDoIt().
G4double G4VProcess::theInitialNumberOfInteractionLength protected
Definition at line 299 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 299 of file G4VProcess.hh
Referenced by ClearNumberOfInteractionLengthLeft(), EndTracking(), GetTotalNumberOfInteractionLengthTraversed(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), ResetNumberOfInteractionLengthLeft(), and StartTracking().
G4double G4VProcess::theNumberOfInteractionLengthLeft protected
Definition at line 292 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 292 of file G4VProcess.hh
Referenced by G4AdjointForcedInteractionForGamma::AlongStepDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4MuonicAtomDecay::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4Decay::AtRestGetPhysicalInteractionLength(), ClearNumberOfInteractionLengthLeft(), G4MuonicAtomDecay::DecayIt(), EndTracking(), GetNumberOfInteractionLengthLeft(), GetTotalNumberOfInteractionLengthTraversed(), G4GammaGeneralProcess::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4VEnergyLossProcess::PostStepDoIt(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4eplusPolarizedAnnihilation::PostStepGetPhysicalInteractionLength(), G4AdjointForcedInteractionForGamma::PostStepGetPhysicalInteractionLength(), G4ePolarizedIonisation::PostStepGetPhysicalInteractionLength(), G4PolarizedCompton::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PostStepGetPhysicalInteractionLength(), G4VEmProcess::PostStepGetPhysicalInteractionLength(), G4Decay::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), ResetNumberOfInteractionLengthLeft(), G4GammaGeneralProcess::StartTracking(), G4VEmProcess::StartTracking(), G4VEnergyLossProcess::StartTracking(), StartTracking(), and SubtractNumberOfInteractionLengthLeft().
G4String G4VProcess::thePhysicsTableFileName protected
Definition at line 337 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 337 of file G4VProcess.hh
Referenced by GetPhysicsTableFileName().
G4double G4VProcess::thePILfactor protected
Definition at line 345 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 345 of file G4VProcess.hh
Referenced by AtRestGPIL(), GetPILfactor(), PostStepGPIL(), and SetPILfactor().
G4String G4VProcess::theProcessName protected
Definition at line 334 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 334 of file G4VProcess.hh
Referenced by DumpInfo(), EndTracking(), G4WeightCutOffProcess::GetName(), G4ImportanceProcess::GetName(), GetPhysicsTableFileName(), GetProcessName(), G4WrapperProcess::RegisterProcess(), StartTracking(), G4VITProcess::SubtractNumberOfInteractionLengthLeft(), and SubtractNumberOfInteractionLengthLeft().
G4int G4VProcess::theProcessSubType protected
Definition at line 342 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 342 of file G4VProcess.hh
Referenced by DumpInfo(), G4MuonicAtomDecay::G4MuonicAtomDecay(), GetProcessSubType(), and SetProcessSubType().
G4ProcessType G4VProcess::theProcessType protected
Definition at line 339 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 339 of file G4VProcess.hh
Referenced by DumpInfo(), G4AdjointProcessEquivalentToDirectProcess::G4AdjointProcessEquivalentToDirectProcess(), GetProcessType(), G4WrapperProcess::RegisterProcess(), and SetProcessType().
G4int G4VProcess::verboseLevel protected
Definition at line 370 of file G4VProcess.hh.
View newest version in sPHENIX GitHub at line 370 of file G4VProcess.hh
Referenced by G4VEmProcess::ActivateForcedInteraction(), G4VEnergyLossProcess::ActivateForcedInteraction(), G4VEmProcess::ActivateSecondaryBiasing(), G4VEnergyLossProcess::ActivateSecondaryBiasing(), G4VEnergyLossProcess::AddCollaborativeProcess(), G4LowECapture::AddRegion(), G4Transportation::AlongStepDoIt(), G4CoupledTransportation::AlongStepDoIt(), G4MonopoleTransportation::AlongStepDoIt(), G4Transportation::AlongStepGetPhysicalInteractionLength(), G4VContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4CoupledTransportation::AlongStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AlongStepGetPhysicalInteractionLength(), G4VRestContinuousProcess::AlongStepGetPhysicalInteractionLength(), G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength(), G4hImpactIonisation::AntiProtonParametrisedDEDX(), G4AntiNeutronAnnihilationAtRest::AtRestDoIt(), G4ParallelWorldScoringProcess::AtRestDoIt(), G4AntiNeutronAnnihilationAtRest::AtRestGetPhysicalInteractionLength(), G4VRestContinuousProcess::AtRestGetPhysicalInteractionLength(), G4VRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestProcess::AtRestGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::AtRestGetPhysicalInteractionLength(), G4VXTRenergyLoss::BuildAngleForEnergyBank(), G4VXTRenergyLoss::BuildAngleTable(), G4eLowEnergyLoss::BuildDEDXTable(), G4VEnergyLossProcess::BuildDEDXTable(), G4VXTRenergyLoss::BuildEnergyTable(), G4VXTRenergyLoss::BuildGlobalAngleTable(), G4VEnergyLossProcess::BuildLambdaTable(), G4hImpactIonisation::BuildLambdaTable(), G4VEmProcess::BuildLambdaTable(), G4LowEnergyBremsstrahlung::BuildLossTable(), G4LowEnergyIonisation::BuildLossTable(), G4hImpactIonisation::BuildLossTable(), G4ChargeExchangeProcess::BuildPhysicsTable(), G4ElectronCapture::BuildPhysicsTable(), G4LowECapture::BuildPhysicsTable(), G4LowEnergyIonisation::BuildPhysicsTable(), G4LowEnergyBremsstrahlung::BuildPhysicsTable(), G4hImpactIonisation::BuildPhysicsTable(), G4SynchrotronRadiation::BuildPhysicsTable(), G4GammaGeneralProcess::BuildPhysicsTable(), G4VXTRenergyLoss::BuildPhysicsTable(), G4VEmProcess::BuildPhysicsTable(), G4DNABrownianTransportation::BuildPhysicsTable(), G4VMultipleScattering::BuildPhysicsTable(), G4VEnergyLossProcess::BuildPhysicsTable(), G4OpRayleigh::CalculateRayleighMeanFreePaths(), G4eplusPolarizedAnnihilation::ComputeSaturationFactor(), G4ePolarizedIonisation::ComputeSaturationFactor(), G4PolarizedCompton::ComputeSaturationFactor(), G4DNAElectronHoleRecombination::Create(), G4DNASecondOrderReaction::Create(), G4VPhononProcess::CreateSecondary(), DMXMaxTimeCuts::DMXMaxTimeCuts(), DMXMinEkineCuts::DMXMinEkineCuts(), DMXSpecialCuts::DMXSpecialCuts(), EndTracking(), F04StepMax::F04StepMax(), G4VEmProcess::FindLambdaMax(), G4AntiNeutronAnnihilationAtRest::G4AntiNeutronAnnihilationAtRest(), G4Cerenkov::G4Cerenkov(), G4ChargeExchangeProcess::G4ChargeExchangeProcess(), G4CoupledTransportation::G4CoupledTransportation(), G4DNAMolecularDissociation::G4DNAMolecularDissociation(), G4ePolarizedIonisation::G4ePolarizedIonisation(), G4ErrorEnergyLoss::G4ErrorEnergyLoss(), G4FastSimulationManagerProcess::G4FastSimulationManagerProcess(), G4ImportanceProcess::G4ImportanceProcess(), G4LowEnergyBremsstrahlung::G4LowEnergyBremsstrahlung(), G4LowEnergyCompton::G4LowEnergyCompton(), G4LowEnergyGammaConversion::G4LowEnergyGammaConversion(), G4LowEnergyIonisation::G4LowEnergyIonisation(), G4LowEnergyPhotoElectric::G4LowEnergyPhotoElectric(), G4LowEnergyPolarizedCompton::G4LowEnergyPolarizedCompton(), G4LowEnergyRayleigh::G4LowEnergyRayleigh(), G4MaxTimeCuts::G4MaxTimeCuts(), G4MinEkineCuts::G4MinEkineCuts(), G4MonopoleTransportation::G4MonopoleTransportation(), G4OpAbsorption::G4OpAbsorption(), G4OpBoundaryProcess::G4OpBoundaryProcess(), G4OpMieHG::G4OpMieHG(), G4OpRayleigh::G4OpRayleigh(), G4OpWLS::G4OpWLS(), G4ParallelWorldProcess::G4ParallelWorldProcess(), G4ParallelWorldScoringProcess::G4ParallelWorldScoringProcess(), G4Scintillation::G4Scintillation(), G4ScoreSplittingProcess::G4ScoreSplittingProcess(), G4SpecialCuts::G4SpecialCuts(), G4StepLimiter::G4StepLimiter(), G4StrawTubeXTRadiator::G4StrawTubeXTRadiator(), G4SynchrotronRadiation::G4SynchrotronRadiation(), G4TransparentRegXTRadiator::G4TransparentRegXTRadiator(), G4Transportation::G4Transportation(), G4UCNAbsorption::G4UCNAbsorption(), G4UCNBoundaryProcess::G4UCNBoundaryProcess(), G4UCNLoss::G4UCNLoss(), G4UCNMultiScattering::G4UCNMultiScattering(), G4UserSpecialCuts::G4UserSpecialCuts(), G4VXTRenergyLoss::G4VXTRenergyLoss(), G4WeightCutOffProcess::G4WeightCutOffProcess(), G4WeightWindowProcess::G4WeightWindowProcess(), G4VXTRenergyLoss::GetAngleVector(), G4Cerenkov::GetAverageNumberOfPhotons(), G4ChargeExchangeProcess::GetElementCrossSection(), G4VXTRenergyLoss::GetGasZmuProduct(), G4PhononScattering::GetMeanFreePath(), G4PhononDownconversion::GetMeanFreePath(), G4SynchrotronRadiation::GetMeanFreePath(), G4eplusPolarizedAnnihilation::GetMeanFreePath(), G4VXTRenergyLoss::GetMeanFreePath(), G4ePolarizedIonisation::GetMeanFreePath(), G4PolarizedCompton::GetMeanFreePath(), G4UCNAbsorption::GetMeanFreePath(), G4ScreenedNuclearRecoil::GetNewCrossSectionHandler(), G4VXTRenergyLoss::GetNumberOfPhotons(), G4VXTRenergyLoss::GetPlateZmuProduct(), G4SynchrotronRadiation::GetRandomEnergySR(), GetVerboseLevel(), G4ScreenedNuclearRecoil::GetVerboseLevel(), G4hhIonisation::InitialiseEnergyLossProcess(), G4eeToHadrons::InitialiseProcess(), G4hImpactIonisation::InitializeMe(), G4UCNBoundaryProcess::MRreflect(), G4UCNBoundaryProcess::MRreflectHigh(), G4HadronElasticProcess::PostStepDoIt(), G4NeutrinoElectronProcess::PostStepDoIt(), G4MuNeutrinoNucleusProcess::PostStepDoIt(), G4OpMieHG::PostStepDoIt(), G4DNASecondOrderReaction::PostStepDoIt(), G4LowEnergyPolarizedCompton::PostStepDoIt(), G4OpAbsorption::PostStepDoIt(), G4CoupledTransportation::PostStepDoIt(), G4OpRayleigh::PostStepDoIt(), G4VXTRenergyLoss::PostStepDoIt(), G4OpWLS::PostStepDoIt(), G4UCNAbsorption::PostStepDoIt(), G4UCNLoss::PostStepDoIt(), G4UCNMultiScattering::PostStepDoIt(), G4UCNBoundaryProcess::PostStepDoIt(), G4Cerenkov::PostStepDoIt(), G4VEmProcess::PostStepDoIt(), G4ScoreSplittingProcess::PostStepDoIt(), G4ParallelWorldScoringProcess::PostStepDoIt(), G4OpBoundaryProcess::PostStepDoIt(), G4Scintillation::PostStepDoIt(), G4VITDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VRestContinuousDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VITRestDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4VDiscreteProcess::PostStepGetPhysicalInteractionLength(), G4DNASecondOrderReaction::PostStepGetPhysicalInteractionLength(), G4eplusPolarizedAnnihilation::PostStepGetPhysicalInteractionLength(), G4ePolarizedIonisation::PostStepGetPhysicalInteractionLength(), G4PolarizedCompton::PostStepGetPhysicalInteractionLength(), G4VEnergyLossProcess::PostStepGetPhysicalInteractionLength(), G4GammaGeneralProcess::PreparePhysicsTable(), G4VEmProcess::PreparePhysicsTable(), G4VMultipleScattering::PreparePhysicsTable(), G4VEnergyLossProcess::PreparePhysicsTable(), G4hImpactIonisation::ProtonParametrisedDEDX(), G4UCNBoundaryProcess::Reflect(), G4CoupledTransportation::ReportInexactEnergy(), G4CoupledTransportation::ReportMissingLogger(), G4GammaGeneralProcess::RetrievePhysicsTable(), G4VEmProcess::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrievePhysicsTable(), G4VEnergyLossProcess::RetrieveTable(), G4VEmProcess::SetCrossSectionBiasingFactor(), G4VEnergyLossProcess::SetCrossSectionBiasingFactor(), G4CoupledTransportation::SetHighLooperThresholds(), G4Transportation::SetHighLooperThresholds(), G4VEnergyLossProcess::SetInverseRangeTable(), G4LowECapture::SetKinEnergyLimit(), G4ElectronCapture::SetKinEnergyLimit(), G4NeutronKiller::SetKinEnergyLimit(), G4VEnergyLossProcess::SetLambdaTable(), G4CoupledTransportation::SetLowLooperThresholds(), G4Transportation::SetLowLooperThresholds(), G4VEnergyLossProcess::SetRangeTableForLoss(), G4VEnergyLossProcess::SetSecondaryRangeTable(), G4VEnergyLossProcess::SetSubLambdaTable(), G4NeutronKiller::SetTimeLimit(), SetVerboseLevel(), G4FastSimulationManagerProcess::SetWorldVolume(), G4XTRRegularRadModel::SpectralXTRdEdx(), G4RegularXTRadiator::SpectralXTRdEdx(), G4TransparentRegXTRadiator::SpectralXTRdEdx(), G4CoupledTransportation::StartTracking(), StartTracking(), G4VMultipleScattering::StorePhysicsTable(), G4VEnergyLossProcess::StorePhysicsTable(), G4VEnergyLossProcess::StreamInfo(), G4VMultipleScattering::StreamInfo(), G4VEmProcess::StreamInfo(), G4VITProcess::SubtractNumberOfInteractionLengthLeft(), SubtractNumberOfInteractionLengthLeft(), XrayTelStepCut::XrayTelStepCut(), and G4MonopoleTransportation::~G4MonopoleTransportation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/management/include/G4VProcess.hh
geant4/tree/geant4-10.6-release/source/processes/management/src/G4VProcess.cc