ECCE @ EIC Software: G4ITTransportation Class Reference
G4ITTransportation Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTransportation.hh>
Classes
struct G4ITTransportationState
Public Member Functions
G4ITTransportation (const G4String &aName="ITTransportation", G4int verbosityLevel=0)
virtual ~G4ITTransportation ()
G4ITTransportation (const G4ITTransportation &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void ComputeStep (const G4Track &, const G4Step &, const double timeStep, double &spaceStep)
virtual void StartTracking (G4Track *aTrack)
G4bool IsStepLimitedByGeometry ()
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double, G4double currentMinimumStep, G4double &currentSafety, G4GPILSelection *selection)
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double, G4ForceCondition *pForceCond)
virtual G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &stepData)
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &)
G4PropagatorInField * GetPropagatorInField ()
void SetPropagatorInField (G4PropagatorInField *pFieldPropagator)
void SetVerboseLevel (G4int verboseLevel)
G4int GetVerboseLevel () const
G4double GetThresholdWarningEnergy () const
G4double GetThresholdImportantEnergy () const
G4int GetThresholdTrials () const
void SetThresholdWarningEnergy (G4double newEnWarn)
void SetThresholdImportantEnergy (G4double newEnImp)
void SetThresholdTrials (G4int newMaxTrials)
G4double GetMaxEnergyKilled () const
G4double GetSumEnergyKilled () const
void ResetKilledStatistics (G4int report=1)
void EnableShortStepOptimisation (G4bool optimise=true)
Public Member Functions inherited from G4VITProcess
G4VITProcess (const G4String &name, G4ProcessType type=fNotDefined)
virtual ~G4VITProcess ()
G4VITProcess (const G4VITProcess &other)
G4VITProcess & operator= (const G4VITProcess &other)
G4bool operator== (const G4VITProcess &right) const
G4bool operator!= (const G4VITProcess &right) const
size_t GetProcessID () const
G4shared_ptr< G4ProcessState_Lock > GetProcessState ()
void SetProcessState (G4shared_ptr< G4ProcessState_Lock > aProcInfo)
void ResetProcessState ()
G4double GetInteractionTimeLeft ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4bool ProposesTimeStep () const
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual void EndTracking ()
virtual void SetProcessManager (const G4ProcessManager *)
virtual const G4ProcessManager * GetProcessManager ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Protected Member Functions
G4bool DoesGlobalFieldExist ()
void SetInstantiateProcessState (G4bool flag)
G4bool InstantiateProcessState ()
Protected Member Functions inherited from G4VITProcess
void RetrieveProcessInfo ()
void CreateInfo ()
template<typename T >
T * GetState ()
virtual void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
virtual void ClearInteractionTimeLeft ()
virtual void ClearNumberOfInteractionLengthLeft ()
void SetInstantiateProcessState (G4bool flag)
G4bool InstantiateProcessState ()
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes
G4ITNavigator * fLinearNavigator
G4PropagatorInField * fFieldPropagator
G4ParticleChangeForTransport fParticleChange
G4double fThreshold_Warning_Energy
G4double fThreshold_Important_Energy
G4int fThresholdTrials
G4double fUnimportant_Energy
G4double fSumEnergyKilled
G4double fMaxEnergyKilled
G4bool fShortStepOptimisation
G4ITSafetyHelper * fpSafetyHelper
G4int fVerboseLevel
Protected Attributes inherited from G4VITProcess
G4shared_ptr< G4ProcessState > fpState
G4bool fProposesTimeStep
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Private Member Functions
G4ITTransportation & operator= (const G4ITTransportation &)
Private Attributes
G4bool fInstantiateProcessState
Additional Inherited Members
Static Public Member Functions inherited from G4VITProcess
static const size_t & GetMaxProcessIndex ()
Detailed Description
Definition at line 73 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 73 of file G4ITTransportation.hh
Constructor & Destructor Documentation
G4ITTransportation::G4ITTransportation (const G4String & aName = "ITTransportation", G4int verbosityLevel = 0)
Definition at line 95 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 95 of file G4ITTransportation.cc
References G4VProcess::enableAlongStepDoIt, G4VProcess::enableAtRestDoIt, G4VProcess::enablePostStepDoIt, fFieldPropagator, fInstantiateProcessState, fLinearNavigator, fParticleChange, fpSafetyHelper, G4VITProcess::fpState, G4ITTransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetPropagatorInField(), G4ITTransportationManager::GetSafetyHelper(), G4TransportationManager::GetTransportationManager(), G4ITTransportationManager::GetTransportationManager(), G4VProcess::pParticleChange, G4VITProcess::SetInstantiateProcessState(), SetInstantiateProcessState(), and G4VProcess::SetProcessSubType().
G4ITTransportation::~G4ITTransportation () virtual
Definition at line 214 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 214 of file G4ITTransportation.cc
References fMaxEnergyKilled, fSumEnergyKilled, fVerboseLevel, G4cout, and G4endl.
G4ITTransportation::G4ITTransportation (const G4ITTransportation & right)
Definition at line 138 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 138 of file G4ITTransportation.cc
References G4VProcess::enableAlongStepDoIt, G4VProcess::enableAtRestDoIt, G4VProcess::enablePostStepDoIt, fFieldPropagator, fInstantiateProcessState, fLinearNavigator, fMaxEnergyKilled, fParticleChange, fpSafetyHelper, fShortStepOptimisation, fSumEnergyKilled, fThreshold_Important_Energy, fThreshold_Warning_Energy, fThresholdTrials, fUnimportant_Energy, fVerboseLevel, G4ITTransportationManager::GetNavigatorForTracking(), G4TransportationManager::GetPropagatorInField(), G4ITTransportationManager::GetSafetyHelper(), G4TransportationManager::GetTransportationManager(), G4ITTransportationManager::GetTransportationManager(), G4VProcess::pParticleChange, G4VITProcess::SetInstantiateProcessState(), and SetInstantiateProcessState().
Member Function Documentation
G4VParticleChange * G4ITTransportation::AlongStepDoIt (const G4Track & track, const G4Step & stepData) virtual
!!!!!!! A REVOIR !!!!
Implements G4VProcess.
Reimplemented in G4DNABrownianTransportation.
Definition at line 688 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 688 of file G4ITTransportation.cc
References G4Track::CalculateVelocityForOpticalPhoton(), fFieldPropagator, G4ParticleTable::FindParticle(), fMaxEnergyKilled, fParticleChange, fStopAndKill, fSumEnergyKilled, fThreshold_Important_Energy, fThreshold_Warning_Energy, fThresholdTrials, fVerboseLevel, G4cout, G4endl, G4ThreadLocal, G4Track::GetGlobalTime(), G4Track::GetKineticEnergy(), G4Track::GetLocalTime(), G4Track::GetParticleDefinition(), G4ParticleTable::GetParticleTable(), G4Step::GetPreStepPoint(), G4Track::GetStepLength(), G4StepPoint::GetVelocity(), G4PropagatorInField::GimmeTrajectoryVectorAndForgetIt(), G4ParticleChangeForTransport::Initialize(), G4MemStat::MemoryUsage(), MeV, PrepareState, G4ParticleChange::ProposeEnergy(), G4ParticleChange::ProposeGlobalTime(), G4ParticleChange::ProposeLocalTime(), G4ParticleChange::ProposeMomentumDirection(), G4ParticleChange::ProposePolarization(), G4ParticleChange::ProposePosition(), G4VParticleChange::ProposeTrackStatus(), G4VParticleChange::ProposeTrueStepLength(), G4ParticleChange::ProposeVelocity(), G4ParticleChangeForTransport::SetMomentumChanged(), G4ParticleChangeForTransport::SetPointerToVectorOfAuxiliaryPoints(), and State.
Referenced by G4DNABrownianTransportation::AlongStepDoIt().
G4double G4ITTransportation::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double , G4double currentMinimumStep, G4double & currentSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Reimplemented in G4DNABrownianTransportation.
Definition at line 252 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 252 of file G4ITTransportation.cc
References CandidateForSelection, G4FieldManager::ConfigureForTrack(), FatalException, fFieldPropagator, G4PropagatorInField::FindAndSetFieldManager(), fLinearNavigator, fPreviousSafety, fPreviousSftOrigin, fpSafetyHelper, fShortStepOptimisation, G4cout, G4endl, G4Exception(), G4DynamicParticle::GetCharge(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), GetIT(), G4Track::GetKineticEnergy(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetPolarization(), G4Track::GetPosition(), G4IT::GetTrackingInfo(), G4TrackingInformation::GetTrackStateManager(), G4Track::GetVelocity(), G4Track::GetVolume(), G4TrackStateDependent< T >::LoadTrackState(), CLHEP::Hep3Vector::mag2(), PrepareState, G4TrackStateDependent< T >::ResetTrackState(), G4ITSafetyHelper::SetCurrentSafety(), sqr(), State, and G4VITProcess::theInteractionTimeLeft.
Referenced by G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength().
virtual G4VParticleChange* G4ITTransportation::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 113 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 113 of file G4ITTransportation.hh
virtual G4double G4ITTransportation::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VProcess.
Definition at line 106 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 106 of file G4ITTransportation.hh
void G4ITTransportation::BuildPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VITProcess.
Reimplemented in G4DNABrownianTransportation.
Definition at line 229 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 229 of file G4ITTransportation.cc
References fpSafetyHelper, and G4ITSafetyHelper::InitialiseHelper().
Referenced by G4DNABrownianTransportation::BuildPhysicsTable().
void G4ITTransportation::ComputeStep (const G4Track & track, const G4Step & , const double timeStep, double & spaceStep) virtual
Reimplemented in G4DNABrownianTransportation.
Definition at line 647 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 647 of file G4ITTransportation.cc
References G4Track::CalculateVelocity(), fParticleChange, G4Track::GetDynamicParticle(), G4Track::GetGlobalTime(), G4DynamicParticle::GetMomentumDirection(), G4Track::GetPosition(), G4Track::GetVelocity(), PrepareState, G4ParticleChange::ProposeVelocity(), and State.
Referenced by G4ITStepProcessor::DoDefinePhysicalStepLength().
G4bool G4ITTransportation::DoesGlobalFieldExist () protected
Definition at line 234 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 234 of file G4ITTransportation.cc
References G4FieldManager::DoesFieldExist(), G4TransportationManager::GetFieldManager(), and G4TransportationManager::GetTransportationManager().
Referenced by StartTracking().
void G4ITTransportation::EnableShortStepOptimisation (G4bool optimise = true) inline
G4double G4ITTransportation::GetMaxEnergyKilled () const inline
G4PropagatorInField* G4ITTransportation::GetPropagatorInField ()
G4double G4ITTransportation::GetSumEnergyKilled () const inline
G4double G4ITTransportation::GetThresholdImportantEnergy () const inline
G4int G4ITTransportation::GetThresholdTrials () const inline
G4double G4ITTransportation::GetThresholdWarningEnergy () const inline
G4int G4ITTransportation::GetVerboseLevel () const inline
G4bool G4ITTransportation::InstantiateProcessState () inline protected
Definition at line 259 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 259 of file G4ITTransportation.hh
References fInstantiateProcessState.
G4bool G4ITTransportation::IsStepLimitedByGeometry () inline
Definition at line 97 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ITTransportation.hh
G4ITTransportation & G4ITTransportation::operator= (const G4ITTransportation &) private
Definition at line 175 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 175 of file G4ITTransportation.cc
G4VParticleChange * G4ITTransportation::PostStepDoIt (const G4Track & track, const G4Step &) virtual
Implements G4VProcess.
Reimplemented in G4DNABrownianTransportation.
Definition at line 870 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 870 of file G4ITTransportation.cc
References FatalErrorInArgument, fLinearNavigator, fParticleChange, fStopAndKill, fVerboseLevel, G4cout, G4endl, G4Exception(), G4VPhysicalVolume::GetLogicalVolume(), G4MaterialCutsCouple::GetMaterial(), G4LogicalVolume::GetMaterial(), G4ProductionCutsTable::GetMaterialCutsCouple(), G4LogicalVolume::GetMaterialCutsCouple(), G4Track::GetMomentumDirection(), G4Track::GetPosition(), G4MaterialCutsCouple::GetProductionCuts(), G4ProductionCutsTable::GetProductionCutsTable(), G4LogicalVolume::GetSensitiveDetector(), G4Track::GetTouchableHandle(), G4Track::GetTrackID(), G4Track::GetTrackStatus(), G4VTouchable::GetVolume(), G4ParticleChangeForTransport::Initialize(), nanometer, PrepareState, G4VParticleChange::ProposeLastStepInVolume(), G4VParticleChange::ProposeTrackStatus(), G4ParticleChangeForTransport::SetMaterialCutsCoupleInTouchable(), G4ParticleChangeForTransport::SetMaterialInTouchable(), G4ParticleChangeForTransport::SetSensitiveDetectorInTouchable(), G4ParticleChangeForTransport::SetTouchableHandle(), and State.
Referenced by G4DNABrownianTransportation::PostStepDoIt().
G4double G4ITTransportation::PostStepGetPhysicalInteractionLength (const G4Track & , G4double , G4ForceCondition * pForceCond) virtual
Implements G4VProcess.
Definition at line 859 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 859 of file G4ITTransportation.cc
References DBL_MAX, and Forced.
void G4ITTransportation::ResetKilledStatistics (G4int report = 1) inline
void G4ITTransportation::SetInstantiateProcessState (G4bool flag) inline protected
Definition at line 254 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 254 of file G4ITTransportation.hh
References fInstantiateProcessState.
Referenced by G4ITTransportation(), and G4DNABrownianTransportation::StartTracking().
void G4ITTransportation::SetPropagatorInField (G4PropagatorInField * pFieldPropagator)
void G4ITTransportation::SetThresholdImportantEnergy (G4double newEnImp) inline
void G4ITTransportation::SetThresholdTrials (G4int newMaxTrials) inline
void G4ITTransportation::SetThresholdWarningEnergy (G4double newEnWarn) inline
void G4ITTransportation::SetVerboseLevel (G4int verboseLevel) inline
void G4ITTransportation::StartTracking (G4Track * aTrack) virtual
Reimplemented from G4VITProcess.
Reimplemented in G4DNABrownianTransportation.
Definition at line 1040 of file G4ITTransportation.cc.
View newest version in sPHENIX GitHub at line 1040 of file G4ITTransportation.cc
References G4PropagatorInField::ClearPropagatorState(), DoesGlobalFieldExist(), fFieldPropagator, fInstantiateProcessState, fpSafetyHelper, G4VITProcess::fpState, G4ThreadLocal, G4FieldManagerStore::GetInstance(), GetIT(), G4Track::GetTouchableHandle(), G4TrackStateDependent< T >::NewTrackState(), PrepareState, G4TrackStateDependent< T >::SaveTrackState(), G4VITProcess::StartTracking(), G4VProcess::StartTracking(), and State.
Referenced by G4DNABrownianTransportation::StartTracking().
Member Data Documentation
G4PropagatorInField* G4ITTransportation::fFieldPropagator protected
Definition at line 220 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 220 of file G4ITTransportation.hh
Referenced by AlongStepDoIt(), AlongStepGetPhysicalInteractionLength(), G4ITTransportation(), and StartTracking().
G4bool G4ITTransportation::fInstantiateProcessState private
Definition at line 265 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 265 of file G4ITTransportation.hh
Referenced by G4ITTransportation(), InstantiateProcessState(), SetInstantiateProcessState(), and StartTracking().
G4ITNavigator* G4ITTransportation::fLinearNavigator protected
Definition at line 219 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 219 of file G4ITTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4ITTransportation(), and PostStepDoIt().
G4double G4ITTransportation::fMaxEnergyKilled protected
Definition at line 241 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 241 of file G4ITTransportation.hh
Referenced by AlongStepDoIt(), G4ITTransportation(), and ~G4ITTransportation().
G4ParticleChangeForTransport G4ITTransportation::fParticleChange protected
Definition at line 226 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 226 of file G4ITTransportation.hh
Referenced by AlongStepDoIt(), G4DNABrownianTransportation::AlongStepDoIt(), ComputeStep(), G4DNABrownianTransportation::Diffusion(), G4ITTransportation(), PostStepDoIt(), and G4DNABrownianTransportation::PostStepDoIt().
G4ITSafetyHelper* G4ITTransportation::fpSafetyHelper protected
Definition at line 247 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 247 of file G4ITTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), BuildPhysicsTable(), G4DNABrownianTransportation::BuildPhysicsTable(), G4DNABrownianTransportation::ComputeGeomLimit(), G4ITTransportation(), and StartTracking().
G4bool G4ITTransportation::fShortStepOptimisation protected
Definition at line 245 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 245 of file G4ITTransportation.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and G4ITTransportation().
G4double G4ITTransportation::fSumEnergyKilled protected
Definition at line 240 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 240 of file G4ITTransportation.hh
Referenced by AlongStepDoIt(), G4ITTransportation(), and ~G4ITTransportation().
G4double G4ITTransportation::fThreshold_Important_Energy protected
Definition at line 232 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 232 of file G4ITTransportation.hh
Referenced by AlongStepDoIt(), and G4ITTransportation().
G4double G4ITTransportation::fThreshold_Warning_Energy protected
Definition at line 231 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 231 of file G4ITTransportation.hh
Referenced by AlongStepDoIt(), and G4ITTransportation().
G4int G4ITTransportation::fThresholdTrials protected
Definition at line 233 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 233 of file G4ITTransportation.hh
Referenced by AlongStepDoIt(), and G4ITTransportation().
G4double G4ITTransportation::fUnimportant_Energy protected
Definition at line 236 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 236 of file G4ITTransportation.hh
Referenced by G4ITTransportation().
G4int G4ITTransportation::fVerboseLevel protected
Definition at line 250 of file G4ITTransportation.hh.
View newest version in sPHENIX GitHub at line 250 of file G4ITTransportation.hh
Referenced by AlongStepDoIt(), G4DNABrownianTransportation::AlongStepDoIt(), G4DNABrownianTransportation::AlongStepGetPhysicalInteractionLength(), G4DNABrownianTransportation::ComputeStep(), G4DNABrownianTransportation::Diffusion(), G4DNABrownianTransportation::G4DNABrownianTransportation(), G4ITTransportation(), PostStepDoIt(), G4DNABrownianTransportation::PostStepDoIt(), and ~G4ITTransportation().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/include/G4ITTransportation.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/dna/management/src/G4ITTransportation.cc