ECCE @ EIC Software: G4Parton Class Reference
G4Parton Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4Parton.hh>
Public Member Functions
G4Parton ()
G4Parton (G4int PDGencoding)
G4Parton (const G4Parton &right)
~G4Parton ()
G4Parton & operator= (const G4Parton &right)
G4bool operator== (const G4Parton &right) const
G4bool operator!= (const G4Parton &right) const
G4int GetPDGcode () const
G4ParticleDefinition * GetDefinition ()
void SetDefinition (G4ParticleDefinition *aDefinition)
void DefineMomentumInZ (G4double aLightConeMomentum, G4bool aDirection)
void DefineMomentumInZ (G4double aLightConeMomentum, G4double aLightConeE, G4bool aDirection)
const G4ThreeVector & GetPosition () const
void SetPosition (const G4ThreeVector &aPosition)
const G4LorentzVector & Get4Momentum () const
void Set4Momentum (const G4LorentzVector &aMomentum)
void SetX (G4double anX)
G4double GetX ()
void SetColour (G4int aColour)
G4int GetColour ()
void SetIsoSpinZ (G4double anIsoSpinZ)
G4double GetIsoSpinZ ()
void SetSpinZ (G4double aSpinZ)
G4double GetSpinZ ()
Public Attributes
G4int PDGencoding
G4ParticleDefinition * theDefinition
Private Member Functions
G4double GetMass ()
Private Attributes
G4LorentzVector theMomentum
G4ThreeVector thePosition
G4int theColour
G4double theIsoSpinZ
G4double theSpinZ
G4double theX
Detailed Description
Definition at line 47 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 47 of file G4Parton.hh
Constructor & Destructor Documentation
G4Parton::G4Parton () inline
Definition at line 50 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 50 of file G4Parton.hh
References G4UniformRand, PDGencoding, theColour, theIsoSpinZ, and theSpinZ.
G4Parton::G4Parton (G4int PDGencoding)
Definition at line 39 of file G4Parton.cc.
View newest version in sPHENIX GitHub at line 39 of file G4Parton.cc
References kdfinder::abs(), G4ParticleTable::FindParticle(), G4cout, G4endl, G4UniformRand, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetParticleType(), G4ParticleDefinition::GetPDGiIsospin(), G4ParticleDefinition::GetPDGIsospin3(), G4ParticleDefinition::GetPDGiSpin(), PDGencoding, theColour, theDefinition, theIsoSpinZ, theSpinZ, and theX.
G4Parton::G4Parton (const G4Parton & right)
Definition at line 107 of file G4Parton.cc.
View newest version in sPHENIX GitHub at line 107 of file G4Parton.cc
References PDGencoding, theColour, theDefinition, theIsoSpinZ, theMomentum, thePosition, theSpinZ, and theX.
G4Parton::~G4Parton ()
Definition at line 136 of file G4Parton.cc.
View newest version in sPHENIX GitHub at line 136 of file G4Parton.cc
Member Function Documentation
void G4Parton::DefineMomentumInZ (G4double aLightConeMomentum, G4bool aDirection)
Definition at line 142 of file G4Parton.cc.
View newest version in sPHENIX GitHub at line 142 of file G4Parton.cc
References Get4Momentum(), GetMass(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), sqr(), and theX.
void G4Parton::DefineMomentumInZ (G4double aLightConeMomentum, G4double aLightConeE, G4bool aDirection)
Definition at line 153 of file G4Parton.cc.
View newest version in sPHENIX GitHub at line 153 of file G4Parton.cc
References Get4Momentum(), GetMass(), CLHEP::HepLorentzVector::px(), CLHEP::HepLorentzVector::py(), Set4Momentum(), CLHEP::HepLorentzVector::setE(), CLHEP::HepLorentzVector::setPz(), sqr(), and theX.
const G4LorentzVector & G4Parton::Get4Momentum () const inline
Definition at line 143 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 143 of file G4Parton.hh
References theMomentum.
Referenced by G4SoftStringBuilder::BuildString(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::CreateStrings(), DefineMomentumInZ(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4FragmentingString::G4FragmentingString(), G4PartonPair::G4PartonPair(), G4LundStringFragmentation::Loop_toFragmentString(), operator=(), G4QGSParticipants::PerformSoftCollisions(), and G4QGSDiffractiveExcitation::String().
G4int G4Parton::GetColour () inline
Definition at line 90 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 90 of file G4Parton.hh
References theColour.
Referenced by G4PartonPair::G4PartonPair(), G4QGSMSplitableHadron::GetValenceQuarkFlavors(), and G4QGSMSplitableHadron::SoftSplitUp().
G4ParticleDefinition * G4Parton::GetDefinition () inline
Definition at line 161 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 161 of file G4Parton.hh
References theDefinition.
Referenced by G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::DeterminePartonMomenta(), G4QuarkExchange::ExciteParticipants(), G4FragmentingString::G4FragmentingString(), and G4PartonPair::G4PartonPair().
G4double G4Parton::GetIsoSpinZ () inline
Definition at line 93 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 93 of file G4Parton.hh
References theIsoSpinZ.
G4double G4Parton::GetMass () inline private
Definition at line 155 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 155 of file G4Parton.hh
References G4ParticleDefinition::GetPDGMass(), and theDefinition.
Referenced by DefineMomentumInZ().
G4int G4Parton::GetPDGcode () const inline
Definition at line 127 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 127 of file G4Parton.hh
References PDGencoding.
Referenced by G4SoftStringBuilder::BuildString(), G4FTFModel::BuildStrings(), G4DiffractiveExcitation::CreateStrings(), G4QGSParticipants::CreateStrings(), G4QGSMFragmentation::FragmentString(), G4LundStringFragmentation::FragmentString(), G4ExcitedString::GetAntiColorParton(), G4ExcitedString::GetColorParton(), G4LundStringFragmentation::Loop_toFragmentString(), operator=(), G4QGSParticipants::PerformSoftCollisions(), and G4QGSDiffractiveExcitation::String().
const G4ThreeVector & G4Parton::GetPosition (void) const inline
Definition at line 132 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 132 of file G4Parton.hh
References thePosition.
Referenced by G4ExcitedString::G4ExcitedString(), and operator=().
G4double G4Parton::GetSpinZ () inline
Definition at line 96 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 96 of file G4Parton.hh
References theSpinZ.
Referenced by G4PartonPair::G4PartonPair(), G4QGSMSplitableHadron::GetValenceQuarkFlavors(), and G4QGSMSplitableHadron::SoftSplitUp().
G4double G4Parton::GetX () inline
Definition at line 87 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 87 of file G4Parton.hh
References theX.
Referenced by G4SoftStringBuilder::BuildString(), G4QGSParticipants::CreateStrings(), and G4QGSParticipants::PerformSoftCollisions().
G4bool G4Parton::operator!= (const G4Parton & right) const inline
Definition at line 122 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 122 of file G4Parton.hh
References right.
G4Parton & G4Parton::operator= (const G4Parton & right)
Definition at line 119 of file G4Parton.cc.
View newest version in sPHENIX GitHub at line 119 of file G4Parton.cc
References Get4Momentum(), GetPDGcode(), GetPosition(), PDGencoding, theColour, theDefinition, theIsoSpinZ, theMomentum, thePosition, theSpinZ, and theX.
G4bool G4Parton::operator== (const G4Parton & right) const inline
Definition at line 117 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 117 of file G4Parton.hh
References right.
void G4Parton::Set4Momentum (const G4LorentzVector & aMomentum) inline
Definition at line 148 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 148 of file G4Parton.hh
References theMomentum.
Referenced by G4QGSMSplitableHadron::BuildSeaQuark(), G4FTFAnnihilation::Create1DiquarkAntiDiquarkString(), G4FTFAnnihilation::Create1QuarkAntiQuarkString(), G4DiffractiveExcitation::CreateStrings(), DefineMomentumInZ(), G4QGSParticipants::DeterminePartonMomenta(), G4QGSMSplitableHadron::DiffractiveSplitUp(), G4DiffractiveSplitableHadron::G4DiffractiveSplitableHadron(), G4DiffractiveSplitableHadron::SetFirstParton(), G4DiffractiveSplitableHadron::SetSecondParton(), G4QGSMSplitableHadron::SoftSplitUp(), G4DiffractiveSplitableHadron::SplitUp(), and G4QGSDiffractiveExcitation::String().
void G4Parton::SetColour (G4int aColour) inline
Definition at line 89 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 89 of file G4Parton.hh
References theColour.
Referenced by G4QGSMSplitableHadron::GetValenceQuarkFlavors(), and G4QGSMSplitableHadron::SoftSplitUp().
void G4Parton::SetDefinition (G4ParticleDefinition * aDefinition) inline
Definition at line 166 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 166 of file G4Parton.hh
References G4ParticleDefinition::GetPDGEncoding(), PDGencoding, and theDefinition.
Referenced by G4QuarkExchange::ExciteParticipants().
void G4Parton::SetIsoSpinZ (G4double anIsoSpinZ) inline
Definition at line 92 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 92 of file G4Parton.hh
References theIsoSpinZ.
void G4Parton::SetPosition (const G4ThreeVector & aPosition) inline
Definition at line 137 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 137 of file G4Parton.hh
References thePosition.
Referenced by G4QGSMSplitableHadron::BuildSeaQuark(), G4QGSMSplitableHadron::DiffractiveSplitUp(), and G4QGSMSplitableHadron::GetValenceQuarkFlavors().
void G4Parton::SetSpinZ (G4double aSpinZ) inline
Definition at line 95 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 95 of file G4Parton.hh
References theSpinZ.
Referenced by G4QGSMSplitableHadron::GetValenceQuarkFlavors(), and G4QGSMSplitableHadron::SoftSplitUp().
void G4Parton::SetX (G4double anX) inline
Definition at line 86 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 86 of file G4Parton.hh
References theX.
Member Data Documentation
G4int G4Parton::PDGencoding
Definition at line 102 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 102 of file G4Parton.hh
Referenced by G4Parton(), GetPDGcode(), operator=(), and SetDefinition().
G4int G4Parton::theColour private
Definition at line 109 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 109 of file G4Parton.hh
Referenced by G4Parton(), GetColour(), operator=(), and SetColour().
G4ParticleDefinition* G4Parton::theDefinition
Definition at line 103 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 103 of file G4Parton.hh
Referenced by G4Parton(), GetDefinition(), GetMass(), operator=(), and SetDefinition().
G4double G4Parton::theIsoSpinZ private
Definition at line 110 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 110 of file G4Parton.hh
Referenced by G4Parton(), GetIsoSpinZ(), operator=(), and SetIsoSpinZ().
G4LorentzVector G4Parton::theMomentum private
Definition at line 106 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 106 of file G4Parton.hh
Referenced by G4Parton(), Get4Momentum(), operator=(), and Set4Momentum().
G4ThreeVector G4Parton::thePosition private
Definition at line 107 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 107 of file G4Parton.hh
Referenced by G4Parton(), GetPosition(), operator=(), and SetPosition().
G4double G4Parton::theSpinZ private
Definition at line 111 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 111 of file G4Parton.hh
Referenced by G4Parton(), GetSpinZ(), operator=(), and SetSpinZ().
G4double G4Parton::theX private
Definition at line 113 of file G4Parton.hh.
View newest version in sPHENIX GitHub at line 113 of file G4Parton.hh
Referenced by DefineMomentumInZ(), G4Parton(), GetX(), operator=(), and SetX().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/include/G4Parton.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/util/src/G4Parton.cc