ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/include/G3toG4MANY.hh File Reference
G3toG4MANY.hh File Reference
#include <vector>
#include "G3VolTableEntry.hh"
#include "G4Transform3D.hh"
Typedefs
typedef std::vector
< G3VolTableEntry * > G3VolTableEntryVector
Functions
void G3toG4MANY (G3VolTableEntry *curVTE)
void MakeBooleanSolids (G3VolTableEntry *curVTE, G3VolTableEntryVector *overlaps, const G4Transform3D &transform)
void SubstractSolids (G3VolTableEntry *vte1, G3VolTableEntry *vte2, G4int copy, const G4Transform3D &transform)
G4Transform3D GetTransform3D (G3Pos *)
Typedef Documentation
typedef std::vector<G3VolTableEntry*> G3VolTableEntryVector
Definition at line 68 of file G3toG4MANY.hh.
View newest version in sPHENIX GitHub at line 68 of file G3toG4MANY.hh
Function Documentation
void G3toG4MANY (G3VolTableEntry * curVTE)
Definition at line 38 of file G3toG4MANY.cc.
View newest version in sPHENIX GitHub at line 38 of file G3toG4MANY.cc
References FatalException, G3toG4MANY(), G4cout, G4endl, G4Exception(), G3VolTableEntry::GetDaughter(), G3VolTableEntry::GetG3PosCopy(), G3VolTableEntry::GetName(), G3VolTableEntry::GetNoDaughters(), G3VolTableEntry::GetNoOverlaps(), G3VolTableEntry::GetOverlaps(), GetTransform3D(), G3VolTableEntry::HasMANY(), HepGeom::Transform3D::inverse(), MakeBooleanSolids(), G3VolTableEntry::NPCopies(), and Acts::Test::transform.
Referenced by G3toG4MANY().
G4Transform3D GetTransform3D (G3Pos *)
Definition at line 145 of file G3toG4MANY.cc.
View newest version in sPHENIX GitHub at line 145 of file G3toG4MANY.cc
References G3Rot, G3RotTable::Get(), G3Pos::GetIrot(), G3Pos::GetPos(), and HepGeom::Transform3D::inverse().
Referenced by G3toG4MANY(), and SubstractSolids().
void MakeBooleanSolids (G3VolTableEntry * curVTE, G3VolTableEntryVector * overlaps, const G4Transform3D & transform)
Definition at line 75 of file G3toG4MANY.cc.
View newest version in sPHENIX GitHub at line 75 of file G3toG4MANY.cc
References G4cout, G4endl, G3VolTableEntry::GetClone(), G3VolTableEntry::GetMasterClone(), G3VolTableEntry::GetName(), G3VolTableEntry::GetNoClones(), G3VolTableEntry::NPCopies(), and SubstractSolids().
Referenced by G3toG4MANY().
void SubstractSolids (G3VolTableEntry * vte1, G3VolTableEntry * vte2, G4int copy, const G4Transform3D & transform)
Definition at line 106 of file G3toG4MANY.cc.
View newest version in sPHENIX GitHub at line 106 of file G3toG4MANY.cc
References FatalException, G4cout, G4endl, G4Exception(), G3VolTableEntry::GetDaughter(), G3VolTableEntry::GetG3PosCopy(), G4VSolid::GetName(), G3VolTableEntry::GetName(), G3VolTableEntry::GetNoDaughters(), G3VolTableEntry::GetSolid(), GetTransform3D(), HepGeom::Transform3D::inverse(), k, G3VolTableEntry::NPCopies(), G3VolTableEntry::SetSolid(), SubstractSolids(), and Acts::Test::transform.
Referenced by MakeBooleanSolids(), and SubstractSolids().