ECCE @ EIC Software: G4LatticeReader Class Reference
G4LatticeReader Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4LatticeReader.hh>
Public Member Functions
G4LatticeReader (G4int vb=0)
~G4LatticeReader ()
void SetVerboseLevel (G4int vb)
G4LatticeLogical * MakeLattice (const G4String &filepath)
Protected Member Functions
G4bool OpenFile (const G4String &filepath)
G4bool ProcessToken ()
G4bool ProcessValue (const G4String &name)
G4bool ProcessConstants ()
G4bool ProcessMap ()
G4bool ProcessNMap ()
G4bool ReadMapInfo ()
G4bool SkipComments ()
void CloseFile ()
Private Attributes
G4int verboseLevel
std::ifstream * psLatfile
G4LatticeLogical * pLattice
G4String fMapPath
G4String fToken
G4double fValue
G4String fMap
G4String fsPol
G4int fPol
G4int fNX
G4int fNY
Static Private Attributes
static const G4String fDataDir
Detailed Description
Definition at line 42 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 42 of file G4LatticeReader.hh
Constructor & Destructor Documentation
G4LatticeReader::G4LatticeReader (G4int vb = 0)
Definition at line 54 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 54 of file G4LatticeReader.cc
G4LatticeReader::~G4LatticeReader ()
Definition at line 58 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 58 of file G4LatticeReader.cc
References psLatfile.
Member Function Documentation
void G4LatticeReader::CloseFile () protected
Definition at line 125 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 125 of file G4LatticeReader.cc
References psLatfile.
Referenced by MakeLattice(), and OpenFile().
G4LatticeLogical * G4LatticeReader::MakeLattice (const G4String & filepath)
Definition at line 65 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 65 of file G4LatticeReader.cc
References CloseFile(), FatalException, INPUTHEPMC::filename, G4cout, G4endl, G4Exception(), OpenFile(), pLattice, ProcessToken(), psLatfile, and verboseLevel.
Referenced by G4LatticeManager::LoadLattice().
G4bool G4LatticeReader::OpenFile (const G4String & filepath) protected
Definition at line 99 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 99 of file G4LatticeReader.cc
References CloseFile(), fDataDir, INPUTHEPMC::filename, fMapPath, G4cout, G4endl, G4String::last(), psLatfile, and verboseLevel.
Referenced by MakeLattice().
G4bool G4LatticeReader::ProcessConstants () protected
Definition at line 184 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 184 of file G4LatticeReader.cc
References G4cout, G4endl, G4InuclParticleNames::lambda, pLattice, psLatfile, G4LatticeLogical::SetDynamicalConstants(), and verboseLevel.
Referenced by ProcessToken().
G4bool G4LatticeReader::ProcessMap () protected
Definition at line 231 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 231 of file G4LatticeReader.cc
References fMap, fNX, fNY, fPol, G4cerr, G4endl, G4LatticeLogical::LoadMap(), pLattice, and ReadMapInfo().
Referenced by ProcessToken().
G4bool G4LatticeReader::ProcessNMap () protected
Definition at line 240 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 240 of file G4LatticeReader.cc
References fMap, fNX, fNY, fPol, G4cerr, G4endl, G4LatticeLogical::Load_NMap(), pLattice, and ReadMapInfo().
Referenced by ProcessToken().
G4bool G4LatticeReader::ProcessToken () protected
Definition at line 134 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 134 of file G4LatticeReader.cc
References fToken, G4cout, G4endl, ProcessConstants(), ProcessMap(), ProcessNMap(), ProcessValue(), psLatfile, SkipComments(), and verboseLevel.
Referenced by MakeLattice().
G4bool G4LatticeReader::ProcessValue (const G4String & name) protected
Definition at line 158 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 158 of file G4LatticeReader.cc
References fValue, G4cerr, G4cout, G4endl, pLattice, psLatfile, G4LatticeLogical::SetAnhDecConstant(), G4LatticeLogical::SetFTDOS(), G4LatticeLogical::SetLDOS(), G4LatticeLogical::SetScatteringConstant(), G4LatticeLogical::SetSTDOS(), and verboseLevel.
Referenced by ProcessToken().
G4bool G4LatticeReader::ReadMapInfo () protected
Definition at line 197 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 197 of file G4LatticeReader.cc
References fMap, fMapPath, fNX, fNY, fPol, fsPol, G4cerr, G4cout, G4endl, G4LatticeLogical::MAXRES, psLatfile, G4String::toLower(), and verboseLevel.
Referenced by ProcessMap(), and ProcessNMap().
void G4LatticeReader::SetVerboseLevel (G4int vb) inline
Definition at line 47 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 47 of file G4LatticeReader.hh
References verboseLevel.
G4bool G4LatticeReader::SkipComments () protected
Definition at line 151 of file G4LatticeReader.cc.
View newest version in sPHENIX GitHub at line 151 of file G4LatticeReader.cc
References max, and psLatfile.
Referenced by ProcessToken().
Member Data Documentation
const G4String G4LatticeReader::fDataDir static private
Initial value:
=
  std::getenv("G4LATTICEDATA") ? (const char*)std::getenv("G4LATTICEDATA") : "./CrystalMaps"
Definition at line 74 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 74 of file G4LatticeReader.hh
Referenced by OpenFile().
G4String G4LatticeReader::fMap private
Definition at line 71 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 71 of file G4LatticeReader.hh
Referenced by ProcessMap(), ProcessNMap(), and ReadMapInfo().
G4String G4LatticeReader::fMapPath private
Definition at line 68 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 68 of file G4LatticeReader.hh
Referenced by OpenFile(), and ReadMapInfo().
G4int G4LatticeReader::fNX private
Definition at line 72 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 72 of file G4LatticeReader.hh
Referenced by ProcessMap(), ProcessNMap(), and ReadMapInfo().
G4int G4LatticeReader::fNY private
Definition at line 72 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 72 of file G4LatticeReader.hh
Referenced by ProcessMap(), ProcessNMap(), and ReadMapInfo().
G4int G4LatticeReader::fPol private
Definition at line 72 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 72 of file G4LatticeReader.hh
Referenced by ProcessMap(), ProcessNMap(), and ReadMapInfo().
G4String G4LatticeReader::fsPol private
Definition at line 71 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 71 of file G4LatticeReader.hh
Referenced by ReadMapInfo().
G4String G4LatticeReader::fToken private
Definition at line 69 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 69 of file G4LatticeReader.hh
Referenced by ProcessToken().
G4double G4LatticeReader::fValue private
Definition at line 70 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 70 of file G4LatticeReader.hh
Referenced by ProcessValue().
G4LatticeLogical* G4LatticeReader::pLattice private
Definition at line 66 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 66 of file G4LatticeReader.hh
Referenced by MakeLattice(), ProcessConstants(), ProcessMap(), ProcessNMap(), and ProcessValue().
std::ifstream* G4LatticeReader::psLatfile private
Definition at line 65 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 65 of file G4LatticeReader.hh
Referenced by CloseFile(), MakeLattice(), OpenFile(), ProcessConstants(), ProcessToken(), ProcessValue(), ReadMapInfo(), SkipComments(), and ~G4LatticeReader().
G4int G4LatticeReader::verboseLevel private
Definition at line 63 of file G4LatticeReader.hh.
View newest version in sPHENIX GitHub at line 63 of file G4LatticeReader.hh
Referenced by MakeLattice(), OpenFile(), ProcessConstants(), ProcessToken(), ProcessValue(), ReadMapInfo(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/include/G4LatticeReader.hh
geant4/tree/geant4-10.6-release/source/processes/solidstate/phonon/src/G4LatticeReader.cc