ECCE @ EIC Software: G4VAnalysisManager Class Reference
G4VAnalysisManager Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4VAnalysisManager.hh>
Public Member Functions
G4VAnalysisManager (const G4String &type, G4bool isMaster)
virtual ~G4VAnalysisManager ()
G4bool OpenFile (const G4String &fileName="")
G4bool Write ()
G4bool CloseFile (G4bool reset=true)
G4bool Merge (tools::histo::hmpi *hmpi)
G4bool Plot ()
G4bool IsOpenFile () const
G4bool SetFileName (const G4String &fileName)
G4bool SetHistoDirectoryName (const G4String &dirName)
G4bool SetNtupleDirectoryName (const G4String &dirName)
void SetCompressionLevel (G4int level)
G4String GetFileName () const
G4String GetHistoDirectoryName () const
G4String GetNtupleDirectoryName () const
G4int GetCompressionLevel () const
G4int CreateH1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4int CreateH1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none")
G4int CreateH2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4int CreateH2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4int CreateH3 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear", const G4String &zbinSchemeName="linear")
G4int CreateH3 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool SetH1 (G4int id, G4int nbins, G4double xmin, G4double xmax, const G4String &unitName="none", const G4String &fcnName="none", const G4String &binSchemeName="linear")
G4bool SetH1 (G4int id, const std::vector< G4double > &edges, const G4String &unitName="none", const G4String &fcnName="none")
G4bool SetH2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4bool SetH2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4bool SetH3 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nzbins, G4double zmin, G4double zmax, G4int nybins, G4double ymin, G4double ymax, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear", const G4String &zbinSchemeName="linear")
G4bool SetH3 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, const std::vector< G4double > &zedges, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool ScaleH1 (G4int id, G4double factor)
G4bool ScaleH2 (G4int id, G4double factor)
G4bool ScaleH3 (G4int id, G4double factor)
G4int CreateP1 (const G4String &name, const G4String &title, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear")
G4int CreateP1 (const G4String &name, const G4String &title, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4int CreateP2 (const G4String &name, const G4String &title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4int CreateP2 (const G4String &name, const G4String &title, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool SetP1 (G4int id, G4int nbins, G4double xmin, G4double xmax, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &xbinSchemeName="linear")
G4bool SetP1 (G4int id, const std::vector< G4double > &edges, G4double ymin=0, G4double ymax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none")
G4bool SetP2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none", const G4String &xbinSchemeName="linear", const G4String &ybinSchemeName="linear")
G4bool SetP2 (G4int id, const std::vector< G4double > &xedges, const std::vector< G4double > &yedges, G4double zmin=0, G4double zmax=0, const G4String &xunitName="none", const G4String &yunitName="none", const G4String &zunitName="none", const G4String &xfcnName="none", const G4String &yfcnName="none", const G4String &zfcnName="none")
G4bool ScaleP1 (G4int id, G4double factor)
G4bool ScaleP2 (G4int id, G4double factor)
G4int CreateNtuple (const G4String &name, const G4String &title)
G4int CreateNtupleIColumn (const G4String &name)
G4int CreateNtupleFColumn (const G4String &name)
G4int CreateNtupleDColumn (const G4String &name)
G4int CreateNtupleSColumn (const G4String &name)
G4int CreateNtupleIColumn (const G4String &name, std::vector< int > &vector)
G4int CreateNtupleFColumn (const G4String &name, std::vector< float > &vector)
G4int CreateNtupleDColumn (const G4String &name, std::vector< double > &vector)
void FinishNtuple ()
G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleSColumn (G4int ntupleId, const G4String &name)
G4int CreateNtupleIColumn (G4int ntupleId, const G4String &name, std::vector< int > &vector)
G4int CreateNtupleFColumn (G4int ntupleId, const G4String &name, std::vector< float > &vector)
G4int CreateNtupleDColumn (G4int ntupleId, const G4String &name, std::vector< double > &vector)
void FinishNtuple (G4int ntupleId)
virtual void SetNtupleMerging (G4bool mergeNtuples, G4int nofReducedNtupleFiles=0)
virtual void SetNtupleRowWise (G4bool rowWise, G4bool rowMode=true)
virtual void SetBasketSize (unsigned int basketSize)
virtual void SetBasketEntries (unsigned int basketEntries)
G4bool SetFirstHistoId (G4int firstId)
G4bool SetFirstH1Id (G4int firstId)
G4bool SetFirstH2Id (G4int firstId)
G4bool SetFirstH3Id (G4int firstId)
G4bool SetFirstProfileId (G4int firstId)
G4bool SetFirstP1Id (G4int firstId)
G4bool SetFirstP2Id (G4int firstId)
G4bool SetFirstNtupleId (G4int firstId)
G4bool SetFirstNtupleColumnId (G4int firstId)
G4bool FillH1 (G4int id, G4double value, G4double weight=1.0)
G4bool FillH2 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0)
G4bool FillH3 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0)
G4bool FillP1 (G4int id, G4double xvalue, G4double yvalue, G4double weight=1.0)
G4bool FillP2 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight=1.0)
G4bool FillNtupleIColumn (G4int id, G4int value)
G4bool FillNtupleFColumn (G4int id, G4float value)
G4bool FillNtupleDColumn (G4int id, G4double value)
G4bool FillNtupleSColumn (G4int id, const G4String &value)
G4bool AddNtupleRow ()
G4bool FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)
G4bool FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)
G4bool FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)
G4bool FillNtupleSColumn (G4int ntupleId, G4int id, const G4String &value)
G4bool AddNtupleRow (G4int ntupleId)
void SetActivation (G4bool activation)
G4bool GetActivation () const
G4bool IsActive () const
G4bool IsAscii () const
G4bool IsPlotting () const
G4int GetFirstH1Id () const
G4int GetFirstH2Id () const
G4int GetFirstH3Id () const
G4int GetFirstP1Id () const
G4int GetFirstP2Id () const
G4int GetFirstNtupleId () const
G4int GetFirstNtupleColumnId () const
G4int GetNofH1s () const
G4int GetNofH2s () const
G4int GetNofH3s () const
G4int GetNofP1s () const
G4int GetNofP2s () const
G4int GetNofNtuples () const
G4int GetH1Id (const G4String &name, G4bool warn=true) const
G4int GetH2Id (const G4String &name, G4bool warn=true) const
G4int GetH3Id (const G4String &name, G4bool warn=true) const
G4int GetP1Id (const G4String &name, G4bool warn=true) const
G4int GetP2Id (const G4String &name, G4bool warn=true) const
void SetH1Activation (G4bool activation)
void SetH1Activation (G4int id, G4bool activation)
void SetH1Ascii (G4int id, G4bool ascii)
void SetH1Plotting (G4int id, G4bool plotting)
void SetH2Activation (G4bool activation)
void SetH2Activation (G4int id, G4bool activation)
void SetH2Ascii (G4int id, G4bool ascii)
void SetH2Plotting (G4int id, G4bool plotting)
void SetH3Activation (G4bool activation)
void SetH3Activation (G4int id, G4bool activation)
void SetH3Ascii (G4int id, G4bool ascii)
void SetH3Plotting (G4int id, G4bool plotting)
void SetP1Activation (G4bool activation)
void SetP1Activation (G4int id, G4bool activation)
void SetP1Ascii (G4int id, G4bool ascii)
void SetP1Plotting (G4int id, G4bool plotting)
void SetP2Activation (G4bool activation)
void SetP2Activation (G4int id, G4bool activation)
void SetP2Ascii (G4int id, G4bool ascii)
void SetP2Plotting (G4int id, G4bool plotting)
void SetNtupleActivation (G4bool activation)
void SetNtupleActivation (G4int id, G4bool activation)
G4int GetH1Nbins (G4int id) const
G4double GetH1Xmin (G4int id) const
G4double GetH1Xmax (G4int id) const
G4double GetH1Width (G4int id) const
G4int GetH2Nxbins (G4int id) const
G4double GetH2Xmin (G4int id) const
G4double GetH2Xmax (G4int id) const
G4double GetH2XWidth (G4int id) const
G4int GetH2Nybins (G4int id) const
G4double GetH2Ymin (G4int id) const
G4double GetH2Ymax (G4int id) const
G4double GetH2YWidth (G4int id) const
G4int GetH3Nxbins (G4int id) const
G4double GetH3Xmin (G4int id) const
G4double GetH3Xmax (G4int id) const
G4double GetH3XWidth (G4int id) const
G4int GetH3Nybins (G4int id) const
G4double GetH3Ymin (G4int id) const
G4double GetH3Ymax (G4int id) const
G4double GetH3YWidth (G4int id) const
G4int GetH3Nzbins (G4int id) const
G4double GetH3Zmin (G4int id) const
G4double GetH3Zmax (G4int id) const
G4double GetH3ZWidth (G4int id) const
G4int GetP1Nbins (G4int id) const
G4double GetP1Xmin (G4int id) const
G4double GetP1Xmax (G4int id) const
G4double GetP1XWidth (G4int id) const
G4double GetP1Ymin (G4int id) const
G4double GetP1Ymax (G4int id) const
G4int GetP2Nxbins (G4int id) const
G4double GetP2Xmin (G4int id) const
G4double GetP2Xmax (G4int id) const
G4double GetP2XWidth (G4int id) const
G4int GetP2Nybins (G4int id) const
G4double GetP2Ymin (G4int id) const
G4double GetP2Ymax (G4int id) const
G4double GetP2YWidth (G4int id) const
G4double GetP2Zmin (G4int id) const
G4double GetP2Zmax (G4int id) const
G4String GetH1Name (G4int id) const
G4double GetH1Unit (G4int id) const
G4bool GetH1Activation (G4int id) const
G4bool GetH1Ascii (G4int id) const
G4bool GetH1Plotting (G4int id) const
G4String GetH2Name (G4int id) const
G4double GetH2XUnit (G4int id) const
G4double GetH2YUnit (G4int id) const
G4bool GetH2Activation (G4int id) const
G4bool GetH2Ascii (G4int id) const
G4bool GetH2Plotting (G4int id) const
G4String GetH3Name (G4int id) const
G4double GetH3XUnit (G4int id) const
G4double GetH3YUnit (G4int id) const
G4double GetH3ZUnit (G4int id) const
G4bool GetH3Activation (G4int id) const
G4bool GetH3Ascii (G4int id) const
G4bool GetH3Plotting (G4int id) const
G4String GetP1Name (G4int id) const
G4double GetP1XUnit (G4int id) const
G4double GetP1YUnit (G4int id) const
G4bool GetP1Activation (G4int id) const
G4bool GetP1Ascii (G4int id) const
G4bool GetP1Plotting (G4int id) const
G4String GetP2Name (G4int id) const
G4double GetP2XUnit (G4int id) const
G4double GetP2YUnit (G4int id) const
G4double GetP2ZUnit (G4int id) const
G4bool GetP2Activation (G4int id) const
G4bool GetP2Ascii (G4int id) const
G4bool GetP2Plotting (G4int id) const
G4bool GetNtupleActivation (G4int id) const
G4bool SetH1Title (G4int id, const G4String &title)
G4bool SetH1XAxisTitle (G4int id, const G4String &title)
G4bool SetH1YAxisTitle (G4int id, const G4String &title)
G4bool SetH1XAxisIsLog (G4int id, G4bool isLog)
G4bool SetH1YAxisIsLog (G4int id, G4bool isLog)
G4bool SetH2Title (G4int id, const G4String &title)
G4bool SetH2XAxisTitle (G4int id, const G4String &title)
G4bool SetH2YAxisTitle (G4int id, const G4String &title)
G4bool SetH2ZAxisTitle (G4int id, const G4String &title)
G4bool SetH2XAxisIsLog (G4int id, G4bool isLog)
G4bool SetH2YAxisIsLog (G4int id, G4bool isLog)
G4bool SetH2ZAxisIsLog (G4int id, G4bool isLog)
G4bool SetH3Title (G4int id, const G4String &title)
G4bool SetH3XAxisTitle (G4int id, const G4String &title)
G4bool SetH3YAxisTitle (G4int id, const G4String &title)
G4bool SetH3ZAxisTitle (G4int id, const G4String &title)
G4bool SetH3XAxisIsLog (G4int id, G4bool isLog)
G4bool SetH3YAxisIsLog (G4int id, G4bool isLog)
G4bool SetH3ZAxisIsLog (G4int id, G4bool isLog)
G4bool SetP1Title (G4int id, const G4String &title)
G4bool SetP1XAxisTitle (G4int id, const G4String &title)
G4bool SetP1YAxisTitle (G4int id, const G4String &title)
G4bool SetP1XAxisIsLog (G4int id, G4bool isLog)
G4bool SetP1YAxisIsLog (G4int id, G4bool isLog)
G4bool SetP2Title (G4int id, const G4String &title)
G4bool SetP2XAxisTitle (G4int id, const G4String &title)
G4bool SetP2YAxisTitle (G4int id, const G4String &title)
G4bool SetP2ZAxisTitle (G4int id, const G4String &title)
G4bool SetP2XAxisIsLog (G4int id, G4bool isLog)
G4bool SetP2YAxisIsLog (G4int id, G4bool isLog)
G4bool SetP2ZAxisIsLog (G4int id, G4bool isLog)
G4String GetH1Title (G4int id) const
G4String GetH1XAxisTitle (G4int id) const
G4String GetH1YAxisTitle (G4int id) const
G4bool GetH1XAxisIsLog (G4int id) const
G4bool GetH1YAxisIsLog (G4int id) const
G4String GetH2Title (G4int id) const
G4String GetH2XAxisTitle (G4int id) const
G4String GetH2YAxisTitle (G4int id) const
G4String GetH2ZAxisTitle (G4int id) const
G4bool GetH2XAxisIsLog (G4int id) const
G4bool GetH2YAxisIsLog (G4int id) const
G4bool GetH2ZAxisIsLog (G4int id) const
G4String GetH3Title (G4int id) const
G4String GetH3XAxisTitle (G4int id) const
G4String GetH3YAxisTitle (G4int id) const
G4String GetH3ZAxisTitle (G4int id) const
G4bool GetH3XAxisIsLog (G4int id) const
G4bool GetH3YAxisIsLog (G4int id) const
G4bool GetH3ZAxisIsLog (G4int id) const
G4String GetP1Title (G4int id) const
G4String GetP1XAxisTitle (G4int id) const
G4String GetP1YAxisTitle (G4int id) const
G4bool GetP1XAxisIsLog (G4int id) const
G4bool GetP1YAxisIsLog (G4int id) const
G4String GetP2Title (G4int id) const
G4String GetP2XAxisTitle (G4int id) const
G4String GetP2YAxisTitle (G4int id) const
G4String GetP2ZAxisTitle (G4int id) const
G4bool GetP2XAxisIsLog (G4int id) const
G4bool GetP2YAxisIsLog (G4int id) const
G4bool GetP2ZAxisIsLog (G4int id) const
void SetVerboseLevel (G4int verboseLevel)
G4int GetVerboseLevel () const
G4String GetType () const
G4String GetFileType () const
Protected Member Functions
virtual G4bool OpenFileImpl (const G4String &fileName)=0
virtual G4bool WriteImpl ()=0
virtual G4bool CloseFileImpl (G4bool reset)=0
virtual G4bool PlotImpl ()=0
virtual G4bool MergeImpl (tools::histo::hmpi *hmpi)=0
virtual G4bool IsOpenFileImpl () const =0
void SetH1Manager (G4VH1Manager *h1Manager)
void SetH2Manager (G4VH2Manager *h2Manager)
void SetH3Manager (G4VH3Manager *h3Manager)
void SetP1Manager (G4VP1Manager *p1Manager)
void SetP2Manager (G4VP2Manager *p2Manager)
void SetNtupleManager (G4VNtupleManager *ntupleManager)
void SetFileManager (std::shared_ptr< G4VFileManager > fileManager)
void SetPlotManager (std::shared_ptr< G4PlotManager > plotManager)
G4bool WriteAscii (const G4String &fileName)
Protected Attributes
G4AnalysisManagerState fState
std::shared_ptr< G4VFileManager > fVFileManager
std::shared_ptr< G4PlotManager > fPlotManager
Static Protected Attributes
static constexpr unsigned int fgkDefaultBasketSize = 32000
static constexpr unsigned int fgkDefaultBasketEntries = 4000
Private Attributes
std::unique_ptr
< G4AnalysisMessenger > fMessenger
std::shared_ptr< G4HnManager > fH1HnManager
std::shared_ptr< G4HnManager > fH2HnManager
std::shared_ptr< G4HnManager > fH3HnManager
std::shared_ptr< G4HnManager > fP1HnManager
std::shared_ptr< G4HnManager > fP2HnManager
std::unique_ptr< G4VH1Manager > fVH1Manager
std::unique_ptr< G4VH2Manager > fVH2Manager
std::unique_ptr< G4VH3Manager > fVH3Manager
std::unique_ptr< G4VP1Manager > fVP1Manager
std::unique_ptr< G4VP2Manager > fVP2Manager
G4VNtupleManager * fVNtupleManager
Detailed Description
Definition at line 65 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VAnalysisManager.hh
Constructor & Destructor Documentation
G4VAnalysisManager::G4VAnalysisManager (const G4String & type, G4bool isMaster)
Definition at line 61 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 61 of file G4VAnalysisManager.cc
G4VAnalysisManager::~G4VAnalysisManager () virtual
Definition at line 82 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 82 of file G4VAnalysisManager.cc
References fVNtupleManager.
Member Function Documentation
G4bool G4VAnalysisManager::AddNtupleRow ()
Referenced by Histo::AddRow(), XrayFluoAnalysisManager::analyseStepping(), XrayTelAnalysis::analyseStepping(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), CCalEventAction::EndOfEventAction(), HistoManager::FillNtuple(), G4HumanPhantomAnalysisManager::FillNtupleWithEnergyDeposition(), DMXPrimaryGeneratorAction::GeneratePrimaries(), ScreenSD::ProcessHits(), Par02Output::SaveTrack(), GammaRayTelAnalysis::setNtuple(), HadrontherapyLet::StoreLetAscii(), PurgMagSteppingAction::UserSteppingAction(), DMXEventAction::writePmtHitsToFile(), DMXEventAction::writeScintHitsToFile(), and ScoreSpecies::WriteWithAnalysisManager().
G4bool G4VAnalysisManager::AddNtupleRow (G4int ntupleId)
G4bool G4VAnalysisManager::CloseFile (G4bool reset = true)
Definition at line 241 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 241 of file G4VAnalysisManager.cc
References CloseFileImpl().
Referenced by Analysis::Close(), Par02Output::EndAnalysis(), HistoManager::EndOfRun(), GammaRayTelAnalysis::EndOfRun(), LXeRunAction::EndOfRunAction(), FCALRunAction::EndOfRunAction(), UltraRunAction::EndOfRunAction(), XrayFluoAnalysisManager::finish(), XrayTelAnalysis::finish(), main(), HistoManager::Save(), G4HumanPhantomAnalysisManager::save(), Histo::Save(), RMC01AnalysisManager::Save(), RunAction::SaveHisto(), HadrontherapyLet::StoreLetAscii(), RunAction::WriteHistogram(), RunAction::WriteNtuple(), and ScoreSpecies::WriteWithAnalysisManager().
virtual G4bool G4VAnalysisManager::CloseFileImpl (G4bool reset) protected pure virtual
Implemented in G4RootAnalysisManager, G4CsvAnalysisManager, G4Hdf5AnalysisManager, G4XmlAnalysisManager, and G4RootMpiAnalysisManager.
Referenced by CloseFile().
G4int G4VAnalysisManager::CreateH1 (const G4String & name, const G4String & title, G4int nbins, G4double xmin, G4double xmax, const G4String & unitName = "none", const G4String & fcnName = "none", const G4String & binSchemeName = "linear")
Definition at line 313 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 313 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckName(), G4Analysis::CheckNbins(), fVH1Manager, and G4Analysis::kInvalidId.
Referenced by GammaRayTelAnalysis::BeginOfRun(), UltraRunAction::BeginOfRunAction(), CCalRunAction::Book(), Analysis::Book(), HistoManager::Book(), ExGflashHistoManager::Book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), Histo::Book(), DMXRunAction::Book(), RunAction::Book(), RMC01AnalysisManager::Book(), RunAction::BookHisto(), Par02Output::CreateHistograms(), FCALRunAction::FCALRunAction(), and G4H1Messenger::SetNewValue().
G4int G4VAnalysisManager::CreateH1 (const G4String & name, const G4String & title, const std::vector< G4double > & edges, const G4String & unitName = "none", const G4String & fcnName = "none")
Definition at line 327 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 327 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), G4Analysis::CheckName(), fVH1Manager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateH2 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear")
Definition at line 338 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 338 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckName(), G4Analysis::CheckNbins(), fVH2Manager, and G4Analysis::kInvalidId.
Referenced by GammaRayTelAnalysis::BeginOfRun(), Analysis::Book(), XrayTelAnalysis::book(), DMXRunAction::Book(), and G4H2Messenger::SetNewValue().
G4int G4VAnalysisManager::CreateH2 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none")
Definition at line 362 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 362 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), G4Analysis::CheckName(), fVH2Manager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateH3 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4int nzbins, G4double zmin, G4double zmax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear", const G4String & zbinSchemeName = "linear")
Definition at line 380 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 380 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckName(), G4Analysis::CheckNbins(), fVH3Manager, and G4Analysis::kInvalidId.
Referenced by Analysis::Book(), and G4H3Messenger::SetNewValue().
G4int G4VAnalysisManager::CreateH3 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const std::vector< G4double > & zedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none")
Definition at line 413 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 413 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), G4Analysis::CheckName(), fVH3Manager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtuple (const G4String & name, const G4String & title)
Definition at line 751 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 751 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtuple(), fVNtupleManager, and G4Analysis::kInvalidId.
Referenced by GammaRayTelAnalysis::BeginOfRun(), CCalRunAction::Book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), Histo::Book(), PurgMagRunAction::Book(), DMXRunAction::Book(), RunAction::CreateHistogram(), RunAction::CreateNtuple(), G4PhysChemIO::G4Analysis::InitializeFile(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
G4int G4VAnalysisManager::CreateNtupleDColumn (const G4String & name)
Definition at line 776 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 776 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleDColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
Referenced by GammaRayTelAnalysis::BeginOfRun(), G4HumanPhantomAnalysisManager::book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), Histo::Book(), PurgMagRunAction::Book(), DMXRunAction::Book(), RunAction::CreateHistogram(), RunAction::CreateNtuple(), G4PhysChemIO::G4Analysis::InitializeFile(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
G4int G4VAnalysisManager::CreateNtupleDColumn (const G4String & name, std::vector< double > & vector)
Definition at line 810 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 810 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleDColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleDColumn (G4int ntupleId, const G4String & name)
Definition at line 882 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 882 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleDColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleDColumn (G4int ntupleId, const G4String & name, std::vector< double > & vector)
Definition at line 920 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 920 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleDColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleFColumn (const G4String & name)
Definition at line 768 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 768 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleFColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
Referenced by CCalRunAction::Book(), and Histo::Book().
G4int G4VAnalysisManager::CreateNtupleFColumn (const G4String & name, std::vector< float > & vector)
Definition at line 801 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 801 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleFColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleFColumn (G4int ntupleId, const G4String & name)
Definition at line 872 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 872 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleFColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleFColumn (G4int ntupleId, const G4String & name, std::vector< float > & vector)
Definition at line 910 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 910 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleFColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleIColumn (const G4String & name)
Definition at line 760 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 760 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleIColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
Referenced by XrayFluoAnalysisManager::book(), Histo::Book(), RunAction::CreateNtuple(), G4PhysChemIO::G4Analysis::InitializeFile(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
G4int G4VAnalysisManager::CreateNtupleIColumn (const G4String & name, std::vector< int > & vector)
Definition at line 792 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 792 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleIColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleIColumn (G4int ntupleId, const G4String & name)
Definition at line 863 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 863 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleIColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleIColumn (G4int ntupleId, const G4String & name, std::vector< int > & vector)
Definition at line 900 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 900 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleIColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateNtupleSColumn (const G4String & name)
Definition at line 784 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 784 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleSColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
Referenced by RunAction::CreateNtuple(), G4PhysChemIO::G4Analysis::InitializeFile(), and ScoreSpecies::WriteWithAnalysisManager().
G4int G4VAnalysisManager::CreateNtupleSColumn (G4int ntupleId, const G4String & name)
Definition at line 891 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 891 of file G4VAnalysisManager.cc
References G4Analysis::CheckName(), G4VNtupleManager::CreateNtupleSColumn(), fVNtupleManager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateP1 (const G4String & name, const G4String & title, G4int nbins, G4double xmin, G4double xmax, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinSchemeName = "linear")
Definition at line 559 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 559 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckName(), G4Analysis::CheckNbins(), fVP1Manager, and G4Analysis::kInvalidId.
Referenced by Analysis::Book(), ExGflashHistoManager::Book(), and G4P1Messenger::SetNewValue().
G4int G4VAnalysisManager::CreateP1 (const G4String & name, const G4String & title, const std::vector< G4double > & edges, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none")
Definition at line 580 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 580 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), G4Analysis::CheckMinMax(), G4Analysis::CheckName(), fVP1Manager, and G4Analysis::kInvalidId.
G4int G4VAnalysisManager::CreateP2 (const G4String & name, const G4String & title, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear")
Definition at line 598 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 598 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckName(), G4Analysis::CheckNbins(), fVP2Manager, and G4Analysis::kInvalidId.
Referenced by Analysis::Book(), and G4P2Messenger::SetNewValue().
G4int G4VAnalysisManager::CreateP2 (const G4String & name, const G4String & title, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none")
Definition at line 627 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 627 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), G4Analysis::CheckMinMax(), G4Analysis::CheckName(), fVP2Manager, and G4Analysis::kInvalidId.
G4bool G4VAnalysisManager::FillH1 (G4int id, G4double value, G4double weight = 1.0)
Referenced by Run::AddPhantomElectron(), Run::AddPhantomGamma(), Run::AddPhantomStep(), Run::AddTargetElectron(), Run::AddTargetPhoton(), XrayFluoAnalysisManager::analyseEnergyDep(), XrayFluoAnalysisManager::analysePrimaryGenerator(), XrayFluoAnalysisManager::analyseStepping(), XrayTelAnalysis::analyseStepping(), StackingAction::ClassifyNewTrack(), Run::ComputeFluenceError(), CCalSteppingAction::endOfEvent(), Run::EndOfEvent(), CCalEventAction::EndOfEventAction(), EventAction::EndOfEventAction(), FCALTBEventAction::EndOfEventAction(), LXeEventAction::EndOfEventAction(), DMXEventAction::EndOfEventAction(), UltraEventAction::EndOfEventAction(), Run::EndOfRun(), HistoManager::EndOfRun(), Histo::Fill(), RunAction::FillData(), Run::FillHisto(), HistoManager::FillHisto(), Par02Output::FillHistogram(), Run::FillPerEvent(), GammaRayTelAnalysis::InsertEnergy(), GammaRayTelAnalysis::InsertHits(), DMXSteppingAction::UserSteppingAction(), and DMXEventAction::writeScintHitsToFile().
G4bool G4VAnalysisManager::FillH2 (G4int id, G4double xvalue, G4double yvalue, G4double weight = 1.0)
Referenced by XrayTelAnalysis::analyseStepping(), GammaRayTelAnalysis::InsertPositionXZ(), GammaRayTelAnalysis::InsertPositionYZ(), and DMXEventAction::writePmtHitsToFile().
G4bool G4VAnalysisManager::FillH3 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight = 1.0)
G4bool G4VAnalysisManager::FillNtupleDColumn (G4int id, G4double value)
Referenced by XrayFluoAnalysisManager::analyseStepping(), XrayTelAnalysis::analyseStepping(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), HistoManager::FillNtuple(), G4HumanPhantomAnalysisManager::FillNtupleWithEnergyDeposition(), Histo::FillTupleD(), DMXPrimaryGeneratorAction::GeneratePrimaries(), ScreenSD::ProcessHits(), Par02Output::SaveTrack(), GammaRayTelAnalysis::setNtuple(), HadrontherapyLet::StoreLetAscii(), PurgMagSteppingAction::UserSteppingAction(), DMXEventAction::writePmtHitsToFile(), DMXEventAction::writeScintHitsToFile(), and ScoreSpecies::WriteWithAnalysisManager().
G4bool G4VAnalysisManager::FillNtupleDColumn (G4int ntupleId, G4int columnId, G4double value)
G4bool G4VAnalysisManager::FillNtupleFColumn (G4int id, G4float value)
Referenced by CCalEventAction::EndOfEventAction(), and Histo::FillTupleF().
G4bool G4VAnalysisManager::FillNtupleFColumn (G4int ntupleId, G4int columnId, G4float value)
G4bool G4VAnalysisManager::FillNtupleIColumn (G4int id, G4int value)
Referenced by XrayFluoAnalysisManager::analyseStepping(), G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), Histo::FillTupleI(), ScreenSD::ProcessHits(), Par02Output::SaveTrack(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
G4bool G4VAnalysisManager::FillNtupleIColumn (G4int ntupleId, G4int columnId, G4int value)
G4bool G4VAnalysisManager::FillNtupleSColumn (G4int id, const G4String & value)
Referenced by G4PhysChemIO::G4Analysis::CreateSolvatedElectron(), G4PhysChemIO::G4Analysis::CreateWaterMolecule(), and ScoreSpecies::WriteWithAnalysisManager().
G4bool G4VAnalysisManager::FillNtupleSColumn (G4int ntupleId, G4int id, const G4String & value)
G4bool G4VAnalysisManager::FillP1 (G4int id, G4double xvalue, G4double yvalue, G4double weight = 1.0)
Referenced by Run::FillPerEvent().
G4bool G4VAnalysisManager::FillP2 (G4int id, G4double xvalue, G4double yvalue, G4double zvalue, G4double weight = 1.0)
void G4VAnalysisManager::FinishNtuple ()
Definition at line 819 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 819 of file G4VAnalysisManager.cc
References G4VNtupleManager::FinishNtuple(), and fVNtupleManager.
Referenced by GammaRayTelAnalysis::BeginOfRun(), CCalRunAction::Book(), G4HumanPhantomAnalysisManager::book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), PurgMagRunAction::Book(), DMXRunAction::Book(), RunAction::CreateHistogram(), RunAction::CreateNtuple(), G4PhysChemIO::G4Analysis::InitializeFile(), HadrontherapyLet::StoreLetAscii(), and ScoreSpecies::WriteWithAnalysisManager().
void G4VAnalysisManager::FinishNtuple (G4int ntupleId)
Definition at line 930 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 930 of file G4VAnalysisManager.cc
References G4VNtupleManager::FinishNtuple(), and fVNtupleManager.
G4bool G4VAnalysisManager::GetActivation () const
G4int G4VAnalysisManager::GetCompressionLevel () const
Definition at line 307 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 307 of file G4VAnalysisManager.cc
References fState, and G4AnalysisManagerState::GetCompressionLevel().
G4String G4VAnalysisManager::GetFileName () const
Definition at line 289 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 289 of file G4VAnalysisManager.cc
References fVFileManager.
Referenced by FCALRunAction::FCALRunAction(), Run::PrintFluence(), Run::Run(), Run::WriteActivity(), and EventAction::WriteFibers().
G4String G4VAnalysisManager::GetFileType () const
Referenced by RMC01AnalysisManager::Book().
G4int G4VAnalysisManager::GetFirstH1Id () const
Definition at line 1057 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1057 of file G4VAnalysisManager.cc
References fH1HnManager.
G4int G4VAnalysisManager::GetFirstH2Id () const
Definition at line 1065 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1065 of file G4VAnalysisManager.cc
References fH2HnManager.
G4int G4VAnalysisManager::GetFirstH3Id () const
Definition at line 1073 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1073 of file G4VAnalysisManager.cc
References fH3HnManager.
G4int G4VAnalysisManager::GetFirstNtupleColumnId () const
Definition at line 1105 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1105 of file G4VAnalysisManager.cc
References fVNtupleManager, and G4VNtupleManager::GetFirstNtupleColumnId().
G4int G4VAnalysisManager::GetFirstNtupleId () const
Definition at line 1097 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1097 of file G4VAnalysisManager.cc
References fVNtupleManager, and G4BaseAnalysisManager::GetFirstId().
G4int G4VAnalysisManager::GetFirstP1Id () const
Definition at line 1081 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1081 of file G4VAnalysisManager.cc
References fP1HnManager.
G4int G4VAnalysisManager::GetFirstP2Id () const
Definition at line 1089 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1089 of file G4VAnalysisManager.cc
References fP2HnManager.
G4bool G4VAnalysisManager::GetH1Activation (G4int id) const
Referenced by StepMaxProcess::PostStepGetPhysicalInteractionLength().
G4bool G4VAnalysisManager::GetH1Ascii (G4int id) const
G4int G4VAnalysisManager::GetH1Id (const G4String & name, G4bool warn = true) const
Referenced by CCalRunAction::BeginOfRunAction(), CCalSteppingAction::endOfEvent(), and CCalEventAction::EndOfEventAction().
G4String G4VAnalysisManager::GetH1Name (G4int id) const
Referenced by HistoManager::PrintStatistic().
G4int G4VAnalysisManager::GetH1Nbins (G4int id) const
Referenced by HistoManager::DumpHistoParameters(), and Run::InitFluence().
G4bool G4VAnalysisManager::GetH1Plotting (G4int id) const
G4String G4VAnalysisManager::GetH1Title (G4int id) const
Referenced by HistoManager::DumpHistoParameters().
G4double G4VAnalysisManager::GetH1Unit (G4int id) const
Referenced by StepMaxProcess::PostStepGetPhysicalInteractionLength().
G4double G4VAnalysisManager::GetH1Width (G4int id) const
Referenced by HistoManager::DumpHistoParameters(), Run::InitFluence(), and StepMaxProcess::PostStepGetPhysicalInteractionLength().
G4bool G4VAnalysisManager::GetH1XAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetH1XAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetH1Xmax (G4int id) const
Referenced by HistoManager::DumpHistoParameters().
G4double G4VAnalysisManager::GetH1Xmin (G4int id) const
Referenced by HistoManager::DumpHistoParameters().
G4bool G4VAnalysisManager::GetH1YAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetH1YAxisTitle (G4int id) const
G4bool G4VAnalysisManager::GetH2Activation (G4int id) const
G4bool G4VAnalysisManager::GetH2Ascii (G4int id) const
G4int G4VAnalysisManager::GetH2Id (const G4String & name, G4bool warn = true) const
G4String G4VAnalysisManager::GetH2Name (G4int id) const
G4int G4VAnalysisManager::GetH2Nxbins (G4int id) const
G4int G4VAnalysisManager::GetH2Nybins (G4int id) const
G4bool G4VAnalysisManager::GetH2Plotting (G4int id) const
G4String G4VAnalysisManager::GetH2Title (G4int id) const
G4bool G4VAnalysisManager::GetH2XAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetH2XAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetH2Xmax (G4int id) const
G4double G4VAnalysisManager::GetH2Xmin (G4int id) const
G4double G4VAnalysisManager::GetH2XUnit (G4int id) const
G4double G4VAnalysisManager::GetH2XWidth (G4int id) const
G4bool G4VAnalysisManager::GetH2YAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetH2YAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetH2Ymax (G4int id) const
G4double G4VAnalysisManager::GetH2Ymin (G4int id) const
G4double G4VAnalysisManager::GetH2YUnit (G4int id) const
G4double G4VAnalysisManager::GetH2YWidth (G4int id) const
G4bool G4VAnalysisManager::GetH2ZAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetH2ZAxisTitle (G4int id) const
G4bool G4VAnalysisManager::GetH3Activation (G4int id) const
G4bool G4VAnalysisManager::GetH3Ascii (G4int id) const
G4int G4VAnalysisManager::GetH3Id (const G4String & name, G4bool warn = true) const
G4String G4VAnalysisManager::GetH3Name (G4int id) const
G4int G4VAnalysisManager::GetH3Nxbins (G4int id) const
G4int G4VAnalysisManager::GetH3Nybins (G4int id) const
G4int G4VAnalysisManager::GetH3Nzbins (G4int id) const
G4bool G4VAnalysisManager::GetH3Plotting (G4int id) const
G4String G4VAnalysisManager::GetH3Title (G4int id) const
G4bool G4VAnalysisManager::GetH3XAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetH3XAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetH3Xmax (G4int id) const
G4double G4VAnalysisManager::GetH3Xmin (G4int id) const
G4double G4VAnalysisManager::GetH3XUnit (G4int id) const
G4double G4VAnalysisManager::GetH3XWidth (G4int id) const
G4bool G4VAnalysisManager::GetH3YAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetH3YAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetH3Ymax (G4int id) const
G4double G4VAnalysisManager::GetH3Ymin (G4int id) const
G4double G4VAnalysisManager::GetH3YUnit (G4int id) const
G4double G4VAnalysisManager::GetH3YWidth (G4int id) const
G4bool G4VAnalysisManager::GetH3ZAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetH3ZAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetH3Zmax (G4int id) const
G4double G4VAnalysisManager::GetH3Zmin (G4int id) const
G4double G4VAnalysisManager::GetH3ZUnit (G4int id) const
G4double G4VAnalysisManager::GetH3ZWidth (G4int id) const
G4String G4VAnalysisManager::GetHistoDirectoryName () const
Definition at line 295 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 295 of file G4VAnalysisManager.cc
References fVFileManager.
G4int G4VAnalysisManager::GetNofH1s () const
Definition at line 1113 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1113 of file G4VAnalysisManager.cc
References fH1HnManager.
Referenced by HistoManager::PrintStatistic(), and RMC01AnalysisManager::Save().
G4int G4VAnalysisManager::GetNofH2s () const
Definition at line 1119 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1119 of file G4VAnalysisManager.cc
References fH2HnManager.
Referenced by RMC01AnalysisManager::Save().
G4int G4VAnalysisManager::GetNofH3s () const
Definition at line 1125 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1125 of file G4VAnalysisManager.cc
References fH3HnManager.
G4int G4VAnalysisManager::GetNofNtuples () const
Definition at line 1143 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1143 of file G4VAnalysisManager.cc
References fVNtupleManager, and G4VNtupleManager::GetNofNtuples().
G4int G4VAnalysisManager::GetNofP1s () const
Definition at line 1131 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1131 of file G4VAnalysisManager.cc
References fP1HnManager.
G4int G4VAnalysisManager::GetNofP2s () const
Definition at line 1137 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1137 of file G4VAnalysisManager.cc
References fP2HnManager.
G4bool G4VAnalysisManager::GetNtupleActivation (G4int id) const
G4String G4VAnalysisManager::GetNtupleDirectoryName () const
Definition at line 301 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 301 of file G4VAnalysisManager.cc
References fVFileManager.
G4bool G4VAnalysisManager::GetP1Activation (G4int id) const
G4bool G4VAnalysisManager::GetP1Ascii (G4int id) const
G4int G4VAnalysisManager::GetP1Id (const G4String & name, G4bool warn = true) const
G4String G4VAnalysisManager::GetP1Name (G4int id) const
G4int G4VAnalysisManager::GetP1Nbins (G4int id) const
G4bool G4VAnalysisManager::GetP1Plotting (G4int id) const
G4String G4VAnalysisManager::GetP1Title (G4int id) const
G4bool G4VAnalysisManager::GetP1XAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetP1XAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetP1Xmax (G4int id) const
G4double G4VAnalysisManager::GetP1Xmin (G4int id) const
G4double G4VAnalysisManager::GetP1XUnit (G4int id) const
G4double G4VAnalysisManager::GetP1XWidth (G4int id) const
G4bool G4VAnalysisManager::GetP1YAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetP1YAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetP1Ymax (G4int id) const
G4double G4VAnalysisManager::GetP1Ymin (G4int id) const
G4double G4VAnalysisManager::GetP1YUnit (G4int id) const
G4bool G4VAnalysisManager::GetP2Activation (G4int id) const
G4bool G4VAnalysisManager::GetP2Ascii (G4int id) const
G4int G4VAnalysisManager::GetP2Id (const G4String & name, G4bool warn = true) const
G4String G4VAnalysisManager::GetP2Name (G4int id) const
G4int G4VAnalysisManager::GetP2Nxbins (G4int id) const
G4int G4VAnalysisManager::GetP2Nybins (G4int id) const
G4bool G4VAnalysisManager::GetP2Plotting (G4int id) const
G4String G4VAnalysisManager::GetP2Title (G4int id) const
G4bool G4VAnalysisManager::GetP2XAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetP2XAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetP2Xmax (G4int id) const
G4double G4VAnalysisManager::GetP2Xmin (G4int id) const
G4double G4VAnalysisManager::GetP2XUnit (G4int id) const
G4double G4VAnalysisManager::GetP2XWidth (G4int id) const
G4bool G4VAnalysisManager::GetP2YAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetP2YAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetP2Ymax (G4int id) const
G4double G4VAnalysisManager::GetP2Ymin (G4int id) const
G4double G4VAnalysisManager::GetP2YUnit (G4int id) const
G4double G4VAnalysisManager::GetP2YWidth (G4int id) const
G4bool G4VAnalysisManager::GetP2ZAxisIsLog (G4int id) const
G4String G4VAnalysisManager::GetP2ZAxisTitle (G4int id) const
G4double G4VAnalysisManager::GetP2Zmax (G4int id) const
G4double G4VAnalysisManager::GetP2Zmin (G4int id) const
G4double G4VAnalysisManager::GetP2ZUnit (G4int id) const
G4String G4VAnalysisManager::GetType () const
Referenced by RunAction::CreateHistogram(), RunAction::CreateNtuple(), SetBasketEntries(), SetBasketSize(), SetNtupleMerging(), and SetNtupleRowWise().
G4int G4VAnalysisManager::GetVerboseLevel () const
G4bool G4VAnalysisManager::IsActive () const
Definition at line 1019 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1019 of file G4VAnalysisManager.cc
References fH1HnManager, fH2HnManager, fH3HnManager, fP1HnManager, fP2HnManager, fState, and G4AnalysisManagerState::GetIsActivation().
Referenced by LXeRunAction::BeginOfRunAction(), LXeRunAction::EndOfRunAction(), Run::Run(), and HistoManager::Update().
G4bool G4VAnalysisManager::IsAscii () const
Definition at line 1033 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1033 of file G4VAnalysisManager.cc
References fH1HnManager, fH2HnManager, fH3HnManager, fP1HnManager, and fP2HnManager.
Referenced by G4Hdf5AnalysisManager::WriteImpl(), G4XmlAnalysisManager::WriteImpl(), and G4RootAnalysisManager::WriteImpl().
G4bool G4VAnalysisManager::IsOpenFile () const
Definition at line 259 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 259 of file G4VAnalysisManager.cc
References IsOpenFileImpl().
virtual G4bool G4VAnalysisManager::IsOpenFileImpl () const protected pure virtual
Implemented in G4RootAnalysisManager, G4CsvAnalysisManager, G4Hdf5AnalysisManager, and G4XmlAnalysisManager.
Referenced by IsOpenFile().
G4bool G4VAnalysisManager::IsPlotting () const
Definition at line 1045 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1045 of file G4VAnalysisManager.cc
References fH1HnManager, fH2HnManager, fH3HnManager, fP1HnManager, and fP2HnManager.
Referenced by Write().
G4bool G4VAnalysisManager::Merge (tools::histo::hmpi * hmpi)
Definition at line 247 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 247 of file G4VAnalysisManager.cc
References MergeImpl().
Referenced by G4MPIhistoMerger::Merge().
virtual G4bool G4VAnalysisManager::MergeImpl (tools::histo::hmpi * hmpi) protected pure virtual
Implemented in G4ToolsAnalysisManager.
Referenced by Merge().
G4bool G4VAnalysisManager::OpenFile (const G4String & fileName = "")
Definition at line 206 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 206 of file G4VAnalysisManager.cc
References fVFileManager, G4Exception(), JustWarning, and OpenFileImpl().
Referenced by GammaRayTelAnalysis::BeginOfRun(), LXeRunAction::BeginOfRunAction(), FCALRunAction::BeginOfRunAction(), UltraRunAction::BeginOfRunAction(), CCalRunAction::Book(), AnalysisManager::book(), G4HumanPhantomAnalysisManager::book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), Histo::Book(), PurgMagRunAction::Book(), RunAction::Book(), DMXRunAction::Book(), RMC01AnalysisManager::Book(), RunAction::CreateHistogram(), RunAction::CreateNtuple(), Analysis::OpenFile(), Run::Run(), Par02Output::StartAnalysis(), HadrontherapyLet::StoreLetAscii(), G4PhysChemIO::G4Analysis::WriteInto(), and ScoreSpecies::WriteWithAnalysisManager().
virtual G4bool G4VAnalysisManager::OpenFileImpl (const G4String & fileName) protected pure virtual
Implemented in G4RootAnalysisManager, G4CsvAnalysisManager, G4Hdf5AnalysisManager, G4XmlAnalysisManager, and G4RootMpiAnalysisManager.
Referenced by OpenFile().
G4bool G4VAnalysisManager::Plot ()
Definition at line 253 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 253 of file G4VAnalysisManager.cc
References PlotImpl().
virtual G4bool G4VAnalysisManager::PlotImpl () protected pure virtual
Implemented in G4ToolsAnalysisManager.
Referenced by Plot(), and Write().
G4bool G4VAnalysisManager::ScaleH1 (G4int id, G4double factor)
Definition at line 541 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 541 of file G4VAnalysisManager.cc
References fVH1Manager.
Referenced by Run::EndOfRun(), RMC01AnalysisManager::Save(), and RunAction::SaveHisto().
G4bool G4VAnalysisManager::ScaleH2 (G4int id, G4double factor)
Definition at line 547 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 547 of file G4VAnalysisManager.cc
References fVH2Manager.
Referenced by RMC01AnalysisManager::Save().
G4bool G4VAnalysisManager::ScaleH3 (G4int id, G4double factor)
Definition at line 553 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 553 of file G4VAnalysisManager.cc
References fVH3Manager.
G4bool G4VAnalysisManager::ScaleP1 (G4int id, G4double factor)
Definition at line 739 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 739 of file G4VAnalysisManager.cc
References fVP1Manager.
G4bool G4VAnalysisManager::ScaleP2 (G4int id, G4double factor)
Definition at line 745 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 745 of file G4VAnalysisManager.cc
References fVP2Manager.
void G4VAnalysisManager::SetActivation (G4bool activation)
Definition at line 1011 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1011 of file G4VAnalysisManager.cc
References fState, and G4AnalysisManagerState::SetIsActivation().
Referenced by HistoManager::Book(), LXeHistoManager::Book(), ExGflashHistoManager::Book(), RunAction::BookHisto(), G4AnalysisMessenger::SetNewValue(), and HistoManager::Update().
void G4VAnalysisManager::SetBasketEntries (unsigned int basketEntries) virtual
Reimplemented in G4RootAnalysisManager.
Definition at line 854 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 854 of file G4VAnalysisManager.cc
References GetType().
void G4VAnalysisManager::SetBasketSize (unsigned int basketSize) virtual
Reimplemented in G4RootAnalysisManager.
Definition at line 845 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 845 of file G4VAnalysisManager.cc
References GetType().
void G4VAnalysisManager::SetCompressionLevel (G4int level)
Definition at line 283 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 283 of file G4VAnalysisManager.cc
References fState, and G4AnalysisManagerState::SetCompressionLevel().
Referenced by G4AnalysisMessenger::SetNewValue().
void G4VAnalysisManager::SetFileManager (std::shared_ptr< G4VFileManager > fileManager) protected
Definition at line 139 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 139 of file G4VAnalysisManager.cc
References fVFileManager.
Referenced by G4CsvAnalysisManager::G4CsvAnalysisManager(), G4Hdf5AnalysisManager::G4Hdf5AnalysisManager(), G4RootAnalysisManager::G4RootAnalysisManager(), and G4XmlAnalysisManager::G4XmlAnalysisManager().
G4bool G4VAnalysisManager::SetFileName (const G4String & fileName)
Definition at line 265 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 265 of file G4VAnalysisManager.cc
References fVFileManager.
Referenced by HistoManager::Book(), LXeHistoManager::Book(), ExGflashHistoManager::Book(), RunAction::BookHisto(), FCALRunAction::FCALRunAction(), G4FileMessenger::SetNewValue(), and Par02Output::StartAnalysis().
G4bool G4VAnalysisManager::SetFirstH1Id (G4int firstId)
Definition at line 953 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 953 of file G4VAnalysisManager.cc
References fH1HnManager.
Referenced by SetFirstHistoId().
G4bool G4VAnalysisManager::SetFirstH2Id (G4int firstId)
Definition at line 959 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 959 of file G4VAnalysisManager.cc
References fH2HnManager.
Referenced by SetFirstHistoId().
G4bool G4VAnalysisManager::SetFirstH3Id (G4int firstId)
Definition at line 965 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 965 of file G4VAnalysisManager.cc
References fH3HnManager.
Referenced by SetFirstHistoId().
G4bool G4VAnalysisManager::SetFirstHistoId (G4int firstId)
Definition at line 936 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 936 of file G4VAnalysisManager.cc
References SetFirstH1Id(), SetFirstH2Id(), and SetFirstH3Id().
Referenced by GammaRayTelAnalysis::BeginOfRun(), UltraRunAction::BeginOfRunAction(), CCalRunAction::Book(), XrayFluoAnalysisManager::book(), XrayTelAnalysis::book(), DMXRunAction::Book(), RunAction::Book(), RMC01AnalysisManager::Book(), RunAction::BookHisto(), FCALRunAction::FCALRunAction(), and HadrontherapyLet::StoreLetAscii().
G4bool G4VAnalysisManager::SetFirstNtupleColumnId (G4int firstId)
Definition at line 1003 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1003 of file G4VAnalysisManager.cc
References fVNtupleManager, and G4VNtupleManager::SetFirstNtupleColumnId().
G4bool G4VAnalysisManager::SetFirstNtupleId (G4int firstId)
Definition at line 997 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 997 of file G4VAnalysisManager.cc
References fVNtupleManager, and G4BaseAnalysisManager::SetFirstId().
Referenced by CCalRunAction::Book(), AnalysisManager::book(), G4HumanPhantomAnalysisManager::book(), XrayFluoAnalysisManager::book(), PurgMagRunAction::Book(), DMXRunAction::Book(), RunAction::CreateNtuple(), and HadrontherapyLet::StoreLetAscii().
G4bool G4VAnalysisManager::SetFirstP1Id (G4int firstId)
Definition at line 985 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 985 of file G4VAnalysisManager.cc
References fP1HnManager.
Referenced by SetFirstProfileId().
G4bool G4VAnalysisManager::SetFirstP2Id (G4int firstId)
Definition at line 991 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 991 of file G4VAnalysisManager.cc
References fP2HnManager.
Referenced by SetFirstProfileId().
G4bool G4VAnalysisManager::SetFirstProfileId (G4int firstId)
Definition at line 971 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 971 of file G4VAnalysisManager.cc
References SetFirstP1Id(), and SetFirstP2Id().
G4bool G4VAnalysisManager::SetH1 (G4int id, G4int nbins, G4double xmin, G4double xmax, const G4String & unitName = "none", const G4String & fcnName = "none", const G4String & binSchemeName = "linear")
Definition at line 436 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 436 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckNbins(), fVH1Manager, and G4Analysis::kInvalidId.
Referenced by Run::InitFluence(), G4H1Messenger::SetNewValue(), and HistoManager::Update().
G4bool G4VAnalysisManager::SetH1 (G4int id, const std::vector< G4double > & edges, const G4String & unitName = "none", const G4String & fcnName = "none")
Definition at line 448 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 448 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), fVH1Manager, and G4Analysis::kInvalidId.
void G4VAnalysisManager::SetH1Activation (G4bool activation)
Definition at line 1159 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1159 of file G4VAnalysisManager.cc
References fH1HnManager.
Referenced by HistoManager::Book(), LXeHistoManager::Book(), RunAction::BookHisto(), and HistoManager::Update().
void G4VAnalysisManager::SetH1Activation (G4int id, G4bool activation)
Definition at line 1151 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1151 of file G4VAnalysisManager.cc
References fH1HnManager.
void G4VAnalysisManager::SetH1Ascii (G4int id, G4bool ascii)
Definition at line 1167 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1167 of file G4VAnalysisManager.cc
References fH1HnManager.
Referenced by RMC01AnalysisManager::Save().
void G4VAnalysisManager::SetH1Manager (G4VH1Manager * h1Manager) protected
Definition at line 92 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 92 of file G4VAnalysisManager.cc
References fH1HnManager, fMessenger, fVH1Manager, and G4VH1Manager::GetHnManager().
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
void G4VAnalysisManager::SetH1Plotting (G4int id, G4bool plotting)
Definition at line 1173 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1173 of file G4VAnalysisManager.cc
References fH1HnManager.
G4bool G4VAnalysisManager::SetH1Title (G4int id, const G4String & title)
Referenced by G4H1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH1XAxisIsLog (G4int id, G4bool isLog)
Referenced by G4H1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH1XAxisTitle (G4int id, const G4String & title)
Referenced by Par02Output::CreateHistograms(), and G4H1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH1YAxisIsLog (G4int id, G4bool isLog)
Referenced by G4H1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH1YAxisTitle (G4int id, const G4String & title)
Referenced by Par02Output::CreateHistograms(), and G4H1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear")
Definition at line 458 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 458 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckNbins(), fVH2Manager, and G4Analysis::kInvalidId.
Referenced by G4H2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH2 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none")
Definition at line 478 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 478 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), fVH2Manager, and G4Analysis::kInvalidId.
void G4VAnalysisManager::SetH2Activation (G4bool activation)
Definition at line 1187 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1187 of file G4VAnalysisManager.cc
References fH2HnManager.
void G4VAnalysisManager::SetH2Activation (G4int id, G4bool activation)
Definition at line 1179 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1179 of file G4VAnalysisManager.cc
References fH2HnManager.
void G4VAnalysisManager::SetH2Ascii (G4int id, G4bool ascii)
Definition at line 1195 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1195 of file G4VAnalysisManager.cc
References fH2HnManager.
void G4VAnalysisManager::SetH2Manager (G4VH2Manager * h2Manager) protected
Definition at line 100 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 100 of file G4VAnalysisManager.cc
References fH2HnManager, fMessenger, fVH2Manager, and G4VH2Manager::GetHnManager().
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
void G4VAnalysisManager::SetH2Plotting (G4int id, G4bool plotting)
Definition at line 1201 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1201 of file G4VAnalysisManager.cc
References fH2HnManager.
G4bool G4VAnalysisManager::SetH2Title (G4int id, const G4String & title)
Referenced by G4H2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH2XAxisIsLog (G4int id, G4bool isLog)
Referenced by G4H2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH2XAxisTitle (G4int id, const G4String & title)
Referenced by G4H2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH2YAxisIsLog (G4int id, G4bool isLog)
Referenced by G4H2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH2YAxisTitle (G4int id, const G4String & title)
Referenced by G4H2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH2ZAxisIsLog (G4int id, G4bool isLog)
Referenced by G4H2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH2ZAxisTitle (G4int id, const G4String & title)
Referenced by G4H2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH3 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nzbins, G4double zmin, G4double zmax, G4int nybins, G4double ymin, G4double ymax, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear", const G4String & zbinSchemeName = "linear")
Definition at line 492 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 492 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckNbins(), fVH3Manager, and G4Analysis::kInvalidId.
Referenced by G4H3Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH3 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, const std::vector< G4double > & zedges, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none")
Definition at line 522 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 522 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), fVH3Manager, and G4Analysis::kInvalidId.
void G4VAnalysisManager::SetH3Activation (G4bool activation)
Definition at line 1215 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1215 of file G4VAnalysisManager.cc
References fH3HnManager.
void G4VAnalysisManager::SetH3Activation (G4int id, G4bool activation)
Definition at line 1207 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1207 of file G4VAnalysisManager.cc
References fH3HnManager.
void G4VAnalysisManager::SetH3Ascii (G4int id, G4bool ascii)
Definition at line 1223 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1223 of file G4VAnalysisManager.cc
References fH3HnManager.
void G4VAnalysisManager::SetH3Manager (G4VH3Manager * h3Manager) protected
Definition at line 108 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 108 of file G4VAnalysisManager.cc
References fH3HnManager, fMessenger, fVH3Manager, and G4VH3Manager::GetHnManager().
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
void G4VAnalysisManager::SetH3Plotting (G4int id, G4bool plotting)
Definition at line 1229 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1229 of file G4VAnalysisManager.cc
References fH3HnManager.
G4bool G4VAnalysisManager::SetH3Title (G4int id, const G4String & title)
Referenced by G4H3Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH3XAxisIsLog (G4int id, G4bool isLog)
Referenced by G4H3Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH3XAxisTitle (G4int id, const G4String & title)
Referenced by G4H3Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH3YAxisIsLog (G4int id, G4bool isLog)
Referenced by G4H3Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH3YAxisTitle (G4int id, const G4String & title)
Referenced by G4H3Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH3ZAxisIsLog (G4int id, G4bool isLog)
Referenced by G4H3Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetH3ZAxisTitle (G4int id, const G4String & title)
Referenced by G4H3Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetHistoDirectoryName (const G4String & dirName)
Definition at line 271 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 271 of file G4VAnalysisManager.cc
References fVFileManager.
Referenced by RMC01AnalysisManager::Book(), and G4FileMessenger::SetNewValue().
void G4VAnalysisManager::SetNtupleActivation (G4bool activation)
Definition at line 1299 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1299 of file G4VAnalysisManager.cc
References fVNtupleManager, and G4VNtupleManager::SetActivation().
Referenced by G4NtupleMessenger::SetNewValue().
void G4VAnalysisManager::SetNtupleActivation (G4int id, G4bool activation)
Definition at line 1291 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1291 of file G4VAnalysisManager.cc
References fVNtupleManager, and G4VNtupleManager::SetActivation().
G4bool G4VAnalysisManager::SetNtupleDirectoryName (const G4String & dirName)
Definition at line 277 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 277 of file G4VAnalysisManager.cc
References fVFileManager.
Referenced by AnalysisManager::book(), G4HumanPhantomAnalysisManager::book(), RunAction::CreateNtuple(), and G4FileMessenger::SetNewValue().
void G4VAnalysisManager::SetNtupleManager (G4VNtupleManager * ntupleManager) protected
Definition at line 132 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 132 of file G4VAnalysisManager.cc
References fVNtupleManager.
Referenced by G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), G4RootAnalysisManager::CreateNtupleManagers(), G4CsvAnalysisManager::G4CsvAnalysisManager(), G4Hdf5AnalysisManager::G4Hdf5AnalysisManager(), and G4XmlAnalysisManager::G4XmlAnalysisManager().
void G4VAnalysisManager::SetNtupleMerging (G4bool mergeNtuples, G4int nofReducedNtupleFiles = 0) virtual
Reimplemented in G4RootAnalysisManager.
Definition at line 825 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 825 of file G4VAnalysisManager.cc
References GetType().
void G4VAnalysisManager::SetNtupleRowWise (G4bool rowWise, G4bool rowMode = true) virtual
Reimplemented in G4RootAnalysisManager.
Definition at line 835 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 835 of file G4VAnalysisManager.cc
References GetType().
G4bool G4VAnalysisManager::SetP1 (G4int id, G4int nbins, G4double xmin, G4double xmax, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & xbinSchemeName = "linear")
Definition at line 650 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 650 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckNbins(), fVP1Manager, and G4Analysis::kInvalidId.
Referenced by G4P1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP1 (G4int id, const std::vector< G4double > & edges, G4double ymin = 0, G4double ymax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none")
Definition at line 670 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 670 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), G4Analysis::CheckMinMax(), fVP1Manager, and G4Analysis::kInvalidId.
void G4VAnalysisManager::SetP1Activation (G4bool activation)
Definition at line 1243 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1243 of file G4VAnalysisManager.cc
References fP1HnManager.
void G4VAnalysisManager::SetP1Activation (G4int id, G4bool activation)
Definition at line 1235 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1235 of file G4VAnalysisManager.cc
References fP1HnManager.
void G4VAnalysisManager::SetP1Ascii (G4int id, G4bool ascii)
Definition at line 1251 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1251 of file G4VAnalysisManager.cc
References fP1HnManager.
void G4VAnalysisManager::SetP1Manager (G4VP1Manager * p1Manager) protected
Definition at line 116 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 116 of file G4VAnalysisManager.cc
References fMessenger, fP1HnManager, fVP1Manager, and G4VP1Manager::GetHnManager().
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
void G4VAnalysisManager::SetP1Plotting (G4int id, G4bool plotting)
Definition at line 1257 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1257 of file G4VAnalysisManager.cc
References fP1HnManager.
G4bool G4VAnalysisManager::SetP1Title (G4int id, const G4String & title)
Referenced by G4P1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP1XAxisIsLog (G4int id, G4bool isLog)
Referenced by G4P1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP1XAxisTitle (G4int id, const G4String & title)
Referenced by G4P1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP1YAxisIsLog (G4int id, G4bool isLog)
Referenced by G4P1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP1YAxisTitle (G4int id, const G4String & title)
Referenced by G4P1Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP2 (G4int id, G4int nxbins, G4double xmin, G4double xmax, G4int nybins, G4double ymin, G4double ymax, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none", const G4String & xbinSchemeName = "linear", const G4String & ybinSchemeName = "linear")
Definition at line 687 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 687 of file G4VAnalysisManager.cc
References G4Analysis::CheckMinMax(), G4Analysis::CheckNbins(), fVP2Manager, and G4Analysis::kInvalidId.
Referenced by G4P2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP2 (G4int id, const std::vector< G4double > & xedges, const std::vector< G4double > & yedges, G4double zmin = 0, G4double zmax = 0, const G4String & xunitName = "none", const G4String & yunitName = "none", const G4String & zunitName = "none", const G4String & xfcnName = "none", const G4String & yfcnName = "none", const G4String & zfcnName = "none")
Definition at line 715 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 715 of file G4VAnalysisManager.cc
References G4Analysis::CheckEdges(), G4Analysis::CheckMinMax(), fVP2Manager, and G4Analysis::kInvalidId.
void G4VAnalysisManager::SetP2Activation (G4bool activation)
Definition at line 1271 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1271 of file G4VAnalysisManager.cc
References fP2HnManager.
void G4VAnalysisManager::SetP2Activation (G4int id, G4bool activation)
Definition at line 1263 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1263 of file G4VAnalysisManager.cc
References fP2HnManager.
void G4VAnalysisManager::SetP2Ascii (G4int id, G4bool ascii)
Definition at line 1279 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1279 of file G4VAnalysisManager.cc
References fP2HnManager.
void G4VAnalysisManager::SetP2Manager (G4VP2Manager * p2Manager) protected
Definition at line 124 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 124 of file G4VAnalysisManager.cc
References fMessenger, fP2HnManager, fVP2Manager, and G4VP2Manager::GetHnManager().
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
void G4VAnalysisManager::SetP2Plotting (G4int id, G4bool plotting)
Definition at line 1285 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1285 of file G4VAnalysisManager.cc
References fP2HnManager.
G4bool G4VAnalysisManager::SetP2Title (G4int id, const G4String & title)
Referenced by G4P2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP2XAxisIsLog (G4int id, G4bool isLog)
Referenced by G4P2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP2XAxisTitle (G4int id, const G4String & title)
Referenced by G4P2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP2YAxisIsLog (G4int id, G4bool isLog)
Referenced by G4P2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP2YAxisTitle (G4int id, const G4String & title)
Referenced by G4P2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP2ZAxisIsLog (G4int id, G4bool isLog)
Referenced by G4P2Messenger::SetNewValue().
G4bool G4VAnalysisManager::SetP2ZAxisTitle (G4int id, const G4String & title)
Referenced by G4P2Messenger::SetNewValue().
void G4VAnalysisManager::SetPlotManager (std::shared_ptr< G4PlotManager > plotManager) protected
Definition at line 145 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 145 of file G4VAnalysisManager.cc
References fPlotManager.
Referenced by G4ToolsAnalysisManager::G4ToolsAnalysisManager().
void G4VAnalysisManager::SetVerboseLevel (G4int verboseLevel)
Definition at line 1309 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 1309 of file G4VAnalysisManager.cc
References fState, and G4AnalysisManagerState::SetVerboseLevel().
Referenced by CCalRunAction::Book(), AnalysisManager::book(), HistoManager::Book(), LXeHistoManager::Book(), ExGflashHistoManager::Book(), G4HumanPhantomAnalysisManager::book(), XrayFluoAnalysisManager::book(), RunAction::BookHisto(), RunAction::CreateHistogram(), RunAction::CreateNtuple(), G4AnalysisMessenger::SetNewValue(), Par02Output::StartAnalysis(), and HadrontherapyLet::StoreLetAscii().
G4bool G4VAnalysisManager::Write ()
Definition at line 225 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 225 of file G4VAnalysisManager.cc
References IsPlotting(), PlotImpl(), and WriteImpl().
Referenced by Par02Output::EndAnalysis(), HistoManager::EndOfRun(), GammaRayTelAnalysis::EndOfRun(), LXeRunAction::EndOfRunAction(), FCALRunAction::EndOfRunAction(), UltraRunAction::EndOfRunAction(), XrayFluoAnalysisManager::finish(), XrayTelAnalysis::finish(), main(), HistoManager::Save(), Analysis::Save(), G4HumanPhantomAnalysisManager::save(), Histo::Save(), RMC01AnalysisManager::Save(), RunAction::SaveHisto(), HadrontherapyLet::StoreLetAscii(), RunAction::WriteHistogram(), RunAction::WriteNtuple(), and ScoreSpecies::WriteWithAnalysisManager().
G4bool G4VAnalysisManager::WriteAscii (const G4String & fileName) protected
Definition at line 151 of file G4VAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 151 of file G4VAnalysisManager.cc
References G4String::append(), fState, fVH1Manager, fVH2Manager, fVH3Manager, G4Exception(), G4AnalysisManagerState::GetVerboseL1(), G4AnalysisManagerState::GetVerboseL3(), JustWarning, and G4AnalysisVerbose::Message().
Referenced by G4Hdf5AnalysisManager::WriteImpl(), G4XmlAnalysisManager::WriteImpl(), and G4RootAnalysisManager::WriteImpl().
virtual G4bool G4VAnalysisManager::WriteImpl () protected pure virtual
Implemented in G4RootAnalysisManager, G4CsvAnalysisManager, G4Hdf5AnalysisManager, and G4XmlAnalysisManager.
Referenced by Write().
Member Data Documentation
constexpr unsigned int G4VAnalysisManager::fgkDefaultBasketEntries = 4000 static protected
Definition at line 644 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 644 of file G4VAnalysisManager.hh
Referenced by G4RootAnalysisManager::G4RootAnalysisManager().
constexpr unsigned int G4VAnalysisManager::fgkDefaultBasketSize = 32000 static protected
Definition at line 643 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 643 of file G4VAnalysisManager.hh
Referenced by G4RootAnalysisManager::G4RootAnalysisManager().
std::shared_ptr<G4HnManager> G4VAnalysisManager::fH1HnManager private
Definition at line 654 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 654 of file G4VAnalysisManager.hh
Referenced by GetFirstH1Id(), GetNofH1s(), IsActive(), IsAscii(), IsPlotting(), SetFirstH1Id(), SetH1Activation(), SetH1Ascii(), SetH1Manager(), and SetH1Plotting().
std::shared_ptr<G4HnManager> G4VAnalysisManager::fH2HnManager private
Definition at line 655 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 655 of file G4VAnalysisManager.hh
Referenced by GetFirstH2Id(), GetNofH2s(), IsActive(), IsAscii(), IsPlotting(), SetFirstH2Id(), SetH2Activation(), SetH2Ascii(), SetH2Manager(), and SetH2Plotting().
std::shared_ptr<G4HnManager> G4VAnalysisManager::fH3HnManager private
Definition at line 656 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 656 of file G4VAnalysisManager.hh
Referenced by GetFirstH3Id(), GetNofH3s(), IsActive(), IsAscii(), IsPlotting(), SetFirstH3Id(), SetH3Activation(), SetH3Ascii(), SetH3Manager(), and SetH3Plotting().
std::unique_ptr<G4AnalysisMessenger> G4VAnalysisManager::fMessenger private
Definition at line 653 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 653 of file G4VAnalysisManager.hh
Referenced by SetH1Manager(), SetH2Manager(), SetH3Manager(), SetP1Manager(), and SetP2Manager().
std::shared_ptr<G4HnManager> G4VAnalysisManager::fP1HnManager private
Definition at line 657 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 657 of file G4VAnalysisManager.hh
Referenced by GetFirstP1Id(), GetNofP1s(), IsActive(), IsAscii(), IsPlotting(), SetFirstP1Id(), SetP1Activation(), SetP1Ascii(), SetP1Manager(), and SetP1Plotting().
std::shared_ptr<G4HnManager> G4VAnalysisManager::fP2HnManager private
Definition at line 658 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 658 of file G4VAnalysisManager.hh
Referenced by GetFirstP2Id(), GetNofP2s(), IsActive(), IsAscii(), IsPlotting(), SetFirstP2Id(), SetP2Activation(), SetP2Ascii(), SetP2Manager(), and SetP2Plotting().
std::shared_ptr<G4PlotManager> G4VAnalysisManager::fPlotManager protected
Definition at line 649 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 649 of file G4VAnalysisManager.hh
Referenced by G4ToolsAnalysisManager::PlotImpl(), and SetPlotManager().
G4AnalysisManagerState G4VAnalysisManager::fState protected
Definition at line 647 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 647 of file G4VAnalysisManager.hh
Referenced by G4RootAnalysisManager::ClearNtupleManagers(), G4XmlAnalysisManager::CloseFileImpl(), G4RootAnalysisManager::CloseFileImpl(), G4RootMpiAnalysisManager::CreateMpiNtupleManagers(), G4RootAnalysisManager::CreateNtupleManagers(), G4CsvAnalysisManager::G4CsvAnalysisManager(), G4Hdf5AnalysisManager::G4Hdf5AnalysisManager(), G4RootAnalysisManager::G4RootAnalysisManager(), G4ToolsAnalysisManager::G4ToolsAnalysisManager(), G4XmlAnalysisManager::G4XmlAnalysisManager(), GetCompressionLevel(), IsActive(), G4ToolsAnalysisManager::MergeImpl(), G4RootMpiAnalysisManager::OpenFileImpl(), G4Hdf5AnalysisManager::OpenFileImpl(), G4XmlAnalysisManager::OpenFileImpl(), G4RootAnalysisManager::OpenFileImpl(), SetActivation(), SetCompressionLevel(), G4RootMpiAnalysisManager::SetMpiNtupleMergingMode(), G4RootAnalysisManager::SetNtupleMergingMode(), G4RootAnalysisManager::SetNtupleRowWise(), SetVerboseLevel(), WriteAscii(), G4XmlAnalysisManager::WriteImpl(), G4Hdf5AnalysisManager::WriteImpl(), G4CsvAnalysisManager::WriteImpl(), G4RootMpiAnalysisManager::WriteNtuple(), G4RootAnalysisManager::WriteNtuple(), G4CsvAnalysisManager::~G4CsvAnalysisManager(), G4Hdf5AnalysisManager::~G4Hdf5AnalysisManager(), G4RootAnalysisManager::~G4RootAnalysisManager(), and G4XmlAnalysisManager::~G4XmlAnalysisManager().
std::shared_ptr<G4VFileManager> G4VAnalysisManager::fVFileManager protected
Definition at line 648 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 648 of file G4VAnalysisManager.hh
Referenced by GetFileName(), GetHistoDirectoryName(), GetNtupleDirectoryName(), OpenFile(), G4ToolsAnalysisManager::PlotImpl(), SetFileManager(), SetFileName(), SetHistoDirectoryName(), and SetNtupleDirectoryName().
std::unique_ptr<G4VH1Manager> G4VAnalysisManager::fVH1Manager private
Definition at line 659 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 659 of file G4VAnalysisManager.hh
Referenced by CreateH1(), ScaleH1(), SetH1(), SetH1Manager(), and WriteAscii().
std::unique_ptr<G4VH2Manager> G4VAnalysisManager::fVH2Manager private
Definition at line 660 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 660 of file G4VAnalysisManager.hh
Referenced by CreateH2(), ScaleH2(), SetH2(), SetH2Manager(), and WriteAscii().
std::unique_ptr<G4VH3Manager> G4VAnalysisManager::fVH3Manager private
Definition at line 661 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 661 of file G4VAnalysisManager.hh
Referenced by CreateH3(), ScaleH3(), SetH3(), SetH3Manager(), and WriteAscii().
G4VNtupleManager* G4VAnalysisManager::fVNtupleManager private
Definition at line 665 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 665 of file G4VAnalysisManager.hh
Referenced by CreateNtuple(), CreateNtupleDColumn(), CreateNtupleFColumn(), CreateNtupleIColumn(), CreateNtupleSColumn(), FinishNtuple(), GetFirstNtupleColumnId(), GetFirstNtupleId(), GetNofNtuples(), SetFirstNtupleColumnId(), SetFirstNtupleId(), SetNtupleActivation(), SetNtupleManager(), and ~G4VAnalysisManager().
std::unique_ptr<G4VP1Manager> G4VAnalysisManager::fVP1Manager private
Definition at line 662 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 662 of file G4VAnalysisManager.hh
Referenced by CreateP1(), ScaleP1(), SetP1(), and SetP1Manager().
std::unique_ptr<G4VP2Manager> G4VAnalysisManager::fVP2Manager private
Definition at line 663 of file G4VAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 663 of file G4VAnalysisManager.hh
Referenced by CreateP2(), ScaleP2(), SetP2(), and SetP2Manager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4VAnalysisManager.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4VAnalysisManager.cc