ECCE @ EIC Software: G4MesonConstructor Class Reference
G4MesonConstructor Class Reference
#include <geant4/tree/geant4-10.6-release/source/particles/hadrons/mesons/include/G4MesonConstructor.hh>
Public Member Functions
G4MesonConstructor ()
~G4MesonConstructor ()
Static Public Member Functions
static void ConstructParticle ()
Static Protected Member Functions
static void ConstructLightMesons ()
static void ConstructCharmMesons ()
static void ConstructBottomMesons ()
Detailed Description
Definition at line 38 of file G4MesonConstructor.hh.
View newest version in sPHENIX GitHub at line 38 of file G4MesonConstructor.hh
Constructor & Destructor Documentation
G4MesonConstructor::G4MesonConstructor ()
Definition at line 70 of file G4MesonConstructor.cc.
View newest version in sPHENIX GitHub at line 70 of file G4MesonConstructor.cc
G4MesonConstructor::~G4MesonConstructor ()
Definition at line 74 of file G4MesonConstructor.cc.
View newest version in sPHENIX GitHub at line 74 of file G4MesonConstructor.cc
Member Function Documentation
void G4MesonConstructor::ConstructBottomMesons () static protected
Definition at line 111 of file G4MesonConstructor.cc.
View newest version in sPHENIX GitHub at line 111 of file G4MesonConstructor.cc
References G4AntiBMesonZero::AntiBMesonZeroDefinition(), G4AntiBsMesonZero::AntiBsMesonZeroDefinition(), G4BcMesonMinus::BcMesonMinusDefinition(), G4BcMesonPlus::BcMesonPlusDefinition(), G4BMesonMinus::BMesonMinusDefinition(), G4BMesonPlus::BMesonPlusDefinition(), G4BMesonZero::BMesonZeroDefinition(), G4BsMesonZero::BsMesonZeroDefinition(), and G4Upsilon::UpsilonDefinition().
Referenced by ConstructParticle().
void G4MesonConstructor::ConstructCharmMesons () static protected
Definition at line 100 of file G4MesonConstructor.cc.
View newest version in sPHENIX GitHub at line 100 of file G4MesonConstructor.cc
References G4AntiDMesonZero::AntiDMesonZeroDefinition(), G4DMesonMinus::DMesonMinusDefinition(), G4DMesonPlus::DMesonPlusDefinition(), G4DMesonZero::DMesonZeroDefinition(), G4DsMesonMinus::DsMesonMinusDefinition(), G4DsMesonPlus::DsMesonPlusDefinition(), G4Etac::EtacDefinition(), and G4JPsi::JPsiDefinition().
Referenced by ConstructParticle().
void G4MesonConstructor::ConstructLightMesons () static protected
Definition at line 86 of file G4MesonConstructor.cc.
View newest version in sPHENIX GitHub at line 86 of file G4MesonConstructor.cc
References G4AntiKaonZero::AntiKaonZeroDefinition(), G4Eta::EtaDefinition(), G4EtaPrime::EtaPrimeDefinition(), G4KaonMinus::KaonMinusDefinition(), G4KaonPlus::KaonPlusDefinition(), G4KaonZero::KaonZeroDefinition(), G4KaonZeroLong::KaonZeroLongDefinition(), G4KaonZeroShort::KaonZeroShortDefinition(), G4PionMinus::PionMinusDefinition(), G4PionPlus::PionPlusDefinition(), and G4PionZero::PionZeroDefinition().
Referenced by ConstructParticle().
void G4MesonConstructor::ConstructParticle (void) static
Definition at line 79 of file G4MesonConstructor.cc.
View newest version in sPHENIX GitHub at line 79 of file G4MesonConstructor.cc
References ConstructBottomMesons(), ConstructCharmMesons(), and ConstructLightMesons().
Referenced by B03PhysicsList::ConstructAllMesons(), Par02PhysicsList::ConstructMesons(), XrayTelPhysicsList::ConstructMesons(), DMXPhysicsList::ConstructMyHadrons(), LBE::ConstructMyMesons(), EICPhysicsList::ConstructParticle(), GammaKnifeParticles::ConstructParticle(), HadrontherapyParticles::ConstructParticle(), G4ChannelingPhysics::ConstructParticle(), GammaRayTelParticles::ConstructParticle(), Particles::ConstructParticle(), XrayFluoPhysicsList::ConstructParticle(), G4ChargeExchangePhysics::ConstructParticle(), G4HadronDElasticPhysics::ConstructParticle(), G4HadronHElasticPhysics::ConstructParticle(), G4HadronPhysicsQGS_BIC::ConstructParticle(), G4HadronPhysicsFTF_BIC::ConstructParticle(), G4DecayPhysics::ConstructParticle(), G4HadronPhysicsShieldingLEND::ConstructParticle(), G4VHadronPhysics::ConstructParticle(), G4HadronPhysicsFTFP_BERT::ConstructParticle(), G4HadronPhysicsQGSP_BIC::ConstructParticle(), G4HadronPhysicsQGSP_BERT::ConstructParticle(), G4StoppingPhysicsFritiofWithBinaryCascade::ConstructParticle(), G4HadronPhysicsShielding::ConstructParticle(), G4HadronElasticPhysics::ConstructParticle(), G4HadronPhysicsQGSP_BIC_AllHP::ConstructParticle(), G4HadronPhysicsINCLXX::ConstructParticle(), G4StoppingPhysics::ConstructParticle(), G4HadronPhysicsQGSP_BIC_HP::ConstructParticle(), and G4HadronPhysicsFTFQGSP_BERT::ConstructParticle().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/particles/hadrons/mesons/include/G4MesonConstructor.hh
geant4/tree/geant4-10.6-release/source/particles/hadrons/mesons/src/G4MesonConstructor.cc