ECCE @ EIC Software: G4MuMinusCapturePrecompound Class Reference
G4MuMinusCapturePrecompound Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4MuMinusCapturePrecompound.hh>
Public Member Functions
G4MuMinusCapturePrecompound (G4VPreCompoundModel *ptr=0)
~G4MuMinusCapturePrecompound ()
G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
void ModelDescription (std::ostream &outFile) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Private Member Functions
void AddNewParticle (const G4ParticleDefinition *aParticle, G4ThreeVector &direction, G4double kinEnergy)
G4MuMinusCapturePrecompound & operator= (const G4MuMinusCapturePrecompound &right)
G4MuMinusCapturePrecompound (const G4MuMinusCapturePrecompound &)
Private Attributes
G4HadFinalState result
G4Fancy3DNucleus fNucleus
const G4ParticleDefinition * fProton
const G4ParticleDefinition * fNeutron
G4VPreCompoundModel * fPreCompound
G4double fMuMass
G4double fThreshold
G4double fTime
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Detailed Description
Definition at line 64 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 64 of file G4MuMinusCapturePrecompound.hh
Constructor & Destructor Documentation
G4MuMinusCapturePrecompound::G4MuMinusCapturePrecompound (G4VPreCompoundModel * ptr = 0)
Definition at line 63 of file G4MuMinusCapturePrecompound.cc.
View newest version in sPHENIX GitHub at line 63 of file G4MuMinusCapturePrecompound.cc
References G4HadronicInteractionRegistry::FindModel(), fMuMass, fNeutron, fPreCompound, fProton, fThreshold, fTime, G4ParticleDefinition::GetPDGMass(), G4HadronicInteractionRegistry::Instance(), MeV, G4MuonMinus::MuonMinus(), G4Neutron::Neutron(), and G4Proton::Proton().
G4MuMinusCapturePrecompound::~G4MuMinusCapturePrecompound ()
Definition at line 84 of file G4MuMinusCapturePrecompound.cc.
View newest version in sPHENIX GitHub at line 84 of file G4MuMinusCapturePrecompound.cc
References G4HadFinalState::Clear(), and result.
G4MuMinusCapturePrecompound::G4MuMinusCapturePrecompound (const G4MuMinusCapturePrecompound &) private
Member Function Documentation
void G4MuMinusCapturePrecompound::AddNewParticle (const G4ParticleDefinition * aParticle, G4ThreeVector & direction, G4double kinEnergy) inline private
Definition at line 100 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 100 of file G4MuMinusCapturePrecompound.hh
References G4HadFinalState::AddSecondary(), fTime, result, and G4HadSecondary::SetTime().
Referenced by ApplyYourself().
G4HadFinalState * G4MuMinusCapturePrecompound::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Implements G4HadronicInteraction.
Definition at line 92 of file G4MuMinusCapturePrecompound.cc.
View newest version in sPHENIX GitHub at line 92 of file G4MuMinusCapturePrecompound.cc
References A(), AddNewParticle(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4HadFinalState::Clear(), G4VPreCompoundModel::DeExcite(), dir, e, CLHEP::HepLorentzVector::e(), fMuMass, fNeutron, fNucleus, fPreCompound, fProton, fTime, G4cout, G4endl, G4Exception(), G4RandomDirection(), G4UniformRand, G4Nucleus::GetA_asInt(), G4HadProjectile::GetBoundEnergy(), G4ReactionProduct::GetDefinition(), G4HadProjectile::GetGlobalTime(), G4ReactionProduct::GetKineticEnergy(), G4HadronicInteraction::GetModelName(), G4ReactionProduct::GetMomentum(), G4NucleiProperties::GetNuclearMass(), G4Fancy3DNucleus::GetNucleons(), G4HadFinalState::GetNumberOfSecondaries(), G4ParticleDefinition::GetPDGMass(), G4ReactionProduct::GetTOF(), G4Nucleus::GetZ_asInt(), GeV, G4Fancy3DNucleus::Init(), JustWarning, keV, CLHEP::HepLorentzVector::mag(), MeV, n, G4NeutrinoMu::NeutrinoMu(), source.hepunit::neutron_mass_c2, result, CLHEP::HepLorentzVector::set(), G4HadFinalState::SetStatusChange(), stopAndKill, G4Triton::Triton(), CLHEP::Hep3Vector::unit(), CLHEP::HepLorentzVector::vect(), G4HadronicInteraction::verboseLevel, and Z.
void G4MuMinusCapturePrecompound::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Definition at line 262 of file G4MuMinusCapturePrecompound.cc.
View newest version in sPHENIX GitHub at line 262 of file G4MuMinusCapturePrecompound.cc
G4MuMinusCapturePrecompound& G4MuMinusCapturePrecompound::operator= (const G4MuMinusCapturePrecompound & right) private
Member Data Documentation
G4double G4MuMinusCapturePrecompound::fMuMass private
Definition at line 92 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 92 of file G4MuMinusCapturePrecompound.hh
Referenced by ApplyYourself(), and G4MuMinusCapturePrecompound().
const G4ParticleDefinition* G4MuMinusCapturePrecompound::fNeutron private
Definition at line 90 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 90 of file G4MuMinusCapturePrecompound.hh
Referenced by ApplyYourself(), and G4MuMinusCapturePrecompound().
G4Fancy3DNucleus G4MuMinusCapturePrecompound::fNucleus private
Definition at line 88 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 88 of file G4MuMinusCapturePrecompound.hh
Referenced by ApplyYourself().
G4VPreCompoundModel* G4MuMinusCapturePrecompound::fPreCompound private
Definition at line 91 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 91 of file G4MuMinusCapturePrecompound.hh
Referenced by ApplyYourself(), and G4MuMinusCapturePrecompound().
const G4ParticleDefinition* G4MuMinusCapturePrecompound::fProton private
Definition at line 89 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 89 of file G4MuMinusCapturePrecompound.hh
Referenced by ApplyYourself(), and G4MuMinusCapturePrecompound().
G4double G4MuMinusCapturePrecompound::fThreshold private
Definition at line 93 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 93 of file G4MuMinusCapturePrecompound.hh
Referenced by G4MuMinusCapturePrecompound().
G4double G4MuMinusCapturePrecompound::fTime private
Definition at line 94 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 94 of file G4MuMinusCapturePrecompound.hh
Referenced by AddNewParticle(), ApplyYourself(), and G4MuMinusCapturePrecompound().
G4HadFinalState G4MuMinusCapturePrecompound::result private
Definition at line 87 of file G4MuMinusCapturePrecompound.hh.
View newest version in sPHENIX GitHub at line 87 of file G4MuMinusCapturePrecompound.hh
Referenced by AddNewParticle(), ApplyYourself(), and ~G4MuMinusCapturePrecompound().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/include/G4MuMinusCapturePrecompound.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/stopping/src/G4MuMinusCapturePrecompound.cc