ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/global/pyG4RotationMatrix.cc File Reference
pyG4RotationMatrix.cc File Reference
#include <boost/python.hpp>
#include "G4RotationMatrix.hh"
Namespaces
namespace pyG4RotationMatrix
Typedefs
typedef G4RotationMatrix XXX
Functions
void export_G4RotationMatrix ()
Variables
XXX &(XXX::* pyG4RotationMatrix::f1_rotate)(G4double, const G4ThreeVector &) = &XXX::rotate
XXX &(XXX::* pyG4RotationMatrix::f2_rotate)(G4double, const G4ThreeVector *) = &XXX::rotate
Typedef Documentation
typedef G4RotationMatrix XXX
Definition at line 36 of file pyG4RotationMatrix.cc.
View newest version in sPHENIX GitHub at line 36 of file pyG4RotationMatrix.cc
Function Documentation
void export_G4RotationMatrix ()
Definition at line 53 of file pyG4RotationMatrix.cc.
View newest version in sPHENIX GitHub at line 53 of file pyG4RotationMatrix.cc
References CLHEP::HepRotation::axis(), CLHEP::HepRotation::colX(), CLHEP::HepRotation::colY(), CLHEP::HepRotation::colZ(), CLHEP::HepRotation::delta(), pyG4RotationMatrix::f1_rotate, pyG4RotationMatrix::f2_rotate, CLHEP::HepRotation::getAxis(), CLHEP::HepRotation::getDelta(), CLHEP::HepRotation::getPhi(), CLHEP::HepRotation::getPsi(), CLHEP::HepRotation::getTheta(), CLHEP::HepRotation::IDENTITY, CLHEP::HepRotation::inverse(), CLHEP::HepRotation::invert(), CLHEP::HepRotation::isIdentity(), CLHEP::HepRotation::phi(), CLHEP::HepRotation::phiX(), CLHEP::HepRotation::phiY(), CLHEP::HepRotation::phiZ(), CLHEP::HepRotation::psi(), CLHEP::HepRotation::rotateAxes(), CLHEP::HepRotation::rotateX(), CLHEP::HepRotation::rotateY(), CLHEP::HepRotation::rotateZ(), CLHEP::HepRotation::rowX(), CLHEP::HepRotation::rowY(), CLHEP::HepRotation::rowZ(), CLHEP::HepRotation::setAxis(), CLHEP::HepRotation::setDelta(), CLHEP::HepRotation::setPhi(), CLHEP::HepRotation::setPsi(), CLHEP::HepRotation::setTheta(), CLHEP::HepRotation::theta(), CLHEP::HepRotation::thetaX(), CLHEP::HepRotation::thetaY(), CLHEP::HepRotation::thetaZ(), CLHEP::HepRotation::xx(), CLHEP::HepRotation::xy(), CLHEP::HepRotation::xz(), CLHEP::HepRotation::yx(), CLHEP::HepRotation::yy(), CLHEP::HepRotation::yz(), CLHEP::HepRotation::zx(), CLHEP::HepRotation::zy(), and CLHEP::HepRotation::zz().
Referenced by BOOST_PYTHON_MODULE().