ECCE @ EIC Software: F01FieldSetup Class Reference
F01FieldSetup Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01FieldSetup.hh>
Public Member Functions
F01FieldSetup (G4ThreeVector, G4int stepperNum=-1000, G4bool useFSALstepper=false)
F01FieldSetup ()
F01FieldSetup (F01FieldSetup &)=delete
virtual ~F01FieldSetup ()
void SetStepperType (G4int i)
void SetStepper ()
void SetMinStep (G4double s)
void InitialiseAll ()
void CreateStepperAndChordFinder ()
void CreateFSALStepperAndChordFinder ()
void SetFieldValue (G4ThreeVector fieldVector)
void SetFieldZValue (G4double fieldValue)
G4ThreeVector GetConstantFieldValue ()
void SetUseFSALstepper (G4bool val=true)
G4bool GetUseFSALstepper ()
Protected Member Functions
G4VIntegrationDriver * CreateFSALStepperAndDriver ()
G4FieldManager * GetGlobalFieldManager ()
Protected Attributes
G4FieldManager * fFieldManager = nullptr
G4ChordFinder * fChordFinder = nullptr
G4Mag_UsualEqRhs * fEquation = nullptr
G4MagneticField * fMagneticField = nullptr
G4MagIntegratorStepper * fStepper = nullptr
G4bool fUseFSALstepper = false
G4VIntegrationDriver * fDriver = nullptr
G4int fStepperType = -1
G4double fMinStep = -1.0
F01FieldMessenger * fFieldMessenger = nullptr
Detailed Description
Definition at line 56 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 56 of file F01FieldSetup.hh
Constructor & Destructor Documentation
F01FieldSetup::F01FieldSetup (G4ThreeVector fieldVector, G4int stepperNum = -1000, G4bool useFSALstepper = false)
Definition at line 84 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 84 of file F01FieldSetup.cc
References fStepperType, fUseFSALstepper, G4cout, G4endl, and InitialiseAll().
F01FieldSetup::F01FieldSetup ()
Definition at line 118 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 118 of file F01FieldSetup.cc
References G4cout, G4endl, and InitialiseAll().
F01FieldSetup::F01FieldSetup (F01FieldSetup &) delete
F01FieldSetup::~F01FieldSetup () virtual
Definition at line 157 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 157 of file F01FieldSetup.cc
References fChordFinder, fFieldMessenger, fMagneticField, and fStepper.
Member Function Documentation
void F01FieldSetup::CreateFSALStepperAndChordFinder ()
Definition at line 379 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 379 of file F01FieldSetup.cc
References CreateFSALStepperAndDriver(), fChordFinder, fDriver, fMinStep, G4cout, G4endl, and mm.
Referenced by InitialiseAll().
G4VIntegrationDriver * F01FieldSetup::CreateFSALStepperAndDriver () protected
Definition at line 309 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 309 of file F01FieldSetup.cc
References fEquation, fMinStep, fStepper, fStepperType, G4cout, G4endl, and G4VIntegrationDriver::GetStepper().
Referenced by CreateFSALStepperAndChordFinder().
void F01FieldSetup::CreateStepperAndChordFinder ()
Definition at line 167 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 167 of file F01FieldSetup.cc
References fChordFinder, fFieldManager, fMagneticField, fMinStep, fStepper, G4cout, G4endl, mm, G4FieldManager::SetChordFinder(), G4FieldManager::SetDetectorField(), and SetStepper().
Referenced by InitialiseAll(), F01FieldMessenger::SetNewValue(), and SetStepperType().
G4ThreeVector F01FieldSetup::GetConstantFieldValue ()
G4FieldManager * F01FieldSetup::GetGlobalFieldManager () protected
Definition at line 442 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 442 of file F01FieldSetup.cc
References G4TransportationManager::GetFieldManager(), and G4TransportationManager::GetTransportationManager().
Referenced by SetFieldValue().
G4bool F01FieldSetup::GetUseFSALstepper () inline
Definition at line 89 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 89 of file F01FieldSetup.hh
References fUseFSALstepper.
void F01FieldSetup::InitialiseAll ()
Definition at line 131 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 131 of file F01FieldSetup.cc
References CreateFSALStepperAndChordFinder(), CreateStepperAndChordFinder(), fChordFinder, fEquation, fFieldManager, fFieldMessenger, fMagneticField, fMinStep, fUseFSALstepper, G4cout, G4endl, G4TransportationManager::GetFieldManager(), G4TransportationManager::GetTransportationManager(), mm, G4FieldManager::SetChordFinder(), and G4FieldManager::SetDetectorField().
Referenced by F01FieldSetup().
void F01FieldSetup::SetFieldValue (G4ThreeVector fieldVector)
Definition at line 407 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 407 of file F01FieldSetup.cc
References fEquation, fMagneticField, G4cout, G4endl, gauss, GetGlobalFieldManager(), G4FieldManager::SetDetectorField(), and G4EquationOfMotion::SetFieldObj().
Referenced by SetFieldZValue(), and F01FieldMessenger::SetNewValue().
void F01FieldSetup::SetFieldZValue (G4double fieldValue)
Definition at line 398 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 398 of file F01FieldSetup.cc
References SetFieldValue().
Referenced by F01FieldMessenger::SetNewValue().
void F01FieldSetup::SetMinStep (G4double s) inline
Definition at line 74 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 74 of file F01FieldSetup.hh
References fMinStep.
Referenced by F01FieldMessenger::SetNewValue().
void F01FieldSetup::SetStepper ()
Definition at line 189 of file F01FieldSetup.cc.
View newest version in sPHENIX GitHub at line 189 of file F01FieldSetup.cc
References fEquation, fStepper, fStepperType, G4cout, G4endl, and kTsitouras45.
Referenced by CreateStepperAndChordFinder().
void F01FieldSetup::SetStepperType (G4int i) inline
Definition at line 69 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 69 of file F01FieldSetup.hh
References CreateStepperAndChordFinder(), and fStepperType.
Referenced by F01FieldMessenger::SetNewValue().
void F01FieldSetup::SetUseFSALstepper (G4bool val = true) inline
Definition at line 88 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 88 of file F01FieldSetup.hh
References fUseFSALstepper.
Member Data Documentation
G4ChordFinder* F01FieldSetup::fChordFinder = nullptr protected
Definition at line 101 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 101 of file F01FieldSetup.hh
Referenced by CreateFSALStepperAndChordFinder(), CreateStepperAndChordFinder(), InitialiseAll(), and ~F01FieldSetup().
G4VIntegrationDriver* F01FieldSetup::fDriver = nullptr protected
Definition at line 107 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 107 of file F01FieldSetup.hh
Referenced by CreateFSALStepperAndChordFinder().
G4Mag_UsualEqRhs* F01FieldSetup::fEquation = nullptr protected
Definition at line 102 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 102 of file F01FieldSetup.hh
Referenced by CreateFSALStepperAndDriver(), InitialiseAll(), SetFieldValue(), and SetStepper().
G4FieldManager* F01FieldSetup::fFieldManager = nullptr protected
Definition at line 100 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 100 of file F01FieldSetup.hh
Referenced by CreateStepperAndChordFinder(), and InitialiseAll().
F01FieldMessenger* F01FieldSetup::fFieldMessenger = nullptr protected
Definition at line 112 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 112 of file F01FieldSetup.hh
Referenced by InitialiseAll(), and ~F01FieldSetup().
G4MagneticField* F01FieldSetup::fMagneticField = nullptr protected
Definition at line 103 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 103 of file F01FieldSetup.hh
Referenced by CreateStepperAndChordFinder(), InitialiseAll(), SetFieldValue(), and ~F01FieldSetup().
G4double F01FieldSetup::fMinStep = -1.0 protected
Definition at line 110 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 110 of file F01FieldSetup.hh
Referenced by CreateFSALStepperAndChordFinder(), CreateFSALStepperAndDriver(), CreateStepperAndChordFinder(), InitialiseAll(), and SetMinStep().
G4MagIntegratorStepper* F01FieldSetup::fStepper = nullptr protected
Definition at line 105 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 105 of file F01FieldSetup.hh
Referenced by CreateFSALStepperAndDriver(), CreateStepperAndChordFinder(), SetStepper(), and ~F01FieldSetup().
G4int F01FieldSetup::fStepperType = -1 protected
Definition at line 108 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 108 of file F01FieldSetup.hh
Referenced by CreateFSALStepperAndDriver(), F01FieldSetup(), SetStepper(), and SetStepperType().
G4bool F01FieldSetup::fUseFSALstepper = false protected
Definition at line 106 of file F01FieldSetup.hh.
View newest version in sPHENIX GitHub at line 106 of file F01FieldSetup.hh
Referenced by F01FieldSetup(), GetUseFSALstepper(), InitialiseAll(), and SetUseFSALstepper().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field01/include/F01FieldSetup.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field01/src/F01FieldSetup.cc