ECCE @ EIC Software: G4VParticipants Class Reference
G4VParticipants Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/include/G4VParticipants.hh>
Public Member Functions
G4VParticipants ()
G4VParticipants (const G4VParticipants &right)
virtual ~G4VParticipants ()
const G4VParticipants & operator= (const G4VParticipants &right)
G4bool operator== (const G4VParticipants &right) const
G4bool operator!= (const G4VParticipants &right) const
virtual void Init (G4int theZ, G4int theA)
virtual void SetNucleus (G4V3DNucleus *aNucleus)
virtual G4V3DNucleus * GetWoundedNucleus () const
virtual void InitProjectileNucleus (G4int theZ, G4int theA)
virtual void SetProjectileNucleus (G4V3DNucleus *aNucleus)
virtual G4V3DNucleus * GetProjectileNucleus () const
Public Attributes
G4V3DNucleus * theNucleus
G4V3DNucleus * theProjectileNucleus
Detailed Description
Definition at line 47 of file G4VParticipants.hh.
View newest version in sPHENIX GitHub at line 47 of file G4VParticipants.hh
Constructor & Destructor Documentation
G4VParticipants::G4VParticipants ()
Definition at line 43 of file G4VParticipants.cc.
View newest version in sPHENIX GitHub at line 43 of file G4VParticipants.cc
G4VParticipants::G4VParticipants (const G4VParticipants & right)
G4VParticipants::~G4VParticipants () virtual
Definition at line 48 of file G4VParticipants.cc.
View newest version in sPHENIX GitHub at line 48 of file G4VParticipants.cc
References theNucleus, and theProjectileNucleus.
Member Function Documentation
G4V3DNucleus * G4VParticipants::GetProjectileNucleus () const inline virtual
Reimplemented in G4QGSParticipants.
Definition at line 79 of file G4VParticipants.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VParticipants.hh
References theProjectileNucleus.
Referenced by G4FTFModel::GetProjectileNucleus().
G4V3DNucleus * G4VParticipants::GetWoundedNucleus () const inline virtual
Definition at line 74 of file G4VParticipants.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VParticipants.hh
References theNucleus.
Referenced by G4FTFModel::GetTargetNucleus(), and G4FTFModel::GetWoundedNucleus().
void G4VParticipants::Init (G4int theZ, G4int theA) virtual
Definition at line 56 of file G4VParticipants.cc.
View newest version in sPHENIX GitHub at line 56 of file G4VParticipants.cc
References G4V3DNucleus::Init(), G4V3DNucleus::SortNucleonsIncZ(), and theNucleus.
Referenced by G4FTFModel::Init().
void G4VParticipants::InitProjectileNucleus (G4int theZ, G4int theA) virtual
Definition at line 70 of file G4VParticipants.cc.
View newest version in sPHENIX GitHub at line 70 of file G4VParticipants.cc
References G4V3DNucleus::Init(), G4V3DNucleus::SortNucleonsDecZ(), and theProjectileNucleus.
Referenced by G4FTFModel::Init().
G4bool G4VParticipants::operator!= (const G4VParticipants & right) const
const G4VParticipants& G4VParticipants::operator= (const G4VParticipants & right)
G4bool G4VParticipants::operator== (const G4VParticipants & right) const
void G4VParticipants::SetNucleus (G4V3DNucleus * aNucleus) virtual
Definition at line 64 of file G4VParticipants.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VParticipants.cc
References theNucleus.
void G4VParticipants::SetProjectileNucleus (G4V3DNucleus * aNucleus) virtual
Definition at line 78 of file G4VParticipants.cc.
View newest version in sPHENIX GitHub at line 78 of file G4VParticipants.cc
References theProjectileNucleus.
Referenced by G4QGSParticipants::BuildInteractions(), and G4FTFModel::Init().
Member Data Documentation
G4V3DNucleus* G4VParticipants::theNucleus
Definition at line 66 of file G4VParticipants.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VParticipants.hh
Referenced by G4QGSParticipants::BuildInteractions(), G4QGSParticipants::DoLorentzBoost(), G4FTFParticipants::GetList(), G4QGSParticipants::GetList(), G4QGSParticipants::GetTargetNucleus(), GetWoundedNucleus(), Init(), G4QGSParticipants::PrepareInitialState(), G4QGSParticipants::ReggeonCascade(), G4GammaParticipants::SelectInteractions(), G4QGSParticipants::SelectInteractions(), SetNucleus(), G4QGSParticipants::StoreInvolvedNucleon(), and ~G4VParticipants().
G4V3DNucleus* G4VParticipants::theProjectileNucleus
Definition at line 67 of file G4VParticipants.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VParticipants.hh
Referenced by G4FTFParticipants::GetList(), GetProjectileNucleus(), G4FTFModel::Init(), InitProjectileNucleus(), SetProjectileNucleus(), and ~G4VParticipants().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/include/G4VParticipants.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/parton_string/management/src/G4VParticipants.cc