ECCE @ EIC Software: G4VhElectronicStoppingPower Class Reference
G4VhElectronicStoppingPower Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VhElectronicStoppingPower.hh>
Public Member Functions
G4VhElectronicStoppingPower ()
virtual ~G4VhElectronicStoppingPower ()
virtual G4double StoppingPower (const G4Material *material, G4double kineticEnergy)=0
virtual G4bool HasMaterial (const G4Material *material)=0
virtual G4double ElectronicStoppingPower (G4double z, G4double kineticEnergy) const =0
Protected Member Functions
G4double HeEffChargeSquare (const G4double z, const G4double kineticEnergyHe) const
G4double GetHeMassAMU () const
Private Member Functions
G4VhElectronicStoppingPower (G4VhElectronicStoppingPower &)
G4VhElectronicStoppingPower & operator= (const G4VhElectronicStoppingPower &right)
Private Attributes
const G4double theHeMassAMU
Detailed Description
Definition at line 59 of file G4VhElectronicStoppingPower.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VhElectronicStoppingPower.hh
Constructor & Destructor Documentation
G4VhElectronicStoppingPower::G4VhElectronicStoppingPower ()
Definition at line 58 of file G4VhElectronicStoppingPower.cc.
View newest version in sPHENIX GitHub at line 58 of file G4VhElectronicStoppingPower.cc
G4VhElectronicStoppingPower::~G4VhElectronicStoppingPower () virtual
Definition at line 64 of file G4VhElectronicStoppingPower.cc.
View newest version in sPHENIX GitHub at line 64 of file G4VhElectronicStoppingPower.cc
G4VhElectronicStoppingPower::G4VhElectronicStoppingPower (G4VhElectronicStoppingPower &) private
Member Function Documentation
virtual G4double G4VhElectronicStoppingPower::ElectronicStoppingPower (G4double z, G4double kineticEnergy) const pure virtual
Implemented in G4hICRU49p, G4hZiegler1985p, G4hICRU49He, and G4hSRIM2000p.
Referenced by G4hParametrisedLossModel::StoppingPower().
G4double G4VhElectronicStoppingPower::GetHeMassAMU () const inline protected
Definition at line 85 of file G4VhElectronicStoppingPower.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VhElectronicStoppingPower.hh
References theHeMassAMU.
Referenced by HeEffChargeSquare().
virtual G4bool G4VhElectronicStoppingPower::HasMaterial (const G4Material * material) pure virtual
Implemented in G4hICRU49p, G4hZiegler1985p, G4hICRU49He, and G4hSRIM2000p.
Referenced by G4hParametrisedLossModel::StoppingPower().
G4double G4VhElectronicStoppingPower::HeEffChargeSquare (const G4double z, const G4double kineticEnergyHe) const protected
Definition at line 69 of file G4VhElectronicStoppingPower.cc.
View newest version in sPHENIX GitHub at line 69 of file G4VhElectronicStoppingPower.cc
References c, e, G4Exp(), GetHeMassAMU(), keV, max, w, x, y, and z.
Referenced by G4hICRU49He::ElectronicStoppingPower(), and G4hICRU49He::StoppingPower().
G4VhElectronicStoppingPower& G4VhElectronicStoppingPower::operator= (const G4VhElectronicStoppingPower & right) private
virtual G4double G4VhElectronicStoppingPower::StoppingPower (const G4Material * material, G4double kineticEnergy) pure virtual
Implemented in G4hICRU49p, G4hZiegler1985p, G4hICRU49He, and G4hSRIM2000p.
Referenced by G4hParametrisedLossModel::StoppingPower().
Member Data Documentation
const G4double G4VhElectronicStoppingPower::theHeMassAMU private
Definition at line 95 of file G4VhElectronicStoppingPower.hh.
View newest version in sPHENIX GitHub at line 95 of file G4VhElectronicStoppingPower.hh
Referenced by GetHeMassAMU().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4VhElectronicStoppingPower.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4VhElectronicStoppingPower.cc