ECCE @ EIC Software: G4GeomTestVolume Class Reference
G4GeomTestVolume Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4GeomTestVolume.hh>
Public Member Functions
G4GeomTestVolume (G4VPhysicalVolume *theTarget, G4double theTolerance=0.0, G4int numberOfPoints=10000, G4bool theVerbosity=true)
~G4GeomTestVolume ()
G4double GetTolerance () const
void SetTolerance (G4double tolerance)
G4int GetResolution () const
void SetResolution (G4int points)
G4bool GetVerbosity () const
void SetVerbosity (G4bool verbosity)
G4int GetErrorsThreshold () const
void SetErrorsThreshold (G4int max)
void TestRecursiveOverlap (G4int sLevel=0, G4int depth=-1)
Private Attributes
G4VPhysicalVolume * target
G4double tolerance
G4int resolution
G4int maxErr = 1
G4bool verbosity
Detailed Description
Definition at line 43 of file G4GeomTestVolume.hh.
View newest version in sPHENIX GitHub at line 43 of file G4GeomTestVolume.hh
Constructor & Destructor Documentation
G4GeomTestVolume::G4GeomTestVolume (G4VPhysicalVolume * theTarget, G4double theTolerance = 0.0, G4int numberOfPoints = 10000, G4bool theVerbosity = true)
Definition at line 42 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 42 of file G4GeomTestVolume.cc
G4GeomTestVolume::~G4GeomTestVolume ()
Definition at line 53 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 53 of file G4GeomTestVolume.cc
Member Function Documentation
G4int G4GeomTestVolume::GetErrorsThreshold () const
Definition at line 106 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 106 of file G4GeomTestVolume.cc
References maxErr.
G4int G4GeomTestVolume::GetResolution () const
Definition at line 74 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 74 of file G4GeomTestVolume.cc
References resolution.
G4double G4GeomTestVolume::GetTolerance () const
Definition at line 58 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 58 of file G4GeomTestVolume.cc
References tolerance.
G4bool G4GeomTestVolume::GetVerbosity () const
Definition at line 90 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 90 of file G4GeomTestVolume.cc
References verbosity.
void G4GeomTestVolume::SetErrorsThreshold (G4int max)
Definition at line 114 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 114 of file G4GeomTestVolume.cc
References max, and maxErr.
Referenced by G4GeometryMessenger::SetNewValue(), and TestRecursiveOverlap().
void G4GeomTestVolume::SetResolution (G4int points)
Definition at line 82 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 82 of file G4GeomTestVolume.cc
References resolution.
Referenced by G4GeometryMessenger::SetNewValue().
void G4GeomTestVolume::SetTolerance (G4double tolerance)
Definition at line 66 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 66 of file G4GeomTestVolume.cc
References tolerance.
Referenced by G4GeometryMessenger::SetNewValue().
void G4GeomTestVolume::SetVerbosity (G4bool verbosity)
Definition at line 98 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 98 of file G4GeomTestVolume.cc
References verbosity.
Referenced by G4GeometryMessenger::SetNewValue().
void G4GeomTestVolume::TestRecursiveOverlap (G4int sLevel = 0, G4int depth = -1)
Definition at line 122 of file G4GeomTestVolume.cc.
View newest version in sPHENIX GitHub at line 122 of file G4GeomTestVolume.cc
References G4LogicalVolume::GetDaughter(), G4LogicalVolume::GetNoDaughters(), maxErr, resolution, SetErrorsThreshold(), TestRecursiveOverlap(), tolerance, and verbosity.
Referenced by G4GeometryMessenger::RecursiveOverlapTest(), and TestRecursiveOverlap().
Member Data Documentation
G4int G4GeomTestVolume::maxErr = 1 private
Definition at line 79 of file G4GeomTestVolume.hh.
View newest version in sPHENIX GitHub at line 79 of file G4GeomTestVolume.hh
Referenced by GetErrorsThreshold(), SetErrorsThreshold(), and TestRecursiveOverlap().
G4int G4GeomTestVolume::resolution private
Definition at line 78 of file G4GeomTestVolume.hh.
View newest version in sPHENIX GitHub at line 78 of file G4GeomTestVolume.hh
Referenced by GetResolution(), SetResolution(), and TestRecursiveOverlap().
G4VPhysicalVolume* G4GeomTestVolume::target private
Definition at line 76 of file G4GeomTestVolume.hh.
View newest version in sPHENIX GitHub at line 76 of file G4GeomTestVolume.hh
G4double G4GeomTestVolume::tolerance private
Definition at line 77 of file G4GeomTestVolume.hh.
View newest version in sPHENIX GitHub at line 77 of file G4GeomTestVolume.hh
Referenced by GetTolerance(), SetTolerance(), and TestRecursiveOverlap().
G4bool G4GeomTestVolume::verbosity private
Definition at line 80 of file G4GeomTestVolume.hh.
View newest version in sPHENIX GitHub at line 80 of file G4GeomTestVolume.hh
Referenced by GetVerbosity(), SetVerbosity(), and TestRecursiveOverlap().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/navigation/include/G4GeomTestVolume.hh
geant4/tree/geant4-10.6-release/source/geometry/navigation/src/G4GeomTestVolume.cc