ECCE @ EIC Software: B2bDetectorConstruction Class Reference
B2bDetectorConstruction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/include/B2bDetectorConstruction.hh>
Public Member Functions
B2bDetectorConstruction ()
virtual ~B2bDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
void SetTargetMaterial (G4String)
void SetChamberMaterial (G4String)
void SetMaxStep (G4double)
void SetCheckOverlaps (G4bool)
B2bDetectorConstruction ()
virtual ~B2bDetectorConstruction ()
virtual G4VPhysicalVolume * Construct ()
virtual void ConstructSDandField ()
void SetTargetMaterial (G4String)
void SetChamberMaterial (G4String)
void SetMaxStep (G4double)
void SetCheckOverlaps (G4bool)
Public Member Functions inherited from G4VUserDetectorConstruction
G4VUserDetectorConstruction ()
virtual ~G4VUserDetectorConstruction ()
virtual void CloneSD ()
virtual void CloneF ()
void RegisterParallelWorld (G4VUserParallelWorld *)
G4int ConstructParallelGeometries ()
void ConstructParallelSD ()
G4int GetNumberOfParallelWorld () const
G4VUserParallelWorld * GetParallelWorld (G4int i) const
Private Member Functions
void DefineMaterials ()
G4VPhysicalVolume * DefineVolumes ()
void DefineMaterials ()
G4VPhysicalVolume * DefineVolumes ()
Private Attributes
G4LogicalVolume * fLogicTarget
G4LogicalVolume * fLogicChamber
G4Material * fTargetMaterial
G4Material * fChamberMaterial
G4UserLimits * fStepLimit
B2bDetectorMessenger * fMessenger
G4bool fCheckOverlaps
Static Private Attributes
static G4ThreadLocal
G4GlobalMagFieldMessenger * fMagFieldMessenger = 0
Additional Inherited Members
Protected Member Functions inherited from G4VUserDetectorConstruction
void SetSensitiveDetector (const G4String &logVolName, G4VSensitiveDetector *aSD, G4bool multi=false)
void SetSensitiveDetector (G4LogicalVolume *logVol, G4VSensitiveDetector *aSD)
Detailed Description
Detector construction class to define materials, geometry and global uniform magnetic field.
Definition at line 48 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 48 of file B2bDetectorConstruction.hh
Constructor & Destructor Documentation
B2bDetectorConstruction::B2bDetectorConstruction ()
Definition at line 62 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 62 of file B2bDetectorConstruction.cc
References fMessenger.
B2bDetectorConstruction::~B2bDetectorConstruction () virtual
Definition at line 74 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 74 of file B2bDetectorConstruction.cc
References fMessenger, and fStepLimit.
B2bDetectorConstruction::B2bDetectorConstruction ()
virtual B2bDetectorConstruction::~B2bDetectorConstruction () virtual
Member Function Documentation
G4VPhysicalVolume * B2bDetectorConstruction::Construct (void) virtual
Implements G4VUserDetectorConstruction.
Definition at line 82 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 82 of file B2bDetectorConstruction.cc
References DefineMaterials(), and DefineVolumes().
virtual G4VPhysicalVolume* B2bDetectorConstruction::Construct () virtual
Implements G4VUserDetectorConstruction.
void B2bDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
Definition at line 279 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 279 of file B2bDetectorConstruction.cc
References G4SDManager::AddNewDetector(), fLogicChamber, fMagFieldMessenger, G4SDManager::GetSDMpointer(), G4AutoDelete::Register(), G4VUserDetectorConstruction::SetSensitiveDetector(), and G4GlobalMagFieldMessenger::SetVerboseLevel().
virtual void B2bDetectorConstruction::ConstructSDandField () virtual
Reimplemented from G4VUserDetectorConstruction.
void B2bDetectorConstruction::DefineMaterials () private
Definition at line 93 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 93 of file B2bDetectorConstruction.cc
References fChamberMaterial, G4NistManager::FindOrBuildMaterial(), fTargetMaterial, G4cout, G4endl, G4Material::GetMaterialTable(), and G4NistManager::Instance().
Referenced by Construct().
void B2bDetectorConstruction::DefineMaterials () private
G4VPhysicalVolume* B2bDetectorConstruction::DefineVolumes () private
G4VPhysicalVolume * B2bDetectorConstruction::DefineVolumes () private
Set additional contraints on the track, with G4UserSpecialCuts
G4double maxLength = 2*trackerLength, maxTime = 0.1*ns, minEkin = 10*MeV; trackerLV->SetUserLimits(new G4UserLimits(maxStep, maxLength, maxTime, minEkin));
Definition at line 114 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 114 of file B2bDetectorConstruction.cc
References cm, deg, fChamberMaterial, fCheckOverlaps, fLogicChamber, fLogicTarget, fStepLimit, fTargetMaterial, G4cout, G4endl, G4GeometryTolerance::GetInstance(), G4GeometryManager::GetInstance(), G4Material::GetMaterial(), G4Material::GetName(), G4GeometryTolerance::GetSurfaceTolerance(), kZAxis, mm, G4LogicalVolume::SetUserLimits(), G4LogicalVolume::SetVisAttributes(), and G4GeometryManager::SetWorldMaximumExtent().
Referenced by Construct().
void B2bDetectorConstruction::SetChamberMaterial (G4String materialName)
Definition at line 327 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 327 of file B2bDetectorConstruction.cc
References fChamberMaterial, G4NistManager::FindOrBuildMaterial(), fLogicChamber, G4cout, G4endl, G4NistManager::Instance(), and G4LogicalVolume::SetMaterial().
Referenced by B2bDetectorMessenger::SetNewValue().
void B2bDetectorConstruction::SetChamberMaterial (G4String)
void B2bDetectorConstruction::SetCheckOverlaps (G4bool)
void B2bDetectorConstruction::SetCheckOverlaps (G4bool)
void B2bDetectorConstruction::SetMaxStep (G4double maxStep)
Definition at line 352 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 352 of file B2bDetectorConstruction.cc
References fStepLimit, and G4UserLimits::SetMaxAllowedStep().
Referenced by B2bDetectorMessenger::SetNewValue().
void B2bDetectorConstruction::SetMaxStep (G4double)
void B2bDetectorConstruction::SetTargetMaterial (G4String materialName)
Definition at line 302 of file B2bDetectorConstruction.cc.
View newest version in sPHENIX GitHub at line 302 of file B2bDetectorConstruction.cc
References G4NistManager::FindOrBuildMaterial(), fLogicTarget, fTargetMaterial, G4cout, G4endl, G4NistManager::Instance(), and G4LogicalVolume::SetMaterial().
Referenced by B2bDetectorMessenger::SetNewValue().
void B2bDetectorConstruction::SetTargetMaterial (G4String)
Member Data Documentation
G4Material * B2bDetectorConstruction::fChamberMaterial private
Definition at line 74 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 74 of file B2bDetectorConstruction.hh
Referenced by DefineMaterials(), DefineVolumes(), and SetChamberMaterial().
G4bool B2bDetectorConstruction::fCheckOverlaps private
Definition at line 83 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 83 of file B2bDetectorConstruction.hh
Referenced by DefineVolumes().
G4LogicalVolume * B2bDetectorConstruction::fLogicChamber private
Definition at line 71 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 71 of file B2bDetectorConstruction.hh
Referenced by ConstructSDandField(), DefineVolumes(), and SetChamberMaterial().
G4LogicalVolume * B2bDetectorConstruction::fLogicTarget private
Definition at line 70 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 70 of file B2bDetectorConstruction.hh
Referenced by DefineVolumes(), and SetTargetMaterial().
G4ThreadLocal G4GlobalMagFieldMessenger * B2bDetectorConstruction::fMagFieldMessenger = 0 static private
Definition at line 80 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 80 of file B2bDetectorConstruction.hh
Referenced by ConstructSDandField().
B2bDetectorMessenger * B2bDetectorConstruction::fMessenger private
Definition at line 78 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 78 of file B2bDetectorConstruction.hh
Referenced by B2bDetectorConstruction(), and ~B2bDetectorConstruction().
G4UserLimits * B2bDetectorConstruction::fStepLimit private
Definition at line 76 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 76 of file B2bDetectorConstruction.hh
Referenced by DefineVolumes(), SetMaxStep(), and ~B2bDetectorConstruction().
G4Material * B2bDetectorConstruction::fTargetMaterial private
Definition at line 73 of file B2bDetectorConstruction.hh.
View newest version in sPHENIX GitHub at line 73 of file B2bDetectorConstruction.hh
Referenced by DefineMaterials(), DefineVolumes(), and SetTargetMaterial().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/include/B2bDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/include/B2bDetectorConstruction.hh
geant4/tree/geant4-10.6-release/examples/basic/B2/B2b/src/B2bDetectorConstruction.cc
geant4/tree/geant4-10.6-release/examples/extended/parallel/TBB/B2b/src/B2bDetectorConstruction.cc