ECCE @ EIC Software: B1RunAction Class Reference
B1RunAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/basic/B1/include/B1RunAction.hh>
Public Member Functions
B1RunAction ()
virtual ~B1RunAction ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
void AddEdep (G4double edep)
B1RunAction ()
virtual ~B1RunAction ()
virtual G4Run * GenerateRun ()
virtual void BeginOfRunAction (const G4Run *)
virtual void EndOfRunAction (const G4Run *)
Public Member Functions inherited from G4UserRunAction
G4UserRunAction ()
virtual ~G4UserRunAction ()
virtual void SetMaster (G4bool val=true)
G4bool IsMaster () const
Private Attributes
G4Accumulable< G4double > fEdep
G4Accumulable< G4double > fEdep2
Additional Inherited Members
Protected Attributes inherited from G4UserRunAction
G4bool isMaster
Detailed Description
Run action class
In EndOfRunAction(), it calculates the dose in the selected volume from the energy deposit accumulated via stepping and event actions. The computed dose is then printed on the screen.
Definition at line 45 of file B1RunAction.hh.
View newest version in sPHENIX GitHub at line 45 of file B1RunAction.hh
Constructor & Destructor Documentation
B1RunAction::B1RunAction ()
Definition at line 45 of file B1RunAction.cc.
View newest version in sPHENIX GitHub at line 45 of file B1RunAction.cc
References fEdep, fEdep2, gray, G4AccumulableManager::Instance(), microgray, milligray, and G4AccumulableManager::RegisterAccumulable().
B1RunAction::~B1RunAction () virtual
Definition at line 70 of file B1RunAction.cc.
View newest version in sPHENIX GitHub at line 70 of file B1RunAction.cc
B1RunAction::B1RunAction ()
virtual B1RunAction::~B1RunAction () virtual
Member Function Documentation
void B1RunAction::AddEdep (G4double edep)
Definition at line 155 of file B1RunAction.cc.
View newest version in sPHENIX GitHub at line 155 of file B1RunAction.cc
References edep, fEdep, and fEdep2.
Referenced by B1EventAction::EndOfEventAction().
virtual void B1RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void B1RunAction::BeginOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
Definition at line 75 of file B1RunAction.cc.
View newest version in sPHENIX GitHub at line 75 of file B1RunAction.cc
References G4RunManager::GetRunManager(), G4AccumulableManager::Instance(), G4AccumulableManager::Reset(), and G4RunManager::SetRandomNumberStore().
virtual void B1RunAction::EndOfRunAction (const G4Run *) virtual
Reimplemented from G4UserRunAction.
void B1RunAction::EndOfRunAction (const G4Run * run) virtual
Reimplemented from G4UserRunAction.
Definition at line 88 of file B1RunAction.cc.
View newest version in sPHENIX GitHub at line 88 of file B1RunAction.cc
References dose, edep, fEdep, fEdep2, G4BestUnit, G4cout, G4endl, G4LogicalVolume::GetMass(), G4Run::GetNumberOfEvent(), G4ParticleGun::GetParticleDefinition(), G4ParticleGun::GetParticleEnergy(), B1PrimaryGeneratorAction::GetParticleGun(), G4ParticleDefinition::GetParticleName(), G4RunManager::GetRunManager(), B1DetectorConstruction::GetScoringVolume(), G4RunManager::GetUserDetectorConstruction(), G4RunManager::GetUserPrimaryGeneratorAction(), G4Accumulable< T >::GetValue(), G4AccumulableManager::Instance(), G4UserRunAction::IsMaster(), mass, and G4AccumulableManager::Merge().
G4Run * B1RunAction::GenerateRun (void) virtual
Reimplemented from G4UserRunAction.
Definition at line 66 of file B1RunAction.cc.
View newest version in sPHENIX GitHub at line 66 of file B1RunAction.cc
Member Data Documentation
G4Accumulable<G4double> B1RunAction::fEdep private
Definition at line 58 of file B1RunAction.hh.
View newest version in sPHENIX GitHub at line 58 of file B1RunAction.hh
Referenced by AddEdep(), B1RunAction(), and EndOfRunAction().
G4Accumulable<G4double> B1RunAction::fEdep2 private
Definition at line 59 of file B1RunAction.hh.
View newest version in sPHENIX GitHub at line 59 of file B1RunAction.hh
Referenced by AddEdep(), B1RunAction(), and EndOfRunAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/basic/B1/include/B1RunAction.hh
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/include/B1RunAction.hh
geant4/tree/geant4-10.6-release/examples/basic/B1/src/B1RunAction.cc
geant4/tree/geant4-10.6-release/examples/extended/visualization/userVisAction/src/B1RunAction.cc