ECCE @ EIC Software: F04DetectorMessenger Class Reference
F04DetectorMessenger Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04DetectorMessenger.hh>
Public Member Functions
F04DetectorMessenger (F04DetectorConstruction *)
virtual ~F04DetectorMessenger ()
virtual void SetNewValue (G4UIcommand *, G4String)
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
virtual G4String GetCurrentValue (G4UIcommand *command)
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Attributes
F04DetectorConstruction * fDetector
G4UIdirectory * fDetDir
G4UIcmdWithAString * fWorldMaterCmd
G4UIcmdWithADoubleAndUnit * fWorldRCmd
G4UIcmdWithADoubleAndUnit * fWorldZCmd
G4UIcmdWithADoubleAndUnit * fCaptureRCmd
G4UIcmdWithADoubleAndUnit * fCaptureZCmd
G4UIcmdWithADoubleAndUnit * fTransferRCmd
G4UIcmdWithADoubleAndUnit * fTransferZCmd
G4UIcmdWithADoubleAndUnit * fTransferPCmd
G4UIcmdWithAString * fTgtMaterCmd
G4UIcmdWithADoubleAndUnit * fTgtRadCmd
G4UIcmdWithADoubleAndUnit * fTgtThickCmd
G4UIcmdWithADoubleAndUnit * fTgtPosCmd
G4UIcmdWithAnInteger * fTgtAngCmd
G4UIcmdWithAString * fDgrMaterCmd
G4UIcmdWithADoubleAndUnit * fDgrRadCmd
G4UIcmdWithADoubleAndUnit * fDgrThickCmd
G4UIcmdWithADoubleAndUnit * fDgrPosCmd
Additional Inherited Members
Protected Member Functions inherited from G4UImessenger
G4String ItoS (G4int i)
G4String DtoS (G4double a)
G4String BtoS (G4bool b)
G4int StoI (G4String s)
G4long StoL (G4String s)
G4double StoD (G4String s)
G4bool StoB (G4String s)
void AddUIcommand (G4UIcommand *newCommand)
void CreateDirectory (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
template<typename T >
T * CreateCommand (const G4String &cname, const G4String &dsc)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Detailed Description
Definition at line 45 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 45 of file F04DetectorMessenger.hh
Constructor & Destructor Documentation
F04DetectorMessenger::F04DetectorMessenger (F04DetectorConstruction * detector)
Definition at line 41 of file F04DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 41 of file F04DetectorMessenger.cc
References G4UIcommand::AvailableForStates(), fCaptureRCmd, fCaptureZCmd, fDetDir, fDgrMaterCmd, fDgrPosCmd, fDgrRadCmd, fDgrThickCmd, fTgtAngCmd, fTgtMaterCmd, fTgtPosCmd, fTgtRadCmd, fTgtThickCmd, fTransferPCmd, fTransferRCmd, fTransferZCmd, fWorldMaterCmd, fWorldRCmd, fWorldZCmd, G4State_Idle, G4State_PreInit, G4UIcmdWithADoubleAndUnit::SetDefaultUnit(), G4UIcmdWithAString::SetDefaultValue(), G4UIcommand::SetGuidance(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithADoubleAndUnit::SetParameterName(), G4UIcommand::SetRange(), and G4UIcommand::SetToBeBroadcasted().
F04DetectorMessenger::~F04DetectorMessenger () virtual
Definition at line 178 of file F04DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 178 of file F04DetectorMessenger.cc
References fCaptureRCmd, fCaptureZCmd, fDetDir, fDgrMaterCmd, fDgrPosCmd, fDgrRadCmd, fDgrThickCmd, fTgtAngCmd, fTgtMaterCmd, fTgtPosCmd, fTgtRadCmd, fTgtThickCmd, fTransferPCmd, fTransferRCmd, fTransferZCmd, fWorldMaterCmd, fWorldRCmd, and fWorldZCmd.
Member Function Documentation
void F04DetectorMessenger::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 207 of file F04DetectorMessenger.cc.
View newest version in sPHENIX GitHub at line 207 of file F04DetectorMessenger.cc
References fCaptureRCmd, fCaptureZCmd, fDetector, fDgrMaterCmd, fDgrPosCmd, fDgrRadCmd, fDgrThickCmd, fTgtAngCmd, fTgtMaterCmd, fTgtPosCmd, fTgtRadCmd, fTgtThickCmd, fTransferPCmd, fTransferRCmd, fTransferZCmd, fWorldMaterCmd, fWorldRCmd, fWorldZCmd, G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(), G4UIcmdWithAnInteger::GetNewIntValue(), F04DetectorConstruction::SetCaptureMgntLength(), F04DetectorConstruction::SetCaptureMgntRadius(), F04DetectorConstruction::SetDegraderMaterial(), F04DetectorConstruction::SetDegraderPos(), F04DetectorConstruction::SetDegraderRadius(), F04DetectorConstruction::SetDegraderThickness(), F04DetectorConstruction::SetTargetAngle(), F04DetectorConstruction::SetTargetMaterial(), F04DetectorConstruction::SetTargetPos(), F04DetectorConstruction::SetTargetRadius(), F04DetectorConstruction::SetTargetThickness(), F04DetectorConstruction::SetTransferMgntLength(), F04DetectorConstruction::SetTransferMgntPos(), F04DetectorConstruction::SetTransferMgntRadius(), F04DetectorConstruction::SetWorldMaterial(), F04DetectorConstruction::SetWorldSizeR(), and F04DetectorConstruction::SetWorldSizeZ().
Member Data Documentation
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fCaptureRCmd private
Definition at line 64 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 64 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fCaptureZCmd private
Definition at line 65 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 65 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIdirectory* F04DetectorMessenger::fDetDir private
Definition at line 58 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 58 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), and ~F04DetectorMessenger().
F04DetectorConstruction* F04DetectorMessenger::fDetector private
Definition at line 56 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 56 of file F04DetectorMessenger.hh
Referenced by SetNewValue().
G4UIcmdWithAString* F04DetectorMessenger::fDgrMaterCmd private
Definition at line 77 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 77 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fDgrPosCmd private
Definition at line 80 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 80 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fDgrRadCmd private
Definition at line 78 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 78 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fDgrThickCmd private
Definition at line 79 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 79 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithAnInteger* F04DetectorMessenger::fTgtAngCmd private
Definition at line 75 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 75 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithAString* F04DetectorMessenger::fTgtMaterCmd private
Definition at line 71 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 71 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fTgtPosCmd private
Definition at line 74 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 74 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fTgtRadCmd private
Definition at line 72 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 72 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fTgtThickCmd private
Definition at line 73 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 73 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fTransferPCmd private
Definition at line 69 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 69 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fTransferRCmd private
Definition at line 67 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 67 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fTransferZCmd private
Definition at line 68 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 68 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithAString* F04DetectorMessenger::fWorldMaterCmd private
Definition at line 60 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 60 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fWorldRCmd private
Definition at line 61 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 61 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
G4UIcmdWithADoubleAndUnit* F04DetectorMessenger::fWorldZCmd private
Definition at line 62 of file F04DetectorMessenger.hh.
View newest version in sPHENIX GitHub at line 62 of file F04DetectorMessenger.hh
Referenced by F04DetectorMessenger(), SetNewValue(), and ~F04DetectorMessenger().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/field/field04/include/F04DetectorMessenger.hh
geant4/tree/geant4-10.6-release/examples/extended/field/field04/src/F04DetectorMessenger.cc