ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/geometry/biasing/include/G4GeometryCell.hh File Reference
G4GeometryCell.hh File Reference
#include "globals.hh"
Classes
class G4GeometryCell
Functions
G4bool operator== (const G4GeometryCell &k1, const G4GeometryCell &k2)
G4bool operator!= (const G4GeometryCell &k1, const G4GeometryCell &k2)
Function Documentation
G4bool operator!= (const G4GeometryCell & k1, const G4GeometryCell & k2)
Definition at line 84 of file G4GeometryCell.cc.
View newest version in sPHENIX GitHub at line 84 of file G4GeometryCell.cc
References G4GeometryCell::GetPhysicalVolume(), and G4GeometryCell::GetReplicaNumber().
G4bool operator== (const G4GeometryCell & k1, const G4GeometryCell & k2)
Definition at line 70 of file G4GeometryCell.cc.
View newest version in sPHENIX GitHub at line 70 of file G4GeometryCell.cc
References G4GeometryCell::GetPhysicalVolume(), and G4GeometryCell::GetReplicaNumber().