ECCE @ EIC Software: G4INCL::IAvatar Class Reference
G4INCL::IAvatar Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLIAvatar.hh>
Public Member Functions
IAvatar ()
IAvatar (G4double time)
virtual ~IAvatar ()
virtual G4INCL::IChannel * getChannel ()=0
FinalState * getFinalState ()
void fillFinalState (FinalState *fs)
virtual void preInteraction ()=0
virtual void postInteraction (FinalState *)=0
G4double getTime () const
virtual ParticleList getParticles () const =0
virtual std::string dump () const =0
AvatarType getType () const
G4bool isACollision () const
G4bool isADecay () const
void setType (AvatarType t)
long getID () const
std::string toString ()
Protected Attributes
G4double theTime
Private Attributes
long ID
AvatarType type
Static Private Attributes
static G4ThreadLocal long nextID = 1
Detailed Description
Definition at line 72 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 72 of file G4INCLIAvatar.hh
Constructor & Destructor Documentation
G4INCL::IAvatar::IAvatar ()
Definition at line 53 of file G4INCLIAvatar.cc.
View newest version in sPHENIX GitHub at line 53 of file G4INCLIAvatar.cc
References ID, and nextID.
G4INCL::IAvatar::IAvatar (G4double time)
Definition at line 61 of file G4INCLIAvatar.cc.
View newest version in sPHENIX GitHub at line 61 of file G4INCLIAvatar.cc
References ID, and nextID.
G4INCL::IAvatar::~IAvatar () virtual
Definition at line 69 of file G4INCLIAvatar.cc.
View newest version in sPHENIX GitHub at line 69 of file G4INCLIAvatar.cc
References INCL_DEBUG.
Member Function Documentation
virtual std::string G4INCL::IAvatar::dump () const pure virtual
Implemented in G4INCL::SurfaceAvatar, G4INCL::DecayAvatar, G4INCL::BinaryCollisionAvatar, and G4INCL::ParticleEntryAvatar.
Referenced by G4INCL::CascadeAction::beforeAvatarDefaultAction().
void G4INCL::IAvatar::fillFinalState (FinalState * fs)
Definition at line 96 of file G4INCLIAvatar.cc.
View newest version in sPHENIX GitHub at line 96 of file G4INCLIAvatar.cc
References c, G4INCL::IChannel::fillFinalState(), getChannel(), G4INCL::Random::getSeeds(), INCL_DEBUG, postInteraction(), and preInteraction().
Referenced by G4INCL::INCL::cascade(), and getFinalState().
virtual G4INCL::IChannel* G4INCL::IAvatar::getChannel () pure virtual
Implemented in G4INCL::InteractionAvatar, G4INCL::SurfaceAvatar, G4INCL::DecayAvatar, G4INCL::BinaryCollisionAvatar, and G4INCL::ParticleEntryAvatar.
Referenced by fillFinalState().
FinalState * G4INCL::IAvatar::getFinalState ()
Definition at line 90 of file G4INCLIAvatar.cc.
View newest version in sPHENIX GitHub at line 90 of file G4INCLIAvatar.cc
References fillFinalState(), and Acts::UnitConstants::fs.
Referenced by G4INCL::Nucleus::computeOneNucleonRecoilKinematics(), G4INCL::Nucleus::decayOutgoingDeltas(), G4INCL::Nucleus::decayOutgoingPionResonances(), G4INCL::Nucleus::decayOutgoingSigmaZero(), and G4INCL::INCL::makeCompoundNucleus().
long G4INCL::IAvatar::getID () const inline
Definition at line 94 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 94 of file G4INCLIAvatar.hh
Referenced by G4INCL::CascadeAction::afterAvatarDefaultAction(), G4INCL::CascadeAction::beforeAvatarDefaultAction(), and toString().
virtual ParticleList G4INCL::IAvatar::getParticles () const pure virtual
Implemented in G4INCL::SurfaceAvatar, G4INCL::DecayAvatar, G4INCL::BinaryCollisionAvatar, and G4INCL::ParticleEntryAvatar.
Referenced by G4INCL::Store::add(), G4INCL::Store::addParticleEntryAvatar(), G4INCL::Store::removeAvatar(), and toString().
G4double G4INCL::IAvatar::getTime () const inline
Definition at line 84 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 84 of file G4INCLIAvatar.hh
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::Store::avatarComparisonPredicate(), G4INCL::StandardPropagationModel::propagate(), and toString().
AvatarType G4INCL::IAvatar::getType () const inline
Definition at line 90 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 90 of file G4INCLIAvatar.hh
Referenced by G4INCL::AvatarDumpAction::afterAvatarUserAction(), G4INCL::CascadeAction::beforeAvatarDefaultAction(), G4INCL::InteractionAvatar::shouldUseLocalEnergy(), and toString().
G4bool G4INCL::IAvatar::isACollision () const inline
Definition at line 91 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 91 of file G4INCLIAvatar.hh
References G4INCL::CollisionAvatarType.
Referenced by G4INCL::CascadeAction::afterAvatarDefaultAction().
G4bool G4INCL::IAvatar::isADecay () const inline
Definition at line 92 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 92 of file G4INCLIAvatar.hh
References G4INCL::DecayAvatarType.
Referenced by G4INCL::CascadeAction::afterAvatarDefaultAction().
virtual void G4INCL::IAvatar::postInteraction (FinalState *) pure virtual
Implemented in G4INCL::InteractionAvatar, G4INCL::SurfaceAvatar, G4INCL::BinaryCollisionAvatar, G4INCL::DecayAvatar, and G4INCL::ParticleEntryAvatar.
Referenced by fillFinalState().
virtual void G4INCL::IAvatar::preInteraction () pure virtual
Implemented in G4INCL::InteractionAvatar, G4INCL::SurfaceAvatar, G4INCL::BinaryCollisionAvatar, G4INCL::DecayAvatar, and G4INCL::ParticleEntryAvatar.
Referenced by fillFinalState().
void G4INCL::IAvatar::setType (AvatarType t) inline
Definition at line 93 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 93 of file G4INCLIAvatar.hh
References t.
Referenced by G4INCL::BinaryCollisionAvatar::BinaryCollisionAvatar(), G4INCL::DecayAvatar::DecayAvatar(), G4INCL::ParticleEntryAvatar::ParticleEntryAvatar(), and G4INCL::SurfaceAvatar::SurfaceAvatar().
std::string G4INCL::IAvatar::toString ()
Definition at line 73 of file G4INCLIAvatar.cc.
View newest version in sPHENIX GitHub at line 73 of file G4INCLIAvatar.cc
References e, getID(), getParticles(), getTime(), getType(), numberOfParticles, and readPY::pl.
Member Data Documentation
long G4INCL::IAvatar::ID private
Definition at line 98 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 98 of file G4INCLIAvatar.hh
Referenced by IAvatar().
G4ThreadLocal long G4INCL::IAvatar::nextID = 1 static private
Definition at line 100 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 100 of file G4INCLIAvatar.hh
Referenced by IAvatar().
G4double G4INCL::IAvatar::theTime protected
Definition at line 102 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 102 of file G4INCLIAvatar.hh
Referenced by G4INCL::ParticleEntryAvatar::dump(), G4INCL::BinaryCollisionAvatar::dump(), G4INCL::DecayAvatar::dump(), and G4INCL::SurfaceAvatar::dump().
AvatarType G4INCL::IAvatar::type private
Definition at line 99 of file G4INCLIAvatar.hh.
View newest version in sPHENIX GitHub at line 99 of file G4INCLIAvatar.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/include/G4INCLIAvatar.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/utils/src/G4INCLIAvatar.cc