ECCE @ EIC Software: G4MaleBuilder Class Reference
G4MaleBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4MaleBuilder.hh>
Public Member Functions
G4MaleBuilder ()
~G4MaleBuilder ()
void BuildMaleGenitalia (const G4String &colourName, G4bool solidVis, G4bool sensitivity)
void BuildLeftTeste (const G4String &colourName, G4bool solidVis, G4bool sensitivity)
void BuildRightTeste (const G4String &colourName, G4bool solidVis, G4bool sensitivity)
Public Member Functions inherited from G4PhantomBuilder
G4PhantomBuilder ()
~G4PhantomBuilder ()
void BuildHead (const G4String &, G4bool, G4bool)
void BuildTrunk (const G4String &, G4bool, G4bool)
void BuildLeftLeg (const G4String &, G4bool, G4bool)
void BuildRightLeg (const G4String &, G4bool, G4bool)
void BuildUpperSpine (const G4String &, G4bool, G4bool)
void BuildMiddleLowerSpine (const G4String &, G4bool, G4bool)
void BuildLeftLegBone (const G4String &, G4bool, G4bool)
void BuildRightLegBone (const G4String &, G4bool, G4bool)
void BuildLeftArmBone (const G4String &, G4bool, G4bool)
void BuildRightArmBone (const G4String &, G4bool, G4bool)
void BuildSkull (const G4String &, G4bool, G4bool)
void BuildRibCage (const G4String &, G4bool, G4bool)
void BuildPelvis (const G4String &, G4bool, G4bool)
void BuildLeftScapula (const G4String &, G4bool, G4bool)
void BuildRightScapula (const G4String &, G4bool, G4bool)
void BuildLeftAdrenal (const G4String &, G4bool, G4bool)
void BuildRightAdrenal (const G4String &, G4bool, G4bool)
void BuildLeftClavicle (const G4String &, G4bool, G4bool)
void BuildRightClavicle (const G4String &, G4bool, G4bool)
void BuildBrain (const G4String &, G4bool, G4bool)
void BuildHeart (const G4String &, G4bool, G4bool)
void BuildLeftLung (const G4String &, G4bool, G4bool)
void BuildRightLung (const G4String &, G4bool, G4bool)
void BuildStomach (const G4String &, G4bool, G4bool)
void BuildSmallIntestine (const G4String &, G4bool, G4bool)
void BuildUpperLargeIntestine (const G4String &, G4bool, G4bool)
void BuildLowerLargeIntestine (const G4String &, G4bool, G4bool)
void BuildLeftKidney (const G4String &, G4bool, G4bool)
void BuildRightKidney (const G4String &, G4bool, G4bool)
void BuildLiver (const G4String &, G4bool, G4bool)
void BuildPancreas (const G4String &, G4bool, G4bool)
void BuildSpleen (const G4String &, G4bool, G4bool)
void BuildUrinaryBladder (const G4String &, G4bool, G4bool)
void BuildThyroid (const G4String &, G4bool, G4bool)
void BuildThymus (const G4String &, G4bool, G4bool)
void SetModel (G4String)
void SetMotherVolume (G4VPhysicalVolume *)
G4VPhysicalVolume * GetPhantom ()
Public Member Functions inherited from G4BasePhantomBuilder
G4BasePhantomBuilder ()
virtual ~G4BasePhantomBuilder ()
virtual void BuildLeftOvary (const G4String &, G4bool, G4bool)
virtual void BuildRightOvary (const G4String &, G4bool, G4bool)
virtual void BuildUterus (const G4String &, G4bool, G4bool)
virtual void BuildLeftBreast (const G4String &, G4bool, G4bool)
virtual void BuildRightBreast (const G4String &, G4bool, G4bool)
virtual void BuildVoxelLeftBreast (const G4String &, G4bool, G4bool)
virtual void BuildVoxelRightBreast (const G4String &, G4bool, G4bool)
Additional Inherited Members
Protected Attributes inherited from G4PhantomBuilder
G4VBodyFactory * body
G4String model
G4VPhysicalVolume * motherVolume
G4VPhysicalVolume * headVolume
G4VPhysicalVolume * trunkVolume
G4VPhysicalVolume * leftLegVolume
G4VPhysicalVolume * rightLegVolume
G4VPhysicalVolume * maleGenitaliaVolume
Detailed Description
Definition at line 39 of file G4MaleBuilder.hh.
View newest version in sPHENIX GitHub at line 39 of file G4MaleBuilder.hh
Constructor & Destructor Documentation
G4MaleBuilder::G4MaleBuilder ()
Definition at line 35 of file G4MaleBuilder.cc.
View newest version in sPHENIX GitHub at line 35 of file G4MaleBuilder.cc
G4MaleBuilder::~G4MaleBuilder ()
Definition at line 39 of file G4MaleBuilder.cc.
View newest version in sPHENIX GitHub at line 39 of file G4MaleBuilder.cc
References G4PhantomBuilder::body.
Member Function Documentation
void G4MaleBuilder::BuildLeftTeste (const G4String & colourName, G4bool solidVis, G4bool sensitivity) virtual
Reimplemented from G4BasePhantomBuilder.
Definition at line 57 of file G4MaleBuilder.cc.
View newest version in sPHENIX GitHub at line 57 of file G4MaleBuilder.cc
References G4PhantomBuilder::body, FatalException, G4cout, G4endl, G4Exception(), G4PhantomBuilder::maleGenitaliaVolume, and G4PhantomBuilder::motherVolume.
void G4MaleBuilder::BuildMaleGenitalia (const G4String & colourName, G4bool solidVis, G4bool sensitivity) virtual
Reimplemented from G4BasePhantomBuilder.
Definition at line 44 of file G4MaleBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4MaleBuilder.cc
References G4PhantomBuilder::body, FatalException, G4cout, G4endl, G4Exception(), G4PhantomBuilder::maleGenitaliaVolume, and G4PhantomBuilder::motherVolume.
void G4MaleBuilder::BuildRightTeste (const G4String & colourName, G4bool solidVis, G4bool sensitivity) virtual
Reimplemented from G4BasePhantomBuilder.
Definition at line 68 of file G4MaleBuilder.cc.
View newest version in sPHENIX GitHub at line 68 of file G4MaleBuilder.cc
References G4PhantomBuilder::body, FatalException, G4cout, G4endl, G4Exception(), G4PhantomBuilder::maleGenitaliaVolume, and G4PhantomBuilder::motherVolume.
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4MaleBuilder.hh
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/src/G4MaleBuilder.cc