ECCE @ EIC Software: Par01EnergySpot Class Reference
Par01EnergySpot Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01EnergySpot.hh>
Public Member Functions
Par01EnergySpot ()
Par01EnergySpot (const G4ThreeVector &point, G4double E)
~Par01EnergySpot ()
void SetEnergy (const G4double &E)
G4double GetEnergy () const
void SetPosition (const G4ThreeVector &point)
G4ThreeVector GetPosition () const
G4bool operator== (const Par01EnergySpot &eSpot) const
void Draw (G4Colour *color=0)
void Print ()
Private Attributes
G4double fEnergy
G4ThreeVector fPoint
Detailed Description
Definition at line 37 of file Par01EnergySpot.hh.
View newest version in sPHENIX GitHub at line 37 of file Par01EnergySpot.hh
Constructor & Destructor Documentation
Par01EnergySpot::Par01EnergySpot ()
Definition at line 42 of file Par01EnergySpot.cc.
View newest version in sPHENIX GitHub at line 42 of file Par01EnergySpot.cc
Par01EnergySpot::Par01EnergySpot (const G4ThreeVector & point, G4double E)
Definition at line 47 of file Par01EnergySpot.cc.
View newest version in sPHENIX GitHub at line 47 of file Par01EnergySpot.cc
References E, fEnergy, and fPoint.
Par01EnergySpot::~Par01EnergySpot ()
Definition at line 55 of file Par01EnergySpot.cc.
View newest version in sPHENIX GitHub at line 55 of file Par01EnergySpot.cc
Member Function Documentation
void Par01EnergySpot::Draw (G4Colour * color = 0)
Definition at line 60 of file Par01EnergySpot.cc.
View newest version in sPHENIX GitHub at line 60 of file Par01EnergySpot.cc
References cm, color(), fPoint, G4VVisManager::GetConcreteInstance(), G4InuclParticleNames::pp, G4Visible::SetVisAttributes(), CLHEP::Hep3Vector::setX(), CLHEP::Hep3Vector::setY(), CLHEP::Hep3Vector::setZ(), CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
G4double Par01EnergySpot::GetEnergy () const inline
Definition at line 45 of file Par01EnergySpot.hh.
View newest version in sPHENIX GitHub at line 45 of file Par01EnergySpot.hh
References fEnergy.
Referenced by Par01PionShowerModel::FillFakeStep(), and Par01EMShowerModel::FillFakeStep().
G4ThreeVector Par01EnergySpot::GetPosition () const inline
Definition at line 48 of file Par01EnergySpot.hh.
View newest version in sPHENIX GitHub at line 48 of file Par01EnergySpot.hh
References fPoint.
Referenced by Par01PionShowerModel::FillFakeStep(), and Par01EMShowerModel::FillFakeStep().
G4bool Par01EnergySpot::operator== (const Par01EnergySpot & eSpot) const inline
Definition at line 50 of file Par01EnergySpot.hh.
View newest version in sPHENIX GitHub at line 50 of file Par01EnergySpot.hh
References fEnergy, and fPoint.
void Par01EnergySpot::Print (void)
Definition at line 94 of file Par01EnergySpot.cc.
View newest version in sPHENIX GitHub at line 94 of file Par01EnergySpot.cc
References fEnergy, fPoint, G4cout, and G4endl.
void Par01EnergySpot::SetEnergy (const G4double & E) inline
Definition at line 44 of file Par01EnergySpot.hh.
View newest version in sPHENIX GitHub at line 44 of file Par01EnergySpot.hh
References E, and fEnergy.
Referenced by Par01PionShowerModel::Explode(), and Par01EMShowerModel::Explode().
void Par01EnergySpot::SetPosition (const G4ThreeVector & point) inline
Definition at line 47 of file Par01EnergySpot.hh.
View newest version in sPHENIX GitHub at line 47 of file Par01EnergySpot.hh
References fPoint.
Referenced by Par01PionShowerModel::Explode(), and Par01EMShowerModel::Explode().
Member Data Documentation
G4double Par01EnergySpot::fEnergy private
Definition at line 62 of file Par01EnergySpot.hh.
View newest version in sPHENIX GitHub at line 62 of file Par01EnergySpot.hh
Referenced by GetEnergy(), operator==(), Par01EnergySpot(), Print(), and SetEnergy().
G4ThreeVector Par01EnergySpot::fPoint private
Definition at line 63 of file Par01EnergySpot.hh.
View newest version in sPHENIX GitHub at line 63 of file Par01EnergySpot.hh
Referenced by Draw(), GetPosition(), operator==(), Par01EnergySpot(), Print(), and SetPosition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/include/Par01EnergySpot.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par01/src/Par01EnergySpot.cc