ECCE @ EIC Software: G4VisCommandsViewerSet Class Reference
G4VisCommandsViewerSet Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsViewerSet.hh>
Public Member Functions
G4VisCommandsViewerSet ()
virtual ~G4VisCommandsViewerSet ()
G4String GetCurrentValue (G4UIcommand *command)
void SetNewValue (G4UIcommand *command, G4String newValue)
Public Member Functions inherited from G4VVisCommand
G4VVisCommand ()
virtual ~G4VVisCommand ()
Public Member Functions inherited from G4UImessenger
G4UImessenger ()
G4UImessenger (const G4String &path, const G4String &dsc, G4bool commandsToBeBroadcasted=true)
virtual ~G4UImessenger ()
G4bool operator== (const G4UImessenger &messenger) const
G4bool CommandsShouldBeInMaster () const
Private Member Functions
G4VisCommandsViewerSet (const G4VisCommandsViewerSet &)
G4VisCommandsViewerSet & operator= (const G4VisCommandsViewerSet &)
Private Attributes
G4UIcmdWithAString * fpCommandAll
G4UIcmdWithABool * fpCommandAutoRefresh
G4UIcmdWithABool * fpCommandAuxEdge
G4UIcommand * fpCommandBackground
G4UIcommand * fpCommandCulling
G4UIcmdWithAString * fpCommandCutawayMode
G4UIcommand * fpCommandDefaultColour
G4UIcommand * fpCommandDefaultTextColour
G4UIcmdWithABool * fpCommandEdge
G4UIcommand * fpCommandExplodeFactor
G4UIcmdWithADouble * fpCommandGlobalMarkerScale
G4UIcmdWithADouble * fpCommandGlobalLineWidthScale
G4UIcmdWithABool * fpCommandHiddenEdge
G4UIcmdWithABool * fpCommandHiddenMarker
G4UIcmdWithAString * fpCommandLightsMove
G4UIcommand * fpCommandLightsThetaPhi
G4UIcommand * fpCommandLightsVector
G4ThreeVector fLightsVector
G4UIcmdWithAnInteger * fpCommandLineSegments
G4UIcmdWithAnInteger * fpCommandNumberOfCloudPoints
G4UIcmdWithABool * fpCommandPicking
G4UIcommand * fpCommandProjection
G4UIcmdWithAString * fpCommandRotationStyle
G4UIcommand * fpCommandSectionPlane
G4UIcmdWithAString * fpCommandStyle
G4UIcmdWith3VectorAndUnit * fpCommandTargetPoint
G4UIcommand * fpCommandUpThetaPhi
G4UIcommand * fpCommandUpVector
G4ThreeVector fUpVector
G4UIcommand * fpCommandViewpointThetaPhi
G4UIcommand * fpCommandViewpointVector
G4ThreeVector fViewpointVector
G4UIdirectory * fpTimeWindowDirectory
G4UIcommand * fpCommandTimeWindowDisplayHeadTime
G4UIcommand * fpCommandTimeWindowDisplayLightFront
G4UIcommand * fpCommandTimeWindowEndTime
G4UIcmdWithADouble * fpCommandTimeWindowFadeFactor
G4UIcommand * fpCommandTimeWindowStartTime
Additional Inherited Members
Static Public Member Functions inherited from G4VVisCommand
static void SetVisManager (G4VisManager *pVisManager)
static const G4Colour & GetCurrentTextColour ()
Protected Member Functions inherited from G4VVisCommand
void SetViewParameters (G4VViewer *viewer, const G4ViewParameters &viewParams)
void RefreshIfRequired (G4VViewer *viewer)
void InterpolateViews (G4VViewer *currentViewer, std::vector< G4ViewParameters > viewVector, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
void InterpolateToNewView (G4VViewer *currentViewer, const G4ViewParameters &oldVP, const G4ViewParameters &newVP, const G4int nInterpolationPoints=50, const G4int waitTimePerPointmilliseconds=20, const G4String exportString="")
const G4String & ConvertToColourGuidance ()
void ConvertToColour (G4Colour &colour, const G4String &redOrString, G4double green, G4double blue, G4double opacity)
G4bool ProvideValueOfUnit (const G4String &where, const G4String &unit, const G4String &category, G4double &value)
void CheckSceneAndNotifyHandlers (G4Scene *=nullptr)
void G4VisCommandsSceneAddUnsuccessful (G4VisManager::Verbosity verbosity)
void CopyGuidanceFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd, G4int startLine=0)
void CopyParametersFrom (const G4UIcommand *fromCmd, G4UIcommand *toCmd)
void DrawExtent (const G4VisExtent &)
Static Protected Member Functions inherited from G4VVisCommand
static G4String ConvertToString (G4double x, G4double y, const char *unitName)
static G4bool ConvertToDoublePair (const G4String &paramString, G4double &xval, G4double &yval)
Protected Attributes inherited from G4UImessenger
G4UIdirectory * baseDir
G4String baseDirName
G4bool commandsShouldBeInMaster
Static Protected Attributes inherited from G4VVisCommand
static G4VisManager * fpVisManager = 0
static G4int fErrorCode = 0
static G4int fCurrentArrow3DLineSegmentsPerCircle = 6
static G4Colour fCurrentColour = G4Colour::White()
static G4double fCurrentLineWidth = 1.
static G4Colour fCurrentTextColour = G4Colour::Blue()
static G4Text::Layout fCurrentTextLayout = G4Text::left
static G4double fCurrentTextSize = 12.
static
G4PhysicalVolumeModel::TouchableProperties fCurrentTouchableProperties
static G4VisExtent fCurrentExtentForField
static std::vector
< G4PhysicalVolumesSearchScene::Findings > fCurrrentPVFindingsForField
Detailed Description
Definition at line 45 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 45 of file G4VisCommandsViewerSet.hh
Constructor & Destructor Documentation
G4VisCommandsViewerSet::G4VisCommandsViewerSet ()
Definition at line 46 of file G4VisCommandsViewerSet.cc.
View newest version in sPHENIX GitHub at line 46 of file G4VisCommandsViewerSet.cc
References G4VVisCommand::ConvertToColourGuidance(), fpCommandAll, fpCommandAutoRefresh, fpCommandAuxEdge, fpCommandBackground, fpCommandCulling, fpCommandCutawayMode, fpCommandDefaultColour, fpCommandDefaultTextColour, fpCommandEdge, fpCommandExplodeFactor, fpCommandGlobalLineWidthScale, fpCommandGlobalMarkerScale, fpCommandHiddenEdge, fpCommandHiddenMarker, fpCommandLightsMove, fpCommandLightsThetaPhi, fpCommandLightsVector, fpCommandLineSegments, fpCommandNumberOfCloudPoints, fpCommandPicking, fpCommandProjection, fpCommandRotationStyle, fpCommandSectionPlane, fpCommandStyle, fpCommandTargetPoint, fpCommandTimeWindowDisplayHeadTime, fpCommandTimeWindowDisplayLightFront, fpCommandTimeWindowEndTime, fpCommandTimeWindowFadeFactor, fpCommandTimeWindowStartTime, fpCommandUpThetaPhi, fpCommandUpVector, fpCommandViewpointThetaPhi, fpCommandViewpointVector, fpTimeWindowDirectory, G4VisAttributes::fVeryLongTime, G4UIcmdWithAString::SetCandidates(), G4UIcmdWithAnInteger::SetDefaultValue(), G4UIcmdWithADouble::SetDefaultValue(), G4UIcmdWithAString::SetDefaultValue(), G4UIcmdWithABool::SetDefaultValue(), G4UIparameter::SetDefaultValue(), G4UIparameter::SetGuidance(), G4UIcommand::SetGuidance(), G4UIcommand::SetParameter(), G4UIparameter::SetParameterCandidates(), G4UIcmdWithAString::SetParameterName(), G4UIcmdWithAnInteger::SetParameterName(), G4UIcmdWithADouble::SetParameterName(), G4UIcmdWithABool::SetParameterName(), G4UIcmdWith3VectorAndUnit::SetParameterName(), G4UIparameter::SetParameterRange(), G4UIcommand::SetRange(), and G4UIcmdWith3VectorAndUnit::SetUnitCategory().
G4VisCommandsViewerSet::~G4VisCommandsViewerSet () virtual
Definition at line 599 of file G4VisCommandsViewerSet.cc.
View newest version in sPHENIX GitHub at line 599 of file G4VisCommandsViewerSet.cc
References fpCommandAll, fpCommandAutoRefresh, fpCommandAuxEdge, fpCommandBackground, fpCommandCulling, fpCommandCutawayMode, fpCommandDefaultColour, fpCommandDefaultTextColour, fpCommandEdge, fpCommandExplodeFactor, fpCommandGlobalLineWidthScale, fpCommandGlobalMarkerScale, fpCommandHiddenEdge, fpCommandHiddenMarker, fpCommandLightsMove, fpCommandLightsThetaPhi, fpCommandLightsVector, fpCommandLineSegments, fpCommandNumberOfCloudPoints, fpCommandPicking, fpCommandProjection, fpCommandRotationStyle, fpCommandSectionPlane, fpCommandStyle, fpCommandTargetPoint, fpCommandTimeWindowDisplayHeadTime, fpCommandTimeWindowDisplayLightFront, fpCommandTimeWindowEndTime, fpCommandTimeWindowFadeFactor, fpCommandTimeWindowStartTime, fpCommandUpThetaPhi, fpCommandUpVector, fpCommandViewpointThetaPhi, fpCommandViewpointVector, and fpTimeWindowDirectory.
G4VisCommandsViewerSet::G4VisCommandsViewerSet (const G4VisCommandsViewerSet &) private
Member Function Documentation
G4String G4VisCommandsViewerSet::GetCurrentValue (G4UIcommand * command) virtual
Reimplemented from G4UImessenger.
Definition at line 637 of file G4VisCommandsViewerSet.cc.
View newest version in sPHENIX GitHub at line 637 of file G4VisCommandsViewerSet.cc
G4VisCommandsViewerSet& G4VisCommandsViewerSet::operator= (const G4VisCommandsViewerSet &) private
void G4VisCommandsViewerSet::SetNewValue (G4UIcommand * command, G4String newValue) virtual
Reimplemented from G4UImessenger.
Definition at line 642 of file G4VisCommandsViewerSet.cc.
View newest version in sPHENIX GitHub at line 642 of file G4VisCommandsViewerSet.cc
References G4ViewParameters::AddVisAttributesModifier(), G4ViewParameters::cloud, G4String::compareTo(), G4VisManager::confirmations, G4ViewParameters::constrainUpDirection, G4UIcommand::ConvertTo3Vector(), G4UIcommand::ConvertToBool(), G4UIcommand::ConvertToDimensionedDouble(), G4UIcommand::ConvertToDouble(), G4UIcommand::ConvertToInt(), G4UIcommand::ConvertToString(), G4ViewParameters::cutawayIntersection, G4ViewParameters::cutawayUnion, deg, G4VisManager::errors, F, G4ViewParameters::freeRotation, G4BestUnit, G4cerr, G4cout, G4endl, G4ViewParameters::GetActualLightpointDirection(), G4ViewParameters::GetBackgroundColour(), G4VisAttributes::GetColour(), G4ViewParameters::GetCurrentTargetPoint(), G4ViewParameters::GetCutawayMode(), G4ViewParameters::GetDefaultTextVisAttributes(), G4VViewer::GetDefaultViewParameters(), G4ViewParameters::GetDefaultVisAttributes(), G4ViewParameters::GetDrawingStyle(), G4ViewParameters::GetEndTime(), G4ViewParameters::GetExplodeCentre(), G4ViewParameters::GetExplodeFactor(), G4ViewParameters::GetFadeFactor(), G4ViewParameters::GetGlobalLineWidthScale(), G4ViewParameters::GetGlobalMarkerScale(), G4ViewParameters::GetLightpointDirection(), G4ViewParameters::GetLightsMoveWithCamera(), G4VViewer::GetName(), G4VViewer::GetPrivateVisAttributesModifiers(), G4ViewParameters::GetRotationStyle(), G4VSceneHandler::GetScene(), G4VViewer::GetSceneHandler(), G4ViewParameters::GetSectionPlane(), G4Scene::GetStandardTargetPoint(), G4ViewParameters::GetStartTime(), G4ViewParameters::GetUpVector(), G4VViewer::GetViewParameters(), G4ViewParameters::GetViewpointDirection(), G4ViewParameters::GetVisibleDensity(), G4ViewParameters::hlhsr, G4ViewParameters::hlr, G4ViewParameters::hsr, G4String::ignoreCase, G4ViewParameters::IsAutoRefresh(), G4ViewParameters::IsAuxEdgeVisible(), G4ViewParameters::IsDensityCulling(), G4ViewParameters::IsMarkerNotHidden(), G4ViewParameters::IsPicking(), G4ViewParameters::IsSection(), CLHEP::Hep3Vector::mag2(), CLHEP::normal(), ns, phi, G4ViewParameters::SetAutoRefresh(), G4ViewParameters::SetAuxEdgeVisible(), G4ViewParameters::SetBackgroundColour(), G4VisAttributes::SetColour(), G4ViewParameters::SetCulling(), G4ViewParameters::SetCullingCovered(), G4ViewParameters::SetCullingInvisible(), G4ViewParameters::SetCurrentTargetPoint(), G4ViewParameters::SetCutawayMode(), G4ViewParameters::SetDefaultTextVisAttributes(), G4ViewParameters::SetDefaultVisAttributes(), G4ViewParameters::SetDensityCulling(), G4ViewParameters::SetDisplayHeadTime(), G4ViewParameters::SetDisplayHeadTimeBlue(), G4ViewParameters::SetDisplayHeadTimeGreen(), G4ViewParameters::SetDisplayHeadTimeRed(), G4ViewParameters::SetDisplayHeadTimeSize(), G4ViewParameters::SetDisplayHeadTimeX(), G4ViewParameters::SetDisplayHeadTimeY(), G4ViewParameters::SetDisplayLightFront(), G4ViewParameters::SetDisplayLightFrontBlue(), G4ViewParameters::SetDisplayLightFrontGreen(), G4ViewParameters::SetDisplayLightFrontRed(), G4ViewParameters::SetDisplayLightFrontT(), G4ViewParameters::SetDisplayLightFrontX(), G4ViewParameters::SetDisplayLightFrontY(), G4ViewParameters::SetDisplayLightFrontZ(), G4ViewParameters::SetDrawingStyle(), G4ViewParameters::SetEndTime(), G4ViewParameters::SetExplodeCentre(), G4ViewParameters::SetExplodeFactor(), G4ViewParameters::SetFadeFactor(), G4ViewParameters::SetFieldHalfAngle(), G4ViewParameters::SetGlobalLineWidthScale(), G4ViewParameters::SetGlobalMarkerScale(), G4ViewParameters::SetLightpointDirection(), G4ViewParameters::SetLightsMoveWithCamera(), G4ViewParameters::SetMarkerHidden(), G4ViewParameters::SetMarkerNotHidden(), G4ViewParameters::SetNoOfSides(), G4ViewParameters::SetNumberOfCloudPoints(), G4ViewParameters::SetPicking(), G4ViewParameters::SetRotationStyle(), G4ViewParameters::SetSectionPlane(), G4ViewParameters::SetStartTime(), G4ViewParameters::SetUpVector(), G4ViewParameters::SetViewAndLights(), G4VViewer::SetViewParameters(), G4ViewParameters::SetViewpointDirection(), G4ViewParameters::SetVisibleDensity(), theta(), CLHEP::Hep3Vector::unit(), G4ViewParameters::UnsetSectionPlane(), G4UIcommand::ValueOf(), G4VisManager::warnings, G4ViewParameters::wireframe, x, y, and z.
Member Data Documentation
G4ThreeVector G4VisCommandsViewerSet::fLightsVector private
Definition at line 71 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 71 of file G4VisCommandsViewerSet.hh
G4UIcmdWithAString* G4VisCommandsViewerSet::fpCommandAll private
Definition at line 54 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 54 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithABool* G4VisCommandsViewerSet::fpCommandAutoRefresh private
Definition at line 55 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithABool* G4VisCommandsViewerSet::fpCommandAuxEdge private
Definition at line 56 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 56 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandBackground private
Definition at line 57 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 57 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandCulling private
Definition at line 58 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 58 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithAString* G4VisCommandsViewerSet::fpCommandCutawayMode private
Definition at line 59 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 59 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandDefaultColour private
Definition at line 60 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 60 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandDefaultTextColour private
Definition at line 61 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 61 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithABool* G4VisCommandsViewerSet::fpCommandEdge private
Definition at line 62 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 62 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandExplodeFactor private
Definition at line 63 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 63 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithADouble* G4VisCommandsViewerSet::fpCommandGlobalLineWidthScale private
Definition at line 65 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 65 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithADouble* G4VisCommandsViewerSet::fpCommandGlobalMarkerScale private
Definition at line 64 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 64 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithABool* G4VisCommandsViewerSet::fpCommandHiddenEdge private
Definition at line 66 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 66 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithABool* G4VisCommandsViewerSet::fpCommandHiddenMarker private
Definition at line 67 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 67 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithAString* G4VisCommandsViewerSet::fpCommandLightsMove private
Definition at line 68 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 68 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandLightsThetaPhi private
Definition at line 69 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 69 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandLightsVector private
Definition at line 70 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 70 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithAnInteger* G4VisCommandsViewerSet::fpCommandLineSegments private
Definition at line 72 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 72 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithAnInteger* G4VisCommandsViewerSet::fpCommandNumberOfCloudPoints private
Definition at line 73 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 73 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithABool* G4VisCommandsViewerSet::fpCommandPicking private
Definition at line 74 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 74 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandProjection private
Definition at line 75 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 75 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithAString* G4VisCommandsViewerSet::fpCommandRotationStyle private
Definition at line 76 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 76 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandSectionPlane private
Definition at line 77 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 77 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithAString* G4VisCommandsViewerSet::fpCommandStyle private
Definition at line 78 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 78 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWith3VectorAndUnit* G4VisCommandsViewerSet::fpCommandTargetPoint private
Definition at line 79 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 79 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandTimeWindowDisplayHeadTime private
Definition at line 87 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 87 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandTimeWindowDisplayLightFront private
Definition at line 88 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 88 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandTimeWindowEndTime private
Definition at line 89 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 89 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcmdWithADouble* G4VisCommandsViewerSet::fpCommandTimeWindowFadeFactor private
Definition at line 90 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 90 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandTimeWindowStartTime private
Definition at line 91 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 91 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandUpThetaPhi private
Definition at line 80 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 80 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandUpVector private
Definition at line 81 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 81 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandViewpointThetaPhi private
Definition at line 83 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 83 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIcommand* G4VisCommandsViewerSet::fpCommandViewpointVector private
Definition at line 84 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 84 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4UIdirectory* G4VisCommandsViewerSet::fpTimeWindowDirectory private
Definition at line 86 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 86 of file G4VisCommandsViewerSet.hh
Referenced by G4VisCommandsViewerSet(), and ~G4VisCommandsViewerSet().
G4ThreeVector G4VisCommandsViewerSet::fUpVector private
Definition at line 82 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 82 of file G4VisCommandsViewerSet.hh
G4ThreeVector G4VisCommandsViewerSet::fViewpointVector private
Definition at line 85 of file G4VisCommandsViewerSet.hh.
View newest version in sPHENIX GitHub at line 85 of file G4VisCommandsViewerSet.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/management/include/G4VisCommandsViewerSet.hh
geant4/tree/geant4-10.6-release/source/visualization/management/src/G4VisCommandsViewerSet.cc