ECCE @ EIC Software: G4UIcmdWithNucleusLimits Class Reference
G4UIcmdWithNucleusLimits Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4UIcmdWithNucleusLimits.hh>
Public Member Functions
G4UIcmdWithNucleusLimits (const char *theCommandPath, G4UImessenger *theMessenger)
~G4UIcmdWithNucleusLimits ()
G4NucleusLimits GetNewNucleusLimitsValue (G4String paramString)
G4String ConvertToString (G4NucleusLimits nuclimit)
void SetParameterName (const char *theNameAMin, const char *theNameAMax, const char *theNameZMin, const char *theNameZMax, G4bool omittable, G4bool currentAsDefault=true)
void SetDefaultValue (G4NucleusLimits defVal)
Public Member Functions inherited from G4UIcommand
G4UIcommand ()
G4UIcommand (const char *theCommandPath, G4UImessenger *theMessenger, G4bool tBB=true)
virtual ~G4UIcommand ()
G4bool operator== (const G4UIcommand &right) const
G4bool operator!= (const G4UIcommand &right) const
virtual G4int DoIt (G4String parameterList)
G4String GetCurrentValue ()
void AvailableForStates (G4ApplicationState s1)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4)
void AvailableForStates (G4ApplicationState s1, G4ApplicationState s2, G4ApplicationState s3, G4ApplicationState s4, G4ApplicationState s5)
G4bool IsAvailable ()
virtual void List ()
void SetRange (const char *rs)
const G4String & GetRange () const
size_t GetGuidanceEntries () const
const G4String & GetGuidanceLine (G4int i) const
const G4String & GetCommandPath () const
const G4String & GetCommandName () const
size_t GetParameterEntries () const
G4UIparameter * GetParameter (G4int i) const
std::vector< G4ApplicationState > * GetStateList ()
G4UImessenger * GetMessenger () const
void SetParameter (G4UIparameter *const newParameter)
void SetGuidance (const char *aGuidance)
const G4String GetTitle () const
void SetToBeBroadcasted (G4bool val)
G4bool ToBeBroadcasted () const
void SetToBeFlushed (G4bool val)
G4bool ToBeFlushed () const
void SetWorkerThreadOnly (G4bool val=true)
G4bool IsWorkerThreadOnly () const
void CommandFailed (G4int errCode, G4ExceptionDescription &ed)
void CommandFailed (G4ExceptionDescription &ed)
G4int IfCommandFailed ()
G4String & GetFailureDescription ()
void ResetFailure ()
Additional Inherited Members
Static Public Member Functions inherited from G4UIcommand
static G4String ConvertToString (G4bool boolVal)
static G4String ConvertToString (G4int intValue)
static G4String ConvertToString (G4double doubleValue)
static G4String ConvertToString (G4double doubleValue, const char *unitName)
static G4String ConvertToString (G4ThreeVector vec)
static G4String ConvertToString (G4ThreeVector vec, const char *unitName)
static G4bool ConvertToBool (const char *st)
static G4int ConvertToInt (const char *st)
static G4double ConvertToDouble (const char *st)
static G4double ConvertToDimensionedDouble (const char *st)
static G4ThreeVector ConvertTo3Vector (const char *st)
static G4ThreeVector ConvertToDimensioned3Vector (const char *st)
static G4double ValueOf (const char *unitName)
static G4String CategoryOf (const char *unitName)
static G4String UnitsList (const char *unitCategory)
Protected Types inherited from G4UIcommand
using yystype = G4UItokenNum::yystype
using tokenNum = G4UItokenNum::tokenNum
Protected Member Functions inherited from G4UIcommand
G4int CheckNewValue (const char *newValue)
Protected Attributes inherited from G4UIcommand
G4bool toBeBroadcasted
G4bool toBeFlushed
G4bool workerThreadOnly
G4int commandFailureCode
G4String failureDescription
Detailed Description
Definition at line 76 of file G4UIcmdWithNucleusLimits.hh.
View newest version in sPHENIX GitHub at line 76 of file G4UIcmdWithNucleusLimits.hh
Constructor & Destructor Documentation
G4UIcmdWithNucleusLimits::G4UIcmdWithNucleusLimits (const char * theCommandPath, G4UImessenger * theMessenger)
Definition at line 32 of file G4UIcmdWithNucleusLimits.cc.
View newest version in sPHENIX GitHub at line 32 of file G4UIcmdWithNucleusLimits.cc
G4UIcmdWithNucleusLimits::~G4UIcmdWithNucleusLimits ()
Definition at line 47 of file G4UIcmdWithNucleusLimits.cc.
View newest version in sPHENIX GitHub at line 47 of file G4UIcmdWithNucleusLimits.cc
Member Function Documentation
G4String G4UIcmdWithNucleusLimits::ConvertToString (G4NucleusLimits nuclimit)
Definition at line 67 of file G4UIcmdWithNucleusLimits.cc.
View newest version in sPHENIX GitHub at line 67 of file G4UIcmdWithNucleusLimits.cc
References G4NucleusLimits::GetAMax(), G4NucleusLimits::GetAMin(), G4NucleusLimits::GetZMax(), and G4NucleusLimits::GetZMin().
G4NucleusLimits G4UIcmdWithNucleusLimits::GetNewNucleusLimitsValue (G4String paramString)
Definition at line 54 of file G4UIcmdWithNucleusLimits.cc.
View newest version in sPHENIX GitHub at line 54 of file G4UIcmdWithNucleusLimits.cc
Referenced by G4RadioactiveDecayBaseMessenger::SetNewValue(), and G4RadioactiveDecaymessenger::SetNewValue().
void G4UIcmdWithNucleusLimits::SetDefaultValue (G4NucleusLimits defVal)
Definition at line 100 of file G4UIcmdWithNucleusLimits.cc.
View newest version in sPHENIX GitHub at line 100 of file G4UIcmdWithNucleusLimits.cc
References G4NucleusLimits::GetAMax(), G4NucleusLimits::GetAMin(), G4UIcommand::GetParameter(), G4NucleusLimits::GetZMax(), G4NucleusLimits::GetZMin(), and G4UIparameter::SetDefaultValue().
void G4UIcmdWithNucleusLimits::SetParameterName (const char * theNameAMin, const char * theNameAMax, const char * theNameZMin, const char * theNameZMax, G4bool omittable, G4bool currentAsDefault = true)
Definition at line 78 of file G4UIcmdWithNucleusLimits.cc.
View newest version in sPHENIX GitHub at line 78 of file G4UIcmdWithNucleusLimits.cc
References G4UIparameter::SetCurrentAsDefault(), G4UIparameter::SetOmittable(), and G4UIparameter::SetParameterName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/include/G4UIcmdWithNucleusLimits.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/radioactive_decay/src/G4UIcmdWithNucleusLimits.cc