ECCE @ EIC Software: G4Solver< Function > Class Template Reference
G4Solver< Function > Class Template Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4Solver.hh>
Public Types
enum { DefaultMaxIter = 100 }
Public Member Functions
G4Solver ()
G4Solver (const G4int iterations, const G4double tol)
G4Solver (const G4Solver &right)
~G4Solver ()
G4Solver & operator= (const G4Solver &right)
G4bool operator== (const G4Solver &right) const
G4bool operator!= (const G4Solver &right) const
G4int GetMaxIterations (void) const
void SetMaxIterations (const G4int iterations)
G4double GetTolerance (void) const
void SetTolerance (const G4double epsilon)
G4double GetIntervalLowerLimit (void) const
G4double GetIntervalUpperLimit (void) const
void SetIntervalLimits (const G4double Limit1, const G4double Limit2)
G4double GetRoot (void) const
G4bool Bisection (Function &theFunction)
G4bool RegulaFalsi (Function &theFunction)
G4bool Brent (Function &theFunction)
G4bool Crenshaw (Function &theFunction)
Private Attributes
G4int MaxIter
G4double tolerance
G4double a
G4double b
G4double root
Detailed Description
template<class Function>
class G4Solver< Function >
Definition at line 40 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 40 of file G4Solver.hh
Member Enumeration Documentation
template<class Function> anonymous enum
Enumerator:
DefaultMaxIter
Definition at line 43 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 43 of file G4Solver.hh
Constructor & Destructor Documentation
template<class Function> G4Solver< Function >::G4Solver () inline
Definition at line 46 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 46 of file G4Solver.hh
template<class Function> G4Solver< Function >::G4Solver (const G4int iterations, const G4double tol) inline
Definition at line 49 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 49 of file G4Solver.hh
template<class Function > G4Solver< Function >::G4Solver (const G4Solver< Function > & right)
Definition at line 35 of file G4Solver.cc.
View newest version in sPHENIX GitHub at line 35 of file G4Solver.cc
References a, G4Solver< Function >::a, b, G4Solver< Function >::b, G4Solver< Function >::MaxIter, G4Solver< Function >::root, and G4Solver< Function >::tolerance.
template<class Function> G4Solver< Function >::~G4Solver () inline
Definition at line 57 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 57 of file G4Solver.hh
Member Function Documentation
template<class Function> G4bool G4Solver< Function >::Bisection (Function & theFunction)
template<class Function> G4bool G4Solver< Function >::Brent (Function & theFunction)
Referenced by G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), and G4StatMFMacroTemperature::CalcTemperature().
template<class Function> G4bool G4Solver< Function >::Crenshaw (Function & theFunction)
Referenced by G4StatMFMacroTemperature::CalcTemperature().
template<class Function> G4double G4Solver< Function >::GetIntervalLowerLimit (void) const inline
Definition at line 71 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 71 of file G4Solver.hh
References G4Solver< Function >::a.
template<class Function> G4double G4Solver< Function >::GetIntervalUpperLimit (void) const inline
Definition at line 72 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 72 of file G4Solver.hh
References G4Solver< Function >::b.
template<class Function> G4int G4Solver< Function >::GetMaxIterations (void) const inline
Definition at line 64 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 64 of file G4Solver.hh
References G4Solver< Function >::MaxIter.
template<class Function> G4double G4Solver< Function >::GetRoot (void) const inline
Definition at line 76 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 76 of file G4Solver.hh
References G4Solver< Function >::root.
Referenced by G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), and G4StatMFMacroTemperature::CalcTemperature().
template<class Function> G4double G4Solver< Function >::GetTolerance (void) const inline
Definition at line 67 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 67 of file G4Solver.hh
References G4Solver< Function >::tolerance.
template<class Function > G4bool G4Solver< Function >::operator!= (const G4Solver< Function > & right) const
Definition at line 64 of file G4Solver.cc.
View newest version in sPHENIX GitHub at line 64 of file G4Solver.cc
References HepGeom::BasicVector3D< T >::operator==().
template<class Function > G4Solver< Function > & G4Solver< Function >::operator= (const G4Solver< Function > & right)
Definition at line 46 of file G4Solver.cc.
View newest version in sPHENIX GitHub at line 46 of file G4Solver.cc
References a, G4Solver< Function >::a, b, G4Solver< Function >::b, G4Solver< Function >::MaxIter, G4Solver< Function >::root, and G4Solver< Function >::tolerance.
template<class Function > G4bool G4Solver< Function >::operator== (const G4Solver< Function > & right) const
Definition at line 57 of file G4Solver.cc.
View newest version in sPHENIX GitHub at line 57 of file G4Solver.cc
template<class Function> G4bool G4Solver< Function >::RegulaFalsi (Function & theFunction)
template<class Function> void G4Solver< Function >::SetIntervalLimits (const G4double Limit1, const G4double Limit2)
Referenced by G4StatMFMacroMultiplicity::CalcChemicalPotentialMu(), G4StatMFMacroChemicalPotential::CalcChemicalPotentialNu(), and G4StatMFMacroTemperature::CalcTemperature().
template<class Function> void G4Solver< Function >::SetMaxIterations (const G4int iterations) inline
Definition at line 65 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 65 of file G4Solver.hh
References G4Solver< Function >::MaxIter.
template<class Function> void G4Solver< Function >::SetTolerance (const G4double epsilon) inline
Definition at line 68 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 68 of file G4Solver.hh
References epsilon(), and G4Solver< Function >::tolerance.
Member Data Documentation
template<class Function> G4double G4Solver< Function >::a private
Definition at line 101 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 101 of file G4Solver.hh
Referenced by G4Solver< Function >::G4Solver(), G4Solver< Function >::GetIntervalLowerLimit(), and G4Solver< Function >::operator=().
template<class Function> G4double G4Solver< Function >::b private
Definition at line 102 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 102 of file G4Solver.hh
Referenced by G4Solver< Function >::G4Solver(), G4Solver< Function >::GetIntervalUpperLimit(), and G4Solver< Function >::operator=().
template<class Function> G4int G4Solver< Function >::MaxIter private
Definition at line 95 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 95 of file G4Solver.hh
Referenced by G4Solver< Function >::G4Solver(), G4Solver< Function >::GetMaxIterations(), G4Solver< Function >::operator=(), and G4Solver< Function >::SetMaxIterations().
template<class Function> G4double G4Solver< Function >::root private
Definition at line 105 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 105 of file G4Solver.hh
Referenced by G4Solver< Function >::G4Solver(), G4Solver< Function >::GetRoot(), and G4Solver< Function >::operator=().
template<class Function> G4double G4Solver< Function >::tolerance private
Definition at line 98 of file G4Solver.hh.
View newest version in sPHENIX GitHub at line 98 of file G4Solver.hh
Referenced by G4Solver< Function >::G4Solver(), G4Solver< Function >::GetTolerance(), G4Solver< Function >::operator=(), and G4Solver< Function >::SetTolerance().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4Solver.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4Solver.cc