ECCE @ EIC Software: G4LivermoreBremsstrahlungModel Class Reference
G4LivermoreBremsstrahlungModel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermoreBremsstrahlungModel.hh>
Public Member Functions
G4LivermoreBremsstrahlungModel (const G4ParticleDefinition *p=0, const G4String &nam="LowEnBrem")
virtual ~G4LivermoreBremsstrahlungModel ()
virtual void Initialise (const G4ParticleDefinition *, const G4DataVector &)
virtual void InitialiseForElement (const G4ParticleDefinition *, G4int Z)
virtual void SampleSecondaries (std::vector< G4DynamicParticle * > *, const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double cutEnergy, G4double maxEnergy)
void SetBicubicInterpolationFlag (G4bool)
Public Member Functions inherited from G4eBremsstrahlungRelModel
G4eBremsstrahlungRelModel (const G4ParticleDefinition *p=0, const G4String &nam="eBremLPM")
virtual ~G4eBremsstrahlungRelModel ()
virtual void InitialiseLocal (const G4ParticleDefinition *, G4VEmModel *masterModel) override
virtual G4double ComputeDEDXPerVolume (const G4Material *, const G4ParticleDefinition *, G4double ekin, G4double cutEnergy) override
virtual G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, G4double ekin, G4double zet, G4double, G4double cutEnergy, G4double maxEnergy=DBL_MAX) override
virtual void SetupForMaterial (const G4ParticleDefinition *, const G4Material *, G4double) override
virtual G4double MinPrimaryEnergy (const G4Material *, const G4ParticleDefinition *, G4double cutEnergy) override
Public Member Functions inherited from G4VEmModel
G4VEmModel (const G4String &nam)
virtual ~G4VEmModel ()
virtual void InitialiseForMaterial (const G4ParticleDefinition *, const G4Material *)
virtual G4double CrossSectionPerVolume (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double GetPartialCrossSection (const G4Material *, G4int level, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double ComputeCrossSectionPerShell (const G4ParticleDefinition *, G4int Z, G4int shellIdx, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
virtual G4double ChargeSquareRatio (const G4Track &)
virtual G4double GetChargeSquareRatio (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual G4double GetParticleCharge (const G4ParticleDefinition *, const G4Material *, G4double kineticEnergy)
virtual void StartTracking (G4Track *)
virtual void CorrectionsAlongStep (const G4MaterialCutsCouple *, const G4DynamicParticle *, G4double &eloss, G4double &niel, G4double length)
virtual G4double Value (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy)
virtual G4double MinEnergyCut (const G4ParticleDefinition *, const G4MaterialCutsCouple *)
virtual void DefineForRegion (const G4Region *)
virtual void ModelDescription (std::ostream &outFile) const
void InitialiseElementSelectors (const G4ParticleDefinition *, const G4DataVector &)
std::vector
< G4EmElementSelector * > * GetElementSelectors ()
void SetElementSelectors (std::vector< G4EmElementSelector * > *)
virtual G4double ComputeDEDX (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=DBL_MAX)
G4double CrossSection (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeMeanFreePath (const G4ParticleDefinition *, G4double kineticEnergy, const G4Material *, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4double ComputeCrossSectionPerAtom (const G4ParticleDefinition *, const G4Element *, G4double kinEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectTargetAtom (const G4MaterialCutsCouple *, const G4ParticleDefinition *, G4double kineticEnergy, G4double logKineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
const G4Element * SelectRandomAtom (const G4Material *, const G4ParticleDefinition *, G4double kineticEnergy, G4double cutEnergy=0.0, G4double maxEnergy=DBL_MAX)
G4int SelectRandomAtomNumber (const G4Material *)
G4int SelectIsotopeNumber (const G4Element *)
void SetParticleChange (G4VParticleChange *, G4VEmFluctuationModel *f=nullptr)
void SetCrossSectionTable (G4PhysicsTable *, G4bool isLocal)
G4ElementData * GetElementData ()
G4PhysicsTable * GetCrossSectionTable ()
G4VEmFluctuationModel * GetModelOfFluctuations ()
G4VEmAngularDistribution * GetAngularDistribution ()
G4VEmModel * GetTripletModel ()
void SetTripletModel (G4VEmModel *)
void SetAngularDistribution (G4VEmAngularDistribution *)
G4double HighEnergyLimit () const
G4double LowEnergyLimit () const
G4double HighEnergyActivationLimit () const
G4double LowEnergyActivationLimit () const
G4double PolarAngleLimit () const
G4double SecondaryThreshold () const
G4bool LPMFlag () const
G4bool DeexcitationFlag () const
G4bool ForceBuildTableFlag () const
G4bool UseAngularGeneratorFlag () const
void SetAngularGeneratorFlag (G4bool)
void SetHighEnergyLimit (G4double)
void SetLowEnergyLimit (G4double)
void SetActivationHighEnergyLimit (G4double)
void SetActivationLowEnergyLimit (G4double)
G4bool IsActive (G4double kinEnergy) const
void SetPolarAngleLimit (G4double)
void SetSecondaryThreshold (G4double)
void SetLPMFlag (G4bool val)
void SetDeexcitationFlag (G4bool val)
void SetForceBuildTable (G4bool val)
void SetFluctuationFlag (G4bool val)
void SetMasterThread (G4bool val)
G4bool IsMaster () const
void SetUseBaseMaterials (G4bool val)
G4bool UseBaseMaterials () const
G4double MaxSecondaryKinEnergy (const G4DynamicParticle *dynParticle)
const G4String & GetName () const
void SetCurrentCouple (const G4MaterialCutsCouple *)
const G4Element * GetCurrentElement () const
const G4Isotope * GetCurrentIsotope () const
G4bool IsLocked () const
void SetLocked (G4bool)
Protected Member Functions
virtual G4double ComputeDXSectionPerAtom (G4double gammaEnergy)
virtual G4String DirectoryPath () const
Protected Member Functions inherited from G4eBremsstrahlungRelModel
void SetParticle (const G4ParticleDefinition *p)
Protected Member Functions inherited from G4VEmModel
G4ParticleChangeForLoss * GetParticleChangeForLoss ()
G4ParticleChangeForGamma * GetParticleChangeForGamma ()
virtual G4double MaxSecondaryEnergy (const G4ParticleDefinition *, G4double kineticEnergy)
const G4MaterialCutsCouple * CurrentCouple () const
void SetCurrentElement (const G4Element *)
Private Member Functions
void ReadData (G4int Z, const char *path=0)
G4LivermoreBremsstrahlungModel & operator= (const G4LivermoreBremsstrahlungModel &right)
G4LivermoreBremsstrahlungModel (const G4LivermoreBremsstrahlungModel &)
Private Attributes
G4int nwarn
size_t idx
size_t idy
G4bool useBicubicInterpolation
Static Private Attributes
static G4Physics2DVector * dataSB [101] = {0}
static G4double ylimit [101] = {0.0}
static G4double expnumlim = -12.
Additional Inherited Members
Protected Attributes inherited from G4eBremsstrahlungRelModel
G4bool fIsElectron
G4bool fIsScatOffElectron
G4bool fIsLPMActive
G4int fCurrentIZ
G4double fPrimaryParticleMass
G4double fPrimaryKinEnergy
G4double fPrimaryTotalEnergy
G4double fDensityFactor
G4double fDensityCorr
G4double fLowestKinEnergy
G4double fNucTerm
G4double fSumTerm
const G4ParticleDefinition * fPrimaryParticle
G4ParticleDefinition * fGammaParticle
G4ParticleChangeForLoss * fParticleChange
Static Protected Attributes inherited from G4eBremsstrahlungRelModel
static const G4double gBremFactor
static const G4double gMigdalConstant
Detailed Description
Definition at line 60 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 60 of file G4LivermoreBremsstrahlungModel.hh
Constructor & Destructor Documentation
G4LivermoreBremsstrahlungModel::G4LivermoreBremsstrahlungModel (const G4ParticleDefinition * p = 0, const G4String & nam = "LowEnBrem")
Definition at line 82 of file G4LivermoreBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 82 of file G4LivermoreBremsstrahlungModel.cc
References eV, idx, idy, nwarn, G4VEmModel::SetAngularDistribution(), G4VEmModel::SetLowEnergyLimit(), and G4VEmModel::SetLPMFlag().
G4LivermoreBremsstrahlungModel::~G4LivermoreBremsstrahlungModel () virtual
Definition at line 95 of file G4LivermoreBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 95 of file G4LivermoreBremsstrahlungModel.cc
References dataSB, and G4VEmModel::IsMaster().
G4LivermoreBremsstrahlungModel::G4LivermoreBremsstrahlungModel (const G4LivermoreBremsstrahlungModel &) private
Member Function Documentation
G4double G4LivermoreBremsstrahlungModel::ComputeDXSectionPerAtom (G4double gammaEnergy) protected virtual
Reimplemented from G4eBremsstrahlungRelModel.
Definition at line 195 of file G4LivermoreBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 195 of file G4LivermoreBremsstrahlungModel.cc
References alpha, Acts::VectorHelpers::cross(), dataSB, e2, expnumlim, G4eBremsstrahlungRelModel::fCurrentIZ, G4eBremsstrahlungRelModel::fIsElectron, G4eBremsstrahlungRelModel::fPrimaryKinEnergy, G4eBremsstrahlungRelModel::fPrimaryParticleMass, G4eBremsstrahlungRelModel::fPrimaryTotalEnergy, G4Exp(), G4Log(), G4eBremsstrahlungRelModel::gBremFactor, idx, idy, InitialiseForElement(), MeV, millibarn, G4Physics2DVector::Value(), x, y, and Z.
G4String G4LivermoreBremsstrahlungModel::DirectoryPath () const protected virtual
Definition at line 138 of file G4LivermoreBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 138 of file G4LivermoreBremsstrahlungModel.cc
Referenced by ReadData().
void G4LivermoreBremsstrahlungModel::Initialise (const G4ParticleDefinition * p, const G4DataVector & cuts) virtual
Reimplemented from G4eBremsstrahlungRelModel.
Definition at line 109 of file G4LivermoreBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 109 of file G4LivermoreBremsstrahlungModel.cc
References dataSB, G4Element::GetElementTable(), G4Element::GetNumberOfElements(), G4eBremsstrahlungRelModel::Initialise(), G4VEmModel::IsMaster(), ReadData(), and Z.
void G4LivermoreBremsstrahlungModel::InitialiseForElement (const G4ParticleDefinition * , G4int Z) virtual
Reimplemented from G4VEmModel.
Definition at line 374 of file G4LivermoreBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 374 of file G4LivermoreBremsstrahlungModel.cc
References dataSB, ReadData(), and G4TemplateAutoLock< _Mutex_t >::unlock().
Referenced by ComputeDXSectionPerAtom().
G4LivermoreBremsstrahlungModel& G4LivermoreBremsstrahlungModel::operator= (const G4LivermoreBremsstrahlungModel & right) private
void G4LivermoreBremsstrahlungModel::ReadData (G4int Z, const char * path = 0) private
Definition at line 145 of file G4LivermoreBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 145 of file G4LivermoreBremsstrahlungModel.cc
References dataSB, DirectoryPath(), emaxlog, FatalException, fin, G4Exception(), idx, idy, G4Physics2DVector::Retrieve(), G4Physics2DVector::SetBicubicInterpolation(), useBicubicInterpolation, v, G4Physics2DVector::Value(), ylimit, and Z.
Referenced by Initialise(), and InitialiseForElement().
void G4LivermoreBremsstrahlungModel::SampleSecondaries (std::vector< G4DynamicParticle * > * vdp, const G4MaterialCutsCouple * couple, const G4DynamicParticle * dp, G4double cutEnergy, G4double maxEnergy) virtual
Reimplemented from G4eBremsstrahlungRelModel.
Definition at line 239 of file G4LivermoreBremsstrahlungModel.cc.
View newest version in sPHENIX GitHub at line 239 of file G4LivermoreBremsstrahlungModel.cc
References dataSB, e1, e2, source.hepunit::electron_mass_c2, elowlimit, emax, epeaklimit, expnumlim, G4eBremsstrahlungRelModel::fCurrentIZ, G4eBremsstrahlungRelModel::fDensityCorr, G4eBremsstrahlungRelModel::fGammaParticle, source.hepunit::fine_structure_const, G4eBremsstrahlungRelModel::fIsElectron, G4eBremsstrahlungRelModel::fParticleChange, G4eBremsstrahlungRelModel::fPrimaryParticle, G4eBremsstrahlungRelModel::fPrimaryParticleMass, G4eBremsstrahlungRelModel::fPrimaryTotalEnergy, fStopAndKill, G4Exception(), G4Exp(), G4Log(), G4UniformRand, G4VEmModel::GetAngularDistribution(), G4DynamicParticle::GetKineticEnergy(), G4MaterialCutsCouple::GetMaterial(), G4DynamicParticle::GetMomentumDirection(), G4ParticleDefinition::GetParticleName(), idx, idy, JustWarning, MeV, min, nwarn, G4VParticleChange::ProposeTrackStatus(), G4VEmAngularDistribution::SampleDirection(), G4VEmModel::SecondaryThreshold(), G4VEmModel::SelectRandomAtom(), G4ParticleChangeForLoss::SetProposedKineticEnergy(), G4ParticleChangeForLoss::SetProposedMomentumDirection(), G4eBremsstrahlungRelModel::SetupForMaterial(), twopi, v, G4Physics2DVector::Value(), G4VEmModel::Value(), x, x1, xmax, xmin, y, ylimit, and Z.
void G4LivermoreBremsstrahlungModel::SetBicubicInterpolationFlag (G4bool val) inline
Definition at line 105 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4LivermoreBremsstrahlungModel.hh
References useBicubicInterpolation.
Member Data Documentation
G4Physics2DVector * G4LivermoreBremsstrahlungModel::dataSB = {0} static private
Definition at line 96 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 96 of file G4LivermoreBremsstrahlungModel.hh
Referenced by ComputeDXSectionPerAtom(), Initialise(), InitialiseForElement(), ReadData(), SampleSecondaries(), and ~G4LivermoreBremsstrahlungModel().
G4double G4LivermoreBremsstrahlungModel::expnumlim = -12. static private
Definition at line 98 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4LivermoreBremsstrahlungModel.hh
Referenced by ComputeDXSectionPerAtom(), and SampleSecondaries().
size_t G4LivermoreBremsstrahlungModel::idx private
Definition at line 100 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 100 of file G4LivermoreBremsstrahlungModel.hh
Referenced by ComputeDXSectionPerAtom(), G4LivermoreBremsstrahlungModel(), ReadData(), and SampleSecondaries().
size_t G4LivermoreBremsstrahlungModel::idy private
Definition at line 101 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4LivermoreBremsstrahlungModel.hh
Referenced by ComputeDXSectionPerAtom(), G4LivermoreBremsstrahlungModel(), ReadData(), and SampleSecondaries().
G4int G4LivermoreBremsstrahlungModel::nwarn private
Definition at line 99 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 99 of file G4LivermoreBremsstrahlungModel.hh
Referenced by G4LivermoreBremsstrahlungModel(), and SampleSecondaries().
G4bool G4LivermoreBremsstrahlungModel::useBicubicInterpolation private
Definition at line 102 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4LivermoreBremsstrahlungModel.hh
Referenced by ReadData(), and SetBicubicInterpolationFlag().
G4double G4LivermoreBremsstrahlungModel::ylimit = {0.0} static private
Definition at line 97 of file G4LivermoreBremsstrahlungModel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4LivermoreBremsstrahlungModel.hh
Referenced by ReadData(), and SampleSecondaries().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/include/G4LivermoreBremsstrahlungModel.hh
geant4/tree/geant4-10.6-release/source/processes/electromagnetic/lowenergy/src/G4LivermoreBremsstrahlungModel.cc