ECCE @ EIC Software: geant4/tree/geant4-10.6-release/environments/g4py/source/processes/pyG4ProcessManager.cc File Reference
pyG4ProcessManager.cc File Reference
#include <boost/python.hpp>
#include "G4ProcessManager.hh"
Namespaces
namespace pyG4ProcessManager
Functions
list pyG4ProcessManager::f_GetProcessList (const G4ProcessManager *procMgr)
list pyG4ProcessManager::f_GetProcessVector (const G4ProcessManager *procMgr, G4ProcessVectorDoItIndex idx, G4ProcessVectorTypeIndex typ=typeGPIL)
pyG4ProcessManager::BOOST_PYTHON_FUNCTION_OVERLOADS (g_GetProcessVector, f_GetProcessVector, 2, 3) list f_GetAtRestProcessVector(const G4ProcessManager *procMgr
void export_G4ProcessManager ()
Variables
G4ProcessVectorTypeIndex pyG4ProcessManager::typ
G4VProcess *(G4ProcessManager::* pyG4ProcessManager::f2_RemoveProcess)(G4int) = &G4ProcessManager::RemoveProcess
G4VProcess *(G4ProcessManager::* pyG4ProcessManager::f1_SetProcessActivation)(G4VProcess *, G4bool) = &G4ProcessManager::SetProcessActivation
G4VProcess *(G4ProcessManager::* pyG4ProcessManager::f2_SetProcessActivation)(G4int, G4bool) = &G4ProcessManager::SetProcessActivation
G4bool(G4ProcessManager::* pyG4ProcessManager::f1_GetProcessActivation)(G4VProcess *) const = &G4ProcessManager::GetProcessActivation
G4bool(G4ProcessManager::* pyG4ProcessManager::f2_GetProcessActivation)(G4int) const = &G4ProcessManager::GetProcessActivation
Function Documentation
void export_G4ProcessManager ()
Definition at line 170 of file pyG4ProcessManager.cc.
View newest version in sPHENIX GitHub at line 170 of file pyG4ProcessManager.cc
References G4ProcessManager::AddContinuousProcess(), G4ProcessManager::AddDiscreteProcess(), G4ProcessManager::AddProcess(), G4ProcessManager::AddRestProcess(), G4ProcessManager::DumpInfo(), pyG4ProcessManager::f1_GetProcessActivation, pyG4ProcessManager::f1_SetProcessActivation, pyG4ProcessManager::f2_GetProcessActivation, pyG4ProcessManager::f2_RemoveProcess, pyG4ProcessManager::f2_SetProcessActivation, pyG4ProcessManager::f_GetProcessList(), pyG4ProcessManager::f_GetProcessVector(), G4ProcessManager::GetAlongStepIndex(), G4ProcessManager::GetAtRestIndex(), G4ProcessManager::GetParticleType(), G4ProcessManager::GetPostStepIndex(), G4ProcessManager::GetProcessIndex(), G4ProcessManager::GetProcessListLength(), G4ProcessManager::GetProcessOrdering(), G4ProcessManager::GetProcessVectorIndex(), G4ProcessManager::GetVerboseLevel(), idxAll, idxAlongStep, idxAtRest, idxPostStep, ordDefault, ordInActive, ordLast, G4ProcessManager::SetParticleType(), G4ProcessManager::SetProcessOrdering(), G4ProcessManager::SetProcessOrderingToFirst(), G4ProcessManager::SetProcessOrderingToLast(), G4ProcessManager::SetVerboseLevel(), and typeDoIt.
Referenced by BOOST_PYTHON_MODULE().