ECCE @ EIC Software: G4BinaryDeuteronBuilder Class Reference
G4BinaryDeuteronBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BinaryDeuteronBuilder.hh>
Public Member Functions
G4BinaryDeuteronBuilder ()
virtual ~G4BinaryDeuteronBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4DeuteronInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
virtual void SetMaxEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VDeuteronBuilder
G4VDeuteronBuilder ()=default
virtual ~G4VDeuteronBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
Private Attributes
G4BinaryCascade * theModel
G4double theMin
G4double theMax
Detailed Description
Definition at line 52 of file G4BinaryDeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 52 of file G4BinaryDeuteronBuilder.hh
Constructor & Destructor Documentation
G4BinaryDeuteronBuilder::G4BinaryDeuteronBuilder ()
Definition at line 47 of file G4BinaryDeuteronBuilder.cc.
View newest version in sPHENIX GitHub at line 47 of file G4BinaryDeuteronBuilder.cc
References G4HadronicParameters::GetMaxEnergyTransitionFTF_Cascade(), G4HadronicParameters::Instance(), theMax, theMin, and theModel.
virtual G4BinaryDeuteronBuilder::~G4BinaryDeuteronBuilder () inline virtual
Definition at line 56 of file G4BinaryDeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 56 of file G4BinaryDeuteronBuilder.hh
Member Function Documentation
virtual void G4BinaryDeuteronBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VDeuteronBuilder.
Definition at line 58 of file G4BinaryDeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 58 of file G4BinaryDeuteronBuilder.hh
void G4BinaryDeuteronBuilder::Build (G4DeuteronInelasticProcess * aP) final override virtual
Implements G4VDeuteronBuilder.
Definition at line 55 of file G4BinaryDeuteronBuilder.cc.
View newest version in sPHENIX GitHub at line 55 of file G4BinaryDeuteronBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4BinaryDeuteronBuilder::SetMaxEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 62 of file G4BinaryDeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 62 of file G4BinaryDeuteronBuilder.hh
References theMax.
virtual void G4BinaryDeuteronBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 61 of file G4BinaryDeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 61 of file G4BinaryDeuteronBuilder.hh
References theMin.
Member Data Documentation
G4double G4BinaryDeuteronBuilder::theMax private
Definition at line 70 of file G4BinaryDeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4BinaryDeuteronBuilder.hh
Referenced by Build(), G4BinaryDeuteronBuilder(), and SetMaxEnergy().
G4double G4BinaryDeuteronBuilder::theMin private
Definition at line 69 of file G4BinaryDeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 69 of file G4BinaryDeuteronBuilder.hh
Referenced by Build(), G4BinaryDeuteronBuilder(), and SetMinEnergy().
G4BinaryCascade* G4BinaryDeuteronBuilder::theModel private
Definition at line 68 of file G4BinaryDeuteronBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4BinaryDeuteronBuilder.hh
Referenced by Build(), and G4BinaryDeuteronBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4BinaryDeuteronBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4BinaryDeuteronBuilder.cc