ECCE @ EIC Software: G4UIaliasList Class Reference
G4UIaliasList Class Reference
#include <geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIaliasList.hh>
Public Member Functions
G4UIaliasList ()
~G4UIaliasList ()
void RemoveAlias (const char *aliasName)
void ChangeAlias (const char *aliasName, const char *aliasValue)
G4String * FindAlias (const char *aliasName)
void List ()
Private Member Functions
G4bool operator== (const G4UIaliasList &right) const
G4bool operator!= (const G4UIaliasList &right) const
void AddNewAlias (const char *aliasName, const char *aliasValue)
G4int FindAliasID (const char *aliasName)
Private Attributes
std::vector< G4String * > alias
std::vector< G4String * > value
Detailed Description
Definition at line 42 of file G4UIaliasList.hh.
View newest version in sPHENIX GitHub at line 42 of file G4UIaliasList.hh
Constructor & Destructor Documentation
G4UIaliasList::G4UIaliasList ()
Definition at line 32 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 32 of file G4UIaliasList.cc
G4UIaliasList::~G4UIaliasList ()
Definition at line 35 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 35 of file G4UIaliasList.cc
References alias.
Member Function Documentation
void G4UIaliasList::AddNewAlias (const char * aliasName, const char * aliasValue) private
Definition at line 54 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 54 of file G4UIaliasList.cc
References alias, FindAlias(), G4cerr, and G4endl.
Referenced by ChangeAlias().
void G4UIaliasList::ChangeAlias (const char * aliasName, const char * aliasValue)
Definition at line 81 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 81 of file G4UIaliasList.cc
References AddNewAlias(), and FindAliasID().
Referenced by G4UImanager::SetAlias().
G4String * G4UIaliasList::FindAlias (const char * aliasName)
Definition at line 92 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 92 of file G4UIaliasList.cc
References FindAliasID().
Referenced by AddNewAlias(), and G4UImanager::SolveAlias().
G4int G4UIaliasList::FindAliasID (const char * aliasName) private
Definition at line 100 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 100 of file G4UIaliasList.cc
References alias.
Referenced by ChangeAlias(), FindAlias(), and RemoveAlias().
void G4UIaliasList::List ()
Definition at line 108 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 108 of file G4UIaliasList.cc
References alias, G4cout, G4endl, and tmp.
Referenced by G4UImanager::ListAlias().
G4bool G4UIaliasList::operator!= (const G4UIaliasList & right) const private
Definition at line 49 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 49 of file G4UIaliasList.cc
G4bool G4UIaliasList::operator== (const G4UIaliasList & right) const private
Definition at line 44 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 44 of file G4UIaliasList.cc
void G4UIaliasList::RemoveAlias (const char * aliasName)
Definition at line 68 of file G4UIaliasList.cc.
View newest version in sPHENIX GitHub at line 68 of file G4UIaliasList.cc
References alias, FindAliasID(), G4cerr, and G4endl.
Referenced by G4UImanager::RemoveAlias().
Member Data Documentation
std::vector<G4String*> G4UIaliasList::alias private
Definition at line 63 of file G4UIaliasList.hh.
View newest version in sPHENIX GitHub at line 63 of file G4UIaliasList.hh
Referenced by AddNewAlias(), FindAliasID(), List(), RemoveAlias(), and ~G4UIaliasList().
std::vector<G4String*> G4UIaliasList::value private
Definition at line 64 of file G4UIaliasList.hh.
View newest version in sPHENIX GitHub at line 64 of file G4UIaliasList.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/intercoms/include/G4UIaliasList.hh
geant4/tree/geant4-10.6-release/source/intercoms/src/G4UIaliasList.cc