ECCE @ EIC Software: G4ErrorFreeTrajState Class Reference
G4ErrorFreeTrajState Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorFreeTrajState.hh>
Public Member Functions
G4ErrorFreeTrajState ()
G4ErrorFreeTrajState (const G4String &partName, const G4Point3D &pos, const G4Vector3D &mom, const G4ErrorTrajErr &errmat=G4ErrorTrajErr(5, 0))
G4ErrorFreeTrajState (const G4ErrorSurfaceTrajState &tpOS)
~G4ErrorFreeTrajState ()
virtual G4int Update (const G4Track *aTrack)
virtual G4int PropagateError (const G4Track *aTrack)
virtual void Dump (std::ostream &out=G4cout) const
virtual void SetPosition (const G4Point3D pos)
virtual void SetMomentum (const G4Vector3D &mom)
void SetParameters (const G4Point3D &pos, const G4Vector3D &mom)
G4ErrorFreeTrajParam GetParameters () const
G4ErrorMatrix GetTransfMat () const
Public Member Functions inherited from G4ErrorTrajState
G4ErrorTrajState ()
G4ErrorTrajState (const G4String &partType, const G4Point3D &pos, const G4Vector3D &mom, const G4ErrorTrajErr &errmat=G4ErrorTrajErr(5, 0))
virtual ~G4ErrorTrajState ()
void SetData (const G4String &partType, const G4Point3D &pos, const G4Vector3D &mom)
void BuildCharge ()
void UpdatePosMom (const G4Point3D &pos, const G4Vector3D &mom)
void DumpPosMomError (std::ostream &out=G4cout) const
const G4String & GetParticleType () const
void SetParticleType (const G4String &partType)
G4Point3D GetPosition () const
G4Vector3D GetMomentum () const
G4ErrorTrajErr GetError () const
virtual void SetError (G4ErrorTrajErr em)
G4Track * GetG4Track () const
void SetG4Track (G4Track *trk)
G4double GetCharge () const
void SetCharge (G4double ch)
virtual G4eTSType GetTSType () const
Private Member Functions
void Init ()
G4int PropagateErrorMSC (const G4Track *aTrack)
void CalculateEffectiveZandA (const G4Material *mate, double &effZ, double &effA)
G4int PropagateErrorIoni (const G4Track *aTrack)
Private Attributes
G4ErrorFreeTrajParam fTrajParam
G4ErrorMatrix theTransfMat
G4bool theFirstStep
Friends
std::ostream & operator<< (std::ostream &, const G4ErrorFreeTrajState &ts)
Additional Inherited Members
Protected Attributes inherited from G4ErrorTrajState
G4String fParticleType
G4Point3D fPosition
G4Vector3D fMomentum
G4double fCharge
G4ErrorTrajErr fError
G4eTSType theTSType
G4Track * theG4Track
G4int iverbose
Detailed Description
Definition at line 64 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 64 of file G4ErrorFreeTrajState.hh
Constructor & Destructor Documentation
G4ErrorFreeTrajState::G4ErrorFreeTrajState () inline
Definition at line 68 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 68 of file G4ErrorFreeTrajState.hh
G4ErrorFreeTrajState::G4ErrorFreeTrajState (const G4String & partName, const G4Point3D & pos, const G4Vector3D & mom, const G4ErrorTrajErr & errmat = G4ErrorTrajErr(5,0))
Definition at line 48 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 48 of file G4ErrorFreeTrajState.cc
References fTrajParam, and Init().
G4ErrorFreeTrajState::G4ErrorFreeTrajState (const G4ErrorSurfaceTrajState & tpOS)
Definition at line 56 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ErrorFreeTrajState.cc
References source.hepunit::c_light, cm, HepGeom::BasicVector3D< T >::cross(), dir, E, G4ErrorTrajState::fCharge, G4ErrorTrajState::fError, G4ErrorTrajState::fMomentum, G4ErrorTrajState::fPosition, fTrajParam, G4cout, G4endl, G4FieldManager::GetDetectorField(), G4ErrorFreeTrajParam::GetDirection(), G4ErrorTrajState::GetError(), G4TransportationManager::GetFieldManager(), G4Field::GetFieldValue(), G4ErrorFreeTrajParam::GetLambda(), G4ErrorSurfaceTrajState::GetParameters(), GetParameters(), G4ErrorFreeTrajParam::GetPhi(), G4ErrorSurfaceTrajParam::GetPV(), G4ErrorSurfaceTrajParam::GetPW(), G4TransportationManager::GetTransportationManager(), G4ErrorSurfaceTrajParam::GetVectorV(), G4ErrorSurfaceTrajState::GetVectorV(), G4ErrorSurfaceTrajParam::GetVectorW(), G4ErrorSurfaceTrajState::GetVectorW(), h1, Init(), G4ErrorTrajState::iverbose, CLHEP::Hep3Vector::mag(), HepGeom::BasicVector3D< T >::mag(), HepGeom::BasicVector3D< T >::mag2(), mom, Q, G4ErrorSymMatrix::similarity(), tesla, CLHEP::Hep3Vector::theta(), CLHEP::Hep3Vector::x(), HepGeom::BasicVector3D< T >::x(), CLHEP::Hep3Vector::y(), HepGeom::BasicVector3D< T >::y(), CLHEP::Hep3Vector::z(), and HepGeom::BasicVector3D< T >::z().
G4ErrorFreeTrajState::~G4ErrorFreeTrajState () inline
Definition at line 78 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 78 of file G4ErrorFreeTrajState.hh
Member Function Documentation
void G4ErrorFreeTrajState::CalculateEffectiveZandA (const G4Material * mate, double & effZ, double & effA) private
Definition at line 653 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 653 of file G4ErrorFreeTrajState.cc
References Acts::UnitConstants::g, G4Element::GetA(), G4Material::GetElement(), G4Material::GetFractionVector(), G4Material::GetNumberOfElements(), G4Element::GetZ(), and mole.
Referenced by PropagateErrorIoni(), and PropagateErrorMSC().
void G4ErrorFreeTrajState::Dump (std::ostream & out = G4cout) const virtual
Implements G4ErrorTrajState.
Definition at line 169 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 169 of file G4ErrorFreeTrajState.cc
G4ErrorFreeTrajParam G4ErrorFreeTrajState::GetParameters () const inline
Definition at line 107 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ErrorFreeTrajState.hh
References fTrajParam.
Referenced by G4ErrorSurfaceTrajState::BuildErrorMatrix(), and G4ErrorFreeTrajState().
G4ErrorMatrix G4ErrorFreeTrajState::GetTransfMat () const inline
Definition at line 110 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 110 of file G4ErrorFreeTrajState.hh
References theTransfMat.
void G4ErrorFreeTrajState::Init () private
Definition at line 160 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 160 of file G4ErrorFreeTrajState.cc
References G4ErrorTrajState::BuildCharge(), G4eTS_FREE, theFirstStep, theTransfMat, and G4ErrorTrajState::theTSType.
Referenced by G4ErrorFreeTrajState().
G4int G4ErrorFreeTrajState::PropagateError (const G4Track * aTrack) virtual
Reimplemented from G4ErrorTrajState.
Definition at line 202 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 202 of file G4ErrorFreeTrajState.cc
References charge, cm, CLHEP::Hep3Vector::cross(), G4ErrorTrajState::fError, G4cout, G4endl, G4ErrorMode_PropBackwards, G4ErrorStage_Deflation, G4InuclParticleNames::gam, G4DynamicParticle::GetCharge(), G4FieldManager::GetDetectorField(), G4Track::GetDynamicParticle(), G4ErrorPropagatorData::GetErrorPropagatorData(), G4TransportationManager::GetFieldManager(), G4Field::GetFieldValue(), G4GeometryTolerance::GetInstance(), G4StepPoint::GetMomentum(), G4Track::GetMomentum(), G4StepPoint::GetPosition(), G4Track::GetPosition(), G4Step::GetPreStepPoint(), G4Track::GetStep(), G4Step::GetStepLength(), G4GeometryTolerance::GetSurfaceTolerance(), G4TransportationManager::GetTransportationManager(), GeV, h1, h2, G4ErrorTrajState::iverbose, kCarTolerance, CLHEP::Hep3Vector::mag(), HepGeom::BasicVector3D< T >::mag(), MeV, CLHEP::Hep3Vector::perp(), HepGeom::BasicVector3D< T >::perp(), PropagateErrorIoni(), PropagateErrorMSC(), HepGeom::BasicVector3D< T >::setX(), G4ErrorSymMatrix::similarity(), G4ErrorSymMatrix::T(), G4ErrorMatrix::T(), tesla, HepGeom::BasicVector3D< T >::theta(), theTransfMat, CLHEP::Hep3Vector::x(), HepGeom::BasicVector3D< T >::x(), CLHEP::Hep3Vector::y(), HepGeom::BasicVector3D< T >::y(), CLHEP::Hep3Vector::z(), and HepGeom::BasicVector3D< T >::z().
Referenced by G4ErrorPropagator::MakeOneStep().
G4int G4ErrorFreeTrajState::PropagateErrorIoni (const G4Track * aTrack) private
Definition at line 668 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 668 of file G4ErrorFreeTrajState.cc
References CalculateEffectiveZandA(), cm, E, Emax, Acts::VectorHelpers::eta(), F1, F2, G4ErrorTrajState::fError, G4cout, G4endl, G4Material::GetDensity(), G4Track::GetDynamicParticle(), G4VPhysicalVolume::GetLogicalVolume(), G4DynamicParticle::GetMass(), G4LogicalVolume::GetMaterial(), G4StepPoint::GetMomentum(), G4Track::GetMomentum(), G4Step::GetPreStepPoint(), G4Track::GetStep(), G4Step::GetStepLength(), G4Track::GetTotalEnergy(), G4Track::GetVolume(), GeV, G4ErrorTrajState::iverbose, CLHEP::Hep3Vector::mag(), mass, mg, and mole.
Referenced by PropagateError().
G4int G4ErrorFreeTrajState::PropagateErrorMSC (const G4Track * aTrack) private
Definition at line 602 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 602 of file G4ErrorFreeTrajState.cc
References CalculateEffectiveZandA(), charge, cm, G4ErrorTrajState::fError, Acts::UnitConstants::g, G4cout, G4endl, G4DynamicParticle::GetCharge(), G4Material::GetDensity(), G4Track::GetDynamicParticle(), G4VPhysicalVolume::GetLogicalVolume(), G4LogicalVolume::GetMaterial(), G4Track::GetMomentum(), G4Material::GetName(), G4Material::GetNuclearInterLength(), G4Material::GetRadlen(), G4Track::GetStep(), G4Step::GetStepLength(), G4Track::GetTotalEnergy(), G4Track::GetVolume(), GeV, G4ErrorTrajState::iverbose, CLHEP::Hep3Vector::mag(), mole, CLHEP::Hep3Vector::x(), and CLHEP::Hep3Vector::y().
Referenced by PropagateError().
virtual void G4ErrorFreeTrajState::SetMomentum (const G4Vector3D & mom) inline virtual
Reimplemented from G4ErrorTrajState.
Definition at line 97 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ErrorFreeTrajState.hh
References G4ErrorTrajState::fPosition, and SetParameters().
void G4ErrorFreeTrajState::SetParameters (const G4Point3D & pos, const G4Vector3D & mom) inline
Definition at line 100 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 100 of file G4ErrorFreeTrajState.hh
References G4ErrorTrajState::fMomentum, G4ErrorTrajState::fPosition, fTrajParam, mom, pos(), and G4ErrorFreeTrajParam::SetParameters().
Referenced by SetMomentum(), and SetPosition().
virtual void G4ErrorFreeTrajState::SetPosition (const G4Point3D pos) inline virtual
Reimplemented from G4ErrorTrajState.
Definition at line 94 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ErrorFreeTrajState.hh
References G4ErrorTrajState::fMomentum, and SetParameters().
G4int G4ErrorFreeTrajState::Update (const G4Track * aTrack) virtual
Reimplemented from G4ErrorTrajState.
Definition at line 175 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 175 of file G4ErrorFreeTrajState.cc
References fTrajParam, G4Track::GetMomentum(), G4Track::GetPosition(), G4ErrorFreeTrajParam::Update(), and G4ErrorTrajState::UpdatePosMom().
Referenced by G4ErrorPropagator::MakeOneStep().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const G4ErrorFreeTrajState & ts) friend
Definition at line 185 of file G4ErrorFreeTrajState.cc.
View newest version in sPHENIX GitHub at line 185 of file G4ErrorFreeTrajState.cc
Member Data Documentation
G4ErrorFreeTrajParam G4ErrorFreeTrajState::fTrajParam private
Definition at line 130 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 130 of file G4ErrorFreeTrajState.hh
Referenced by G4ErrorFreeTrajState(), GetParameters(), operator<<(), SetParameters(), and Update().
G4bool G4ErrorFreeTrajState::theFirstStep private
Definition at line 134 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 134 of file G4ErrorFreeTrajState.hh
Referenced by Init().
G4ErrorMatrix G4ErrorFreeTrajState::theTransfMat private
Definition at line 132 of file G4ErrorFreeTrajState.hh.
View newest version in sPHENIX GitHub at line 132 of file G4ErrorFreeTrajState.hh
Referenced by GetTransfMat(), Init(), and PropagateError().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorFreeTrajState.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorFreeTrajState.cc