ECCE @ EIC Software: G4CrossSectionPairGG Class Reference
G4CrossSectionPairGG Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionPairGG.hh>
Public Member Functions
G4CrossSectionPairGG (G4VCrossSectionDataSet *low, G4double Etransit)
virtual ~G4CrossSectionPairGG ()
virtual void CrossSectionDescription (std::ostream &) const
virtual G4bool IsElementApplicable (const G4DynamicParticle *, G4int Z, const G4Material *mat=0)
virtual G4double GetElementCrossSection (const G4DynamicParticle *, G4int Z, const G4Material *mat=0)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void DumpPhysicsTable (const G4ParticleDefinition &)
Public Member Functions inherited from G4VCrossSectionDataSet
G4VCrossSectionDataSet (const G4String &nam="")
virtual ~G4VCrossSectionDataSet ()
virtual G4bool IsIsoApplicable (const G4DynamicParticle *, G4int Z, G4int A, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
G4double GetCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
G4double ComputeCrossSection (const G4DynamicParticle *, const G4Element *, const G4Material *mat=nullptr)
virtual G4double GetIsoCrossSection (const G4DynamicParticle *, G4int Z, G4int A, const G4Isotope *iso=nullptr, const G4Element *elm=nullptr, const G4Material *mat=nullptr)
virtual const G4Isotope * SelectIsotope (const G4Element *, G4double kinEnergy, G4double logE)
virtual G4int GetVerboseLevel () const
virtual void SetVerboseLevel (G4int value)
G4double GetMinKinEnergy () const
void SetMinKinEnergy (G4double value)
G4double GetMaxKinEnergy () const
void SetMaxKinEnergy (G4double value)
bool ForAllAtomsAndEnergies () const
void SetForAllAtomsAndEnergies (G4bool val)
const G4String & GetName () const
Private Types
typedef std::valarray< G4double > XS_factors
typedef std::pair< const
G4ParticleDefinition
*, XS_factors > ParticleXScale
Private Member Functions
G4CrossSectionPairGG ()
G4CrossSectionPairGG (const G4CrossSectionPairGG &)
G4CrossSectionPairGG & operator= (const G4CrossSectionPairGG &)
Private Attributes
G4NistManager * NistMan
G4VCrossSectionDataSet * theLowX
G4ComponentGGHadronNucleusXsc * theHighX
G4double ETransition
std::vector< ParticleXScale > scale_factors
Additional Inherited Members
Protected Member Functions inherited from G4VCrossSectionDataSet
void SetName (const G4String &)
Protected Attributes inherited from G4VCrossSectionDataSet
G4int verboseLevel
Detailed Description
Definition at line 49 of file G4CrossSectionPairGG.hh.
View newest version in sPHENIX GitHub at line 49 of file G4CrossSectionPairGG.hh
Member Typedef Documentation
typedef std::pair<const G4ParticleDefinition *, XS_factors > G4CrossSectionPairGG::ParticleXScale private
Definition at line 83 of file G4CrossSectionPairGG.hh.
View newest version in sPHENIX GitHub at line 83 of file G4CrossSectionPairGG.hh
typedef std::valarray<G4double> G4CrossSectionPairGG::XS_factors private
Definition at line 82 of file G4CrossSectionPairGG.hh.
View newest version in sPHENIX GitHub at line 82 of file G4CrossSectionPairGG.hh
Constructor & Destructor Documentation
G4CrossSectionPairGG::G4CrossSectionPairGG (G4VCrossSectionDataSet * low, G4double Etransit)
Definition at line 47 of file G4CrossSectionPairGG.cc.
View newest version in sPHENIX GitHub at line 47 of file G4CrossSectionPairGG.cc
References G4NistManager::Instance(), NistMan, theHighX, and G4VCrossSectionDataSet::verboseLevel.
G4CrossSectionPairGG::~G4CrossSectionPairGG () virtual
Definition at line 56 of file G4CrossSectionPairGG.cc.
View newest version in sPHENIX GitHub at line 56 of file G4CrossSectionPairGG.cc
G4CrossSectionPairGG::G4CrossSectionPairGG () private
G4CrossSectionPairGG::G4CrossSectionPairGG (const G4CrossSectionPairGG &) private
Member Function Documentation
void G4CrossSectionPairGG::BuildPhysicsTable (const G4ParticleDefinition & pDef) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 123 of file G4CrossSectionPairGG.cc.
View newest version in sPHENIX GitHub at line 123 of file G4CrossSectionPairGG.cc
References G4VComponentCrossSection::BuildPhysicsTable(), G4VCrossSectionDataSet::BuildPhysicsTable(), ETransition, G4cout, G4endl, G4lrint(), G4NistManager::GetAtomicMassAmu(), G4VCrossSectionDataSet::GetElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), G4VComponentCrossSection::GetName(), G4VCrossSectionDataSet::GetName(), G4ParticleDefinition::GetParticleName(), G4VCrossSectionDataSet::IsElementApplicable(), mat, mom, NistMan, scale_factors, theHighX, theLowX, and G4VCrossSectionDataSet::verboseLevel.
Referenced by GetElementCrossSection().
void G4CrossSectionPairGG::CrossSectionDescription (std::ostream & outFile) const virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 59 of file G4CrossSectionPairGG.cc.
View newest version in sPHENIX GitHub at line 59 of file G4CrossSectionPairGG.cc
void G4CrossSectionPairGG::DumpPhysicsTable (const G4ParticleDefinition &) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 197 of file G4CrossSectionPairGG.cc.
View newest version in sPHENIX GitHub at line 197 of file G4CrossSectionPairGG.cc
References ETransition, G4cout, G4endl, G4VCrossSectionDataSet::GetName(), GeV, and theLowX.
G4double G4CrossSectionPairGG::GetElementCrossSection (const G4DynamicParticle * aParticle, G4int Z, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 84 of file G4CrossSectionPairGG.cc.
View newest version in sPHENIX GitHub at line 84 of file G4CrossSectionPairGG.cc
References BuildPhysicsTable(), ETransition, G4cout, G4endl, G4lrint(), G4NistManager::GetAtomicMassAmu(), G4DynamicParticle::GetDefinition(), G4VCrossSectionDataSet::GetElementCrossSection(), G4ComponentGGHadronNucleusXsc::GetInelasticGlauberGribov(), G4DynamicParticle::GetKineticEnergy(), NistMan, scale_factors, theHighX, theLowX, and G4VCrossSectionDataSet::verboseLevel.
G4bool G4CrossSectionPairGG::IsElementApplicable (const G4DynamicParticle * aParticle, G4int Z, const G4Material * mat = 0) virtual
Reimplemented from G4VCrossSectionDataSet.
Definition at line 72 of file G4CrossSectionPairGG.cc.
View newest version in sPHENIX GitHub at line 72 of file G4CrossSectionPairGG.cc
References ETransition, G4DynamicParticle::GetKineticEnergy(), G4VCrossSectionDataSet::IsElementApplicable(), and theLowX.
G4CrossSectionPairGG& G4CrossSectionPairGG::operator= (const G4CrossSectionPairGG &) private
Member Data Documentation
G4double G4CrossSectionPairGG::ETransition private
Definition at line 81 of file G4CrossSectionPairGG.hh.
View newest version in sPHENIX GitHub at line 81 of file G4CrossSectionPairGG.hh
Referenced by BuildPhysicsTable(), DumpPhysicsTable(), GetElementCrossSection(), and IsElementApplicable().
G4NistManager* G4CrossSectionPairGG::NistMan private
Definition at line 78 of file G4CrossSectionPairGG.hh.
View newest version in sPHENIX GitHub at line 78 of file G4CrossSectionPairGG.hh
Referenced by BuildPhysicsTable(), G4CrossSectionPairGG(), and GetElementCrossSection().
std::vector<ParticleXScale> G4CrossSectionPairGG::scale_factors private
Definition at line 84 of file G4CrossSectionPairGG.hh.
View newest version in sPHENIX GitHub at line 84 of file G4CrossSectionPairGG.hh
Referenced by BuildPhysicsTable(), and GetElementCrossSection().
G4ComponentGGHadronNucleusXsc* G4CrossSectionPairGG::theHighX private
Definition at line 80 of file G4CrossSectionPairGG.hh.
View newest version in sPHENIX GitHub at line 80 of file G4CrossSectionPairGG.hh
Referenced by BuildPhysicsTable(), G4CrossSectionPairGG(), and GetElementCrossSection().
G4VCrossSectionDataSet* G4CrossSectionPairGG::theLowX private
Definition at line 79 of file G4CrossSectionPairGG.hh.
View newest version in sPHENIX GitHub at line 79 of file G4CrossSectionPairGG.hh
Referenced by BuildPhysicsTable(), DumpPhysicsTable(), GetElementCrossSection(), and IsElementApplicable().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/include/G4CrossSectionPairGG.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/cross_sections/src/G4CrossSectionPairGG.cc