ECCE @ EIC Software: RE05CalorimeterParametrisation Class Reference
RE05CalorimeterParametrisation Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05CalorimeterParametrisation.hh>
Public Member Functions
RE05CalorimeterParametrisation ()
~RE05CalorimeterParametrisation ()
virtual void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
virtual void ComputeDimensions (G4Tubs &calorimeterLayer, const G4int copyNo, const G4VPhysicalVolume *physVol) const
Public Member Functions inherited from G4VPVParameterisation
G4VPVParameterisation ()
virtual ~G4VPVParameterisation ()
virtual G4VSolid * ComputeSolid (const G4int, G4VPhysicalVolume *)
virtual G4Material * ComputeMaterial (const G4int repNo, G4VPhysicalVolume *currentVol, const G4VTouchable *parentTouch=nullptr)
virtual G4bool IsNested () const
virtual G4VVolumeMaterialScanner * GetMaterialScanner ()
Private Member Functions
virtual void ComputeDimensions (G4Trd &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Trap &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Cons &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Orb &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Sphere &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Ellipsoid &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Torus &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Para &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Hype &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Box &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polycone &, const G4int, const G4VPhysicalVolume *) const
virtual void ComputeDimensions (G4Polyhedra &, const G4int, const G4VPhysicalVolume *) const
Private Attributes
G4double fExpHall_x
G4double fExpHall_y
G4double fExpHall_z
G4double fTrkTubs_rmax
G4double fTrkTubs_rmin
G4double fTrkTubs_dz
G4double fTrkTubs_sphi
G4double fTrkTubs_dphi
G4int fNotrkLayers
G4double fTracker_radius [5]
G4double fTracker_thick
G4double fTracker_length [5]
G4double fCaloTubs_rmax
G4double fCaloTubs_rmin
G4double fCaloTubs_dz
G4double fCaloTubs_sphi
G4double fCaloTubs_dphi
G4int fNocaloLayers
G4double fAbsorber_thick
G4double fScinti_thick
G4int fSegmentsinZ
G4double fCaloRing_rmax
G4double fCaloRing_rmin
G4double fCaloRing_dz
G4double fCaloRing_sphi
G4double fCaloRing_dphi
G4int fSegmentsinPhi
G4double fCaloCell_rmax
G4double fCaloCell_rmin
G4double fCaloCell_dz
G4double fCaloCell_sphi
G4double fCaloCell_dphi
G4int fNomucounter
G4double fMuBox_radius
G4double fMuBox_width
G4double fMuBox_thick
G4double fMuBox_length
Detailed Description
Definition at line 54 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 54 of file RE05CalorimeterParametrisation.hh
Constructor & Destructor Documentation
RE05CalorimeterParametrisation::RE05CalorimeterParametrisation ()
Definition at line 40 of file RE05CalorimeterParametrisation.cc.
View newest version in sPHENIX GitHub at line 40 of file RE05CalorimeterParametrisation.cc
RE05CalorimeterParametrisation::~RE05CalorimeterParametrisation ()
Definition at line 48 of file RE05CalorimeterParametrisation.cc.
View newest version in sPHENIX GitHub at line 48 of file RE05CalorimeterParametrisation.cc
Member Function Documentation
void RE05CalorimeterParametrisation::ComputeDimensions (G4Tubs & calorimeterLayer, const G4int copyNo, const G4VPhysicalVolume * physVol) const virtual
Reimplemented from G4VPVParameterisation.
Definition at line 63 of file RE05CalorimeterParametrisation.cc.
View newest version in sPHENIX GitHub at line 63 of file RE05CalorimeterParametrisation.cc
References fAbsorber_thick, fCaloTubs_dphi, fCaloTubs_dz, fCaloTubs_rmin, fCaloTubs_sphi, fScinti_thick, G4Tubs::SetDeltaPhiAngle(), G4Tubs::SetInnerRadius(), G4Tubs::SetOuterRadius(), G4Tubs::SetStartPhiAngle(), and G4Tubs::SetZHalfLength().
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Trd & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 69 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 69 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Trap & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 71 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 71 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Cons & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 73 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 73 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Orb & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 75 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 75 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Sphere & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 77 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 77 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Ellipsoid & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 79 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 79 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Torus & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 81 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 81 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Para & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 83 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 83 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Hype & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 85 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 85 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Box & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 87 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 87 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Polycone & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 89 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 89 of file RE05CalorimeterParametrisation.hh
virtual void RE05CalorimeterParametrisation::ComputeDimensions (G4Polyhedra & , const G4int , const G4VPhysicalVolume *) const inline private virtual
Reimplemented from G4VPVParameterisation.
Definition at line 91 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 91 of file RE05CalorimeterParametrisation.hh
void RE05CalorimeterParametrisation::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const virtual
Implements G4VPVParameterisation.
Definition at line 54 of file RE05CalorimeterParametrisation.cc.
View newest version in sPHENIX GitHub at line 54 of file RE05CalorimeterParametrisation.cc
References Acts::Test::origin(), and G4VPhysicalVolume::SetTranslation().
Member Data Documentation
G4double RE05CalorimeterParametrisation::fAbsorber_thick private
Definition at line 54 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 54 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloCell_dphi private
Definition at line 69 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 69 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloCell_dz private
Definition at line 67 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 67 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloCell_rmax private
Definition at line 65 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 65 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloCell_rmin private
Definition at line 66 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 66 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloCell_sphi private
Definition at line 68 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 68 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloRing_dphi private
Definition at line 62 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 62 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloRing_dz private
Definition at line 60 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 60 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloRing_rmax private
Definition at line 58 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 58 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloRing_rmin private
Definition at line 59 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 59 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloRing_sphi private
Definition at line 61 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 61 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloTubs_dphi private
Definition at line 51 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 51 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloTubs_dz private
Definition at line 49 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 49 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloTubs_rmax private
Definition at line 47 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 47 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloTubs_rmin private
Definition at line 48 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 48 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fCaloTubs_sphi private
Definition at line 50 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 50 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fExpHall_x private
Definition at line 32 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 32 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fExpHall_y private
Definition at line 33 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 33 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fExpHall_z private
Definition at line 34 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 34 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fMuBox_length private
Definition at line 75 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 75 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fMuBox_radius private
Definition at line 72 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 72 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fMuBox_thick private
Definition at line 74 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 74 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fMuBox_width private
Definition at line 73 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 73 of file RE05CalorimeterParametrisation.hh
G4int RE05CalorimeterParametrisation::fNocaloLayers private
Definition at line 53 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 53 of file RE05CalorimeterParametrisation.hh
G4int RE05CalorimeterParametrisation::fNomucounter private
Definition at line 71 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 71 of file RE05CalorimeterParametrisation.hh
G4int RE05CalorimeterParametrisation::fNotrkLayers private
Definition at line 42 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 42 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fScinti_thick private
Definition at line 55 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 55 of file RE05CalorimeterParametrisation.hh
G4int RE05CalorimeterParametrisation::fSegmentsinPhi private
Definition at line 64 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 64 of file RE05CalorimeterParametrisation.hh
G4int RE05CalorimeterParametrisation::fSegmentsinZ private
Definition at line 57 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 57 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fTracker_length[5] private
Definition at line 45 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 45 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fTracker_radius[5] private
Definition at line 43 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 43 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fTracker_thick private
Definition at line 44 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 44 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fTrkTubs_dphi private
Definition at line 40 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 40 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fTrkTubs_dz private
Definition at line 38 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 38 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fTrkTubs_rmax private
Definition at line 36 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 36 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fTrkTubs_rmin private
Definition at line 37 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 37 of file RE05CalorimeterParametrisation.hh
G4double RE05CalorimeterParametrisation::fTrkTubs_sphi private
Definition at line 39 of file RE05CalorimeterParametrisation.hh.
View newest version in sPHENIX GitHub at line 39 of file RE05CalorimeterParametrisation.hh
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05CalorimeterParametrisation.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05DetectorParameterDef.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/src/RE05CalorimeterParametrisation.cc