ECCE @ EIC Software: DicomBeamControlPoint Class Reference
DicomBeamControlPoint Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomBeamControlPoint.hh>
Public Member Functions
DicomBeamControlPoint (DRTControlPointSequence::Item cpItem, DicomBeamControlPoint *point0)
~DicomBeamControlPoint ()
void SetIndex (Sint32 dat)
Sint32 GetIndex () const
void SetNominalBeamEnergy (Float64 dat)
Float64 GetNominalBeamEnergy () const
void SetGantryAngle (Float64 dat)
void SetGantryRotationDirection (OFString dat)
void SetBeamLimitingDeviceAngle (Float64 dat)
void SetBeamLimitingDeviceRotationDirection (OFString dat)
void SetPatientSupportAngle (Float64 dat)
void SetPatientSupportRotationDirection (OFString dat)
void SetTableTopEccentricAngle (Float64 dat)
void SetTableTopEccentricRotationDirection (OFString dat)
void SetIsocenterPosition (G4ThreeVector dat)
void SetSourceToSurfaceDistance (Float64 dat)
void SetCumulativeMetersetWeight (Float64 dat)
void SetMetersetWeight (Float64 dat)
void SetGantryPitchAngle (Float32 dat)
void SetSurfaceEntryPoint (Float64 dat)
void SetTableTopEccentricAxisDistance (Float64 dat)
void SetTableTopLateralPosition (Float64 dat)
void SetTableTopLongitudinalPosition (Float64 dat)
void SetTableTopPitchAngle (Float32 dat)
void SetTableTopPitchRotationDirection (OFString dat)
void SetTableTopRollAngle (Float32 dat)
void SetTableTopRollRotationDirection (OFString dat)
void SetTableTopVerticalPosition (Float64 dat)
OFString GetGantryRotationDirection () const
Float64 GetBeamLimitingDeviceAngle () const
OFString GetBeamLimitingDeviceRotationDirection () const
Float64 GetPatientSupportAngle () const
OFString GetPatientSupportRotationDirection () const
Float64 GetTableTopEccentricAngle () const
OFString GetTableTopEccentricRotationDirection () const
G4ThreeVector GetIsocenterPosition () const
Float64 GetSourceToSurfaceDistance () const
Float64 GetCumulativeMetersetWeight () const
Float64 GetMetersetWeight () const
Float32 GetGantryPitchAngle () const
Float64 GetSurfaceEntryPoint () const
Float64 GetTableTopEccentricAxisDistance () const
Float64 GetTableTopLateralPosition () const
Float64 GetTableTopLongitudinalPosition () const
Float32 GetTableTopPitchAngle () const
OFString GetTableTopPitchRotationDirection () const
Float32 GetTableTopRollAngle () const
OFString GetTableTopRollRotationDirection () const
Float64 GetTableTopVerticalPosition () const
void AddDevice (DicomBeamDevicePos *dbd)
void DumpToFile (std::ofstream &out)
void Print (std::ostream &out)
Private Attributes
Sint32 theIndex
Float64 theNominalBeamEnergy
Float64 theGantryAngle
OFString theGantryRotationDirection
Float64 theBeamLimitingDeviceAngle
OFString theBeamLimitingDeviceRotationDirection
Float64 thePatientSupportAngle
OFString thePatientSupportRotationDirection
Float64 theTableTopEccentricAngle
OFString theTableTopEccentricRotationDirection
G4ThreeVector theIsocenterPosition
Float64 theSourceToSurfaceDistance
Float64 theCumulativeMetersetWeight
Float64 theMetersetWeight
Float32 theGantryPitchAngle
Float64 theSurfaceEntryPoint
Float64 theTableTopEccentricAxisDistance
Float64 theTableTopLateralPosition
Float64 theTableTopLongitudinalPosition
Float32 theTableTopPitchAngle
OFString theTableTopPitchRotationDirection
Float32 theTableTopRollAngle
OFString theTableTopRollRotationDirection
Float64 theTableTopVerticalPosition
std::vector< DicomBeamDevicePos * > theDevices
Detailed Description
Definition at line 36 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 36 of file DicomBeamControlPoint.hh
Constructor & Destructor Documentation
DicomBeamControlPoint::DicomBeamControlPoint (DRTControlPointSequence::Item cpItem, DicomBeamControlPoint * point0)
Definition at line 33 of file DicomBeamControlPoint.cc.
View newest version in sPHENIX GitHub at line 33 of file DicomBeamControlPoint.cc
References AddDevice(), G4cout, G4endl, GetBeamLimitingDeviceAngle(), GetBeamLimitingDeviceRotationDirection(), GetGantryPitchAngle(), GetIsocenterPosition(), GetNominalBeamEnergy(), GetPatientSupportAngle(), GetPatientSupportRotationDirection(), GetSourceToSurfaceDistance(), GetSurfaceEntryPoint(), GetTableTopEccentricAngle(), GetTableTopEccentricAxisDistance(), GetTableTopEccentricRotationDirection(), GetTableTopLateralPosition(), GetTableTopLongitudinalPosition(), GetTableTopPitchAngle(), GetTableTopPitchRotationDirection(), GetTableTopRollAngle(), GetTableTopRollRotationDirection(), GetTableTopVerticalPosition(), SetBeamLimitingDeviceAngle(), SetBeamLimitingDeviceRotationDirection(), SetCumulativeMetersetWeight(), SetGantryAngle(), SetGantryPitchAngle(), SetIndex(), SetIsocenterPosition(), SetNominalBeamEnergy(), SetPatientSupportAngle(), SetPatientSupportRotationDirection(), SetSourceToSurfaceDistance(), SetSurfaceEntryPoint(), SetTableTopEccentricAngle(), SetTableTopEccentricAxisDistance(), SetTableTopEccentricRotationDirection(), SetTableTopLateralPosition(), SetTableTopLongitudinalPosition(), SetTableTopPitchAngle(), SetTableTopPitchRotationDirection(), SetTableTopRollAngle(), SetTableTopRollRotationDirection(), and SetTableTopVerticalPosition().
DicomBeamControlPoint::~DicomBeamControlPoint () inline
Definition at line 40 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 40 of file DicomBeamControlPoint.hh
Member Function Documentation
void DicomBeamControlPoint::AddDevice (DicomBeamDevicePos * dbd) inline
Definition at line 185 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 185 of file DicomBeamControlPoint.hh
References theDevices.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::DumpToFile (std::ofstream & out)
Definition at line 223 of file DicomBeamControlPoint.cc.
View newest version in sPHENIX GitHub at line 223 of file DicomBeamControlPoint.cc
References G4endl, theBeamLimitingDeviceAngle, theDevices, theGantryAngle, theGantryPitchAngle, theIndex, theIsocenterPosition, theMetersetWeight, theNominalBeamEnergy, thePatientSupportAngle, theSourceToSurfaceDistance, theSurfaceEntryPoint, theTableTopEccentricAngle, theTableTopEccentricAxisDistance, theTableTopLateralPosition, theTableTopLongitudinalPosition, theTableTopPitchAngle, theTableTopRollAngle, theTableTopVerticalPosition, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Float64 DicomBeamControlPoint::GetBeamLimitingDeviceAngle () const inline
Definition at line 124 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 124 of file DicomBeamControlPoint.hh
References theBeamLimitingDeviceAngle.
Referenced by DicomBeamControlPoint().
OFString DicomBeamControlPoint::GetBeamLimitingDeviceRotationDirection () const inline
Definition at line 127 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 127 of file DicomBeamControlPoint.hh
References theBeamLimitingDeviceRotationDirection.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetCumulativeMetersetWeight () const inline
Definition at line 148 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 148 of file DicomBeamControlPoint.hh
References theCumulativeMetersetWeight.
Float32 DicomBeamControlPoint::GetGantryPitchAngle () const inline
Definition at line 154 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 154 of file DicomBeamControlPoint.hh
References theGantryPitchAngle.
Referenced by DicomBeamControlPoint().
OFString DicomBeamControlPoint::GetGantryRotationDirection () const inline
Definition at line 121 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 121 of file DicomBeamControlPoint.hh
References theGantryRotationDirection.
Sint32 DicomBeamControlPoint::GetIndex () const inline
Definition at line 46 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 46 of file DicomBeamControlPoint.hh
References theIndex.
G4ThreeVector DicomBeamControlPoint::GetIsocenterPosition () const inline
Definition at line 142 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 142 of file DicomBeamControlPoint.hh
References theIsocenterPosition.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetMetersetWeight () const inline
Definition at line 151 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 151 of file DicomBeamControlPoint.hh
References theMetersetWeight.
Float64 DicomBeamControlPoint::GetNominalBeamEnergy () const inline
Definition at line 52 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 52 of file DicomBeamControlPoint.hh
References theNominalBeamEnergy.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetPatientSupportAngle () const inline
Definition at line 130 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 130 of file DicomBeamControlPoint.hh
References thePatientSupportAngle.
Referenced by DicomBeamControlPoint().
OFString DicomBeamControlPoint::GetPatientSupportRotationDirection () const inline
Definition at line 133 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 133 of file DicomBeamControlPoint.hh
References thePatientSupportRotationDirection.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetSourceToSurfaceDistance () const inline
Definition at line 145 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 145 of file DicomBeamControlPoint.hh
References theSourceToSurfaceDistance.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetSurfaceEntryPoint () const inline
Definition at line 157 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 157 of file DicomBeamControlPoint.hh
References theSurfaceEntryPoint.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetTableTopEccentricAngle () const inline
Definition at line 136 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 136 of file DicomBeamControlPoint.hh
References theTableTopEccentricAngle.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetTableTopEccentricAxisDistance () const inline
Definition at line 160 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 160 of file DicomBeamControlPoint.hh
References theTableTopEccentricAxisDistance.
Referenced by DicomBeamControlPoint().
OFString DicomBeamControlPoint::GetTableTopEccentricRotationDirection () const inline
Definition at line 139 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 139 of file DicomBeamControlPoint.hh
References theTableTopEccentricRotationDirection.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetTableTopLateralPosition () const inline
Definition at line 163 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 163 of file DicomBeamControlPoint.hh
References theTableTopLateralPosition.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetTableTopLongitudinalPosition () const inline
Definition at line 166 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 166 of file DicomBeamControlPoint.hh
References theTableTopLongitudinalPosition.
Referenced by DicomBeamControlPoint().
Float32 DicomBeamControlPoint::GetTableTopPitchAngle () const inline
Definition at line 169 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 169 of file DicomBeamControlPoint.hh
References theTableTopPitchAngle.
Referenced by DicomBeamControlPoint().
OFString DicomBeamControlPoint::GetTableTopPitchRotationDirection () const inline
Definition at line 172 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 172 of file DicomBeamControlPoint.hh
References theTableTopPitchRotationDirection.
Referenced by DicomBeamControlPoint().
Float32 DicomBeamControlPoint::GetTableTopRollAngle () const inline
Definition at line 175 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 175 of file DicomBeamControlPoint.hh
References theTableTopRollAngle.
Referenced by DicomBeamControlPoint().
OFString DicomBeamControlPoint::GetTableTopRollRotationDirection () const inline
Definition at line 178 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 178 of file DicomBeamControlPoint.hh
References theTableTopRollRotationDirection.
Referenced by DicomBeamControlPoint().
Float64 DicomBeamControlPoint::GetTableTopVerticalPosition () const inline
Definition at line 181 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 181 of file DicomBeamControlPoint.hh
References theTableTopVerticalPosition.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::Print (std::ostream & out)
Definition at line 217 of file DicomBeamControlPoint.cc.
View newest version in sPHENIX GitHub at line 217 of file DicomBeamControlPoint.cc
void DicomBeamControlPoint::SetBeamLimitingDeviceAngle (Float64 dat) inline
Definition at line 61 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 61 of file DicomBeamControlPoint.hh
References theBeamLimitingDeviceAngle.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetBeamLimitingDeviceRotationDirection (OFString dat) inline
Definition at line 64 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 64 of file DicomBeamControlPoint.hh
References theBeamLimitingDeviceRotationDirection.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetCumulativeMetersetWeight (Float64 dat) inline
Definition at line 85 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 85 of file DicomBeamControlPoint.hh
References theCumulativeMetersetWeight.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetGantryAngle (Float64 dat) inline
Definition at line 55 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 55 of file DicomBeamControlPoint.hh
References theGantryAngle.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetGantryPitchAngle (Float32 dat) inline
Definition at line 91 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 91 of file DicomBeamControlPoint.hh
References theGantryPitchAngle.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetGantryRotationDirection (OFString dat) inline
Definition at line 58 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 58 of file DicomBeamControlPoint.hh
References theGantryRotationDirection.
void DicomBeamControlPoint::SetIndex (Sint32 dat) inline
Definition at line 43 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 43 of file DicomBeamControlPoint.hh
References theIndex.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetIsocenterPosition (G4ThreeVector dat) inline
Definition at line 79 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 79 of file DicomBeamControlPoint.hh
References theIsocenterPosition.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetMetersetWeight (Float64 dat) inline
Definition at line 88 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 88 of file DicomBeamControlPoint.hh
References theMetersetWeight.
void DicomBeamControlPoint::SetNominalBeamEnergy (Float64 dat) inline
Definition at line 49 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 49 of file DicomBeamControlPoint.hh
References theNominalBeamEnergy.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetPatientSupportAngle (Float64 dat) inline
Definition at line 67 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 67 of file DicomBeamControlPoint.hh
References thePatientSupportAngle.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetPatientSupportRotationDirection (OFString dat) inline
Definition at line 70 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 70 of file DicomBeamControlPoint.hh
References thePatientSupportRotationDirection.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetSourceToSurfaceDistance (Float64 dat) inline
Definition at line 82 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 82 of file DicomBeamControlPoint.hh
References theSourceToSurfaceDistance.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetSurfaceEntryPoint (Float64 dat) inline
Definition at line 94 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 94 of file DicomBeamControlPoint.hh
References theSurfaceEntryPoint.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopEccentricAngle (Float64 dat) inline
Definition at line 73 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 73 of file DicomBeamControlPoint.hh
References theTableTopEccentricAngle.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopEccentricAxisDistance (Float64 dat) inline
Definition at line 97 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 97 of file DicomBeamControlPoint.hh
References theTableTopEccentricAxisDistance.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopEccentricRotationDirection (OFString dat) inline
Definition at line 76 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 76 of file DicomBeamControlPoint.hh
References theTableTopEccentricRotationDirection.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopLateralPosition (Float64 dat) inline
Definition at line 100 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 100 of file DicomBeamControlPoint.hh
References theTableTopLateralPosition.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopLongitudinalPosition (Float64 dat) inline
Definition at line 103 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 103 of file DicomBeamControlPoint.hh
References theTableTopLongitudinalPosition.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopPitchAngle (Float32 dat) inline
Definition at line 106 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 106 of file DicomBeamControlPoint.hh
References theTableTopPitchAngle.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopPitchRotationDirection (OFString dat) inline
Definition at line 109 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 109 of file DicomBeamControlPoint.hh
References theTableTopPitchRotationDirection.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopRollAngle (Float32 dat) inline
Definition at line 112 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 112 of file DicomBeamControlPoint.hh
References theTableTopRollAngle.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopRollRotationDirection (OFString dat) inline
Definition at line 115 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 115 of file DicomBeamControlPoint.hh
References theTableTopRollRotationDirection.
Referenced by DicomBeamControlPoint().
void DicomBeamControlPoint::SetTableTopVerticalPosition (Float64 dat) inline
Definition at line 118 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 118 of file DicomBeamControlPoint.hh
References theTableTopVerticalPosition.
Referenced by DicomBeamControlPoint().
Member Data Documentation
Float64 DicomBeamControlPoint::theBeamLimitingDeviceAngle private
Definition at line 198 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 198 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetBeamLimitingDeviceAngle(), and SetBeamLimitingDeviceAngle().
OFString DicomBeamControlPoint::theBeamLimitingDeviceRotationDirection private
Definition at line 199 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 199 of file DicomBeamControlPoint.hh
Referenced by GetBeamLimitingDeviceRotationDirection(), and SetBeamLimitingDeviceRotationDirection().
Float64 DicomBeamControlPoint::theCumulativeMetersetWeight private
Definition at line 206 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 206 of file DicomBeamControlPoint.hh
Referenced by GetCumulativeMetersetWeight(), and SetCumulativeMetersetWeight().
std::vector<DicomBeamDevicePos *> DicomBeamControlPoint::theDevices private
Definition at line 219 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 219 of file DicomBeamControlPoint.hh
Referenced by AddDevice(), and DumpToFile().
Float64 DicomBeamControlPoint::theGantryAngle private
Definition at line 196 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 196 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), and SetGantryAngle().
Float32 DicomBeamControlPoint::theGantryPitchAngle private
Definition at line 208 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 208 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetGantryPitchAngle(), and SetGantryPitchAngle().
OFString DicomBeamControlPoint::theGantryRotationDirection private
Definition at line 197 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 197 of file DicomBeamControlPoint.hh
Referenced by GetGantryRotationDirection(), and SetGantryRotationDirection().
Sint32 DicomBeamControlPoint::theIndex private
Definition at line 194 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 194 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetIndex(), and SetIndex().
G4ThreeVector DicomBeamControlPoint::theIsocenterPosition private
Definition at line 204 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 204 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetIsocenterPosition(), and SetIsocenterPosition().
Float64 DicomBeamControlPoint::theMetersetWeight private
Definition at line 207 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 207 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetMetersetWeight(), and SetMetersetWeight().
Float64 DicomBeamControlPoint::theNominalBeamEnergy private
Definition at line 195 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 195 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetNominalBeamEnergy(), and SetNominalBeamEnergy().
Float64 DicomBeamControlPoint::thePatientSupportAngle private
Definition at line 200 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 200 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetPatientSupportAngle(), and SetPatientSupportAngle().
OFString DicomBeamControlPoint::thePatientSupportRotationDirection private
Definition at line 201 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 201 of file DicomBeamControlPoint.hh
Referenced by GetPatientSupportRotationDirection(), and SetPatientSupportRotationDirection().
Float64 DicomBeamControlPoint::theSourceToSurfaceDistance private
Definition at line 205 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 205 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetSourceToSurfaceDistance(), and SetSourceToSurfaceDistance().
Float64 DicomBeamControlPoint::theSurfaceEntryPoint private
Definition at line 209 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 209 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetSurfaceEntryPoint(), and SetSurfaceEntryPoint().
Float64 DicomBeamControlPoint::theTableTopEccentricAngle private
Definition at line 202 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 202 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetTableTopEccentricAngle(), and SetTableTopEccentricAngle().
Float64 DicomBeamControlPoint::theTableTopEccentricAxisDistance private
Definition at line 210 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 210 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetTableTopEccentricAxisDistance(), and SetTableTopEccentricAxisDistance().
OFString DicomBeamControlPoint::theTableTopEccentricRotationDirection private
Definition at line 203 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 203 of file DicomBeamControlPoint.hh
Referenced by GetTableTopEccentricRotationDirection(), and SetTableTopEccentricRotationDirection().
Float64 DicomBeamControlPoint::theTableTopLateralPosition private
Definition at line 211 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 211 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetTableTopLateralPosition(), and SetTableTopLateralPosition().
Float64 DicomBeamControlPoint::theTableTopLongitudinalPosition private
Definition at line 212 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 212 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetTableTopLongitudinalPosition(), and SetTableTopLongitudinalPosition().
Float32 DicomBeamControlPoint::theTableTopPitchAngle private
Definition at line 213 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 213 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetTableTopPitchAngle(), and SetTableTopPitchAngle().
OFString DicomBeamControlPoint::theTableTopPitchRotationDirection private
Definition at line 214 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 214 of file DicomBeamControlPoint.hh
Referenced by GetTableTopPitchRotationDirection(), and SetTableTopPitchRotationDirection().
Float32 DicomBeamControlPoint::theTableTopRollAngle private
Definition at line 215 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 215 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetTableTopRollAngle(), and SetTableTopRollAngle().
OFString DicomBeamControlPoint::theTableTopRollRotationDirection private
Definition at line 216 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 216 of file DicomBeamControlPoint.hh
Referenced by GetTableTopRollRotationDirection(), and SetTableTopRollRotationDirection().
Float64 DicomBeamControlPoint::theTableTopVerticalPosition private
Definition at line 217 of file DicomBeamControlPoint.hh.
View newest version in sPHENIX GitHub at line 217 of file DicomBeamControlPoint.hh
Referenced by DumpToFile(), GetTableTopVerticalPosition(), and SetTableTopVerticalPosition().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/include/DicomBeamControlPoint.hh
geant4/tree/geant4-10.6-release/examples/extended/medical/DICOM/dicomReader/src/DicomBeamControlPoint.cc