ECCE @ EIC Software: G4NeutrinoNucleusModel Class Reference
G4NeutrinoNucleusModel Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/include/G4NeutrinoNucleusModel.hh>
Public Member Functions
G4NeutrinoNucleusModel (const G4String &name="neutrino-nucleus")
virtual ~G4NeutrinoNucleusModel ()
virtual G4bool IsApplicable (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)
virtual G4HadFinalState * ApplyYourself (const G4HadProjectile &aTrack, G4Nucleus &targetNucleus)=0
void ClusterDecay (G4LorentzVector &lvX, G4int qX)
void MesonDecay (G4LorentzVector &lvX, G4int qX)
void FinalBarion (G4LorentzVector &lvB, G4int qB, G4int pdgB)
void RecoilDeexcitation (G4Fragment &fragment)
void FinalMeson (G4LorentzVector &lvM, G4int qM, G4int pdgM)
void CoherentPion (G4LorentzVector &lvP, G4int pdgP, G4Nucleus &targetNucleus)
void SetCutEnergy (G4double ec)
G4double GetCutEnergy ()
G4double GetNuEnergy ()
G4double GetQtransfer ()
G4double GetQ2 ()
G4double GetXsample ()
G4int GetPDGencoding ()
G4bool GetCascade ()
G4bool GetString ()
G4double GetCosTheta ()
G4double GetEmu ()
G4double GetEx ()
G4double GetMuMass ()
G4double GetW2 ()
G4double GetM1 ()
G4double GetMr ()
G4double GetTr ()
G4double GetDp ()
G4LorentzVector GetLVl ()
G4LorentzVector GetLVh ()
G4LorentzVector GetLVt ()
G4LorentzVector GetLVcpi ()
G4double GetMinNuMuEnergy ()
G4double ThresholdEnergy (G4double mI, G4double mF, G4double mP)
G4double FinalMomentum (G4double mI, G4double mF, G4double mP, G4LorentzVector lvX)
G4double FermiMomentum (G4Nucleus &targetNucleus)
G4double NucleonMomentum (G4Nucleus &targetNucleus)
G4double GetEx (G4int A, G4bool fP)
G4double GgSampleNM (G4Nucleus &nucl)
G4int GetEnergyIndex (G4double energy)
G4double GetNuMuQeTotRat (G4int index, G4double energy)
G4int GetOnePionIndex (G4double energy)
G4double GetNuMuOnePionProb (G4int index, G4double energy)
virtual void ModelDescription (std::ostream &) const
Public Member Functions inherited from G4HadronicInteraction
G4HadronicInteraction (const G4String &modelName="HadronicModel")
virtual ~G4HadronicInteraction ()
virtual G4double SampleInvariantT (const G4ParticleDefinition *p, G4double plab, G4int Z, G4int A)
G4double GetMinEnergy () const
G4double GetMinEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMinEnergy (G4double anEnergy)
void SetMinEnergy (G4double anEnergy, const G4Element *anElement)
void SetMinEnergy (G4double anEnergy, const G4Material *aMaterial)
G4double GetMaxEnergy () const
G4double GetMaxEnergy (const G4Material *aMaterial, const G4Element *anElement) const
void SetMaxEnergy (const G4double anEnergy)
void SetMaxEnergy (G4double anEnergy, const G4Element *anElement)
void SetMaxEnergy (G4double anEnergy, const G4Material *aMaterial)
G4int GetVerboseLevel () const
void SetVerboseLevel (G4int value)
const G4String & GetModelName () const
void DeActivateFor (const G4Material *aMaterial)
void ActivateFor (const G4Material *aMaterial)
void DeActivateFor (const G4Element *anElement)
void ActivateFor (const G4Element *anElement)
G4bool IsBlocked (const G4Material *aMaterial) const
G4bool IsBlocked (const G4Element *anElement) const
void SetRecoilEnergyThreshold (G4double val)
G4double GetRecoilEnergyThreshold () const
virtual const std::pair
< G4double, G4double > GetFatalEnergyCheckLevels () const
virtual std::pair< G4double,
G4double > GetEnergyMomentumCheckLevels () const
void SetEnergyMomentumCheckLevels (G4double relativeLevel, G4double absoluteLevel)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void InitialiseModel ()
Protected Attributes
G4ParticleDefinition * theMuonMinus
G4ParticleDefinition * theMuonPlus
G4double fSin2tW
G4double fCutEnergy
G4int fNbin
G4int fIndex
G4int fEindex
G4int fXindex
G4int fQindex
G4int fOnePionIndex
G4int fPDGencoding
G4bool fCascade
G4bool fString
G4bool fProton
G4bool f2p2h
G4bool fBreak
G4double fNuEnergy
G4double fQ2
G4double fQtransfer
G4double fXsample
G4double fM1
G4double fM2
G4double fMt
G4double fMu
G4double fW2
G4double fMpi
G4double fW2pi
G4double fMinNuEnergy
G4double fDp
G4double fTr
G4double fEmu
G4double fEmuPi
G4double fEx
G4double fMr
G4double fCosTheta
G4double fCosThetaPi
G4LorentzVector fLVh
G4LorentzVector fLVl
G4LorentzVector fLVt
G4LorentzVector fLVcpi
G4GeneratorPrecompoundInterface * fPrecoInterface
G4PreCompoundModel * fPreCompound
G4ExcitationHandler * fDeExcitation
G4Nucleus * fRecoil
Protected Attributes inherited from G4HadronicInteraction
G4HadFinalState theParticleChange
G4int verboseLevel
G4double theMinEnergy
G4double theMaxEnergy
G4bool isBlocked
Static Protected Attributes
static const G4int fResNumber = 6
static const G4double fResMass [6]
static const G4int fClustNumber = 4
static const G4double fMesMass [4] = {1260., 980., 770., 139.57}
static const G4int fMesPDG [4] = {20213, 9000211, 213, 211}
static const G4double fBarMass [4] = {1700., 1600., 1232., 939.57}
static const G4int fBarPDG [4] = {12224, 32224, 2224, 2212}
static const G4double fNuMuResQ [50][50]
static const G4double fNuMuEnergy [50]
static const G4double fNuMuQeTotRat [50]
static const G4double fOnePionEnergy [58]
static const G4double fOnePionProb [58]
Additional Inherited Members
Protected Member Functions inherited from G4HadronicInteraction
void SetModelName (const G4String &nam)
G4bool IsBlocked () const
void Block ()
Detailed Description
Definition at line 62 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 62 of file G4NeutrinoNucleusModel.hh
Constructor & Destructor Documentation
G4NeutrinoNucleusModel::G4NeutrinoNucleusModel (const G4String & name = "neutrino-nucleus")
Definition at line 96 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 96 of file G4NeutrinoNucleusModel.cc
References e, eV, f2p2h, fBreak, fCascade, fCosTheta, fCosThetaPi, fCutEnergy, fDeExcitation, fDp, fEindex, fEmu, fEmuPi, fEx, fIndex, fLVcpi, fLVh, fLVl, fLVt, fM1, fM2, fMinNuEnergy, fMpi, fMr, fMt, fMu, fNbin, fNuEnergy, fOnePionIndex, fPDGencoding, fPrecoInterface, fPreCompound, fProton, fQ2, fQindex, fQtransfer, fRecoil, fSin2tW, fString, fTr, fW2, fW2pi, fXindex, fXsample, GetMinNuMuEnergy(), GeV, MeV, G4MuonMinus::MuonMinus(), G4MuonPlus::MuonPlus(), G4VIntraNuclearTransportModel::SetDeExcitation(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), TeV, theMuonMinus, and theMuonPlus.
G4NeutrinoNucleusModel::~G4NeutrinoNucleusModel () virtual
Definition at line 172 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 172 of file G4NeutrinoNucleusModel.cc
References fPrecoInterface.
Member Function Documentation
virtual G4HadFinalState* G4NeutrinoNucleusModel::ApplyYourself (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) pure virtual
Implements G4HadronicInteraction.
Implemented in G4NuMuNucleusNcModel, and G4NuMuNucleusCcModel.
void G4NeutrinoNucleusModel::ClusterDecay (G4LorentzVector & lvX, G4int qX)
Definition at line 533 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 533 of file G4NeutrinoNucleusModel.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), dir, fBarMass, fBarPDG, fClustNumber, FinalBarion(), G4ParticleTable::FindParticle(), fMesMass, G4RandomDirection(), G4UniformRand, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzVector::m(), MesonDecay(), and MeV.
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and G4NuMuNucleusNcModel::ApplyYourself().
void G4NeutrinoNucleusModel::CoherentPion (G4LorentzVector & lvP, G4int pdgP, G4Nucleus & targetNucleus)
Definition at line 413 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 413 of file G4NeutrinoNucleusModel.cc
References a, A(), G4HadFinalState::AddSecondary(), G4Nucleus::AtomicMass(), b, B(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), c, Acts::Test::dX, CLHEP::HepLorentzVector::e(), Acts::eX, FinalMomentum(), G4ParticleTable::FindParticle(), fLVcpi, fLVt, fMr, G4UniformRand, G4Nucleus::GetA_asInt(), G4NucleiProperties::GetNuclearMass(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetZ_asInt(), CLHEP::HepLorentzVector::m(), MeV, pdg, G4Proton::Proton(), RecoilDeexcitation(), G4Fragment::SetExcEnergyAndMomentum(), G4HadFinalState::SetLocalEnergyDeposit(), G4Fragment::SetNumberOfHoles(), targ, G4HadronicInteraction::theParticleChange, CLHEP::HepLorentzVector::vect(), and Z.
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and G4NuMuNucleusNcModel::ApplyYourself().
G4double G4NeutrinoNucleusModel::FermiMomentum (G4Nucleus & targetNucleus)
Definition at line 856 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 856 of file G4NeutrinoNucleusModel.cc
References A(), G4Nucleus::GetA_asInt(), G4Nucleus::GetZ_asInt(), kn, MeV, t1, t2, and Z.
Referenced by GgSampleNM(), and NucleonMomentum().
void G4NeutrinoNucleusModel::FinalBarion (G4LorentzVector & lvB, G4int qB, G4int pdgB)
Definition at line 253 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 253 of file G4NeutrinoNucleusModel.cc
References a, A(), G4HadFinalState::AddSecondary(), G4Nucleus::AtomicMass(), b, B(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), c, G4INCL::ClusterDecay::decay(), G4KineticTrack::Decay(), Acts::Test::dX, CLHEP::HepLorentzVector::e(), source.hepunit::electron_mass_c2, Acts::eX, fDp, G4ParticleTable::FindParticle(), fLVt, fMr, fRecoil, fTr, G4UniformRand, G4Nucleus::GetA_asInt(), G4NucleiProperties::GetNuclearMass(), G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), G4Nucleus::GetZ_asInt(), CLHEP::HepLorentzVector::m(), MeV, pdg, RecoilDeexcitation(), G4Fragment::SetExcEnergyAndMomentum(), G4HadFinalState::SetLocalEnergyDeposit(), G4Fragment::SetNumberOfHoles(), G4HadronicInteraction::theParticleChange, CLHEP::HepLorentzVector::vect(), and Z.
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and ClusterDecay().
void G4NeutrinoNucleusModel::FinalMeson (G4LorentzVector & lvM, G4int qM, G4int pdgM)
Definition at line 213 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 213 of file G4NeutrinoNucleusModel.cc
References G4HadFinalState::AddSecondary(), G4INCL::ClusterDecay::decay(), G4KineticTrack::Decay(), G4ParticleTable::FindParticle(), G4ParticleTable::GetParticleTable(), pdg, and G4HadronicInteraction::theParticleChange.
Referenced by MesonDecay().
G4double G4NeutrinoNucleusModel::FinalMomentum (G4double mI, G4double mF, G4double mP, G4LorentzVector lvX)
Definition at line 825 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 825 of file G4NeutrinoNucleusModel.cc
References a, b, B(), c, Acts::Test::delta, CLHEP::HepLorentzVector::e(), Acts::eX, CLHEP::Hep3Vector::mag(), and CLHEP::HepLorentzVector::vect().
Referenced by CoherentPion().
G4bool G4NeutrinoNucleusModel::GetCascade () inline
Definition at line 102 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 102 of file G4NeutrinoNucleusModel.hh
References fCascade.
G4double G4NeutrinoNucleusModel::GetCosTheta () inline
Definition at line 105 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 105 of file G4NeutrinoNucleusModel.hh
References fCosTheta.
G4double G4NeutrinoNucleusModel::GetCutEnergy () inline
Definition at line 94 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 94 of file G4NeutrinoNucleusModel.hh
References fCutEnergy.
G4double G4NeutrinoNucleusModel::GetDp () inline
Definition at line 113 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 113 of file G4NeutrinoNucleusModel.hh
References fDp.
G4double G4NeutrinoNucleusModel::GetEmu () inline
Definition at line 106 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 106 of file G4NeutrinoNucleusModel.hh
References fEmu.
G4int G4NeutrinoNucleusModel::GetEnergyIndex (G4double energy)
Definition at line 1012 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 1012 of file G4NeutrinoNucleusModel.cc
References fIndex, fNuMuEnergy, and GeV.
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and G4NuMuNucleusNcModel::ApplyYourself().
G4double G4NeutrinoNucleusModel::GetEx () inline
Definition at line 107 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 107 of file G4NeutrinoNucleusModel.hh
References fEx.
Referenced by G4NuMuNucleusCcModel::SampleLVkr().
G4double G4NeutrinoNucleusModel::GetEx (G4int A, G4bool fP)
Definition at line 914 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 914 of file G4NeutrinoNucleusModel.cc
References dE, e1, e2, Acts::eX, and MeV.
G4LorentzVector G4NeutrinoNucleusModel::GetLVcpi () inline
Definition at line 118 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 118 of file G4NeutrinoNucleusModel.hh
References fLVcpi.
G4LorentzVector G4NeutrinoNucleusModel::GetLVh () inline
Definition at line 116 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 116 of file G4NeutrinoNucleusModel.hh
References fLVh.
G4LorentzVector G4NeutrinoNucleusModel::GetLVl () inline
Definition at line 115 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 115 of file G4NeutrinoNucleusModel.hh
References fLVl.
G4LorentzVector G4NeutrinoNucleusModel::GetLVt () inline
Definition at line 117 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 117 of file G4NeutrinoNucleusModel.hh
References fLVt.
G4double G4NeutrinoNucleusModel::GetM1 () inline
Definition at line 110 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 110 of file G4NeutrinoNucleusModel.hh
References fM1.
G4double G4NeutrinoNucleusModel::GetMinNuMuEnergy () inline
Definition at line 120 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 120 of file G4NeutrinoNucleusModel.hh
References fM1, fMu, and CLHEP::MeV.
Referenced by G4NeutrinoNucleusModel().
G4double G4NeutrinoNucleusModel::GetMr () inline
Definition at line 111 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 111 of file G4NeutrinoNucleusModel.hh
References fMr.
G4double G4NeutrinoNucleusModel::GetMuMass () inline
Definition at line 108 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 108 of file G4NeutrinoNucleusModel.hh
References fMu.
G4double G4NeutrinoNucleusModel::GetNuEnergy () inline
Definition at line 96 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 96 of file G4NeutrinoNucleusModel.hh
References fNuEnergy.
G4double G4NeutrinoNucleusModel::GetNuMuOnePionProb (G4int index, G4double energy)
Definition at line 1113 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 1113 of file G4NeutrinoNucleusModel.cc
References angle, energy, fOnePionEnergy, fOnePionIndex, fOnePionProb, GeV, ratio, x1, x2, y1, and y2.
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and G4NuMuNucleusNcModel::ApplyYourself().
G4double G4NeutrinoNucleusModel::GetNuMuQeTotRat (G4int index, G4double energy)
Definition at line 1033 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 1033 of file G4NeutrinoNucleusModel.cc
References angle, energy, fIndex, fNuMuEnergy, fNuMuQeTotRat, fOnePionEnergy, GeV, ratio, x1, x2, y1, and y2.
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and G4NuMuNucleusNcModel::ApplyYourself().
G4int G4NeutrinoNucleusModel::GetOnePionIndex (G4double energy)
Definition at line 1092 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 1092 of file G4NeutrinoNucleusModel.cc
References fOnePionEnergy, fOnePionIndex, and GeV.
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and G4NuMuNucleusNcModel::ApplyYourself().
G4int G4NeutrinoNucleusModel::GetPDGencoding () inline
Definition at line 101 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 101 of file G4NeutrinoNucleusModel.hh
References fPDGencoding.
G4double G4NeutrinoNucleusModel::GetQ2 () inline
Definition at line 98 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 98 of file G4NeutrinoNucleusModel.hh
References fQ2.
G4double G4NeutrinoNucleusModel::GetQtransfer () inline
Definition at line 97 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 97 of file G4NeutrinoNucleusModel.hh
References fQtransfer.
G4bool G4NeutrinoNucleusModel::GetString () inline
Definition at line 103 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 103 of file G4NeutrinoNucleusModel.hh
References fString.
G4double G4NeutrinoNucleusModel::GetTr () inline
Definition at line 112 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 112 of file G4NeutrinoNucleusModel.hh
References fTr.
G4double G4NeutrinoNucleusModel::GetW2 () inline
Definition at line 109 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 109 of file G4NeutrinoNucleusModel.hh
References fW2.
G4double G4NeutrinoNucleusModel::GetXsample () inline
Definition at line 99 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 99 of file G4NeutrinoNucleusModel.hh
References fXsample.
G4double G4NeutrinoNucleusModel::GgSampleNM (G4Nucleus & nucl)
Definition at line 955 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 955 of file G4NeutrinoNucleusModel.cc
References A(), f2p2h, FermiMomentum(), G4UniformRand, G4Nucleus::GetA_asInt(), mom, G4INCL::DeJongSpin::shoot(), and xx.
Referenced by G4NuMuNucleusCcModel::SampleLVkr().
G4bool G4NeutrinoNucleusModel::IsApplicable (const G4HadProjectile & aTrack, G4Nucleus & targetNucleus) virtual
Reimplemented from G4HadronicInteraction.
Reimplemented in G4NuMuNucleusNcModel, and G4NuMuNucleusCcModel.
Definition at line 189 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 189 of file G4NeutrinoNucleusModel.cc
References energy, fMinNuEnergy, G4HadProjectile::GetDefinition(), G4ParticleDefinition::GetParticleName(), G4HadProjectile::GetTotalEnergy(), G4Nucleus::GetZ_asInt(), and Z.
void G4NeutrinoNucleusModel::MesonDecay (G4LorentzVector & lvX, G4int qX)
Definition at line 666 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 666 of file G4NeutrinoNucleusModel.cc
References CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), dir, fClustNumber, FinalMeson(), G4ParticleTable::FindParticle(), fMesMass, fMesPDG, G4RandomDirection(), G4UniformRand, G4ParticleTable::GetParticleTable(), G4ParticleDefinition::GetPDGMass(), CLHEP::HepLorentzVector::m(), and MeV.
Referenced by ClusterDecay().
void G4NeutrinoNucleusModel::ModelDescription (std::ostream & outFile) const virtual
Reimplemented from G4HadronicInteraction.
Reimplemented in G4NuMuNucleusNcModel, and G4NuMuNucleusCcModel.
Definition at line 178 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 178 of file G4NeutrinoNucleusModel.cc
G4double G4NeutrinoNucleusModel::NucleonMomentum (G4Nucleus & targetNucleus)
Definition at line 887 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 887 of file G4NeutrinoNucleusModel.cc
References A(), f2p2h, FermiMomentum(), G4UniformRand, G4Nucleus::GetA_asInt(), GeV, and mom.
Referenced by G4NuMuNucleusNcModel::SampleLVkr().
void G4NeutrinoNucleusModel::RecoilDeexcitation (G4Fragment & fragment)
Definition at line 376 of file G4NeutrinoNucleusModel.cc.
View newest version in sPHENIX GitHub at line 376 of file G4NeutrinoNucleusModel.cc
References G4HadFinalState::AddSecondary(), G4PreCompoundModel::DeExcite(), fPreCompound, and G4HadronicInteraction::theParticleChange.
Referenced by CoherentPion(), and FinalBarion().
void G4NeutrinoNucleusModel::SetCutEnergy (G4double ec) inline
Definition at line 93 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 93 of file G4NeutrinoNucleusModel.hh
References fCutEnergy.
G4double G4NeutrinoNucleusModel::ThresholdEnergy (G4double mI, G4double mF, G4double mP) inline
Definition at line 122 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 122 of file G4NeutrinoNucleusModel.hh
References fW2, and w.
Member Data Documentation
G4bool G4NeutrinoNucleusModel::f2p2h protected
Definition at line 154 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), GgSampleNM(), NucleonMomentum(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
const G4double G4NeutrinoNucleusModel::fBarMass = {1700., 1600., 1232., 939.57} static protected
Definition at line 179 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 179 of file G4NeutrinoNucleusModel.hh
Referenced by ClusterDecay().
const G4int G4NeutrinoNucleusModel::fBarPDG = {12224, 32224, 2224, 2212} static protected
Definition at line 180 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 180 of file G4NeutrinoNucleusModel.hh
Referenced by ClusterDecay().
G4bool G4NeutrinoNucleusModel::fBreak protected
Definition at line 154 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4bool G4NeutrinoNucleusModel::fCascade protected
Definition at line 154 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), and GetCascade().
const G4int G4NeutrinoNucleusModel::fClustNumber = 4 static protected
Definition at line 174 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 174 of file G4NeutrinoNucleusModel.hh
Referenced by ClusterDecay(), and MesonDecay().
G4double G4NeutrinoNucleusModel::fCosTheta protected
Definition at line 160 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), GetCosTheta(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4double G4NeutrinoNucleusModel::fCosThetaPi protected
Definition at line 160 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel().
G4double G4NeutrinoNucleusModel::fCutEnergy protected
Definition at line 151 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 151 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), GetCutEnergy(), and SetCutEnergy().
G4ExcitationHandler* G4NeutrinoNucleusModel::fDeExcitation protected
Definition at line 166 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 166 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel().
G4double G4NeutrinoNucleusModel::fDp protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by FinalBarion(), G4NeutrinoNucleusModel(), and GetDp().
G4int G4NeutrinoNucleusModel::fEindex protected
Definition at line 153 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), G4NuMuNucleusCcModel::SampleQkr(), G4NuMuNucleusNcModel::SampleQkr(), G4NuMuNucleusCcModel::SampleXkr(), and G4NuMuNucleusNcModel::SampleXkr().
G4double G4NeutrinoNucleusModel::fEmu protected
Definition at line 160 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), GetEmu(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4double G4NeutrinoNucleusModel::fEmuPi protected
Definition at line 160 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel().
G4double G4NeutrinoNucleusModel::fEx protected
Definition at line 160 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), and GetEx().
G4int G4NeutrinoNucleusModel::fIndex protected
Definition at line 153 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), GetEnergyIndex(), and GetNuMuQeTotRat().
G4LorentzVector G4NeutrinoNucleusModel::fLVcpi protected
Definition at line 162 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4NeutrinoNucleusModel.hh
Referenced by CoherentPion(), G4NeutrinoNucleusModel(), and GetLVcpi().
G4LorentzVector G4NeutrinoNucleusModel::fLVh protected
Definition at line 162 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), GetLVh(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4LorentzVector G4NeutrinoNucleusModel::fLVl protected
Definition at line 162 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), GetLVl(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4LorentzVector G4NeutrinoNucleusModel::fLVt protected
Definition at line 162 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 162 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), CoherentPion(), FinalBarion(), G4NeutrinoNucleusModel(), GetLVt(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4double G4NeutrinoNucleusModel::fM1 protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), GetM1(), G4NuMuNucleusCcModel::GetMinNuMuEnergy(), G4NuMuNucleusNcModel::GetMinNuMuEnergy(), GetMinNuMuEnergy(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4double G4NeutrinoNucleusModel::fM2 protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel().
const G4double G4NeutrinoNucleusModel::fMesMass = {1260., 980., 770., 139.57} static protected
Definition at line 176 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 176 of file G4NeutrinoNucleusModel.hh
Referenced by ClusterDecay(), and MesonDecay().
const G4int G4NeutrinoNucleusModel::fMesPDG = {20213, 9000211, 213, 211} static protected
Definition at line 177 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 177 of file G4NeutrinoNucleusModel.hh
Referenced by MesonDecay().
G4double G4NeutrinoNucleusModel::fMinNuEnergy protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), G4NuMuNucleusCcModel::IsApplicable(), IsApplicable(), and G4NuMuNucleusNcModel::IsApplicable().
G4double G4NeutrinoNucleusModel::fMpi protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), and G4NeutrinoNucleusModel().
G4double G4NeutrinoNucleusModel::fMr protected
Definition at line 160 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 160 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), CoherentPion(), FinalBarion(), G4NeutrinoNucleusModel(), and GetMr().
G4double G4NeutrinoNucleusModel::fMt protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), and G4NeutrinoNucleusModel().
G4double G4NeutrinoNucleusModel::fMu protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NeutrinoNucleusModel(), G4NuMuNucleusCcModel::GetMinNuMuEnergy(), GetMinNuMuEnergy(), GetMuMass(), and G4NuMuNucleusCcModel::SampleLVkr().
G4int G4NeutrinoNucleusModel::fNbin protected
Definition at line 153 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), G4NuMuNucleusCcModel::InitialiseModel(), and G4NuMuNucleusNcModel::InitialiseModel().
G4double G4NeutrinoNucleusModel::fNuEnergy protected
Definition at line 156 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), GetNuEnergy(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
const G4double G4NeutrinoNucleusModel::fNuMuEnergy static protected
Initial value:
=
{
  0.112103, 0.117359, 0.123119, 0.129443, 0.136404,
  0.144084, 0.152576, 0.161991, 0.172458, 0.184126,
  0.197171, 0.211801, 0.228261, 0.24684, 0.267887,
  0.291816, 0.319125, 0.350417, 0.386422, 0.428032,
  0.47634, 0.532692, 0.598756, 0.676612, 0.768868,
  0.878812, 1.01062, 1.16963, 1.36271, 1.59876,
  1.88943, 2.25002, 2.70086, 3.26916, 3.99166,
  4.91843, 6.11836, 7.6872, 9.75942, 12.5259,
  16.2605, 21.3615, 28.4141, 38.2903, 52.3062,
  72.4763, 101.93, 145.6, 211.39, 312.172
}
Definition at line 185 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 185 of file G4NeutrinoNucleusModel.hh
Referenced by GetEnergyIndex(), and GetNuMuQeTotRat().
const G4double G4NeutrinoNucleusModel::fNuMuQeTotRat static protected
Initial value:
=
{
  0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98,
  0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98,
  0.97, 0.96, 0.95, 0.93,
  0.917794, 0.850239, 0.780412, 0.709339, 0.638134, 0.568165,
  0.500236, 0.435528, 0.375015, 0.319157, 0.268463, 0.2232, 0.183284,
  0.148627, 0.119008, 0.0940699, 0.0733255, 0.0563819, 0.0427312, 0.0319274,
  0.0235026, 0.0170486, 0.0122149, 0.00857825, 0.00594018, 0.00405037
}
Definition at line 186 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 186 of file G4NeutrinoNucleusModel.hh
Referenced by GetNuMuQeTotRat().
const G4double G4NeutrinoNucleusModel::fNuMuResQ[50][50] static protected
Definition at line 182 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 182 of file G4NeutrinoNucleusModel.hh
const G4double G4NeutrinoNucleusModel::fOnePionEnergy static protected
Initial value:
=
{
  0.275314, 0.293652, 0.31729, 0.33409, 0.351746, 0.365629, 0.380041, 0.400165, 0.437941, 0.479237,
  0.504391, 0.537803, 0.588487, 0.627532, 0.686839, 0.791905, 0.878332, 0.987405, 1.08162, 1.16971,
  1.2982, 1.40393, 1.49854, 1.64168, 1.7524, 1.87058, 2.02273, 2.15894, 2.3654, 2.55792, 2.73017,
  3.03005, 3.40733, 3.88128, 4.53725, 5.16786, 5.73439, 6.53106, 7.43879, 8.36214, 9.39965, 10.296,
  11.5735, 13.1801, 15.2052, 17.5414, 19.7178, 22.7462, 25.9026, 29.4955, 33.5867, 39.2516, 46.4716,
  53.6065, 63.4668, 73.2147, 85.5593, 99.9854
}
Definition at line 187 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 187 of file G4NeutrinoNucleusModel.hh
Referenced by GetNuMuOnePionProb(), GetNuMuQeTotRat(), and GetOnePionIndex().
G4int G4NeutrinoNucleusModel::fOnePionIndex protected
Definition at line 153 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), GetNuMuOnePionProb(), and GetOnePionIndex().
const G4double G4NeutrinoNucleusModel::fOnePionProb static protected
Initial value:
=
{
  0.0019357, 0.0189361, 0.0378722, 0.0502758, 0.0662559, 0.0754581, 0.0865008, 0.0987275, 0.124112,
  0.153787, 0.18308, 0.213996, 0.245358, 0.274425, 0.301536, 0.326612, 0.338208, 0.337806, 0.335948,
  0.328092, 0.313557, 0.304965, 0.292169, 0.28481, 0.269474, 0.254138, 0.247499, 0.236249, 0.221654,
  0.205492, 0.198781, 0.182216, 0.162251, 0.142878, 0.128631, 0.116001, 0.108435, 0.0974843, 0.082092,
  0.0755204, 0.0703121, 0.0607066, 0.0554278, 0.0480401, 0.0427023, 0.0377123, 0.0323248, 0.0298584,
  0.0244296, 0.0218526, 0.019121, 0.016477, 0.0137309, 0.0137963, 0.0110371, 0.00834028, 0.00686127, 0.00538226
}
Definition at line 188 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 188 of file G4NeutrinoNucleusModel.hh
Referenced by GetNuMuOnePionProb().
G4int G4NeutrinoNucleusModel::fPDGencoding protected
Definition at line 153 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), and GetPDGencoding().
G4GeneratorPrecompoundInterface* G4NeutrinoNucleusModel::fPrecoInterface protected
Definition at line 164 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 164 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), and ~G4NeutrinoNucleusModel().
G4PreCompoundModel* G4NeutrinoNucleusModel::fPreCompound protected
Definition at line 165 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 165 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), and RecoilDeexcitation().
G4bool G4NeutrinoNucleusModel::fProton protected
Definition at line 154 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), and G4NuMuNucleusCcModel::SampleLVkr().
G4double G4NeutrinoNucleusModel::fQ2 protected
Definition at line 156 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), GetQ2(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4int G4NeutrinoNucleusModel::fQindex protected
Definition at line 153 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), G4NuMuNucleusCcModel::GetQkr(), and G4NuMuNucleusNcModel::GetQkr().
G4double G4NeutrinoNucleusModel::fQtransfer protected
Definition at line 156 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), GetQtransfer(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4Nucleus* G4NeutrinoNucleusModel::fRecoil protected
Definition at line 169 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 169 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), FinalBarion(), and G4NeutrinoNucleusModel().
const G4double G4NeutrinoNucleusModel::fResMass static protected
Initial value:
=
  {2190., 1920., 1700., 1600., 1440., 1232. }
Definition at line 172 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 172 of file G4NeutrinoNucleusModel.hh
const G4int G4NeutrinoNucleusModel::fResNumber = 6 static protected
Definition at line 171 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 171 of file G4NeutrinoNucleusModel.hh
G4double G4NeutrinoNucleusModel::fSin2tW protected
Definition at line 150 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 150 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel().
G4bool G4NeutrinoNucleusModel::fString protected
Definition at line 154 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 154 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), and GetString().
G4double G4NeutrinoNucleusModel::fTr protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by FinalBarion(), G4NeutrinoNucleusModel(), and GetTr().
G4double G4NeutrinoNucleusModel::fW2 protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), G4NuMuNucleusNcModel::ApplyYourself(), G4NeutrinoNucleusModel(), GetW2(), G4NuMuNucleusCcModel::SampleLVkr(), G4NuMuNucleusNcModel::SampleLVkr(), G4NuMuNucleusCcModel::ThresholdEnergy(), G4NuMuNucleusNcModel::ThresholdEnergy(), and ThresholdEnergy().
G4double G4NeutrinoNucleusModel::fW2pi protected
Definition at line 158 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 158 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel().
G4int G4NeutrinoNucleusModel::fXindex protected
Definition at line 153 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 153 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), G4NuMuNucleusCcModel::GetXkr(), G4NuMuNucleusNcModel::GetXkr(), G4NuMuNucleusCcModel::SampleQkr(), and G4NuMuNucleusNcModel::SampleQkr().
G4double G4NeutrinoNucleusModel::fXsample protected
Definition at line 156 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 156 of file G4NeutrinoNucleusModel.hh
Referenced by G4NeutrinoNucleusModel(), GetXsample(), G4NuMuNucleusCcModel::SampleLVkr(), and G4NuMuNucleusNcModel::SampleLVkr().
G4ParticleDefinition* G4NeutrinoNucleusModel::theMuonMinus protected
Definition at line 147 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 147 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and G4NeutrinoNucleusModel().
G4ParticleDefinition* G4NeutrinoNucleusModel::theMuonPlus protected
Definition at line 148 of file G4NeutrinoNucleusModel.hh.
View newest version in sPHENIX GitHub at line 148 of file G4NeutrinoNucleusModel.hh
Referenced by G4NuMuNucleusCcModel::ApplyYourself(), and G4NeutrinoNucleusModel().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/include/G4NeutrinoNucleusModel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/lepto_nuclear/src/G4NeutrinoNucleusModel.cc