ECCE @ EIC Software: cheprep::DefaultHepRepType Class Reference
cheprep::DefaultHepRepType Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepType.h>
Public Member Functions
DefaultHepRepType (HEPREP::HepRepType *parent, std::string name)
DefaultHepRepType (HEPREP::HepRepTypeTree *parent, std::string name)
~DefaultHepRepType ()
HEPREP::HepRepType * getSuperType ()
HEPREP::HepRepAttDef * getAttDef (std::string name)
HEPREP::HepRepAttValue * getAttValue (std::string name)
HEPREP::HepRepType * copy (HEPREP::HepRepType *parent)
std::string getName ()
std::string getFullName ()
std::string getDescription ()
void setDescription (std::string description)
std::string getInfoURL ()
void setInfoURL (std::string infoURL)
void addType (HEPREP::HepRepType *type)
std::vector< HEPREP::HepRepType * > getTypeList ()
Public Member Functions inherited from cheprep::DefaultHepRepDefinition
DefaultHepRepDefinition ()
~DefaultHepRepDefinition ()
void addAttDef (HEPREP::HepRepAttDef *hepRepAttDef)
void addAttDef (std::string name, std::string desc, std::string type, std::string extra)
std::set< HEPREP::HepRepAttDef * > getAttDefsFromNode ()
HEPREP::HepRepAttDef * getAttDefFromNode (std::string lowerCaseName)
Public Member Functions inherited from cheprep::DefaultHepRepAttribute
DefaultHepRepAttribute ()
~DefaultHepRepAttribute ()
std::set
< HEPREP::HepRepAttValue * > getAttValuesFromNode ()
void addAttValue (HEPREP::HepRepAttValue *hepRepAttValue)
void addAttValue (std::string key, char *value, int showLabel)
void addAttValue (std::string key, std::string value, int showLabel)
void addAttValue (std::string key, int value, int showLabel)
void addAttValue (std::string key, int64 value, int showLabel)
void addAttValue (std::string key, double value, int showLabel)
void addAttValue (std::string key, bool value, int showLabel)
void addAttValue (std::string key, std::vector< double > value, int showLabel)
void addAttValue (std::string key, double red, double green, double blue, double alpha, int showLabel)
HEPREP::HepRepAttValue * getAttValueFromNode (std::string lowerCaseName)
HEPREP::HepRepAttValue * removeAttValue (std::string key)
Public Member Functions inherited from HEPREP::HepRepAttribute
virtual ~HepRepAttribute ()
Destructor.
Public Member Functions inherited from HEPREP::HepRepDefinition
virtual ~HepRepDefinition ()
Destructor.
Public Member Functions inherited from HEPREP::HepRepType
virtual ~HepRepType ()
Destructor.
Private Attributes
HEPREP::HepRepType * parent
std::vector< HEPREP::HepRepType * > types
std::string name
std::string description
std::string infoURL
Detailed Description
Definition at line 24 of file DefaultHepRepType.h.
View newest version in sPHENIX GitHub at line 24 of file DefaultHepRepType.h
Constructor & Destructor Documentation
cheprep::DefaultHepRepType::DefaultHepRepType (HEPREP::HepRepType * parent, std::string name)
Definition at line 13 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 13 of file DefaultHepRepType.cc
References HEPREP::HepRepType::addType(), description, infoURL, and parent.
cheprep::DefaultHepRepType::DefaultHepRepType (HEPREP::HepRepTypeTree * parent, std::string name)
Definition at line 24 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 24 of file DefaultHepRepType.cc
References HEPREP::HepRepTypeTree::addType(), description, and infoURL.
cheprep::DefaultHepRepType::~DefaultHepRepType ()
Definition at line 32 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 32 of file DefaultHepRepType.cc
References types.
Member Function Documentation
void cheprep::DefaultHepRepType::addType (HEPREP::HepRepType * type) virtual
Adds a sub-type to this type.
Parameters
type sub-type to be added.
Implements HEPREP::HepRepType.
Definition at line 102 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 102 of file DefaultHepRepType.cc
References types.
HepRepType * cheprep::DefaultHepRepType::copy (HEPREP::HepRepType * parent) virtual
Returns a deep copy of this type.
Parameters
parent to which this copy is added.
Returns
copy of this type.
Implements HEPREP::HepRepType.
Definition at line 73 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 73 of file DefaultHepRepType.cc
HepRepAttDef * cheprep::DefaultHepRepType::getAttDef (std::string name) virtual
Return a named attribute definition searched on this node and any parent nodes.
Parameters
name of attribute definition.
Returns
attribute definition.
Implements cheprep::DefaultHepRepDefinition.
Definition at line 42 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 42 of file DefaultHepRepType.cc
References HEPREP::HepRepDefinition::getAttDefFromNode(), and HEPREP::HepRepType::getSuperType().
HepRepAttValue * cheprep::DefaultHepRepType::getAttValue (std::string name) virtual
searched for a value with given name. Search up the type tree if needed.
Implements cheprep::DefaultHepRepDefinition.
Definition at line 59 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 59 of file DefaultHepRepType.cc
References HEPREP::HepRepAttribute::getAttValueFromNode(), and HEPREP::HepRepType::getSuperType().
string cheprep::DefaultHepRepType::getDescription () virtual
Returns the description of this type.
Returns
description of type.
Implements HEPREP::HepRepType.
Definition at line 86 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 86 of file DefaultHepRepType.cc
References description.
string cheprep::DefaultHepRepType::getFullName () virtual
Returns the full name of this type. The full name is constructed from the root of the typeTree (without the typeTreeName) by concatenating all the node names separated by slashes "/". For example: Geometry/InnerDetector/Sector24/Wire20
Returns
full name of type.
See Also
getName()
Implements HEPREP::HepRepType.
Definition at line 82 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 82 of file DefaultHepRepType.cc
References HEPREP::HepRepType::getFullName(), getName(), and getSuperType().
string cheprep::DefaultHepRepType::getInfoURL () virtual
Returns the information URL of this type.
Returns
info URL of type.
Implements HEPREP::HepRepType.
Definition at line 94 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 94 of file DefaultHepRepType.cc
References infoURL.
string cheprep::DefaultHepRepType::getName () virtual
Returns the name of this type. This is the full name if one uses flat-types, and the node name if one uses hierarchical typenames. It is the name supplied at construction of the type.
Returns
name of type.
See Also
getFullName()
Implements HEPREP::HepRepType.
Definition at line 78 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 78 of file DefaultHepRepType.cc
References name.
Referenced by getFullName().
HepRepType * cheprep::DefaultHepRepType::getSuperType () virtual
Returns the parent of this type.
Returns
parent of type, or null if top-level.
Implements HEPREP::HepRepType.
Definition at line 38 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 38 of file DefaultHepRepType.cc
References parent.
Referenced by getFullName().
vector< HepRepType * > cheprep::DefaultHepRepType::getTypeList () virtual
Returns a collection of all the sub-types of this type.
Returns
collection of HepRepTypes.
Implements HEPREP::HepRepType.
Definition at line 107 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 107 of file DefaultHepRepType.cc
References types.
void cheprep::DefaultHepRepType::setDescription (std::string description) virtual
Sets the description of this type.
Parameters
infoURL
Implements HEPREP::HepRepType.
Definition at line 90 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 90 of file DefaultHepRepType.cc
References incremental_prev_tag::desc, and description.
void cheprep::DefaultHepRepType::setInfoURL (std::string infoURL) virtual
Sets the information URL of this type.
Parameters
infoURL
Implements HEPREP::HepRepType.
Definition at line 98 of file DefaultHepRepType.cc.
View newest version in sPHENIX GitHub at line 98 of file DefaultHepRepType.cc
References infoURL.
Member Data Documentation
std::string cheprep::DefaultHepRepType::description private
Definition at line 30 of file DefaultHepRepType.h.
View newest version in sPHENIX GitHub at line 30 of file DefaultHepRepType.h
Referenced by DefaultHepRepType(), getDescription(), and setDescription().
std::string cheprep::DefaultHepRepType::infoURL private
Definition at line 31 of file DefaultHepRepType.h.
View newest version in sPHENIX GitHub at line 31 of file DefaultHepRepType.h
Referenced by DefaultHepRepType(), getInfoURL(), and setInfoURL().
std::string cheprep::DefaultHepRepType::name private
Definition at line 29 of file DefaultHepRepType.h.
View newest version in sPHENIX GitHub at line 29 of file DefaultHepRepType.h
Referenced by getName().
HEPREP::HepRepType* cheprep::DefaultHepRepType::parent private
Definition at line 27 of file DefaultHepRepType.h.
View newest version in sPHENIX GitHub at line 27 of file DefaultHepRepType.h
Referenced by DefaultHepRepType(), and getSuperType().
std::vector<HEPREP::HepRepType*> cheprep::DefaultHepRepType::types private
Definition at line 28 of file DefaultHepRepType.h.
View newest version in sPHENIX GitHub at line 28 of file DefaultHepRepType.h
Referenced by addType(), getTypeList(), and ~DefaultHepRepType().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/HepRep/include/cheprep/DefaultHepRepType.h
geant4/tree/geant4-10.6-release/source/visualization/HepRep/src/DefaultHepRepType.cc