ECCE @ EIC Software: G4Abla Class Reference
G4Abla Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/include/G4Abla.hh>
Public Member Functions
G4Abla (G4Volant *aVolant, G4VarNtp *aVarntp)
~G4Abla ()
G4Abla (G4Abla const &other)
Dummy copy constructor.
G4Abla & operator= (G4Abla const &other)
Dummy assignment operator.
void setVerboseLevel (G4int level)
G4Volant * getVolant ()
void DeexcitationAblaxx (G4int nucleusA, G4int nucleusZ, G4double excitationEnergy, G4double angularMomentum, G4double momX, G4double momY, G4double momZ, G4int eventnumber)
void DeexcitationAblaxx (G4int nucleusA, G4int nucleusZ, G4double excitationEnergy, G4double angularMomentum, G4double momX, G4double momY, G4double momZ, G4int eventnumber, G4int nucleusS)
void initEvapora ()
void SetParameters ()
void SetParametersG4 (G4int z, G4int a)
void qrot (G4double z, G4double a, G4double bet, G4double sig, G4double u, G4double *qr)
void mglw (G4double a, G4double z, G4double *el)
void mglms (G4double a, G4double z, G4int refopt4, G4double *el)
G4double spdef (G4int a, G4int z, G4int optxfis)
G4double fissility (G4int a, G4int z, G4int ny, G4double sn, G4double slam, G4int optxfis)
void evapora (G4double zprf, G4double aprf, G4double *ee_par, G4double jprf, G4double *zf_par, G4double *af_par, G4double *mtota_par, G4double *vleva_par, G4double *vxeva_par, G4double *vyeva_par, G4int *ff_par, G4int *fimf_par, G4double *fzimf, G4double *faimf, G4double *tkeimf_par, G4double *jprfout, G4int *inttype_par, G4int *inum_par, G4double EV_TEMP[200][6], G4int *iev_tab_temp_par, G4int *nblam0)
void direct (G4double zprf, G4double a, G4double ee, G4double jprf, G4double *probp_par, G4double *probd_par, G4double *probt_par, G4double *probn_par, G4double *probhe_par, G4double *proba_par, G4double *probg_par, G4double *probimf_par, G4double *probf_par, G4double *problamb0_par, G4double *ptotl_par, G4double *sn_par, G4double *sbp_par, G4double *sbd_par, G4double *sbt_par, G4double *sbhe_par, G4double *sba_par, G4double *slamb0_par, G4double *ecn_par, G4double *ecp_par, G4double *ecd_par, G4double *ect_par, G4double *eche_par, G4double *eca_par, G4double *ecg_par, G4double *eclamb0_par, G4double *bp_par, G4double *bd_par, G4double *bt_par, G4double *bhe_par, G4double *ba_par, G4double *sp_par, G4double *sd_par, G4double *st_par, G4double *she_par, G4double *sa_par, G4double *ef_par, G4double *ts1_par, G4int, G4int inum, G4int itest, G4int *sortie, G4double *tcn, G4double *jprfn_par, G4double *jprfp_par, G4double *jprfd_par, G4double *jprft_par, G4double *jprfhe_par, G4double *jprfa_par, G4double *jprflamb0_par, G4double *tsum_par, G4int NbLam0)
void fission (G4double AF, G4double ZF, G4double EE, G4double JPRF, G4double *VX1_FISSION, G4double *VY1_FISSION, G4double *VZ1_FISSION, G4double *VX2_FISSION, G4double *VY2_FISSION, G4double *VZ2_FISSION, G4int *ZFP1, G4int *AFP1, G4int *SFP1, G4int *ZFP2, G4int *AFP2, G4int *SFP2, G4int *imode, G4double *VX_EVA_SC, G4double *VY_EVA_SC, G4double *VZ_EVA_SC, G4double EV_TEMP[200][6], G4int *IEV_TAB_FIS, G4int *NbLam0)
void lorentz_boost (G4double VXRIN, G4double VYRIN, G4double VZRIN, G4double VXIN, G4double VYIN, G4double VZIN, G4double *VXOUT, G4double *VYOUT, G4double *VZOUT)
void unstable_nuclei (G4int AFP, G4int ZFP, G4int *AFPNEW, G4int *ZFPNEW, G4int &IOUNSTABLE, G4double VX, G4double VY, G4double VZ, G4double *VP1X, G4double *VP1Y, G4double *VP1Z, G4double BU_TAB_TEMP[200][6], G4int *ILOOP)
void unstable_tke (G4double AIN, G4double ZIN, G4double ANEW, G4double ZNEW, G4double VXIN, G4double VYIN, G4double VZIN, G4double *V1X, G4double *V1Y, G4double *V1Z, G4double *V2X, G4double *V2Y, G4double *V2Z)
void tke_bu (G4double Z, G4double A, G4double ZALL, G4double AAL, G4double *VX, G4double *VY, G4double *VZ)
void AMOMENT (G4double AABRA, G4double APRF, G4int IMULTIFR, G4double *PX, G4double *PY, G4double *PZ)
void barrs (G4int Z1, G4int A1, G4int Z2, G4int A2, G4double *sBARR, G4double *sOMEGA)
void evap_postsaddle (G4double A, G4double Z, G4double E_scission_pre, G4double *E_scission_post, G4double *A_scission, G4double *Z_scission, G4double &vx_eva, G4double &vy_eva, G4double &vz_eva, G4int *NbLam0_par)
void imf (G4double ACN, G4double ZCN, G4double TEMP, G4double EE, G4double *ZIMF, G4double *AIMF, G4double *BIMF, G4double *SBIMF, G4double *TIMF, G4double JPRF)
void fomega_sp (G4double AF, G4double Y, G4double *MFCD, G4double *sOMEGA, G4double *sHOMEGA)
void fomega_gs (G4double AF, G4double ZF, G4double *K1, G4double *sOMEGA, G4double *sHOMEGA)
G4double tunnelling (G4double A, G4double ZPRF, G4double Y, G4double EE, G4double EF, G4double TEMP, G4double DENSG, G4double DENSF, G4double ENH_FACT)
void fission_width (G4double ZPRF, G4double A, G4double EE, G4double BS, G4double BK, G4double EF, G4double Y, G4double *GF, G4double *TEMP, G4double JPR, G4int IEROT, G4int FF_ALLOWED, G4int OPTCOL, G4int OPTSHP, G4double DENSG)
void unbound (G4double SN, G4double SP, G4double SD, G4double ST, G4double SHE, G4double SA, G4double BP, G4double BD, G4double BT, G4double BHE, G4double BA, G4double *PROBF, G4double *PROBN, G4double *PROBP, G4double *PROBD, G4double *PROBT, G4double *PROBHE, G4double *PROBA, G4double *PROBIMF, G4double *PROBG, G4double *ECN, G4double *ECP, G4double *ECD, G4double *ECT, G4double *ECHE, G4double *ECA)
void fissionDistri (G4double &a, G4double &z, G4double &e, G4double &a1, G4double &z1, G4double &e1, G4double &v1, G4double &a2, G4double &z2, G4double &e2, G4double &v2, G4double &vx_eva_sc, G4double &vy_eva_sc, G4double &vz_eva_sc, G4int *NbLam0_par)
void even_odd (G4double r_origin, G4double r_even_odd, G4int &i_out)
G4double umass (G4double z, G4double n, G4double beta)
G4double ecoul (G4double z1, G4double n1, G4double beta1, G4double z2, G4double n2, G4double beta2, G4double d)
G4double Uwash (G4double E, G4double Ecrit, G4double Freduction, G4double gamma)
G4double frldm (G4double z, G4double n, G4double beta)
G4double eflmac_profi (G4double a, G4double z)
G4double gausshaz (G4int k, G4double xmoy, G4double sig)
G4double haz (G4int k)
void densniv (G4double a, G4double z, G4double ee, G4double ef, G4double *dens, G4double bshell, G4double bs, G4double bk, G4double *temp, G4int optshp, G4int optcol, G4double defbet, G4double *ecor, G4double jprf, G4int ifis, G4double *qr)
void part_fiss (G4double BET, G4double GP, G4double GF, G4double Y, G4double TAUF, G4double TS1, G4double TSUM, G4int *CHOICE, G4double ZF, G4double AF, G4double FT, G4double *T_LAPSE, G4double *GF_LOC)
G4double func_trans (G4double TIME, G4double ZF, G4double AF, G4double BET, G4double Y, G4double FT, G4double T_0)
void lpoly (G4double x, G4int n, G4double pl[])
G4double eflmac (G4int ia, G4int iz, G4int flag, G4int optshp)
void appariem (G4double a, G4double z, G4double *del)
void parite (G4double n, G4double *par)
G4double tau (G4double bet, G4double homega, G4double ef, G4double t)
G4double cram (G4double bet, G4double homega)
G4double bipol (G4int iflag, G4double y)
void barfit (G4int iz, G4int ia, G4int il, G4double *sbfis, G4double *segs, G4double *selmax)
G4double width (G4double AMOTHER, G4double ZMOTHER, G4double APART, G4double ZPART, G4double TEMP, G4double B1, G4double SB1, G4double EXC)
G4double pen (G4double A, G4double ap, G4double omega, G4double T)
void lorb (G4double AMOTHER, G4double ADAUGHTER, G4double LMOTHER, G4double EEFINAL, G4double *LORBITAL, G4double *SIGMA_LORBITAL)
void bsbkbc (G4double A, G4double Z, G4double *BS, G4double *BK, G4double *BC)
G4double erf (G4double x)
G4double gammp (G4double a, G4double x)
void gcf (G4double *gammcf, G4double a, G4double x, G4double gln)
void gser (G4double *gamser, G4double a, G4double x, G4double gln)
G4double fvmaxhaz (G4double T)
G4double fvmaxhaz_neut (G4double x)
void standardRandom (G4double *rndm, G4long *seed)
G4double gammln (G4double xx)
G4double fd (G4double E)
G4double f (G4double E)
G4double fmaxhaz (G4double T)
G4double fmaxhaz_old (G4double T)
G4int IPOWERLIMHAZ (G4double lambda, G4int xmin, G4int xmax)
G4double pace2 (G4double a, G4double z)
void guet (G4double *x_par, G4double *z_par, G4double *find_par)
void isostab_lim (G4int z, G4int *nmin, G4int *nmax)
void FillData (G4int IMULTBU, G4int IEV_TAB)
G4double gethyperseparation (G4double A, G4double Z, G4int ny)
G4double getdeltabinding (G4double a, G4int nblamb)
G4double gethyperbinding (G4double A, G4double Z, G4int ny)
G4int min (G4int a, G4int b)
G4double min (G4double a, G4double b)
G4int max (G4int a, G4int b)
G4double max (G4double a, G4double b)
G4double DSIGN (G4double a, G4double b)
G4int ISIGN (G4int a, G4int b)
G4int nint (G4double number)
G4int secnds (G4int x)
G4int mod (G4int a, G4int b)
G4double dmod (G4double a, G4double b)
G4double dint (G4double a)
G4int idint (G4double a)
G4int idnint (G4double value)
G4double utilabs (G4double a)
G4double dmin1 (G4double a, G4double b, G4double c)
G4Ec2sub * getFrldmTable ()
Private Attributes
G4int verboseLevel
G4int ilast
G4double T_freeze_out_in
G4int IEV_TAB_SSC
G4double BU_TAB [200][12]
G4double EV_TAB [200][6]
G4double EV_TAB_SSC [200][6]
G4int gammaemission
G4double T_freeze_out
G4Pace * pace
G4Ald * ald
G4Eenuc * eenuc
G4Ec2sub * ec2sub
G4Ecld * ecld
G4Mexp * masses
G4Fb * fb
G4Fiss * fiss
G4Opt * opt
G4Volant * volant
G4VarNtp * varntp
G4int Ainit
G4int Zinit
G4int Sinit
Detailed Description
Class containing ABLA++ de-excitation code.
Definition at line 54 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 54 of file G4Abla.hh
Constructor & Destructor Documentation
G4Abla::G4Abla (G4Volant * aVolant, G4VarNtp * aVarntp)
This constructor is used by standalone test driver and the Geant4 interface.
Parameters
aHazard random seeds
aVolant data structure for ABLA output
aVarNtp data structure for transfering ABLA output to Geant4 interface
Definition at line 44 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 44 of file G4Abla.cc
References fb(), G4Volant::iv, and G4VarNtp::ntrack.
G4Abla::~G4Abla ()
Basic destructor.
Definition at line 82 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 82 of file G4Abla.cc
References ald, ec2sub, ecld, eenuc, fb, fiss, masses, opt, and pace.
G4Abla::G4Abla (G4Abla const & other)
Dummy copy constructor.
Member Function Documentation
void G4Abla::AMOMENT (G4double AABRA, G4double APRF, G4int IMULTIFR, G4double * PX, G4double * PY, G4double * PZ)
Calculation of the angular momentum of breakup fragments according to Goldhaber model
Definition at line 10223 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 10223 of file G4Abla.cc
References kdfinder::abs(), gausshaz(), and T_freeze_out.
Referenced by DeexcitationAblaxx().
void G4Abla::appariem (G4double a, G4double z, G4double * del)
Procedure for calculating the pairing correction to the binding energy of a specific nucleus.
Definition at line 5144 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5144 of file G4Abla.cc
References parite().
void G4Abla::barfit (G4int iz, G4int ia, G4int il, G4double * sbfis, G4double * segs, G4double * selmax)
THIS SUBROUTINE RETURNS THE BARRIER HEIGHT BFIS, THE GROUND-STATE ENERGY SEGS, IN MEV, AND THE ANGULAR MOMENTUM AT WHICH THE FISSION BARRIER DISAPPEARS, LMAX, IN UNITS OF H-BAR, WHEN CALLED WITH INTEGER AGUMENTS IZ, THE ATOMIC NUMBER, IA, THE ATOMIC MASS NUMBER, AND IL, THE ANGULAR MOMENTUM IN UNITS OF H-BAR. (PLANCK'S CONSTANT DIVIDED BY 2*PI).
Definition at line 5390 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5390 of file G4Abla.cc
References a, k, lpoly(), m, readPY::pl, x, y, z, and zz.
Referenced by direct().
void G4Abla::barrs (G4int Z1, G4int A1, G4int Z2, G4int A2, G4double * sBARR, G4double * sOMEGA)
Calculation of particle emission barriers.
Definition at line 5347 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5347 of file G4Abla.cc
References ecld, G4Ecld::rms, Z1, and Z2.
Referenced by direct(), and imf().
G4double G4Abla::bipol (G4int iflag, G4double y)
CALCULATION OF THE SURFACE BS OR CURVATURE BK OF A NUCLEUS RELATIVE TO THE SPHERICAL CONFIGURATION BASED ON MYERS, DROPLET MODEL FOR ARBITRARY SHAPES
Definition at line 5244 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5244 of file G4Abla.cc
References bk, e, idint(), and verboseLevel.
Referenced by direct().
void G4Abla::bsbkbc (G4double A, G4double Z, G4double * BS, G4double * BK, G4double * BC)
Calculation of BS and BK for the nuclear-level density.
Definition at line 6481 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6481 of file G4Abla.cc
References G4Ecld::beta2, G4Ecld::beta4, ecld, and idnint().
Referenced by direct(), and imf().
G4double G4Abla::cram (G4double bet, G4double homega)
KRAMERS FAKTOR - REDUCTION OF THE FISSION PROBABILITY INDEPENDENT OF EXCITATION ENERGY
Definition at line 5227 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5227 of file G4Abla.cc
Referenced by direct(), and func_trans().
void G4Abla::DeexcitationAblaxx (G4int nucleusA, G4int nucleusZ, G4double excitationEnergy, G4double angularMomentum, G4double momX, G4double momY, G4double momZ, G4int eventnumber)
Main interface to the de-excitation code.
Parameters
nucleusA mass number of the nucleus
nucleusZ charge number of the nucleus
excitationEnergy excitation energy of the nucleus
angularMomentum angular momentum of the nucleus (produced as output by INCL4)
momX momentum x-component
momY momentum y-component
momZ momentum z-component
eventnumber number of the event
Definition at line 96 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 96 of file G4Abla.cc
Referenced by G4AblaInterface::DeExcite().
void G4Abla::DeexcitationAblaxx (G4int nucleusA, G4int nucleusZ, G4double excitationEnergy, G4double angularMomentum, G4double momX, G4double momY, G4double momZ, G4int eventnumber, G4int nucleusS)
Main interface to the de-excitation code for hyper-nuclei.
Parameters
nucleusA mass number of the nucleus
nucleusZ charge number of the nucleus
excitationEnergy excitation energy of the nucleus
angularMomentum angular momentum of the nucleus (produced as output by INCL)
momX momentum x-component
momY momentum y-component
momZ momentum z-component
eventnumber number of the event
nucleusS is the strange number
Definition at line 102 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 102 of file G4Abla.cc
References kdfinder::abs(), Ainit, G4Ald::ak, ald, AMOMENT(), source.hepunit::amu, G4Ald::as, G4Ald::av, BU_TAB, C(), G4Volant::clear(), G4VarNtp::clear(), dint(), DSIGN(), eflmac(), EV_TAB, EV_TAB_SSC, evapora(), ff, FillData(), fiss, fission(), G4AblaRandom::flat(), gammaemission, gausshaz(), I, idnint(), G4Fiss::ifis, IPOWERLIMHAZ(), ISIGN(), isostab_lim(), G4Volant::iv, G4VarNtp::kfis, lorentz_boost(), max(), G4Opt::nblan0, G4VarNtp::ntrack, opt, G4Opt::optimfallowed, ran(), SetParametersG4(), Sinit, T_freeze_out, T_freeze_out_in, tke_bu(), unstable_nuclei(), V1, V2, varntp, volant, Zinit, and G4Fiss::zt.
void G4Abla::densniv (G4double a, G4double z, G4double ee, G4double ef, G4double * dens, G4double bshell, G4double bs, G4double bk, G4double * temp, G4int optshp, G4int optcol, G4double defbet, G4double * ecor, G4double jprf, G4int ifis, G4double * qr)
Level density parameters.
Definition at line 4473 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 4473 of file G4Abla.cc
References a, G4Ald::ak, ald, G4Ald::as, G4Ald::av, bk, e, G4Ecld::ecgnz, ecld, fe, fiss, idnint(), in, max(), G4Ald::optafan, G4Fiss::optct, parite(), pi, qrot(), y1, and y2.
Referenced by direct(), fission_width(), and imf().
G4double G4Abla::dint (G4double a)
Definition at line 6212 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6212 of file G4Abla.cc
Referenced by DeexcitationAblaxx(), direct(), evap_postsaddle(), evapora(), fissionDistri(), and parite().
void G4Abla::direct (G4double zprf, G4double a, G4double ee, G4double jprf, G4double * probp_par, G4double * probd_par, G4double * probt_par, G4double * probn_par, G4double * probhe_par, G4double * proba_par, G4double * probg_par, G4double * probimf_par, G4double * probf_par, G4double * problamb0_par, G4double * ptotl_par, G4double * sn_par, G4double * sbp_par, G4double * sbd_par, G4double * sbt_par, G4double * sbhe_par, G4double * sba_par, G4double * slamb0_par, G4double * ecn_par, G4double * ecp_par, G4double * ecd_par, G4double * ect_par, G4double * eche_par, G4double * eca_par, G4double * ecg_par, G4double * eclamb0_par, G4double * bp_par, G4double * bd_par, G4double * bt_par, G4double * bhe_par, G4double * ba_par, G4double * sp_par, G4double * sd_par, G4double * st_par, G4double * she_par, G4double * sa_par, G4double * ef_par, G4double * ts1_par, G4int , G4int inum, G4int itest, G4int * sortie, G4double * tcn, G4double * jprfn_par, G4double * jprfp_par, G4double * jprfd_par, G4double * jprft_par, G4double * jprfhe_par, G4double * jprfa_par, G4double * jprflamb0_par, G4double * tsum_par, G4int NbLam0)
Calculation of particle emission probabilities.
Definition at line 3109 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 3109 of file G4Abla.cc
References kdfinder::abs(), G4Ald::ak, ald, G4Ald::as, Acts::Test::at, G4Ald::av, barfit(), barrs(), G4Fiss::bet, G4Ecld::beta2, bipol(), bk, bp, bsbkbc(), cram(), densniv(), dint(), dmin1(), e, G4Ecld::ecgnz, ecld, G4Fb::efa, CEMC_TOWER::emin, fb, fiss, fissility(), fission_width(), fomega_gs(), fomega_sp(), fvmaxhaz(), fvmaxhaz_neut(), gammaemission, gausshaz(), getdeltabinding(), gethyperbinding(), gethyperseparation(), idnint(), G4Fiss::ifis, ilast, in, isostab_lim(), k, k1, lorb(), max(), mglms(), mglw(), min(), mod(), opt, G4Fiss::optcol, G4Opt::optimfallowed, G4Fiss::optshp, G4Opt::optshpimf, G4Fiss::optxfis, part_fiss(), pen(), pi, pt, sn, G4InuclParticleNames::sp, tau(), unbound(), G4Ecld::vgsld, width(), xx, and y.
Referenced by evap_postsaddle(), and evapora().
G4double G4Abla::dmin1 (G4double a, G4double b, G4double c)
Definition at line 6250 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6250 of file G4Abla.cc
References a, b, and c.
Referenced by direct(), evap_postsaddle(), evapora(), pythag(), and unbound().
G4double G4Abla::dmod (G4double a, G4double b)
G4double G4Abla::DSIGN (G4double a, G4double b)
Definition at line 6134 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6134 of file G4Abla.cc
References kdfinder::abs().
Referenced by DeexcitationAblaxx().
double G4Abla::ecoul (G4double z1, G4double n1, G4double beta1, G4double z2, G4double n2, G4double beta2, G4double d)
Definition at line 8974 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 8974 of file G4Abla.cc
References d.
Referenced by fissionDistri().
G4double G4Abla::eflmac (G4int ia, G4int iz, G4int flag, G4int optshp)
This function will calculate the liquid-drop nuclear mass for spheri configuration according to the preprint NUCLEAR GROUND-STATE MASSES and DEFORMATIONS by P. Mo"ller et al. from August 16, 1993 p. All constants are taken from this publication for consistency.
Definition at line 4991 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 4991 of file G4Abla.cc
References a, a0, kdfinder::abs(), G4Mexp::bind, c1, ff, in, masses, G4Mexp::mexpiop, mod(), n, parite(), pi, w, and z.
Referenced by DeexcitationAblaxx(), FillData(), initEvapora(), and mglms().
G4double G4Abla::eflmac_profi (G4double a, G4double z)
Definition at line 9048 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 9048 of file G4Abla.cc
References a, a0, c1, ff, in, n, pi, utilabs(), w, and z.
Referenced by frldm().
G4double G4Abla::erf (G4double x)
Special functions used for the emission of particles.
Definition at line 5704 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5704 of file G4Abla.cc
References gammp().
Referenced by width().
void G4Abla::evap_postsaddle (G4double A, G4double Z, G4double E_scission_pre, G4double * E_scission_post, G4double * A_scission, G4double * Z_scission, G4double & vx_eva, G4double & vy_eva, G4double & vz_eva, G4int * NbLam0_par)
Calculation of particle emission between the saddle and scission point.
Definition at line 7469 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7469 of file G4Abla.cc
References a0, bp, c, dint(), direct(), dmin1(), e2, e3, CEMC_TOWER::emin, EV_TAB_SSC, fiss, G4AblaRandom::flat(), gammaemission, IEV_TAB_SSC, G4Fiss::ifis, itest, lorentz_boost(), G4Opt::nblan0, opt, G4Opt::optimfallowed, pc, sn, G4InuclParticleNames::sp, Acts::VectorHelpers::time(), v2, and x.
Referenced by fissionDistri().
void G4Abla::evapora (G4double zprf, G4double aprf, G4double * ee_par, G4double jprf, G4double * zf_par, G4double * af_par, G4double * mtota_par, G4double * vleva_par, G4double * vxeva_par, G4double * vyeva_par, G4int * ff_par, G4int * fimf_par, G4double * fzimf, G4double * faimf, G4double * tkeimf_par, G4double * jprfout, G4int * inttype_par, G4int * inum_par, G4double EV_TEMP[200][6], G4int * iev_tab_temp_par, G4int * nblam0)
Main evaporation routine.
Definition at line 2568 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 2568 of file G4Abla.cc
References bp, c, dint(), direct(), dmin1(), e, e2, e3, ff, G4AblaRandom::flat(), fmaxhaz(), imf(), itest, lorentz_boost(), min(), G4Opt::nblan0, opt, pc, sn, G4InuclParticleNames::sp, v2, and x.
Referenced by DeexcitationAblaxx(), and fission().
void G4Abla::even_odd (G4double r_origin, G4double r_even_odd, G4int & i_out)
Calculation of even-odd effects in fission.
Definition at line 8884 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 8884 of file G4Abla.cc
Referenced by fissionDistri().
G4double G4Abla::f (G4double E)
*FONCTION INTEGRALE DE FD(E)
Definition at line 5820 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5820 of file G4Abla.cc
Referenced by fmaxhaz_old().
G4double G4Abla::fd (G4double E)
DISTRIBUTION DE MAXWELL
Definition at line 5813 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5813 of file G4Abla.cc
Referenced by fmaxhaz_old().
void G4Abla::FillData (G4int IMULTBU, G4int IEV_TAB)
Fill the data array for INCL
Definition at line 6001 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6001 of file G4Abla.cc
References Ainit, G4VarNtp::avv, BU_TAB, c, eflmac(), G4VarNtp::enerj, EV_TAB, G4VarNtp::itypcasc, nint(), G4VarNtp::ntrack, G4VarNtp::pxlab, G4VarNtp::pylab, G4VarNtp::pzlab, Sinit, G4VarNtp::svv, v2, varntp, Zinit, and G4VarNtp::zvv.
Referenced by DeexcitationAblaxx().
G4double G4Abla::fissility (G4int a, G4int z, G4int ny, G4double sn, G4double slam, G4int optxfis)
Calculation of fissility parameter
Definition at line 2513 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 2513 of file G4Abla.cc
References G, Acts::IntegrationTest::R, and zz.
Referenced by direct(), and spdef().
void G4Abla::fission (G4double AF, G4double ZF, G4double EE, G4double JPRF, G4double * VX1_FISSION, G4double * VY1_FISSION, G4double * VZ1_FISSION, G4double * VX2_FISSION, G4double * VY2_FISSION, G4double * VZ2_FISSION, G4int * ZFP1, G4int * AFP1, G4int * SFP1, G4int * ZFP2, G4int * AFP2, G4int * SFP2, G4int * imode, G4double * VX_EVA_SC, G4double * VY_EVA_SC, G4double * VZ_EVA_SC, G4double EV_TEMP[200][6], G4int * IEV_TAB_FIS, G4int * NbLam0)
Calculation of fission and the particle emission probabilities after fission.
Definition at line 9967 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 9967 of file G4Abla.cc
References EV_TAB_SSC, evapora(), fiss, fissionDistri(), G4AblaRandom::flat(), gammaemission, idnint(), IEV_TAB_SSC, G4Fiss::ifis, G4VarNtp::kfis, lorentz_boost(), opt, G4Opt::optimfallowed, and varntp.
Referenced by DeexcitationAblaxx().
void G4Abla::fission_width (G4double ZPRF, G4double A, G4double EE, G4double BS, G4double BK, G4double EF, G4double Y, G4double * GF, G4double * TEMP, G4double JPR, G4int IEROT, G4int FF_ALLOWED, G4int OPTCOL, G4int OPTSHP, G4double DENSG)
Calculation of fission width at the saddle point according to B&W.
Definition at line 6881 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6881 of file G4Abla.cc
References A(), G4Fiss::dcr, densniv(), fiss, tunnelling(), G4Fiss::ucr, and Y.
Referenced by direct().
void G4Abla::fissionDistri (G4double & a, G4double & z, G4double & e, G4double & a1, G4double & z1, G4double & e1, G4double & v1, G4double & a2, G4double & z2, G4double & e2, G4double & v2, G4double & vx_eva_sc, G4double & vy_eva_sc, G4double & vz_eva_sc, G4int * NbLam0_par)
Calculation of the fission distribution.
Definition at line 7966 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7966 of file G4Abla.cc
References A(), kdfinder::abs(), G4Ecld::beta2, d, dint(), e, ecld, ecoul(), evap_postsaddle(), even_odd(), G4AblaRandom::flat(), frldm(), gausshaz(), idint(), max(), min(), mod(), N, utilabs(), Uwash(), Z, and z1.
Referenced by fission().
G4double G4Abla::fmaxhaz (G4double T)
tirage aleatoire dans une maxwellienne
Definition at line 5826 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5826 of file G4Abla.cc
References G4AblaRandom::flat().
Referenced by evapora().
G4double G4Abla::fmaxhaz_old (G4double T)
tirage aleatoire dans une maxwellienne
Definition at line 5831 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5831 of file G4Abla.cc
References e, f(), fd(), G4AblaRandom::flat(), itest, nint(), x, x1, and y.
void G4Abla::fomega_gs (G4double AF, G4double ZF, G4double * K1, G4double * sOMEGA, G4double * sHOMEGA)
Calculation of omega at ground state.
Definition at line 5325 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5325 of file G4Abla.cc
References C().
Referenced by direct(), func_trans(), and part_fiss().
void G4Abla::fomega_sp (G4double AF, G4double Y, G4double * MFCD, G4double * sOMEGA, G4double * sHOMEGA)
Calculation of omega at saddle point.
Definition at line 5299 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5299 of file G4Abla.cc
References Y.
Referenced by direct(), func_trans(), and tunnelling().
G4double G4Abla::frldm (G4double z, G4double n, G4double beta)
Definition at line 9017 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 9017 of file G4Abla.cc
References a, eflmac_profi(), umass(), and z.
Referenced by fissionDistri().
G4double G4Abla::func_trans (G4double TIME, G4double ZF, G4double AF, G4double BET, G4double Y, G4double FT, G4double T_0)
Definition at line 6511 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6511 of file G4Abla.cc
References G4Fiss::at, G4Ecld::beta2, cram(), ecld, fiss, fomega_gs(), fomega_sp(), Y, and G4Fiss::zt.
Referenced by part_fiss().
G4double G4Abla::fvmaxhaz (G4double T)
Definition at line 6502 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6502 of file G4Abla.cc
References G4AblaRandom::flat().
Referenced by direct().
G4double G4Abla::fvmaxhaz_neut (G4double x)
Definition at line 7028 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7028 of file G4Abla.cc
References G4AblaRandom::flat().
Referenced by direct().
G4double G4Abla::gammln (G4double xx)
LOGARITHM OF THE GAMM FUNCTION
Definition at line 5792 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5792 of file G4Abla.cc
References tmp, x, xx, and y.
Referenced by gcf(), and gser().
G4double G4Abla::gammp (G4double a, G4double x)
Definition at line 5716 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5716 of file G4Abla.cc
References gcf(), and gser().
Referenced by erf().
G4double G4Abla::gausshaz (G4int k, G4double xmoy, G4double sig)
Definition at line 10321 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 10321 of file G4Abla.cc
References fac, G4ThreadLocal, haz(), r, v1, and v2.
Referenced by AMOMENT(), DeexcitationAblaxx(), direct(), and fissionDistri().
void G4Abla::gcf (G4double * gammcf, G4double a, G4double x, G4double gln)
Definition at line 5732 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5732 of file G4Abla.cc
References a, G4InuclParticleNames::an, b, c, d, e, eps, gammln(), and Acts::UnitConstants::h.
Referenced by gammp().
G4double G4Abla::getdeltabinding (G4double a, G4int nblamb)
Separation energies of for other particles for hypernuclei
Definition at line 7781 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7781 of file G4Abla.cc
Referenced by direct().
G4Ec2sub* G4Abla::getFrldmTable () inline
Definition at line 481 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 481 of file G4Abla.hh
References ec2sub.
G4double G4Abla::gethyperbinding (G4double A, G4double Z, G4int ny)
Definition at line 7822 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7822 of file G4Abla.cc
References c, D(), k, mod(), my, N, and Z.
Referenced by direct(), and gethyperseparation().
G4double G4Abla::gethyperseparation (G4double A, G4double Z, G4int ny)
Separation energies of lambda
Definition at line 7787 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7787 of file G4Abla.cc
References gethyperbinding().
Referenced by direct().
G4Volant* G4Abla::getVolant () inline
Get the internal output data structure pointer.
Definition at line 89 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 89 of file G4Abla.hh
References volant.
void G4Abla::gser (G4double * gamser, G4double a, G4double x, G4double gln)
Definition at line 5764 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5764 of file G4Abla.cc
References a, G4InuclParticleNames::ap, e, eps, gammln(), n, and sum.
Referenced by gammp().
void G4Abla::guet (G4double * x_par, G4double * z_par, G4double * find_par)
Definition at line 5930 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5930 of file G4Abla.cc
References c1, c2, x, xx, z, and zz.
Referenced by pace2().
G4double G4Abla::haz (G4int k)
Definition at line 10178 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 10178 of file G4Abla.cc
References G4AblaRandom::flat(), G4ThreadLocal, mod(), secnds(), x, and y.
Referenced by gausshaz(), imf(), and tke_bu().
G4int G4Abla::idint (G4double a)
Definition at line 6231 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6231 of file G4Abla.cc
Referenced by bipol(), fissionDistri(), and pace2().
G4int G4Abla::idnint (G4double value)
Definition at line 6242 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6242 of file G4Abla.cc
Referenced by bsbkbc(), DeexcitationAblaxx(), densniv(), direct(), fission(), imf(), lorb(), mglms(), parite(), qrot(), spdef(), tunnelling(), unstable_tke(), and width().
void G4Abla::imf (G4double ACN, G4double ZCN, G4double TEMP, G4double EE, G4double * ZIMF, G4double * AIMF, G4double * BIMF, G4double * SBIMF, G4double * TIMF, G4double JPRF)
Calculation of imfs.
Definition at line 7033 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7033 of file G4Abla.cc
References barrs(), G4Ecld::beta2, bsbkbc(), densniv(), G4Ecld::ecgnz, ecld, haz(), idnint(), in, isostab_lim(), max(), mglms(), min(), opt, G4Opt::optshpimf, G4Ecld::vgsld, width(), and X.
Referenced by evapora().
void G4Abla::initEvapora ()
Initialize ABLA evaporation code.
Definition at line 2135 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 2135 of file G4Abla.cc
References a, G4Ecld::alpha, G4Ecld::beta2, G4Ecld::beta4, G4Mexp::bind, G4Pace::dm, ec2sub, G4Ecld::ecfnz, G4Ecld::ecgnz, ecld, G4Ec2sub::ecnz, eflmac(), G4AblaVirtualData::getAlpha(), G4AblaVirtualData::getBeta2(), G4AblaVirtualData::getBeta4(), G4AblaVirtualData::getEcnz(), G4AblaVirtualData::getMexp(), G4AblaVirtualData::getMexpID(), G4AblaVirtualData::getPace2(), G4AblaVirtualData::getRms(), G4AblaVirtualData::getVgsld(), masses, max(), G4Mexp::mexpiop, mod(), n, pace, parite(), G4AblaDataFile::readData(), G4Ecld::rms, verboseLevel, G4Ecld::vgsld, and z.
Referenced by G4AblaInterface::G4AblaInterface().
G4int G4Abla::IPOWERLIMHAZ (G4double lambda, G4int xmin, G4int xmax)
Random generator according to the powerfunction y = x**(lambda) in the range from xmin to xmax
Definition at line 10213 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 10213 of file G4Abla.cc
References G4AblaRandom::flat(), nint(), and y.
Referenced by DeexcitationAblaxx().
G4int G4Abla::ISIGN (G4int a, G4int b)
Definition at line 6146 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6146 of file G4Abla.cc
References kdfinder::abs().
Referenced by DeexcitationAblaxx().
void G4Abla::isostab_lim (G4int z, G4int * nmin, G4int * nmax)
Limits of existing nuclei
Definition at line 7345 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7345 of file G4Abla.cc
Referenced by DeexcitationAblaxx(), direct(), imf(), and unstable_nuclei().
void G4Abla::lorb (G4double AMOTHER, G4double ADAUGHTER, G4double LMOTHER, G4double EEFINAL, G4double * LORBITAL, G4double * SIGMA_LORBITAL)
Calculation of mean value of orbital angular momentum.
Definition at line 6989 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6989 of file G4Abla.cc
References idnint().
Referenced by direct().
void G4Abla::lorentz_boost (G4double VXRIN, G4double VYRIN, G4double VZRIN, G4double VXIN, G4double VYIN, G4double VZIN, G4double * VXOUT, G4double * VYOUT, G4double * VZOUT)
Calculation of lorentz's boost
Definition at line 9920 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 9920 of file G4Abla.cc
References C(), and e.
Referenced by DeexcitationAblaxx(), evap_postsaddle(), evapora(), fission(), and unstable_tke().
void G4Abla::lpoly (G4double x, G4int n, G4double pl[])
This subroutine calculates the ordinary legendre polynomials of order 0 to n-1 of argument x and stores them in the vector pl. They are calculated by recursion relation from the first two polynomials. Written by A.J.Sierk LANL t-9 February, 1984
Definition at line 4974 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 4974 of file G4Abla.cc
References n, and x.
Referenced by barfit().
G4int G4Abla::max (G4int a, G4int b)
Definition at line 6124 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6124 of file G4Abla.cc
References a, and b.
Referenced by DeexcitationAblaxx(), densniv(), direct(), fissionDistri(), imf(), and initEvapora().
G4double G4Abla::max (G4double a, G4double b)
Definition at line 6114 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6114 of file G4Abla.cc
References a, and b.
void G4Abla::mglms (G4double a, G4double z, G4int refopt4, G4double * el)
Mglms
Definition at line 2416 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 2416 of file G4Abla.cc
References ec2sub, G4Ec2sub::ecnz, eflmac(), idnint(), n1, and z1.
Referenced by direct(), imf(), and unstable_tke().
void G4Abla::mglw (G4double a, G4double z, G4double * el)
Model de la goutte liquide de c. f. weizsacker. usually an obsolete option
Definition at line 2389 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 2389 of file G4Abla.cc
References a.
Referenced by direct().
G4int G4Abla::min (G4int a, G4int b)
Definition at line 6104 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6104 of file G4Abla.cc
References a, and b.
Referenced by direct(), evapora(), fissionDistri(), and imf().
G4double G4Abla::min (G4double a, G4double b)
Definition at line 6094 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6094 of file G4Abla.cc
References a, and b.
G4int G4Abla::mod (G4int a, G4int b)
Definition at line 6202 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6202 of file G4Abla.cc
References b.
Referenced by direct(), eflmac(), fissionDistri(), genevent(), gethyperbinding(), grun(), haz(), initEvapora(), isdiquark(), ishadron(), klu(), luchge(), lucomp(), ludecy(), luedit(), luexec(), luhepc(), luindf(), lukfdi(), lulist(), luname(), luprep(), lushow(), lustrf(), lutabu(), lutest(), lux3jt(), luxkfl(), luxtot(), luzdis(), pyadsh(), pycjdc(), pycomp(), pycttr(), pydecy(), pydiff(), pydisg(), pydump(), pyedit(), pyeig4(), pyevnt(), pyevnw(), pyevol(), pyexec(), pyfscr(), pyggam(), pyhepc(), pyhext(), pyhidiff(), pyhiinit(), pyhimaxi(), pyhimult(), pyhirand(), pyhiremn(), pyhiresd(), pyhiscat(), pyhisigh(), pyhispli(), pyhisspa(), pyhithia(), pyhiwidt(), pyindf(), pyinit(), pyjurf(), pyk(), pykfdi(), pylist(), pymass(), pymaxi(), pymign(), pymihg(), pymihk(), pymirm(), pymult(), pynjdc(), pynmes(), pypdel(), pypdfu(), pyplot(), pyprep(), pyptfs(), pyptis(), pyptmi(), pyr(), pyrand(), pyreco(), pyremn(), pyresd(), pyrvch(), pyrvgl(), pyrvne(), pyscat(), pysfdc(), pysgex(), pysghf(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pyshow(), pysigh(), pyslha(), pyspli(), pysspa(), pystat(), pystrf(), pytabu(), pytbdy(), pytest(), pythia(), pytime(), pytune(), pyupev(), pywidt(), pywidx(), pyx3jt(), pyxkfl(), pyxtee(), pyzdis(), rlu(), tunnelling(), uglast(), ulmass(), vegas(), and width().
G4int G4Abla::nint (G4double number)
Definition at line 6158 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6158 of file G4Abla.cc
Referenced by FillData(), fmaxhaz_old(), hijing(), IPOWERLIMHAZ(), luboei(), pyboei(), pydump(), pyfact(), pyfill(), pyfscr(), pyhist(), pynull(), pyoper(), pypile(), pyplot(), pyrvsf(), pysugi(), and pytbbn().
G4Abla& G4Abla::operator= (G4Abla const & other)
Dummy assignment operator.
G4double G4Abla::pace2 (G4double a, G4double z)
Definition at line 5892 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5892 of file G4Abla.cc
References G4Pace::dm, guet(), idint(), and pace.
void G4Abla::parite (G4double n, G4double * par)
PROCEDURE FOR CALCULATING THE PARITY OF THE NUMBER N. RETURNS -1 IF N IS ODD AND +1 IF N IS EVEN
Definition at line 5174 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5174 of file G4Abla.cc
References dint(), idnint(), and n1.
Referenced by appariem(), densniv(), eflmac(), and initEvapora().
void G4Abla::part_fiss (G4double BET, G4double GP, G4double GF, G4double Y, G4double TAUF, G4double TS1, G4double TSUM, G4int * CHOICE, G4double ZF, G4double AF, G4double FT, G4double * T_LAPSE, G4double * GF_LOC)
Calculation of the fission probability modified by transient time effects.
Definition at line 6608 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6608 of file G4Abla.cc
References G4AblaRandom::flat(), fomega_gs(), func_trans(), and X.
Referenced by direct().
G4double G4Abla::pen (G4double A, G4double ap, G4double omega, G4double T)
Calculation of penetration factors for light charged particles.
Definition at line 6456 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6456 of file G4Abla.cc
References G4InuclParticleNames::ap, and e.
Referenced by direct().
void G4Abla::qrot (G4double z, G4double a, G4double bet, G4double sig, G4double u, G4double * qr)
Coefficient of collective enhancement including damping Input: z,a,bet,sig,u Output: qr - collective enhancement factor See junghans et al., nucl. phys. a 629 (1998) 635
Parameters
z charge number
a mass number
bet beta deformation
sig perpendicular spin cut-off factor
u Energy
Returns
Coefficient of collective enhancement
Definition at line 4895 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 4895 of file G4Abla.cc
References kdfinder::abs(), G4Fiss::dcr, dz, fiss, idnint(), n, G4Fiss::ucr, and z.
Referenced by densniv().
G4int G4Abla::secnds (G4int x)
Definition at line 6186 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6186 of file G4Abla.cc
References Acts::VectorHelpers::time(), and G4InuclParticleNames::tm.
Referenced by haz().
void G4Abla::SetParameters ()
Initialize ABLA parameters.
Definition at line 2322 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 2322 of file G4Abla.cc
References G4Ald::ak, ald, G4Ald::as, G4Ald::av, G4Fiss::bet, G4Fiss::dcr, fiss, G4Fiss::ifis, opt, G4Ald::optafan, G4Opt::optcha, G4Fiss::optcol, G4Fiss::optct, G4Opt::optemd, G4Opt::optimfallowed, G4Fiss::optshp, G4Opt::optshpimf, G4Fiss::optxfis, T_freeze_out_in, G4Fiss::ucr, and G4Fiss::zt.
Referenced by G4AblaInterface::G4AblaInterface().
void G4Abla::SetParametersG4 (G4int z, G4int a)
Definition at line 2302 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 2302 of file G4Abla.cc
References a, G4Fiss::at, fiss, opt, G4Fiss::optcol, G4Fiss::optshp, G4Opt::optshpimf, z, and G4Fiss::zt.
Referenced by DeexcitationAblaxx().
void G4Abla::setVerboseLevel (G4int level)
Set verbosity level.
Definition at line 77 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 77 of file G4Abla.cc
References verboseLevel.
G4double G4Abla::spdef (G4int a, G4int z, G4int optxfis)
Definition at line 2471 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 2471 of file G4Abla.cc
References dx, fissility(), idnint(), v, and x.
void G4Abla::standardRandom (G4double * rndm, G4long * seed)
Random numbers.
G4double G4Abla::tau (G4double bet, G4double homega, G4double ef, G4double t)
RISE TIME IN WHICH THE FISSION WIDTH HAS REACHED 90 PERCENT OF ITS FINAL VALUE
Definition at line 5199 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 5199 of file G4Abla.cc
References e.
Referenced by airy2(), airy2d(), direct(), getdeltat(), getneff(), getscatterer(), gettemp(), pyhiklim(), pyhikmap(), pyhimaxi(), pyhimult(), pyhisigh(), pykcut(), pyklim(), pykmap(), pymaxi(), pymign(), pymult(), pyptmi(), and pysigh().
void G4Abla::tke_bu (G4double Z, G4double A, G4double ZALL, G4double AAL, G4double * VX, G4double * VY, G4double * VZ)
Calculation of tke for breakup fragments
Definition at line 10148 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 10148 of file G4Abla.cc
References A(), haz(), and Acts::IntegrationTest::R.
Referenced by DeexcitationAblaxx().
G4double G4Abla::tunnelling (G4double A, G4double ZPRF, G4double Y, G4double EE, G4double EF, G4double TEMP, G4double DENSG, G4double DENSF, G4double ENH_FACT)
Calculation of tunnelling effect in fission.
Definition at line 6811 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6811 of file G4Abla.cc
References fomega_sp(), idnint(), and mod().
Referenced by fission_width().
double G4Abla::umass (G4double z, G4double n, G4double beta)
Functions for the fission model.
Definition at line 8944 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 8944 of file G4Abla.cc
References a, alpha, pi, and z.
Referenced by frldm().
void G4Abla::unbound (G4double SN, G4double SP, G4double SD, G4double ST, G4double SHE, G4double SA, G4double BP, G4double BD, G4double BT, G4double BHE, G4double BA, G4double * PROBF, G4double * PROBN, G4double * PROBP, G4double * PROBD, G4double * PROBT, G4double * PROBHE, G4double * PROBA, G4double * PROBIMF, G4double * PROBG, G4double * ECN, G4double * ECP, G4double * ECD, G4double * ECT, G4double * ECHE, G4double * ECA)
Calculation of unbound nuclei.
Definition at line 7846 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 7846 of file G4Abla.cc
References dmin1(), and e.
Referenced by direct().
void G4Abla::unstable_nuclei (G4int AFP, G4int ZFP, G4int * AFPNEW, G4int * ZFPNEW, G4int & IOUNSTABLE, G4double VX, G4double VY, G4double VZ, G4double * VP1X, G4double * VP1Y, G4double * VP1Z, G4double BU_TAB_TEMP[200][6], G4int * ILOOP)
Calculation of unstable nuclei
Definition at line 9156 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 9156 of file G4Abla.cc
References I, isostab_lim(), and unstable_tke().
Referenced by DeexcitationAblaxx().
void G4Abla::unstable_tke (G4double AIN, G4double ZIN, G4double ANEW, G4double ZNEW, G4double VXIN, G4double VYIN, G4double VZIN, G4double * V1X, G4double * V1Y, G4double * V1Z, G4double * V2X, G4double * V2Y, G4double * V2Z)
Calculation of unstable nuclei tke
Definition at line 9842 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 9842 of file G4Abla.cc
References C(), G4AblaRandom::flat(), idnint(), lorentz_boost(), masses, G4Mexp::massexp, and mglms().
Referenced by unstable_nuclei().
G4double G4Abla::utilabs (G4double a)
Definition at line 6264 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6264 of file G4Abla.cc
References kdfinder::abs().
Referenced by eflmac_profi(), and fissionDistri().
G4double G4Abla::Uwash (G4double E, G4double Ecrit, G4double Freduction, G4double gamma)
Definition at line 9002 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 9002 of file G4Abla.cc
Referenced by fissionDistri().
G4double G4Abla::width (G4double AMOTHER, G4double ZMOTHER, G4double APART, G4double ZPART, G4double TEMP, G4double B1, G4double SB1, G4double EXC)
Calculation of decay widths for light particles.
Definition at line 6270 of file G4Abla.cc.
View newest version in sPHENIX GitHub at line 6270 of file G4Abla.cc
References kdfinder::abs(), B(), C(), C2, e, erf(), G, idnint(), and mod().
Referenced by direct(), and imf().
Member Data Documentation
G4int G4Abla::Ainit private
Definition at line 504 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 504 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), and FillData().
G4Ald* G4Abla::ald private
Definition at line 494 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 494 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), densniv(), direct(), SetParameters(), and ~G4Abla().
G4double G4Abla::BU_TAB[200][12] private
Definition at line 490 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 490 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), and FillData().
G4Ec2sub* G4Abla::ec2sub private
Definition at line 496 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 496 of file G4Abla.hh
Referenced by getFrldmTable(), initEvapora(), mglms(), and ~G4Abla().
G4Ecld* G4Abla::ecld private
Definition at line 497 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 497 of file G4Abla.hh
Referenced by barrs(), bsbkbc(), densniv(), direct(), fissionDistri(), func_trans(), imf(), initEvapora(), and ~G4Abla().
G4Eenuc* G4Abla::eenuc private
Definition at line 495 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 495 of file G4Abla.hh
Referenced by ~G4Abla().
G4double G4Abla::EV_TAB[200][6] private
Definition at line 490 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 490 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), and FillData().
G4double G4Abla::EV_TAB_SSC[200][6] private
Definition at line 490 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 490 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), evap_postsaddle(), and fission().
G4Fb* G4Abla::fb private
Definition at line 499 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 499 of file G4Abla.hh
Referenced by direct(), and ~G4Abla().
G4Fiss* G4Abla::fiss private
Definition at line 500 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 500 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), densniv(), direct(), evap_postsaddle(), fission(), fission_width(), func_trans(), qrot(), SetParameters(), SetParametersG4(), and ~G4Abla().
G4int G4Abla::gammaemission private
Definition at line 491 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 491 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), direct(), evap_postsaddle(), and fission().
G4int G4Abla::IEV_TAB_SSC private
Definition at line 489 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 489 of file G4Abla.hh
Referenced by evap_postsaddle(), and fission().
G4int G4Abla::ilast private
Definition at line 487 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 487 of file G4Abla.hh
Referenced by direct().
G4Mexp* G4Abla::masses private
Definition at line 498 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 498 of file G4Abla.hh
Referenced by eflmac(), initEvapora(), unstable_tke(), and ~G4Abla().
G4Opt* G4Abla::opt private
Definition at line 501 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 501 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), direct(), evap_postsaddle(), evapora(), fission(), imf(), SetParameters(), SetParametersG4(), and ~G4Abla().
G4Pace* G4Abla::pace private
Definition at line 493 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 493 of file G4Abla.hh
Referenced by initEvapora(), pace2(), and ~G4Abla().
G4int G4Abla::Sinit private
Definition at line 504 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 504 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), and FillData().
G4double G4Abla::T_freeze_out private
Definition at line 492 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 492 of file G4Abla.hh
Referenced by AMOMENT(), and DeexcitationAblaxx().
G4double G4Abla::T_freeze_out_in private
Definition at line 488 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 488 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), and SetParameters().
G4VarNtp* G4Abla::varntp private
Definition at line 503 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 503 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), FillData(), and fission().
G4int G4Abla::verboseLevel private
Definition at line 486 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 486 of file G4Abla.hh
Referenced by bipol(), initEvapora(), and setVerboseLevel().
G4Volant* G4Abla::volant private
Definition at line 502 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 502 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), and getVolant().
G4int G4Abla::Zinit private
Definition at line 504 of file G4Abla.hh.
View newest version in sPHENIX GitHub at line 504 of file G4Abla.hh
Referenced by DeexcitationAblaxx(), and FillData().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/include/G4Abla.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/abla/src/G4Abla.cc