ECCE @ EIC Software: acts/blob/master/Examples/Scripts/MaterialMaping/materialPlotHelper.cpp File Reference
materialPlotHelper.cpp File Reference
#include "materialPlotHelper.hpp"
#include <iomanip>
#include <ostream>
#include <string>
#include "../../external/acts-core/thirdparty/nlohmann_json/single_include/nlohmann/json.hpp"
Classes
struct sinfo
Information on a given surface.
Typedefs
using json = nlohmann::json
Functions
void Parse_Json (const json &Det, std::map< std::string, std::string > &surface_name)
Parse the surface map json file to associate the surface name to each id.
void Initialise_info (sinfo &surface_info, const std::map< std::string, std::string > &surface_name, const uint64_t &id, const int &type, const float &pos, const float &range_min, const float &range_max)
Initialise the information on each surface.
Typedef Documentation
using json = nlohmann::json
Definition at line 17 of file materialPlotHelper.cpp.
View newest version in sPHENIX GitHub at line 17 of file materialPlotHelper.cpp
Function Documentation
void Initialise_info (sinfo & surface_info, const std::map< std::string, std::string > & surface_name, const uint64_t & id, const int & type, const float & pos, const float & range_min, const float & range_max)
Initialise the information on each surface.
Definition at line 89 of file materialPlotHelper.cpp.
View newest version in sPHENIX GitHub at line 89 of file materialPlotHelper.cpp
References sinfo::id, sinfo::idname, sinfo::name, sinfo::pos, pos(), sinfo::range_max, sinfo::range_min, and sinfo::type.
Referenced by Fill().
void Parse_Json (const json & Det, std::map< std::string, std::string > & surface_name)
Parse the surface map json file to associate the surface name to each id.
Definition at line 42 of file materialPlotHelper.cpp.
View newest version in sPHENIX GitHub at line 42 of file materialPlotHelper.cpp
References nlohmann::basic_json::items().
Referenced by Fill().