ECCE @ EIC Software: IORTPhysicsList Class Reference
IORTPhysicsList Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/include/IORTPhysicsList.hh>
Public Member Functions
IORTPhysicsList ()
virtual ~IORTPhysicsList ()
void ConstructParticle ()
void SetCuts ()
void SetCutForGamma (G4double)
void SetCutForElectron (G4double)
void SetCutForPositron (G4double)
void SetDetectorCut (G4double cut)
void AddPhysicsList (const G4String &name)
void ConstructProcess ()
void AddStepMax ()
IORTStepMax * GetStepMaxProcess ()
void AddPackage (const G4String &name)
Public Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList ()
virtual ~G4VModularPhysicsList ()
void RegisterPhysics (G4VPhysicsConstructor *)
const G4VPhysicsConstructor * GetPhysics (G4int index) const
const G4VPhysicsConstructor * GetPhysics (const G4String &name) const
const G4VPhysicsConstructor * GetPhysicsWithType (G4int physics_type) const
void ReplacePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4VPhysicsConstructor *)
void RemovePhysics (G4int type)
void RemovePhysics (const G4String &name)
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
G4int GetInstanceID () const
virtual void TerminateWorker () override
Public Member Functions inherited from G4VUserPhysicsList
G4VUserPhysicsList ()
virtual ~G4VUserPhysicsList ()
G4VUserPhysicsList (const G4VUserPhysicsList &)
G4VUserPhysicsList & operator= (const G4VUserPhysicsList &)
void Construct ()
void UseCoupledTransportation (G4bool vl=true)
void SetDefaultCutValue (G4double newCutValue)
G4double GetDefaultCutValue () const
void BuildPhysicsTable ()
void PreparePhysicsTable (G4ParticleDefinition *)
void BuildPhysicsTable (G4ParticleDefinition *)
G4bool StorePhysicsTable (const G4String &directory=".")
G4bool IsPhysicsTableRetrieved () const
G4bool IsStoredInAscii () const
const G4String & GetPhysicsTableDirectory () const
void SetPhysicsTableRetrieved (const G4String &directory="")
void SetStoredInAscii ()
void ResetPhysicsTableRetrieved ()
void ResetStoredInAscii ()
void DumpList () const
void DumpCutValuesTable (G4int flag=1)
void DumpCutValuesTableIfRequested ()
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
void SetCutsWithDefault ()
void SetCutValue (G4double aCut, const G4String &pname)
G4double GetCutValue (const G4String &pname) const
void SetCutValue (G4double aCut, const G4String &pname, const G4String &rname)
void SetParticleCuts (G4double cut, G4ParticleDefinition *particle, G4Region *region=0)
void SetParticleCuts (G4double cut, const G4String &particleName, G4Region *region=0)
void SetCutsForRegion (G4double aCut, const G4String &rname)
void ResetCuts ()
void SetApplyCuts (G4bool value, const G4String &name)
G4bool GetApplyCuts (const G4String &name) const
void RemoveProcessManager ()
void AddProcessManager (G4ParticleDefinition *newParticle, G4ProcessManager *newManager=0)
void CheckParticleList ()
void DisableCheckParticleList ()
G4int GetInstanceID () const
virtual void InitializeWorker ()
Private Attributes
G4EmConfigurator em_config
G4double cutForGamma
G4double cutForElectron
G4double cutForPositron
G4String emName
G4VPhysicsConstructor * emPhysicsList
G4VPhysicsConstructor * decPhysicsList
IORTStepMax * stepMaxProcess
IORTPhysicsListMessenger * pMessenger
Additional Inherited Members
Static Public Member Functions inherited from G4VModularPhysicsList
static const G4VMPLManager & GetSubInstanceManager ()
Protected Types inherited from G4VModularPhysicsList
typedef
G4VMPLData::G4PhysConstVectorData G4PhysConstVector
Protected Member Functions inherited from G4VModularPhysicsList
G4VModularPhysicsList (const G4VModularPhysicsList &)
G4VModularPhysicsList & operator= (const G4VModularPhysicsList &)
Protected Attributes inherited from G4VModularPhysicsList
G4int verboseLevel
G4int g4vmplInstanceID
Static Protected Attributes inherited from G4VModularPhysicsList
static G4RUN_DLL G4VMPLManager G4VMPLsubInstanceManager
Detailed Description
Definition at line 51 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 51 of file IORTPhysicsList.hh
Constructor & Destructor Documentation
IORTPhysicsList::IORTPhysicsList ()
Definition at line 68 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 68 of file IORTPhysicsList.cc
References cutForElectron, cutForGamma, cutForPositron, decPhysicsList, G4VUserPhysicsList::defaultCutValue, emName, emPhysicsList, mm, pMessenger, G4VModularPhysicsList::SetVerboseLevel(), and stepMaxProcess.
IORTPhysicsList::~IORTPhysicsList () virtual
Definition at line 87 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 87 of file IORTPhysicsList.cc
References decPhysicsList, emPhysicsList, and pMessenger.
Member Function Documentation
void IORTPhysicsList::AddPackage (const G4String & name)
void IORTPhysicsList::AddPhysicsList (const G4String & name)
Definition at line 113 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 113 of file IORTPhysicsList.cc
References emName, emPhysicsList, G4cout, G4endl, G4RunManager::GetRunManager(), and G4VModularPhysicsList::verboseLevel.
Referenced by IORTPhysicsListMessenger::SetNewValue().
void IORTPhysicsList::AddStepMax ()
Definition at line 159 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 159 of file IORTPhysicsList.cc
References G4ProcessManager::AddDiscreteProcess(), G4VUserPhysicsList::GetParticleIterator(), G4ParticleDefinition::GetProcessManager(), IORTStepMax::IsApplicable(), particle, and stepMaxProcess.
Referenced by ConstructProcess().
void IORTPhysicsList::ConstructParticle (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 94 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 94 of file IORTPhysicsList.cc
References G4VPhysicsConstructor::ConstructParticle(), and decPhysicsList.
void IORTPhysicsList::ConstructProcess (void) virtual
Reimplemented from G4VModularPhysicsList.
Definition at line 99 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 99 of file IORTPhysicsList.cc
References G4EmConfigurator::AddModels(), AddStepMax(), G4VUserPhysicsList::AddTransportation(), G4VPhysicsConstructor::ConstructProcess(), em_config, and emPhysicsList.
IORTStepMax* IORTPhysicsList::GetStepMaxProcess () inline
Definition at line 69 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 69 of file IORTPhysicsList.hh
References stepMaxProcess.
void IORTPhysicsList::SetCutForElectron (G4double cut)
Definition at line 202 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 202 of file IORTPhysicsList.cc
References cutForElectron, G4Electron::Electron(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by IORTPhysicsListMessenger::SetNewValue().
void IORTPhysicsList::SetCutForGamma (G4double cut)
Definition at line 196 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 196 of file IORTPhysicsList.cc
References cutForGamma, G4Gamma::Gamma(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by IORTPhysicsListMessenger::SetNewValue().
void IORTPhysicsList::SetCutForPositron (G4double cut)
Definition at line 208 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 208 of file IORTPhysicsList.cc
References cutForPositron, G4Positron::Positron(), and G4VUserPhysicsList::SetParticleCuts().
Referenced by IORTPhysicsListMessenger::SetNewValue().
void IORTPhysicsList::SetCuts () virtual
Reimplemented from G4VUserPhysicsList.
Definition at line 177 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 177 of file IORTPhysicsList.cc
References cutForElectron, cutForGamma, cutForPositron, G4VUserPhysicsList::defaultCutValue, G4VUserPhysicsList::DumpCutValuesTable(), G4BestUnit, G4cout, G4endl, G4VUserPhysicsList::SetCutValue(), SetDetectorCut(), and G4VModularPhysicsList::verboseLevel.
void IORTPhysicsList::SetDetectorCut (G4double cut)
Definition at line 214 of file IORTPhysicsList.cc.
View newest version in sPHENIX GitHub at line 214 of file IORTPhysicsList.cc
References G4ProductionCuts::GetIndex(), G4RegionStore::GetInstance(), and G4RegionStore::GetRegion().
Referenced by SetCuts().
Member Data Documentation
G4double IORTPhysicsList::cutForElectron private
Definition at line 77 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 77 of file IORTPhysicsList.hh
Referenced by IORTPhysicsList(), SetCutForElectron(), and SetCuts().
G4double IORTPhysicsList::cutForGamma private
Definition at line 76 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 76 of file IORTPhysicsList.hh
Referenced by IORTPhysicsList(), SetCutForGamma(), and SetCuts().
G4double IORTPhysicsList::cutForPositron private
Definition at line 78 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 78 of file IORTPhysicsList.hh
Referenced by IORTPhysicsList(), SetCutForPositron(), and SetCuts().
G4VPhysicsConstructor* IORTPhysicsList::decPhysicsList private
Definition at line 82 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 82 of file IORTPhysicsList.hh
Referenced by ConstructParticle(), IORTPhysicsList(), and ~IORTPhysicsList().
G4EmConfigurator IORTPhysicsList::em_config private
Definition at line 74 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 74 of file IORTPhysicsList.hh
Referenced by ConstructProcess().
G4String IORTPhysicsList::emName private
Definition at line 80 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 80 of file IORTPhysicsList.hh
Referenced by AddPhysicsList(), and IORTPhysicsList().
G4VPhysicsConstructor* IORTPhysicsList::emPhysicsList private
Definition at line 81 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 81 of file IORTPhysicsList.hh
Referenced by AddPhysicsList(), ConstructProcess(), IORTPhysicsList(), and ~IORTPhysicsList().
IORTPhysicsListMessenger* IORTPhysicsList::pMessenger private
Definition at line 85 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 85 of file IORTPhysicsList.hh
Referenced by IORTPhysicsList(), and ~IORTPhysicsList().
IORTStepMax* IORTPhysicsList::stepMaxProcess private
Definition at line 83 of file IORTPhysicsList.hh.
View newest version in sPHENIX GitHub at line 83 of file IORTPhysicsList.hh
Referenced by AddStepMax(), GetStepMaxProcess(), and IORTPhysicsList().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/include/IORTPhysicsList.hh
geant4/tree/geant4-10.6-release/examples/advanced/iort_therapy/src/IORTPhysicsList.cc