ECCE @ EIC Software: G4INCL::NSToNLChannel Class Reference
G4INCL::NSToNLChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNSToNLChannel.hh>
Public Member Functions
NSToNLChannel (Particle *, Particle *)
virtual ~NSToNLChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
INCL_DECLARE_ALLOCATION_POOL (NSToNLChannel)
Private Attributes
Particle * particle1
Particle * particle2
Detailed Description
Definition at line 47 of file G4INCLNSToNLChannel.hh.
View newest version in sPHENIX GitHub at line 47 of file G4INCLNSToNLChannel.hh
Constructor & Destructor Documentation
G4INCL::NSToNLChannel::NSToNLChannel (Particle * p1, Particle * p2)
Definition at line 49 of file G4INCLNSToNLChannel.cc.
View newest version in sPHENIX GitHub at line 49 of file G4INCLNSToNLChannel.cc
G4INCL::NSToNLChannel::~NSToNLChannel () virtual
Definition at line 53 of file G4INCLNSToNLChannel.cc.
View newest version in sPHENIX GitHub at line 53 of file G4INCLNSToNLChannel.cc
Member Function Documentation
void G4INCL::NSToNLChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 55 of file G4INCLNSToNLChannel.cc.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNSToNLChannel.cc
References G4INCL::FinalState::addModifiedParticle(), G4INCL::ParticleTable::getIsospin(), G4INCL::Particle::getMass(), G4INCL::ParticleTable::getNucleonType(), G4INCL::Particle::getType(), G4INCL::Particle::isNucleon(), G4INCL::Lambda, my, G4INCL::Random::normVector(), G4InuclParticleNames::nucleon(), particle1, particle2, G4INCL::Particle::setEnergy(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setType(), and G4INCL::KinematicsUtils::totalEnergyInCM().
G4INCL::NSToNLChannel::INCL_DECLARE_ALLOCATION_POOL (NSToNLChannel) private
Member Data Documentation
Particle* G4INCL::NSToNLChannel::particle1 private
Definition at line 55 of file G4INCLNSToNLChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNSToNLChannel.hh
Referenced by fillFinalState().
Particle * G4INCL::NSToNLChannel::particle2 private
Definition at line 55 of file G4INCLNSToNLChannel.hh.
View newest version in sPHENIX GitHub at line 55 of file G4INCLNSToNLChannel.hh
Referenced by fillFinalState().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLNSToNLChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLNSToNLChannel.cc