ECCE @ EIC Software: geant4/tree/geant4-10.6-release/source/g3tog4/src/G4gsmate.cc File Reference
G4gsmate.cc File Reference
#include <cmath>
#include "G4PhysicalConstants.hh"
#include "G4SystemOfUnits.hh"
#include "G3toG4.hh"
#include "G3MatTable.hh"
#include "G3EleTable.hh"
#include "G4Material.hh"
#include "G4Isotope.hh"
#include "G4UnitsTable.hh"
Functions
void PG4gsmate (G4String *tokens)
void G4gsmate (G4int imate, G4String name, G4double ain, G4double zin, G4double densin, G4double, G4int, G4double *)
Function Documentation
void G4gsmate (G4int imate, G4String name, G4double ain, G4double zin, G4double densin, G4double , G4int , G4double *)
Definition at line 104 of file G4gsmate.cc.
View newest version in sPHENIX GitHub at line 104 of file G4gsmate.cc
References a, G4Material::AddElement(), G4String::both, cm3, Acts::UnitConstants::g, G3Ele, G3Mat, G4gsmixt(), G3EleTable::GetEle(), kelvin, kStateGas, material(), mole, n, pascal, G3MatTable::put(), G4String::strip(), source.hepunit::universe_mean_density, z, and zz.
Referenced by PG4gsmate().
void PG4gsmate (G4String * tokens)
Definition at line 41 of file G4gsmate.cc.
View newest version in sPHENIX GitHub at line 41 of file G4gsmate.cc
References a, G3fillParams(), G4gsmate(), Ipar, PTgsmate, Rpar, Spar, and z.
Referenced by G3CLEval().