ECCE @ EIC Software: G4StatMF Class Reference
G4StatMF Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMF.hh>
Public Member Functions
G4StatMF ()
~G4StatMF ()
G4FragmentVector * BreakItUp (const G4Fragment &theNucleus)
Public Member Functions inherited from G4VMultiFragmentation
G4VMultiFragmentation ()
virtual ~G4VMultiFragmentation ()
Private Member Functions
G4StatMF (const G4StatMF &right)
G4StatMF & operator= (const G4StatMF &right)
G4bool operator== (const G4StatMF &right)
G4bool operator!= (const G4StatMF &right)
G4bool FindTemperatureOfBreakingChannel (const G4Fragment &theFragment, const G4StatMFChannel *aChannel, G4double &Temperature)
G4double CalcEnergy (G4int A, G4int Z, const G4StatMFChannel *aChannel, G4double T)
Private Attributes
G4VStatMFEnsemble * _theEnsemble
Detailed Description
Definition at line 46 of file G4StatMF.hh.
View newest version in sPHENIX GitHub at line 46 of file G4StatMF.hh
Constructor & Destructor Documentation
G4StatMF::G4StatMF ()
Definition at line 37 of file G4StatMF.cc.
View newest version in sPHENIX GitHub at line 37 of file G4StatMF.cc
G4StatMF::~G4StatMF ()
Definition at line 41 of file G4StatMF.cc.
View newest version in sPHENIX GitHub at line 41 of file G4StatMF.cc
G4StatMF::G4StatMF (const G4StatMF & right) private
Member Function Documentation
G4FragmentVector * G4StatMF::BreakItUp (const G4Fragment & theNucleus) virtual
Implements G4VMultiFragmentation.
Definition at line 44 of file G4StatMF.cc.
View newest version in sPHENIX GitHub at line 44 of file G4StatMF.cc
References _theEnsemble, kdfinder::abs(), CLHEP::HepLorentzVector::boost(), CLHEP::HepLorentzVector::boostVector(), G4StatMFChannel::CheckFragments(), G4StatMFMacroCanonical::ChooseAandZ(), e, CLHEP::HepLorentzVector::e(), FindTemperatureOfBreakingChannel(), G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4StatMFParameters::GetMaxAverageMultiplicity(), G4VStatMFEnsemble::GetMeanTemperature(), G4Fragment::GetMomentum(), G4StatMFChannel::GetMultiplicity(), G4Fragment::GetZ_asInt(), CLHEP::Hep3Vector::mag2(), CLHEP::HepLorentzVector::setE(), and CLHEP::HepLorentzVector::setVect().
G4double G4StatMF::CalcEnergy (G4int A, G4int Z, const G4StatMFChannel * aChannel, G4double T) private
Definition at line 273 of file G4StatMF.cc.
View newest version in sPHENIX GitHub at line 273 of file G4StatMF.cc
References G4StatMFParameters::GetCoulomb(), G4StatMFChannel::GetFragmentsEnergy(), and G4NucleiProperties::GetMassExcess().
Referenced by FindTemperatureOfBreakingChannel().
G4bool G4StatMF::FindTemperatureOfBreakingChannel (const G4Fragment & theFragment, const G4StatMFChannel * aChannel, G4double & Temperature) private
Definition at line 196 of file G4StatMF.cc.
View newest version in sPHENIX GitHub at line 196 of file G4StatMF.cc
References A(), kdfinder::abs(), CalcEnergy(), eps, G4Fragment::GetA_asInt(), G4Fragment::GetExcitationEnergy(), G4Fragment::GetZ_asInt(), max, MeV, T, and Z.
Referenced by BreakItUp().
G4bool G4StatMF::operator!= (const G4StatMF & right) private
G4StatMF& G4StatMF::operator= (const G4StatMF & right) private
G4bool G4StatMF::operator== (const G4StatMF & right) private
Member Data Documentation
G4VStatMFEnsemble* G4StatMF::_theEnsemble private
Definition at line 82 of file G4StatMF.hh.
View newest version in sPHENIX GitHub at line 82 of file G4StatMF.hh
Referenced by BreakItUp().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/include/G4StatMF.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/de_excitation/multifragmentation/src/G4StatMF.cc