ECCE @ EIC Software: G03ColorReader Class Reference
G03ColorReader Class Reference
GDML reader for the color attributes.
#include <geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G03/include/G03ColorReader.hh>
Public Member Functions
G03ColorReader ()
~G03ColorReader ()
void ExtensionRead (const xercesc::DOMElement *const element)
void ColorRead (const xercesc::DOMElement *const element)
G4VisAttributes * GetVisAttribute (const G4String &ref)
Public Member Functions inherited from G4GDMLReadStructure
G4GDMLReadStructure ()
virtual ~G4GDMLReadStructure ()
G4VPhysicalVolume * GetPhysvol (const G4String &) const
G4LogicalVolume * GetVolume (const G4String &) const
G4AssemblyVolume * GetAssembly (const G4String &) const
G4GDMLAuxListType GetVolumeAuxiliaryInformation (G4LogicalVolume *) const
G4VPhysicalVolume * GetWorldVolume (const G4String &)
const G4GDMLAuxMapType * GetAuxMap () const
void Clear ()
virtual void Volume_contentRead (const xercesc::DOMElement *const)
virtual void StructureRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadParamvol
virtual void ParamvolRead (const xercesc::DOMElement *const, G4LogicalVolume *)
virtual void Paramvol_contentRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadSetup
G4String GetSetup (const G4String &)
virtual void SetupRead (const xercesc::DOMElement *const element)
Public Member Functions inherited from G4GDMLReadSolids
G4VSolid * GetSolid (const G4String &) const
G4SurfaceProperty * GetSurfaceProperty (const G4String &) const
virtual void SolidsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadMaterials
G4Element * GetElement (const G4String &, G4bool verbose=true) const
G4Isotope * GetIsotope (const G4String &, G4bool verbose=true) const
G4Material * GetMaterial (const G4String &, G4bool verbose=true) const
virtual void MaterialsRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLReadDefine
G4bool IsValidID (const G4String &) const
G4double GetConstant (const G4String &)
G4double GetVariable (const G4String &)
G4double GetQuantity (const G4String &)
G4ThreeVector GetPosition (const G4String &)
G4ThreeVector GetRotation (const G4String &)
G4ThreeVector GetScale (const G4String &)
G4GDMLMatrix GetMatrix (const G4String &)
virtual void DefineRead (const xercesc::DOMElement *const)
Public Member Functions inherited from G4GDMLRead
virtual void UserinfoRead (const xercesc::DOMElement *const)
void Read (const G4String &, G4bool validation, G4bool isModule, G4bool strip=true)
void StripNames () const
void StripName (G4String &) const
void OverlapCheck (G4bool)
const G4GDMLAuxListType * GetAuxList () const
Protected Member Functions
virtual void VolumeRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLReadStructure
void AssemblyRead (const xercesc::DOMElement *const)
void DivisionvolRead (const xercesc::DOMElement *const)
G4LogicalVolume * FileRead (const xercesc::DOMElement *const)
void PhysvolRead (const xercesc::DOMElement *const, G4AssemblyVolume *assembly=0)
void ReplicavolRead (const xercesc::DOMElement *const, G4int number)
void ReplicaRead (const xercesc::DOMElement *const replicaElement, G4LogicalVolume *logvol, G4int number)
EAxis AxisRead (const xercesc::DOMElement *const axisElement)
G4double QuantityRead (const xercesc::DOMElement *const readElement)
void BorderSurfaceRead (const xercesc::DOMElement *const)
void SkinSurfaceRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLReadParamvol
G4GDMLReadParamvol ()
virtual ~G4GDMLReadParamvol ()
void Box_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Trd_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Trap_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Tube_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Cone_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Sphere_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Orb_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Torus_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Ellipsoid_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Para_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Hype_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Polycone_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void Polyhedra_dimensionsRead (const xercesc::DOMElement *const, G4GDMLParameterisation::PARAMETER &)
void ParameterisedRead (const xercesc::DOMElement *const)
void ParametersRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLReadSetup
G4GDMLReadSetup ()
virtual ~G4GDMLReadSetup ()
Protected Member Functions inherited from G4GDMLReadSolids
G4GDMLReadSolids ()
virtual ~G4GDMLReadSolids ()
void BooleanRead (const xercesc::DOMElement *const, const BooleanOp)
void BoxRead (const xercesc::DOMElement *const)
void ConeRead (const xercesc::DOMElement *const)
void ElconeRead (const xercesc::DOMElement *const)
void EllipsoidRead (const xercesc::DOMElement *const)
void EltubeRead (const xercesc::DOMElement *const)
void XtruRead (const xercesc::DOMElement *const)
void HypeRead (const xercesc::DOMElement *const)
void MultiUnionNodeRead (const xercesc::DOMElement *const, G4MultiUnion *const)
void MultiUnionRead (const xercesc::DOMElement *const)
void OrbRead (const xercesc::DOMElement *const)
void ParaRead (const xercesc::DOMElement *const)
void ParaboloidRead (const xercesc::DOMElement *const)
void PolyconeRead (const xercesc::DOMElement *const)
void GenericPolyconeRead (const xercesc::DOMElement *const)
void PolyhedraRead (const xercesc::DOMElement *const)
void GenericPolyhedraRead (const xercesc::DOMElement *const)
G4QuadrangularFacet * QuadrangularRead (const xercesc::DOMElement *const)
void ReflectedSolidRead (const xercesc::DOMElement *const)
void ScaledSolidRead (const xercesc::DOMElement *const)
G4ExtrudedSolid::ZSection SectionRead (const xercesc::DOMElement *const, G4double)
void SphereRead (const xercesc::DOMElement *const)
void TessellatedRead (const xercesc::DOMElement *const)
void TetRead (const xercesc::DOMElement *const)
void TorusRead (const xercesc::DOMElement *const)
void GenTrapRead (const xercesc::DOMElement *const)
void TrapRead (const xercesc::DOMElement *const)
void TrdRead (const xercesc::DOMElement *const)
void TubeRead (const xercesc::DOMElement *const)
void CutTubeRead (const xercesc::DOMElement *const)
void TwistedboxRead (const xercesc::DOMElement *const)
void TwistedtrapRead (const xercesc::DOMElement *const)
void TwistedtrdRead (const xercesc::DOMElement *const)
void TwistedtubsRead (const xercesc::DOMElement *const)
G4TriangularFacet * TriangularRead (const xercesc::DOMElement *const)
G4TwoVector TwoDimVertexRead (const xercesc::DOMElement *const, G4double)
zplaneType ZplaneRead (const xercesc::DOMElement *const)
rzPointType RZPointRead (const xercesc::DOMElement *const)
void OpticalSurfaceRead (const xercesc::DOMElement *const)
void PropertyRead (const xercesc::DOMElement *const, G4OpticalSurface *)
Protected Member Functions inherited from G4GDMLReadMaterials
G4GDMLReadMaterials ()
virtual ~G4GDMLReadMaterials ()
G4double AtomRead (const xercesc::DOMElement *const)
G4int CompositeRead (const xercesc::DOMElement *const, G4String &)
G4double DRead (const xercesc::DOMElement *const)
G4double PRead (const xercesc::DOMElement *const)
G4double TRead (const xercesc::DOMElement *const)
G4double MEERead (const xercesc::DOMElement *const)
void ElementRead (const xercesc::DOMElement *const)
G4double FractionRead (const xercesc::DOMElement *const, G4String &)
void IsotopeRead (const xercesc::DOMElement *const)
void MaterialRead (const xercesc::DOMElement *const)
void MixtureRead (const xercesc::DOMElement *const, G4Element *)
void MixtureRead (const xercesc::DOMElement *const, G4Material *)
void PropertyRead (const xercesc::DOMElement *const, G4Material *)
Protected Member Functions inherited from G4GDMLReadDefine
G4GDMLReadDefine ()
virtual ~G4GDMLReadDefine ()
G4RotationMatrix GetRotationMatrix (const G4ThreeVector &)
void VectorRead (const xercesc::DOMElement *const, G4ThreeVector &)
G4String RefRead (const xercesc::DOMElement *const)
void ConstantRead (const xercesc::DOMElement *const)
void MatrixRead (const xercesc::DOMElement *const)
void PositionRead (const xercesc::DOMElement *const)
void RotationRead (const xercesc::DOMElement *const)
void ScaleRead (const xercesc::DOMElement *const)
void VariableRead (const xercesc::DOMElement *const)
void QuantityRead (const xercesc::DOMElement *const)
void ExpressionRead (const xercesc::DOMElement *const)
Protected Member Functions inherited from G4GDMLRead
G4GDMLRead ()
virtual ~G4GDMLRead ()
G4String Transcode (const XMLCh *const)
G4String GenerateName (const G4String &name, G4bool strip=false)
G4String Strip (const G4String &) const
void GeneratePhysvolName (const G4String &, G4VPhysicalVolume *)
void LoopRead (const xercesc::DOMElement *const, void(G4GDMLRead::*)(const xercesc::DOMElement *const))
G4GDMLAuxStructType AuxiliaryRead (const xercesc::DOMElement *const auxElem)
Private Attributes
std::map< G4String,
G4VisAttributes * > fAttribs
Additional Inherited Members
Protected Attributes inherited from G4GDMLReadStructure
G4GDMLAuxMapType auxMap
G4GDMLAssemblyMapType assemblyMap
G4LogicalVolume * pMotherLogical
std::map< std::string,
G4VPhysicalVolume * > setuptoPV
G4bool strip
Detailed Description
GDML reader for the color attributes.
Definition at line 47 of file G03ColorReader.hh.
View newest version in sPHENIX GitHub at line 47 of file G03ColorReader.hh
Constructor & Destructor Documentation
G03ColorReader::G03ColorReader ()
Definition at line 39 of file G03ColorReader.cc.
View newest version in sPHENIX GitHub at line 39 of file G03ColorReader.cc
G03ColorReader::~G03ColorReader ()
Definition at line 46 of file G03ColorReader.cc.
View newest version in sPHENIX GitHub at line 46 of file G03ColorReader.cc
References fAttribs, and pos().
Member Function Documentation
void G03ColorReader::ColorRead (const xercesc::DOMElement *const element)
Definition at line 121 of file G03ColorReader.cc.
View newest version in sPHENIX GitHub at line 121 of file G03ColorReader.cc
References a, b, color(), G4GDMLRead::eval, G4GDMLEvaluator::Evaluate(), fAttribs, Acts::UnitConstants::g, G4cout, G4endl, G4GDMLRead::GenerateName(), r, and G4GDMLRead::Transcode().
Referenced by ExtensionRead().
void G03ColorReader::ExtensionRead (const xercesc::DOMElement *const element) virtual
Reimplemented from G4GDMLRead.
Definition at line 55 of file G03ColorReader.cc.
View newest version in sPHENIX GitHub at line 55 of file G03ColorReader.cc
References ColorRead(), FatalException, G4cout, G4endl, G4Exception(), and G4GDMLRead::Transcode().
G4VisAttributes * G03ColorReader::GetVisAttribute (const G4String & ref)
Definition at line 164 of file G03ColorReader.cc.
View newest version in sPHENIX GitHub at line 164 of file G03ColorReader.cc
References col, FatalException, fAttribs, G4Exception(), and pos().
Referenced by VolumeRead().
void G03ColorReader::VolumeRead (const xercesc::DOMElement * const volumeElement) protected virtual
Reimplemented from G4GDMLReadStructure.
Definition at line 80 of file G03ColorReader.cc.
View newest version in sPHENIX GitHub at line 80 of file G03ColorReader.cc
References G4GDMLRead::AuxiliaryRead(), G4GDMLReadStructure::auxMap, G4GDMLRead::GenerateName(), G4GDMLReadMaterials::GetMaterial(), G4GDMLReadSolids::GetSolid(), GetVisAttribute(), G4GDMLReadStructure::pMotherLogical, G4GDMLReadDefine::RefRead(), G4LogicalVolume::SetVisAttributes(), G4GDMLRead::Transcode(), and G4GDMLReadStructure::Volume_contentRead().
Member Data Documentation
std::map<G4String, G4VisAttributes*> G03ColorReader::fAttribs private
Definition at line 66 of file G03ColorReader.hh.
View newest version in sPHENIX GitHub at line 66 of file G03ColorReader.hh
Referenced by ColorRead(), GetVisAttribute(), and ~G03ColorReader().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G03/include/G03ColorReader.hh
geant4/tree/geant4-10.6-release/examples/extended/persistency/gdml/G03/src/G03ColorReader.cc