ECCE @ EIC Software: G4QGSPKaonBuilder Class Reference
G4QGSPKaonBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPKaonBuilder.hh>
Public Member Functions
G4QGSPKaonBuilder (G4bool quasiElastic=false)
virtual ~G4QGSPKaonBuilder ()
virtual void Build (G4HadronElasticProcess *aP) finaloverride
virtual void Build (G4KaonPlusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonMinusInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroLInelasticProcess *aP) finaloverride
virtual void Build (G4KaonZeroSInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VKaonBuilder
G4VKaonBuilder ()=default
virtual ~G4VKaonBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4GeneratorPrecompoundInterface * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4double theMin
G4double theMax
Detailed Description
Definition at line 57 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4QGSPKaonBuilder.hh
Constructor & Destructor Documentation
G4QGSPKaonBuilder::G4QGSPKaonBuilder (G4bool quasiElastic = false)
Definition at line 43 of file G4QGSPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 43 of file G4QGSPKaonBuilder.cc
References G4HadronicParameters::GetMaxEnergy(), G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMax, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSPKaonBuilder::~G4QGSPKaonBuilder () virtual
Definition at line 66 of file G4QGSPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 66 of file G4QGSPKaonBuilder.cc
References theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
void G4QGSPKaonBuilder::Build (G4HadronElasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 74 of file G4QGSPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 74 of file G4QGSPKaonBuilder.cc
void G4QGSPKaonBuilder::Build (G4KaonPlusInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 77 of file G4QGSPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 77 of file G4QGSPKaonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4QGSPKaonBuilder::Build (G4KaonMinusInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 85 of file G4QGSPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 85 of file G4QGSPKaonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4QGSPKaonBuilder::Build (G4KaonZeroLInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 93 of file G4QGSPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 93 of file G4QGSPKaonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
void G4QGSPKaonBuilder::Build (G4KaonZeroSInelasticProcess * aP) final override virtual
Implements G4VKaonBuilder.
Definition at line 101 of file G4QGSPKaonBuilder.cc.
View newest version in sPHENIX GitHub at line 101 of file G4QGSPKaonBuilder.cc
References G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMax, theMin, and theModel.
virtual void G4QGSPKaonBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 70 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 70 of file G4QGSPKaonBuilder.hh
References theMin.
Member Data Documentation
G4GeneratorPrecompoundInterface* G4QGSPKaonBuilder::theCascade private
Definition at line 75 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSPKaonBuilder.hh
Referenced by G4QGSPKaonBuilder().
G4double G4QGSPKaonBuilder::theMax private
Definition at line 80 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 80 of file G4QGSPKaonBuilder.hh
Referenced by Build(), and G4QGSPKaonBuilder().
G4double G4QGSPKaonBuilder::theMin private
Definition at line 79 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 79 of file G4QGSPKaonBuilder.hh
Referenced by Build(), G4QGSPKaonBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSPKaonBuilder::theModel private
Definition at line 74 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QGSPKaonBuilder.hh
Referenced by Build(), and G4QGSPKaonBuilder().
G4QuasiElasticChannel* G4QGSPKaonBuilder::theQuasiElastic private
Definition at line 78 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSPKaonBuilder.hh
Referenced by G4QGSPKaonBuilder(), and ~G4QGSPKaonBuilder().
G4ExcitedStringDecay* G4QGSPKaonBuilder::theStringDecay private
Definition at line 77 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QGSPKaonBuilder.hh
Referenced by G4QGSPKaonBuilder(), and ~G4QGSPKaonBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSPKaonBuilder::theStringModel private
Definition at line 76 of file G4QGSPKaonBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSPKaonBuilder.hh
Referenced by G4QGSPKaonBuilder(), and ~G4QGSPKaonBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSPKaonBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSPKaonBuilder.cc