ECCE @ EIC Software: CLHEP::HepStat Class Reference
CLHEP::HepStat Class Reference
#include <geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/Stat.h>
Static Public Member Functions
static double flatToGaussian (double r)
static double inverseErf (double t)
static double erf (double x)
static double erfQ (double x)
static double gammln (double x)
Private Member Functions
HepStat ()
Detailed Description
Author
Definition at line 50 of file Stat.h.
View newest version in sPHENIX GitHub at line 50 of file Stat.h
Constructor & Destructor Documentation
CLHEP::HepStat::HepStat () private
Member Function Documentation
double CLHEP::HepStat::erf (double x) static
Definition at line 268 of file flatToGaussian.cc.
View newest version in sPHENIX GitHub at line 268 of file flatToGaussian.cc
References deriv(), erfQ(), inverseErf(), CLHEP::pi, and x.
Referenced by G4QMDMeanField::Cal2BodyQuantities(), Erfc(), and G4FPYSamplingOps::ShiftParameters().
double CLHEP::HepStat::erfQ (double x) static
Definition at line 23 of file erfQ.cc.
View newest version in sPHENIX GitHub at line 23 of file erfQ.cc
References kdfinder::abs(), t, and z.
Referenced by erf().
double CLHEP::HepStat::flatToGaussian (double r) static
Definition at line 88 of file flatToGaussian.cc.
View newest version in sPHENIX GitHub at line 88 of file flatToGaussian.cc
References d1, dx, f0(), f1, CLHEP::gaussTables, Acts::UnitConstants::h, int(), r, sign(), Acts::Test::step(), Table4offset, Table4size, Table4step, CLHEP::Toffsets, CLHEP::transformSmall(), CLHEP::Tsizes, CLHEP::Tsteps, x2, and y1.
Referenced by inverseErf().
double CLHEP::HepStat::gammln (double x) static
Definition at line 18 of file gammln.cc.
View newest version in sPHENIX GitHub at line 18 of file gammln.cc
References tmp, and x.
double CLHEP::HepStat::inverseErf (double t) static
Definition at line 260 of file flatToGaussian.cc.
View newest version in sPHENIX GitHub at line 260 of file flatToGaussian.cc
References flatToGaussian().
Referenced by erf(), InvErf(), and InvErfc().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/externals/clhep/include/CLHEP/Random/Stat.h
geant4/tree/geant4-10.6-release/source/externals/clhep/src/erfQ.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/flatToGaussian.cc
geant4/tree/geant4-10.6-release/source/externals/clhep/src/gammln.cc