ECCE @ EIC Software: G4ExceptionHandler Class Reference
G4ExceptionHandler Class Reference
#include <geant4/tree/geant4-10.6-release/source/run/include/G4ExceptionHandler.hh>
Public Member Functions
G4ExceptionHandler ()
virtual ~G4ExceptionHandler ()
G4bool operator== (const G4ExceptionHandler &right) const
G4bool operator!= (const G4ExceptionHandler &right) const
virtual G4bool Notify (const char *originOfException, const char *exceptionCode, G4ExceptionSeverity severity, const char *description)
Public Member Functions inherited from G4VExceptionHandler
G4VExceptionHandler ()
virtual ~G4VExceptionHandler ()
G4bool operator== (const G4VExceptionHandler &right) const
G4bool operator!= (const G4VExceptionHandler &right) const
Private Member Functions
G4ExceptionHandler (const G4ExceptionHandler &right)
G4ExceptionHandler & operator= (const G4ExceptionHandler &right)
void DumpTrackInfo ()
Detailed Description
Definition at line 55 of file G4ExceptionHandler.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ExceptionHandler.hh
Constructor & Destructor Documentation
G4ExceptionHandler::G4ExceptionHandler ()
Definition at line 43 of file G4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 43 of file G4ExceptionHandler.cc
G4ExceptionHandler::~G4ExceptionHandler () virtual
Definition at line 47 of file G4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 47 of file G4ExceptionHandler.cc
G4ExceptionHandler::G4ExceptionHandler (const G4ExceptionHandler & right) private
Definition at line 51 of file G4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 51 of file G4ExceptionHandler.cc
Member Function Documentation
void G4ExceptionHandler::DumpTrackInfo () private
Definition at line 146 of file G4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 146 of file G4ExceptionHandler.cc
References G4BestUnit, G4cerr, G4endl, G4State_EventProc, G4Track::GetCreatorModelName(), G4Track::GetCreatorProcess(), G4StateManager::GetCurrentState(), G4SteppingManager::GetfStep(), G4SteppingManager::GetfTrack(), G4Track::GetKineticEnergy(), G4StepPoint::GetMaterial(), G4Track::GetMomentumDirection(), G4VPhysicalVolume::GetName(), G4Material::GetName(), G4Track::GetParentID(), G4Track::GetParticleDefinition(), G4ParticleDefinition::GetParticleName(), G4StepPoint::GetPhysicalVolume(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4StepPoint::GetProcessDefinedStep(), G4VProcess::GetProcessName(), G4RunManagerKernel::GetRunManagerKernel(), G4StateManager::GetStateManager(), G4Step::GetStepLength(), G4TrackingManager::GetSteppingManager(), G4StepPoint::GetStepStatus(), G4Step::GetTotalEnergyDeposit(), G4Track::GetTrackID(), and G4RunManagerKernel::GetTrackingManager().
Referenced by Notify().
G4bool G4ExceptionHandler::Notify (const char * originOfException, const char * exceptionCode, G4ExceptionSeverity severity, const char * description) virtual
Implements G4VExceptionHandler.
Definition at line 71 of file G4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 71 of file G4ExceptionHandler.cc
References G4RunManager::AbortEvent(), G4RunManager::AbortRun(), DumpTrackInfo(), EventMustBeAborted, FatalErrorInArgument, FatalException, G4cerr, G4cout, G4endl, G4State_EventProc, G4State_GeomClosed, G4StateManager::GetCurrentState(), G4RunManager::GetRunManager(), G4StateManager::GetStateManager(), message(), and RunMustBeAborted.
G4bool G4ExceptionHandler::operator!= (const G4ExceptionHandler & right) const
Definition at line 66 of file G4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 66 of file G4ExceptionHandler.cc
G4ExceptionHandler & G4ExceptionHandler::operator= (const G4ExceptionHandler & right) private
Definition at line 56 of file G4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ExceptionHandler.cc
G4bool G4ExceptionHandler::operator== (const G4ExceptionHandler & right) const
Definition at line 61 of file G4ExceptionHandler.cc.
View newest version in sPHENIX GitHub at line 61 of file G4ExceptionHandler.cc
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/run/include/G4ExceptionHandler.hh
geant4/tree/geant4-10.6-release/source/run/src/G4ExceptionHandler.cc