ECCE @ EIC Software: G4TrajectoryDrawByCharge Class Reference
G4TrajectoryDrawByCharge Class Reference
#include <geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByCharge.hh>
Public Types
enum Charge { Negative =-1, Neutral =0, Positive =1 }
Public Member Functions
G4TrajectoryDrawByCharge (const G4String &name="Unspecified", G4VisTrajContext *context=0)
G4TrajectoryDrawByCharge (const G4String &name, const G4Colour &positive, const G4Colour &negative, const G4Colour &neutral)
virtual ~G4TrajectoryDrawByCharge ()
virtual void Draw (const G4VTrajectory &trajectory, const G4bool &visible=true) const
virtual void Print (std::ostream &ostr) const
void Set (const Charge &charge, const G4Colour &colour)
void Set (const Charge &charge, const G4String &colour)
void Set (const G4String &charge, const G4Colour &colour)
void Set (const G4String &charge, const G4String &colour)
Public Member Functions inherited from G4VTrajectoryModel
G4VTrajectoryModel (const G4String &name, G4VisTrajContext *fpContext=0)
virtual ~G4VTrajectoryModel ()
G4String Name () const
const G4VisTrajContext & GetContext () const
void SetVerbose (const G4bool &)
G4bool GetVerbose () const
Private Member Functions
G4bool ConvertToCharge (const G4String &, Charge &)
Private Attributes
G4ModelColourMap< Charge > fMap
Detailed Description
Definition at line 42 of file G4TrajectoryDrawByCharge.hh.
View newest version in sPHENIX GitHub at line 42 of file G4TrajectoryDrawByCharge.hh
Member Enumeration Documentation
enum G4TrajectoryDrawByCharge::Charge
Enumerator:
Negative
Neutral
Positive
Definition at line 46 of file G4TrajectoryDrawByCharge.hh.
View newest version in sPHENIX GitHub at line 46 of file G4TrajectoryDrawByCharge.hh
Constructor & Destructor Documentation
G4TrajectoryDrawByCharge::G4TrajectoryDrawByCharge (const G4String & name = "Unspecified", G4VisTrajContext * context = 0)
Definition at line 34 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 34 of file G4TrajectoryDrawByCharge.cc
References G4Colour::Blue(), fMap, G4Colour::Green(), Negative, Neutral, Positive, and G4Colour::Red().
G4TrajectoryDrawByCharge::G4TrajectoryDrawByCharge (const G4String & name, const G4Colour & positive, const G4Colour & negative, const G4Colour & neutral)
Definition at line 43 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 43 of file G4TrajectoryDrawByCharge.cc
References fMap, Negative, Neutral, and Positive.
G4TrajectoryDrawByCharge::~G4TrajectoryDrawByCharge () virtual
Definition at line 54 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 54 of file G4TrajectoryDrawByCharge.cc
Member Function Documentation
G4bool G4TrajectoryDrawByCharge::ConvertToCharge (const G4String & string, Charge & myCharge) private
Definition at line 134 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 134 of file G4TrajectoryDrawByCharge.cc
References charge, Negative, Neutral, and Positive.
Referenced by Set().
void G4TrajectoryDrawByCharge::Draw (const G4VTrajectory & trajectory, const G4bool & visible = true) const virtual
Implements G4VTrajectoryModel.
Definition at line 57 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 57 of file G4TrajectoryDrawByCharge.cc
References charge, G4TrajectoryDrawerUtils::DrawLineAndPoints(), fMap, G4cout, G4endl, G4VTrajectory::GetCharge(), G4ModelColourMap< T >::GetColour(), G4VTrajectoryModel::GetContext(), G4VTrajectoryModel::GetVerbose(), G4VTrajectoryModel::Name(), Negative, Neutral, Positive, G4VisTrajContext::Print(), and G4VisTrajContext::SetLineColour().
void G4TrajectoryDrawByCharge::Print (std::ostream & ostr) const virtual
Implements G4VTrajectoryModel.
Definition at line 82 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 82 of file G4TrajectoryDrawByCharge.cc
References fMap, G4cout, G4endl, G4VTrajectoryModel::GetContext(), G4VTrajectoryModel::Name(), G4VisTrajContext::Print(), and G4ModelColourMap< T >::Print().
void G4TrajectoryDrawByCharge::Set (const Charge & charge, const G4Colour & colour)
Definition at line 97 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 97 of file G4TrajectoryDrawByCharge.cc
References charge, and fMap.
Referenced by Set().
void G4TrajectoryDrawByCharge::Set (const Charge & charge, const G4String & colour)
Definition at line 91 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 91 of file G4TrajectoryDrawByCharge.cc
References fMap, and G4ModelColourMap< T >::Set().
void G4TrajectoryDrawByCharge::Set (const G4String & charge, const G4Colour & colour)
Definition at line 119 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 119 of file G4TrajectoryDrawByCharge.cc
References charge, ConvertToCharge(), G4Exception(), JustWarning, and Set().
void G4TrajectoryDrawByCharge::Set (const G4String & charge, const G4String & colour)
Definition at line 103 of file G4TrajectoryDrawByCharge.cc.
View newest version in sPHENIX GitHub at line 103 of file G4TrajectoryDrawByCharge.cc
References charge, ConvertToCharge(), G4Exception(), JustWarning, and Set().
Member Data Documentation
G4ModelColourMap<Charge> G4TrajectoryDrawByCharge::fMap private
Definition at line 76 of file G4TrajectoryDrawByCharge.hh.
View newest version in sPHENIX GitHub at line 76 of file G4TrajectoryDrawByCharge.hh
Referenced by Draw(), G4TrajectoryDrawByCharge(), Print(), and Set().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/visualization/modeling/include/G4TrajectoryDrawByCharge.hh
geant4/tree/geant4-10.6-release/source/visualization/modeling/src/G4TrajectoryDrawByCharge.cc