ECCE @ EIC Software: G4QGSBinaryPionBuilder Class Reference
G4QGSBinaryPionBuilder Class Reference
#include <geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBinaryPionBuilder.hh>
Public Member Functions
G4QGSBinaryPionBuilder (G4bool quasiElastic=false)
virtual ~G4QGSBinaryPionBuilder ()
virtual void Build (G4HadronElasticProcess *) finaloverride
virtual void Build (G4PionPlusInelasticProcess *aP) finaloverride
virtual void Build (G4PionMinusInelasticProcess *aP) finaloverride
virtual void SetMinEnergy (G4double aM) finaloverride
Public Member Functions inherited from G4VPionBuilder
G4VPionBuilder ()=default
virtual ~G4VPionBuilder ()
Public Member Functions inherited from G4PhysicsBuilderInterface
G4PhysicsBuilderInterface ()=default
virtual ~G4PhysicsBuilderInterface ()
virtual void Build ()
virtual void RegisterMe (G4PhysicsBuilderInterface *)
virtual void SetMaxEnergy (G4double)
Private Attributes
G4TheoFSGenerator * theModel
G4BinaryCascade * theCascade
G4QGSModel< G4QGSParticipants > * theStringModel
G4ExcitedStringDecay * theStringDecay
G4QuasiElasticChannel * theQuasiElastic
G4double theMin
Detailed Description
Definition at line 57 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 57 of file G4QGSBinaryPionBuilder.hh
Constructor & Destructor Documentation
G4QGSBinaryPionBuilder::G4QGSBinaryPionBuilder (G4bool quasiElastic = false)
Definition at line 44 of file G4QGSBinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 44 of file G4QGSBinaryPionBuilder.cc
References G4HadronicParameters::GetMinEnergyTransitionQGS_FTF(), G4HadronicParameters::Instance(), G4VPartonStringModel::SetFragmentationModel(), G4TheoFSGenerator::SetHighEnergyGenerator(), G4TheoFSGenerator::SetQuasiElasticChannel(), G4TheoFSGenerator::SetTransport(), theCascade, theMin, theModel, theQuasiElastic, theStringDecay, and theStringModel.
G4QGSBinaryPionBuilder::~G4QGSBinaryPionBuilder () virtual
Definition at line 66 of file G4QGSBinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 66 of file G4QGSBinaryPionBuilder.cc
References theQuasiElastic, theStringDecay, and theStringModel.
Member Function Documentation
virtual void G4QGSBinaryPionBuilder::Build (G4HadronElasticProcess *) inline final override virtual
Implements G4VPionBuilder.
Definition at line 64 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 64 of file G4QGSBinaryPionBuilder.hh
void G4QGSBinaryPionBuilder::Build (G4PionPlusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 74 of file G4QGSBinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 74 of file G4QGSBinaryPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionPlus::Definition(), G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
void G4QGSBinaryPionBuilder::Build (G4PionMinusInelasticProcess * aP) final override virtual
Implements G4VPionBuilder.
Definition at line 83 of file G4QGSBinaryPionBuilder.cc.
View newest version in sPHENIX GitHub at line 83 of file G4QGSBinaryPionBuilder.cc
References G4HadronicProcess::AddDataSet(), G4PionMinus::Definition(), G4HadronicParameters::Instance(), G4HadronicProcess::RegisterMe(), G4HadronicInteraction::SetMaxEnergy(), G4HadronicInteraction::SetMinEnergy(), theMin, and theModel.
virtual void G4QGSBinaryPionBuilder::SetMinEnergy (G4double aM) inline final override virtual
Reimplemented from G4PhysicsBuilderInterface.
Definition at line 68 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 68 of file G4QGSBinaryPionBuilder.hh
References theMin.
Member Data Documentation
G4BinaryCascade* G4QGSBinaryPionBuilder::theCascade private
Definition at line 74 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 74 of file G4QGSBinaryPionBuilder.hh
Referenced by G4QGSBinaryPionBuilder().
G4double G4QGSBinaryPionBuilder::theMin private
Definition at line 78 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 78 of file G4QGSBinaryPionBuilder.hh
Referenced by Build(), G4QGSBinaryPionBuilder(), and SetMinEnergy().
G4TheoFSGenerator* G4QGSBinaryPionBuilder::theModel private
Definition at line 73 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 73 of file G4QGSBinaryPionBuilder.hh
Referenced by Build(), and G4QGSBinaryPionBuilder().
G4QuasiElasticChannel* G4QGSBinaryPionBuilder::theQuasiElastic private
Definition at line 77 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 77 of file G4QGSBinaryPionBuilder.hh
Referenced by G4QGSBinaryPionBuilder(), and ~G4QGSBinaryPionBuilder().
G4ExcitedStringDecay* G4QGSBinaryPionBuilder::theStringDecay private
Definition at line 76 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 76 of file G4QGSBinaryPionBuilder.hh
Referenced by G4QGSBinaryPionBuilder(), and ~G4QGSBinaryPionBuilder().
G4QGSModel< G4QGSParticipants >* G4QGSBinaryPionBuilder::theStringModel private
Definition at line 75 of file G4QGSBinaryPionBuilder.hh.
View newest version in sPHENIX GitHub at line 75 of file G4QGSBinaryPionBuilder.hh
Referenced by G4QGSBinaryPionBuilder(), and ~G4QGSBinaryPionBuilder().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/physics_lists/builders/include/G4QGSBinaryPionBuilder.hh
geant4/tree/geant4-10.6-release/source/physics_lists/builders/src/G4QGSBinaryPionBuilder.cc