ECCE @ EIC Software: G4VAnalysisReader Class Reference
G4VAnalysisReader Class Reference abstract
#include <geant4/tree/geant4-10.6-release/source/analysis/management/include/G4VAnalysisReader.hh>
Public Member Functions
G4VAnalysisReader (const G4String &type, G4bool isMaster)
virtual ~G4VAnalysisReader ()
void SetFileName (const G4String &fileName)
G4String GetFileName () const
G4int ReadH1 (const G4String &h1Name, const G4String &fileName="", const G4String &dirName="")
G4int ReadH2 (const G4String &h2Name, const G4String &fileName="", const G4String &dirName="")
G4int ReadH3 (const G4String &h3Name, const G4String &fileName="", const G4String &dirName="")
G4int ReadP1 (const G4String &h1Name, const G4String &fileName="", const G4String &dirName="")
G4int ReadP2 (const G4String &h2Name, const G4String &fileName="", const G4String &dirName="")
G4bool SetFirstHistoId (G4int firstId)
G4bool SetFirstH1Id (G4int firstId)
G4bool SetFirstH2Id (G4int firstId)
G4bool SetFirstH3Id (G4int firstId)
G4bool SetFirstProfileId (G4int firstId)
G4bool SetFirstP1Id (G4int firstId)
G4bool SetFirstP2Id (G4int firstId)
G4bool SetFirstNtupleId (G4int firstId)
G4int GetNtuple (const G4String &ntupleName, const G4String &fileName="", const G4String &dirName="")
G4bool SetNtupleIColumn (const G4String &columnName, G4int &value)
G4bool SetNtupleFColumn (const G4String &columnName, G4float &value)
G4bool SetNtupleDColumn (const G4String &columnName, G4double &value)
G4bool SetNtupleSColumn (const G4String &columnName, G4String &value)
G4bool SetNtupleIColumn (const G4String &columnName, std::vector< int > &vector)
G4bool SetNtupleFColumn (const G4String &columnName, std::vector< float > &vector)
G4bool SetNtupleDColumn (const G4String &columnName, std::vector< double > &vector)
G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, G4int &value)
G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, G4float &value)
G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, G4double &value)
G4bool SetNtupleSColumn (G4int ntupleId, const G4String &columnName, G4String &value)
G4bool SetNtupleIColumn (G4int ntupleId, const G4String &columnName, std::vector< int > &vector)
G4bool SetNtupleFColumn (G4int ntupleId, const G4String &columnName, std::vector< float > &vector)
G4bool SetNtupleDColumn (G4int ntupleId, const G4String &columnName, std::vector< double > &vector)
G4bool GetNtupleRow ()
G4bool GetNtupleRow (G4int ntupleId)
G4bool IsAscii () const
G4int GetNofH1s () const
G4int GetNofH2s () const
G4int GetNofH3s () const
G4int GetNofP1s () const
G4int GetNofP2s () const
G4int GetNofNtuples () const
G4int GetH1Id (const G4String &name, G4bool warn=true) const
G4int GetH2Id (const G4String &name, G4bool warn=true) const
G4int GetH3Id (const G4String &name, G4bool warn=true) const
G4int GetP1Id (const G4String &name, G4bool warn=true) const
G4int GetP2Id (const G4String &name, G4bool warn=true) const
G4int GetH1Nbins (G4int id) const
G4double GetH1Xmin (G4int id) const
G4double GetH1Xmax (G4int id) const
G4double GetH1Width (G4int id) const
G4int GetH2Nxbins (G4int id) const
G4double GetH2Xmin (G4int id) const
G4double GetH2Xmax (G4int id) const
G4double GetH2XWidth (G4int id) const
G4int GetH2Nybins (G4int id) const
G4double GetH2Ymin (G4int id) const
G4double GetH2Ymax (G4int id) const
G4double GetH2YWidth (G4int id) const
G4int GetH3Nxbins (G4int id) const
G4double GetH3Xmin (G4int id) const
G4double GetH3Xmax (G4int id) const
G4double GetH3XWidth (G4int id) const
G4int GetH3Nybins (G4int id) const
G4double GetH3Ymin (G4int id) const
G4double GetH3Ymax (G4int id) const
G4double GetH3YWidth (G4int id) const
G4int GetH3Nzbins (G4int id) const
G4double GetH3Zmin (G4int id) const
G4double GetH3Zmax (G4int id) const
G4double GetH3ZWidth (G4int id) const
G4int GetP1Nbins (G4int id) const
G4double GetP1Xmin (G4int id) const
G4double GetP1Xmax (G4int id) const
G4double GetP1XWidth (G4int id) const
G4double GetP1Ymin (G4int id) const
G4double GetP1Ymax (G4int id) const
G4int GetP2Nxbins (G4int id) const
G4double GetP2Xmin (G4int id) const
G4double GetP2Xmax (G4int id) const
G4double GetP2XWidth (G4int id) const
G4int GetP2Nybins (G4int id) const
G4double GetP2Ymin (G4int id) const
G4double GetP2Ymax (G4int id) const
G4double GetP2YWidth (G4int id) const
G4double GetP2Zmin (G4int id) const
G4double GetP2Zmax (G4int id) const
G4String GetH1Title (G4int id) const
G4String GetH1XAxisTitle (G4int id) const
G4String GetH1YAxisTitle (G4int id) const
G4String GetH2Title (G4int id) const
G4String GetH2XAxisTitle (G4int id) const
G4String GetH2YAxisTitle (G4int id) const
G4String GetH2ZAxisTitle (G4int id) const
G4String GetH3Title (G4int id) const
G4String GetH3XAxisTitle (G4int id) const
G4String GetH3YAxisTitle (G4int id) const
G4String GetH3ZAxisTitle (G4int id) const
G4String GetP1Title (G4int id) const
G4String GetP1XAxisTitle (G4int id) const
G4String GetP1YAxisTitle (G4int id) const
G4String GetP1ZAxisTitle (G4int id) const
G4String GetP2Title (G4int id) const
G4String GetP2XAxisTitle (G4int id) const
G4String GetP2YAxisTitle (G4int id) const
G4String GetP2ZAxisTitle (G4int id) const
void SetVerboseLevel (G4int verboseLevel)
G4int GetVerboseLevel () const
G4String GetType () const
G4String GetFileType () const
Protected Member Functions
virtual G4int ReadH1Impl (const G4String &h1Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName)=0
virtual G4int ReadH2Impl (const G4String &h2Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName)=0
virtual G4int ReadH3Impl (const G4String &h3Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName)=0
virtual G4int ReadP1Impl (const G4String &p1Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName)=0
virtual G4int ReadP2Impl (const G4String &p2Name, const G4String &fileName, const G4String &dirName, G4bool isUserFileName)=0
virtual G4int ReadNtupleImpl (const G4String &ntupleName, const G4String &fileName, const G4String &dirName, G4bool isUserFileName)=0
void SetH1Manager (G4VH1Manager *h1Manager)
void SetH2Manager (G4VH2Manager *h2Manager)
void SetH3Manager (G4VH3Manager *h3Manager)
void SetP1Manager (G4VP1Manager *p1Manager)
void SetP2Manager (G4VP2Manager *p2Manager)
void SetNtupleManager (G4VRNtupleManager *ntupleManager)
void SetFileManager (G4BaseFileManager *fileManager)
Protected Attributes
G4AnalysisManagerState fState
Private Attributes
std::unique_ptr< G4VH1Manager > fVH1Manager
std::unique_ptr< G4VH2Manager > fVH2Manager
std::unique_ptr< G4VH3Manager > fVH3Manager
std::unique_ptr< G4VP1Manager > fVP1Manager
std::unique_ptr< G4VP2Manager > fVP2Manager
std::unique_ptr
< G4VRNtupleManager > fVNtupleManager
std::unique_ptr
< G4BaseFileManager > fFileManager
Detailed Description
Definition at line 55 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 55 of file G4VAnalysisReader.hh
Constructor & Destructor Documentation
G4VAnalysisReader::G4VAnalysisReader (const G4String & type, G4bool isMaster)
Definition at line 45 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 45 of file G4VAnalysisReader.cc
G4VAnalysisReader::~G4VAnalysisReader () virtual
Definition at line 57 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 57 of file G4VAnalysisReader.cc
Member Function Documentation
G4String G4VAnalysisReader::GetFileName () const
Definition at line 117 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 117 of file G4VAnalysisReader.cc
References fFileManager.
G4String G4VAnalysisReader::GetFileType () const
G4int G4VAnalysisReader::GetH1Id (const G4String & name, G4bool warn = true) const
G4int G4VAnalysisReader::GetH1Nbins (G4int id) const
G4String G4VAnalysisReader::GetH1Title (G4int id) const
G4double G4VAnalysisReader::GetH1Width (G4int id) const
G4String G4VAnalysisReader::GetH1XAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetH1Xmax (G4int id) const
G4double G4VAnalysisReader::GetH1Xmin (G4int id) const
G4String G4VAnalysisReader::GetH1YAxisTitle (G4int id) const
G4int G4VAnalysisReader::GetH2Id (const G4String & name, G4bool warn = true) const
G4int G4VAnalysisReader::GetH2Nxbins (G4int id) const
G4int G4VAnalysisReader::GetH2Nybins (G4int id) const
G4String G4VAnalysisReader::GetH2Title (G4int id) const
G4String G4VAnalysisReader::GetH2XAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetH2Xmax (G4int id) const
G4double G4VAnalysisReader::GetH2Xmin (G4int id) const
G4double G4VAnalysisReader::GetH2XWidth (G4int id) const
G4String G4VAnalysisReader::GetH2YAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetH2Ymax (G4int id) const
G4double G4VAnalysisReader::GetH2Ymin (G4int id) const
G4double G4VAnalysisReader::GetH2YWidth (G4int id) const
G4String G4VAnalysisReader::GetH2ZAxisTitle (G4int id) const
G4int G4VAnalysisReader::GetH3Id (const G4String & name, G4bool warn = true) const
G4int G4VAnalysisReader::GetH3Nxbins (G4int id) const
G4int G4VAnalysisReader::GetH3Nybins (G4int id) const
G4int G4VAnalysisReader::GetH3Nzbins (G4int id) const
G4String G4VAnalysisReader::GetH3Title (G4int id) const
G4String G4VAnalysisReader::GetH3XAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetH3Xmax (G4int id) const
G4double G4VAnalysisReader::GetH3Xmin (G4int id) const
G4double G4VAnalysisReader::GetH3XWidth (G4int id) const
G4String G4VAnalysisReader::GetH3YAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetH3Ymax (G4int id) const
G4double G4VAnalysisReader::GetH3Ymin (G4int id) const
G4double G4VAnalysisReader::GetH3YWidth (G4int id) const
G4String G4VAnalysisReader::GetH3ZAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetH3Zmax (G4int id) const
G4double G4VAnalysisReader::GetH3Zmin (G4int id) const
G4double G4VAnalysisReader::GetH3ZWidth (G4int id) const
G4int G4VAnalysisReader::GetNofH1s () const
Definition at line 435 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 435 of file G4VAnalysisReader.cc
References fVH1Manager.
G4int G4VAnalysisReader::GetNofH2s () const
Definition at line 441 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 441 of file G4VAnalysisReader.cc
References fVH2Manager.
G4int G4VAnalysisReader::GetNofH3s () const
Definition at line 447 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 447 of file G4VAnalysisReader.cc
References fVH3Manager.
G4int G4VAnalysisReader::GetNofNtuples () const
Definition at line 465 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 465 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4int G4VAnalysisReader::GetNofP1s () const
Definition at line 453 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 453 of file G4VAnalysisReader.cc
References fVP1Manager.
G4int G4VAnalysisReader::GetNofP2s () const
Definition at line 459 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 459 of file G4VAnalysisReader.cc
References fVP2Manager.
G4int G4VAnalysisReader::GetNtuple (const G4String & ntupleName, const G4String & fileName = "", const G4String & dirName = "")
Definition at line 295 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 295 of file G4VAnalysisReader.cc
References fFileManager, G4Exception(), JustWarning, G4Analysis::kInvalidId, and ReadNtupleImpl().
G4bool G4VAnalysisReader::GetNtupleRow ()
Definition at line 422 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 422 of file G4VAnalysisReader.cc
References fVNtupleManager.
Referenced by XrayFluoAnalysisManager::LoadGunData().
G4bool G4VAnalysisReader::GetNtupleRow (G4int ntupleId)
Definition at line 429 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 429 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4int G4VAnalysisReader::GetP1Id (const G4String & name, G4bool warn = true) const
G4int G4VAnalysisReader::GetP1Nbins (G4int id) const
G4String G4VAnalysisReader::GetP1Title (G4int id) const
G4String G4VAnalysisReader::GetP1XAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetP1Xmax (G4int id) const
G4double G4VAnalysisReader::GetP1Xmin (G4int id) const
G4double G4VAnalysisReader::GetP1XWidth (G4int id) const
G4String G4VAnalysisReader::GetP1YAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetP1Ymax (G4int id) const
G4double G4VAnalysisReader::GetP1Ymin (G4int id) const
G4String G4VAnalysisReader::GetP1ZAxisTitle (G4int id) const
G4int G4VAnalysisReader::GetP2Id (const G4String & name, G4bool warn = true) const
G4int G4VAnalysisReader::GetP2Nxbins (G4int id) const
G4int G4VAnalysisReader::GetP2Nybins (G4int id) const
G4String G4VAnalysisReader::GetP2Title (G4int id) const
G4String G4VAnalysisReader::GetP2XAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetP2Xmax (G4int id) const
G4double G4VAnalysisReader::GetP2Xmin (G4int id) const
G4double G4VAnalysisReader::GetP2XWidth (G4int id) const
G4String G4VAnalysisReader::GetP2YAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetP2Ymax (G4int id) const
G4double G4VAnalysisReader::GetP2Ymin (G4int id) const
G4double G4VAnalysisReader::GetP2YWidth (G4int id) const
G4String G4VAnalysisReader::GetP2ZAxisTitle (G4int id) const
G4double G4VAnalysisReader::GetP2Zmax (G4int id) const
G4double G4VAnalysisReader::GetP2Zmin (G4int id) const
G4String G4VAnalysisReader::GetType () const
G4int G4VAnalysisReader::GetVerboseLevel () const
G4bool G4VAnalysisReader::IsAscii () const
G4int G4VAnalysisReader::ReadH1 (const G4String & h1Name, const G4String & fileName = "", const G4String & dirName = "")
Definition at line 123 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 123 of file G4VAnalysisReader.cc
References fFileManager, G4Exception(), JustWarning, G4Analysis::kInvalidId, and ReadH1Impl().
virtual G4int G4VAnalysisReader::ReadH1Impl (const G4String & h1Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) protected pure virtual
Implemented in G4CsvAnalysisReader, G4Hdf5AnalysisReader, G4RootAnalysisReader, and G4XmlAnalysisReader.
Referenced by ReadH1().
G4int G4VAnalysisReader::ReadH2 (const G4String & h2Name, const G4String & fileName = "", const G4String & dirName = "")
Definition at line 144 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 144 of file G4VAnalysisReader.cc
References fFileManager, G4Exception(), JustWarning, G4Analysis::kInvalidId, and ReadH2Impl().
virtual G4int G4VAnalysisReader::ReadH2Impl (const G4String & h2Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) protected pure virtual
Implemented in G4CsvAnalysisReader, G4Hdf5AnalysisReader, G4RootAnalysisReader, and G4XmlAnalysisReader.
Referenced by ReadH2().
G4int G4VAnalysisReader::ReadH3 (const G4String & h3Name, const G4String & fileName = "", const G4String & dirName = "")
Definition at line 165 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 165 of file G4VAnalysisReader.cc
References fFileManager, G4Exception(), JustWarning, G4Analysis::kInvalidId, and ReadH3Impl().
virtual G4int G4VAnalysisReader::ReadH3Impl (const G4String & h3Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) protected pure virtual
Implemented in G4CsvAnalysisReader, G4Hdf5AnalysisReader, G4RootAnalysisReader, and G4XmlAnalysisReader.
Referenced by ReadH3().
virtual G4int G4VAnalysisReader::ReadNtupleImpl (const G4String & ntupleName, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) protected pure virtual
Implemented in G4CsvAnalysisReader, G4Hdf5AnalysisReader, G4RootAnalysisReader, and G4XmlAnalysisReader.
Referenced by GetNtuple().
G4int G4VAnalysisReader::ReadP1 (const G4String & h1Name, const G4String & fileName = "", const G4String & dirName = "")
Definition at line 186 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 186 of file G4VAnalysisReader.cc
References fFileManager, G4Exception(), JustWarning, G4Analysis::kInvalidId, and ReadP1Impl().
virtual G4int G4VAnalysisReader::ReadP1Impl (const G4String & p1Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) protected pure virtual
Implemented in G4CsvAnalysisReader, G4Hdf5AnalysisReader, G4RootAnalysisReader, and G4XmlAnalysisReader.
Referenced by ReadP1().
G4int G4VAnalysisReader::ReadP2 (const G4String & h2Name, const G4String & fileName = "", const G4String & dirName = "")
Definition at line 207 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 207 of file G4VAnalysisReader.cc
References fFileManager, G4Exception(), JustWarning, G4Analysis::kInvalidId, and ReadP2Impl().
virtual G4int G4VAnalysisReader::ReadP2Impl (const G4String & p2Name, const G4String & fileName, const G4String & dirName, G4bool isUserFileName) protected pure virtual
Implemented in G4CsvAnalysisReader, G4Hdf5AnalysisReader, G4RootAnalysisReader, and G4XmlAnalysisReader.
Referenced by ReadP2().
void G4VAnalysisReader::SetFileManager (G4BaseFileManager * fileManager) protected
Definition at line 101 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 101 of file G4VAnalysisReader.cc
References fFileManager.
Referenced by G4CsvAnalysisReader::G4CsvAnalysisReader(), G4Hdf5AnalysisReader::G4Hdf5AnalysisReader(), G4RootAnalysisReader::G4RootAnalysisReader(), and G4XmlAnalysisReader::G4XmlAnalysisReader().
void G4VAnalysisReader::SetFileName (const G4String & fileName)
Definition at line 111 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 111 of file G4VAnalysisReader.cc
References fFileManager.
G4bool G4VAnalysisReader::SetFirstH1Id (G4int firstId)
Definition at line 245 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 245 of file G4VAnalysisReader.cc
References fVH1Manager.
Referenced by SetFirstHistoId().
G4bool G4VAnalysisReader::SetFirstH2Id (G4int firstId)
Definition at line 251 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 251 of file G4VAnalysisReader.cc
References fVH2Manager.
Referenced by SetFirstHistoId().
G4bool G4VAnalysisReader::SetFirstH3Id (G4int firstId)
Definition at line 257 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 257 of file G4VAnalysisReader.cc
References fVH3Manager.
Referenced by SetFirstHistoId().
G4bool G4VAnalysisReader::SetFirstHistoId (G4int firstId)
Definition at line 228 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 228 of file G4VAnalysisReader.cc
References SetFirstH1Id(), SetFirstH2Id(), and SetFirstH3Id().
G4bool G4VAnalysisReader::SetFirstNtupleId (G4int firstId)
Definition at line 289 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 289 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetFirstP1Id (G4int firstId)
Definition at line 277 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 277 of file G4VAnalysisReader.cc
References fVP1Manager.
Referenced by SetFirstProfileId().
G4bool G4VAnalysisReader::SetFirstP2Id (G4int firstId)
Definition at line 283 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 283 of file G4VAnalysisReader.cc
References fVP2Manager.
Referenced by SetFirstProfileId().
G4bool G4VAnalysisReader::SetFirstProfileId (G4int firstId)
Definition at line 263 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 263 of file G4VAnalysisReader.cc
References SetFirstP1Id(), and SetFirstP2Id().
void G4VAnalysisReader::SetH1Manager (G4VH1Manager * h1Manager) protected
Definition at line 65 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 65 of file G4VAnalysisReader.cc
References fVH1Manager.
Referenced by G4ToolsAnalysisReader::G4ToolsAnalysisReader().
void G4VAnalysisReader::SetH2Manager (G4VH2Manager * h2Manager) protected
Definition at line 71 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 71 of file G4VAnalysisReader.cc
References fVH2Manager.
Referenced by G4ToolsAnalysisReader::G4ToolsAnalysisReader().
void G4VAnalysisReader::SetH3Manager (G4VH3Manager * h3Manager) protected
Definition at line 77 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 77 of file G4VAnalysisReader.cc
References fVH3Manager.
Referenced by G4ToolsAnalysisReader::G4ToolsAnalysisReader().
G4bool G4VAnalysisReader::SetNtupleDColumn (const G4String & columnName, G4double & value)
Definition at line 331 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 331 of file G4VAnalysisReader.cc
References fVNtupleManager.
Referenced by XrayFluoAnalysisManager::LoadGunData().
G4bool G4VAnalysisReader::SetNtupleDColumn (const G4String & columnName, std::vector< double > & vector)
Definition at line 359 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 359 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleDColumn (G4int ntupleId, const G4String & columnName, G4double & value)
Definition at line 382 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 382 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleDColumn (G4int ntupleId, const G4String & columnName, std::vector< double > & vector)
Definition at line 414 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 414 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleFColumn (const G4String & columnName, G4float & value)
Definition at line 324 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 324 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleFColumn (const G4String & columnName, std::vector< float > & vector)
Definition at line 352 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 352 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleFColumn (G4int ntupleId, const G4String & columnName, G4float & value)
Definition at line 374 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 374 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleFColumn (G4int ntupleId, const G4String & columnName, std::vector< float > & vector)
Definition at line 406 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 406 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleIColumn (const G4String & columnName, G4int & value)
Definition at line 317 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 317 of file G4VAnalysisReader.cc
References fVNtupleManager.
Referenced by XrayFluoAnalysisManager::LoadGunData().
G4bool G4VAnalysisReader::SetNtupleIColumn (const G4String & columnName, std::vector< int > & vector)
Definition at line 345 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 345 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleIColumn (G4int ntupleId, const G4String & columnName, G4int & value)
Definition at line 366 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 366 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleIColumn (G4int ntupleId, const G4String & columnName, std::vector< int > & vector)
Definition at line 398 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 398 of file G4VAnalysisReader.cc
References fVNtupleManager.
void G4VAnalysisReader::SetNtupleManager (G4VRNtupleManager * ntupleManager) protected
Definition at line 95 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 95 of file G4VAnalysisReader.cc
References fVNtupleManager.
Referenced by G4CsvAnalysisReader::G4CsvAnalysisReader(), G4Hdf5AnalysisReader::G4Hdf5AnalysisReader(), G4RootAnalysisReader::G4RootAnalysisReader(), and G4XmlAnalysisReader::G4XmlAnalysisReader().
G4bool G4VAnalysisReader::SetNtupleSColumn (const G4String & columnName, G4String & value)
Definition at line 338 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 338 of file G4VAnalysisReader.cc
References fVNtupleManager.
G4bool G4VAnalysisReader::SetNtupleSColumn (G4int ntupleId, const G4String & columnName, G4String & value)
Definition at line 390 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 390 of file G4VAnalysisReader.cc
References fVNtupleManager.
void G4VAnalysisReader::SetP1Manager (G4VP1Manager * p1Manager) protected
Definition at line 83 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 83 of file G4VAnalysisReader.cc
References fVP1Manager.
Referenced by G4ToolsAnalysisReader::G4ToolsAnalysisReader().
void G4VAnalysisReader::SetP2Manager (G4VP2Manager * p2Manager) protected
Definition at line 89 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 89 of file G4VAnalysisReader.cc
References fVP2Manager.
Referenced by G4ToolsAnalysisReader::G4ToolsAnalysisReader().
void G4VAnalysisReader::SetVerboseLevel (G4int verboseLevel)
Definition at line 475 of file G4VAnalysisReader.cc.
View newest version in sPHENIX GitHub at line 475 of file G4VAnalysisReader.cc
References fState, and G4AnalysisManagerState::SetVerboseLevel().
Referenced by XrayFluoAnalysisManager::LoadGunData().
Member Data Documentation
std::unique_ptr<G4BaseFileManager> G4VAnalysisReader::fFileManager private
Definition at line 260 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 260 of file G4VAnalysisReader.hh
Referenced by GetFileName(), GetNtuple(), ReadH1(), ReadH2(), ReadH3(), ReadP1(), ReadP2(), SetFileManager(), and SetFileName().
G4AnalysisManagerState G4VAnalysisReader::fState protected
Definition at line 250 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 250 of file G4VAnalysisReader.hh
Referenced by G4CsvAnalysisReader::G4CsvAnalysisReader(), G4Hdf5AnalysisReader::G4Hdf5AnalysisReader(), G4RootAnalysisReader::G4RootAnalysisReader(), G4ToolsAnalysisReader::G4ToolsAnalysisReader(), G4XmlAnalysisReader::G4XmlAnalysisReader(), G4Hdf5AnalysisReader::ReadH1Impl(), G4RootAnalysisReader::ReadH1Impl(), G4CsvAnalysisReader::ReadH1Impl(), G4XmlAnalysisReader::ReadH1Impl(), G4CsvAnalysisReader::ReadH2Impl(), G4RootAnalysisReader::ReadH2Impl(), G4Hdf5AnalysisReader::ReadH2Impl(), G4XmlAnalysisReader::ReadH2Impl(), G4CsvAnalysisReader::ReadH3Impl(), G4RootAnalysisReader::ReadH3Impl(), G4Hdf5AnalysisReader::ReadH3Impl(), G4XmlAnalysisReader::ReadH3Impl(), G4Hdf5AnalysisReader::ReadNtupleImpl(), G4XmlAnalysisReader::ReadNtupleImpl(), G4CsvAnalysisReader::ReadNtupleImpl(), G4RootAnalysisReader::ReadNtupleImpl(), G4Hdf5AnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP1Impl(), G4CsvAnalysisReader::ReadP1Impl(), G4RootAnalysisReader::ReadP1Impl(), G4XmlAnalysisReader::ReadP2Impl(), G4CsvAnalysisReader::ReadP2Impl(), G4Hdf5AnalysisReader::ReadP2Impl(), G4RootAnalysisReader::ReadP2Impl(), SetVerboseLevel(), G4CsvAnalysisReader::~G4CsvAnalysisReader(), G4Hdf5AnalysisReader::~G4Hdf5AnalysisReader(), G4RootAnalysisReader::~G4RootAnalysisReader(), and G4XmlAnalysisReader::~G4XmlAnalysisReader().
std::unique_ptr<G4VH1Manager> G4VAnalysisReader::fVH1Manager private
Definition at line 254 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 254 of file G4VAnalysisReader.hh
Referenced by GetNofH1s(), SetFirstH1Id(), and SetH1Manager().
std::unique_ptr<G4VH2Manager> G4VAnalysisReader::fVH2Manager private
Definition at line 255 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 255 of file G4VAnalysisReader.hh
Referenced by GetNofH2s(), SetFirstH2Id(), and SetH2Manager().
std::unique_ptr<G4VH3Manager> G4VAnalysisReader::fVH3Manager private
Definition at line 256 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 256 of file G4VAnalysisReader.hh
Referenced by GetNofH3s(), SetFirstH3Id(), and SetH3Manager().
std::unique_ptr<G4VRNtupleManager> G4VAnalysisReader::fVNtupleManager private
Definition at line 259 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 259 of file G4VAnalysisReader.hh
Referenced by GetNofNtuples(), GetNtupleRow(), SetFirstNtupleId(), SetNtupleDColumn(), SetNtupleFColumn(), SetNtupleIColumn(), SetNtupleManager(), and SetNtupleSColumn().
std::unique_ptr<G4VP1Manager> G4VAnalysisReader::fVP1Manager private
Definition at line 257 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 257 of file G4VAnalysisReader.hh
Referenced by GetNofP1s(), SetFirstP1Id(), and SetP1Manager().
std::unique_ptr<G4VP2Manager> G4VAnalysisReader::fVP2Manager private
Definition at line 258 of file G4VAnalysisReader.hh.
View newest version in sPHENIX GitHub at line 258 of file G4VAnalysisReader.hh
Referenced by GetNofP2s(), SetFirstP2Id(), and SetP2Manager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/analysis/management/include/G4VAnalysisReader.hh
geant4/tree/geant4-10.6-release/source/analysis/management/src/G4VAnalysisReader.cc