ECCE @ EIC Software: G4UniformGravityField Class Reference
G4UniformGravityField Class Reference
#include <geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4UniformGravityField.hh>
Public Member Functions
G4UniformGravityField (const G4ThreeVector &FieldVector)
G4UniformGravityField (const G4double gy=-9.81 *CLHEP::m/CLHEP::s/CLHEP::s)
virtual ~G4UniformGravityField ()
G4UniformGravityField (const G4UniformGravityField &p)
G4UniformGravityField & operator= (const G4UniformGravityField &p)
G4bool DoesFieldChangeEnergy () const
virtual void GetFieldValue (const G4double Point[4], G4double *field) const
virtual G4Field * Clone () const
Public Member Functions inherited from G4Field
G4Field (G4bool gravityOn=false)
G4Field (const G4Field &)
virtual ~G4Field ()
G4Field & operator= (const G4Field &p)
G4bool IsGravityActive () const
void SetGravityActive (G4bool OnOffFlag)
Private Attributes
G4double fFieldComponents [3]
Additional Inherited Members
Static Public Attributes inherited from G4Field
static constexpr G4int MAX_NUMBER_OF_COMPONENTS = 24
Detailed Description
Definition at line 44 of file G4UniformGravityField.hh.
View newest version in sPHENIX GitHub at line 44 of file G4UniformGravityField.hh
Constructor & Destructor Documentation
G4UniformGravityField::G4UniformGravityField (const G4ThreeVector & FieldVector)
Definition at line 38 of file G4UniformGravityField.cc.
View newest version in sPHENIX GitHub at line 38 of file G4UniformGravityField.cc
References fFieldComponents, CLHEP::Hep3Vector::x(), CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Referenced by Clone().
G4UniformGravityField::G4UniformGravityField (const G4double gy = -9.81*CLHEP::m/CLHEP::s/CLHEP::s)
Definition at line 47 of file G4UniformGravityField.cc.
View newest version in sPHENIX GitHub at line 47 of file G4UniformGravityField.cc
References fFieldComponents.
G4UniformGravityField::~G4UniformGravityField () virtual
Definition at line 55 of file G4UniformGravityField.cc.
View newest version in sPHENIX GitHub at line 55 of file G4UniformGravityField.cc
G4UniformGravityField::G4UniformGravityField (const G4UniformGravityField & p)
Definition at line 59 of file G4UniformGravityField.cc.
View newest version in sPHENIX GitHub at line 59 of file G4UniformGravityField.cc
References fFieldComponents.
Member Function Documentation
G4Field * G4UniformGravityField::Clone () const virtual
Reimplemented from G4Field.
Definition at line 80 of file G4UniformGravityField.cc.
View newest version in sPHENIX GitHub at line 80 of file G4UniformGravityField.cc
References fFieldComponents, and G4UniformGravityField().
G4bool G4UniformGravityField::DoesFieldChangeEnergy () const inline virtual
Implements G4Field.
Definition at line 60 of file G4UniformGravityField.hh.
View newest version in sPHENIX GitHub at line 60 of file G4UniformGravityField.hh
void G4UniformGravityField::GetFieldValue (const G4double Point[4], G4double * field) const virtual
Implements G4Field.
Definition at line 89 of file G4UniformGravityField.cc.
View newest version in sPHENIX GitHub at line 89 of file G4UniformGravityField.cc
References fFieldComponents.
G4UniformGravityField & G4UniformGravityField::operator= (const G4UniformGravityField & p)
Definition at line 69 of file G4UniformGravityField.cc.
View newest version in sPHENIX GitHub at line 69 of file G4UniformGravityField.cc
References fFieldComponents, and G4Field::operator=().
Member Data Documentation
G4double G4UniformGravityField::fFieldComponents[3] private
Definition at line 69 of file G4UniformGravityField.hh.
View newest version in sPHENIX GitHub at line 69 of file G4UniformGravityField.hh
Referenced by Clone(), G4UniformGravityField(), GetFieldValue(), and operator=().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/include/G4UniformGravityField.hh
geant4/tree/geant4-10.6-release/source/geometry/magneticfield/src/G4UniformGravityField.cc