ECCE @ EIC Software: Par02TrackingAction Class Reference
Par02TrackingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02TrackingAction.hh>
Public Member Functions
Par02TrackingAction ()
A default constructor.
virtual ~Par02TrackingAction ()
virtual void PreUserTrackingAction (const G4Track *track)
virtual void PostUserTrackingAction (const G4Track *track)
Public Member Functions inherited from G4UserTrackingAction
G4UserTrackingAction ()
virtual ~G4UserTrackingAction ()
virtual void SetTrackingManagerPointer (G4TrackingManager *pValue)
Additional Inherited Members
Protected Attributes inherited from G4UserTrackingAction
G4TrackingManager * fpTrackingManager
Detailed Description
Tracking action (before/after track processing).
Defines the action at the start and at the end of processing of each track. The class needs to be set in G4RunManager::SetUserAction().
Author
Anna Zaborowska
Definition at line 42 of file Par02TrackingAction.hh.
View newest version in sPHENIX GitHub at line 42 of file Par02TrackingAction.hh
Constructor & Destructor Documentation
Par02TrackingAction::Par02TrackingAction ()
A default constructor.
Definition at line 47 of file Par02TrackingAction.cc.
View newest version in sPHENIX GitHub at line 47 of file Par02TrackingAction.cc
Par02TrackingAction::~Par02TrackingAction () virtual
Definition at line 51 of file Par02TrackingAction.cc.
View newest version in sPHENIX GitHub at line 51 of file Par02TrackingAction.cc
Member Function Documentation
void Par02TrackingAction::PostUserTrackingAction (const G4Track * track) virtual
Defines the actions at the end of processing the track. It saves the information of MC data (PDG code, initial momentum), tracker (momentum), EMCal and HCal (energy deposit and its position) as well as resolution and efficiency for all the detectors.
Reimplemented from G4UserTrackingAction.
Definition at line 66 of file Par02TrackingAction.cc.
View newest version in sPHENIX GitHub at line 66 of file Par02TrackingAction.cc
References Par02Output::eSaveEMCal, Par02Output::eSaveHCal, Par02Output::eSaveMC, Par02Output::eSaveTracker, fStopAndKill, G4Track::GetDynamicParticle(), Par02PrimaryParticleInformation::GetEMCalEfficiency(), Par02PrimaryParticleInformation::GetEMCalEnergy(), Par02PrimaryParticleInformation::GetEMCalPosition(), Par02PrimaryParticleInformation::GetEMCalResolution(), Par02PrimaryParticleInformation::GetHCalEfficiency(), Par02PrimaryParticleInformation::GetHCalEnergy(), Par02PrimaryParticleInformation::GetHCalPosition(), Par02PrimaryParticleInformation::GetHCalResolution(), Par02PrimaryParticleInformation::GetMCMomentum(), G4Track::GetParentID(), Par02PrimaryParticleInformation::GetPartID(), Par02PrimaryParticleInformation::GetPDG(), G4DynamicParticle::GetPrimaryParticle(), Par02PrimaryParticleInformation::GetTrackerEfficiency(), Par02PrimaryParticleInformation::GetTrackerMomentum(), Par02PrimaryParticleInformation::GetTrackerResolution(), G4Track::GetTrackStatus(), G4PrimaryParticle::GetUserInformation(), Par02Output::Instance(), MeV, mm, and Par02Output::SaveTrack().
void Par02TrackingAction::PreUserTrackingAction (const G4Track * track) virtual
Defines the actions at the start of processing the track. It checks the pseudorapidity range and if the particle is a primary.
Reimplemented from G4UserTrackingAction.
Definition at line 55 of file Par02TrackingAction.cc.
View newest version in sPHENIX GitHub at line 55 of file Par02TrackingAction.cc
References kdfinder::abs(), fStopAndKill, G4Track::GetMomentum(), MeV, CLHEP::Hep3Vector::perp(), and CLHEP::Hep3Vector::pseudoRapidity().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/include/Par02TrackingAction.hh
geant4/tree/geant4-10.6-release/examples/extended/parameterisations/Par02/src/Par02TrackingAction.cc