ECCE @ EIC Software: G4ErrorMatrix Class Reference
G4ErrorMatrix Class Reference
#include <geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorMatrix.hh>
Classes
class G4ErrorMatrix_row
class G4ErrorMatrix_row_const
Public Member Functions
G4ErrorMatrix ()
G4ErrorMatrix (G4int p, G4int q)
G4ErrorMatrix (G4int p, G4int q, G4int i)
G4ErrorMatrix (const G4ErrorMatrix &m1)
G4ErrorMatrix (const G4ErrorSymMatrix &m1)
virtual ~G4ErrorMatrix ()
virtual G4int num_row () const
virtual G4int num_col () const
virtual const G4double & operator() (G4int row, G4int col) const
virtual G4double & operator() (G4int row, G4int col)
G4ErrorMatrix & operator*= (G4double t)
G4ErrorMatrix & operator/= (G4double t)
G4ErrorMatrix & operator+= (const G4ErrorMatrix &m2)
G4ErrorMatrix & operator+= (const G4ErrorSymMatrix &m2)
G4ErrorMatrix & operator-= (const G4ErrorMatrix &m2)
G4ErrorMatrix & operator-= (const G4ErrorSymMatrix &m2)
G4ErrorMatrix & operator= (const G4ErrorMatrix &m2)
G4ErrorMatrix & operator= (const G4ErrorSymMatrix &m2)
G4ErrorMatrix operator- () const
G4ErrorMatrix apply (G4double(*f)(G4double, G4int, G4int)) const
G4ErrorMatrix T () const
G4ErrorMatrix sub (G4int min_row, G4int max_row, G4int min_col, G4int max_col) const
void sub (G4int row, G4int col, const G4ErrorMatrix &m1)
G4ErrorMatrix inverse (G4int &ierr) const
virtual void invert (G4int &ierr)
G4double determinant () const
G4double trace () const
G4ErrorMatrix_row operator[] (G4int)
const G4ErrorMatrix_row_const operator[] (G4int) const
Static Public Member Functions
static void error (const char *s)
Protected Member Functions
virtual G4int num_size () const
virtual void invertHaywood4 (G4int &ierr)
virtual void invertHaywood5 (G4int &ierr)
virtual void invertHaywood6 (G4int &ierr)
Private Member Functions
G4int dfact_matrix (G4double &det, G4int *ir)
G4int dfinv_matrix (G4int *ir)
Private Attributes
std::vector< G4double > m
G4int nrow
G4int ncol
G4int size
Friends
class G4ErrorMatrix_row
class G4ErrorMatrix_row_const
class G4ErrorSymMatrix
G4ErrorMatrix operator+ (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator- (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorSymMatrix &m1, const G4ErrorMatrix &m2)
G4ErrorMatrix operator* (const G4ErrorSymMatrix &m1, const G4ErrorSymMatrix &m2)
G4ErrorMatrix qr_solve (G4ErrorMatrix *, const G4ErrorMatrix &b)
void tridiagonal (G4ErrorSymMatrix *a, G4ErrorMatrix *hsm)
void row_house (G4ErrorMatrix *, const G4ErrorMatrix &, G4double, G4int, G4int, G4int, G4int)
void back_solve (const G4ErrorMatrix &R, G4ErrorMatrix *b)
void col_givens (G4ErrorMatrix *A, G4double c, G4double s, G4int k1, G4int k2, G4int rowmin, G4int rowmax)
void row_givens (G4ErrorMatrix *A, G4double c, G4double s, G4int k1, G4int k2, G4int colmin, G4int colmax)
void col_house (G4ErrorMatrix *, const G4ErrorMatrix &, G4double, G4int, G4int, G4int, G4int)
void house_with_update (G4ErrorMatrix *a, G4int row, G4int col)
void house_with_update (G4ErrorMatrix *a, G4ErrorMatrix *v, G4int row, G4int col)
void house_with_update2 (G4ErrorSymMatrix *a, G4ErrorMatrix *v, G4int row, G4int col)
Detailed Description
Definition at line 46 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 46 of file G4ErrorMatrix.hh
Constructor & Destructor Documentation
G4ErrorMatrix::G4ErrorMatrix ()
G4ErrorMatrix::G4ErrorMatrix (G4int p, G4int q)
Definition at line 73 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 73 of file G4ErrorMatrix.cc
References ncol, nrow, and size.
G4ErrorMatrix::G4ErrorMatrix (G4int p, G4int q, G4int i)
Definition at line 79 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 79 of file G4ErrorMatrix.cc
References a, b, error(), m, ncol, nrow, and size.
G4ErrorMatrix::G4ErrorMatrix (const G4ErrorMatrix & m1)
Definition at line 116 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 116 of file G4ErrorMatrix.cc
References m.
G4ErrorMatrix::G4ErrorMatrix (const G4ErrorSymMatrix & m1)
Definition at line 122 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 122 of file G4ErrorMatrix.cc
References k, G4ErrorSymMatrix::m, m, n, ncol, nrow, and size.
G4ErrorMatrix::~G4ErrorMatrix () virtual
Definition at line 112 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 112 of file G4ErrorMatrix.cc
Member Function Documentation
G4ErrorMatrix G4ErrorMatrix::apply (G4double(*)(G4double, G4int, G4int) f) const
Definition at line 389 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 389 of file G4ErrorMatrix.cc
References a, b, f, m, num_col(), and num_row().
G4double G4ErrorMatrix::determinant () const
Definition at line 775 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 775 of file G4ErrorMatrix.cc
References dfact_matrix(), error(), G4ThreadLocal, ncol, and nrow.
G4int G4ErrorMatrix::dfact_matrix (G4double & det, G4int * ir) private
Definition at line 517 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 517 of file G4ErrorMatrix.cc
References DBL_EPSILON, epsilon(), error(), k, m, n, ncol, CLHEP::normal(), nrow, and t.
Referenced by determinant(), G4ErrorSymMatrix::determinant(), and invert().
G4int G4ErrorMatrix::dfinv_matrix (G4int * ir) private
Definition at line 404 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 404 of file G4ErrorMatrix.cc
References error(), k, m, n, num_col(), and num_row().
Referenced by invert().
void G4ErrorMatrix::error (const char * s) static
Definition at line 804 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 804 of file G4ErrorMatrix.cc
References FatalException, G4Exception(), and message().
Referenced by determinant(), dfact_matrix(), dfinv_matrix(), G4ErrorMatrix(), G4ErrorSymMatrix::G4ErrorSymMatrix(), invert(), sub(), and G4ErrorSymMatrix::sub().
G4ErrorMatrix G4ErrorMatrix::inverse (G4int & ierr) const inline
void G4ErrorMatrix::invert (G4int & ierr) virtual
Definition at line 644 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 644 of file G4ErrorMatrix.cc
References dfact_matrix(), dfinv_matrix(), error(), G4ThreadLocal, invertHaywood4(), invertHaywood5(), invertHaywood6(), m, ncol, nrow, t1, and t2.
void G4ErrorMatrix::invertHaywood4 (G4int & ierr) protected virtual
Definition at line 910 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 910 of file G4ErrorMatrix.cc
References F00, F01, F02, F03, F10, F11, F12, F13, F20, F21, F22, F23, F30, F31, F32, F33, and m.
Referenced by invert().
void G4ErrorMatrix::invertHaywood5 (G4int & ierr) protected virtual
Definition at line 1009 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 1009 of file G4ErrorMatrix.cc
References m, M00, M01, M02, M03, M04, M10, M11, M12, M13, M14, M20, M21, M22, M23, M24, M30, M31, M32, M33, M34, M40, M41, M42, M43, and M44.
Referenced by invert().
void G4ErrorMatrix::invertHaywood6 (G4int & ierr) protected virtual
Definition at line 1232 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 1232 of file G4ErrorMatrix.cc
References A00, A01, A02, A03, A04, A05, A10, A11, A12, A13, A14, A15, A20, A21, A22, A23, A24, A25, A30, A31, A32, A33, A34, A35, A40, A41, A42, A43, A44, A45, A50, A51, A52, A53, A54, A55, and m.
Referenced by invert().
virtual G4int G4ErrorMatrix::num_col () const inline virtual
Referenced by apply(), dfinv_matrix(), dsum(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator<<(), G4ErrorSymMatrix::similarity(), G4ErrorSymMatrix::similarityT(), and sub().
virtual G4int G4ErrorMatrix::num_row () const inline virtual
Referenced by apply(), dfinv_matrix(), dsum(), operator*(), operator+(), operator+=(), operator-(), operator-=(), operator<<(), operator=(), G4ErrorSymMatrix::similarity(), and sub().
virtual G4int G4ErrorMatrix::num_size () const inline protected virtual
virtual const G4double& G4ErrorMatrix::operator() (G4int row, G4int col) const inline virtual
virtual G4double& G4ErrorMatrix::operator() (G4int row, G4int col) inline virtual
G4ErrorMatrix & G4ErrorMatrix::operator*= (G4double t)
Definition at line 325 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 325 of file G4ErrorMatrix.cc
References SIMPLE_UOP.
G4ErrorMatrix & G4ErrorMatrix::operator+= (const G4ErrorMatrix & m2)
Definition at line 305 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 305 of file G4ErrorMatrix.cc
References CHK_DIM_2, num_col(), num_row(), and SIMPLE_BOP.
G4ErrorMatrix & G4ErrorMatrix::operator+= (const G4ErrorSymMatrix & m2)
Definition at line 401 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 401 of file G4ErrorSymMatrix.cc
References CHK_DIM_2, k, G4ErrorSymMatrix::m, m, n, G4ErrorSymMatrix::num_col(), num_col(), G4ErrorSymMatrix::num_row(), and num_row().
G4ErrorMatrix G4ErrorMatrix::operator- () const
Definition at line 214 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 214 of file G4ErrorMatrix.cc
References a, b, e, m, ncol, and nrow.
G4ErrorMatrix & G4ErrorMatrix::operator-= (const G4ErrorMatrix & m2)
Definition at line 312 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 312 of file G4ErrorMatrix.cc
References CHK_DIM_2, num_col(), num_row(), and SIMPLE_BOP.
G4ErrorMatrix & G4ErrorMatrix::operator-= (const G4ErrorSymMatrix & m2)
Definition at line 433 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 433 of file G4ErrorSymMatrix.cc
References CHK_DIM_2, k, G4ErrorSymMatrix::m, m, n, G4ErrorSymMatrix::num_col(), num_col(), G4ErrorSymMatrix::num_row(), and num_row().
G4ErrorMatrix & G4ErrorMatrix::operator/= (G4double t)
Definition at line 319 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 319 of file G4ErrorMatrix.cc
References SIMPLE_UOP.
G4ErrorMatrix & G4ErrorMatrix::operator= (const G4ErrorMatrix & m2)
Definition at line 331 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 331 of file G4ErrorMatrix.cc
References m, ncol, nrow, and size.
G4ErrorMatrix & G4ErrorMatrix::operator= (const G4ErrorSymMatrix & m2)
Definition at line 477 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 477 of file G4ErrorSymMatrix.cc
References k, G4ErrorSymMatrix::m, m, n, ncol, G4ErrorSymMatrix::nrow, nrow, num_row(), and size.
G4ErrorMatrix_row G4ErrorMatrix::operator[] (G4int) inline
const G4ErrorMatrix_row_const G4ErrorMatrix::operator[] (G4int) const inline
G4ErrorMatrix G4ErrorMatrix::sub (G4int min_row, G4int max_row, G4int min_col, G4int max_col) const
Definition at line 154 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 154 of file G4ErrorMatrix.cc
References a, error(), m, num_col(), and num_row().
Referenced by dsum().
void G4ErrorMatrix::sub (G4int row, G4int col, const G4ErrorMatrix & m1)
Definition at line 176 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 176 of file G4ErrorMatrix.cc
References a, error(), m, num_col(), and num_row().
G4ErrorMatrix G4ErrorMatrix::T () const
Definition at line 373 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 373 of file G4ErrorMatrix.cc
References m, ncol, nrow, readPY::pl, pt, and size.
Referenced by G4ErrorFreeTrajState::PropagateError().
G4double G4ErrorMatrix::trace () const
Definition at line 794 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 794 of file G4ErrorMatrix.cc
References d, m, ncol, and t.
Friends And Related Function Documentation
void back_solve (const G4ErrorMatrix & R, G4ErrorMatrix * b) friend
void col_givens (G4ErrorMatrix * A, G4double c, G4double s, G4int k1, G4int k2, G4int rowmin, G4int rowmax) friend
void col_house (G4ErrorMatrix * , const G4ErrorMatrix & , G4double , G4int , G4int , G4int , G4int) friend
friend class G4ErrorMatrix_row friend
Definition at line 174 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ErrorMatrix.hh
friend class G4ErrorMatrix_row_const friend
Definition at line 175 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 175 of file G4ErrorMatrix.hh
friend class G4ErrorSymMatrix friend
Definition at line 176 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 176 of file G4ErrorMatrix.hh
void house_with_update (G4ErrorMatrix * a, G4int row, G4int col) friend
void house_with_update (G4ErrorMatrix * a, G4ErrorMatrix * v, G4int row, G4int col) friend
void house_with_update2 (G4ErrorSymMatrix * a, G4ErrorMatrix * v, G4int row, G4int col) friend
G4ErrorMatrix operator* (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 271 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 271 of file G4ErrorMatrix.cc
G4ErrorMatrix operator* (const G4ErrorMatrix & m1, const G4ErrorSymMatrix & m2) friend
Definition at line 286 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 286 of file G4ErrorSymMatrix.cc
G4ErrorMatrix operator* (const G4ErrorSymMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 320 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 320 of file G4ErrorSymMatrix.cc
G4ErrorMatrix operator* (const G4ErrorSymMatrix & m1, const G4ErrorSymMatrix & m2) friend
Definition at line 353 of file G4ErrorSymMatrix.cc.
View newest version in sPHENIX GitHub at line 353 of file G4ErrorSymMatrix.cc
G4ErrorMatrix operator+ (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 224 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 224 of file G4ErrorMatrix.cc
G4ErrorMatrix operator- (const G4ErrorMatrix & m1, const G4ErrorMatrix & m2) friend
Definition at line 236 of file G4ErrorMatrix.cc.
View newest version in sPHENIX GitHub at line 236 of file G4ErrorMatrix.cc
G4ErrorMatrix qr_solve (G4ErrorMatrix * , const G4ErrorMatrix & b) friend
void row_givens (G4ErrorMatrix * A, G4double c, G4double s, G4int k1, G4int k2, G4int colmin, G4int colmax) friend
void row_house (G4ErrorMatrix * , const G4ErrorMatrix & , G4double , G4int , G4int , G4int , G4int) friend
void tridiagonal (G4ErrorSymMatrix * a, G4ErrorMatrix * hsm) friend
Member Data Documentation
std::vector<G4double > G4ErrorMatrix::m private
Definition at line 224 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 224 of file G4ErrorMatrix.hh
Referenced by apply(), G4ErrorSymMatrix::assign(), dfact_matrix(), dfinv_matrix(), G4ErrorMatrix(), invert(), invertHaywood4(), invertHaywood5(), invertHaywood6(), operator*(), operator+=(), operator-(), operator-=(), operator=(), G4ErrorSymMatrix::similarity(), sub(), T(), and trace().
G4int G4ErrorMatrix::ncol private
Definition at line 226 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 226 of file G4ErrorMatrix.hh
Referenced by determinant(), dfact_matrix(), G4ErrorMatrix(), invert(), operator*(), operator+(), operator-(), operator=(), T(), and trace().
G4int G4ErrorMatrix::nrow private
Definition at line 226 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 226 of file G4ErrorMatrix.hh
Referenced by G4ErrorSymMatrix::assign(), determinant(), dfact_matrix(), G4ErrorMatrix(), invert(), operator*(), operator+(), operator-(), operator=(), and T().
G4int G4ErrorMatrix::size private
Definition at line 227 of file G4ErrorMatrix.hh.
View newest version in sPHENIX GitHub at line 227 of file G4ErrorMatrix.hh
Referenced by G4ErrorMatrix(), operator=(), and T().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/error_propagation/include/G4ErrorMatrix.hh
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorMatrix.cc
geant4/tree/geant4-10.6-release/source/error_propagation/src/G4ErrorSymMatrix.cc