ECCE @ EIC Software: G4ParticleHPNames Class Reference
G4ParticleHPNames Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPNames.hh>
Public Member Functions
G4ParticleHPNames ()
G4ParticleHPNames (G4int maxOffSet)
~G4ParticleHPNames ()
G4ParticleHPDataUsed GetName (G4int A, G4int Z, G4String base, G4String rest, G4bool &active)
G4ParticleHPDataUsed GetName (G4int A, G4int Z, G4int M, G4String base, G4String rest, G4bool &active)
G4String GetName (G4int i)
void SetMaxOffSet (G4int anOffset)
G4String itoa (int current)
Public Attributes
G4int theMaxOffSet
Static Public Attributes
static const G4String theString [100]
Detailed Description
Definition at line 39 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 39 of file G4ParticleHPNames.hh
Constructor & Destructor Documentation
G4ParticleHPNames::G4ParticleHPNames () inline
Definition at line 43 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 43 of file G4ParticleHPNames.hh
References theMaxOffSet.
G4ParticleHPNames::G4ParticleHPNames (G4int maxOffSet) inline
Definition at line 44 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 44 of file G4ParticleHPNames.hh
References theMaxOffSet.
G4ParticleHPNames::~G4ParticleHPNames () inline
Definition at line 45 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 45 of file G4ParticleHPNames.hh
Member Function Documentation
G4ParticleHPDataUsed G4ParticleHPNames::GetName (G4int A, G4int Z, G4String base, G4String rest, G4bool & active) inline
Definition at line 48 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 48 of file G4ParticleHPNames.hh
References GetName().
Referenced by G4ParticleHPJENDLHEData::BuildPhysicsTable(), GetName(), G4ParticleHPIsoData::GetName(), G4ParticleHPFFFissionFS::Init(), G4ParticleHPCaptureFS::Init(), G4ParticleHPFSFissionFS::Init(), G4ParticleHPFissionBaseFS::Init(), G4ParticleHPElasticFS::Init(), G4ParticleHPIsoData::Init(), G4ParticleHPInelasticBaseFS::Init(), G4ParticleHPInelasticCompFS::Init(), G4FissionLibrary::Init(), and G4WendtFissionFragmentGenerator::InitializeANucleus().
G4ParticleHPDataUsed G4ParticleHPNames::GetName (G4int A, G4int Z, G4int M, G4String base, G4String rest, G4bool & active)
Definition at line 70 of file G4ParticleHPNames.cc.
View newest version in sPHENIX GitHub at line 70 of file G4ParticleHPNames.cc
References A(), dir, file, G4cout, G4endl, G4ParticleHPDataUsed::GetA(), G4ParticleHPManager::GetDataStream2(), G4ParticleHPManager::GetInstance(), G4ParticleHPDataUsed::GetName(), G4ParticleHPManager::GetSkipMissingIsotopes(), G4ParticleHPManager::GetVerboseLevel(), G4ParticleHPDataUsed::GetZ(), G4SandiaTable::GetZtoA(), in, G4ParticleHPDataUsed::IsThisNaturalAbundance(), itoa(), G4ParticleHPDataUsed::SetA(), G4ParticleHPDataUsed::SetM(), G4ParticleHPDataUsed::SetName(), G4ParticleHPDataUsed::SetNaturalAbundanceFlag(), G4ParticleHPDataUsed::SetZ(), theMaxOffSet, theString, and Z.
G4String G4ParticleHPNames::GetName (G4int i)
Definition at line 67 of file G4ParticleHPNames.cc.
View newest version in sPHENIX GitHub at line 67 of file G4ParticleHPNames.cc
References theString.
G4String G4ParticleHPNames::itoa (int current) inline
Definition at line 57 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 57 of file G4ParticleHPNames.hh
Referenced by GetName().
void G4ParticleHPNames::SetMaxOffSet (G4int anOffset) inline
Definition at line 51 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 51 of file G4ParticleHPNames.hh
References theMaxOffSet.
Member Data Documentation
G4int G4ParticleHPNames::theMaxOffSet
Definition at line 56 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 56 of file G4ParticleHPNames.hh
Referenced by G4ParticleHPNames(), GetName(), and SetMaxOffSet().
const G4String G4ParticleHPNames::theString static
Initial value:
= {"Hydrogen", "Helium",
 "Lithium", "Berylium", "Boron", "Carbon", "Nitrogen", "Oxygen", "Fluorine",
 "Neon", "Sodium", "Magnesium", "Aluminum", "Silicon", "Phosphorous",
 "Sulfur", "Chlorine", "Argon", "Potassium", "Calcium", "Scandium",
 "Titanium", "Vanadium", "Chromium", "Manganese", "Iron", "Cobalt", "Nickel",
 "Copper", "Zinc", "Gallium", "Germanium", "Arsenic", "Selenium", "Bromine",
 "Krypton", "Rubidium", "Strontium", "Yttrium", "Zirconium", "Niobium",
 "Molybdenum", "Technetium", "Ruthenium", "Rhodium", "Palladium", "Silver",
 "Cadmium", "Indium", "Tin", "Antimony", "Tellurium", "Iodine", "Xenon",
 "Cesium", "Barium", "Lanthanum", "Cerium", "Praseodymium", "Neodymium",
 "Promethium", "Samarium", "Europium", "Gadolinium", "Terbium", "Dysprosium",
 "Holmium", "Erbium", "Thulium", "Ytterbium", "Lutetium", "Hafnium",
 "Tantalum", "Tungsten", "Rhenium", "Osmium", "Iridium", "Platinium", "Gold",
 "Mercury", "Thallium", "Lead", "Bismuth", "Polonium", "Astatine", "Radon",
 "Francium", "Radium", "Actinium", "Thorium", "Protactinium", "Uranium",
 "Neptunium", "Plutonium", "Americium", "Curium", "Berkelium", "Californium",
 "Einsteinium","Fermium"}
Definition at line 55 of file G4ParticleHPNames.hh.
View newest version in sPHENIX GitHub at line 55 of file G4ParticleHPNames.hh
Referenced by GetName(), and G4FissionProductYieldDist::MakeIsotopeName().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/include/G4ParticleHPNames.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/particle_hp/src/G4ParticleHPNames.cc