ECCE @ EIC Software: RE05MuonHit Class Reference
RE05MuonHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05MuonHit.hh>
Public Member Functions
RE05MuonHit ()
virtual ~RE05MuonHit ()
RE05MuonHit (const RE05MuonHit &right)
const RE05MuonHit & operator= (const RE05MuonHit &right)
G4bool operator== (const RE05MuonHit &right) const
void * operator new (size_t)
void operator delete (void *aHit)
virtual void Draw ()
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
virtual void Print ()
void SetEdep (G4double de)
void AddEdep (G4double de)
G4double GetEdep ()
void SetPos (G4ThreeVector xyz)
G4ThreeVector GetPos ()
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
Private Attributes
G4double fEdep
G4ThreeVector fPos
Static Private Attributes
static std::map< G4String,
G4AttDef > fAttDefs
Detailed Description
Definition at line 42 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 42 of file RE05MuonHit.hh
Constructor & Destructor Documentation
RE05MuonHit::RE05MuonHit ()
Definition at line 45 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 45 of file RE05MuonHit.cc
RE05MuonHit::~RE05MuonHit () virtual
Definition at line 51 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 51 of file RE05MuonHit.cc
RE05MuonHit::RE05MuonHit (const RE05MuonHit & right)
Definition at line 56 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 56 of file RE05MuonHit.cc
References fEdep, and fPos.
Member Function Documentation
void RE05MuonHit::AddEdep (G4double de) inline
Definition at line 68 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 68 of file RE05MuonHit.hh
References fEdep.
Referenced by RE05MuonSD::ProcessHits().
std::vector< G4AttValue > * RE05MuonHit::CreateAttValues () const virtual
Reimplemented from G4VHit.
Definition at line 112 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 112 of file RE05MuonHit.cc
void RE05MuonHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 83 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 83 of file RE05MuonHit.cc
References G4VVisManager::Draw(), G4VMarker::filled, fPos, G4VVisManager::GetConcreteInstance(), G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
const std::map< G4String, G4AttDef > * RE05MuonHit::GetAttDefs () const virtual
Reimplemented from G4VHit.
Definition at line 100 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 100 of file RE05MuonHit.cc
References fAttDefs.
G4double RE05MuonHit::GetEdep () inline
Definition at line 70 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 70 of file RE05MuonHit.hh
References fEdep.
G4ThreeVector RE05MuonHit::GetPos () inline
Definition at line 74 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 74 of file RE05MuonHit.hh
References fPos.
Referenced by RE05MuonSD::ProcessHits().
void RE05MuonHit::operator delete (void * aHit) inline
Definition at line 88 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 88 of file RE05MuonHit.hh
References RE05MuonHitAllocator.
void * RE05MuonHit::operator new (size_t) inline
Definition at line 82 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 82 of file RE05MuonHit.hh
References RE05MuonHitAllocator.
const RE05MuonHit & RE05MuonHit::operator= (const RE05MuonHit & right)
Definition at line 65 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 65 of file RE05MuonHit.cc
References fEdep, and fPos.
G4bool RE05MuonHit::operator== (const RE05MuonHit & right) const
Definition at line 74 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 74 of file RE05MuonHit.cc
void RE05MuonHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 124 of file RE05MuonHit.cc.
View newest version in sPHENIX GitHub at line 124 of file RE05MuonHit.cc
void RE05MuonHit::SetEdep (G4double de) inline
Definition at line 66 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 66 of file RE05MuonHit.hh
References fEdep.
Referenced by RE05MuonSD::ProcessHits().
void RE05MuonHit::SetPos (G4ThreeVector xyz) inline
Definition at line 72 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 72 of file RE05MuonHit.hh
References fPos.
Referenced by RE05MuonSD::ProcessHits().
Member Data Documentation
std::map< G4String, G4AttDef > RE05MuonHit::fAttDefs static private
Definition at line 63 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 63 of file RE05MuonHit.hh
Referenced by GetAttDefs().
G4double RE05MuonHit::fEdep private
Definition at line 61 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 61 of file RE05MuonHit.hh
Referenced by AddEdep(), GetEdep(), operator=(), RE05MuonHit(), and SetEdep().
G4ThreeVector RE05MuonHit::fPos private
Definition at line 62 of file RE05MuonHit.hh.
View newest version in sPHENIX GitHub at line 62 of file RE05MuonHit.hh
Referenced by Draw(), GetPos(), operator=(), RE05MuonHit(), and SetPos().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/include/RE05MuonHit.hh
geant4/tree/geant4-10.6-release/examples/extended/runAndEvent/RE05/src/RE05MuonHit.cc