ECCE @ EIC Software: G4HumanPhantomAnalysisManager Class Reference
G4HumanPhantomAnalysisManager Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4HumanPhantomAnalysisManager.hh>
Public Member Functions
G4HumanPhantomAnalysisManager ()
~G4HumanPhantomAnalysisManager ()
void book ()
void FillNtupleWithEnergyDeposition (G4int, G4double)
void save ()
Private Attributes
G4bool factoryOn
G4int fNtColId [MaxNtCol]
Detailed Description
Definition at line 46 of file G4HumanPhantomAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 46 of file G4HumanPhantomAnalysisManager.hh
Constructor & Destructor Documentation
G4HumanPhantomAnalysisManager::G4HumanPhantomAnalysisManager ()
Definition at line 38 of file G4HumanPhantomAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 38 of file G4HumanPhantomAnalysisManager.cc
References factoryOn, fNtColId, k, and MaxNtCol.
G4HumanPhantomAnalysisManager::~G4HumanPhantomAnalysisManager ()
Definition at line 49 of file G4HumanPhantomAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 49 of file G4HumanPhantomAnalysisManager.cc
Member Function Documentation
void G4HumanPhantomAnalysisManager::book ()
Definition at line 53 of file G4HumanPhantomAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 53 of file G4HumanPhantomAnalysisManager.cc
References G4VAnalysisManager::CreateNtupleDColumn(), factoryOn, G4VAnalysisManager::FinishNtuple(), fNtColId, G4cout, G4endl, G4ToolsAnalysisManager::Instance(), G4VAnalysisManager::OpenFile(), G4VAnalysisManager::SetFirstNtupleId(), G4VAnalysisManager::SetNtupleDirectoryName(), and G4VAnalysisManager::SetVerboseLevel().
void G4HumanPhantomAnalysisManager::FillNtupleWithEnergyDeposition (G4int organ, G4double energyDep)
Definition at line 86 of file G4HumanPhantomAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 86 of file G4HumanPhantomAnalysisManager.cc
References G4VAnalysisManager::AddNtupleRow(), G4VAnalysisManager::FillNtupleDColumn(), fNtColId, G4cout, G4endl, and G4ToolsAnalysisManager::Instance().
void G4HumanPhantomAnalysisManager::save ()
Definition at line 98 of file G4HumanPhantomAnalysisManager.cc.
View newest version in sPHENIX GitHub at line 98 of file G4HumanPhantomAnalysisManager.cc
References G4VAnalysisManager::CloseFile(), factoryOn, G4ToolsAnalysisManager::Instance(), and G4VAnalysisManager::Write().
Member Data Documentation
G4bool G4HumanPhantomAnalysisManager::factoryOn private
Definition at line 67 of file G4HumanPhantomAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 67 of file G4HumanPhantomAnalysisManager.hh
Referenced by book(), G4HumanPhantomAnalysisManager(), and save().
G4int G4HumanPhantomAnalysisManager::fNtColId[MaxNtCol] private
Definition at line 68 of file G4HumanPhantomAnalysisManager.hh.
View newest version in sPHENIX GitHub at line 68 of file G4HumanPhantomAnalysisManager.hh
Referenced by book(), FillNtupleWithEnergyDeposition(), and G4HumanPhantomAnalysisManager().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/include/G4HumanPhantomAnalysisManager.hh
geant4/tree/geant4-10.6-release/examples/advanced/human_phantom/src/G4HumanPhantomAnalysisManager.cc