ECCE @ EIC Software: G4tgrSolid Class Reference
G4tgrSolid Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrSolid.hh>
Public Member Functions
G4tgrSolid ()
G4tgrSolid (const std::vector< G4String > &wl)
virtual ~G4tgrSolid ()
const G4String & GetName () const
const G4String & GetType () const
const std::vector< std::vector
< G4double > * > GetSolidParams () const
virtual const G4String & GetRelativeRotMatName () const
virtual G4ThreeVector GetRelativePlace () const
Protected Attributes
G4String theName
G4String theType
std::vector< std::vector
< G4double > * > theSolidParams
Private Member Functions
void FillSolidParams (const std::vector< G4String > &wl)
Friends
std::ostream & operator<< (std::ostream &, const G4tgrSolid &)
Detailed Description
Definition at line 48 of file G4tgrSolid.hh.
View newest version in sPHENIX GitHub at line 48 of file G4tgrSolid.hh
Constructor & Destructor Documentation
G4tgrSolid::G4tgrSolid ()
Definition at line 46 of file G4tgrSolid.cc.
View newest version in sPHENIX GitHub at line 46 of file G4tgrSolid.cc
G4tgrSolid::G4tgrSolid (const std::vector< G4String > & wl)
Definition at line 58 of file G4tgrSolid.cc.
View newest version in sPHENIX GitHub at line 58 of file G4tgrSolid.cc
References FillSolidParams(), G4cout, G4endl, G4tgrVolumeMgr::GetInstance(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), G4tgrVolumeMgr::RegisterMe(), theName, and theType.
G4tgrSolid::~G4tgrSolid () virtual
Definition at line 52 of file G4tgrSolid.cc.
View newest version in sPHENIX GitHub at line 52 of file G4tgrSolid.cc
Member Function Documentation
void G4tgrSolid::FillSolidParams (const std::vector< G4String > & wl) private
Definition at line 104 of file G4tgrSolid.cc.
View newest version in sPHENIX GitHub at line 104 of file G4tgrSolid.cc
References deg, G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrMessenger::GetVerboseLevel(), and theSolidParams.
Referenced by G4tgrSolid().
const G4String& G4tgrSolid::GetName (void) const inline
Definition at line 60 of file G4tgrSolid.hh.
View newest version in sPHENIX GitHub at line 60 of file G4tgrSolid.hh
References theName.
Referenced by G4tgbVolume::FindOrConstructG4Solid(), G4tgrVolumeMgr::RegisterMe(), and G4tgrVolumeMgr::UnRegisterMe().
G4ThreeVector G4tgrSolid::GetRelativePlace () const virtual
Reimplemented in G4tgrSolidBoolean.
Definition at line 97 of file G4tgrSolid.cc.
View newest version in sPHENIX GitHub at line 97 of file G4tgrSolid.cc
const G4String & G4tgrSolid::GetRelativeRotMatName () const virtual
Reimplemented in G4tgrSolidBoolean.
Definition at line 90 of file G4tgrSolid.cc.
View newest version in sPHENIX GitHub at line 90 of file G4tgrSolid.cc
References theName.
Referenced by G4tgbVolume::FindOrConstructG4Solid().
const std::vector< std::vector< G4double > * > G4tgrSolid::GetSolidParams () const
Definition at line 83 of file G4tgrSolid.cc.
View newest version in sPHENIX GitHub at line 83 of file G4tgrSolid.cc
References theSolidParams.
Referenced by G4tgbVolume::FindOrConstructG4Solid().
const G4String& G4tgrSolid::GetType () const inline
Definition at line 61 of file G4tgrSolid.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgrSolid.hh
References theType.
Referenced by G4tgbVolume::FindOrConstructG4Solid().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrSolid & sol) friend
Definition at line 172 of file G4tgrSolid.cc.
View newest version in sPHENIX GitHub at line 172 of file G4tgrSolid.cc
Member Data Documentation
G4String G4tgrSolid::theName protected
Definition at line 72 of file G4tgrSolid.hh.
View newest version in sPHENIX GitHub at line 72 of file G4tgrSolid.hh
Referenced by G4tgrSolid(), G4tgrSolidBoolean::G4tgrSolidBoolean(), GetName(), GetRelativeRotMatName(), and operator<<().
std::vector< std::vector<G4double>* > G4tgrSolid::theSolidParams protected
Definition at line 76 of file G4tgrSolid.hh.
View newest version in sPHENIX GitHub at line 76 of file G4tgrSolid.hh
Referenced by FillSolidParams(), GetSolidParams(), and operator<<().
G4String G4tgrSolid::theType protected
Definition at line 74 of file G4tgrSolid.hh.
View newest version in sPHENIX GitHub at line 74 of file G4tgrSolid.hh
Referenced by G4tgrSolid(), G4tgrSolidBoolean::G4tgrSolidBoolean(), GetType(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrSolid.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrSolid.cc