ECCE @ EIC Software: G4tgrPlaceSimple Class Reference
G4tgrPlaceSimple Class Reference
#include <geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrPlaceSimple.hh>
Public Member Functions
G4tgrPlaceSimple ()
~G4tgrPlaceSimple ()
G4tgrPlaceSimple (const std::vector< G4String > &wl)
const G4String & GetRotMatName () const
G4ThreeVector GetPlacement () const
Public Member Functions inherited from G4tgrPlace
G4tgrPlace ()
virtual ~G4tgrPlace ()
const G4String & GetParentName () const
G4tgrVolume * GetVolume () const
unsigned int GetCopyNo () const
const G4String & GetType () const
void SetVolume (G4tgrVolume *vol)
void SetType (const G4String &typ)
Protected Attributes
G4ThreeVector thePlace
G4String theRotMatName
Protected Attributes inherited from G4tgrPlace
G4tgrVolume * theVolume
G4String theParentName
unsigned int theCopyNo
G4String theType
Friends
std::ostream & operator<< (std::ostream &os, const G4tgrPlaceSimple &obj)
Detailed Description
Definition at line 50 of file G4tgrPlaceSimple.hh.
View newest version in sPHENIX GitHub at line 50 of file G4tgrPlaceSimple.hh
Constructor & Destructor Documentation
G4tgrPlaceSimple::G4tgrPlaceSimple ()
Definition at line 43 of file G4tgrPlaceSimple.cc.
View newest version in sPHENIX GitHub at line 43 of file G4tgrPlaceSimple.cc
G4tgrPlaceSimple::~G4tgrPlaceSimple ()
Definition at line 49 of file G4tgrPlaceSimple.cc.
View newest version in sPHENIX GitHub at line 49 of file G4tgrPlaceSimple.cc
G4tgrPlaceSimple::G4tgrPlaceSimple (const std::vector< G4String > & wl)
Definition at line 55 of file G4tgrPlaceSimple.cc.
View newest version in sPHENIX GitHub at line 55 of file G4tgrPlaceSimple.cc
References G4cout, G4endl, G4tgrUtils::GetDouble(), G4tgrUtils::GetInt(), G4tgrUtils::GetString(), G4tgrMessenger::GetVerboseLevel(), mm, G4tgrPlace::theCopyNo, G4tgrPlace::theParentName, thePlace, theRotMatName, and G4tgrPlace::theType.
Member Function Documentation
G4ThreeVector G4tgrPlaceSimple::GetPlacement () const inline virtual
Reimplemented from G4tgrPlace.
Definition at line 62 of file G4tgrPlaceSimple.hh.
View newest version in sPHENIX GitHub at line 62 of file G4tgrPlaceSimple.hh
References thePlace.
const G4String& G4tgrPlaceSimple::GetRotMatName () const inline
Definition at line 61 of file G4tgrPlaceSimple.hh.
View newest version in sPHENIX GitHub at line 61 of file G4tgrPlaceSimple.hh
References theRotMatName.
Referenced by G4tgbVolume::ConstructG4PhysVol().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const G4tgrPlaceSimple & obj) friend
Definition at line 88 of file G4tgrPlaceSimple.cc.
View newest version in sPHENIX GitHub at line 88 of file G4tgrPlaceSimple.cc
Member Data Documentation
G4ThreeVector G4tgrPlaceSimple::thePlace protected
Definition at line 68 of file G4tgrPlaceSimple.hh.
View newest version in sPHENIX GitHub at line 68 of file G4tgrPlaceSimple.hh
Referenced by G4tgrPlaceSimple(), GetPlacement(), and operator<<().
G4String G4tgrPlaceSimple::theRotMatName protected
Definition at line 71 of file G4tgrPlaceSimple.hh.
View newest version in sPHENIX GitHub at line 71 of file G4tgrPlaceSimple.hh
Referenced by G4tgrPlaceSimple(), GetRotMatName(), and operator<<().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/persistency/ascii/include/G4tgrPlaceSimple.hh
geant4/tree/geant4-10.6-release/source/persistency/ascii/src/G4tgrPlaceSimple.cc