ECCE @ EIC Software: G4ParallelGeometriesLimiterProcess Class Reference
G4ParallelGeometriesLimiterProcess Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4ParallelGeometriesLimiterProcess.hh>
Public Member Functions
G4ParallelGeometriesLimiterProcess (const G4String &processName="biasLimiter")
virtual ~G4ParallelGeometriesLimiterProcess ()
void AddParallelWorld (const G4String &parallelWorldName)
void RemoveParallelWorld (const G4String &parallelWorldName)
const std::vector
< G4VPhysicalVolume * > & GetParallelWorlds () const
G4int GetParallelWorldIndex (const G4VPhysicalVolume *parallelWorld) const
G4int GetParallelWorldIndex (G4String parallelWorldName) const
const std::vector< G4Navigator * > & GetActiveNavigators () const
const G4Navigator * GetNavigator (G4int worldIndex) const
const std::vector< const
G4VPhysicalVolume * > & GetCurrentVolumes () const
const std::vector< const
G4VPhysicalVolume * > & GetPreviousVolumes () const
const G4VPhysicalVolume * GetCurrentVolume (G4int worldIndex) const
const G4VPhysicalVolume * GetPreviousVolume (G4int worldIndex) const
const std::vector< G4bool > & GetIsLimiting () const
const std::vector< G4bool > & GetWasLimiting () const
G4bool GetIsLimiting (G4int worldIndex) const
G4bool GetWasLimiting (G4int worldIndex) const
void StartTracking (G4Track *)
void EndTracking ()
G4double PostStepGetPhysicalInteractionLength (const G4Track &, G4double, G4ForceCondition *)
G4VParticleChange * PostStepDoIt (const G4Track &, const G4Step &)
G4double AlongStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4VParticleChange * AlongStepDoIt (const G4Track &track, const G4Step &step)
G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
virtual void SetProcessManager (const G4ProcessManager *)
Public Member Functions inherited from G4VProcess
G4VProcess (const G4String &aName="NoName", G4ProcessType aType=fNotDefined)
G4VProcess (const G4VProcess &right)
virtual ~G4VProcess ()
G4bool operator== (const G4VProcess &right) const
G4bool operator!= (const G4VProcess &right) const
G4double GetCurrentInteractionLength () const
void SetPILfactor (G4double value)
G4double GetPILfactor () const
G4double AlongStepGPIL (const G4Track &track, G4double previousStepSize, G4double currentMinimumStep, G4double &proposedSafety, G4GPILSelection *selection)
G4double AtRestGPIL (const G4Track &track, G4ForceCondition *condition)
G4double PostStepGPIL (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4bool IsApplicable (const G4ParticleDefinition &)
virtual void BuildPhysicsTable (const G4ParticleDefinition &)
virtual void PreparePhysicsTable (const G4ParticleDefinition &)
virtual G4bool StorePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
virtual G4bool RetrievePhysicsTable (const G4ParticleDefinition *, const G4String &, G4bool)
const G4String & GetPhysicsTableFileName (const G4ParticleDefinition *, const G4String &directory, const G4String &tableName, G4bool ascii=false)
const G4String & GetProcessName () const
G4ProcessType GetProcessType () const
void SetProcessType (G4ProcessType)
G4int GetProcessSubType () const
void SetProcessSubType (G4int)
virtual const G4ProcessManager * GetProcessManager ()
virtual void ResetNumberOfInteractionLengthLeft ()
G4double GetNumberOfInteractionLengthLeft () const
G4double GetTotalNumberOfInteractionLengthTraversed () const
G4bool isAtRestDoItIsEnabled () const
G4bool isAlongStepDoItIsEnabled () const
G4bool isPostStepDoItIsEnabled () const
virtual void DumpInfo () const
virtual void ProcessDescription (std::ostream &outfile) const
void SetVerboseLevel (G4int value)
G4int GetVerboseLevel () const
virtual void SetMasterProcess (G4VProcess *masterP)
const G4VProcess * GetMasterProcess () const
virtual void BuildWorkerPhysicsTable (const G4ParticleDefinition &part)
virtual void PrepareWorkerPhysicsTable (const G4ParticleDefinition &)
Private Attributes
std::vector< G4VPhysicalVolume * > fParallelWorlds
std::vector< G4Navigator * > fParallelWorldNavigators
std::vector< G4int > fParallelWorldNavigatorIndeces
std::vector< G4double > fParallelWorldSafeties
std::vector< G4bool > fParallelWorldIsLimiting
std::vector< G4bool > fParallelWorldWasLimiting
std::vector< const
G4VPhysicalVolume * > fCurrentVolumes
std::vector< const
G4VPhysicalVolume * > fPreviousVolumes
G4double fParallelWorldSafety
G4bool fIsTrackingTime
G4FieldTrack fFieldTrack
G4ParticleChangeForNothing fDummyParticleChange
G4PathFinder * fPathFinder
G4TransportationManager * fTransportationManager
Additional Inherited Members
Static Public Member Functions inherited from G4VProcess
static const G4String & GetProcessTypeName (G4ProcessType)
Protected Member Functions inherited from G4VProcess
void SubtractNumberOfInteractionLengthLeft (G4double previousStepSize)
void ClearNumberOfInteractionLengthLeft ()
Protected Attributes inherited from G4VProcess
const G4ProcessManager * aProcessManager
G4VParticleChange * pParticleChange
G4ParticleChange aParticleChange
G4double theNumberOfInteractionLengthLeft
G4double currentInteractionLength
G4double theInitialNumberOfInteractionLength
G4String theProcessName
G4String thePhysicsTableFileName
G4ProcessType theProcessType
G4int theProcessSubType
G4double thePILfactor
G4bool enableAtRestDoIt
G4bool enableAlongStepDoIt
G4bool enablePostStepDoIt
G4int verboseLevel
Detailed Description
Definition at line 61 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 61 of file G4ParallelGeometriesLimiterProcess.hh
Constructor & Destructor Documentation
G4ParallelGeometriesLimiterProcess::G4ParallelGeometriesLimiterProcess (const G4String & processName = "biasLimiter")
Definition at line 40 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 40 of file G4ParallelGeometriesLimiterProcess.cc
References fPathFinder, fTransportationManager, G4PathFinder::GetInstance(), and G4TransportationManager::GetTransportationManager().
virtual G4ParallelGeometriesLimiterProcess::~G4ParallelGeometriesLimiterProcess () inline virtual
Definition at line 70 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 70 of file G4ParallelGeometriesLimiterProcess.hh
Member Function Documentation
void G4ParallelGeometriesLimiterProcess::AddParallelWorld (const G4String & parallelWorldName)
Definition at line 56 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 56 of file G4ParallelGeometriesLimiterProcess.cc
References FatalException, fIsTrackingTime, fParallelWorlds, fTransportationManager, G4endl, G4Exception(), G4TransportationManager::GetNavigatorForTracking(), G4VProcess::GetProcessName(), G4Navigator::GetWorldVolume(), G4TransportationManager::IsWorldExisting(), and JustWarning.
Referenced by G4GenericBiasingPhysics::AssociateParallelGeometries().
G4VParticleChange * G4ParallelGeometriesLimiterProcess::AlongStepDoIt (const G4Track & track, const G4Step & step) virtual
Implements G4VProcess.
Definition at line 370 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 370 of file G4ParallelGeometriesLimiterProcess.cc
References fDummyParticleChange, and G4ParticleChangeForNothing::Initialize().
G4double G4ParallelGeometriesLimiterProcess::AlongStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4double currentMinimumStep, G4double & proposedSafety, G4GPILSelection * selection) virtual
Implements G4VProcess.
Definition at line 253 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 253 of file G4ParallelGeometriesLimiterProcess.cc
References CandidateForSelection, G4PathFinder::ComputeStep(), DBL_MAX, fFieldTrack, fParallelWorldIsLimiting, fParallelWorldNavigatorIndeces, fParallelWorldNavigators, fParallelWorldSafeties, fParallelWorldSafety, fPathFinder, G4ThreadLocal, G4Track::GetCurrentStepNumber(), G4Track::GetVolume(), kDoNot, kSharedOther, kSharedTransport, kUnique, NotCandidateForSelection, and G4FieldTrackUpdator::Update().
G4VParticleChange* G4ParallelGeometriesLimiterProcess::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 156 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 156 of file G4ParallelGeometriesLimiterProcess.hh
G4double G4ParallelGeometriesLimiterProcess::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Implements G4VProcess.
Definition at line 152 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 152 of file G4ParallelGeometriesLimiterProcess.hh
References DBL_MAX.
void G4ParallelGeometriesLimiterProcess::EndTracking () virtual
Reimplemented from G4VProcess.
Definition at line 228 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 228 of file G4ParallelGeometriesLimiterProcess.cc
References G4TransportationManager::DeActivateNavigator(), fIsTrackingTime, fParallelWorldNavigators, and fTransportationManager.
const std::vector< G4Navigator* >& G4ParallelGeometriesLimiterProcess::GetActiveNavigators () const inline
Definition at line 94 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 94 of file G4ParallelGeometriesLimiterProcess.hh
References fParallelWorldNavigators.
const G4VPhysicalVolume* G4ParallelGeometriesLimiterProcess::GetCurrentVolume (G4int worldIndex) const inline
Definition at line 111 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 111 of file G4ParallelGeometriesLimiterProcess.hh
References fCurrentVolumes.
const std::vector< const G4VPhysicalVolume* >& G4ParallelGeometriesLimiterProcess::GetCurrentVolumes () const inline
Definition at line 107 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 107 of file G4ParallelGeometriesLimiterProcess.hh
References fCurrentVolumes.
Referenced by G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength().
const std::vector< G4bool >& G4ParallelGeometriesLimiterProcess::GetIsLimiting () const inline
Definition at line 114 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 114 of file G4ParallelGeometriesLimiterProcess.hh
References fParallelWorldIsLimiting.
Referenced by GB06BOptnSplitAndKillByImportance::GenerateBiasingFinalState().
G4bool G4ParallelGeometriesLimiterProcess::GetIsLimiting (G4int worldIndex) const inline
Definition at line 118 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 118 of file G4ParallelGeometriesLimiterProcess.hh
References fParallelWorldIsLimiting.
const G4Navigator* G4ParallelGeometriesLimiterProcess::GetNavigator (G4int worldIndex) const inline
Definition at line 97 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 97 of file G4ParallelGeometriesLimiterProcess.hh
References fParallelWorldNavigators.
Referenced by StartTracking().
G4int G4ParallelGeometriesLimiterProcess::GetParallelWorldIndex (const G4VPhysicalVolume * parallelWorld) const
Definition at line 406 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 406 of file G4ParallelGeometriesLimiterProcess.cc
References fParallelWorlds, and Acts::Test::world.
Referenced by GetParallelWorldIndex(), and GB06BOptrSplitAndKillByImportance::StartRun().
G4int G4ParallelGeometriesLimiterProcess::GetParallelWorldIndex (G4String parallelWorldName) const
Definition at line 423 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 423 of file G4ParallelGeometriesLimiterProcess.cc
References fTransportationManager, GetParallelWorldIndex(), and G4TransportationManager::IsWorldExisting().
const std::vector< G4VPhysicalVolume* >& G4ParallelGeometriesLimiterProcess::GetParallelWorlds () const inline
Definition at line 80 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 80 of file G4ParallelGeometriesLimiterProcess.hh
References fParallelWorlds.
const G4VPhysicalVolume* G4ParallelGeometriesLimiterProcess::GetPreviousVolume (G4int worldIndex) const inline
Definition at line 112 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 112 of file G4ParallelGeometriesLimiterProcess.hh
References fPreviousVolumes.
const std::vector< const G4VPhysicalVolume* >& G4ParallelGeometriesLimiterProcess::GetPreviousVolumes () const inline
Definition at line 108 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 108 of file G4ParallelGeometriesLimiterProcess.hh
References fPreviousVolumes.
const std::vector< G4bool >& G4ParallelGeometriesLimiterProcess::GetWasLimiting () const inline
Definition at line 115 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 115 of file G4ParallelGeometriesLimiterProcess.hh
References fParallelWorldWasLimiting.
Referenced by G4BiasingProcessInterface::PostStepGetPhysicalInteractionLength().
G4bool G4ParallelGeometriesLimiterProcess::GetWasLimiting (G4int worldIndex) const inline
Definition at line 119 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 119 of file G4ParallelGeometriesLimiterProcess.hh
References fParallelWorldWasLimiting.
G4VParticleChange* G4ParallelGeometriesLimiterProcess::PostStepDoIt (const G4Track & , const G4Step &) inline virtual
Implements G4VProcess.
Definition at line 135 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 135 of file G4ParallelGeometriesLimiterProcess.hh
G4double G4ParallelGeometriesLimiterProcess::PostStepGetPhysicalInteractionLength (const G4Track & , G4double , G4ForceCondition * condition) virtual
Implements G4VProcess.
Definition at line 236 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 236 of file G4ParallelGeometriesLimiterProcess.cc
References DBL_MAX, fCurrentVolumes, fParallelWorldIsLimiting, fParallelWorldNavigatorIndeces, fParallelWorldWasLimiting, fPathFinder, fPreviousVolumes, G4PathFinder::GetLocatedVolume(), and NotForced.
void G4ParallelGeometriesLimiterProcess::RemoveParallelWorld (const G4String & parallelWorldName)
Definition at line 126 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 126 of file G4ParallelGeometriesLimiterProcess.cc
References fIsTrackingTime, fParallelWorlds, fTransportationManager, G4endl, G4Exception(), G4VProcess::GetProcessName(), G4TransportationManager::IsWorldExisting(), and JustWarning.
void G4ParallelGeometriesLimiterProcess::SetProcessManager (const G4ProcessManager * mgr) virtual
Reimplemented from G4VProcess.
Definition at line 379 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 379 of file G4ParallelGeometriesLimiterProcess.cc
References G4BiasingProcessSharedData::fParallelGeometriesLimiterProcess, G4BiasingProcessSharedData::fSharedDataMap, G4endl, G4Exception(), G4ParticleDefinition::GetParticleName(), G4ProcessManager::GetParticleType(), and JustWarning.
void G4ParallelGeometriesLimiterProcess::StartTracking (G4Track * track) virtual
Reimplemented from G4VProcess.
Definition at line 193 of file G4ParallelGeometriesLimiterProcess.cc.
View newest version in sPHENIX GitHub at line 193 of file G4ParallelGeometriesLimiterProcess.cc
References G4TransportationManager::ActivateNavigator(), fCurrentVolumes, fIsTrackingTime, fParallelWorldIsLimiting, fParallelWorldNavigatorIndeces, fParallelWorldNavigators, fParallelWorlds, fParallelWorldSafeties, fParallelWorldSafety, fParallelWorldWasLimiting, fPathFinder, fPreviousVolumes, fTransportationManager, G4PathFinder::GetLocatedVolume(), G4Track::GetMomentumDirection(), GetNavigator(), G4Track::GetPosition(), and G4PathFinder::PrepareNewTrack().
Member Data Documentation
std::vector< const G4VPhysicalVolume* > G4ParallelGeometriesLimiterProcess::fCurrentVolumes private
Definition at line 172 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 172 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by GetCurrentVolume(), GetCurrentVolumes(), PostStepGetPhysicalInteractionLength(), and StartTracking().
G4ParticleChangeForNothing G4ParallelGeometriesLimiterProcess::fDummyParticleChange private
Definition at line 177 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 177 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AlongStepDoIt().
G4FieldTrack G4ParallelGeometriesLimiterProcess::fFieldTrack private
Definition at line 176 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 176 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength().
G4bool G4ParallelGeometriesLimiterProcess::fIsTrackingTime private
Definition at line 175 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 175 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AddParallelWorld(), EndTracking(), RemoveParallelWorld(), and StartTracking().
std::vector< G4bool > G4ParallelGeometriesLimiterProcess::fParallelWorldIsLimiting private
Definition at line 170 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 170 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), GetIsLimiting(), PostStepGetPhysicalInteractionLength(), and StartTracking().
std::vector< G4int > G4ParallelGeometriesLimiterProcess::fParallelWorldNavigatorIndeces private
Definition at line 168 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 168 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), PostStepGetPhysicalInteractionLength(), and StartTracking().
std::vector< G4Navigator* > G4ParallelGeometriesLimiterProcess::fParallelWorldNavigators private
Definition at line 167 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 167 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), EndTracking(), GetActiveNavigators(), GetNavigator(), and StartTracking().
std::vector< G4VPhysicalVolume* > G4ParallelGeometriesLimiterProcess::fParallelWorlds private
Definition at line 166 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 166 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AddParallelWorld(), GetParallelWorldIndex(), GetParallelWorlds(), RemoveParallelWorld(), and StartTracking().
std::vector< G4double > G4ParallelGeometriesLimiterProcess::fParallelWorldSafeties private
Definition at line 169 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 169 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
G4double G4ParallelGeometriesLimiterProcess::fParallelWorldSafety private
Definition at line 174 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 174 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), and StartTracking().
std::vector< G4bool > G4ParallelGeometriesLimiterProcess::fParallelWorldWasLimiting private
Definition at line 171 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 171 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by GetWasLimiting(), PostStepGetPhysicalInteractionLength(), and StartTracking().
G4PathFinder* G4ParallelGeometriesLimiterProcess::fPathFinder private
Definition at line 178 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 178 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AlongStepGetPhysicalInteractionLength(), G4ParallelGeometriesLimiterProcess(), PostStepGetPhysicalInteractionLength(), and StartTracking().
std::vector< const G4VPhysicalVolume* > G4ParallelGeometriesLimiterProcess::fPreviousVolumes private
Definition at line 173 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 173 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by GetPreviousVolume(), GetPreviousVolumes(), PostStepGetPhysicalInteractionLength(), and StartTracking().
G4TransportationManager* G4ParallelGeometriesLimiterProcess::fTransportationManager private
Definition at line 179 of file G4ParallelGeometriesLimiterProcess.hh.
View newest version in sPHENIX GitHub at line 179 of file G4ParallelGeometriesLimiterProcess.hh
Referenced by AddParallelWorld(), EndTracking(), G4ParallelGeometriesLimiterProcess(), GetParallelWorldIndex(), RemoveParallelWorld(), and StartTracking().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/include/G4ParallelGeometriesLimiterProcess.hh
geant4/tree/geant4-10.6-release/source/processes/biasing/generic/src/G4ParallelGeometriesLimiterProcess.cc