ECCE @ EIC Software: CCalSteppingAction Class Reference
CCalSteppingAction Class Reference
#include <geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSteppingAction.hh>
Public Member Functions
CCalSteppingAction ()
virtual ~CCalSteppingAction ()
virtual void UserSteppingAction (const G4Step *aStep)
void endOfEvent ()
Public Member Functions inherited from G4UserSteppingAction
G4UserSteppingAction ()
virtual ~G4UserSteppingAction ()
virtual void SetSteppingManagerPointer (G4SteppingManager *pValue)
Private Attributes
G4float LateralProfile [70]
G4float timeDeposit [200]
G4int timeHistoMaxBin
Additional Inherited Members
Protected Attributes inherited from G4UserSteppingAction
G4SteppingManager * fpSteppingManager
Detailed Description
Definition at line 38 of file CCalSteppingAction.hh.
View newest version in sPHENIX GitHub at line 38 of file CCalSteppingAction.hh
Constructor & Destructor Documentation
CCalSteppingAction::CCalSteppingAction ()
Definition at line 44 of file CCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 44 of file CCalSteppingAction.cc
References LateralProfile, timeDeposit, and timeHistoMaxBin.
CCalSteppingAction::~CCalSteppingAction () virtual
Definition at line 51 of file CCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 51 of file CCalSteppingAction.cc
Member Function Documentation
void CCalSteppingAction::endOfEvent ()
Definition at line 87 of file CCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 87 of file CCalSteppingAction.cc
References G4VAnalysisManager::FillH1(), G4cout, G4endl, G4VAnalysisManager::GetH1Id(), G4ToolsAnalysisManager::Instance(), LateralProfile, t, timeDeposit, and timeHistoMaxBin.
Referenced by CCalEventAction::EndOfEventAction().
void CCalSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Reimplemented from G4UserSteppingAction.
Definition at line 54 of file CCalSteppingAction.cc.
View newest version in sPHENIX GitHub at line 54 of file CCalSteppingAction.cc
References cm, CLHEP::eV, G4StepPoint::GetGlobalTime(), G4StepPoint::GetPosition(), G4Step::GetPostStepPoint(), G4Step::GetPreStepPoint(), G4Step::GetTotalEnergyDeposit(), CLHEP::GeV, it, LateralProfile, max, min, nanosecond, Acts::VectorHelpers::perp(), Acts::VectorHelpers::time(), timeDeposit, timeHistoMaxBin, CLHEP::Hep3Vector::y(), and CLHEP::Hep3Vector::z().
Member Data Documentation
G4float CCalSteppingAction::LateralProfile[70] private
Definition at line 50 of file CCalSteppingAction.hh.
View newest version in sPHENIX GitHub at line 50 of file CCalSteppingAction.hh
Referenced by CCalSteppingAction(), endOfEvent(), and UserSteppingAction().
G4float CCalSteppingAction::timeDeposit[200] private
Definition at line 51 of file CCalSteppingAction.hh.
View newest version in sPHENIX GitHub at line 51 of file CCalSteppingAction.hh
Referenced by CCalSteppingAction(), endOfEvent(), and UserSteppingAction().
G4int CCalSteppingAction::timeHistoMaxBin private
Definition at line 52 of file CCalSteppingAction.hh.
View newest version in sPHENIX GitHub at line 52 of file CCalSteppingAction.hh
Referenced by CCalSteppingAction(), endOfEvent(), and UserSteppingAction().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/include/CCalSteppingAction.hh
geant4/tree/geant4-10.6-release/examples/advanced/composite_calorimeter/src/CCalSteppingAction.cc