ECCE @ EIC Software: ExN02TrackerHit Class Reference
ExN02TrackerHit Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/ExN02TrackerHit.hh>
Public Member Functions
ExN02TrackerHit ()
~ExN02TrackerHit ()
ExN02TrackerHit (const ExN02TrackerHit &)
const ExN02TrackerHit & operator= (const ExN02TrackerHit &)
G4bool operator== (const ExN02TrackerHit &) const
void * operator new (size_t)
void operator delete (void *)
void Draw ()
void Print ()
void SetTrackID (G4int track)
void SetChamberNb (G4int chamb)
void SetEdep (G4double de)
void SetPos (G4ThreeVector xyz)
G4int GetTrackID () const
G4int GetChamberNb () const
G4double GetEdep () const
G4ThreeVector GetPos () const
Public Member Functions inherited from G4VHit
G4VHit ()
virtual ~G4VHit ()
G4bool operator== (const G4VHit &right) const
virtual const std::map
< G4String, G4AttDef > * GetAttDefs () const
virtual std::vector< G4AttValue > * CreateAttValues () const
Private Attributes
G4ThreeVector pos
G4double edep
G4int trackID
G4int chamberNb
Detailed Description
Definition at line 48 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 48 of file ExN02TrackerHit.hh
Constructor & Destructor Documentation
ExN02TrackerHit::ExN02TrackerHit ()
Definition at line 45 of file ExN02TrackerHit.cc.
View newest version in sPHENIX GitHub at line 45 of file ExN02TrackerHit.cc
ExN02TrackerHit::~ExN02TrackerHit ()
Definition at line 49 of file ExN02TrackerHit.cc.
View newest version in sPHENIX GitHub at line 49 of file ExN02TrackerHit.cc
ExN02TrackerHit::ExN02TrackerHit (const ExN02TrackerHit & right)
Definition at line 53 of file ExN02TrackerHit.cc.
View newest version in sPHENIX GitHub at line 53 of file ExN02TrackerHit.cc
References chamberNb, edep, pos, and trackID.
Member Function Documentation
void ExN02TrackerHit::Draw () virtual
Reimplemented from G4VHit.
Definition at line 82 of file ExN02TrackerHit.cc.
View newest version in sPHENIX GitHub at line 82 of file ExN02TrackerHit.cc
References G4VVisManager::Draw(), G4VMarker::filled, G4VVisManager::GetConcreteInstance(), pos, G4VMarker::SetFillStyle(), G4VMarker::SetScreenSize(), and G4Visible::SetVisAttributes().
G4int ExN02TrackerHit::GetChamberNb () const inline
Definition at line 92 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 92 of file ExN02TrackerHit.hh
References chamberNb.
Referenced by MarshaledExN02TrackerHit::marshal4().
G4double ExN02TrackerHit::GetEdep () const inline
Definition at line 93 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 93 of file ExN02TrackerHit.hh
References edep.
Referenced by MarshaledExN02TrackerHit::marshal2().
G4ThreeVector ExN02TrackerHit::GetPos () const inline
Definition at line 94 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 94 of file ExN02TrackerHit.hh
References pos.
Referenced by MarshaledExN02TrackerHit::marshal1().
G4int ExN02TrackerHit::GetTrackID () const inline
Definition at line 91 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 91 of file ExN02TrackerHit.hh
References trackID.
Referenced by MarshaledExN02TrackerHit::marshal3().
void ExN02TrackerHit::operator delete (void * aHit) inline
Definition at line 111 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 111 of file ExN02TrackerHit.hh
References G4Allocator< Type >::FreeSingle().
void * ExN02TrackerHit::operator new (size_t) inline
Definition at line 104 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 104 of file ExN02TrackerHit.hh
References G4Allocator< Type >::MallocSingle().
const ExN02TrackerHit & ExN02TrackerHit::operator= (const ExN02TrackerHit & right)
Definition at line 64 of file ExN02TrackerHit.cc.
View newest version in sPHENIX GitHub at line 64 of file ExN02TrackerHit.cc
References chamberNb, edep, pos, and trackID.
G4bool ExN02TrackerHit::operator== (const ExN02TrackerHit & right) const
Definition at line 75 of file ExN02TrackerHit.cc.
View newest version in sPHENIX GitHub at line 75 of file ExN02TrackerHit.cc
void ExN02TrackerHit::Print (void) virtual
Reimplemented from G4VHit.
Definition at line 99 of file ExN02TrackerHit.cc.
View newest version in sPHENIX GitHub at line 99 of file ExN02TrackerHit.cc
References chamberNb, edep, G4BestUnit, G4cout, G4endl, pos, and trackID.
void ExN02TrackerHit::SetChamberNb (G4int chamb) inline
Definition at line 87 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 87 of file ExN02TrackerHit.hh
References chamberNb.
Referenced by ExN02TrackerSD::ProcessHits(), and MarshaledExN02TrackerHit::unmarshal4().
void ExN02TrackerHit::SetEdep (G4double de) inline
Definition at line 88 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 88 of file ExN02TrackerHit.hh
References edep.
Referenced by ExN02TrackerSD::ProcessHits(), and MarshaledExN02TrackerHit::unmarshal2().
void ExN02TrackerHit::SetPos (G4ThreeVector xyz) inline
Definition at line 89 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 89 of file ExN02TrackerHit.hh
References pos.
Referenced by ExN02TrackerSD::ProcessHits(), and MarshaledExN02TrackerHit::unmarshal1().
void ExN02TrackerHit::SetTrackID (G4int track) inline
Definition at line 86 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 86 of file ExN02TrackerHit.hh
References track, and trackID.
Referenced by ExN02TrackerSD::ProcessHits(), and MarshaledExN02TrackerHit::unmarshal3().
Member Data Documentation
G4int ExN02TrackerHit::chamberNb private
Definition at line 79 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 79 of file ExN02TrackerHit.hh
Referenced by ExN02TrackerHit(), GetChamberNb(), operator=(), Print(), and SetChamberNb().
G4double ExN02TrackerHit::edep private
Definition at line 71 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 71 of file ExN02TrackerHit.hh
Referenced by ExN02TrackerHit(), GetEdep(), operator=(), Print(), and SetEdep().
G4ThreeVector ExN02TrackerHit::pos private
Definition at line 67 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 67 of file ExN02TrackerHit.hh
Referenced by Draw(), ExN02TrackerHit(), GetPos(), operator=(), Print(), and SetPos().
G4int ExN02TrackerHit::trackID private
Definition at line 75 of file ExN02TrackerHit.hh.
View newest version in sPHENIX GitHub at line 75 of file ExN02TrackerHit.hh
Referenced by ExN02TrackerHit(), GetTrackID(), operator=(), Print(), and SetTrackID().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/include/ExN02TrackerHit.hh
geant4/tree/geant4-10.6-release/examples/extended/parallel/TopC/ParN02/src/ExN02TrackerHit.cc