ECCE @ EIC Software: MCTruthConfig Class Reference
MCTruthConfig Class Reference
#include <geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/include/MCTruthConfig.hh>
Public Member Functions
MCTruthConfig ()
virtual ~MCTruthConfig ()
void SetMinE (double e)
G4double GetMinE () const
void SetParticleTypes (std::vector< G4int > &types)
void AddParticleType (G4int type)
std::vector< G4int > & GetParticleTypes ()
void SetCreatorProcesses (std::vector< G4String > &processes)
void AddCreatorProcess (G4String &process)
std::vector< G4String > & GetCreatorProcesses ()
Private Attributes
G4double fMinE
std::vector< G4int > fParticleTypes
std::vector< G4String > fCreatorProcesses
Detailed Description
Definition at line 48 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 48 of file MCTruthConfig.hh
Constructor & Destructor Documentation
MCTruthConfig::MCTruthConfig ()
Definition at line 46 of file MCTruthConfig.cc.
View newest version in sPHENIX GitHub at line 46 of file MCTruthConfig.cc
MCTruthConfig::~MCTruthConfig () virtual
Definition at line 51 of file MCTruthConfig.cc.
View newest version in sPHENIX GitHub at line 51 of file MCTruthConfig.cc
Member Function Documentation
void MCTruthConfig::AddCreatorProcess (G4String & process) inline
Definition at line 65 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 65 of file MCTruthConfig.hh
References fCreatorProcesses.
void MCTruthConfig::AddParticleType (G4int type) inline
Definition at line 60 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 60 of file MCTruthConfig.hh
References fParticleTypes.
Referenced by main().
std::vector<G4String>& MCTruthConfig::GetCreatorProcesses () inline
Definition at line 67 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 67 of file MCTruthConfig.hh
References fCreatorProcesses.
G4double MCTruthConfig::GetMinE () const inline
Definition at line 57 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 57 of file MCTruthConfig.hh
References fMinE.
Referenced by MCTruthTrackingAction::TrackToBeStored().
std::vector<G4int>& MCTruthConfig::GetParticleTypes () inline
Definition at line 61 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 61 of file MCTruthConfig.hh
References fParticleTypes.
Referenced by MCTruthTrackingAction::TrackToBeStored().
void MCTruthConfig::SetCreatorProcesses (std::vector< G4String > & processes) inline
Definition at line 63 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 63 of file MCTruthConfig.hh
References fCreatorProcesses.
void MCTruthConfig::SetMinE (double e) inline
Definition at line 56 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 56 of file MCTruthConfig.hh
References e, and fMinE.
Referenced by main().
void MCTruthConfig::SetParticleTypes (std::vector< G4int > & types) inline
Definition at line 59 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 59 of file MCTruthConfig.hh
References fParticleTypes.
Member Data Documentation
std::vector<G4String> MCTruthConfig::fCreatorProcesses private
Definition at line 74 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 74 of file MCTruthConfig.hh
Referenced by AddCreatorProcess(), GetCreatorProcesses(), and SetCreatorProcesses().
G4double MCTruthConfig::fMinE private
Definition at line 72 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 72 of file MCTruthConfig.hh
Referenced by GetMinE(), and SetMinE().
std::vector<G4int> MCTruthConfig::fParticleTypes private
Definition at line 73 of file MCTruthConfig.hh.
View newest version in sPHENIX GitHub at line 73 of file MCTruthConfig.hh
Referenced by AddParticleType(), GetParticleTypes(), and SetParticleTypes().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/include/MCTruthConfig.hh
geant4/tree/geant4-10.6-release/examples/extended/eventgenerator/HepMC/MCTruth/src/MCTruthConfig.cc