ECCE @ EIC Software: G4INCL::ParticleEntryChannel Class Reference
G4INCL::ParticleEntryChannel Class Reference
#include <geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLParticleEntryChannel.hh>
Public Member Functions
ParticleEntryChannel (Nucleus *n, Particle *p)
virtual ~ParticleEntryChannel ()
void fillFinalState (FinalState *fs)
Public Member Functions inherited from G4INCL::IChannel
IChannel ()
virtual ~IChannel ()
FinalState * getFinalState ()
Private Member Functions
G4bool particleEnters (const G4double theQValueCorrection)
Modify particle that enters the nucleus.
Private Attributes
Nucleus * theNucleus
Particle * theParticle
Detailed Description
Definition at line 49 of file G4INCLParticleEntryChannel.hh.
View newest version in sPHENIX GitHub at line 49 of file G4INCLParticleEntryChannel.hh
Constructor & Destructor Documentation
G4INCL::ParticleEntryChannel::ParticleEntryChannel (Nucleus * n, Particle * p)
Definition at line 45 of file G4INCLParticleEntryChannel.cc.
View newest version in sPHENIX GitHub at line 45 of file G4INCLParticleEntryChannel.cc
G4INCL::ParticleEntryChannel::~ParticleEntryChannel () virtual
Definition at line 49 of file G4INCLParticleEntryChannel.cc.
View newest version in sPHENIX GitHub at line 49 of file G4INCLParticleEntryChannel.cc
Member Function Documentation
void G4INCL::ParticleEntryChannel::fillFinalState (FinalState * fs) virtual
Implements G4INCL::IChannel.
Definition at line 52 of file G4INCLParticleEntryChannel.cc.
View newest version in sPHENIX GitHub at line 52 of file G4INCLParticleEntryChannel.cc
References G4INCL::FinalState::addEnteringParticle(), G4INCL::ProjectileRemnant::computeExcitationEnergyExcept(), G4INCL::Particle::getA(), G4INCL::Particle::getEmissionQValueCorrection(), G4INCL::Particle::getEnergy(), G4INCL::NuclearPotential::INuclearPotential::getFermiEnergy(), G4INCL::Particle::getID(), G4INCL::Particle::getINCLMass(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMomentum(), G4INCL::Particle::getNumberOfKaon(), G4INCL::Nucleus::getPotential(), G4INCL::Nucleus::getProjectileRemnant(), G4INCL::Particle::getS(), G4INCL::ParticleTable::getTableMass, G4INCL::Particle::getTableMass(), G4INCL::Particle::getZ(), INCL_DEBUG, G4INCL::Particle::isKaon(), G4INCL::Particle::isNucleonorLambda(), G4INCL::Nucleus::isNucleusNucleusCollision(), G4INCL::FinalState::makeParticleBelowFermi(), G4INCL::FinalState::makeParticleBelowZero(), particleEnters(), G4INCL::Particle::print(), G4INCL::ProjectileRemnant::removeParticle(), G4INCL::Particle::setNumberOfKaon(), G4INCL::FinalState::setTotalEnergyBeforeInteraction(), theNucleus, and theParticle.
G4bool G4INCL::ParticleEntryChannel::particleEnters (const G4double theQValueCorrection) private
Modify particle that enters the nucleus.
Modify the particle momentum and/or position when the particle enters the nucleus.
Returns
false if the particle enters below 0 total energy.
Definition at line 170 of file G4INCLParticleEntryChannel.cc.
View newest version in sPHENIX GitHub at line 170 of file G4INCLParticleEntryChannel.cc
References G4INCL::Particle::adjustMomentumFromEnergy(), G4INCL::NuclearPotential::INuclearPotential::computePotentialEnergy(), G4INCL::Store::getConfig(), G4INCL::Particle::getCosRPAngle(), G4INCL::Particle::getEnergy(), G4INCL::Particle::getID(), G4INCL::Particle::getKineticEnergy(), G4INCL::Particle::getMass(), G4INCL::Particle::getMomentum(), G4INCL::Particle::getPosition(), G4INCL::Nucleus::getPotential(), G4INCL::Config::getRefraction(), G4INCL::Nucleus::getStore(), INCL_DEBUG, INCL_WARN, G4INCL::ThreeVector::mag2(), max, n, CLHEP::normal(), G4INCL::Particle::print(), r2, G4INCL::Particle::setEnergy(), G4INCL::Particle::setINCLMass(), G4INCL::Particle::setMomentum(), G4INCL::Particle::setPotentialEnergy(), G4INCL::RootFinder::solve(), G4INCL::RootFinder::Solution::success, theNucleus, theParticle, v, and G4INCL::RootFinder::Solution::x.
Referenced by fillFinalState().
Member Data Documentation
Nucleus* G4INCL::ParticleEntryChannel::theNucleus private
Definition at line 66 of file G4INCLParticleEntryChannel.hh.
View newest version in sPHENIX GitHub at line 66 of file G4INCLParticleEntryChannel.hh
Referenced by fillFinalState(), and particleEnters().
Particle* G4INCL::ParticleEntryChannel::theParticle private
Definition at line 67 of file G4INCLParticleEntryChannel.hh.
View newest version in sPHENIX GitHub at line 67 of file G4INCLParticleEntryChannel.hh
Referenced by fillFinalState(), and particleEnters().
The documentation for this class was generated from the following files:
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/include/G4INCLParticleEntryChannel.hh
geant4/tree/geant4-10.6-release/source/processes/hadronic/models/inclxx/incl_physics/src/G4INCLParticleEntryChannel.cc